### ISSUE TITLE
APM tracing is failing due to span being ended twice

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#100072]
### Elasticsearch Version

8.11

### Java Version

_bundled_

### OS Version

mac

### Problem Description

with apm tracing enabled elasticsearch is throwing assertion error when running a `gradlew run` cluster

```» [2023-09-29T16:43:32,698][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [runTask-0] fatal error in thread [elasticsearch[runTask-0][search][T#2]], exiting java.lang.AssertionError
»       at co.elastic.apm.agent.impl.transaction.AbstractSpan.end(AbstractSpan.java:588)
»       at co.elastic.apm.agent.impl.transaction.AbstractSpan.end(AbstractSpan.java:557)
»       at co.elastic.apm.agent.opentelemetry.tracing.OTelSpan.end(OTelSpan.java:122)
»       at org.elasticsearch.telemetry.apm@8.11.0-SNAPSHOT/org.elasticsearch.telemetry.apm.internal.tracing.APMTracer.stopTrace(APMTracer.java:385)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.telemetry.tracing.Tracer.stopTrace(Tracer.java:78)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager.unregister(TaskManager.java:336)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.transport.RequestHandlerRegistry.lambda$processMessageReceived$0(RequestHandlerRegistry.java:67)
»       at org.elasticsearch.base@8.11.0-SNAPSHOT/org.elasticsearch.core.Releasables$3.close(Releasables.java:142)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:44)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.support.ChannelActionListener.lambda$onResponse$0(ChannelActionListener.java:31)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.ActionListener.run(ActionListener.java:368)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:31)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:19)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:51)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:48)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$3.doRun(ActionRunnable.java:73)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
»       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
»       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
»       at java.base/java.lang.Thread.run(Thread.java:1583)
```

APM logs
```
2023-09-29 16:43:32,684 [elasticsearch[runTask-0][search][T#2]] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to 'indices:data/read/search[phase/query]' 00-d5cbef085caa775a48c22d8f6b572d75-de0e50d04211fefd-00 (84003e0) (4)
2023-09-29 16:43:32,684 [elasticsearch[runTask-0][search][T#2]] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - endSpan 'indices:data/read/search[phase/query]' 00-d5cbef085caa775a48c22d8f6b572d75-de0e50d04211fefd-00 (84003e0)
2023-09-29 16:43:32,684 [elasticsearch[runTask-0][search][T#2]] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'GET /{index}/_search' 00-d5cbef085caa775a48c22d8f6b572d75-de0e50d04211fefd-00 (139632d) (11)
2023-09-29 16:43:32,684 [elasticsearch[runTask-0][search][T#2]] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'indices:data/read/search[phase/query]' 00-d5cbef085caa775a48c22d8f6b572d75-de0e50d04211fefd-00 (84003e0) (3)
2023-09-29 16:43:32,684 [elasticsearch[runTask-0][search][T#2]] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'GET /{index}/_search' 00-d5cbef085caa775a48c22d8f6b572d75-de0e50d04211fefd-00 (139632d) (10)
2023-09-29 16:43:32,684 [elasticsearch[runTask-0][search][T#2]] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'indices:data/read/search' 00-d5cbef085caa775a48c22d8f6b572d75-de0e50d04211fefd-00 (bca2bb6) (2)
2023-09-29 16:43:32,684 [elasticsearch[runTask-0][search][T#2]] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'GET /{index}/_search' 00-d5cbef085caa775a48c22d8f6b572d75-de0e50d04211fefd-00 (139632d) (9)
2023-09-29 16:43:32,685 [elasticsearch[runTask-0][search][T#2]] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'indices:data/read/search[phase/query]' 00-d5cbef085caa775a48c22d8f6b572d75-de0e50d04211fefd-00 (84003e0) (2)
2023-09-29 16:43:32,693 [elasticsearch[runTask-0][search][T#2]] DEBUG co.elastic.apm.agent.impl.ActiveStack - Deactivating OTelBridgeContext[{opentelemetry-trace-span-key=OtelSpan['indices:data/read/search[phase/query]' 00-d5cbef085caa775a48c22d8f6b572d75-de0e50d04211fefd-00 (84003e0)]}] on thread 112
2023-09-29 16:43:32,696 [elasticsearch[runTask-0][search][T#3]] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to 'GET /{index}/_search' 00-d5cbef085caa775a48c22d8f6b572d75-de0e50d04211fefd-00 (139632d) (10)
2023-09-29 16:43:32,696 [elasticsearch[runTask-0][search][T#3]] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to 'indices:data/read/search' 00-d5cbef085caa775a48c22d8f6b572d75-de0e50d04211fefd-00 (bca2bb6) (3)
2023-09-29 16:43:32,696 [elasticsearch[runTask-0][search][T#3]] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - endSpan 'indices:data/read/search' 00-d5cbef085caa775a48c22d8f6b572d75-de0e50d04211fefd-00 (bca2bb6)
2023-09-29 16:43:32,696 [elasticsearch[runTask-0][search][T#3]] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'GET /{index}/_search' 00-d5cbef085caa775a48c22d8f6b572d75-de0e50d04211fefd-00 (139632d) (9)
2023-09-29 16:43:32,696 [elasticsearch[runTask-0][search][T#3]] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'indices:data/read/search' 00-d5cbef085caa775a48c22d8f6b572d75-de0e50d04211fefd-00 (bca2bb6) (2)
2023-09-29 16:43:32,696 [elasticsearch[runTask-0][search][T#3]] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'GET /{index}/_search' 00-d5cbef085caa775a48c22d8f6b572d75-de0e50d04211fefd-00 (139632d) (8)
2023-09-29 16:43:32,696 [elasticsearch[runTask-0][search][T#3]] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'GET /{index}/_search' 00-d5cbef085caa775a48c22d8f6b572d75-de0e50d04211fefd-00 (139632d) (7)
2023-09-29 16:43:32,696 [elasticsearch[runTask-0][search][T#3]] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'indices:data/read/search' 00-d5cbef085caa775a48c22d8f6b572d75-de0e50d04211fefd-00 (bca2bb6) (1)
2023-09-29 16:43:32,695 [elasticsearch[runTask-0][search][T#2]] WARN  co.elastic.apm.agent.impl.transaction.AbstractSpan - End has already been called: 'indices:data/read/search[phase/query]' 00-d5cbef085caa775a48c22d8f6b572d75-de0e50d04211fefd-00 (84003e0)
```

when enabeling trace APM logs we get to see the 2 different stacktracing calling endSpan for the same span id
```
2023-09-29 16:54:31,657 [elasticsearch[runTask-0][search][T#1]] WARN  co.elastic.apm.agent.impl.transaction.AbstractSpan - End has already been called: 'indices:data/read/search[phase/query]' 00-c0c729ba17b1f5c9071e27913d3d3e04-e0d2887e8d30da7e-01 (19fd5734)
java.lang.Throwable: null
        at co.elastic.apm.agent.impl.transaction.AbstractSpan.end(AbstractSpan.java:583) ~[elastic-apm-agent-1.43.0.jar:1.43.0]
        at co.elastic.apm.agent.impl.transaction.AbstractSpan.end(AbstractSpan.java:557) ~[elastic-apm-agent-1.43.0.jar:1.43.0]
        at co.elastic.apm.agent.opentelemetry.tracing.OTelSpan.end(OTelSpan.java:122) ~[elastic-apm-agent-1.43.0.jar:1.43.0]
        at org.elasticsearch.telemetry.apm.internal.tracing.APMTracer.stopTrace(APMTracer.java:385) ~[?:?]
        at org.elasticsearch.telemetry.tracing.Tracer.stopTrace(Tracer.java:78) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
        at org.elasticsearch.tasks.TaskManager.unregister(TaskManager.java:336) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
        at org.elasticsearch.transport.RequestHandlerRegistry.lambda$processMessageReceived$0(RequestHandlerRegistry.java:67) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
        at org.elasticsearch.core.Releasables$3.close(Releasables.java:142) ~[elasticsearch-core-8.11.0-SNAPSHOT.jar:?]
        at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:44) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
        at org.elasticsearch.action.support.ChannelActionListener.lambda$onResponse$0(ChannelActionListener.java:31) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
        at org.elasticsearch.action.ActionListener.run(ActionListener.java:368) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
        at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:31) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
        at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:19) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
        at org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:51) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
        at org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:48) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
        at org.elasticsearch.action.ActionRunnable$3.doRun(ActionRunnable.java:73) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]

```

```
2023-09-29 16:54:31,645 [elasticsearch[runTask-0][search][T#1]] TRACE co.elastic.apm.agent.impl.ElasticApmTracer - ending span at
java.lang.RuntimeException: this exception is just used to record where the span has been ended from
at co.elastic.apm.agent.impl.ElasticApmTracer.endSpan(ElasticApmTracer.java:528) ~[elastic-apm-agent-1.43.0.jar:1.43.0]
at co.elastic.apm.agent.impl.transaction.Span.afterEnd(Span.java:288) ~[elastic-apm-agent-1.43.0.jar:1.43.0]
at co.elastic.apm.agent.impl.transaction.AbstractSpan.end(AbstractSpan.java:580) ~[elastic-apm-agent-1.43.0.jar:1.43.0]
at co.elastic.apm.agent.impl.transaction.AbstractSpan.end(AbstractSpan.java:557) ~[elastic-apm-agent-1.43.0.jar:1.43.0]
at co.elastic.apm.agent.opentelemetry.tracing.OTelSpan.end(OTelSpan.java:122) ~[elastic-apm-agent-1.43.0.jar:1.43.0]
at org.elasticsearch.telemetry.apm.internal.tracing.APMTracer.stopTrace(APMTracer.java:394) ~[?:?]
at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:675) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$2(SearchService.java:542) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
at org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:51) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
at org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:48) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
at org.elasticsearch.action.ActionRunnable$3.doRun(ActionRunnable.java:73) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.11.0-SNAPSHOT.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
at java.lang.Thread.run(Thread.java:1583) [?:?]

```

### Steps to Reproduce

start ES with tracing enabled

```
cat ../apm_enable_statefull.gradle 
rootProject {
  if (project.name == 'elasticsearch') {
    afterEvaluate {
      testClusters.matching { it.name == "runTask" }.configureEach {
        setting 'xpack.security.audit.enabled', 'true'
        keystore 'tracing.apm.secret_token', 'YOURPASSWORD'
        setting 'telemetry.metrics.enabled', 'true'
        setting 'tracing.apm.enabled', 'true'

      setting 'tracing.apm.agent.server_url', 'YOUR server' 
      }
    }
  }
}

```

start ES
` ./gradlew run -I ../apm_enable_statefull.gradle `

post a doc

curl --request POST \
  --url http://localhost:9200/xxx2232/_doc \
  --header 'Accept: application/vnd.elasticsearch+json;compatible-with=8' \
  --header 'Authorization: Basic ZWxhc3RpYy1hZG1pbjplbGFzdGljLXBhc3N3b3Jk' \
  --header 'Content-Type: application/vnd.elasticsearch+json;compatible-with=8' \
  --data '{
	"x":123
}'

call a search api
curl --request GET \
  --url http://localhost:9200/xxx2232/_search \
  --header 'Accept: application/vnd.elasticsearch+json;compatible-with=8' \
  --header 'Authorization: Basic ZWxhc3RpYzpwYXNzd29yZA==' \
  --header 'Content-Type: application/vnd.elasticsearch+json;compatible-with=8'

**Comment by williamrandolph** [comment]
I get a different error from this test case when I disable assertions:

```
» [2023-10-02T14:38:02,267][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [runTask-0] fatal error in thread [elasticsearch[runTask-0][search][T#1]], exiting java.lang.ExceptionInInitializerError
»       at co.elastic.apm.agent.profiler.ProfilingActivationListener.beforeActivate(ProfilingActivationListener.java:44)
»       at co.elastic.apm.agent.impl.ActiveStack.triggerActivationListeners(ActiveStack.java:139)
»       at co.elastic.apm.agent.impl.ActiveStack.activate(ActiveStack.java:101)
»       at co.elastic.apm.agent.impl.ElasticApmTracer.activate(ElasticApmTracer.java:867)
»       at co.elastic.apm.agent.opentelemetry.context.OTelContextStorage.attach(OTelContextStorage.java:62)
»       at io.opentelemetry.context@1.17.0/io.opentelemetry.context.Context.makeCurrent(Context.java:202)
»       at org.elasticsearch.telemetry.apm@8.11.0-SNAPSHOT/org.elasticsearch.telemetry.apm.internal.tracing.APMTracer.withScope(APMTracer.java:286)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.telemetry.tracing.Tracer.withScope(Tracer.java:184)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:662)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.search.SearchService.lambda$executeQueryPhase$2(SearchService.java:542)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:51)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:48)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$3.doRun(ActionRunnable.java:73)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
»       at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
»       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
»       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
»       at java.base/java.lang.Thread.run(Thread.java:1583)
»  Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")
»       at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Unavailable.defineClass(ClassInjector.java:1472)
»       at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:284)
»       at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:118)
»       at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:241)
»       at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:148)
»       at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
»       at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6325)
»       at co.elastic.apm.agent.sdk.internal.ThreadUtil.generateVirtualChecker(ThreadUtil.java:65)
»       at co.elastic.apm.agent.sdk.internal.ThreadUtil.<clinit>(ThreadUtil.java:35)
»       ... 20 more
```

I'm not sure if it's the same underlying issue.

**Comment by stu-elastic** [comment]
It looks like there is a stop in `SearchService.executeQueryPhase` that causes the `TaskManager.unregister`'s `tracer.stopTrace` to fail.  That uses an API that gets the current span from the `Context`.  Then, when the task is unregistered, the same span is stopped a second time.  I added some logging and we can see this.

```
» [2023-10-03T15:31:34,669][WARN ][o.e.t.a.i.t.APMTracer    ] [runTask-0] STU: Starting trace [SpanId[task-189]]
» [2023-10-03T15:31:34,680][WARN ][o.e.t.a.i.t.APMTracer    ] [runTask-0] STU: Starting trace [executeQueryPhase]
» [2023-10-03T15:31:34,691][WARN ][o.e.s.SearchService      ] [runTask-0] STU: executeQueryPhase stopTrace [189]
» [2023-10-03T15:31:34,691][WARN ][o.e.t.a.i.t.APMTracer    ] [runTask-0] STU: Finishing current trace from context
» [2023-10-03T15:31:34,691][WARN ][o.e.t.a.i.t.APMTracer    ] [runTask-0] STU: Finishing [OtelSpan['indices:data/read/search[phase/query]' 00-3fabec830e8c0bc1263da7fa26448ae8-90f0063dc8b9c
1ab-00 (de83516)]]
» [2023-10-03T15:31:34,706][WARN ][o.e.t.a.i.t.APMTracer    ] [runTask-0] STU: Finishing trace [SpanId[task-189]][OtelSpan['indices:data/read/search[phase/query]' 00-3fabec830e8c0bc1263da7
fa26448ae8-90f0063dc8b9c1ab-00 (de83516)]]        
```
