### ISSUE TITLE
APM agent fails to start with JDK21

### ISSUE THREAD

**Issue by ldematte** [elastic/elasticsearch#100082]
### Elasticsearch Version

8.11.0

### Java Version

JDK21

### OS Version

macOS 13.5

### Problem Description

When elasticsearch is compiled with JDK21, `elastic-apm-agent` fails to start with this exception:
```
[elastic-apm-agent] ERROR Failed to start agent
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at co.elastic.apm.agent.premain.AgentMain.loadAndInitializeAgent(AgentMain.java:161)
        at co.elastic.apm.agent.premain.AgentMain.init(AgentMain.java:102)
        at co.elastic.apm.agent.premain.AgentMain.premain(AgentMain.java:51)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:560)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:572)
Caused by: java.lang.AssertionError
        at co.elastic.apm.agent.bci.ElasticApmAgent.initAgentBuilder(ElasticApmAgent.java:368)
        at co.elastic.apm.agent.bci.ElasticApmAgent.initInstrumentation(ElasticApmAgent.java:288)
        at co.elastic.apm.agent.bci.ElasticApmAgent.initInstrumentation(ElasticApmAgent.java:177)
        at co.elastic.apm.agent.bci.ElasticApmAgent.initialize(ElasticApmAgent.java:163)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 8 more
```

digging into the apm.log, it's a ByteBuddy problem:

```
2023-09-29 17:51:10,674 [main] ERROR co.elastic.apm.agent.bci.ElasticApmAgent - Exception occurred while applying instrumentation co.elastic.apm.agent.bbwarmup.WarmupInstrumentation
java.lang.IllegalArgumentException: Java 21 (65) is not supported by the current version of Byte Buddy which officially supports Java 20 (64) - update Byte Buddy or set net.bytebuddy.experimental as a VM property
	at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:96) ~[elastic-apm-agent-1.36.0.jar:1.36.0]
	at net.bytebuddy.pool.TypePool$Default.parse(TypePool.java:855) ~[elastic-apm-agent-1.36.0.jar:1.36.0]
	at net.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:841) ~[elastic-apm-agent-1.36.0.jar:1.36.0]
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.access$001(TypePool.java:921) ~[elastic-apm-agent-1.36.0.jar:1.36.0]
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.doResolve(TypePool.java:1019) ~[elastic-apm-agent-1.36.0.jar:1.36.0]
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyResolution.isResolved(TypePool.java:1048) ~[elastic-apm-agent-1.36.0.jar:1.36.0]
	at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$LazyAnnotationValue$ForTypeValue.doResolve(TypePool.java:6415) ~[elastic-apm-agent-1.36.0.jar:1.36.0]
	at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$LazyAnnotationValue.filter(TypePool.java:6276) ~[elastic-apm-agent-1.36.0.jar:1.36.0]
	at net.bytebuddy.description.annotation.AnnotationValue$AbstractBase.filter(AnnotationValue.java:856) ~[elastic-apm-agent-1.36.0.jar:1.36.0]
	at net.bytebuddy.description.annotation.AnnotationDescription$AnnotationInvocationHandler.of(AnnotationDescription.java:317) ~[elastic-apm-agent-1.36.0.jar:1.36.0]
	at net.bytebuddy.pool.TypePool$Default$LazyTypeDescription$LazyAnnotationDescription$Loadable.load(TypePool.java:6245) ~[elastic-apm-agent-1.36.0.jar:1.36.0]
	at co.elastic.apm.agent.bci.ElasticApmAgent.validateAdvice(ElasticApmAgent.java:548) ~[elastic-apm-agent-1.36.0.jar:1.36.0]
	at co.elastic.apm.agent.bci.ElasticApmAgent.getTransformer(ElasticApmAgent.java:473) ~[elastic-apm-agent-1.36.0.jar:1.36.0]
	at co.elastic.apm.agent.bci.ElasticApmAgent.applyAdvice(ElasticApmAgent.java:442) ~[elastic-apm-agent-1.36.0.jar:1.36.0]
	at co.elastic.apm.agent.bci.ElasticApmAgent.initAgentBuilder(ElasticApmAgent.java:363) [elastic-apm-agent-1.36.0.jar:1.36.0]
	at co.elastic.apm.agent.bci.ElasticApmAgent.initInstrumentation(ElasticApmAgent.java:288) [elastic-apm-agent-1.36.0.jar:1.36.0]
	...
```

Passing `-Dnet.bytebuddy.experimental=true` from the bootstrap to the Server JVM options does indeed solve the issue.
This is of course a hack and the long term solution would be to update the elastic APM agent (and ByteBuddy), when a version compatible with JDK21 is available.

### Steps to Reproduce

- Set the JDK to 21
- Enable APM in elasticsearch.yml
- `./gradlew run` 
- Inspect the logs at the very beginning of bootstrap

**Comment by SylvainJuge** [comment]
Hi !

From the stack trace we can see an older version of the agent is used here (1.36.0).

So this is very probably already fixed by https://github.com/elastic/elasticsearch/pull/100064 as the agent has been already updated to the latest version a few days ago.

@ldematte can you try to see if this still happens after the update on `main` ?

**Comment by ldematte** [comment]
Hi! I can confirm that after merging https://github.com/elastic/elasticsearch/pull/100064 and pulling in the new agent version this is fixed - the agent starts correctly without `-Dnet.bytebuddy.experimental=true` on JDK21 as well. 

Thanks!

**Comment by komal540** [comment]
Hi, Is it resolved ?

**Comment by ldematte** [comment]
>I can confirm that after merging https://github.com/elastic/elasticsearch/pull/100064 and pulling in the new agent version this is fixed - the agent starts correctly without -Dnet.bytebuddy.experimental=true on JDK21 as well.

Yes, I was able to confirm @SylvainJuge hypothesis on my machine. The latest version of the agent does not raise the exception anymore.
