### ISSUE TITLE
`index_out_of_bounds_exception` when highlighting "match_only_text" fields

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#100071]
We recently found errors in some of the metrics dashboards that could be narrowed down to highlighting on a "match_only_text" field with a "match_phrae" query. 
This problem only seems to surface with several segments, so I [wrote a test linked in this PR](https://github.com/elastic/elasticsearch/pull/100066) that indexes a larger number of documents and retrieve a larger document size in the request to have a high-enough likelihood to fail.

The highlighter related failure that appears very often when running this is of the form:
```
java.lang.AssertionError: Unexpected ShardFailures: [shard [[ZtI-5CyWTRGpBRbHOMGB4Q][test][0]], reason [org.elasticsearch.transport.RemoteTransportException: [node_s1][127.0.0.1:13303][indices:data/read/search[phase/fetch/id]]
Caused by: org.elasticsearch.search.fetch.FetchPhaseExecutionException: Fetch Failed [Error running fetch phase for doc [14]]
	at org.elasticsearch.search.fetch.FetchPhaseDocsIterator.iterate(FetchPhaseDocsIterator.java:73)
	at org.elasticsearch.search.fetch.FetchPhase.buildSearchHits(FetchPhase.java:170)
	at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:79)
	at org.elasticsearch.search.SearchService.lambda$executeFetchPhase$9(SearchService.java:861)
	at org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:51)
	at org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:48)
	at org.elasticsearch.action.ActionRunnable$3.doRun(ActionRunnable.java:73)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: index_out_of_bounds_exception: Index 7 out of bounds for length 7
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at org.apache.lucene.index.CodecReader$1.document(CodecReader.java:108)
	at org.elasticsearch.search.internal.FieldUsageTrackingDirectoryReader$FieldUsageTrackingLeafReader$2.document(FieldUsageTrackingDirectoryReader.java:150)
	at org.elasticsearch.index.fieldvisitor.StoredFieldLoader$ReaderStoredFieldLoader.advanceTo(StoredFieldLoader.java:182)
	at org.elasticsearch.search.lookup.StoredFieldSourceProvider$LeafStoredFieldSourceProvider.getSource(StoredFieldSourceProvider.java:75)
	at org.elasticsearch.search.lookup.StoredFieldSourceProvider.getSource(StoredFieldSourceProvider.java:38)
	at org.elasticsearch.search.lookup.SearchLookup.getSource(SearchLookup.java:144)
	at org.elasticsearch.index.mapper.extras.MatchOnlyTextFieldMapper$MatchOnlyTextFieldType.lambda$getValueFetcherProvider$2(MatchOnlyTextFieldMapper.java:213)
	at org.elasticsearch.index.mapper.extras.SourceConfirmedTextQuery$RuntimePhraseScorer.computeFreq(SourceConfirmedTextQuery.java:376)
	at org.elasticsearch.index.mapper.extras.SourceConfirmedTextQuery$RuntimePhraseScorer.freq(SourceConfirmedTextQuery.java:368)
	at org.elasticsearch.index.mapper.extras.SourceConfirmedTextQuery$RuntimePhraseScorer$1.matches(SourceConfirmedTextQuery.java:327)
	at org.apache.lucene.search.Weight.matches(Weight.java:90)
	at org.apache.lucene.search.uhighlight.FieldOffsetStrategy.createOffsetsEnumsWeightMatcher(FieldOffsetStrategy.java:147)
	at org.apache.lucene.search.uhighlight.FieldOffsetStrategy.createOffsetsEnumFromReader(FieldOffsetStrategy.java:74)
	at org.apache.lucene.search.uhighlight.MemoryIndexOffsetStrategy.getOffsetsEnum(MemoryIndexOffsetStrategy.java:119)
	at org.apache.lucene.search.uhighlight.FieldHighlighter.highlightFieldForDoc(FieldHighlighter.java:80)
	at org.elasticsearch.lucene.search.uhighlight.CustomFieldHighlighter.highlightFieldForDoc(CustomFieldHighlighter.java:63)
	at org.elasticsearch.lucene.search.uhighlight.CustomUnifiedHighlighter.highlightField(CustomUnifiedHighlighter.java:148)
	at org.elasticsearch.search.fetch.subphase.highlight.DefaultHighlighter.highlight(DefaultHighlighter.java:81)
	at org.elasticsearch.search.fetch.subphase.highlight.HighlightPhase$1.process(HighlightPhase.java:69)
	at org.elasticsearch.search.fetch.FetchPhase$1.nextDoc(FetchPhase.java:164)
	at org.elasticsearch.search.fetch.FetchPhaseDocsIterator.iterate(FetchPhaseDocsIterator.java:70)
```

I'll open a separate issue for the other kind of error that test frequently produces to not mix up the two things.

**Comment by romseygeek** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/100134
