### ISSUE TITLE
ClusterHealthRestCancellationIT.testClusterHealthRestCancellation failed

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#100062]
### CI Link

https://gradle-enterprise.elastic.co/s/mjyqs6uqr7oam

### Repro line

./gradlew ':qa:smoke-test-http:javaRestTest' --tests "org.elasticsearch.http.ClusterHealthRestCancellationIT.testClusterHealthRestCancellation" -Dtests.seed=E99BACA50D51F65 -Dtests.locale=lt -Dtests.timezone=America/Asuncion -Druntime.java=21

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

```

[2023-09-29T09:17:10,678][INFO ][o.e.g.GatewayService     ] [node_s0] recovered [0] indices into cluster_state
[2023-09-29T09:17:10,701][INFO ][o.e.h.n.s.HealthNodeTaskExecutor] [node_s0] Node [{node_s0}{DgYSsEPtQO2s7lqvvLu7Wg}] is selected as the current health node.
[2023-09-29T09:17:10,761][INFO ][o.e.c.m.MetadataIndexTemplateService] [node_s0] adding template [random_index_template] for index patterns [*]
[2023-09-29T09:17:10,784][INFO ][o.e.h.ClusterHealthRestCancellationIT] [testClusterHealthRestCancellation] [ClusterHealthRestCancellationIT#testClusterHealthRestCancellation]: all set up test
[2023-09-29T09:17:10,794][INFO ][o.e.h.ClusterHealthRestCancellationIT] [testClusterHealthRestCancellation] --> sending cluster state request
[2023-09-29T09:17:10,811][INFO ][o.e.t.TaskAssertions     ] [testClusterHealthRestCancellation] --> waiting for task with prefix [cluster:monitor/health] to start
[2023-09-29T09:17:10,819][INFO ][o.e.h.ClusterHealthRestCancellationIT] [testClusterHealthRestCancellation] --> cancelling cluster health request
[2023-09-29T09:17:10,820][INFO ][o.e.h.ClusterHealthRestCancellationIT] [testClusterHealthRestCancellation] --> checking cluster health task cancelled
[2023-09-29T09:17:10,820][INFO ][o.e.t.TaskAssertions     ] [testClusterHealthRestCancellation] --> checking that all tasks with prefix cluster:monitor/health are marked as cancelled
Rgs 29, 2023 9:17:20 AM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[#320,elasticsearch[node_s0][masterService#updateTask][T#1],5,TGRP-ClusterHealthRestCancellationIT]
java.lang.AssertionError: unexpected
	at __randomizedtesting.SeedInfo.seed([E99BACA50D51F65]:0)
	at org.elasticsearch.test.ESTestCase.safeAwait(ESTestCase.java:2012)
	at org.elasticsearch.http.ClusterHealthRestCancellationIT$1.execute(ClusterHealthRestCancellationIT.java:40)
	at org.elasticsearch.cluster.service.MasterService$UnbatchedExecutor.execute(MasterService.java:550)
	at org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1039)
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1004)
	at org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:232)
	at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1626)
	at org.elasticsearch.action.ActionListener.run(ActionListener.java:368)
	at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.run(MasterService.java:1623)
	at org.elasticsearch.cluster.service.MasterService$5.lambda$doRun$0(MasterService.java:1237)
	at org.elasticsearch.action.ActionListener.run(ActionListener.java:368)
	at org.elasticsearch.cluster.service.MasterService$5.doRun(MasterService.java:1216)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CyclicBarrier.dowait(CyclicBarrier.java:259)
	at java.base/java.util.concurrent.CyclicBarrier.await(CyclicBarrier.java:437)
	at org.elasticsearch.test.ESTestCase.safeAwait(ESTestCase.java:2007)
	... 16 more
```

**Comment by masseyke** [comment]
@nik9000 you're able to reproduce this locally? I've tried repeatedly, and it always succeeds for me.

I see from the logs that it's failing because there were no cancellable tasks found of type `cluster:monitor/health` (org.elasticsearch.http.ClusterHealthRestCancellationIT.testClusterHealthRestCancellation(ClusterHealthRestCancellationIT.java:66)). But this is shortly after the call to awaitTaskWithPrefixOnMaster() for that same type. So we know it _was_ running. The only thing I can think of is that some task completely unrelated to the test happened to update the cluster state at that moment? I'm not familiar with this code at all though -- maybe @DaveCTurner has some thoughts about how that could happen?

**Comment by andreidan** [comment]
Retagging this as it refers to the `_cluster/health` API (I was a bit confused :) )

**Comment by alex-spies** [comment]
Happened again today: https://gradle-enterprise.elastic.co/s/cyxpq4tggt34a

**Comment by DaveCTurner** [comment]
I'm wondering if we should `safeAwait(barrier);` before even submitting the cluster health request, so that we can be sure the master service thread is busy first. I mean I suspect that's going to be the eventual fix, but the thing that puzzles me is that we submit the blocking task at `NORMAL` priority _directly_ to the master service, so it shouldn't be possible for the cluster health task to get ahead of it somehow. And yet that's what seems to be happening. I'm adding yet more logging in #103193 to try and confirm this.

**Comment by mark-vieira** [comment]
Hit another failure of this test today (first in a long while) but a different error. Related?

https://gradle-enterprise.elastic.co/s/kozsv35qlwolc/tests/:qa:smoke-test-http:javaRestTest/org.elasticsearch.http.ClusterHealthRestCancellationIT/testClusterHealthRestCancellation

**Comment by iverase** [comment]
https://gradle-enterprise.elastic.co/s/hnlxl7na65w3s

**Comment by astefan** [comment]
On 8.13 today: https://gradle-enterprise.elastic.co/s/nkfmr7gzg6o6q

```
REPRODUCE WITH: ./gradlew ':qa:smoke-test-http:javaRestTest' --tests "org.elasticsearch.http.ClusterHealthRestCancellationIT.testClusterHealthRestCancellation" -Dtests.seed=9A04368ED6A7E7E -Dtests.locale=fi -Dtests.timezone=Europe/Chisinau -Druntime.java=22

org.elasticsearch.http.ClusterHealthRestCancellationIT > testClusterHealthRestCancellation FAILED
    junit.framework.AssertionFailedError: found no cancellable tasks
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.Assert.assertTrue(Assert.java:22)
        at junit.framework.TestCase.assertTrue(TestCase.java:192)
        at org.elasticsearch.test.TaskAssertions.lambda$assertAllCancellableTasksAreCancelled$2(TaskAssertions.java:82)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1255)
        at org.elasticsearch.test.TaskAssertions.assertAllCancellableTasksAreCancelled(TaskAssertions.java:65)
        at org.elasticsearch.http.ClusterHealthRestCancellationIT.testClusterHealthRestCancellation(ClusterHealthRestCancellationIT.java:85)

    org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (remove-index-template [random_index_template]) within 30s
        at org.elasticsearch.cluster.service.MasterService$TaskTimeoutHandler.doRun(MasterService.java:1460)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.lang.Thread.run(Thread.java:1570)

    java.lang.AssertionError: unexpected
        at __randomizedtesting.SeedInfo.seed([9A04368ED6A7E7E]:0)
        at org.elasticsearch.http.ClusterHealthRestCancellationIT$1.execute(ClusterHealthRestCancellationIT.java:57)

        Caused by:
        java.util.concurrent.TimeoutException
            at java.base/java.util.concurrent.CyclicBarrier.dowait(CyclicBarrier.java:259)
            at java.base/java.util.concurrent.CyclicBarrier.await(CyclicBarrier.java:437)
            at org.elasticsearch.http.ClusterHealthRestCancellationIT$1.execute(ClusterHealthRestCancellationIT.java:52)
```

**Comment by jonathan-buttner** [comment]
Another failure on main: https://gradle-enterprise.elastic.co/s/ict5idbdeuk7m/tests/task/:qa:smoke-test-http:javaRestTest/details/org.elasticsearch.http.ClusterHealthRestCancellationIT/testClusterHealthRestCancellation?expanded-stacktrace=WyIwIl0&top-execution=1

I'm going to mute it.

**Comment by DaveCTurner** [comment]
Ok I see the problem, there's a race involving the check for cancellation after starting the task:

```
diff --git a/qa/smoke-test-http/src/javaRestTest/java/org/elasticsearch/http/ClusterHealthRestCancellationIT.java b/qa/smoke-test-http/src/javaRestTest/java/org/elasticsearch/http/ClusterHealthRestCancellationIT.java
index 9d70686c085..c8be24e3c33 100644
--- a/qa/smoke-test-http/src/javaRestTest/java/org/elasticsearch/http/ClusterHealthRestCancellationIT.java
+++ b/qa/smoke-test-http/src/javaRestTest/java/org/elasticsearch/http/ClusterHealthRestCancellationIT.java
@@ -84,6 +84,7 @@ public class ClusterHealthRestCancellationIT extends HttpSmokeTestCase {
         expectThrows(CancellationException.class, future::actionGet);

         logger.info("--> checking cluster health task cancelled");
+        Thread.sleep(1000);
         assertAllCancellableTasksAreCancelled(TransportClusterHealthAction.NAME);

         safeAwait(barrier);
diff --git a/server/src/main/java/org/elasticsearch/action/admin/cluster/health/TransportClusterHealthAction.java b/server/src/main/java/org/elasticsearch/action/admin/cluster/health/TransportClusterHealthAction.java
index fc541fe7108..0ff0ecd90a5 100644
--- a/server/src/main/java/org/elasticsearch/action/admin/cluster/health/TransportClusterHealthAction.java
+++ b/server/src/main/java/org/elasticsearch/action/admin/cluster/health/TransportClusterHealthAction.java
@@ -125,6 +125,12 @@ public class TransportClusterHealthAction extends TransportMasterNodeReadAction<
         final int waitCount,
         final long endTimeRelativeMillis
     ) {
+        try {
+            Thread.sleep(500);
+        } catch (InterruptedException e) {
+            throw new AssertionError(e);
+        }
+
         if (task.notifyIfCancelled(listener)) {
             return;
         }
```

We need to wait until we're blocked on the master service before cancelling the task instead.
