### ISSUE TITLE
ESQL: EsqlActionIT.testGroupedCountAllWithFilter trips circuit breaker

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#100114]
### Description

query `"from test | where data > 1 | stats count(*) by data | sort data"` trips the circuit breaker with a leftover long/double:
```
gradlew ':x-pack:plugin:esql:internalClusterTest' --tests "org.elasticsearch.xpack.esql.action.EsqlActionIT.testGroupedCountAllWithFilter" 
```
```
Request breaker not reset to 0 on node: node_s0
Expected: <0L>
     but: was <64L>
java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
Expected: <0L>
     but: was <64L>
	at __randomizedtesting.SeedInfo.seed([EEE92053B3D5C59D:D958EA3D3273AC80]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.test.InternalTestCluster.lambda$ensureEstimatedStats$41(InternalTestCluster.java:2439)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1196)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1169)
	at org.elasticsearch.test.InternalTestCluster.ensureEstimatedStats(InternalTestCluster.java:2437)
	at org.elasticsearch.test.TestCluster.assertAfterTest(TestCluster.java:92)
	at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2486)
```

**Comment by dnhatn** [comment]
Fixed in #100153
