### ISSUE TITLE
[CI] PercentileDoubleAggregatorFunctionTests testManyInitialFinal failing

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#100104]
```
org.elasticsearch.compute.aggregation.PercentileDoubleAggregatorFunctionTests > testManyInitialFinal FAILED
    java.lang.IllegalStateException: can't read released page
        at __randomizedtesting.SeedInfo.seed([5CA00D8107CC7D58:D71E537C310CE3F2]:0)
        at org.elasticsearch.compute.data.Page.getBlock(Page.java:106)
        at org.elasticsearch.compute.aggregation.AggregatorFunctionTestCase.lambda$assertSimpleOutput$0(AggregatorFunctionTestCase.java:82)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/wdzzgdtc57ga4/tests/:x-pack:plugin:esql:compute:test/org.elasticsearch.compute.aggregation.PercentileDoubleAggregatorFunctionTests/testManyInitialFinal

**Reproduction line:**
```
./gradlew ':x-pack:plugin:esql:compute:test' --tests "org.elasticsearch.compute.aggregation.PercentileDoubleAggregatorFunctionTests.testManyInitialFinal" -Dtests.seed=5CA00D8107CC7D58 -Dtests.locale=fi-FI -Dtests.timezone=America/Juneau -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.compute.aggregation.PercentileDoubleAggregatorFunctionTests&tests.test=testManyInitialFinal

**Failure excerpt:**
```
java.lang.IllegalStateException: can't read released page

  at __randomizedtesting.SeedInfo.seed([5CA00D8107CC7D58:D71E537C310CE3F2]:0)
  at org.elasticsearch.compute.data.Page.getBlock(Page.java:106)
  at org.elasticsearch.compute.aggregation.AggregatorFunctionTestCase.lambda$assertSimpleOutput$0(AggregatorFunctionTestCase.java:82)
  at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
  at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
  at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
  at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
  at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
  at org.elasticsearch.compute.aggregation.AggregatorFunctionTestCase.assertSimpleOutput(AggregatorFunctionTestCase.java:82)
  at org.elasticsearch.compute.operator.ForkingOperatorTestCase.testManyInitialFinal(ForkingOperatorTestCase.java:97)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by stu-elastic** [comment]
dupe of https://github.com/elastic/elasticsearch/issues/100060
