### ISSUE TITLE
ESQL: org.elasticsearch.xpack.esql.action.ManyShardsIT.testConcurrentQueries failing

### ISSUE THREAD

**Issue by ChrisHegarty** [elastic/elasticsearch#100142]
REPRODUCE WITH: ./gradlew 'null' --tests "org.elasticsearch.xpack.esql.action.ManyShardsIT.testConcurrentQueries" -Dtests.seed=9AD8895DAA31433E -Dtests.locale=pl -Dtests.timezone=Asia/Dubai -Druntime.java=19

java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
Expected: <0L>
     but: was <192L>
Expected :<0L>
Actual   :<192L>
<Click to see difference>

	at __randomizedtesting.SeedInfo.seed([9AD8895DAA31433E:D8436A782A56361F]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.test.InternalTestCluster.lambda$ensureEstimatedStats$41(InternalTestCluster.java:2439)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1196)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1169)
	at org.elasticsearch.test.InternalTestCluster.ensureEstimatedStats(InternalTestCluster.java:2437)
	at org.elasticsearch.test.TestCluster.assertAfterTest(TestCluster.java:92)
	at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2486)
	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:590)
	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2327)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)

**Comment by dnhatn** [comment]
I've opened https://github.com/elastic/elasticsearch/pull/100176
