### ISSUE TITLE
[CI] EsqlSpecIT test {ints.WarningWithFromSource} failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#100163]
**Build scan:**
https://gradle-enterprise.elastic.co/s/e2qarzt72fo2u/tests/:x-pack:plugin:esql:qa:server:multi-node:javaRestTest/org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT/test%20%7Bints.WarningWithFromSource%7D
**Reproduction line:**
```
./gradlew ':x-pack:plugin:esql:qa:server:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT" -Dtests.method="test {ints.WarningWithFromSource}" -Dtests.seed=B0AC1F2AF6CEF42E -Dtests.locale=es-US -Dtests.timezone=Pacific/Noumea -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT&tests.test=test%20%7Bints.WarningWithFromSource%7D
**Failure excerpt:**
```
java.lang.AssertionError: Expected a list containing
0: "Line 1:65: evaluation of [to_int(x)] failed, treating result as null. Only first 20 failures recorded."
1: expected "Line 1:65: org.elasticsearch.xpack.ql.QlIllegalArgumentException: [100010000000] out of [integer] range" but was "Line 1:65: org.elasticsearch.xpack.ql.QlIllegalArgumentException: [100730000000] out of [integer] range"

  at __randomizedtesting.SeedInfo.seed([B0AC1F2AF6CEF42E:38F820F0583299D6]:0)
  at org.elasticsearch.test.MapMatcher.assertMap(MapMatcher.java:82)
  at org.elasticsearch.test.MapMatcher.assertMap(MapMatcher.java:65)
  at org.elasticsearch.xpack.esql.qa.rest.RestEsqlTestCase.performRequest(RestEsqlTestCase.java:498)
  at org.elasticsearch.xpack.esql.qa.rest.RestEsqlTestCase.runEsql(RestEsqlTestCase.java:447)
  at org.elasticsearch.xpack.esql.qa.rest.EsqlSpecTestCase.doTest(EsqlSpecTestCase.java:102)
  at org.elasticsearch.xpack.esql.qa.rest.EsqlSpecTestCase.test(EsqlSpecTestCase.java:94)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by mark-vieira** [comment]
Both this an `multipleWarnings` are newly added and seem to be failing a lot so I've muted them both in 81cecfb5aef4aec37ea5406a306d10328413db6a.

**Comment by bpintea** [comment]
Fixed in #100539.

**Comment by nik9000** [comment]
@bpintea could you investigate this one?

**Comment by dnhatn** [comment]
Another instance: https://gradle-enterprise.elastic.co/s/w4woe5qhz72om/

**Comment by kkrik-es** [comment]
Happened again: https://gradle-enterprise.elastic.co/s/3djzij34rxx4s

**Comment by bpintea** [comment]
The new failures aren't the same as those that prompted opening this issue:
* old failure:
```
java.lang.AssertionError: Expected a list containing
0: "Line 1:65: evaluation of [to_int(x)] failed, treating result as null. Only first 20 failures recorded."
1: expected "Line 1:65: org.elasticsearch.xpack.ql.QlIllegalArgumentException: [100010000000] out of [integer] range" but was "Line 1:65: org.elasticsearch.xpack.ql.QlIllegalArgumentException: [100730000000] out of [integer] range"
```

* new failures:
```
org.elasticsearch.xpack.esql.qa.multi_node.EsqlSpecIT > test {ints.WarningWithFromSource#[skip:-8.11.99, reason:ql exceptions were updated in 8.12]} FAILED
    java.lang.AssertionError: Expected a list containing
    0: expected "Line 1:89: evaluation of [to_int(x)] failed, treating result as null. Only first 20 failures recorded." but was <missing>
    1: expected "Line 1:89: org.elasticsearch.xpack.ql.InvalidArgumentException: [100010000000] out of [integer] range" but was <missing>
```

**Comment by bpintea** [comment]
@nhat, is there any work left for #99927?
There's this issue and a [new similar one](https://github.com/elastic/elasticsearch/issues/102982) (besides some other [build failure](https://buildkite.com/elastic/elasticsearch-pull-request/builds/3262#018c367b-6ab2-4031-8b86-f2a9f520d220)) which have the same manifestation as #98719. I'm not positive that these have be the same cause, but it's likely.

**Comment by dnhatn** [comment]
@bpintea I have a theory, but haven't been able to reproduce it. I will have another look at the response headers today.
