### ISSUE TITLE
NullPointerException in DiskThresholdMonitor via RoutingNode.iterator 

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#100201]
### Elasticsearch Version

8.7.1

### Java Version

_bundled_

### OS Version

ess docker image

### Problem Description

It seems to occur on the master when a node has left the cluster.
```
[INFO ][org.elasticsearch.cluster.InternalClusterInfoService] failed to notify [org.elasticsearch.node.Node$$Lambda$4937/0x00000008020ab618@62cb72f] of new cluster info
java.lang.NullPointerException: Cannot invoke "org.elasticsearch.cluster.routing.RoutingNode.iterator()" because the return value of "org.elasticsearch.cluster.routing.RoutingNodes.node(String)" is null
	at org.elasticsearch.cluster.routing.allocation.DiskThresholdMonitor.onNewInfo(DiskThresholdMonitor.java:386) ~[elasticsearch-8.7.1.jar:?]
	at org.elasticsearch.cluster.InternalClusterInfoService$AsyncRefresh.callListeners(InternalClusterInfoService.java:330) ~[elasticsearch-8.7.1.jar:?]
	at org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:102) ~[elasticsearch-core-8.7.1.jar:?]
	at org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:54) ~[elasticsearch-core-8.7.1.jar:?]
	at org.elasticsearch.action.support.RefCountingRunnable.releaseRef(RefCountingRunnable.java:134) ~[elasticsearch-8.7.1.jar:?]
	at org.elasticsearch.action.support.RefCountingRunnable$AcquiredRef.close(RefCountingRunnable.java:77) ~[elasticsearch-8.7.1.jar:?]
	at org.elasticsearch.core.IOUtils.close(IOUtils.java:71) ~[elasticsearch-core-8.7.1.jar:?]
	at org.elasticsearch.core.Releasables.close(Releasables.java:32) ~[elasticsearch-core-8.7.1.jar:?]
	at org.elasticsearch.core.Releasables.closeExpectNoException(Releasables.java:56) ~[elasticsearch-core-8.7.1.jar:?]
	at org.elasticsearch.action.ActionListener$6.run(ActionListener.java:521) ~[elasticsearch-8.7.1.jar:?]
	at org.elasticsearch.action.ActionListener$RunAfterActionListener.onResponse(ActionListener.java:394) ~[elasticsearch-8.7.1.jar:?]
	at org.elasticsearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:49) ~[elasticsearch-8.7.1.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:958) ~[elasticsearch-8.7.1.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.7.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

### Steps to Reproduce

Observed in production, have not reproduced.

**Comment by geekpete** [comment]
Also occurs in 8.9.1.

**Comment by rseldner** [comment]
Hit this on `8.15.2` in Elastic Cloud.  The current master was reporting the following `INFO` level message (logger: `org.elasticsearch.cluster.InternalClusterInfoService`):
```
failed to notify [org.elasticsearch.node.NodeConstruction$$Lambda/0x00007f551bded5f0@1baabe21] of new cluster info
java.lang.NullPointerException: Cannot invoke "org.elasticsearch.cluster.routing.RoutingNode.iterator()" because the return value of "org.elasticsearch.cluster.routing.RoutingNodes.node(String)" is null
	at org.elasticsearch.cluster.routing.allocation.DiskThresholdMonitor.onNewInfo(DiskThresholdMonitor.java:388) ~[elasticsearch-8.15.2.jar:?]
	at org.elasticsearch.cluster.InternalClusterInfoService$AsyncRefresh.callListeners(InternalClusterInfoService.java:330) ~[elasticsearch-8.15.2.jar:?]
	at org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118) ~[elasticsearch-core-8.15.2.jar:?]
	at org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70) ~[elasticsearch-core-8.15.2.jar:?]
	at org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112) ~[elasticsearch-8.15.2.jar:?]
	at org.elasticsearch.core.Releasables.close(Releasables.java:34) ~[elasticsearch-core-8.15.2.jar:?]
	at org.elasticsearch.core.Releasables.closeExpectNoException(Releasables.java:56) ~[elasticsearch-core-8.15.2.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations$2.run(ActionListenerImplementations.java:49) ~[elasticsearch-8.15.2.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:271) ~[elasticsearch-8.15.2.jar:?]
	at org.elasticsearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:39) ~[elasticsearch-8.15.2.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984) ~[elasticsearch-8.15.2.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.15.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
```
Multiple nodes were observed to have left the cluster prior to this NPE

**Comment by ywangd** [comment]
I think this can happen when the node-to-be-replaced (source) leaves the cluster before the corresponding shutdown metadata is removed from the cluster state. 

https://github.com/elastic/elasticsearch/blob/bb93f1f3ce8f1460e48a4b86d3b0fee72b4fa4b1/server/src/main/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdMonitor.java#L381-L389

We should filter out the source node if it is not part of the cluster anymore similar to how we filter out the target node. Based on the history of the changes, I am relabelling to as `:Core/Infra/Node Lifecycle`.
