### ISSUE TITLE
[CI] RestEsqlIT testTextMode failing

### ISSUE THREAD

**Issue by piergm** [elastic/elasticsearch#100257]
**Build scan:**
https://gradle-enterprise.elastic.co/s/clmn25yo7y7lq/tests/:x-pack:plugin:esql:qa:server:single-node:javaRestTest/org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT/testTextMode
**Reproduction line:**
```
./gradlew ':x-pack:plugin:esql:qa:server:single-node:javaRestTest' --tests "org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testTextMode" -Dtests.seed=BD511BAA0D86C1A5 -Dtests.locale=ar-TN -Dtests.timezone=Asia/Tomsk -Druntime.java=19
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT&tests.test=testTextMode
**Failure excerpt:**
```
java.net.ConnectException: Connection refused

  at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:930)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:300)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:303)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
  at org.elasticsearch.test.rest.ESRestTestCase.initClient(ESRestTestCase.java:232)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

  Caused by: java.net.ConnectException: Connection refused

    at sun.nio.ch.Net.pollConnect(Net.java:-2)
    at sun.nio.ch.Net.pollConnectNow(Net.java:672)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
    at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174)
    at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
    at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221)
    at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
    at java.lang.Thread.run(Thread.java:1589)

```

**Comment by bpintea** [comment]
Scan contains:
```
Tests with failures:
 - org.elasticsearch.xpack.esql.qa.single_node.HeapAttackIT.testHugeConcat
 - org.elasticsearch.xpack.esql.qa.single_node.HeapAttackIT.testManyEval
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testTextMode
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testNullInAggs
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testErrorMessageForArrayValuesInParams
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testMetadataFieldsOnMultipleIndices
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testCSVNoHeaderMode
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testErrorMessageForLiteralDateMathOverflowOnNegation
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testGetAnswer
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testErrorMessageForInvalidParams
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testCSVMode
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testErrorMessageForLiteralDateMathOverflow
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testErrorMessageForEmptyParams
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testTSVMode
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testErrorMessageForMissingValueInParams
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testPragmaNotAllowed
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testColumnarMode
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testBasicEsql
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testUseUnknownIndex
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testErrorMessageForInvalidTypeInParams
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testInvalidPragma
 - org.elasticsearch.xpack.esql.qa.single_node.RestEsqlIT.testErrorMessageForMissingTypeInParams
```
so caused by the HeapAttackIT failings, which have been addressed (fixed & muted) by now.
`testTextMode()` itself hasn't been muted and hasn't failed since, so this should be safe to close.
