### ISSUE TITLE
[ML] Anomaly detection job throws errors when not all remote clusters have source data

### ISSUE THREAD

**Issue by wwang500** [elastic/elasticsearch#100311]
### Stack Version: 

8.10.2

### Error:
```
[instance-0000000034] [ccs_using_wildcard_for_both_clusters] error while extracting data
org.elasticsearch.ResourceNotFoundException: [3] remote clusters out of [4] were skipped when performing datafeed search
	at org.elasticsearch.xpack.core.ml.datafeed.extractor.DataExtractor.checkForSkippedClusters(DataExtractor.java:61) ~[?:?]
	at org.elasticsearch.xpack.ml.datafeed.extractor.chunked.ChunkedDataExtractor.executeSearchRequest(ChunkedDataExtractor.java:150) ~[?:?]
	at org.elasticsearch.xpack.ml.datafeed.extractor.chunked.ChunkedDataExtractor$DataSummaryFactory.newAggregatedDataSummary(ChunkedDataExtractor.java:248) ~[?:?]
	at org.elasticsearch.xpack.ml.datafeed.extractor.chunked.ChunkedDataExtractor$DataSummaryFactory.buildDataSummary(ChunkedDataExtractor.java:221) ~[?:?]
	at org.elasticsearch.xpack.ml.datafeed.extractor.chunked.ChunkedDataExtractor.setUpChunkedSearch(ChunkedDataExtractor.java:123) ~[?:?]
	at org.elasticsearch.xpack.ml.datafeed.extractor.chunked.ChunkedDataExtractor.next(ChunkedDataExtractor.java:116) ~[?:?]
	at org.elasticsearch.xpack.ml.datafeed.DatafeedJob.run(DatafeedJob.java:376) ~[?:?]
	at org.elasticsearch.xpack.ml.datafeed.DatafeedJob.runRealtime(DatafeedJob.java:226) ~[?:?]
	at org.elasticsearch.xpack.ml.datafeed.DatafeedRunner$Holder.executeRealTime(DatafeedRunner.java:561) ~[?:?]
	at org.elasticsearch.xpack.ml.datafeed.DatafeedRunner$3.doRun(DatafeedRunner.java:307) ~[?:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983) ~[elasticsearch-8.10.2.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.10.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

### Possible root cause:

https://github.com/elastic/elasticsearch/pull/97731

### Step to reproduce:
1. Deploy three clusters: 
- main_cluster
- remote_cluster_1
- remote_cluster_2

2. From main_cluster, setup remote clusters to remote_cluster_1 and remote_cluster_2
3. In remote_cluster_1,  load some data, in my case, I have dataset named: `gallery-2023`
4. In main_cluster, create an anomaly detection job, configured with the datafeed:
```
"indices": [
      "*:gallery-*"
    ]
```
5. Start ad job, 

**Observerd:**

AD job is in started state, however it did't process data, and In job message, there is an error: `Datafeed is encountering errors extracting data: [3] remote clusters out of [4] were skipped when performing datafeed search`

**Note:**
With the same configure, the job was working fine on stack version 8.9.0. 

- In 8.9.0,  for this settings (multiple remote clusters, only one cluster has the gallery data), the search `GET *:gallery-*/_search` returns:
```
"_clusters": {
    "total": 2,
    "successful": 2,
    "skipped": 0
  },
```

- In 8.10.x,  the same search `GET *:gallery-*/_search`  returns:
```
"_clusters": {
    "total": 2,
    "successful": 1,
    "skipped": 1,
    "details": {
      "remote_cluster_1": {
        "status": "successful",
        "indices": "gallery-*",
        "took": 19,
        "timed_out": false,
        "_shards": {
          "total": 126,
          "successful": 126,
          "skipped": 0,
          "failed": 0
        }
      },
      "remote_cluster_2": {
        "status": "failed",
        "indices": "gallery-*",
        "took": 2,
        "timed_out": false,
        "_shards": {
          "total": 0,
          "successful": 0,
          "skipped": 0,
          "failed": 0
        }
      }
    }
  },
```

**Comment by droberts195** [comment]
Setting `ccs_minimize_roundtrips=false` is a possible workaround for this problem.

Hopefully #100354 will fix it. We should retest once that is merged and then assess whether any further fixes on top are required in the ML datafeed code.
