### ISSUE TITLE
index [.ds-.slm-history-5-2023.10.09-000001] is the write index for data stream [.slm-history-5] and cannot be deleted

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#100536]
### CI Link

https://gradle-enterprise.elastic.co/s/wz3ofquvkhbem/console-log/raw

### Repro line

```
 ./gradlew ':docs:yamlRestTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/query-dsl/simple-query-string-query/line_291}" -Dtests.seed=E12124F261F0BF90 -Dtests.locale=es-US -Dtests.timezone=US/Central -Druntime.java=21
```

### Does it reproduce?

no

### Applicable branches

main

### Failure history

Didn't load.

### Failure excerpt

```

REPRODUCE WITH: ./gradlew ':docs:yamlRestTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/query-dsl/simple-query-string-query/line_291}" -Dtests.seed=E12124F261F0BF90 -Dtests.locale=es-US -Dtests.timezone=US/Central -Druntime.java=21

org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT > test {yaml=reference/query-dsl/simple-query-string-query/line_291} FAILED
    org.elasticsearch.client.ResponseException: method [DELETE], host [http://127.0.0.1:43027], URI [*,-.ds-ilm-history-*?expand_wildcards=open%2Cclosed%2Chidden], status line [HTTP/1.1 400 Bad Request]
    {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"index [.ds-.slm-history-5-2023.10.09-000001] is the write index for data stream [.slm-history-5] and cannot be deleted"}],"type":"illegal_argument_exception","reason":"index [.ds-.slm-history-5-2023.10.09-000001] is the write index for data stream [.slm-history-5] and cannot be deleted"},"status":400}
        at __randomizedtesting.SeedInfo.seed([E12124F261F0BF90:69751B28CF0CD268]:0)
        at app//org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347)
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
        at app//org.elasticsearch.test.rest.ESRestTestCase.wipeAllIndices(ESRestTestCase.java:981)
        at app//org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:729)
        at app//org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:421)
        at java.base@21/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base@21/java.lang.reflect.Method.invoke(Method.java:580)
        at app//com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
```

**Comment by masseyke** [comment]
It looks like an SLM policy runs at exactly midnight, which is where this failure happened. I'll update ESRestTestCase to exclude slm history the same way we do ilm history.
