### ISSUE TITLE
[CI] CoalesceTests classMethod failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#100559]
Just got a bunch of instances of this suite timing out all on Windows agents. Could be a coincidence but seems unlikely.

**Build scan:**
https://gradle-enterprise.elastic.co/s/rvfpi7upehqjk/tests/:x-pack:plugin:esql:test/org.elasticsearch.xpack.esql.expression.function.scalar.nulls.CoalesceTests
**Reproduction line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.esql.expression.function.scalar.nulls.CoalesceTests&tests.test=classMethod
**Failure excerpt:**
```
java.lang.Exception: Suite timeout exceeded (>= 2400000 msec).

  at __randomizedtesting.SeedInfo.seed([546AEE28130887AC]:0)

```

**Comment by dnhatn** [comment]
```
 at java.base/java.security.AccessController.getStackAccessControlContext(Native Method)	
 at java.base/java.security.AccessController.isPrivileged(AccessController.java:754)	
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)	
 at org.apache.lucene.util.RamUsageEstimator.shallowSizeOfInstance(RamUsageEstimator.java:598)	
 at org.elasticsearch.compute.data.IntArrayBlock.ramBytesEstimated(IntArrayBlock.java:96)	
 at org.elasticsearch.compute.data.IntArrayBlock.ramBytesUsed(IntArrayBlock.java:102)	
 at org.elasticsearch.compute.data.BlockFactory.newIntArrayBlock(BlockFactory.java:167)	
 at org.elasticsearch.compute.data.IntBlockBuilder.build(IntBlockBuilder.java:196)	
 at org.elasticsearch.compute.data.IntArrayBlock.filter(IntArrayBlock.java:72)	
 at org.elasticsearch.compute.data.IntArrayBlock.filter(IntArrayBlock.java:20)	
 at org.elasticsearch.xpack.esql.expression.function.scalar.nulls.Coalesce$CoalesceEvaluator.lambda$eval$0(Coalesce.java:151)	
 at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)	
 at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)	
 at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:712)	
 at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)	
 at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)	
 at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)	
 at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)	
 at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)	
 at org.elasticsearch.xpack.esql.expression.function.scalar.nulls.Coalesce$CoalesceEvaluator.eval(Coalesce.java:151)	
 at org.elasticsearch.xpack.esql.expression.function.AbstractFunctionTestCase.lambda$testEvaluateInManyThreads$1(AbstractFunctionTestCase.java:439)	
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)	
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)	
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)	
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)	
 at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by nik9000** [comment]
The looks like this: `RamUsageEstimator.shallowSizeOfInstance(MvOrdering.class)` - which we should just remove. `MvOrdering` is shared.

**Comment by DaveCTurner** [comment]
@ChrisHegarty heads up that I have muted this test with 8e5445b78e3041d038807bfc298ba26eca095d1c, you'll need to revert that commit in your PR.

**Comment by ChrisHegarty** [comment]
Thanks David, I'll sync up with main and remove the mute in this PR. 👍
