### ISSUE TITLE
[CI] DownsampleClusterDisruptionIT testDownsampleIndexWithRollingRestart failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#100653]
**Build scan:**
https://gradle-enterprise.elastic.co/s/fhhlgbhrpcmay/tests/:x-pack:plugin:downsample:internalClusterTest/org.elasticsearch.xpack.downsample.DownsampleClusterDisruptionIT/testDownsampleIndexWithRollingRestart
**Reproduction line:**
```
./gradlew ':x-pack:plugin:downsample:internalClusterTest' --tests "org.elasticsearch.xpack.downsample.DownsampleClusterDisruptionIT.testDownsampleIndexWithRollingRestart" -Dtests.seed=975F427D3DCB26B8 -Dtests.locale=el-GR -Dtests.timezone=US/Central -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.downsample.DownsampleClusterDisruptionIT&tests.test=testDownsampleIndexWithRollingRestart
**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=515, name=Thread-8, state=RUNNABLE, group=TGRP-DownsampleClusterDisruptionIT]

  at __randomizedtesting.SeedInfo.seed([975F427D3DCB26B8:56BB4E492B562868]:0)

  Caused by: java.lang.AssertionError: timed out waiting for green state

    at __randomizedtesting.SeedInfo.seed([975F427D3DCB26B8]:0)
    at org.junit.Assert.fail(Assert.java:88)
    at org.elasticsearch.test.ESIntegTestCase.ensureColor(ESIntegTestCase.java:1003)
    at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:927)
    at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:916)
    at org.elasticsearch.xpack.downsample.DownsampleClusterDisruptionIT$Disruptor.run(DownsampleClusterDisruptionIT.java:112)
    at java.lang.Thread.run(Thread.java:1583)

```

**Comment by davidkyle** [comment]
Another failure although the stack trace and exception are different to the one above

```
java.lang.AssertionError: (No message provided)	
at __randomizedtesting.SeedInfo.seed([91A71F0132BAB65C:504313352427B88C]:0)	
•••
at org.elasticsearch.xpack.downsample.DownsampleClusterDisruptionIT.assertTargetIndex(DownsampleClusterDisruptionIT.java:384)	
at org.elasticsearch.xpack.downsample.DownsampleClusterDisruptionIT.testDownsampleIndexWithRollingRestart(DownsampleClusterDisruptionIT.java:270)	

```

https://gradle-enterprise.elastic.co/s/onjyc4bx35426/tests/task/:x-pack:plugin:downsample:internalClusterTest/details/org.elasticsearch.xpack.downsample.DownsampleClusterDisruptionIT/testDownsampleIndexWithRollingRestart?top-execution=1

**Comment by davidkyle** [comment]
Been busy failing today, another with the same error as in the top post

https://gradle-enterprise.elastic.co/s/maogofmww2al6/tests/task/:x-pack:plugin:downsample:internalClusterTest/details/org.elasticsearch.xpack.downsample.DownsampleClusterDisruptionIT/testDownsampleIndexWithRollingRestart?top-execution=1

**Comment by craigtaverner** [comment]
Failed twice in the last week. I see it was muted in main, but the latest failure is in 8.11, so we should mute it there too.

**Comment by kkrik-es** [comment]
This fails very infrequently, I got one failure out of 100 runs. Looking at the log (attached), the test actually completes after throwing a timeout on checkGreen. It seems that things run somewhat slowly every now and then (not sure why), but just increasing the timeout seems to do the trick.
[log.zip](https://github.com/elastic/elasticsearch/files/14207297/log.zip)

**Comment by mosche** [comment]
Reopening, there's been another failure today:

[elasticsearch / periodic / main / openjdk21 / checkPart2 / java-matrix](https://gradle-enterprise.elastic.co/s/qezer25v7h534)
Test failures:
[DownsampleClusterDisruptionIT » testDownsampleIndexWithRollingRestart](https://gradle-enterprise.elastic.co/s/qezer25v7h534/tests/:x-pack:plugin:downsample:internalClusterTest/org.elasticsearch.xpack.downsample.DownsampleClusterDisruptionIT/testDownsampleIndexWithRollingRestart)

**Comment by mosche** [comment]
Reopening, there's been another failure today:

[elasticsearch / periodic / main / openjdk21 / checkPart2 / java-matrix](https://gradle-enterprise.elastic.co/s/qezer25v7h534)
Test failures:
[DownsampleClusterDisruptionIT » testDownsampleIndexWithRollingRestart](https://gradle-enterprise.elastic.co/s/qezer25v7h534/tests/:x-pack:plugin:downsample:internalClusterTest/org.elasticsearch.xpack.downsample.DownsampleClusterDisruptionIT/testDownsampleIndexWithRollingRestart)

**Comment by iverase** [comment]
And another: https://gradle-enterprise.elastic.co/s/uvr5iikxtxcca

**Comment by kkrik-es** [comment]
Got another repro of the failure (1 in 100), attached log
[log.txt](https://github.com/elastic/elasticsearch/files/14539431/log.txt)
.

**Comment by kkrik-es** [comment]
Node t3 fails to send a notification it completed downsampling due to restarting:

```
[2024-03-08T08:16:25,195][INFO ][o.e.x.d.DownsampleShardIndexer] [node_t3] Downsampling task [downsample-jgogdsletaa-0-197h] on shard [eksulfznuo][0] failed indexing [6595]
[2024-03-08T08:16:25,195][ERROR][o.e.x.d.DownsampleShardPersistentTaskExecutor] [node_t3] Downsampling task [downsample-jgogdsletaa-0-197h non retriable failure [Downsampling task [downsample-jgogdsletaa-0-197h] on shard [eksulfznuo][0] failed indexing []]
[2024-03-08T08:16:25,195][WARN ][o.e.p.AllocatedPersistentTask] [node_t3] task [downsample-jgogdsletaa-0-197h] failed with an exception
org.elasticsearch.xpack.downsample.DownsampleShardIndexerException: Downsampling task [downsample-jgogdsletaa-0-197h] on shard [eksulfznuo][0] failed indexing [6595]
	at org.elasticsearch.xpack.downsample.DownsampleShardIndexer.execute(DownsampleShardIndexer.java:202) ~[main/:?]
	at org.elasticsearch.xpack.downsample.DownsampleShardPersistentTaskExecutor$1.doRun(DownsampleShardPersistentTaskExecutor.java:210) ~[main/:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984) ~[elasticsearch-8.14.0-SNAPSHOT.jar:8.14.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.14.0-SNAPSHOT.jar:8.14.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[2024-03-08T08:16:25,196][WARN ][o.e.p.AllocatedPersistentTask] [node_t3] notification for task [rollup-shard[c]] with id [downsample-jgogdsletaa-0-197h] failed
```

The downsampling task still shows up as pending, though:

```
[2024-03-08T08:16:25,300][INFO ][o.e.c.c.NodeJoinExecutor ] [node_t0] node-join: [{node_t3}{hoDZUnHrSHSnz-jt7SWBdw}{QDXHbahuRCe6_bLqs2NwHg}{node_t3}{127.0.0.1}{127.0.0.1:14592}{d}{8.14.0}{7000099-8503000}] with reason [joining after restart, removed [0ms] ago with reason [disconnected]]
[2024-03-08T08:16:25,313][INFO ][o.e.x.d.TransportDownsampleAction] [node_t0] Task [downsample-jgogdsletaa-0-197h] already exists. Waiting.
[2024-03-08T08:17:24,997][ERROR][o.e.x.d.TransportDownsampleAction] [node_t0] error while waiting for downsampling persistent task
java.lang.IllegalStateException: Timed out when waiting for persistent task after 1m
```

The task says it can't find appropriate nodes:

```
persistent_tasks: {"last_allocation_id":12,"tasks":[{"id":"health-node","task":{"health-node":{"params":{}}},"allocation_id":11,"assignment":{"executor_node":"e9xbw270Q8aC9MDHdGhcFg","explanation":""},"allocation_id_on_last_status_update":9},{"id":"downsample-jgogdsletaa-0-197h","task":{"rollup-shard":{"params":{"downsample_config":{"fixed_interval":"197h"},"rollup_index":"jgogdsletaa","index_start_time_millis":1599674400000,"index_end_time_millis":4292437253384,"shard_id":"[eksulfznuo][0]","metrics":["counter"],"labels":[],"dimensions":["dimension_kw","dimension_long"]},"state":{"status":"STARTED","tsid":""}}},"allocation_id":12,"assignment":{"executor_node":null,"explanation":"no appropriate nodes found for the assignment"},"allocation_id_on_last_status_update":10}]} 
```

After the timeout on ensureGreen is thrown (after 1 minute), it's all good:

```
2024-03-08T08:17:57,716][INFO ][o.e.x.d.DownsampleShardIndexer] [node_t3] Downsampling task [downsample-jgogdsletaa-0-197h on shard [eksulfznuo][0] started
[2024-03-08T08:17:57,728][INFO ][o.e.x.d.DownsampleShardIndexer] [node_t3] Shard [eksulfznuo][0] processed [10000] docs, created [10000] downsample buckets
[2024-03-08T08:17:57,890][INFO ][o.e.c.r.a.AllocationService] [node_t0] current.health="GREEN" message="Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[jgogdsletaa][0]]])." previous.health="RED" reason="shards started [[jgogdsletaa][0]]"
[2024-03-08T08:17:58,027][INFO ][o.e.x.d.DownsampleShardIndexer] [node_t3] Shard [[eksulfznuo][0]] successfully sent [10000], received source doc [10000], indexed downsampled doc [10000], failed [0], took [402ms]
[2024-03-08T08:17:58,028][INFO ][o.e.x.d.DownsampleShardIndexer] [node_t3] Downsampling task [downsample-jgogdsletaa-0-197h on shard [eksulfznuo][0] completed
[2024-03-08T08:17:58,042][INFO ][o.e.x.d.TransportDownsampleAction] [node_t0] Downsampling task [downsample-jgogdsletaa-0-197h completed for shard [eksulfznuo][0]
[2024-03-08T08:17:58,042][INFO ][o.e.x.d.TransportDownsampleAction] [node_t0] All downsampling tasks completed [1]
[2024-03-08
```

I wonder if there's a deadlock where node 3 is waiting for the downsampling task to complete before restarting, while downsampling task is waiting for node 3 to get back..

**Comment by ywangd** [comment]
Failed again https://gradle-enterprise.elastic.co/s/3tezbmvf77qyw/tests/task/:x-pack:plugin:downsample:internalClusterTest/details/org.elasticsearch.xpack.downsample.DownsampleClusterDisruptionIT/testDownsampleIndexWithRollingRestart?top-execution=1
