### ISSUE TITLE
[CI] HeapAttackIT testGroupOnManyLongs failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#100640]
Looks to be consistently failing on Windows.

**Build scan:**
https://gradle-enterprise.elastic.co/s/5tdfiyv7dtveq/tests/:x-pack:plugin:esql:qa:server:single-node:javaRestTest/org.elasticsearch.xpack.esql.qa.single_node.HeapAttackIT/testGroupOnManyLongs
**Reproduction line:**
```
gradlew ':x-pack:plugin:esql:qa:server:single-node:javaRestTest' --tests "org.elasticsearch.xpack.esql.qa.single_node.HeapAttackIT.testGroupOnManyLongs" -Dtests.seed=66A6D752483ECAF6 -Dtests.locale=cs-CZ -Dtests.timezone=Europe/Oslo -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.esql.qa.single_node.HeapAttackIT&tests.test=testGroupOnManyLongs
**Failure excerpt:**
```
java.net.SocketTimeoutException: 300 000 milliseconds timeout on connection http-outgoing-7 [ACTIVE]

  at __randomizedtesting.SeedInfo.seed([66A6D752483ECAF6:1826E48EBDD2450B]:0)
  at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:915)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:300)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:303)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
  at org.elasticsearch.xpack.esql.qa.single_node.HeapAttackIT.query(HeapAttackIT.java:281)
  at org.elasticsearch.xpack.esql.qa.single_node.HeapAttackIT.groupOnManyLongs(HeapAttackIT.java:134)
  at org.elasticsearch.xpack.esql.qa.single_node.HeapAttackIT.testGroupOnManyLongs(HeapAttackIT.java:118)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

  Caused by: java.net.SocketTimeoutException: 300 000 milliseconds timeout on connection http-outgoing-7 [ACTIVE]

    at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387)
    at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:98)
    at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:40)
    at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:261)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:502)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:211)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
    at java.lang.Thread.run(Thread.java:1583)

```

**Comment by ChrisHegarty** [comment]
This is not a blocker. Removing the blocker label.

**Comment by ChrisHegarty** [comment]
I'll look at muting this test on Windows or otherwise increasing the timeout.

**Comment by ChrisHegarty** [comment]
More Windows failures. But why Windows???

[elasticsearch / periodic / platform-support / main / windows-2022 / checkPart2 / platform-support-windows](https://gradle-enterprise.elastic.co/s/zehx5b5zk2xni)
Test failures:
[HeapAttackIT » testGroupOnManyLongs](https://gradle-enterprise.elastic.co/s/zehx5b5zk2xni/tests/:x-pack:plugin:esql:qa:server:single-node:javaRestTest/org.elasticsearch.xpack.esql.qa.single_node.HeapAttackIT/testGroupOnManyLongs)



[elasticsearch / periodic / platform-support / 8.11 / windows-2016 / checkPart2 / platform-support-windows](https://gradle-enterprise.elastic.co/s/zsnp4ub4fhe3g)
Test failures:
[HeapAttackIT » testGroupOnManyLongs](https://gradle-enterprise.elastic.co/s/zsnp4ub4fhe3g/tests/:x-pack:plugin:esql:qa:server:single-node:javaRestTest/org.elasticsearch.xpack.esql.qa.single_node.HeapAttackIT/testGroupOnManyLongs)

**Comment by cbuescher** [comment]
Fwiw there are more failures of this still on 8.11, at least one of them doesn't seem to be on Windows:

https://gradle-enterprise.elastic.co/s/bqpmzfcaomiq4

I'll check if the mute from above is already present on the 8.11 branch since I don't understand why this is still failing.

**Comment by cbuescher** [comment]
I muted this on 8.11 as well with https://github.com/elastic/elasticsearch/pull/101580

**Comment by mark-vieira** [comment]
> This is also failing in 8.11, shall we port the fix or the mute?

If there is a fix, it should be backported.

**Comment by dnhatn** [comment]
We have removed these tests in 8.11 in #103154.

**Comment by idegtiarenko** [comment]
Another failure (not sure what version is that): https://gradle-enterprise.elastic.co/s/vnzxsu4ff62sm/tests/task/:x-pack:plugin:esql:qa:server:heap-attack:javaRestTest/details/org.elasticsearch.xpack.esql.qa.heap_attack.HeapAttackIT/testGroupOnManyLongs?top-execution=1
