### ISSUE TITLE
Red indexes with nullpointer exception

### ISSUE THREAD

**Issue by anjanpathak** [elastic/elasticsearch#10068]
We are having problem while serving query. We were running ES 1.2.1 on Cent OS installed as RPM package and suddenly started getting errors while querying. The log showed this:

    [2015-03-09 18:35:25,102][INFO ][cluster.metadata         ] [Morpheus] [thedealspoint] update_mapping [publicDeals] (dynamic)
    [2015-03-09 18:35:25,131][WARN ][index.engine.internal    ] [Morpheus] [thedealspoint][0] failed engine [refresh failed]
    [2015-03-09 18:35:25,162][WARN ][cluster.action.shard     ] [Morpheus] [thedealspoint][0] sending failed shard for [thedealspoint][0], node[Sa7pUWi2SNmVSL22U4eITw], [P], s[STARTED], indexUUID [v-u_MHhfQMyTbZ6-_XqH0w], reason [engine failure, message [refresh failed][NullPointerException[null]]]
    [2015-03-09 18:35:25,163][WARN ][cluster.action.shard     ] [Morpheus] [thedealspoint][0] received shard failed for [thedealspoint][0], node[Sa7pUWi2SNmVSL22U4eITw], [P], s[STARTED], indexUUID [v-u_MHhfQMyTbZ6-_XqH0w], reason [engine failure, message [refresh failed][NullPointerException[null]]]
    [2015-03-09 18:35:26,842][DEBUG][action.search.type       ] [Morpheus] All shards failed for phase: [query_fetch]
    [2015-03-09 18:35:34,371][DEBUG][action.search.type       ] [Morpheus] All shards failed for phase: [query_fetch]
    [2015-03-09 18:35:34,395][DEBUG][action.search.type       ] [Morpheus] All shards failed for phase: [query_fetch]
    [20

Our setup was default one node installation with memory increased and ES was running without any maintenance for almost a year now. We felt marvel was taking too much space and hence cleared up the marvel indexes. We also deleted our own index and did a fresh indexing. But there was no luck. Things work for few queries and then fails with the same message above. Ultimately unzipped latest ES version (elasticsearch-1.4.4) on a new directory. Started with default settings and did again fresh indexing (Our content is in MySQL and ES is used as search engine). Things work for few queries and then the shard gets unassigned after a while. The error message is shown below:

[vantage@vc-prod elasticsearch-1.4.4]$ bin/elasticsearch

    [2015-03-11 18:46:17,904][INFO ][node                     ] [Doctor Strange] version[1.4.4], pid[13798], build[c88f77f/2015-02-19T13:05:36Z]
    [2015-03-11 18:46:17,905][INFO ][node                     ] [Doctor Strange] initializing ...
    [2015-03-11 18:46:17,911][INFO ][plugins                  ] [Doctor Strange] loaded [], sites []
    [2015-03-11 18:46:21,450][INFO ][node                     ] [Doctor Strange] initialized
    [2015-03-11 18:46:21,450][INFO ][node                     ] [Doctor Strange] starting ...
    [2015-03-11 18:46:21,626][INFO ][transport                ] [Doctor Strange] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/128.199.143.152:9300]}
    [2015-03-11 18:46:21,700][INFO ][discovery                ] [Doctor Strange] elasticsearch/2bQbRn93SOeDdmDLHijwBg
    [2015-03-11 18:46:25,482][INFO ][cluster.service          ] [Doctor Strange] new_master [Doctor Strange][2bQbRn93SOeDdmDLHijwBg][vc-prod][inet[/128.199.143.152:9300]], reason: zen-disco-join (elected_as_master)
    [2015-03-11 18:46:25,519][INFO ][http                     ] [Doctor Strange] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/128.199.143.152:9200]}
    [2015-03-11 18:46:25,520][INFO ][node                     ] [Doctor Strange] started
    [2015-03-11 18:46:26,459][INFO ][gateway                  ] [Doctor Strange] recovered [2] indices into cluster_state
    [2015-03-11 18:46:26,639][DEBUG][action.search.type       ] [Doctor Strange] All shards failed for phase: [query_fetch]
    [2015-03-11 18:46:26,639][DEBUG][action.search.type       ] [Doctor Strange] All shards failed for phase: [query_fetch]
    [2015-03-11 18:46:26,862][WARN ][indices.cluster          ] [Doctor Strange] [thedealspoint][0] failed to start shard
    org.elasticsearch.index.gateway.IndexShardGatewayRecoveryException: [thedealspoint][0] failed recovery
        at org.elasticsearch.index.gateway.IndexShardGatewayService$1.run(IndexShardGatewayService.java:185)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: org.elasticsearch.index.engine.FlushFailedEngineException: [thedealspoint][0] Flush failed
        at org.elasticsearch.index.engine.internal.InternalEngine.flush(InternalEngine.java:926)
        at org.elasticsearch.index.shard.service.InternalIndexShard.performRecoveryFinalization(InternalIndexShard.java:749)
        at org.elasticsearch.index.gateway.local.LocalIndexShardGateway.recover(LocalIndexShardGateway.java:291)
        at org.elasticsearch.index.gateway.IndexShardGatewayService$1.run(IndexShardGatewayService.java:132)
        ... 3 more
    Caused by: java.lang.NullPointerException
        at org.elasticsearch.search.suggest.completion.Completion090PostingsFormat$CompletionLookupProvider.parsePayload(Completion090PostingsFormat.java:337)
        at org.elasticsearch.search.suggest.completion.AnalyzingCompletionLookupProvider$CompletionPostingsConsumer.addPosition(AnalyzingCompletionLookupProvider.java:189)
        at org.elasticsearch.search.suggest.completion.Completion090PostingsFormat$GroupedPostingsConsumer.addPosition(Completion090PostingsFormat.java:188)
        at org.apache.lucene.index.FreqProxTermsWriterPerField.flush(FreqProxTermsWriterPerField.java:488)
        at org.apache.lucene.index.FreqProxTermsWriter.flush(FreqProxTermsWriter.java:80)
        at org.apache.lucene.index.DefaultIndexingChain.flush(DefaultIndexingChain.java:114)
        at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:439)
        at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:513)
        at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:624)
        at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:2949)
        at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3104)
        at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3071)
        at org.elasticsearch.index.engine.internal.InternalEngine.flush(InternalEngine.java:916)
        ... 6 more
    [2015-03-11 18:46:26,890][WARN ][cluster.action.shard     ] [Doctor Strange] [thedealspoint][0] sending failed shard for [thedealspoint][0], node[2bQbRn93SOeDdmDLHijwBg], [P], s[INITIALIZING], indexUUID [vjORGaDpSsKPcGddR2ELdg], reason [Failed to start shard, message [IndexShardGatewayRecoveryException[[thedealspoint][0] failed recovery]; nested: FlushFailedEngineException[[thedealspoint][0] Flush failed]; nested: NullPointerException; ]]
    [2015-03-11 18:46:26,890][WARN ][cluster.action.shard     ] [Doctor Strange] [thedealspoint][0] received shard failed for [thedealspoint][0], node[2bQbRn93SOeDdmDLHijwBg], [P], s[INITIALIZING], indexUUID [vjORGaDpSsKPcGddR2ELdg], reason [Failed to start shard, message [IndexShardGatewayRecoveryException[[thedealspoint][0] failed recovery]; nested: FlushFailedEngineException[[thedealspoint][0] Flush failed]; nested: NullPointerException; ]]
    [2015-03-11 18:46:28,818][DEBUG][action.search.type       ] [Doctor Strange] All shards failed for phase: [query_fetch]
    [2015-03-11 18:46:30,173][DEBUG][action.search.type       ] [Doctor Strange] All shards failed for phase: [query_fetch]
    [2015-03-11 18:46:33,339][DEBUG][action.search.type       ] [Doctor Strange] All shards failed for phase: [query_fetch]

-----------------------------------
Ultimately we created a completely new CentOS instance, installed ES and did a fresh installation and indexing. Things are working so far but we would like to get to the bottom of the null pointer issue and also move to the old installation if possible. 

Thanks, 
Anjan

**Comment by clintongormley** [comment]
Hi @anjanpathak 

I see that you're using the completion suggester.  I wonder if you have two fields with the same name in two different types in the same index, one mapped as a completion field and one not?  In your new installation, are you still using the completion suggester?  It may also be a bug that has already been fixed.

**Comment by clintongormley** [comment]
Hi @anjanpathak 

Any more info here?

**Comment by dakrone** [comment]
Closing since we have not heard back in over 6 months.
