### ISSUE TITLE
[CI] CcsCommonYamlTestSuiteIT test {p0=search.vectors/60_dense_vector_dynamic_mapping/Dynamically created dense vector fields still require the number of dims to match} failing

### ISSUE THREAD

**Issue by kkrik-es** [elastic/elasticsearch#100822]
**Build scan:**
https://gradle-enterprise.elastic.co/s/gnrevr6btxwsu/tests/:qa:ccs-common-rest:yamlRestTest/org.elasticsearch.test.rest.yaml.CcsCommonYamlTestSuiteIT/test%20%7Bp0=search.vectors%2F60_dense_vector_dynamic_mapping%2FDynamically%20created%20dense%20vector%20fields%20still%20require%20the%20number%20of%20dims%20to%20match%7D
**Reproduction line:**
```
./gradlew ':qa:ccs-common-rest:yamlRestTest' --tests "org.elasticsearch.test.rest.yaml.CcsCommonYamlTestSuiteIT" -Dtests.method="test {p0=search.vectors/60_dense_vector_dynamic_mapping/Dynamically created dense vector fields still require the number of dims to match}" -Dtests.seed=B27FF7F92187F0B8 -Dtests.locale=ca -Dtests.timezone=Europe/Rome -Druntime.java=17
```

**Applicable branches:**
8.11

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.test.rest.yaml.CcsCommonYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dsearch.vectors/60_dense_vector_dynamic_mapping/Dynamically%20created%20dense%20vector%20fields%20still%20require%20the%20number%20of%20dims%20to%20match%7D
**Failure excerpt:**
```
java.lang.AssertionError: Failure at [search.vectors/60_dense_vector_dynamic_mapping:165]: field [test-map-dense-vector.mappings.properties.my_field.dims] is null

  at __randomizedtesting.SeedInfo.seed([B27FF7F92187F0B8:3A2BC8238F7B9D40]:0)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:582)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:534)
  at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(null:-1)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:39)
  at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:39)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.lang.AssertionError: field [test-map-dense-vector.mappings.properties.my_field.dims] is null

    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertNotNull(Assert.java:712)
    at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:78)
    at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:562)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:534)
    at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(null:-1)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:568)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:39)
    at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:39)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by kkrik-es** [comment]
I also see the following in [logs](https://gradle-enterprise.elastic.co/s/gnrevr6btxwsu/console-log?page=12):

```
1> [2023-10-13T12:26:24,983][INFO ][o.e.c.m.MetadataCreateIndexService] [remote_cluster-0] failed on parsing mappings on index creation [bad-dynamic-template-index] org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping: dynamic template [bad_dynamic_template] has invalid content [{"match":"*dense_vector*","mapping":{"dims":5000,"index":true,"similarity":"cosine","type":"dense_vector"}}], attempted to validate it with the following match_mapping_type: [object, string, long, double, boolean, date, binary]	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.mapper.MapperService.parseMapping(MapperService.java:555)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.mapper.MapperService.doMerge(MapperService.java:517)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:404)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.updateIndexMappingsAndBuildSortOrder(MetadataCreateIndexService.java:1340)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.lambda$applyCreateIndexWithTemporaryService$2(MetadataCreateIndexService.java:472)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:732)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexWithTemporaryService(MetadataCreateIndexService.java:470)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequestWithV1Templates(MetadataCreateIndexService.java:593)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:420)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:299)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$UnbatchedExecutor.execute(MasterService.java:550)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1039)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1004)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:232)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1626)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.ActionListener.run(ActionListener.java:368)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.run(MasterService.java:1623)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$5.lambda$doRun$0(MasterService.java:1237)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.ActionListener.run(ActionListener.java:368)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$5.doRun(MasterService.java:1216)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)	
  1> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)	
  1> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)	
  1> 	at java.base/java.lang.Thread.run(Thread.java:833)	
  1> Caused by: java.lang.IllegalArgumentException: dynamic template [bad_dynamic_template] has invalid content [{"match":"*dense_vector*","mapping":{"dims":5000,"index":true,"similarity":"cosine","type":"dense_vector"}}], attempted to validate it with the following match_mapping_type: [object, string, long, double, boolean, date, binary]	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.mapper.RootObjectMapper.validateDynamicTemplate(RootObjectMapper.java:339)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.mapper.RootObjectMapper.processField(RootObjectMapper.java:468)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.mapper.RootObjectMapper.parse(RootObjectMapper.java:412)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.mapper.MappingParser.parse(MappingParser.java:116)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.mapper.MapperService.parseMapping(MapperService.java:553)	
  1> 	... 24 more	
  1> Caused by: org.elasticsearch.index.mapper.MapperParsingException: The number of dimensions for field [__dynamic__bad_dynamic_template] should be in the range [1, 4096] but was [5000]	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.mapper.vectors.DenseVectorFieldMapper$Builder.lambda$new$4(DenseVectorFieldMapper.java:111)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.mapper.FieldMapper$Parameter.parse(FieldMapper.java:794)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.mapper.FieldMapper$Builder.parse(FieldMapper.java:1388)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.mapper.FieldMapper$TypeParser.parse(FieldMapper.java:1465)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.mapper.FieldMapper$TypeParser.parse(FieldMapper.java:1422)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.mapper.RootObjectMapper.lambda$validateDynamicTemplate$1(RootObjectMapper.java:324)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.mapper.RootObjectMapper.validate(RootObjectMapper.java:355)	
  1> 	at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.mapper.RootObjectMapper.validateDynamicTemplate(RootObjectMapper.java:321)
```

**Comment by benwtrent** [comment]
Those logs are from an earlier test `If we set dynamic templates to astronomically high or low dim counts, we get a mapping error`. So I think those are OK.

This test failure looks exactly like: https://github.com/elastic/elasticsearch/issues/100502

But it doesn't have my trace logging turned on!!!

**Comment by benwtrent** [comment]
Ah, because its in 8.11, my trace logging is only on main :(. I will backport my logging & close this issue in preference to the existing failure.

FWIW, the failure is indeed the same as the original issue:

```
1> [2023-10-13T12:28:27,267][INFO ][o.e.t.r.y.CcsCommonYamlTestSuiteIT] [test] Stash dump on test failure [{ |  
-- | --
  | 1>   "stash" : { |  
  | 1>     "body" : { |  
  | 1>       "test-map-dense-vector" : { |  
  | 1>         "mappings" : { |  
  | 1>           "properties" : { |  
  | 1>             "my_field" : { |  
  | 1>               "type" : "dense_vector", |  
  | 1>               "index" : true, |  
  | 1>               "similarity" : "cosine" |  
  | 1>             } |  
  | 1>           } |  
  | 1>         } |  
  | 1>       } |  
  | 1>     } |  
  | 1>   } |  
  | 1> }]
```

But we see in the logging that the mapping gets updated.
