### ISSUE TITLE
TimeBasedUUIDGenerator relies on getMacAddress which doesn't work in Azure WebJob

### ISSUE THREAD

**Issue by bzbetty** [elastic/elasticsearch#10099]
Trying to penny pinch in Azure by running Elastic Search as a WebJob.

Azure Websites are fairly locked down and don't allow you to enumerate network addresses (at least that's my theory).  I assumed this wouldn't be needed if I bind to a specific IP but it appears the TimeBasedUUIDGenerator also uses the machines Mac Address.

[03/15/2015 23:56:11 > 6e43bd: ERR ] Exception in thread "main" java.lang.Error: IP Helper Library GetIfTable function failed
[03/15/2015 23:56:11 > 6e43bd: ERR ] 	at java.net.NetworkInterface.getAll(Native Method)
[03/15/2015 23:56:11 > 6e43bd: ERR ] 	at java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:334)
[03/15/2015 23:56:11 > 6e43bd: ERR ] 	at org.elasticsearch.common.MacAddressProvider.getMacAddress(MacAddressProvider.java:35)
[03/15/2015 23:56:11 > 6e43bd: ERR ] 	at org.elasticsearch.common.MacAddressProvider.getSecureMungedAddress(MacAddressProvider.java:67)
[03/15/2015 23:56:11 > 6e43bd: ERR ] 	at org.elasticsearch.common.TimeBasedUUIDGenerator.<clinit>(TimeBasedUUIDGenerator.java:41)
[03/15/2015 23:56:11 > 6e43bd: ERR ] 	at org.elasticsearch.common.Strings.<clinit>(Strings.java:48)
[03/15/2015 23:56:11 > 6e43bd: ERR ] 	at org.elasticsearch.common.settings.ImmutableSettings$Builder.replacePropertyPlaceholders(ImmutableSettings.java:1063)
[03/15/2015 23:56:11 > 6e43bd: ERR ] 	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareSettings(InternalSettingsPreparer.java:53)
[03/15/2015 23:56:11 > 6e43bd: ERR ] 	at org.elasticsearch.bootstrap.Bootstrap.initialSettings(Bootstrap.java:106)
[03/15/2015 23:56:11 > 6e43bd: ERR ] 	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:177)
[03/15/2015 23:56:11 > 6e43bd: ERR ] 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)

Replication Instructions
* Download elastic search zip file
* Add a batch file to the root that contains the following
set ES_MIN_MEM=32m
set ES_MAX_MEM=500m
bin\elasticsearch.bat 
* Create a website in Azure, go to the web jobs tab and upload the zip file
* Open up the log for the webjob to view its output.

**Comment by clintongormley** [comment]
@mikemccand anything we can do here? I'm guessing the MAC address is fairly important when generating UUIDs :)

**Comment by mikemccand** [comment]
Actually this is pretty easy to fix @clintongormley: we already catch and `logger.warn` `SocketException` if there are problems getting the mac address, I can widen that to any `Throwable`.  I'll open a PR.

Still it's likely there are other problems with running ES in a WebJob environment...
