### ISSUE TITLE
[CI] DesiredNodesStatusIT testIdempotentUpdateWithUpdatedStatus failing

### ISSUE THREAD

**Issue by arteam** [elastic/elasticsearch#100967]
**Build scan:**
https://gradle-enterprise.elastic.co/s/cw7boswhuri7g/tests/:server:internalClusterTest/org.elasticsearch.cluster.DesiredNodesStatusIT/testIdempotentUpdateWithUpdatedStatus
**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.cluster.DesiredNodesStatusIT.testIdempotentUpdateWithUpdatedStatus" -Dtests.seed=CC6CBC7BC3CFCC3F -Dtests.locale=hr -Dtests.timezone=America/Dawson_Creek -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.cluster.DesiredNodesStatusIT&tests.test=testIdempotentUpdateWithUpdatedStatus
**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=1077, name=elasticsearch[node_t6][clusterApplierService#updateTask][T#1], state=RUNNABLE, group=TGRP-DesiredNodesStatusIT]

  at __randomizedtesting.SeedInfo.seed([CC6CBC7BC3CFCC3F:D4F44694455DBA8C]:0)

  Caused by: java.lang.AssertionError: (No message provided)

    at __randomizedtesting.SeedInfo.seed([CC6CBC7BC3CFCC3F]:0)
    at org.elasticsearch.discovery.PeerFinder.closePeers(PeerFinder.java:182)
    at org.elasticsearch.cluster.coordination.Coordinator.onClusterStateApplied(Coordinator.java:415)
    at org.elasticsearch.cluster.coordination.Coordinator.lambda$handleApplyCommit$8(Coordinator.java:403)
    at org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.lambda$map$0(ActionListenerImplementations.java:108)
    at org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:89)
    at org.elasticsearch.cluster.service.ClusterApplierService$ClusterApplyActionListener.onResponse(ClusterApplierService.java:598)
    at org.elasticsearch.cluster.service.ClusterApplierService$ClusterApplyActionListener.onResponse(ClusterApplierService.java:569)
    at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:439)
    at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:916)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:217)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:183)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.lang.Thread.run(Thread.java:1583)

```

**Comment by arteam** [comment]
The test failures seems to be cluster coordination related, not much for the desired nodes API.

**Comment by fcofdez** [comment]
This should be fixed by https://github.com/elastic/elasticsearch/pull/100986
