### ISSUE TITLE
[CI] EvalOperatorTests testSimpleCircuitBreaking failing

### ISSUE THREAD

**Issue by quux00** [elastic/elasticsearch#100984]
Fails on main 

./gradlew ':x-pack:plugin:esql:compute:test' --tests "org.elasticsearch.compute.operator.EvalOperatorTests.testSimpleCircuitBreaking" -Dtests.seed=A6DFC03BA45C0ACD -Dtests.locale=zh-SG -Dtests.timezone=Asia/Makassar -Druntime.java=21

**Build scan:**
https://gradle-enterprise.elastic.co/s/7d5w746m45pie/tests/:x-pack:plugin:esql:compute:test/org.elasticsearch.compute.operator.EvalOperatorTests/testSimpleCircuitBreaking
**Reproduction line:**
```
./gradlew ':x-pack:plugin:esql:compute:test' --tests "org.elasticsearch.compute.operator.EvalOperatorTests.testSimpleCircuitBreaking" -Dtests.seed=A6DFC03BA45C0ACD -Dtests.locale=zh-SG -Dtests.timezone=Asia/Makassar -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.compute.operator.EvalOperatorTests&tests.test=testSimpleCircuitBreaking
**Failure excerpt:**
```
junit.framework.AssertionFailedError: Expected exception CircuitBreakingException but no exception was thrown

  at __randomizedtesting.SeedInfo.seed([A6DFC03BA45C0ACD:B24F743EE22EEFA]:0)
  at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2864)
  at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2850)
  at org.elasticsearch.compute.operator.OperatorTestCase.testSimpleCircuitBreaking(OperatorTestCase.java:100)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by luigidellaquila** [comment]
This seems an unfortunate coincidence: the randomized values result in a particularly big value for [smallEnoughToCircuitBreak()](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/operator/OperatorTestCase.java#L93) (6300 in a range from 1 to 8000) and a particularly small [input](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/operator/OperatorTestCase.java#L95) (1044 in a range from 1000 to 10.000). 
I think we just have to lower the `smallEnoughToCircuitBreak()` value a bit, unless there is some specific calculation that I ignore behind these numbers. @nik9000 @ChrisHegarty any clue?

**Comment by luigidellaquila** [comment]
I'm lowering it to low-risk in the meantime

**Comment by maxhniebergall** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/ry2jb4vy2dfu6/tests/task/:x-pack:plugin:esql:compute:test/details/org.elasticsearch.compute.operator.EvalOperatorTests/testSimpleCircuitBreaking

`
./gradlew ':x-pack:plugin:esql:compute:test' --tests "org.elasticsearch.compute.operator.EvalOperatorTests.testSimpleCircuitBreaking" -Dtests.seed=6C2935A89B42F0F7 -Dtests.locale=zh-Hant-TW -Dtests.timezone=America/Nome -Druntime.java=21
`
