### ISSUE TITLE
[CI] SnapshotsStressTestsIT failure

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#101029]
### CI Link

https://gradle-enterprise.elastic.co/s/q7czw7twlsxik

### Repro line

`':server:internalClusterTest' --tests "org.elasticsearch.snapshots.SnapshotStressTestsIT.testRandomActivities" -Dtests.seed=F1980E360247D5B1 -Dtests.locale=ar-LY -Dtests.timezone=Chile/Continental -Druntime.java=21`

### Does it reproduce?

No

### Applicable branches

main

### Failure excerpt

```
    java.lang.AssertionError: java.lang.AssertionError: java.nio.file.NoSuchFileException: /home/davidturner/src/elasticsearch/server/build/testrun/internalClusterTest/temp/org.elasticsearch.snapshots.SnapshotStressTestsIT_F1980E360247D5B1-001/tempDir-002/repos/PylHhYAhiy/indices/OANV69t0QOCAiQkr30IfHw/2/index--feK6pXDR9e7yalgyGFAEg
        at org.elasticsearch.repositories.blobstore.BlobStoreTestUtil.assertConsistency(BlobStoreTestUtil.java:94)
        at org.elasticsearch.snapshots.AbstractSnapshotIntegTestCase.lambda$assertRepoConsistency$1(AbstractSnapshotIntegTestCase.java:153)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.elasticsearch.snapshots.AbstractSnapshotIntegTestCase.assertRepoConsistency(AbstractSnapshotIntegTestCase.java:147)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
        at java.base/java.lang.Thread.run(Thread.java:1583)

        Caused by:
        java.lang.AssertionError: java.nio.file.NoSuchFileException: /home/davidturner/src/elasticsearch/server/build/testrun/internalClusterTest/temp/org.elasticsearch.snapshots.SnapshotStressTestsIT_F1980E360247D5B1-001/tempDir-002/repos/PylHhYAhiy/indices/OANV69t0QOCAiQkr30IfHw/2/index--feK6pXDR9e7yalgyGFAEg
            at org.elasticsearch.repositories.blobstore.BlobStoreTestUtil$2.onResponse(BlobStoreTestUtil.java:268)
            at org.elasticsearch.repositories.blobstore.BlobStoreTestUtil$2.onResponse(BlobStoreTestUtil.java:262)
            at org.elasticsearch.repositories.GetSnapshotInfoContext.onResponse(GetSnapshotInfoContext.java:117)
            at org.elasticsearch.repositories.blobstore.BlobStoreRepository.lambda$getOneSnapshotInfo$24(BlobStoreRepository.java:1849)
            at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:916)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
            ... 1 more

            Caused by:
            java.nio.file.NoSuchFileException: /home/davidturner/src/elasticsearch/server/build/testrun/internalClusterTest/temp/org.elasticsearch.snapshots.SnapshotStressTestsIT_F1980E360247D5B1-001/tempDir-002/repos/PylHhYAhiy/indices/OANV69t0QOCAiQkr30IfHw/2/index--feK6pXDR9e7yalgyGFAEg
                at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
                at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
                at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
                at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
                at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
                at java.base/java.nio.file.Files.newByteChannel(Files.java:431)
                at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
                at org.apache.lucene.tests.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:193)
                at org.apache.lucene.tests.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:193)
                at org.apache.lucene.tests.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:193)
                at org.apache.lucene.tests.mockfile.HandleTrackingFS.newInputStream(HandleTrackingFS.java:94)
                at org.apache.lucene.tests.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:193)
                at java.base/java.nio.file.Files.newInputStream(Files.java:159)
                at org.elasticsearch.common.blobstore.fs.FsBlobContainer.readBlob(FsBlobContainer.java:188)
                at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.read(ChecksumBlobStoreFormat.java:121)
                at org.elasticsearch.repositories.blobstore.BlobStoreRepository.buildBlobStoreIndexShardSnapshots(BlobStoreRepository.java:3656)
                at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getBlobStoreIndexShardSnapshots(BlobStoreRepository.java:3633)
                at org.elasticsearch.repositories.blobstore.BlobStoreTestUtil.assertSnapshotInfosConsistency(BlobStoreTestUtil.java:351)
                at org.elasticsearch.repositories.blobstore.BlobStoreTestUtil$2.onResponse(BlobStoreTestUtil.java:266)
                ... 7 more
```

This failure is super super rare, I've seen it maybe twice after running this test in a loop for several days. It indicates we're doing something wrong with shard generations still.

**Comment by DaveCTurner** [comment]
I've found [a way to reproduce this](https://github.com/elastic/elasticsearch/compare/main...DaveCTurner:elasticsearch:2023/12/27/testDeleteIndexWithOutOfOrderFinalization) - it requires deleting an index during out-of-order snapshot finalization, so it's pretty delicate.

**Comment by kingherc** [comment]
One more at [elasticsearch / periodic / platform-support / main / debian-11 / platform-support-unix](https://gradle-enterprise.elastic.co/s/4t6r5dk4vkaje)

```
    java.lang.AssertionError: java.lang.AssertionError: java.nio.file.NoSuchFileException: /opt/local-ssd/buildkite/builds/bk-agent-prod-gcp-1704430908311388851/elastic/elasticsearch-periodic-platform-support/server/build/testrun/internalClusterTest/temp/org.elasticsearch.snapshots.SnapshotStressTestsIT_D5C3A255A514ABB2-001/tempDir-002/repos/wkujWTVxAr/indices/uiEFev9pSX2Ii-6iR6aMBg/0/index-7dx3dt7bQiG13lDoLKWIag	
        at org.elasticsearch.repositories.blobstore.BlobStoreTestUtil.assertConsistency(BlobStoreTestUtil.java:96)
...
```
