### ISSUE TITLE
After collecting nginx logs, Elasticsearch failed to start

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [elastic/elasticsearch#101170]
### Elasticsearch Version

7.17.14

### Java Version

_bundled_

### OS Version

Linux elasticsearch-1 5.10.134-14.1.an23.x86_64 #1 SMP Thu May 25 19:57:17 CST 2023 x86_64 GNU/Linux

### Problem Description

Elasticsearch Installation Documents：https://xuxiaowei-com-cn.github.io/gitlab-k8s/docs/es/anolis-23-install-es-7.x
Kibana Installation Documents：https://xuxiaowei-com-cn.github.io/gitlab-k8s/docs/es/anolis-23-install-kibana-7.x
Filebeat Installation Documents：https://xuxiaowei-com-cn.github.io/gitlab-k8s/docs/es/anolis-23-install-filebeat-7.x

Before collecting nginx logs, there were multiple shutdowns without any issues.
After collecting nginx logs, power off and restart, resulting in the following error.

```
[2023-10-20T14:36:02,632][INFO ][o.e.n.Node               ] [elasticsearch-1] version[7.17.14], pid[1742], build[default/rpm/774e3bfa4d52e2834e4d9d8d669d77e4e5c1017f/2023-10-05T22:17:33.780167078Z], OS[Linux/5.10.134-14.1.an23.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/21/21+35-2513]
[2023-10-20T14:36:02,636][INFO ][o.e.n.Node               ] [elasticsearch-1] JVM home [/usr/share/elasticsearch/jdk], using bundled JDK [true]
[2023-10-20T14:36:02,636][INFO ][o.e.n.Node               ] [elasticsearch-1] JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -Djava.security.manager=allow, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-11315863829923439270, -XX:+HeapDumpOnOutOfMemoryError, -XX:+ExitOnOutOfMemoryError, -XX:HeapDumpPath=/var/lib/elasticsearch, -XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Xms7997m, -Xmx7997m, -XX:MaxDirectMemorySize=4194304000, -XX:G1HeapRegionSize=4m, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=15, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/etc/elasticsearch, -Des.distribution.flavor=default, -Des.distribution.type=rpm, -Des.bundled_jdk=true]
[2023-10-20T14:36:04,947][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [aggs-matrix-stats]
[2023-10-20T14:36:04,948][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [analysis-common]
[2023-10-20T14:36:04,948][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [constant-keyword]
[2023-10-20T14:36:04,948][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [frozen-indices]
[2023-10-20T14:36:04,948][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [ingest-common]
[2023-10-20T14:36:04,949][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [ingest-geoip]
[2023-10-20T14:36:04,949][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [ingest-user-agent]
[2023-10-20T14:36:04,949][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [kibana]
[2023-10-20T14:36:04,949][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [lang-expression]
[2023-10-20T14:36:04,949][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [lang-mustache]
[2023-10-20T14:36:04,950][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [lang-painless]
[2023-10-20T14:36:04,950][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [legacy-geo]
[2023-10-20T14:36:04,950][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [mapper-extras]
[2023-10-20T14:36:04,950][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [mapper-version]
[2023-10-20T14:36:04,950][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [parent-join]
[2023-10-20T14:36:04,951][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [percolator]
[2023-10-20T14:36:04,951][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [rank-eval]
[2023-10-20T14:36:04,951][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [reindex]
[2023-10-20T14:36:04,951][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [repositories-metering-api]
[2023-10-20T14:36:04,951][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [repository-encrypted]
[2023-10-20T14:36:04,952][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [repository-url]
[2023-10-20T14:36:04,952][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [runtime-fields-common]
[2023-10-20T14:36:04,952][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [search-business-rules]
[2023-10-20T14:36:04,952][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [searchable-snapshots]
[2023-10-20T14:36:04,952][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [snapshot-repo-test-kit]
[2023-10-20T14:36:04,953][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [spatial]
[2023-10-20T14:36:04,953][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [systemd]
[2023-10-20T14:36:04,953][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [transform]
[2023-10-20T14:36:04,953][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [transport-netty4]
[2023-10-20T14:36:04,954][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [unsigned-long]
[2023-10-20T14:36:04,954][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [vector-tile]
[2023-10-20T14:36:04,954][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [vectors]
[2023-10-20T14:36:04,954][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [wildcard]
[2023-10-20T14:36:04,954][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-aggregate-metric]
[2023-10-20T14:36:04,955][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-analytics]
[2023-10-20T14:36:04,955][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-async]
[2023-10-20T14:36:04,955][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-async-search]
[2023-10-20T14:36:04,955][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-autoscaling]
[2023-10-20T14:36:04,955][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-ccr]
[2023-10-20T14:36:04,955][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-core]
[2023-10-20T14:36:04,956][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-data-streams]
[2023-10-20T14:36:04,956][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-deprecation]
[2023-10-20T14:36:04,956][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-enrich]
[2023-10-20T14:36:04,956][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-eql]
[2023-10-20T14:36:04,956][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-fleet]
[2023-10-20T14:36:04,957][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-graph]
[2023-10-20T14:36:04,957][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-identity-provider]
[2023-10-20T14:36:04,957][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-ilm]
[2023-10-20T14:36:04,957][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-logstash]
[2023-10-20T14:36:04,957][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-ml]
[2023-10-20T14:36:04,958][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-monitoring]
[2023-10-20T14:36:04,958][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-ql]
[2023-10-20T14:36:04,958][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-rollup]
[2023-10-20T14:36:04,958][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-security]
[2023-10-20T14:36:04,958][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-shutdown]
[2023-10-20T14:36:04,958][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-sql]
[2023-10-20T14:36:04,959][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-stack]
[2023-10-20T14:36:04,959][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-text-structure]
[2023-10-20T14:36:04,959][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-voting-only-node]
[2023-10-20T14:36:04,959][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] loaded module [x-pack-watcher]
[2023-10-20T14:36:04,960][INFO ][o.e.p.PluginsService     ] [elasticsearch-1] no plugins loaded
[2023-10-20T14:36:04,970][ERROR][o.e.b.Bootstrap          ] [elasticsearch-1] Exception
java.lang.NumberFormatException: For input string: "18446744073709551615"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Long.parseLong(Long.java:708) ~[?:?]
	at java.lang.Long.parseLong(Long.java:831) ~[?:?]
	at org.elasticsearch.monitor.os.OsProbe.getCgroupV2CpuStats(OsProbe.java:616) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:670) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:868) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:875) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.xpack.ml.MachineLearning.additionalSettings(MachineLearning.java:684) ~[?:?]
	at org.elasticsearch.plugins.PluginsService.updatedSettings(PluginsService.java:218) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.node.Node.<init>(Node.java:414) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.node.Node.<init>(Node.java:309) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434) [elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:169) [elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:160) [elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77) [elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112) [elasticsearch-cli-7.17.14.jar:7.17.14]
	at org.elasticsearch.cli.Command.main(Command.java:77) [elasticsearch-cli-7.17.14.jar:7.17.14]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:125) [elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) [elasticsearch-7.17.14.jar:7.17.14]
[2023-10-20T14:36:04,977][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [elasticsearch-1] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.NumberFormatException: For input string: "18446744073709551615"
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:173) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:160) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112) ~[elasticsearch-cli-7.17.14.jar:7.17.14]
	at org.elasticsearch.cli.Command.main(Command.java:77) ~[elasticsearch-cli-7.17.14.jar:7.17.14]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:125) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) ~[elasticsearch-7.17.14.jar:7.17.14]
Caused by: java.lang.NumberFormatException: For input string: "18446744073709551615"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Long.parseLong(Long.java:708) ~[?:?]
	at java.lang.Long.parseLong(Long.java:831) ~[?:?]
	at org.elasticsearch.monitor.os.OsProbe.getCgroupV2CpuStats(OsProbe.java:616) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:670) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:868) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:875) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.xpack.ml.MachineLearning.additionalSettings(MachineLearning.java:684) ~[?:?]
	at org.elasticsearch.plugins.PluginsService.updatedSettings(PluginsService.java:218) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.node.Node.<init>(Node.java:414) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.node.Node.<init>(Node.java:309) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434) ~[elasticsearch-7.17.14.jar:7.17.14]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:169) ~[elasticsearch-7.17.14.jar:7.17.14]
	... 6 more
```

### Steps to Reproduce

Follow the above document to proceed

**Comment by JVerwolf** [comment]
This is a result of the parsed value being larger than the max value allowed for long.  This is in the OsProbe, which I think is in the purview of the Core/Infra team, so routing it there.

**Comment by benwtrent** [comment]
// CC @elastic/ml-core 

Though, calling `OsProbe.getInstance().osStats()` should be safe, it's weird that it throws.

**Comment by droberts195** [comment]
This is happening on the Anolis 23 Linux distribution, which isn't supported. (Seems to come from https://openanolis.cn/page/about.)

It's returning the highest possible _unsigned_ 64 bit number for one of the CPU stats. I guess the OS probe code should be robust against this, because maybe a supported distro will start doing this soon. The code could possibly just ignore out-of-range stats if it's not one of the ones we care about.

@xuxiaowei-com-cn would you mind posting the full output of `more /sys/fs/cgroup/*/cpu.stat` from the machine where this happened so that we can see exactly which stat has this value?

**Comment by xuxiaowei-com-cn** [comment]
@droberts195 

```
[root@elasticsearch-1 ~]# more /sys/fs/cgroup/*/cpu.stat
::::::::::::::
/sys/fs/cgroup/dev-hugepages.mount/cpu.stat
::::::::::::::
usage_usec 4503
user_usec 0
system_usec 4503
nr_periods 0
nr_throttled 0
throttled_usec 0
current_bw 18446744073709551615
nr_bursts 0
burst_usec 0
```

```
Dec 11 08:23:12 elasticsearch-1 systemd[1]: Starting elasticsearch.service - Elasticsearch...
░░ Subject: A start job for unit elasticsearch.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit elasticsearch.service has begun execution.
░░ 
░░ The job identifier is 1298.
Dec 11 08:23:15 elasticsearch-1 systemd-entrypoint[1896]: Dec 11, 2023 8:23:15 AM sun.util.locale.provider.LocaleProviderAdapter <clinit>
Dec 11 08:23:15 elasticsearch-1 systemd-entrypoint[1896]: WARNING: COMPAT locale provider will be removed in a future release
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]: uncaught exception in thread [main]
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]: java.lang.NumberFormatException: For input string: "18446744073709551615"
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at java.base/java.lang.Long.parseLong(Long.java:708)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at java.base/java.lang.Long.parseLong(Long.java:831)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at org.elasticsearch.monitor.os.OsProbe.getCgroupV2CpuStats(OsProbe.java:616)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:670)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:868)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:875)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at org.elasticsearch.xpack.ml.MachineLearning.additionalSettings(MachineLearning.java:684)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at org.elasticsearch.plugins.PluginsService.updatedSettings(PluginsService.java:218)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at org.elasticsearch.node.Node.<init>(Node.java:414)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at org.elasticsearch.node.Node.<init>(Node.java:309)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:169)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:160)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at org.elasticsearch.cli.Command.main(Command.java:77)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:125)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80)
Dec 11 08:23:18 elasticsearch-1 systemd-entrypoint[1896]: For complete error details, refer to the log at /var/log/elasticsearch/elasticsearch.log
Dec 11 08:23:18 elasticsearch-1 systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit elasticsearch.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Dec 11 08:23:18 elasticsearch-1 systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit elasticsearch.service has entered the 'failed' state with result 'exit-code'.
Dec 11 08:23:18 elasticsearch-1 systemd[1]: Failed to start elasticsearch.service - Elasticsearch.
░░ Subject: A start job for unit elasticsearch.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit elasticsearch.service has finished with a failure.
░░ 
░░ The job identifier is 1298 and the job result is failed.
Dec 11 08:23:18 elasticsearch-1 systemd[1]: elasticsearch.service: Consumed 16.109s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit elasticsearch.service completed and consumed the indicated resources.
```

**Comment by droberts195** [comment]
Thanks @xuxiaowei-com-cn.

So it's the `current_bw` value that's causing this.

I don't think the Elasticsearch code uses that one, so the problem arises from trying to parse all the values, even the ones that won't subsequently be used in any way.

I imagine this will start happening on a supported platform the next time we try to extend the support matrix to include a recent distribution.
