### ISSUE TITLE
[CI] GeoTileGridAggregatorTests testBoundedSingletonDocsAsSubAgg failing

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#101114]
Related #101077

**Build scan:**
https://gradle-enterprise.elastic.co/s/etxi7bywgffhm/tests/:server:test/org.elasticsearch.search.aggregations.bucket.geogrid.GeoTileGridAggregatorTests/testBoundedSingletonDocsAsSubAgg
**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.geogrid.GeoTileGridAggregatorTests.testBoundedSingletonDocsAsSubAgg" -Dtests.seed=60FF773AB2793A80 -Dtests.locale=de -Dtests.timezone=America/Glace_Bay -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.aggregations.bucket.geogrid.GeoTileGridAggregatorTests&tests.test=testBoundedSingletonDocsAsSubAgg
**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <{C={1/0/1=1, 1/1/1=1}, D={1/0/1=1, 1/1/0=1, 1/1/1=1}, E={1/0/0=1}, F={1/0/1=1, 1/1/0=1}, G={1/0/0=1, 1/0/1=1}, K={1/1/0=1}, N={1/0/0=1, 1/1/1=1}, O={1/0/0=1}, P={1/1/0=2}, Q={1/0/1=1}, R={1/1/1=1}, U={1/1/1=1}, V={1/0/0=1, 1/0/1=2}, W={1/0/1=1}, X={1/0/1=1, 1/1/0=1, 1/1/1=1}, Y={1/0/1=2}, Z={1/0/1=1, 1/1/1=1}, a={1/0/1=1}, b={1/0/0=1}, d={1/1/1=1}, e={1/0/0=1}, g={1/1/0=1}, h={1/0/1=1}, i={1/1/1=2}, j={1/0/1=2, 1/1/1=2}, m={1/0/1=1, 1/1/1=3}, n={1/0/0=1, 1/1/1=1}, o={1/0/0=1, 1/0/1=1}, p={1/0/1=1}, r={1/1/0=1, 1/1/1=1}, s={1/1/0=1}, t={1/0/0=1, 1/0/1=1}, u={1/0/1=1, 1/1/0=1, 1/1/1=1}, v={1/0/0=1, 1/0/1=1}, x={1/1/0=1, 1/1/1=1}}>
     but: was <{C={1/0/1=1}, D={1/0/1=1}, E={1/0/0=1}, F={1/0/1=1}, G={1/0/0=1, 1/0/1=1}, K={}, N={1/0/0=1}, O={1/0/0=1}, P={}, Q={1/0/1=1}, R={}, U={}, V={1/0/0=1, 1/0/1=2}, W={1/0/1=1}, X={1/0/1=1}, Y={1/0/1=2}, Z={1/0/1=1}, a={1/0/1=1}, b={1/0/0=1}, d={}, e={1/0/0=1}, g={}, h={1/0/1=1}, i={}, j={1/0/1=2}, m={1/0/1=1}, n={1/0/0=1}, o={1/0/0=1, 1/0/1=1}, p={1/0/1=1}, r={}, s={}, t={1/0/0=1, 1/0/1=1}, u={1/0/1=1}, v={1/0/0=1, 1/0/1=1}, x={}}>

  at __randomizedtesting.SeedInfo.seed([60FF773AB2793A80:7390764034CF7DD4]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.search.aggregations.bucket.geogrid.GeoGridAggregatorTestCase.lambda$testWithSeveralDocsAsSubAgg$14(GeoGridAggregatorTestCase.java:250)
  at org.elasticsearch.search.aggregations.AggregatorTestCase.testCase(AggregatorTestCase.java:720)
  at org.elasticsearch.search.aggregations.bucket.geogrid.GeoGridAggregatorTestCase.testWithSeveralDocsAsSubAgg(GeoGridAggregatorTestCase.java:213)
  at org.elasticsearch.search.aggregations.bucket.geogrid.GeoGridAggregatorTestCase.testBoundedSingletonDocsAsSubAgg(GeoGridAggregatorTestCase.java:192)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by iverase** [comment]
Actually I am going to close it in favour of https://github.com/elastic/elasticsearch/issues/101077 as that test muted all the suite.
