### ISSUE TITLE
Tragic failure of primary marks replicas as stale

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#101180]
A [user on the forums](https://discuss.elastic.co/t/index-with-multiple-replicas-turned-red-when-node-with-primary-went-down/345439) reported temporary unavailability of a shard when the node with the primary failed due to the filesystem becoming readonly during replication:

```
[2023-10-18T08:41:30,766][WARN ][o.e.c.r.a.AllocationService] [elastic-node-eastus2-3-vm-0] failing shard [failed shard, shard [abc__events-2023.10.18][0], node[Jk9Y9EtDSmS_XXXXXX], [R], s[STARTED], a[id=gfggfYtfR7ajKXd4kj73Gg], message [failed to perform indices:data/write/bulk[s] on replica [abc__events-2023.10.18][0], node[Jk9Y9EtDSmS_XXXXXX], [R], s[STARTED], a[id=gfggfYtfR7ajKXd4kj73Gg]], failure [IndexShardClosedException[CurrentState[CLOSED] Primary closed.]], markAsStale [true]]
[2023-10-18T08:41:31,023][WARN ][o.e.c.r.a.AllocationService] [elastic-node-eastus2-3-vm-0] failing shard [failed shard, shard [abc__events-2023.10.18][0], node[pA_ggBT3Q9mmUdXXXX], [R], s[STARTED], a[id=tH7xi2bAQAi1ce2PwJ5ylQ], message [failed to perform indices:data/write/bulk[s] on replica [abc__events-2023.10.18][0], node[pA_ggBT3Q9mmUdXXXX], [R], s[STARTED], a[id=tH7xi2bAQAi1ce2PwJ5ylQ]], failure [IndexShardClosedException[CurrentState[CLOSED] Primary closed.]], markAsStale [true]]
[2023-10-18T08:41:31,024][WARN ][o.e.c.r.a.AllocationService] [elastic-node-eastus2-3-vm-0] failing shard [failed shard, shard [abc__events-2023.10.18][0], node[TN3qE5YWRMaji3pWXXXX], [P], s[STARTED], a[id=lCe4tac4Q-q8pl0gRMTETw], message [shard failure, reason [already closed by tragic event on the translog]], failure [IOException[Read-only file system]], markAsStale [true]]
```

I think it was incorrect to mark the replicas as stale in this situation, since this write was not acked.

**Comment by caolix** [comment]
[2023-11-25T06:29:24,271][WARN ][o.e.c.a.s.ShardStateAction] [oindex-node-2] no master known for action [internal:cluster/shard/failure] for shard entry [shard id [[s3-index-000001][1]], allocation id [ol36iYJuRa-VoTERn7rkUw], primary term [1], message [failed to perform indices:data/write/bulk[s] on replica [s3-index-000001][1], node[SzAJevUTTseoS5vj3xZATw], [R], s[STARTED], a[id=ol36iYJuRa-VoTERn7rkUw]], markAsStale [true], failure [[s3-index-000001/TrvZTDZJRua-Qh5sMhRzuQ][[s3-index-000001][1]] org.elasticsearch.index.shard.IndexShardClosedException: CurrentState[CLOSED] Primary closed.
        at org.elasticsearch.server@8.3.3/org.elasticsearch.action.support.replication.PendingReplicationActions.lambda$cancelActions$1(PendingReplicationActions.java:110)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.elasticsearch.server@8.3.3/org.elasticsearch.action.support.replication.PendingReplicationActions.lambda$cancelActions$2(PendingReplicationActions.java:110)
        at org.elasticsearch.server@8.3.3/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:710)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
]]

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch @caolix.

I think your message was posted in error so I'm going to hide it to keep this thread on-topic for the OP. If you'd like to discuss further, please do so on the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) rather than here.

**Comment by amberzsy** [comment]
@DaveCTurner any followup and plan to fix for this?

**Comment by xuanyuan300** [comment]
@DaveCTurner We are currently encountering
this issue,Do you have any plans to fix it? Thanks.
