### ISSUE TITLE
Too long instrument names trigger opentelemetry validation

### ISSUE THREAD

**Issue by ldematte** [elastic/elasticsearch#101271]
### Elasticsearch Version

8.12

### Java Version

_bundled_

### OS Version

Any

### Problem Description

OTel validation checks instrument names upon creation, and if they do not pass validation, it (seemingly - if you trust the error message) return a noop instrument.

Problem is, the character limit for the names is very low (63 chars) and we already have at least one in the codebase that triggers validation.

Example stack trace:
```
Instrument name "elasticsearch.blob_cache.miss_that_triggered_read_from_blob_store" is invalid, returning noop instrument. Instrument names must consist of 63 or fewer characters including alphanumeric, _, ., -, and start with a letter. java.lang.AssertionError
  1>    at io.opentelemetry.api@1.17.0/io.opentelemetry.api.internal.ValidationUtil.log(ValidationUtil.java:55)
  1>    at io.opentelemetry.api@1.17.0/io.opentelemetry.api.internal.ValidationUtil.checkValidInstrumentName(ValidationUtil.java:72)
  1>    at io.opentelemetry.api@1.17.0/io.opentelemetry.api.internal.ValidationUtil.checkValidInstrumentName(ValidationUtil.java:61)
  1>    at io.opentelemetry.api@1.17.0/io.opentelemetry.api.metrics.DefaultMeter.counterBuilder(DefaultMeter.java:42)
  1>    at org.elasticsearch.telemetry.apm@8.12.0-SNAPSHOT/org.elasticsearch.telemetry.apm.internal.metrics.LongCounterAdapter.buildInstrument(LongCounterAdapter.java:30)
  1>    at org.elasticsearch.telemetry.apm@8.12.0-SNAPSHOT/org.elasticsearch.telemetry.apm.internal.metrics.LongCounterAdapter.buildInstrument(LongCounterAdapter.java:22)
  1>    at org.elasticsearch.telemetry.apm@8.12.0-SNAPSHOT/org.elasticsearch.telemetry.apm.AbstractInstrument.lambda$doBuildInstrument$0(AbstractInstrument.java:41)
  1>    at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
  1>    at org.elasticsearch.telemetry.apm@8.12.0-SNAPSHOT/org.elasticsearch.telemetry.apm.AbstractInstrument.doBuildInstrument(AbstractInstrument.java:41)
  1>    at org.elasticsearch.telemetry.apm@8.12.0-SNAPSHOT/org.elasticsearch.telemetry.apm.AbstractInstrument.<init>(AbstractInstrument.java:37)
  1>    at org.elasticsearch.telemetry.apm@8.12.0-SNAPSHOT/org.elasticsearch.telemetry.apm.internal.metrics.LongCounterAdapter.<init>(LongCounterAdapter.java:25)
  1>    at org.elasticsearch.telemetry.apm@8.12.0-SNAPSHOT/org.elasticsearch.telemetry.apm.APMMeterRegistry.registerLongCounter(APMMeterRegistry.java:114)
  1>    at org.elasticsearch.stateless@8.12.0-SNAPSHOT/co.elastic.elasticsearch.stateless.Stateless.createComponents(Stateless.java:488)
  1>    at org.elasticsearch.server@8.12.0-SNAPSHOT/org.elasticsearch.node.NodeConstruction.lambda$construct$16(NodeConstruction.java:743)
```

### Steps to Reproduce

Run `:libs:serverless-build-info:yamlRestTest`, suite: `co.elastic.elasticsearch.serverless.buildinfo.ServerlessBuildInfoIT` and examine logs

**Comment by stu-elastic** [comment]
Cut issue in appropriate repo
