### ISSUE TITLE
[CI] DeprecationHttpIT testDeprecationMessagesCanBeIndexed failing

### ISSUE THREAD

**Issue by pxsalehi** [elastic/elasticsearch#101263]
**Build scan:**
https://gradle-enterprise.elastic.co/s/qkexzsxpddo6w/tests/:x-pack:plugin:deprecation:qa:rest:javaRestTest/org.elasticsearch.xpack.deprecation.DeprecationHttpIT/testDeprecationMessagesCanBeIndexed
**Reproduction line:**
```
./gradlew ':x-pack:plugin:deprecation:qa:rest:javaRestTest' --tests "org.elasticsearch.xpack.deprecation.DeprecationHttpIT.testDeprecationMessagesCanBeIndexed" -Dtests.seed=87F10B316C1BA76E -Dtests.locale=hu-HU -Dtests.timezone=Universal -Druntime.java=17
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.deprecation.DeprecationHttpIT&tests.test=testDeprecationMessagesCanBeIndexed

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: iterable with items [(map containing ["@timestamp"->ANYTHING] and map containing ["elasticsearch.cluster.name"->ANYTHING] and map containing ["elasticsearch.cluster.uuid"->ANYTHING] and map containing ["elasticsearch.http.request.x_opaque_id"->"xOpaqueId-testDeprecationMessagesCanBeIndexed"] and map containing ["elasticsearch.event.category"->"settings"] and map containing ["elasticsearch.node.id"->ANYTHING] and map containing ["elasticsearch.node.name"->ANYTHING] and map containing ["data_stream.dataset"->"deprecation.elasticsearch"] and map containing ["data_stream.namespace"->"default"] and map containing ["data_stream.type"->"logs"] and map containing ["ecs.version"->ANYTHING] and map containing ["event.code"->"deprecated_settings"] and map containing ["event.dataset"->"deprecation.elasticsearch"] and map containing ["log.level"->"WARN"] and map containing ["log.logger"->ANYTHING] and map containing ["message"->"[deprecated_settings] usage is deprecated. use [settings] instead"]), (map containing ["@timestamp"->ANYTHING] and map containing ["elasticsearch.cluster.name"->ANYTHING] and map containing ["elasticsearch.cluster.uuid"->ANYTHING] and map containing ["elasticsearch.http.request.x_opaque_id"->"xOpaqueId-testDeprecationMessagesCanBeIndexed"] and map containing ["elasticsearch.event.category"->"api"] and map containing ["elasticsearch.node.id"->ANYTHING] and map containing ["elasticsearch.node.name"->ANYTHING] and map containing ["data_stream.dataset"->"deprecation.elasticsearch"] and map containing ["data_stream.namespace"->"default"] and map containing ["data_stream.type"->"logs"] and map containing ["ecs.version"->ANYTHING] and map containing ["event.code"->"deprecated_route_GET_/_test_cluster/deprecated_settings"] and map containing ["event.dataset"->"deprecation.elasticsearch"] and map containing ["log.level"->"WARN"] and map containing ["log.logger"->ANYTHING] and map containing ["message"->"[/_test_cluster/deprecated_settings] exists for deprecated tests"])] in any order
     but: not matched: <{elasticsearch.cluster.name=javaRestTest, service.name=ES_ECS, elasticsearch.event.category=settings, data_stream.namespace=default, message=[test.setting.deprecated.true2] setting was deprecated in Elasticsearch and will be removed in a future release., data_stream.type=logs, log.logger=org.elasticsearch.deprecation.common.settings.Settings, @timestamp=2023-10-24T08:53:36.929Z, event.code=test.setting.deprecated.true2, elasticsearch.cluster.uuid=YRL9ICzWRTmResFN85NYWg, elasticsearch.node.name=javaRestTest-0, ecs.version=1.2.0, data_stream.dataset=deprecation.elasticsearch, log.level=WARN, event.dataset=deprecation.elasticsearch, process.thread.name=elasticsearch[javaRestTest-0][masterService#updateTask][T#1], elasticsearch.node.id=mRTgmgI-Tl6fP5B0VBcwZQ}>

  at __randomizedtesting.SeedInfo.seed([87F10B316C1BA76E:2C1EDD7D04F490C9]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.deprecation.DeprecationHttpIT.lambda$testDeprecationMessagesCanBeIndexed$9(DeprecationHttpIT.java:397)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1202)
  at org.elasticsearch.xpack.deprecation.DeprecationHttpIT.testDeprecationMessagesCanBeIndexed(DeprecationHttpIT.java:392)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by thecoop** [comment]
Same as other DeprecationHttpIT test failures

**Comment by thecoop** [comment]
Hopefully fixed by #101273

**Comment by andreidan** [comment]
This failed again today https://gradle-enterprise.elastic.co/s/5ig6u4x7th5gm

**Comment by mosche** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/107563
