### ISSUE TITLE
Unable to add user using shield

### ISSUE THREAD

**Issue by rishi-freshbooks** [elastic/elasticsearch#10132]
I have installed license and shield, and get this stack trace:
```
[vagrant@es02 elasticsearch]$ sudo bash bin/shield/esusers adduser es_user -r admin
Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/common/cli/CliTool
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.common.cli.CliTool
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 13 more
```

Any ideas

**Comment by javanna** [comment]
Hi @rishi-freshbooks which version of elasticsearch are you using?

**Comment by rishi-freshbooks** [comment]
Hi @javanna, I am using 1.4.4 with Java 1.7.0_75

**Comment by javanna** [comment]
that sounds good @rishi-freshbooks . how did you install elasticsearch? Is the `lib` directory containing the elasticsearch jar in `$ES_HOME/lib`? Does the current user have access to it?

**Comment by rishi-freshbooks** [comment]
I installed elasticseach through "yum install elasticseach".
`$ES_HOME = /usr/share/elasticsearch`

`$ES_HOME/lib` does have the jar.

Current user does have read access:
```
[vagrant@es01 ~]$ ls -l /usr/share/elasticsearch/lib/
total 20228
-rw-r--r-- 1 root root 12480928 Jul  9  2014 elasticsearch-1.2.2.jar
-rw-r--r-- 1 root root   914597 Jul  9  2014 jna-4.1.0.jar
-rw-r--r-- 1 root root   794991 Jul  9  2014 jts-1.13.jar
-rw-r--r-- 1 root root   489884 Jul  9  2014 log4j-1.2.17.jar
-rw-r--r-- 1 root root  1688588 Jul  9  2014 lucene-analyzers-common-4.8.1.jar
-rw-r--r-- 1 root root   404512 Jul  9  2014 lucene-codecs-4.8.1.jar
-rw-r--r-- 1 root root  2411877 Jul  9  2014 lucene-core-4.8.1.jar
-rw-r--r-- 1 root root   107738 Jul  9  2014 lucene-grouping-4.8.1.jar
-rw-r--r-- 1 root root   138211 Jul  9  2014 lucene-highlighter-4.8.1.jar
-rw-r--r-- 1 root root    64185 Jul  9  2014 lucene-join-4.8.1.jar
-rw-r--r-- 1 root root    36027 Jul  9  2014 lucene-memory-4.8.1.jar
-rw-r--r-- 1 root root    95888 Jul  9  2014 lucene-misc-4.8.1.jar
-rw-r--r-- 1 root root   211084 Jul  9  2014 lucene-queries-4.8.1.jar
-rw-r--r-- 1 root root   390591 Jul  9  2014 lucene-queryparser-4.8.1.jar
-rw-r--r-- 1 root root    54579 Jul  9  2014 lucene-sandbox-4.8.1.jar
-rw-r--r-- 1 root root   108199 Jul  9  2014 lucene-spatial-4.8.1.jar
-rw-r--r-- 1 root root   178673 Jul  9  2014 lucene-suggest-4.8.1.jar
drwxr-xr-x 2 root root     4096 Mar 16 16:31 sigar
-rw-r--r-- 1 root root   102177 Jul  9  2014 spatial4j-0.4.1.jar
```

**Comment by javanna** [comment]
the lib directory doesn't contain `1.4.4` but `elasticsearch-1.2.2.jar`, that is why you get that error and the creation of users fail. Also...not related but important too, do you really need to install elasticsearch as root? That doesn't seem like a great idea to me.

**Comment by rishi-freshbooks** [comment]
My apologies! What a silly a mistake, I was toggling between environments (one has 1.4.4 and the other 1.2.2)... you are right.

I agree;  it does not need to be installed as root; should create a elasticsearch user.

Thanks!! Closing ticket.

**Comment by javanna** [comment]
Glad to hear you found the issue, thanks for letting us know!
