### ISSUE TITLE
Build failure on elasticsearch # 8.10 - intake rest compatibility

### ISSUE THREAD

**Issue by ldematte** [elastic/elasticsearch#101461]
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.10+intake+multijob+rest-compat/242/

### Repro line

N/A

### Does it reproduce?

No

### Applicable branches

8.10

### Failure excerpt

Seems like a problem with Vault:

```
15:40:46 Caused by: com.bettercloud.vault.VaultException: Vault responded with HTTP status code: 500
15:40:46 	at com.bettercloud.vault.api.Auth.loginByAppRole(Auth.java:435)
15:40:46 	at com.bettercloud.vault.api.Auth$loginByAppRole.call(Unknown Source)
15:40:46 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
15:40:46 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
15:40:46 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157)
15:40:46 	at init_8g96ggaa0v5iilfe8vnvbfx0p.run(/var/lib/jenkins/.gradle/init.d/init.gradle:37)
15:40:46 	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
```

Likely transient - re-running the build pass, but maybe worth investigating anyway.

**Comment by mark-vieira** [comment]
This is a transient network error communicating with vault from CI.
