### ISSUE TITLE
[CI] DownsampleActionIT testDownsampleTwice failing

### ISSUE THREAD

**Issue by ldematte** [elastic/elasticsearch#101428]
**Build scan:**
https://gradle-enterprise.elastic.co/s/5yokfvudch5qq/tests/:x-pack:plugin:ilm:qa:multi-node:javaRestTest/org.elasticsearch.xpack.ilm.actions.DownsampleActionIT/testDownsampleTwice
**Reproduction line:**
```
./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.actions.DownsampleActionIT.testDownsampleTwice" -Dtests.seed=2737BE7616155EDF -Dtests.locale=mk-MK -Dtests.timezone=Asia/Tashkent -Druntime.java=21
```

**Applicable branches:**
main, 8.11

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ilm.actions.DownsampleActionIT&tests.test=testDownsampleTwice

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: is <true>
     but: was <false>

  at __randomizedtesting.SeedInfo.seed([2737BE7616155EDF:6F6BA0A38DDF75C5]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.ilm.actions.DownsampleActionIT.lambda$testDownsampleTwice$18(DownsampleActionIT.java:470)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1202)
  at org.elasticsearch.xpack.ilm.actions.DownsampleActionIT.testDownsampleTwice(DownsampleActionIT.java:469)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by martijnvg** [comment]
The reason this test fails is because ILM is waiting for current time to be based the backing index's end time:

```
Waiting until the index's time series end time lapses before proceeding with action [downsample] as the index can still accept writes.
```

Maybe we need to reduce the look ahead time in the test? Or wait longer?

**Comment by ldematte** [comment]
Failed again today: https://gradle-enterprise.elastic.co/s/ybspjfd326dx4/tests/task/:x-pack:plugin:ilm:qa:multi-node:javaRestTest/details/org.elasticsearch.xpack.ilm.actions.DownsampleActionIT/testDownsampleTwice?top-execution=1

I'm going to mute it

**Comment by mark-vieira** [comment]
I cherry picked the mute to 8.11 since it's failing there as well.

**Comment by idegtiarenko** [comment]
There is a failure in `testDownsampleTwiceSameInterval` that looks very similar: https://gradle-enterprise.elastic.co/s/zglpk2dn2apo2/tests/task/:x-pack:plugin:ilm:qa:multi-node:javaRestTest/details/org.elasticsearch.xpack.ilm.actions.DownsampleActionIT/testDownsampleTwiceSameInterval?top-execution=1

**Comment by luigidellaquila** [comment]
Muting `testDownsampleTwiceSameInterval` as well

**Comment by jan-elastic** [comment]
happened again: https://gradle-enterprise.elastic.co/s/qtvareshmngw2/tests/task/:x-pack:plugin:ilm:qa:multi-node:javaRestTest/details/org.elasticsearch.xpack.ilm.actions.DownsampleActionIT/testDownsampleTwiceSameInterval?top-execution=1

**Comment by kingherc** [comment]
Re-opening due to [elasticsearch / periodic / platform-support / 8.12 / ubuntu-2204 / platform-support-unix](https://gradle-enterprise.elastic.co/s/sk2qpg2cm52eg)

**Comment by kkrik-es** [comment]
I see the following in the log:

```
[2024-02-14T08:24:05,541][ERROR][o.e.x.i.a.DownsampleActionIT] [testDownsampleTwice] Index [.ds-ds-znbivfjoqv-2024.02.14-000001] ilm explain {index=.ds-ds-znbivfjoqv-2024.02.14-000001, managed=true, policy=policy-FIimk, index_creation_date_millis=1707895314144, time_since_index_creation=2.18m, lifecycle_date_millis=1707895314144, age=2.18m, phase=warm, phase_time_millis=1707895314254, action=downsample, action_time_millis=1707895314254, step=check-ts-end-time-passed, step_time_millis=1707895319103, step_info={message=The [index.time_series.end_time] setting for index [.ds-ds-znbivfjoqv-2024.02.14-000001] is [1707895674000]. Waiting until the index's time series end time lapses before proceeding with action [downsample] as the index can still accept writes.}, phase_execution={policy=policy-FIimk, phase_definition={min_age=0ms, actions={downsample={fixed_interval=1m, wait_timeout=1d}}}, version=1, modified_date_in_millis=1707895314105}}
```

Is this a race condition between removing the end time in the test, and ILM running this check? If so, would it help to reduce the `LIFECYCLE_POLL_INTERVAL` (default is 10 minutes)? @andreidan for thoughts.

**Comment by kkrik-es** [comment]
Wrt the last failure, the log shows that the test timed out waiting for end time to lapse before marking the index as readonly.

```
1> [2024-02-14T08:21:54,074][INFO ][o.e.x.i.a.DownsampleActionIT] [testDownsampleTwice] before test
  1> [2024-02-14T08:21:54,103][INFO ][o.e.x.i.a.DownsampleActionIT] [testDownsampleTwice] --> running [testDownsampleTwice] with index [index-rkxiarbkai], data stream [ds-znbivfjoqv], alias [alias-aoPKf] and policy [policy-FIimk]
  1> [2024-02-14T08:21:54,259][INFO ][o.e.x.i.a.DownsampleActionIT] [testDownsampleTwice] --> firstBackingIndex: .ds-ds-znbivfjoqv-2024.02.14-000001
  1> [2024-02-14T08:24:05,541][ERROR][o.e.x.i.a.DownsampleActionIT] [testDownsampleTwice] Index [.ds-ds-znbivfjoqv-2024.02.14-000001] ilm explain {index=.ds-ds-znbivfjoqv-2024.02.14-000001, managed=true, policy=policy-FIimk, index_creation_date_millis=1707895314144, time_since_index_creation=2.18m, lifecycle_date_millis=1707895314144, age=2.18m, phase=warm, phase_time_millis=1707895314254, action=downsample, action_time_millis=1707895314254, step=check-ts-end-time-passed, step_time_millis=1707895319103, step_info={message=The [index.time_series.end_time] setting for index [.ds-ds-znbivfjoqv-2024.02.14-000001] is [1707895674000]. Waiting until the index's time series end time lapses before proceeding with action [downsample] as the index can still accept writes.}, phase_execution={policy=policy-FIimk, phase_definition={min_age=0ms, actions={downsample={fixed_interval=1m, wait_timeout=1d}}}, version=1, modified_date_in_millis=1707895314105}}
  1> [2024-02-14T08:24:05,818][INFO ][o.e.x.i.a.DownsampleActionIT] [testDownsampleTwice] There are still tasks running after this test that might break subsequent tests [health-node[c]].
```

`Waiting until the index's time series end time lapses before proceeding with action [downsample] as the index can still accept writes.`

It seems like a timing issue where the service updating the end time somehow ran first, pushing the end time 6 minutes into the future (`08:27:54`).

**Comment by andreidan** [comment]
Ah good catch Kostas.

Should we lower the look ahead time tot he minimum value in the index template ? (1m? ) 

```
                        "look_ahead_time": "1m",
```

**Comment by kkrik-es** [comment]
I think we can increase `time_series.poll_interval`, testing this..

**Comment by kkrik-es** [comment]
`"look_ahead_time": "1m",`

This is added in the index template already. Still, we only wait for 30s for the index to be readonly, so that may not be enough if we're unlucky.. Lemme increase the timeout and see if it helps.
