### ISSUE TITLE
[CI] InternalMedianAbsoluteDeviationTests testConcurrentEquals failing

### ISSUE THREAD

**Issue by ldematte** [elastic/elasticsearch#101417]
Fails on 8.11 branch, not on main

**Build scan:**
https://gradle-enterprise.elastic.co/s/4irsnbcx5vpfw/tests/:server:test/org.elasticsearch.search.aggregations.metrics.InternalMedianAbsoluteDeviationTests/testConcurrentEquals
**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.metrics.InternalMedianAbsoluteDeviationTests.testConcurrentEquals" -Dtests.seed=ED3008B8577B78F8 -Dtests.locale=fr-BE -Dtests.timezone=Asia/Kolkata -Druntime.java=21
```

**Applicable branches:**
8.11

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.aggregations.metrics.InternalMedianAbsoluteDeviationTests&tests.test=testConcurrentEquals

**Failure excerpt:**
```
java.util.concurrent.ExecutionException: java.lang.AssertionError: expected: org.elasticsearch.search.aggregations.metrics.InternalMedianAbsoluteDeviation<{"mEKUa":{"value":0.23608820427483945,"value_as_string":"0.24"}}> but was: org.elasticsearch.search.aggregations.metrics.InternalMedianAbsoluteDeviation<{"mEKUa":{"value":0.23608820427483945,"value_as_string":"0.24"}}>

  at __randomizedtesting.SeedInfo.seed([ED3008B8577B78F8:9FDD38896C659AB4]:0)
  at java.util.concurrent.FutureTask.report(FutureTask.java:122)
  at java.util.concurrent.FutureTask.get(FutureTask.java:191)
  at org.elasticsearch.test.AbstractWireTestCase.concurrentTest(AbstractWireTestCase.java:117)
  at org.elasticsearch.test.AbstractWireTestCase.testConcurrentEquals(AbstractWireTestCase.java:91)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

  Caused by: java.lang.AssertionError: expected: org.elasticsearch.search.aggregations.metrics.InternalMedianAbsoluteDeviation<{"mEKUa":{"value":0.23608820427483945,"value_as_string":"0.24"}}> but was: org.elasticsearch.search.aggregations.metrics.InternalMedianAbsoluteDeviation<{"mEKUa":{"value":0.23608820427483945,"value_as_string":"0.24"}}>

    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at org.elasticsearch.test.AbstractWireTestCase.lambda$testConcurrentEquals$0(AbstractWireTestCase.java:93)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
    at java.util.concurrent.FutureTask.run(FutureTask.java:317)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.lang.Thread.run(Thread.java:1583)

```

**Comment by ldematte** [comment]
Possibly related to https://github.com/elastic/elasticsearch/issues/97486

**Comment by kkrik-es** [comment]
Not a blocker, this code hasn't changed much in the past 6 months. I'll take a closer look and revisit the labels.

**Comment by kkrik-es** [comment]
I'm confused by the assert:

```
Caused by: java.lang.AssertionError: expected: org.elasticsearch.search.aggregations.metrics.InternalMedianAbsoluteDeviation<{"mEKUa":{"value":0.23608820427483945,"value_as_string":"0.24"}}> but was: org.elasticsearch.search.aggregations.metrics.InternalMedianAbsoluteDeviation<{"mEKUa":{"value":0.23608820427483945,"value_as_string":"0.24"}}>
```

The values match? Not sure what's the error here.

**Comment by ldematte** [comment]
> Not a blocker, this code hasn't changed much in the past 6 months. I'll take a closer look and revisit the labels.

My understanding is that blocker is assigned by default, then the correct team triages it and assign the correct risk/label (like you did)

> The values match? Not sure what's the error here.

it might be a rounding issue: the values may be slightly different, but the difference is so tiny that the string representation looks identical. If it is a hard equals on doubles, I'd consider introducing a delta.

**Comment by kkrik-es** [comment]
Interesting, I got 1 failure out of a 1000 tries.. Not tied to 8.10 in any way, just a corner case I think.

**Comment by ldematte** [comment]
Another failure, but with no error message this time? [InternalMedianAbsoluteDeviationTests » testConcurrentEquals](https://gradle-enterprise.elastic.co/s/24vnkjls5tzdg/tests/:server:test/org.elasticsearch.search.aggregations.metrics.InternalMedianAbsoluteDeviationTests/testConcurrentEquals)

On main, on Windows (unfortunately)
