### ISSUE TITLE
[CI] S3BlobStoreRepositoryTests testIndicesDeletedFromRepository failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#101582]
**Build scan:**
https://gradle-enterprise.elastic.co/s/wgqnlk7bzg2cc/tests/:modules:repository-s3:internalClusterTest/org.elasticsearch.repositories.s3.S3BlobStoreRepositoryTests/testIndicesDeletedFromRepository
**Reproduction line:**
```
./gradlew ':modules:repository-s3:internalClusterTest' --tests "org.elasticsearch.repositories.s3.S3BlobStoreRepositoryTests.testIndicesDeletedFromRepository" -Dtests.seed=3CD814429AB8A819 -Dtests.locale=es-ES -Dtests.timezone=Europe/Nicosia -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.repositories.s3.S3BlobStoreRepositoryTests&tests.test=testIndicesDeletedFromRepository

**Failure excerpt:**
```
java.lang.AssertionError: expected:<14> but was:<15>

  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.failNotEquals(Assert.java:834)
  at org.junit.Assert.assertEquals(Assert.java:645)
  at org.junit.Assert.assertEquals(Assert.java:631)
  at org.elasticsearch.repositories.blobstore.ESBlobStoreRepositoryIntegTestCase.testIndicesDeletedFromRepository(ESBlobStoreRepositoryIntegTestCase.java:449)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by DaveCTurner** [comment]
Duplicates https://github.com/elastic/elasticsearch/issues/101602. Seems pretty serious tbh but not a distrib team issue.

**Comment by ywangd** [comment]
Indeed. Thanks David! Shard snapshot failed with the following stacktrace
```
  1> java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 15
  1> 	at java.util.ArrayList.add(ArrayList.java:484) ~[?:?]
  1> 	at java.util.ArrayList.add(ArrayList.java:496) ~[?:?]
  1> 	at org.elasticsearch.telemetry.MetricRecorder$RegisteredMetric.call(MetricRecorder.java:52) ~[framework-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
  1> 	at org.elasticsearch.telemetry.MetricRecorder.call(MetricRecorder.java:87) ~[framework-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
  1> 	at org.elasticsearch.telemetry.MetricRecorder.call(MetricRecorder.java:80) ~[framework-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
  1> 	at org.elasticsearch.telemetry.RecordingInstruments$RecordingInstrument.call(RecordingInstruments.java:45) ~[framework-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
  1> 	at org.elasticsearch.telemetry.RecordingInstruments$RecordingLongCounter.incrementBy(RecordingInstruments.java:167) ~[framework-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
  1> 	at org.elasticsearch.repositories.s3.S3BlobStore$IgnoreNoResponseMetricsCollector.collectMetrics(S3BlobStore.java:174) ~[main/:?]
  1> 	at org.elasticsearch.repositories.s3.S3BlobStore$1.collectMetrics(S3BlobStore.java:130) ~[main/:?]
```

 I'll close this one. Based on the [latest comment](https://github.com/elastic/elasticsearch/issues/101602#issuecomment-1787255180) on #101602. The underlying issue is being fixed right now.
