### ISSUE TITLE
[CI] ClassificationHousePricingIT testFeatureImportanceValues failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#101598]
**Build scan:**
https://gradle-enterprise.elastic.co/s/uwwlkdiu6izvg/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.ClassificationHousePricingIT/testFeatureImportanceValues
**Reproduction line:**
```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.ClassificationHousePricingIT.testFeatureImportanceValues" -Dtests.seed=8C442F444C8DA895 -Dtests.locale=ca-ES -Dtests.timezone=Africa/Gaborone -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.ClassificationHousePricingIT&tests.test=testFeatureImportanceValues

**Failure excerpt:**
```
java.lang.AssertionError: Stats were: {"id":"classification_house_pricing_test_feature_importance_values","state":"started","progress":[{"phase":"reindexing","progress_percent":100},{"phase":"loading_data","progress_percent":100},{"phase":"feature_selection","progress_percent":100},{"phase":"coarse_parameter_search","progress_percent":100},{"phase":"fine_tuning_parameters","progress_percent":100},{"phase":"final_training","progress_percent":100},{"phase":"writing_results","progress_percent":100},{"phase":"inference","progress_percent":98}],"data_counts":{"training_docs_count":510,"test_docs_count":950,"skipped_docs_count":0},"memory_usage":{"timestamp":1698748402711,"peak_usage_bytes":232102,"status":"ok"},"analysis_stats":{"classification_stats":{"timestamp":1698748402711,"iteration":0,"hyperparameters":{"class_assignment_objective":"maximize_minimum_recall","alpha":6.0709755979659175,"downsample_factor":0.23874177497042998,"eta":0.6217679005474379,"eta_growth_rate_per_tree":1.3108839502737188,"feature_bag_fraction":0.13333333333333341,"gamma":0.3794904870054506,"lambda":0.02703658022998078,"max_attempts_to_add_tree":0,"max_optimization_rounds_per_hyperparameter":2,"max_trees":16,"num_folds":0,"num_splits_per_feature":0,"soft_tree_depth_limit":4.289165585614386,"soft_tree_depth_tolerance":0.15},"timing_stats":{"elapsed_time":0,"iteration_time":0},"validation_loss":{"loss_type":"binomial_logistic"}}},"node":{"id":"Cc575Xj0T9aRR8t9oavYYw","name":"javaRestTest-1","ephemeral_id":"KLmNX-teT2iKh5FeSZZu-Q","transport_address":"127.0.0.1:37293","attributes":{"testattr":"test","transform.config_version":"10.0.0","xpack.installed":"true","ml.allocated_processors":"32","ml.max_jvm_size":"536870912","ml.config_version":"11.0.0","ml.machine_memory":"101258194944","ml.allocated_processors_double":"32.0"}},"assignment_explanation":""}
Expected: <stopped>
     but: was <started>

  at __randomizedtesting.SeedInfo.seed([8C442F444C8DA895:719549882B1AF1C0]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:204)
  at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.lambda$waitUntilAnalyticsIsStopped$0(MlNativeDataFrameAnalyticsIntegTestCase.java:129)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1202)
  at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.waitUntilAnalyticsIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:129)
  at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.waitUntilAnalyticsIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:125)
  at org.elasticsearch.xpack.ml.integration.ClassificationHousePricingIT.testFeatureImportanceValues(ClassificationHousePricingIT.java:1566)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by cbuescher** [comment]
At first I thought this was https://github.com/elastic/elasticsearch/issues/90019, but the errors in the logs coming from painless scripts look different, so I'm opening this for investigation. Please close if the two are related.

```
Caused by: org.elasticsearch.script.GeneralScriptException: Failed to compile inline script [ctx.message instanceof String && ctx.message.startsWith('{') && ctx.message.endsWith('}')] using lang [painless]
	at org.elasticsearch.script.ScriptCache.compile(ScriptCache.java:119) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	at org.elasticsearch.script.ScriptService.compile(ScriptService.java:634) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	at org.elasticsearch.ingest.ConditionalProcessor.<init>(ConditionalProcessor.java:80) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	at org.elasticsearch.ingest.ConditionalProcessor.<init>(ConditionalProcessor.java:61) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	at org.elasticsearch.ingest.ConfigurationUtils.readProcessor(ConfigurationUtils.java:628) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	at org.elasticsearch.ingest.ConfigurationUtils.readProcessor(ConfigurationUtils.java:580) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	at org.elasticsearch.ingest.ConfigurationUtils.readProcessorConfigs(ConfigurationUtils.java:500) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	at org.elasticsearch.ingest.Pipeline.create(Pipeline.java:81) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	at org.elasticsearch.ingest.IngestService.innerUpdatePipelines(IngestService.java:1123) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	... 12 more
	Suppressed: org.elasticsearch.script.GeneralScriptException: Failed to compile inline script [ctx._tmp_json_message != null] using lang [painless]
		at org.elasticsearch.script.ScriptCache.compile(ScriptCache.java:119) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.script.ScriptService.compile(ScriptService.java:634) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.ingest.ConditionalProcessor.<init>(ConditionalProcessor.java:80) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.ingest.ConditionalProcessor.<init>(ConditionalProcessor.java:61) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.ingest.ConfigurationUtils.readProcessor(ConfigurationUtils.java:628) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.ingest.ConfigurationUtils.readProcessor(ConfigurationUtils.java:580) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.ingest.ConfigurationUtils.readProcessorConfigs(ConfigurationUtils.java:500) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.ingest.Pipeline.create(Pipeline.java:81) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.ingest.IngestService.innerUpdatePipelines(IngestService.java:1123) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.ingest.IngestService.applyClusterState(IngestService.java:1099) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:539) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:526) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:498) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:429) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:916) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:217) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:183) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
		at java.lang.Thread.run(Thread.java:1583) ~[?:?]
	Caused by: java.lang.IllegalArgumentException: mock painless does not know how to handle context [processor_conditional]
		at org.elasticsearch.xpack.ml.integration.MlNativeIntegTestCase$MockPainlessScriptEngine.compile(MlNativeIntegTestCase.java:454) ~[javaRestTest/:?]
		at org.elasticsearch.script.ScriptCache.lambda$compile$0(ScriptCache.java:108) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.common.cache.Cache.computeIfAbsent(Cache.java:418) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.script.ScriptCache.compile(ScriptCache.java:90) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		... 20 more
	Suppressed: org.elasticsearch.script.GeneralScriptException: Failed to compile inline script [ctx._tmp_json_message != null] using lang [painless]
		at org.elasticsearch.script.ScriptCache.compile(ScriptCache.java:119) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.script.ScriptService.compile(ScriptService.java:634) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.ingest.ConditionalProcessor.<init>(ConditionalProcessor.java:80) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.ingest.ConditionalProcessor.<init>(ConditionalProcessor.java:61) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.ingest.ConfigurationUtils.readProcessor(ConfigurationUtils.java:628) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.ingest.ConfigurationUtils.readProcessor(ConfigurationUtils.java:580) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.ingest.ConfigurationUtils.readProcessorConfigs(ConfigurationUtils.java:500) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.ingest.Pipeline.create(Pipeline.java:81) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.ingest.IngestService.innerUpdatePipelines(IngestService.java:1123) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.ingest.IngestService.applyClusterState(IngestService.java:1099) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:539) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:526) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:498) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:429) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:916) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:217) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:183) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
		at java.lang.Thread.run(Thread.java:1583) ~[?:?]
	Caused by: java.lang.IllegalArgumentException: mock painless does not know how to handle context [processor_conditional]
		at org.elasticsearch.xpack.ml.integration.MlNativeIntegTestCase$MockPainlessScriptEngine.compile(MlNativeIntegTestCase.java:454) ~[javaRestTest/:?]
		at org.elasticsearch.script.ScriptCache.lambda$compile$0(ScriptCache.java:108) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.common.cache.Cache.computeIfAbsent(Cache.java:418) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		at org.elasticsearch.script.ScriptCache.compile(ScriptCache.java:90) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
		... 20 more
Caused by: java.lang.IllegalArgumentException: mock painless does not know how to handle context [processor_conditional]
	at org.elasticsearch.xpack.ml.integration.MlNativeIntegTestCase$MockPainlessScriptEngine.compile(MlNativeIntegTestCase.java:454) ~[javaRestTest/:?]
	at org.elasticsearch.script.ScriptCache.lambda$compile$0(ScriptCache.java:108) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	at org.elasticsearch.common.cache.Cache.computeIfAbsent(Cache.java:418) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	at org.elasticsearch.script.ScriptCache.compile(ScriptCache.java:90) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	at org.elasticsearch.script.ScriptService.compile(ScriptService.java:634) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	at org.elasticsearch.ingest.ConditionalProcessor.<init>(ConditionalProcessor.java:80) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	at org.elasticsearch.ingest.ConditionalProcessor.<init>(ConditionalProcessor.java:61) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	at org.elasticsearch.ingest.ConfigurationUtils.readProcessor(ConfigurationUtils.java:628) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	at org.elasticsearch.ingest.ConfigurationUtils.readProcessor(ConfigurationUtils.java:580) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	at org.elasticsearch.ingest.ConfigurationUtils.readProcessorConfigs(ConfigurationUtils.java:500) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	at org.elasticsearch.ingest.Pipeline.create(Pipeline.java:81) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	at org.elasticsearch.ingest.IngestService.innerUpdatePipelines(IngestService.java:1123) ~[elasticsearch-8.12.0-SNAPSHOT.jar:8.12.0-SNAPSHOT]
	... 12 more
```

**Comment by droberts195** [comment]
Classifying as `low-risk`. It's something missing from a test mock: `mock painless does not know how to handle context`

**Comment by pxsalehi** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/qzm4lg6c35nn2
