### ISSUE TITLE
[CI] RestClientMultipleHostsIntegTests testNodeSelector failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#101593]
**Build scan:**
https://gradle-enterprise.elastic.co/s/gf7iabc7cwhw6/tests/:client:rest:test/org.elasticsearch.client.RestClientMultipleHostsIntegTests/testNodeSelector
**Reproduction line:**
```
null
```

**Applicable branches:**
8.11

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.client.RestClientMultipleHostsIntegTests&tests.test=testNodeSelector

**Failure excerpt:**
```
java.lang.RuntimeException: error while performing request

  at __randomizedtesting.SeedInfo.seed([F6896B299EBE3E08:92B11EF655E38D2A]:0)
  at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:940)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:300)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
  at org.elasticsearch.client.RestClientSingleHostTests.performRequestSyncOrAsync(RestClientSingleHostTests.java:639)
  at org.elasticsearch.client.RestClientMultipleHostsIntegTests.testNodeSelector(RestClientMultipleHostsIntegTests.java:313)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

  Caused by: org.apache.http.ProtocolException: Not a valid protocol version: [0x1e][0x1f]Æ[0x21]org.gradle.api.internal.tasks.testing.worker.RemoteTestClassProcessor[0x67]Æ[0x69]org.gradle.api.internal.tasks.testing.worker.RemoteTestClassProcessorstartProcessing[0xbf][0xc0][0xc1][0xc2]Æ[0xc4]org.gradle.api.internal.tasks.testing.worker.RemoteTestClassProcessorprocessTestClass[0x11b]·org.gradle.api.internal.tasks.testing.TestClassRunInfoÀ[0x154]org.elasticsearch.client.HeapBufferedAsyncResponseConsumerTests[0x194][0x195][0x196]¸org.elasticsearch.client.RestClientGzipCompressionTests[0x1cf][0x1d0][0x1d1]Æ[0x1d3]org.gradle.api.internal.tasks.testing.worker.RemoteTestClassProcessorstop[0x21e][0x21f]

    at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:209)
    at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:245)
    at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87)
    at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40)
    at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
    at java.lang.Thread.run(Thread.java:1583)

    Caused by: org.apache.http.ParseException: Not a valid protocol version: [U+0000]Æorg.gradle.api.internal.tasks.testing.worker.RemoteTestClassProcessor[U+0000]Æorg.gradle.api.internal.tasks.testing.worker.RemoteTestClassProcessorstartProcessing[U+0000][U+0000]Æorg.gradle.api.internal.tasks.testing.worker.RemoteTestClassProcessorprocessTestClass·org.gradle.api.internal.tasks.testing.TestClassRunInfoÀorg.elasticsearch.client.HeapBufferedAsyncResponseConsumerTests[U+0000]¸org.elasticsearch.client.RestClientGzipCompressionTests[U+0000]Æorg.gradle.api.internal.tasks.testing.worker.RemoteTestClassProcessorstop[U+0000]

      at org.apache.http.message.BasicLineParser.parseProtocolVersion(BasicLineParser.java:148)
      at org.apache.http.message.BasicLineParser.parseStatusLine(BasicLineParser.java:366)
      at org.apache.http.impl.nio.codecs.DefaultHttpResponseParser.createMessage(DefaultHttpResponseParser.java:112)
      at org.apache.http.impl.nio.codecs.DefaultHttpResponseParser.createMessage(DefaultHttpResponseParser.java:50)
      at org.apache.http.impl.nio.codecs.AbstractMessageParser.parseHeadLine(AbstractMessageParser.java:156)
      at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:207)
      at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:245)
      at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87)
      at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40)
      at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
      at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
      at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
      at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
      at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
      at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
      at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
      at java.lang.Thread.run(Thread.java:1583)

```

**Comment by mattc58** [comment]
Spoke to @swallez and re-categorizing this as non-blocker

**Comment by swallez** [comment]
Quoting our chat (I was on PTO):
>  The error messages are weird, like if the http server started by the test is sending garbage. I've run the test on my machine and it works fine (unsurprising, this code hasn't changed for years). So my guess is that it's a transient error caused by something in the environment.
