### ISSUE TITLE
[CI] JdbcResultSetIT testGettingTimeWithoutCalendarWithNanos failing

### ISSUE THREAD

**Issue by maxhniebergall** [elastic/elasticsearch#101571]
**Build scan:**
https://gradle-enterprise.elastic.co/s/b7vlqpognhhxm/tests/:x-pack:plugin:sql:qa:jdbc:single-node:v7.17.7%23bwcTest/org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcResultSetIT/testGettingTimeWithoutCalendarWithNanos
**Reproduction line:**
```
./gradlew ':x-pack:plugin:sql:qa:jdbc:single-node:v7.17.7#bwcTest' -Dtests.class="org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcResultSetIT" -Dtests.method="testGettingTimeWithoutCalendarWithNanos" -Dtests.seed=D22DCA9765EA1886 -Dtests.bwc=true -Dtests.locale=uk -Dtests.timezone=Europe/Lisbon -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcResultSetIT&tests.test=testGettingTimeWithoutCalendarWithNanos

**Failure excerpt:**
```
java.lang.AssertionError: expected: java.sql.Time<06:32:38> but was: java.sql.Time<06:32:38>

  at __randomizedtesting.SeedInfo.seed([D22DCA9765EA1886:609A4814F6994CFC]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.failNotEquals(Assert.java:834)
  at org.junit.Assert.assertEquals(Assert.java:118)
  at org.junit.Assert.assertEquals(Assert.java:144)
  at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.lambda$testGettingTimeWithoutCalendarWithNanos$128(ResultSetTestCase.java:1304)
  at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:2025)
  at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:2013)
  at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.testGettingTimeWithoutCalendarWithNanos(ResultSetTestCase.java:1299)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by gmarouli** [comment]
One more failure: https://gradle-enterprise.elastic.co/s/lvopxaboa723e/tests/task/:x-pack:plugin:sql:qa:jdbc:single-node:javaRestTest/details/org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcResultSetIT/testGettingTimeWithoutCalendarWithNanos?top-execution=1

I wasn't able to reproduce it locally.

I didn't mute it because I could not retrieve the history to check how often it fails.

**Comment by thecoop** [comment]
Another one, this time on 7.17: https://gradle-enterprise.elastic.co/s/ozwgjuymyzfts/tests/task/:x-pack:plugin:sql:qa:jdbc:single-node:v7.16.3%23bwcTest/details/org.elasticsearch.xpack.sql.qa.jdbc.single_node.JdbcResultSetIT/testGettingTimeWithoutCalendarWithNanos?top-execution=1
