### ISSUE TITLE
use elasticsearch java client query api with docvalueFields and storedField, and response is error!!

### ISSUE THREAD

**Issue by Mrruigege** [elastic/elasticsearch#101785]
### Elasticsearch Version

8.0.0

### Java Version

8.9.1

### OS Version

ubuntu

### Problem Description

i want to use es query with docvalue_fields and stored_fields. in kibana，it's ok. but when i use use elasticsearch java client to query, it response error! the error is:

java.lang.NullPointerException
    at org.eclipse.parsson.JsonGeneratorImpl.writeEscapedString(JsonGeneratorImpl.java:539)
        at org.eclipse.parsson.JsonGeneratorImpl.write(JsonGeneratorImpl.java:359)
        at co.elastic.clients.elasticsearch.core.search.Hit.serializeInternal(Hit.java:303)
        at co.elastic.clients.elasticsearch.core.search.Hit.serialize(Hit.java:293)
        at co.elastic.clients.elasticsearch.core.search.HitsMetadata.serializeInternal(HitsMetadata.java:130)
        at co.elastic.clients.elasticsearch.core.search.HitsMetadata.serialize(HitsMetadata.java:115)
        at co.elastic.clients.elasticsearch.core.search.ResponseBody.serializeInternal(ResponseBody.java:248)
        at co.elastic.clients.elasticsearch.core.search.ResponseBody.serialize(ResponseBody.java:232)
        at co.elastic.clients.json.JsonpUtils.toString(JsonpUtils.java:408)
        at co.elastic.clients.json.JsonpUtils.toString(JsonpUtils.java:345)
        at co.elastic.clients.elasticsearch.core.search.ResponseBody.toString(ResponseBody.java:311)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.io.PrintStream.println(PrintStream.java:897)
        at com.example.demoproject.ElasticsearchTest.test(ElasticsearchTest.java:53)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        Suppressed: jakarta.json.stream.JsonGenerationException: Generating incomplete JSON
        at org.eclipse.parsson.JsonGeneratorImpl.close(JsonGeneratorImpl.java:519)
        at co.elastic.clients.json.JsonpUtils.toString(JsonpUtils.java:407)
        ... 74 more

### 1、create index and add data
PUT device_info
{
  "settings": {
    "number_of_shards": 1, 
    "number_of_replicas": 2
  }
  , "mappings": {
    "properties": {
      "city": {
        "type": "keyword"
      }
    }
  }
}

PUT device_info/_bulk
{"index": {"_id": "1"}}
{"city": "chengdu"}
{"index": {"_id": "2"}}
{"city": "chengdu"}

### 2、use kibana query (return no error)
GET device_info/_search
{
  "stored_fields": ["_none_"],
  "docvalue_fields": ["city"], 
  "query": {
    "term": {
      "city": {
        "value": "chengdu"
      }
    }
  }
}

### 3、use elasticsearch java client to query
 @Test
    public void test() throws IOException {
        ApiTypeHelper.DANGEROUS_disableRequiredPropertiesCheck(true);
        SearchResponse<Void> response = elasticsearchClient.search(s -> s
                .index("device_info")
                .query(q -> q
                        .term(t -> t
                                .field("city")
                                .value("chengdu")))
                .docvalueFields(d -> d
                        .field("city"))
                .storedFields("_none_"), Void.class);
        System.out.println(response);
        ApiTypeHelper.DANGEROUS_disableRequiredPropertiesCheck(false);
    }

error info : 
java.lang.NullPointerException
    at org.eclipse.parsson.JsonGeneratorImpl.writeEscapedString(JsonGeneratorImpl.java:539)
        at org.eclipse.parsson.JsonGeneratorImpl.write(JsonGeneratorImpl.java:359)
        at co.elastic.clients.elasticsearch.core.search.Hit.serializeInternal(Hit.java:303)
        at co.elastic.clients.elasticsearch.core.search.Hit.serialize(Hit.java:293)
        at co.elastic.clients.elasticsearch.core.search.HitsMetadata.serializeInternal(HitsMetadata.java:130)
        at co.elastic.clients.elasticsearch.core.search.HitsMetadata.serialize(HitsMetadata.java:115)
        at co.elastic.clients.elasticsearch.core.search.ResponseBody.serializeInternal(ResponseBody.java:248)
        at co.elastic.clients.elasticsearch.core.search.ResponseBody.serialize(ResponseBody.java:232)
        at co.elastic.clients.json.JsonpUtils.toString(JsonpUtils.java:408)
        at co.elastic.clients.json.JsonpUtils.toString(JsonpUtils.java:345)
        at co.elastic.clients.elasticsearch.core.search.ResponseBody.toString(ResponseBody.java:311)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.io.PrintStream.println(PrintStream.java:897)
        at com.example.demoproject.ElasticsearchTest.test(ElasticsearchTest.java:53)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        Suppressed: jakarta.json.stream.JsonGenerationException: Generating incomplete JSON
        at org.eclipse.parsson.JsonGeneratorImpl.close(JsonGeneratorImpl.java:519)
        at co.elastic.clients.json.JsonpUtils.toString(JsonpUtils.java:407)
        ... 74 more

**Comment by Mrruigege** [comment]
this is java test
`@Test
    public void test() throws IOException {
        ApiTypeHelper.DANGEROUS_disableRequiredPropertiesCheck(true);
        SearchResponse<Void> response = elasticsearchClient.search(s -> s
                .index("device_info")
                .query(q -> q
                        .term(t -> t
                                .field("city")
                                .value("成都市")))
                .docvalueFields(d -> d
                        .field("city"))
                .storedFields("_none_"), Void.class);
        System.out.println(response);
        ApiTypeHelper.DANGEROUS_disableRequiredPropertiesCheck(false);
    }`

**Comment by Mrruigege** [comment]
![Uploading 截屏2023-11-03 23.37.11.png…]()

**Comment by Mrruigege** [comment]
<img width="1134" alt="Hit.class" src="https://github.com/elastic/elasticsearch/assets/38402567/b8c04ef9-43d3-4009-829e-6164a9520984">
i think the '_id' should null judgment

**Comment by mark-vieira** [comment]
@swallez should these issues be moved to the https://github.com/elastic/elasticsearch-java repo?

**Comment by swallez** [comment]
@mark-vieira yes, definitely. Feel free to move issues about `co.elastic.clients` without asking 😉
