### ISSUE TITLE
[CI] ApmIT testApmIntegration failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#101793]
Three recent failures, all on Windows

- https://gradle-enterprise.elastic.co/s/ubisw5ojzjtkc/tests/task/:test:external-modules:test-apm-integration:javaRestTest/details/org.elasticsearch.test.apmintegration.ApmIT/testApmIntegration?page=eyJvdXRwdXQiOnsiMCI6Mn19&top-execution=1
- https://gradle-enterprise.elastic.co/s/jyjthj5oiq3jq/tests/task/:test:external-modules:test-apm-integration:javaRestTest/details/org.elasticsearch.test.apmintegration.ApmIT/testApmIntegration?top-execution=1
- https://gradle-enterprise.elastic.co/s/rkbhvghgl3ipk/tests/task/:test:external-modules:test-apm-integration:javaRestTest/details/org.elasticsearch.test.apmintegration.ApmIT/testApmIntegration?top-execution=1

**Build scan:**
https://gradle-enterprise.elastic.co/s/ubisw5ojzjtkc/tests/:test:external-modules:test-apm-integration:javaRestTest/org.elasticsearch.test.apmintegration.ApmIT/testApmIntegration
**Reproduction line:**
```
gradlew ':test:external-modules:test-apm-integration:javaRestTest' --tests "org.elasticsearch.test.apmintegration.ApmIT.testApmIntegration" -Dtests.seed=8AD21A2C81F39C87 -Dtests.locale=et-EE -Dtests.timezone=Asia/Omsk -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.test.apmintegration.ApmIT&tests.test=testApmIntegration

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: a map with size <0>
     but: map size was <6>

  at __randomizedtesting.SeedInfo.seed([8AD21A2C81F39C87:5043BADF6723031F]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.test.apmintegration.ApmIT.testApmIntegration(ApmIT.java:107)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by pgomulka** [comment]
given apm is not enabled yet, I will change the label to low-risk

**Comment by pgomulka** [comment]
I can confirm it was failing reliably on my windows laptop. It was the problem in how I was paring an NDJson
I was using UTF_8 for reading a stream, but still using the System.lineSeparator for spliting the lines.
raised a pr to fix it

**Comment by valeriy42** [comment]
Another failure on CI: https://gradle-enterprise.elastic.co/s/3f6viuklbhb42
