### ISSUE TITLE
[CI] WindowsServiceTests test16InstallSpecialCharactersInJdkPath failing

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#101878]
**Build scan:**
https://gradle-enterprise.elastic.co/s/to5mcpmspdyuy/tests/:qa:os:destructiveDistroTest.default-windows-archive/org.elasticsearch.packaging.test.WindowsServiceTests/test16InstallSpecialCharactersInJdkPath
**Reproduction line:**
```
null
```

**Applicable branches:**
7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.WindowsServiceTests&tests.test=test16InstallSpecialCharactersInJdkPath

**Failure excerpt:**
```
java.lang.RuntimeException: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\a (special) jdk -> C:\tmp\elasticsearch\jdk

  at __randomizedtesting.SeedInfo.seed([BFA63EFAC056AE11:BD8D33D12A8A3582]:0)
  at org.elasticsearch.packaging.util.FileUtils.mv(FileUtils.java:136)
  at org.elasticsearch.packaging.test.WindowsServiceTests.test16InstallSpecialCharactersInJdkPath(WindowsServiceTests.java:162)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

  Caused by: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\a (special) jdk -> C:\tmp\elasticsearch\jdk

    at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
    at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
    at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:414)
    at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:291)
    at java.nio.file.Files.move(Files.java:1430)
    at org.elasticsearch.packaging.util.FileUtils.mv(FileUtils.java:134)
    at org.elasticsearch.packaging.test.WindowsServiceTests.test16InstallSpecialCharactersInJdkPath(WindowsServiceTests.java:162)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1583)

```

**Comment by rjernst** [comment]
This looks like https://github.com/elastic/elasticsearch/issues/96026 cropping up again. It's a test only issue, and we have been unable to find what other process is holding open these temporary files which we create in the tests.

**Comment by williamrandolph** [comment]
The failure on this issue is the only time this test has failed in the last 90 days, according to [Gradle CI Reports](https://gradle-enterprise.elastic.co/scans/tests?search.buildOutcome=failure&search.relativeStartTime=P90D&search.tags=WINDOWS&search.timeZoneId=America%2FNew_York&tests.container=org.elasticsearch.packaging.test.WindowsServiceTests&tests.test=test16InstallSpecialCharactersInJdkPath), and WindowsServiceTest failures [in the last 28 days](https://gradle-enterprise.elastic.co/scans/tests?search.buildOutcome=failure&search.relativeStartTime=P28D&search.tags=WINDOWS&search.timeZoneId=America%2FNew_York&tests.container=org.elasticsearch.packaging.test.WindowsServiceTests&tests.test=test30StartStop) are different ones.

I'm going to close it for now. We should reopen it if it we see it more frequently (or if I've turned out to have missed more frequent recent occurrences.)
