### ISSUE TITLE
[CI] SearchIdleIT testSearchIdleStats failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#101827]
I also saw this when running `./gradlew :server:test :server:internalclustertest` locally on `main`. Not reliably tho.

**Build scan:**
https://gradle-enterprise.elastic.co/s/kf7zb4ip7b64c/tests/:server:internalClusterTest/org.elasticsearch.index.shard.SearchIdleIT/testSearchIdleStats
**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.index.shard.SearchIdleIT.testSearchIdleStats" -Dtests.seed=F50C56E58F2BD0B3 -Dtests.locale=es-NI -Dtests.timezone=Mexico/BajaSur -Druntime.java=21
```

**Applicable branches:**
main, 8.10

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.index.shard.SearchIdleIT&tests.test=testSearchIdleStats

**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at __randomizedtesting.SeedInfo.seed([F50C56E58F2BD0B3:458C7B60682BD7E2]:0)
  at org.junit.Assert.fail(Assert.java:86)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.junit.Assert.assertTrue(Assert.java:52)
  at org.elasticsearch.index.shard.SearchIdleIT.testSearchIdleStats(SearchIdleIT.java:234)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by quux00** [comment]
I was able to reproduce this twice out 100 runs, but it doesn't reproduce reliably.

For both failures in my testing it is the second to last assert that fails:

```
        assertTrue(Arrays.stream(statsResponse.getShards()).allMatch(ShardStats::isSearchIdle));
```

Is this ticket misrouted? I don't think this is search team code? This is an index setting and the test is looking at shard stats. I think the test is hitting the equivalent of the <index>/_stats endpoint. I would have thought this is more for core/infra or maybe distributed?

**Comment by mattc58** [comment]
Changing this to `medium-risk` and will wait for @rjernst or @henningandersen to see if it makes sense in their areas

**Comment by thecoop** [comment]
Could this just be a slow cluster problem? There's a check immediately above that for the exact same condition that is failing at the subsequent line - so it would only progress if the condition is true or the timeout is hit. Do we just need to make hte timeout a bit more lenient here?

**Comment by thecoop** [comment]
I don't think this is core/infra anyway - its to do with shard stats, which is distributed

**Comment by DaveCTurner** [comment]
>  its to do with shard stats, which is distributed

That's not the case, different shard stats are owned by different teams depending on the area to which they relate. In this case it's about the search-idle subsystem which falls somewhere between distrib and search, but since the failing test was relatively [recently added](#96213), and not by the distrib team, I think we need the search team to take ownership of this.

**Comment by lkts** [comment]
It does seem like we just need a bigger wait time, i opened #107881.
