### ISSUE TITLE
Snapshot sometimes lose some shards data

### ISSUE THREAD

**Issue by aqlu** [elastic/elasticsearch#10183]
I used 1.4.2 version of elasticsearch,  each index is 10 shards,  when use snapshot to backup indices sometimes lose shards. 

Some of the information listed below：

```
[elasticsearch@lin-mongo-65-182 indices] curl -XPUT 'localhost:9200/_snapshot/log_backup/snapshot-logstash-2015.03.15_20150320-160201?wait_for_completion=true&pretty' -d '{
       "indices":"logstash-2015.03.15"
 }'
{
  "snapshot" : {
    "snapshot" : "snapshot-logstash-2015.03.15_20150320-160201",
    "indices" : [ "logstash-2015.03.15" ],
    "state" : "SUCCESS",
    "start_time" : "2015-03-20T08:35:41.641Z",
    "start_time_in_millis" : 1426840541641,
    "end_time" : "2015-03-20T08:36:23.932Z",
    "end_time_in_millis" : 1426840583932,
    "duration_in_millis" : 42291,
    "failures" : [ ],
    "shards" : {
      "total" : 10,
      "failed" : 0,
      "successful" : 10
    }
  }
}
```
result is snapshot successful for 10 shards; but  when i restore this snapshot, ES report many exception:

```
[2015-03-20 16:09:12,088][WARN ][indices.cluster          ] [lin-65-181] [logstash-2015.03.15][0] failed to start shard
org.elasticsearch.index.gateway.IndexShardGatewayRecoveryException: [logstash-2015.03.15][0] failed recovery
	at org.elasticsearch.index.gateway.IndexShardGatewayService$1.run(IndexShardGatewayService.java:185)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.snapshots.IndexShardRestoreFailedException: [logstash-2015.03.15][0] restore failed
	at org.elasticsearch.index.snapshots.IndexShardSnapshotAndRestoreService.restore(IndexShardSnapshotAndRestoreService.java:130)
	at org.elasticsearch.index.gateway.IndexShardGatewayService$1.run(IndexShardGatewayService.java:127)
	... 3 more
Caused by: org.elasticsearch.index.snapshots.IndexShardRestoreFailedException: [logstash-2015.03.15][0] failed to restore snapshot [snapshot-logstash-2015.03.15_20150320-160201]
	at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository.restore(BlobStoreIndexShardRepository.java:165)
	at org.elasticsearch.index.snapshots.IndexShardSnapshotAndRestoreService.restore(IndexShardSnapshotAndRestoreService.java:124)
	... 4 more
Caused by: org.elasticsearch.index.snapshots.IndexShardRestoreFailedException: [logstash-2015.03.15][0] failed to read shard snapshot file
	at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$Context.loadSnapshot(BlobStoreIndexShardRepository.java:319)
	at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$RestoreContext.restore(BlobStoreIndexShardRepository.java:709)
	at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository.restore(BlobStoreIndexShardRepository.java:162)
	... 5 more
Caused by: java.io.FileNotFoundException: /home/elasticsearch/ES_backup/log/indices/logstash-2015.03.15/0/snapshot-snapshot-logstash-2015.03.15_20150320-160201 (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at org.elasticsearch.common.blobstore.fs.FsBlobContainer.openInput(FsBlobContainer.java:79)
	at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$Context.loadSnapshot(BlobStoreIndexShardRepository.java:316)
	... 7 more
```

I jump to the backup directory, found miss "0" directory for index "logstash-2015.03.15".
```
[elasticsearch@lin-mongo-65-182 indices]$ pwd
/home/elasticsearch/ES_backup/log/indices
[elasticsearch@lin-mongo-65-182 indices]$ tree -L 2 ./
./
├── logstash-2015.03.14
│   ├── 0
│   ├── 1
│   ├── 2
│   ├── 3
│   ├── 4
│   ├── 5
│   ├── 6
│   ├── 7
│   ├── 8
│   └── 9
└── logstash-2015.03.15
    ├── 1
    ├── 2
    ├── 3
    ├── 4
    ├── 5
    ├── 6
    ├── 7
    ├── 8
    ├── 9
    └── snapshot-snapshot-logstash-2015.03.15_20150320-160201
```

**Comment by tlrx** [comment]
@aqlu thanks for reporting. How frequent is this error? Do you use a specific tool to do the snapshots?

I didn't reproduce this issue. Can you please try to reproduce it with TRACE log enabled for the snapshots and post the output here?

To enable TRACE logging:
- edit logging.yml
- add `snapshots: TRACE` under `logger` section
- you should see traces like this: `[TRACE][snapshots                ] [Wind Warrior] [my_backup:snapshot_1] Updating shard [[library2][0]] with status [SUCCESS]`

**Comment by aqlu** [comment]
@tlrx Thanks for you reply. I' m so sorry, it's not a ES bug, It's some problems in my environment about NFS on one ES node, some data of shards is saved into local disk. 
Thanks for your advice again!

**Comment by tlrx** [comment]
Ok, thanks to let us know :)

I close the issue, feel free to reopen if needed.
