### ISSUE TITLE
[CI] MlAssignmentPlannerUpgradeIT testMlAssignmentPlannerUpgrade failing

### ISSUE THREAD

**Issue by williamrandolph** [elastic/elasticsearch#101926]
This looks like we need a test assumption so we don't run this in environments where it can't succeed: `Reason: This node has insufficient allocated processors. Available processors [1], free processors [0], processors required for each allocation of this model [1]`. This integration test was introduced in https://github.com/elastic/elasticsearch/pull/98874

**Build scan:**
https://gradle-enterprise.elastic.co/s/csfzw3sbupz3w/tests/:x-pack:qa:rolling-upgrade:v8.11.1%23oldClusterTest/org.elasticsearch.upgrades.MlAssignmentPlannerUpgradeIT/testMlAssignmentPlannerUpgrade
**Reproduction line:**
```
./gradlew ':x-pack:qa:rolling-upgrade:v8.11.1#oldClusterTest' -Dtests.class="org.elasticsearch.upgrades.MlAssignmentPlannerUpgradeIT" -Dtests.method="testMlAssignmentPlannerUpgrade" -Dtests.seed=9733484CA2FD9E9F -Dtests.bwc=true -Dtests.configure_test_clusters_with_one_processor=true -Dtests.locale=sr-CS -Dtests.timezone=America/Thule -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.MlAssignmentPlannerUpgradeIT&tests.test=testMlAssignmentPlannerUpgrade

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:37329], URI [/_ml/trained_models/new_memory_format/deployment/_start?timeout=40s&wait_for=started&inference_threads=1&model_threads=1], status line [HTTP/1.1 429 Too Many Requests]
Warnings: [Deprecated field [model_threads] used, expected [number_of_allocations] instead, Deprecated field [inference_threads] used, expected [threads_per_allocation] instead]
{"error":{"root_cause":[{"type":"status_exception","reason":"Could not start deployment because no ML nodes with sufficient capacity were found"}],"type":"status_exception","reason":"Could not start deployment because no ML nodes with sufficient capacity were found","caused_by":{"type":"illegal_state_exception","reason":"Could not start deployment because no suitable nodes were found, allocation explanation [Could not assign (more) allocations on node [1kxIZS2TTfiMWWGQta8D1g]. Reason: This node has insufficient allocated processors. Available processors [1], free processors [0], processors required for each allocation of this model [1]|Could not assign (more) allocations on node [Rt9lb1FKR0q_71eP1m1hzA]. Reason: This node has insufficient allocated processors. Available processors [1], free processors [0], processors required for each allocation of this model [1]|Could not assign (more) allocations on node [f_9n2rEFRIitR0uvnk3BLA]. Reason: This node has insufficient allocated processors. Available processors [1], free processors [0], processors required for each allocation of this model [1]]"}},"status":429}

  at __randomizedtesting.SeedInfo.seed([9733484CA2FD9E9F:382316FB07353418]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
  at org.elasticsearch.upgrades.MlAssignmentPlannerUpgradeIT.startDeployment(MlAssignmentPlannerUpgradeIT.java:279)
  at org.elasticsearch.upgrades.MlAssignmentPlannerUpgradeIT.startDeployment(MlAssignmentPlannerUpgradeIT.java:266)
  at org.elasticsearch.upgrades.MlAssignmentPlannerUpgradeIT.setupDeployments(MlAssignmentPlannerUpgradeIT.java:210)
  at org.elasticsearch.upgrades.MlAssignmentPlannerUpgradeIT.testMlAssignmentPlannerUpgrade(MlAssignmentPlannerUpgradeIT.java:72)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by mark-vieira** [comment]
This looks like a new test and is failing roughly 10% of the time. Can we mute?
![image](https://github.com/elastic/elasticsearch/assets/4106672/acdabd2b-44d2-485d-80f6-32284e664b2f)

**Comment by mark-vieira** [comment]
@williamrandolph Looks like mentioning "fix" and this issue in the mute PR accidentally closed this issue. Reopening.

**Comment by ldematte** [comment]
Another failure https://gradle-enterprise.elastic.co/s/yx7tu5b7vak6o/tests/task/:x-pack:qa:rolling-upgrade:v8.11.1%23oldClusterTest/details/org.elasticsearch.upgrades.MlAssignmentPlannerUpgradeIT/testMlAssignmentPlannerUpgrade?top-execution=1

It seems also to consistently fail for BwC on all versions ranging from 8.0.0 to 8.2.0, with a different error: https://gradle-enterprise.elastic.co/s/evw3pxch2yhww/tests/task/:x-pack:qa:rolling-upgrade:v8.0.1%23twoThirdsUpgradedTest/details/org.elasticsearch.upgrades.MlAssignmentPlannerUpgradeIT/testMlAssignmentPlannerUpgrade?top-execution=1

You might want to review that too, either bumping the assumeTrue version or adjusting the expected values.

**Comment by droberts195** [comment]
@valeriy42 the common thing about these failures is that they happen in the `single-processor-node-tests`. The solution in the past has been to make the deployments low priority, so they don't demand a particular number of processors - for example see #95490. Please can you either do the same here, or, if you think that the assignment planning aspect of the test would be ruined by doing this, add an `assumeFalse` that the test isn't running in a `single-processor-node-tests` job.

**Comment by droberts195** [comment]
Actually I just realised that there's going to be another problem here, which is that low priority deployments were only added in 8.6, in #91234. So that workaround isn't going to work for BWC tests.

**Comment by davidkyle** [comment]
The test actually creates 2 deployments, starting the 2nd will always fail on single processor tests due to insufficient CPUs being available. As we cannot use low priority deployments the only option is to skip the test for single processors, I opened #101957 to do that.

There is another upgrade test in the suite that also creates a deployment (`MLModelDeploymentsUpgradeIT`), I can't find any failures of that due to insufficient CPUs which is strange as if this test ran first `MLModelDeploymentsUpgradeIT` could not create its normal priority deployment

**Comment by mark-vieira** [comment]
> Actually I just realised that there's going to be another problem here, which is that low priority deployments were only added in 8.6, in #91234. So that workaround isn't going to work for BWC tests.

Correct, this is failing across other builds other than the single processor node tests, specifically BWC jobs for versions 8.0.0 -> 8.2.0.

![image](https://github.com/elastic/elasticsearch/assets/4106672/da3a43ed-5af7-4add-80f8-af75d43f9132)

**Comment by mark-vieira** [comment]
I've reopened this issue and remuted the test.
