### ISSUE TITLE
Failure generating build-complete archive on Windows

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#102022]
https://gradle-enterprise.elastic.co/s/nenpfb4iogx3k/failure?expanded-stacktrace=WyIwLTEiXQ#1

```
* Exception is:
java.lang.RuntimeException: java.io.IOException: request to write '149' bytes exceeds size in header of '0' bytes for entry './PaxHeaders.X/modules/data-streams/build/testrun/javaRestTest/temp/test-cluster210746955614619588/'
	at org.elasticsearch.gradle.internal.ElasticsearchBuildCompletePlugin$BuildFinishedFlowAction.createBuildArchiveTar(ElasticsearchBuildCompletePlugin.java:210)
	at org.elasticsearch.gradle.internal.ElasticsearchBuildCompletePlugin$BuildFinishedFlowAction.execute(ElasticsearchBuildCompletePlugin.java:135)
	at org.elasticsearch.gradle.internal.ElasticsearchBuildCompletePlugin$BuildFinishedFlowAction.execute(ElasticsearchBuildCompletePlugin.java:108)
	at org.gradle.configurationcache.flow.FlowScheduler.schedule(FlowScheduler.kt:48)
```

**Comment by mark-vieira** [comment]
@breskeby is this possibly fallout from #96475?
