### ISSUE TITLE
ES|QL: NPE on topN layout planning

### ISSUE THREAD

**Issue by luigidellaquila** [elastic/elasticsearch#102123]
Testing on CSV Spec dataset

```
from employees | sort height.half_float ASC | eval  height.half_float = -1679932072 |  sort  first_name DESC
```

```
{
    "error": {
        "root_cause": [
            {
                "type": "null_pointer_exception",
                "reason": "Cannot invoke \"org.elasticsearch.xpack.esql.planner.Layout$ChannelAndType.channel()\" because the return value of \"org.elasticsearch.xpack.esql.planner.Layout.get(org.elasticsearch.xpack.ql.expression.NameId)\" is null"
            }
        ],
        "type": "null_pointer_exception",
        "reason": "Cannot invoke \"org.elasticsearch.xpack.esql.planner.Layout$ChannelAndType.channel()\" because the return value of \"org.elasticsearch.xpack.esql.planner.Layout.get(org.elasticsearch.xpack.ql.expression.NameId)\" is null",
        "suppressed": [
            {
                "type": "task_cancelled_exception",
                "reason": "parent task was cancelled [cancelled]"
            },
            {
                "type": "task_cancelled_exception",
                "reason": "parent task was cancelled [cancelled]"
            }
        ]
    },
    "status": 500
}
```

```
Execution time: [29]ms
[2023-11-14T09:56:49,008][WARN ][o.e.x.e.a.EsqlResponseListener] [runTask-0] Request failed with status [INTERNAL_SERVER_ERROR]: java.lang.NullPointerException: Cannot invoke "org.elasticsearch.xpack.esql.planner.Layout$ChannelAndType.channel()" because the return value of "org.elasticsearch.xpack.esql.planner.Layout.get(org.elasticsearch.xpack.ql.expression.NameId)" is null
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.lambda$planTopN$3(LocalExecutionPlanner.java:420)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planTopN(LocalExecutionPlanner.java:430)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:188)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planOutput(LocalExecutionPlanner.java:310)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:224)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:168)
        at org.elasticsearch.xpack.esql.plugin.ComputeService.runCompute(ComputeService.java:260)
```

**Comment by luigidellaquila** [comment]
Fixed in latest snapshot, most likely thanks to https://github.com/elastic/elasticsearch/pull/102399
