### ISSUE TITLE
[CI] CronEvalCliTests test10Install failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#102174]
Looking through history I see a number of these failures trying to get the rpm lock, but all on 7.17. This one happened on a pull request of mine. It's not clear why we would be failing to get that lock as we don't do any parallel packaging test execution.

**Build scan:**
https://gradle-enterprise.elastic.co/s/xpvgr55f5hmpc/tests/:qa:packaging:destructiveDistroTest.default-rpm/org.elasticsearch.packaging.test.CronEvalCliTests/test10Install
**Reproduction line:**
```
null
```

**Applicable branches:**
main, 7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.CronEvalCliTests&tests.test=test10Install

**Failure excerpt:**
```
java.lang.RuntimeException: Installing distribution org.elasticsearch.packaging.util.Distribution@6b5c0f8d failed: exitCode = [1] stdout = [] stderr = [error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Resource temporarily unavailable)]

  at __randomizedtesting.SeedInfo.seed([E0C3854BF831E200:C9989B3A4A15D5A]:0)
  at org.elasticsearch.packaging.util.Packages.installPackage(Packages.java:93)
  at org.elasticsearch.packaging.util.Packages.installPackage(Packages.java:82)
  at org.elasticsearch.packaging.test.PackagingTestCase.install(PackagingTestCase.java:244)
  at org.elasticsearch.packaging.test.CronEvalCliTests.test10Install(CronEvalCliTests.java:25)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by mark-vieira** [comment]
Duplicate of https://github.com/elastic/elasticsearch/issues/102115#issuecomment-1809603605
