### ISSUE TITLE
[CI] PackageTests test83SystemdMask failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#102115]
**Build scan:**
https://gradle-enterprise.elastic.co/s/orgpt636ladgq/tests/:qa:packaging:destructiveDistroTest.default-rpm/org.elasticsearch.packaging.test.PackageTests/test83SystemdMask
**Reproduction line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.PackageTests&tests.test=test83SystemdMask

**Failure excerpt:**
```
java.lang.RuntimeException: Installing distribution org.elasticsearch.packaging.util.Distribution@248a98e3 failed: exitCode = [1] stdout = [] stderr = [error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Resource temporarily unavailable)]

  at __randomizedtesting.SeedInfo.seed([5D1DD4DB0E30BE9B:6A8EBE13CA7634E7]:0)
  at org.elasticsearch.packaging.util.Packages.installPackage(Packages.java:93)
  at org.elasticsearch.packaging.util.Packages.installPackage(Packages.java:82)
  at org.elasticsearch.packaging.test.PackagingTestCase.install(PackagingTestCase.java:244)
  at org.elasticsearch.packaging.test.PackageTests.test83SystemdMask(PackageTests.java:342)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by mark-vieira** [comment]
I hit this today too: https://github.com/elastic/elasticsearch/issues/102115#issuecomment-1809603605

I'm wondering why this is happening. I actually see a handful of these on the 7.17 branch and the first incidents of this happening on `main` started today. I'm not aware of any changes here. Perhaps some kind of update to our CI images? This looks to be unique to our RHEL jobs.

**Comment by mark-vieira** [comment]
One theory is that there's something else trying to use the package manager at the time out of band of the build. Perhaps a service of some kind. @brianseeders do we have system logs somewhere we can access? I recall you setting up agent and sending logs/metrics somewhere.

**Comment by brianseeders** [comment]
```
01:02:24.000
system.syslog
Starting dnf automatic...
```

I'll create an issue to make sure automatic updates are disabled across the agents, and another to get access to the buildkite agent logs/metrics cluster sorted out.

**Comment by mark-vieira** [comment]
Good to know we're not going mad and at least _some_ of my theories have merit.
