### ISSUE TITLE
[CI] EsqlDisruptionIT testFromStatsGroupingByKeywordWithNulls failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#102338]
This particular test has only failed once but I see 4 failures in the past two weeks in `EsqlDisruptionIT` with the `no such shard` error. Perhaps there's a commonality there.

**Build scan:**
https://gradle-enterprise.elastic.co/s/iu6vissruunyu/tests/:x-pack:plugin:esql:internalClusterTest/org.elasticsearch.xpack.esql.action.EsqlDisruptionIT/testFromStatsGroupingByKeywordWithNulls

**Reproduction line:**
```
./gradlew ':x-pack:plugin:esql:internalClusterTest' --tests "org.elasticsearch.xpack.esql.action.EsqlDisruptionIT.testFromStatsGroupingByKeywordWithNulls" -Dtests.seed=1111E4BB162CF37F -Dtests.locale=pl-PL -Dtests.timezone=Europe/Chisinau -Druntime.java=17
```

**Applicable branches:**
main, 8.11

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.esql.action.EsqlDisruptionIT&tests.test=testFromStatsGroupingByKeywordWithNulls

**Failure excerpt:**
```
org.elasticsearch.index.shard.ShardNotFoundException: no such shard

  at __randomizedtesting.SeedInfo.seed([1111E4BB162CF37F:C3663C55DA8CBFF1]:0)
  at org.elasticsearch.index.IndexService.getShard(IndexService.java:323)
  at org.elasticsearch.xpack.esql.plugin.ComputeService.acquireSearchContexts(ComputeService.java:290)
  at org.elasticsearch.xpack.esql.plugin.ComputeService$DataNodeRequestHandler.messageReceived(ComputeService.java:430)
  at org.elasticsearch.xpack.esql.plugin.ComputeService$DataNodeRequestHandler.messageReceived(ComputeService.java:422)
  at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
  at org.elasticsearch.transport.InboundHandler.doHandleRequest(InboundHandler.java:288)
  at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:301)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by dnhatn** [comment]
I am re-labelling this medium-risk as it's a test-issue. I will look into this tomorrow.

**Comment by thecoop** [comment]
Another one: https://gradle-enterprise.elastic.co/s/3b67gltbd373m
