### ISSUE TITLE
[CI] FrozenExistenceDeciderIT testZeroToOne failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#102405]
**Build scan:**
https://gradle-enterprise.elastic.co/s/eewt3gpefj3xk/tests/:x-pack:plugin:autoscaling:internalClusterTest/org.elasticsearch.xpack.autoscaling.existence.FrozenExistenceDeciderIT/testZeroToOne

**Reproduction line:**
```
./gradlew ':x-pack:plugin:autoscaling:internalClusterTest' --tests "org.elasticsearch.xpack.autoscaling.existence.FrozenExistenceDeciderIT.testZeroToOne" -Dtests.seed=469675C6E5031553 -Dtests.locale=ar-DZ -Dtests.timezone=America/Argentina/San_Luis -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testZeroToOne'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.autoscaling.existence.FrozenExistenceDeciderIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium))))

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: ["partial-index"] 
     but: item 0: was "index"

  at __randomizedtesting.SeedInfo.seed([469675C6E5031553:37C2DB27E3E84B70]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.autoscaling.existence.FrozenExistenceDeciderIT.lambda$testZeroToOne$2(FrozenExistenceDeciderIT.java:140)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1237)
  at org.elasticsearch.xpack.autoscaling.existence.FrozenExistenceDeciderIT.testZeroToOne(FrozenExistenceDeciderIT.java:138)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by DaveCTurner** [comment]
I'm going to call this `low-risk` because it seems to happen so rarely, and apparently resolved itself just after the test timed out. It looks like something was blocking the index from completing its migration to the frozen tier, but I cannot see what that might be:

```
[2023-11-21T07:15:40,635][INFO ][o.e.c.s.MasterService    ] [node_t0] node-join[{node_t3}{PgtUSVJrQ5yukbRCMNR7jw}{yqEWqa1tR4eJCVvgNZm-zw}{node_t3}{127.0.0.1}{127.0.0.1:18974}{f}{8.12.0}{7000099-8500003} joining], term: 1, version: 35, delta: added {{node_t3}{PgtUSVJrQ5yukbRCMNR7jw}{yqEWqa1tR4eJCVvgNZm-zw}{node_t3}{127.0.0.1}{127.0.0.1:18974}{f}{8.12.0}{7000099-8500003}}
[2023-11-21T07:15:40,649][INFO ][o.e.c.s.ClusterApplierService] [node_t2] added {{node_t3}{PgtUSVJrQ5yukbRCMNR7jw}{yqEWqa1tR4eJCVvgNZm-zw}{node_t3}{127.0.0.1}{127.0.0.1:18974}{f}{8.12.0}{7000099-8500003}}, term: 1, version: 35, reason: ApplyCommitRequest{term=1, version=35, sourceNode={node_t0}{3SrFXv6aTD2tdAoPigvcXQ}{U84mm7BkRHG-GQeljHftxA}{node_t0}{127.0.0.1}{127.0.0.1:18971}{m}{8.12.0}{7000099-8500003}{xpack.installed=true}}
[2023-11-21T07:15:40,649][INFO ][o.e.c.s.ClusterApplierService] [node_t1] added {{node_t3}{PgtUSVJrQ5yukbRCMNR7jw}{yqEWqa1tR4eJCVvgNZm-zw}{node_t3}{127.0.0.1}{127.0.0.1:18974}{f}{8.12.0}{7000099-8500003}}, term: 1, version: 35, reason: ApplyCommitRequest{term=1, version=35, sourceNode={node_t0}{3SrFXv6aTD2tdAoPigvcXQ}{U84mm7BkRHG-GQeljHftxA}{node_t0}{127.0.0.1}{127.0.0.1:18971}{m}{8.12.0}{7000099-8500003}{xpack.installed=true}}
[2023-11-21T07:15:40,664][INFO ][o.e.c.s.ClusterApplierService] [node_t3] master node changed {previous [], current [{node_t0}{3SrFXv6aTD2tdAoPigvcXQ}{U84mm7BkRHG-GQeljHftxA}{node_t0}{127.0.0.1}{127.0.0.1:18971}{m}{8.12.0}{7000099-8500003}]}, added {{node_t2}{RPhigRGfSd6iE7gJq369Vg}{NqS4GnhCQ_2V_pjwKAqp5w}{node_t2}{127.0.0.1}{127.0.0.1:18973}{s}{8.12.0}{7000099-8500003}, {node_t0}{3SrFXv6aTD2tdAoPigvcXQ}{U84mm7BkRHG-GQeljHftxA}{node_t0}{127.0.0.1}{127.0.0.1:18971}{m}{8.12.0}{7000099-8500003}, {node_t1}{9olUtm1HT6anbYnjcZocVg}{mC4fLI-ETTag3lzTaPwvSA}{node_t1}{127.0.0.1}{127.0.0.1:18972}{s}{8.12.0}{7000099-8500003}}, term: 1, version: 35, reason: ApplyCommitRequest{term=1, version=35, sourceNode={node_t0}{3SrFXv6aTD2tdAoPigvcXQ}{U84mm7BkRHG-GQeljHftxA}{node_t0}{127.0.0.1}{127.0.0.1:18971}{m}{8.12.0}{7000099-8500003}{xpack.installed=true}}
[2023-11-21T07:15:40,717][WARN ][o.e.d.c.s.Settings       ] [node_t3] data_stream.dataset="deprecation.elasticsearch" data_stream.namespace="default" data_stream.type="logs" elasticsearch.event.category="settings" event.code="index.data_path" message="[index.data_path] setting was deprecated in Elasticsearch and will be removed in a future release."
[2023-11-21T07:15:40,717][WARN ][o.e.d.c.s.Settings       ] [node_t3] data_stream.dataset="deprecation.elasticsearch" data_stream.namespace="default" data_stream.type="logs" elasticsearch.event.category="settings" event.code="index.data_path" message="[index.data_path] setting was deprecated in Elasticsearch and will be removed in a future release."
[2023-11-21T07:15:40,750][INFO ][o.e.l.ClusterStateLicenseService] [node_t3] license [99d237c6-56f2-4b01-9189-e20b42f6aab3] mode [trial] - valid
[2023-11-21T07:15:40,751][INFO ][o.e.n.Node               ] [[test_TEST-TEST_WORKER_VM=[188]-CLUSTER_SEED=[8982097451220102346]-HASH=[712C746687]-cluster[T#4]]] started {node_t3}{PgtUSVJrQ5yukbRCMNR7jw}{yqEWqa1tR4eJCVvgNZm-zw}{node_t3}{127.0.0.1}{127.0.0.1:18974}{f}{8.12.0}{7000099-8500003}{xpack.installed=true}
[2023-11-21T07:15:40,753][INFO ][o.e.c.s.ClusterApplierService] [node_t0] added {{node_t3}{PgtUSVJrQ5yukbRCMNR7jw}{yqEWqa1tR4eJCVvgNZm-zw}{node_t3}{127.0.0.1}{127.0.0.1:18974}{f}{8.12.0}{7000099-8500003}}, term: 1, version: 35, reason: Publication{term=1, version=35}
[2023-11-21T07:15:40,778][INFO ][o.e.c.c.NodeJoinExecutor ] [node_t0] node-join: [{node_t3}{PgtUSVJrQ5yukbRCMNR7jw}{yqEWqa1tR4eJCVvgNZm-zw}{node_t3}{127.0.0.1}{127.0.0.1:18974}{f}{8.12.0}{7000099-8500003}] with reason [joining]
[2023-11-21T07:15:40,781][INFO ][o.e.x.i.IndexLifecycleTransition] [node_t0] moving index [index] from [{"phase":"frozen","action":"searchable_snapshot","name":"wait-for-data-tier"}] to [{"phase":"frozen","action":"searchable_snapshot","name":"mount-snapshot"}] in policy [policy]
[2023-11-21T07:15:41,140][INFO ][o.e.x.i.IndexLifecycleTransition] [node_t0] moving index [index] from [{"phase":"frozen","action":"searchable_snapshot","name":"mount-snapshot"}] to [{"phase":"frozen","action":"searchable_snapshot","name":"wait-for-index-color"}] in policy [policy]
[2023-11-21T07:15:41,231][INFO ][o.e.c.r.a.AllocationService] [node_t0] current.health="GREEN" message="Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[partial-index][0]]])." previous.health="YELLOW" reason="shards started [[partial-index][0]]"
[2023-11-21T07:16:46,458][INFO ][o.e.s.SnapshotsService   ] [node_t0] deleting snapshots [old-version-snapshot-*] from repository [UupsQVXqKx]
[2023-11-21T07:16:46,462][INFO ][o.e.a.a.c.r.c.TransportCleanupRepositoryAction] [node_t0] Running cleanup operations on repository [UupsQVXqKx][1]
[2023-11-21T07:16:46,488][INFO ][o.e.x.i.IndexLifecycleTransition] [node_t0] moving index [index] from [{"phase":"frozen","action":"searchable_snapshot","name":"wait-for-index-color"}] to [{"phase":"frozen","action":"searchable_snapshot","name":"copy-execution-state"}] in policy [policy]
[2023-11-21T07:16:46,491][INFO ][o.e.x.i.IndexLifecycleTransition] [node_t0] moving index [index] from [{"phase":"frozen","action":"searchable_snapshot","name":"copy-execution-state"}] to [{"phase":"frozen","action":"searchable_snapshot","name":"copy-settings"}] in policy [policy]
[2023-11-21T07:16:46,495][INFO ][o.e.x.i.IndexLifecycleTransition] [node_t0] moving index [index] from [{"phase":"frozen","action":"searchable_snapshot","name":"copy-settings"}] to [{"phase":"frozen","action":"searchable_snapshot","name":"branch-on-datastream-check"}] in policy [policy]
[2023-11-21T07:16:46,496][INFO ][o.e.x.i.IndexLifecycleTransition] [node_t0] moving index [index] from [{"phase":"frozen","action":"searchable_snapshot","name":"branch-on-datastream-check"}] to [{"phase":"frozen","action":"searchable_snapshot","name":"swap-aliases"}] in policy [policy]
[2023-11-21T07:16:46,554][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_t0] [index/2PKlIMwvQx2tgpQDbi-zFQ] deleting index
```

I think this needs someone with more ILM expertise to investigate so I'm relabelling this.

**Comment by kkrik-es** [comment]
Seems like it's still an issue: https://gradle-enterprise.elastic.co/s/u2vx3o2hpmssm

**Comment by andreidan** [comment]
Ah I think I know what's going on here 
```
2024-02-22T06:33:01,388][INFO ][o.e.x.i.IndexLifecycleTransition] [node_t0] moving index [index] from [{"phase":"frozen","action":"searchable_snapshot","name":"mount-snapshot"}] to [{"phase":"froz
en","action":"searchable_snapshot","name":"wait-for-index-color"}] in policy [policy]
[2024-02-22T06:33:01,490][INFO ][o.e.c.r.a.AllocationService] [node_t0] current.health="GREEN" message="Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[partial-ind
ex][0]]])." previous.health="YELLOW" reason="shards started [[partial-index][0]]"
[2024-02-22T06:34:31,308][INFO ][o.e.s.SnapshotsService   ] [node_t0] deleting snapshots [old-version-snapshot-*] from repository [RChoZEgFoK]
[2024-02-22T06:34:31,312][INFO ][o.e.a.a.c.r.c.TransportCleanupRepositoryAction] [node_t0] Running cleanup operations on repository [RChoZEgFoK][1]
[2024-02-22T06:34:31,348][INFO ][o.e.x.i.IndexLifecycleTransition] [node_t0] moving index [index] from [{"phase":"frozen","action":"searchable_snapshot","name":"wait-for-index-color"}] to [{"phase"
:"frozen","action":"searchable_snapshot","name":"copy-execution-state"}] in policy [policy]
[2024-02-22T06:34:31,352][INFO ][o.e.x.i.IndexLifecycleTransition] [node_t0] moving index [index] from [{"phase":"frozen","action":"searchable_snapshot","name":"copy-execution-state"}] to [{"phase"
:"frozen","action":"searchable_snapshot","name":"copy-settings"}] in policy [policy]
[2024-02-22T06:34:31,354][INFO ][o.e.x.i.IndexLifecycleTransition] [node_t0] moving index [index] from [{"phase":"frozen","action":"searchable_snapshot","name":"copy-settings"}] to [{"phase":"froze
n","action":"searchable_snapshot","name":"branch-on-datastream-check"}] in policy [policy]
```

ILM transitions to `wait-for-index-color` (a step that needs a cluster state changed event to evaluate against) but misses the cluster state event that notifies that `partial-index` is now `GREEN`. 
And then the cluster is quiet and no more state changes occur and we timeout. Note that the test is unblocked by the teardown of the IT that triggers some cluster state changes.
