### ISSUE TITLE
[CI] RcsCcsCommonYamlTestSuiteIT test {p0=eql/10_basic/Execute EQL sequence with string key.} failing

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#102423]
**Build scan:**
https://gradle-enterprise.elastic.co/s/ckwu2xvpt7h4e/tests/:qa:ccs-common-rest:yamlRestTest/org.elasticsearch.test.rest.yaml.RcsCcsCommonYamlTestSuiteIT/test%20%7Bp0=eql%2F10_basic%2FExecute%20EQL%20sequence%20with%20string%20key.%7D

**Reproduction line:**
```
./gradlew ':qa:ccs-common-rest:yamlRestTest' --tests "org.elasticsearch.test.rest.yaml.RcsCcsCommonYamlTestSuiteIT" -Dtests.method="test {p0=eql/10_basic/Execute EQL sequence with string key.}" -Dtests.seed=612CCCF15406C135 -Dtests.locale=ar-KW -Dtests.timezone=US/Indiana-Starke -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test%20%7Bp0%3Deql/10_basic/Execute%20EQL%20sequence%20with%20string%20key.%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.test.rest.yaml.RcsCcsCommonYamlTestSuiteIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium))))

**Failure excerpt:**
```
java.lang.AssertionError: Failure at [eql/10_basic:173]: expected [2xx] status code but api [eql.search] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"verification_exception","reason":"verification_exception: Found 2 problems\nline 1:19: Unknown column [event.category]\nline 1:33: Unknown column [user]","stack_trace":"org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: verification_exception: Found 2 problems\nline 1:19: Unknown column [event.category]\nline 1:33: Unknown column [user]\n\tat org.elasticsearch.xpack.eql.analysis.Analyzer.verify(Analyzer.java:66)\n\tat org.elasticsearch.xpack.eql.analysis.Analyzer.analyze(Analyzer.java:60)\n\tat org.elasticsearch.xpack.eql.session.EqlSession.lambda$analyzedPlan$1(EqlSession.java:115)\n\tat org.elasticsearch.xpack.ql.util.ActionListeners.lambda$map$0(ActionListeners.java:24)\n\tat org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)\n\tat org.elasticsearch.xpack.ql.util.ActionListeners.lambda$map$0(ActionListeners.java:24)\n\tat org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)\n\tat org.elasticsearch.xpack.ql.index.IndexResolver.lambda$resolveAsMergedMapping$5(IndexResolver.java:330)\n\tat org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)\n\tat org.elasticsearch.action.ActionListener$4.onResponse(ActionListener.java:331)\n\tat org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:203)\n\tat org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:197)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)\n\tat org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)\n\tat org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:305)\n\tat org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.mergeIndexResponses(TransportFieldCapabilitiesAction.java:256)\n\tat org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.lambda$doExecuteForked$5(TransportFieldCapabilitiesAction.java:189)\n\tat org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:117)\n\tat org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:69)\n\tat org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:116)\n\tat org.elasticsearch.core.Releasables$3.close(Releasables.java:142)\n\tat org.elasticsearch.common.util.concurrent.RunOnce.run(RunOnce.java:40)\n\tat org.elasticsearch.action.fieldcaps.RequestDispatcher.innerExecute(RequestDispatcher.java:153)\n\tat org.elasticsearch.action.fieldcaps.RequestDispatcher$1.doRun(RequestDispatcher.java:122)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.lang.Thread.run(Thread.java:1583)\n"}],"type":"verification_exception","reason":"verification_exception: Found 2 problems\nline 1:19: Unknown column [event.category]\nline 1:33: Unknown column [user]","stack_trace":"org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: verification_exception: Found 2 problems\nline 1:19: Unknown column [event.category]\nline 1:33: Unknown column [user]\n\tat org.elasticsearch.xpack.eql.analysis.Analyzer.verify(Analyzer.java:66)\n\tat org.elasticsearch.xpack.eql.analysis.Analyzer.analyze(Analyzer.java:60)\n\tat org.elasticsearch.xpack.eql.session.EqlSession.lambda$analyzedPlan$1(EqlSession.java:115)\n\tat org.elasticsearch.xpack.ql.util.ActionListeners.lambda$map$0(ActionListeners.java:24)\n\tat org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)\n\tat org.elasticsearch.xpack.ql.util.ActionListeners.lambda$map$0(ActionListeners.java:24)\n\tat org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)\n\tat org.elasticsearch.xpack.ql.index.IndexResolver.lambda$resolveAsMergedMapping$5(IndexResolver.java:330)\n\tat org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)\n\tat org.elasticsearch.action.ActionListener$4.onResponse(ActionListener.java:331)\n\tat org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:203)\n\tat org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:197)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)\n\tat org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)\n\tat org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:305)\n\tat org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.mergeIndexResponses(TransportFieldCapabilitiesAction.java:256)\n\tat org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.lambda$doExecuteForked$5(TransportFieldCapabilitiesAction.java:189)\n\tat org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:117)\n\tat org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:69)\n\tat org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:116)\n\tat org.elasticsearch.core.Releasables$3.close(Releasables.java:142)\n\tat org.elasticsearch.common.util.concurrent.RunOnce.run(RunOnce.java:40)\n\tat org.elasticsearch.action.fieldcaps.RequestDispatcher.innerExecute(RequestDispatcher.java:153)\n\tat org.elasticsearch.action.fieldcaps.RequestDispatcher$1.doRun(RequestDispatcher.java:122)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.lang.Thread.run(Thread.java:1583)\n"},"status":400}]

  at __randomizedtesting.SeedInfo.seed([612CCCF15406C135:E978F32BFAFAACCD]:0)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:572)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:524)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:47)
  at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:47)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

  Caused by: java.lang.AssertionError: expected [2xx] status code but api [eql.search] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"verification_exception","reason":"verification_exception: Found 2 problems\nline 1:19: Unknown column [event.category]\nline 1:33: Unknown column [user]","stack_trace":"org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: verification_exception: Found 2 problems\nline 1:19: Unknown column [event.category]\nline 1:33: Unknown column [user]\n\tat org.elasticsearch.xpack.eql.analysis.Analyzer.verify(Analyzer.java:66)\n\tat org.elasticsearch.xpack.eql.analysis.Analyzer.analyze(Analyzer.java:60)\n\tat org.elasticsearch.xpack.eql.session.EqlSession.lambda$analyzedPlan$1(EqlSession.java:115)\n\tat org.elasticsearch.xpack.ql.util.ActionListeners.lambda$map$0(ActionListeners.java:24)\n\tat org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)\n\tat org.elasticsearch.xpack.ql.util.ActionListeners.lambda$map$0(ActionListeners.java:24)\n\tat org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)\n\tat org.elasticsearch.xpack.ql.index.IndexResolver.lambda$resolveAsMergedMapping$5(IndexResolver.java:330)\n\tat org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)\n\tat org.elasticsearch.action.ActionListener$4.onResponse(ActionListener.java:331)\n\tat org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:203)\n\tat org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:197)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)\n\tat org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)\n\tat org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:305)\n\tat org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.mergeIndexResponses(TransportFieldCapabilitiesAction.java:256)\n\tat org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.lambda$doExecuteForked$5(TransportFieldCapabilitiesAction.java:189)\n\tat org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:117)\n\tat org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:69)\n\tat org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:116)\n\tat org.elasticsearch.core.Releasables$3.close(Releasables.java:142)\n\tat org.elasticsearch.common.util.concurrent.RunOnce.run(RunOnce.java:40)\n\tat org.elasticsearch.action.fieldcaps.RequestDispatcher.innerExecute(RequestDispatcher.java:153)\n\tat org.elasticsearch.action.fieldcaps.RequestDispatcher$1.doRun(RequestDispatcher.java:122)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.lang.Thread.run(Thread.java:1583)\n"}],"type":"verification_exception","reason":"verification_exception: Found 2 problems\nline 1:19: Unknown column [event.category]\nline 1:33: Unknown column [user]","stack_trace":"org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: verification_exception: Found 2 problems\nline 1:19: Unknown column [event.category]\nline 1:33: Unknown column [user]\n\tat org.elasticsearch.xpack.eql.analysis.Analyzer.verify(Analyzer.java:66)\n\tat org.elasticsearch.xpack.eql.analysis.Analyzer.analyze(Analyzer.java:60)\n\tat org.elasticsearch.xpack.eql.session.EqlSession.lambda$analyzedPlan$1(EqlSession.java:115)\n\tat org.elasticsearch.xpack.ql.util.ActionListeners.lambda$map$0(ActionListeners.java:24)\n\tat org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)\n\tat org.elasticsearch.xpack.ql.util.ActionListeners.lambda$map$0(ActionListeners.java:24)\n\tat org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)\n\tat org.elasticsearch.xpack.ql.index.IndexResolver.lambda$resolveAsMergedMapping$5(IndexResolver.java:330)\n\tat org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)\n\tat org.elasticsearch.action.ActionListener$4.onResponse(ActionListener.java:331)\n\tat org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:203)\n\tat org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:197)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)\n\tat org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)\n\tat org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:305)\n\tat org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.mergeIndexResponses(TransportFieldCapabilitiesAction.java:256)\n\tat org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.lambda$doExecuteForked$5(TransportFieldCapabilitiesAction.java:189)\n\tat org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:117)\n\tat org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:69)\n\tat org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:116)\n\tat org.elasticsearch.core.Releasables$3.close(Releasables.java:142)\n\tat org.elasticsearch.common.util.concurrent.RunOnce.run(RunOnce.java:40)\n\tat org.elasticsearch.action.fieldcaps.RequestDispatcher.innerExecute(RequestDispatcher.java:153)\n\tat org.elasticsearch.action.fieldcaps.RequestDispatcher$1.doRun(RequestDispatcher.java:122)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.lang.Thread.run(Thread.java:1583)\n"},"status":400}]

    at org.junit.Assert.fail(Assert.java:88)
    at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:374)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:552)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:524)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:47)
    at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:47)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1583)

```

**Comment by luigidellaquila** [comment]
It doesn't seem to reproduce locally and it failed only once. 
The failure looks like a resolution problem (`Unknown column [event.category]`)

Labeling as low risk for now, as it doesn't seem to be critical. If it fails again we'll raise the severity

**Comment by alex-spies** [comment]
Hm, this keeps failing like once a month.
