### ISSUE TITLE
[CI] DanglingIndicesRestIT testDanglingIndicesCanBeDeleted failing

### ISSUE THREAD

**Issue by n1v0lg** [elastic/elasticsearch#102593]
We had a similar failure in unrelated test suites here:

https://github.com/elastic/elasticsearch/issues/99023

I'm opening this as a new issue since it gives a nice failure summary. Please close as duplicate if you prefer to re-open the linked issue instead.

**Build scan:**
https://gradle-enterprise.elastic.co/s/mbywwsjtfq2fk/tests/:qa:smoke-test-http:javaRestTest/org.elasticsearch.http.DanglingIndicesRestIT/testDanglingIndicesCanBeDeleted

**Reproduction line:**
```
./gradlew ':qa:smoke-test-http:javaRestTest' --tests "org.elasticsearch.http.DanglingIndicesRestIT.testDanglingIndicesCanBeDeleted" -Dtests.seed=9F2C14415499FB79 -Dtests.locale=ms-MY -Dtests.timezone=America/Indiana/Marengo -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testDanglingIndicesCanBeDeleted'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.http.DanglingIndicesRestIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium))))

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=1048, name=elasticsearch[node_t2][clusterApplierService#updateTask][T#1], state=RUNNABLE, group=TGRP-DanglingIndicesRestIT]

  at __randomizedtesting.SeedInfo.seed([9F2C14415499FB79:33922743AFCE9B8C]:0)

  Caused by: java.lang.AssertionError: (No message provided)

    at __randomizedtesting.SeedInfo.seed([9F2C14415499FB79]:0)
    at org.elasticsearch.discovery.PeerFinder.closePeers(PeerFinder.java:183)
    at org.elasticsearch.cluster.coordination.Coordinator.onClusterStateApplied(Coordinator.java:420)
    at org.elasticsearch.cluster.coordination.Coordinator.lambda$handleApplyCommit$8(Coordinator.java:408)
    at org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.lambda$map$0(ActionListenerImplementations.java:108)
    at org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:89)
    at org.elasticsearch.cluster.service.ClusterApplierService$ClusterApplyActionListener.onResponse(ClusterApplierService.java:598)
    at org.elasticsearch.cluster.service.ClusterApplierService$ClusterApplyActionListener.onResponse(ClusterApplierService.java:569)
    at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:439)
    at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:916)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:217)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:183)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.lang.Thread.run(Thread.java:1583)

```

**Comment by DaveCTurner** [comment]
> Applicable branches:
> main

Are you sure @n1v0lg? The linked build scan was from 8.11, which would suggest we just need to backport #100986.

**Comment by n1v0lg** [comment]
@DaveCTurner Ah sorry, you're absolutely right. I could have sworn it was `main` but checking again this is indeed 8.11. I can open a backport. Sorry for the noise.

**Comment by n1v0lg** [comment]
Backport open here: https://github.com/elastic/elasticsearch/pull/102603

Closing!

**Comment by jfreden** [comment]
Looks like this is happening again: https://gradle-enterprise.elastic.co/s/yobj3o43eogj4

**Comment by DaveCTurner** [comment]
Although it's the same test failing, it's a different exception, and this was a failure that actually only happened on the 8.11 branch. Would you open a fresh issue so that it has up-to-date information @jfreden?
