### ISSUE TITLE
CI] SearchWithMinCompatibleSearchNodeIT testMinVersionAsOldVersion failing

### ISSUE THREAD

**Issue by afoucret** [elastic/elasticsearch#102575]
### Tests:
Three tests are failing with the same error:

- [testMinVersionAsOldVersion](https://gradle-enterprise.elastic.co/s/foomrrnt7s2ta/tests/task/:qa:mixed-cluster:v8.11.2%23mixedClusterTest/details/org.elasticsearch.backwards.SearchWithMinCompatibleSearchNodeIT/testMinVersionAsOldVersion)
- [testCcsMinimizeRoundtripsIsFalse](https://gradle-enterprise.elastic.co/s/foomrrnt7s2ta/tests/task/:qa:mixed-cluster:v8.11.2%23mixedClusterTest/details/org.elasticsearch.backwards.SearchWithMinCompatibleSearchNodeIT/testCcsMinimizeRoundtripsIsFalse)
- [testMinVersionAsNewVersion](https://gradle-enterprise.elastic.co/s/foomrrnt7s2ta/tests/task/:qa:mixed-cluster:v8.11.2%23mixedClusterTest/details/org.elasticsearch.backwards.SearchWithMinCompatibleSearchNodeIT/testMinVersionAsNewVersion)

### CI Link

https://gradle-enterprise.elastic.co/s/foomrrnt7s2ta

### Repro line

```
./gradlew ':qa:mixed-cluster:v8.11.2#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.SearchWithMinCompatibleSearchNodeIT" -Dtests.method="testMinVersionAsOldVersion" -Dtests.seed=5D68FEC6666DFBBE -Dtests.bwc=true -Dtests.locale=en-AU -Dtests.timezone=America/Belize -Druntime.java=21
```

### Does it reproduce?

No

### Applicable branches

main

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe%2FParis&tests.container=org.elasticsearch.backwards.SearchWithMinCompatibleSearchNodeIT&tests.test=testMinVersionAsOldVersion

### Failure excerpt

```
java.lang.AssertionError: timed out waiting for green state for index [test_min_version] cluster state [{ |  
```

**Comment by afoucret** [comment]
I found some other failures for this test recently so it is likely that is is a flakiness.

<img width="1262" alt="Capture d’écran 2023-11-24 à 10 46 05" src="https://github.com/elastic/elasticsearch/assets/529238/a657091e-db5f-46d0-86be-e62187db3bf5">

**Comment by ldematte** [comment]
Another failure in the 7.17 branch: https://gradle-enterprise.elastic.co/s/5st4xtvfascbk/tests/task/:qa:mixed-cluster:v7.1.0%23mixedClusterTest/details/org.elasticsearch.backwards.SearchWithMinCompatibleSearchNodeIT/testMinVersionAsNewVersion?top-execution=1

**Comment by benwtrent** [comment]
OK, that 7.17 failure is something very different:

> java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

Interesting...

**Comment by benwtrent** [comment]
Ah, two nodes crashed?
[mixed-cluster.zip](https://github.com/elastic/elasticsearch/files/14722009/mixed-cluster.zip)

```
[2024-03-21T20:42:49,041][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v7.1.0-3] fatal error in thread [elasticsearch[v7.1.0-3][clusterApplierService#updateTask][T#1]], exiting
java.lang.AssertionError: {_doc=org.elasticsearch.index.mapper.DocumentMapper@79314ebf}
	at org.elasticsearch.index.mapper.MapperService.assertMappingVersion(MapperService.java:264) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.index.mapper.MapperService.updateMapping(MapperService.java:218) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.index.IndexService.updateMapping(IndexService.java:551) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.updateIndices(IndicesClusterStateService.java:533) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:266) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$5(ClusterApplierService.java:478) ~[elasticsearch-7.1.0.jar:7.1.0]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:476) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:459) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:413) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:164) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) ~[elasticsearch-7.1.0.jar:7.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
```
```
[2024-03-21T20:44:57,353][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v7.1.0-2] fatal error in thread [elasticsearch[v7.1.0-2][clusterApplierService#updateTask][T#1]], exiting
java.lang.AssertionError: {_doc=org.elasticsearch.index.mapper.DocumentMapper@2fbe67de}
	at org.elasticsearch.index.mapper.MapperService.assertMappingVersion(MapperService.java:264) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.index.mapper.MapperService.updateMapping(MapperService.java:218) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.index.IndexService.updateMapping(IndexService.java:551) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.updateIndices(IndicesClusterStateService.java:533) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:266) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$5(ClusterApplierService.java:478) ~[elasticsearch-7.1.0.jar:7.1.0]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:476) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:459) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:413) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:164) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) ~[elasticsearch-7.1.0.jar:7.1.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) ~[elasticsearch-7.1.0.jar:7.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
```

**Comment by benwtrent** [comment]
OK, here is where the assertion is tripped:

https://github.com/elastic/elasticsearch/blob/3ce7d2c9b621e796ace43008134413cea7648a06/server/src/main/java/org/elasticsearch/index/mapper/MapperService.java#L259-L264

Apparently the `{_doc=org.elasticsearch.index.mapper.DocumentMapper@2fbe67de}` for this node or the other is an update but the mapping version value isn't incremented?

**Comment by benwtrent** [comment]
Well, I can see https://github.com/elastic/elasticsearch/commit/921462a94f375cca57b48ae4f2df1650cc10ca4f

Removed this assertion check starting in 7.12, but I honestly don't understand why. I would have thought that we would still want to check that the mapping version gets updated when there are changes?

Then later we completely refactored the version checking here: https://github.com/elastic/elasticsearch/commit/3d963a3174d8a6e6e5145c7e4b025707745736cd

This was in 7.13.

I am guessing we accidentally removed assertions and then changed how we check for the differences and this then introduced some subtle bug?

@javanna Do you have any ideas? I know this was a while ago :/

**Comment by benwtrent** [comment]
Ah, so this test failure is likely due to a "representative change" of the object and not necessary a "equality change": https://github.com/elastic/elasticsearch/issues/59427

This tells me this assertion trip on old nodes is...useless? I honestly don't know.

This keeps getting weirder @javanna :)

**Comment by benwtrent** [comment]
I see this really old test failure: https://github.com/elastic/elasticsearch/issues/86887

Its roots are the same as this new failure, running into a mapping assertion failure as the representation is different, but apparently we don't increment the version values if the xcontent is now the same?
