### ISSUE TITLE
elasticsearch 1.5 initialize error

### ISSUE THREAD

**Issue by zhufeizzz** [elastic/elasticsearch#10257]
I have already install the lastest sheild from https://download.elasticsearch.org/elasticsearch/shield/shield-1.1.0.zip

```
[2015-03-25 17:04:54,234][INFO ][node                     ] [Wind Dancer] version[1.5.0], pid[50884], build[5448160/2015-03-23T14:30:58Z]
[2015-03-25 17:04:54,234][INFO ][node                     ] [Wind Dancer] initializing ...
[2015-03-25 17:04:54,288][INFO ][plugins                  ] [Wind Dancer] loaded [shield, license], sites []
[2015-03-25 17:04:54,827][INFO ][transport                ] [Wind Dancer] Using [org.elasticsearch.shield.transport.ShieldServerTransportService] as transport service, overridden by [shield]
[2015-03-25 17:04:54,827][INFO ][transport                ] [Wind Dancer] Using [org.elasticsearch.shield.transport.netty.ShieldNettyTransport] as transport, overridden by [shield]
[2015-03-25 17:04:54,827][INFO ][http                     ] [Wind Dancer] Using [org.elasticsearch.shield.transport.netty.ShieldNettyHttpServerTransport] as http transport, overridden by [shield]
[2015-03-25 17:04:57,781][INFO ][node                     ] [Wind Dancer] initialized
[2015-03-25 17:04:57,782][INFO ][node                     ] [Wind Dancer] starting ...
[2015-03-25 17:04:59,043][INFO ][shield.transport         ] [Wind Dancer] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/11.12.205.204:9300]}
[2015-03-25 17:04:59,066][INFO ][discovery                ] [Wind Dancer] elasticsearch/glJ3SVj_RDqKTzD301RTgw
[2015-03-25 17:04:59,090][WARN ][discovery.zen.ping.unicast] [Wind Dancer] [1] failed send ping to [Wind Dancer][glJ3SVj_RDqKTzD301RTgw][linux][inet[/11.12.205.204:9300]]
java.lang.NoSuchMethodError: org.elasticsearch.transport.netty.MessageChannelHandler.<init>(Lorg/elasticsearch/transport/netty/NettyTransport;Lorg/elasticsearch/common/logging/ESLogger;)V
	at org.elasticsearch.shield.transport.netty.ShieldMessageChannelHandler.<init>(ShieldMessageChannelHandler.java:43)
	at org.elasticsearch.shield.transport.netty.ShieldNettyTransport$SslClientChannelPipelineFactory.getPipeline(ShieldNettyTransport.java:122)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:206)
	at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:778)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:731)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:704)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:216)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$3.run(UnicastZenPing.java:376)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by javanna** [comment]
Hi @zhufeizzz shield 1.1 works against 1.4.x, while shield 1.2 has same features but works against 1.5. I'm afraid you installed the wrong version. Once you move to shield 1.2 everything should be fine.

**Comment by javanna** [comment]
One more thing, if you point the plugin script to `elasticsearch/shield/latest` that already downloads the correct version depending on your elasticsearch version. Not sure, but seems like it went wrong for you because you have pointed to `elasticsearch/shield/1.1.0` directly?

**Comment by uboness** [comment]
indeed `elasticsearch/shield/latest` should work... but we seem to have an issue there at the moment... checking it out

**Comment by uboness** [comment]
oops.. my bad... seems to work after all... in any case.. see http://www.elastic.co/guide/en/shield/current/quick-getting-started.html

**Comment by zhufeizzz** [comment]
@javanna I download shield manual from this url https://download.elasticsearch.org/elasticsearch/shield/shield-latest.zip

The server return back shield-1.1.0.zip to me, can you try this url?

**Comment by javanna** [comment]
@zhufeizzz correct if you download manually `latest` points to `1.1`, we only have a 50% chance to give you the correct version. We are discussing how we could improve this for manual downloads. For now the behaviour you see is expected, you should download directly the 1.2.0 version [here](https://download.elasticsearch.org/elasticsearch/shield/shield-1.2.0.zip) .
