### ISSUE TITLE
FileNotFoundException during :plugins:repository-hdfs:forbiddenApisJavaRestTest

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#102712]
Build scan: https://gradle-enterprise.elastic.co/s/u6j4allgydguu

Interesting part in the console log:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':plugins:repository-hdfs:forbiddenApisJavaRestTest'.
...
Caused by: org.gradle.internal.deprecation.DocumentedFailure$DocumentedExceptionWithCause: Cannot access input property 'classpath' of task ':plugins:repository-hdfs:forbiddenApisJavaRestTest'. Accessing unreadable inputs or outputs is not supported. Declare the task as untracked by using Task.doNotTrackState(). For more information, please refer to https://docs.gradle.org/8.4/userguide/incremental_build.html#disable-state-tracking in the Gradle documentation.
...
Caused by: java.io.UncheckedIOException: Failed to create MD5 hash for file '/opt/local-ssd/buildkite/builds/bk-agent-prod-gcp-1701176508246589041/elastic/elasticsearch-periodic-platform-support/test/fixtures/krb5kdc-fixture/testfixtures_shared/shared/hdfs/keytabs/elasticsearch.keytab' as it does not exist.
...
Caused by: java.io.FileNotFoundException: /opt/local-ssd/buildkite/builds/bk-agent-prod-gcp-1701176508246589041/elastic/elasticsearch-periodic-platform-support/test/fixtures/krb5kdc-fixture/testfixtures_shared/shared/hdfs/keytabs/elasticsearch.keytab (Permission denied)	
	at java.base/java.io.FileInputStream.open0(Native Method)	
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)	
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)	
	at org.gradle.internal.hash.DefaultFileHasher.hash(DefaultFileHasher.java:36)
```

**Comment by mark-vieira** [comment]
The "permission denied" bit seems relevant. This sounds like the docker container is writing these files as some user (probably root) which then aren't readable by the CI user running Gradle. Not sure if we've changed anything here. I think we made some changes to forbidden apis though. @breskeby anything come to mind? Are we running forbidden apis in parallel with other tasks in the same project now? Perhaps some ordering issue? I'm wondering why we haven't seen this before. I assume if these files are added to the test runtime classpath, we'd expect to see a similar error for the test task as well.
