### ISSUE TITLE
[CI] APMIndexTemplateRegistryTests testIngestPipelines failing

### ISSUE THREAD

**Issue by ChrisHegarty** [elastic/elasticsearch#102797]
**Build scan:**
https://gradle-enterprise.elastic.co/s/nfw7pgg7qvpya/tests/:x-pack:plugin:apm-data:test/org.elasticsearch.xpack.apmdata.APMIndexTemplateRegistryTests/testIngestPipelines

**Reproduction line:**
```
./gradlew ':x-pack:plugin:apm-data:test' --tests "org.elasticsearch.xpack.apmdata.APMIndexTemplateRegistryTests.testIngestPipelines" -Dtests.seed=F47F91E5606932A -Dtests.locale=id-ID -Dtests.timezone=Australia/Lindeman -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testIngestPipelines'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.apmdata.APMIndexTemplateRegistryTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium))))

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: a value equal to or greater than <1>
     but: <0> was less than <1>

  at __randomizedtesting.SeedInfo.seed([F47F91E5606932A:9E4A21F257218DD]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.apmdata.APMIndexTemplateRegistryTests.lambda$testIngestPipelines$5(APMIndexTemplateRegistryTests.java:158)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1213)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1186)
  at org.elasticsearch.xpack.apmdata.APMIndexTemplateRegistryTests.lambda$testIngestPipelines$6(APMIndexTemplateRegistryTests.java:158)
  at java.util.ArrayList.forEach(ArrayList.java:1596)
  at org.elasticsearch.xpack.apmdata.APMIndexTemplateRegistryTests.testIngestPipelines(APMIndexTemplateRegistryTests.java:145)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by ChrisHegarty** [comment]
Same failure seen in this PR - https://github.com/elastic/elasticsearch/pull/102782. ( https://buildkite.com/elastic/elasticsearch-pull-request/builds/2651#018c1d16-1242-4845-98be-dd74f686c723)

**Comment by gmarouli** [comment]
My investigation shows that this is a timing issue in the test and not the code, for this reason I change it into ``low-risk. 

I wasn't able to reproduce it locally without any code manipulation, but adding a sleep of 5ms managed to produce the same logging:

```
[2023-11-05T23:34:36,435][INFO ][....] adding ingest pipeline apm@default-pipeline 
[2023-11-05T23:34:36,442][INFO ][....] adding ingest pipeline apm@default-pipeline
[2023-11-05T23:34:36,442][INFO ][....] adding ingest pipeline apm@pipeline
```
What we see here is described here:
- The test loops over every pipeline configuration, namely `apm@default-pipeline`, `apm@pipeline`, `traces-apm@pipeline`, `metrics-apm@pipeline`,  it triggers a cluster change and waits to observe the `PutPipelineRequest` for the respective pipeline, these requests are a sync. After waiting only for the request it is interested the test will trigger the next change. However, it shares the `APMIndexTemplateRegistry` which means it's possible, to run two cluster changes in parallel, and only one can create a pipeline.

For example, both `apm@default-pipeline` and `apm@pipeline` do not have dependencies so they can both be created on the first round. I am going to add some comments around the logging above to explain what I believe is happening:

```
# First cluster change is triggered and it will try to insert as many pipelines as possible. 
# Namely `apm@default-pipeline` # and `apm@pipeline` because they have no dependencies
[First round] adding ingest pipeline apm@default-pipeline 
# The code sees that the pipeline was added so it kick starts the second cluster change
[Second round] adding ingest pipeline apm@default-pipeline
# The first cluster change continues on adding the second pipeline and holds the creation 
# flag blocking other threads from creating it.
[First round] adding ingest pipeline apm@pipeline
# Second round fails to create the `apm@pipeline` because the creation flag was held by the first round.
```

**Comment by ywangd** [comment]
@gmarouli This failed on 8.12 as well https://gradle-enterprise.elastic.co/s/ho2w3iknobbfe/tests/task/:x-pack:plugin:apm-data:test/details/org.elasticsearch.xpack.apmdata.APMIndexTemplateRegistryTests/testIngestPipelines?top-execution=1

Might want to consider backporting the fix?

**Comment by kkrik-es** [comment]
Another failure in 8.12: https://gradle-enterprise.elastic.co/s/4u2zibrfxkvcw

Reopening to get the fix backported.

**Comment by gmarouli** [comment]
oh apologies @ywangd & @kkrik-es I completely missed this, it's too late to backport it now.
