### ISSUE TITLE
CI: BigArraysTests.testLongArrayFill raises ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#10278]
see http://build-us-00.elastic.co/job/es_g1gc_master_metal/4810/testReport/junit/org.elasticsearch.common.util/BigArraysTests/testLongArrayFill/

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at org.elasticsearch.common.util.BigLongArray.fill(BigLongArray.java:106)
	at org.elasticsearch.test.cache.recycler.MockBigArrays$LongArrayWrapper.fill(MockBigArrays.java:435)
	at org.elasticsearch.common.util.BigArraysTests.testLongArrayFill(BigArraysTests.java:229)
```

The seed reproduces:

```
mvn clean test -Dtests.seed=7E0265B0C4E00A96 -Dtests.class=org.elasticsearch.common.util.BigArraysTests -Dtests.method="testLongArrayFill" -Des.logger.level=DEBUG -Des.node.mode=network -Dtests.security.manager=false -Dtests.nightly=false -Dtests.heap.size=1024m -Dtests.jvm.argline="-server -XX:+UseG1GC -XX:+UseCompressedOops -XX:+AggressiveOpts" -Dtests.locale=ms_MY -Dtests.timezone=America/Cuiaba -Dtests.processors=8
```

**Comment by rjernst** [comment]
The fill function did not account for an empty range of [from,to).  This only "mattered" when `from == to == 0`.

I've pushed a fix.
master: 5b0512f
1.x: aa1d0f2
1.5: a008fc1
