### ISSUE TITLE
[CI] SearchCancellationIT testCancellationDuringFetchPhase failing

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#102856]
failing since 29th Nov

https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe%2FWarsaw&tests.container=org.elasticsearch.search.SearchCancellationIT&tests.test=testCancellationDuringFetchPhase

**Build scan:**
https://gradle-enterprise.elastic.co/s/qzyq6ot5cxlu2/tests/:server:internalClusterTest/org.elasticsearch.search.SearchCancellationIT/testCancellationDuringFetchPhase

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.search.SearchCancellationIT.testCancellationDuringFetchPhase" -Dtests.seed=ED7C5C625698D31 -Dtests.locale=et-EE -Dtests.timezone=Etc/GMT-12 -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testCancellationDuringFetchPhase'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.search.SearchCancellationIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium))))

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: an empty collection
     but: <[LEAK: resource was not cleaned up before it was garbage-collected.
Recent access records: 
#1:
	org.elasticsearch.action.search.TransportMultiSearchAction$1.finish(TransportMultiSearchAction.java:196)
	org.elasticsearch.action.search.TransportMultiSearchAction$1.handleResponse(TransportMultiSearchAction.java:175)
	org.elasticsearch.action.search.TransportMultiSearchAction$1.onResponse(TransportMultiSearchAction.java:160)
	org.elasticsearch.action.search.TransportMultiSearchAction$1.onResponse(TransportMultiSearchAction.java:157)
	org.elasticsearch.action.ActionListener$4.onResponse(ActionListener.java:331)
	org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:202)
	org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:196)
	org.elasticsearch.action.search.TransportSearchAction.lambda$doExecute$4(TransportSearchAction.java:301)
	org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)
	org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:260)
	org.elasticsearch.action.ActionListener$4.onResponse(ActionListener.java:331)
	org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:703)
	org.elasticsearch.action.search.FetchLookupFieldsPhase.run(FetchLookupFieldsPhase.java:75)
	org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:451)
	org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:445)
	org.elasticsearch.action.search.ExpandSearchPhase.onPhaseDone(ExpandSearchPhase.java:151)
	org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:105)
	org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:451)
	org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:445)
	org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:238)
	org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$2(FetchSearchPhase.java:125)
	org.elasticsearch.action.search.CountedCollector.countDown(CountedCollector.java:42)
	org.elasticsearch.action.search.CountedCollector.onFailure(CountedCollector.java:64)
	org.elasticsearch.action.search.FetchSearchPhase$2.onFailure(FetchSearchPhase.java:194)
	org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:54)
	org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:553)
	org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1718)
	org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1435)
	org.elasticsearch.transport.InboundHandler.doHandleException(InboundHandler.java:475)
	org.elasticsearch.transport.InboundHandler.handleException(InboundHandler.java:462)
	org.elasticsearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:453)
	org.elasticsearch.transport.InboundHandler.executeResponseHandler(InboundHandler.java:145)
	org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:122)
	org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:96)
	org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:825)
	org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:124)
	org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:96)
	org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:61)
	org.elasticsearch.transport.netty4.Netty4MessageInboundHandler.channelRead(Netty4MessageInboundHandler.java:48)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	java.base/java.lang.Thread.run(Thread.java:1583)
#2:
	org.elasticsearch.core.RefCounted.mustIncRef(RefCounted.java:71)
	org.elasticsearch.client.internal.support.AbstractClient$RefCountedFuture.onResponse(AbstractClient.java:1613)
	org.elasticsearch.client.internal.support.AbstractClient$RefCountedFuture.onResponse(AbstractClient.java:1609)
	org.elasticsearch.action.ActionListener$4.onResponse(ActionListener.java:331)
	org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:202)
	org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:196)
	org.elasticsearch.action.search.TransportMultiSearchAction$1.finish(TransportMultiSearchAction.java:194)
	org.elasticsearch.action.search.TransportMultiSearchAction$1.handleResponse(TransportMultiSearchAction.java:175)
	org.elasticsearch.action.search.TransportMultiSearchAction$1.onResponse(TransportMultiSearchAction.java:160)
	org.elasticsearch.action.search.TransportMultiSearchAction$1.onResponse(TransportMultiSearchAction.java:157)
	org.elasticsearch.action.ActionListener$4.onResponse(ActionListener.java:331)
	org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:202)
	org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:196)
	org.elasticsearch.action.search.TransportSearchAction.lambda$doExecute$4(TransportSearchAction.java:301)
	org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)
	org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:260)
	org.elasticsearch.action.ActionListener$4.onResponse(ActionListener.java:331)
	org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:703)
	org.elasticsearch.action.search.FetchLookupFieldsPhase.run(FetchLookupFieldsPhase.java:75)
	org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:451)
	org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:445)
	org.elasticsearch.action.search.ExpandSearchPhase.onPhaseDone(ExpandSearchPhase.java:151)
	org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:105)
	org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:451)
	org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:445)
	org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:238)
	org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$2(FetchSearchPhase.java:125)
	org.elasticsearch.action.search.CountedCollector.countDown(CountedCollector.java:42)
	org.elasticsearch.action.search.CountedCollector.onFailure(CountedCollector.java:64)
	org.elasticsearch.action.search.FetchSearchPhase$2.onFailure(FetchSearchPhase.java:194)
	org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:54)
	org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:553)
	org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1718)
	org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1435)
	org.elasticsearch.transport.InboundHandler.doHandleException(InboundHandler.java:475)
	org.elasticsearch.transport.InboundHandler.handleException(InboundHandler.java:462)
	org.elasticsearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:453)
	org.elasticsearch.transport.InboundHandler.executeResponseHandler(InboundHandler.java:145)
	org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:122)
	org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:96)
	org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:825)
	org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:124)
	org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:96)
	org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:61)
	org.elasticsearch.transport.netty4.Netty4MessageInboundHandler.channelRead(Netty4MessageInboundHandler.java:48)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	java.base/java.lang.Thread.run(Thread.java:1583)
Created at:
	org.elasticsearch.action.search.MultiSearchResponse.<init>(MultiSearchResponse.java:140)
	org.elasticsearch.action.search.TransportMultiSearchAction$1.finish(TransportMultiSearchAction.java:191)
	org.elasticsearch.action.search.TransportMultiSearchAction$1.handleResponse(TransportMultiSearchAction.java:175)
	org.elasticsearch.action.search.TransportMultiSearchAction$1.onResponse(TransportMultiSearchAction.java:160)
	org.elasticsearch.action.search.TransportMultiSearchAction$1.onResponse(TransportMultiSearchAction.java:157)
	org.elasticsearch.action.ActionListener$4.onResponse(ActionListener.java:331)
	org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:202)
	org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:196)
	org.elasticsearch.action.search.TransportSearchAction.lambda$doExecute$4(TransportSearchAction.java:301)
	org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)
	org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:260)
	org.elasticsearch.action.ActionListener$4.onResponse(ActionListener.java:331)
	org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:703)
	org.elasticsearch.action.search.FetchLookupFieldsPhase.run(FetchLookupFieldsPhase.java:75)
	org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:451)
	org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:445)
	org.elasticsearch.action.search.ExpandSearchPhase.onPhaseDone(ExpandSearchPhase.java:151)
	org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:105)
	org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:451)
	org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:445)
	org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:238)
	org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$2(FetchSearchPhase.java:125)
	org.elasticsearch.action.search.CountedCollector.countDown(CountedCollector.java:42)
	org.elasticsearch.action.search.CountedCollector.onFailure(CountedCollector.java:64)
	org.elasticsearch.action.search.FetchSearchPhase$2.onFailure(FetchSearchPhase.java:194)
	org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:54)
	org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:553)
	org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1718)
	org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1435)
	org.elasticsearch.transport.InboundHandler.doHandleException(InboundHandler.java:475)
	org.elasticsearch.transport.InboundHandler.handleException(InboundHandler.java:462)
	org.elasticsearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:453)
	org.elasticsearch.transport.InboundHandler.executeResponseHandler(InboundHandler.java:145)
	org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:122)
	org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:96)
	org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:825)
	org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:124)
	org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:96)
	org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:61)
	org.elasticsearch.transport.netty4.Netty4MessageInboundHandler.channelRead(Netty4MessageInboundHandler.java:48)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	java.base/java.lang.Thread.run(Thread.java:1583)]>

  at __randomizedtesting.SeedInfo.seed([ED7C5C625698D31:67335C2F1CF91D80]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:726)
  at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:517)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by pgomulka** [comment]
closing in favour of https://github.com/elastic/elasticsearch/issues/102257
