### ISSUE TITLE
ES|QL: better type handling in STATS

### ISSUE THREAD

**Issue by luigidellaquila** [elastic/elasticsearch#102961]
Some types are not properly handled as inputs for aggregate functions. Validation passes, but then the planning throws an exception.
It would be much better to have a proper ValidationException with a user friendly error message.

Eg. `count_distinct()` does not validate UNSIGNED_LONG and VERSION properly (but `count()` does); `max()/min()...` functions do not validate UNSIGNED_LONG properly, but validate (yet do not support) VERSION; 

```
row x = to_unsigned_long(10) | stats  a = count_distinct(x)
```

```
{
    "error": {
        "root_cause": [
            {
                "type": "esql_illegal_argument_exception",
                "reason": "illegal data type [unsigned_long]"
            }
        ],
        "type": "esql_illegal_argument_exception",
        "reason": "illegal data type [unsigned_long]"
    },
    "status": 500
}
```

```
org.elasticsearch.xpack.esql.EsqlIllegalArgumentException: illegal agg type: unsigned_long
        at org.elasticsearch.xpack.esql.planner.AggregateMapper.dataTypeToString(AggregateMapper.java:231)
        at org.elasticsearch.xpack.esql.planner.AggregateMapper.aggDefOrNull(AggregateMapper.java:155)
        at org.elasticsearch.xpack.esql.planner.AggregateMapper.computeEntryForAgg(AggregateMapper.java:111)
        at org.elasticsearch.xpack.esql.planner.AggregateMapper.lambda$map$3(AggregateMapper.java:107)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
        at org.elasticsearch.xpack.esql.planner.AggregateMapper.map(AggregateMapper.java:107)
        at org.elasticsearch.xpack.esql.planner.AggregateMapper.lambda$doMapping$1(AggregateMapper.java:97)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.elasticsearch.xpack.esql.planner.AggregateMapper.doMapping(AggregateMapper.java:97)
        at org.elasticsearch.xpack.esql.planner.AggregateMapper.mapNonGrouping(AggregateMapper.java:84)
        at org.elasticsearch.xpack.esql.planner.AbstractPhysicalOperationProviders.groupingPhysicalOperation(AbstractPhysicalOperationProviders.java:66)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planAggregation(LocalExecutionPlanner.java:232
```

**Comment by costin** [comment]
Good catch - please update the Verifier to do the same validation after resolution.
