### ISSUE TITLE
[CI] SearchUsageStatsTests.testEqualsAndHashcode failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#102920]
### CI Link

https://gradle-enterprise.elastic.co/s/xooooat6hfrcc

### Repro line

`./gradlew ':server:test' --tests "org.elasticsearch.action.admin.cluster.stats.SearchUsageStatsTests.testEqualsAndHashcode" -Dtests.seed=4ACCFB0EC25D3085 -Dtests.locale=es-CO -Dtests.timezone=Asia/Aqtobe -Druntime.java=21`

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

```
  2> java.lang.AssertionError: SearchUsageStats mutation should not be equal to original
    Expected: not <{
      "search" : {
        "total" : 4274853694888555554,
        "queries" : {
          "function_score" : 1132154870774338162,
          "match" : 9093327110996320607,
          "range" : 3108377874468427272
        },
        "rescorers" : {
          "query" : 2428939235303283814,
          "learn_to_rank" : 129724287171024361
        },
        "sections" : { }
      }
    }>
         but: was <{
      "search" : {
        "total" : 4274853694888555554,
        "queries" : {
          "function_score" : 1132154870774338162,
          "match" : 9093327110996320607,
          "range" : 3108377874468427272
        },
        "rescorers" : {
          "query" : 2428939235303283814,
          "learn_to_rank" : 129724287171024361
        },
        "sections" : { }
      }
    }>
        at __randomizedtesting.SeedInfo.seed([4ACCFB0EC25D3085:3BC383C30DBA79AA]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.test.EqualsHashCodeTestUtils.checkEqualsAndHashCode(EqualsHashCodeTestUtils.java:95)
        at org.elasticsearch.test.AbstractWireTestCase.testEqualsAndHashcode(AbstractWireTestCase.java:60)
```

**Comment by carlosdelest** [comment]
@afoucret , this might be related to your recent changes in #102771 . Can you please take a look?
