### ISSUE TITLE
CI: GeoDistanceTests.testDistanceSortingNestedFields runs into NPE on fetch phase

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#10296]
http://build-us-00.elastic.co/job/es_core_15_centos/168/testReport/junit/org.elasticsearch.search.geo/GeoDistanceTests/testDistanceSortingNestedFields/

Doesn't look like a geo related issue:

```
java.lang.AssertionError: Expected different hit count.  Total shards: 9 Successful shards: 8 & 1 shard failures:
 shard [[UJboLng4Sbmce5B3_MvRnQ][companies][0]], reason [RemoteTransportException[[node_s1][local[274]][indices:data/read/search[phase/fetch/id]]]; nested: NullPointerException; ]
Expected: <4>
     but: was <3>
	at __randomizedtesting.SeedInfo.seed([2294217C90EA15A7:F1CD59C9510B38EC]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
```

**Comment by martijnvg** [comment]
This is the actual error:

```
org.elasticsearch.transport.RemoteTransportException: [node_s1][local[274]][indices:data/read/search[phase/fetch/id]]
  1> Caused by: java.lang.NullPointerException
  1> 	at org.elasticsearch.common.bytes.BytesReference$Helper.hashCode(BytesReference.java:71)
  1> 	at org.elasticsearch.common.bytes.BytesReference$Helper.bytesHashCode(BytesReference.java:61)
  1> 	at org.elasticsearch.common.bytes.BytesArray.hashCode(BytesArray.java:171)
  1> 	at org.elasticsearch.common.text.StringAndBytesText.hashCode(StringAndBytesText.java:94)
  1> 	at com.carrotsearch.hppc.Internals.rehash(Internals.java:10)
  1> 	at com.carrotsearch.hppc.ObjectIntOpenHashMap.containsKey(ObjectIntOpenHashMap.java:714)
  1> 	at org.elasticsearch.common.io.stream.HandlesStreamOutput.writeSharedText(HandlesStreamOutput.java:60)
  1> 	at org.elasticsearch.search.internal.InternalSearchHit.writeTo(InternalSearchHit.java:709)
  1> 	at org.elasticsearch.search.internal.InternalSearchHits.writeTo(InternalSearchHits.java:259)
  1> 	at org.elasticsearch.search.fetch.FetchSearchResult.writeTo(FetchSearchResult.java:104)
  1> 	at org.elasticsearch.transport.local.LocalTransportChannel.sendResponse(LocalTransportChannel.java:74)
  1> 	at org.elasticsearch.transport.local.LocalTransportChannel.sendResponse(LocalTransportChannel.java:62)
  1> 	at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:869)
  1> 	at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:862)
  1> 	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:279)
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  1> 	at java.lang.Thread.run(Thread.java:745)
```

I'm not sure yet why the type of a hit is null.

**Comment by clintongormley** [comment]
@martijnvg can this be closed?

**Comment by martijnvg** [comment]
This can be closed. I can't find the fix, but it stopped failing a long time ago (20th April).
