### ISSUE TITLE
some indices recovery are delayed when one left node rejoin the cluster

### ISSUE THREAD

**Issue by SoldierProgrammer** [elastic/elasticsearch#102957]
### Elasticsearch Version

7.10.2

### Java Version

_bundled_

### OS Version

centos 7

### Problem Description

**Base infomation:**
An elasticsearch cluster with 3 master nodes and 10 data nodes, with total 1000+ indices,  and 700+ shards in every data node.
the config index.unassigned.node_left.delayed_timeout is 1 hour.

when an exception occurs(maybe the network problem or others), one of the data nodes left the cluster for a while(about 1 minute),
the cluster status is changed from green to yellow.
when the node rejoined the cluster, the shards in this left node begin to recover, wait a moment, and the most of the left shards recovered, only two shards cannot recover automatically.

when I use GET _cluster/allocation/explain to get the response:
"can_allocate" : "allocation_delayed",
"allocate_explanation" : "cannot allocate because the cluster is still waiting 45m for the departed node holding a replica to rejoin, despite being allowed to allocate the shard to at least one other node",

And I try to GET /_cluster/pending_tasks, its response:
{
  "tasks" : [ ]
}

why cannot all of the shards automatically revocer, it always left one or two shards waiting to 1 hour to recover ??
This problem has occurred many times.

**solution**
I set index.unassigned.node_left.delayed_timeout to 1 minute and wait the two shards to recover and then change the config item to 1 hour again.

### Steps to Reproduce

when an exception occurs(maybe the network problem or others), one of the data nodes left the cluster for a while(about 1 minute),
the cluster status is changed from green to yellow.
when the node rejoined the cluster, the shards in this left node begin to recover, wait a moment, and the most of the left shards recovered, only two shards cannot recover automatically.

### Logs (if relevant)

[2023-12-05T15:08:45,958][INFO ][o.e.i.s.TransportNodesListShardStoreMetadata] [node-10..10.111.111] [.kibana_task_manager_2][0]: failed to obtain shard lock
org.elasticsearch.env.ShardLockObtainFailedException: [.kibana_task_manager_2][0]: obtaining shard lock for [read metadata snapshot] timed out after [5000ms], lock already held for [closing shard] with age [8112ms]
        at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:781) ~[elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:687) ~[elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.index.store.Store.readMetadataSnapshot(Store.java:451) [elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.indices.store.TransportNodesListShardStoreMetadata.listStoreMetadata(TransportNodesListShardStoreMetadata.java:173) [elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.indices.store.TransportNodesListShardStoreMetadata.nodeOperation(TransportNodesListShardStoreMetadata.java:117) [elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.indices.store.TransportNodesListShardStoreMetadata.nodeOperation(TransportNodesListShardStoreMetadata.java:67) [elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:158) [elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:271) [elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:267) [elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:257) [x-pack-security-7.10.2.jar:7.10.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:224) [elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.lambda$messageReceived$0(SecurityServerTransportInterceptor.java:306) [x-pack-security-7.10.2.jar:7.10.2]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeSystemUser(AuthorizationService.java:401) [x-pack-security-7.10.2.jar:7.10.2]
        at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:205) [x-pack-security-7.10.2.jar:7.10.2]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$inbound$1(ServerTransportFilter.java:129) [x-pack-security-7.10.2.jar:7.10.2]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$2(AuthenticationService.java:323) [x-pack-security-7.10.2.jar:7.10.2]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$6(AuthenticationService.java:384) [x-pack-security-7.10.2.jar:7.10.2]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:395) [x-pack-security-7.10.2.jar:7.10.2]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:320) [x-pack-security-7.10.2.jar:7.10.2]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:261) [x-pack-security-7.10.2.jar:7.10.2]
        at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:173) [x-pack-security-7.10.2.jar:7.10.2]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.inbound(ServerTransportFilter.java:120) [x-pack-security-7.10.2.jar:7.10.2]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:313) [x-pack-security-7.10.2.jar:7.10.2]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:72) [elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:305) [elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:743) [elasticsearch-7.10.2.jar:7.10.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.10.2.jar:7.10.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?

**Comment by DaveCTurner** [comment]
Thank you very much for your interest in Elasticsearch. Unfortunately the issue you have reported relates to Elasticsearch version 7.10.2 which is very old and has passed [end-of-life](https://www.elastic.co/support/eol). We will not investigate issues related to unsupported versions here on Github, so I am closing this to indicate that no action is needed from the Elasticsearch development team. It's possible that you will find a volunteer to help you with this issue on the [community forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6), but our strong recommendation would be to upgrade to a supported version of Elasticsearch as a matter of some urgency. If you can reproduce your issue on a supported version then please open a fresh bug report.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.
