### ISSUE TITLE
[CI] LearningToRankRescorerIT testLearningToRankRescore failing

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#103072]
Also other test failures in this class

**Build scan:**
https://gradle-enterprise.elastic.co/s/mlap7th5eqptk/tests/:x-pack:plugin:ml:qa:single-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.LearningToRankRescorerIT/testLearningToRankRescore

**Reproduction line:**
```
./gradlew ':x-pack:plugin:ml:qa:single-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.LearningToRankRescorerIT.testLearningToRankRescore" -Dtests.seed=25C2A98F7336871A -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=ar-TN -Dtests.timezone=Asia/Dili -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.ml.integration.LearningToRankRescorerIT#testLearningToRankRescore`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testLearningToRankRescore'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.ml.integration.LearningToRankRescorerIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [PUT], host [http://[::1]:37501], URI [_ml/trained_models/ltr-model], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"named_object_not_found_exception","reason":"[5:5] unknown field [learning_to_rank]"}],"type":"x_content_parse_exception","reason":"[5:5] [trained_model_config] failed to parse field [inference_config]","caused_by":{"type":"x_content_parse_exception","reason":"[5:5] [inference_config] failed to parse field [learning_to_rank]","caused_by":{"type":"named_object_not_found_exception","reason":"[5:5] unknown field [learning_to_rank]"}}},"status":400}

  at __randomizedtesting.SeedInfo.seed([25C2A98F7336871A:3D8A9AB5FEF50407]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:351)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:317)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:292)
  at org.elasticsearch.xpack.ml.integration.InferenceTestCase.putRegressionModel(InferenceTestCase.java:106)
  at org.elasticsearch.xpack.ml.integration.LearningToRankRescorerIT.setupModelAndData(LearningToRankRescorerIT.java:28)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by idegtiarenko** [comment]
Another failure here: https://gradle-enterprise.elastic.co/s/roreoehk3hyp4/tests/task/:x-pack:plugin:ml:qa:single-node-tests:javaRestTest/details/org.elasticsearch.xpack.ml.integration.LearningToRankRescorerIT/testLearningToRankRescore?top-execution=1

**Comment by maxhniebergall** [comment]
more test failures:
[LearningToRankRescorerIT » testLearningToRankRescorerWithChainedRescorers](https://gradle-enterprise.elastic.co/s/vzkaxgqj2555q/tests/:x-pack:plugin:ml:qa:single-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.LearningToRankRescorerIT/testLearningToRankRescorerWithChainedRescorers)
[LearningToRankRescorerIT » testLearningToRankRescoreSmallWindow](https://gradle-enterprise.elastic.co/s/vzkaxgqj2555q/tests/:x-pack:plugin:ml:qa:single-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.LearningToRankRescorerIT/testLearningToRankRescoreSmallWindow)
[LearningToRankRescorerIT » testLearningToRankRescore](https://gradle-enterprise.elastic.co/s/vzkaxgqj2555q/tests/:x-pack:plugin:ml:qa:single-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.LearningToRankRescorerIT/testLearningToRankRescore)

**Comment by ywangd** [comment]
Still fails for 8.12 release-tests
https://gradle-enterprise.elastic.co/s/slfkrqrwwdhfs

I am going to backport the mute to 8.12

**Comment by ywangd** [comment]
Backport PR #103367

**Comment by maxhniebergall** [comment]
@afoucret are you able to assess the risk for this issue?
