### ISSUE TITLE
[CI] ToDoubleTests testFold {TestCase=<long unicode KEYWORD>} failing

### ISSUE THREAD

**Issue by kkrik-es** [elastic/elasticsearch#103132]
**Build scan:**
https://gradle-enterprise.elastic.co/s/vwm3dbg6amas6/tests/:x-pack:plugin:esql:test/org.elasticsearch.xpack.esql.expression.function.scalar.convert.ToDoubleTests/testFold%20%7BTestCase=%3Clong%20unicode%20KEYWORD%3E%7D

**Reproduction line:**
```
./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.expression.function.scalar.convert.ToDoubleTests.testFold {TestCase=<long unicode KEYWORD>}" -Dtests.seed=640B56F851F950C5 -Dtests.locale=ro -Dtests.timezone=America/Argentina/Catamarca -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.esql.expression.function.scalar.convert.ToDoubleTests#testFold {TestCase=<long unicode KEYWORD>}`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testFold%20%7BTestCase%3D%3Clong%20unicode%20KEYWORD%3E%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.expression.function.scalar.convert.ToDoubleTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: a collection containing <WARN: Line -1:-1: java.lang.NumberFormatException: For input string: \"%1F%11%25%07%0Dw7N%0CA$(Q[%13AD;^c[z%19?Ck%16;%06I%13ur\"%16%0FdK:+77^w/f1;E$%1AOKA%14%04?%0A%020~jQt?8%15%0EjqRw@+\\gY/%1D(K.t%1D{%0C+ 1>JGB(%0EOQ%0C%15%08x4;~Evr%0A@?\\%04#0:	%13Y%01tw8O$B({Yrlj,%17QU%18?+%04lE9%02Dvm%7FW%196;%14b%0B'X]#YHc%124'm%0CMHSS$JD^^h*!%17%1A8%05%0C0'%1C*{1iS%19e%08%05M;%11#,%1BCJmbknG	Vp%17&%25%12;%0Fq,#%10uPGUVVTx\"#N/[%10%0C5B%0EkDb\"%1A`U]a*6i-%005Q%02ic#X?%01gtv%0BC%15%1F\"%0COE%1C%18%1C{%0F%1AbL%1Dy:%1D%10%01^9%14Xj%0CX%1Af/-%00GIfo\"5Z1aCj#a%16_i%08&;K]Hz{pA%07G	C_gZ8p%1A%1D%0D+%0E;9%1CiInFB%106kZ%15%13\"8y;%0DU{%13%1D%1D-YcX4,ue%13z!%18%18T:0\\/+%7Fev	Ty%16|?R%10B!%14G%17%168%1C%0A%06{h}%00l%1Bp^#q39%1Eg2%0C%173lA:QBuGg%10wjOT%03%0BD%06%08$%1E)r%0F`9X`%14QJL:pR)IF %1C+`n@l5%04>%00y-%1Dsd.lu80%25M(6Zw*9d}H\"~%1Cic%13%1E+%12{%06%100buAac%13%0Cw0%19O%0F	%0Dt%14U|$%07ZQt^H%11%11%153rZ[%16X5spy%0B%12E%7F1%17}#]Q%08%00nT%0B%08\"%18;%1D^%17s</%02%0F%10h,'EsV`-X][?S%02%11u,e!wIg%16OWVc%7F0/qK%25F0%13MOhIYY3nK%0BpU@'~Xx%13hNv;1%16?Lms%0AQV%0E05Wj{%15Rt%18a%00X^%07i%078^M{z%007 u%1D>+%03	$woUL%13GO	%00t?G%13F`-p2%05v0/ycJ-~9%05%04eleWo4p$l%1Eo%1Bh$%25<%00h=v%129y %01G%05%1AS%027%19i7+,IA <``Jbrt%08%109|{:n%14#rELx%04zO3%0Bx%055%0C%19%03%08%057\"D%0Ef%00e?]%1E%19=0%07%0B]09D~pKt%16u%06k>X}9%13C%1DbI&\\125,8}%02F[UDV%12|%13%10%1BdWpSKnq%1D%13R`%14Hpe5VX)T%12N`-D%049:`%03?p%0C 3&%1C{yY l%18%19M%17N/M?%124%0F%11%0A%1E%08CG%0D%06ex%19n#ZJ%13N!Id-tg%12B$Vq]-%159%14y5^,Z\\y]\\4k3x?|%0B!OP\\&%1A%05_P%04AH(t.6%14%13	\"(4Cp&%100wFF`%13!%15;,R	%15%0C%01LF%0F0i%16%15c%0D%0E]u%18%12fptu%1B%03=%00U%02%1E%08Qh%17 %00Jt%10g4R{*Qk%02#%07hSrx<?%19$6Iy%0C%18h}_,Sx[7%1Awv'!lf%0DlW1zZg>zAN\\qJR%0A%0B6%1F%16%1E9%16%0Cp%7F%0B%1B%1BkAvoB8Q)M~x<%05EpI~%0C8%103$u.Wa%0Fo;LhS%1D%1A%11e%1CU|'!%1D%02ET%25cn63%10wl%7Fz%1EBlKxF%25%0AA9Hf#ZR+,f7c0)B&%06%01F%0Cz/%07WLIZ%14#%15%0EI4U%14g3%7F%7Fxge}%0Dyw-%04%1C;%0C?%25EQu%03WU#2^_S%0D%12te%0Bp5J%0B0%0E`c%12iU%06f)Z%1CU7ufL5sQ%01[)Ul%1B:%05)LI7UXI%0A$IwNu5%1Dz5u%18r8%03%02~.%19oUdYj#%02};%01&%13T4%0AQ0)hl)ver%1B;C%05%0E&K%07/%06%15.%0E69!Sq2%0CF@%0DBP`e|EF%19)&1QQ0tlcnFW%0B)ju=\\I%16%0E%0F%11glMf%02H~\"zaSsmt,%13%12%06w\\d%03%00i1/5dkv%12%01T2%10%0E%08-Yr1%11*w={D%02\"H!j%16p%0B0)x4)%1E&0XAI'oXV%13$8%10(S*9RP%19K_NB%0Fm?k?Qt}/%0Bz%03q%1E7%07{%1Fe%00%251%04Hk1)k%18|:t<Yip%1Dd|U:c[b%07A%02?%14X%0DwR}%18%15'%1F,R!%1F{%18d^c;bwkC=|<<%11U%11k7D8%16%00L'%10^Q%10+p%1Cwgll0)%00p%1E,N%1Fl-FXD9QrB,%0D#eu6%17Vu%0F6Ho%10a%18k}Cf(#%17%06%0C,O%1Av%0CfF%1C;%11FO^%00E4=P`X%1AxiN`'s&&D`p%19'%0A%1FvXix^7r)~8%0Ck%1B>nC.~af7%0A;%18D%07'@%05Wccd%1BZ%0B%02p%0Ek-b%13ZDM=x8,^t%04L%1En[b%17?UR;(%1E%0ANsT&E%04%18%0A(OO+%1C%12%183%13xSn8%118+=\\4ij%05%1A%7F]A.b+2%1F%07%0D6jtP%0F m U%1A%1F~M9d%0BXa#gze|k%03]u[!~%02?)Q`0%147{Y%05u^5EO7%19|0%04K%1FO^ \\:%0B0[Ny?%12\"%17<jG%03%0B)^_%12%16%0A%1F%1F%0F%11%05%0B%11F%0F%154RF!,dB%0C%19 W7%14&9q%1D%0F%19%10.>%18~yS7}_	FUhiDFG3v^%0C%01%07'm%0C2%151\"`CNH&%19D%0D'qY%03Xb}E:\\L%01;%14=,so%12{MeL6^vBcMnW%14%0Cv%16&,R%19`y%25%0F#WJ3dI%14%1Fop%03o'FC%12;%1EjE*A%01%0C)T%00G%11V%01~6%7F|u%166bWP8wq	%19-P%0F%0E|%1E<1v4YR%1D(%05^%0B2%03%25g#/G%1E}%01%13Y;y%134}M%1DO%1A#+u6%055r/%0BMRDt\\A%0CR)%13%1D(hVXT&]..na%03%7F&zBB%7FvFECN%00T,%1A]8t2C%0D-}%05mY'%1B$M_\\kC%18y%17rig%0BI%1EQ3XjaWG&~%1F%003\"zZ%08lJGHLqLx,j8%019ApU^%0A%16Jx2J>kKYF3Q.%0E%17DqmeS%00%1E8r1D%00)%08nD3%07Z'=7%06Gn%126%03W%14,%1Aue4%0Ad`%18_t%17%1D00'pI<%11%12%1B%02%131P`[>k0GGBd	%1040%172J,@N90.F%17v%11%19Vm%122@c%25/%17%04e%00%12\\1%1C%06W%11a%14caa%07%16%12/|%10/xr%11$t%1E%18#%0D%1CG|%18%194|D%0F I%17hr/+{p9gVI%1B[f	C%05OC)%0A9s %0BZs.fBQ[yB%14C%0BP}Qorg(g%1A\"k n+4caH9y%0Cx(JEpOe1%10c%17e-ztP@VL%0DMo\"%01%10r|nC%0B{%08\"xMWtt%14x\\o\"IkEs%163wV1!( C?F%08bN54%1A%12_%08sF%16)zFz>FEb%0E=&s%01(:%1E^QAIc%10twB|7%1FN%0F%1A4sU#zv.t)%05?fp%17%1AO%14=%02%11%1D]%03s%06:%05R1~Q%02%02V&Q%1Fz%17%0Eot)0%1BSM$Lkf`1m%0F!>[%18%10lQ%25*G}#%1E%04I-oL%0FR%0D;G'%0F7Ty&%03%19%1Ek*@5%11N%08%0D%11W0}UilM(H/aj%12BCR%1C%1EZ:O%0Ee]~aa,#_d<c%00%02%02MDgivM%0Ay%1D%15~\\%08J1S%0EJed%00%06C<%25lx%1E\\t%05%1C$P+5&J*M4/<:u%1C*xX%00%13	%05{_aR'ip$%0AL%10%116f-jZ&%11_i%122RLn%08`LuR%17?%25%0DxSW(M9%1E@#%11i %0BX4mf8Z\"^dEHZ%0FA%0A<%103#ID;yNJ%17S%14%06%03yW/oP%0FTyg[>wm%1CY%05%03a2Nr(B%10&a\">
     but: mismatches were: [was <CRITICAL: Line -1:-1: evaluation of [] failed, treating result as null. Only first 20 failures recorded.>, was <CRITICAL: Line -1:-1: java.lang.NumberFormatException: For input string: \"%25%07%0Dw7N%0CA$(Q[%13AD;^c[z%19?Ck%16;%06I%13ur\"%16%0FdK:+77^w/f1;E$%1AOKA%14%04?%0A%020~jQt?8%15%0EjqRw@+\\gY/%1D(K.t%1D{%0C+ 1>JGB(%0EOQ%0C%15%08x4;~Evr%0A@?\\%04#0:	%13Y%01tw8O$B({Yrlj,%17QU%18?+%04lE9%02Dvm%7FW%196;%14b%0B'X]#YHc%124'm%0CMHSS$JD^^h*!%17%1A8%05%0C0'%1C*{1iS%19e%08%05M;%11#,%1BCJmbknG	Vp%17&%25%12;%0Fq,#%10uPGUVVTx\"#N/[%10%0C5B%0EkDb\"%1A`U]a*6i-%005Q%02ic#X?%01gtv%0BC%15%1F\"%0COE%1C%18%1C{%0F%1AbL%1Dy:%1D%10%01^9%14Xj%0CX%1Af/-%00GIfo\"5Z1aCj#a%16_i%08&;K]Hz{pA%07G	C_gZ8p%1A%1D%0D+%0E;9%1CiInFB%106kZ%15%13\"8y;%0DU{%13%1D%1D-YcX4,ue%13z!%18%18T:0\\/+%7Fev	Ty%16|?R%10B!%14G%17%168%1C%0A%06{h}%00l%1Bp^#q39%1Eg2%0C%173lA:QBuGg%10wjOT%03%0BD%06%08$%1E)r%0F`9X`%14QJL:pR)IF %1C+`n@l5%04>%00y-%1Dsd.lu80%25M(6Zw*9d}H\"~%1Cic%13%1E+%12{%06%100buAac%13%0Cw0%19O%0F	%0Dt%14U|$%07ZQt^H%11%11%153rZ[%16X5spy%0B%12E%7F1%17}#]Q%08%00nT%0B%08\"%18;%1D^%17s</%02%0F%10h,'EsV`-X][?S%02%11u,e!wIg%16OWVc%7F0/qK%25F0%13MOhIYY3nK%0BpU@'~Xx%13hNv;1%16?Lms%0AQV%0E05Wj{%15Rt%18a%00X^%07i%078^M{z%007 u%1D>+%03	$woUL%13GO	%00t?G%13F`-p2%05v0/ycJ-~9%05%04eleWo4p$l%1Eo%1Bh$%25<%00h=v%129y %01G%05%1AS%027%19i7+,IA <``Jbrt%08%109|{:n%14#rELx%04zO3%0Bx%055%0C%19%03%08%057\"D%0Ef%00e?]%1E%19=0%07%0B]09D~pKt%16u%06k>X}9%13C%1DbI&\\125,8}%02F[UDV%12|%13%10%1BdWpSKnq%1D%13R`%14Hpe5VX)T%12N`-D%049:`%03?p%0C 3&%1C{yY l%18%19M%17N/M?%124%0F%11%0A%1E%08CG%0D%06ex%19n#ZJ%13N!Id-tg%12B$Vq]-%159%14y5^,Z\\y]\\4k3x?|%0B!OP\\&%1A%05_P%04AH(t.6%14%13	\"(4Cp&%100wFF`%13!%15;,R	%15%0C%01LF%0F0i%16%15c%0D%0E]u%18%12fptu%1B%03=%00U%02%1E%08Qh%17 %00Jt%10g4R{*Qk%02#%07hSrx<?%19$6Iy%0C%18h}_,Sx[7%1Awv'!lf%0DlW1zZg>zAN\\qJR%0A%0B6%1F%16%1E9%16%0Cp%7F%0B%1B%1BkAvoB8Q)M~x<%05EpI~%0C8%103$u.Wa%0Fo;LhS%1D%1A%11e%1CU|'!%1D%02ET%25cn63%10wl%7Fz%1EBlKxF%25%0AA9Hf#ZR+,f7c0)B&%06%01F%0Cz/%07WLIZ%14#%15%0EI4U%14g3%7F%7Fxge}%0Dyw-%04%1C;%0C?%25EQu%03WU#2^_S%0D%12te%0Bp5J%0B0%0E`c%12iU%06f)Z%1CU7ufL5sQ%01[)Ul%1B:%05)LI7UXI%0A$IwNu5%1Dz5u%18r8%03%02~.%19oUdYj#%02};%01&%13T4%0AQ0)hl)ver%1B;C%05%0E&K%07/%06%15.%0E69!Sq2%0CF@%0DBP`e|EF%19)&1QQ0tlcnFW%0B)ju=\\I%16%0E%0F%11glMf%02H~\"zaSsmt,%13%12%06w\\d%03%00i1/5dkv%12%01T2%10%0E%08-Yr1%11*w={D%02\"H!j%16p%0B0)x4)%1E&0XAI'oXV%13$8%10(S*9RP%19K_NB%0Fm?k?Qt}/%0Bz%03q%1E7%07{%1Fe%00%251%04Hk1)k%18|:t<Yip%1Dd|U:c[b%07A%02?%14X%0DwR}%18%15'%1F,R!%1F{%18d^c;bwkC=|<<%11U%11k7D8%16%00L'%10^Q%10+p%1Cwgll0)%00p%1E,N%1Fl-FXD9QrB,%0D#eu6%17Vu%0F6Ho%10a%18k}Cf(#%17%06%0C,O%1Av%0CfF%1C;%11FO^%00E4=P`X%1AxiN`'s&&D`p%19'%0A%1FvXix^7r)~8%0Ck%1B>nC.~af7%0A;%18D%07'@%05Wccd%1BZ%0B%02p%0Ek-b%13ZDM=x8,^t%04L%1En[b%17?UR;(%1E%0ANsT&E%04%18%0A(OO+%1C%12%183%13xSn8%118+=\\4ij%05%1A%7F]A.b+2%1F%07%0D6jtP%0F m U%1A%1F~M9d%0BXa#gze|k%03]u[!~%02?)Q`0%147{Y%05u^5EO7%19|0%04K%1FO^ \\:%0B0[Ny?%12\"%17<jG%03%0B)^_%12%16%0A%1F%1F%0F%11%05%0B%11F%0F%154RF!,dB%0C%19 W7%14&9q%1D%0F%19%10.>%18~yS7}_	FUhiDFG3v^%0C%01%07'm%0C2%151\"`CNH&%19D%0D'qY%03Xb}E:\\L%01;%14=,so%12{MeL6^vBcMnW%14%0Cv%16&,R%19`y%25%0F#WJ3dI%14%1Fop%03o'FC%12;%1EjE*A%01%0C)T%00G%11V%01~6%7F|u%166bWP8wq	%19-P%0F%0E|%1E<1v4YR%1D(%05^%0B2%03%25g#/G%1E}%01%13Y;y%134}M%1DO%1A#+u6%055r/%0BMRDt\\A%0CR)%13%1D(hVXT&]..na%03%7F&zBB%7FvFECN%00T,%1A]8t2C%0D-}%05mY'%1B$M_\\kC%18y%17rig%0BI%1EQ3XjaWG&~%1F%003\"zZ%08lJGHLqLx,j8%019ApU^%0A%16Jx2J>kKYF3Q.%0E%17DqmeS%00%1E8r1D%00)%08nD3%07Z'=7%06Gn%126%03W%14,%1Aue4%0Ad`%18_t%17%1D00'pI<%11%12%1B%02%131P`[>k0GGBd	%1040%172J,@N90.F%17v%11%19Vm%122@c%25/%17%04e%00%12\\1%1C%06W%11a%14caa%07%16%12/|%10/xr%11$t%1E%18#%0D%1CG|%18%194|D%0F I%17hr/+{p9gVI%1B[f	C%05OC)%0A9s %0BZs.fBQ[yB%14C%0BP}Qorg(g%1A\"k n+4caH9y%0Cx(JEpOe1%10c%17e-ztP@VL%0DMo\"%01%10r|nC%0B{%08\"xMWtt%14x\\o\"IkEs%163wV1!( C?F%08bN54%1A%12_%08sF%16)zFz>FEb%0E=&s%01(:%1E^QAIc%10twB|7%1FN%0F%1A4sU#zv.t)%05?fp%17%1AO%14=%02%11%1D]%03s%06:%05R1~Q%02%02V&Q%1Fz%17%0Eot)0%1BSM$Lkf`1m%0F!>[%18%10lQ%25*G}#%1E%04I-oL%0FR%0D;G'%0F7Ty&%03%19%1Ek*@5%11N%08%0D%11W0}UilM(H/aj%12BCR%1C%1EZ:O%0Ee]~aa,#_d<c%00%02%02MDgivM%0Ay%1D%15~\\%08J1S%0EJed%00%06C<%25lx%1E\\t%05%1C$P+5&J*M4/<:u%1C*xX%00%13	%05{_aR'ip$%0AL%10%116f-jZ&%11_i%122RLn%08`LuR%17?%25%0DxSW(M9%1E@#%11i %0BX4mf8Z\"^dEHZ%0FA%0A<%103#ID;yNJ%17S%14%06%03yW/oP%0FTyg[>wm%1CY%05%03a2Nr(B%10&a\">]

  at __randomizedtesting.SeedInfo.seed([640B56F851F950C5:E8779F6C269FA95C]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.test.ESTestCase.assertWarnings(ESTestCase.java:645)
  at org.elasticsearch.test.ESTestCase.assertWarnings(ESTestCase.java:596)
  at org.elasticsearch.xpack.esql.expression.function.AbstractFunctionTestCase.testFold(AbstractFunctionTestCase.java:516)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by bpintea** [comment]
Dup of https://github.com/elastic/elasticsearch/issues/103127
