### ISSUE TITLE
[CI] MlDistributedFailureIT testClusterWithTwoMlNodes_StopsDatafeed_GivenJobFailsOnReassign failing

### ISSUE THREAD

**Issue by kkrik-es** [elastic/elasticsearch#103108]
**Build scan:**
https://gradle-enterprise.elastic.co/s/zq4t346hqu3hw/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT/testClusterWithTwoMlNodes_StopsDatafeed_GivenJobFailsOnReassign

**Reproduction line:**
```
./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testClusterWithTwoMlNodes_StopsDatafeed_GivenJobFailsOnReassign" -Dtests.seed=4A8F3E635CA139B -Dtests.locale=th-TH-u-nu-thai-x-lvariant-TH -Dtests.timezone=America/St_Barthelemy -Druntime.java=21
```

**Applicable branches:**
main, 8.12, 8.11

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT#testClusterWithTwoMlNodes_StopsDatafeed_GivenJobFailsOnReassign`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testClusterWithTwoMlNodes_StopsDatafeed_GivenJobFailsOnReassign'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: an empty collection
     but: <[LEAK: resource was not cleaned up before it was garbage-collected.
Recent access records: 
Created at:
	org.elasticsearch.action.search.ArraySearchPhaseResults.<init>(ArraySearchPhaseResults.java:25)
	org.elasticsearch.action.search.QueryPhaseResultConsumer.<init>(QueryPhaseResultConsumer.java:85)
	org.elasticsearch.action.search.SearchPhaseController.newSearchPhaseResults(SearchPhaseController.java:808)
	org.elasticsearch.action.search.TransportSearchAction$AsyncSearchActionProvider.newSearchPhase(TransportSearchAction.java:1302)
	org.elasticsearch.action.search.TransportSearchAction.executeSearch(TransportSearchAction.java:1131)
	org.elasticsearch.action.search.TransportSearchAction.executeLocalSearch(TransportSearchAction.java:913)
	org.elasticsearch.action.search.TransportSearchAction.lambda$executeRequest$10(TransportSearchAction.java:337)
	org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)
	org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:109)
	org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:77)
	org.elasticsearch.action.search.TransportSearchAction.executeRequest(TransportSearchAction.java:449)
	org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:304)
	org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:114)
	org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:87)
	org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:53)
	org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:85)
	org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:62)
	org.elasticsearch.tasks.TaskManager.registerAndExecute(TaskManager.java:196)
	org.elasticsearch.client.internal.node.NodeClient.executeLocally(NodeClient.java:108)
	org.elasticsearch.client.internal.node.NodeClient.doExecute(NodeClient.java:86)
	org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:381)
	org.elasticsearch.client.internal.FilterClient.doExecute(FilterClient.java:54)
	org.elasticsearch.client.internal.ParentTaskAssigningClient.doExecute(ParentTaskAssigningClient.java:59)
	org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:381)
	org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:367)
	org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:34)
	org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:41)
	org.elasticsearch.xpack.core.ClientHelper.executeWithHeaders(ClientHelper.java:274)
	org.elasticsearch.xpack.ml.datafeed.extractor.scroll.ScrollDataExtractor.executeSearchRequest(ScrollDataExtractor.java:137)
	org.elasticsearch.xpack.ml.datafeed.extractor.scroll.ScrollDataExtractor.initScroll(ScrollDataExtractor.java:124)
	org.elasticsearch.xpack.ml.datafeed.extractor.scroll.ScrollDataExtractor.tryNextStream(ScrollDataExtractor.java:118)
	org.elasticsearch.xpack.ml.datafeed.extractor.scroll.ScrollDataExtractor.next(ScrollDataExtractor.java:101)
	org.elasticsearch.xpack.ml.datafeed.extractor.chunked.ChunkedDataExtractor.getNextStream(ChunkedDataExtractor.java:172)
	org.elasticsearch.xpack.ml.datafeed.extractor.chunked.ChunkedDataExtractor.next(ChunkedDataExtractor.java:118)
	org.elasticsearch.xpack.ml.datafeed.DatafeedJob.run(DatafeedJob.java:376)
	org.elasticsearch.xpack.ml.datafeed.DatafeedJob.runLookBack(DatafeedJob.java:179)
	org.elasticsearch.xpack.ml.datafeed.DatafeedRunner$Holder.executeLookBack(DatafeedRunner.java:548)
	org.elasticsearch.xpack.ml.datafeed.DatafeedRunner$2.doRun(DatafeedRunner.java:247)
	org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:916)
	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	java.base/java.lang.Thread.run(Thread.java:1583)]>

  at __randomizedtesting.SeedInfo.seed([4A8F3E635CA139B:6707958DFCAD798A]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:726)
  at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:517)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by droberts195** [comment]
@original-brownbear this must be a side effect of #103009.

I cannot see an obvious reason for the leak.

The test where this is happening is a complex internal cluster test that runs two ML nodes in the same JVM and stops one of them while ML code is running. Could that be the reason?

**Comment by kingherc** [comment]
Another one at [elasticsearch / periodic / platform-support / 8.12 / sles-12 / platform-support-unix](https://gradle-enterprise.elastic.co/s/xcihisgol6i64)

**Comment by droberts195** [comment]
A different test in the same suite has just failed in the same way: https://github.com/elastic/elasticsearch/issues/104071

**Comment by mark-vieira** [comment]
This one is continuing to fail as well: https://gradle-enterprise.elastic.co/s/pg2hjpcf7jy4c/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT/testClusterWithTwoMlNodes_StopsDatafeed_GivenJobFailsOnReassign

**Comment by mark-vieira** [comment]
I've muted this on `main`, `8.12` and `8.11`.

**Comment by alex-spies** [comment]
Another failure on main: https://gradle-enterprise.elastic.co/s/vs5c4ha5kdgus/tests/task/:x-pack:plugin:ml:internalClusterTest/details/org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT/testClusterWithTwoMlNodes_StopsDatafeed_GivenJobFailsOnReassign?top-execution=1
