### ISSUE TITLE
Using bundled JDK, but encountering errors during startup referring to the local JDK. 

### ISSUE THREAD

**Issue by yizhi1654** [elastic/elasticsearch#103241]
### Elasticsearch Version

8.5.3

### Installed Plugins

null

### Java Version

_bundled_

### OS Version

win10

### Problem Description

After downloading and extracting, I haven't made any modifications. Upon directly clicking bin/elasticsearch.bat, the command line indicates the use of the bundled JDK instead of the system JDK. However, during startup, it throws an error related to not finding the JDK file within my system. Why is it attempting to use my system's JDK? This issue persists even with the latest version. When I check elasticsearch.log, it indicates that it can't locate the JDK file from my system.

### Steps to Reproduce

"Win10, JDK 17 as the Java environment, encountering the following error. 
[2023-12-10T16:14:25,843][ERROR][o.e.b.Elasticsearch      ] [BUCHEN] fatal exception while booting Elasticsearch
java.nio.file.NoSuchFileException: E:\SDK\JDK17\lib\dt.jar
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53) ~[?:?]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1849) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1279) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:710) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:345) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:316) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:255) ~[?:?]
	at org.elasticsearch.jdk.JarHell.checkJarHell(JarHell.java:221) ~[elasticsearch-core-8.5.3.jar:?]
	at org.elasticsearch.jdk.JarHell.checkJarHell(JarHell.java:84) ~[elasticsearch-core-8.5.3.jar:?]
	at org.elasticsearch.bootstrap.Elasticsearch.initPhase2(Elasticsearch.java:180) ~[elasticsearch-8.5.3.jar:?]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:66) ~[elasticsearch-8.5.3.jar:?]

### Logs (if relevant)

[2023-12-10T16:14:25,843][ERROR][o.e.b.Elasticsearch      ] [BUCHEN] fatal exception while booting Elasticsearch
java.nio.file.NoSuchFileException: E:\SDK\JDK17\lib\dt.jar
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53) ~[?:?]
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1849) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1279) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:710) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:345) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:316) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:255) ~[?:?]
	at org.elasticsearch.jdk.JarHell.checkJarHell(JarHell.java:221) ~[elasticsearch-core-8.5.3.jar:?]
	at org.elasticsearch.jdk.JarHell.checkJarHell(JarHell.java:84) ~[elasticsearch-core-8.5.3.jar:?]
	at org.elasticsearch.bootstrap.Elasticsearch.initPhase2(Elasticsearch.java:180) ~[elasticsearch-8.5.3.jar:?]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:66) ~[elasticsearch-8.5.3.jar:?]

**Comment by yizhi1654** [comment]
![image](https://github.com/elastic/elasticsearch/assets/112741300/7e796e4a-e6b6-49d9-950f-18e05489d339)
![image](https://github.com/elastic/elasticsearch/assets/112741300/3c069921-3199-4a77-a20d-0428ca5c9fe0)

**Comment by mark-vieira** [comment]
There should be a line earlier in the log indicating exactly what Java runtime is used. Is that pointing to the bundled JDK?

**Comment by yizhi1654** [comment]
> There should be a line earlier in the log indicating exactly what Java runtime is used. Is that pointing to the bundled JDK?

The screenshot above shows that JDK 17 was being used, not the bundled JDK. However, during startup, the console indicated the use of the bundled JDK. These details are visible in the screenshot above. Later, after removing the JDK from the environment variables, the application ran successfully. Thanks.😊

**Comment by mark-vieira** [comment]
I was referring to a log message that looks something like this:
```
[2023-12-14T18:55:52,775][INFO ][o.e.n.Node               ] [runTask-0] version[8.13.0-SNAPSHOT], pid[26171], build[tar/a08219761241f71eee80427d8ed69038ccec8ffb/2023-12-15T02:54:51.719568Z], OS[Mac OS X/14.2/aarch64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/21/21+35-2513]
```

In any case, it seems removing the `JAVA_HOME` environment variable solved your problem. This may very well be a bug in 8.5.3 but given that release is EOL I'll close this issue.

**Comment by yizhi1654** [comment]
> I was referring to a log message that looks something like this:
> 
> ```
> [2023-12-14T18:55:52,775][INFO ][o.e.n.Node               ] [runTask-0] version[8.13.0-SNAPSHOT], pid[26171], build[tar/a08219761241f71eee80427d8ed69038ccec8ffb/2023-12-15T02:54:51.719568Z], OS[Mac OS X/14.2/aarch64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/21/21+35-2513]
> ```
> 
> In any case, it seems removing the `JAVA_HOME` environment variable solved your problem. This may very well be a bug in 8.5.3 but given that release is EOL I'll close this issue.
There's no such log in either the log file or the console output. However, the error indicates the use of the JDK from the environment variable. This issue hasn't only occurred in this version; I've encountered it in other versions as well. Thank you for your response.😊😊

**Comment by mark-vieira** [comment]
> This issue hasn't only occurred in this version; I've encountered it in other versions as well. Thank you for your response.

If you are seeing this behavior in current versions of Elasticsearch please feel free to open a new issue. The behavior _should_ be that `JAVA_HOME` is completely ignored, and only `ES_JAVA_HOME` is used to override the bundled JDK.
