### ISSUE TITLE
testPeerRecoveryRetentionLeases -  Elasticsearch process died while waiting for ports file

### ISSUE THREAD

**Issue by maxhniebergall** [elastic/elasticsearch#103285]
### CI Link

https://gradle-enterprise.elastic.co/s/ihqhydeyivro4/console-log/task/:qa:full-cluster-restart:v8.12.0%23bwcTest?anchor=119&page=1

### Repro line

./gradlew ':qa:full-cluster-restart:v8.12.0#bwcTest' -Dtests.class="org.elasticsearch.upgrades.FullClusterRestartIT" -Dtests.method="testPeerRecoveryRetentionLeases {cluster=UPGRADED}" -Dtests.seed=DB593AC604795E85 -Dtests.bwc=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=es-ES -Dtests.timezone=Africa/Mogadishu -Druntime.java=21 -Dlicense.key=${PWD}/x-pack/license-tools/src/test/resources/public.key

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

REPRODUCE WITH: ./gradlew ':qa:full-cluster-restart:v8.12.0#bwcTest' -Dtests.class="org.elasticsearch.upgrades.FullClusterRestartIT" -Dtests.method="testPeerRecoveryRetentionLeases {cluster=UPGRADED}" -Dtests.seed=DB593AC604795E85 -Dtests.bwc=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=es-ES -Dtests.timezone=Africa/Mogadishu -Druntime.java=21 |  
-- | --
  |   |  
  | org.elasticsearch.upgrades.FullClusterRestartIT > testPeerRecoveryRetentionLeases {cluster=UPGRADED} FAILED |  
  | java.lang.RuntimeException: An error occurred orchestrating test cluster. |  
  | at __randomizedtesting.SeedInfo.seed([DB593AC604795E85:7CAD3B3E4818E181]:0) |  
  | at org.elasticsearch.test.cluster.local.DefaultLocalClusterHandle.execute(DefaultLocalClusterHandle.java:259) |  
  | at org.elasticsearch.test.cluster.local.DefaultLocalClusterHandle.writeUnicastHostsFile(DefaultLocalClusterHandle.java:240) |  
  | at org.elasticsearch.test.cluster.local.DefaultLocalClusterHandle.waitUntilReady(DefaultLocalClusterHandle.java:183) |  
  | at org.elasticsearch.test.cluster.local.DefaultLocalClusterHandle.upgradeToVersion(DefaultLocalClusterHandle.java:161) |  
  | at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster.upgradeToVersion(DefaultLocalElasticsearchCluster.java:150) |  
  | at org.elasticsearch.upgrades.ParameterizedFullClusterRestartTestCase.maybeUpgrade(ParameterizedFullClusterRestartTestCase.java:95) |  
  | at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) |  
  | at java.base/java.lang.reflect.Method.invoke(Method.java:580) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48) |  
  | at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43) |  
  | at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45) |  
  | at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60) |  
  | at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902) |  
  | at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:47) |  
  | at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) |  
  | at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38) |  
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53) |  
  | at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43) |  
  | at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44) |  
  | at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60) |  
  | at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850) |  
  | at java.base/java.lang.Thread.run(Thread.java:1583) |  
  |   |  
  | Caused by: |  
  | java.lang.RuntimeException: Elasticsearch process died while waiting for ports file. See console output for details. |  
  | at org.elasticsearch.test.cluster.local.AbstractLocalClusterFactory$Node.lambda$waitUntilReady$0(AbstractLocalClusterFactory.java:274) |  
  | at org.elasticsearch.test.cluster.util.Retry.lambda$retryUntilTrue$0(Retry.java:28) |  
  | ... 1 more |  
  |   |  
  | REPRODUCE WITH: ./gradlew ':qa:full-cluster-restart:v8.12.0#bwcTest' -Dtests.class="org.elasticsearch.upgrades.QueryBuilderBWCIT" -Dtests.method="testQueryBuilderBWC {cluster=UPGRADED}" -Dtests.seed=DB593AC604795E85 -Dtests.bwc=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=sl -Dtests.timezone=Asia/Thimphu -Druntime.java=21 |  
  |   |  
  | org.elasticsearch.upgrades.QueryBuilderBWCIT > testQueryBuilderBWC {cluster=UPGRADED} FAILED |  
  | java.lang.RuntimeException: An error occurred orchestrating test cluster. |  
  | at __randomizedtesting.SeedInfo.seed([DB593AC604795E85:D8C5D605EDD63D95]:0) |  
  | at org.elasticsearch.test.cluster.local.DefaultLocalClusterHandle.execute(DefaultLocalClusterHandle.java:259) |  
  | at org.elasticsearch.test.cluster.local.DefaultLocalClusterHandle.writeUnicastHostsFile(DefaultLocalClusterHandle.java:240) |  
  | at org.elasticsearch.test.cluster.local.DefaultLocalClusterHandle.waitUntilReady(DefaultLocalClusterHandle.java:183) |  
  | at org.elasticsearch.test.cluster.local.DefaultLocalClusterHandle.upgradeToVersion(DefaultLocalClusterHandle.java:161) |  
  | at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster.upgradeToVersion(DefaultLocalElasticsearchCluster.java:150) |  
  | at org.elasticsearch.upgrades.ParameterizedFullClusterRestartTestCase.maybeUpgrade(ParameterizedFullClusterRestartTestCase.java:95) |  
  | at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) |  
  | at java.base/java.lang.reflect.Method.invoke(Method.java:580) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48) |  
  | at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43) |  
  | at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45) |  
  | at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60) |  
  | at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902) |  
  | at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:47) |  
  | at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38) |  
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53) |  
  | at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43) |  
  | at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44) |  
  | at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60) |  
  | at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850) |  
  | at java.base/java.lang.Thread.run(Thread.java:1583) |  
  |   |  
  | Caused by: |  
  | java.lang.RuntimeException: Elasticsearch process died while waiting for ports file. See console output for details. |  
  | at org.elasticsearch.test.cluster.local.AbstractLocalClusterFactory$Node.lambda$waitUntilReady$0(AbstractLocalClusterFactory.java:274) |  
  | at org.elasticsearch.test.cluster.util.Retry.lambda$retryUntilTrue$0(Retry.java:28) |  
  | ... 1 more |  
  |   |  
  | Tests with failures: |  
  | - org.elasticsearch.upgrades.FullClusterRestartIT.testPeerRecoveryRetentionLeases {cluster=UPGRADED} |  
  | - org.elasticsearch.upgrades.QueryBuilderBWCIT.testQueryBuilderBWC {cluster=UPGRADED}

**Comment by mark-vieira** [comment]
Here's the root cause. I think the issue here is these tests are missing the failure store feature flag.

cc @jbaiera 

```
[2023-12-11T17:08:37,766][ERROR][o.e.b.Elasticsearch      ] [test-cluster-1] fatal exception while booting Elasticsearch org.elasticsearch.ElasticsearchException: failed to load metadata	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:120)	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.node.Node.start(Node.java:311)	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.bootstrap.Elasticsearch.start(Elasticsearch.java:458)	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:251)	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:73)	
Caused by: org.elasticsearch.gateway.CorruptStateException: org.elasticsearch.xcontent.XContentParseException: [-1:14350] [index_template] failed to parse field [index_template]	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.gateway.PersistedClusterStateService.readXContent(PersistedClusterStateService.java:675)	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.gateway.PersistedClusterStateService.lambda$loadOnDiskState$6(PersistedClusterStateService.java:573)	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.gateway.PersistedClusterStateService.consumeFromType(PersistedClusterStateService.java:717)	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.gateway.PersistedClusterStateService.loadOnDiskState(PersistedClusterStateService.java:572)	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.gateway.PersistedClusterStateService.loadBestOnDiskState(PersistedClusterStateService.java:496)	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.gateway.PersistedClusterStateService.loadBestOnDiskState(PersistedClusterStateService.java:411)	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.gateway.GatewayMetaState.createOnDiskPersistedState(GatewayMetaState.java:181)	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.gateway.GatewayMetaState.createPersistedState(GatewayMetaState.java:149)	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:107)	
	... 4 more	
Caused by: org.elasticsearch.xcontent.XContentParseException: [-1:14350] [index_template] failed to parse field [index_template]	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.ObjectParser.throwFailedToParse(ObjectParser.java:616)	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:611)	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.ObjectParser.parseSub(ObjectParser.java:629)	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:315)	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:166)	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.cluster.metadata.ComposableIndexTemplateMetadata.fromXContent(ComposableIndexTemplateMetadata.java:68)	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.NamedXContentRegistry$Entry.lambda$new$0(NamedXContentRegistry.java:54)	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.NamedXContentRegistry.parseNamedObject(NamedXContentRegistry.java:147)	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.support.AbstractXContentParser.namedObject(AbstractXContentParser.java:414)	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.cluster.metadata.Metadata$Builder.fromXContent(Metadata.java:2686)	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.gateway.PersistedClusterStateService.readXContent(PersistedClusterStateService.java:673)	
	... 12 more	
Caused by: org.elasticsearch.xcontent.XContentParseException: [-1:14350] [index_template] failed to parse field [data_stream]	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.ObjectParser.throwFailedToParse(ObjectParser.java:616)	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:611)	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.ObjectParser.parseSub(ObjectParser.java:629)	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:315)	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:166)	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.cluster.metadata.ComposableIndexTemplate.parse(ComposableIndexTemplate.java:107)	
	at org.elasticsearch.server@8.13.0/org.elasticsearch.cluster.metadata.ComposableIndexTemplateMetadata.lambda$static$1(ComposableIndexTemplateMetadata.java:51)	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.ObjectParser.lambda$declareField$10(ObjectParser.java:431)	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:609)	
	... 21 more	
Caused by: org.elasticsearch.xcontent.XContentParseException: [-1:14336] [data_stream_template] unknown field [failure_store]	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.ObjectParser.lambda$errorOnUnknown$2(ObjectParser.java:105)	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.ObjectParser.parse(ObjectParser.java:299)	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:166)	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.ObjectParser.lambda$declareField$10(ObjectParser.java:431)	
	at org.elasticsearch.xcontent@8.13.0/org.elasticsearch.xcontent.ObjectParser.parseValue(ObjectParser.java:609)	
	... 28 more
```
