### ISSUE TITLE
Use of javascript in mapping `transform` fails

### ISSUE THREAD

**Issue by lukas-vlcek** [elastic/elasticsearch#10336]
Below reproduction shows that while it is possible to use `groovy` in mapping `transform` the same operation fails when `javascript` is used.

Tested with Elasticsearch `1.4.1`, `1.4.4` and `1.5.0`.

### Reproduction

Download fresh Elasticsearch (`1.4.1`) and install lang-javascript plugin (`2.4.1`):

````bash
	wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.1.zip
	unzip elasticsearch-1.4.1.zip
	cd elasticsearch-1.4.1
	./bin/plugin install elasticsearch/elasticsearch-lang-javascript/2.4.1
````
	
Enable scripting:

````bash	
	echo script.disable_dynamic: false | tee -a config/elasticsearch.yml > /dev/null
	cat config/elasticsearch.yml | grep script
	# script.disable_dynamic: false
````
	
Start node:

````bash	
	./bin/elasticsearch -d
````
    
After node is ready check we have a fresh empty cluster with javascript plugin only:
	
````bash
	curl 'http://localhost:9200/_cat/health?v'
	# epoch      timestamp cluster       status node.total node.data shards pri relo init unassign 
	# 1427789340 10:09:00  elasticsearch green           1         1      0   0    0    0        0 
	
	curl 'localhost:9200/_cat/plugins?v'
	# name      component       version type url
	# Maur-Konn lang-javascript 2.4.1   j
````
    
Create index with `transform` script:

````bash
	curl -X PUT 'localhost:9200/test_javascript' -d '{
	  "mappings": {
	    "test": {
	      "transform": {
	        "script":"true",
	        "lang": "javascript"
	      }
	    }
	  }
	}'
	# {"acknowledged":true}
	
	curl -X PUT 'localhost:9200/test_groovy' -d '{
	  "mappings": {
	    "test": {
	      "transform": {
	        "script":"true",
	        "lang": "groovy"
	      }
	    }
	  }
	}'
	# {"acknowledged":true}
	
	curl -X GET 'localhost:9200/test*/_mapping?pretty'
	#{
	#  "test_groovy" : {
	#    "mappings" : {
	#      "test" : {
	#        "transform" : {
	#          "script" : "true",
	#          "lang" : "groovy"
	#        },
	#        "properties" : { }
	#      }
	#    }
	#  },
	#  "test_javascript" : {
	#    "mappings" : {
	#      "test" : {
	#        "transform" : {
	#          "script" : "true",
	#          "lang" : "javascript"
	#        },
	#        "properties" : { }
	#      }
	#    }
	#  }
	#}
````
	
Index document into test indices:

````bash
	curl -X POST 'localhost:9200/test_groovy/test' -d '{ "foo": "bar" }'
	# {"_index":"test_groovy","_type":"test","_id":"AUxu4fLdiRC7ona2R0WV","_version":1,"created":true}
	
	curl -X POST 'localhost:9200/test_javascript/test' -d '{ "foo": "bar" }'
	# {"error":"MapperParsingException[failed to parse]; nested: ElasticsearchIllegalArgumentException[failed to execute script]; nested: NullPointerException; ","status":400}
````
	
Check log file:

````	
less logs/elasticsearch.log

[2015-03-31 10:10:59,993][DEBUG][action.index             ] [Maur-Konn] [test_javascript][2], node[KF0FaHAPSAybJxQpwMPCow], [P], s[STARTED]: Failed to execute [index {[test_javascript][test][AUxu4jHGiRC7ona2R0WW], source[{ "foo": "bar" }]}]
org.elasticsearch.index.mapper.MapperParsingException: failed to parse
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:562)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:490)
        at org.elasticsearch.index.shard.service.InternalIndexShard.prepareCreate(InternalIndexShard.java:392)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:198)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:511)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: failed to execute script
        at org.elasticsearch.index.mapper.DocumentMapper$ScriptTransform.transformSourceAsMap(DocumentMapper.java:836)
        at org.elasticsearch.index.mapper.DocumentMapper.transformSourceAsMap(DocumentMapper.java:606)
        at org.elasticsearch.index.mapper.DocumentMapper.transform(DocumentMapper.java:612)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:507)
        ... 8 more
Caused by: java.lang.NullPointerException
        at org.elasticsearch.script.javascript.JavaScriptScriptEngineService.executable(JavaScriptScriptEngineService.java:113)
        at org.elasticsearch.script.ScriptService.executable(ScriptService.java:467)
        at org.elasticsearch.script.ScriptService.executable(ScriptService.java:463)
        at org.elasticsearch.index.mapper.DocumentMapper$ScriptTransform.transformSourceAsMap(DocumentMapper.java:828)
        ... 11 more

````

**Comment by dadoonet** [comment]
@lukas-vlcek I wonder if you should not better open it in javascript lang plugin instead of here. `org.elasticsearch.script.javascript.JavaScriptScriptEngineService` is in this plugin.

**Comment by lukas-vlcek** [comment]
@dadoonet To be honest I am not sure where exactly the problem is. Feel free to move it to [lang-javascript](https://github.com/elastic/elasticsearch-lang-javascript) if the problem is there.

**Comment by yesoreyeram** [comment]
Any workaround to run javascript in transform?

**Comment by lukas-vlcek** [comment]
@yesoreyeram regarding workaround I switched to `"lang": "groovy"`.

**Comment by clintongormley** [comment]
Mapping transform has been removed. Closing
