### ISSUE TITLE
[CI] SamlAuthenticationIT testLoginWithWrongRealmFails failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#103595]
**Build scan:**
https://gradle-enterprise.elastic.co/s/bcff22m6d6nto/tests/:x-pack:qa:saml-idp-tests:javaRestTest/org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT/testLoginWithWrongRealmFails

**Reproduction line:**
```
./gradlew ':x-pack:qa:saml-idp-tests:javaRestTest' --tests "org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.testLoginWithWrongRealmFails" -Dtests.seed=AAB24A59DF2ABBC4 -Dtests.locale=lt -Dtests.timezone=America/Indiana/Vevay -Druntime.java=21
```

**Applicable branches:**
main, 8.12, 8.11

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT#testLoginWithWrongRealmFails`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testLoginWithWrongRealmFails'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.apache.http.conn.HttpHostConnectException: Connect to localhost:32798 [localhost/127.0.0.1] failed: Connection refused

  at __randomizedtesting.SeedInfo.seed([AAB24A59DF2ABBC4:5FB6DB0EBFDF20F3]:0)
  at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
  at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
  at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
  at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
  at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
  at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
  at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
  at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
  at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.lambda$execute$4(SamlAuthenticationIT.java:510)
  at java.security.AccessController.doPrivileged(AccessController.java:571)
  at org.elasticsearch.xpack.core.common.socket.SocketAccess.doPrivileged(SocketAccess.java:32)
  at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.execute(SamlAuthenticationIT.java:510)
  at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.getIdpLoginPage(SamlAuthenticationIT.java:381)
  at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.testLoginWithWrongRealmFails(SamlAuthenticationIT.java:273)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:47)
  at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
  at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
  at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

  Caused by: java.net.ConnectException: Connection refused

    at sun.nio.ch.Net.pollConnect(Net.java:-2)
    at sun.nio.ch.Net.pollConnectNow(Net.java:682)
    at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
    at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
    at java.net.Socket.connect(Socket.java:751)
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
    at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.lambda$execute$4(SamlAuthenticationIT.java:510)
    at java.security.AccessController.doPrivileged(AccessController.java:571)
    at org.elasticsearch.xpack.core.common.socket.SocketAccess.doPrivileged(SocketAccess.java:32)
    at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.execute(SamlAuthenticationIT.java:510)
    at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.getIdpLoginPage(SamlAuthenticationIT.java:381)
    at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.testLoginWithWrongRealmFails(SamlAuthenticationIT.java:273)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:47)
    at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
    at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1583)

```

**Comment by mark-vieira** [comment]
@breskeby There's been a sudden uptick in failures on this suite since the refactor of the fixtures. Do you mind taking a look?

**Comment by breskeby** [comment]
Interestingly it looks like it started failing on 8.11 branch (without the refactoring) more often than on the branches with the fix. havn't figured out yet why

**Comment by alex-spies** [comment]
Potentially related build failure: https://gradle-enterprise.elastic.co/s/bd543seuui5ty

**Comment by nik9000** [comment]
Here's another one like alex's above: https://gradle-enterprise.elastic.co/s/5ioyt3mjsksi6/

**Comment by iverase** [comment]
two more: [8.11] https://gradle-enterprise.elastic.co/s/m7fozgmbkrwsa
                  [8.12] https://gradle-enterprise.elastic.co/s/35vpnm5w5fwdc

**Comment by kingherc** [comment]
One more [8.12] at https://gradle-enterprise.elastic.co/s/h7b7i33srf3le

**Comment by kingherc** [comment]
This ticket was still occurring only in 8.11 and 8.12 because in main there's a mute for the whole suite that was introduced in https://github.com/elastic/elasticsearch/commit/953b7ba99be1b2dc6485fccd5316f3339276d51a for ticket https://github.com/elastic/elasticsearch/issues/103717 .

I have just made a PR to backport than mute to 8.11 and 8.12.

If this ticket has the same cause as https://github.com/elastic/elasticsearch/issues/103717 , I would suggest to close it after that ticket is resolved.

**Comment by mark-vieira** [comment]
Got another one today :(

https://gradle-enterprise.elastic.co/s/koet2nzbg4wi4

@breskeby should we turn logging on for the fixture containers themselves to see if there is anything we can learn there?

**Comment by breskeby** [comment]
I'll have a look tomorrow. 🤞 it could be a transient error not being able to download the image 🤔

**Comment by mark-vieira** [comment]
> I'll have a look tomorrow. 🤞 it could be a transient error not being able to download the image 🤔

I would expect that to manifest as a different error as the fixture wouldn't even be able to start.

**Comment by jan-elastic** [comment]
One more: https://gradle-enterprise.elastic.co/s/zgt7n2se5i6h6

**Comment by joegallo** [comment]
https://gradle-enterprise.elastic.co/s/h5fuakwfltgps/

**Comment by mark-vieira** [comment]
Looks like the changes to pre-bake the fixture image helped, but we still get occassional failures. Interestingly, they seem to all be on ARM systems.

**Comment by mark-vieira** [comment]
I've recategorized this as low risk since the test is no longer muted.

**Comment by kingherc** [comment]
Also at [elasticsearch / periodic / platform-support / main / ubuntu-2004-aarch64 / checkPart2 / platform-support-arm](https://gradle-enterprise.elastic.co/s/72f3tfn6hl7mk)
Test failures:
[SamlAuthenticationIT » testLoginWithWrongRealmFails](https://gradle-enterprise.elastic.co/s/72f3tfn6hl7mk/tests/:x-pack:qa:saml-idp-tests:javaRestTest/org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT/testLoginWithWrongRealmFails)
[SamlAuthenticationIT » testLoginUserWithAuthorizingRealm](https://gradle-enterprise.elastic.co/s/72f3tfn6hl7mk/tests/:x-pack:qa:saml-idp-tests:javaRestTest/org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT/testLoginUserWithAuthorizingRealm)
[SamlAuthenticationIT » testLoginUserWithSamlRoleMapping](https://gradle-enterprise.elastic.co/s/72f3tfn6hl7mk/tests/:x-pack:qa:saml-idp-tests:javaRestTest/org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT/testLoginUserWithSamlRoleMapping)

**Comment by kingherc** [comment]
More at [elasticsearch / periodic / platform-support / main / ubuntu-2004-aarch64 / checkPart2 / platform-support-arm](https://gradle-enterprise.elastic.co/s/lwiclk3qk7bd6)
Test failures:
[SamlAuthenticationIT » testLoginUserWithAuthorizingRealm](https://gradle-enterprise.elastic.co/s/lwiclk3qk7bd6/tests/:x-pack:qa:saml-idp-tests:javaRestTest/org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT/testLoginUserWithAuthorizingRealm)
[SamlAuthenticationIT » testLoginUserWithSamlRoleMapping](https://gradle-enterprise.elastic.co/s/lwiclk3qk7bd6/tests/:x-pack:qa:saml-idp-tests:javaRestTest/org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT/testLoginUserWithSamlRoleMapping)
[SamlAuthenticationIT » testLoginWithWrongRealmFails](https://gradle-enterprise.elastic.co/s/lwiclk3qk7bd6/tests/:x-pack:qa:saml-idp-tests:javaRestTest/org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT/testLoginWithWrongRealmFails)

I will mute these 3 tests on main.

**Comment by breskeby** [comment]
This hasn't failed for more than a week after my latest change. I make the bold move and consider this closed. 🤞
