### ISSUE TITLE
Failure with `inner_hits` and multiple nested knn clauses

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#103792]
### Elasticsearch Version

v8.11+

### Java Version

_bundled_

### OS Version

_any_

### Problem Description

When attempting to gather inner-hits across multiple nested kNN fields under the same nested context, the search will fail.

Example failure:
```
[inner_hits] already contains an entry for key [paragraphs]
```

### Steps to Reproduce

```
DELETE test-index

PUT test-index
{
  "mappings": {
    "properties": {
      "paragraphs": {
        "type": "nested",
        "properties": {
          "documentText": {
            "type": "text"
          },
          "documentTitle": {
            "type": "text"
          },
          "textEmbedding": {
            "type": "dense_vector"
          },
          "titleEmbedding": {
            "type": "dense_vector"
          }
        }
      }
    }
  }
}

POST test-index/_doc
{
  "paragraphs": [
	{
	  "documentText": "foo bar",
	  "documentTitle": "foo bar",
	  "textEmbedding": [0.1, 0.2],
	  "titleEmbedding": [0.1, 0.2]
	},
	{
	  "documentText": "foo bar",
	  "documentTitle": "foo bar",
	  "textEmbedding": [0.1, 0.2],
	  "titleEmbedding": [0.1, 0.2]
	}
  ]
}

POST test-index/_search?error_trace
{
  "knn": [
    {
      "field": "paragraphs.titleEmbedding",
      "query_vector": [
        0.1, 0.2
      ],
      "k": 20,
      "num_candidates": 50,
      "inner_hits": {
        "_source": [
          "paragraphs.documentTitle"
        ],
        "fields": [
          "paragraphs.documentTitle"
        ]
      }
    },
    {
      "field": "paragraphs.textEmbedding",
      "query_vector": [
        0.1, 0.2
      ],
      "k": 20,
      "num_candidates": 50,
      "inner_hits": {
        "_source": [
          "paragraphs.documentText"
        ],
        "fields": [
          "paragraphs.documentText"
        ]
      }
    }
  ]
}
```

### Logs (if relevant)

```
"java.lang.IllegalArgumentException: [inner_hits] already contains an entry for key [paragraphs]
  at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.index.query.NestedQueryBuilder.extractInnerHitBuilders(NestedQueryBuilder.java:319)
  at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.index.query.InnerHitContextBuilder.extractInnerHits(InnerHitContextBuilder.java:67)
  at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.index.query.BoolQueryBuilder.extractInnerHitBuilders(BoolQueryBuilder.java:389)
  at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.index.query.InnerHitContextBuilder.extractInnerHits(InnerHitContextBuilder.java:67)
  at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.search.SearchService.parseSource(SearchService.java:1238)
  at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.search.SearchService.createContext(SearchService.java:1041)
  at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.search.SearchService.lambda$executeQueryPhase$6(SearchService.java:774)
  at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:73)
  at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:70)
  at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:95)
  at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
  at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
  at org.elasticsearch.server@8.13.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by benwtrent** [comment]
I am able to bypass this behavior by supplying a unique `name` for each inner_hit definition. This is a frustrating experience, but I understand why the bug occurs.

We should at a minimum document this behavior as it relates to `knn` to prevent future confusion. This behavior is already documented at a high-level in the [inner-hits documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/inner-hits.html)

Example:

```
{
  "knn": [
    {
      "field": "paragraphs.titleEmbedding",
      "query_vector": [
        0.1, 0.2
      ],
      "k": 20,
      "num_candidates": 50,
      "inner_hits": {
		"name": "title",
        "_source": [
          "paragraphs.documentTitle"
        ],
        "fields": [
          "paragraphs.documentTitle"
        ]
      }
    },
    {
      "field": "paragraphs.textEmbedding",
      "query_vector": [
        0.1, 0.2
      ],
      "k": 20,
      "num_candidates": 50,
      "inner_hits": {
		"name": "text",
        "_source": [
          "paragraphs.documentText"
        ],
        "fields": [
          "paragraphs.documentText"
        ]
      }
    }
  ]
}
```

**Comment by benwtrent** [comment]
Updated the documentation here: https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html

Since we cannot infer separate names without adding confusion, folks should add names themselves.

**Comment by jeffvestal** [comment]
This is what I have been doing. I thought it was less of a "bug" and more just how it works. 
Great to have it documented though.
