### ISSUE TITLE
[CI] CoordinatedInferenceIngestIT testIngestWithMultipleModelTypes failing

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#103868]
Same problem as #103808 - when the `pytorch_inference` process fails to connect to the JVM an uncaught exception crashes the whole node.

**Build scan:**
https://gradle-enterprise.elastic.co/s/xzzjqu7pq4gkc/tests/:x-pack:plugin:ml:qa:ml-inference-service-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.CoordinatedInferenceIngestIT/testIngestWithMultipleModelTypes

**Reproduction line:**
```
./gradlew ':x-pack:plugin:ml:qa:ml-inference-service-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.CoordinatedInferenceIngestIT.testIngestWithMultipleModelTypes" -Dtests.seed=34EA2F866A20CC72 -Dtests.locale=bg -Dtests.timezone=Asia/Kuching -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.ml.integration.CoordinatedInferenceIngestIT#testIngestWithMultipleModelTypes`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testIngestWithMultipleModelTypes'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.ml.integration.CoordinatedInferenceIngestIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:35821], URI [/_ml/trained_models/pytorch_model/deployment/_start?timeout=40s&wait_for=started&threads_per_allocation=1&number_of_allocations=1], status line [HTTP/1.1 408 Request Timeout]
{"error":{"root_cause":[{"type":"status_exception","reason":"Starting deployment timed out after [40s]"}],"type":"status_exception","reason":"Starting deployment timed out after [40s]"},"status":408}

  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:351)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:317)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:292)
  at org.elasticsearch.xpack.ml.integration.CoordinatedInferenceIngestIT.startDeployment(CoordinatedInferenceIngestIT.java:293)
  at org.elasticsearch.xpack.ml.integration.CoordinatedInferenceIngestIT.testIngestWithMultipleModelTypes(CoordinatedInferenceIngestIT.java:66)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:47)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by droberts195** [comment]
```
[2024-01-03T22:11:57,746][ERROR][o.e.x.m.i.a.TrainedModelAssignmentNodeService] [test-cluster-0] [pytorch_model] model [pytorch_model] failed to load
java.lang.IllegalStateException: Future got interrupted
        at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:48) ~[elasticsearch-8.12.0-SNAPSHOT.jar:?]
        at org.elasticsearch.action.support.PlainActionFuture.actionGet(PlainActionFuture.java:191) ~[elasticsearch-8.12.0-SNAPSHOT.jar:?]
        at org.elasticsearch.xpack.ml.inference.assignment.TrainedModelAssignmentNodeService.loadQueuedModels(TrainedModelAssignmentNodeService.java:211) ~[?:?]
        at org.elasticsearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:223) ~[elasticsearch-8.12.0-SNAPSHOT.jar:?]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983) ~[elasticsearch-8.12.0-SNAPSHOT.jar:?]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.12.0-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1100) ~[?:?]
        at org.elasticsearch.action.support.PlainActionFuture$Sync.get(PlainActionFuture.java:322) ~[elasticsearch-8.12.0-SNAPSHOT.jar:?]
        at org.elasticsearch.action.support.PlainActionFuture.get(PlainActionFuture.java:91) ~[elasticsearch-8.12.0-SNAPSHOT.jar:?]
        at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:45) ~[elasticsearch-8.12.0-SNAPSHOT.jar:?]
        ... 8 more
[2024-01-03T22:11:57,745][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [test-cluster-0] uncaught exception in thread [elasticsearch[test-cluster-0][ml_utility][T#3]]
org.elasticsearch.ElasticsearchException: Failed to connect to pytorch process for job pytorch_model
        at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.serverError(ExceptionsHelper.java:66) ~[?:?]
        at org.elasticsearch.xpack.ml.inference.pytorch.process.NativePyTorchProcessFactory.createProcess(NativePyTorchProcessFactory.java:98) ~[?:?]
        at org.elasticsearch.xpack.ml.inference.pytorch.process.NativePyTorchProcessFactory.createProcess(NativePyTorchProcessFactory.java:31) ~[?:?]
        at org.elasticsearch.xpack.ml.inference.deployment.DeploymentManager$ProcessContext.startAndLoad(DeploymentManager.java:500) ~[?:?]
        at org.elasticsearch.xpack.ml.inference.deployment.DeploymentManager.lambda$startDeployment$4(DeploymentManager.java:204) ~[?:?]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:916) ~[elasticsearch-8.12.0-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.io.FileNotFoundException: /dev/shm/bk/bk-agent-prod-gcp-1704290614526839664/elastic/elasticsearch-intake/x-pack/plugin/ml/qa/ml-inference-service-tests/build/testrun/javaRestTest/temp/test-cluster15350844261989684800/test-cluster-0/tmp/pytorch_inference_pytorch_model_log_13278 (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[?:?]
        at java.io.FileInputStream.open(FileInputStream.java:213) ~[?:?]
        at java.io.FileInputStream.<init>(FileInputStream.java:152) ~[?:?]
        at java.io.FileInputStream.<init>(FileInputStream.java:106) ~[?:?]
        at org.elasticsearch.xpack.ml.utils.NamedPipeHelper$PrivilegedInputPipeOpener.run(NamedPipeHelper.java:288) ~[?:?]
        at org.elasticsearch.xpack.ml.utils.NamedPipeHelper$PrivilegedInputPipeOpener.run(NamedPipeHelper.java:277) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:319) ~[?:?]
        at org.elasticsearch.xpack.ml.utils.NamedPipeHelper.openNamedPipeInputStream(NamedPipeHelper.java:130) ~[?:?]
        at org.elasticsearch.xpack.ml.utils.NamedPipeHelper.openNamedPipeInputStream(NamedPipeHelper.java:97) ~[?:?]
        at org.elasticsearch.xpack.ml.process.ProcessPipes.connectLogStream(ProcessPipes.java:158) ~[?:?]
        at org.elasticsearch.xpack.ml.process.AbstractNativeProcess.start(AbstractNativeProcess.java:92) ~[?:?]
        at org.elasticsearch.xpack.ml.inference.pytorch.process.NativePyTorchProcessFactory.createProcess(NativePyTorchProcessFactory.java:89) ~[?:?]
        ... 7 more
```

**Comment by droberts195** [comment]
Also in the log:

```
[2024-01-03T22:09:33,565][INFO ][o.e.x.m.i.d.DeploymentManager] [test-cluster-0] [pytorch_model] Starting model deployment of model [pytorch_model]
[2024-01-03T22:09:34,491][WARN ][o.e.x.m.p.l.CppLogMessageHandler] [test-cluster-0] [controller/13881] [CDetachedProcessSpawner.cc@202] Child process with PID 21072 has exited with exit code 127
[2024-01-03T22:09:44,906][ERROR][o.e.x.m.i.p.p.NativePyTorchProcessFactory] [test-cluster-0] Failed to connect to pytorch process for job pytorch_model
```
