### ISSUE TITLE
[CI] DownsampleActionIT testRollupNonTSIndex failing

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#103981]
**Build scan:**
https://gradle-enterprise.elastic.co/s/ruzhsbyskkuk6/tests/:x-pack:plugin:ilm:qa:multi-node:javaRestTest/org.elasticsearch.xpack.ilm.actions.DownsampleActionIT/testRollupNonTSIndex

**Reproduction line:**
```
./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.actions.DownsampleActionIT.testRollupNonTSIndex" -Dtests.seed=25F9F6ED0F69AEE9 -Dtests.locale=ar-DZ -Dtests.timezone=Europe/Monaco -Druntime.java=19
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.ilm.actions.DownsampleActionIT#testRollupNonTSIndex`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testRollupNonTSIndex'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.ilm.actions.DownsampleActionIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <{"phase":"warm","action":"complete","name":"complete"}>
     but: was <{"phase":"null","action":"null","name":"null"}>

  at __randomizedtesting.SeedInfo.seed([25F9F6ED0F69AEE9:B9F4C90CB6DD48DE]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.ilm.actions.DownsampleActionIT.lambda$testRollupNonTSIndex$16(DownsampleActionIT.java:404)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1281)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1254)
  at org.elasticsearch.xpack.ilm.actions.DownsampleActionIT.testRollupNonTSIndex(DownsampleActionIT.java:404)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

**Comment by DaveCTurner** [comment]
Failed again at https://gradle-enterprise.elastic.co/s/4hzqteph2qrpo, reinstating the mute.

**Comment by martijnvg** [comment]
No reported failures since the last ~2 weeks, which was when #106563 was merged. I think that change stabilized this test as well.

**Comment by jonathan-buttner** [comment]
Another failure today: https://gradle-enterprise.elastic.co/s/b6u4ilthqirna/tests/task/:x-pack:plugin:ilm:qa:multi-node:javaRestTest/details/org.elasticsearch.xpack.ilm.actions.DownsampleActionIT/testRollupNonTSIndex?top-execution=1

**Comment by kkrik-es** [comment]
There was a single failure over the past week, over more than 2k runs. Re-enabling the test for coverage, keeping an eye for further failures.

**Comment by kkrik-es** [comment]
No more failures over the past week. Closing it for now.

**Comment by kkrik-es** [comment]
Seems like a race condition:

```
1> [2024-04-24T19:24:50,027][INFO ][o.e.x.i.a.DownsampleActionIT] [testRollupNonTSIndex] --> running [testRollupNonTSIndex] with index [index-kugukislys], data stream [ds-cwycolhzpu], alias [alias-ppQRH] and policy [policy-UuNay]
  1> [2024-04-24T19:25:00,353][WARN ][o.e.x.i.a.DownsampleActionIT] [testRollupNonTSIndex] --> original index name is [index-kugukislys], rollup index name is NULL, possible explanation: {index=index-kugukislys, managed=true, policy=policy-UuNay, index_creation_date_millis=1713968690115, time_since_index_creation=10.23s, step_info={type=illegal_argument_exception, reason=policy [policy-UuNay] does not exist}}
Â» [2024-04-24T14:25:00,549][ERROR][o.e.x.i.IndexLifecycleRunner] [javaRestTest-3] policy [policy-UuNay] for index [index-kugukislys] failed on step [{"phase":"warm","action":"migrate","name":"migrate"}]. Moving to ERROR step [index-kugukislys/zdP8uRrlTiWztDwfcKEEBA] org.elasticsearch.index.IndexNotFoundException: no such index [index-kugukislys]
```

Waiting for longer should allow for things to work.

**Comment by davidkyle** [comment]
Failed on 8.14 https://gradle-enterprise.elastic.co/s/ns3igizthf3eq

@kkrik-es was the fix backported?

**Comment by kkrik-es** [comment]
Yeah I saw the failure.. I didn't backport the fix, will do so if I don't see another failure in main this week.

**Comment by kkrik-es** [comment]
No more failures, closing (and backporting the fix) for now.
