### ISSUE TITLE
[CI] TopNOperatorTests testRandomMultiValuesTopN failing

### ISSUE THREAD

**Issue by joegallo** [elastic/elasticsearch#104167]
**Build scan:**
https://gradle-enterprise.elastic.co/s/4g3rokcrg4xfg/tests/:x-pack:plugin:esql:compute:test/org.elasticsearch.compute.operator.topn.TopNOperatorTests/testRandomMultiValuesTopN

**Reproduction line:**
```
gradlew ':x-pack:plugin:esql:compute:test' --tests "org.elasticsearch.compute.operator.topn.TopNOperatorTests.testRandomMultiValuesTopN" -Dtests.seed=CB6410900D99BF2F -Dtests.locale=en-PH -Dtests.timezone=Indian/Mahe -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.compute.operator.topn.TopNOperatorTests#testRandomMultiValuesTopN`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testRandomMultiValuesTopN'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.compute.operator.topn.TopNOperatorTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.IllegalStateException: Cannot find encoder for BytesRef value

  at __randomizedtesting.SeedInfo.seed([CB6410900D99BF2F:982255F933DEF647]:0)
  at org.elasticsearch.compute.operator.topn.DefaultSortableTopNEncoder.encodeBytesRef(DefaultSortableTopNEncoder.java:16)
  at org.elasticsearch.compute.operator.topn.KeyExtractorForBytesRef.nonNul(KeyExtractorForBytesRef.java:44)
  at org.elasticsearch.compute.operator.topn.KeyExtractorForBytesRef$MinForUnordered.writeKey(KeyExtractorForBytesRef.java:127)
  at org.elasticsearch.compute.operator.topn.TopNOperator$RowFiller.writeKey(TopNOperator.java:183)
  at org.elasticsearch.compute.operator.topn.TopNOperator$RowFiller.row(TopNOperator.java:176)
  at org.elasticsearch.compute.operator.topn.TopNOperator.addInput(TopNOperator.java:357)
  at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:214)
  at org.elasticsearch.compute.operator.Driver.run(Driver.java:139)
  at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:327)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by mark-vieira** [comment]
Muted
