### ISSUE TITLE
[CI] ShardSplittingQueryTests testSplitOnIdOrRouting failing

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#104111]
Fails reliably with the given seed.

**Build scan:**
https://gradle-enterprise.elastic.co/s/7r2q4kfosrh2s/tests/:server:test/org.elasticsearch.index.shard.ShardSplittingQueryTests/testSplitOnIdOrRouting

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.index.shard.ShardSplittingQueryTests.testSplitOnIdOrRouting" -Dtests.seed=783DCE0F1B0403A5 -Dtests.locale=zh-Hans-CN -Dtests.timezone=America/Montevideo -Druntime.java=21 -Dtests.fips.enabled=true
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
[Failure dashboard for `org.elasticsearch.index.shard.ShardSplittingQueryTests#testSplitOnIdOrRouting`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testSplitOnIdOrRouting'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.index.shard.ShardSplittingQueryTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: _1a(9.9.1):C371:[diagnostics={java.runtime.version=21.0.1+12-29, mergeFactor=1, java.vendor=Oracle Corporation, os=Linux, os.version=5.15.0-1047-gcp, timestamp=1704778597647, mergeMaxNumSegments=-1, lucene.version=9.9.1, source=merge, os.arch=amd64}]:[attributes={Lucene90StoredFieldsFormat.mode=BEST_SPEED}] :id=7goujv7o2tqptzxxnhti77hu0 docID: 16 actualID: 49. Actual: 9

  at __randomizedtesting.SeedInfo.seed([783DCE0F1B0403A5:E449997C44CD59D6]:0)
  at org.junit.Assert.fail(Assert.java:89)
  at org.junit.Assert.failEquals(Assert.java:187)
  at org.junit.Assert.assertNotEquals(Assert.java:201)
  at org.elasticsearch.index.shard.ShardSplittingQueryTests.assertSplit(ShardSplittingQueryTests.java:188)
  at org.elasticsearch.index.shard.ShardSplittingQueryTests.testSplitOnIdOrRouting(ShardSplittingQueryTests.java:119)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by tvernum** [comment]
I think shard splitting is distributed. Right?
This test has been around for so long that it's hard to know who owns it now.

**Comment by ywangd** [comment]
Git bisect shows the first bad commit is https://github.com/elastic/elasticsearch/commit/fc87985f9b112ad8a45f88f25bf1cfe2a4d5e32a which is a Lucene upgrade from `9.9.0-snapshot-910c721e065` to `9.9.0-snapshot-b13e4a121ab`. Hence I am transfering this to the search team and unassigning myself. 

Note the reproduction line has `fips` in it. But it is not relevant. The test failure is reproducible by just
```
./gradlew ':server:test' --tests "org.elasticsearch.index.shard.ShardSplittingQueryTests.testSplitOnIdOrRouting" -Dtests.seed=783DCE0F1B0403A5
```

**Comment by carlosdelest** [comment]
My git bisect investigation points at [581b6ed](https://github.com/elastic/elasticsearch/commit/581b6ed4085980fb585786469d14edf33f977c22) as the first commit with this problem (the commit here does not work as the Lucene snapshot is not present in the repo 🤔 , which could explain why that is a bad commit).

In any case, it is also a Lucene upgrade commit. [These](https://github.com/apache/lucene/compare/ea8b647..1138a406) are the changes between the previous and the new Lucene version that this commit introduces.

From what I see in the test execution, the iterator returned from a `ShardSplittingQuery` is somehow returning a document that has as Shard ID the one that shouldn't be included as part of the query, thus failing this check [here](https://github.com/elastic/elasticsearch/blob/553f75ca9b9ae6e344fb6e7b7924979d8638385a/server/src/test/java/org/elasticsearch/index/shard/ShardSplittingQueryTests.java#L188).

For now I can't reconcile the Lucene changes with the above explanation for the test failures; I'll ask the team for help.
