### ISSUE TITLE
Profiling can throw when using kNN with a pre-filter

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#104131]
### Elasticsearch Version

8.11+

### Java Version

_bundled_

### OS Version

_any_

### Problem Description

When profiling complex queries an exception can be thrown during profiling

### Steps to Reproduce

still working on this...

### Logs (if relevant)

```
Caused by: org.elasticsearch.search.dfs.DfsPhaseExecutionException: Dfs Failed [Exception during dfs phase]
  at org.elasticsearch.search.dfs.DfsPhase.execute(DfsPhase.java:61)
  at org.elasticsearch.search.SearchService.executeDfsPhase(SearchService.java:500)
  at org.elasticsearch.search.SearchService.lambda$executeDfsPhase$0(SearchService.java:489)
  at org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:51)
  at org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:48)
  at org.elasticsearch.action.ActionRunnable$3.doRun(ActionRunnable.java:73)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1583)
Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: index_out_of_bounds_exception: Index: 26, Size: 23
  at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:838)
  at java.util.ArrayList.add(ArrayList.java:510)
  at org.elasticsearch.search.profile.AbstractInternalProfileTree.addDependencyNode(AbstractInternalProfileTree.java:103)
  at org.elasticsearch.search.profile.AbstractInternalProfileTree.getProfileBreakdown(AbstractInternalProfileTree.java:78)
  at org.elasticsearch.search.profile.AbstractProfiler.getQueryBreakdown(AbstractProfiler.java:26)
  at org.elasticsearch.search.internal.ContextIndexSearcher.createWeight(ContextIndexSearcher.java:225)
  at org.apache.lucene.search.BooleanWeight.<init>(BooleanWeight.java:59)
  at org.apache.lucene.search.BooleanQuery.createWeight(BooleanQuery.java:245)
  at org.elasticsearch.search.internal.ContextIndexSearcher.createWeight(ContextIndexSearcher.java:230)
  at org.apache.lucene.search.ConstantScoreQuery.createWeight(ConstantScoreQuery.java:136)
  at org.apache.lucene.search.AbstractMultiTermQueryConstantScoreWrapper$RewritingWeight.rewrite(AbstractMultiTermQueryConstantScoreWrapper.java:174)
  at org.apache.lucene.search.AbstractMultiTermQueryConstantScoreWrapper$RewritingWeight$1.get(AbstractMultiTermQueryConstantScoreWrapper.java:269)
  at org.elasticsearch.search.profile.query.ProfileWeight$1.get(ProfileWeight.java:69)
  at org.apache.lucene.search.Boolean2ScorerSupplier.req(Boolean2ScorerSupplier.java:212)
  at org.apache.lucene.search.Boolean2ScorerSupplier.getInternal(Boolean2ScorerSupplier.java:131)
  at org.apache.lucene.search.Boolean2ScorerSupplier.get(Boolean2ScorerSupplier.java:111)
  at org.elasticsearch.search.profile.query.ProfileWeight$1.get(ProfileWeight.java:69)
  at org.apache.lucene.search.Boolean2ScorerSupplier.req(Boolean2ScorerSupplier.java:212)
  at org.apache.lucene.search.Boolean2ScorerSupplier.getInternal(Boolean2ScorerSupplier.java:131)
  at org.apache.lucene.search.Boolean2ScorerSupplier.get(Boolean2ScorerSupplier.java:111)
  at org.elasticsearch.search.profile.query.ProfileWeight$1.get(ProfileWeight.java:69)
  at org.elasticsearch.search.profile.query.ProfileWeight.scorer(ProfileWeight.java:45)
  at org.apache.lucene.search.AbstractKnnVectorQuery.getLeafResults(AbstractKnnVectorQuery.java:134)
  at org.apache.lucene.search.AbstractKnnVectorQuery.searchLeaf(AbstractKnnVectorQuery.java:117)
  at org.apache.lucene.search.AbstractKnnVectorQuery.lambda$parallelSearch$0(AbstractKnnVectorQuery.java:111)
  at java.util.concurrent.FutureTask.run(FutureTask.java:317)
  ... 6 more
```

**Comment by benwtrent** [comment]
When attempting to replicate this locally (with assertions on), I am actually hitting an assertion:

```
PUT test
{
    "mappings": {
        "properties": {
            "name": {
                "type": "keyword"
            },
            "vector": {
                "type": "dense_vector",
                "dims": 5,
                "index": true,
                "similarity": "l2_norm"
            }
        }
    }
}

PUT test/_doc/1
{
    "name": "cow.jpg",
    "vector": [
        230,
        300.33,
        -34.8988,
        15.555,
        -200
    ]
}

POST test/_search
{
    "profile": true,
    "knn": {
        "query_vector": [
            230,
            300.33,
            -34.8988,
            15.555,
            -200
        ],
        "field": "vector",
        "num_candidates": 100,
        "k": 10,
        "filter": [
            {
                "bool": {
                    "filter": [
                        {
                            "term": {
                                "name": {
                                    "value": "cow.jpg"
                                }
                            }
                        }
                    ],
                    "must": [
                        {
                            "match_all": {}
                        }
                    ]
                }
            }
        ]
    }
}
```

**Comment by benwtrent** [comment]
OK, with how kNN does pre-filtering, our profiling there is just busted. 

One of the key issues is here: https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/search/AbstractKnnVectorQuery.java#L76

We are already profiling the weight rewriting at the top level kNN action. However, we then are rewriting the prefilter, which fires this again:

https://github.com/elastic/elasticsearch/blob/94f2b6f1048405582185d153d1f2ca94a0118033/server/src/main/java/org/elasticsearch/search/internal/ContextIndexSearcher.java#L197

So, we trip the assertion as one rewrite for this profiler is already in flight (the kNN rewrite) and then we rewrite the prefilter. 

In production, this manifests itself as incorrect rewrite values. But I wonder if how we handle this profiling is part of the issue with the original IOOBE.

**Comment by benwtrent** [comment]
https://github.com/elastic/elasticsearch/issues/104235 Recreates the issue, but its not 100% reliable. Sometimes it passes.

While debugging during a failed run, I got a warning from intellij that one of my watched variables was updated from another thread and skipped my breakpoint! Which is weird, as multi-threaded search should be turned off during profiling. 

The failure is always within the `createWeight` phase. I don't know any `createWeight` actions that are actually multi-threaded. I am still digging into this as we are definitely running into something weird with kNN prefilters & profiling.

//CC @javanna FYI

**Comment by benwtrent** [comment]
OK, I added a check to make sure the currentThread when constructing the profiler is the same thread when using it, and it turns out it isn't. I am guessing we haven't turned off multi-threading when profiling is turned on?

```
Caused by: java.lang.IllegalStateException: Profiler is not thread-safe and can only be used from the thread that created it. Current thread: elasticsearch[node_s0][search_worker][T#3], profiler thread: elasticsearch[node_s0][search][T#4]
```

**Comment by benwtrent** [comment]
This is a multi-threaded search bug. We should not be using search workers and multi-threaded search when `profile: true`. Apparently we still are.

**Comment by benwtrent** [comment]
To triple verify, I looked for a race condition in this class: `AbstractInternalProfileTree`. From debugging, I see that this method: `AbstractInternalProfileTree#getProfileBreakdown` gets called from multiple threads, as the following new assertions trip:

```
    public PB getProfileBreakdown(E query) {
        int token = currentToken;
        boolean stackEmpty = stack.isEmpty();
        // If the stack is empty, we are a new root query
        if (stackEmpty) {
            // We couldn't find a rewritten query to attach to, so just add it as a
            // top-level root. This is just a precaution: it really shouldn't happen.
            // We would only get here if a top-level query that never rewrites for some reason.
            roots.add(token);

            // Increment the token since we are adding a new node, but notably, do not
            // updateParent() because this was added as a root
            currentToken += 1;
            assert token == currentToken - 1; // Will trip
            stack.add(token);
            return addDependencyNode(query, token);
        }

        updateParent(token);
        // Increment the token since we are adding a new node
        currentToken += 1;
        assert token == currentToken - 1; // will trip
        stack.add(token);
        return addDependencyNode(query, token);
    }
```
This indicates that `currentToken` is being double incremented or not incremented at all.

I cannot easily tell why we fail here. We do start the initial rewrite of the weights in a searcher thread and then the rewrites continue on in a search worker thread. (see previous comments)

**Comment by benwtrent** [comment]
Also note in my testing I periodically saw the following:
```
    Caused by: org.elasticsearch.search.dfs.DfsPhaseExecutionException: Dfs Failed [Exception during dfs phase]
        at org.elasticsearch.search.dfs.DfsPhase.execute(DfsPhase.java:62)
        at org.elasticsearch.search.SearchService.executeDfsPhase(SearchService.java:499)
        at org.elasticsearch.search.SearchService.lambda$executeDfsPhase$0(SearchService.java:488)
        at org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:73)
        at org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:70)
        at org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:95)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
    Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "parent" is null
        at org.elasticsearch.search.profile.AbstractInternalProfileTree.updateParent(AbstractInternalProfileTree.java:175)
        at org.elasticsearch.search.profile.AbstractInternalProfileTree.getProfileBreakdown(AbstractInternalProfileTree.java:72)
        at org.elasticsearch.search.profile.AbstractProfiler.getQueryBreakdown(AbstractProfiler.java:26)
        at org.elasticsearch.search.internal.ContextIndexSearcher.createWeight(ContextIndexSearcher.java:219)
        at org.apache.lucene.search.ConstantScoreQuery.createWeight(ConstantScoreQuery.java:136)
        at org.apache.lucene.search.AbstractMultiTermQueryConstantScoreWrapper$RewritingWeight.rewrite(AbstractMultiTermQueryConstantScoreWrapper.java:174)
        at org.apache.lucene.search.AbstractMultiTermQueryConstantScoreWrapper$RewritingWeight$1.get(AbstractMultiTermQueryConstantScoreWrapper.java:269)
        at org.elasticsearch.search.profile.query.ProfileWeight$1.get(ProfileWeight.java:69)
        at org.apache.lucene.search.Boolean2ScorerSupplier.req(Boolean2ScorerSupplier.java:212)
        at org.apache.lucene.search.Boolean2ScorerSupplier.getInternal(Boolean2ScorerSupplier.java:131)
        at org.apache.lucene.search.Boolean2ScorerSupplier.get(Boolean2ScorerSupplier.java:111)
        at org.elasticsearch.search.profile.query.ProfileWeight$1.get(ProfileWeight.java:69)
        at org.elasticsearch.search.profile.query.ProfileWeight.scorer(ProfileWeight.java:45)
        at org.apache.lucene.search.AbstractKnnVectorQuery.getLeafResults(AbstractKnnVectorQuery.java:116)
        at org.apache.lucene.search.AbstractKnnVectorQuery.searchLeaf(AbstractKnnVectorQuery.java:99)
        at org.apache.lucene.search.AbstractKnnVectorQuery.lambda$rewrite$0(AbstractKnnVectorQuery.java:86)
        at org.apache.lucene.search.TaskExecutor$TaskGroup.lambda$createTask$0(TaskExecutor.java:118)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        ... 6 more
    }
        at __randomizedtesting.SeedInfo.seed([F5E517678C2E344F:6537B3C296313554]:0)
        at app//org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:708)
        at app//org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:400)
        at app//org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:740)
        at app//org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:493)
        at app//org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:331)
        at app//org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:54)
        at app//org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:656)
        at app//org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1717)
        at app//org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1435)
        at app//org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1575)
        at app//org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1550)
        at app//org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:46)
        at app//org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:38)
        at app//org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:146)
        at app//org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:28)
        at app//org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
        at app//org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
        at app//org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.base@21/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21/java.lang.Thread.run(Thread.java:1583)

        Caused by:
        org.elasticsearch.ElasticsearchException$1: Cannot invoke "java.lang.Integer.intValue()" because "parent" is null
            at app//org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:673)
            at app//org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:398)
            ... 19 more

            Caused by:
            java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "parent" is null
                at org.elasticsearch.search.profile.AbstractInternalProfileTree.updateParent(AbstractInternalProfileTree.java:175)
                at org.elasticsearch.search.profile.AbstractInternalProfileTree.getProfileBreakdown(AbstractInternalProfileTree.java:72)
                at org.elasticsearch.search.profile.AbstractProfiler.getQueryBreakdown(AbstractProfiler.java:26)
                at org.elasticsearch.search.internal.ContextIndexSearcher.createWeight(ContextIndexSearcher.java:219)
                at org.apache.lucene.search.ConstantScoreQuery.createWeight(ConstantScoreQuery.java:136)
                at org.apache.lucene.search.AbstractMultiTermQueryConstantScoreWrapper$RewritingWeight.rewrite(AbstractMultiTermQueryConstantScoreWrapper.java:174)
                at org.apache.lucene.search.AbstractMultiTermQueryConstantScoreWrapper$RewritingWeight$1.get(AbstractMultiTermQueryConstantScoreWrapper.java:269)
                at org.elasticsearch.search.profile.query.ProfileWeight$1.get(ProfileWeight.java:69)
                at org.apache.lucene.search.Boolean2ScorerSupplier.req(Boolean2ScorerSupplier.java:212)
                at org.apache.lucene.search.Boolean2ScorerSupplier.getInternal(Boolean2ScorerSupplier.java:131)
                at org.apache.lucene.search.Boolean2ScorerSupplier.get(Boolean2ScorerSupplier.java:111)
                at org.elasticsearch.search.profile.query.ProfileWeight$1.get(ProfileWeight.java:69)
                at org.elasticsearch.search.profile.query.ProfileWeight.scorer(ProfileWeight.java:45)
                at org.apache.lucene.search.AbstractKnnVectorQuery.getLeafResults(AbstractKnnVectorQuery.java:116)
                at org.apache.lucene.search.AbstractKnnVectorQuery.searchLeaf(AbstractKnnVectorQuery.java:99)
                at org.apache.lucene.search.AbstractKnnVectorQuery.lambda$rewrite$0(AbstractKnnVectorQuery.java:86)
                at org.apache.lucene.search.TaskExecutor$TaskGroup.lambda$createTask$0(TaskExecutor.java:118)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
                ... 6 more
```

**Comment by benwtrent** [comment]
Whenever this is fixed, the following test needs to be unmuted: https://github.com/elastic/elasticsearch/issues/104235

**Comment by javanna** [comment]
I believe Here is the root cause of the issue: https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/search/AbstractMultiTermQueryConstantScoreWrapper.java#L174  is what you were looking for, that is the cause for createWeight being called concurrently. It's not so common, but it may happen when using multi term queries.
