### ISSUE TITLE
[CI] :docs:yamlRestTest task failed

### ISSUE THREAD

**Issue by jonathan-buttner** [elastic/elasticsearch#104105]
### CI Link

https://gradle-enterprise.elastic.co/s/aq7xp2f653wnm/failure

### Repro line

N/A

### Does it reproduce?

Didn't try

### Applicable branches

7.17

### Failure excerpt

```

> Task :docs:yamlRestTest FAILED
--
  | Exec output and error:
  | \| Output for ./bin/elasticsearch-keystore:Enter new password for the elasticsearch keystore (empty for no password): Enter same password again: Exception in thread "main" java.lang.NullPointerException: Cannot read the array length because "result" is null
  | \|       at org.elasticsearch.cli.Terminal.readSecret(Terminal.java:78)
  | \|       at org.elasticsearch.cli.KeyStoreAwareCommand.readPassword(KeyStoreAwareCommand.java:49)
  | \|       at org.elasticsearch.common.settings.CreateKeyStoreCommand.execute(CreateKeyStoreCommand.java:38)
  | \|       at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77)
  | \|       at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
  | \|       at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:95)
  | \|       at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
  | \|       at org.elasticsearch.cli.Command.main(Command.java:77)
  | \|       at org.elasticsearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:33)
  |  
  | > Task :client:rest-high-level:asyncJavaRestTest FAILED
  | Exec output and error:
  | \| Output for ./bin/elasticsearch-keystore:Enter value for xpack.security.transport.ssl.truststore.secure_password: Exception in thread "main" java.lang.NullPointerException: Cannot read the array length because "array" is null
  | \|       at java.base/java.nio.CharBuffer.wrap(CharBuffer.java:468)
  | \|       at org.elasticsearch.common.settings.KeyStoreWrapper.setString(KeyStoreWrapper.java:609)
  | \|       at org.elasticsearch.common.settings.AddStringKeyStoreCommand.executeCommand(AddStringKeyStoreCommand.java:94)
  | \|       at org.elasticsearch.common.settings.BaseKeyStoreCommand.execute(BaseKeyStoreCommand.java:61)
  | \|       at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77)
  | \|       at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
  | \|       at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:95)
  | \|       at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
  | \|       at org.elasticsearch.cli.Command.main(Command.java:77)
  | \|       at org.elasticsearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:33)



```

**Comment by jonathan-buttner** [comment]
I probably got the label wrong here, but I'm not sure who owns the keystore.

**Comment by rjernst** [comment]
Will be fixed by https://github.com/elastic/elasticsearch/pull/104102

**Comment by rjernst** [comment]
Closing in favor of https://github.com/elastic/elasticsearch/issues/103963 which is addressing Java 22 failures
