### ISSUE TITLE
[CI] MLModelDeploymentsUpgradeIT testTrainedModelDeployment failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#104193]
**Build scan:**
https://gradle-enterprise.elastic.co/s/pcdaqhet232e6/tests/:x-pack:qa:rolling-upgrade:v8.13.0%23oldClusterTest/org.elasticsearch.upgrades.MLModelDeploymentsUpgradeIT/testTrainedModelDeployment

**Reproduction line:**
```
./gradlew ':x-pack:qa:rolling-upgrade:v8.13.0#oldClusterTest' -Dtests.class="org.elasticsearch.upgrades.MLModelDeploymentsUpgradeIT" -Dtests.method="testTrainedModelDeployment" -Dtests.seed=ACACC12D680436E -Dtests.bwc=true -Dtests.locale=es-PA -Dtests.timezone=Cuba -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.upgrades.MLModelDeploymentsUpgradeIT#testTrainedModelDeployment`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testTrainedModelDeployment'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.upgrades.MLModelDeploymentsUpgradeIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:44549], URI [/_ml/trained_models/upgrade-deployment-test/deployment/_infer], status line [HTTP/1.1 409 Conflict]
Warnings: [[POST /_ml/trained_models/{model_id}/deployment/_infer] is deprecated! Use [POST /_ml/trained_models/{model_id}/_infer] instead.]
{"error":{"root_cause":[{"type":"status_exception","reason":"[upgrade-deployment-test] process context missing"}],"type":"status_exception","reason":"[upgrade-deployment-test] process context missing"},"status":409}

  at __randomizedtesting.SeedInfo.seed([ACACC12D680436E:F1128A4DF740F9F9]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:351)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:317)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:292)
  at org.elasticsearch.upgrades.MLModelDeploymentsUpgradeIT.infer(MLModelDeploymentsUpgradeIT.java:298)
  at org.elasticsearch.upgrades.MLModelDeploymentsUpgradeIT.assertInfer(MLModelDeploymentsUpgradeIT.java:191)
  at org.elasticsearch.upgrades.MLModelDeploymentsUpgradeIT.testTrainedModelDeployment(MLModelDeploymentsUpgradeIT.java:112)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by droberts195** [comment]
This is caused by caching the `deps` and `nodeps` artifacts differently. We tell Gradle it can cache for 2 hours here: https://github.com/elastic/elasticsearch/blob/709c0f5d31a08838c1c96fbb2bacc8fa532c76fe/x-pack/plugin/ml/build.gradle#L58

I am pretty sure what's happened is that the `deps` artifact has been cached, so contains the PyTorch 1.13.1 libraries. But the `nodeps` artifact has been newly downloaded, so contains a `pytorch_inference` process that's expecting to link against PyTorch 2.1.2.

It's possible to recreate these scenarios using a local Ivy repo and the `-Dbuild.ml_cpp.repo` argument for Gradle.

The repro command is this:

```
./gradlew ':x-pack:qa:rolling-upgrade:v8.13.0#bwcTest' -Dtests.class="org.elasticsearch.upgrades.MLModelDeploymentsUpgradeIT" -Dtests.bwc=true -Dbuild.ml_cpp.repo=/home/dave/ivy
```

Creating a local Ivy repo initialised inconsistently like this reproduces the exact same error:

```
wget https://artifacts-snapshot.elastic.co/ml-cpp/8.13.0-4066b45f/downloads/ml-cpp/ml-cpp-8.13.0-SNAPSHOT-nodeps.zip
wget https://artifacts-snapshot.elastic.co/ml-cpp/8.13.0-1f86b6c1/downloads/ml-cpp/ml-cpp-8.13.0-SNAPSHOT-deps.zip
```

Creating a local Ivy repo initialised consistently like this makes the test work:

```
wget https://artifacts-snapshot.elastic.co/ml-cpp/8.13.0-4066b45f/downloads/ml-cpp/ml-cpp-8.13.0-SNAPSHOT-nodeps.zip
wget https://artifacts-snapshot.elastic.co/ml-cpp/8.13.0-4066b45f/downloads/ml-cpp/ml-cpp-8.13.0-SNAPSHOT-deps.zip
```

This also explains why the PR CI in the ml-cpp repo works fine.

There is one more clue that inconsistent `deps`/`nodeps` artifacts are the problem. Flukily we have debug logging enabled for this test at the moment. With consistent artifacts and everything using PyTorch 2.1.2, the bit of debug where we log the PyTorch config contains this:

```
Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
```

But with PyTorch 1.13.1 it contains this:

```
Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
```

And before the crash the server-side log files from this issue contain that second log line. So it's pretty certain that this is caused by an inconsistent build where part of the ml-cpp code is old and part is new.

**Comment by droberts195** [comment]
I'm wondering if another reason we're seeing this now when we didn't on the last PyTorch upgrade is the Jenkins to BuildKite migration. With Jenkins the workers were unique to each CI job. But maybe BuildKite recycles them, leading to files already being in the Gradle cache?

**Comment by mark-vieira** [comment]
> I am pretty sure what's happened is that the `deps` artifact has been cached, so contains the PyTorch 1.13.1 libraries. But the `nodeps` artifact has been newly downloaded, so contains a `pytorch_inference` process that's expecting to link against PyTorch 2.1.2.

I'm not sure that's the case. In the build scan you can see that both artifacts were downloaded: https://gradle-enterprise.elastic.co/s/pcdaqhet232e6/performance/network-activity

So it may be the case that something was out of sync with these artifacts but not due to local caching since we grabbed the latest of both artifacts during the build linked above.

**Comment by mark-vieira** [comment]
> But maybe BuildKite recycles them, leading to files already being in the Gradle cache?

We still use ephemeral workers for all jobs.

**Comment by droberts195** [comment]
> So it may be the case that something was out of sync with these artifacts but not due to local caching since we grabbed the latest of both artifacts during the build linked above.

I wonder if we're paying the price of `x-goog-storage-class: MULTI_REGIONAL`:

```
bash-3.2$ curl -I https://artifacts-snapshot.elastic.co/ml-cpp/8.13.0-SNAPSHOT/downloads/ml-cpp/ml-cpp-8.13.0-SNAPSHOT-deps.zip
HTTP/2 200 
x-guploader-uploadid: ABPtcPp4vmxT3WYiqRapekY_MYRNM319Rqgl2RKsE_Gu3N6WiELGM5U35_wkkPHnSLCoL4HmGB1oVbsaMtXhn77YM60f
x-goog-generation: 1704888204708778
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 382042919
x-goog-hash: crc32c=79AgtQ==
x-goog-hash: md5=uyCFWcaFHyjqIh87YNzX4Q==
x-goog-expiration: Fri, 09 Feb 2024 12:03:24 GMT
x-goog-storage-class: MULTI_REGIONAL
accept-ranges: bytes
server: UploadServer
date: Wed, 10 Jan 2024 18:20:21 GMT
age: 1626
last-modified: Wed, 10 Jan 2024 12:03:24 GMT
etag: "bb208559c6851f28ea221f3b60dcd7e1"
content-type: application/zip
vary: Origin
content-length: 382042919
cache-control: public,max-age=3600
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

bash-3.2$ curl -I https://artifacts-snapshot.elastic.co/ml-cpp/8.13.0-SNAPSHOT/downloads/ml-cpp/ml-cpp-8.13.0-SNAPSHOT-nodeps.zip
HTTP/2 200 
x-guploader-uploadid: ABPtcPoQM3TNFXc9Zfs1ns9yxNwPUSfYB6WQnZ6LeBraqx1OpOrsycIffzIzf29FbFjThvGzNek0N1VuQ6DHppc4LThDmA
x-goog-generation: 1704888206135134
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 42927229
x-goog-hash: crc32c=UGNQFw==
x-goog-hash: md5=N2SwsO4W9kHivM3hHQdopA==
x-goog-expiration: Fri, 09 Feb 2024 12:03:26 GMT
x-goog-storage-class: MULTI_REGIONAL
accept-ranges: bytes
server: UploadServer
date: Wed, 10 Jan 2024 18:20:21 GMT
age: 2124
last-modified: Wed, 10 Jan 2024 12:03:26 GMT
etag: "3764b0b0ee16f641e2bccde11d0768a4"
content-type: application/zip
vary: Origin
content-length: 42927229
cache-control: public,max-age=3600
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```

These files are stored in multiple regions, which makes them faster to download, but presumably they propagate at different rates to the different regions.

Maybe the reason we didn't have these problems for the last upgrade is if we were using S3 at that time rather than GCS. S3 had the problem that it was single region (Ireland), so slow to download for some parts of the world. But presumably didn't suffer from propagation delays.

I guess the pragmatic way around this is to merge the C++ PR late on Saturday evening and just ignore the failures for a few hours afterwards.

**Comment by mark-vieira** [comment]
> These files are stored in multiple regions, which makes them faster to download, but presumably they propagate at different rates to the different regions.

Certainly there's a way to enforce consistency here. Or some notion of atomic operations on groups of objects. We can't possibly be the first people to hit this. I expect if I update a set of objects in a bucket, that they are either all updated or none are across regions. There's so many other use cases where this would cause havoc.

**Comment by droberts195** [comment]
From https://cloud.google.com/storage/docs/consistency#atomic_operations:

> Cloud Storage provides atomicity guarantees for most operations involving individual objects, such as uploading an object, updating an object's metadata, and deleting an object. Operations involving multiple objects at once, such as copying or renaming multiple objects, are not atomic.

From https://cloud.google.com/storage/docs/availability-durability#key-concepts:

> * Objects stored in dual-regions can optionally use [turbo replication](https://cloud.google.com/storage/docs/availability-durability#turbo-replication) to achieve a faster, more predictable replication across regions.

So turbo replication is only available with **dual**-region storage, not **multi**-region. It costs 4¢/GB rather than 2¢/GB, which wouldn't be a problem if it was just applied to these ML objects. But I imagine the release team is going to complain if we ask them to have a different setup for the ml-cpp build artifacts compared to all the others.

We change the C++ dependencies in an interface-breaking way about once every 3 months. We can avoid doing loads of multi-team build system work if we just plan to merge these changes during weekends when nothing else important is happening and accept there'll be some spurious build failures for a couple of hours afterwards. If we pick a time when nobody will be doing test triage for the next few hours then the failures will likely go unnoticed.

**Comment by mark-vieira** [comment]
> We change the C++ dependencies in an interface-breaking way about once every 3 months.

Thanks, David. I agree, this seems like an infrequent enough scenario where it doesn't seem worth jumping through hoops.
