### ISSUE TITLE
[CI] DfsProfilerIT testProfileDfs failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#104235]
This reproduced locally for me.

**Build scan:**
https://gradle-enterprise.elastic.co/s/5tk2twhstr3iy/tests/:server:internalClusterTest/org.elasticsearch.search.profile.dfs.DfsProfilerIT/testProfileDfs

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.search.profile.dfs.DfsProfilerIT.testProfileDfs" -Dtests.seed=F1A3160151EBA0D6 -Dtests.locale=tr-TR -Dtests.timezone=America/Indiana/Knox -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
[Failure dashboard for `org.elasticsearch.search.profile.dfs.DfsProfilerIT#testProfileDfs`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testProfileDfs'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.search.profile.dfs.DfsProfilerIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed

  at __randomizedtesting.SeedInfo.seed([F1A3160151EBA0D6:D5270E587F366AE1]:0)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:708)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:400)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:740)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:493)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:331)
  at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:54)
  at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:656)
  at org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1717)
  at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1435)
  at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1575)
  at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1550)
  at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:46)
  at org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:38)
  at org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:146)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:28)
  at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1583)

  Caused by: org.elasticsearch.ElasticsearchException$1: Index: 33, Size: 31

    at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:673)
    at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:398)
    at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:740)
    at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:493)
    at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:331)
    at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:54)
    at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:656)
    at org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1717)
    at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1435)
    at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1575)
    at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1550)
    at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:46)
    at org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:38)
    at org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:146)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:28)
    at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.lang.Thread.run(Thread.java:1583)

    Caused by: java.lang.IndexOutOfBoundsException: Index: 33, Size: 31

      at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:838)
      at java.util.ArrayList.add(ArrayList.java:510)
      at org.elasticsearch.search.profile.AbstractInternalProfileTree.addDependencyNode(AbstractInternalProfileTree.java:103)
      at org.elasticsearch.search.profile.AbstractInternalProfileTree.getProfileBreakdown(AbstractInternalProfileTree.java:78)
      at org.elasticsearch.search.profile.AbstractProfiler.getQueryBreakdown(AbstractProfiler.java:26)
      at org.elasticsearch.search.internal.ContextIndexSearcher.createWeight(ContextIndexSearcher.java:219)
      at org.apache.lucene.search.ConstantScoreQuery.createWeight(ConstantScoreQuery.java:136)
      at org.apache.lucene.search.AbstractMultiTermQueryConstantScoreWrapper$RewritingWeight.rewrite(AbstractMultiTermQueryConstantScoreWrapper.java:174)
      at org.apache.lucene.search.AbstractMultiTermQueryConstantScoreWrapper$RewritingWeight$1.get(AbstractMultiTermQueryConstantScoreWrapper.java:269)
      at org.elasticsearch.search.profile.query.ProfileWeight$1.get(ProfileWeight.java:69)
      at org.apache.lucene.search.DisjunctionMaxQuery$DisjunctionMaxWeight$1.get(DisjunctionMaxQuery.java:154)
      at org.elasticsearch.search.profile.query.ProfileWeight$1.get(ProfileWeight.java:69)
      at org.elasticsearch.search.profile.query.ProfileWeight$1.get(ProfileWeight.java:69)
      at org.elasticsearch.search.profile.query.ProfileWeight.scorer(ProfileWeight.java:45)
      at org.apache.lucene.search.AbstractKnnVectorQuery.getLeafResults(AbstractKnnVectorQuery.java:116)
      at org.apache.lucene.search.AbstractKnnVectorQuery.searchLeaf(AbstractKnnVectorQuery.java:99)
      at org.apache.lucene.search.AbstractKnnVectorQuery.lambda$rewrite$0(AbstractKnnVectorQuery.java:86)
      at org.apache.lucene.search.TaskExecutor$TaskGroup.lambda$createTask$0(TaskExecutor.java:118)
      at java.util.concurrent.FutureTask.run(FutureTask.java:317)
      at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
      at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
      at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
      at java.lang.Thread.run(Thread.java:1583)

```

**Comment by mark-vieira** [comment]
@benwtrent since you made some changes here recently do you mind taking a look? Since the reproduced for me I've muted for now.

**Comment by benwtrent** [comment]
@mark-vieira this is amazing! I was trying to reproduce this bug FOREVER and a test finally failed!!! YES!

This is the best test failure I have seen in a long time, thank you CI!

**Comment by benwtrent** [comment]
This failure is caused by this bug: https://github.com/elastic/elasticsearch/issues/104131
