### ISSUE TITLE
[CI] bwcTest with v7.17.17 fails under FIPS setup 

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#104293]
### CI Link

https://gradle-enterprise.elastic.co/s/bk3voq647prpm

### Repro line

N/A

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure history

N/A

### Failure excerpt

The 7.17.7 cluster failed to come up. It seems to me that the root cause is the follows:

```
» [2024-01-12T05:13:18,245][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v7.17.17-0] uncaught exception in thread [main]
»  org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [xpack.security.fips_mode.required_providers] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
»  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:173) ~[elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:160) ~[elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77) ~[elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112) ~[elasticsearch-cli-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  	at org.elasticsearch.cli.Command.main(Command.java:77) ~[elasticsearch-cli-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:125) ~[elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) ~[elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  Caused by: java.lang.IllegalArgumentException: unknown setting [xpack.security.fips_mode.required_providers] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
»  	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:561) ~[elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:507) ~[elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:477) ~[elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:447) ~[elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:137) ~[elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  	at org.elasticsearch.node.Node.<init>(Node.java:502) ~[elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  	at org.elasticsearch.node.Node.<init>(Node.java:309) ~[elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234) ~[elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234) ~[elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434) ~[elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:169) ~[elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
»  	... 6 more
»  uncaught exception in thread [main]
```

**Comment by slobodanadamovic** [comment]
This is a duplicate of https://github.com/elastic/elasticsearch/issues/104234, which has already been fixed (https://github.com/elastic/elasticsearch/pull/104287).
