### ISSUE TITLE
[docker-compose] kibana container error log: resource_already_exists_exception: index [.apm-agent-configuration/sB9zCdtATuylj1_vgWgY4g] already exists

### ISSUE THREAD

**Issue by chaseSpace** [elastic/elasticsearch#104215]
### Elasticsearch Version

8.11.3

### Installed Plugins

default

### Java Version

_bundled_

### OS Version

Darwin Kernel Version 22.1.0 (macOS)

### Problem Description

I have referred to the official [docker-compose.yml](https://github.com/elastic/elasticsearch/blob/8.11/docs/reference/setup/install/docker/docker-compose.yml) to establish my three node ES clusters. I did not change `yml` file, below is my `.env` file:
```
# Password for the 'elastic' user (at least 6 characters)
ELASTIC_PASSWORD=123456

# Password for the 'kibana_system' user (at least 6 characters)
KIBANA_PASSWORD=123456

# Version of Elastic products
STACK_VERSION=8.11.3

# Set the cluster name
CLUSTER_NAME=docker-cluster

# Set to 'basic' or 'trial' to automatically start the 30-day trial
LICENSE=basic
#LICENSE=trial

# Port to expose Elasticsearch HTTP API to the host
ES_PORT=9200
#ES_PORT=127.0.0.1:9200

# Port to expose Kibana to the host
KIBANA_PORT=5601
#KIBANA_PORT=80

# Increase or decrease based on the available host memory (in bytes)
MEM_LIMIT=512241824

# Project namespace (defaults to the current folder name if not set)
COMPOSE_PROJECT_NAME=test
``` 

then I executed the command with following:
```
$ docker compose up -d

$ docker-compose ps
NAME                COMMAND                  SERVICE             STATUS              PORTS
test-es01-1         "/bin/tini -- /usr/l…"   es01                running (healthy)   0.0.0.0:9200->9200/tcp, 9300/tcp
test-es02-1         "/bin/tini -- /usr/l…"   es02                running (healthy)   9200/tcp, 9300/tcp
test-es03-1         "/bin/tini -- /usr/l…"   es03                running (healthy)   9200/tcp, 9300/tcp
test-kibana-1       "/bin/tini -- /usr/l…"   kibana              running (healthy)   0.0.0.0:5601->5601/tcp
test-setup-1        "/bin/tini -- /usr/l…"   setup               exited (0)  
```
and I checked container log of `test-kibana-1`:
```
2024-01-11 00:19:39 [2024-01-10T16:19:39.758+00:00][INFO ][status] Kibana is now degraded (was available)
2024-01-11 00:19:46 [2024-01-10T16:19:46.026+00:00][INFO ][status] Kibana is now available (was degraded)
2024-01-11 00:20:00 [2024-01-10T16:20:00.784+00:00][INFO ][status] Kibana is now degraded (was available)
2024-01-11 00:20:03 [2024-01-10T16:20:03.948+00:00][INFO ][plugins.fleet] Fleet Usage: {"agents_enabled":true,"agents":{"total_enrolled":0,"healthy":0,"unhealthy":0,"offline":0,"inactive":0,"unenrolled":0,"total_all_statuses":0,"updating":0},"fleet_server":{"total_all_statuses":0,"total_enrolled":0,"healthy":0,"unhealthy":0,"offline":0,"updating":0,"num_host_urls":0}}
2024-01-11 00:20:04 [2024-01-10T16:20:04.381+00:00][WARN ][plugins.apm] Could not create index: '.apm-agent-configuration'. Retrying...
2024-01-11 00:20:04 [2024-01-10T16:20:04.382+00:00][WARN ][plugins.apm] ResponseError: resource_already_exists_exception
2024-01-11 00:20:04     Root causes:
2024-01-11 00:20:04             resource_already_exists_exception: index [.apm-agent-configuration/sB9zCdtATuylj1_vgWgY4g] already exists
2024-01-11 00:20:04     at KibanaTransport.request (/usr/share/kibana/node_modules/@elastic/transport/lib/Transport.js:479:27)
2024-01-11 00:20:04     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-01-11 00:20:04     at KibanaTransport.request (/usr/share/kibana/node_modules/@kbn/core-elasticsearch-client-server-internal/src/create_transport.js:51:16)
2024-01-11 00:20:04     at Indices.create (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/api/api/indices.js:191:16)
2024-01-11 00:20:04     at /usr/share/kibana/node_modules/@kbn/observability-plugin/server/utils/create_or_update_index.js:39:12
2024-01-11 00:20:04     at RetryOperation._fn (/usr/share/kibana/node_modules/p-retry/index.js:50:12)
```

- I can access Kibana's login page `http://localhost:5601`, but I encountered an error while logging in.
- ES cluster health api responsed `green` color.

### Steps to Reproduce

described on above.

**Comment by chaseSpace** [comment]
It seems that the `MEM_LIMIT` of `.env` file is too low. I increased it to 1GB and this problem no longer occurs.

**Comment by kingherc** [comment]
@chaseSpace this issue seems to be Kibana related. If it is still valid, please re-open in https://github.com/elastic/kibana/issues .
