### ISSUE TITLE
cat APIs can 404 due to a race condition

### ISSUE THREAD

**Issue by joegallo** [elastic/elasticsearch#104371]
This came up on a flakey test, #97809.

For both `_cat/indices` and `_cat/shards`, if you iterate on creating and deleting new indices, and separately also invoking the relevant cat APIs, you'll get a 404 sometimes unexpectedly.

Here are the commands to run:

```
while true; do index=$(openssl rand -hex 12); curl $ES_CREDS -XPUT $ES_URL/$index; echo; sleep 1; curl $ES_CREDS -XDELETE $ES_URL/$index; echo; done
```

```
 while true; do curl $ES_CREDS "$ES_URL/_cat/indices?v&error_trace"; echo; done
```

I was able to reproduce this against 7.17.x and 8.11.x, based on the code involved I think it's a problem we've had more or less forever. I'm not sure how serious I would say this is -- the cat APIs are for people of course, and if you run the command again it'll almost certainly work on the retry, but I do think it's unfortunate that we're returning an error response when we shouldn't be.

**Comment by joegallo** [comment]
Duplicating https://github.com/elastic/elasticsearch/issues/97809#issuecomment-1878960689 to this ticket:

-----

Okay, I reproduced this on a 3 node 7.17.2 cluster. Here's the stack trace:

```
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [2cac048b854d86e9e7706fa7]","index_uuid":"_na_","resource.type":"index_or_alias","resource.id":"2cac048b854d86e9e7706fa7","index":"2cac048b854d86e9e770[235/6125]
ck_trace":"[2cac048b854d86e9e7706fa7] IndexNotFoundException[no such index [2cac048b854d86e9e7706fa7]]
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.indexNotFoundException(IndexNameExpressionResolver.java:1250)
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.innerResolve(IndexNameExpressionResolver.java:1188)
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:1144)
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:292)
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:270)
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:92)
    at org.elasticsearch.action.admin.indices.settings.get.TransportGetSettingsAction.checkBlock(TransportGetSettingsAction.java:64)
    at org.elasticsearch.action.admin.indices.settings.get.TransportGetSettingsAction.checkBlock(TransportGetSettingsAction.java:31)
    at org.elasticsearch.action.support.master.TransportMasterNodeAction.checkBlockIfStateRecovered(TransportMasterNodeAction.java:138)
    at org.elasticsearch.action.support.master.TransportMasterNodeAction.access$000(TransportMasterNodeAction.java:52)
    at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:185)
    at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:158)
    at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:52)
    at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:179)
    at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:53)
    at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:177)
    at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$3(SecurityActionFilter.java:190)
    at org.elasticsearch.action.ActionListener$DelegatingFailureActionListener.onResponse(ActionListener.java:219)
    at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:577)
    at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:571)
    at org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:85)
    at org.elasticsearch.xpack.security.authz.interceptor.SearchRequestInterceptor.intercept(SearchRequestInterceptor.java:26)
    at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:575)
    at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:571)
```

I caught it by spinning up a cluster then running these two commands in different terminals: 

```
while true; do index=$(openssl rand -hex 12); curl $ES_CREDS -XPUT $ES_URL/$index; echo; sleep 1; curl $ES_CREDS -XDELETE $ES_URL/$index; echo; done
```

```
while true; do curl $ES_CREDS "$ES_URL/_cat/indices?v&error_trace"; echo; done
```

**Comment by joegallo** [comment]
Duplicating https://github.com/elastic/elasticsearch/issues/97809#issuecomment-1878971289 to this ticket:

-----

Here's a 8.11.3 stack trace -- I was hoping maybe https://github.com/elastic/elasticsearch/pull/93437 would have invalidated the circumstances where this bug happened (🤷) but no such luck.

```
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [77af693ebd14b44e71d1ddaf]","index_uuid":"_na_","resource.type":"index_or_alias","resource.id":"77af693ebd14b44e71d1ddaf","index":"77af693ebd14b44e71d1ddaf","stack_trace":"[77af693ebd14b44e71d1ddaf] org.elasticsearch.index.IndexNotFoundException: no such index [77af693ebd14b44e71d1ddaf]
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.notFoundException(IndexNameExpressionResolver.java:474)
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$ExplicitResourceNameFilter.ensureAliasOrIndexExists(IndexNameExpressionResolver.java:1604)
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$ExplicitResourceNameFilter.filterUnavailable(IndexNameExpressionResolver.java:1584)
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.resolveExpressions(IndexNameExpressionResolver.java:266)
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:341)
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:332)
    at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndexNames(IndexNameExpressionResolver.java:91)
    at org.elasticsearch.action.admin.indices.settings.get.TransportGetSettingsAction.checkBlock(TransportGetSettingsAction.java:70)
    at org.elasticsearch.action.admin.indices.settings.get.TransportGetSettingsAction.checkBlock(TransportGetSettingsAction.java:37)
    at org.elasticsearch.action.support.master.TransportMasterNodeAction.checkBlockIfStateRecovered(TransportMasterNodeAction.java:136)
    at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:201)
    at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:173)
    at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:55)
    at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:87)
    at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:53)
    at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:85)
```
