### ISSUE TITLE
[CI] CcrRollingUpgradeIT testCannotFollowLeaderInUpgradedCluster failing

### ISSUE THREAD

**Issue by edsavage** [elastic/elasticsearch#104620]
**Build scan:**
https://gradle-enterprise.elastic.co/s/s6a2urt7xmby6/tests/:x-pack:qa:rolling-upgrade-multi-cluster:v8.12.0%23follower%23upgradedClusterTest/org.elasticsearch.upgrades.CcrRollingUpgradeIT/testCannotFollowLeaderInUpgradedCluster

**Reproduction line:**
```
./gradlew ':x-pack:qa:rolling-upgrade-multi-cluster:v8.12.0#follower#upgradedClusterTest' -Dtests.class="org.elasticsearch.upgrades.CcrRollingUpgradeIT" -Dtests.method="testCannotFollowLeaderInUpgradedCluster" -Dtests.seed=77E1D53FAF91D442 -Dtests.bwc=true -Dtests.locale=zh-CN -Dtests.timezone=Europe/Paris -Druntime.java=21
```

**Applicable branches:**
8.12

**Reproduces locally?:**
Yes

**Failure history:**
[Failure dashboard for `org.elasticsearch.upgrades.CcrRollingUpgradeIT#testCannotFollowLeaderInUpgradedCluster`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testCannotFollowLeaderInUpgradedCluster'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.upgrades.CcrRollingUpgradeIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
junit.framework.AssertionFailedError: Expected exception ResponseException but no exception was thrown

  at __randomizedtesting.SeedInfo.seed([77E1D53FAF91D442:F9BE25B305B8CF59]:0)
  at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2889)
  at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2875)
  at org.elasticsearch.upgrades.CcrRollingUpgradeIT.testCannotFollowLeaderInUpgradedCluster(CcrRollingUpgradeIT.java:225)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by benwtrent** [comment]
Fixing team tag to `CCR` related tag and not search.

**Comment by idegtiarenko** [comment]
Is it same as https://github.com/elastic/elasticsearch/issues/103094 (with the same cause?)

**Comment by kingherc** [comment]
Another one at [elasticsearch / periodic / 8.12 / 8.12.0 / bwc](https://gradle-enterprise.elastic.co/s/vhg64625je5as) . Will mute.

**Comment by idegtiarenko** [comment]
I believe it another fix like https://github.com/elastic/elasticsearch/pull/103096

**Comment by thecoop** [comment]
To confirm, this failure is on main, upgrading _from_ 8.12

**Comment by thecoop** [comment]
@kingherc looks like you muted on main and 8.12, did you mean to do that?

**Comment by kingherc** [comment]
Hi @thecoop , I initially wanted to mute in 8.12 thinking it was main, without having realized the 8.13 label was out a couple of days ago. So my original PR merged in main. Then I manually muted on 8.12. But I did not take further action because I thought any bug would be in both 8.12 and main. That's not the case?

**Comment by thecoop** [comment]
This test fails on 8.12 branch, when upgrading from 8.12.0 to 8.12.1. It does not fail on main.

Is this test meant to check followers that differ only in patch versions can't update from leaders?

**Comment by kingherc** [comment]
Reading a bit testCannotFollowLeaderInUpgradedCluster, it seems that there should have been an exception due to:

```
            // At this point the leader cluster has not been upgraded, but follower cluster has been upgrade.
            // Create a leader index in the follow cluster and try to follow it in the leader cluster.
            // This should fail, because the leader cluster at this point in time can't do file based recovery from follower.
```

Reading also https://www.elastic.co/guide/en/elasticsearch/reference/current/xpack-ccr.html :

> In a uni-directional configuration, the cluster containing follower indices must be running the same or newer version of Elasticsearch as the remote cluster. If newer, the versions must also be compatible as outlined in the following matrix.

So indeed there should have been an exception. Whatever the issue (which I'm not assigned/investigating currently), it probably means main is also affected, since the bwc tests upgrade from 8.12.x -> 8.13.x (current main), right? I'm wondering whether I should unmute on main, or it's still valid to have it muted (even though we did not have an error on main -- but could be because 8.13/main is just a couple of days old).

**Comment by thecoop** [comment]
The index version on main has already been bumped, so this exception will be (correctly) hit. This implies that we need a new index version for _every single patch release_, rather than every minor release. Is that actually the case?

**Comment by kingherc** [comment]
Ah I see! I'll make a PR to unmute on main then.

@thecoop one of the test's expected exception messages comes from org.elasticsearch.snapshots.RestoreService#validateSnapshotRestorable : 

```
        if (IndexVersion.current().before(snapshotInfo.version())) {
            throw new SnapshotRestoreException(
                new Snapshot(repository.name(), snapshotInfo.snapshotId()),
                "the snapshot was created with index version ["
                    + snapshotInfo.version()
                    + "] which is higher than the version used by this node ["
                    + IndexVersion.current()
                    + "]"
            );
        }
```

The `if` was changed by you. The previous version reads:

```
        if (Version.CURRENT.before(snapshotInfo.version())) {
            throw new SnapshotRestoreException(
                new Snapshot(repository.name(), snapshotInfo.snapshotId()),
                "the snapshot was created with Elasticsearch version ["
                    + snapshotInfo.version()
                    + "] which is higher than the version of this node ["
                    + Version.CURRENT
                    + "]"
            );
        }
```

last modified by @original-brownbear .
Still seems to me that would take into account minor releases, and falls in line with the documentation, right?

**Comment by thecoop** [comment]
Yeah, it does follow that it checks patch releases too. We've had several discussions about this previously - I'll try and join these all up.

**Comment by thecoop** [comment]
@rjernst @DaveCTurner We've had discussions previously about proactively bumping index versions in order to enforce version boundaries. Could you confirm that we still want to enforce CCR leader/follower boundaries down to the release patch version, which would require a new index version for every patch release? Or do we want to consider changing it to enforce it at the minor release version boundaries only?

**Comment by DaveCTurner** [comment]
IMO we do indeed want to remain strict here. I reckon it'd be good to find a different way to enforce that than creating a new `IndexVersion` for each patch release, but that seems like a valid workaround for now.

**Comment by thecoop** [comment]
Very well.

However, there is a complexity here. 8.12 uses index version 8500008, so the new index version for 8.12.1 would be 8500009. **However**, that version has **already** been used for 8.13. So there is no space in the index version to allow 8.12.1+ to have different version numbers, to fix this test and enforce the patch version barrier.

We have updated IndexVersion to use similar numbering style as TransportVersion, to 8501000which does allow for patch versions, but that was only done _after_ 8.12 had been released.

**However**, I don't believe anything has actually changed for the recent index versions, and 8.13 hasn't been released yet, so 8500009 and 8501000 are actually identical. This means we could repurpose 8500009 for 8.12.1 (and the following numbers for 8.12.n), leaving 8.13, when it is released, on 8501000+.

I don't think this will actually change anything for serverless, as the format hasn't actually changed, and serverless knows nothing about releases.

So, to fix this:
- Re-designate version 8500009 as the version for 8.12.1, define it on 8.12.
- Leave 8.13 on 8501000. This effectively just renames the existing constants on main.

**Comment by thecoop** [comment]
This is fixed by #104754

**Comment by joegallo** [comment]
https://gradle-enterprise.elastic.co/s/cyqfyacbj6oyg

**Comment by thecoop** [comment]
Broken due to the 8.12.1 release. We're discussing this in the core/infra sync today

**Comment by iverase** [comment]
https://gradle-enterprise.elastic.co/s/yeyd7dkjbelje

**Comment by thecoop** [comment]
This test (or the code) needs to be modified due to #105295. I'll mute for now
