### ISSUE TITLE
[ELK] Elasticsearch errors when i add a scripted field in Kibana 4

### ISSUE THREAD

**Issue by Nurza** [elastic/elasticsearch#10474]
Hello, I'm using ELK with kibana 4.0.2 and elasticsearch 1.4.4 on ubuntu 14.04 and java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25).

When I want to create a scripted field (example: ```doc['status'].value+42```) the web ui displays the message: ```Discover: An error occurred with your request. Reset your inputs and try again.```

And in ```/var/log/elasticsearch/elasticsearch.log```:

```
[2015-04-08 11:59:16,294][DEBUG][action.search.type       ] [Moonstone] [logstash-2015.04.08][4], node[3hsQHmeVRo2hGHdFbiG_-Q], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@45f7b369] lastShard [true]
org.elasticsearch.search.SearchParseException: [logstash-2015.04.08][4]: query[ConstantScore(BooleanFilter(+QueryWrapperFilter(host:codemanager) +QueryWrapperFilter(ConstantScore(cache(_type:nginx))) +cache(@timestamp:[1428486256162 TO 1428487156162])))],from[-1],size[500],sort[<custom:"@timestamp": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@51d592b6>!]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"query_string":{"analyze_wildcard":true,"query":"*"}},"filter":{"bool":{"must":[{"query":{"match":{"host":{"query":"codemanager","type":"phrase"}}}},{"query":{"match":{"_type":{"query":"nginx","type":"phrase"}}}},{"range":{"@timestamp":{"gte":1428486256162,"lte":1428487156162}}}],"must_not":[]}}}},"highlight":{"pre_tags":["@kibana-highlighted-field@"],"post_tags":["@/kibana-highlighted-field@"],"fields":{"*":{}}},"size":500,"sort":{"@timestamp":"desc"},"aggs":{"2":{"date_histogram":{"field":"@timestamp","interval":"30s","pre_zone":"+02:00","pre_zone_adjust_large_interval":true,"min_doc_count":0,"extended_bounds":{"min":1428486256161,"max":1428487156161}}}},"fields":["*","_source"],"script_fields":{"lala":{"script":"doc['status'].value+42","lang":"expression"}},"fielddata_fields":["@timestamp","time"]}]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:687)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:543)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:515)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:277)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.script.expression.ExpressionScriptCompilationException: Field [status] used in expression must be numeric
	at org.elasticsearch.script.expression.ExpressionScriptEngineService.search(ExpressionScriptEngineService.java:131)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:511)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:515)
	at org.elasticsearch.search.fetch.script.ScriptFieldsParseElement.parse(ScriptFieldsParseElement.java:82)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:671)
	... 9 more
[2015-04-08 11:59:16,295][DEBUG][action.search.type       ] [Moonstone] [logstash-2015.04.08][1], node[3hsQHmeVRo2hGHdFbiG_-Q], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@45f7b369]
org.elasticsearch.search.SearchParseException: [logstash-2015.04.08][1]: query[ConstantScore(BooleanFilter(+QueryWrapperFilter(host:codemanager) +QueryWrapperFilter(ConstantScore(cache(_type:nginx))) +cache(@timestamp:[1428486256162 TO 1428487156162])))],from[-1],size[500],sort[<custom:"@timestamp": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@210e49a>!]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"query_string":{"analyze_wildcard":true,"query":"*"}},"filter":{"bool":{"must":[{"query":{"match":{"host":{"query":"codemanager","type":"phrase"}}}},{"query":{"match":{"_type":{"query":"nginx","type":"phrase"}}}},{"range":{"@timestamp":{"gte":1428486256162,"lte":1428487156162}}}],"must_not":[]}}}},"highlight":{"pre_tags":["@kibana-highlighted-field@"],"post_tags":["@/kibana-highlighted-field@"],"fields":{"*":{}}},"size":500,"sort":{"@timestamp":"desc"},"aggs":{"2":{"date_histogram":{"field":"@timestamp","interval":"30s","pre_zone":"+02:00","pre_zone_adjust_large_interval":true,"min_doc_count":0,"extended_bounds":{"min":1428486256161,"max":1428487156161}}}},"fields":["*","_source"],"script_fields":{"lala":{"script":"doc['status'].value+42","lang":"expression"}},"fielddata_fields":["@timestamp","time"]}]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:687)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:543)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:515)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:277)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.script.expression.ExpressionScriptCompilationException: Field [status] used in expression must be numeric
	at org.elasticsearch.script.expression.ExpressionScriptEngineService.search(ExpressionScriptEngineService.java:131)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:511)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:515)
	at org.elasticsearch.search.fetch.script.ScriptFieldsParseElement.parse(ScriptFieldsParseElement.java:82)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:671)
	... 9 more
[2015-04-08 11:59:16,295][DEBUG][action.search.type       ] [Moonstone] All shards failed for phase: [query]
[2015-04-08 11:59:16,296][DEBUG][action.search.type       ] [Moonstone] [logstash-2015.04.08][3], node[3hsQHmeVRo2hGHdFbiG_-Q], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@45f7b369] lastShard [true]
org.elasticsearch.search.SearchParseException: [logstash-2015.04.08][3]: query[ConstantScore(BooleanFilter(+QueryWrapperFilter(host:codemanager) +QueryWrapperFilter(ConstantScore(cache(_type:nginx))) +cache(@timestamp:[1428486256162 TO 1428487156162])))],from[-1],size[500],sort[<custom:"@timestamp": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@1598a69f>!]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"query_string":{"analyze_wildcard":true,"query":"*"}},"filter":{"bool":{"must":[{"query":{"match":{"host":{"query":"codemanager","type":"phrase"}}}},{"query":{"match":{"_type":{"query":"nginx","type":"phrase"}}}},{"range":{"@timestamp":{"gte":1428486256162,"lte":1428487156162}}}],"must_not":[]}}}},"highlight":{"pre_tags":["@kibana-highlighted-field@"],"post_tags":["@/kibana-highlighted-field@"],"fields":{"*":{}}},"size":500,"sort":{"@timestamp":"desc"},"aggs":{"2":{"date_histogram":{"field":"@timestamp","interval":"30s","pre_zone":"+02:00","pre_zone_adjust_large_interval":true,"min_doc_count":0,"extended_bounds":{"min":1428486256161,"max":1428487156161}}}},"fields":["*","_source"],"script_fields":{"lala":{"script":"doc['status'].value+42","lang":"expression"}},"fielddata_fields":["@timestamp","time"]}]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:687)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:543)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:515)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:277)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.script.expression.ExpressionScriptCompilationException: Field [status] used in expression must be numeric
	at org.elasticsearch.script.expression.ExpressionScriptEngineService.search(ExpressionScriptEngineService.java:131)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:511)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:515)
	at org.elasticsearch.search.fetch.script.ScriptFieldsParseElement.parse(ScriptFieldsParseElement.java:82)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:671)
	... 9 more
[2015-04-08 11:59:16,295][DEBUG][action.search.type       ] [Moonstone] [logstash-2015.04.08][2], node[3hsQHmeVRo2hGHdFbiG_-Q], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@45f7b369] lastShard [true]
org.elasticsearch.search.SearchParseException: [logstash-2015.04.08][2]: query[ConstantScore(BooleanFilter(+QueryWrapperFilter(host:codemanager) +QueryWrapperFilter(ConstantScore(cache(_type:nginx))) +cache(@timestamp:[1428486256162 TO 1428487156162])))],from[-1],size[500],sort[<custom:"@timestamp": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@7d035eda>!]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"query_string":{"analyze_wildcard":true,"query":"*"}},"filter":{"bool":{"must":[{"query":{"match":{"host":{"query":"codemanager","type":"phrase"}}}},{"query":{"match":{"_type":{"query":"nginx","type":"phrase"}}}},{"range":{"@timestamp":{"gte":1428486256162,"lte":1428487156162}}}],"must_not":[]}}}},"highlight":{"pre_tags":["@kibana-highlighted-field@"],"post_tags":["@/kibana-highlighted-field@"],"fields":{"*":{}}},"size":500,"sort":{"@timestamp":"desc"},"aggs":{"2":{"date_histogram":{"field":"@timestamp","interval":"30s","pre_zone":"+02:00","pre_zone_adjust_large_interval":true,"min_doc_count":0,"extended_bounds":{"min":1428486256161,"max":1428487156161}}}},"fields":["*","_source"],"script_fields":{"lala":{"script":"doc['status'].value+42","lang":"expression"}},"fielddata_fields":["@timestamp","time"]}]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:687)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:543)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:515)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:277)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.script.expression.ExpressionScriptCompilationException: Field [status] used in expression must be numeric
	at org.elasticsearch.script.expression.ExpressionScriptEngineService.search(ExpressionScriptEngineService.java:131)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:511)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:515)
	at org.elasticsearch.search.fetch.script.ScriptFieldsParseElement.parse(ScriptFieldsParseElement.java:82)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:671)
	... 9 more
[2015-04-08 11:59:16,296][DEBUG][action.search.type       ] [Moonstone] [logstash-2015.04.08][0], node[3hsQHmeVRo2hGHdFbiG_-Q], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@45f7b369] lastShard [true]
org.elasticsearch.search.SearchParseException: [logstash-2015.04.08][0]: query[ConstantScore(BooleanFilter(+QueryWrapperFilter(host:codemanager) +QueryWrapperFilter(ConstantScore(cache(_type:nginx))) +cache(@timestamp:[1428486256162 TO 1428487156162])))],from[-1],size[500],sort[<custom:"@timestamp": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@3ce90bce>!]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"query_string":{"analyze_wildcard":true,"query":"*"}},"filter":{"bool":{"must":[{"query":{"match":{"host":{"query":"codemanager","type":"phrase"}}}},{"query":{"match":{"_type":{"query":"nginx","type":"phrase"}}}},{"range":{"@timestamp":{"gte":1428486256162,"lte":1428487156162}}}],"must_not":[]}}}},"highlight":{"pre_tags":["@kibana-highlighted-field@"],"post_tags":["@/kibana-highlighted-field@"],"fields":{"*":{}}},"size":500,"sort":{"@timestamp":"desc"},"aggs":{"2":{"date_histogram":{"field":"@timestamp","interval":"30s","pre_zone":"+02:00","pre_zone_adjust_large_interval":true,"min_doc_count":0,"extended_bounds":{"min":1428486256161,"max":1428487156161}}}},"fields":["*","_source"],"script_fields":{"lala":{"script":"doc['status'].value+42","lang":"expression"}},"fielddata_fields":["@timestamp","time"]}]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:687)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:543)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:515)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:277)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.script.expression.ExpressionScriptCompilationException: Field [status] used in expression must be numeric
	at org.elasticsearch.script.expression.ExpressionScriptEngineService.search(ExpressionScriptEngineService.java:131)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:511)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:515)
	at org.elasticsearch.search.fetch.script.ScriptFieldsParseElement.parse(ScriptFieldsParseElement.java:82)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:671)
	... 9 more
```

What can I do please?

**Comment by clintongormley** [comment]
Hi @Nurza 

Please ask questions like these on the mailing list.  By default, the only scripting language enabled for dynamic scripts is "expressions", which doesn't handle non-numeric fields.  If you want to use groovy, you'll have to store your scripts in a file on the server.
