### ISSUE TITLE
[CI] SearchableSnapshotActionIT testConvertingSearchableSnapshotFromFullToPartial failing

### ISSUE THREAD

**Issue by jan-elastic** [elastic/elasticsearch#104846]
**Build scan:**
https://gradle-enterprise.elastic.co/s/2ljfeke4dock4/tests/:x-pack:plugin:ilm:qa:multi-node:javaRestTest/org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT/testConvertingSearchableSnapshotFromFullToPartial

**Reproduction line:**
```
./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testConvertingSearchableSnapshotFromFullToPartial" -Dtests.seed=2E0F1CB799FDC648 -Dtests.locale=en-NZ -Dtests.timezone=Europe/Sofia -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT#testConvertingSearchableSnapshotFromFullToPartial`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testConvertingSearchableSnapshotFromFullToPartial'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [DELETE], host [http://[::1]:43607], URI [restored-myindex-tppj], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The provided expression [restored-myindex-tppj] matches an alias, specify the corresponding concrete indices instead."}],"type":"illegal_argument_exception","reason":"The provided expression [restored-myindex-tppj] matches an alias, specify the corresponding concrete indices instead."},"status":400}

  at __randomizedtesting.SeedInfo.seed([2E0F1CB799FDC648:7DEA37C67F7EB66F]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:351)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:317)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:292)
  at org.elasticsearch.test.rest.ESRestTestCase.wipeSearchableSnapshotsIndices(ESRestTestCase.java:1089)
  at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:764)
  at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:470)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by gmarouli** [comment]
So this is a bit weird. The deletion fails because `restored-myindex-tppj` is an alias and not a concrete searchable snapshot which matches what the test `testConvertingSearchableSnapshotFromFullToPartial` is expecting, see the last assertion of the test:
```
assertTrue(
     "Expecting the mounted index to be deleted and to be converted to an alias",
      aliasExists(searchableSnapMountedIndexName, SearchableSnapshotAction.FULL_RESTORED_INDEX_PREFIX + index)
)
```

When I run it locally the tear down of the test correctly uses the index name `partial-restored-myindex-tppj` to delete the index.

It appears that in this case the following code received a outdated response (?) but I am not sure how that could be possible yet:
```
        final Request request = new Request("GET", "_cluster/state/metadata");
        request.addParameter("filter_path", "metadata.indices.*.settings.index.store.snapshot");

        final Response response = adminClient().performRequest(request);
        @SuppressWarnings("unchecked")
        Map<String, ?> indices = (Map<String, ?>) XContentMapValues.extractValue("metadata.indices", entityAsMap(response));
```

**Comment by gmarouli** [comment]
Considering the message above, it feels to me that this is an inconsistency between cluster states. This test has had 3 failures in the last 6 months:
- 25/11/2023
- 24/12/2023
- 26/01/2024

 So, I have been trying to figure out how this could happen, to help myself I wrote the timeline below:

This is the timeline:
- The assertion in the test, confirms that there is an alias `restored-myindex-tppj`. GetAliases is a local action since https://github.com/elastic/elasticsearch/pull/101815 (Novemeber 6th 2023). **So by this time, `restored-myindex-tppj` is already an alias.**
- We get the cluster state from `GET _cluster/state/metadata`, this is a `TransportMasterNodeReadAction`, so it should have the latest data. It doesn't provide the local query param, so by default it's false.

I have not yet an idea how could this happen. I expect that since `restored-myindex-tppj` is an alias, it is a requirement that it has been deleted first.

**Comment by DaveCTurner** [comment]
> We get the cluster state from GET _cluster/state/metadata, this is a TransportMasterNodeReadAction, so it should have the latest data.

That doesn't follow. It gets the _last-applied state_ according to the master, but other nodes may have applied a later state by this point. Perhaps try inserting a `GET _cluster/health?wait_for_events=languid` to ensure that all prior cluster state updates are complete.

I could believe #101815 has disturbed some timing in this area by making the get-aliases action run faster and/or on a different node, but it won't be the root cause.

**Comment by gmarouli** [comment]
> > We get the cluster state from GET _cluster/state/metadata, this is a TransportMasterNodeReadAction, so it should have the latest data.
> 
> That doesn't follow. It gets the _last-applied state_ according to the master, but other nodes may have applied a later state by this point. Perhaps try inserting a `GET _cluster/health?wait_for_events=languid` to ensure that all prior cluster state updates are complete.
> 
> I could believe #101815 has disturbed some timing in this area by making the get-aliases action run faster and/or on a different node, but it won't be the root cause.

Thank you @DaveCTurner
