### ISSUE TITLE
Occasionally, the following errors occur when using collapse

### ISSUE THREAD

**Issue by yangruijing90** [elastic/elasticsearch#104961]
### Elasticsearch Version

7.8.1

### Java Version

_bundled_

### OS Version

linux

### Problem Description

DSL:
GET test_index/_search
{ 
  "from": 0,
  "size": 10,
  "track_total_hits": true,
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "createtime": {
              "from": "2023-11-01",
              "to": "2024-01-31"
            }
          }
        }
      ]
    }
  },
  "_source": false,
  "sort": [
    {
      "createtime": {
        "order": "desc"
      }
    }
  ],
  "collapse": {
    "field": "courseid"
  }
}

### Steps to Reproduce

courseid  type is long 

### Logs (if relevant)

org.elasticsearch.action.search.SearchPhaseExecutionException: 
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:551) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.action.search.FetchSearchPhase$1.onFailure(FetchSearchPhase.java:100) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:695) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.8.1.jar:7.8.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.UnsupportedOperationException
        at java.util.AbstractList.add(AbstractList.java:153) ~[?:?]
        at java.util.AbstractList$SubList.add(AbstractList.java:797) ~[?:?]
        at java.util.AbstractList.add(AbstractList.java:111) ~[?:?]
        at org.elasticsearch.action.search.SearchPhaseController.sortDocs(SearchPhaseController.java:180) ~[elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:521) ~[elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.action.search.SearchPhaseController.access$200(SearchPhaseController.java:76) ~[elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.action.search.SearchPhaseController$QueryPhaseResultConsumer.reduce(SearchPhaseController.java:757) ~[elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:116) ~[elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:47) ~[elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:95) ~[elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.8.1.jar:7.8.1]
        ... 6 more
```[tasklist]
### Tasks
```

**Comment by yangruijing90** [comment]
org.elasticsearch.action.search.SearchPhaseExecutionException: 
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:551) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.action.search.FetchSearchPhase$1.onFailure(FetchSearchPhase.java:100) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:695) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.8.1.jar:7.8.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ArrayStoreException: org.apache.lucene.search.TopFieldDocs
        at java.util.AbstractCollection.toArray(AbstractCollection.java:202) ~[?:?]
        at org.elasticsearch.action.search.SearchPhaseController.mergeTopDocs(SearchPhaseController.java:240) ~[elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.action.search.SearchPhaseController.sortDocs(SearchPhaseController.java:186) ~[elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:521) ~[elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.action.search.SearchPhaseController.access$200(SearchPhaseController.java:76) ~[elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.action.search.SearchPhaseController$QueryPhaseResultConsumer.reduce(SearchPhaseController.java:757) ~[elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:116) ~[elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:47) ~[elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:95) ~[elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.8.1.jar:7.8.1]

**Comment by DaveCTurner** [comment]
Thank you very much for your interest in Elasticsearch. Unfortunately the issue you have reported relates to Elasticsearch version 7.8.1 which is very old and has passed [end-of-life](https://www.elastic.co/support/eol). We will not investigate issues related to unsupported versions here on Github, so I am closing this to indicate that no action is needed from the Elasticsearch development team. It's possible that you will find a volunteer to help you with this issue on the [community forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6), but our strong recommendation would be to upgrade to a supported version of Elasticsearch as a matter of some urgency. If you can reproduce your issue on a supported version then please open a fresh bug report.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.
