### ISSUE TITLE
[CI] SharedBlobCacheServiceTests testGetMultiThreaded failing

### ISSUE THREAD

**Issue by DiannaHohensee** [elastic/elasticsearch#104997]
### CI Link

https://gradle-enterprise.elastic.co/s/y2wty2aknyshk/tests/task/:x-pack:plugin:blob-cache:test/details/org.elasticsearch.blobcache.shared.SharedBlobCacheServiceTests/testGetMultiThreaded?top-execution=1

### Repro line
```
./gradlew ':x-pack:plugin:blob-cache:test' --tests "org.elasticsearch.blobcache.shared.SharedBlobCacheServiceTests.testGetMultiThreaded" -Dtests.seed=CB78B9BD805285EB -Dtests.locale=es-CO -Dtests.timezone=America/Cancun -Druntime.java=21
```
### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure excerpt

```
java.lang.AssertionError: org.apache.lucene.store.AlreadyClosedException: no free region found
at __randomizedtesting.SeedInfo.seed([CB78B9BD805285EB]:0)
at org.elasticsearch.blobcache.shared.SharedBlobCacheServiceTests.lambda$testGetMultiThreaded$14(SharedBlobCacheServiceTests.java:466)
at java.lang.Thread.run(Thread.java:1583)


  | Caused by: org.apache.lucene.store.AlreadyClosedException: no free region found
  |   | at org.elasticsearch.blobcache.shared.SharedBlobCacheService.throwAlreadyClosed(SharedBlobCacheService.java:580)  | 
  |   | at org.elasticsearch.blobcache.shared.SharedBlobCacheService$LFUCache.initChunk(SharedBlobCacheService.java:1291) |  
  |   | at org.elasticsearch.blobcache.shared.SharedBlobCacheService$LFUCache.get(SharedBlobCacheService.java:1219) |  
  |   | at org.elasticsearch.blobcache.shared.SharedBlobCacheService$LFUCache.get(SharedBlobCacheService.java:1154) |  
  |   | at org.elasticsearch.blobcache.shared.SharedBlobCacheService.get(SharedBlobCacheService.java:458) |  
  |   | at org.elasticsearch.blobcache.shared.SharedBlobCacheServiceTests.lambda$testGetMultiThreaded$14(SharedBlobCacheServiceTests.java:464) |  
  |   | at java.lang.Thread.run(Thread.java:1583) |  
```

```

[2024-01-31T16:37:10,449][INFO ][o.e.b.s.SharedBlobCacheServiceTests] [testGetMultiThreaded] before test |  
-- | --
  | [2024-01-31T16:37:10,490][INFO ][o.e.e.NodeEnvironment    ] [testGetMultiThreaded] using [1] data paths, mounts [[/opt/local-ssd (/dev/nvme0n1)]], net usable_space [318.8gb], net total_space [368gb], types [ext4] |  
  | [2024-01-31T16:37:10,497][INFO ][o.e.e.NodeEnvironment    ] [testGetMultiThreaded] heap size [512mb], compressed ordinary object pointers [true] |  
  | [2024-01-31T16:37:10,520][INFO ][o.e.p.Preallocate        ] [testGetMultiThreaded] pre-allocating cache file [/opt/local-ssd/buildkite/builds/bk-agent-prod-gcp-1706734902520139651/elastic/elasticsearch-periodic-platform-support/x-pack/plugin/blob-cache/build/testrun/test/temp/org.elasticsearch.blobcache.shared.SharedBlobCacheServiceTests_CB78B9BD805285EB-001/tempDir-009/data/shared_snapshot_cache] (3686400 bytes) using native methods |  
  | [2024-01-31T16:37:10,521][WARN ][o.e.p.Preallocate        ] [testGetMultiThreaded] failed to pre-allocate cache file [/opt/local-ssd/buildkite/builds/bk-agent-prod-gcp-1706734902520139651/elastic/elasticsearch-periodic-platform-support/x-pack/plugin/blob-cache/build/testrun/test/temp/org.elasticsearch.blobcache.shared.SharedBlobCacheServiceTests_CB78B9BD805285EB-001/tempDir-009/data/shared_snapshot_cache] using native methods |  
  | java.lang.reflect.InaccessibleObjectException: Unable to make field private int java.io.FileDescriptor.fd accessible: module java.base does not "opens java.io" to unnamed module @515aebb0 |  
  | at java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391) ~[?:?] |  
  | at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367) ~[?:?] |  
  | at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315) ~[?:?] |  
  | at java.lang.reflect.Field.checkCanSetAccessible(Field.java:183) ~[?:?] |  
  | at java.lang.reflect.Field.setAccessible(Field.java:177) ~[?:?] |  
  | at org.elasticsearch.preallocate.Preallocate$FileDescriptorFieldAction.run(Preallocate.java:110) ~[elasticsearch-preallocate-8.13.0-SNAPSHOT.jar:8.13.0-SNAPSHOT] |  
  | at org.elasticsearch.preallocate.Preallocate$FileDescriptorFieldAction.run(Preallocate.java:96) ~[elasticsearch-preallocate-8.13.0-SNAPSHOT.jar:8.13.0-SNAPSHOT] |  
  | at java.security.AccessController.doPrivileged(AccessController.java:571) ~[?:?] |  
  | at org.elasticsearch.preallocate.Preallocate.preallocate(Preallocate.java:54) ~[elasticsearch-preallocate-8.13.0-SNAPSHOT.jar:8.13.0-SNAPSHOT] |  
  | at org.elasticsearch.preallocate.Preallocate.preallocate(Preallocate.java:37) ~[elasticsearch-preallocate-8.13.0-SNAPSHOT.jar:8.13.0-SNAPSHOT] |  
  | at org.elasticsearch.blobcache.shared.SharedBytes.<init>(SharedBytes.java:80) ~[main/:?] |  
  | at org.elasticsearch.blobcache.shared.SharedBlobCacheService.<init>(SharedBlobCacheService.java:371) ~[main/:?] |  
  | at org.elasticsearch.blobcache.shared.SharedBlobCacheService.<init>(SharedBlobCacheService.java:333) ~[main/:?] |  
  | at org.elasticsearch.blobcache.shared.SharedBlobCacheServiceTests.testGetMultiThreaded(SharedBlobCacheServiceTests.java:442) ~[test/:?] |  
  | at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] |  
  | at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at org.junit.rules.RunRules.evaluate(RunRules.java:20) ~[junit-4.13.2.jar:4.13.2] |  
  | at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48) ~[lucene-test-framework-9.9.2.jar:9.9.2 a2939784c4ca60bc28bf488b5479c02fc2e5e22c - 2024-01-25 09:51:09] |  
  | at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43) ~[lucene-test-framework-9.9.2.jar:9.9.2 a2939784c4ca60bc28bf488b5479c02fc2e5e22c - 2024-01-25 09:51:09] |  
  | at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45) ~[lucene-test-framework-9.9.2.jar:9.9.2 a2939784c4ca60bc28bf488b5479c02fc2e5e22c - 2024-01-25 09:51:09] |  
  | at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60) ~[lucene-test-framework-9.9.2.jar:9.9.2 a2939784c4ca60bc28bf488b5479c02fc2e5e22c - 2024-01-25 09:51:09] |  
  | at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44) ~[lucene-test-framework-9.9.2.jar:9.9.2 a2939784c4ca60bc28bf488b5479c02fc2e5e22c - 2024-01-25 09:51:09] |  
  | at org.junit.rules.RunRules.evaluate(RunRules.java:20) ~[junit-4.13.2.jar:4.13.2] |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43) ~[lucene-test-framework-9.9.2.jar:9.9.2 a2939784c4ca60bc28bf488b5479c02fc2e5e22c - 2024-01-25 09:51:09] |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38) ~[lucene-test-framework-9.9.2.jar:9.9.2 a2939784c4ca60bc28bf488b5479c02fc2e5e22c - 2024-01-25 09:51:09] |  
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53) ~[lucene-test-framework-9.9.2.jar:9.9.2 a2939784c4ca60bc28bf488b5479c02fc2e5e22c - 2024-01-25 09:51:09] |  
  | at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43) ~[lucene-test-framework-9.9.2.jar:9.9.2 a2939784c4ca60bc28bf488b5479c02fc2e5e22c - 2024-01-25 09:51:09] |  
  | at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44) ~[lucene-test-framework-9.9.2.jar:9.9.2 a2939784c4ca60bc28bf488b5479c02fc2e5e22c - 2024-01-25 09:51:09] |  
  | at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60) ~[lucene-test-framework-9.9.2.jar:9.9.2 a2939784c4ca60bc28bf488b5479c02fc2e5e22c - 2024-01-25 09:51:09] |  
  | at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47) ~[lucene-test-framework-9.9.2.jar:9.9.2 a2939784c4ca60bc28bf488b5479c02fc2e5e22c - 2024-01-25 09:51:09] |  
  | at org.junit.rules.RunRules.evaluate(RunRules.java:20) ~[junit-4.13.2.jar:4.13.2] |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850) ~[randomizedtesting-runner-2.8.0.jar:?] |  
  | at java.lang.Thread.run(Thread.java:1583) ~[?:?] |  
  | [2024-01-31T16:37:10,533][INFO ][o.e.p.Preallocate        ] [testGetMultiThreaded] pre-allocating cache file [/opt/local-ssd/buildkite/builds/bk-agent-prod-gcp-1706734902520139651/elastic/elasticsearch-periodic-platform-support/x-pack/plugin/blob-cache/build/testrun/test/temp/org.elasticsearch.blobcache.shared.SharedBlobCacheServiceTests_CB78B9BD805285EB-001/tempDir-009/data/shared_snapshot_cache] (3686400 bytes) using setLength method |  
  | ene 31, 2024 4:37:10 PM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException |  
  | WARNING: Uncaught exception in thread: Thread[#82,Thread-16,5,TGRP-SharedBlobCacheServiceTests] |  
  | java.lang.AssertionError: org.apache.lucene.store.AlreadyClosedException: no free region found |  
  | at __randomizedtesting.SeedInfo.seed([CB78B9BD805285EB]:0) |  
  | at org.elasticsearch.blobcache.shared.SharedBlobCacheServiceTests.lambda$testGetMultiThreaded$14(SharedBlobCacheServiceTests.java:466) |  
  | at java.base/java.lang.Thread.run(Thread.java:1583) |  
  | Caused by: org.apache.lucene.store.AlreadyClosedException: no free region found |  
  | at org.elasticsearch.blobcache.shared.SharedBlobCacheService.throwAlreadyClosed(SharedBlobCacheService.java:580) |  
  | at org.elasticsearch.blobcache.shared.SharedBlobCacheService$LFUCache.initChunk(SharedBlobCacheService.java:1291) |  
  | at org.elasticsearch.blobcache.shared.SharedBlobCacheService$LFUCache.get(SharedBlobCacheService.java:1219) |  
  | at org.elasticsearch.blobcache.shared.SharedBlobCacheService$LFUCache.get(SharedBlobCacheService.java:1154) |  
  | at org.elasticsearch.blobcache.shared.SharedBlobCacheService.get(SharedBlobCacheService.java:458) |  
  | at org.elasticsearch.blobcache.shared.SharedBlobCacheServiceTests.lambda$testGetMultiThreaded$14(SharedBlobCacheServiceTests.java:464) |  
  | ... 1 more |  
  |   |  
  | [2024-01-31T16:37:10,662][INFO ][o.e.b.s.SharedBlobCacheServiceTests] [testGetMultiThreaded] after test
```

**Comment by DiannaHohensee** [comment]
Might be related to https://github.com/elastic/elasticsearch/commit/f2d96442f643108b4d9e35e4193a35730cd2a201, which modified the test a couple days ago. @henningandersen @tlrx FYI
