### ISSUE TITLE
Downsample task doesn't clear the `STARTED` status when failed/cancelled

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#105068]
### Elasticsearch Version

8.12, 8.13 onwards 

### Java Version

_bundled_

### OS Version

Darwin

### Problem Description

During a cluster rolling restart the downsample persistent task might be cancelled. 
When this happens we'd want the status of the source index to be changed from `STARTED` to `UNKNOW` (or `ERROR` once https://github.com/elastic/elasticsearch/issues/98875 is implemented).

Currently it remains in `STARTED` and services like DSL continue to wait for downsampling to finish (instead of re-kicking the operation)

We would see a sequence like this 
```
[2024-02-02T06:37:01,513][ERROR][o.e.x.d.DownsampleShardIndexer] [node_t3] Shard [[.ds-metrics-foo-2024.02.02-000001][0]] failed to populate downsample index. Failures: [{null=org.elasticsearch.node.NodeClosedException: node closed {node_t3}{hHb78IPvT6GZLupyj2WcBw}{b6D6imYbRGe2On2DLSH_UA}{node_t3}{127.0.0.1}{127.0.0.1:13363}{d}{8.13.0}{7000099-8502001}{xpack.installed=true}}]
[2024-02-02T06:37:01,525][ERROR][o.e.x.d.DownsampleShardIndexer] [node_t3] Shard [[.ds-metrics-foo-2024.02.02-000001][0]] failed to populate downsample index. Failures: [{null=org.elasticsearch.node.NodeClosedException: node closed {node_t3}{hHb78IPvT6GZLupyj2WcBw}{b6D6imYbRGe2On2DLSH_UA}{node_t3}{127.0.0.1}{127.0.0.1:13363}{d}{8.13.0}{7000099-8502001}{xpack.installed=true}}]
[2024-02-02T06:37:01,552][ERROR][o.e.x.d.DownsampleShardIndexer] [node_t3] Shard [[.ds-metrics-foo-2024.02.02-000001][0]] failed to populate downsample index. Failures: [{null=org.elasticsearch.node.NodeClosedException: node closed {node_t3}{hHb78IPvT6GZLupyj2WcBw}{b6D6imYbRGe2On2DLSH_UA}{node_t3}{127.0.0.1}{127.0.0.1:13363}{d}{8.13.0}{7000099-8502001}{xpack.installed=true}}]
[2024-02-02T06:37:01,562][ERROR][o.e.x.d.DownsampleShardIndexer] [node_t3] Shard [[.ds-metrics-foo-2024.02.02-000001][0]] failed to populate downsample index. Failures: [{null=org.elasticsearch.node.NodeClosedException: node closed {node_t3}{hHb78IPvT6GZLupyj2WcBw}{b6D6imYbRGe2On2DLSH_UA}{node_t3}{127.0.0.1}{127.0.0.1:13363}{d}{8.13.0}{7000099-8502001}{xpack.installed=true}}]
[2024-02-02T06:37:01,584][ERROR][o.e.x.d.DownsampleShardIndexer] [node_t3] Shard [[.ds-metrics-foo-2024.02.02-000001][0]] failed to populate downsample index. Failures: [{null=org.elasticsearch.node.NodeClosedException: node closed {node_t3}{hHb78IPvT6GZLupyj2WcBw}{b6D6imYbRGe2On2DLSH_UA}{node_t3}{127.0.0.1}{127.0.0.1:13363}{d}{8.13.0}{7000099-8502001}{xpack.installed=true}}]
[2024-02-02T06:37:01,601][ERROR][o.e.x.d.DownsampleShardPersistentTaskExecutor] [node_t3] Downsampling task [downsample-downsample-5m-.ds-metrics-foo-2024.02.02-000001-0-5m non retriable failure [Shard [.ds-metrics-foo-2024.02.02-000001][0] downsample cancelled]
[2024-02-02T06:37:01,603][WARN ][o.e.p.AllocatedPersistentTask] [node_t3] task [downsample-downsample-5m-.ds-metrics-foo-2024.02.02-000001-0-5m] failed with an exception
org.elasticsearch.xpack.downsample.DownsampleShardIndexerException: Shard [.ds-metrics-foo-2024.02.02-000001][0] downsample cancelled
	at org.elasticsearch.xpack.downsample.DownsampleShardIndexer.checkCancelled(DownsampleShardIndexer.java:238) ~[main/:?]
	at org.elasticsearch.search.aggregations.support.TimeSeriesIndexSearcher.checkCancelled(TimeSeriesIndexSearcher.java:231) ~[elasticsearch-8.13.0-SNAPSHOT.jar:8.13.0-SNAPSHOT]
```

```
org.elasticsearch.xpack.downsample.DownsampleShardIndexerException: Shard [.ds-metrics-foo-2024.02.02-000001][0] downsample cancelled
...
Caused by: org.elasticsearch.tasks.TaskCancelledException: Shard [.ds-metrics-foo-2024.02.02-000001][0] downsample cancelled
	at org.elasticsearch.xpack.downsample.DownsampleShardIndexer.checkCancelled(DownsampleShardIndexer.java:237) ~[main/:?]
	... 10 more
```

And DSL would idle forever in 
```
Data stream lifecycle service waits for index [.ds-metrics-foo-2024.02.02-000001] to be downsampled. Current status is [started] and the downsample index name is [downsample-5m-.ds-metrics-foo-2024.02.02-000001]
```

### Steps to Reproduce

Unmute and repeatedly run `org.elasticsearch.xpack.downsample.DataStreamLifecycleDownsampleDisruptionIT/testDataStreamLifecycleDownsampleRollingRestart`

Build scan: https://gradle-enterprise.elastic.co/s/oik4alu6vadqs

**Comment by kkrik-es** [comment]
I got another error, I think:

```
java.lang.AssertionError: 
    Expected: is <success>
         but: was <started>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2119)
        at org.elasticsearch.xpack.downsample.DataStreamLifecycleDownsampleDisruptionIT.lambda$testDataStreamLifecycleDownsampleRollingRestart$2(DataStreamLifecycleDownsampleDisruptionIT.java:141)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1255)
        at org.elasticsearch.xpack.downsample.DataStreamLifecycleDownsampleDisruptionIT.testDataStreamLifecycleDownsampleRollingRestart(DataStreamLifecycleDownsampleDisruptionIT.java:132)
```

The logs contain the following repeated message:

```
[2024-02-06T01:12:22,677][TRACE][o.e.d.l.DataStreamLifecycleService] [testDataStreamLifecycleDownsampleRollingRestart] Data stream lifecycle encountered an error trying to downsample index [.ds-metrics-foo-2024.02.06-000001]. Data stream lifecycle will attempt to downsample the index on its next run.
```

**Comment by kkrik-es** [comment]
This seems relevant:

```
[2024-02-06T03:22:04,568][WARN ][o.e.p.AllocatedPersistentTask] [node_t3] task [downsample-downsample-5m-.ds-metrics-foo-2024.02.06-000001-0-5m] failed with an exception
java.lang.NullPointerException: Cannot invoke "org.elasticsearch.common.document.DocumentField.getValue()" because the return value of "org.elasticsearch.search.SearchHit.field(String)" is null
	at org.elasticsearch.xpack.downsample.DownsampleShardPersistentTaskExecutor$1.doRun(DownsampleShardPersistentTaskExecutor.java:192) ~[main/:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984) ~[elasticsearch-8.13.0-SNAPSHOT.jar:8.13.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.13.0-SNAPSHOT.jar:8.13.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by kkrik-es** [comment]
In failed runs, there's only a single downsampling task that errors out:

```
Downsampling task [downsample-downsample-5m-.ds-metrics-foo-2024.02.06-000001-0-5m on shard [.ds-metrics-foo-2024.02.06-000001][0] started
...
[2024-02-06T03:22:04,405][INFO ][o.e.x.d.DownsampleShardIndexer] [node_t3] Downsampling task [downsample-downsample-5m-.ds-metrics-foo-2024.02.06-000001-0-5m] on shard [.ds-metrics-foo-2024.02.06-000001][0] failed indexing [17025]
[2024-02-06T03:22:04,405][ERROR][o.e.x.d.DownsampleShardPersistentTaskExecutor] [node_t3] Downsampling task [downsample-downsample-5m-.ds-metrics-foo-2024.02.06-000001-0-5m non retriable failure [Downsampling task [downsample-downsample-5m-.ds-metrics-foo-2024.02.06-000001-0-5m] on shard [.ds-metrics-foo-2024.02.06-000001][0] failed indexing [17025]]
```

On successful runs, a second downsampling task is started and succeeds:

```
[2024-02-06T05:44:47,089][INFO ][o.e.x.d.DownsampleShardIndexer] [node_t3] Downsampling task [downsample-downsample-5m-.ds-metrics-foo-2024.02.06-000001-0-5m on shard [.ds-metrics-foo-2024.02.06-000001][0] started
...
[2024-02-06T05:44:48,820][INFO ][o.e.x.d.DownsampleShardIndexer] [node_t3] Downsampling task [downsample-downsample-5m-.ds-metrics-foo-2024.02.06-000001-0-5m] on shard [.ds-metrics-foo-2024.02.06-000001][0] failed indexing [10430]
[2024-02-06T05:44:48,820][ERROR][o.e.x.d.DownsampleShardPersistentTaskExecutor] [node_t3] Downsampling task [downsample-downsample-5m-.ds-metrics-foo-2024.02.06-000001-0-5m non retriable failure [Downsampling task [downsample-downsample-5m-.ds-metrics-foo-2024.02.06-000001-0-5m] on shard [.ds-metrics-foo-2024.02.06-000001][0] failed indexing [10430]]
...
[2024-02-06T05:44:48,957][ERROR][o.e.x.d.DownsampleShardPersistentTaskExecutor] [node_t3] Downsampling task [downsample-downsample-5m-.ds-metrics-foo-2024.02.06-000001-0-5m non-retriable failure [Cannot invoke "org.elasticsearch.index.IndexService.getShard(int)" because "indexService" is null]
...
[2024-02-06T05:44:49,508][INFO ][o.e.x.d.DownsampleShardIndexer] [node_t3] Downsampling task [downsample-downsample-5m-.ds-metrics-foo-2024.02.06-000001-0-5m on shard [.ds-metrics-foo-2024.02.06-000001][0] started
...
[2024-02-06T05:44:50,826][INFO ][o.e.x.d.DownsampleShardIndexer] [node_t3] Downsampling task [downsample-downsample-5m-.ds-metrics-foo-2024.02.06-000001-0-5m on shard [.ds-metrics-foo-2024.02.06-000001][0] completed
```

Not sure why no retry task gets created in the failure scenario.

**Comment by kkrik-es** [comment]
I see the following in the failure scenario:

```
[2024-02-06T06:17:20,324][INFO ][o.e.d.l.DataStreamLifecycleService] [node_t0] Data stream lifecycle issuing request to downsample index [.ds-metrics-foo-2024.02.06-000001] to index [downsample-5m-.ds-metrics-foo-2024.02.06-000001]
...
[2024-02-06T06:17:20,424][INFO ][o.e.x.d.TransportDownsampleAction] [node_t0] Task [downsample-downsample-5m-.ds-metrics-foo-2024.02.06-000001-0-5m] already exists. Waiting.
```

This may indicate that there's a duplicate task in the master that gets never reset, so the data node never receives a new request to (re)start downsampling.

**Comment by kkrik-es** [comment]
Should be fixed now.
