### ISSUE TITLE
Snapshot restore fails to allocate replicas due to FieldExistsQuery error

### ISSUE THREAD

**Issue by JVerwolf** [elastic/elasticsearch#105206]
### Elasticsearch Version

8.11.1

### Java Version

_bundled_

### OS Version

cloud

### Problem Description

Snapshot restored failed to allocate replica shards, though it did allocate a primary shard.  The issue  seems to stem from the following Lucene (v9.8.0) log (see full stack trace below):
```
Caused by: java.lang.IllegalStateException: FieldExistsQuery requires that the field indexes doc values, norms or vectors, but field '_primary_term' exists and indexes neither of these data structures
```

A seemingly likely culprit was that a restore was performed from a `source_only` index (which has known bugs and there is discussion around removing `source_only` functionality altogether). However, in this case, the user mentioned that this `source_only` option was not enabled.

We could explore changing the conditional in Lucene that results in the aforementioned log error when undergoing a snapshot restore.

### Steps to Reproduce

Cannot reproduce locally

### Logs (if relevant)

The full stack trace is shown on the Primary Shard (specifics replaced with REDACTED):
```
[instance-REDACTED] [typeahead-v0][0] marking and sending shard failed due to [failed recovery]
org.elasticsearch.indices.recovery.RecoveryFailedException: [typeahead-v0][0]: Recovery failed from {instance-REDACTED}{REDACTED}{REDACTED}{instance-REDACTED}{10.47.49.43}{10.47.49.43:19005}{himrst}{8.11.1}{7000099-8500003}{data=hot, ml.config_version=11.0.0, transform.config_version=10.0.0, xpack.installed=true, server_name=instance-REDACTED.REDACTED, region=unknown-region, instance_configuration=gcp.data.highcpu.1, availability_zone=us-east1-d, logical_availability_zone=zone-2} into {instance-REDACTED}{REDACTED}{REDACTED}{instance-REDACTED}{10.47.49.36}{10.47.49.36:19182}{himrst}{8.11.1}{7000099-8500003}{data=hot, ml.config_version=11.0.0, xpack.installed=true, transform.config_version=10.0.0, server_name=instance-REDACTED.REDACTED, region=unknown-region, instance_configuration=gcp.data.highcpu.1, availability_zone=us-east1-b, logical_availability_zone=zone-0}
	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$RecoveryResponseHandler.handleException(PeerRecoveryTargetService.java:836) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1421) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1421) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.transport.InboundHandler.doHandleException(InboundHandler.java:475) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.transport.InboundHandler$3.doRun(InboundHandler.java:467) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.11.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: org.elasticsearch.transport.RemoteTransportException: [instance-REDACTED][172.17.0.40:19005][internal:index/shard/recovery/start_recovery]
Caused by: org.elasticsearch.index.engine.RecoveryEngineException: Phase[1] sendFileStep failed
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:290) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.lambda$recoverToTarget$6(RecoverySourceHandler.java:198) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:305) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.RecoverySourceHandler$1.onResponse(RecoverySourceHandler.java:404) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.lambda$recoverToTarget$5(RecoverySourceHandler.java:192) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.lambda$runUnderPrimaryPermit$19(RecoverySourceHandler.java:423) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.action.ActionListener.run(ActionListener.java:368) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.lambda$runUnderPrimaryPermit$20(RecoverySourceHandler.java:401) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener.onResponse(ActionListenerImplementations.java:212) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.index.shard.IndexShard.lambda$wrapPrimaryOperationPermitListener$27(IndexShard.java:3405) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener.onResponse(ActionListenerImplementations.java:212) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.index.shard.IndexShardOperationPermits.innerAcquire(IndexShardOperationPermits.java:254) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:202) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:3376) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:3366) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.runUnderPrimaryPermit(RecoverySourceHandler.java:401) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:180) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.PeerRecoverySourceService.recoverWithFreshClusterState(PeerRecoverySourceService.java:184) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.PeerRecoverySourceService$1.accept(PeerRecoverySourceService.java:146) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.PeerRecoverySourceService$1.accept(PeerRecoverySourceService.java:143) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.PeerRecoverySourceClusterStateDelay.ensureClusterStateVersion(PeerRecoverySourceClusterStateDelay.java:41) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.PeerRecoverySourceService.recover(PeerRecoverySourceService.java:137) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.PeerRecoverySourceService.lambda$new$0(PeerRecoverySourceService.java:86) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:565) ~[?:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(SecurityServerTransportInterceptor.java:618) ~[?:?]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(SecurityServerTransportInterceptor.java:607) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeSystemUser(AuthorizationService.java:668) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:310) ~[?:?]
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter.lambda$inbound$1(ServerTransportFilter.java:113) ~[?:?]
	at org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.xpack.security.authc.AuthenticatorChain.authenticateAsync(AuthenticatorChain.java:94) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:261) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:199) ~[?:?]
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter.authenticate(ServerTransportFilter.java:126) ~[?:?]
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter.inbound(ServerTransportFilter.java:104) ~[?:?]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:629) ~[?:?]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.transport.InboundHandler.doHandleRequest(InboundHandler.java:288) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:301) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.11.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: FieldExistsQuery requires that the field indexes doc values, norms or vectors, but field '_primary_term' exists and indexes neither of these data structures
	at org.apache.lucene.search.FieldExistsQuery.rewrite(FieldExistsQuery.java:170) ~[lucene-core-9.8.0.jar:?]
	at org.apache.lucene.search.BooleanQuery.rewrite(BooleanQuery.java:293) ~[lucene-core-9.8.0.jar:?]
	at org.apache.lucene.search.ConstantScoreQuery.rewrite(ConstantScoreQuery.java:44) ~[lucene-core-9.8.0.jar:?]
	at org.apache.lucene.search.ConstantScoreQuery.rewrite(ConstantScoreQuery.java:44) ~[lucene-core-9.8.0.jar:?]
	at org.apache.lucene.search.IndexSearcher.rewrite(IndexSearcher.java:791) ~[lucene-core-9.8.0.jar:?]
	at org.apache.lucene.search.IndexSearcher.rewrite(IndexSearcher.java:805) ~[lucene-core-9.8.0.jar:?]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:685) ~[lucene-core-9.8.0.jar:?]
	at org.apache.lucene.search.IndexSearcher.count(IndexSearcher.java:457) ~[lucene-core-9.8.0.jar:?]
	at org.elasticsearch.index.engine.LuceneChangesSnapshot.countOperations(LuceneChangesSnapshot.java:292) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.index.engine.InternalEngine.countChanges(InternalEngine.java:3056) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.index.shard.IndexShard.countChanges(IndexShard.java:2430) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.estimateNumberOfHistoryOperations(RecoverySourceHandler.java:388) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:270) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.lambda$recoverToTarget$6(RecoverySourceHandler.java:198) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:305) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.RecoverySourceHandler$1.onResponse(RecoverySourceHandler.java:404) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.lambda$recoverToTarget$5(RecoverySourceHandler.java:192) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.lambda$runUnderPrimaryPermit$19(RecoverySourceHandler.java:423) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.action.ActionListener.run(ActionListener.java:368) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.lambda$runUnderPrimaryPermit$20(RecoverySourceHandler.java:401) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener.onResponse(ActionListenerImplementations.java:212) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.index.shard.IndexShard.lambda$wrapPrimaryOperationPermitListener$27(IndexShard.java:3405) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener.onResponse(ActionListenerImplementations.java:212) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.index.shard.IndexShardOperationPermits.innerAcquire(IndexShardOperationPermits.java:254) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:202) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:3376) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:3366) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.runUnderPrimaryPermit(RecoverySourceHandler.java:401) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:180) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.PeerRecoverySourceService.recoverWithFreshClusterState(PeerRecoverySourceService.java:184) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.PeerRecoverySourceService$1.accept(PeerRecoverySourceService.java:146) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.PeerRecoverySourceService$1.accept(PeerRecoverySourceService.java:143) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.PeerRecoverySourceClusterStateDelay.ensureClusterStateVersion(PeerRecoverySourceClusterStateDelay.java:41) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.PeerRecoverySourceService.recover(PeerRecoverySourceService.java:137) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.indices.recovery.PeerRecoverySourceService.lambda$new$0(PeerRecoverySourceService.java:86) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:565) ~[?:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(SecurityServerTransportInterceptor.java:618) ~[?:?]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(SecurityServerTransportInterceptor.java:607) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeSystemUser(AuthorizationService.java:668) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:310) ~[?:?]
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter.lambda$inbound$1(ServerTransportFilter.java:113) ~[?:?]
	at org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.xpack.security.authc.AuthenticatorChain.authenticateAsync(AuthenticatorChain.java:94) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:261) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:199) ~[?:?]
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter.authenticate(ServerTransportFilter.java:126) ~[?:?]
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter.inbound(ServerTransportFilter.java:104) ~[?:?]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:629) ~[?:?]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.transport.InboundHandler.doHandleRequest(InboundHandler.java:288) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:301) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983) ~[elasticsearch-8.11.1.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.11.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by DaveCTurner** [comment]
> A seemingly likely culprit was that a restore was performed from a source_only index (which has known bugs and there is discussion around removing source_only functionality altogether). However, in this case, the user mentioned that this source_only option was not enabled.

I think this isn't accurate. The user had previously used source-only snapshots, and we believe this index had at some point in the past been a source-only snapshot. Source-only snapshots mutilate the index in ways that can only be reversed by reindexing to a fresh index, a subsequent snapshot/restore cycle is not enough to fix things.

There's no need for a source-only snapshot to restore into an index with replicas. The only thing to do with a source-only snapshot is reindex it, and this only needs a primary. We could in theory make it so that source-only snapshots cannot even have replicas, but having discussed this with the team we're not convinced it's worth the effort. Therefore I'm closing this until we get some specific repro instructions that show how to get this failure to happen without involving a source-only snapshot.
