### ISSUE TITLE
NodeTests#testCloseOnLeaked* reliably failing on MacOS

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#105236]
### CI Link

https://gradle-enterprise.elastic.co/s/wanu5py6nxvhy

### Repro line

`./gradlew ':server:test' --tests "org.elasticsearch.node.NodeTests" -Dtests.seed=44759719145FA21D -Dtests.locale=en-GB -Dtests.timezone=Europe/London -Druntime.java=21`

### Does it reproduce?

Yes

### Applicable branches

`main`

### Failure excerpt

Strangely all seems well on Linux tho.

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.node.NodeTests.testCloseOnLeakedStoreReference" -Dtests.seed=840CE1E9346E700E -Dtests.locale=es-BO -Dtests.timezone=Europe/Copenhagen -Druntime.java=21

java.util.concurrent.TimeoutException: Timeout waiting for task.
org.elasticsearch.ElasticsearchTimeoutException: java.util.concurrent.TimeoutException: Timeout waiting for task.
	at __randomizedtesting.SeedInfo.seed([840CE1E9346E700E:F22014281969A7F6]:0)
	at app//org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:67)
	at app//org.elasticsearch.action.support.PlainActionFuture.actionGet(PlainActionFuture.java:166)
	at app//org.elasticsearch.action.support.PlainActionFuture.actionGet(PlainActionFuture.java:160)
	at app//org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:50)
	at app//org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:16)
	at app//org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:112)
	at app//org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:104)
	at app//org.elasticsearch.node.NodeTests.testCloseOnLeakedStoreReference(NodeTests.java:324)
	at java.base@21/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base@21/java.lang.reflect.Method.invoke(Method.java:580)
	at app//com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
	at app//com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
	at app//com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
	at app//com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at app//org.junit.rules.RunRules.evaluate(RunRules.java:20)
...
```

**Comment by ldematte** [comment]
I was not able to reproduce on my Mac, but then I realized the test fails on machines with almost full disk (or better, full mount point for the `data` directory).

Extract from the build scan: 
```
[2024-02-07T12:06:11,375][WARN ][o.e.c.r.a.DiskThresholdMonitor] [mock_ node] high disk watermark [90%] exceeded on [1bL2AwAAQAC47gDc_____w][mock_ node][****/server/build/testrun/test/temp/org.elasticsearch.node.NodeTests_44759719145FA21D-001/tempDir-002/data] free: 84gb[9%], shards will be relocated away from this node; currently relocating away shards totalling [0] bytes; the node is expected to continue to exceed the high disk watermark when these relocations are complete```

This puts the one-node cluster in a red state; it seems that the one that does the check is the "cluster routing allocation" component. Other similar tests (e.g. IndicesServiceCloseTests) have the same structure, and address the problem by setting very low watermarks values to prevent tests from failing on nodes without enough disk space. 
Will do the same for this test(s).
