### ISSUE TITLE
[CI] RoleMappingFileSettingsIT testRoleMappingsApplied failing

### ISSUE THREAD

**Issue by volodk85** [elastic/elasticsearch#105316]
### CI Link

https://gradle-enterprise.elastic.co/s/vr7m3qpgpz4j2

### Repro line

./gradlew ':x-pack:plugin:security:internalClusterTest' --tests "org.elasticsearch.integration.RoleMappingFileSettingsIT.testRoleMappingsApplied" -Dtests.seed=2F347EC376879869 -Dtests.locale=be -Dtests.timezone=SystemV/MST7 -Druntime.java=21

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure excerpt

```
org.elasticsearch.integration.RoleMappingFileSettingsIT > testRoleMappingsApplied FAILED
    java.lang.AssertionError: Unexpected AlreadyClosedException
        at __randomizedtesting.SeedInfo.seed([2F347EC376879869]:0)
        at org.elasticsearch.index.engine.InternalEngine.failOnTragicEvent(InternalEngine.java:2523)
        at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:2069)
        at org.elasticsearch.index.engine.InternalEngine.lambda$maybeRefresh$8(InternalEngine.java:2021)
        at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:270)
        at org.elasticsearch.index.engine.InternalEngine.maybeRefresh(InternalEngine.java:2021)
        at org.elasticsearch.index.shard.IndexShard.lambda$scheduledRefresh$47(IndexShard.java:3934)
        at org.elasticsearch.action.ActionListener.run(ActionListener.java:356)
        at org.elasticsearch.index.shard.IndexShard.scheduledRefresh(IndexShard.java:3914)
        at org.elasticsearch.index.IndexService.maybeRefreshEngine(IndexService.java:1003)
        at org.elasticsearch.index.IndexService$AsyncRefreshTask.runInternal(IndexService.java:1139)
        at org.elasticsearch.common.util.concurrent.AbstractAsyncTask.run(AbstractAsyncTask.java:137)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:917)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

        Caused by:
        org.apache.lucene.store.AlreadyClosedException: engine is closed
            at app//org.elasticsearch.index.shard.IndexShard.getEngine(IndexShard.java:3184)
            at app//org.elasticsearch.index.shard.IndexShard$RefreshFieldHasValueListener.afterRefresh(IndexShard.java:4014)
            at app//org.apache.lucene.search.ReferenceManager.notifyRefreshListenersRefreshed(ReferenceManager.java:275)
            at app//org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:182)
            at app//org.apache.lucene.search.ReferenceManager.maybeRefresh(ReferenceManager.java:213)
            at app//org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:2048)
            ... 13 more
```

**Comment by slobodanadamovic** [comment]
This is a duplicate of https://github.com/elastic/elasticsearch/issues/105330 for which a fix has been raised https://github.com/elastic/elasticsearch/pull/105374.
