### ISSUE TITLE
Cannot invoke String.length() because str is null error with ParentIdQueryBuilder

### ISSUE THREAD

**Issue by demjened** [elastic/elasticsearch#105366]
On serverless we observed a couple of 500's with the message `Cannot invoke \"String.length()\" because \"str\" is null\`, caused by this line: https://github.com/elastic/elasticsearch/blob/21b0caaf13cf1d0dde5a85ef2a44917d3481d539/modules/parent-join/src/main/java/org/elasticsearch/join/query/ParentIdQueryBuilder.java#L70

ES version: 8.13.0

I tried reproducing the error in a serverless environment but I didn't get past the syntax validation (`type` cannot be null).

Relevant stack trace:
```
"Failed to execute phase [query], all shards failed; shardFailures {[<redacted>][<redacted>][0]: org.elasticsearch.transport.SendRequestTransportException: [es-es-search-<redacted>][indices:data/read/search[phase/query]]
...
Caused by: java.lang.NullPointerException: Cannot invoke \"String.length()\" because \"str\" is null
  at org.elasticsearch.server@8.13.0/org.elasticsearch.common.io.stream.StreamOutput.writeString(StreamOutput.java:402)
  at org.elasticsearch.server@8.13.0/org.elasticsearch.common.io.stream.StreamOutput.writeString(StreamOutput.java:389)
  at org.elasticsearch.join@8.13.0/org.elasticsearch.join.query.ParentIdQueryBuilder.doWriteTo(ParentIdQueryBuilder.java:70)
  at org.elasticsearch.server@8.13.0/org.elasticsearch.index.query.AbstractQueryBuilder.writeTo(AbstractQueryBuilder.java:76)
  at org.elasticsearch.server@8.13.0/org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:995)
  at org.elasticsearch.server@8.13.0/org.elasticsearch.search.builder.SubSearchSourceBuilder.writeTo(SubSearchSourceBuilder.java:84)
  at org.elasticsearch.server@8.13.0/org.elasticsearch.common.io.stream.StreamOutput.writeWriteable(StreamOutput.java:983)
  at org.elasticsearch.server@8.13.0/org.elasticsearch.common.io.stream.StreamOutput.writeCollection(StreamOutput.java:1052)
  at org.elasticsearch.server@8.13.0/org.elasticsearch.common.io.stream.StreamOutput.writeCollection(StreamOutput.java:1042)
  at org.elasticsearch.server@8.13.0/org.elasticsearch.search.builder.SearchSourceBuilder.writeTo(SearchSourceBuilder.java:294)
  at org.elasticsearch.server@8.13.0/org.elasticsearch.common.io.stream.StreamOutput.writeOptionalWriteable(StreamOutput.java:972)
  at org.elasticsearch.server@8.13.0/org.elasticsearch.search.internal.ShardSearchRequest.innerWriteTo(ShardSearchRequest.java:361)
  at org.elasticsearch.server@8.13.0/org.elasticsearch.search.internal.ShardSearchRequest.writeTo(ShardSearchRequest.java:349)
  at org.elasticsearch.server@8.13.0/org.elasticsearch.transport.OutboundMessage.serialize(OutboundMessage.java:71)
  at org.elasticsearch.server@8.13.0/org.elasticsearch.transport.OutboundHandler.sendMessage(OutboundHandler.java:186)
  at org.elasticsearch.server@8.13.0/org.elasticsearch.transport.OutboundHandler.sendRequest(OutboundHandler.java:105)
  at org.elasticsearch.server@8.13.0/org.elasticsearch.transport.TcpTransport$NodeChannels.sendRequest(TcpTransport.java:322)
  at org.elasticsearch.server@8.13.0/org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:953)
  ... 178 more
```

**Comment by benwtrent** [comment]
> but I didn't get past the syntax validation (type cannot be null).

Looking at the code, it seems like this would only occur when serializing to another node. I actually don't immediately see where we validate that `type` shouldn't be `null`. 

When you say you got "syntax validation" could you post what failure you did receive @demjened?

**Comment by demjened** [comment]
I used the example parent ID mapping and request in the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-parent-id-query.html#query-dsl-parent-id-query) without a `type` attribute.

I just tested it again on a 8.12.0 deployment, and I saw some race condition-like anomaly. Executing the query many times in a row resulted randomly in either
- 400 with an error message `[parent_id] no relation found for child [null]`
- 500 with the `Cannot invoke \"String.length()\" because \"str\" is null\"` error message


https://github.com/elastic/elasticsearch/assets/14224983/6ba10f52-3aa2-4a2e-ae65-329619b84033

**Comment by benwtrent** [comment]
thank you @demjened , The bug fix isn't too bad. Looks like @original-brownbear has taken up the cause.
