### ISSUE TITLE
[CI] ConcurrentSnapshotsIT testDeleteIndexWithOutOfOrderFinalization failing

### ISSUE THREAD

**Issue by kingherc** [elastic/elasticsearch#105484]
Might be transient, but opening the ticket just in case, so it's first taken a deeper look.

```
  1> [2024-02-14T02:38:36,051][INFO ][o.e.c.r.a.AllocationService] [node_t0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[index-2][0]]]).
  1> [2024-02-14T02:38:36,065][INFO ][o.e.s.ConcurrentSnapshotsIT] [testDeleteIndexWithOutOfOrderFinalization] --> creating or updating repository [test-repo] [fs]
  1> [2024-02-14T02:38:36,077][INFO ][o.e.r.RepositoriesService] [node_t0] put repository [test-repo]
  1> [2024-02-14T02:38:36,108][INFO ][o.e.s.SnapshotsService   ] [node_t0] snapshot [test-repo:snapshot-with-index-0/qPioiixeSi-2KOFwisJKVw] started
  1> [2024-02-14T02:38:36,114][INFO ][o.e.s.SnapshotsService   ] [node_t0] snapshot [test-repo:snapshot-with-index-1/BiR5Q9HLT0Sn0SPAP-ZxLA] started
  1> [2024-02-14T02:38:36,126][INFO ][o.e.s.SnapshotsService   ] [node_t0] snapshot [test-repo:snapshot-with-index-2/XlkfD5MAQ62f9V-WL4Ml1Q] started
  1> [2024-02-14T02:38:36,174][INFO ][o.e.s.SnapshotsService   ] [node_t0] snapshot [test-repo:snapshot-with-index-1/BiR5Q9HLT0Sn0SPAP-ZxLA] completed with state [SUCCESS]
  1> [2024-02-14T02:38:36,199][INFO ][o.e.s.SnapshotsService   ] [node_t0] snapshot [test-repo:snapshot-with-index-2/XlkfD5MAQ62f9V-WL4Ml1Q] completed with state [SUCCESS]
  1> [2024-02-14T02:38:36,222][INFO ][o.e.s.SnapshotsService   ] [node_t0] snapshot [test-repo:snapshot-with-index-0/qPioiixeSi-2KOFwisJKVw] completed with state [SUCCESS]
  2> 二月 14, 2024 2:39:06 上午 com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
  2> 警告: Uncaught exception in thread: Thread[Thread-64,5,TGRP-ConcurrentSnapshotsIT]
  2> java.lang.AssertionError: java.util.concurrent.TimeoutException: Timeout waiting for task.
  2> 	at __randomizedtesting.SeedInfo.seed([E41F8D023ED55CA0]:0)
  2> 	at org.elasticsearch.snapshots.ConcurrentSnapshotsIT.lambda$testDeleteIndexWithOutOfOrderFinalization$24(ConcurrentSnapshotsIT.java:2116)
  2> 	at java.base/java.lang.Thread.run(Thread.java:829)
  2> Caused by: java.util.concurrent.TimeoutException: Timeout waiting for task.
  2> 	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:228)
  2> 	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:53)
  2> 	at org.elasticsearch.test.ClusterServiceUtils.awaitClusterState(ClusterServiceUtils.java:234)
  2> 	at org.elasticsearch.snapshots.AbstractSnapshotIntegTestCase.awaitClusterState(AbstractSnapshotIntegTestCase.java:571)
  2> 	at org.elasticsearch.snapshots.AbstractSnapshotIntegTestCase.awaitClusterState(AbstractSnapshotIntegTestCase.java:563)
  2> 	at org.elasticsearch.snapshots.ConcurrentSnapshotsIT.lambda$testDeleteIndexWithOutOfOrderFinalization$24(ConcurrentSnapshotsIT.java:2093)
  2> 	... 1 more

  1> [2024-02-14T02:39:06,240][INFO ][o.e.s.ConcurrentSnapshotsIT] [testDeleteIndexWithOutOfOrderFinalization] --> creating full snapshot [final-full-snapshot] in [test-repo]
  1> [2024-02-14T02:39:06,249][INFO ][o.e.s.SnapshotsService   ] [node_t0] snapshot [test-repo:final-full-snapshot/U7OBQ7rBQeWDoDC_tOVq0Q] started
  1> [2024-02-14T02:39:06,303][INFO ][o.e.s.ConcurrentSnapshotsIT] [testDeleteIndexWithOutOfOrderFinalization] --> deleting snapshot [final-full-snapshot] from repo [test-repo]
  1> [2024-02-14T02:39:06,303][INFO ][o.e.s.SnapshotsService   ] [node_t0] snapshot [test-repo:final-full-snapshot/U7OBQ7rBQeWDoDC_tOVq0Q] completed with state [SUCCESS]
  1> [2024-02-14T02:39:06,304][INFO ][o.e.s.SnapshotsService   ] [testDeleteIndexWithOutOfOrderFinalization] deleting snapshots [final-full-snapshot] from repository [test-repo]
  1> [2024-02-14T02:39:06,344][INFO ][o.e.s.SnapshotsService   ] [node_t0] snapshots [final-full-snapshot/U7OBQ7rBQeWDoDC_tOVq0Q] deleted
  1> [2024-02-14T02:39:06,350][INFO ][o.e.s.SnapshotsService   ] [node_t0] deleting snapshots [old-version-snapshot-*] from repository [test-repo]
  1> [2024-02-14T02:39:06,352][INFO ][o.e.a.a.c.r.c.TransportCleanupRepositoryAction] [testDeleteIndexWithOutOfOrderFinalization] Running cleanup operations on repository [test-repo][4]
  1> [2024-02-14T02:39:06,361][INFO ][o.e.a.a.c.r.c.TransportCleanupRepositoryAction] [node_t0] Done with repository cleanup on [test-repo][4] with result [{"deleted_bytes":0,"deleted_blobs":0}]
  1> [2024-02-14T02:39:06,395][INFO ][o.e.s.ConcurrentSnapshotsIT] [testDeleteIndexWithOutOfOrderFinalization] [ConcurrentSnapshotsIT#testDeleteIndexWithOutOfOrderFinalization]: cleaning up after test
  1> [2024-02-14T02:39:06,411][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_t0] [index-to-delete/A8vj5S5DTlyt-LjgCxW9Ag] deleting index
  1> [2024-02-14T02:39:06,411][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_t0] [index-2/ZdixiPpISiyCa4brRsR4DA] deleting index
  1> [2024-02-14T02:39:06,411][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_t0] [index-0/9KYqsU3KRX6ipZqsABwW9Q] deleting index
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/scqs3t3grvcnm/tests/:server:internalClusterTest/org.elasticsearch.snapshots.ConcurrentSnapshotsIT/testDeleteIndexWithOutOfOrderFinalization

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.ConcurrentSnapshotsIT.testDeleteIndexWithOutOfOrderFinalization" -Dtests.seed=E41F8D023ED55CA0 -Dtests.locale=zh-Hant-TW -Dtests.timezone=Antarctica/McMurdo -Druntime.java=11
```

**Applicable branches:**
7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.snapshots.ConcurrentSnapshotsIT#testDeleteIndexWithOutOfOrderFinalization`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testDeleteIndexWithOutOfOrderFinalization'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.snapshots.ConcurrentSnapshotsIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: java.util.concurrent.TimeoutException: Timeout waiting for task.

  at __randomizedtesting.SeedInfo.seed([E41F8D023ED55CA0]:0)
  at org.elasticsearch.snapshots.ConcurrentSnapshotsIT.lambda$testDeleteIndexWithOutOfOrderFinalization$24(ConcurrentSnapshotsIT.java:2116)
  at java.lang.Thread.run(Thread.java:829)

  Caused by: java.util.concurrent.TimeoutException: Timeout waiting for task.

    at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:228)
    at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:53)
    at org.elasticsearch.test.ClusterServiceUtils.awaitClusterState(ClusterServiceUtils.java:234)
    at org.elasticsearch.snapshots.AbstractSnapshotIntegTestCase.awaitClusterState(AbstractSnapshotIntegTestCase.java:571)
    at org.elasticsearch.snapshots.AbstractSnapshotIntegTestCase.awaitClusterState(AbstractSnapshotIntegTestCase.java:563)
    at org.elasticsearch.snapshots.ConcurrentSnapshotsIT.lambda$testDeleteIndexWithOutOfOrderFinalization$24(ConcurrentSnapshotsIT.java:2093)
    at java.lang.Thread.run(Thread.java:829)

```

**Comment by arteam** [comment]
The test comes from #103817 and it was backport to 7.17 where it fails regularly. I'm gonna mute it on the 7.17 branch
