### ISSUE TITLE
co.elastic.elasticsearch.metering.IndexSizeMeteringIT > testSizeMetricsAreRecorded FAILED

### ISSUE THREAD

**Issue by DiannaHohensee** [elastic/elasticsearch#105585]
### CI Link

https://buildkite.com/elastic/elasticsearch-serverless-pull-request/builds/954#018db00b-2167-4063-b5d0-ace013a7e1ce

### Repro line

REPRODUCE WITH: ./gradlew ':modules:serverless-metering:internalClusterTest' --tests "co.elastic.elasticsearch.metering.IndexSizeMeteringIT.testSizeMetricsAreRecorded" -Dtests.seed=12FC2813A4DF3D1E -Dtests.locale=pt-PT -Dtests.timezone=America/Ensenada -Druntime.java=21

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure excerpt

```

co.elastic.elasticsearch.metering.IndexSizeMeteringIT > testSizeMetricsAreRecorded FAILED
    java.util.NoSuchElementException: No value present
        at __randomizedtesting.SeedInfo.seed([12FC2813A4DF3D1E:DBA8FA1CF97B45B7]:0)
        at java.base/java.util.Optional.get(Optional.java:143)
        at co.elastic.elasticsearch.metering.AbstractMeteringIntegTestCase.getFirstReceivedRecord(AbstractMeteringIntegTestCase.java:144)
        at co.elastic.elasticsearch.metering.IndexSizeMeteringIT.testSizeMetricsAreRecorded(IndexSizeMeteringIT.java:102)
```

**Comment by DiannaHohensee** [comment]
Oops, I thought AbstractMeteringIntegTestCase was in elasticsearch, and it's not.
