### ISSUE TITLE
[CI] DataStreamLifecycleDownsampleDisruptionIT testDataStreamLifecycleDownsampleRollingRestart failing

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#105577]
**Build scan:**
https://gradle-enterprise.elastic.co/s/bxsxynuftpees/tests/:x-pack:plugin:downsample:internalClusterTest/org.elasticsearch.xpack.downsample.DataStreamLifecycleDownsampleDisruptionIT/testDataStreamLifecycleDownsampleRollingRestart

**Reproduction line:**
```
./gradlew ':x-pack:plugin:downsample:internalClusterTest' --tests "org.elasticsearch.xpack.downsample.DataStreamLifecycleDownsampleDisruptionIT.testDataStreamLifecycleDownsampleRollingRestart" -Dtests.seed=8A21E9141C0F5434 -Dtests.locale=hi-IN -Dtests.timezone=Atlantic/St_Helena -Druntime.java=21
```

**Applicable branches:**
8.12

**Reproduces locally?:**
No

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.downsample.DataStreamLifecycleDownsampleDisruptionIT#testDataStreamLifecycleDownsampleRollingRestart`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testDataStreamLifecycleDownsampleRollingRestart'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.downsample.DataStreamLifecycleDownsampleDisruptionIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.elasticsearch.node.NodeClosedException: node closed {node_t1}{llCnhTpwTLWxO90uTnMHZw}{zITNmZUDTdCEYQefoLMU4g}{node_t1}{127.0.0.1}{127.0.0.1:21762}{d}{8.12.2}{7000099-8500010}{xpack.installed=true}

  at __randomizedtesting.SeedInfo.seed([8A21E9141C0F5434:5DB87EA44A02B17A]:0)
  at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:943)
  at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:847)
  at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:757)
  at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:745)
  at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:245)
  at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.onNewClusterState(TransportMasterNodeAction.java:306)
  at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onNewClusterState(ClusterStateObserver.java:341)
  at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:171)
  at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:119)
  at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.retry(TransportMasterNodeAction.java:302)
  at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.retryOnNextState(TransportMasterNodeAction.java:283)
  at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.handleException(TransportMasterNodeAction.java:263)
  at org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1718)
  at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1435)
  at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:1319)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by idegtiarenko** [comment]
Is this one same as https://github.com/elastic/elasticsearch/issues/99520 ?

**Comment by mark-vieira** [comment]
This test continues to fail a couple of times a day so I've muted it on `main`, `8.13` and `8.12`. I'm also readding the blocker label since this is muted so we can retriage.

**Comment by dakrone** [comment]
I believe this is a duplicate of #99520, so I'm closing it in favor of that one.
