### ISSUE TITLE
Inconsistent long overflow with a date field

### ISSUE THREAD

**Issue by srri** [elastic/elasticsearch#105634]
### Elasticsearch Version

8.12.0

### Java Version

_bundled_

### OS Version

Elastic Cloud

### Problem Description

When posting a document, with a field definition of:
```
                "time_field" : {
                    "type" : "date",
                    "format" : "date_optional_time||epoch_millis",
                    "index" : false
                }
```

If the value is > 292278994, I get a long overflow exception (eg: `292278994` is OK, `292278995` and higher fails)

### Steps to Reproduce

Mapping:
```
"mappings": {
            "dynamic": "strict",
            "properties": {
                "@timestamp": {
                    "type": "date",
                    "format": "date_optional_time||epoch_millis"
                },
                "time_field" : {
                    "type" : "date",
                    "format" : "date_optional_time||epoch_millis",
                    "index" : false
                }
            }
        }
```

Test file:
```
cat test-file.json
{
  "@timestamp": "1708109088737",
  "time_field": 292278995
}
```

```
curl -X POST --insecure https://localhost:9200/logs-events-elasticsearchidentificationevent/_doc -u 'elastic:elastic123' -H "Content-Type: application/json"  -d @test-file.json
{"error":{"root_cause":[{"type":"document_parsing_exception","reason":"[1:58] failed to parse field [time_field] of type [date] in document with id 'aYJPwo0BtRzlmlC49I_Z'. Preview of field's value: '292278995'"}],"type":"document_parsing_exception","reason":"[1:58] failed to parse field [time_field] of type [date] in document with id 'aYJPwo0BtRzlmlC49I_Z'. Preview of field's value: '292278995'","caused_by":{"type":"arithmetic_exception","reason":"long overflow"}},"status":400}
```

Looking at the document being stored (the last successful one, with a value of `292278994`)

```
{
  "_index": ".ds-logs-events-elasticsearchidentificationevent-2024.02.19-000001",
  "_id": "aIJPwo0BtRzlmlC41Y9c",
  "_version": 1,
  "_score": 0,
  "_source": {
    "@timestamp": "1708109088737",
    "time_field": 292278994
  },
  "fields": {
    "@timestamp": [
      "2024-02-16T18:44:48.737Z"
    ],
    "time_field": [
      "+292278994-01-01T00:00:00.000Z"
    ]
  }
}
```

It seems it is parsing `292278994` as a date, however, if I change the file (quoting the number in strings)
{
  "@timestamp": "1708109088737",
  "time_field": "292278995"
}

It still fails with the same error. How can this be OK for `@timestamp` but not for `time_field`?

### Logs (if relevant)

```
[instance-0000000014/[.ds-logs-events-elasticsearchidentificationevent-2024.02.15-000026/[1/

failed to execute bulk item (create) index {[logs-events-elasticsearchidentificationevent/[elasticsearchIdentificationEvent+11+10000981/, source[n/a, actual length: [23.1kb/, max length: 2kb/} org.elasticsearch.index.mapper.DocumentParsingException: 

[1:1924/failed to parse field [time_field/of type [date/ in document with id 'elasticsearchIdentificationEvent+11+10000981'. 

Preview of field's value: '978366495' at org.elasticsearch.index.mapper.FieldMapper.rethrowAsDocumentParsingException(FieldMapper.java:232) ~

[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:185) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:411) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:642) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:342) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:293) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.index.mapper.DocumentParser.internalParseDocument(DocumentParser.java:144) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:96) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:92) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:1012) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:960) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:904) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:360) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:224) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:291) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:142) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:74) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.action.support.replication.TransportWriteAction$1.doRun(TransportWriteAction.java:216) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.12.0.jar:?/
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?/
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?/
 at java.lang.Thread.run(Thread.java:1583) ~[?:?/
 Caused by: java.lang.ArithmeticException: long overflow at java.lang.Math.multiplyExact(Math.java:1032) ~[?:?/
 at java.lang.Math.multiplyExact(Math.java:1008) ~[?:?/
 at java.time.Instant.toEpochMilli(Instant.java:1262) ~[?:?/
 at org.elasticsearch.index.mapper.DateFieldMapper$Resolution$1.convert(DateFieldMapper.java:95) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.index.mapper.DateFieldMapper$DateFieldType.parse(DateFieldMapper.java:490) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.index.mapper.DateFieldMapper.parseCreateField(DateFieldMapper.java:910) ~[elasticsearch-8.12.0.jar:?/
 at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:183) ~[elasticsearch-8.12.0.jar:?/
```

**Comment by benwtrent** [comment]
I can confirm this weird behavior. 

When supplying `1708109088737` we parse as `epoch_millis` directly. When supplying `292278995` we attempt to use the default date value parser and parse it as `uuuu-MM-dd'T'HH:mm:ss.SSSZ`. You can see the output when printing as `+292278994-01-01T00:00:00.000Z"` Which indeed is a weird value as `292278994` is definitely not the year you are expecting if you wish `292278994` to be parsed as epoch-millis.

@srri would you expect `292278994` to always be parsed as `epoch_millis`?

**Comment by benwtrent** [comment]
Related: https://github.com/elastic/elasticsearch/issues/81042

**Comment by benwtrent** [comment]
When a number isn't at least 10 digits long, it isn't parsed as `epoch_millis` but instead its parsed as a `year` and thus we hit the arithmetic overflow in java's parser.

I am not sure we should attempt to automatically switch to parse as `epoch_millis` if we hit an arithmetic overflow.

`292278995` if parsed as `epoch_millis` would be the date `Sunday, January 4, 1970 9:11:18 AM` because its only `292278.995` seconds from the epoch (`Thursday, January 1, 1970 12:00:00 AM`).

**Comment by srri** [comment]
> @srri would you expect 292278994 to always be parsed as epoch_millis?

I was just surprised as I thought the default date parser expects a string-formatted input, and just treated the number as a year only. We discovered this in a bug where we were writing epoch seconds to this field and finally hit a value that resulted in a `year` > 292278994. Seems like perhaps just a documentation bug that would benefit from some additional text.

**Comment by benwtrent** [comment]
> where we were writing epoch seconds to this field

`epoch_second` is what you should use instead of `epoch_millis` if you are writing seconds.

But, yeah we attempt the parsers in order and that means that Java may (regrettibly) parse it as a year 🤦

**Comment by srri** [comment]
> epoch_second is what you should use instead of epoch_millis if you are writing seconds.
Of course, was just a bug on our side.

> But, yeah we attempt the parsers in order and that means that Java may (regrettibly) parse it as a year
So if the format were:
`"epoch_millis||date_optional_time"`
instead of:
`"date_optional_time||epoch_millis"`
It would have treated the input as `epoch_millis`?

**Comment by benwtrent** [comment]
@srri correct. I just did a test to confirm

if you index with `"epoch_millis||date_optional_time"` the overflow error doesn't occur because we do not attempt to parse the date.

**Comment by benwtrent** [comment]
One other thing to note is the difference between `date_optional_time` and `strict_date_optional_time`. 

`date_optional_time` is very lenient. 

`strict_date_optional_time` is strict and a valid date must be provided and it will not parse a single numerical value as a date. 

Consequently `"format": "strict_date_optional_time||epoch_millis"` does NOT suffer from the same weird overflow failure.

**Comment by benwtrent** [comment]
🤦 Looking at the code, I see why adding another digit causes the parsing to be OK with `date_optional_time`.

Our parsing does this:
```
 private static final DateTimeFormatter DATE_FORMATTER = new DateTimeFormatterBuilder().appendValue(
        ChronoField.YEAR,
        1,
        9,
        SignStyle.NORMAL
    )
```
So, for the lenient version we parse the first `9` digits (if it starts with digits) as a year. Adding another digit fails the formatter cleanly (as its not `9` digits followed by a `-`). Thus it doesn't hit the arithmetic overflow.

Dang, why can't we have a universal time stamp format that is always a particular format all the time no matter the time-zone or logging system :).

I am not sure how to best update the docs to reflect this side-effect. I will see if there is any clean place to indicate this behavior.

**Comment by srri** [comment]
Thanks Ben, I appreciate the deep dive into this issue. I'm happy to close this and look forward to any doc updates.
