### ISSUE TITLE
ES having trouble parsing Hash of Array

### ISSUE THREAD

**Issue by domofactor** [elastic/elasticsearch#10577]
hey guys,

I noticed that ES was failing on the following message on versions 1.2.2 and 1.50 when using it as an Outputter in Logstash. Any Ideas?  Also, if I should be posting this elsewhere, please let me know! Thank You.

Message:
```
{"myname":"terrell", "foo":{[1 , 2 , 3]}}
```

Error:
```
[2015-03-17 23:51:16,225][DEBUG][action.bulk              ] [mozstash-ubuntu-1404] [logstash-2015.03.17][3] failed to execute bulk item (index) index {[logstash-2015.03.17][logs][DdfZBz4qSKOMAOzT-NNp5w], source[{"@timestamp":"2015-03-17T23:51:16.235Z","tier":"_default","hostname":"emitter-ubuntu-1204","severity":"notice","service":"vagrant","collector":"collector-ubuntu-1404","message":"{\"myname\":\"terrell\", \"foo\":[1 , 2 , 3]}","@version":"1","host":"172.28.128.5:41237","myname":"terrell","foo":[1,2,3]}]}
org.elasticsearch.index.mapper.MapperParsingException: object mapping [foo] trying to serialize a value with no field associated with it, current value [1]
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:644)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:501)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:648)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeArray(ObjectMapper.java:636)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:493)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:534)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:483)
        at org.elasticsearch.index.shard.service.InternalIndexShard.prepareCreate(InternalIndexShard.java:376)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:430)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:158)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:527)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:426)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by imotov** [comment]
Hash is a set of key - value pairs. I think your hash `{[1 , 2 , 3]}` is missing the key portion. It should be `{"arr": [1, 2, 3]}` to be a hash. Would you agree? Another question is why such hash is getting generated, and this would be a great question for the [logstash mailing list](https://groups.google.com/forum/#!forum/logstash-users).

**Comment by clintongormley** [comment]
Yep - this is malformed JSON. You should try to find where this bad JSON is coming from
