### ISSUE TITLE
Test cases depends on the locale info

### ISSUE THREAD

**Issue by puppylpg** [elastic/elasticsearch#105822]
### CI Link

locally reproduced

### Repro line

locally reproduced

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

There are some test failures when running `./gradlew :server:test` in main for `ReadinessServiceTests#testStatusChange` and `ReadinessServiceTests#testTCPProbe`, because they expect connection exceptions and [tries to check the exception message](https://github.com/elastic/elasticsearch/blob/b4b32aa53a53975d1540dfc37c985729d622c6b6/test/framework/src/main/java/org/elasticsearch/test/readiness/ReadinessClientProbe.java#L77) as `Connection refused`. However, the `ConnectException` message returned depends on the locale of the machine where the tests are running.

Here is the locale environment of mine:
```bash
$ echo $LANG
zh_CN.UTF-8

$ echo $LC_ALL


$ echo $LANGUAGE
zh_CN

$ locale
LANG=zh_CN.UTF-8
LANGUAGE=zh_CN
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=

```

which causes the exception message to be `拒绝连接` rather than `Connection refused`:
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.readiness.ReadinessServiceTests.testTCPProbe" -Dtests.seed=3C10013F4F3AED5 -Dtests.locale=fr-CH -Dtests.timezone=Africa/Ndjamena -Druntime.java=21


Expected: a string containing "Connection refused"
     but: was "拒绝连接"
java.lang.AssertionError: 
Expected: a string containing "Connection refused"
     but: was "拒绝连接"
	at __randomizedtesting.SeedInfo.seed([3C10013F4F3AED5:15EF4B4851A01333]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at org.elasticsearch.test.readiness.ReadinessClientProbe.lambda$tcpReadinessProbeFalse$2(ReadinessClientProbe.java:77)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at org.elasticsearch.test.readiness.ReadinessClientProbe.tcpReadinessProbeFalse(ReadinessClientProbe.java:72)
	at org.elasticsearch.test.readiness.ReadinessClientProbe.tcpReadinessProbeFalse(ReadinessClientProbe.java:64)
	at org.elasticsearch.readiness.ReadinessServiceTests.testTCPProbe(ReadinessServiceTests.java:183)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

I think we should add the locale info in the build configuration to make sure that the test cases pass regardless of the environment they are running.

**Comment by mark-vieira** [comment]
I don't think we want to be hard-coding locales. In fact, our randomized testing framework should be choosing a random locale for test execution. It seems that's not actually working and it just uses the host locale anyway?

**Comment by puppylpg** [comment]
>  It seems that's not actually working and it just uses the host locale anyway?

I do think so. In the fail message the `REPRODUCE` part shows that it uses `-Dtests.locale=fr-CH -Dtests.timezone=Africa/Ndjamena` but still the error message appears as my locale `zh_CN`.

If random locale is used on purpose, why does the test case [try to check the exception message](https://github.com/elastic/elasticsearch/blob/b4b32aa53a53975d1540dfc37c985729d622c6b6/test/framework/src/main/java/org/elasticsearch/test/readiness/ReadinessClientProbe.java#L77) which is localized?

**Comment by mark-vieira** [comment]
There's two problems here. First, it doesn't seem as though the test is running in the randomly selected locale, it's using the host locale regardless. Second is that the test is susceptible to locale, which is sort of the whole point of randomly selecting one during test execution, which is to root out problems like this one. This isn't actually a "bug" of course, but just the test not being robust against localization.

**Comment by puppylpg** [comment]
Thanks for your detailed explanation. 

For the first problem, I think it's because the `LANGUAGE` locale is set on my host and has nothing about current locale info after a small test:
```java
import java.io.IOException;
import java.net.Socket;

/**
 * @author puppylpg on 2024/02/28
 */
public class TcpConnect {

	public static void main(String[] args) {
		String serverAddress = "localhost";
		int serverPort = 12345;

		try {
			Socket socket = new Socket(serverAddress, serverPort);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
```

```bash
Ξ ~ → javac TcpConnect.java
Ξ ~ → java TcpConnect
java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        ...

// Chinese
Ξ ~ → LANGUAGE=zh_CN java TcpConnect
java.net.ConnectException: 拒绝连接
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        ...

// French
Ξ ~ → LANGUAGE=fr_CH java TcpConnect
java.net.ConnectException: Connexion refusée
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        ...

// Russian
Ξ ~ → LANGUAGE=ru_RU java TcpConnect
java.net.ConnectException: В соединении отказано
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        ...
```
The `Connection refused` message has nothing about the current locale but the `LANGUAGE` environment, so the random locale is not a problem.

For the second point, I think maybe just checking the exception type rather detailed message is ok.
