### ISSUE TITLE
ESQL heap attack test failing

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#105814]
### CI Link

https://gradle-enterprise.elastic.co/s/x6pug7fdypkjo

### Repro line

```bash
./gradlew ':test:external-modules:test-esql-heap-attack:javaRestTest' --tests "org.elasticsearch.xpack.esql.heap_attack.HeapAttackIT.testGroupOnManyLongs" -Dtests.seed=F87001F812AC63B0 -Dtests.locale=ja-JP-u-ca-japanese-x-lvariant-JP -Dtests.timezone=Australia/Melbourne -Druntime.java=18
```

### Does it reproduce?

No

### Applicable branches

main

### Failure excerpt

```
org.elasticsearch.xpack.esql.heap_attack.HeapAttackIT > testFetchTooManyMvLongs FAILED |  
-- | --
java.lang.AssertionError: Expected a map containing |  
status: expected <429> but was <500> |  
error: a map containing |  
type: expected "circuit_breaking_exception" but was "node_disconnected_exception" |  
reason: "[test-cluster-0][127.0.0.1:35249][indices:data/read/esql/data] disconnected" unexpected but ok |  
stack_trace: "org.elasticsearch.transport.NodeDisconnectedException: [test-cluster-0][127.0.0.1:35249][indices:data/read/esql/data] disconnected
  Suppressed: org.elasticsearch.tasks.TaskCancelledException: cancelled
    at org.elasticsearch.compute.operator.Driver.cancel(Driver.java:263)
    at org.elasticsearch.compute.operator.DriverTaskRunner$DriverRequest$1.onCancelled(DriverTaskRunner.java:101)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.tasks.CancellableTask.cancel(CancellableTask.java:43)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$CancellableTaskHolder.cancel(TaskManager.java:617)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager.cancel(TaskManager.java:274)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.tasks.TaskCancellationService.doCancelTaskAndDescendants(TaskCancellationService.java:127)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.tasks.TaskCancellationService.lambda$cancelTaskAndDescendants$0(TaskCancellationService.java:106)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.ResultDeduplicator.executeOnce(ResultDeduplicator.java:49)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.tasks.TaskCancellationService.cancelTaskAndDescendants(TaskCancellationService.java:103)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.tasks.TaskCancellationService$BanParentRequestHandler.messageReceived(TaskCancellationService.java:358)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.tasks.TaskCancellationService$BanParentRequestHandler.messageReceived(TaskCancellationService.java:342)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:1056)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.transport.TransportService$3.sendRequest(TransportService.java:144)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:953)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:848)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.tasks.TaskCancellationService.setBanOnChildConnections(TaskCancellationService.java:181)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.tasks.TaskCancellationService.doCancelTaskAndDescendants(TaskCancellationService.java:132)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.tasks.TaskCancellationService.lambda$cancelTaskAndDescendants$0(TaskCancellationService.java:106)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.ResultDeduplicator.executeOnce(ResultDeduplicator.java:49)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.tasks.TaskCancellationService.cancelTaskAndDescendants(TaskCancellationService.java:103)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager.cancelTaskAndDescendants(TaskManager.java:812)
    at org.elasticsearch.xpack.esql.plugin.ComputeService.lambda$cancelOnFailure$17(ComputeService.java:377)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.acceptException(ActionListenerImplementations.java:186)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onFailure(ActionListenerImplementations.java:191)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
    at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.ActionLi… |  
suppressed: <[{reason=cancelled, stack_trace=org.elasticsearch.tasks.TaskCancelledException: cancelled
```

**Comment by rjernst** [comment]
Note this has been failing for at least a couple weeks in the periodic jobs on main. It seems to fail randomly with the java-matrix tests (various jdk versions).

**Comment by dnhatn** [comment]
Fixed in https://github.com/elastic/elasticsearch/pull/105848.
