### ISSUE TITLE
org.elasticsearch.xpack.esql.querydsl.query.SingleValueQueryTests.testNotMatchSome fails

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#105918]
### CI Link

https://gradle-enterprise.elastic.co/s/4s2zmu3ptejvi

### Repro line

./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.querydsl.query.SingleValueQueryTests.testNotMatchSome {p0=StandardSetup[fieldType=float, multivaluedField=true, empty=false, count=100]}" -Dtests.seed=12D140223DEBBFA8 -Dtests.locale=he -Dtests.timezone=Africa/Ceuta -Druntime.java=21

### Does it reproduce?

Yes

### Applicable branches

main, 8.13

### Failure excerpt

```
org.elasticsearch.xpack.esql.querydsl.query.SingleValueQueryTests > testNotMatchSome {p0=StandardSetup[fieldType=float, multivaluedField=true, empty=false, count=100]} FAILED
--
  | java.lang.AssertionError:
  | Expected: <0>
  | but: was <2>
  | at __randomizedtesting.SeedInfo.seed([12D140223DEBBFA8:EBC472399B2907A8]:0)
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
  | at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2119)
  | at org.elasticsearch.xpack.esql.querydsl.query.SingleValueQueryTests$StandardSetup.assertStats(SingleValueQueryTests.java:316)
  | at org.elasticsearch.xpack.esql.querydsl.query.SingleValueQueryTests.testCase(SingleValueQueryTests.java:218)
  | at org.elasticsearch.xpack.esql.querydsl.query.SingleValueQueryTests.testNotMatchSome(SingleValueQueryTests.java:142)
```

**Comment by benwtrent** [comment]
There are many other repo lines with various other inputs that cause this test to fail, but I didn't want to copy 20+ of them. 

Seems to happen on any `fieldType` & `empty` true or false.
