### ISSUE TITLE
NPE when used get api with specified preference _shards 

### ISSUE THREAD

**Issue by cfangpp** [elastic/elasticsearch#105942]
### Elasticsearch Version

7.6.2

### Java Version

Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

### OS Version

Linux

### Problem Description

I just used _get api to get one doc with preference _shards:1, it's response null_pointer_exception to me, maybe response not found more friendly.

below is response result.

{
    "error": {
        "root_cause": [
            {
                "type": "null_pointer_exception",
                "reason": null
            }
        ],
        "type": "null_pointer_exception",
        "reason": null
    },
    "status": 500
}

### Steps to Reproduce

1. POST /test_index/_doc
{"level": "INFO", "m": "xxx"}
2. GET test_index/_doc/XzqkDY4B7JdxVhZZd4-x?preference=_shards:1

### Logs (if relevant)

[2024-03-05T16:14:22,925][WARN ][r.suppressed             ] [fangchaoqun.local] path: /lumberjack_optimize_v3/_doc/XzqkDY4B7JdxVhZZd4-x, params: {preference=_shards:1, index=lumberjack_optimize_v3, id=XzqkDY4B7JdxVhZZd4-x}
org.elasticsearch.transport.RemoteTransportException: [fangchaoqun.local][127.0.0.1:9300][indices:data/read/get[s]]
Caused by: java.lang.NullPointerException
	at org.elasticsearch.action.get.TransportGetAction.asyncShardOperation(TransportGetAction.java:82) ~[elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.action.get.TransportGetAction.asyncShardOperation(TransportGetAction.java:45) ~[elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:289) ~[elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:282) ~[elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:257) [x-pack-security-7.6.2.jar:7.6.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:315) [x-pack-security-7.6.2.jar:7.6.2]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) [elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:756) [elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.transport.TransportService.access$100(TransportService.java:74) [elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.transport.TransportService$3.sendRequest(TransportService.java:127) [elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:702) [elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor.sendWithUser(SecurityServerTransportInterceptor.java:162) [x-pack-security-7.6.2.jar:7.6.2]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor.access$300(SecurityServerTransportInterceptor.java:53) [x-pack-security-7.6.2.jar:7.6.2]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$1.sendRequest(SecurityServerTransportInterceptor.java:129) [x-pack-security-7.6.2.jar:7.6.2]
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:616) [elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:583) [elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.start(TransportSingleShardAction.java:178) [elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction.doExecute(TransportSingleShardAction.java:103) [elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction.doExecute(TransportSingleShardAction.java:62) [elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:153) [elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.apply(SecurityActionFilter.java:123) [x-pack-security-7.6.2.jar:7.6.2]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:151) [elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:129) [elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:64) [elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:94) [elasticsearch-7.6.2.jar:7.6.2]
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:83) [elasticsearch-7.6.2.jar:7.6.2]

**Comment by DaveCTurner** [comment]
Thank you very much for your interest in Elasticsearch. Unfortunately the issue you have reported relates to Elasticsearch version 7.6.2 which is very old and has passed [end-of-life](https://www.elastic.co/support/eol). We will not investigate issues related to unsupported versions here on Github, so I am closing this to indicate that no action is needed from the Elasticsearch development team. It's possible that you will find a volunteer to help you with this issue on the [community forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6), but our strong recommendation would be to upgrade to a supported version of Elasticsearch as a matter of some urgency. If you can reproduce your issue on a supported version then please open a fresh bug report.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.
