### ISSUE TITLE
NoNodeAvailableException: None of the configured nodes are available: []

### ISSUE THREAD

**Issue by jeffreyji666** [elastic/elasticsearch#10603]
I build a es cluster with 2 nodes on EC2. and they are accessible by 9200 and 9300 port. I even do the telnet test on 9300 port, it is ok.

and I write the following code:

> elastic.host=172.31.10.168:9300,172.31.10.169:9300

> Map<String, String> params = new HashMap<String, String>();
        params.put("cluster.name", "test");
        Settings settings = ImmutableSettings.settingsBuilder().put(params).build();
        client = new TransportClient(settings);
        String[] hosts = Config.getString("elastic.host").split(",");
        for (String host : hosts) {
            String[] hp = host.split(":");
            if (hp.length != 2) {
                continue;
            }
            client.addTransportAddress(new InetSocketTransportAddress(hp[0], Integer.valueOf(hp[1])));
        }

but when I do a query, error happen as follows:
> org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:279)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:198)
	at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:106)
	at org.elasticsearch.client.support.AbstractClient.count(AbstractClient.java:379)
	at org.elasticsearch.client.transport.TransportClient.count(TransportClient.java:396)
	at org.elasticsearch.action.count.CountRequestBuilder.doExecute(CountRequestBuilder.java:146)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65)

and my es config is as follows:

>
cluster.name: test
node.name: ip-172-31-10-168.cn-north-1.compute.internal
node.max_local_storage_nodes: 1
node.master: true
node.data: false
index.mapper.dynamic: true
action.auto_create_index: true
action.disable_delete_all_indices: true
path.conf: /usr/local/etc/elasticsearch
path.data: /usr/local/var/data/elasticsearch
path.logs: /usr/local/var/log/elasticsearch
bootstrap.mlockall: true
http.port: 9200
gateway.expected_nodes: 1
discovery.zen.minimum_master_nodes: 1
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["172.31.10.168", "172.31.15.169"]
cloud.node.auto_attributes: true

anyone could please give me a suggestion?

**Comment by dadoonet** [comment]
A better place for questions like this is on the mailing list as it's more a configuration issue than a bug.
I think it's a security issue. If you are running your code outside AWS, you need to open 9300 port to the outside as well.

Closing as not an issue.
