### ISSUE TITLE
DataStreamTests.testIsFailureIndex failure

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#106073]
### CI Link

https://gradle-enterprise.elastic.co/s/s4p32xkgwckwi/console-log/task/:server:test?anchor=133&page=1

### Repro line

./gradlew ':server:test' --tests "org.elasticsearch.cluster.metadata.DataStreamTests.testIsFailureIndex" -Dtests.seed=4F2268643A971F5E -Dtests.locale=zh-Hant-HK -Dtests.timezone=Pacific/Port_Moresby -Druntime.java=21

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

  2> java.lang.AssertionError	
        at __randomizedtesting.SeedInfo.seed([4F2268643A971F5E:D6EB76D19F4F81F2]:0)	
        at org.elasticsearch.cluster.metadata.DataStream.<init>(DataStream.java:210)	
        at org.elasticsearch.cluster.metadata.DataStreamTests.testIsFailureIndex(DataStreamTests.java:1925)

**Comment by rjernst** [comment]
Note this failed on a branch PR, but reproduces on main.
