### ISSUE TITLE
Failure to recover shards after power outage

### ISSUE THREAD

**Issue by WellingR** [elastic/elasticsearch#10606]
We have ElasticSearch running on a single node. After a power outage, some of the shards could not be recovered. The log was filled with occurences of the log messages below.

Removing the *.recovering files in the elasticsearch data directories and restarting ElasticSearch fixed the problem.

I would be nice if ElasticSearch would ignore the corrupt data, and recover as much as is possible.

    [2015-01-24 23:13:49,683][WARN ][indices.cluster          ] [synergia-nat3] [adsb-tracks-historic-2015-01-24][0] failed to start shard
    org.elasticsearch.index.gateway.IndexShardGatewayRecoveryException: [adsb-tracks-historic-2015-01-24][0] failed to recover shard
    	at org.elasticsearch.index.gateway.local.LocalIndexShardGateway.recover(LocalIndexShardGateway.java:287)
    	at org.elasticsearch.index.gateway.IndexShardGatewayService$1.run(IndexShardGatewayService.java:132)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    	at java.lang.Thread.run(Unknown Source)
    Caused by: org.elasticsearch.index.translog.TranslogCorruptedException: translog corruption while reading from stream
    	at org.elasticsearch.index.translog.ChecksummedTranslogStream.read(ChecksummedTranslogStream.java:70)
    	at org.elasticsearch.index.gateway.local.LocalIndexShardGateway.recover(LocalIndexShardGateway.java:257)
    	... 4 more
    Caused by: java.io.EOFException
    	at org.elasticsearch.common.io.stream.InputStreamStreamInput.readBytes(InputStreamStreamInput.java:53)
    	at org.elasticsearch.index.translog.BufferedChecksumStreamInput.readBytes(BufferedChecksumStreamInput.java:55)
    	at org.elasticsearch.common.io.stream.StreamInput.readBytesReference(StreamInput.java:86)
    	at org.elasticsearch.common.io.stream.StreamInput.readBytesReference(StreamInput.java:74)
    	at org.elasticsearch.index.translog.Translog$Create.readFrom(Translog.java:353)
    	at org.elasticsearch.index.translog.ChecksummedTranslogStream.read(ChecksummedTranslogStream.java:68)
    	... 5 more
    [2015-01-24 23:13:49,715][WARN ][cluster.action.shard     ] [synergia-nat3] [adsb-tracks-historic-2015-01-24][0] sending failed shard for [adsb-tracks-historic-2015-01-24][0], node[44Mul_1jQMyvxBZOtrbJSQ], [P], s[INITIALIZING], indexUUID [pxoE803TSFa5YMDEdB3a1g], reason [Failed to start shard, message [IndexShardGatewayRecoveryException[[adsb-tracks-historic-2015-01-24][0] failed to recover shard]; nested: TranslogCorruptedException[translog corruption while reading from stream]; nested: EOFException; ]]
    [2015-01-24 23:13:49,715][WARN ][cluster.action.shard     ] [synergia-nat3] [adsb-tracks-historic-2015-01-24][0] received shard failed for [adsb-tracks-historic-2015-01-24][0], node[44Mul_1jQMyvxBZOtrbJSQ], [P], s[INITIALIZING], indexUUID [pxoE803TSFa5YMDEdB3a1g], reason [Failed to start shard, message [IndexShardGatewayRecoveryException[[adsb-tracks-historic-2015-01-24][0] failed to recover shard]; nested: TranslogCorruptedException[translog corruption while reading from stream]; nested: EOFException; ]]

This issue was originally discovered on ElasticSearch 1.4.1 however we have also seen this issue for 1.4.4 and 1.5.0

**Comment by mikemccand** [comment]
Hmm, I think https://github.com/elastic/elasticsearch/pull/9797 should have
fixed this as of 1.5.0.  Are you sure you see the same problem in 1.5.0?

Mike McCandless

**Comment by WellingR** [comment]
I will try to reproduce the issue again in 1.5.0

**Comment by WellingR** [comment]
I did quite a lot of tries today to reproduce the issue on 1.5.0, however I could not reproduce the problem. So it no longer seems to occur for ElasticSearch 1.5.0

**Comment by bleskes** [comment]
cool. Thx @WellingR  for trying. PS - use 1.5.1 if you can. It has an important fix to the relocation code.

**Comment by mseneby** [comment]
I have exact problem: power outage happened on all nodes and elastic search never recovered back;
this is the typical exceptions:

[2016-03-28 13:59:04,464][WARN ][cluster.action.shard     ] [Ahab] [tower][3] received shard failed for [tower][3], node[VhLi7qJNRhe6qr_pEP6Vpw], [P], v[596], s[INITIALIZING], a[id=RTJb9YYrRQeY0TLi9wBuSQ], unassigned_info[[reason=ALLOCATION_FAILED], at[2016-03-28T20:58:57.865Z], details[failed recovery, failure IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to recover from translog]; nested: EngineException[failed to recover from translog]; nested: ElasticsearchException[unexpected exception reading from translog snapshot of /livetest/elasticsearch-2.2.0/data/opersearch-m4/nodes/0/indices/tower/3/translog/translog-82.tlog]; nested: EOFException[read past EOF. pos [7319569] length: [4] end: [7319569]]; ]], indexUUID [wH16M_qLRyy3f-a1GpFbGQ], message [failed recovery], failure [IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to recover from translog]; nested: EngineException[failed to recover from translog]; nested: ElasticsearchException[unexpected exception reading from translog snapshot of /livetest/elasticsearch-2.2.0/data/opersearch-m4/nodes/0/indices/tower/3/translog/translog-82.tlog]; nested: EOFException[read past EOF. pos [7319569] length: [4] end: [7319569]]; ]
[tower][[tower][3]] IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to recover from translog]; nested: EngineException[failed to recover from translog]; nested: ElasticsearchException[unexpected exception reading from translog snapshot of /livetest/elasticsearch-2.2.0/data/opersearch-m4/nodes/0/indices/tower/3/translog/translog-82.tlog]; nested: EOFException[read past EOF. pos [7319569] length: [4] end: [7319569]];
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:254)
        at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
        at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: [tower][[tower][3]] EngineCreationFailureException[failed to recover from translog]; nested: EngineException[failed to recover from translog]; nested: ElasticsearchException[unexpected exception reading from translog snapshot of /livetest/elasticsearch-2.2.0/data/opersearch-m4/nodes/0/indices/tower/3/translog/translog-82.tlog]; nested: EOFException[read past EOF. pos [7319569] length: [4] end: [7319569]];
        at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:178)
        at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
        at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1450)
        at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1434)
        at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:925)
        at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:897)
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:245)
        ... 5 more
Caused by: [tower][[tower][3]] EngineException[failed to recover from translog]; nested: ElasticsearchException[unexpected exception reading from translog snapshot of /livetest/elasticsearch-2.2.0/data/opersearch-m4/nodes/0/indices/tower/3/translog/translog-82.tlog]; nested: EOFException[read past EOF. pos [7319569] length: [4] end: [7319569]];
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:254)
        at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:175)
        ... 11 more
Caused by: ElasticsearchException[unexpected exception reading from translog snapshot of /livetest/elasticsearch-2.2.0/data/opersearch-m4/nodes/0/indices/tower/3/translog/translog-82.tlog]; nested: EOFException[read past EOF. pos [7319569] length: [4] end: [7319569]];
        at org.elasticsearch.index.translog.TranslogReader.readSize(TranslogReader.java:102)
        at org.elasticsearch.index.translog.TranslogReader.access$000(TranslogReader.java:46)
        at org.elasticsearch.index.translog.TranslogReader$ReaderSnapshot.readOperation(TranslogReader.java:297)
        at org.elasticsearch.index.translog.TranslogReader$ReaderSnapshot.next(TranslogReader.java:290)
        at org.elasticsearch.index.translog.MultiSnapshot.next(MultiSnapshot.java:70)
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:240)
        ... 12 more
Caused by: java.io.EOFException: read past EOF. pos [7319569] length: [4] end: [7319569]
        at org.elasticsearch.common.io.Channels.readFromFileChannelWithEofException(Channels.java:102)
        at org.elasticsearch.index.translog.ImmutableTranslogReader.readBytes(ImmutableTranslogReader.java:84)
        at org.elasticsearch.index.translog.TranslogReader.readSize(TranslogReader.java:91)
        ... 17 more

It was heavily writing to nodes during outage.

**Comment by bleskes** [comment]
@mseneby these are indication of translog truncations. What type FS/OS are your running on? I also suspect it's a 2.2.0 ES , right? do you still have the files?
