### ISSUE TITLE
Rolling over a data stream alias causes a null pointer exception

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#106137]
When a executing a rollover operation on an alias, if the alias is a data stream alias the operation will fail with a null pointer exception.

Affected versions: Tested on 8.12.0

Reproduction:

```
PUT /_index_template/jimmy-ds-test
{
  "index_patterns": ["jimmy-ds-*"],
  "data_stream": {},
  "template": {
    "aliases": {
      "ds-alias": {
        "is_write_index": true
      }
    }, 
    "settings": {
      "number_of_shards": 1
    },
    "mappings": {
      "properties": {
        "idNumber": {
          "type": "long"
        },
        "@timestamp": {
          "type": "date"
        }
      }
    }
  }
}

PUT /jimmy-ds-test-1/_create/1
{
  "@timestamp": "2024-03-08",
  "idNumber": 4
}

POST /ds-alias/_rollover?error_trace
```

Results in the following exception message:
```
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": """Cannot invoke "org.elasticsearch.cluster.metadata.AliasMetadata.writeIndex()" because "aliasMetadata" is null""",
        "stack_trace": """org.elasticsearch.ElasticsearchException$1: Cannot invoke "org.elasticsearch.cluster.metadata.AliasMetadata.writeIndex()" because "aliasMetadata" is null
	at org.elasticsearch.server@8.12.0/org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:673)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:601)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.rest.RestResponse.build(RestResponse.java:180)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:140)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:111)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:55)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.rest.action.RestCancellableNodeClient$1.onFailure(RestCancellableNodeClient.java:96)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.tasks.TaskManager$1.onFailure(TaskManager.java:214)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:27)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:39)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:27)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:27)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onFailure(ActionListenerImplementations.java:308)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$2(TransportMasterNodeAction.java:233)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.acceptException(ActionListenerImplementations.java:186)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onFailure(ActionListenerImplementations.java:191)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.admin.indices.rollover.TransportRolloverAction$RolloverTask.onFailure(TransportRolloverAction.java:251)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.cluster.service.MasterService$ExecutionResult.notifyFailure(MasterService.java:975)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.cluster.service.MasterService$ExecutionResult.onClusterStateUnchanged(MasterService.java:938)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:245)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1626)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.ActionListener.run(ActionListener.java:386)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.run(MasterService.java:1623)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.cluster.service.MasterService$5.lambda$doRun$0(MasterService.java:1237)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.ActionListener.run(ActionListener.java:386)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.cluster.service.MasterService$5.doRun(MasterService.java:1216)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "org.elasticsearch.cluster.metadata.AliasMetadata.writeIndex()" because "aliasMetadata" is null
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.admin.indices.rollover.MetadataRolloverService.rolloverAlias(MetadataRolloverService.java:202)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.admin.indices.rollover.MetadataRolloverService.rolloverClusterState(MetadataRolloverService.java:117)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.admin.indices.rollover.TransportRolloverAction$RolloverExecutor.executeTask(TransportRolloverAction.java:332)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.admin.indices.rollover.TransportRolloverAction$RolloverExecutor.execute(TransportRolloverAction.java:268)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1039)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1004)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:232)
	... 11 more
"""
      }
    ],
    "type": "null_pointer_exception",
    "reason": """Cannot invoke "org.elasticsearch.cluster.metadata.AliasMetadata.writeIndex()" because "aliasMetadata" is null""",
    "stack_trace": """java.lang.NullPointerException: Cannot invoke "org.elasticsearch.cluster.metadata.AliasMetadata.writeIndex()" because "aliasMetadata" is null
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.admin.indices.rollover.MetadataRolloverService.rolloverAlias(MetadataRolloverService.java:202)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.admin.indices.rollover.MetadataRolloverService.rolloverClusterState(MetadataRolloverService.java:117)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.admin.indices.rollover.TransportRolloverAction$RolloverExecutor.executeTask(TransportRolloverAction.java:332)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.admin.indices.rollover.TransportRolloverAction$RolloverExecutor.execute(TransportRolloverAction.java:268)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1039)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1004)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:232)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1626)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.ActionListener.run(ActionListener.java:386)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.run(MasterService.java:1623)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.cluster.service.MasterService$5.lambda$doRun$0(MasterService.java:1237)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.action.ActionListener.run(ActionListener.java:386)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.cluster.service.MasterService$5.doRun(MasterService.java:1216)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
	at org.elasticsearch.server@8.12.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
"""
  },
  "status": 500
}
```

**Comment by howardhuanghua** [comment]
Hi @jbaiera , I am trying to fix this NPE issue.

**Comment by limotova** [comment]
@howardhuanghua are you still looking into this? I was working with code close to this area and I think I know what's going on.

First of all, rolling over the data stream works properly, and the path taken for rolling over the alias vs the data stream is pretty similar until [this point](https://github.com/elastic/elasticsearch/blob/6d040d9bea355b1b8f97e2bec41747f35f1ad695/server/src/main/java/org/elasticsearch/action/admin/indices/rollover/MetadataRolloverService.java#L117)

The null pointer exception happens within the call to `rolloverAlias(...)` around [here](https://github.com/elastic/elasticsearch/blob/6d040d9bea355b1b8f97e2bec41747f35f1ad695/server/src/main/java/org/elasticsearch/action/admin/indices/rollover/MetadataRolloverService.java#L201) with the issue specifically being that, while we have the correct `writeIndex` (the backing index of the ds), its `aliases` map is empty (so when `writeIndex.getAliases().get(alias.getName())` is called in the following line, the `get()` portion returns null)

So I looked into what happens when the index is being created in the first place to see why its aliases map is empty, and saw that IndexMetadata for indices belonging to data streams [intentionally](https://github.com/elastic/elasticsearch/blob/dce8a6b77f61ede59d23af10b45e702048c9d0f7/server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java#L672) don't have links to the parent data stream's aliases
(I can also confirm that the DataStreamMetadata inside Metadata's `customs` has a reference to the alias there)

Additionally, back in the `rolloverAlias(...)` method `aliasMetadata` is only used to determine if the alias has a [write index](https://github.com/elastic/elasticsearch/blob/6d040d9bea355b1b8f97e2bec41747f35f1ad695/server/src/main/java/org/elasticsearch/action/admin/indices/rollover/MetadataRolloverService.java#L203) and to determine if the alias [is hidden](https://github.com/elastic/elasticsearch/blob/6d040d9bea355b1b8f97e2bec41747f35f1ad695/server/src/main/java/org/elasticsearch/action/admin/indices/rollover/MetadataRolloverService.java#L224), both of which I think can be determined from the `IndexAbstraction.Alias alias` that is being passed into this method. 
So then I tested out what would happen if you used `alias` instead of `aliasMetadata`, but then it actually fails further down the line [here](https://github.com/elastic/elasticsearch/blob/b6f876f32a270e7240117bdc6cd46d01c563f549/server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexAliasesService.java#L245-L249)

So since it seems that `rolloverAlias(...)` was designed specifically for aliases to indices, I'm thinking the fix might be to change the [rollover target](https://github.com/elastic/elasticsearch/blob/6d040d9bea355b1b8f97e2bec41747f35f1ad695/server/src/main/java/org/elasticsearch/action/admin/indices/rollover/MetadataRolloverService.java#L106) (where we split between over aliases vs data streams) to the data stream instead of the alias so we go into the `rolloverDataStream(...)` path instead.

**Comment by howardhuanghua** [comment]
@limotova thanks for the detail analysis. Since you've already got the root cause, would you please help to fix it directly? I haven't started yet.
