### ISSUE TITLE
[CI] SmokeTestWatcherWithSecurityClientYamlTestSuiteIT test {yaml=watcher/.../.../...} failing

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#106192]
**Build scan:**
https://gradle-enterprise.elastic.co/s/cmf3ig675uytq/tests/:x-pack:plugin:watcher:qa:with-security:yamlRestTest/org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityClientYamlTestSuiteIT/test%20%7Byaml=watcher%2Fput_watch%2F80_put_get_watch_with_passwords%2FTest%20getting%20a%20watch%20does%20not%20contain%20the%20original%20password%7D

**Reproduction line:**
```
./gradlew ':x-pack:plugin:watcher:qa:with-security:yamlRestTest' --tests "org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityClientYamlTestSuiteIT.test {yaml=watcher/put_watch/80_put_get_watch_with_passwords/Test getting a watch does not contain the original password}" -Dtests.seed=5D57F279B63D2D41 -Dtests.locale=ar-LY -Dtests.timezone=Antarctica/Rothera -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
[Failure dashboard for `org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityClientYamlTestSuiteIT#test {yaml=watcher/put_watch/80_put_get_watch_with_passwords/Test getting a watch does not contain the original password}`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test%20%7Byaml%3Dwatcher/put_watch/80_put_get_watch_with_passwords/Test%20getting%20a%20watch%20does%20not%20contain%20the%20original%20password%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityClientYamlTestSuiteIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <0>
     but: was <1>

  at __randomizedtesting.SeedInfo.seed([5D57F279B63D2D41:D503CDA318C140B9]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
  at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2130)
  at org.elasticsearch.xpack.watcher.WatcherRestTestCase.deleteAllWatcherData(WatcherRestTestCase.java:106)
  at org.elasticsearch.xpack.watcher.WatcherYamlSuiteTestCase.stopWatcher(WatcherYamlSuiteTestCase.java:100)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by idegtiarenko** [comment]
There are number of tests in the watcher directory that are flaky now:
* [test {yaml=watcher/security/20_test_run_as_execute_watch/Test watch index action requires permission to write to an index}](https://gradle-enterprise.elastic.co/s/cmf3ig675uytq/tests/task/:x-pack:plugin:watcher:qa:with-security:yamlRestTest/details/org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityClientYamlTestSuiteIT/test%20%7Byaml=watcher%2Fsecurity%2F20_test_run_as_execute_watch%2FTest%20watch%20index%20action%20requires%20permission%20to%20write%20to%20an%20index%7D?top-execution=1)
* [test {yaml=watcher/put_watch/80_put_get_watch_with_passwords/Test getting a watch does not contain the original password}](https://gradle-enterprise.elastic.co/s/cmf3ig675uytq/tests/task/:x-pack:plugin:watcher:qa:with-security:yamlRestTest/details/org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityClientYamlTestSuiteIT/test%20%7Byaml=watcher%2Fput_watch%2F80_put_get_watch_with_passwords%2FTest%20getting%20a%20watch%20does%20not%20contain%20the%20original%20password%7D?top-execution=1)
* [test {yaml=watcher/activate_watch/10_basic/Non existent watch returns 404}](https://gradle-enterprise.elastic.co/s/urg33txmrewku/tests/task/:x-pack:plugin:watcher:qa:with-security:yamlRestTest/details/org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityClientYamlTestSuiteIT/test%20%7Byaml=watcher%2Factivate_watch%2F10_basic%2FNon%20existent%20watch%20returns%20404%7D?top-execution=1)
* [test {yaml=watcher/get_watch/20_missing/Test get watch api with missing watch on existing index}](https://gradle-enterprise.elastic.co/s/urg33txmrewku/tests/task/:x-pack:plugin:watcher:qa:with-security:yamlRestTest/details/org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityClientYamlTestSuiteIT/test%20%7Byaml=watcher%2Fget_watch%2F20_missing%2FTest%20get%20watch%20api%20with%20missing%20watch%20on%20existing%20index%7D?top-execution=1)
* [test {yaml=watcher/get_watch/30_with_chain_input/Test get watch api with chained input and basic auth}](https://gradle-enterprise.elastic.co/s/6hsaiety7ao4e/tests/task/:x-pack:plugin:watcher:qa:with-security:yamlRestTest/details/org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityClientYamlTestSuiteIT/test%20%7Byaml=watcher%2Fget_watch%2F30_with_chain_input%2FTest%20get%20watch%20api%20with%20chained%20input%20and%20basic%20auth%7D?top-execution=1)
* [test {yaml=watcher/put_watch/10_basic/Test put watch api}](https://gradle-enterprise.elastic.co/s/6hsaiety7ao4e/tests/task/:x-pack:plugin:watcher:qa:with-security:yamlRestTest/details/org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityClientYamlTestSuiteIT/test%20%7Byaml=watcher%2Fput_watch%2F10_basic%2FTest%20put%20watch%20api%7D?top-execution=1)

**Comment by joegallo** [comment]
This is due to https://github.com/elastic/elasticsearch/pull/106141, which was intended to give us more information for tracking down this issue -- and now we've got the more information, I'd say. 😉

I'll revert that PR and we think about what it all means.

**Comment by joegallo** [comment]
Related to https://github.com/elastic/elasticsearch/issues/65547.

**Comment by joegallo** [comment]
Alright, I reverted #106141, so I think we can close this in favor of continuing to track #65547.
