### ISSUE TITLE
Fix leaking log-level set on root logger in LoggerTests

### ISSUE THREAD

**Issue by pmpailis** [elastic/elasticsearch#106250]
### CI Link

https://gradle-enterprise.elastic.co/s/ssqi5r5klvhsm

### Repro line

./gradlew ':server:test' --tests "org.elasticsearch.snapshots.SnapshotResiliencyTests*" -Druntime.java=21  -Dtests.es.logger.level=DEBUG

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

```org.elasticsearch.snapshots.SnapshotResiliencyTests > testIllegalArgumentExceptionLogging FAILED
    java.lang.AssertionError: expected to see INFO log but did not
    Expected: <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([782F1BB9840950FE:32EBB1FE53CD0BB8]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.elasticsearch.test.MockLogAppender$SeenEventExpectation.assertMatched(MockLogAppender.java:127)
```

The following 4 tests started failing yesterday in `SnapshotResiliencyTests` due to an incorrectly set log-level.  
```
Tests with failures:
 - org.elasticsearch.snapshots.SnapshotResiliencyTests.testIndexNotFoundExceptionLogging
 - org.elasticsearch.snapshots.SnapshotResiliencyTests.testFullSnapshotUnassignedShards
 - org.elasticsearch.snapshots.SnapshotResiliencyTests.testIllegalArgumentExceptionLogging
 - org.elasticsearch.snapshots.SnapshotResiliencyTests.testSnapshotNameAlreadyInUseExceptionLogging
 ```

 It seems that in this [PR](https://github.com/elastic/elasticsearch/pull/105020) we updated the log-level of the[ root logger](https://github.com/elastic/elasticsearch/blob/main/server/src/test/java/org/elasticsearch/common/logging/LoggersTests.java#L88) as part of the tests, so if it happens that the `SnapshotResiliencyTests` are executed **after** the `LoggersTests`, the log-level for the `SnapshotsService` logger will be set to debug causing the failures above.  

We should probably reset the log-level after the tests, as we do in `InternalEngineTests#testMergeThreadLogging`  for example

**Comment by pmpailis** [comment]
There is already a fix for the tests in the description in this [PR](https://github.com/elastic/elasticsearch/pull/106238), but this could potentially manifest in other tests as well.
