### ISSUE TITLE
ES having trouble parsing 

### ISSUE THREAD

**Issue by vadim-moz** [elastic/elasticsearch#10636]
We have a troubles with some messages going to ES. It looks like messages are silently dropped from Kibana. We would expect JSON message, or at very least, a unparsed message with the proper tag.

command:
```
logger -p notice "{\"myname\":\"vadim\", \"date\":\"`date`\",\"foo\":[0,1]}"
```

Stack trace in ES log (/var/log/elasticsearch/mozstash.log):
```
[2015-04-16 18:00:08,776][DEBUG][action.bulk              ] [mozstash1404-ubuntu-1404] [logstash-2015.04.16][3] failed to execute bulk item (index) index {[logstash-2015.04.16][logs][dlshi6ycRJmp1TR46Icolg], source[{"@timestamp":"2015-04-16T18:00:08.798Z","tier":"_default","hostname":"emitter1204-ubuntu-1204","severity":"notice","service":"vagrant","collector":"collector-ubuntu-1404","message":"{\"myname\":\"vadim\", \"date\":\"Thu Apr 16 18:00:08 UTC 2015\",\"foo\":[0,1]}","@version":"1","host":"10.85.25.25:55269","myname":"vadim","date":"Thu Apr 16 18:00:08 UTC 2015","foo":[0,1]}]}
org.elasticsearch.index.mapper.MapperParsingException: object mapping [foo] trying to serialize a value with no field associated with it, current value [0]
	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:702)
	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:497)
	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:706)
	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeNonDynamicArray(ObjectMapper.java:695)
	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeArray(ObjectMapper.java:604)
	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:489)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:544)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:493)
	at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:438)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:432)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:149)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:515)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:422)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Another example:
```
logger -p notice "{\"myname\":\"vadim\", \"date\":\"`date`\",\"foo\":{\"bar\":\"baz\"}}"
```

Stack trace:
```
[2015-04-16 18:07:44,757][DEBUG][action.bulk              ] [mozstash1404-ubuntu-1404] [logstash-2015.04.16][3] failed to execute bulk item (index) index {[logstash-2015.04.16][logs][NkUpFrrzTwqMRnPRvE2RYg], source[{"@timestamp":"2015-04-16T18:07:44.898Z","tier":"_default","hostname":"emitter1204-ubuntu-1204","severity":"notice","service":"vagrant","collector":"collector-ubuntu-1404","message":"{\"myname\":\"vadim\", \"date\":\"Thu Apr 16 18:07:44 UTC 2015\",\"foo\":{\"bar\":\"baz\"}}","@version":"1","host":"10.85.25.25:55269","myname":"vadim","date":"Thu Apr 16 18:07:44 UTC 2015","foo":{"bar":"baz"}}]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [foo.bar]
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:410)
	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:706)
	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:497)
	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:554)
	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:487)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:544)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:493)
	at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:438)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:432)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:149)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:515)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:422)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "baz"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:441)
	at java.lang.Long.parseLong(Long.java:483)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.longValue(AbstractXContentParser.java:145)
	at org.elasticsearch.index.mapper.core.LongFieldMapper.innerParseCreateField(LongFieldMapper.java:300)
	at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:236)
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:400)
	... 14 more
```

Elastic version info:
```
# curl -XGET 'localhost:9200'
{
  "status" : 200,
  "name" : "mozstash1404-ubuntu-1404",
  "cluster_name" : "mozstash",
  "version" : {
    "number" : "1.5.0",
    "build_hash" : "544816042d40151d3ce4ba4f95399d7860dc2e92",
    "build_timestamp" : "2015-03-23T14:30:58Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

Thank you for your help

**Comment by clintongormley** [comment]
Hi @vadim-moz 

It looks like you are relying on dynamic mapping to introduce new fields, and you are sending fields with different datatypes.  For instance:

    object mapping [foo] trying to serialize a value with no field associated with it, current value [0]

Field `foo` has already been introduced into your mapping as type `object`, so indexing `foo` as a number won't work.

Similarly:

    ... failed to parse [foo.bar]
    Caused by: java.lang.NumberFormatException: For input string: "baz"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)

`foo.bar` has already been introduced as a number (probably a `long`), but now you're trying to index a `string`.

You can't change the data type of an existing field.  Once a field has been added, it's `type` is set forever more.

**Comment by vadim-moz** [comment]
This is possible, however I am confused: we are using Logstash for log storage. It means unpredictable (application defined fields, which are changed as log objects change). Do we have wrong expectations?

**Comment by clintongormley** [comment]
@vadim-moz not quite sure what you mean, but if you are sending logstash fields containing different data types, then those same mixed data types are going to be forwarded to Elasticsearch.  Logstash does have the ability to (eg) change a string like `"10"` to the number `10`.

If you have no control over the data type in field `foo`, then you can set it to type `object` and set `enabled: false`.  Then it will just ignore everything in that field (meaning you can't search on it either).  Otherwise you have to find some way of rewriting `foo` based on the data type

**Comment by vadim-moz** [comment]
Thank you very much. Let me clarify my question:

I am looking for implementing logging facility for big application:
```rb
log.info({description: 'something', exception: ErrorObject, user: something, account: something})
```
Of course (and during lifecycle of application) available fields and their representation might change unpredictably. My goal was to convert it to reasonable schema-free json, and use logstash / kibana to interface it.

The naive approach obviously does not work (judging by your comments). So, for example, I might convert the example above in something like:
```json
{
  "timestamp": "2015-04-23",
  "pid": 2132131,
  "url": "https://github.com/my-repo",
  "data": {
     "description": "something",
     "exception": {
       "class": "SuperError",
       "message": "error! error!",
       "backtrace": [
          "loc1",
          "loc2",
       ]
     },
     "user": "John Smith",
     "accoount": 123456
  }
}
```
(hope, it is valid json).

The big question: will I be able send tomorrow something like:
```json
{
  "timestamp": "2015-04-24",
  "pid": 5697865,
  "data": {
     "description": "something else",
     "user": {
        "first-name": "John",
        "last-name": "Smith"
     },
     "accoount": "123456-pr"
  }
}
```
(I do not mean to automatically identify that it is the same `John Smith`, I need just to get these messages stored in ES.)

Thank you very much,
/vadim

**Comment by clintongormley** [comment]
HI @vadim-moz 

> The big question: will I be able send tomorrow something like:

No you won't.  The `data.user` field from the first example is already  a `string`, but in the second example you're sending it as on `object`.   Unless....

If you set the `data` object to `enabled: false` then it will ignore everything under it. The JSON will still be stored in the `_source` field, but it won't try to parse or index it.  This also means that you can't search for anything in the `data` field.
