### ISSUE TITLE
[CI] DownsampleActionSingleNodeTests testCannotDownsampleWhileOtherDownsampleInProgress failing

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#106403]
**Build scan:**
https://gradle-enterprise.elastic.co/s/hjehcw3ak4ets/tests/:x-pack:plugin:downsample:test/org.elasticsearch.xpack.downsample.DownsampleActionSingleNodeTests/testCannotDownsampleWhileOtherDownsampleInProgress

**Reproduction line:**
```
./gradlew ':x-pack:plugin:downsample:test' --tests "org.elasticsearch.xpack.downsample.DownsampleActionSingleNodeTests.testCannotDownsampleWhileOtherDownsampleInProgress" -Dtests.seed=8E5AEEE1E9924404 -Dtests.locale=zh-Hans-CN -Dtests.timezone=AST -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.downsample.DownsampleActionSingleNodeTests#testCannotDownsampleWhileOtherDownsampleInProgress`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testCannotDownsampleWhileOtherDownsampleInProgress'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.downsample.DownsampleActionSingleNodeTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.elasticsearch.ElasticsearchException: downsample task [downsample-downsample-ynbrxltcjhvoej-0-13d] failed

  at __randomizedtesting.SeedInfo.seed([8E5AEEE1E9924404:AE3519837F3E6A11]:0)
  at org.elasticsearch.xpack.downsample.TransportDownsampleAction$2.onResponse(TransportDownsampleAction.java:425)
  at org.elasticsearch.xpack.downsample.TransportDownsampleAction$2.onResponse(TransportDownsampleAction.java:417)
  at org.elasticsearch.persistent.PersistentTasksService$1.onNewClusterState(PersistentTasksService.java:213)
  at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onNewClusterState(ClusterStateObserver.java:379)
  at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.clusterChanged(ClusterStateObserver.java:230)
  at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListener(ClusterApplierService.java:560)
  at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:547)
  at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:505)
  at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:429)
  at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:917)
  at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:217)
  at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:183)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by martijnvg** [comment]
The cause of the downsampling failure: 

```
[2024-03-17T20:39:16,407][WARN ][o.e.p.AllocatedPersistentTask] [node_s_0] task [downsample-downsample-ynbrxltcjhvoej-0-13d] failed with an exception	
org.elasticsearch.xpack.downsample.DownsampleShardIndexerException: Downsampling task [downsample-downsample-ynbrxltcjhvoej-0-13d] on shard [ynbrxltcjhvoej][0] failed indexing [452]	
	at org.elasticsearch.xpack.downsample.DownsampleShardIndexer.execute(DownsampleShardIndexer.java:202) ~[main/:?]	
	at org.elasticsearch.xpack.downsample.DownsampleShardPersistentTaskExecutor$1.doRun(DownsampleShardPersistentTaskExecutor.java:220) ~[main/:?]	
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984) ~[elasticsearch-8.14.0-SNAPSHOT.jar:8.14.0-SNAPSHOT]	
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.14.0-SNAPSHOT.jar:8.14.0-SNAPSHOT]	
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]	
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
```

I think logging should here be improved, so that we can get insight how the indexing failed.

**Comment by martijnvg** [comment]
The reason that indexing failed is because the target index started to block writes:

```
[2024-03-17T20:39:16,345][ERROR][o.e.x.d.DownsampleShardIndexer] [node_s_0] Shard [[ynbrxltcjhvoej][0]] failed to populate downsample index. Failures: [{null=org.elasticsearch.cluster.block.ClusterBlockException: index [downsample-ynbrxltcjhvoej] blocked by: [FORBIDDEN/8/index write (api)];}]
```

**Comment by martijnvg** [comment]
Looking better at the test logs, it looks like the first downsample attempt completes successfully, but just after the persistent task completes, the duplicate downsample operations starts downsampling. Failing later, because the initial downsample operation made target index read only.  I think just before the downsample shard operation starts, a check should be added that checks whether the `index.downsample.status` has been set to `success`. There is a similar check at pre check in `TransportDownsampleAction`, but in this case that isn't enough.

```
[2024-03-17T20:39:16,127][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Downsampling task [downsample-downsample-ynbrxltcjhvoej-0-13d on shard [ynbrxltcjhvoej][0] started	
[2024-03-17T20:39:16,132][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Shard [ynbrxltcjhvoej][0] processed [1034] docs, created [452] downsample buckets	
[2024-03-17T20:39:16,215][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Shard [[ynbrxltcjhvoej][0]] successfully sent [1034], received source doc [452], indexed downsampled doc [452], failed [0], took [0s]	
[2024-03-17T20:39:16,216][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Downsampling task [downsample-downsample-ynbrxltcjhvoej-0-13d on shard [ynbrxltcjhvoej][0] completed	
[2024-03-17T20:39:16,236][INFO ][o.e.x.d.TransportDownsampleAction] [node_s_0] Downsampling task [downsample-downsample-ynbrxltcjhvoej-0-13d completed for shard [ynbrxltcjhvoej][0]	
[2024-03-17T20:39:16,236][INFO ][o.e.x.d.TransportDownsampleAction] [node_s_0] All downsampling tasks completed [1]	
[2024-03-17T20:39:16,329][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Downsampling task [downsample-downsample-ynbrxltcjhvoej-0-13d on shard [ynbrxltcjhvoej][0] started	
[2024-03-17T20:39:16,334][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Shard [ynbrxltcjhvoej][0] processed [1034] docs, created [452] downsample buckets	
[2024-03-17T20:39:16,345][ERROR][o.e.x.d.DownsampleShardIndexer] [node_s_0] Shard [[ynbrxltcjhvoej][0]] failed to populate downsample index. Failures: [{null=org.elasticsearch.cluster.block.ClusterBlockException: index [downsample-ynbrxltcjhvoej] blocked by: [FORBIDDEN/8/index write (api)];}]	
[2024-03-17T20:39:16,346][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Shard [[ynbrxltcjhvoej][0]] successfully sent [1034], received source doc [452], indexed downsampled doc [452], failed [452], took [0s]	
[2024-03-17T20:39:16,350][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Downsampling task [downsample-downsample-ynbrxltcjhvoej-0-13d] on shard [ynbrxltcjhvoej][0] failed indexing [452]	
````

**Comment by martijnvg** [comment]
No reported failures since the last 2 weeks, which was when #106563 was merged. I think that change stabilized this test.
