### ISSUE TITLE
[CI] SamlAuthenticationIT failing tests

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#106758]
Affected tests:
- testLoginWithWrongRealmFails
- testLoginUserWithAuthorizingRealm
- testLoginUserWithSamlRoleMapping

All fail due to an unexpected 503 response.

Couldn't reproduce with Java 17 (cannot build with Java 22 for some reason).

**Build scan:**
https://gradle-enterprise.elastic.co/s/zrzfpexlbpplu/tests/:x-pack:qa:saml-idp-tests:javaRestTest/org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT/testLoginUserWithAuthorizingRealm

**Reproduction line:**
```
./gradlew ':x-pack:qa:saml-idp-tests:javaRestTest' --tests "org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.testLoginUserWithAuthorizingRealm" -Dtests.seed=AB05D4214788494C -Dtests.locale=is-IS -Dtests.timezone=Africa/Lome -Druntime.java=22
```

**Applicable branches:**
7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT#testLoginUserWithAuthorizingRealm`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testLoginUserWithAuthorizingRealm'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: Unexpected HTTP Response status: HTTP/1.1 503 Service Unavailable
Expected: <200>
     but: was <503>

  at __randomizedtesting.SeedInfo.seed([AB05D4214788494C:F978DB5EE3253BF4]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:964)
  at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.assertHttpOk(SamlAuthenticationIT.java:441)
  at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.lambda$getIdpLoginPage$0(SamlAuthenticationIT.java:302)
  at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.execute(SamlAuthenticationIT.java:433)
  at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.getIdpLoginPage(SamlAuthenticationIT.java:301)
  at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.loginViaSaml(SamlAuthenticationIT.java:200)
  at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.testLoginUserWithAuthorizingRealm(SamlAuthenticationIT.java:180)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1570)

```

**Comment by breskeby** [comment]
seems they fail on 7.17. We probably should back port the rework we did on those fixtures on main

**Comment by alex-spies** [comment]
Also fails on `main`: https://gradle-enterprise.elastic.co/s/tbhii33whrunc

**Comment by alex-spies** [comment]
More 7.17 failures: https://gradle-enterprise.elastic.co/s/g5bdagsm2ceba

**Comment by mark-vieira** [comment]
This is failing multiple times a day on 7.17. I think the uptick is due to a bug we had where we weren't actually running these periodic tests on that branch correctly.

![image](https://github.com/elastic/elasticsearch/assets/4106672/bf181f2f-74f0-4db1-a817-aedc37b36941)

**Comment by breskeby** [comment]
They still fail on 7.17 but that must be unrelated to the refactoring to testcontainers as that hasn't been backported. I'll go ahead and mute those tests on 7.17

**Comment by jfreden** [comment]
Looks like this hasn't failed on main for several months and that it's muted on 7.17. 

>They still fail on 7.17 but that must be unrelated to the refactoring to testcontainers as that hasn't been backported. I'll go ahead and mute those tests on 7.17

Was the refactoring be backported? If it was, can we unmute the tests and close this issue? @breskeby

**Comment by breskeby** [comment]
That particular refactoring hasn't been back ported. I don't remember the details but some test container logic was incompatible. I'll revisit this and check if we could get that done somehow and get this issue finally resolved an all our active branches

**Comment by jfreden** [comment]
@breskeby were you able to check how much effort/if it's worth it to backport the changes to 7.17?

**Comment by slobodanadamovic** [comment]
Reopening because the tests are still muted on 7.17 branch.

**Comment by mattc58** [comment]
Closing this. It's only happening on `7.17` and we're not maintaining that beyond ultra critical security issues.
