### ISSUE TITLE
[CI] AzureBlobStoreRepositoryTests testSnapshotAndRestore failing

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#106749]
Didn't manage to run the test with Java 8; with Java 17, this does not reproduce for me.

**Build scan:**
https://gradle-enterprise.elastic.co/s/wjudszhpjwz2c/tests/:plugins:repository-azure:internalClusterTest/org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests/testSnapshotAndRestore

**Reproduction line:**
```
./gradlew ':plugins:repository-azure:internalClusterTest' --tests "org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests.testSnapshotAndRestore" -Dtests.seed=631A64F66941DE2 -Dtests.locale=ar-JO -Dtests.timezone=Mexico/BajaSur -Druntime.java=8
```

**Applicable branches:**
7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests#testSnapshotAndRestore`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testSnapshotAndRestore'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at __randomizedtesting.SeedInfo.seed([631A64F66941DE2]:0)
  at sun.net.httpserver.ServerImpl.requestCompleted(ServerImpl.java:937)
  at sun.net.httpserver.FixedLengthInputStream.readImpl(FixedLengthInputStream.java:63)
  at sun.net.httpserver.LeftOverInputStream.read(LeftOverInputStream.java:99)
  at java.io.FilterInputStream.read(FilterInputStream.java:107)
  at org.elasticsearch.core.internal.io.Streams.copy(Streams.java:46)
  at org.elasticsearch.core.internal.io.Streams.copy(Streams.java:80)
  at org.elasticsearch.common.io.Streams.readFully(Streams.java:243)
  at fixture.azure.AzureHttpHandler.handle(AzureHttpHandler.java:95)
  at org.elasticsearch.repositories.blobstore.ESMockAPIBasedRepositoryIntegTestCase$HttpStatsCollectorHandler.handle(ESMockAPIBasedRepositoryIntegTestCase.java:378)
  at org.elasticsearch.repositories.blobstore.ESMockAPIBasedRepositoryIntegTestCase$ExceptionCatchingHttpHandler.handle(ESMockAPIBasedRepositoryIntegTestCase.java:414)
  at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
  at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
  at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
  at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:822)
  at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
  at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:794)
  at org.elasticsearch.repositories.blobstore.ESMockAPIBasedRepositoryIntegTestCase.lambda$startHttpServer$0(ESMockAPIBasedRepositoryIntegTestCase.java:105)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:750)

```

**Comment by pxsalehi** [comment]
This fails on 8.12 too. The error seems related to the HTTP mock server that is used in the test. IMO, not a blocker.

**Comment by DaveCTurner** [comment]
I think it's https://bugs.openjdk.org/browse/JDK-8299058, fixed in JDK22 and only a test issue otherwise.

**Comment by idegtiarenko** [comment]
Should we exclude this test when running on older JDKs?
Or (if possible) catch this failure and log a warning without failing the test?
