### ISSUE TITLE
[CI] AzureBlobStoreRepositoryTests testDanglingShardLevelBlobCleanup failing

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#106778]
**Build scan:**
https://gradle-enterprise.elastic.co/s/5hm4i7kz2hmhe/tests/:modules:repository-azure:internalClusterTest/org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests/testDanglingShardLevelBlobCleanup

**Reproduction line:**
```
./gradlew ':modules:repository-azure:internalClusterTest' --tests "org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests.testDanglingShardLevelBlobCleanup" -Dtests.seed=22CD8CF0C1D93787 -Dtests.locale=es-SV -Dtests.timezone=America/Cordoba -Druntime.java=21
```

**Applicable branches:**
8.12

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests#testDanglingShardLevelBlobCleanup`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testDanglingShardLevelBlobCleanup'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: State is not REQUEST (IDLE)

  at __randomizedtesting.SeedInfo.seed([22CD8CF0C1D93787]:0)
  at sun.net.httpserver.ServerImpl.requestCompleted(ServerImpl.java:1001)
  at sun.net.httpserver.FixedLengthInputStream.readImpl(FixedLengthInputStream.java:63)
  at sun.net.httpserver.LeftOverInputStream.read(LeftOverInputStream.java:99)
  at java.io.FilterInputStream.read(FilterInputStream.java:95)
  at org.elasticsearch.core.Streams.copy(Streams.java:45)
  at org.elasticsearch.core.Streams.copy(Streams.java:79)
  at org.elasticsearch.common.io.Streams.readFully(Streams.java:189)
  at fixture.azure.AzureHttpHandler.handle(AzureHttpHandler.java:95)
  at org.elasticsearch.repositories.blobstore.ESMockAPIBasedRepositoryIntegTestCase$HttpStatsCollectorHandler.handle(ESMockAPIBasedRepositoryIntegTestCase.java:371)
  at org.elasticsearch.repositories.blobstore.ESMockAPIBasedRepositoryIntegTestCase$ExceptionCatchingHttpHandler.handle(ESMockAPIBasedRepositoryIntegTestCase.java:407)
  at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
  at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
  at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:101)
  at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:871)
  at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
  at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:847)
  at org.elasticsearch.repositories.blobstore.ESMockAPIBasedRepositoryIntegTestCase.lambda$startHttpServer$0(ESMockAPIBasedRepositoryIntegTestCase.java:104)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:916)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by pxsalehi** [comment]
The error seems related to the HTTP mock server that is used in the test. IMO, not a blocker.

**Comment by DaveCTurner** [comment]
I think this is https://bugs.openjdk.org/browse/JDK-8299058.

**Comment by DaveCTurner** [comment]
Yeah this was using JDK21, should be fixed now.
