### ISSUE TITLE
[CI] HdfsSearchableSnapshotsIT and SecureHdfsSearchableSnapshotsIT classMethod failing

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#106757]
Maybe related to the failure from https://github.com/elastic/elasticsearch/issues/106739, but the exact failure is different.

Maybe caused by https://github.com/elastic/elasticsearch/pull/106228 - CC @breskeby

**Build scan:**
https://gradle-enterprise.elastic.co/s/qyotfg4qsdc66/tests/:x-pack:plugin:searchable-snapshots:qa:hdfs:javaRestTest/org.elasticsearch.xpack.searchablesnapshots.hdfs.HdfsSearchableSnapshotsIT

**Reproduction line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.searchablesnapshots.hdfs.HdfsSearchableSnapshotsIT#classMethod`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('classMethod'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.searchablesnapshots.hdfs.HdfsSearchableSnapshotsIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.security.InvalidParameterException: Key size for HMAC must be at least 112 bits in approved mode: SHA-1/HMAC

  at __randomizedtesting.SeedInfo.seed([8968AA0493508CAB]:0)
  at org.bouncycastle.jcajce.provider.BaseKeyGenerator.engineInit(null:-1)
  at javax.crypto.KeyGenerator.init(KeyGenerator.java:539)
  at javax.crypto.KeyGenerator.init(KeyGenerator.java:516)
  at fixture.hdfs2.org.apache.hadoop.security.token.SecretManager.<init>(SecretManager.java:144)
  at fixture.hdfs2.org.apache.hadoop.security.token.delegation.AbstractDelegationTokenSecretManager.<init>(AbstractDelegationTokenSecretManager.java:120)
  at fixture.hdfs2.org.apache.hadoop.hdfs.security.token.delegation.DelegationTokenSecretManager.<init>(DelegationTokenSecretManager.java:95)
  at fixture.hdfs2.org.apache.hadoop.hdfs.server.namenode.FSNamesystem.createDelegationTokenSecretManager(FSNamesystem.java:5868)
  at fixture.hdfs2.org.apache.hadoop.hdfs.server.namenode.FSNamesystem.<init>(FSNamesystem.java:870)
  at fixture.hdfs2.org.apache.hadoop.hdfs.server.namenode.FSNamesystem.<init>(FSNamesystem.java:724)
  at fixture.hdfs2.org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:1103)
  at fixture.hdfs2.org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:376)
  at fixture.hdfs2.org.apache.hadoop.hdfs.DFSTestUtil.formatNameNode(DFSTestUtil.java:233)
  at fixture.hdfs2.org.apache.hadoop.hdfs.MiniDFSCluster.createNameNodesAndSetConf(MiniDFSCluster.java:1027)
  at fixture.hdfs2.org.apache.hadoop.hdfs.MiniDFSCluster.initMiniDFSCluster(MiniDFSCluster.java:830)
  at fixture.hdfs2.org.apache.hadoop.hdfs.MiniDFSCluster.<init>(MiniDFSCluster.java:485)
  at fixture.hdfs2.org.apache.hadoop.hdfs.MiniDFSCluster$Builder.build(MiniDFSCluster.java:444)
  at org.elasticsearch.test.fixtures.hdfs.HdfsFixture.startMinHdfs(HdfsFixture.java:233)
  at org.elasticsearch.test.fixtures.hdfs.HdfsFixture.before(HdfsFixture.java:84)
  at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by breskeby** [comment]
should be fixed by this:
