### ISSUE TITLE
[CI] TemporaryDirectoryConfigTests test21AcceptsCustomPathInDocker failing

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#106771]
**Build scan:**
https://gradle-enterprise.elastic.co/s/b2iz4zgwguq3u/tests/:qa:os:destructiveDistroTest.default-dockerIronBank/org.elasticsearch.packaging.test.TemporaryDirectoryConfigTests/test21AcceptsCustomPathInDocker

**Reproduction line:**
```
null
```

**Applicable branches:**
7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.packaging.test.TemporaryDirectoryConfigTests#test21AcceptsCustomPathInDocker`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test21AcceptsCustomPathInDocker'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.packaging.test.TemporaryDirectoryConfigTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: Elasticsearch container did not start successfully.

ps output:
    PID TTY      STAT   TIME COMMAND
      1 ?        Ss     0:00 /bin/tini -- /usr/local/bin/docker-entrypoint.sh eswrapper
      7 ?        S      0:00 /bin/bash /usr/share/elasticsearch/bin/elasticsearch
    483 ?        S      0:00 /bin/bash bin/elasticsearch-keystore has-passwd --silent
    485 ?        Sl     0:03 /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Xms4m -Xmx64m -XX:+UseSerialGC -Des.cgroups.hierarchy.override=/ -Des.cgroups.hierarchy.override=/ -Des.path.home=/usr/share/elasticsearch -Des.path.conf=/usr/share/elasticsearch/config -Des.distribution.flavor=default -Des.distribution.type=docker -cp /usr/share/elasticsearch/lib/*:/usr/share/elasticsearch/lib/tools/keystore-cli/* org.elasticsearch.common.settings.KeyStoreCli has-passwd --silent -Eingest.geoip.downloader.enabled=false -Ediscovery.type=single-node
    567 pts/2    Rs+    0:00 ps -ww ax

Stdout:
Created elasticsearch keystore in /usr/share/elasticsearch/config/elasticsearch.keystore

Stderr:

  at __randomizedtesting.SeedInfo.seed([C21243B574573655:D59EF18E6AFBC20D]:0)
  at org.junit.Assert.fail(Assert.java:89)
  at org.elasticsearch.packaging.util.docker.Docker.waitForElasticsearchToStart(Docker.java:171)
  at org.elasticsearch.packaging.util.docker.Docker.runContainer(Docker.java:113)
  at org.elasticsearch.packaging.test.TemporaryDirectoryConfigTests.test21AcceptsCustomPathInDocker(TemporaryDirectoryConfigTests.java:66)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1570)

```

**Comment by mosche** [comment]
I wasn't able to reproduce this unfortunately. 
Initially it looked like we're missing container logs, though those exist. The container simply stopped / crashed after the keystore command for any reason.

Considering that's the only time this failed in a very long time, I'm closing this.
