### ISSUE TITLE
HdfsSearchableSnapshotsIT fails under fips condition

### ISSUE THREAD

**Issue by quux00** [elastic/elasticsearch#106845]
### CI Link

https://gradle-enterprise.elastic.co/s/l6hhztomqyiew/tests/task/:x-pack:plugin:searchable-snapshots:qa:hdfs:javaRestTest/details/org.elasticsearch.xpack.searchablesnapshots.hdfs.HdfsSearchableSnapshotsIT?top-execution=1

### Repro line

./gradlew ':x-pack:plugin:searchable-snapshots:qa:hdfs:javaRestTest' --tests "org.elasticsearch.xpack.searchablesnapshots.hdfs.HdfsSearchableSnapshotsIT" -Dtests.seed=1CD8FD71D0A779E5 -Dtests.locale=en -Dtests.timezone=Etc/UTC -Druntime.java=22 -Dtests.fips.enabled=true

### Does it reproduce?

Yes

### Applicable branches

main and https://github.com/elastic/elasticsearch/pull/106638

### Failure excerpt

```
java.security.InvalidParameterException: Key size for HMAC must be at least 112 bits in approved mode: SHA-1/HMAC
	at __randomizedtesting.SeedInfo.seed([1CD8FD71D0A779E5]:0)
	at org.bouncycastle.jcajce.provider.BaseKeyGenerator.engineInit(Unknown Source)
	at java.base/javax.crypto.KeyGenerator.init(KeyGenerator.java:535)
	at java.base/javax.crypto.KeyGenerator.init(KeyGenerator.java:512)
	at fixture.hdfs2.org.apache.hadoop.security.token.SecretManager.<init>(SecretManager.java:144)
	at fixture.hdfs2.org.apache.hadoop.security.token.delegation.AbstractDelegationTokenSecretManager.<init>(AbstractDelegationTokenSecretManager.java:120)
	at fixture.hdfs2.org.apache.hadoop.hdfs.security.token.delegation.DelegationTokenSecretManager.<init>(DelegationTokenSecretManager.java:95)
	at fixture.hdfs2.org.apache.hadoop.hdfs.server.namenode.FSNamesystem.createDelegationTokenSecretManager(FSNamesystem.java:5868)
	at fixture.hdfs2.org.apache.hadoop.hdfs.server.namenode.FSNamesystem.<init>(FSNamesystem.java:870)
	at fixture.hdfs2.org.apache.hadoop.hdfs.server.namenode.FSNamesystem.<init>(FSNamesystem.java:724)
	at fixture.hdfs2.org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:1103)
	at fixture.hdfs2.org.apache.hadoop.hdfs.server.namenode.NameNode.format(NameNode.java:376)
	at fixture.hdfs2.org.apache.hadoop.hdfs.DFSTestUtil.formatNameNode(DFSTestUtil.java:233)
	at fixture.hdfs2.org.apache.hadoop.hdfs.MiniDFSCluster.createNameNodesAndSetConf(MiniDFSCluster.java:1027)
	at fixture.hdfs2.org.apache.hadoop.hdfs.MiniDFSCluster.initMiniDFSCluster(MiniDFSCluster.java:830)
	at fixture.hdfs2.org.apache.hadoop.hdfs.MiniDFSCluster.<init>(MiniDFSCluster.java:485)
	at fixture.hdfs2.org.apache.hadoop.hdfs.MiniDFSCluster$Builder.build(MiniDFSCluster.java:444)
	at org.elasticsearch.test.fixtures.hdfs.HdfsFixture.tryStartingHdfs(HdfsFixture.java:255)
	at org.elasticsearch.test.fixtures.hdfs.HdfsFixture.startMinHdfs(HdfsFixture.java:193)
	at org.elasticsearch.test.fixtures.hdfs.HdfsFixture.before(HdfsFixture.java:85)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by mark-vieira** [comment]
@breskeby Shouldn't https://github.com/elastic/elasticsearch/pull/106762 have addressed this?

**Comment by breskeby** [comment]
yes. The linked build scan is from a PR. my guess is that it hasn't been rebased after we pushed #106762

**Comment by breskeby** [comment]
ah wait. this is searchable-snapshots 👀
