### ISSUE TITLE
Elasticsearch 8.13 Percolator Regression, Exception thrown On Wildcard Query createWeight

### ISSUE THREAD

**Issue by mccheah** [elastic/elasticsearch#107176]
### Elasticsearch Version

8.13.1

### Installed Plugins

Percolator

### Java Version

17

### OS Version

N/A

### Problem Description

Upon upgrading from Elasticsearch 8.12 to 8.13.1, the code shown in the "Steps to Reproduce" section below started throwing an exception when it used to pass (using the Java client API). I’m running a single node Elasticsearch cluster. Is this a regression, or is there an expected API break in the way Percolator is meant to be used on ES 8.13?

### Steps to Reproduce

Run this code with an Elasticsearch client pointing at any cluster:

```
    private static void basicPercolatorFailureExample(co.elastic.clients.elasticsearch.ElasticsearchClient client) throws IOException {
        client
                .indices()
                .create(builder -> builder
                        .index("test-docs-index")
                        .mappings(mappingBuilder -> mappingBuilder
                                .properties("field1", propBuilder -> propBuilder.keyword(kwBuilder -> kwBuilder))));
        client.indices()
                .create(builder -> builder
                        .index("test-percolate-index")
                        .mappings(mappingBuilder -> mappingBuilder
                                .properties("field1", propBuilder -> propBuilder.keyword(kwBuilder -> kwBuilder))
                                .properties(
                                        "query",
                                        propBuilder -> propBuilder.percolator(percBuilder -> percBuilder))));
        client.index(builder -> builder
                .id("id")
                .document(Map.of("field1", "doc_1"))
                .index("test-docs-index")
                .refresh(Refresh.True));
        Query wildcardQuery = Query.of(builder -> builder.wildcard(
                wcBuilder -> wcBuilder.field("field1").queryName("field1").value("doc_*")));
        IndexRequest<?> indexRequest = IndexRequest.of(builder -> builder
                .id("percolator-id")
                .index("test-percolate-index")
                .document(new PercolatorDocument(wildcardQuery))
                .refresh(Refresh.True));
        client.index(indexRequest);
        // Thw following code throws an exception
        SearchResponse<?> percolateResponse = client.search(
                sb -> sb
                        .query(qb -> qb
                                .percolate(perc -> perc
                                        .index("test-docs-index")
                                        .id("id")
                                        .field("query")))
                        .index("test-percolate-index"),
                JsonData.class);

        // This code is never reached
        org.assertj.core.api.Assertions.assertThat(percolateResponse.hits().total().value()).isOne();
    }
```

Exception thrown on the client:

```
org.elasticsearch.client.ResponseException: method [POST], host [https://<REDACTED>:9200], URI [/test-percolate-index/_search?typed_keys=true], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"unsupported_operation_exception","reason":"Query field1:doc_* does not implement createWeight"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"test-percolate-index","node":"jF9bdyvkSuK716u0rUVk4w","reason":{"type":"unsupported_operation_exception","reason":"Query field1:doc_* does not implement createWeight"}}],"caused_by":{"type":"unsupported_operation_exception","reason":"Query field1:doc_* does not implement createWeight","caused_by":{"type":"unsupported_operation_exception","reason":"Query field1:doc_* does not implement createWeight"}}},"status":500}
    at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:351)
    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:317)
    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:292)
    at co.elastic.clients.transport.rest_client.RestClientHttpClient.performRequest(RestClientHttpClient.java:91)
    at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:144)
    at co.elastic.clients.elasticsearch.ElasticsearchClient.search(ElasticsearchClient.java:1923)
    at co.elastic.clients.elasticsearch.ElasticsearchClient.search(ElasticsearchClient.java:1940)
```

Exception thrown on the server:

```
DEBUG [2024-04-02T17:51:52.605894Z] org.elasticsearch.action.search.TransportSearchAction: [jF9bdyvkSuK716u0rUVk4w][test-percolate-index][0]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[test-percolate-index], indicesOptions=IndicesOptions[ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, expand_wildcards_hidden=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false, ignore_throttled=true], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=0, batchedReduceSize=512, preFilterShardSize=null, allowPartialSearchResults=true, localClusterAlias=null, getOrCreateAbsoluteStartMillis=-1, ccsMinimizeRoundtrips=true, source={"query":{"percolate":{"field":"query","documents":[{"field1":"doc_1"}]}}}}] lastShard [true] (0: [jF9bdyvkSuK716u0rUVk4w][test-percolate-index][0]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[test-percolate-index], indicesOptions=IndicesOptions[ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, expand_wildcards_hidden=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false, ignore_throttled=true], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=0, batchedReduceSize=512, preFilterShardSize=null, allowPartialSearchResults=true, localClusterAlias=null, getOrCreateAbsoluteStartMillis=-1, ccsMinimizeRoundtrips=true, source={"query":{"percolate":{"field":"query","documents":[{"field1":"doc_1"}]}}}}] lastShard [true], throwable0_message: [<REDACTED>][172.29.0.3:9300][indices:data/read/search[phase/query]], throwable1_message: Fetch Failed [Error running fetch phase for doc [0]], throwable2_message: Query field1:doc_* does not implement createWeight)
org.elasticsearch.transport.RemoteTransportException: [<REDACTED>][172.29.0.3:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.search.fetch.FetchPhaseExecutionException: Fetch Failed [Error running fetch phase for doc [0]]
        at org.elasticsearch.server@8.13.0/org.elasticsearch.search.fetch.FetchPhaseDocsIterator.iterate(FetchPhaseDocsIterator.java:78)
        at org.elasticsearch.server@8.13.0/org.elasticsearch.search.fetch.FetchPhase.buildSearchHits(FetchPhase.java:170)
        at org.elasticsearch.server@8.13.0/org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:78)
        at org.elasticsearch.server@8.13.0/org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:720)
        at org.elasticsearch.server@8.13.0/org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:691)
        at org.elasticsearch.server@8.13.0/org.elasticsearch.search.SearchService.lambda$executeQueryPhase$2(SearchService.java:549)
        at org.elasticsearch.server@8.13.0/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:73)
        at org.elasticsearch.server@8.13.0/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:70)
        at org.elasticsearch.server@8.13.0/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:95)
        at org.elasticsearch.server@8.13.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.server@8.13.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
        at org.elasticsearch.server@8.13.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
        at org.elasticsearch.server@8.13.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.UnsupportedOperationException: Query field1:doc_* does not implement createWeight
        at org.apache.lucene.core@9.10.0/org.apache.lucene.search.Query.createWeight(Query.java:84)
        at org.apache.lucene.core@9.10.0/org.apache.lucene.search.NamedMatches$NamedQuery.createWeight(NamedMatches.java:101)
        at org.apache.lucene.core@9.10.0/org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:874)
        at org.elasticsearch.percolator@8.13.0/org.elasticsearch.percolator.PercolatorMatchedSlotSubFetchPhase$1.process(PercolatorMatchedSlotSubFetchPhase.java:108)
        at org.elasticsearch.server@8.13.0/org.elasticsearch.search.fetch.FetchPhase$1.nextDoc(FetchPhase.java:164)
        at org.elasticsearch.server@8.13.0/org.elasticsearch.search.fetch.FetchPhaseDocsIterator.iterate(FetchPhaseDocsIterator.java:70)
        ... 15 more
```

**Comment by benwtrent** [comment]
This does seem related to: https://github.com/elastic/elasticsearch/pull/103084

@mccheah I didn't think that query names worked at all for percolator queries pre-8.13. It just sort of dropped it on the floor without warning. What is the expected behavior for a query name in percolator before 8.13?

Does your request work if you remove the `.queryName("field1")`?

**Comment by mccheah** [comment]
Removing `queryName` seems to fix this example. We don't have to depend on queryName, but it would still be nice to have either:

* A better error message, ideally at query indexing time indicating this is the problem, as opposed to having the query fail at percolation time. And / or,
* Just don't fail the percolation entirely - if the query API allows for setting these fields then they would be reasonably expected to not make the percolation throw this kind of exception.

**Comment by benwtrent** [comment]
I agree @mccheah and thank you for the clarifications. Just wanted to make sure if using the `_name` was giving any benefit at all <8.13.

**Comment by mccheah** [comment]
Excellent, thanks for the quick response - looking forward to seeing the patch to improve this!
