### ISSUE TITLE
[CI] DownsampleActionSingleNodeTests testCannotDownsampleWhileOtherDownsampleInProgress failing

### ISSUE THREAD

**Issue by kkrik-es** [elastic/elasticsearch#107210]
**Build scan:**
https://gradle-enterprise.elastic.co/s/2cchkwzvo6qd6/tests/:x-pack:plugin:downsample:test/org.elasticsearch.xpack.downsample.DownsampleActionSingleNodeTests/testCannotDownsampleWhileOtherDownsampleInProgress

**Reproduction line:**
```
./gradlew ':x-pack:plugin:downsample:test' --tests "org.elasticsearch.xpack.downsample.DownsampleActionSingleNodeTests.testCannotDownsampleWhileOtherDownsampleInProgress" -Dtests.seed=E2910C8F994C399F -Dtests.locale=sk-SK -Dtests.timezone=Pacific/Midway -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.downsample.DownsampleActionSingleNodeTests#testCannotDownsampleWhileOtherDownsampleInProgress`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testCannotDownsampleWhileOtherDownsampleInProgress'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.downsample.DownsampleActionSingleNodeTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.elasticsearch.ElasticsearchException: downsample task [downsample-downsample-aqymczlptkewem-0-228h] failed

  at __randomizedtesting.SeedInfo.seed([E2910C8F994C399F:C2FEFBED0FE0178A]:0)
  at org.elasticsearch.xpack.downsample.TransportDownsampleAction$2.onResponse(TransportDownsampleAction.java:499)
  at org.elasticsearch.xpack.downsample.TransportDownsampleAction$2.onResponse(TransportDownsampleAction.java:491)
  at org.elasticsearch.persistent.PersistentTasksService$1.onNewClusterState(PersistentTasksService.java:213)
  at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onNewClusterState(ClusterStateObserver.java:375)
  at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.clusterChanged(ClusterStateObserver.java:226)
  at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListener(ClusterApplierService.java:561)
  at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:548)
  at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:506)
  at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:430)
  at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:155)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:917)
  at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:217)
  at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:183)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by kkrik-es** [comment]
Relevant log entries:

```
 1> [2024-04-07T21:43:04,617][INFO ][o.e.x.d.DownsampleActionSingleNodeTests] [testCannotDownsampleWhileOtherDownsampleInProgress] before test
  1> [2024-04-07T21:43:04,624][WARN ][o.e.d.c.m.MetadataCreateIndexService] [node_s_0] data_stream.dataset="deprecation.elasticsearch" data_stream.namespace="default" data_stream.type="logs" elasticsearch.event.category="templates" event.code="index_template_multiple_match" message="index [aqymczlptkewem] matches multiple legacy templates [one_shard_index_template, random-soft-deletes-template], composable templates will only match a single template"
  1> [2024-04-07T21:43:04,640][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s_0] [aqymczlptkewem] creating index, cause [api], templates [one_shard_index_template, random-soft-deletes-template], shards [1]/[0]
  1> [2024-04-07T21:43:04,787][INFO ][o.e.c.r.a.AllocationService] [node_s_0] current.health="GREEN" message="Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[aqymczlptkewem][0]]])." previous.health="YELLOW" reason="shards started [[aqymczlptkewem][0]]"
  1> [2024-04-07T21:43:05,369][INFO ][o.e.x.d.DownsampleActionSingleNodeTests] [testCannotDownsampleWhileOtherDownsampleInProgress] Indexed [4191] documents. Dropped [0] duplicates.
  1> [2024-04-07T21:43:05,540][INFO ][o.e.c.r.a.AllocationService] [node_s_0] current.health="GREEN" message="Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[downsample-aqymczlptkewem][0]]])." previous.health="YELLOW" reason="shards started [[downsample-aqymczlptkewem][0]]"
  1> [2024-04-07T21:43:05,541][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Downsampling task [downsample-downsample-aqymczlptkewem-0-228h on shard [aqymczlptkewem][0] started
  1> [2024-04-07T21:43:05,557][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Shard [aqymczlptkewem][0] processed [4191] docs, created [521] downsample buckets
  1> [2024-04-07T21:43:05,669][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Shard [[aqymczlptkewem][0]] successfully sent [4191], received source doc [521], indexed downsampled doc [521], failed [0], took [203ms]
  1> [2024-04-07T21:43:05,669][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Downsampling task [downsample-downsample-aqymczlptkewem-0-228h on shard [aqymczlptkewem][0] completed
  1> [2024-04-07T21:43:05,719][INFO ][o.e.x.d.TransportDownsampleAction] [node_s_0] Downsampling task [downsample-downsample-aqymczlptkewem-0-228h completed for shard [aqymczlptkewem][0]
  1> [2024-04-07T21:43:05,720][INFO ][o.e.x.d.TransportDownsampleAction] [node_s_0] All downsampling tasks completed [1]
  1> [2024-04-07T21:43:05,854][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Downsampling task [downsample-downsample-aqymczlptkewem-0-228h on shard [aqymczlptkewem][0] started
  1> [2024-04-07T21:43:05,864][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Shard [aqymczlptkewem][0] processed [4191] docs, created [521] downsample buckets
  1> [2024-04-07T21:43:05,901][ERROR][o.e.x.d.DownsampleShardIndexer] [node_s_0] Shard [[aqymczlptkewem][0]] failed to populate downsample index. Failures: [{null=org.elasticsearch.cluster.block.ClusterBlockException: index [downsample-aqymczlptkewem] blocked by: [FORBIDDEN/8/index write (api)];}]
  1> [2024-04-07T21:43:05,917][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Shard [[aqymczlptkewem][0]] successfully sent [4191], received source doc [521], indexed downsampled doc [521], failed [521], took [0s]
  1> [2024-04-07T21:43:05,921][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Downsampling task [downsample-downsample-aqymczlptkewem-0-228h] on shard [aqymczlptkewem][0] failed indexing [521]
  1> [2024-04-07T21:43:05,922][ERROR][o.e.x.d.DownsampleShardPersistentTaskExecutor] [node_s_0] Downsampling task [downsample-downsample-aqymczlptkewem-0-228h non retriable failure [Downsampling task [downsample-downsample-aqymczlptkewem-0-228h] on shard [aqymczlptkewem][0] failed indexing [521]]
  1> [2024-04-07T21:43:05,954][ERROR][o.e.x.d.TransportDownsampleAction] [node_s_0] error while waiting for downsampling persistent task
  1> org.elasticsearch.ElasticsearchException: downsample task [downsample-downsample-aqymczlptkewem-0-228h] failed
  1> 	at org.elasticsearch.xpack.downsample.TransportDownsampleAction$2.onResponse(TransportDownsampleAction.java:499) ~[main/:?]
  1> 	at org.elasticsearch.xpack.downsample.TransportDownsampleAction$2.onResponse(TransportDownsampleAction.java:491) ~[main/:?]
  1> 	at org.elasticsearch.persistent.PersistentTasksService$1.onNewClusterState(PersistentTasksService.java:213) ~[elasticsearch-8.14.0-SNAPSHOT.jar:8.14.0-SNAPSHOT]
  1> 	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onNewClusterState(ClusterStateObserver.java:375) ~[elasticsearch-8.14.0-SNAPSHOT.jar:8.14.0-SNAPSHOT]
  1> 	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.clusterChanged(ClusterStateObserver.java:226) ~[elasticsearch-8.14.0-SNAPSHOT.jar:8.14.0-SNAPSHOT]
  1> 	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListener(ClusterApplierService.java:561) ~[elasticsearch-8.14.0-SNAPSHOT.jar:8.14.0-SNAPSHOT]
  1> 	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:548) ~[elasticsearch-8.14.0-SNAPSHOT.jar:8.14.0-SNAPSHOT]
  1> 	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:506) ~[elasticsearch-8.14.0-SNAPSHOT.jar:8.14.0-SNAPSHOT]
  1> 	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:430) ~[elasticsearch-8.14.0-SNAPSHOT.jar:8.14.0-SNAPSHOT]
  1> 	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:155) ~[elasticsearch-8.14.0-SNAPSHOT.jar:8.14.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:917) ~[elasticsearch-8.14.0-SNAPSHOT.jar:8.14.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:217) ~[elasticsearch-8.14.0-SNAPSHOT.jar:8.14.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:183) ~[elasticsearch-8.14.0-SNAPSHOT.jar:8.14.0-SNAPSHOT]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
  1> 	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
  1> [2024-04-07T21:43:05,981][INFO ][o.e.x.d.DownsampleActionSingleNodeTests] [testCannotDownsampleWhileOtherDownsampleInProgress] after test
```

The interesting failure is this one, on the retry:

```
  1> [2024-04-07T21:43:05,901][ERROR][o.e.x.d.DownsampleShardIndexer] [node_s_0] Shard [[aqymczlptkewem][0]] failed to populate downsample index. Failures: [{null=org.elasticsearch.cluster.block.ClusterBlockException: index [downsample-aqymczlptkewem] blocked by: [FORBIDDEN/8/index write (api)];}]
```

**Comment by kkrik-es** [comment]
This is still happening: 

https://gradle-enterprise.elastic.co/s/ygv5qoxopbkqs

**Comment by kkrik-es** [comment]
No more failures since the last fix. Resolving for now.
