### ISSUE TITLE
[Transforms] Transform has failed with "The object cannot be set twice"

### ISSUE THREAD

**Issue by prwhelan** [elastic/elasticsearch#107215]
### Description

```java
org.elasticsearch.transport.RemoteTransportException: [<>][<>][cluster:admin/persistent/update_status]
Caused by: org.elasticsearch.ResourceNotFoundException: the task with id slo-summary-timeslices-90d-rolling and allocation id <> doesn't exist
	at org.elasticsearch.persistent.PersistentTasksClusterService$4.execute(PersistentTasksClusterService.java:264)
	at org.elasticsearch.cluster.service.MasterService$UnbatchedExecutor.execute(MasterService.java:550)
	at org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1039)
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1004)
	at org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:232)
	at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1645)
	at org.elasticsearch.action.ActionListener.run(ActionListener.java:356)
	at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.run(MasterService.java:1642)
	at org.elasticsearch.cluster.service.MasterService$5.lambda$doRun$0(MasterService.java:1237)
	at org.elasticsearch.action.ActionListener.run(ActionListener.java:356)
	at org.elasticsearch.cluster.service.MasterService$5.doRun(MasterService.java:1216)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1583)
```

```java
org.apache.lucene.util.SetOnce$AlreadySetException: The object cannot be set twice!
	at org.apache.lucene.core@9.10.0/org.apache.lucene.util.SetOnce.set(SetOnce.java:70)
	at org.elasticsearch.transform@8.14.0/org.elasticsearch.xpack.transform.transforms.TransformPersistentTasksExecutor.lambda$nodeOperation$8(TransformPersistentTasksExecutor.java:289)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:171)
	at org.elasticsearch.transform@8.14.0/org.elasticsearch.xpack.transform.persistence.IndexBasedTransformConfigManager.lambda$getTransformStoredDoc$21(IndexBasedTransformConfigManager.java:724)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:245)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:202)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:196)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:307)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.search.TransportSearchAction.lambda$doExecute$2(TransportSearchAction.java:308)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:245)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:269)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.ActionListener.respondAndRelease(ActionListener.java:289)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:706)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.search.FetchLookupFieldsPhase.run(FetchLookupFieldsPhase.java:75)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:454)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:448)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.search.ExpandSearchPhase.onPhaseDone(ExpandSearchPhase.java:153)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:54)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:454)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:448)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:235)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:108)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:87)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
	at org.elasticsearch.server@8.14.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by prwhelan** [comment]
Seems there are three threads running the startup procedure at the same time
```
elasticsearch[<>][system_read][T#1]
```
```
elasticsearch[<>][management][T#2]
```
```
elasticsearch[<>][generic][T#13]
```

T13 succeeds, T1 fails, T2 also has failures but I'm guessing that is called via the `mark*` API

**Comment by prwhelan** [comment]
- https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/scheduling/TransformScheduler.java#L157
- https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformRetryableStartUpListener.java#L60
- https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformPersistentTasksExecutor.java#L417
- https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/persistence/IndexBasedTransformConfigManager.java#L430

Looks like the scheduler unblocks after it kicks off the async call, and a scheduler thread can retry the task while the first one is going.  Whoever makes it to the SetOnce first will start the task and the other will fail the call
