### ISSUE TITLE
NoSuchRemoteClusterException is returned for both non-existent remotes and remotes with skip_unavailable=true

### ISSUE THREAD

**Issue by quux00** [elastic/elasticsearch#107381]
### Elasticsearch Version

8.14-SNAPSHOT

### Java Version

_bundled_

### OS Version

Darwin michaels-mbp.lan 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

### Problem Description

When doing cross-cluster searches (`_search` or `_async_search`), `NoSuchRemoteClusterException` is returned for both non-existent remotes and remotes with skip_unavailable=true that cannot be connected to. By contrast, remotes with skip_unavailable=false return a "connection_exception" error message when they cannot be reached.

Should we also be returning "connection exception" errors for skip_unavailable=true remotes? Should NoSuchRemoteClusterException be reserved for attempts to search clusters that are not configured?

This issue occurs for both non-secured and secured clusters. See the "Steps to Reproduce" section for details.

### Steps to Reproduce

Manual testing. Configure a cluster to connect to two remote clusters. In my case, the three clusters all run on the same local machine and the config on the primary looks like:

```
cluster:
    remote:
        remote1:
            seeds: 127.0.0.1:9301
            skip_unavailable: true
        remote2:
            seeds: 127.0.0.1:9302
            skip_unavailable: false
```

<br/>

#### Scenario 1: on a non-secured cluster, query for remote5

```
POST  remote5: */_async_search
{
   ... query not shown ...
}
```

You get a `NoSuchRemoteClusterException` (as expected)

<details><summary>Response example (toggle)</summary>

```
{
  "id": "FnFVcFctWTNxUnRDZlNzVVZFU2Q1dncaMWdWNHdULXdUaEtsUjc2UFJvTm9HZzoyNTk=",
  "is_partial": true,
  "is_running": false,
  "start_time_in_millis": 1712781379327,
  "expiration_time_in_millis": 1713213379327,
  "error": {
    "type": "status_exception",
    "reason": "error while executing search",
    "caused_by": {
      "type": "no_such_remote_cluster_exception",
      "reason": "no such remote cluster: [remote11]"
    }
  }
}
```

</details>

<br/>

#### Scenario 2: on a non-secured cluster, query for remote2 (skip_unavailable=false) when remote2 is not running/down

You get a "not connected" type exception (as expected)

<details><summary>Response example (toggle)</summary>

```
{
  "id": "FnhXUkh5dTQ5U0ppdWlVNUFTeFF4MGcaMWdWNHdULXdUaEtsUjc2UFJvTm9HZzoxNTM=",
  "is_partial": true,
  "is_running": false,
  "start_time_in_millis": 1712781752071,
  "expiration_time_in_millis": 1713213752071,
  "error": {
    "type": "status_exception",
    "reason": "error while executing search",
    "caused_by": {
      "type": "connect_transport_exception",
      "reason": "[][127.0.0.1:9302] connect_exception",
      "caused_by": {
        "type": "uncategorized_execution_exception",
        "reason": "Failed execution",
        "caused_by": {
          "type": "execution_exception",
          "reason": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9302",
          "caused_by": {
            "type": "annotated_connect_exception",
            "reason": "Connection refused: /127.0.0.1:9302",
            "caused_by": {
              "type": "connect_exception",
              "reason": "Connection refused"
            }
          }
        }
      }
    }
  }
}
```

</details>

<br/>

#### Scenario 3: on a non-secured cluster, query for remote1 (skip_unavailable=true) when remote1 is not running/down

In the search response you get a NoSuchRemoteClusterException:

```
// snippet of _cluster/details section in SearchResponse:
          "status": "skipped",
          "indices": "*",
          "timed_out": false,
          "failures": [
            {
              "shard": -1,
              "index": null,
              "reason": {
                "type": "no_such_remote_cluster_exception",
                "reason": "no such remote cluster: [remote1]"
              }
            }
          ]
```

<details><summary>Stack trace in logs when this happens (toggle)</summary>

```
[2024-04-10T16:39:21,495][WARN ][o.e.t.SniffConnectionStrategy] [node-1] fetching nodes from external cluster [remote1] failed org.elasticsearch.transport.ConnectTransportException: [][127.0.0.1:9301] connect_exception
        at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onFailure(TcpTransport.java:1144)
        at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener$FailureResult.complete(SubscribableListener.java:390)
        at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:302)
        at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.setResult(SubscribableListener.java:327)
        at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.onFailure(SubscribableListener.java:246)
        at org.elasticsearch.transport.netty4@8.14.0-SNAPSHOT/org.elasticsearch.transport.netty4.Netty4Utils.lambda$addListener$2(Netty4Utils.java:178)
        at io.netty.common@4.1.107.Final/io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
        at io.netty.common@4.1.107.Final/io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
        at io.netty.common@4.1.107.Final/io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
        at io.netty.common@4.1.107.Final/io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
        at io.netty.common@4.1.107.Final/io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
        at io.netty.common@4.1.107.Final/io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
        at io.netty.common@4.1.107.Final/io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:322)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:338)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.common@4.1.107.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.common@4.1.107.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.elasticsearch.common.util.concurrent.UncategorizedExecutionException: Failed execution
        at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.wrapAsExecutionException(SubscribableListener.java:283)
        at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ListenableFuture.wrapException(ListenableFuture.java:38)
        at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ListenableFuture.wrapException(ListenableFuture.java:27)
        ... 18 more
Caused by: java.util.concurrent.ExecutionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9301
        ... 21 more
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9301
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
        at io.netty.transport@4.1.107.Final/io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.common@4.1.107.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.common@4.1.107.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

</details>

<br/>

#### Secured clusters

I believe the same issue occurs on a secured cluster.

Example: in this test of [RemoteClusterSecurityFcActionAuthorizationIT](https://github.com/elastic/elasticsearch/pull/105792/files#diff-7e661242193b12735bd6cb53ce9be1edce2b8a74e5fa5b27039bdec8598e8f50R317), when the default value of skip_unavailable was changed from `false` to `true`, the search no longer throws the expected `ElasticsearchSecurityException`, but now instead throws `NoSuchRemoteClusterException`.

**Comment by DaveCTurner** [comment]
I believe you're asking about the following line of code, but it would be good if you could confirm this. The other usages of `NoSuchRemoteClusterException` look appropriate to me.

https://github.com/elastic/elasticsearch/blob/d920f4f2916929b694930d201793064cbc593877/server/src/main/java/org/elasticsearch/transport/RemoteConnectionManager.java#L154

> Should we also be returning "connection exception" errors for skip_unavailable=true remotes?

Unclear. The whole point of `skip_unavailable=true` is that we don't even try to establish a connection if one isn't already available and without attempting to establish a connection we won't have a connection exception to report.

> Should NoSuchRemoteClusterException be reserved for attempts to search clusters that are not configured?

Quite possibly, although I don't see a perfect alternative today. Maybe a `org.elasticsearch.transport.NodeNotConnectedException` with `discoveryNode = null` and a message that mentions the remote cluster name?

Such a change should have no impact on CCR as long as we continue to consider such an exception as retryable (see `org.elasticsearch.xpack.ccr.action.ShardFollowNodeTask#shouldRetry`). I'm concerned that there may be broader impact on CCS tho. @quux00 would you open a PR with your proposed solution, including any changes to CCS to handle it?
