### ISSUE TITLE
Illegal instant due to time zone offset transition, Joda error

### ISSUE THREAD

**Issue by deusofnull** [elastic/elasticsearch#10739]
Hi there everyone,

I posted in another issue dealing with the "Illegal instant" error and it was suggested to create a new issue as my stack trace was somewhat different.  Here is the other issue thread: https://github.com/elastic/elasticsearch/issues/10025

My issue is regarding a JDBC SQL river using the elasticsearch-JDBC plugin
https://github.com/jprante/elasticsearch-jdbc

I am attempting to use field mapping to parse a timestamp in the following format 
```
2015-03-08 02:00:00 EST
```

This was needed because when timezone was not included, Kibana would display all data in the incorrect timezone.  

My field mappings look like this:
```
curl -XPUT 'localhost:9200/distribution_posting_status_sp' -d '
        { "mappings" : {
        "distribution_operation_posting_trend_historical": {
        "properties": {
          "day_name" : {
            "type" : "string"
          },
          "day_timeinterval" : {
            "type" : "date",
            "format": "yyyy-MM-dd HH:mm:ss z"
          },
          "posting_count" : {
            "type" : "long"
          },
          "posting_status" : {
            "type" : "string"
          }
        }
      },
      "distribution_operation_posting_trend_15min":{
        "properties": {
          "day_name" : {
            "type" : "string"
          },
          "day_timeinterval" : {
            "type" : "date",
            "format": "yyyy-MM-dd HH:mm:ss z"
          },
          "posting_count" : {
            "type" : "long"
          },
          "posting_status" : {
            "type" : "string"
          }
        }
      }
    }
}'
```

The Joda time format indicates that a "z" character should match an input of 
``` Pacific Standard Time; PST ```
So EST should not be an issue there.  

The stack trace that I got is as follows:
```
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [day_timeinterval]
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:416)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:709)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:500)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:542)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:491)
        at org.elasticsearch.index.shard.service.InternalIndexShard.prepareCreate(InternalIndexShard.java:392)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:444)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:150)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:512)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.mapper.MapperParsingException: failed to parse date field [2015-03-08 02:15:00 EST], tried both date format [yyyy-MM-dd HH:mm:ss z], and timestamp number with locale []
        at org.elasticsearch.index.mapper.core.DateFieldMapper.parseStringValue(DateFieldMapper.java:621)
        at org.elasticsearch.index.mapper.core.DateFieldMapper.innerParseCreateField(DateFieldMapper.java:549)
        at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:235)
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:406)
        ... 12 more
Caused by: org.elasticsearch.common.joda.time.IllegalInstantException: Cannot parse "2015-03-08 02:15:00 EST": Illegal instant due to time zone offset transition (America/New_York)
        at org.elasticsearch.common.joda.time.format.DateTimeParserBucket.computeMillis(DateTimeParserBucket.java:390)
        at org.elasticsearch.common.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:749)
        at org.elasticsearch.index.mapper.core.DateFieldMapper.parseStringValue(DateFieldMapper.java:615)
```

I suspect that this is caused by a Daylight Saving Time "gap", though I am unsure of what that implies. I do not know too much about the underworkings of Elasticsearch and am a rather new user.

Can anyone suggest a course of action?  I may modify the stored procedure to output the timestamp with a UTC offset intstead of the string representation of timezone, IE: -04:00 for DST EST and -05:00 for non-DST EST.

Thanks!

**Comment by cbuescher** [comment]
It seems you are trying to index dates that are not valid in the specified time zone. The date "2015-03-08 02:15:00 EST" falls into the DST gap which last happened on Mar 8th for that time zone. This means that dates between "2015-03-08 02:00:00 EST" and "2015-03-08 02:59:59 EST" will be rejected as invalid because they don't exist for that time zone.
You should check your application logic how this invalid timestamp is produced and try to prevent this there. Either by using explicit timezone offsets (like -04:00 or -05:00) or by first converting to UTC.

**Comment by cbuescher** [comment]
btw. Rivers will be deprecated: https://www.elastic.co/blog/deprecating_rivers

**Comment by deusofnull** [comment]
Sadly, I am not the database guy at my org, and his teams are the ones writing these stored procedures.   I will have to go back to them with a request for any kind of SP change...

Honestly I might do what that elastic bog post suggests and build a custom import tool to do what this river is doing now.  I bet the Python-ES-dsl plugin would be great for that.

So the reason I do think this is more of an issue than just what you've accounted for.  Other dates that have failed due to this error include:
```
2015-01-23 10:00:00 EST

2015-01-23 11:15:00 EST

2015-01-23 19:45:00 EST

2015-01-24 00:00:00 EST

2015-01-30 01:15:00 EST

2015-02-27 12:00:00 EST

etc,etc,etc
```
Note: these are not consecutive as in the times between these failures did not themselves fail.  There are thousands of dates that fail on my execution of the river.

These date times are on -05:00 UTC, not daylight savings rest hour (March 8th 2am).

I am going to build a work around using another system, but I'd still like this to work in the mean time.  

Any thoughts?

**Comment by cbuescher** [comment]
Just out of curiosity, what seems to be the issue with the other dates you mentioned? I can see the error you mentioned when I use your mapping and index date with "2015-03-08 02:15:00 EST", but with the same mappings I can index the dates you mentioned above. Is this probably another issue?

**Comment by deusofnull** [comment]
Hey!  When I set everything up again to cause the error to post here, everything ended up working... I can't explain it.  I replicated the bug... must have been 5 times yesterday. But today everything works.

*scratches head*

Sorry!

**Comment by cbuescher** [comment]
No problem, I will close this then.

**Comment by flyisland** [comment]
hi @cbuescher , I have no idea why 'Dates between "2015-03-08 02:00:00 EST" and "2015-03-08 02:59:59 EST"  don't exist for that time zone.'

I have just google it that "EST" is used in: North America, Caribbean, Central America (http://www.timeanddate.com/time/zones/est). I don't understand why these area doesn't have the "2015-03-08 02:15:00".

Would u please tell me where to find information about this question, thanks.

**Comment by cbuescher** [comment]
Hi @flyisland, I think I was refering to daylight savings time. For 2015 this was March 8th, so at 02:00 clocks were forwarded one hour: http://www.timeanddate.com/time/change/usa/new-york?year=2015

**Comment by flyisland** [comment]
thanks @cbuescher, I see now.
