### ISSUE TITLE
Integration test failing due to assertion that does not allow calling blocking code from networking threads.

### ISSUE THREAD

**Issue by dr2014** [elastic/elasticsearch#10735]
Sample project is available at: https://github.com/dr2014/ES_IntegrationTest_Issue

Elasticsearch version: 1.5.1

The assertion in Transports [https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/transport/Transports.java#L57] is failing integration test for HTTP requests.

What is the correct way to make a blocking call from RestHandler? 

Stacktrace:
Expected current thread [Thread[elasticsearch[node_s6][http_server_worker][T#1]{New I/O worker #75},5,SampleTest]] to not be a transport thread. Reason: 
java.lang.AssertionError: Expected current thread [Thread[elasticsearch[node_s6][http_server_worker][T#1]{New I/O worker #75},5,TGRP-SampleTest]] to not be a transport thread. Reason: 
	at org.elasticsearch.transport.Transports.assertNotTransportThread(Transports.java:57)
	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:117)
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:45)
	at plugin.TestRestHandler.handleRequest(TestRestHandler.java:37)
	at org.elasticsearch.rest.RestController.executeHandler(RestController.java:225)
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:170)
	at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:121)
	at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:83)
	at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:329)

**Comment by s1monw** [comment]
use the mainling list for questions like this... the answer to your question is in https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/rest/action/admin/cluster/health/RestClusterHealthAction.java
