### ISSUE TITLE
[CI] SearchableSnapshotActionIT testSearchableSnapshotsInHotPhasePinnedToHotNodes failing

### ISSUE THREAD

**Issue by luigidellaquila** [elastic/elasticsearch#107421]
**Build scan:**
https://gradle-enterprise.elastic.co/s/unsdhiimapjfc/tests/:x-pack:plugin:ilm:qa:multi-node:javaRestTest/org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT/testSearchableSnapshotsInHotPhasePinnedToHotNodes

**Reproduction line:**
```
gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testSearchableSnapshotsInHotPhasePinnedToHotNodes" -Dtests.seed=63B915F409E7F1D1 -Dtests.locale=es-AR -Dtests.timezone=US/Mountain -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT#testSearchableSnapshotsInHotPhasePinnedToHotNodes`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testSearchableSnapshotsInHotPhasePinnedToHotNodes'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [DELETE], host [http://[::1]:59427], URI [_data_stream/logs-ihhfczesvn], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"snapshot_in_progress_exception","reason":"Cannot delete indices that are being snapshotted: [[.ds-logs-ihhfczesvn-2024.04.12-000002/ABSsl8IPTn-zW16PB5RMwg]]. Try again after snapshot finishes or cancel the currently running snapshot."}],"type":"snapshot_in_progress_exception","reason":"Cannot delete indices that are being snapshotted: [[.ds-logs-ihhfczesvn-2024.04.12-000002/ABSsl8IPTn-zW16PB5RMwg]]. Try again after snapshot finishes or cancel the currently running snapshot."},"status":400}

  at __randomizedtesting.SeedInfo.seed([63B915F409E7F1D1:1653EFC6B3966860]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:351)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:317)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:292)
  at org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testSearchableSnapshotsInHotPhasePinnedToHotNodes(SearchableSnapshotActionIT.java:873)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by idegtiarenko** [comment]
The failure reported above concerns ILM, 

In particular the test creates a data stream (with backing index `.ds-logs-ihhfczesvn-2024.04.12-000001`) and rolls it over to create a searchable snapshot out of it. In the reported failure the second rollover was happening and we were snapshotting `.ds-logs-ihhfczesvn-2024.04.12-000002` (even after the datastream and policy were removed).

I am re-labeling to data management to check why.

**Comment by nielsbauman** [comment]
Leaving some notes here for when I get back to this:
- ILM rolls over data stream after inserting 1 doc:
    > [2024-04-12T13:35:00,899][INFO ][o.e.x.c.i.WaitForRolloverReadyStep] [javaRestTest-3] index [.ds-logs-ihhfczesvn-2024.04.12-000001] is ready for rollover, conditions: [{[min_docs: 1]=true, [max_primary_shard_docs: 200000000]=false, [max_docs: 1]=true}]
    ....
    [2024-04-12T13:35:00,985][DEBUG][o.e.x.i.IndexLifecycleRunner] [javaRestTest-3] [.ds-logs-ihhfczesvn-2024.04.12-000001] running policy with async action step [{"phase":"hot","action":"rollover","name":"attempt-rollover"}]
    [2024-04-12T13:35:00,994][INFO ][o.e.c.m.MetadataCreateIndexService] [javaRestTest-3] [.ds-logs-ihhfczesvn-2024.04.12-000002] creating index, cause [rollover_data_stream], templates [wtsrqyic], shards [1]/[1]
- Another rollover gets executed:
    > [2024-04-12T13:35:01,179][INFO ][o.e.c.m.MetadataCreateIndexService] [javaRestTest-3] [.ds-logs-ihhfczesvn-2024.04.12-000003] creating index, cause [rollover_data_stream], templates [wtsrqyic], shards [1]/[1]
    
    The second index is still in the initialization phase, so this rollover isn't caused by another document being ingested in the second index for some reason.
- ILM proceeds to initialize the second and third index, while the first index is still awaiting the rollover request:
    > [2024-04-12T13:35:01,358][TRACE][o.e.x.i.IndexLifecycleRunner] [javaRestTest-3] [.ds-logs-ihhfczesvn-2024.04.12-000001] retrieved current step key: {"phase":"hot","action":"rollover","name":"attempt-rollover"}

    Note this `attempt-rollover` step isn't waiting for the shards to become active; that's what we have the `wait-for-active-shards` step for.
- ILM logs the callback after the rollover request:
    > [2024-04-12T13:35:01,359][TRACE][o.e.x.i.IndexLifecycleRunner] [javaRestTest-3] cs-change-async-action-callback, [.ds-logs-ihhfczesvn-2024.04.12-000001], current-step: {"phase":"hot","action":"rollover","name":"attempt-rollover"}
- The remaining steps/logs aren't as interesting, as in this first part, we already saw 2 rollovers while we should have only seen 1.

Conclusion so far: ILM fired a rollover request, which created a new index, but then a second rollover request got executed before the callback of the first rollover request was completed.

**Comment by nielsbauman** [comment]
Ah after reading through my notes again (I am a rubber duck?), I'm guessing the first rollover is from ILM and the second (erroneous) one is from https://github.com/elastic/elasticsearch/blob/25e35510ab0ea75e12be6dc72a47c2e06e08fccb/x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/actions/SearchableSnapshotActionIT.java#L860-L860
I'll try to reproduce this later today. That seems like the most plausible explanation right now. Although, I would have expected this to happen more often.

**Comment by nielsbauman** [comment]
I wasn't able to reproduce this right away, as the timing has to be just right in order for this to happen, but I'm fairly confident that #108790 will prevent this failure from happening again.
