### ISSUE TITLE
java.net.UnknownHostException Name or service not known 7.17 amazonlinux-2

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#107614]
### CI Link

https://gradle-enterprise.elastic.co/s/bumpfzvv4xrzm

### Repro line

./gradlew ':plugins:transport-nio:test' --tests "org.elasticsearch.transport.nio.SimpleNioTransportTests.testTcpHandshakeConnectionReset" -Dtests.seed=190C6A0B6FD13535 -Dtests.locale=es-EC -Dtests.timezone=Asia/Vladivostok -Druntime.java=21

### Does it reproduce?

Didn't try

### Applicable branches

7.17

### Failure history

https://gradle-enterprise.elastic.co/scans?search.tags=amazonlinux-2%2C7.17&search.timeZoneId=Europe%2FBucharest

### Failure excerpt

Many tests are failing for some time: https://gradle-enterprise.elastic.co/scans?search.relativeStartTime=P28D&search.tags=amazonlinux-2%2C7.17&search.timeZoneId=Europe%2FBucharest
```
java.net.UnknownHostException: i-0d800436281c0d777.us-west-2.compute.internal: i-0d800436281c0d777.us-west-2.compute.internal: Name or service not known	
    	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1647)	
    	at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.getHostname(MetricsSystemImpl.java:550)	
    	at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.configureSystem(MetricsSystemImpl.java:485)	
    	at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.configure(MetricsSystemImpl.java:481)	
    	at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.start(MetricsSystemImpl.java:188)	
    	at org.apache.hadoop.metrics2.impl.MetricsSystemImpl.init(MetricsSystemImpl.java:163)	
    	at org.apache.hadoop.metrics2.lib.DefaultMetricsSystem.init(DefaultMetricsSystem.java:54)	
    	at org.apache.hadoop.metrics2.lib.DefaultMetricsSystem.initialize(DefaultMetricsSystem.java:50)	
    	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1625)	
    	at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNode(MiniDFSCluster.java:1162)	
    	at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNodesAndSetConf(MiniDFSCluster.java:1037)	
    	at org.apache.hadoop.hdfs.MiniDFSCluster.initMiniDFSCluster(MiniDFSCluster.java:830)	
    	at org.apache.hadoop.hdfs.MiniDFSCluster.<init>(MiniDFSCluster.java:485)	
    	at org.apache.hadoop.hdfs.MiniDFSCluster$Builder.build(MiniDFSCluster.java:444)	
    	at hdfs.MiniHDFS.main(MiniHDFS.java:114)	
    Caused by: java.net.UnknownHostException: i-0d800436281c0d777.us-west-2.compute.internal: Name or service not known	
    	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)	
    	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933)	
    	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)	
    	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)	
    	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)	
    	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1642)	
    	... 14 more
```

**Comment by alex-spies** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/srf5ofrnaujkw

**Comment by mark-vieira** [comment]
Something is obviously weird with DNS on this system. I'll look into this.

**Comment by davidkyle** [comment]
Another failure today https://gradle-enterprise.elastic.co/s/k363d5qzblyn2

**Comment by mark-vieira** [comment]
Should be addressed by https://github.com/elastic/elasticsearch/pull/107907
