### ISSUE TITLE
Integration testing framework overrides System.out which breaks logging output to console

### ISSUE THREAD

**Issue by Unisay** [elastic/elasticsearch#10788]
First of all in a separate Thread `org.apache.lucene.util.TestRuleLimitSysouts` gets loaded:
```
at org.apache.lucene.util.TestRuleLimitSysouts.<clinit>(TestRuleLimitSysouts.java:79)
at org.apache.lucene.util.LuceneTestCase.<clinit>(LuceneTestCase.java:552)
at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:35)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:48)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:65)
at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:55)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:365)
at java.lang.Thread.run(Thread.java:745)
```
It contains following static init block:
```
  /**
   * We capture system output and error streams as early as possible because
   * certain components (like the Java logging system) steal these references and
   * never refresh them.
   * 
   * Also, for this exact reason, we cannot change delegate streams for every suite.
   * This isn't as elegant as it should be, but there's no workaround for this.
   */
  static {
    System.out.flush();
    System.err.flush();

    final String csn = Charset.defaultCharset().name();
    capturedSystemOut = new DelegateStream(System.out, csn, bytesWritten);
    capturedSystemErr = new DelegateStream(System.err, csn, bytesWritten);

    System.setOut(capturedSystemOut.printStream);
    System.setErr(capturedSystemErr.printStream);
  }
```
As you can see `System.out` is overridden here. 
The problem with `DelegateStream capturedSystemOut` which replaces original stream is that it also limits number of bytes that could be output:
```
private void validateClassAnnotations() {
    Class<?> target = RandomizedTest.getContext().getTargetClass();
    if (target.isAnnotationPresent(Limit.class)) {
      int bytes = target.getAnnotation(Limit.class).bytes();
      if (bytes < 0 || bytes > 1 * 1024 * 1024) {
        throw new AssertionError("The sysout limit is insane. Did you want to use "
            + "@" + LuceneTestCase.SuppressSysoutChecks.class.getName() + " annotation to "
            + "avoid sysout checks entirely?");
      }
    }
  }
``` 
and somehow removes line-ending chars (\n) so that all logging output which goes to console consists of many logging event clued together into one big line.

Since original output stream is never returned back it also affects all output which happens in the same JVM - e.g. log output formatting of other integration tests is broken.

**Comment by clintongormley** [comment]
Why not just use the annotation to suppress that check?  eg  https://github.com/elastic/elasticsearch/blob/master/src/test/java/org/elasticsearch/index/codec/postingformat/ElasticsearchPostingsFormatTest.java#L36

**Comment by Unisay** [comment]
@clintongormley 
Because code in `TestRuleLimitSysouts` which checks if annotation present is never executed when my test extends `ElasticsearchIntegrationTest`:

```
  // This method is not run 
  protected boolean isEnforced() {
    Class<?> target = RandomizedTest.getContext().getTargetClass();

    if (LuceneTestCase.VERBOSE || 
        LuceneTestCase.INFOSTREAM ||
        target.isAnnotationPresent(SuppressSysoutChecks.class)) {
      return false;
    }
    
    if (!target.isAnnotationPresent(Limit.class)) {
      return false;
    }

    return true;
  }
```

because this method in `TestRuleLimitSysouts`:
```
  @Override
  protected void before() throws Throwable {
    if (isEnforced()) {
      checkCaptureStreams();
    }
    ...
  }
```
is also never run, 
because `ElasticsearchIntegrationTest` doesn't extend `LuceneTestCase`

**Comment by clintongormley** [comment]
@javanna do you have any suggestions here?

**Comment by bbednarek** [comment]
@clintongormley @javanna any updates on this?

**Comment by clintongormley** [comment]
@rjernst what's your take on this?

**Comment by rjernst** [comment]
I'm not sure this is an issue anymore. ESIntegTestCase now (indirectly, through ESTestCase) extends LuceneTestCase.

**Comment by clintongormley** [comment]
thanks @Unisay - closing
