### ISSUE TITLE
[CI] DownsampleActionSingleNodeTests testCannotDownsampleWhileOtherDownsampleInProgress failing

### ISSUE THREAD

**Issue by slobodanadamovic** [elastic/elasticsearch#107904]
**Build scan:**
https://gradle-enterprise.elastic.co/s/ygv5qoxopbkqs/tests/:x-pack:plugin:downsample:test/org.elasticsearch.xpack.downsample.DownsampleActionSingleNodeTests/testCannotDownsampleWhileOtherDownsampleInProgress

**Reproduction line:**
```
./gradlew ':x-pack:plugin:downsample:test' --tests "org.elasticsearch.xpack.downsample.DownsampleActionSingleNodeTests.testCannotDownsampleWhileOtherDownsampleInProgress" -Dtests.seed=FCE9B44B6379CBC3 -Dtests.locale=ar-LY -Dtests.timezone=Africa/Ceuta -Druntime.java=21 -Dtests.fips.enabled=true
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.downsample.DownsampleActionSingleNodeTests#testCannotDownsampleWhileOtherDownsampleInProgress`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testCannotDownsampleWhileOtherDownsampleInProgress'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.downsample.DownsampleActionSingleNodeTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.elasticsearch.ElasticsearchException: downsample task [downsample-downsample-gsbskprihwaewu-0-351ms] failed

  at __randomizedtesting.SeedInfo.seed([FCE9B44B6379CBC3:DC864329F5D5E5D6]:0)
  at org.elasticsearch.xpack.downsample.TransportDownsampleAction$2.onResponse(TransportDownsampleAction.java:497)
  at org.elasticsearch.xpack.downsample.TransportDownsampleAction$2.onResponse(TransportDownsampleAction.java:489)
  at org.elasticsearch.persistent.PersistentTasksService$1.onNewClusterState(PersistentTasksService.java:195)
  at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onNewClusterState(ClusterStateObserver.java:375)
  at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.clusterChanged(ClusterStateObserver.java:226)
  at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListener(ClusterApplierService.java:561)
  at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:548)
  at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:506)
  at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:430)
  at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:155)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:917)
  at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:217)
  at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:183)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by kkrik-es** [comment]
Looking at the logs, there's a race between the two downsampling actions: the first manages to complete first so the second one fails as the downsample index can't be written any more:

```
[2024-04-25T15:59:36,589][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Downsampling task [downsample-downsample-gsbskprihwaewu-0-351ms on shard [gsbskprihwaewu][0] started
[2024-04-25T15:59:36,596][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Shard [gsbskprihwaewu][0] processed [2270] docs, created [535] downsample buckets
[2024-04-25T15:59:36,597][INFO ][o.e.c.r.a.AllocationService] [node_s_0] current.health="GREEN" message="Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[downsample-gsbskprihwaewu][0]]])." previous.health="YELLOW" reason="shards started [[downsample-gsbskprihwaewu][0]]"
[2024-04-25T15:59:36,689][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Shard [[gsbskprihwaewu][0]] successfully sent [2270], received source doc [535], indexed downsampled doc [535], failed [0], took [0s]
[2024-04-25T15:59:36,689][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Downsampling task [downsample-downsample-gsbskprihwaewu-0-351ms on shard [gsbskprihwaewu][0] completed
[2024-04-25T15:59:36,701][INFO ][o.e.x.d.TransportDownsampleAction] [node_s_0] Downsampling task [downsample-downsample-gsbskprihwaewu-0-351ms completed for shard [gsbskprihwaewu][0]
[2024-04-25T15:59:36,701][INFO ][o.e.x.d.TransportDownsampleAction] [node_s_0] All downsampling tasks completed [1]
[2024-04-25T15:59:36,751][WARN ][o.e.p.PersistentTasksClusterService] [node_s_0] trying to update state on task downsample-downsample-gsbskprihwaewu-0-351ms with unexpected allocation id 14
[2024-04-25T15:59:36,759][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Downsampling task [downsample-downsample-gsbskprihwaewu-0-351ms on shard [gsbskprihwaewu][0] started
[2024-04-25T15:59:36,764][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Shard [gsbskprihwaewu][0] processed [2270] docs, created [535] downsample buckets
[2024-04-25T15:59:36,776][ERROR][o.e.x.d.DownsampleShardIndexer] [node_s_0] Shard [[gsbskprihwaewu][0]] failed to populate downsample index. Failures: [{null=org.elasticsearch.cluster.block.ClusterBlockException: index [downsample-gsbskprihwaewu] blocked by: [FORBIDDEN/8/index write (api)];}]
[2024-04-25T15:59:36,777][INFO ][o.e.x.d.DownsampleShardIndexer] [node_s_0] Shard [[gsbskprihwaewu][0]] successfully sent [2270], received source doc [535], indexed downsampled doc [535], failed [535], took [0s]
```

**Comment by kkrik-es** [comment]
@slobodanadamovic was the branch up-to-date? I submitted a fix for this in #107213, wonder if it's included.

**Comment by slobodanadamovic** [comment]
@kkrik-es Yes. The branch was up-to-date. I have just merged a new changes from the main when I reported it.

**Comment by kkrik-es** [comment]
Thanks for confirming, lemme reopen the original bug and mark this as duplicate.
