### ISSUE TITLE
Test failure: GetUserPrivilegesResponseTests.testSerializationForCurrentVersion

### ISSUE THREAD

**Issue by edsavage** [elastic/elasticsearch#108285]
### CI Link

https://buildkite.com/elastic/elasticsearch-periodic-platform-support/builds/2633#018f4a59-f51e-476a-a6ac-a1aa31ac2646

### Repro line

REPRODUCE WITH: ./gradlew ':x-pack:plugin:core:test' --tests "org.elasticsearch.xpack.core.security.action.user.GetUserPrivilegesResponseTests.testSerializationForCurrentVersion" -Dtests.seed=BA6487ACE905F3F5 -Dtests.locale=zh-Hant-HK -Dtests.timezone=Asia/Aqtau -Druntime.java=21

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

org.elasticsearch.xpack.core.security.action.user.GetUserPrivilegesResponseTests > testSerializationForCurrentVersion FAILED
    java.lang.AssertionError: 
    Expected: <org.elasticsearch.xpack.core.security.action.user.GetUserPrivilegesResponse@8f05791f>
         but: was <org.elasticsearch.xpack.core.security.action.user.GetUserPrivilegesResponse@6db43f9>
        at __randomizedtesting.SeedInfo.seed([BA6487ACE905F3F5:7D3BD42FD3942A82]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2160)
        at org.elasticsearch.xpack.core.security.action.user.GetUserPrivilegesResponseTests.testSerializationForCurrentVersion(GetUserPrivilegesResponseTests.java:84)

**Comment by slobodanadamovic** [comment]
Fixed by #108255
