### ISSUE TITLE
BlockHash - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#108268]
Version: 8.13.x

```
{
    "query": "FROM `.ds-metrics-system` | EVAL bucket=DATE_TRUNC(1 hour, @timestamp) | STATS s=AVG(system.cpu.total.norm.pct) BY organization.itbs.name,bucket"
}
```
I was investigating a support issue and found this ESQL failed with that index.

```
{
    "type": "array_index_out_of_bounds_exception",
    "reason": "arraycopy: length -8573 is negative",
    "stack_trace": "java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -8573 is negative
at java.lang.System.arraycopy(Native Method)
at org.apache.lucene.util.BytesRefBuilder.append(BytesRefBuilder.java:79)
at org.apache.lucene.util.BytesRefBuilder.append(BytesRefBuilder.java:85)
at org.elasticsearch.compute.operator.BatchEncoder$DirectBytesRefs.readValueAtBlockIndex(BatchEncoder.java:615)
at org.elasticsearch.compute.operator.BatchEncoder$DirectEncoder.read(BatchEncoder.java:293)
at org.elasticsearch.compute.aggregation.blockhash.PackedValuesBlockHash$AddWork.addMultipleEntries(PackedValuesBlockHash.java:160)
at org.elasticsearch.compute.aggregation.blockhash.PackedValuesBlockHash$AddWork.add(PackedValuesBlockHash.java:133)
at org.elasticsearch.compute.aggregation.blockhash.PackedValuesBlockHash.add(PackedValuesBlockHash.java:77)
at org.elasticsearch.compute.aggregation.blockhash.PackedValuesBlockHash.add(PackedValuesBlockHash.java:72)
at org.elasticsearch.compute.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:102)
at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:214)
at org.elasticsearch.compute.operator.Driver.run(Driver.java:139)
at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:327)
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.lang.Thread.run(Thread.java:1583)
"
  },
  "status": 500
}
```

/cc @nik9000

**Comment by dnhatn** [comment]
I've opened #108283
