### ISSUE TITLE
[CI] DockerTests test500Readiness failing

### ISSUE THREAD

**Issue by joegallo** [elastic/elasticsearch#108523]
**Build scan:**
https://gradle-enterprise.elastic.co/s/jfhv4jdyalmjm/tests/:qa:packaging:destructiveDistroTest.default-docker/org.elasticsearch.packaging.test.DockerTests/test500Readiness

**Reproduction line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.packaging.test.DockerTests#test500Readiness`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test500Readiness'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.packaging.test.DockerTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at __randomizedtesting.SeedInfo.seed([C08005FCAB509171:10D51055CE402A98]:0)
  at org.junit.Assert.fail(Assert.java:87)
  at org.junit.Assert.assertTrue(Assert.java:42)
  at org.junit.Assert.assertTrue(Assert.java:53)
  at org.elasticsearch.packaging.test.DockerTests.test500Readiness(DockerTests.java:1222)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by joegallo** [comment]
[Some other failures](https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=America%2FNew_York&tests.container=org.elasticsearch.packaging.test.DockerTests&tests.test=test500Readiness)

**Comment by joegallo** [comment]
It got me on https://github.com/elastic/elasticsearch/pull/108518 and @benwtrent on https://github.com/elastic/elasticsearch/pull/108522 and https://github.com/elastic/elasticsearch/pull/107047.

**Comment by mark-vieira** [comment]
This test is related to the readiness probe so adding the core/infra label to this. Not sure if any changes have been made in that area lately. Also muting for now.

**Comment by mark-vieira** [comment]
@rjernst As far as I can tell the test waits for ES to report green, then attempts to connect on the readiness port and fails. Is there any scenario in which the node would report as green but the readiness port would not be listening? Is there some kind of race condition here?

**Comment by rjernst** [comment]
Readiness is orthogonal to health. It waits for 2 conditions to be met:
* A master node is elected
* File settings have been applied

If the cluster is green, a master node should be there. So that leaves file settings, but this test doesn't use file settings, so there shouldn't be any waiting.

I'm attempting to gather more information but dumping the ES log file before we fail the test:
https://github.com/elastic/elasticsearch/pull/108587
