### ISSUE TITLE
Stop - start sequence drives to IllegalThreadStateException

### ISSUE THREAD

**Issue by atomcat1978** [elastic/elasticsearch#10868]
After a node is created, and stop()-start() method is called sequentially, an IllegalThreadStateException is thrown.

Se below:
<pre>
Exception in thread "main" java.lang.IllegalThreadStateException
	at java.lang.Thread.start(Thread.java:705)
	at org.elasticsearch.indices.ttl.IndicesTTLService.doStart(IndicesTTLService.java:95)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:85)
	at org.elasticsearch.node.internal.InternalNode.start(InternalNode.java:245)
	at no.capraconsulting.esbug.App.main(App.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
</pre>

The problem seems to be in the `IndicesTTLService` class. Its `purgerThread` attribute is in `Thread.State.TERMINATED` as `purgerThread.start()` is invoked from `IndicesTTLService::start`.

**Comment by kimchy** [comment]
@atomcat1978 actually, we removed the ability to stop a node, and moved to just being able to create one and close it. The benefit of stopping and starting compared to recreating the node is negligible, since already almost all the "work" is done in the start method

**Comment by clintongormley** [comment]
Is there anything we need to fix here?

**Comment by atomcat1978** [comment]
@kimchy Ok. Maybe would be wise to clean up the code so that a noop is done? Getting an exception is not too nice:)

Actually, in IOC frameworks (like Spring) there might be a need to start and stop a wrapped node... I would have needed this functionality in integration tests, but ended up with node recreation at the end.

**Comment by kimchy** [comment]
++, thanks @atomcat1978, agreed on cleaning up the Node code here and remove its start/stop external semantics

**Comment by s1monw** [comment]
Node has only `start` and `close` I don't see what else needs to be fixed here? I will close this issue here since it's already cleaned up.
