### ISSUE TITLE
JavaClientApi create SynonymsRule failed

### ISSUE THREAD

**Issue by fengyonghui** [elastic/elasticsearch#108655]
### Elasticsearch Version

8.12

### Java Version

openjdk version "17.0.8.1"

### OS Version

windows 11

### Problem Description

java code
```
PutSynonymRuleRequest.Builder builder = new PutSynonymRuleRequest.Builder();
        builder.setId("my_synonyms_set")
                .ruleId("1")
                .synonyms("phone","苹果","华为");
        return esSynonymsClient.putSynonymRule(builder.build());
```
[es/synonyms.put_synonym_rule] failed: [illegal_argument_exception] Failed to parse: {"synonyms":["phone","苹果","华为"]}
at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:345) ~[elasticsearch-java-8.12.2.jar:na]
at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:147) ~[elasticsearch-java-8.12.2.jar:na]
at co.elastic.clients.elasticsearch.synonyms.ElasticsearchSynonymsClient.putSynonymRule(ElasticsearchSynonymsClient.java:302) ~[elasticsearch-java-8.12

### Steps to Reproduce

run the code, got follow exception:
co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/synonyms.put_synonym_rule] failed: [illegal_argument_exception] Failed to parse: {"synonyms":["phone","苹果","华为"]}
	at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:345) ~[elasticsearch-java-8.12.2.jar:na]
	at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:147) ~[elasticsearch-java-8.12.2.jar:na]
	at co.elastic.clients.elasticsearch.synonyms.ElasticsearchSynonymsClient.putSynonymRule(ElasticsearchSynonymsClient.java:302) ~[elasticsearch-java-8.12.2.jar:na]

**Comment by slobodanadamovic** [comment]
Thank you for the report. This is a bug in the [Elasticsearch specification](https://github.com/elastic/elasticsearch-specification/pull/2407) and it has already been fixed in elasticsearch-java 8.12.2 version.
