### ISSUE TITLE
`AssertionError` at `TopScoreDocCollector.java:75`

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#108614]
### CI Link

https://gradle-enterprise.elastic.co/s/fo7aqcomz2icg

### Repro line

N/A

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure history

N/A

### Failure excerpt

 Node crashed with the following in its logs:

```
java.lang.AssertionError
	at org.apache.lucene.core@9.10.0/org.apache.lucene.search.TopScoreDocCollector$SimpleTopScoreDocCollector$1.collect(TopScoreDocCollector.java:75)
	at org.apache.lucene.core@9.10.0/org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:277)
	at org.apache.lucene.core@9.10.0/org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:236)
	at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:45)
	at org.apache.lucene.core@9.10.0/org.apache.lucene.search.BulkScorer.score(BulkScorer.java:38)
	at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:431)
	at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:360)
	at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.search.internal.ContextIndexSearcher.lambda$search$4(ContextIndexSearcher.java:345)
	at org.apache.lucene.core@9.10.0/org.apache.lucene.search.TaskExecutor$TaskGroup.lambda$createTask$0(TaskExecutor.java:117)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
	at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

java.lang.AssertionError
	at org.apache.lucene.core@9.10.0/org.apache.lucene.search.TopScoreDocCollector$SimpleTopScoreDocCollector$1.collect(TopScoreDocCollector.java:75)
	at org.apache.lucene.core@9.10.0/org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:277)
	at org.apache.lucene.core@9.10.0/org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:236)
	at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:45)
	at org.apache.lucene.core@9.10.0/org.apache.lucene.search.BulkScorer.score(BulkScorer.java:38)
	at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:431)
	at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:360)
	at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.search.internal.ContextIndexSearcher.lambda$search$4(ContextIndexSearcher.java:345)
	at org.apache.lucene.core@9.10.0/org.apache.lucene.search.TaskExecutor$TaskGroup.lambda$createTask$0(TaskExecutor.java:117)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
	at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by benwtrent** [comment]
@DaveCTurner did the PR build have: https://github.com/elastic/elasticsearch/commit/e352345c233fc977212d2d6e386ac346c1f9603f  in it?

**Comment by DaveCTurner** [comment]
Yes. The `Source` link (bottom right of the below screenshot) links to https://github.com/DaveCTurner/elasticsearch/commits/0810cada602842398b2c13f12dc79240382dfa04/ which does indeed include that commit in its ancestry.

<img width="683" alt="image" src="https://github.com/elastic/elasticsearch/assets/5058284/61f9e96c-8d02-4cd3-8002-edccae4a676a">

**Comment by benwtrent** [comment]
OK, this is weird. Need to dig further. The failure log: https://es-delivery-stats.elastic.dev/app/r/s/3AZWr

The first failure is from `Apr 17, 2024 @ 07:59:55.955` from commit: https://github.com/elastic/elasticsearch/commits/2f9e753463909f820493fd191ecc8f8bffb30b29/

The negative score assertion is still tripping. It SEEMS to be due to negative scores in knn, but with: https://github.com/elastic/elasticsearch/commit/e352345c233fc977212d2d6e386ac346c1f9603f

I don't see how its possible :(.

**Comment by benwtrent** [comment]
Ah, 🤦 our format only changes merges. These failures should be fixed by: https://github.com/apache/lucene/pull/13356

**Comment by benwtrent** [comment]
This should be fixed with Lucene update.
