### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/bootstrap/Elasticsearch 

### ISSUE THREAD

**Issue by Mohamed70** [elastic/elasticsearch#10872]
Sorry, I was busy that's why I didn't answer on this issue:
  https://github.com/elastic/elasticsearch/issues/10259
So, I tested ZIP and TAR, and it doesn't works, it only works with the DEB archive.
When I run with zip or tar I get this:

    root@debian:/home/user/elasticsearch-1.5.2# ./bin/elasticsearch
    Exception in thread "main" java.lang.NoClassDefFoundError:     org/elasticsearch/bootstrap/Elasticsearch
    Caused by: java.lang.ClassNotFoundException: org.elasticsearch.bootstrap.Elasticsearch
	at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
    Could not find the main class: org.elasticsearch.bootstrap.Elasticsearch. Program will exit.

And I want to test the Marvel plugin but I also get a similar error:

    root@debian:/home/user/elasticsearch-1.5.2# ./bin/plugin -i elasticsearch/marvel/latest
    Exception in thread "main" java.lang.UnsupportedClassVersionError:      org/elasticsearch/plugins/PluginManager : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
    Could not find the main class: org.elasticsearch.plugins.PluginManager. Program will exit.

**Comment by dadoonet** [comment]
Let's follow up this discussion on #10259.

Closing.
