### ISSUE TITLE
[CI] ReactiveStorageDeciderDecisionTests testStoragePreventsAllocation failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#108753]
Test fails reproducibly with that seed but passes with others.

**Build scan:**
https://gradle-enterprise.elastic.co/s/nhsejuf474tiy/tests/:x-pack:plugin:autoscaling:test/org.elasticsearch.xpack.autoscaling.storage.ReactiveStorageDeciderDecisionTests/testStoragePreventsAllocation

**Reproduction line:**
```
./gradlew ':x-pack:plugin:autoscaling:test' --tests "org.elasticsearch.xpack.autoscaling.storage.ReactiveStorageDeciderDecisionTests.testStoragePreventsAllocation" -Dtests.seed=89B44AB7F8C090D8 -Dtests.locale=ga -Dtests.timezone=Asia/Bangkok -Druntime.java=21
```

**Applicable branches:**
main, 8.13

**Reproduces locally?:**
Yes

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.autoscaling.storage.ReactiveStorageDeciderDecisionTests#testStoragePreventsAllocation`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testStoragePreventsAllocation'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.autoscaling.storage.ReactiveStorageDeciderDecisionTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: sameInstance(<cluster uuid: _na_ [committed: false]
version: 0
state uuid: QCHxn_uYSOmMQN6Ux_n6eg
from_diff: false
meta data version: 0
   coordination_metadata:
      term: 0
      last_committed_config: VotingConfiguration{}
      last_accepted_config: VotingConfiguration{}
      voting tombstones: []
   [test-10]: v[13], mv[1], sv[1], av[1]
      0: p_term [1], isa_ids [pYjVIQAETHe3rDkgR6Ju7Q, UuBw-CyoTyOhv96_QobeKA]
      1: p_term [1], isa_ids [n1VVJqtNTgmQpBFnKTYbJQ, eZ1cHs4_RSWYxigqv4kDlQ]
      2: p_term [1], isa_ids [3Om59eBfRy62YWoBY_Offw, -f5xbZ59T9qdfOPUSrvldw]
      3: p_term [1], isa_ids [CAnFlTDQSiSA-4xMxdOAKA, 0NCtTNXGSXy8RhpJf9qNpA]
      4: p_term [1], isa_ids [QegCYOX6TC-YmeAEZbG70w, 5FwylE7gRr2A1PcBO69iDg]
metadata customs:
   index-graveyard: IndexGraveyard[[]]
nodes (node-left generation: 0):
   {hot_0}{hot_0}{aoHJMpKgSEyqLSSjfw2iuQ}{Sl0nESanSxuuLFB6zKjfCw}{0.0.0.0}{0.0.0.0:6}{h}{8.13.5}{7000099-8503000}
   {hot_1}{hot_1}{uzOTVUv2TMuqdOxxbQztMQ}{gop_jV3jQuCJZDPBiyOKUA}{0.0.0.0}{0.0.0.0:7}{h}{8.13.5}{7000099-8503000}
   {hot_2}{hot_2}{Kx7lCF-_TnqPskcORvX3-Q}{FA0QkWGwR9G_Urrv_tAtEQ}{0.0.0.0}{0.0.0.0:8}{h}{8.13.5}{7000099-8503000}
   {hot_3}{hot_3}{m_gus2LPREeinUDro0kqpQ}{AP-8G46TTMeuR_kt1BINCA}{0.0.0.0}{0.0.0.0:9}{h}{8.13.5}{7000099-8503000}
   {hot_4}{hot_4}{WykQ91g2QKShygXpeeqj6g}{gNaal1_WSROwQ-ih_pdxXg}{0.0.0.0}{0.0.0.0:10}{h}{8.13.5}{7000099-8503000}
   {warm_0}{warm_0}{vhHbWHExREu3M5VNXMvAJA}{67B-MNcZSeCCD0l5Ltzd1w}{0.0.0.0}{0.0.0.0:11}{w}{8.13.5}{7000099-8503000}
cluster features:
   hot_0: []
   hot_1: []
   hot_2: []
   hot_3: []
   hot_4: []
   warm_0: []
routing_table (version 0):
-- index [[test-10]]
----shard_id [test-10][0]
--------[test-10][0], node[hot_2], [P], s[STARTED], a[id=pYjVIQAETHe3rDkgR6Ju7Q], failed_attempts[0]
--------[test-10][0], node[hot_4], [R], s[STARTED], a[id=UuBw-CyoTyOhv96_QobeKA], failed_attempts[0]
----shard_id [test-10][1]
--------[test-10][1], node[hot_1], [P], s[STARTED], a[id=n1VVJqtNTgmQpBFnKTYbJQ], failed_attempts[0]
--------[test-10][1], node[hot_2], [R], s[STARTED], a[id=eZ1cHs4_RSWYxigqv4kDlQ], failed_attempts[0]
----shard_id [test-10][2]
--------[test-10][2], node[hot_0], [P], s[STARTED], a[id=-f5xbZ59T9qdfOPUSrvldw], failed_attempts[0]
--------[test-10][2], node[hot_2], relocating [hot_4], [R], s[RELOCATING], a[id=3Om59eBfRy62YWoBY_Offw, rId=n6g4YnKWQSaZEzuY4ZWqaw], failed_attempts[0], expected_shard_size[1]
----shard_id [test-10][3]
--------[test-10][3], node[hot_1], [P], s[STARTED], a[id=CAnFlTDQSiSA-4xMxdOAKA], failed_attempts[0]
--------[test-10][3], node[hot_3], [R], s[STARTED], a[id=0NCtTNXGSXy8RhpJf9qNpA], failed_attempts[0]
----shard_id [test-10][4]
--------[test-10][4], node[hot_0], [P], s[STARTED], a[id=5FwylE7gRr2A1PcBO69iDg], failed_attempts[0]
--------[test-10][4], node[hot_3], [R], s[STARTED], a[id=QegCYOX6TC-YmeAEZbG70w], failed_attempts[0]

routing_nodes:
-----node_id[hot_1][V]
--------[test-10][1], node[hot_1], [P], s[STARTED], a[id=n1VVJqtNTgmQpBFnKTYbJQ], failed_attempts[0]
--------[test-10][3], node[hot_1], [P], s[STARTED], a[id=CAnFlTDQSiSA-4xMxdOAKA], failed_attempts[0]
-----node_id[hot_0][V]
--------[test-10][2], node[hot_0], [P], s[STARTED], a[id=-f5xbZ59T9qdfOPUSrvldw], failed_attempts[0]
--------[test-10][4], node[hot_0], [P], s[STARTED], a[id=5FwylE7gRr2A1PcBO69iDg], failed_attempts[0]
-----node_id[warm_0][V]
-----node_id[hot_3][V]
--------[test-10][3], node[hot_3], [R], s[STARTED], a[id=0NCtTNXGSXy8RhpJf9qNpA], failed_attempts[0]
--------[test-10][4], node[hot_3], [R], s[STARTED], a[id=QegCYOX6TC-YmeAEZbG70w], failed_attempts[0]
-----node_id[hot_2][V]
--------[test-10][0], node[hot_2], [P], s[STARTED], a[id=pYjVIQAETHe3rDkgR6Ju7Q], failed_attempts[0]
--------[test-10][1], node[hot_2], [R], s[STARTED], a[id=eZ1cHs4_RSWYxigqv4kDlQ], failed_attempts[0]
--------[test-10][2], node[hot_2], relocating [hot_4], [R], s[RELOCATING], a[id=3Om59eBfRy62YWoBY_Offw, rId=n6g4YnKWQSaZEzuY4ZWqaw], failed_attempts[0], expected_shard_size[1]
-----node_id[hot_4][V]
--------[test-10][0], node[hot_4], [R], s[STARTED], a[id=UuBw-CyoTyOhv96_QobeKA], failed_attempts[0]
--------[test-10][2], node[hot_4], relocating [hot_2], [R], recovery_source[peer recovery], s[INITIALIZING], a[id=n6g4YnKWQSaZEzuY4ZWqaw, rId=3Om59eBfRy62YWoBY_Offw], failed_attempts[0], expected_shard_size[1]
---- unassigned
>)
     but: was <cluster uuid: _na_ [committed: false]
version: 0
state uuid: QCHxn_uYSOmMQN6Ux_n6eg
from_diff: false
meta data version: 0
   coordination_metadata:
      term: 0
      last_committed_config: VotingConfiguration{}
      last_accepted_config: VotingConfiguration{}
      voting tombstones: []
   [test-10]: v[14], mv[1], sv[1], av[1]
      0: p_term [1], isa_ids [pYjVIQAETHe3rDkgR6Ju7Q, UuBw-CyoTyOhv96_QobeKA]
      1: p_term [1], isa_ids [n1VVJqtNTgmQpBFnKTYbJQ, eZ1cHs4_RSWYxigqv4kDlQ]
      2: p_term [1], isa_ids [n6g4YnKWQSaZEzuY4ZWqaw, -f5xbZ59T9qdfOPUSrvldw]
      3: p_term [1], isa_ids [CAnFlTDQSiSA-4xMxdOAKA, 0NCtTNXGSXy8RhpJf9qNpA]
      4: p_term [1], isa_ids [QegCYOX6TC-YmeAEZbG70w, 5FwylE7gRr2A1PcBO69iDg]
metadata customs:
   index-graveyard: IndexGraveyard[[]]
nodes (node-left generation: 0):
   {hot_0}{hot_0}{aoHJMpKgSEyqLSSjfw2iuQ}{Sl0nESanSxuuLFB6zKjfCw}{0.0.0.0}{0.0.0.0:6}{h}{8.13.5}{7000099-8503000}
   {hot_1}{hot_1}{uzOTVUv2TMuqdOxxbQztMQ}{gop_jV3jQuCJZDPBiyOKUA}{0.0.0.0}{0.0.0.0:7}{h}{8.13.5}{7000099-8503000}
   {hot_2}{hot_2}{Kx7lCF-_TnqPskcORvX3-Q}{FA0QkWGwR9G_Urrv_tAtEQ}{0.0.0.0}{0.0.0.0:8}{h}{8.13.5}{7000099-8503000}
   {hot_3}{hot_3}{m_gus2LPREeinUDro0kqpQ}{AP-8G46TTMeuR_kt1BINCA}{0.0.0.0}{0.0.0.0:9}{h}{8.13.5}{7000099-8503000}
   {hot_4}{hot_4}{WykQ91g2QKShygXpeeqj6g}{gNaal1_WSROwQ-ih_pdxXg}{0.0.0.0}{0.0.0.0:10}{h}{8.13.5}{7000099-8503000}
   {warm_0}{warm_0}{vhHbWHExREu3M5VNXMvAJA}{67B-MNcZSeCCD0l5Ltzd1w}{0.0.0.0}{0.0.0.0:11}{w}{8.13.5}{7000099-8503000}
cluster features:
   hot_0: []
   hot_1: []
   hot_2: []
   hot_3: []
   hot_4: []
   warm_0: []
routing_table (version 0):
-- index [[test-10]]
----shard_id [test-10][0]
--------[test-10][0], node[hot_2], [P], s[STARTED], a[id=pYjVIQAETHe3rDkgR6Ju7Q], failed_attempts[0]
--------[test-10][0], node[hot_4], [R], s[STARTED], a[id=UuBw-CyoTyOhv96_QobeKA], failed_attempts[0]
----shard_id [test-10][1]
--------[test-10][1], node[hot_1], [P], s[STARTED], a[id=n1VVJqtNTgmQpBFnKTYbJQ], failed_attempts[0]
--------[test-10][1], node[hot_2], [R], s[STARTED], a[id=eZ1cHs4_RSWYxigqv4kDlQ], failed_attempts[0]
----shard_id [test-10][2]
--------[test-10][2], node[hot_0], [P], s[STARTED], a[id=-f5xbZ59T9qdfOPUSrvldw], failed_attempts[0]
--------[test-10][2], node[hot_4], [R], s[STARTED], a[id=n6g4YnKWQSaZEzuY4ZWqaw], failed_attempts[0]
----shard_id [test-10][3]
--------[test-10][3], node[hot_1], [P], s[STARTED], a[id=CAnFlTDQSiSA-4xMxdOAKA], failed_attempts[0]
--------[test-10][3], node[hot_3], [R], s[STARTED], a[id=0NCtTNXGSXy8RhpJf9qNpA], failed_attempts[0]
----shard_id [test-10][4]
--------[test-10][4], node[hot_0], [P], s[STARTED], a[id=5FwylE7gRr2A1PcBO69iDg], failed_attempts[0]
--------[test-10][4], node[hot_3], [R], s[STARTED], a[id=QegCYOX6TC-YmeAEZbG70w], failed_attempts[0]

routing_nodes:
-----node_id[hot_1][V]
--------[test-10][1], node[hot_1], [P], s[STARTED], a[id=n1VVJqtNTgmQpBFnKTYbJQ], failed_attempts[0]
--------[test-10][3], node[hot_1], [P], s[STARTED], a[id=CAnFlTDQSiSA-4xMxdOAKA], failed_attempts[0]
-----node_id[hot_0][V]
--------[test-10][2], node[hot_0], [P], s[STARTED], a[id=-f5xbZ59T9qdfOPUSrvldw], failed_attempts[0]
--------[test-10][4], node[hot_0], [P], s[STARTED], a[id=5FwylE7gRr2A1PcBO69iDg], failed_attempts[0]
-----node_id[warm_0][V]
-----node_id[hot_3][V]
--------[test-10][3], node[hot_3], [R], s[STARTED], a[id=0NCtTNXGSXy8RhpJf9qNpA], failed_attempts[0]
--------[test-10][4], node[hot_3], [R], s[STARTED], a[id=QegCYOX6TC-YmeAEZbG70w], failed_attempts[0]
-----node_id[hot_2][V]
--------[test-10][0], node[hot_2], [P], s[STARTED], a[id=pYjVIQAETHe3rDkgR6Ju7Q], failed_attempts[0]
--------[test-10][1], node[hot_2], [R], s[STARTED], a[id=eZ1cHs4_RSWYxigqv4kDlQ], failed_attempts[0]
-----node_id[hot_4][V]
--------[test-10][0], node[hot_4], [R], s[STARTED], a[id=UuBw-CyoTyOhv96_QobeKA], failed_attempts[0]
--------[test-10][2], node[hot_4], [R], s[STARTED], a[id=n6g4YnKWQSaZEzuY4ZWqaw], failed_attempts[0]
---- unassigned
>

  at __randomizedtesting.SeedInfo.seed([89B44AB7F8C090D8:B1FCDDED408F1D41]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
  at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2119)
  at org.elasticsearch.xpack.autoscaling.storage.ReactiveStorageDeciderDecisionTests.testStoragePreventsAllocation(ReactiveStorageDeciderDecisionTests.java:235)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by idegtiarenko** [comment]
This failure is the same as in https://github.com/elastic/elasticsearch/issues/105957 and is fixed by the change proposed there
