### ISSUE TITLE
Failures in elasticsearch / periodic / platform-support / 7.17 / windows-2016 / checkPart1 / platform-support-windows

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#108755]
### CI Link

https://buildkite.com/elastic/elasticsearch-periodic-platform-support/builds/2772#018f84d1-26b9-46f0-9f59-84a24d4eacf8

### Repro line

none

### Does it reproduce?

No

### Applicable branches

7.17

### Failure excerpt

Execution failed for task ':test:external-modules:test-error-query:yamlRestTest'.
> Can't run bin script: `elasticsearch-keystore` does not exist. Is this the distribution you expect it to be ?
* Try:
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test:external-modules:test-error-query:yamlRestTest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:130)
     [...]
Caused by: org.elasticsearch.gradle.testclusters.TestClustersException: Can't run bin script: `elasticsearch-keystore` does not exist. Is this the distribution you expect it to be ?
        at org.elasticsearch.gradle.testclusters.ElasticsearchNode.runElasticsearchBinScriptWithInput(ElasticsearchNode.java:776)
        at org.elasticsearch.gradle.testclusters.ElasticsearchNode.runElasticsearchBinScript(ElasticsearchNode.java:808)
        at org.elasticsearch.gradle.testclusters.ElasticsearchNode.start(ElasticsearchNode.java:541)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.elasticsearch.gradle.testclusters.ElasticsearchCluster.start(ElasticsearchCluster.java:323)
        at org.elasticsearch.gradle.testclusters.TestClustersRegistry.maybeStartCluster(TestClustersRegistry.java:37)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.elasticsearch.gradle.testclusters.TestClustersPlugin$TestClustersHookPlugin$1.beforeActions(TestClustersPlugin.java:209)
       [...]

**Comment by cbuescher** [comment]
This one looks similar, not Windows 2016 but  "[elasticsearch / periodic / platform-support / 7.17 / oraclelinux-7 / platform-support-unix](https://gradle-enterprise.elastic.co/s/ljerycd2abzki)" so worth mentioning: https://gradle-enterprise.elastic.co/s/ljerycd2abzk

**Comment by mark-vieira** [comment]
Looks like some issue either copying the test distribution or perhaps in hardlinking it. Found a few instances of this happening for the [async-search module](https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=*%0A%3E%20Can%27t%20run%20bin%20script:%20%60elasticsearch-keystore%60%20does%20not%20exist.%20Is%20this%20the%20distribution%20you%20expect%20it%20to%20be%20%3F&search.relativeStartTime=P90D&search.timeZoneId=America%2FLos_Angeles#) but none in the past month and all on 7.17. There nothing out of the ordinary there that would explain this behavior.

**Comment by mark-vieira** [comment]
I can't find any recent instances of this. Closing.
