### ISSUE TITLE
failed to create engine

### ISSUE THREAD

**Issue by Sic9527** [elastic/elasticsearch#108842]
### Elasticsearch Version

7.17.13

### Java Version

openjdk 20.0.2 2023-07-18 OpenJDK Runtime Environment (build 20.0.2+9-78) OpenJDK 64-Bit Server VM (build 20.0.2+9-78, mixed mode, sharing)

### OS Version

centOS 7.8

### Problem Description

{"type": "server", "timestamp": "2024-05-21T01:32:09,968Z", "level": "WARN", "component": "o.e.i.t.Translog", "cluster.name": "docker-cluster", "node.name": "elasticsearch-bf9ddf677-x2m42", "message": " [records-all-20240521][0] failed to delete temp file /usr/share/elasticsearch/data/nodes/0/indices/KTLY3cJkR5CWKQvVKUeFEg/0/translog/translog-10626317916496319544.ckp", "cluster.uuid": "3ryH_a0PQUGfor5v_I8cTA", "node.id": "_6YccP_mRDaSZKx5UaR1PQ" , 
"stacktrace": ["java.nio.file.NoSuchFileException: /usr/share/elasticsearch/data/nodes/0/indices/KTLY3cJkR5CWKQvVKUeFEg/0/translog/translog-10626317916496319544.ckp",
"at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]",
"at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]",
"at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]",
"at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:291) ~[?:?]",
"at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:104) ~[?:?]",
"at java.nio.file.Files.delete(Files.java:1151) ~[?:?]",
"at org.elasticsearch.index.translog.Translog.copyCheckpointTo(Translog.java:310) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:282) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.translog.Translog.<init>(Translog.java:188) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:546) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:226) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:199) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:14) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:2064) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:2028) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:472) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:90) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:436) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:88) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:2361) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.17.13.jar:7.17.13]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]",
"at java.lang.Thread.run(Thread.java:1623) [?:?]"] }
{"type": "server", "timestamp": "2024-05-21T01:32:10,046Z", "level": "WARN", "component": "o.e.i.c.IndicesClusterStateService", "cluster.name": "docker-cluster", "node.name": "elasticsearch-bf9ddf677-x2m42", "message": "[records-all-20240521][3] marking and sending shard failed due to [failed recovery]", "cluster.uuid": "3ryH_a0PQUGfor5v_I8cTA", "node.id": "_6YccP_mRDaSZKx5UaR1PQ" , 
"stacktrace": ["org.elasticsearch.indices.recovery.RecoveryFailedException: [sw_records-all-20240521][3]: Recovery failed on {elasticsearch-bf9ddf677-x2m42}{_6YccP_mRDaSZKx5UaR1PQ}{DM4GX44TSqu_35UFlD2iAQ}{10.42.0.34}{10.42.0.34:9300}{cdfhilmrstw}{ml.machine_memory=6442450944, xpack.installed=true, transform.node=true, ml.max_open_jobs=512, ml.max_jvm_size=2147483648}",
"at org.elasticsearch.index.shard.IndexShard.lambda$executeRecovery$21(IndexShard.java:3246) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:144) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.lambda$recoveryListener$6(StoreRecovery.java:385) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:144) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:439) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:88) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:2361) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.17.13.jar:7.17.13]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]",
"at java.lang.Thread.run(Thread.java:1623) [?:?]",
"Caused by: org.elasticsearch.index.shard.IndexShardRecoveryException: failed to recover from gateway",
"at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:477) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:90) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:436) ~[elasticsearch-7.17.13.jar:7.17.13]",
"... 8 more",
"Caused by: org.elasticsearch.index.engine.EngineCreationFailureException: failed to create engine",
"at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:251) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:199) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:14) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:2064) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:2028) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:472) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:90) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:436) ~[elasticsearch-7.17.13.jar:7.17.13]",
"... 8 more",
"Caused by: java.io.IOException: Operation not supported",
"at sun.nio.fs.LinuxNativeDispatcher.directCopy0(Native Method) ~[?:?]",
"at sun.nio.fs.LinuxFileSystem.directCopy(LinuxFileSystem.java:159) ~[?:?]",
"at sun.nio.fs.UnixFileSystem.copyFile(UnixFileSystem.java:683) ~[?:?]",
"at sun.nio.fs.UnixFileSystem.copy(UnixFileSystem.java:1061) ~[?:?]",
"at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:300) ~[?:?]",
"at java.nio.file.Files.copy(Files.java:1303) ~[?:?]",
"at org.elasticsearch.index.translog.Translog.copyCheckpointTo(Translog.java:301) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:282) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.translog.Translog.<init>(Translog.java:188) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:546) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:226) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:199) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:14) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:2064) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:2028) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:472) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:90) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:436) ~[elasticsearch-7.17.13.jar:7.17.13]",
"... 8 more"] }

### Steps to Reproduce

"type": "server", "timestamp": "2024-05-21T01:27:20,854Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "elasticsearch-bf9ddf677-x2m42", "message": "using [1] data paths, mounts [[/usr/share/elasticsearch/data (nfs-server-hostname:/var/nfs-share/elasticsearch-data-volume-pvc-2a8071cb-73a4-46d3-9bd1-1b32a45dcd55)]], net usable_space [151.9gb], net total_space [165.8gb], types [nfs4]" }

### Logs (if relevant)

{"type": "server", "timestamp": "2024-05-21T01:32:09,968Z", "level": "WARN", "component": "o.e.i.t.Translog", "cluster.name": "docker-cluster", "node.name": "elasticsearch-bf9ddf677-x2m42", "message": " [records-all-20240521][0] failed to delete temp file /usr/share/elasticsearch/data/nodes/0/indices/KTLY3cJkR5CWKQvVKUeFEg/0/translog/translog-10626317916496319544.ckp", "cluster.uuid": "3ryH_a0PQUGfor5v_I8cTA", "node.id": "_6YccP_mRDaSZKx5UaR1PQ" , 
"stacktrace": ["java.nio.file.NoSuchFileException: /usr/share/elasticsearch/data/nodes/0/indices/KTLY3cJkR5CWKQvVKUeFEg/0/translog/translog-10626317916496319544.ckp",
"at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]",
"at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]",
"at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]",
"at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:291) ~[?:?]",
"at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:104) ~[?:?]",
"at java.nio.file.Files.delete(Files.java:1151) ~[?:?]",
"at org.elasticsearch.index.translog.Translog.copyCheckpointTo(Translog.java:310) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:282) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.translog.Translog.<init>(Translog.java:188) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:546) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:226) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:199) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:14) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:2064) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:2028) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:472) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:90) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:436) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:88) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:2361) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.17.13.jar:7.17.13]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]",
"at java.lang.Thread.run(Thread.java:1623) [?:?]"] }
{"type": "server", "timestamp": "2024-05-21T01:32:10,046Z", "level": "WARN", "component": "o.e.i.c.IndicesClusterStateService", "cluster.name": "docker-cluster", "node.name": "elasticsearch-bf9ddf677-x2m42", "message": "[records-all-20240521][3] marking and sending shard failed due to [failed recovery]", "cluster.uuid": "3ryH_a0PQUGfor5v_I8cTA", "node.id": "_6YccP_mRDaSZKx5UaR1PQ" , 
"stacktrace": ["org.elasticsearch.indices.recovery.RecoveryFailedException: [sw_records-all-20240521][3]: Recovery failed on {elasticsearch-bf9ddf677-x2m42}{_6YccP_mRDaSZKx5UaR1PQ}{DM4GX44TSqu_35UFlD2iAQ}{10.42.0.34}{10.42.0.34:9300}{cdfhilmrstw}{ml.machine_memory=6442450944, xpack.installed=true, transform.node=true, ml.max_open_jobs=512, ml.max_jvm_size=2147483648}",
"at org.elasticsearch.index.shard.IndexShard.lambda$executeRecovery$21(IndexShard.java:3246) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:144) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.lambda$recoveryListener$6(StoreRecovery.java:385) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:144) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:439) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:88) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:2361) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777) [elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.17.13.jar:7.17.13]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]",
"at java.lang.Thread.run(Thread.java:1623) [?:?]",
"Caused by: org.elasticsearch.index.shard.IndexShardRecoveryException: failed to recover from gateway",
"at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:477) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:90) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:436) ~[elasticsearch-7.17.13.jar:7.17.13]",
"... 8 more",
"Caused by: org.elasticsearch.index.engine.EngineCreationFailureException: failed to create engine",
"at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:251) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:199) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:14) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:2064) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:2028) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:472) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:90) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:436) ~[elasticsearch-7.17.13.jar:7.17.13]",
"... 8 more",
"Caused by: java.io.IOException: Operation not supported",
"at sun.nio.fs.LinuxNativeDispatcher.directCopy0(Native Method) ~[?:?]",
"at sun.nio.fs.LinuxFileSystem.directCopy(LinuxFileSystem.java:159) ~[?:?]",
"at sun.nio.fs.UnixFileSystem.copyFile(UnixFileSystem.java:683) ~[?:?]",
"at sun.nio.fs.UnixFileSystem.copy(UnixFileSystem.java:1061) ~[?:?]",
"at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:300) ~[?:?]",
"at java.nio.file.Files.copy(Files.java:1303) ~[?:?]",
"at org.elasticsearch.index.translog.Translog.copyCheckpointTo(Translog.java:301) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:282) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.translog.Translog.<init>(Translog.java:188) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:546) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:226) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:199) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:14) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:2064) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:2028) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:472) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:90) ~[elasticsearch-7.17.13.jar:7.17.13]",
"at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:436) ~[elasticsearch-7.17.13.jar:7.17.13]",
"... 8 more"] }

**Comment by gbanasiak** [comment]
Judging by `using [1] data paths, mounts [[/usr/share/elasticsearch/data (nfs-server-hostname:/var/nfs-share/elasticsearch-data-volume-pvc-2a8071cb-73a4-46d3-9bd1-1b32a45dcd55)]` and this stack trace:

```
"Caused by: java.io.IOException: Operation not supported",
"at sun.nio.fs.LinuxNativeDispatcher.directCopy0(Native Method) ~[?:?]",
"at sun.nio.fs.LinuxFileSystem.directCopy(LinuxFileSystem.java:159) ~[?:?]",
"at sun.nio.fs.UnixFileSystem.copyFile(UnixFileSystem.java:683) ~[?:?]",
"at sun.nio.fs.UnixFileSystem.copy(UnixFileSystem.java:1061) ~[?:?]",
"at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:300) ~[?:?]",
"at java.nio.file.Files.copy(Files.java:1303) ~[?:?]",
```

I'm suspecting the problem is with how your NFS mount is configured. Can you reproduce the problem without NFS using local storage? If not, please check your NFS setup.

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

Specifically, the exception `java.io.IOException: Operation not supported` is coming from your operating environment and indicates that there is some fundamental problem, possibly related to system configuration or possibly a hardware fault. In either case, this isn't an Elasticsearch bug - failing to start the shard is the right way to react in this situation.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
