### ISSUE TITLE
[CI] Failure in org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=transform/transforms_start_stop/Test stop missing transform}

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#108959]
It's a bit hard to figure out what exactly happened, here, but there's lots of failures around yaml tests

Failure in `[elasticsearch / periodic / platform-support / 8.14 / ubuntu-2004-aarch64 / checkPart3 / platform-support-arm](https://gradle-enterprise.elastic.co/s/xw4dpy6yvnwia)` - https://gradle-enterprise.elastic.co/s/xw4dpy6yvnwia

First failure reproduction `./gradlew ':x-pack:plugin:yamlRestTest' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=ml/inference_crud/Test force delete given model with alias referenced by pipeline}" -Dtests.seed=858DD2DE27314F95 -Dtests.locale=zh-Hant-HK -Dtests.timezone=Africa/Douala -Druntime.java=22`

Stack trace
```
org.elasticsearch.xpack.test.rest.XPackRestIT > test {p0=transform/transforms_start_stop/Test stop missing transform} FAILED	
    java.lang.AssertionError: Failure at [transform/transforms_start_stop:2]: expected [2xx] status code but api [indices.create] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [airline-data/3cfF4iQQRq60bIYSf3lmPg] already exists","index_uuid":"3cfF4iQQRq60bIYSf3lmPg","index":"airline-data","stack_trace":"[airline-data/3cfF4iQQRq60bIYSf3lmPg] org.elasticsearch.ResourceAlreadyExistsException: index [airline-data/3cfF4iQQRq60bIYSf3lmPg] already exists\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validateIndexName(MetadataCreateIndexService.java:177)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validate(MetadataCreateIndexService.java:1371)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:345)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:300)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$UnbatchedExecutor.execute(MasterService.java:550)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1039)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1004)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:232)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1645)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.ActionListener.run(ActionListener.java:356)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.run(MasterService.java:1642)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$5.lambda$doRun$0(MasterService.java:1237)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.ActionListener.run(ActionListener.java:356)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$5.doRun(MasterService.java:1216)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1570)\n"}],"type":"resource_already_exists_exception","reason":"index [airline-data/3cfF4iQQRq60bIYSf3lmPg] already exists","index_uuid":"3cfF4iQQRq60bIYSf3lmPg","index":"airline-data","stack_trace":"[airline-data/3cfF4iQQRq60bIYSf3lmPg] org.elasticsearch.ResourceAlreadyExistsException: index [airline-data/3cfF4iQQRq60bIYSf3lmPg] already exists\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validateIndexName(MetadataCreateIndexService.java:177)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validate(MetadataCreateIndexService.java:1371)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:345)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:300)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$UnbatchedExecutor.execute(MasterService.java:550)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1039)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1004)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:232)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1645)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.ActionListener.run(ActionListener.java:356)\n\tat org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$Ba…	
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:610)	
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:544)
...
```

**Comment by nik9000** [comment]
I agree getting the first one is the right way.

Sorry to file a dupe. Or potential dupe. Good luck!

**Comment by prwhelan** [comment]
Ah thank you, I wasn't sure if that was correct or not.  When we fix the duplicate ticket, I'll double back and make sure this issue isn't seen anymore either.
