### ISSUE TITLE
Test failure in DocValuesCodecDuelTest

### ISSUE THREAD

**Issue by kderusso** [elastic/elasticsearch#108928]
### CI Link

https://buildkite.com/elastic/elasticsearch-pull-request/builds/20270#018fa1c7-9788-4e09-b43b-aac6156a18e5

### Repro line

```
./gradlew ':server:test' --tests "org.elasticsearch.index.codec.tsdb.DocValuesCodecDuelTests.testDuel" -Dtests.seed=C34B003B0029E2E6 -Dtests.locale=ms-MY -Dtests.timezone=America/Indiana/Marengo -Druntime.java=22
```

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

This occurred in my PR branch but also occurs in `main`.  
Potentially related to: https://github.com/elastic/elasticsearch/pull/108853

```
> Task :server:test
--
  |  
  | REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.index.codec.tsdb.DocValuesCodecDuelTests.testDuel" -Dtests.seed=C34B003B0029E2E6 -Dtests.locale=ms-MY -Dtests.timezone=America/Indiana/Marengo -Druntime.java=22
  |  
  | org.elasticsearch.index.codec.tsdb.DocValuesCodecDuelTests > testDuel FAILED
  | java.io.EOFException
  | at __randomizedtesting.SeedInfo.seed([C34B003B0029E2E6:8FCBBA3B5EA17AF4]:0)
  | at org.apache.lucene.store.ByteBuffersDataInput.readByte(ByteBuffersDataInput.java:113)
  | at org.apache.lucene.store.DataInput.readInt(DataInput.java:97)
  | at org.apache.lucene.store.ByteBuffersDataInput.readInt(ByteBuffersDataInput.java:200)
  | at org.apache.lucene.store.DataInput.readLong(DataInput.java:184)
  | at org.apache.lucene.store.ByteBuffersDataInput.readLong(ByteBuffersDataInput.java:212)
  | at org.apache.lucene.store.ByteBuffersIndexInput.readLong(ByteBuffersIndexInput.java:127)
  | at org.apache.lucene.tests.store.MockIndexInputWrapper.readLong(MockIndexInputWrapper.java:178)
  | at org.apache.lucene.codecs.lucene90.IndexedDISI$Method$2.advanceWithinBlock(IndexedDISI.java:623)
  | at org.apache.lucene.codecs.lucene90.IndexedDISI.advance(IndexedDISI.java:446)
  | at org.apache.lucene.codecs.lucene90.Lucene90DocValuesProducer$21.advance(Lucene90DocValuesProducer.java:919)
  | at org.elasticsearch.index.codec.tsdb.DocValuesCodecDuelTests.assertSortedDocValues(DocValuesCodecDuelTests.java:142)
  | at org.elasticsearch.index.codec.tsdb.DocValuesCodecDuelTests.testDuel(DocValuesCodecDuelTests.java:113)
  |  
  |  
  | Suite: Test class org.elasticsearch.index.codec.tsdb.DocValuesCodecDuelTests
  | 1> [2024-05-22T15:43:51,858][INFO ][o.e.i.c.t.DocValuesCodecDuelTests] [testDuel] before test
  | 1> [2024-05-22T15:44:05,295][INFO ][o.e.i.c.t.DocValuesCodecDuelTests] [testDuel] after test
  | 2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.index.codec.tsdb.DocValuesCodecDuelTests.testDuel" -Dtests.seed=C34B003B0029E2E6 -Dtests.locale=ms-MY -Dtests.timezone=America/Indiana/Marengo -Druntime.java=22
  | 2> java.io.EOFException
  | at __randomizedtesting.SeedInfo.seed([C34B003B0029E2E6:8FCBBA3B5EA17AF4]:0)
  | at org.apache.lucene.store.ByteBuffersDataInput.readByte(ByteBuffersDataInput.java:113)
  | at org.apache.lucene.store.DataInput.readInt(DataInput.java:97)
  | at org.apache.lucene.store.ByteBuffersDataInput.readInt(ByteBuffersDataInput.java:200)
  | at org.apache.lucene.store.DataInput.readLong(DataInput.java:184)
  | at org.apache.lucene.store.ByteBuffersDataInput.readLong(ByteBuffersDataInput.java:212)
  | at org.apache.lucene.store.ByteBuffersIndexInput.readLong(ByteBuffersIndexInput.java:127)
  | at org.apache.lucene.tests.store.MockIndexInputWrapper.readLong(MockIndexInputWrapper.java:178)
  | at org.apache.lucene.codecs.lucene90.IndexedDISI$Method$2.advanceWithinBlock(IndexedDISI.java:623)
  | at org.apache.lucene.codecs.lucene90.IndexedDISI.advance(IndexedDISI.java:446)
  | at org.apache.lucene.codecs.lucene90.Lucene90DocValuesProducer$21.advance(Lucene90DocValuesProducer.java:919)
  | at org.elasticsearch.index.codec.tsdb.DocValuesCodecDuelTests.assertSortedDocValues(DocValuesCodecDuelTests.java:142)
  | at org.elasticsearch.index.codec.tsdb.DocValuesCodecDuelTests.testDuel(DocValuesCodecDuelTests.java:113)
  | 2> NOTE: leaving temporary files on disk at: /dev/shm/bk/bk-agent-prod-gcp-1716406174795243165/elastic/elasticsearch-pull-request/server/build/testrun/test/temp/org.elasticsearch.index.codec.tsdb.DocValuesCodecDuelTests_C34B003B0029E2E6-001
  | 2> NOTE: test params are: codec=Asserting(Lucene99): {}, docValues:{}, maxPointsInLeafNode=1372, maxMBSortInHeap=6.381646376643742, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=ms-MY, timezone=America/Indiana/Marengo
  | 2> NOTE: Linux 5.15.0-1060-gcp amd64/Oracle Corporation 22.0.1 (64-bit)/cpus=32,threads=1,free=394770256,total=536870912
  | 2> NOTE: All tests run in this JVM: [ActionListenerTests, TransportGetDesiredBalanceActionTests, NodesHotThreadsRequestTests, NodesStatsRequestTests, ClusterUpdateSettingsResponseTests, SnapshotIndexStatusTests, GetScriptLanguageResponseTests, ReloadAnalyzersResponseTests, GetIndexActionTests, MetadataRolloverServiceAutoShardingTests, IndicesShardStoreResponseTests, TransportSimulateIndexTemplateActionTests, BulkRequestTests, ModifyDataStreamsRequestTests, FieldCapabilitiesResponseTests, IndexRequestTests, AbstractSearchAsyncActionTests, ParsedScrollIdTests, SearchShardsRequestTests, ListenerTimeoutsTests, TransportNodesActionTests, GetSynonymsSetsActionRequestSerializingTests, ElasticsearchUncaughtExceptionHandlerTests, ClusterStateTaskExecutorTests, CoordinationDiagnosticsServiceTests, MasterHistoryTests, ClusterIndexHealthTests, DataStreamLifecycleTests, IndexMetadataStatsSerializationTests, MetadataIndexAliasesServiceTests, DiscoveryNodeFiltersTests, RecoverySourceTests, BalancedSingleShardTests, MoveDecisionTests, ShardChangesObserverTests, ClusterInfoSimulatorTests, EnableAllocationTests, MasterServiceTests, StringsTests, IteratorsTests, LuceneGeometriesUtilsTests, BytesStreamsTests, PrefixLoggerTests, InputStreamIndexInputTests, RegexTests, DateUtilsRoundingTests, BinarySearcherTests, MapsTests, ListenableFutureTests, XContentFactoryTests, DiscoveryModuleTests, ClusterStateUpdatersTests, HealthPeriodicLoggerTests, HealthNodeTaskParamsXContentTests, IndexServiceTests, HunspellTokenFilterFactoryTests, DocValuesCodecDuelTests]
```

**Comment by martijnvg** [comment]
This is a test failure and is caused by incorrect usage of the `DocIdSetIterator#advance(...)` method.

**Comment by dnhatn** [comment]
Thanks Luca. I opened #110056.
