### ISSUE TITLE
[CI] DlsFlsRequestCacheTests testRequestCacheWithTemplateRoleQuery failing

### ISSUE THREAD

**Issue by nielsbauman** [elastic/elasticsearch#109011]
**Build scan:**
https://gradle-enterprise.elastic.co/s/mjh3a4jsoi76k/tests/:x-pack:plugin:security:internalClusterTest/org.elasticsearch.integration.DlsFlsRequestCacheTests/testRequestCacheWithTemplateRoleQuery

**Reproduction line:**
```
./gradlew ':x-pack:plugin:security:internalClusterTest' --tests "org.elasticsearch.integration.DlsFlsRequestCacheTests.testRequestCacheWithTemplateRoleQuery" -Dtests.seed=313F2D116C7DED2B -Dtests.locale=nl-NL -Dtests.timezone=Antarctica/South_Pole -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.integration.DlsFlsRequestCacheTests#testRequestCacheWithTemplateRoleQuery`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testRequestCacheWithTemplateRoleQuery'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.integration.DlsFlsRequestCacheTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.elasticsearch.ResourceAlreadyExistsException: index [dls-index/uAmo67hcRQyX4BQ_vA3HNg] already exists

  at __randomizedtesting.SeedInfo.seed([313F2D116C7DED2B:8CC6CF60D40A632B]:0)
  at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validateIndexName(MetadataCreateIndexService.java:177)
  at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validate(MetadataCreateIndexService.java:1371)
  at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:345)
  at org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:300)
  at org.elasticsearch.cluster.service.MasterService$UnbatchedExecutor.execute(MasterService.java:551)
  at org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1050)
  at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1015)
  at org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:233)
  at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1656)
  at org.elasticsearch.action.ActionListener.run(ActionListener.java:433)
  at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.run(MasterService.java:1653)
  at org.elasticsearch.cluster.service.MasterService$5.lambda$doRun$0(MasterService.java:1248)
  at org.elasticsearch.action.ActionListener.run(ActionListener.java:433)
  at org.elasticsearch.cluster.service.MasterService$5.doRun(MasterService.java:1227)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1570)

```

**Comment by nielsbauman** [comment]
Some more occurrences:
https://gradle-enterprise.elastic.co/s/omk4kvhba4txc
https://gradle-enterprise.elastic.co/s/24hedutnxpbpg

**Comment by jfreden** [comment]
Fixed in: https://github.com/elastic/elasticsearch/pull/109024
