### ISSUE TITLE
Unable to use QueryBuilders in a Spring Boot executable JAR

### ISSUE THREAD

**Issue by os-cas** [elastic/elasticsearch#109165]
### Elasticsearch Version

8.13.2

### Java Version

_bundled_

### OS Version

Windows 10

### Problem Description

In a Spring Boot project I have a dependency to `org.elasticsearch:elasticsearch:8.13.2` which transitively brings in elasticsearch-x-content.
The standard way to package a Spring Boot application is to build an executable fat/uber JAR using the spring-boot-maven-plugin.

The problem arises through calls of .toString() on any AbstractQueryBuilder implementation which results in:
`NoSuchFileException: /IMPL-JARS/x-content/jackson-core-2.15.0.jar`

The reason is that the classes listed in the stacktrace are hard-coded to expect their external dependencies in the IMPL-JARS folder of their containing JAR.
But with my repackaged JAR by Spring the actual path would be:
`myapp.jar!/BOOT-INF/lib/elasticsearch-x-content-8.13.2.jar!/IMPL-JARS/jackson-core-2.15.0.jar`
instead of
`elasticsearch-x-content-8.13.2.jar/IMPL-JARS/jackson-core-2.15.0.jar`

Am I doing something wrong? Is there no way to use this in a regular Spring Boot application anymore? In ElasticSearch 7.x this was no problem.

### Steps to Reproduce

- set up a Spring Boot project
- add a dependency to org.elasticsearch:elasticsearch-x-content:8.13.2
- in the entry point of your application call e.g. `new BoolQueryBuilder().toString();`
- build and start an executable JAR using the spring-boot-maven-plugin

### Logs (if relevant)

java.nio.file.NoSuchFileException: /IMPL-JARS/x-content/jackson-core-2.15.0.jar
        at org.elasticsearch.core.internal.provider.EmbeddedImplClassLoader.scanPackages(EmbeddedImplClassLoader.java:422)
        at org.elasticsearch.core.internal.provider.EmbeddedImplClassLoader.getProviderPrefixes(EmbeddedImplClassLoader.java:454)
        at org.elasticsearch.core.internal.provider.EmbeddedImplClassLoader.lambda$getInstance$0(EmbeddedImplClassLoader.java:98)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
        at org.elasticsearch.core.internal.provider.EmbeddedImplClassLoader.getInstance(EmbeddedImplClassLoader.java:99)
        at org.elasticsearch.core.internal.provider.ProviderLocator.load(ProviderLocator.java:107)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
        at org.elasticsearch.core.internal.provider.ProviderLocator.get(ProviderLocator.java:100)
        at org.elasticsearch.xcontent.spi.XContentProvider$Holder.<clinit>(XContentProvider.java:95)
        ... 25 common frames omitted

**Comment by mark-vieira** [comment]
It looks like you can instruct spring boot _not_ to package certain dependencies in the uberjar.

https://docs.spring.io/spring-boot/gradle-plugin/packaging.html#packaging-executable.configuring.unpacking

**Comment by os-cas** [comment]
@mark-vieira Thank you, that's a great hint!

I found a corresponding `requiresUnpack` configuration param for their maven-plugin as well. It will unpack the specified dependency into the tmp folder at runtime which solves the mentioned issue around the elasticsearch-x-content.jar.

For me it was fixed with a configuration as in this snippet:
```
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <executions>
        <execution>
            <configuration>
                <requiresUnpack>
                    <dependency>
                        <groupId>org.elasticsearch</groupId>
                        <artifactId>elasticsearch-x-content</artifactId>
                    </dependency>
                </requiresUnpack>
```
