### ISSUE TITLE
MV_APPEND tests failing on geo_shape

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#109373]
### CI Link

local

### Repro line

./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.expression.function.scalar.multivalue.MvAppendTests.testEvaluateBlockWithoutNulls {TestCase=<geo_shape>, <geo_shape>}" -Dtests.seed=D9F77BE783139D12 -Dtests.locale=es-SV -Dtests.timezone=Europe/Riga -Druntime.java=22

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

```
  1> [2024-06-05T01:09:31,200][INFO ][o.e.x.e.e.f.s.m.MvAppendTests] [testEvaluateBlockWithoutNulls] [TestCase=<geo_shape>, <geo_shape>] after test
  2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.expression.function.scalar.multivalue.MvAppendTests.testEvaluateBlockWithoutNulls {TestCase=<geo_shape>, <geo_shape>}" -Dtests.seed=D9F77BE783139D12 -Dtests.locale=es-SV -Dtests.timezone=Europe/Riga -Druntime.java=22
  2> java.lang.AssertionError: Test data is too large to fit in the memory
        at __randomizedtesting.SeedInfo.seed([D9F77BE783139D12:93E9D00A2A5B0AA6]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertFalse(Assert.java:65)
        at org.elasticsearch.xpack.esql.expression.function.AbstractFunctionTestCase.testEvaluateBlockWithoutNulls(AbstractFunctionTestCase.java:313)
        at java.base/jdk.internal.reflect.DirectMethodHandl
```

I think we need to limit the size of the shape a bit.

**Comment by benwtrent** [comment]
Here is another failure:

https://gradle-enterprise.elastic.co/s/4yfw7myjrplly

```
./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.expression.function.scalar.multivalue.MvAppendTests.testEvaluateBlockWithoutNulls {TestCase=<cartesian_shape>, <cartesian_shape>}" -Dtests.seed=9E8676FD1A5A77FB -Dtests.locale=fr-BE -Dtests.timezone=America/Creston -Druntime.java=22
```
