### ISSUE TITLE
Problems using debian package with new debian jessie

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#10938]
Hi

no deep dive yet, just figured out that there is a problem with the repository when running with the freshly released debian jessie, which now uses systemd

```
root@debian-800-jessie:~# systemctl status elasticsearch
● elasticsearch.service - Starts and stops a single elasticsearch instance on this system
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled)
   Active: failed (Result: exit-code) since Sun 2015-05-03 13:17:43 GMT; 35min ago
     Docs: http://www.elasticsearch.org
  Process: 389 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -Des.default.config=$CONF_FILE -Des.default.path.home=$ES_HOME -Des.default.path.logs=$LOG_DIR -Des.default.path.data=$DATA_DIR -Des.default.path.work=$WORK_DIR -Des.default.path.conf=$CONF_DIR (code=exited, status=3)
 Main PID: 389 (code=exited, status=3)

May 03 13:17:43 debian-800-jessie elasticsearch[389]: at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:383)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at java.nio.file.Files.createDirectory(Files.java:630)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at java.nio.file.Files.createAndCheckIsDirectory(Files.java:734)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at java.nio.file.Files.createDirectories(Files.java:720)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:105)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:160)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: ... 4 more
May 03 13:17:43 debian-800-jessie systemd[1]: elasticsearch.service: main process exited, code=exited, status=3/NOTIMPLEMENTED
May 03 13:17:43 debian-800-jessie systemd[1]: Unit elasticsearch.service entered failed state.
```

this is from a `journalctl` output and shows a wrong data path

```
May 03 13:17:42 debian-800-jessie elasticsearch[389]: Failed to configure logging...
May 03 13:17:42 debian-800-jessie elasticsearch[389]: org.elasticsearch.ElasticsearchException: Failed to load logging configuration
May 03 13:17:42 debian-800-jessie elasticsearch[389]: at org.elasticsearch.common.logging.log4j.LogConfigurator.resolveConfig(LogConfigurator.java:139)
May 03 13:17:42 debian-800-jessie elasticsearch[389]: at org.elasticsearch.common.logging.log4j.LogConfigurator.configure(LogConfigurator.java:89)
May 03 13:17:42 debian-800-jessie elasticsearch[389]: at org.elasticsearch.bootstrap.Bootstrap.setupLogging(Bootstrap.java:100)
May 03 13:17:42 debian-800-jessie elasticsearch[389]: at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:184)
May 03 13:17:42 debian-800-jessie elasticsearch[389]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
May 03 13:17:42 debian-800-jessie elasticsearch[389]: Caused by: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/config
May 03 13:17:42 debian-800-jessie elasticsearch[389]: at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
May 03 13:17:42 debian-800-jessie elasticsearch[389]: at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
May 03 13:17:42 debian-800-jessie elasticsearch[389]: at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
May 03 13:17:42 debian-800-jessie elasticsearch[389]: at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
May 03 13:17:42 debian-800-jessie elasticsearch[389]: at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
May 03 13:17:42 debian-800-jessie elasticsearch[389]: at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:97)
May 03 13:17:42 debian-800-jessie elasticsearch[389]: at java.nio.file.Files.readAttributes(Files.java:1686)
May 03 13:17:42 debian-800-jessie elasticsearch[389]: at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:109)
May 03 13:17:42 debian-800-jessie elasticsearch[389]: at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69)
May 03 13:17:42 debian-800-jessie elasticsearch[389]: at java.nio.file.Files.walkFileTree(Files.java:2602)
May 03 13:17:42 debian-800-jessie elasticsearch[389]: at org.elasticsearch.common.logging.log4j.LogConfigurator.resolveConfig(LogConfigurator.java:123)
May 03 13:17:42 debian-800-jessie elasticsearch[389]: ... 4 more
May 03 13:17:43 debian-800-jessie elasticsearch[389]: log4j:WARN No appenders could be found for logger (node).
May 03 13:17:43 debian-800-jessie elasticsearch[389]: log4j:WARN Please initialize the log4j system properly.
May 03 13:17:43 debian-800-jessie elasticsearch[389]: log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
May 03 13:17:43 debian-800-jessie elasticsearch[389]: {1.5.2}: Initialization Failed ...
May 03 13:17:43 debian-800-jessie elasticsearch[389]: - ElasticsearchIllegalStateException[Failed to created node environment]
May 03 13:17:43 debian-800-jessie elasticsearch[389]: AccessDeniedException[/usr/share/elasticsearch/data]
May 03 13:17:43 debian-800-jessie elasticsearch[389]: org.elasticsearch.ElasticsearchIllegalStateException: Failed to created node environment
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:162)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:70)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:213)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:383)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at java.nio.file.Files.createDirectory(Files.java:630)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at java.nio.file.Files.createAndCheckIsDirectory(Files.java:734)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at java.nio.file.Files.createDirectories(Files.java:720)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:105)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:160)
May 03 13:17:43 debian-800-jessie elasticsearch[389]: ... 4 more
```

**Comment by tlrx** [comment]
@spinscale there are few issues with SytemD, can you please check if you can reproduce it with #10725 ? Thanks

**Comment by spinscale** [comment]
yes, elasticsearch starts with that PR on jessie, let's close this one with the PR as well

**Comment by spinscale** [comment]
Closing this one due to #10725 being closed
