### ISSUE TITLE
[CI] EsqlClientYamlIT test {p0=esql/150_lookup/multivalued keys} failing

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#109477]
**Build scan:**
https://gradle-enterprise.elastic.co/s/bm6cwqxsiyqac/tests/:x-pack:plugin:esql:qa:server:multi-node:yamlRestTest/org.elasticsearch.xpack.esql.qa.multi_node.EsqlClientYamlIT/test%20%7Bp0=esql%2F150_lookup%2Fmultivalued%20keys%7D

**Reproduction line:**
```
./gradlew ':x-pack:plugin:esql:qa:server:multi-node:yamlRestTest' --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlClientYamlIT.test {p0=esql/150_lookup/multivalued keys}" -Dtests.seed=13124E01B43AFA13 -Dtests.locale=es-UY -Dtests.timezone=Asia/Ust-Nera -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.esql.qa.multi_node.EsqlClientYamlIT#test {p0=esql/150_lookup/multivalued keys}`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test%20%7Bp0%3Desql/150_lookup/multivalued%20keys%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.qa.multi_node.EsqlClientYamlIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.RuntimeException: Failure at [esql/150_lookup:194]: 60.000 milliseconds timeout on connection http-outgoing-2 [ACTIVE]

  at __randomizedtesting.SeedInfo.seed([13124E01B43AFA13:9B4671DB1AC697EB]:0)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:612)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:553)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:47)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1570)

  Caused by: java.net.SocketTimeoutException: 60.000 milliseconds timeout on connection http-outgoing-2 [ACTIVE]

    at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:919)
    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:304)
    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:292)
    at org.elasticsearch.test.rest.yaml.ClientYamlTestClient.callApi(ClientYamlTestClient.java:194)
    at org.elasticsearch.test.rest.yaml.ClientYamlTestExecutionContext.callApiInternal(ClientYamlTestExecutionContext.java:237)
    at org.elasticsearch.test.rest.yaml.ClientYamlTestExecutionContext.callApi(ClientYamlTestExecutionContext.java:157)
    at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:361)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:590)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:553)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:47)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1570)

    Caused by: java.net.SocketTimeoutException: 60.000 milliseconds timeout on connection http-outgoing-2 [ACTIVE]

      at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387)
      at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:98)
      at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:40)
      at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
      at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:261)
      at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:502)
      at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:211)
      at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
      at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
      at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
      at java.lang.Thread.run(Thread.java:1570)

```

**Comment by nik9000** [comment]
Doesn't reproduce. Checking the saved build bits.

**Comment by nik9000** [comment]
The logs don't show me anything interesting. Here's where the failure happened:
```
[2024-06-07T23:44:36,311][INFO ][o.e.c.r.a.AllocationService] [test-cluster-1] current.health="GREEN" message="Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][4]]])." previous.health="YELLOW" reason="shards started [[test][4]]"
[2024-06-07T23:45:36,244] ...failure happens here...
[2024-06-07T23:45:36,308][INFO ][o.e.x.m.MachineLearning  ] [test-cluster-1] Starting machine learning feature reset
```

```
[2024-06-07T23:44:34,148][INFO ][o.e.x.e.EnrichPolicyRunner] [test-cluster-0] Policy [networks-policy]: Policy execution complete
[2024-06-07T23:45:36,244] ...failure happens here...
[2024-06-07T23:45:38,113][INFO ][o.e.n.Node               ] [test-cluster-0] stopping ...
```

This isn't even the last of the tests. Three more run after this and pass.

**Comment by nik9000** [comment]
The failure is just a timeout, so I checked for GC pauses and don't see a long one:
```
[2024-06-07T13:44:37.224+0000][799157][info ][safepoint   ] Safepoint "Cleanup", Time since last: 1361576542 ns, Reaching safepoint: 68883 ns, Cleanup: 22265 ns, At safepoint: 16977 ns, Total: 108125 ns
[2024-06-07T13:44:43.309+0000][799157][info ][safepoint   ] Safepoint "Cleanup", Time since last: 6084797009 ns, Reaching safepoint: 71024 ns, Cleanup: 15188 ns, At safepoint: 15885 ns, Total: 102097 ns
[2024-06-07T13:45:06.311+0000][799157][info ][safepoint   ] Safepoint "Cleanup", Time since last: 23002298383 ns, Reaching safepoint: 96985 ns, Cleanup: 19006 ns, At safepoint: 22753 ns, Total: 138744 ns
[2024-06-07T13:45:36.315+0000][799157][info ][safepoint   ] Safepoint "Cleanup", Time since last: 30003396248 ns, Reaching safepoint: 114032 ns, Cleanup: 56463 ns, At safepoint: 23203 ns, Total: 193698 ns
```

and
```
[2024-06-07T13:44:36.165+0000][799165][info ][safepoint   ] Safepoint "Cleanup", Time since last: 1035249252 ns, Reaching safepoint: 28409 ns, Cleanup: 21751 ns, At safepoint: 16339 ns, Total: 66499 ns
[2024-06-07T13:44:36.190+0000][799165][info ][gc,start    ] GC(114) Pause Young (Normal) (G1 Evacuation Pause)
[2024-06-07T13:44:36.190+0000][799165][info ][gc,task     ] GC(114) Using 12 workers of 23 for evacuation
[2024-06-07T13:44:36.190+0000][799165][debug][gc,age      ] GC(114) Desired survivor size 20971520 bytes, new threshold 15 (max threshold 15)
[2024-06-07T13:44:36.193+0000][799165][info ][gc,phases   ] GC(114)   Pre Evacuate Collection Set: 0.28ms
[2024-06-07T13:44:36.193+0000][799165][info ][gc,phases   ] GC(114)   Merge Heap Roots: 0.12ms
[2024-06-07T13:44:36.193+0000][799165][info ][gc,phases   ] GC(114)   Evacuate Collection Set: 1.97ms
[2024-06-07T13:44:36.193+0000][799165][info ][gc,phases   ] GC(114)   Post Evacuate Collection Set: 0.68ms
[2024-06-07T13:44:36.193+0000][799165][info ][gc,phases   ] GC(114)   Other: 0.16ms
[2024-06-07T13:44:36.193+0000][799165][trace][gc,age      ] GC(114) Age table with threshold 15 (max threshold 15)
[2024-06-07T13:44:36.193+0000][799165][trace][gc,age      ] GC(114) - age   1:     398624 bytes,     398624 total
[2024-06-07T13:44:36.193+0000][799165][trace][gc,age      ] GC(114) - age   2:     103456 bytes,     502080 total
[2024-06-07T13:44:36.193+0000][799165][trace][gc,age      ] GC(114) - age   3:      13264 bytes,     515344 total
[2024-06-07T13:44:36.193+0000][799165][trace][gc,age      ] GC(114) - age   4:       6552 bytes,     521896 total
[2024-06-07T13:44:36.193+0000][799165][trace][gc,age      ] GC(114) - age   5:     162336 bytes,     684232 total
[2024-06-07T13:44:36.193+0000][799165][trace][gc,age      ] GC(114) - age   6:      12648 bytes,     696880 total
[2024-06-07T13:44:36.193+0000][799165][trace][gc,age      ] GC(114) - age   7:      79416 bytes,     776296 total
[2024-06-07T13:44:36.193+0000][799165][trace][gc,age      ] GC(114) - age   8:     527336 bytes,    1303632 total
[2024-06-07T13:44:36.193+0000][799165][trace][gc,age      ] GC(114) - age   9:      25512 bytes,    1329144 total
[2024-06-07T13:44:36.193+0000][799165][trace][gc,age      ] GC(114) - age  10:      88216 bytes,    1417360 total
[2024-06-07T13:44:36.193+0000][799165][trace][gc,age      ] GC(114) - age  11:       9448 bytes,    1426808 total
[2024-06-07T13:44:36.193+0000][799165][trace][gc,age      ] GC(114) - age  12:       2680 bytes,    1429488 total
[2024-06-07T13:44:36.193+0000][799165][trace][gc,age      ] GC(114) - age  13:      17592 bytes,    1447080 total
[2024-06-07T13:44:36.193+0000][799165][trace][gc,age      ] GC(114) - age  14:       4528 bytes,    1451608 total
[2024-06-07T13:44:36.193+0000][799165][trace][gc,age      ] GC(114) - age  15:       3664 bytes,    1455272 total
[2024-06-07T13:44:36.193+0000][799165][info ][gc,heap     ] GC(114) Eden regions: 75->0(75)
[2024-06-07T13:44:36.193+0000][799165][info ][gc,heap     ] GC(114) Survivor regions: 1->1(10)
[2024-06-07T13:44:36.193+0000][799165][info ][gc,heap     ] GC(114) Old regions: 26->26
[2024-06-07T13:44:36.193+0000][799165][info ][gc,heap     ] GC(114) Humongous regions: 0->0
[2024-06-07T13:44:36.193+0000][799165][info ][gc,metaspace] GC(114) Metaspace: 165034K(169280K)->165034K(169280K) NonClass: 142440K(144768K)->142440K(144768K) Class: 22594K(24512K)->22594K(24512K)
[2024-06-07T13:44:36.193+0000][799165][info ][gc          ] GC(114) Pause Young (Normal) (G1 Evacuation Pause) 402M->102M(512M) 3.481ms
[2024-06-07T13:44:36.194+0000][799165][info ][gc,cpu      ] GC(114) User=0.02s Sys=0.00s Real=0.01s
[2024-06-07T13:44:36.194+0000][799165][info ][safepoint   ] Safepoint "G1CollectForAllocation", Time since last: 25269916 ns, Reaching safepoint: 80636 ns, Cleanup: 4306 ns, At safepoint: 3783648 ns, Total: 3868590 ns
[2024-06-07T13:44:40.337+0000][799165][info ][safepoint   ] Safepoint "Cleanup", Time since last: 4143710283 ns, Reaching safepoint: 70969 ns, Cleanup: 12494 ns, At safepoint: 15723 ns, Total: 99186 ns
[2024-06-07T13:44:50.339+0000][799165][info ][safepoint   ] Safepoint "Cleanup", Time since last: 10001529701 ns, Reaching safepoint: 128063 ns, Cleanup: 14258 ns, At safepoint: 23328 ns, Total: 165649 ns
[2024-06-07T13:45:06.341+0000][799165][info ][safepoint   ] Safepoint "Cleanup", Time since last: 16001740619 ns, Reaching safepoint: 107554 ns, Cleanup: 16758 ns, At safepoint: 16185 ns, Total: 140497 ns
[2024-06-07T13:45:28.344+0000][799165][info ][safepoint   ] Safepoint "Cleanup", Time since last: 22002390915 ns, Reaching safepoint: 113024 ns, Cleanup: 12752 ns, At safepoint: 15838 ns, Total: 141614 ns
[2024-06-07T13:45:36.457+0000][799165][info ][safepoint   ] Safepoint "Cleanup", Time since last: 8113326463 ns, Reaching safepoint: 42546 ns, Cleanup: 34079 ns, At safepoint: 38836 ns, Total: 115461 ns
[2024-06-07T13:45:37.518+0000][799165][info ][gc,start    ] GC(115) Pause Young (Normal) (G1 Evacuation Pause)
[2024-06-07T13:45:37.518+0000][799165][info ][gc,task     ] GC(115) Using 12 workers of 23 for evacuation
[2024-06-07T13:45:37.518+0000][799165][debug][gc,age      ] GC(115) Desired survivor size 20971520 bytes, new threshold 15 (max threshold 15)
[2024-06-07T13:45:37.522+0000][799165][info ][gc,phases   ] GC(115)   Pre Evacuate Collection Set: 0.34ms
[2024-06-07T13:45:37.522+0000][799165][info ][gc,phases   ] GC(115)   Merge Heap Roots: 0.14ms
[2024-06-07T13:45:37.522+0000][799165][info ][gc,phases   ] GC(115)   Evacuate Collection Set: 2.07ms
[2024-06-07T13:45:37.522+0000][799165][info ][gc,phases   ] GC(115)   Post Evacuate Collection Set: 0.90ms
[2024-06-07T13:45:37.522+0000][799165][info ][gc,phases   ] GC(115)   Other: 0.15ms
[2024-06-07T13:45:37.522+0000][799165][trace][gc,age      ] GC(115) Age table with threshold 15 (max threshold 15)
[2024-06-07T13:45:37.522+0000][799165][trace][gc,age      ] GC(115) - age   1:     255600 bytes,     255600 total
[2024-06-07T13:45:37.522+0000][799165][trace][gc,age      ] GC(115) - age   2:      16160 bytes,     271760 total
[2024-06-07T13:45:37.522+0000][799165][trace][gc,age      ] GC(115) - age   3:      11208 bytes,     282968 total
[2024-06-07T13:45:37.522+0000][799165][trace][gc,age      ] GC(115) - age   4:      11824 bytes,     294792 total
[2024-06-07T13:45:37.522+0000][799165][trace][gc,age      ] GC(115) - age   5:       5440 bytes,     300232 total
[2024-06-07T13:45:37.522+0000][799165][trace][gc,age      ] GC(115) - age   6:     161680 bytes,     461912 total
[2024-06-07T13:45:37.522+0000][799165][trace][gc,age      ] GC(115) - age   7:      12520 bytes,     474432 total
[2024-06-07T13:45:37.522+0000][799165][trace][gc,age      ] GC(115) - age   8:      79416 bytes,     553848 total
[2024-06-07T13:45:37.522+0000][799165][trace][gc,age      ] GC(115) - age   9:     527264 bytes,    1081112 total
[2024-06-07T13:45:37.522+0000][799165][trace][gc,age      ] GC(115) - age  10:      25320 bytes,    1106432 total
[2024-06-07T13:45:37.522+0000][799165][trace][gc,age      ] GC(115) - age  11:      88216 bytes,    1194648 total
[2024-06-07T13:45:37.522+0000][799165][trace][gc,age      ] GC(115) - age  12:       9448 bytes,    1204096 total
[2024-06-07T13:45:37.522+0000][799165][trace][gc,age      ] GC(115) - age  13:       2680 bytes,    1206776 total
[2024-06-07T13:45:37.522+0000][799165][trace][gc,age      ] GC(115) - age  14:      17592 bytes,    1224368 total
[2024-06-07T13:45:37.522+0000][799165][trace][gc,age      ] GC(115) - age  15:       4344 bytes,    1228712 total
[2024-06-07T13:45:37.522+0000][799165][info ][gc,heap     ] GC(115) Eden regions: 75->0(75)
[2024-06-07T13:45:37.522+0000][799165][info ][gc,heap     ] GC(115) Survivor regions: 1->1(10)
[2024-06-07T13:45:37.522+0000][799165][info ][gc,heap     ] GC(115) Old regions: 26->26
[2024-06-07T13:45:37.522+0000][799165][info ][gc,heap     ] GC(115) Humongous regions: 0->0
[2024-06-07T13:45:37.522+0000][799165][info ][gc,metaspace] GC(115) Metaspace: 165131K(169344K)->165131K(169344K) NonClass: 142528K(144832K)->142528K(144832K) Class: 22603K(24512K)->22603K(24512K)
[2024-06-07T13:45:37.522+0000][799165][info ][gc          ] GC(115) Pause Young (Normal) (G1 Evacuation Pause) 402M->101M(512M) 3.900ms
[2024-06-07T13:45:37.522+0000][799165][info ][gc,cpu      ] GC(115) User=0.02s Sys=0.00s Real=0.00s
[2024-06-07T13:45:37.522+0000][799165][info ][safepoint   ] Safepoint "G1CollectForAllocation", Time since last: 1060950034 ns, Reaching safepoint: 85313 ns, Cleanup: 62213 ns, At safepoint: 4173388 ns, Total: 4320914 ns
[2024-06-07T13:45:39.004+0000][799165][info ][safepoint   ] Safepoint "Cleanup", Time since last: 1481809813 ns, Reaching safepoint: 8752 ns, Cleanup: 83151 ns, At safepoint: 7741 ns, Total: 99644 ns
[2024-06-07T13:45:40.155+0000][799165][info ][gc,heap,exit] Heap
[2024-06-07T13:45:40.155+0000][799165][info ][gc,heap,exit]  garbage-first heap   total reserved 524288K, committed 524288K, used 280285K [0x00000000e0000000, 0x0000000100000000)
[2024-06-07T13:45:40.155+0000][799165][info ][gc,heap,exit]   region size 4096K, 44 young (180224K), 1 survivors (4096K)
[2024-06-07T13:45:40.155+0000][799165][info ][gc,heap,exit]  Metaspace       used 165454K, committed 169664K, reserved 1245184K
[2024-06-07T13:45:40.155+0000][799165][info ][gc,heap,exit]   class space    used 22669K, committed 24576K, reserved 1048576K
```

**Comment by nik9000** [comment]
Since this has only failed once I'm going to reenable it and see if we can get another failure with more fun information.
