### ISSUE TITLE
[CI] TimeSeriesSortedSourceOperatorTests testMatchNone failing

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#109568]
**Build scan:**
https://gradle-enterprise.elastic.co/s/fvh4qgufosmaw/tests/:x-pack:plugin:esql:compute:test/org.elasticsearch.compute.lucene.TimeSeriesSortedSourceOperatorTests/testMatchNone

**Reproduction line:**
```
./gradlew ':x-pack:plugin:esql:compute:test' --tests "org.elasticsearch.compute.lucene.TimeSeriesSortedSourceOperatorTests.testMatchNone" -Dtests.seed=B30D7DDC97AC45E2 -Dtests.locale=fr-CA -Dtests.timezone=Asia/Phnom_Penh -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
[Failure dashboard for `org.elasticsearch.compute.lucene.TimeSeriesSortedSourceOperatorTests#testMatchNone`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testMatchNone'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.compute.lucene.TimeSeriesSortedSourceOperatorTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.NullPointerException: Cannot read field "timeSeriesHash" because the return value of "org.apache.lucene.util.PriorityQueue.top()" is null

  at __randomizedtesting.SeedInfo.seed([B30D7DDC97AC45E2:27A0C9D5F5EB8EB5]:0)
  at org.elasticsearch.compute.lucene.TimeSeriesSortedSourceOperatorFactory$Impl$TimeSeriesIterator.consume(TimeSeriesSortedSourceOperatorFactory.java:278)
  at org.elasticsearch.compute.lucene.TimeSeriesSortedSourceOperatorFactory$Impl.getOutput(TimeSeriesSortedSourceOperatorFactory.java:189)
  at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:247)
  at org.elasticsearch.compute.operator.Driver.run(Driver.java:178)
  at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:364)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1570)

```

**Comment by dnhatn** [comment]
Fixed in #109580
