### ISSUE TITLE
KerberosTicketValidatorTests fails when locale database is set to CLDR

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#109621]
This is in the context of #109465. The COMPAT locale database has been removed in JDK 23, and so we need to change to the CLDR dataset. However, doing so breaks `KerberosTicketValidatorTests` in a very strange way:

```
java.security.PrivilegedActionException: javax.security.auth.login.LoginException: Parse Generalized time, invalid format
    at __randomizedtesting.SeedInfo.seed([FD4F44A45D0B391C:73F8EF4888446031]:0)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:575)
    at org.elasticsearch.xpack.security.authc.kerberos.SpnegoClient.<init>(SpnegoClient.java:84)
    at org.elasticsearch.xpack.security.authc.kerberos.KerberosTicketValidatorTests.testValidKebrerosTicket(KerberosTicketValidatorTests.java:126)

    Caused by:
    javax.security.auth.login.LoginException: Parse Generalized time, invalid format
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:789)
        at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:597)
        at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:754)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:678)
        at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:676)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
        at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:676)
        at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at org.elasticsearch.xpack.security.authc.kerberos.SpnegoClient.loginUsingPassword(SpnegoClient.java:193)
        at org.elasticsearch.xpack.security.authc.kerberos.SpnegoClient.lambda$new$0(SpnegoClient.java:85)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
        ... 2 more

        Caused by:
        java.io.IOException: Parse Generalized time, invalid format
            at java.base/sun.security.util.DerValue.toDigit(DerValue.java:1058)
            at java.base/sun.security.util.DerValue.getTimeInternal(DerValue.java:903)
            at java.base/sun.security.util.DerValue.getGeneralizedTime(DerValue.java:1101)
            at java.security.jgss/sun.security.krb5.internal.KerberosTime.parse(KerberosTime.java:286)
            at java.security.jgss/sun.security.krb5.internal.KRBError.init(KRBError.java:350)
            at java.security.jgss/sun.security.krb5.internal.KRBError.<init>(KRBError.java:193)
            at java.security.jgss/sun.security.krb5.KrbAsRep.<init>(KrbAsRep.java:63)
            at java.security.jgss/sun.security.krb5.KrbAsReqBuilder.send(KrbAsReqBuilder.java:345)
            at java.security.jgss/sun.security.krb5.KrbAsReqBuilder.action(KrbAsReqBuilder.java:498)
            at jdk.security.auth/com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:751)
            ... 12 more
```

REPRODUCTION STEPS:

1. Change [this line](https://github.com/elastic/elasticsearch/blob/main/build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/ElasticsearchTestBasePlugin.java#L89) from `SPI,COMPAT` to `SPI,CLDR`
2. Run the following reproduction
```
./gradlew ':x-pack:qa:evil-tests:test' --tests "org.elasticsearch.xpack.security.authc.kerberos.KerberosTicketValidatorTests.testValidKebrerosTicket" -Dtests.seed=FD4F44A45D0B391C
```

It seems like its using locale information when generating a token, but that shouldn't be happening.

Note that several other tests will be broken by changing COMPAT to CLDR; these are fixed by #109465. This specific test failure is standalone.

**Comment by n1v0lg** [comment]
Sorry still digging through this (this is old code I'm entirely unfamiliar with) -- I will hopefully get somewhere concrete tomorrow. For now though, one observation:

Locale _is_ used under the hood by the lib we depend on (for the tests only, I _think_). We call this out [here](https://github.com/elastic/elasticsearch/blob/main/x-pack/qa/evil-tests/src/test/java/org/elasticsearch/xpack/security/authc/kerberos/KerberosTestCase.java#L59-L62) which mentions `org.apache.kerby.asn1.type.Asn1GeneralizedTime#toBytes` which does makes a call to `SimpleDateFormat dateF = new SimpleDateFormat("yyyyMMddHHmmss'Z'");` and that makes a call to `Locale.getDefault()` under the hood. I'm assuming that's what is causing the failure here.

**Comment by thecoop** [comment]
This breaks because there are lots of new locales added in CLDR which use non-latin scripts - previously the date format was fallback back to ROOT, which uses locale, but now the format ends up with non-latin numerals in the string, which breaks the test.

The list of new locales added can be found [here](https://gist.github.com/thecoop/3fd683a0e85ba299241cc1b4ede59111)
