### ISSUE TITLE
Log Storm on Bad Query

### ISSUE THREAD

**Issue by rabx88** [elastic/elasticsearch#10967]
I am seeing massive log spam on my servers with 1.5.2. The errors below are resulting in up to 10 GB log files for a given day. It seems like a pretty vicious logging loop. I will certainly delete this query as a temporary workaround but a single "bad" search should not allow this kind of storm to happen.

[2015-05-04 14:53:00,768][DEBUG][action.search.type       ] [White Fang] [probes][0], node[aZkN-qLtSHyUpn08VqAN6A], [R], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@a5cc7e7] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [Ecstasy][inet[/192.168.102.135:9300]][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.search.SearchParseException: [probes][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"filter":{"bool":{"must":[{"range":{"@timestamp":{"gt":"now-61s"}}},{"term":{"_type":"custom_win32_perfformatteddata_perfos_memory"}},{"script":{"lang":"expression","script":"doc['custom_win32_perfformatteddata_perfos_memory.AvailableMBytes'].value * 1000000.0 / doc['custom_win32_perfformatteddata_perfos_memory.TotalPhysicalMemory'].value < 0.1"}}]}},"size":10}]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:721)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:557)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:291)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:776)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:767)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:277)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.script.expression.ExpressionScriptCompilationException: Field [custom_win32_perfformatteddata_perfos_memory.AvailableMBytes] used in expression does not exist in mappings
	at org.elasticsearch.script.expression.ExpressionScriptEngineService.search(ExpressionScriptEngineService.java:129)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:432)
	at org.elasticsearch.index.query.ScriptFilterParser$ScriptFilter.<init>(ScriptFilterParser.java:135)
	at org.elasticsearch.index.query.ScriptFilterParser.parse(ScriptFilterParser.java:114)
	at org.elasticsearch.index.query.QueryParseContext.executeFilterParser(QueryParseContext.java:368)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerFilter(QueryParseContext.java:349)
	at org.elasticsearch.index.query.BoolFilterParser.parse(BoolFilterParser.java:92)
	at org.elasticsearch.index.query.QueryParseContext.executeFilterParser(QueryParseContext.java:368)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerFilter(QueryParseContext.java:349)
	at org.elasticsearch.index.query.IndexQueryParserService.parseInnerFilter(IndexQueryParserService.java:295)
	at org.elasticsearch.search.query.PostFilterParseElement.parse(PostFilterParseElement.java:33)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705)
	... 10 more
[2015-05-04 14:53:00,768][DEBUG][action.search.type       ] [White Fang] [issues-2015.05.01][1], node[aZkN-qLtSHyUpn08VqAN6A], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@a5cc7e7] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [Ecstasy][inet[/192.168.102.135:9300]][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.search.SearchParseException: [issues-2015.05.01][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"filter":{"bool":{"must":[{"range":{"@timestamp":{"gt":"now-61s"}}},{"term":{"_type":"custom_win32_perfformatteddata_perfos_memory"}},{"script":{"lang":"expression","script":"doc['custom_win32_perfformatteddata_perfos_memory.AvailableMBytes'].value * 1000000.0 / doc['custom_win32_perfformatteddata_perfos_memory.TotalPhysicalMemory'].value < 0.1"}}]}},"size":10}]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:721)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:557)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:291)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:776)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:767)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:277)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.script.expression.ExpressionScriptCompilationException: Field [custom_win32_perfformatteddata_perfos_memory.AvailableMBytes] used in expression does not exist in mappings
	at org.elasticsearch.script.expression.ExpressionScriptEngineService.search(ExpressionScriptEngineService.java:129)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:432)
	at org.elasticsearch.index.query.ScriptFilterParser$ScriptFilter.<init>(ScriptFilterParser.java:135)
	at org.elasticsearch.index.query.ScriptFilterParser.parse(ScriptFilterParser.java:114)
	at org.elasticsearch.index.query.QueryParseContext.executeFilterParser(QueryParseContext.java:368)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerFilter(QueryParseContext.java:349)
	at org.elasticsearch.index.query.BoolFilterParser.parse(BoolFilterParser.java:92)
	at org.elasticsearch.index.query.QueryParseContext.executeFilterParser(QueryParseContext.java:368)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerFilter(QueryParseContext.java:349)
	at org.elasticsearch.index.query.IndexQueryParserService.parseInnerFilter(IndexQueryParserService.java:295)
	at org.elasticsearch.search.query.PostFilterParseElement.parse(PostFilterParseElement.java:33)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705)
	... 10 more
[2015-05-04 14:53:00,768][DEBUG][action.search.type       ] [White Fang] [secrets][2], node[aZkN-qLtSHyUpn08VqAN6A], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@a5cc7e7] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [Ecstasy][inet[/192.168.102.135:9300]][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.search.SearchParseException: [secrets][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"filter":{"bool":{"must":[{"range":{"@timestamp":{"gt":"now-61s"}}},{"term":{"_type":"custom_win32_perfformatteddata_perfos_memory"}},{"script":{"lang":"expression","script":"doc['custom_win32_perfformatteddata_perfos_memory.AvailableMBytes'].value * 1000000.0 / doc['custom_win32_perfformatteddata_perfos_memory.TotalPhysicalMemory'].value < 0.1"}}]}},"size":10}]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:721)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:557)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:291)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:776)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:767)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:277)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.script.expression.ExpressionScriptCompilationException: Field [custom_win32_perfformatteddata_perfos_memory.AvailableMBytes] used in expression does not exist in mappings
	at org.elasticsearch.script.expression.ExpressionScriptEngineService.search(ExpressionScriptEngineService.java:129)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:432)
	at org.elasticsearch.index.query.ScriptFilterParser$ScriptFilter.<init>(ScriptFilterParser.java:135)
	at org.elasticsearch.index.query.ScriptFilterParser.parse(ScriptFilterParser.java:114)
	at org.elasticsearch.index.query.QueryParseContext.executeFilterParser(QueryParseContext.java:368)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerFilter(QueryParseContext.java:349)
	at org.elasticsearch.index.query.BoolFilterParser.parse(BoolFilterParser.java:92)
	at org.elasticsearch.index.query.QueryParseContext.executeFilterParser(QueryParseContext.java:368)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerFilter(QueryParseContext.java:349)
	at org.elasticsearch.index.query.IndexQueryParserService.parseInnerFilter(IndexQueryParserService.java:295)
	at org.elasticsearch.search.query.PostFilterParseElement.parse(PostFilterParseElement.java:33)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705)

**Comment by clintongormley** [comment]
This error is logged once per shard (as the error may be different on each shard).  You can change the level of `action.search` logging from `DEBUG` to `INFO` to avoid having these bad queries logged.

**Comment by rabx88** [comment]
Fair enough, thanks for the quick reply! I would consider changing the defaults to INFO though as most users are probably not interested in or capable of making sense of this level of detail.
