### ISSUE TITLE
[CI] PackageTests test60Reinstall failing

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#109897]
**Build scan:**
https://gradle-enterprise.elastic.co/s/oq3tuilsvc7bk/tests/:qa:packaging:destructiveDistroTest.default-rpm/org.elasticsearch.packaging.test.PackageTests/test60Reinstall

**Reproduction line:**
```
null
```

**Applicable branches:**
8.14

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.packaging.test.PackageTests#test60Reinstall`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test60Reinstall'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.packaging.test.PackageTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.RuntimeException: Installing distribution org.elasticsearch.packaging.util.Distribution@1b98f5a1 failed: exitCode = [1] stdout = [] stderr = [package elasticsearch-0:8.14.2~SNAPSHOT-1.x86_64 is already installed]

  at __randomizedtesting.SeedInfo.seed([E1A8202628EA4496:B38AD3878C51B07]:0)
  at org.elasticsearch.packaging.util.Packages.installPackage(Packages.java:93)
  at org.elasticsearch.packaging.util.Packages.installPackage(Packages.java:82)
  at org.elasticsearch.packaging.test.PackagingTestCase.install(PackagingTestCase.java:244)
  at org.elasticsearch.packaging.test.PackageTests.test60Reinstall(PackageTests.java:215)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1570)

```

**Comment by ywangd** [comment]
Just noticed this was reported as #109852 not long ago. It seems the fix did not fully work. This is still failing on many Linux distribution. I have also muted the test as part of report it here.

**Comment by mark-vieira** [comment]
> Just noticed this was reported as #109852 not long ago. It seems the fix did not fully work. This is still failing on many Linux distribution. I have also muted the test as part of report it here.

The above failure did not yet include the fix. I believe we can close this and remove the mute.

**Comment by ywangd** [comment]
You are right. I unmuted it with 5126e62fb428d71e06a53058be507aaba89fc8e6
Closing this issue
