### ISSUE TITLE
[CI] EsqlAsyncSecurityIT testInsufficientPrivilege failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#109806]
**Build scan:**
https://gradle-enterprise.elastic.co/s/7q4i7hkcgs3pw/tests/:x-pack:plugin:esql:qa:security:javaRestTest/org.elasticsearch.xpack.esql.EsqlAsyncSecurityIT/testInsufficientPrivilege

**Reproduction line:**
```
./gradlew ':x-pack:plugin:esql:qa:security:javaRestTest' --tests "org.elasticsearch.xpack.esql.EsqlAsyncSecurityIT.testInsufficientPrivilege" -Dtests.seed=6BE610F4610E7615 -Dtests.locale=ar-SA -Dtests.timezone=Australia/Lord_Howe -Druntime.java=17 -Dtests.fips.enabled=true
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.esql.EsqlAsyncSecurityIT#testInsufficientPrivilege`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testInsufficientPrivilege'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.EsqlAsyncSecurityIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: a string containing "unauthorized for user [test-admin] run as [metadata1_read2] with effective roles [metadata1_read2] on indices [index-user1], this action is granted by the index privileges [read,all]"
     but: was "method [GET], host [http://127.0.0.1:38777], URI [_query/async/FlpMUS1pSkhMVE0teDdGQnhNenphb1EbNXlJcVVhN01SU1c2OVJMT1Q4SEdNdzo1NjI0?wait_for_completion_timeout=60s], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [.async-search]","resource.type":"index_or_alias","resource.id":".async-search","index_uuid":"_na_","index":".async-search"}],"type":"index_not_found_exception","reason":"no such index [.async-search]","resource.type":"index_or_alias","resource.id":".async-search","index_uuid":"_na_","index":".async-search"},"status":404}"

  at __randomizedtesting.SeedInfo.seed([6BE610F4610E7615:7E9C3F3EA2F6C740]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
  at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2275)
  at org.elasticsearch.xpack.esql.EsqlSecurityIT.testInsufficientPrivilege(EsqlSecurityIT.java:145)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.elasticsearch.test.cluster.local.DefaultLocalElasticsearchCluster$1.evaluate(DefaultLocalElasticsearchCluster.java:47)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by nik9000** [comment]
Gradle says:
```
[2024-06-16T14:51:12,102][INFO ][o.e.x.e.EsqlAsyncSecurityIT] [testInsufficientPrivilege] REQUEST=Request{method='POST', endpoint='_query/async', entity=[Content-Type: application/json; charset=UTF-8,Content-Length: 231,Chunked: false], options=RequestOptions{headers=es-security-runas-user: metadata1_read2}}
[2024-06-16T14:51:12,103][INFO ][o.e.x.e.EsqlAsyncSecurityIT] [testInsufficientPrivilege] REQUEST body={query=FROM index-user1,index-user2 | STATS sum=sum(value) | limit 10000000, keep_on_completion=true, wait_for_completion_timeout=913nanos, pragma={enrich_max_workers=5, data_partitioning=segment, page_size=1}}
[2024-06-16T14:51:12,115][INFO ][o.e.x.e.EsqlAsyncSecurityIT] [testInsufficientPrivilege] RESPONSE=Response{requestLine=POST _query/async HTTP/1.1, host=http://127.0.0.1:38777, response=HTTP/1.1 200 OK}
[2024-06-16T14:51:12,115][INFO ][o.e.x.e.EsqlAsyncSecurityIT] [testInsufficientPrivilege] REQUEST=Request{method='GET', endpoint='_query/async/FlpMUS1pSkhMVE0teDdGQnhNenphb1EbNXlJcVVhN01SU1c2OVJMT1Q4SEdNdzo1NjI0?wait_for_completion_timeout=60s', options=RequestOptions{headers=es-security-runas-user: metadata1_read2}}
```

**Comment by nik9000** [comment]
It looks to me like the request in question timed out waiting for the planning of the index to finish but then retried fast enough that the `.async_search` index had yet to be created. That, or it isn't allowed to access it. I'm not sure which one is more likely.

And I can't reproduce locally.

**Comment by nik9000** [comment]
Looks to only fail a couple of % of the time. Going to run it in a loop with iters

**Comment by nik9000** [comment]
Ha! Reproduced:
```
    {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [.async-search]","resource.type":"index_or_alias","resource.id":".async-search","index_uuid":"_na_","index":".async-search"}],"type":"index_not_found_exception","reason":"no such index [.async-search]","resource.type":"index_or_alias","resource.id":".async-search","index_uuid":"_na_","index":".async-search"},"status":404}"
```
