### ISSUE TITLE
[CI] PackageUpgradeTests test10InstallBwcVersion failing

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#109901]
This fails on many branches include 8.14.2 and all the way to 8.1.3

**Build scan:**
https://gradle-enterprise.elastic.co/s/ohrrdisecnssi/tests/:qa:packaging:destructiveDistroUpgradeTest.v8.3.3.default-rpm/org.elasticsearch.packaging.test.PackageUpgradeTests/test10InstallBwcVersion

**Reproduction line:**
```
null
```

**Applicable branches:**
8.14

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.packaging.test.PackageUpgradeTests#test10InstallBwcVersion`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test10InstallBwcVersion'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.packaging.test.PackageUpgradeTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.RuntimeException: Installing distribution org.elasticsearch.packaging.util.Distribution@3d568341 failed: exitCode = [1] stdout = [] stderr = [warning: /opt/buildkite-agent/.gradle/caches/modules-2/files-2.1/elasticsearch-distribution/elasticsearch/8.3.3/2965288f452b7d3aeeb4ec83199c64e3b6e78910/elasticsearch-8.3.3-x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID d88e42b4: NOKEY
	installing package elasticsearch-0:8.3.3-1.x86_64 needs 1009MB on the / filesystem]

  at __randomizedtesting.SeedInfo.seed([29857869666838E8:BAB6D26F9FC895]:0)
  at org.elasticsearch.packaging.util.Packages.installPackage(Packages.java:93)
  at org.elasticsearch.packaging.util.Packages.installPackage(Packages.java:82)
  at org.elasticsearch.packaging.test.PackageUpgradeTests.test10InstallBwcVersion(PackageUpgradeTests.java:47)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1570)

```

**Comment by ywangd** [comment]
From the same test class, the following also fails. 
* [test20InstallUpgradedVersion](https://gradle-enterprise.elastic.co/s/abvppoehzqung/tests/task/:qa:packaging:destructiveDistroUpgradeTest.v7.17.23.default-rpm/details/org.elasticsearch.packaging.test.PackageUpgradeTests/test20InstallUpgradedVersion?top-execution=1)
* [test12SetupBwcVersion](https://gradle-enterprise.elastic.co/s/tc6xmja3w365y/tests/task/:qa:packaging:destructiveDistroUpgradeTest.v8.15.0.default-rpm/details/org.elasticsearch.packaging.test.PackageUpgradeTests/test12SetupBwcVersion?top-execution=1)

Including them here instead of raising new issue since I suspect they are caused by the same underlying problem.

**Comment by mark-vieira** [comment]
@brianseeders let's keep an eye on this to see what is happening. These tests in particular only build a single version RPM so they should not use much workspace disk space so something is definitely odd here.

**Comment by mark-vieira** [comment]
We've resolved the issues with disk space on agents.
