### ISSUE TITLE
NullPointerException in the Profiling plugin (xpack.profiling.action.CO2Calculator.getKiloWattsPerCore)

### ISSUE THREAD

**Issue by rockdaboot** [elastic/elasticsearch#109953]
### Elasticsearch Version

8.15 snapshot, 8.14

### Java Version

_bundled_

### OS Version

any

### Problem Description

The Kibana flamegraph and TopN functions view in Universal Profiling stay empty, even though data exists.
The reason for this is a Null Pointer Exception in the profiling plugin caused by incomplete host metadata.

Relevant part of the stacktrace:
```
[2024-06-19T18:37:03,104][WARN ][r.suppressed             ] [runTask-0] path: /_profiling/topn/functions, params: {}, status: 500 java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "<local2>" is null
        at org.elasticsearch.xpack.profiling.action.CO2Calculator.getKiloWattsPerCore(CO2Calculator.java:59)
        at org.elasticsearch.xpack.profiling.action.CO2Calculator.getAnnualCO2Tons(CO2Calculator.java:54)
        at org.elasticsearch.xpack.profiling.action.TransportGetStackTracesAction$StackTraceHandler.calculateCO2AndCosts(TransportGetStackTracesAction.java:631)
        at org.elasticsearch.xpack.profiling.action.TransportGetStackTracesAction$StackTraceHandler.mayFinish(TransportGetStackTracesAction.java:645)
        at org.elasticsearch.xpack.profiling.action.TransportGetStackTracesAction$StackTraceHandler.onHostsResponse(TransportGetStackTracesAction.java:601)
```

### Steps to Reproduce

Use Universal Profiling in Kibana with incomplete entries in `profiling-hosts`.

**Comment by rockdaboot** [comment]
An example record from `profiling-hosts` that triggers this NPE:
```
    "_source": {
      "profiling.project.id": "",
      "host.id": "",
      "@timestamp": 0,
      "ecs.version": "1.12.0"
    }
```
