### ISSUE TITLE
[CI] EsqlNodeSubclassTests ToPartial failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#110310]
### CI Link

https://buildkite.com/elastic/elasticsearch-pull-request/builds/24191#0190699a-a75d-4ece-975b-e64a993e0d1a

### Repro line

./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.tree.EsqlNodeSubclassTests" -Dtests.method="testInfoParameters {class org.elasticsearch.xpack.esql.expression.function.aggregate.ToPartial}" -Dtests.seed=F05AB5B3EBF180EC -Dtests.locale=et -Dtests.timezone=Africa/Harare -Druntime.java=22

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

```
<html>
<body>
<!--StartFragment-->
REPRODUCE WITH: ./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.tree.EsqlNodeSubclassTests" -Dtests.method="testInfoParameters {class org.elasticsearch.xpack.esql.expression.function.aggregate.ToPartial}" -Dtests.seed=F05AB5B3EBF180EC -Dtests.locale=et -Dtests.timezone=Africa/Harare -Druntime.java=22
--
  |  
  | EsqlNodeSubclassTests > testInfoParameters {class org.elasticsearch.xpack.esql.expression.function.aggregate.ToPartial} FAILED
  | java.lang.AssertionError: expected:<1> but was:<2>
  | at __randomizedtesting.SeedInfo.seed([F05AB5B3EBF180EC:A03EB7D16901A572]:0)
  | at org.junit.Assert.fail(Assert.java:89)
  | at org.junit.Assert.failNotEquals(Assert.java:835)
  | at org.junit.Assert.assertEquals(Assert.java:647)
  | at org.junit.Assert.assertEquals(Assert.java:633)
  | at org.elasticsearch.xpack.esql.core.tree.NodeSubclassTests.testInfoParameters(NodeSubclassTests.java:110)
  | at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  | at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  | at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  | at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  | at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  | at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  | at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  | at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  | at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  | at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  | at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  | at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  | at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  | at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  | at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  | at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  | at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  | at java.base/java.lang.Thread.run(Thread.java:1570)

<!--EndFragment-->
</body>
</html>
```

And a second one:

```
<html>
<body>
<!--StartFragment-->


REPRODUCE WITH: ./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.tree.EsqlNodeSubclassTests" -Dtests.method="testReplaceChildren {class org.elasticsearch.xpack.esql.expression.function.aggregate.ToPartial}" -Dtests.seed=F05AB5B3EBF180EC -Dtests.locale=et -Dtests.timezone=Africa/Harare -Druntime.java=22
  |  
  | EsqlNodeSubclassTests > testReplaceChildren {class org.elasticsearch.xpack.esql.expression.function.aggregate.ToPartial} FAILEDT
  | java.lang.AssertionError: expected:<uMHmNHeDwzJHCUMOPrJhSNFrj> but was:<?HuQdDh.hpwQL>ualsTests
  | at __randomizedtesting.SeedInfo.seed([F05AB5B3EBF180EC:C9A516FE12F7A012]:0)
  | at org.junit.Assert.fail(Assert.java:89)t org.elasticsearch.xpack...scalar.string.SubstringTests
  | at org.junit.Assert.failNotEquals(Assert.java:835) Executing test org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT
  | at org.junit.Assert.assertEquals(Assert.java:120)earch...operator.comparison.NotEqualsTests
  | at org.junit.Assert.assertEquals(Assert.java:146)
  | at org.elasticsearch.xpack.esql.core.tree.NodeSubclassTests.assertTransformedOrReplacedChildren(NodeSubclassTests.java:253)
  | at org.elasticsearch.xpack.esql.core.tree.NodeSubclassTests.testReplaceChildren(NodeSubclassTests.java:224)
  | at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  | at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)ts
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  | at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  | at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  | at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  | at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  | at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  | at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  | at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  | at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  | at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  | at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  | at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  | at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  | at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  | at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  | at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  | at java.base/java.lang.Thread.run(Thread.java:1570)
 

<br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>
```

**Comment by alex-spies** [comment]
`testReplaceChildren` is also failing for `toPartial` for me (once unmuted).

**Comment by alex-spies** [comment]
Currently `EsqlNodeSubclassTests` are all muted; I'm unmuting all but the `toPartial` tests [here](https://github.com/elastic/elasticsearch/pull/110284/files#diff-41386766c394f14f5f205f92bb26eb1420b80af0057c78b2842fcc7ddd3d67aaL110-R111).

**Comment by nik9000** [comment]
If you make a test extending `AbstractNodeTestCase` for that particular subclass you can customize the testing somewhat and that should cause `EsqlNodeSubclassTests` to skip testing that subclass. *AND* it'll cause `EsqlNodeSubclassTests` to build use your test subclass to build examples of your class using your subclass. See `LiteralTests` for such a subclass.

I'd long forgotten about this behavior, but I think it's an escape hatch I build half a lifetime ago when working on SQL.

**Comment by dnhatn** [comment]
@nik9000 Good suggestion. I opened https://github.com/elastic/elasticsearch/pull/110448/files.
