### ISSUE TITLE
org.elasticsearch.xpack.esql.EsqlAsyncSecurityIT#testUnauthorizedIndices failing

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#110340]
```
[2024-06-28T21:46:05,087][WARN ][o.e.x.e.EsqlAsyncSecurityIT] [testUnauthorizedIndices] 404 fetching task status
org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:46079], URI [_query/async/FkRPbVlPVjk2UWdtek82R2RVM1d5MncaaktqZ3EyOVVTdEtsTGNiRTNpYUtXdzo5NTI=?wait_for_completion_timeout=60s&error_trace=true], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"resource_not_found_exception","reason":"FkRPbVlPVjk2UWdtek82R2RVM1d5MncaaktqZ3EyOVVTdEtsTGNiRTNpYUtXdzo5NTI=","stack_trace":"org.elasticsearch.ResourceNotFoundException: FkRPbVlPVjk2UWdtek82R2RVM1d5MncaaktqZ3EyOVVTdEtsTGNiRTNpYUtXdzo5NTI=\n\tat org.elasticsearch.xcore@8.15.0-SNAPSHOT/org.elasticsearch.xpack.core.async.AsyncTaskIndexService.parseResponseFromIndex(AsyncTaskIndexService.java:475)\n\tat org.elasticsearch.xcore@8.15.0-SNAPSHOT/org.elasticsearch.xpack.core.async.AsyncTaskIndexService.lambda$getResponseFromIndex$5(AsyncTaskIndexService.java:438)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener.onResponse(ActionListenerImplementations.java:217)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:392)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:202)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:196)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:307)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:392)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:48)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1480)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1577)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1551)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:35)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:32)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:19)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListener.respondAndRelease(ActionListener.java:367)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:78)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:75)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:100)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1570)\n"}],"type":"resource_not_found_exception","reason":"FkRPbVlPVjk2UWdtek82R2RVM1d5MncaaktqZ3EyOVVTdEtsTGNiRTNpYUtXdzo5NTI=","stack_trace":"org.elasticsearch.ResourceNotFoundException: FkRPbVlPVjk2UWdtek82R2RVM1d5MncaaktqZ3EyOVVTdEtsTGNiRTNpYUtXdzo5NTI=\n\tat org.elasticsearch.xcore@8.15.0-SNAPSHOT/org.elasticsearch.xpack.core.async.AsyncTaskIndexService.parseResponseFromIndex(AsyncTaskIndexService.java:475)\n\tat org.elasticsearch.xcore@8.15.0-SNAPSHOT/org.elasticsearch.xpack.core.async.AsyncTaskIndexService.lambda$getResponseFromIndex$5(AsyncTaskIndexService.java:438)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener.onResponse(ActionListenerImplementations.java:217)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:392)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:202)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:196)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:307)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:392)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:48)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1480)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1577)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1551)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:35)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:32)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:19)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListener.respondAndRelease(ActionListener.java:367)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:78)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:75)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:100)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1570)\n"},"status":404}
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:351) ~[elasticsearch-rest-client-8.15.0-SNAPSHOT.jar:8.15.0-SNAPSHOT]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:317) ~[elasticsearch-rest-client-8.15.0-SNAPSHOT.jar:8.15.0-SNAPSHOT]
...

org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:46079], URI [_query/async/FkRPbVlPVjk2UWdtek82R2RVM1d5MncaaktqZ3EyOVVTdEtsTGNiRTNpYUtXdzo5NTI=?wait_for_completion_timeout=60s&error_trace=true], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"resource_not_found_exception","reason":"FkRPbVlPVjk2UWdtek82R2RVM1d5MncaaktqZ3EyOVVTdEtsTGNiRTNpYUtXdzo5NTI=","stack_trace":"org.elasticsearch.ResourceNotFoundException: FkRPbVlPVjk2UWdtek82R2RVM1d5MncaaktqZ3EyOVVTdEtsTGNiRTNpYUtXdzo5NTI=\n\tat org.elasticsearch.xcore@8.15.0-SNAPSHOT/org.elasticsearch.xpack.core.async.AsyncTaskIndexService.parseResponseFromIndex(AsyncTaskIndexService.java:475)\n\tat org.elasticsearch.xcore@8.15.0-SNAPSHOT/org.elasticsearch.xpack.core.async.AsyncTaskIndexService.lambda$getResponseFromIndex$5(AsyncTaskIndexService.java:438)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener.onResponse(ActionListenerImplementations.java:217)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:392)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:202)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:196)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:307)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:392)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:48)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1480)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1577)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1551)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:35)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:32)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:19)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListener.respondAndRelease(ActionListener.java:367)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:78)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:75)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:100)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1570)\n"}],"type":"resource_not_found_exception","reason":"FkRPbVlPVjk2UWdtek82R2RVM1d5MncaaktqZ3EyOVVTdEtsTGNiRTNpYUtXdzo5NTI=","stack_trace":"org.elasticsearch.ResourceNotFoundException: FkRPbVlPVjk2UWdtek82R2RVM1d5MncaaktqZ3EyOVVTdEtsTGNiRTNpYUtXdzo5NTI=\n\tat org.elasticsearch.xcore@8.15.0-SNAPSHOT/org.elasticsearch.xpack.core.async.AsyncTaskIndexService.parseResponseFromIndex(AsyncTaskIndexService.java:475)\n\tat org.elasticsearch.xcore@8.15.0-SNAPSHOT/org.elasticsearch.xpack.core.async.AsyncTaskIndexService.lambda$getResponseFromIndex$5(AsyncTaskIndexService.java:438)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener.onResponse(ActionListenerImplementations.java:217)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:392)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:202)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:196)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:307)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:392)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:48)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1480)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1577)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1551)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:35)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:32)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:19)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListener.respondAndRelease(ActionListener.java:367)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:78)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:75)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:100)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)\n\tat org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1570)\n"},"status":404}
```

**Comment by nik9000** [comment]
This is just me not having solved a bug in #110305.
