### ISSUE TITLE
Elastic Search Mapping issue

### ISSUE THREAD

**Issue by sugansan** [elastic/elasticsearch#11031]
curl -XPUT 10.206.72.108:9200/_template/demotest -d '{

    "template": "logstash-jmeter-results-*",
    "settings": {
        "number_of_shards": 1,
        "number_of_replicas": 0,
        "index.refresh_interval": "5s"
    },
    "mappings": {
        "logs": {
            "properties": {
                 "elapsed": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "responseCode": {
                    "type": "integer"
                },
                "threadName": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "bytes": {
                    "type": "integer"
                },
                "responseMessage": {
                    "type": "string"
                },
                "Latency": {
                    "type": "integer"
                }, 
				"dataType": {
                    "type": "string"
                }    
            }
        }
    }
}'

I am unable to take STAT from kibana to show min,max ,count for the integer fields

Elastic Search shows the following error

csearch.action.search.SearchRequest@1495de2a]
org.elasticsearch.search.SearchParseException: [logstash-jmeter-results-2015.05.07][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"facets":{"stats":{"statistical":{"field":"Latency"},"facet_filter":{"fquery":{"query":{"filtered":{"query":{"bool":{"should":[{"query_string":{"query":"*"}}]}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"from":1430989905359,"to":1430990205359}}}]}}}}}}},"stats_*":{"statistical":{"field":"Latency"},"facet_filter":{"fquery":{"query":{"filtered":{"query":{"bool":{"should":[{"query_string":{"query":"*"}}]}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"from":1430989905359,"to":1430990205359}}}]}}}}}}}},"size":0}]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:664)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:515)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:487)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:256)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:206)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:203)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.search.facet.FacetPhaseExecutionException: Facet [stats]: field [Latency] isn't a number field, but a string
        at org.elasticsearch.search.facet.statistical.StatisticalFacetParser.parse(StatisticalFacetParser.java:132)
        at org.elasticsearch.search.facet.FacetParseElement.parse(FacetParseElement.java:93)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:648)
        ... 9 more

**Comment by rjernst** [comment]
The error is this:
> Caused by: org.elasticsearch.search.facet.FacetPhaseExecutionException: Facet [stats]: field [Latency] isn't a number field, but a string

This indicates the mappings are not what you think (perhaps you pass in `Latency` in a json string and that template has not always existed?). Please join us on https://discuss.elastic.co/ for troubleshooting help, we reserve github for confirmed bugs and feature requests.

**Comment by sugansan** [comment]
Yes. But I already added Latency field to mapping template. This  is resolved . There was a conflict between my old indexing templates. I deleted the old ones and renamed the index pattern. Then my problem got resolved.
