### ISSUE TITLE
ES|QL: test with multi-node and no replicas fails on Serverless

### ISSUE THREAD

**Issue by luigidellaquila** [elastic/elasticsearch#110434]
```
EsqlClientYamlIT » test {p0=esql/170_no_replicas/Test From 1}
EsqlClientYamlIT » test {p0=esql/170_no_replicas/Test From 5}
```

```

[2024-07-03T10:24:58,970][WARN ][o.e.x.e.a.EsqlResponseListener] [search-2-Demndmu] Request failed with status [SERVICE_UNAVAILABLE]: org.elasticsearch.action.NoShardAvailableActionException: index [test7] has no active shard copy |  
-- | --
  | at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.fieldcaps.RequestDispatcher.<init>(RequestDispatcher.java:104) |  
  | at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.doExecuteForked(TransportFieldCapabilitiesAction.java:217) |  
  | at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.lambda$doExecute$0(TransportFieldCapabilitiesAction.java:115) |  
  | at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:100) |  
  | at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) |  
  | at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) |  
  | at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984) |  
  | at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) |  
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) |  
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) |  
  | at java.base/java.lang.Thread.run(Thread.java:1570)


```

**Comment by luigidellaquila** [comment]
Closing and moving where it belongs (Serverless)
