### ISSUE TITLE
Running into IllegalAccessError on Virtuozzo VPS

### ISSUE THREAD

**Issue by wodka** [elastic/elasticsearch#11062]
log does not show any entry (no errors) but a search results gives the message:
**IllegalAccessError[tried to access method .<init>()V from class org.elasticsearch.common.hppc.IntObjectOpenHashMap$ValuesContainer]**

*also the following (other error but with that it's still running)*
2015-05-08 15:03:25,583][DEBUG][action.admin.cluster.node.stats] [Cypher] failed to execute on node [dB-NuNvWR1ynNyc9aHxHOw]
java.lang.NullPointerException
	at org.elasticsearch.monitor.fs.SigarFsProbe.stats(SigarFsProbe.java:83)
	at org.elasticsearch.monitor.fs.FsService$FsStatsCache.refresh(FsService.java:56)
	at org.elasticsearch.monitor.fs.FsService$FsStatsCache.refresh(FsService.java:49)
	at org.elasticsearch.common.util.SingleObjectCache.getOrRefresh(SingleObjectCache.java:55)
	at org.elasticsearch.monitor.fs.FsService.stats(FsService.java:46)
	at org.elasticsearch.node.service.NodeService.stats(NodeService.java:156)
	at org.elasticsearch.action.admin.cluster.node.stats.TransportNodesStatsAction.nodeOperation(TransportNodesStatsAction.java:96)
	at org.elasticsearch.action.admin.cluster.node.stats.TransportNodesStatsAction.nodeOperation(TransportNodesStatsAction.java:44)
	at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction$2.run(TransportNodesOperationAction.java:141)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

sometimes it returns to work after a few minutes, sometimes I have to restart es. I do not know how to reproduce the error - only that is happening since the beginning of the week on 2 vservers.

**Comment by clintongormley** [comment]
Hi @wodka 

What OS are you running on, and what version of Elasticsearch?  I'm guessing that sigar doesn't yet support whatever you're using.  Try removing `lib/sigar` and restarting Elasticsearch, and see if the problem goes away.

**Comment by wodka** [comment]
Hi, 

can you tell me how to remove lib/sigar?

OS: Ubuntu 14.04.2 LTS
Kernel: 3.13.0-042stab106.6 #1 SMP Mon Apr 20 14:48:47 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

Elasticsearch Version:
```json
{
  "status" : 200,
  "name" : "Skinhead",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.5.2",
    "build_hash" : "62ff9868b4c8a0c45860bebb259e21980778ab1c",
    "build_timestamp" : "2015-04-27T09:21:06Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

I cannot tell which version of virtuozzo (running on hosteurope.de infrastructure)

**Comment by imotov** [comment]
@wodka: just delete the `sigar` directory or move it somewhere else from the `lib` directory where it is residing. On Ubuntu it should be in `/usr/share/elasticsearch/lib/sigar`.

**Comment by wodka** [comment]
Hi, this seems to solve the problem, the strange thing is that it was working prior to this week... 

thx anyway!

should I keep the ticket open?

**Comment by clintongormley** [comment]
Closing in favour of #11034
