### ISSUE TITLE
bulk index connection timeout caused by readtimeout error

### ISSUE THREAD

**Issue by Fool-LeoTao** [elastic/elasticsearch#11075]
In my case,I am trying to use bulk indexing for a large amount of documents.
```
def bulk_index():
    chunk = []
    for count, doc in enumerate(doc_generator()):
        id = doc.get('_id')
        chunk.append({
            'index': {
                '_id': id
            }
        })
        chunk.append(doc)
        if (count + 1) % 10000 == 0:
            assert len(chunk) == 20000
            res = es.bulk(index='weibo', doc_type='user', body=chunk)
            assert res['errors'] is False
            chunk = []
    print 'docs total count: %s' % (count + 1)
```
```
Traceback (most recent call last):
  File "es_index.py", line 63, in <module>
    bulk_index()
  File "es_index.py", line 16, in _
    rv = func(*args, **kwargs)
  File "es_index.py", line 53, in bulk_index
    res = es.bulk(index='weibo', doc_type='user', body=chunk)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 711, in bulk
    params=params, body=self._bulk_body(body))
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 79, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=10))
```
My `elasticsearch.yml`is just like:
```
index.analysis.analyzer.default.type : "ik"
index.store.type: mmapfs
indices.memory.index_buffer_size: 30%
index.translog.flush_threshold_ops: 50000
refresh_interval: 30s
```

**Comment by markwalkom** [comment]
Hello,
We're moving to https://discuss.elastic.co for any technical troubleshooting issues that are not bugs, please join us there for future discussion on this topic.
