### ISSUE TITLE
Improve exception message for bad `${ENV_VAR}` substitution in `elasticsearch.yml`

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#110858]
Elasticsearch will interpolate environment variables into settings read from `elasticsearch.yml`:

```
cluster.name: ${ES_CLUSTER_NAME}
```

Any environment variables used in this way must be set, but the error for an unset environment variable is kinda opaque:

```
Exception in thread "main" java.lang.IllegalArgumentException: Could not resolve placeholder 'ES_CLUSTER_NAME'
	at org.elasticsearch.common.settings.PropertyPlaceholder.parseStringValue(PropertyPlaceholder.java:102)
	at org.elasticsearch.common.settings.PropertyPlaceholder.replacePlaceholders(PropertyPlaceholder.java:57)
	at org.elasticsearch.common.settings.Settings$Builder.replacePropertyPlaceholders(Settings.java:1314)
	at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:56)
	at org.elasticsearch.common.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:110)
	at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
	at org.elasticsearch.cli.Command.main(Command.java:50)
	at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)
```

Could we mention in this message that it relates to an environment variable mentioned in `elasticsearch.yml` which is not set?

**Comment by niklasfriberg** [comment]
I'd like to contribute on this issue, could I get assigned please.

**Comment by DaveCTurner** [comment]
Thanks @niklasfriberg - we don't generally assign issues like this but I'm not aware of anyone else working on this issue right now. Please feel free to contribute a PR.

**Comment by minkichoe** [comment]
I have also been working on this since yesterday. I understand that I didn't inform you in advance, so there's no obligation to accept my PR. However, I wanted to share my work rather than let it go to waste. https://github.com/elastic/elasticsearch/pull/114552
