### ISSUE TITLE
CanMatchPreFilterSearchPhaseTests > testSortShards FAILED

### ISSUE THREAD

**Issue by maxhniebergall** [elastic/elasticsearch#110991]
### CI Link

https://gradle-enterprise.elastic.co/s/75i35dy3fsa7e/tests/task/:server:test/details/org.elasticsearch.action.search.CanMatchPreFilterSearchPhaseTests/testSortShards?top-execution=1

### Repro line

./gradlew ":server:test" --tests "org.elasticsearch.action.search.CanMatchPreFilterSearchPhaseTests.testSortShards" -Dtests.seed=C49998B0F87552D6 -Dtests.locale=pl-PL -Dtests.timezone=Europe/Copenhagen -Druntime.java=22	

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

CanMatchPreFilterSearchPhaseTests > testSortShards FAILED
    java.lang.AssertionError: expected:<[logs][3]> but was:<[logs][5]>
        at __randomizedtesting.SeedInfo.seed([C49998B0F87552D6:A20BF86ABFFC582C]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at org.elasticsearch.action.search.CanMatchPreFilterSearchPhaseTests.testSortShards(CanMatchPreFilterSearchPhaseTests.java:368)

**Comment by benwtrent** [comment]
@original-brownbear not a coincidence I think :)
