### ISSUE TITLE
AssertionError hit if data stream matches match-all index template

### ISSUE THREAD

**Issue by masseyke** [elastic/elasticsearch#111204]
I'm allowed to create a match-all data stream index template:
```
$ curl -X PUT "localhost:9200/_index_template/my-index-template?pretty" -H 'Content-Type: application/json' -d'
{
  "index_patterns": ["*"],
  "data_stream": { },
  "priority": 100,
  "template": {
    "lifecycle": {
      "data_retention": "30d"
    }
  },
  "_meta": {
    "description": "Template with data stream lifecycle"
  }
}
'
{
  "acknowledged" : true
}
```
But if i try to create a data stream that matches that template, my server crashes with an assertion error (if assertions are enabled):
```
$ curl -X POST "localhost:9200/my-data-stream/_doc/?pretty" -H 'Content-Type: application/json' -d'
{
  "@timestamp": "2099-11-15T13:12:00",
  "message": "GET /search HTTP/1.1 200 1070000",
  "user": {
    "id": "asdf"
  }               
}                           
'
```
The reason is that we ignore the matching v2 template because it's match-all and we're a creating the data stream's write index as a hidden index https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java#L1319, and then crash because there's no `@timestamp` field in the mapping:
```
[2024-07-23T10:13:53,678][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [runTask-0] fatal error in thread [elasticsearch[runTask-0][masterService#updateTask][T#5]], exiting java.lang.AssertionError: _data_stream_timestamp meta field mapper must exist
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateDataStreamService.validateTimestampFieldMapping(MetadataCreateDataStreamService.java:485)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.index.IndexMode$1.validateTimestampFieldMapping(IndexMode.java:69)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.updateIndexMappingsAndBuildSortOrder(MetadataCreateIndexService.java:1355)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.lambda$applyCreateIndexWithTemporaryService$2(MetadataCreateIndexService.java:478)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:715)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexWithTemporaryService(MetadataCreateIndexService.java:476)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequestWithV1Templates(MetadataCreateIndexService.java:600)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:424)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:442)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateDataStreamService.createBackingIndex(MetadataCreateDataStreamService.java:405)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateDataStreamService.createDataStream(MetadataCreateDataStreamService.java:306)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateDataStreamService.createDataStream(MetadataCreateDataStreamService.java:204)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateDataStreamService.createDataStream(MetadataCreateDataStreamService.java:129)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.admin.indices.create.AutoCreateAction$TransportAction$CreateIndexTask.execute(AutoCreateAction.java:261)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.admin.indices.create.AutoCreateAction$TransportAction.lambda$new$0(AutoCreateAction.java:120)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1070)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1033)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:233)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1686)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListener.run(ActionListener.java:444)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.run(MasterService.java:1683)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$5.lambda$doRun$0(MasterService.java:1278)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListener.run(ActionListener.java:444)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$5.doRun(MasterService.java:1257)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
        at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1570)
```
When we made the initial request it was as a non-hidden index-like thing, and when we look for the template we find the match-all one that is a data stream template. Then we make the request to make the backing index itself as a hidden index (https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateDataStreamService.java#L401), don't find any templates, and blow up.
So it's valid to have a match-all template for a data stream... you just can't create any indices in that data stream.
We need to change the code so that it is not possible to hit this assertion error -- we either need to prevent users from making match-all data stream index templates, or allow hidden indices to use match-all templates.

**Comment by masseyke** [comment]
We've discussed this, and plan to allow hidden indices to be created in this case (that is, we will allow users to create a data stream template that matches `*`).
