### ISSUE TITLE
ESQL: unexpected error when querying an empty-mapping index

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#111545]
### Description

```
PUT /localhost/test

{
    "mappings": {
        "properties": {

        }
    }
}
```

then querying this index with a simple `FROM test` results in 

```
path: /_query, params: {format=txt, error_trace=true}, status: 500 java.lang.IllegalStateException: can't find input for [<no-fields>{r}#1]
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planProject(LocalExecutionPlanner.java:601)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:202)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planExchangeSink(LocalExecutionPlanner.java:320)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:234)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:173)
        at org.elasticsearch.xpack.esql.plugin.ComputeService.runCompute(ComputeService.java:403)
```

Having an index like

```
PUT /localhost/test

{   }
```

and using the same ES|QL query has a more user friendly behavior:

```
  <no-fields>  
---------------
```

**Comment by astefan** [comment]
This is blocked by https://github.com/elastic/elasticsearch/issues/107031

**Comment by GalLalouche** [comment]
This would also fail if the mappings themselves are empty objects, e.g.,
```
PUT /localhost/test

{
    "mappings": {
        "properties": {
            "a": {"type":"object"},
            "b": {"type":"object"},
        }
    }
}
```

**Comment by bpintea** [comment]
This now looks like:
```
500 java.lang.IllegalStateException: Found 1 problem
line 84:3: Plan [ProjectExec[[<no-fields>{r$}#1]]] optimized incorrectly due to missing references [<no-fields>{r$}#1]
        at org.elasticsearch.xpack.esql.optimizer.PostOptimizationPhasePlanVerifier.verify(PostOptimizationPhasePlanVerifier.java:53)
        at org.elasticsearch.xpack.esql.optimizer.LocalPhysicalPlanOptimizer.verify(LocalPhysicalPlanOptimizer.java:52)
        at org.elasticsearch.xpack.esql.optimizer.LocalPhysicalPlanOptimizer.localOptimize(LocalPhysicalPlanOptimizer.java:48)
        at org.elasticsearch.xpack.esql.planner.PlannerUtils.lambda$localPlan$12(PlannerUtils.java:257)
        at org.elasticsearch.xpack.esql.core.tree.Node.lambda$transformUp$12(Node.java:255)
        at org.elasticsearch.xpack.esql.core.tree.Node.transformUp(Node.java:250)
        at org.elasticsearch.xpack.esql.core.tree.Node.lambda$transformUp$11(Node.java:248)
        at org.elasticsearch.xpack.esql.core.tree.Node.transformChildren(Node.java:273)
        at org.elasticsearch.xpack.esql.core.tree.Node.transformUp(Node.java:248)
        at org.elasticsearch.xpack.esql.core.tree.Node.transformUp(Node.java:255)
        at org.elasticsearch.xpack.esql.planner.PlannerUtils.localPlan(PlannerUtils.java:230)
        at org.elasticsearch.xpack.esql.planner.PlannerUtils.localPlan(PlannerUtils.java:203)
        at org.elasticsearch.xpack.esql.planner.PlannerUtils.localPlan(PlannerUtils.java:186)
        at org.elasticsearch.xpack.esql.plugin.ComputeService.runCompute(ComputeService.java:677)
        at org.elasticsearch.xpack.esql.plugin.DataNodeComputeHandler$DataNodeRequestExecutor.lambda$runBatch$4(DataNodeComputeHandler.java:370)
        at org.elasticsearch.server@9.4.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:258)
        at org.elasticsearch.server@9.4.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:58)
        at org.elasticsearch.server@9.4.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:55)
        at org.elasticsearch.server@9.4.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:101)
        at org.elasticsearch.server@9.4.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
```

**Comment by alex-spies** [comment]
We keep re-discovering this. @jan-elastic found this problem and included an analysis in https://github.com/elastic/elasticsearch/issues/149718.

**Comment by jan-elastic** [comment]
FYI: the `GenerativeIT` fails sometimes by generating this (that's how I discovered it).

**Comment by GalLalouche** [comment]
IMHO, the "right" thing to do here is to have a nicer error message than an internal error. Querying completely unmapped indices and not specifying any fields is almost certainly a user mistake, and the user should be notified of that. 
Note that this isn't related to `LOAD`/`NULLIFY`, which by definition need _something_ to work with (i.e., explicitly mentioned fields or fields being at least partially mapped). 

However, for `LOAD_ALL` (MVP #154413) we _do_ want to return all the fields from `_source` even when they aren't mentioned.

**Comment by mayya-sharipova** [comment]
We see these issues in production Serverless on a project:

```
java.lang.IllegalStateException: Found 1 problem
line 3:3: Plan [ProjectExec[[<no-fields>{r$}#89]]] optimized incorrectly due to missing references [<no-fields>{r$}#89]
```
