### ISSUE TITLE
ESQL: MultiClusterSpecIT failing with "sink exchanger for id [...] already exists"

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#111546]
### CI Link

https://gradle-enterprise.elastic.co/s/p7xn5xnzen3x4/tests/task/:x-pack:plugin:esql:qa:server:multi-clusters:v8.16.0%23bwcTest/details/org.elasticsearch.xpack.esql.ccq.MultiClusterSpecIT/test%20%7Bunion_types.MultiIndexIndirectUseOfUnionTypesInInlineStats%7D?top-execution=1

### Repro line

REPRODUCE WITH: ./gradlew ":x-pack:plugin:esql:qa:server:multi-clusters:v8.16.0#bwcTest" -Dtests.class="org.elasticsearch.xpack.esql.ccq.MultiClusterSpecIT" -Dtests.method="test {union_types.MultiIndexIndirectUseOfUnionTypesInInlineStats}" -Dtests.seed=50E27B3168B4639E -Dtests.bwc=true -Dtests.locale=tr -Dtests.timezone=Europe/Skopje -Druntime.java=22

### Does it reproduce?

Didn't try

### Applicable branches

alex-spies:fix-union-types-breaking-unsupported-in-renames

### Failure excerpt

```

MultiClusterSpecIT > test {union_types.MultiIndexIndirectUseOfUnionTypesInInlineStats} FAILED
    org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:40903], URI [/_query?pretty=true&error_trace=true], status line [HTTP/1.1 500 Internal Server Error]
    :)
    úerrorúroot_causeøútypeVillegal_state_exceptionreasonàsink exchanger for id [xQjXQFEHQH-XPNZXRvIIPg:5143] already existsüstack_traceäorg.elasticsearch.ElasticsearchException$1: sink exchanger for id [xQjXQFEHQH-XPNZXRvIIPg:5143] already exists
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:704)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:632)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.rest.RestResponse.build(RestResponse.java:186)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:145)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:116)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:53)
    	at org.elasticsearch.xpack.esql.action.EsqlResponseListener.lambda$wrapWithLogging$1(EsqlResponseListener.java:173)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:264)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.rest.action.RestCancellableNodeClient$1.onFailure(RestCancellableNodeClient.java:96)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:409)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$1.onFailure(TaskManager.java:214)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onFailure(ActionListenerImplementations.java:345)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:409)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
    	at org.elasticsearch.xpack.esql.execution.PlanExecutor.lambda$esql$0(PlanExecutor.java:73)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:264)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
    	at org.elasticsearch.xpack.esql.plugin.ComputeService.lambda$execute$1(ComputeService.java:144)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.acceptException(ActionListenerImplementations.java:187)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onFailure(ActionListenerImplementations.java:192)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
    	at org.elasticsearch.xpack.esql.plugin.ComputeListener.lambda$new$1(ComputeListener.java:53)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:264)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:409)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:127)
    	at org.elasticsearch.base@8.16.0-SNAPSHOT/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)
    	at org.elasticsearch.base@8.16.0-SNAPSHOT/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)
    	at org.elasticsearch.base@8.16.0-SNAPSHOT/org.elasticsearch.core.Releasables$4.close(Releasables.java:159)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.support.RefCountingListener$1.onFailure(RefCountingListener.java:158)
    	at org.elasticsearch.xpack.esql.plugin.ComputeListener.lambda$acquireAvoid$2(ComputeListener.java:68)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.acceptException(ActionListenerImplementations.java:187)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onFailure(ActionListenerImplementations.java:192)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onFailure(ActionListenerImplementations.java:345)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:409)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onFailure(ActionListenerImplementations.java:306)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:409)
    	at org.elasticsearch.compute.operator.DriverRunner$1.done(DriverRunner.java:63)
    	at org.elasticsearch.compute.operator.DriverRunner$1.onFailure(DriverRunner.java:54)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener$FailureResult.complete(SubscribableListener.java:398)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:310)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:209)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:174)
    	at org.elasticsearch.compute.operator.Driver.abort(Driver.java:224)
    	at org.elasticsearch.compute.operator.DriverTaskRunner$1.lambda$start$0(DriverTaskRunner.java:60)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:264)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.transport.TransportResponseHandler$1.handleException(TransportResponseHandler.java:63)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1779)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1503)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1637)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.transport.TransportService$DirectResponseChannel$2.doRun(TransportService.java:1617)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
    	at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    	at java.base/java.lang.Thread.run(Thread.java:1570)
    Caused by: java.lang.IllegalStateException: sink exchanger for id [xQjXQFEHQH-XPNZXRvIIPg:5143] already exists
    	at org.elasticsearch.compute.operator.exchange.ExchangeService.createSinkHandler(ExchangeService.java:120)
    	at org.elasticsearch.compute.operator.exchange.ExchangeService$OpenExchangeRequestHandler.messageReceived(ExchangeService.java:196)
    	at org.elasticsearch.compute.operator.exchange.ExchangeService$OpenExchangeRequestHandler.messageReceived(ExchangeService.java:193)
    	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
    	at org.elasticsearch.transport.InboundHandler.doHandleRequest(InboundHandler.java:287)
    	at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:300)
    	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
    	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
    	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
    	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    	at java.lang.Thread.run(Thread.java:1570)
    	Suppressed: org.elasticsearch.tasks.TaskCancelledException: cancelled on failure
    		at org.elasticsearch.compute.operator.Driver.cancel(Driver.java:304)
    		at org.elasticsearch.compute.operator.DriverTaskRunner$DriverRequest$1.onCancelled(DriverTaskRunner.java:101)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.tasks.CancellableTask.cancel(CancellableTask.java:43)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager$CancellableTaskHolder.cancel(TaskManager.java:617)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager.cancel(TaskManager.java:274)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.tasks.TaskCancellationService.doCancelTaskAndDescendants(TaskCancellationService.java:141)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.tasks.TaskCancellationService.lambda$cancelTaskAndDescendants$0(TaskCancellationService.java:120)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ResultDeduplicator.executeOnce(ResultDeduplicator.java:49)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.tasks.TaskCancellationService.cancelTaskAndDescendants(TaskCancellationService.java:117)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.tasks.TaskCancellationService$BanParentRequestHandler.messageReceived(TaskCancellationService.java:372)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.tasks.TaskCancellationService$BanParentRequestHandler.messageReceived(TaskCancellationService.java:356)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:1085)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.transport.TransportService$3.sendRequest(TransportService.java:160)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:982)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:877)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.tasks.TaskCancellationService.setBanOnChildConnections(TaskCancellationService.java:195)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.tasks.TaskCancellationService.doCancelTaskAndDescendants(TaskCancellationService.java:146)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.tasks.TaskCancellationService.lambda$cancelTaskAndDescendants$0(TaskCancellationService.java:120)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ResultDeduplicator.executeOnce(ResultDeduplicator.java:49)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.tasks.TaskCancellationService.cancelTaskAndDescendants(TaskCancellationService.java:117)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager.cancelTaskAndDescendants(TaskManager.java:812)
    		at org.elasticsearch.xpack.esql.plugin.ComputeListener.lambda$acquireAvoid$2(ComputeListener.java:65)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.acceptException(ActionListenerImplementations.java:187)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onFailure(ActionListenerImplementations.java:192)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onFailure(ActionListenerImplementations.java:306)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:409)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:409)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:127)
    		at org.elasticsearch.base@8.16.0-SNAPSHOT/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)
    		at org.elasticsearch.base@8.16.0-SNAPSHOT/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)
    		at org.elasticsearch.base@8.16.0-SNAPSHOT/org.elasticsearch.core.Releasables$4.close(Releasables.java:159)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.support.RefCountingListener$1.onFailure(RefCountingListener.java:158)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:53)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1503)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.transport.InboundHandler.doHandleException(InboundHandler.java:474)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.transport.InboundHandler$3.doRun(InboundHandler.java:466)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
    		at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    		at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by alex-spies** [comment]
The work in the branch this fails on seems highly unrelated; it only touches validation.

But! It adds a new INLINESTATS test, which is failing here. Problems with exchanges seem plausible with INLINESTATS.

/CC @nik9000

**Comment by alex-spies** [comment]
Here's just the test, so people don't have to checkout my branch:

```

multiIndexIndirectUseOfUnionTypesInLookup
// TODO: `union_types` is required only because this makes the test skip in the csv tests; better solution:
// make the csv tests work with multiple indices.
required_capability: union_types
required_capability: lookup_v4
FROM sample_data, sample_data_ts_long
| SORT client_ip ASC
| LIMIT 1
| EVAL int = (event_duration - 1232380)::integer
| LOOKUP int_number_names ON int
;

@timestamp:null | client_ip:ip | event_duration:long | message:keyword | int:integer | name:keyword
           null | 172.21.0.5   |             1232382 | Disconnected    |           2 | two
;
```

**Comment by alex-spies** [comment]
This looks like it could be the same as https://github.com/elastic/elasticsearch/issues/106641, which is already resolved, so I'm closing this.

**Comment by alex-spies** [comment]
Actually, https://github.com/elastic/elasticsearch/pull/110569, which fixed https://github.com/elastic/elasticsearch/issues/106641, doesn't affect `EsqlSpecTestCase`/`MultiClusterSpecIt`. But since this only happened in a branch, I think this can remain closed; the test bot will open a new issue if this happens again.
