### ISSUE TITLE
[CI] RestEsqlIT failing in release builds

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#111726]
### CI Link

https://gradle-enterprise.elastic.co/s/og3auotbcrwo6/tests/task/:x-pack:plugin:esql:qa:server:multi-node:javaRestTest/details/org.elasticsearch.xpack.esql.qa.multi_node.RestEsqlIT/testTopLevelFilterBoolMerged%20%7BASYNC%7D?top-execution=1

### Repro line

./gradlew ":x-pack:plugin:esql:qa:server:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.RestEsqlIT.testTopLevelFilterBoolMerged {ASYNC}" -Dtests.seed=BDDF8B812FD76586 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=en-PH -Dtests.timezone=Europe/Belgrade -Druntime.java=22

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

```
[2024-08-08T23:53:30,617][ERROR][o.e.ExceptionsHelper     ] [test-cluster-0] fatal error java.lang.AssertionError: java.lang.ClassCastException: class org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput cannot be cast to class org.elasticsearch.xpack.esql.io.stream.PlanStreamInput (org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput is in module org.elasticsearch.server@8.16.0 of loader 'app'; org.elasticsearch.xpack.esql.io.stream.PlanStreamInput is in unnamed module of loader java.net.FactoryURLClassLoader @5817f1ca)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.ExceptionsHelper.lambda$maybeDieOnAnotherThread$4(ExceptionsHelper.java:444)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.ExceptionsHelper.maybeDieOnAnotherThread(ExceptionsHelper.java:434)
	at org.elasticsearch.transport.netty4@8.16.0/org.elasticsearch.transport.netty4.Netty4MessageInboundHandler.exceptionCaught(Netty4MessageInboundHandler.java:66)
	at io.netty.transport@4.1.109.Final/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.transport@4.1.109.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:447)
	at io.netty.transport@4.1.109.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.109.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.codec@4.1.109.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.transport@4.1.109.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.transport@4.1.109.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.109.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.transport@4.1.109.Final/io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.transport@4.1.109.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.transport@4.1.109.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.109.Final/io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.transport@4.1.109.Final/io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.transport@4.1.109.Final/io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.transport@4.1.109.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689)
	at io.netty.transport@4.1.109.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652)
	at io.netty.transport@4.1.109.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.common@4.1.109.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.common@4.1.109.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by alex-spies** [comment]
I think this is the same as https://github.com/elastic/elasticsearch/issues/111701.

Set risk to `blocker` since this affects release builds.

**Comment by nik9000** [comment]
:+1:
