### ISSUE TITLE
ESQL: Null point error finding errors....

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#111894]
### Description

I'm working with someone who's using CCR to restore a ton of clusters locally and they are getting errors like this from ESQL:
```
    "type": "exception",
    "reason": null,
    "stack_trace": """org.elasticsearch.ElasticsearchException
	at org.elasticsearch.compute.operator.FailureCollector.unwrapAndCollect(FailureCollector.java:51)
	at org.elasticsearch.xpack.esql.plugin.ComputeListener.lambda$acquireAvoid$2(ComputeListener.java:61)
	at 
```

It's so confused it can't even tell us why.

**Comment by dnhatn** [comment]
I opened https://github.com/elastic/elasticsearch/pull/111983
