### ISSUE TITLE
MixedClusterEsqlSpecIT » test {comparison.RangeVersion SYNC}

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#111814]
### CI Link

https://gradle-enterprise.elastic.co/s/amjnirhn22oq6

### Repro line

```
./gradlew ":x-pack:plugin:esql:qa:server:mixed-cluster:v8.13.4#javaRestTest" -Dtests.class="org.elasticsearch.xpack.esql.qa.mixed.MixedClusterEsqlSpecIT" -Dtests.method="test {comparison.RangeVersion SYNC}" -Dtests.seed=55002380A10412CC -Dtests.bwc=true -Dtests.locale=ar-MA -Dtests.timezone=Brazil/East -Druntime.java=22
```

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

```
    line 2:9: first argument of [version > "2"] is [version] so second argument must also be [version] but was [keyword]
    line 2:27: first argument of [version < "4"] is [version] so second argument must also be [version] but was [keyword]üDäorg.elasticsearch.xpack.esql.VerificationException: Found 2 problems
    line 2:9: first argument of [version > "2"] is [version] so second argument must also be [version] but was [keyword]
    line 2:27: first argument of [version < "4"] is [version] so second argument must also be [version] but was [keyword]
        at org.elasticsearch.xpack.esql.analysis.Analyzer.verify(Analyzer.java:124)
        at org.elasticsearch.xpack.esql.analysis.Analyzer.analyze(Analyzer.java:118)
        at org.elasticsearch.xpack.esql.session.EsqlSession.lambda$analyzedPlan$2(EsqlSession.java:149)
        at org.elasticsearch.xpack.esql.session.EsqlSession.lambda$preAnalyze$8(EsqlSession.java:188)
        at org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:245)
        at org.elasticsearch.xpack.ql.index.IndexResolver.lambda$resolveAsMergedMapping$8(IndexResolver.java:420)
        at org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:245)
        at org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:314)
        at org.elasticsearch.server@8.13.4/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:202)
        at org.elasticsearch.server@8.13.4/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:196)
        at org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:307)
        at org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:314)
        at org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:276)
        at org.elasticsearch.server@8.13.4/org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.mergeIndexResponses(TransportFieldCapabilitiesAction.java:278)
        at org.elasticsearch.server@8.13.4/org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.lambda$doExecuteForked$6(TransportFieldCapabilitiesAction.java:207)
        at org.elasticsearch.base@8.13.4/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)
        at org.elasticsearch.base@8.13.4/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)
        at org.elasticsearch.server@8.13.4/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)
        at org.elasticsearch.base@8.13.4/org.elasticsearch.core.Releasables$4.close(Releasables.java:159)
        at org.elasticsearch.server@8.13.4/org.elasticsearch.common.util.concurrent.RunOnce.run(RunOnce.java:40)
        at org.elasticsearch.server@8.13.4/org.elasticsearch.action.fieldcaps.RequestDispatcher.innerExecute(RequestDispatcher.java:153)
        at org.elasticsearch.server@8.13.4/org.elasticsearch.action.fieldcaps.RequestDispatcher$1.doRun(RequestDispatcher.java:122)
        at org.elasticsearch.server@8.13.4/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.server@8.13.4/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
        at org.elasticsearch.server@8.13.4/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
        at org.elasticsearch.server@8.13.4/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
    üûstatus$
               û
        at __randomizedtesting.SeedInfo.seed([55002380A10412CC:DD541C5A0FF87F34]:0)
        at org.elasticsearch.xpack.esql.qa.mixed.MixedClusterEsqlSpecIT.comparison.RangeVersion(comparison.csv-spec:194)
```

It seems like a recent version bump might have broken these ESQL tests.

**Comment by alex-spies** [comment]
@fang-xing-esql I think we need to put [this test](https://github.com/elastic/elasticsearch/pull/111437/files#diff-9b77bee1c446b51ae5c3a6f459b02f1557cb0740374da74e42e2ce07e0e94303R183-R194) behind a capability because implicit casting of versions was not a thing on 8.13. I'm not sure when it was introduced, but that's where we need the capability from, or conversely a skip for any version that's too old.

Would you like to take this?

**Comment by fang-xing-esql** [comment]
> @fang-xing-esql I think we need to put [this test](https://github.com/elastic/elasticsearch/pull/111437/files#diff-9b77bee1c446b51ae5c3a6f459b02f1557cb0740374da74e42e2ce07e0e94303R183-R194) behind a capability because implicit casting of versions was not a thing on 8.13. I'm not sure when it was introduced, but that's where we need the capability from, or conversely a skip for any version that's too old.
> 
> Would you like to take this?

Just saw it, it is related to implicit casting indeed, I'll add EsqlCapabilities for this test.
