### ISSUE TITLE
ESQL: InternalServerError when a shard is missing

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#111895]
### Description

I'm working with someone right now who's using cross cluster replication to restore a *ton* of indices into their cluster and ESQL is blowing up with `InternalServerError`s. But running them with error_trace gets:
```
{
  "error": {
    "root_cause": [
      {
        "type": "shard_not_found_exception",
        "reason": "no shard copies found [.ds-logs-elastic_agent-default-2023.04.24-000089][0]",
        "index_uuid": "nmk_yxOtSCW6oWnZptuxPg",
        "shard": "0",
        "index": ".ds-logs-elastic_agent-default-2023.04.24-000089",
        "stack_trace": """[.ds-logs-elastic_agent-default-2023.04.24-000089/nmk_yxOtSCW6oWnZptuxPg][[.ds-logs-elastic_agent-default-2023.04.24-000089][0]] org.elasticsearch.index.shard.ShardNotFoundException: no shard copies found [.ds-logs-elastic_agent-default-2023.04.24-000089][0]
at org.elasticsearch.xpack.esql.plugin.ComputeService.lambda$lookupDataNodes$22(ComputeService.java:538)
at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:89)
at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)
at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:48)
```

I'm not entirely sure what's up because I'm looking over their shoulder, but we should at least give a good error message without `error_trace` on.

**Comment by dnhatn** [comment]
Yes, this is because we set `allowPartialSearchResults=false` in the SearchShardsRequest. I've unassigned myself from the issue since this is not a bug; we require the execution info before we can return the partial result.
