### ISSUE TITLE
Node restart causes ClusterBlockException when Transport Client is used

### ISSUE THREAD

**Issue by bigwheel** [elastic/elasticsearch#11202]
## Abstract
Transport Client can work correctly when shutdown a connecting node, however when the node starts ClusterBlockException raised.

## Environment

* cluster
  * version: 1.4.4
  * 3 nodes(phyical server)
  * Index
    * big index data(20gb, i couldnt reproduce this issue with no index data)
    * number_of_replicas: 1
    * number_of_shards: 9

* application
  * version: 1.4.4
  * Java using Transport Client
  * specify all IPs of 3 nodes

## Reproduce process

1. query through Transport Client continuosly, repeatedly(any query is ok. ex: search, get, index...)
2. shutdown a node (shutdown API or initd script)
  * In this phase sometime searching method returns a result that contains failed shards. But this is NOT fatail. I retry search and can get collect result.
3. start the node
4. Transport Client sometime causes following Exception. We cannot catch it bacause it happens in Elasticsearch Client Thread pool maybe.
```
[error] (run-main-0) org.elasticsearch.transport.RemoteTransportException: [es-node01][inet[/192.168.10.42:9300]][indices:data/read/search]
org.elasticsearch.transport.RemoteTransportException: [es-node01][inet[/192.168.10.42:9300]][indices:data/read/search]
Caused by: org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
        at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:151)
        at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedRaiseException(ClusterBlocks.java:141)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.<init>(TransportSearchTypeAction.java:111)
        at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction.<init>(TransportSearchQueryThenFetchAction.java:70)
        at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction.<init>(TransportSearchQueryThenFetchAction.java:64)
        at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction.doExecute(TransportSearchQueryThenFetchAction.java:61)
        at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction.doExecute(TransportSearchQueryThenFetchAction.java:51)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:100)
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:43)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75)
        at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:63)
        at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:51)
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:217)
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:111)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

## IMO
https://groups.google.com/d/msg/elasticsearch/qBw6mgCO_Nk/N77Oe9X2YdIJ is right.
Transport Client accesses starting client before it connects cluster.
But, I cannot find any settings to solve this.
I tried [Sniff Setting](https://www.elastic.co/guide/en/elasticsearch/client/java-api/1.x/client.html#transport-client) but the exception is still caused.

By deleting TransportAddress of restarting node, exception didn't happen finally.
However it needs application restart.
I want to do rolling update elasticsearch cluster without application server shutdown.

Could anyone help us?

## Other Info
* I couldnt reproduce this issue using Node Client
* We cannot use Node Client by production enviroinment restriction (at least now, im trying to solve this)
* Almost same issue: https://groups.google.com/forum/#!msg/elasticsearch/qBw6mgCO_Nk/BLuikJhaiBsJ

**Comment by gongweixin** [comment]
I also got this exception, you now have a solution for it ？
@bigwheel

**Comment by bigwheel** [comment]
@gongweixin 
After I wrote this issue, we found a mistake in this issue report.
> Transport Client sometime causes following Exception. We cannot catch it bacause it happens in Elasticsearch Client Thread pool maybe.
This is not correct, we can catch exceptions such as following code.
```java
try {
client.prepareSearch().execute().actionGet();
} catch (RemoteTransportException e) {
 ...
}
```
We decided to retry query simply when exception happened.

P.S.
This mistake happens by inappropriate exception handling.
In fact, catching this exception is not so difficult.

**Comment by clintongormley** [comment]
@bigwheel thanks for letting us know.  Can this issue be closed?

**Comment by hiranfdo** [comment]
configured the net.ipv4.tcp_keepalive_time for a suitable value in the ES cluster nodes.
eg: add the line  net.ipv4.tcp_keepalive_time=300  to the   /etc/sysctl.conf for all the ES nodes and reboot it

**Comment by hiranfdo** [comment]
can solve the issue 
ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/2/no master];]\",\"status\":503}
solution:
set the tcp_keepalive_time to a suitable value ( default 7200 seconds) . example change the value to 
tcp_keepalive_time=300

add this tcp_keepalive_time=300 end of the file /etc/sysctl.conf  ( permanent fix)  
of all the ES nodes and reboot the ES nodes.
