### ISSUE TITLE
[ML] NPE in MlAssignmentNotifier

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#112136]
### Elasticsearch Version

8.13

### Java Version

_bundled_

### OS Version

any

### Problem Description

An NullPointerException with this stack trace has been reported

```
[instance-0000000021] uncaught exception in thread [elasticsearch[instance-0000000021][generic][T#30254]] java.lang.NullPointerException: Cannot invoke "org.elasticsearch.xpack.core.ml.utils.MlTaskState.isFailed()" because the return value of "org.elasticsearch.persistent.PersistentTasksCustomMetadata$PersistentTask.getState()" is null at org.elasticsearch.xpack.ml.MlAssignmentNotifier.findLongTimeUnassignedTasks(MlAssignmentNotifier.java:303) ~[?:?] at org.elasticsearch.xpack.ml.MlAssignmentNotifier.logLongTimeUnassigned(MlAssignmentNotifier.java:270) ~[?:?] at org.elasticsearch.xpack.ml.MlAssignmentNotifier.lambda$clusterChanged$0(MlAssignmentNotifier.java:94) ~[?:?] at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:917) ~[elasticsearch-8.13.2.jar:?] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Steps to Reproduce

Unknown

**Comment by jan-elastic** [comment]
This was fixed in 8.14 by https://github.com/elastic/elasticsearch/pull/107312
