### ISSUE TITLE
ESQL: Full task queue leads to 500 errors instead of 429

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#112106]
Sometimes, the compute engine's tasks get rejected by the thread pool executor because its queue is full. These rejections get bubbled up as internal server errors (500), but they should be 429 as we receive more esql requests than can currently be handled.

The failures happens at `ExchangeSourceImpl.checkFailure(ExchangeSourceHandler.java:56)`

Example stack traces (note the queue capacity and queued tasks in the `EsRejectedExecutionException`):

<details open>
  <summary>Failure with the ExchangeSourceHandler</summary>

```
org.elasticsearch.ElasticsearchException: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=org.elasticsearch.compute.operator.exchange.ExchangeSourceHandler$1@3bcd2d6e, creationTimeNanos=74787393969789, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = es-es-search-7bd65598d6-pkjh7/search, queue capacity = 1000, task execution EWMA = 333.3ms, total task execution time = 8d, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@6671ec3b[Running, pool size = 43, active threads = 43, queued tasks = 1000, completed tasks = 2316007]]
	at org.elasticsearch.server@8.16.0/org.elasticsearch.ExceptionsHelper.convertToElastic(ExceptionsHelper.java:55)
	at org.elasticsearch.compute.operator.exchange.ExchangeSourceHandler$ExchangeSourceImpl.checkFailure(ExchangeSourceHandler.java:56)
	at org.elasticsearch.compute.operator.exchange.ExchangeSourceHandler$ExchangeSourceImpl.isFinished(ExchangeSourceHandler.java:68)
	at org.elasticsearch.compute.operator.exchange.ExchangeSourceOperator.isFinished(ExchangeSourceOperator.java:64)
	at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:246)
	at org.elasticsearch.compute.operator.Driver.run(Driver.java:178)
	at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:364)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:991)
	at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
	Suppressed: org.elasticsearch.ElasticsearchException: 1 further exceptions were dropped
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:125)
		at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)
		at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:151)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:146)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onResponse(ActionListenerImplementations.java:183)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:96)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:335)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:48)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleResponse(TransportService.java:1775)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1498)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.InboundHandler.doHandleResponse(InboundHandler.java:432)
		at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.InboundHandler$2.doRun(InboundHandler.java:389)
		... 7 more
```

</details>

InboundHandler:
```
org.elasticsearch.ElasticsearchException: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=org.elasticsearch.transport.InboundHandler$1@6840ea11, creationTimeNanos=1576951554213, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = es-es-search-6cdc4ccfd5-nhw8r/search, queue capacity = 1000, task execution EWMA = 189.5ms, total task execution time = 18.3h, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@6671ec3b[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 405290]] at org.elasticsearch.server@8.16.0/org.elasticsearch.ExceptionsHelper.convertToElastic(ExceptionsHelper.java:55) at org.elasticsearch.compute.operator.exchange.ExchangeSourceHandler$ExchangeSourceImpl.checkFailure(ExchangeSourceHandler.java:56) at org.elasticsearch.compute.operator.exchange.ExchangeSourceHandler$ExchangeSourceImpl.isFinished(ExchangeSourceHandler.java:68) at org.elasticsearch.compute.operator.exchange.ExchangeSourceOperator.isFinished(ExchangeSourceOperator.java:64) at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:246) at org.elasticsearch.compute.operator.Driver.run(Driver.java:178) at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:364) at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:991) at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) at java.base/java.lang.Thread.run(Thread.java:1570) Caused by: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=org.elasticsearch.transport.InboundHandler$1@6840ea11, creationTimeNanos=1576951554213, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = es-es-search-6cdc4ccfd5-nhw8r/search, queue capacity = 1000, task execution EWMA = 189.5ms, total task execution time = 18.3h, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@6671ec3b[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 405290]]
```

ExchangeRequest:
```
org.elasticsearch.ElasticsearchException: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=processing of [10328][internal:data/read/esql/exchange]: org.elasticsearch.compute.operator.exchange.ExchangeRequest/BNGH40RcSuO-ZExCVtIU5A:2709, creationTimeNanos=246015711951, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = es-es-search-6cdc4ccfd5-8rwm8/search, queue capacity = 1000, task execution EWMA = 31.6ms, total task execution time = 1.1h, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@6671ec3b[Running, pool size = 49, active threads = 49, queued tasks = 1007, completed tasks = 3307]] at org.elasticsearch.server@8.16.0/org.elasticsearch.ExceptionsHelper.convertToElastic(ExceptionsHelper.java:55) at org.elasticsearch.compute.operator.exchange.ExchangeSourceHandler$ExchangeSourceImpl.checkFailure(ExchangeSourceHandler.java:56) at org.elasticsearch.compute.operator.exchange.ExchangeSourceHandler$ExchangeSourceImpl.isFinished(ExchangeSourceHandler.java:68) at org.elasticsearch.compute.operator.exchange.ExchangeSourceOperator.isFinished(ExchangeSourceOperator.java:64) at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:246) at org.elasticsearch.compute.operator.Driver.run(Driver.java:178) at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:364) at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:991) at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) at java.base/java.lang.Thread.run(Thread.java:1570) Suppressed: org.elasticsearch.ElasticsearchException: 1 further exceptions were dropped at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:125) at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118) at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:151) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:146) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onResponse(ActionListenerImplementations.java:183) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:121) at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118) at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:151) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:146) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:386) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:306) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.setResult(SubscribableListener.java:351) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.onResponse(SubscribableListener.java:249) at org.elasticsearch.compute.operator.exchange.ExchangeSourceHandler$PendingInstances.finishInstance(ExchangeSourceHandler.java:266) at org.elasticsearch.compute.operator.exchange.ExchangeSourceHandler$RemoteSinkFetcher.onSinkComplete(ExchangeSourceHandler.java:208) at org.elasticsearch.compute.operator.exchange.ExchangeSourceHandler$RemoteSinkFetcher.onSinkFailed(ExchangeSourceHandler.java:202) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:264) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onFailure(ActionListenerImplementations.java:306) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:53) at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1784) at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1508) at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1508) at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.InboundHandler.doHandleException(InboundHandler.java:474) at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.InboundHandler$3.doRun(InboundHandler.java:466) ... 7 more Suppressed: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=processing of [10540][indices:data/read/esql/compute]: org.elasticsearch.compute.operator.DriverTaskRunner$DriverRequest/BNGH40RcSuO-ZExCVtIU5A:6822, creationTimeNanos=246049460417, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = es-es-search-6cdc4ccfd5-8rwm8/search, queue capacity = 1000, task execution EWMA = 120.5ms, total task execution time = 1.1h, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@6671ec3b[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 3375]] Suppressed: org.elasticsearch.ElasticsearchException: 1 further exceptions were dropped at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:125) at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118) at org.elasticsearch.base@8.16.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.RefCountingListener$1.onFailure(RefCountingListener.java:158) at org.elasticsearch.xpack.esql.plugin.ComputeListener.lambda$acquireAvoid$2(ComputeListener.java:68) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.acceptException(ActionListenerImplementations.java:187) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onFailure(ActionListenerImplementations.java:192) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31) at org.elasticsearch.xpack.esql.plugin.ComputeService$DataNodeRequestExecutor$1.onFailure(ComputeService.java:626) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onFailure(ActionListenerImplementations.java:345) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:74) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onFailure(ActionListenerImplementations.java:306) at org.elasticsearch.compute.operator.DriverRunner$1.done(DriverRunner.java:63) at org.elasticsearch.compute.operator.DriverRunner$1.onFailure(DriverRunner.java:54) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener$FailureResult.complete(SubscribableListener.java:398) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:310) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.setResult(SubscribableListener.java:335) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.SubscribableListener.onFailure(SubscribableListener.java:254) at org.elasticsearch.compute.operator.Driver.abort(Driver.java:227) at org.elasticsearch.compute.operator.DriverTaskRunner$1.lambda$start$0(DriverTaskRunner.java:60) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:63) at org.elasticsearch.server@8.16.0/org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:264) at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportResponseHandler$1.handleException(TransportResponseHandler.java:63) at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1784) at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1508) at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1642) at org.elasticsearch.server@8.16.0/org.elasticsearch.transport.TransportService$DirectResponseChannel$2.doRun(TransportService.java:1622) at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:991) at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) at java.base/java.lang.Thread.run(Thread.java:1570) Suppressed: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=processing of [10357][indices:data/read/esql/compute]: org.elasticsearch.compute.operator.DriverTaskRunner$DriverRequest/BNGH40RcSuO-ZExCVtIU5A:6822, creationTimeNanos=246021178764, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = es-es-search-6cdc4ccfd5-8rwm8/search, queue capacity = 1000, task execution EWMA = 18.3ms, total task execution time = 1.1h, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@6671ec3b[Running, pool size = 49, active threads = 49, queued tasks = 1008, completed tasks = 3313]] Suppressed: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=processing of [10356][indices:data/read/esql/compute]: org.elasticsearch.compute.operator.DriverTaskRunner$DriverRequest/BNGH40RcSuO-ZExCVtIU5A:6822, creationTimeNanos=246020998191, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = es-es-search-6cdc4ccfd5-8rwm8/search, queue capacity = 1000, task execution EWMA = 18.3ms, total task execution time = 1.1h, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@6671ec3b[Running, pool size = 49, active threads = 49, queued tasks = 1008, completed tasks = 3313]] Suppressed: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=processing of [10422][indices:data/read/esql/compute]: org.elasticsearch.compute.operator.DriverTaskRunner$DriverRequest/BNGH40RcSuO-ZExCVtIU5A:6822, creationTimeNanos=246040326359, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = es-es-search-6cdc4ccfd5-8rwm8/search, queue capacity = 1000, task execution EWMA = 64.6ms, total task execution time = 1.1h, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@6671ec3b[Running, pool size = 49, active threads = 49, queued tasks = 999, completed tasks = 3369]] Suppressed: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=processing of [10457][indices:data/read/esql/compute]: org.elasticsearch.compute.operator.DriverTaskRunner$DriverRequest/BNGH40RcSuO-ZExCVtIU5A:6822, creationTimeNanos=246043019461, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = es-es-search-6cdc4ccfd5-8rwm8/search, queue capacity = 1000, task execution EWMA = 58.4ms, total task execution time = 1.1h, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@6671ec3b[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 3370]] Suppressed: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=processing of [10469][indices:data/read/esql/compute]: org.elasticsearch.compute.operator.DriverTaskRunner$DriverRequest/BNGH40RcSuO-ZExCVtIU5A:6822, creationTimeNanos=246043404016, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = es-es-search-6cdc4ccfd5-8rwm8/search, queue capacity = 1000, task execution EWMA = 58.4ms, total task execution time = 1.1h, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@6671ec3b[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 3370]] Suppressed: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=processing of [10456][indices:data/read/esql/compute]: org.elasticsearch.compute.operator.DriverTaskRunner$DriverRequest/BNGH40RcSuO-ZExCVtIU5A:6822, creationTimeNanos=246042948174, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = es-es-search-6cdc4ccfd5-8rwm8/search, queue capacity = 1000, task execution EWMA = 58.4ms, total task execution time = 1.1h, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@6671ec3b[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 3370]] Suppressed: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=processing of [10454][indices:data/read/esql/compute]: org.elasticsearch.compute.operator.DriverTaskRunner$DriverRequest/BNGH40RcSuO-ZExCVtIU5A:6822, creationTimeNanos=246042807470, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = es-es-search-6cdc4ccfd5-8rwm8/search, queue capacity = 1000, task execution EWMA = 64.6ms, total task execution time = 1.1h, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@6671ec3b[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 3369]] Suppressed: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=processing of [10487][indices:data/read/esql/compute]: org.elasticsearch.compute.operator.DriverTaskRunner$DriverRequest/BNGH40RcSuO-ZExCVtIU5A:6822, creationTimeNanos=246043747291, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = es-es-search-6cdc4ccfd5-8rwm8/search, queue capacity = 1000, task execution EWMA = 58.4ms, total task execution time = 1.1h, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@6671ec3b[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 3370]] Suppressed: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=processing of [10464][indices:data/read/esql/compute]: org.elasticsearch.compute.operator.DriverTaskRunner$DriverRequest/BNGH40RcSuO-ZExCVtIU5A:6822, creationTimeNanos=246043290776, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = es-es-search-6cdc4ccfd5-8rwm8/search, queue capacity = 1000, task execution EWMA = 58.4ms, total task execution time = 1.1h, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@6671ec3b[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 3370]] Suppressed: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=processing of [10497][indices:data/read/esql/compute]: org.elasticsearch.compute.operator.DriverTaskRunner$DriverRequest/BNGH40RcSuO-ZExCVtIU5A:6822, creationTimeNanos=246044166883, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = es-es-search-6cdc4ccfd5-8rwm8/search, queue capacity = 1000, task execution EWMA = 58.4ms, total task execution time = 1.1h, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@6671ec3b[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 3370]] Caused by: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=processing of [10328][internal:data/read/esql/exchange]: org.elasticsearch.compute.operator.exchange.ExchangeRequest/BNGH40RcSuO-ZExCVtIU5A:2709, creationTimeNanos=246015711951, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = es-es-search-6cdc4ccfd5-8rwm8/search, queue capacity = 1000, task execution EWMA = 31.6ms, total task execution time = 1.1h, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@6671ec3b[Running, pool size = 49, active threads = 49, queued tasks = 1007, completed tasks = 3307]] Suppressed: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=processing of [10326][internal:data/read/esql/exchange]: org.elasticsearch.compute.operator.exchange.ExchangeRequest/BNGH40RcSuO-ZExCVtIU5A:2709, creationTimeNanos=246015543473, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = es-es-search-6cdc4ccfd5-8rwm8/search, queue capacity = 1000, task execution EWMA = 35.1ms, total task execution time = 1.1h, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@6671ec3b[Running, pool size = 49, active threads = 49, queued tasks = 1007, completed tasks = 3306]] Suppressed: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of TimedRunnable{original=processing of [10331][internal:data/read/esql/exchange]: org.elasticsearch.compute.operator.exchange.ExchangeRequest/BNGH40RcSuO-ZExCVtIU5A:2709, creationTimeNanos=246015808831, startTimeNanos=0, finishTimeNanos=-1, failedOrRejected=false} on TaskExecutionTimeTrackingEsThreadPoolExecutor[name = es-es-search-6cdc4ccfd5-8rwm8/search, queue capacity = 1000, task execution EWMA = 28.5ms, total task execution time = 1.1h, org.elasticsearch.common.util.concurrent.TaskExecutionTimeTrackingEsThreadPoolExecutor@6671ec3b[Running, pool size = 49, active threads = 49, queued tasks = 1007, completed tasks = 3308]]
```

**Comment by dnhatn** [comment]
I've opened https://github.com/elastic/elasticsearch/pull/112178.
