### ISSUE TITLE
ThreadContextTests.testDropWarningsExceedingMaxSettings

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#112256]
### CI Link

https://gradle-enterprise.elastic.co/s/osvjrrcle2zhe

### Repro line

./gradlew ":server:test" --tests "org.elasticsearch.common.util.concurrent.ThreadContextTests.testDropWarningsExceedingMaxSettings" -Dtests.seed=61206B0BE9059C89 -Dtests.locale=ar-EG -Dtests.timezone=UCT -Druntime.java=17

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

This seems to fail for me with the following:

```
ThreadContextTests > testDropWarningsExceedingMaxSettings FAILED
    java.lang.AssertionError: expected to see warnings too long but did not
    Expected: <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([61206B0BE9059C89:D64D8FE3524FAA8C]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.elasticsearch.test.MockLog$SeenEventExpectation.assertMatched(MockLog.java:176)
        at org.elasticsearch.test.MockLog$WrappedLoggingExpectation.assertMatched(MockLog.java:280)
        at org.elasticsearch.test.MockLog.assertAllExpectationsMatched(MockLog.java:110)
        at org.elasticsearch.common.util.concurrent.ThreadContextTests.testDropWarningsExceedingMaxSettings(ThreadContextTests.java:682)
```

**Comment by dakrone** [comment]
Muting this in https://github.com/elastic/elasticsearch/pull/112316 because it is repeatedly failing

**Comment by dakrone** [comment]
Duplicate of https://github.com/elastic/elasticsearch/issues/111707
