### ISSUE TITLE
Randomized Testing NPE in Seed

### ISSUE THREAD

**Issue by sawyercade** [elastic/elasticsearch#11239]
I'm attempting to test a customer ShardsAllocator plugin and am running into the following error when attempting to create an index:

    java.lang.NullPointerException
	at __randomizedtesting.SeedInfo.seed([BE85E9425BC7431B:F5AE237DAA0F1150]:0)
	at org.elasticsearch.cluster.routing.allocation.decider.ThrottlingAllocationDecider.canAllocate(ThrottlingAllocationDecider.java:109)
	at org.elasticsearch.cluster.routing.allocation.decider.AllocationDeciders.canAllocate(AllocationDeciders.java:146)
	at org.elasticsearch.cluster.routing.allocation.allocator.SizeShardsAllocator$SizeBalancer.allocateUnassigned(SizeShardsAllocator.java:135)
	at org.elasticsearch.cluster.routing.allocation.allocator.SizeShardsAllocator$SizeBalancer.balance(SizeShardsAllocator.java:107)
	at org.elasticsearch.cluster.routing.allocation.allocator.SizeShardsAllocator.allocateUnassigned(SizeShardsAllocator.java:67)
	at org.elasticsearch.cluster.routing.allocation.allocator.ShardsAllocators.allocateUnassigned(ShardsAllocators.java:74)
	at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:217)
	at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:160)
	at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:146)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:453)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:383)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

This issue appears to be a recurrence of https://github.com/elastic/elasticsearch/issues/7409 . I'm running Mac OS X 10.10.2 and Java 1.8.0_31. My elasticsearch repo is current up through commit 33fd25083e520e40cc9181a0d690e637b6eb04f4.

Here's a bit of the integration test I'm attempting to run: 

    @ElasticsearchIntegrationTest.ClusterScope(scope = ElasticsearchIntegrationTest.Scope.SUITE)
    public class SizeAllocatorTests extends ElasticsearchIntegrationTest {

    @Before
    public void setup() throws IOException {
        createIndex("test"); // exception happens after this call
        ensureGreen("test");

        refresh();
    }

    @Override
    protected Settings nodeSettings(int nodeOrdinal) {
        return settingsBuilder()
                .put(super.nodeSettings(nodeOrdinal))
                .put(ShardsAllocatorModule.TYPE_KEY, "org.elasticsearch.cluster.routing.allocation.allocator.SizeShardsAllocator")
                .build();
    }

**Comment by sawyercade** [comment]
Closing, issue is in the custom ShardsAllocator, not production ES.
