### ISSUE TITLE
[CI] SharedBlobCacheServiceTests.testGetMultiThreaded failure

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#112305]
### CI Link

https://gradle-enterprise.elastic.co/s/ieetjzos2svao

### Repro line

./gradlew ":x-pack:plugin:blob-cache:test" --tests "org.elasticsearch.blobcache.shared.SharedBlobCacheServiceTests.testGetMultiThreaded" -Dtests.seed=9176519ABB89E00D -Dtests.locale=fr-FR -Dtests.timezone=Asia/Pyongyang -Druntime.java=22

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

failed in PR build

### Failure excerpt

```
SharedBlobCacheServiceTests > testGetMultiThreaded FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([9176519ABB89E00D]:0)
        at org.junit.Assert.fail(Assert.java:87)aturesMetadata
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertNotNull(Assert.java:713)
        at org.junit.Assert.assertNotNull(Assert.java:723)
        at org.elasticsearch.blobcache.shared.SharedBlobCacheServiceTests.lambda$testGetMultiThreaded$16(SharedBlobCacheServiceTests.java:500)
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([9176519ABB89E00D]:0)
        at org.junit.Assert.fail(Assert.java:87)t org.elasticsearch...shared.SharedBlobCacheServiceTests
        at org.junit.Assert.assertTrue(Assert.java:42)elasticsearch.blobcache.common.SparseFileTrackerTests
        at org.junit.Assert.assertNotNull(Assert.java:713)
        at org.junit.Assert.assertNotNull(Assert.java:723)
        at org.elasticsearch.blobcache.shared.SharedBlobCacheServiceTests.lambda$testGetMultiThreaded$16(SharedBlobCacheServiceTests.java:500)
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([9176519ABB89E00D]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertNotNull(Assert.java:713)
        at org.junit.Assert.assertNotNull(Assert.java:723)
        at org.elasticsearch.blobcache.shared.SharedBlobCacheServiceTests.lambda$testGetMultiThreaded$16(SharedBlobCacheServiceTests.java:500)
```

**Comment by dakrone** [comment]
This seems to have around a ~10-20% failure rate on my machine, so I'm going to open a PR to mute it for now.

**Comment by dakrone** [comment]
Duplicate of https://github.com/elastic/elasticsearch/issues/112314
