### ISSUE TITLE
Corrupted shard

### ISSUE THREAD

**Issue by Hocdoc** [elastic/elasticsearch#11249]
After restarting Elasticsearch 1.5.2 (just a `sudo service elasticsearch restart`) on my single node server with about 600GB data one shard cannot get recovered and the cluster stays in the red status. I haven't noticed any problems before the restart. I'm using the indices without replicas.

I am using a GCE instance with persistent disks and there is enough free space for Elasticsearch there (>170GB). 

Error log:

    [2015-05-20 07:48:29,774][WARN ][indices.cluster          ] [test1] [[gardenhose-2015-week20][2]] marking and sending shard failed due to [failed recovery]
    org.elasticsearch.index.gateway.IndexShardGatewayRecoveryException: [gardenhose-2015-week20][2] failed recovery
            at org.elasticsearch.index.gateway.IndexShardGatewayService$1.run(IndexShardGatewayService.java:162)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)
    Caused by: org.elasticsearch.index.engine.EngineCreationFailureException: [gardenhose-2015-week20][2] failed to upgrade 3x segments
            at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:121)
            at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:32)
            at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1262)
            at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1257)
            at org.elasticsearch.index.shard.IndexShard.prepareForTranslogRecovery(IndexShard.java:784)
            at org.elasticsearch.index.gateway.local.LocalIndexShardGateway.recover(LocalIndexShardGateway.java:226)
            at org.elasticsearch.index.gateway.IndexShardGatewayService$1.run(IndexShardGatewayService.java:112)
            ... 3 more
    Caused by: java.io.EOFException: read past EOF: NIOFSIndexInput(path="/mnt/elasticsearch-test1/test/nodes/0/indices/gardenhose-2015-week20/2/index/segments_c9")
            at org.apache.lucene.store.BufferedIndexInput.refill(BufferedIndexInput.java:336)
            at org.apache.lucene.store.BufferedIndexInput.readByte(BufferedIndexInput.java:54)
            at org.apache.lucene.store.DataInput.readInt(DataInput.java:98)
            at org.apache.lucene.store.BufferedIndexInput.readInt(BufferedIndexInput.java:183)
            at org.elasticsearch.common.lucene.Lucene.indexNeeds3xUpgrading(Lucene.java:767)
            at org.elasticsearch.common.lucene.Lucene.upgradeLucene3xSegmentsMetadata(Lucene.java:778)
            at org.elasticsearch.index.engine.InternalEngine.upgrade3xSegments(InternalEngine.java:1084)
            at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:119)
            ... 9 more

**Comment by tlrx** [comment]
This looks similar to #10680

**Comment by Hocdoc** [comment]
Yes, shutdown of the cluster may have last 30s.
I have noticed there was a big query running before the restart which cause an OOM-Exception.

I have uploaded the full log file https://gist.githubusercontent.com/Hocdoc/0956a3675bd63e0af0d5/raw/elasticsearch.log . The (first) restart was at [2015-05-20 07:44:35,457].

**Comment by clintongormley** [comment]
Actually, it says `failed to upgrade 3x segments`.  Makes me think this was an old previously-corrupted index.

**Comment by mikemccand** [comment]
Hmm I think I see what's happening here ... Elasticsearch detects false corruption if the segments file is 0 bytes, and gives a confusing message about upgrading 3x segments.

Was `/mnt/elasticsearch-test1/test/nodes/0/indices/gardenhose-2015-week20/2/index/segments_c9` 0 bytes in this case?

I'll work on a fix.

**Comment by mikemccand** [comment]
This only affects 1.x; we don't do this check in 2.0 (master).

**Comment by mikemccand** [comment]
Fixed with better error reporting in #11539.
