### ISSUE TITLE
IntelliJ NativeLibraryProvider is missing for Java 21

### ISSUE THREAD

**Issue by ChrisHegarty** [elastic/elasticsearch#112804]
The following exception is often encountered with running tests with the IntelliJ test runner. Running tests with the Gradle runner is fine.
```
java.lang.LinkageError: NativeLibraryProvider is missing for Java 21

	at org.elasticsearch.nativeaccess.lib.NativeLibraryProvider.loadJdkImpl(NativeLibraryProvider.java:85)
	at org.elasticsearch.nativeaccess.lib.NativeLibraryProvider.loadProvider(NativeLibraryProvider.java:67)
	at org.elasticsearch.nativeaccess.lib.NativeLibraryProvider$Holder.<clinit>(NativeLibraryProvider.java:97)
	at org.elasticsearch.nativeaccess.lib.NativeLibraryProvider.instance(NativeLibraryProvider.java:43)
	at org.elasticsearch.nativeaccess.NativeAccessHolder.<clinit>(NativeAccessHolder.java:22)
	at org.elasticsearch.nativeaccess.NativeAccess.instance(NativeAccess.java:24)
	at org.elasticsearch.bootstrap.Elasticsearch.initializeNatives(Elasticsearch.java:282)
	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:91)
	at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:329)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:631)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.nativeaccess.jdk.JdkNativeLibraryProvider
```

**Comment by rjernst** [comment]
This is a limitation of IntelliJ.  Since the jdk21 provider is loaded through an MRJAR, it won't work in intellij. Test must be run either with JDK 17, or with the gradle runner.

**Comment by mark-vieira** [comment]
So is this just that the additional sourcesets aren't on the runtime classpath when running in intellij? Could we hack this somehow?

**Comment by mark-vieira** [comment]
Or more simply, given that the new minimum runtime version is Java 21, couldn't we collapse the MR sources down into the `main` sourceset? For 9.0 the pre-21 implementations will never be used do why separate that in the MR jar. We should only use the MR jar for Java 22+ impls.

**Comment by rjernst** [comment]
> So is this just that the additional sourcesets aren't on the runtime classpath when running in intellij? Could we hack this somehow?

Unfortunately adding the additional sourcesets in a non MRJAR means there is jarhell. So we would have to relax our jarhell check, and then _also_ add special handling to know how to fallback to the jdk 17 impl when not running on jdk 21+. It would be complicated, and I don't think worth it (we discussed when first adding native access).

> given that the new minimum runtime version is Java 21, couldn't we collapse the MR sources down into the main sourceset

Yes, I plan to do this now that main is Java 21.

**Comment by ChrisHegarty** [comment]
Is there any way to configure Gradle (or the import into IntelliJ) so that tests depend upon the jar file of the native subproject, rather than the exploded classes? This would be much closer to actual runtime behaviour.

**Comment by breskeby** [comment]
for running those tests with gradle and the gradle runner in idea this
should be possible to configure

**Comment by nik9000** [comment]
How's this going? I feel like I keep bumping into this. Local testing harder, mostly because the intellij gradle runner is slower, doesn't like rerunning individual tests sometimes, and doesn't seem compatible with running all subclasses of a particular test.

**Comment by rjernst** [comment]
This issue was actually solved, by collapsing the sourcesets. But another was introduced as a byproduct of the change. We now have the issue that IntelliJ cannot build the native lib because we enable preview features, but also use the `--release NN` flag. I've pulled my hair out trying to figure out why and how IntelliJ is using `javac 22`, when my project jdk is 21, and our min jdk version is 21. I do not know where 22 comes in.

**Comment by ldematte** [comment]
FWIW, I had to manually set JAVA_HOME. `/usr/libexec/java_home -v 21` was giving me a JDK 22 location despite having a valid JDK 21 installed (the same way). Don't know if it's related?
