### ISSUE TITLE
Failed to configure logging...

### ISSUE THREAD

**Issue by igoreliasm** [elastic/elasticsearch#11283]
Hello, guys
They could help me this error?

```
/usr/share/elasticsearch# ./bin/elasticsearch
Failed to configure logging...
org.elasticsearch.ElasticsearchException: Failed to load logging configuration
	at org.elasticsearch.common.logging.log4j.LogConfigurator.resolveConfig(LogConfigurator.java:139)
	at org.elasticsearch.common.logging.log4j.LogConfigurator.configure(LogConfigurator.java:89)
	at org.elasticsearch.bootstrap.Bootstrap.setupLogging(Bootstrap.java:100)
	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:184)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
Caused by: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/config
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:97)
	at java.nio.file.Files.readAttributes(Files.java:1686)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:109)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69)
	at java.nio.file.Files.walkFileTree(Files.java:2602)
	at org.elasticsearch.common.logging.log4j.LogConfigurator.resolveConfig(LogConfigurator.java:123)
	... 4 more
log4j:WARN No appenders could be found for logger (node).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```
```
cat /etc/centos-release 
CentOS release 6.5 (Final)
```
x86_64

Please;

**Comment by clintongormley** [comment]
Hi @igoreliasm 

Questions like these are best asked in the forum https://discuss.elastic.co/ but I'm guessing that you installed Elasticsearch as an RPM, in which case your config files are elsewhere.  Try starting Elasticsearch using the init scripts, rather than directly on the command line

**Comment by mikesparr** [comment]
@clintongormley I'll jump into forum but ran into same issue. Trying to figure how to run ES from command line so I can control it with Supervisord.
