### ISSUE TITLE
RankDocsQueryBuilderTests testRankDocsQueryEarlyTerminate fails in lucene_snapshot branch

### ISSUE THREAD

**Issue by pmpailis** [elastic/elasticsearch#114097]
### CI Link

https://gradle-enterprise.elastic.co/s/vhr5553t3xca4

### Repro line

 ./gradlew ":server:test" --tests "org.elasticsearch.search.retriever.rankdoc.RankDocsQueryBuilderTests.testRankDocsQueryEarlyTerminate" -Dtests.seed=DD785775C8E7BEC7 -Dtests.locale=luo -Dtests.timezone=America/Halifax -Druntime.java=22	

### Does it reproduce?

No

### Applicable branches

lucene_snapshot

### Failure excerpt

```
RankDocsQueryBuilderTests > testRankDocsQueryEarlyTerminate FAILED	
    java.lang.AssertionError: 	
    Expected: a value less than or equal to <15L>	
         but: <42L> was greater than <15L>	
        at __randomizedtesting.SeedInfo.seed([DD785775C8E7BEC7:B6DF60B51DB9733A]:0)	
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)	
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)	
        at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2536)	
        at org.elasticsearch.search.retriever.rankdoc.RankDocsQueryBuilderTests.testRankDocsQueryEarlyTerminate(RankDocsQueryBuilderTests.java:162)	
```

**Comment by pmpailis** [comment]
Fix has been submitted in #114725  and test is no longer muted. Closing this one. Thanks @jimczi !
