### ISSUE TITLE
[CI] ScheduledEventTests testBuild_SucceedsWithProvidedSkipResultAndSkipModelUpdatesValues fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#114893]
### CI Link

https://gradle-enterprise.elastic.co/s/f7xodendhcxqi/tests/task/:x-pack:plugin:core:test/details/org.elasticsearch.xpack.core.ml.calendars.ScheduledEventTests/testBuild_SucceedsWithProvidedSkipResultAndSkipModelUpdatesValues?top-execution=1

### Repro line

./gradlew ":x-pack:plugin:core:test" --tests "org.elasticsearch.xpack.core.ml.calendars.ScheduledEventTests.testBuild_SucceedsWithProvidedSkipResultAndSkipModelUpdatesValues" -Dtests.seed=1736FEED7A9C76A6 -Dtests.locale=kkj -Dtests.timezone=Australia/Queensland -Druntime.java=22

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

```
2> org.elasticsearch.ElasticsearchStatusException: Event start time [2024-10-16T10:34:06.793Z] must come before end time [2024-10-16T10:34:06.793Z]
        at __randomizedtesting.SeedInfo.seed([1736FEED7A9C76A6:4084A1DB50F928E1]:0)
        at app//org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.badRequestException(ExceptionsHelper.java:93)
        at app//org.elasticsearch.xpack.core.ml.calendars.ScheduledEvent$Builder.build(ScheduledEvent.java:349)
        at app//org.elasticsearch.xpack.core.ml.calendars.ScheduledEventTests.validateScheduledEventSuccessfulBuild(ScheduledEventTests.java:220)
        at app//org.elasticsearch.xpack.core.ml.calendars.ScheduledEventTests.testBuild_SucceedsWithProvidedSkipResultAndSkipModelUpdatesValues(ScheduledEventTests.java:199)
```

**Comment by maxhniebergall** [comment]
https://github.com/elastic/elasticsearch/pull/116118

**Comment by davidkyle** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/116118
