### ISSUE TITLE
[1.3.7] shard fails to start IllegalArgumentException[No type mapped for [0]]

### ISSUE THREAD

**Issue by AVVS** [elastic/elasticsearch#11502]
i can say that my mappings suck for this index, since every random payload that gets indexed from headers (indexing parsed emails) are set dynamically to "index": "no" instead of being ignored and not added to the mappings, but, at the same time, this is not something that should make 1/3 of shards fail after a power outage in the data center, where I had 2 replicas of each shard. Can some1 shed some light into this error and whether you want to examine the mapping with all the weird headers that people set on their emails?

```java
[2015-06-04 12:53:08,633][WARN ][indices.cluster          ] [storage.01] [messages][9] failed to start shard
org.elasticsearch.index.gateway.IndexShardGatewayRecoveryException: [messages][9] failed to recover shard
	at org.elasticsearch.index.gateway.local.LocalIndexShardGateway.recover(LocalIndexShardGateway.java:269)
	at org.elasticsearch.index.gateway.IndexShardGatewayService$1.run(IndexShardGatewayService.java:132)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: No type mapped for [0]
	at org.elasticsearch.index.translog.Translog$Operation$Type.fromId(Translog.java:224)
	at org.elasticsearch.index.translog.TranslogStreams.readTranslogOperation(TranslogStreams.java:34)
	at org.elasticsearch.index.gateway.local.LocalIndexShardGateway.recover(LocalIndexShardGateway.java:241)
	... 4 more
[2015-06-04 12:53:08,654][WARN ][cluster.action.shard     ] [storage.01] [messages][9] sending failed shard for [messages][9], node[Rus251Q6T5Ko5LhObmMzrA], [P], s[INITIALIZING], indexUUID [WgO6d6KnRQ6eNgw5CK7_Rw], reason [Failed to start shard, message [IndexShardGatewayRecoveryException[[messages][9] failed to recover shard]; nested: IllegalArgumentException[No type mapped for [0]]; ]]
```

**Comment by dakrone** [comment]
@AVVS it looks like your translog is corrupted, if you move the translog file away from the shard's directory you should be able to recover the shard.

**Comment by clintongormley** [comment]
Just to add to this: we've done a lot of work recently to improve translog handling and to reduce the chances of corruption, eg #11011 and #11143.  Not only is corruption much less likely, but Elasticsearch is better able to detect and handle this situation if it occurs.

I don't think there is anything more to do on this ticket, so I'm going to close it.  Feel free to reopen if there is something that hasn't been covered.

**Comment by nariman-haghighi** [comment]
Just ran into this exact error on a migration from 1.5.2 -> 1.7.0. Deleted the translog file from the shard's directory and was able to recover.
