### ISSUE TITLE
Elasticsearch cannot access S3 repo using AWS web identity token due to an irrecoverable error

### ISSUE THREAD

**Issue by pxsalehi** [elastic/elasticsearch#115186]
There has been reports of ES (8.15) access to S3 repository not working a while after it is set up using an AWS web identity token file. Any attempt to access the repository seems to fail with:
```
Unable to load credentials from org.elasticsearch.repositories.s3.S3Service$CustomWebIdentityTokenCredentialsProvider

com.amazonaws.AmazonClientException: java.lang.IllegalStateException: Connection pool shut down
	at com.amazonaws.auth.RefreshableTask.refreshValue(RefreshableTask.java:303)
	at com.amazonaws.auth.RefreshableTask.blockingRefresh(RefreshableTask.java:251)
	at com.amazonaws.auth.RefreshableTask.getValue(RefreshableTask.java:192)
	at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider.getCredentials(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:130)
	at org.elasticsearch.repositories.s3.S3Service$CustomWebIdentityTokenCredentialsProvider.getCredentials(S3Service.java:449)
	at org.elasticsearch.repositories.s3.S3Service$ErrorLoggingCredentialsProvider.getCredentials(S3Service.java:479)
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:111)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at org.elasticsearch.repositories.s3.SocketAccess.doPrivileged(SocketAccess.java:31)
	at org.elasticsearch.repositories.s3.S3Service$PrivilegedAWSCredentialsProvider.getCredentials(S3Service.java:313)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1269)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:845)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:794)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1524)
	at org.elasticsearch.repositories.s3.S3RetryingInputStream.lambda$openStreamWithRetry$0(S3RetryingInputStream.java:100)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at org.elasticsearch.repositories.s3.SocketAccess.doPrivileged(SocketAccess.java:31)
	at org.elasticsearch.repositories.s3.S3RetryingInputStream.openStreamWithRetry(S3RetryingInputStream.java:100)
	at org.elasticsearch.repositories.s3.S3RetryingInputStream.<init>(S3RetryingInputStream.java:85)
	at org.elasticsearch.repositories.s3.S3RetryingInputStream.<init>(S3RetryingInputStream.java:67)
	at org.elasticsearch.repositories.s3.S3BlobContainer.readBlob(S3BlobContainer.java:104)
	at org.elasticsearch.server@8.15.2/org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.read(ChecksumBlobStoreFormat.java:123)
	at org.elasticsearch.server@8.15.2/org.elasticsearch.repositories.blobstore.BlobStoreRepository.lambda$getOneSnapshotInfo$26(BlobStoreRepository.java:1957)
	at org.elasticsearch.server@8.15.2/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:917)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.IllegalStateException: Connection pool shut down
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:269)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy27.requestConnection(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.doInvoke(AWSSecurityTokenServiceClient.java:1727)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1694)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1683)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.executeAssumeRoleWithWebIdentity(AWSSecurityTokenServiceClient.java:1042)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.assumeRoleWithWebIdentity(AWSSecurityTokenServiceClient.java:1010)
	at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider.newSession(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:149)
	at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider.access$000(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:40)
	at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider$1.call(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:65)
	at com.amazonaws.auth.STSAssumeRoleWithWebIdentitySessionCredentialsProvider$1.call(STSAssumeRoleWithWebIdentitySessionCredentialsProvider.java:62)
	at com.amazonaws.auth.RefreshableTask.refreshValue(RefreshableTask.java:295)
	... 34 more
```

This doesn't seem to happen consistently. When it happens it cannot be recovered unless the node is restarted.

**Comment by aviau** [comment]
It looks like this is a regression of issue https://github.com/elastic/elasticsearch/issues/101828 which was closed. There are multiple people getting the issue.

**Comment by ahmetdd** [comment]
Can I manually renew the AWS web identity token without restarting the pods. is this possible ?

**Comment by murtll** [comment]
I faced the same issue after upgrading Elasticsearch to 8.16 in Kubernetes.
In my case, the problem was the env `AWS_WEB_IDENTITY_TOKEN_FILE` was not set manually as specified in the [doc](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-snapshots.html#CO12-2) and was automatically set to `/var/run/secrets/eks.amazonaws.com/serviceaccount/token`.
It worked somehow until the expiration of the first issued token, but then there was no refreshing.
As another [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/repository-s3.html#iam-kubernetes-service-accounts) says

> a repository can’t read any files outside its config directory

So I thought there might be a problem and set the envs according to the first doc.
```yaml
          - name: AWS_WEB_IDENTITY_TOKEN_FILE
            value: "/usr/share/elasticsearch/config/repository-s3/aws-web-identity-token-file" 
          - name: AWS_ROLE_ARN
            value: "arn:aws:iam::YOUR_ROLE_ARN_HERE" 
```
After that it was resolved for me.

**Comment by ahmetdd** [comment]
@murtll I tried the change you specified, but the result didn't change. It starts to get an error after a while.I test verifying the repository from the kibana interface for a certain period of time and it's connect.(8 hours)
then I run the policy to take snap and it makes the snap to Aws S3. Some time after receiving snap, it can no longer verify the repository and cannot access S3. so it starts getting errors after the snap. I could not determine what changes after taking snap to S3.

**First verify**

`- Connected
{
  "nodes": {
    "xXTMsdfghvb3aMHvFw": {
      "name": "NODE1-es-default-1"
    },
    "msROT00234fdfdZcIBg0Q": {
      "name": "NODE2-es-default-0"
    },
    "qWuOhHUjfdsflsdfiMkcg": {
      "name": "NODE3-es-default-2"
    }
  }
}`

**After taking snap**

`{
  "error" : {
    "root_cause" : [
      {
        "type" : "repository_verification_exception",
        "reason" : "[snap_repository] path [test/test] is not accessible on master node"
      }
    ],
    "type" : "repository_verification_exception",
    "reason" : "[snap_repository] path [test/test] is not accessible on master node",
    "caused_by" : {
      "type" : "i_o_exception",
      "reason" : "Unable to upload object [test/testmaster.dat] using a single upload",
	  
	 }
}`

**Comment by DaveCTurner** [comment]
I suspect this is the same bug I was hitting when working on https://github.com/elastic/elasticsearch/pull/117628. I fixed it in that PR, so an upgrade to 8.18.0 (when it's released) should do the trick. Until then, I don't see a workaround other than restarting nodes, sorry.

**Comment by ahmetdd** [comment]
@DaveCTurner Is it possible that this change was made earlier than 8.18.0 ?

**Comment by DaveCTurner** [comment]
Good question @ahmetdd but I think the answer is no, https://github.com/elastic/elasticsearch/pull/119748 fixes a different (nearby) issue.
