### ISSUE TITLE
[CI] two_nodes_should_run_using_public_ip fails due to missing node

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#11533]
Stack trace:

```
java.lang.AssertionError: expected:<2> but was:<1>
    at __randomizedtesting.SeedInfo.seed([6E452F021F50AE3F:1E58450F06FBF158]:0)
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at org.elasticsearch.discovery.azure.AbstractAzureComputeServiceTest.checkNumberOfNodes(AbstractAzureComputeServiceTest.java:51)
    at org.elasticsearch.discovery.azure.AzureTwoStartedNodesTest.two_nodes_should_run_using_public_ip(AzureTwoStartedNodesTest.java:78)
```

repro line:

```
mvn test -Pdev -Dtests.seed=6E452F021F50AE3F -Dtests.class=org.elasticsearch.discovery.azure.AzureTwoStartedNodesTest -Dtests.slow=true -Dtests.method="two_nodes_should_run_using_public_ip" -Des.logger.level=DEBUG -Des.node.mode=network -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=it -Dtests.timezone=Asia/Kashgar
```

Build url: http://build-us-00.elastic.co/job/es_core_master_centos/5094/

**Comment by bleskes** [comment]
Another similar failure for two_nodes_should_run_using_private_ip : http://build-us-00.elastic.co/job/es_g1gc_master_metal/8693/testReport/junit/org.elasticsearch.discovery.azure/AzureTwoStartedNodesTest/two_nodes_should_run_using_private_ip/

**Comment by clintongormley** [comment]
Long time since we've seen this. Closing

**Comment by DaveCTurner** [comment]
The [offending tests](https://github.com/elastic/elasticsearch/blob/43a91f4184d8dfe45cf82b7a300f1d6baa438af0/plugins/discovery-azure-classic/src/test/java/org/elasticsearch/discovery/azure/classic/AzureTwoStartedNodesTests.java#L41) were marked `@AwaitsFix` in June 2015 so haven't been running for a while. Can they be reinstated?

**Comment by jasontedor** [comment]
Let's remove the awaits fix and see what happens? And close this issue and open a new one if we find out there are problems.

**Comment by bleskes** [comment]
+1

**Comment by tlrx** [comment]
This test has been refactored in #27945, closing.
