### ISSUE TITLE
codec mismatch: actual codec=state vs expected codec=segments

### ISSUE THREAD

**Issue by Kry1702** [elastic/elasticsearch#115614]
# Base info
Elasticsearch Version：7.17.14
Docker  Version：19.03
OS Version：CentOS  7.9  x86

# Fault phenomenon

```
ElasticsearchException[failed to bind service]; nested: CorruptIndexException[codec mismatch: actual codec=state vs expected codec=segments (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="/usr/share/elasticsearch/data/nodes/0/_state/segments_phj")))];
Likely root cause: org.apache.lucene.index.CorruptIndexException: codec mismatch: actual codec=state vs expected codec=segments (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="/usr/share/elasticsearch/data/nodes/0/_state/segments_phj")))
        at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:208)
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:309)
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:291)
        at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:64)
        at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:61)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:720)
        at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:84)
        at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:64)
        at org.elasticsearch.gateway.PersistedClusterStateService.nodeMetadata(PersistedClusterStateService.java:306)
        at org.elasticsearch.env.NodeEnvironment.loadNodeMetadata(NodeEnvironment.java:459)
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:356)
        at org.elasticsearch.node.Node.<init>(Node.java:429)
        at org.elasticsearch.node.Node.<init>(Node.java:309)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:169)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:160)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
        at org.elasticsearch.cli.Command.main(Command.java:77)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:125)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80)
For complete error details, refer to the log at /usr/share/elasticsearch/logs/docker-cluster.log
```

The OS file system uses XFS, the service runs based on the docker container,and mount the data to the disk, 5 disks based on the RIAD 5 combination.
Run the xfs_repair -L /dev/sdb1 command to repair the fault,mount the disk after the file system is restored.
Running the service reported the above error.

Are there any good solutions to these problems?  thank you！

**Comment by astefan** [comment]
Hey there @Kry1702,
From your description I understand that the disk had a failure, you used `xfs_repair` to fix it, then the Lucene codec (index corrupted error) message was present in logs.
This doesn't seem to be a verified bug and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
