### ISSUE TITLE
SearchServiceTests.testParseSourceValidation fails

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#115936]
### CI Link

https://gradle-enterprise.elastic.co/s/kwj5ep3e5vymm

### Repro line

./gradlew ":server:test" --tests "org.elasticsearch.search.SearchServiceTests.testParseSourceValidation" -Dtests.seed=DB172D57BA3537A5 -Dtests.locale=ar-BH -Dtests.timezone=America/Argentina/San_Luis -Druntime.java=22

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

```
SearchServiceTests > testParseSourceValidation FAILED
    java.lang.AssertionError:
    Expected: a string containing "`search_after` cannot be used in a scroll context."
         but: was "Sort must contain at least one field."
        at __randomizedtesting.SeedInfo.seed([DB172D57BA3537A5:48807AB8AFE2159C]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2543)
        at org.elasticsearch.search.SearchServiceTests.assertCreateContextValidation(SearchServiceTests.java:3038)
        at org.elasticsearch.search.SearchServiceTests.testParseSourceValidation(SearchServiceTests.java:2947)
```

**Comment by carlosdelest** [comment]
Marking `low-risk`, the test was muted and then the checking order changed for the request, so now the response is a different message. 

It is still an `IllegalArgumentException` with a different message, so users would receive a 400 back in case this is not a testing issue.

**Comment by drempapis** [comment]
Committed #117963
