### ISSUE TITLE
[CI] ES|QL TelemetryIT.testMetrics failure

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#116003]
### CI Link

https://gradle-enterprise.elastic.co/s/xrzv7jdcyi4ky/console-log/raw

### Repro line

`./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.action.TelemetryIT.testMetrics"`

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

```
1> [2024-10-31T08:08:55,817][INFO ][o.e.x.e.a.TelemetryIT    ] [testMetrics] [TelemetryIT#testMetrics {TestCase=Test[query=FROM idx
  1> | EVAL ip = to_ip(host), x = to_string(host), y = to_string(host)
  1> | INLINESTATS max(id)
  1> , expectedCommands={INLINESTATS=1, STATS=1, FROM=1, EVAL=1}, expectedFunctions={TO_STRING=2, MAX=1, TO_IP=1}, success=true]}]: cleaned up after test
  1> [2024-10-31T08:08:55,818][INFO ][o.e.x.e.a.TelemetryIT    ] [testMetrics] [TestCase=Test[query=FROM idx
  1> | EVAL ip = to_ip(host), x = to_string(host), y = to_string(host)
  1> | INLINESTATS max(id)
  1> , expectedCommands={INLINESTATS=1, STATS=1, FROM=1, EVAL=1}, expectedFunctions={TO_STRING=2, MAX=1, TO_IP=1}, success=true]] after test
  2> REPRODUCE WITH: ./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.action.TelemetryIT.testMetrics {TestCase=Test[query=FROM idx
  2> | EVAL ip = to_ip(host), x = to_string(host), y = to_string(host)
  2> | INLINESTATS max(id)
  2> , expectedCommands={INLINESTATS=1, STATS=1, FROM=1, EVAL=1}, expectedFunctions={TO_STRING=2, MAX=1, TO_IP=1}, success=true]}" -Dtests.seed=2C24155C2F138C18 -Dtests.locale=es-PH -Dtests.timezone=America/Miquelon -Druntime.java=23
  2> REPRODUCE WITH: ./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.action.TelemetryIT.testMetrics {TestCase=Test[query=FROM idx
  2> | EVAL ip = to_ip(host), x = to_string(host), y = to_string(host)
  2> | INLINESTATS max(id)
  2> , expectedCommands={INLINESTATS=1, STATS=1, FROM=1, EVAL=1}, expectedFunctions={TO_STRING=2, MAX=1, TO_IP=1}, success=true]}" -Dtests.seed=2C24155C2F138C18 -Dtests.locale=es-PH -Dtests.timezone=America/Miquelon -Druntime.java=23
  2> REPRODUCE WITH: ./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.action.TelemetryIT.testMetrics {TestCase=Test[query=FROM idx
  2> | EVAL ip = to_ip(host), x = to_string(host), y = to_string(host)
  2> | INLINESTATS max(id)
  2> , expectedCommands={INLINESTATS=1, STATS=1, FROM=1, EVAL=1}, expectedFunctions={TO_STRING=2, MAX=1, TO_IP=1}, success=true]}" -Dtests.seed=2C24155C2F138C18 -Dtests.locale=es-PH -Dtests.timezone=America/Miquelon -Druntime.java=23
  2> java.lang.AssertionError: 
    Expected: is <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([2C24155C2F138C18]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2543)
        at org.elasticsearch.xpack.esql.action.TelemetryIT.assertAllUsages(TelemetryIT.java:217)
        at org.elasticsearch.xpack.esql.action.TelemetryIT.lambda$testQuery$0(TelemetryIT.java:188)

    java.lang.AssertionError: 
    Expected: is <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([2C24155C2F138C18]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2543)
        at org.elasticsearch.xpack.esql.action.TelemetryIT.assertAllUsages(TelemetryIT.java:217)
        at org.elasticsearch.xpack.esql.action.TelemetryIT.lambda$testQuery$0(TelemetryIT.java:188)

    java.lang.AssertionError: 
    Expected: is <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([2C24155C2F138C18]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2543)
        at org.elasticsearch.xpack.esql.action.TelemetryIT.assertAllUsages(TelemetryIT.java:217)
        at org.elasticsearch.xpack.esql.action.TelemetryIT.lambda$testQuery$0(TelemetryIT.java:188)
```

**Comment by luigidellaquila** [comment]
I think it's related to https://github.com/elastic/elasticsearch/pull/115813

The underlying error is a query planning problem:

```
java.lang.IllegalStateException: can't find input for [max(id){r}#464]
```

the query is 

```
FROM idx
| EVAL ip = to_ip(host), x = to_string(host), y = to_string(host)
| INLINESTATS max(id)
```


The failure is quite deterministic, I'll disable that specific query from the telemetry tests to avoid too much noise.

@costin maybe you have a clue on the root cause, this test never failed before AFAIK

**Comment by luigidellaquila** [comment]
Related to https://github.com/elastic/elasticsearch/issues/110923

**Comment by costin** [comment]
Backport to 8.x at #116045

**Comment by nik9000** [comment]
I think we can drop the usage of INLINESTATS in the test, right?

**Comment by alex-spies** [comment]
That's already done in [Luigi's mute](https://github.com/elastic/elasticsearch/commit/681f5096e24967fc99699e682906776c1a75d39e).

Since the CI failure itself is resolved and we currently don't work on INLINESTATS, maybe it's better to add this failed query to the INLINESTATS follow-up meta issue than having a separate issue for it that'll stay open for a while.

**Comment by alex-spies** [comment]
Moved the corresponding work on INLINESTATS into its [meta issue](https://github.com/elastic/elasticsearch/issues/110923).
