### ISSUE TITLE
IllegalStateException thrown in SemanticQueryBuilder

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#116106]
### Description

For a `_field_caps` request with `params: {types=, ignore_unavailable=true, expand_wildcards=open, allow_no_indices=true, index=*,-.*, serverlessRequest=true, include_empty_fields=false}`, resulting in a `status: 500`, the following suppressed exception is logged:

```
java.lang.IllegalStateException: No inference results set for [semantic_text] field [description_embedding]
	at org.elasticsearch.inference@9.0.0/org.elasticsearch.xpack.inference.queries.SemanticQueryBuilder.doRewriteBuildSemanticQuery(SemanticQueryBuilder.java:169)
	at org.elasticsearch.inference@9.0.0/org.elasticsearch.xpack.inference.queries.SemanticQueryBuilder.doRewrite(SemanticQueryBuilder.java:155)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.AbstractQueryBuilder.rewrite(AbstractQueryBuilder.java:281)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.BoolQueryBuilder.rewriteClauses(BoolQueryBuilder.java:399)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.BoolQueryBuilder.doRewrite(BoolQueryBuilder.java:353)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.AbstractQueryBuilder.rewrite(AbstractQueryBuilder.java:281)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.BoolQueryBuilder.rewriteClauses(BoolQueryBuilder.java:399)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.BoolQueryBuilder.doRewrite(BoolQueryBuilder.java:353)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.AbstractQueryBuilder.rewrite(AbstractQueryBuilder.java:281)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.search.builder.SubSearchSourceBuilder.rewrite(SubSearchSourceBuilder.java:90)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.search.builder.SubSearchSourceBuilder.rewrite(SubSearchSourceBuilder.java:38)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.Rewriteable.rewrite(Rewriteable.java:57)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.Rewriteable.rewrite(Rewriteable.java:40)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.Rewriteable.rewrite(Rewriteable.java:125)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.search.builder.SearchSourceBuilder.rewrite(SearchSourceBuilder.java:1178)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.search.builder.SearchSourceBuilder.rewrite(SearchSourceBuilder.java:94)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.Rewriteable.rewrite(Rewriteable.java:57)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.Rewriteable.rewrite(Rewriteable.java:40)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.search.internal.ShardSearchRequest$RequestRewritable.rewrite(ShardSearchRequest.java:588)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.search.internal.ShardSearchRequest$RequestRewritable.rewrite(ShardSearchRequest.java:577)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.query.Rewriteable.rewrite(Rewriteable.java:57)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.search.SearchService.queryStillMatchesAfterRewrite(SearchService.java:1740)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.fieldcaps.FieldCapabilitiesFetcher.canMatchShard(FieldCapabilitiesFetcher.java:245)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.fieldcaps.FieldCapabilitiesFetcher.doFetch(FieldCapabilitiesFetcher.java:113)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.fieldcaps.FieldCapabilitiesFetcher.fetch(FieldCapabilitiesFetcher.java:77)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$NodeTransportHandler.lambda$messageReceived$0(TransportFieldCapabilitiesAction.java:591)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:356)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$NodeTransportHandler.messageReceived(TransportFieldCapabilitiesAction.java:570)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$NodeTransportHandler.messageReceived(TransportFieldCapabilitiesAction.java:565)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:579)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(SecurityServerTransportInterceptor.java:632)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(SecurityServerTransportInterceptor.java:621)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:640)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.ResizeRequestInterceptor.intercept(ResizeRequestInterceptor.java:105)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:79)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.ValidateRequestInterceptor.intercept(ValidateRequestInterceptor.java:20)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:79)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.ShardSearchRequestInterceptor.intercept(ShardSearchRequestInterceptor.java:23)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:79)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.UpdateRequestInterceptor.intercept(UpdateRequestInterceptor.java:27)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:79)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.SearchRequestInterceptor.intercept(SearchRequestInterceptor.java:20)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.IndicesAliasesRequestInterceptor.intercept(IndicesAliasesRequestInterceptor.java:127)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.SearchRequestCacheDisablingInterceptor.intercept(SearchRequestCacheDisablingInterceptor.java:53)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.BulkShardRequestInterceptor.intercept(BulkShardRequestInterceptor.java:85)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.interceptor.DlsFlsLicenseRequestInterceptor.intercept(DlsFlsLicenseRequestInterceptor.java:106)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService.runRequestInterceptors(AuthorizationService.java:634)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService.handleIndexActionAuthorizationResult(AuthorizationService.java:619)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$13(AuthorizationService.java:517)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:1033)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:999)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.RBACEngine.authorizeIndexAction(RBACEngine.java:384)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeAction(AuthorizationService.java:510)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService.maybeAuthorizeRunAs(AuthorizationService.java:442)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorize$3(AuthorizationService.java:329)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:257)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.RBACEngine.lambda$resolveAuthorizationInfo$0(RBACEngine.java:156)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:247)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.lambda$getRoles$4(CompositeRolesStore.java:202)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:247)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.lambda$getRole$5(CompositeRolesStore.java:220)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:247)
	at org.elasticsearch.xcore@9.0.0/org.elasticsearch.xpack.core.security.authz.store.RoleReferenceIntersection.lambda$buildRole$0(RoleReferenceIntersection.java:49)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:247)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.support.GroupedActionListener.onResponse(GroupedActionListener.java:57)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.buildRoleFromRoleReference(CompositeRolesStore.java:317)
	at org.elasticsearch.xcore@9.0.0/org.elasticsearch.xpack.core.security.authz.store.RoleReferenceIntersection.lambda$buildRole$1(RoleReferenceIntersection.java:53)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.elasticsearch.xcore@9.0.0/org.elasticsearch.xpack.core.security.authz.store.RoleReferenceIntersection.buildRole(RoleReferenceIntersection.java:53)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRole(CompositeRolesStore.java:218)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRoles(CompositeRolesStore.java:195)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.RBACEngine.resolveAuthorizationInfo(RBACEngine.java:152)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:345)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.transport.ServerTransportFilter.lambda$inbound$1(ServerTransportFilter.java:114)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:247)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:97)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authc.AuthenticatorChain.authenticate(AuthenticatorChain.java:93)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:264)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:201)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.transport.ServerTransportFilter.authenticate(ServerTransportFilter.java:127)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.transport.ServerTransportFilter.inbound(ServerTransportFilter.java:105)
	at org.elasticsearch.security@9.0.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:643)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:76)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:1098)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)\n

```

**Comment by benwtrent** [comment]
It is strange that field caps is making a semantic query at all :/ I wonder what is going on there.

**Comment by benwtrent** [comment]
LOL, looking at the comments on that line of code this is throwing on:

```
                // This should never happen, but throw on it in case it ever does
                throw new IllegalStateException(
                    "No inference results set for [" + semanticTextFieldType.typeName() + "] field [" + fieldName + "]"
                );
```

The curse of "This should never happen" has struck again!

**Comment by benwtrent** [comment]
@Mikep86 @carlosdelest ^ I wonder if this is because FieldCaps isn't rewriting queries like we expect for can_match?

Basically, field_caps allows `index_filter` which does a `can_match` phase to determine if all the shards for a given index will rewrite to a `match_none`. 

This makes me wonder if we should return a `MatchAllQuery` if inference results is `null`?

**Comment by Mikep86** [comment]
++, smells like a missing rewrite to me. It's plausible that we missed this during testing since the can_match phase is skipped most of the time.

**Comment by Mikep86** [comment]
@benwtrent I investigated this issue and was able to reproduce it with these steps:

```json
PUT field-caps-index
{
  "mappings": {
    "properties": {
      "semantic": {
        "type": "semantic_text"
      },
      "text_field": {
        "type": "text"
      }
    }
  }
}

POST field-caps-index/_doc/
{
  "semantic": "some test data",
  "text_field": "other test data"
} 

GET */_field_caps?fields=*&ignore_unavailable=true&expand_wildcards=open&allow_no_indices=true&include_empty_fields=false
{
  "index_filter": {
    "semantic": {
      "field": "semantic",
      "query": "test"
    }
  }
}
```

What's fascinating about the field caps API in this case is that it executes a subset of the normal rewrite rounds. Most importantly, the coordinator node rewrite round (where inference is performed) is skipped and it jumps straight to the can-match phase using a full `SearchExecutionContext`. This triggers the bug since the `semantic` query assumes that the coordinator node rewrite round is always executed first.

I think your proposed fix is the right one, if `inferenceResults` is `null` we should rewrite to `MatchAllQuery`. This assumes that the only way we get here is via an `index_filter` on the field caps API. Are there any other API paths you're aware of where the coordinator node rewrite round is skipped?

**Comment by benwtrent** [comment]
> Are there any other API paths you're aware of where the coordinator node rewrite round is skipped?

Not off hand, but I would assume `can_match`, `fetch`, `field_caps` all skip that rewrite. Though, the first two are just part of the normal search phase.

Maybe we should check `_count` as well? Its an optimized search path, so it shouldn't do any skipping but let's double check.

**Comment by Mikep86** [comment]
This bug is part of a larger issue with how the Field Caps API rewrites queries. See https://github.com/elastic/elasticsearch/issues/121709.

**Comment by marfinbirt** [comment]
Hello everyone, any progress on this? We're currently experiencing the same error and don't know how to proceed.

**Comment by Mikep86** [comment]
@marfinbirt No progress on this, but you can likely work around this by using an [exists query](https://www.elastic.co/docs/reference/query-languages/query-dsl/query-dsl-exists-query) on the `semantic_text` field instead. Since `semantic` queries perform a vector search operation, they have high recall (i.e. most, if not all, docs with a value for the field will be returned). Thus, an `exists` query on the field is effectively the same operation.

**Comment by marfinbirt** [comment]
I'm not sure what kind of matrix operation the query is performing under the hood when using **semantic_text**; I'm not an expert on it yet. I'd assume the _query_string_ passed in the query is transformed into an array, which is then compared to each of the documents in the index. 

```
"should": [
  {
    "semantic": {
  	"field": "embeddingSparse",
  	"query": "{{query_string}}",
    }
  }...
]
```

If this is true, I don't quite understand how replacing the query with **exists** will generate the same result, especially when exist doesn't receive any query_string. Can you please elaborate?

**Comment by kderusso** [comment]
Hey there @marfinbirt it does a vector search under the hood and the exists will filter to ensure only compatible fields are searched.

**Comment by Mikep86** [comment]
@marfinbirt The `semantic` query takes the query string and uses the model associated with the `semantic_text` field to generate an embedding, which is then used to determine document relevance using vector search.

Vector search operations are known to be high recall because every vector has some non-zero similarity to another vector. What matters in vector search is the degree of that similarity, which is why we use parameters like `k` in the `knn` query to restrict our results to documents that are similar enough to actually be relevant.

When vector search is used as a filter (as it is in this case), a field existence check (i.e. what the `exists` query does) is effectively the same due to the high recall nature of the search operation. Put another way, it doesn't matter what query string you use when using vector search as a filter. It will have some non-zero similarity to every embedding indexed, making the operation the same as a field existence check.

**Comment by kderusso** [comment]
Another example where this error comes up: 

```
"POST _aliases
{
 "actions": [
  {
   "add": {
    "index": "my_index",
    "alias": "alias_of_my_index",
    "filter": {
     "bool": {
      "should": [
       {
        "semantic": {
         "field": "embeddings_field",
         "query": "the query text"
        }
       }
      ]
     }
    }
   }
  }
 ]
}
```

Error: 
type: 'illegal_argument_exception"
reason: "failed to parse filter for alias [alias_of_my_index]"
caused_by
type: "illegal_state_exception"
reason: "No inference results set for [semantic_text] field [embeddings_field]"

**Comment by Mikep86** [comment]
Good catch, thanks @kderusso!

**Comment by Mikep86** [comment]
I investigated this further and there are a few paths through which a `semantic` query can be applied while skipping coordinator node rewrite:

- Field Caps index filters
- [Terms enum index filters](https://www.elastic.co/guide/en/elasticsearch/reference/8.18/search-terms-enum.html)
- [Alias filters](https://www.elastic.co/docs/manage-data/data-store/aliases#filter-alias)

The commonality with all of the above is that they are filter contexts.

If we can assume that these are the only paths through which coordinator node rewrite is skipped, we can implement a simple solution for all three code paths: In the `semantic` query, if the inference results are missing, rewrite to an `exists` query. That's a potentially big assumption though. @javanna @jimczi WDYT?

**Comment by javanna** [comment]
I am not convinced that we should fix anything so far. This is similar to terms lookup queries, as async actions are registered to them. They can't be used in an alias filter, nor in field caps as an index filter. We may want to throw a clearer error, perhaps make it a 400 error and clearly document this limitation?

I would like to better understand what makes the semantic query end up in a field caps index filter. That's odd, and I'd expect that not to come from users calling field caps manually, which is an important data point.

**Comment by Mikep86** [comment]
Understood @javanna, @Samiul-TheSoccerFan is working on tracking down where `semantic` queries can be added as a field caps index filter in Kibana. Let's regroup once he has more info about that.

**Comment by Mikep86** [comment]
@javanna We tracked down how this can happen in Kibana. It can be triggered in Discover or Lens if the user specifies a filter using Query DSL and puts a `semantic` query in it:

<img width="1028" height="421" alt="Image" src="https://github.com/user-attachments/assets/9c726fc0-65b8-4837-92fd-e61621310b39" />

What compounds the problem is that Kibana does a poor job reporting the error:

<img width="1161" height="412" alt="Image" src="https://github.com/user-attachments/assets/547da591-fb88-4974-a2be-c0351be8143f" />

You only get the _actual_ error if you examine with developer tools:

<img width="1635" height="234" alt="Image" src="https://github.com/user-attachments/assets/cf3fcaab-627a-458d-aedc-a2316bfebc92" />

Kibana wraps it in a 404, which is super helpful 🫠

**Comment by javanna** [comment]
thanks for tracking that down. I would imagine the same happens when you use a terms lookup in there too, which is an existing problem. I would ask if there's any usecase to use a semantic query in there, how common that could be. 

I would be leaning towards reverting #131111 to be honest. An error was previously returned anyways. If anything, we may wrap the "async actions still registered" for field caps index filter into something a little more explainable, as opposed to doing a class cast in there.

**Comment by Mikep86** [comment]
@javanna 

> I would ask if there's any usecase to use a semantic query in there, how common that could be.

No real-world usecase and it's very uncommon. As is, it takes a fair bit of effort to get to this state in Kibana because you need to enter a filter using Query DSL.

> I would be leaning towards reverting https://github.com/elastic/elasticsearch/pull/131111 to be honest.

Agreed we ultimately want to revert that change, but we need to replace it with different error handling. The whole reason we're discussing this is that the previous error handling returned a 500, which triggered a suppressed REST error, which triggered this whole investigation.

> If anything, we may wrap the "async actions still registered" for field caps index filter into something a little more explainable, as opposed to doing a class cast in there.

How would that work in this case? The async actions are registered on coordinator node rewrite. Since that rewrite phase doesn't execute through field caps, there are no registered async actions to detect.

**Comment by kderusso** [comment]
> Agreed we ultimately want to revert that change, but we need to replace it with different error handling. The whole reason we're discussing this is that the previous error handling returned a 500, which triggered a suppressed REST error, which triggered this whole investigation.

Can we just change the original error to return a 400 in this case, with maybe a better error message saying that inference is not supported for this use case?

**Comment by javanna** [comment]
I don't think we can go as far as being specific to inference in the error message, but turning that into a 400 sounds like a good idea to me, when such queries are used in the index filter of field caps. 

> How would that work in this case? The async actions are registered on coordinator node rewrite. Since that rewrite phase doesn't execute through field caps, there are no registered async actions to detect.

I have not looked at the code closely, but I was assuming that it's field caps that triggers the exception and we could catch it and wrap it. It may be a bit hacky still, you think that's not possible?

**Comment by Mikep86** [comment]
Agreed that returning a 400 is the correct solution. The next question is how to do that.

> I have not looked at the code closely, but I was assuming that it's field caps that triggers the exception and we could catch it and wrap it. It may be a bit hacky still, you think that's not possible?

Field caps does trigger the exception, but the situation is a bit more nuanced than that. The exception is raised during query rewrite, but there is no info in `QueryRewriteContext` to indicate that the rewrite is happening in the context of a field caps request. So we can't wrap the exception in the rewrite process itself. The other place we could wrap it is in [canMatchShard](https://github.com/Mikep86/elasticsearch/blob/3b6284505cb2f28e48fec44f01e7136aa8378ab7/server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesFetcher.java#L247-L247), but we would need to specialize the exception thrown during query rewrite so that we don't inadvertently wrap unrelated server-side errors.

The other option I was thinking of was a variation of https://github.com/elastic/elasticsearch/pull/131111, except check for queries that implement a certain interface/annotation. Check for something like `CoordinatorRewriteQuery` and throw if that is included as an index filter.

Preferences between these two options? Thoughts on alternatives?

**Comment by javanna** [comment]
I would catch the exception when calling rewrite in the field caps code e.g. `FieldCapabilitiesFetcher#canMatchShard` like you mentioned. Yet looking deeper at the code, I wonder if field caps is calling can match properly. I think that at the very least, callers of `queryStillMatchesAfterRewrite` should catch exception and interpret a failure as false as opposed to propagating them. A can match issue should not fail the query, and it should probably not fail field caps either? if we did that, we would not have this problem either, and providing such filter to field caps would be a no-op, how does that sound?

**Comment by Mikep86** [comment]
@javanna 

> I think that at the very least, callers of `queryStillMatchesAfterRewrite` should catch exception and interpret a failure as false as opposed to propagating them

That could work as long as we log any errors we catch so that they are not silently swallowed. Historically, has logging been sufficient for catching error conditions like this?

**Comment by javanna** [comment]
for can match, we don't do any logging so far, as it is an optional step. A failure on can match should not fail the search, and the same should be the case for field caps but it's currently not I believe.

**Comment by Mikep86** [comment]
@javanna 

Correct, the issue is that a can match failure causes field caps to fail. AFAIU the fix is:

- Update `FieldCapabilitiesFetcher#canMatchShard` to catch a specialized exception thrown when query rewrite fails due to the lack of coordinator node rewrite
- Log the event so that it is not silently ignored

If we're aligned, I can schedule work on a comprehensive fix

**Comment by javanna** [comment]
Looking at all the other can match consumers, I think the bug here is that field caps fails when can match does. We should rather catch any exception when calling can match as part of field caps. With that I don't think we need any specialized exception. I also don't think we need any logging in this case.

**Comment by dimitris-athanasiou** [comment]
Hi @javanna! Long time no see! I hope you're doing great!

I've been looking into this.

While field caps can be addressed by catching exceptions can match throws, this does not address the `put alias` problem @kderusso caught. There, in https://github.com/elastic/elasticsearch/blob/e76c2a6c5723c150170beef0b0450605ba119edc/server/src/main/java/org/elasticsearch/cluster/metadata/AliasValidator.java#L157 we also attempt to rewrite the queries in order to validate them before creating the alias.

I can imagine there might be more places like that, where we rewrite the queries for some reason. Should we not look for a fix that addresses all the class rather than treat field caps only?

I have not wrapped my head fully around this yet, but could we not assume that in rewrite `SemanticQueryBuilder` returns itself if no inference results are available?

**Comment by Mikep86** [comment]
> I have not wrapped my head fully around this yet, but could we not assume that in rewrite SemanticQueryBuilder returns itself if no inference results are available?

This wouldn't fix the problem as `SemanticQueryBuilder` requires inference results to continue its rewrite process. Earlier, we discussed rewriting to an `exists` query in this case, but we decided against that because it assumes the only way we can get into this state is through paths like fields caps, which is a dangerous assumption. There are also other queries that require coordinator node rewrite and we would like to implement a solution that handles those as well.

> While field caps can be addressed by catching exceptions can match throws, this does not address the put alias problem @kderusso caught

Maybe we should catch exceptions there as well?

**Comment by dimitris-athanasiou** [comment]
For the case of `put alias`, using a semantic query as a filter is a terrible idea as it is a very costly way of doing an `exists` query. Thus, a `400` error code is suitable. The error message could be better but this is quite the edge case.

I'll proceed making a fix for `field caps` as agreed.

**Comment by javanna** [comment]
> I can imagine there might be more places like that, where we rewrite the queries for some reason. Should we not look for a fix that addresses all the class rather than treat field caps only?

I think these are two separate problems. Field caps should not fail if rewriting the index filter fails. Can match is an optional step that should not fix whatever relies on it. 

The alias filter problem is understood and I think needs separate treatment. Throwing 400 and documenting what can't be used in an alias filter is good with me.
