### ISSUE TITLE
ArchiveTests test41AutoconfigurationNotTriggeredWhenNodeCannotContainData failing

### ISSUE THREAD

**Issue by pxsalehi** [elastic/elasticsearch#116299]
### CI Link

https://gradle-enterprise.elastic.co/s/einnxdw6o36bu

### Repro line

n/a

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure excerpt

```

[2024-11-06T08:17:36,616][ERROR][o.e.b.Elasticsearch      ] [BK-AGENT-PROD-G] fatal exception while booting Elasticsearch |  
-- | --
  | org.elasticsearch.ElasticsearchException: Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory. To bypass this problem by running Elasticsearch without machine learning functionality set [xpack.ml.enabled: false]. |  
  | at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLearning.java:1061) ~[?:?] |  
  | at org.elasticsearch.node.NodeConstruction.lambda$construct$16(NodeConstruction.java:888) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?] |  
  | at org.elasticsearch.plugins.PluginsService.lambda$flatMap$1(PluginsService.java:254) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?] |  
  | at java.util.stream.ReferencePipeline$7$1FlatMap.accept(ReferencePipeline.java:289) ~[?:?] |  
  | at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215) ~[?:?] |  
  | at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722) ~[?:?] |  
  | at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570) ~[?:?] |  
  | at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560) ~[?:?] |  
  | at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:636) ~[?:?] |  
  | at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:291) ~[?:?] |  
  | at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:656) ~[?:?] |  
  | at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:662) ~[?:?] |  
  | at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:667) ~[?:?] |  
  | at org.elasticsearch.node.NodeConstruction.construct(NodeConstruction.java:910) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?] |  
  | at org.elasticsearch.node.NodeConstruction.prepareConstruction(NodeConstruction.java:290) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?] |  
  | at org.elasticsearch.node.Node.<init>(Node.java:184) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?] |  
  | at org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:245) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?] |  
  | at org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:245) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?] |  
  | at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:76) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]


```

**Comment by pxsalehi** [comment]
This is windows packaging test.

**Comment by pxsalehi** [comment]
Muted in https://github.com/elastic/elasticsearch/commit/dee518612f9a8c1ed75a476774d70dc4a5c9d983.

**Comment by pxsalehi** [comment]
Also `:qa:packaging:destructiveDistroTest.default-windows-archive  org.elasticsearch.packaging.test.ArchiveTests test42AutoconfigurationNotTriggeredWhenNodeCannotBecomeMaster` seems to be failing for the same reason.

**Comment by breskeby** [comment]
From looking at the commit history, I _think_ the most likely change that started causing that test failure is the dynamic entitlement PR https://github.com/elastic/elasticsearch/pull/116125

**Comment by davidkyle** [comment]
This is due to ML upgrading the build system to Windows 2022 on the main branch https://github.com/elastic/ml-cpp/pull/2769

**Comment by davidkyle** [comment]
This Windows 2019 is failing due to upgrading the Windows build to 2022 in https://github.com/elastic/ml-cpp/pull/2769

Windows 2016 and 2019 will not be supported in version 9
