### ISSUE TITLE
[build] include in plugins only needed jars

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#11647]
Follow up for https://github.com/elastic/elasticsearch-analysis-kuromoji/issues/61

We don't shade anymore elasticsearch dependencies, so plugins might include jars in the distribution ZIP file which might not be needed anymore.

For example, `elasticsearch-cloud-aws` comes with:

```
Archive:  cloud-aws/target/releases/elasticsearch-cloud-aws-2.0.0-SNAPSHOT.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
  1920788  05-18-15 09:42   aws-java-sdk-ec2-1.9.34.jar
   503963  05-18-15 09:42   aws-java-sdk-core-1.9.34.jar
   232771  01-19-15 09:24   commons-codec-1.6.jar
   915096  01-19-15 09:24   jackson-databind-2.3.2.jar
   252288  05-18-15 09:42   aws-java-sdk-kms-1.9.34.jar
    62050  01-19-15 09:24   commons-logging-1.1.3.jar
   282269  10-31-14 13:19   httpcore-4.3.2.jar
    35058  01-19-15 09:24   jackson-annotations-2.3.0.jar
   229998  05-29-15 12:28   jackson-core-2.5.3.jar
   589289  01-19-15 09:24   joda-time-2.7.jar
   562858  05-18-15 09:42   aws-java-sdk-s3-1.9.34.jar
   590533  10-31-14 13:19   httpclient-4.3.5.jar
    44854  06-12-15 19:22   elasticsearch-cloud-aws-2.0.0-SNAPSHOT.jar
 --------                   -------
  6221815                   13 files
```

A lot of those files are already distributed with elasticsearch itself so classes are available within the classloader.

That's leading me to another question. We might now hit incompatibility issues. Let say we upgrade jackson to 3.0.0 in elasticsearch but aws sdk requires 2.x version. We might have a clash. @s1monw @rmuir WDYT?
That might not happen though.

**Comment by dadoonet** [comment]
Adding here an interesting article about building artifacts with assembly plugin http://books.sonatype.com/mvnref-book/reference/assemblies-sect-controlling-contents.html

**Comment by rmuir** [comment]
> A lot of those files are already distributed with elasticsearch itself so classes are available within the classloader.

thats why i say, list *exactly* what we are putting in our zips. no stupid maven transient dependencies: it does not work here anyway!!!! 

And for things like tracking licensing, knowing exactly what is going into the zips is a must-have anyway.

**Comment by dadoonet** [comment]
I found a configuration for analysis plugins which does what we expect.

src/main/assembly/plugins.xml

```xml
<?xml version="1.0"?>
<assembly>
    <id>plugin</id>
    <formats>
        <format>zip</format>
    </formats>
    <includeBaseDirectory>false</includeBaseDirectory>
    <dependencySets>
        <dependencySet>
            <outputDirectory>/</outputDirectory>
            <useProjectArtifact>true</useProjectArtifact>
            <useTransitiveFiltering>true</useTransitiveFiltering>
            <useTransitiveDependencies>true</useTransitiveDependencies>
            <excludes>
                <exclude>org.elasticsearch:elasticsearch</exclude>
            </excludes>
        </dependencySet>
    </dependencySets>
</assembly>
```

Test script:

```sh
#!/bin/bash

for i in * ; do
  if [ -d "$i" ]; then
    echo "**** $i"
	cd $i
	mvn clean install -DskipTests 1>> ../make.logs
	unzip -l target/releases/elasticsearch-$i-2.0.0-SNAPSHOT.zip
	cd ..
  fi
done
```

It gives:

```
**** analysis-icu
Archive:  target/releases/elasticsearch-analysis-icu-2.0.0-SNAPSHOT.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
    78854  06-11-15 14:52   lucene-analyzers-icu-5.2.0.jar
 11126867  12-03-14 18:48   icu4j-54.1.jar
    23791  06-15-15 12:47   elasticsearch-analysis-icu-2.0.0-SNAPSHOT.jar
 --------                   -------
 11229512                   3 files
**** analysis-kuromoji
Archive:  target/releases/elasticsearch-analysis-kuromoji-2.0.0-SNAPSHOT.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
  4598265  06-11-15 14:52   lucene-analyzers-kuromoji-5.2.0.jar
    20858  06-15-15 12:47   elasticsearch-analysis-kuromoji-2.0.0-SNAPSHOT.jar
 --------                   -------
  4619123                   2 files
**** analysis-phonetic
Archive:  target/releases/elasticsearch-analysis-phonetic-2.0.0-SNAPSHOT.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
   284184  11-25-14 11:46   commons-codec-1.10.jar
    15810  06-15-15 12:47   elasticsearch-analysis-phonetic-2.0.0-SNAPSHOT.jar
    26152  06-11-15 14:52   lucene-analyzers-phonetic-5.2.0.jar
 --------                   -------
   326146                   3 files
**** analysis-smartcn
Archive:  target/releases/elasticsearch-analysis-smartcn-2.0.0-SNAPSHOT.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
  3603150  06-11-15 14:52   lucene-analyzers-smartcn-5.2.0.jar
    12121  06-15-15 12:47   elasticsearch-analysis-smartcn-2.0.0-SNAPSHOT.jar
 --------                   -------
  3615271                   2 files
**** analysis-stempel
Archive:  target/releases/elasticsearch-analysis-stempel-2.0.0-SNAPSHOT.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
    10452  06-15-15 12:48   elasticsearch-analysis-stempel-2.0.0-SNAPSHOT.jar
   517989  06-11-15 14:52   lucene-analyzers-stempel-5.2.0.jar
 --------                   -------
   528441                   2 files
```

What I like with this approach is that we can share the same configuration file accros multiple plugins (may be all of them).

When running that on other plugins (with same assembly descriptor), I get:

```
**** cloud-aws
Archive:  target/releases/elasticsearch-cloud-aws-2.0.0-SNAPSHOT.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
   503963  05-18-15 09:42   aws-java-sdk-core-1.9.34.jar
   915096  01-19-15 09:24   jackson-databind-2.3.2.jar
   252288  05-18-15 09:42   aws-java-sdk-kms-1.9.34.jar
   590533  10-31-14 13:19   httpclient-4.3.5.jar
   232771  01-19-15 09:24   commons-codec-1.6.jar
    35058  01-19-15 09:24   jackson-annotations-2.3.0.jar
   589289  01-19-15 09:24   joda-time-2.7.jar
    62050  01-19-15 09:24   commons-logging-1.1.3.jar
   282269  10-31-14 13:19   httpcore-4.3.2.jar
   229998  05-29-15 12:28   jackson-core-2.5.3.jar
   562858  05-18-15 09:42   aws-java-sdk-s3-1.9.34.jar
    44854  06-15-15 12:48   elasticsearch-cloud-aws-2.0.0-SNAPSHOT.jar
  1920788  05-18-15 09:42   aws-java-sdk-ec2-1.9.34.jar
 --------                   -------
  6221815                   13 files
**** cloud-azure
Archive:  target/releases/elasticsearch-cloud-azure-2.0.0-SNAPSHOT.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
   662947  02-04-15 16:33   azure-storage-2.0.0.jar
    62050  01-19-15 09:24   commons-logging-1.1.3.jar
   232771  01-19-15 09:24   commons-codec-1.6.jar
   465649  10-30-14 13:57   jersey-core-1.13.jar
    18323  10-30-14 13:57   jackson-jaxrs-1.9.2.jar
    27075  10-30-14 13:57   jackson-xc-1.9.2.jar
    96737  02-05-15 11:45   azure-management-0.7.0.jar
   229998  05-29-15 12:28   jackson-core-2.5.3.jar
   149432  02-04-15 16:28   azure-core-0.7.0.jar
   590533  10-31-14 13:19   httpclient-4.3.5.jar
     2497  10-25-14 15:13   javax.inject-1.jar
   131269  10-30-14 13:48   jersey-client-1.13.jar
    67758  10-30-14 13:54   jettison-1.1.jar
   890168  10-30-14 13:55   jaxb-impl-2.2.3-1.jar
    25689  10-31-14 13:19   slf4j-api-1.6.2.jar
   634271  02-04-15 17:23   azure-management-compute-0.7.0.jar
   508143  10-30-14 13:57   mail-1.4.5.jar
   765648  10-30-14 13:57   jackson-mapper-asl-1.9.2.jar
   412739  10-31-14 13:19   commons-lang3-3.3.2.jar
   282269  10-31-14 13:19   httpcore-4.3.2.jar
    62983  10-25-14 15:13   activation-1.1.jar
   163417  10-30-14 13:54   jersey-json-1.13.jar
    26514  10-27-14 17:18   stax-api-1.0.1.jar
   105134  10-30-14 13:55   jaxb-api-2.2.2.jar
    23346  10-30-14 13:55   stax-api-1.0-2.jar
   228286  10-30-14 13:56   jackson-core-asl-1.9.2.jar
    48482  06-15-15 12:48   elasticsearch-cloud-azure-2.0.0-SNAPSHOT.jar
 --------                   -------
  6914128                   27 files
**** cloud-gce
Archive:  target/releases/elasticsearch-cloud-gce-2.0.0-SNAPSHOT.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
   194265  04-24-15 12:25   google-api-client-1.20.0.jar
   232771  01-19-15 09:24   commons-codec-1.6.jar
   286717  04-24-15 12:25   google-http-client-1.20.0.jar
   590533  10-31-14 13:19   httpclient-4.3.5.jar
   466069  04-24-15 12:24   google-api-services-compute-v1-rev59-1.20.0.jar
   282269  10-31-14 13:19   httpcore-4.3.2.jar
  1791384  04-24-15 12:25   guava-jdk5-13.0.jar
    61092  04-24-15 12:25   google-oauth-client-1.20.0.jar
    33015  10-25-14 15:12   jsr305-1.3.9.jar
    62050  01-19-15 09:24   commons-logging-1.1.3.jar
     6720  04-24-15 12:25   google-http-client-jackson2-1.20.0.jar
   229998  05-29-15 12:28   jackson-core-2.5.3.jar
    18219  06-15-15 12:49   elasticsearch-cloud-gce-2.0.0-SNAPSHOT.jar
 --------                   -------
  4255102                   13 files
```

Finding the dependencies to include/update looks as a nightmare to me and that's somehow what maven is good at. 
That said, too many libs are still included in cloud plugins. A global workaround would be to mark all elasticsearch core dependencies as `provided` in `plugins/pom.xml`. In that case, shared libs won't be included in the plugin distribution as maven will resolve that.

@rmuir I understand that you are not a fan of this and the reasons you are against this.
To me it's a tradeoff between `plugin.xml` complexity and the risk of missing something. It looks super easy for simple plugins like analysis but more complex for cloud plugins.
I can give a try to your solution though and see where is goes.

**Comment by dadoonet** [comment]
Ha. I forgot to say that it works well for analysis plugins because I added in `plugins/pom.xml`:

```xml
        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-analyzers-common</artifactId>
            <scope>provided</scope>
        </dependency>
```

**Comment by dadoonet** [comment]
And here is the result for lang plugins:

```
**** lang-javascript
Archive:  target/releases/elasticsearch-lang-javascript-2.0.0-SNAPSHOT.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
  1134765  12-12-14 19:05   rhino-1.7R4.jar
    23725  06-15-15 13:16   elasticsearch-lang-javascript-2.0.0-SNAPSHOT.jar
 --------                   -------
  1158490                   2 files
**** lang-python
Archive:  target/releases/elasticsearch-lang-python-2.0.0-SNAPSHOT.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
    10063  06-15-15 13:17   elasticsearch-lang-python-2.0.0-SNAPSHOT.jar
 37021723  05-27-15 22:59   jython-standalone-2.7.0.jar
 --------                   -------
 37031786                   2 files
```

**Comment by dadoonet** [comment]
By explicitly marking elasticsearch core dependencies as provided, it reduced the number of libs of cloud plugins. We now have:

```
**** cloud-aws
Archive:  target/releases/elasticsearch-cloud-aws-2.0.0-SNAPSHOT.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
  1920788  05-18-15 09:42   aws-java-sdk-ec2-1.9.34.jar
   503963  05-18-15 09:42   aws-java-sdk-core-1.9.34.jar
   232771  01-19-15 09:24   commons-codec-1.6.jar
   562858  05-18-15 09:42   aws-java-sdk-s3-1.9.34.jar
    62050  01-19-15 09:24   commons-logging-1.1.3.jar
   282269  10-31-14 13:19   httpcore-4.3.2.jar
    35058  01-19-15 09:24   jackson-annotations-2.3.0.jar
   252288  05-18-15 09:42   aws-java-sdk-kms-1.9.34.jar
    44854  06-15-15 13:27   elasticsearch-cloud-aws-2.0.0-SNAPSHOT.jar
   590533  10-31-14 13:19   httpclient-4.3.5.jar
  1143162  06-15-15 11:11   jackson-databind-2.5.3.jar
 --------                   -------
  5630594                   11 files
**** cloud-azure
Archive:  target/releases/elasticsearch-cloud-azure-2.0.0-SNAPSHOT.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
   662947  02-04-15 16:33   azure-storage-2.0.0.jar
     2497  10-25-14 15:13   javax.inject-1.jar
   131269  10-30-14 13:48   jersey-client-1.13.jar
    67758  10-30-14 13:54   jettison-1.1.jar
    26514  10-27-14 17:18   stax-api-1.0.1.jar
   890168  10-30-14 13:55   jaxb-impl-2.2.3-1.jar
   149432  02-04-15 16:28   azure-core-0.7.0.jar
   282269  10-31-14 13:19   httpcore-4.3.2.jar
   232771  01-19-15 09:24   commons-codec-1.6.jar
   163417  10-30-14 13:54   jersey-json-1.13.jar
   105134  10-30-14 13:55   jaxb-api-2.2.2.jar
    23346  10-30-14 13:55   stax-api-1.0-2.jar
   765648  10-30-14 13:57   jackson-mapper-asl-1.9.2.jar
   634271  02-04-15 17:23   azure-management-compute-0.7.0.jar
    62983  10-25-14 15:13   activation-1.1.jar
   465649  10-30-14 13:57   jersey-core-1.13.jar
    18323  10-30-14 13:57   jackson-jaxrs-1.9.2.jar
    27075  10-30-14 13:57   jackson-xc-1.9.2.jar
    96737  02-05-15 11:45   azure-management-0.7.0.jar
    48481  06-15-15 13:28   elasticsearch-cloud-azure-2.0.0-SNAPSHOT.jar
   590533  10-31-14 13:19   httpclient-4.3.5.jar
    62050  01-19-15 09:24   commons-logging-1.1.3.jar
   508143  10-30-14 13:57   mail-1.4.5.jar
   228286  10-30-14 13:56   jackson-core-asl-1.9.2.jar
 --------                   -------
  6245701                   24 files
**** cloud-gce
Archive:  target/releases/elasticsearch-cloud-gce-2.0.0-SNAPSHOT.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
   466069  04-24-15 12:24   google-api-services-compute-v1-rev59-1.20.0.jar
   282269  10-31-14 13:19   httpcore-4.3.2.jar
    18217  06-15-15 13:28   elasticsearch-cloud-gce-2.0.0-SNAPSHOT.jar
   194265  04-24-15 12:25   google-api-client-1.20.0.jar
   590533  10-31-14 13:19   httpclient-4.3.5.jar
    61092  04-24-15 12:25   google-oauth-client-1.20.0.jar
   232771  01-19-15 09:24   commons-codec-1.6.jar
   286717  04-24-15 12:25   google-http-client-1.20.0.jar
    33015  10-25-14 15:12   jsr305-1.3.9.jar
    62050  01-19-15 09:24   commons-logging-1.1.3.jar
     6720  04-24-15 12:25   google-http-client-jackson2-1.20.0.jar
  1791384  04-24-15 12:25   guava-jdk5-13.0.jar
 --------                   -------
  4025102                   12 files
```

aws: 13 -> 11
azure: 27 -> 24
gce: 13 -> 12

**Comment by rmuir** [comment]
> @rmuir I understand that you are not a fan of this and the reasons you are against this.
> To me it's a tradeoff between plugin.xml complexity and the risk of missing something.

I think maven's transitive dependency mechanism is *broken* here either way.

The way i see it, there are two choices:
1 manually maintain list of all transitive dependencies for elasticsearch/lucene/anything else ES brings in 
2 manually maintain list of all dependencies for each plugin.

Given those two choices, I argue that 2 is easier than 1. It is also easier to reason about: you specify exactly what should be in the zip, versus trying to navigate through tons of confusing maven dependencies to figure out why something that should not be there..

So i am not insisting on number 2... I just think its the less evil of the two choices. If there is a third choice that is simpler then this is not really relevant.

**Comment by rmuir** [comment]
By the way @dadoonet if you have a PR for this, we should move forward. We can followup with improved ways to do it later. Today our plugins have duplicate jars (jar hell): I think its a big problem.

I'm gonna make this issue as a blocker.

**Comment by rmuir** [comment]
and again, your method is fine, method number 1 versus method number 2 is not so important when today we have number 3: jar hell.

**Comment by clintongormley** [comment]
@dadoonet any progress here?

**Comment by dadoonet** [comment]
Not at this time. Focussing all efforts on distribution modules. Trying to fix remaining RPM issue.

**Comment by rmuir** [comment]
I can try to implement the approach david took. First i am looking at jar hell, and maybe we can improve testing around this area once we have that (at least a script or something, try to load all plugins up...)

**Comment by dadoonet** [comment]
@clintongormley @rmuir Good news. I think I'm done with the distribution stuff: https://github.com/elastic/elasticsearch/pull/11523

So I looked again at my WIP and pushed my branch here: https://github.com/dadoonet/elasticsearch/tree/plugins/reduce-analysis-size

I'll travelling today and hopefully will be able to push that forward and come with a PR.
Will update here.

**Comment by dadoonet** [comment]
@rmuir I finally opened #11944. Was having some issues when I rebased my code with the license-checker as some jars are not provided anymore within the plugin artifact. :) 

Let me know what you think of it.

**Comment by jaysonminard** [comment]
So is this creating a new dependency hell?  If we bring in ElasticSearch, say via Gradle, then we end up with all the versions it uses of many libraries all possible conflicting with other frameworks and even our application code.  All to get access to the client, or to run embedded ES.  And now to resolve it, the application has to shade things of its own to avoid unknown failures happening in ES which probably requires more specific and well tested versions of things  But on accident, if they don't know all this, their Gradle will change version numbers used to the most recent, causing unknown failures, silent or obvious.  And if they want to fix it, the only place they really can then is shading their application's usage, and hope that the somewhat-not-really-maintained-with-every-feature Gradle Shadow plugin can handle only shading the right things and not mucking up others.  And when you add that plugin, then you might have issues with Gradle Application plugin knowing to use a partial Uber JAR with some shaded things, then other JARs that were left untouched (if even possible), and whack-bam-fun-and-games you are in a new hell.  

up until now, ElasticSearch was one library you could include that didn't screw you over.  Now we get to play games with it and a longer list of dependencies!  

Obviously this issue was from the viewpoint of the creators of ES, and not from the viewpoint of using it as a library.  Or am I missing some magical benefit this provides?  I only see problems.  

btw, I think you broke some plugins on Master, cloud-was doesn't register s3 repos anymore.

```
org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: org/apache/http/protocol/HttpContext
  at org.elasticsearch.repositories.s3.S3Repository.<init>(Unknown Source)
  while locating org.elasticsearch.repositories.s3.S3Repository
  while locating org.elasticsearch.repositories.Repository

1 error
	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:140)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
	at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:404)
	at org.elasticsearch.repositories.RepositoriesService.registerRepository(RepositoriesService.java:368)
	at org.elasticsearch.repositories.RepositoriesService.access$100(RepositoriesService.java:55)
	at org.elasticsearch.repositories.RepositoriesService$1.execute(RepositoriesService.java:110)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:378)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:209)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/apache/http/protocol/HttpContext
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:129)
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:432)
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:414)
	at org.elasticsearch.cloud.aws.InternalAwsS3Service.getClient(InternalAwsS3Service.java:153)
	at org.elasticsearch.cloud.aws.InternalAwsS3Service.client(InternalAwsS3Service.java:82)
	at org.elasticsearch.repositories.s3.S3Repository.<init>(S3Repository.java:125)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:56)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
	at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:54)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:865)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:858)
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
	... 13 more
Caused by: java.lang.ClassNotFoundException: org.apache.http.protocol.HttpContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more

```

**Comment by dadoonet** [comment]
@jaysonminard you can still use the shaded version of elasticsearch as we still provide it with the classifier `shaded`: https://github.com/elastic/elasticsearch/blob/master/core/pom.xml#L374

Would that help you?

Thank you for raising the S3 issue. We need to check that.

**Comment by dadoonet** [comment]
I just opened #12034 for the last issue you reported.
