### ISSUE TITLE
RemoteClusterPermissionsTests » testCollapseAndRemoveUnsupportedPrivileges NullPointerException

### ISSUE THREAD

**Issue by masseyke** [elastic/elasticsearch#116520]
### CI Link

https://gradle-enterprise.elastic.co/s/aijtpslrcecfo/tests/task/:x-pack:plugin:core:test/details/org.elasticsearch.xpack.core.security.authz.permission.RemoteClusterPermissionsTests/testCollapseAndRemoveUnsupportedPrivileges?top-execution=1

### Repro line

./gradlew ":x-pack:plugin:core:test" --tests "org.elasticsearch.xpack.core.security.authz.permission.RemoteClusterPermissionsTests.testCollapseAndRemoveUnsupportedPrivileges" -Dtests.seed=D930E26AF0B02A66 -Dtests.locale=en-AU -Dtests.timezone=America/Marigot -Druntime.java=23

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

```java.lang.NullPointerException: Cannot invoke "java.util.Collection.size()" because "collection" is null
	at __randomizedtesting.SeedInfo.seed([D930E26AF0B02A66:A204096B4B91141C]:0)
	at com.carrotsearch.randomizedtesting.generators.RandomPicks.randomFrom(RandomPicks.java:48)
	at org.elasticsearch.test.ESTestCase.randomFrom(ESTestCase.java:1197)
	at org.elasticsearch.test.ESTestCase.randomFrom(ESTestCase.java:1192)
	at org.elasticsearch.xpack.core.security.authz.permission.RemoteClusterPermissionsTests.testCollapseAndRemoveUnsupportedPrivileges(RemoteClusterPermissionsTests.java:134)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```

**Comment by masseyke** [comment]
This is actually happening on my PR branch, not main. No idea why, but it's my problem.

**Comment by masseyke** [comment]
OK this happens in my branch because it will happen any time that `ROLE_MONITOR_STATS` is not the latest version in TransportVersions. So it doesn't fail in main, but no one can add a transport versions until this is fixed.

**Comment by jakelandis** [comment]
This reproduces when you add a new transport version. Fixed by https://github.com/elastic/elasticsearch/pull/116532.
