### ISSUE TITLE
NullPointerException when using bulk import

### ISSUE THREAD

**Issue by hydrogen18** [elastic/elasticsearch#11671]
While using the bulk import, I got an error message of `NullPointerException[null]`

From the logs:

```
[2015-06-15 08:03:03,831][DEBUG][action.bulk              ] [Autolycus] [products][3], node[ZrSwGU7bR_Oh9htebqstEA], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.bulk.BulkShardRequest@5f410b12]
java.lang.NullPointerException
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shards(TransportShardBulkAction.java:129)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performReplicas(TransportShardReplicationOperationAction.java:565)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:512)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2015-06-15 08:03:03,841][DEBUG][action.bulk              ] [Autolycus] [products][4], node[ZrSwGU7bR_Oh9htebqstEA], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.bulk.BulkShardRequest@77230a7b]
java.lang.NullPointerException
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shards(TransportShardBulkAction.java:129)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performReplicas(TransportShardReplicationOperationAction.java:565)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:512)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2015-06-15 08:03:03,865][DEBUG][action.bulk              ] [Autolycus] [products][1], node[ZrSwGU7bR_Oh9htebqstEA], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.bulk.BulkShardRequest@7d9b753]
java.lang.NullPointerException
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shards(TransportShardBulkAction.java:129)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performReplicas(TransportShardReplicationOperationAction.java:565)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:512)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2015-06-15 08:03:03,881][DEBUG][action.bulk              ] [Autolycus] [products][2], node[ZrSwGU7bR_Oh9htebqstEA], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.bulk.BulkShardRequest@1542dc3d]
java.lang.NullPointerException
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shards(TransportShardBulkAction.java:129)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performReplicas(TransportShardReplicationOperationAction.java:565)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:512)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Running 1.4.2 locally on Ubuntu 14.04 LTS

```
[ericu-destroyer-of-worlds] elasticsearch$ curl localhost:9200
{
  "status" : 200,
  "name" : "Autolycus",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.4.2",
    "build_hash" : "927caff6f05403e936c20bf4529f144f0c89fd8c",
    "build_timestamp" : "2014-12-16T14:11:12Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.2"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by dakrone** [comment]
@hydrogen18 can you give us an example bulk request that is causing the null pointer exception?

**Comment by bleskes** [comment]
@hydrogen18 do you create the index dynamically by indexing into it or is it created in advance?

**Comment by hydrogen18** [comment]
The index is created in advance. I could give you an example, but the documents are boring.

**Comment by bleskes** [comment]
@hydrogen18 thx. The stack trace (which we can do better reporting dealing with) suggest that index was removed while the operation was in flight. Can that be?

**Comment by hydrogen18** [comment]
I did not intentionally do that. This box is on our local network, so I suppose it is possible. Would there be a log statement indicating when the index was dropped?

**Comment by bleskes** [comment]
on the  master, you should see the result of this log:

```
                logger.info("[{}] deleting index", request.index);
```

**Comment by hydrogen18** [comment]
It does appear the indices were deleted in the same time period. I am unsure how that happened. There is probably no 'correct' way for the software to handle such a situation. However, it'd be nice if the message was something other than "NullPointerException"

```
elasticsearch.log.2015-06-15:[2015-06-15 08:03:03,744][INFO ][cluster.metadata         ] [Autolycus] [products] deleting index
elasticsearch.log.2015-06-15:[2015-06-15 08:03:09,115][INFO ][cluster.metadata         ] [Autolycus] [scripts] deleting index
```

**Comment by bleskes** [comment]
Yeah, the NullPointerException is totally wrong. I’ll fix that….

Thanks for digging it up.

**Comment by gfyoung** [comment]
@bleskes : It seems some like logging a warning of some kind (after checking for `null`) would be best?

**Comment by bleskes** [comment]
@gfyoung we should totally avoid the NPE and deal with concurrent index deletion correctly. This has long been fixed (somewhere in the 2.x history line) so I'm closing this now.
