### ISSUE TITLE
NullPointerException indexing percolator query with "inner_hits"

### ISSUE THREAD

**Issue by Volune** [elastic/elasticsearch#11672]
With ElasticSearch 1.5.2

I have a mapping with a nested object and try to index a percolator query like this:
```
{
  "query": {
    "filtered": {
      "query": {
        "match_all": {}
      },
      "filter": {
        "nested": {
          "path": "nestedObject",
          "query": {
            "filtered": {
              "query": {
                "match_all": {}
              }
            }
          },
          "inner_hits": {
            "size": 1000
          }
        }
      }
    }
  }
}
```

That produces this exception:
```
org.elasticsearch.index.percolator.PercolatorException: [test] failed to parse query [498370ec09aecc8ac355befa1f41]
        at org.elasticsearch.index.percolator.PercolatorQueriesRegistry.parsePercolatorDocument(PercolatorQueriesRegistry.java:196)
        at org.elasticsearch.index.percolator.PercolatorQueriesRegistry$RealTimePercolatorOperationListener.preIndex(PercolatorQueriesRegistry.java:324)
        at org.elasticsearch.index.indexing.ShardIndexingService.preIndex(ShardIndexingService.java:139)
        at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:493)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:196)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:515)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:422)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.elasticsearch.index.query.QueryParseContext.addInnerHits(QueryParseContext.java:268)
        at org.elasticsearch.index.query.NestedQueryParser$ToBlockJoinQueryBuilder.build(NestedQueryParser.java:153)
        at org.elasticsearch.index.query.NestedFilterParser.parse(NestedFilterParser.java:97)
        at org.elasticsearch.index.query.QueryParseContext.executeFilterParser(QueryParseContext.java:368)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerFilter(QueryParseContext.java:349)
        at org.elasticsearch.index.query.BoolFilterParser.parse(BoolFilterParser.java:92)
        at org.elasticsearch.index.query.QueryParseContext.executeFilterParser(QueryParseContext.java:368)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerFilter(QueryParseContext.java:349)
        at org.elasticsearch.index.query.FilteredQueryParser.parse(FilteredQueryParser.java:74)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:302)
        at org.elasticsearch.index.query.IndexQueryParserService.parseInnerQuery(IndexQueryParserService.java:321)
        at org.elasticsearch.index.percolator.PercolatorQueriesRegistry.parseQuery(PercolatorQueriesRegistry.java:222)
        at org.elasticsearch.index.percolator.PercolatorQueriesRegistry.parsePercolatorDocument(PercolatorQueriesRegistry.java:193)
        ... 9 more
```

I can index the query if I remove the useless "inner_hits" field. Maybe Elasticsearch should return a better error than `NullPointerException`

**Comment by martijnvg** [comment]
@Volune agreed, ES should fail with a better error with something like: `inner hits isn't supported in the percolate api`
