### ISSUE TITLE
Exception on MapperParsingException

### ISSUE THREAD

**Issue by sybnex** [elastic/elasticsearch#11714]
I've got following error in elasticsearch.log

```
[2015-06-17 07:13:18,146][DEBUG][action.bulk              ] [Claudette St. Croix] [idx_xxx-2015.06.16][3] failed to execute bulk item (index) index {[idx_xxx-2015.06.16][xxx][AU3_74pBI_BlciXyfFn7], source[{"message":"2015 06 16 17:09:30 ipF=172.16.94.11 country=XX srvname=XX method=GET reqF=\"GET /xx/account/self HTTP/1.1\" Referer=\"-\" sCF=403 sCB=- bsF=- dTF=- dTB=- dTcB=- dTsB=- dTr1B=- dTr2B=- browser=\"xx\" SSLC=- SSLP=- invS=- AddrB=\"-\" trID=- Event=- ","@version":"1","@timestamp":"2015-06-16T15:09:33.904Z","type":"xx","file":"/var/opt/xx/customaccess.log","host":"xx.test","offset":"10940297","ipF":"172.16.94.11","country":"XX","srvname":"xx.test","method":"GET","reqF":"GET /xx/account/self HTTP/1.1","Referer":"-","sCF":403,"sCB":0,"bsF":"-","dTF":0.0,"dTB":0.0,"dTcB":0.0,"dTsB":0.0,"dTr1B":0.0,"dTr2B":0.0,"browser":"xx","SSLC":"-","SSLP":"-","invS":"-","AddrB":"-","trID":"-","Event":"-","received_at":"2015-06-16T15:09:33.904Z","received_from":["xx","test"],"hostname":"xx"}]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [bsF]
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:411)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:706)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:497)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:544)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:493)
        at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:466)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:418)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:148)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:574)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:440)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "-"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:581)
        at java.lang.Long.parseLong(Long.java:631)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.longValue(AbstractXContentParser.java:145)
        at org.elasticsearch.index.mapper.core.LongFieldMapper.innerParseCreateField(LongFieldMapper.java:288)
        at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:239)
        at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:401)
        ... 13 more
```

Filter is based on kv. Number Detection in Elasticsearch is activated.

**Comment by markwalkom** [comment]
`-` is not an integer so you cannot map it to one.

Please join us in #elasticsearch on Freenode or at https://discuss.elastic.co/ for troubleshooting help, we reserve Github for confirmed bugs and feature requests :)

**Comment by sybnex** [comment]
I was never trying to ... here the filter:

```
    kv {
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    mutate {
      convert => [ "sCB", "integer" ]
      convert => [ "sCF", "integer" ]
      convert => [ "dTB",   "float" ]
      convert => [ "dTF",   "float" ]
      convert => [ "dTcB",  "float" ]
      convert => [ "dTsB",  "float" ]
      convert => [ "dTr1B", "float" ]
      convert => [ "dTr2B", "float" ]
      convert => [ "bsF"  , "string"]
    }
    if [bsF] == "-" {
      drop { }
    }
```

**Comment by sybnex** [comment]
OK, you right. Just saw it right now on formated screen. The other fields are also crappy.
