### ISSUE TITLE
Calling a CCS index `*:index_name` requires `remote_cluster_client` when there are no remote clusters

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#117178]
### Elasticsearch Version

8.14+

### Java Version

_bundled_

### OS Version

_any_

### Problem Description

When searching an index pattern that COULD refer to remote clusters, even though there are NO remote clusters configured, requires `remote_cluster_client` to be set.

Some solutions add "catch all" index patters in Kibana (e.g. `*:metrics-*`), this now requires all nodes to have `remote_cluster_client` role configured. For some customers, they prefer to minutely control the roles and now they cannot.

### Steps to Reproduce

Create a cluster
Have no remote_cluster_client

Add some basic data and attempt to search

```
POST test/_doc
{
	"text": "quick brown fox, quick brown fox"
}


POST *:*/_search?error_trace
{
  "query": {
	"match_all": {}
  }
}
```

### Logs (if relevant)

```
        "stack_trace": "java.lang.IllegalArgumentException: node [Benjamins-MacBook-Pro-2.local] does not have the remote cluster client role enabled
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.transport.RemoteClusterAware.groupClusterIndices(RemoteClusterAware.java:137)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.transport.RemoteClusterService.groupIndices(RemoteClusterService.java:188)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.action.ResolvedIndices.resolveWithIndicesRequest(ResolvedIndices.java:153)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.action.search.TransportSearchAction.executeRequest(TransportSearchAction.java:344)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:316)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:121)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:135)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:54)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:132)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.action.support.MappedActionFilters$MappedFilterChain.proceed(MappedActionFilters.java:71)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.action.support.MappedActionFilters.apply(MappedActionFilters.java:49)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:132)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.action.support.TransportAction.handleExecution(TransportAction.java:96)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:59)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.tasks.TaskManager.registerAndExecute(TaskManager.java:197)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.client.internal.node.NodeClient.executeLocally(NodeClient.java:106)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.action.RestCancellableNodeClient.doExecute(RestCancellableNodeClient.java:82)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:140)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.action.search.RestSearchAction.lambda$prepareRequest$2(RestSearchAction.java:125)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:144)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestController$1.onResponse(RestController.java:469)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestController$1.onResponse(RestController.java:463)
  at org.elasticsearch.security@9.0.0-SNAPSHOT/org.elasticsearch.xpack.security.rest.SecurityRestFilter.intercept(SecurityRestFilter.java:69)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:463)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:627)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:306)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:488)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:584)
  at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:461)
  at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.handlePipelinedRequest(Netty4HttpPipeliningHandler.java:169)
  at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:148)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  at io.netty.codec@4.1.115.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
  at io.netty.codec@4.1.115.Final/io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:120)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  at io.netty.codec@4.1.115.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
  at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpAggregator.channelRead(Netty4HttpAggregator.java:52)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  at io.netty.codec@4.1.115.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  at io.netty.codec@4.1.115.Final/io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
  at io.netty.codec@4.1.115.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  at io.netty.codec@4.1.115.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
  at io.netty.transport@4.1.115.Final/io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
  at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
  at io.netty.transport@4.1.115.Final/io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
  at io.netty.transport@4.1.115.Final/io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
  at io.netty.transport@4.1.115.Final/io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
  at io.netty.transport@4.1.115.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689)
  at io.netty.transport@4.1.115.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652)
  at io.netty.transport@4.1.115.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
  at io.netty.common@4.1.115.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
  at io.netty.common@4.1.115.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  at java.base/java.lang.Thread.run(Thread.java:1575)
"
```

**Comment by smalyshev** [comment]
The source of the issue seems to be in `groupClusterIndices` which does: 

```
if (isRemoteClusterClientEnabled == false) {
     assert remoteClusterNames.isEmpty() : remoteClusterNames;
     throw new IllegalArgumentException("node [" + nodeName + "] does not have the remote cluster client role enabled");
}
```
However if we just remove the check, we may end up being hit by https://github.com/elastic/elasticsearch/issues/115262 if there are no matching local indices, so it looks like these two needs to be fixed in concert or at least we should be aware of it when fixing that.

**Comment by benwtrent** [comment]
@smalyshev it still happens. 

To reproduce, assemble elasticsearch, adjust the node roles of your single node cluster to NOT include remote_cluster_client, then execute the API commands mentioned in the description.

My elasticsearch yaml. (security disabled for simple api testing locally).
```
node.roles: [data, master, ingest]
xpack.security.enabled: false
```

**Comment by javanna** [comment]
with the current semantics `*:anything`  refers to remote clusters only, and does not include targeting the local cluster. Would you rather expect your query to return empty results? I don't find the error particularly surprising, you are asking for remote indices while you are not allowed to do so? Maybe I am missing something.

**Comment by benwtrent** [comment]
@javanna its strange to me that there are NO remote clusters configured at all. So, why do we need remote cluster client at all?

I would rather it just look at the local cluster and not require remote cluster client

**Comment by javanna** [comment]
That's to do with the current semantics of `*:*` expanding only to remote clusters, as opposed to `*:*,*` expanding to remote as well as local. I would think it's surprising that a remote only expressions resolves to local clusters, regardless of whether there are remote clusters registered or not. The fact that there are or there aren't remote clusters registered should not affect the meaning of a given index expression?

**Comment by benwtrent** [comment]
> The fact that there are or there aren't remote clusters registered should not affect the meaning of a given index expression?

Interesting, you are saying that `*:*,*` should work even if there aren't remote clusters? Or that it should fail as well?

**Comment by javanna** [comment]
> Interesting, you are saying that *:*,* should work even if there aren't remote clusters? Or that it should fail as well?

It depends on how indices and cluster resolution is set up, via `ignore_unavailable` at the request level and `skip_unavailable` at the remote level.

**Comment by smalyshev** [comment]
If we use something like `prefix*:*` and there are no matching remotes, it's the empty result (absent permissions issues etc. of course). So it makes sense `*:...` should probably return empty result if there's no remotes? 

And I would assume if there's no remotes it makes sense that it shouldn't need any remote permissions/capacities? 

> Interesting, you are saying that `*:*,*` should work even if there aren't remote clusters? Or that it should fail as well?

I don't think it should fail, because `missing*:missing*,*` does not fail (if there are any local indices at all). Does this make sense?

**Comment by javanna** [comment]
> If we use something like prefix*:* and there are no matching remotes, it's the empty result (absent permissions issues etc. of course). So it makes sense *:... should probably return empty result if there's no remotes?

Has this behaviour changed recently? I honestly don't follow this discrepancy, how would `*:*` be treated differently from another remote cluster expression with wildcards?

**Comment by smalyshev** [comment]
@javanna I don't think it changed. This is a special case where you don't have permissions to access remote clusters, and you query kinda mentions remote clusters but not really because the remote-like pattern does not actually resolve to any real remote. It's not a huge deal that we return an error in this case, since if you don't have permissions to make remote queries, you don't have much business to use patterns that look like remotes anyway. But, strictly speaking, it would be more correct to return empty result here. I think it always been this way, just nobody paid too much attention to it because it's a very corner case.

**Comment by javanna** [comment]
I think it's debatable and it depends on user expectations, maybe the ordinary `ignore_unavailable` options and friends should be honored in this case too. Given that remote expressions can't possibly have a match on the local cluster, I could see both users expecting an error as well as users expecting empty results.
