### ISSUE TITLE
Failed to derive xcontent from org.elasticsearch.common.bytes.ChannelBufferBytesReference

### ISSUE THREAD

**Issue by alexanderkjall** [elastic/elasticsearch#11725]
I'm getting the following error when I'm trying to do a scan request.

This is the steps I have taken and the response I got:

    $ curl -XGET 'es1.di.no:9200/customer/_search?search_type=scan&scroll=2m&size=20' -d '{"query" : {"match_all" : {}}}'
    {"_scroll_id":"c2Nhbjs1OzEyNzkzODozSGdydm9mQlREdVYtNlFrS1FDSlBROzEyNzkzOTozSGdydm9mQlREdVYtNlFrS1FDSlBROzEyNzk0MjozSGdydm9mQlREdVYtNlFrS1FDSlBROzEyNzk0MTozSGdydm9mQlREdVYtNlFrS1FDSlBROzEyNzk0MDozSGdydm9mQlREdVYtNlFrS1FDSlBROzE7dG90YWxfaGl0czoxMTMyMzk2ODs=","took":85,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":11323968,"max_score":0.0,"hits":[]}}

    $ curl -XGET 'es1.di.no:9200/customer/_search?scroll=2m&size=20' -d 'c2Nhbjs1OzEyNzkzODozSGdydm9mQlREdVYtNlFrS1FDSlBROzEyNzkzOTozSGdydm9mQlREdVYtNlFrS1FDSlBROzEyNzk0MjozSGdydm9mQlREdVYtNlFrS1FDSlBROzEyNzk0MTozSGdydm9mQlREdVYtNlFrS1FDSlBROzEyNzk0MDozSGdydm9mQlREdVYtNlFrS1FDSlBROzE7dG90YWxfaGl0czoxMTMyMzk2ODs='
    {"error":"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[HN7qGhz6QmWNEvjSCMStJg][customer][0]: SearchParseException[[customer][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [_na_]]]; nested: ElasticsearchParseException[Failed to derive xcontent from org.elasticsearch.common.bytes.ChannelBufferBytesReference@47359ae3]; }{[HN7qGhz6QmWNEvjSCMStJg][customer][1]: SearchParseException[[customer][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [_na_]]]; nested: ElasticsearchParseException[Failed to derive xcontent from org.elasticsearch.common.bytes.ChannelBufferBytesReference@47359ae3]; }{[HN7qGhz6QmWNEvjSCMStJg][customer][2]: SearchParseException[[customer][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [_na_]]]; nested: ElasticsearchParseException[Failed to derive xcontent from org.elasticsearch.common.bytes.ChannelBufferBytesReference@47359ae3]; }{[HN7qGhz6QmWNEvjSCMStJg][customer][3]: SearchParseException[[customer][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [_na_]]]; nested: ElasticsearchParseException[Failed to derive xcontent from org.elasticsearch.common.bytes.ChannelBufferBytesReference@47359ae3]; }{[HN7qGhz6QmWNEvjSCMStJg][customer][4]: SearchParseException[[customer][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [_na_]]]; nested: ElasticsearchParseException[Failed to derive xcontent from org.elasticsearch.common.bytes.ChannelBufferBytesReference@47359ae3]; }]","status":400}

This the stacktrace i see on the server side (one per shard, I'll just paste one):

    [2015-06-17 16:15:11,922][DEBUG][action.search.type       ] [Prod-node 1] All shards failed for phase: [query]
    org.elasticsearch.search.SearchParseException: [customer][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [_na_]]
            at org.elasticsearch.search.SearchService.parseSource(SearchService.java:721)
            at org.elasticsearch.search.SearchService.createContext(SearchService.java:557)
            at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529)
            at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:291)
            at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
            at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
            at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
            at java.lang.Thread.run(Thread.java:745)
    Caused by: org.elasticsearch.ElasticsearchParseException: Failed to derive xcontent from org.elasticsearch.common.bytes.ChannelBufferBytesReference@47359ae3
            at org.elasticsearch.common.xcontent.XContentFactory.xContent(XContentFactory.java:259)
            at org.elasticsearch.search.SearchService.parseSource(SearchService.java:691)
            ... 9 more

I use elasticsearch version 1.5.2.

**Comment by imotov** [comment]
The second command should use special `/_search/scroll` endpoint and not the same search endpoint. Please see [Elasticsearch Reference](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html#search-request-scroll) for more information. By the way, https://discuss.elastic.co/ is much better place to ask questions like this - we are using github to keep track of bug reports and enhancement requests only. Since this issue doesn't look like a bug, I am going to close it.

**Comment by alexanderkjall** [comment]
Oh, I assumed that since it printed a stacktrace it was a bug, I'll make sure to read up more carefully next time.
