### ISSUE TITLE
Investigate synthetic source doc values error

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#117644]
As part of running an es|ql error the following error occurred:

```
Caused by: java.io.EOFException: read past EOF: MemorySegmentIndexInput(path=".../elasticsearch-9.0.0-SNAPSHOT/data/indices/5KLVwOQ3QNOfGg4zLqBt4w/0/index/_11.cfs") [slice=_11_ES87TSDB_0.dvd] [slice=docs]
	at org.apache.lucene.store.MemorySegmentIndexInput.readByte(MemorySegmentIndexInput.java:158) ~[lucene-core-10.0.0.jar:?]
	at org.apache.lucene.store.DataInput.readInt(DataInput.java:97) ~[lucene-core-10.0.0.jar:?]
	at org.apache.lucene.store.MemorySegmentIndexInput.readInt(MemorySegmentIndexInput.java:273) ~[lucene-core-10.0.0.jar:?]
	at org.apache.lucene.store.DataInput.readLong(DataInput.java:145) ~[lucene-core-10.0.0.jar:?]
	at org.apache.lucene.store.MemorySegmentIndexInput.readLong(MemorySegmentIndexInput.java:300) ~[lucene-core-10.0.0.jar:?]
	at org.apache.lucene.codecs.lucene90.IndexedDISI$Method$2.advanceExactWithinBlock(IndexedDISI.java:692) ~[lucene-core-10.0.0.jar:?]
	at org.apache.lucene.codecs.lucene90.IndexedDISI.advanceExact(IndexedDISI.java:504) ~[lucene-core-10.0.0.jar:?]
	at org.elasticsearch.index.codec.tsdb.ES87TSDBDocValuesProducer$9.advanceExact(ES87TSDBDocValuesProducer.java:1052) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.codec.tsdb.ES87TSDBDocValuesProducer$5.advanceExact(ES87TSDBDocValuesProducer.java:299) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.apache.lucene.index.SingletonSortedSetDocValues.advanceExact(SingletonSortedSetDocValues.java:83) ~[lucene-core-10.0.0.jar:?]
	at org.elasticsearch.index.mapper.SortedSetDocValuesSyntheticFieldLoaderLayer$ImmediateDocValuesLoader.advanceToDoc(SortedSetDocValuesSyntheticFieldLoaderLayer.java:116) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.mapper.CompositeSyntheticFieldLoader.lambda$docValuesLoader$1(CompositeSyntheticFieldLoader.java:79) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.mapper.ObjectMapper$SyntheticSourceFieldLoader$ObjectDocValuesLoader.advanceToDoc(ObjectMapper.java:939) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.mapper.ObjectMapper$SyntheticSourceFieldLoader$ObjectDocValuesLoader.advanceToDoc(ObjectMapper.java:939) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.mapper.ObjectMapper$SyntheticSourceFieldLoader$ObjectDocValuesLoader.advanceToDoc(ObjectMapper.java:939) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.mapper.SourceLoader$Synthetic$SyntheticLeaf.write(SourceLoader.java:210) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.mapper.SourceLoader$Synthetic$SyntheticLeaf.source(SourceLoader.java:181) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.mapper.SourceLoader$Synthetic$LeafWithMetrics.source(SourceLoader.java:146) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.search.lookup.SyntheticSourceProvider$SyntheticSourceLeafLoader.getSource(SyntheticSourceProvider.java:58) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.search.lookup.SyntheticSourceProvider.getSource(SyntheticSourceProvider.java:42) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.search.lookup.LeafSearchLookup.lambda$new$0(LeafSearchLookup.java:40) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	... 19 more
```

The es|ql part of the stack trace:

```
[2024-11-14T03:02:47,764][WARN ][o.e.x.e.a.EsqlResponseListener] [elasticsearch-1] Request failed with status [INTERNAL_SERVER_ERROR]: 
org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: unchecked_i_o_exception: Couldn't load source
	at org.elasticsearch.search.lookup.LeafSearchLookup.lambda$new$0(LeafSearchLookup.java:42) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.script.AbstractFieldScript.extractFromSource(AbstractFieldScript.java:107) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.script.AbstractFieldScript.emitFromSource(AbstractFieldScript.java:127) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.script.LongFieldScript$1$1.execute(LongFieldScript.java:29) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.script.AbstractFieldScript.runForDoc(AbstractFieldScript.java:159) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.mapper.LongScriptBlockDocValuesReader.read(LongScriptBlockDocValuesReader.java:69) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.index.mapper.LongScriptBlockDocValuesReader.read(LongScriptBlockDocValuesReader.java:56) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.compute.lucene.ValuesSourceReaderOperator.loadFromSingleLeaf(ValuesSourceReaderOperator.java:230) ~[?:?]
	at org.elasticsearch.compute.lucene.ValuesSourceReaderOperator.process(ValuesSourceReaderOperator.java:143) ~[?:?]
	at org.elasticsearch.compute.operator.AbstractPageMappingOperator.getOutput(AbstractPageMappingOperator.java:76) ~[?:?]
	at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:258) ~[?:?]
	at org.elasticsearch.compute.operator.Driver.run(Driver.java:189) ~[?:?]
	at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:378) ~[?:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27) ~[elasticsearch-9.0.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

[full-stacktrace.txt](https://github.com/user-attachments/files/17957949/stacktrace.txt)

Queries like this fail

```
POST /_query
{
  "query": "FROM .ds-logs-nginx.error-default-2024.11.13-000001 | EVAL compression = rally.doc_size::DOUBLE / rally.message_size | STATS AVG(compression)"
}
```

**Comment by martijnvg** [comment]
The main reason that the `EOFException` occurs is that `LeafSearchLookup` instance gets reused between `BlockDocValuesReader` instances. In the above query there are two `BlockDocValuesReader` instances using the `LeafSeachLookup`. When `ValuesSourceReaderOperator` reads on columnar fashion (via `loadFromSingleLeaf()` or loadFromSingleLeafUnsorted() methods) then ranges of docids get processed multiple times by same  `LeafSearchLookup` instance. For the synthetic source loader this is an issue because as part of synthesizing source doc value iterators then can advance backwards. This violates `DocValuesIterator#advanceExact(...)` and `DocIdSetIterator#advance(...)` contracts and then at some point during the executing of the query `EOFException` occur deep in the codec.


This is fixable. For example we could enforce different `SearchLookup` instances between fields or force a row oriented execution fashion.
