### ISSUE TITLE
OutOfMemoryError during jackson serialization when bulk indexing

### ISSUE THREAD

**Issue by l15k4** [elastic/elasticsearch#11761]
ES 1.6, -Xmx2024 (512BM usually sufficient), java client with elastic4s
I cannot bulk index 800 documents of constant size where single document looks like this : 
```
foo -> "c0004"
bar -> "10764182"
baz -> "92fde3ff-a659-408c-8b5c-1e7465447234"
xyz -> "123456789098765432345678987654324567"
```

CPU immediately at 100% until it fails on OOME on that single bulk. It is less than 350 characters which is not even 1MB of raw text... when I decrease 800 to 400 documents it is done in a few milliseconds. There must be some sort of bug in ES json serialization...

```
java.lang.OutOfMemoryError: Java heap space
	at org.elasticsearch.common.jackson.core.util.BufferRecycler.calloc(BufferRecycler.java:156)
	at org.elasticsearch.common.jackson.core.util.BufferRecycler.allocCharBuffer(BufferRecycler.java:124)
	at org.elasticsearch.common.jackson.core.util.BufferRecycler.allocCharBuffer(BufferRecycler.java:114)
	at org.elasticsearch.common.jackson.core.io.IOContext.allocConcatBuffer(IOContext.java:186)
	at org.elasticsearch.common.jackson.core.json.UTF8JsonGenerator.<init>(UTF8JsonGenerator.java:127)
	at org.elasticsearch.common.jackson.core.JsonFactory._createUTF8Generator(JsonFactory.java:1284)
	at org.elasticsearch.common.jackson.core.JsonFactory.createGenerator(JsonFactory.java:1016)
	at org.elasticsearch.common.xcontent.json.JsonXContent.createGenerator(JsonXContent.java:74)
	at org.elasticsearch.common.xcontent.json.JsonXContent.createGenerator(JsonXContent.java:80)
	at org.elasticsearch.common.xcontent.XContentBuilder.<init>(XContentBuilder.java:109)
	at org.elasticsearch.common.xcontent.XContentBuilder.<init>(XContentBuilder.java:99)
	at org.elasticsearch.common.xcontent.XContentBuilder.builder(XContentBuilder.java:77)
	at org.elasticsearch.common.xcontent.json.JsonXContent.contentBuilder(JsonXContent.java:40)
	at org.elasticsearch.common.xcontent.XContentFactory.contentBuilder(XContentFactory.java:122)
	at org.elasticsearch.common.xcontent.XContentFactory.jsonBuilder(XContentFactory.java:49)
	at com.sksamuel.elastic4s.IndexDefinition._fieldsAsXContent(IndexDsl.scala:50)
	at com.sksamuel.elastic4s.IndexDefinition.build(IndexDsl.scala:44)
	at com.sksamuel.elastic4s.BulkDefinition$$anonfun$1.apply(bulk.scala:82)
	at com.sksamuel.elastic4s.BulkDefinition$$anonfun$1.apply(bulk.scala:81)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.sksamuel.elastic4s.BulkDefinition.<init>(bulk.scala:81)
	at com.sksamuel.elastic4s.BulkDsl$class.bulk(bulk.scala:18)
	at com.sksamuel.elastic4s.ElasticDsl$.bulk(ElasticDsl.scala:456)
```

**Comment by l15k4** [comment]
Ups, my apologies. It looks I underestimated scroll page size. 
I have 100 indices on 3 nodes using 5 shards and I'm scanning  all the indices. I thought that request can hit max 5 shards, so when I set page size 200, it would be 1000 max. But it looks like the bulks have like 10 000 documents which is 10MB of text.

**Comment by clintongormley** [comment]
thanks for letting us know @l15k4

**Comment by l15k4** [comment]
@clintongormley what is the upper bound when scrolling 100 indices on this : 
```

**Comment by clintongormley** [comment]
@l15k4 you get back a max of  `size * number_of_shards`
