### ISSUE TITLE
GroovyScriptExecutionException: NumberFormatException[null]

### ISSUE THREAD

**Issue by gkozyryatskyy** [elastic/elasticsearch#11774]
Hello.
I have a mapping like this.

    {  
        "user":{  
           "properties":{  
              "mCount":{  
                 "type":"integer",
                 "store":true,
                 "doc_values":true
              }
           }
        },
        "media":{  
           "_parent":{  
              "type":"user"
           },
           "_routing":{  
              "required":true
           },
           "properties":{  
              "location":{  
                 "type":"geo_point",
                 "doc_values":true,
                 "lat_lon":true,
                 "geohash":true,
                 "geohash_prefix":true
              }
           }
        }
     }
      
I run this query 

    {
        "size" : 10,
        "query" : {
          "has_child" : {
            "query" : {
              "filtered" : {
                "filter" : {
                  "geo_bbox" : {
                    "location" : {
                      "top_left" : [ -74.1, 41.73 ],
                      "bottom_right" : [ -73.99, 40.717 ]
                    }
                  }
                }
              }
            },
            "child_type" : "media",
            "score_type" : "sum"
          }
        },
        "fields" : "mCount",
        "sort" : [ {
          "_script" : {
            "script" : "_score  / doc['mCount'].value",
            "type" : "number",
            "reverse" : true
          }
        } ],
        "track_scores" : true
      }

and got 

    query[filtered(ChildrenQuery[min(0) max(2147483647)of media/user](filtered(ConstantScore(GeoBoundingBoxFilter(location, [41.73, -74.1], [40.717, -73.99])))->cache(_type:media)))->cache(_type:user)],from[0],size[10],sort[<custom:"_script": org.elasticsearch.search.sort.ScriptSortParser$2@7144a535>!]: Query Failed [Failed to execute main query]
            at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:163)
            at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:289)
            at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:300)
            at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
            at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
            at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)
        Caused by: org.elasticsearch.script.groovy.GroovyScriptExecutionException: NumberFormatException[null]
            at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript.run(GroovyScriptEngineService.java:278)
            at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript.runAsDouble(GroovyScriptEngineService.java:294)
            at org.elasticsearch.search.sort.ScriptSortParser$2$1.get(ScriptSortParser.java:177)
            at org.elasticsearch.index.fielddata.fieldcomparator.DoubleValuesComparatorSource$1$1.get(DoubleValuesComparatorSource.java:87)
            at org.apache.lucene.search.FieldComparator$DoubleComparator.copy(FieldComparator.java:367)
            at org.apache.lucene.search.TopFieldCollector$OutOfOrderOneComparatorScoringMaxScoreCollector.collect(TopFieldCollector.java:363)
            at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:193)
            at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:163)
            at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:35)
            at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:621)
            at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:191)
            at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:581)
            at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:533)
            at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:510)
            at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:345)
            at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:150)
            ... 8 more

when i replace script in scriptsort to ```"script" : "_score  * (1 / doc['mCount'].value")"``` Im also get ```NumberFormatException[null]``` , but when i replace script to ```"script" : "_score  * (1.0 / doc['mCount'].value")"``` it is working fine. And i get 

    {
        "took" : 2,
        "timed_out" : false,
        "_shards" : {
          "total" : 5,
          "successful" : 5,
          "failed" : 0
        },
        "hits" : {
          "total" : 14,
          "max_score" : 317.0,
          "hits" : [ {
            "_index" : "qwe",
            "_type" : "user",
            "_id" : "1433",
            "_score" : 317.0,
            "fields" : {
              "mCount" : [ 2562 ]
            },
            "sort" : [ 0.12373145979703357 ]
          }, {
            "_index" : "qwe",
            "_type" : "user",
            "_id" : "1615",
            "_score" : 299.0,
            "fields" : {
              "mCount" : [ 6283 ]
            },
            "sort" : [ 0.04758873149769219 ]
          }, {
            "_index" : "qwe",
            "_type" : "user",
            "_id" : "49",
            "_score" : 56.0,
            "fields" : {
              "mCount" : [ 1327 ]
            },
            "sort" : [ 0.042200452147701586 ]
          }, {
            "_index" : "qwe",
            "_type" : "user",
            "_id" : "3264",
            "_score" : 64.0,
            "fields" : {
              "mCount" : [ 3210 ]
            },
            "sort" : [ 0.019937694704049845 ]
          }, {
            "_index" : "qwe",
            "_type" : "user",
            "_id" : "2808",
            "_score" : 15.0,
            "fields" : {
              "mCount" : [ 911 ]
            },
            "sort" : [ 0.01646542261251372 ]
          }, {
            "_index" : "qwe",
            "_type" : "user",
            "_id" : "1004",
            "_score" : 11.0,
            "fields" : {
              "mCount" : [ 760 ]
            },
            "sort" : [ 0.014473684210526316 ]
          }, {
            "_index" : "qwe",
            "_type" : "user",
            "_id" : "3096",
            "_score" : 9.0,
            "fields" : {
              "mCount" : [ 638 ]
            },
            "sort" : [ 0.014106583072100312 ]
          }, {
            "_index" : "qwe",
            "_type" : "user",
            "_id" : "6",
            "_score" : 7.0,
            "fields" : {
              "mCount" : [ 995 ]
            },
            "sort" : [ 0.007035175879396985 ]
          }, {
            "_index" : "qwe",
            "_type" : "user",
            "_id" : "33",
            "_score" : 10.0,
            "fields" : {
              "mCount" : [ 1460 ]
            },
            "sort" : [ 0.00684931506849315 ]
          }, {
            "_index" : "qwe",
            "_type" : "user",
            "_id" : "4695",
            "_score" : 5.0,
            "fields" : {
              "mCount" : [ 934 ]
            },
            "sort" : [ 0.005353319057815846 ]
          } ]
        }
      }

Why it is so? Why i can not use just ```"script" : "_score  / doc['mCount'].value"``` ?

**Comment by askaliuk** [comment]
Having the same problem. Debugging now. Let me know if you make any progress.
My assumption: `doc['mCount'].value` is something, which we don't expect.

**Comment by gkozyryatskyy** [comment]
This exception throws just with division operator.
For exemple ```"script" : "_score * doc['mCount'].value"``` working fine.
Like i sad ```"script" : "_score / doc['mCount'].value"``` and ```"script" : "_score * (1 / doc['mCount'].value")"``` do not working, But "script" : "_score * (1.0 / doc['mCount'].value")" working fine.
Thats why i think the problem is cast from int to double, or from string to double.
May be elastic can't represent _score as double for division. Like it can't divide ```1 / doc['mCount'].value``` but ```1.0 / doc['mCount'].value``` works fine.

**Comment by clintongormley** [comment]
@jpountz could we cast integers in script scoring to floats to avoid this issue?

**Comment by askaliuk** [comment]
@gkozyryatskyy 

This code:
```
termInfo=_index['text'].get('something', _POSITIONS);
for(pos in termInfo){
     return 1 / (pos.position.toInteger() + 1) * doc['somefield'].value;
};
```

Works fine for me by some reason.

**Comment by clintongormley** [comment]
I think we've just got to go with using explicit floats.  Closing
