### ISSUE TITLE
Negative longs unsupported error in data stream stats

### ISSUE THREAD

**Issue by dennis-trapp** [elastic/elasticsearch#117911]
### Elasticsearch Version

8.15.0

### Java Version

_bundled_

### OS Version

Ubuntu 22.04.1

### Problem Description

Getting "Negative longs unsupported" error when querying stats for multiple data streams.

There is no error when querying stats for exact data stream name.

### Steps to Reproduce

`GET _data_stream/logs-*-xxx/_stats`

### Logs (if relevant)

```
{
  "_shards": {
    "total": 64,
    "successful": 31,
    "failed": 33,
    "failures": [
      {
        "shard": 0,
        "index": ".ds-logs-xxx-2024.11.21-000014",
        "status": "INTERNAL_SERVER_ERROR",
        "reason": {
          "type": "failed_node_exception",
          "reason": "Failed node [9ONhA0lVRJes3mGA8mfUUw]",
          "node_id": "9ONhA0lVRJes3mGA8mfUUw",
          "caused_by": {
            "type": "illegal_state_exception",
            "reason": "Negative longs unsupported, use writeLong or writeZLong for negative numbers [-62135596800000]"
          }
        }
      },
```

**Comment by dakrone** [comment]
Can you re-run the request with `error_trace=true`? That should spit out the entire stack trace.

**Comment by dennis-trapp** [comment]
No additional info in response body, but here's what I saw in server logs:


error.message: `Negative longs unsupported, use writeLong or writeZLong for negative numbers [-62135596800000]`
error.type: `java.lang.IllegalStateException`
log.logger: `org.elasticsearch.transport.OutboundHandler`
log.level: `WARN`
message: `failed to serialize outbound message [Response{1788022020}{false}{false}{false}{class org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$NodeResponse}]`
error.stack_trace:
```
java.lang.IllegalStateException: Negative longs unsupported, use writeLong or writeZLong for negative numbers [-62135596800000]
	at org.elasticsearch.server@8.15.0/org.elasticsearch.common.io.stream.StreamOutput.writeVLong(StreamOutput.java:271)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.datastreams.DataStreamsStatsAction$DataStreamShardStats.writeTo(DataStreamsStatsAction.java:263)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.common.io.stream.StreamOutput.writeOptionalWriteable(StreamOutput.java:1010)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.common.io.stream.StreamOutput.writeCollection(StreamOutput.java:1090)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$NodeResponse.writeTo(TransportBroadcastByNodeAction.java:601)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.transport.OutboundMessage.serialize(OutboundMessage.java:71)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.transport.OutboundHandler.sendMessage(OutboundHandler.java:214)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.transport.OutboundHandler.sendResponse(OutboundHandler.java:151)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.transport.TcpTransportChannel.sendResponse(TcpTransportChannel.java:57)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:35)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:32)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:19)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:386)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:306)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:209)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:174)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.CancellableFanOut$SubtasksCompletionHandler.run(CancellableFanOut.java:201)
	at org.elasticsearch.base@8.15.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)
	at org.elasticsearch.base@8.15.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.CancellableFanOut.run(CancellableFanOut.java:134)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction.executeAsDataNode(TransportBroadcastByNodeAction.java:461)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.messageReceived(TransportBroadcastByNodeAction.java:395)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.messageReceived(TransportBroadcastByNodeAction.java:392)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:579)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(SecurityServerTransportInterceptor.java:632)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$3.onResponse(SecurityServerTransportInterceptor.java:621)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:640)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:79)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.interceptor.ValidateRequestInterceptor.intercept(ValidateRequestInterceptor.java:20)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:79)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.interceptor.UpdateRequestInterceptor.intercept(UpdateRequestInterceptor.java:27)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.interceptor.IndicesAliasesRequestInterceptor.intercept(IndicesAliasesRequestInterceptor.java:124)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.interceptor.DlsFlsLicenseRequestInterceptor.intercept(DlsFlsLicenseRequestInterceptor.java:106)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.interceptor.SearchRequestCacheDisablingInterceptor.intercept(SearchRequestCacheDisablingInterceptor.java:53)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:79)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.interceptor.SearchRequestInterceptor.intercept(SearchRequestInterceptor.java:20)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.interceptor.ResizeRequestInterceptor.intercept(ResizeRequestInterceptor.java:98)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.interceptor.BulkShardRequestInterceptor.intercept(BulkShardRequestInterceptor.java:85)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:638)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:634)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:79)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.interceptor.ShardSearchRequestInterceptor.intercept(ShardSearchRequestInterceptor.java:23)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService.runRequestInterceptors(AuthorizationService.java:634)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService.handleIndexActionAuthorizationResult(AuthorizationService.java:619)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$13(AuthorizationService.java:517)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:1033)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:999)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.RBACEngine.lambda$authorizeIndexAction$3(RBACEngine.java:421)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:245)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:386)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:306)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:209)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:174)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService$CachingAsyncSupplier.getAsync(AuthorizationService.java:1079)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.RBACEngine.authorizeIndexAction(RBACEngine.java:389)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeAction(AuthorizationService.java:510)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService.maybeAuthorizeRunAs(AuthorizationService.java:442)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorize$3(AuthorizationService.java:329)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:249)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.RBACEngine.lambda$resolveAuthorizationInfo$0(RBACEngine.java:155)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:245)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.lambda$getRoles$4(CompositeRolesStore.java:192)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:245)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.lambda$getRole$5(CompositeRolesStore.java:210)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:245)
	at org.elasticsearch.xcore@8.15.0/org.elasticsearch.xpack.core.security.authz.store.RoleReferenceIntersection.lambda$buildRole$0(RoleReferenceIntersection.java:49)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:245)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.support.GroupedActionListener.onResponse(GroupedActionListener.java:56)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.buildRoleFromRoleReference(CompositeRolesStore.java:290)
	at org.elasticsearch.xcore@8.15.0/org.elasticsearch.xpack.core.security.authz.store.RoleReferenceIntersection.lambda$buildRole$1(RoleReferenceIntersection.java:53)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.elasticsearch.xcore@8.15.0/org.elasticsearch.xpack.core.security.authz.store.RoleReferenceIntersection.buildRole(RoleReferenceIntersection.java:53)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRole(CompositeRolesStore.java:208)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRoles(CompositeRolesStore.java:185)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.RBACEngine.resolveAuthorizationInfo(RBACEngine.java:151)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:345)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.transport.ServerTransportFilter.lambda$inbound$1(ServerTransportFilter.java:114)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:245)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authc.AuthenticatorChain.authenticate(AuthenticatorChain.java:93)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:264)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:201)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.transport.ServerTransportFilter.authenticate(ServerTransportFilter.java:127)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.transport.ServerTransportFilter.inbound(ServerTransportFilter.java:105)
	at org.elasticsearch.security@8.15.0/org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:643)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.transport.InboundHandler.doHandleRequest(InboundHandler.java:287)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:300)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
	at org.elasticsearch.server@8.15.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```
