### ISSUE TITLE
Server error while parsing ESQL query

### ISSUE THREAD

**Issue by lkts** [elastic/elasticsearch#119025]
### Elasticsearch Version

9.0

### Java Version

_bundled_

### OS Version

all

### Problem Description

The following error was observed. Unfortunately the query that leads to this is not known (the author was experimenting and does not remember what it was), it is possible that it is an invalid query. In that case this error should not be a server error but a client error.

```
java.util.EmptyStackException
at org.antlr.v4.runtime.Lexer.popMode(Lexer.java:192)
at org.antlr.v4.runtime.atn.LexerPopModeAction.execute(LexerPopModeAction.java:58)
at org.antlr.v4.runtime.atn.LexerActionExecutor.execute(LexerActionExecutor.java:168)
at org.antlr.v4.runtime.atn.LexerATNSimulator.accept(LexerATNSimulator.java:366)
at org.antlr.v4.runtime.atn.LexerATNSimulator.failOrAccept(LexerATNSimulator.java:299)
at org.antlr.v4.runtime.atn.LexerATNSimulator.execATN(LexerATNSimulator.java:230)
at org.antlr.v4.runtime.atn.LexerATNSimulator.match(LexerATNSimulator.java:114)
at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:141)
at org.elasticsearch.xpack.esql.parser.EsqlParser$ParametrizedTokenSource.nextToken(EsqlParser.java:169)
at org.antlr.v4.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:169)
at org.antlr.v4.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:152)
at org.antlr.v4.runtime.BufferedTokenStream.consume(BufferedTokenStream.java:136)
at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:515)
at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:371)
at org.elasticsearch.xpack.esql.parser.EsqlBaseParser.booleanExpression(EsqlBaseParser.java:912)
at org.elasticsearch.xpack.esql.parser.EsqlBaseParser.whereCommand(EsqlBaseParser.java:695)
at org.elasticsearch.xpack.esql.parser.EsqlBaseParser.processingCommand(EsqlBaseParser.java:547)
at org.elasticsearch.xpack.esql.parser.EsqlBaseParser.query(EsqlBaseParser.java:347)
at org.elasticsearch.xpack.esql.parser.EsqlBaseParser.singleStatement(EsqlBaseParser.java:230)
at org.elasticsearch.xpack.esql.parser.EsqlParser.invokeParser(EsqlParser.java:100)
at org.elasticsearch.xpack.esql.parser.EsqlParser.createStatement(EsqlParser.java:63)
at org.elasticsearch.xpack.esql.session.EsqlSession.parse(EsqlSession.java:269)
at org.elasticsearch.xpack.esql.session.EsqlSession.execute(EsqlSession.java:154)
at org.elasticsearch.xpack.esql.execution.PlanExecutor.esql(PlanExecutor.java:80)
at org.elasticsearch.xpack.esql.plugin.TransportEsqlQueryAction.innerExecute(TransportEsqlQueryAction.java:186)
at org.elasticsearch.xpack.esql.plugin.TransportEsqlQueryAction.lambda$execute$1(TransportEsqlQueryAction.java:156)
at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListener.run(ActionListener.java:452)
at org.elasticsearch.xpack.esql.plugin.TransportEsqlQueryAction.execute(TransportEsqlQueryAction.java:156)
at org.elasticsearch.xpack.esql.plugin.TransportEsqlQueryAction.execute(TransportEsqlQueryAction.java:56)
at org.elasticsearch.xpack.esql.core.async.AsyncTaskManagementService.asyncExecute(AsyncTaskManagementService.java:188)
at org.elasticsearch.xpack.esql.plugin.TransportEsqlQueryAction.doExecuteForked(TransportEsqlQueryAction.java:140)
at org.elasticsearch.xpack.esql.plugin.TransportEsqlQueryAction.lambda$doExecute$0(TransportEsqlQueryAction.java:132)
at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:101)
at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34)
at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)
at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
```

### Steps to Reproduce

N/A

**Comment by luigidellaquila** [comment]
I managed to reproduce this problem, it's just due to extra parentheses in the query, eg.

```
row a = 1 | where a < 2 )
```

We should return a ParsingException and a better error message, but the query is invalid anyway

**Comment by ChrisHegarty** [comment]
Additionally, `FROM test | eval x = [1, 2, 3]]`

**Comment by costin** [comment]
Invalid stack popping is not properly handled by ANTLR, despite the issue being reported years ago https://github.com/antlr/antlr4/issues/2006 . There is also a [PR for it](https://github.com/antlr/antlr4/pull/3317) but it didn't get merged suggesting the problem is a bit more complicated.
Catching the exception seems the best way forward atm.
