### ISSUE TITLE
NoSuchNodeException during startup

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#11923]
When adding a new node to the cluster, master throws a series of NoSuchNodeException exceptions until the new node is ready:

    [2015-06-29 20:14:27,958][WARN ][gateway                  ] [foo] [t][3]: failed to list shard for shard_store on node [g51KTc9wQZWlLiwiYFkcgg]
    FailedNodeException[Failed node [g51KTc9wQZWlLiwiYFkcgg]]; nested: NoSuchNodeException[No such node [g51KTc9wQZWlLiwiYFkcgg]];
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onFailure(TransportNodesAction.java:179)
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.start(TransportNodesAction.java:131)
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$100(TransportNodesAction.java:91)
        at org.elasticsearch.action.support.nodes.TransportNodesAction.doExecute(TransportNodesAction.java:65)
        at org.elasticsearch.action.support.nodes.TransportNodesAction.doExecute(TransportNodesAction.java:42)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:63)
        at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.list(TransportNodesListShardStoreMetaData.java:82)
        at org.elasticsearch.gateway.AsyncShardFetch.asyncFetch(AsyncShardFetch.java:267)
        at org.elasticsearch.gateway.AsyncShardFetch.fetchData(AsyncShardFetch.java:117)
        at org.elasticsearch.gateway.GatewayAllocator.allocateUnassigned(GatewayAllocator.java:406)
        at org.elasticsearch.cluster.routing.allocation.allocator.ShardsAllocators.allocateUnassigned(ShardsAllocators.java:72)
        at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:179)
        at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:159)
        at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:145)
        at org.elasticsearch.discovery.zen.ZenDiscovery$11.execute(ZenDiscovery.java:937)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:378)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:209)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:179)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)
    Caused by: NoSuchNodeException[No such node [g51KTc9wQZWlLiwiYFkcgg]]
        ... 20 more

**Comment by s1monw** [comment]
@kimchy can you take a look at this?

**Comment by kimchy** [comment]
I think I know what happens, now that we reroute within the same cluster state when we add nodes, it means that they will be part of the cluster state being built. When we go and list the started shards, we use the existing cluster state that hasn't yet been updated to find the relevant nodes, and they will not be there since they are just being added... .

**Comment by bleskes** [comment]
closed with #11960
