### ISSUE TITLE
Bucket script pipeline aggregation under a single bucket aggregation produces a class cast exception

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#119343]
Adding a [bucket script pipeline aggregation ](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-bucket-script-aggregation.html)under a single buckets aggregation like the filter aggregation results on a class class exception, for example:

```
POST test/_doc 
{
  "field" : "foo"
}

GET test/_search 
{
  "size": 0,
  "aggs": {
    "single_bucket": {
      "filter": {
        "exists": {
          "field": "field.keyword"
        }
      },
      "aggs": {
        "value" : {
          "cardinality": {
            "field": "field.keyword"
          }
        },
        "bucket_script": {
          "bucket_script": {
            "buckets_path": {
              "card" : "value"
            },
            "script": "params.card + 1"
          }
        }
      }
    }
  }
}
```
Output:

```
{
  "error": {
    "root_cause": [],
    "type": "search_phase_execution_exception",
    "reason": "",
    "phase": "rank-feature",
    "grouped": true,
    "failed_shards": [],
    "caused_by": {
      "type": "class_cast_exception",
      "reason": "class org.elasticsearch.search.aggregations.bucket.filter.InternalFilter cannot be cast to class org.elasticsearch.search.aggregations.InternalMultiBucketAggregation (org.elasticsearch.search.aggregations.bucket.filter.InternalFilter and org.elasticsearch.search.aggregations.InternalMultiBucketAggregation are in module org.elasticsearch.server@8.17.0 of loader 'app')"
    }
  },
  "status": 500
}
```

**Comment by smalyshev** [comment]
Seen this live with this backtrace: 
```
"Failed to execute phase [fetch], 
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:644)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction.onPhaseFailure(SearchQueryThenFetchAsyncAction.java:79)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.search.FetchSearchPhase$1.onFailure(FetchSearchPhase.java:88)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:29)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1044)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
	at java.base/java.lang.Thread.run(Thread.java:1447)
Caused by: java.lang.ClassCastException: class org.elasticsearch.search.aggregations.bucket.filter.InternalFilter cannot be cast to class org.elasticsearch.search.aggregations.InternalMultiBucketAggregation (org.elasticsearch.search.aggregations.bucket.filter.InternalFilter and org.elasticsearch.search.aggregations.InternalMultiBucketAggregation are in module org.elasticsearch.server@9.1.0 of loader 'app')
	at org.elasticsearch.server@9.1.0/org.elasticsearch.search.aggregations.pipeline.BucketScriptPipelineAggregator.reduce(BucketScriptPipelineAggregator.java:52)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.search.aggregations.InternalAggregation.reducePipelines(InternalAggregation.java:119)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.search.aggregations.bucket.InternalSingleBucketAggregation.reducePipelines(InternalSingleBucketAggregation.java:142)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.search.aggregations.InternalAggregations.lambda$maybeExecuteFinalReduce$0(InternalAggregations.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:727)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.search.aggregations.InternalAggregations.maybeExecuteFinalReduce(InternalAggregations.java:198)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.search.aggregations.InternalAggregations.topLevelReduce(InternalAggregations.java:187)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.search.QueryPhaseResultConsumer.aggregate(QueryPhaseResultConsumer.java:417)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.search.QueryPhaseResultConsumer.reduce(QueryPhaseResultConsumer.java:249)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:96)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:83)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	... 6 more
"
```

**Comment by ivancea** [comment]
Fixed in https://github.com/elastic/elasticsearch/pull/132320

It basically changed the error 500 to an error 400, and added tests
