### ISSUE TITLE
Issue with rank_features field when updating document

### ISSUE THREAD

**Issue by vinodkotagiri** [elastic/elasticsearch#119381]
i have an index with a field rank_features, and i ingested documents to that index, when i am tring to update any field other than the field with rank_feature, I am getting this error 
Error updating documents: ResponseError: document_parsing_exception: [document_parsing_exception] Reason: [1:2658] failed to parse: [rank_features] fields do not support indexing multiple values for the same rank feature [ml_text.tokens.copyright] in the same document
    at onBody (/app/node_modules/@elastic/elasticsearch/lib/Transport.js:375:23)
    at IncomingMessage.onEnd (/app/node_modules/@elastic/elasticsearch/lib/Transport.js:299:11)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  meta: {
    body: { error: [Object], status: 400 },
    statusCode: 400,
    headers: {
      'content-length': '659',
      'content-type': 'application/json',
      'x-cloud-request-id': 'HLxoyyIoRRiyz2T7eif1Rw',
      'x-elastic-product': 'Elasticsearch',
      'x-found-handling-cluster': '10d5d33851874436885b4939d3b5212d',
      'x-found-handling-instance': 'instance-0000000005',
      date: 'Tue, 24 Dec 2024 08:42:01 GMT'
    },
    meta: {
      context: null,
      request: [Object],
      name: 'elasticsearch-js',
      connection: [Object],
      attempts: 0,
      aborted: false
    }
  }
}
null

But when i change the rank_features to sparse_vector it is woking fine.

**Comment by john-wagster** [comment]
Closing for now; please feel free to reopen if you are able to provide more information.
