### ISSUE TITLE
StackOverflowError when a SearchParseException is thrown

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#11994]
The following request produces a SearchParseException because there is no aggregator of type `foo`:
```
GET _search
{
  "aggs": {
    "foo": {
      "bar": {}
    }
  }
}
```

On the current master this is masked by a StackOverflowError (I presume as the stack trace fall off the top of the console buffer) will the follow (part) stacktrace showing the infinite loop:

```
	at org.elasticsearch.ElasticsearchException.toXContent(ElasticsearchException.java:277)
	at org.elasticsearch.ElasticsearchException.toXContent(ElasticsearchException.java:312)
	at org.elasticsearch.ElasticsearchException.toXContent(ElasticsearchException.java:277)
	at org.elasticsearch.ElasticsearchException.toXContent(ElasticsearchException.java:312)
	at org.elasticsearch.ElasticsearchException.toXContent(ElasticsearchException.java:277)
	at org.elasticsearch.ElasticsearchException.toXContent(ElasticsearchException.java:312)
	at org.elasticsearch.ElasticsearchException.toXContent(ElasticsearchException.java:277)
	at org.elasticsearch.ElasticsearchException.toXContent(ElasticsearchException.java:312)
	at org.elasticsearch.ElasticsearchException.toXContent(ElasticsearchException.java:277)
	at org.elasticsearch.ElasticsearchException.toXContent(ElasticsearchException.java:312)
	at org.elasticsearch.ElasticsearchException.toXContent(ElasticsearchException.java:277)
	at org.elasticsearch.ElasticsearchException.toXContent(ElasticsearchException.java:312)
	at org.elasticsearch.ElasticsearchException.toXContent(ElasticsearchException.java:277)
```

**Comment by colings86** [comment]
SearchParseException extends SearchException which in turn extends ElasticsearchException and implements ElasticsearchWrapperException. Any exception which extends ElasticsearchException and implements ElasticsearchWrapperExceptionwill suffer this issue

**Comment by colings86** [comment]
From what I can see, the following Exceptions are affected:
* BroadcastShardOperationFailedException
* IndexCreationException
* PercolateException
* RecoverFilesRecoveryException
* RemoteTransportException
* SearchException
* SearchContextException
* SendRequestTransportException
