### ISSUE TITLE
[build] cloud-aws doesn't register s3 repos anymore

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#12034]
Reported in https://github.com/elastic/elasticsearch/issues/11647#issuecomment-118523861

> btw, I think you broke some plugins on Master, cloud-aws doesn't register s3 repos anymore.

```
org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: org/apache/http/protocol/HttpContext
  at org.elasticsearch.repositories.s3.S3Repository.<init>(Unknown Source)
  while locating org.elasticsearch.repositories.s3.S3Repository
  while locating org.elasticsearch.repositories.Repository

1 error
	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:140)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
	at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:404)
	at org.elasticsearch.repositories.RepositoriesService.registerRepository(RepositoriesService.java:368)
	at org.elasticsearch.repositories.RepositoriesService.access$100(RepositoriesService.java:55)
	at org.elasticsearch.repositories.RepositoriesService$1.execute(RepositoriesService.java:110)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:378)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:209)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/apache/http/protocol/HttpContext
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:129)
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:432)
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:414)
	at org.elasticsearch.cloud.aws.InternalAwsS3Service.getClient(InternalAwsS3Service.java:153)
	at org.elasticsearch.cloud.aws.InternalAwsS3Service.client(InternalAwsS3Service.java:82)
	at org.elasticsearch.repositories.s3.S3Repository.<init>(S3Repository.java:125)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:56)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
	at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:54)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:865)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:858)
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
	... 13 more
Caused by: java.lang.ClassNotFoundException: org.apache.http.protocol.HttpContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more
```

**Comment by dadoonet** [comment]
It sounds like that this dependency in plugin `pom.xml` is the culprit here:

```xml
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <scope>test</scope>
        </dependency>
```

httpclient and its dependencies (httpcore) is marked as a test dependency.
But httpclient is also a transitive dependency for aws sdk:

```
[INFO] +- com.amazonaws:aws-java-sdk-ec2:jar:1.10.0:compile
[INFO] |  \- com.amazonaws:aws-java-sdk-core:jar:1.10.0:compile
[INFO] |     +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |     \- org.apache.httpcomponents:httpclient:jar:4.3.6:compile
[INFO] |        +- org.apache.httpcomponents:httpcore:jar:4.3.3:compile
[INFO] |        \- commons-codec:commons-codec:jar:1.6:compile
```

When httpclient is marked with a `test` scope, it's ignored then as it has precedence on transitive dependencies. `mvn dependency:tree` gives:

```
[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ elasticsearch-cloud-aws ---
[INFO] org.elasticsearch.plugin:elasticsearch-cloud-aws:jar:2.0.0-SNAPSHOT
[INFO] +- com.amazonaws:aws-java-sdk-ec2:jar:1.10.0:compile
[INFO] |  \- com.amazonaws:aws-java-sdk-core:jar:1.10.0:compile
[INFO] +- com.amazonaws:aws-java-sdk-s3:jar:1.10.0:compile
[INFO] |  \- com.amazonaws:aws-java-sdk-kms:jar:1.10.0:compile
[INFO] +- org.hamcrest:hamcrest-all:jar:1.3:test
[INFO] +- org.apache.lucene:lucene-test-framework:jar:5.2.1:test
[INFO] |  +- org.apache.lucene:lucene-codecs:jar:5.2.1:test
[INFO] |  +- com.carrotsearch.randomizedtesting:randomizedtesting-runner:jar:2.1.14:test
[INFO] |  +- junit:junit:jar:4.11:test
[INFO] |  \- org.apache.ant:ant:jar:1.8.2:test
[INFO] +- org.elasticsearch:elasticsearch:test-jar:tests:2.0.0-SNAPSHOT:test
[INFO] |  \- com.twitter:jsr166e:jar:1.1.0:provided
[INFO] +- org.elasticsearch:elasticsearch:jar:2.0.0-SNAPSHOT:provided
[INFO] +- org.apache.lucene:lucene-core:jar:5.2.1:provided
[INFO] +- org.apache.lucene:lucene-backward-codecs:jar:5.2.1:provided
[INFO] +- org.apache.lucene:lucene-analyzers-common:jar:5.2.1:provided
[INFO] +- org.apache.lucene:lucene-queries:jar:5.2.1:provided
[INFO] +- org.apache.lucene:lucene-memory:jar:5.2.1:provided
[INFO] +- org.apache.lucene:lucene-highlighter:jar:5.2.1:provided
[INFO] +- org.apache.lucene:lucene-queryparser:jar:5.2.1:provided
[INFO] |  \- org.apache.lucene:lucene-sandbox:jar:5.2.1:provided
[INFO] +- org.apache.lucene:lucene-suggest:jar:5.2.1:provided
[INFO] |  \- org.apache.lucene:lucene-misc:jar:5.2.1:provided
[INFO] +- org.apache.lucene:lucene-join:jar:5.2.1:provided
[INFO] |  \- org.apache.lucene:lucene-grouping:jar:5.2.1:provided
[INFO] +- org.apache.lucene:lucene-spatial:jar:5.2.1:provided
[INFO] +- org.apache.lucene:lucene-expressions:jar:5.2.1:provided
[INFO] |  +- org.antlr:antlr-runtime:jar:3.5:provided
[INFO] |  +- org.ow2.asm:asm:jar:4.1:provided
[INFO] |  \- org.ow2.asm:asm-commons:jar:4.1:provided
[INFO] +- com.spatial4j:spatial4j:jar:0.4.1:provided
[INFO] +- com.vividsolutions:jts:jar:1.13:provided
[INFO] +- com.github.spullara.mustache.java:compiler:jar:0.8.13:provided
[INFO] +- com.google.guava:guava:jar:18.0:provided
[INFO] +- com.carrotsearch:hppc:jar:0.7.1:provided
[INFO] +- joda-time:joda-time:jar:2.8:provided
[INFO] +- org.joda:joda-convert:jar:1.2:provided
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.5.3:provided
[INFO] +- com.fasterxml.jackson.dataformat:jackson-dataformat-smile:jar:2.5.3:provided
[INFO] +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.5.3:provided
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.5.3:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.5.0:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.12:provided
[INFO] +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.5.3:provided
[INFO] +- io.netty:netty:jar:3.10.0.Final:provided
[INFO] +- com.ning:compress-lzf:jar:1.0.2:provided
[INFO] +- com.tdunning:t-digest:jar:3.0:provided
[INFO] +- org.apache.commons:commons-lang3:jar:3.3.2:provided
[INFO] +- commons-cli:commons-cli:jar:1.2:provided
[INFO] +- org.codehaus.groovy:groovy-all:jar:indy:2.4.0:provided
[INFO] +- log4j:log4j:jar:1.2.17:provided
[INFO] +- log4j:apache-log4j-extras:jar:1.2.17:provided
[INFO] +- org.slf4j:slf4j-api:jar:1.6.2:provided
[INFO] +- net.java.dev.jna:jna:jar:4.1.0:provided
[INFO] \- org.apache.httpcomponents:httpclient:jar:4.3.6:test
[INFO]    +- org.apache.httpcomponents:httpcore:jar:4.3.3:test
[INFO]    +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO]    \- commons-codec:commons-codec:jar:1.6:test
```

We should change the scope of `httpclient` explicitly for every plugin which requires it. Will come with a PR for it.
