### ISSUE TITLE
Custom mapping types can no longer be processed by ObjectMapper

### ISSUE THREAD

**Issue by jprante** [elastic/elasticsearch#12103]
I compile against master snapshots and use a custom mapping type, called `ref`.

This mapping works well

```
{
  "doc" : {
    "properties": {
      "authorName": {
        "type": "string"
      },
      "authorID": {
        "type": "ref",
        "ref_index": "authors",
        "ref_type": "authors",
        "ref_fields": [
          "author"
        ],
        "to": [
          "dc.creator"
        ]
      },
      "dc": {
        "properties": {
          "creator": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

but with this mapping

```
{
  "doc" : {
    "properties": {
      "author": {
        "properties": {
          "authorName": {
            "type": "string"
          },
          "authorID": {
            "type": "ref",
            "ref_index": "authors",
            "ref_type": "authors",
            "ref_fields": [
              "author"
            ],
            "to": [
              "dc.creator"
            ]
          }
        }
      },
      "dc": {
        "properties": {
          "creator": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

I get an exception since this commit https://github.com/elastic/elasticsearch/commit/2cc0382cf0160f8ef179b62cb4418853382a6901 

```
org.elasticsearch.index.mapper.MapperParsingException: mapping [doc]
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:365)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:378)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:209)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Field name [author.authorID] cannot contain '.'
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:283)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:228)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parse(ObjectMapper.java:203)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:315)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:228)
	at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:137)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:208)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:189)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:371)
	at org.elasticsearch.index.mapper.MapperService.assertSerialization(MapperService.java:325)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:316)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:255)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:362)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:378)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:209)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

But I do not have a field `author.authorID` so the error message seems to be wrong.

How can I fix this? Am I supposed to only use custom mapping types on root object level? Is this a bug?

**Comment by rjernst** [comment]
Thanks for reporting @jprante! This seems like a bug. I'm investigating.

**Comment by jprante** [comment]
I found a solution, in the custom mapper implementation, this change makes the error disappear:

From

```
    @Override
    public XContentBuilder toXContent(XContentBuilder builder, Params params) throws IOException {
        builder.startObject(name());
        builder.field("type", CONTENT_TYPE);
```
to 

```
    @Override
    public XContentBuilder toXContent(XContentBuilder builder, Params params) throws IOException {
        builder.startObject(simpleName());
        builder.field("type", CONTENT_TYPE);
        ...
```

Maybe other (custom) mapper implementations need to serialize to `simpleName()`, too?

**Comment by rjernst** [comment]
Ah yes, that would cause the problem! name() now returns the full path, while simpleName() is the immediate field name and intended for serialization as you are now using it.

**Comment by jpountz** [comment]
Closing as the problem looks solved to me.
