### ISSUE TITLE
Search Scroll witch keep alive prevent shards from closing (during Index closing)

### ISSUE THREAD

**Issue by cleemansen** [elastic/elasticsearch#12116]
Say my scroll keep alive time is set to 1 minute.
1. I'm executing a search with that scroll settings
2. Immediately after receiving my search result I'm closing and reopening the index
3. For exactly one minute I get the following error message and my cluster is red
4. after 1 minute my cluster is green.

 ```
[2015-06-22 14:48:13,846][INFO ][cluster.metadata         ] [Grim Hunter] closing indices [[de_v4]]
[2015-06-22 14:48:22,263][INFO ][cluster.metadata         ] [Grim Hunter] opening indices [[de_v4]]
[2015-06-22 14:48:27,308][WARN ][indices.cluster          ] [Grim Hunter] [[de_v4][2]] marking and sending shard failed due to [failed to create shard]
org.elasticsearch.index.shard.IndexShardCreationException: [de_v4][2] failed to create shard
	at org.elasticsearch.index.IndexService.createShard(IndexService.java:357)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyInitializingShard(IndicesClusterStateService.java:704)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewOrUpdatedShards(IndicesClusterStateService.java:605)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:185)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:480)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.lucene.store.LockObtainFailedException: Can't lock shard [de_v4][2], timed out after 5000ms
	at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:576)
	at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:504)
	at org.elasticsearch.index.IndexService.createShard(IndexService.java:310)
	... 9 more
[2015-06-22 14:48:27,309][WARN ][cluster.action.shard     ] [Grim Hunter] [de_v4][2] received shard failed for [de_v4][2], node[iTOuyuGSRLab6ZZxwnhb3g], [P], s[INITIALIZING], indexUUID [jsOkLa-_Q8GSPkKAXXfsoQ], reason [shard failure [failed to create shard][IndexShardCreationException[[de_v4][2] failed to create shard]; nested: LockObtainFailedException[Can't lock shard [de_v4][2], timed out after 5000ms]; ]]
[2015-06-22 14:48:32,309][WARN ][indices.cluster          ] [Grim Hunter] [[de_v4][0]] marking and sending shard failed due to [failed to create shard]
org.elasticsearch.index.shard.IndexShardCreationException: [de_v4][0] failed to create shard
	at org.elasticsearch.index.IndexService.createShard(IndexService.java:357)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyInitializingShard(IndicesClusterStateService.java:704)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewOrUpdatedShards(IndicesClusterStateService.java:605)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:185)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:480)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.lucene.store.LockObtainFailedException: Can't lock shard [de_v4][0], timed out after 5000ms
	at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:576)
	at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:504)
	at org.elasticsearch.index.IndexService.createShard(IndexService.java:310)
	... 9 more

[... trimmed ...]

[2015-06-22 14:49:17,414][WARN ][cluster.action.shard     ] [Grim Hunter] [de_v4][0] received shard failed for [de_v4][0], node[iTOuyuGSRLab6ZZxwnhb3g], [P], s[INITIALIZING], indexUUID [jsOkLa-_Q8GSPkKAXXfsoQ], reason [shard failure [failed to create shard][IndexShardCreationException[[de_v4][0] failed to create shard]; nested: LockObtainFailedException[Can't lock shard [de_v4][0], timed out after 5000ms]; ]]
[2015-06-22 14:49:17,414][WARN ][cluster.action.shard     ] [Grim Hunter] [de_v4][3] received shard failed for [de_v4][3], node[iTOuyuGSRLab6ZZxwnhb3g], [P], s[INITIALIZING], indexUUID [jsOkLa-_Q8GSPkKAXXfsoQ], reason [master [Grim Hunter][iTOuyuGSRLab6ZZxwnhb3g][u-excus][inet[/192.168.1.181:9300]] marked shard as initializing, but shard is marked as failed, resend shard failure]
```

*Update:*
Today I adjusted the logging settings and briefly before the cluster is getting green:
```
[2015-06-23 12:21:00,100][DEBUG][search                   ] [Prime Mover] freeing search context [1], time [1435054860015], lastAccessTime [1435054776777], keepAlive [60000]
[2015-06-23 12:21:00,101][DEBUG][search                   ] [Prime Mover] freeing search context [2], time [1435054860015], lastAccessTime [1435054776777], keepAlive [60000]
```

btw: [clearing](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html#_clear_scroll_api) (manually) all scroll ids during closing / opening process solves the problem (as temporary workaround); cluster state will be green immediately after reopening the index.

```
curl -XDELETE localhost:9200/_search/scroll/_all
```

Tested with Elasticsearch v1.6.0

**Comment by cleemansen** [comment]
Similar issue see #8940.

**Comment by clintongormley** [comment]
We should close all search contexts when closing an index in order to abort the scroll.

**Comment by martijnvg** [comment]
The `SearchService` class maintains the open search contexts (for all searches and shards on a node). When we close an index, we just close the shard, but we check `SearchService ` and clear search contexts of shards being closed. If do this, then this should fix the problem.
