### ISSUE TITLE
[CI] Failure retrieving fields from bulk request

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#12133]
http://build-us-00.elastic.co/job/es_core_master_centos/5592/consoleText

Related to https://github.com/elastic/elasticsearch/pull/12114

```
  2> REPRODUCE WITH: mvn test -Pdev -Dtests.seed=BCBC09EB75B9088F -Dtests.class=org.elasticsearch.test.rest.Rest5Tests -Dtests.slow=true -Dtests.method="test {yaml=bulk/40_fields/Fields}" -Des.logger.level=DEBUG -Des.node.mode=local -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=be -Dtests.timezone=Australia/Darwin -Dtests.rest.blacklist=cat.recovery/10_basic/*
FAILURE 0.31s J0 | Rest5Tests.test {yaml=bulk/40_fields/Fields} <<<
   > Throwable #1: java.lang.AssertionError: expected [2xx] status code but api [bulk] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Malformed action/metadata line [1], expected a simple value for field [fields] but found [START_ARRAY]"}],"type":"illegal_argument_exception","reason":"Malformed action/metadata line [1], expected a simple value for field [fields] but found [START_ARRAY]"},"status":400}]
   > 	at __randomizedtesting.SeedInfo.seed([BCBC09EB75B9088F:34E83631DB456577]:0)
   > 	at org.elasticsearch.test.rest.section.DoSection.execute(DoSection.java:99)
   > 	at org.elasticsearch.test.rest.ElasticsearchRestTestCase.test(ElasticsearchRestTestCase.java:373)
   > 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dakrone** [comment]
Fixed by 799e801
