### ISSUE TITLE
Invalid cluster settings allowed to be persisted

### ISSUE THREAD

**Issue by nellicus** [elastic/elasticsearch#12268]
Invalid cluster settings are allowed to be persisted and causing below exception at each node restart, not sure if further impact on the allocation decider:

```
[2015-07-15 15:21:42,675][WARN ][node.settings            ] [The Wink] failed to refresh settings for [org.elasticsearch.cluster.routing.allocation.decider.EnableAllocationDecider@55a88417]
org.elasticsearch.ElasticsearchIllegalArgumentException: Illegal allocation.enable value []
	at org.elasticsearch.cluster.routing.allocation.decider.EnableAllocationDecider$Allocation.parse(EnableAllocationDecider.java:122)
	at org.elasticsearch.cluster.routing.allocation.decider.EnableAllocationDecider.onRefreshSettings(EnableAllocationDecider.java:100)
	at org.elasticsearch.node.settings.NodeSettingsService.clusterChanged(NodeSettingsService.java:84)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:480)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Repro

1) install elasticsearch 1.6.0

```
Antonios-MacBook-Air-2:bin abonuccelli$ ./elasticsearch
[2015-07-15 15:20:14,248][INFO ][node                     ] [Giant-Man] version[1.6.0], pid[14041], build[cdd3ac4/2015-06-09T13:36:34Z]
[2015-07-15 15:20:14,249][INFO ][node                     ] [Giant-Man] initializing ...
[2015-07-15 15:20:14,262][INFO ][plugins                  ] [Giant-Man] loaded [marvel], sites [marvel]
[2015-07-15 15:20:14,338][INFO ][env                      ] [Giant-Man] using [1] data paths, mounts [[/ (/dev/disk0s2)]], net usable_space [169.1gb], net total_space [465.1gb], types [hfs]
[2015-07-15 15:20:18,222][INFO ][node                     ] [Giant-Man] initialized
[2015-07-15 15:20:18,225][INFO ][node                     ] [Giant-Man] starting ...
[2015-07-15 15:20:18,548][INFO ][transport                ] [Giant-Man] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/192.168.43.141:9300]}
[2015-07-15 15:20:18,587][INFO ][discovery                ] [Giant-Man] elasticsearch/7V8IhiMqSvGdQywjbja7fw
[2015-07-15 15:20:22,377][INFO ][cluster.service          ] [Giant-Man] new_master [Giant-Man][7V8IhiMqSvGdQywjbja7fw][Antonios-MacBook-Air-2.local][inet[/192.168.43.141:9300]], reason: zen-disco-join (elected_as_master)
[2015-07-15 15:20:22,426][INFO ][http                     ] [Giant-Man] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/192.168.43.141:9200]}
[2015-07-15 15:20:22,427][INFO ][node                     ] [Giant-Man] started
[2015-07-15 15:20:22,462][INFO ][gateway                  ] [Giant-Man] recovered [0] indices into cluster_state
[2015-07-15 15:20:29,292][INFO ][cluster.metadata         ] [Giant-Man] [.marvel-2015.07.15] creating index, cause [auto(bulk api)], templates [marvel], shards [1]/[1], mappings [_default_, shard_event, index_event, index_stats, node_event, routing_event, cluster_event, cluster_state, cluster_stats, node_stats, indices_stats]
[2015-07-15 15:20:30,207][INFO ][cluster.metadata         ] [Giant-Man] [.marvel-2015.07.15] update_mapping [node_stats] (dynamic)
[2015-07-15 15:20:30,273][INFO ][cluster.metadata         ] [Giant-Man] [.marvel-2015.07.15] update_mapping [routing_event] (dynamic)
[2015-07-15 15:20:30,299][INFO ][cluster.metadata         ] [Giant-Man] [.marvel-2015.07.15] update_mapping [cluster_state] (dynamic)
[2015-07-15 15:20:30,302][INFO ][cluster.metadata         ] [Giant-Man] [.marvel-2015.07.15] update_mapping [node_event] (dynamic)
[2015-07-15 15:20:30,317][INFO ][cluster.metadata         ] [Giant-Man] [.marvel-2015.07.15] update_mapping [cluster_event] (dynamic)
[2015-07-15 15:20:30,329][INFO ][cluster.metadata         ] [Giant-Man] [.marvel-2015.07.15] update_mapping [index_event] (dynamic)
[2015-07-15 15:20:30,369][INFO ][cluster.metadata         ] [Giant-Man] [.marvel-2015.07.15] update_mapping [index_stats] (dynamic)
[2015-07-15 15:20:30,399][INFO ][cluster.metadata         ] [Giant-Man] [.marvel-2015.07.15] update_mapping [indices_stats] (dynamic)
[2015-07-15 15:20:30,456][INFO ][cluster.metadata         ] [Giant-Man] [.marvel-2015.07.15] update_mapping [cluster_stats] (dynamic)
[2015-07-15 15:20:37,274][DEBUG][river.cluster            ] [Giant-Man] processing [reroute_rivers_node_changed]: execute
[2015-07-15 15:20:37,275][DEBUG][river.cluster            ] [Giant-Man] processing [reroute_rivers_node_changed]: no change in cluster_state
[2015-07-15 15:20:37,275][DEBUG][cluster.service          ] [Giant-Man] processing [cluster_update_settings]: took 2ms done applying updated cluster_state (version: 12)
[2015-07-15 15:20:37,275][DEBUG][cluster.service          ] [Giant-Man] processing [reroute_after_cluster_update_settings]: execute
[2015-07-15 15:20:37,276][DEBUG][cluster.service          ] [Giant-Man] processing [reroute_after_cluster_update_settings]: took 0s no change in cluster_state
```

2) Set invalid empty string
 
```
PUT _cluster/settings
{
  "persistent": {
    "cluster": {
      "routing": {
        "allocation": {
          "enable": ""
        }
      }
    }
  }
}
```

3) validate this is let through and persisted
```
GET _cluster/settings



{
   "persistent": {
      "cluster": {
         "routing": {
            "allocation": {
               "enable": ""
            }
         }
      }
   },
   "transient": {}
}
```

3) In the logs
```
[2015-07-15 15:20:39,635][DEBUG][cluster.service          ] [Giant-Man] processing [cluster_update_settings]: execute
[2015-07-15 15:20:39,636][DEBUG][cluster.service          ] [Giant-Man] cluster state updated, version [13], source [cluster_update_settings]
[2015-07-15 15:20:39,636][DEBUG][cluster.service          ] [Giant-Man] publishing cluster state version 13
[2015-07-15 15:20:39,636][DEBUG][cluster.service          ] [Giant-Man] set local cluster state to version 13
[2015-07-15 15:20:39,638][WARN ][node.settings            ] [Giant-Man] failed to refresh settings for [org.elasticsearch.cluster.routing.allocation.decider.EnableAllocationDecider@55a88417]
org.elasticsearch.ElasticsearchIllegalArgumentException: Illegal allocation.enable value []
	at org.elasticsearch.cluster.routing.allocation.decider.EnableAllocationDecider$Allocation.parse(EnableAllocationDecider.java:122)
	at org.elasticsearch.cluster.routing.allocation.decider.EnableAllocationDecider.onRefreshSettings(EnableAllocationDecider.java:100)
	at org.elasticsearch.node.settings.NodeSettingsService.clusterChanged(NodeSettingsService.java:84)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:480)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-07-15 15:20:39,642][DEBUG][river.cluster            ] [Giant-Man] processing [reroute_rivers_node_changed]: execute
[2015-07-15 15:20:39,642][DEBUG][river.cluster            ] [Giant-Man] processing [reroute_rivers_node_changed]: no change in cluster_state
[2015-07-15 15:20:39,650][DEBUG][cluster.service          ] [Giant-Man] processing [cluster_update_settings]: took 14ms done applying updated cluster_state (version: 13)
[2015-07-15 15:20:39,651][DEBUG][cluster.service          ] [Giant-Man] processing [reroute_after_cluster_update_settings]: execute
[2015-07-15 15:20:39,651][DEBUG][cluster.service          ] [Giant-Man] processing [reroute_after_cluster_update_settings]: took 0s no change in cluster_state
[2015-07-15 15:20:48,242][DEBUG][indices.memory           ] [Giant-Man] recalculating shard indexing buffer (reason=[[ADDED]]), total is [99mb] with [1] active shards, each shard set to indexing=[99mb], translog=[64kb]
[2015-07-15 15:20:48,242][DEBUG][index.shard              ] [Giant-Man] [.marvel-2015.07.15][0] updating index_buffer_size from [64mb] to [99mb]
```

4) stop node
```
^C[2015-07-15 15:21:32,381][INFO ][node                     ] [Giant-Man] stopping ...
[2015-07-15 15:21:32,401][DEBUG][marvel.agent             ] [Giant-Man] shutting down worker, exporting pending event
[2015-07-15 15:21:32,401][DEBUG][marvel.agent             ] [Giant-Man] worker shutdown
[2015-07-15 15:21:32,405][DEBUG][indices                  ] [Giant-Man] [.marvel-2015.07.15] closing ... (reason [shutdown])
[2015-07-15 15:21:32,406][DEBUG][indices                  ] [Giant-Man] [.marvel-2015.07.15] closing index service (reason [shutdown])
[2015-07-15 15:21:32,412][DEBUG][index                    ] [Giant-Man] [.marvel-2015.07.15] [0] closing... (reason: [shutdown])
[2015-07-15 15:21:32,423][DEBUG][index.shard              ] [Giant-Man] [.marvel-2015.07.15][0] state: [STARTED]->[CLOSED], reason [shutdown]
[2015-07-15 15:21:32,423][DEBUG][index.shard              ] [Giant-Man] [.marvel-2015.07.15][0] operations counter reached 0, will not accept any further writes
[2015-07-15 15:21:32,423][DEBUG][index.engine             ] [Giant-Man] [.marvel-2015.07.15][0] flushing shard on close - this might take some time to sync files to disk
[2015-07-15 15:21:32,440][DEBUG][index.engine             ] [Giant-Man] [.marvel-2015.07.15][0] close now acquiring writeLock
[2015-07-15 15:21:32,441][DEBUG][index.engine             ] [Giant-Man] [.marvel-2015.07.15][0] close acquired writeLock
[2015-07-15 15:21:32,456][DEBUG][index.engine             ] [Giant-Man] [.marvel-2015.07.15][0] engine closed [api]
[2015-07-15 15:21:32,457][DEBUG][index                    ] [Giant-Man] [.marvel-2015.07.15] [0] closed (reason: [shutdown])
[2015-07-15 15:21:32,457][DEBUG][indices                  ] [Giant-Man] [.marvel-2015.07.15] closing index cache (reason [shutdown])
[2015-07-15 15:21:32,457][DEBUG][index.cache.filter.weighted] [Giant-Man] [.marvel-2015.07.15] full cache clear, reason [close]
[2015-07-15 15:21:32,457][DEBUG][index.cache.fixedbitset  ] [Giant-Man] [.marvel-2015.07.15] clearing all bitsets because [close]
[2015-07-15 15:21:32,457][DEBUG][indices                  ] [Giant-Man] [.marvel-2015.07.15] clearing index field data (reason [shutdown])
[2015-07-15 15:21:32,457][DEBUG][indices                  ] [Giant-Man] [.marvel-2015.07.15] closing analysis service (reason [shutdown])
[2015-07-15 15:21:32,457][DEBUG][indices                  ] [Giant-Man] [.marvel-2015.07.15] closing index engine (reason [shutdown])
[2015-07-15 15:21:32,457][DEBUG][indices                  ] [Giant-Man] [.marvel-2015.07.15] closing index gateway (reason [shutdown])
[2015-07-15 15:21:32,458][DEBUG][indices                  ] [Giant-Man] [.marvel-2015.07.15] closing mapper service (reason [shutdown])
[2015-07-15 15:21:32,458][DEBUG][indices                  ] [Giant-Man] [.marvel-2015.07.15] closing index query parser service (reason [shutdown])
[2015-07-15 15:21:32,459][DEBUG][indices                  ] [Giant-Man] [.marvel-2015.07.15] closing index service (reason [shutdown])
[2015-07-15 15:21:32,459][DEBUG][indices                  ] [Giant-Man] [.marvel-2015.07.15] closed... (reason [shutdown])
[2015-07-15 15:21:32,467][INFO ][node                     ] [Giant-Man] stopped
[2015-07-15 15:21:32,467][INFO ][node                     ] [Giant-Man] closing ...
[2015-07-15 15:21:32,485][INFO ][node                     ] [Giant-Man] closed
```

5) restart node
```
Antonios-MacBook-Air-2:bin abonuccelli$ ./elasticsearch
[2015-07-15 15:21:34,636][INFO ][node                     ] [The Wink] version[1.6.0], pid[14054], build[cdd3ac4/2015-06-09T13:36:34Z]
[2015-07-15 15:21:34,637][INFO ][node                     ] [The Wink] initializing ...
[2015-07-15 15:21:34,649][INFO ][plugins                  ] [The Wink] loaded [marvel], sites [marvel]
[2015-07-15 15:21:34,710][INFO ][env                      ] [The Wink] using [1] data paths, mounts [[/ (/dev/disk0s2)]], net usable_space [169.1gb], net total_space [465.1gb], types [hfs]
[2015-07-15 15:21:38,459][INFO ][node                     ] [The Wink] initialized
[2015-07-15 15:21:38,460][INFO ][node                     ] [The Wink] starting ...
[2015-07-15 15:21:38,684][INFO ][transport                ] [The Wink] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/192.168.43.141:9300]}
[2015-07-15 15:21:38,738][INFO ][discovery                ] [The Wink] elasticsearch/SSoVsPgpTMSCn3DLoxkJIw
[2015-07-15 15:21:42,519][INFO ][cluster.service          ] [The Wink] new_master [The Wink][SSoVsPgpTMSCn3DLoxkJIw][Antonios-MacBook-Air-2.local][inet[/192.168.43.141:9300]], reason: zen-disco-join (elected_as_master)
[2015-07-15 15:21:42,671][INFO ][http                     ] [The Wink] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/192.168.43.141:9200]}
[2015-07-15 15:21:42,672][INFO ][node                     ] [The Wink] started
[2015-07-15 15:21:42,675][WARN ][node.settings            ] [The Wink] failed to refresh settings for [org.elasticsearch.cluster.routing.allocation.decider.EnableAllocationDecider@55a88417]
org.elasticsearch.ElasticsearchIllegalArgumentException: Illegal allocation.enable value []
	at org.elasticsearch.cluster.routing.allocation.decider.EnableAllocationDecider$Allocation.parse(EnableAllocationDecider.java:122)
	at org.elasticsearch.cluster.routing.allocation.decider.EnableAllocationDecider.onRefreshSettings(EnableAllocationDecider.java:100)
	at org.elasticsearch.node.settings.NodeSettingsService.clusterChanged(NodeSettingsService.java:84)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:480)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-07-15 15:21:42,735][INFO ][gateway                  ] [The Wink] recovered [1] indices into cluster_state
```

**Comment by clintongormley** [comment]
Hi @nellicus 

Yes this is currently the behaviour.  Unfortunately it is not easily fixable - it is a project we're planning on tackling in the 2.x series (see #6732 for more).

The way to fix it is to reset this setting to its default value (which you have to set explicitly) as in:

    PUT _cluster/settings
    {
      "persistent": {
        "cluster": {
          "routing": {
            "allocation": {
              "enable": "all"
            }
          }
        }
      }
    }


It'll remain in the cluster settings though - there's currently no way to delete settings.

Closing in favour of #6732
