### ISSUE TITLE
ImmutableSettings.classLoader() is ignored

### ISSUE THREAD

**Issue by lytvynenkoinvest** [elastic/elasticsearch#12402]
During nodeBuilder.node() on init of InternalNode passed to settings classloader is ignored.
It happens in InternalNode (line 136, elasticsearch 1.7.0) -> InternalSettingsPreparer(line: 153).

I create Settings instance and set classloader to the instance.
The settings instance I set to node builder and execute nodebuilder.node().
After that in constructor of TransportService I see settings instance without my classloader.

Does workarround exists for this problem?

**Comment by lytvynenkoinvest** [comment]
Cluster contains 2 nodes.
All ES and lucene classes are loaded by classloader that loaded my main class(where I create node builder) and this classloader I set into immutable settings.
But because of ThreadContext classloader is used I received next Exception:

Caused by: org.elasticsearch.transport.RemoteTransportException: Failed to deserialize exception response from stream
Caused by: org.elasticsearch.transport.TransportSerializationException: Failed to deserialize exception response from stream
	at org.elasticsearch.transport.netty.MessageChannelHandler.handlerResponseError(MessageChannelHandler.java:178)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:130)
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)[:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)[:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745)[:1.7.0_75]
Caused by: java.io.InvalidClassException: failed to read class descriptor
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1603)[:1.7.0_75]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)[:1.7.0_75]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)[:1.7.0_75]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)[:1.7.0_75]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)[:1.7.0_75]
	at org.elasticsearch.transport.netty.MessageChannelHandler.handlerResponseError(MessageChannelHandler.java:176)
	... 23 more
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.transport.RemoteTransportException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)[:1.7.0_75]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)[:1.7.0_75]
	at java.security.AccessController.doPrivileged(Native Method)[:1.7.0_75]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)[:1.7.0_75]
	at com.shared.classloader.MyClassLoader.findClass(XESClassLoader.java:195)[etools-commons-cl.jar:8.6.0.0-SNAPSHOT.5007]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)[:1.7.0_75]
	at com.shared.classloader.MyClassLoader.loadClass(XESClassLoader.java:183)[etools-commons-cl.jar:8.6.0.0-SNAPSHOT.5007]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)[:1.7.0_75]
	at org.elasticsearch.common.io.ThrowableObjectInputStream.loadClass(ThrowableObjectInputStream.java:99)
	at org.elasticsearch.common.io.ThrowableObjectInputStream.readClassDescriptor(ThrowableObjectInputStream.java:73)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1601)[:1.7.0_75]
	... 28 more

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/12340
