### ISSUE TITLE
Cannot instantiate SPI class: org.apache.lucene.codecs.lucene40.Lucene40Codec

### ISSUE THREAD

**Issue by devoncrouse** [elastic/elasticsearch#12432]
Both JDK 7 & 8:
```
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
```
```
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
```

When calling `NodeBuilder.nodeBuilder().node();`, I get the following exception. I've tried adding `lucene-codec:4.10.4` as a dependency, since I didn't see it in `elasticsearch-1.7.0.pom`, but no luck... Am I doing it wrong? I've successfully used previous versions of the library.

```
INFO  [2015-07-24 00:10:45,431] org.elasticsearch.node: [Shooting Star] version[1.7.0], pid[45231], build[929b973/2015-07-16T14:31:07Z]
INFO  [2015-07-24 00:10:45,431] org.elasticsearch.node: [Shooting Star] initializing ...
Exception in thread "main" java.util.ServiceConfigurationError: Cannot instantiate SPI class: org.apache.lucene.codecs.lucene40.Lucene40Codec
	at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:77)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:47)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:37)
	at org.apache.lucene.codecs.Codec.<clinit>(Codec.java:41)
	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:155)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
	at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:166)
...
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene40' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [IDVersion]
	at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:109)
	at org.apache.lucene.codecs.PostingsFormat.forName(PostingsFormat.java:100)
	at org.apache.lucene.codecs.lucene40.Lucene40Codec.<init>(Lucene40Codec.java:117)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:67)
	... 13 more
```

**Comment by devoncrouse** [comment]
Can no longer reproduce this; things are working now. Not sure what I changed :shrug:

**Comment by jpv** [comment]
same trouble. Arrrg
