### ISSUE TITLE
PluginService should ignore .DS_Store and other hidden files

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#12433]
If you traverse into a plugin directory with Finder, OSX will start creating `.DS_Store` files everywhere.  The PluginService will then attempt to read these files on startup and bomb out:

```
[2015-07-24 00:35:29,943][WARN ][bootstrap                ] failed to add plugin [/Users/tongz/Documents/elasticsearch_master/core/target/releases/elasticsearch-2.0.0-beta1-SNAPSHOT/plugins/.DS_Store]
java.nio.file.FileSystemException: /Users/tongz/Documents/elasticsearch_master/core/target/releases/elasticsearch-2.0.0-beta1-SNAPSHOT/plugins/.DS_Store/plugin-descriptor.properties: Not a directory
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
at java.nio.file.Files.newByteChannel(Files.java:361)
at java.nio.file.Files.newByteChannel(Files.java:407)
at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
at java.nio.file.Files.newInputStream(Files.java:152)
at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:85)
at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:316)
at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:109)
at org.elasticsearch.node.Node.<init>(Node.java:147)
at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:157)
at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:176)
at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:277)
at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:28)
[2015-07-24 00:35:29,946][WARN ][bootstrap                ] failed to add plugin [/Users/tongz/Documents/elasticsearch_master/core/target/releases/elasticsearch-2.0.0-beta1-SNAPSHOT/plugins/sight]
java.lang.IllegalArgumentException: Plugin [sight] must be at least a jvm or site plugin
at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:100)
at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:316)
at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:109)
at org.elasticsearch.node.Node.<init>(Node.java:147)
at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:157)
at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:176)
at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:277)
at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:28)
```

It would make sense for `.DS_Store` and other hidden files to be ignored by default.

**Comment by jpountz** [comment]
Closed via #12465
