### ISSUE TITLE
Snapshot repository failling HEAD request during start-up is not available

### ISSUE THREAD

**Issue by nkvoll** [elastic/elasticsearch#12462]
This manifests as `{"error":"RepositoryMissingException[[test-repo] missing]","status":404}`-errors if the repository is attempted used.

This behaviour is problematic in case a service has an intermittent hiccup just as Elasticsearch is starting (i.e S3 having some issues at the API level, temporary networking issues and so on).

Here's the stack trace from the instance start:

    [2015-07-25 20:52:16,198][WARN ][repositories             ] [Red Shift] failed to create repository [s3][test-repo]
    org.elasticsearch.common.inject.CreationException: Guice creation errors:

    1) Error injecting constructor, com.amazonaws.AmazonClientException: Unable to execute HTTP request: Connection refused
      at org.elasticsearch.repositories.s3.S3Repository.<init>(Unknown Source)
      while locating org.elasticsearch.repositories.s3.S3Repository
      while locating org.elasticsearch.repositories.Repository

    1 error
    	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
    	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
    	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
    	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
    	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
    	at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:407)
    	at org.elasticsearch.repositories.RepositoriesService.clusterChanged(RepositoriesService.java:302)
    	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:480)
    	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
    	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: com.amazonaws.AmazonClientException: Unable to execute HTTP request: Connection refused
    	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:473)
    	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:297)
    	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3672)
    	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1079)
    	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1042)
    	at org.elasticsearch.cloud.aws.blobstore.S3BlobStore.<init>(S3BlobStore.java:74)
    	at org.elasticsearch.repositories.s3.S3Repository.<init>(S3Repository.java:125)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
    	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
    	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
    	at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:52)
    	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
    	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
    	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
    	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
    	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
    	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
    	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
    	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
    	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
    	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
    	... 11 more
    Caused by: java.net.ConnectException: Connection refused
    	at java.net.PlainSocketImpl.socketConnect(Native Method)
    	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
    	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    	at java.net.Socket.connect(Socket.java:589)
    	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
    	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
    	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
    	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
    	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
    	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
    	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
    	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:701)
    	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:462)
    	... 35 more
    [2015-07-25 20:52:16,205][WARN ][repositories             ] [Red Shift] failed to create repository [test-repo]
    org.elasticsearch.repositories.RepositoryException: [test-repo] failed to create repository
    	at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:414)
    	at org.elasticsearch.repositories.RepositoriesService.clusterChanged(RepositoriesService.java:302)
    	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:480)
    	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
    	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: org.elasticsearch.common.inject.CreationException: Guice creation errors:

    1) Error injecting constructor, com.amazonaws.AmazonClientException: Unable to execute HTTP request: Connection refused
      at org.elasticsearch.repositories.s3.S3Repository.<init>(Unknown Source)
      while locating org.elasticsearch.repositories.s3.S3Repository
      while locating org.elasticsearch.repositories.Repository

    1 error
    	at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
    	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
    	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
    	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
    	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
    	at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:407)
    	... 7 more
    Caused by: com.amazonaws.AmazonClientException: Unable to execute HTTP request: Connection refused
    	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:473)
    	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:297)
    	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3672)
    	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1079)
    	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1042)
    	at org.elasticsearch.cloud.aws.blobstore.S3BlobStore.<init>(S3BlobStore.java:74)
    	at org.elasticsearch.repositories.s3.S3Repository.<init>(S3Repository.java:125)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
    	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
    	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
    	at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:52)
    	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
    	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
    	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
    	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
    	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
    	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
    	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
    	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
    	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
    	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
    	... 11 more
    Caused by: java.net.ConnectException: Connection refused
    	at java.net.PlainSocketImpl.socketConnect(Native Method)
    	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
    	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    	at java.net.Socket.connect(Socket.java:589)
    	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
    	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
    	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
    	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
    	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
    	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
    	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
    	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:701)
    	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:462)
    	... 35 more

**Comment by xuzha** [comment]
I think probably we need add backup and retry for this [client.doesBucketExist(bucket](https://github.com/elastic/elasticsearch/blob/master/plugins/cloud-aws/src/main/java/org/elasticsearch/cloud/aws/blobstore/S3BlobStore.java#L74)

**Comment by clintongormley** [comment]
@tlrx @dadoonet any thoughts on this?

**Comment by tlrx** [comment]
@clintongormley I agree with @xuzha

**Comment by xuzha** [comment]
I think I'm going to create another quick PR for this. And I could do another refactor for this.

**Comment by xuzha** [comment]
I think the last PR is quite straightforward. Please help me review, I think we need this.

**Comment by alexbrasetvik** [comment]
I'd love to have this fix in 1.7.1 as well.

**Comment by clintongormley** [comment]
Closed by #12462

**Comment by nkvoll** [comment]
Do I understand it correctly if the current fix just adds retries? What if the repository is down for an hour after the cluster starts, but the snapshot/restore API is not used during this time?

As a user, I'd expect it to be able to work lazily, i.e, it's fine to log that it's not available during startup etc, but if it's available when it's used, I'd expect it to "just work".
