### ISSUE TITLE
Nicer exception when sorting on mixed data types

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12675]
If you sort on (eg) a date field but set the `unmapped_type` to (eg) boolean, you can end up with an exception which is difficult to understand, eg:

    [2015-08-05 14:54:57,145][DEBUG][action.search.type       ] [Arizona Annie] [index1][2]: Failed to execute [org.elasticsearch.action.search.SearchRequest@22b8bc4f] while moving to second phase
    java.lang.ClassCastException: java.lang.Long cannot be cast to org.apache.lucene.util.BytesRef
            at org.apache.lucene.search.FieldComparator$TermOrdValComparator.compareValues(FieldComparator.java:902)
            at org.apache.lucene.search.TopDocs$MergeSortQueue.lessThan(TopDocs.java:172)
            at org.apache.lucene.search.TopDocs$MergeSortQueue.lessThan(TopDocs.java:120)
            at org.apache.lucene.util.PriorityQueue.upHeap(PriorityQueue.java:225)
            at org.apache.lucene.util.PriorityQueue.add(PriorityQueue.java:133)
            at org.apache.lucene.search.TopDocs.merge(TopDocs.java:234)

We should at least provide the name of the field that is causing this exception.

**Comment by clintongormley** [comment]
This appears to have been fixed in 2.x

**Comment by lxbalex** [comment]
Hi, I have a question, my elasticsearch version is 1.4.3, when I execute a query like that, it end up with a exception...
`GET /test_index/_search
{
	"from": 0,
	"size": 200,
	"query": {
		"filtered": {
			"filter": {
				"bool": {
					"must": {
						"range": {
							"senddate": {
								"from": "2016-02-01 00:00:00",
								"to": null,
								"include_lower": false,
								"include_upper": true
							}
						}
					}
				}
			}
		}
	},
	"sort": [
		{
			"senddate": {
				"order": "asc"
			}
		}
	]
}`

The exception is
`{
   "error": "ReduceSearchPhaseException[Failed to execute phase [query], [reduce] ]; nested: ClassCastException[org.apache.lucene.util.BytesRef cannot be cast to java.lang.Long]; ",
   "status": 503
}`

And my mappings is
`senddate: {
store: true
format: yyyy-MM-dd HH:mm:ss
type: date
}`

Can anybody tell my why?
