### ISSUE TITLE
RPM and DEB won't start

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#12702]
On master:

```bash
$ sudo dpkg -i elasticsearch*.deb
$ sudo /etc/init.d/elasticsearch start
$ cat /var/log/elasticsearch.log
[2015-08-06 18:32:06,248][ERROR][org.elasticsearch.bootstrap] Exception
java.nio.file.AccessDeniedException: /etc/elasticsearch/scripts
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:383)
        at java.nio.file.Files.createDirectory(Files.java:630)
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:734)
        at java.nio.file.Files.createDirectories(Files.java:720)
        at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:168)
        at org.elasticsearch.bootstrap.Security.addPath(Security.java:148)
        at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:125)
        at org.elasticsearch.bootstrap.Security.configure(Security.java:57)
        at org.elasticsearch.bootstrap.Bootstrap.setupSecurity(Bootstrap.java:188)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:166)
        at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:272)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:28)
```

**Comment by rmuir** [comment]
the default path.scripts is path.conf/scripts. We ensure it exists so we can grant permissions to it. if path.conf is configured to not be writable by the es user, then this `scripts` directory needs to be created and exist up front. 

Note that i'm not sure how such a configuration is intended to work with plugins. Some plugins like shield install subdirectories too, e.g.  `conf/shield`. So how are users supposed to install that? Hopefully not as root.

**Comment by nik9000** [comment]
The rpm and deb gave /etc/elasticsearch (path.conf) to root which is what I'd expect.

I have no clue what the plugins should do, but to make the rpm and deb useful again I'll create those directories when they install.

**Comment by tlrx** [comment]
> So how are users supposed to install that? Hopefully not as root.

@rmuir I think we agreed on installing plugins as root... At the same time we agreed on doing some ownership changes in #11016.
