### ISSUE TITLE
Unable to start ElasticsearchF.java in eclipse

### ISSUE THREAD

**Issue by HarishAtGitHub** [elastic/elasticsearch#12737]
Hi ,
   earlier(a week before) I just used to follow http://www.lindstromhenrik.com/debugging-elasticsearch-in-eclipse/ and I was able to start ElasticsearchF.java and was able to even put a break point. But recently I am not able to do so . It gives a lot of errors like 

<code>
java.io.IOException: Resource not found: "org/joda/time/tz/data/ZoneInfoMap" ClassLoader: sun.misc.Launcher$AppClassLoader@c387f44
	at org.joda.time.tz.ZoneInfoProvider.openResource(ZoneInfoProvider.java:210)
	at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:127)
	at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:86)
	at org.joda.time.DateTimeZone.getDefaultProvider(DateTimeZone.java:514)
	at org.joda.time.DateTimeZone.getProvider(DateTimeZone.java:413)
	at org.joda.time.DateTimeZone.forID(DateTimeZone.java:216)
	at org.joda.time.DateTimeZone.getDefault(DateTimeZone.java:151)
	at org.joda.time.chrono.ISOChronology.getInstance(ISOChronology.java:79)
	at org.joda.time.DateTimeUtils.getChronology(DateTimeUtils.java:266)
	at org.joda.time.format.DateTimeFormatter.selectChronology(DateTimeFormatter.java:968)
	at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:672)
	at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:560)
	at org.joda.time.format.DateTimeFormatter.print(DateTimeFormatter.java:644)
	at org.elasticsearch.Build.<clinit>(Build.java:51)
	at org.elasticsearch.node.Node.<init>(Node.java:136)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:157)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:177)
	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:272)
	at org.elasticsearch.bootstrap.ElasticsearchF.main(ElasticsearchF.java:30)
<b>Exception in thread "main" java.lang.IllegalStateException: java.nio.file.NoSuchFileException: /home/harish/Documents/code/elasticsearch/es/fork-new/elasticsearch/plugins/analysis-icu/plugin-descriptor.properties</b>
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:111)
	at org.elasticsearch.node.Node.<init>(Node.java:146)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:157)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:177)
	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:272)
	at org.elasticsearch.bootstrap.ElasticsearchF.main(ElasticsearchF.java:30)
Caused by: java.nio.file.NoSuchFileException: /home/harish/Documents/code/elasticsearch/es/fork-new/elasticsearch/plugins/analysis-icu/plugin-descriptor.properties
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:86)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:318)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:108)
	... 5 more

</code>

also error indicates it is looking for elasticsearch/plugins/analysis-icu/plugin-descriptor.properties
also saw the code here in https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/plugins/PluginInfo.java#L82-L87

and there is a check for plugin descriptor. But earlier it used to work without myself having to do anything. Did anything change in between to include plugins install and hence it is looking for plugin descriptor file ?

**Comment by rmuir** [comment]
This is not a supported way to run elasticsearch.

**Comment by HarishAtGitHub** [comment]
@rmuir but pls can u at least give me some clue why it was working previously but not now ... this clue can help me debug ...

**Comment by dadoonet** [comment]
Try to start the Bootstrap class instead.

**Comment by HarishAtGitHub** [comment]
I tried to do that too ...
initially I got error as follows
<code>
java.lang.IllegalStateException: failed to load bundle [] due to jar hell
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:360)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:109)
	at org.elasticsearch.node.Node.<init>(Node.java:146)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:157)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:177)
	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:272)
	at org.elasticsearch.bootstrap.ElasticsearchF.main(ElasticsearchF.java:30)
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/home/harish/Documents/code/elasticsearch/es/fork2-new/elasticsearch/core/eclipse-build" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at sun.nio.fs.UnixPath.checkRead(UnixPath.java:795)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:49)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.Files.walkFileTree(Files.java:2662)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:123)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:358)
	... 6 more
Exception in thread "main" java.lang.IllegalStateException: failed to load bundle [] due to jar hell
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:360)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:109)
	at org.elasticsearch.node.Node.<init>(Node.java:146)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:157)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:177)
	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:272)
	at org.elasticsearch.bootstrap.ElasticsearchF.main(ElasticsearchF.java:30)
Caused by: java.security.AccessControlException: <b>access denied ("java.io.FilePermission" "/home/harish/Documents/code/elasticsearch/es/fork2-new/elasticsearch/core/eclipse-build" "read")</b>
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at sun.nio.fs.UnixPath.checkRead(UnixPath.java:795)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:49)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.Files.walkFileTree(Files.java:2662)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:123)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:358)
	... 6 more

</code>

I get above strange errors and it is due to this line https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/plugins/PluginsService.java#L358
.
These errors appeared strange because a week ago I checkedout code
and it just worked amazingly as expected .. but I don't know what happened all of  sudden.
so I just wanted to check if I can proceed if I bypass the error by commenting that line.
but I then landed up in this exact error which someone else too caught ..pls see this http://stackoverflow.com/questions/30837055/elastic-search-error

**Comment by clintongormley** [comment]
Hi @HarishAtGitHub 

I run ES in Eclipse with these VM arguments:

    -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=logs/heapdump.hprof -Delasticsearch -Des.foreground=yes -ea -Des.path.home=/Users/clinton/workspace/elasticsearch/core/ -Des.security.manager.enabled=false -Des.http.cors.enabled=true -Des.http.cors.allow-origin=*

**Comment by dadoonet** [comment]
@clintongormley i think we should add this info to the TESTING doc. WDYT?

**Comment by HarishAtGitHub** [comment]
Oh my god....  that was  really great help @clintongormley ....
-Des.security.manager.enabled=false is the one that did the magic ...
Thank you very much.
so because by default it was true ,, all the the JarHell.checkJarHell as in https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/plugins/PluginsService.java#L358  was failing .

Thanks @clintongormley and @dadoonet .

Learning:
But this gave an opportunity to know about [JarHell](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/bootstrap/JarHell.java).. I was trying to add duplicate jars and it just caught it.. Super... . I have seen places where duplicate jars got into the system by plugins(especially logger jars) (eg in jenkins, nexus oss) gave errors which were hard to debug. This JarHell seems like a good solution for such problems . JarHell is amazing.

**Comment by dadoonet** [comment]
> JarHell is amazing.

I do agree !

**Comment by clintongormley** [comment]
> i think we should add this info to the TESTING doc. WDYT?

@dadoonet I agree - want to add it?

**Comment by HarishAtGitHub** [comment]
Or shall we do it in [Contributing.md](https://github.com/elastic/elasticsearch/edit/master/CONTRIBUTING.md) . Because that is the one developers who are interested in debugging will look into first(as per unwritten convention).

Shall I do it and post a pull request if you say 'yes' ?

**Comment by dadoonet** [comment]
Just added info here: https://github.com/elastic/elasticsearch/commit/2b9ef26006c0e4608110164480b8127dffb9d6ad

**Comment by HarishAtGitHub** [comment]
Thank you very much. That information is neat.

**Comment by HarishAtGitHub** [comment]
the reason why I was getting the Exception in thread "main" java.lang.IllegalStateException: java.nio.file.NoSuchFileException: /home/harish/Documents/code/elasticsearch/es/fork-new/elasticsearch/plugins/analysis-icu/plugin-descriptor.properties was that because I was having the
es.path.home= elastic search root folder. 
as there were plugins inside the plugins folder it was searching for properties files and it was failing.
and also it was looking for the "config" folder which was not there .

ya elasticsearch-root-folder/core is the right value as @clintongormley  pointed out . it had a config with elasticsearch.yml and a plugins folder that was empty .

just documenting this so that no one else faces this problem .

**Comment by rmuir** [comment]
You need to run ./run.sh

It is the only supported way to do this, because it runs bin/elasticsearch

We cannot even keep bin/elasticsearch working correctly, so we cant possible support other ways to run elasticsearch. I don't give any fucks if we supported 18 different ways to run ES before, we do not anymore.
