### ISSUE TITLE
Build of QA: Smoke Test Shaded Jar fails under maven 3.3.x

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#12791]
Build fails with maven 3.3.1 and 3.3.3. To reproduce, install one of the 3.3.x versions of maven and run `mvn clean verify` in the root directory of the project. The build will fail in the QA: Smoke Test Shaded Jar module with the following error:

```
Started J0 PID(99979@flea.local).
Suite: org.elasticsearch.shaded.test.ShadedIT
  2> NOTE: reproduce with: ant test  -Dtestcase=ShadedIT -Dtests.method=testJodaIsNotOnTheCP -Dtests.seed=2F4D23A7462CF921 -Dtests.locale= -Dtests.timezone=Asia/Baku -Dtests.asserts=true -Dtests.file.encoding=UTF-8
FAILURE 0.06s | ShadedIT.testJodaIsNotOnTheCP <<<
  > Throwable #1: junit.framework.AssertionFailedError: Expected an exception but the test passed: java.lang.ClassNotFoundException
  > at __randomizedtesting.SeedInfo.seed([2F4D23A7462CF921:3A9404F1F69FD80]:0)
  > at junit.framework.Assert.fail(Assert.java:57)
  > at java.lang.Thread.run(Thread.java:745)
  2> NOTE: reproduce with: ant test  -Dtestcase=ShadedIT -Dtests.method=testGuavaIsNotOnTheCP -Dtests.seed=2F4D23A7462CF921 -Dtests.locale= -Dtests.timezone=Asia/Baku -Dtests.asserts=true -Dtests.file.encoding=UTF-8
FAILURE 0.01s | ShadedIT.testGuavaIsNotOnTheCP <<<
  > Throwable #1: junit.framework.AssertionFailedError: Expected an exception but the test passed: java.lang.ClassNotFoundException
  > at __randomizedtesting.SeedInfo.seed([2F4D23A7462CF921:C2502FD54D83433D]:0)
  > at junit.framework.Assert.fail(Assert.java:57)
  > at java.lang.Thread.run(Thread.java:745)
  2> NOTE: reproduce with: ant test  -Dtestcase=ShadedIT -Dtests.method=testjsr166eIsNotOnTheCP -Dtests.seed=2F4D23A7462CF921 -Dtests.locale= -Dtests.timezone=Asia/Baku -Dtests.asserts=true -Dtests.file.encoding=UTF-8
FAILURE 0.01s | ShadedIT.testjsr166eIsNotOnTheCP <<<
  > Throwable #1: junit.framework.AssertionFailedError: Expected an exception but the test passed: java.lang.ClassNotFoundException
  > at __randomizedtesting.SeedInfo.seed([2F4D23A7462CF921:35593286F4269392]:0)
  > at junit.framework.Assert.fail(Assert.java:57)
  > at java.lang.Thread.run(Thread.java:745)
  2> NOTE: leaving temporary files on disk at: /Users/Shared/Jenkins/Home/workspace/elasticsearch-master/qa/smoke-test-shaded/target/J0/temp/org.elasticsearch.shaded.test.ShadedIT_2F4D23A7462CF921-001
  2> NOTE: test params are: codec=CheapBastard, sim=DefaultSimilarity, locale=, timezone=Asia/Baku
  2> NOTE: Mac OS X 10.10.4 x86_64/Oracle Corporation 1.8.0_25 (64-bit)/cpus=8,threads=1,free=482137936,total=514850816
  2> NOTE: All tests run in this JVM: [ShadedIT]
Completed [1/1] in 6.61s, 5 tests, 3 failures <<< FAILURES!


Tests with failures:
  - org.elasticsearch.shaded.test.ShadedIT.testJodaIsNotOnTheCP
  - org.elasticsearch.shaded.test.ShadedIT.testGuavaIsNotOnTheCP
  - org.elasticsearch.shaded.test.ShadedIT.testjsr166eIsNotOnTheCP
```
Please note that build doesn't fail with maven 3.2.x and it doesn't fail if mvn command is executed inside the qa/smoke-test-sharded directory. Only when the build is started from the root directory the error above can be observed.

**Comment by dadoonet** [comment]
I can confirm and reproduce the issue. 

Funny thing: when you do that again from root dir but "resume from" smoke-test-shaded module, you don't hit the issue...

`mvn clean verify -rf :smoke-test-shaded` gives `BUILD SUCCESS`

**Comment by dadoonet** [comment]
I found a way to quickly reproduce the issue.

```
mvn verify -pl org.elasticsearch.distribution.shaded:elasticsearch,:smoke-test-shaded
```

It makes obvious that when shaded is added to the reactor, it fails then smoke tests.
Working on it...

**Comment by dadoonet** [comment]
So the difference between both execution plan is obviously the `projectArtifactMap`:

The wrong one when you run `org.elasticsearch.distribution.shaded:elasticsearch,:smoke-test-shaded`

```
[DEBUG]   (f) projectArtifactMap = 
* org.elasticsearch.distribution.shaded:elasticsearch=org.elasticsearch.distribution.shaded:elasticsearch:jar:2.0.0-beta1-SNAPSHOT:compile
* org.elasticsearch:elasticsearch=org.elasticsearch:elasticsearch:jar:2.0.0-beta1-SNAPSHOT:compile
* org.apache.lucene:lucene-backward-codecs=org.apache.lucene:lucene-backward-codecs:jar:5.2.1:compile
* org.apache.lucene:lucene-analyzers-common=org.apache.lucene:lucene-analyzers-common:jar:5.2.1:compile
* org.apache.lucene:lucene-queries=org.apache.lucene:lucene-queries:jar:5.2.1:compile
* org.apache.lucene:lucene-memory=org.apache.lucene:lucene-memory:jar:5.2.1:compile
* org.apache.lucene:lucene-highlighter=org.apache.lucene:lucene-highlighter:jar:5.2.1:compile
* org.apache.lucene:lucene-queryparser=org.apache.lucene:lucene-queryparser:jar:5.2.1:compile
* org.apache.lucene:lucene-sandbox=org.apache.lucene:lucene-sandbox:jar:5.2.1:compile
* org.apache.lucene:lucene-suggest=org.apache.lucene:lucene-suggest:jar:5.2.1:compile
* org.apache.lucene:lucene-misc=org.apache.lucene:lucene-misc:jar:5.2.1:compile
* org.apache.lucene:lucene-join=org.apache.lucene:lucene-join:jar:5.2.1:compile
* org.apache.lucene:lucene-grouping=org.apache.lucene:lucene-grouping:jar:5.2.1:compile
* org.apache.lucene:lucene-spatial=org.apache.lucene:lucene-spatial:jar:5.2.1:compile
* com.spatial4j:spatial4j=com.spatial4j:spatial4j:jar:0.4.1:compile
* com.google.guava:guava=com.google.guava:guava:jar:18.0:compile
* com.carrotsearch:hppc=com.carrotsearch:hppc:jar:0.7.1:compile
* joda-time:joda-time=joda-time:joda-time:jar:2.8:compile
* org.joda:joda-convert=org.joda:joda-convert:jar:1.2:compile
* com.fasterxml.jackson.core:jackson-core=com.fasterxml.jackson.core:jackson-core:jar:2.5.3:compile
* com.fasterxml.jackson.dataformat:jackson-dataformat-smile=com.fasterxml.jackson.dataformat:jackson-dataformat-smile:jar:2.5.3:compile
* com.fasterxml.jackson.dataformat:jackson-dataformat-yaml=com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.5.3:compile
* org.yaml:snakeyaml=org.yaml:snakeyaml:jar:1.12:compile
* com.fasterxml.jackson.dataformat:jackson-dataformat-cbor=com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.5.3:compile
* io.netty:netty=io.netty:netty:jar:3.10.3.Final:compile
* com.ning:compress-lzf=com.ning:compress-lzf:jar:1.0.2:compile
* com.tdunning:t-digest=com.tdunning:t-digest:jar:3.0:compile
* org.hdrhistogram:HdrHistogram=org.hdrhistogram:HdrHistogram:jar:2.1.6:compile
* org.apache.commons:commons-lang3=org.apache.commons:commons-lang3:jar:3.3.2:compile
* commons-cli:commons-cli=commons-cli:commons-cli:jar:1.3.1:compile
* com.twitter:jsr166e=com.twitter:jsr166e:jar:1.1.0:compile
* org.hamcrest:hamcrest-all=org.hamcrest:hamcrest-all:jar:1.3:test
* org.apache.lucene:lucene-test-framework=org.apache.lucene:lucene-test-framework:jar:5.2.1:test
* org.apache.lucene:lucene-codecs=org.apache.lucene:lucene-codecs:jar:5.2.1:test
* org.apache.lucene:lucene-core=org.apache.lucene:lucene-core:jar:5.2.1:compile
* com.carrotsearch.randomizedtesting:randomizedtesting-runner=com.carrotsearch.randomizedtesting:randomizedtesting-runner:jar:2.1.16:test
* junit:junit=junit:junit:jar:4.11:test
* org.apache.ant:ant=org.apache.ant:ant:jar:1.8.2:test
```

The right one:

```
[DEBUG]   (f) projectArtifactMap = 
* org.elasticsearch.distribution.shaded:elasticsearch=org.elasticsearch.distribution.shaded:elasticsearch:jar:2.0.0-beta1-SNAPSHOT:compile
* org.apache.lucene:lucene-core=org.apache.lucene:lucene-core:jar:5.2.1:compile
* org.apache.lucene:lucene-backward-codecs=org.apache.lucene:lucene-backward-codecs:jar:5.2.1:compile
* org.apache.lucene:lucene-analyzers-common=org.apache.lucene:lucene-analyzers-common:jar:5.2.1:compile
* org.apache.lucene:lucene-queries=org.apache.lucene:lucene-queries:jar:5.2.1:compile
* org.apache.lucene:lucene-memory=org.apache.lucene:lucene-memory:jar:5.2.1:compile
* org.apache.lucene:lucene-highlighter=org.apache.lucene:lucene-highlighter:jar:5.2.1:compile
* org.apache.lucene:lucene-queryparser=org.apache.lucene:lucene-queryparser:jar:5.2.1:compile
* org.apache.lucene:lucene-sandbox=org.apache.lucene:lucene-sandbox:jar:5.2.1:compile
* org.apache.lucene:lucene-suggest=org.apache.lucene:lucene-suggest:jar:5.2.1:compile
* org.apache.lucene:lucene-misc=org.apache.lucene:lucene-misc:jar:5.2.1:compile
* org.apache.lucene:lucene-join=org.apache.lucene:lucene-join:jar:5.2.1:compile
* org.apache.lucene:lucene-grouping=org.apache.lucene:lucene-grouping:jar:5.2.1:compile
* org.apache.lucene:lucene-spatial=org.apache.lucene:lucene-spatial:jar:5.2.1:compile
* com.spatial4j:spatial4j=com.spatial4j:spatial4j:jar:0.4.1:compile
* org.hamcrest:hamcrest-all=org.hamcrest:hamcrest-all:jar:1.3:test
* org.apache.lucene:lucene-test-framework=org.apache.lucene:lucene-test-framework:jar:5.2.1:test
* org.apache.lucene:lucene-codecs=org.apache.lucene:lucene-codecs:jar:5.2.1:test
* com.carrotsearch.randomizedtesting:randomizedtesting-runner=com.carrotsearch.randomizedtesting:randomizedtesting-runner:jar:2.1.16:test
* junit:junit=junit:junit:jar:4.11:test
* org.apache.ant:ant=org.apache.ant:ant:jar:1.8.2:test
```

Trying to find a fix now...

**Comment by dadoonet** [comment]
Adding here some notes on how to quickly debug that (might help for the future).

Just run:

```sh
mvn dependency:tree -pl :smoke-test-shaded
```

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ smoke-test-shaded ---
[INFO] org.elasticsearch.qa:smoke-test-shaded:jar:2.0.0-beta1-SNAPSHOT
[INFO] +- org.elasticsearch.distribution.shaded:elasticsearch:jar:2.0.0-beta1-SNAPSHOT:compile
[INFO] |  +- org.apache.lucene:lucene-core:jar:5.2.1:compile
[INFO] |  +- org.apache.lucene:lucene-backward-codecs:jar:5.2.1:compile
[INFO] |  +- org.apache.lucene:lucene-analyzers-common:jar:5.2.1:compile
[INFO] |  +- org.apache.lucene:lucene-queries:jar:5.2.1:compile
[INFO] |  +- org.apache.lucene:lucene-memory:jar:5.2.1:compile
[INFO] |  +- org.apache.lucene:lucene-highlighter:jar:5.2.1:compile
[INFO] |  +- org.apache.lucene:lucene-queryparser:jar:5.2.1:compile
[INFO] |  +- org.apache.lucene:lucene-sandbox:jar:5.2.1:compile
[INFO] |  +- org.apache.lucene:lucene-suggest:jar:5.2.1:compile
[INFO] |  +- org.apache.lucene:lucene-misc:jar:5.2.1:compile
[INFO] |  +- org.apache.lucene:lucene-join:jar:5.2.1:compile
[INFO] |  +- org.apache.lucene:lucene-grouping:jar:5.2.1:compile
[INFO] |  +- org.apache.lucene:lucene-spatial:jar:5.2.1:compile
[INFO] |  \- com.spatial4j:spatial4j:jar:0.4.1:compile
[INFO] +- org.hamcrest:hamcrest-all:jar:1.3:test
[INFO] \- org.apache.lucene:lucene-test-framework:jar:5.2.1:test
[INFO]    +- org.apache.lucene:lucene-codecs:jar:5.2.1:test
[INFO]    +- com.carrotsearch.randomizedtesting:randomizedtesting-runner:jar:2.1.16:test
[INFO]    +- junit:junit:jar:4.11:test
[INFO]    \- org.apache.ant:ant:jar:1.8.2:test
```

and 

```sh
mvn dependency:tree -pl org.elasticsearch.distribution.shaded:elasticsearch,:smoke-test-shaded
```

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ smoke-test-shaded ---
[INFO] org.elasticsearch.qa:smoke-test-shaded:jar:2.0.0-beta1-SNAPSHOT
[INFO] +- org.elasticsearch.distribution.shaded:elasticsearch:jar:2.0.0-beta1-SNAPSHOT:compile
[INFO] |  \- org.elasticsearch:elasticsearch:jar:2.0.0-beta1-SNAPSHOT:compile
[INFO] |     +- org.apache.lucene:lucene-backward-codecs:jar:5.2.1:compile
[INFO] |     +- org.apache.lucene:lucene-analyzers-common:jar:5.2.1:compile
[INFO] |     +- org.apache.lucene:lucene-queries:jar:5.2.1:compile
[INFO] |     +- org.apache.lucene:lucene-memory:jar:5.2.1:compile
[INFO] |     +- org.apache.lucene:lucene-highlighter:jar:5.2.1:compile
[INFO] |     +- org.apache.lucene:lucene-queryparser:jar:5.2.1:compile
[INFO] |     |  \- org.apache.lucene:lucene-sandbox:jar:5.2.1:compile
[INFO] |     +- org.apache.lucene:lucene-suggest:jar:5.2.1:compile
[INFO] |     |  \- org.apache.lucene:lucene-misc:jar:5.2.1:compile
[INFO] |     +- org.apache.lucene:lucene-join:jar:5.2.1:compile
[INFO] |     |  \- org.apache.lucene:lucene-grouping:jar:5.2.1:compile
[INFO] |     +- org.apache.lucene:lucene-spatial:jar:5.2.1:compile
[INFO] |     |  \- com.spatial4j:spatial4j:jar:0.4.1:compile
[INFO] |     +- com.google.guava:guava:jar:18.0:compile
[INFO] |     +- com.carrotsearch:hppc:jar:0.7.1:compile
[INFO] |     +- joda-time:joda-time:jar:2.8:compile
[INFO] |     +- org.joda:joda-convert:jar:1.2:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-core:jar:2.5.3:compile
[INFO] |     +- com.fasterxml.jackson.dataformat:jackson-dataformat-smile:jar:2.5.3:compile
[INFO] |     +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.5.3:compile
[INFO] |     |  \- org.yaml:snakeyaml:jar:1.12:compile
[INFO] |     +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.5.3:compile
[INFO] |     +- io.netty:netty:jar:3.10.3.Final:compile
[INFO] |     +- com.ning:compress-lzf:jar:1.0.2:compile
[INFO] |     +- com.tdunning:t-digest:jar:3.0:compile
[INFO] |     +- org.hdrhistogram:HdrHistogram:jar:2.1.6:compile
[INFO] |     +- org.apache.commons:commons-lang3:jar:3.3.2:compile
[INFO] |     +- commons-cli:commons-cli:jar:1.3.1:compile
[INFO] |     \- com.twitter:jsr166e:jar:1.1.0:compile
[INFO] +- org.hamcrest:hamcrest-all:jar:1.3:test
[INFO] \- org.apache.lucene:lucene-test-framework:jar:5.2.1:test
[INFO]    +- org.apache.lucene:lucene-codecs:jar:5.2.1:test
[INFO]    +- org.apache.lucene:lucene-core:jar:5.2.1:compile
[INFO]    +- com.carrotsearch.randomizedtesting:randomizedtesting-runner:jar:2.1.16:test
[INFO]    +- junit:junit:jar:4.11:test
[INFO]    \- org.apache.ant:ant:jar:1.8.2:test
```

**Comment by dadoonet** [comment]
Reopening as the change has been reverted

**Comment by dadoonet** [comment]
We removed the shaded module so it's not an issue anymore... :p 

Closing
