### ISSUE TITLE
[test] failures in MovAvgUnitTests with seed 571CCDD579600679

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#12799]
I just ran on the latest master branch `mvn clean verify` from the root dir and it failed in core module with those tests:

```
Suite: org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgUnitTests
  2> REPRODUCE WITH: mvn test -Pdev -Dtests.seed=571CCDD579600679 -Dtests.class=org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgUnitTests -Dtests.method="testHoltWintersMultiplicativePadModel" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=en_NZ -Dtests.timezone=Asia/Manila
FAILURE 0.02s J0 | MovAvgUnitTests.testHoltWintersMultiplicativePadModel <<<
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <0>
   >      but: was <1>
   > 	at __randomizedtesting.SeedInfo.seed([571CCDD579600679:B423C11EAE0C0175]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgUnitTests.testHoltWintersMultiplicativePadModel(MovAvgUnitTests.java:383)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> REPRODUCE WITH: mvn test -Pdev -Dtests.seed=571CCDD579600679 -Dtests.class=org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgUnitTests -Dtests.method="testHoltWintersAdditiveModel" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=en_NZ -Dtests.timezone=Asia/Manila
FAILURE 0.01s J0 | MovAvgUnitTests.testHoltWintersAdditiveModel <<<
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <0>
   >      but: was <1>
   > 	at __randomizedtesting.SeedInfo.seed([571CCDD579600679:F3BB0CD1D2ABDC22]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgUnitTests.testHoltWintersAdditiveModel(MovAvgUnitTests.java:523)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> REPRODUCE WITH: mvn test -Pdev -Dtests.seed=571CCDD579600679 -Dtests.class=org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgUnitTests -Dtests.method="testHoltWintersMultiplicativePadPredictionModel" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=en_NZ -Dtests.timezone=Asia/Manila
FAILURE 0.01s J0 | MovAvgUnitTests.testHoltWintersMultiplicativePadPredictionModel <<<
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <0>
   >      but: was <-1>
   > 	at __randomizedtesting.SeedInfo.seed([571CCDD579600679:777379F9A211757]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgUnitTests.testHoltWintersMultiplicativePadPredictionModel(MovAvgUnitTests.java:454)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> REPRODUCE WITH: mvn test -Pdev -Dtests.seed=571CCDD579600679 -Dtests.class=org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgUnitTests -Dtests.method="testHoltWintersAdditivePredictionModel" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=en_NZ -Dtests.timezone=Asia/Manila
FAILURE 0.01s J0 | MovAvgUnitTests.testHoltWintersAdditivePredictionModel <<<
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <0>
   >      but: was <1>
   > 	at __randomizedtesting.SeedInfo.seed([571CCDD579600679:4AC23A92C590A297]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgUnitTests.testHoltWintersAdditivePredictionModel(MovAvgUnitTests.java:594)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> NOTE: leaving temporary files on disk at: /Users/dpilato/Documents/Elasticsearch/dev/elasticsearch/core/target/J0/temp/org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgUnitTests_571CCDD579600679-001
  2> NOTE: test params are: codec=Asserting(Lucene50): {}, docValues:{}, sim=DefaultSimilarity, locale=en_NZ, timezone=Asia/Manila
  2> NOTE: Mac OS X 10.10.4 x86_64/Oracle Corporation 1.7.0_60 (64-bit)/cpus=4,threads=1,free=334469960,total=525860864
  2> NOTE: All tests run in this JVM: [ElasticsearchPostingsFormatTest, TribeUnitTests, IndexShardModuleTests, DeflateXContentTests, Rest2Tests, NodeClientTests, StoreTest, ArrayUtilsTests, RatioValueTests, FuzzinessTests, DoubleFieldDataTests, StopTokenFilterTests, AnalysisFactoryTests, GetTermVectorsTests, IndexLookupTests, TermsShardMinDocCountTests, SimpleAllTests, IndicesLifecycleListenerSingleNodeTests, MultiPercolatorTests, MissingTests, CompletionTokenStreamTest, CreateIndexRequestBuilderTest, PathTests, GeoDistanceTests, KeepTypesFilterFactoryTests, PatternCaptureTokenFilterTests, BuilderRawFieldTests, ShardInfoTests, TermVectorsUnitTests, SearchFieldsTests, MultiDataPathUpgraderTests, VersionsTests, DynamicMappingTests, IndicesRequestTests, SearchWithRejectionsTests, MinTests, SumTests, LoggingListenerTests, GeoJSONShapeParserTests, RoutingBackwardCompatibilityUponUpgradeTests, MoreLikeThisTests, HppcMapsTests, RecoveriesCollectionTests, Murmur3FieldMapperTests, HttpPublishPortTests, DelayedAllocationTests, FieldStatsIntegrationTests, HistogramTests, JNANativesTests, ClusterHealthResponsesTests, IndicesLeaksTests, ParentIdAggTests, SimpleDynamicTemplatesTests, NoneRecyclerTests, UpdateNumberOfReplicasTests, ParentFieldTypeTests, ByteUtilsTests, SyncedFlushSingleNodeTest, FilteringAllocationTests, ByteSizeUnitTests, JarHellTests, NodeVersionAllocationDeciderTests, UpgradeReallyOldIndexTest, EnvironmentTests, ShardRoutingTests, ClusterHealthTests, ZenFaultDetectionTests, PercentileRanksTests, GeoShapeFieldTypeTests, FilterRoutingTests, IndexWithShadowReplicasTests, TransportMessageTests, SuggestStatsTests, ExternalValuesMapperIntegrationTests, UnicastZenPingTests, BasicAnalysisBackwardCompatibilityTests, SimpleBlocksTests, CompletionFieldMapperTests, UnassignedInfoTests, ListenerActionTests, IndexLifecycleActionTests, GetIndexBackwardsCompatibilityTests, Rest6Tests, IdFieldTypeTests, MathUtilsTests, IndicesStoreIntegrationTests, RecoveryStateTest, SimpleIndexTemplateTests, SimpleExistsTests, TransportClientTests, StoredNumericValuesTest, FileWatcherTest, TranslogVersionTests, ActionNamesTests, ConcurrentPercolatorTests, BlobStoreTest, ClusterStatsTests, GeoFilterTests, SettingsValidatorTests, IndicesSegmentsRequestTests, SimpleMultiSearchTests, MultiPercolatorRequestTests, CircuitBreakerNoopTests, ParentFieldLoadingTest, GeoLocationContextMappingTest, JsonSettingsLoaderTests, IndexRequestBuilderTests, ParseMappingTypeLevelTests, TimeZoneRoundingTests, XContentFactoryTests, ChildrenTests, TenShardsOneReplicaRoutingTests, IndexShardTests, StatsTests, PreBuiltAnalyzerIntegrationTests, SnapshotUtilsTests, JacksonLocationTests, SearchWhileCreatingIndexTests, CJKFilterFactoryTests, UpdateNoopTests, RejectionActionTests, EnableAllocationDeciderIntegrationTest, SearchTimeoutTests, GeoUtilsTests, Rest5Tests, ByteSizeValueTests, RegexTests, ShardReduceTests, SloppyMathTests, StemmerTokenFilterFactoryTests, OptimizeBlocksTests, DoubleIndexingDocTest, IndexAliasesServiceTests, NestedAggregatorTest, SortParserTests, ListenableActionFutureTests, TTLPercolatorTests, DedicatedAggregationTests, ExplainableScriptTests, DiscoveryWithServiceDisruptionsTests, ScanContextTests, LegacyVerificationTests, CborFilteringGeneratorTests, FunctionScorePluginTests, MustacheScriptEngineTest, NativeScriptTests, UpdateMappingIntegrationTests, CorruptedFileTest, CorruptedCompressorTests, IndicesRequestCacheTests, UpdateThreadPoolSettingsTests, ShardReplicationTests, MultiValueModeTests, KeyedLockTests, RoutingTypeMapperTests, IndexTypeMapperIntegrationTests, ScoreTypeTests, SearchWithRandomExceptionsTests, ClusterStateRequestTest, RebalanceAfterActiveTests, SearchServiceTests, GeoPointParsingTests, SearchScrollWithFailingNodesTests, PathTrieTests, TokenCountFieldMapperTests, IndexCacheableQueryTests, DecayFunctionScoreTests, AggregationsBinaryTests, UnicastBackwardsCompatibilityTest, AckClusterUpdateSettingsTests, SimpleDateMappingTests, CreateIndexTests, FunctionScoreTests, ScriptedMetricTests, BulkProcessorTests, DirectoryUtilsTest, SearchSourceBuilderTest, NGramTokenizerFactoryTests, OpenCloseIndexTests, DateHistogramOffsetTests, StopAnalyzerTests, IdMappingTests, DeflateCompressedStreamTests, MissingValuesTests, FileSystemUtilsTests, IndexQueryParserFilterDateRangeTimezoneTests, ElasticsearchExceptionTests, MetaDataTests, SmileFilteringGeneratorTests, RoutingServiceTests, DateFieldTypeTests, CircuitBreakerUnitTests, IndexRequestBuilderTest, SignificantTermsBackwardCompatibilityTests, SourceFetchingTests, XContentBuilderTests, TransportSearchFailuresTests, ChannelsTests, SimpleThreadPoolTests, SimpleSortTests, SnapshotBlocksTests, PercolatorTests, Rest0Tests, DoubleTermsTests, DuelScrollTests, GetActionTests, GeoDistanceTests, LZFCompressedStreamTests, ContextAndHeaderTransportTests, BucketScriptTests, CircuitBreakerServiceTests, TokenCountFieldMapperIntegrationTests, SearchWhileRelocatingTests, MappingMetaDataParserTests, MockDiskUsagesTests, MinBucketTests, AliasRoutingTests, TransformOnIndexMapperIntegrationTest, LongHashTests, ClusterStateDiffPublishingTests, CustomQueryParserTests, NaNSortingTests, TTLMappingTests, TypesExistsTests, FloatFieldDataTests, SimpleStringMappingTests, GeoShapeFieldMapperTests, InternalTestClusterTests, InternalEngineSettingsTest, ScriptQuerySearchTests, BinaryDVFieldDataTests, MissingValueTests, DeleteIndexBlocksTests, CompoundAnalysisTests, ResponseHeaderPluginTests, TransportClientRetryTests, CommonGramsTokenFilterFactoryTests, BitSetFilterCacheTest, MovAvgUnitTests]
Completed [733/803] on J0 in 0.12s, 13 tests, 4 failures <<< FAILURES!
```

**Comment by dadoonet** [comment]
Probably a local issue. Closing...

**Comment by dadoonet** [comment]
Argh... This moment you discover you were working in an outdated dir containing an outdated version of the project! What a shame... :)
