### ISSUE TITLE
multicast is sent over all interfaces by default

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#12914]
Migration guide says:

Elasticsearch now binds to the loopback interface by default (usually
`127.0.0.1` or `::1`). The `network.host` setting can be specified to change
this behavior.

But this is a little confusing, because it still sends multicast packets over all interfaces (224.2.2.4). Instead, when we are only bound to loopback interface, I think we should use a link-local scoped address (e.g. 224.0.0.x). Ideally we'd use node-local if ipv4 had it (nodes bound to different loopback interfaces won't see each other). ipv6 can do node-local though.

Just startup another node on the same network with -Des.network.host=<realip> and you will see that it gets multicast packets from the other machine (of course things don't work, since its advertising localhost):

[2015-08-15 22:19:45,835][WARN ][org.elasticsearch.discovery.zen.ping.multicast] [Lorna Dane] failed to connect to requesting node [Locksmith][ywu92vT0Q0OYRNo-EmK01w][mac2][inet[/127.0.0.1:9300]]
ConnectTransportException[[Locksmith][inet[/127.0.0.1:9300]] connect_timeout[30s]]; nested: ConnectException[Connection refused: /127.0.0.1:9300];
	at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:827)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:760)
	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:733)
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:234)
	at org.elasticsearch.discovery.zen.ping.multicast.MulticastZenPing$Receiver$1.run(MulticastZenPing.java:537)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: /127.0.0.1:9300
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	... 3 more

Try the same scenario with `bin/elasticsearch -Ddiscovery.zen.ping.multicast.group=224.0.0.200` and you can bring up multiple instances on one machine, but you won't see these pings from another machine. With mac at least there is an issue, and even changing the address here does not work...

**Comment by rmuir** [comment]
Hmm i'm not sure its as simple as the address, and thats not working from OS X to OS X. 

Linux seems ok.

This problem seems to be OS X specific. I'm not sure the current logic around `discovery.zen.ping.multicast.defer_group_to_set_interface` to try to coerce OS x to do the right thing is working. Setting it to false doesn't change anything.

**Comment by dakrone** [comment]
When I originally added `discovery.zen.ping.multicast.defer_group_to_set_interface` it was because though OSX would bind to `lo0`, it wouldn't send the multicast packet throw that interface (using `en0` instead) so it couldn't discover other nodes bound to 127.0.0.1. I verified the behavior with tcpdump, but perhaps it has been since fixed.

**Comment by rmuir** [comment]
Yeah, its not behaving the same as linux machines: those seem fine. Keep in mind its tricky to verify with tcpdump, in most cases I think you need to join the multicast group for tcpdump to show the packets. Its easier to just bring up an ES node on another machine in the ethernet network and see if its getting multicast packets.

**Comment by rmuir** [comment]
There is a JDK bug here.
When the address is a loopback address, we should set TTL=0, so that no packets leave the machine.
However, this does not work on OS X.

Its the exact same issue as https://bugs.openjdk.java.net/browse/JDK-6250763, just that was only fixed on Linux, not fixed on OS X, even with recent java 9 builds.

if i set TTL to 0, and try to send to an IPV4 address, I still send multicast packets out of my ethernet to other machines, which should not happen!

If I specify -Djava.net.preferIPv4Stack=true, then it works and TTL is correctly respected (but thats hardly a viable workaround).

You can test this easily with a small java or C program like this. Run an ES node on linux or something on the network because it will print errors if packets are sent:

    public static void main(String args[]) throws Exception {
      MulticastSocket socket = new MulticastSocket();
      socket.setTimeToLive(0); // has no impact unless jvm flag -Djava.net.preferIPv4Stack=true 
      SocketAddress destination = new InetSocketAddress(InetAddress.getByName("224.2.2.4"),   54328);
      socket.send(new DatagramPacket("abcd".getBytes(), 4, destination));
      socket.close();
    }

**Comment by rmuir** [comment]
I'm closing this: nothing can be done except to fix the JVM. it must make the correct system calls.
