### ISSUE TITLE
common.network failed to resolve localhost

### ISSUE THREAD

**Issue by wadekun** [elastic/elasticsearch#12925]
in linux:

[root@Search bin]# ./elasticsearch
[2015-08-17 16:39:06,294][INFO ][node                     ] [Vivisector] version[1.7.1], pid[8548], build[b88f43f/2015-07-29T09:54:16Z]
[2015-08-17 16:39:06,300][INFO ][node                     ] [Vivisector] initializing ...
[2015-08-17 16:39:06,451][INFO ][plugins                  ] [Vivisector] loaded [analysis-ik], sites [head, kopf]
[2015-08-17 16:39:06,484][INFO ][env                      ] [Vivisector] using [1] data paths, mounts [[/ (/dev/sda3)]], net usable_space [4.6gb], net total_space [8.6gb], types [ext4]
[2015-08-17 16:39:08,434][WARN ][common.network           ] failed to resolve local host, fallback to loopback
java.net.UnknownHostException: Search: Search: unknown error
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at org.elasticsearch.common.network.NetworkUtils.<clinit>(NetworkUtils.java:55)
	at org.elasticsearch.http.netty.NettyHttpServerTransport.<init>(NettyHttpServerTransport.java:165)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
	at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:52)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:59)
	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:210)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:77)
	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:245)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
Caused by: java.net.UnknownHostException: Search: unknown error

**Comment by wadekun** [comment]
modify the hosts

**Comment by SalahAdDin** [comment]
jajajajajajajjajaja

**Comment by lemonsoftltd** [comment]
In my centos7, /etc/hosts file is:
> 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
> ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
> 10.0.0.1	es1
> 10.0.0.2	es2

In master node /etc/elasticsearch/elasticsearch.yml file is:
> cluster.name: delastic
> node.name: master-1
> node.master: true
> node.data: true
> path.data: /var/lib/elasticsearch
> path.logs: /var/log/elasticsearch
> network.host: 10.0.0.1
> http.port: 9200
> discovery.zen.ping.unicast.hosts: [“es1” , “es2”]

I have DNSMasq instead of nameserver and its dns records. In bash, I checked that:

> [root@dhpc01 ~]# **ping es2 -c 2**
> PING es2 (10.0.0.2) 56(84) bytes of data.
> 64 bytes from dhpc02 (10.0.0.2): icmp_seq=1 ttl=64 time=0.207 ms
> 64 bytes from dhpc02 (10.0.0.2): icmp_seq=2 ttl=64 time=0.184 ms
> --- es2 ping statistics ---
> 2 packets transmitted, 2 received, 0% packet loss, time 999ms
> rtt min/avg/max/mdev = 0.184/0.195/0.207/0.018 ms

> [root@dhpc01 ~]# **nslookup es2**
> ;; Got SERVFAIL reply from 193.140.25.30, trying next server
> Server:         127.0.0.1
> Address:        127.0.0.1#53
> Name:   es2
> Address: 10.0.0.2

In log file of elasticsearch, I still see the same error:
> [2019-03-27T17:54:30,271][WARN ][o.e.d.z.UnicastZenPing   ] [master-1] **failed to resolve host** [“es2”]
> java.net.**UnknownHostException**: “es2”
> 	at java.net.InetAddress.getAllByName0(InetAddress.java:1281) ~[?:1.8.0_191]
> 	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:1.8.0_191]
> 	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0_191]
> 	at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:550) ~[elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:503) ~[elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:738) ~[elasticsearch-6.6.2.jar:6.6.2]
> 	at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$resolveHostsLists$0(UnicastZenPing.java:189) ~[elasticsearch-6.6.2.jar:6.6.2]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660) [elasticsearch-6.6.2.jar:6.6.2]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

What is the problem in my configuration or centos system? My elasticsearch version is 6.6.2 installed from RPM package.

**Comment by lemonsoftltd** [comment]
> 
> 
> In my centos7, /etc/hosts file is:
> 
> > 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
> > ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
> > 10.0.0.1	es1
> > 10.0.0.2	es2
> 
> In master node /etc/elasticsearch/elasticsearch.yml file is:
> 
> > cluster.name: delastic
> > node.name: master-1
> > node.master: true
> > node.data: true
> > path.data: /var/lib/elasticsearch
> > path.logs: /var/log/elasticsearch
> > network.host: 10.0.0.1
> > http.port: 9200
> > discovery.zen.ping.unicast.hosts: [“es1” , “es2”]
> 
> I have DNSMasq instead of nameserver and its dns records. In bash, I checked that:
> 
> > [root@dhpc01 ~]# **ping es2 -c 2**
> > PING es2 (10.0.0.2) 56(84) bytes of data.
> > 64 bytes from dhpc02 (10.0.0.2): icmp_seq=1 ttl=64 time=0.207 ms
> > 64 bytes from dhpc02 (10.0.0.2): icmp_seq=2 ttl=64 time=0.184 ms
> > --- es2 ping statistics ---
> > 2 packets transmitted, 2 received, 0% packet loss, time 999ms
> > rtt min/avg/max/mdev = 0.184/0.195/0.207/0.018 ms
> 
> > [root@dhpc01 ~]# **nslookup es2**
> > ;; Got SERVFAIL reply from 193.140.25.30, trying next server
> > Server:         127.0.0.1
> > Address:        127.0.0.1#53
> > Name:   es2
> > Address: 10.0.0.2
> 
> In log file of elasticsearch, I still see the same error:
> 
> > [2019-03-27T17:54:30,271][WARN ][o.e.d.z.UnicastZenPing   ] [master-1] **failed to resolve host** [“es2”]
> > java.net.**UnknownHostException**: “es2”
> > at java.net.InetAddress.getAllByName0(InetAddress.java:1281) ~[?:1.8.0_191]
> > at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:1.8.0_191]
> > at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0_191]
> > at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:550) ~[elasticsearch-6.6.2.jar:6.6.2]
> > at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:503) ~[elasticsearch-6.6.2.jar:6.6.2]
> > at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:738) ~[elasticsearch-6.6.2.jar:6.6.2]
> > at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$resolveHostsLists$0(UnicastZenPing.java:189) ~[elasticsearch-6.6.2.jar:6.6.2]
> > at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
> > at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660) [elasticsearch-6.6.2.jar:6.6.2]
> > at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
> > at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
> > at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
> 
> What is the problem in my configuration or centos system? My elasticsearch version is 6.6.2 installed from RPM package.

After updating Java, the error still present:
[2019-03-28T10:38:33,996][WARN ][o.e.d.z.UnicastZenPing   ] [master-1] failed to resolve host [“es2”]
java.net.UnknownHostException: “es2”: Temporary failure in name resolution
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0_201]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) ~[?:1.8.0_201]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) ~[?:1.8.0_201]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277) ~[?:1.8.0_201]
	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:1.8.0_201]
	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0_201]
	at org.elasticsearch.transport.TcpTransport.parse(TcpTransport.java:550) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.transport.TcpTransport.addressesFromString(TcpTransport.java:503) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:738) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$resolveHostsLists$0(UnicastZenPing.java:189) ~[elasticsearch-6.6.2.jar:6.6.2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660) [elasticsearch-6.6.2.jar:6.6.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by lemonsoftltd** [comment]
I can reach both IP address or hostname(resolved by dnsmasq) on bash:

> [root@dhpc01 ~]# curl 10.0.0.2:9200
> {
>   "name" : "es2",
>   "cluster_name" : "demir-elastic",
>   "cluster_uuid" : "_na_",
>   "version" : {
>     "number" : "6.6.2",
>     "build_flavor" : "default",
>     "build_type" : "rpm",
>     "build_hash" : "3bd3e59",
>     "build_date" : "2019-03-06T15:16:26.864148Z",
>     "build_snapshot" : false,
>     "lucene_version" : "7.6.0",
>     "minimum_wire_compatibility_version" : "5.6.0",
>     "minimum_index_compatibility_version" : "5.0.0"
>   },
>   "tagline" : "You Know, for Search"
> }

> [root@dhpc01 ~]# curl es2:9200
> {
>   "name" : "es2",
>   "cluster_name" : "demir-elastic",
>   "cluster_uuid" : "_na_",
>   "version" : {
>     "number" : "6.6.2",
>     "build_flavor" : "default",
>     "build_type" : "rpm",
>     "build_hash" : "3bd3e59",
>     "build_date" : "2019-03-06T15:16:26.864148Z",
>     "build_snapshot" : false,
>     "lucene_version" : "7.6.0",
>     "minimum_wire_compatibility_version" : "5.6.0",
>     "minimum_index_compatibility_version" : "5.0.0"
>   },
>   "tagline" : "You Know, for Search"
> }
