### ISSUE TITLE
optimize one shard failed - caused by org.apache.lucene.store.BufferedChecksumIndexInput cannot seek backwards

### ISSUE THREAD

**Issue by kjelle** [elastic/elasticsearch#13012]
Hello.

Im running ES v1.7.1 on ubuntu 14.04 servers. I write data to an alias for "today's index" (storm-YYYY-MM-DD). I have 24 nodes, and today's index have 24 shards and 0 replicas. At midnight I update my aliases, and issue a "curator optimize --max_num_segments 1" on "yesterday's index" and enable 3 replicas. I update "yesterday's index" _settings with setting "index.store.throttle.type" to none before starting the optimize (running at the night - almost no searches going).

When I call the optimize I see a long list of segments (last night 1127 segments). When it finished I noticed an exception in my master node's log and shard0 was not optimized. The other 23 shards, 1-23, had exactly 1 segment. To check the list of segments i call "_cat/segments/$YESTERDAY_INDEX?pretty\&v". This list was long and ugly before the optimize. Afterwards, it only displayed shard 1-23 (shard 0 is absent). When I call the same API a few seconds later, shard0 i present with it's previous 45ish segment count.

```
[DEBUG][action.admin.indices.optimize] [s01-master-01] [storm-2015-08-18][0], node[hsfByw1LT46uvyHKjImkiA], [P], s[STARTED]: failed to execute [OptimizeRequest{maxNumSegments=1, onlyExpungeDeletes=false, flush=true, force=false}]
org.elasticsearch.transport.RemoteTransportException: [l06-data-02][inet[/192.168.1.19:9302]][indices:admin/optimize[s]]
Caused by: org.elasticsearch.index.engine.OptimizeFailedEngineException: [storm-2015-08-18][0] force merge failed
        at org.elasticsearch.index.engine.InternalEngine.forceMerge(InternalEngine.java:829)
        at org.elasticsearch.index.shard.IndexShard.optimize(IndexShard.java:734)
        at org.elasticsearch.action.admin.indices.optimize.TransportOptimizeAction.shardOperation(TransportOptimizeAction.java:110)
        at org.elasticsearch.action.admin.indices.optimize.TransportOptimizeAction.shardOperation(TransportOptimizeAction.java:49)
        at org.elasticsearch.action.support.broadcast.TransportBroadcastOperationAction$ShardTransportHandler.messageReceived(TransportBroadcastOperationAction.java:338)
        at org.elasticsearch.action.support.broadcast.TransportBroadcastOperationAction$ShardTransportHandler.messageReceived(TransportBroadcastOperationAction.java:324)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:279)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: background merge hit exception: _fm(4.10.4):C7401808 _7z6(4.10.4):c7051806 _96x(4.10.4):c7006519 _9kz(4.10.4):c7033966 _6t7(4.10.4):c7038676 _4r0(4.10.4):c7040730 _8do(4.10.4):c7012751 _3v7(4.10.4):c7061041 _16c(4.10.4):C6950686 _9li(4.10.4):c263395 _9ky(4.10.4):c231955 _9j2(4.10.4):c187371 _9lg(4.10.4):c137054 _9jt(4.10.4):c89542 _9lh(4.10.4):c86325 _9j3(4.10.4):c59804 _9kq(4.10.4):c34919 _9jy(4.10.4):c33735 _9lj(4.10.4):c32217 _9ka(4.10.4):c31557 _9js(4.10.4):c18749 _9ke(4.10.4):c17671 _9lb(4.10.4):c14342 _9la(4.10.4):c13163 _9l5(4.10.4):c12237 _9l4(4.10.4):c11045 _9le(4.10.4):c10496 _9l8(4.10.4):c6735 _9l2(4.10.4):c6319 _9kv(4.10.4):c40 into _9lk [maxNumSegments=1]
        at org.apache.lucene.index.IndexWriter.forceMerge(IndexWriter.java:1829)
        at org.elasticsearch.index.engine.InternalEngine.forceMerge(InternalEngine.java:817)
        ... 10 more
Caused by: java.lang.IllegalStateException: class org.apache.lucene.store.BufferedChecksumIndexInput cannot seek backwards
        at org.apache.lucene.store.ChecksumIndexInput.seek(ChecksumIndexInput.java:49)
        at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader$ChunkIterator.next(CompressingStoredFieldsReader.java:442)
        at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.merge(CompressingStoredFieldsWriter.java:368)
        at org.apache.lucene.index.SegmentMerger.mergeFields(SegmentMerger.java:332)
        at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:100)
        at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4223)
        at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:3811)
        at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:409)
        at org.apache.lucene.index.TrackingConcurrentMergeScheduler.doMerge(TrackingConcurrentMergeScheduler.java:107)
        at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:486)
```

**Comment by mikemccand** [comment]
This is a spooky exception; I haven't seen it before.  It means that when reading from a segment in order to merged stored fields, we somehow attempted to seek backwards, which should never happen because merging only iterates through the docs "in order" 0 .. maxDoc.

I've committed more verbosity to this particular exception message in Lucene so we'll know "how far backwards" in the future, but for today:

It might be a Lucene bug, maybe a corner case somehow (the code in this area is quite complex, but I can't see any bug after staring at it for a while)...

It could be a JVM bug: which Java version are you using on the node with the affected shard?

It could also be as yet undetected index corruption: can you run CheckIndex on this shard?  Use index.shard.check_on_startup and restart that node: https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html

Or, can you upload the shard somewhere where I can download?

**Comment by kjelle** [comment]
To allow the cluster to function properly I excluded that node from allocation so no data resides on the RAID0 for this node atm.

I coincidentally checked dmesg on the server and it seemed to be a disk problem for the RAID0 partition used by _l06-data-02_ (sdc1) at the same time as the Exception appeared.

```
[47263.954825] sd 0:2:2:0: [sdc]
[47263.954833] Result: hostbyte=DID_ERROR driverbyte=DRIVER_OK
[47263.954835] sd 0:2:2:0: [sdc] CDB:
[47263.954837] Read(16): 88 00 00 00 00 00 7a c0 00 7a 00 00 00 08 00 00
[47263.954847] end_request: I/O error, dev sdc, sector 2059403386
[47263.960688] EXT4-fs error (device sdc1): ext4_wait_block_bitmap:476: comm java: Cannot read block bitmap - block_group = 7867, block_bitmap = 257425419
[47264.010809] sd 0:2:2:0: [sdc]
[47264.010823] Result: hostbyte=DID_ERROR driverbyte=DRIVER_OK
[47264.010826] sd 0:2:2:0: [sdc] CDB:
[47264.010828] Read(16): 88 00 00 00 00 00 7a c0 00 82 00 00 00 08 00 00
[47264.010838] end_request: I/O error, dev sdc, sector 2059403394
[47264.016754] EXT4-fs error (device sdc1): ext4_wait_block_bitmap:476: comm java: Cannot read block bitmap - block_group = 7868, block_bitmap = 257425420
```

Why it tries to seek backwards I cannot say.

But - after this Exception, and moving the shards off this node, I have begun to experience other Exceptions which I cannot resolve (google, forums, github issues). See [#13095]

**Comment by kjelle** [comment]
@mikemccand: We have reconfigured the entire cluster. We are now running 24 RAID0's and assign 6 partitions to each ES node (4 ES nodes per server). Waiting to see if/when the bug comes back.

**Comment by jpountz** [comment]
@kjelle Have you seen the error happen again?

**Comment by clintongormley** [comment]
No more feedback. Closing

**Comment by Leryan** [comment]
Hi,

Running on NFS can trigger this error. I didn't found any solution at the moment for this error.

**Comment by fredsted** [comment]
Seeing this error using NFS, but using NFSv4, where `nolock` no longer applies. Does anyone know of a solution here?
