### ISSUE TITLE
Getting java.lang.NoSuchFieldError run time error on field JRE_IS_64BIT

### ISSUE THREAD

**Issue by kvramana** [elastic/elasticsearch#13052]
My environment: I am using ES 1.7.1, with jdk1.7.0_72, on a Linux x86-64 bit platform, and in its lib directory, there is this jar called lucene-core-4.10.4.jar.

A simple ES transport client, using its JAVA API, produces this error stack trace:
java.lang.NoSuchFieldError: JRE_IS_64BIT
        at org.apache.lucene.util.RamUsageEstimator.<clinit>(RamUsageEstimator.java:145)
        at org.elasticsearch.common.util.BigArrays.<clinit>(BigArrays.java:51)
        at org.elasticsearch.common.io.stream.BytesStreamOutput.<init>(BytesStreamOutput.java:55)
        at org.elasticsearch.common.io.stream.BytesStreamOutput.<init>(BytesStreamOutput.java:45)
        at org.elasticsearch.common.xcontent.XContentBuilder.builder(XContentBuilder.java:77)
        at org.elasticsearch.common.xcontent.json.JsonXContent.contentBuilder(JsonXContent.java:40)
        at org.elasticsearch.common.xcontent.XContentFactory.contentBuilder(XContentFactory.java:122)
        at org.elasticsearch.common.xcontent.XContentFactory.jsonBuilder(XContentFactory.java:49)

When i de-compile lucene-core-4.10.4.jar, i do see the field JRE_IS_64BIT though.

Is it possible that an out of version JAR is packaged up inside ES 1.7.1?

**Comment by kvramana** [comment]
Closing it, i figured that an older version of lucene-core.jar got ahead into classpath, removed it and it's working as it should.
