### ISSUE TITLE
doc_values doesn't work with keyword tokenizers

### ISSUE THREAD

**Issue by bra-fsn** [elastic/elasticsearch#13099]
I've tried enabling doc_values on a keyword tokenized string field (lowercase and icu_collation filter is tried) and it fails with:
```
org.elasticsearch.index.mapper.MapperParsingException: Expected map for property [fields] on field [doc_values] but got a class java.lang.String
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:292)
        at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:214)
        at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:136)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:211)
        at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:192)
        at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:449)
        at org.elasticsearch.cluster.metadata.MetaDataMappingService$4.execute(MetaDataMappingService.java:505)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:196)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:162)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

I guess this should be a perfectly valid combination.

Examples used:
```
{"tokenizer": "keyword","filter": ["lowercase"]}
```
and 
```
{'subject':{"type": "string", "analyzer": "lc"},"doc_values": true}
```

elasticsearch version 1.7.1, icu plugin: 2.7.0

**Comment by jasontedor** [comment]
Currently, doc values are not supported on analyzed string fields. There is an [open issue](https://github.com/elastic/elasticsearch/issues/12394) to address this situation in a future release of Elasticsearch.

Relates #10061 and #12394.

**Comment by bra-fsn** [comment]
@jasontedor: ah, thanks, I couldn't find it.
