### ISSUE TITLE
RecoveryFailedException: NegativeArraySizeException when marking and sending shard

### ISSUE THREAD

**Issue by kjelle** [elastic/elasticsearch#13095]
Elasticsearch version: 1.7.1 - 24 data nodes, 3 masters, 3 clients.

````
Settings (transient)
indices.recovery.translog_size 512kb
indices.recovery.concurrent_streams 3
indices.recovery.translog_ops 1000
indices.recovery.max_bytes_per_sec 40mb
indices.recovery.file_chunk_size 512kb
cluster.routing.allocation.cluster_concurrent_rebalance 2
cluster.routing.allocation.node_concurrent_recoveries 2

Settings (yml)
index.refresh_interval 60s
indices.recovery.max_bytes_per_sec 200mb
```

I get Exceptions when ES moves shards or enables replication. Some replications are stuck in INITIALIZATION. It tries to INIT, then falls back to UNASSIGNED. Some INIt on replicas and some relocations seems to run OK (/_cat/recovery).

I would estiamte this is affected by almost all indices (see many in the log). And it seems not to be only one shard per index. The consistent error is the **Caused by: java.lang.NegativeArraySizeException**. The last Caused by seems to go into recursion and we get a ton of **Suppressed: ..**

The exceptions comes "now and then". If I increase indices.recovery to concurrent_streams 24, max_bytes_per_sec 512mb it doesn't increase the Exception rate. **However**, if I increase node_concurrent_recoveries beyond 2, e.g. to 3, the number of Exceptions explodes - flooding with tens or hundreds per second on each node. 

```
[2015-08-25 07:46:23,207][WARN ][indices.cluster          ] [l03-data-01] [[storm-today][9]] marking and sending shard failed due to [failed recovery]
org.elasticsearch.indices.recovery.RecoveryFailedException: [storm-today][9]: Recovery failed from [l05-data-04][yQg00N7RTzOGHT3UQ-6Sjg]l05][inet[/192.168.1.18:9304]]{rack_id=A25, master=false} into [l03-data-01][7fzOuK7ZRFuhN0a1UlcXIQ][l03][inet[192.168.1.16/192.168.1.16:9301]]{rack_id=A25, master=false}
        at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:280)
        at org.elasticsearch.indices.recovery.RecoveryTarget.access$700(RecoveryTarget.java:70)
        at org.elasticsearch.indices.recovery.RecoveryTarget$RecoveryRunner.doRun(RecoveryTarget.java:561)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.transport.RemoteTransportException: [l05-data-04][inet[/192.168.1.18:9304]][internal:index/shard/recovery/start_recovery]
Caused by: org.elasticsearch.index.engine.RecoveryEngineException: [storm-today][9] Phase[1] Execution failed
        at org.elasticsearch.index.engine.InternalEngine.recover(InternalEngine.java:883)
        at org.elasticsearch.index.shard.IndexShard.recover(IndexShard.java:780)
        at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:125)
        at org.elasticsearch.indices.recovery.RecoverySource.access$200(RecoverySource.java:49)
        at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:146)
        at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:279)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.indices.recovery.RecoverFilesRecoveryException: [storm-today][9] Failed to transfer [13] files with total size of [11.2gb]
        at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:430)
        at org.elasticsearch.index.engine.InternalEngine.recover(InternalEngine.java:878)
        ... 10 more
Caused by: java.lang.NegativeArraySizeException
        at org.elasticsearch.indices.recovery.RecoverySourceHandler$3.doRun(RecoverySourceHandler.java:280)
        ... 4 more
        Suppressed: java.lang.NegativeArraySizeException
                ... 5 more
        Suppressed: java.lang.NegativeArraySizeException
                ... 5 more
        Suppressed: java.lang.NegativeArraySizeException
                ... 5 more
        Suppressed: java.lang.NegativeArraySizeException
                ... 5 more
        Suppressed: java.lang.NegativeArraySizeException
                ... 5 more
        Suppressed: java.lang.NegativeArraySizeException
                ... 5 more
        Suppressed: java.lang.NegativeArraySizeException
                ... 5 more
        Suppressed: java.lang.NegativeArraySizeException
                ... 5 more
        Suppressed: java.lang.NegativeArraySizeException
                ... 5 more
        Suppressed: java.lang.NegativeArraySizeException
                ... 5 more
        Suppressed: java.lang.NegativeArraySizeException
                ... 5 more
        Suppressed: java.lang.NegativeArraySizeException
                ... 5 more
```

**Comment by clintongormley** [comment]
This looks a lot like file corruption, presumably related to the RAID error that you mentioned in #13012 

                                final int BUFFER_SIZE = (int) recoverySettings.fileChunkSize().bytes();
                                final byte[] buf = new byte[BUFFER_SIZE];

**Comment by kjelle** [comment]
@clintongormley I'v decomissioned our node with the faulty RAID0 and wiped indices and reloading all the data to see if the problem will go away. It seems to be that if an index has resided on the faulty RAID0 all seems well unit this shard is relocated, or I try to generate a replica from it. Let's see if removing one of my nodes reveals anything new.

**Comment by kjelle** [comment]
We'll at the same time remove RAID0 and stripe using multi path in ES yaml.

**Comment by clintongormley** [comment]
@kjelle note that there is a big change in multi-path coming in 2.0.  In 1.x, the files from a single shard are striped across multiple paths, which means that failure on any one path can corrupt all shards on that node.  In 2.0, each shard is written to a single data path only, so failure of that path will only affect the shards on that path.  When first upgrading to 2.0, segment files are moved around to ensure that each shard lives in a single path.

**Comment by kjelle** [comment]
@clintongormley thanks for that info. I decided on RAID0 to be able to utilize the whole IOPS of 6 disks as one, instead one by one (as you mention for 2.x). We'll see how it performance, and switch back if necessary

**Comment by kjelle** [comment]
@clintongormley the problem is with the code in v1.7.1. If you set equal to or higher than 2048mb (2147483648 bytes) you go pass max int for a *32bit Java int* (2147483647) which results in *-2147483648*.

An interesting observation is that the Exception hits after a while (5minutes+ and after 15ish percent) and not initially

I see that in the [v2.0 branch of RecoverySourceHandler](https://github.com/elastic/elasticsearch/blob/2.0/core/src/main/java/org/elasticsearch/indices/recovery/RecoverySourceHandler.java#L296) it has been fixed;
```
final int BUFFER_SIZE = (int) Math.max(1, recoverySettings.fileChunkSize().bytes()); // at least one!
```

**Comment by clintongormley** [comment]
OK, that was changed in https://github.com/elastic/elasticsearch/pull/12919

According to the settings you provided in the description, you'd only set `indices.recovery.file_chunk_size` to `512kb`. Did you try setting it to a different too-high value?

Either way, we should probably add some validation around that setting.

**Comment by kjelle** [comment]
@clintongormley yes, i was setting it up to 2048mb.

**Comment by clintongormley** [comment]
Nothing more to do here. Closing
