### ISSUE TITLE
Return error for invalid search exists api query

### ISSUE THREAD

**Issue by masaruh** [elastic/elasticsearch#13094]
If you send invalid query like this:
```
POST /someindex/_search/exists
{
  "size": 0,
  "query": {
    "match_all": {}
  }
}
```

it returns `{"exits": false}` while it logs exception like:
```
[2015-08-25 12:29:23,958][DEBUG][action.exists            ] [Stellaris] [someindex][3], node[Qm1-IUusSuioZ_r-T-daSg], [P], s[STARTED]: failed to execute [[[someindex]][], source[{
  "size": 0,
  "query": {
    "match_all": {}
  }
}
]]
org.elasticsearch.index.query.QueryParsingException: [someindex] request does not support [size]
	at org.elasticsearch.index.query.IndexQueryParserService.parseQuery(IndexQueryParserService.java:360)
	at org.elasticsearch.action.exists.TransportExistsAction.shardOperation(TransportExistsAction.java:187)
	at org.elasticsearch.action.exists.TransportExistsAction.shardOperation(TransportExistsAction.java:66)
	at org.elasticsearch.action.support.broadcast.TransportBroadcastOperationAction$AsyncBroadcastAction$1.run(TransportBroadcastOperationAction.java:170)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Shouldn't it return error in this case?

**Comment by jpountz** [comment]
+1

**Comment by harshita1931** [comment]
hello everyone :)
I am new to open source programming and I want to learn the same. I wanted to do some bug fixing so as to get an idea of how things are done. I saw this issue and want to work on it. Kindly help me by telling me in brief how to start on this. I would be greatly thankful to you all :)

**Comment by johtani** [comment]
I try to execute this invalid query on 2.0.0-beta2, then I can not see an Exception in logs.

**Comment by javanna** [comment]
We decided to remove the search exists api in #13682. It is now deprecated in 2.1 and 2.x branches and removed from master. We can close this as won't fix then.
