### ISSUE TITLE
Snapshot error while snapshotting to AWS S3

### ISSUE THREAD

**Issue by niraj8241** [elastic/elasticsearch#13114]
Hi All,

I am using ES 1.5 version with Cloud-AWS plugin 2.5.1. I am trying to create a snapshot but i see the following error in the logs. 

```
[2015-08-26 00:04:54,216][WARN ][snapshots                ] [prod-01-data01] [[logstash-2015.08.25][3]] [niraj-backup:test] failed to create snapshot
org.elasticsearch.index.snapshots.IndexShardSnapshotFailedException: [logstash-2015.08.25][3] INSTANCE
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository.snapshot(BlobStoreIndexShardRepository.java:150)
        at org.elasticsearch.index.snapshots.IndexShardSnapshotAndRestoreService.snapshot(IndexShardSnapshotAndRestoreService.java:85)
        at org.elasticsearch.snapshots.SnapshotsService$5.run(SnapshotsService.java:817)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchFieldError: INSTANCE
        at org.apache.http.client.utils.URLEncodedUtils.parse(URLEncodedUtils.java:243)
        at org.apache.http.client.utils.URLEncodedUtils.parse(URLEncodedUtils.java:222)
        at org.apache.http.client.utils.URIBuilder.parseQuery(URIBuilder.java:95)
        at org.apache.http.client.utils.URIBuilder.digestURI(URIBuilder.java:165)
        at org.apache.http.client.utils.URIBuilder.<init>(URIBuilder.java:90)
        at org.apache.http.client.utils.URIUtils.rewriteURI(URIUtils.java:138)
        at org.apache.http.impl.client.DefaultRequestDirector.rewriteRequestURI(DefaultRequestDirector.java:354)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:477)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:701)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:462)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:297)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3672)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3621)
        at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:642)
        at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:625)
        at org.elasticsearch.cloud.aws.blobstore.S3BlobContainer.listBlobsByPrefix(S3BlobContainer.java:118)
        at org.elasticsearch.cloud.aws.blobstore.S3BlobContainer.listBlobs(S3BlobContainer.java:136)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.snapshot(BlobStoreIndexShardRepository.java:438)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository.snapshot(BlobStoreIndexShardRepository.java:140)
        ... 5 more
```

Any suggestion would be really appreciated. I am kinda stuck as of now. 

Regards
Niraj

**Comment by dadoonet** [comment]
Which exact commands you run?

**Comment by niraj8241** [comment]
curl -XPUT 'http://localhost:9200/_snapshot/niraj' -d '{
    "type": "s3",
    "settings": {
        "bucket": "xxxxxx",
        "region": "us-east"
    }
}'

This was for snapshot 

curl -XPUT 'http://localhost:9200/_snapshot/s3/niraj123'

**Comment by dadoonet** [comment]
Closing as also opened here: https://discuss.elastic.co/t/nosuchfielderror-instance-while-elasticsearch-backup/28060/2

Will reopen if it's an issue.

**Comment by dadoonet** [comment]
What does your elasticsearch.yml look like?

**Comment by dadoonet** [comment]
Also do you have other plugins or run elasticsearch embedded?

**Comment by niraj8241** [comment]
Below is my elasticsearch.yml file

action:
  disable_delete_all_indices: true
bootstrap:
  mlockall: true
cloud:
  aws:
    access_key: xxxxxxxxxxxxx
    secret_key: xxxxxxxxxxxxxxx
cluster:
  name: elasticsearch
discovery:
  zen:
    minimum_master_nodes: 2
    ping:
      multicast:
        enabled: false
      unicast:
        hosts:
             - xxxxxxxx:9300
             - xxxxxxxx:9300
             - xxxxxxxx:9300
gateway:
  expected_nodes: 3
  recover_after_nodes: 2
  recover_after_time: 2m
index:
  indexing:
    slowlog:
      threshold:
        index:
          warn: 10s
  merge:
    scheduler:
      max_thread_count: 1
  refresh_interval: 30s
  search:
    slowlog:
      threshold:
        query:
          warn: 10s
  translog:
    flush_threshold_size: 500mb
indices:
  breaker:
    fielddata:
      limit: 60%
    request:
      limit: 40%
    total:
      limit: 70%
  cache:
    filter:
      size: 15%
  fielddata:
    cache:
      size: 20%
  memory:
    index_buffer_size: 20%
    min_index_buffer_size: 96mb
    min_shard_index_buffer_size: 12mb
node:
  name: prod-01-data03-prod-01-data03
path:
  data: /opt/elasticsearch/data/prod-01-data03
script:
  disable_dynamic: true



Yeh i have marvel and watcher installed.

**Comment by dadoonet** [comment]
Reopening.

I'll try to reproduce.

In the meantime, could you uninstall watcher, try again ?
Same with marvel then ?

**Comment by niraj8241** [comment]
Yeah i did. But still the same

**Comment by dadoonet** [comment]
And you restarted the nodes, right?

**Comment by niraj8241** [comment]
yes i did on all the nodes.

**Comment by dadoonet** [comment]
So I checked AWS Plugin 2.5.1. It's bundled with `httpclient:jar:4.3.5` and `httpcore:jar:4.3.2`.

```
[INFO] org.elasticsearch:elasticsearch-cloud-aws:jar:2.5.1
[INFO] +- org.elasticsearch:elasticsearch:jar:1.5.0:provided
[INFO] |  +- org.apache.lucene:lucene-analyzers-common:jar:4.10.4:provided
[INFO] |  +- org.apache.lucene:lucene-queries:jar:4.10.4:provided
[INFO] |  +- org.apache.lucene:lucene-memory:jar:4.10.4:provided
[INFO] |  +- org.apache.lucene:lucene-highlighter:jar:4.10.4:provided
[INFO] |  +- org.apache.lucene:lucene-queryparser:jar:4.10.4:provided
[INFO] |  +- org.apache.lucene:lucene-sandbox:jar:4.10.4:provided
[INFO] |  +- org.apache.lucene:lucene-suggest:jar:4.10.4:provided
[INFO] |  +- org.apache.lucene:lucene-misc:jar:4.10.4:provided
[INFO] |  +- org.apache.lucene:lucene-join:jar:4.10.4:provided
[INFO] |  +- org.apache.lucene:lucene-grouping:jar:4.10.4:provided
[INFO] |  +- org.apache.lucene:lucene-spatial:jar:4.10.4:provided
[INFO] |  |  \- com.spatial4j:spatial4j:jar:0.4.1:provided
[INFO] |  +- org.antlr:antlr-runtime:jar:3.5:provided
[INFO] |  +- org.ow2.asm:asm:jar:4.1:provided
[INFO] |  \- org.ow2.asm:asm-commons:jar:4.1:provided
[INFO] +- org.apache.lucene:lucene-core:jar:4.10.4:provided
[INFO] +- com.amazonaws:aws-java-sdk-ec2:jar:1.9.34:compile
[INFO] |  \- com.amazonaws:aws-java-sdk-core:jar:1.9.34:compile
[INFO] |     +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |     +- org.apache.httpcomponents:httpclient:jar:4.3.5:compile
[INFO] |     |  \- org.apache.httpcomponents:httpcore:jar:4.3.2:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-databind:jar:2.3.2:compile
[INFO] |     |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.3.0:compile
[INFO] |     |  \- com.fasterxml.jackson.core:jackson-core:jar:2.4.2:compile
[INFO] |     \- joda-time:joda-time:jar:2.7:compile
[INFO] +- com.amazonaws:aws-java-sdk-s3:jar:1.9.34:compile
[INFO] |  \- com.amazonaws:aws-java-sdk-kms:jar:1.9.34:compile
[INFO] +- commons-codec:commons-codec:jar:1.4:compile
```

Could you run:

```sh
ls -l plugins/cloud-aws
curl 'localhost:9200/_cat/plugins?v'
```

**Comment by niraj8241** [comment]
ls -l plugins/cloud-aws

-rw-r--r-- 1 root root  481641 Aug 26 05:42 aws-java-sdk-core-1.9.23.jar
-rw-r--r-- 1 root root 1838789 Aug 26 05:42 aws-java-sdk-ec2-1.9.23.jar
-rw-r--r-- 1 root root  252285 Aug 26 05:42 aws-java-sdk-kms-1.9.23.jar
-rw-r--r-- 1 root root  540472 Aug 26 05:42 aws-java-sdk-s3-1.9.23.jar
-rw-r--r-- 1 root root   58160 Aug 26 05:42 commons-codec-1.4.jar
-rw-r--r-- 1 root root   62050 Aug 26 05:42 commons-logging-1.1.3.jar
-rw-r--r-- 1 root root   45054 Aug 26 05:42 elasticsearch-cloud-aws-2.5.0.jar
-rw-r--r-- 1 root root  590533 Aug 26 05:42 httpclient-4.3.5.jar
-rw-r--r-- 1 root root  282269 Aug 26 05:42 httpcore-4.3.2.jar
-rw-r--r-- 1 root root   35058 Aug 26 05:42 jackson-annotations-2.3.0.jar
-rw-r--r-- 1 root root  225316 Aug 26 05:42 jackson-core-2.4.2.jar
-rw-r--r-- 1 root root  915096 Aug 26 05:42 jackson-databind-2.3.2.jar
-rw-r--r-- 1 root root  589289 Aug 26 05:42 joda-time-2.7.jar

name                                    component          version type url
prod-01-data01 cloud-aws          2.5.0   j
prod-01-data03 cloud-aws          2.5.0   j
prod-01-data02 cloud-aws          2.5.0   j

**Comment by niraj8241** [comment]
Just to mention. as a part of triaging i downgraded my cloud-aws plugin to 2.5.0 to match the ES version of 1.5.0

**Comment by dadoonet** [comment]
So only 3 nodes in the full cluster and you don't embed elasticsearch in another JVM or so ?

**Comment by niraj8241** [comment]
Sorry I didn't get your question. What does this mean embed elastic search in another JvM?

**Comment by dadoonet** [comment]
If you don't understand that means you probably don't do it ! :)

Well sometimes Java developers embed ES in their Java web application. I guess you don't use Java for programming, right?

**Comment by niraj8241** [comment]
:) yaah i am poor sys admin who doesn't do java programming.

**Comment by dadoonet** [comment]
Any chance you could upgrade to 1.7 and update aws plugin to 2.7.1?

**Comment by dadoonet** [comment]
No feedback provided. Closing.

Feel free to reopen if you have any more information

**Comment by dadoonet** [comment]
Note that we had a similar report when running AWS plugin and mapper attachments plugin. See https://github.com/elastic/elasticsearch-mapper-attachments/issues/157

**Comment by niraj8241** [comment]
The mapper plugin was recently installed. Not before i posted this question
