### ISSUE TITLE
Problem installing plugins without checksums

### ISSUE THREAD

**Issue by lmenezes** [elastic/elasticsearch#13196]
trying to make kopf work with 2.0-beta1 but I just got:

```
[11:01] leonardo.menezes:elasticsearch-2.0.0-beta1/ $ ./bin/plugin install lmenezes/elasticsearch-kopf/develop
-> Installing lmenezes/elasticsearch-kopf/develop...
Trying http://download.elastic.co/lmenezes/elasticsearch-kopf/elasticsearch-kopf-develop.zip ...
Trying http://search.maven.org/remotecontent?filepath=lmenezes/elasticsearch-kopf/develop/elasticsearch-kopf-develop.zip ...
Trying https://oss.sonatype.org/service/local/repositories/releases/content/lmenezes/elasticsearch-kopf/develop/elasticsearch-kopf-develop.zip ...
Trying https://github.com/lmenezes/elasticsearch-kopf/archive/develop.zip ...
Downloading .................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................DONE
Verifying https://github.com/lmenezes/elasticsearch-kopf/archive/develop.zip checksums if available ...
Trying https://github.com/lmenezes/elasticsearch-kopf/archive/master.zip ...
Downloading ....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................DONE
Verifying https://github.com/lmenezes/elasticsearch-kopf/archive/master.zip checksums if available ...
```

is this the expected behaviour? I will add checksums if necessary, but going from specified branch to master branch in case no checksum is found doesn't seem like the expected outcome(but maybe it is...)

**Comment by dadoonet** [comment]
I think you're right. It's a bug IMO.

In the meantime, could you add to your repo a checksum file? May be not doable with github though...

**Comment by lmenezes** [comment]
yeah, will try that in the afternoon, need to leave now. thanks :)

**Comment by dadoonet** [comment]
You can actually run:

```sh
bin/plugin https://github.com/lmenezes/elasticsearch-kopf/archive/develop.zip
```

So you don't have to provide the checksum file for now.

**Comment by dadoonet** [comment]
I see what is happening. We expect to get a `FileNotFoundException` when we download a checksum file if this one does not exist but we get a `IOException`:

```
Can't get https://github.com/lmenezes/elasticsearch-kopf/archive/develop.zip.sha1 to /var/folders/r_/r14sy86n2zb91jyz1ptb5b4w0000gn/T/elasticsearch-kopf765881667629279646.zip.sha1
```

https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/http/client/HttpDownloadHelper.java#L156-156

Will propose a fix.

**Comment by dadoonet** [comment]
Weird...

We have a stacktrace:

```
java.io.IOException: Can't get https://github.com/lmenezes/elasticsearch-kopf/archive/develop.zip.sha1 to /var/folders/r_/r14sy86n2zb91jyz1ptb5b4w0000gn/T/elasticsearch-kopf2636540761510642632.zip.sha1
	at org.elasticsearch.common.http.client.HttpDownloadHelper$GetThread.downloadFile(HttpDownloadHelper.java:429)
	at org.elasticsearch.common.http.client.HttpDownloadHelper$GetThread.get(HttpDownloadHelper.java:306)
	at org.elasticsearch.common.http.client.HttpDownloadHelper$GetThread.run(HttpDownloadHelper.java:292)
Caused by: java.io.FileNotFoundException: https://github.com/lmenezes/elasticsearch-kopf/archive/develop.zip.sha1
	at sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1675)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1673)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1671)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1244)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.elasticsearch.common.http.client.HttpDownloadHelper$GetThread.downloadFile(HttpDownloadHelper.java:422)
	... 2 more
Caused by: java.io.FileNotFoundException: https://github.com/lmenezes/elasticsearch-kopf/archive/develop.zip.sha1
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1624)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.elasticsearch.common.http.client.HttpDownloadHelper$GetThread.openConnection(HttpDownloadHelper.java:376)
	at org.elasticsearch.common.http.client.HttpDownloadHelper$GetThread.get(HttpDownloadHelper.java:300)
	... 1 more
```

This code is supposed to unwrap the `FileNotFoundException` but it does not:

```java
if (ExceptionsHelper.unwrapCause(e) instanceof FileNotFoundException) {
     // checksum file didn't exist
     return false;
}
```

`unwrapCause()` does not work in our case because we don't have any `ElasticsearchWrapperException` here:

```java
public static Throwable unwrapCause(Throwable t) {
    Throwable result = t;
    while (result instanceof ElasticsearchWrapperException) {
       // Skipped for clarity
    }
    return result;
}
```

I guess this happened when we removed most of the elasticsearch exception and replaced them with standard java exceptions. @s1monw WDYT?

**Comment by clintongormley** [comment]
thanks for reporting this @lmenezes
