### ISSUE TITLE
`beforeIndexShardCreated` listener for indexModule called twice

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#13259]
If I have a plugin that registers a listener for `beforeIndexShardCreated` via the `indexModules` endpoint, as so:

```java
public class ListenerPlugin extends Plugin {
    /** ... other stuff here */
    @Override
    public Collection<Module> indexModules(Settings settings) {
        List<Module> modules = new ArrayList<>(super.indexModules(settings));
        modules.add(new ListenerModule());
        return modules;
    }
}
```

And then does:

```java
public class Listener extends IndicesLifecycle.Listener {

    @Inject
    public Listener(Settings settings, IndicesLifecycle indicesLifecycle, Environment env) {
        indicesLifecycle.addListener(this);
        System.out.println("Listener created!");
    }

    @Override
    public void beforeIndexShardCreated(ShardId shardId, Settings indexSettings) {
        System.out.println("Entering beforeIndexShardCreated()");
        
        System.out.println("Exiting beforeIndexShardCreated()");
    }
}
```

I expect that the listener's `beforeIndexShardCreated` method will only be called once for each newly created shard, however, in some cases, it is called twice.

Here's how I reproduced this:
- Install plugin on all ES nodes
- Start 3 ES nodes
- Create an index with 1 primary shard and 0 replicas

```json
POST /myindex
{
  "index": {
    "number_of_shards": 1,
    "number_of_replicas": 0,
    "data_path": "/tmp/bar/foo",
    "shadow_replicas": true
  }
}
```

- Verify that the shard is created and I see:

Entering beforeIndexShardCreated()
Exiting beforeIndexShardCreated()

**Once**, in the logs (because 1 shard was created)

- Relocate the shard from a node to another node via the `_cluster/reroute` API

Then I see this in the logs:

```
[2015-09-01 15:52:16,468][DEBUG][org.elasticsearch.indices.cluster] [Thermo] [myindex][0] creating shard
Entering beforeIndexShardCreated()
Exiting beforeIndexShardCreated()
Entering beforeIndexShardCreated()
Exiting beforeIndexShardCreated()
```

The listener is being called twice. Looking through the logs, I see the log line `Listener created!` **twice** on this particular node, once when the index was created but no shards were placed on this node, and another time when the actual shard is moved to the node.

It looks like we create class more than once per index, which seems like something we should try to avoid?

**Comment by bleskes** [comment]
@dakrone I tried to find out how this happens the only thing I could suspect is Guice causing two instances of Listener to be created. I would be very curious to see the code of ListenerModule.

**Comment by s1monw** [comment]
@dakrone can you reproduce it and print the stacktrace for each of the invocations?

**Comment by s1monw** [comment]
ok I can reproduce this problem. It's caused by the fact that the master creates the index once before we actually creating it on other nodes to ensure we can fully create it and don't throw an exception. If you print stacktraces it looks like this:

```
[2015-10-08 11:23:50,331][INFO ][org.elasticsearch.index  ] [ListenerIT#testIt]: starting test
[2015-10-08 11:23:50,604][WARN ][LISTENER                 ] Listener created!
java.lang.RuntimeException
	at org.elasticsearch.index.ListenerIT$MyTestListener.<init>(ListenerIT.java:67)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:50)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116)
	at org.elasticsearch.common.inject.InjectorImpl$5$1.call(InjectorImpl.java:828)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:880)
	at org.elasticsearch.common.inject.InjectorImpl$5.get(InjectorImpl.java:823)
	at org.elasticsearch.common.inject.InheritingState.makeAllBindingsToEagerSingletons(InheritingState.java:157)
	at org.elasticsearch.common.inject.InjectorImpl.readOnlyAllSingletons(InjectorImpl.java:909)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:59)
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:347)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:364)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:383)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-10-08 11:23:50,688][INFO ][org.elasticsearch.cluster.metadata] [node_s0] [test] creating index, cause [api], templates [random_index_template], shards [1]/[0], mappings [_default_]
[2015-10-08 11:23:50,710][WARN ][LISTENER                 ] Listener created!
java.lang.RuntimeException
	at org.elasticsearch.index.ListenerIT$MyTestListener.<init>(ListenerIT.java:67)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:50)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116)
	at org.elasticsearch.common.inject.InjectorImpl$5$1.call(InjectorImpl.java:828)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:880)
	at org.elasticsearch.common.inject.InjectorImpl$5.get(InjectorImpl.java:823)
	at org.elasticsearch.common.inject.InheritingState.makeAllBindingsToEagerSingletons(InheritingState.java:157)
	at org.elasticsearch.common.inject.InjectorImpl.readOnlyAllSingletons(InjectorImpl.java:909)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:59)
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:347)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewIndices(IndicesClusterStateService.java:303)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:172)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:493)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

a short term workaround for this is to de-register the listener which it should do anyway like this:
```Java
        @Override
        public void afterIndexClosed(Index index, @IndexSettings Settings indexSettings) {
            lifecycle.removeListener(this);
        }
```

But we should really turn this into an index level component that we destroy once the index is destroyed. ie instead of `IndicesLifecycle` we would have an `IndexLifecycle` that we can trash after the index is destroyed

**Comment by s1monw** [comment]
@dakrone  I am going to push this out to 2.1 for now

**Comment by bleskes** [comment]
That’s indeed why the listener is created twice, but  does it explain why we call beforeIndexShardCreated twice- the master doesn’t create shards... That’s where I got stuck looking at this…

**Comment by s1monw** [comment]
I also think it's not necessarily a bug, if a listener does this it will leak once an index is moved to another node entirely so it has to cleanup after himself.

**Comment by s1monw** [comment]
> That’s indeed why the listener is created twice, but  does it explain why we call beforeIndexShardCreated twice- the master doesn’t create shards... That’s where I got stuck looking at this…

it does never unregister itself. so if you allocate a shard on the node that happens to be the master as well you will AGAIN register the listener (a new instance) once it's actually creating the shard.

**Comment by s1monw** [comment]
here is an output of this test https://gist.github.com/s1monw/1a552a6abb7f63c51e6f

```
...
[2015-10-08 11:39:40,526][WARN ][LISTENER                 ] Listener created!
java.lang.RuntimeException
	at org.elasticsearch.index.ListenerIT$MyTestListener.<init>(ListenerIT.java:67)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:50)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116)
	at org.elasticsearch.common.inject.InjectorImpl$5$1.call(InjectorImpl.java:828)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:880)
	at org.elasticsearch.common.inject.InjectorImpl$5.get(InjectorImpl.java:823)
	at org.elasticsearch.common.inject.InheritingState.makeAllBindingsToEagerSingletons(InheritingState.java:157)
	at org.elasticsearch.common.inject.InjectorImpl.readOnlyAllSingletons(InjectorImpl.java:909)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:59)
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:347)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:364)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:383)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-10-08 11:39:40,714][INFO ][org.elasticsearch.cluster.metadata] [node_s0] [test] creating index, cause [api], templates [random_index_template], shards [1]/[0], mappings [_default_]
[2015-10-08 11:39:40,741][WARN ][LISTENER                 ] Listener created!
java.lang.RuntimeException
	at org.elasticsearch.index.ListenerIT$MyTestListener.<init>(ListenerIT.java:67)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:50)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116)
	at org.elasticsearch.common.inject.InjectorImpl$5$1.call(InjectorImpl.java:828)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:880)
	at org.elasticsearch.common.inject.InjectorImpl$5.get(InjectorImpl.java:823)
	at org.elasticsearch.common.inject.InheritingState.makeAllBindingsToEagerSingletons(InheritingState.java:157)
	at org.elasticsearch.common.inject.InjectorImpl.readOnlyAllSingletons(InjectorImpl.java:909)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:59)
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:347)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewIndices(IndicesClusterStateService.java:303)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:172)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:493)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-10-08 11:39:40,748][WARN ][LISTENER                 ] RUNNING beforeIndexShardCreated() on instance org.elasticsearch.index.ListenerIT$MyTestListener@25e3d50a 
[2015-10-08 11:39:40,748][WARN ][LISTENER                 ] RUNNING beforeIndexShardCreated() on instance org.elasticsearch.index.ListenerIT$MyTestListener@7555bbb0 
[2015-10-08 11:39:40,879][WARN ][LISTENER                 ] RUNNING afterIndexShardCreated() on instance org.elasticsearch.index.ListenerIT$MyTestListener@25e3d50a
[2015-10-08 11:39:40,880][WARN ][LISTENER                 ] RUNNING afterIndexShardCreated() on instance org.elasticsearch.index.ListenerIT$MyTestListener@7555bbb0
```
