### ISSUE TITLE
Test Failure: AwarenessAllocationIT.testAwarenessZones

### ISSUE THREAD

**Issue by alexksikes** [elastic/elasticsearch#13305]
Build URL: http://build-us-00.elastic.co/job/elasticsearch-20-win2012/131/testReport/junit/org.elasticsearch.cluster.allocation/AwarenessAllocationIT/testAwarenessZones/

Reproduce:
```
mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch:elasticsearch -Dtests.seed=179D7B92393C913 -Dtests.class=org.elasticsearch.cluster.allocation.AwarenessAllocationIT -Dtests.method="testAwarenessZones" -Des.logger.level=DEBUG -Des.node.mode=network -Dtests.nightly=false -Dtests.client.ratio=0.0 -Dtests.heap.size=512m -Dtests.jvm.argline="-server -XX:+UseSerialGC -XX:-UseCompressedOops -XX:+AggressiveOpts -Djava.net.preferIPv4Stack=true" -Dtests.locale=de_DE -Dtests.timezone=ACT
```

Stack trace:
```
java.lang.AssertionError: 
Expected: (<2> or <3>)
     but: was <5>
	at __randomizedtesting.SeedInfo.seed([179D7B92393C913:87A23D3AC18A574C]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.elasticsearch.cluster.allocation.AwarenessAllocationIT.testAwarenessZones(AwarenessAllocationIT.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1638)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:847)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:897)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:50)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:46)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:49)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:65)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:48)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:365)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:798)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:458)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:856)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$3.evaluate(RandomizedRunner.java:758)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$4.evaluate(RandomizedRunner.java:792)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:803)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:46)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:42)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:39)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:39)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:54)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:65)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:55)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:365)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tlrx** [comment]
This test fails regularly the last 3 weeks:

----- 

Build URL	http://build-us-00.elastic.co/job/es_core_master_window-2012/1711/
Project:	es_core_master_window-2012
Randomization: 	8u11,network,heap[1024m],-server +UseConcMarkSweepGC -UseCompressedOops +AggressiveOpts
Date of build:	Mon, 07 Sep 2015 21:32:27 +0000
Build duration:	2 hr 46 min

----- 

Build URL	http://build-us-00.elastic.co/job/es_core_master_window-2012/1694/
Project:	es_core_master_window-2012
Randomization: 	8u11,network,heap[512m],-server +UseParallelGC -UseCompressedOops +AggressiveOpts
Date of build:	Fri, 04 Sep 2015 16:11:54 +0000
Build duration:	2 hr 53 min

----- 

Build URL	http://build-us-00.elastic.co/job/elasticsearch-20-win2012/131/
Project:	elasticsearch-20-win2012
Randomization: 	8u11,network,heap[512m],-server +UseSerialGC -UseCompressedOops +AggressiveOpts
Date of build:	Thu, 03 Sep 2015 01:14:29 +0000
Build duration:	2 hr 45 min

----- 

Build URL	http://build-us-00.elastic.co/job/es_core_master_window-2012/1676/
Project:	es_core_master_window-2012
Randomization: 	7u55,network,heap[1024m],-server +UseConcMarkSweepGC -UseCompressedOops,assert off
Date of build:	Tue, 01 Sep 2015 15:02:56 +0000
Build duration:	2 hr 47 min

----- 

Build URL	http://build-us-00.elastic.co/job/elasticsearch-20-win2012/98/
Project:	elasticsearch-20-win2012
Randomization: 	7u55,network,heap[936m],-server +UseParallelGC +UseCompressedOops
Date of build:	Fri, 28 Aug 2015 00:42:24 +0000
Build duration:	2 hr 45 min

----- 


Build URL	http://build-us-00.elastic.co/job/elasticsearch-20-win2008/67/
Project:	elasticsearch-20-win2008
Randomization: 	7u55,network,heap[512m],-server +UseConcMarkSweepGC -UseCompressedOops
Date of build:	Thu, 20 Aug 2015 19:48:41 +0000
Build duration:	1 hr 59 min

**Comment by tlrx** [comment]
After looking at the test and the logs, it looks like all failures have the same scenario. 

I try to explain my understanding, hopefully I'm not completely wrong:

The four nodes are started in an asynchronous manner with min.master.nodes set to 3. Node_t0 starts first and try to find other nodes on localhost with unicast. While it tries successive ports,  node_t1, node_t2 and node_t3 also start (all nodes are started asynchronously).

Node_t0 finally connects to another node (let's say, on the port used by node_t1) and gets back a `RemoteTransportException` because the remote node is still initializing and not yet started.

Then the remote node is started and both nodes, node_t0 and node_t1 are connected.

The same thing happen for node_t2 and node_t3: node_t0 tries to connect and gets a remote exception, then nodes are able to connect to each other.

But once node_t0 is connected to node_1 and node_2 it elects itself as master:
```
[node_t0] elected as master, waiting for incoming joins ([2] needed)
```

and waits for join requests. 

At this point, I suspect that the previous remote exceptions are handled and provoke the disconnection of node_t0 from nodes t1..t3:
```
[2015-09-04 18:30:57,932][DEBUG][discovery.zen            ] [node_t0] elected as master, waiting for incoming joins ([2] needed)
[2015-09-04 18:30:57,932][DEBUG][transport.netty          ] [node_t0] disconnecting from [{#zen_unicast_8_YoSSyfnvSnmF0a8ViPEw7w#}{127.0.0.1}{127.0.0.1:9402}{mode=network, zone=b}] due to explicit disconnect call
[2015-09-04 18:30:57,932][DEBUG][transport.netty          ] [node_t0] disconnecting from [{#zen_unicast_3#}{127.0.0.1}{127.0.0.1:9402}] due to explicit disconnect call
[2015-09-04 18:30:57,932][DEBUG][transport.netty          ] [node_t0] disconnecting from [{#zen_unicast_6_ESxZGa4IQXymN4ZTTRD9kQ#}{127.0.0.1}{127.0.0.1:9401}{mode=network, zone=b}] due to explicit disconnect call
[2015-09-04 18:30:57,932][DEBUG][transport.netty          ] [node_t0] disconnecting from [{#zen_unicast_7_ESxZGa4IQXymN4ZTTRD9kQ#}{127.0.0.1}{127.0.0.1:9401}{mode=network, zone=b}] due to explicit disconnect call
```

node_t0 will wait for joins but nothing will come and after a given delay:
```
[2015-09-04 18:31:23,906][WARN ][discovery                ] [node_t0] waited for 30s and no initial state was set by the discovery
[2015-09-04 18:31:23,906][DEBUG][gateway                  ] [node_t0] can't wait on start for (possibly) reading state from gateway, will do it asynchronously
[2015-09-04 18:31:23,906][INFO ][node                     ] [node_t0] started
```

In the meanwhile, the 3 other nodes keep chatting together and elect another as master:
̀```
[2015-09-04 18:31:01,177][DEBUG][discovery.zen            ] [node_t3] elected as master, waiting for incoming joins ([2] needed)
```

Since the 3 other nodes are correctly connected to each other, the test can create the index "test" with 5 shards / 1 replica that will be allocated on the 3 nodes. With the awareness settings, one of the node will get 5 shards allocated, 2 on another one and 3 on the last one.
