### ISSUE TITLE
Referencing previous initialised variables raises a NullPointerException

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13370]
_From @pedrocunha on March 26, 2015 15:5_

Hello,

The following search request raises a NullPointerException complaining foo is not defined:

```
curl -XPOST "http://localhost:9200/index/model/_search" -d'
{
  "query": {
    "function_score": {
      "script_score": {
        "script": "foo = 2; foo + 2",
        "lang": "python"
      }
    }
  }
}'
```

This is similar to https://github.com/elastic/elasticsearch-lang-python/issues/19 but in this case I'm trying to reference the variable just initialised. I'm using ES 1.4.3 and python plugin 2.4.1. I've tried both 1.5 ES version and the plugin snapshot versions, and the behaviour is the same.

Note that the above is totally valid if we change "lang" to "groovy".

Am I missing out something ?

Please help,
Thank you

_Copied from original issue: elastic/elasticsearch-lang-python#29_

**Comment by dadoonet** [comment]
Actually your python script does not return anything. When function_score API tries to access the value, it generates a NPE.
I think we need to catch it properly in elasticsearch core code itself.

What are you trying to achieve here? Could you illustrate your example with a more concrete use case?
Also, could you put here the full stack trace?

cc @brwe Do you think we should detect that in elasticsearch core to avoid NPE if the language returns null. WDYT?

**Comment by dadoonet** [comment]
_From @pedrocunha on March 30, 2015 8:41_

Ok, some context. My cluster has currently around 1M docs which are used to search. We apply a bunch of filtering and in the end we use the script score to compute some business logic. The script is multi-line and written in groovy. Irrelevant whitespace and comments are then stripped, cached and then sent to ES as a dynamic script (which then ES caches it too). 

This works quite well for us: response time is consistently 30-50ms~ despite the high search query demand.

Groovy is not considered a sandboxed language anymore. So, in theory using Python could make our scripts bit more readable and shorter (if we don't take a performance hit) and that's why I was interested in giving it a try. 

Does that give some real context in this case ?

> Actually your python script does not return anything. When function_score API tries to access the value, it generates a NPE.

```
curl -XPOST "http://localhost:9200/index/model/_search" -d'
{
  "query": {
    "function_score": {
      "script_score": {
        "script": "return 2",
        "lang": "python"
      }
    }
  }
}'
```

Specifying `return` raises a python error:
```
[2015-03-30 09:32:42,076][DEBUG][action.search.type       ] [Belathauzer] [index][2], node[0AjBuVPwSWyjcJJAePpBOw], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@65c6eb62] lastShard [true]
org.elasticsearch.search.SearchParseException: [index][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{
  "query": {
    "function_score": {
      "script_score": {
        "script":"return 2",
        "lang": "python"
      }
    }
  }
}
]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:721)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:557)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:291)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.query.QueryParsingException: [search_development] script_score the script could not be loaded
	at org.elasticsearch.index.query.functionscore.script.ScriptScoreFunctionParser.parse(ScriptScoreFunctionParser.java:93)
	at org.elasticsearch.index.query.functionscore.FunctionScoreQueryParser.parse(FunctionScoreQueryParser.java:133)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:302)
	at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:382)
	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:281)
	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:276)
	at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:705)
	... 9 more
Caused by: SyntaxError: ("'return' outside function", ('<script>', 1, 0, ''))

	at org.python.core.ParserFacade.fixParseError(ParserFacade.java:95)
	at org.python.core.CompilerFacade.compile(CompilerFacade.java:36)
	at org.python.core.Py.compile_flags(Py.java:1823)
	at org.python.core.Py.compile_flags(Py.java:1828)
	at org.python.util.PythonInterpreter.compile(PythonInterpreter.java:277)
	at org.python.util.PythonInterpreter.compile(PythonInterpreter.java:272)
	at org.python.util.PythonInterpreter.compile(PythonInterpreter.java:266)
	at org.elasticsearch.script.python.PythonScriptEngineService.compile(PythonScriptEngineService.java:70)
	at org.elasticsearch.script.ScriptService.compile(ScriptService.java:297)
	at org.elasticsearch.script.ScriptService.search(ScriptService.java:429)
	at org.elasticsearch.index.query.functionscore.script.ScriptScoreFunctionParser.parse(ScriptScoreFunctionParser.java:90)
	... 16 more
```

Full stack of the NullPointerException with the original code:
```
[2015-03-30 09:31:19,067][DEBUG][action.search.type       ] [Belathauzer] All shards failed for phase: [query]
org.elasticsearch.search.query.QueryPhaseExecutionException: [index][4]: query[filtered(function score (ConstantScore(*:*),function=script[foo = 2; foo +2], params [null]))->cache(+_type:property +org.elasticsearch.index.search.nested.NonNestedDocsFilter@55c9b8e4)],from[0],size[10]: Query Failed [Failed to execute main query]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:163)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:286)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:297)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.elasticsearch.script.python.PythonScriptEngineService$PythonSearchScript.runAsDouble(PythonScriptEngineService.java:215)
	at org.elasticsearch.common.lucene.search.function.ScriptScoreFunction.score(ScriptScoreFunction.java:100)
	at org.elasticsearch.common.lucene.search.function.FunctionScoreQuery$FunctionFactorScorer.innerScore(FunctionScoreQuery.java:160)
	at org.elasticsearch.common.lucene.search.function.CustomBoostFactorScorer$AnyNextDoc.score(CustomBoostFactorScorer.java:133)
	at org.elasticsearch.common.lucene.search.function.CustomBoostFactorScorer.score(CustomBoostFactorScorer.java:71)
	at org.apache.lucene.search.TopScoreDocCollector$OutOfOrderTopScoreDocCollector.collect(TopScoreDocCollector.java:140)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:193)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:163)
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:35)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:621)
	at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:191)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:491)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:448)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:281)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:269)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:157)
	... 8 more
```

So a few things:
- It would be great if we could have multi-line python scripts. Maybe specified as an array of strings which then have the right indentation in order to be parsed/eval correctly.
- While it failed above with the return - note that removing the return (and making `script: "2"`) does make the function score work and apply 2 to every document - it would be great if we can make sure early `return`s work as expected.

**Comment by dadoonet** [comment]
_From @pedrocunha on April 7, 2015 10:32_

Any new feedback on this? Thanks.

**Comment by cwarny** [comment]
@dadoonet did you end up finding a workaround? Facing same problem

**Comment by dadoonet** [comment]
May be @pedrocunha did?

**Comment by pedrocunha** [comment]
Workaround for me was staying in Groovy land unfortunately.

**Comment by cwarny** [comment]
Ugh, OK, thanks. Seems like not being able to register multi-line Python scripts defeats the purpose of being able to use Python for ES scripting

**Comment by rjernst** [comment]
Python scripting has been removed in master (6.0).
