### ISSUE TITLE
-Werror is not working with java 9 / jigsaw

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13448]
Does it work with existing java 9 builds at all? 

I get vague compilation failures from maven, with no mention of any warnings or anything, even when running with debugging enabled.

We might need to conditionally disable Werror for java 9, but it would be good to investigate why its not working and get it fixed (seems like a maven bug).

**Comment by rmuir** [comment]
Here is the useless fail you get even with mvn -X
```
[INFO] Compiling 2901 source files to /home/rmuir/workspace/elasticsearch/core/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.709 s
[INFO] Finished at: 2015-09-10T01:24:16-04:00
[INFO] Final Memory: 17M/57M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project elasticsearch: Compilation failure -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project elasticsearch: Compilation failure
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9.0/Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9.0/NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9.0/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@9.0/Method.java:517)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:915)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by rjernst** [comment]
I tried on a java 9 ea build and got the same problem. I will conditionalize -Werror in maven based on java version until we can figure it out.

**Comment by rmuir** [comment]
+1 for that approach. We can get java 9 ea working again and just open a bug with maven or whatever and enable it once we have a version that works.

**Comment by uschindler** [comment]
Hi,
while doing the invokedynamic stuff for string concats, I hit this issue, too. I was finally removing the `-Werror` from the build plugin.

With build 118 the situation gets worse: `Class.newInstance()` gots deprecated in Java 9, so it produces a deprecation warning, too. BUT: as we are targetting Java 8 currently the build, the code developer cannot know if a method is deprecated in Java 9. Because of that we have forbiddenapis, which checks on the deprecated list of Java 8, not the one of 9! Because forbiddenapis already does this, the @deprecated checks by javac could be disabled (at least for JDK signatures).

Personally, I don't like -Werror because of that, because you can never know if future java versions or different JVM vendors introduce as new warnings. So -Xlint:all and then exclude some is bad idea! If you want to fail on warning, be explicit on *which* warning you want to fail, not "all" minus some, because "all" is undefined.

Alternatively only enable -Werror if the compile JVM is the one you expect.

So +1 to add `-Werror` only if the compiler Java version is 1.8. Thats the right thing to do.

**Comment by hub-cap** [comment]
This has been implemented in gradle as of today with java 9
