### ISSUE TITLE
Better logging for when license plugin is missing from a node

### ISSUE THREAD

**Issue by msimos** [elastic/elasticsearch#13445]
Because the license plugin updates the cluster state, any node without the license plugin fails to join the cluster. However because the default logging is INFO the messages about failing to join the cluster state don't show up on either the master node or the node without the license. On the client node which was trying to join all I saw was after setting discovery to TRACE:

[2015-09-09 16:43:36,224][DEBUG][discovery.zen ] [phl-head-03] no master node is set, despite of join request completing. retrying pings.

There should be more information logged at INFO without having to enable DEBUG logging at both the master and the node which fails to join the cluster due to the missing license plugin. This was on Elasticsearch 1.7.1.

**Comment by craigbro** [comment]
If it was going to NOT sync and join the cluster because of the missing plugin, I would expect it to error outright and die, or log it at as big frigging ERROR level -- "hey, I can't sync state because I don't have a plugin the rest of the cluster has." This is not an INFO level fail, this is a "stop the world I want to get off" level ERROR.

**Comment by clintongormley** [comment]
@areek can you take a look at this please?

**Comment by ppf2** [comment]
+1, this affects all clusters that are running plugins that require the license module and if the connection is made via a NodeClient (which includes both Java NodeClient clients as well as the *tribe node*).

On the tribe node scenario, we are currently logging the important details only at the DEBUG level on the cluster the tribe node is attempting to join to.  Such exceptions should be logged at the ERROR or WARN level :)

```
[2015-10-07 22:17:00,133][DEBUG][cluster.service          ] ack received from node [[tribe_node_1/t1][3jIcB_yJSFGxI_w_NDahMg][Iceman][inet[/192.168.1.127:9302]]{client=true, data=false}], cluster_state update (version: 21)
org.elasticsearch.transport.RemoteTransportException: [tribe_node_1/t1][inet[/192.168.1.127:9302]][internal:discovery/zen/publish]
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: No custom index metadata factory registered for type [licenses]
	at org.elasticsearch.cluster.metadata.MetaData.lookupFactorySafe(MetaData.java:130)
	at org.elasticsearch.cluster.metadata.MetaData$Builder.readFrom(MetaData.java:1467)
	at org.elasticsearch.cluster.ClusterState$Builder.readFrom(ClusterState.java:681)
	at org.elasticsearch.discovery.zen.publish.PublishClusterStateAction$PublishClusterStateRequestHandler.messageReceived(PublishClusterStateAction.java:192)
	at org.elasticsearch.discovery.zen.publish.PublishClusterStateAction$PublishClusterStateRequestHandler.messageReceived(PublishClusterStateAction.java:175)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:222)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:114)
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tarass** [comment]
This somehow wasn't affecting us prior to 2.0, but now Java clients can't join cluster as a full client Node because they don't have a license plugin. The worst part is that this was a "silent" behavior.

**Comment by PhaedrusTheGreek** [comment]
+1

Java Node client joins the cluster, and the cluster even reports that the client joined and all seems well:

```
host      ip        heap.percent ram.percent load node.role master name                 
127.0.0.1 127.0.0.1            2         100 2.87 c         -      Some Java Client     
127.0.0.1 127.0.0.1            3         100 2.87 d         *      My ES Instance 
```

If you then execute a search, you get:
```
ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];]
... stack trace ...
```

Or attempt to Index data, you get:

```
MasterNotDiscoveredException[waited for [1m]]
... stack trace ...
```

**Comment by PhaedrusTheGreek** [comment]
Related discussion on this issue from Logstash:
https://discuss.elastic.co/t/receiving-logstash-error-after-installing-watcher-service-unavailable-1-state-not-recovered-initialized-service-unavailable-2-no-master/32721/6

**Comment by PhaedrusTheGreek** [comment]
To enable the License Plugin in the Java Client for version 2.0.0:

```
<dependency>
         <groupId>org.elasticsearch.plugin</groupId>
         <artifactId>license</artifactId>
         <version>2.0.0</version>
</dependency> 
      
```
and
```
Node node = nodeBuilder()
	.settings(Settings.settingsBuilder()
	     .put("node.name", "Some Java Client")
	     .put("path.home", "/tmp/")
	     .put("plugin.types", LicensePlugin.class.getName()
	))
	.client(true)
	.node();
```

**Comment by curu** [comment]
the document of license plugin(or marvel install doc) should explicitly point out the possible problem may arise.and give user a solution.

**Comment by gmoskovicz** [comment]
+1 better logging will help

**Comment by shavo007** [comment]
I tried the approach above and still fails locally!! How do i resolve this?

**Comment by PhaedrusTheGreek** [comment]
@shavo007 , please post your question with configuration examples at https://discuss.elastic.co/, as that will be a better place to expand the troubleshooting discussion.   Please post a link to the discussion back on this issue for reference.
