### ISSUE TITLE
[test] security manager problem with python plugin on windows

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#13467]
`PythonScriptEngineTests` fail with below error on Windows since we switched security manager on per default.

```
 2> REPRODUCE WITH: mvn test -Pdev -pl org.elasticsearch.plugin:lang-python -Dtests.seed=1D11CE3B5E4534A6 -Dtests.class=org.elasticsearch.script.python.PythonScriptEngineTests -Dtests.method="testSimpleEquation" -Des.logger.level=DEBUG -Dtests.nightly=false -Dtests.client.ratio=0.0 -Dtests.heap.size=512m -Dtests.jvm.argline="-server -XX:+UseG1GC -XX:+UseCompressedOops -XX:+AggressiveOpts -Djava.net.preferIPv4Stack=true" -Dtests.locale=mk -Dtests.timezone=Asia/Dhaka
  2> REPRODUCE WITH: mvn test -Pdev -pl org.elasticsearch.plugin:lang-python -Dtests.seed=1D11CE3B5E4534A6 -Dtests.class=org.elasticsearch.script.python.PythonScriptEngineTests -Dtests.method="testSimpleEquation" -Des.logger.level=DEBUG -Dtests.nightly=false -Dtests.client.ratio=0.0 -Dtests.heap.size=512m -Dtests.jvm.argline="-server -XX:+UseG1GC -XX:+UseCompressedOops -XX:+AggressiveOpts -Djava.net.preferIPv4Stack=true" -Dtests.locale=mk -Dtests.timezone=Asia/Dhaka
ERROR   1.47s | PythonScriptEngineTests.testSimpleEquation <<<
   > Throwable #1: java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Users\Administrator\.m2\repository\org\python\jython-standalone\2.7.0" "read")
   > 	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
   > 	at java.security.AccessController.checkPermission(AccessController.java:884)
   > 	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
   > 	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
   > 	at java.io.File.exists(File.java:814)
   > 	at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:434)
   > 	at java.io.File.getCanonicalPath(File.java:618)
   > 	at org.python.core.PySystemState.findRoot(PySystemState.java:750)
   > 	at org.python.core.PySystemState.initRegistry(PySystemState.java:782)
   > 	at org.python.core.PySystemState.doInitialize(PySystemState.java:1045)
   > 	at org.python.core.PySystemState.initialize(PySystemState.java:974)
   > 	at org.python.core.PySystemState.initialize(PySystemState.java:930)
   > 	at org.python.core.PySystemState.initialize(PySystemState.java:925)
   > 	at org.python.core.PySystemState.initialize(PySystemState.java:920)
   > 	at org.python.core.PySystemState.initialize(PySystemState.java:916)
   > 	at org.python.core.ThreadStateMapping.getThreadState(ThreadStateMapping.java:32)
   > 	at org.python.core.Py.getThreadState(Py.java:1440)
   > 	at org.python.core.Py.getThreadState(Py.java:1436)
   > 	at org.python.core.Py.getSystemState(Py.java:1456)
   > 	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:105)
   > 	at org.python.util.PythonInterpreter.threadLocalStateInterpreter(PythonInterpreter.java:81)
   > 	at org.elasticsearch.script.python.PythonScriptEngineService.<init>(PythonScriptEngineService.java:57)
   > 	at org.elasticsearch.script.python.PythonScriptEngineTests.setup(PythonScriptEngineTests.java:48)
   > 	at java.lang.Thread.run(Thread.java:745)Throwable #2: java.lang.NullPointerException
   > 	at org.elasticsearch.script.python.PythonScriptEngineTests.close(PythonScriptEngineTests.java:56)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> REPRODUCE WITH: mvn test -Pdev -pl org.elasticsearch.plugin:lang-python -Dtests.seed=1D11CE3B5E4534A6 -Dtests.class=org.elasticsearch.script.python.PythonScriptEngineTests -Dtests.method="testObjectMapInter" -Des.logger.level=DEBUG -Dtests.nightly=false -Dtests.client.ratio=0.0 -Dtests.heap.size=512m -Dtests.jvm.argline="-server -XX:+UseG1GC -XX:+UseCompressedOops -XX:+AggressiveOpts -Djava.net.preferIPv4Stack=true" -Dtests.locale=mk -Dtests.timezone=Asia/Dhaka
  2> REPRODUCE WITH: mvn test -Pdev -pl org.elasticsearch.plugin:lang-python -Dtests.seed=1D11CE3B5E4534A6 -Dtests.class=org.elasticsearch.script.python.PythonScriptEngineTests -Dtests.method="testObjectMapInter" -Des.logger.level=DEBUG -Dtests.nightly=false -Dtests.client.ratio=0.0 -Dtests.heap.size=512m -Dtests.jvm.argline="-server -XX:+UseG1GC -XX:+UseCompressedOops -XX:+AggressiveOpts -Djava.net.preferIPv4Stack=true" -Dtests.locale=mk -Dtests.timezone=Asia/Dhaka
ERROR   0.06s | PythonScriptEngineTests.testObjectMapInter <<<
   > Throwable #1: java.lang.NullPointerException
   > 	at org.python.core.imp.load(imp.java:713)
   > 	at org.python.core.Py.importSiteIfSelected(Py.java:1558)
   > 	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:116)
   > 	at org.python.util.PythonInterpreter.threadLocalStateInterpreter( don't work wellPythonInterpreter.java:81)
   > 	at org.elasticsearch.script.python.PythonScriptEngineService.<init>(PythonScriptEngineService.java:57)
   > 	at org.elasticsearch.script.python.PythonScriptEngineTests.setup(PythonScriptEngineTests.java:48)
   > 	at java.lang.Thread.run(Thread.java:745)Throwable #2: java.lang.NullPointerException
   > 	at org.elasticsearch.script.python.PythonScriptEngineTests.close(PythonScriptEngineTests.java:56)
   > 	at java.lang.Thread.run(Thread.java:745)
```
Build url:

http://build-us-00.elastic.co/job/es_core_master_window-2008/2201/consoleText

**Comment by rmuir** [comment]
Why was this module not running with security manager before on windows? Is this some bug in the maven build? Some bug in jenkins configuration?

The security manager default change was intended to only impact IDEs.

**Comment by rmuir** [comment]
Separate from that, I knew that python did this, but it only impacts tests for us. We already have a hack for it here (looks like this needs additional permissions to work on windows):

https://github.com/elastic/elasticsearch/blob/master/core/src/test/java/org/elasticsearch/bootstrap/BootstrapForTesting.java#L96-L101

But I really want to know why jenkins on windows wasn't running python with security manager before.

**Comment by rmuir** [comment]
I don't see anything in this python build.xml that would cause this. Looks like tests were never running with securitymanager at all under windows for some maven/jenkins reason. There might be a long tail of things to fix now.

**Comment by clintongormley** [comment]
Windows build are now using the security manager. Closing
