### ISSUE TITLE
Running bin/plugin creates empty log files

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#13557]
Recently, running `bin/plugin` started creating empty log files:
```
-rw-r--r--. 1 root root 0 Sep 14 13:50 elasticsearch_deprecation.log
-rw-r--r--. 1 root root 0 Sep 14 13:50 elasticsearch_index_indexing_slowlog.log
-rw-r--r--. 1 root root 0 Sep 14 13:50 elasticsearch_index_search_slowlog.log
-rw-r--r--. 1 root root 0 Sep 14 13:50 elasticsearch.log

drwxr-xr-x. 2 root          root           4096 Sep 14 13:54 logs
```
The trouble is that they are created as the user that ran `bin/plugin` which is usually `root`. Elasticsearch is never run as root so it fails to create and write to to the logs. It warns pretty mightily:
```
   log4j:ERROR setFile(null,true) call failed.
   java.io.FileNotFoundException: /tmp/elasticsearch/logs/elasticsearch.log (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
        at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
        at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
        at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:223)
        at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
        at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
        at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
        at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
        at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
        at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
        at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:440)
        at org.elasticsearch.common.logging.log4j.LogConfigurator.configure(LogConfigurator.java:116)
        at org.elasticsearch.bootstrap.Bootstrap.setupLogging(Bootstrap.java:187)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:244)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
   log4j:ERROR Either File or DatePattern options are not set for appender [file].
```

You can recreate it with the tar distribution:
```bash
mkdir tmp
cd tmp
tar xf ../elasticsearch-2.1.0-SNAPSHOT.tar.gz
cd elasticsearch*
sudo bin/plugin install file://${SOME_PATH_TO_A_PLUG}
ls -l | grep log
```

Note: if you do this inside vagrant do it in `/tmp` or something. `/elasticsearch` is shared using virtualboxfs and will always be owned by the virtualbox user.

**Comment by nik9000** [comment]
I _think_ this is a non-issue/testing methodology problem. Mostly?

The thing is that when you install elasticsearch using the deb `/var/log/elasticsearch` is created properly and `bin/plugin` doesn't go and create log files owned by root even if you run it as root. Which is how you normally run `bin/plugin`. I just checked it on trusty.

The tar package is different. If you run `bin/plugin` as root there you'll get the problem above. But luckily, you don't really have to run `bin/plugin` as root using the tar distribution. So this is only a problem for silly people like me who always run it as root because they are used to doing so.
