### ISSUE TITLE
RandomShapeGenerator sometimes throws an AssertionError

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#13551]
The actual assert message is pretty unhelpful (`"geom"`) but on debugging it looks like the random shape generator is sometimes creating a self-intersecting polygon which trips this assert in JTS.

Build failure URL: http://build-us-00.elastic.co/job/es_feature_query_refactoring/8930/testReport/junit/org.elasticsearch.index.query/GeoPolygonQueryBuilderTests/testEqualsAndHashcode/

reproduce command:
```
mvn test -Pdev -pl org.elasticsearch:elasticsearch -Dtests.seed=C20B28F0F4F4711B -Dtests.class=org.elasticsearch.index.query.GeoPolygonQueryBuilderTests -Dtests.method="testEqualsAndHashcode" -Des.logger.level=DEBUG -Dtests.assertion.disabled=false -Dtests.heap.size=1024m -Dtests.locale=sr__#Latn -Dtests.timezone=America/North_Dakota/Center
NOTE: leaving temporary files on disk at: /home/jenkins/workspace/es_feature_query_refactoring/core/target/J3/temp/org.elasticsearch.index.query.GeoPolygonQueryBuilderTests_C20B28F0F4F4711B-001
NOTE: test params are: codec=Asserting(Lucene53), sim=RandomSimilarityProvider(queryNorm=false,coord=crazy): {}, locale=sr__#Latn, timezone=America/North_Dakota/Center
```

stack trace (truncated):
```
java.lang.AssertionError: geom
	at __randomizedtesting.SeedInfo.seed([C20B28F0F4F4711B:B304503D3B133834]:0)
	at com.spatial4j.core.shape.jts.JtsGeometry.cutUnwrappedGeomInto360(JtsGeometry.java:460)
	at com.spatial4j.core.shape.jts.JtsGeometry.<init>(JtsGeometry.java:85)
	at org.elasticsearch.common.geo.builders.ShapeBuilder.jtsGeometry(ShapeBuilder.java:92)
	at org.elasticsearch.common.geo.builders.BasePolygonBuilder.build(BasePolygonBuilder.java:170)
	at org.elasticsearch.test.geo.RandomShapeGenerator.createShape(RandomShapeGenerator.java:220)
	at org.elasticsearch.test.geo.RandomShapeGenerator.createShape(RandomShapeGenerator.java:223)
	at org.elasticsearch.test.geo.RandomShapeGenerator.createShape(RandomShapeGenerator.java:142)
	at org.elasticsearch.test.geo.RandomShapeGenerator.createShapeWithin(RandomShapeGenerator.java:87)
	at org.elasticsearch.index.query.GeoPolygonQueryBuilderTests.randomPolygon(GeoPolygonQueryBuilderTests.java:113)
	at org.elasticsearch.index.query.GeoPolygonQueryBuilderTests.doCreateTestQueryBuilder(GeoPolygonQueryBuilderTests.java:49)
	at org.elasticsearch.index.query.GeoPolygonQueryBuilderTests.doCreateTestQueryBuilder(GeoPolygonQueryBuilderTests.java:44)
	at org.elasticsearch.index.query.AbstractQueryTestCase.createTestQueryBuilder(AbstractQueryTestCase.java:251)
	at org.elasticsearch.index.query.AbstractQueryTestCase.testEqualsAndHashcode(AbstractQueryTestCase.java:420)
```

**Comment by jaymode** [comment]
Another failure: http://build-us-00.elastic.co/job/es_core_2x_strong/128/testReport/junit/org.elasticsearch.search.geo/GeoShapeIntegrationIT/testPointsOnly/

Reproduces with:
```
mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch:elasticsearch -Dtests.seed=A4335303BE97F8F7 -Dtests.class=org.elasticsearch.search.geo.GeoShapeIntegrationIT -Dtests.method="testPointsOnly" -Des.logger.level=DEBUG -Des.node.mode=local -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=1003m -Dtests.locale=es_CO -Dtests.timezone=America/Indiana/Tell_City
```
