### ISSUE TITLE
NPE when deleting an index whose files have the wrong permissions

### ISSUE THREAD

**Issue by avleen** [elastic/elasticsearch#13577]
[2015-09-06 09:30:01,684][WARN ][cluster.action.index     ] [hostname] [logstash-2015.08.06]failed to ack index store deleted for  index
java.lang.NullPointerException
        at org.elasticsearch.indices.IndicesService$PendingDelete.toString(IndicesService.java:665)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at java.util.AbstractCollection.toString(AbstractCollection.java:462)
        at org.elasticsearch.indices.IndicesService.processPendingDeletes(IndicesService.java:734)
        at org.elasticsearch.cluster.action.index.NodeIndexDeletedAction.lockIndexAndAck(NodeIndexDeletedAction.java:125)
        at org.elasticsearch.cluster.action.index.NodeIndexDeletedAction.access$500(NodeIndexDeletedAction.java:49)
        at org.elasticsearch.cluster.action.index.NodeIndexDeletedAction$2.doRun(NodeIndexDeletedAction.java:113)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

The directory tree for the shard for this index became owned by root. When we sent a request to delete the index, ES threw back lots of errors that it couldn't delete the various files on disk, and then hit this NPE.

**Comment by clintongormley** [comment]
Hiya @avleen 

Trying to replicate on 1.7.1 but it seems to work OK. I just chowned data/elasticsearch/nodes/0/

What version are you on? And what path exactly had the wrong owner?

**Comment by bleskes** [comment]
@avleen - which ES version is this?

**Comment by avleen** [comment]
Hey folks,

Terribly sorry for the delay. This should be 1.6.1 I think.

**Comment by clintongormley** [comment]
@avleen any more information on which path had the bad perms?

**Comment by clintongormley** [comment]
Nothing further. Closing
