### ISSUE TITLE
Logger name doesn't correspond to logging config

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#13658]
Log messages used to remove the `org.elasticsearch.` prefix from the logger name, eg:

     [2015-09-18 18:15:00,996][TRACE][discovery.zen.ping.unicast] [U-Man] [1] disconnecting from...

In 2.0.0-beta2 it logs this line as:

    [2015-09-18 18:15:00,996][TRACE][org.elasticsearch.discovery.zen.ping.unicast] [U-Man] [1] disconnecting from...

The `config/logging.yml` still refers to the logger names without the prefix, eg:

      # discovery
      discovery: TRACE

This needs to be changed to the following to work:

      # discovery
      org.elasticsearch.discovery: TRACE

Personally I'd prefer to go back to removing the prefix, but not sure if there was a reason for adding the prefix in?  Either way, the config file should be consistent with what we do in practice.

**Comment by pickypg** [comment]
I ran out of time to chase down the appropriate fix, but this is the first _static_ use of the `Loggers` class, which is triggering the system property to be read _before_ it's set in `org.elasticsearch.bootstrap.Bootstrap`.

```
	at org.elasticsearch.common.logging.Loggers.<clinit>(Loggers.java:44) // I added a static block to catch it
	at org.elasticsearch.common.MacAddressProvider.<clinit>(MacAddressProvider.java:32)
	at org.elasticsearch.common.TimeBasedUUIDGenerator.<clinit>(TimeBasedUUIDGenerator.java:38)
	at org.elasticsearch.common.Strings.<clinit>(Strings.java:64)
	at org.elasticsearch.common.settings.Settings$Builder.replacePropertyPlaceholders(Settings.java:1178)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.initializeSettings(InternalSettingsPreparer.java:158)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:84)
	at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:107)
	at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:100)
	at org.elasticsearch.bootstrap.BootstrapCLIParser.<init>(BootstrapCLIParser.java:48)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:222)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

Simplest fix is to just put the system property at the top of the `org.elasticsearch.bootstrap.Bootstrap#init` method.
