### ISSUE TITLE
RepositoryS3RestIT fails when no network is available

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13686]
```
Suite: org.elasticsearch.repositories.s3.RepositoryS3RestIT
  2> REPRODUCE WITH: mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch.plugin:repository-s3 -Dtests.seed=1368C600E5FF263C -Dtests.class=org.elasticsearch.repositories.s3.RepositoryS3RestIT -Dtests.method="test {yaml=repository_s3/20_repository/S3 repository can be registereed}" -Des.logger.level=ERROR -Dtests.cluster=localhost:9500 -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=mt_MT -Dtests.timezone=Australia/Eucla -Dtests.rest.suite=repository_s3
FAILURE 11.4s | RepositoryS3RestIT.test {yaml=repository_s3/20_repository/S3 repository can be registereed} <<<
   > Throwable #1: java.lang.AssertionError: expected [2xx] status code but api [snapshot.create_repository] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"repository_exception","reason":"[test_repo_s3_1] failed to create repository"}],"type":"repository_exception","reason":"[test_repo_s3_1] failed to create repository","caused_by":{"type":"creation_exception","reason":"Guice creation errors:\n\n1) Error injecting constructor, com.amazonaws.AmazonClientException: Unable to execute HTTP request: s3.amazonaws.com\n  at org.elasticsearch.repositories.s3.S3Repository.<init>(Unknown Source)\n  while locating org.elasticsearch.repositories.s3.S3Repository\n  while locating org.elasticsearch.repositories.Repository\n\n1 error","caused_by":{"type":"amazon_client_exception","reason":"Unable to execute HTTP request: s3.amazonaws.com","caused_by":{"type":"unknown_host_exception","reason":"s3.amazonaws.com"}}}},"status":500}]
```

Caused by `{"type":"unknown_host_exception","reason":"s3.amazonaws.com"}`

**Comment by dadoonet** [comment]
Was testing that again in master and it still fails.

```
Suite: org.elasticsearch.repositories.s3.RepositoryS3RestIT
  1> [2016-07-21 15:15:18,644][INFO ][org.elasticsearch.test.rest.client] REST client initialized [http://[::1]:53710], elasticsearch version: [5.0.0-alpha5]
  1> [2016-07-21 15:15:18,652][INFO ][org.elasticsearch.test.rest.client] REST client initialized [http://[::1]:53710], elasticsearch version: [5.0.0-alpha5]
  1> [2016-07-21 15:15:28,319][INFO ][org.elasticsearch.repositories.s3] Stash dump on failure [{
  1>   "stash" : { }
  1> }]
  2> REPRODUCE WITH: gradle :plugins:repository-s3:integTest -Dtests.seed=39589EDC630B851 -Dtests.class=org.elasticsearch.repositories.s3.RepositoryS3RestIT -Dtests.method="test {yaml=repository_s3/20_repository/S3 repository can be registered}" -Dtests.security.manager=true -Dtests.locale=ar-KW -Dtests.timezone=Pacific/Yap
FAILURE 10.2s | RepositoryS3RestIT.test {yaml=repository_s3/20_repository/S3 repository can be registered} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected [2xx] status code but api [snapshot.create_repository] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"repository_exception","reason":"[test_repo_s3_1] failed to create repository"}],"type":"repository_exception","reason":"[test_repo_s3_1] failed to create repository","caused_by":{"type":"amazon_client_exception","reason":"Unable to execute HTTP request: s3.amazonaws.com","caused_by":{"type":"unknown_host_exception","reason":"s3.amazonaws.com"}}},"status":500}]
   >    at __randomizedtesting.SeedInfo.seed([39589EDC630B851:8BC1B63768CCD5A9]:0)
   >    at org.elasticsearch.test.rest.section.DoSection.execute(DoSection.java:108)
   >    at org.elasticsearch.test.rest.ESRestTestCase.test(ESRestTestCase.java:399)
   >    at java.lang.Thread.run(Thread.java:745)
```

Not sure yet how we can skip the REST tests for this plugin if no internet connection is available.

**Comment by javanna** [comment]
@dadoonet is this still valid? Maybe we should have a network feature in our rest tests so that this test is run only when we know we have network?

**Comment by dadoonet** [comment]
Well. This one is 2 years old now and no one else seemed to complain about it so I think we can close it.
