### ISSUE TITLE
Allow node to start up even if script.disable_dynamic is configured in 2.x+

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#13756]
From 2.x branch, if script.disable_dynamic is set in the configuration, we throw the following exception:

```
Exception in thread "main" java.lang.IllegalArgumentException: script.disable_dynamic is not a supported setting, replace with fine-grained script settings. 
Dynamic scripts can be enabled for all languages and all operations by replacing `script.disable_dynamic: false` with `script.inline: on` and `script.indexed: on` in elasticsearch.yml
	at org.elasticsearch.script.ScriptService.<init>(ScriptService.java:146)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at <<<guice>>>
	at org.elasticsearch.node.Node.<init>(Node.java:202)
	at org.elasticsearch.node.Node.<init>(Node.java:129)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:168)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:268)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```
But then the ES process quits and will not start up.  A better behavior will be for it to just throw the exception, ignore the script.disable_dynamic setting and still allow the ES node to start up.

**Comment by rmuir** [comment]
I dont understand why we should be lenient, I think its good to fail on configuration errors.

**Comment by ppf2** [comment]
I am more thinking about potential surprise when folks upgrade to 2.x.  As much as we hope that admins out there will thoroughly test and read the documentation on breaking changes, this is unfortunately not always the case, so I am just wondering if it is better to still allow the node to start up and just continue to throw these exceptions to the log on every start up (or attempt to invoke scripting when it is disabled) just to remind the admins to do some clean up.  But I do see your point here, this will simply shift the surprise to when they actually have to use scripting/runtime :)

**Comment by dadoonet** [comment]
Can the migration plugin catch that?

**Comment by clintongormley** [comment]
No it can't.  The error message is self explanatory, and it is an easy fix.  Also the fact that it is an error that prevents startup means the user won't miss it.

Nothing to do here.

**Comment by magec** [comment]
I'm facing that error and came across this PR, agree that I should read the doc, and that it should fail.
