### ISSUE TITLE
Elastic search 2.0.0-beta2  zip package does not start on ubuntu

### ISSUE THREAD

**Issue by silvestrelosada** [elastic/elasticsearch#13785]
I'm running several installations of elasticsearch 1.X on ubuntu laptop without any issues, that installatios are made from zip. I downloaded version and when I try to run  I found this error.

Exception in thread "main" java.lang.IllegalStateException: failed to load bundle [] due to jar hell
Likely root cause: java.security.AccessControlException: access denied ("java.io.FilePermission" "/usr/share/java/jayatanaag.jar" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:372)
	at java.security.AccessController.checkPermission(AccessController.java:559)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at java.util.zip.ZipFile.<init>(ZipFile.java:206)
	at java.util.zip.ZipFile.<init>(ZipFile.java:145)
	at java.util.jar.JarFile.<init>(JarFile.java:154)
	at java.util.jar.JarFile.<init>(JarFile.java:91)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:116)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:345)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:112)
	at org.elasticsearch.node.Node.<init>(Node.java:144)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:168)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:266)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

Jayatana is installed by default on ubuntu to support global menu.

**Comment by rmuir** [comment]
I think we should unset JAVA_TOOL_OPTIONS in our startup script...

**Comment by silvestrelosada** [comment]
If I disabe jayatana on my ubuntu seems to work well

**Comment by rmuir** [comment]
Yeah, I think we should just do it for you so people don't experience problems, and don't need to disable it (e.g. we disable it for elasticsearch, because we don't want it)

**Comment by s1monw** [comment]
+1 @rmuir

**Comment by rmuir** [comment]
And warn if it contains anything. Basically saying, hey look, we are ignoring this stuff, if you want to pass stuff to java, use JAVA_OPTS. That way there are no surprises.

**Comment by rmuir** [comment]
Thank you for testing the beta and reporting this.
