### ISSUE TITLE
native scripts docs are out of date

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13811]
I don't think this is going to work:

```
Note, the scripts need to be in the classpath of elasticsearch. One simple way to do it is to create a directory under plugins (choose a descriptive name), and place the jar / classes files there. They will be automatically loaded.
```

We should recommend something else, e.g. to put the jar in lib/, if they are supposed to be in the main classpath.

**Comment by dadoonet** [comment]
Nice catch. I wonder if we should look by default in a specific user dir so upgrading elasticsearch would be easier?

Load scripts from plugins._scripts for example?

**Comment by rmuir** [comment]
If we do that, then the fix is more complex than a doc one. I think we should do the simple doc fix for 2.0? what percentage of users are using native scripts?

Separately, I tend to agree it would be cleaner, there is something to be said for "improving" native script support by loading the user classes in a child loader (versus encouraging them to put them in lib/ which will be the main classpath). The downside is that if we do that, we should really add e.g. a qa scenario that tests it, since its more involved. 

I'm also hesitant to overhaul native script support, since scripting engine support is currently also undergoing refactoring in master, and we might want to do things completely differently there (e.g. perhaps native scripting is a plugin or something, i dont know, have not even looked at it).

**Comment by rjernst** [comment]
I think we should just stick to a doc fix for now. At the moment, native scripts must now be loaded through a plugin. We can think about how we could make it easier for 2.1 or 2.2 (although I personally think a plugin is the right thing here), but that's the way it is for 2.0.

**Comment by dadoonet** [comment]
Agreed

**Comment by ppf2** [comment]
+1.  If they follow the current procedure in the native script documentation today, they will not be able to start up the ES node in 2.x (as expected).  

```
Exception in thread "main" java.lang.IllegalStateException: Unable to initialize plugins
Likely root cause: java.nio.file.NoSuchFileException: /ELK/elasticsearch-2.1.0-SNAPSHOT/plugins/test/plugin-descriptor.properties
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
    at java.nio.file.Files.newByteChannel(Files.java:315)
    at java.nio.file.Files.newByteChannel(Files.java:361)
    at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:380)
    at java.nio.file.Files.newInputStream(Files.java:106)
    at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:86)
    at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:301)
    at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:107)
    at org.elasticsearch.node.Node.<init>(Node.java:148)
    at org.elasticsearch.node.Node.<init>(Node.java:129)
    at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:168)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:268)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```

As part of the doc resolution to this ticket, let's also include this in our breaking changes documentation (https://www.elastic.co/guide/en/elasticsearch/reference/2.0/_plugin_and_packaging_changes.html and/or https://www.elastic.co/guide/en/elasticsearch/reference/2.0/_scripting_changes.html). Thx!

**Comment by harpreetsb** [comment]
has this been fixed
We upgraded to the ES2.0 and tried restarting it and
```
[2015-10-30 01:34:45,391][INFO ][node                     ] [Spitfire] version[2.0.0], pid[5824], build[de54438/2015-10-22T08:09:48Z]
[2015-10-30 01:34:45,392][INFO ][node                     ] [Spitfire] initializing ...
[2015-10-30 01:34:45,405][ERROR][bootstrap                ] Exception
java.lang.IllegalStateException: Unable to initialize plugins
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:115)
        at org.elasticsearch.node.Node.<init>(Node.java:144)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/plugins/_site/plugin-descriptor.properties
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:86)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:306)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:112)
        ... 5 more

```

**Comment by dadoonet** [comment]
Did you create the descriptor file? https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugin-authors.html#_plugin_descriptor_file

**Comment by harpreetsb** [comment]
No nothing, but i already had few plugins

**Comment by harpreetsb** [comment]
Weird that things work fine on my local machine,
But on my local machine  when i do
`sudo service elasticsearch status`
I get 
`elasticsearch is not running`
 BUT
'http://localhost:9200/' return 
```json
{
  "status" : 200,
  "name" : "Orphan",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.4.4",
    "build_hash" : "c88f77ffc81301dfa9dfd81ca2232f09588bd512",
    "build_timestamp" : "2015-02-19T13:05:36Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.3"
  },
  "tagline" : "You Know, for Search"
}

```

**Comment by dadoonet** [comment]
I don't understand. You wrote elasticsearch 2.0 but here it's 1.4.4.

Feel free to ask your questions on discuss.elastic.co.

**Comment by harpreetsb** [comment]
oh well i had to delete all previous node data to get the new version running..
I wil post here later onces i configure mine and see if our online server does not give same error.
