### ISSUE TITLE
Exception in 2.0.0-beta2: "java.nio.file.AccessDeniedException: /var/cache/ldconfig"

### ISSUE THREAD

**Issue by BCWilsonDotCom** [elastic/elasticsearch#13864]
While trying to start up elasticsearch 2.0.0 beta2 I'm running into:

```
[2015-09-29 16:00:30,019][ERROR][org.elasticsearch.bootstrap] Exception
java.nio.file.AccessDeniedException: /var/cache/ldconfig
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:426)
    at java.nio.file.Files.newDirectoryStream(Files.java:413)
    at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:179)
    at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
    at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
    at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
    at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69)
    at java.nio.file.Files.walkFileTree(Files.java:2602)
    at java.nio.file.Files.walkFileTree(Files.java:2635)
    at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:137)
    at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:86)
    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:154)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:266)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

**Comment by rmuir** [comment]
Why is this in your classpath?

**Comment by rmuir** [comment]
And if you run with -Des.logger.level=DEBUG, you will get a lot of information, that might tell us why the system is misconfigured like that, the classpath shouldn't contain directories like that, that you don't have access to.

**Comment by BCWilsonDotCom** [comment]
Why is /var/cache/ldconfig in the classpath? It isn't as far as I can tell.

ES_CLASSPATH is `ES_CLASSPATH=$ES_CLASSPATH:$ES_HOME/lib/*:$ES_HOME/lib/sigar/*`

If I open up permissions on that dir it keeps trying to access various directories and fails with the same exception.

Directories it's complained about:
```
/var/cache/ldconfig
/var/lib/polkit-1
/var/lib/sudo
```

Also, I put `-Des.logger.level=DEBUG` into my elasticsearch-env.sh file and it doesn't appear to show any additional output in the log file.

**Comment by rmuir** [comment]
You aren't running 2.0-beta2, but some frankenstein installation:

rmuir@beast:~/Downloads/elasticsearch-2.0.0-beta2$ fgrep -r sigar .
rmuir@beast:~/Downloads/elasticsearch-2.0.0-beta2$

**Comment by nik9000** [comment]
> You aren't running 2.0-beta2, but some frankenstein installation:

Can you post the steps you took to get here?

**Comment by BCWilsonDotCom** [comment]
It looks like this was an issue caused by our config management system, chef in this case, mixing older ES 1.7 scripts with ES 2.0.

**Comment by clintongormley** [comment]
thanks for letting us know @BCWilsonDotCom
