### ISSUE TITLE
SharedClusterSnapshotRestoreIT. deleteSnapshotWithMissingIndexAndShardMetadataTest test failure

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#13904]
I hit this failing seed on master ... not sure why it's failing:

```
Started J0 PID(19725@Michaels-MacBook-Pro-2.local).
Suite: org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT
  2> REPRODUCE WITH: mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch:elasticsearch -Dtests.seed=8EEF26FBB2DE1802 -Dtests.class=org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT -Dtests.method="deleteSnapshotWithMissingIndexAndShardMetadataTest" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=fr_FR -Dtests.timezone=Canada/Yukon
FAILURE 4.62s | SharedClusterSnapshotRestoreIT.deleteSnapshotWithMissingIndexAndShardMetadataTest <<<
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <11>
   >      but: was <9>
   > 	at __randomizedtesting.SeedInfo.seed([8EEF26FBB2DE1802:FC339B914AD34F7]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.deleteSnapshotWithMissingIndexAndShardMetadataTest(SharedClusterSnapshotRestoreIT.java:835)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> NOTE: leaving temporary files on disk at: /Users/mike/src/es.clean/core/target/J0/temp/org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT_8EEF26FBB2DE1802-002
  2> NOTE: test params are: codec=Asserting(Lucene53): {_field_names=PostingsFormat(name=Asserting), foo=PostingsFormat(name=Asserting), _type=PostingsFormat(name=Asserting), _uid=PostingsFormat(name=Asserting), _all=PostingsFormat(name=Asserting)}, docValues:{_version=DocValuesFormat(name=Asserting)}, sim=RandomSimilarityProvider(queryNorm=false,coord=yes): {}, locale=fr_FR, timezone=Canada/Yukon
  2> NOTE: Mac OS X 10.10.4 x86_64/Oracle Corporation 1.8.0_40 (64-bit)/cpus=4,threads=1,free=400935864,total=514850816
  2> NOTE: All tests run in this JVM: [SharedClusterSnapshotRestoreIT]
Completed [1/1] in 5.81s, 1 test, 1 failure <<< FAILURES!
```

**Comment by clintongormley** [comment]
old report - closing
