### ISSUE TITLE
setting network.bind_host: localhost and publish_host: _ens192:ipv4_ uses localhost only

### ISSUE THREAD

**Issue by cristifalcas** [elastic/elasticsearch#13921]
We wanted to set the REST API of an elasticsearch cluster to localhost and proxy all requests with a web proxy (apache), but to let the cluster find the nodes via the main interface. But it looks like it will bind to the local interface only.

Those are the ports opened by elasticsearch process:

    # netstat -tulpn | grep 20438
    tcp6       0      0 127.0.0.1:9200          :::*                    LISTEN      20438/java
    tcp6       0      0 127.0.0.1:9300          :::*                    LISTEN      20438/java
    udp6       0      0 :::54328                :::*                                20438/java

This is the relevant configuration from /etc/elasticsearch/es-01/elasticsearch.yml:

    network:
      publish_host: _ens192:ipv4_
      bind_host: localhost

Those are the startup log messages:

    starting ...
    bound_address {inet[/127.0.0.1:9300]}, publish_address {inet[/10.220.10.105:9300]}
    optymyze_Romania/XPSgcKuQSteNJfNwyWIsTg
    new_master [v-so-repo-05.synygy.net-es-01][XPSgcKuQSteNJfNwyWIsTg][v-so-repo-05.synygy.net][inet[/10.220.10.105:9300]]{host=v-so-repo-05.synygy}, reason: zen-disco-join (elected_as_master)
    delaying initial state recovery for [5m]. recover_after_time was set to [5m]
    bound_address {inet[/127.0.0.1:9200]}, publish_address {inet[/10.220.10.105:9200]}
    started

Here is an exception thrown shortly after starting:

    [inet[/10.220.10.105:9300]] connect_timeout[30s]
	    at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:825)
	    at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:758)
	    at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:731)
	    at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:216)
	    at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:584)
	    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	    at java.lang.Thread.run(Thread.java:722)
    Caused by: java.net.ConnectException: Connection refused: /10.220.10.105:9300
	    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:701)
	    at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	    at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	    at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	    at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	    at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	    at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	    ... 3 more

**Comment by clintongormley** [comment]
@cristifalcas Elasticsearch only listens on the bind host, whatever you set publish host to.  If you only listen to bind host, then your nodes won't be able to contact each other.
