### ISSUE TITLE
SearchWhileCreatingIndexIT.testNoReplicas test failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#13987]
build link: http://build-us-00.elastic.co/job/es_core_master_centos/7914/consoleText

actual failure: 

```
FAILURE 6.77s J0 | SearchWhileCreatingIndexIT.testNoReplicas <<<
   > Throwable #1: java.lang.AssertionError: Hit count is 0 but 1 was expected.  Total shards: 6 Successful shards: 5 & 0 shard failures:
   > 	at __randomizedtesting.SeedInfo.seed([1E2B6029CF6723AD:F05D84A395793CC1]:0)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertHitCount(ElasticsearchAssertions.java:212)
   > 	at org.elasticsearch.search.basic.SearchWhileCreatingIndexIT.searchWhileCreatingIndex(SearchWhileCreatingIndexIT.java:81)
   > 	at org.elasticsearch.search.basic.SearchWhileCreatingIndexIT.testNoReplicas(SearchWhileCreatingIndexIT.java:47)
   > 	at java.lang.Thread.run(Thread.java:745)
```

This failure does __not__ reproduce for me with: 

```
mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch:elasticsearch -Dtests.seed=1E2B6029CF6723AD -Dtests.class=org.elasticsearch.search.basic.SearchWhileCreatingIndexIT -Dtests.method="testNoReplicas" -Des.logger.level=DEBUG -Des.node.mode=local -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=el -Dtests.timezone=Pacific/Tarawa
```

**Comment by clintongormley** [comment]
Old test failure. Closing

**Comment by jasontedor** [comment]
Relates #16208
