### ISSUE TITLE
Document details about config file name suffix impact on parser used

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#14081]
Config files can be defined in YAML or JSON format.  In most cases the examples are in yaml, but it seems that in some cases a file without a suffix can be interpreted as JSON (even if it is YAML) which will fail.

> @spinscale 
> _Elasticsearch has the notion of a XContent construct, which can either be YAML, JSON, SMILE or CBOR and is usually detected by its first characters_

In specific example, a file was created `shield/user_roles` (note: no `.yml` suffix!) which resulted in this error:

```
[2015-10-11 11:54:23,475][ERROR][shield.authc.support ] [node1] failed to parse role mappings file [/etc/elasticsearch/shield/role_mapping]. skipping/removing all mappings... 
org.elasticsearch.common.settings.SettingsException: Failed to load settings from [/etc/elasticsearch/shield/role_mapping] 
at org.elasticsearch.common.settings.ImmutableSettings$Builder.loadFromStream(ImmutableSettings.java:985) 
at org.elasticsearch.shield.authc.support.DnRoleMapper.parseFile(DnRoleMapper.java:118) 
at org.elasticsearch.shield.authc.support.DnRoleMapper.parseFileLenient(DnRoleMapper.java:102) 
at org.elasticsearch.shield.authc.support.DnRoleMapper.<init>(DnRoleMapper.java:73) 
at org.elasticsearch.shield.authc.ldap.LdapRealm$Factory.create(LdapRealm.java:63) 
at org.elasticsearch.shield.authc.ldap.LdapRealm$Factory.create(LdapRealm.java:43) 
at org.elasticsearch.shield.authc.Realms.initRealms(Realms.java:114) 
at org.elasticsearch.shield.authc.Realms.doStart(Realms.java:56) 
at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:85) 
at org.elasticsearch.node.internal.InternalNode.start(InternalNode.java:238) 
at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:128) 
at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:216) 
at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32) 
Caused by: org.elasticsearch.common.jackson.core.JsonParseException: Unrecognized token 'admin': was expecting ('true', 'false' or 'null') 
at [Source: admin: 
- "cn=ABC123,ou=Users,dc=corporate" 
; line: 1, column: 6] 
at org.elasticsearch.common.jackson.core.JsonParser._constructError(JsonParser.java:1419) 
at org.elasticsearch.common.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508) 
at org.elasticsearch.common.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2300) 
at org.elasticsearch.common.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1459) 
at org.elasticsearch.common.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:683) 
at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:51) 
at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(XContentSettingsLoader.java:60) 
at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(XContentSettingsLoader.java:45) 
at org.elasticsearch.common.settings.ImmutableSettings$Builder.loadFromStream(ImmutableSettings.java:982) 
... 12 more 
```

Suggest more explicit documentation around config file type options and the rules governing how the format is guessed if not obvious by file suffix.

**Comment by spinscale** [comment]
the config file you are referring to is not an ordinary config file, but one that is not `xContent` compatible, as it basically looks like `/etc/group`. The config file in the exception is another shield file, that indeed is load by `xContent` mechanisms

Checking the exception this is indeed a problem due to `SettingsLoaderFactory.loadFromResource()`, which is checking for the file suffixes and falls back to JSON, see https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/settings/loader/SettingsLoaderFactory.java#L37-L48

**Comment by robin13** [comment]
So is this a problem with the config loader, or with the documentation?  I am confused as to what file formats are possible for which configuration files...

**Comment by spinscale** [comment]
IMO updating the docs to mention the default is JSON (except for files ending in `.yml`, `.yaml` or `.properties` is fine from how I read your problem... but maybe I misunderstood you

**Comment by debadair** [comment]
As of 2.0, Elasticsearch settings are always specified in YAML. From 5.0 onward, security settings are specified in YAML or the Elasticsearch keystore.
