### ISSUE TITLE
Spurious File Not Found Exception

### ISSUE THREAD

**Issue by ankrugold** [elastic/elasticsearch#14106]
Hi ,
We have deployed ES 1.4 on AWS using EBS as storage, we recently started seeing some issues with index in which index remains unassigned , we see a FileNotFoundException in the logs .the file is a lucene file ,  we deleted the shard folder and restarted cluster after which we start getting FIleNotFoundExceptions again while Recovering , so we clean up the whole data path folder and expect that the machine should recover since all primaries are assigned , cluster is in yellow state. However same FileNotFound Exception and recovery fails,

2015-10-14 00:54:47,095 WARN  [org.elasticsearch.indices.cluster] (elasticsearch[Captain Germany][generic][T#9]) [Captain Germany] [indexName][2] failed to start shard
org.elasticsearch.indices.recovery.RecoveryFailedException: [indexName][2]: Recovery failed from [Guido Carosella][aBOW6HyxSDG6hkbUrlSwLw][indexName01.xyz.xyz.com][inet:9300]]{zone=us-east-1a} into [Captain Germany][wXPQlst-QyCBx39CoJWcQA][indexName03.xyz.xyz.com][inet[/:9300]]{zone=us-east-1d}
        at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:308)
        at org.elasticsearch.indices.recovery.RecoveryTarget.access$200(RecoveryTarget.java:65)
        at org.elasticsearch.indices.recovery.RecoveryTarget$3.run(RecoveryTarget.java:186)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.transport.RemoteTransportException: [Guido Carosella][inet[/:9300]][internal:index/shard/recovery/start_recovery]
Caused by: org.elasticsearch.index.engine.RecoveryEngineException: [entity_2015100804][2] Phase[1] Execution failed
        at org.elasticsearch.index.engine.internal.InternalEngine.recover(InternalEngine.java:1120)
        at org.elasticsearch.index.shard.service.InternalIndexShard.recover(InternalIndexShard.java:654)
        at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:137)
        at org.elasticsearch.indices.recovery.RecoverySource.access$2600(RecoverySource.java:74)
        at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:464)
        at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:450)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.run(MessageChannelHandler.java:275)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.indices.recovery.RecoverFilesRecoveryException: [entity_2015100804][2] Failed to transfer [0] files with total size of [0b]
        at org.elasticsearch.indices.recovery.RecoverySource$1.phase1(RecoverySource.java:276)
        at org.elasticsearch.index.engine.internal.InternalEngine.recover(InternalEngine.java:1116)
        ... 9 more
Caused by: java.nio.file.NoSuchFileException: /mnt/data/data/indexName-sep/nodes/0/indices/indexName/2/index/_4wi.si
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
        at java.nio.channels.FileChannel.open(FileChannel.java:287)
        at java.nio.channels.FileChannel.open(FileChannel.java:335)
        at org.apache.lucene.store.NIOFSDirectory.openInput(NIOFSDirectory.java:81)
        at org.apache.lucene.store.FileSwitchDirectory.openInput(FileSwitchDirectory.java:172)
        at org.apache.lucene.store.FilterDirectory.openInput(FilterDirectory.java:80)
        at org.elasticsearch.index.store.DistributorDirectory.openInput(DistributorDirectory.java:130)
        at org.apache.lucene.store.Directory.openChecksumInput(Directory.java:113)
        at org.apache.lucene.codecs.lucene46.Lucene46SegmentInfoReader.read(Lucene46SegmentInfoReader.java:51)
        at org.apache.lucene.index.SegmentInfos.read(SegmentInfos.java:358)
        at org.elasticsearch.common.lucene.Lucene.readSegmentInfos(Lucene.java:94)
        at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:124)
        at org.elasticsearch.index.store.Store.access$400(Store.java:80)
        at org.elasticsearch.index.store.Store$MetadataSnapshot.buildMetadata(Store.java:575)
        at org.elasticsearch.index.store.Store$MetadataSnapshot.<init>(Store.java:568)
        at org.elasticsearch.index.store.Store.getMetadata(Store.java:186)
        at org.elasticsearch.indices.recovery.RecoverySource$1.phase1(RecoverySource.java:146)
       ... 10 more

**Comment by clintongormley** [comment]
hiya

so much has changed since 1.4 was released, especially around recovery and snapshot/restore.  please upgrade.
