### ISSUE TITLE
DedicatedClusterSnapshotRestoreIT.restoreIndexWithMissingShards rarely fails

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#14115]
DedicatedClusterSnapshotRestoreIT.restoreIndexWithMissingShards failed twice in the last 10 days with the following error:
```
Expected: <100L> but: was <87L>
	at __randomizedtesting.SeedInfo.seed([5C47F8A2C729A266:D663A36E857381AD]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT.restoreIndexWithMissingShards(DedicatedClusterSnapshotRestoreIT.java:525)
```

I didn't manage to reproduce the failure. Seems like after a restore not all expected documents can be found in the index using the count api:

http://build-us-00.elastic.co/job/es_core_master_centos/8019

**Comment by bleskes** [comment]
This fails because of the change in https://github.com/elastic/elasticsearch/pull/13766/files#diff-e3d064cfd24df0c1f53af98e6f9bc66dR675  . I'll work on a fix but need to get some other things done first.  If anyone interested in picking this up first , please ping me :)

**Comment by s1monw** [comment]
@bleskes what's the reason for this failure can you comment with more details?

**Comment by bleskes** [comment]
@s1monw see #14276
