### ISSUE TITLE
About compiler source in IntelliJ IDEA

### ISSUE THREAD

**Issue by feifeiiiiiiiiiii** [elastic/elasticsearch#14180]
When compiler source failed, as follow:

```
Exception in thread "main" java.lang.IllegalStateException: jar hell!
class: jdk.packager.services.UserJvmOptionsService
jar1: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/ant-javafx.jar
jar2: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/lib/packager.jar
	at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:248)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:152)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:87)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:154)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:266)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:36)
Refer to the log for complete error details.
```
How to solve it?

**Comment by dadoonet** [comment]
I manually updated the JDK configuration and removed `ant-javafx.jar` for example.
You have to do it for all conflicting libs.

**Comment by jasontedor** [comment]
The only JDK jars needed on the classpath are the ones listed in this [comment](https://github.com/elastic/elasticsearch/pull/13465#issuecomment-142124441).

**Comment by feifeiiiiiiiiiii** [comment]
@jakommo @dadoonet tks
