### ISSUE TITLE
ElasticSearch shutdown randowmly after a while when RejectedExecutionException occured

### ISSUE THREAD

**Issue by alexandrenavarro** [elastic/elasticsearch#14188]
ElasticSearch shutdown randowmly after a while.

This is the log of the elasticsearch (1.7.2) set in debug. Tell me if you want to active more specific logs. I don't try to shutdown the elasticsearch at this moment.

[2015-10-19 10:36:30,024][DEBUG][index.merge.scheduler    ] [Baphomet] [logstash-2015.10.19][3] merge segment [_6dd] done: took [27.5s], [285.6 MB], [644,636 docs]
[2015-10-19 10:45:51,459][INFO ][node                     ] [Baphomet] stopping ...
[2015-10-19 10:45:51,609][WARN ][netty.channel.DefaultChannelPipeline] An exception was thrown by an exception handler.
java.util.concurrent.RejectedExecutionException: Worker has already been shutdown
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.registerTask(AbstractNioSelector.java:120)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.executeInIoThread(AbstractNioWorker.java:72)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.executeInIoThread(NioWorker.java:36)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.executeInIoThread(AbstractNioWorker.java:56)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.executeInIoThread(NioWorker.java:36)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioChannelSink.execute(AbstractNioChannelSink.java:34)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.execute(DefaultChannelPipeline.java:636)
        at org.elasticsearch.common.netty.channel.Channels.fireExceptionCaughtLater(Channels.java:496)
        at org.elasticsearch.common.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:46)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.notifyHandlerException(DefaultChannelPipeline.java:658)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:781)
        at org.elasticsearch.common.netty.channel.Channels.write(Channels.java:725)
        at org.elasticsearch.common.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:71)
        at org.elasticsearch.common.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
        at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.handleDownstream(HttpPipeliningHandler.java:87)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
        at org.elasticsearch.http.netty.NettyHttpChannel.sendResponse(NettyHttpChannel.java:195)
        at org.elasticsearch.rest.action.support.RestResponseListener.processResponse(RestResponseListener.java:43)
        at org.elasticsearch.rest.action.support.RestActionListener.onResponse(RestActionListener.java:49)
        at org.elasticsearch.action.bulk.TransportBulkAction$2.finishHim(TransportBulkAction.java:360)
        at org.elasticsearch.action.bulk.TransportBulkAction$2.onResponse(TransportBulkAction.java:330)
        at org.elasticsearch.action.bulk.TransportBulkAction$2.onResponse(TransportBulkAction.java:323)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$ReplicationPhase.doFinish(TransportShardReplicationOperationAction.java:963)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$ReplicationPhase.doRun(TransportShardReplicationOperationAction.java:831)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.finishAndMoveToReplication(TransportShardReplicationOperationAction.java:525)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:603)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:440)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2015-10-19 10:45:52,113][DEBUG][indices                  ] [Baphomet] [logstash-2015.10.09] closing ... (reason [shutdown])
[2015-10-19 10:45:52,113][DEBUG][indices                  ] [Baphomet] [logstash-2015.10.09] closing index service (reason [shutdown])
[2015-10-19 10:45:52,132][DEBUG][indices                  ] [Baphomet] [logstash-2015.10.14] closing ... (reason [shutdown])
[2015-10-19 10:45:52,132][DEBUG][indices                  ] [Baphomet] [logstash-2015.10.14] closing index service (reason [shutdown])
[2015-10-19 10:45:52,137][DEBUG][indices                  ] [Baphomet] [logstash-2015.10.15] closing ... (reason [shutdown])
[2015-10-19 10:45:52,137][DEBUG][indices                  ] [Baphomet] [logstash-2015.10.15] closing index service (reason [shutdown])
[2015-10-19 10:45:52,143][DEBUG][indices                  ] [Baphomet] [logstash-2015.10.12] closing ... (reason [shutdown])
[2015-10-19 10:45:52,143][DEBUG][indices                  ] [Baphomet] [logstash-2015.10.12] closing index service (reason [shutdown])
....

**Comment by sazary** [comment]
What was the reason?

**Comment by Gerboa** [comment]
Also getting this happen. What was the cause?

**Comment by matteomelani** [comment]
+1. Any clues?

**Comment by awaistune** [comment]
Check your memory (heap / non heap).
