### ISSUE TITLE
DuelScrollIT is flaky

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#14263]
```
Suite: org.elasticsearch.search.scroll.DuelScrollIT
  2> REPRODUCE WITH: mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch:elasticsearch -Dtests.seed=509C33B10AD7FB5B -Dtests.class=org.elasticsearch.search.scroll.DuelScrollIT -Dtests.method="testDuelIndexOrderQueryThenFetch" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=pt_BR -Dtests.timezone=Atlantic/South_Georgia
FAILURE 1.80s J2 | DuelScrollIT.testDuelIndexOrderQueryThenFetch <<<
   > Throwable #1: org.junit.ComparisonFailure: expected:<[31]> but was:<[72]>
   >    at __randomizedtesting.SeedInfo.seed([509C33B10AD7FB5B:58D94811A90F5A55]:0)
   >    at org.elasticsearch.search.scroll.DuelScrollIT.testDuelIndexOrder(DuelScrollIT.java:283)
   >    at org.elasticsearch.search.scroll.DuelScrollIT.testDuelIndexOrderQueryThenFetch(DuelScrollIT.java:309)
   >    at java.lang.Thread.run(Thread.java:745)
  2> NOTE: leaving temporary files on disk at: /home/rmuir/workspace/elasticsearch/core/target/J2/temp/org.elasticsearch.search.scroll.DuelScrollIT_509C33B10AD7FB5B-001
  2> NOTE: test params are: codec=Asserting(Lucene53): {nested.field3=PostingsFormat(name=Asserting), _routing=PostingsFormat(name=Asserting), nested.field4=PostingsFormat(name=Asserting), field1=PostingsFormat(name=Asserting), _field_names=PostingsFormat(name=Asserting), foo=PostingsFormat(name=Asserting), _type=PostingsFormat(name=Asserting), _uid=PostingsFormat(name=Asserting), field2=PostingsFormat(name=Asserting), _all=PostingsFormat(name=Asserting)}, docValues:{nested.field3=DocValuesFormat(name=Asserting), field1=DocValuesFormat(name=Asserting), foo=DocValuesFormat(name=Asserting), _version=DocValuesFormat(name=Asserting)}, sim=RandomSimilarityProvider(queryNorm=false,coord=yes): {}, locale=pt_BR, timezone=Atlantic/South_Georgia
  2> NOTE: Linux 3.19.0-28-generic amd64/Oracle Corporation 1.8.0_45 (64-bit)/cpus=8,threads=1,free=459413528,total=510132224
  2> NOTE: All tests run in this JVM: [ClusterSettingsIT, DuelScrollIT]
Completed [12/287] on J2 in 10.60s, 4 tests, 1 failure <<< FAILURES!
```

**Comment by colings86** [comment]
@jimczi this test seems to pass with this seed for me on master now. Any reason not to close this?

**Comment by jimczi** [comment]
I tested this seed on master, 5.x, 5.4, 5.3 and 2.4. They all pass so I think it's ok to close this.
Thanks @colings86
