### ISSUE TITLE
NullPointerException when combining field and script in aggregation

### ISSUE THREAD

**Issue by jappievw** [elastic/elasticsearch#14262]
Using a script in the percentile aggregation in Kibana 4, this results in an Elasticsearch NullPointerException. [Example](https://www.dropbox.com/s/op3kzha6qwjlbpe/Screenshot%202015-10-23%2014.08.17.png?dl=0). This seems to be caused by Kibana including both the field and script property. It is not possible to exclude the field property from Kibana.

For the sake of simplicity I narrowed this down to a plain simple ES query. Elasticsearch 1.7.3 on a bare CentOS 7.1 box installed using the yum repo. No changes have been made to the ES config.

Be sure to have one document in an index with a numerical field.

    $ curl -XDELETE localhost:9200/test
    
    $ curl -XPUT localhost:9200/test/test/1?pretty=true -d '{
        "metric": 100
    }'
    
    {
      "_index" : "test",
      "_type" : "test",
      "_id" : "1",
      "_version" : 1,
      "created" : true
    }

Mapping has become a long value, which is fine for percentile agg

    $ curl -XGET localhost:9200/test/_mapping?pretty=true
    
    {
      "test" : {
        "mappings" : {
          "test" : {
            "properties" : {
              "metric" : {
                "type" : "long"
              }
            }
          }
        }
      }
    }

Running a query with both the field and script properties supplied. Results in a NullPointerException. I expected that the script would have precedence.

    $ curl -XPOST localhost:9200/test/test/_search?pretty=true -d '{
      "size": 0,
      "query": {
        "match_all": {}
      },
      "aggs": {
        "some-agg": {
          "percentiles": {
            "field": "metric",
            "lang": "expression",
            "script": "1"
          }
        }
      }
    }'
    
    {
      "took" : 4,
      "timed_out" : false,
      "_shards" : {
        "total" : 5,
        "successful" : 4,
        "failed" : 1,
        "failures" : [ {
          "index" : "test",
          "shard" : 2,
          "status" : 500,
          "reason" : "QueryPhaseExecutionException[[test][2]: query[ConstantScore(cache(_type:test))],from[0],size[0]: Query Failed [Failed to execute main query]]; nested: NullPointerException; "
        } ]
      },
      "hits" : {
        "total" : 0,
        "max_score" : 0.0,
        "hits" : [ ]
      },
      "aggregations" : {
        "some-agg" : {
          "values" : {
            "1.0" : "NaN",
            "5.0" : "NaN",
            "25.0" : "NaN",
            "50.0" : "NaN",
            "75.0" : "NaN",
            "95.0" : "NaN",
            "99.0" : "NaN"
          }
        }
      }
    }

**Comment by jappievw** [comment]
PS; this is what is included in the Elasticsearch log file:
```
[2015-10-23 16:29:19,142][DEBUG][action.search.type       ] [Pip the Troll] [test][2], node[YWWDb9UsQEGefx8R1f_Urw], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@35c01a59] lastShard [true]
org.elasticsearch.search.query.QueryPhaseExecutionException: [test][2]: query[ConstantScore(cache(_type:test))],from[0],size[0]: Query Failed [Failed to execute main query]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:163)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:301)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:312)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.elasticsearch.script.expression.ExpressionScript.setNextVar(ExpressionScript.java:109)
	at org.elasticsearch.search.aggregations.support.ValuesSource$Numeric$WithScript$DoubleValues.setDocument(ValuesSource.java:513)
	at org.elasticsearch.search.aggregations.metrics.percentiles.AbstractPercentilesAggregator.collect(AbstractPercentilesAggregator.java:83)
	at org.elasticsearch.search.aggregations.AggregationPhase$AggregationsCollector.collect(AggregationPhase.java:161)
	at org.elasticsearch.common.lucene.MultiCollector.collect(MultiCollector.java:60)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:193)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:163)
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:35)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:621)
	at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:191)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:309)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:117)
	... 8 more
```

**Comment by clintongormley** [comment]
Note: this script works correctly with Groovy
