### ISSUE TITLE
Upgrade to 2.0 on Found from 1.7.3 fails

### ISSUE THREAD

**Issue by smayzak** [elastic/elasticsearch#14313]
I tried to upgrade from 1.7.3 yesterday with Alex help and there was a problem even though my cluster passed the migration assistant with all greens except for a not red issue with a boolean.

Here is the exception.  

 [2015-10-26 22:40:44,272][ERROR][bootstrap                ] Guice Exception: java.lang.IllegalStateException: unable to upgrade the mappings for the index [sa_tps_reports], reason: [analyzer on field [raw] must be set when search_analyzer is set]

**Comment by rborer** [comment]
I had the same issue, on a single node with kibana 4.1.2.

I found the following exception in ES logs:

```
[2015-10-29 11:18:09,862][ERROR][bootstrap                ] Guice Exception: java.lang.IllegalStateException: unable to upgrade the mappings for the index [kibana-int], reason: [Mapper for [_index] conflicts with existing mapping in other types:
[mapper [_index] cannot be changed from type [_index] to [string]]]
Likely root cause: java.lang.IllegalArgumentException: Mapper for [_index] conflicts with existing mapping in other types:
[mapper [_index] cannot be changed from type [_index] to [string]]
        at org.elasticsearch.index.mapper.FieldTypeLookup.checkCompatibility(FieldTypeLookup.java:117)
        at org.elasticsearch.index.mapper.MapperService.checkNewMappersCompatibility(MapperService.java:345)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:296)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:242)
        at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.checkMappingsCompatibility(MetaDataIndexUpgradeService.java:329)
        at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.upgradeIndexMetaData(MetaDataIndexUpgradeService.java:112)
        at org.elasticsearch.gateway.GatewayMetaState.pre20Upgrade(GatewayMetaState.java:226)
        at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:85)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at <<<guice>>>
        at org.elasticsearch.node.Node.<init>(Node.java:198)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

**Comment by clintongormley** [comment]
@rborer This is a different error.  Please could you upload your mapping for the kibana index?  I think this might be an old index.

**Comment by clintongormley** [comment]
@smayzak I've changed the migration tool to report this mapping as a "red" error, and I've opened #14383 to make it possible to upgrade with this mapping

**Comment by rborer** [comment]
@clintongormley Thanks, here is my current Kibana mapping:

```
{
  "kibana-int" : {
    "mappings" : {
      "temp" : {
        "properties" : {
          "dashboard" : {
            "type" : "string"
          },
          "group" : {
            "type" : "string"
          },
          "title" : {
            "type" : "string"
          },
          "user" : {
            "type" : "string"
          }
        }
      },
      "dashboard" : {
        "properties" : {
          "_index" : {
            "type" : "string"
          },
          "_source" : {
            "properties" : {
              "dashboard" : {
                "type" : "string"
              },
              "group" : {
                "type" : "string"
              },
              "title" : {
                "type" : "string"
              },
              "user" : {
                "type" : "string"
              }
            }
          },
          "_type" : {
            "type" : "string"
          },
          "_version" : {
            "type" : "long"
          },
          "dashboard" : {
            "type" : "string"
          },
          "exists" : {
            "type" : "boolean"
          },
          "group" : {
            "type" : "string"
          },
          "title" : {
            "type" : "string"
          },
          "user" : {
            "type" : "string"
          }
        }
      }
    }
  }
}
```

**Comment by clintongormley** [comment]
Thanks @rborer.  That index is from kibana3, which won't work with kibana4 anyway, so you can go ahead and delete it.

**Comment by rborer** [comment]
@clintongormley fool me, I completely forgot about that kibana3 index! Thanks a lot, I'll get rid of it asap.
