### ISSUE TITLE
Server not started on Ubuntu after upgrade to 2.0.0-rc1

### ISSUE THREAD

**Issue by ewgRa** [elastic/elasticsearch#14323]
Exception

```
1) Error injecting constructor, RepositoryException[[testrepo] location [/tmp/backups/backup2] doesn't match any of the locations specified by path.repo because this setting is empty]
  at org.elasticsearch.repositories.fs.FsRepository.<init>(Unknown Source)
  while locating org.elasticsearch.repositories.fs.FsRepository
  while locating org.elasticsearch.repositories.Repository

1 error
        at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:344)
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:178)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
        at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:137)
        at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:56)
        at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:404)
        ... 7 more
Caused by: RepositoryException[[testrepo] location [/tmp/backups/backup2] doesn't match any of the locations specified by path.repo because this setting is empty]
        at org.elasticsearch.repositories.fs.FsRepository.<init>(FsRepository.java:85)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:56)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
        at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:54)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:865)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:858)
        at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
        ... 11 more
```

After create directory and add path.repo: ["/tmp/backups"] to elasticsearch.yml it start working, but in logs have similar messages about another directories: /tmp/test_repository, /tmp/test_register

Also interesting in logs:

[2015-10-28 00:24:47,331][INFO ][cluster.routing.allocation.decider] [Paige Guthrie] low disk watermark [85%] exceeded on [8qeuTUZdQ0SuYLZTspuvjw][Paige Guthrie][/var/lib/elasticsearch/elasticsearch/nodes/0] free: 11.9gb[10.9%], replicas will not be assigned to this node

ES installed just to localhost without cluster and so on.

**Comment by dadoonet** [comment]
I guess you upgraded from a version < 1.6?

See https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-1.6.html

**Comment by dadoonet** [comment]
Add all your repo dir to path.repo
