### ISSUE TITLE
Unicast hosts port range breaking change in ES 2.0

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#14457]
There is a breaking change in ES 2.0 where we changed the unicast.hosts specification.

There are 2 issues with this change:

1) This is missed in our breaking changes "network changes" documentation:
https://www.elastic.co/guide/en/elasticsearch/reference/2.0/_network_changes.html

While the new syntax is documented in the [Zen discovery](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/modules-discovery-zen.html#unicast) documentation, it should also be mentioned on the breaking changes page.

2) The change is breaking, but the exception thrown on the failed ES startup is misleading.  Instead of a UnknownHostException, it will be helpful for the error handling to tell the user that the setting specification has changed, and provide an example of the new syntax right in the error message.

Works in 2.0:
discovery.zen.ping.unicast.hosts: ['127.0.0.1:9300-9400']

Works in 1.7, breaks in 2.0 (and server will not start up):
discovery.zen.ping.unicast.hosts: ['127.0.0.1[9300-9400]']

And it throws the exception:

```
[2015-11-02 13:48:57,713][INFO ][watcher.trigger.schedule ] [Starhawk] using [ticker] schedule trigger engine
Exception in thread "main" java.lang.IllegalArgumentException: Failed to resolve address for [127.0.0.1[9300-9400]]
Likely root cause: java.net.UnknownHostException: 127.0.0.1[9300-9400]: nodename nor servname provided, or not known
    at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
    at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
    at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
    at java.net.InetAddress.getAllByName0(InetAddress.java:1246)
    at java.net.InetAddress.getAllByName(InetAddress.java:1162)
    at java.net.InetAddress.getAllByName(InetAddress.java:1098)
    at org.elasticsearch.transport.netty.NettyTransport.parse(NettyTransport.java:668)
    at org.elasticsearch.transport.netty.NettyTransport.addressesFromString(NettyTransport.java:620)
    at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:398)
    at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.<init>(UnicastZenPing.java:141)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at <<<guice>>>
    at org.elasticsearch.node.Node.<init>(Node.java:198)
    at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

**Comment by debadair** [comment]
No longer updating 2.x docs.
