### ISSUE TITLE
Test with @SuppressLocalMode and discovery.type=local diverges

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#14476]
Currently there is a test (`ClusterServiceIt.testMasterAwareExecution`) on Jenkins that does not terminate. 

http://build-us-00.elastic.co/job/es_core_master_medium/2568
(reported by @nik9000)

It seems to be not related to cluster state, but more related to test setup, namely interplay of @SuppressLocalMode and put("discovery.type", "local”). This means that we have combination of node.mode = network and discovery.type = local. Only the tests in ClusterServiceIT are configured like that. Should probably be changed? I reproduced the issue on my machine (but not deterministic even if providing seed...)

Small test case producing the issue sometimes (always on fresh JVM)

```
package org.elasticsearch.action.support.master;

import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.common.unit.TimeValue;
import org.elasticsearch.test.ESIntegTestCase;
import org.elasticsearch.test.InternalTestCluster;

import java.util.concurrent.ExecutionException;

import static org.elasticsearch.common.settings.Settings.settingsBuilder;

@ESIntegTestCase.ClusterScope(scope = ESIntegTestCase.Scope.TEST, numDataNodes = 0)
@ESIntegTestCase.SuppressLocalMode
public class BlaTest extends ESIntegTestCase {
    public void testFail() throws ExecutionException, InterruptedException {
        Settings settings = settingsBuilder()
                .put("discovery.type", "local")
                .build();

        InternalTestCluster.Async<String> master = internalCluster().startNodeAsync(settings);
        InternalTestCluster.Async<String> nonMaster = internalCluster().startNodeAsync(settingsBuilder().put(settings).put("node.master", false).build());
        master.get();
        nonMaster.get();
        ensureStableCluster(2, TimeValue.timeValueMinutes(2));
    }
}
```

Jstack interesting part:

```
"TEST-BlaTest.testFail-seed#[5531179544489649]" #12 prio=5 os_prio=31 tid=0x00007f83fbafa000 nid=0x5103 waiting on condition [0x0000700001
34d000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006c09db8c0> (a org.elasticsearch.common.util.concurrent.BaseFuture$Sync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:238)
        at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:78)
        at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:42)
        at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:68)
        at org.elasticsearch.test.ESIntegTestCase.ensureClusterSizeConsistency(ESIntegTestCase.java:1094)
        at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:593)
        at org.elasticsearch.test.ESIntegTestCase.after(ESIntegTestCase.java:1972)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1665)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:922)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:50)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:46)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:49)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:65)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:48)
```

Also noteworthy that often the following warning is displayed in the logs (which shows that it has somewhat to do with discovery and the mix of modes):

```
[2015-11-03 00:19:42,917][WARN ][org.elasticsearch.discovery] [node_t1] waited for 30s and no initial state was set by the discovery
```

**Comment by ywelsch** [comment]
This is again #14535
