### ISSUE TITLE
ES 2.0.0 fails to start if the Marvel exporter agent is configured.

### ISSUE THREAD

**Issue by ajaybhatnagar** [elastic/elasticsearch#14498]
Elasticsearch 2.0.0 able to start without these lines in the yml file. Plugins license and marvel agent installed on the ES node. There is no error logs generated either except for gc.log. Monitoring nodes listed are reachable from the ES node and running OK with Kibana/Marvel.

As per documentation (https://www.elastic.co/guide/en/marvel/current/installing-marvel.html) following config was used
marvel.agent.exporters:
  id1:
    type: http
    host: [http://es-thr-mon2-m01:9200,es-thr-mon2-m02:9200]

Correct configuration need to use  with quotes sign as below:
marvel.agent.exporters:
  id1:
    type: http
    host: ["http://es-thr-mon2-m01:9200","es-thr-mon2-m02:9200"]

**Comment by dineshbugide** [comment]
The above thing worked for me but I am not able to interact with the server using the URL:
http://localhost:9200/_plugin/marvel

**Comment by clintongormley** [comment]
@dineshbugide Marvel UI is now a Kibana app.  The docs explain how to set it up.

@ajaybhatnagar you need to tell us more about how you installed, configured, and started elasticsearch.

**Comment by mdiehm** [comment]
I had the same issues today. I run debian jessie (8.2). Repos for elastic added to /etc/apt... as described in the documentation. Running elastic through systemd as described in your documentation. When I add the marvel.agent.exporters the way you tell people I get:

systemctl status elasticsearch

[2015-11-17 19:28:17,347][WARN ][netty.channel.DefaultChannelPipeline] An exception was thrown by an exception handler.
java.util.concurrent.RejectedExecutionException: Worker has already been shutdown
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.registerTask(AbstractNioSelector.java:120)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.executeInIoThread(AbstractNioWorker.java:72)
        at org.jboss.netty.channel.socket.nio.NioWorker.executeInIoThread(NioWorker.java:36)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.executeInIoThread(AbstractNioWorker.java:56)
        at org.jboss.netty.channel.socket.nio.NioWorker.executeInIoThread(NioWorker.java:36)
        at org.jboss.netty.channel.socket.nio.AbstractNioChannelSink.execute(AbstractNioChannelSink.java:34)
        at org.jboss.netty.channel.DefaultChannelPipeline.execute(DefaultChannelPipeline.java:636)
        at org.jboss.netty.channel.Channels.fireExceptionCaughtLater(Channels.java:496)
        at org.jboss.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:46)
        at org.jboss.netty.channel.DefaultChannelPipeline.notifyHandlerException(DefaultChannelPipeline.java:658)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:781)
        at org.jboss.netty.channel.Channels.write(Channels.java:725)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:71)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
        at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.handleDownstream(HttpPipeliningHandler.java:87)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
        at org.elasticsearch.http.netty.NettyHttpChannel.sendResponse(NettyHttpChannel.java:174)
        at org.elasticsearch.rest.action.support.RestResponseListener.processResponse(RestResponseListener.java:43)
        at org.elasticsearch.rest.action.support.RestActionListener.onResponse(RestActionListener.java:49)
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.finishHim(TransportNodesAction.java:203)
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onOperation(TransportNodesAction.java:178)
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$600(TransportNodesAction.java:94)
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$2.handleResponse(TransportNodesAction.java:155)
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$2.handleResponse(TransportNodesAction.java:147)
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:185)
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:138)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

my config looks like this:
marvel.agent.exporters:

  id1:
    type: http
    host: [http://131.152.2.121:9200, http://131.152.2.122:9200]

**Comment by clintongormley** [comment]
@tlrx any ideas?

**Comment by tlrx** [comment]
The documentation was indeed wrong and has been fixed recently. Now the [Installing Marvel](https://www.elastic.co/guide/en/marvel/current/installing-marvel.html#monitoring-cluster) page shows a configuration sample where the `host` have double quotes:

```yaml
marvel.agent.exporters:
  id1:
    type: http
    host: ["http://es-mon-1:9200", "http://es-mon2:9200"]
```

In systemd based distributions, like @mdiehm is using, elasticsearch will not start if the `elasticsearch.yml` contains an error. 

The file `elasticsearch.log` remains empty but the command `journalctl -u elasticsearch.service` shows the error:

```
nov. 19 09:59:38 debian elasticsearch[2405]: Exception in thread "main" SettingsException[Failed to load setting
nov. 19 09:59:38 debian elasticsearch[2405]: host: [http:localhost:9200,localhost:9201]
nov. 19 09:59:38 debian elasticsearch[2405]: ^];
nov. 19 09:59:38 debian elasticsearch[2405]: Likely root cause: while scanning a plain scalar
nov. 19 09:59:38 debian elasticsearch[2405]: in 'reader', line 4, column 12:
nov. 19 09:59:38 debian elasticsearch[2405]: Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for deta
nov. 19 09:59:38 debian elasticsearch[2405]: at com.fasterxml.jackson.dataformat.yaml.snakeyaml.scanner.ScannerI
...
org.elasticsearch.bootstrap.Bootstrap.initialSettings(Bootstrap.
nov. 19 09:59:38 debian elasticsearch[2405]: at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:241)
nov. 19 09:59:38 debian elasticsearch[2405]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.jav
nov. 19 09:59:38 debian elasticsearch[2405]: Refer to the log for complete error details.
nov. 19 09:59:39 debian systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
nov. 19 09:59:39 debian systemd[1]: Unit elasticsearch.service entered failed state.
```

@ajaybhatnagar I suppose your case falls into the same category. If not, please feel free to reopen this issue and give us more information as @clintongormley suggested.
