### ISSUE TITLE
Mapping conflict error upgrading from 1.5 to 2.0

### ISSUE THREAD

**Issue by chilladx** [elastic/elasticsearch#14491]
When trying to start the master node of my cluster, just after the upgrade from 1.5 to 2.0 (yeah, that's a big jump), I get this error log:

```
[2015-11-03 18:15:10,948][ERROR][gateway                  ] [mon-01] failed to read local state, exiting...
java.lang.IllegalStateException: unable to upgrade the mappings for the index [logstash-2015.10.18], reason: [Mapper for [timestamp] conflicts with existing mapping in other types:
[mapper [timestamp] cannot be changed from type [date] to [string]]]
```

Unfortunately, I don't have the detailed description of the field or the relevant analyzer configuration for the field, but as its name states, it's a timestamp from logstash, so it should look like one of these:
- "dd/MMM/yyyy:HH:mm:ss Z"
- "YYYY-MM-dd HH:mm:ss"
- "HH:mm:ss"
- "YYYY-MM-dd HH:mm:ss,SSS ZZ"
- "YYYY-MM-dd HH:mm:ss,SSSZZ"
- "YYYY-MM-dd HH:mm:ss,SSS"

The log ends with this:

```
[2015-11-03 18:15:11,383][ERROR][bootstrap                ] Guice Exception: java.lang.IllegalStateException: unable to upgrade the mappings for the index [logstash-2015.10.18], reason: [Mapper for [timestamp] conflicts with existing mapping in other types:
[mapper [timestamp] cannot be changed from type [date] to [string]]]
Likely root cause: java.lang.IllegalArgumentException: Mapper for [timestamp] conflicts with existing mapping in other types:
[mapper [timestamp] cannot be changed from type [date] to [string]]
        at org.elasticsearch.index.mapper.FieldTypeLookup.checkCompatibility(FieldTypeLookup.java:117)
        at org.elasticsearch.index.mapper.MapperService.checkNewMappersCompatibility(MapperService.java:345)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:296)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:242)
        at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.checkMappingsCompatibility(MetaDataIndexUpgradeService.java:329)
        at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.upgradeIndexMetaData(MetaDataIndexUpgradeService.java:112)
        at org.elasticsearch.gateway.GatewayMetaState.pre20Upgrade(GatewayMetaState.java:226)
        at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:85)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at <<<guice>>>
        at org.elasticsearch.node.Node.<init>(Node.java:198)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

And the node shuts down..

I have carefully read #13169 and #13345, but none of these helped me, the node keeps failing to start.

**Comment by jpountz** [comment]
If I read the exception correctly, your `logstash-2015.10.18` index has a `timestamp` field which is mapped as a `string` on one type and as a `date` on another type, which is something that elasticsearch can't cope with. In elasticsearch 1.x this issue would be silent and only trip when trying to search/sort/aggregate on a field. In Elasticsearch 2.0, we detect these inconsistencies more proactively. Unfortunately the only way to fix the issue would be to reindex these data.

**Comment by chilladx** [comment]
Many thanks, @jpountz . So I'll clause this issue, as it's not a bug, but a problem in my data. I'll try to downgrade back to 1.5.x, update my mappings, and then upgrade again to 2.0.

**Comment by chilladx** [comment]
Just for the record, here is the fine manual about this: https://www.elastic.co/blog/great-mapping-refactoring

I'm in the "Conflicting field mappings" case, where, as stated by @jpountz , the only option is to reindex the data.

**Comment by veronicacannon** [comment]
I tried to downgrade back to 1.7 (in my case) so I could delete my mappings and indices.  I get the same error when trying to start Elasticsearch in the older version.  This is a new install so I can safely delete the indices, mappings, logstash, etc.  Is there a way to do that without running Elasticsearch? 

Ubuntu 14
downgraded from Elasticsearch 2.1 to 1.7
