### ISSUE TITLE
Receiving "Multiple entries with same key" error when cycling in and out new nodes on elasticsearch 2.0.0

### ISSUE THREAD

**Issue by robertsmarty** [elastic/elasticsearch#14517]
Hi,

I'm testing my cluster and cycling in new nodes and cycling out old ones however after waiting a couple of hours shards and replicas haven't sorted themselves out. When listing the status of all shards via GET /cat/_shards I receive...

{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "Multiple entries with same key: [cloudtrail-2015.10.16][0], node[2yaILlgNTX24_lrlf77gIg], [P], v[25], s[STARTED], a[id=wtXiTTw9T4C9KHucOIQKGA]=org.elasticsearch.action.admin.indices.stats.CommonStats@7968034a and [cloudtrail-2015.10.16][0], node[2yaILlgNTX24_lrlf77gIg], [P], v[25], s[STARTED], a[id=wtXiTTw9T4C9KHucOIQKGA]=org.elasticsearch.action.admin.indices.stats.CommonStats@49422abd"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "Multiple entries with same key: [cloudtrail-2015.10.16][0], node[2yaILlgNTX24_lrlf77gIg], [P], v[25], s[STARTED], a[id=wtXiTTw9T4C9KHucOIQKGA]=org.elasticsearch.action.admin.indices.stats.CommonStats@7968034a and [cloudtrail-2015.10.16][0], node[2yaILlgNTX24_lrlf77gIg], [P], v[25], s[STARTED], a[id=wtXiTTw9T4C9KHucOIQKGA]=org.elasticsearch.action.admin.indices.stats.CommonStats@49422abd"
    },
    "status": 400
}

Any ideas?

**Comment by s1monw** [comment]
can you look at the nodes log file and paste me the stacktrace for this exception?

**Comment by robertsmarty** [comment]
Is this what you're after?

[2015-11-04 21:04:30,269][INFO ][rest.suppressed          ] /_cat/shards Params: {}
java.lang.IllegalArgumentException: Multiple entries with same key: [cloudtrail-2015.10.16][0], node[2yaILlgNTX24_lrlf77gIg], [P], v[25], s[STARTED], a[id=wtXiTTw9T4C9KHucOIQKGA]=org.elasticsearch.action.admin.indices.stats.CommonStats@4e720ea0 and [cloudtrail-2015.10.16][0], node[2yaILlgNTX24_lrlf77gIg], [P], v[25], s[STARTED], a[id=wtXiTTw9T4C9KHucOIQKGA]=org.elasticsearch.action.admin.indices.stats.CommonStats@4960652f
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104)
	at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254)
	at org.elasticsearch.action.admin.indices.stats.IndicesStatsResponse.asMap(IndicesStatsResponse.java:65)
	at org.elasticsearch.rest.action.cat.RestShardsAction.buildTable(RestShardsAction.java:172)
	at org.elasticsearch.rest.action.cat.RestShardsAction.access$000(RestShardsAction.java:43)
	at org.elasticsearch.rest.action.cat.RestShardsAction$1$1.buildResponse(RestShardsAction.java:73)
	at org.elasticsearch.rest.action.cat.RestShardsAction$1$1.buildResponse(RestShardsAction.java:70)
	at org.elasticsearch.rest.action.support.RestResponseListener.processResponse(RestResponseListener.java:43)
	at org.elasticsearch.rest.action.support.RestActionListener.onResponse(RestActionListener.java:49)
	at org.elasticsearch.shield.action.ShieldActionFilter$SigningListener.onResponse(ShieldActionFilter.java:193)
	at org.elasticsearch.shield.action.ShieldActionFilter$SigningListener.onResponse(ShieldActionFilter.java:179)
	at org.elasticsearch.action.support.TransportAction$ResponseFilterChain.proceed(TransportAction.java:141)
	at org.elasticsearch.shield.action.ShieldActionFilter.apply(ShieldActionFilter.java:124)
	at org.elasticsearch.action.support.TransportAction$ResponseFilterChain.proceed(TransportAction.java:139)
	at org.elasticsearch.action.support.TransportAction$FilteredActionListener.onResponse(TransportAction.java:166)
	at org.elasticsearch.action.support.TransportAction$FilteredActionListener.onResponse(TransportAction.java:152)
	at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction.onCompletion(TransportBroadcastByNodeAction.java:357)
	at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction.onNodeResponse(TransportBroadcastByNodeAction.java:326)
	at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction$1.handleResponse(TransportBroadcastByNodeAction.java:300)
	at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction$1.handleResponse(TransportBroadcastByNodeAction.java:292)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:185)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:138)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by robertsmarty** [comment]
Update on this. Doing more testing I have found that the cluster does eventually go to a green state however the same error still exists when using GET /cat/_shards

**Comment by clintongormley** [comment]
What version(s) of Elasticsearch are you using?

**Comment by robertsmarty** [comment]
2.0.0 and still have the error when accessing GET /cat/_shards so can provide more info. Status of the cluster is green. I deleted the index above to clear the error however I now have it on a different index.

**Comment by s1monw** [comment]
thanks, can you paste the output of `GET localhost:9200/_stats` please

**Comment by robertsmarty** [comment]
![stats](https://cloud.githubusercontent.com/assets/4920375/11050813/72f71aec-879d-11e5-8069-eb1b40596687.jpg)

Trying to upload this txt file as jpg as I don't seem to be able to save to repo. Please rename to txt to open.

**Comment by masaruh** [comment]
It happens when you have Shield and configure alias.
I believe it's fixed by https://github.com/elastic/elasticsearch/pull/14316.

**Comment by GlenRSmith** [comment]
A companion to this is that _settings and _mapping return JSON bodies with duplicate keys.

**Comment by clintongormley** [comment]
Thanks @masaruh. Closing in favour of #14316
