### ISSUE TITLE
org.elasticsearch.bwcompat.BasicBackwardsCompatibilityIT fails on 2.x and 2.0 on Windows

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#14514]
Example failures:

http://build-us-00.elastic.co/job/es_core_2x_window-2008/193
http://build-us-00.elastic.co/job/es_core_2x_window-2012/156
http://build-us-00.elastic.co/job/es_core_21_window-2008/70

Reproduce command:
```
mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch.qa.backwards:current -Dtests.seed=FDFEBB4487D6B7EC -Dtests.class=org.elasticsearch.bwcompat.BasicBackwardsCompatibilityIT -Dtests.method="testDeleteRoutingRequired" -Des.logger.level=DEBUG -Dtests.nightly=false -Dtests.client.ratio=0.0 -Dtests.heap.size=512m -Des.node.mode=local -Dtests.bwc.version=2.2.0-SNAPSHOT -Dtests.bwc.path=target/backwards -Dtests.jvm.argline=""-server -XX:+UseG1GC -XX:-UseCompressedOops -Djava.net.preferIPv4Stack=true"" -Dtests.locale=bg -Dtests.timezone=Africa/Lagos
```

Failure message:
```
FAILURE 71.8s | BasicBackwardsCompatibilityIT.testDeleteRoutingRequired <<<
   > Throwable #1: java.lang.AssertionError: ClusterHealthResponse has timed out - returned: [{
   >   "cluster_name" : "SUITE-CHILD_VM=[0]-CLUSTER_SEED=[-257963635650616420]-HASH=[1B66F7F9939D50]-cluster",
   >   "status" : "green",
   >   "timed_out" : true,
   >   "number_of_nodes" : 7,
   >   "number_of_data_nodes" : 7,
   >   "active_primary_shards" : 4,
   >   "active_shards" : 4,
   >   "relocating_shards" : 0,
   >   "initializing_shards" : 0,
   >   "unassigned_shards" : 0,
   >   "delayed_unassigned_shards" : 0,
   >   "number_of_pending_tasks" : 0,
   >   "number_of_in_flight_fetch" : 0,
   >   "task_max_waiting_in_queue_millis" : 0,
   >   "active_shards_percent_as_number" : 100.0
   > }]
   > Expected: is <false>
   >      but: was <true>
   > 	at __randomizedtesting.SeedInfo.seed([FDFEBB4487D6B7EC:6D1AB79C0D9CADCA]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertNoTimeout(ElasticsearchAssertions.java:105)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureClusterSizeConsistency(ESIntegTestCase.java:1092)
   > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:600)
   > 	at org.elasticsearch.test.ESIntegTestCase.after(ESIntegTestCase.java:1956)
   > 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by colings86** [comment]
@nik9000 would you be able to look at these failures? It looks to be only affecting the windows builds

**Comment by nik9000** [comment]
> @nik9000 would you be able to look at these failures? It looks to be only affecting the windows builds

I started yesterday actually. This is caused by #14503. I can reproduce it on linux too using -Djava.net.preferIPv4 or whatever its called. I'm still seeing if I can create a non-bwc recreation for that issue.
