### ISSUE TITLE
org.elasticsearch.percolator.RecoveryPercolatorIT.testSinglePercolator_recovery

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#14521]
Out of memory Error caused the failure:

http://build-us-00.elastic.co/job/es_core_21_strong/198/

reproduce command:
```
mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch:elasticsearch -Dtests.seed=C3AB6B0AD64016DB -Dtests.class=org.elasticsearch.percolator.RecoveryPercolatorIT -Des.logger.level=DEBUG -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Des.node.mode=network -Dtests.locale=en_US -Dtests.timezone=Etc/UTC
```

Error:
```
java.lang.OutOfMemoryError: Direct buffer memory
	at __randomizedtesting.SeedInfo.seed([C3AB6B0AD64016DB:E9CBD0B4B13DE8B6]:0)
	at java.nio.Bits.reserveMemory(Bits.java:658)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$Preallocation.<init>(SocketSendBufferPool.java:156)
	at org.jboss.netty.channel.socket.nio.SocketSendBufferPool.<init>(SocketSendBufferPool.java:42)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.<init>(AbstractNioWorker.java:45)
	at org.jboss.netty.channel.socket.nio.NioWorker.<init>(NioWorker.java:45)
	at org.jboss.netty.channel.socket.nio.NioWorkerPool.newWorker(NioWorkerPool.java:44)
	at org.jboss.netty.channel.socket.nio.NioWorkerPool.newWorker(NioWorkerPool.java:28)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool.init(AbstractNioWorkerPool.java:80)
	at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:39)
	at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:33)

```

**Comment by martijnvg** [comment]
This test no longer fails. (it has been rewritten and is now named RecoveryPercolatorIT#testPercolatorRecovery())
