### ISSUE TITLE
Highlighter causing overflow of boolean max clause count

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#14538]
The following appears to be the case where the wildcard query (in this case, entered by a Kibana user) caused enough Lucene rewrites so that it overflows the boolean max clause count of 1024 by default.  While we could potentially workaround this by increasing the max clause count in Lucene/ES, it is not the ideal workaround given the memory implications.    

This appears to be a highlighter issue based on the stack.  Not sure if the highlighter honors these rewrite settings (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-term-rewrite.html) ... Is there any safeguard that can be configured to prevent the highlighter from causing the great number of bool queries that is being generated?

```
[indices:data/read/search[phase/fetch/id]] 
Caused by: org.elasticsearch.search.fetch.FetchPhaseExecutionException: [logstash-2015.11.03][9]: query[filtered(+host:* +(message:20151103) +(message:main) +(message:dialer))->BooleanFilter(+cache(@timestamp:[1446555600000 TO 1446574259999]))],from[0],size[1000],sort[<custom:"@timestamp": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@69646af6>!]: Fetch Failed [Failed to highlight field [message]] 
at org.elasticsearch.search.highlight.PlainHighlighter.highlight(PlainHighlighter.java:134) 
at org.elasticsearch.search.highlight.HighlightPhase.hitExecute(HighlightPhase.java:133) 
at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:194) 
at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:516) 
at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:868) 
at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:862) 
at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:279) 
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
at java.lang.Thread.run(Thread.java:745) 
Caused by: org.apache.lucene.search.BooleanQuery$TooManyClauses: maxClauseCount is set to 1024
at org.apache.lucene.search.ScoringRewrite$1.checkMaxClauseCount(ScoringRewrite.java:72) 
at org.apache.lucene.search.ScoringRewrite$ParallelArraysTermCollector.collect(ScoringRewrite.java:149)
at org.apache.lucene.search.TermCollectingRewrite.collectTerms(TermCollectingRewrite.java:79) 
at org.apache.lucene.search.ScoringRewrite.rewrite(ScoringRewrite.java:105) 
at org.apache.lucene.search.MultiTermQuery.rewrite(MultiTermQuery.java:288) 
at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.extract(WeightedSpanTermExtractor.java:217) 
at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.extract(WeightedSpanTermExtractor.java:99) 
at org.elasticsearch.search.highlight.CustomQueryScorer$CustomWeightedSpanTermExtractor.extractUnknownQuery(CustomQueryScorer.java:89) 
at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.extract(WeightedSpanTermExtractor.java:224) 
at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.getWeightedSpanTerms(WeightedSpanTermExtractor.java:474) 
at org.apache.lucene.search.highlight.QueryScorer.initExtractor(QueryScorer.java:217) 
at org.apache.lucene.search.highlight.QueryScorer.init(QueryScorer.java:186) 
at org.apache.lucene.search.highlight.Highlighter.getBestTextFragments(Highlighter.java:197) 
at org.elasticsearch.search.highlight.PlainHighlighter.highlight(PlainHighlighter.java:120) 
... 10 more
```

**Comment by nik9000** [comment]
> Is there any safeguard that can be configured to prevent the highlighter from causing the great number of bool queries that is being generated?

I honestly don't know if the highlighter respects the rewrite configuration - without trying it I'm 60% sure it does but that isn't saying much. For what its worth the experimental highlighter doesn't have to rewrite most wildcard queries so it won't hit this particular problem.

**Comment by ppf2** [comment]
The experimental highlighter (https://github.com/elastic/elasticsearch/pull/5767) was added as a doc change.  As Nik noted above, this alternate highlighter does not rewrite wildcard queries so it will not run into this issue.  This is a request to enhance the out of the box highlighter for it to also handle wildcard queries in a more efficient way like the experimental highlighter.

**Comment by clintongormley** [comment]
closing in favour of #21621
