### ISSUE TITLE
NPE onNodeFailure 

### ISSUE THREAD

**Issue by bangert** [elastic/elasticsearch#14584]
Hi,

we may have tried something stupid here:

```
$ curl 192.168.8.180:9200/_cat/nodes?h=name,version,jdk,ip,master,node.role
robocop      2.0.0 1.7.0_79 192.168.8.237 - d
Det Røde Lyn 2.0.0 1.8.0_65 192.168.8.180 * -
stuart       2.0.0 1.8.0_65 192.168.8.13  - d
Gulle        2.0.0 1.7.0_85 192.168.8.21  m d 
```
"Det Røde Lyn" is a windows machine.

all nodes have "Gulle" configured as unicast host
```
discovery.zen.ping.unicast.hosts: ["192.168.8.21"]
```
when Gulle shutdown the cluster broke down and the following shows up in the log of the stuart node. The logfile of the other nodes in the cluster dont show a similar NPE.

We have been unable to reproduce this, but thought you might be interested in this anyway.
```
[2015-11-06 13:28:07,710][INFO ][cluster.routing.allocation.decider] [stuart] updating [cluster.routing.allocation.enable] from [ALL] to [NONE]
[2015-11-06 13:28:47,859][INFO ][discovery.zen            ] [stuart] master_left [{Gulle}{F4pDMpoOSG6U0fBuxUzFWg}{192.168.8.21}{192.168.8.21:9300}], reason [transport disconnected]
[2015-11-06 13:28:47,859][WARN ][discovery.zen            ] [stuart] master left (reason = transport disconnected), current nodes: {{robocop}{LHRwN1SYTMC05oPnrnlhVg}{192.168.8.237}{192.168.8.237:9300}{rack=robo-desk, max_local_storage_nodes=1, master=false},{Det Røde Lyn}{DmoJNBpOR8m1WKBPQojwag}{192.168.8.180}{192.168.8.180:9300}{data=false},{stuart}{TYWtWR00Q6Kv8pG6Fi09Yw}{192.168.8.13}{192.168.8.13:9300}{master=false},}
[2015-11-06 13:28:47,859][INFO ][cluster.service          ] [stuart] removed {{Gulle}{F4pDMpoOSG6U0fBuxUzFWg}{192.168.8.21}{192.168.8.21:9300},}, reason: zen-disco-master_failed ({Gulle}{F4pDMpoOSG6U0fBuxUzFWg}{192.168.8.21}{192.168.8.21:9300})
[2015-11-06 13:28:50,397][DEBUG][action.admin.cluster.state] [stuart] no known master node, scheduling a retry
[2015-11-06 13:28:50,398][DEBUG][action.admin.cluster.state] [stuart] no known master node, scheduling a retry
[2015-11-06 13:28:50,398][INFO ][rest.suppressed          ] /_stats/docs,store Params: {metric=docs,store}
java.lang.NullPointerException
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction.onNodeFailure(TransportBroadcastByNodeAction.java:332)
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction.sendNodeRequest(TransportBroadcastByNodeAction.java:314)
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction.start(TransportBroadcastByNodeAction.java:284)
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction.doExecute(TransportBroadcastByNodeAction.java:217)
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction.doExecute(TransportBroadcastByNodeAction.java:77)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:70)
        at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:347)
        at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:52)
        at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient.doExecute(BaseRestHandler.java:83)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:347)
        at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1177)
        at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.stats(AbstractClient.java:1482)
        at org.elasticsearch.rest.action.admin.indices.stats.RestIndicesStatsAction.handleRequest(RestIndicesStatsAction.java:102)
        at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:54)
        at org.elasticsearch.rest.RestController.executeHandler(RestController.java:207)
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:166)
        at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:128)
        at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:86)
        at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:348)
        at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:63)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2015-11-06 13:28:50,398][DEBUG][action.admin.indices.get ] [stuart] no known master node, scheduling a retry
[2015-11-06 13:28:50,399][DEBUG][action.admin.cluster.health] [stuart] no known master node, scheduling a retry
[2015-11-06 13:28:51,291][INFO ][cluster.service          ] [stuart] detected_master {Det Røde Lyn}{DmoJNBpOR8m1WKBPQojwag}{192.168.8.180}{192.168.8.180:9300}{data=false}, reason: zen-disco-receive(from master [{Det Røde Lyn}{DmoJNBpOR8m1WKBPQojwag}{192.168.8.180}{192.168.8.180:9300}{data=false}])
[2015-11-06 13:29:13,992][INFO ][cluster.service          ] [stuart] added {{Gulle}{vDbnkAfsT96NnX_Q3cN1oA}{192.168.8.21}{192.168.8.21:9300},}, reason: zen-disco-receive(from master [{Det Røde Lyn}{DmoJNBpOR8m1WKBPQojwag}{192.168.8.180}{192.168.8.180:9300}{data=false}])
[2015-11-06 13:29:55,312][INFO ][cluster.routing.allocation.decider] [stuart] updating [cluster.routing.allocation.enable] from [NONE] to [ALL]

**Comment by bangert** [comment]
hm, we were actually able to reproduce this.
This time, all remaining nodes showed the same NPE, while the new master node (Det Røde Lyn) actually showed it twice (approx. 10 seconds between the two)

**Comment by jasontedor** [comment]
I think that this is happening because immediately before the request and the master leaving the cluster, allocation was disabled. When the master leaves the cluster, the shards assigned to that node will not be reassigned. As such, the shards that were on the master will be in the cluster state but not associated with a node that is in the cluster state. When `sendNodeRequest` tries to look up the node to send the request to for such a shard there ends up being no such node. This leads to one NPE, which gets caught and cascades into a second NPE in the `onNodeFailure` handler. The correct course of action is to treat such shards as if it they are not available so that we never even attempt to send requests for them.

Thank you for the bug report. I'll be opening a pull request later to address this issue.

**Comment by bangert** [comment]
Awesome work! Thanks.
