### ISSUE TITLE
Many Unclear Warnings after upgrade to v1.7.3: "no index mapper found for field"

### ISSUE THREAD

**Issue by segalziv** [elastic/elasticsearch#14618]
After upgrading to 1.7.3, I see many warning in the log file:

[2015-11-09 10:15:33,919][WARN ][index.codec              ] [data_xxx] [index-name] no index mapper found for field: [field-name] returning default doc values format

[2015-11-09 10:15:31,798][WARN ][index.codec              ] [data_xxx] [index-name] no index mapper found for field: [field-name] returning default postings format

I've checked the github, forums, ... and couldn't find the root cause and how can this be resolved.

Please advice, let me know if you like me to submit more info. Thanks

**Comment by clintongormley** [comment]
Hi @segalziv 

It looks like you upgraded from an old version and are running into this change: https://github.com/elastic/elasticsearch/pull/7604

You will need to reindex into a new index without those custom mappings

**Comment by segalziv** [comment]
@clintongormley Thanks for answering fast!

The index is a daily (logs) index, which was created in 1.7.3. to begin with. So I can't understand how reindexing will help.

I have to add that there were some mapping race condition warnings on this index, which feels related:

[2015-11-09 09:41:23,932][WARN ][action.bulk              ] [data_xxx] failed to perform indices:data/write/bulk[s] on remote replica [data_xxx][A_uuXlcwTnKmQs2VCJLuOQ][ip-0-0-0-0][inet[/0.0.0.0:9300]]{max_local_storage_nodes=1, zone=us-east-1a, master=false}[index-name][8]
org.elasticsearch.transport.RemoteTransportException: [data_xxx][inet[/0.0.0.0:9300]][indices:data/write/bulk[s][r]]
Caused by: org.elasticsearch.index.mapper.MapperParsingException: failed to parse [field-name]
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:411)
	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:554)
	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:487)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:544)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:493)
	at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:466)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnReplica(TransportShardBulkAction.java:566)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$ReplicaOperationTransportHandler.messageReceived(TransportShardReplicationOperationAction.java:250)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$ReplicaOperationTransportHandler.messageReceived(TransportShardReplicationOperationAction.java:229)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:279)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: unknown property [referrer]
	at org.elasticsearch.index.mapper.core.StringFieldMapper.parseCreateFieldForString(StringFieldMapper.java:331)
	at org.elasticsearch.index.mapper.core.StringFieldMapper.parseCreateField(StringFieldMapper.java:277)
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:401)
	... 15 more
