### ISSUE TITLE
Test Failure: SearchQueryIT.testConstantScoreQuery - all shards failed

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#14679]
Build URL: http://build-us-00.elastic.co/job/es_core_master_debian/7823/testReport/junit/org.elasticsearch.search.query/SearchQueryIT/testConstantScoreQuery/

Cannot reproduce locally

Reproduction command:

```
gradle :plugins:lang-groovy:integTest -Dtests.seed=ED48A577973A709C -Dtests.class=org.elasticsearch.search.query.SearchQueryIT -Dtests.method="testConstantScoreQuery" -Des.logger.level=DEBUG -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=573m -Dtests.jvm.argline="-server -XX:+UseParallelGC -XX:+UseCompressedOops" -Dtests.locale=sr_BA -Dtests.timezone=America/Yellowknife
```

Stack trace:
```
Failed to execute phase [query], all shards failed
	at __randomizedtesting.SeedInfo.seed([ED48A577973A709C:6772A8B75A54A1D6]:0)
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:230)
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:174)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:810)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:788)
	at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:361)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: RemoteTransportException[[Gazelle][127.0.0.1:9500][indices:data/read/search[phase/query]]]; nested: IllegalIndexShardStateException[CurrentState[RECOVERING] operations only allowed when shard state is one of [POST_RECOVERY, STARTED, RELOCATED]];
Caused by: [test_1][[test_1][0]] IllegalIndexShardStateException[CurrentState[RECOVERING] operations only allowed when shard state is one of [POST_RECOVERY, STARTED, RELOCATED]]
	at org.elasticsearch.index.shard.IndexShard.readAllowed(IndexShard.java:907)
	at org.elasticsearch.index.shard.IndexShard.acquireSearcher(IndexShard.java:725)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:550)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:527)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:278)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:346)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:343)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bleskes** [comment]
closed in https://github.com/elastic/elasticsearch/commit/18a75fb30c9d186dac0c232d9ca85445892ee5ca
