### ISSUE TITLE
Switching from log4j to slf4j breaks ES 2.0 bin/plugin

### ISSUE THREAD

**Issue by jprante** [elastic/elasticsearch#14685]
When using slf4j instead of log4j, the ES 2.0 plugin tool breaks with

```
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/PropertyConfigurator
	at org.elasticsearch.common.logging.log4j.LogConfigurator.configure(LogConfigurator.java:128)
	at org.elasticsearch.plugins.PluginManagerCliParser.main(PluginManagerCliParser.java:67)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.PropertyConfigurator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

There is a strict dependency on log4j in the `PluginManagerCliParser` which should not be there. 

`EsLoggerFactory` handles support of log4j, slf4j, and jdk logging gracefully at https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/logging/ESLoggerFactory.java#L33-L48

Reproduction:

- remove log4j jar from lib
- add slf4j-api-1.7.13.jar to lib (and probably log4j2 or other slf4j impls)
- start of ES 2.0 works
- start of `bin/plugin` breaks

If you could upgrade from log4j to log4j2 by default, it would be much appreciated.

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/16585
