### ISSUE TITLE
gradle puts wrong java version in manifest

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#14702]
if i build a zip with java 9, then switch to java 8 to run it:

```
rmuir@beast:~/workspace/elasticsearch/distribution/zip/build/distributions/elasticsearch-3.0.0-SNAPSHOT$ bin/elasticsearch
Exception in thread "main" java.lang.IllegalStateException: /home/rmuir/workspace/elasticsearch/distribution/zip/build/distributions/elasticsearch-3.0.0-SNAPSHOT/lib/elasticsearch-3.0.0-SNAPSHOT.jar requires Java 1.9:, your system: 1.8
	at org.elasticsearch.bootstrap.JarHell.checkJavaVersion(JarHell.java:249)
	at org.elasticsearch.bootstrap.JarHell.checkManifest(JarHell.java:217)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:177)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:87)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:164)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```

**Comment by rmuir** [comment]
actually the class files must be correct, we aren't that good. its the manifest that is wrong.
