### ISSUE TITLE
elasticsearch failed to execute on node

### ISSUE THREAD

**Issue by shravankodipaka** [elastic/elasticsearch#14729]
Hi all, am facing the below issue while checking the log file of Elasticsearch. My environment is AWS EC2 instance, am installed ELK-stack on the instance, am unable to load the logs data from logstash to elasticsearch...then am cross checked the log file of elasticsearch i seen the below message in elasticsearch.log..  
Please help me from this issue... 

[2015-11-13 00:52:40,858][INFO ][cluster.service          ] [May Parker] added {[Clearcut][TBNd6XIrTHqje7vD9qk2tA][ip-10-129-52-27.ap-southeast-1.compute.internal][inet[/10.129.52.27:9301]],}, reason: zen-disco-receive(join from node[[Clearcut][TBNd6XIrTHqje7vD9qk2tA][ip-10-129-52-27.ap-southeast-1.compute.internal][inet[/10.129.52.27:9301]]])
[2015-11-13 00:59:12,840][DEBUG][action.admin.cluster.node.stats] [May Parker] failed to execute on node [TBNd6XIrTHqje7vD9qk2tA]
org.elasticsearch.transport.ReceiveTimeoutTransportException: [Clearcut][inet[/10.129.52.27:9301]][cluster:monitor/nodes/stats[n]] request_id [1572] timed out after [15001ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:529)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2015-11-13 00:59:42,839][DEBUG][action.admin.cluster.node.stats] [May Parker] failed to execute on node [TBNd6XIrTHqje7vD9qk2tA]
org.elasticsearch.transport.ReceiveTimeoutTransportException: [Clearcut][inet[/10.129.52.27:9301]][cluster:monitor/nodes/stats[n]] request_id [1605] timed out after [15000ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:529)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2015-11-13 01:00:12,839][DEBUG][action.admin.cluster.node.stats] [May Parker] failed to execute on node [TBNd6XIrTHqje7vD9qk2tA]
"elasticsearch.log" 239L, 40979C

Thanks,
Shravan K.

**Comment by dadoonet** [comment]
Does not look like an issue here. Could you please open a thread on discuss.elastic.co instead?

**Comment by shravankodipaka** [comment]
thank u....
