### ISSUE TITLE
link to scripts: java.security.AccessControlException: access denied ("java.io.FilePermission"...

### ISSUE THREAD

**Issue by twigbranch** [elastic/elasticsearch#14733]
In ES 1.x I was able to symbolically link from a subdirectory of the scripts directory to a directory containing my groovy scripts. Now, with ES 2.0, on load, I get the following error:

Exception in thread "main" java.security.AccessControlException: access denied ("java.io.FilePermission" "/usr/local/Cellar/elasticsearch/2.0.0_1/libexec/config/scripts/my_directory/my_subdirectory" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at sun.nio.fs.UnixPath.checkRead(UnixPath.java:795)
	at sun.nio.fs.UnixFileSystemProvider.checkAccess(UnixFileSystemProvider.java:290)
	at java.nio.file.Files.exists(Files.java:2385)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.init(FileWatcher.java:157)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.createChild(FileWatcher.java:173)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.listChildren(FileWatcher.java:188)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.onDirectoryCreated(FileWatcher.java:299)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.init(FileWatcher.java:162)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.createChild(FileWatcher.java:173)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.listChildren(FileWatcher.java:188)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.onDirectoryCreated(FileWatcher.java:299)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.init(FileWatcher.java:162)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.access$000(FileWatcher.java:75)
	at org.elasticsearch.watcher.FileWatcher.doInit(FileWatcher.java:65)
	at org.elasticsearch.watcher.AbstractResourceWatcher.init(AbstractResourceWatcher.java:36)
	at org.elasticsearch.watcher.ResourceWatcherService.add(ResourceWatcherService.java:133)
	at org.elasticsearch.watcher.ResourceWatcherService.add(ResourceWatcherService.java:126)
	at org.elasticsearch.script.ScriptService.<init>(ScriptService.java:192)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at <<<guice>>>
	at org.elasticsearch.node.Node.<init>(Node.java:198)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170)
	<<<truncated>>>

**Comment by dadoonet** [comment]
Have a look at https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_plugin_and_packaging_changes.html#_symbolic_links_and_paths

**Comment by dadoonet** [comment]
Sounds like we advertised we can follow symlinks for scripts?

**Comment by rmuir** [comment]
symbolic links are never supported. if they happen to work, its random chance.

**Comment by dadoonet** [comment]
@rmuir do I misunderstand the doc I linked?

**Comment by rmuir** [comment]
they are neither tested nor supported. we can't, we can't prevent some code from traversing the link (in which case unix permissions checks are different too, same problem).

**Comment by dadoonet** [comment]
I totally agree with you Robert. I'm just asking if we must fix the doc or if I simply misunderstood that part.

**Comment by rmuir** [comment]
What the documentation says works, that is not what is happening here.

**Comment by dadoonet** [comment]
So I definitely don't understand this:

> but no symlinks under that path will be followed (with the exception of path.scripts, which does follow symlinks).

My bad English I guess. Closing the "issue" then.

**Comment by twigbranch** [comment]
I saw that part of the docs before I posted the issue.  I, also, am confused by it.  With ES 1.5.2, What I was doing worked without issue on each installation I tried, both on Centos and OSX.  The doc quoted above says path.scripts "does follow symlinks" and symlinks under that path will be followed.  How is my symlink NOT under the path.scripts path?

path.scripts is not explicitly set in my elasticsearch.yml, so ES appears to be using the default.

This is my symlink:
/usr/local/Cellar/elasticsearch/2.0.0_1/libexec/config/scripts/my_directory/my_subdirectory -> /Users/tbr/projects/www/my_site/es/scripts

**Comment by nik9000** [comment]
I believe the document means that `config/scripts` itself can be a symlink but that symlinks within the directory aren't supported. I haven't tried it though.

**Comment by twigbranch** [comment]
The the doc should say symlinks from path.scripts, but not within, will be followed.

Or, even better ES would follow the symlinks within path.scripts.

**Comment by rmuir** [comment]
No, we don't need to do a recursive traversal for symlinks for security purposes, when symlinks themselves are broken from that perspective. Just don't use symlinks.

**Comment by dadoonet** [comment]
I prefer this wording. Symlinks are forbidden. Period. This is clear IMO.

**Comment by twigbranch** [comment]
OK. Then the doc should be updated - the combination of 'under' with plural for symlinks is confusing and makes it sound like you can have multiple symlinks within path.scripts.

**Comment by rmuir** [comment]
I agree, and the purpose of adding `path.scripts` in the first place was so that people could configure a shared location without resorting to stuff like symlinks.

**Comment by frutik** [comment]
path.scripts: /data/www/sample_name/releases/current/app/search/scripts

current - symlink to the directory with the current checkout of the application: releases/current -> releases/2016042701. 
What's wrong with such setup?

**Comment by frutik** [comment]
I investigated more, and issue exists only after switching symlink. I am getting 


[2016-04-28 04:33:46,444][WARN ][threadpool               ] [master-0] failed to run org.elasticsearch.watcher.ResourceWatcherService$ResourceMonitor@4b018985
java.security.AccessControlException: access denied ("java.io.FilePermission" "/data/www/sample_name/releases/current/app/search/scripts" "read")

After restart of elasticsearch, everything works as expected

**Comment by rjernst** [comment]
@frutik Symlinks in java security manager require adding permission for both the link and what the link points to. The `path.scripts` setting is read and followed at startup, and those permissions are added to the policy then. Simply changing the link while elasticsearch is running will not work. This is why restarting solved your problem, it re-read the link and added the setup the new appropriate permissions.
