### ISSUE TITLE
Reproducible - null Query in BoostingQueryBuilderTests throws assertion

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#14746]
Ran into this error while regression testing master.
```
Suite: org.elasticsearch.index.query.BoostingQueryBuilderTests
  2> REPRODUCE WITH: gradle :core:test -Dtests.seed=1817BD8B51E70A2 -Dtests.class=org.elasticsearch.index.query.BoostingQueryBuilderTests -Dtests.method="testToQuery" -Des.logger.level=WARN -Dtests.security.manager=true -Dtests.locale=es_EC -Dtests.timezone=America/Martinique
FAILURE 0.01s J1 | BoostingQueryBuilderTests.testToQuery <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: null
   >      but: was <mapped_boolean:F^0.1>
   > 	at __randomizedtesting.SeedInfo.seed([1817BD8B51E70A2:F67A79E6C49DB548]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.index.query.AbstractQueryTestCase.assertLuceneQuery(AbstractQueryTestCase.java:528)
   > 	at org.elasticsearch.index.query.AbstractQueryTestCase.testToQuery(AbstractQueryTestCase.java:476)
   > 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cbuescher** [comment]
Great catch, found the root cause for this. When we set up those query builder tests we randomly assign the `_name` field to a query. In rare cases we might accidentally pick the same name for subqueries and the main query under test, like in this case:
```
{
  "boosting" : {
    "positive" : { },
    "negative" : {
      "term" : {
        "mapped_boolean" : {
          "value" : false,
          "boost" : 0.1,
          "_name" : "q"
        }
      }
    },
    "negative_boost" : 0.6666667,
    "boost" : 1.0,
    "_name" : "q"
  }
}
```
When storing the queries by name in the shard context namedQueries map, this can lead to conflicts. Will change the test setup so this cannot happen any longer.
