### ISSUE TITLE
Marvel IndexNotFoundException on ES 2.0

### ISSUE THREAD

**Issue by johnarnold** [elastic/elasticsearch#14789]
Version:
johnar@flowmaster3:/usr/share/elasticsearch$ bin/elasticsearch --version
Version: 2.0.0, Build: de54438/2015-10-22T08:09:48Z, JVM: 1.8.0_60

Plugins:
johnar@flowmaster3:/usr/share/elasticsearch$ bin/plugin list
Installed plugins in /usr/share/elasticsearch/plugins:
    - marvel-agent
    - license
    - kopf
    - head

Full error description:
When trying to use the marvel plugin in Kibana4, I get a "no data" URL like:

https://elasticsearch:444/app/marvel#/no-data?_g=(refreshInterval:(display:'10%20seconds',pause:!f,value:10000),time:(from:now-1h,mode:quick,to:now))

In the elasticsearch log, I get an error that looks like the index was not created:
http://pastebin.com/crQgxDXM

Further up the log I'm also getting errors like:
[2015-11-16 22:40:20,981][INFO ][rest.suppressed          ] /_status Params: {index=_status}
java.lang.IllegalArgumentException: No feature for name [_status]
        at org.elasticsearch.action.admin.indices.get.GetIndexRequest$Feature.fromName(GetIndexRequest.java:82)
        at org.elasticsearch.action.admin.indices.get.GetIndexRequest$Feature.convertToFeatures(GetIndexRequest.java:95)
        at org.elasticsearch.rest.action.admin.indices.get.RestGetIndicesAction.handleRequest(RestGetIndicesAction.java:77)

If I search for marvel related logs:
http://pastebin.com/PF5vce7x

**Comment by tlrx** [comment]
Thanks for reporting. The logs are truncated so I can't be sure of what is going on.

What is the layout of your cluster? One or more nodes? Is Marvel installed on all nodes? Does Marvel export data locally or via HTTP to another cluster? 

Can you please share a full log (from start) and your configuration please (take care to remove any sensitive data)?

**Comment by johnarnold** [comment]
[flowstash.txt](https://github.com/elastic/elasticsearch/files/36943/flowstash.txt)



[elasticsearch.yml.txt](https://github.com/elastic/elasticsearch/files/36945/elasticsearch.yml.txt)
Sure thanks for taking a look.  The cluster has (3) master nodes and (24) data nodes.  License and Marvel-agent plugins are installed on all nodes.  The marvel agent is using default config, exporting locally.

Some more digging reveals that I may only be seeing these errors on the first master node.  I spot checked the other two masters and a random data node and they're clean.  This master node also fell out of the cluster overnight...  Possibly something else bad going on with this node.

It is also worth noting, I'm still getting "no data" from the marvel app in kibana4, and the other nodes are posting errors like:
2015-11-17 15:51:54,205][DEBUG][action.admin.cluster.node.info] [flowmaster2] failed to execute on node [MzfyRE6sTMeZ6d-hGm_xlA]
RemoteTransportException[[flowdata13][10.10.10.23:9300][cluster:monitor/nodes/info[n]]]; nested: NotSerializableExceptionWrapper;
Caused by: NotSerializableExceptionWrapper[null]
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at org.elasticsearch.action.admin.cluster.node.info.PluginsInfo.writeTo(PluginsInfo.java:86)
        at org.elasticsearch.action.admin.cluster.node.info.NodeInfo.writeTo(NodeInfo.java:284)
        at org.elasticsearch.transport.netty.NettyTransportChannel.sendResponse(NettyTransportChannel.java:97)
        at org.elasticsearch.transport.netty.NettyTransportChannel.sendResponse(NettyTransportChannel.java:75)
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:211)
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:207)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:299)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

and 

[2015-11-17 17:07:20,708][DEBUG][action.admin.indices.stats] [flowdata1] [indices:monitor/stats] failed to execute operation for shard [[ipfix.2m-2015.09.25.05][9], node[0VqzKuFbR0iQ0ijw1C_GPA], [R], v[15], s[INITIALIZING], a[id=IldoY0ygQieYS4VpcDzb0w], unassigned_info[[reason=NODE_LEFT], at[2015-11-17T16:35:51.063Z], details[node_left[ojAMM5pCRMadJxtk2xFfHQ]]]]
[ipfix.2m-2015.09.25.05][[ipfix.2m-2015.09.25.05][9]] BroadcastShardOperationFailedException[operation indices:monitor/stats failed]; nested: ShardNotFoundException[no such shard];
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.onShardOperation(TransportBroadcastByNodeAction.java:399)
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.messageReceived(TransportBroadcastByNodeAction.java:376)
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.messageReceived(TransportBroadcastByNodeAction.java:365)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:299)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: [ipfix.2m-2015.09.25.05][[ipfix.2m-2015.09.25.05][9]] ShardNotFoundException[no such shard]
        at org.elasticsearch.index.IndexService.shardSafe(IndexService.java:198)
        at org.elasticsearch.action.admin.indices.stats.TransportIndicesStatsAction.shardOperation(TransportIndicesStatsAction.java:98)
        at org.elasticsearch.action.admin.indices.stats.TransportIndicesStatsAction.shardOperation(TransportIndicesStatsAction.java:47)
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.onShardOperation(TransportBroadcastByNodeAction.java:395)
        ... 7 more

**Comment by johnarnold** [comment]
[flowdata1.log.txt](https://github.com/elastic/elasticsearch/files/36949/flowdata1.log.txt)
[flowmaster2.log.txt](https://github.com/elastic/elasticsearch/files/36950/flowmaster2.log.txt)

Two additional logfiles, one from a data node and one from a "otherwise working" master node.

**Comment by johnarnold** [comment]
Also noticed marvel shards are unassigned:

johnar@flowmaster1:/var/log/elasticsearch$ curl -XGET http://localhost:9200/_cat/shards | grep marvel
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1 1192k    1 16299    0     0  16003      0  0:01:16  0:00:01  0:01:15 16010.marvel-es-2015.11.17  0  p INITIALIZING                  10.10.10.34 flowdata24
.marvel-es-2015.11.17  0  r UNASSIGNED
.marvel-es-2015.11.16  0  r INITIALIZING                  10.10.10.34 flowdata24
.marvel-es-2015.11.16  0  p STARTED      4013754  870.2mb 10.10.10.31 flowdata21
.marvel-es-2015.11.15  0  p UNASSIGNED
.marvel-es-2015.11.15  0  r UNASSIGNED
100 1192k  100 1192k    0     0  1166k      0  0:00:01  0:00:01 --:--:-- 1167k
.marvel-es-data        0  p INITIALIZING                  10.10.10.34 flowdata24
.marvel-es-data        0  r UNASSIGNED

**Comment by johnarnold** [comment]
I used cluster reroute API to force the primary and replica shards onto different nodes and my cluster is now green:

{
  "cluster_name" : "flowstash",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 25,
  "number_of_data_nodes" : 22,
  "active_primary_shards" : 7446,
  "active_shards" : 14892,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}

Still no data in Marvel.

**Comment by tlrx** [comment]
@johnarnold thanks for all these log files, there are very valuable things in (out of memory errors, concurrent modification while getting the nodes stats, unassigned shards etc).

 I'll dig into them and I'll inform you soon.

**Comment by tlrx** [comment]
@johnarnold Looks like flowmaster1 had an OutOfMemory error around [2015-11-17 05:38:26,357]... can you please see if the JVM created an heapdump on disk? Thanks

**Comment by clintongormley** [comment]
@tlrx @johnarnold ...in which case the shards probably weren't being assigned because of the bug that has been fixed here: https://github.com/elastic/elasticsearch/pull/14695

**Comment by tlrx** [comment]
@clintongormley thanks for the pointer. 

I also found a bug in marvel that may cause OOM errors if the shards stay unassigned for a long time. It will be fixed in next releases.

Anyway it does not explain why the shards of the marvel indices were not assigned. @johnarnold I'm curious to know why you have so many shards (24 per index) in your cluster? 

`"active_shards" : 14892` is a lot of shards...

**Comment by johnarnold** [comment]
24 data nodes, 1 primary shard per node.  This spreads the indexing work across all the nodes, keeps shard size to a reasonable size.

Where would the heapdump be on disk?

**Comment by tlrx** [comment]
> Where would the heapdump be on disk?

Thanks but I think it's useless now: we found and fixed the issue and it will be released soon.

> 24 data nodes, 1 primary shard per node. This spreads the indexing work across all the nodes, keeps shard size to a reasonable size.

Out of curiosity, what is a reasonable shard size in your case? And what is your indexing load?

**Comment by clintongormley** [comment]
thanks @tlrx. closing
