### ISSUE TITLE
Marvel not working after changing cluster.name to sth. else than elasticsearch

### ISSUE THREAD

**Issue by mdiehm** [elastic/elasticsearch#14807]
Marvel worked fine when the cluster was name elasticsearch. No I changed it and things went wrong. I have uninstalled marvel and licence and reinstalled with no success. I see there is a marvel index created in the indices directory:

root@moose:/var/lib/elasticsearch/hirschewiewir/nodes/0/indices# du -hs .marvel-es-*
16K     .marvel-es-2015.11.17
16K     .marvel-es-data

but the shareds are unassigned:
.marvel-es-data       0 p UNASSIGNED                                     
.marvel-es-data       0 r UNASSIGNED  

when I start elasticsearch i see in the logfile:
[2015-11-17 19:31:57,216][INFO ][plugins                  ] [moose] loaded [license, marvel], sites []

when I try to access the marvel plugin within kibana i get the following error message in the elasticsearch logfile: 

[2015-11-17 19:37:21,955][DEBUG][action.search.type       ] [moose] All shards failed for phase: [query_fetch]                                                                                                              [59/87]
[.marvel-es-data][[.marvel-es-data][0]] NoShardAvailableActionException[null]
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.start(TransportSearchTypeAction.java:151)
        at org.elasticsearch.action.search.type.TransportSearchQueryAndFetchAction.doExecute(TransportSearchQueryAndFetchAction.java:58)
        at org.elasticsearch.action.search.type.TransportSearchQueryAndFetchAction.doExecute(TransportSearchQueryAndFetchAction.java:47)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:70)
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:103)
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:44)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:70)
        at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:347)
        at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:52)
        at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient.doExecute(BaseRestHandler.java:83)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:347)
        at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:570)
        at org.elasticsearch.rest.action.search.RestSearchAction.handleRequest(RestSearchAction.java:84)
        at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:54)
        at org.elasticsearch.rest.RestController.executeHandler(RestController.java:207)
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:166)
        at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:128)
        at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:86)
        at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:348)
        at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:63)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by rabeetwaqar1** [comment]
I have the same issue, But i'm facing this while setting the cluster name to : elasticsearch

**Comment by clintongormley** [comment]
Could you try using the [cluster reroute API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-reroute.html)  with the `explain` query string param, to assign the primary marvel shard. It will tell you why the shard can't be assigned.

**Comment by johnarnold** [comment]
I tried it on my cluster, got an error like this:

{
  "error" : {
    "root_cause" : [ {
      "type" : "remote_transport_exception",
      "reason" : "[flowmaster3][10.10.10.6:9300][cluster:admin/reroute]"
    } ],
    "type" : "illegal_argument_exception",
    "reason" : "[allocate] trying to allocate a primary shard [.marvel-es-2015.11.18][0], which is disabled"
  },
  "status" : 400
}

**Comment by johnarnold** [comment]
I figured out that allocating the primary replica to a specific node works to assign it.

curl -XPOST 'localhost:9200/_cluster/reroute?pretty' -d '{
    "commands" : [ 
        {
          "allocate" : {
              "index" : ".marvel-es-data", "shard" : 0, "node" : "flowdata1", "allow_primary" : true
          }
        }
    ]
}'

I had to do this for each marvel shard in: curl -XGET http://localhost:9200/_cat/shards | grep marvel

**Comment by clintongormley** [comment]
@johnarnold i specifically didn't want you to force the primary.  instead I wanted to find out why the primary shard wasn't being allocated.  Nothing in the older logs giving a reason?

**Comment by johnarnold** [comment]
I managed to repro shard allocation problem.

[explain.txt](https://github.com/elastic/elasticsearch/files/40744/explain.txt)

**Comment by clintongormley** [comment]
OK so this is the interesting bit:

        ".marvel-es-2015.11.15" : {
          "shards" : {
            "0" : [ {
              "state" : "UNASSIGNED",
              "primary" : true,
              "node" : null,
              "relocating_node" : null,
              "shard" : 0,
              "index" : ".marvel-es-2015.11.15",
              "version" : 2,
              "unassigned_info" : {
                "reason" : "NODE_LEFT",
                "at" : "2015-11-21T04:50:34.073Z",
                "details" : "node_left[qKKxT9bPQeiVyioqNuhWlA]"
              }
            }, {
              "state" : "UNASSIGNED",
              "primary" : false,
              "node" : null,
              "relocating_node" : null,
              "shard" : 0,
              "index" : ".marvel-es-2015.11.15",
              "version" : 2,
              "unassigned_info" : {
                "reason" : "INDEX_CREATED",
                "at" : "2015-11-21T04:31:31.548Z"
              }
            } ]
          }
        },

The primary was assigned to a node which has since left, and the replica was never assigned.  Are you using shard allocation settings?

**Comment by clintongormley** [comment]
No more feedback. Closing
