### ISSUE TITLE
[CI Failure] GeoDistanceRangeQueryTests.testToQuery fails due to numeric precision problem

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#14838]
Via: http://build-us-00.elastic.co/job/es_core_master_centos/8587/testReport/junit/org.elasticsearch.index.query/GeoDistanceRangeQueryTests/testToQuery/

```
FAILURE 0.21s | GeoDistanceRangeQueryTests.testToQuery <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: a numeric value within <-0.33952242975718117> of <-0.3395224297571812>
   >      but: <-0.3395224297571813> differed by <0.3395224297571812>
   > 	at __randomizedtesting.SeedInfo.seed([5BDFC4A476C6B339:AC24C69A074576D3]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.index.query.GeoDistanceRangeQueryTests.assertLegacyQuery(GeoDistanceRangeQueryTests.java:165)
   > 	at org.elasticsearch.index.query.GeoDistanceRangeQueryTests.doAssertLuceneQuery(GeoDistanceRangeQueryTests.java:120)
   > 	at org.elasticsearch.index.query.GeoDistanceRangeQueryTests.doAssertLuceneQuery(GeoDistanceRangeQueryTests.java:41)
   > 	at org.elasticsearch.index.query.AbstractQueryTestCase.assertLuceneQuery(AbstractQueryTestCase.java:555)
   > 	at org.elasticsearch.index.query.AbstractQueryTestCase.testToQuery(AbstractQueryTestCase.java:487)
   > 	at org.elasticsearch.index.query.GeoDistanceRangeQueryTests.testToQuery(GeoDistanceRangeQueryTests.java:203)
   > 	at java.lang.Thread.run(Thread.java:745)
```

Reproduces with:

```
gradle :core:test -Dtests.seed=5BDFC4A476C6B339 -Dtests.class=org.elasticsearch.index.query.GeoDistanceRangeQueryTests -Dtests.method="testToQuery" -Des.logger.level=DEBUG -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=1024m -Dtests.jvm.argline="-server -XX:+UseParallelGC -XX:+UseCompressedOops -XX:+AggressiveOpts" -Dtests.locale=pt -Dtests.timezone=America/New_York
```

**Comment by dakrone** [comment]
@nknize can you take a look at this?
