### ISSUE TITLE
Search using alias + type returns {"error": null}

### ISSUE THREAD

**Issue by kadishmal** [elastic/elasticsearch#14875]
Very strange. Using ES 1.7.3 on CentOS 6.3 x64.

1. First, create an alias for an existing index.

   ```
   POST /_aliases
   {
       "actions" : [
           { "add" : { "index" : "v2-log-2015-11-19", "alias" : "log-2015-11-19" } }
       ]
   }
   ```

2. Then perform a search using the new alias:

    ```
    POST /log-2015-11-19/webapp/_search?routing=webapp
    {
      "query": {
        "filtered": {
          "filter": {
            "range": {
              "logTime": {
                "from": 1447910416536,
                "to": 1447996816535
              }
            }
          }
        }
      }
    }
    ```

    Returns:

    ```
    {
       "error": null
    }
    ```

    The ES logs say:

    ```
    [2015-11-20 14:36:38,813][DEBUG][org.eclipse.jetty.io.nio ] [bumbobox.dev] created SCEP@2a7c878a{l(/10.11.12.13:45811)<->r(/10.11.12.15:9200),s=0,open=true,ishut=false,oshut=false,rb=false,wb=false,w=true,i=0}-{AsyncHttpConnection@55a68ad0,g=HttpGenerator{s=0,h=-1,b=-1,c=-1},p=HttpParser{s=-14,l=0,c=0},r=0}
    [2015-11-20 14:36:38,813][DEBUG][org.eclipse.jetty.server.Server] [bumbobox.dev] REQUEST /log-2015-11-19/webapp/_search on AsyncHttpConnection@55a68ad0,g=HttpGenerator{s=0,h=-1,b=-1,c=-1},p=HttpParser{s=6,l=7,c=-2},r=1
    [2015-11-20 14:36:38,814][DEBUG][index.analysis.rest      ] [bumbobox.dev] failed to parse search request parameters
    java.lang.NullPointerException
            at org.elasticsearch.index.analysis.rest.TokenizerRestAction.handleRequest(TokenizerRestAction.java:93)
            at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:53)
            at org.elasticsearch.rest.RestController.executeHandler(RestController.java:225)
            at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:170)
            at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:121)
            at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:83)
            at com.sonian.elasticsearch.http.jetty.handler.JettyHttpServerTransportHandler.handle(JettyHttpServerTransportHandler.java:69)
            at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:522)
            at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
            at org.eclipse.jetty.server.Server.handle(Server.java:366)
            at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
            at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
            at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
            at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:957)
            at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
            at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
            at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
            at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
            at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
            at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
            at java.lang.Thread.run(Thread.java:745)
    [2015-11-20 14:36:38,815][DEBUG][org.eclipse.jetty.server.Server] [bumbobox.dev] RESPONSE /log-2015-11-19/webapp/_search  400 handled=false
    ```

3. If you search the original index directly, then it works properly:

    ```
    POST /v2-log-2015-11-19/webapp/_search?routing=webapp
    {
      "query": {
        "filtered": {
          "filter": {
            "range": {
              "logTime": {
                "from": 1447910416536,
                "to": 1447996816535
              }
            }
          }
        }
      }
    }
    ```

    Returns:

    ```
    {
       "took": 2,
       "timed_out": false,
       "_shards": {
          "total": 1,
          "successful": 1,
          "failed": 0
       },
       "hits": {
          "total": 3960,
          "max_score": 1,
          "hits": [
             {
                    ....
    ```

4. Alternatively, if you remove the type from the alias based search request, the response is correct.

    ```
    POST /log-2015-11-19/_search
    {
      "query": {
        "filtered": {
          "filter": {
            "range": {
              "logTime": {
                "from": 1447910416536,
                "to": 1447996816535
              }
            }
          }
        }
      }
    }
    ```

    Returns:

    ```
    {
       "took": 165,
       "timed_out": false,
       "_shards": {
          "total": 15,
          "successful": 15,
          "failed": 0
       },
       "hits": {
          "total": 68061695,
          "max_score": 1,
          "hits": [
             {
                    ....
    ```

All the above is same when using any different type.

Is there anything I am doing wrong?

**Comment by kadishmal** [comment]
This seems to be related to our internal highlight plugin that we use.
