### ISSUE TITLE
Expired documents purge is not working after installing Shield Plugin

### ISSUE THREAD

**Issue by vikasgithub** [elastic/elasticsearch#14876]
I am trying out the ElasticSearch purge functionality for expired documents. It works fine when I do not have Shield plugin configured. But, as soon as I have Shield plugin configured, I get the following error

2015-11-20 09:40:52,052][DEBUG][shield.authz.accesscontrol] [localhost] [test][4] couldn't locate the current request, field level security will only allow meta fields
2015-11-20 09:40:52,053][DEBUG][indices.ttl              ] [localhost] [test][4] purging shard
2015-11-20 09:40:52,054][WARN ][indices.ttl              ] [localhost] failed to purge
java.lang.IllegalStateException: opting out of the query cache. current request can't be found
       at org.elasticsearch.shield.authz.accesscontrol.OptOutQueryCache.doCache(OptOutQueryCache.java:62)
       at org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:853)
       at org.apache.lucene.search.IndexSearcher.createNormalizedWeight(IndexSearcher.java:834)
       at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:485)
       at org.elasticsearch.indices.ttl.IndicesTTLService.purgeShards(IndicesTTLService.java:204)
       at org.elasticsearch.indices.ttl.IndicesTTLService.access$000(IndicesTTLService.java:67)
       at org.elasticsearch.indices.ttl.IndicesTTLService$PurgerThread.run(IndicesTTLService.java:140)

I have username and password authentication enabled in Shield. I have enabled anonymous access as well. But, the error is same in all cases.

I am using Java 7.0, ElasticSearch 2.0 and Shield 2.0.

**Comment by dadoonet** [comment]
I think you are hitting this known limitation: https://www.elastic.co/guide/en/shield/current/limitations.html#_document_expiration__ttl

**Comment by hemantpatil25** [comment]
Hi , I am facing the same issue. I have configured the shield plugin over the ES due to this i got multiple error like as below

failed to purge
java.lang.IllegalStateException: opting out of the query cache. current request can't be found
	at org.elasticsearch.shield.authz.accesscontrol.OptOutQueryCache.doCache(OptOutQueryCache.java:61)
	at org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:906)
	at org.apache.lucene.search.IndexSearcher.createNormalizedWeight(IndexSearcher.java:887)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:535)
	at org.elasticsearch.indices.ttl.IndicesTTLService.purgeShards(IndicesTTLService.java:204)
	at org.elasticsearch.indices.ttl.IndicesTTLService.access$000(IndicesTTLService.java:67)
	at org.elasticsearch.indices.ttl.IndicesTTLService$PurgerThread.run(IndicesTTLService.java:140)


Please let me know how i can fixed this issue. Is there any configuration change i need to do?
