### ISSUE TITLE
Should ELasticSearch work with Windows Server 2008 R2 

### ISSUE THREAD

**Issue by acb122** [elastic/elasticsearch#14947]
I recently upgraded to elastic search 2.0 on my Windows Server 2008 R2 machine, I am now getting a java error when trying to run it, is 2008 still supported?

**Comment by dadoonet** [comment]
Yes. But may be you can describe which exact error you have.

A better place could be to ask that in discuss.elastic.co.

**Comment by acb122** [comment]
it was this url https://www.elastic.co/support/matrix which seems to show it wasn't supported. But no issues online i could find.

**Comment by acb122** [comment]
at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived
(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(S
impleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultCh
annelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerC
ontext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(Ope
nChannelsHandler.java:75)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultCh
annelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultCh
annelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:26
8)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:25
5)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(Abstract
NioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNi
oSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioW
orker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnabl
e.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProof
Worker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2015-11-23 16:18:19,107][INFO ][node                     ] [opus] stopping ...
[2015-11-23 16:18:19,216][INFO ][node                     ] [opus] stopped
[2015-11-23 16:18:19,231][INFO ][node                     ] [opus] closing ...
[2015-11-23 16:18:19,231][INFO ][node                     ] [opus] closed
Terminate batch job (Y/N)? y

D:\elasticsearch-2.0.0>bin\elasticsearch.bat
[2015-11-23 16:22:02,343][INFO ][node                     ] [opus] version[2.0.0
], pid[8632], build[de54438/2015-10-22T08:09:48Z]
[2015-11-23 16:22:02,343][INFO ][node                     ] [opus] initializing
...
[2015-11-23 16:22:02,421][INFO ][plugins                  ] [opus] loaded [], si
tes []
[2015-11-23 16:22:02,483][INFO ][env                      ] [opus] using [1] dat
a paths, mounts [[D_Data (D:)]], net usable_space [681gb], net total_space [683.
3gb], spins? [unknown], types [NTFS]
[2015-11-23 16:22:04,293][INFO ][node                     ] [opus] initialized
[2015-11-23 16:22:04,293][INFO ][node                     ] [opus] starting ...
[2015-11-23 16:22:04,917][INFO ][transport                ] [opus] publish_addre
ss {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}, {[::1]:9300}
[2015-11-23 16:22:04,917][INFO ][discovery                ] [opus] opus/K0OL0MD4
RhyZRiFPIPMG3Q
[2015-11-23 16:22:08,988][INFO ][cluster.service          ] [opus] new_master {o
pus}{K0OL0MD4RhyZRiFPIPMG3Q}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-join(
elected_as_master, [0] joins received)
[2015-11-23 16:22:09,082][INFO ][gateway                  ] [opus] recovered [1]
 indices into cluster_state
[2015-11-23 16:22:09,503][INFO ][http                     ] [opus] publish_addre
ss {127.0.0.1:9201}, bound_addresses {127.0.0.1:9201}, {[::1]:9201}
[2015-11-23 16:22:09,503][INFO ][node                     ] [opus] started
[2015-11-23 16:23:15,579][INFO ][rest.suppressed          ] /o/_mapping/field/*
Params: {ignore_unavailable=false, allow_no_indices=false, index=o, include_defa
ults=true, fields=*, _=1448295795436}
[o] IndexNotFoundException[no such index]
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$Wildca
rdExpressionResolver.resolve(IndexNameExpressionResolver.java:560)
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concre
teIndices(IndexNameExpressionResolver.java:127)
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concre
teIndices(IndexNameExpressionResolver.java:71)
        at org.elasticsearch.action.admin.indices.mapping.get.TransportGetFieldM
appingsAction.doExecute(TransportGetFieldMappingsAction.java:57)
        at org.elasticsearch.action.admin.indices.mapping.get.TransportGetFieldM
appingsAction.doExecute(TransportGetFieldMappingsAction.java:40)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAct
ion.java:70)
        at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58
)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClien
t.java:347)
        at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:52)

        at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient.do
Execute(BaseRestHandler.java:83)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClien
t.java:347)
        at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(
AbstractClient.java:1177)
        at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.getField
Mappings(AbstractClient.java:1377)
        at org.elasticsearch.rest.action.admin.indices.mapping.get.RestGetFieldM
appingAction.handleRequest(RestGetFieldMappingAction.java:66)
        at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.
java:54)
        at org.elasticsearch.rest.RestController.executeHandler(RestController.j
ava:207)
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.
java:166)
        at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.
java:128)
        at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServ
er.java:86)
        at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest
(NettyHttpServerTransport.java:348)
        at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpR
equestHandler.java:63)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(S
impleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultCh
annelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerC
ontext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.message
Received(HttpPipeliningHandler.java:60)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleCha
nnelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultCh
annelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerC
ontext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceive
d(HttpChunkAggregator.java:145)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(S
impleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultCh
annelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerC
ontext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived
(HttpContentDecoder.java:108)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(S
impleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultCh
annelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerC
ontext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:29
6)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessage
Received(FrameDecoder.java:459)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(Repl
ayingDecoder.java:536)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived
(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(S
impleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultCh
annelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerC
ontext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(Ope
nChannelsHandler.java:75)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultCh
annelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultCh
annelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:26
8)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:25
5)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(Abstract
NioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNi
oSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioW
orker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnabl
e.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProof
Worker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2015-11-23 16:23:16,421][INFO ][rest.suppressed          ] /op/_mapping/field/*
 Params: {ignore_unavailable=false, allow_no_indices=false, index=op, include_de
faults=true, fields=*, _=1448295796296}
[op] IndexNotFoundException[no such index]
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$Wildca
rdExpressionResolver.resolve(IndexNameExpressionResolver.java:560)
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concre
teIndices(IndexNameExpressionResolver.java:127)
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concre
teIndices(IndexNameExpressionResolver.java:71)
        at org.elasticsearch.action.admin.indices.mapping.get.TransportGetFieldM
appingsAction.doExecute(TransportGetFieldMappingsAction.java:57)
        at org.elasticsearch.action.admin.indices.mapping.get.TransportGetFieldM
appingsAction.doExecute(TransportGetFieldMappingsAction.java:40)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAct
ion.java:70)
        at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58
)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClien
t.java:347)
        at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:52)

        at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient.do
Execute(BaseRestHandler.java:83)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClien
t.java:347)
        at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(
AbstractClient.java:1177)
        at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.getField
Mappings(AbstractClient.java:1377)
        at org.elasticsearch.rest.action.admin.indices.mapping.get.RestGetFieldM
appingAction.handleRequest(RestGetFieldMappingAction.java:66)
        at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.
java:54)
        at org.elasticsearch.rest.RestController.executeHandler(RestController.j
ava:207)
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.
java:166)
        at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.
java:128)
        at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServ
er.java:86)
        at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest
(NettyHttpServerTransport.java:348)
        at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpR
equestHandler.java:63)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(S
impleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultCh
annelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerC
ontext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.message
Received(HttpPipeliningHandler.java:60)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleCha
nnelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultCh
annelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerC
ontext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceive
d(HttpChunkAggregator.java:145)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(S
impleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultCh
annelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerC
ontext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived
(HttpContentDecoder.java:108)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(S
impleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultCh
annelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerC
ontext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:29
6)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessage
Received(FrameDecoder.java:459)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(Repl
ayingDecoder.java:536)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived
(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(S
impleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultCh
annelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerC
ontext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(Ope
nChannelsHandler.java:75)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultCh
annelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultCh
annelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:26
8)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:25
5)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(Abstract
NioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNi
oSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioW
orker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnabl
e.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProof
Worker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by dadoonet** [comment]
Ha. I misread the issue. I thought you were talking about 2012 not 2008.

**Comment by dadoonet** [comment]
About the "issue", sounds like you PUT a mapping in a non existing index or so?

May be you could describe what you are doing on discuss.elastic.co?

Closing here as not an issue.
