### ISSUE TITLE
After upgrade 2.0.0 -> 2.1.0 NoSuchFileException while deleting tlog files on *every* shard

### ISSUE THREAD

**Issue by uschindler** [elastic/elasticsearch#14989]
After upgrading a single node elasticsearch installation with 3 indexes, on startup Elasticsearch produces a message in the log file like the following:

```
[2015-11-24 22:36:38,840][WARN ][index.translog           ] [PANGAEA Elasticsearch] [portals_v1][1] failed to delete temp file /pangaea/elasticsearch/data/pangaea/nodes/0/indices/portals_v1/1/translog/translog-1417903832395804337.tlog
java.nio.file.NoSuchFileException: /pangaea/elasticsearch/data/pangaea/nodes/0/indices/portals_v1/1/translog/translog-1417903832395804337.tlog
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
        at java.nio.file.Files.delete(Files.java:1126)
        at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:324)
        at org.elasticsearch.index.translog.Translog.<init>(Translog.java:166)
        at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:209)
        at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:152)
        at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
        at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1408)
        at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1403)
        at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:906)
        at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:883)
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:245)
        at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
        at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

You get one message per shard. The file really does not exist! The index works fine afterwards.

If you restart elasticsearch again the same errors occur again, but with different filenames.

Operating system is Ubuntu 14.04; debian package installation:
root@pangaea-mw1:~# uname -a
Linux pangaea-mw1 3.13.0-66-generic #108-Ubuntu SMP Wed Oct 7 15:20:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

This is not a blocker for me because everything works and I don't care about tranlog, but users that rely on it working may have problems.

All indexes were recreated a week ago with 2.0.0.

**Comment by s1monw** [comment]
my bad I guess, I think this is a side-effect of https://github.com/elastic/elasticsearch/pull/14695 I will look. It's shouldn't be a problem but the message is annoying!  sorry for the noise

**Comment by s1monw** [comment]
this has already been fixed here https://github.com/elastic/elasticsearch/pull/14872

**Comment by uschindler** [comment]
OK thanks @s1monw,
I was not sure if this is a real "error" and may cause corrumption so I better opened an issue (@rmuir suggested this). The log level was warning anyway, but a stack trace always alerts you.

**Comment by s1monw** [comment]
yeah no worries - thanks for opening the issue

**Comment by kirrg001** [comment]
same here

[2015-11-26 15:01:25,607][WARN ][index.translog           ] [Marrow] [staging-stats-2015.09.20][4] failed to delete temp file /data/elasticsearch/elasticsearch/nodes/0/indices/test/4/translog/translog-4738663133382677499.tlo

**Comment by damm** [comment]
I get this; however it never recovers?

**Comment by uschindler** [comment]
The messages are repeated on every server restart, so yes it does not recovers from that state. According to @s1monw and the [WARN] message this is just a warning and does not affect your index. So just wait for update #14872 to get released.

**Comment by damm** [comment]
Ouch I hope 2.1.1 hits soon then

**Comment by Namita26** [comment]
[2015-11-30 15:54:05,217][WARN ][index.translog           ] [Miguel O'Hara] [questions][2] failed to delete temp file /Users/kechit/softwares/elasticsearch-2.1.0/data/elasticsearch/nodes/0/indices/questions/2/translog/translog-1286082166987208532.tlog
java.nio.file.NoSuchFileException: /Users/kechit/softwares/elasticsearch-2.1.0/data/elasticsearch/nodes/0/indices/questions/2/translog/translog-1286082166987208532.tlog
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
    at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
    at java.nio.file.Files.delete(Files.java:1126)
    at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:324)
    at org.elasticsearch.index.translog.Translog.<init>(Translog.java:166)
    at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:209)
    at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:152)
    at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
    at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1408)
    at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1403)
    at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:906)
    at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:883)
    at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:245)
    at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
    at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

**Comment by clintongormley** [comment]
@Namita26 this log message is harmless. just ignore it

**Comment by damm** [comment]
That's the confusing part is I've actually had failures with that same message... it should be harmless but it doesn't seem to be?

**Comment by Namita26** [comment]
Cool. I was able to do everything what I wanted even if this warning was coming! So :)

**Comment by masifpak** [comment]
My log file dbrdsa.log.2015-12-03 filled upto 160GB. Can it be deleted automatically otherwise it will occupy my whole storage.

**Comment by kgignatyev** [comment]
Noisy logs are not good, please consider making non-critical issues less visible, otherwise it is hard to distinguish between real issues and harmless notes

**Comment by teeschke** [comment]
I am running 2.1.0 on CentOS and have the same issue. But the reported error is real: the translog folders are growing because clean-up job is failing.
see "du -h" command
```
4,0K	./_state
66M	./2/index
34G	./2/translog
4,0K	./2/_state
34G	./2
133M	./3/index
8,0K	./3/translog
4,0K	./3/_state
133M	./3
132M	./1/index
34G	./1/translog
4,0K	./1/_state
34G	./1
53M	./0/index
34G	./0/translog
4,0K	./0/_state
34G	./0
132M	./4/index
8,0K	./4/translog
4,0K	./4/_state
132M	./4
101G	.
```

the elasticsearch logfiles are full of messages with the following pattern:
```
[2016-02-04 22:00:21,828][WARN ][cluster.action.shard     ] [Ruby Thursday] [my_application][1] received shard failed for [my_application][1], node[H6mW8DMZTJ2wENc013Q42A], [P], v[119], s[INITIALIZING], a[id=0GK9JCovTresNYzyj0y7Cw], unassigned_info[[reason=ALLOCATION_FAILED], at[2016-02-04T21:53:42.844Z], details[failed recovery, failure IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to recover from translog]; nested: EngineException[failed to recover from translog]; nested: ElasticsearchException[unexpected exception reading from translog snapshot of /var/lib/elasticsearch/my_elasticsearch/nodes/0/indices/my_application/1/translog/translog-30.tlog]; nested: EOFException[read requested past EOF. pos [44120241] end: [44120241]]; ]], indexUUID [rofptGBoSLuIrNqkyBpvNA], message [failed recovery], failure [IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to recover from translog]; nested: EngineException[failed to recover from translog]; nested: ElasticsearchException[unexpected exception reading from translog snapshot of /var/lib/elasticsearch/my_elasticsearch/nodes/0/indices/my_application/1/translog/translog-30.tlog]; nested: EOFException[read requested past EOF. pos [44120241] end: [44120241]]; ]
[my_application][[my_application][1]] IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to recover from translog]; nested: EngineException[failed to recover from translog]; nested: ElasticsearchException[unexpected exception reading from translog snapshot of /var/lib/elasticsearch/my_elasticsearch/nodes/0/indices/my_application/1/translog/translog-30.tlog]; nested: EOFException[read requested past EOF. pos [44120241] end: [44120241]];
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:254)
	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [my_application][[my_application][1]] EngineCreationFailureException[failed to recover from translog]; nested: EngineException[failed to recover from translog]; nested: ElasticsearchException[unexpected exception reading from translog snapshot of /var/lib/elasticsearch/my_elasticsearch/nodes/0/indices/my_application/1/translog/translog-30.tlog]; nested: EOFException[read requested past EOF. pos [44120241] end: [44120241]];
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:178)
	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1408)
	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1403)
	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:906)
	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:883)
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:245)
	... 5 more
Caused by: [my_application][[my_application][1]] EngineException[failed to recover from translog]; nested: ElasticsearchException[unexpected exception reading from translog snapshot of /var/lib/elasticsearch/my_elasticsearch/nodes/0/indices/my_application/1/translog/translog-30.tlog]; nested: EOFException[read requested past EOF. pos [44120241] end: [44120241]];
	at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:254)
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:175)
	... 11 more
Caused by: ElasticsearchException[unexpected exception reading from translog snapshot of /var/lib/elasticsearch/my_elasticsearch/nodes/0/indices/my_application/1/translog/translog-30.tlog]; nested: EOFException[read requested past EOF. pos [44120241] end: [44120241]];
	at org.elasticsearch.index.translog.TranslogReader.readSize(TranslogReader.java:102)
	at org.elasticsearch.index.translog.TranslogReader.access$000(TranslogReader.java:46)
	at org.elasticsearch.index.translog.TranslogReader$ReaderSnapshot.readOperation(TranslogReader.java:297)
	at org.elasticsearch.index.translog.TranslogReader$ReaderSnapshot.next(TranslogReader.java:290)
	at org.elasticsearch.index.translog.MultiSnapshot.next(MultiSnapshot.java:70)
	at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:240)
	... 12 more
Caused by: java.io.EOFException: read requested past EOF. pos [44120241] end: [44120241]
	at org.elasticsearch.index.translog.ImmutableTranslogReader.readBytes(ImmutableTranslogReader.java:79)
	at org.elasticsearch.index.translog.TranslogReader.readSize(TranslogReader.java:91)
	... 17 more
[2016-02-04 22:00:21,948][WARN ][index.translog           ] [Ruby Thursday] [my_application][1] failed to delete temp file /var/lib/elasticsearch/my_elasticsearch/nodes/0/indices/my_application/1/translog/translog-2956456055072727048.tlog
java.nio.file.NoSuchFileException: /var/lib/elasticsearch/my_elasticsearch/nodes/0/indices/my_application/1/translog/translog-2956456055072727048.tlog
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:324)
	at org.elasticsearch.index.translog.Translog.<init>(Translog.java:166)
	at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:209)
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:152)
	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1408)
	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1403)
	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:906)
	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:883)
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:245)
	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by teeschke** [comment]
Aright. An upgrade from 2.1.0 to 2.1.1 fixed it! 
Thanks.
