### ISSUE TITLE
testUpgradeOldMapping200 fails

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#15034]
See: http://build-us-00.elastic.co/job/es_core_21_strong/363/

```
Failed to execute phase [query_fetch], all shards failed
	at __randomizedtesting.SeedInfo.seed([13BE8512880D9B9B:3332E128222610B]:0)
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:228)
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:174)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:821)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:799)
	at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:361)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Sadly this doesn't reproduce locally for me. It may be related to #14896, so @jpountz can you please take a look?

**Comment by bleskes** [comment]
another example, if it helps: http://build-us-00.elastic.co/job/es_core_2.x_oel_6/1202

**Comment by jpountz** [comment]
Fixed by @s1monw  (thanks)
