### ISSUE TITLE
SharedClusterSnapshotRestoreIT.changeSettingsOnRestoreTest times out

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#15040]
See 
http://build-us-00.elastic.co/job/es_core_21_metal/264

**Comment by ywelsch** [comment]
Looks to me like filesystem error.

We have threads hanging in sun.nio.ch.FileDispatcherImpl.force0(Native Method).

Interesting bits in log:

```
[2015-11-26 01:54:03,961][DEBUG][netty.channel.socket.nio.AbstractNioSelector] Selector.select() returned prematurely because the I/O thread has been interrupted. Use shutdown() to shut the NioSelector down.
[2015-11-26 01:54:03,961][DEBUG][netty.channel.socket.nio.AbstractNioSelector] Selector.select() returned prematurely because the I/O thread has been interrupted. Use shutdown() to shut the NioSelector down.
[2015-11-26 01:54:03,961][DEBUG][netty.channel.socket.nio.AbstractNioSelector] Selector.select() returned prematurely because the I/O thread has been interrupted. Use shutdown() to shut the NioSelector down.
[2015-11-26 01:54:03,964][DEBUG][netty.channel.socket.nio.AbstractNioSelector] Selector.select() returned prematurely because the I/O thread has been interrupted. Use shutdown() to shut the NioSelector down.
[2015-11-26 01:54:03,964][DEBUG][netty.channel.socket.nio.AbstractNioSelector] Selector.select() returned prematurely because the I/O thread has been interrupted. Use shutdown() to shut the NioSelector down.
[2015-11-26 01:54:03,964][DEBUG][netty.channel.socket.nio.AbstractNioSelector] Selector.select() returned prematurely because the I/O thread has been interrupted. Use shutdown() to shut the NioSelector down.
[2015-11-26 01:54:03,965][DEBUG][netty.channel.socket.nio.AbstractNioSelector] Selector.select() returned prematurely because the I/O thread has been interrupted. Use shutdown() to shut the NioSelector down.
[2015-11-26 01:54:03,965][DEBUG][netty.channel.socket.nio.AbstractNioSelector] Selector.select() returned prematurely because the I/O thread has been interrupted. Use shutdown() to shut the NioSelector down.
[2015-11-26 01:54:03,965][DEBUG][netty.channel.socket.nio.AbstractNioSelector] Selector.select() returned prematurely because the I/O thread has been interrupted. Use shutdown() to shut the NioSelector down.
[2015-11-26 01:54:03,965][DEBUG][netty.channel.socket.nio.AbstractNioSelector] Selector.select() returned prematurely because the I/O thread has been interrupted. Use shutdown() to shut the NioSelector down.
[2015-11-26 01:54:03,965][WARN ][gateway                  ] [node_s0] [_global]: failed to write global state
org.apache.lucene.util.ThreadInterruptedException: java.lang.InterruptedException: sleep interrupted
	at org.apache.lucene.util.IOUtils.fsync(IOUtils.java:406)
	at org.elasticsearch.gateway.MetaDataStateFormat.write(MetaDataStateFormat.java:133)
	at org.elasticsearch.gateway.MetaStateService.writeGlobalState(MetaStateService.java:149)
	at org.elasticsearch.gateway.GatewayMetaState.clusterChanged(GatewayMetaState.java:148)
	at org.elasticsearch.gateway.Gateway.clusterChanged(Gateway.java:185)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:494)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: java.nio.channels.ClosedByInterruptException
		at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
		at sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:391)
		at org.apache.lucene.util.IOUtils.fsync(IOUtils.java:396)
		... 10 more
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.apache.lucene.util.IOUtils.fsync(IOUtils.java:404)
	... 10 more
```

Comment in Netty code regarding the `Selector.select()` warning: http://netty.io/3.9/xref/org/jboss/netty/channel/socket/nio/AbstractNioSelector.html
```
// Thread was interrupted but NioSelector was not shutdown.
239                                 // As this is most likely a bug in the handler of the user or it's client
240                                 // library we will log it.
241                                 //
242                                 // See https://github.com/netty/netty/issues/2426
```


Interesting threads in stack dump:

```
	elasticsearch[node_s2][snapshot][T#1]" ID=7457 RUNNABLE
	at sun.nio.ch.FileDispatcherImpl.force0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.force(FileDispatcherImpl.java:76)
	at sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:387)
	at org.apache.lucene.util.IOUtils.fsync(IOUtils.java:396)
	at org.elasticsearch.common.blobstore.fs.FsBlobContainer.writeBlob(FsBlobContainer.java:99)
	at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.snapshotFile(BlobStoreIndexShardRepository.java:659)
	at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.snapshot(BlobStoreIndexShardRepository.java:604)
	at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository.snapshot(BlobStoreIndexShardRepository.java:191)
	at org.elasticsearch.snapshots.SnapshotShardsService.snapshot(SnapshotShardsService.java:340)
	at org.elasticsearch.snapshots.SnapshotShardsService.access$200(SnapshotShardsService.java:76)
	at org.elasticsearch.snapshots.SnapshotShardsService$1.doRun(SnapshotShardsService.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Locked synchronizers:
	- java.util.concurrent.ThreadPoolExecutor$Worker@3d035ed2

"elasticsearch[node_s1][snapshot][T#1]" ID=7456 RUNNABLE
	at sun.nio.ch.FileDispatcherImpl.force0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.force(FileDispatcherImpl.java:76)
	at sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:387)
	at org.apache.lucene.util.IOUtils.fsync(IOUtils.java:396)
	at org.elasticsearch.common.blobstore.fs.FsBlobContainer.writeBlob(FsBlobContainer.java:98)
	at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.snapshotFile(BlobStoreIndexShardRepository.java:659)
	at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.snapshot(BlobStoreIndexShardRepository.java:604)
	at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository.snapshot(BlobStoreIndexShardRepository.java:191)
	at org.elasticsearch.snapshots.SnapshotShardsService.snapshot(SnapshotShardsService.java:340)
	at org.elasticsearch.snapshots.SnapshotShardsService.access$200(SnapshotShardsService.java:76)
	at org.elasticsearch.snapshots.SnapshotShardsService$1.doRun(SnapshotShardsService.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Locked synchronizers:
	- java.util.concurrent.ThreadPoolExecutor$Worker@4a066cec
```

**Comment by ywelsch** [comment]
@s1monw Looking at org.apache.lucene.util.IOUtils.fsync, I'm wondering though why the force operation is retried in case of a ClosedChannelException (of which the thrown ClosedByInterruptException is one).

**Comment by ywelsch** [comment]
might be related to this:

https://issues.apache.org/jira/browse/LUCENE-6902

**Comment by clintongormley** [comment]
@ywelsch can this be closed?

**Comment by ywelsch** [comment]
With the fix in Lucene an no further reoccurrences I'm aware of, I'm closing this.
