### ISSUE TITLE
Mapping `properties._id` causes conflicts and shard failures

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#15057]
Recreation on 2.1.0:

    PUT t
    {
      "mappings": {
        "one": {
          "properties": {
            "_id": {
              "type": "string"
            }
          }
        },
        "two": {}
      }
    }

This returns OK, but in the logs:

    [2015-11-27 10:36:51,848][WARN ][indices.cluster          ] [Primevil] [t] failed to add mapping [one], source [{"one":{"properties":{"_id":{"type":"string"}}}}]
    java.lang.IllegalArgumentException: Mapper for [_id] conflicts with existing mapping in other types:
    [mapper [_id] cannot be changed from type [_id] to [string]]
      at org.elasticsearch.index.mapper.FieldTypeLookup.checkCompatibility(FieldTypeLookup.java:117)
      at org.elasticsearch.index.mapper.MapperService.checkNewMappersCompatibility(MapperService.java:364)
      at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:315)
      at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:261)
      at org.elasticsearch.indices.cluster.IndicesClusterStateService.processMapping(IndicesClusterStateService.java:418)
      at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyMappings(IndicesClusterStateService.java:372)
      at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:177)
      at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:494)
      at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
      at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
    [2015-11-27 10:36:51,849][WARN ][indices.cluster          ] [Primevil] [[t][4]] marking and sending shard failed due to [master [{Primevil}{FZZ2xKQATOSVT6qMODFe2w}{127.0.0.1}{127.0.0.1:9300}] marked shard as started, but shard has not been created, mark shard as failed]
    [2015-11-27 10:36:51,849][WARN ][cluster.action.shard     ] [Primevil] [t][4] received shard failed for [t][4], node[FZZ2xKQATOSVT6qMODFe2w], [P], v[2], s[STARTED], a[id=SfSzHTRlSAawEvHtC7cMLg], indexUUID [bcTOLPxjTM2cB95wPE0sJQ], message [master [{Primevil}{FZZ2xKQATOSVT6qMODFe2w}{127.0.0.1}{127.0.0.1:9300}] marked shard as started, but shard has not been created, mark shard as failed], failure [Unknown]

**Comment by Zyg0te** [comment]
Im experiencing this issue. Is there a known workaround? How do I prevent data loss?

**Comment by clintongormley** [comment]
We're working on a bug fix.  There isn't a workaround that I'm aware of.  You will need to reindex this data to a new index.

**Comment by jpountz** [comment]
Delaying to 2.2.0: I'm on the fence to put such a change in a bugfix release.

**Comment by krisb78** [comment]
Shouldn't dynamic templates recognise these meta-properties (i.e., "_all", "_id", "_parent", "_routing", "_timestamp", "_ttl") and handle them properly?

I have the following template:

```
{
  "shop_order_v1" : {
    "order" : 0,
    "template" : "shop_order_v1*",
    "settings" : { },
    "mappings" : {
      "shop_order" : {
        "dynamic_templates" : [ {
          "store_generic" : {
            "mapping" : {
              "index" : "not_analyzed",
              "store" : true,
              "doc_values" : true
            },
            "match" : "*"
          }
        } ],
        "properties" : {
          "timestamp" : {
            "store" : true,
            "format" : "yyyy-MM-dd HH:mm:ss",
            "doc_values" : true,
            "type" : "date"
          },
          "started" : {
            "store" : true,
            "format" : "yyyy-MM-dd HH:mm:ss",
            "doc_values" : true,
            "type" : "date"
          },
          "geo_point" : {
            "doc_values" : true,
            "type" : "geo_point"
          }
        }
      }
    },
    "aliases" : {
      "shop_order_v1" : { }
    }
  }
}
```

I'm hitting this error when I'm trying to index a document that contains the "_id" property, e.g.

```
{
  "_id": "foo"
}
```

At the moment I'm working around this by removing the "_id" property from the docs before indexing (bulk), but this used to work ok on 1.7.4.

**Comment by clintongormley** [comment]
@krisb78 the ability to embed metafields in the source of a document has been removed.  It required double parsing of the document (once on the coordinating node and once on the data node)

**Comment by krisb78** [comment]
Thought so - thanks, I'll amend my code.

**Comment by vladan-me** [comment]
This is a breaking change that is not mentioned in your documentation...
