### ISSUE TITLE
Error when upgrading the server to 2.1 without upgrading java client at the same time

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#15071]
Here is what I did:

I install a fresh new version of elasticsearch 2.1.0. And starts it (note that I'm running it with `license` and `marvel-agent`).

```
$ bin/elasticsearch
[2015-11-27 20:59:15,909][INFO ][node                     ] [Ajak] version[2.1.0], pid[74419], build[72cd1f1/2015-11-18T22:40:03Z]
[2015-11-27 20:59:15,910][INFO ][node                     ] [Ajak] initializing ...
[2015-11-27 20:59:16,341][INFO ][plugins                  ] [Ajak] loaded [license, marvel-agent], sites []
[2015-11-27 20:59:16,387][INFO ][env                      ] [Ajak] using [1] data paths, mounts [[/ (/dev/disk1)]], net usable_space [36.6gb], net total_space [464.7gb], spins? [unknown], types [hfs]
[2015-11-27 20:59:19,519][INFO ][node                     ] [Ajak] initialized
[2015-11-27 20:59:19,519][INFO ][node                     ] [Ajak] starting ...
[2015-11-27 20:59:19,657][INFO ][transport                ] [Ajak] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
[2015-11-27 20:59:19,669][INFO ][discovery                ] [Ajak] workshop/K8cI0q5zTU-J-iuxKIBcIg
[2015-11-27 20:59:22,697][INFO ][cluster.service          ] [Ajak] new_master {Ajak}{K8cI0q5zTU-J-iuxKIBcIg}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2015-11-27 20:59:22,712][INFO ][http                     ] [Ajak] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}
[2015-11-27 20:59:22,713][INFO ][node                     ] [Ajak] started
```

I have a Java application using elasticsearch 2.0.0 jar as a client.

```java
Client client = TransportClient.builder().build()
        .addTransportAddress(new InetSocketTransportAddress(new InetSocketAddress("127.0.0.1", 9300)));

if (!client.admin().indices().prepareExists("person").execute().actionGet().isExists()) {
    String indexSettings = readFileInClasspath("/settings.json");
    client.admin().indices().prepareCreate("person").setSettings(indexSettings).execute().actionGet();
}
```

When running this, I get on the client side:

```
nov. 27, 2015 9:03:03 PM org.elasticsearch.plugins.PluginsService <init>
INFOS: [James Sanders] loaded [], sites []
nov. 27, 2015 9:03:03 PM org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler doSample
INFOS: [James Sanders] failed to get node info for {#transport#-1}{127.0.0.1}{127.0.0.1:9300}, disconnecting...
RemoteTransportException[[Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.liveness.LivenessResponse]]]; nested: TransportSerializationException[Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.liveness.LivenessResponse]]; nested: ExceptionInInitializerError; nested: IllegalArgumentException[An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene50' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [es090, completion090, XBloomFilter]];
Caused by: TransportSerializationException[Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.liveness.LivenessResponse]]; nested: ExceptionInInitializerError; nested: IllegalArgumentException[An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene50' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [es090, completion090, XBloomFilter]];
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:179)
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:138)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
        at org.elasticsearch.Version.fromId(Version.java:500)
        at org.elasticsearch.Version.readVersion(Version.java:276)
        at org.elasticsearch.cluster.node.DiscoveryNode.readFrom(DiscoveryNode.java:326)
        at org.elasticsearch.cluster.node.DiscoveryNode.readNode(DiscoveryNode.java:309)
        at org.elasticsearch.action.admin.cluster.node.liveness.LivenessResponse.readFrom(LivenessResponse.java:52)
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:177)
        ... 23 more
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene50' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [es090, completion090, XBloomFilter]
        at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:109)
        at org.apache.lucene.codecs.PostingsFormat.forName(PostingsFormat.java:112)
        at org.elasticsearch.common.lucene.Lucene.<clinit>(Lucene.java:103)
        ... 29 more

nov. 27, 2015 9:03:03 PM org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler doSample
INFOS: [James Sanders] failed to get node info for {#transport#-1}{127.0.0.1}{127.0.0.1:9300}, disconnecting...
RemoteTransportException[[Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.liveness.LivenessResponse]]]; nested: TransportSerializationException[Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.liveness.LivenessResponse]]; nested: NoClassDefFoundError[Could not initialize class org.elasticsearch.common.lucene.Lucene];
Caused by: TransportSerializationException[Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.liveness.LivenessResponse]]; nested: NoClassDefFoundError[Could not initialize class org.elasticsearch.common.lucene.Lucene];
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:179)
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:138)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.common.lucene.Lucene
        at org.elasticsearch.Version.fromId(Version.java:500)
        at org.elasticsearch.Version.readVersion(Version.java:276)
        at org.elasticsearch.cluster.node.DiscoveryNode.readFrom(DiscoveryNode.java:326)
        at org.elasticsearch.cluster.node.DiscoveryNode.readNode(DiscoveryNode.java:309)
        at org.elasticsearch.action.admin.cluster.node.liveness.LivenessResponse.readFrom(LivenessResponse.java:52)
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:177)
        ... 23 more

Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: []]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:280)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:197)
        at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:272)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:347)
        at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1177)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59)
        at org.elasticsearch.demo.workshop.injector.runner.Generate.main(Generate.java:103)
```

If I update the client to 2.1.0, the exact same code now works perfectly.

**Comment by dadoonet** [comment]
Also tested without license and marvel. Same issue.

```
[2015-11-28 14:23:24,643][INFO ][node                     ] [Native] version[2.1.0], pid[11128], build[72cd1f1/2015-11-18T22:40:03Z]
[2015-11-28 14:23:24,644][INFO ][node                     ] [Native] initializing ...
[2015-11-28 14:23:24,721][INFO ][plugins                  ] [Native] loaded [], sites []
```

**Comment by rmuir** [comment]
Looks like you don't have lucene jars configured correctly on the client side:

```
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene50' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [es090, completion090, XBloomFilter]
        at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:109)
        at org.apache.lucene.codecs.PostingsFormat.forName(PostingsFormat.java:112)
        at org.elasticsearch.common.lucene.Lucene.<clinit>(Lucene.java:103)
        ... 29 more
```

This happens easily with improper shading. Lucene uses SPI and it is important to configure things to merge META-INF/ services.

**Comment by dadoonet** [comment]
Here is what I'm doing.

Client side `pom.xml`:

```xml
    <dependencies>
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>2.0.0</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>2.5.4</version>
                <configuration>
                    <finalName>injector-${elasticsearch.version}</finalName>
                    <appendAssemblyId>false</appendAssemblyId>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive>
                        <manifest>
                            <mainClass>org.elasticsearch.demo.workshop.injector.runner.Generate</mainClass>
                        </manifest>
                    </archive>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

So is this happening because I'm building a jar with all deps? `jar-with-dependencies`
Is it what you called "shading"? Note that I'm not moving any class to another package.

**Comment by rmuir** [comment]
Right, shading, uber-jar, whatever it is. Its not properly merging META-INF/ entries, creating a broken lucene installation. Hence lucene can'f find services that should be there.

**Comment by dadoonet** [comment]
Ok thanks Robert. I guess we can close it then.

**Comment by rmuir** [comment]
AFAIK, the shade plugin is the best way to create an uber jar (even if you arent relocating packages). It has the ability to properly merge META-INF/services across the different jars into a combined one that will work, but you may have to pass some parameters to do that.

**Comment by rmuir** [comment]
See https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ServicesResourceTransformer

It is really necessary if you want to shade/uberjar lucene at all.

**Comment by dadoonet** [comment]
Thank you Robert. I think I need to add that to the Java documentation.
Reopening as "doc"

**Comment by dadoonet** [comment]
I ran some more tests this morning. Actually maven assembly plugin sucks when you have to deal with `META-INF/services`.

So instead of calling `maven-assembly-plugin`, it's better to use `maven-shade-plugin` with the option @rmuir gave.

At the end, this is working well:

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.4.1</version>
                <executions>
                    <!-- Run shade goal on package phase -->
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <finalName>injector-${elasticsearch.version}</finalName>
                            <transformers>
                                <!-- add Main-Class to manifest file -->
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>org.elasticsearch.demo.workshop.injector.runner.Generate</mainClass>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by kdubezerra** [comment]
The solution you guys posted is for maven-based projects. Do you know an equivalent solution for gradle projects? FYI, the problem I'm facing is more similar to https://github.com/elastic/elasticsearch/issues/18908, but perhaps this one here has the same solution.

**Comment by rjernst** [comment]
@kdubezerra It looks like the [fat jar plugin](https://github.com/musketyr/gradle-fatjar-plugin) is able to handle properly merging `META-INF/services` as was described in this issue.

**Comment by aiionx** [comment]
@dadoonet 
Thanks, that conf works!

**Comment by abhiroyg** [comment]
Hi,

Do you guys know any working solution for OSGI Felix's maven-bundle-plugin ?
