### ISSUE TITLE
SearchFieldsTests.testLoadMetadata fails

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#15145]
SearchFieldsTests.testLoadMetadata fails in current master with the following error. It reproduced only once for me, tried running the test multiple times with no luck. I am thinking it may be related to recent mapping changes, also wondering if #15142 might fix this issue. Seems an actual problem though rather than a test bug. @jpountz @jasontedor can either of you please have a look and assign this?

```
java.lang.AssertionError: 
Expected: an empty iterable
     but: [<java.lang.IllegalArgumentException: can't add a _parent field that points to an already existing type>]
	at __randomizedtesting.SeedInfo.seed([2723CD59178F56E2:30964EA8729EAE09]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1433)
	at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1353)
	at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1337)
	at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1313)
	at org.elasticsearch.messy.tests.SearchFieldsTests.testLoadMetadata(SearchFieldsTests.java:663)
```

http://build-us-00.elastic.co/job/es_g1gc_master_metal/25993/testReport/junit/org.elasticsearch.messy.tests/SearchFieldsTests/testLoadMetadata/

**Comment by javanna** [comment]
Same failure, but different test (ChildQuerySearchIT.testScoreForParentChildQueriesWithFunctionScore): http://build-us-00.elastic.co/job/es_core_master_window-2012/2083/testReport/junit/org.elasticsearch.search.child/ChildQuerySearchIT/testScoreForParentChildQueriesWithFunctionScore/

**Comment by javanna** [comment]
And another one (ChildQuerySearchIT.testCachingBugWithFqueryFilter): http://build-us-00.elastic.co/job/es_core_master_suse/2614/testReport/junit/org.elasticsearch.search.child/ChildQuerySearchIT/testCachingBugWithFqueryFilter/

**Comment by jpountz** [comment]
I'm in the process of doing significant refactorings of how mappings are validated so I'll take this one.

**Comment by jpountz** [comment]
These failures have not reproduced recently.
