### ISSUE TITLE
v2.1 failed to delete temp file Exception when start node 

### ISSUE THREAD

**Issue by davidcai19840412** [elastic/elasticsearch#15176]
--------------------
Exception
--------------------
[WARN ][index.translog           ] [es_sqmall_dev_1] [index][1] failed to delete temp file /home/sauna.test/server/elasticsearch/data/es_sqmall_dev/nodes/0/indices/index/1/translog/translog-2613417349747513949.tlog
java.nio.file.NoSuchFileException: /home/sauna.test/server/elasticsearch/data/es_sqmall_dev/nodes/0/indices/index/1/translog/translog-2613417349747513949.tlog
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1079)
	at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:324)
	at org.elasticsearch.index.translog.Translog.<init>(Translog.java:166)
	at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:209)
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:152)
	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1408)
	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1403)
	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:906)
	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:883)
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:245)
	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by dadoonet** [comment]
Fixed in https://github.com/elastic/elasticsearch/pull/14872
