### ISSUE TITLE
UnicastBackwardsCompatibilityIT fails frequently on 2.1 Windows

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#15182]
This test fails quiet frequently over the last few days on 2.1 branch, going through the failure mails it seems its only on Windows 2012 machine. Last seen was

http://build-us-00.elastic.co/job/es_core_21_window-2012/129/

and the top of the stacktrace reads like
```
java.lang.IllegalStateException: Failed to start elasticserch. Responses: [couldn't find elasticsearch bound to localhost:29301!]
	at __randomizedtesting.SeedInfo.seed([24181440F4C4423C]:0)
	at org.elasticsearch.test.ExternalNodeServiceClient.interact(ExternalNodeServiceClient.java:85)
	at org.elasticsearch.test.ExternalNodeServiceClient.stop(ExternalNodeServiceClient.java:60)
	at org.elasticsearch.test.ExternalNode.stop(ExternalNode.java:231)
	at org.elasticsearch.test.ExternalNode.close(ExternalNode.java:257)
	at org.apache.lucene.util.IOUtils.close(IOUtils.java:97)
	at org.apache.lucene.util.IOUtils.close(IOUtils.java:84)
	at org.elasticsearch.test.CompositeTestCluster.close(CompositeTestCluster.java:266)
	at org.apache.lucene.util.IOUtils.close(IOUtils.java:97)
	at org.elasticsearch.test.ESIntegTestCase.clearClusters(ESIntegTestCase.java:588)
	at org.elasticsearch.test.ESIntegTestCase.afterClass(ESIntegTestCase.java:1978)
```

Going throught the output it is not clear to me if this is a follow up error cause by something else.

**Comment by nik9000** [comment]
If I had to guess blindly I'd guess that I left a bug in ExternalNode that let it try to shut down the node twice. Why it only comes up on windows is a mystery to me though.

**Comment by clintongormley** [comment]
Old test failure. Closing
