### ISSUE TITLE
Date Format mapping not working in 2.1

### ISSUE THREAD

**Issue by SMUnlimited** [elastic/elasticsearch#15244]
Using the latest version of Elasticsearch 2.1.0 on Windows 7

The date format mapping appears to be ignored.

Set a format in mappings

```JSON
curl -XPUT http://localhost:9200/myindex1 '{
  "mappings": {
    "document": {
      "properties": {
        "date_field": {
          "type": "date",
          "format": "yyyy/MM/dd"
        }
      }
    }
  }
}
```

Ingest a document

``` JSON
curl -XPUT http://localhost:9200/myindex1/mydoc/1 '{
    "date_field": "2013/12/23"
}'

```

Throws following exception
```
15:01:30,123 INFO  [elasticsearch[platform-webapp-ISVGREPC0000738][index][T#2]:rest.suppressed]: /com.detica.elasticsearch.platform.module.bulk.bulkidsretrievecomponentit1/mydoc/1 Params: {id=1, index=com.detica.elasticsearch.platform.module.bulk.bulkidsretrievecomponentit1, type=mydoc}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [date_field]
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:339) ~[elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:314) ~[elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.index.mapper.DocumentParser.parseAndMergeUpdate(DocumentParser.java:762) ~[elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.index.mapper.DocumentParser.parseDynamicValue(DocumentParser.java:676) ~[elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:447) ~[elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:267) ~[elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.index.mapper.DocumentParser.innerParseDocument(DocumentParser.java:127) ~[elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:79) ~[elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:318) ~[elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:551) ~[elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:542) ~[elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.prepareIndexOperationOnPrimary(TransportReplicationAction.java:1049) ~[elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.executeIndexRequestOnPrimary(TransportReplicationAction.java:1060) ~[elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:170) ~[elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.performOnPrimary(TransportReplicationAction.java:579) [elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase$1.doRun(TransportReplicationAction.java:452) [elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-2.1.0.jar:2.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.IllegalArgumentException: Invalid format: "2013/12/23" is malformed at "/12/23"
	at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187) ~[joda-time-2.8.2.jar:2.8.2]
	at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:780) ~[joda-time-2.8.2.jar:2.8.2]
	at org.elasticsearch.index.mapper.core.DateFieldMapper$DateFieldType.parseStringValue(DateFieldMapper.java:360) ~[elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.index.mapper.core.DateFieldMapper.innerParseCreateField(DateFieldMapper.java:526) ~[elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:213) ~[elasticsearch-2.1.0.jar:2.1.0]
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:331) ~[elasticsearch-2.1.0.jar:2.1.0]
	... 19 more
```

**Yml settings file**
Single es node

cluster.name: myTestCluster
index.number_of_replicas: 0
index.number_of_shards: 1
http.enabled: true
http.cors.enabled: true
http.cors.allow-origin: "*"

**Funky Scary Strange Part**
I ended up debugging line by line to see if I could catch what the format was being set to, or overridden to cause this issue. This was in:
DateFieldMapper.dateTimeFormatter()
DateFieldMapper.setDateTimeFormatter()

But the document index action worked this time once it went through the DocumentParser. But the weird thing is the mapping had magically changed by itself from

"yyyy/MM/dd" to "yyyy/MM/dd HH:mm:ss||yyyy/MM/dd||epoch_millis"

I.e i did a "_mapping" GET request to confirm and it was no longer yyyy/MM/dd. I havn't a clue how that is even possible. This never happens when it is not working but whatever it did fixed being able to add documents at that moment.

Note if I manually set the date format myself to "yyyy/MM/dd HH:mm:ss||yyyy/MM/dd||epoch_millis" in a new index I still cannot add a document. 

In any case when the add document is failing the date format appears to be using the 'default' rather than my custom format.

**Comment by SMUnlimited** [comment]
Never mind helps to have the same document type in your mapping and ingest.

The funky scary strange part is still odd though.

**Comment by clintongormley** [comment]
thanks @SMUnlimited
