### ISSUE TITLE
NumberFormatException with ip type

### ISSUE THREAD

**Issue by timmgrant** [elastic/elasticsearch#15288]
Hi,

I am using:

 elasticsearch: 2.0.0
 logstash: 2.0.0

When using the 'ip' type in elasticsearch I get a NumberFormatException.

template is:
```javascript
{
	"template" : "frameaccess-*",
	"aliases" : { },
	"mappings" : {
		"frameaccess" : {
			"properties" : {
				"@timestamp" : {"type" : "date","format" : "dateOptionalTime"},
				"@version" : {"type" : "string", "index" : "not_analyzed"},
				"host" : {"type" : "string", "index" : "not_analyzed"},
				"message" : {"type" : "string"},
				"clientip" : {"type" : "ip", "store": "true", "index" : "not_analyzed"},
				"username" : {"type" : "string", "index" : "not_analyzed"},
				"method" : {"type" : "string", "index" : "not_analyzed"},
				"request" : {"type" : "string"},
				"http_version" : {"type" : "float"},
				"http_status_code" : {"type" : "integer"},
				"size" : {"type" : "long"},
                                "responsetime" : {"type" : "double"},
				"source" : {"type" : "string", "index" : "not_analyzed"}
			}
		}
	},
	"settings" : {
		"index" : {
			"number_of_shards" : "3",
			"number_of_replicas" : "1"
		}
	}
}
```

logstash config is:

```javascript
input { 
   stdin { codec => plain }
}
output { 
   elasticsearch {
      hosts => "elasticsearchurl.company.com:80"
      index => "frameaccess-%{+YYYY.MM.dd}"
   }
}
filter {
  grok {
    match => [
      "message",
      '(-|%{IPORHOST:clientip}) \- (-|%{HTTPDUSER:username}) \[%{HTTPDATE:timestamp}\] "%{WORD:method} %{URIPATHPARAM:request} HTTP/%{NUMBER:http_version}" (-|%{INT:http_status_code}) (-|%{INT:size}) (-|%{NUMBER:responsetime})'
    ]
  }
  
  date {
    locale => "en"
    timezone => "Europe/London"
    match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
  }
  
  mutate {
    add_field => { "source" => "appname" }
    replace => { "host" => "mynodehostname.company.com" }
    remove_field => [ "timestamp" ]
  }
}
```
Test input is:

`192.168.0.1 - fbloggs [29/Sep/2015:00:00:00 +0100] "POST /ctx/minimumEntry.jsp HTTP/1.1" 200 48005 0.285`

Result is:

```
io/console not supported; tty will not be manipulated
Default settings used: Filter workers: 4
Logstash startup completed
?[33mFailed action.  {:status=>400, :action=>["index", {:_id=>nil, :_index=>"frameaccess-2015.09.28", :_type=>"logs", :_routing=>nil}, #<LogStash::Event:0x48d26c4b @metadata={"retry_count"=>0}, @accessors=#<LogStash::Util::Accessors:0x7ae71f79 @store={"message"=>"192.168.0.1 - fbloggs [29/Sep/2015:00:00:00 +0100] \"POST /ctx/minimumEntry.jsp HTTP/1.1\" 200 48005 0.285\r", "@version"=>"1", "@timestamp"=>"2015-09-28T23:00:00.000Z", "host"=>"mynodehostname.company.com", "clientip"=>"192.168.0.1", "username"=>"fbloggs", "method"=>"POST", "request"=>"/ctx/minimumEntry.jsp", "http_version"=>"1.1", "http_status_code"=>"200", "size"=>"48005", "responsetime"=>"0.285", "source"=>"appname"}, @lut={"host"=>[{"message"=>"192.168.0.1 - fbloggs [29/Sep/2015:00:00:00 +0100] \"POST /ctx/minimumEntry.jsp HTTP/1.1\" 200 48005 0.285\r", "@version"=>"1", "@timestamp"=>"2015-09-28T23:00:00.000Z", "host"=>"mynodehostname.company.com", "clientip"=>"192.168.0.1", "username"=>"fbloggs", "method"=>"POST", "request"=>"/ctx/minimumEntry.jsp", "http_version"=>"1.1", "http_status_code"=>"200", "size"=>"48005", "responsetime"=>"0.285", "source"=>"appname"}, "host"], "message"=>[{"message"=>"192.168.0.1 - fbloggs [29/Sep/2015:00:00:00 +0100] \"POST /ctx/minimumEntry.jsp HTTP/1.1\" 200 48005 0.285\r", "@version"=>"1", "@timestamp"=>"2015-09-28T23:00:00.000Z","host"=>"mynodehostname.company.com", "clientip"=>"192.168.0.1", "username"=>"fbloggs", "method"=>"POST", "request"=>"/ctx/minimumEntry.jsp", "http_version"=>"1.1", "http_status_code"=>"200", "size"=>"48005", "responsetime"=>"0.285", "source"=>"appname"}, "message"], "clientip"=>[{"message"=>"192.168.0.1 - fbloggs [29/Sep/2015:00:00:00 +0100] \"POST /ctx/minimumEntry.jsp HTTP/1.1\" 200 48005 0.285\r", "@version"=>"1", "@timestamp"=>"2015-09-28T23:00:00.000Z", "host"=>"mynodehostname.company.com", "clientip"=>"192.168.0.1", "username"=>"fbloggs", "method"=>"POST", "request"=>"/ctx/minimumEntry.jsp", "http_version"=>"1.1", "http_status_code"=>"200", "size"=>"48005", "responsetime"=>"0.285", "source"=>"appname"}, "clientip"], "username"=>[{"message"=>"192.168.0.1 - fbloggs [29/Sep/2015:00:00:00 +0100] \"POST /ctx/minimumEntry.jsp HTTP/1.1\" 200 48005 0.285\r","@version"=>"1", "@timestamp"=>"2015-09-28T23:00:00.000Z", "host"=>"mynodehostname.company.com", "clientip"=>"192.168.0.1", "username"=>"fbloggs", "method"=>"POST", "request"=>"/ctx/minimumEntry.jsp", "http_version"=>"1.1", "http_status_code"=>"200", "size"=>"48005", "responsetime"=>"0.285", "source"=>"appname"}, "username"], "timestamp"=>[{"message"=>"192.168.0.1 - fbloggs [29/Sep/2015:00:00:00 +0100] \"POST /ctx/minimumEntry.jsp HTTP/1.1\" 200 48005 0.285\r", "@version"=>"1", "@timestamp"=>"2015-09-28T23:00:00.000Z", "host"=>"mynodehostname.company.com", "clientip"=>"192.168.0.1", "username"=>"fbloggs", "method"=>"POST", "request"=>"/ctx/minimumEntry.jsp", "http_version"=>"1.1", "http_status_code"=>"200", "size"=>"48005", "responsetime"=>"0.285", "source"=>"appname"}, "timestamp"], "method"=>[{"message"=>"192.168.0.1 - fbloggs [29/Sep/2015:00:00:00 +0100] \"POST /ctx/minimumEntry.jsp HTTP/1.1\" 200 48005 0.285\r", "@version"=>"1", "@timestamp"=>"2015-09-28T23:00:00.000Z", "host"=>"mynodehostname.company.com", "clientip"=>"192.168.0.1", "username"=>"fbloggs", "method"=>"POST", "request"=>"/ctx/minimumEntry.jsp", "http_version"=>"1.1", "http_status_code"=>"200", "size"=>"48005", "responsetime"=>"0.285", "source"=>"appname"}, "method"], "request"=>[{"message"=>"192.168.0.1 - fbloggs [29/Sep/2015:00:00:00 +0100] \"POST /ctx/minimumEntry.jsp HTTP/1.1\" 200 48005 0.285\r", "@version"=>"1", "@timestamp"=>"2015-09-28T23:00:00.000Z", "host"=>"mynodehostname.company.com", "clientip"=>"192.168.0.1", "username"=>"fbloggs", "method"=>"POST", "request"=>"/ctx/minimumEntry.jsp", "http_version"=>"1.1", "http_status_code"=>"200", "size"=>"48005", "responsetime"=>"0.285", "source"=>"appname"}, "request"], "http_version"=>[{"message"=>"192.168.0.1 - fbloggs [29/Sep/2015:00:00:00 +0100] \"POST /ctx/minimumEntry.jsp HTTP/1.1\" 200 48005 0.285\r","@version"=>"1", "@timestamp"=>"2015-09-28T23:00:00.000Z", "host"=>"mynodehostname.company.com", "clientip"=>"192.168.0.1", "username"=>"fbloggs", "method"=>"POST", "request"=>"/ctx/minimumEntry.jsp", "http_version"=>"1.1", "http_status_code"=>"200", "size"=>"48005", "responsetime"=>"0.285", "source"=>"appname"}, "http_version"], "http_status_code"=>[{"message"=>"192.168.0.1 - fbloggs [29/Sep/2015:00:00:00 +0100] \"POST /ctx/minimumEntry.jsp HTTP/1.1\" 200 48005 0.285\r", "@version"=>"1", "@timestamp"=>"2015-09-28T23:00:00.000Z", "host"=>"mynodehostname.company.com", "clientip"=>"192.168.0.1", "username"=>"fbloggs", "method"=>"POST", "request"=>"/ctx/minimumEntry.jsp", "http_version"=>"1.1", "http_status_code"=>"200", "size"=>"48005", "responsetime"=>"0.285", "source"=>"appname"}, "http_status_code"], "size"=>[{"message"=>"192.168.0.1 - fbloggs [29/Sep/2015:00:00:00 +0100] \"POST /ctx/minimumEntry.jsp HTTP/1.1\" 200 48005 0.285\r", "@version"=>"1", "@timestamp"=>"2015-09-28T23:00:00.000Z", "host"=>"mynodehostname.company.com", "clientip"=>"192.168.0.1", "username"=>"fbloggs", "method"=>"POST", "request"=>"/ctx/minimumEntry.jsp", "http_version"=>"1.1", "http_status_code"=>"200", "size"=>"48005", "responsetime"=>"0.285", "source"=>"appname"}, "size"], "responsetime"=>[{"message"=>"192.168.0.1 - fbloggs [29/Sep/2015:00:00:00 +0100] \"POST /ctx/minimumEntry.jsp HTTP/1.1\" 200 48005 0.285\r", "@version"=>"1", "@timestamp"=>"2015-09-28T23:00:00.000Z", "host"=>"mynodehostname.company.com", "clientip"=>"192.168.0.1", "username"=>"fbloggs", "method"=>"POST", "request"=>"/ctx/minimumEntry.jsp", "http_version"=>"1.1", "http_status_code"=>"200", "size"=>"48005", "responsetime"=>"0.285", "source"=>"appname"}, "responsetime"], "@timestamp"=>[{"message"=>"192.168.0.1 - fbloggs [29/Sep/2015:00:00:00 +0100] \"POST /ctx/minimumEntry.jsp HTTP/1.1\" 200 48005 0.285\r", "@version"=>"1", "@timestamp"=>"2015-09-28T23:00:00.000Z", "host"=>"mynodehostname.company.com", "clientip"=>"192.168.0.1", "username"=>"fbloggs", "method"=>"POST", "request"=>"/ctx/minimumEntry.jsp", "http_version"=>"1.1", "http_status_code"=>"200", "size"=>"48005", "responsetime"=>"0.285", "source"=>"appname"}, "@timestamp"], "source"=>[{"message"=>"192.168.0.1 - fbloggs [29/Sep/2015:00:00:00 +0100] \"POST /ctx/minimumEntry.jsp HTTP/1.1\" 200 48005 0.285\r", "@version"=>"1", "@timestamp"=>"2015-09-28T23:00:00.000Z", "host"=>"mynodehostname.company.com", "clientip"=>"192.168.0.1", "username"=>"fbloggs","method"=>"POST", "request"=>"/ctx/minimumEntry.jsp", "http_version"=>"1.1", "http_status_code"=>"200", "size"=>"48005", "responsetime"=>"0.285", "source"=>"appname"}, "source"], "type"=>[{"message"=>"192.168.0.1 - fbloggs [29/Sep/2015:00:00:00 +0100] \"POST /ctx/minimumEntry.jsp HTTP/1.1\" 200 48005 0.285\r", "@version"=>"1", "@timestamp"=>"2015-09-28T23:00:00.000Z", "host"=>"mynodehostname.company.com", "clientip"=>"192.168.0.1", "username"=>"fbloggs", "method"=>"POST", "request"=>"/ctx/minimumEntry.jsp", "http_version"=>"1.1", "http_status_code"=>"200", "size"=>"48005", "responsetime"=>"0.285", "source"=>"appname"}, "type"]}>, @data={"message"=>"192.168.0.1 - fbloggs [29/Sep/2015:00:00:00 +0100] \"POST /ctx/minimumEntry.jsp HTTP/1.1\" 200 48005 0.285\r", "@version"=>"1", "@timestamp"=>"2015-09-28T23:00:00.000Z", "host"=>"mynodehostname.company.com", "clientip"=>"192.168.0.1", "username"=>"fbloggs", "method"=>"POST", "request"=>"/ctx/minimumEntry.jsp", "http_version"=>"1.1", "http_status_code"=>"200", "size"=>"48005", "responsetime"=>"0.285", "source"=>"appname"}, @metadata_accessors=#<LogStash::Util::Accessors:0x124e57b @store={"retry_count"=>0}, @lut={}>, @cancelled=false>], :response=>{"create"=>{"_index"=>"frameaccess-2015.09.28", "_type"=>"logs", "_id"=>"AVF9g1sPPii72JEyi-z_", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [clientip]", "caused_by"=>{"type"=>"number_format_exception", "reason"=>"For input string: \"192.168.0.1\""}}}}, :level=>:warn}?[0m
Logstash shutdown completed
```

Log says:

```
[2015-12-07 16:58:23,968][DEBUG][action.bulk              ] [MACHINENAME] [frameaccess-2015.09.28][2] failed to execute bulk item (index) index {[frameaccess-2015.09.28][logs][AVF9YT5FPii72JEyi-z9], source[{"message":"192.168.0.1 - fbloggs [29/Sep/2015:00:00:00 +0100] \"POST /ctx/minimumEntry.jsp HTTP/1.1\" 200 48005 0.285\r","@version":"1","@timestamp":"2015-09-28T23:00:00.000Z","host":"mynodehostname.company.com","clientip":"192.168.0.1","username":"fbloggs","method":"POST","request":"/ctx/minimumEntry.jsp","http_version":"1.1","http_status_code":"200","size":"48005","responsetime":"0.285","source":"appname"}]}
MapperParsingException[failed to parse [clientip]]; nested: NumberFormatException[For input string: "192.168.0.1"];
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:339)
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:314)
	at org.elasticsearch.index.mapper.DocumentParser.parseAndMergeUpdate(DocumentParser.java:762)
	at org.elasticsearch.index.mapper.DocumentParser.parseDynamicValue(DocumentParser.java:676)
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:447)
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:267)
	at org.elasticsearch.index.mapper.DocumentParser.innerParseDocument(DocumentParser.java:128)
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:79)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:318)
	at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:503)
	at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:494)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.prepareIndexOperationOnPrimary(TransportReplicationAction.java:1052)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.executeIndexRequestOnPrimary(TransportReplicationAction.java:1060)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:338)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:131)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.performOnPrimary(TransportReplicationAction.java:579)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase$1.doRun(TransportReplicationAction.java:452)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "192.168.0.1"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.longValue(AbstractXContentParser.java:145)
	at org.elasticsearch.index.mapper.core.LongFieldMapper.innerParseCreateField(LongFieldMapper.java:276)
	at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:213)
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:331)
	... 20 more
```

**Comment by rjernst** [comment]
We can see from the stack trace the request is trying to dynamically update the mappings:
```at org.elasticsearch.index.mapper.DocumentParser.parseDynamicValue(DocumentParser.java:676)```

This means the template is not getting applied. The type in your mappings is "frameaccess", but logstash defaults to a type of "logs", and we see this in the request debugging info printed:
`[frameaccess-2015.09.28]`**`[logs]`**`[AVF9YT5FPii72JEyi-z9]`

I think you should be using logstash to manage your templates? If you have problems with that, please open an issue with logstash.
