### ISSUE TITLE
Creating a java client node throws "script file extension not supported [groovy]", but script works as expected

### ISSUE THREAD

**Issue by dimitris-prelert** [elastic/elasticsearch#15286]
I have two groovy files placed in the config/scripts directory of the elasticsearch home directory. Since upgrading to elasticsearch 2.1.0 (from 1.6.0), I have started seeing the following stacktrace upon launching my application:

`java.lang.IllegalArgumentException: script file extension not supported [groovy]
	at org.elasticsearch.script.ScriptService.getScriptEngineServiceForFileExt(ScriptService.java:221)
	at org.elasticsearch.script.ScriptService.access$1200(ScriptService.java:83)
	at org.elasticsearch.script.ScriptService$ScriptChangesListener.onFileInit(ScriptService.java:537)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.onFileCreated(FileWatcher.java:256)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.init(FileWatcher.java:166)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.createChild(FileWatcher.java:173)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.listChildren(FileWatcher.java:188)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.onDirectoryCreated(FileWatcher.java:299)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.init(FileWatcher.java:162)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.access$000(FileWatcher.java:75)
	at org.elasticsearch.watcher.FileWatcher.doInit(FileWatcher.java:65)
	at org.elasticsearch.watcher.AbstractResourceWatcher.init(AbstractResourceWatcher.java:36)
	at org.elasticsearch.watcher.ResourceWatcherService.add(ResourceWatcherService.java:133)
	at org.elasticsearch.watcher.ResourceWatcherService.add(ResourceWatcherService.java:126)
	at org.elasticsearch.script.ScriptService.<init>(ScriptService.java:192)`

It seems like there is no engine for groovy files. However, when I later perform an operation that uses the scripts, everything works with no problems at all. Seeing in the source code, I can see the "scriptEnginesByExt" map being populated before the FileWatcher gets initialised. So, I cannot see how the engine for groovy scripts could be being added later. 

Also note that this occurs when I am creating a Node client (configured with `.client(true)`). If I create a transport client instead, I do not get the stacktrace. Before upgrading, such a stacktrace was not present while still using a Node client.

I would be thankful for any ideas on why this is happening.

**Comment by rjernst** [comment]
Scripts do not run on client nodes, which explains why the system works fine even though you see the error. The transport client is just a client (it does not create a node, so no script service).

I would guess that you are missing groovy in your classpath, which would cause the 2.1 code to skip registering groovy as a script language. Most likely you were using a shaded jar in 1.6, which we no longer have in 2.x, meaning you must include dependencies yourself when using ES as a client.

**Comment by dimitris-prelert** [comment]
Thank you for the explanation!
