### ISSUE TITLE
Security: plugin-security.policy seem to be ignored

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#15307]
When creating a zip distribution and trying to start it, it fails due to a `java.security.AccessControlException`. It seems as if the `plugin-security.policy` are ignored. This is the log when starting up

```
[2015-12-08 10:50:31,291][INFO ][node                     ] [Polaris] version[3.0.0-SNAPSHOT], pid[20776], build[0809e4a/2015-12-08T09:16:54.109Z]
[2015-12-08 10:50:31,292][INFO ][node                     ] [Polaris] initializing ...
[2015-12-08 10:50:31,583][ERROR][bootstrap                ] Exception
ElasticsearchException[Failed to load plugin class [org.elasticsearch.script.expression.ExpressionPlugin]]; nested: ExceptionInInitializerError; nested: AccessControlException[access de
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:453)
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:402)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:114)
        at org.elasticsearch.node.Node.<init>(Node.java:150)
        at org.elasticsearch.node.Node.<init>(Node.java:131)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:179)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:293)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.lang.ExceptionInInitializerError
        at org.elasticsearch.script.expression.ExpressionPlugin$1.run(ExpressionPlugin.java:45)
        at org.elasticsearch.script.expression.ExpressionPlugin$1.run(ExpressionPlugin.java:41)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.elasticsearch.script.expression.ExpressionPlugin.<clinit>(ExpressionPlugin.java:41)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:445)
        ... 8 more
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getClassLoader")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.ClassLoader.checkClassLoaderPermission(ClassLoader.java:1525)
        at java.lang.Class.getClassLoader(Class.java:683)
        at org.apache.lucene.expressions.js.JavascriptCompiler.checkFunction(JavascriptCompiler.java:706)
        at org.apache.lucene.expressions.js.JavascriptCompiler.<clinit>(JavascriptCompiler.java:695)
        ... 17 more
```

P.S. Added a comment [in #15253](https://github.com/elastic/elasticsearch/pull/15253#issuecomment-162834286), but figured out it makes more sense to have an own issue

havent tested on 2.2

**Comment by rmuir** [comment]
works for me, works for jenkins

**Comment by spinscale** [comment]
found it: running the distribution from inside $TMPDIR does not seem to be supported... guess that's a feature?

**Comment by rmuir** [comment]
If you want to support it, then it must be tested in jenkins.

**Comment by rmuir** [comment]
For the record, the issue is unrelated to that permission, or any recent change in general: its because you are on a mac and your /tmp is symlinked.

I opened a PR, in case we want to fix the symlink issue: https://github.com/elastic/elasticsearch/pull/15311

Or not, I am equally happy with symlink = security exception.
