### ISSUE TITLE
Option to suppress DocumentAlreadyExistsException

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#15329]
Currently when op_type=create is used, we write the following exception at the INFO level to the ES log file for each document that is rejected.  This can potentially write a ton of entries to the logs, drowning other more important log entries.

```
[2015-12-08 23:01:08,790][INFO ][rest.suppressed          ] /test/type/1 Params: {id=1, index=test, op_type=create, type=type}
[test][[test][3]] DocumentAlreadyExistsException[[type][1]: document already exists]
	at org.elasticsearch.index.engine.InternalEngine.innerCreateNoLock(InternalEngine.java:411)
	at org.elasticsearch.index.engine.InternalEngine.innerCreate(InternalEngine.java:369)
	at org.elasticsearch.index.engine.InternalEngine.create(InternalEngine.java:341)
	at org.elasticsearch.index.shard.IndexShard.create(IndexShard.java:517)
	at org.elasticsearch.index.engine.Engine$Create.execute(Engine.java:789)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.executeIndexRequestOnPrimary(TransportReplicationAction.java:1073)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:170)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.performOnPrimary(TransportReplicationAction.java:579)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase$1.doRun(TransportReplicationAction.java:452)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Maybe we can provide an option to suppress these, or write them to the DEBUG level, etc..

**Comment by kimchy** [comment]
I tend to agree, seems like we throw back the failure to the user, this seems like a DEBUG logging

**Comment by bleskes** [comment]
This was introduced with #12991 where we stopped serializing complete stack traces to the user but rather  logging them on the server.  Personally I'm a bit conflicted between logging this as INFO or DEBUG in general. However, for document level exceptions like version conflicts and doc already exists, we typically log a trace message as it can be very verbose and also not an error per-se but rather normal API behavior. I think we should follow that standard here too.
