### ISSUE TITLE
box_type error.

### ISSUE THREAD

**Issue by HowookJeong** [elastic/elasticsearch#15327]
- Master node
- Hot node
- Warm node

The cluster have three nodes and I tried hot-warm architecture. (using es 2.1.0)
But I couldn't update box_type because i got a below exception.
I don't know why elasticsearch distinguish by a field name or create index.
So, I think it is bug.

[Run...]
$ curl -XPOST "http://localhost:9200/db/_settings" -d'
{
    "index.routing.allocation.require.box_type":"warm"
}'

[Exception...]
[2015-12-09 14:29:10,675][INFO ][rest.suppressed          ] /db/_settings Params: {index=db, type=_settings}
RemoteTransportException[[hot-node][127.0.0.1:9301][indices:data/write/index]]; nested: MapperParsingException[Field name [index.routing.allocation.require.box_type] cannot contain '.'];
Caused by: MapperParsingException[Field name [index.routing.allocation.require.box_type] cannot contain '.']
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:278)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:223)
	at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:139)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:210)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:191)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:387)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$2.execute(MetaDataMappingService.java:386)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:388)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745) 

[Run...]
$ curl -XPOST "http://localhost:9200/db" -d'
{
  "settings": {
    "index.routing.allocation.require.box_type":"warm"
  }
}'

[Exception...]
[2015-12-09 14:49:50,825][INFO ][rest.suppressed          ] /db Params: {index=db}
[db] IndexAlreadyExistsException[already exists]
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDataCreateIndexService.java:168)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validate(MetaDataCreateIndexService.java:520)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$200(MetaDataCreateIndexService.java:97)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:241)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:388)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ywelsch** [comment]
Use `PUT` instead of `POST` for the request (see https://www.elastic.co/guide/en/elasticsearch/reference/2.1/shard-allocation-filtering.html).

The error message is misleading in this case. We will need to look at what can be done about it.

**Comment by HowookJeong** [comment]
Thank you for your comment.

I succeeded it.

[Good]
$ curl -XPUT "http://localhost:9200/db/_settings" -d'
{
    "index.routing.allocation.require.box_type":"warm"
}'

[Bad]
$ curl -XPUT "http://localhost:9200/db" -d'
{
  "settings": {
    "index.routing.allocation.require.box_type":"warm"
  }
}'

- bad request error messages.
{
   "error": {
      "root_cause": [
         {
            "type": "index_already_exists_exception",
            "reason": "already exists",
            "index": "db"
         }
      ],
      "type": "index_already_exists_exception",
      "reason": "already exists",
      "index": "db"
   },
   "status": 400
}

Close this ticket.

Thanks.

**Comment by jasontedor** [comment]
> The error message is misleading in this case. We will need to look at what can be done about it.

@ywelsch See #15335.
