### ISSUE TITLE
Windows 7 Java 1.8 Elastic Search 2.1 Unsupported major.minor version 51.0 Error

### ISSUE THREAD

**Issue by CMcMe** [elastic/elasticsearch#15339]
Hi

My apologies if I am doing something dumb but I have been trying to get this working for a while now. 

I have downloaded and unpacked elasticsearch 2.1 (ZIP from elastic.co) and get the error below. I have reinstalled Java 1.8 and cleaned up any old installations but still get the same error. Any suggestions? I have repeated the download and install of both ElasticSearch and Java a couple of times to be sure.

JAVA_HOME set to C:\Progra~1\Java\jdk1.8.0_25

Thanks in advance

CM

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\WorkSpace\elasticsearch-2.1.0\bin>java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

C:\WorkSpace\elasticsearch-2.1.0\bin>elasticsearch.bat
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/bootstrap/Elasticsearch : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:630)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:614)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:305)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:246)
Could not find the main class: org.elasticsearch.bootstrap.Elasticsearch.  Program will exit.

**Comment by nik9000** [comment]
> Unsupported major.minor version 51.0

This means you are trying to run 2.1.0 (which requires java 7) with java 6 or something older than that. I really think we should do a better job of catching these errors and reporting them with less noise so I'm not going to just close this, though its probably a duplicate and something that you should have asked on discuss.elastic.co.

To debug which version of Java Elasticsearch is picking up you have to hack around in the bat file.

**Comment by CMcMe** [comment]
Thanks for the reply and my apologies, it looks like you are right. Whilst 'java -version' is returning 1.8 it looks like hidden away within my machine is some odd configuration that means 1.6 is being detected by elastic search.

**Comment by jasontedor** [comment]
Closed by #23194
