### ISSUE TITLE
OutOfMemoryError[Java heap space] when executing update with bad fields

### ISSUE THREAD

**Issue by anyatch** [elastic/elasticsearch#15338]
Hi!
Running elasticsearch 2.1.0 I encountered weird behavior when trying to execute update. Tried to execute this query:
```
POST my-index/my-type/my_id/_update
{"doc": {"my_field_name": "blabla"}, "doc_as_upsert": true, "fields": "_source"}
```
and got **OutOfMemoryError\[Java heap space\]** (it took Elasticsearch a few seconds to answer).

As I understand it, the format of the query above is wrong. The value of "fields" should be list, not string (indeed when correcting the query the update worked fine). In a case like that I would expect to get some kind of an error indicating my request is not valid but It seems like some internal error have happen in elasticsearch and resulted in OutOfMemoryError.

This is the stack trace:
`java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:2219)
        at java.util.ArrayList.grow(ArrayList.java:242)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:216)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:208)
        at java.util.ArrayList.add(ArrayList.java:440)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readList(AbstractXContentParser.java:290)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readList(AbstractXContentParser.java:253)
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.list(AbstractXContentParser.java:218)
        at org.elasticsearch.action.update.UpdateRequest.source(UpdateRequest.java:672)
        at org.elasticsearch.rest.action.update.RestUpdateAction.handleRequest(RestUpdateAction.java:101)
        at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:54)
        at org.elasticsearch.rest.RestController.executeHandler(RestController.java:207)
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:166)
        at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:128)
        at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:86)
        at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:348)
        at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:63)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
`

**Comment by clintongormley** [comment]
thanks for reporting @anyatch - nice catch
