### ISSUE TITLE
Windows service fails to start es: 2.1.0 default settings

### ISSUE THREAD

**Issue by randude** [elastic/elasticsearch#15357]
I'm using a clean windows 7 with elastic search 2.1.0 with the default settings.
When i run the process with elasticsearch.bat everything is ok.
When i try to run the service via the service.bat start i get this log in the stderr file:

"Failed to start service
2015-12-10 09:11:57 Commons Daemon procrun stderr initialized
Exception in thread "main" tion: path.home is not configured
	at org.elasticsearch.env.Environment.<init>(Environment.java:99)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:81)
	at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:107)
	at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:100)
	at org.elasticsearch.bootstrap.BootstrapCLIParser.<init>(BootstrapCLIParser.java:48)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:241)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
The data area passed to a system call is too small.
"

I installed the process properly and i've seen that this is a known issue that was supposedly fixed. This isn't the case. 
Please assist.
Thanks.

One last thing: when i installed the service i got this error:
Error: Don't modify the classpath with ES_CLASSPATH, Best is to add
additional elements via the plugin mechanism, or if code must really be
added to the main classpath, add jars to lib\, unsupported
The service 'elasticsearch-service-x64' has been installed.

**Comment by randude** [comment]
solved it, it was my machine's problem...
