### ISSUE TITLE
bin/plugin failure returns 0

### ISSUE THREAD

**Issue by ntent-ashton** [elastic/elasticsearch#15455]
I was working on what I thought was a clean machine, but it turns out some strange dependency pulled in and set default java-1.6.0.  bin/plugin barfs (won't even run), but for some reason exits 0, which threw me way off course in debugging.

[root@ca6-06:/usr/share/elasticsearch]# bin/plugin  http://nexus/nexus/content/repositories/releases/boilerplate/1.0.0/boilerplate-1.0.0.zip
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/plugins/PluginManagerCliParser : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)

Could not find the main class: org.elasticsearch.plugins.PluginManagerCliParser. Program will exit.

**Comment by ntent-ashton** [comment]
The resolution for this issue was obviously to kill 1.6.0 with extreme prejudice.  The issue is that bin/plugin returns 0 on this failure.

**Comment by jasontedor** [comment]
I can not reproduce this on 2.x nor on master. What version of Elasticsearch are you seeing this on?

```
14:04:45 [jason:~/elasticsearch/elasticsearch-2.1.0/bin] $ JAVA_HOME=`/usr/libexec/java_home -v 1.6` ./plugin
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/plugins/PluginManagerCliParser : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
14:05:05 [jason:~/elasticsearch/elasticsearch-2.1.0/bin] 1 $ echo $?
1

**Comment by ntent-ashton** [comment]
You know what, I can't reproduce it - also I think it's more related to bad handling of this error in the puppet module anyway.  My mistake.
