### ISSUE TITLE
Apparent degradation in handling of large concurrent index job on update from 1.3.4 to 2.1.0

### ISSUE THREAD

**Issue by hronik1** [elastic/elasticsearch#15465]
Scoping out potential issues from upgrading from 1.3.4 to 2.1.0 since 1.3.4 is swiftly approaching end of life.

I am standing up identical spec 1.3.4 and 2.1.0 single node clusters, and attempting to reindex an existing index from the current staging environment into them(doing this to both to see how the versions compare when being overloaded as well as to get some test data into them). I am launching a spark job which uses elasticsearch-hadoop-2.2.0-m1 and is indexing into it using 16 executors.

To my surprise, the 1.3.4 index got about 200 times more data into it before the index job failed, compared to the 2.1.0 index. While indexing into both seemed to face error conditions along the way(will post errors below), the 2.1.0 index job seemed to fail almost immediately while the 1.3.4 seems to attempt recovery and continue indexing for quite some time before failing.

Recurring 1.3.4 error(seen repeatedly, but indexing continues):
```
15/12/15 16:33:51 ERROR Executor: Exception in task 8.0 in stage 0.0 (TID 8)
org.elasticsearch.hadoop.EsHadoopException: Could not write all entries [6/1047872] (maybe ES was overloaded?). Bailing out...
	at org.elasticsearch.hadoop.rest.RestRepository.flush(RestRepository.java:239)
	at org.elasticsearch.hadoop.rest.RestRepository.doWriteToIndex(RestRepository.java:176)
	at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:152)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:49)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$saveToEsWithMeta$1.apply(EsSpark.scala:86)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$saveToEsWithMeta$1.apply(EsSpark.scala:86)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

Error in 2.1.0(fails almost immediately after encountering):
```
15/12/15 16:58:29 ERROR Executor: Exception in task 8.0 in stage 0.0 (TID 8)
org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: Found unrecoverable error [Too Many Requests(429) - [rejected execution of org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase$1@250a2a1c on EsThreadPoolExecutor[bulk, queue capacity = 50, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@75bb8775[Running, pool size = 2, active threads = 2, queued tasks = 50, completed tasks = 0]]]]; Bailing out..
	at org.elasticsearch.hadoop.rest.RestClient.retryFailedEntries(RestClient.java:215)
	at org.elasticsearch.hadoop.rest.RestClient.bulk(RestClient.java:169)
	at org.elasticsearch.hadoop.rest.RestRepository.tryFlush(RestRepository.java:214)
	at org.elasticsearch.hadoop.rest.RestRepository.flush(RestRepository.java:237)
	at org.elasticsearch.hadoop.rest.RestRepository.doWriteToIndex(RestRepository.java:176)
	at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:152)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:49)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$saveToEsWithMeta$1.apply(EsSpark.scala:86)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$saveToEsWithMeta$1.apply(EsSpark.scala:86)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by jasontedor** [comment]
> single node clusters

From the bulk thread pool having `pool size = 2` (in your exception message) we can deduce that this a very small node, two cores it appears?

> indexing into it using 16 executors

From your description, I'm assuming that these are all operating concurrently. This is basically the perfect setup for an overwhelmed node.

On 1.3.4:

> `maybe ES was overloaded?`

On 2.1.0:

> `Too Many Requests(429) - [rejected execution... queue capacity = 50...queued tasks = 50...]`

In both cases, the exception messages are telling you that Elasticsearch can't keep up, and this doesn't strike me as surprising at all given that you have sixteen workers and two consumers. Elasticsearch is trying to apply backpressure to the job because its bulk queue is stuffed.

Given this, I don't see an issue to be addressed.

**Comment by hronik1** [comment]
Jason yes, as I pointed out earlier in the post, the purpose is to test how
the cluster handles when it is overwhelmed.

I am aware that those messages are pointing out the fact the node is being
overwhelmed, that is not my point of confusion. The point I am trying to
prove is that this appears to be a regression, since 1.3.4 consistently
appears to be doing a much better job at successfully applying back
pressure and indexing data into a node when in an overwhelmed stated, while
2.1.0 appears to immediately just fall over.

**Comment by clintongormley** [comment]
It's not falling over. It is rejecting requests (telling the client to back off) so that it doesn't fall over and consume all resources, depriving other tasks like eg search from working.

**Comment by hronik1** [comment]
Clinton, yes my apologies for the misuse of fallover.

I am aware of why the reject requests are happening, as well as their
purpose. My confusion, and underlying issue I am trying to get at is why
the older version appears to be able to index substantially more(200x, 15
million vs. 85 thousand) documents before reaching a state where they
completely stop indexing altogether. If this was a trivial difference, I
would not be so concerned/confused, however a 200x difference is not
trivial.

**Comment by jasontedor** [comment]
@hronik1 I understand what you're saying, but sixteen producers against two consumers is so far beyond the intended usage of Elasticsearch and the bulk API (which sits behind the elasticsearch-hadoop implementation) that it is not a situation to engineer for.

**Comment by AshisPF** [comment]
increase the ulimit on the consumer .

Use a text editor and open the /etc/initscript file and add the following lines to the file:
ulimit -Hn 65535
ulimit -Sn 65535
eval exec "$4"

Save the file.
If you start the server as a regular process
Use a text editor and open the /etc/security/limits.conf file.
Increase the upper limit on the number of file descriptors by adding the following lines to the file:

* soft    nofile          65535
* hard    nofile          65535

Save the file.
Restart the Linux server for the operating system change to take effect for all processes.
