### ISSUE TITLE
merge thread are blocked each other

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#15538]
my server runs very slow and I did a thread dump and found out that many lucene merge threads are blocked.
my question is:
1. why are there so many merge threds?
2. why are thy blocked each other?
3. is this a ES 2.1.0 bug?

Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode):

"elasticsearch[node1][[jsf-monitor-data-performance-2015-12-18][9]: Lucene Merge Thread #655955]" #668132 daemon prio=5 os_prio=0 tid=0x00007f24880dd800 nid=0x17978 waiting for monitor entry [0x00007f221c9b6000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler.beforeMerge(InternalEngine.java:1200)
	- waiting to lock <0x000000019b76d350> (a org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler)
	at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.doMerge(ElasticsearchConcurrentMergeScheduler.java:93)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:626)

"elasticsearch[node1][[jsf-monitor-data-performance-2015-12-18][9]: Lucene Merge Thread #655954]" #668131 daemon prio=5 os_prio=0 tid=0x00007f236912a000 nid=0x17977 waiting for monitor entry [0x00007f21fb618000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler.afterMerge(InternalEngine.java:1212)
	- waiting to lock <0x000000019b76d350> (a org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler)
	at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.doMerge(ElasticsearchConcurrentMergeScheduler.java:99)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:626)

"elasticsearch[node1][[jsf-monitor-data-performance-2015-12-18][9]: Lucene Merge Thread #655953]" #668130 daemon prio=5 os_prio=0 tid=0x00007f2368d59800 nid=0x17976 waiting for monitor entry [0x00007f22051e7000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler.afterMerge(InternalEngine.java:1212)
	- waiting to lock <0x000000019b76d350> (a org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler)
	at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.doMerge(ElasticsearchConcurrentMergeScheduler.java:99)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:626)

"elasticsearch[node1][[jsf-monitor-data-performance-2015-12-18][9]: Lucene Merge Thread #655952]" #668129 daemon prio=5 os_prio=0 tid=0x00007f2368d59000 nid=0x17975 waiting for monitor entry [0x00007f221e161000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler.afterMerge(InternalEngine.java:1212)
	- waiting to lock <0x000000019b76d350> (a org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler)
	at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.doMerge(ElasticsearchConcurrentMergeScheduler.java:99)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:626)

"elasticsearch[node1][[jsf-monitor-data-performance-2015-12-18][9]: Lucene Merge Thread #655951]" #668128 daemon prio=5 os_prio=0 tid=0x00007f236913e800 nid=0x17974 waiting for monitor entry [0x00007f22515ce000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4237)
	- waiting to lock <0x0000000125da7ac0> (a org.apache.lucene.index.IndexWriter)
	at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:3664)
	at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:588)
	at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.doMerge(ElasticsearchConcurrentMergeScheduler.java:94)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:626)

"elasticsearch[node1][[jsf-monitor-data-performance-2015-12-18][9]: Lucene Merge Thread #655950]" #668127 daemon prio=5 os_prio=0 tid=0x00007f243408c800 nid=0x17973 waiting for monitor entry [0x00007f2251a83000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler.beforeMerge(InternalEngine.java:1200)
	- waiting to lock <0x000000019b76d350> (a org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler)
	at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.doMerge(ElasticsearchConcurrentMergeScheduler.java:93)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:626)

"elasticsearch[node1][[jsf-monitor-data-performance-2015-12-18][9]: Lucene Merge Thread #655949]" #668126 daemon prio=5 os_prio=0 tid=0x00007f253c0a1000 nid=0x17972 waiting for monitor entry [0x00007f21bf650000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler.afterMerge(InternalEngine.java:1212)
	- waiting to lock <0x000000019b76d350> (a org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler)
	at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.doMerge(ElasticsearchConcurrentMergeScheduler.java:99)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:626)

"elasticsearch[node1][[jsf-monitor-data-performance-2015-12-18][9]: Lucene Merge Thread #655948]" #668125 daemon prio=5 os_prio=0 tid=0x00007f2368d5f000 nid=0x17971 waiting for monitor entry [0x00007f21bf04a000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler.afterMerge(InternalEngine.java:1212)
	- waiting to lock <0x000000019b76d350> (a org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler)
	at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.doMerge(ElasticsearchConcurrentMergeScheduler.java:99)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:626)

"elasticsearch[node1][[jsf-monitor-data-performance-2015-12-18][9]: Lucene Merge Thread #655947]" #668124 daemon prio=5 os_prio=0 tid=0x00007f2369156000 nid=0x17970 waiting for monitor entry [0x00007f22052e8000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler.afterMerge(InternalEngine.java:1212)
	- waiting to lock <0x000000019b76d350> (a org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler)
	at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.doMerge(ElasticsearchConcurrentMergeScheduler.java:99)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:626)

"elasticsearch[node1][[jsf-monitor-data-performance-2015-12-18][9]: Lucene Merge Thread #655946]" #668123 daemon prio=5 os_prio=0 tid=0x00007f2369144800 nid=0x1796f waiting for monitor entry [0x00007f221dd5d000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler.afterMerge(InternalEngine.java:1212)
	- waiting to lock <0x000000019b76d350> (a org.elasticsearch.index.engine.InternalEngine$EngineMergeScheduler)
	at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.doMerge(ElasticsearchConcurrentMergeScheduler.java:99)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:626)

**Comment by mikemccand** [comment]
Can you include all threads in the thread dump?

Somehow your shard is scheduled a truly insane number of merges (655K+) over time ... have you changed any settings from defaults?  How are you using ES, e.g. are you asking ES to refresh or flush frequently?

**Comment by makeyang** [comment]
@mikemccand  sorry for late replay. it was the weekend last 2 days and I happened can't touch internet.
the full thread dump is below link:
https://github.com/makeyang/grocery/blob/master/td.txt
Yes, I changed some settings from default:
index.translog.sync_interval: 30s
index.translog.durability: async
indices.memory.index_buffer_size: 40%

**Comment by mikemccand** [comment]
I see way too many bulk indexing threads (stalled, because merging can't keep up).

Did you increase your bulk thread pool size to >= 200?

**Comment by makeyang** [comment]
@mikemccand 
yes, bulk thread pool size to = 200

our situation is below:
many client try to write to ES and concurrency is high, so I try to handle this high concurrency  and modified the thread pool size and queue size.

**Comment by clintongormley** [comment]
@makeyang don't increase the number of bulk threads like that - you're overloading the system on one side and paying for it somewhere else.  You won't be able to set such high values going forward. See https://github.com/elastic/elasticsearch/pull/15585

If your hardware isn't keeping up with your requirements, you need more hardware
