### ISSUE TITLE
Security manager and file permissions

### ISSUE THREAD

**Issue by aeryaguzov** [elastic/elasticsearch#15556]
Current version: 2.1.1

```
IndexCreationException[failed to create index]; nested: AccessControlException[access denied ("java.io.FilePermission" "/data/search/ext/exceptions.txt" "read")];
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:360)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewIndices(IndicesClusterStateService.java:307)
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:176)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:494)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/data/search/ext/exceptions.txt" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:372)
        at java.security.AccessController.checkPermission(AccessController.java:559)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
        at java.io.File.isDirectory(File.java:838)
```

```
$ ls -la /data/search/ext/exceptions.txt
-rwxrwxrwx 1 root root 816 дек.  19 10:05 /data/search/ext/exceptions.txt
```

File has right permissions and can be read by elasticsearch user.

I found a [workaround] (https://discuss.elastic.co/t/accesscontrolexception-when-accessing-local-file-from-plugin/33658) and disable security manager, everything is working fine now.

Can you explain this behavior or fix it if it is wrong ?

**Comment by dadoonet** [comment]
Is it a config file or so? If so, you should place it in the config folder.

My 2 cents

**Comment by aeryaguzov** [comment]
It is a file with mapping for char filter, specified in **mapping_path**.

Can explain why this file and, I think, any other must be in config folder? Is there any docs about that?

**Comment by dadoonet** [comment]
I agree that it should be documented in char filter doc. Also may be added to breaking changes in 2.0.

Do you want to contribute this doc change?

**Comment by aeryaguzov** [comment]
Yeah, of course.

Just need time to test all "paths" options like **synonyms_path** and ***stopwords_path** to ensure they are all must be in the config folder.

I'll provide a PR in a couple of days.
