### ISSUE TITLE
mvel  Thread Safe question

### ISSUE THREAD

**Issue by zhangrong4** [elastic/elasticsearch#15563]
We encounter a problem.When concurrent is large，it occurs stack  as follow：

"rateplanDateExecutor-499" - Thread t@38815
   java.lang.Thread.State: RUNNABLE
	at java.util.WeakHashMap.get(WeakHashMap.java:403)
	at org.mvel2.util.ParseTools.getBestCandidate(ParseTools.java:243)
	at org.mvel2.util.ParseTools.getBestCandidate(ParseTools.java:224)
	at org.mvel2.PropertyAccessor.getMethod(PropertyAccessor.java:864)
	at org.mvel2.PropertyAccessor.get(PropertyAccessor.java:164)
	at org.mvel2.PropertyAccessor.get(PropertyAccessor.java:135)
	at org.mvel2.ast.ASTNode.getReducedValue(ASTNode.java:167)
	at org.mvel2.MVELInterpretedRuntime.parseAndExecuteInterpreted(MVELInterpretedRuntime.java:93)
	at org.mvel2.MVELInterpretedRuntime.parse(MVELInterpretedRuntime.java:44)
	at org.mvel2.MVEL.eval(MVEL.java:155)
	at org.mvel2.PropertyAccessor.getMethod(PropertyAccessor.java:802)
	at org.mvel2.PropertyAccessor.get(PropertyAccessor.java:164)
	at org.mvel2.PropertyAccessor.get(PropertyAccessor.java:135)
	at org.mvel2.ast.Union.getReducedValue(Union.java:50)
	at org.mvel2.MVELInterpretedRuntime.parseAndExecuteInterpreted(MVELInterpretedRuntime.java:93)
	at org.mvel2.MVELInterpretedRuntime.parse(MVELInterpretedRuntime.java:44)
	at org.mvel2.MVEL.eval(MVEL.java:262)
	at org.mvel2.MVEL.evalToBoolean(MVEL.java:691)
	at cobar.client.router.rules.ibatis.IBatisNamespaceShardingRule.isDefinedAt(IBatisNamespaceShardingRule.java:54)
	at cobar.client.router.rules.ibatis.IBatisNamespaceShardingRule.isDefinedAt(IBatisNamespaceShardingRule.java:33)
	at cobar.client.router.DefaultCobarClientInternalRouter.searchMatchedRuleAgainst(DefaultCobarClientInternalRouter.java:109)
	at cobar.client.router.DefaultCobarClientInternalRouter.doRoute(DefaultCobarClientInternalRouter.java:72)
	at cobar.client.router.DefaultCobarClientInternalRouter.doRoute(DefaultCobarClientInternalRouter.java:52)
	at cobar.client.CobarSqlSessionTemplate.lookupDataSourcesByRouter(CobarSqlSessionTemplate.java:849)
	at cobar.client.CobarSqlSessionTemplate.selectList(CobarSqlSessionTemplate.java:258)
	at cobar.client.CobarSqlSessionTemplate.selectList(CobarSqlSessionTemplate.java:249)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:119)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:63)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy33.queryListByParams(Unknown Source)
	at wolverine.ris.index.rateplan.service.RatePlanService.sendRatePlanDate(RatePlanService.java:192)
	at wolverine.ris.index.rateplan.service.RatePlanService.queryRatePlanDate(RatePlanService.java:159)
	at wolverine.ris.index.rateplan.service.RatePlanService$$FastClassByCGLIB$$2e73933b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:701)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:95)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- locked <26c6fd14> (a java.util.concurrent.ThreadPoolExecutor$Worker)

code：
if(bestCandidate != null){
    if(methCathe == null){
           RESOLVED_METH_CATHE.put(method,methCathe=new WeakHashMap<Integer,WeakReference<Method>>());
    }

**Comment by jpountz** [comment]
Can you give more context, I'm confused to not even see 'elasticsearch' in the stack trace. Also how is RESOLVED_METH_CATHE defined, is it  shared by several scripts?

**Comment by zhangrong4** [comment]
it's just mvel question，not ES ，
the defination is  as follow:
private Static Map<String,Map<Integer,WeakReference<Method>>>  RESOLVE_METH_CATHE = new  WeakHashMap<String,Map<Integer,WeakReference<Method>>>
when  use get method,it is deadlocked,the cpu usage reach 100%

**Comment by zhangrong4** [comment]
WeakHashMap<String,Map<Integer,WeakReference<Method>>>

**Comment by jpountz** [comment]
Since you are not using elasticsearch from within elasticsearch, it is probably a better idea to ask the question at the mvel project directly https://github.com/mvel/mvel.
