### ISSUE TITLE
NullPointerException for query with index time boost

### ISSUE THREAD

**Issue by jbgo** [elastic/elasticsearch#15576]
The the following index, mapping, and data,

    curl -XPUT localhost:9200/rolodex

    curl -XPUT localhost:9200/rolodex/_mapping/people -d '{
      "properties": {
        "first_name": {
          "type": "string",
          "boost": 2
        },
        "last_name": {
          "type": "string"
        }
      }
    }'

    curl -XPOST localhost:9200/rolodex/people/_bulk
    -d '{"index":{}}
    {"first_name":"Luke","last_name":"Skywalker"}
    {"index":{}}
    {"first_name":"Darth","last_name":"Vader"}
    {"index":{}}
    {"first_name":"Hans","last_name":"Solo"}
    '

the following query reports a null pointer exception.

    curl -XGET localhost:9200/rolodex/people/_search -d '{
      "query": {
        "query_string": {
          "query": "Luke Skywalker",
          "default_operator": "AND"
        }
      }
    }'

    RESPONSE:
    {
      "took": 2,
      "timed_out": false,
      "_shards": {
        "total": 5,
        "successful": 4,
        "failed": 1,
        "failures": [
          {
            "shard": 0,
            "index": "rolodex",
            "node": "L_In19tcTLSNSzmsmgil-A",
            "reason": {
              "type": "null_pointer_exception",
              "reason": null
            }
          }
        ]
      },
      "hits": {
        "total": 1,
        "max_score": 1.3258252,
        "hits": [
          {
            "_index": "rolodex",
            "_type": "people",
            "_id": "AVHFemEFCCiMRlO7V7ZY",
            "_score": 1.3258252,
            "_source": {
              "first_name": "Luke",
              "last_name": "Skywalker"
            }
          }
        ]
      }
    }

With only 3 documents, sometimes I have to delete and recreate the index a couple of times before the failure is reported. Sometimes no nodes fail, and sometimes all nodes fail.

I am running the elasticsearch 2.1.0 image from
https://hub.docker.com/_/elasticsearch/ on boot2docker 1.9.0.

Here is the stack trace from the elasticsearch logs.

    2015-12-21T17:05:46.136403752Z [2015-12-21 17:05:46,136][DEBUG][action.search.type       ] [Morg] [rolodex][0], node[L_In19tcTLSNSzmsmgil-A], [P], v[2], s[STARTED], a[id=LF1cKPjDTsiQf5nQP6xCAA]: Failed to execute [org.elasticsearch.action.search.SearchRequest@adc647e] lastShard [true]
    2015-12-21T17:05:46.136437040Z RemoteTransportException[[Morg][172.17.0.2:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: NullPointerException;
    2015-12-21T17:05:46.136442165Z Caused by: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: NullPointerException;
    2015-12-21T17:05:46.136445843Z  at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:343)
    2015-12-21T17:05:46.136449638Z  at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:106)
    2015-12-21T17:05:46.136461835Z  at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:363)
    2015-12-21T17:05:46.136466054Z  at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:375)
    2015-12-21T17:05:46.136469858Z  at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
    2015-12-21T17:05:46.136473454Z  at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
    2015-12-21T17:05:46.136477012Z  at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
    2015-12-21T17:05:46.136480479Z  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    2015-12-21T17:05:46.136483856Z  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    2015-12-21T17:05:46.136487285Z  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    2015-12-21T17:05:46.136491130Z  at java.lang.Thread.run(Thread.java:745)
    2015-12-21T17:05:46.136494768Z Caused by: java.lang.NullPointerException
    2015-12-21T17:05:46.136498057Z  at org.apache.lucene.index.OrdTermState.copyFrom(OrdTermState.java:37)
    2015-12-21T17:05:46.136501479Z  at org.apache.lucene.codecs.BlockTermState.copyFrom(BlockTermState.java:56)
    2015-12-21T17:05:46.136506167Z  at org.apache.lucene.codecs.lucene50.Lucene50PostingsFormat$IntBlockTermState.copyFrom(Lucene50PostingsFormat.java:475)
    2015-12-21T17:05:46.136509715Z  at org.apache.lucene.codecs.blocktree.SegmentTermsEnum.seekExact(SegmentTermsEnum.java:1014)
    2015-12-21T17:05:46.136513150Z  at org.elasticsearch.common.lucene.all.AllTermQuery$1.scorer(AllTermQuery.java:152)
    2015-12-21T17:05:46.136516449Z  at org.elasticsearch.common.lucene.all.AllTermQuery$1.scorer(AllTermQuery.java:102)
    2015-12-21T17:05:46.136520126Z  at org.apache.lucene.search.Weight.bulkScorer(Weight.java:135)
    2015-12-21T17:05:46.136523487Z  at org.apache.lucene.search.BooleanWeight.booleanScorer(BooleanWeight.java:201)
    2015-12-21T17:05:46.136526914Z  at org.apache.lucene.search.BooleanWeight.bulkScorer(BooleanWeight.java:233)
    2015-12-21T17:05:46.136530305Z  at org.apache.lucene.search.BooleanWeight.booleanScorer(BooleanWeight.java:201)
    2015-12-21T17:05:46.136533711Z  at org.apache.lucene.search.BooleanWeight.bulkScorer(BooleanWeight.java:233)
    2015-12-21T17:05:46.136537120Z  at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:769)
    2015-12-21T17:05:46.136540486Z  at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:486)
    2015-12-21T17:05:46.136543839Z  at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:324)
    2015-12-21T17:05:46.136547271Z  ... 10 more

**Comment by jimferenczi** [comment]
You can find the fix for 2.1.2 here: https://github.com/elastic/elasticsearch/pull/15506

**Comment by jimferenczi** [comment]
I am closing it since the fix is pushed.

**Comment by jbgo** [comment]
@jimferenczi thanks! :smile:
