### ISSUE TITLE
Java Indexed Scripts API - prepare put - Failed to derive XContent

### ISSUE THREAD

**Issue by sokrahta** [elastic/elasticsearch#15583]
Trying to use the indexed scripts api from the java client

have latest versions
* elasticsearch 2.1.1
* groovy 2.4.4

attempting to follow the guide
https://github.com/elastic/elasticsearch/blob/master/docs/java-api/indexed-scripts.asciidoc

```
    client.client.preparePutIndexedScript
      .setScriptLang("groovy")
      .setId("script1")
      .setSource("_score * doc['my_numeric_field'].value")
      .execute.actionGet
```

fails with this exception
```
org.elasticsearch.ElasticsearchParseException: Failed to derive xcontent
 at org.elasticsearch.common.xcontent.XContentFactory.xContent(XContentFactory.java:293)
 at org.elasticsearch.script.ScriptService.validate(ScriptService.java:359)
 at org.elasticsearch.script.ScriptService.putScriptToIndex(ScriptService.java:394)
 at org.elasticsearch.action.indexedscripts.put.TransportPutIndexedScriptAction.doExecute(TransportPutIndexedScriptAction.java:51)
 at org.elasticsearch.action.indexedscripts.put.TransportPutIndexedScriptAction.doExecute(TransportPutIndexedScriptAction.java:37)
 at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:70)
 at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
 at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:347)
 at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85)
 at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59)
 at com.socrata.cetera.search.TestESData$class.bootstrapSettings(TestESData.scala:292)
...
```

**Comment by ywelsch** [comment]
The documentation is wrong. Instead of
```
.setSource("_score * doc['my_numeric_field'].value")
```
use
```
.setSource("{ \"script\": \"_score * doc['my_numeric_field'].value\" }")
```
or simpler:
```
.setSource("script", "_score * doc['my_numeric_field'].value")
```

**Comment by sokrahta** [comment]
thanks @ywelsch :+1:
