### ISSUE TITLE
Could not load hunspell dictionary through a symlink

### ISSUE THREAD

**Issue by thlawiczka** [elastic/elasticsearch#15581]
Hi,

using ES 2.1.0 I can't use a system hunspell dictionary, as follow:
```
mkdir -p /etc/elasticsearch/hunspell/pl_PL
cd /etc/elasticsearch/hunspell/pl_PL
ln -s /usr/share/hunspell/pl_PL.* .
ls -l /etc/elasticsearch/hunspell/pl_PL
lrwxrwxrwx 1 root root 29 Dec 21 15:48 pl_PL.aff -> /usr/share/hunspell/pl_PL.aff
lrwxrwxrwx 1 root root 29 Dec 21 15:48 pl_PL.dic -> /usr/share/hunspell/pl_PL.dic
```

```
[2015-12-21 15:54:27,417][ERROR][indices.analysis         ] [Hammer and Anvil] Could not load hunspell dictionary [pl_PL]
java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/elasticsearch/hunspell/pl_PL/pl_PL.dic" "read")
        at java.security.AccessControlContext.checkPermission(Unknown Source)
        at java.security.AccessController.checkPermission(Unknown Source)
        at java.lang.SecurityManager.checkPermission(Unknown Source)
        at java.lang.SecurityManager.checkRead(Unknown Source)
        at sun.nio.fs.UnixChannelFactory.open(Unknown Source)
        at sun.nio.fs.UnixChannelFactory.newFileChannel(Unknown Source)
        at sun.nio.fs.UnixChannelFactory.newFileChannel(Unknown Source)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source)
        at java.nio.file.Files.newInputStream(Unknown Source)
        at org.elasticsearch.indices.analysis.HunspellService.loadDictionary(HunspellService.java:185)
        at org.elasticsearch.indices.analysis.HunspellService.access$000(HunspellService.java:70)
        at org.elasticsearch.indices.analysis.HunspellService$1.load(HunspellService.java:96)
        at org.elasticsearch.indices.analysis.HunspellService$1.load(HunspellService.java:91)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
        at org.elasticsearch.indices.analysis.HunspellService.scanAndLoadDictionaries(HunspellService.java:134)
        at org.elasticsearch.indices.analysis.HunspellService.<init>(HunspellService.java:102)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:56)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:887)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:880)
        at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:46)
        at org.elasticsearch.node.Node.<init>(Node.java:202)
        at org.elasticsearch.node.Node.<init>(Node.java:129)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
[2015-12-21 15:54:27,420][ERROR][indices.analysis         ] [Hammer and Anvil] exception while loading dictionary pl_PL
```

However, coping files or using hard-links (`ln` without -s) works fine. Also version ES 1.7 works with symlinks.

ES user has proper perms for those files:
```
su - elasticsearch -c "wc -l /usr/share/hunspell/pl_PL.*"
   7232 /usr/share/hunspell/pl_PL.aff
 297671 /usr/share/hunspell/pl_PL.dic
 304903 total
```

**Comment by thlawiczka** [comment]
It seem to be the same as this one: https://github.com/elastic/elasticsearch/issues/14733 .

**Comment by clintongormley** [comment]
Correct. This is no longer supported. https://www.elastic.co/guide/en/elasticsearch/reference/2.1/breaking_20_plugin_and_packaging_changes.html#_symbolic_links_and_paths
