### ISSUE TITLE
One server SERVER_UNAVAILBLE

### ISSUE THREAD

**Issue by shaharmor** [elastic/elasticsearch#15624]
```
[2015-12-23 07:28:50,395][INFO ][cluster.service          ] [elasticsearch5eu] detected_master {elasticsearch4eu}{mwj3SPCCTxC6Hs-vVUi7DA}{10.240.0.27}{10.240.0.27:9300}{max_local_storage_nodes=1}, added {{elasticsearch4eu}{mwj3SPCCTxC6Hs-vVUi7DA}{10.240.0.27}{10.240.0.27:9300}{max_local_storage_nodes=1},}, reason: zen-disco-receive(from master [{elasticsearch4eu}{mwj3SPCCTxC6Hs-vVUi7DA}{10.240.0.27}{10.240.0.27:9300}{max_local_storage_nodes=1}])
[2015-12-23 07:28:50,397][INFO ][discovery.zen            ] [elasticsearch5eu] master_left [{elasticsearch4eu}{mwj3SPCCTxC6Hs-vVUi7DA}{10.240.0.27}{10.240.0.27:9300}{max_local_storage_nodes=1}], reason [transport disconnected]
[2015-12-23 07:28:50,397][INFO ][discovery.zen            ] [elasticsearch5eu] failed to send join request to master [{elasticsearch4eu}{mwj3SPCCTxC6Hs-vVUi7DA}{10.240.0.27}{10.240.0.27:9300}{max_local_storage_nodes=1}], reason [NodeDisconnectedException[[elasticsearch4eu][10.240.0.27:9300][internal:discovery/zen/join] disconnected]]
[2015-12-23 07:28:50,397][WARN ][discovery.zen            ] [elasticsearch5eu] master left (reason = transport disconnected), current nodes: {{elasticsearch3eu}{p5GtQctYTUmBxt9ICB8NrA}{10.240.0.22}{10.240.0.22:9300}{max_local_storage_nodes=1},{elasticsearch5eu}{-PXOfPkwQRSPYpwsLpapag}{10.240.0.29}{10.240.0.29:9300}{max_local_storage_nodes=1},}
[2015-12-23 07:28:50,397][INFO ][cluster.service          ] [elasticsearch5eu] removed {{elasticsearch4eu}{mwj3SPCCTxC6Hs-vVUi7DA}{10.240.0.27}{10.240.0.27:9300}{max_local_storage_nodes=1},}, reason: zen-disco-master_failed ({elasticsearch4eu}{mwj3SPCCTxC6Hs-vVUi7DA}{10.240.0.27}{10.240.0.27:9300}{max_local_storage_nodes=1})
[2015-12-23 07:28:50,397][WARN ][cluster.service          ] [elasticsearch5eu] failed to notify ClusterStateListener
java.lang.IllegalStateException: master not available when registering auto-generated license
	at org.elasticsearch.license.plugin.core.LicensesService.requestTrialLicense(LicensesService.java:750)
	at org.elasticsearch.license.plugin.core.LicensesService.clusterChanged(LicensesService.java:484)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:494)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-23 07:28:51,422][INFO ][rest.suppressed          ] /_bulk Params: {}
ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/2/no master];]
	at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:154)
	at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedRaiseException(ClusterBlocks.java:144)
	at org.elasticsearch.action.bulk.TransportBulkAction.executeBulk(TransportBulkAction.java:212)
	at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:159)
	at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:71)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:70)
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:347)
	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:52)
	at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient.doExecute(BaseRestHandler.java:83)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:347)
	at org.elasticsearch.client.support.AbstractClient.bulk(AbstractClient.java:424)
	at org.elasticsearch.rest.action.bulk.RestBulkAction.handleRequest(RestBulkAction.java:90)
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:54)
	at org.elasticsearch.rest.RestController.executeHandler(RestController.java:207)
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:166)
	at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:128)
	at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:86)
	at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:348)
	at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:63)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:194)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:135)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:452)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by s1monw** [comment]
apparently your master left and the node can't find another one.... please use our discuss forum to ask questions
