### ISSUE TITLE
Configuration failed caused by jar hell

### ISSUE THREAD

**Issue by Glecun** [elastic/elasticsearch#15635]
Hi,

Sorry for my english i'm french...

I'm using the java api.

I was using elasticsearch 1.7 and now I'm trying to update my version to elasticsearch 2.1. It works well until i have to set the 'path.home' for my Node client in my application.

So I did something like this:
```
        node   = nodeBuilder().settings(Settings.builder()
        									.put("path.home", "C:\\path\\to\\elasticsearch-2.1.0\\")
        									.put("cluster.name", "hotline")
        									.put("node.data", "false")
        									.put("node.master", "false")
        									.put("node.name", "Soldat"))     									
        									.node();
```

But when I run the tomcat i have got this error:
```
GRAVE: Critical error during deployment: 
com.sun.faces.config.ConfigurationException: CONFIGURATION FAILED! failed to load bundle [file:/C:/Users/fr115484/Desktop/elasticsearch-2.1.0/plugins/license/license-2.1.0.jar, file:/C:/Users/fr115484/Desktop/elasticsearch-2.1.0/plugins/license/license-core-2.1.0.jar, file:/C:/Users/fr115484/Desktop/elasticsearch-2.1.0/plugins/license/license-plugin-api-2.1.0.jar, file:/C:/Users/fr115484/Desktop/elasticsearch-2.1.0/plugins/marvel-agent/marvel-agent-2.1.0.jar] due to jar hell
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:375)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:225)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4992)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5490)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: failed to load bundle [file:/C:/Users/fr115484/Desktop/elasticsearch-2.1.0/plugins/license/license-2.1.0.jar, file:/C:/Users/fr115484/Desktop/elasticsearch-2.1.0/plugins/license/license-core-2.1.0.jar, file:/C:/Users/fr115484/Desktop/elasticsearch-2.1.0/plugins/license/license-plugin-api-2.1.0.jar, file:/C:/Users/fr115484/Desktop/elasticsearch-2.1.0/plugins/marvel-agent/marvel-agent-2.1.0.jar] due to jar hell
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:338)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:109)
	at org.elasticsearch.node.Node.<init>(Node.java:148)
	at org.elasticsearch.node.Node.<init>(Node.java:129)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:152)
	at com.foncia.hotlinemyfoncia.service.ClientProvider.prepareClient(ClientProvider.java:44)
	at com.foncia.hotlinemyfoncia.util.ElasticSearchSystemEventListener.processEvent(ElasticSearchSystemEventListener.java:32)
	at javax.faces.event.SystemEvent.processListener(SystemEvent.java:106)
	at com.sun.faces.application.ApplicationImpl.processListeners(ApplicationImpl.java:2168)
	at com.sun.faces.application.ApplicationImpl.invokeListenersFor(ApplicationImpl.java:2144)
	at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:302)
	at com.sun.faces.config.ConfigManager.publishPostConfigEvent(ConfigManager.java:600)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:369)
	... 10 more
Caused by: java.lang.IllegalStateException: jar hell!
class: org.apache.catalina.loader.StandardClassLoader
jar1: C:\dev\apache-tomcat-7.0.55\bin\bootstrap.jar
jar2: C:\dev\bin\bootstrap.jar
	at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:280)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:186)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:336)
	... 23 more
```

I think he cannot load the plugins but actually I don't need any plugin for my Node Client...

Please how can I correct that ?

Thanks

**Comment by dadoonet** [comment]
You can join us on discuss.elastic.co for questions.
Cherry on the cake: there's a french section :)

I guess that you have to clean the way tomcat is launched. Tomcat seems to add bootstrap.jar twice...
