### ISSUE TITLE
Exception in thread "main" java.lang.IllegalStateException: path.home is not configured

### ISSUE THREAD

**Issue by selfchanger** [elastic/elasticsearch#15660]
es_version:2.1
code:
   import static org.elasticsearch.node.NodeBuilder.*;

    Node node = nodeBuilder().node(); 
    Client client = node.client();

when i run this application,it gets wrong,why?
Exception in thread "main" java.lang.IllegalStateException: path.home is not configured
	at org.elasticsearch.env.Environment.<init>(Environment.java:99)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:81)
	at org.elasticsearch.node.Node.<init>(Node.java:135)
	at org.elasticsearch.node.Node.<init>(Node.java:129)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:152)
	at com.wap.sohu.mpaper.util.ElasticsearchUtil.main(ElasticsearchUtil.java:237)
Disconnected from the target VM, address: '127.0.0.1:62666', transport: 'socket'

**Comment by selfchanger** [comment]
elasticsearch.yml:
# Use a descriptive name for your cluster:
#
cluster.name: cms-elasticsearch
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
node.name: node-1
#
# Add custom attributes to the node:
#
# node.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
path.home: D:/elasticsearch-2.1.0

**Comment by selfchanger** [comment]
solution:
add "-Des.path.home=D:\\elasticsearch-2.1.0" in VM options,
see http://blog.csdn.net/jianjun200607/article/details/49821813#reply
