### ISSUE TITLE
logs is full of messages: Field data loading is forbidden on firstReceived

### ISSUE THREAD

**Issue by mogadanez** [elastic/elasticsearch#15665]
```
[2015-12-24 18:22:23,097][DEBUG][action.search.type       ] [Honcho] [296715] Failed to execute fetch phase
RemoteTransportException[[Honcho][127.0.0.1:9300][indices:data/read/search[phase/fetch/id]]]; nested: IllegalStateException[Field data loading is forbidden on firstReceived];
Caused by: java.lang.IllegalStateException: Field data loading is forbidden on firstReceived
        at org.elasticsearch.index.fielddata.plain.DisabledIndexFieldData.fail(DisabledIndexFieldData.java:68)
        at org.elasticsearch.index.fielddata.plain.DisabledIndexFieldData.empty(DisabledIndexFieldData.java:59)
        at org.elasticsearch.index.fielddata.plain.AbstractIndexFieldData.load(AbstractIndexFieldData.java:72)
        at org.elasticsearch.search.fetch.fielddata.FieldDataFieldsFetchSubPhase.hitExecute(FieldDataFieldsFetchSubPhase.java:100)
        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:178)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:589)
        at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:408)
        at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:405)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[2015-12-24 18:22:23,097][DEBUG][action.search.type       ] [Honcho] [296714] Failed to execute fetch phase
RemoteTransportException[[Honcho][127.0.0.1:9300][indices:data/read/search[phase/fetch/id]]]; nested: ElasticsearchException[java.lang.IllegalStateException: Field data loading is forbidden on firstReceived]; ne
Caused by: ElasticsearchException[java.lang.IllegalStateException: Field data loading is forbidden on firstReceived]; nested: UncheckedExecutionException[java.lang.IllegalStateException: Field data loading is fo
        at org.elasticsearch.index.fielddata.plain.AbstractIndexFieldData.load(AbstractIndexFieldData.java:82)
        at org.elasticsearch.search.fetch.fielddata.FieldDataFieldsFetchSubPhase.hitExecute(FieldDataFieldsFetchSubPhase.java:100)
        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:178)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:589)
        at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:408)
        at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:405)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Field data loading is forbidden on firstReceived
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
        at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache.load(IndicesFieldDataCache.java:156)
        at org.elasticsearch.index.fielddata.plain.AbstractIndexFieldData.load(AbstractIndexFieldData.java:76)
        ... 10 more

```

**Comment by clintongormley** [comment]
This DEBUG level log message is telling you that you (or one of your users) keeps trying to do something which isn't supported.  If you don't want to see this message, then change they log level for `search.action.type`
