### ISSUE TITLE
es2.1.1 keep throw DocumentAlreadyExistsException

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#15696]
RemoteTransportException[[node1][node1:9300][indices:data/write/index]]; nested: DocumentAlreadyExistsException[[config][4.3.0]: document already exists];
Caused by: [.kibana][[.kibana][0]] DocumentAlreadyExistsException[[config][4.3.0]: document already exists]
        at org.elasticsearch.index.engine.InternalEngine.innerCreateNoLock(InternalEngine.java:432)
        at org.elasticsearch.index.engine.InternalEngine.innerCreate(InternalEngine.java:390)
        at org.elasticsearch.index.engine.InternalEngine.create(InternalEngine.java:362)
        at org.elasticsearch.index.shard.IndexShard.create(IndexShard.java:531)
        at org.elasticsearch.index.engine.Engine$Create.execute(Engine.java:810)
        at org.elasticsearch.action.support.replication.TransportReplicationAction.executeIndexRequestOnPrimary(TransportReplicationAction.java:1073)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:170)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.performOnPrimary(TransportReplicationAction.java:579)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase$1.doRun(TransportReplicationAction.java:452)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by clintongormley** [comment]
This looks like a Kibana issue, not an Elasticsearch issue
