### ISSUE TITLE
Snapshot not failing gracefully when disk quota exceeded

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#15690]
Have a scenario (ES 1.7.1) in the field where the disk quota is exceeded (OpenVZ).  As a result, the snapshot failed shortly after initialization:

```
[2015-12-20 20:00:41,479][WARN ][snapshots                ] [node_name] failed to create snapshot [full_snap:2015_12_20_20_00_02]
org.elasticsearch.snapshots.SnapshotCreationException: [full_snap:2015_12_20_20_00_02] failed to create snapshot
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.initializeSnapshot(BlobStoreRepository.java:260)
	at org.elasticsearch.snapshots.SnapshotsService.beginSnapshot(SnapshotsService.java:290)
	at org.elasticsearch.snapshots.SnapshotsService.access$600(SnapshotsService.java:92)
	at org.elasticsearch.snapshots.SnapshotsService$1$1.run(SnapshotsService.java:211)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /es_snapshots/indices/index_name/snapshot-2015_12_20_20_00_02 (Disk quota exceeded)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
	at org.elasticsearch.common.blobstore.fs.FsBlobContainer.createOutput(FsBlobContainer.java:93)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.initializeSnapshot(BlobStoreRepository.java:247)
	... 6 more
```

However, it status remains in_progress status instead of gracefully recovering and reporting an error:

```
{"snapshots":[{"snapshot":"2015_12_20_20_00_02","version_id":1070199,"version":"1.7.1","indices":["list_of_indices],"state":"IN_PROGRESS","start_time":"2015-12-21T04:00:02.952Z","start_time_in_millis":1450670402952,"failures":[],"shards":{"total":0,"failed":0,"successful":0}}]}
```
1450670402952 = 12/20/2015, 8:00:02 PM (local time)

**Comment by clintongormley** [comment]
@ywelsch could you have a look at this please?

**Comment by ywelsch** [comment]
I looked at the code and, indeed, there is a possibility for this situation to happen (also on master). I will open a PR with a fix in the next days.

**Comment by ywelsch** [comment]
I was wrong in my initial analysis. In 2.0 this situation cannot occur anymore. As this is 1.x only, occurring only in very rare circumstances and not a severe bug (next snapshot can properly be made), I'll close this one.
