### ISSUE TITLE
multi_fields across types cause MapperParsingException

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#15706]
When using a multi_field across types in the same index, Elasticsearch fails with the following exception during indexing:

```
{
  "took": 482,
  "errors": true,
  "items": [
    {
      "index": {
        "_index": "logstash-2015.09.20",
        "_type": "nginx",
        "_id": "AU_x3-TaGFA8no6QjiSO",
        "_version": 1,
        "_shards": {
          "total": 1,
          "successful": 1,
          "failed": 0
        },
        "created": true,
        "status": 201
      }
    },
    {
      "index": {
        "_index": "logstash-2015.09.20",
        "_type": "apache",
        "_id": "AU_x3-TaGFA8no6QjiSB",
        "status": 400,
        "error": {
          "type": "mapper_parsing_exception",
          "reason": "failed to parse",
          "caused_by": {
            "type": "illegal_state_exception",
            "reason": null
          }
        }
      }
    }
  ]
}
```

And on the server:

```
MapperParsingException[failed to parse]; nested: IllegalStateException;
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:146)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:276)
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:483)
	at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:465)
[...]
Caused by: java.lang.IllegalStateException
	at org.elasticsearch.index.mapper.FieldMapper.updateFieldType(FieldMapper.java:365)
	at org.elasticsearch.index.mapper.FieldMapper$MultiFields.updateFieldType(FieldMapper.java:604)
	at org.elasticsearch.index.mapper.FieldMapper.updateFieldType(FieldMapper.java:369)
	at org.elasticsearch.index.mapper.FieldMapper.updateFieldType(FieldMapper.java:50)
	at org.elasticsearch.index.mapper.DocumentParser.parseDynamicValue(DocumentParser.java:613)
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:430)
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:251)
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:114)
	... 17 more
```

Steps to reproduce (see also attached files):

```
curl -XPUT localhost:9200/_template/logstash -d @template.txt
curl -s -XPOST localhost:9200/_bulk --data-binary @bulk_data.txt
```

The reason is that ES tries to reuse the multi_field `ip.raw` from the type `nginx` in the type `apache` but somehow fails to "copy" the settings.

The problem was originally found by @LeeDr from the Kibana team. This is a regression that was introduced with commit id 3015eb3.

[template.txt](https://github.com/elastic/elasticsearch/files/74695/template.txt)
[bulk_data.txt](https://github.com/elastic/elasticsearch/files/74696/bulk_data.txt)

**Comment by jpountz** [comment]
Fixed via #15715
