### ISSUE TITLE
indices\mpapercms\2\translog\translog-3662425237604305305.tlog java.nio.file.NoSuchFileException: D:\elasticsearch-2.1.0\data\elasticsearch\nodes\0\indices\mpapercms\2\translog\translog-3662425237604305305.tlog

### ISSUE THREAD

**Issue by selfchanger** [elastic/elasticsearch#15720]
Hi，since i installed elasticsearch 2.1.0，each time i start up es,it reports this exception：
code:
[2015-12-31 11:02:04,933][WARN ][index.translog           ] [Flash Thompson] [mpapercms][0] failed to delete temp file D:\elasticsearch-2.1.0\data\ela
sticsearch\nodes\0\indices\mpapercms\0\translog\translog-17313653199342993.tlog
java.nio.file.NoSuchFileException: D:\elasticsearch-2.1.0\data\elasticsearch\nodes\0\indices\mpapercms\0\translog\translog-17313653199342993.tlog
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
        at java.nio.file.Files.delete(Files.java:1079)
        at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:324)
        at org.elasticsearch.index.translog.Translog.<init>(Translog.java:166)
        at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:209)
        at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:152)
        at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
        at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1408)
        at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1403)
        at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:906)
        at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:883)
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:245)
        at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
        at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by jpountz** [comment]
this is fixed in version 2.1.1 https://github.com/elastic/elasticsearch/pull/14872

Also you can safely ignore this warning, it is harmless.

**Comment by selfchanger** [comment]
@jpountz see, thanks!
