### ISSUE TITLE
multi_match query gives java.lang.IllegalArgumentException: Illegal shift value, must be 0..63; got shift=2147483647

### ISSUE THREAD

**Issue by jreinke** [elastic/elasticsearch#15860]
Hi team,

I get an error using a `multi_match` query with `cross_fields` type and a numeric query.
I'm using v2.1.1 on OSX, installed via Homebrew.

**Index basic data**
```
curl -XPUT http://localhost:9200/blog/post/1?pretty=1 -d '{"foo":123, "bar":"xyzzy", "baz":456}'
```

**Use a `multi_match` query with `cross_fields` type and a numeric query**
```
curl -XGET http://localhost:9200/blog/post/_search?pretty=1 -d '{"query": {"multi_match": {"type": "cross_fields", "query": "100", "lenient": true, "fields": ["foo", "bar", "baz"]}}}'
```

**Error**
```
{
  "error" : {
    "root_cause" : [ {
      "type" : "illegal_argument_exception",
      "reason" : "Illegal shift value, must be 0..63; got shift=2147483647"
    } ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [ {
      "shard" : 0,
      "index" : "blog",
      "node" : "0TxGVVWsSu2qX63hZdOv2w",
      "reason" : {
        "type" : "illegal_argument_exception",
        "reason" : "Illegal shift value, must be 0..63; got shift=2147483647"
      }
    } ]
  },
  "status" : 400
}
```

**Note that the error does not appear if I specify only 1 numeric field in search.**

**Stack trace**
```
Caused by: java.lang.IllegalArgumentException: Illegal shift value, must be 0..63; got shift=2147483647
	at org.apache.lucene.util.NumericUtils.longToPrefixCodedBytes(NumericUtils.java:147)
	at org.apache.lucene.util.NumericUtils.longToPrefixCoded(NumericUtils.java:121)
	at org.apache.lucene.analysis.NumericTokenStream$NumericTermAttributeImpl.getBytesRef(NumericTokenStream.java:163)
	at org.apache.lucene.analysis.NumericTokenStream$NumericTermAttributeImpl.clone(NumericTokenStream.java:217)
	at org.apache.lucene.analysis.NumericTokenStream$NumericTermAttributeImpl.clone(NumericTokenStream.java:148)
	at org.apache.lucene.util.AttributeSource$State.clone(AttributeSource.java:54)
	at org.apache.lucene.util.AttributeSource.captureState(AttributeSource.java:281)
	at org.apache.lucene.analysis.CachingTokenFilter.fillCache(CachingTokenFilter.java:96)
	at org.apache.lucene.analysis.CachingTokenFilter.incrementToken(CachingTokenFilter.java:70)
	at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:223)
	at org.apache.lucene.util.QueryBuilder.createBooleanQuery(QueryBuilder.java:87)
	at org.elasticsearch.index.search.MatchQuery.parse(MatchQuery.java:178)
	at org.elasticsearch.index.search.MultiMatchQuery.parseAndApply(MultiMatchQuery.java:55)
	at org.elasticsearch.index.search.MultiMatchQuery.access$000(MultiMatchQuery.java:42)
	at org.elasticsearch.index.search.MultiMatchQuery$QueryBuilder.parseGroup(MultiMatchQuery.java:118)
	at org.elasticsearch.index.search.MultiMatchQuery$CrossFieldsQueryBuilder.buildGroupedQueries(MultiMatchQuery.java:198)
	at org.elasticsearch.index.search.MultiMatchQuery.parse(MultiMatchQuery.java:86)
	at org.elasticsearch.index.query.MultiMatchQueryParser.parse(MultiMatchQueryParser.java:163)
	at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:257)
	at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:303)
	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:206)
	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:201)
	at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:831)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:651)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:617)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
```

**Comment by nik9000** [comment]
Fun times. Reproduces in master. I'll work on fixing it there and backporting it after that.

**Comment by jreinke** [comment]
FYI, I have reported a similar bug with the same symptoms (1 numeric field included is ok but 2+ numeric fields give `number_format_exception`). Don't know if it could be related.

https://github.com/elastic/elasticsearch/issues/3975#issuecomment-167577538

**Comment by nik9000** [comment]
Good timing! I've figure out what is up and I've started on a solution. I've only got about two more hours left to work on it so I might not have anything before the weekend but, yeah, I'll have something soon.

The `lenient: true` issue is similar so I'll work on it while I'm in there.

**Comment by nik9000** [comment]
Had to revert the change. I'll get it in there though.
