### ISSUE TITLE
elasticsearch fails to start tribe node

### ISSUE THREAD

**Issue by zcola** [elastic/elasticsearch#15880]
Hi folks,

I'm trying to start tribe node using following config:

```
network.host: 10.63.19.34
tribe:
    e6001:
        #path.conf: /home/elk/etc/tribe-client
        cluster.name: es-test
        discovery.zen.ping.timeout: 100s
        discovery.zen.ping.multicast.enabled: false
        discovery.zen.ping.unicast.hosts: ["10.63.19.36", "10.63.19.37"]
    e6002:
        #path.conf: /home/elk/etc/tribe-client
        cluster.name: es-testold
        discovery.zen.ping.timeout: 100s
        discovery.zen.ping.multicast.enabled: false
        discovery.zen.ping.unicast.hosts: ["10.63.19.34"]
    blocks:
        write:    true
        metadata: true
```
This config resides in the file `~/etc/elasticsearch_tribe/elasticsearch.yml`. I'm starting it using following command:

```
/home/elk/running/elasticsearch/bin/elasticsearch  --path.conf /home/elk/etc/elasticsearch_tribe
```

Elasticsearch fails with following output:

2.1.1
```
/home/elk/running/elasticsearch/bin/elasticsearch  --path.conf /home/elk/etc/elasticsearch_tribe
[2016-01-11 18:14:07,952][WARN ][bootstrap                ] unable to install syscall filter: prctl(PR_GET_NO_NEW_PRIVS): Invalid argument
[2016-01-11 18:14:08,312][INFO ][node                     ] [Great Gambonnos] version[2.1.1], pid[21083], build[40e2c53/2015-12-15T13:05:55Z]
[2016-01-11 18:14:08,312][INFO ][node                     ] [Great Gambonnos] initializing ...
[2016-01-11 18:14:08,686][INFO ][plugins                  ] [Great Gambonnos] loaded [elasticsearch-analysis-ik], sites []
[2016-01-11 18:14:11,782][INFO ][ik-analyzer              ] [Dict Loading]ik/custom/mydict.dic
[2016-01-11 18:14:11,783][INFO ][ik-analyzer              ] [Dict Loading]ik/custom/single_word_low_freq.dic
[2016-01-11 18:14:11,787][INFO ][ik-analyzer              ] [Dict Loading]ik/custom/ext_stopword.dic
[2016-01-11 18:14:12,705][INFO ][node                     ] [Great Gambonnos/e6001] version[2.1.1], pid[21083], build[40e2c53/2015-12-15T13:05:55Z]
[2016-01-11 18:14:12,706][INFO ][node                     ] [Great Gambonnos/e6001] initializing ...
[2016-01-11 18:14:13,080][INFO ][plugins                  ] [Great Gambonnos/e6001] loaded [elasticsearch-analysis-ik], sites []
Exception in thread "main" java.security.AccessControlException: access denied ("java.io.FilePermission" "/home/elk/running/elasticsearch/config/hunspell" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at sun.nio.fs.UnixPath.checkRead(UnixPath.java:795)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:49)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.Files.isDirectory(Files.java:2192)
	at org.elasticsearch.indices.analysis.HunspellService.scanAndLoadDictionaries(HunspellService.java:127)
	at org.elasticsearch.indices.analysis.HunspellService.<init>(HunspellService.java:102)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at <<<guice>>>
	at org.elasticsearch.node.Node.<init>(Node.java:200)
	at org.elasticsearch.tribe.TribeClientNode.<init>(TribeClientNode.java:35)
	at org.elasticsearch.tribe.TribeService.<init>(TribeService.java:140)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at <<<guice>>>
	at org.elasticsearch.node.Node.<init>(Node.java:200)
	at org.elasticsearch.node.Node.<init>(Node.java:128)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	<<<truncated>>>
```

2.1.0
```
/home/elk/running/elasticsearch/bin/elasticsearch  --path.conf /home/elk/etc/elasticsearch_tribe
[2016-01-11 18:17:05,196][WARN ][bootstrap                ] unable to install syscall filter: prctl(PR_GET_NO_NEW_PRIVS): Invalid argument
[2016-01-11 18:17:05,562][INFO ][node                     ] [Lasher] version[2.1.0], pid[22340], build[72cd1f1/2015-11-18T22:40:03Z]
[2016-01-11 18:17:05,562][INFO ][node                     ] [Lasher] initializing ...
[2016-01-11 18:17:06,120][INFO ][plugins                  ] [Lasher] loaded [license, marvel-agent, ${elasticsearch.plugin.name}], sites [kopf]
[2016-01-11 18:17:09,358][INFO ][ik-analyzer              ] [Dict Loading]ik/custom/mydict.dic
[2016-01-11 18:17:09,366][INFO ][ik-analyzer              ] [Dict Loading]ik/custom/single_word_low_freq.dic
[2016-01-11 18:17:09,372][INFO ][ik-analyzer              ] [Dict Loading]ik/custom/ext_stopword.dic
Exception in thread "main" java.security.AccessControlException: access denied ("java.io.FilePermission" "/home/elk/running/elasticsearch/config/elasticsearch.yml" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at sun.nio.fs.UnixPath.checkRead(UnixPath.java:795)
	at sun.nio.fs.UnixFileSystemProvider.checkAccess(UnixFileSystemProvider.java:290)
	at java.nio.file.Files.exists(Files.java:2385)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:86)
	at org.elasticsearch.node.Node.<init>(Node.java:135)
	at org.elasticsearch.node.Node.<init>(Node.java:129)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.tribe.TribeService.<init>(TribeService.java:140)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at <<<guice>>>
	at org.elasticsearch.node.Node.<init>(Node.java:202)
	at org.elasticsearch.node.Node.<init>(Node.java:129)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```
```
java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
cat /etc/debian_version
7.9
```

Please advise how this can be resolved.

Thinks

**Comment by jpountz** [comment]
The problem is due to the fact that your configuration tries to load files (/home/elk/running/elasticsearch/config/hunspell, /home/elk/running/elasticsearch/config/elasticsearch.yml) from outside of your conf directory (/home/elk/etc/elasticsearch_tribe), which is forbidden for security reasons.

**Comment by clintongormley** [comment]
@jpountz i'm just wondering if the tribe node itself is trying to load the hunspell dictionary?

**Comment by rjernst** [comment]
@clintongormley Yes, the tribe node is a "normal" node right now (still initializes all other node services, include the analysis module, which creates the hunspell service). It also seems here path.conf was not read at the right time, since something in the 2.1.0 case tried reading elasticsearch.yml from the default conf dir.

**Comment by zcola** [comment]
@jpountz But the Starting method is used to start the `data node` or `master node` can be started successfully. And I did not `/home/elk/running/elasticsearch/config/hunspell` this file, hunspell this error does not occur in `2.1.1`, not `2.1.0`.

**Comment by zcola** [comment]
@rjernst Your advice?

**Comment by zcola** [comment]
`--path.conf` parameter is not used can be started successfully, but can only start from the default configuration path location

```
 /home/elk/running/elasticsearch/bin/elasticsearch
home/elk/running/elasticsearch/bin/elasticsearch
[2016-01-12 10:18:38,017][WARN ][bootstrap                ] unable to install syscall filter: prctl(PR_GET_NO_NEW_PRIVS): Invalid argument
[2016-01-12 10:18:38,288][INFO ][node                     ] [Arishem the Judge] version[2.1.0], pid[25632], build[72cd1f1/2015-11-18T22:40:03Z]
[2016-01-12 10:18:38,289][INFO ][node                     ] [Arishem the Judge] initializing ...
[2016-01-12 10:18:38,827][INFO ][plugins                  ] [Arishem the Judge] loaded [license, marvel-agent, ${elasticsearch.plugin.name}], sites [kopf]
[2016-01-12 10:18:41,745][INFO ][ik-analyzer              ] [Dict Loading]ik/custom/mydict.dic
[2016-01-12 10:18:41,745][INFO ][ik-analyzer              ] [Dict Loading]ik/custom/single_word_low_freq.dic
[2016-01-12 10:18:41,752][INFO ][ik-analyzer              ] [Dict Loading]ik/custom/ext_stopword.dic
[2016-01-12 10:18:42,300][INFO ][node                     ] [Arishem the Judge/e6001] version[2.1.0], pid[25632], build[72cd1f1/2015-11-18T22:40:03Z]
[2016-01-12 10:18:42,300][INFO ][node                     ] [Arishem the Judge/e6001] initializing ...
[2016-01-12 10:18:42,464][INFO ][plugins                  ] [Arishem the Judge/e6001] loaded [license, marvel-agent, ${elasticsearch.plugin.name}], sites [kopf]
[2016-01-12 10:18:43,045][INFO ][ik-analyzer              ] [Dict Loading]ik/custom/mydict.dic
[2016-01-12 10:18:43,046][INFO ][ik-analyzer              ] [Dict Loading]ik/custom/single_word_low_freq.dic
[2016-01-12 10:18:43,049][INFO ][ik-analyzer              ] [Dict Loading]ik/custom/ext_stopword.dic
[2016-01-12 10:18:43,120][INFO ][node                     ] [Arishem the Judge/e6001] initialized
[2016-01-12 10:18:43,125][INFO ][node                     ] [Arishem the Judge/e6002] version[2.1.0], pid[25632], build[72cd1f1/2015-11-18T22:40:03Z]
[2016-01-12 10:18:43,125][INFO ][node                     ] [Arishem the Judge/e6002] initializing ...
```

**Comment by clintongormley** [comment]
@zcola i finally understand what you mean.  I've opened #16253 to address this
