### ISSUE TITLE
Wrong "index.routing.allocation.enable" value prevents all allocation

### ISSUE THREAD

**Issue by masaruh** [elastic/elasticsearch#15920]
(This happens on 1.7.3 and 2.1.0)

On single node cluster, do this

```
PUT recoverytest

PUT recoverytest/_settings
{
  "index.routing.allocation.enable": "true"
}

```

and restart node.
You get this exception and no shard is allocated.

```
[2016-01-12 17:04:52,871][ERROR][cluster.routing          ] [Blue Shield] unexpected failure during [cluster_reroute(async_shard_fetch)], current state version [2]
java.lang.IllegalArgumentException: Illegal allocation.enable value [TRUE]
	at org.elasticsearch.cluster.routing.allocation.decider.EnableAllocationDecider$Allocation.parse(EnableAllocationDecider.java:189)
	at org.elasticsearch.cluster.routing.allocation.decider.EnableAllocationDecider.canAllocate(EnableAllocationDecider.java:91)
	at org.elasticsearch.cluster.routing.allocation.decider.AllocationDeciders.canAllocate(AllocationDeciders.java:74)
	at org.elasticsearch.gateway.PrimaryShardAllocator.buildNodesToAllocate(PrimaryShardAllocator.java:179)
	at org.elasticsearch.gateway.PrimaryShardAllocator.allocateUnassigned(PrimaryShardAllocator.java:96)
	at org.elasticsearch.gateway.GatewayAllocator.allocateUnassigned(GatewayAllocator.java:125)
	at org.elasticsearch.cluster.routing.allocation.allocator.ShardsAllocators.allocateUnassigned(ShardsAllocators.java:72)
	at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:175)
	at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:155)
	at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:141)
	at org.elasticsearch.cluster.routing.RoutingService$2.execute(RoutingService.java:176)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:388)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I think one wrong value in index level setting shouldn't prevent other indices' shards allocation.
Could be dup of #6732 since this shouldn't happen if you can't set wrong value.

**Comment by clintongormley** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/15278

**Comment by haiguo** [comment]
What we saw is that entire cluster recover can be stopped by a bad setting on a single index.  Master node will stop directly recovery when an IllegalArgumentException is thrown.  Is that fixed in 15278?

**Comment by clintongormley** [comment]
I missed the fact that this is an index setting rather than a cluster setting. Index settings are still being worked on, but yes, the validation of index settings will fix this.  This will be fixed once https://github.com/elastic/elasticsearch/issues/6732 is closed

**Comment by promiseofcake** [comment]
What can we do if we are currently in this state short of upgrading? (2.4.2)
