### ISSUE TITLE
Nullpointer using named query when there are nested docs

### ISSUE THREAD

**Issue by tstibbs** [elastic/elasticsearch#15949]
It is possible for a null pointer to happen when using a named query when you also have nested docs (seen on 1.4.3, I can't reproduce on 2.1.1 but given the number of things that have to be in place to reproduce I can't be that confident that it doesn't exist somewhere in the latest version).

A script to reproduce it can be found here: https://gist.github.com/tstibbs/92de2206531ca37e0764

The last command in the gist is a search request that should result in a null pointer, I see something like the following in the logs:

    [2016-01-12 16:51:30,174][DEBUG][action.search.type       ] [Black Fox] [myindex][0], node[WYV4NA6SRNyRXepgS8QEQQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@43cc9843]
    java.lang.NullPointerException
        at org.apache.lucene.search.DisjunctionScorer.advance(DisjunctionScorer.java:155)
        at org.apache.lucene.search.ConstantScoreQuery$ConstantScorer.advance(ConstantScoreQuery.java:278)
        at org.elasticsearch.search.fetch.matchedqueries.MatchedQueriesFetchSubPhase.addMatchedQueries(MatchedQueriesFetchSubPhase.java:108)
        at org.elasticsearch.search.fetch.matchedqueries.MatchedQueriesFetchSubPhase.hitExecute(MatchedQueriesFetchSubPhase.java:80)
        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:211)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:372)
        at org.elasticsearch.search.action.SearchServiceTransportAction$11.call(SearchServiceTransportAction.java:333)
        at org.elasticsearch.search.action.SearchServiceTransportAction$11.call(SearchServiceTransportAction.java:330)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
    [2016-01-12 16:51:30,174][DEBUG][action.search.type       ] [Black Fox] All shards failed for phase: [query_fetch]

I'm not sure if everything in the script is strictly required, but the following three things all seem to be required in order to reproduce it:
* A large number of (possibly empty) documents – see org.apache.lucene.search.ConstantScoreAutoRewrite:91.
* Multiple matching docs on the same shard.
* Multiple matching documents that have nested children – the nested docs cause issues in [MatchedQueriesFetchSubPhase](https://github.com/elastic/elasticsearch/blob/1.4/src/main/java/org/elasticsearch/search/fetch/matchedqueries/MatchedQueriesFetchSubPhase.java#L108) where the filterIterator can be advanced beyond NO_MORE_DOCS (I’m not sure if that’s allowed or not, but the org.apache.lucene.search.DisjunctionScorer.advance method assumes it isn’t).

**Comment by clintongormley** [comment]
I'm able to reproduce this in 1.7.3, but not in 2.0.0  or beyond.  @jpountz @martijnvg do you know for sure whether this has been fixed?

**Comment by jpountz** [comment]
I don't know when it was fixed but I think I found the bug: in 1.7 MatchedQueriesFetchSubPhase might call DocIdSetIterator.advance after it already returned NO_MORE_DOCS, which is illegal.

**Comment by clintongormley** [comment]
Is this no longer the case in 2.x? In which case we can close?

**Comment by jpountz** [comment]
Nope the code in 2.x is fine. Do we want to get this fixed in 1.7?

**Comment by clintongormley** [comment]
@jpountz depends how big a job it is i suppose?

**Comment by jpountz** [comment]
It looks simple. I'll give it a try and give up if it's more complicated than I expected.

**Comment by jpountz** [comment]
Fixed via #15962
