### ISSUE TITLE
Loss data while using bulk request to create a new index at first time

### ISSUE THREAD

**Issue by yzprofile** [elastic/elasticsearch#15961]
Version: 2.1.1, Build: 40e2c53/2015-12-15T13:05:55Z, JVM: 1.8.0_60

```json
message.json

{"index":{"_index":"test","_type":"message","_id":"1"}}
{"integer":1}
{"index":{"_index":"test","_type":"message","_id":"2"}}
{"integer":1.0}

```

```bash
# 1. Delete every thing
curl -XDELETE "http://localhost:9200/*"

# 2. Bulk request
curl -s -XPOST localhost:9200/_bulk --data-binary @message.json

```

```json
{
    "errors": true,
    "items": [
        {
            "index": {
                "_id": "1",
                "_index": "test",
                "_type": "message",
                "error": {
                    "reason": "Merge failed with failures {[mapper [integer] of different type, current_type [double], merged_type [long]]}",
                    "type": "merge_mapping_exception"
                },
                "status": 400
            }
        },
        {
            "index": {
                "_id": "2",
                "_index": "test",
                "_shards": {
                    "failed": 0,
                    "successful": 1,
                    "total": 2
                },
                "_type": "message",
                "_version": 1,
                "status": 201
            }
        }
    ],
    "took": 40
}
```

```bash
[2016-01-14 01:25:30,179][INFO ][cluster.metadata         ] [Swarm] [test] deleting index
[2016-01-14 01:25:31,405][INFO ][cluster.metadata         ] [Swarm] [test] creating index, cause [auto(bulk api)], templates [], shards [5]/[1], mappings [message]
[2016-01-14 01:25:31,425][INFO ][cluster.metadata         ] [Swarm] [test] update_mapping [message]
[2016-01-14 01:25:31,428][DEBUG][action.admin.indices.mapping.put] [Swarm] failed to put mappings on indices [[test]], type [message]
MergeMappingException[Merge failed with failures {[mapper [integer] of different type, current_type [double], merged_type [long]]}]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$2.execute(MetaDataMappingService.java:392)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:388)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-01-14 01:25:31,429][DEBUG][action.bulk              ] [Swarm] [test][3] failed to execute bulk item (index) index {[test][message][1], source[{"integer":1}]}
MergeMappingException[Merge failed with failures {[mapper [integer] of different type, current_type [double], merged_type [long]]}]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$2.execute(MetaDataMappingService.java:392)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:388)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

```json
curl "http://localhost:9200/test/_search?pretty"

{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test",
      "_type" : "message",
      "_id" : "1",
      "_score" : 1.0,
      "_source":{"integer":1}
    } ]
  }
}
```

**Comment by jpountz** [comment]
This does not qualify as a data loss given that only one write was acknowledged (see the error in the bulk response).

However there seems to be a problem indeed as the second document should have picked the mapping definition generated by the first document instead of trying to map the field as a double.

**Comment by clintongormley** [comment]
@jpountz These two docs go to different shards, so the second doc was mapped before the first.  If you run this a few times, you'll see the order changing.  Nothing to fix here.

**Comment by jpountz** [comment]
Oh yes indeed!

**Comment by yzprofile** [comment]
```json
POST /test/
{
  "mappings": {
    "_default_": {
      "properties": {
        "integer": {
          "type": "double"
        }
      }
    }
  }
}
```

It will work well if I create mapping before sending bulk request.

And there will not be an error: "merge failed".

If the "double"  support to index "long" data ,  Why don't make it compatible?

Thanks.

**Comment by clintongormley** [comment]
Hmmm this is very tricky.  One shard succeeds in adding a `double` field, then the other tries to add an `integer` field, which causes a merge conflict (because the field already exists and is of a different datatype).

If you were to reindex the integer document, it would be coerced to a double and accepted, but it'd be really hard to add this "retry" logic into the mapping code.  I think there are two practical solutions here:

* map your fields ahead of time, or
* ensure that fields with the same name contain the same datatype (ie pass `1.0` instead of `1`)

**Comment by yzprofile** [comment]
Thanks for your time to explain, Issue close. 

Thanks.
