### ISSUE TITLE
Following error coming after start the ES2.1.1 

### ISSUE THREAD

**Issue by sabarnath** [elastic/elasticsearch#15979]
$ ./elasticsearch 
[2016-01-14 15:18:50,490][INFO ][node                     ] [es_f1_01] version[2.1.1], pid[25850], build[40e2c53/2015-12-15T13:05:55Z]
[2016-01-14 15:18:50,490][INFO ][node                     ] [es_f1_01] initializing ...
Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/plugins/AbstractPlugin
Likely root cause: java.lang.ClassNotFoundException: org.elasticsearch.plugins.AbstractPlugin
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:789)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:789)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:380)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:348)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:109)
	at org.elasticsearch.node.Node.<init>(Node.java:146)
	at org.elasticsearch.node.Node.<init>(Node.java:128)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

**Comment by sabarnath** [comment]
Note : i have added my own plugins too.

**Comment by dadoonet** [comment]
What happens if you don't install your plugin?
Are you using the official distribution? Or are you building your own elasticsearch version?

**Comment by sabarnath** [comment]
yes . I tried without our plugins we face some other issues,

 like below
Note : We are upgrade the 1.5.1 into 2.1.1 , I just copied existing(1.5.1) data folder into current(2.1.1) version

[2016-01-14 15:51:50,734][ERROR][gateway                  ] [es_f1_01] failed to read local state, exiting...
java.lang.IllegalStateException: unable to upgrade the mappings for the index [medzo_vendor_thing], reason: [Mapper for [payload] conflicts with existing mapping in other types[mapper [payload.explanation] has different [store] values, mapper [payload.explanation] has different [omit_norms] values, cannot change from disable to enabled, mapper [payload.explanation] has different [analyzer]]]
	at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.checkMappingsCompatibility(MetaDataIndexUpgradeService.java:339)
	at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.upgradeIndexMetaData(MetaDataIndexUpgradeService.java:116)
	at org.elasticsearch.gateway.GatewayMetaState.pre20Upgrade(GatewayMetaState.java:228)
	at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:87)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:56)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:887)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
	at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:887)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:880)
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:46)
	at org.elasticsearch.node.Node.<init>(Node.java:200)
	at org.elasticsearch.node.Node.<init>(Node.java:128)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.lang.IllegalArgumentException: Mapper for [payload] conflicts with existing mapping in other types[mapper [payload.explanation] has different [store] values, mapper [payload.explanation] has different [omit_norms] values, cannot change from disable to enabled, mapper [payload.explanation] has different [analyzer]]
	at org.elasticsearch.index.mapper.MapperService.checkNewMappersCompatibility(MapperService.java:363)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:319)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:265)
	at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.checkMappingsCompatibility(MetaDataIndexUpgradeService.java:333)
	... 39 more

**Comment by sabarnath** [comment]
Seems , We had own analyzer in setting of 1.5.1 not supporting current version .

Following  error mapper : mapper [payload.explanation]

"explanation": {

    "store": true,
    "norms": {
        "enabled": false
    },
    "analyzer": "vmWhitespaceAnalyzer",
    "type": "string"

}
----------------------------------------------------------
See this is our own custom analyzer : 

"vmWhitespaceAnalyzer":{
                    "type":"pattern",
                    "flags":"DOTALL",
                    "lowercase":"true",
                    "pattern":"\\s+",
                    "stopwords":"_none_"
                }

**Comment by dadoonet** [comment]
So without your plugin, elasticsearch is able to go further than:

```
[2016-01-14 15:18:50,490][INFO ][node ] [es_f1_01] initializing ...
```

As I can now see:

```
[2016-01-14 15:51:50,734][ERROR][gateway ] [es_f1_01] failed to read local state, exiting...
```

Which happens after plugin initialization.

So I'm closing this ticket because as you can see your plugin seems to be incorrect here. May be it was not upgraded???
Feel free to follow up on discuss.elastic.co.

About the other issue you are seeing, I'd also recommend asking on discuss as we and the community can better help you there.
