### ISSUE TITLE
Setting invalid codec causes shard to keep failing and stuck in initializing state

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#16032]
On ES 2.1.1.  Ran into this when trying to verify if a setting has persisted.  In this case, I am purposely setting the codec to an invalid codec name `best_compression1` instead of `best_compression`:

```
POST /largeevent/_close
PUT /largeevent/_settings
{
  "index.codec":"best_compression1"
}
POST /largeevent/_open
GET /largeevent/_settings
```

As soon as, I reopen the index after making the setting change, the shard gets into a failure loop trying to initialize the shard and will not start up.

```
[2016-01-15 18:12:18,597][WARN ][cluster.action.shard     ] [node-1] [largeevent][1] received shard failed for [largeevent][1], node[O373snrkTTGclRFL0t7H5g], [P], v[1553], s[INITIALIZING], a[id=w3VoZACfQKq_QcsDGLaZ3Q], unassigned_info[[reason=ALLOCATION_FAILED], at[2016-01-16T02:12:18.563Z], details[failed recovery, failure IndexShardRecoveryException[failed recovery]; nested: IllegalArgumentException[failed to find codec [best_compression1]]; ]], indexUUID [JEPoX4QkR_Om-W69VKV6iQ], message [failed recovery], failure [IndexShardRecoveryException[failed recovery]; nested: IllegalArgumentException[failed to find codec [best_compression1]]; ]
[largeevent][[largeevent][1]] IndexShardRecoveryException[failed recovery]; nested: IllegalArgumentException[failed to find codec [best_compression1]];
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: failed to find codec [best_compression1]
	at org.elasticsearch.index.codec.CodecService.codec(CodecService.java:94)
	at org.elasticsearch.index.engine.EngineConfig.getCodec(EngineConfig.java:255)
	at org.elasticsearch.index.engine.InternalEngine.createWriter(InternalEngine.java:1057)
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:150)
	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1408)
	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1403)
	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:906)
	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:883)
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:245)
	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
	... 3 more
```

Will be nice if we can handle this better.

**Comment by clintongormley** [comment]
With the changes coming in #16054 you will be able to close the index, update the settings, and reopen the index.  The continuous failures can only be prevented once we remove Guice.
