### ISSUE TITLE
Attachment mapper plugin: attempting to retrieve stored fields realtime produces incorrect results or exception

### ISSUE THREAD

**Issue by dminkovsky** [elastic/elasticsearch#16073]
Overview (ES 2.1.1):

- Index an attachment-mapped field
- Attempt to retrieve stored sub-fields real time, before refresh
- Observe that:
  - if string-type sub-fields (i.e. `content_type`) are requested, their content is the base-64 encoded attachment
  - if number-type sub-fields (i.e. `content_length`) an exception is thrown and the query fails
- If the refresh interval elapses, the same query succeeds and produces correct results.

---

Mapping

```
"data" : {
  "type" : "attachment",
  "fields" : {
    "content_type" : {
      "type" : "string",
      "store" : true
    },
    "content_length" : {
      "type" : "integer",
      "store" : true
    }
    // rest omitted 
  }
}
```

Using the JS client:

```
es.create({
  index: 'test',
  type: 'attachment',
  parent: 'someID',
  body: {
    data: ''e1xydGYxXGFuc2kNCkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0DQpccGFyIH0="
  }
}).then(
  ({ _id }) => es.get({
    index: 'test',
    type: 'attachment',
    id: _id,
    parent: 'someID',
    fields: ['data.content_type', 'data.content_length']
  })
)
```

Executing this query results in the following exception:

```
[2016-01-19 00:09:22,656][DEBUG][action.get               ] [MODOK] null: failed to execute [get [live][attachment][AVJYSZJK_w5v_dJkuVcb]: routing [AVJYSZIQ_w5v_dJkuVca]]
RemoteTransportException[[MODOK][127.0.0.1:9300][indices:data/read/get[s]]]; nested: NumberFormatException[For input string: "e1xydGYxXGFuc2kNCkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0DQpccGFyIH0="];
Caused by: java.lang.NumberFormatException: For input string: "e1xydGYxXGFuc2kNCkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0DQpccGFyIH0="
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at org.elasticsearch.index.mapper.core.IntegerFieldMapper$IntegerFieldType.value(IntegerFieldMapper.java:161)
        at org.elasticsearch.index.mapper.core.IntegerFieldMapper$IntegerFieldType.value(IntegerFieldMapper.java:124)
        at org.elasticsearch.index.mapper.core.NumberFieldMapper$NumberFieldType.valueForSearch(NumberFieldMapper.java:150)
        at org.elasticsearch.index.get.ShardGetService.innerGet(ShardGetService.java:247)
        at org.elasticsearch.index.get.ShardGetService.get(ShardGetService.java:86)
        at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:101)
        at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:44)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:282)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:275)
```

Performing the same query but only requesting the `data.content_type` stored field yields 

```
'data.content_type': [ 'e1xydGYxXGFuc2kNCkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0DQpccGFyIH0=' ] }
```

as the value of `content_type` in `fields` in the response.

I've read the stored fields documentation and my understanding is that they are not available to realtime APIs like Get. So, I was expecting that for queries requesting stored fields that were submitted before the elapsing of the refresh interval, the fields would simply not be available. (Incidentally, submitting `realtime:true` or `realtime:false` with the request had no effect and I am not sure what this option does.)

**Comment by clintongormley** [comment]
This issue is resolved by using the ingest attachment plugin instead. Closing as the mapper attachment plugin is deprecated
