### ISSUE TITLE
org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?)

### ISSUE THREAD

**Issue by mobidevadmin** [elastic/elasticsearch#16083]
Hello,

I've had such an issue for 3 times now for the last 3 days. For me, It's absolutely random. Have no clues where to start investigating. 

Elasticsearch 2.1 is running on software linux RAID1. Disks are fine (according to S.M.A.R.T.), fsck passes succesfully each time, there are plenty of free disk space. System's dmesg and syslog are clean.

Thanks for help!

[2016-01-19 03:48:29,354][ERROR][index.engine             ] [kibana4] [logstash-2016.01.19][1] failed to merge
org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=9ea446d9 actual=fb46cdc (resource=BufferedChecksumIndexInput(NIOFSIndexInput
(path="/data/elasticsearch2/data/kibana4/nodes/0/indices/logstash-2016.01.19/1/index/_xo.cfs") [slice=_xo_Lucene50_0.doc]))
        at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:335)
        at org.apache.lucene.codecs.CodecUtil.checksumEntireFile(CodecUtil.java:449)
        at org.apache.lucene.codecs.lucene50.Lucene50PostingsReader.checkIntegrity(Lucene50PostingsReader.java:1299)
        at org.apache.lucene.codecs.blocktree.BlockTreeTermsReader.checkIntegrity(BlockTreeTermsReader.java:336)
        at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsReader.checkIntegrity(PerFieldPostingsFormat.java:317)
        at org.apache.lucene.codecs.FieldsConsumer.merge(FieldsConsumer.java:96)
        at org.apache.lucene.index.SegmentMerger.mergeTerms(SegmentMerger.java:193)
        at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:95)
        at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4089)
        at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:3664)
        at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:588)
        at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.doMerge(ElasticsearchConcurrent

**Comment by clintongormley** [comment]
Hi @mobidevadmin 

While we had issues with bad legacy checksums back in 1.4, the only time I've seen reports like this recently has been from real corruption.  It's always possible that some new bug has been introduced, but I think on balance that the likeliest issue is with the file system/hardware.

Could I suggest migrating to a non-raided, locally mounted filesystem and see if the issue disappears?

**Comment by mobidevadmin** [comment]
Hello,

thanks for the response! The migration is possible (and i will most likely go this way) but I have another elasticsearch indices storage on same RAID massive, and it's totally fine, but it's version is 1.7.3. And also other files from same RAID are perfectly fine. Unlike this ELK installation which fails once a day (at night in my case).

**Comment by jpountz** [comment]
For the record, we only added checks that checksums match on merge in 2.0, so it might be that your 1.7 data is corrupted as well but that the corruption has not surfaced yet.

**Comment by mobidevadmin** [comment]
Hi @jpountz,

thanks for the info. Sorry for noobie question, is there a way to check elasticsearch 1.7 for such errors manually?

**Comment by jpountz** [comment]
I think the easier way would be to use the lucene jar that is in the lib directory of elasticsearch (lucene-core-4.x.jar) and use it to run the CheckIndex utility. The command should look something like ```java -cp /usr/share/elasticsearch/lib/lucene-core-4.10.4.jar -ea:org.apache.lucene... org.apache.lucene.index.CheckIndex $datadir/nodes/0/indices/$index/$shard/index/```. Note that it is a bit tedious as it needs to be run for every shard. It might be slow as well given that this command will not only verify checksums but also make sure that the index can actually be read and that its datastructures are consistent with ach other.

**Comment by Lin-Brian** [comment]
Hi  @jpountz   ,
After I used CheckIndex 
WARNING: 4 broken segments (containing 16202693 documents) detected
WARNING: would write new segments file, and 16202693 documents would be lost, if -fix were specified
And -fix it
But my index status is also Unassigned , cant use cluster.reroute API  
`nested: ElasticsearchIllegalArgumentException[[allocate] trying to allocate a primary shard [logstash-2015.12.12][1], which is disabled]; ","status":400}`
How to enable the index?

**Comment by clintongormley** [comment]
@Lin-Brian your index is corrupt.  Either reindex your documents from source or use the -fix option (and lose the corrupted documents).

**Comment by suiyuan2009** [comment]
I use ubuntu to run lucene(not ES), and nfs to mount disk(actually is rocketstor) of macmini. I get this error constantly.

```
Exception in thread "main" org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
        at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:724)
        at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:738)
        at org.apache.lucene.index.IndexWriter.numDocs(IndexWriter.java:1198)
        at xxxx.xxxxx.search.XxxxxxxxIndexer.close(XxxxxxxxIndexer.java:184)
        at xxxx.xxxxx.search.ThreadedXxxxxxxxIndexer.close(ThreadedXxxxxxxxIndexer.java:59)
        at xxxx.xxxxx.search.ThreadedXxxxxxxxIndexer.main(ThreadedXxxxxxxxIndexer.java:136)

Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=51fbdb5c actual=6e964d17 (resource=BufferedChecksumIndexInput(MMapIndexInput(path="/mnt/HPT8_56T/xxxxxxxxx-index/index1/_mq.cfs") [slice=_mq_Lucene50_0.pos]))
        at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:365)
        at org.apache.lucene.codecs.CodecUtil.checksumEntireFile(CodecUtil.java:469)
        at org.apache.lucene.codecs.lucene50.Lucene50PostingsReader.checkIntegrity(Lucene50PostingsReader.java:1286)
        at org.apache.lucene.codecs.blocktree.BlockTreeTermsReader.checkIntegrity(BlockTreeTermsReader.java:336)
        at org.apache.lucene.codecs.perfield.PerFieldPostingsFormat$FieldsReader.checkIntegrity(PerFieldPostingsFormat.java:317)
        at org.apache.lucene.codecs.FieldsConsumer.merge(FieldsConsumer.java:96)
        at org.apache.lucene.index.SegmentMerger.mergeTerms(SegmentMerger.java:211)
        at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:96)
        at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4099)
        at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:3679)
        at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:588)
        at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:626)
```

**Comment by clintongormley** [comment]
@suiyuan2009 Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks

**Comment by suiyuan2009** [comment]
@clintongormley thanks, I will move to the forum
