### ISSUE TITLE
NullPointerException during Query phase 

### ISSUE THREAD

**Issue by hydrogen18** [elastic/elasticsearch#16123]
Hi, I am getting the following error from the `elasticsearch-ruby` gem while query'ing elasticsearch. I am using JRuby-1.7.22 

```
Elasticsearch::Transport::Transport::Errors::InternalServerError: [500] {"error":{"root_cause":[{"type":"null_pointer_exception","reason":null}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query_fetch","grouped":true,"failed_shards":[{"shard":0,"index":"ct_80e958881295065b_language_packs","node":"b2ol3POOSpiYCeD94ZCQuA","reason":{"type":"null_pointer_exception","reason":null}}]},"status":500}
    /home/ericu/.rvm/gems/jruby-1.7.22@community/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/base.rb:146:in `__raise_transport_error'
    /home/ericu/.rvm/gems/jruby-1.7.22@community/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/base.rb:256:in `perform_request'
    /home/ericu/.rvm/gems/jruby-1.7.22@community/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
    /home/ericu/.rvm/gems/jruby-1.7.22@community/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/client.rb:125:in `perform_request'
    /home/ericu/.rvm/gems/jruby-1.7.22@community/gems/elasticsearch-api-1.0.15/lib/elasticsearch/api/actions/search.rb:167:in `search'
    /home/ericu/community/lib/searchable.rb:1029:in `raw_search'
    /home/ericu/.rvm/gems/jruby-1.7.22@community/gems/statsd-ruby-1.2.1/lib/statsd.rb:232:in `time'
    /home/ericu/community/lib/searchable.rb:1028:in `raw_search'
    /home/ericu/community/lib/searchable.rb:1416:in `raw_search'
    /home/ericu/community/lib/searchable.rb:1530:in `raw_search'
    /home/ericu/community/app/models/search/language_pack.rb:59:in `search'
    test/unit/search/language_pack_test.rb:56:in `LanguagePackTest'
```

Here is the HTTP request + response for the query

```
GET http://localhost:9200/ct_80e958881295065b_language_packs/_search [status:500, request:0.176s, query:N/A]
> {"query":{"filtered":{"filter":{"bool":{"must":[{"term":{"killed":false}},{"term":{"listed":true}}]}},"query":{"match":{"_all":"foo"}}}},"highlight":{"fields":{"name":{},"description":{},"user_name":{}},"pre_tags":["<strong>"],"post_tags":["</strong>"],"require_field_match":false},"size":10}
< {"error":{"root_cause":[{"type":"null_pointer_exception","reason":null}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query_fetch","grouped":true,"failed_shards":[{"shard":0,"index":"ct_80e958881295065b_language_packs","node":"b2ol3POOSpiYCeD94ZCQuA","reason":{"type":"null_pointer_exception","reason":null}}]},"status":500}
[500] {"error":{"root_cause":[{"type":"null_pointer_exception","reason":null}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query_fetch","grouped":true,"failed_shards":[{"shard":0,"index":"ct_80e958881295065b_language_packs","node":"b2ol3POOSpiYCeD94ZCQuA","reason":{"type":"null_pointer_exception","reason":null}}]},"status":500}
````

This is how I made the index

```
PUT http://localhost:9200/ct_80e958881295065b_language_packs [status:200, request:1.079s, query:n/a]
> {"mappings":{"language_pack":{"properties":{"user_id":{"type":"integer"},"current_shared_plugin_version_id":{"type":"integer"},"shared_plugin_category_id":{"type":"integer"},"featured_image_id":{"type":"integer"},"original_current_shared_plugin_version_id":{"type":"integer"},"id":{"type":"integer","index":"not_analyzed"},"name":{"type":"string","analyzer":"snowball","boost":2.0},"description":{"type":"string","analyzer":"snowball"},"created_at":{"type":"date"},"updated_at":{"type":"date"},"downloads":{"type":"integer"},"download_count":{"type":"integer"},"times_rated":{"type":"integer"},"avg_rating":{"type":"float"},"user_name":{"type":"string","analyzer":"lowercase_keyword"},"killed":{"type":"boolean"},"public":{"type":"boolean"},"min_app_version":{"type":"string"},"max_app_version":{"type":"string"},"min_app_version_integer":{"type":"integer"},"max_app_version_integer":{"type":"integer"},"extension_type":{"type":"string"},"extension_category":{"type":"string"},"icon_small":{"type":"string","index":"not_analyzed"},"icon_medium":{"type":"string","index":"not_analyzed"},"icon_large":{"type":"string","index":"not_analyzed"},"url":{"type":"string","index":"not_analyzed"},"last_update":{"type":"date"},"featured":{"type":"boolean"},"listed":{"type":"boolean"},"taxon_names":{"type":"string"}}}},"settings":{"analysis":{"analyzer":{"autocomplete_indexing":{"tokenizer":"whitespace","filter":["lowercase","word_delimiter","autocomplete_filter"]},"autocomplete_search":{"tokenizer":"whitespace","filter":["lowercase","word_delimiter","truncate"]},"keyword_only":{"type":"custom","tokenizer":"keyword","filter":["trim"]},"lowercase_keyword":{"type":"custom","tokenizer":"keyword","filter":["lowercase"]},"autocomplete":{"type":"custom","tokenizer":"keyword","filter":["lowercase","keyword_filter"]},"letters":{"type":"custom","tokenizer":"letter","filter":["lowercase"],"char_filter":["html_strip"]},"standard_no_html":{"type":"standard","char_filter":["html_strip"]},"snowball_plus":{"tokenizer":"standard","filter":["standard","lowercase","stop","word_delimiter","snowball"]}},"filter":{"autocomplete_filter":{"type":"edge_ngram","min_gram":1,"max_gram":20},"synonym":{"type":"synonym","ignore_case":"true","synonyms":["computer, pc, desktop, workstation","laptop, notebook","ram, memory","cpu, processor","gpu, graphics card","hdd, hard drive","ssd, solid state drive"]},"keyword_filter":{"type":"edge_ngram","min_gram":3,"max_gram":20}}},"index":{"number_of_replicas":0,"number_of_shards":1}}}
< {"acknowledged":true}
```

Here is what I could find in my `elasticsearch.log`

```
RemoteTransportException[[Emma Frost][127.0.0.1:9300][indices:data/read/search[phase/query+fetch]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: NullPointerException;
Caused by: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: NullPointerException;
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:343)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:106)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:363)
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:467)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:392)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:389)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.apache.lucene.index.OrdTermState.copyFrom(OrdTermState.java:37)
	at org.apache.lucene.codecs.BlockTermState.copyFrom(BlockTermState.java:56)
	at org.apache.lucene.codecs.lucene50.Lucene50PostingsFormat$IntBlockTermState.copyFrom(Lucene50PostingsFormat.java:475)
	at org.apache.lucene.codecs.blocktree.SegmentTermsEnum.seekExact(SegmentTermsEnum.java:1014)
	at org.elasticsearch.common.lucene.all.AllTermQuery$1.scorer(AllTermQuery.java:152)
	at org.elasticsearch.common.lucene.all.AllTermQuery$1.scorer(AllTermQuery.java:102)
	at org.apache.lucene.search.Weight.bulkScorer(Weight.java:135)
	at org.apache.lucene.search.BooleanWeight.booleanScorer(BooleanWeight.java:201)
	at org.apache.lucene.search.BooleanWeight.bulkScorer(BooleanWeight.java:233)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:769)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:486)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:324)
	... 10 more
[2016-01-20 07:53:09,790][DEBUG][action.search.type       ] [Emma Frost] All shards failed for phase: [query_fetch]
RemoteTransportException[[Emma Frost][127.0.0.1:9300][indices:data/read/search[phase/query+fetch]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: NullPointerException;
Caused by: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: NullPointerException;
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:343)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:106)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:363)
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:467)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:392)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:389)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.apache.lucene.index.OrdTermState.copyFrom(OrdTermState.java:37)
	at org.apache.lucene.codecs.BlockTermState.copyFrom(BlockTermState.java:56)
	at org.apache.lucene.codecs.lucene50.Lucene50PostingsFormat$IntBlockTermState.copyFrom(Lucene50PostingsFormat.java:475)
	at org.apache.lucene.codecs.blocktree.SegmentTermsEnum.seekExact(SegmentTermsEnum.java:1014)
	at org.elasticsearch.common.lucene.all.AllTermQuery$1.scorer(AllTermQuery.java:152)
	at org.elasticsearch.common.lucene.all.AllTermQuery$1.scorer(AllTermQuery.java:102)
	at org.apache.lucene.search.Weight.bulkScorer(Weight.java:135)
	at org.apache.lucene.search.BooleanWeight.booleanScorer(BooleanWeight.java:201)
	at org.apache.lucene.search.BooleanWeight.bulkScorer(BooleanWeight.java:233)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:769)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:486)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:324)
	... 10 more
[2016-01-20 07:53:09,790][INFO ][rest.suppressed          ] /ct_a26d4338e39cc61b_language_packs/_search Params: {index=ct_a26d4338e39cc61b_language_packs}
Failed to execute phase [query_fetch], all shards failed; shardFailures {[5yggsqv3SuWB2EiQ2YFCsw][ct_a26d4338e39cc61b_language_packs][0]: RemoteTransportException[[Emma Frost][127.0.0.1:9300][indices:data/read/search[phase/query+fetch]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: NullPointerException; }
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:228)
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:174)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:821)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:799)
	at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:361)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: ; nested: NullPointerException;
	at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:382)
	at org.elasticsearch.action.search.SearchPhaseExecutionException.guessRootCauses(SearchPhaseExecutionException.java:152)
	at org.elasticsearch.action.search.SearchPhaseExecutionException.getCause(SearchPhaseExecutionException.java:99)
	at java.lang.Throwable.printStackTrace(Throwable.java:665)
	at java.lang.Throwable.printStackTrace(Throwable.java:721)
	at org.apache.log4j.DefaultThrowableRenderer.render(DefaultThrowableRenderer.java:60)
	at org.apache.log4j.spi.ThrowableInformation.getThrowableStrRep(ThrowableInformation.java:87)
	at org.apache.log4j.spi.LoggingEvent.getThrowableStrRep(LoggingEvent.java:413)
	at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:313)
	at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.elasticsearch.common.logging.log4j.Log4jESLogger.internalInfo(Log4jESLogger.java:125)
	at org.elasticsearch.common.logging.support.AbstractESLogger.info(AbstractESLogger.java:90)
	at org.elasticsearch.rest.BytesRestResponse.convert(BytesRestResponse.java:131)
	at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:96)
	at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:87)
	at org.elasticsearch.rest.action.support.RestActionListener.onFailure(RestActionListener.java:60)
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.raiseEarlyFailure(TransportSearchTypeAction.java:316)
	... 10 more
Caused by: java.lang.NullPointerException
	at org.apache.lucene.index.OrdTermState.copyFrom(OrdTermState.java:37)
	at org.apache.lucene.codecs.BlockTermState.copyFrom(BlockTermState.java:56)
	at org.apache.lucene.codecs.lucene50.Lucene50PostingsFormat$IntBlockTermState.copyFrom(Lucene50PostingsFormat.java:475)
	at org.apache.lucene.codecs.blocktree.SegmentTermsEnum.seekExact(SegmentTermsEnum.java:1014)
	at org.elasticsearch.common.lucene.all.AllTermQuery$1.scorer(AllTermQuery.java:152)
	at org.elasticsearch.common.lucene.all.AllTermQuery$1.scorer(AllTermQuery.java:102)
	at org.apache.lucene.search.Weight.bulkScorer(Weight.java:135)
	at org.apache.lucene.search.BooleanWeight.booleanScorer(BooleanWeight.java:201)
	at org.apache.lucene.search.BooleanWeight.bulkScorer(BooleanWeight.java:233)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:769)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:486)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:324)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:106)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:363)
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:467)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:392)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:389)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	... 3 more
```

Here is what my elasticsearch version:

```
[ericu-destroyer-of-worlds] community$ curl localhost:9200
{
  "name" : "Savage Steel",
  "cluster_name" : "ericu-dow-es",
  "version" : {
    "number" : "2.1.1",
    "build_hash" : "40e2c53a6b6c2972b3d13846e450e66f4375bd71",
    "build_timestamp" : "2015-12-15T13:05:55Z",
    "build_snapshot" : false,
    "lucene_version" : "5.3.1"
  },
  "tagline" : "You Know, for Search"
}

```

If you need additional information please let me know, this is easy to reproduce.

**Comment by jpountz** [comment]
Fixed via #15506. A release containing this fix should be out soon.
