### ISSUE TITLE
geo_point ignore ignore_malformed setting

### ISSUE THREAD

**Issue by yijui** [elastic/elasticsearch#16137]
even with enable `ignore_malformed` on mapping
```
"geoip_coordinate" : {
    "type" : "geo_point",
    "ignore_malformed" : true
},
```
Bulk insert(by fluentd elasticsearch plugin) something like`"geoip_coordinate":"-,-"`still throw exception
```
[2016-01-20 12:05:09,274][DEBUG][action.bulk              ] [my server name] [my index name][2] failed to execute bulk item (index) index {[my index name][nginx][AVJdNRawFNa9of9WENEs], source[{"request_time":"0
.500","remote_addr":"172.0.0.1","server_port":"8080","geoip_coordinate":"-,-","@timestamp":"2016-0
1-20T08:21:26+08:00"}]}
MapperParsingException[failed to parse]; nested: NumberFormatException[For input string: "-"];
        at org.elasticsearch.index.mapper.DocumentParser.innerParseDocument(DocumentParser.java:159)
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:79)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:304)
        at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:516)
        at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:507)
        at org.elasticsearch.action.support.replication.TransportReplicationAction.prepareIndexOperationOnPrimary(TransportReplicationAction.java:1052)
        at org.elasticsearch.action.support.replication.TransportReplicationAction.executeIndexRequestOnPrimary(TransportReplicationAction.java:1060)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:338)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:131)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.performOnPrimary(TransportReplicationAction.java:579)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase$1.doRun(TransportReplicationAction.java:452)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "-"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at org.elasticsearch.common.geo.GeoPoint.resetFromString(GeoPoint.java:71)
        at org.elasticsearch.index.mapper.geo.GeoPointFieldMapper.parsePointFromString(GeoPointFieldMapper.java:694)
        at org.elasticsearch.index.mapper.geo.GeoPointFieldMapper.parse(GeoPointFieldMapper.java:669)
        at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:314)
        at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:441)
        at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:267)
        at org.elasticsearch.index.mapper.DocumentParser.innerParseDocument(DocumentParser.java:127)
        ... 14 more
```

**Comment by jasontedor** [comment]
Closed by 3651854bf6d0b1e9fb4ad8a954f476ba9f6df367.
