### ISSUE TITLE
If use an unknown analyzer es 2.1.1 throw  NullPointerException

### ISSUE THREAD

**Issue by node** [elastic/elasticsearch#16150]
When I try to visit http://my-es-host:9200/_analyze?text=NBA 2K&analyzer=ik  everything is OK, but when I change "analyzer=ik" to "analyzer=blahblahblah" , there is a NullPointerException.  Maybe an exception named "UnknownAnalyzerException"  is better ?  If  other guys meet this NullPointerException , actually they can not understand what to happen .

```
  [2016-01-21 22:53:52,836][ERROR][transport                ] [es2-181-9500] failed to handle exception for action [indices:admin/analyze[s]], handler [org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$1@43726337]
java.lang.NullPointerException
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.perform(TransportSingleShardAction.java:195)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.access$700(TransportSingleShardAction.java:115)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$1.handleException(TransportSingleShardAction.java:174)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:821)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:799)
	at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:361)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by clintongormley** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/15447
