### ISSUE TITLE
Snapshot to Azure Blob-storage is failing with IndexShardSnapshotFailedException (nested: IOException; nested: StorageException)

### ISSUE THREAD

**Issue by tejasavora** [elastic/elasticsearch#16158]
I am trying to take a snapshot of our existing indices to Azure Cloud Storage and it is failing with `IndexShardSnapshotFailedException (nested: IOException; nested: StorageException)`

We are using:
`ES Version: 2.1.1`
`Cloud-Azure Version: Latest (2.1.1)` - installed using `plugin install cloud-azure`

Configuration in `elasticsearch.yml` is:
```
cloud:
    azure:
        storage:
            account: "azurecloudstoragenameXXX"
            key: "azurecloudstoragekeyXXX"
```

I am trying to create a new repository using following:
```
PUT _snapshot/onazure?verify=false
{
  "type" : "azure",
  "settings" : {
    "container" : "esbackup",
    "compressed" : true
  }
}
```

Once the repository has been created, I am trying to take a snapshot using following:
```
PUT _snapshot/onazure/snapshot-1-01212016-1920
{
  "indices": [
    "index1",
    "index2",
    "index3",
    "index4"
  ]
}
```

Every time, I am trying to take a snapshot, it is failing with the following exception and fails to take a snapshot. Exception:
```
[2016-01-21 19:19:03,328][WARN ][snapshots                ] [node-1] [[index1][1]] [onazure:snapshot-1-01212016-1920] failed to create snapshot
[index1][[index1][1]] IndexShardSnapshotFailedException[Failed to perform snapshot (index files)]; nested: IOException; nested: StorageException[Value for one of the query parameters specified in the request URI is invalid.];
	at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.snapshot(BlobStoreIndexShardRepository.java:606)
	at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository.snapshot(BlobStoreIndexShardRepository.java:191)
	at org.elasticsearch.snapshots.SnapshotShardsService.snapshot(SnapshotShardsService.java:340)
	at org.elasticsearch.snapshots.SnapshotShardsService.access$200(SnapshotShardsService.java:76)
	at org.elasticsearch.snapshots.SnapshotShardsService$1.doRun(SnapshotShardsService.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException
	at com.microsoft.azure.storage.core.Utility.initIOException(Utility.java:598)
	at com.microsoft.azure.storage.blob.BlobOutputStream$1.call(BlobOutputStream.java:374)
	at com.microsoft.azure.storage.blob.BlobOutputStream$1.call(BlobOutputStream.java:358)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: com.microsoft.azure.storage.StorageException: Value for one of the query parameters specified in the request URI is invalid.
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:162)
	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:307)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:177)
	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadBlockInternal(CloudBlockBlob.java:714)
	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadBlock(CloudBlockBlob.java:686)
	at com.microsoft.azure.storage.blob.BlobOutputStream$1.call(BlobOutputStream.java:362)
	... 7 more
[2016-01-21 19:19:04,407][INFO ][snapshots                ] [node-1] snapshot [onazure:snapshot-1-01212016-1920] is done
```

I tried running the snapshot with only one index which has almost (250 GB) of data, and it is still failing.

However, if I use an index (individually or in group while taking a snapshot) which is almost ~5MB in size, I do not get any exception from log. It says: snapshot is done - however, if I check the `esbackup` container underneath the blob storage, it does not contain any blobs.

Also, tried with `"compressed": false` setting and it is not working with that setting as well.

**Comment by clintongormley** [comment]
@dadoonet any idea what is going on here?

**Comment by dadoonet** [comment]
I have no idea. Never seen this message from Azure before. I know they have strict policy regarding naming but I don't see anything wrong here.
I need to reproduce it locally. Assigning to myself.

**Comment by dadoonet** [comment]
@tejasavora Could you please run that again and add in `logging.yml` file:

```yml
cloud.azure.storage: TRACE
```

Or send

```
PUT /_cluster/settings
{
    "transient" : {
        "logger.cloud.azure.storage" : "TRACE"
    }
}
```

Then do the same operation again and paste the logs on gist.github.com or here if not too big?
If you have some critical data inside your logs (like credentials), feel free to hide them.

Thanks.

**Comment by dadoonet** [comment]
No further news. Closing. Feel free to reopen if you can come with more information.
