### ISSUE TITLE
NPE when query if we have boost in the mapping

### ISSUE THREAD

**Issue by medcl** [elastic/elasticsearch#16220]
Hi,
here is the reproduce:
```
curl -XDELETE http://localhost:9200/index

curl -XPUT http://localhost:9200/index

curl -XPOST http://localhost:9200/index/fulltext/_mapping -d'
{
    "fulltext": {
        "properties": {
            "content": {
                "type": "string",
                "boost": 8
            }
        }
    }
}'

curl -XPOST http://localhost:9200/index/fulltext/1 -d'
{"content":"test"}
'

curl -XGET http://localhost:9200/index/_search?q=test


curl -XPOST http://localhost:9200/index/_search -d'
{
  "query": {
    "term": {
      "_all": "test"
    }
  }
}'
```

```
{"took":10,"timed_out":false,"_shards":{"total":5,"successful":4,"failed":1,"failures":[{"shard":3,"index":"index","node":"phYI6RmCSLu8VWrVeOSCow","reason":{"type":"null_pointer_exception","reason":null}}]},"hits":{"total":0,"max_score":null,"hits":[]}}
```

here is the error in the console
```
[2016-01-26 15:54:36,104][DEBUG][action.search.type       ] [Rodstvow] [index][3], node[phYI6RmCSLu8VWrVeOSCow], [P], v[2], s[STARTED], a[id=yCs33OxKRmycU_mPfEZ5Mg]: Failed to execute [org.elasticsearch.action.search.SearchRequest@1d24fcc4]
RemoteTransportException[[Rodstvow][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: NullPointerException;
Caused by: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: NullPointerException;
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:343)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:106)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:363)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:375)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.apache.lucene.index.OrdTermState.copyFrom(OrdTermState.java:37)
	at org.apache.lucene.codecs.BlockTermState.copyFrom(BlockTermState.java:56)
	at org.apache.lucene.codecs.lucene50.Lucene50PostingsFormat$IntBlockTermState.copyFrom(Lucene50PostingsFormat.java:475)
	at org.apache.lucene.codecs.blocktree.SegmentTermsEnum.seekExact(SegmentTermsEnum.java:1014)
	at org.elasticsearch.common.lucene.all.AllTermQuery$1.scorer(AllTermQuery.java:152)
	at org.elasticsearch.common.lucene.all.AllTermQuery$1.scorer(AllTermQuery.java:102)
	at org.apache.lucene.search.Weight.bulkScorer(Weight.java:135)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:769)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:486)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:324)
	... 10 more
```

but this works:
```
curl -XGET http://localhost:9200/index/_search\?q\=content:test
```

but if we remove the ```"boost": 8``` from mapping, the NPE is gone.

**Comment by jimferenczi** [comment]
This is fixed by #15506. The release with the fix is coming soon.
