### ISSUE TITLE
Elasticsearch failed to create index after upgradation to 2.1.1 

### ISSUE THREAD

**Issue by hiteshmahajan** [elastic/elasticsearch#16283]
[logstash-2016.01.28] failed to create
MapperParsingException[Failed to parse mapping [_default_]: Mapping definition for [geoip] has unsupported parameters:  [path : full]]; nested: MapperParsingException[Mapping definition for [geoip] has unsupported parameters:  [path : full]];
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:369)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:388)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by hiteshmahajan** [comment]
Its resolved, added template_overwrite => true to conf file.

**Comment by lengendary** [comment]
where to add added template_overwrite => true  ? can u show me the complete conf file? thank u very much
