### ISSUE TITLE
Use es2.1.1 and meet many thread waiting all the same (not blocked)

### ISSUE THREAD

**Issue by node** [elastic/elasticsearch#16287]
Actually I use es1.3 and then es 1.7 , but meet many threads waiting. So I read several issues here , like 
#10766 , #10940 , #11467 , #10704 , then I read this commit https://github.com/kimchy/elasticsearch/commit/fc483a7cbff03de07cf96b46ec00a8aa6ef16002 (Automatically thread client based action listeners), hope this will be fix in es 2.0 + .  But when I upgrade to es 2.1.1 , meet the same thread waiting : 

```
"catalina-exec-35" daemon prio=10 tid=0x00007fdb08020800 nid=0x887a waiting on condition [0x00007fdabedeb000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000007f0ca71c8> (a org.elasticsearch.common.util.concurrent.BaseFuture$Sync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:994)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
        at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:276)
        at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:116)
        at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:42)
        
        ... here is my code to invoke search api of es
        
        at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.web.servlet.mvc.multiaction.MultiActionController.invokeNamedMethod(MultiActionController.java:471)
```
The whole thread dump is here: 
https://gist.github.com/node/773dc44273d0c78680ed

So how can I fix this ? Is this only an issues about es transport client ?

**Comment by clintongormley** [comment]
Could you provide the code that you are using to run your search requests?

**Comment by node** [comment]
@clintongormley  here is it:
```
SearchResponse response = esClient
                .prepareSearch(esManager.getIndexName())
                .setTypes(esManager.getIndexType())
                .setSearchType(SearchType.DFS_QUERY_THEN_FETCH)
                .setQuery(mmQuery).setPostFilter(andSearchFilter)
                .setTrackScores(true)
                .setMinScore(MyConst.SEARCH_ES_MINSCORE)
                .addSort(SortBuilders.scoreSort())
                .addSort("official", SortOrder.DESC)
                .addSort("downloadCount", SortOrder.DESC)
                .setFrom(pageFrom).setSize(pageSize)
                .setExplain(true).execute().actionGet();

        SearchHits hits = response.getHits();
```
And esClient is from 
```
esClient = TransportClient.builder().settings(settings).build();
```
And mmQuery is MultiMatchQueryBuilder object, and andSearchFilter is a BoolQueryBuilder object.

**Comment by clintongormley** [comment]
it sounds like you are overloading your cluster.  Check the size of the queue in the search thread pool.  I think the forum is probably a better place to continue this discussion as it doesn't sound like a bug: http://discuss.elastic.co/

**Comment by node** [comment]
Thanks all the same. @clintongormley
