### ISSUE TITLE
Some questions about Tribe node log 

### ISSUE THREAD

**Issue by zcola** [elastic/elasticsearch#16302]
Two clusters are to be installed  Marvel plugin, Tribe node also need to install the license plugin, Otherwise, could not connect the two cluster，There have been some quite understand the message log，But Tribe node  can provide the service.

```

[2016-01-29 11:52:35,167][DEBUG][action.admin.indices.create] [elk-etribe01-105] no known master node, scheduling a retry
[2016-01-29 11:52:35,196][DEBUG][action.admin.indices.create] [elk-etribe01-105] no known master node, scheduling a retry

[2016-01-29 11:56:48,030][WARN ][cluster.service          ] [elk-etribe01-105/e100] failed to notify ClusterStateListener
java.lang.ClassCastException: org.elasticsearch.license.plugin.core.LicensesMetaData cannot be cast to org.elasticsearch.license.plugin.core.LicensesMetaData
    at org.elasticsearch.license.plugin.core.LicensesService.clusterChanged(LicensesService.java:462)
    at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:494)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
...


```

**Comment by clintongormley** [comment]
Hi @zcola 

This has been improved in 2.2.0 - the exception now reads:

    IllegalArgumentException[No custom metadata prototype registered for type [licenses], node like missing plugins]; ]
