### ISSUE TITLE
Elasticsearch won't start on Mac OS 10.10.5

### ISSUE THREAD

**Issue by th3m4ri0** [elastic/elasticsearch#16379]
Hi,
I've had a working install of Elasticsearch for some time now and it eventually stopped working.
I uninstalled it then reinstalled it with brew. Here's what happens: 
```
 ct@inferno ~  $ brew uninstall elasticsearch --force
Uninstalling elasticsearch... (50 files, 30.9M)
 ct@inferno ~  $ brew install elasticsearch
==> Downloading https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distributi
Already downloaded: /Library/Caches/Homebrew/elasticsearch-2.1.1.tar.gz
==> Caveats
Data:    /usr/local/var/elasticsearch/elasticsearch_ct/
Logs:    /usr/local/var/log/elasticsearch/elasticsearch_ct.log
Plugins: /usr/local/Cellar/elasticsearch/2.1.1/libexec/plugins/
Config:  /usr/local/etc/elasticsearch/
plugin script: /usr/local/Cellar/elasticsearch/2.1.1/libexec/bin/plugin

To have launchd start elasticsearch at login:
  ln -sfv /usr/local/opt/elasticsearch/*.plist ~/Library/LaunchAgents
Then to load elasticsearch now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.elasticsearch.plist
Or, if you don't want/need launchctl, you can just run:
  elasticsearch
==> Summary
🍺  /usr/local/Cellar/elasticsearch/2.1.1: 50 files, 30.9M, built in 1 second
 ct@inferno ~  $ elasticsearch
[2016-02-02 11:34:03,823][INFO ][node                     ] [Vindaloo] version[2.1.1], pid[15869], build[40e2c53/2015-12-15T13:05:55Z]
[2016-02-02 11:34:03,823][INFO ][node                     ] [Vindaloo] initializing ...
Exception in thread "main" java.lang.IllegalStateException: Unable to initialize plugins
Likely root cause: java.nio.file.NoSuchFileException: /usr/local/var/lib/elasticsearch/plugins/analysis-icu/plugin-descriptor.properties
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:317)
	at java.nio.file.Files.newByteChannel(Files.java:363)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:380)
	at java.nio.file.Files.newInputStream(Files.java:108)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:86)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:302)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:108)
	at org.elasticsearch.node.Node.<init>(Node.java:146)
	at org.elasticsearch.node.Node.<init>(Node.java:128)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```

I've searched for the likely root cause, to no avail.
Any idea ?

**Comment by jasontedor** [comment]
Do you have a stale plugin from an old installation sitting around and have your config pointing to that old plugin directory? That's what it looks like.

```
Likely root cause: java.nio.file.NoSuchFileException: /usr/local/var/lib/elasticsearch/plugins/analysis-icu/plugin-descriptor.properties
```

> I've had a working install of Elasticsearch

What version? If you're coming from the 1.x line, I think the above explanation is what's going on. If not, let us know and we'll investigate further.

**Comment by jasontedor** [comment]
I can replicate your issue confirming that my theory is a good explanation:

```
11:59:34 3d [jason:~] $ brew install elasticsearch17
[...]
11:59:38 3d [jason:~] $ /usr/local/Cellar/elasticsearch17/1.7.4/bin/plugin --install elasticsearch/elasticsearch-analysis-icu/2.7.0
[...]
12:00:10 3d [jason:~] $ elasticsearch
[2016-02-02 12:00:13,537][INFO ][node                     ] [Ka-Zar] version[1.7.4], pid[88711], build[0d3159b/2015-12-15T11:25:18Z]
[2016-02-02 12:00:13,537][INFO ][node                     ] [Ka-Zar] initializing ...
[2016-02-02 12:00:13,603][INFO ][plugins                  ] [Ka-Zar] loaded [analysis-icu], sites []
[2016-02-02 12:00:13,631][INFO ][env                      ] [Ka-Zar] using [1] data paths, mounts [[/ (/dev/disk1)]], net usable_space [104.9gb], net total_space [232.6gb], types [hfs]
[2016-02-02 12:00:15,156][INFO ][node                     ] [Ka-Zar] initialized
[2016-02-02 12:00:15,158][INFO ][node                     ] [Ka-Zar] starting ...
[2016-02-02 12:00:15,242][INFO ][transport                ] [Ka-Zar] bound_address {inet[/127.0.0.1:9300]}, publish_address {inet[/127.0.0.1:9300]}
[2016-02-02 12:00:15,257][INFO ][discovery                ] [Ka-Zar] elasticsearch_jason/69KwMa0fQlSKlymxaASeDw
[2016-02-02 12:00:19,030][INFO ][cluster.service          ] [Ka-Zar] new_master [Ka-Zar][69KwMa0fQlSKlymxaASeDw][...][inet[/127.0.0.1:9300]], reason: zen-disco-join (elected_as_master)
[2016-02-02 12:00:19,046][INFO ][http                     ] [Ka-Zar] bound_address {inet[/127.0.0.1:9200]}, publish_address {inet[/127.0.0.1:9200]}
[2016-02-02 12:00:19,046][INFO ][node                     ] [Ka-Zar] started
[2016-02-02 12:00:19,051][INFO ][gateway                  ] [Ka-Zar] recovered [0] indices into cluster_state
^C[2016-02-02 12:00:26,751][INFO ][node                     ] [Ka-Zar] stopping ...
[2016-02-02 12:00:26,767][INFO ][node                     ] [Ka-Zar] stopped
[2016-02-02 12:00:26,767][INFO ][node                     ] [Ka-Zar] closing ...
[2016-02-02 12:00:26,771][INFO ][node                     ] [Ka-Zar] closed
12:00:26 3d [jason:~] 130 $ brew remove elasticsearch17
Uninstalling /usr/local/Cellar/elasticsearch17/1.7.4... (36 files, 29.7M)
12:00:35 3d [jason:~] $ brew install elasticsearch
[...]
12:00:42 3d [jason:~] $ elasticsearch --path.plugins /usr/local/var/lib/elasticsearch/plugins/
[2016-02-02 12:00:54,171][INFO ][node                     ] [Baron Mordo] version[2.1.1], pid[88898], build[40e2c53/2015-12-15T13:05:55Z]
[2016-02-02 12:00:54,171][INFO ][node                     ] [Baron Mordo] initializing ...
Exception in thread "main" java.lang.IllegalStateException: Unable to initialize plugins
Likely root cause: java.nio.file.NoSuchFileException: /usr/local/var/lib/elasticsearch/plugins/analysis-icu/plugin-descriptor.properties
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:86)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:302)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:108)
        at org.elasticsearch.node.Node.<init>(Node.java:146)
        at org.elasticsearch.node.Node.<init>(Node.java:128)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```

Ideally you should just remove the old plugin directory:

```
$ rm -rf /usr/local/var/lib/elasticsearch/plugins
```

as none of the plugins there will work when upgrading from Elasticsearch 1.x to Elasticsearch 2.x because of a change in the plugin format. But if you have some reason to keep them around, change the config for `path.plugins`.

**Comment by th3m4ri0** [comment]
Works perfectly ! Thank you ! :smile:

**Comment by jasontedor** [comment]
> Works perfectly ! Thank you ! :smile:

Excellent. You're very welcome. :smile:

**Comment by fabiobarboza7** [comment]
> I can replicate your issue confirming that my [theory](https://github.com/elastic/elasticsearch/issues/16379#issuecomment-178682514) is plausible:
> 
> ```
> 11:59:34 3d [jason:~] $ brew install elasticsearch17
> [...]
> 11:59:38 3d [jason:~] $ /usr/local/Cellar/elasticsearch17/1.7.4/bin/plugin --install elasticsearch/elasticsearch-analysis-icu/2.7.0
> [...]
> 12:00:10 3d [jason:~] $ elasticsearch
> [2016-02-02 12:00:13,537][INFO ][node                     ] [Ka-Zar] version[1.7.4], pid[88711], build[0d3159b/2015-12-15T11:25:18Z]
> [2016-02-02 12:00:13,537][INFO ][node                     ] [Ka-Zar] initializing ...
> [2016-02-02 12:00:13,603][INFO ][plugins                  ] [Ka-Zar] loaded [analysis-icu], sites []
> [2016-02-02 12:00:13,631][INFO ][env                      ] [Ka-Zar] using [1] data paths, mounts [[/ (/dev/disk1)]], net usable_space [104.9gb], net total_space [232.6gb], types [hfs]
> [2016-02-02 12:00:15,156][INFO ][node                     ] [Ka-Zar] initialized
> [2016-02-02 12:00:15,158][INFO ][node                     ] [Ka-Zar] starting ...
> [2016-02-02 12:00:15,242][INFO ][transport                ] [Ka-Zar] bound_address {inet[/127.0.0.1:9300]}, publish_address {inet[/127.0.0.1:9300]}
> [2016-02-02 12:00:15,257][INFO ][discovery                ] [Ka-Zar] elasticsearch_jason/69KwMa0fQlSKlymxaASeDw
> [2016-02-02 12:00:19,030][INFO ][cluster.service          ] [Ka-Zar] new_master [Ka-Zar][69KwMa0fQlSKlymxaASeDw][...][inet[/127.0.0.1:9300]], reason: zen-disco-join (elected_as_master)
> [2016-02-02 12:00:19,046][INFO ][http                     ] [Ka-Zar] bound_address {inet[/127.0.0.1:9200]}, publish_address {inet[/127.0.0.1:9200]}
> [2016-02-02 12:00:19,046][INFO ][node                     ] [Ka-Zar] started
> [2016-02-02 12:00:19,051][INFO ][gateway                  ] [Ka-Zar] recovered [0] indices into cluster_state
> ^C[2016-02-02 12:00:26,751][INFO ][node                     ] [Ka-Zar] stopping ...
> [2016-02-02 12:00:26,767][INFO ][node                     ] [Ka-Zar] stopped
> [2016-02-02 12:00:26,767][INFO ][node                     ] [Ka-Zar] closing ...
> [2016-02-02 12:00:26,771][INFO ][node                     ] [Ka-Zar] closed
> 12:00:26 3d [jason:~] 130 $ brew remove elasticsearch17
> Uninstalling /usr/local/Cellar/elasticsearch17/1.7.4... (36 files, 29.7M)
> 12:00:35 3d [jason:~] $ brew install elasticsearch
> [...]
> 12:00:42 3d [jason:~] $ elasticsearch --path.plugins /usr/local/var/lib/elasticsearch/plugins/
> [2016-02-02 12:00:54,171][INFO ][node                     ] [Baron Mordo] version[2.1.1], pid[88898], build[40e2c53/2015-12-15T13:05:55Z]
> [2016-02-02 12:00:54,171][INFO ][node                     ] [Baron Mordo] initializing ...
> Exception in thread "main" java.lang.IllegalStateException: Unable to initialize plugins
> Likely root cause: java.nio.file.NoSuchFileException: /usr/local/var/lib/elasticsearch/plugins/analysis-icu/plugin-descriptor.properties
>         at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
>         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
>         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
>         at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
>         at java.nio.file.Files.newByteChannel(Files.java:361)
>         at java.nio.file.Files.newByteChannel(Files.java:407)
>         at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
>         at java.nio.file.Files.newInputStream(Files.java:152)
>         at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:86)
>         at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:302)
>         at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:108)
>         at org.elasticsearch.node.Node.<init>(Node.java:146)
>         at org.elasticsearch.node.Node.<init>(Node.java:128)
>         at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
>         at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
>         at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
>         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
> Refer to the log for complete error details.
> ```
> 
> Ideally you should just remove the old plugin directory:
> 
> ```
> $ rm -rf /usr/local/var/lib/elasticsearch/plugins
> ```
> 
> as none of the plugins there will work when upgrading from Elasticsearch 1.x to Elasticsearch 2.x because of a change in the plugin format. But if you have some reason to keep them around, change the config for `path.plugins`.

coming from 2021 to say, thank you!
