### ISSUE TITLE
Timeout cloud_azure/15_index_creation/Test the smb_mmap_fs directory wrapper

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#16409]
http://build-us-00.elastic.co/job/es_core_2x_windows-2012-r2/536/

Failure:
```
java.lang.AssertionError: expected [2xx] status code but api [cluster.health] returned [408 Request Timeout] [{"cluster_name":"prepare_release","status":"yellow","timed_out":true,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":1,"active_shards":1,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":1,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":50.0}]
	at __randomizedtesting.SeedInfo.seed([17258535D2F76202:9F71BAEF7C0B0FFA]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.elasticsearch.test.rest.section.DoSection.execute(DoSection.java:103)
	at org.elasticsearch.test.rest.ESRestTestCase.test(ESRestTestCase.java:375)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1660)
```

Sadly it doesn't reproduce.

@dakrone I'm assigning this to you as you have recently added the test.

**Comment by dakrone** [comment]
I pushed a fix for this here: https://github.com/elastic/elasticsearch/commit/59a44b0a012e5046165a553a50cfbc23eeeeb995
