### ISSUE TITLE
'Failed to send ping' and firewall

### ISSUE THREAD

**Issue by marcinkubica** [elastic/elasticsearch#16421]
Got myself firewalled between datacenters (without knowing it) and when adding a node it seemed to just not being able to find anything:

```
[2016-02-03 16:48:46,094][INFO ][node                     ] [ottsc-tiger] stopped
[2016-02-03 16:48:46,094][INFO ][node                     ] [ottsc-tiger] closing ...
[2016-02-03 16:48:46,145][INFO ][node                     ] [ottsc-tiger] closed
[2016-02-03 16:48:47,493][INFO ][node                     ] [ottsc-tiger] version[2.2.0], pid[21119], build[8ff36d1/2016-01-27T13:32:39Z]
[2016-02-03 16:48:47,495][INFO ][node                     ] [ottsc-tiger] initializing ...
[2016-02-03 16:48:48,531][INFO ][plugins                  ] [ottsc-tiger] modules [lang-expression, lang-groovy], plugins [license, marvel-agent], sites []
[2016-02-03 16:48:50,545][INFO ][node                     ] [ottsc-tiger] initialized
[2016-02-03 16:48:50,545][INFO ][node                     ] [ottsc-tiger] starting ...
[2016-02-03 16:48:50,680][INFO ][transport                ] [ottsc-tiger] publish_address {10.72.58.246:9300}, bound_addresses {10.72.58.246:9300}
[2016-02-03 16:48:50,692][INFO ][discovery                ] [ottsc-tiger] ottsc-elastic-large/lk3l2COET7y296byYYT3ZA
[2016-02-03 16:49:00,551][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:49:10,552][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:49:20,553][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:49:20,692][WARN ][discovery                ] [ottsc-tiger] waited for 30s and no initial state was set by the discovery
[2016-02-03 16:49:20,716][INFO ][http                     ] [ottsc-tiger] publish_address {10.72.58.246:9200}, bound_addresses {10.72.58.246:9200}
[2016-02-03 16:49:20,717][INFO ][node                     ] [ottsc-tiger] started
[2016-02-03 16:49:30,553][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:49:40,554][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:49:50,555][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:50:00,556][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:50:10,560][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:50:20,560][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:50:30,561][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:50:40,562][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:50:50,562][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:51:00,563][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:51:10,564][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:51:20,564][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:51:30,566][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:51:40,567][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:51:50,567][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:52:00,568][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:52:10,569][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:52:20,569][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:52:30,570][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:52:40,571][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:52:50,572][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:53:00,572][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:53:10,573][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:53:20,574][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:53:30,574][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:53:40,575][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:53:50,576][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:54:00,576][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:54:10,577][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:54:20,578][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:54:30,579][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:54:40,580][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:54:50,580][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:55:00,581][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:55:10,582][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:55:20,583][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:55:30,583][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:55:40,584][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:55:50,585][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:56:00,585][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:56:10,586][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
[2016-02-03 16:56:20,587][INFO ][marvel.agent.exporter    ] [ottsc-tiger] skipping exporter [default_local] as it isn't ready yet
```

Once punched ports 9300-9400 it suddenly start talking

```
[2016-02-03 16:56:21,573][WARN ][discovery.zen.ping.unicast] [ottsc-tiger] failed to send ping to [{#zen_unicast_2#}{10.88.58.13}{10.88.58.13:9300}]
SendRequestTransportException[[][10.88.58.13:9300][internal:discovery/zen/unicast]]; nested: NodeNotConnectedException[[][10.88.58.13:9300] Node not connected];
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:323)
        at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPingRequestToNode(UnicastZenPing.java:440)
        at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.access$1000(UnicastZenPing.java:83)
        at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$3.run(UnicastZenPing.java:403)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: NodeNotConnectedException[[][10.88.58.13:9300] Node not connected]
        at org.elasticsearch.transport.netty.NettyTransport.nodeChannel(NettyTransport.java:1115)
        at org.elasticsearch.transport.netty.NettyTransport.sendRequest(NettyTransport.java:802)
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:312)
        ... 6 more
[2016-02-03 16:56:21,620][WARN ][discovery.zen.ping.unicast] [ottsc-tiger] failed to send ping to [{#zen_unicast_1#}{10.88.58.12}{10.88.58.12:9300}]
SendRequestTransportException[[][10.88.58.12:9300][internal:discovery/zen/unicast]]; nested: NodeNotConnectedException[[][10.88.58.12:9300] Node not connected];
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:323)
        at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPingRequestToNode(UnicastZenPing.java:440)
        at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.access$1000(UnicastZenPing.java:83)
        at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$3.run(UnicastZenPing.java:403)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: NodeNotConnectedException[[][10.88.58.12:9300] Node not connected]
        at org.elasticsearch.transport.netty.NettyTransport.nodeChannel(NettyTransport.java:1115)
        at org.elasticsearch.transport.netty.NettyTransport.sendRequest(NettyTransport.java:802)
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:312)
        ... 6 more
[2016-02-03 16:56:24,357][INFO ][cluster.service          ] [ottsc-tiger] detected_master {ottsc-elastic-01}{gXG7_pfnSCe6X4sOCJwL2w}{10.88.58.12}{10.88.58.12:9300}, added {{ottsc-elastic-02}{Ll4MtYTjSIuU2z-3Rjf48Q}{10.88.58.13}{10.88.58.13:9300},{ottsc-elastic-01}{gXG7_pfnSCe6X4sOCJwL2w}{10.88.58.12}{10.88.58.12:9300},{kibana-large}{h5cB_G0vTx6z8Ixmgc7ZPw}{10.88.58.10}{10.88.58.10:9300}{data=false, master=false},}, reason: zen-disco-receive(from master [{ottsc-elastic-01}{gXG7_pfnSCe6X4sOCJwL2w}{10.88.58.12}{10.88.58.12:9300}])
[2016-02-03 16:56:24,843][INFO ][license.plugin.core      ] [ottsc-tiger] license [55847aa4-e3bc-4935-84c7-83e20bdead0b] - valid
```

I would expect it will say earlier about ping failure? 

Ta
Marcin

**Comment by clintongormley** [comment]
It says:

    [2016-02-03 16:49:20,692][WARN ][discovery                ] [ottsc-tiger] waited for 30s and no initial state was set by the discovery

Setting it to DEBUG would provide more info, but I don't think we should be warning about every missed ping, no?

What would you change?

**Comment by marcinkubica** [comment]
Hi I would change this message

```[2016-02-03 16:56:21,573][WARN ][discovery.zen.ping.unicast] [ottsc-tiger] failed to send ping to [{#zen_unicast_2#}{10.88.58.13}{10.88.58.13:9300}]```
to be in the log *before* the actual recovery.

Instead it popped in after.

Cheers
Marcin

**Comment by marcinkubica** [comment]
I think current logic is ping failures do pop in log if a node is connected to the cluster, but has issues connecting to some nodes. 

However if it can't join the cluster on start, then it seems like it's not respecting the unicast list and is not reporting connection failures.

**Comment by jasontedor** [comment]
We log failed pings at the trace level, I do not think there is anything that needs to be done here.
