### ISSUE TITLE
plugin permission errors in 2.2.0

### ISSUE THREAD

**Issue by mkelkarbv** [elastic/elasticsearch#16427]
I am trying to write a plugin for ES 2.2.0. When I start elasticsearch with plugin installed, this is what I get -

Likely root cause: java.security.AccessControlException: access denied ("javax.management.MBeanServerPermission" "createMBeanServer")
at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
at java.security.AccessController.checkPermission(AccessController.java:884)
at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:465)
at com.yammer.metrics.reporting.JmxReporter.(JmxReporter.java:388)
at com.yammer.metrics.reporting.JmxReporter.startDefault(JmxReporter.java:340)
at com.yammer.metrics.Metrics.(Metrics.java:20)

This is my plugin-security.policy file -

grant {
permission javax.management.MBeanServerPermission "createMBeanServer";
};

This supposed to work, right?

**Comment by rjernst** [comment]
There is more to do than simply adding the permission. You must wrap the code trying to use the extra permissions with a `AccessController.doPrivileged` block. See https://www.elastic.co/guide/en/elasticsearch/plugins/2.2/plugin-authors.html#_java_security_permissions.

**Comment by rendel** [comment]
Hi @rjernst 

We are facing a similar issue, but with the elasticsearch test framework. We are using `ESIntegTestCase` for our unit tests, and it looks like it does not have the proper file permissions for our test directories. The only way we found so far to be able to run unit tests is to specify our own policy at runtime using `-Djava.security.policy=my_policy`.
You can find more information in my post on discuss: https://discuss.elastic.co/t/permission-denied-error-in-plugin-for-es-2-2-0/40915/4?u=renaud1

**Comment by mrgambal** [comment]
@rjernst this issue is a duplicate for #16459 and it has been already fixed in v2.2.1.
