### ISSUE TITLE
Plugin does not work with ES 2.2.0

### ISSUE THREAD

**Issue by phutchins** [elastic/elasticsearch#16485]
Get complaints about java permissions but adding them doesn't seem to fix...

[2016-02-05 11:39:42,346][WARN ][discovery.gce ] [homer] Exception caught during discovery: access denied ("java.lang.RuntimePermission" "setFactory") java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "setFactory") at java.security.AccessControlContext.checkPermission(AccessControlContext.java:372) at java.security.AccessController.checkPermission(AccessController.java:559) at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) at java.lang.SecurityManager.checkSetFactory(SecurityManager.java:1625) at javax.net.ssl.HttpsURLConnection.setSSLSocketFactory(HttpsURLConnection.java:362) at com.google.api.client.http.javanet.NetHttpTransport.buildRequest(NetHttpTransport.java:145) at com.google.api.client.http.javanet.NetHttpTransport.buildRequest(NetHttpTransport.java:62) at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:863) at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419) at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352) at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469) at org.elasticsearch.cloud.gce.GceComputeServiceImpl$1$1.run(GceComputeServiceImpl.java:94) at org.elasticsearch.cloud.gce.GceComputeServiceImpl$1$1.run(GceComputeServiceImpl.java:90) at java.security.AccessController.doPrivileged(Native Method) 

Glad to provide any information needed to help troubleshoot.

I answered 'y' (yes) to the prompt to add security options to java, also attempted to add them manually. Still no luck. Uninstalled and reinstalled the plugin...

I rolled back to 2.1.1 and it works again...

**Comment by kevinliteon** [comment]
Same for me :+1:

**Comment by nivethav** [comment]
The cloud-gce 2.2.0 works with elasticsearch 2.1.1 as long as no other plugins are installed. Then this is causing the following error : 
** Exception caught during discovery: access denied ("java.lang.RuntimePermission" "setFactory")**

**Comment by clintongormley** [comment]
@jasontedor could you take a look at this please?

**Comment by jasontedor** [comment]
> Get complaints about java permissions but adding them doesn't seem to fix...

@phutchins Where did you add the `setFactory` permission?

**Comment by phutchins** [comment]
@jasontedor I tried the server.policy file and I believe one other place that I can't recall at the moment...

**Comment by jasontedor** [comment]
> I tried the server.policy file and I believe one other place that I can't recall at the moment...

@phutchins Would you be willing to try adding it to `${path.plugins}/cloud-gce/plugin-security.policy` as I think that that is where you'll need to add it (depends on where your plugins are installed)? Can you add

```
permission java.lang.RuntimePermission "setFactory";
```

to the `grant` entries there? If you bump into any other permissions that are needed, add them there too (reading through the [code](https://github.com/google/google-http-java-client/blob/1.20.0/google-http-client/src/main/java/com/google/api/client/http/javanet/NetHttpTransport.java) and the [docs](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/HttpsURLConnection.html), another one that *might* come up is `permission javax.net.ssl.SSLPermission "setHostnameVerifier";`). Please note that adding any additional security permissions is at your own risk. You can read about the [`setFactory` runtime permission](http://download.java.net/jdk7/archive/b123/docs/api/java/lang/RuntimePermission.html) and the *possible* [`setHostNameVerifier` SSL permission](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLPermission.html) but if you report them back here we will do a thorough investigation on them in advance of the next patch release.

**Comment by jasontedor** [comment]
@phutchins I'd like to make sure this can be addressed for a maintenance release. Have you had the opportunity to try the above settings?

**Comment by phutchins** [comment]
Hey @jasontedor, I've not yet but will as soon as I get a chance. Hope to get back to you soon.
