### ISSUE TITLE
Groovy script in aggregation not working in 2.2

### ISSUE THREAD

**Issue by reflection** [elastic/elasticsearch#16487]
Reported problem in 2.0 (#14273), but this time around there are different errors:

Here's the aggregation expressed in elasticsearch-dsl-py (which works fine in 1.x):
```
s.aggs \
  .bucket('hour', 'terms', script= \
          'use(groovy.time.TimeCategory) { \
            new Date(doc["timestamp"].value).format("HH") \
          }', size=0, order={'_term': 'asc'}) \
  .metric('bandwidth', 'sum', field='size') \
    .bucket('action', 'terms', field='action', size=0) \
    .metric('bandwidth', 'sum', field='size')
```
In 2.2 we get this error:
```
es_1          | [2016-02-05 23:09:19,452][DEBUG][action.search.type       ] [Dmitri Bukharin] [356019-20160128][4], node[vJdfzAOUSzySzoEHaePQfg], [P], v[2], s[STARTED], a[id=ynZWRaZdQ6uhnwbsyMD1DA]: Failed to execute [org.elasticsearch.action.search.SearchRequest@496d4b1a] lastShard [true]
es_1          | RemoteTransportException[[Dmitri Bukharin][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: ScriptException[failed to run inline script [use(groovy.time.TimeCategory) {                 new Date(doc["timestamp"].value).format("HH")               }] using lang [groovy]]; nested: MissingPropertyException[No such property: groovy for class: 9bb55a3e15db1c99c3f7f34eb032629ba6109bc4];
es_1          | Caused by: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: ScriptException[failed to run inline script [use(groovy.time.TimeCategory) {                 new Date(doc["timestamp"].value).format("HH")               }] using lang [groovy]]; nested: MissingPropertyException[No such property: groovy for class: 9bb55a3e15db1c99c3f7f34eb032629ba6109bc4];
es_1          | 	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:409)
es_1          | 	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:113)
es_1          | 	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:364)
es_1          | 	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:376)
es_1          | 	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
es_1          | 	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
es_1          | 	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
es_1          | 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
es_1          | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
es_1          | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
es_1          | 	at java.lang.Thread.run(Thread.java:745)
es_1          | Caused by: ScriptException[failed to run inline script [use(groovy.time.TimeCategory) {                 new Date(doc["timestamp"].value).format("HH")               }] using lang [groovy]]; nested: MissingPropertyException[No such property: groovy for class: 9bb55a3e15db1c99c3f7f34eb032629ba6109bc4];
es_1          | 	at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript.run(GroovyScriptEngineService.java:318)
es_1          | 	at org.elasticsearch.search.aggregations.support.values.ScriptBytesValues.setDocument(ScriptBytesValues.java:53)
es_1          | 	at org.elasticsearch.search.aggregations.bucket.terms.StringTermsAggregator$1.collect(StringTermsAggregator.java:80)
es_1          | 	at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:88)
es_1          | 	at org.apache.lucene.search.MultiCollector$MultiLeafCollector.collect(MultiCollector.java:173)
es_1          | 	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:218)
es_1          | 	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:169)
es_1          | 	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39)
es_1          | 	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:821)
es_1          | 	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:535)
es_1          | 	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:384)
es_1          | 	... 10 more
es_1          | Caused by: groovy.lang.MissingPropertyException: No such property: groovy for class: 9bb55a3e15db1c99c3f7f34eb032629ba6109bc4
es_1          | 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
es_1          | 	at org.codehaus.groovy.vmplugin.v7.IndyGuardsFiltersAndSignatures.unwrap(IndyGuardsFiltersAndSignatures.java:177)
es_1          | 	at 9bb55a3e15db1c99c3f7f34eb032629ba6109bc4.run(9bb55a3e15db1c99c3f7f34eb032629ba6109bc4:1)
es_1          | 	at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript$1.run(GroovyScriptEngineService.java:311)
es_1          | 	at java.security.AccessController.doPrivileged(Native Method)
es_1          | 	at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript.run(GroovyScriptEngineService.java:308)
```

**Comment by reflection** [comment]
Nevermind, in 2.2 we either need to disable the new Java Security Manager or whitelist any classes we need.

**Comment by rvalenciano** [comment]
@reflection or anyone, do you have specific steps for whitelist any classes we need.? I'm having issues using groovy.json.JsonOutput.toJson in a script.
