### ISSUE TITLE
Getting Shard failures for a quoted string search query

### ISSUE THREAD

**Issue by apanimesh061** [elastic/elasticsearch#16544]
I am using Elasticsearch 2.2.0.

I have the following schema for the index:

```
{
  "settings" : {
    "index.number_of_shards" : 1,
    "index.similarity.default.type": "BM25"
  }
}
```

I index 5 documents and I even test it in the code as follows:

```
Client testClient = client();
.
. // index the documents here
.
SearchResponse countResponse = testClient.prepareSearch(indexName)
            .setTypes("post").setSize(0).execute().actionGet();
assertHitCount(countResponse, 5L); // this one passes which means all 5 documents were indexed

String singleWord = "Lorem";
String twoWords = "Lorem ipsum";
String quotedPhrase = "\"Lorem ipsum\"";

QueryStringQueryBuilder query = queryStringQuery(quotedPhrase);
query.useDisMax(true);
query.defaultOperator(QueryStringQueryBuilder.Operator.AND);
query.autoGeneratePhraseQueries(true);
query.field("content", 1f);

SearchRequestBuilder request = testClient.prepareSearch(indexName).setTypes("student");
request.setQuery(query);
request.addField("*");
request.setExplain(true);
SearchResponse response = request.execute().actionGet();
assertHitCount(response, 1L);
```

I notice that the query for `quotedPhrase` results in the following errors arbitrarily:

- Shard Failures
```
Failed to execute phase [query_fetch], all shards failed
; shardFailures {[ppHLclgASbiK4nZBBjIYjg][default_index][0]: RemoteTransportException[[node_t1][local[2]][indices:data/read/search[phase/query+fetch]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: AbstractMethodError[org.apache.lucene.search.TwoPhaseIterator.matchCost()F]; }
```
- No hits
```
java.lang.AssertionError: Hit count is 0 but 1 was expected.  Total shards: 9 Successful shards: 8 & 1 shard failures:
```
- Sometimes that test passes.

**UPDATE**: This works in ES 2.1.1 but not in ES 2.2.0

Other details:

1. I am using `ESIntegTestCase`
2. On the top of the class name I have `@ESIntegTestCase.ClusterScope(scope = ESIntegTestCase.Scope.TEST)`
3. This test runs for `singleWord` and `twoWords`

What could be the issue?

I am attacking the stack trace as well:

```
org.elasticsearch.transport.RemoteTransportException: [node_t0][local[1]][indices:data/read/search[phase/query+fetch]]
org.elasticsearch.search.query.QueryPhaseExecutionException: Query Failed [Failed to execute main query]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:409) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:113) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:364) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:468) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:392) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:389) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-2.2.0.jar:2.2.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
Caused by: java.lang.AbstractMethodError: org.apache.lucene.search.TwoPhaseIterator.matchCost()F
	at org.apache.lucene.search.ConjunctionDISI$TwoPhaseConjunctionDISI.<init>(ConjunctionDISI.java:186) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.ConjunctionDISI$TwoPhaseConjunctionDISI.<init>(ConjunctionDISI.java:164) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.ConjunctionDISI$TwoPhase.<init>(ConjunctionDISI.java:227) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.ConjunctionDISI$TwoPhase.<init>(ConjunctionDISI.java:221) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.ConjunctionDISI.intersect(ConjunctionDISI.java:50) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.ConjunctionScorer.<init>(ConjunctionScorer.java:41) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.BooleanWeight.req(BooleanWeight.java:403) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.BooleanWeight.scorer(BooleanWeight.java:326) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.Weight.bulkScorer(Weight.java:135) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.BooleanWeight.bulkScorer(BooleanWeight.java:262) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.AssertingWeight.bulkScorer(AssertingWeight.java:69) ~[lucene-test-framework-5.3.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.AssertingWeight.bulkScorer(AssertingWeight.java:69) ~[lucene-test-framework-5.3.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:818) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:535) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:384) ~[elasticsearch-2.2.0.jar:2.2.0]
	... 10 common frames omitted
13:57:52.458 [elasticsearch[node_t0][search][T#3]] DEBUG action.search.type - [node_t0] All shards failed for phase: [query_fetch]
org.elasticsearch.transport.RemoteTransportException: [node_t0][local[1]][indices:data/read/search[phase/query+fetch]]
org.elasticsearch.search.query.QueryPhaseExecutionException: Query Failed [Failed to execute main query]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:409) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:113) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:364) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:468) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:392) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:389) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-2.2.0.jar:2.2.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
Caused by: java.lang.AbstractMethodError: org.apache.lucene.search.TwoPhaseIterator.matchCost()F
	at org.apache.lucene.search.ConjunctionDISI$TwoPhaseConjunctionDISI.<init>(ConjunctionDISI.java:186) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.ConjunctionDISI$TwoPhaseConjunctionDISI.<init>(ConjunctionDISI.java:164) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.ConjunctionDISI$TwoPhase.<init>(ConjunctionDISI.java:227) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.ConjunctionDISI$TwoPhase.<init>(ConjunctionDISI.java:221) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.ConjunctionDISI.intersect(ConjunctionDISI.java:50) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.ConjunctionScorer.<init>(ConjunctionScorer.java:41) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.BooleanWeight.req(BooleanWeight.java:403) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.BooleanWeight.scorer(BooleanWeight.java:326) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.Weight.bulkScorer(Weight.java:135) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.BooleanWeight.bulkScorer(BooleanWeight.java:262) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.AssertingWeight.bulkScorer(AssertingWeight.java:69) ~[lucene-test-framework-5.3.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.AssertingWeight.bulkScorer(AssertingWeight.java:69) ~[lucene-test-framework-5.3.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:818) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:535) ~[lucene-core-5.4.1.jar:5.4.1 1725212 - jpountz - 2016-01-18 11:44:59]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:384) ~[elasticsearch-2.2.0.jar:2.2.0]
	... 10 common frames omitted
```

**Comment by clintongormley** [comment]
@jpountz any ideas what is happening here?

**Comment by apanimesh061** [comment]
Hi, 
Any update about this issue?

**Comment by clintongormley** [comment]
@jpountz pinging again

**Comment by apanimesh061** [comment]
@clintongormley I guess I found the issue. It is due to the lucene version. ES 2.1.1 uses Lucene 5.3.1 and ES 2.2.0 uses Lucene 5.4.1. The `TwoPhaseIterator.matchCost()` was introduced in in Lucene 5.4. if I am not wrong.

I would suggest you mention somewhere, that the Lucene core version should be updated to 5.4, when updating to ES 2.2.0.

**Comment by clintongormley** [comment]
@apanimesh061 you won't be able to run the wrong lucene version as of 2.3.0 (see https://github.com/elastic/elasticsearch/pull/16305)
