### ISSUE TITLE
NullPointerException when ALIAS is missing

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#16549]
The issue is: https://github.com/ywelsch/elasticsearch/blob/bef0bedba9e4d3417205eee7a0601eaf9763a831/core/src/main/java/org/elasticsearch/action/admin/indices/alias/IndicesAliasesRequest.java#L289

Which should be `aliasAction.aliases == null || aliasAction.aliases.length == 0`. 

Now for the following request:

```
POST /_aliases
{
  "actions": [
    {
      "add": {
        "index": "test_index",
        "alias": null,
        "fdasdilter": {
          "termssse": {
            "tagss": "customerconsent"
          }
        }
      }
    }
  ]
}
```

We get the following errors:

```
{
   "error": {
      "root_cause": [
         {
            "type": "null_pointer_exception",
            "reason": null
         }
      ],
      "type": "null_pointer_exception",
      "reason": null
   },
   "status": 500
}
```

```
[2016-02-09 15:56:02,492][INFO ][rest.suppressed          ] /_aliases Params: {}
java.lang.NullPointerException
	at org.elasticsearch.action.admin.indices.alias.IndicesAliasesRequest.validate(IndicesAliasesRequest.java:289)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:62)
	at org.elasticsearch.client.node.
```

**Comment by gmoskovicz** [comment]
This was introduced in #15305
