### ISSUE TITLE
field mapping conflicts are critical errors?

### ISSUE THREAD

**Issue by sysmonk** [elastic/elasticsearch#16576]
Hi,

I've upgraded our ES cluster from 1.7.4 to 2.2 yesterday. Before updating, i've run the migration plugin to check for errors. It showed two BLUE alerts - one about boolean fields returning 0/1 rather than T/F, and the other one about mapping field conflicts. 
The mapping field conflict warning was because i had a bug in my mapping with _source specified as a field. The migration plugin noted this as a BLUE warning and said it's ok to upgrade. From the plugin documentation https://github.com/elastic/elasticsearch-migration:

> Blue
> An advisory note that something has changed. No action needed.

I've fixed the schema, and all new indices were created with proper schema (this is a logstash cluster with daily/weekly indices). 

After upgrading the cluster to 2.2, elasticsearch woud start, but then exit soon. The logs contained:

```
2016-02-09 08:14:34,146][INFO ][node                     ] [es1.logstash.example.com] version[2.2.0], pid[7960], build[8ff36d1/2016-01-27T13:32:39Z]
[2016-02-09 08:14:34,147][INFO ][node                     ] [es1.logstash.example.com] initializing ...
[2016-02-09 08:14:34,651][INFO ][plugins                  ] [es1.logstash.example.com] modules [lang-expression, lang-groovy], plugins [], sites []
[2016-02-09 08:14:34,673][INFO ][env                      ] [es1.logstash.example.com] using [1] data paths, mounts [[/ (/dev/sda3)]], net usable_space [1.1tb], net total_space [1.4tb], spins? [possibl
y], types [ext4]
[2016-02-09 08:14:34,673][INFO ][env                      ] [es1.logstash.example.com] heap size [27.8gb], compressed ordinary object pointers [true]
[2016-02-09 08:14:36,994][ERROR][gateway                  ] [es1.logstash.example.com] failed to read local state, exiting...
java.lang.IllegalStateException: unable to upgrade the mappings for the index [flows-2016.01.06], reason: [Field [_source] is defined both as an object and a field in [netflow]]
        at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.checkMappingsCompatibility(MetaDataIndexUpgradeService.java:339)
        at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.upgradeIndexMetaData(MetaDataIndexUpgradeService.java:116)
        at org.elasticsearch.gateway.GatewayMetaState.pre20Upgrade(GatewayMetaState.java:228)
        at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:87)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:50)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:887)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
        at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:887)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
        at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:887)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:880)
        at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:46)
        at org.elasticsearch.node.Node.<init>(Node.java:200)
        at org.elasticsearch.node.Node.<init>(Node.java:128)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.lang.IllegalArgumentException: Field [_source] is defined both as an object and a field in [netflow]
        at org.elasticsearch.index.mapper.MapperService.checkFieldUniqueness(MapperService.java:375)
        at org.elasticsearch.index.mapper.MapperService.checkMappersCompatibility(MapperService.java:385)
        at org.elasticsearch.index.mapper.MapperService.checkMappersCompatibility(MapperService.java:411)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:314)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:272)
        at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.checkMappingsCompatibility(MetaDataIndexUpgradeService.java:333)
        ... 48 more
[2016-02-09 08:14:37,590][ERROR][bootstrap                ] Guice Exception: java.lang.IllegalStateException: unable to upgrade the mappings for the index [flows-2016.01.06], reason: [Field [_source] is defined both as an object and a field in [netflow]]
Likely root cause: java.lang.IllegalArgumentException: Field [_source] is defined both as an object and a field in [netflow]
        at org.elasticsearch.index.mapper.MapperService.checkFieldUniqueness(MapperService.java:375)
        at org.elasticsearch.index.mapper.MapperService.checkMappersCompatibility(MapperService.java:385)
        at org.elasticsearch.index.mapper.MapperService.checkMappersCompatibility(MapperService.java:411)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:314)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:272)
        at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.checkMappingsCompatibility(MetaDataIndexUpgradeService.java:333)
        at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.upgradeIndexMetaData(MetaDataIndexUpgradeService.java:116)
        at org.elasticsearch.gateway.GatewayMetaState.pre20Upgrade(GatewayMetaState.java:228)
        at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:87)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at <<<guice>>>
        at org.elasticsearch.node.Node.<init>(Node.java:200)
        at org.elasticsearch.node.Node.<init>(Node.java:128)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

Unfortunately, it kept crashing like that all the time until i removed all the affected indices ( 1.5 months of netflow logs). I understand the conflicting mapping might not be supported, but the migration plugin should at least mark that as RED / Critical error. If it did, i could have waited a month before upgrading so that new indices use the proper, not broken schema.

**Comment by rjernst** [comment]
> Unfortunately, it kept crashing like that all the time until i removed all the affected indices

The indexes should have been intact. The error you see is part of the "upgrade" process when starting a node. Moving them to another location should have allowed you to still open them with a 1.7 cluster. Also, this is why it is highly recommended to backup your data with a snapshot before upgrading.

> the migration plugin should at least mark that as RED / Critical error.

@clintongormley That seems like an easy fix? This blue warning you got is not actually the error here. This is because of a more recent change which does not allow a field to be an "object" as well as a regular field at the same time. For example, if in your mappings you had a field underneath `_source`, then _source would become an object field.

**Comment by clintongormley** [comment]
@rjernst fixed in https://github.com/elastic/elasticsearch-migration/commit/0d6dce8dcd58b15201fbcd3206ca33eba1558a12

Closing this issue as i don't think there is any more to do here
