### ISSUE TITLE
Indices Recovery Failure after ES upgrade (from 2.1 to 2.2)

### ISSUE THREAD

**Issue by iliasse-hassala** [elastic/elasticsearch#16581]
I get the error below after upgrading from ES 2.1 to 2.2. 
When i close the related indices (3 among 12) the error disappears but the cluster stucks in red state.

Any help please ?

Logs from Master Node : 

[2016-02-10 14:34:16,281][INFO ][gateway                  ] [Node0] recovered [28] indices into cluster_state
[2016-02-10 14:34:16,924][WARN ][cluster.action.shard     ] [Node0] [patentsample][2] received shard failed for [patentsample][2], node[MJvzZG3GRYWsWQMkwW_iTQ], [P], v[7], s[INITIALIZING], a[id=5Q7BsdFMQ7uw1NLUUtmC4g], unassigned_info[[reason=CLUSTER_RECOVERED], at[2016-02-10T14:34:15.484Z]], indexUUID [NVocWIBeT_OSfX5BzWCbug], message [failed recovery], failure [IndexShardRecoveryException[failed to fetch index version after copying it over]; nested: CorruptIndexException[Hit unexpected exception while reading segment infos (resource=commit(null))]; nested: IllegalArgumentException[Could not load codec 'Lucene54'.  Did you forget to add lucene-backward-codecs.jar?]; nested: IllegalArgumentException[An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene54' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene40, Lucene41, Lucene42, Lucene45, Lucene46, Lucene49, Lucene410, Lucene50, Lucene53]]; ]
[patentsample][[patentsample][2]] IndexShardRecoveryException[failed to fetch index version after copying it over]; nested: CorruptIndexException[Hit unexpected exception while reading segment infos (resource=commit(null))]; nested: IllegalArgumentException[Could not load codec 'Lucene54'.  Did you forget to add lucene-backward-codecs.jar?]; nested: IllegalArgumentException[An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene54' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene40, Lucene41, Lucene42, Lucene45, Lucene46, Lucene49, Lucene410, Lucene50, Lucene53]];
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:224)
        at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
        at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.lucene.index.CorruptIndexException: Hit unexpected exception while reading segment infos (resource=commit(null))
        at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:170)
        at org.elasticsearch.index.store.Store.readLastCommittedSegmentsInfo(Store.java:148)
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:199)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: Could not load codec 'Lucene54'.  Did you forget to add lucene-backward-codecs.jar?
        at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:481)
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:361)
        at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:493)
        at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:490)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:731)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:683)
        at org.apache.lucene.index.SegmentInfos.readLatestCommit(SegmentInfos.java:490)
        at org.elasticsearch.common.lucene.Lucene.readSegmentInfos(Lucene.java:98)
        at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:163)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene54' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene40, Lucene41, Lucene42, Lucene45, Lucene46, Lucene49, Lucene410, Lucene50, Lucene53]
        at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:109)
        at org.apache.lucene.codecs.Codec.forName(Codec.java:113)
        at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:469)
        ... 15 more
[2016-02-10 14:34:16,926][WARN ][cluster.action.shard     ] [Node0] [publicationsample][4] received shard failed for [publicationsample][4], node[MJvzZG3GRYWsWQMkwW_iTQ], [P], v[7], s[INITIALIZING], a[id=YFaIx3-lTcek_bvzrBBgnw], unassigned_info[[reason=CLUSTER_RECOVERED], at[2016-02-10T14:34:15.485Z]], indexUUID [slQCqXWKS5W1nwfux3WD6w], message [failed recovery], failure [IndexShardRecoveryException[failed to fetch index version after copying it over]; nested: CorruptIndexException[Hit unexpected exception while reading segment infos (resource=commit(null))]; nested: IllegalArgumentException[Could not load codec 'Lucene54'.  Did you forget to add lucene-backward-codecs.jar?]; nested: IllegalArgumentException[An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene54' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene40, Lucene41, Lucene42, Lucene45, Lucene46, Lucene49, Lucene410, Lucene50, Lucene53]]; ]
[publicationsample][[publicationsample][4]] IndexShardRecoveryException[failed to fetch index version after copying it over]; nested: CorruptIndexException[Hit unexpected exception while reading segment infos (resource=commit(null))]; nested: IllegalArgumentException[Could not load codec 'Lucene54'.  Did you forget to add lucene-backward-codecs.jar?]; nested: IllegalArgumentException[An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene54' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene40, Lucene41, Lucene42, Lucene45, Lucene46, Lucene49, Lucene410, Lucene50, Lucene53]];
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:224)
        at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
        at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.lucene.index.CorruptIndexException: Hit unexpected exception while reading segment infos (resource=commit(null))
        at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:170)
        at org.elasticsearch.index.store.Store.readLastCommittedSegmentsInfo(Store.java:148)
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:199)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: Could not load codec 'Lucene54'.  Did you forget to add lucene-backward-codecs.jar?
        at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:481)
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:361)
        at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:493)
        at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:490)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:731)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:683)
        at org.apache.lucene.index.SegmentInfos.readLatestCommit(SegmentInfos.java:490)
        at org.elasticsearch.common.lucene.Lucene.readSegmentInfos(Lucene.java:98)
        at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:163)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene54' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene40, Lucene41, Lucene42, Lucene45, Lucene46, Lucene49, Lucene410, Lucene50, Lucene53]
        at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:109)
        at org.apache.lucene.codecs.Codec.forName(Codec.java:113)
        at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:469)
        ... 15 more
[2016-02-10 14:34:17,491][WARN ][cluster.action.shard     ] [Node0] [publicationsample][4] received shard failed for [publicationsample][4], node[MJvzZG3GRYWsWQMkwW_iTQ], [P], v[7], s[INITIALIZING], a[id=YFaIx3-lTcek_bvzrBBgnw], unassigned_info[[reason=CLUSTER_RECOVERED], at[2016-02-10T14:34:15.485Z]], indexUUID [slQCqXWKS5W1nwfux3WD6w], message [master {Node0}{JA-FfaaNSu-YHEmTRWmdKw}{10.150.232.141}{10.150.232.141:9301} marked shard as initializing, but shard is marked as failed, resend shard failure], failure [Unknown]
[2016-02-10 14:34:17,533][WARN ][cluster.action.shard     ] [Node0] [patentsample][2] received shard failed for [patentsample][2], node[MJvzZG3GRYWsWQMkwW_iTQ], [P], v[7], s[INITIALIZING], a[id=5Q7BsdFMQ7uw1NLUUtmC4g], unassigned_info[[reason=CLUSTER_RECOVERED], at[2016-02-10T14:34:15.484Z]], indexUUID [NVocWIBeT_OSfX5BzWCbug], message [master {Node0}{JA-FfaaNSu-YHEmTRWmdKw}{10.150.232.141}{10.150.232.141:9301} marked shard as initializing, but shard is marked as failed, resend shard failure], failure [Unknown]
[2016-02-10 14:34:17,585][WARN ][cluster.action.shard     ] [Node0] [publicationsample][1] received shard failed for [publicationsample][1], node[MJvzZG3GRYWsWQMkwW_iTQ], [P], v[7], s[INITIALIZING], a[id=eRGZ06jJRQukGunuw-KR5g], unassigned_info[[reason=CLUSTER_RECOVERED], at[2016-02-10T14:34:15.485Z]], indexUUID [slQCqXWKS5W1nwfux3WD6w], message [failed recovery], failure [IndexShardRecoveryException[failed to fetch index version after copying it over]; nested: CorruptIndexException[Hit unexpected exception while reading segment infos (resource=commit(null))]; nested: IllegalArgumentException[Could not load codec 'Lucene54'.  Did you forget to add lucene-backward-codecs.jar?]; nested: IllegalArgumentException[An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene54' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene40, Lucene41, Lucene42, Lucene45, Lucene46, Lucene49, Lucene410, Lucene50, Lucene53]]; ]
[publicationsample][[publicationsample][1]] IndexShardRecoveryException[failed to fetch index version after copying it over]; nested: CorruptIndexException[Hit unexpected exception while reading segment infos (resource=commit(null))]; nested: IllegalArgumentException[Could not load codec 'Lucene54'.  Did you forget to add lucene-backward-codecs.jar?]; nested: IllegalArgumentException[An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene54' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene40, Lucene41, Lucene42, Lucene45, Lucene46, Lucene49, Lucene410, Lucene50, Lucene53]];
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:224)
        at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
        at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.lucene.index.CorruptIndexException: Hit unexpected exception while reading segment infos (resource=commit(null))
        at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:170)
        at org.elasticsearch.index.store.Store.readLastCommittedSegmentsInfo(Store.java:148)
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:199)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: Could not load codec 'Lucene54'.  Did you forget to add lucene-backward-codecs.jar?
        at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:481)
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:361)
        at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:493)
        at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:490)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:731)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:683)
        at org.apache.lucene.index.SegmentInfos.readLatestCommit(SegmentInfos.java:490)
        at org.elasticsearch.common.lucene.Lucene.readSegmentInfos(Lucene.java:98)
        at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:163)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene54' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene40, Lucene41, Lucene42, Lucene45, Lucene46, Lucene49, Lucene410, Lucene50, Lucene53]
        at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:109)
        at org.apache.lucene.codecs.Codec.forName(Codec.java:113)
        at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:469)
        ... 15 more
[2016-02-10 14:34:17,757][WARN ][cluster.action.shard     ] [Node0] [familysample][0] received shard failed for [familysample][0], node[MJvzZG3GRYWsWQMkwW_iTQ], [P], v[7], s[INITIALIZING], a[id=lQICArHATBSnSm-PU_B4Cg], unassigned_info[[reason=CLUSTER_RECOVERED], at[2016-02-10T14:34:15.484Z]], indexUUID [aeC20SE7TkSeE3iMu3i_Fw], message [failed recovery], failure [IndexShardRecoveryException[failed to fetch index version after copying it over]; nested: CorruptIndexException[Hit unexpected exception while reading segment infos (resource=commit(null))]; nested: IllegalArgumentException[Could not load codec 'Lucene54'.  Did you forget to add lucene-backward-codecs.jar?]; nested: IllegalArgumentException[An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene54' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene40, Lucene41, Lucene42, Lucene45, Lucene46, Lucene49, Lucene410, Lucene50, Lucene53]]; ]
[familysample][[familysample][0]] IndexShardRecoveryException[failed to fetch index version after copying it over]; nested: CorruptIndexException[Hit unexpected exception while reading segment infos (resource=commit(null))]; nested: IllegalArgumentException[Could not load codec 'Lucene54'.  Did you forget to add lucene-backward-codecs.jar?]; nested: IllegalArgumentException[An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene54' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene40, Lucene41, Lucene42, Lucene45, Lucene46, Lucene49, Lucene410, Lucene50, Lucene53]];
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:224)
        at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
        at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.lucene.index.CorruptIndexException: Hit unexpected exception while reading segment infos (resource=commit(null))
        at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:170)
        at org.elasticsearch.index.store.Store.readLastCommittedSegmentsInfo(Store.java:148)
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:199)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: Could not load codec 'Lucene54'.  Did you forget to add lucene-backward-codecs.jar?
        at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:481)
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:361)
        at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:493)
        at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:490)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:731)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:683)
        at org.apache.lucene.index.SegmentInfos.readLatestCommit(SegmentInfos.java:490)
        at org.elasticsearch.common.lucene.Lucene.readSegmentInfos(Lucene.java:98)
        at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:163)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene54' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene40, Lucene41, Lucene42, Lucene45, Lucene46, Lucene49, Lucene410, Lucene50, Lucene53]
        at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:109)
        at org.apache.lucene.codecs.Codec.forName(Codec.java:113)
        at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:469)
        ... 15 more
[2016-02-10 14:34:17,758][WARN ][cluster.action.shard     ] [Node0] [familysample][3] received shard failed for [familysample][3], node[MJvzZG3GRYWsWQMkwW_iTQ], [P], v[7], s[INITIALIZING], a[id=PQq5FgyvR3Kd9_9TLgta0w], unassigned_info[[reason=CLUSTER_RECOVERED], at[2016-02-10T14:34:15.484Z]], indexUUID [aeC20SE7TkSeE3iMu3i_Fw], message [failed recovery], failure [IndexShardRecoveryException[failed to fetch index version after copying it over]; nested: CorruptIndexException[Hit unexpected exception while reading segment infos (resource=commit(null))]; nested: IllegalArgumentException[Could not load codec 'Lucene54'.  Did you forget to add lucene-backward-codecs.jar?]; nested: IllegalArgumentException[An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene54' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene40, Lucene41, Lucene42, Lucene45, Lucene46, Lucene49, Lucene410, Lucene50, Lucene53]]; ]
[familysample][[familysample][3]] IndexShardRecoveryException[failed to fetch index version after copying it over]; nested: CorruptIndexException[Hit unexpected exception while reading segment infos (resource=commit(null))]; nested: IllegalArgumentException[Could not load codec 'Lucene54'.  Did you forget to add lucene-backward-codecs.jar?]; nested: IllegalArgumentException[An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene54' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene40, Lucene41, Lucene42, Lucene45, Lucene46, Lucene49, Lucene410, Lucene50, Lucene53]];
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:224)
        at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
        at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.lucene.index.CorruptIndexException: Hit unexpected exception while reading segment infos (resource=commit(null))
        at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:170)
        at org.elasticsearch.index.store.Store.readLastCommittedSegmentsInfo(Store.java:148)
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:199)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: Could not load codec 'Lucene54'.  Did you forget to add lucene-backward-codecs.jar?
        at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:481)
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:361)
        at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:493)
        at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:490)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:731)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:683)
        at org.apache.lucene.index.SegmentInfos.readLatestCommit(SegmentInfos.java:490)
        at org.elasticsearch.common.lucene.Lucene.readSegmentInfos(Lucene.java:98)
        at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:163)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene54' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene40, Lucene41, Lucene42, Lucene45, Lucene46, Lucene49, Lucene410, Lucene50, Lucene53]
        at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:109)
        at org.apache.lucene.codecs.Codec.forName(Codec.java:113)
        at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:469)
        ... 15 more
[2016-02-10 14:34:17,780][WARN ][cluster.action.shard     ] [Node0] [familysample][3] received shard failed for [familysample][3], node[MJvzZG3GRYWsWQMkwW_iTQ], [P], v[7], s[INITIALIZING], a[id=PQq5FgyvR3Kd9_9TLgta0w], unassigned_info[[reason=CLUSTER_RECOVERED], at[2016-02-10T14:34:15.484Z]], indexUUID [aeC20SE7TkSeE3iMu3i_Fw], message [master {Node0}{JA-FfaaNSu-YHEmTRWmdKw}{10.150.232.141}{10.150.232.141:9301} marked shard as initializing, but shard is marked as failed, resend shard failure], failure [Unknown]
[2016-02-10 14:34:17,780][WARN ][cluster.action.shard     ] [Node0] [familysample][0] received shard failed for [familysample][0], node[MJvzZG3GRYWsWQMkwW_iTQ], [P], v[7], s[INITIALIZING], a[id=lQICArHATBSnSm-PU_B4Cg], unassigned_info[[reason=CLUSTER_RECOVERED], at[2016-02-10T14:34:15.484Z]], indexUUID [aeC20SE7TkSeE3iMu3i_Fw], message [master {Node0}{JA-FfaaNSu-YHEmTRWmdKw}{10.150.232.141}{10.150.232.141:9301} marked shard as initializing, but shard is marked as failed, resend shard failure], failure [Unknown]
[2016-02-10 14:34:19,159][INFO ][cluster.service          ] [Node0] added {{Node2}{XS3GAcc1QJ2PiqINJ0vmWw}{10.150.232.143}{10.150.232.143:9300},}, reason: zen-disco-join(join from node[{Node2}{XS3GAcc1QJ2PiqINJ0vmWw}{10.150.232.143}{10.150.232.143:9300}])

**Comment by rjernst** [comment]
How did you upgrade? It looks like you have lucene jars from ES 2.1 on your classpath.

**Comment by iliasse-hassala** [comment]
Hi rjernst, thank you for your answer.

Actually I'm using a Dockerfile (below) i just changed the image i'm pulling (2.1 to 2.2).
I have a 3 nodes setup : Node{0,1,2}

FROM elasticsearch:2.2

        EXPOSE 9200 9300

        RUN /usr/share/elasticsearch/bin/plugin install license
        RUN /usr/share/elasticsearch/bin/plugin install marvel-agent
        RUN /usr/share/elasticsearch/bin/plugin install delete-by-query
        RUN export ES_HEAP_SIZE=30g
        COPY ESconf/* /usr/share/elasticsearch/config/

CMD elasticsearch

Basically what i noticed is that the translogs of 3 indices among 12 were not empty. And when i close these 3 indices the errors disappears but the cluster is stuck in red state.
I run "/_cat/shards" in the master node (Node3) and i see that there are some UNASSIGNED shards belonging to Node0 I presume (primary ones, since i had no replicas in order to speed up the bulk injection).

The Master node sees 3 nodes :  "_health" gives this
{
  "cluster_name" : "NOSQL_elastic_cluster",
  "status" : "red",
  "timed_out" : false,
  "number_of_nodes" : 3,
  "number_of_data_nodes" : 3,
  "active_primary_shards" : 52,
  "active_shards" : 69,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 25,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 73.40425531914893
}

But when i run the same command on Node0 I get nothing (it times out) so may be something else is going on with Node0. What is weird is that the logs of Node0 says everything is ok (it detects the master and joins the cluster) :


[2016-02-10 16:54:27,638][INFO ][node                     ] [Node0] version[2.2.0], pid[6], build[8ff36d1/2016-01-27T13:32:39Z]
[2016-02-10 16:54:27,638][INFO ][node                     ] [Node0] initializing ...
[2016-02-10 16:54:28,409][INFO ][plugins                  ] [Node0] modules [lang-expression, lang-groovy], plugins [license, marvel-agent, delete-by-query], sites []
[2016-02-10 16:54:28,464][INFO ][env                      ] [Node0] using [1] data paths, mounts [[/usr/share/elasticsearch/data (h097b:/vol/K1NQDATASQL1/ESdata/Node0)]], net usable_space [1.3tb], net total_space [2.9tb], spins? [possibly], types [nfs]
[2016-02-10 16:54:28,464][INFO ][env                      ] [Node0] heap size [30.6gb], compressed ordinary object pointers [true]
[2016-02-10 16:54:31,097][INFO ][node                     ] [Node0] initialized
[2016-02-10 16:54:31,097][INFO ][node                     ] [Node0] starting ...
[2016-02-10 16:54:31,505][INFO ][transport                ] [Node0] publish_address {10.150.232.141:9301}, bound_addresses {[::]:9301}
[2016-02-10 16:54:31,520][INFO ][discovery                ] [Node0] NOSQL_elastic_cluster/JFUJziK_QViw9kPut7Aopw
[2016-02-10 16:54:34,672][INFO ][cluster.service          ] [Node0] detected_master {Node2}{ZyxfRlELTECjeiSk63Wutw}{10.150.232.143}{10.150.232.143:9300}, added {{Node1}{kv-JGvl0RaCzdzCL-WWQ0A}{10.150.232.142}{10.150.232.142:9300},{Node2}{ZyxfRlELTECjeiSk63Wutw}{10.150.232.143}{10.150.232.143:9300},}, reason: zen-disco-receive(from master [{Node2}{ZyxfRlELTECjeiSk63Wutw}{10.150.232.143}{10.150.232.143:9300}])
[2016-02-10 16:54:34,820][INFO ][license.plugin.core      ] [Node0] license [4eedac74-a1d1-4023-8006-82db439db4f1] - valid
[2016-02-10 16:54:34,822][ERROR][license.plugin.core      ] [Node0]
#
# License will expire on [Friday, March 11, 2016]. If you have a new license, please update it.
# Otherwise, please reach out to your support contact.
#
# Commercial plugins operate with reduced functionality on license expiration:
# - marvel
#  - The agent will stop collecting cluster and indices metrics
[2016-02-10 16:54:35,201][INFO ][http                     ] [Node0] publish_address {10.150.232.141:9201}, bound_addresses {[::]:9201}
[2016-02-10 16:54:35,202][INFO ][node                     ] [Node0] started


Any idea ? thanks for your help.

**Comment by iliasse-hassala** [comment]
Hi rjernst, thank you for your answer.

Actually I'm using a Dockerfile (below) i just changed the image i'm pulling (2.1 to 2.2).
I have a 3 nodes setup : Node{0,1,2}

```
FROM elasticsearch:2.2

        EXPOSE 9200 9300

        RUN /usr/share/elasticsearch/bin/plugin install license
        RUN /usr/share/elasticsearch/bin/plugin install marvel-agent
        RUN /usr/share/elasticsearch/bin/plugin install delete-by-query
        RUN export ES_HEAP_SIZE=30g
        COPY ESconf/* /usr/share/elasticsearch/config/

CMD elasticsearch
```

Basically what i noticed is that the translogs of 3 indices among 12 were not empty. And when i close these 3 indices the errors disappears but the cluster is stuck in red state.
I run "/_cat/shards" in the master node (Node3) and i see that there are some UNASSIGNED shards belonging to Node0 I presume (primary ones, since i had no replicas in order to speed up the bulk injection).

The Master node sees 3 nodes :  "_health" gives this
```
{
  "cluster_name" : "NOSQL_elastic_cluster",
  "status" : "red",
  "timed_out" : false,
  "number_of_nodes" : 3,
  "number_of_data_nodes" : 3,
  "active_primary_shards" : 52,
  "active_shards" : 69,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 25,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 73.40425531914893
}
```

But when i run the same command on Node0 I get nothing (it times out) so may be something else is going on with Node0. What is weird is that the logs of Node0 says everything is ok (it detects the master and joins the cluster) :


```
[2016-02-10 16:54:27,638][INFO ][node                     ] [Node0] version[2.2.0], pid[6], build[8ff36d1/2016-01-27T13:32:39Z]
[2016-02-10 16:54:27,638][INFO ][node                     ] [Node0] initializing ...
[2016-02-10 16:54:28,409][INFO ][plugins                  ] [Node0] modules [lang-expression, lang-groovy], plugins [license, marvel-agent, delete-by-query], sites []
[2016-02-10 16:54:28,464][INFO ][env                      ] [Node0] using [1] data paths, mounts [[/usr/share/elasticsearch/data (h097b:/vol/K1NQDATASQL1/ESdata/Node0)]], net usable_space [1.3tb], net total_space [2.9tb], spins? [possibly], types [nfs]
[2016-02-10 16:54:28,464][INFO ][env                      ] [Node0] heap size [30.6gb], compressed ordinary object pointers [true]
[2016-02-10 16:54:31,097][INFO ][node                     ] [Node0] initialized
[2016-02-10 16:54:31,097][INFO ][node                     ] [Node0] starting ...
[2016-02-10 16:54:31,505][INFO ][transport                ] [Node0] publish_address {10.150.232.141:9301}, bound_addresses {[::]:9301}
[2016-02-10 16:54:31,520][INFO ][discovery                ] [Node0] NOSQL_elastic_cluster/JFUJziK_QViw9kPut7Aopw
[2016-02-10 16:54:34,672][INFO ][cluster.service          ] [Node0] detected_master {Node2}{ZyxfRlELTECjeiSk63Wutw}{10.150.232.143}{10.150.232.143:9300}, added {{Node1}{kv-JGvl0RaCzdzCL-WWQ0A}{10.150.232.142}{10.150.232.142:9300},{Node2}{ZyxfRlELTECjeiSk63Wutw}{10.150.232.143}{10.150.232.143:9300},}, reason: zen-disco-receive(from master [{Node2}{ZyxfRlELTECjeiSk63Wutw}{10.150.232.143}{10.150.232.143:9300}])
[2016-02-10 16:54:34,820][INFO ][license.plugin.core      ] [Node0] license [4eedac74-a1d1-4023-8006-82db439db4f1] - valid
[2016-02-10 16:54:35,201][INFO ][http                     ] [Node0] publish_address {10.150.232.141:9201}, bound_addresses {[::]:9201}
[2016-02-10 16:54:35,202][INFO ][node                     ] [Node0] started
```


Any idea ? thanks for your help.

**Comment by iliasse-hassala** [comment]
I had to reroute manually the UNASSIGNED shards. I guess that i should stop the cluster more properly (i was doing some bulk injection) before doing the update.
