### ISSUE TITLE
Indexing failure when using bulk API

### ISSUE THREAD

**Issue by fadi-assaad** [elastic/elasticsearch#16628]
Experienced an error while indexing content from drupal to elasticsearch installed on same VM. Noticed two things from elasticsearch logs below:

- failed to parse, document is empty.

- 'defaiya_articles_alias' alias which i think it was created automatically on first bulk operation occured.

Am using Elasticsearch 1.7.4 along drupal module elasticsearch_connector-7.x-1.0-alpha9

This happens when posting with Bulk endpoint
localhost:9200/defaiya_articles/defaiya_articles/_bulk?refresh=1

I have no clue about whats happening but i know am missing some configuration on elasticsearch. That because drupal module was working fine with a trial service from found.elasic.co.

### Elasticsearch log
`[2016-02-12 09:05:37,968][DEBUG][action.index             ] [Lucifer] [defaiya_articles][0], node[jDATrKcOQc2i0x7FmkSRNA], [P], s[STARTED]: Failed to execute [index {[defaiya_articles_alias][defaiya_articles][AVLUTKGwN3desrFRGnhC], source[_na_]}]
org.elasticsearch.index.mapper.MapperParsingException: failed to parse, document is empty
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:562)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:493)
        at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:465)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:201)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:574)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:440)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
`
### Index information
`{
  "defaiya_articles" : {
    "aliases" : {
      "defaiya_articles_alias" : { }
    },
    "mappings" : {
      "defaiya_articles" : {
        "properties" : {
          "articledate" : {
            "type" : "date",
            "format" : "yyyy-MM-dd HH:mm:ss"
          },
          "body:value" : {
            "type" : "string"
          },
          "id" : {
            "type" : "integer",
            "include_in_all" : false
          },
          "search_api_language" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "title" : {
            "type" : "string"
          }
        }
      }
    },
    "settings" : {
      "index" : {
        "creation_date" : "1454879612879",
        "uuid" : "b5ljdnseQc2ZFDGLliYTLA",
        "number_of_replicas" : "1",
        "number_of_shards" : "1",
        "version" : {
          "created" : "1070499"
        }
      }
    },
    "warmers" : { }
  }
}
`

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
