### ISSUE TITLE
Can not run Tika StandAlone runner

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#16630]
In mapper-attachments plugin, I created originally a [Stand Alone command line tool](https://github.com/elastic/elasticsearch/blob/master/plugins/mapper-attachments/src/test/java/org/elasticsearch/mapper/attachments/StandaloneRunner.java) which helps me to extract data from binary files.
It helps to understand what Tika actually extracts before sending the text to elasticsearch. Basically it helps to debug when users report issues.

In master branch, when I run the StandAlone tool (which is a `main()` - not a test) from IntelliJ, I'm getting this error:

```
Exception in thread "main" java.lang.IllegalStateException: running tests but failed to invoke RandomizedContext#getRandom
	at org.elasticsearch.common.Randomness.get(Randomness.java:105)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.randomNodeName(InternalSettingsPreparer.java:194)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.finalizeSettings(InternalSettingsPreparer.java:167)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:106)
	at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:100)
	at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:91)
	at org.elasticsearch.mapper.attachments.StandaloneRunner.<init>(StandaloneRunner.java:171)
	at org.elasticsearch.mapper.attachments.StandaloneRunner.main(StandaloneRunner.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.elasticsearch.common.Randomness.get(Randomness.java:101)
	... 12 more
Caused by: java.lang.IllegalStateException: No context information for thread: Thread[id=1, name=main, state=RUNNABLE, group=main]. Is this thread running under a class com.carrotsearch.randomizedtesting.RandomizedRunner runner context? Add @RunWith(class com.carrotsearch.randomizedtesting.RandomizedRunner.class) to your test class. Make sure your code accesses random contexts within @BeforeClass and @AfterClass boundary (for example, static test class initializers are not permitted to access random contexts).
	at com.carrotsearch.randomizedtesting.RandomizedContext.context(RandomizedContext.java:244)
	at com.carrotsearch.randomizedtesting.RandomizedContext.current(RandomizedContext.java:151)
	... 17 more
``` 

I'm not expecting anything from the test framework here so I'm a bit surprise about the result.

I know that a `main` should not be in our `src/test` dir but I don't really want to commit this class in `src/main`.

Should I simply remove that class because we can't use it anymore?
Knowing that this plugin will probably become deprecated by the node-ingest one...

**Comment by dadoonet** [comment]
@rjernst WDYT?

**Comment by clintongormley** [comment]
Given that we're deprecating the mapper-attachment plugin in https://github.com/elastic/elasticsearch/issues/16650 I'd say this can be closed.
