### ISSUE TITLE
DuelFieldDataTests.testDuelGeoPoints sometimes fails

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#16634]
This failure reproduces consistently on master with the seed: `-Dtests.seed=AD46AA1C13DCCBCC`

The stack trace is:
```
java.lang.NumberFormatException: Invalid shift value (-32) in prefixCoded bytes (is encoded value really an INT?)
	at __randomizedtesting.SeedInfo.seed([AD46AA1C13DCCBCC:7920A55097BF4789]:0)
	at org.apache.lucene.util.NumericUtils.getPrefixCodedLongShift(NumericUtils.java:200)
	at org.elasticsearch.index.fielddata.ordinals.OrdinalsBuilder$1.accept(OrdinalsBuilder.java:435)
	at org.apache.lucene.index.FilteredTermsEnum.next(FilteredTermsEnum.java:232)
	at org.elasticsearch.index.fielddata.ordinals.OrdinalsBuilder$3.next(OrdinalsBuilder.java:478)
	at org.elasticsearch.index.fielddata.plain.AbstractIndexGeoPointFieldData$GeoPointTermsEnum.next(AbstractIndexGeoPointFieldData.java:55)
	at org.elasticsearch.index.fielddata.plain.GeoPointArrayIndexFieldData.loadFieldData22(GeoPointArrayIndexFieldData.java:100)
	at org.elasticsearch.index.fielddata.plain.GeoPointArrayIndexFieldData.loadDirect(GeoPointArrayIndexFieldData.java:82)
	at org.elasticsearch.index.fielddata.plain.GeoPointArrayIndexFieldData.loadDirect(GeoPointArrayIndexFieldData.java:1)
	at org.elasticsearch.index.fielddata.DuelFieldDataTests.duelFieldDataGeoPoint(DuelFieldDataTests.java:564)
	at org.elasticsearch.index.fielddata.DuelFieldDataTests.testDuelGeoPoints(DuelFieldDataTests.java:449)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1764)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:871)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:907)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:921)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:809)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:460)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:880)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:781)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:816)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:827)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
	at java.lang.Thread.run(Thread.java:745)


```

@mikemccand @nknize Maybe this is something to do with the new GeoPoint implementation?

**Comment by mikemccand** [comment]
Hmm this looks quite bad: it looks likely we indexed with PREFIX encoding but tried to search using the legacy NUMERIC?  Something is wrong w/ the back compat layer @nknize?

**Comment by s1monw** [comment]
@colings86 can we mute the test?

**Comment by colings86** [comment]
Sure. Will do

**Comment by colings86** [comment]
test has been muted in https://github.com/elastic/elasticsearch/commit/83885423a0577c83e4ca7da922547d212b0b5fd7

**Comment by nknize** [comment]
Pushing fix.
