### ISSUE TITLE
Translog recovery failure eating CPU

### ISSUE THREAD

**Issue by drewr** [elastic/elasticsearch#16662]
Found one of the nodes in my idle (other than marvel), local **2.2.0** cluster eating a chunk of CPU today.

![image](https://cloud.githubusercontent.com/assets/6202/13036529/42007536-d32f-11e5-82bb-8a867af923e4.png)

```
% curl -s localhost:9200/_cat/nodes\?h=ip,master,name
127.0.0.1 * Graviton     
127.0.0.1 m Blood Spider 
% curl -s localhost:9200/_cat/shards | fgrep 02.13
.marvel-es-2016.02.13                     0 p INITIALIZING                127.0.0.1 Graviton     
.marvel-es-2016.02.13                     0 r UNASSIGNED
%
```

A bunch of checkpoint logs happen:

```
[2016-02-14 00:29:10,769][DEBUG][index.translog           ] [Graviton] [.marvel-es-2016.02.13][0] recovered local translog from checkpoint Checkpoint{offset=2556515, numOps=4273, translogFileGe
neration= 3691}
```

Both nodes load their data dir from the same `nodes/` path, and this volume is **87% full**.  So allocation of this shard keeps occurring:

```
[2016-02-14 00:29:28,147][INFO ][cluster.routing.allocation.decider] [Graviton] low disk watermark [85%] exceeded on [DG6Jls2UTrSSsrG2huoYMQ][Graviton][/home/aar/Downloads/elasticsearch-2.2.0/d
ata/elasticsearch/nodes/1] free: 66.2gb[14.8%], replicas will not be assigned to this node
[2016-02-14 00:29:28,147][INFO ][cluster.routing.allocation.decider] [Graviton] low disk watermark [85%] exceeded on [w8hx8OmwRg6ETfhbAA6XYg][Blood Spider][/home/aar/Downloads/elasticsearch-2.2
.0/data/elasticsearch/nodes/0] free: 66.2gb[14.8%], replicas will not be assigned to this node
```

Then the allocation is attempted:

```
[2016-02-14 00:29:29,120][DEBUG][index.translog           ] [Graviton] [.marvel-es-2016.02.13][0] translog closed
[2016-02-14 00:29:29,120][DEBUG][index                    ] [Graviton] [.marvel-es-2016.02.13] [0] closing... (reason: [failed recovery])
[2016-02-14 00:29:29,120][DEBUG][index.shard              ] [Graviton] [.marvel-es-2016.02.13][0] state: [RECOVERING]->[CLOSED], reason [failed recovery]
[2016-02-14 00:29:29,120][DEBUG][index.shard              ] [Graviton] [.marvel-es-2016.02.13][0] operations counter reached 0, will not accept any further writes
[2016-02-14 00:29:29,120][DEBUG][index.store              ] [Graviton] [.marvel-es-2016.02.13][0] store reference count on close: 0
[2016-02-14 00:29:29,120][DEBUG][index                    ] [Graviton] [.marvel-es-2016.02.13] [0] closed (reason: [failed recovery])
[2016-02-14 00:29:29,120][WARN ][indices.cluster          ] [Graviton] [[.marvel-es-2016.02.13][0]] marking and sending shard failed due to [failed recovery]
[.marvel-es-2016.02.13][[.marvel-es-2016.02.13][0]] IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to recover from translog]; nested: EngineException[failed to recover from translog]; nested: ElasticsearchException[unexpected exception reading from translog snapshot of /home/aar/Downloads/elasticsearch-2.2.0/data/elasticsearch/nodes/1/indices/.marvel-es-2016.02.13/0/translog/translog-6.tlog]; nested: EOFException[read past EOF. pos [2556515] length: [4] end: [2556515]];
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:254)
        at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
        at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: [.marvel-es-2016.02.13][[.marvel-es-2016.02.13][0]] EngineCreationFailureException[failed to recover from translog]; nested: EngineException[failed to recover from translog]; nested: ElasticsearchException[unexpected exception reading from translog snapshot of /home/aar/Downloads/elasticsearch-2.2.0/data/elasticsearch/nodes/1/indices/.marvel-es-2016.02.13/0/translog/translog-6.tlog]; nested: EOFException[read past EOF. pos [2556515] length: [4] end: [2556515]];
        at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:178)
        at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
        at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1450)
        at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1434)
        at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:925)
        at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:897)
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:245)
        ... 5 more
Caused by: [.marvel-es-2016.02.13][[.marvel-es-2016.02.13][0]] EngineException[failed to recover from translog]; nested: ElasticsearchException[unexpected exception reading from translog snapshot of /home/aar/Downloads/elasticsearch-2.2.0/data/elasticsearch/nodes/1/indices/.marvel-es-2016.02.13/0/translog/translog-6.tlog]; nested: EOFException[read past EOF. pos [2556515] length: [4] end: [2556515]];
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:254)
        at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:175)
        ... 11 more
Caused by: ElasticsearchException[unexpected exception reading from translog snapshot of /home/aar/Downloads/elasticsearch-2.2.0/data/elasticsearch/nodes/1/indices/.marvel-es-2016.02.13/0/translog/translog-6.tlog]; nested: EOFException[read past EOF. pos [2556515] length: [4] end: [2556515]];
        at org.elasticsearch.index.translog.TranslogReader.readSize(TranslogReader.java:102)
        at org.elasticsearch.index.translog.TranslogReader.access$000(TranslogReader.java:46)
        at org.elasticsearch.index.translog.TranslogReader$ReaderSnapshot.readOperation(TranslogReader.java:297)
        at org.elasticsearch.index.translog.TranslogReader$ReaderSnapshot.next(TranslogReader.java:290)
        at org.elasticsearch.index.translog.MultiSnapshot.next(MultiSnapshot.java:70)
        at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:240)
        ... 12 more
Caused by: java.io.EOFException: read past EOF. pos [2556515] length: [4] end: [2556515]
        at org.elasticsearch.common.io.Channels.readFromFileChannelWithEofException(Channels.java:102)
        at org.elasticsearch.index.translog.ImmutableTranslogReader.readBytes(ImmutableTranslogReader.java:84)
        at org.elasticsearch.index.translog.TranslogReader.readSize(TranslogReader.java:91)
        ... 17 more
[2016-02-14 00:29:29,121][WARN ][cluster.action.shard     ] [Graviton] [.marvel-es-2016.02.13][0] received shard failed for [.marvel-es-2016.02.13][0], node[DG6Jls2UTrSSsrG2huoYMQ], [P], v[7374], s[INITIALIZING], a[id=0EodiK9gS8KIGvHSHNi1ew], unassigned_info[[reason=ALLOCATION_FAILED], at[2016-02-14T06:29:10.518Z], details[failed recovery, failure IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to recover from translog]; nested: EngineException[failed to recover from translog]; nested: ElasticsearchException[unexpected exception reading from translog snapshot of /home/aar/Downloads/elasticsearch-2.2.0/data/elasticsearch/nodes/0/indices/.marvel-es-2016.02.13/0/translog/translog-6.tlog]; nested: EOFException[read past EOF. pos [2343547] length: [4] end: [2343547]]; ]], indexUUID [Wl7rh0TuT1ms79hg-H8hzA], message [failed recovery], failure [IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to recover from translog]; nested: EngineException[failed to recover from translog]; nested: ElasticsearchException[unexpected exception reading from translog snapshot of /home/aar/Downloads/elasticsearch-2.2.0/data/elasticsearch/nodes/1/indices/.marvel-es-2016.02.13/0/translog/translog-6.tlog]; nested: EOFException[read past EOF. pos [2556515] length: [4] end: [2556515]]; ]
```

This process repeats ad infinitum.  `DEBUG` log file is each over 1g the past couple of days.

`hot_threads` has this repeated section:

```
   98.7% (493.3ms out of 500ms) cpu usage by thread 'elasticsearch[Graviton][generic][T#1]'
     10/10 snapshots sharing following 24 elements
       sun.nio.fs.UnixNativeDispatcher.readdir(Native Method)
       sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(UnixDirectoryStream.java:168)
       sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.hasNext(UnixDirectoryStream.java:201)
       org.elasticsearch.index.translog.Translog$OnCloseRunnable.handle(Translog.java:726)
       org.elasticsearch.index.translog.Translog$OnCloseRunnable.handle(Translog.java:713)
       org.elasticsearch.index.translog.ChannelReference.closeInternal(ChannelReference.java:67)
       org.elasticsearch.common.util.concurrent.AbstractRefCounted.decRef(AbstractRefCounted.java:64)
       org.elasticsearch.index.translog.TranslogReader.close(TranslogReader.java:143)
       org.apache.lucene.util.IOUtils.close(IOUtils.java:97)
       org.elasticsearch.index.translog.Translog.close(Translog.java:425)
       org.apache.lucene.util.IOUtils.closeWhileHandlingException(IOUtils.java:129)
       org.apache.lucene.util.IOUtils.closeWhileHandlingException(IOUtils.java:118)
       org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:183)
       org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
       org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1450)
       org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1434)
       org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:925)
       org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:897)
       org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:245)
       org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
       org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)
```

**Comment by bleskes** [comment]
@drewr I understand  this is  a fresh 2.2.0 and not an upgrade from an older version? Do you have anything in the logs indicating why the primary would be unassigned to begin with? Was the cluster taken down? Also, can you save the index folder and put it somewhere we can take a look?

The CPU is explained by the master continuously trying to open the single shard it can find (and running into this issue). IMO we should treat translog corruption as proper corruption and make the shard as bad. @s1monw thoughts?

**Comment by bleskes** [comment]
Oh, so old. Closing as the code today looks totally different.
