### ISSUE TITLE
no known master node, scheduling a retry

### ISSUE THREAD

**Issue by andr3w77** [elastic/elasticsearch#16683]
For some reason my data nodes is not being able to find my master node. any help would be appreciate it.

data node:
cluster.name: security-siem
node.name: elastic1
node.master: false
node.data: true
discovery.zen.ping.unicast.hosts: ["elastic-kibana"]

>[2016-02-15 15:18:15,321][INFO ][node                     ] [elastic1] version[2.2.0], pid[14790], build[8ff36d1/2016-01-27T13:32:39Z]
[2016-02-15 15:18:15,322][INFO ][node                     ] [elastic1] initializing ...
[2016-02-15 15:18:15,768][INFO ][plugins                  ] [elastic1] modules [lang-expression, lang-groovy], plugins [], sites []
[2016-02-15 15:18:15,782][INFO ][env                      ] [elastic1] using [1] data paths, mounts [[/ (/dev/sda1)]], net usable_space [11.9gb], net total_space [14.6gb], spins? [possibly], types [ext4]
[2016-02-15 15:18:15,787][INFO ][env                      ] [elastic1] heap size [1015.6mb], compressed ordinary object pointers [true]
[2016-02-15 15:18:17,940][INFO ][node                     ] [elastic1] initialized
[2016-02-15 15:18:17,941][INFO ][node                     ] [elastic1] starting ...
[2016-02-15 15:18:18,001][INFO ][transport                ] [elastic1] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2016-02-15 15:18:18,042][INFO ][discovery                ] [elastic1] security-siem/KxFzgm9TTviihCbO16B9nw
[2016-02-15 15:18:48,043][WARN ][discovery                ] [elastic1] waited for 30s and no initial state was set by the discovery
[2016-02-15 15:18:48,057][INFO ][http                     ] [elastic1] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
[2016-02-15 15:18:48,057][INFO ][node                     ] [elastic1] started
[2016-02-15 15:23:52,009][DEBUG][action.admin.cluster.state] [elastic1] no known master node, scheduling a retry
[2016-02-15 15:24:22,010][DEBUG][action.admin.cluster.state] [elastic1] timed out while retrying [cluster:monitor/state] after failure (timeout [30s])
[2016-02-15 15:24:22,015][INFO ][rest.suppressed          ] /_cat/indices Params: {v=}
MasterNotDiscoveredException[null]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$5.onTimeout(TransportMasterNodeAction.java:205)
        at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:239)
        at org.elasticsearch.cluster.service.InternalClusterService$NotifyTimeout.run(InternalClusterService.java:794)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Master node:
cluster.name: security-siem
node.name; elastic-kibana
node.master: true
node.data: false
discovery.zen.ping.unicast.hosts: ["elastic1"]

> [2016-02-15 15:17:58,874][INFO ][node                     ] [elastic-kibana] version[2.2.0], pid[4060], build[8ff36d1/2016-01-27T13:32:39Z]
[2016-02-15 15:17:58,878][INFO ][node                     ] [elastic-kibana] initializing ...
[2016-02-15 15:17:59,350][INFO ][plugins                  ] [elastic-kibana] modules [lang-expression, lang-groovy], plugins [], sites []
[2016-02-15 15:17:59,376][INFO ][env                      ] [elastic-kibana] using [1] data paths, mounts [[/ (/dev/sda1)]], net usable_space [11.7gb], net total_space [14.6gb], spins? [possibly], types [ext4]
[2016-02-15 15:17:59,384][INFO ][env                      ] [elastic-kibana] heap size [1015.6mb], compressed ordinary object pointers [true]
[2016-02-15 15:18:01,563][INFO ][node                     ] [elastic-kibana] initialized
[2016-02-15 15:18:01,569][INFO ][node                     ] [elastic-kibana] starting ...
[2016-02-15 15:18:01,668][INFO ][transport                ] [elastic-kibana] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2016-02-15 15:18:01,681][INFO ][discovery                ] [elastic-kibana] security-siem/QZF-VFfjTDy95-iHQQWm8A
[2016-02-15 15:18:04,736][INFO ][cluster.service          ] [elastic-kibana] new_master {elastic-kibana}{QZF-VFfjTDy95-iHQQWm8A}{127.0.0.1}{127.0.0.1:9300}{data=false, master=true}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2016-02-15 15:18:04,776][INFO ][http                     ] [elastic-kibana] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
[2016-02-15 15:18:04,777][INFO ][node                     ] [elastic-kibana] started
[2016-02-15 15:18:04,795][INFO ][gateway                  ] [elastic-kibana] recovered [1] indices into cluster_state

**Comment by jasontedor** [comment]
Nodes bind to localhost by default, you need to set `network.host` to have them bind to an external interface. You can read more about this is in the [network settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#modules-network).
