### ISSUE TITLE
doc and script are mutually exclusive

### ISSUE THREAD

**Issue by salimane** [elastic/elasticsearch#16684]
Consider this :
```
POST /website/pageviews/1/_update?retry_on_conflict=5 
{
   "doc_as_upsert" : "true",
   "script" : "ctx._source.views+=1",
   "doc": {
       "views": 1
   }
}
```

The above should in theory: 
- create a new doc if non-existant
- update existing doc if the id already exists
- increase views by 1 if the id already exists

Currently there is an error saying that ``can't provide both script and doc``
```
org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: can't provide both script and doc;
	at org.elasticsearch.action.bulk.BulkRequest.validate(BulkRequest.java:499)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:62)
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:351)
	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:52)
	at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient.doExecute(BaseRestHandler.java:83)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:351)
	at org.elasticsearch.client.support.AbstractClient.bulk(AbstractClient.java:428)
```

Thanks

**Comment by clintongormley** [comment]
This is how you should write it:

    POST /website/pageviews/1/_update?retry_on_conflict=5 
    {
      "script": "ctx._source.views+=1",
      "upsert": {
        "views": 1
      }
    }
