### ISSUE TITLE
NullPointerException on hasParentQuery when parent does not exist

### ISSUE THREAD

**Issue by srhtcn** [elastic/elasticsearch#16692]
Elastic version 2.2.0

> http://localhost:9200/my_index/parent_mapping/

I accidentally wrote **has_parent **instead of **has_child **and got NullPointerException.

 _Parent type does not have any parent of itself._

When I wrote has_child instead of has_parent query works as expected.

This query causes exception
```
{
  "size": 5,
  "query": {
    "bool": {
      "must": [
        {
          "query": {
            "has_parent": {
              "type": "child_mapping",
              "score_mode": "max",
              "query": {
                "match_all": {}
              },
              "inner_hits": {
                "from": 0,
                "size": 5
              }
            }
          }
        },
        {
          "query": {
            "match_all": {}
          }
        }
      ]
    }
  },
  "sort": [
    {
      "name": "asc"
    }
  ]
}

```
Here is the exception log I received:
```
RemoteTransportException[[Workit.Local][127.0.0.1:9300][indices:data/read/search[phase/query+fetch]]]; nested: NullPointerExceptio
n;
Caused by: java.lang.NullPointerException
        at org.elasticsearch.index.fielddata.plain.ParentChildIndexFieldData.getOrdinalMap(ParentChildIndexFieldData.java:566)
        at org.elasticsearch.index.query.HasChildQueryParser$LateParsingQuery.rewrite(HasChildQueryParser.java:259)
        at org.apache.lucene.search.ConstantScoreQuery.rewrite(ConstantScoreQuery.java:55)
        at org.apache.lucene.search.BooleanQuery.rewrite(BooleanQuery.java:252)
        at org.apache.lucene.search.BooleanQuery.rewrite(BooleanQuery.java:252)
        at org.apache.lucene.search.IndexSearcher.rewrite(IndexSearcher.java:836)
        at org.elasticsearch.search.internal.ContextIndexSearcher.rewrite(ContextIndexSearcher.java:81)
        at org.elasticsearch.search.internal.DefaultSearchContext.preProcess(DefaultSearchContext.java:232)
        at org.elasticsearch.search.query.QueryPhase.preProcess(QueryPhase.java:103)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:674)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:618)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:461)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchSer
viceTransportAction.java:392)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchSer
viceTransportAction.java:389)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2016-02-16 16:54:02,014][DEBUG][action.search.type       ] [Workit.Local] All shards failed for phase: [query_fetch]
RemoteTransportException[[Workit.Local][127.0.0.1:9300][indices:data/read/search[phase/query+fetch]]]; nested: NullPointerExceptio
n;
Caused by: java.lang.NullPointerException
        at org.elasticsearch.index.fielddata.plain.ParentChildIndexFieldData.getOrdinalMap(ParentChildIndexFieldData.java:566)
        at org.elasticsearch.index.query.HasChildQueryParser$LateParsingQuery.rewrite(HasChildQueryParser.java:259)
        at org.apache.lucene.search.ConstantScoreQuery.rewrite(ConstantScoreQuery.java:55)
        at org.apache.lucene.search.BooleanQuery.rewrite(BooleanQuery.java:252)
        at org.apache.lucene.search.BooleanQuery.rewrite(BooleanQuery.java:252)
        at org.apache.lucene.search.IndexSearcher.rewrite(IndexSearcher.java:836)
        at org.elasticsearch.search.internal.ContextIndexSearcher.rewrite(ContextIndexSearcher.java:81)
        at org.elasticsearch.search.internal.DefaultSearchContext.preProcess(DefaultSearchContext.java:232)
        at org.elasticsearch.search.query.QueryPhase.preProcess(QueryPhase.java:103)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:674)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:618)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:461)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchSer
viceTransportAction.java:392)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchSer
viceTransportAction.java:389)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2016-02-16 16:54:02,024][INFO ][rest.suppressed          ] /my_index/type/_search Params: {index=my_index, type=type}
Failed to execute phase [query_fetch], all shards failed; shardFailures {[F6pFRctSR4CSS1stcYFiyA][my_index][0]: RemoteTranspor
tException[[Workit.Local][127.0.0.1:9300][indices:data/read/search[phase/query+fetch]]]; nested: NullPointerException; }
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAc
tion.java:228)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.ja
va:174)
        at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:821)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:799)
        at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:361)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: ; nested: NullPointerException;
        at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:386)
        at org.elasticsearch.action.search.SearchPhaseExecutionException.guessRootCauses(SearchPhaseExecutionException.java:152)
        at org.elasticsearch.action.search.SearchPhaseExecutionException.getCause(SearchPhaseExecutionException.java:99)
        at java.lang.Throwable.printStackTrace(Throwable.java:665)
        at java.lang.Throwable.printStackTrace(Throwable.java:721)
        at org.apache.log4j.DefaultThrowableRenderer.render(DefaultThrowableRenderer.java:60)
        at org.apache.log4j.spi.ThrowableInformation.getThrowableStrRep(ThrowableInformation.java:87)
        at org.apache.log4j.spi.LoggingEvent.getThrowableStrRep(LoggingEvent.java:413)
        at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:313)
        at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
        at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
        at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
        at org.apache.log4j.Category.callAppenders(Category.java:206)
        at org.apache.log4j.Category.forcedLog(Category.java:391)
        at org.apache.log4j.Category.log(Category.java:856)
        at org.elasticsearch.common.logging.log4j.Log4jESLogger.internalInfo(Log4jESLogger.java:125)
        at org.elasticsearch.common.logging.support.AbstractESLogger.info(AbstractESLogger.java:90)
        at org.elasticsearch.rest.BytesRestResponse.convert(BytesRestResponse.java:131)
        at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:96)
        at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:87)
        at org.elasticsearch.rest.action.support.RestActionListener.onFailure(RestActionListener.java:60)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.raiseEarlyFailure(TransportSearchTypeAct
ion.java:316)
        ... 10 more
Caused by: java.lang.NullPointerException
        at org.elasticsearch.index.fielddata.plain.ParentChildIndexFieldData.getOrdinalMap(ParentChildIndexFieldData.java:566)
        at org.elasticsearch.index.query.HasChildQueryParser$LateParsingQuery.rewrite(HasChildQueryParser.java:259)
        at org.apache.lucene.search.ConstantScoreQuery.rewrite(ConstantScoreQuery.java:55)
        at org.apache.lucene.search.BooleanQuery.rewrite(BooleanQuery.java:252)
        at org.apache.lucene.search.BooleanQuery.rewrite(BooleanQuery.java:252)
        at org.apache.lucene.search.IndexSearcher.rewrite(IndexSearcher.java:836)
        at org.elasticsearch.search.internal.ContextIndexSearcher.rewrite(ContextIndexSearcher.java:81)
        at org.elasticsearch.search.internal.DefaultSearchContext.preProcess(DefaultSearchContext.java:232)
        at org.elasticsearch.search.query.QueryPhase.preProcess(QueryPhase.java:103)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:674)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:618)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:461)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchSer
viceTransportAction.java:392)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchSer
viceTransportAction.java:389)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        ... 3 more
```

**Comment by clintongormley** [comment]
Simple recreation:

    PUT t
    {
      "mappings": {
        "parent": {},
        "child": {
          "_parent": {
            "type": "parent"
          }
        }
      }
    }
    
    PUT t/parent/1
    {}
    
    PUT t/child/2?parent=1
    {}
    
    GET _search
    {
      "query": {
        "has_parent": {
          "parent_type": "child",
          "query": {"match_all": {}}
        }
      }
    }

**Comment by clintongormley** [comment]
This is also broken in master
