### ISSUE TITLE
ES 2.2 java security feature breaks OSS plugins

### ISSUE THREAD

**Issue by sscarduzio** [elastic/elasticsearch#16714]
This problem was introduced in 2.2, works fine with 2.1.1 and lower.

I have an Elasticsearch opensource plugin that needs reflection to inspect the originating address of HTTP requests.

In ES 2.2 they introduced security permissions for plugins, following the instructions, I added a grant in the plugin-security.policy file with the following:
```
grant {
  permission java.lang.reflect.ReflectPermission "suppressAccessChecks";
};
```
Now upon installation of the plugin, I can see this (as anticipated in the docs). So I assume the request for permission is successfully kicking in.
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.reflect.ReflectPermission suppressAccessChecks
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
Installed readonlyrest into /elasticsearch/plugins/readonlyrest
```

However, from my function that actually uses reflection, still see this error...

```
java.security.AccessControlException: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")
    at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
    at java.security.AccessController.checkPermission(AccessController.java:884)
    at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
    at java.lang.reflect.AccessibleObject.setAccessible(AccessibleObject.java:128)
    at org.elasticsearch.plugin.readonlyrest.acl.blocks.rules.impl.HostsRule.getAddress(HostsRule.java:76)
    at org.elasticsearch.plugin.readonlyrest.acl.blocks.rules.impl.HostsRule.match(HostsRule.java:130)
    at org.elasticsearch.plugin.readonlyrest.acl.blocks.Block.check(Block.java:104)
    at org.elasticsearch.plugin.readonlyrest.acl.ACL.check(ACL.java:48)
    at org.elasticsearch.plugin.readonlyrest.ReadonlyRestAction$1.process(ReadonlyRestAction.java:60)
    at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:265)
```

Is there something missing? I have no clue.

**Comment by sscarduzio** [comment]
Nevermind, I needed to wrap the privileged  action in AccessController.doPrivileged.

**Comment by zaakiy** [comment]
Seeing the same issue on Elasticsearch 2.3.1
```
[root@ip-10-11-1-181 elasticsearch]# /usr/share/elasticsearch/bin/plugin install cloud-aws
-> Installing cloud-aws...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/cloud-aws/2.3.1/cloud-aws-2.3.1.zip ...
Downloading .............................................................................................................................................................................................................................................................................................................................................DONE
Verifying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/cloud-aws/2.3.1/cloud-aws-2.3.1.zip checksums if available ...
Downloading .DONE
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission getClassLoader
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]
```

**Comment by nik9000** [comment]
> Seeing the same issue on Elasticsearch 2.3.1

This message is intentional. That plugin wants more permissions than Elasticsearch wants so you get the message and you can decide if you trust the plugin and the permission.
