### ISSUE TITLE
Sort with a closure comparator doesn't work from groovy scripts

### ISSUE THREAD

**Issue by bra-fsn** [elastic/elasticsearch#16784]
**Elasticsearch version**: 2.2.0

**JVM version**:openjdk version "1.8.0_66"
OpenJDK Runtime Environment (build 1.8.0_66-b17)
OpenJDK 64-Bit Server VM (build 25.66-b17, mixed mode)

**OS version**: FreeBSD 10

**Description of the problem including expected versus actual behavior**: I would like to sort a list from a groovy script with a custom comparator. It fails.
I've already tried to disable groovy sandbox by setting
script.groovy.sandbox.enabled: false

**Steps to reproduce**:
Put this into a groovy script and call it:
`list=[1,2,3,4,5]
list.sort{ a, b ->
	if (a>b)
		return -1
	else if (a<b)
		return 1
	else
		return 0

}`

**Provide logs (if relevant)**:
`2016-02-2321:52:33,259][INFO` ][rest.suppressed          ] /a/b/c/_update Params: {index=a, id=b, type=c}
RemoteTransportException[[dev00][192.168.0.170:9301][indices:data/write/update[s]]]; nested: IllegalArgumentException[failed to execute script]; nested: ScriptException[failed to run file script [report] using lang [groovy]]; nested: NoClassDefFoundError[sun/reflect/MethodAccessorImpl]; nested: ClassNotFoundException[sun.reflect.MethodAccessorImpl];
Caused by: java.lang.IllegalArgumentException: failed to execute script
	at org.elasticsearch.action.update.UpdateHelper.executeScript(UpdateHelper.java:256)
	at org.elasticsearch.action.update.UpdateHelper.prepare(UpdateHelper.java:196)
	at org.elasticsearch.action.update.UpdateHelper.prepare(UpdateHelper.java:79)
	at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:170)
	at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:164)
	at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:65)
	at org.elasticsearch.action.support.single.instance.TransportInstanceSingleOperationAction$ShardTransportHandler.messageReceived(TransportInstanceSingleOperationAction.java:249)
	at org.elasticsearch.action.support.single.instance.TransportInstanceSingleOperationAction$ShardTransportHandler.messageReceived(TransportInstanceSingleOperationAction.java:245)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: ScriptException[failed to run file script [report] using lang [groovy]]; nested: NoClassDefFoundError[sun/reflect/MethodAccessorImpl]; nested: ClassNotFoundException[sun.reflect.MethodAccessorImpl];
	at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript.run(GroovyScriptEngineService.java:318)
	at org.elasticsearch.action.update.UpdateHelper.executeScript(UpdateHelper.java:251)
	... 12 more
Caused by: java.lang.NoClassDefFoundError: sun/reflect/MethodAccessorImpl
	at sun.misc.Unsafe.defineClass(Native Method)
	at sun.reflect.ClassDefiner.defineClass(ClassDefiner.java:63)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:399)
	at sun.reflect.MethodAccessorGenerator$1.run(MethodAccessorGenerator.java:394)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.MethodAccessorGenerator.generate(MethodAccessorGenerator.java:393)
	at sun.reflect.MethodAccessorGenerator.generateMethod(MethodAccessorGenerator.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:53)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.util.ClosureComparator.compare(ClosureComparator.java:39)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:356)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.sort(DefaultGroovyMethods.java:8476)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.sort(DefaultGroovyMethods.java:8438)
	at org.codehaus.groovy.runtime.dgm$566.doMethodInvoke(Unknown Source)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:218)
	at ae5d43c5eafaae31062b2722aa92b85ba22c61c7.run(ae5d43c5eafaae31062b2722aa92b85ba22c61c7:43)
	at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript$1.run(GroovyScriptEngineService.java:311)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript.run(GroovyScriptEngineService.java:308)
	... 13 more
Caused by: java.lang.ClassNotFoundException: sun.reflect.MethodAccessorImpl
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:677)
	at groovy.lang.GroovyClassLoader$InnerLoader.loadClass(GroovyClassLoader.java:425)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:787)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:775)
	... 42 more

`

**Comment by bra-fsn** [comment]
Ah, the upcoming 2.1 has the needed fix:
https://github.com/elastic/elasticsearch/commit/e63c87c14a201522a5b2290f6ac435c2fb791817
