### ISSUE TITLE
Proper handling exception

### ISSUE THREAD

**Issue by vsizov** [elastic/elasticsearch#16804]
**Elasticsearch version**:

2.1.1

**JVM version**:

 1.8.0_60

**OS version**:

Mac OS yosemite

**Description of the problem including expected versus actual behavior**:

If I'm testing undefined analyser the request will hang, instead it should return an error.

`curl -XGET 'localhost:9200/_analyze' -d ' {"analyzer" : "path_analyzer", "text" : "config/initialize/gitlab.yml" }'`

**Steps to reproduce**:
run `curl -XGET 'localhost:9200/_analyze' -d ' {"analyzer" : "path_analyzer", "text" : "config/initialize/gitlab.yml" }'`

**Provide logs (if relevant)**:
```
[2016-02-25 12:11:20,699][ERROR][transport                ] [Tomazooma] failed to handle exception for action [indices:admin/analyze[s]], handler [org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$1@1da2dd9e]
java.lang.NullPointerException
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.perform(TransportSingleShardAction.java:195)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.access$700(TransportSingleShardAction.java:115)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$1.handleException(TransportSingleShardAction.java:174)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:821)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:799)
	at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:361)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```
**Describe the feature**:

**Comment by jasontedor** [comment]
Duplicates #15148
