### ISSUE TITLE
ES 1.7 - failed to read local state, exiting... org.elasticsearch.ElasticsearchException 

### ISSUE THREAD

**Issue by mukeshkdangi** [elastic/elasticsearch#16818]
**Getting following error on running -  **

`elasticsearch --config=/usr/local/opt/elasticsearch17/config/elasticsearch.yml`

Error - (can't use ES 2.2 because of some application constraints)
aunchctl unload ~/Library/LaunchAgents/homebrew.mxcl.elasticsearch17.plist
```
MYMAC:etc mukesh$ launchctl load ~/Library/LaunchAgents/homebrew.mxcl.elasticsearch17.plist
MYMAC:etc mukesh$ elasticsearch --config=/usr/local/opt/elasticsearch17/config/elasticsearch.yml
[2016-02-26 17:01:13,895][INFO ][node                     ] [Mikado] version[1.7.5], pid[30437], build[00f95f4/2016-02-02T09:55:30Z]
[2016-02-26 17:01:13,896][INFO ][node                     ] [Mikado] initializing ...
[2016-02-26 17:01:13,964][INFO ][plugins                  ] [Mikado] loaded [], sites []
[2016-02-26 17:01:14,002][INFO ][env                      ] [Mikado] using [1] data paths, mounts [[/ (/dev/disk1)]], net usable_space [5.2gb], net total_space [111.8gb], types [hfs]
[2016-02-26 17:01:16,050][ERROR][gateway.local.state.shards] [Mikado] failed to read local state (started shards), exiting...
org.elasticsearch.ElasticsearchException: unexpected field in shard state [index_uuid]
	at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:153)
	at org.elasticsearch.gateway.local.state.meta.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:297)
	at org.elasticsearch.gateway.local.state.shards.LocalGatewayShardsState.loadShardStateInfo(LocalGatewayShardsState.java:188)
	at org.elasticsearch.gateway.local.state.shards.LocalGatewayShardsState.loadShardsStateInfo(LocalGatewayShardsState.java:173)
	at org.elasticsearch.gateway.local.state.shards.LocalGatewayShardsState.<init>(LocalGatewayShardsState.java:66)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
	at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:52)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
```

**Comment by bleskes** [comment]
The index_uuid field was added to the shard state in 2.0  (https://github.com/elastic/elasticsearch/pull/10093 ) . It seems you have installed ES 2.x and then downgrade to ES1.7. 1.7 can not read the state file made by 2.x (and many other files). This is expected and is by design. You sadly have two options - go back to 2.x or delete the data and reindex on 1.7

**Comment by mukeshkdangi** [comment]
i have already deleted the whole ES folder and purged ES 2.x, installed 1.7 ..still same error ..any suggestion ?

**Comment by bleskes** [comment]
@mukeshkdangi I don't know - this exception comes from reading too new state files...

**Comment by edwinlunando** [comment]
I got this problem too. I delete the elasticsearch data problem and fix the issue.

**Comment by nakamichikun** [comment]
Thanks edwinlunando, that's work.
