### ISSUE TITLE
ElasticsearchException[failed to create shard]; nested: AccessDeniedException

### ISSUE THREAD

**Issue by teewhey** [elastic/elasticsearch#16918]
I keep on getting this after I reboot the service.

[2016-03-03 02:20:15,998][WARN ][indices.cluster          ] [prod-elasticsearch-10-2-25-12] [[search_v2][2]] marking and sending shard failed due to [failed to create shard]
[search_v2][[search_v2][2]] ElasticsearchException[failed to create shard]; nested: AccessDeniedException[/mnt/elasticsearch/index-data/prod_elastic_cluster/nodes/0/indices/search_v2/2/_state];
	at org.elasticsearch.index.IndexService.createShard(IndexService.java:389)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyInitializingShard(IndicesClusterStateService.java:650)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewOrUpdatedShards(IndicesClusterStateService.java:550)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:179)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:494)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.AccessDeniedException: /mnt/elasticsearch/index-data/prod_elastic_cluster/nodes/0/indices/search_v2/2/_state
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:426)
	at java.nio.file.Files.newDirectoryStream(Files.java:413)
	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:257)
	at org.elasticsearch.index.shard.ShardPath.loadShardPath(ShardPath.java:122)
	at org.elasticsearch.index.IndexService.createShard(IndexService.java:311)
	... 9 more

A few shards are looping between UNASSIGNED & INITIALIZING.
I've checked the folder permission and it is correct. Any idea how can I fix this?

**Comment by jasontedor** [comment]
> I've checked the folder permission and it is correct. 

Are you sure? What user are you launching the Elasticsearch process as, and are you sure that that user has permissions for the resource in question? Be sure to check ownership and all of the `rwx` flags for the state file `/mnt/elasticsearch/index-data/prod_elastic_cluster/nodes/0/indices/search_v2/2/_state` and all parent directories.

**Comment by teewhey** [comment]
Yes I am sure... The owners for the folders and groups belongs to "elasticsearch" user that is used to launch the process.

The cluster was previously working until I did some relocation and restarted the cluster, that's when the issue started to happen. But I do notice this : 
On the data folder where one of the failing shard is (/mnt/elasticsearch/index-data/prod_elastic_cluster/nodes/0/indices/search_v2/3/_state)

ls -al
total 8
drwxr-xr-x 2 elasticsearch elasticsearch 4096 Mar  2 10:18 .
drw-r-xr-x 5 elasticsearch elasticsearch 4096 Mar  2 10:18 ..

The folder permission for '..' is not 755. Since there is no reason to manually changing the folder permission, I'd say these are handled by elasticsearch since those that are working has 755 permission on the ".." folder.

**Comment by jasontedor** [comment]
You've shown that the elasticsearch user does not have the executable permission for the parent directory. If the owner doesn't have the executable permission on the parent directory, it will not be able to read a subdirectory via an absolute path through that parent directory.

**Comment by teewhey** [comment]
My point is why ".." is created by elasticsearch as 655 instead of 755 since the creation of these directories are handled by elasticsearch.

**Comment by jasontedor** [comment]
> The cluster was previously working until I did some relocation

Are you sure that you didn't make commit an oops when you did the relocation?

> My point is why ".." is created by elasticsearch as 655 instead of 755 since the creation of these directories are handled by elasticsearch.

Elasticsearch uses the default permissions; do you have a `umask` set?

**Comment by teewhey** [comment]
The umask is set is 0022.
During the relocation, my job queue is still running, so very likely there was some commit ops happened during relocation.

**Comment by jasontedor** [comment]
> During the relocation, my job queue is still running, so very likely there was some commit ops happened during relocation.

Just fix the permissions and you'll be fine. :smile:

**Comment by teewhey** [comment]
Yeah.. already done that earlier when i presented the finding earlier : )
