### ISSUE TITLE
[CI] IndexWithShadowReplicasIT failures after writeLockTimeout removed from Engine

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#16936]
This reproduces pretty frequently (but not all the time):

```
Caused by: [test][[test][0]] EngineCreationFailureException[failed to create engine]; nested: LockObtainFailedException[Lock held elsewhere: /var/lib/jenkins/jobs/elasticsearch/workspace/core/build/testrun/integTest/J4/temp/org.elasticsearch.index.IndexWithShadowReplicasIT_E1ABD5E13715F0B9-001/tempDir-007/test/0/index/write.lock]; nested: FileAlreadyExistsException[/var/lib/jenkins/jobs/elasticsearch/workspace/core/build/testrun/integTest/J4/temp/org.elasticsearch.index.IndexWithShadowReplicasIT_E1ABD5E13715F0B9-001/tempDir-007/test/0/index/write.lock];
11:46:57   1>    at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:151)
11:46:57   1>    at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
11:46:57   1>    at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1316)
11:46:57   1>    at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1302)
11:46:57   1>    at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:892)
11:46:57   1>    at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:865)
11:46:57   1>    at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:226)
11:46:57   1>    ... 9 more
```

I've marked the suite with `AwaitsFix` (f9d1f95e846e7aae6d431fba3031d61a3bb3b1ee) as @s1monw mentioned it's simple until he gets a chance to fix it.

**Comment by dakrone** [comment]
Related issue: https://github.com/elastic/elasticsearch/pull/16930
