### ISSUE TITLE
NoNodeAvailableException when use BulkRequest

### ISSUE THREAD

**Issue by davidcai19840412** [elastic/elasticsearch#16970]
**Elasticsearch version**:2.1.0

**JVM version**: 1.7

**Description of the problem including expected versus actual behavior**:

NoNodeAvailableException when use BulkRequest

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:
[03-05 22:17:26,154] ERROR [][][Thread-7] c.y.s.common.canal.BaseCanalClient[126] - process error!
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{localhost/127.0.0.1:4593}]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:286) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:351) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59) ~[elasticsearch-2.2.0.jar:2.2.0]
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:67) ~[elasticsearch-2.2.0.jar:2.2.0]
	at com.yuanpin.slora.es.base.BaseIndexType.handleEvents(BaseIndexType.java:431) ~[slora.biz-2.0-SNAPSHOT.jar:na]
	at com.yuanpin.slora.common.canal.CanalEventRegister.trigger(CanalEventRegister.java:81) ~[slora.common-2.0-SNAPSHOT.jar:na]
	at com.yuanpin.slora.common.canal.BaseCanalClient.process(BaseCanalClient.java:114) ~[slora.common-2.0-SNAPSHOT.jar:na]
	at com.yuanpin.slora.common.canal.BaseCanalClient$2.run(BaseCanalClient.java:68) [slora.common-2.0-SNAPSHOT.jar:na]
	at java.lang.Thread.run(Thread.java:722) [na:1.7.0_17]

**Comment by clintongormley** [comment]
It sounds like your transport client can't connect to any nodes.

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
