### ISSUE TITLE
IllegalArgumentException[mapper [cells] of different type, current_type [string], merged_type [long]]

### ISSUE THREAD

**Issue by soenter** [elastic/elasticsearch#17092]
at org.elasticsearch.index.mapper.DocumentParser.innerParseDocument(DocumentParser.java:163)
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:79)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:304)
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:547)
	at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:529)
	at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:211)
	at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:223)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:157)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:65)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:595)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:263)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:260)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

JSON:
{"key":"46c0a372-cd9f-48c1-9afe-165e5ce5af4d","cells":[["2015-04-03 16\\:32\\:18:","",1428050312047000],["2015-04-03 16\\:32\\:18:business","wk",1428050312047000],["2015-04-03 16\\:32\\:18:caller","smp",1428050312047000],["2015-04-03 16\\:32\\:18:contextid","63CE89409EE6448555832BC08496B204-n2.work1",1428050312047000],["2015-04-03 16\\:32\\:18:customenv","{\"ip\":\"49.83.17.189\"}",1428050312047000],["2015-04-03 16\\:32\\:18:data_info","{\"transaction\":{\"merchant\":{\"mid\":\"888002189990019\"},\"orderhead\":{\"orderId\":\"150403A00005196\",\"orderType\":\"0005\",\"orderCount\":1,\"orderAmount\":200.00,\"transAmount\":200.00,\"stat\":\"00\",\"currency\":\"156\"},\"orderdetail\":{\"pay\":{\"payId\":\"150403P00005132\",\"payKid\":\"02\",\"payTid\":\"A04\",\"payOrgid\":\"B0000001\",\"payAmount\":200.00,\"payDisAmount\":0.00,\"payFee\":0.00,\"currency\":\"156\",\"medium\":\"8188310700233874\",\"stat\":\"P0\"},\"rec\":{\"recId\":\"150403E0002821\",\"accountNo\":\"8867200950010700\",\"accountType\":\"01\",\"recAmount\":200.00,\"recDisAmount\":0.00,\"recFee\":0.00,\"currency\":\"156\",\"stat\":\"C0\"}}}}",1428050312047000],["2015-04-03 16\\:32\\:18:eventtype","0002",1428050312047000],["2015-04-03 16\\:32\\:18:exchange","asynchronous",1428050312047000],["2015-04-03 16\\:32\\:18:format","json",1428050312047000],["2015-04-03 16\\:32\\:18:method","com.sand.risk.service.smp.transanalysis.TransAnalysis",1428050312047000],["2015-04-03 16\\:32\\:18:stats","1",1428050312047000],["2015-04-03 16\\:32\\:18:terminal_info","data-not-found",1428050312047000],["2015-04-03 16\\:32\\:18:terminal_type","web",1428050312047000],["2015-04-03 16\\:32\\:18:user","{\"id\":\"61546\",\"name\":\"13851126055\",\"phone\":\"13851126055\",\"email\":\"wbww888@163.com\"}",1428050312047000],["2015-04-03 16\\:32\\:18:utime","2015-04-03 16:37:47",1428050312047000],["2015-04-03 16\\:32\\:18:version","2.0.0",1428050312047000]]}

My json format is correct, why is there this exception ?

**Comment by dadoonet** [comment]
Sounds like `cells` has incorrect mapping. Was an array of `String` but you are now passing also a long value `1428050312047000`...

But please join us on discuss.elastic.co if you have questions like this.
This space is only for confirmed issues.

**Comment by 7leafcom** [comment]
I can into this issue with dynamic mapping on version 2.4.1. The data is pretty much the same, but it works on one index and not on the other. Very strange. I'm trying to narrow it down.

http://stackoverflow.com/questions/40541125/inconsistent-mapperparsingexception-on-elasticsearch-2-4-1
