### ISSUE TITLE
_analyze never responds given an unknown tokenizer

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#17119]
I came across this while trying to see the English analyzer, but I forgot to change `tokenizer` to `analyzer`.

```
GET /_analyze
{
  "tokenizer" : "english",
  "text" : "whatever"
}
```

The only error that comes out of Elasticsearch (tested on 2.2.0 and 2.1.1) is an obscure one:

```
[2016-03-15 14:52:11,050][ERROR][transport                ] [Jessica Drew] failed to handle exception for action [indices:admin/analyze[s]], handler [org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$1@4ffecb71]
java.lang.NullPointerException
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.perform(TransportSingleShardAction.java:195)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.access$700(TransportSingleShardAction.java:115)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$1.handleException(TransportSingleShardAction.java:174)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:821)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:799)
	at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:361)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Worse still, it never actually closes the connection so the request hangs, awaiting a response (probably indicating a secondary bug in this code path).

**Comment by gmoskovicz** [comment]
:+1: :bug:

**Comment by clintongormley** [comment]
Duplicates #15148, closed by #15447

**Comment by jasontedor** [comment]
Duplicates #15148, closed by #15447

**Comment by clintongormley** [comment]
Too slow, @jasontedor !

**Comment by pickypg** [comment]
Ugh, I searched for _analyze!
