### ISSUE TITLE
Fetch phase should not init a LeafSearchLookup for each document with groovy script

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#17110]
In 2.2 when someone uses a script field then a new `LeafSearchLookup` is created for each document that is fetched via the call stack below. This is unfortunate if the documents are fetched with scan and scroll because this renders the caches in `LeafDocLookup` and `LeafFieldsLookup` and  `LeafIndexLookup` useless. 

```
        at org.elasticsearch.search.lookup.IndexLookup.getLeafIndexLookup(IndexLookup.java:69)
    at org.elasticsearch.search.lookup.SearchLookup.getLeafSearchLookup(SearchLookup.java:57)
    at org.elasticsearch.script.groovy.GroovyScriptEngineService$4.getLeafSearchScript(GroovyScriptEngineService.java:236)
    at org.elasticsearch.search.fetch.script.ScriptFieldsFetchSubPhase.hitExecute(ScriptFieldsFetchSubPhase.java:77)
    at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:187)
    at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:478)

```

**Comment by clintongormley** [comment]
@jpountz is this fixed?

**Comment by javanna** [comment]
This is related to groovy scripts, which were removed, so I think we can close this issue. agreed @jpountz ?

**Comment by jpountz** [comment]
This issue is not really specific to Groovy and still exists. I opened #26775 to replace this one.

**Comment by javanna** [comment]
thanks a lot Adrien.
