### ISSUE TITLE
Can't run snapshot build of elasticsearch 5.0 with plugins

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#17166]
**Elasticsearch version**: 
5.0.0-SNAPSHOT (build from master using `gradle assemble`

**JVM version**: 
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**OS version**:
OSX El Capitan Version 10.11.3 (15D21)

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

**Scenario 1**:
 1. Build a snapshot build from master using `gradle assemble`
 2. Extract tar.gz
 3. Run bin/elasticsearch
 4.Start up of the node fails due to the following exception 

[2016-03-17 11:34:31,066][INFO ][node                     ] [Captain Savage] version[5.0.0-SNAPSHOT], pid[4048], build[da24bfe/2016-03-17T11:23:11.636Z]
[2016-03-17 11:34:31,068][INFO ][node                     ] [Captain Savage] initializing ...
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [ingest-grok] is incompatible with Elasticsearch [5.0.0]. Was designed for version [3.0.0-SNAPSHOT]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:100)
	at org.elasticsearch.plugins.PluginsService.getModuleBundles(PluginsService.java:304)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:117)
	at org.elasticsearch.node.Node.<init>(Node.java:187)
	at org.elasticsearch.node.Node.<init>(Node.java:168)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:188)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:262)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:108)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:103)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
	at org.elasticsearch.cli.Command.main(Command.java:53)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)
Refer to the log for complete error details.

**Scenario 2**:
 1. Build a snapshot build from master using `gradle assemble`
 2. Extract tar.gz
 3. Try to install one of the built plugins using `bin/elasticsearch-plugin install file:///Path/to/built/S3-plugin.zip
 4.Installing the plugin fails due to the following exception 

Plugins directory [/Users/me/elasticsearch-5.0.0-SNAPSHOT/plugins] does not exist. Creating...
-> Downloading file:///Users/me/repository-s3-5.0.0-SNAPSHOT.zip
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [repository-s3] is incompatible with Elasticsearch [5.0.0]. Was designed for version [3.0.0-SNAPSHOT]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:100)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:287)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:345)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:169)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:155)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
	at org.elasticsearch.cli.Command.main(Command.java:53)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:45)

It looks like the versioning process in the release/branching might not be updating the versions in the `plugin-descriptor.properties` for both plugins and modules

**Comment by jasontedor** [comment]
@colings86 I think that you just need to do a `gradle clean`. Can you verify if that fixes the issue for you?

**Comment by colings86** [comment]
@jasontedor yep you are right, a `gradle clean` fixed it. Sorry for the noise
