### ISSUE TITLE
CI: CancellableTasksTests fails with uncaught exception

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#17169]
Saw this several times in the last 12 hours on the 2.x and 2.3 branch:

```
Suite: org.elasticsearch.action.admin.cluster.node.tasks.CancellableTasksTests
  2> mrt 17, 2016 3:53:26 PM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
  2> WARNING: Uncaught exception in thread: Thread[elasticsearch[TransportTasksActionTests][generic][T#8],5,TGRP-CancellableTasksTests]
  2> EsRejectedExecutionException[rejected execution of org.elasticsearch.transport.TransportService$3@2c0ff1dc on EsThreadPoolExecutor[generic, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@22c80a2d[Shutting down, pool size = 4, active threads = 4, queued tasks = 0, completed tasks = 62]]]
  2> 	at __randomizedtesting.SeedInfo.seed([D7BCB71B5D341091]:0)
  2> 	at org.elasticsearch.common.util.concurrent.EsAbortPolicy.rejectedExecution(EsAbortPolicy.java:50)
  2> 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
  2> 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
  2> 	at org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor.execute(EsThreadPoolExecutor.java:85)
  2> 	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:341)
  2> 	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:299)
  2> 	at org.elasticsearch.action.admin.cluster.node.tasks.cancel.TransportCancelTasksAction.sendRemoveBanRequest(TransportCancelTasksAction.java:205)
  2> 	at org.elasticsearch.action.admin.cluster.node.tasks.cancel.TransportCancelTasksAction.removeBanOnNodes(TransportCancelTasksAction.java:166)
  2> 	at org.elasticsearch.action.admin.cluster.node.tasks.cancel.TransportCancelTasksAction.access$000(TransportCancelTasksAction.java:63)
  2> 	at org.elasticsearch.action.admin.cluster.node.tasks.cancel.TransportCancelTasksAction$3.accept(TransportCancelTasksAction.java:130)
  2> 	at org.elasticsearch.action.admin.cluster.node.tasks.cancel.TransportCancelTasksAction$3.accept(TransportCancelTasksAction.java:127)
  2> 	at org.elasticsearch.action.admin.cluster.node.tasks.cancel.TransportCancelTasksAction$BanLock.finish(TransportCancelTasksAction.java:238)
  2> 	at org.elasticsearch.action.admin.cluster.node.tasks.cancel.TransportCancelTasksAction$BanLock.onBanSet(TransportCancelTasksAction.java:226)
  2> 	at org.elasticsearch.action.admin.cluster.node.tasks.cancel.TransportCancelTasksAction$5.handleException(TransportCancelTasksAction.java:187)
  2> 	at org.elasticsearch.transport.TransportService$2.run(TransportService.java:206)
  2> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  2> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  2> 	at java.lang.Thread.run(Thread.java:745)
  2> 
  2> REPRODUCE WITH: mvn test -Pdev -pl org.elasticsearch:elasticsearch -Dtests.seed=D7BCB71B5D341091 -Dtests.class=org.elasticsearch.action.admin.cluster.node.tasks.CancellableTasksTests -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=en-US -Dtests.timezone=Etc/UTC
  2> NOTE: test params are: codec=Asserting(Lucene54): {}, docValues:{}, sim=RandomSimilarity(queryNorm=true,coord=yes): {}, locale=nl-BE, timezone=Asia/Novosibirsk
  2> NOTE: Linux 3.13.0-74-generic amd64/Oracle Corporation 1.8.0_72-internal (64-bit)/cpus=4,threads=1,free=451774008,total=530579456
  2> NOTE: All tests run in this JVM: [NullValueObjectMappingTests, IndexSearcherWrapperTests, CompletionFieldMapperTests, VersionLookupTests, CommonTermsQueryParserTests, NamingConventionTests, ScriptContextRegistryTests, NettyTransportTests, TransportModuleTests, MustacheTests, AnalyzerBackwardsCompatTests, FileUtilsTests, TableTests, SettingsValidatorTests, FilterFieldDataTests, ExpectedShardSizeAllocationTests, ClusterStateHealthTests, IndexingMemoryControllerTests, DocumentFieldMapperTests, PluginManagerUnitTests, UniqueTokenFilterTests, SortedSetDVStringFieldDataTests, LuceneTests, TransportClientHeadersTests, DiskThresholdDeciderUnitTests, PrimaryNotRelocatedWhileBeingRecoveredTests, GatewayServiceTests, GeoUtilsTests, KeepTypesFilterFactoryTests, IndicesServiceTests, EsExecutorsTests, RetryTests, FileInfoTests, CustomBoostMappingTests, Base64Tests, TransportTasksActionTests, PreBuiltTokenFilterFactoryFactoryTests, IndexTypeMapperTests, IndexFieldDataServiceTests, PutWarmerRequestTests, PathMapperTests, ReplicaAllocatedAfterPrimaryTests, SourceFieldTypeTests, FilterPathGeneratorFilteringTests, MinScoreScorerTests, JsonXContentTests, UpdateRequestTests, RestApiParserTests, ClusterSerializationTests, ParentQueryTests, ShadowEngineTests, CodecTests, ScriptSortBuilderTests, XContentHelperTests, CompressSourceMappingTests, MetaDataTests, ThrottlingAllocationTests, FilterRoutingTests, StringFieldMapperPositionIncrementGapTests, BlacklistedPathPatternMatcherTests, RecoveriesCollectionTests, MetaStateServiceTests, ConcurrentRecyclerTests, TransportReplicationActionTests, SimpleDateMappingTests, XMoreLikeThisTests, NoisyChannelSpellCheckerTests, DeflateXContentTests, MemoryCircuitBreakerTests, IndexStoreBWCTests, TribeUnitTests, IndexRequestBuilderTests, InternalTestClusterTests, SnowballAnalyzerTests, PreferLocalPrimariesToRelocatingPrimariesTests, ParseDocumentTypeLevelsTests, ProfileTests, CountResponseTests, BinaryFieldTypeTests, StopTokenFilterTests, ZenFaultDetectionTests, BigArraysTests, ParseFieldTests, GeoShapeFieldTypeTests, LongHashTests, ChildrenConstantScoreQueryTests, PlainHighlighterTests, VectorHighlighterTests, LongFieldTypeTests, ClassPermissionTests, DynamicMappingTests, JacksonLocationTests, ShapeBuilderTests, RestAnalyzeActionTests, SeccompTests, BoundTransportAddressTests, SingleObjectCacheTests, CopyOnWriteHashMapTests, SetupSectionParserTests, TimeZoneRoundingTests, GeoPointFieldMapperTests, ScriptParameterParserTests, ProcessProbeTests, StringFieldTypeTests, UpdateThreadPoolSettingsTests, DiskUsageTests, SearchServiceTests, SmileFilteringGeneratorTests, TypeFieldTypeTests, ByteFieldTypeTests, NestedAggregatorTests, SloppyMathTests, NetworkAddressTests, SingleOrdinalsTests, NodeEnvironmentTests, DeadNodesAllocationTests, RoutingServiceTests, HppcMapsTests, NumericAnalyzerTests, IndicesOptionsTests, ZenDiscoveryUnitTests, ShardUtilsTests, DuelFieldDataTests, MergePolicySettingsTests, IndexQueryParserFilterDateRangeTimezoneTests, ThreadPoolSerializationTests, SimpleDynamicTemplatesTests, NetworkUtilsTests, LZFXContentTests, ESDirectoryReaderTests, SyncedFlushUnitTests, StoreTests, PathTests, CheckFileCommandTests, IndexAliasesServiceTests, CompoundAnalysisTests, ReplicaShardAllocatorTests, RefCountedTests, DistanceUnitTests, CustomPassageFormatterTests, CustomPostingsHighlighterTests, ExceptionSerializationTests, OriginalIndicesTests, ClusterHealthResponsesTests, CancellableTasksTests]
ERROR   0.00s J1 | CancellableTasksTests (suite) <<<
   > Throwable #1: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=1259, name=elasticsearch[TransportTasksActionTests][generic][T#8], state=RUNNABLE, group=TGRP-CancellableTasksTests]
   > Caused by: EsRejectedExecutionException[rejected execution of org.elasticsearch.transport.TransportService$3@2c0ff1dc on EsThreadPoolExecutor[generic, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@22c80a2d[Shutting down, pool size = 4, active threads = 4, queued tasks = 0, completed tasks = 62]]]
   > 	at __randomizedtesting.SeedInfo.seed([D7BCB71B5D341091]:0)
   > 	at org.elasticsearch.common.util.concurrent.EsAbortPolicy.rejectedExecution(EsAbortPolicy.java:50)
   > 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
   > 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
   > 	at org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor.execute(EsThreadPoolExecutor.java:85)
   > 	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:341)
   > 	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:299)
   > 	at org.elasticsearch.action.admin.cluster.node.tasks.cancel.TransportCancelTasksAction.sendRemoveBanRequest(TransportCancelTasksAction.java:205)
   > 	at org.elasticsearch.action.admin.cluster.node.tasks.cancel.TransportCancelTasksAction.removeBanOnNodes(TransportCancelTasksAction.java:166)
   > 	at org.elasticsearch.action.admin.cluster.node.tasks.cancel.TransportCancelTasksAction.access$000(TransportCancelTasksAction.java:63)
   > 	at org.elasticsearch.action.admin.cluster.node.tasks.cancel.TransportCancelTasksAction$3.accept(TransportCancelTasksAction.java:130)
   > 	at org.elasticsearch.action.admin.cluster.node.tasks.cancel.TransportCancelTasksAction$3.accept(TransportCancelTasksAction.java:127)
   > 	at org.elasticsearch.action.admin.cluster.node.tasks.cancel.TransportCancelTasksAction$BanLock.finish(TransportCancelTasksAction.java:238)
   > 	at org.elasticsearch.action.admin.cluster.node.tasks.cancel.TransportCancelTasksAction$BanLock.onBanSet(TransportCancelTasksAction.java:226)
   > 	at org.elasticsearch.action.admin.cluster.node.tasks.cancel.TransportCancelTasksAction$5.handleException(TransportCancelTasksAction.java:187)
   > 	at org.elasticsearch.transport.TransportService$2.run(TransportService.java:206)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   > 	at java.lang.Thread.run(Thread.java:745)
Completed [345/556 (1!)] on J1 in 0.36s, 2 tests, 1 error <<< FAILURES!
```

This is from: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+2.3+multijob-os-compatibility/os=ubuntu/4/ 

but it also happened earlier on 2.x, e.g.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+2.x+periodic/96/
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+2.x+multijob-os-compatibility/os=fedora/42/
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+2.x+multijob-os-compatibility/os=ubuntu/42/

I wasn't able to reproduce the failure locally yet. 
@imotov, @nik9000 is this something you could take a look at?

**Comment by imotov** [comment]
I think we need to backport 8652cd8 to 2.x, 2.3 as well as get #16965 to get rid of these.

**Comment by nik9000** [comment]
I knew I saw a thing about this. I can have a look at it in a few hours if no one else gets to it.

**Comment by nik9000** [comment]
Ok - if you backport 8652cd8aa3eb03ac10c53be8be7ad75f2a3e1175 you have to backport 17e28d05b75f092ab7f2ee2a20230ab5dc4bfc88. That test starts failing once you backport the first change and it looks like the logic in 17e28d05b75f092ab7f2ee2a20230ab5dc4bfc88 holds in 2.3/2.x so I'll just backport both.

@s1monw if you have any objections to this then reply and I'll revert them.

**Comment by nik9000** [comment]
2.3: d32c7fb8a89e92d3ce63b266222cedaa9832818c and a0df1479a6882c85f3619bf196fb326f26774a1d
2.x: 114001db60bb01741c7de70dd8cb147af4183207 and 8c053bd92e89166cb0e2a5efe09fbb62b5fc2132
