### ISSUE TITLE
elasticsearch does not start / gradle build totally broken with JDK 9 build 110

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#17171]
With the latest java 9 ea (110), a compiled version will not work at all.
Maybe we are doing something illegal/sheisty to retrieve the PID, maybe its a bug.

```
rmuir@beast:~/workspace/elasticsearch/distribution/zip/build/distributions/elasticsearch-5.0.0-SNAPSHOT$ bin/elasticsearch
Java HotSpot(TM) 64-Bit Server VM warning: Option UseParNewGC was deprecated in version 9.0 and will likely be removed in a future release.
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class java.lang.management.ManagementFactory$PlatformMBeanFinder
    at java.lang.management.ManagementFactory.getPlatformMXBean(ManagementFactory.java:649)
    at java.lang.management.ManagementFactory.getRuntimeMXBean(ManagementFactory.java:355)
    at org.elasticsearch.monitor.jvm.JvmInfo.<clinit>(JvmInfo.java:53)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:245)
    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:108)
    at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:103)
    at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
    at org.elasticsearch.cli.Command.main(Command.java:53)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)
Refer to the log for complete error details.
```

Also gradle itself eats it early and does not work at all:

```
rmuir@beast:~/workspace/elasticsearch$ gradle --stacktrace clean

FAILURE: Build failed with an exception.

* What went wrong:
sun.management.spi.PlatformMBeanProvider: Provider jdk.management.cmm.internal.PlatformMBeanProviderImpl not found

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.util.ServiceConfigurationError: sun.management.spi.PlatformMBeanProvider: Provider jdk.management.cmm.internal.PlatformMBeanProviderImpl not found
    at java.util.ServiceLoader.fail(ServiceLoader.java:237)
    at java.util.ServiceLoader.access$300(ServiceLoader.java:183)
    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:402)
    at java.util.ServiceLoader$1.next(ServiceLoader.java:478)
    at java.lang.Iterable.forEach(Iterable.java:74)
    at java.lang.management.ManagementFactory$PlatformMBeanFinder.lambda$static$0(ManagementFactory.java:890)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessController.doPrivileged(AccessController.java:428)
    at java.lang.management.ManagementFactory$PlatformMBeanFinder.<clinit>(ManagementFactory.java:886)
    at java.lang.management.ManagementFactory.getPlatformMXBean(ManagementFactory.java:649)
    at java.lang.management.ManagementFactory.getRuntimeMXBean(ManagementFactory.java:355)
    at org.gradle.launcher.daemon.configuration.CurrentProcess.inferJvmOptions(CurrentProcess.java:71)
    at org.gradle.launcher.daemon.configuration.CurrentProcess.<init>(CurrentProcess.java:33)
    at org.gradle.launcher.cli.BuildActionsFactory.canUseCurrentProcess(BuildActionsFactory.java:95)
    at org.gradle.launcher.cli.BuildActionsFactory.createAction(BuildActionsFactory.java:72)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.createAction(CommandLineActionFactory.java:242)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:232)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
    at org.gradle.launcher.Main.doAction(Main.java:33)
    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:520)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
```

**Comment by rmuir** [comment]
@uschindler tells me he is digging in a bit.

**Comment by uschindler** [comment]
Lucene fails with similar error (just hidden):
RamUsageEstimator tries to get the PlatformMXBean and fails with above error message. Because of this it say "no hotspot available".

The test of RamUsageEstimator does some assertions and fails because of this (it sees a 64 bit Oracle JVM, but no hotspot bean -> boom):

```
java.lang.AssertionError: We should have been able to detect Hotspot's internal settings from the management bean.
	at __randomizedtesting.SeedInfo.seed([4E4F519BECD7B56E:F467726384B9DE51]:0)
	at org.junit.Assert.fail(Assert.java:93)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at org.apache.lucene.util.TestRamUsageEstimator.testHotspotBean(TestRamUsageEstimator.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:520)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1764)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:871)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:907)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:921)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:809)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:460)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:880)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:781)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:816)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:827)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
	at java.lang.Thread.run(Thread.java:804)
```

**Comment by uschindler** [comment]
In addition, the Junit4 test runner canot display the PID of test JVMs:
```
  [junit4] Started J2 PID(<pid acquire exception: java.util.ServiceConfigurationError: sun.management.spi.PlatformMBeanProvider: Provider jdk.management.cmm.internal.PlatformMBeanProviderImpl not found>).
   [junit4] Started J0 PID(<pid acquire exception: java.util.ServiceConfigurationError: sun.management.spi.PlatformMBeanProvider: Provider jdk.management.cmm.internal.PlatformMBeanProviderImpl not found>).
   [junit4] Started J1 PID(<pid acquire exception: java.util.ServiceConfigurationError: sun.management.spi.PlatformMBeanProvider: Provider jdk.management.cmm.internal.PlatformMBeanProviderImpl not found>).
```

**Comment by uschindler** [comment]
Here is my reproducer, I will open issue at OpenJDK:

```
import java.lang.management.ManagementFactory;
import com.sun.management.HotSpotDiagnosticMXBean;

public final class Test {
 
  public static void main(String... args) throws Throwable {
    ManagementFactory.getPlatformMXBean(HotSpotDiagnosticMXBean.class);
  } 
   
}
```

If you run this program -> boom.

**Comment by uschindler** [comment]
It also fails if you ask for the standard runtime bean (like gradle). You don't even need to ask for the hotspot bean. Any platform bean fails. So `ManagementFactory.getRuntimeMXBean()` fails the same way.

**Comment by uschindler** [comment]
@s1monw 's garbage collector stats also fail (BTW: same applies for Solr).

**Comment by hub-cap** [comment]
No longer relevant as we are running java 9 w/ elasticsearch and gradle now
