### ISSUE TITLE
Tests seems to ignore plugin-security.policy

### ISSUE THREAD

**Issue by cadu-goncalves** [elastic/elasticsearch#17175]
**Elasticsearch version**: 2.2.1

**JVM version**: 1.8

**OS version**: Windows 7 64bits

**Description of the problem including expected versus actual behavior**:
My Maven project applies the security conventions described here https://www.elastic.co/guide/en/elasticsearch/plugins/2.2/plugin-authors.html#_java_security_permissions. However I'm getting some problems related with security manager inside my unit tests.
 
I've picked a test case from Elasticsearch Attachments plugin to help me to find the problem. When I run the testcase 'org.elasticsearch.mapper.attachments.TikaDocTests' from original project using Gradle it works fine (no SecurityExceptions), but if I copy it "as is" to my Maven project and I run it I get many SecurityExceptions related with Tika (all the permissions I wrote in my plugin-security.policy are the same used by the Attachments plugin).

I also noticed that no matter what I wrote in plugin-security.policy file, the tests work the same, it seems to be ignored.

**Steps to reproduce**: Not applies

**Provide logs (if relevant)**:
Caused by: java.lang.SecurityException: Unable to create temporary file or directory
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:143)
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
	at java.nio.file.Files.createTempFile(Files.java:897)
	at org.apache.tika.io.TemporaryResources.createTempFile(TemporaryResources.java:79)
	at org.apache.tika.io.TikaInputStream.getPath(TikaInputStream.java:586)
	at org.apache.tika.io.TikaInputStream.getFile(TikaInputStream.java:615)
	at org.apache.tika.parser.pkg.ZipContainerDetector.detectZipFormat(ZipContainerDetector.java:143)
	at org.apache.tika.parser.pkg.ZipContainerDetector.detect(ZipContainerDetector.java:90)
	at org.apache.tika.detect.CompositeDetector.detect(CompositeDetector.java:77)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:112)
	at org.apache.tika.Tika.parseToString(Tika.java:496)
	at org.apache.tika.Tika.parseToString(Tika.java:571)

**Describe the feature**: Test framework

**Comment by cadu-goncalves** [comment]
Here is a Maven project that shows the error.
[myplugin.zip](https://github.com/elastic/elasticsearch/files/178493/myplugin.zip)

**Comment by cadu-goncalves** [comment]
The only way to make the tests work obsously, is by disabling the Security Manager:
`$ mvn clean test -Dtests.security.manager=false`

Of course it is a poor workaround, we need to test against Security Manager.

**Comment by rjernst** [comment]
@cadu-goncalves For unit tests to work with the added permissions, you need to have both your plugin properties and plugins security files in test resources. Notice that the tika plugin uses the plugin parent pom, which handles this.
https://github.com/elastic/elasticsearch/blob/2.x/plugins/mapper-attachments/pom.xml

**Comment by cadu-goncalves** [comment]
Thanks @rjernst

**Comment by cadu-goncalves** [comment]
Adding both plugin-descriptor.properties and plugin-security.policy at root of test resources solved the problem. Thank you very much!
