### ISSUE TITLE
Groovy script does not work with 'each' function

### ISSUE THREAD

**Issue by sergfed** [elastic/elasticsearch#17194]
**Elasticsearch version**:

2.2.0

**JVM version**:

1.8.0_73

**OS version**:

Windows

**Description of the problem including expected versus actual behavior**:

Seems that script is cached and in this state stops work with 'each' function.

**Steps to reproduce**:

Simplified example. Please do not seek sense in it )

 1. POST http://localhost:9200/testindex/testtype/testid/_update
`{
	"script" : {
		"inline" : "stats.each { key = it.getKey(); value = stats[key]; ctx._source.visits = value.visits; }",
		"params" : {
			"stats" : {
				"internal" : {
					"visits" : 10
				},
				"external" : {
					"visits" : 20
				}
			}
		}
	},
	"upsert" : {
		"visits" : 10
	}
}`
 2. Repeat step 1 until it stops work. It may happen on the second time or on the 20th. You will get an error
`{
	"error" : {
		"root_cause" : [{
				"type" : "remote_transport_exception",
				"reason" : "[nodename][127.0.0.1:9300][indices:data/write/update[s]]"
			}
		],
		"type" : "illegal_argument_exception",
		"reason" : "failed to execute script",
		"caused_by" : {
			"type" : "script_exception",
			"reason" : "failed to run inline script [stats.each { key = it.getKey(); value = stats[key];  ctx._source.visits = value.visits; }] using lang [groovy]",
			"caused_by" : {
				"type" : "no_class_def_found_error",
				"reason" : "sun/reflect/MethodAccessorImpl",
				"caused_by" : {
					"type" : "class_not_found_exception",
					"reason" : "sun.reflect.MethodAccessorImpl"
				}
			}
		}
	},
	"status" : 400
}
`
 3. If you change inline script (you can simply insert a space) then it starts work. Then go to step 2.

**Provide logs (if relevant)**:

From elastic log:
`[INFO ][rest.suppressed          ] /testindex/testtype/testid/_update Params: {index=testindex, id=testid, type=testtype}
RemoteTransportException[[nodename][127.0.0.1:9300][indices:data/write/update[s]]]; nested: IllegalArgumentException[failed to execute script]; nested: ScriptException[failed to run inline script [stats.each { key = it.getKey(); value = stats[key]; ctx._source.visits = value.visits; }] using lang [groovy]]; nested: NoClassDefFoundError[sun/reflect/MethodAccessorImpl]; nested: ClassNotFoundException[sun.reflect.MethodAccessorImpl];
Caused by: java.lang.IllegalArgumentException: failed to execute script
	at org.elasticsearch.action.update.UpdateHelper.executeScript(UpdateHelper.java:256)
	at org.elasticsearch.action.update.UpdateHelper.prepare(UpdateHelper.java:196)
	at org.elasticsearch.action.update.UpdateHelper.prepare(UpdateHelper.java:79)
	at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:170)
	at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:164)
	at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:65)
	at org.elasticsearch.action.support.single.instance.TransportInstanceSingleOperationAction$ShardTransportHandler.messageReceived(TransportInstanceSingleOperationAction.java:249)
	at org.elasticsearch.action.support.single.instance.TransportInstanceSingleOperationAction$ShardTransportHandler.messageReceived(TransportInstanceSingleOperationAction.java:245)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: ScriptException[failed to run inline script [stats.each { key = it.getKey(); value = stats[key]; ctx._source.visits = value.visits; }] using lang [groovy]]; nested: NoClassDefFoundError[sun/reflect/MethodAccessorImpl]; nested: ClassNotFoundException[sun.reflect.MethodAccessorImpl];
	at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript.run(GroovyScriptEngineService.java:318)
	at org.elasticsearch.action.update.UpdateHelper.executeScript(UpdateHelper.java:251)
	... 12 more
Caused by: java.lang.NoClassDefFoundError: sun/reflect/MethodAccessorImpl
	at sun.misc.Unsafe.defineClass(Native Method)
	at sun.reflect.ClassDefiner.defineClass(Unknown Source)
	at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
	at sun.reflect.MethodAccessorGenerator$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.MethodAccessorGenerator.generate(Unknown Source)
	at sun.reflect.MethodAccessorGenerator.generateMethod(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
	at groovy.lang.Closure.call(Closure.java:426)
	at groovy.lang.Closure.call(Closure.java:442)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:5228)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2107)
	at org.codehaus.groovy.runtime.dgm$163.doMethodInvoke(Unknown Source)
	at 2fe87ca3b157e7fc7a85946504c7142bec5e87df.run(2fe87ca3b157e7fc7a85946504c7142bec5e87df:1)
	at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript$1.run(GroovyScriptEngineService.java:311)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript.run(GroovyScriptEngineService.java:308)
	... 13 more
Caused by: java.lang.ClassNotFoundException: sun.reflect.MethodAccessorImpl
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:677)
	at groovy.lang.GroovyClassLoader$InnerLoader.loadClass(GroovyClassLoader.java:425)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:787)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:775)
	... 36 more
`

**Comment by ywelsch** [comment]
It's fixed in ES 2.2.1 (see #16540)

**Comment by sergfed** [comment]
Thank you!
Seems i should check new versions every day )
