### ISSUE TITLE
Evaluate windows permissions in InstallPluginCommand

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#17201]
#17176 tightened up directory permissions during plugin installations. Sadly the added permissions are no good on windows as their are POSIX based.   We should evaluate what permissions are required for windows.

See for example http://build-us-00.elastic.co/job/es_core_master_windows-2012-r2/2703/consoleText, failing with: 

```
Exception in thread "main" java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
	at sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
	at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:492)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
	at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:173)
	at java.nio.file.Files.createTempDirectory(Files.java:950)
	at org.elasticsearch.plugins.InstallPluginCommand.unzip(InstallPluginCommand.java:252)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:174)
```

For now , permissions are disabled on windows with https://github.com/elastic/elasticsearch/commit/ee95c0a3843434b6fa43c8e448a192118368e6f4

**Comment by rmuir** [comment]
This code uses getFileAttributeView incorrectly: only BasicFileAttributeView is guaranteed. It needs to check for null in any other case.

**Comment by rmuir** [comment]
Same goes with the createTempDirectory+with+attributes call: UOE needs to be handled. Then Constants.WINDOWS should be removed.
