### ISSUE TITLE
Getting array_index_out_of_bounds_exception while using order_by

### ISSUE THREAD

**Issue by Vineeth-Mohan** [elastic/elasticsearch#17225]
**Observations**
 * ES version 2.2.1
 * If number of documents indexed is 2 , there is no error or issue
 * With following recreation , I am seeing array_index_out_of_bounds_exception exception 

```
curl -XDELETE 'http://localhost:9200/vm/'
echo
curl -XPOST 'http://localhost:9200/vm/vm' -d '{ "name" : "vm" , "rank" : 2 , "date" : 2000 }'
echo
curl -XPOST 'http://localhost:9200/vm/vm' -d '{ "name" : "vm1" , "rank" : 2 , "date" : 2000 }'
echo
curl -XPOST 'http://localhost:9200/vm/vm' -d '{ "name" : "vm2" , "rank" : 2 , "date" : 2000 }'
echo
curl -XPOST 'http://localhost:9200/vm/vm' -d '{ "name" : "vm3" , "rank" : 2 , "date" : 2000 }'
echo
curl -XPOST 'http://localhost:9200/vm/vm' -d '{ "name" : "vm4" , "rank" : 2 , "date" : 2000 }'
echo
curl -XPOST 'http://localhost:9200/vm/vm' -d '{ "name" : "vm5" , "rank" : 2 , "date" : 2000 }'
echo
curl -XPOST 'http://localhost:9200/vm/vm' -d '{ "name" : "vm6" , "rank" : 2 , "date" : 2000 }'
echo
curl -XPOST 'http://localhost:9200/vm/vm' -d '{ "name" : "vm7" , "rank" : 2 , "date" : 2000 }'
echo
curl -XPOST 'http://localhost:9200/vm/vm' -d '{ "name" : "vm8" , "rank" : 2 , "date" : 2000 }'
echo
curl -XPOST 'http://localhost:9200/vm/vm' -d '{ "name" : "vm9" , "rank" : 2 , "date" : 2000 }'
echo
curl -XPOST 'http://localhost:9200/vm/vm' -d '{ "name" : "vm10" , "rank" : 2 , "date" : 2000 }'
echo
curl -XPOST 'http://localhost:9200/vm/vm' -d '{ "name" : "vm11" , "rank" : 2 , "date" : 2000 }'
echo
curl -XPOST 'http://localhost:9200/vm/_refresh'
echo
curl -XPOST 'http://localhost:9200/vm/vm/_search?pretty' -d '{
  "size": 0,
  "aggs": {
    "keywords": {
      "terms": {
        "collect_mode": "breadth_first",
        "field": "name",
        "size": 1,
        "order": {
          "dateB>rankAvg": "asc"
        }
      },
      "aggs": {
        "dateB": {
          "filter": {
            "term": {
              "date": 2001
            }
          },
          "aggs": {
            "rankAvg": {
              "min": {
                "field": "rank",
                "missing": 1000
              }
            }
          }
        }
      }
    }
  }
}'
```

Response
```
{
  "took" : 13,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 3,
    "failed" : 2,
    "failures" : [ {
      "shard" : 2,
      "index" : "vm",
      "node" : "xpPiHlvJQjSgYu-L10WJuA",
      "reason" : {
        "type" : "array_index_out_of_bounds_exception",
        "reason" : "1"
      }
    } ]
  },
  "hits" : {
    "total" : 2,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "keywords" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 1,
      "buckets" : [ {
        "key" : "vm10",
        "doc_count" : 1,
        "dateB" : {
          "doc_count" : 0,
          "rankAvg" : {
            "value" : null
          }
        }
      } ]
    }
  }
}
```

Logs emitted

```
[2016-03-21 21:53:55,238][DEBUG][action.search.type       ] [Gertrude Yorkes] [vm][4], node[pkRBZKPTStiOaYYr4mH_-w], [P], v[2], s[STARTED], a[id=Tf6t7fTWRz-FSvU30ln-mA]: Failed to execute [org.elasticsearch.action.search.SearchRequest@a062c99] lastShard [true]
RemoteTransportException[[Gertrude Yorkes][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: ArrayIndexOutOfBoundsException[1];
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.elasticsearch.common.util.BigArrays$DoubleArrayWrapper.get(BigArrays.java:260)
	at org.elasticsearch.search.aggregations.metrics.min.MinAggregator.metric(MinAggregator.java:100)
	at org.elasticsearch.search.aggregations.bucket.terms.InternalOrder$Aggregation$3.compare(InternalOrder.java:213)
	at org.elasticsearch.search.aggregations.bucket.terms.InternalOrder$Aggregation$3.compare(InternalOrder.java:210)
	at org.elasticsearch.search.aggregations.bucket.terms.InternalOrder$CompoundOrder$CompoundOrderComparator.compare(InternalOrder.java:280)
	at org.elasticsearch.search.aggregations.bucket.terms.InternalOrder$CompoundOrder$CompoundOrderComparator.compare(InternalOrder.java:266)
	at org.elasticsearch.search.aggregations.bucket.terms.support.BucketPriorityQueue.lessThan(BucketPriorityQueue.java:37)
	at org.elasticsearch.search.aggregations.bucket.terms.support.BucketPriorityQueue.lessThan(BucketPriorityQueue.java:26)
	at org.apache.lucene.util.PriorityQueue.upHeap(PriorityQueue.java:258)
	at org.apache.lucene.util.PriorityQueue.add(PriorityQueue.java:135)
	at org.apache.lucene.util.PriorityQueue.insertWithOverflow(PriorityQueue.java:151)
	at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator.buildAggregation(GlobalOrdinalsStringTermsAggregator.java:176)
	at org.elasticsearch.search.aggregations.AggregationPhase.execute(AggregationPhase.java:167)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:119)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:364)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:376)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by clintongormley** [comment]
@colings86 could you take a look at this please

**Comment by Vineeth-Mohan** [comment]
Thanks guys.
