### ISSUE TITLE
PluginManager: Installing non-existing plugin returns confusing error message

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#17226]
If a plugin does not exist, then this is returned

```
bin/elasticsearch-plugin install nonexistentplugin
-> Downloading nonexistentplugin
Exception in thread "main" java.net.MalformedURLException: no protocol: nonexistentplugin
	at java.net.URL.<init>(URL.java:586)
	at java.net.URL.<init>(URL.java:483)
	at java.net.URL.<init>(URL.java:432)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:211)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:206)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:174)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:162)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
	at org.elasticsearch.cli.Command.main(Command.java:53)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:57)
```

Also I cant seem to find out the URL which is actually requested for debugging purposes anymore, might be intended though?

**Comment by rjernst** [comment]
`nonexistentplugin` *is* the url the plugin cli is trying to resolve. The logic is simple (1) is it a known official plugin? (2) is it maven coordinates? (3) finally, try it as a url.

**Comment by rjernst** [comment]
If we want this to be "nicer" we could print a message in this final case on the usage info about what is supported (official plugin name, maven coordinates, or url).

**Comment by javanna** [comment]
> If we want this to be "nicer" we could print a message in this final case on the usage info about what is supported (official plugin name, maven coordinates, or url).

++ that was the purpose of this issue I believe. The logic is clear to developers, but the current error is confusing to users.

**Comment by nik9000** [comment]
> The logic is clear to developers, but the current error is confusing to users.

I suspect this mostly comes up in the "I misspelled kuromoji" kind of use case.

**Comment by rjernst** [comment]
Perhaps we should improve the usage information, and throw a UserError with USAGE here then.

**Comment by nikoncode** [comment]
I think need to show message like follows:
<pre>
$elasticsearch-plugin install lipsum
Not found as core plugin.
Not found as maven artifact.
Not found as URL.

Usages:
install name
install groupId:artifactId:version
install file:///name.zip
</pre>

Why github isn't supported now (5.x)?

**Comment by clintongormley** [comment]
> Why github isn't supported now (5.x)?

Site plugins are no longer supported, only Java plugins.  Site plugins should be reimplemented as Kibana plugins.

**Comment by clintongormley** [comment]
It's easy enough to figure out whether the argument looks like a protocol or not, and it would be much friendlier to say "unknown plugin" in this case than "no protocol: foo".  Also, the current usage method doesn't mention that you can pass a URL or maven coordinates to install.

**Comment by rjernst** [comment]
I opened #18876 to give a nicer error message. It does not yet force listing out all the acceptable patterns for installing, but that is a broader issue I think we need to address with real usage lines.
