### ISSUE TITLE
QuorumGatewayIT fails on master

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#17236]
The failure reproduces (e.g. with seed BD57BE5B57A9875A:5339034DFF2C888F). Stumbled upon it while running tests to get #16963 back up-to-date. Seems like we are missing the document that we index after the full cluster restart, when a single node is up. Seems quite bad at first glance.

```
java.lang.AssertionError: Count is 2 but 3 was expected.  Total shards: 5 Successful shards: 5 & 0 shard failures:

	at __randomizedtesting.SeedInfo.seed([BD57BE5B57A9875A:5339034DFF2C888F]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertHitCount(ElasticsearchAssertions.java:248)
	at org.elasticsearch.gateway.QuorumGatewayIT.testQuorumRecovery(QuorumGatewayIT.java:103)
```

**Comment by javanna** [comment]
Assigning @bleskes as this failure was related to #17233 not sure whether reverting the original change solves completely the issue yet and whether we should close it or not.

**Comment by bleskes** [comment]
It does indeed. The change was reverted, so I'm closing this.
