### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by beiske** [elastic/elasticsearch#17292]
When testing master I get a not so descriptive error message. I'm guessing there are some bad settings, but it would be nice to get an error message decribing which key has a value that cannot be null.

```
Exception in thread "main" java.lang.NullPointerException: Argument 'value' must not be null.
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.elasticsearch.common.property.PropertyPlaceholder.replacePlaceholders(PropertyPlaceholder.java:80)
	at org.elasticsearch.common.settings.Settings$Builder.replacePropertyPlaceholders(Settings.java:1224)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.initializeSettings(InternalSettingsPreparer.java:133)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:107)
	at org.elasticsearch.bootstrap.Bootstrap.initialSettings(Bootstrap.java:199)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:237)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:108)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:103)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
	at org.elasticsearch.cli.Command.main(Command.java:53)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)
```

**Comment by beiske** [comment]
The root cause was this setting:

```
cloud:
    aws:
        region:  #  eu-west-1,  us-east-1 etc
```
