### ISSUE TITLE
Vagrant upgrade test failing after relocating indexes to new folder structure

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#17294]
We have a simple upgrade test that is failing frequently right now in master. The test is rather simple. Startup Elasticsearch 2.0.0, index some documents, stop Elasticsearch, upgrade to master, start Elasticsearch back up, and then check that those indexed documents are there. In these failures, Elasticsearch successfully starts back up, relocates the indices to the new folder structure, goes yellow, yet gives mysterious shard not found exceptions after get requests are issued against those documents. Here are the logs from a failed run:

```
[2016-03-22 16:23:40,311][INFO ][node                     ] [Manbot] version[2.0.0], pid[32374], build[de54438/2015-10-22T08:09:48Z]
[2016-03-22 16:23:40,311][INFO ][node                     ] [Manbot] initializing ...
[2016-03-22 16:23:40,366][INFO ][plugins                  ] [Manbot] loaded [], sites []
[2016-03-22 16:23:40,441][INFO ][env                      ] [Manbot] using [1] data paths, mounts [[/ (/dev/mapper/fedora-root)]], net usable_space [15.7gb], net total_space [17.4gb], spins? [possibly], types [xfs]
[2016-03-22 16:23:42,137][INFO ][node                     ] [Manbot] initialized
[2016-03-22 16:23:42,137][INFO ][node                     ] [Manbot] starting ...
[2016-03-22 16:23:42,178][INFO ][transport                ] [Manbot] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}, {[::1]:9300}
[2016-03-22 16:23:42,194][INFO ][discovery                ] [Manbot] elasticsearch/_QbU4s4ISjWDgtZHjdbqJg
[2016-03-22 16:23:45,321][INFO ][cluster.service          ] [Manbot] new_master {Manbot}{_QbU4s4ISjWDgtZHjdbqJg}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2016-03-22 16:23:45,387][INFO ][http                     ] [Manbot] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {[::1]:9200}
[2016-03-22 16:23:45,387][INFO ][node                     ] [Manbot] started
[2016-03-22 16:23:45,393][INFO ][gateway                  ] [Manbot] recovered [0] indices into cluster_state
[2016-03-22 16:23:46,369][INFO ][cluster.metadata         ] [Manbot] [library] creating index, cause [auto(index api)], templates [], shards [5]/[1], mappings [book]
[2016-03-22 16:23:46,693][INFO ][cluster.metadata         ] [Manbot] [library] update_mapping [book]
[2016-03-22 16:23:46,791][INFO ][cluster.metadata         ] [Manbot] [library2] creating index, cause [auto(index api)], templates [], shards [5]/[1], mappings [book]
[2016-03-22 16:23:46,926][INFO ][cluster.metadata         ] [Manbot] [library2] update_mapping [book]
[2016-03-22 16:23:47,107][INFO ][node                     ] [Manbot] stopping ...
[2016-03-22 16:23:47,276][INFO ][node                     ] [Manbot] stopped
[2016-03-22 16:23:47,276][INFO ][node                     ] [Manbot] closing ...
[2016-03-22 16:23:47,279][INFO ][node                     ] [Manbot] closed
[2016-03-22 16:23:48,660][WARN ][bootstrap                ] max file descriptors [65535] for elasticsearch process likely too low, increase to at least [65536]
[2016-03-22 16:23:48,677][INFO ][node                     ] [Mary "Skeeter" MacPherran] version[5.0.0-SNAPSHOT], pid[900], build[8004c51/2016-03-22T15:58:45.132Z]
[2016-03-22 16:23:48,677][INFO ][node                     ] [Mary "Skeeter" MacPherran] initializing ...
[2016-03-22 16:23:49,149][INFO ][plugins                  ] [Mary "Skeeter" MacPherran] modules [lang-mustache, lang-painless, ingest-grok, reindex, lang-expression, lang-groovy], plugins []
[2016-03-22 16:23:49,173][INFO ][env                      ] [Mary "Skeeter" MacPherran] using [1] data paths, mounts [[/ (/dev/mapper/fedora-root)]], net usable_space [15.7gb], net total_space [17.4gb], spins? [possibly], types [xfs]
[2016-03-22 16:23:49,173][INFO ][env                      ] [Mary "Skeeter" MacPherran] heap size [1015.6mb], compressed ordinary object pointers [true]
[2016-03-22 16:23:51,515][INFO ][common.util              ] [library/y0Jj3USfQpOkx0zpC88ObQ] upgrading [/var/lib/elasticsearch/elasticsearch/nodes/0/indices/library] to new naming convention
[2016-03-22 16:23:51,516][INFO ][common.util              ] [library/y0Jj3USfQpOkx0zpC88ObQ] moved from [/var/lib/elasticsearch/elasticsearch/nodes/0/indices/library] to [/var/lib/elasticsearch/elasticsearch/nodes/0/indices/y0Jj3USfQpOkx0zpC88ObQ]
[2016-03-22 16:23:51,519][INFO ][common.util              ] [library2/6Vuo4MIiQvGenbpxkLfi2Q] upgrading [/var/lib/elasticsearch/elasticsearch/nodes/0/indices/library2] to new naming convention
[2016-03-22 16:23:51,519][INFO ][common.util              ] [library2/6Vuo4MIiQvGenbpxkLfi2Q] moved from [/var/lib/elasticsearch/elasticsearch/nodes/0/indices/library2] to [/var/lib/elasticsearch/elasticsearch/nodes/0/indices/6Vuo4MIiQvGenbpxkLfi2Q]
[2016-03-22 16:23:51,605][INFO ][node                     ] [Mary "Skeeter" MacPherran] initialized
[2016-03-22 16:23:51,609][INFO ][node                     ] [Mary "Skeeter" MacPherran] starting ...
[2016-03-22 16:23:51,683][INFO ][transport                ] [Mary "Skeeter" MacPherran] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2016-03-22 16:23:54,818][INFO ][cluster.service          ] [Mary "Skeeter" MacPherran] new_master {Mary "Skeeter" MacPherran}{D0lJ0rzOTmGhTEmHl1p8sQ}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2016-03-22 16:23:54,900][INFO ][http                     ] [Mary "Skeeter" MacPherran] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
[2016-03-22 16:23:54,901][INFO ][node                     ] [Mary "Skeeter" MacPherran] started
[2016-03-22 16:23:55,060][INFO ][gateway                  ] [Mary "Skeeter" MacPherran] recovered [2] indices into cluster_state
[2016-03-22 16:23:55,372][WARN ][rest.suppressed          ] /library/book/1 Params: {pretty=, index=library, id=1, type=book}
NoShardAvailableActionException[No shard available for [get [library][book][1]: routing [null]]]
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.perform(TransportSingleShardAction.java:205)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.start(TransportSingleShardAction.java:184)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction.doExecute(TransportSingleShardAction.java:93)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction.doExecute(TransportSingleShardAction.java:57)
	at org.elasticsearch.action.support.TransportAction.doExecute(TransportAction.java:150)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:174)
	at org.elasticsearch.action.ingest.IngestActionFilter.apply(IngestActionFilter.java:80)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:172)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:145)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:87)
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:64)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:402)
	at org.elasticsearch.client.support.AbstractClient.get(AbstractClient.java:494)
	at org.elasticsearch.rest.action.get.RestGetAction.handleRequest(RestGetAction.java:79)
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:51)
	at org.elasticsearch.rest.RestController.executeHandler(RestController.java:214)
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:174)
	at org.elasticsearch.http.HttpServer.dispatchRequest(HttpServer.java:101)
	at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:487)
	at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:65)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:85)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:83)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-03-22 16:23:55,561][INFO ][node                     ] [Mary "Skeeter" MacPherran] stopping ...
[2016-03-22 16:23:55,595][WARN ][cluster.action.shard     ] [Mary "Skeeter" MacPherran] [library][2] unexpected failure while sending request [internal:cluster/shard/started] to [{Mary "Skeeter" MacPherran}{D0lJ0rzOTmGhTEmHl1p8sQ}{127.0.0.1}{127.0.0.1:9300}] for shard [target shard [[[library/y0Jj3USfQpOkx0zpC88ObQ]][2], node[D0lJ0rzOTmGhTEmHl1p8sQ], [P], s[INITIALIZING], a[id=Mjw1dR_XTDO2NZ4Oqm9nGA], unassigned_info[[reason=CLUSTER_RECOVERED], at[2016-03-22T16:23:54.974Z]]], source shard [[[library/y0Jj3USfQpOkx0zpC88ObQ]][2], node[D0lJ0rzOTmGhTEmHl1p8sQ], [P], s[INITIALIZING], a[id=Mjw1dR_XTDO2NZ4Oqm9nGA], unassigned_info[[reason=CLUSTER_RECOVERED], at[2016-03-22T16:23:54.974Z]]], message [after recovery from store]]
SendRequestTransportException[[Mary "Skeeter" MacPherran][127.0.0.1:9300][internal:cluster/shard/started]]; nested: TransportException[TransportService is closed stopped can't send request];
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:331)
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:290)
	at org.elasticsearch.cluster.action.shard.ShardStateAction.sendShardAction(ShardStateAction.java:101)
	at org.elasticsearch.cluster.action.shard.ShardStateAction.shardStarted(ShardStateAction.java:333)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.lambda$applyInitializingShard$2(IndicesClusterStateService.java:627)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: TransportException[TransportService is closed stopped can't send request]
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:311)
	... 8 more
[2016-03-22 16:23:55,620][INFO ][node                     ] [Mary "Skeeter" MacPherran] stopped
[2016-03-22 16:23:55,620][INFO ][node                     ] [Mary "Skeeter" MacPherran] closing ...
[2016-03-22 16:23:55,631][INFO ][node                     ] [Mary "Skeeter" MacPherran] closed
```

**Comment by jasontedor** [comment]
These logs still seemingly indicate an odd issue here, but it's not reliably reproducible so I'm closing this until it surfaces again.
