### ISSUE TITLE
ElasticSearch and kibana timeout problem

### ISSUE THREAD

**Issue by Mobasher-NetLinks** [elastic/elasticsearch#17356]
I'm using ElasticSearch, everything was normal and working, but message `high desk watermark [90%].....some shards will be relocated away from this node` was showed.
But after some days kibana and elasticsearch can't connect, and connection timeout occur.

    Ahmads-MacBook-Pro:elasticsearch-1.7.0 mobasherfasihy$ bin/elasticsearch
    [2016-03-26 14:57:57,230][INFO ][node                     ] [Sage] version[1.7.0], pid[86359], build[929b973/2015-07-16T14:31:07Z]
    [2016-03-26 14:57:57,231][INFO ][node                     ] [Sage] initializing ...
    [2016-03-26 14:57:57,391][INFO ][com.floragunn.searchguard.SearchGuardPlugin] Class enhancements for DLS/FLS successful
    [2016-03-26 14:57:57,407][INFO ][plugins                  ] [Sage] loaded [searchguard, license, marvel], sites [marvel]
    [2016-03-26 14:57:57,437][INFO ][env                      ] [Sage] using [1] data paths, mounts [[/ (/dev/disk1)]], net usable_space [17.9gb], net total_space [369.5gb], types [hfs]
    [2016-03-26 14:57:59,083][WARN ][com.floragunn.searchguard.util.SecurityUtil] AES 256 not supported, max key length for AES is 128. To enable AES 256 install 'Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files'
    [2016-03-26 14:57:59,261][INFO ][node                     ] [Sage] initialized
    [2016-03-26 14:57:59,261][INFO ][node                     ] [Sage] starting ...
    [2016-03-26 14:57:59,333][INFO ][transport                ] [Sage] bound_address {inet[/127.0.0.1:9304]}, publish_address {inet[localhost/127.0.0.1:9304]}
    [2016-03-26 14:57:59,345][INFO ][discovery                ] [Sage] elasticsearch/XR6DsFmbQk267g3UFpbQCw
    [2016-03-26 14:58:03,125][INFO ][cluster.service          ] [Sage] new_master [Sage][XR6DsFmbQk267g3UFpbQCw][Ahmads-MacBook-Pro.local][inet[localhost/127.0.0.1:9304]], reason: zen-disco-join (elected_as_master)
    [2016-03-26 14:58:03,149][INFO ][http                     ] [Sage] bound_address {inet[/127.0.0.1:9204]}, publish_address {inet[localhost/127.0.0.1:9204]}
    [2016-03-26 14:58:03,149][INFO ][node                     ] [Sage] started
    [2016-03-26 14:58:03,157][INFO ][gateway                  ] [Sage] recovered [0] indices into cluster_state
    [2016-03-26 14:58:15,288][ERROR][marvel.agent.exporter    ] [Sage] error connecting to [127.0.0.1:9200] [connect timed out]
    [2016-03-26 14:58:15,288][ERROR][marvel.agent.exporter    ] [Sage] could not connect to any configured elasticsearch instances: [127.0.0.1:9200]
    [2016-03-26 14:58:21,293][ERROR][marvel.agent.exporter    ] [Sage] error connecting to [127.0.0.1:9200] [connect timed out]
    [2016-03-26 14:58:21,294][ERROR][marvel.agent.exporter    ] [Sage] could not connect to any configured elasticsearch instances: [127.0.0.1:9200]
    [2016-03-26 14:58:27,304][ERROR][marvel.agent.exporter    ] [Sage] error connecting to [127.0.0.1:9200] [connect timed out]
    [2016-03-26 14:58:27,304][ERROR][marvel.agent.exporter    ] [Sage] could not connect to any configured elasticsearch instances: [127.0.0.1:9200]
    [2016-03-26 14:58:33,136][WARN ][cluster.routing.allocation.decider] [Sage] high disk watermark [90%] exceeded on [XR6DsFmbQk267g3UFpbQCw][Sage] free: 17.9gb[4.8%], shards will be relocated away from this node
    [2016-03-26 14:58:33,136][INFO ][cluster.routing.allocation.decider] [Sage] high disk watermark exceeded on one or more nodes, rerouting shards
    [2016-03-26 14:58:33,315][ERROR][marvel.agent.exporter    ] [Sage] error connecting to [127.0.0.1:9200] [connect timed out]
    [2016-03-26 14:58:33,315][ERROR][marvel.agent.exporter    ] [Sage] could not connect to any configured elasticsearch instances: [127.0.0.1:9200]
    [2016-03-26 14:58:49,326][ERROR][marvel.agent.exporter    ] [Sage] error connecting to [127.0.0.1:9200] [connect timed out]
    [2016-03-26 14:58:49,326][ERROR][marvel.agent.exporter    ] [Sage] could not connect to any configured elasticsearch instances: [127.0.0.1:9200]
    [2016-03-26 14:58:55,328][ERROR][marvel.agent.exporter    ] [Sage] error connecting to [127.0.0.1:9200] [connect timed out]
    [2016-03-26 14:58:55,328][ERROR][marvel.agent.exporter    ] [Sage] could not connect to any configured elasticsearch instances: [127.0.0.1:9200]
    [2016-03-26 14:59:01,330][ERROR][marvel.agent.exporter    ] [Sage] error connecting to [127.0.0.1:9200] [connect timed out]
    [2016-03-26 14:59:01,330][ERROR][marvel.agent.exporter    ] [Sage] could not connect to any configured elasticsearch instances: [127.0.0.1:9200]
    [2016-03-26 14:59:03,133][WARN ][cluster.routing.allocation.decider] [Sage] high disk watermark [90%] exceeded on [XR6DsFmbQk267g3UFpbQCw][Sage] free: 17.9gb[4.8%], shards will be relocated away from this node
    [2016-03-26 14:59:07,338][ERROR][marvel.agent.exporter    ] [Sage] error connecting to [127.0.0.1:9200] [connect timed out]
    [2016-03-26 14:59:07,338][ERROR][marvel.agent.exporter    ] [Sage] could not connect to any configured elasticsearch instances: [127.0.0.1:9200]
    [2016-03-26 14:59:23,346][ERROR][marvel.agent.exporter    ] [Sage] error connecting to [127.0.0.1:9200] [connect timed out]
    [2016-03-26 14:59:23,346][ERROR][marvel.agent.exporter    ] [Sage] could not connect to any configured elasticsearch instances: [127.0.0.1:9200]
    [2016-03-26 14:59:29,351][ERROR][marvel.agent.exporter    ] [Sage] error connecting to [127.0.0.1:9200] [connect timed out]
    [2016-03-26 14:59:29,351][ERROR][marvel.agent.exporter    ] [Sage] could not connect to any configured elasticsearch instances: [127.0.0.1:9200]
    [2016-03-26 14:59:33,136][WARN ][cluster.routing.allocation.decider] [Sage] high disk watermark [90%] exceeded on [XR6DsFmbQk267g3UFpbQCw][Sage] free: 17.9gb[4.8%], shards will be relocated away from this node
    [2016-03-26 14:59:33,136][INFO ][cluster.routing.allocation.decider] [Sage] high disk watermark exceeded on one or more nodes, rerouting shards
    [2016-03-26 14:59:35,355][ERROR][marvel.agent.exporter    ] [Sage] error connecting to [127.0.0.1:9200] [connect timed out]
    [2016-03-26 14:59:35,355][ERROR][marvel.agent.exporter    ] [Sage] could not connect to any configured elasticsearch instances: [127.0.0.1:9200]

and in kibana 

    {"name":"Kibana","hostname":"Ahmads-MacBook-Pro.local","pid":85748,"level":50,"err":{"message":"Request Timeout after 5000ms","name":"Error","stack":"Error: Request Timeout after 5000ms\n    at null.<anonymous> (/Users/ahmadhusseinrezae/kibana-4.1.3-darwin-x64/src/node_modules/elasticsearch/src/lib/transport.js:282:15)\n    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)"},"msg":"","time":"2016-03-26T08:55:35.517Z","v":0}

**Comment by clintongormley** [comment]
Hi @Mobasher-NetLinks 

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
