### ISSUE TITLE
failed to send ping to

### ISSUE THREAD

**Issue by Mobasher-NetLinks** [elastic/elasticsearch#17361]
**Elasticsearch version 2.2.1**:

**1.8**:

**OS X 10.10 (14A389a)**:

`Ahmads-MacBook-Pro:elasticsearch-2.2.1` mobasherfasihy$ bin/elasticsearch
[2016-03-28 13:51:26,794][INFO ][node                     ] [Sasquatch] version[2.2.1], pid[94989], build[d045fc2/2016-03-09T09:38:54Z]
[2016-03-28 13:51:26,795][INFO ][node                     ] [Sasquatch] initializing ...
[2016-03-28 13:51:27,255][INFO ][plugins                  ] [Sasquatch] modules [lang-expression, lang-groovy], plugins [], sites []
[2016-03-28 13:51:27,271][INFO ][env                      ] [Sasquatch] using [1] data paths, mounts [[/ (/dev/disk1)]], net usable_space [35.2gb], net total_space [369.5gb], spins? [unknown], types [hfs]
[2016-03-28 13:51:27,271][INFO ][env                      ] [Sasquatch] heap size [989.8mb], compressed ordinary object pointers [true]
[2016-03-28 13:51:28,489][INFO ][node                     ] [Sasquatch] initialized
[2016-03-28 13:51:28,489][INFO ][node                     ] [Sasquatch] starting ...
[2016-03-28 13:51:28,561][INFO ][transport                ] [Sasquatch] publish_address {127.0.0.1:9312}, bound_addresses {[fe80::1]:9308}, {[::1]:9308}, {127.0.0.1:9312}
[2016-03-28 13:51:28,567][INFO ][discovery                ] [Sasquatch] elasticsearch/_MPsbDKrQw2c6TSz_YcuCA
[2016-03-28 13:51:32,390][WARN ][discovery.zen.ping.unicast] [Sasquatch] failed to send ping to [{#zen_unicast_4#}{127.0.0.1}{127.0.0.1:9303}]
ReceiveTimeoutTransportException[[][127.0.0.1:9303][internal:discovery/zen/unicast] request_id [2] timed out after [3753ms]]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-03-28 13:51:32,390][WARN ][discovery.zen.ping.unicast] [Sasquatch] failed to send ping to [{#zen_unicast_6#}{::1}{[::1]:9300}]
ReceiveTimeoutTransportException[[][[::1]:9300][internal:discovery/zen/unicast] request_id [7] timed out after [3764ms]]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-03-28 13:51:32,390][WARN ][discovery.zen.ping.unicast] [Sasquatch] failed to send ping to [{#zen_unicast_5#}{127.0.0.1}{127.0.0.1:9304}]
ReceiveTimeoutTransportException[[][127.0.0.1:9304][internal:discovery/zen/unicast] request_id [10] timed out after [3763ms]]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-03-28 13:51:32,390][WARN ][discovery.zen.ping.unicast] [Sasquatch] failed to send ping to [{#zen_unicast_2#}{127.0.0.1}{127.0.0.1:9301}]
ReceiveTimeoutTransportException[[][127.0.0.1:9301][internal:discovery/zen/unicast] request_id [3] timed out after [3753ms]]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-03-28 13:51:32,390][WARN ][discovery.zen.ping.unicast] [Sasquatch] failed to send ping to [{#zen_unicast_9#}{::1}{[::1]:9303}]
ReceiveTimeoutTransportException[[][[::1]:9303][internal:discovery/zen/unicast] request_id [5] timed out after [3764ms]]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-03-28 13:51:32,390][WARN ][discovery.zen.ping.unicast] [Sasquatch] failed to send ping to [{#zen_unicast_10#}{::1}{[::1]:9304}]
ReceiveTimeoutTransportException[[][[::1]:9304][internal:discovery/zen/unicast] request_id [1] timed out after [3753ms]]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-03-28 13:51:32,390][WARN ][discovery.zen.ping.unicast] [Sasquatch] failed to send ping to [{#zen_unicast_8#}{::1}{[::1]:9302}]
ReceiveTimeoutTransportException[[][[::1]:9302][internal:discovery/zen/unicast] request_id [4] timed out after [3753ms]]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-03-28 13:51:32,390][WARN ][discovery.zen.ping.unicast] [Sasquatch] failed to send ping to [{#zen_unicast_1#}{127.0.0.1}{127.0.0.1:9300}]
ReceiveTimeoutTransportException[[][127.0.0.1:9300][internal:discovery/zen/unicast] request_id [8] timed out after [3764ms]]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-03-28 13:51:32,390][WARN ][discovery.zen.ping.unicast] [Sasquatch] failed to send ping to [{#zen_unicast_3#}{127.0.0.1}{127.0.0.1:9302}]
ReceiveTimeoutTransportException[[][127.0.0.1:9302][internal:discovery/zen/unicast] request_id [9] timed out after [3764ms]]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-03-28 13:51:32,390][WARN ][discovery.zen.ping.unicast] [Sasquatch] failed to send ping to [{#zen_unicast_7#}{::1}{[::1]:9301}]
ReceiveTimeoutTransportException[[][[::1]:9301][internal:discovery/zen/unicast] request_id [6] timed out after [3764ms]]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-03-28 13:51:33,096][INFO ][cluster.service          ] [Sasquatch] new_master {Sasquatch}{_MPsbDKrQw2c6TSz_YcuCA}{127.0.0.1}{127.0.0.1:9312}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2016-03-28 13:51:33,129][INFO ][http                     ] [Sasquatch] publish_address {127.0.0.1:9211}, bound_addresses {[fe80::1]:9208}, {[::1]:9208}, {127.0.0.1:9211}
[2016-03-28 13:51:33,129][INFO ][node                     ] [Sasquatch] started
`

**Comment by jasontedor** [comment]
This is normal. Elasticsearch is trying to discover other nodes on localhost as part of its discovery process. Since there are apparently no such nodes, the pings timeout.
