### ISSUE TITLE
Elasticsearch proxy error when setting script.disable_dynamic

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch#17459]
**Elasticsearch version**: 2.3.0
**JVM version**: 1.8 latest
**OS version**: Windows 10 64bit

I'm upgrading my app from 1.7.5 and my elasticsearch.yml file had `script.disable_dynamic: false` set. When trying to launch with this setting I get the following error:

```sh
C:\elasticsearch.2.3\bin>elasticsearch
[2016-03-31 15:12:42,319][INFO ][node                     ] [ex-dev01] version[2.3.0], pid[6016], build[8371be8/2016-03-29T07:54:48Z]
[2016-03-31 15:12:42,324][INFO ][node                     ] [ex-dev01] initializing ...
[2016-03-31 15:12:42,801][INFO ][plugins                  ] [ex-dev01] modules [reindex, lang-expression, lang-groovy], plugins [license, marvel-agent, cloud-azure], sites []
[2016-03-31 15:12:42,824][INFO ][env                      ] [ex-dev01] using [1] data paths, mounts [[(C:)]], net usable_space [175.6gb], net total_space [255.6gb], spins? [unknown], types [NTFS]
[2016-03-31 15:12:42,830][INFO ][env                      ] [ex-dev01] heap size [910.5mb], compressed ordinary object pointers [true]
Exception in thread "main" java.lang.IllegalStateException: This is a proxy used to support circular references involving constructors. The object we're proxying is not constructed yet. Please wait until after injection has completed to use this object.
        at <<<guice>>>
        at com.sun.proxy.$Proxy13.settings(Unknown Source)
        at org.elasticsearch.client.FilterClient.<init>(FilterClient.java:41)
        at org.elasticsearch.marvel.shield.SecuredClient.<init>(SecuredClient.java:38)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at <<<guice>>>
        at org.elasticsearch.node.Node.<init>(Node.java:213)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

```

This should be a better error message!

**Comment by niemyjski** [comment]
I'm trying to find what this setting has been changed to. Ideas?

**Comment by s1monw** [comment]
maybe this helps https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html#enable-dynamic-scripting

**Comment by s1monw** [comment]
btw. upcoming 5.0 version has settigns validation it will tell you which setting is not valid etc.

**Comment by clintongormley** [comment]
Yeah, this setting was changed quite a while ago, and as Simon says, the experience in 5.0 will be a whole lot better.  Nothing further to do here, so closing

**Comment by h3** [comment]
For the googlers, I also get this error when setting an invalid value for `discovery.zen.ping.unicast.hosts`.

Make sure it matches the value of `network.host` (but in a list).
