### ISSUE TITLE
Improve error reporting for permissions errors on script directory

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#17467]
Did an upgrade to 2.3 and restarted the process and saw;
```
# service elasticsearch start
 * Starting Elasticsearch Server
# tailf /var/log/elasticsearch/elasticsearch.log
#
# LICENSE EXPIRED ON [Friday, February 05, 2016]. IF YOU HAVE A NEW LICENSE, PLEASE
# UPDATE IT. OTHERWISE, PLEASE REACH OUT TO YOUR SUPPORT CONTACT.
#
[2016-04-01 04:45:57,713][INFO ][gateway                  ] [Nightwatch] recovered [38] indices into cluster_state
[2016-04-01 04:46:03,004][INFO ][cluster.routing.allocation] [Nightwatch] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.kibana][0]] ...]).
[2016-04-01 04:46:39,207][INFO ][node                     ] [Nightwatch] stopping ...
[2016-04-01 04:46:39,485][INFO ][node                     ] [Nightwatch] stopped
[2016-04-01 04:46:39,485][INFO ][node                     ] [Nightwatch] closing ...
[2016-04-01 04:46:39,519][INFO ][node                     ] [Nightwatch] closed
```
But after a while there was no new logs showing the service starting, which was confirmed with;
```
# ps -ef|grep java
root     16365  1680  0 04:47 pts/0    00:00:00 grep --color=auto java
```
So I ran it manually;
```
# /usr/bin/java -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Djna.nosys=true -Des.path.home=/usr/share/elasticsearch -cp /usr/share/elasticsearch/lib/elasticsearch-2.3.0.jar:/usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch start -d -p /var/run/elasticsearch/elasticsearch.pid --default.path.home=/usr/share/elasticsearch --default.path.logs=/var/log/elasticsearch --default.path.data=/var/lib/elasticsearch --default.path.conf=/etc/elasticsearch
Exception in thread "main" ElasticsearchException[Failed to load logging configuration]; nested: AccessDeniedException[/etc/elasticsearch/scripts];
Likely root cause: java.nio.file.AccessDeniedException: /etc/elasticsearch/scripts
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300)
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
	at java.nio.file.Files.walkFileTree(Files.java:2706)
	at org.elasticsearch.common.logging.log4j.LogConfigurator.resolveConfig(LogConfigurator.java:142)
	at org.elasticsearch.common.logging.log4j.LogConfigurator.configure(LogConfigurator.java:103)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:243)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```

Here's what it looks like;
```
# ll -d /etc/elasticsearch/scripts
total 24
drwxr-x---  2 root elasticsearch 4096 Dec 15 13:30 scripts/
```

I tried a `chown -R elasticsearch:elasticsearch scripts/` but it didn't help. Neither did a `chmod 755 scripts/`. Note that I did nothing to that directory, I just ran an `apt-get dist-upgrade`.

To fix it I had to delete the directory, recreate it, re-add the permissions and all was good. No idea what happened there...

Anyway the root cause of this being a permissions error would be easier to diagnose if there were something in the logs to that affect :)

**Comment by rjernst** [comment]
When you say you "ran it manually" you mean as your user, not the elasticsearch user? Other has no permissions, so it cannot read the directory.

**Comment by clintongormley** [comment]
You didn't mention which version of ubuntu you're using, but i'm guessing that you're on a more recent version, which uses systemd, in which case you'd find logs using journalctl (which is now documented).

**Comment by jasontedor** [comment]
The root cause indicated a [permissions issue](https://docs.oracle.com/javase/7/docs/api/java/nio/file/AccessDeniedException.html):

> `Likely root cause: java.nio.file.AccessDeniedException: /etc/elasticsearch/scripts`

**Comment by glmrenard** [comment]
Hello, I also encounteer this issue, but the folder does not even exist ...
Any help appreciated.

Thanks :)
