### ISSUE TITLE
Network interface names containing colons can't be bound to

### ISSUE THREAD

**Issue by karlra** [elastic/elasticsearch#17473]
**Elasticsearch version**: 
2.3.0

**JVM version**:
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

**OS version**:
Ubuntu 14.04:4

**Steps to reproduce**:
 1. Add a network interface that contains a colon
 2. Add this interface to elasticsearch.yml as the network host or publish host like so: network.host: `_bond0:0_`
 3. Restart elasticsearch

**Provide logs (if relevant)**:

    [2016-04-01 11:59:04,363][INFO ][node                     ] [master_1] initialized
    [2016-04-01 11:59:04,363][INFO ][node                     ] [master_1] starting ...
    [2016-04-01 11:59:04,466][ERROR][bootstrap                ] [master_1] Exception
    java.lang.IllegalArgumentException: No interface named 'bond0:0' found, got [name:lo (lo), name:bond0 (bond0), name:bond0:0 (bond0:0)]
            at org.elasticsearch.common.network.NetworkUtils.getAddressesForInterface(NetworkUtils.java:232)
            at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:262)
            at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:209)
            at org.elasticsearch.common.network.NetworkService.resolveBindHostAddresses(NetworkService.java:122)
            at org.elasticsearch.transport.netty.NettyTransport.bindServerBootstrap(NettyTransport.java:424)
            at org.elasticsearch.transport.netty.NettyTransport.doStart(NettyTransport.java:321)
            at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
            at org.elasticsearch.transport.TransportService.doStart(TransportService.java:170)
            at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
            at org.elasticsearch.node.Node.start(Node.java:252)
            at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:221)
            at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:287)
            at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
    [2016-04-01 11:59:04,486][INFO ][node                     ] [master_1] stopping ...
    [2016-04-01 11:59:04,488][INFO ][node                     ] [master_1] stopped

**Comment by daschl** [comment]
I was curious so I dug in a bit. The problem is not the colon naming but rather that this is a virtual interface. `NetworkUtils.getAddressesForInterface` uses `NetworkInterface.getByName` of the JDK which returns null for virtual interfaces, even if the "name" is right. 

For your case `NetworkInterface.getByName("bond0").getSubInterfaces().nextElement();` would get you the right element. 

Now the thing is, its quite unpractical to split it up by colon itself and then match the subinterfaces name, but I think a compromise would be to just iterate over the result from `NetworkService .getInterfaces` and get the one where the name matches - because this includes all the physical and virtual interfaces (what the JDK refers to as sub interfaces`.

@jasontedor wdyt?

**Comment by daschl** [comment]
I'll rework the test case and resubmit.
