### ISSUE TITLE
BulkProcessor exception in 2.3.0 - IllegalIndexShardStateException

### ISSUE THREAD

**Issue by reflection** [elastic/elasticsearch#17482]
**Elasticsearch version**: 2.3.0 (official es docker image)

**JVM version**: OpenJDK Runtime Environment (build 1.8.0_72-internal-b15)

**OS version**: Debian 8

**Description of the problem including expected versus actual behavior**: Starting from es 2.2 and still in 2.3, we get the following exception only while using the Java BulkProcessor:
```
[356019-20160321][[356019-20160321][0]] IllegalIndexShardStateException[CurrentState[POST_RECOVERY] operation only allowed when started/recovering, origin [PRIMARY]]
	at org.elasticsearch.index.shard.IndexShard.ensureWriteAllowed(IndexShard.java:1068)
	at org.elasticsearch.index.shard.IndexShard.create(IndexShard.java:538)
	at org.elasticsearch.index.engine.Engine$Create.execute(Engine.java:810)
	at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:237)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:326)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:119)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:68)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:639)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:271)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Did we lose the records that would have been indexed, or does BulkProcessor wait for the index to get in a state where it can write and retry?  If the latter, are these exceptions "harmless" as stated in #15478 (there were multiple exceptions there so not sure if this was considered the harmless one).

**Steps to reproduce**:
 1. Consume from Kafka topic with three consumer threads that share one ES BulkProcessor object with all default values.

**Comment by jasontedor** [comment]
> official es docker image

Just so that there is no confusion: there is not an official Docker image provided by Elastic at this time. Any images that you currently obtain off of Docker Hub that are marked as "official" are not vetted by Elastic. (And I'm not saying that you're confused here, this is for clarity for anyone else reading this thread.)

> Did we lose the records that would have been indexed, or does BulkProcessor wait for the index to get in a state where it can write and retry?

How did you configure the `BulkProcessor`? How are you committing message consumption back to Kafka?

> If the latter, are these exceptions "harmless" as stated in #15478 (there were multiple exceptions there so not sure if this was considered the harmless one).

The situation in #15478 is quite different than your situation. The logging in #15478 was debug logging from stats requests where shards were being ignored because they were in a state not ready to receive such requests. A stats request missing a recovering shard is not a big deal. Your situation is concerning indexing into a primary shard and how you handle this exception is critically important to whether or not there is a data loss. Thus, the questions above about how you configured the `BulkProcessor` and how you're handling topic consumption.

I note that you truncated part of the exception message (in particular, the log level and the log prefix). Is there any chance that you can provide the remainder of the log message, including any additional pieces of the exception if there are any (there might not be other than the missing level and prefix)?

**Comment by reflection** [comment]
Automatic offset committing in Kafka with the new consumer wasn't working the way I thought it would.  I switched back to the old high-level consumer, and these errors went away.

That being said, if we do see these kind of errors, [BulkProcessor](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-docs-bulk-processor.html) looks like it would retry with whatever you set in its BackoffPolicy.
