### ISSUE TITLE
Filter aggregation with no filter results in a NullPointerException

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch#17518]
**Elasticsearch version**: master

**JVM version**: 1.8.0_74

**OS version**: Win 10

**Description of the problem including expected versus actual behavior**:

Not really a typical use case, but an issue nonetheless caught by our integration tests.  Specifying no filter in a filter agg results in a NPE.

**Steps to reproduce**:
 ```
{
  "aggs": {
    "empty_filter": {
      "filter": {}
    }
  }
}
```

Response:

```
{
  "error" : {
    "root_cause" : [ {
      "type" : "null_pointer_exception",
      "reason" : null
    } ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [ {
      "shard" : 0,
      "index" : "project",
      "node" : "9QsiljMeTtKbZ2FijGofvw",
      "reason" : {
        "type" : "null_pointer_exception",
        "reason" : null
      }
    } ],
    "caused_by" : {
      "type" : "null_pointer_exception",
      "reason" : null
    }
  },
  "status" : 500
}
```

**Provide logs (if relevant)**:

```
Failed to execute [org.elasticsearch.action.search.SearchRequest@3218e268]
RemoteTransportException[[readonly-node-55e651][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: NullPointerException;
Caused by: java.lang.NullPointerException
	at org.apache.lucene.search.IndexSearcher.rewrite(IndexSearcher.java:684)
	at org.apache.lucene.search.IndexSearcher.createNormalizedWeight(IndexSearcher.java:734)
	at org.elasticsearch.search.internal.ContextIndexSearcher.createNormalizedWeight(ContextIndexSearcher.java:107)
	at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregatorFactory.<init>(FilterAggregatorFactory.java:46)
	at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregatorBuilder.doBuild(FilterAggregatorBuilder.java:60)
	at org.elasticsearch.search.aggregations.AggregatorBuilder.build(AggregatorBuilder.java:120)
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:171)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:709)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:577)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:526)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:277)
	at org.elasticsearch.search.action.SearchTransportService$SearchQueryTransportHandler.messageReceived(SearchTransportService.java:369)
	at org.elasticsearch.search.action.SearchTransportService$SearchQueryTransportHandler.messageReceived(SearchTransportService.java:366)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:468)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by colings86** [comment]
@gmarz Thanks for flagging this up. I have opened #17542 to fix this.
