### ISSUE TITLE
[CI Failure] OldIndexBackwardsCompatibilityIT.testOldIndexes fails b/c payloads not found in _all search

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#17514]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/237/console

Reproduces locally for me with:

```
gradle :core:integTest -Dtests.seed=DAF558AA44C953B8 -Dtests.class=org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT -Dtests.method="testOldIndexes" -Des.logger.level=INFO -Dtests.security.manager=true -Dtests.locale=en-IE -Dtests.timezone=Europe/Lisbon
```

Seems to fail when testing against 2.3.1 and an `_all` search.  Afraid I don't know much about the backcompat tests to investigate more.  @jpountz @jimferenczi Is this perhaps related to https://github.com/elastic/elasticsearch/pull/16899 ?

```
1> [2016-04-04 13:32:19,670][INFO ][org.elasticsearch.bwcompat] --> Testing old index index-2.3.1.zip
  1> [2016-04-04 13:32:19,755][INFO ][org.elasticsearch.bwcompat] --> injecting index [index-2.3.1] into multi data path
  1> [2016-04-04 13:32:19,849][WARN ][org.elasticsearch.common.util] [/Users/tongz/Documents/elasticsearch_gradle/elasticsearch/core/build/testrun/integTest/J0/temp/org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT_DAF558AA44C953B8-002/tempDir-002/multi-path1/TEST-CHILD_VM=[0]-CLUSTER_SEED=[-7196169852749911737]-HASH=[F4A1A95576A]-cluster/nodes/0/indices/index-2.1.2] no index state found - ignoring
  1> [2016-04-04 13:32:19,851][WARN ][org.elasticsearch.common.util] [/Users/tongz/Documents/elasticsearch_gradle/elasticsearch/core/build/testrun/integTest/J0/temp/org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT_DAF558AA44C953B8-002/tempDir-002/multi-path2/TEST-CHILD_VM=[0]-CLUSTER_SEED=[-7196169852749911737]-HASH=[F4A1A95576A]-cluster/nodes/0/indices/index-2.1.2] no index state found - ignoring
  1> [2016-04-04 13:32:19,853][WARN ][org.elasticsearch.common.util] [/Users/tongz/Documents/elasticsearch_gradle/elasticsearch/core/build/testrun/integTest/J0/temp/org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT_DAF558AA44C953B8-002/tempDir-002/multi-path1/TEST-CHILD_VM=[0]-CLUSTER_SEED=[-7196169852749911737]-HASH=[F4A1A95576A]-cluster/nodes/0/indices/index-2.2.1] no index state found - ignoring
  1> [2016-04-04 13:32:19,853][WARN ][org.elasticsearch.common.util] [/Users/tongz/Documents/elasticsearch_gradle/elasticsearch/core/build/testrun/integTest/J0/temp/org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT_DAF558AA44C953B8-002/tempDir-002/multi-path2/TEST-CHILD_VM=[0]-CLUSTER_SEED=[-7196169852749911737]-HASH=[F4A1A95576A]-cluster/nodes/0/indices/index-2.2.1] no index state found - ignoring
  1> [2016-04-04 13:32:19,856][INFO ][org.elasticsearch.common.util] [index-2.3.1/_llJ2G6NQfmFpn-VuRXk5Q] upgrading [/Users/tongz/Documents/elasticsearch_gradle/elasticsearch/core/build/testrun/integTest/J0/temp/org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT_DAF558AA44C953B8-002/tempDir-002/multi-path1/TEST-CHILD_VM=[0]-CLUSTER_SEED=[-7196169852749911737]-HASH=[F4A1A95576A]-cluster/nodes/0/indices/index-2.3.1] to new naming convention
  1> [2016-04-04 13:32:19,857][INFO ][org.elasticsearch.common.util] [index-2.3.1/_llJ2G6NQfmFpn-VuRXk5Q] moved from [/Users/tongz/Documents/elasticsearch_gradle/elasticsearch/core/build/testrun/integTest/J0/temp/org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT_DAF558AA44C953B8-002/tempDir-002/multi-path1/TEST-CHILD_VM=[0]-CLUSTER_SEED=[-7196169852749911737]-HASH=[F4A1A95576A]-cluster/nodes/0/indices/index-2.3.1] to [/Users/tongz/Documents/elasticsearch_gradle/elasticsearch/core/build/testrun/integTest/J0/temp/org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT_DAF558AA44C953B8-002/tempDir-002/multi-path1/TEST-CHILD_VM=[0]-CLUSTER_SEED=[-7196169852749911737]-HASH=[F4A1A95576A]-cluster/nodes/0/indices/_llJ2G6NQfmFpn-VuRXk5Q]
  1> [2016-04-04 13:32:19,858][WARN ][org.elasticsearch.common.util] [/Users/tongz/Documents/elasticsearch_gradle/elasticsearch/core/build/testrun/integTest/J0/temp/org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT_DAF558AA44C953B8-002/tempDir-002/multi-path2/TEST-CHILD_VM=[0]-CLUSTER_SEED=[-7196169852749911737]-HASH=[F4A1A95576A]-cluster/nodes/0/indices/index-2.3.1] no index state found - ignoring
  1> [2016-04-04 13:32:19,867][INFO ][org.elasticsearch.gateway] [node_t2] [[index-2.3.1/_llJ2G6NQfmFpn-VuRXk5Q]] dangling index, exists on local file system, but not in cluster metadata, auto import to cluster state
  1> [2016-04-04 13:32:19,872][WARN ][org.elasticsearch.index  ] [node_t0] [index-2.3.1] [index.merge.enabled] is set to false, this should only be used in tests and can cause serious problems in production environments
  1> [2016-04-04 13:32:19,875][INFO ][org.elasticsearch.gateway] [node_t0] auto importing dangled indices [[index-2.3.1/_llJ2G6NQfmFpn-VuRXk5Q]/OPEN] from [{node_t2}{xo2bfVhdSFepOjnC3EER5Q}{local}{local[3]}]
  1> [2016-04-04 13:32:19,880][WARN ][org.elasticsearch.index  ] [node_t2] [index-2.3.1] [index.merge.enabled] is set to false, this should only be used in tests and can cause serious problems in production environments
  1> [2016-04-04 13:32:19,905][WARN ][org.elasticsearch.index  ] [node_t2] [index-2.3.1] [index.merge.enabled] is set to false, this should only be used in tests and can cause serious problems in production environments
  1> [2016-04-04 13:32:19,978][INFO ][org.elasticsearch.cluster.routing.allocation] [node_t0] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[index-2.3.1][0]] ...]).
  1> [2016-04-04 13:32:19,979][WARN ][org.elasticsearch.index  ] [node_t1] [index-2.3.1] [index.merge.enabled] is set to false, this should only be used in tests and can cause serious problems in production environments
  1> [2016-04-04 13:32:19,996][WARN ][org.elasticsearch.index  ] [node_t0] [index-2.3.1] [index.merge.enabled] is set to false, this should only be used in tests and can cause serious problems in production environments
  1> [2016-04-04 13:32:20,020][INFO ][org.elasticsearch.bwcompat] --> testing basic search
  1> [2016-04-04 13:32:20,022][INFO ][org.elasticsearch.bwcompat] Found 2499 in old index
  1> [2016-04-04 13:32:20,023][INFO ][org.elasticsearch.bwcompat] --> testing basic search with sort
  1> [2016-04-04 13:32:20,028][INFO ][org.elasticsearch.bwcompat] --> testing exists filter
  1> [2016-04-04 13:32:20,032][INFO ][org.elasticsearch.bwcompat] --> testing _all search
  1> [2016-04-04 13:32:20,041][INFO ][org.elasticsearch.bwcompat] [OldIndexBackwardsCompatibilityIT#testOldIndexes]: finished test
  1> [2016-04-04 13:32:20,049][INFO ][org.elasticsearch.bwcompat] [OldIndexBackwardsCompatibilityIT#testOldIndexes]: cleaning up after test
  1> [2016-04-04 13:32:20,079][WARN ][org.elasticsearch.index  ] [node_t1] [index-2.3.1] [index.merge.enabled] is set to false, this should only be used in tests and can cause serious problems in production environments
  1> [2016-04-04 13:32:20,080][WARN ][org.elasticsearch.index  ] [node_t1] [index-2.3.1] [index.merge.enabled] is set to false, this should only be used in tests and can cause serious problems in production environments
  1> [2016-04-04 13:32:20,120][WARN ][org.elasticsearch.index  ] [node_t0] [index-2.3.1] [index.merge.enabled] is set to false, this should only be used in tests and can cause serious problems in production environments
  1> [2016-04-04 13:32:20,121][WARN ][org.elasticsearch.index  ] [node_t0] [index-2.3.1] [index.merge.enabled] is set to false, this should only be used in tests and can cause serious problems in production environments
  1> [2016-04-04 13:32:20,143][INFO ][org.elasticsearch.node   ] [node_t0] stopping ...
  1> [2016-04-04 13:32:20,146][INFO ][org.elasticsearch.node   ] [node_t0] stopped
  1> [2016-04-04 13:32:20,146][INFO ][org.elasticsearch.node   ] [node_t0] closing ...
  1> [2016-04-04 13:32:20,157][INFO ][org.elasticsearch.node   ] [node_t0] closed
  1> [2016-04-04 13:32:20,159][INFO ][org.elasticsearch.node   ] [node_t1] stopping ...
  1> [2016-04-04 13:32:20,160][INFO ][org.elasticsearch.node   ] [node_t1] stopped
  1> [2016-04-04 13:32:20,160][INFO ][org.elasticsearch.node   ] [node_t1] closing ...
  1> [2016-04-04 13:32:20,164][INFO ][org.elasticsearch.node   ] [node_t1] closed
  1> [2016-04-04 13:32:20,167][INFO ][org.elasticsearch.node   ] [node_t2] stopping ...
  1> [2016-04-04 13:32:20,168][INFO ][org.elasticsearch.node   ] [node_t2] stopped
  1> [2016-04-04 13:32:20,168][INFO ][org.elasticsearch.node   ] [node_t2] closing ...
  1> [2016-04-04 13:32:20,176][INFO ][org.elasticsearch.node   ] [node_t2] closed
  1> [2016-04-04 13:32:20,176][INFO ][org.elasticsearch.bwcompat] [OldIndexBackwardsCompatibilityIT#testOldIndexes]: cleaned up after test
  2> REPRODUCE WITH: gradle :core:integTest -Dtests.seed=DAF558AA44C953B8 -Dtests.class=org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT -Dtests.method="testOldIndexes" -Des.logger.level=INFO -Dtests.security.manager=true -Dtests.locale=en-IE -Dtests.timezone=Europe/Lisbon
FAILURE 25.3s | OldIndexBackwardsCompatibilityIT.testOldIndexes <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Could not find payload boost in explanation
   > 2.4764225 = sum of:
   >   2.4764225 = weight(_all:36 in 0) [PerFieldSimilarity], result of:
   >     2.4764225 = fieldWeight in 0, product of:
   >       1.0 = tf(freq=1.0), with freq of:
   >         1.0 = termFreq=1.0
   >       4.952845 = idf(docFreq=47, docCount=2499)
   >       0.5 = fieldNorm(doc=0)
   >   0.0 = match on required clause, product of:
   >     0.0 = # clause
   >     0.20190416 = _type:doc, product of:
   >       1.0 = boost
   >       0.20190416 = queryNorm
   > 	at __randomizedtesting.SeedInfo.seed([DAF558AA44C953B8:FD2F1AFC0324C60F]:0)
   > 	at org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT.assertAllSearchWorks(OldIndexBackwardsCompatibilityIT.java:403)
   > 	at org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT.assertOldIndexWorks(OldIndexBackwardsCompatibilityIT.java:320)
   > 	at org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT.testOldIndexes(OldIndexBackwardsCompatibilityIT.java:305)
   > 	at java.lang.Thread.run(Thread.java:745)
```

```
org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT testOldIndexes
FAILED: 1
ERROR: 0
SKIPPED: 66
TOTAL: 6145

BUILD INFO

Build	20160404170608-D7238A4C
Log	https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/237/console
Duration	14m 54s (894774ms)
Started	2016-04-04T17:06:08.441Z
Ended	2016-04-04T17:21:03.215Z
Exit Code	1
Host	slave-1cdb68c6 (up 90 days)
OS	Fedora 23, Linux 4.2.8-300.fc23.x86_64
Specs	4 CPUs, 15.67GB RAM
java.version	1.8.0_65
java.vm.name	OpenJDK 64-Bit Server VM
java.vm.version	25.65-b01
java.runtime.version	1.8.0_65-b17
java.home	/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-13.b17.fc23.x86_64
```

**Comment by polyfractal** [comment]
Seemed to be failing consistently so I went ahead and silenced the test for now to keep the noise down.

**Comment by jimferenczi** [comment]
This is related to this commit https://github.com/elastic/elasticsearch/commit/b7fb34fed23976ba341873f6244ce982e0a79b9f
I'll investigate but I guess it is due to a misconfiguration during the creation of the 2.3.1 index. 
@clintongormley where can I find the procedure to create the bwc indices ?

**Comment by jpountz** [comment]
@jimferenczi it is in `dev-tools/create_bwc_index.py`

**Comment by jimferenczi** [comment]
Thanks @jpountz I opened https://github.com/elastic/elasticsearch/pull/17530

**Comment by jimferenczi** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/17530
