### ISSUE TITLE
Disk Space full + unassigned nodes after close/open index

### ISSUE THREAD

**Issue by joshreback** [elastic/elasticsearch#17519]
**Elasticsearch version**: 
1.6.0

**JVM version**:
1.8.0_45-internal

**Description of the problem including expected versus actual behavior**:
I recently closed an index to make some changes to the available analyzers. After opening the index, I quickly started seeing disk space on all of our nodes fill up. My guess is that, as part of the failed recovery, Elasticsearch may have created another replica, since each shard has a replica which is not assigned to any node in the cluster (there are currently 3 shards and 2 replicas). I will paste relevant logs and configurations below. 

**Provide logs (if relevant)**:
Here are logs from the master node on the day that the index was closed: 

```
[2016-03-18 01:54:46,161][INFO ][cluster.metadata] [instance name] closing indices [[prod]]
[2016-03-18 01:54:46,161][INFO ][cluster.metadata] [instance name] opening indices [[prod]]
[2016-03-18 01:54:48,493][WARN ][cluster.routing.allocation.decider] [instance name] After allocating, node [nodename] would have less than the required 0b free bytes threshold (-28916726190 bytes free), preventing allocation
[2016-03-18 01:54:48,494][WARN ][cluster.routing.allocation.decider] [instance name] After allocating, node [nodename] would have less than the required 0b free bytes threshold  (-29217364398 bytes free), preventing allocation
```
... one of these lines for each of the ES nodes ...

Then, there is one of these exceptions for each node:
```
[2016-03-18 01:54:49,500][DEBUG][action.search.type] [instance name] All shards failed for phase: [query]
org.elasticsearch.transport.RemoteTransportException: instance name]][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.index.shard.IllegalIndexShardStateException: [prod][0] CurrentState[RECOVERING] operations only allowed when started/relocated
    at org.elasticsearch.index.shard.IndexShard.readAllowed(IndexShard.java:1000)
    at org.elasticsearch.index.shard.IndexShard.acquireSearcher(IndexShard.java:793)
    at org.elasticsearch.index.shard.IndexShard.acquireSearcher(IndexShard.java:789)
    at org.elasticsearch.search.SearchService.createContext(SearchService.java:552)
    at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:532)
    at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:294)
    at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:776)
    at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:767)
    at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:279)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Then:
```
[2016-03-18 01:56:39,891][INFO ][cluster.metadata] [instance name] [prod] create_mapping [mapping name]
.
.
.
[2016-03-18 02:05:18,993][WARN ][cluster.action.shard] [instance name] [prod][1] received shard failed for [prod][1], node[node name], [R], s[INITIALIZING], indexUUID [index id], reason [shard failure [failed recovery][RecoveryFailedException[[prod][1]: Recovery failed from [instance name]{master=true} into [instance name]{master=false}]; nested: RemoteTransportException[[instance name][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[[prod][1] Phase[1] Execution failed]; nested: RecoverFilesRecoveryException[[prod][1] Failed to transfer [0] files with total size of [0b]]; nested: IllegalStateException[try to recover [prod][1] from primary shard with sync id but number of docs differ: 217250828 (instance name, primary) vs 217250830(instance name)]; ]]
```

And then a bunch of low-disk/high-disk watermark errors on each of the nodes. These errors have continued happening since the time the open/close commands were run, and as such they are preventing new data from being indexed.

When I run /cat/_shards/prod, I see:
```
index shard prirep state             docs  store ip          node                                    
prod  0     p      STARTED      218452373 73.5gb 
prod  0     r      STARTED      218452373 73.5gb 
prod  0     r      UNASSIGNED                                                                        
prod  1     p      STARTED      217445482 73.1gb 
prod  1     r      STARTED      217445482 73.1gb 
prod  1     r      UNASSIGNED                                                                        
prod  2     r      INITIALIZING                  
prod  2     r      INITIALIZING                 
prod  2     p      STARTED      218665090 73.2gb
```

and note that one of the replica shards for shard 2 oscillates between an INITIALIZING and UNASSIGNED phase.

Is anyone able to consult on the best way to resolve these issues? My best guess is to scale the # of replicas down to 0, let Elasticsearch clean up the orphaned shards, and then scale back up to 1. But, I'm not really confident enough in my knowledge of ES to move forward quite yet. 

I'm also curious if anyone can provide some more info on why opening/closing an index leads to spikes in disk usage. The docs mention that closing an index can result in such a situation, but they don't give much other background.

Happy to provide any other info if helpful. Thanks a bunch in advance!

**Comment by clintongormley** [comment]
HI @joshreback 

It looks like your disks are reporting free space incorrectly:

    After allocating, node [nodename] would have less than the required 0b free bytes threshold (-28916726190 bytes free)

I remember that a change was made to ignore obviously incorrect reporting of disk size (but i can't find the PR right now, so not sure what version it was in).

I suggest disabling the disk threshold decider: https://www.elastic.co/guide/en/elasticsearch/reference/1.6/index-modules-allocation.html#disk

And I'd suggest upgrading to a newer version - lots of bugs have been fixed since 1.6

**Comment by joshreback** [comment]
Thanks @clintongormley. Ultimately fixed the problem by cutting down the # of replicas from 2 to 1, and ES cleaned itself up just fine. Were there recovery-related bugs that you remember in 1.6? (e.g, ES inadvertently creating another replica). Just trying to understand how this issue may have cropped up in the first place.

**Comment by clintongormley** [comment]
@joshreback difficult to say :)  Just look at the long list of [`:Recovery`](https://github.com/elastic/elasticsearch/pulls?q=is%3Apr+label%3A%3ARecovery+is%3Aclosed) and [`:Allocation`](https://github.com/elastic/elasticsearch/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%3AAllocation+is%3Aclosed+)  changes
