### ISSUE TITLE
NullPointerException in BoolQueryBuilder.doXArrayContent

### ISSUE THREAD

**Issue by diego522** [elastic/elasticsearch#17510]
Hi, i'm getting an error but only when i have a massive requests. Let me explain, I have a service that communicate with ES, and my service receives a lot of request per second, and in a random way i'm getting this error (please see the stacktrace) when I build the request to ES from the service, is not always the same request (i have a stack of request with performance test), for example, from 100 request 4 fail, and in another time 0 fails, it's random. When the tests run, are the unique application that is consuming the service. In average there are 10 concurrent user ( configuration with Gatling test)  requesting to the service.

For my case it's only with a BoolQueryBuilder (all queries are builded using this class)

My configuration is
 - 1.7.2 ES version 
 - 1.7.2 version of Java connector.
 - Spring Boot 1.2.3.RELEASE version
 - Java 1.8.0_25 version

This is my stacktrace
````
java.lang.NullPointerException: null
	at org.elasticsearch.index.query.BoolQueryBuilder.doXArrayContent(BoolQueryBuilder.java:181) ~[elasticsearch-1.7.2.jar!/:na]
	at org.elasticsearch.index.query.BoolQueryBuilder.doXContent(BoolQueryBuilder.java:152) ~[elasticsearch-1.7.2.jar!/:na]
	at org.elasticsearch.index.query.BaseQueryBuilder.toXContent(BaseQueryBuilder.java:66) ~[elasticsearch-1.7.2.jar!/:na]
	at org.elasticsearch.index.query.BoolQueryBuilder.doXArrayContent(BoolQueryBuilder.java:181) ~[elasticsearch-1.7.2.jar!/:na]
	at org.elasticsearch.index.query.BoolQueryBuilder.doXContent(BoolQueryBuilder.java:150) ~[elasticsearch-1.7.2.jar!/:na]
	at org.elasticsearch.index.query.BaseQueryBuilder.toXContent(BaseQueryBuilder.java:66) ~[elasticsearch-1.7.2.jar!/:na]
	at org.elasticsearch.action.support.QuerySourceBuilder.innerToXContent(QuerySourceBuilder.java:59) ~[elasticsearch-1.7.2.jar!/:na]
	at org.elasticsearch.search.builder.SearchSourceBuilder.innerToXContent(SearchSourceBuilder.java:789) ~[elasticsearch-1.7.2.jar!/:na]
	at org.elasticsearch.search.builder.SearchSourceBuilder.toXContent(SearchSourceBuilder.java:767) ~[elasticsearch-1.7.2.jar!/:na]
	at org.elasticsearch.search.builder.SearchSourceBuilder.buildAsBytes(SearchSourceBuilder.java:756) ~[elasticsearch-1.7.2.jar!/:na]
	... 81 common frames omitted
Wrapped by: org.elasticsearch.search.builder.SearchSourceBuilderException: Failed to build search source
	at org.elasticsearch.search.builder.SearchSourceBuilder.buildAsBytes(SearchSourceBuilder.java:759) ~[elasticsearch-1.7.2.jar!/:na]
	at org.elasticsearch.action.search.SearchRequest.source(SearchRequest.java:253) ~[elasticsearch-1.7.2.jar!/:na]
	at org.elasticsearch.action.search.SearchRequestBuilder.request(SearchRequestBuilder.java:1102) ~[elasticsearch-1.7.2.jar!/:na]
	at org.elasticsearch.action.search.MultiSearchRequestBuilder.add(MultiSearchRequestBuilder.java:57) ~[elasticsearch-1.7.2.jar!/:na]
	at com.search.repository.SearchRepository.executeQuery(SearchRepository.java:86) ~[search-io-service-sdk-1.1.0-SNAPSHOT.jar!/:na]
	at com.search.repository.SearchRepository$$FastClassBySpringCGLIB$$dcf9ea4e.invoke(<generated>) [spring-core-4.1.6.RELEASE.jar!/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717) [spring-aop-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) [spring-tx-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) [spring-aop-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
````

I need to know if this problem could be caused by the concurrent user requests to the service , or could be a ES issue. If you need more details, please let me know.

Thank you :)

**Comment by clintongormley** [comment]
Hi @diego522 

You haven't given us any indication of what requests you are running  other than the fact that they're "massive", but I don't know what massive means here, or what your code looks like.  Also, you're on an old version. This code has been completely rewritten in later versions.  BoolQueryBuilder no longer exists in 5.0.

If you provide more info, somebody may be interested in looking at it, but given the changes that have happened subsequently it is unlikely.  I'd suggest testing out your code on a later version and reopening this bug (with more info) if you can still replicate the issue.

thanks
