### ISSUE TITLE
_cat/plugins throws NullPointerException on client nodes

### ISSUE THREAD

**Issue by terjesannum** [elastic/elasticsearch#17533]
**Elasticsearch version**: 2.3.1

**JVM version**: OpenJDK Runtime Environment (build 1.8.0_71-b15)

**OS version**: Linux 2.6.32-573.12.1.el6.x86_64 #1 SMP

**Description of the problem including expected versus actual behavior**:

Calling _cat/plugins on client nodes throws NullPointerException:

`[2016-04-05 10:02:28,895][WARN ][rest.suppressed          ] /_cat/plugins Params: {}
java.lang.NullPointerException
        at org.elasticsearch.rest.action.cat.RestPluginsAction.buildTable(RestPluginsAction.java:98)
        at org.elasticsearch.rest.action.cat.RestPluginsAction.access$000(RestPluginsAction.java:41)
        at org.elasticsearch.rest.action.cat.RestPluginsAction$1$1.buildResponse(RestPluginsAction.java:69)
        at org.elasticsearch.rest.action.cat.RestPluginsAction$1$1.buildResponse(RestPluginsAction.java:66)
        at org.elasticsearch.rest.action.support.RestResponseListener.processResponse(RestResponseListener.java:43)
        at org.elasticsearch.rest.action.support.RestActionListener.onResponse(RestActionListener.java:49)
        at org.elasticsearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:89)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
`

The problem seems only to happen on client nodes, not data nodes.

**Steps to reproduce**:
 1. curl http://localhost:9200/_cat/plugins

**Comment by clintongormley** [comment]
This has been fixed by #16898
