### ISSUE TITLE
 Java api field  script encounter BigDecimal Exception in Elastic 2.1

### ISSUE THREAD

**Issue by game365** [elastic/elasticsearch#17531]
**Elasticsearch 2.1.0**

**jdk1.7.0_79x64**

**Debian GNU/Linux 7.8 (wheezy)  64bit**

 1.I set up my Elastic 2.1.0 cluster and I do 

```
PUT  bucket/relation/1 
{
  "name":"Jake",
  "frozen":300000
}
```

 2.use elastic java api

```
    try {
        Settings settings = Settings.settingsBuilder().put("cluster.name", "my-application").build();
        Client client = TransportClient.builder().settings(settings).build().addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("10.166.224.199"), 9300));
    } catch (UnknownHostException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
    SearchRequestBuilder builder = client.prepareSearch("bucket").setTypes("relation");
    builder.addScriptField("money", new Script("doc['frozen'].value / 100"));
    SearchResponse searchResponse=builder.get();
```

 3.I get error

```
 Exception in thread "main" NotSerializableExceptionWrapper[Can't write type [class java.math.BigDecimal]]
    at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:416)
    at org.elasticsearch.search.internal.InternalSearchHitField.writeTo(InternalSearchHitField.java:112)
    at org.elasticsearch.search.internal.InternalSearchHit.writeTo(InternalSearchHit.java:728)
    at org.elasticsearch.search.internal.InternalSearchHits.writeTo(InternalSearchHits.java:261)
    at org.elasticsearch.search.internal.InternalSearchHits.writeTo(InternalSearchHits.java:232)
    at org.elasticsearch.search.internal.InternalSearchResponse.writeTo(InternalSearchResponse.java:121)
    at org.elasticsearch.action.search.SearchResponse.writeTo(SearchResponse.java:207)
    at org.elasticsearch.transport.netty.NettyTransportChannel.sendResponse(NettyTransportChannel.java:97)
    at org.elasticsearch.transport.netty.NettyTransportChannel.sendResponse(NettyTransportChannel.java:75)
    at org.elasticsearch.action.support.HandledTransportAction$TransportHandler$1.onResponse(HandledTransportAction.java:49)
    at org.elasticsearch.action.support.HandledTransportAction$TransportHandler$1.onResponse(HandledTransportAction.java:45)
    at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction$2.doRun(TransportSearchQueryThenFetchAction.java:155)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**But when I use sense:**

```
GET  bucket/relation/_search
{
 "script_fields" : {
"money" : {
"script" : "doc['frozen'].value / 100"
}
 }
}
```

it works.

**Comment by prateekengineer** [comment]
This method **public void writeGenericValue(@Nullable Object value) throws IOException**   checks the type of Object while writing generic value .It has provide support for various types but 
not for object of BigDecimal type.

So it throws **IOException("Can't write type [" + type + "]")**

**Comment by smartcat315** [comment]
This problem has been bothering me for a long time.Is the problem solved?

**Comment by rjernst** [comment]
Groovy has been removed for 6.0 and this was an issue with BigDecimal being accessible in groovy. Painless has BigDecimal whitelisted so this should not be an issue.
