### ISSUE TITLE
Invalid shift value in prefixCoded bytes

### ISSUE THREAD

**Issue by s12v** [elastic/elasticsearch#17559]
**Elasticsearch version**: 1.7.5

**JVM version**: 8-jre

**OS version**: docker

**Description of the problem including expected versus actual behavior**:

Sorting fails after field with the same name is inserted in a *different* type with a different mapping within the same index. Expected: results from specified type.

**Steps to reproduce**:
```
PUT test

PUT test/_mapping/foo
{
  "properties": {
    "id": {
      "type": "integer"
    }
  }
}

POST test/foo
{
  "id": 1
}

# Works
GET test/foo/_search
{
  "sort": "id"
}

# Breaks sorting by id in ANY type within test index
POST test/bar
{
  "id": 2
}

# Doesn't work
GET test/foo/_search
{
  "sort": "id"
}

# Doesn't work either
GET test/bar/_search
{
  "sort": "id"
}
```

**Provide logs (if relevant)**:

```
[2016-04-06 11:33:43,399][DEBUG][action.search.type       ] [Umbo] [test][4], node[utxVpAQfT_GXAYpH1nq3kQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@3fcf2407] lastShard [true]
org.elasticsearch.search.query.QueryPhaseExecutionException: [test][4]: query[ConstantScore(cache(_type:foo))],from[0],size[10],sort[<custom:"id": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@6676d6dc>]: Query Failed [Failed to execute main query]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:163)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:301)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:312)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchException: java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)
	at org.elasticsearch.index.fielddata.plain.AbstractIndexFieldData.load(AbstractIndexFieldData.java:80)
	at org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource$1.getLongValues(LongValuesComparatorSource.java:67)
	at org.apache.lucene.search.FieldComparator$LongComparator.setNextReader(FieldComparator.java:716)
	at org.apache.lucene.search.TopFieldCollector$OneComparatorNonScoringCollector.setNextReader(TopFieldCollector.java:97)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:612)
	at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:191)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:581)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:533)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:510)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:345)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:150)
	... 8 more
Caused by: org.elasticsearch.common.util.concurrent.UncheckedExecutionException: java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)
	at org.elasticsearch.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at org.elasticsearch.common.cache.LocalCache.get(LocalCache.java:3937)
	at org.elasticsearch.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
	at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache.load(IndicesFieldDataCache.java:167)
	at org.elasticsearch.index.fielddata.plain.AbstractIndexFieldData.load(AbstractIndexFieldData.java:74)
	... 18 more
Caused by: java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)
	at org.apache.lucene.util.NumericUtils.getPrefixCodedIntShift(NumericUtils.java:209)
	at org.elasticsearch.index.fielddata.ordinals.OrdinalsBuilder$2.accept(OrdinalsBuilder.java:445)
	at org.apache.lucene.index.FilteredTermsEnum.next(FilteredTermsEnum.java:244)
	at org.elasticsearch.index.fielddata.RamAccountingTermsEnum.next(RamAccountingTermsEnum.java:82)
	at org.elasticsearch.index.fielddata.ordinals.OrdinalsBuilder$3.next(OrdinalsBuilder.java:472)
	at org.elasticsearch.index.fielddata.plain.PackedArrayIndexFieldData.loadDirect(PackedArrayIndexFieldData.java:109)
	at org.elasticsearch.index.fielddata.plain.PackedArrayIndexFieldData.loadDirect(PackedArrayIndexFieldData.java:49)
	at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache$1.call(IndicesFieldDataCache.java:180)
	at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache$1.call(IndicesFieldDataCache.java:167)
	at org.elasticsearch.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742)
	at org.elasticsearch.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at org.elasticsearch.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at org.elasticsearch.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at org.elasticsearch.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 22 more
```

**Comment by clintongormley** [comment]
This is a known issue with mappings in 1.x.  In 2.0 you are no longer allowed to have fields with the same name but different mappings in different types. See #8870

**Comment by mohdnavedshaikh** [comment]
Hi @clintongormley ,

I have some what same kind of issue.Kindly, help me to resolve the issue i am recieving .

I have below aggregation query:

{
  "query": {
    "bool": {
      "must": [
        {
          "bool": {
            "must": [
              {
                "nested": {
                  "query": {
                    "term": {
                      "skus.rack_status": "Y"
                    }
                  },
                  "path": "skus"
                }
              },
              {
                "terms": {
                  "boutique_id": [
                    "14404"
                  ]
                }
              }
            ]
          }
        },
        {
          "nested": {
            "filter": {
              "bool": {
                "must": {
                  "match_all": {}
                }
              }
            },
            "path": "skus"
          }
        }
      ]
    }
  },
  "aggregations": {
    "presaleFilter": {
      "terms": {
        "field": "is_presale"
      }
    },
    "filterCondition": {
      "filter": {
        "bool": {
          "must": {
            "nested": {
              "filter": {
                "bool": {
                  "must": [
                    {
                      "match_all": {}
                    },
                    {
                      "range": {
                        "skus.inv": {
                          "from": 0,
                          "to": null,
                          "include_lower": false,
                          "include_upper": true
                        }
                      }
                    }
                  ]
                }
              },
              "path": "skus"
            }
          }
        }
      },
      "aggregations": {
        "topCategoryFilter": {
          "terms": {
            "field": "category_id",
            "size": 2147483647
          },
          "aggregations": {
            "subCategoryFilter": {
              "terms": {
                "field": "sub_category_id",
                "size": 2147483647
              }
            }
          }
        },
        **"brandFilter": {
          "terms": {
            "field": "brand_id",
            "size": 2147483647
          }**
        }, "productClass": {
          "terms": {
            "field": "product_class_id",
            "size": 2147483647
          }
        },
        "skuFilter": {
          "nested": {
            "path": "skus"
          },
          "aggregations": {
            "sizeValues": {
              "nested": {
                "path": "skus.attribute"
              },
              "aggregations": {
                "attributeId": {
                  "terms": {
                    "field": "skus.attribute.attribute_id",
                    "size": 2147483647
                  },
                  "aggregations": {
                    "attributeValue": {
                      "terms": {
                        "field": "skus.attribute.attribute_value",
                        "size": 2147483647
                      }
                    }
                  }
                }
              }
            },
            "fromAge": {
              "terms": {
                "field": "skus.from_age"
              },
              "aggregations": {
                "toAge": {
                  "terms": {
                    "field": "skus.to_age",
                    "size": 2147483647
                  }
                },
                "from_to_age": {
                  "reverse_nested": {}
                }
              }
            },
            "gender": {
              "terms": {
                "field": "skus.gender",
                "size": 2147483647
              },
              "aggregations": {
                "gender_to_skus": {
                  "reverse_nested": {}
                }
              }
            },
            "min_price": {
              "min": {
                "field": "skus.sale_price"
              }
            },
            "max_price": {
              "max": {
                "field": "skus.sale_price"
              }
            }
          }
        }
      }
    }
  },
  "from": 0,
  "size": 56
}

The highlighted if commented out then i get response else i get below given  exception : 

org.elasticsearch.ElasticsearchException: java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)
	at org.elasticsearch.index.fielddata.plain.AbstractIndexFieldData.load(AbstractIndexFieldData.java:80)
	at org.elasticsearch.search.aggregations.support.ValuesSource$MetaData.load(ValuesSource.java:88)
	at org.elasticsearch.search.aggregations.support.AggregationContext.numericField(AggregationContext.java:159)
	at org.elasticsearch.search.aggregations.support.AggregationContext.valuesSource(AggregationContext.java:137)
	at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.create(ValuesSourceAggregatorFactory.java:53)
	at org.elasticsearch.search.aggregations.AggregatorFactories.createAndRegisterContextAware(AggregatorFactories.java:53)
	at org.elasticsearch.search.aggregations.AggregatorFactories.createSubAggregators(AggregatorFactories.java:71)
	at org.elasticsearch.search.aggregations.Aggregator.<init>(Aggregator.java:191)
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.<init>(BucketsAggregator.java:39)
	at org.elasticsearch.search.aggregations.bucket.SingleBucketAggregator.<init>(SingleBucketAggregator.java:32)
	at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregator.<init>(FilterAggregator.java:45)
	at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregator$Factory.create(FilterAggregator.java:86)
	at org.elasticsearch.search.aggregations.AggregatorFactories.createAndRegisterContextAware(AggregatorFactories.java:53)
	at org.elasticsearch.search.aggregations.AggregatorFactories.createTopLevelAggregators(AggregatorFactories.java:157)
	at org.elasticsearch.search.aggregations.AggregationPhase.preProcess(AggregationPhase.java:79)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:100)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:301)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:312)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.common.util.concurrent.UncheckedExecutionException: java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)
	at org.elasticsearch.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at org.elasticsearch.common.cache.LocalCache.get(LocalCache.java:3937)
	at org.elasticsearch.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
	at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache.load(IndicesFieldDataCache.java:167)
	at org.elasticsearch.index.fielddata.plain.AbstractIndexFieldData.load(AbstractIndexFieldData.java:74)
	... 23 more
Caused by: java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)
	at org.apache.lucene.util.NumericUtils.getPrefixCodedIntShift(NumericUtils.java:209)
	at org.elasticsearch.index.fielddata.ordinals.OrdinalsBuilder$2.accept(OrdinalsBuilder.java:445)
	at org.apache.lucene.index.FilteredTermsEnum.next(FilteredTermsEnum.java:244)
	at org.elasticsearch.index.fielddata.RamAccountingTermsEnum.next(RamAccountingTermsEnum.java:82)
	at org.elasticsearch.index.fielddata.ordinals.OrdinalsBuilder$3.next(OrdinalsBuilder.java:472)
	at org.elasticsearch.index.fielddata.plain.PackedArrayIndexFieldData.loadDirect(PackedArrayIndexFieldData.java:109)
	at org.elasticsearch.index.fielddata.plain.PackedArrayIndexFieldData.loadDirect(PackedArrayIndexFieldData.java:49)
	at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache$1.call(IndicesFieldDataCache.java:180)
	at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache$1.call(IndicesFieldDataCache.java:167)
	at org.elasticsearch.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742)
	at org.elasticsearch.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at org.elasticsearch.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at org.elasticsearch.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at org.elasticsearch.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 27 more


Thank You in advance.
