### ISSUE TITLE
Test failure in FunctionScoreQueryBuilderTests.testMustRewrite

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#17583]
Build URL:
```
http://build-us-00.elastic.co/job/es_g1gc_master_metal/35311
```

Reproduce command:
```
gradle :core:test -Dtests.seed=35D37728EEA24403 -Dtests.class=org.elasticsearch.index.query.functionscore.FunctionScoreQueryBuilderTests -Dtests.method="testMustRewrite" -Des.logger.level=WARN -Dtests.security.manager=true -Dtests.locale=he-IL -Dtests.timezone=America/Caracas
```

Failure:
```
java.lang.IllegalArgumentException: function_score : scale must be > 0.0.
	at __randomizedtesting.SeedInfo.seed([35D37728EEA24403:813C041596F54283]:0)
	at org.elasticsearch.index.query.functionscore.DecayFunctionBuilder$AbstractDistanceScoreFunction.<init>(DecayFunctionBuilder.java:504)
	at org.elasticsearch.index.query.functionscore.DecayFunctionBuilder$NumericFieldDataScoreFunction.<init>(DecayFunctionBuilder.java:415)
	at org.elasticsearch.index.query.functionscore.DecayFunctionBuilder.parseDateVariable(DecayFunctionBuilder.java:321)
	at org.elasticsearch.index.query.functionscore.DecayFunctionBuilder.parseVariable(DecayFunctionBuilder.java:202)
	at org.elasticsearch.index.query.functionscore.DecayFunctionBuilder.doToFunction(DecayFunctionBuilder.java:183)
	at org.elasticsearch.index.query.functionscore.ScoreFunctionBuilder.toFunction(ScoreFunctionBuilder.java:137)
	at org.elasticsearch.index.query.functionscore.FunctionScoreQueryBuilder.doToQuery(FunctionScoreQueryBuilder.java:327)
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:78)
	at org.elasticsearch.index.query.AbstractQueryTestCase.testMustRewrite(AbstractQueryTestCase.java:981)
	at org.elasticsearch.index.query.functionscore.FunctionScoreQueryBuilderTests.testMustRewrite(FunctionScoreQueryBuilderTests.java:611)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1764)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:871)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:907)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:921)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:809)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:460)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:880)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:781)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:816)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:827)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by colings86** [comment]
@nik9000 could this be due to your changes yesterday?

**Comment by javanna** [comment]
I believe this was fixex by https://github.com/elastic/elasticsearch/commit/cd982ade99ce2db939b7ed9278ba199010641131 .
