### ISSUE TITLE
Rest Test failure: indices.stats/10_index/Index when testing using zip distributions on debian

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#17594]
Build URL:

```
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=debian/213
```

Reproduce Command (note: this does not reproduce locally for me):

```
gradle :distribution:integ-test-zip:integTest -Dtests.seed=C508E06E98CA79E -Dtests.class=org.elasticsearch.test.rest.RestIT -Dtests.method="test {p0=indices.stats/10_index/Index - one index}" -Des.logger.level=WARN -Dtests.security.manager=true -Dtests.locale=el-CY -Dtests.timezone=Poland
```

Failure:

```
java.lang.AssertionError: expected [2xx] status code but api [index] returned [503 Service Unavailable] [{"error":{"root_cause":[{"type":"process_cluster_event_timeout_exception","reason":"failed to process cluster event (put-mapping [bar]) within 30s"}],"type":"process_cluster_event_timeout_exception","reason":"failed to process cluster event (put-mapping [bar]) within 30s"},"status":503}]
   >    at __randomizedtesting.SeedInfo.seed([C508E06E98CA79E:8404B1DC4770CA66]:0)
   >    at org.elasticsearch.test.rest.section.DoSection.execute(DoSection.java:107)
   >    at org.elasticsearch.test.rest.ESRestTestCase.test(ESRestTestCase.java:387)
   >    at java.lang.Thread.run(Thread.java:745)
```

**Comment by javanna** [comment]
given that this issue had no activity in more than a year, I would close it. We can always reopen if we encounter the same failure again.
