### ISSUE TITLE
java.security.AccessControlException in ESIntegTestCase when using Mockito

### ISSUE THREAD

**Issue by tkaiser** [elastic/elasticsearch#17615]
May be related to #16459.

**Elasticsearch version**: 2.3.1

**JVM version**:
```
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

**OS version**:
OS X 10.11.4

**Description of the problem including expected versus actual behavior**:
When initializing a Mockito mock inside a test class inhering from `ESIntegTestCase`, I get a AccessControlException. Running the test with `-Dtests.security.manager=false` prevents the exception.

**Steps to reproduce**:
 ```
import static org.mockito.Mockito.mock;

import java.util.List;

import org.elasticsearch.test.ESIntegTestCase;
import org.junit.Test;

public class SecurityManagerTest extends ESIntegTestCase {

    @Test
    public void test() throws Exception {
        final List mock = mock(List.class);
    }
}

```

**Provide logs (if relevant)**:
```
java.lang.ExceptionInInitializerError
	at __randomizedtesting.SeedInfo.seed([7DFCAB452E627517:F5A8949F809E18EF]:0)
	at org.mockito.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:167)
	at org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:217)
	at org.mockito.cglib.core.KeyFactory$Generator.create(KeyFactory.java:145)
	at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:117)
	at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:109)
	at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:105)
	at org.mockito.cglib.proxy.Enhancer.<clinit>(Enhancer.java:70)
	at org.powermock.api.mockito.repackaged.ClassImposterizer.createProxyClass(ClassImposterizer.java:95)
	at org.powermock.api.mockito.repackaged.ClassImposterizer.imposterise(ClassImposterizer.java:57)
	at org.powermock.api.mockito.repackaged.ClassImposterizer.imposterise(ClassImposterizer.java:49)
	at org.powermock.api.mockito.repackaged.CglibMockMaker.createMock(CglibMockMaker.java:24)
	at org.powermock.api.mockito.internal.mockmaker.PowerMockMaker.createMock(PowerMockMaker.java:46)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
	at org.mockito.Mockito.mock(Mockito.java:1285)
	at org.mockito.Mockito.mock(Mockito.java:1163)
	at com.compuware.apm.elasticsearch.util.SecurityManagerTest.test(SecurityManagerTest.java:14)

...

Caused by: java.security.AccessControlException: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.reflect.AccessibleObject.setAccessible(AccessibleObject.java:128)
	at org.mockito.cglib.core.ReflectUtils$2.run(ReflectUtils.java:57)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.mockito.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:47)

```

**Comment by jasontedor** [comment]
We provide [securemock](https://github.com/elastic/securemock for mocking under the security manager.
