### ISSUE TITLE
Primary shard failures should not block other primary shard recoveries

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#17630]
On master, if I have an index with 5 primary shards, and I corrupt the `0` and
`1` shards, once ES hits a corrupt shard, it will not attempt to recovery the
next primary shard.

**Steps to reproduce**:
 1. Create an index with 5 shards
 2. Corrupt the 0 and 1 shards (I used <https://github.com/joshsegall/corrupt>
 to add bytes to the end of the `segments_#` files)
 3. Start up ES

Here's what I get:

```
[2016-04-08 14:11:35,850][WARN ][indices.cluster          ] [Captain Zero] [[i][1]] marking and sending shard failed due to [failed recovery]
[i/QzoKda9aQCG_hCaZQ18GEg][[i][1]] IndexShardRecoveryException[failed to fetch index version after copying it over]; nested: IndexShardRecoveryException[shard allocated for local recovery (post api), should exist, but doesn't, current files: [segments_3, write.lock]]; nested: IndexFormatTooOldException[Format version is not supported (resource BufferedChecksumIndexInput(NIOFSIndexInput(path="/home/hinmanm/scratch/elasticsearch-5.0.0-alpha1-SNAPSHOT/data/elasticsearch/nodes/0/indices/QzoKda9aQCG_hCaZQ18GEg/1/index/segments_3"))): 317397653 (needs to be between 1071082519 and 1071082519). This version of Lucene only supports indexes created with release 5.0 and later.];
    at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:208)
    at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:78)
    at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:123)
    at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:76)
    at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1092)
    at org.elasticsearch.indices.cluster.IndicesClusterStateService.lambda$applyInitializingShard$2(IndicesClusterStateService.java:636)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:408)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: [i/QzoKda9aQCG_hCaZQ18GEg][[i][1]] IndexShardRecoveryException[shard allocated for local recovery (post api), should exist, but doesn't, current files: [segments_3, write.lock]]; nested: IndexFormatTooOldException[Format version is not supported (resource BufferedChecksumIndexInput(NIOFSIndexInput(path="/home/hinmanm/scratch/elasticsearch-5.0.0-alpha1-SNAPSHOT/data/elasticsearch/nodes/0/indices/QzoKda9aQCG_hCaZQ18GEg/1/index/segments_3"))): 317397653 (needs to be between 1071082519 and 1071082519). This version of Lucene only supports indexes created with release 5.0 and later.];
    at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:193)
    ... 9 more
Caused by: org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(NIOFSIndexInput(path="/home/hinmanm/scratch/elasticsearch-5.0.0-alpha1-SNAPSHOT/data/elasticsearch/nodes/0/indices/QzoKda9aQCG_hCaZQ18GEg/1/index/segments_3"))): 317397653 (needs to be between 1071082519 and 1071082519). This version of Lucene only supports indexes created with release 5.0 and later.
    at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:295)
    at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:284)
    at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:441)
    at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:438)
    at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:685)
    at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:637)
    at org.apache.lucene.index.SegmentInfos.readLatestCommit(SegmentInfos.java:443)
    at org.elasticsearch.common.lucene.Lucene.readSegmentInfos(Lucene.java:123)
    at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:191)
    at org.elasticsearch.index.store.Store.readLastCommittedSegmentsInfo(Store.java:176)
    at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:184)
```

Which is great, and expected (I corrupted the files).

What I do expect is that ES will skip this shard (shard 1) since it failed and
try shard 0, instead, it gives up and never gets that far, leaving it unassigned
and un-tried:

```
index shard prirep state      docs store ip        node
i     4     p      STARTED       0  130b 127.0.0.1 Captain Zero
i     4     r      UNASSIGNED
i     3     p      STARTED       0  130b 127.0.0.1 Captain Zero
i     3     r      UNASSIGNED
i     2     p      STARTED       0  130b 127.0.0.1 Captain Zero
i     2     r      UNASSIGNED
i     1     p      UNASSIGNED
i     1     r      UNASSIGNED
i     0     p      UNASSIGNED
i     0     r      UNASSIGNED
```

This might not sound like a big deal, however, for the shard that was tried
(shard 1), `UnassignedInfo` will contain the `IndexShardRecoveryException` with
all the details about the file being corrupt and all that. For the shard that
was never tried (shard 0), it doesn't have those details (even though I
corrupted the shard).

It would be great if both shards' `UnassignedInfo` had any exception that
occurred during recovery.

**Comment by bleskes** [comment]
In order to assign primaries the master goes out and asks the node if they have data for those shards. With 2.x we actually try to [read the lucene index](org.elasticsearch.index.store.Store#tryOpenIndex) before returning a response. If the nodes fail to open the index the shard will not be assigned to them and will be left unassigned (assuming no other copy is available) and nothing will change in the unassigned info (at least today).  Currently you can use the shard stores API to get the same information the master uses (and this should be added IMO to the new allocation explain API ).

What surprise me in this report is that shard 1 actually managed to be assigned. It seems the exceptions comes from reading the segments info, which is also read by the [shard data fetching](TransportNodesListGatewayStartedShards) action mentioned above. Do you have any idea what this may have happened?

**Comment by dakrone** [comment]
> Do you have any idea what this may have happened?

The only thing I could think of is that the shard store fetching returned successfully and then it tried to open the actual index. What's interesting is that the same corruption was added to both the 0 and 1 shards

**Comment by bleskes** [comment]
@dakrone I found the source of the race condition and opened #17663 . I'm not sure it fully closes this issue as I think part of the problem is proper reporting. I think the allocation explain API should cover this. Do you agree and there an issue we can close this in favor of?

**Comment by dakrone** [comment]
> I think the allocation explain API should cover this. Do you agree and there an issue we can close this in favor of?

Yeah, I've already started integrating the shard stores API into the allocation explain API, so I'll close this for now. Thanks for opening the PR
