### ISSUE TITLE
Failed to index docx file with mapper-attachments plugin that comes with Elasticsearch 2.3.1

### ISSUE THREAD

**Issue by clarencechan** [elastic/elasticsearch#17641]
I run ES with the following setup:
- ES 2.3.1 and Mapper-attachments plugin that comes with it
- Oracle java 8
- Ubuntu 14.04

I saw the following error when I tried to index docx files:

```
[2016-04-11 15:01:37,521][DEBUG][mapper.attachment        ] Failed to extract [100000] characters of text for [null]: [Unexpected RuntimeException from org.apache.tika.parser.microsoft.ooxml.OOXMLParser@3e3917f2]
[2016-04-11 15:01:37,521][TRACE][mapper.attachment        ] exception caught
org.apache.tika.exception.TikaException: Unexpected RuntimeException from org.apache.tika.parser.microsoft.ooxml.OOXMLParser@3e3917f2
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:282)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120)
	at org.apache.tika.Tika.parseToString(Tika.java:537)
	at org.elasticsearch.mapper.attachments.TikaImpl$1.run(TikaImpl.java:94)
	at org.elasticsearch.mapper.attachments.TikaImpl$1.run(TikaImpl.java:91)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.mapper.attachments.TikaImpl.parse(TikaImpl.java:91)
	at org.elasticsearch.mapper.attachments.AttachmentMapper.parse(AttachmentMapper.java:481)
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:309)
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:436)
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:262)
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:122)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309)
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:580)
	at org.elasticsearch.index.shard.IndexShard.prepareIndexOnReplica(IndexShard.java:569)
	at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnReplica(TransportIndexAction.java:185)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnReplica(TransportIndexAction.java:170)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnReplica(TransportIndexAction.java:66)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncReplicaAction.doRun(TransportReplicationAction.java:392)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReplicaOperationTransportHandler.messageReceived(TransportReplicationAction.java:291)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReplicaOperationTransportHandler.messageReceived(TransportReplicationAction.java:283)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:300)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.poi.openxml4j.exceptions.InvalidOperationException: Can't open the specified file: '/tmp/apache-tika-2211524028819836878.tmp'
	at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:112)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:225)
	at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:69)
	at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:87)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	... 27 more
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.zip.ZipFile.<init>(ZipFile.java:164)
	at org.apache.poi.openxml4j.util.ZipSecureFile.<init>(ZipSecureFile.java:105)
	at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipFile(ZipHelper.java:175)
	at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:110)
	... 31 more

```

I thought ES 2.3.1 should have fixed the indexing issue for docx files, but it's still no luck for me.

**Comment by dadoonet** [comment]
Could you update your description and paste the full stacktrace using 3 ticks ( \` ) at the beginning and end of the stacktrace?

See https://guides.github.com/features/mastering-markdown/ (Syntax highlighting).

**Comment by clarencechan** [comment]
Updated.

**Comment by clintongormley** [comment]
For some reason, java zip can't open the file.  Is there any more exception to shed light on that? Are you sure the file is readable?  

What happens if you run elasticsearch as:

    ./bin/elasticsearch --security.manager.enabled false

**Comment by clarencechan** [comment]
> Is there any more exception to shed light on that?

I could not find any other exceptions.

> ./bin/elasticsearch --security.manager.enabled false

Same result

> Are you sure the file is readable?

I've done a few more tests with mixed results. Some docx were ok while some were not. But I have no problem opening all the docx from Microsoft Word. Hence, they are all readable.

**Comment by clintongormley** [comment]
Any chance you could make the document available to us so we could try it out?

**Comment by clarencechan** [comment]
[test1.docx](https://github.com/elastic/elasticsearch/files/220587/test1.docx) is NOT ok
[test2a.docx](https://github.com/elastic/elasticsearch/files/220589/test2a.docx) is ok

**Comment by clarencechan** [comment]
Sry, I messed up with my test files. test1.docx is actually ok. I will upload the files once again after i sorted out my test files.

**Comment by clarencechan** [comment]
I found the problem. It's the golang driver that caused the problem. It's not an ES bug.

**Comment by clintongormley** [comment]
thanks for letting us know @clarencechan
