### ISSUE TITLE
ElasticSearch2.1.1 cluster do not work using Shield plugin

### ISSUE THREAD

**Issue by robin820224** [elastic/elasticsearch#17668]
I am using the ES 2.1.1. I have created a cluster with name "wisesearch", which included two node "wisesearch-node1" and "wisesearch-node2", it had worked fine until I installed Shield plugin.

After start node1, the node1's log show "[wisesearch-node1] failed to send join request to master" error. And the other hand, the node2's log show "java.net.NoRouteToHostException: No route to host". The ES will show "cluster_block_exception" error with query index:
{
"error" : {
"root_cause" : [ {
"type" : "cluster_block_exception",
"reason" : "blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];"
} ],
"type" : "cluster_block_exception",
"reason" : "blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];"
},
"status" : 503
}

Node1's log:
[2016-04-11 17:35:05,870][INFO ][discovery.zen ] [wisesearch-node1] failed to send join request to master [{wisesearch-node2}{WSGMaGHSQEyrHZmONb8J6w}{10.47.211.106}{10.47.211.106:9300}], reason [RemoteTransportException[[wisesearch-node2][10.47.211.106:9300][internal:discovery/zen/join]]; nested: ConnectTransportException[[wisesearch-node1][10.47.211.95:9300] connect_timeout[30s]]; nested: NotSerializableExceptionWrapper[No route to host]; ]

Node2's log:
[2016-04-11 17:35:37,562][WARN ][shield.transport.netty ] [wisesearch-node2] exception caught on transport layer [[id: 0x14feb6ff]], closing connection
java.net.NoRouteToHostException: No route to host
at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)

The Node1's elasticsearch.yum file:
cluster.name: wisesearch
node.name: wisesearch-node1
network.host: 0.0.0.0
discovery.zen.ping.unicast.hosts: ["10.47.211.106"]
discovery.zen.minimum_master_nodes: 2
shield.audit.enabled: true

The Node2's elasticsearch.yum file:
cluster.name: wisesearch
node.name: wisesearch-node2
network.host: 0.0.0.0
discovery.zen.ping.unicast.hosts: ["10.47.211.95"]
discovery.zen.minimum_master_nodes: 2
shield.audit.enabled: true

**Comment by jaymode** [comment]
This was asked and answered in our forums https://discuss.elastic.co/t/after-use-shield-the-es-cluster-do-not-work/4706 so I am closing this issue.
