### ISSUE TITLE
Better handling when _source is disabled for reindex api

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#17666]
**Elasticsearch version**: 2.3.1

**Description of the problem including expected versus actual behavior**:

When _source is disabled, reindex api throws a NPE. 

**Steps to reproduce**:
 1.  Create an index with a type that has _source disabled
 2.  Create a document in the index
 3.  Use the reindex api and you will see:

```
{
   "error": {
      "root_cause": [
         {
            "type": "null_pointer_exception",
            "reason": null
         }
      ],
      "type": "null_pointer_exception",
      "reason": null
   },
   "status": 500
}
```

**Provide logs (if relevant)**:

```
[2016-04-11 15:39:45,057][WARN ][rest.suppressed          ] /_reindex Params: {}
java.lang.NullPointerException
	at org.elasticsearch.common.compress.lzf.LZFCompressor.isCompressed(LZFCompressor.java:54)
	at org.elasticsearch.common.compress.CompressorFactory.compressor(CompressorFactory.java:74)
	at org.elasticsearch.common.compress.CompressorFactory.uncompressIfNeeded(CompressorFactory.java:118)
	at org.elasticsearch.search.internal.InternalSearchHit.sourceRef(InternalSearchHit.java:200)
	at org.elasticsearch.index.reindex.TransportReindexAction$AsyncIndexBySearchAction.buildIndexRequest(TransportReindexAction.java:152)
	at org.elasticsearch.index.reindex.AbstractAsyncBulkIndexByScrollAction.buildBulk(AbstractAsyncBulkIndexByScrollAction.java:90)
	at org.elasticsearch.index.reindex.AbstractAsyncBulkByScrollAction$2.doRun(AbstractAsyncBulkByScrollAction.java:199)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

While the reindex api requires _source, it will be nice to handle this situation better.

**Comment by nik9000** [comment]
Fair enough!

**Comment by ppf2** [comment]
Thanks!
