### ISSUE TITLE
GeoBoundingBoxQueryBuilderTests#testExceptionOnMissingTypes CI test failure

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#17766]
Original failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=debian/258/console

```
Suite: org.elasticsearch.index.query.GeoBoundingBoxQueryBuilderTests
  2> REPRODUCE WITH: gradle :core:test -Dtests.seed=7236AD4BA5852E8 -Dtests.class=org.elasticsearch.index.query.GeoBoundingBoxQueryBuilderTests -Dtests.method="testExceptionOnMissingTypes" -Des.logger.level=WARN -Dtests.security.manager=true -Dtests.locale=fr-BE -Dtests.timezone=Asia/Hebron
FAILURE 0.10s J0 | GeoBoundingBoxQueryBuilderTests.testExceptionOnMissingTypes <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Found no indexed geo query.
   > 	at __randomizedtesting.SeedInfo.seed([7236AD4BA5852E8:C0398645FCFA1C3D]:0)
   > 	at org.elasticsearch.index.query.GeoBoundingBoxQueryBuilderTests.doAssertLuceneQuery(GeoBoundingBoxQueryBuilderTests.java:284)
   > 	at org.elasticsearch.index.query.GeoBoundingBoxQueryBuilderTests.doAssertLuceneQuery(GeoBoundingBoxQueryBuilderTests.java:47)
   > 	at org.elasticsearch.index.query.AbstractQueryTestCase.assertLuceneQuery(AbstractQueryTestCase.java:622)
   > 	at org.elasticsearch.index.query.AbstractQueryTestCase.testToQuery(AbstractQueryTestCase.java:547)
   > 	at org.elasticsearch.index.query.GeoBoundingBoxQueryBuilderTests.testExceptionOnMissingTypes(GeoBoundingBoxQueryBuilderTests.java:132)
   > 	at java.lang.Thread.run(Thread.java:745)
```

Reproducibles on my machine. Most likely related to #17751.

**Comment by colings86** [comment]
Fixed by https://github.com/elastic/elasticsearch/commit/d863cbaa07d30c4e66f8ffe84b652ae7494d0851

**Comment by colings86** [comment]
Thanks for raising this @imotov 😄
