### ISSUE TITLE
MultiSearch floods ES console with EsRejectedExecutionException stack traces

### ISSUE THREAD

**Issue by rnagappan** [elastic/elasticsearch#17771]
**Elasticsearch version**: 2.2.2 and 2.3.1

**JVM version**: 1.8.0_51 64-bit

**OS version**: Windows 10 64-bit

**Description of the problem including expected versus actual behavior**:

I am trying use the multisearch API to run a large number of independent searches in a batch. I expect all the searches to run on the localhost cluster and to return, as per the API description. Instead I get heaps of EsRejectedExecutionExceptions in my ES console window.

_I would expect that the multisearch API could manage its queue of requests so as to not flood Elasticsearch. The main reason I am trying to use this is to reduce the round-trip latency of each network request-response cycle. For even 1000 queries that adds up to a lot of waiting just for each transport back and forth._

**Steps to reproduce**:

My code (using the Java Transport client) just queries for the counts of documents containing 1000 different terms and returns those terms present in at least 5 docs each:

        List<String> terms = new ArrayList<>(1000);
        Random random = new Random();
        for (int i = 0; i < 1000; i++)
        {
            terms.add(Integer.toString(random.nextInt()));
        }

        MultiSearchRequestBuilder requestBuilder = getEsClient().prepareMultiSearch();
        terms.forEach(term -> {
            SearchRequestBuilder query = getEsClient().prepareSearch()
                                                      .setSize(0)
                                                      .setNoFields()
                                                      .setFetchSource(false)
                                                      .setTypes(ElasticSearchSchema.DOCS_TYPE)
                                                      .setQuery(termQuery(LuceneFields.CONTENT.getName(), term));
            requestBuilder.add(query);
        });

        MultiSearchResponse.Item[] responses = requestBuilder.get()
                                                             .getResponses();

        Set<String> result = new HashSet<>(1000);
        List<Integer> failedResponses = new ArrayList<>();
        for (int i = 0; i < responses.length; i++)
        {
            MultiSearchResponse.Item response = responses[i];
            try
            {
                if (response.getResponse().getHits().getTotalHits() >= 5)
                {
                    result.add(terms.get(i));
                }
            }
            catch (NullPointerException e)
            {
                failedResponses.add(i);
            }
        }
        System.out.println("" + failedResponses.size() + " responses failed: " + Joiner.on(", ").join(failedResponses));

The request returns eventually but the logs are spammed with hundreds of failure messages (see below). Occasionally one of the queries will return a failure response like this that matches the ES cluster console output but the number of failures is tiny compared to the log spam:

    EsRejectedExecutionException[rejected execution of org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction$2@5d935160 on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@25ba6eb[Running, pool size = 37, active threads = 37, queued tasks = 1000, completed tasks = 312998]]] 

After a typical run with hundreds of messages on the log only one query returned a failed result in the end:

    1 responses failed: 847

**Provide logs (if relevant)**:

... but the ES console contains lots of entries like this, even if all the queries eventually succeeded:

    [2016-04-15 11:00:29,114][DEBUG][action.search.type       ] [SYD-NAGAPPR-WS] [nuix-334f4c30941040ee894bde64ef3cc932][4], node[i_7E_ZZ8TYGZ9jXfnhaeig], [P], v[14], s[STARTED], a[id=_7pFXxtcSpir1j5nZAkLmQ]: Failed to execute [org.elasticsearch.action.search.SearchRequest@219198fc] lastShard [true]
    RemoteTransportException[[SYD-NAGAPPR-WS][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: EsRejectedExecutionException[rejected execution of org.elasticsearch.transport.TransportService$4@5b94e2b8 on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@25ba6eb[Running, pool size = 37, active threads = 37, queued tasks = 996, completed tasks = 129578]]];
    Caused by: EsRejectedExecutionException[rejected execution of org.elasticsearch.transport.TransportService$4@5b94e2b8 on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@25ba6eb[Running, pool size = 37, active threads = 37, queued tasks = 996, completed tasks = 129578]]]
        at org.elasticsearch.common.util.concurrent.EsAbortPolicy.rejectedExecution(EsAbortPolicy.java:50)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
        at org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor.execute(EsThreadPoolExecutor.java:85)
        at org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:346)
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:310)
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:282)
        at org.elasticsearch.search.action.SearchServiceTransportAction.sendExecuteQuery(SearchServiceTransportAction.java:142)
        at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction.sendExecuteFirstPhase(TransportSearchQueryThenFetchAction.java:85)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.performFirstPhase(TransportSearchTypeAction.java:166)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.start(TransportSearchTypeAction.java:148)
        at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction.doExecute(TransportSearchQueryThenFetchAction.java:64)
        at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction.doExecute(TransportSearchQueryThenFetchAction.java:53)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:70)
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:99)
        at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:44)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:70)
        at org.elasticsearch.action.search.TransportMultiSearchAction.doExecute(TransportMultiSearchAction.java:63)
        at org.elasticsearch.action.search.TransportMultiSearchAction.doExecute(TransportMultiSearchAction.java:39)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:70)
        at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:45)
        at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:41)
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:244)
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:114)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by clintongormley** [comment]
> Occasionally one of the queries will return a failure response like this that matches the ES cluster console output but the number of failures is tiny compared to the log spam:

Did you check the shard failures in each search request? I bet there are lots of shard failures (which are responsible for the stack traces) and you're getting incomplete results.

**Comment by rnagappan** [comment]
Yes, there are many shard failures for each request, so many matching failure messages like this below. The question remains though, why can't MultiSearch manage its own request queue so it does not flood the cluster like this?

    shard [[UVvK8FU6TmGS6LDnVczdaA][nuix-334f4c30941040ee894bde64ef3cc932][3]], reason [RemoteTransportException[[SYD-NAGAPPR-WS][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: EsRejectedExecutionException[rejected execution of org.elasticsearch.transport.TransportService$4@a81db35 on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@7bb429e0[Running, pool size = 37, active threads = 37, queued tasks = 990, completed tasks = 120883]]]; ], cause [EsRejectedExecutionException[rejected execution of org.elasticsearch.transport.TransportService$4@a81db35 on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@7bb429e0[Running, pool size = 37, active threads = 37, queued tasks = 990, completed tasks = 120883]]]
	at org.elasticsearch.common.util.concurrent.EsAbortPolicy.rejectedExecution(EsAbortPolicy.java:50)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor.execute(EsThreadPoolExecutor.java:85)
	at org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:346)
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:310)
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:282)
	at org.elasticsearch.search.action.SearchServiceTransportAction.sendExecuteQuery(SearchServiceTransportAction.java:142)
	at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction.sendExecuteFirstPhase(TransportSearchQueryThenFetchAction.java:85)
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.performFirstPhase(TransportSearchTypeAction.java:166)
	at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.start(TransportSearchTypeAction.java:148)
	at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction.doExecute(TransportSearchQueryThenFetchAction.java:64)
	at org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction.doExecute(TransportSearchQueryThenFetchAction.java:53)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:70)
	at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:99)
	at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:44)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:70)
	at org.elasticsearch.action.search.TransportMultiSearchAction.doExecute(TransportMultiSearchAction.java:63)
	at org.elasticsearch.action.search.TransportMultiSearchAction.doExecute(TransportMultiSearchAction.java:39)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:70)
	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:45)
	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:41)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:244)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:114)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by martijnvg** [comment]
Closing this issue in favour of #17926. 

@rnagappan There is room for improvement for the multi search api. Unfortunately today there isn't much that can be done to avoid rejected exceptions in your case other then lowering the amount of search requests in the multi search api or adding more nodes to your cluster.
