### ISSUE TITLE
_cat/plugins throws NullPointerException on Tribe node

### ISSUE THREAD

**Issue by HonzaKral** [elastic/elasticsearch#17772]
**Elasticsearch version**: 2.3.1

**JVM version**: 1.8.0_31-b13

**OS version**: CentOS 7

**Description of the problem including expected versus actual behavior**:
We have `license` and `marvel` plugins installed (version 2.3.1) - we can see the plugins fine, the cat api works. Once the tribe connects to a cluster containing just a `kopf` plugin it starts throwing NPE. `_nodes` still contains correct info about the plugins and when we do `_cat/plugins` on the cluster the tribes connect to we see its plugins ans well as the plugins on the tribe node.

**Provide logs (if relevant)**:

```
[2016-04-15 01:23:02,525][WARN ][rest.suppressed          ] /_cat/plugins Params: {}
java.lang.NullPointerException
        at org.elasticsearch.rest.action.cat.RestPluginsAction.buildTable(RestPluginsAction.java:98)
        at org.elasticsearch.rest.action.cat.RestPluginsAction.access$000(RestPluginsAction.java:41)
        at org.elasticsearch.rest.action.cat.RestPluginsAction$1$1.buildResponse(RestPluginsAction.java:69)
        at org.elasticsearch.rest.action.cat.RestPluginsAction$1$1.buildResponse(RestPluginsAction.java:66)
        at org.elasticsearch.rest.action.support.RestResponseListener.processResponse(RestResponseListener.java:43)
        at org.elasticsearch.rest.action.support.RestActionListener.onResponse(RestActionListener.java:49)
        at org.elasticsearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:89)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by javanna** [comment]
Not sure if this problem still persists, but tribe node has been deprecated and removed, hence I am closing this issue.
