### ISSUE TITLE
Java.lang.NullPointerException: Cannot get property ‘x’ on null object - when running a groovy script

### ISSUE THREAD

**Issue by tpraizler** [elastic/elasticsearch#17845]
**Elasticsearch version**: 2.0.0

**JVM version**: Not sure - running on elastic cloud

**OS version**: Not sure - running on elastic cloud

**Description of the problem including expected versus actual behavior**:
My use case is trying to update a document simultaneously with 2  of the options of the update api, sometimes update fails and sometimes it is successful.
 
I use a Transport client using elastic4s as my client.

so my document looks like this:

```
{ 
   "field": {
      "names": ["A","B","C"],
      "A": { "name": "A is awesome" },
      "B": { "name": "B is awesome" },
      "C": { "name": "C is awesome" }
   },
   "email": "x@gmail.com"
}
```

I am trying to update the names field with one request using inline script, and add another field under "field" with another request using the doc api. Those 2 requests are running simultaneously.

So here is my code:

```
  override def addTerms(String, terms: Set[String]) = {
    val groovyScript =
      s"""if (ctx._source.field.names== null)
          |   ctx._source.field.names=newItems
          |else
          |   ctx._source.field.names<< newItems;
          |ctx._source.field.names= ctx._source.field.names.flatten().unique();""".stripMargin
    client.execute(ElasticDsl.update id id in indexName / documentType retryOnConflict 5 script {
      script(groovyScript).params(Map("newItems" -> terms.toArray))
    })
  }   

  override def update(id: String, field: NestedFieldValue) = {
    client.execute {
      ElasticDsl.update(id) in indexName / documentType retryOnConflict 5 doc field
    }
  }
```

Executing the above method in parallel fails, but when I run it sequentially it works.
This works: 

`update(id, field).flatMap(_ => addTerms(id, path, terms))`

**Steps to reproduce**:
 1. Running the above methods in parallel fails with a NullPointerException coming from groovy engine.
So here is a piece of code:

```
for{
 _ <- update(id, field)
 _ <- addTerms(id, path, terms)
}yield{}

```

**Provide logs (if relevant)**:
```

Caused by: java.lang.IllegalArgumentException: failed to execute script 
   at org.elasticsearch.action.update.UpdateHelper.executeScript(UpdateHelper.java:256) ~[org.elasticsearch.elasticsearch-2.0.1.jar:2.0.1] 
   at org.elasticsearch.action.update.UpdateHelper.prepare(UpdateHelper.java:196) ~[org.elasticsearch.elasticsearch-2.0.1.jar:2.0.1] 
   at org.elasticsearch.action.update.UpdateHelper.prepare(UpdateHelper.java:79) ~[org.elasticsearch.elasticsearch-2.0.1.jar:2.0.1] 
   at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:170) ~[org.elasticsearch.elasticsearch-2.0
   at org.elasticsearch.action.update.TransportUpdateAction$3$1.doRun(TransportUpdateAction.java:227) ~[org.elasticsearch.elasticsearch-2.0.1.
   at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[org.elasticsearch.elasticsearch-2.0.1.jar:2.0.1]
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_74-cedar14] 
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_74-cedar14] 
   at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_74-cedar14] 
 Caused by: org.elasticsearch.script.groovy.GroovyScriptExecutionException: failed to run inline script [if (ctx._source.field.names == null) 
     ctx._source.field.names=newItems 
  else 
     ctx._source.field.names<< newItems; 
     ctx._source.field.names = ctx._source.field.names.flatten().unique()] using lang [groovy] 
    at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript.run(GroovyScriptEngineService.java:253) ~[org.elasticsearch.
    at org.elasticsearch.action.update.UpdateHelper.executeScript(UpdateHelper.java:251) ~[org.elasticsearch.elasticsearch-2.0.1.jar:2.0.1] 
    ... 8 common frames omitted 
  Caused by: java.lang.NullPointerException: Cannot get property 'names' on null object 
    at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60) ~[org.codehaus.groovy.groovy-all-2.4.0.jar:2.4.0] 
    at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:172) ~[org.codehaus.groovy.groovy-all-2.4.0.jar:2.4.0] 
    at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:47) ~[org.codehaus.groovy.groovy-all-2.4.0.jar:2.4.0] 
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296) ~[org.codehaus.groovy.groovy-all-2.4.0.
    at 889babff0826c95e16279a9fb1fd2eb97a63e642.run(889babff0826c95e16279a9fb1fd2eb97a63e642:1) ~[na:na] 
    at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript.run(GroovyScriptEngineService.java:248) ~[org.elasticsearch.
```

**Comment by clintongormley** [comment]
From the error message, it looks like your `field` is missing some times, hence the NPE.  I'm unable to replicate this.  I tried running these two requests in parallel:

    POST /t/t/1/_update?pretty=1&retry_on_conflict=5
    {
       "script" : "if (ctx._source.field.names== null) {ctx._source.field.names=newItems} else {ctx._source.field.names<< newItems}; ctx._source.field.names= ctx._source.field.names.flatten().unique();",
       "params" : {
          "newItems" : [
             "foo",
             "bar"
          ]
       }
    }

and

    POST /t/t/1/_update?pretty=1&retry_on_conflict=5
    {
      "retry_on_conflict": 5,
      "doc": {
        "field": {
          "foo": {
            "name": "foo is awesome"
          }
        }
      }
    }

and I reset the doc every now and again with 

    POST t/t/1
    { 
       "field": {
          "names": ["A","B","C"],
          "A": { "name": "A is awesome" },
          "B": { "name": "B is awesome" },
          "C": { "name": "C is awesome" }
       },
       "email": "x@gmail.com"
    }

No joy.  I think you have some code somewhere which is updating this doc with a source that doesn't include `field`.  A runnable recreation would be appreciated (and in something other than Scala :) )

**Comment by tpraizler** [comment]
Thanks @clintongormley for looking into this! 
Did you run it on one documents? I run around 80 simultaneously requests to ES, 2 for every one of the 40 documents. This behavior is pretty random, it fails almost every execution of those 80 futures, but on different document every time.
Does this information help in some way? Are you able to create such scenario?

**Comment by clintongormley** [comment]
@tpraizler your original description lacks some steps.  could you provide an exact recreation (something easy to run without installing lots of libraries) to try it out?

**Comment by clintongormley** [comment]
No further feedback.  Closing
