### ISSUE TITLE
assertion error: assertNotTransportThread while testing rest handler using ESIntegTestCase

### ISSUE THREAD

**Issue by bandika-dgit** [elastic/elasticsearch#17865]
**Elasticsearch version**: 2.2.0

**JVM version**: 1.7.0_79

**OS version**: OS X 10.8.5

**Description of the problem including expected versus actual behavior**:
Testing rest handler which called client api prepareUpdate returned assertionError:
`java.lang.AssertionError: Expected current thread [Thread[elasticsearch[node_s0][http_server_worker][T#1]{New I/O worker #28},5,TGRP-GetReportFileRestHandlerTest]] to not be a transport thread. Reason: [Blocking operation]`

Expected not to throw assertion error

**Steps to reproduce**:
 1. Create rest handler which called search API
 2. Invoke rest handler within ESIntegTestCase

**Provide logs (if relevant)**:
[2016-04-20 01:58:22,213][INFO ][rest.suppressed          ] /interactions/order/_report/not_exists Params: {id=not_exists, index=interactions, type=order}
java.lang.AssertionError: Expected current thread [Thread[elasticsearch[node_s0][http_server_worker][T#1]{New I/O worker #28},5,TGRP-GetReportFileRestHandlerTest]] to not be a transport thread. Reason: [Blocking operation]
	at org.elasticsearch.transport.Transports.assertNotTransportThread(Transports.java:62)
	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:115)
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:42)
	at test.SimpleReportExecutionRepository.getDocument(SimpleReportExecutionRepository.java:164)
	at test.SimpleReportExecutionRepository.get(SimpleReportExecutionRepository.java:92)
	at test.ReportExecutionMonitor.get(ReportExecutionMonitor.java:149)
	at test.GetReportFileRestHandler.handleRequest(GetReportFileRestHandler.java:81)
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:54)
	at org.elasticsearch.rest.RestController.executeHandler(RestController.java:207)
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:166)
	at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:128)
	at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:86)
	at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:363)
	at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:63)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Describe the feature**:

**Comment by jasontedor** [comment]
It's not a bug, you're doing something you shouldn't be doing: executing a blocking operation on a networking thread. That is exactly what this assertion is protecting against.

**Comment by bandika-dgit** [comment]
Hi, thanks for quick response.
I've test on elasticsearch instance also, but the rest handler not throwing any assertion error.

**Comment by jasontedor** [comment]
Assertions aren't enabled when you run Elasticsearch by default. You can enable them by launching the JVM with `-ea` (pass this via `ES_JAVA_OPTS`). :smile:
