### ISSUE TITLE
Missing input data for one minute.maybe about the template mapping

### ISSUE THREAD

**Issue by yuz11** [elastic/elasticsearch#17883]
Elasticsearch version: 2.1.1

JVM version: 1.8.0_40

OS version: ubuntu 12.04

Description of the problem including expected versus actual behavior:
I create a template mapping some logs.the input is in the same format and well run for a while(months).
However I find that today(2016.4.20) 14:00:00 to 14:00:01, I am missing data of this minute.I have the statistic of writing to ElasticSearch and the statistic tells data has been send successfully to Es Server.
Then I find out the logs below.
If u need any other clues.please contact me.

the template is set by 

    PUT /_template/t1
    {
      "template": "*",
      "settings": {
        "index.refresh_interval": "30s",
        "index.routing.allocation.require.box_type": "hot",
        "number_of_shards": "52"
      },
      "mappings": {
        "log": {
          "properties": {
            "timestamp": {
              "type": "date",
              "format": "epoch_second"
            },
            "service": {
              "type": "string",
              "index": "not_analyzed",
              "doc_values": false
            },
            "id": {
              "type": "string",
              "index": "not_analyzed",
              "doc_values": false
            },
            "ip": {
              "type": "string",
              "index": "not_analyzed"
            },
            "function": {
              "type": "string",
              "index": "not_analyzed"
            },
            "logtype": {
              "type": "string",
              "index": "not_analyzed",
              "doc_values": false
            }
          }
        }
      }
    }

Provide logs (if relevant):

    [2016-04-20 14:00:36,552][DEBUG][action.admin.indices.mapping.put] [Gregory Gideon] failed to put mappings on indices [[bt_svc_ap_2016042014]], type [log]
    ProcessClusterEventTimeoutException[failed to process cluster event (put-mapping [log]) within 30s]
            at org.elasticsearch.cluster.service.InternalClusterService$2$1.run(InternalClusterService.java:290)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)
    [2016-04-20 14:00:36,552][DEBUG][action.admin.indices.mapping.put] [Gregory Gideon] failed to put mappings on indices [[bt_svc_ap_2016042014]], type [log]
    ProcessClusterEventTimeoutException[failed to process cluster event (put-mapping [log]) within 30s]
            at org.elasticsearch.cluster.service.InternalClusterService$2$1.run(InternalClusterService.java:290)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)

**Comment by clintongormley** [comment]
Hi @yuz11 

It looks like nodes in your cluster were unresponsive so the mapping update failed.  I'd investigate what was happening to your nodes during that time.
