### ISSUE TITLE
Elasticsearch parsing the source for a disabled object when using Transform

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#17953]
**Elasticsearch version**: `2.3.1`

**JVM version**: `Java(TM) SE Runtime Environment (build 1.8.0_45-b14)`

**OS version**: Any OS

**Description of the problem including expected versus actual behavior**:

Using a simple script, called `fake.groovy` which is just a `return true` script, you can verify that the content of object fields that are not enabled are being parsed anyway. Looking at the [source](https://github.com/elastic/elasticsearch/blob/2.3/core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java#L748) it looks like the `mapOrdered` method is actually using the `JsonXContentParser` with all the fields no matter if they are enabled or not. We shouldn't parse the source and we should have the same behaviour than when not using `transform` method.

If you don't use transform, the mapper will avoid parsing the content and this will work as expected.

**Steps to reproduce**:
 1. Create a `fake.groovy` script and place it in `/config/scripts`
 2. Create an index using the transform [1]
 3. Index a document with a field that should fail if the source is parsed (example `BIG_INTEGER`) [2]
 4. The result of this is an error, because is trying to parse the source, we should use the source, not parse it when the object is not enabled.

[1] 

```
DELETE test

PUT test/
{
  "mappings": {
    "entry": {
      "transform": {
        "file": "fake",
        "lang": "groovy"
      },
      "properties": {
        "ssl": {
          "type": "object",
          "enabled": false
        }
      }
    }
  }
}
```

[2]

```
POST test/entry
{
  "ssl": {
    "cert": {
      "serial": 13408895465235657000
    }
  }
}
```

**Provide logs (if relevant)**:

```
[2016-04-25 08:53:39,233][DEBUG][action.index             ] [Hurricane] failed to execute [index {][entry][AVRNRI6cWqa-34uUr91K], source[{
  "ssl": {
    "cert": {\
      "serial": 13408895465235657000,\\
    }
  }
}
]}] on [-][4]]
MapperParsingException[failed to parse]; nested: IllegalStateException[No matching token for number_type [BIG_INTEGER]];
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:154)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309)
	at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:529)
	at org.elasticsearch.index.shard.IndexShard.prepareCreateOnPrimary(IndexShard.java:506)
	at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:215)
	at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:224)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:158)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:66)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:639)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:271)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: No matching token for number_type [BIG_INTEGER]
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.convertNumberType(JsonXContentParser.java:216)
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.numberType(JsonXContentParser.java:68)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:301)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:274)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:314)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:274)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:314)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:274)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readOrderedMap(AbstractXContentParser.java:249)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.mapOrdered(AbstractXContentParser.java:213)
	at org.elasticsearch.index.mapper.DocumentParser.transform(DocumentParser.java:748)
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:93)
	... 17 more

```

**Comment by clintongormley** [comment]
The source transform feature was never documented to ignore disabled object fields. On top of that, it was deprecated in 2.0 and removed in 5.0, so we won't be making any changes to it now

**Comment by gmoskovicz** [comment]
Thanks for the update @clintongormley
