### ISSUE TITLE
elasticsearch.yml example is outdated

### ISSUE THREAD

**Issue by naisanza** [elastic/elasticsearch#17974]
**Elasticsearch version**:
Version: 5.0.0-alpha1, Build: 7d4ed5b/2016-04-04T10:39:25.841Z, JVM: 1.8.0_91

**JVM version**:
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**OS version**:
Linux elasticsearch 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
$ELASTICSEARCH_HOME/config/elasticsearch.yml needs to be updated to spec.

It shows that the format for `network.host` is `network.host: 192.168.1.19` but that does not work. The proper format is `network.host: ["192.168.1.19"]`

```
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
# network.host: 192.168.1.19
#
# Set a custom port for HTTP:
#
# http.port: 9200
```

**Steps to reproduce**:
 1. Set `elasticsearch.yml` to `network.host: 192.168.1.19`
 2. Start `elasticsearch`
 3. Java error occurs

**Provide logs (if relevant)**:

/opt/elasticsearch/elasticsearch-5.0.0-alpha1/logs/elasticsearch.log
```
java.lang.RuntimeException: max file descriptors [4096] for elasticsearch process likely too low, increase to at least [65536]
        at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:79)
        at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:60)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:187)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:263)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:111)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:106)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
        at org.elasticsearch.cli.Command.main(Command.java:53)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)
```

**Describe the feature**:
Make sure config files, example configs, and documentation all match up. Otherwise this was a 23 minute headache that should have been avoided.

**Comment by naisanza** [comment]
https://github.com/elastic/elasticsearch/issues/15340 gave me the idea to use a quoteed array/list, which is how I got it to work

**Comment by jasontedor** [comment]
I'm sorry that you experienced pain here. However, you do not have to set `network.host` to an array, setting it as a single value is accepted. Note the error message that you're getting is about a failing bootstrap check. These are checks that are being added in Elasticsearch 5.0.0 to increase the resiliency of production configurations of Elasticsearch. A production configuration is an instance of Elasticsearch that binds to or publishes to a non-loopback network interface. Since the non-array `network.host` setting was correctly applied, the bootstrap checks are executed and that's why you're seeing the error message:

```
java.lang.RuntimeException: max file descriptors [4096] for elasticsearch process likely too low, increase to at least [65536]
```

It's telling you exactly what the problem is: you need to increase the number of available file descriptors to 65536.

Can you explain what led you to believe that the problem was not having the `network.host` setting set as an array? On my system I can do the following:

```
$ cat ./config/elasticsearch.yml | grep network.host
network.host: ["192.168.1.105", "127.0.0.1"]
$ ./bin/elasticsearch | grep bound_addresses
[2016-04-26 06:14:33,592][INFO ][transport                ] [Bloodhawk] publish_address {192.168.1.105:9300}, bound_addresses {192.168.1.105:9300}, {127.0.0.1:9300}
[2016-04-26 06:14:36,679][INFO ][http                     ] [Bloodhawk] publish_address {192.168.1.105:9200}, bound_addresses {192.168.1.105:9200}, {127.0.0.1:9200}
^C
```

```
$ cat ./config/elasticsearch.yml | grep network.host
network.host: 192.168.1.105
$ ./bin/elasticsearch | grep bound_addresses
[2016-04-26 06:15:32,977][INFO ][transport                ] [Senator Robert Kelly] publish_address {192.168.1.105:9300}, bound_addresses {192.168.1.105:9300}
[2016-04-26 06:15:36,028][INFO ][http                     ] [Senator Robert Kelly] publish_address {192.168.1.105:9200}, bound_addresses {192.168.1.105:9200}
^C
```

and in either case Elasticsearch starts up just fine.

**Comment by naisanza** [comment]
Hi! Even with `max file descriptors` aside elasticsearch won't start after that java error.

For example:

`network.host: _site_`:

```
root@elasticsearch_running:~# netstat -ant
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
```

`network.host: "_site_"`:

```
root@elasticsearch_running:~# netstat -ant
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
```


`network.host: ["_site_"]`:

```
root@elasticsearch_running:~# netstat -ant
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp6       0      0 10.0.3.85:9200          :::*                    LISTEN
tcp6       0      0 10.0.3.85:9300          :::*                    LISTEN
```

`network.bind_host: 10.0.3.85`:

```
root@elasticsearch_running:~# netstat -ant
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
```

`network.bind_host: ["10.0.3.85"]`:

```
root@elasticsearch_running:~# netstat -ant
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp6       0      0 10.0.3.85:9200          :::*                    LISTEN
tcp6       0      0 10.0.3.85:9300          :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
```

**Comment by jasontedor** [comment]
> Hi! Even with max file descriptors aside elasticsearch won't start after that java error.

Can you please share the log messages from Elasticsearch failing to start?

**Comment by naisanza** [comment]
@jasontedor sure! I've attached all the logs from `$ES_HOME/logs/`

Only elasticsearch.log contained anything:

```
[2016-04-26 19:22:26,605][ERROR][bootstrap                ] Exception
java.lang.RuntimeException: max file descriptors [4096] for elasticsearch process likely too low, increase to at least [65536]
	at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:79)
	at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:60)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:187)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:263)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:111)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:106)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
	at org.elasticsearch.cli.Command.main(Command.java:53)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)
```

```
root@elasticsearch_running:~# du -sh /opt/elasticsearch/elasticsearch-5.0.0-alpha1/logs/*
0       /opt/elasticsearch/elasticsearch-5.0.0-alpha1/logs/elasticsearch_deprecation.log
0       /opt/elasticsearch/elasticsearch-5.0.0-alpha1/logs/elasticsearch_index_indexing_slowlog.log
0       /opt/elasticsearch/elasticsearch-5.0.0-alpha1/logs/elasticsearch_index_search_slowlog.log
4.0K    /opt/elasticsearch/elasticsearch-5.0.0-alpha1/logs/elasticsearch.log
```

Attached log files:
[elasticsearch.zip](https://github.com/elastic/elasticsearch/files/237303/elasticsearch.zip)

**Comment by jasontedor** [comment]
@naisanza Sorry, I don't understand what those logs are showing me since you didn't share the configuration nor the command-line parameters used to start Elasticsearch. Would it be possible for you to show from the command-line and configuration that is giving you trouble and the log messages that Elasticsearch displays on the console when it fails to start?

**Comment by naisanza** [comment]
@jasontedor sorry about that. A very minimal setup


rc.local:

```
root@elasticsearch_running:~# cat /etc/rc.local
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

su - eric -c "elasticsearch & disown %"

exit 0
```

elasticsearch.yml:

```
root@elasticsearch_running:~# grep -v "^#" /opt/elasticsearch/elasticsearch-5.0.0-alpha1/config/elasticsearch.yml
network.host: _site_
```

from the shell:

```
eric@elasticsearch_running:~$ elasticsearch
Exception in thread "main" java.lang.RuntimeException: max file descriptors [4096] for elasticsearch process likely too low, increase to at least [65536]
        at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:79)
        at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:60)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:187)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:263)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:111)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:106)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
        at org.elasticsearch.cli.Command.main(Command.java:53)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)
Refer to the log for complete error details.
```

**Comment by jasontedor** [comment]
But `network.host: _site_` means that you're binding to a non-loopback interface and that subjects the instance to the bootstrap checks that we discussed [previously](https://github.com/elastic/elasticsearch/issues/17974#issuecomment-214693883). The error message tells you that you're still running into the file descriptor issue. This has nothing to do with `network.host` being an array versus not being an array.

**Comment by naisanza** [comment]
@jasontedor 

elasticsearch.yml
```
eric@elasticsearch_running:~$ grep -v "^#" /opt/elasticsearch/elasticsearch-5.0.0-alpha1/config/elasticsearch.yml
network.host: ["_site_"]
```

elasticsearch starts:

```
eric@elasticsearch_running:~$ elasticsearch
[2016-04-26 19:55:25,643][WARN ][bootstrap                ] max file descriptors [4096] for elasticsearch process likely too low, increase to at least [65536]
[2016-04-26 19:55:25,644][WARN ][bootstrap                ] please set [discovery.zen.minimum_master_nodes] to a majority of the number of master eligible nodes in your cluster.
[2016-04-26 19:55:25,668][INFO ][node                     ] [Trevor Fitzroy] version[5.0.0-alpha1], pid[693], build[7d4ed5b/2016-04-04T10:39:25.841Z]
[2016-04-26 19:55:25,669][INFO ][node                     ] [Trevor Fitzroy] initializing ...
[2016-04-26 19:55:26,294][INFO ][plugins                  ] [Trevor Fitzroy] modules [lang-mustache, lang-painless, ingest-grok, reindex, lang-expression, lang-groovy], plugins []
[2016-04-26 19:55:26,334][INFO ][env                      ] [Trevor Fitzroy] using [1] data paths, mounts [[/ (/home/eric/.local/share/lxc/base-ubuntu/rootfs)]], net usable_space [57.4gb], net total_space [78.6gb], spins? [possibly], types [overlayfs]
[2016-04-26 19:55:26,335][INFO ][env                      ] [Trevor Fitzroy] heap size [990.7mb], compressed ordinary object pointers [true]
[2016-04-26 19:55:29,636][INFO ][node                     ] [Trevor Fitzroy] initialized
[2016-04-26 19:55:29,637][INFO ][node                     ] [Trevor Fitzroy] starting ...
[2016-04-26 19:55:29,765][INFO ][transport                ] [Trevor Fitzroy] publish_address {10.0.3.85:9300}, bound_addresses {10.0.3.85:9300}
[2016-04-26 19:55:32,879][INFO ][cluster.service          ] [Trevor Fitzroy] new_master {Trevor Fitzroy}{MprWNSUcQB2GhSTwXp1h7A}{10.0.3.85}{10.0.3.85:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2016-04-26 19:55:32,994][INFO ][http                     ] [Trevor Fitzroy] publish_address {10.0.3.85:9200}, bound_addresses {10.0.3.85:9200}
[2016-04-26 19:55:32,995][INFO ][node                     ] [Trevor Fitzroy] started
[2016-04-26 19:55:33,033][INFO ][gateway                  ] [Trevor Fitzroy] recovered [0] indices into cluster_state
```

**Comment by jasontedor** [comment]
Okay, thank you for that! I attempted to reproduce this on master and I was not able to. That put me down the path of thinking about what has changed in the bootstrap checks between alpha1 and master. A key change is how these bootstrap checks detect whether or not you're bound to a non-loopback interface. In particular, in alpha1 we merely checked to see if the `network.host` setting is set or not. When you set `network.host: _site_` then that setting is clearly set. However, when you set `network.host: ["_site_"]` that doesn't actually set `network.host`. Instead, it sets `network.host.0`, `network.host.1`, ..., `network.host.n` up to `n`, the number of the elements in the array minus one. In alpha1 we were not checking for any `network.host.k` settings, just `network.host`. This is why you're encountering this issue. In master since #17595 we do this very differently. Instead, we bind to the configured network interfaces and then check whether or not any of those bindings are to non-loopback interfaces. This indirectly eliminated this painful issue.

I'm *truly* sorry that you ran into this pain and appreciate your repeated feedback as we worked through this one.

**Comment by jasontedor** [comment]
@naisanza I've marked you as being eligible for the [pioneer program](https://www.elastic.co/blog/elastic-pioneer-program). Thanks again for the report!

**Comment by naisanza** [comment]
@jasontedor no problem! Pioneer Program sounds awesome

**Comment by alexanderkjeldaas** [comment]
This exception happens on the official docker hub elasticsearch:5 image.

**Comment by jasontedor** [comment]
There is not an official Docker image that is affiliated with Elastic. To be clear, the "official" Docker image on Docker Hub is not affiliated with Elastic.
