### ISSUE TITLE
Securemock which is included in Elasticsearch 5.0.0-alpha1 test-framework contains classes from org.objenesis and thus causes jar-hell

### ISSUE THREAD

**Issue by centic9** [elastic/elasticsearch#18063]
**Elasticsearch version**:5.0.0-alpha1

**JVM version**:1.8.0_66

**OS version**:Windows 8.1

**Description of the problem including expected versus actual behavior**: 

I use the Elasticsearch Test-Framework for testing some of my code which uses the Elasticsearch Java Client. It works fine with 2.3.2, when I try this with 5.0.0-alpha1, I get jar-hell errors as follows:

```
java.lang.RuntimeException: found jar hell in test classpath
	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:89)
	at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:117)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:585)
Caused by: java.lang.IllegalStateException: jar hell!
class: org.objenesis.instantiator.android.Android10Instantiator
jar1: C:\Users\.gradle\caches\modules-2\files-2.1\org.objenesis\objenesis\2.1\87c0ea803b69252868d09308b4618f766f135a96\objenesis-2.1.jar
jar2: C:\Users\.gradle\caches\modules-2\files-2.1\org.elasticsearch\securemock\1.2\98201d4ad5ac93f6b415ae9172d52b5e7cda490e\securemock-1.2.jar
	at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:282)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:186)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:87)
	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:87)
	... 4 more
```

It seems the new securemock package of Elasticsearch contains classes from org.objenesis and thus leads to jarhell failures, e.g. when using easymock, which pulls in the official org.objenesis package.

**Steps to reproduce**:
 1. Create a project using ESIntegrationTest
 2. Use both easymock and the following Gradle dependencies

    testCompile 'org.elasticsearch:elasticsearch:5.0.0-alpha1'
    testCompile 'org.elasticsearch.test:framework:5.0.0-alpha1'
    testCompile 'org.easymock:easymock:3.3.1'

 3. Try to run the unit-test

**Comment by rjernst** [comment]
> Use both easymock and the following Gradle dependencies

This combination is not supported, since mockito is itself of easymock, I believe, and using the ES test framework requires using securemock instead of mockito. Securemock is a simple copy of mockito with important calls to the jdk wrapped with doPrivileged blocks that work correctly with security manager.
