### ISSUE TITLE
ScalingThreadPoolTests.testScalingThreadPoolThreadsAreTerminatedAfterKeepAlive CI Failure

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#18072]
Seems to be semi-consistently failing:

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=opensuse/345/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=oraclelinux/343/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=opensuse/341/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/615/console

However, I was unable to reproduce any of these failures on either of my two machines. :(

```
gradle :core:test -Dtests.seed=A1BF5ED4DA80E472 -Dtests.class=org.elasticsearch.threadpool.ScalingThreadPoolTests -Dtests.method="testScalingThreadPoolThreadsAreTerminatedAfterKeepAlive" -Des.logger.level=WARN -Dtests.security.manager=true -Dtests.locale=ar-LB -Dtests.timezone=Asia/Anadyr

FAILURE 0.14s J1 | ScalingThreadPoolTests.testScalingThreadPoolThreadsAreTerminatedAfterKeepAlive <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <128L>
   >      but: was <127L>
   > 	at __randomizedtesting.SeedInfo.seed([A1BF5ED4DA80E472:BC4ACB642517FFFA]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.threadpool.ScalingThreadPoolTests.lambda$testScalingThreadPoolThreadsAreTerminatedAfterKeepAlive$7(ScalingThreadPoolTests.java:196)
   > 	at org.elasticsearch.threadpool.ScalingThreadPoolTests.runScalingThreadPoolTest(ScalingThreadPoolTests.java:244)
   > 	at org.elasticsearch.threadpool.ScalingThreadPoolTests.testScalingThreadPoolThreadsAreTerminatedAfterKeepAlive(ScalingThreadPoolTests.java:167)
   > 	at java.lang.Thread.run(Thread.java:745)
  1> [2016-04-29 19:31:31,374][WARN ][org.elasticsearch.common.settings] [testResizingScalingThreadPoolQueue] failed to apply settings
  1> java.lang.IllegalArgumentException: thread pool [warmer] of type scaling can not have its queue re-sized but was [518323132]
  1> 	at org.elasticsearch.threadpool.ThreadPool.rebuild(ThreadPool.java:528)
  1> 	at org.elasticsearch.threadpool.ThreadPool.updateSettings(ThreadPool.java:628)
  1> 	at org.elasticsearch.common.settings.Setting$3$1.apply(Setting.java:727)
  1> 	at org.elasticsearch.common.settings.Setting$3$1.apply(Setting.java:702)
  1> 	at org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater.lambda$updater$0(AbstractScopedSettings.java:319)
  1> 	at org.elasticsearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:165)
  1> 	at org.elasticsearch.threadpool.ScalingThreadPoolTests.lambda$null$9(ScalingThreadPoolTests.java:226)
  1> 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2677)
  1> 	at org.elasticsearch.threadpool.ScalingThreadPoolTests.lambda$testResizingScalingThreadPoolQueue$10(ScalingThreadPoolTests.java:224)
  1> 	at org.elasticsearch.threadpool.ScalingThreadPoolTests.runScalingThreadPoolTest(ScalingThreadPoolTests.java:244)
  1> 	at org.elasticsearch.threadpool.ScalingThreadPoolTests.testResizingScalingThreadPoolQueue(ScalingThreadPoolTests.java:222)
  1> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  1> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  1> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  1> 	at java.lang.reflect.Method.invoke(Method.java:498)
  1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1764)
  1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:871)
  1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:907)
  1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:921)
  1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  1> 	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  1> 	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  1> 	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  1> 	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  1> 	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  1> 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
  1> 	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:809)
  1> 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:460)
  1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:880)
  1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:781)
  1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:816)
  1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:827)
  1> 	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  1> 	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  1> 	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  1> 	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  1> 	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  1> 	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  1> 	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  1> 	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  1> 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
  1> 	at java.lang.Thread.run(Thread.java:745)
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-os-compatibility/os/opensuse/core/build/testrun/test/J1/temp/org.elasticsearch.threadpool.ScalingThreadPoolTests_A1BF5ED4DA80E472-001
  2> NOTE: test params are: codec=Asserting(Lucene60): {}, docValues:{}, maxPointsInLeafNode=1221, maxMBSortInHeap=6.699272557998749, sim=RandomSimilarity(queryNorm=false,coord=yes): {}, locale=ar-LB, timezone=Asia/Anadyr
  2> NOTE: Linux 3.16.7-29-default amd64/Oracle Corporation 1.8.0_72 (64-bit)/cpus=4,threads=1,free=431645528,total=517996544
  2> NOTE: All tests run in this JVM: [JoinProcessorTests, URIPatternTests, PrimaryElectionRoutingTests, BootstrapSettingsTests, RecoveryStatusTests, ExceptionSerializationTests, DateFormatTests, AwarenessAllocationTests, LegacyLongFieldTypeTests, PipelineExecutionServiceTests, NodeVersionAllocationDeciderTests, FsBlobStoreContainerTests, ParentFieldTypeTests, TransportAnalyzeActionTests, SimpleMapperTests, EnvironmentTests, RebalanceAfterActiveTests, FailProcessorTests, TermVectorsUnitTests, SimulateProcessorResultTests, PercentilesTests, LockedRecyclerTests, MaxMapCountCheckTests, QueryPhaseTests, ByteUtilsTests, DiskThresholdDeciderTests, LongNestedSortingTests, ShardRoutingTests, ClusterChangedEventTests, YamlFilteringGeneratorTests, GeoQueryContextTests, BlockingClusterStatePublishResponseHandlerTests, GeoDistanceQueryBuilderTests, IndicesStatsTests, CompoundProcessorTests, HistogramTests, CamelCaseFieldNameTests, FieldDataCacheTests, LaplaceModelTests, FileInfoTests, SpanNearQueryBuilderTests, FuzzinessTests, CardinalityTests, MinTests, ScoreSortBuilderTests, MatchPhrasePrefixQueryBuilderTests, QueryShardContextTests, IndicesRequestCacheTests, Murmur3HashFunctionTests, EnvelopeBuilderTests, RenameProcessorTests, NodeClientHeadersTests, SearchSlowLogTests, WildcardExpressionResolverTests, ReverseNestedTests, KeepFilterFactoryTests, IndexSearcherWrapperTests, GeoUtilsTests, ScriptContextRegistryTests, ScalingThreadPoolTests]
```

```
BUILD INFO

Build	20160429192716-1B1E4023
Log	https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=opensuse/345/console
Duration	5m 41s (341210ms)
Started	2016-04-29T19:27:16.547Z
Ended	2016-04-29T19:32:57.757Z
Exit Code	1
Host	slave-f1f8d528 (up 116 days)
OS	OpenSuSE 13.2, Linux 3.16.7-29-default
Specs	4 CPUs, 15.45GB RAM
java.version	1.8.0_72
java.vm.name	OpenJDK 64-Bit Server VM
java.vm.version	25.72-b15
java.runtime.version	1.8.0_72-b15
java.home	/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0
```

**Comment by jasontedor** [comment]
It's due to a race between the main test thread and last few thread pool threads that are executing tasks during the test.
