### ISSUE TITLE
NPE when calling non existing ingest pipeline

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#18139]
**Elasticsearch version**: 5.0.0-alpha2
**Description of the problem including expected versus actual behavior**: NPE is thrown when calling non existing ingest pipeline. I would expect a better message like "Pipeline [{}] does not exist".

**Steps to reproduce**:

```sh
curl -XDELETE "localhost:9200/_ingest/pipeline/doesnotexist?pretty"
curl -XPOST "localhost:9200/_ingest/pipeline/doesnotexist/_simulate?pretty" -d '{
	"docs": [ {
		"_index": "index",
		"_type": "type",
		"_id": "id",
		"_source": {
			"foo" : "baz"
		}
	}	]
}'
``` 

Gives back:

```json
  "error" : {
    "root_cause" : [ {
      "type" : "null_pointer_exception",
      "reason" : null
    } ],
    "type" : "null_pointer_exception",
    "reason" : null
  },
  "status" : 500
}
```

**Provide logs (if relevant)**:

```
[2016-05-04 16:55:54,814][WARN ][rest.suppressed          ] /_ingest/pipeline/doesnotexist/_simulate Params: {pretty=, id=doesnotexist}
java.lang.NullPointerException
	at org.elasticsearch.action.ingest.SimulateExecutionService$1.doRun(SimulateExecutionService.java:72)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:452)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by clintongormley** [comment]
@talevy could you take a look please?

**Comment by talevy** [comment]
yup!

**Comment by talevy** [comment]
this should make for a nicer exception ^^
