### ISSUE TITLE
[CI] org.elasticsearch.smoketest.SmokeTestDocsIT failure

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#18165]
```
==> Test Info: seed=56269F69F703EF6B; jvm=1; suite=1
Suite: org.elasticsearch.smoketest.SmokeTestDocsIT
  1> [2016-05-05 13:52:54,519][ERROR][org.elasticsearch.smoketest] This failing test was generated by documentation starting at analyzers/pattern-analyzer.asciidoc:91. It may include many snippets. See docs/README.asciidoc for an explanation of test generation.
  2> REPRODUCE WITH: gradle :docs:integTest -Dtests.seed=56269F69F703EF6B -Dtests.class=org.elasticsearch.smoketest.SmokeTestDocsIT -Dtests.method="test {yaml=analyzers/pattern-analyzer/91}" -Des.logger.level=WARN -Dtests.security.manager=true -Dtests.jvm.argline="-XX:-UseParNewGC -XX:-UseConcMarkSweepGC -XX:+UseG1GC" -Dtests.locale=ar-SD -Dtests.timezone=America/Halifax
FAILURE 0.85s | SmokeTestDocsIT.test {yaml=analyzers/pattern-analyzer/91} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected [2xx] status code but api [raw] returned [503 Service Unavailable] [{"error":{"root_cause":[{"type":"no_shard_available_action_exception","reason":"No shard available for [org.elasticsearch.action.admin.indices.analyze.AnalyzeRequest@3dc5f582]"}],"type":"no_shard_available_action_exception","reason":"No shard available for [org.elasticsearch.action.admin.indices.analyze.AnalyzeRequest@3dc5f582]"},"status":503}]
   > 	at __randomizedtesting.SeedInfo.seed([56269F69F703EF6B:DE72A0B359FF8293]:0)
   > 	at org.elasticsearch.test.rest.section.DoSection.execute(DoSection.java:107)
   > 	at org.elasticsearch.test.rest.ESRestTestCase.test(ESRestTestCase.java:395)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> NOTE: leaving temporary files on disk at: /home/hinmanm/es/elasticsearch/docs/build/testrun/integTest/J0/temp/org.elasticsearch.smoketest.SmokeTestDocsIT_56269F69F703EF6B-001
  2> NOTE: test params are: codec=Lucene60, sim=ClassicSimilarity, locale=ar-SD, timezone=America/Halifax
  2> NOTE: Linux 4.4.8-300.fc23.x86_64 amd64/Oracle Corporation 1.8.0_77 (64-bit)/cpus=4,threads=1,free=443735048,total=536870912
  2> NOTE: All tests run in this JVM: [SmokeTestDocsIT]
Completed [1/1] in 1.30s, 1 test, 1 failure <<< FAILURES!
```

Looks like the documentation needs to be corrected. This reproduces with:

```
gradle :docs:integTest -Dtests.seed=56269F69F703EF6B -Dtests.class=org.elasticsearch.smoketest.SmokeTestDocsIT -Dtests.method="test {yaml=analyzers/pattern-analyzer/91}" -Des.logger.level=WARN -Dtests.security.manager=true -Dtests.jvm.argline="-XX:-UseParNewGC -XX:-UseConcMarkSweepGC -XX:+UseG1GC" -Dtests.locale=ar-SD -Dtests.timezone=America/Halifax
```

**Comment by nik9000** [comment]
I'll have a look at it. It hadn't happened for me.
