### ISSUE TITLE
Exception on shutting down the embedded node when any of the services is closed before the node

### ISSUE THREAD

**Issue by bikeholik** [elastic/elasticsearch#18182]
Elasticsearch version: 2.3.1

Background: I'm running an embedded elasticsearch node in a spring boot application and have a scheduled job using ClusterService. 

On application shutdown when ClusterService is closed independently, before node is closed, then I get a following exception on closing a node:
```
java.lang.IllegalStateException: Can't move to started state when closed
	at org.elasticsearch.common.component.Lifecycle.canMoveToStopped(Lifecycle.java:144)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:81)
	at org.elasticsearch.node.Node.stop(Node.java:326)
	at org.elasticsearch.node.Node.close(Node.java:351)
	at com.example.NodeManager.destroy(NodeManager.java:87)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:262)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:972)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:979)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1006)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:982)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:901)
```

1. Message seems to be wrong. It tries to move to STOPPED state.
2. Shouldn't closed services be ignored when node closes?

**Comment by jasontedor** [comment]
> Message seems to be wrong. It tries to move to STOPPED state.

Already corrected in master in d0d2d2be8c2cbd94949273b4bc848aa0430c10a4.

> Shouldn't closed services be ignored when node closes?

Why is the cluster service already closed? Closed services should not be ignored when stopping a node; it's a bug if we are stopping services that are already closed.

Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions.
