### ISSUE TITLE
Deprecate user-configurable analyzer versions 

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#18267]
All analyzers, tokenizers, etc accept a `version` parameter today (see https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis.html#backwards-compatibility).

The problem is, it doesn't work as expected.  For instance in master, you can specify that you want version `3.0` of an analyzer and your request will be accepted, but the code doesn't HAVE version `3.0` of the analyzer. Lucene 6 only includes version constants for 5.0 and above.

Internally, the version parameter is useful as it means we can recognise an index created before an analyzer was changed (eg see [ArabicAnalyzer.java](https://github.com/apache/lucene-solr/blob/branch_6x/lucene/analysis/common/src/java/org/apache/lucene/analysis/ar/ArabicAnalyzer.java#L137)) but we can't read indices created before Lucene 5.0 anyway, so exposing the `version` in the API doesn't make much sense to me.

**Comment by clintongormley** [comment]
@MaineC Could you take this one please?

**Comment by MaineC** [comment]
From the docs you linked it's not quite clear to me where the `version` parameter can be added today. Do you happen to have a brief json snippet handy that I can send to a local ES instance to try it out?

Also, from reading at least some of our [version](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/lucene/Lucene.java#L114) parsing code it looks like users should at least see a warning in their log files. Is that the case here?

**Comment by clintongormley** [comment]
This is how you'd use it:

    PUT foo
    {
      "settings": {
        "analysis": {
          "analyzer": {
            "old_standard": {
              "type": "standard",
              "version": "2.0"
            }
          }
        }
      }
    }

>  it looks like users should at least see a warning in their log files. Is that the case here?

No, nothing in the logs

> (If so, then I'd guess the idea here would be to remove the leniency of defaulting to some version in case the version string cannot be parsed and fail instead.)

i don't think this should be user-configurable at all.  It should be used purely to allow bwc for existing indices (and that use is internal only)

**Comment by MaineC** [comment]
> i don't think this should be user-configurable at all. It should be used purely to allow bwc for 
> existing indices (and that use is internal only)

Makes sense to me. When looking for the code that actually parses the snippet you provided it looks to me like this is being checked only once the analyzer is actually used. Here's what I tried:

    PUT foo
    {
      "settings": {
        "analysis": {
          "analyzer": {
            "old_standard": {
              "type": "standard",
              "version": "2.0",
              "foobar": "23"
            }
          }
        }
      }
    }

I can easily add this kind of setting without any complaints in the response nor in the logs. I can also use the analyzer with

    GET /foo/_analyze
    {
      "analyzer" : "old_standard",
      "text" : "this is a test"
    }

without issue.

    DELETE /foo

    PUT foo
    {
      "settings": {
        "analysis": {
          "analyzer": {
            "old_standard": {
              "type": "standard",
              "version": "bullshit"
            }
          }
        }
      }
    }

This can be set just fine. When trying to use the analyzer through the _analyze endpoint I get good looking analysis results through HTTP, but a 

    2016-06-28 09:28:36,102][WARN ][index.analysis           ] [Vidar] [foo] no version match bullshit,     default to 6.0.0
    java.text.ParseException: Failed to parse major version from "bullshit" (got: bullshit)
    	at org.apache.lucene.util.Version.parse(Version.java:161)
    	at org.elasticsearch.common.lucene.Lucene.parseVersion(Lucene.java:112)
    	at org.elasticsearch.index.analysis.Analysis.parseAnalysisVersion(Ana

in the logs.

Others may correct me if I'm wrong, but to me this looks a lot like analysis settings aren't validated (?!) here:

https://github.com/elastic/elasticsearch/blob/93415d45061ca35042c21c45a1593cca39adb8d1/core/src/main/java/org/elasticsearch/common/settings/IndexScopedSettings.java#L153 

Not sure how deep validation should go, explicitly disallowing the `version` entry but allowing other bullshit entries seems confusing to me.

**Comment by clintongormley** [comment]
> Not sure how deep validation should go, explicitly disallowing the version entry but allowing other bullshit entries seems confusing to me. Deeply validating these settings doesn't look particularly "low-hanging-fruit"'y to me.

Agreed.  Analyzers need a big refactoring too.  For now I'd just focus on the `version` key.

**Comment by romseygeek** [comment]
cc @elastic/es-search-aggs

**Comment by akshaybhadange** [comment]
if this issue is open,can i work on this ,plz guide me as i am new to this contribution

**Comment by javanna** [comment]
heya @akshaybhadange I just updated the labels, sorry but this is probably not a great one for external contributors due to its breaking nature. We may want to reconsider how to proceed with this issue.
