### ISSUE TITLE
java.lang.IllegalArgumentException: the version needs to contain major, minor, and revision, and optionally the build: ${elasticsearch.version}

### ISSUE THREAD

**Issue by ftieben** [elastic/elasticsearch#18271]
**Elasticsearch version**: 5.0.0_alpha2
**JVM version**: openjdk version "1.8.0_51"
**OS version**: Red Hat Enterprise Linux Server release 6.7 (Santiago)

**Description of the problem including expected versus actual behavior**:

We installed the 5.0.0.alpha2 version with the .rpm and can't even start the Application:

**Provide logs (if relevant)**:

[2016-05-11 12:49:05,015][WARN ][bootstrap                ] unable to install syscall filter: 
java.lang.UnsupportedOperationException: seccomp unavailable: CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER are needed
        at org.elasticsearch.bootstrap.Seccomp.linuxImpl(Seccomp.java:347)
        at org.elasticsearch.bootstrap.Seccomp.init(Seccomp.java:616)
        at org.elasticsearch.bootstrap.JNANatives.trySeccomp(JNANatives.java:215)
        at org.elasticsearch.bootstrap.Natives.trySeccomp(Natives.java:99)
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:99)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:152)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:267)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:111)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:106)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:91)
        at org.elasticsearch.cli.Command.main(Command.java:53)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)
[2016-05-11 12:49:05,330][INFO ][node                     ] [Nathaniel Essex] version[5.0.0-alpha2], pid[28514], build[e3126df/2016-04-26T12:08:58.960Z]
[2016-05-11 12:49:05,330][INFO ][node                     ] [Nathaniel Essex] initializing ...
[2016-05-11 12:49:06,216][ERROR][bootstrap                ] Exception
java.lang.IllegalArgumentException: the version needs to contain major, minor, and revision, and optionally the build: ${elasticsearch.version}
        at org.elasticsearch.Version.fromString(Version.java:162)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:94)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:339)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:131)
        at org.elasticsearch.node.Node.<init>(Node.java:186)
        at org.elasticsearch.node.Node.<init>(Node.java:161)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:188)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:188)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:267)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:111)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:106)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:91)
        at org.elasticsearch.cli.Command.main(Command.java:53)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)

**Comment by jasontedor** [comment]
You have a plugin causing issues, maybe a botched build? Which plugins do you have installed?

**Comment by ftieben** [comment]
Thanks for that advice:

root@HOST:~$ /usr/share/elasticsearch/bin/elasticsearch-plugin remove hq
-> Removing hq...
root@HOST:~$ /etc/init.d/elasticsearch start
Starting elasticsearch:                                    [  OK  ]

**Comment by naoko** [comment]
Thank you! I see HQ is no longer supported. Attempt to uninstall plugin after upgrade is completed I got this error `ERROR: plugin hq not found; run 'elasticsearch-plugin list' to get list of installed plugins`. so I ran this `rm -rf /usr/share/elasticsearch/plugins/hq` to remove it and now things are running
