### ISSUE TITLE
`DateTimeZone.forID` doesn't work in ES 2.x

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#18328]
**Elasticsearch version**: 2.x

**JVM version**: 1.8

**OS version**: Any

**The following works in 1.x**:

```
PUT try
{
  "mappings": {
    "type": {
      "properties": {
        "time": {
          "type": "date"
        }
      }
    }
  }
}

POST try/type
{
  "time": "2016-05-09T14:33:36.202Z"
}

POST try/_search
{
  "script_fields": {
    "FIELD": {
      "script": "doc['time'].date.setZone(DateTimeZone.forID('America/New_York')); return doc['time'].date;"
    }
  }
}
```

**The following DOES NOT work in 2.x**

```
PUT try
{
  "mappings": {
    "type": {
      "properties": {
        "time": {
          "type": "date"
        }
      }
    }
  }
}

POST try/type
{
  "time": "2016-05-09T14:33:36.202Z"
}

POST try/_search
{
  "fields": [],
  "script_fields": {
    "FIELD": {
      "script": {
        "inline": "doc['time'].date.setZone(DateTimeZone.forID('America/New_York'))"
      }
    }
  }
}
```

The error is the following:

```
{
  "took": 429,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 4,
    "failed": 1,
    "failures": [
      {
        "shard": 4,
        "index": "try",
        "node": "YY36CprdRhq_oWPHloHqOA",
        "reason": {
          "type": "script_exception",
          "reason": "failed to run inline script [doc['time'].date.setZone(DateTimeZone.forID('America/New_York'))] using lang [groovy]",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "The datetime zone id 'America/New_York' is not recognised"
          }
        }
      }
    ]
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": []
  }
}
```

In the logs, i see the following:

```
[2016-05-13 10:02:00,471][DEBUG][action.search            ] [Karl Lykos] [4] Failed to execute fetch phase
RemoteTransportException[[Karl Lykos][127.0.0.1:9300][indices:data/read/search[phase/fetch/id]]]; nested: ScriptException[failed to run inline script [doc['time'].date.setZone(DateTimeZone.forID('America/New_York'))] using lang [groovy]]; nested: IllegalArgumentException[The datetime zone id 'America/New_York' is not recognised];
Caused by: ScriptException[failed to run inline script [doc['time'].date.setZone(DateTimeZone.forID('America/New_York'))] using lang [groovy]]; nested: IllegalArgumentException[The datetime zone id 'America/New_York' is not recognised];
	at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript.run(GroovyScriptEngineService.java:320)
	at org.elasticsearch.search.fetch.script.ScriptFieldsFetchSubPhase.hitExecute(ScriptFieldsFetchSubPhase.java:85)
	at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:188)
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:592)
	at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:408)
	at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:405)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: The datetime zone id 'America/New_York' is not recognised
	at org.joda.time.DateTimeZone.forID(DateTimeZone.java:229)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:228)
	at 5b2c7c46fa5b2546451451ee1ff497b431ee701d.run(5b2c7c46fa5b2546451451ee1ff497b431ee701d:1)
	at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript$1.run(GroovyScriptEngineService.java:313)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript.run(GroovyScriptEngineService.java:310)
	... 12 more
```

**Comment by gmoskovicz** [comment]
Looks related to #14524

**Comment by jasontedor** [comment]
Duplicates #18017

**Comment by jasontedor** [comment]
Note that the reproduction provided here does *not* reproduce if your machine is set to the `America/New_York` timezone; you have to change the script to a timezone that your machine is not set to.
