### ISSUE TITLE
DST issues with DateHistogram

### ISSUE THREAD

**Issue by nilsga** [elastic/elasticsearch#18326]
**Elasticsearch version**: 2.3.2

**JVM version**: 1.8.0_92

**OS version**: Windows 7

**Description of the problem including expected versus actual behavior**:

It appears that the DateHistogram aggregation has some troubles when time zone is set, and the histogram with hourly interval passes a DST transition (eg CEST -> CET). 

**Steps to reproduce**:

Tests reproducing the error in this diff against v2.3.2: https://github.com/nilsga/elasticsearch/commit/155e3081ca04cd63e6b973dbe4cebd13bb7972b8

**Provide logs (if relevant)**:

The error is 

```
Failed to execute phase [merge], [reduce] 

	at __randomizedtesting.SeedInfo.seed([71B41DDE1915B1DC:6476BA807BC1E239]:0)
	at org.elasticsearch.action.search.SearchQueryAndFetchAsyncAction$1.onFailure(SearchQueryAndFetchAsyncAction.java:76)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError
	at org.elasticsearch.search.aggregations.bucket.histogram.InternalHistogram.addEmptyBuckets(InternalHistogram.java:442)
	at org.elasticsearch.search.aggregations.bucket.histogram.InternalHistogram.doReduce(InternalHistogram.java:466)
	at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:153)
	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:170)
	at org.elasticsearch.search.controller.SearchPhaseController.merge(SearchPhaseController.java:411)
	at org.elasticsearch.action.search.SearchQueryAndFetchAsyncAction$1.doRun(SearchQueryAndFetchAsyncAction.java:64)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	... 3 more
```

I think it is related to the implementation of `TimeZoneRounding.nextRoundingInterval`. I don't quite get why time is converted from UTC to local time, and then back to UTC. I would expect a certain point of time to be constant, regardless of timezone. Formatting of time, however, I can understand would require time zone specific behaviour.

**Comment by jasontedor** [comment]
Relates #18310

**Comment by nilsga** [comment]
I have not fully understood the logic yet, but It seems odd that the rounding logic is implemented by actually shifting the time according to local "calendar" time. All duration fields in `DateTimeUnit` seems to be UTC based. If one instead looked up the `DateTimeField` with the correct timezone of the chronology, it seems to me like the rounding should be provided "out of the box" by Joda.

**Comment by cbuescher** [comment]
@nilsga great catch, I'm looking into this and think I found the glitch in the rounding logic of `TimeZoneRounding.nextRoundingInterval`. The conversion from UTC to local time is necessary there for day or month intervals, otherwise we would end up cases where `TimeZoneRounding.nextRoundingInterval` is not on the correct start of day/month when crossing dst transitions. But I think for smaller durations (hours in your case, minutes and seconds also) we should not do this. I will need to look a bit closer and add some test to be sure though.

**Comment by cbuescher** [comment]
This is how this behaviour presents itself outside of unit-tests: create an empty index, add any document with a date field, then do a histogram query with extended bounds covering the last DST end (e.g. Oslo/Europe 2015-10-25, 2015-10-25T02:00:00.000+02:00):

```
DELETE /_all

PUT /test/type/1
{
  "dateField" : "2000-01-01"
}

GET /test/type/_search
{
  "query": {
    "match_none": {}
  },
  "aggs": {
    "events_by_date": {
      "date_histogram": {
        "field": "dateField",
        "interval": "1h",
        "time_zone": "Europe/Oslo",
        "min_doc_count": 0,
        "extended_bounds": {
          "min": "2015-10-25T02:00:00.000+02:00",
          "max": "2015-10-25T04:00:00.000+01:00"
        }
      }
    }
  }
}

"aggregations": {
    "events_by_date": {
      "buckets": [
        {
          "key_as_string": "2015-10-25T02:00:00.000+02:00",
          "key": 1445731200000,
          "doc_count": 0
        },
        {
          "key_as_string": "2015-10-25T03:00:00.000+01:00",
          "key": 1445738400000,
          "doc_count": 0
        },
        {
          "key_as_string": "2015-10-25T04:00:00.000+01:00",
          "key": 1445742000000,
          "doc_count": 0
        }
      ]
    }
  }
```

The problem is that when looking at the bucket keys (utc), the first bucket covers two hours (1445738400000 - 1445731200000 = 7200000) whereas the other buckets are one hour(3600000 ms) wide.

In the other direction (start of DST) we dont have the same problem. Since local time is advanced by one hour, we still have 1h buckets, but you can see the jump in "key_as_string":

```
GET /test/type/_search
{
  "query": {
    "match_none": {}
  },
  "aggs": {
    "events_by_date": {
      "date_histogram": {
        "field": "dateField",
        "interval": "1h",
        "time_zone": "Europe/Oslo",
        "min_doc_count": 0,
        "extended_bounds": {
          "min": "2016-03-27T01:00:00.000+01:00",
          "max": "2016-03-27T04:00:00.000+02:00"
        }
      }
    }
  }
}

"aggregations": {
    "events_by_date": {
      "buckets": [
        {
          "key_as_string": "2016-03-27T01:00:00.000+01:00",
          "key": 1459036800000,
          "doc_count": 0
        },
        {
          "key_as_string": "2016-03-27T03:00:00.000+02:00",
          "key": 1459040400000,
          "doc_count": 0
        },
        {
          "key_as_string": "2016-03-27T04:00:00.000+02:00",
          "key": 1459044000000,
          "doc_count": 0
        }
      ]
    }
  } 
```

I think we should have equally spaced date histogram buckets for hour and sub-hour time units and will open a PR for that.

**Comment by nilsga** [comment]
Thanks for looking into it. I understand that you need to have correctly aligned buckets for all time units. But I don't understand why this could not be handled by the JodaTime library by using `ISOChronology.getInstance(timeZone)` instead of `ISOChronology.getInstanceUTC()`, which would yield time zone adjusted "floor" values for `DateTimeField.roundFloor`?

```
DateTime time = new DateTime(1445731200000L, DateTimeZone.UTC);DateTimeZone.UTC);
DateTimeField fieldUtc = ISOChronology.getInstanceUTC().dayOfMonth();
DateTimeField field = ISOChronology.getInstance(DateTimeZone.forID("Europe/Oslo")).dayOfMonth();
DateTime rounded = new DateTime(field.roundFloor(time.getMillis()), DateTimeZone.forID("Europe/Oslo"));
DateTime roundedUtc = new DateTime(fieldUtc.roundFloor(time.getMillis()), DateTimeZone.UTC);
System.out.println(rounded);
System.out.println(roundedUtc);
System.out.println(rounded.withZone(DateTimeZone.UTC));
```

Output:

```
2015-10-25T00:00:00.000+02:00
2015-10-25T00:00:00.000Z
2015-10-24T22:00:00.000Z
```

**Comment by cbuescher** [comment]
@nilsga thanks for pointing this out. As far as I see, this will do the same thing in ZonedChronology#roundFloor() that we are currently do in our TimeZoneRounding#roundKey(), namely converting UTC to local and back. It might be worth looking into whether using Joda directly for this would simplify our code base or not.
