### ISSUE TITLE
[spark] fields replacement in es.update.script.params fails for objects

### ISSUE THREAD

**Issue by cscetbon** [elastic/elasticsearch#18358]
**Elasticsearch version**: 1.7+

**JVM version**: 1.7+

**OS version**: OS X, Linux

**Description of the problem including expected versus actual behavior**:

Parameter fields corresponding to a nested object are substituted by strings instead of collections.
Which means that collection operations can't succeed in scripts. A workaround is to convert the string to an object before using it in the script, but it should definitely be handled internally.

**Steps to reproduce**:

- Delete index in case it already exists

```curl -XDELETE 'http://localhost:9200/index2'```

- Add mapping

```
curl -XPOST 'http://localhost:9200/index2' -d '
{
  "mappings": {
    "contact": {
      "properties": {
        "id": {
          "type": "string"
        },
        "adresses": {
          "type": "nested", 
          "properties": {
            "id":    { "type": "string"  },
            "zipcode": { "type": "string"  }
          }
        }
      }
    }
  }
}
'
```
- Create new contact

```curl -XPOST 'http://localhost:9200/index2/contact/67861' -d '{ "id" : "67861","adresses": [] }'```
- Use Spark to try to add an entry to adresses nested object 

```
import org.apache.spark.{SparkConf, SparkContext}
import org.elasticsearch.spark._
sc.stop
val sparkConf = new SparkConf().set("es.write.operation", "upsert").set("es.input.json", "true").set("es.mapping.id","id")
val sc = new SparkContext(sparkConf)
val lines = sc.parallelize( List("""{"id":"67861","address":{"zipcode":"25381","id":"67861"}}"""))
val up_params = "new_address:address"
val up_script = "ctx._source.adresses+=new_address"
lines.saveToEs("index2/contact", Map("es.update.script.params" -> up_params, "es.update.script" -> up_script))
```

We then get the following error

```
failed to execute bulk item (index) index {[index2][contact][67861], source[{"id":"67861","adresses":["{\"zipcode\":\"25381\",\"id\":\"67861\"}"]}]}
MapperParsingException[object mapping for [adresses] tried to parse field [null] as object, but found a concrete value]
...
```

In the error message you can see that the issue is that what is inserted into adresses array is a string and not an object.
 
If we use an object in the script it works as expected :

 ```
val up_script = """ctx._source.adresses += [zipcode: '25381', id: '67861']"""
lines.saveToEs("index2/contact", Map("es.update.script" -> up_script))
```

**Provide logs (if relevant)**: 
```
failed to execute bulk item (index) index {[index2][contact][67861], source[{"id":"67861","adresses":["{\"zipcode\":\"25381\",\"id\":\"67861\"}"]}]}
MapperParsingException[object mapping for [adresses] tried to parse field [null] as object, but found a concrete value]
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:213)
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:306)
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:436)
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:262)
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:122)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309)
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:580)
```

**Describe the feature**: NA

**Comment by clintongormley** [comment]
HI @cscetbon 

I suggest you open this issue on the es-hadoop list: https://github.com/elastic/elasticsearch-hadoop/issues

**Comment by cscetbon** [comment]
@clintongormley 👌
