### ISSUE TITLE
EngineException[Couldn't resolve version] nested: NotSerializableExceptionWrapper

### ISSUE THREAD

**Issue by JackWang917** [elastic/elasticsearch#18365]
I got the following exception, when I tried to update some records, I never seen this exception before, please help:

```
2016-05-15 20:27:04,411][INFO ][rest.suppressed] /index1/aprelease/1122/_update Params: {id=aa22, index=index1, type=aprelease}

RemoteTransportException[[test-es15-a][indices:data/write/update[s]]]; nested: 
EngineException[Couldn't resolve version]; nested: NotSerializableExceptionWrapper[Input/output 
error: NIOFSIndexInput(path="/data/node-a/data/ts-data/nodes/0/indices/index1/18/index/_ypk3.cfs") 
[slice=_ypk3_Lucene50_0.tim]]; nested: NotSerializableExceptionWrapper[Input/output error];

Caused by: [index1][[index1][18]] EngineException[Couldn't resolve version]; nested: 
NotSerializableExceptionWrapper[Input/output error: NIOFSIndexInput(path="/data/node-a/data/ts-
data/nodes/0/indices/index1/18/index/_ypk3.cfs") [slice=_ypk3_Lucene50_0.tim]]; nested: 
NotSerializableExceptionWrapper[Input/output error];
	at org.elasticsearch.index.engine.Engine.getFromSearcher(Engine.java:256)
	at org.elasticsearch.index.engine.InternalEngine.get(InternalEngine.java:349)
	at org.elasticsearch.index.shard.IndexShard.get(IndexShard.java:606)
	at org.elasticsearch.index.get.ShardGetService.innerGet(ShardGetService.java:173)
	at org.elasticsearch.index.get.ShardGetService.get(ShardGetService.java:86)
	at org.elasticsearch.action.update.UpdateHelper.prepare(UpdateHelper.java:76)
	at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:170)
	at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:164)
	at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:65)
	at org.elasticsearch.action.support.single.instance.TransportInstanceSingleOperationAction$ShardTransportHandler.messageReceived(TransportInstanceSingleOperationAction.java:249)
	at org.elasticsearch.action.support.single.instance.TransportInstanceSingleOperationAction$ShardTransportHandler.messageReceived(TransportInstanceSingleOperationAction.java:245)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:299)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by clintongormley** [comment]
What version of Elasticsearch? My initial guess is that you have a corrupt shard.

**Comment by rmuir** [comment]
"input/output error" often points to an error with the filesystem or hardware.

**Comment by JackWang917** [comment]
ES version is 2.1

**Comment by JackWang917** [comment]
I found the reason: The disk was broken. But why ES didn't note that, it seems ES had no ware about the big problem. Is an ES bug?

**Comment by jasontedor** [comment]
It did, when an I/O operation on the disk failed. There is no Elasticsearch bug here.
