### ISSUE TITLE
unknown setting [discovery.ec2.ping_timeout]

### ISSUE THREAD

**Issue by mats116** [elastic/elasticsearch#18386]
about 5.0.0-alpha2.

My settings are as follows:
```yml
discovery.type: ec2
discovery.ec2.ping_timeout: 60s
```

Logs are as follows:
```java
Exception in thread "main" java.lang.IllegalArgumentException: unknown setting [discovery.ec2.ping_timeout] did you mean any of [discovery.zen.ping_timeout, discovery.zen.fd.ping_timeout, discovery.zen.join_timeout, discovery.zen.publish_timeout, discovery.zen.commit_timeout]?
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:267)
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:238)
	at org.elasticsearch.common.settings.SettingsModule.configure(SettingsModule.java:120)
	at <<<guice>>>
	at org.elasticsearch.node.Node.<init>(Node.java:235)
	at org.elasticsearch.node.Node.<init>(Node.java:161)
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:188)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:188)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:267)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:111)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:106)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:91)
	at org.elasticsearch.cli.Command.main(Command.java:53)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)
Refer to the log for complete error details.
```

`discovery.ec2.ping_timeout` is defined in [Docs](https://www.elastic.co/guide/en/elasticsearch/plugins/master/discovery-ec2-discovery.html)

Is this a bug ?

**Comment by rjernst** [comment]
You need to install the `discovery-ec2` plugin.

**Comment by s1monw** [comment]
@rjernst hmm maybe we need to add some DYM like functionality for prefixes too and list at least build-in plugins. I think this can reduce the noise for stuff like this on the issue tracker?

**Comment by rjernst** [comment]
@s1monw I think the only way to do that would be to include all plugin settings somehow inside ES itself (perhaps a resource file generated in the build from the plugin source)? But I don't think it should be something managed by hand, it would just get out of date quickly?
