### ISSUE TITLE
Cannot open 2.3.1 index in 5.0.0-alpha2

### ISSUE THREAD

**Issue by pokorsky** [elastic/elasticsearch#18418]
**Elasticsearch version**: 5.0.0-alpha2
**JVM version**:  1.8.0_92
**OS version**: MS Win 10
**Description of the problem including expected versus actual behavior**:
I cannot open the index created with ES 2.3.1 in ES 5.0.0-alpha2. According to [docs] (https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking-changes-5.0.html) there is no need to upgrade the 2.x index but I get the following exception. The other kibana index was migrated successfully.

```
Exception in thread "main" java.lang.IllegalStateException: The index [[sdtwitter-20160417000000/23TYmyVRQxmn7VZ4Ih3Oug]] was created before v2.0.0.beta1 and wasn't upgraded. This index should be open using a version before 5.0.0-alpha2 and upgraded using the upgrade API.
        at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.checkSupportedVersion(MetaDataIndexUpgradeService.java:98)
        at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.upgradeIndexMetaData(MetaDataIndexUpgradeService.java:72)
        at org.elasticsearch.gateway.GatewayMetaState.upgradeMetaData(GatewayMetaState.java:229)
        at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:90)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at <<<guice>>>
        at org.elasticsearch.node.Node.<init>(Node.java:235)
        at org.elasticsearch.node.Node.<init>(Node.java:161)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:188)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:188)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:267)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:111)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:106)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:91)
        at org.elasticsearch.cli.Command.main(Command.java:53)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)
```

**Comment by s1monw** [comment]
can you provide the index metadata by any chance it should be in the data path underneath `sdtwitter-20160417000000/_state`

**Comment by pokorsky** [comment]
This is the origin metadata file before migration.

[state-13.zip](https://github.com/elastic/elasticsearch/files/268859/state-13.zip)

**Comment by s1monw** [comment]
this index was created with `1.7.3` according to that state file. You have to reindex indices on 2.x before moving to 5.x. Yet, I think the error message is confusing here and has to be fixed. @clintongormley I think we should be explicit here and say `has to be reindexed with 2.x`?

**Comment by pokorsky** [comment]
The index was imported with elasticdump to ES 2.3.1 with bulk api. Is it really necessary to upgrade the index?

**Comment by s1monw** [comment]
> The index was imported with elasticdump to ES 2.3.1 with bulk api. Is it really necessary to upgrade the index?

I don't know what elasticdump is and how it works. If that tool blindly copied index metadata then it will essentially create broken indices. We rely on the metadata we use internally to make decisions. If you reindexed it into 2.3 with a tool that copies the created_version from the old index then you bascially have to do that again, sorry.

**Comment by s1monw** [comment]
@pokorsky I opened an issue with elasticsearch-dump

**Comment by pokorsky** [comment]
Sorry for confusion. I have investigated the data and it does not seem to be related to elasticdump. At least there is no mention of ES version in the imported dump file.
The current index was created in ES 2.3.1 with
```
PUT sdtwitter-20160417000000
{
  "settings":{
    ...
    "version": {"created": "1070399"},
    "uuid": "FhxSdp0YRNSyb9pztxyPSQ"}
    ...
  }
}
```
Does `1070399` stand for `1.7.3`?
But the index status shows now
```json
"uuid": "23TYmyVRQxmn7VZ4Ih3Oug",
"version": {
    "created": "1070399",
    "upgraded": "2030199"
}
```
Does not `"upgraded": "2030199"` mean the version of the index is 2.3.1? Does it need to be reindexed yet?

**Comment by clintongormley** [comment]
> Does not "upgraded": "2030199" mean the version of the index is 2.3.1? Does it need to be reindexed yet?

Have a look at the warning on the upgrade API page: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-upgrade.html

You need to reindex this index.  The reindex API in 2.3 makes this easy.  Try out the migration helper plugin which gives a simple UI for reindexing: https://github.com/elastic/elasticsearch-migration/tree/2.x

**Comment by pokorsky** [comment]
I wanted to avoid several hours of reindexing as the index was created in 2.3.1 but the reindex definitely solved the issue. Thank you for your help on this.
