### ISSUE TITLE
CI: Failing org.elasticsearch.messy.tests.IndicesRequestTests on 2.x

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#18453]
**Elasticsearch version**: 2.x

**JVM version**: Oracle Corporation 1.8.0_77 (64-bit)

**OS version**: Linux 3.12.51-52.31-default amd64

**Description of the problem including expected versus actual behavior**:

Failing CI tests on 2.x branch:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+2.x+multijob-intake/205/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+2.x+multijob-intake/204/console
http://build-us-00.elastic.co/job/es_core_2x_windows-2012-r2/973
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+2.x+multijob-intake/203/console

**Provide logs (if relevant)**:
```
Suite: org.elasticsearch.messy.tests.IndicesRequestTests
  2> REPRODUCE WITH: mvn test -Pdev -pl org.elasticsearch.module:lang-groovy -Dtests.seed=A693FA69435937FD -Dtests.class=org.elasticsearch.messy.tests.IndicesRequestTests -Dtests.method="testClearCache" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=fr-CH -Dtests.timezone=Europe/Belfast
FAILURE 0.95s J0 | IndicesRequestTests.testClearCache <<<
   > Throwable #1: java.lang.AssertionError: no internal requests intercepted for action [indices:admin/cache/clear[n]]
   > Expected: a value greater than <0>
   >      but: <0> was equal to <0>
   > 	at __randomizedtesting.SeedInfo.seed([A693FA69435937FD:684CC0A5C1CA78BD]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.messy.tests.IndicesRequestTests.assertSameIndices(IndicesRequestTests.java:736)
   > 	at org.elasticsearch.messy.tests.IndicesRequestTests.assertSameIndices(IndicesRequestTests.java:725)
   > 	at org.elasticsearch.messy.tests.IndicesRequestTests.testClearCache(IndicesRequestTests.java:426)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> REPRODUCE WITH: mvn test -Pdev -pl org.elasticsearch.module:lang-groovy -Dtests.seed=A693FA69435937FD -Dtests.class=org.elasticsearch.messy.tests.IndicesRequestTests -Dtests.method="testForceMerge" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=fr-CH -Dtests.timezone=Europe/Belfast
FAILURE 0.57s J0 | IndicesRequestTests.testForceMerge <<<
   > Throwable #1: java.lang.AssertionError: no internal requests intercepted for action [indices:admin/optimize[n]]
   > Expected: a value greater than <0>
   >      but: <0> was equal to <0>
   > 	at __randomizedtesting.SeedInfo.seed([A693FA69435937FD:FBEBABFB4BDD3AA5]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.messy.tests.IndicesRequestTests.assertSameIndices(IndicesRequestTests.java:736)
   > 	at org.elasticsearch.messy.tests.IndicesRequestTests.assertSameIndices(IndicesRequestTests.java:725)
   > 	at org.elasticsearch.messy.tests.IndicesRequestTests.testForceMerge(IndicesRequestTests.java:401)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> REPRODUCE WITH: mvn test -Pdev -pl org.elasticsearch.module:lang-groovy -Dtests.seed=A693FA69435937FD -Dtests.class=org.elasticsearch.messy.tests.IndicesRequestTests -Dtests.method="testRecovery" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=fr-CH -Dtests.timezone=Europe/Belfast
FAILURE 1.64s J0 | IndicesRequestTests.testRecovery <<<
   > Throwable #1: java.lang.AssertionError: no internal requests intercepted for action [indices:monitor/recovery[n]]
   > Expected: a value greater than <0>
   >      but: <0> was equal to <0>
   > 	at __randomizedtesting.SeedInfo.seed([A693FA69435937FD:676383C56E09FD5A]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.messy.tests.IndicesRequestTests.assertSameIndices(IndicesRequestTests.java:736)
   > 	at org.elasticsearch.messy.tests.IndicesRequestTests.assertSameIndices(IndicesRequestTests.java:725)
   > 	at org.elasticsearch.messy.tests.IndicesRequestTests.testRecovery(IndicesRequestTests.java:438)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> REPRODUCE WITH: mvn test -Pdev -pl org.elasticsearch.module:lang-groovy -Dtests.seed=A693FA69435937FD -Dtests.class=org.elasticsearch.messy.tests.IndicesRequestTests -Dtests.method="testIndicesStats" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=fr-CH -Dtests.timezone=Europe/Belfast
FAILURE 0.80s J0 | IndicesRequestTests.testIndicesStats <<<
   > Throwable #1: java.lang.AssertionError: no internal requests intercepted for action [indices:monitor/stats[n]]
   > Expected: a value greater than <0>
   >      but: <0> was equal to <0>
   > 	at __randomizedtesting.SeedInfo.seed([A693FA69435937FD:B7CE8FFC016D7FCB]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.messy.tests.IndicesRequestTests.assertSameIndices(IndicesRequestTests.java:736)
   > 	at org.elasticsearch.messy.tests.IndicesRequestTests.assertSameIndices(IndicesRequestTests.java:725)
   > 	at org.elasticsearch.messy.tests.IndicesRequestTests.testIndicesStats(IndicesRequestTests.java:462)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> REPRODUCE WITH: mvn test -Pdev -pl org.elasticsearch.module:lang-groovy -Dtests.seed=A693FA69435937FD -Dtests.class=org.elasticsearch.messy.tests.IndicesRequestTests -Dtests.method="testSegments" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=fr-CH -Dtests.timezone=Europe/Belfast
FAILURE 1.55s J0 | IndicesRequestTests.testSegments <<<
   > Throwable #1: java.lang.AssertionError: no internal requests intercepted for action [indices:monitor/segments[n]]
   > Expected: a value greater than <0>
   >      but: <0> was equal to <0>
   > 	at __randomizedtesting.SeedInfo.seed([A693FA69435937FD:73BCFB86802FF5E7]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.messy.tests.IndicesRequestTests.assertSameIndices(IndicesRequestTests.java:736)
   > 	at org.elasticsearch.messy.tests.IndicesRequestTests.assertSameIndices(IndicesRequestTests.java:725)
   > 	at org.elasticsearch.messy.tests.IndicesRequestTests.testSegments(IndicesRequestTests.java:450)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+2.x+multijob-intake/modules/lang-groovy/target/J0/temp/org.elasticsearch.messy.tests.IndicesRequestTests_A693FA69435937FD-001
  2> NOTE: test params are: codec=Asserting(Lucene54): {field=PostingsFormat(name=Asserting), _field_names=PostingsFormat(name=Asserting), _type=PostingsFormat(name=Asserting), _uid=PostingsFormat(name=Asserting), _timestamp=PostingsFormat(name=Asserting), _all=PostingsFormat(name=Asserting)}, docValues:{_type=DocValuesFormat(name=Lucene54), _version=DocValuesFormat(name=Lucene54), _timestamp=DocValuesFormat(name=Lucene54)}, sim=RandomSimilarity(queryNorm=false,coord=crazy): {}, locale=fr-CH, timezone=Europe/Belfast
  2> NOTE: Linux 3.12.51-52.31-default amd64/Oracle Corporation 1.8.0_77 (64-bit)/cpus=4,threads=1,free=342974464,total=513802240
  2> NOTE: All tests run in this JVM: [GroovyScriptTests, IndicesRequestTests]
```

**Comment by cbuescher** [comment]
This reproduces on 2.x when running the whole test suit. I think it might have started with 40452f0, the rest of the changes since then look harmless. @danielmitterdorfer could you take a look at this? I will put an @AwaitsFix in for this test for now.
