### ISSUE TITLE
geo_bounding_box queries failing with "Illegal shift value, must be 32..63; got shift=0"

### ISSUE THREAD

**Issue by daamsie** [elastic/elasticsearch#18458]
**Elasticsearch version**:2.3.2

**JVM version**: 1.8.0 25.0-b70

**OS version**: Mac OS X 10.10.3

**Description of the problem including expected versus actual behavior**:
Indexing documents with geo_point attributes and then finding them in a bounding_box results in an illegal_argument_exception with the reason "Illegal shift value, must be 32..63; got shift=0"

**Steps to reproduce**:
1. 
`curl -XPUT 'http://localhost:9200/test/' `

2.
```
curl -XPUT 'http://localhost:9200/test/a/_mapping' -d '
{
    
    "properties" : {
        "location" : {"type": "geo_point", "store": true, "lat_lon": true},
        "name": {"type" : "string", "store" : true }
    }
}
'
```
 3.
```
curl -XPOST 'http://localhost:9200/test/a/1/' -d '
{
    "location" : {"lat": 44, "lon": 55},
    "name": "John Smith"
}
'
```
4. 
```
curl -XPOST 'http://localhost:9200/test/a/_search' -d '
{
 query: {
    bool: {
      must: {
        match_all: {}
      },
      filter: {
        geo_bounding_box: {
        location : {
              top_left : [56,43],
              bottom_right : [54,45]
          }
        }
      }
    }   
  }
}
'
```

**Stacktrace**:

```
[2016-05-19 11:11:51,705][DEBUG][action.search            ] [Crimson Dynamo V] [test][3], node[qR1OS2SgRkKv5G-g7z43Tw], [P], v[2], s[STARTED], a[id=43cmhMAPSBCaD8gU5b88Hg]: Failed to execute [org.elasticsearch.action.search.SearchRequest@3ccd252e] lastShard [true]
RemoteTransportException[[Crimson Dynamo V][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: IllegalArgumentException[Illegal shift value, must be 32..63; got shift=0];
Caused by: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: IllegalArgumentException[Illegal shift value, must be 32..63; got shift=0];
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:409)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:113)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:366)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:378)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.IllegalArgumentException: Illegal shift value, must be 32..63; got shift=0
	at org.apache.lucene.spatial.util.GeoEncodingUtils.geoCodedToPrefixCodedBytes(GeoEncodingUtils.java:114)
	at org.apache.lucene.spatial.util.GeoEncodingUtils.geoCodedToPrefixCoded(GeoEncodingUtils.java:92)
	at org.apache.lucene.spatial.geopoint.search.GeoPointPrefixTermsEnum$Range.fillBytesRef(GeoPointPrefixTermsEnum.java:234)
	at org.apache.lucene.spatial.geopoint.search.GeoPointTermsEnum.nextRange(GeoPointTermsEnum.java:71)
	at org.apache.lucene.spatial.geopoint.search.GeoPointPrefixTermsEnum.nextRange(GeoPointPrefixTermsEnum.java:169)
	at org.apache.lucene.spatial.geopoint.search.GeoPointPrefixTermsEnum.nextSeekTerm(GeoPointPrefixTermsEnum.java:188)
	at org.apache.lucene.index.FilteredTermsEnum.next(FilteredTermsEnum.java:212)
	at org.apache.lucene.spatial.geopoint.search.GeoPointTermQueryConstantScoreWrapper$1.scorer(GeoPointTermQueryConstantScoreWrapper.java:103)
	at org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight.scorer(LRUQueryCache.java:628)
	at org.elasticsearch.indices.cache.query.IndicesQueryCache$CachingWeightWrapper.scorer(IndicesQueryCache.java:263)
	at org.apache.lucene.search.BooleanWeight.scorer(BooleanWeight.java:389)
	at org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight.scorer(LRUQueryCache.java:628)
	at org.elasticsearch.indices.cache.query.IndicesQueryCache$CachingWeightWrapper.scorer(IndicesQueryCache.java:263)
	at org.apache.lucene.search.ConstantScoreQuery$1.scorer(ConstantScoreQuery.java:134)
	at org.apache.lucene.search.BooleanWeight.scorer(BooleanWeight.java:389)
	at org.apache.lucene.search.Weight.bulkScorer(Weight.java:135)
	at org.apache.lucene.search.BooleanWeight.bulkScorer(BooleanWeight.java:370)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:818)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:535)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:384)
	... 12 more

```

**Comment by brwe** [comment]
I think `top_left` and `bottom_right` need to be swapped in the query. This query works:

```
POST /test/a/_search
{
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "filter": {
        "geo_bounding_box": {
          "location": {
            "bottom_right": [
              56,
              43
            ],
            "top_left": [
              54,
              45
            ]
          }
        }
      }
    }
  }
}
```


A better error message would certainly help here.

**Comment by daamsie** [comment]
Interesting. But why would 54 be the top of the box and 56 be bottom? And why would 45 be right while 43 is left? That doesn't make any sense.

For now I am working around this bug by using a geo_polygon, but I understand the performance is not as good. 

```
curl -XPOST 'http://localhost:9200/test/a/_search' -d '
{
 query: {
    bool: {
      must: {
        match_all: {}
      },
      filter: {
        geo_polygon: {
        location : {
            points: [
                {lat: 43, lon: 54},
                {lat: 43, lon: 56},
                {lat: 45, lon: 56},
                {lat: 45, lon: 54}
            ]
          }
        }
      }
    }   
  }
}
'
```

**Comment by s1monw** [comment]
@nknize can you please look at this issue. I think it has something todo with your geov2 changes. Maybe we trying to pull a double from a float field or something like this. It seems like the wrong decoding for prefix coded terms is used on the lucene level.

**Comment by brwe** [comment]
>  But why would 54 be the top of the box and 56 be bottom? And why would 45 be right while 43 is left? That doesn't make any sense.

When you define a geo coordinate with [x, y] then x is the longitude and y the latitude, see [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-bounding-box-query.html#_lat_lon_as_array_2). 

So [56, y] will be "right" (east, unless you want to span 56-54 once around earth) of  [54, y]  and [x, 45] would be "above" (north) of [x, 43]. 
At least this is how I understood it.

**Comment by brwe** [comment]
Although now that I think about it I am assuming here that  +10 longitude means we are going east and I am not sure anymore this is correct. @nknize  will hopefully be able to explain.

**Comment by daamsie** [comment]
+10 longitude does mean you're headed east. 

But I see what you're saying now... I did know that geoJSON format has lon, then lat, but I didn't notice that top_left also follows this. The naming is _really_ confusing in that instance since it strongly implies that top (latitude) comes before left (longitude). It's like naming it latLon and then having the values be [lon, lat]

Ah well, in that case I agree that some better error messaging would be great here, but at least this thread now exists to help future people googling for an answer (I spent a while hunting for one on this! :))

**Comment by nknize** [comment]
@daamsie I see how one could misinterpret `top_left` `bottom_right` json field names. For this reason we recommend expressing a geo point as an object so there's no ambiguity as to which value is lat and lon.

Still, the error message indicates a bug with pole crossing. I would expect this query be split into 2 bboxes: [56, 43] , [180, -90] and [-180, 90] , [54, 45]  The fact this wasn't caught also indicates missing test coverage so thank you for pointing this out.

**Comment by jweber** [comment]
I just wanted to note that we started seeing this same issue after moving to 2.3.3.

If it helps, here are a few of the _geo_bounding_box_ values that were generating this message:

`{
	"top_left": "48.65, -123.4805",
	"bottom_right": "48.7, -123.409"
}`

`{
	"top_left": "54, 10.5",
	"bottom_right": "54.1, 10.6"
}`

`{
	"top_left": "37.3, -112.6",
	"bottom_right": "37.4, -112.5"
}`

**Comment by nknize** [comment]
Hi @jweber, the coordinates should be in lon, lat order.

**Comment by jweber** [comment]
[The docs](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-geo-bounding-box-query.html#_lat_lon_as_string_2) say that it should be in lat,lon order when used as a string. Is that incorrect?

**Comment by nknize** [comment]
Sorry, you're correct. But in each of your examples the top `latitude` value is less than the bottom. So the bounding boxes will be crossing the pole. It looks like the check for this didn't make it into the 2.3 branch so you're getting the scary Lucene exception. I'll back port the friendlier exception. Thanks for the heads up!

**Comment by nknize** [comment]
I added the friendlier exception handling in https://github.com/elastic/elasticsearch/commit/55513946827b5061be6d431da5671711ec489d6c Its already fixed on master so I'm going to go ahead and close this issue.
