### ISSUE TITLE
Rest URL path parsing fails with IAE when trying to send an error response

### ISSUE THREAD

**Issue by camilojd** [elastic/elasticsearch#18476]
**Elasticsearch version**: master @ c257e2c51f235853c4453a86e10e463813140fc9

**JVM version**:  Oracle Corporation 1.8.0_91 [OpenJDK 64-Bit Server VM 25.91-b14]

**OS version**: Linux 4.4.9-300.fc23.x86_64 (amd64)

**Description of the problem including expected versus actual behavior**:
ES fails to respond with an error for an invalid URL but doesn't disconnect the client.

The REST layer should fail with an appropriate error and close the connection immediately.

**Steps to reproduce**:
`curl 'localhost:9200/%a`'

**Provide logs (if relevant)**:

```
[elasticsearch] [2016-05-19 14:35:52,468][ERROR][rest                     ] [Nuke - Squadron Supreme Member] failed to send failure response for uri [/%a]
[elasticsearch] java.lang.IllegalArgumentException: partial escape sequence at end of string: /%a
[elasticsearch] 	at org.elasticsearch.rest.support.RestUtils.decode(RestUtils.java:182)
[elasticsearch] 	at org.elasticsearch.rest.support.RestUtils.decodeComponent(RestUtils.java:143)
[elasticsearch] 	at org.elasticsearch.rest.support.RestUtils.decodeComponent(RestUtils.java:107)
[elasticsearch] 	at org.elasticsearch.rest.RestRequest.path(RestRequest.java:62)
[elasticsearch] 	at org.elasticsearch.rest.BytesRestResponse.convert(BytesRestResponse.java:126)
[elasticsearch] 	at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:90)
[elasticsearch] 	at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:81)
[elasticsearch] 	at org.elasticsearch.rest.RestController.sendErrorResponse(RestController.java:184)
[elasticsearch] 	at org.elasticsearch.http.HttpServer.dispatchRequest(HttpServer.java:116)
[elasticsearch] 	at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:490)
[elasticsearch] 	at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:65)
[elasticsearch] 	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
[elasticsearch] 	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
[elasticsearch] 	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
[elasticsearch] 	at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:85)

```

**Comment by jasontedor** [comment]
Thanks for reporting. I opened #18477.
