### ISSUE TITLE
[CI] org.elasticsearch.indices.IndicesServiceTests.testDeleteIndexStore fails due to state file not existing

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#18558]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/636/console

The failure is:

```
ERROR   0.14s J1 | IndicesServiceTests.testDeleteIndexStore <<< FAILURES!
   > Throwable #1: ElasticsearchException[java.io.IOException: failed to read [id:1, legacy:false, file:/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-intake/core/build/testrun/test/J1/temp/org.elasticsearch.indices.IndicesServiceTests_678304BAB99F89CE-001/tempDir-011/data/single-node-cluster-CHILD_VM=[1]-CLUSTER_SEED=[3730156636843346220]-HASH=[2CC2E218290088]/nodes/0/_state/global-1.st]]; nested: IOException[failed to read [id:1, legacy:false, file:/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-intake/core/build/testrun/test/J1/temp/org.elasticsearch.indices.IndicesServiceTests_678304BAB99F89CE-001/tempDir-011/data/single-node-cluster-CHILD_VM=[1]-CLUSTER_SEED=[3730156636843346220]-HASH=[2CC2E218290088]/nodes/0/_state/global-1.st]]; nested: NoSuchFileException[/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-intake/core/build/testrun/test/J1/temp/org.elasticsearch.indices.IndicesServiceTests_678304BAB99F89CE-001/tempDir-011/data/single-node-cluster-CHILD_VM=[1]-CLUSTER_SEED=[3730156636843346220]-HASH=[2CC2E218290088]/nodes/0/_state/global-1.st];
   > 	at __randomizedtesting.SeedInfo.seed([678304BAB99F89CE:D34003C59E7578EF]:0)
   > 	at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:164)
   > 	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:321)
   > 	at org.elasticsearch.gateway.MetaStateService.loadGlobalState(MetaStateService.java:109)
   > 	at org.elasticsearch.gateway.MetaStateService.loadFullState(MetaStateService.java:54)
   > 	at org.elasticsearch.gateway.GatewayMetaState.loadMetaState(GatewayMetaState.java:102)
   > 	at org.elasticsearch.indices.IndicesServiceTests.testDeleteIndexStore(IndicesServiceTests.java:128)
   > 	at java.lang.Thread.run(Thread.java:745)
   > Caused by: java.io.IOException: failed to read [id:1, legacy:false, file:/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-intake/core/build/testrun/test/J1/temp/org.elasticsearch.indices.IndicesServiceTests_678304BAB99F89CE-001/tempDir-011/data/single-node-cluster-CHILD_VM=[1]-CLUSTER_SEED=[3730156636843346220]-HASH=[2CC2E218290088]/nodes/0/_state/global-1.st]
   > 	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:316)
   > 	... 41 more
   > Caused by: java.nio.file.NoSuchFileException: /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-intake/core/build/testrun/test/J1/temp/org.elasticsearch.indices.IndicesServiceTests_678304BAB99F89CE-001/tempDir-011/data/single-node-cluster-CHILD_VM=[1]-CLUSTER_SEED=[3730156636843346220]-HASH=[2CC2E218290088]/nodes/0/_state/global-1.st
   > 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
   > 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
   > 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
   > 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
   > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newByteChannel(FilterFileSystemProvider.java:212)
   > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newByteChannel(FilterFileSystemProvider.java:212)
   > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newByteChannel(FilterFileSystemProvider.java:212)
   > 	at org.apache.lucene.mockfile.HandleTrackingFS.newByteChannel(HandleTrackingFS.java:240)
   > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newByteChannel(FilterFileSystemProvider.java:212)
   > 	at org.apache.lucene.mockfile.HandleTrackingFS.newByteChannel(HandleTrackingFS.java:240)
   > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newByteChannel(FilterFileSystemProvider.java:212)
   > 	at java.nio.file.Files.newByteChannel(Files.java:361)
   > 	at java.nio.file.Files.newByteChannel(Files.java:407)
   > 	at org.apache.lucene.store.SimpleFSDirectory.openInput(SimpleFSDirectory.java:77)
   > 	at org.elasticsearch.gateway.MetaDataStateFormat.read(MetaDataStateFormat.java:182)
   > 	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:311)
   > 	... 41 more
```

However, it does not reproduce, here's the reproduction line:

```
gradle :core:test -Dtests.seed=678304BAB99F89CE -Dtests.class=org.elasticsearch.indices.IndicesServiceTests -Dtests.method="testDeleteIndexStore" -Dtests.security.manager=true -Dtests.locale=sv-SE -Dtests.timezone=Asia/Macau
```

**Comment by abeyad** [comment]
Could be related (though not the same) as: https://github.com/elastic/elasticsearch/issues/17767

**Comment by ywelsch** [comment]
The lines that lead to the failure are
```
assertAcked(client().admin().indices().prepareDelete("test"));
meta = gwMetaState.loadMetaState();
```

To understand why this fails, it is important to know that acknowledgment of deletion can happen before the new cluster state containing the deletion has been written to disk, even if the cluster is only single-node.
Now, the way `loadMetaState` works is by listing the directory contents to find the *latest* meta state file.  Latest means state file with highest version identifier attached to it. In a second step, it tries to read the file. If the meta state file has been replaced in the meanwhile by an updated version (and the old version deleted), we try to read the file that has been deleted.

loadMetaState() is only safe to call from the cluster state update thread, the same thread where we write the state files.

To fix the test, we could add the line
```
assertBusy(() -> assertThat(client().admin().cluster().preparePendingClusterTasks().get().getPendingTasks(), empty()));
```
between the index deletion and loadMetaState(). @bleskes what do you think?

**Comment by bleskes** [comment]
I think there are two things that's wrong here:

1) Delete index should wait for both node ack and cluster publishing to complete.
2) loadMetaState() and state writign should be thread safe. It's very trappy now.  We could do through in memory locks, but file based RW locks will be better. @s1monw any thoughts here?

**Comment by ywelsch** [comment]
I've opened #18602 for the first issue.
