### ISSUE TITLE
Bug: org.elasticsearch.test.ESIntegTestCase has randomly failing shards when using excludes in terms aggregations

### ISSUE THREAD

**Issue by DavidHauger** [elastic/elasticsearch#18575]
In one of our `ESIntegTestCase`s, we set up an index, add a couple of documents and run a number of queries against these indices.
In most cases this works fine, with 1 exception: when using `exclude(String[] terms)` in a `TermsBuilder`, every now and then (not always!), some of the shards fail.
The shard settings of our `ESIntegTestCase` are not changed; so it sets up 1-10 shards.
Whether these aggregations aim at a field on root level or a nested document does not matter - we could reproduce the error in either case (just running the test often enough).
What seems to make a difference: It only happens when applying `exclude`; with `include` we have not seen failing shards yet.
We have not tested the regular expressions; only `String[]`.

two failure messages that we saw on the `SearchResponse` in `.getShardFailures()` (nested document / root document):
```
shard [[DT3n-RvATnO4NDMUrDo4BA][visit][1]], reason [RemoteTransportException[[node_s0][local[1]][indices:data/read/search[phase/query/id]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: AssertionError[startIndex=0, numBits=0]; ], cause [java.lang.AssertionError: startIndex=0, numBits=0
	at org.apache.lucene.util.LongBitSet.set(LongBitSet.java:335)
	at org.elasticsearch.search.aggregations.bucket.terms.support.IncludeExclude$TermListBackedOrdinalsFilter.acceptedGlobalOrdinals(IncludeExclude.java:179)
	at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator.getLeafCollector(GlobalOrdinalsStringTermsAggregator.java:97)
	at org.elasticsearch.search.aggregations.AggregatorBase.getLeafCollector(AggregatorBase.java:132)
	at org.elasticsearch.search.aggregations.AggregatorFactory$1$1.collect(AggregatorFactory.java:204)
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectExistingBucket(BucketsAggregator.java:80)
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectBucket(BucketsAggregator.java:72)
	at org.elasticsearch.search.aggregations.bucket.nested.ReverseNestedAggregator$1.collect(ReverseNestedAggregator.java:91)
	at org.elasticsearch.search.aggregations.LeafBucketCollector$3.collect(LeafBucketCollector.java:73)
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectExistingBucket(BucketsAggregator.java:80)
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectBucket(BucketsAggregator.java:72)
	at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregator$1.collect(FilterAggregator.java:67)
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectExistingBucket(BucketsAggregator.java:80)
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectBucket(BucketsAggregator.java:72)
	at org.elasticsearch.search.aggregations.bucket.nested.NestedAggregator$1.collect(NestedAggregator.java:118)
	at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:88)
	at org.apache.lucene.search.MultiCollector$MultiLeafCollector.collect(MultiCollector.java:174)
	at org.apache.lucene.search.AssertingLeafCollector.collect(AssertingLeafCollector.java:52)
	at org.apache.lucene.search.AssertingLeafCollector.collect(AssertingLeafCollector.java:52)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:221)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:172)
	at org.apache.lucene.search.AssertingBulkScorer.score(AssertingBulkScorer.java:79)
	at org.apache.lucene.search.AssertingBulkScorer.score(AssertingBulkScorer.java:63)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:821)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:535)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:384)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:113)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:433)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:376)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:373)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

and 

```
shard [[3TcVXShdQq6NoMcYQCwbtQ][visit][5]], reason [RemoteTransportException[[node_s0][local[1]][indices:data/read/search[phase/query]]]; nested: UncheckedExecutionException[QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: AssertionError[startIndex=0, numBits=0];]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: AssertionError[startIndex=0, numBits=0]; ], cause [com.google.common.util.concurrent.UncheckedExecutionException: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: AssertionError[startIndex=0, numBits=0];
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
	at org.elasticsearch.indices.cache.request.IndicesRequestCache.loadIntoContext(IndicesRequestCache.java:263)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:364)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:378)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: AssertionError[startIndex=0, numBits=0];
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:409)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:113)
	at org.elasticsearch.indices.cache.request.IndicesRequestCache$Loader.call(IndicesRequestCache.java:302)
	at org.elasticsearch.indices.cache.request.IndicesRequestCache$Loader.call(IndicesRequestCache.java:283)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 14 more
Caused by: java.lang.AssertionError: startIndex=0, numBits=0
	at org.apache.lucene.util.LongBitSet.set(LongBitSet.java:335)
	at org.elasticsearch.search.aggregations.bucket.terms.support.IncludeExclude$TermListBackedOrdinalsFilter.acceptedGlobalOrdinals(IncludeExclude.java:179)
	at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator.getLeafCollector(GlobalOrdinalsStringTermsAggregator.java:97)
	at org.elasticsearch.search.aggregations.AggregatorBase.getLeafCollector(AggregatorBase.java:132)
	at org.elasticsearch.search.aggregations.AggregatorFactory$1$1.collect(AggregatorFactory.java:204)
	at org.elasticsearch.search.aggregations.LeafBucketCollector$3.collect(LeafBucketCollector.java:73)
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectExistingBucket(BucketsAggregator.java:80)
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectBucket(BucketsAggregator.java:72)
	at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregator$1.collect(FilterAggregator.java:67)
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectExistingBucket(BucketsAggregator.java:80)
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectBucket(BucketsAggregator.java:72)
	at org.elasticsearch.search.aggregations.bucket.nested.NestedAggregator$1.collect(NestedAggregator.java:118)
	at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:88)
	at org.apache.lucene.search.MultiCollector$MultiLeafCollector.collect(MultiCollector.java:174)
	at org.apache.lucene.search.AssertingLeafCollector.collect(AssertingLeafCollector.java:52)
	at org.apache.lucene.search.AssertingLeafCollector.collect(AssertingLeafCollector.java:52)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:221)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:172)
	at org.apache.lucene.search.AssertingBulkScorer.score(AssertingBulkScorer.java:79)
	at org.apache.lucene.search.AssertingBulkScorer.score(AssertingBulkScorer.java:63)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:821)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:535)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:384)
	... 22 more
```
The format of the response is always the same and correct; so we can still retrieve results; however, if one or two shards fail, the numbers within the response are incorrect; some documents are missing. The easiest way to check whether it worked is to check the number of failed shards.

FYI: We are using **ElasticSearch 2.3.2**

**Comment by jpountz** [comment]
It looks to me that it can happen when all documents with a value are deleted on a shard and then merged away. Can you describe what your test case is doing?

**Comment by DavidHauger** [comment]
it creates an index, adds a couple of documents (these two steps are done in the setup which is used for a couple of tests), creates a `TermsBuilder` aggregation, sets the `exclude()` with an array of Strings, and performs a query with this `TermsBuilder` aggregation added (and processes the result for further testing).
Well, the query is a bit more complex, but we saw this "shard failing exception" only with the exclude option set; the same test with an include option always worked (we include some values in one case and excluded the others in another test - so the results should be exactly the same).
Within this test we are not deleting (or overriding) any documents. Our test case extends `ESIntegTestCase`; the failing shards are definitely not necessarily empty; because there are 1-2 documents missing in the results, that should lie on these failing shard(s).
