### ISSUE TITLE
Move useful messages from debug/trace level to warn/error

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#18576]
_From @ppf2 on June 18, 2015 23:56_

The following is an example of log entries that are very useful in troubleshooting azure discovery issues but are only available at the TRACE level:

```
[2015-06-18 23:18:57,662][TRACE][discovery.azure          ] [Baron Strucker] starting to ping
[2015-06-18 23:18:57,692][DEBUG][discovery.azure          ] [Baron Strucker] start building nodes list using Azure API
[2015-06-18 23:19:00,383][WARN ][discovery.azure          ] [Baron Strucker] can not get list of azure nodes: [can not get list of azure nodes]. Returning empty list of nodes.
[2015-06-18 23:19:00,383][TRACE][discovery.azure          ] [Baron Strucker] AzureServiceRemoteException caught
org.elasticsearch.cloud.azure.AzureServiceRemoteException: can not get list of azure nodes
	at org.elasticsearch.cloud.azure.management.AzureComputeServiceImpl.getServiceDetails(AzureComputeServiceImpl.java:100)
	at org.elasticsearch.discovery.azure.AzureUnicastHostsProvider.buildDynamicNodes(AzureUnicastHostsProvider.java:176)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPings(UnicastZenPing.java:313)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.ping(UnicastZenPing.java:219)
	at org.elasticsearch.discovery.zen.ping.ZenPingService.ping(ZenPingService.java:146)
	at org.elasticsearch.discovery.zen.ping.ZenPingService.pingAndWait(ZenPingService.java:124)
	at org.elasticsearch.discovery.zen.ZenDiscovery.findMaster(ZenDiscovery.java:996)
	at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:360)
	at org.elasticsearch.discovery.zen.ZenDiscovery.access$6100(ZenDiscovery.java:85)
	at org.elasticsearch.discovery.zen.ZenDiscovery$JoinThreadControl$1.run(ZenDiscovery.java:1373)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.microsoft.windowsazure.exception.ServiceException: BadRequest: The hosted service name is invalid.
	at com.microsoft.windowsazure.exception.ServiceException.createFromXml(ServiceException.java:216)
	at com.microsoft.windowsazure.management.compute.HostedServiceOperationsImpl.getDetailed(HostedServiceOperationsImpl.java:1740)
	at org.elasticsearch.cloud.azure.management.AzureComputeServiceImpl.getServiceDetails(AzureComputeServiceImpl.java:98)
	... 12 more
```

Can we move these to warn or error level?

And also move this one to INFO level ([2015-06-18 23:18:41,554][DEBUG][cloud.azure              ] [Baron Strucker] starting azure services?  Just to show that it is actually trying to use azure discovery? 

thx!

_Copied from original issue: elastic/elasticsearch-cloud-azure#94_

**Comment by dadoonet** [comment]
I think that at a WARN level we should probably also print the inner message: `BadRequest: The hosted service name is invalid.`
About moving to INFO level `starting azure services` or such message, I think it makes sense.

I'm going to copy this issue to elasticsearch repo.

**Comment by dadoonet** [comment]
As Azure Classic plugin is deprecated in 5.0, I'm closing this one.
