### ISSUE TITLE
2.3.3 reindex api - InvalidIndexNameException[Invalid index name [_reindex]

### ISSUE THREAD

**Issue by natelapp** [elastic/elasticsearch#18628]
**Elasticsearch version**: 2.3.3

**JVM version**: 1.8.0_91

**OS version**: Amazon Linux AMI release 2016.03

**Description of the problem including expected versus actual behavior**:

I'm attempting to use the new [reindex api] (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html) but am receiving an error `[_reindex] failed to create
[_reindex] InvalidIndexNameException[Invalid index name [_reindex], must not start with '_']`

I could be overlooking something simple, but I'm just not seeing what I'm doing wrong if that's the case.

**Steps to reproduce**:
 1.  Executed the following line: 
```
curl -XPOST 'http://es1:9200/_reindex?pretty' -d '{"source":{"index":"medr-discovery-index-v2-20160320"},"dest":{"index":"medr-discovery-index-v2-20160528","version_type":"external"}}'
```
 
**Provide logs (if relevant)**:

I'm running 2.3.3:
```
$ curl -XGET 'http://es1:9200'
{
  "name" : "es1-dev",
  "cluster_name" : "medr_elz_dev",
  "version" : {
    "number" : "2.3.3",
    "build_hash" : "218bdf10790eef486ff2c41a3df5cfa32dadcfde",
    "build_timestamp" : "2016-05-17T15:40:04Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}
```

I execute the command above and receive this error:
```
{
  "error" : {
    "root_cause" : [ {
      "type" : "invalid_index_name_exception",
      "reason" : "Invalid index name [_reindex], must not start with '_'",
      "index" : "_reindex"
    } ],
    "type" : "invalid_index_name_exception",
    "reason" : "Invalid index name [_reindex], must not start with '_'",
    "index" : "_reindex"
  },
  "status" : 400
}
```

These are the logs from the single node in this cluster:
```
[2016-05-28 17:04:43,943][INFO ][node                     ] [es1-dev] version[2.3.3], pid[9628], build[218bdf1/2016-05-17T15:40:04Z]
[2016-05-28 17:04:43,943][INFO ][node                     ] [es1-dev] initializing ...
[2016-05-28 17:04:44,928][INFO ][plugins                  ] [es1-dev] modules [], plugins [analysis-phonetic, license, analysis-kuromoji, cloud-aws, lang-fields-native, analysis-icu, marvel-agent, analysis-smartcn, hq], sites [hq]
[2016-05-28 17:04:44,958][INFO ][env                      ] [es1-dev] using [1] data paths, mounts [[/data (/dev/xvdb)]], net usable_space [476gb], net total_space [503.8gb], spins? [no], types [ext4]
[2016-05-28 17:04:44,958][INFO ][env                      ] [es1-dev] heap size [3.9gb], compressed ordinary object pointers [true]
[2016-05-28 17:04:44,958][WARN ][env                      ] [es1-dev] max file descriptors [65535] for elasticsearch process likely too low, consider increasing to at least [65536]
[2016-05-28 17:04:48,000][INFO ][node                     ] [es1-dev] initialized
[2016-05-28 17:04:48,000][INFO ][node                     ] [es1-dev] starting ...
[2016-05-28 17:04:48,157][INFO ][transport                ] [es1-dev] publish_address {10.0.2.10:9300}, bound_addresses {10.0.2.10:9300}
[2016-05-28 17:04:48,162][INFO ][discovery                ] [es1-dev] medr_elz_dev/vFYAS4mxSd68SCnF1NVY6g
[2016-05-28 17:04:58,011][INFO ][marvel.agent.exporter    ] [es1-dev] skipping exporter [default_local] as it isn't ready yet
[2016-05-28 17:05:08,011][INFO ][marvel.agent.exporter    ] [es1-dev] skipping exporter [default_local] as it isn't ready yet
[2016-05-28 17:05:18,012][INFO ][marvel.agent.exporter    ] [es1-dev] skipping exporter [default_local] as it isn't ready yet
[2016-05-28 17:05:18,165][WARN ][discovery                ] [es1-dev] waited for 30s and no initial state was set by the discovery
[2016-05-28 17:05:18,171][INFO ][http                     ] [es1-dev] publish_address {10.0.2.10:9200}, bound_addresses {10.0.2.10:9200}
[2016-05-28 17:05:18,171][INFO ][node                     ] [es1-dev] started
[2016-05-28 17:05:18,187][INFO ][cluster.service          ] [es1-dev] new_master {es1-dev}{vFYAS4mxSd68SCnF1NVY6g}{10.0.2.10}{10.0.2.10:9300}{max_local_storage_nodes=1, master=true}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2016-05-28 17:05:18,436][INFO ][license.plugin.core      ] [es1-dev] license [ac1d0ccd-9fab-43b2-8906-33b26a9b38e6] - valid
[2016-05-28 17:05:18,561][INFO ][gateway                  ] [es1-dev] recovered [13] indices into cluster_state
[2016-05-28 17:05:21,840][INFO ][cluster.routing.allocation] [es1-dev] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[indexing-metrics-v1-index-20151012][0]] ...]).
[2016-05-28 17:06:43,360][DEBUG][action.admin.indices.create] [es1-dev] [_reindex] failed to create
[_reindex] InvalidIndexNameException[Invalid index name [_reindex], must not start with '_']
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDataCreateIndexService.java:150)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validate(MetaDataCreateIndexService.java:473)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$100(MetaDataCreateIndexService.java:97)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1.execute(MetaDataCreateIndexService.java:192)
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by ywelsch** [comment]
It seems that the `reindex` module is missing from your ES installation:

```
[2016-05-28 17:04:44,928][INFO ][plugins                  ] [es1-dev] modules [], plugins [analysis-phonetic, license, analysis-kuromoji, cloud-aws, lang-fields-native, analysis-icu, marvel-agent, analysis-smartcn, hq], sites [hq]
```

On a fresh installation of ES the log line looks as follows:

```
[2016-05-29 10:07:51,699][INFO ][plugins                  ] [Android Man] modules [reindex, lang-expression, lang-groovy], plugins [], sites []
```

We bundle reindex and the other listed modules by default (in a directory `modules` under your ES installation). How did you install ES?

**Comment by natelapp** [comment]
Ah.  I didn't realize that those were handled separately and packaged under a `modules` directory, which we aren't accounting for in our installation.   Sorry for the misreport -- I appreciate your help with figuring this out.

**Comment by nik9000** [comment]
Sorry for the confusion!
On May 29, 2016 7:01 AM, "natelapp" <notifications@github.com> wrote:

Ah. I didn't realize that those were handled separately and packaged under
a modules directory, which we aren't accounting for in our installation.
Sorry for the misreport -- I appreciate your help with figuring this out.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/elastic/elasticsearch/issues/18628#issuecomment-222354736>,
or mute the thread
<https://github.com/notifications/unsubscribe/AANLotKUwX-Q0kn4WxVMxGy15Gs0ot9fks5qGXHsgaJpZM4IpIAC>
.
