### ISSUE TITLE
Disable compression when talking to a local node

### ISSUE THREAD

**Issue by burtonator** [elastic/elasticsearch#18629]
We are testing re-indexing data on an Elasticsearch 2.3.3 instance (latest at the time).

I'm trying to find all bottlenecks to improve indexing and noticed the attached exception (see below)

Compression shouldn't be used when talking to the local node.  There's no real benefit in having this as there's no speedup due to very high bandwidth.  Additionally, it doesn't even speed up switch throughput as switches aren't involved.

It would be ideal to disable compression when talking to the local host and would avoid wasted compression/decompression for next to no benefit.  

```
        at java.util.zip.Deflater.deflateBytes(Native Method)
        at java.util.zip.Deflater.deflate(Deflater.java:444)
        - locked <0xXXXXXXXXXXXXXXXX> (a java.util.zip.ZStreamRef)
        at java.util.zip.Deflater.deflate(Deflater.java:366)
        at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:251)
        at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
        - locked <0xXXXXXXXXXXXXXXXX> (a java.io.BufferedOutputStream)
        at org.elasticsearch.common.io.stream.OutputStreamStreamOutput.writeBytes(OutputStreamStreamOutput.java:42)
        at org.elasticsearch.common.io.stream.StreamOutput.write(StreamOutput.java:299)
        at org.jboss.netty.buffer.HeapChannelBuffer.getBytes(HeapChannelBuffer.java:111)
        at org.elasticsearch.common.bytes.ChannelBufferBytesReference.writeTo(ChannelBufferBytesReference.java:64)
        at org.elasticsearch.common.io.stream.StreamOutput.writeBytesReference(StreamOutput.java:127)
        at org.elasticsearch.action.index.IndexRequest.writeTo(IndexRequest.java:732)
        at org.elasticsearch.action.bulk.BulkRequest.writeTo(BulkRequest.java:546)
        at org.elasticsearch.transport.netty.NettyTransport.sendRequest(NettyTransport.java:863)
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:329)
        at org.elasticsearch.action.TransportActionNodeProxy.execute(TransportActionNodeProxy.java:51)
        at org.elasticsearch.client.transport.support.TransportProxyClient$1.doWithNode(TransportProxyClient.java:58)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:212)
        at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56)

```

**Comment by bobrik** [comment]
I'm looking into why 2.4 is recovering shards slowly and hot threads report:

```
::: {mynode}{MFzED4YTQuy-24wahqqeow}{10.36.19.17}{10.36.19.17:9305}{rack_id=111, master=false}
   Hot threads at 2017-06-28T03:13:37.323Z, interval=5s, busiestThreads=3, ignoreIdleThreads=true:

   24.4% (1.2s out of 5s) cpu usage by thread 'elasticsearch[mynode][[http_server_worker.default]][T#52]{New I/O worker #117}'
     7/10 snapshots sharing following 7 elements
       org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
       org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
       org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
       org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)

   23.5% (1.1s out of 5s) cpu usage by thread 'elasticsearch[mynode][[http_server_worker.default]][T#54]{New I/O worker #119}'
     2/10 snapshots sharing following 38 elements
       java.util.zip.Inflater.inflateBytes(Native Method)
       java.util.zip.Inflater.inflate(Inflater.java:259)
       java.util.zip.InflaterInputStream.read(InflaterInputStream.java:152)
       java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
       java.io.BufferedInputStream.read(BufferedInputStream.java:345)
       org.elasticsearch.common.io.Streams.readFully(Streams.java:216)
       org.elasticsearch.common.io.stream.InputStreamStreamInput.readBytes(InputStreamStreamInput.java:51)
       org.elasticsearch.common.io.stream.FilterStreamInput.readBytes(FilterStreamInput.java:44)
       org.elasticsearch.common.io.stream.StreamInput.readBytesReference(StreamInput.java:98)
       org.elasticsearch.common.io.stream.StreamInput.readBytesReference(StreamInput.java:86)
       org.elasticsearch.indices.recovery.RecoveryFileChunkRequest.readFrom(RecoveryFileChunkRequest.java:109)
       org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:222)
       org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:116)
       org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
       org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
       org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
       org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
       org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
       org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
       org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)
       org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
       org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
       org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
       org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
       org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
       org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
       org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
       org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
       org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
       org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
       org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
       org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
       org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
       org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
       org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)
     5/10 snapshots sharing following 15 elements
       sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
       sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
       sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
       sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
       sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
       org.jboss.netty.channel.socket.nio.SelectorUtil.select(SelectorUtil.java:68)
       org.jboss.netty.channel.socket.nio.AbstractNioSelector.select(AbstractNioSelector.java:434)
       org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:212)
       org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
       org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
       org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
       org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)

   19.8% (991.4ms out of 5s) cpu usage by thread 'elasticsearch[mynode][[http_server_worker.default]][T#64]{New I/O worker #129}'
     2/10 snapshots sharing following 38 elements
       java.util.zip.Inflater.inflateBytes(Native Method)
       java.util.zip.Inflater.inflate(Inflater.java:259)
       java.util.zip.InflaterInputStream.read(InflaterInputStream.java:152)
       java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
       java.io.BufferedInputStream.read(BufferedInputStream.java:345)
       org.elasticsearch.common.io.Streams.readFully(Streams.java:216)
       org.elasticsearch.common.io.stream.InputStreamStreamInput.readBytes(InputStreamStreamInput.java:51)
       org.elasticsearch.common.io.stream.FilterStreamInput.readBytes(FilterStreamInput.java:44)
       org.elasticsearch.common.io.stream.StreamInput.readBytesReference(StreamInput.java:98)
       org.elasticsearch.common.io.stream.StreamInput.readBytesReference(StreamInput.java:86)
       org.elasticsearch.indices.recovery.RecoveryFileChunkRequest.readFrom(RecoveryFileChunkRequest.java:109)
       org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:222)
       org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:116)
       org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
       org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
       org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
       org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
       org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
       org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
       org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)
       org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
       org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
       org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
       org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
       org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
       org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
       org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
       org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
       org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
       org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
       org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
       org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
       org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
       org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
       org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)
     7/10 snapshots sharing following 15 elements
       sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
       sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
       sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
       sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
       sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
       org.jboss.netty.channel.socket.nio.SelectorUtil.select(SelectorUtil.java:68)
       org.jboss.netty.channel.socket.nio.AbstractNioSelector.select(AbstractNioSelector.java:434)
       org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:212)
       org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
       org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
       org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
       org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)
     unique snapshot
       org.jboss.netty.buffer.HeapChannelBuffer.<init>(HeapChannelBuffer.java:42)
       org.jboss.netty.buffer.BigEndianHeapChannelBuffer.<init>(BigEndianHeapChannelBuffer.java:34)
       org.jboss.netty.buffer.ChannelBuffers.buffer(ChannelBuffers.java:134)
       org.jboss.netty.buffer.HeapChannelBufferFactory.getBuffer(HeapChannelBufferFactory.java:68)
       org.jboss.netty.buffer.AbstractChannelBufferFactory.getBuffer(AbstractChannelBufferFactory.java:48)
       org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:80)
       org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
       org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
       org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
       org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
       org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
       org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)
```

ES itself is saturating 1 CPU when there are 32 idle CPUs in the system. With 2x10G network it makes very little sense to compress.
