### ISSUE TITLE
Cloud azure plugin crashes on start

### ISSUE THREAD

**Issue by Burgov** [elastic/elasticsearch#18637]
**Elasticsearch version**:
2.3

**JVM version**:
1.8.0_91-b14

**OS version**:
Ubuntu 16.04

**Description of the problem including expected versus actual behavior**:
I have the following config:

```
discovery:
    type: azure

cloud:
    azure:
        management:
             subscription.id: [...]
             cloud.service.name: [...]
             keystore:
                   path: /home/elasticsearch/azurekeystore.pkcs12
                   password: [...]
                   type: pkcs12
```

Now when I try to start elasticsearch it fails and I find the following error in the logs:

```
[2016-05-30 12:59:49,219][ERROR][bootstrap                ] Guice Exception: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getClassLoader")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.ClassLoader.checkClassLoaderPermission(ClassLoader.java:1528)
        at java.lang.Thread.getContextClassLoader(Thread.java:1436)
        at com.microsoft.windowsazure.Configuration.load(Configuration.java:104)
        at com.microsoft.windowsazure.Configuration.getInstance(Configuration.java:90)
        at com.microsoft.windowsazure.management.configuration.ManagementConfiguration.configure(ManagementConfiguration.java:134)
        at org.elasticsearch.cloud.azure.management.AzureComputeServiceImpl.<init>(AzureComputeServiceImpl.java:75)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at <<<guice>>>
        at org.elasticsearch.node.Node.<init>(Node.java:213)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

any idea what I'm doing wrong here?
If I leave out the pasted piece of the config, elastic fires up just fine.

**Comment by dadoonet** [comment]
Just want to make sure: are you using elasticsearch 2.3.2 or another version?

**Comment by Burgov** [comment]
@dadoonet  it's v2.3.3

**Comment by dadoonet** [comment]
So I'm able to reproduce it. I'll create a PR for this and hopefully I'll give a workaround for it.

**Comment by Burgov** [comment]
Thanks! Curious to see the PR to learn what causes it
