### ISSUE TITLE
AWS IAM role not working with Elasticsearch 5.0.0-alpha2, but works with 2.3 version

### ISSUE THREAD

**Issue by randhirkr** [elastic/elasticsearch#18652]
**Elasticsearch version**:  5.0.0-alpha2

**JVM version**: 1.8.0_91(1.8.0_91-b14)

**OS version**: Red Hat Enterprise Linux 7.2 (3.10.0-327.18.2.el7.x86_64)

**Description of the problem including expected versus actual behavior**:
I am trying to use AWS IAM role with Elasticsearch 5.0.0-alpha2 and EC2 discovery plug-in, but it does not seem to be working and I am getting below error:

> "Exception while retrieving instance list from AWS API: Authorization header or parameters are not formatted correctly. (Service: AmazonEC2; Status Code: 401; Error Code: AuthFailure"

I am using below configuration with jdk8:

> cluster.name: "test-cluster"
> cloud.aws.region: "us-west-2"
> cloud.aws.ec2.region: "us-west-2"
> cloud.aws.ec2.protocol: "http"
> discovery.type: "ec2"
> #bootstrap.mlockall: true
> node.master: true
> node.data: false
> node.name: ${HOSTNAME}-Master
> discovery.zen.minimum_master_nodes: 1
> network.host: ec2:privateIp
> discovery.ec2.any_group: true
> discovery.ec2.groups : sg-9d856tfe

And, below is IAM role permission that I have configured with elasticsearch instance:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "ec2:Describe*"
            ],
            "Effect": "Allow",
            "Resource": [
                "*"
            ]
        }
    ]
}
```

However, same configuration works fine with with Elasticsearch 2.3 version. Has anyone faced the same issue with the latest Elasticsearch version 5.0.0-alpha2?

Also, today I enabled the debug mode of AWS call and I could notice(see below) that its loading credentials from **StaticCredentialsProvider** - its wrong behavior. As access and secret key is absent in the config(elasticsearch.yml) file, so ideally it should load credential from **InstanceProfileCredentialsProvider**.

> [DEBUG][com.amazonaws.auth.AWSCredentialsProviderChain] Loading credentials from com.amazonaws.internal.StaticCredentialsProvider@40bf7b26

**Steps to reproduce**:
 1. Start elasticsearch master data node with the above mentioned configuration.

**Provide logs (if relevant)**:
```
com.amazonaws.AmazonServiceException: Authorization header or parameters are not formatted correctly. (Service: AmazonEC2; Status Code: 401; Error Code: AuthFailure; Request ID: )
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1239)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:823)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
        at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:11901)
        at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:5940)
        at org.elasticsearch.discovery.ec2.AwsEc2UnicastHostsProvider.fetchDynamicNodes(AwsEc2UnicastHostsProvider.java:117)
        at org.elasticsearch.discovery.ec2.AwsEc2UnicastHostsProvider$DiscoNodesCache.refresh(AwsEc2UnicastHostsProvider.java:232)
        at org.elasticsearch.discovery.ec2.AwsEc2UnicastHostsProvider$DiscoNodesCache.refresh(AwsEc2UnicastHostsProvider.java:217)
        at org.elasticsearch.common.util.SingleObjectCache.getOrRefresh(SingleObjectCache.java:54)
        at org.elasticsearch.discovery.ec2.AwsEc2UnicastHostsProvider.buildDynamicNodes(AwsEc2UnicastHostsProvider.java:103)
        at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPings(UnicastZenPing.java:344)
        at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.ping(UnicastZenPing.java:249)
        at org.elasticsearch.discovery.zen.ping.ZenPingService.ping(ZenPingService.java:106)
        at org.elasticsearch.discovery.zen.ping.ZenPingService.pingAndWait(ZenPingService.java:84)
        at org.elasticsearch.discovery.zen.ZenDiscovery.findMaster(ZenDiscovery.java:845)
        at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:376)
        at org.elasticsearch.discovery.zen.ZenDiscovery.access$4500(ZenDiscovery.java:89)
        at org.elasticsearch.discovery.zen.ZenDiscovery$JoinThreadControl$1.run(ZenDiscovery.java:1166)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:392)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by randhirkr** [comment]
Thanks Alex for fixing this issue. Looks like that was the issue even though key was empty, but not null, it was going to else flow and looking for credentials in **StaticCredentialsProvider**.

Let me re-install the **discovery-ec2** plug-in and test this. I will let you know, if any issue. Thanks again.

**Comment by randhirkr** [comment]
Hi Alex,
How can I test your fix? I have removed the discovery-ec2 plug-in and installed again(as shown below), but getting the same error as above.

> bin/elasticsearch-plugin remove discovery-ec2
> bin/elasticsearch-plugin install discovery-ec2

Can you please help me here so that I can get the latest change w.r.t. discovery-ec2 plug-in? Thanks.

**Comment by dadoonet** [comment]
Thanks a lot @randhirkr. I added you to the pioneer program.

**Comment by dexterous** [comment]
@dadoonet do we have to be added to the pioneer program to get these fixes? If so, I'd like to get on too as I'm facing this issue as well. Also, what additional configuration will I have to setup WRT the pioneer program? Thanks.

**Comment by clintongormley** [comment]
@dexterous see https://www.elastic.co/blog/elastic-pioneer-program

**Comment by Gmanweb** [comment]
I am having the exact same problem, what is the fix.
