### ISSUE TITLE
Getting a null_pointer_exception when executing suggest

### ISSUE THREAD

**Issue by Popo-lth** [elastic/elasticsearch#18657]
**Elasticsearch version**:
2.3.2
**JVM version**:
1.8.0_73
**OS version**:
CentOS release 6.6 (Final)
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
https://www.elastic.co/guide/en/elasticsearch/reference/2.3/suggester-context.html
 1.

```
PUT services/_mapping/service
{
    "service": {
        "properties": {
            "name": {
                "type" : "string"
            },
            "tag": {
                "type" : "string"
            },
            "suggest_field": {
                "type": "completion",
                "context": {
                    "color": { 
                        "type": "category",
                        "path": "color_field",
                        "default": ["red", "green", "blue"]
                    },
                    "location": { 
                        "type": "geo",
                        "precision": "5m",
                        "neighbors": true,
                        "default": "u33"
                    }
            }
        }
    }
    }
}
```

 2.

```
PUT services/service/1
{
    "name": "knapsack",
    "suggest_field": {
        "input": ["knacksack", "backpack", "daypack"],
        "context": {
            "color": ["red", "yellow"]
            }
        }
}
```

 3.

```
POST services/_suggest?pretty'
{
    "suggest" : {
        "text" : "m",
        "completion" : {
            "field" : "suggest_field",
            "size": 10,
            "context": {
                "color": "red"
            }
        }
    }
}
```

**The response I'm getting is:**

```
{
  "_shards": {
    "total": 5,
    "successful": 4,
    "failed": 1,
    "failures": [
      {
        "shard": 3,
        "index": "services",
        "status": "INTERNAL_SERVER_ERROR",
        "reason": {
          "type": "exception",
          "reason": "failed to execute suggest",
          "caused_by": {
            "type": "null_pointer_exception",
            "reason": null
          }
        }
      }
    ]
  }
}
```

**Provide logs (if relevant)**:

```
RemoteTransportException[[192.168.1.100-node2][192.168.1.100:29300][indices:data/read/suggest[s]]]; nested: ElasticsearchException[failed to execute suggest]; nested: NullPointerException;
Caused by: ElasticsearchException[failed to execute suggest]; nested: NullPointerException;
        at org.elasticsearch.action.suggest.TransportSuggestAction.shardOperation(TransportSuggestAction.java:152)
        at org.elasticsearch.action.suggest.TransportSuggestAction.shardOperation(TransportSuggestAction.java:61)
        at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$ShardTransportHandler.messageReceived(TransportBroadcastAction.java:282)
        at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$ShardTransportHandler.messageReceived(TransportBroadcastAction.java:278)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:300)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.elasticsearch.search.suggest.context.ContextMapping$ContextQuery.toAutomaton(ContextMapping.java:264)
        at org.elasticsearch.search.suggest.completion.AnalyzingCompletionLookupProvider$2.getLookup(AnalyzingCompletionLookupProvider.java:279)
        at org.elasticsearch.search.suggest.completion.Completion090PostingsFormat$CompletionTerms.getLookup(Completion090PostingsFormat.java:264)
        at org.elasticsearch.search.suggest.completion.CompletionSuggester.innerExecute(CompletionSuggester.java:69)
        at org.elasticsearch.search.suggest.completion.CompletionSuggester.innerExecute(CompletionSuggester.java:44)
        at org.elasticsearch.search.suggest.Suggester.execute(Suggester.java:41)
        at org.elasticsearch.search.suggest.SuggestPhase.execute(SuggestPhase.java:85)
        at org.elasticsearch.action.suggest.TransportSuggestAction.shardOperation(TransportSuggestAction.java:147)
        ... 9 more

```

https://github.com/elastic/elasticsearch/blob/v2.3.2/core/src/main/java/org/elasticsearch/search/suggest/context/ContextMapping.java : 308

```
            List<ContextQuery> queries = new ArrayList<>(mappings.size());
            for (ContextMapping mapping : mappings.values()) {
                queries.add(querySet.get(mapping.name));
            }
```

Not checked  "querySet.get(mapping.name)" equal to null

**Comment by s1monw** [comment]
that seems like a bug not checking this, would you be willing to submit a pullrequest to fix this? The analysis of the problem looks awesome and we are happy to guide you to fix the problem? @areek what do you think?

**Comment by robacarp** [comment]
I ran across the same error but it took me a while to understand what I could do to resolve the issue until the patch comes through. In the example from @areek, the `service` suggest field has two contexts: color and location. The suggest query only specifies the color context and not the location context.

My new understanding of the design is: Queries against the `_suggest` endpoint must specify all contexts defined in the suggester.  

Hope that helps!

**Comment by robacarp** [comment]
It's also worth noting that the example code given [in the official docs](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/suggester-context.html#_category_query) triggers this bug.

**Comment by sergbass** [comment]
> My new understanding of the design is: Queries against the _suggest endpoint must specify all contexts defined in the suggester. 

@robacarp, I think that it would be more convenient to allow specifying less categories/contexts that indexed field has. In my case, I need to suggest hotels by name, and I have several cases:

1. Suggest hotel name that's found by current search
2. Suggest hotel by selected area
3. Suggest hotel by selected city
4. More combinations possible in future

Currently I added all these parameters as separate categories to one suggest field. If we do like you proposed, I'll need to create separate suggest fields to every usage case. Other workaround in my case would be to add just one category with values like "city-1234", "area-4321", etc., by it seems to eliminate category idea.

**Comment by clintongormley** [comment]
@sergbass in 5.0 the completion suggester has been completely rewritten and supports the functionality you suggest

**Comment by jimczi** [comment]
The completion suggester has been rewritten in 5 and the same recreation would now yield to no result. I am closing this since we don't have release on 2.x anymore.
