### ISSUE TITLE
Elasticsearch 5.0 (5.0.0-alpha2) Disable multicast - unknown setting error

### ISSUE THREAD

**Issue by dayjavid** [elastic/elasticsearch#18686]
**Elasticsearch version**:
5.0.0-alpha2

**JVM version**:
openjdk version "1.8.0_51"
OpenJDK Runtime Environment (build 1.8.0_51-b16)
OpenJDK 64-Bit Server VM (build 25.51-b03, mixed mode)

**OS version**:
uname -a
Linux ***** 2.6.32-504.8.1.el6.centos.plus.x86_64 # 1 SMP Wed Jan 28 20:58:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

```
Exception in thread "main" java.lang.IllegalArgumentException: unknown setting [discovery.zen.ping.multicast.enabled]
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:267)
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:238)
        at org.elasticsearch.common.settings.SettingsModule.configure(SettingsModule.java:120)
        at <<<guice>>>
        at org.elasticsearch.node.Node.<init>(Node.java:235)
        at org.elasticsearch.node.Node.<init>(Node.java:161)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:188)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:188)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:267)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:111)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:106)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:91)
        at org.elasticsearch.cli.Command.main(Command.java:53)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)
Refer to the log for complete error details.
```

I am attempting to disable multicast using methods defined from previous versions. Searches did not turn up any results on this. 

**Steps to reproduce**:
 1. Setting in  elasticsearch.yml config file: `discovery.zen.ping.multicast.enabled: false`

**Comment by clintongormley** [comment]
Hi @dayjavid 

Multicast was only available as a plugin from 2.0 onwards, and that plugin was removed in 5.0, so the setting no longer applies

**Comment by dayjavid** [comment]
I was under the impression that disabling multicast was recommended, especially on larger networks. 

Is that not true anymore? Or are there other ways to accomplish what that was trying to achieve?

**Comment by clintongormley** [comment]
Multicast no longer exists.  Only unicast.

**Comment by dayjavid** [comment]
Ahh ok. Understood. Thanks much!

**Comment by mcxu** [comment]
What should be the configuration for unicast? Also, is there a page with documentation for the configurations? Thanks!

**Comment by jasontedor** [comment]
> What should be the configuration for unicast? Also, is there a page with documentation for the configurations?

@mcxu The [docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/modules-discovery-zen.html) you're looking for cover your first question. If you have additional questions, please use the [forum](https://discuss.elastic.co); Elastic reserves GitHub for verified bug reports and feature requests.
