### ISSUE TITLE
node.client: false setting not allowed

### ISSUE THREAD

**Issue by ajaybhatnagar** [elastic/elasticsearch#18704]
**Elasticsearch version**:
5.0.0 Alpha 3
**JVM version**:
1.8.0-092
**OS version**:
Ubuntu 3.16.0-71-lowlatency
**Description of the problem including expected versus actual behavior**:
Node startup error with node type setting

**Steps to reproduce**:
 Elasticsearch.yml should have attribute set in elasticsearch.yml. 

**Provide logs (if relevant)**:

[2016-06-02 18:45:17,147][ERROR][bootstrap                ] Exception
java.lang.IllegalArgumentException: unknown setting [node.client]
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:267)
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:238)
        at org.elasticsearch.common.settings.SettingsModule.configure(SettingsModule.java:125)
        at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
        at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:233)
        at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:103)
        at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:148)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:46)
        at org.elasticsearch.node.Node.<init>(Node.java:249)
        at org.elasticsearch.node.Node.<init>(Node.java:162)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:180)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:180)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:255)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:96)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:91)
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:91)
        at org.elasticsearch.cli.Command.main(Command.java:53)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:70)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:63)
        Suppressed: java.lang.IllegalArgumentException: unknown setting [path.work]

**Comment by jasontedor** [comment]
The `node.client` setting was removed in #16963 and is covered in the [breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_settings_changes.html#_node_types_settings) documentation.
