### ISSUE TITLE
org.elasticsearch.index.IndexWithShadowReplicasIT fails to delete index directory

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#18743]
Build URL:
http://build-us-00.elastic.co/job/es_core_2x_window-2012/945/testReport/junit/junit.framework/TestSuite/org_elasticsearch_index_IndexWithShadowReplicasIT/

failure:

```
java.io.IOException: Could not remove the following files (in the order of attempts):
   Y:\jenkins\workspace\es_core_2x_window-2012\core\target\J0\temp\org.elasticsearch.index.IndexWithShadowReplicasIT_6DC4FBD8628375FD-001\tempDir-024\test\3\index\_1.cfs: java.nio.file.AccessDeniedException: Y:\jenkins\workspace\es_core_2x_window-2012\core\target\J0\temp\org.elasticsearch.index.IndexWithShadowReplicasIT_6DC4FBD8628375FD-001\tempDir-024\test\3\index\_1.cfs
   Y:\jenkins\workspace\es_core_2x_window-2012\core\target\J0\temp\org.elasticsearch.index.IndexWithShadowReplicasIT_6DC4FBD8628375FD-001\tempDir-024\test\3\index\_0.cfs: java.nio.file.AccessDeniedException: Y:\jenkins\workspace\es_core_2x_window-2012\core\target\J0\temp\org.elasticsearch.index.IndexWithShadowReplicasIT_6DC4FBD8628375FD-001\tempDir-024\test\3\index\_0.cfs
   Y:\jenkins\workspace\es_core_2x_window-2012\core\target\J0\temp\org.elasticsearch.index.IndexWithShadowReplicasIT_6DC4FBD8628375FD-001\tempDir-024\test\3\index: java.nio.file.DirectoryNotEmptyException: Y:\jenkins\workspace\es_core_2x_window-2012\core\target\J0\temp\org.elasticsearch.index.IndexWithShadowReplicasIT_6DC4FBD8628375FD-001\tempDir-024\test\3\index
   Y:\jenkins\workspace\es_core_2x_window-2012\core\target\J0\temp\org.elasticsearch.index.IndexWithShadowReplicasIT_6DC4FBD8628375FD-001\tempDir-024\test\3: java.nio.file.DirectoryNotEmptyException: Y:\jenkins\workspace\es_core_2x_window-2012\core\target\J0\temp\org.elasticsearch.index.IndexWithShadowReplicasIT_6DC4FBD8628375FD-001\tempDir-024\test\3

    at org.apache.lucene.util.IOUtils.rm(IOUtils.java:295)
    at org.elasticsearch.env.NodeEnvironment.deleteShardDirectoryUnderLock(NodeEnvironment.java:403)
    at org.elasticsearch.indices.IndicesService.deleteShardStore(IndicesService.java:556)
    at org.elasticsearch.index.IndexService.onShardClose(IndexService.java:502)
    at org.elasticsearch.index.IndexService.access$200(IndexService.java:76)
    at org.elasticsearch.index.IndexService$StoreCloseListener.handle(IndexService.java:528)
    at org.elasticsearch.index.IndexService$StoreCloseListener.handle(IndexService.java:513)
    at org.elasticsearch.index.store.Store.closeInternal(Store.java:363)
    at org.elasticsearch.index.store.Store.access$000(Store.java:87)
    at org.elasticsearch.index.store.Store$1.closeInternal(Store.java:108)
    at org.elasticsearch.common.util.concurrent.AbstractRefCounted.decRef(AbstractRefCounted.java:64)
    at org.elasticsearch.index.store.Store.decRef(Store.java:345)
    at org.elasticsearch.index.store.Store.close(Store.java:353)
    at org.elasticsearch.index.IndexService.closeShardInjector(IndexService.java:457)
    at org.elasticsearch.index.IndexService.removeShard(IndexService.java:416)
    at org.elasticsearch.index.IndexService.close(IndexService.java:252)
    at org.elasticsearch.indices.IndicesService.removeIndex(IndicesService.java:413)
    at org.elasticsearch.indices.IndicesService.deleteIndex(IndicesService.java:478)
    at org.elasticsearch.indices.cluster.IndicesClusterStateService.deleteIndex(IndicesClusterStateService.java:732)
    at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyDeletedIndices(IndicesClusterStateService.java:225)
    at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:162)
    at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:610)
    at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

reproduce URL:

```
mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch:elasticsearch -Dtests.seed=6DC4FBD8628375FD -Dtests.class=org.elasticsearch.index.IndexWithShadowReplicasIT -Des.logger.level=DEBUG -Dtests.nightly=false -Dtests.client.ratio=0.0 -Dtests.heap.size=512m -Des.node.mode=local -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:+UseCompressedOops -XX:+AggressiveOpts -Djava.net.preferIPv4Stack=true" -Dtests.locale=en-US -Dtests.timezone=UTC
```

**Comment by colings86** [comment]
@dakrone is this something you can look into?

**Comment by dakrone** [comment]
Shadow replicas have been removed and this is no longer applicable
