### ISSUE TITLE
Fails to bootstrap

### ISSUE THREAD

**Issue by Hirurg103** [elastic/elasticsearch#18761]
**2.3.0**:

**OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)**:

**Ubuntu 16.04 x64**:

**Elasticsearch fails to start**:

I installed java9, elasticsearch 2.3.0 under non-root (elasticserch) user.
I gave the user sudo privileges

When I try to access elasticsearch I get 

```bash
 curl localhost:9200/_cat/aliases
```
curl: (7) Failed to connect to localhost port 9200: Connection refused

This is what I see in the /var/log/elasticsearch/elasticsearch.log

`[2016-06-07 03:00:26,614][WARN ][env                      ] [Ape-X] max file descriptors [65535] for elasticsearch process likely too low, consider increasing to at least [65536]
[2016-06-07 03:00:26,663][ERROR][bootstrap                ] Exception
java.lang.Error: java.security.AccessControlException: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")
        at com.twitter.jsr166e.Striped64.<clinit>(Striped64.java:319)
        at org.elasticsearch.common.metrics.CounterMetric.<init>(CounterMetric.java:28)
        at org.elasticsearch.common.util.concurrent.EsAbortPolicy.<init>(EsAbortPolicy.java:30)
        at org.elasticsearch.common.util.concurrent.EsExecutors.newFixed(EsExecutors.java:80)
        at org.elasticsearch.threadpool.ThreadPool.rebuild(ThreadPool.java:482)
        at org.elasticsearch.threadpool.ThreadPool.build(ThreadPool.java:400)
        at org.elasticsearch.threadpool.ThreadPool.<init>(ThreadPool.java:232)
        at org.elasticsearch.node.Node.<init>(Node.java:170)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.security.AccessControlException: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")
        at java.security.AccessControlContext.checkPermission(java.base@9-internal/AccessControlContext.java:468)
        at java.security.AccessController.checkPermission(java.base@9-internal/AccessController.java:894)
        at java.lang.SecurityManager.checkPermission(java.base@9-internal/SecurityManager.java:541)
        at java.lang.reflect.AccessibleObject.checkPermission(java.base@9-internal/AccessibleObject.java:74)
        at java.lang.reflect.Field.setAccessible(java.base@9-internal/Field.java:163)
        at com.twitter.jsr166e.Striped64$1.run(Striped64.java:340)
        at com.twitter.jsr166e.Striped64$1.run(Striped64.java:336)
        at java.security.AccessController.doPrivileged(java.base@9-internal/Native Method)
        at com.twitter.jsr166e.Striped64.getUnsafe(Striped64.java:335)
        at com.twitter.jsr166e.Striped64.<clinit>(Striped64.java:312)
        ... 12 more
`

I googled this issue, but could not find the fix. Could you give me some clue on how to fix it please?

**Comment by clintongormley** [comment]
Hi @Hirurg103 

It's quite likely that 2.x won't work with Java9.  Could you try with Java8 and see what happens?

**Comment by Hirurg103** [comment]
Ok @clintongormley. Don't have my working machine with me, I will try Java8 in 3-4 hours

**Comment by jasontedor** [comment]
I think it should work fine, but can you please try a more recent build of JDK 9; that build that you're using is old in a world of at-least weekly EA builds.

**Comment by Hirurg103** [comment]
@clintongormley I installed java 8 and elastic works fine now. Thank you very much for the help! @jasontedor I will try to install elastic 2.3 with the latest version of JDK 9

**Comment by jasontedor** [comment]
Thanks @Hirurg103. I think that we can close this issue then? Please let me know if you think otherwise.
