### ISSUE TITLE
Add whitelisted classes groovy.json.JSONOutput 

### ISSUE THREAD

**Issue by rvalenciano** [elastic/elasticsearch#18807]
**Elasticsearch version**: 2.3

**JVM version**:  openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

**OS version**: centOS 7

**Description of the problem including expected versus actual behavior**:

I'm having the exact same issue of this [thread](https://discuss.elastic.co/t/webhook-action-hits-collection-not-json/24568): Basically watcher ctx is giving me a java.util.HashMap object and I need a json object.

So, I try to implement the solution but I get the error described in the log section (Summarizing, ScriptException[failed to run inline script [return [ body: groovy.json.JsonOutput.toJson(ctx  .payload.hits.hits)]] using lang [groovy]]; nested: MissingPropertyException[No such property: groovy for class). 

Doing more research, I found this [page](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-security.html) about the security feature of whitelisting classes. I guess i can whitelist in my classloader whitelist in the java security policy, but why not producing json output from elasticsearch scripting for default?

**Steps to reproduce**:

1. Using sense, create a watch like [this](https://gist.github.com/rvalenciano/db701603a1df6051dd9315da64505f8f):

**Provide logs (if relevant)**:

The error is described here;

`[2016-06-09 11:12:09,191][INFO ][cluster.metadata         ] [Tower] [.watch_history-2016.06.09] update_mapping [watch_record]
[2016-06-09 11:12:19,102][ERROR][watcher.transform.script ] [Tower] failed to execute [script] transform for [running_process_watch_1-2016-06-09T17:12:19.083Z]
ScriptException[failed to run inline script [return [ body: groovy.json.JsonOutput.toJson(ctx  .payload.hits.hits)]] using lang [groovy]]; nested: MissingPropertyException[No such property: groovy for class: 703695e74fadee477a3e905ccc4a47d0c085cf47];
	at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript.run(GroovyScriptEngineService.java:320)
	at org.elasticsearch.watcher.transform.script.ExecutableScriptTransform.doExecute(ExecutableScriptTransform.java:74)
	at org.elasticsearch.watcher.transform.script.ExecutableScriptTransform.execute(ExecutableScriptTransform.java:60)
	at org.elasticsearch.watcher.transform.script.ExecutableScriptTransform.execute(ExecutableScriptTransform.java:41)
	at org.elasticsearch.watcher.execution.ExecutionService.executeInner(ExecutionService.java:378)
	at org.elasticsearch.watcher.execution.ExecutionService.execute(ExecutionService.java:273)
	at org.elasticsearch.watcher.execution.ExecutionService$WatchExecutionTask.run(ExecutionService.java:438)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: groovy.lang.MissingPropertyException: No such property: groovy for class: 703695e74fadee477a3e905ccc4a47d0c085cf47
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.vmplugin.v7.IndyGuardsFiltersAndSignatures.unwrap(IndyGuardsFiltersAndSignatures.java:177)
	at 703695e74fadee477a3e905ccc4a47d0c085cf47.run(703695e74fadee477a3e905ccc4a47d0c085cf47:1)
	at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript$1.run(GroovyScriptEngineService.java:313)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript.run(GroovyScriptEngineService.java:310) 
`

**Describe the feature**:

Is there any possibility for whitelisting groovy.json.JSONOutput in the default class wishlist? An example of this is in this [fork](https://github.com/rmuir/elasticsearch/commit/79467a138a0f435ff3776216aa8df0364787ad00).

**Comment by jasontedor** [comment]
The Groovy dependency has been reduced from the `groovy-all` artifact to `groovy` (just the core). The class `groovy.json.JsonOutput` is no longer available with the `lang-groovy` module so we will not be whitelisting this class. 

Relates #16858

**Comment by rvalenciano** [comment]
@jasontedor , quick question, any other possible way to retrieve a json instead of a java.util.HashMap response from watcher ctx? Or do I have to program using groovy core a parser from HashMap to json?

**Comment by jasontedor** [comment]
@rvalenciano I think that it's best to ask that question on the [Elastic Discourse forums](https://discuss.elastic.co) in the [Watcher category](https://discuss.elastic.co/c/watcher).

**Comment by rvalenciano** [comment]
Thanks @jasontedor

**Comment by kousiknandy** [comment]
FWIW, I had the same problem, and had to drop [groovy-json-2.4.6.jar](http://central.maven.org/maven2/org/codehaus/groovy/groovy-json/2.4.6/groovy-json-2.4.6.jar) in the ${ELASTICSEARCH_HOME}/modules/lang-groovy/ directory for it to work.
