### ISSUE TITLE
MultiMatchQueryIT#testCrossFieldMode test failure

### ISSUE THREAD

**Issue by abeyad** [elastic/elasticsearch#18873]
This test rarely seems to fail on CI, but I can reproduce it reliably on master with:

```
gradle :core:integTest -Dtests.seed=F953E772EA3B8953 -Dtests.class=org.elasticsearch.search.query.MultiMatchQueryIT -Dtests.method="testCrossFieldMode" -Dtests.security.manager=true -Dtests.locale=hi -Dtests.timezone=America/Bahia_Banderas
```

There seems to be some underlying issues with boosting, as the first search hit returned is supposed to have an id of ultimate1, but the id is 49, which is one of the later documents created in the `init()` phase of the test.

**Comment by drewr** [comment]
One more repro seed, FWIW.

```
  2> REPRODUCE WITH: gradle :core:integTest -Dtests.seed=C3DC091D23C57091 -Dtests.class=org.elasticsearch.search.query.MultiMatchQueryIT -Dtests.method="testCrossFieldMode" -Dtests.security.man
ager=true -Dtests.locale=id -Dtests.timezone=America/Mexico_City
FAILURE 2.19s | MultiMatchQueryIT.testCrossFieldMode <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: searchHit id should be "ultimate1"
   >      but:  was "49"
   >    at __randomizedtesting.SeedInfo.seed([C3DC091D23C57091:CBFC75455976FFFC]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
   >    at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertSearchHit(ElasticsearchAssertions.java:349)
   >    at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertSearchHit(ElasticsearchAssertions.java:284)
   >    at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertFirstHit(ElasticsearchAssertions.java:261)
   >    at org.elasticsearch.search.query.MultiMatchQueryIT.testCrossFieldMode(MultiMatchQueryIT.java:575)
   >    at java.lang.Thread.run(Thread.java:745)
```

**Comment by awislowski** [comment]
I have made a PR fixing this issue.
