### ISSUE TITLE
Courier Fetch: Bad Gateway

### ISSUE THREAD

**Issue by pip00** [elastic/elasticsearch#18894]
I been getting this error lately as soon as fire up Kibana. Any ideas why this is happening ?
As soon as I hit the Go Back button my queries would populate.

![image](https://cloud.githubusercontent.com/assets/19933089/16049157/af59e2d0-3224-11e6-9a8a-4f99cfdee818.png)

![image](https://cloud.githubusercontent.com/assets/19933089/16049190/c7b95284-3224-11e6-9187-ec72ad1a09de.png)

Here are my ES logs:

[2016-06-15 11:32:38,512][DEBUG][action.admin.cluster.node.stats] [elastic-kibana] failed to execute on node [Cr1WzqKXTAmtVy15adTRbg]
ReceiveTimeoutTransportException[[elasticsearch-1][192.168.1.102:9300][cluster:monitor/nodes/stats[n]] request_id [189677] timed out after [15099ms]]
at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
[2016-06-15 11:32:38,899][DEBUG][action.admin.cluster.node.stats] [elastic-kibana] failed to execute on node [CIqJQI_SQlK0HbP4naWhkA]
ReceiveTimeoutTransportException[[elasticsearch-2][192.168.1.103:9300][cluster:monitor/nodes/stats[n]] request_id [189678] timed out after [15499ms]]
at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
[2016-06-15 11:32:59,304][WARN ][transport ] [elastic-kibana] Received response for a request that has timed out, sent [35904ms] ago, timed out [20805ms] ago, action [cluster:monitor/nodes/stats[n]], node [{elasticsearch-1}{Cr1WzqKXTAmtVy15adTRbg}{192.168.1.102}{192.168.1.102:9300}{master=false}], id [189677]
[2016-06-15 11:33:10,304][WARN ][transport ] [elastic-kibana] Received response for a request that has timed out, sent [46904ms] ago, timed out [31405ms] ago, action [cluster:monitor/nodes/stats[n]], node [{elasticsearch-2}{CIqJQI_SQlK0HbP4naWhkA}{192.168.1.103}{192.168.1.103:9300}{master=false}], id [189678]

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks

**Comment by clintongormley** [comment]
Sorry for closing @pip00 - I see https://github.com/elastic/elasticsearch/issues/18868 and https://github.com/elastic/kibana/issues/7455 as well, but the right place to ask is in the forums.  My best guess is you're having GC issues, but this isn't a bug in Elasticsearch so github is not the right place.

**Comment by pip00** [comment]
No problem. Thank your for your help.
