### ISSUE TITLE
Packaging: Upgrading from alpha3 using RPM does not work

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#19026]
When trying to upgrade from alpha3 to a more recent (snapshot) version

**Elasticsearch version**: 5.0.0-alpha3

**OS version**: Centos 7

**Steps to reproduce**:

```
rpm -i elasticsearch-5.0.0-alpha3.rpm
systemctl daemon-reload
systemctl start elasticsearch
# use journalctl -f to check that alpha3 has started, msut be aborted
 journalctl -f -n 40

rpm -Uvh elasticsearch-5.0.0-alpha4.rpm
systemctl daemon-reload
systemctl restart elasticsearch
```

Output of journalctl

```
Jun 22 12:44:56 localhost.localdomain elasticsearch[31947]: Exception in thread "main" java.lang.IllegalStateException: Unable to access 'path.scripts' (/etc/elasticsearch/scripts)
```

When installing alpha3 first, then `/etc/elasticsearch/scripts` is not created, neither it is on upgrade to alpha4. However, there are additional problems when creating that directory

```
mkdir /etc/elasticsearch/scripts
systemctl start elasticsearch
journalctl -f -n 40
```

output is

```
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: [2016-06-22 12:49:01,953][INFO ][node                     ] [Hank McCoy] version[5.0.0-alpha4], pid[31996], build[b0da471/2016-06-22T12:33:48.164Z], OS[Linux/3.10.0-327.18.2.el7.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_91/25.91-b14]
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: [2016-06-22 12:49:01,954][INFO ][node                     ] [Hank McCoy] initializing ...
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: Exception in thread "main" java.lang.IllegalStateException: Unable to initialize modules
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: Likely root cause: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/modules/ingest-grok/plugin-descriptor.properties
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at java.nio.file.Files.newByteChannel(Files.java:361)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at java.nio.file.Files.newByteChannel(Files.java:407)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at java.nio.file.Files.newInputStream(Files.java:152)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:74)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at org.elasticsearch.plugins.PluginsService.getModuleBundles(PluginsService.java:327)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:131)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at org.elasticsearch.node.Node.<init>(Node.java:211)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at org.elasticsearch.node.Node.<init>(Node.java:172)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:175)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:175)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:250)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:96)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:91)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:91)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at org.elasticsearch.cli.Command.main(Command.java:53)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:70)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:63)
Jun 22 12:49:01 localhost.localdomain elasticsearch[31996]: Refer to the log for complete error details.
```

The issue here seems to be that the `ingest-grok` module does not exist after alpha3 anymore (has been moved into `ingest-common`, but it was not cleaned up properly on upgrade.

If we decide that upgrading from alpha3 to newer alpha version does not need to work, than the last part of this can potentially be ignored, however we still need to ensure that upgrading from any older (non alpha) elasticsearch version to a newer one works.

**Comment by jasontedor** [comment]
I don't think we need to support upgrading between pre-releses.

> If we decide that upgrading from alpha3 to newer alpha version does not need to work, than the last part of this can potentially be ignored, however we still need to ensure that upgrading from any older (non alpha) elasticsearch version to a newer one works.

The packaging tests [do this](https://github.com/elastic/elasticsearch/blob/6671c0cf09ffe9dbc31936b25524df88d29612ed/qa/vagrant/src/test/resources/packaging/scripts/80_upgrade.bats). Right now they test upgrading from 2.0.0; I will open a PR to move this to 2.3.3.

**Comment by jasontedor** [comment]
I opened #19029.

**Comment by spinscale** [comment]
IMO we should still ensure that uninstalling an RPM cleans up `/usr/share/elasticsearch/modules`

Otherwise this just postpones the problem until an official release uses different modules.

**Comment by clintongormley** [comment]
> IMO we should still ensure that uninstalling an RPM cleans up /usr/share/elasticsearch/modules
> Otherwise this just postpones the problem until an official release uses different modules.

Agreed!

**Comment by jasontedor** [comment]
Our packaging tests in CI now cover upgrades from all eligible versions, I think that we can close this one out.
