### ISSUE TITLE
__es__.tmp left behind from atomic move check prevents node startup

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#19036]
**Elasticsearch version**:  2.3.0

Have an environment where __es__.tmp is left behind from our atomic_move check on the file system.  The directory only has the __es__.tmp file (i.e. no __es__.final).  

total 4
-rw-r--r--. 1 elasticsearch elasticsearch 0 Jun 21 19:36 __es__.tmp
drwxr-xr-x. 39 elasticsearch elasticsearch 4096 Jun 21 00:02 indices
-rw-r--r--. 1 elasticsearch elasticsearch 0 Mar 31 15:12 node.lock
drwxr-xr-x. 2 elasticsearch elasticsearch 33 Jun 6 18:17 _state

```
[2016-06-22 00:00:01,812][INFO ][node                     ] [node_name] version[2.3.0], pid[7400], build[8371be8/2016-03-29T07:54:48Z]
[2016-06-22 00:00:01,812][INFO ][node                     ] [node_name] initializing ...
[2016-06-22 00:00:02,204][INFO ][plugins                  ] [node_name] modules [reindex, lang-expression, lang-groovy], plugins [license, shield, marvel-agent], sites []
[2016-06-22 00:00:02,223][INFO ][env                      ] [node_name] using [1] data paths, mounts [[/var (/dev/mapper/vg00-lv--var)]], net usable_space [580.9gb], net total_space [1tb], spins? [possibly], types [xfs]
[2016-06-22 00:00:02,223][INFO ][env                      ] [node_name] heap size [989.8mb], compressed ordinary object pointers [true]
[2016-06-22 00:00:02,223][WARN ][env                      ] [node_name] max file descriptors [4096] for elasticsearch process likely too low, consider increasing to at least [65536]
[2016-06-22 00:00:02,542][INFO ][http                     ] [node_name] Using [org.elasticsearch.http.netty.NettyHttpServerTransport] as http transport, overridden by [shield]
[2016-06-22 00:00:02,654][INFO ][transport                ] [node_name] Using [org.elasticsearch.shield.transport.ShieldServerTransportService] as transport service, overridden by [shield]
[2016-06-22 00:00:02,654][INFO ][transport                ] [node_name] Using [org.elasticsearch.shield.transport.netty.ShieldNettyTransport] as transport, overridden by [shield]
[2016-06-22 00:00:03,535][ERROR][bootstrap                ] Guice Exception: java.nio.file.FileAlreadyExistsException: /var/lib/elasticsearch-20/cluster_name/nodes/0/__es__.tmp
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.createFile(Files.java:632)
	at org.elasticsearch.env.NodeEnvironment.ensureAtomicMoveSupported(NodeEnvironment.java:794)
	at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:82)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at <<<guice>>>
	at org.elasticsearch.node.Node.<init>(Node.java:213)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

It didn't throw an AtomicMoveNotSupportedException so it appears that the check passed, but somehow it has trouble cleaning up the tmp file, so that on the next run, it bombs out when it tries to do a file create  when the tmp file already exists.  Should we handle this more gracefully and still allow the node to start up?  If not, a more intuitive error handling message will be helpful.

**Comment by jasontedor** [comment]
That's odd; we `try/finally` clean up those files. The only way those files are not cleaned up is if the `finally` block did not complete (e.g., someone pulled the plug on the machine after the `__es__.tmp` file was created but before the `finally` block executed) or the delete operation failed.

The other interesting item here is how the `node.lock` is really old relative to the `__es__.tmp` file. Is there something else going on here?

**Comment by maxcom** [comment]
This happened after OOM killer killed Elasticsearch. Maybe ES can automaticly remove this lost temp file on startup?

**Comment by s1monw** [comment]
> This happened after OOM killer killed Elasticsearch. Maybe ES can automaticly remove this lost temp file on startup?

I am not sure, if your OOM Killer kicks in at that early stage something is really fishy. It's such an exceptional situation that we should require human interaction? I mean we can maybe throw a better exception but messing with it seems dangerous?

**Comment by benavid** [comment]
Do you know if this issue continue happens with elasticseach 2.4.1?, when I try to start elasticsearch I receive this error: Starting elasticsearch: Exception in thread "main" java.nio.file.FileAlreadyExistsException: /data/elasticsearch/marta/nodes/0/__es__.tmp
