### ISSUE TITLE
 process creation failed in ES2.3.2

### ISSUE THREAD

**Issue by chindhuhari** [elastic/elasticsearch#19041]
**Elasticsearch version**: 2.3.2

**JVM version**:1.7

**OS version**: Windows 8

**Description of the problem including expected versus actual behavior**: This was working well in Elasticsearch 2.0.2, I just upgraded to ES 2.3.2, it started throwing the following error : 
I am using nutch internally for crawling file/web, there is a plugin wrapper for it. When we run in Windows, hadoop(internally used by nutch) uses cygwin for running UNIX command "chmod", it used to work fine while the same thing was used in ES2.0, but now it throws the error :

Cannot run program "chmod": CreateProcess error=1816,
Not enough quota is available to process this command

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

java.io.IOException: Cannot run program "chmod": CreateProcess error=1816, Not enough quota is available to process this command
	at java.lang.ProcessBuilder.start(Unknown Source)
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:149)
	at org.apache.hadoop.util.Shell.run(Shell.java:134)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:286)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:354)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:337)
	at org.apache.hadoop.fs.RawLocalFileSystem.execCommand(RawLocalFileSystem.java:481)
	at org.apache.hadoop.fs.RawLocalFileSystem.setPermission(RawLocalFileSystem.java:473)
	at org.apache.hadoop.fs.FilterFileSystem.setPermission(FilterFileSystem.java:280)
	at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:266)
	at org.apache.hadoop.mapred.JobClient.configureCommandLineOptions(JobClient.java:573)
	at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:761)
	at org.apache.hadoop.mapred.JobClient.submitJob(JobClient.java:730)
	at org.apache.hadoop.mapred.JobClient.runJob(JobClient.java:1249)
	at org.apache.nutch.crawl.Injector.inject(Injector.java:323)

**Describe the feature**:

**Comment by jasontedor** [comment]
This is not an Elasticsearch issue (it's not even in your stack trace) but rather your system is low on resources. You need to investigate resource limitations on your machine such as virtual memory, handles, etc.

**Comment by rmuir** [comment]
No, it is us. But execution is not supported :)

**Comment by jasontedor** [comment]
> No, it is us. But execution is not supported :)

Okay. Thanks for the correction, the error message (not in your control) also appears when a Windows system is running low on resources.

**Comment by rmuir** [comment]
Good. I am happy that it is confusing.

Users get a completely unambiguous error message from security manager (execution denied) 100% of the time, telling them that execution is not allowed. So it is no real issue.

**Comment by chindhuhari** [comment]
Thank you all for the response.
