### ISSUE TITLE
SearchGraurd plugin not connecting  with Elasticsearch

### ISSUE THREAD

**Issue by kavipreetha** [elastic/elasticsearch#19054]
I use elasticssearch 2.3.3 
and installed following as plugin in ES
search-guard-ssl - 2.3.3.13
search-guard-2 - 2.3.3.1

1. Created jks file using search-guard-ssl and copied to elasticsearch/config path

2. elasticsearch.yml added entried related to search-guard-ssl 
searchguard.ssl.transport.keystore_filepath: node-guidanz-keystore.jks
searchguard.ssl.transport.keystore_password: guidanz123
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: guidanz123
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: node-guidanz-keystore.jks
searchguard.ssl.http.keystore_password: guidanz123
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: guidanz123

3. elasticsearch.yml added the entry of search-guard-2 plugin
searchguard.authcz.admin_dn:
  - "DC=com, DC=10.9.14.8, O=Guidanz Com Inc., OU=Guidanz Com Inc. Root CA, CN=Guidanz Com Inc. Root CA"

4. Opened another terminal and ran the following command,
plugins/search-guard-2/tools/sgadmin.sh -cd plugins/search-guard-2/sgconfig/ -h 10.9.14.8 -p 9300 -ks plugins/search-guard-2/sgconfig/node-guidanz-keystore.jks  -kspass guidanz123 -ts plugins/search-guard-2/sgconfig/truststore.jks -tspass guidanz123  -nrhn
Got the following error,
Connect to 10.9.14.8:9300
Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{10.9.14.8}{10.9.14.8:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transpotore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: guidanz123
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: node-guidanz-keystore.jks
searchguard.ssl.http.keystore_password: guidanz123
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: guidanz123

searchguard.audit.type: internal_elasticsearch

Kindly suggest to proceed further.rt.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:348)
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:848)
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.health(AbstractClient.java:868)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:201)

5. And in elelasticsearch got the following error,

[2016-06-24 11:56:38,625][ERROR][com.floragunn.searchguard.transport.SearchGuardTransportService] No user found in this LivenessRequest for action cluster:monitor/nodes/liveness and transport type netty. If you see this error related when you use sgadmin make sure you connect with a client (and not with a node) certificate.

Below is full configuration of my elasticsearch.yml

cluster.name: my-searchgaurd-application
network.host: 10.9.14.8
http.port: 9500
searchguard.authcz.admin_dn:
  - "DC=com, DC=10.9.14.8, O=Guidanz Com Inc., OU=Guidanz Com Inc. Root CA, CN=Guidanz Com Inc. Root CA"
  
searchguard.ssl.transport.keystore_filepath: node-guidanz-keystore.jks
searchguard.ssl.transport.keystore_password: guidanz123
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: guidanz123
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: node-guidanz-keystore.jks
searchguard.ssl.http.keystore_password: guidanz123
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: guidanz123

searchguard.audit.type: internal_elasticsearch

Kindly suggest to proceed further.

**Comment by spinscale** [comment]
this looks like a searchguard problem. I think it's easier to file an issue in the search guard repository, as this is a plugin not maintained by elasticsearch developers
