### ISSUE TITLE
Running elasticsearch-5.0.0-alpha3 on Ubuntu 14.04 seems to hang

### ISSUE THREAD

**Issue by draghuram** [elastic/elasticsearch#19134]
**Elasticsearch version**: 5.0.0-alpha3

**JVM version**: 1.8.0_25

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:

elasticsearch doesn't seem to be doing any thing. In particular, I don't see any log messages about binding to IP and port. Even "netstat -anp" doesn't show any bindings.

**Steps to reproduce**:
 1. cd elasticsearch-5.0.0-alpha3
 2. ./bin/elasticsearch

**Comment by jasontedor** [comment]
Sorry that you're having trouble, but we'll need more detail than this to debug. What log messages do you see? Can you take a stack dump with `jstack` when it's apparently hanging?

**Comment by draghuram** [comment]
I see no log messages on STDOUT. Is there a log file I can check?

I am attaching the jstack output.
[es.txt](https://github.com/elastic/elasticsearch/files/337939/es.txt)

**Comment by jasontedor** [comment]
From the stack trace I can tell you that there will not have been any log messages at this point.

```
"main" #1 prio=5 os_prio=0 tid=0x00007f84d000b000 nid=0x296b runnable [0x00007f84d95e2000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.fs.UnixNativeDispatcher.stat0(Native Method)
	at sun.nio.fs.UnixNativeDispatcher.stat(UnixNativeDispatcher.java:286)
	at sun.nio.fs.UnixFileAttributes.get(UnixFileAttributes.java:70)
	at sun.nio.fs.UnixFileStore.devFor(UnixFileStore.java:55)
	at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:70)
	at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:48)
	at sun.nio.fs.LinuxFileSystem.getFileStore(LinuxFileSystem.java:112)
	at sun.nio.fs.UnixFileSystem$FileStoreIterator.readNext(UnixFileSystem.java:213)
	at sun.nio.fs.UnixFileSystem$FileStoreIterator.hasNext(UnixFileSystem.java:224)
	- locked <0x00000000807cc8e8> (a sun.nio.fs.UnixFileSystem$FileStoreIterator)
	at org.apache.lucene.util.IOUtils.getFileStore(IOUtils.java:543)
	at org.apache.lucene.util.IOUtils.spinsLinux(IOUtils.java:487)
	at org.apache.lucene.util.IOUtils.spins(IOUtils.java:476)
	at org.elasticsearch.env.ESFileStore.<init>(ESFileStore.java:60)
	at org.elasticsearch.env.Environment.<clinit>(Environment.java:105)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:98)
	at org.elasticsearch.bootstrap.Bootstrap.initialSettings(Bootstrap.java:194)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:234)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:96)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:91)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:91)
	at org.elasticsearch.cli.Command.main(Command.java:53)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:70)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:63)
```

Is that always where it's hung? Maybe take `jstack` a few more times to be sure?

That's where it's trying to detect if you have an SSD. I think this is environmental; is something wrong with your filesystem?

**Comment by draghuram** [comment]
The latest jstack output shows identical trace as above. I do have a hanging NFS mount and when I unmounted it, ES did proceed and there were some log messages about IP and port number. So the bad NFS mount was the problem. I am curious why ES is going through all the mount points, however.

Thanks for quick help any way.

**Comment by jasontedor** [comment]
NFS is what's wrong with your filesystem. 😛

> I am curious why ES is going through all the mount points, however.

We cache them on startup (expensive) to look up the store paths later.

> Thanks for quick help any way.

You're welcome.

**Comment by draghuram** [comment]
If I may suggest, it would be helpful if ES logs messages as it looks up (could be DEBUG level) paths. These messages can be shown with "-v" option and that will help in debugging.

**Comment by nik9000** [comment]
We could almost certainly log a warning if the process takes more than a second....

**Comment by jasontedor** [comment]
> If I may suggest, it would be helpful if ES logs messages as it looks up (could be DEBUG level) paths. These messages can be shown with "-v" option and that will help in debugging.

> We could almost certainly log a warning if the process takes more than a second....

This is happening in Lucene, before we've even bootstrapped. Yes, we can fork a thread and so on, but I think that's overkill here?

**Comment by s1monw** [comment]
> This is happening in Lucene, before we've even bootstrapped. Yes, we can fork a thread and so on, but I think that's overkill here?

I agree - what if the NFS mount hangs at a later stage we are just pushing the problem out.

**Comment by draghuram** [comment]
Though I don't know internals of ES, forking a thread just for this purpose does sound overkill.

**Comment by NeilRickards** [comment]
Does ES actually have anything on that NFS mount - data, binaries, config, etc.?
If so, then failing when the mount is unavailable sounds reasonable (though ideally with more logging).
If, on the other hand, ES (or Lucene) is just enumerating all the mounts on the system and hanging, then that sounds like undesirable behaviour.
