### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by iokays** [elastic/elasticsearch#19138]
Hi,  I encountered a problem when I insert data, the following specific information.
(Elasticsearch 2.3.1, JVM version 1.7.0_80x, CentOS release 6.6 (Final))

100.6% (502.7ms out of 500ms) cpu usage by thread 'elasticsearch[Pressure][index][T#8]'
     3/10 snapshots sharing following 30 elements
       java.lang.invoke.LambdaForm$DMH/1697384030.invokeSpecial_LL_L(LambdaForm$DMH)
       java.lang.invoke.LambdaForm$BMH/1674119038.reinvoke(LambdaForm$BMH)
       java.lang.invoke.LambdaForm$MH/5369010.invokeExact_MT(LambdaForm$MH)
       java.lang.invoke.MethodHandleImpl$GuardWithCatch.invoke_L1(MethodHandleImpl.java:619)
       java.lang.invoke.LambdaForm$DMH/1697384030.invokeSpecial_LL_L(LambdaForm$DMH)
       java.lang.invoke.LambdaForm$BMH/1674119038.reinvoke(LambdaForm$BMH)
       java.lang.invoke.LambdaForm$DMH/1697384030.invokeSpecial_LL_L(LambdaForm$DMH)
       java.lang.invoke.LambdaForm$MH/688130558.guard(LambdaForm$MH)
       java.lang.invoke.LambdaForm$DMH/1697384030.invokeSpecial_LL_L(LambdaForm$DMH)
       java.lang.invoke.LambdaForm$MH/1319810003.guard(LambdaForm$MH)
       java.lang.invoke.LambdaForm$MH/303157806.linkToCallSite(LambdaForm$MH)
       2057dd62e69d7b398105d17365a0e4fffae8cc18.run(2057dd62e69d7b398105d17365a0e4fffae8cc18:1)
       org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript$1.run(GroovyScriptEngineService.java:313)
       java.security.AccessController.doPrivileged(Native Method)
       org.elasticsearch.script.groovy.GroovyScriptEngineService$GroovyScript.run(GroovyScriptEngineService.java:310)
       org.elasticsearch.action.update.UpdateHelper.executeScript(UpdateHelper.java:252)
       org.elasticsearch.action.update.UpdateHelper.prepare(UpdateHelper.java:197)
       org.elasticsearch.action.update.UpdateHelper.prepare(UpdateHelper.java:80)
       org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:174)
       org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:168)
       org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:66)
       org.elasticsearch.action.support.single.instance.TransportInstanceSingleOperationAction$ShardTransportHandler.messageReceived(TransportInstanceSingleOperationAction.java:244)
       org.elasticsearch.action.support.single.instance.TransportInstanceSingleOperationAction$ShardTransportHandler.messageReceived(TransportInstanceSingleOperationAction.java:240)
       org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
       org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
       org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:300)
       org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
       java.lang.Thread.run(Thread.java:745)

**This is the code:** 

`public void run() {
        while (true) {
            final long start = System.currentTimeMillis();
            int max = 0;
            for (int j = 0; j < 1024; j++) {
                max = ATOMIC.incrementAndGet();
                final String id = Integer.toString(max);
                final IndexTest entity = new IndexTest();
                entity.setId(id);
                repository.save("index_test", "type", id, id, entity, false);
            }
            final long end = System.currentTimeMillis();
            long cost = end - start;
            long avgCost = cost / 1024;
            LOGGER.info("thread index: {},\t run: {},\t cost: {}ms,\t average cost: {}ms, maxValue: {}", this.index,
                    1024, cost, avgCost, max);
        }
    }`

**logger**
2016-06-29 04:01:58 INFO [com.chinatime.datacenter.test.elastic.InsertES2]:71 Line - thread index: 6,	 run: 1024,	 cost: 9971ms,	 average cost: 9ms, maxValue: 29784947
2016-06-29 04:01:58 INFO [com.chinatime.datacenter.test.elastic.InsertES2]:71 Line - thread index: 3,	 run: 1024,	 cost: 9833ms,	 average cost: 9ms, maxValue: 29785724
2016-06-29 04:01:59 INFO [com.chinatime.datacenter.test.elastic.InsertES2]:71 Line - thread index: 2,	 run: 1024,	 cost: 9844ms,	 average cost: 9ms, maxValue: 29786615
2016-06-29 04:02:01 INFO [com.chinatime.datacenter.test.elastic.InsertES2]:71 Line - thread index: 7,	 run: 1024,	 cost: 9754ms,	 average cost: 9ms, maxValue: 29787929
2016-06-29 04:02:02 INFO [com.chinatime.datacenter.test.elastic.InsertES2]:71 Line - thread index: 8,	 run: 1024,	 cost: 9655ms,	 average cost: 9ms, maxValue: 29789595
2016-06-29 04:02:02 INFO [com.chinatime.datacenter.test.elastic.InsertES2]:71 Line - thread index: 4,	 run: 1024,	 cost: 9641ms,	 average cost: 9ms, maxValue: 29789704
2016-06-29 04:02:03 INFO [com.chinatime.datacenter.test.elastic.InsertES2]:71 Line - thread index: 5,	 run: 1024,	 cost: 9759ms,	 average cost: 9ms, maxValue: 29790382
2016-06-29 08:48:06 INFO [com.chinatime.datacenter.test.elastic.InsertES2]:71 Line - thread index: 9,	 run: 1024,	 cost: 17170973ms,	 average cost: 16768ms, maxValue: 29792325
2016-06-29 08:48:06 INFO [com.chinatime.datacenter.test.elastic.InsertES2]:71 Line - thread index: 3,	 run: 1024,	 cost: 17167821ms,	 average cost: 16765ms, maxValue: 29796080
Exception in thread "pool-1-thread-6" ElasticsearchTimeoutException[Timeout waiting for task.]
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:70)
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:62)
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:52)
	at com.chinatime.common.elasticsearch.utils.AbstractElasticRepository.save(AbstractElasticRepository.java:120)
	at com.chinatime.datacenter.test.elastic.InsertES2.run(InsertES2.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Work

**Comment by iokays** [comment]
CUP INFO:

Cpu0  : 99.7%us,  0.0%sy,  0.0%ni,  0.0%id,  0.0%wa,  0.0%hi,  0.3%si,  0.0%st
Cpu1  :  0.3%us,  0.0%sy,  0.0%ni, 99.3%id,  0.3%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu2  :100.0%us,  0.0%sy,  0.0%ni,  0.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu3  :  1.3%us,  0.7%sy,  0.0%ni, 98.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu4  :  0.7%us,  0.7%sy,  0.0%ni, 98.7%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu5  :100.0%us,  0.0%sy,  0.0%ni,  0.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu6  :  0.7%us,  0.0%sy,  0.0%ni, 99.3%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu7  :100.0%us,  0.0%sy,  0.0%ni,  0.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  32827372k total, 19282824k used, 13544548k free,   492640k buffers
Swap: 20479996k total,        0k used, 20479996k free,  7979768k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                      
20324 public    20   0 6870m 1.4g  43m S 403.0  4.3   6235:34 java

**Comment by 3st384n** [comment]
Se que yo solo observo aqui pero en realidad me gustaria aprender esto que ustedes hacen!

**Comment by jpountz** [comment]
Most cpu time seems to be spent running your update script. You might want to simplify it or apply the update on client side if you really need to make it faster, but otherwise there is nothing wrong with having high CPU usage given that you are trying to index at full throttle.

**Comment by iokays** [comment]
@jpountz  Thank you, but I stopped writing this is now the state of the CPU data after 7 hours, has not come down.hot_threads too.

**Comment by jpountz** [comment]
Is it possible that you have an infinite loop in your update scripts?

**Comment by iokays** [comment]
I now have the method to script the update of total abolition, and then test to see test results.
