### ISSUE TITLE
LuceneTests.testAsSequentialAccessBits fails frequently and reproducible

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#19151]
Failure is : 

```
java.lang.AssertionError: The top-reader used to create Weight (org.apache.lucene.index.CompositeReaderContext@622216af) is not the same as the current reader's top-reader (org.apache.lucene.index.CompositeReaderContext@474b5998
	at __randomizedtesting.SeedInfo.seed([8C29ADADD27E8824:8EBEA1349D13476A]:0)
	at org.apache.lucene.search.TermQuery$TermWeight.scorer(TermQuery.java:100)
	at org.elasticsearch.common.lucene.LuceneTests.testAsSequentialAccessBits(LuceneTests.java:381)
```

To reproduce: 

```
gradle :core:test -Dtests.seed=8C29ADADD27E8824 -Dtests.class=org.elasticsearch.common.lucene.LuceneTests -Dtests.method="testAsSequentialAccessBits" -Dtests.security.manager=true -Dtests.locale=sq -Dtests.timezone=Africa/Libreville
```

See for example: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/916/consoleText

**Comment by brwe** [comment]
I muted the test for now.
