### ISSUE TITLE
Not able to install plugin. <java.lang.classcastException>

### ISSUE THREAD

**Issue by vinay992002** [elastic/elasticsearch#19182]
**Elasticsearch version**: 1.0.2

**JVM version**: java 7

**OS version**:  Windows 7
**Issue**
I am trying to install plugin (which is just a custom Analyzer) its giving this error
 
 com.analyzer.AnalyzerPlugin cannot be cast to org.elasticsearch.plugins.Plugin   at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:505)

what could be the possible reason of it?

**logs**:

[2016-06-30 16:03:22,796][INFO ][node                     ] [Whirlwind] version[1.0.2], pid[17104], build[4fc0da7/2014-03-25T15:41:15Z]
[2016-06-30 16:03:22,796][INFO ][node                     ] [Whirlwind] initializing ...
[2016-06-30 16:03:22,804][WARN ][plugins                  ] [Whirlwind] failed to load plugin from [file:/C:/Users/user/Downloads/elasticsearch-1.0.2/plugins/analyzer/es-plugin.properties]
org.elasticsearch.ElasticsearchException: Failed to load plugin class [com.analyzer.AnalyzerPlugin]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:516)
        at org.elasticsearch.plugins.PluginsService.loadPluginsFromClasspath(PluginsService.java:397)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:100)
        at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:143)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:68)
        at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:201)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
Caused by: java.lang.ClassCastException: com.analyzer.AnalyzerPlugin cannot be cast to org.elasticsearch.plugins.Plugin
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:505)
        ... 7 more
[2016-06-30 16:03:22,808][INFO ][plugins                  ] [Whirlwind] loaded [], sites []
[2016-06-30 16:03:25,507][INFO ][node                     ] [Whirlwind] initialized
[2016-06-30 16:03:25,507][INFO ][node                     ] [Whirlwind] starting ...
[2016-06-30 16:03:25,602][INFO ][transport                ] [Whirlwind] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/10.224.242.131:9300]
}
[2016-06-30 16:03:28,765][INFO ][cluster.service          ] [Whirlwind] new_master [Whirlwind][oCo73HnaTNiLzpu-M7YsHw][WBHATVW7HYD][inet[/10.224.242.131:9300]],
 reason: zen-disco-join (elected_as_master)
[2016-06-30 16:03:28,816][INFO ][discovery                ] [Whirlwind] elasticsearch/oCo73HnaTNiLzpu-M7YsHw
[2016-06-30 16:03:28,849][INFO ][gateway                  ] [Whirlwind] recovered [0] indices into cluster_state
[2016-06-30 16:03:28,870][INFO ][http                     ] [Whirlwind] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/10.224.242.131:9200]

**Comment by dadoonet** [comment]
Your plugin is incorrect probably.

Ask this on discuss.elastic.co please. We'll help you there.

**Comment by jasontedor** [comment]
Presumably because the plugin does not conform to the plugin API for the version of Elasticsearch that you're trying to install on. Either way, the version of Elasticsearch that you're running is woefully old and is unsupported. You should upgrade.
