### ISSUE TITLE
Failed to install ElasticSearch

### ISSUE THREAD

**Issue by MarcusGitAccount** [elastic/elasticsearch#19236]
I am trying to install ElasticSearch and when I am running bin/elasticsearch from cmd I am getting this error. Do you have any ideas what might be the problem and how can I fix it ? Thanks.

```
C:\Users\Marcus\Documents\ElasticSearch\elasticsearch-5.0.0-alpha4>bin\elasticsearch.bat
[2016-07-03 19:13:24,266][INFO ][node                     ] [Blue Diamond] version[5.0.0-alpha4],pid[5968], build[3f5b994/2016-06-27T16:23:46.861Z], OS[Windows 7/6.1/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_92/25.92-b14]
[2016-07-03 19:13:24,267][INFO ][node                     ] [Blue Diamond] initializing ...
Exception in thread "main" ElasticsearchException[Could not find plugin class [org.elasticsearch.script.mustache.MustachePlugin]]; nested: ClassNotFoundException[org.elasticsearch.script.mustache.MustachePlugin];
Likely root cause: java.lang.ClassNotFoundException: org.elasticsearch.script.mustache.MustachePlugin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:441)
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:412)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:134)
        at org.elasticsearch.node.Node.<init>(Node.java:212)
        at org.elasticsearch.node.Node.<init>(Node.java:173)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:175)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:175)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:250)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:96)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:91)
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:91)
        at org.elasticsearch.cli.Command.main(Command.java:53)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:70)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:63)

Refer to the log for complete error details.
```

**Comment by dadoonet** [comment]
Did you download elasticsearch from the website? https://www.elastic.co/downloads/elasticsearch

Which exact binary did you download?
Did you just unzip and launch?

Thanks

**Comment by MarcusGitAccount** [comment]
I have dowloaded elasticsearch from the website, the 5.0.0-alpha4 version.
I have unziped and launch the bin\elasticsearch.bat command from cmd.

Marcus

**Comment by dadoonet** [comment]
I just started a Windows8 instances, downloaded a fresh version of elasticsearch and launched it.
Ran very well.

Not sure why you are seeing this.

Could you try again from scratch and report all the steps here?

Also check your system/user properties. May be you have some strange JVM options?

**Comment by jasontedor** [comment]
I think that somehow you mangled the modules directory, and removed at a minimum the lang-mustache-5.0.0-alpha4.jar file. That is, I can reproduce your exact stack trace just by removing this file.

<details>
  <summary>Removing lang-mustache-5.0.0-alpha4.jar</summary>
```bash
14:48:38 ⌁38% [jason:~/elasticsearch] $ rm elasticsearch-5.0.0-alpha4/modules/lang-mustache/lang-mustache-5.0.0-alpha4.jar
14:48:40 ⌁38% [jason:~/elasticsearch] $ ls -al ./elasticsearch-5.0.0-alpha4/modules/lang-mustache/
total 216
drwxr-xr-x   5 jason  staff    170 Jul  3 14:46 .
drwxr-xr-x  10 jason  staff    340 Jun 30 14:52 ..
-rw-r--r--   1 jason  staff  98451 Jun 30 14:51 compiler-0.9.1.jar
-rw-r--r--   1 jason  staff   1309 Jun 30 14:51 plugin-descriptor.properties
-rw-r--r--   1 jason  staff    902 Jun 30 14:51 plugin-security.policy
14:48:52 ⌁38% [jason:~/elasticsearch] $ ./elasticsearch-5.0.0-alpha4/bin/elasticsearch
[2016-07-03 14:49:00,904][INFO ][node                     ] [Hub] version[5.0.0-alpha4], pid[40059], build[3f5b994/2016-06-27T16:23:46.861Z], OS[Mac OS X/10.11.5/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_92/25.92-b14]
[2016-07-03 14:49:00,905][INFO ][node                     ] [Hub] initializing ...
Exception in thread "main" ElasticsearchException[Could not find plugin class [org.elasticsearch.script.mustache.MustachePlugin]]; nested: ClassNotFoundException[org.elasticsearch.script.mustache.MustachePlugin];
Likely root cause: java.lang.ClassNotFoundException: org.elasticsearch.script.mustache.MustachePlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:441)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:412)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:134)
	at org.elasticsearch.node.Node.<init>(Node.java:212)
	at org.elasticsearch.node.Node.<init>(Node.java:173)
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:175)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:175)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:250)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:96)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:91)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:91)
	at org.elasticsearch.cli.Command.main(Command.java:53)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:70)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:63)
Refer to the log for complete error details.
14:49:01 ⌁38% [jason:~/elasticsearch] 1 $ 
```
</details>

However, a clean install of Elasticsearch 5.0.0-alpha4 will include this file, and Elasticsearch will start fine:

<details>
<summary>Clean install of Elasticsearch 5.0.0-alpha4</summary>
```bash
14:55:28 ⌁36% [jason:~/elasticsearch] $ rm -rf elasticsearch-5.0.0-alpha4/
14:55:34 ⌁36% [jason:~/elasticsearch] $ curl -L -O -sS https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/zip/elasticsearch/5.0.0-alpha4/elasticsearch-5.0.0-alpha4.zip
14:55:46 ⌁35% [jason:~/elasticsearch] $ unzip elasticsearch-5.0.0-alpha4.zip 
Archive:  elasticsearch-5.0.0-alpha4.zip
   creating: elasticsearch-5.0.0-alpha4/
   creating: elasticsearch-5.0.0-alpha4/lib/
  inflating: elasticsearch-5.0.0-alpha4/lib/elasticsearch-5.0.0-alpha4.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/lucene-core-6.1.0.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/lucene-analyzers-common-6.1.0.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/lucene-backward-codecs-6.1.0.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/lucene-grouping-6.1.0.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/lucene-highlighter-6.1.0.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/lucene-join-6.1.0.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/lucene-memory-6.1.0.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/lucene-misc-6.1.0.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/lucene-queries-6.1.0.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/lucene-queryparser-6.1.0.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/lucene-sandbox-6.1.0.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/lucene-spatial-6.1.0.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/lucene-spatial-extras-6.1.0.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/lucene-spatial3d-6.1.0.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/lucene-suggest-6.1.0.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/securesm-1.0.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/jopt-simple-4.9.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/hppc-0.7.1.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/joda-time-2.9.4.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/joda-convert-1.2.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/jackson-core-2.7.1.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/jackson-dataformat-smile-2.7.1.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/jackson-dataformat-yaml-2.7.1.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/jackson-dataformat-cbor-2.7.1.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/netty-3.10.5.Final.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/t-digest-3.0.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/HdrHistogram-2.1.6.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/spatial4j-0.6.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/jts-1.13.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/log4j-1.2.17.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/apache-log4j-extras-1.2.17.jar  
  inflating: elasticsearch-5.0.0-alpha4/lib/jna-4.2.2.jar  
   creating: elasticsearch-5.0.0-alpha4/config/
  inflating: elasticsearch-5.0.0-alpha4/config/jvm.options  
  inflating: elasticsearch-5.0.0-alpha4/config/elasticsearch.yml  
  inflating: elasticsearch-5.0.0-alpha4/config/logging.yml  
   creating: elasticsearch-5.0.0-alpha4/bin/
  inflating: elasticsearch-5.0.0-alpha4/bin/elasticsearch-plugin  
  inflating: elasticsearch-5.0.0-alpha4/bin/elasticsearch.in.sh  
  inflating: elasticsearch-5.0.0-alpha4/bin/elasticsearch  
  inflating: elasticsearch-5.0.0-alpha4/bin/elasticsearch-systemd-pre-exec  
  inflating: elasticsearch-5.0.0-alpha4/bin/elasticsearch-plugin.bat  
  inflating: elasticsearch-5.0.0-alpha4/bin/elasticsearch.in.bat  
  inflating: elasticsearch-5.0.0-alpha4/bin/service.bat  
  inflating: elasticsearch-5.0.0-alpha4/bin/elasticsearch.bat  
  inflating: elasticsearch-5.0.0-alpha4/NOTICE.txt  
  inflating: elasticsearch-5.0.0-alpha4/README.textile  
  inflating: elasticsearch-5.0.0-alpha4/LICENSE.txt  
  inflating: elasticsearch-5.0.0-alpha4/bin/elasticsearch-service-mgr.exe  
  inflating: elasticsearch-5.0.0-alpha4/bin/elasticsearch-service-x64.exe  
  inflating: elasticsearch-5.0.0-alpha4/bin/elasticsearch-service-x86.exe  
   creating: elasticsearch-5.0.0-alpha4/modules/
   creating: elasticsearch-5.0.0-alpha4/modules/lang-painless/
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-painless/plugin-security.policy  
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-painless/plugin-descriptor.properties  
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-painless/asm-debug-all-5.1.jar  
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-painless/lang-painless-5.0.0-alpha4.jar  
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-painless/antlr4-runtime-4.5.1-1.jar  
   creating: elasticsearch-5.0.0-alpha4/modules/percolator/
  inflating: elasticsearch-5.0.0-alpha4/modules/percolator/percolator-5.0.0-alpha4.jar  
  inflating: elasticsearch-5.0.0-alpha4/modules/percolator/plugin-descriptor.properties  
   creating: elasticsearch-5.0.0-alpha4/modules/lang-groovy/
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-groovy/plugin-security.policy  
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-groovy/plugin-descriptor.properties  
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-groovy/groovy-2.4.6-indy.jar  
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-groovy/lang-groovy-5.0.0-alpha4.jar  
   creating: elasticsearch-5.0.0-alpha4/modules/ingest-common/
  inflating: elasticsearch-5.0.0-alpha4/modules/ingest-common/joni-2.1.6.jar  
  inflating: elasticsearch-5.0.0-alpha4/modules/ingest-common/ingest-common-5.0.0-alpha4.jar  
  inflating: elasticsearch-5.0.0-alpha4/modules/ingest-common/plugin-descriptor.properties  
  inflating: elasticsearch-5.0.0-alpha4/modules/ingest-common/jcodings-1.0.12.jar  
   creating: elasticsearch-5.0.0-alpha4/modules/reindex/
  inflating: elasticsearch-5.0.0-alpha4/modules/reindex/plugin-descriptor.properties  
  inflating: elasticsearch-5.0.0-alpha4/modules/reindex/reindex-5.0.0-alpha4.jar  
   creating: elasticsearch-5.0.0-alpha4/modules/lang-mustache/
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-mustache/compiler-0.9.1.jar  
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-mustache/plugin-security.policy  
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-mustache/plugin-descriptor.properties  
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-mustache/lang-mustache-5.0.0-alpha4.jar  
   creating: elasticsearch-5.0.0-alpha4/modules/lang-expression/
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-expression/asm-tree-5.0.4.jar  
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-expression/plugin-security.policy  
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-expression/plugin-descriptor.properties  
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-expression/asm-commons-5.0.4.jar  
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-expression/lucene-expressions-6.1.0.jar  
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-expression/antlr4-runtime-4.5.1-1.jar  
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-expression/asm-5.0.4.jar  
  inflating: elasticsearch-5.0.0-alpha4/modules/lang-expression/lang-expression-5.0.0-alpha4.jar  
   creating: elasticsearch-5.0.0-alpha4/modules/aggs-matrix-stats/
  inflating: elasticsearch-5.0.0-alpha4/modules/aggs-matrix-stats/plugin-descriptor.properties  
  inflating: elasticsearch-5.0.0-alpha4/modules/aggs-matrix-stats/aggs-matrix-stats-5.0.0-alpha4.jar  
14:55:52 ⌁35% [jason:~/elasticsearch] $ ls -al elasticsearch-5.0.0-alpha4/modules/lang-mustache/
total 320
drwxr-xr-x   6 jason  staff    204 Jun 27 16:26 .
drwxr-xr-x  10 jason  staff    340 Jun 27 16:27 ..
-rw-rw-r--   1 jason  staff  98451 Jun 27 16:26 compiler-0.9.1.jar
-rw-rw-r--   1 jason  staff  49699 Jun 27 16:26 lang-mustache-5.0.0-alpha4.jar
-rw-rw-r--   1 jason  staff   1309 Jun 27 16:26 plugin-descriptor.properties
-rw-rw-r--   1 jason  staff    902 Jun 27 16:26 plugin-security.policy
14:56:01 ⌁35% [jason:~/elasticsearch] $ ./elasticsearch-5.0.0-alpha4/bin/elasticsearch
[2016-07-03 14:56:08,806][INFO ][node                     ] [Boost] version[5.0.0-alpha4], pid[40876], build[3f5b994/2016-06-27T16:23:46.861Z], OS[Mac OS X/10.11.5/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_92/25.92-b14]
[2016-07-03 14:56:08,807][INFO ][node                     ] [Boost] initializing ...
[2016-07-03 14:56:09,358][INFO ][plugins                  ] [Boost] modules [percolator, lang-mustache, lang-painless, reindex, aggs-matrix-stats, lang-expression, ingest-common, lang-groovy], plugins []
[2016-07-03 14:56:09,807][INFO ][env                      ] [Boost] using [1] data paths, mounts [[/ (/dev/disk1)]], net usable_space [346.6gb], net total_space [464.7gb], spins? [unknown], types [hfs]
[2016-07-03 14:56:09,807][INFO ][env                      ] [Boost] heap size [1.9gb], compressed ordinary object pointers [true]
[2016-07-03 14:56:10,662][INFO ][node                     ] [Boost] initialized
[2016-07-03 14:56:10,662][INFO ][node                     ] [Boost] starting ...
[2016-07-03 14:56:10,734][INFO ][transport                ] [Boost] publish_address {127.0.0.1:9300}, bound_addresses {[fe80::1]:9300}, {[::1]:9300}, {127.0.0.1:9300}
[2016-07-03 14:56:10,737][WARN ][bootstrap                ] [Boost] initial heap size [268435456] not equal to maximum heap size [2147483648]; this can cause resize pauses and prevents mlockall from locking the entire heap
[2016-07-03 14:56:10,737][WARN ][bootstrap                ] [Boost] please set [discovery.zen.minimum_master_nodes] to a majority of the number of master eligible nodes in your cluster
[2016-07-03 14:56:13,774][INFO ][cluster.service          ] [Boost] new_master {Boost}{ah2ahfU1TWKXWc4gbZOkxg}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-join(elected_as_master, [0] nodes joined)
[2016-07-03 14:56:13,792][INFO ][http                     ] [Boost] publish_address {127.0.0.1:9200}, bound_addresses {[fe80::1]:9200}, {[::1]:9200}, {127.0.0.1:9200}
[2016-07-03 14:56:13,792][INFO ][node                     ] [Boost] started
[2016-07-03 14:56:13,802][INFO ][gateway                  ] [Boost] recovered [0] indices into cluster_state
^C[2016-07-03 14:56:15,267][INFO ][node                     ] [Boost] stopping ...
[2016-07-03 14:56:15,277][INFO ][node                     ] [Boost] stopped
[2016-07-03 14:56:15,277][INFO ][node                     ] [Boost] closing ...
[2016-07-03 14:56:15,284][INFO ][node                     ] [Boost] closed
14:56:15 ⌁35% [jason:~/elasticsearch] 130 $ 
```
</details>
