### ISSUE TITLE
Create-bwc index tool fails with mapping exception

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#19253]
Trying to create a bwc index for 5.0.0-alpha4  with

    python3 dev-tools/create_bwc_index.py 5.0.0-alpha4

fails with a mapping exception:

    Traceback (most recent call last):
      File "dev-tools/create_bwc_index.py", line 461, in <module>
        main()
      File "dev-tools/create_bwc_index.py", line 457, in main
        create_bwc_index(cfg, version)
      File "dev-tools/create_bwc_index.py", line 421, in create_bwc_index
        generate_index(client, version, index_name)
      File "dev-tools/create_bwc_index.py", line 300, in generate_index
        'warmers': warmers
      File "/usr/local/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
        return func(*args, params=params, **kwargs)
      File "/usr/local/lib/python3.5/site-packages/elasticsearch/client/indices.py", line 103, in create
        params=params, body=body)
      File "/usr/local/lib/python3.5/site-packages/elasticsearch/transport.py", line 307, in perform_request
        status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
      File "/usr/local/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
        self._raise_error(response.status, raw_data)
      File "/usr/local/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
        raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
    elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception')

**Comment by clintongormley** [comment]
@rjernst could you take a look at this please?
