### ISSUE TITLE
Duplicated documents after bulk create and server restart

### ISSUE THREAD

**Issue by jt1** [elastic/elasticsearch#19286]
**Elasticsearch version**: 2.3.3

**JVM version**: OpenJDK 1.8.0_91

**OS version**: Ubuntu 16.04

**Description of the problem including expected versus actual behavior**:
Documents are not properly indexed when Elasticsearch is restarted just after bulk request is send.
Bulk request is retried because of _connection refused_ error. Finally random documents are duplicated (same content, different id) in the index.

**Steps to reproduce**:
 1. Start sending 1000 bulk requests with 100 documents each, one after another. First request example:

 ```
 curl -XPOST 'localhost:9200/_bulk' -d '
             {"index":{"_index" : "index1", "_type": "test"}}
             {"counter": "1", "package": "1/1000"}
             {"index":{"_index" : "index1", "_type": "test"}}
             {"counter": "2", "package": "1/1000"}
             ...
             {"index":{"_index" : "index1", "_type": "test"}}
             {"counter": "100", "package": "1/1000"}
 '
 ```

 2. Restart Elasticsearch just after server starts receiving requests. 
 ```sudo service elasticsearch restart```
 3. Repeat previous step couple of times.
 4. If bulk request fails (Connection refused) because of Elasticsearch restart, repeat sending request until it succeed.
 5. After all bulk requests are sent, index document count is grater then 10000.
 ```curl -XGET http://localhost:9200/index1/_count```
 {"count":**10326**,"_shards":{"total":5,"successful":5,"failed":0}}

**Provide logs (if relevant)**:
```
[2016-07-06 15:49:28,441][INFO ][node                     ] [ubuntu1-node] stopping ...
[2016-07-06 15:49:28,485][WARN ][netty.channel.DefaultChannelPipeline] An exception was thrown by an exception handler.
java.util.concurrent.RejectedExecutionException: Worker has already been shutdown
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.registerTask(AbstractNioSelector.java:120)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.executeInIoThread(AbstractNioWorker.java:72)
	at org.jboss.netty.channel.socket.nio.NioWorker.executeInIoThread(NioWorker.java:36)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.executeInIoThread(AbstractNioWorker.java:56)
	at org.jboss.netty.channel.socket.nio.NioWorker.executeInIoThread(NioWorker.java:36)
	at org.jboss.netty.channel.socket.nio.AbstractNioChannelSink.execute(AbstractNioChannelSink.java:34)
	at org.jboss.netty.channel.DefaultChannelPipeline.execute(DefaultChannelPipeline.java:636)
	at org.jboss.netty.channel.Channels.fireExceptionCaughtLater(Channels.java:496)
	at org.jboss.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:46)
	at org.jboss.netty.channel.DefaultChannelPipeline.notifyHandlerException(DefaultChannelPipeline.java:658)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:781)
	at org.jboss.netty.channel.Channels.write(Channels.java:725)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:71)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
	at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.handleDownstream(HttpPipeliningHandler.java:87)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
	at org.elasticsearch.http.netty.NettyHttpChannel.sendResponse(NettyHttpChannel.java:146)
	at org.elasticsearch.rest.action.support.RestResponseListener.processResponse(RestResponseListener.java:43)
	at org.elasticsearch.rest.action.support.RestActionListener.onResponse(RestActionListener.java:49)
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:89)
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:85)
	at org.elasticsearch.action.bulk.TransportBulkAction$2.finishHim(TransportBulkAction.java:356)
	at org.elasticsearch.action.bulk.TransportBulkAction$2.onFailure(TransportBulkAction.java:351)
	at org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:95)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.finishAsFailed(TransportReplicationAction.java:567)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$1.handleException(TransportReplicationAction.java:527)
	at org.elasticsearch.transport.TransportService$2.run(TransportService.java:206)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-07-06 15:49:28,512][WARN ][transport                ] [ubuntu1-node] Transport response handler not found of id [43]
[2016-07-06 15:49:28,863][INFO ][node                     ] [ubuntu1-node] stopped
[2016-07-06 15:49:28,863][INFO ][node                     ] [ubuntu1-node] closing ...
[2016-07-06 15:49:28,868][INFO ][node                     ] [ubuntu1-node] closed
```

**Comment by ywelsch** [comment]
Elasticsearch does not provide exactly-once delivery guarantees. If you want to avoid duplicates you can provide an explicit document id, for example:

```
curl -XPOST 'localhost:9200/_bulk' -d '
           {"index":{"_index" : "index1", "_type": "test", "_id" : "1"}}
           {"counter": "1", "package": "1/1000"}
           {"index":{"_index" : "index1", "_type": "test", "_id" : "2"}}
           {"counter": "2", "package": "1/1000"}
           ...
           {"index":{"_index" : "index1", "_type": "test", "_id" : "3"}}
           {"counter": "100", "package": "1/1000"}
'
```

**Comment by bleskes** [comment]
> Elasticsearch does not provide exactly-once delivery guarantees.

I get what Yannick means, but I'm not sure this statement is 100% clear.  The problem is more that the API you are using is built for a one off usage. The main reason is that those documents do not have an id, which means ES will auto generate a unique one. , When you send twice, ES has no way of know that they are really the same documents and it will generate a new id for those.

If you need these kind of things you should generate your own ids (see http://blog.mikemccandless.com/2014/05/choosing-fast-unique-identifier-uuid.html ) and use those in your requests. Another alternative, is to use the Ids ES returns in the response for bulks for the retries. Of course, this means you need to actually get the response and store that information.
