### ISSUE TITLE
[CI] tests.class=org.elasticsearch.ingest.useragent.UserAgentRestIT fails in 30_custom_regex.yaml

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#19307]
```
   > Throwable #1: java.lang.AssertionError: expected [2xx] status code but api [ingest.put_pipeline] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"parse_exception","reason":"[regex_file] regex file [test-regexes.yaml] doesn't exist (has to exist at node startup)","header":{"processor_type":"user_agent","property_name":"regex_file"}}],"type":"parse_exception","reason":"[regex_file] regex file [test-regexes.yaml] doesn't exist (has to exist at node startup)","header":{"processor_type":"user_agent","property_name":"regex_file"}},"status":400}]
   > 	at __randomizedtesting.SeedInfo.seed([BF3FA2D48D03AEDB:376B9D0E23FFC323]:0)
   > 	at org.elasticsearch.test.rest.section.DoSection.execute(DoSection.java:108)
   > 	at org.elasticsearch.test.rest.ESRestTestCase.test(ESRestTestCase.java:399)
   > 	at java.lang.Thread.run(Thread.java:745)
```

This is might be related to b4defafcb26ab86843bbe3464a4cf54cdc978696

Reproduces with:

```
gradle :plugins:ingest-user-agent:integTest -Dtests.seed=BF3FA2D48D03AEDB -Dtests.class=org.elasticsearch.ingest.useragent.UserAgentRestIT -Dtests.method="test {yaml=ingest-useragent/30_custom_regex/Test user agent processor with custom regex file}" -Dtests.es.logger.level=DEBUG -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=512m -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:-UseCompressedOops" -Dtests.locale=ko-KR -Dtests.timezone=Europe/Stockholm
```

**Comment by dakrone** [comment]
@martijnvg can you take a look?

**Comment by martijnvg** [comment]
@dakrone yes, I'll have a look.

**Comment by jasontedor** [comment]
@martijnvg I pushed a skip in 7d13906fcd44a4b3a9ea4deb51a35149777db5bf.
