### ISSUE TITLE
IpFieldBwCompatIT fails with seed A72FE66BDD9F236C

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#19316]
`IpFieldBwCompatIT` fails with `@Seed("A72FE66BDD9F236C")`. It times out. This is the CI failure:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=ubuntu/726/consoleFull

I'm not sure what is up with it but I don't think the failure is all that recent.

**Comment by jpountz** [comment]
@nik9000 Do you remember if that seed reproduced for you?

**Comment by nik9000** [comment]
IIRC it did, yes. It timed out when I ran the whole suite iirc.

**Comment by jpountz** [comment]
Thanks, I tried a bit more and managed to reproduce it a couple times (it does not reproduce all the time). It looks like classloading gets stuck, every time I hit this failure, a thread was stuck with the following stack trace:
```
"elasticsearch[node_sd3][search][T#2]" #60 daemon prio=5 os_prio=0 tid=0x00007feda8d48800 nid=0x30fc in Object.wait() [0x00007fed425e9000]
   java.lang.Thread.State: RUNNABLE
        at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes.<clinit>(ValuesSource.java:72)
        at org.elasticsearch.search.aggregations.support.AggregationContext.bytesField(AggregationContext.java:167)
        at org.elasticsearch.search.aggregations.support.AggregationContext.originalValuesSource(AggregationContext.java:138)
        at org.elasticsearch.search.aggregations.support.AggregationContext.valuesSource(AggregationContext.java:79)
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:51)
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:225)
        at org.elasticsearch.search.aggregations.AggregatorFactories.createTopLevelAggregators(AggregatorFactories.java:102)
        at org.elasticsearch.search.aggregations.AggregationPhase.preProcess(AggregationPhase.java:61)
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:103)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:322)
        at org.elasticsearch.search.action.SearchTransportService$SearchQueryByIdTransportHandler.messageReceived(SearchTransportService.java:323)
        at org.elasticsearch.search.action.SearchTransportService$SearchQueryByIdTransportHandler.messageReceived(SearchTransportService.java:320)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
        at org.elasticsearch.transport.TransportService$5.doRun(TransportService.java:517)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:510)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
Maybe it has something to do with instantiating a nested sub class from a static block, I could find this issue as well that might be related even though here I can only find a single thread that is waiting on initializing this class: https://bugs.openjdk.java.net/browse/JDK-8139224.
