### ISSUE TITLE
Build Failure: org.elasticsearch.search.basic.SearchWithRandomIOExceptionsIT.testRandomDirectoryIOExceptions

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#19356]
I was unable to reproduce these so far, happened twice in recent test runs:

```
gradle :core:integTest -Dtests.seed=1FFB9F0D780D57E7 -Dtests.class=org.elasticsearch.search.basic.SearchWithRandomIOExceptionsIT -Dtests.method="testRandomDirectoryIOExceptions" -Dtests.security.manager=true -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" -Dtests.locale=fr-CA -Dtests.timezone=Asia/Baku
```

Most of the exceptions in the log are expected, hard to spot the real cause, one of the two failures looks as if a thread is lingering around, the other one shows an uncaught exception for a set of lucene files.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/1062/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/1489/console

**Comment by s1monw** [comment]
@spinscale I opened a PR for this - thx for opening the issue

**Comment by abeyad** [comment]
This test still fails sporadically, though I can't get it to reproduce.  It has failed about 3 times in the last month.  Here is the console output from a CI run for one of the failures.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=sles/651/consoleFull

**Comment by s1monw** [comment]
I think this fails due to a recent refactoring...

```
ERROR   0.83s J0 | SearchWithRandomIOExceptionsIT.testRandomDirectoryIOExceptions <<< FAILURES!
   > Throwable #1: Failed to execute phase [fetch], 
   > 	at __randomizedtesting.SeedInfo.seed([DD628C72414F644:442A44EF3A521DE5]:0)
   > 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:270)
   > 	at org.elasticsearch.action.search.FetchSearchPhase$1.onFailure(FetchSearchPhase.java:93)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:581)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   > 	at java.lang.Thread.run(Thread.java:745)
   > Caused by: java.lang.NullPointerException
   > 	at org.apache.lucene.search.TopDocs$MergeSortQueue.<init>(TopDocs.java:128)
   > 	at org.apache.lucene.search.TopDocs.mergeAux(TopDocs.java:240)
   > 	at org.apache.lucene.search.TopDocs.merge(TopDocs.java:230)
   > 	at org.elasticsearch.action.search.SearchPhaseController.sortDocs(SearchPhaseController.java:265)
   > 	at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:101)
   > 	at org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:45)
   > 	at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:88)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	... 3 more

```

I will take a look at it today or tomorrow
