### ISSUE TITLE
TranslogCorruptedException while attempting to recover ES cluster (2.3.2)

### ISSUE THREAD

**Issue by jaychris** [elastic/elasticsearch#19352]
**Elasticsearch version**: 2.3.2

**JVM version**: 8u29

**OS version**: Ubuntu 16.10

**Description of the problem including expected versus actual behavior**:
After node failure, cluster fails to re-index with TranslogCorruptedException.

We have a 4-node cluster.  One of the nodes (cluster leader) failed due to a cpu failure.  The other 3 nodes were stopped while the failed node was fixed.  Once the node was fixed, the leader was brought back up and the other three nodes restarted.  Re-indexing begins, but two of the nodes start spitting out errors and the cluster fails to start/re-index.

Expected Behavior:
ES will re-index and recover the cluster to "green" health.

Actual Behavior:
Several nodes produce a stream of errors like:

```
[logstash-telemetry-2016.07.09][[logstash-telemetry-2016.07.09][3]] IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed
to create engine]; nested: TranslogCorruptedException[expected shard UUID [[68 46 45 4e 49 38 4e 74 51 65 71 61 33 36 6b 66 33 47 6e 58 56 67]] but got: [[52 6a 6b 5f 50 59 4f
46 54 6d 79 6a 4c 36 45 5a 61 76 33 51 4d 41]] this translog file belongs to a different translog];
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:250)
	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

and the cluster fails to recover.  The leader eventually reports a Java OOM exception, even though each node has more than enough heap for normal operations.

**Steps to reproduce**:
unsure.  The sequence of events was:

1.  leader crashed due to hardware failure
2.  other three nodes were stopped by hand (process, not system)
3.  leader was recovered/restarted
4.  other three nodes were started and joined the cluster
5.  two nodes immediately began reporting TranslogCorruptedException
6.  cluster continues to index, but eventually fails

**Provide logs (if relevant)**:

Errors are a repeating stream like this:
```
[logstash-telemetry-2016.07.09][[logstash-telemetry-2016.07.09][3]] IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed
to create engine]; nested: TranslogCorruptedException[expected shard UUID [[68 46 45 4e 49 38 4e 74 51 65 71 61 33 36 6b 66 33 47 6e 58 56 67]] but got: [[52 6a 6b 5f 50 59 4f
46 54 6d 79 6a 4c 36 45 5a 61 76 33 51 4d 41]] this translog file belongs to a different translog];
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:250)
	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [logstash-telemetry-2016.07.09][[logstash-telemetry-2016.07.09][3]] EngineCreationFailureException[failed to create engine]; nested: TranslogCorruptedException[expec
ted shard UUID [[68 46 45 4e 49 38 4e 74 51 65 71 61 33 36 6b 66 33 47 6e 58 56 67]] but got: [[52 6a 6b 5f 50 59 4f 46 54 6d 79 6a 4c 36 45 5a 61 76 33 51 4d 41]] this translo
g file belongs to a different translog];
	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:155)
	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1509)
	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1493)
	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:966)
	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:938)
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:241)
	... 5 more
Caused by: TranslogCorruptedException[expected shard UUID [[68 46 45 4e 49 38 4e 74 51 65 71 61 33 36 6b 66 33 47 6e 58 56 67]] but got: [[52 6a 6b 5f 50 59 4f 46 54 6d 79 6a 4
c 36 45 5a 61 76 33 51 4d 41]] this translog file belongs to a different translog]
	at org.elasticsearch.index.translog.TranslogReader.open(TranslogReader.java:235)
```

**Comment by bleskes** [comment]
That error indicates that the translog files belong to a different lucene index than the one used when opening them (we bake a uuid into both those files and make sure it matches). Can anything in your problem / how you recovered explain this? are you running on a shared failed system by any chance?

**Comment by jaychris** [comment]
We're using local volumes for each node, so I don't know how they would have gotten mixed.

In the meantime, I resolved this by restoring an earlier snapshot (from before the failure).  There might have been a little bit of lost data from the time between the snapshot and the failure, but it's minimal.  

After restoring from backup, the cluster was able to re-index successfully.

**Comment by ygokirmak** [comment]
@bleskes is there any workaround for solving such cases. I have same case where elasticsearch is running on docker and I removed docker container by mistake and seems new container has a different lucene uuid

**Comment by bleskes** [comment]
@ygokirmak I don't know exactly what happened but I found it very strange that a translog from one lucene index ended up in another's folder. Are you sure the lucene index is the one you want to have? If so you can upgrade to 5.x and use this [command line tool](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-translog.html#corrupt-translog-truncation) . Watch out though - you'd lose some data.
