### ISSUE TITLE
org.elasticsearch.bwcompat.BasicBackwardsCompatibilityIT#testIndexRollingUpgrade fails sporadically

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#19384]
Example build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+2.3+multijob-os-compatibility/os=ubuntu/181/

Exception trace:

```
java.lang.AssertionError: There are still 1 in-flight contexts
    at org.elasticsearch.search.MockSearchService.assertNoInFLightContext(MockSearchService.java:65)
    at org.elasticsearch.test.ESTestCase$2.run(ESTestCase.java:188)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:405)
    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:369)
    at org.elasticsearch.test.ESTestCase.ensureAllSearchContextsReleased(ESTestCase.java:185)
    at org.elasticsearch.test.ESIntegTestCase.after(ESIntegTestCase.java:1959)
[...]
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
    at java.lang.Thread.run(Thread.java:745)
    Suppressed: java.lang.AssertionError: There are still 1 in-flight contexts
        at org.elasticsearch.search.MockSearchService.assertNoInFLightContext(MockSearchService.java:65)
        at org.elasticsearch.test.ESTestCase$2.run(ESTestCase.java:188)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:394)
        ... 38 more
    Caused by: java.lang.RuntimeException
        at org.elasticsearch.search.MockSearchService.putContext(MockSearchService.java:80)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:623)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:371)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:300)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 more
    Suppressed: java.lang.AssertionError: There are still 1 in-flight contexts
        at org.elasticsearch.search.MockSearchService.assertNoInFLightContext(MockSearchService.java:65)
        at org.elasticsearch.test.ESTestCase$2.run(ESTestCase.java:188)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:394)
        ... 38 more
    [CIRCULAR REFERENCE:java.lang.RuntimeException]
    Suppressed: java.lang.AssertionError: There are still 1 in-flight contexts
        at org.elasticsearch.search.MockSearchService.assertNoInFLightContext(MockSearchService.java:65)
        at org.elasticsearch.test.ESTestCase$2.run(ESTestCase.java:188)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:394)
        ... 38 more
    [CIRCULAR REFERENCE:java.lang.RuntimeException]
[...]
```

Reproduces with `mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch.qa.backwards:2.2 -Dtests.seed=5A271C4709F94E84 -Dtests.class=org.elasticsearch.bwcompat.BasicBackwardsCompatibilityIT -Dtests.method="testIndexRollingUpgrade" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=es-CO -Dtests.timezone=Europe/Budapest -Dskip.integ.tests=false -Dtests.iters=1000`

Note: The circular reference is caused by the `ESTestCase.assertBusy` calling the assertion in a loop and `MockSearchService` always returning the same exception instance (this is only secondary though).

**Comment by javanna** [comment]
Given that this issue had no activity in almost a year, I would close it. We can always reopen if we encounter the same failure again.
