### ISSUE TITLE
install elasticsearch error in centos

### ISSUE THREAD

**Issue by gutasaputra** [elastic/elasticsearch#19408]
hi there, last time i install elasticsearch in windows, everything work perfectly fine now.
after some development on my application modules, now i decided to move to my server.
which in running on centos.

i have problems when installing it.
after downloading elasticsearch package.
i run this command : 
`bin/elasticsearch`

and then i got this error msg : 
```
Exception in thread "main" java.lang.RuntimeException: don't run elasticsearch as root.
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:93)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:144)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35
```
this my environment specification : 

> centos-release-6-6.el6.centos.12.2.x86_64
> java version "1.7.0_101"
> elastic version 2.3.4

i dont know what to do to fix this one.
please help me.
thanks in advance.

**Comment by dadoonet** [comment]
Please ask questions on discuss.elastic.co.

The error message is pretty clear here.
