### ISSUE TITLE
[bug report]client won't throw SearchContextMissingException when scroll timeout

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#19414]
1. ES version: 2.1.2
2. JDK version: 1.8.60
3. linux version: 2.6.32

step:
MatchAllQueryBuilder maq = QueryBuilders.matchAllQuery();
        SearchResponse sResponse = client.prepareSearch(indexName)
                .setSearchType(SearchType.SCAN)
                .setQuery(maq)
                .setScroll(new TimeValue(1))
                .setSize(20)
                .execute()
                .actionGet();

while (true) {
            SearchHits hits = sResponse.getHits();
            SearchHit[] hitArray = hits.getHits();
            sResponse = client.prepareSearchScroll(sResponse.getScrollId()).setScroll(new TimeValue(1)).execute().actionGet();
            //Break condition: No hits are returned
            if (sResponse.getHits().getHits().length == 0) {
                break;
            }
        }

when set break point on sResponse = client.prepareSearchScroll and wati for scroll timeout, server throw SearchContextMissingException but client eat this exception silently.

**Comment by makeyang** [comment]
@clintongormley  what does adoptme mean? can I pull a request to fix it on 2.1.2 or what since there won't be any release for 2.1 ?

**Comment by jasontedor** [comment]
@makeyang There will not be a release of the 2.1.x line for addressing issues like this. You're welcome to open a pull request against master.

**Comment by makeyang** [comment]
@jasontedor got it. thanks

**Comment by makeyang** [comment]
@jasontedor  it turns out that master has already fixed this issue. 
Failed to execute phase [query], all shards failed; shardFailures {RemoteTransportException[[192.168.200.191][192.168.200.191:9505][indices:data/read/search[phase/query/scroll]]]; nested: SearchContextMissingException[No search context found for id [1]]; }{RemoteTransportException[[192.168.200.191][192.168.200.191:9505][indices:data/read/search[phase/query/scroll]]]; nested: SearchContextMissingException[No search context found for id [4]]; }{RemoteTransportException[[192.168.200.191][192.168.200.191:9505][indices:data/read/search[phase/query/scroll]]]; nested: SearchContextMissingException[No search context found for id [3]]; }{RemoteTransportException[[192.168.200.191][192.168.200.191:9505][indices:data/read/search[phase/query/scroll]]]; nested: SearchContextMissingException[No search context found for id [5]]; }{RemoteTransportException[[192.168.200.191][192.168.200.191:9505][indices:data/read/search[phase/query/scroll]]]; nested: SearchContextMissingException[No search context found for id [2]]; }
	at org.elasticsearch.action.search.SearchScrollQueryThenFetchAsyncAction.onQueryPhaseFailure(SearchScrollQueryThenFetchAsyncAction.java:155)
	at org.elasticsearch.action.search.SearchScrollQueryThenFetchAsyncAction$1.onFailure(SearchScrollQueryThenFetchAsyncAction.java:142)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:934)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1035)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1013)
	at org.elasticsearch.transport.TransportService$5.onFailure(TransportService.java:528)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:496)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by martijnvg** [comment]
This has been fixed a long time ago in master.
