### ISSUE TITLE
[CI] org.elasticsearch.backwards.MultiNodeBackwardsIT.test {p0=indices.shrink/10_basic/Shrink index via API} fails when multiple nodes are present

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#19419]
The REST test for the shrink API fails:

```
Suite: org.elasticsearch.backwards.MultiNodeBackwardsIT
  1> [2016-07-13 08:28:05,799][INFO ][org.elasticsearch.test.rest.client] REST client initialized [http://[::1]:33103], elasticsearch version: [5.0.0-alpha5]
  1> [2016-07-13 08:28:05,807][INFO ][org.elasticsearch.test.rest.client] REST client initialized [http://[::1]:33103], elasticsearch version: [5.0.0-alpha5]
  1> [2016-07-13 08:28:06,346][INFO ][org.elasticsearch.backwards] Stash dump on failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "cluster_name" : "qa_backwards-5.0_integTest",
  1>       "status" : "green",
  1>       "timed_out" : false,
  1>       "number_of_nodes" : 2,
  1>       "number_of_data_nodes" : 2,
  1>       "active_primary_shards" : 5,
  1>       "active_shards" : 5,
  1>       "relocating_shards" : 0,
  1>       "initializing_shards" : 0,
  1>       "unassigned_shards" : 0,
  1>       "delayed_unassigned_shards" : 0,
  1>       "number_of_pending_tasks" : 0,
  1>       "number_of_in_flight_fetch" : 0,
  1>       "task_max_waiting_in_queue_millis" : 0,
  1>       "active_shards_percent_as_number" : 100.0
  1>     },
  1>     "master" : "sBM60RLuTiuBlZutXBWnGg"
  1>   }
  1> }]
  2> REPRODUCE WITH: gradle :qa:backwards-5.0:integTest -Dtests.seed=529E08C5D51BBDF9 -Dtests.class=org.elasticsearch.backwards.MultiNodeBackwardsIT -Dtests.method="test {p0=indices.shrink/10_basic/Shrink index via API}" -Dtests.security.manager=true -Dtests.locale=es-MX -Dtests.timezone=Indian/Chagos
FAILURE 0.75s | MultiNodeBackwardsIT.test {p0=indices.shrink/10_basic/Shrink index via API} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected [2xx] status code but api [indices.shrink] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"illegal_state_exception","reason":"index source must have all shards allocated on the same node to shrink index"}],"type":"illegal_state_exception","reason":"index source must have all shards allocated on the same node to shrink index"},"status":500}]
   > 	at __randomizedtesting.SeedInfo.seed([529E08C5D51BBDF9:DACA371F7BE7D001]:0)
   > 	at org.elasticsearch.test.rest.section.DoSection.execute(DoSection.java:108)
   > 	at org.elasticsearch.test.rest.ESRestTestCase.test(ESRestTestCase.java:399)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> NOTE: leaving temporary files on disk at: /home/hinmanm/es/elasticsearch/qa/backwards-5.0/build/testrun/integTest/J0/temp/org.elasticsearch.backwards.MultiNodeBackwardsIT_529E08C5D51BBDF9-004
  2> NOTE: test params are: codec=Asserting(Lucene60): {}, docValues:{}, maxPointsInLeafNode=806, maxMBSortInHeap=6.315786973231347, sim=RandomSimilarity(queryNorm=true,coord=crazy): {}, locale=es-MX, timezone=Indian/Chagos
  2> NOTE: Linux 4.6.3-300.fc24.x86_64 amd64/Oracle Corporation 1.8.0_92 (64-bit)/cpus=8,threads=1,free=417462824,total=514850816
  2> NOTE: All tests run in this JVM: [MultiNodeBackwardsIT]
Completed [1/1] in 0.99s, 1 test, 1 failure <<< FAILURES!
```

Reproduction line (reproduces every time for me):

```
gradle :qa:backwards-5.0:integTest -Dtests.seed=529E08C5D51BBDF9 -Dtests.class=org.elasticsearch.backwards.MultiNodeBackwardsIT -Dtests.method="test {p0=indices.shrink/10_basic/Shrink index via API}" -Dtests.security.manager=true -Dtests.locale=es-MX -Dtests.timezone=Indian/Chagos
```

I'm guessing this is because the test assumes that there will only be a single node, but there are two present for the backwards compatibility tests.

**Comment by s1monw** [comment]
@dakrone where did you see this, are there any node logs etc. this has nothing todo with 2 nodes, it should work as it waits for the relocation

**Comment by s1monw** [comment]
I think I know what the problem is, the test doesn't wait for all shards to be active before it uses allocation filtering so the settings call might return successfully but the wait call that happens next is returning immediately since the next reroute is not fully applied and the shard has not yet been relocated. Allocation filtering ie. canRemain is only called on started shards which might not be the case...

**Comment by dakrone** [comment]
@s1monw I was seeing this running tests on master on my desktop. It previously reproduced every time but it's fixed now, thanks for fixing!
