### ISSUE TITLE
Need to validate index.merge.scheduler.max_thread_count input?

### ISSUE THREAD

**Issue by joshuar** [elastic/elasticsearch#19444]
**Elasticsearch version**:
2.x - 5.x

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

It looks like if one is to set "bad" values for `index.merge.scheduler.max_thread_count` it can cause exceptions to be thrown continually in the logs 

**Steps to reproduce**:

Set the value to something crazy:

Request:
```
PUT /test/_settings
{
    "index.merge.scheduler.max_thread_count": "500"
  
}
```

Response:
```
{
  "acknowledged": true
}
```

But  in the logs:

```
es_1 | [2016-07-15 08:56:13,804][INFO ][index.shard              ] [escluster1_es_1] [test][0] updating [index.merge.scheduler.max_thread_count] from [7] to [500]
es_1 | [2016-07-15 08:56:13,805][WARN ][index.settings           ] [escluster1_es_1] [test] failed to refresh settings for [org.elasticsearch.index.shard.IndexShard$ApplyRefreshSettings@5903b92]
es_1 | java.lang.IllegalArgumentException: maxThreadCount should be <= maxMergeCount (= 7)
es_1 | 	at org.apache.lucene.index.ConcurrentMergeScheduler.setMaxMergesAndThreads(ConcurrentMergeScheduler.java:154)
es_1 | 	at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.refreshConfig(ElasticsearchConcurrentMergeScheduler.java:176)
es_1 | 	at org.elasticsearch.index.engine.InternalEngine.onSettingsChanged(InternalEngine.java:1272)
es_1 | 	at org.elasticsearch.index.shard.IndexShard$ApplyRefreshSettings.onRefreshSettings(IndexShard.java:1325)
es_1 | 	at org.elasticsearch.index.settings.IndexSettingsService.refreshSettings(IndexSettingsService.java:54)
es_1 | 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applySettings(IndicesClusterStateService.java:322)
es_1 | 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:169)
es_1 | 	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:610)
es_1 | 	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
es_1 | 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
es_1 | 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
es_1 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
es_1 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
es_1 | 	at java.lang.Thread.run(Thread.java:745)
``` 

Indexing appears to work:

Request:
```
PUT test/t/1
{
  "foo": "bar"
}
```

Response:
```
{
  "_index": "test",
  "_type": "t",
  "_id": "1",
  "_version": 1,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "created": false
}
```

But in the logs:

```
es_1 | [2016-07-15 08:56:23,897][INFO ][cluster.metadata         ] [escluster1_es_1] [test] create_mapping [t]
es_1 | [2016-07-15 08:56:30,799][WARN ][index.shard              ] [escluster1_es_1] [test][0] Failed to perform scheduled engine refresh
es_1 | java.lang.IllegalArgumentException: maxThreadCount should be <= maxMergeCount (= 7)
es_1 | 	at org.apache.lucene.index.ConcurrentMergeScheduler.setMaxMergesAndThreads(ConcurrentMergeScheduler.java:154)
es_1 | 	at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.refreshConfig(ElasticsearchConcurrentMergeScheduler.java:176)
es_1 | 	at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:688)
es_1 | 	at org.elasticsearch.index.shard.IndexShard.refresh(IndexShard.java:661)
es_1 | 	at org.elasticsearch.index.shard.IndexShard$EngineRefresher$1.run(IndexShard.java:1343)
es_1 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
es_1 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
es_1 | 	at java.lang.Thread.run(Thread.java:745)
```

This looks to be harmless, but do need to test more when under indexing and search load.

**Comment by jasontedor** [comment]
Superseded by #20380
