### ISSUE TITLE
Mapper-attachments access denied while trying to find windows font directory

### ISSUE THREAD

**Issue by Skoucail** [elastic/elasticsearch#19471]
**Elasticsearch version**: 2.3.4 (With plugin mapper-attachments)

**JVM version**: 8 update 91 (build 1.8.0_91-b14)

**OS version**: Windows Server 2012R2

**Description of the problem including expected versus actual behavior**:
When indexing the first PDF with the mapper-attachments plugin i get an error when pdfbox tries to find the windows directory witch contains the windows font.
This trows a access denied exeption (tried to run under different users always getting access denied)
Then for every PDF without embedded fonts i get a warning that the font cant be found

**Steps to reproduce**:
1. Start up elasticsearch-service-x64.exe (make sure the mapper-attachments plugin is installed before starting)
2. Index a PDF file without embedded font
3. Check the logging

**Provide logs (if relevant)**:
[2016-07-18 14:05:54,930][ERROR][org.apache.pdfbox.pdmodel.font.PDSimpleFont] Can't determine the width of the space character using 250 as default
java.security.AccessControlException: access denied ("java.io.FilePermission" "<<ALL FILES>>" "execute")
    at java.security.AccessControlContext.checkPermission(Unknown Source)
    at java.security.AccessController.checkPermission(Unknown Source)
    at java.lang.SecurityManager.checkPermission(Unknown Source)
    at java.lang.SecurityManager.checkExec(Unknown Source)
    at java.lang.ProcessBuilder.start(Unknown Source)
    at java.lang.Runtime.exec(Unknown Source)
    at java.lang.Runtime.exec(Unknown Source)
    at java.lang.Runtime.exec(Unknown Source)
    at org.apache.fontbox.util.autodetect.WindowsFontDirFinder.getWinDir(WindowsFontDirFinder.java:50)
    at org.apache.fontbox.util.autodetect.WindowsFontDirFinder.find(WindowsFontDirFinder.java:79)
    at org.apache.fontbox.util.autodetect.FontFileFinder.find(FontFileFinder.java:74)
    at org.apache.fontbox.util.FontManager.loadFonts(FontManager.java:65)
    at org.apache.fontbox.util.FontManager.findTTFontname(FontManager.java:290)
    at org.apache.fontbox.util.FontManager.findTTFont(FontManager.java:326)
    at org.apache.pdfbox.pdmodel.font.PDTrueTypeFont.getTTFFont(PDTrueTypeFont.java:638)
    at org.apache.pdfbox.pdmodel.font.PDTrueTypeFont.getFontWidth(PDTrueTypeFont.java:673)
    at org.apache.pdfbox.pdmodel.font.PDSimpleFont.getFontWidth(PDSimpleFont.java:231)
    at org.apache.pdfbox.pdmodel.font.PDSimpleFont.getSpaceWidth(PDSimpleFont.java:533)
    at org.apache.pdfbox.util.PDFStreamEngine.processEncodedText(PDFStreamEngine.java:355)
    at org.apache.pdfbox.util.operator.ShowText.process(ShowText.java:50)
    at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:557)
    at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:268)
    at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:235)
    at org.apache.pdfbox.util.PDFStreamEngine.processStream(PDFStreamEngine.java:215)
    at org.apache.pdfbox.util.PDFTextStripper.processPage(PDFTextStripper.java:458)
    at org.apache.pdfbox.util.PDFTextStripper.processPages(PDFTextStripper.java:383)
    at org.apache.pdfbox.util.PDFTextStripper.writeText(PDFTextStripper.java:342)
    at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:148)
    at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:148)
    at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
    at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120)
    at org.apache.tika.Tika.parseToString(Tika.java:537)
    at org.elasticsearch.mapper.attachments.TikaImpl$1.run(TikaImpl.java:94)
    at org.elasticsearch.mapper.attachments.TikaImpl$1.run(TikaImpl.java:91)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.elasticsearch.mapper.attachments.TikaImpl.parse(TikaImpl.java:91)
    at org.elasticsearch.mapper.attachments.AttachmentMapper.parse(AttachmentMapper.java:481)
    at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:309)
    at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:326)
    at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:252)
    at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:122)
    at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309)
    at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:580)
    at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:559)
    at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:212)
    at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:224)
    at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:327)
    at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:120)
    at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:68)
    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:639)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:271)
    at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
    at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
[2016-07-18 14:05:57,078][WARN ][org.apache.fontbox.util.FontManager] Font not found: TimesNewRomanPSMT
[2016-07-18 14:05:57,105][WARN ][org.apache.fontbox.util.FontManager] Font not found: TimesNewRomanPSMT
[2016-07-18 14:05:57,711][WARN ][org.apache.fontbox.util.FontManager] Font not found: TimesNewRomanPSMT
[2016-07-18 14:05:57,748][WARN ][org.apache.fontbox.util.FontManager] Font not found: TimesNewRomanPSMT
[2016-07-18 14:05:57,850][WARN ][org.apache.fontbox.util.FontManager] Font not found: TimesNewRomanPSMT
[2016-07-18 14:05:57,867][WARN ][org.apache.fontbox.util.FontManager] Font not found: TimesNewRomanPSMT
[2016-07-18 14:05:59,040][WARN ][org.apache.fontbox.util.FontManager] Font not found: TimesNewRomanPSMT
[2016-07-18 14:05:59,057][WARN ][org.apache.fontbox.util.FontManager] Font not found: TimesNewRomanPSMT
[2016-07-18 14:05:59,081][WARN ][org.apache.fontbox.util.FontManager] Font not found: TimesNewRomanPSMT
[2016-07-18 14:05:59,131][WARN ][org.apache.fontbox.util.FontManager] Font not found: TimesNewRomanPSMT
[2016-07-18 14:05:59,142][WARN ][org.apache.fontbox.util.FontManager] Font not found: TimesNewRomanPSMT
[2016-07-18 14:05:59,154][WARN ][org.apache.fontbox.util.FontManager] Font not found: TimesNewRomanPSMT
[2016-07-18 14:05:59,557][WARN ][org.apache.fontbox.util.FontManager] Font not found: TimesNewRomanPSMT
[2016-07-18 14:05:59,565][WARN ][org.apache.fontbox.util.FontManager] Font not found: TimesNewRomanPSMT
[2016-07-18 14:05:59,572][WARN ][org.apache.fontbox.util.FontManager] Font not found: CourierNewPSMT
[2016-07-18 14:05:59,579][WARN ][org.apache.fontbox.util.FontManager] Font not found: TimesNewRomanPSMT

**Comment by rmuir** [comment]
The bug is in fontbox code, which tries to execute a process, but doesn't handle securityexception:

https://github.com/apache/pdfbox/blob/trunk/fontbox/src/main/java/org/apache/fontbox/util/autodetect/WindowsFontDirFinder.java#L81-L84

We could add a hack/workaround, to deliver it the IOException it wants instead of SecurityException instead, but fontbox needs to be fixed, otherwise the hack never goes away, and its unclear how well this would work anyway, looks like if it makes it past this point, the code will just continue to try to do sheisty stuff with system files, likely unsuccessfully :)

**Comment by Skoucail** [comment]
Well i see they released a few new versions too.
I tried the mapper with the latest 1.x version but there the problem is still in it.
I couldn't get the mapper to work with the newest 2.x version. I guess the API changes are to big compared with the 1.x version.

Do you know what the practical impact is of this problem?
Can i still reliably use the plugin in a production environment?
Because for my small testset of data my searches still hit on the correct PDFs, but of course all the errors en warning in the log do not give me a confident feeling...

**Comment by rmuir** [comment]
With system fonts, PDF processing implies font fallbacks and such, because you didn't include the exact font you used, and it may not be available to the receiving end.

Even if you ignore this problem, and tika had access to all the system fonts, you'd always have to be prepared that the font for a particular document may not be installed server-side, and it may have to fall back to an approximation that isn't based on the true mapping, but may map some glyphs to characters incorrectly and give a lower quality extraction.

I'm guessing your tested PDFs might only/mostly contain 7-bit ascii, which is usually 1:1 in mappings for these fonts: so they happen to work correctly/mostly correctly via a fallback anyway, even though "font not found".

The easiest improvement would be to remove the ERROR via the hack I suggest above (+ fixing fontbox). Its still not going to give access to any system fonts, it will simply reduce noise.

**Comment by rmuir** [comment]
It should go without saying: i don't think we should expose system fonts (unrelated to security) because then different nodes could index the same document in different ways: that's just a source of potential confusion or inconsistency.

Allowing users to configure a directory fonts in some way for this purpose? I haven't looked at the mappings that fontbox provides, don't have any clue if its "enough", and i'm unsure if we want the complexity. Most PDFs really use `embedded` or `embedded subset`, otherwise they are not really "portable".

**Comment by rmuir** [comment]
An even simpler improvement might be to silence this error in the logs such as what happened with AWS: https://github.com/elastic/elasticsearch/blob/master/distribution/src/main/resources/config/logging.yml#L14-L16

unfortunately my experience with that is, people will continue to report confusion unless they are installing new from scratch. but its easier.

**Comment by Skoucail** [comment]
Yes i agree that it would be easier with fonts embedded but there isn't always a choice. For example PDFs users upload.

Guess for now i will just have to ignore the errors and hope for a bugfix in fontbox...

**Comment by SKumarMN** [comment]
I too encounter the same issue 

ES 2.3.2 with mapper-attachment plugin

[2016-08-31 08:56:03,867][ERROR][org.apache.pdfbox.pdmodel.font.PDSimpleFont] Can't determine the width of the space character using 250 as default
java.security.AccessControlException: access denied ("java.io.FilePermission" "/opt/weblogic/.fonts" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at java.io.File.exists(File.java:814)
	at org.apache.fontbox.util.autodetect.NativeFontDirFinder.find(NativeFontDirFinder.java:44)
	at org.apache.fontbox.util.autodetect.FontFileFinder.find(FontFileFinder.java:74)
	at org.apache.fontbox.util.FontManager.loadFonts(FontManager.java:65)
	at org.apache.fontbox.util.FontManager.findTTFontname(FontManager.java:290)
	at org.apache.fontbox.util.FontManager.findTTFont(FontManager.java:326)
	at org.apache.pdfbox.pdmodel.font.PDTrueTypeFont.getTTFFont(PDTrueTypeFont.java:638)
	at org.apache.pdfbox.pdmodel.font.PDTrueTypeFont.getFontWidth(PDTrueTypeFont.java:673)
	at org.apache.pdfbox.pdmodel.font.PDSimpleFont.getFontWidth(PDSimpleFont.java:231)
	at org.apache.pdfbox.pdmodel.font.PDSimpleFont.getSpaceWidth(PDSimpleFont.java:533)
	at org.apache.pdfbox.util.PDFStreamEngine.processEncodedText(PDFStreamEngine.java:355)
	at org.apache.pdfbox.util.operator.ShowTextGlyph.process(ShowTextGlyph.java:62)
	at org.apache.pdfbox.util.PDFStreamEngine.processOperator(PDFStreamEngine.java:557)
	at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:268)
	at org.apache.pdfbox.util.PDFStreamEngine.processSubStream(PDFStreamEngine.java:235)
	at org.apache.pdfbox.util.PDFStreamEngine.processStream(PDFStreamEngine.java:215)
	at org.apache.pdfbox.util.PDFTextStripper.processPage(PDFTextStripper.java:458)
	at org.apache.pdfbox.util.PDFTextStripper.processPages(PDFTextStripper.java:383)
	at org.apache.pdfbox.util.PDFTextStripper.writeText(PDFTextStripper.java:342)
	at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:148)
	at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:148)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120)
	at org.apache.tika.Tika.parseToString(Tika.java:537)
	at org.elasticsearch.mapper.attachments.TikaImpl$1.run(TikaImpl.java:94)
	at org.elasticsearch.mapper.attachments.TikaImpl$1.run(TikaImpl.java:91)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.mapper.attachments.TikaImpl.parse(TikaImpl.java:91)
	at org.elasticsearch.mapper.attachments.AttachmentMapper.parse(AttachmentMapper.java:481)
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:309)
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:436)
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:262)
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:122)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309)
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:580)
	at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:559)
	at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:212)
	at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:224)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:326)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:119)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:68)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:639)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:271)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by talevy** [comment]
Closing since there is no progress on this and mapper-attachment plugin has been deprecated in favor of Ingest-Attachment Processor Plugin
