### ISSUE TITLE
org.elasticsearch.search.aggregations.bucket.DateHistogramIT#testDSTEndTransition fails sporadically

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#19481]
Reproduces locally sometimes, need to run with a high iteration count to get it to trigger.

Example build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=oraclelinux/790/console

```
> REPRODUCE WITH: gradle :core:integTest -Dtests.seed=82560A64C52E117E -Dtests.class=org.elasticsearch.search.aggregations.bucket.DateHistogramIT -Dtests.method="testDSTEndTransition { seed=[82560A64C52E117E:58332BC3718193E2]}" -Dtests.security.manager=true -Dtests.locale=pl -Dtests.timezone=Asia/Bahrain
FAILURE 0.06s | DateHistogramIT.testDSTEndTransition { seed=[82560A64C52E117E:58332BC3718193E2]} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Serialization failed with version [5.0.0-alpha5] bytes should be equal for streamable [org.elasticsearch.search.internal.ShardSearchTransportRequest@77143156]
   > Expected: <org.elasticsearch.common.bytes.PagedBytesReference@87c05c74>
   >      but: was <org.elasticsearch.common.bytes.PagedBytesReference@bf413521>
   >     at __randomizedtesting.SeedInfo.seed([82560A64C52E117E:58332BC3718193E2]:0)
   >     at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >     at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertVersionSerializable(ElasticsearchAssertions.java:667)
   >     at org.elasticsearch.test.transport.AssertingLocalTransport.sendRequest(AssertingLocalTransport.java:93)
   >     at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:470)
   >     at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:438)
   >     at org.elasticsearch.search.action.SearchTransportService.sendExecuteQuery(SearchTransportService.java:141)
   >     at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction.sendExecuteFirstPhase(SearchQueryThenFetchAsyncAction.java:66)
   >     at org.elasticsearch.action.search.AbstractSearchAsyncAction.performFirstPhase(AbstractSearchAsyncAction.java:162)
   >     at org.elasticsearch.action.search.AbstractSearchAsyncAction.start(AbstractSearchAsyncAction.java:143)
   >     at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:96)
   >     at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:45)
   >     at org.elasticsearch.action.support.TransportAction.doExecute(TransportAction.java:158)
   >     at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:182)
   >     at org.elasticsearch.action.ingest.IngestActionFilter.apply(IngestActionFilter.java:80)
   >     at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:180)
   >     at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:153)
   >     at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:87)
   >     at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:75)
   >     at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:64)
   >     at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:403)
   >     at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
   >     at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
   >     at org.elasticsearch.search.aggregations.bucket.DateHistogramIT.testDSTEndTransition(DateHistogramIT.java:1196)
   >     at java.lang.Thread.run(Thread.java:745)
```

Reproduce with:
```
gradle :core:integTest -Dtests.seed=82560A64C52E117E -Dtests.class=org.elasticsearch.search.aggregations.bucket.DateHistogramIT -Dtests.method="testDSTEndTransition" -Dtests.security.manager=true -Dtests.locale=pl -Dtests.timezone=Asia/Bahrain
```

(May need `-Dtests.iters=50` or similar)

**Comment by polyfractal** [comment]
@nik9000 is this perhaps fallout from the recent NamedWriteable changes (e.g. d14e06ce515862ba941308ff80711c98e0fd4be0)

**Comment by nik9000** [comment]
I'll have a look then.

**Comment by nik9000** [comment]
I've figured it out. I don't think it is NamedWriteable related but I don't know what else might have caused it. Should have a PR up for it in a bit. Maybe in the morning.
