### ISSUE TITLE
[CI] org.elasticsearch.backwards.MultiNodeBackwardsIT.test {p0=search.aggregation/20_terms/Double test} fails

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#19487]
Reliably fails.  I tried to go back and git bisect, but was unable to find a recent non-failing commit.

Example failure: http://build-us-00.elastic.co/job/es_core_master_windows-2012-r2/3563/

```
ERROR   30.9s | MultiNodeBackwardsIT.test {p0=search.aggregation/20_terms/Double test} <<< FAILURES!
   > Throwable #1: java.net.SocketTimeoutException: Read timed out
   >    at __randomizedtesting.SeedInfo.seed([4A8B947DEF21C44D:C2DFABA741DDA9B5]:0)
   >    at java.net.SocketInputStream.socketRead0(Native Method)
   >    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
   >    at java.net.SocketInputStream.read(SocketInputStream.java:170)
   >    at java.net.SocketInputStream.read(SocketInputStream.java:141)
   >    at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
   >    at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
   >    at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
   >    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
   >    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
   >    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
   >    at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
   >    at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
   >    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
   >    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
   >    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
   >    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
   >    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
   >    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
   >    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
   >    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:117)
   >    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:194)
   >    at org.elasticsearch.test.rest.client.RestTestClient.callApi(RestTestClient.java:245)
   >    at org.elasticsearch.test.rest.RestTestExecutionContext.callApiInternal(RestTestExecutionContext.java:109)
   >    at org.elasticsearch.test.rest.RestTestExecutionContext.callApi(RestTestExecutionContext.java:77)
   >    at org.elasticsearch.test.rest.section.DoSection.execute(DoSection.java:92)
   >    at org.elasticsearch.test.rest.ESRestTestCase.test(ESRestTestCase.java:390)
   >    at java.lang.Thread.run(Thread.java:745)

```

Reliably reproduces with:

```
gradle :qa:backwards-5.0:integTest -Dtests.seed=4A8B947DEF21C44D -Dtests.class=org.elasticsearch.backwards.MultiNodeBackwardsIT -Dtests.method="test {p0=search.aggregation/20_terms/Double test}" -Dtests.es.logger.level=DEBUG -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=512m -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:+UseCompressedOops -XX:+AggressiveOpts" -Dtests.locale=en-GB -Dtests.timezone=Etc/GMT-10
```

FWIW, I tested on the entire suite (not just the "Double Test" test) and they all fail with the same timeout:

```
gradle :qa:backwards-5.0:integTest -Dtests.seed=4A8B947DEF21C44D -Dtests.class=org.elasticsearch.backwards.MultiNodeBackwardsIT  -Dtests.es.logger.level=DEBUG -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=512m -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:+UseCompressedOops -XX:+AggressiveOpts" -Dtests.locale=en-GB -Dtests.timezone=Etc/GMT-10
```

I have no idea how to debug these bwc tests however, sorry :(

**Comment by awislowski** [comment]
Test was renamed. From MultiNodeBackwardsIT to Backwards50ClientYamlTestSuiteIT in the commit: 9270e8b22b2df5ae09726464419c179e18d9a3a7

Now test is successful:
```
gradle :qa:backwards-5.0:integTest -Dtests.seed=4A8B947DEF21C44D -Dtests.class=org.elasticsearch.backwards.Backwards50ClientYamlTestSuiteIT -Dtests.method="test {p0=search.aggregation/20_terms/Double test}" -Dtests.es.logger.level=DEBUG -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=512m -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:+UseCompressedOops -XX:+AggressiveOpts" -Dtests.locale=en-GB -Dtests.timezone=Etc/GMT-10
```

It could be closed

**Comment by s1monw** [comment]
fixed, closing
