### ISSUE TITLE
ActiveShardsObserverIT#testCreateIndexNotEnoughActiveShardsTimesOut fails

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#19530]
The test failed only once in CI:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+java9-periodic/673/

The test itself succeeds actually, the problem is in the after test checks:

```
FAILURE 5.30s J1 | ActiveShardsObserverIT.testCreateIndexNotEnoughActiveShardsTimesOut <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Shard [test-idx][6] is still locked after 5 sec waiting
   > 	at __randomizedtesting.SeedInfo.seed([CAB167E7B91DDDA2:F4E0B8D9B6F84C47]:0)
   > 	at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:1913)
   > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:550)
   > 	at org.elasticsearch.test.ESIntegTestCase.after(ESIntegTestCase.java:1980)
   > 	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
   > 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-ea/DelegatingMethodAccessorImpl.java:43)
   > 	at java.lang.Thread.run(java.base@9-ea/Thread.java:843)
```

I failed to repro this locally with same seed and many iterations.

**Comment by javanna** [comment]
@abeyad I see that this test was recently created by you, I thought you may want to have a look at it, also you must be familiar with it. Assigning you then.
