### ISSUE TITLE
Reproducible HistogramTests.testEmptyWithExtendedBounds jenkins failure

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#19558]
**Elasticsearch version**: 2.4

**JVM version**: OpenJDK 

**OS version**: Ubuntu 16.04 (Jenkins Fedora)

**Description of the problem including expected versus actual behavior**:

This test failure reproduces. It looks like an inconsistency between computed array sizes and expected results.

**Steps to reproduce**:
 1. Run maven command:
```
mvn test -Pdev -pl org.elasticsearch.module:lang-groovy -Dtests.seed=837BA5E6FB749C36 -Dtests.class=org.elasticsearch.messy.tests.HistogramTests -Dtests.method="testEmptyWithExtendedBounds" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=cs-CZ -Dtests.timezone=UTC
```

**Provide logs (if relevant)**:

```
2> REPRODUCE WITH: mvn test -Pdev -pl org.elasticsearch.module:lang-groovy -Dtests.seed=837BA5E6FB749C36 -Dtests.class=org.elasticsearch.messy.tests.HistogramTests -Dtests.method="testEmptyWithExtendedBounds" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=cs-CZ -Dtests.timezone=UTC
ERROR   0.05s J2 | HistogramTests.testEmptyWithExtendedBounds <<<
   > Throwable #1: java.lang.ArrayIndexOutOfBoundsException
   > 	at __randomizedtesting.SeedInfo.seed([837BA5E6FB749C36:9A82DD869F535877]:0)
   > 	at java.lang.System.arraycopy(Native Method)
   > 	at org.elasticsearch.messy.tests.HistogramTests.testEmptyWithExtendedBounds(HistogramTests.java:1005)
   > 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jpountz** [comment]
Closed by #19559
