### ISSUE TITLE
Upgrade repository type which is not accepted after 1.7

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#19570]
Reported at https://discuss.elastic.co/t/s3-snapshot-repositories-not-working-after-upgrade-from-1-7-to-2-3/56214
## Reproduction steps:
- Start a new 1.7.5 node:

``` sh
bin/elasticsearch -Des.path.repo=/tmp
```
- Create a repository using type `FS`:

```
curl -XPUT 'http://localhost:9200/_snapshot/my_backup' -d '{
    "type": "Fs",
    "settings": {
        "location": "/tmp"
    }
}'
```

Note that we use `Fs` here. So the Class which is Loaded is `FsRepositoryModule`. 
If we use `fs`, same class `FsRepositoryModule` is loaded. If we use `FS` it fails because class `FSRepositoryModule` does not exist.

Why is this important? In the context of S3 repositories, `S3` or `s3` will be allowed in 1.7 as they all try to load `S3RepositoryModule`: https://github.com/elastic/elasticsearch-cloud-aws/blob/es-1.7/src/main/java/org/elasticsearch/repositories/s3/S3RepositoryModule.java.
- Stop 1.7.5 node
- Move data dir to a new empty 2.3.3 node:

``` sh
mv elasticsearch-1.7.5/data elasticsearch-2.3.3
```
- Start 2.3.3 node:

``` sh
bin/elasticsearch -Des.path.repo=/tmp
```

It fails with:

```
[2016-07-25 10:59:09,295][WARN ][repositories             ] [Kleinstocks] failed to create repository [my_backup]
RepositoryException[[my_backup] failed to create repository]; nested: IllegalArgumentException[Unknown [repository] type [Fs]];
    at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:411)
    at org.elasticsearch.repositories.RepositoriesService.clusterChanged(RepositoriesService.java:299)
    at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:610)
    at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unknown [repository] type [Fs]
    at org.elasticsearch.common.util.ExtensionPoint$SelectedType.bindType(ExtensionPoint.java:146)
    at org.elasticsearch.repositories.RepositoryTypesRegistry.bindType(RepositoryTypesRegistry.java:49)
    at org.elasticsearch.repositories.RepositoryModule.configure(RepositoryModule.java:58)
    at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
    at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:233)
    at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:105)
    at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:143)
    at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
    at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:157)
    at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:55)
    at org.elasticsearch.repositories.RepositoriesService.createRepositoryHolder(RepositoriesService.java:404)
    ... 8 more
```
## Bug source

From 2.x [we compare repository names](https://github.com/elastic/elasticsearch/blob/2.4/core/src/main/java/org/elasticsearch/repositories/RepositoriesService.java#L361) with what is defined in https://github.com/elastic/elasticsearch/blob/2.4/core/src/main/java/org/elasticsearch/repositories/fs/FsRepository.java#L51
## How to solve this

Proposal 1: well, it's just about creating repositories so people are loosing any data if they have to recreate a repository from scratch.

``` sh
curl -XPUT 'http://localhost:9200/_snapshot/my_backup'
# Then create the repository with correct settings
```

We should probably add this to the breaking changes and to the migration plugin.

Proposal 2: more complicated: automatically upgrade an existing repository which fails at startup with its lowercase form and write again this new version of the repository.

Thoughts?

**Comment by dadoonet** [comment]
@imotov What do you think?

**Comment by clintongormley** [comment]
>  it's just about creating repositories so people are loosing any data if they have to recreate a repository from scratch.

Is this true?  I thought we left the data in the repo intact.

**Comment by imotov** [comment]
@clintongormley I think David just missed "not" in this sentence. I think it should read "it's just about creating repositories so people are **not** loosing any data"

**Comment by clintongormley** [comment]
Phew, ok :)

In which case I would just go for strict validation.  Bonus points for "did you mean?"

**Comment by dadoonet** [comment]
Ooops. Sorry. Indeed. "Not" is an important missing word here. :)

**Comment by dadoonet** [comment]
I think we can close this very old one.
