### ISSUE TITLE
[CI] org.elasticsearch.common.bytes.BytesArrayTests.testSliceArrayOffset fails

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#19582]
This failure reproduces every time for me with:

```
gradle :core:test -Dtests.seed=42EED4DE0EE5FB95 -Dtests.class=org.elasticsearch.common.bytes.BytesArrayTests -Dtests.method="testSliceArrayOffset" -Dtests.es.logger.level=DEBUG -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=560m -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:-UseCompressedOops" -Dtests.locale=nl-NL -Dtests.timezone=Africa/Lubumbashi
```

Seen here: http://build-us-00.elastic.co/job/es_core_master_windows-2012-r2/3609/console

```
  2> REPRODUCE WITH: gradle :core:test -Dtests.seed=42EED4DE0EE5FB95 -Dtests.class=org.elasticsearch.common.bytes.BytesArrayTests -Dtests.method="testSliceArrayOffset" -Dtests.es.logger.level=DEBUG -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=560m -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:-UseCompressedOops" -Dtests.locale=nl-NL -Dtests.timezone=Africa/Lubumbashi
FAILURE 0.07s | BytesArrayTests.testSliceArrayOffset <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<3663> but was:<0>
   > 	at __randomizedtesting.SeedInfo.seed([42EED4DE0EE5FB95:573929D675033D8B]:0)
   > 	at org.elasticsearch.common.bytes.AbstractBytesReferenceTestCase.testSliceArrayOffset(AbstractBytesReferenceTestCase.java:442)
   > 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dakrone** [comment]
There is also a reproducible failure in `PagedBytesReferenceTests.testSliceArrayOffset` that I believe is related to this (in the same failure on Jenkins):

```
  2> REPRODUCE WITH: gradle :core:test -Dtests.seed=42EED4DE0EE5FB95 -Dtests.class=org.elasticsearch.common.bytes.PagedBytesReferenceTests -Dtests.method="testSliceArrayOffset" -Dtests.es.logger.level=DEBUG -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=560m -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:-UseCompressedOops" -Dtests.locale=vi -Dtests.timezone=Asia/Pyongyang
FAILURE 0.08s | PagedBytesReferenceTests.testSliceArrayOffset <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<3663> but was:<0>
   > 	at __randomizedtesting.SeedInfo.seed([42EED4DE0EE5FB95:573929D675033D8B]:0)
   > 	at org.elasticsearch.common.bytes.AbstractBytesReferenceTestCase.testSliceArrayOffset(AbstractBytesReferenceTestCase.java:442)
   > 	at java.lang.Thread.run(Thread.java:745)
```
