### ISSUE TITLE
Kibana bug locks up Elasticsearch

### ISSUE THREAD

**Issue by LeeDr** [elastic/elasticsearch#19690]
**Elasticsearch version**: 2.3.5 RC 2 (no plugins installed)

**JVM version**: 
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b15, mixed mode)

**OS version**: Windows 10

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Reproduce this Kibana issue;   https://github.com/elastic/kibana/issues/7667
 2. Elasticsearch stops responding.  Doesn't log anything.

**Provide logs (if relevant)**:
```
D:\k4.5.4-es2.3.5\elasticsearch-2.3.5>bin\elasticsearch
[2016-07-29 11:29:54,007][INFO ][node                     ] [Miss America] version[2.3.5], pid[132156], build[90f439f/2016-07-27T10:36:52Z]
[2016-07-29 11:29:54,013][INFO ][node                     ] [Miss America] initializing ...
[2016-07-29 11:29:54,395][INFO ][plugins                  ] [Miss America] modules [reindex, lang-expression, lang-groovy], plugins [], sites []
[2016-07-29 11:29:54,415][INFO ][env                      ] [Miss America] using [1] data paths, mounts [[Data (D:)]], net usable_space [128.4gb], net total_space [270.9gb], spins? [unknown], types [NTFS]
[2016-07-29 11:29:54,423][INFO ][env                      ] [Miss America] heap size [910.5mb], compressed ordinary object pointers [true]
[2016-07-29 11:29:56,431][INFO ][node                     ] [Miss America] initialized
[2016-07-29 11:29:56,436][INFO ][node                     ] [Miss America] starting ...
[2016-07-29 11:29:56,680][INFO ][transport                ] [Miss America] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}, {[::1]:9300}
[2016-07-29 11:29:56,693][INFO ][discovery                ] [Miss America] elasticsearch/ZelqYwXZQjSIeCRBUldM4Q
[2016-07-29 11:30:00,727][INFO ][cluster.service          ] [Miss America] new_master {Miss America}{ZelqYwXZQjSIeCRBUldM4Q}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2016-07-29 11:30:00,871][INFO ][gateway                  ] [Miss America] recovered [5] indices into cluster_state
[2016-07-29 11:30:00,903][INFO ][http                     ] [Miss America] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {[::1]:9200}
[2016-07-29 11:30:00,911][INFO ][node                     ] [Miss America] started
[2016-07-29 11:30:01,501][INFO ][cluster.routing.allocation] [Miss America] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[logstash-2016.07.29][0]] ...]).
[2016-07-29 11:31:20,760][INFO ][monitor.jvm              ] [Miss America] [gc][old][77][6] duration [5.2s], collections [1]/[5.2s], total [5.2s]/[9.9s], memory [615.5mb]->[691.4mb]/[910.5mb], all_pools {[young] [2.1mb]->[8.5mb]/[114mb]}{[survivor] [0b]->[0b]/[113.5mb]}{[old] [613.3mb]->[682.8mb]/[683mb]}
[2016-07-29 11:31:27,599][INFO ][monitor.jvm              ] [Miss America] [gc][old][78][7] duration [6.8s], collections [1]/[6.8s], total [6.8s]/[16.7s], memory [691.4mb]->[736.5mb]/[910.5mb], all_pools {[young] [8.5mb]->[81.5mb]/[114mb]}{[survivor] [0b]->[0b]/[113.5mb]}{[old] [682.8mb]->[655mb]/[683mb]}
[2016-07-29 11:31:35,870][INFO ][monitor.jvm              ] [Miss America] [gc][old][79][8] duration [8.2s], collections [1]/[8.2s], total [8.2s]/[24.9s], memory [736.5mb]->[758.2mb]/[910.5mb], all_pools {[young] [81.5mb]->[103.2mb]/[114mb]}{[survivor] [0b]->[0b]/[113.5mb]}{[old] [655mb]->[655mb]/[683mb]}
[2016-07-29 11:31:46,741][INFO ][monitor.jvm              ] [Miss America] [gc][old][80][10] duration [10.8s], collections [2]/[10.8s], total [10.8s]/[35.8s], memory [758.2mb]->[767.2mb]/[910.5mb], all_pools {[young] [103.2mb]->[112.1mb]/[114mb]}{[survivor] [0b]->[0b]/[113.5mb]}{[old] [655mb]->[655mb]/[683mb]}
```

```
[11:30:01.586] [info][status][plugin:elasticsearch] Status changed from red to green - Kibana index ready
[11:31:18.583] [error][status][plugin:elasticsearch] Status changed from green to red - Request Timeout after 3000ms
[11:31:27.609] [info][status][plugin:elasticsearch] Status changed from red to green - Kibana index ready
[11:31:33.120] [error][status][plugin:elasticsearch] Status changed from green to red - Request Timeout after 3000ms
[11:31:46.744] [info][status][plugin:elasticsearch] Status changed from red to green - Kibana index ready
[11:32:16.755] [error][status][plugin:elasticsearch] Status changed from green to red - Request Timeout after 30000ms
[11:32:22.259] [error][status][plugin:elasticsearch] Status changed from red to red - Request Timeout after 3000ms
[11:37:06.457] [error][elasticsearch] Request error, retrying -- connect ECONNREFUSED 127.0.0.1:9200
[11:37:07.593] [warning][elasticsearch] Unable to revive connection: http://localhost:9200/
[11:37:07.596] [warning][elasticsearch] No living connections
[11:37:07.601] [error][status][plugin:elasticsearch] Status changed from red to red - Unable to connect to Elasticsearch at http://localhost:9200.
[11:37:11.291] [warning][elasticsearch] Unable to revive connection: http://localhost:9200/
[11:37:11.293] [warning][elasticsearch] No living connections
[11:37:14.972] [warning][elasticsearch] Unable to revive connection: http://localhost:9200/
[11:37:14.976] [warning][elasticsearch] No living connections
[11:37:18.573] [warning][elasticsearch] Unable to revive connection: http://localhost:9200/
[11:37:18.576] [warning][elasticsearch] No living connections
```

**Comment by LeeDr** [comment]
It's an out of memory issue;

```
[2016-07-29 11:49:30,030][INFO ][cluster.routing.allocation] [Sauron] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[logstash-2016.07.29][0]] ...]).
java.lang.OutOfMemoryError: GC overhead limit exceeded
Dumping heap to java_pid136212.hprof ...
Heap dump file created [1202950405 bytes in 9.270 secs]
[2016-07-29 11:51:45,979][DEBUG][action.admin.indices.stats] [Sauron] failed to execute [indices:monitor/stats] on node [aVa1p_8zSCKK3gbdJEOrJw]
RemoteTransportException[[Sauron][127.0.0.1:9300][indices:monitor/stats[n]]]; nested: OutOfMemoryError[GC overhead limit exceeded];
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.elasticsearch.action.support.ChildTaskRequest.createTask(ChildTaskRequest.java:72)
        at org.elasticsearch.action.support.ChildTaskRequest.createTask(ChildTaskRequest.java:68)
        at org.elasticsearch.tasks.TaskManager.register(TaskManager.java:67)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2016-07-29 11:51:45,979][DEBUG][action.search            ] [Sauron] [logstash-2016.07.29][0]: Failed to execute [org.elasticsearch.action.search.SearchRequest@4d631ce9] while moving to second phase
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalHistogram$Factory.createBucket(InternalHistogram.java:261)
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalHistogram.addEmptyBuckets(InternalHistogram.java:437)
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalHistogram.doReduce(InternalHistogram.java:466)
        at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:153)
        at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:170)
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalHistogram$Bucket.reduce(InternalHistogram.java:146)
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalHistogram.reduceBuckets(InternalHistogram.java:363)
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalHistogram.doReduce(InternalHistogram.java:462)
        at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:153)
        at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:170)
        at org.elasticsearch.search.controller.SearchPhaseController.merge(SearchPhaseController.java:411)
        at org.elasticsearch.action.search.SearchCountAsyncAction.moveToSecondPhase(SearchCountAsyncAction.java:59)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.innerMoveToSecondPhase(AbstractSearchAsyncAction.java:374)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:171)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onResponse(AbstractSearchAsyncAction.java:147)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onResponse(AbstractSearchAsyncAction.java:144)
        at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:41)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:819)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:803)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:793)
        at org.elasticsearch.transport.DelegatingTransportChannel.sendResponse(DelegatingTransportChannel.java:58)
        at org.elasticsearch.transport.RequestHandlerRegistry$TransportChannelWrapper.sendResponse(RequestHandlerRegistry.java:134)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:369)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2016-07-29 11:51:53,332][INFO ][node                     ] [Sauron] stopping ...
[2016-07-29 11:51:53,399][INFO ][node                     ] [Sauron] stopped
[2016-07-29 11:51:53,402][INFO ][node                     ] [Sauron] closing ...
[2016-07-29 11:51:53,431][INFO ][node                     ] [Sauron] closed
```

**Comment by jasontedor** [comment]
In #18419 we added GC overhead logging and in #19272 we changed Elasticsearch so that it will immediately die on OOM instead of being an undead zombie.

**Comment by polyfractal** [comment]
@jasontedor aren't you supposed to be on vacation?  Get out of here :P

It ended up being an issue with too many buckets.  A large (but sparse) range which was blowing out the heap due to 2.x's default `min_doc_count: 0`.  The chart in question which was causing the issue was originally built on 1.x where `min_doc_count: 1` so it masked the issue.

**Comment by bleskes** [comment]
Is it interesting to see if the new 5.0 circuit break will prevent this?
