### ISSUE TITLE
ES 2.3.4 not starting with tribe configured

### ISSUE THREAD

**Issue by ogardatadude** [elastic/elasticsearch#19728]
**Elasticsearch version**: 2.3.4

**JVM version**: 1.8.101 

**OS version**: Centos 7

**Description of the problem including expected versus actual behavior**:
- ES not starting with tribe configuration, errors with what appears to be a shield license error (see   \  
    below)
- Without tribe configuration it starts and stays running

- Shield plugin is installed
- License is installed
- Shield works without tribe config verified with curl https requests

**Steps to reproduce**:
 1. enable tribe config in elasticsearch.yml
tribe:
  abc:
     cluster.name: abc-cluster
     discovery.zen.ping.unicast.hosts:
      - 10.10.10.10:9300
     discovery.zen.ping.multicast.enabled: false
     shield.ssl.keystore.path: "/etc/elasticsearch/elktribe.jks"
     shield.ssl.keystore.password: "redacted"
     shield.ssl.keystore.key_password: "redacted"
     shield.transport.ssl: true
     shield.http.ssl: true
     shield.ssl.ciphers: TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA
     shield.ssl.hostname_verification.resolve_name: false
  kibana:
     cluster.name: kibana
     discovery.zen.ping.unicast.hosts:
      - 127.0.0.1:9302
     discovery.zen.ping.multicast.enabled: false
     shield.ssl.keystore.path: "/etc/elasticsearch/elktribe.jks"
     shield.ssl.keystore.password: "redacted"
     shield.ssl.keystore.key_password: "redacted"
     shield.transport.ssl: true
     shield.http.ssl: true
     shield.ssl.ciphers: TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA
     shield.ssl.hostname_verification.resolve_name: false
  on_conflict: prefer_kibana

 2. restart es
 3.

**Provide logs (if relevant)**:
[2016-08-01 11:15:02,508][INFO ][node                     ] [tribe1] version[2.3.4], pid[10330], build[e455fd0/2016-06-30T11:24:31Z]
[2016-08-01 11:15:02,509][INFO ][node                     ] [tribe1] initializing ...
[2016-08-01 11:15:03,238][INFO ][plugins                  ] [tribe1] modules [reindex, lang-expression, lang-groovy], plugins [license, shield], sites []
[2016-08-01 11:15:03,776][INFO ][http                     ] [tribe1] Using [org.elasticsearch.http.netty.NettyHttpServerTransport] as http transport, overridden by [shield]
[2016-08-01 11:15:03,945][INFO ][transport                ] [tribe1] Using [org.elasticsearch.shield.transport.ShieldServerTransportService] as transport service, overridden by [shield]
[2016-08-01 11:15:03,945][INFO ][transport                ] [tribe1] Using [org.elasticsearch.shield.transport.netty.ShieldNettyTransport] as transport, overridden by [shield]
[2016-08-01 11:15:05,020][ERROR][bootstrap                ] Guice Exception: org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) No implementation for org.elasticsearch.license.plugin.core.LicenseeRegistry was bound.
  while locating org.elasticsearch.license.plugin.core.LicenseeRegistry
    for parameter 1 at org.elasticsearch.shield.license.ShieldLicensee.<init>(Unknown Source)
  at _unknown_

1 error
        at <<<guice>>>
        at org.elasticsearch.node.Node.<init>(Node.java:213)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

**Comment by clintongormley** [comment]
Please could you try 2.3.5 - this should be fixed there

**Comment by ogardatadude** [comment]
I have and it seems to be, now running info other issues

**Comment by clintongormley** [comment]
Related issues?  If so, could you provide the details, otherwise I think this ticket can be closed

**Comment by ogardatadude** [comment]
No I don't think it is related.

**Comment by clintongormley** [comment]
thanks for letting us know
