### ISSUE TITLE
Add support of multi_value_mode for GeoPoint fields 

### ISSUE THREAD

**Issue by imalygin** [elastic/elasticsearch#19763]
**Elasticsearch version**: 2.3.4

**Description of the problem including expected versus actual behavior**:

_multi_value_mode_ parameter is not supported for GeoPoint fields. 

The example query is:

```
{ "query" : {
  "function_score":{    
    "functions":[{
      "gauss":{
        "triangulation":{
          "origin":[-122.060373,37.39553],
          "offset":"5mi",
          "scale":"5mi", 
           "multi_value_mode":"max"
        }
      }
    }]
  }
} }

```

where _triangulation_ is a field with multiple GeoPoint-s. I assume that now for multiple points it sums scores for all points, but in my case it'd be better to use "max" mode. 

Currently it throws following exception:

```
org.elasticsearch.ElasticsearchParseException: parameter [multi_value_mode] not supported!
    at org.elasticsearch.index.query.functionscore.DecayFunctionParser.parseGeoVariable(DecayFunctionParser.java:227) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.index.query.functionscore.DecayFunctionParser.parseVariable(DecayFunctionParser.java:165) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.index.query.functionscore.DecayFunctionParser.parse(DecayFunctionParser.java:146) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.index.query.functionscore.FunctionScoreQueryParser.parseFiltersAndFunctions(FunctionScoreQueryParser.java:225) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.index.query.functionscore.FunctionScoreQueryParser.parse(FunctionScoreQueryParser.java:129) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:250) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:320) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:223) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:218) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.search.query.QueryBinaryParseElement.parse(QueryBinaryParseElement.java:36) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.search.SearchService.parseSource(SearchService.java:838) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.search.SearchService.createContext(SearchService.java:654) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:620) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:371) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376) ~[elasticsearch-2.3.0.jar:2.3.0]
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-2.3.0.jar:2.3.0]
```

**Comment by rhbecker** [comment]
Looks like you have a syntax error, based on the [example provided in the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#_multi_values_fields) - `multi_value_mode` should be a property of `gauss`, rather than `triangulation`.

```
{
      "gauss":{
        "triangulation":{
          "origin":[-122.060373,37.39553],
          "offset":"5mi",
          "scale":"5mi"
        },
        "multi_value_mode":"max"
      }
    }
```

**Comment by clintongormley** [comment]
thanks @rhbecker
