### ISSUE TITLE
Template is not validated on store

### ISSUE THREAD

**Issue by bobrik** [elastic/elasticsearch#19823]
**Elasticsearch version**:

```
# elasticsearch --version
Version: 2.3.4, Build: e455fd0/2016-06-30T11:24:31Z, JVM: 1.8.0_91
```

**JVM version**:

```
# java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-1~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**OS version**: Debian Jessie, elasticsearch is running in the container from the official docker image.

**Description of the problem including expected versus actual behavior**:

I manually changed field mapping for existing index to enable eager global ordinals for a few fields. It seemed to improve my experience, so I decided to put new mappings into the index template. Unfortunately, I messed up with copy-pasting json from another file and template became invalid. Problem is: Elasticsearch happily saved it and and people got paged in at midnight UTC when index failed to roll.

My incorrect template:

```json
{
  "template": "raytracer-*",
  "settings": {
    "number_of_shards": 50,
    "number_of_replicas": 1,
    "index.refresh_interval": "30s",
    "index.query.default_field": "id",
    "index.search.slowlog.threshold.fetch.warn": "5s",
    "index.search.slowlog.threshold.query.warn": "5s"
  },
  "mappings": {
    "_default_": {
      "_all": {
        "enabled": false
      },
      "dynamic_templates": [
        {
          "string_fields": {
            "match": "*",
            "match_mapping_type": "string",
            "mapping": {
              "type": "string",
              "index": "not_analyzed",
              "ignore_above": 256,
              "doc_values": true
            }
          }
        },
        {
          "long_fields": {
            "match": "*",
            "match_mapping_type": "long",
            "mapping": {
              "type": "long",
              "doc_values": true
            }
          }
        },
        {
          "double_fields": {
            "match": "*",
            "match_mapping_type": "double",
            "mapping": {
              "type": "double",
              "doc_values": true
            }
          }
        },
        {
          "date_fields": {
            "match": "*",
            "match_mapping_type": "date",
            "mapping": {
              "type": "date",
              "doc_values": true
            }
          }
        }
      ],
      "properties": {
        "properties": {
          "request": {
            "type": "string",
            "index": "not_analyzed",
            "doc_values": true,
            "ignore_above": 256,
            "fielddata": {
              "loading": "eager_global_ordinals"
            }
          },
          "client": {
            "type": "string",
            "index": "not_analyzed",
            "doc_values": true,
            "ignore_above": 256,
            "fielddata": {
              "loading": "eager_global_ordinals"
            }
          },
          "host": {
            "type": "string",
            "index": "not_analyzed",
            "doc_values": true,
            "ignore_above": 256,
            "fielddata": {
              "loading": "eager_global_ordinals"
            }
          }
        }
      }
    }
  }
}
```

Error message when you try to create an index from this template:

```
2016-08-05T12:09:51.742 myhost [2016-08-05 12:09:51,741][DEBUG][action.admin.indices.create] [myhost] [raytracer-test] failed to create
2016-08-05T12:09:51.742 myhost MapperParsingException[Failed to parse mapping [_default_]: No type specified for field [properties]]; nested: MapperParsingException[No type specified for field [properties]];
2016-08-05T12:09:51.742 myhost 	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1.execute(MetaDataCreateIndexService.java:320)
2016-08-05T12:09:51.742 myhost 	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
2016-08-05T12:09:51.743 myhost 	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
2016-08-05T12:09:51.743 myhost 	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
2016-08-05T12:09:51.743 myhost 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
2016-08-05T12:09:51.743 myhost 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
2016-08-05T12:09:51.743 myhost 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2016-08-05T12:09:51.743 myhost 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2016-08-05T12:09:51.743 myhost 	at java.lang.Thread.run(Thread.java:745)
2016-08-05T12:09:51.744 myhost Caused by: MapperParsingException[No type specified for field [properties]]
2016-08-05T12:09:51.744 myhost 	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:297)
2016-08-05T12:09:51.744 myhost 	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:218)
2016-08-05T12:09:51.744 myhost 	at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:139)
2016-08-05T12:09:51.744 myhost 	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:118)
2016-08-05T12:09:51.744 myhost 	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:99)
2016-08-05T12:09:51.745 myhost 	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:85)
2016-08-05T12:09:51.745 myhost 	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:269)
2016-08-05T12:09:51.745 myhost 	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1.execute(MetaDataCreateIndexService.java:317)
2016-08-05T12:09:51.745 myhost 	... 8 more
```

It'd be great if elasticsearch could reject templates that can never be instantiated into valid indices. I can't think of a reason why this may be undesirable, but this can be hidden by a query string flag that is enabled by default.

**Comment by clintongormley** [comment]
If you try to create this template in 5.0, you'll get:

    {
      "error": {
        "root_cause": [
          {
            "type": "mapper_parsing_exception",
            "reason": "No type specified for field [properties]"
          }
        ],
        "type": "mapper_parsing_exception",
        "reason": "Failed to parse mapping [_default_]: No type specified for field [properties]",
        "caused_by": {
          "type": "mapper_parsing_exception",
          "reason": "No type specified for field [properties]"
        }
      },
      "status": 400
    }

Closed by https://github.com/elastic/elasticsearch/pull/8802

**Comment by jasontedor** [comment]
In addition to this already being closed, I have two comments:

> elasticsearch is running in the container from the official docker image

At this time, there is no official Docker image prepared by Elastic. There are images that claim to be "official" but they are not vetted by Elastic and we do not support them. Whether or not you already know this. I say it because there is a lot of confusion on this issue.

> Problem is: Elasticsearch happily saved it and and people got paged in at midnight UTC when index failed to roll.

Also, regarding getting paged at midnight: I feel your pain, I've experienced these issues too. But maybe do not deploy straight to production?
