### ISSUE TITLE
Add warning to pattern tokenizer documentation

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#19901]
**Elasticsearch version**: 2.3.x

We have encountered a scenario where a bad document is passed to the pattern tokenizer with a regex that ended up causing recursion or endless backtracking so that it ran out of stack space.

```
java.lang.StackOverflowError
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4785)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568)
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3777)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4785)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568)
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3777)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4785)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568)
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3777)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4785)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568)
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3777)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4785)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568)
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3777)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4785)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568)
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3777)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4785)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568)
	at java.util.regex.Pattern$CharProperty.match(Pattern.java:3777)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Loop.match(Pattern.java:4785)
```

There are a few caveats when using the pattern tokenizer that will be helpful to [document](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-pattern-tokenizer.html) in the product.

* The pattern tokenizer uses the  JDK implementation (java.util.regex) which can easily do very trappy things (e.g. run in exponential time).  Various issues have been reported in the field by users of Java (http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6337993) as well as Lucene (https://issues.apache.org/jira/browse/LUCENE-7256).  These are JDK issues so not something Lucene can address.

* Unlike other Lucene analysis chains, it currently reads the entire doc [into RAM](https://github.com/apache/lucene-solr/blob/master/lucene/analysis/common/src/java/org/apache/lucene/analysis/pattern/PatternTokenizer.java#L156-L157).

* In general, it is less performant than other options.  For example, one alternate (more efficient) method is to avoid using regex entirely by using the [mapping char filter](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/analysis-mapping-charfilter.html) to map the different characters in the pattern tokenizer to a space so that the standard tokenizer will just split on them (since it sees it as a space). 

* Best to note in the documentation that the pattern tokenizer is considered an expert/advanced feature given the implications of using java.util.regex.

**Comment by clintongormley** [comment]
Done, eg see https://www.elastic.co/guide/en/elasticsearch/reference/2.4/analysis-pattern-tokenizer.html#analysis-pattern-tokenizer
