### ISSUE TITLE
Embedded elasticsearch failure with finding the build shortHash.

### ISSUE THREAD

**Issue by ruckc** [elastic/elasticsearch#19930]
**Elasticsearch version**: 5.0.0-alpha5

**Plugins installed**: [netty4-client]

**JVM version**: Oracle Java 1.8.0-102

**OS version**: Windows 10

**Description of the problem including expected versus actual behavior**:

When trying to start an shaded and embedded elasticsearch Node, it hard fails due to #14754.  

**Steps to reproduce**:
 1. use maven-shade-plugin to make a uber jar including elasticsearch
 2. try to start a `new Node()` inside the uber jar
 3. failure occurs because it can't find the build shortHash.

**Provide logs (if relevant)**:

```
2016-08-10 15:23:43,981 INFO [main] org.elasticsearch.node - [] initializing ...
2016-08-10 15:23:44,090 INFO [main] org.elasticsearch.env - [rH3sERa] using [1] data paths, mounts [[/var/lib/elasticsearch (/dev/sdc)]], net usable_space [93.2gb], net total_space [98.3gb], spins? [possibly], types [ext4]
2016-08-10 15:23:44,093 INFO [main] org.elasticsearch.env - [rH3sERa] heap size [3.3gb], compressed ordinary object pointers [true]
2016-08-10 15:23:44,094 INFO [main] org.elasticsearch.node - [rH3sERa] node name [rH3sERa] derived from node ID; set [node.name] to override
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.elasticsearch.node.Node.<init>(Node.java:240)
...
Caused by: java.lang.IllegalStateException: Error finding the build shortHash. Stopping Elasticsearch now so it doesn't run in subtly broken ways. This is likely a build bug.
        at org.elasticsearch.Build.<clinit>(Build.java:62)
        ... 7 more
```

**Describe the feature**:

Please document this in breaking changes with a workaround (i.e. injecting our own shortHash/build date) or allow us to start a node without these Jar manifest entries.

**Comment by jasontedor** [comment]
We [do not support](https://www.elastic.co/blog/elasticsearch-the-server) embedding Elasticsearch nodes.

**Comment by ruckc** [comment]
@jasontedor since when?  I've been embedding elasticsearch for four years now.  Looking at elasticsearch's history ["site:elastic.co embedded"](https://www.google.com/search?q=site%3Aelastic.co%20embedded) there is a significant amount of information floating about how to do it for previous versions, and existing external open source products doing it.  When was embedding deprecated?

**Comment by rjernst** [comment]
@ruckc In the blog post @jasontedor linked to: https://www.elastic.co/blog/elasticsearch-the-server

**Comment by ruckc** [comment]
@rjernst Thanks. I love how that was written today.  Didn't see the original link due to color/contrast issues.
