### ISSUE TITLE
[exception report]IndexShardRecoveryException[failed recovery]

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#19938]
**Elasticsearch version**:
2.1.2
**Plugins installed**: []
elasticsearch-analysis-ik
delete-by-query
repository-hdfs
**JVM version**:
1.8.60
**OS version**:
CentOS release 6.6 (Final)
**Description of the problem including expected versus actual behavior**:
log file of one data node shows a lot of GC info and cluster response request very slow or hardly any response. 
then I try to kill -3 that data node but fails. 
then I kill -9 that data node and restart it.
when this data node start to recovery data, it keeping throw below exceptions:
[XXXXXXX][WARN ][indices.cluster          ] [name] [[indexname][3]] marking and sending shard failed due to [failed recovery]
[indexname][[typename][3]] IndexShardRecoveryException[failed recovery]; nested: IllegalStateException[Checkpoint file translog-3759.ckp already exists but has corrupted content expected: Checkpoint{offset=31629737, numOps=42592, translogFileGeneration= 3759} but got: Checkpoint{offset=31628968, numOps=42591, translogFileGeneration= 3759}];
        at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:179)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Checkpoint file translog-3759.ckp already exists but has corrupted content expected: Checkpoint{offset=31629737, numOps=42592, translogFileGeneration= 3759} but got: Checkpoint{offset=31628968, numOps=42591, translogFileGeneration= 3759}
        at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:339)
        at org.elasticsearch.index.translog.Translog.<init>(Translog.java:179)
        at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:209)
        at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:152)
        at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
        at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1437)
        at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1421)
        at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:920)
        at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:892)
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:245)
        at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
        at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
**Steps to reproduce**:
 1.
 2.
 3.

**Comment by clintongormley** [comment]
You need to upgrade. A number of translog issues have been fixed since 2.1.2

In 5.0 we have a tool which can be used to truncate corrupt translog files.  This doesn't exist in 2.x but there is a workaround:

    POST my_index/_close

    PUT my_index/_settings
    { "index.engine.force_new_translog": true }

    POST my_index/_open

    PUT my_index/_settings
    { "index.engine.force_new_translog": false }

**NOTE:**  Any data in the corrupted translog will be lost.

**Comment by clintongormley** [comment]
@makeyang the advice i've given in the previous message won't work properly.  See https://github.com/elastic/elasticsearch/issues/18972#issuecomment-241156032

Instead, as soon as you can access the index (using the `force_new_translog` setting), you should reindex the data to a new index and delete the old one.

**Comment by makeyang** [comment]
@clintongormley 
thanks, I have read #18972 and got your suggestions.
