### ISSUE TITLE
Restoring a snapshot on fresh cluster is not happenning

### ISSUE THREAD

**Issue by chaitu0292** [elastic/elasticsearch#19954]
[2016-08-11 20:39:48,026][WARN ][cluster.action.shard     ] [masternode] [31_gu_34_s_56_1.365_1][1] received shard failed for target shard [[31_gu_34_s_56_1.365_1][1], node[m3-G4NhDTHm88M1iuGeO0Q], [P], v[59], restoring[Reponame:31_gu_34_s_56_1.365_1_2016-08-11_18_32_14], s[INITIALIZING], a[id=y3umCQy1S92Dl66U-IcWog], unassigned_info[[reason=ALLOCATION_FAILED], at[2016-08-11T15:09:47.994Z], details[failed recovery, failure IndexShardRecoveryException[failed recovery]; nested: IndexShardRestoreFailedException[restore failed]; nested: IndexShardRestoreFailedException[failed to restore snapshot [31_gu_34_s_56_1.365_1_2016-08-11_18_32_14]]; nested: IndexShardRestoreFailedException[failed to read shard snapshot file]; nested: NoSuchFileException[/root/backup/indices/31_gu_34_s_56_1.365_1/1/snap-31_gu_34_s_56_1.365_1_2016-08-11_18_32_14.dat]; ]]], indexUUID [qNnZsg2HTpGE8sowJoNn3A], message [master {masternode}{2YhQdezHRd28ZeI5cmp8Fg}{10.131.75.124}{10.131.75.124:9300}{master=true} marked shard as initializing, but shard is marked as failed, resend shard failure]
[2016-08-11 20:39:48,036][WARN ][cluster.action.shard     ] [masternode] [31_gu_34_s_56_1.365_1][1] received shard failed for target shard [[31_gu_34_s_56_1.365_1][1], node[m3-G4NhDTHm88M1iuGeO0Q], [P], v[59], restoring[Reponame:31_gu_34_s_56_1.365_1_2016-08-11_18_32_14], s[INITIALIZING], a[id=y3umCQy1S92Dl66U-IcWog], unassigned_info[[reason=ALLOCATION_FAILED], at[2016-08-11T15:09:47.994Z], details[failed recovery, failure IndexShardRecoveryException[failed recovery]; nested: IndexShardRestoreFailedException[restore failed]; nested: IndexShardRestoreFailedException[failed to restore snapshot [31_gu_34_s_56_1.365_1_2016-08-11_18_32_14]]; nested: IndexShardRestoreFailedException[failed to read shard snapshot file]; nested: NoSuchFileException[/root/backup/indices/31_gu_34_s_56_1.365_1/1/snap-31_gu_34_s_56_1.365_1_2016-08-11_18_32_14.dat]; ]]], indexUUID [qNnZsg2HTpGE8sowJoNn3A], message [master {masternode}{2YhQdezHRd28ZeI5cmp8Fg}{10.131.75.124}{10.131.75.124:9300}{master=true} marked shard as initializing, but shard is marked as failed, resend shard failure]
[2016-08-11 20:39:48,042][WARN ][cluster.action.shard     ] [masternode] [31_gu_34_s_56_1.365_1][0] received shard failed for target shard [[31_gu_34_s_56_1.365_1][0], node[pD9veWpsQdSbjnYg7AuA7w], [P], v[67], restoring[Reponame:31_gu_34_s_56_1.365_1_2016-08-11_18_32_14], s[INITIALIZING], a[id=FXaIPEL3TYmeJ5D9s495tg], unassigned_info[[reason=ALLOCATION_FAILED], at[2016-08-11T15:09:48.021Z], details[failed recovery, failure IndexShardRecoveryException[failed recovery]; nested: IndexShardRestoreFailedException[restore failed]; nested: IndexShardRestoreFailedException[failed to restore snapshot [31_gu_34_s_56_1.365_1_2016-08-11_18_32_14]]; nested: IndexShardRestoreFailedException[failed to read shard snapshot file]; nested: NoSuchFileException[/root/backup/indices/31_gu_34_s_56_1.365_1/0/snap-31_gu_34_s_56_1.365_1_2016-08-11_18_32_14.dat]; ]]], indexUUID [qNnZsg2HTpGE8sowJoNn3A], message [failed recovery], failure [IndexShardRecoveryException[failed recovery]; nested: IndexShardRestoreFailedException[restore failed]; nested: IndexShardRestoreFailedException[failed to restore snapshot [31_gu_34_s_56_1.365_1_2016-08-11_18_32_14]]; nested: IndexShardRestoreFailedException[failed to read shard snapshot file]; nested: NoSuchFileException[/root/backup/indices/31_gu_34_s_56_1.365_1/0/snap-31_gu_34_s_56_1.365_1_2016-08-11_18_32_14.dat]; ]
[31_gu_34_s_56_1.365_1][[31_gu_34_s_56_1.365_1][0]] IndexShardRecoveryException[failed recovery]; nested: IndexShardRestoreFailedException[restore failed]; nested: IndexShardRestoreFailedException[failed to restore snapshot [31_gu_34_s_56_1.365_1_2016-08-11_18_32_14]]; nested: IndexShardRestoreFailedException[failed to read shard snapshot file]; nested: NoSuchFileException[/root/backup/indices/31_gu_34_s_56_1.365_1/0/snap-31_gu_34_s_56_1.365_1_2016-08-11_18_32_14.dat];
        at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:179)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: [31_gu_34_s_56_1.365_1][[31_gu_34_s_56_1.365_1][0]] IndexShardRestoreFailedException[restore failed]; nested: IndexShardRestoreFailedException[failed to restore snapshot [31_gu_34_s_56_1.365_1_2016-08-11_18_32_14]]; nested: IndexShardRestoreFailedException[failed to read shard snapshot file]; nested: NoSuchFileException[/root/backup/indices/31_gu_34_s_56_1.365_1/0/snap-31_gu_34_s_56_1.365_1_2016-08-11_18_32_14.dat];
        at org.elasticsearch.index.shard.StoreRecoveryService.restore(StoreRecoveryService.java:321)
        at org.elasticsearch.index.shard.StoreRecoveryService.access$000(StoreRecoveryService.java:56)
        at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:126)
        ... 3 more
Caused by: [31_gu_34_s_56_1.365_1][[31_gu_34_s_56_1.365_1][0]] IndexShardRestoreFailedException[failed to restore snapshot [31_gu_34_s_56_1.365_1_2016-08-11_18_32_14]]; nested: IndexShardRestoreFailedException[failed to read shard snapshot file]; nested: NoSuchFileException[/root/backup/indices/31_gu_34_s_56_1.365_1/0/snap-31_gu_34_s_56_1.365_1_2016-08-11_18_32_14.dat];
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository.restore(BlobStoreIndexShardRepository.java:215)
        at org.elasticsearch.index.shard.StoreRecoveryService.restore(StoreRecoveryService.java:312)
        ... 5 more
Caused by: [31_gu_34_s_56_1.365_1][[31_gu_34_s_56_1.365_1][0]] IndexShardRestoreFailedException[failed to read shard snapshot file]; nested: NoSuchFileException[/root/backup/indices/31_gu_34_s_56_1.365_1/0/snap-31_gu_34_s_56_1.365_1_2016-08-11_18_32_14.dat];
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$Context.loadSnapshot(BlobStoreIndexShardRepository.java:352)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$RestoreContext.restore(BlobStoreIndexShardRepository.java:808)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository.restore(BlobStoreIndexShardRepository.java:213)
        ... 6 more
Caused by: java.nio.file.NoSuchFileException: /root/backup/indices/31_gu_34_s_56_1.365_1/0/snap-31_gu_34_s_56_1.365_1_2016-08-11_18_32_14.dat
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.common.blobstore.fs.FsBlobContainer.readBlob(FsBlobContainer.java:89)
        at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.readBlob(ChecksumBlobStoreFormat.java:93)
        at org.elasticsearch.repositories.blobstore.BlobStoreFormat.read(BlobStoreFormat.java:83)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$Context.loadSnapshot(BlobStoreIndexShardRepository.java:350)
        ... 8 more

**Comment by imotov** [comment]
@chaitu0292 which version of elasticsearch is it? How many nodes do you have in this cluster?

**Comment by chaitu0292** [comment]
version 2.3.3 and 3 nodes

**Comment by imotov** [comment]
How did you setup the repository? Is `/root/backup/` a shared directory that is accessible on all nodes?

**Comment by chaitu0292** [comment]
path.repo: ["/root/backup"] in yml

for creating repository
PUT _snapshot/Reponame 
{
    "type": "fs", 
    "settings": {
        "location": "/root/backup" 
    }
}

for restore
POST /_snapshot/Reponame/indexname/_restore?wait_for_completion=true

copied contents of backup folder from my old cluster setup to new cluster backup folder created by elasticserach

**Comment by chaitu0292** [comment]
is /root/backup is directory on master node itself. we are storing the snapshot on same node. And it worked fine when we tried to restore the snapshot in our old cluster setup.

**Comment by imotov** [comment]
It worked accidentally, because you either had a single node cluster or because all your primary shards happened to be on the current mater node, or you tried restoring in exactly the same cluster you made the snapshot. You shouldn't have been able to even register such repository unless you suppressed repository verification. It is necessary to mount the same shared filesystem to the same location on all master and data nodes for the snapshot to work as described in [shared file system repo docs](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/modules-snapshots.html#_shared_file_system_repository).

**Comment by chaitu0292** [comment]
in my elasticsearch.yml of all the nodes path.repo is given as path.repo: ["\root\backup"].
so i have backup folder on all the nodes. And yes there is repository verification exception and i supressed it. So in my case what should i do for my use case to work.

**Comment by imotov** [comment]
As it is described in the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/modules-snapshots.html#_shared_file_system_repository), the repository directory (in your case`\root\backup`) should be shared across all master and data nodes. We check that everything is setup correctly during the verification process which you disabled. So, you need to mount the same directory on all machines and re-register repository without disabling verification and make sure that verification passes. Since, it doesn't seem to be a bug report, I am going to close this issue. If you have any other questions, please don't hesitate to ask them on our support forum https://discuss.elastic.co/

**Comment by chaitu0292** [comment]
In my elasticsearch.yml of all the nodes path.repo is given as path.repo: ["\root\backup"].
so I have backup folder on all the nodes. And yes there is repository verification exception and I suppressed it. So what should I do for my use case to work. I performed restore activities on my old cluster setup for more than 50 times. And I also can see shards of my indices on my other nodes inside backup folder.

**Comment by imotov** [comment]
Sorry, your use case is not supported until #6638 is implemented.  The verification process has to pass otherwise there are no guarantee it would work. Having this folder on all machines is not enough, it has to be the same network share. For restore to work, all these individual files currently scattered across different nodes have to be in the same directory accessible on all nodes where restore will happen.

**Comment by chaitu0292** [comment]
It worked after making a shared fs thank you
