### ISSUE TITLE
5.0.0-alpha5 Java API can't connect to ES node

### ISSUE THREAD

**Issue by mrvincenzo** [elastic/elasticsearch#19952]
5.0.0-alpha5 Java API can't connect to ES node. Same setup **works** with **alpha4** Java API. Getting the following exception "**None of the configured nodes are available**"

```
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{3CJj2k77QF20-9Qw-PZlzA}{10.114.20.230}{10.114.20.230:9300}, {#transport#-2}{1hVLh7CIQY2DkEL_YcUnHA}{10.114.20.230}{10.114.20.230:9300}]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:314) ~[elasticsearch-5.0.0-alpha5.jar:5.0.0-alpha5]
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:228) ~[elasticsearch-5.0.0-alpha5.jar:5.0.0-alpha5]
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:63) ~[elasticsearch-5.0.0-alpha5.jar:5.0.0-alpha5]
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:319) ~[elasticsearch-5.0.0-alpha5.jar:5.0.0-alpha5]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:403) ~[elasticsearch-5.0.0-alpha5.jar:5.0.0-alpha5]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80) ~[elasticsearch-5.0.0-alpha5.jar:5.0.0-alpha5]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54) ~[elasticsearch-5.0.0-alpha5.jar:5.0.0-alpha5]
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:62) ~[elasticsearch-5.0.0-alpha5.jar:5.0.0-alpha5]
```

Setup:
```
Settings settings = Settings.builder()
        .put("cluster.name", "clusterName")
        .put("client.transport.sniff", true)
        .build();

TransportClient client = new PreBuiltTransportClient(settings);

client.addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("10.114.20.230"), 9300));
```
p.s. the IP address is internal IP address

**Comment by colings86** [comment]
> .put("cluster.name", "clusterName")

Is your cluster name actually `"clusterName"` or did you replace it with a placeholder for the purposes for raising this issue so you didn't leak your cluster name?

**Comment by mrvincenzo** [comment]
I replaced it with the real cluster name. I guess the problem was with my elasticsearch configuration. I did another try on a different deployment environment I have with multiple nodes and it worked well. Thanks.

**Comment by Zhaokung** [comment]
hello !
I have also encountered the same problem
this is my java code:
    `
public class Estes {
public static void func() {
		try {				
			Settings settings = Settings.builder()
			        .put("cluster.name", "my-application")
			        .put("client.transport.sniff", true)
			        .build();

			TransportClient client = new PreBuiltTransportClient(settings);

			client.addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("192.168.32.124"), 9300));
		
			String json = "{" +
			
			        "\"user\":\"kimchy\"," +
			        "\"postDate\":\"2013-01-30\"," +
			        "\"message\":\"trying out Elasticsearch\"" +
			    "}";

			IndexResponse response = client.prepareIndex("twitter", "tweet")
			        .setSource(json)
			        .get();
			// Index name
			String _index = response.getIndex();
			// Type name
			String _type = response.getType();
			// Document ID (generated or not)
			String _id = response.getId();
			// Version (if it's the first time you index this document, you will get: 1)
			long _version = response.getVersion();
			// isCreated() is true if the document is a new one, false if it has been updated
			System.out.println(_index + " " + _type + " " + _id + " " + _version + " "); 	
		} catch (UnknownHostException e) {
			e.printStackTrace();
		}
	}
	public static void main(String[] args) {
		func();
	}

}`
 

and this is my maven pom.xml:
<dependencies>
		<dependency>
			<groupId>org.elasticsearch.client</groupId>
			<artifactId>transport</artifactId>
			<version>5.0.0-alpha5</version>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.7</version>
		</dependency>
about the  log4j，  if without this package will appear the error like this 

        Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Priority
	at org.elasticsearch.common.logging.ESLoggerFactory.getLogger(ESLoggerFactory.java:42)
	at org.elasticsearch.common.logging.ESLoggerFactory.getLogger(ESLoggerFactory.java:46)
	at org.elasticsearch.common.logging.Loggers.getLogger(Loggers.java:123)
	at org.elasticsearch.common.settings.Setting.<clinit>(Setting.java:110)
	at org.elasticsearch.node.Node.<clinit>(Node.java:148)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:103)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:222)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:67)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:63)
	at test.Estes.func(Estes.java:25)
	at test.Estes.main(Estes.java:58)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Priority
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 11 more

and added the log4j package the error was well,but the another error was still there .


     log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{aM8chRpoQKiO0iDS149HxQ}{192.168.32.124}{192.168.32.124:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:314)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:228)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:63)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:319)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:403)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:62)
	at test.Estes.func(Estes.java:38)
	at test.Estes.main(Estes.java:58)

ok！ so my problem just like yours    could you help me ?Tell me how you solved it.  please!

**Comment by jasontedor** [comment]
@Zhaokung Please post a topic on the [Elastic Discourse forum](https://discuss.elastic.co); this issue is closed and Elastic reserves GitHub for verified bug reports and feature requests, but provides the Discourse forum for general help.

**Comment by alkanarslan** [comment]
@Zhaokung  removed  .put("client.transport.sniff", true) or .put("client.transport.sniff", false)

**Comment by loriling** [comment]
@Zhaokung 
I just found that i have closed my ES server，it works fine after i reopen it...

**Comment by rustycore** [comment]
@alkanarslan after using ("client.transport.sniff", false) the exception still occurs
