### ISSUE TITLE
Snapshot creation successful with code 200 when file system is unmounted or not accessible

### ISSUE THREAD

**Issue by kmurthy1** [elastic/elasticsearch#19967]
When the nfs share is unmounted and then a snapshot creation is attempted, the snapshot is created successfully with "State: PARTIAL". The response code is 200 
If the same is attempted with '-d' option which is to delete the indices after snapshot, we end up with a partial snapshot and also losing original indices.

**Elasticsearch version**:  "version" : "number" : "2.2.0"

**Plugins installed**: None

**JVM version**:  
[root@localhost ~]#  java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

**OS version**: CentOS Linux release 7.2.1511 

**Description of the problem including expected versus actual behavior**:
Expected behavior: Fail the snapshot creation when the snapshot settings have "type": "fs" and the file system/share is not accessible.

**Steps to reproduce**:
1. Set the snapshot settings to type: fs and  "location": "/mount/backups/my_backup"
2. unmount the share @ /mount/backups/my_backup
3. Run a create snapshot command

**Provide logs (if relevant)**:

[2016-08-11 22:51:44,718][WARN ][snapshots                ] [es_node1] [[test-2016-08-05][4]] [my_backup:snap3] failed to create snapshot
[test-2016-08-05][[test-2016-08-05][4]] IndexShardSnapshotFailedException[Failed to snapshot]; nested: ElasticsearchException[failed to create blob container]; nested: AccessDeniedException[/mnt/backup/indices];
        at org.elasticsearch.snapshots.SnapshotShardsService.snapshot(SnapshotShardsService.java:355)
        at org.elasticsearch.snapshots.SnapshotShardsService.access$200(SnapshotShardsService.java:76)
        at org.elasticsearch.snapshots.SnapshotShardsService$1.doRun(SnapshotShardsService.java:296)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: ElasticsearchException[failed to create blob container]; nested: AccessDeniedException[/mnt/backup/indices];
        at org.elasticsearch.common.blobstore.fs.FsBlobStore.blobContainer(FsBlobStore.java:70)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$Context.<init>(BlobStoreIndexShardRepository.java:310)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$Context.<init>(BlobStoreIndexShardRepository.java:303)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.<init>(BlobStoreIndexShardRepository.java:513)
        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository.snapshot(BlobStoreIndexShardRepository.java:187)
        at org.elasticsearch.snapshots.SnapshotShardsService.snapshot(SnapshotShardsService.java:340)
        ... 6 more
Caused by: java.nio.file.AccessDeniedException: /mnt/backup/indices
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
        at java.nio.file.Files.createDirectory(Files.java:674)
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
        at java.nio.file.Files.createDirectories(Files.java:767)
        at org.elasticsearch.common.blobstore.fs.FsBlobStore.buildAndCreate(FsBlobStore.java:86)
        at org.elasticsearch.common.blobstore.fs.FsBlobStore.blobContainer(FsBlobStore.java:68)
        ... 11 more

**Comment by imotov** [comment]
Do you have multiple nodes and you unmount the share only on some of them?

**Comment by kmurthy1** [comment]
yes, I do have 3 nodes and I unmount only on the one I am executing the snapshot creation.
The same is not true for restoring a snapshot 'I suppose'. i.e even if one of the nodes has the share mounted, we can restore the snapshot on a different node where the share is unmounted.

**Comment by imotov** [comment]
> I unmount only on the one I am executing the snapshot creation

The snapshot command is always executed on the master node and data nodes that contain the primary shards for the indices that you are snapshotting. The node that you send the snapshot command to may be not involved in the snapshot operation at all if it doesn't contain any primary shards. However, it looks like in your case it contains some of the primary shards and these shards fail to snapshot. The PARTIAL status that you get back basically means that at least one shard wasn't successfully snapshotted, but the master node was able to access the repository. We [don't have](#18978) a special status code for 'PARTIAL' responses at the moment, so you need to check the snapshot status before making the decision about deleting the indices.

> If the same is attempted with '-d' option which is to delete the indices after snapshot, we end up with a partial snapshot and also losing original indices.

Could you elaborate on this? I am not sure what you mean by '-d' option.

**Comment by kmurthy1** [comment]
thanks for the clarification. And sorry about the '-d', my bad, it is something that I am using in my script. Will make necessary changes.

**Comment by imotov** [comment]
Cool. I am going to close this issue then. If you have any further questions, please don't hesitate to ask them on our discussion forum https://discuss.elastic.co/.
