### ISSUE TITLE
Query fails with "[No query registered for [filter]]" when run from Java client

### ISSUE THREAD

**Issue by sorokod** [elastic/elasticsearch#20060]
**Elasticsearch version**:2.3.4

**Plugins installed**: []

**JVM version**:1.8

**OS version**:Win 8

**Description of the problem including expected versus actual behavior**:
The following query runs correctly from sense:

    {"filter" : {"terms" : { "myId" : [123, 456 ] }}} 

The same query fails when executed using TransportClient:
```

Caused by: [catalog] QueryParsingException[No query registered for [filter]]
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:248)
        at org.elasticsearch.index.query.WrapperQueryParser.parse(WrapperQueryParser.java:63)
        at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:250)
        at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:320)
        at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:223)
        at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:218)
        at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:838)

```

**Describe the feature**:

**Comment by sorokod** [comment]
https://github.com/elastic/elasticsearch/issues/20020
Related?

**Comment by jpountz** [comment]
Is the `Sense` query the whole json that you sent, or only what lived under `query`? In the former case, you are comparing apples to oranges since the wrapper query only allows you to set the query part, not the whole request body.

**Comment by sorokod** [comment]
In both cases it is exactly the same query. As the wrapper query is pretty much undocumented, what changes need to be made to `{"filter" : {"terms" : { "myId" : [123, 456 ] }}}` for the wrapper query to execute the same logic?

**Comment by jpountz** [comment]
It would be `{"terms" : { "myId" : [123, 456 ] }}`

**Comment by clintongormley** [comment]
Also, note that the wrapper query has been removed in 5.0

**Comment by sorokod** [comment]
Your that end up being a query or a filter?

**Comment by jpountz** [comment]
Queries and filters are the same nowadays if they only compute scores on demand. Whether this will be used as a query or filter depends on whether you put it as a top-level query, in a `filter` clause, under a `constant_score` query, etc.
