### ISSUE TITLE
Can not start ec2 discovery on 5.0.0

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#20296]
I'm testing ec2 discovery with alpha6-SNAPSHOT (e5ff3da) and I'm getting this error which seems to be related to LOG4J.

```
2016-09-02 09:31:36,200 main ERROR An exception occurred processing Appender console java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.nio.ch")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1564)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:311)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.logging.log4j.util.LoaderUtil.loadClass(LoaderUtil.java:122)
	at org.apache.logging.log4j.core.util.Loader.loadClass(Loader.java:228)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.loadClass(ThrowableProxy.java:496)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.toExtendedStackTrace(ThrowableProxy.java:617)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:163)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:138)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:117)
	at org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:314)
	at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:61)
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38)
	at org.apache.logging.log4j.core.layout.PatternLayout$PatternSerializer.toSerializable(PatternLayout.java:294)
	at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:195)
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:180)
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:57)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:120)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:113)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:104)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:155)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:128)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:119)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:390)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:375)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:359)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:349)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1988)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1960)
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:733)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:281)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:100)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:95)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
	at org.elasticsearch.cli.Command.main(Command.java:54)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)
```

**Comment by dadoonet** [comment]
@jasontedor What do you think?

**Comment by dadoonet** [comment]
When I remove ec2 plugin, elasticsearch starts normally.

When I install ec2:

```sh
bin/elasticsearch-plugin install file:///home/ec2-user/discovery-ec2-5.0.0-alpha6-SNAPSHOT.zip
```

Elasticsearch stops without any message:

```
[2016-09-02T09:38:25,174][INFO ][node                     ] [] initializing ...
[2016-09-02T09:38:25,297][INFO ][env                      ] [nWC6hUC] using [1] data paths, mounts [[/ (/dev/xvda1)]], net usable_space [6.3gb], net total_space [7.7gb], spins? [no], types [ext4]
[2016-09-02T09:38:25,298][INFO ][env                      ] [nWC6hUC] heap size [247.6mb], compressed ordinary object pointers [true]
[2016-09-02T09:38:25,299][INFO ][node                     ] [nWC6hUC] node name [nWC6hUC] derived from node ID; set [node.name] to override
[2016-09-02T09:38:25,303][INFO ][node                     ] [nWC6hUC] version[5.0.0-alpha6-SNAPSHOT], pid[9125], build[e5ff3da/2016-09-01T09:45:15.021Z], OS[Linux/4.4.11-23.53.amzn1.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_101/25.101-b13]
[2016-09-02T09:38:27,234][INFO ][plugins                  ] [nWC6hUC] loaded module [aggs-matrix-stats]
[2016-09-02T09:38:27,239][INFO ][plugins                  ] [nWC6hUC] loaded module [ingest-common]
[2016-09-02T09:38:27,239][INFO ][plugins                  ] [nWC6hUC] loaded module [lang-expression]
[2016-09-02T09:38:27,239][INFO ][plugins                  ] [nWC6hUC] loaded module [lang-groovy]
[2016-09-02T09:38:27,239][INFO ][plugins                  ] [nWC6hUC] loaded module [lang-mustache]
[2016-09-02T09:38:27,239][INFO ][plugins                  ] [nWC6hUC] loaded module [lang-painless]
[2016-09-02T09:38:27,239][INFO ][plugins                  ] [nWC6hUC] loaded module [percolator]
[2016-09-02T09:38:27,239][INFO ][plugins                  ] [nWC6hUC] loaded module [reindex]
[2016-09-02T09:38:27,240][INFO ][plugins                  ] [nWC6hUC] loaded module [transport-netty3]
[2016-09-02T09:38:27,240][INFO ][plugins                  ] [nWC6hUC] loaded module [transport-netty4]
[2016-09-02T09:38:27,241][INFO ][plugins                  ] [nWC6hUC] loaded plugin [discovery-ec2]
[2016-09-02T09:38:30,751][INFO ][node                     ] [nWC6hUC] initialized
[2016-09-02T09:38:30,752][INFO ][node                     ] [nWC6hUC] starting ...
[2016-09-02T09:38:31,048][INFO ][transport                ] [nWC6hUC] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
Processus arrêté
```

I'm using 

```sh
$ java -version
openjdk version "1.8.0_101"
OpenJDK Runtime Environment (build 1.8.0_101-b13)
OpenJDK 64-Bit Server VM (build 25.101-b13, mixed mode)
```

**Comment by jasontedor** [comment]
I think that Log4j is trying to log some exception that is thrown, but does not have permissions to access `sun.nio.ch`. I think that this is just hiding the real exception. Can you grant `java.lang.RuntimePermission` `accessClassInPackage.sun.nio.ch` and see what the real exception here is?

**Comment by dadoonet** [comment]
For the record, I'm not able to reproduce all that locally with:

```sh
$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

I'm going to make the suggested change and deploy on ec2 again to get more details if possible.

**Comment by dadoonet** [comment]
So the real exception is:

```
[2016-09-02T14:33:19,273][ERROR][bootstrap                ] [K7iceog] Exception
org.elasticsearch.http.BindHttpException: Failed to bind to [org.elasticsearch.common.transport.PortsRange@2a19a0fe]
	at org.elasticsearch.http.netty4.Netty4HttpServerTransport.bindAddress(Netty4HttpServerTransport.java:440) ~[?:?]
	at org.elasticsearch.http.netty4.Netty4HttpServerTransport.createBoundHttpAddress(Netty4HttpServerTransport.java:338) ~[?:?]
	at org.elasticsearch.http.netty4.Netty4HttpServerTransport.doStart(Netty4HttpServerTransport.java:324) ~[?:?]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68) ~[elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.http.HttpServer.doStart(HttpServer.java:77) ~[elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68) ~[elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.node.Node.start(Node.java:553) ~[elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:193) ~[elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:257) [elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:100) [elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:95) [elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) [elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88) [elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.cli.Command.main(Command.java:54) [elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74) [elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67) [elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
Caused by: java.net.BindException: Ne peut attribuer l'adresse demandée
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_101]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_101]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_101]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_101]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:127) ~[?:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:511) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:496) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980) ~[?:?]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250) ~[?:?]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:363) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) ~[?:?]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_101]
```

Was caused by a bad configuration in `elasticsearch.yml` file.

I'm still having an issue which happens when I have ec2 installed but I don't define any configuration in `elasticsearch.yml`. Full logs here: https://gist.github.com/dadoonet/56108d664bbc79379f578c2d4288df70

In my console, I have:

```
2016-09-02 14:46:55,789 main ERROR An exception occurred processing Appender rolling java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.reflect")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1564)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:311)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.logging.log4j.util.LoaderUtil.loadClass(LoaderUtil.java:122)
	at org.apache.logging.log4j.core.util.Loader.loadClass(Loader.java:228)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.loadClass(ThrowableProxy.java:496)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.toExtendedStackTrace(ThrowableProxy.java:617)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:135)
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:117)
	at org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:314)
	at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:61)
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38)
	at org.apache.logging.log4j.core.layout.PatternLayout$PatternSerializer.toSerializable(PatternLayout.java:294)
	at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:195)
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:180)
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:57)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:120)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:113)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:104)
	at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:86)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:155)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:128)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:119)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:390)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:375)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:359)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:349)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2011)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1884)
	at org.apache.logging.log4j.spi.AbstractLogger.debug(AbstractLogger.java:442)
	at org.elasticsearch.transport.netty4.Netty4InternalESLogger.debug(Netty4InternalESLogger.java:84)
	at io.netty.util.NetUtil$1.run(NetUtil.java:273)
	at io.netty.util.NetUtil$1.run(NetUtil.java:247)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.NetUtil.<clinit>(NetUtil.java:247)
	at io.netty.util.internal.MacAddressUtil.bestAvailableMac(MacAddressUtil.java:53)
	at io.netty.channel.DefaultChannelId.defaultMachineId(DefaultChannelId.java:127)
	at io.netty.channel.DefaultChannelId.<clinit>(DefaultChannelId.java:104)
	at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:107)
	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:79)
	at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84)
	at io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:85)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:71)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:319)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:281)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:277)
	at org.elasticsearch.transport.netty4.Netty4Transport.bind(Netty4Transport.java:475)
	at org.elasticsearch.transport.netty4.Netty4Transport.bind(Netty4Transport.java:91)
	at org.elasticsearch.transport.TcpTransport.lambda$bindToPort$940(TcpTransport.java:609)
	at org.elasticsearch.common.transport.PortsRange.iterate(PortsRange.java:73)
	at org.elasticsearch.transport.TcpTransport.bindToPort(TcpTransport.java:607)
	at org.elasticsearch.transport.TcpTransport.bindServer(TcpTransport.java:591)
	at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:182)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:178)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
	at org.elasticsearch.node.Node.start(Node.java:502)
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:193)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:257)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:100)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:95)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
	at org.elasticsearch.cli.Command.main(Command.java:54)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)
```

And the process immediately stops.

**Comment by dadoonet** [comment]
Apparently, as soon as I add `network.host: _ec2_` the process starts. I still have the same trace though.

**Comment by dadoonet** [comment]
New test with 2 nodes:

```yaml
cloud.aws.access_key: "MYKEY"
cloud.aws.secret_key: "MYSECRET"
cloud.aws.region: eu-central-1
network.host: _ec2_
discovery.type: ec2
```

When I start the second node, I'm getting:

```
[2016-09-02T15:01:14,208][INFO ][transport                ] [W810Von] publish_address {172.31.7.122:9300}, bound_addresses {172.31.7.122:9300}
...
[2016-09-02T15:01:15,321][DEBUG][com.amazonaws.requestId  ] AWS Request ID: 392b0c38-0835-4e1f-b1a9-df868f78d7ce
[2016-09-02T15:01:15,326][DEBUG][discovery.ec2            ] [W810Von] using dynamic discovery nodes [{#cloud-i-a316ce1f-0}{6QCA1_PVSDS9TvYPeoIPTA}{10.35.149.94}{10.35.149.94:9300}, {#cloud-i-dfaf1762-0}{UJYFQx7WTX6jf8Kt3RuKAQ}{10.35.20.247}{10.35.20.247:9300}, {#cloud-i-26b4549b-0}{gDcZMSdQSKKMAc1hx-cZGQ}{10.35.130.115}{10.35.130.115:9300}, {#cloud-i-b6bd050b-0}{uGiP4g9zRsu5nxh4G5e8rg}{10.35.16.171}{10.35.16.171:9300}, {#cloud-i-d37ba06f-0}{EaquIySbR16p_jYzi-upmw}{10.35.153.73}{10.35.153.73:9300}, {#cloud-i-96fabc2a-0}{IaqpUcACTHSASPtFwbtuQw}{10.35.40.199}{10.35.40.199:9300}, {#cloud-i-b1aaec0d-0}{a-jwOq6jRCirQuiwAfLuAg}{10.35.52.154}{10.35.52.154:9300}, {#cloud-i-22b3539f-0}{eFkhAa2bTlqezEF33CD7oA}{10.35.143.143}{10.35.143.143:9300}, {#cloud-i-ac025b10-0}{2KA4R9HJTK2BnZbIit1eyQ}{172.31.7.122}{172.31.7.122:9300}, {#cloud-i-ad025b11-0}{9RsoYYy2RiaxLSvEMvI0bA}{172.31.7.123}{172.31.7.123:9300}]
[2016-09-02T15:01:15,415][DEBUG][transport.netty4         ] [W810Von] connected to node [{#zen_unicast_15_#cloud-i-ad025b11-0#}{moGN20VwS4K7KNe48WZC-A}{172.31.7.123}{172.31.7.123:9300}]
[2016-09-02T15:01:15,451][DEBUG][netty.buffer.AbstractByteBuf] -Dio.netty.buffer.bytebuf.checkAccessible: true
[2016-09-02T15:01:15,459][DEBUG][netty.util.ResourceLeakDetectorFactory] Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@6eb01749
[2016-09-02T15:01:15,471][DEBUG][netty.util.Recycler      ] -Dio.netty.recycler.maxCapacityPerThread: 32768
[2016-09-02T15:01:15,471][DEBUG][netty.util.Recycler      ] -Dio.netty.recycler.maxSharedCapacityFactor: 2
[2016-09-02T15:01:15,471][DEBUG][netty.util.Recycler      ] -Dio.netty.recycler.linkCapacity: 16
[2016-09-02T15:01:15,471][DEBUG][netty.util.Recycler      ] -Dio.netty.recycler.ratio: 8
Processus arrêté
```

The process immediately dies.

I have no clue about what is happening there.

**Comment by dadoonet** [comment]
When on server `172.31.7.122`, I'm running:

```sh
curl 172.31.7.123:9200
curl: (52) Empty reply from server
```

And the node running on `172.31.7.123` dies with nothing in logs but this in the console:

```
Processus arrêté
```

**Comment by dadoonet** [comment]
Ok. Forget about all that mess. Was mainly caused by not enough memory...
As for GCE, I was using a 512mb instance which does not seem to be enough. It runs fine with a 1Gb instance (even if I'm still using 256m heap size).

I'm closing this issue. May be we should keep it open though until we have a fix for the LOG4J2 issue?

**Comment by jasontedor** [comment]
Superseded by #20304
