### ISSUE TITLE
Reintroduce default log level for AWS APIs

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#20294]
When we introduced LOG4J2 (see #20235), we forgot to add back the default log levels for some APIs:

```yaml
  # reduce the logging for aws, too much is logged under the default INFO
  com.amazonaws: WARN
  # aws will try to do some sketchy JMX stuff, but its not needed.
  com.amazonaws.jmx.SdkMBeanRegistrySupport: ERROR
  com.amazonaws.metrics.AwsSdkMetrics: ERROR
```

When starting Elasticsearch 5.0.0 with ec2 plugin, it now prints some logs we were hiding previously:

```
[2016-09-02T08:48:14,329][WARN ][com.amazonaws.jmx.SdkMBeanRegistrySupport] 
java.security.AccessControlException: access denied ("javax.management.MBeanServerPermission" "findMBeanServer")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_101]
	at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_101]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_101]
	at javax.management.MBeanServerFactory.checkPermission(MBeanServerFactory.java:413) ~[?:1.8.0_101]
	at javax.management.MBeanServerFactory.findMBeanServer(MBeanServerFactory.java:361) ~[?:1.8.0_101]
	at com.amazonaws.jmx.MBeans.getMBeanServer(MBeans.java:111) ~[aws-java-sdk-core-1.10.69.jar:?]
	at com.amazonaws.jmx.MBeans.registerMBean(MBeans.java:50) ~[aws-java-sdk-core-1.10.69.jar:?]
	at com.amazonaws.jmx.SdkMBeanRegistrySupport.registerMetricAdminMBean(SdkMBeanRegistrySupport.java:27) [aws-java-sdk-core-1.10.69.jar:?]
	at com.amazonaws.metrics.AwsSdkMetrics.registerMetricAdminMBean(AwsSdkMetrics.java:377) [aws-java-sdk-core-1.10.69.jar:?]
	at com.amazonaws.metrics.AwsSdkMetrics.<clinit>(AwsSdkMetrics.java:338) [aws-java-sdk-core-1.10.69.jar:?]
	at com.amazonaws.AmazonWebServiceClient.requestMetricCollector(AmazonWebServiceClient.java:563) [aws-java-sdk-core-1.10.69.jar:?]
	at com.amazonaws.AmazonWebServiceClient.isRMCEnabledAtClientOrSdkLevel(AmazonWebServiceClient.java:504) [aws-java-sdk-core-1.10.69.jar:?]
	at com.amazonaws.AmazonWebServiceClient.isRequestMetricsEnabled(AmazonWebServiceClient.java:496) [aws-java-sdk-core-1.10.69.jar:?]
	at com.amazonaws.AmazonWebServiceClient.createExecutionContext(AmazonWebServiceClient.java:457) [aws-java-sdk-core-1.10.69.jar:?]
	at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:5382) [aws-java-sdk-ec2-1.10.69.jar:?]
	at org.elasticsearch.discovery.ec2.AwsEc2UnicastHostsProvider.fetchDynamicNodes(AwsEc2UnicastHostsProvider.java:116) [discovery-ec2-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.discovery.ec2.AwsEc2UnicastHostsProvider$DiscoNodesCache.refresh(AwsEc2UnicastHostsProvider.java:234) [discovery-ec2-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.discovery.ec2.AwsEc2UnicastHostsProvider$DiscoNodesCache.refresh(AwsEc2UnicastHostsProvider.java:219) [discovery-ec2-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.common.util.SingleObjectCache.getOrRefresh(SingleObjectCache.java:54) [elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.discovery.ec2.AwsEc2UnicastHostsProvider.buildDynamicNodes(AwsEc2UnicastHostsProvider.java:102) [discovery-ec2-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPings(UnicastZenPing.java:339) [elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.ping(UnicastZenPing.java:243) [elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.discovery.zen.ping.ZenPingService.ping(ZenPingService.java:106) [elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.discovery.zen.ping.ZenPingService.pingAndWait(ZenPingService.java:84) [elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.discovery.zen.ZenDiscovery.findMaster(ZenDiscovery.java:895) [elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:382) [elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.discovery.zen.ZenDiscovery.access$4100(ZenDiscovery.java:92) [elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.discovery.zen.ZenDiscovery$JoinThreadControl$1.run(ZenDiscovery.java:1216) [elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:444) [elasticsearch-5.0.0-alpha6-SNAPSHOT.jar:5.0.0-alpha6-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by jasontedor** [comment]
> we forgot to add back the default log levels for some APIs

It was intentional, I do not think it belongs in the main configuration file, but we can add it to the plugin configuration file since I added support for multiple configuration files.

I opened #20313
