### ISSUE TITLE
Log4j can lose critical exceptions

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#20304]
Start two nodes of Elasticsearch, intentionally binding to the same port:

```
$ bin/elasticsearch -E transport.tcp.port=9300 -E node.max_local_storage_nodes=2
```

Wait for this instance to start, then from another terminal:

```
$ bin/elasticsearch -E transport.tcp.port=9300 -E node.max_local_storage_nodes=2
```

The second node will fail to bind, as expected. However, instead of displaying an already bound exception, Log4j fails in the presence of the security manager and loses the original exception instead producing:

```
2016-09-02 13:46:33,968 main ERROR An exception occurred processing Appender rolling java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.nio.ch")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1564)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:311)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.apache.logging.log4j.util.LoaderUtil.loadClass(LoaderUtil.java:122)
        at org.apache.logging.log4j.core.util.Loader.loadClass(Loader.java:228)
        at org.apache.logging.log4j.core.impl.ThrowableProxy.loadClass(ThrowableProxy.java:496)
        at org.apache.logging.log4j.core.impl.ThrowableProxy.toExtendedStackTrace(ThrowableProxy.java:617)
        at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:163)
        at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:138)
        at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:117)
        at org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:314)
        at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:61)
        at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38)
        at org.apache.logging.log4j.core.layout.PatternLayout$PatternSerializer.toSerializable(PatternLayout.java:294)
        at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:195)
        at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:180)
        at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:57)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:120)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:113)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:104)
        at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:86)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:155)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:128)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:119)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:390)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:375)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:359)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:349)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
        at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1988)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1960)
        at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:733)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:281)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:100)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:95)
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
        at org.elasticsearch.cli.Command.main(Command.java:54)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)
```

This is due to Log4j attempting to load a class that it does not have the permissions to load and this exception goes uncaught.

This is not the only place that this occurs. Effectively, it can occur anywhere the native-like code is executing (think networking, filesystem access, etc.) and an exception is thrown (there are reports of four different examples of this already, the above is just the simplest reproduction).

**Comment by jasontedor** [comment]
I will submit a patch to Log4j for this. Depending on their release plans, I will add a hack to get around this.

**Comment by jasontedor** [comment]
I submitted https://issues.apache.org/jira/browse/LOG4J2-1560 to Log4j.

**Comment by s1monw** [comment]
@jasontedor do we have a workaround for this? Maybe we can remove the blocker label if that is the case?
