### ISSUE TITLE
NoClassDefFoundError SmileParser$Feature

### ISSUE THREAD

**Issue by paulognr** [elastic/elasticsearch#20319]
**Elasticsearch version**: 2.4.0

**Plugins installed**: []

**JVM version**: 1.8.0_101

**OS version**: Windows 10

Hi.

I'm using wildfly-swarm (2016.8.1) (fraction jaxrs-cdi) and elasticsearch 2.4.0.
When I need to use a SearhResponse happens the error described below:

Caused by: java.lang.NoClassDefFoundError: Failed to link com/fasterxml/jackson/dataformat/smile/SmileParser$Feature (Module "deployment.d8ecf032-4a19-4c89-bc96-fd7bfe232f28.war:main" from Service Module Loader): com/fasterxml/jackson/core/FormatFeature
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:446)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:274)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:78)
	at org.jboss.modules.Module.loadModuleClass(Module.java:605)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
	at com.fasterxml.jackson.dataformat.smile.SmileFactory.<clinit>(SmileFactory.java:47)
	at org.elasticsearch.common.xcontent.smile.SmileXContent.<clinit>(SmileXContent.java:44)
	at org.elasticsearch.common.xcontent.XContentFactory.contentBuilder(XContentFactory.java:124)
	at org.elasticsearch.action.support.ToXContentToBytes.buildAsBytes(ToXContentToBytes.java:62)
	at org.elasticsearch.action.search.SearchRequest.source(SearchRequest.java:250)
	at org.elasticsearch.action.search.SearchRequestBuilder.beforeExecute(SearchRequestBuilder.java:1027)
	at org.elasticsearch.action.search.SearchRequestBuilder.beforeExecute(SearchRequestBuilder.java:50)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56)
	at br.com.hunterco.impl.service.HunterServiceBean.find(HunterServiceBean.java:35)
	at br.com.hunterco.impl.service.HunterServiceBean$Proxy$_$$_WeldClientProxy.find(Unknown Source)
	at br.com.hunterco.rest.HunterRest.find(HunterRest.java:26)
	at br.com.hunterco.rest.HunterRest$Proxy$_$$_WeldClientProxy.find(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395)

When I use GetResponse works.

Tks.

**Comment by clintongormley** [comment]
Hi @paulognr 

We don't support running Elasticsearch as embedded.  See https://www.elastic.co/blog/elasticsearch-the-server
