### ISSUE TITLE
failed to parse setting: percentage value not recognized.

### ISSUE THREAD

**Issue by obudiman** [elastic/elasticsearch#20330]
**Elasticsearch version**: 5.0.0_alpha5

**Plugins installed**: x-pack 5.0.0_alpha5

**JVM version**: OpenJDK Runtime Environment (build 1.8.0_101-b13)

**OS version**: Linux 4.4.11-23.53.amzn1.x86_64

**Description of the problem including expected versus actual behavior**:

Elasticsearch failed to start with the following error message:
[WARN ][bootstrap                ] [elk5a_node01] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupError: java.lang.IllegalArgumentException: failed to parse setting [indices.fielddata.cache.size] with value [50%] as a size in bytes: unit is missing or unrecognized
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:105)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:96)
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
        at org.elasticsearch.cli.Command.main(Command.java:54)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:75)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:68)
Caused by: java.lang.IllegalArgumentException: failed to parse setting [indices.fielddata.cache.size] with value [50%] as a size in bytes: unit is missing or unrecognized
        at org.elasticsearch.common.settings.Setting.get(Setting.java:307)
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:272)
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:238)
        at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:138)
        at org.elasticsearch.node.Node.<init>(Node.java:298)
        at org.elasticsearch.node.Node.<init>(Node.java:206)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:175)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:175)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:255)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:101)
        ... 6 more
Caused by: ElasticsearchParseException[failed to parse setting [indices.fielddata.cache.size] with value [50%] as a size in bytes: unit is missing or unrecognized]
        at org.elasticsearch.common.unit.ByteSizeValue.parseBytesSizeValue(ByteSizeValue.java:213)
        at org.elasticsearch.common.unit.ByteSizeValue.parseBytesSizeValue(ByteSizeValue.java:172)
        at org.elasticsearch.common.settings.Setting.lambda$byteSizeSetting$18(Setting.java:571)
        at org.elasticsearch.common.settings.Setting.get(Setting.java:305)
        ... 15 more

**Steps to reproduce**:
 1. Add the following lines to elasticsearch.yml

indices.fielddata.cache.size: "50%"
indices.queries.cache.size: "20%"

 2. Restart elasticsearch

**Comment by colings86** [comment]
I reproduced this on the current master branch. It looks like this (ability to specify the cache sizes as a percentage) might have been accidentally removed when we cut over to the new settings infrastructure.
