### ISSUE TITLE
elsticsearch-plugin list results in error message if there are no plugins installed

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#20342]
**Elasticsearch version**: latest master (2b43c6db3a5bdd822e14b091925bae609b4e286e)

**Plugins installed**: []

**Description of the problem including expected versus actual behavior**: When I run 

`elsticsearch-plugin list` 

with no plugin installed I would expect the list returned is empty. Instead I get:

```
$ ./elasticsearch-5.0.0-alpha6-SNAPSHOT/bin/elasticsearch-plugin  list
Exception in thread "main" java.io.IOException: Plugins directory missing: /home/britta/es-token-plugin/src/test/resources/r-demo/elasticsearch-5.0.0-alpha6-SNAPSHOT/plugins
    at org.elasticsearch.plugins.ListPluginsCommand.execute(ListPluginsCommand.java:51)
    at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
    at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
    at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
    at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
    at org.elasticsearch.cli.Command.main(Command.java:54)
    at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:57)

```

**Comment by dadoonet** [comment]
That's indeed happening with a new installation of elasticsearch when elasticsearch has never been launched.
Once elasticsearch is launched, it creates the missing `plugins` dir.

**Comment by dadoonet** [comment]
Looking at the code it was intentional to fail instead of reporting an empty list and eventually log the fact that the dir is missing.
@rjernst Do you remember this?

**Comment by rjernst** [comment]
I remember there is leniency for the dir not existing in the plugin manager because, IIRC, of tests not explicitly creating the plugins dir. I think we should add that and keep this a hard failure? All the packages should already have a plugins dir created right?

**Comment by rjernst** [comment]
Perhaps it is also the zip/tar.gz that don't have an empty plugins dir (seems that might be the case here). I think we can add that so all the packages don't get this failure.

**Comment by dadoonet** [comment]
Indeed. If doable, I'm +1 to have plugins dir in our archives.

**Comment by jpountz** [comment]
+1 to always having a plugins dir.
