### ISSUE TITLE
ArrayIndexOutOfBoundsException in WriteRequest with TransportClient 5.0.0-alpha5

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#20372]
**Elasticsearch version**: 5.0.0-alpha5
**Plugins installed**: []
**JVM version**: 1.8
**OS version**: Mac OS
**Description of the problem including expected versus actual behavior**:

Error when injecting data from a TransportClient (in Java)

**Steps to reproduce**:

Basically, I have a node running at 127.0.0.1:9300:

```
[2016-09-07 17:25:21,003][INFO ][node                     ] [3UMcJFq] version[5.0.0-alpha5], pid[14725], build[d327dd4/2016-08-04T08:59:39.568Z], OS[Mac OS X/10.11.6/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_60/25.60-b23]
[2016-09-07 17:25:30,651][INFO ][io.netty.util.internal.PlatformDependent] Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
...
[2016-09-07 17:25:50,272][INFO ][transport                ] [3UMcJFq] publish_address {127.0.0.1:9300}, bound_addresses {[fe80::1]:9300}, {[::1]:9300}, {127.0.0.1:9300}
``` 

Then I'm starting a client like this:

```java
        this.esClient = new PreBuiltTransportClient(Settings.EMPTY)
                .addTransportAddress(new InetSocketTransportAddress(new InetSocketAddress("127.0.0.1", 9300)));
```

And indexing with:

```java
    public void save(Person person) throws JsonProcessingException {
        byte[] bytes = mapper.writeValueAsBytes(person);
        esClient.index(new IndexRequest("person", "person", person.getReference()).source(bytes)).actionGet();
    }
```

**Provide logs (if relevant)**:

Logs on the client side:

```
17:34:25.352 [ERROR] f.p.d.l.s.PersonService - Houston, we have a problem!
java.lang.ArrayIndexOutOfBoundsException: 97
	at org.elasticsearch.action.support.WriteRequest$RefreshPolicy.readFrom(WriteRequest.java:101) ~[elasticsearch-5.0.0-alpha5.jar:5.0.0-alpha5]
	at org.elasticsearch.action.support.replication.ReplicatedWriteRequest.readFrom(ReplicatedWriteRequest.java:64) ~[elasticsearch-5.0.0-alpha5.jar:5.0.0-alpha5]
	at org.elasticsearch.action.index.IndexRequest.readFrom(IndexRequest.java:630) ~[elasticsearch-5.0.0-alpha5.jar:5.0.0-alpha5]
	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1296) ~[elasticsearch-5.0.0-alpha5.jar:5.0.0-alpha5]
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1198) ~[elasticsearch-5.0.0-alpha5.jar:5.0.0-alpha5]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) ~[transport-netty4-client-5.0.0-alpha5.jar:5.0.0-alpha5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) ~[netty-codec-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280) ~[netty-codec-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396) ~[netty-codec-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[netty-codec-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:474) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:428) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398) ~[netty-transport-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877) ~[netty-common-4.1.4.Final-elastic-SNAPSHOT.jar:4.1.4.Final-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```

Nothing in server logs.

I did not test yet the alpha6-SNAPSHOT (master branch). May be it has been fixed in the meantime.

**Comment by jasontedor** [comment]
I think that we need to see the contents of the byte array representing `person` here, there are plenty of tests using effectively exactly the same code that you have here. Can you double-check your serialization of `person` or provide a unit test that reproduces this without an external dependency.

**Comment by dadoonet** [comment]
I will. Just for the record, same code works with alpha4.

**Comment by jasontedor** [comment]
That's fine, but we can't debug this until we have a byte array that reproduces the issue.

**Comment by s1monw** [comment]
@dadoonet any chance that you transport client is still alpha4 and the server is alpha5? can you check you are using the right jar on the client?

**Comment by bleskes** [comment]
The liveness request from the client will fail due to minCompatibleVersion checks, preventing alpha5 from speaking to alpha4.

**Comment by s1monw** [comment]
@bleskes I might be wrong but it seems like if you use sniffing it's not doing that. And if we don't use the handshake connect but we should? @dadoonet do you use sniffing?

**Comment by dadoonet** [comment]
I don't but IIRC one of my tests it was impossible to use a client version alpha4 with a node running alpha5. 

But I'll double check all that tomorrow.
And I'll try to reproduce with a test as suggested by Jason.

**Comment by dadoonet** [comment]
Ok. @s1monw is right. Apparently I had in my classpath an old version of something.
I looked at my local .m2 `transport-netty4-client` pom and it was having dependencies on a netty version built by us SNAPSHOT version. Not sure why this happens but here is what I did:

* remove all files in `.m2/repository/org/elasticsearch`
* run `mvn clean install` on my project
* start again

And everything is working fine.

Sorry for the false alarm.

**Comment by s1monw** [comment]
now the question is why was this client able to connect to the node at all?

**Comment by s1monw** [comment]
> [Ok. @s1monw is right.](https://www.youtube.com/watch?v=Uz1Jwyxd4tE)

;)

**Comment by dadoonet** [comment]
@s1monw I think that I was having both versions of the libs on the classpath? That might explain why I was able to use `PreBuiltTransportClient` class (which came only in alpha5 - transport jar).
And I guess that elasticsearch jar alpha4 was still on the classpath.

**Comment by s1monw** [comment]
oh man, jar hell? I guess you should enable jarhell checks in your app. I will use this as an example for everybody complaining in the future.

**Comment by dadoonet** [comment]
> I will use this as an example for everybody complaining in the future.

Definitely
