### ISSUE TITLE
Cluster node unresponsive after parallel search

### ISSUE THREAD

**Issue by xxwikluo** [elastic/elasticsearch#20444]
**Elasticsearch version**: 2.3.1

**Plugins installed**: [head (+ our custom plugin)]

**JVM version**: 1.8.0_40

**OS version**: 2.6.32-358.23.2.el6.x86_64 (Linux)

**Description of the problem including expected versus actual behavior**:
Hi, we're developing a custom plugin in Java with some restActions and we're experiencing some cluster node hangs/unresponsiveness after running some of our custom endpoints where we are doing some searches in parallel with a shared instance of org.elasticsearch.client.Client. Only the node handling the request is affected from what I could see.

Our cluster is running 3 nodes where two are masters and one is a data node.

I have been unable to reproduce the issue in a test environment running a single node (one shard, no replicas) on win7, but can constantly reproduce otherwise with the rest endpoint example below.
Usually it requires a couple of refreshes (1-5) before hanging.

When the node goes unresponsive not every operation seizes, for example another of our end points (not doing a `search` but only a simple `get`) will still work. Noted that `_cat/plugins` will become unresponsive but `_node/node_name/_all` still works.

Tests without the threading part seem to yield no issues; but client instances are supposedly thread safe and adding synchronization doesn't help.

Searching on the issue have yielded little fruit, so any input is welcome.

**Example code**
```
package com.xxx.es.test.rest;

import static org.elasticsearch.rest.RestRequest.Method.GET;

import org.elasticsearch.action.ActionListener;
import org.elasticsearch.action.get.GetRequest;
import org.elasticsearch.action.get.GetResponse;
import org.elasticsearch.action.search.SearchResponse;
import org.elasticsearch.client.Client;
import org.elasticsearch.common.inject.Inject;
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.rest.BaseRestHandler;
import org.elasticsearch.rest.BytesRestResponse;
import org.elasticsearch.rest.RestChannel;
import org.elasticsearch.rest.RestController;
import org.elasticsearch.rest.RestRequest;
import org.elasticsearch.rest.RestStatus;

public class TestAction extends BaseRestHandler {

    final static String EVENTS_INDEX = "allevents";
    final static String TYPE = "documents";
    private String eventIndices;

    @Inject
    public TestAction(Settings settings, RestController controller, Client client) {
        super(settings, controller, client);
        this.eventIndices = settings.get("indexes.events", EVENTS_INDEX);
        controller.registerHandler(GET, "/_test/{id}", this);
    }

    @Override
    protected void handleRequest(RestRequest request, RestChannel channel, Client client) throws Exception {
        final String id1 = request.param("id");

        GetRequest getRequest = new GetRequest(this.eventIndices.trim().split("//s*,//s*")[0], TYPE, id1);

        client.get(getRequest, new ActionListener<GetResponse>() {

            @Override
            public void onResponse(GetResponse response) {

                Thread[] threads = new Thread[2];
                for (int i = 0; i < threads.length; i++) {
                    threads[i] = new Thread(new Runnable() {

                        @Override
                        public void run() {
                            SearchResponse srsp = client.prepareSearch(
                                    eventIndices.trim().split("//s*,//s*"))
                                    .setTypes(TYPE)
                                    .setSize(0)
                                    .execute().actionGet();
                        }
                    });
                    threads[i].run();
                }

                channel.sendResponse(new BytesRestResponse(RestStatus.OK, "Done."));
            }

            @Override
            public void onFailure(Throwable e) {}
        });
    }
}
```

**Steps to reproduce**:
 1. Setup a cluster and make a plugin with the test rest endpoint
 2. Run the endpoint a few times (5~6)
 3. Experience a 502 Proxy Error as the node becomes unresponsive.

**Provide logs (if relevant)**:
excerpt from jstack on the unresponsive node:
```
elasticsearch[es102-xxx][transport_client_worker][T#1]{New I/O worker #1}" #18 daemon prio=5 os_prio=0 tid=0x00007fbaa950a800 nid=0x4746 waiting on condition [0x00
007fba88b33000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000603b06e10> (a org.elasticsearch.common.util.concurrent.BaseFuture$Sync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:276)
        at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:116)
        at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:42)
        at com.xxx.es.test.rest.TestAction$1$1.run(TestAction.java:53)
        at java.lang.Thread.run(Thread.java:745)
        at com.xxx.es.test.rest.TestAction$1.onResponse(TestAction.java:56)
...
```

**Comment by bleskes** [comment]
We try to reserve github for issues. For discussion/questions/help requests, I would ask you to use http://discuss.elastic.co

A quick glance at your code shows at least one thing that's wrong: you need to deal with failures and respond to channel in your `public void onFailure(Throwable e) {}  `. I guess that's why you don't hear back from the node.

I'm closing this. If the above doesn't work, please ask in the forums.

**Comment by xxwikluo** [comment]
Well, the lacking onFailure is only this test endpoint, the actual endpoints at least drops some stack traces like:

```
    @Override
    public void onFailure(final Throwable e) {
        try {
            channel.sendResponse(new BytesRestResponse(channel, e));
        } catch (IOException e1) {
            logger.error("Failed to send failure response", e1);
        }
    }
```

But thanks for the reply will go search/ask in the forums.
