### ISSUE TITLE
Elasticsearch does not start if the configured shared repository path is unavailable on windows

### ISSUE THREAD

**Issue by ktgiang** [elastic/elasticsearch#20466]
**Elasticsearch version**:

2.3.1

 

**Plugins installed**: []

 

**JVM version**:

Version 8 Update 51

 

**OS version**:

Windows 7 Enterprise, SP1

 

**Description of the problem including expected versus actual behavior**:

Expect that the elasticsearch will start-up and just log an error even when the path.repo is not available.

Instead the elasticsearch logs an exception and crashes.

 

**Steps to reproduce**:

1.Configure path.repo with a UNC path that is not available.

2.Start Elasticsearch. Note the Exception in the logs provided below.

 

**Provide logs (if relevant)**:

```
D:\elasticsearch-2.3.1\bin>elasticsearch.bat
[2016-09-14 15:56:27,231][WARN ][bootstrap                ] jvm uses the client vm, make sure to run `java` with the server vm for best performance by adding `-server` to the command line
Exception in thread "main" java.lang.IllegalStateException: Unable to access 'path.repo' (\\SERVERNAME\dd\)
Likely root cause: java.nio.file.FileSystemException: \\SERVERNAME\dd\: Unable to determine if root directory exists
        at java.nio.file.Files.createDirectories(Unknown Source)
        at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:337)
        at org.elasticsearch.bootstrap.Security.addPath(Security.java:314)
        at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:262)
        at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:212)
        at org.elasticsearch.bootstrap.Security.configure(Security.java:118)
        at org.elasticsearch.bootstrap.Bootstrap.setupSecurity(Bootstrap.java:196)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:167)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```
 

Refer to the log for complete error details.

**Comment by dadoonet** [comment]
That's the right behavior to have. Elasticsearch fails if you defined something which can not work.
What else would you expect?

Closing as I don't think it's an issue. Feel free to reopen or comment.
BTW a better starting place for discussion is discuss.elastic.co.
