### ISSUE TITLE
The existence of any non-plugin file in the plugins directory will prevent Elasticsearch from starting

### ISSUE THREAD

**Issue by hmanner** [elastic/elasticsearch#20499]
**Elasticsearch version**: 2.2.0

**OS version**: Windows 10 and Windows Server 2012

**Description of the problem including expected versus actual behavior**:

The existence of any non-plugin file in the plugins directory will prevent Elasticsearch from starting. This happened for us in production after someone by mistake left a zip-file with a github download for a plugin. This needs to become more error resilient.

**Steps to reproduce**:
 1. Open plugins directory in Windows Explorer
 2. Right click, create "New Text Document"
 3. Start Elasticsearch 

**Provide logs (if relevant)**:

c:\bin\elasticsearch-2.2.0\bin>.\elasticsearch.bat
[2016-09-15 12:42:05,172][INFO ][node                     ] [John Ryker] version[2.2.0], pid[2008], build[8ff36d1/2016-01-27T13:32:39Z]
[2016-09-15 12:42:05,172][INFO ][node                     ] [John Ryker] initializing ...
Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [New Text Document.txt]. Was the plugin built before 2.0?
Likely root cause: java.nio.file.NoSuchFileException: c:\bin\elasticsearch-2.2.0\plugins\New Text Document.txt\plugin-descriptor.properties
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source)
        at java.nio.file.Files.newInputStream(Unknown Source)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:87)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
        at org.elasticsearch.node.Node.<init>(Node.java:146)
        at org.elasticsearch.node.Node.<init>(Node.java:128)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

**Comment by clintongormley** [comment]
@hmanner this is doing exactly what we want - alerting you to a problem with your setup and forcing you to fix it.

**Comment by hmanner** [comment]
@clintongormley That way of thinking may be ok when setting up a single cluster. But when having thousands of customers with separate clusters in different time zones you will run into issues like this because someone messed up somewhere. That someone could easily do that same mistake on all nodes in the cluster, which will stop the entire cluster. Really bad if the cluster is a vital service. The issue does not appear when the file is created, it is discovered at a reboot/restart at a later time, possibly by someone without Elasticsearch knowledge, making trouble shooting harder. Responding to the issue by not starting the service on a trivial matter like an unknown file, which can easily be ignored, is really bad practice in my opinion. Much better to start the service and add some kind of warning to the cluster health status so that the problem can be investigated and fixed while the system is up and running fully.

**Comment by clintongormley** [comment]
@hmanner I have a completely different opinion on this.  We have made many many changes to make Elasticsearch shout louder when something is wrong instead of silently ignoring problems and trying to do the right thing, which may not turn out to be the right thing and instead makes debugging problems very hard even for experts.

Instead, the exception that you mention makes it pretty simple for an inexperienced user to figure out that `New Text Document.txt` is probably not a plugin:

    Could not load plugin descriptor for existing plugin [New Text Document.txt]. Was the plugin built before 2.0?
    Likely root cause: java.nio.file.NoSuchFileException: c:\bin\elasticsearch-2.2.0\plugins\New Text Document.txt\plugin-descriptor.properties

**Comment by clintongormley** [comment]
As another example of this, we added jarhell checks which complain if you have jars with the same name in your classpath.  Lots of people complained.  But this is what happens if you don't have these checks: https://github.com/elastic/elasticsearch/issues/20372

**Comment by jasontedor** [comment]
> But when having thousands of customers with separate clusters in different time zones you will run into issues like this because someone messed up somewhere. That someone could easily do that same mistake on all nodes in the cluster, which will stop the entire cluster.

If you followed practices like first installing in a non-production environment and using configuration management like Ansible or Puppet, you'd have seen the issue there and adjusted your installation procedure and the human element would be minimized.

> The issue does not appear when the file is created, it is discovered at a reboot/restart at a later time, possibly by someone without Elasticsearch knowledge, making trouble shooting harder.

Plugins are not picked up until a restart anyway, you should be coordinating installation with restarts.
