### ISSUE TITLE
Human friendly output for "dynamic mapping is disabled" errors

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#20495]
**Elasticsearch version**: 5.0.0alpha5

**Plugins installed**: [x-pack]

**JVM version**: Oracle 1.8.0_101

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behaviour**: When disabling dynamic mapping and then sending a field to said index that isn't defined, you get a large stack trace. It'd be nicer if we had a clean error for this instead.

**Steps to reproduce**:
 1. Create a mapping with `"dynamic": false`
 2. Send a doc with a field that isn't defined in the mapping
 3. Profit

**Provide logs (if relevant)**:
Here's what we get
```
[2016-09-14 06:32:21,739][DEBUG][action.bulk              ] [WoSpzTS] [.monitoring-data-2][0] failed to execute bulk item (index) index {[.monitoring-data-2][kibana][46713587-51a2-42d8-8761-cde0c50e790c], source[{"cluster_uuid":"HaR_vTapQWCE68i6oJrt2A","timestamp":"2016-09-14T06:32:21.679Z","source_node":{"uuid":"WoSpzTSDTo2rwCS1E-iItQ","host":"10.0.2.15","transport_address":"10.0.2.15:9300","ip":"10.0.2.15","name":"WoSpzTS","attributes":{}},"kibana":{"kibana":{"uuid":"46713587-51a2-42d8-8761-cde0c50e790c","name":"elastic5","host":"elastic5","transport_address":"0.0.0.0:5601","version":"5.0.0-alpha5","snapshot":false,"status":"green","statuses":[{"state":"green"},{"state":"green"},{"state":"green"},{"state":"green"},{"state":"green"},{"state":"green"},{"state":"green"},{"state":"green"},{"state":"green"},{"state":"green"},{"state":"green"},{"state":"green"},{"state":"green"},{"state":"green"},{"state":"green"},{"state":"green"},{"state":"green"}]},"os":{"load":{"1m":0.09619140625,"5m":0.20166015625,"15m":0.18115234375},"memory":{"total_in_bytes":4141158400,"free_in_bytes":359690240,"used_in_bytes":3781468160},"uptime_in_millis":5146000},"process":{"memory":{"heap":{"total_in_bytes":613764704,"used_in_bytes":348768360,"size_limit":1535115264},"resident_set_size_in_bytes":663789568},"event_loop_delay":0.7835029996931553,"uptime_in_millis":566868},"sockets":{"http":{"total":0},"https":{"total":0}},"timestamp":"2016-09-14T06:32:19.474Z","requests":{"total":0,"disconnects":0,"status_codes":{}},"response_times":{"average":null,"max":0},"concurrent_connections":0}}]}
[.monitoring-data-2/7VTT-6vRQsObC6HW2Hm9BQ] TypeMissingException[type[kibana] missing]; nested: IllegalStateException[trying to auto create mapping, but dynamic mapping is disabled];
	at org.elasticsearch.index.mapper.MapperService.documentMapperWithAutoCreate(MapperService.java:541)
	at org.elasticsearch.index.shard.IndexShard.docMapper(IndexShard.java:1582)
	at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:492)
	at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:174)
	at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:179)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:348)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.index(TransportShardBulkAction.java:156)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.handleItem(TransportShardBulkAction.java:135)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.onPrimaryShard(TransportShardBulkAction.java:121)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.onPrimaryShard(TransportShardBulkAction.java:72)
	at org.elasticsearch.action.support.replication.TransportWriteAction.shardOperationOnPrimary(TransportWriteAction.java:75)
	at org.elasticsearch.action.support.replication.TransportWriteAction.shardOperationOnPrimary(TransportWriteAction.java:47)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:843)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:813)
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:106)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:302)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:242)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:784)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:781)
	at org.elasticsearch.index.shard.IndexShardOperationsLock.acquire(IndexShardOperationsLock.java:142)
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock(IndexShard.java:1602)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:793)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:256)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:238)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:230)
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportService$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportService.java:206)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TransportService$5.doRun(TransportService.java:517)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:510)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: trying to auto create mapping, but dynamic mapping is disabled
	... 34 more
```

**Comment by s1monw** [comment]
turn the bloody debug logging off you get betta ones mate!

**Comment by clintongormley** [comment]
1. Setting a type to have `dynamic:false` doesn't throw exceptions.  `dynamic:strict` does
2. The exception is not about adding a new field, it's about adding a new type
3. You have the `index.mapper.dynamic` setting set to `false`, nothing to do with the `dynamic` setting
4. The REST response, which is what the user sees, is clear and easy to read
5. You have DEBUG logging turned on.  Nothing is logged at the default level.

**Comment by markwalkom** [comment]
This is base 5.0, there's no debug enabled.

**Comment by clintongormley** [comment]
Just checked, and you're right - we enable this logging by default.

But we always log the stack trace.  it is important that we don't swallow these. We made a lot of changes to ensure that we don't swallow stack traces as it makes debugging very hard.  It's a bug if we don't log the stack trace.  The REST layer returns a simple exception.
