### ISSUE TITLE
Issue with importing bulk data from text file in 5.0.0-aplha5

### ISSUE THREAD

**Issue by bharvidixit** [elastic/elasticsearch#20549]
**Elasticsearch version**: elasticsearch-5.0.0-alpha5

**Plugins installed**: []

**JVM version**: 1.8.0_72

**OS version**: Ubuntu 15

While importing the data from a text file (attached as natural.txt) using _bulk endpoint i am getting "curl: (52) Empty reply from server".  _Surprisingly if i i import only 5 documents (attached as data.txt), it works fine with 5.0.0-alpha5._
[data.txt](https://github.com/elastic/elasticsearch/files/479624/data.txt)
[natural.txt](https://github.com/elastic/elasticsearch/files/479625/natural.txt)

This natural.txt file and bulk import command works fine with elasticsearch version 2.1.1 and elasticsearch-5.0.0-alpha4 but not with elasticsearch-5.0.0-alpha5.

**Steps to reproduce**:
 1. Find the attached text file natural.txt
 2. Run the following command command to import the documents in ES
 **curl -XPOST localhost:9200/_bulk --data-binary @natural.txt** 

**Provide logs (if relevant)**:
In the Elasticsearch logs i find these exceptions:
[2016-09-19 14:37:28,399][WARN ][http.netty4              ] [PONCbrN] caught exception while handling client http traffic, closing connection [id: 0x8447a835, L:/127.0.0.1:9200 - R:/127.0.0.1:59138]
java.lang.UnsupportedOperationException: unsupported message type: DefaultFullHttpResponse (expected: ByteBuf, FileRegion)
	at io.netty.channel.nio.AbstractNioByteChannel.filterOutboundMessage(AbstractNioByteChannel.java:260)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:799)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1291)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:748)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:811)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:824)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:804)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:841)
	at io.netty.handler.codec.MessageAggregator.decode(MessageAggregator.java:222)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:474)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:428)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)

**Comment by dadoonet** [comment]
I think it's the same issue as reported with #19893 and fixed in beta1 with https://github.com/elastic/elasticsearch/pull/19904

Can you check that if you add `-H "Expect:"` it fixes your issue until beta1 is released?

**Comment by jasontedor** [comment]
Duplicates #19834

**Comment by bharvidixit** [comment]
@dadoonet  Thanks. It worked with `-H "Expect:"` option.
