### ISSUE TITLE
5.0.0alpha5 - java.lang.IllegalArgumentException: unknown setting [node.rack]

### ISSUE THREAD

**Issue by naisanza** [elastic/elasticsearch#20542]
I read through the comments in the `elasticsearch.yml` configuration file and decided to try setting more than just the `cluster.name` and `network.host`

After setting the `node.rack` value, the log produced an error: "unknown setting [node.rack]"

**Elasticsearch version**: 5.0.0 alpha5

**Plugins installed**: [none]

**JVM version**: java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**OS version**: Linux elastic01-world 4.4.6-1-pve #1 SMP Thu Apr 21 11:25:40 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Download Java. Download Elasticsearch
 2. Set elasticsearch.yml configuration
 3. Java error

**Provide logs (if relevant)**:

elasticsearch.yml:
```
cluster.name: recovery
node.name: recovery
node.rack: world
network.host: _site_
discovery.zen.minimum_master_nodes: 1
```

recovery.log.txt:
```
[2016-09-19 03:29:40,435][ERROR][bootstrap                ] Exception
java.lang.IllegalArgumentException: unknown setting [node.rack] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:270)
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:238)
	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:138)
	at org.elasticsearch.node.Node.<init>(Node.java:298)
	at org.elasticsearch.node.Node.<init>(Node.java:206)
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:175)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:175)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:255)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:101)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:96)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
	at org.elasticsearch.cli.Command.main(Command.java:54)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:75)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:68)
```
[recovery.log.txt](https://github.com/elastic/elasticsearch/files/479201/recovery.log.txt)

**Comment by dadoonet** [comment]
Read This: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_settings_changes.html#_node_attribute_settings

Please use discuss.elastic.co if you have other questions.

**Comment by dadoonet** [comment]
Reopening as the sample elasticsearch.yml file is incorrect.
