### ISSUE TITLE
error with  indexing json document

### ISSUE THREAD

**Issue by superwood** [elastic/elasticsearch#20602]
When indexing  document  with  json format like

{
 "namespace": "nginx",
 "type": "record",
 "name": "dm_ad_quest",
 "fields": [
     {"name": "ip", "type": ["string","null"]},
     {"name": "snr", "type": ["string","null"]},
     {"name": "ot", "type": ["string","null"]},
     {"name": "nt", "type": ["string","null"]},
     {"name": "sn", "type": ["string","null"]},
     {"name": "ov", "type": ["string","null"]},
     {"name": "mcc", "type": ["string","null"]},
     {"name": "did", "type": ["string","null"]},
     {"name": "l", "type": ["string","null"]},
     {"name": "mac", "type": ["string","null"]},
     {"name": "aid", "type": ["string","null"]},
     {"name": "gpsv", "type": ["string","null"]},
     {"name": "im", "type": ["string","null"]},
     {"name": "vn", "type": ["string","null"]},
     {"name": "adid", "type": ["string","null"]},
     {"name": "pf", "type": ["string","null"]},
     {"name": "tz", "type": ["string","null"]},
     {"name": "t", "type": ["string","null"]},
     {"name": "dm", "type": ["string","null"]},
     {"name": "sv", "type": ["string","null"]},
     {"name": "mnc", "type": ["string","null"]},
     {"name": "ss", "type": ["string","null"]},
     {"name": "vc", "type": ["string","null"]},
     {"name": "pn", "type": ["string","null"]},
     {"name": "gpv", "type": ["string","null"]},
     {"name": "cc", "type": ["string","null"]},
     {"name": "country", "type": ["string","null"]},
     {"name": "area", "type": ["string","null"]},
     {"name": "prop", "type": {"type": "map", "values": "string"}}
 ]
}

I got error 

org.elasticsearch.action.WriteFailureException
    at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:497)
    at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:409)
    at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:148)
    at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:574)
    at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:440)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
Caused by: org.elasticsearch.index.mapper.MapperParsingException: failed to parse [fields.type]
    at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:411)
    at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:554)
    at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:487)
    at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:554)
    at org.elasticsearch.index.mapper.object.ObjectMapper.serializeNonDynamicArray(ObjectMapper.java:685)
    at org.elasticsearch.index.mapper.object.ObjectMapper.serializeArray(ObjectMapper.java:622)
    at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:489)
    at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:544)
    at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:493)
    at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:493)

**Comment by clintongormley** [comment]
Field `fields.type` is a string field in all entries except the last, where you try to make it an object:

    {"name": "prop", "type": {"type": "map", "values": "string"}}

**Comment by superwood** [comment]
{"name": "prop", "type": {"type": "map", "values": "string"}}

The "type" which describe the "prop"  has different model.    Is there any way to index the json document？

**Comment by clintongormley** [comment]
no - it needs a different name
