### ISSUE TITLE
action.auto_create_index: true and index.mapper.dynamic: false does not allow automatic index creation

### ISSUE THREAD

**Issue by oldenbur** [elastic/elasticsearch#20618]
**Elasticsearch version**: 2.3.4

**Plugins installed**: []

**JVM version**: 
openjdk version "1.8.0_77"
OpenJDK Runtime Environment (build 1.8.0_77-b03)
OpenJDK 64-Bit Server VM (build 25.77-b03, mixed mode)

**OS version**:
CentOS Linux release 7.2.1511 (Core) 

**Description of the problem including expected versus actual behavior**:
When `action.auto_create_index: true` and `index.mapper.dynamic: false`, new indices are not auto-created when a document is inserted, even in the presence of a template for that index. Only once the index is explicitly created, can a document be inserted into the index.

**Steps to reproduce**:
 1. In the elasticsearch config (elasticsearch.yml) set action.auto_create_index: true and index.mapper.dynamic: false
 2. Add a valid template for an index/type/document that does not yet exist
 3. Attempt to insert a document into the new index and an error like appears:
    `
   {
      "index": {
        "_id": "e2249700-8008-11e6-85f6-74867aea71fe",
        "_index": "logs-2016-09-20",
        "_type": "logs",
        "error": {
          "index": "logs-2016-09-20",
          "reason": "no such index",
          "resource.id": "logs-2016-09-20",
          "resource.type": "index_expression",
          "type": "index_not_found_exception"
        },
        "status": 404
      }
    }
`

**Provide logs (if relevant)**:
```
[2016-09-21 16:52:10,662][WARN ][action.index             ] [lrdx0000] unexpected error during the primary phase for action [indices:data/write/index], request [index {[logs-2016-09-20][logs][00002189-7a23-4518
-86ab-290ba886033a], source[{
  "priority": 0,
  "rootEntityId": 8,
  "vendorMessageId": "4634"
}
]}]
[logs-2016-09-20] IndexNotFoundException[no such index]
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:151)
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:95)
        at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteSingleIndex(IndexNameExpressionResolver.java:208)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:451)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at org.elasticsearch.action.support.replication.TransportReplicationAction.doExecute(TransportReplicationAction.java:131)
        at org.elasticsearch.action.index.TransportIndexAction.innerExecute(TransportIndexAction.java:135)
        at org.elasticsearch.action.index.TransportIndexAction.doExecute(TransportIndexAction.java:119)
        at org.elasticsearch.action.index.TransportIndexAction.doExecute(TransportIndexAction.java:66)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:137)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:85)
        at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
        at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:52)
        at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient.doExecute(BaseRestHandler.java:83)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
        at org.elasticsearch.client.support.AbstractClient.index(AbstractClient.java:371)
        at org.elasticsearch.rest.action.index.RestIndexAction.handleRequest(RestIndexAction.java:102)
        at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:54)
        at org.elasticsearch.rest.RestController.executeHandler(RestController.java:205)
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:166)
        at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:128)
        at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:86)
        at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:449)
        at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:61)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by rjernst** [comment]
Does your template have mappings for the index?

**Comment by oldenbur** [comment]
Here is an abridged version of the template.  I probably should have mentioned that we have disabled _source for this index, also.
```
{
   "logs": {
      "template": "logs*",
      "order": 0,
      "settings": {
         "index": {
            "refresh_interval": "30s"
         },
         "analysis": {
            "analyzer": {
               "default": {
                  "type": "custom",
                  "tokenizer": "keyword",
                  "filter": ["lowercase", "lr_truncate"]
               },
               "lr_url_analyzer": {
                  "type": "pattern",
                  "pattern": "/",
                  "filter": ["url_stop"]
               }
            },
            "filter": {
               "url_stop": {
                  "type": "stop",
                  "stopwords": ["http", "https"]
               },
               "lr_truncate": {
                  "type": "truncate",
                  "length": 32766
               }
            }
         }
      },
      "mappings": {
         "logs": {
            "_source": {
               "enabled": false
            },
            "_all": {
               "enabled": false
            },
            "properties": {
               "priority": {
                  "type": "byte",
                  "store": true
               },
               "rootEntityId": {
                  "type": "integer",
                  "store": true
               },
               "vendorMessageId": {
                  "type": "string",
                  "store": true
               },
               [...]
            }
         }
      }
   }
}
```

**Comment by rjernst** [comment]
I don't think your template is correct. You have an extra object level there with "logs" that the contents of the template is under. This should be at the root.

**Comment by rjernst** [comment]
But also, what led you to believe that `index.mapper.dynamic` has anything to do with the index not existing? Is there another error somewhere?

**Comment by oldenbur** [comment]
Sorry, we strip the outer-most object level that you allude to before PUT-ing the template. (it is an artifact from ESv1.x when the config could include template files) The reason why we believe that `index.mapper.dynamic` is involved is that automatic index creation works when `action.auto_create_index: true` and `index.mapper.dynamic: true` (all other things equal).

The errors that I have already included appeared in the response to the REST index call and the elasticsearch log file, respectively.  Is there another place that I should look for an error message besides those?

**Comment by oldenbur** [comment]
When we attempt to index and the index ***does exist***, but the template ***does not exist***, we get this error in the REST index response:
```
{
   "error": {
      "root_cause": [
         {
            "type": "type_missing_exception",
            "reason": "type[[logs, trying to auto create mapping, but dynamic mapping is disabled]] missing",
            "index": "logs-2016-09-20"
         }
      ],
      "type": "type_missing_exception",
      "reason": "type[[logs, trying to auto create mapping, but dynamic mapping is disabled]] missing",
      "index": "logs-2016-09-20"
   },
   "status": 404
}
```

**Comment by oldenbur** [comment]
Our use case is time-series indexing.  We would like to automatically create a new index each day, but we want the automatic index creation to fail if the template is not present.

**Comment by rjernst** [comment]
It would seem then that your index does not have the mappings you think it does.  That error about type missing means a mapping for the `logs` type does not exist. (and you have dynamic mappings disabled). Try doing a `GET /logs-2016-09-20/_mapping/*` to see which types you actually have in that index.

**Comment by oldenbur** [comment]
I posted that most recent error to show what happens when we intentionally don't provide a template for an existing index.  In other words, it's expected and shows that `index.mapper.dynamic: false` is working when the index already exists.

Our problem is that an index is not automatically created when `action.auto_create_index: true` in this case.

**Comment by rjernst** [comment]
Alright, I dug through the code a little, and it looks like this restriction was added in 2.3.0:  #15381

I'm not sure the check that was added is right, given this use case (index creation, but with a template containing explicit mappings) is valid IMO. I also think the original issue may not be something to worry about in 5.0 given index level settings in node config is no longer allowed.

/cc @clintongormley @jpountz

**Comment by crutch** [comment]
We are also facing exactly the same issues. We have `auto_create_index:true`, `index.mapper.dynamic: false` and a correct template (an index gets correct mapping from template when created manually via PUT).  

After upgrading from 2.1.0 to 2.4.0 we are getting `IndexNotFoundException` all the time, unless we manually create an index.

**Comment by tartale** [comment]
The difficulty with this bug in 2.x is that, due to the switchover from automatic template reading (from the file system) to requiring an API call to update templates, this use case becomes really important.  If somehow, a template gets removed via an API call, programs that index data would need to know.

Setting `auto_create_index:true` and `index.mapper.dynamic:false` would be an easy way to enable a service to detect if a custom template was somehow removed (if it worked correctly).

**Comment by clintongormley** [comment]
This is a known issue but we have decided not to fix it because (a) `index.*` settings may no longer be set in the config file in 5.0 and (b) there is a different solution.

Instead of setting `index.mapper.dynamic: false` in the config file, set it in the template instead.  This will prevent adding new types that are not defined in the template.  If you want it to apply to all indices by default, then create a template which matches `*` and include the setting there.
