### ISSUE TITLE
Updating X-pack License in 5.0.0-alpha5

### ISSUE THREAD

**Issue by imw** [elastic/elasticsearch#20646]
I can't seem to update the license. Not sure if I am doing something wrong, but at this point it is beginning to seem like a bug:
`root@esdata0:/usr/share/elasticsearch/bin/x-pack# curl -u infegy esdata0:9200Enter host password for user 'infegy':
{
  "name" : "data0",
  "cluster_name" : "atlantis",
  "version" : {
    "number" : "5.0.0-alpha5",
    "build_hash" : "d327dd4",
    "build_date" : "2016-08-04T08:59:39.568Z",
    "build_snapshot" : false,
    "lucene_version" : "6.1.0"
  },
  "tagline" : "You Know, for Search"
}
`

`
root@esdata0:/usr/share/elasticsearch/bin/x-pack# ./users list
admin          : superuser
infegy         : superuser
`

`
root@esdata0:/usr/share/elasticsearch/bin/x-pack# curl -XPUT -u infegy esdata0:9200/_xpack/license -d @/root/basic_license.json
Enter host password for user 'infegy':
curl: (52) Empty reply from server
`
which coincides with:
`
[2016-09-23 20:17:14,401][WARN ][xpack.security.transport.netty4] [data0] caught exception while handling client http traffic, closing connection [id: 0xcc27ef9c, L:/10.17.218.166:9200 - R:/10.17.218.166:37552]
java.lang.UnsupportedOperationException: unsupported message type: DefaultFullHttpResponse (expected: ByteBuf, FileRegion)
	at io.netty.channel.nio.AbstractNioByteChannel.filterOutboundMessage(AbstractNioByteChannel.java:260)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:799)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1291)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:748)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:811)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:824)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:804)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:841)
	at io.netty.handler.codec.MessageAggregator.decode(MessageAggregator.java:222)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:474)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:428)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)
`

**Elasticsearch version**:

**Plugins installed**: []

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by jasontedor** [comment]
Duplicates #19834

**Comment by jasontedor** [comment]
You need to force `curl` to not send the `Expect: Continue` header which you can accomplish with `curl -H Expect: -XPUT -u infegy esdata0:9200/_xpack/license -d @/root/basic_license.json`.

Also, [Elasticsearch 5.0.0-beta1 is available now](https://www.elastic.co/downloads/past-releases/elasticsearch-5-0-0-beta1), you should upgrade, then you don't even have to do this as the bug is already fixed there. :smile:

**Comment by jasontedor** [comment]
Thanks for trying out the pre-release, I've marked you eligible for the [Pioneer Program](https://www.elastic.co/blog/elastic-pioneer-program).

**Comment by imw** [comment]
Super. Thanks very much.
Otherwise, things have been smooth sailing.

**Comment by imw** [comment]
Cluster updated. Issue resolved. :-)
