### ISSUE TITLE
Unable parse yml file with missing space between key & value.

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch#20672]
Elastic 5.0-Beta1

configuration file that breaks.
```yaml
# single node configuration
cluster.name: exceptionless-dev
action.auto_create_index: false
#action.destructive_requires_name: true
discovery.type: local
transport.type:local
http.port: 9200
transport.tcp.port: 9300
bootstrap.memory_lock: true
```

If there is no space `transport.type:local` after the `:` it throws the following error:

```
PS C:\elasticsearch.5.0\bin> .\elasticsearch.bat
Exception in thread "main" SettingsException[Failed to load settings from C:\elasticsearch.5.0\config\elasticsearch.yml]; nested: MarkedYAMLException[while scan
ning a simple key
 in 'reader', line 6, column 1:
    transport.type:local
    ^
could not find expected ':'
 in 'reader', line 7, column 1:
    http.port: 9200
    ^

 at [Source: # single node configuration
cluster.name: exceptionless-dev
action.auto_create_index: false
#action.destructive_requires_name: true
discovery.type: local
transport.type:local
http.port: 9200
transport.tcp.port: 9300
bootstrap.memory_lock: true; line: 5, column: 22]]; nested: ScannerException[while scanning a simple key
 in 'reader', line 6, column 1:
    transport.type:local
    ^
could not find expected ':'
 in 'reader', line 7, column 1:
    http.port: 9200
    ^
];
Likely root cause: while scanning a simple key
 in 'reader', line 6, column 1:
    transport.type:local
    ^
could not find expected ':'
 in 'reader', line 7, column 1:
    http.port: 9200
    ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465)
        at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
        at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
        at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:340)
        at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:52)
        at org.elasticsearch.common.settings.loader.XContentSettingsLoader.serializeObject(XContentSettingsLoader.java:102)
        at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(XContentSettingsLoader.java:72)
        at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(XContentSettingsLoader.java:50)
        at org.elasticsearch.common.settings.loader.YamlSettingsLoader.load(YamlSettingsLoader.java:50)
        at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:935)
        at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Settings.java:924)
        at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:102)
        at org.elasticsearch.bootstrap.Bootstrap.initialEnvironment(Bootstrap.java:207)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:247)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:112)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:103)
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
        at org.elasticsearch.cli.Command.main(Command.java:62)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:73)
Refer to the log for complete error details.
```

I feel like this should be handled better and also have a better error message

**Comment by jasontedor** [comment]
These are the rules of YAML. I don't think we should catch this and try to parse out what the issue might be just to throw a different and maybe wrong error message (the same error arises if you really do not have a colon).
