### ISSUE TITLE
NPE in bin/elasticsearch-plugin script for 5.0.0-beta1

### ISSUE THREAD

**Issue by salyh** [elastic/elasticsearch#20688]
5.0.0-beta1 ``elasticsearch-plugin`` script (at least on mac/unix) quits with a NPE when plugin id is omitted:

``bin/elasticsearch-plugin install`` results in

<pre>
Exception in thread "main" java.lang.NullPointerException
	at java.util.TreeMap.getEntry(TreeMap.java:347)
	at java.util.TreeMap.containsKey(TreeMap.java:232)
	at java.util.TreeSet.contains(TreeSet.java:234)
	at java.util.Collections$UnmodifiableCollection.contains(Collections.java:1032)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:209)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:202)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:190)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
	at org.elasticsearch.cli.Command.main(Command.java:62)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:42)
</pre>

Expected is a descriptive error message like "plugin id is mandatory"

**Comment by jasontedor** [comment]
Already closed by #20660
