### ISSUE TITLE
"java.util.concurrent.RejectedExecutionException: Worker has already been shutdown"

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#20692]
When an Elasticsearch node is shutdown, some Exceptions are thrown, indicating that the node has been shutdown, and that some in-flight processes are failing.

Although this may be normal or benign, it would be good to know the exact reason of this.

```
[2016-09-26 13:59:45,629][INFO ][node                     ] [xxx-elasticsearch-node-1] stopping ...
[2016-09-26 13:59:45,795][WARN ][netty.channel.DefaultChannelPipeline] An exception was thrown by an exception handler.
java.util.concurrent.RejectedExecutionException: Worker has already been shutdown
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.registerTask(AbstractNioSelector.java:120)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.executeInIoThread(AbstractNioWorker.java:72)
        at org.jboss.netty.channel.socket.nio.NioWorker.executeInIoThread(NioWorker.java:36)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.executeInIoThread(AbstractNioWorker.java:56)
        at org.jboss.netty.channel.socket.nio.NioWorker.executeInIoThread(NioWorker.java:36)
        at org.jboss.netty.channel.socket.nio.AbstractNioChannelSink.execute(AbstractNioChannelSink.java:34)
        at org.jboss.netty.channel.DefaultChannelPipeline.execute(DefaultChannelPipeline.java:636)
        at org.jboss.netty.channel.Channels.fireExceptionCaughtLater(Channels.java:496)
        at org.jboss.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:46)
        at org.jboss.netty.channel.DefaultChannelPipeline.notifyHandlerException(DefaultChannelPipeline.java:658)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:577)
        at org.jboss.netty.channel.Channels.write(Channels.java:704)
        at org.jboss.netty.channel.Channels.write(Channels.java:671)
        at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:348)
        at org.elasticsearch.transport.netty.NettyTransportChannel.sendResponse(NettyTransportChannel.java:103)
        at org.elasticsearch.transport.netty.NettyTransportChannel.sendResponse(NettyTransportChannel.java:75)
        at org.elasticsearch.transport.DelegatingTransportChannel.sendResponse(DelegatingTransportChannel.java:58)
        at org.elasticsearch.transport.RequestHandlerRegistry$TransportChannelWrapper.sendResponse(RequestHandlerRegistry.java:134)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:369)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:300)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by mars00772** [comment]
@s1monw 
on es 2.3, I had the same issue, but after restart the node, it could not join the cluster, what should be done to fix this, any suggestions?

**Comment by pjx827480541** [comment]
After running for a while, it will be shutdown, but the process is still there, and it cannot be closed. It has happened several times.

**Comment by LuckyNemo** [comment]
why closed?

**Comment by LuckyNemo** [comment]
today I had the same issue in ES 2.3.2

**Comment by LuckyNemo** [comment]
Anyone can help me？

**Comment by LuckyNemo** [comment]
> is makes sense

？？

**Comment by dadoonet** [comment]
> today I had the same issue in ES 2.3.2

This version is definitely not supported anymore. We are yet at version 7.5.1. 
You should upgrade your cluster.
