### ISSUE TITLE
elasticsearch-plugin list error response

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#20691]
Running the 5.0.0 beta1;

```
# /usr/share/elasticsearch/bin/elasticsearch-plugin list
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [x-pack] is incompatible with Elasticsearch [5.0.0-beta1]. Was designed for version [5.0.0-alpha5]
    at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:108)
    at org.elasticsearch.plugins.ListPluginsCommand.execute(ListPluginsCommand.java:63)
    at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
    at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
    at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
    at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
    at org.elasticsearch.cli.Command.main(Command.java:62)
    at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:42)
```

We shouldn't generate a massive error like this.

Ideally we should just list the plugins and then highlight the incompatibility, like this;

```
# /usr/share/elasticsearch/bin/elasticsearch-plugin list
x-pack@5.0.0-beta1 - INCOMPATIBLE PLUGIN, PLEASE UPGRADE
```

But if not, then just having a plain text response like `Plugin [PLUGINNAME] is incompatible with Elasticsearch [VERSIONNOW]. Was designed for version [VERSIONPAST]` would be great.

This is what KB does after upgrading;

```
# /usr/share/kibana/bin/kibana-plugin list
timelion@5.0.0-alpha5
x-pack@5.0.0-alpha5-SNAPSHOT
```

At this point, I'd still need to upgrade, though it doesn't stacktrace and could have info on the incompatibilities to make things clear.

**Comment by s1monw** [comment]
I agree this feels wrong
