### ISSUE TITLE
Binding to the wildcard of one address family should not prevent binding to addresses in another family

### ISSUE THREAD

**Issue by astralblue** [elastic/elasticsearch#20703]
**Elasticsearch version**: 5.0.0-alpha5 (installed out of the deb repository)

**Plugins installed**: []

**JVM version**: openjdk-8-jre_8u91-b14-3ubuntu1~16.04.1 

**OS version**: Ubuntu 16.04.1 LTS

**Description of the problem including expected versus actual behavior**:

When instructed to wildcard-bind in one address family (say, IPv4), ES requires that the wildcard be the only bind address, and rejects the other addresses even if they belong to another address family (say, IPv6).  This prevents binding to the following combinations:

 * `network.host: ["0.0.0.0", "[::1]"]` – 0.0.0.0 (IPv4 wildcard) rejects ::1 (IPv6 non-wildcard);
 * `network.host: ["127.0.0.1", "[::]"]` – :: (IPv6 wildcard) rejects 127.0.0.1 (IPv4 non-wildcard);
 * `network.host: ["0.0.0.0", "[::]"]` – both 0.0.0.0 and :: (IPv4/IPv6 wildcards) reject each other.

A wildcard bind address should reject other bind addresses **of the same address family only.**

**Steps to reproduce**:
 1. Configure one of the `network.host` directives above into `/etc/elasticsearch/elasticsearch.yml`.
 2. `service elasticsearch start`
 3. Examine `/var/log/elasticsearch/elasticsearch.log`.
  * Expected result: The server starts up successfully.
  * Actual result: The server fails to start up; see the log message below.
 4. `netstat -nap`
  * Expected result: The server has two listening sockets, one for each `network.host` address.
  * Actual result: N/A because the server did not even start up.

**Provide logs (if relevant)**:

```
[2016-09-30 03:11:15,186][ERROR][bootstrap                ] [pqYXWfs] Exception
java.lang.IllegalArgumentException: bind address: {0.0.0.0} is wildcard, but multiple addresses specified: this makes no sense
        at org.elasticsearch.common.network.NetworkService.resolveBindHostAddresses(NetworkService.java:140)
        at org.elasticsearch.transport.TcpTransport.bindServer(TcpTransport.java:569)
        at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:181)
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
        at org.elasticsearch.transport.TransportService.doStart(TransportService.java:177)
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
        at org.elasticsearch.node.Node.start(Node.java:469)
        at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:193)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:257)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:101)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:96)
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
        at org.elasticsearch.cli.Command.main(Command.java:54)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:75)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:68)
```

**Comment by astralblue** [comment]
Looks like https://github.com/elastic/elasticsearch/pull/13954 – support for multiple bind/publish addresses – had this issue.  The `addresses.length > 1` check in addCustomNameResolver() is too aggressive: `addresses` may be a mixture of IPv4 and IPv6 addresses.  Things like `Arrays.asList(addresses).stream().filter((a) -> a.getClass().isInstance(address)).count() > 0` instead would be more suitable.  (Not suggesting this horrendously long Java 8 one-liner as-is; just giving an idea.)

**Comment by clintongormley** [comment]
@jasontedor thoughts?

**Comment by jasontedor** [comment]
@astralblue This is behaving correctly, I think what you're missing is that binding to a wildcard address will bind to all addresses on all families on all interfaces.

My workstation here has two NICs and I've both IPv4 and IPv6 networking configured:

```bash
10:53:32 [jason@totoro:~] $ ifconfig eno1
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.179  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::fa32:e4ff:fe6d:da11  prefixlen 64  scopeid 0x20<link>
        inet6 2605:a000:1230:9b::138a  prefixlen 128  scopeid 0x0<global>
        inet6 2605:a000:1230:9b:fa32:e4ff:fe6d:da11  prefixlen 64  scopeid 0x0<global>
        ether f8:32:e4:6d:da:11  txqueuelen 1000  (Ethernet)
        RX packets 11420967  bytes 5342191880 (4.9 GiB)
        RX errors 0  dropped 8377  overruns 0  frame 0
        TX packets 3291450  bytes 3639292618 (3.3 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xfba00000-fba20000  

10:53:34 [jason@totoro:~] $ ifconfig enp8s0
enp8s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.199  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 2605:a000:1230:9b::2000  prefixlen 128  scopeid 0x0<global>
        inet6 fe80::fa32:e4ff:fe6d:da14  prefixlen 64  scopeid 0x20<link>
        inet6 2605:a000:1230:9b:fa32:e4ff:fe6d:da14  prefixlen 64  scopeid 0x0<global>
        ether f8:32:e4:6d:da:14  txqueuelen 1000  (Ethernet)
        RX packets 9182866  bytes 3140840088 (2.9 GiB)
        RX errors 0  dropped 8575  overruns 0  frame 0
        TX packets 100059  bytes 10220175 (9.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device memory 0xfb600000-fb61ffff  

10:53:40 [jason@totoro:~] $ 
```

Starting Elasticsearch:

```
10:55:29 [jason@totoro:~] 1 $ ES_JAVA_OPTS="-Xms2g -Xmx2g" ~/elasticsearch/elasticsearch-5.0.0-alpha5-SNAPSHOT/bin/elasticsearch -E network.host=0.0.0.0 -E discovery.zen.minimum_master_nodes=1
[2016-10-08 10:55:45,529][INFO ][node                     ] [] initializing ...
[2016-10-08 10:55:45,599][INFO ][env                      ] [vIkTAeg] using [1] data paths, mounts [[/home (/dev/mapper/fedora-home)]], net usable_space [276.3gb], net total_space [388.4gb], spins? [no], types [ext4]
[2016-10-08 10:55:45,599][INFO ][env                      ] [vIkTAeg] heap size [1.9gb], compressed ordinary object pointers [true]
[2016-10-08 10:55:45,600][INFO ][node                     ] [vIkTAeg] node name [vIkTAeg] derived from node ID; set [node.name] to override
[2016-10-08 10:55:45,603][INFO ][node                     ] [vIkTAeg] version[5.0.0-alpha5-SNAPSHOT], pid[15235], build[d327dd4/2016-10-08T14:52:09.844Z], OS[Linux/4.5.7-202.fc23.x86_64/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_102/25.102-b14]
[2016-10-08 10:55:46,188][INFO ][io.netty.util.internal.PlatformDependent] Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
[2016-10-08 10:55:46,237][INFO ][plugins                  ] [vIkTAeg] loaded module [aggs-matrix-stats]
[2016-10-08 10:55:46,237][INFO ][plugins                  ] [vIkTAeg] loaded module [ingest-common]
[2016-10-08 10:55:46,237][INFO ][plugins                  ] [vIkTAeg] loaded module [lang-expression]
[2016-10-08 10:55:46,238][INFO ][plugins                  ] [vIkTAeg] loaded module [lang-groovy]
[2016-10-08 10:55:46,238][INFO ][plugins                  ] [vIkTAeg] loaded module [lang-mustache]
[2016-10-08 10:55:46,238][INFO ][plugins                  ] [vIkTAeg] loaded module [lang-painless]
[2016-10-08 10:55:46,238][INFO ][plugins                  ] [vIkTAeg] loaded module [percolator]
[2016-10-08 10:55:46,238][INFO ][plugins                  ] [vIkTAeg] loaded module [reindex]
[2016-10-08 10:55:46,238][INFO ][plugins                  ] [vIkTAeg] loaded module [transport-netty3]
[2016-10-08 10:55:46,238][INFO ][plugins                  ] [vIkTAeg] loaded module [transport-netty4]
[2016-10-08 10:55:46,238][INFO ][plugins                  ] [vIkTAeg] no plugins loaded
[2016-10-08 10:55:47,557][INFO ][node                     ] [vIkTAeg] initialized
[2016-10-08 10:55:47,557][INFO ][node                     ] [vIkTAeg] starting ...
[2016-10-08 10:55:47,634][INFO ][transport                ] [vIkTAeg] publish_address {192.168.1.179:9300}, bound_addresses {[::]:9300}
[2016-10-08 10:55:47,637][INFO ][bootstrap                ] [vIkTAeg] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2016-10-08 10:55:50,728][INFO ][cluster.service          ] [vIkTAeg] new_master {vIkTAeg}{vIkTAegzQi-nLDaoYkIRUA}{cNv31YMERh2A4GGjbym6Lw}{192.168.1.179}{192.168.1.179:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2016-10-08 10:55:50,752][INFO ][http                     ] [vIkTAeg] publish_address {192.168.1.179:9200}, bound_addresses {[::]:9200}
[2016-10-08 10:55:50,753][INFO ][node                     ] [vIkTAeg] started
[2016-10-08 10:55:50,764][INFO ][gateway                  ] [vIkTAeg] recovered [0] indices into cluster_state
```

Note the bound address is `[::]`, representing the wildcard binding.

Checking `netstat`:

```
10:59:40 [jason@totoro:~] $ netstat -an | grep "\(9200\|9300\)"
tcp6       0      0 :::9200                 :::*                    LISTEN     
tcp6       0      0 :::9300                 :::*                    LISTEN 
```

And then:

```
10:56:08 [jason@totoro:~] $ curl -XGET localhost:9200/                                                                                                                                                          [13/471]
{
  "name" : "vIkTAeg",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "5.0.0-alpha5",
    "build_hash" : "d327dd4",
    "build_date" : "2016-10-08T14:52:09.844Z",
    "build_snapshot" : true,
    "lucene_version" : "6.1.0"
  },
  "tagline" : "You Know, for Search"
}
10:56:13 [jason@totoro:~] $ curl -g -6 -XGET "http://[::1]:9200/"                                                                                                                                                       
{
  "name" : "vIkTAeg",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "5.0.0-alpha5",
    "build_hash" : "d327dd4",
    "build_date" : "2016-10-08T14:52:09.844Z",
    "build_snapshot" : true,
    "lucene_version" : "6.1.0"
  },
  "tagline" : "You Know, for Search"
}
10:56:32 [jason@totoro:~] $ curl -XGET 192.168.1.179:9200/                                                                                                                                                              
{
  "name" : "vIkTAeg",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "5.0.0-alpha5",
    "build_hash" : "d327dd4",
    "build_date" : "2016-10-08T14:52:09.844Z",
    "build_snapshot" : true,
    "lucene_version" : "6.1.0"
  },
  "tagline" : "You Know, for Search"
}
10:56:47 [jason@totoro:~] $ curl -XGET 192.168.1.199:9200/                                                                                                                                                              
{
  "name" : "vIkTAeg",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "5.0.0-alpha5",
    "build_hash" : "d327dd4",
    "build_date" : "2016-10-08T14:52:09.844Z",
    "build_snapshot" : true,
    "lucene_version" : "6.1.0"
  },
  "tagline" : "You Know, for Search"
}
10:56:55 [jason@totoro:~] $ curl -g -6 "http://[2605:a000:1230:9b::138a]:9200/"
{
  "name" : "vIkTAeg",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "5.0.0-alpha5",
    "build_hash" : "d327dd4",
    "build_date" : "2016-10-08T14:52:09.844Z",
    "build_snapshot" : true,
    "lucene_version" : "6.1.0"
  },
  "tagline" : "You Know, for Search"
}
10:58:56 [jason@totoro:~] $ curl -g -6 "http://[2605:a000:1230:9b::2000]:9200/"
{
  "name" : "vIkTAeg",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "5.0.0-alpha5",
    "build_hash" : "d327dd4",
    "build_date" : "2016-10-08T14:52:09.844Z",
    "build_snapshot" : true,
    "lucene_version" : "6.1.0"
  },
  "tagline" : "You Know, for Search"
}
```

So we are able to reach this node over HTTP on all addresses on all interfaces (loopback and the two physical NICs).

**Comment by jasontedor** [comment]
I should also mention that exactly the same behavior occurs if you bind to `[::]` as well.

**Comment by astralblue** [comment]
Jason, your explanation that “binding to a wildcard address will bind to all addresses on all families on all interfaces” is true only if:

 1. The wildcard address is IPv6; and
 2. IPv4-mapped addressing is enabled on the listening socket, i.e. with IPV6_V6ONLY sockopt turned off.

On systems that disable IPv4-mapped addressing, e.g. [on FreeBSD where net.inet6.ip6.v6only=1 by default](https://svnweb.freebsd.org/base/head/sys/netinet6/in6_proto.c?revision=100676&view=markup) for security reasons, listening sockets bound to the IPv6 wildcard will answer only IPv6 connections, and refuse IPv4 connections.

**Comment by astralblue** [comment]
I believe that your test setup has v6only turned off by default (```cat /proc/sys/net/ipv6/bindv6only``` to confirm); if that is the case, curl-ing to an IPv4 address on your system would work as you demonstrated.  My point, however, is that the IPv4-mapped addressing behavior is dependent on system setting, so it would be better not to bank on universal availability of IPv4-mapped addressing, especially when there is an API knob to fine-tune the aspect.  At the very least, the documentation should mention this as a system configuration caveat.

**Comment by jasontedor** [comment]
> your explanation that “binding to a wildcard address will bind to all addresses on all families on all interfaces” is true only if:

> 1. The wildcard address is IPv6; and
> 2. IPv4-mapped addressing is enabled on the listening socket, i.e. with IPV6_V6ONLY sockopt turned off.

This is correct, but not the salient point. The JVM will convert `INADDR_ANY` to `IN6ADDR_ANY_INIT` immediately before binding assuming that IPv6 is available. This can be disabled with `-Djava.net.preferIPv4Stack=true`.

> I believe that your test setup has v6only turned off by default (`cat /proc/sys/net/ipv6/bindv6only` to confirm); if that is the case, curl-ing to an IPv4 address on your system would work as you demonstrated.

This is not correct. 

```
16:44:16 2d [jason@totoro:~] $ cat /proc/sys/net/ipv6/bindv6only
1
16:44:20 2d [jason@totoro:~] $ ~/elasticsearch/elasticsearch-6.0.0-alpha1-SNAPSHOT/bin/elasticsearch -d 
16:44:25 2d [jason@totoro:~] $ curl -XGET localhost:9200/
{
  "name" : "iNb62JJ",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "0AxnrBz1T8GQkIct_CtB0g",
  "version" : {
    "number" : "6.0.0-alpha1",
    "build_hash" : "96aa5e3",
    "build_date" : "2016-10-17T17:46:41.420Z",
    "build_snapshot" : true,
    "lucene_version" : "6.2.0"
  },
  "tagline" : "You Know, for Search"
}
16:44:35 2d [jason@totoro:~] $ curl -g -6 "http://[::1]:9200/"
{
  "name" : "iNb62JJ",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "0AxnrBz1T8GQkIct_CtB0g",
  "version" : {
    "number" : "6.0.0-alpha1",
    "build_hash" : "96aa5e3",
    "build_date" : "2016-10-17T17:46:41.420Z",
    "build_snapshot" : true,
    "lucene_version" : "6.2.0"
  },
  "tagline" : "You Know, for Search"
}
```

The default value of `IPV6_V6ONLY` is the value of `/proc/sys/net/ipv6/bindv6only`, but the JVM unconditionally sets `IPV6_V6ONLY` (via `setsockopt`) if the IPv6 stack is enabled.

These above two points are why binding to `INADDR_ANY` within the JVM on a system that is IPv6 capable will bind to both IPv4 and IPv6 interfaces.

**Comment by stochastic-thread** [comment]
This is a pretty rude error message
