### ISSUE TITLE
Beta: Setting network.host: or network.bind_host: fail to function

### ISSUE THREAD

**Issue by DigiAngel** [elastic/elasticsearch#20723]
**Elasticsearch version**:  version[5.0.0-beta1], pid[361], build[7eb6260/2016-09-20T23:10:37.942Z]

**Plugins installed**: None

**JVM version**: 8

**OS version**: Ubuntu 16.04

**Description of the problem including expected versus actual behavior**:  Fails to start with network.host_global_:, fails to open port with network.host: or network.bind_host: set. 

**Steps to reproduce**:
 1. Set network.host:_global or
 2. Set network.host_bind: anything
 3.

**Provide logs (if relevant)**:
When setting to "_ global _": <- changed because github, there is no space with the _'s
~~~
[2016-10-03T10:37:49,363][ERROR][o.e.b.Bootstrap          ] [scanner] Exception
java.lang.IllegalArgumentException: No up-and-running global-scope (public) addresses found, got [name:lo (lo), name:eth0 (eth0)]
        at org.elasticsearch.common.network.NetworkUtils.getGlobalAddresses(NetworkUtils.java:207) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.common.network.NetworkService.resolveInternal(NetworkService.java:252) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.common.network.NetworkService.resolveInetAddresses(NetworkService.java:220) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.common.network.NetworkService.resolveBindHostAddresses(NetworkService.java:130) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.transport.TcpTransport.bindServer(TcpTransport.java:575) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:182) ~[?:?]
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.transport.TransportService.doStart(TransportService.java:182) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.node.Node.start(Node.java:506) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:211) ~[elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:288) [elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:112) [elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:103) [elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) [elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) [elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.cli.Command.main(Command.java:62) [elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) [elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:73) [elasticsearch-5.0.0-beta1.jar:5.0.0-beta1]
~~~

When setting "network.host: ["192.168.1.8", "127.0.0.1"]":
~~~
[2016-10-03T10:44:05,977][INFO ][o.e.t.TransportService   ] [scanner] publish_address {192.168.1.8:9300}, bound_addresses {192.168.1.8:9300}, {127.0.0.1:9300}
[2016-10-03T10:44:06,030][INFO ][o.e.b.BootstrapCheck     ] [scanner] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2016-10-03T10:44:06,034][ERROR][o.e.b.Bootstrap          ] [scanner] node validation exception
bootstrap checks failed
~~~

When setting "network.bind_host: ["_eth0:ipv4_", "_local_"]": <- these include _'s not shown
~~~
[2016-10-03T10:53:25,197][INFO ][o.e.t.TransportService   ] [scanner] publish_address {127.0.0.1:9300}, bound_addresses {192.168.1.8:9300}, {[::1]:9300}, {127.0.0.1:9300}
[2016-10-03T10:53:25,213][INFO ][o.e.b.BootstrapCheck     ] [scanner] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2016-10-03T10:53:25,219][ERROR][o.e.b.Bootstrap          ] [scanner] node validation exception
bootstrap checks failed
~~~

Currently I can only get the beta to listen to localhost, and only if I comment out the network.host: or network.bind_host: directives.

**Comment by jasontedor** [comment]
> bootstrap checks failed

You have failing [bootstrap checks](https://www.elastic.co/guide/en/elasticsearch/reference/master/bootstrap-checks.html), that's why you're running into issues. You need to read the checks that failed and adjust your installation accordingly.

**Comment by DigiAngel** [comment]
I do not get bootstrap check errors when I comment out either of the network directives:
~~~
[2016-10-03T11:01:36,049][INFO ][o.e.n.Node               ] [scanner] initialized
[2016-10-03T11:01:36,049][INFO ][o.e.n.Node               ] [scanner] starting ...
[2016-10-03T11:01:38,534][INFO ][o.e.t.TransportService   ] [scanner] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2016-10-03T11:01:38,600][WARN ][o.e.b.BootstrapCheck     ] [scanner] memory locking requested for elasticsearch process but memory is not locked
[2016-10-03T11:01:38,600][WARN ][o.e.b.BootstrapCheck     ] [scanner] max virtual memory areas vm.max_map_count [65530] likely too low, increase to at least [262144]
[2016-10-03T11:01:52,910][WARN ][o.e.m.j.JvmGcMonitorService] [scanner] [gc][young][4][4] duration [13.5s], collections [1]/[13.8s], total [13.5s]/[31.3s], memory [129mb]->[67mb]/[1.9gb], all_pools {[young] [102.4mb]->[16.6mb]/[133.1mb]}{[survivor] [16.6mb]->[15.6mb]/[16.6mb]}{[old] [9.9mb]->[35.4mb]/[1.8gb]}
[2016-10-03T11:01:52,916][WARN ][o.e.m.j.JvmGcMonitorService] [scanner] [gc][4] overhead, spent [13.5s] collecting in the last [13.8s]
[2016-10-03T11:01:54,568][INFO ][o.e.c.s.ClusterService   ] [scanner] new_master {scanner}{-_ADS4ViShCeOSWUW-jYDw}{dPWw4Q17Qp68NnFuoV7p5w}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2016-10-03T11:01:54,736][INFO ][o.e.h.HttpServer         ] [scanner] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
[2016-10-03T11:01:54,737][INFO ][o.e.n.Node               ] [scanner] started

**Comment by jasontedor** [comment]
Yes, you do. From your logs:

```
[2016-10-03T11:01:38,600][WARN ][o.e.b.BootstrapCheck     ] [scanner] memory locking requested for elasticsearch process but memory is not locked
[2016-10-03T11:01:38,600][WARN ][o.e.b.BootstrapCheck     ] [scanner] max virtual memory areas vm.max_map_count [65530] likely too low, increase to at least [262144]
```

They are just not enforced when you are only bound or publishing to localhost. This is in the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/bootstrap-checks.html) that I linked to.

You must address these issues.

**Comment by DigiAngel** [comment]
Ok cool...I'm on that now thank you.

**Comment by cyrilcyril70** [comment]
Worked on my AWS Linux Machine

cluster.name: myES_Cluster
node.name: ESNODE_CYR
node.master: true
node.data: true
transport.host: localhost
transport.tcp.port: 9300
http.port: 9200
network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 2

I have tried with this on the elasticsearch.yml (key:value) and worked fine for me. But it takes 2 days to fix it :wink: :slight_smile: , going on with ES Doc is so tough.
