### ISSUE TITLE
Ubuntu 16.04 elasticsearch fails to start when datadir is on iscsi volume

### ISSUE THREAD

**Issue by rdica** [elastic/elasticsearch#20792]
**Elasticsearch version**:
Package: elasticsearch
Version: 2.4.1
License: unknown
Vendor: none
Architecture: all
Maintainer: Elasticsearch Team <info@elastic.co>
Installed-Size: 29847
Depends: libc6, adduser
Section: web
Priority: optional
Homepage: https://www.elastic.co/
Filename: pool/e/el/elasticsearch-2.4.1.deb
Size: 27252092
SHA1: 575a7ee8cb62f6b96fde9dc465b3c4fe0565fb07
SHA256: cdf94b84cbf3024961cd09a689957fe39df6da9afcfe76ceba20dbfb50b92945
MD5sum: eecf5e7dee765777c5c224747a90a750
Description: Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html
Description-md5: 7a174b4a3b09460a7e934d813a44dbc0

**Plugins installed**: []

**JVM version**:
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

**OS version**:
Ubuntu 16.04.1 LTS Server

**Description of the problem including expected versus actual behavior**:
Data directory resides on ISCSI backed volume. The volume is not yet available when elasticsearch is started. Start fails:

[2016-10-06 14:04:38,197][INFO ][node                     ] [str002] stopping ...
[2016-10-06 14:04:44,933][INFO ][node                     ] [str002] stopped
[2016-10-06 14:04:44,934][INFO ][node                     ] [str002] closing ...
[2016-10-06 14:04:44,952][INFO ][node                     ] [str002] closed
[2016-10-06 14:14:49,187][ERROR][bootstrap                ] Exception
java.lang.IllegalStateException: Unable to access 'path.data' (/data/elasticsearch/elasticsearch)
	at org.elasticsearch.bootstrap.Security.addPath(Security.java:316)
	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:259)
	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:212)
	at org.elasticsearch.bootstrap.Security.configure(Security.java:118)
	at org.elasticsearch.bootstrap.Bootstrap.setupSecurity(Bootstrap.java:212)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:183)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.nio.file.AccessDeniedException: /data/elasticsearch/elasticsearch
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:337)
	at org.elasticsearch.bootstrap.Security.addPath(Security.java:314)
	... 7 more

Once boot has been completed, I log in, then run systemctl restart elasticsearch, and the service starts successfully.

**Steps to reproduce**:
 1. Reboot server.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
I'm not sure what you're expecting here; the data directory is not available is not an Elasticsearch issue.

**Comment by rdica** [comment]
Maintainer: Elasticsearch Team info@elastic.co

Did I misunderstand something, is this team not the pkg maintainer?

**Comment by jasontedor** [comment]
> Did I misunderstand something, is this team not the pkg maintainer?

Yes, we are the maintainers but again the issue here is not an Elasticsearch issue. If your data directory is not available we are not going to start.

**Comment by clintongormley** [comment]
@rdica you'll need to adjust the systemd file to wait for the iscsi service to start.  That said, we really don't recommend using non-local disks with Elasticsearch
