### ISSUE TITLE
ElasticSearch 2.4.1 with TestNG problem

### ISSUE THREAD

**Issue by frank-montyne** [elastic/elasticsearch#20848]
**2.4.1**:

**Plugins installed**: []

**1.8.0_74**:

**OSX 10.11.6**:

**When doing a clean install on the attached maven project I get a NoClassDefFoundError error when the test is run. When the ElasticSearch version is changed to 2.3.5 everything works as expected**

java.lang.NoClassDefFoundError: org/apache/lucene/rangetree/RangeTreeDocValuesConsumer
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:72)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:51)
	at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:38)
	at org.apache.lucene.codecs.DocValuesFormat$Holder.<clinit>(DocValuesFormat.java:48)
	at org.apache.lucene.codecs.DocValuesFormat.forName(DocValuesFormat.java:108)
	at org.elasticsearch.common.lucene.Lucene.<clinit>(Lucene.java:67)
	at org.elasticsearch.Version.<clinit>(Version.java:316)
	at com.bynubian.elasticsearch.ConnectTest.testConnect(ConnectTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.rangetree.RangeTreeDocValuesConsumer
	at java.net.URLClassLoader$1.run(URLClassLoader.java:370)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Caused by: java.io.EOFException: Detect premature EOF
	at sun.misc.Resource.getBytes(Resource.java:131)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:462)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	... 45 more:

The very weird thing is when you run the supplied main in the connect class everything works as expected in both ElasticSearch versions. All help is greatly appreciated!

[bynubian-es-bug.zip](https://github.com/elastic/elasticsearch/files/520487/bynubian-es-bug.zip)

**Steps to reproduce**:
 1. Do a clean install on the maven project
 2. Change the ElasticSearch version to 2.3.5
 3.  Do a clean install on the maven project again

**Comment by jasontedor** [comment]
I think that you have an issue on your end:

```
Caused by: java.io.EOFException: Detect premature EOF
at sun.misc.Resource.getBytes(Resource.java:131)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:462)
at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
... 45 more:
```

Please ask additional for general help on the [Elastic Discourse forum](https://discuss.elastic.co); Elastic reserves GitHub for verified bug reports and feature requests.
