### ISSUE TITLE
SNAPSHOT is partial with exception BufferedChecksumIndexInput - Using NFS method

### ISSUE THREAD

**Issue by afsafs** [elastic/elasticsearch#20928]
```
{"snapshot":{"snapshot":"20161013-211236","version_id":2040099,"version":"2.4.0","indices”:[“X1”,”X2”,”X3”,”.kibana"],"state":"PARTIAL","start_time":"2016-10-14T02:12:36.674Z","start_time_in_millis":1476411156674,"end_time":"2016-10-14T02:12:42.381Z","end_time_in_millis":1476411162381,"duration_in_millis":5707,"failures":[{"index”:”X1”,”shard_id":2,"reason":"IndexShardSnapshotFailedException[class org.apache.lucene.store.BufferedChecksumIndexInput cannot seek backwards (pos=-16 getFilePointer()=0)]; nested: IllegalStateException[class org.apache.lucene.store.BufferedChecksumIndexInput cannot seek backwards (pos=-16 getFilePointer()=0)]; ","node_id":"fokdpU00SuexZG1J3dPqrw","status":"INTERNAL_SERVER_ERROR"},{"index”:”X1”,”shard_id":0,"reason":"IndexShardSnapshotFailedException[class org.apache.lucene.store.BufferedChecksumIndexInput cannot seek backwards (pos=-16 getFilePointer()=0)]; nested: IllegalStateException[class org.apache.lucene.store.BufferedChecksumIndexInput cannot seek backwards (pos=-16 getFilePointer()=0)]; ","node_id":"fokdpU00SuexZG1J3dPqrw","status":"INTERNAL_SERVER_ERROR"}],"shards":{"total":16,"failed":2,"successful":14}}}
```

**Comment by s1monw** [comment]
can you check if you see a stacktrace in the log files? this info doesn't get us anywhere.

**Comment by afsafs** [comment]
1) Issue - This snapshot was created using 2.3.1 and is being read with 2.4
2) When I try to create a snapshot with NFS, I get the same error

[2016-10-13 18:50:20,479][WARN ][rest.suppressed          ] path: /_snapshot/backup/_all, params: {repository=backup, snapshot=_all}
SnapshotException[[backup:20161013-175233] Snapshot could not be read]; nested: IllegalStateException[class org.apache.lucene.store.BufferedChecksumIndexInput cannot seek backwards (pos=-16 getFilePointer()=0)];
        at org.elasticsearch.snapshots.SnapshotsService.snapshots(SnapshotsService.java:154)
        at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:80)
        at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:49)
        at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:98)
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$3.doRun(TransportMasterNodeAction.java:185)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: class org.apache.lucene.store.BufferedChecksumIndexInput cannot seek backwards (pos=-16 getFilePointer()=0)
        at org.apache.lucene.store.ChecksumIndexInput.seek(ChecksumIndexInput.java:50)
        at org.apache.lucene.codecs.CodecUtil.checksumEntireFile(CodecUtil.java:450)
        at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.readBlob(ChecksumBlobStoreFormat.java:97)
        at org.elasticsearch.repositories.blobstore.BlobStoreFormat.read(BlobStoreFormat.java:83)
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.readSnapshot(BlobStoreRepository.java:439)
        at org.elasticsearch.snapshots.SnapshotsService.snapshots(SnapshotsService.java:149)
        ... 8 more

**Comment by colings86** [comment]
@afsafs are you still seeing this issue? If so please provide as much detail about the issue and environment as you can and reopen
