### ISSUE TITLE
java process failing to connect to Elastic search after a fresh installation of ES

### ISSUE THREAD

**Issue by chaitu0292** [elastic/elasticsearch#20922]
My scenario: My java process runs continuously(while(1)) on ES.
when a fresh installation of ES is done it fails to connect to ES.Throwing below error.
when i restart my service its working fine.
This occur only during fresh installation of ES. Its working fine when ES going up and down.

2016-10-13 06:44:39 WARN Failed to create ES client: Failed to create a selector.
2016-10-13 06:45:09 WARN network:48 - unable to gather network information
java.net.SocketException: Too many open files
at java.net.NetworkInterface.getAll(Native Method)
at java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:343)
at org.elasticsearch.common.network.NetworkUtils.getInterfaces(NetworkUtils.java:127)
at org.elasticsearch.common.network.IfConfig.doLogging(IfConfig.java:56)
at org.elasticsearch.common.network.IfConfig.logIfNecessary(IfConfig.java:46)
at org.elasticsearch.common.network.NetworkService.(NetworkService.java:86)
at sun.reflect.GeneratedConstructorAccessor6.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:50)
at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:104)
at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:886)
at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:46)
at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:201)
at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:879)
at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96)
at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:46)
at org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:160)

**Comment by jasontedor** [comment]
> `java.net.SocketException: Too many open files`

Check your file limits, and make sure that you're not leaving connections open.
