### ISSUE TITLE
CI: RandomQueryBuilder.createQuery() can lead to NPE when used from test that doesn't subclass AbstractQueryTestCase

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#20968]
This turned up on a PR jenkins run:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+multijob-intake/407/console

```
Suite: org.elasticsearch.search.internal.ShardSearchTransportRequestTests
  2> REPRODUCE WITH: gradle :core:test -Dtests.seed=614FA6D7679FB0D4 -Dtests.class=org.elasticsearch.search.internal.ShardSearchTransportRequestTests -Dtests.method="testSerialization" -Dtests.security.manager=true -Dtests.locale=ar-MA -Dtests.timezone=US/Michigan
ERROR   0.03s J0 | ShardSearchTransportRequestTests.testSerialization <<< FAILURES!
   > Throwable #1: java.lang.NullPointerException
   > 	at __randomizedtesting.SeedInfo.seed([614FA6D7679FB0D4:3597C79F40CD8D48]:0)
   > 	at org.elasticsearch.index.query.IdsQueryBuilderTests.doCreateTestQueryBuilder(IdsQueryBuilderTests.java:50)
   > 	at org.elasticsearch.index.query.IdsQueryBuilderTests.doCreateTestQueryBuilder(IdsQueryBuilderTests.java:37)
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+multijob-intake/core/build/testrun/test/J0/temp/org.elasticsearch.search.internal.ShardSearchTransportRequestTests_614FA6D7679FB0D4-001
  2> NOTE: test params are: codec=Asserting(Lucene62), sim=RandomSimilarity(queryNorm=true,coord=yes): {}, locale=ar-MA, timezone=US/Michigan
  2> NOTE: Linux 3.12.60-52.54-default amd64/Oracle Corporation 1.8.0_101 (64-bit)/cpus=4,threads=1,free=355198832,total=520617984
  2> NOTE: All tests run in this JVM: [BinaryRangeAggregatorTests, ThreadPoolTests, ScaledFloatFieldMapperTests, NestedAggregatorTests, GenericStoreDynamicTemplateTests, StatsBucketTests, IndexTests, CompoundAnalysisTests, NetworkAddressTests, DateMathExpressionResolverTests, ScoreFunctionBuilderTests, SecurityTests, IndicesShardStoreResponseTests, LegacyDoubleFieldTypeTests, ClusterStateToStringTests, MetaDataMappingServiceTests, CJKFilterFactoryTests, StartRecoveryRequestTests, PipelineFactoryTests, TranslogTests, MaxTests, ShardSearchTransportRequestTests]
   > 	at org.elasticsearch.test.AbstractQueryTestCase.createTestQueryBuilder(AbstractQueryTestCase.java:234)
   > 	at org.elasticsearch.index.query.RandomQueryBuilder.createQuery(RandomQueryBuilder.java:47)
   > 	at org.elasticsearch.search.internal.ShardSearchTransportRequestTests.createShardSearchTransportRequest(ShardSearchTransportRequestTests.java:101)
   > 	at org.elasticsearch.search.internal.ShardSearchTransportRequestTests.testSerialization(ShardSearchTransportRequestTests.java:69)
   > 	at java.lang.Thread.run(Thread.java:745)
```

The reason seems to be that ShardSearchTransportRequestTests recently started using randomly created queries from RandomQueryBuilder. This delegates to instances of individual query builder tests, which in turn uses some static members of AbstractQueryTestCase that might not have been initialized by the static @BeforeClass that is usually called by junit.

**Comment by cbuescher** [comment]
Seems to be fixed by 5137f44bd66bdd92b8e99310eefa6b3fd935cc9b on master already.
