### ISSUE TITLE
can't start Elastic Search due to translog missing "NoSuchFileException"

### ISSUE THREAD

**Issue by superhero** [elastic/elasticsearch#21038]
**Elasticsearch version**:
**JVM version**:
**OS version**:
using docker latest, so current version is 2.4.1

**Plugins installed**: []
no plugins

**Description of the problem including expected versus actual behavior**:
**Provide logs (if relevant)**:
**Steps to reproduce**:
When restarting the container, I get the following error 5 times for each index, different files and different folders but all are translogs:

```
java.nio.file.NoSuchFileException: /usr/share/elasticsearch/data/elasticsearch/nodes/0/indices/log/1/translog/translog-8011864828733919272.tlog
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
    at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
    at java.nio.file.Files.delete(Files.java:1126)
    at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:324)
    at org.elasticsearch.index.translog.Translog.<init>(Translog.java:166)
    at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:209)
    at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:152)
    at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
    at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1408)
    at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1403)
    at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:906)
    at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:883)
    at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:245)
    at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
    at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[2016-10-20 09:40:27,880][WARN ][index.translog           ] [Crimson and the Raven] [log][4] failed to delete temp file /usr/share/elasticsearch/data/elasticsearch/nodes/0/indices/log/4/translog/translog-2986338167181911992.tlog
```

The folder `/usr/share/elasticsearch/data/elasticsearch/nodes/0/indices/log/1/translog` contains `translog-165.ckp`, `translog-165.tlog`, `translog-166.tlog` and `translog.ckp`

**Comment by superhero** [comment]
There was more then one bug on the server, Elastic Search worked just fine even though the log is showing these exceptions..

**Comment by dnhatn** [comment]
Closing this because there has been no update (or similar reports) on this issue. Moreover, we have improved the resiliency of translog a lot recently.
