### ISSUE TITLE
UnsupportedClassVersionError: ... Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by JazzFan** [elastic/elasticsearch#21102]
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/bootstrap/Elasticsearch : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Elasticsearch version**:  5.0.0-alpha1/2/beta1 (5.0RC1)

**Plugins installed**: [] none

**JVM version**: 

**OS version**: Ubuntu 12.04 (wheezy/sid)
Linux 3.2.0-69-virtual #103-Ubuntu SMP Tue Sep 2 05:21:29 UTC 2014

**Description of the problem including expected versus actual behavior**:
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/bootstrap/Elasticsearch : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Steps to reproduce**:
 1. run bin/elasticsearch
 2. wait a minute

**Comment by jasontedor** [comment]
You need a Java 8 runtime.

**Comment by mtaylor769** [comment]
I am getting this error even after installing JRE8.

**Comment by nik9000** [comment]
If you see this error elasticsearch isnt running with Java 8.

**Comment by mtaylor769** [comment]
I JUST intstalled Java 8. Your comment is invalid.

**Comment by mtaylor769** [comment]
So, the issue is not _THAT_ the JRE8 is installed, it's **HOW** it get's installed. On the Oracle Developer Downloads page, there are two options for OSX: '.dmg', and '.tar.gz'. I had used the .dmg to install and was getting this error. 

Unlike the flippant "you need Java 8" comments that are ever-so-helpful, especially after confirming my JRE8u111 with [Installed Java Checker](https://java.com/en/download/installed.jsp)  - I found an article that actually explains why installing using the .dmg is problematic and how to properly install using the .tar.gz file and adding it to the System Library in El Capitan:

[Oracle’s JRE 8 on Mac OS X El Capitan](https://oliverdowling.com.au/2015/10/09/oracles-jre-8-on-mac-os-x-el-capitan/)

In the future, only comment if you have something more helpful to add, otherwise, STFU and keep it to yourself.

**Comment by s1monw** [comment]
> In the future, only comment if you have something more helpful to add, otherwise, STFU and keep it to yourself.

@mtaylor769 if you come to an open source project with statements like this nobody wants to help you anymore if you have a serious issue. The issues are happening on your side of the communication and since you just confessed that the problem was _in front of the keyboard_ this time I think it would be more appropriate to say _thank you and sorry for the time you spend helping me_. I know that won't happen but I at least try to manage expectations next time.

**Comment by mtaylor769** [comment]
@s1monw I'm not going to say  "sorry and thank you" for someone wasting my time, as you felt the need to do the same with your response. Message boards are a last resort for me since I've been programming since before your you were a gleam in your father's eye, so flippant answers, and lectures about my tone are the last things I'm looking for when I'm asking for help, Junior.

**Comment by Tomket** [comment]
I got the followings.

C:\elasticsearch-5.2.0\bin>elasticsearch.bat
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/bootstrap/Elasticsearch : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

C:\elasticsearch-5.2.0\bin>java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

C:\elasticsearch-5.2.0\bin>

**Comment by s1monw** [comment]
what does your %JAVA_HOME% point to?

**Comment by Tomket** [comment]
@s1monw, thx for mention the %JAVA_HOME%. It is working.

**Comment by chennaraov** [comment]
I am using java version "1.8.0_77" But still getting the same error. My ES version 5.2.0 running RHEL7 without any plugins

**Comment by hgc2002** [comment]
Somehow, fixing %JAVA_HOME% didn't make it to work, but forcing %JAVA% in elasticsearch.bat did, like this:

set JAVA="K:\aaa_Applications\Development\jdk-8u92-windows-i586\bin\java.exe"
echo %JAVA%

%JAVA% %ES_JAVA_OPTS% %ES_PARAMS% -cp "%ES_CLASSPATH%" "org.elasticsearch.bootstrap.Elasticsearch" !newparams!

**Comment by hassanalip** [comment]
I am using Linux  x86_64 and I have installed the latest JDK: 
echo $JAVA_HOME   --> /usr/java
java -version --> java version "1.6.0_131"

Elasticsearch rpm installed --> elasticsearch-5.2.2-1.noarch

I am still getting the error:
Starting elasticsearch: Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/bootstrap/Elasticsearch : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
........

**Comment by dadoonet** [comment]
@hassanalip It can not work with java 6.

**Comment by hassanalip** [comment]
Thanks for pointing that out. I am still getting the same error when I installed Java 8 and modified the init.d/elastcisearch file to explicitly point to java 8. I am attaching the snippet from the start up script and the output that I get when I try to run Elasticsearch:
================= elasticsearch startup script============================
checkJava() {
    if [ -x "$JAVA_HOME/bin/java" ]; then
        JAVA="$JAVA_HOME/bin/java"
    else
        JAVA="/home/hali1/jdk1.8.0_121/bin/java"
    fi

    if [ ! -x "$JAVA" ]; then
        echo "Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME"
        exit 1
    else
        echo "java running:$JAVA"

    fi
===============================Output=============================
java running:/home/hali1/jdk1.8.0_121/bin/java
Starting elasticsearch: Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/bootstrap/Elasticsearch : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:281)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:56)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: org.elasticsearch.bootstrap.Elasticsearch.  Program will exit.
                                                           [FAILED]

**Comment by hassanalip** [comment]
Thanks Dadoonet. 
There were multiple java versions installed on the system and even when I had change the elasticsearch script to manually set the JAVA_HOME it was not picking up the correct one. I had to go into update-alternatives to pick the correct java version

**Comment by PatelAshish11** [comment]
The version number shown describes the version of the JRE the class file is compatible with.

The reported major numbers are:

Java SE 13 = 57,
Java SE 12 = 56,
Java SE 11 = 55,
Java SE 10 = 54,
Java SE 9 = 53,
Java SE 8 = 52,
Java SE 7 = 51,
Java SE 6.0 = 50,
Java SE 5.0 = 49,
JDK 1.4 = 48,
JDK 1.3 = 47,
JDK 1.2 = 46,
JDK 1.1 = 45

Full source [here](https://icetutor.com/question/how-to-fix-java-lang-unsupportedclassversionerror-unsupported-major-minor-version/)
