### ISSUE TITLE
Mysterious NullPointerException from TransportService#shouldTraceAction

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#21130]
Example build failure:
http://build-us-00.elastic.co/job/es_core_master_windows-2012-r2/4135/

Reproduce command:
```
gradle :core:integTest -Dtests.seed=325A8CF111055EE4 -Dtests.class=org.elasticsearch.cluster.settings.ClusterSettingsIT -Dtests.method="testLoggerLevelUpdate" -Dtests.es.logger.level=DEBUG -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=973m -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:+UseCompressedOops" -Dtests.locale=da -Dtests.timezone=Cuba
```

Error:
```
java.lang.NullPointerException
	at org.elasticsearch.common.regex.Regex.simpleMatch(Regex.java:116)
	at org.elasticsearch.common.regex.Regex.simpleMatch(Regex.java:133)
	at org.elasticsearch.transport.TransportService.shouldTraceAction(TransportService.java:616)
	at org.elasticsearch.transport.TransportService.access$900(TransportService.java:71)
	at org.elasticsearch.transport.TransportService$Adapter.onRequestSent(TransportService.java:696)
	at org.elasticsearch.transport.TcpTransport.lambda$sendRequest$1091(TcpTransport.java:954)
	at org.elasticsearch.transport.TcpTransport$$Lambda$1128/2110774335.run(Unknown Source)
	at org.elasticsearch.transport.MockTcpTransport.sendMessage(MockTcpTransport.java:236)
	at org.elasticsearch.transport.MockTcpTransport.sendMessage(MockTcpTransport.java:66)
	at org.elasticsearch.transport.TcpTransport.internalSendMessage(TcpTransport.java:975)
	at org.elasticsearch.transport.TcpTransport.sendRequest(TcpTransport.java:957)
	at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:519)
	at org.elasticsearch.transport.TransportService$$Lambda$878/1199854267.sendRequest(Unknown Source)
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:464)
	at org.elasticsearch.action.TransportActionNodeProxy.execute(TransportActionNodeProxy.java:51)
	at org.elasticsearch.client.transport.support.TransportProxyClient.lambda$execute$733(TransportProxyClient.java:60)
	at org.elasticsearch.client.transport.support.TransportProxyClient$$Lambda$1143/834830068.doWithNode(Unknown Source)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:230)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:60)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:333)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:400)
	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:67)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:400)
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:707)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:77)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:51)
	at org.elasticsearch.cluster.settings.ClusterSettingsIT.testLoggerLevelUpdate(ClusterSettingsIT.java:352)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1764)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:871)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:907)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:921)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:809)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:460)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:880)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:781)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:816)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:827)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jasontedor** [comment]
This isn't an issue with the specific test, we've been seeing failures like this across a variety of tests for a few weeks now. The only common culprit is the transport tracer, and we suspect a JVM bug.

**Comment by jasontedor** [comment]
I changed the title to reflect that this issue is not specific to this test.

**Comment by colings86** [comment]
Closing this issue as we don't really have enough information to describe this problem at the moment.
