### ISSUE TITLE
Scroll - Java Array Index Out Of Bounds Exception

### ISSUE THREAD

**Issue by saudurehman** [elastic/elasticsearch#21159]
**Elasticsearch version**: 2.4.0

**Plugins installed**: [cloud-aws, kopf, license, marvel-agent]

**JVM version**: 1.8.0_101

**OS version**: Linux - 3.13.0-95-generic

**Description of the problem including expected versus actual behavior**: 
[2016-10-26 22:28:48,314][WARN ][rest.suppressed          ] path: /_search/scroll, params: {scroll=5m}
java.lang.ArrayIndexOutOfBoundsException: -131071

**Steps to reproduce**:
1. Scroll with size 1000, index with 300 shards, with haschild and inner hits of size 300 query.

**Provide logs (if relevant)**:

```
[2016-10-26 22:28:48,314][WARN ][rest.suppressed          ] path: /_search/scroll, params: {scroll=5m}
java.lang.ArrayIndexOutOfBoundsException: -131071
        at org.elasticsearch.common.util.BigByteArray.set(BigByteArray.java:97)
        at org.elasticsearch.common.io.stream.BytesStreamOutput.writeBytes(BytesStreamOutput.java:93)
        at org.elasticsearch.common.io.stream.StreamOutput.write(StreamOutput.java:299)
        at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2014)
        at com.fasterxml.jackson.core.json.UTF8JsonGenerator.flush(UTF8JsonGenerator.java:1027)
        at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.flush(JsonXContentGenerator.java:436)
        at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.writeRawField(JsonXContentGenerator.java:369)
        at org.elasticsearch.common.xcontent.XContentBuilder.rawField(XContentBuilder.java:914)
        at org.elasticsearch.common.xcontent.XContentHelper.writeRawField(XContentHelper.java:378)
        at org.elasticsearch.search.internal.InternalSearchHit.toXContent(InternalSearchHit.java:476)
        at org.elasticsearch.search.internal.InternalSearchHits.toXContent(InternalSearchHits.java:184)
        at org.elasticsearch.search.internal.InternalSearchResponse.toXContent(InternalSearchResponse.java:111)
        at org.elasticsearch.action.search.SearchResponse.toXContent(SearchResponse.java:195)
        at org.elasticsearch.rest.action.support.RestStatusToXContentListener.buildResponse(RestStatusToXContentListener.java:43)
        at org.elasticsearch.rest.action.support.RestStatusToXContentListener.buildResponse(RestStatusToXContentListener.java:38)
        at org.elasticsearch.rest.action.support.RestStatusToXContentListener.buildResponse(RestStatusToXContentListener.java:30)
        at org.elasticsearch.rest.action.support.RestResponseListener.processResponse(RestResponseListener.java:43)
        at org.elasticsearch.rest.action.support.RestActionListener.onResponse(RestActionListener.java:49)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:89)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:85)
        at org.elasticsearch.action.search.SearchScrollScanAsyncAction.innerFinishHim(SearchScrollScanAsyncAction.java:210)
        at org.elasticsearch.action.search.SearchScrollScanAsyncAction.finishHim(SearchScrollScanAsyncAction.java:167)
        at org.elasticsearch.action.search.SearchScrollScanAsyncAction.access$200(SearchScrollScanAsyncAction.java:42)
        at org.elasticsearch.action.search.SearchScrollScanAsyncAction$1.onResponse(SearchScrollScanAsyncAction.java:143)
        at org.elasticsearch.action.search.SearchScrollScanAsyncAction$1.onResponse(SearchScrollScanAsyncAction.java:136)
        at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:41)
        at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:158)
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:124)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Describe the feature**:

**Comment by jpountz** [comment]
I suspect this query generates a response that is more than 2GB in total and overflows an integer.
