### ISSUE TITLE
Exception: [o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]

### ISSUE THREAD

**Issue by shobhitsharma** [elastic/elasticsearch#21162]
**Elasticsearch version**: v5.0.0

**Plugins installed**: []

**JVM version**: 1.8..0_102

**OS version**: macOS Sierra

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
Ran `elasticsearch` from the terminal

**Provide logs (if relevant)**:

```bash
[2016-10-27T22:32:33,158][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [path.plugins] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:116) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:103) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.cli.Command.main(Command.java:62) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:73) ~[elasticsearch-5.0.0.jar:5.0.0]
Caused by: java.lang.IllegalArgumentException: unknown setting [path.plugins] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:271) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:239) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:138) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.node.Node.<init>(Node.java:311) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.node.Node.<init>(Node.java:220) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:191) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:191) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:112) ~[elasticsearch-5.0.0.jar:5.0.0]
```

**Describe the feature**:
Installed elasticsearch from homebrew

**Comment by dakrone** [comment]
Hi,
We reserve Github issues for feature requests and bug reports. If you are having problems please use https://discuss.elastic.co instead!

In your case, the answer is in the message: `unknown setting [path.plugins] please check that any required plugins are installed, or check the breaking changes documentation for removed settings`

**Comment by s1monw** [comment]
@shobhitsharma why did you open this issue, I mean the exception says pretty clearly what's wrong so I wonder if we can do better somehow to display this in a different way? What could have helped here to make it easier to understand?

 You are using `plugin.path` in your settings and it doesn't exists anymore --> `unknown setting [path.plugins] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:116) ~[elasticsearch-5.0.0.jar:5.0.0]`

**Comment by shobhitsharma** [comment]
Interesting, it was a fresh install for ElasticSearch 5 on new machine, switched to older, stable version. Works fine.

**Comment by shobhitsharma** [comment]
Interesting, just wanted to report that it was a fresh install for `5.x` on new machine, switched to older, stable version. Works fine with `2.x`.

**Comment by s1monw** [comment]
@shobhitsharma I have no idea who maintains that homebrew stuff, it's not managed by us, maybe that is the issue, I recommend using a tar / zip distribution from our website instead.

**Comment by jasontedor** [comment]
If you previously had a previous version of Elasticsearch installed and edited the configuration file (`elasticsearch.yml`), when you upgrade via Homebrew, Homebrew will preserve your old config file if you've modified it from the defaults (this is a thing that good package managers do, upgrading should preserve any custom configuration that you've applied). The new configuration file is available in `/usr/local/etc/elasticsearch/elasticsearch.yml.default`.

Thus, I think that you had `path.plugins` in your configuration file from an older installation of Elasticsearch via Homebrew, and this was preserved on upgrade.

**Comment by shobhitsharma** [comment]
@jasontedor That explains it perfectly. I reconfigured it with `5.x.x` defaults, things are running sweetly now. Cheers!

**Comment by kidlab** [comment]
@jasontedor Thank you so much for the tip 👍

**Comment by rocknruby** [comment]
Thanks @jasontedor .  Make it short: 

```
$ cp /usr/local/etc/elasticsearch/elasticsearch.yml.default /usr/local/etc/elasticsearch/elasticsearch.yml
```

**Comment by kimegede** [comment]
> @shobhitsharma why did you open this issue, I mean the exception says pretty clearly what's wrong so I wonder if we can do better somehow to display this in a different way? What could have helped here to make it easier to understand?

@s1monw I had the same issue, and the `plugin.path` did exist in my case, so I wasn't sure where the problem were.
Afterwards I uninstalled elasticsearch and removed config files & folders and installed it again.
Then it seemed to have some issues, with my previous data, which I could easily delete locally - so I did and restarted elasticsearch and that made it work.

**Comment by phpmongodb** [comment]
If you have install elastic search through homebrew then try bellow line to start elasticseach instead of elasticsearch

> brew services start elasticsearch

**Comment by shabtaisharon** [comment]
Now that `path.plugins` is not supported, how do you set a custom folder for plugins?

**Comment by jasontedor** [comment]
@shobhitsharma You can not set a custom directory for plugins, you can only make the plugins folder a symbolic link to another location on the filesystem.
