### ISSUE TITLE
IndicesOptionsIntegrationIT#testUpdateSettings failure on 5.0 branch

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#21198]
Avast! `IndicesOptionsIntegrationIT`'s [sprung a leak](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.0+java9-periodic/488/console) on the 5.0 branch! `testUpdateSettings` failed with this reproduction:
```
gradle :core:integTest -Dtests.seed=D466EB96D225CD8D -Dtests.class=org.elasticsearch.indices.IndicesOptionsIntegrationIT -Dtests.method="testUpdateSettings" -Dtests.security.manager=true -Dtests.locale=sw-UG -Dtests.timezone=Asia/Shanghai
```

Our robot butler tells me that the cause of the failure is:

```
1> java.lang.IllegalStateException: IndexWriter is still open on shard [barbaz][1]
1> at org.elasticsearch.test.store.MockFSDirectoryService.checkIndex(MockFSDirectoryService.java:142) ~[framework-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
1> at org.elasticsearch.test.store.MockFSIndexStore$Listener.afterIndexShardClosed(MockFSIndexStore.java:101) ~[framework-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
1> at org.elasticsearch.index.CompositeIndexEventListener.afterIndexShardClosed(CompositeIndexEventListener.java:110) ~[main/:?]
1> at org.elasticsearch.index.IndexService.closeShard(IndexService.java:405) ~[main/:?]
1> at org.elasticsearch.index.IndexService.removeShard(IndexService.java:381) ~[main/:?]
1> at org.elasticsearch.index.IndexService.close(IndexService.java:237) ~[main/:?]
1> at org.elasticsearch.indices.IndicesService.removeIndex(IndicesService.java:506) ~[main/:?]
1> at org.elasticsearch.indices.IndicesService.deleteIndex(IndicesService.java:568) ~[main/:?]
1> at org.elasticsearch.indices.cluster.IndicesClusterStateService.deleteIndices(IndicesClusterStateService.java:254) ~[main/:?]
1> at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:188) ~[main/:?]
1> at org.elasticsearch.cluster.service.ClusterService.runTasksForExecutor(ClusterService.java:708) ~[main/:?]
1> at org.elasticsearch.cluster.service.ClusterService$UpdateTask.run(ClusterService.java:894) ~[main/:?]
1> at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:444) ~[main/:?]
1> at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:237) ~[main/:?]
1> at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:200) ~[main/:?]
1> at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-ea/ThreadPoolExecutor.java:1161) ~[?:?]
1> at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-ea/ThreadPoolExecutor.java:635) ~[?:?]
1> at java.lang.Thread.run(java.base@9-ea/Thread.java:843) ~[?:?]
1> Caused by: org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /var/lib/jenkins/workspace/elastic+elasticsearch+5.0+java9-
Caused by: org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /var/lib/jenkins/workspace/elastic+elasticsearch+5.0+java9-periodic/core/build/testrun/integTest/J1/temp/org.elasticsearch.indices.IndicesOptionsIntegrationIT_D466EB96D225CD8D-001/tempDir-002/data/nodes/2/indices/3nw9U4VtSgGIsmt9ICaQ9Q/1/index/write.lock
1> at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:127) ~[lucene-core-6.2.0.jar:6.2.0 764d0f19151dbff6f5fcd9fc4b2682cf934590c5 - mike - 2016-08-20 05:39:36]
1> at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41) ~[lucene-core-6.2.0.jar:6.2.0 764d0f19151dbff6f5fcd9fc4b2682cf934590c5 - mike - 2016-08-20 05:39:36]
1> at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45) ~[lucene-core-6.2.0.jar:6.2.0 764d0f19151dbff6f5fcd9fc4b2682cf934590c5 - mike - 2016-08-20 05:39:36]
1> at org.apache.lucene.store.FilterDirectory.obtainLock(FilterDirectory.java:104) ~[lucene-core-6.2.0.jar:6.2.0 764d0f19151dbff6f5fcd9fc4b2682cf934590c5 - mike - 2016-08-20 05:39:36]
1> at org.apache.lucene.store.FilterDirectory.obtainLock(FilterDirectory.java:104) ~[lucene-core-6.2.0.jar:6.2.0 764d0f19151dbff6f5fcd9fc4b2682cf934590c5 - mike - 2016-08-20 05:39:36]
1> at org.apache.lucene.store.MockDirectoryWrapper.obtainLock(MockDirectoryWrapper.java:1049) ~[lucene-test-framework-6.2.0.jar:6.2.0 764d0f19151dbff6f5fcd9fc4b2682cf934590c5 - mike - 2016-08-20 05:39:36]
1> at org.apache.lucene.store.FilterDirectory.obtainLock(FilterDirectory.java:104) ~[lucene-core-6.2.0.jar:6.2.0 764d0f19151dbff6f5fcd9fc4b2682cf934590c5 - mike - 2016-08-20 05:39:36]
1> at org.apache.lucene.index.CheckIndex.<init>(CheckIndex.java:399) ~[lucene-core-6.2.0.jar:6.2.0 764d0f19151dbff6f5fcd9fc4b2682cf934590c5 - mike - 2016-08-20 05:39:36]
1> at org.elasticsearch.test.store.MockFSDirectoryService.checkIndex(MockFSDirectoryService.java:123) ~[framework-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT] 
  1> 	... 17 more 
```

After that all kinds of things failed because the butler couldn't shoot our test.

**Comment by nik9000** [comment]
@mikemccand, any idea why this stack trace literally has your name on it?

**Comment by clintongormley** [comment]
ping @mikemccand

**Comment by javanna** [comment]
given that this issue had no activity in ~8 months, I would close it. We can always reopen if we encounter the same failure again.
