### ISSUE TITLE
Avoid NPE in RestClient#buildUri()

### ISSUE THREAD

**Issue by biyuhao** [elastic/elasticsearch#21232]
**Elasticsearch version**:5.0.0

**Plugins installed**: [none]

**JVM version**:openjdk version "1.8.0_91"

**OS version**:Linux Mint 18

**Description of the problem including expected versus actual behavior**:

1. If we perform a request with null path in RestClient we may got NPE and no hint message.
Since the pathPrefix should not be null, maybe we can treat null path as empty and continue to request.
2. By the way, I have a little question here. Should we encode the URI which composed of pathPrefix and path?

**Steps to reproduce**:
 1.Construct arbitrary valid RestClient.
 2.Perform request with null path.
```restClient.performRequest(method, null);```

**Exception Caught**:
```
java.lang.NullPointerException
	at __randomizedtesting.SeedInfo.seed([D6503272CE20A134:63A320640CEEA8AF]:0)
	at java.net.URI$Parser.parse(URI.java:3042)
	at java.net.URI.<init>(URI.java:588)
	at org.apache.http.client.utils.URIBuilder.<init>(URIBuilder.java:82)
	at org.elasticsearch.client.RestClient.buildUri(RestClient.java:525)
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:285)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:211)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:185)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:146)
......
```

**Comment by javanna** [comment]
I commented on your PR (thanks for sending it!). I think we should improve the error message but we should still fail with an NPE rather that avoid the NPE.
