### ISSUE TITLE
[CI] MockPageRecycler and MockBigArrays failures assertion failures in unrelated tests

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#21315]
Encountered a pair of failures where MockPageRecylcer and MockBigArrays failed assertions because not all pages/arrays were reclaimed.  However, the tests in question don't use MockPageRecyler or MockBigArrays directly.  @ywelsch suggested it may have been interference from an unrelated test, since these share state (e.g. related:  https://github.com/elastic/elasticsearch/pull/21256)

```
   > Throwable #1: java.lang.RuntimeException: 1 pages have not been released
   > 	at __randomizedtesting.SeedInfo.seed([EADFD0414DFC8AEC:A7DA0CF6834BD7E3]:0)
   > 	at org.elasticsearch.common.util.MockPageCacheRecycler.ensureAllPagesAreReleased(MockPageCacheRecycler.java:52)
   > 	at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:227)
   > 	at org.elasticsearch.test.ESTestCase.ensureCleanedUp(ESTestCase.java:222)
   > 	at java.lang.Thread.run(Thread.java:745)
   > Caused by: java.lang.Throwable
   > 	at org.elasticsearch.common.util.MockPageCacheRecycler.wrap(MockPageCacheRecycler.java:69)
   > 	at org.elasticsearch.common.util.MockPageCacheRecycler.bytePage(MockPageCacheRecycler.java:118)
   > 	at org.elasticsearch.common.util.BigArrays.newByteArray(BigArrays.java:466)
   > 	at org.elasticsearch.common.util.MockBigArrays.newByteArray(MockBigArrays.java:102)
   > 	at org.elasticsearch.common.util.BigArrays.newByteArray(BigArrays.java:479)
   > 	at org.elasticsearch.common.io.stream.BytesStreamOutput.<init>(BytesStreamOutput.java:62)
   > 	at org.elasticsearch.common.io.stream.ReleasableBytesStreamOutput.<init>(ReleasableBytesStreamOutput.java:36)
   > 	at org.elasticsearch.transport.TcpTransport.sendResponse(TcpTransport.java:1025)
   > 	at org.elasticsearch.transport.TcpTransportChannel.sendResponse(TcpTransportChannel.java:67)
   > 	at org.elasticsearch.transport.TcpTransportChannel.sendResponse(TcpTransportChannel.java:61)
   > 	at org.elasticsearch.transport.DelegatingTransportChannel.sendResponse(DelegatingTransportChannel.java:58)
   > 	at 
```

```
   > Throwable #1: java.lang.RuntimeException: 1 arrays have not been released
   > 	at __randomizedtesting.SeedInfo.seed([EADFD0414DFC8AEC:FC8E67EBC3395178]:0)
   > 	at org.elasticsearch.common.util.MockBigArrays.ensureAllArraysAreReleased(MockBigArrays.java:66)
   > 	at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:228)
   > 	at org.elasticsearch.test.ESTestCase.ensureCleanedUp(ESTestCase.java:222)
   > 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by imotov** [comment]
A few examples of similar failures from last night and today:

OldMonitoringIndicesBackwardsCompatibilityIT.testOldIndexes  - https://internal-ci.elastic.co/job/elastic+x-plugins+master+periodic/7971/console

PermissionTests.testIndicesGlobalsIterator - https://internal-ci.elastic.co/job/elastic+x-plugins+master/1427/console

ClusterPrivilegeTests.testThatSnapshotAndRestore - https://internal-ci.elastic.co/job/elastic+x-plugins+master+periodic/7964/console

**Comment by bleskes** [comment]
@spinscale and I talked about an option of extending the message in that throwable to see which test run while the page was acquired. Not sure how far he got with it.

**Comment by colings86** [comment]
This seems to have been fixed by https://github.com/elastic/elasticsearch/pull/27880
