### ISSUE TITLE
[CI] DelayedAllocationIT#testDelayedAllocationTimesOut timed out waiting for green

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#21317]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/519/consoleFull

```
gradle :core:integTest -Dtests.seed=52DAE2448723D456 -Dtests.class=org.elasticsearch.cluster.routing.DelayedAllocationIT -Dtests.method="testDelayedAllocationTimesOut" -Dtests.security.manager=true -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" -Dtests.locale=en-AU -Dtests.timezone=America/North_Dakota/Center
```

Took 50+ iterations to reproduce, but seed `52DAE2448723D456:32B89DA3E40C437B` finally did for me.

**Error:**

```
FAILURE 30.8s J2 | DelayedAllocationIT.testDelayedAllocationTimesOut <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: timed out waiting for green state
   > 	at __randomizedtesting.SeedInfo.seed([52DAE2448723D456:6DD1D4D137CACA3F]:0)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:877)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:861)
   > 	at org.elasticsearch.cluster.routing.DelayedAllocationIT.testDelayedAllocationTimesOut(DelayedAllocationIT.java:101)
   > 	at java.lang.Thread.run(Thread.java:745)
  1> [2016-11-03T14:00:34,601][INFO ][o.e.c.r.DelayedAllocationIT] 
```

@ywelsch Is this perhaps in your area of expertise?

**Comment by ywelsch** [comment]
The issue why this test failed is of a more general nature. I opened #21344 to address this.
