### ISSUE TITLE
connection closing/timeout issue maybe related to client node?

### ISSUE THREAD

**Issue by olibob** [elastic/elasticsearch#21326]
**Elasticsearch version**: 5.0.0

**Plugins installed**: []

**JVM version**: 1.8.0_112-b15

**OS version**: Debian 8 (jessie)

Hi,

I'm having an issue bulk loading into a 4 nodes test setup: 1 client node + 3 data nodes (one of them gets elected as master).
During the loading (from scratch), I can see the following in the logs:

Client Node:
```
[2016-11-04T07:16:08,090][WARN ][o.e.t.n.Netty4Transport  ] [bb-front-els-pp] exception caught on transport layer [[id: 0xe3826a4f, L:/10.13.50.199:9300 - R:/10.13.50.132:45521]], closing connection
[2016-11-04T09:12:27,632][WARN ][o.e.t.n.Netty4Transport  ] [bb-front-els-pp] exception caught on transport layer [[id: 0x5da55f00, L:/10.13.50.199:48784 - R:/10.13.50.134:9300]], closing connection
[2016-11-04T09:12:50,672][WARN ][o.e.t.n.Netty4Transport  ] [bb-front-els-pp] exception caught on transport layer [[id: 0xa2219798, L:/10.13.50.199:57320 - R:/10.13.50.133:9300]], closing connection
```

Data1:
```
[2016-11-04T07:16:51,118][WARN ][o.e.t.n.Netty4Transport  ] [bb-back-els1-pp] exception caught on transport layer [[id: 0x7fd2453d, L:/10.13.50.132:45528 - R:/10.13.50.199:9300]], closing connection
```

Data2:
```
[2016-11-04T07:16:49,457][WARN ][o.e.t.n.Netty4Transport  ] [bb-back-els2-pp] exception caught on transport layer [[id: 0xc9a27aae, L:/10.13.50.133:56808 - R:/10.13.50.199:9300]], closing connection
```

Data3:

```
[2016-11-04T07:16:25,248][WARN ][o.e.t.n.Netty4Transport  ] [bb-back-els3-pp] exception caught on transport layer [[id: 0x420dc7e3, L:/10.13.50.134:49367 - R:/10.13.50.199:9300]], closing connection
```

Node configs are very basic:

```
bootstrap.memory_lock: true
network.host: 10.13.50.132 (133, 134)
discovery.zen.ping.unicast.hosts: ["bb-front-els-pp", "bb-back-els1-pp", "bb-back-els2-pp", "bb-back-els3-pp "]
discovery.zen.minimum_master_nodes: 2
node.max_local_storage_nodes: 1
```

Client Node:

```
node.master: false
node.data: false
node.ingest: false
bootstrap.memory_lock: true
network.host: 10.13.50.199
discovery.zen.ping.unicast.hosts: ["bb-front-els-pp", "bb-back-els1-pp", "bb-back-els2-pp", "bb-back-els3-pp "]
discovery.zen.minimum_master_nodes: 2
node.max_local_storage_nodes: 1
```

_cat/nodes

```
10.13.50.132  8 82 0 0.00 0.01 0.05 mdi - bb-back-els1-pp
10.13.50.134 10 90 0 0.04 0.03 0.05 mdi * bb-back-els3-pp
10.13.50.199  5 78 0 0.00 0.01 0.05 -   - bb-front-els-pp
10.13.50.133  7 83 0 0.00 0.01 0.05 mdi - bb-back-els2-pp
```

- There are no network restrictions on these nodes
- All nodes are Debian Jessie VMs (4 cores, 8GB RAM): swappiness set to 1
- Elasticsearch 5.0.0 (no plugins): JVM with 4GB - bootstrap.memory_lock: true
- JDK: 1.8.0_112-b15 (with 1.8.0_101 I've even seen a node restart, master being re-elected, ...)
- We use a data node to bulk load (REST) because we get better results than using the client node

We load 500 documents at a time (around 800k per document). A full load represents 3529299 documents

After a random amount of time (or documents loaded), the warnings start to appear. The  cluster does not respond to queries anymore, even hours after completion of the bulk load. A restart of the cluster is necessary.

Anyone experiencing this kind of behavior?
Any pointers would be appreciated.

**Comment by clintongormley** [comment]
Hi @olibob 

Do you see anything in the elasticsearch logs?  What about node stats - is there anything happening with memory usage?

Could you possibly try using netty3 ( `./bin/elasticsearch -Etransport.type=netty3`)  and see if this reproduces?

**Comment by olibob** [comment]
Hi @clintongormley 

We have stopped the client and are in the process of bulk reloading a fresh index. We'll have the result of this test in a few hours. So far, no errors and 2.7 million documents loaded.

Here's an example of previous logs:

```
[2016-11-03T22:30:21,133][WARN ][o.e.t.n.Netty4Transport  ] [bb-back-els2-pp] exception caught on transport layer [[id: 0xe9336fdd, L:/10.13.50.133:56709 - R:/10.13.50.199:9300]], closing connection
java.io.IOException: Connection Timeout
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:?]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:?]
        at io.netty.buffer.PooledHeapByteBuf.setBytes(PooledHeapByteBuf.java:261) ~[netty-buffer-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[netty-buffer-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367) ~[netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:513) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:467) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty-common-4.1.5.Final.jar:4.1.5.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
[2016-11-03T22:30:27,235][INFO ][o.e.c.s.ClusterService   ] [bb-back-els2-pp] removed {{bb-front-els-pp}{ehwbJQCsTkOHjLSZddC6IA}{10fEbfRbQJeGRGDRZBVgdg}{10.13.50.199}{10.13.50.199:9300},}, reason: zen-disco-receive(from master [master {bb-back-els3-pp}{10Ot_PmnTxSo_uY2QHg92g}{TUZ21h8-TtmKonsgQD_3pQ}{10.13.50.134}{10.13.50.134:9300} committed version [29]])
[2016-11-03T22:30:30,255][INFO ][o.e.c.s.ClusterService   ] [bb-back-els2-pp] added {{bb-front-els-pp}{ehwbJQCsTkOHjLSZddC6IA}{10fEbfRbQJeGRGDRZBVgdg}{10.13.50.199}{10.13.50.199:9300},}, reason: zen-disco-receive(from master [master {bb-back-els3-pp}{10Ot_PmnTxSo_uY2QHg92g}{TUZ21h8-TtmKonsgQD_3pQ}{10.13.50.134}{10.13.50.134:9300} committed version [30]])
```

All data nodes complain about connection issues with the client node. And the client node has connection issues with all data nodes. We first thought it was a network issues and removed all network restriction. At that time, only the client node was used, for search and bulk indexing.

We got "better" results using a data node to bulk index, but no success: warnings in the logs and unresponsive cluster. A simple `curl ip:9200` would work, but anything else, as trivial as `curl ip:9200/_cat/nodes` would get no response at all.

This test (client node offline) is the longest stretch we've gone without errors, but the bulk loading is still going on.

We'll give using netty3 a go when the actual test is completed or failed.

**Comment by olibob** [comment]
Without the client node, the bulk load succeeded.

Adding `-Etransport.type=netty3` to the *jvm.options* file results in the service not starting because the option is not recognized by elasticsearch.

```
Nov 08 09:59:24 bb-back-els1-pp elasticsearch[19087]: Unrecognized option: -Etransport.type=netty3
```

**Comment by clintongormley** [comment]
> Adding -Etransport.type=netty3 to the jvm.options file results in the service not starting because the option is not recognized by elasticsearch.

You should add that to the command line, not jvm.options

> Without the client node, the bulk load succeeded.

I wonder if you're overloading the heap on your client nodes.  How much heap are you giving them?  Try monitoring the stats on the client nodes individually (they're not included in stats requests made to master or data nodes)

**Comment by olibob** [comment]
Ok, I changed the start command in the systemd service. All nodes up.

All nodes have 4GB heap: 3 standard nodes + 1 client node.
A test is ongoing with `-Etransport.type=netty3`

**Comment by olibob** [comment]
With `-Etransport.type=netty3`, the bulk load was successful and Heap usage maxed out at about 73%.

That was bulk loading through the client node.

It seems to correct the errors experienced previously.

**Comment by clintongormley** [comment]
Thanks for the feedback @olibob - I think we need to try to recreate this locally.

btw 500 x 800k = 400MB bulk requests - this is way bigger than we would normally recommend.  I'd try reducing the number of docs to maybe 100 per request?

**Comment by olibob** [comment]
@clintongormley 

The 800k is the size of one bulk request containing the 500 documents. So that bulk is really tiny.

We might have a problem which is not related to the transport. Searching around, I stumbled on [this in the forum](https://discuss.elastic.co/t/random-node-disconnects-java-io-ioexception-connection-timed-out/33151) which led me to [this blog article](https://blog.trifork.com/2015/04/08/dealing-with-nodenotavailableexceptions-in-elasticsearch/comment-page-1/).

So I gave reducing the keep alive a shot with these settings:

```
sysctl -w \
net.ipv4.tcp_keepalive_time=600 \
net.ipv4.tcp_keepalive_intvl=60 \
net.ipv4.tcp_keepalive_probes=3
```

A first test has been done yesterday with these keep alive settings + transport using netty3: result, success!

A second test is ongoing right now, same keep alive settings + transport using netty4.

Results to follow.

**Comment by olibob** [comment]
@clintongormley 

Confirmed: changing the keep alive settings on the hosts solved the issue.
So this was not related to a transport issue.

**Comment by clintongormley** [comment]
thanks for letting us know @olibob - we'll give some thought about where to document these settings.

**Comment by andrershov** [comment]
Closing it in favor of #45081
