### ISSUE TITLE
Bug - changing field in partials update script throws error

### ISSUE THREAD

**Issue by florianbepunkt** [elastic/elasticsearch#21358]
I have a local installaton of ES5. When I create a new index and run the following partial update script:

```
body: {
    "script" : {
	    "inline": "ctx._source.hasLiked.add(params.swipedUserID)",
	    "lang": "painless",
	    "params" : {
	        "swipedUserID": "123456"
	    }
	},
	"upsert": {
	"hasLiked": ['123456]
	}
}
```

everything works as exspected: the value is added to array or upserted if not-existing.

But when I change the script now to `ctx._source.excludeFromQuery.add(params.swipedUserID)` after I run the first version I get an error. But the error seems not to be in my script. If I delete the index and create it again (same mapping, same name, etc) and then run the scripts in reversed order, the `ctx._source.excludeFromQuery.add(params.swipedUserID)` script runs fine, but the `ctx._source.hasLiked.add(params.swipedUserID)` one now throws the (same) error.

Error: 

```
{ Error: [remote_transport_exception] [oPvNqgZ][127.0.0.1:9300][indices:data/write/update[s]]
    at respond (/Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Roomary/Data/firebase-server/node_modules/elasticsearch/src/lib/transport.js:289:15)
    at checkRespForFailure (/Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Roomary/Data/firebase-server/node_modules/elasticsearch/src/lib/transport.js:248:7)
    at HttpConnector.<anonymous> (/Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Roomary/Data/firebase-server/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
    at IncomingMessage.wrapper (/Users/floriannorbertbepunkt/Dropbox/Dropbox Arbeit/Mister Bishop Studios/Roomary/Data/firebase-server/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  status: 400,
  displayName: 'BadRequest',
  message: '[remote_transport_exception] [oPvNqgZ][127.0.0.1:9300][indices:data/write/update[s]]',
  path: '/roomary_swipes/userSwipeData/6HFntI1L8NOzbZj3O5SnfvKHt5C2/_update',
  query: {},
  body: 
   { error: 
      { root_cause: [Object],
        type: 'illegal_argument_exception',
        reason: 'failed to execute script',
        caused_by: [Object] },
     status: 400 },
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[oPvNqgZ][127.0.0.1:9300][indices:data/write/update[s]]"}],"type":"illegal_argument_exception","reason":"failed to execute script","caused_by":{"type":"script_exception","reason":"runtime error","caused_by":{"type":"null_pointer_exception","reason":null},"script_stack":["ctx._source.hasLiked.add(params.swipedUserID)","                               ^---- HERE"],"script":"ctx._source.hasLiked.add(params.swipedUserID)","lang":"painless"}},"status":400}',
  toString: [Function],
  toJSON: [Function] }
```

**Comment by florianbepunkt** [comment]
Okay, figured it out. It's not a bug. It was a weird combination of things… the first function triggers the upsert since the document that should be updated works fine. The upsert works as expected and a new document with the speciefied field is created. Next time, the script runs, since we have a document now… the .add method fails when the field does not exists … so I need to check first whether the field exists (and probably also if it is an array) before calling the .add method.

But debugging this was a pain since the painless (oh my) language error is rather vague… switching to the other languages in my despair I got  a null pointer error message that got me on the right track.

If I may suggest: Maybe you could add to the docs for partial updates some more examples that covers appending data to arrays and checking if field exists.

Thanks for your work.

**Comment by clintongormley** [comment]
When I try this out using REST I get a nicely formatted error message:

```
{
  "error": {
    "root_cause": [
      {
        "type": "remote_transport_exception",
        "reason": "[zSttvmn][127.0.0.1:9300][indices:data/write/update[s]]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "failed to execute script",
    "caused_by": {
      "type": "script_exception",
      "reason": "runtime error",
      "caused_by": {
        "type": "null_pointer_exception",
        "reason": null
      },
      "script_stack": [
        "ctx._source.hasLiked.add(params.swipedUserID)",
        "                               ^---- HERE"
      ],
      "script": "ctx._source.hasLiked.add(params.swipedUserID)",
      "lang": "painless"
    }
  },
  "status": 400
}
```

Perhaps the client that you're using is messing with the formatting?

**Comment by florianbepunkt** [comment]
thanks. I keep it in mind to check my queries with rest api firt next time.
