### ISSUE TITLE
ES script error when upgrade from 2.1.0 to 5.0.0

### ISSUE THREAD

**Issue by small-tomorrow** [elastic/elasticsearch#21372]
**Elasticsearch version**:

**Plugins installed**: []

**JVM version**: Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

**OS version**: Linux version 2.6.32_1-15-0-0 

**Description of the problem including expected versus actual behavior**:
    after upgrading from v2.1 to 5.0 , the query scripts seem not to work anymore . however,I have followed the doc reference of Version 5.0 as configured : **script.legacy.default_lang: groovy** ,but it seems not work ,as the error log shows in the **Provide logs** part bellow.
    my question is : **is there a way to set the default script lang instead of setting lang params in each query script ?**  **any advice will be great appreciated !**
**Steps to reproduce**:
 1. upgrade from V 2.1 to V 5.0
 2. script query failed 
 3. how can I set the default script lang without changing my service code (which is too much) ?

**Provide logs (if relevant)**:
org.elasticsearch.action.search.ReduceSearchPhaseException: [reduce] 
	at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction$2.onFailure(SearchQueryThenFetchAsyncAction.java:143) [elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:490) [elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-5.0.0.jar:5.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: org.elasticsearch.script.ScriptException: compile error
	at org.elasticsearch.painless.PainlessScriptEngineService.convertToScriptException(PainlessScriptEngineService.java:264) ~[?:?]
	at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:176) ~[?:?]
	at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.aggregations.pipeline.bucketscript.BucketScriptPipelineAggregator.reduce(BucketScriptPipelineAggregator.java:95) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:144) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:158) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.aggregations.bucket.terms.InternalTerms$Bucket.reduce(InternalTerms.java:135) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.aggregations.bucket.terms.InternalTerms.doReduce(InternalTerms.java:234) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:142) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:158) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.action.search.SearchPhaseController.merge(SearchPhaseController.java:493) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction$2.doRun(SearchQueryThenFetchAsyncAction.java:132) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.0.0.jar:5.0.0]
	... 3 more
Caused by: java.lang.IllegalArgumentException: Variable [sum_total] is not defined.
	at org.elasticsearch.painless.Executable$Script.compile(sum_total / sum_count @ <inline script>:1) ~[?:?]
	at org.elasticsearch.painless.Locals.getVariable(Locals.java:171) ~[?:?]
	at org.elasticsearch.painless.Locals.getVariable(Locals.java:169) ~[?:?]
	at org.elasticsearch.painless.node.EVariable.analyze(EVariable.java:55) ~[?:?]
	at org.elasticsearch.painless.node.EBinary.analyzeDiv(EBinary.java:145) ~[?:?]
	at org.elasticsearch.painless.node.EBinary.analyze(EBinary.java:72) ~[?:?]
	at org.elasticsearch.painless.node.SExpression.analyze(SExpression.java:56) ~[?:?]
	at org.elasticsearch.painless.node.SSource.analyze(SSource.java:190) ~[?:?]
	at org.elasticsearch.painless.node.SSource.analyze(SSource.java:162) ~[?:?]
	at org.elasticsearch.painless.Compiler.compile(Compiler.java:104) ~[?:?]
	at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:171) ~[?:?]
	at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:168) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_111]
	at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:168) ~[?:?]
	at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:339) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.script.ScriptService.compile(ScriptService.java:235) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.aggregations.pipeline.bucketscript.BucketScriptPipelineAggregator.reduce(BucketScriptPipelineAggregator.java:95) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:144) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:158) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.aggregations.bucket.terms.InternalTerms$Bucket.reduce(InternalTerms.java:135) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.aggregations.bucket.terms.InternalTerms.doReduce(InternalTerms.java:234) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:142) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:158) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.action.search.SearchPhaseController.merge(SearchPhaseController.java:493) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction$2.doRun(SearchQueryThenFetchAsyncAction.java:132) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.0.0.jar:5.0.0]
	... 3 more

**Describe the feature**:

**Comment by small-tomorrow** [comment]
could anyone help me ?  your words may save a young engineer from falling into Canyon

**Comment by clintongormley** [comment]
>  however,I have followed the doc reference of Version 5.0 as configured : script.legacy.default_lang: groovy ,but it seems not work ,as the error log shows in the Provide logs part bellow.
> my question is : is there a way to set the default script lang instead of setting lang params in each query script ? any advice will be great appreciated !

The `script.legacy.default_lang` setting is only for scripts in existing percolators, watches etc.  There is no way to change the default lang for other scripts.  You have have to pass the language in with the request in these cases.

**Comment by small-tomorrow** [comment]
@clintongormley  thank you  ! but  that is wired , if language param is allowed in the request cases , why can't we change the language in a global way ?

**Comment by clintongormley** [comment]
@small-tomorrow because groovy, javascript, python are deprecated and will be removed in 6.0, so we want you to actively think about the fact that you're using a deprecated feature, so that it doesn't come as a surprise later on

**Comment by small-tomorrow** [comment]
@clintongormley okay , thank you very much , it seems we'd better upgrade the requests code in time
