### ISSUE TITLE
TTL fails with `features that prevent cachability are disabled on this context`

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#21457]
Start with 2.4.0:

```
PUT my_index
{
  "mappings": {
    "my_type": {
      "_ttl": {
        "enabled": true
      }
    }
  }
}
```

Upgrade to 5.0.0:

```
PUT my_index/my_type/1?ttl=1s
{
  "text": "Will expire in 10 minutes"
}


GET my_index/_search
```

Returns:

```
{
  "took": 34,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 4,
    "failed": 1,
    "failures": [
      {
        "shard": 3,
        "index": "my_index",
        "node": "AFATqx6CR6SPvGWQ0DaxvA",
        "reason": {
          "type": "illegal_argument_exception",
          "reason": "features that prevent cachability are disabled on this context"
        }
      }
    ]
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": []
  }
} 
```

Related to https://github.com/elastic/elasticsearch/pull/21303

**Comment by clintongormley** [comment]
Stacktrace:

```
[2016-11-10T09:42:48,016][DEBUG][o.e.a.s.TransportSearchAction] [AFATqx6] [3] Failed to execute fetch phase
org.elasticsearch.transport.RemoteTransportException: [AFATqx6][127.0.0.1:9300][indices:data/read/search[phase/fetch/id]]
Caused by: java.lang.IllegalArgumentException: features that prevent cachability are disabled on this context
       	at org.elasticsearch.index.query.QueryShardContext.failIfFrozen(QueryShardContext.java:396) ~[elasticsearch-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
       	at org.elasticsearch.index.query.QueryShardContext.nowInMillis(QueryShardContext.java:278) ~[elasticsearch-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
       	at org.elasticsearch.index.mapper.TTLFieldMapper$TTLFieldType.valueForSearch(TTLFieldMapper.java:146) ~[elasticsearch-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
       	at org.elasticsearch.index.fieldvisitor.FieldsVisitor.postProcess(FieldsVisitor.java:93) ~[elasticsearch-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
       	at org.elasticsearch.search.fetch.FetchPhase.createSearchHit(FetchPhase.java:187) ~[elasticsearch-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
       	at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:152) ~[elasticsearch-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
       	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:474) ~[elasticsearch-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
       	at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$684(SearchTransportService.java:311) ~[elasticsearch-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
       	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
       	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
       	at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) [elasticsearch-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
       	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:520) [elasticsearch-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
       	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.0.1-SNAPSHOT.jar:5.0.1-SNAPSHOT]
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
       	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
```

**Comment by Hronom** [comment]
Does ttl available in ES 5.x ?

**Comment by s1monw** [comment]
@clintongormley this is fixed no?

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/21493

**Comment by Hronom** [comment]
@clintongormley sorry for duplicating question is ttl available in ES 5.x ?

**Comment by clintongormley** [comment]
@Hronom only for bwc, not for new indices
