### ISSUE TITLE
CircuitBreakerServiceIT.testParentChecking failure

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#21548]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+java9-periodic/652/consoleFull
`gradle :docs:integTest -Dtests.seed=E83A8FEF5E51AED9 -Dtests.class=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT -Dtests.method="test {yaml=reference/cat/indices/line_8}" -Dtests.security.manager=true -Dtests.locale=ur-IN -Dtests.timezone=Africa/Mogadishu`

I can't reproduce but I'm opening an issue since it might mean that we miss to close search contexts in some cases.

```
FAILURE 21.3s J0 | CircuitBreakerServiceIT.testParentChecking <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: There are still [1] in-flight contexts. The first one's creation site is listed as the cause of this exception.
   > 	at org.elasticsearch.search.MockSearchService.assertNoInFlightContext(MockSearchService.java:51)
   > 	at org.elasticsearch.test.ESTestCase.lambda$ensureAllSearchContextsReleased$2(ESTestCase.java:298)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:598)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:572)
   > 	at org.elasticsearch.test.ESTestCase.ensureAllSearchContextsReleased(ESTestCase.java:298)
   > 	at org.elasticsearch.test.ESIntegTestCase.after(ESIntegTestCase.java:1982)
   > 	at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
   > 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-ea/DelegatingMethodAccessorImpl.java:43)
   > 	at java.lang.Thread.run(java.base@9-ea/Thread.java:843)
   > 	Suppressed: java.lang.AssertionError: There are still [1] in-flight contexts. The first one's creation site is listed as the cause of this exception.
   > 		at org.elasticsearch.search.MockSearchService.assertNoInFlightContext(MockSearchService.java:51)
   > 		at org.elasticsearch.test.ESTestCase.lambda$ensureAllSearchContextsReleased$2(ESTestCase.java:298)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:586)
   > 		... 37 more
   > 	Caused by: java.lang.RuntimeException: [HmP8LGNQSi-0pUW4BB489A][cb-test][7]searchType=[DFS_QUERY_THEN_FETCH] query=[*:*]
   > 		at org.elasticsearch.search.MockSearchService.addActiveContext(MockSearchService.java:59)
   > 		at org.elasticsearch.search.MockSearchService.putContext(MockSearchService.java:78)
   > 		at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:533)
   > 		at org.elasticsearch.search.SearchService.executeDfsPhase(SearchService.java:234)
   > 		at org.elasticsearch.action.search.SearchTransportService$5.messageReceived(SearchTransportService.java:291)
   > 		at org.elasticsearch.action.search.SearchTransportService$5.messageReceived(SearchTransportService.java:288)
   > 		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
   > 		at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1386)
   > 		at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:520)
   > 		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 		at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-ea/ThreadPoolExecutor.java:1161)
   > 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-ea/ThreadPoolExecutor.java:635)
   > 		... 1 more
```

**Comment by jpountz** [comment]
I am seeing connection issues too, so it might just be due to the fact that connectivity was lost between the request that created the context and the one that was supposed to release it.

**Comment by jpountz** [comment]
This looks like it was indeed caused by a disconnection.

**Comment by tlrx** [comment]
It happens again today: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/782/consoleText

But I don't see anything related to connectivity in the log. @jpountz do you think we could add more log to verify your statement in case of this issue reproduces again?

**Comment by andy-elastic** [comment]
Another one in 6.x. Looks like the same stack trace in the original issue https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/41/consoleText
