### ISSUE TITLE
elasticsearch throw cluster:monitor/nodes/stats[n error 

### ISSUE THREAD

**Issue by GeoffreyFx** [elastic/elasticsearch#21596]
Hi All, 

This is a serious issue about elasticsearch.  

The elasticsearch log throws 'cluster:monitor/nodes/stats[n]]' error, and one of the cluster nodes response time exceeds 15s.  This error badly impact the stable of the whole system causing the search and index operations not workable. 

The ES version we use is 1.7.3. Our cluster topology is 5 primary shard , 2 replica shard, and two ES nodes are installed on each machine, total 10 es nodes on 5 machines.  And every day there is a new index created, the old index are removed. The data amount are about 12 G. 

The traffic of search & index rate are both very high. 

Anyone has this similar issue? Very appreciate your help！！

~~~~~~~~~~~~~~~~log as below~~~~~~~~~~~~~~~~~
[2016-11-16 21:31:31,847][DEBUG][action.admin.cluster.node.stats] [es147] failed to execute on node [cp2Xr5sGTSK7Qw2Ycc-r0Q]
org.elasticsearch.transport.ReceiveTimeoutTransportException: [es34][inet[/10.0.0.34:9300]][cluster:monitor/nodes/stats[n]] request_id [65940515] timed out after [15001ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:529)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2016-11-16 21:31:52,026][WARN ][transport                ] [es147] Received response for a request that has timed out, sent [65180ms] ago, timed out [50180ms] ago, action [cluster:monitor/nodes/stats[n]], node [[es34][cp2Xr5sGTSK7Qw2Ycc-r0Q][node34][inet[/10.0.0.34:9300]]], id [65928009]
[2016-11-16 21:31:56,504][WARN ][transport                ] [es147] Received response for a request that has timed out, sent [39658ms] ago, timed out [24657ms] ago, action [cluster:monitor/nodes/stats[n]], node [[es34][cp2Xr5sGTSK7Qw2Ycc-r0Q][node34][inet[/10.0.0.34:9300]]], id [65940515]

**Comment by clintongormley** [comment]
@GeoffreyFx this looks like you have nodes undergoing heavy GC, causing delays of responses.

It looks like you're using Shield, in which case I suggest opening a ticket with your support engineer.

**Comment by srikantheddla** [comment]
I'm getting the same error. The ES version we use is 2.3.3. Our cluster topology is 5 primary shard , 1 replica shard,  total 3 es nodes on 3 machines. The old indexes are not removed, is that the reason i'm getting the issue?

**Comment by tronicum** [comment]
i get this even on a 3 node kibana-elk-logstash cluster on a fairly good sized vmware machine (with docker). but i started since i tried to forward 4 GB log via filebeat into it.
