### ISSUE TITLE
Indexing operation returns UPDATED instead of CREATED (testAckedIndexing)

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#21658]
Build failure:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.0+multijob-intake/242/consoleFull

Test: `DiscoveryWithServiceDisruptionsIT#testAckedIndexing`

Document id is a fresh id (`id = Integer.toString(idGenerator.incrementAndGet());`)

Failure:
```
1> java.lang.AssertionError: expected:<CREATED> but was:<UPDATED>
  1> 	at org.junit.Assert.fail(Assert.java:88) ~[junit-4.11.jar:?]
  1> 	at org.junit.Assert.failNotEquals(Assert.java:743) ~[junit-4.11.jar:?]
  1> 	at org.junit.Assert.assertEquals(Assert.java:118) ~[junit-4.11.jar:?]
  1> 	at org.junit.Assert.assertEquals(Assert.java:144) ~[junit-4.11.jar:?]
  1> 	at org.elasticsearch.discovery.DiscoveryWithServiceDisruptionsIT.lambda$testAckedIndexing$2(DiscoveryWithServiceDisruptionsIT.java:516) ~[test/:?]
  1> 	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_111]
```

**Comment by ywelsch** [comment]
The logs show a RetryOnPrimaryException:

```
 1> [2016-11-18T14:17:11,821][TRACE][o.e.a.i.TransportIndexAction] [node_t1] received an error from node [XNNdUwGgQKG6orqmdvg6ZA] for request [org.elasticsearch.action.support.replication.TransportReplicationAction$ConcreteShardRequest@2460aa75], scheduling a retry
  1> org.elasticsearch.transport.RemoteTransportException: [node_t1][127.0.0.1:30309][indices:data/write/index[p]]
  1> Caused by: org.elasticsearch.action.support.replication.ReplicationOperation$RetryOnPrimaryException: primary shard [[test][2], node[XNNdUwGgQKG6orqmdvg6ZA], [P], s[STARTED], a[id=CXCRQ8mvRDe6BAt2YVwSSw]] was demoted while failing replica shard
  1> 	at org.elasticsearch.action.support.replication.ReplicationOperation.onPrimaryDemoted(ReplicationOperation.java:227) ~[main/:?]
  1> 	at org.elasticsearch.action.support.replication.ReplicationOperation.access$600(ReplicationOperation.java:55) ~[main/:?]
...
```

What could have had happened here (logs indicate this, but not 100% due to missing toString() on `ConcreteShardRequest`):

- indexing request is indexed into primary, replicated to one replica but not the other.
- Node with primary tries to fail the second replica, but while doing so, get's notified by the master that it's not the primary anymore.
- The node with the primary throws a RetryOnPrimaryException which routes the request to the new primary shard.
- This new primary shard is the previous replica that already has the data. The data gets reindexed (overrides the existing data) and the response gets marked as "updated" instead of "created", which is probably confusing to a user.

For index requests that are handled as part of bulk shard requests, we already have special handling of versions so that the version is reset on a RetryOnPrimaryException. Does it also encompass this scenario and do we return CREATED or UPDATED in that case?

/cc: @bleskes, @areek

**Comment by jpountz** [comment]
I just looked at a recent failure (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=oraclelinux/541/consoleFull) and see the following stack trace:

```
03:26:28   1> java.lang.NullPointerException: null
03:26:28   1> 	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320) ~[?:1.8.0_151]
03:26:28   1> 	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:1.8.0_151]
03:26:28   1> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380) ~[?:1.8.0_151]
03:26:28   1> 	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742) ~[?:1.8.0_151]
03:26:28   1> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_151]
03:26:28   1> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_151]
03:26:28   1> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_151]
03:26:28   1> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_151]
03:26:28   1> 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_151]
03:26:28   1> 	at org.elasticsearch.discovery.zen.UnicastZenPing.sendPings(UnicastZenPing.java:475) ~[main/:?]
03:26:28   1> 	at org.elasticsearch.discovery.zen.UnicastZenPing$1.doRun(UnicastZenPing.java:332) [main/:?]
03:26:28   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:635) [main/:?]
03:26:28   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [main/:?]
03:26:28   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
03:26:28   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
03:26:28   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

It surprises me because it looks like this can only happen if the map, the key mapper or the value mapper is null, and non of these options looks possible to me? Or do I miss something?

**Comment by ywelsch** [comment]
@jpountz While that failure is unrelated to the original failure for which this issue got opened, it led me to find another issue: #28405
As for the `NullPointerException`, I suspect that this is a concurrency issue due to the following preceding line:
```
Set<DiscoveryNode> nodesFromResponses = temporalResponses.stream().map(pingResponse -> {
            assert clusterName.equals(pingResponse.clusterName()) :
                "got a ping request from a different cluster. expected " + clusterName + " got " + pingResponse.clusterName();
            return pingResponse.node();
        }).collect(Collectors.toSet());
```
The `temporalResponses` field is a `ConcurrentLinkedQueue`, and the `PingResponse.node` field is not final (and there is also no other final field in this class, hence no memory barrier, see https://shipilev.net/blog/2014/safe-public-construction/#_safe_initialization), so we might end up with a  set that contains `null`. The fix is to make the fields in `PingResponse` final and move it away from the legacy `Streamable` approach. I've opened #28406 for this.

**Comment by bleskes** [comment]
We have a know issue https://github.com/elastic/elasticsearch/issues/9967 about retries semantics. Fixing this will be hard. I don't see any other option but to relax the test. I'll push that change soon.
