### ISSUE TITLE
crashed elasticsearch with bad painless scripted field

### ISSUE THREAD

**Issue by LeeDr** [elastic/elasticsearch#21764]
**Elasticsearch version**:
"number": "6.0.0-alpha1",
"build_hash": "32e6fcf",
"build_date": "2016-11-23T15:57:31.884Z",
"build_snapshot": true,
**Plugins installed**: []

**JVM version**:
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b15, mixed mode)

**OS version**:
Windows 10

**Description of the problem including expected versus actual behavior**:
I'm automating tests for scripted fields in Kibana.  While deciding what kind of painless string type result script to use I tried this;
`if (doc['response.raw'].value == 200) { return 'good'} else { return 'bad'}`

but results with a response of 200 still said 'bad'.   So I tried with the `===` thinking it was like a javascript 
`if (doc['response.raw'].value === 200) { return 'good'} else { return 'bad'}`

My understanding is that `==` does type conversions and `===` doesn't.  So if the `doc['response.raw'].value` is treated as a string, I was trying to compare it to a number and perhaps this caused the crash?

**Steps to reproduce**:
 1. I'm using dummy logstash data which is created using makelogs tool
 2. In Kibana, I create an index pattern for logstash-*
 3. Create a scripted field with the following settings;
     1. Name: pain2
     1. Language: painless
     1. Type: string (I'm assuming this is the output type from the script)
     1. Format: String
     1. Transform: Title Case
     1. Popularity: 0 (only impacts Kibana UI)
     1. Script: `if (doc['response.raw'].value === 200) { return 'good'} else { return 'bad'}`

Here's a screen shot of the Kibana page for creating the scripted field with these values populated:
![image](https://cloud.githubusercontent.com/assets/13542669/20578260/1a4ef8aa-b18c-11e6-8fbd-03044d5bff26.png)

**Provide logs (if relevant)**:
```
INFO - ? - ? - [2016-11-23T14:28:14,850][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [elasticsearch[K59JG6z][search][T#9]], exiting
INFO - ? - ? - java.lang.VerifyError: Bad type on operand stack
INFO - ? - ? - Exception Details:
INFO - ? - ? - Location:
INFO - ? - ? - org/elasticsearch/painless/Executable$Script.execute(Ljava/util/Map;Lorg/apache/lucene/search/Scorer;Lorg/elasticsearch/search/lookup/LeafDocLookup;Ljava/lang/Object;)Ljava/lang/Object; @16: if_acmpeq
INFO - ? - ? - Reason:
INFO - ? - ? - Type integer (current frame, stack[1]) is not assignable to reference type
INFO - ? - ? - Current Frame:
INFO - ? - ? - bci: @16
INFO - ? - ? - flags: { }
INFO - ? - ? - locals: { 'org/elasticsearch/painless/Executable$Script', 'java/util/Map', 'org/apache/lucene/search/Scorer', 'org/elasticsearch/search/lookup/LeafDocLookup', 'java/lang/Object' }
INFO - ? - ? - stack: { 'java/lang/Object', integer }
INFO - ? - ? - Bytecode:
INFO - ? - ? - 0x0000000: 2d12 0db9 0013 0200 ba00 1f00 0011 00c8
INFO - ? - ? - 0x0000010: a500 0703 a700 0404 9900 0612 21b0 1223
INFO - ? - ? - 0x0000020: b0
INFO - ? - ? - Stackmap Table:
INFO - ? - ? - same_frame(@23)
INFO - ? - ? - same_locals_1_stack_item_frame(@24,Integer)
INFO - ? - ? - same_frame(@30)
INFO - ? - ? - at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_73]
INFO - ? - ? - at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_73]
INFO - ? - ? - at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_73]
INFO - ? - ? - at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_73]
INFO - ? - ? - at org.elasticsearch.painless.Compiler.compile(Compiler.java:110) ~[?:?]
INFO - ? - ? - at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:171) ~[?:?]
INFO - ? - ? - at org.elasticsearch.painless.PainlessScriptEngineService$2.run(PainlessScriptEngineService.java:168) ~[?:?]
INFO - ? - ? - at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_73]
INFO - ? - ? - at org.elasticsearch.painless.PainlessScriptEngineService.compile(PainlessScriptEngineService.java:168) ~[?:?]
INFO - ? - ? - at org.elasticsearch.script.ScriptService.compileInternal(ScriptService.java:335) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.script.ScriptService.compile(ScriptService.java:231) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.script.ScriptService.search(ScriptService.java:486) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.search.SearchService.parseSource(SearchService.java:773) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.search.SearchService.createContext(SearchService.java:553) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:529) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:364) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.action.search.SearchTransportService$9.messageReceived(SearchTransportService.java:324) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.action.search.SearchTransportService$9.messageReceived(SearchTransportService.java:321) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:572) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:527) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
INFO - ? - ? - at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_73]
INFO - ? - ? - at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_73]
INFO - ? - ? - at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
server    log   [20:28:15.212] [error][elasticsearch] Request error, retrying
HEAD http://localhost:9220/ => read ECONNRESET
server    log   [20:28:15.228] [warning][elasticsearch] Unable to revive connection: http://localhost:9220/
server    log   [20:28:15.228] [warning][elasticsearch] No living connections
server    log   [20:28:15.234] [error][status][plugin:elasticsearch@6.0.0-alpha1] Status changed from green to red - 
```

**Comment by nik9000** [comment]
> My understanding is that == does type conversions and === doesn't.

`==` checks for equal objects and `===` checks for "same" objects. You probably want `doc['response.raw'].value == '200'` as a workaround.

**Comment by nik9000** [comment]
> Steps to reproduce:
...
> In Kibana

Elasticsearch bugs should usually be filed with reproduction steps using curl or sense syntax. Following your kibana steps would take me much more time to follow. In this case I'm just going to circumvent the whole thing and use the script itself

**Comment by LeeDr** [comment]
Confirmed that this works;
`if (doc['response.raw'].value == '200') { return 'good'} else { return 'bad'}`

**Comment by jdconrad** [comment]
I'm going to close this issue as a fix is in.
