### ISSUE TITLE
ES 5 Java client requires Order.term(boolean), and throws on Order.aggregation("_term", boolean)

### ISSUE THREAD

**Issue by jacobg** [elastic/elasticsearch#21782]
**Elasticsearch version**: 5

**Plugins installed**: []

**JVM version**: 8

**OS version**: OS X client, Docker service

**Description of the problem including expected versus actual behavior**:

Using Java client, run an aggregated query using `Order.aggregation("_term", boolean)`.

Expected: orders by _term
Actual: throws exception that order is invalid. Exception in logs below

In ES 2, using "_term" works fine.

Workaround: use `Order.term(boolean)`

**Provide logs (if relevant)**:

```
Caused by: org.elasticsearch.search.aggregations.AggregationExecutionException: Invalid term-aggregator order path [_term]. Unknown aggregation [_term]
	at org.elasticsearch.search.aggregations.support.AggregationPath.validate(AggregationPath.java:292)
	at org.elasticsearch.search.aggregations.bucket.terms.InternalOrder.validate(InternalOrder.java:163)
	at org.elasticsearch.search.aggregations.bucket.terms.InternalOrder.validate(InternalOrder.java:156)
	at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregator.<init>(TermsAggregator.java:178)
	at org.elasticsearch.search.aggregations.bucket.terms.AbstractStringTermsAggregator.<init>(AbstractStringTermsAggregator.java:42)
	at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator.<init>(GlobalOrdinalsStringTermsAggregator.java:78)
	at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory$ExecutionMode$2.create(TermsAggregatorFactory.java:250)
	at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.doCreateInternal(TermsAggregatorFactory.java:167)
	at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:55)
	at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:225)
	at org.elasticsearch.search.aggregations.AggregatorFactories.createTopLevelAggregators(AggregatorFactories.java:102)
	at org.elasticsearch.search.aggregations.AggregationPhase.preProcess(AggregationPhase.java:61)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:104)
	at org.elasticsearch.indices.IndicesService.lambda$loadIntoContext$17(IndicesService.java:1116)
	at org.elasticsearch.indices.IndicesService.lambda$cacheShardLevelResult$19(IndicesService.java:1186)
	at org.elasticsearch.indices.IndicesRequestCache$Loader.load(IndicesRequestCache.java:151)
	at org.elasticsearch.indices.IndicesRequestCache$Loader.load(IndicesRequestCache.java:134)
	at org.elasticsearch.common.cache.Cache.computeIfAbsent(Cache.java:385)
	at org.elasticsearch.indices.IndicesRequestCache.getOrCompute(IndicesRequestCache.java:117)
	at org.elasticsearch.indices.IndicesService.cacheShardLevelResult(IndicesService.java:1192)
	at org.elasticsearch.indices.IndicesService.loadIntoContext(IndicesService.java:1115)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:236)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:251)
	at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$6(SearchTransportService.java:276)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:520)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by clintongormley** [comment]
Yes.  This is mentioned in the breaking changes docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_java_api_changes.html#_searchsourcebuilder

**Comment by jacobg** [comment]
Thanks Clinton. Sorry I don't see a reference to it in the breaking changes doc. Is it implied from a statement made in that document? If so, it might help to make it clearer for people who aren't familar with the implementation details.

**Comment by clintongormley** [comment]
@jacobg yeah, it's in that section i linked to:

> SearchSourceBuilderedit
> All methods which take an XContentBuilder, BytesReference Map<String, Object> or bytes[] have been removed in favor of providing the relevant builder object for that feature (e.g. HighlightBuilder, AggregationBuilder, SuggestBuilder) . This means that all search requests can now be validated at call time which results in much clearer errors.

I realise that from that brief description it may not be obvious which classes were affected. But search parsing underwent a massive rewrite for 5.0, so it'd be wise to expect that many classes are affected :)

**Comment by jacobg** [comment]
Ok thanks. At least if someone has the same issue I did, they'll find it by searching my comments on this issue.  :)
