### ISSUE TITLE
x-pack 5.0.1 ，login  has failed

### ISSUE THREAD

**Issue by a5601564** [elastic/elasticsearch#21795]
**Elasticsearch version 5.0.1:

**Plugins installed X-pack 5.0.1:

**JVM version 1.8.0.65:

**OS version centos 7.2:

**Description of the problem including expected versus actual behavior

i fallow someone passage ，that
x-pack安装之后有一个超级用户elastic ，其默认的密码是changeme

it doesn't work；

Provide logs (if relevant):
Elasticsearch

[2016-11-25T17:35:12,739][INFO ][o.e.x.m.e.Exporters ] [lmwGdLM] skipping exporter [default_local] as it isn't ready yet
[2016-11-25T17:35:12,739][ERROR][o.e.x.m.AgentService ] [lmwGdLM] exception when exporting documents
org.elasticsearch.xpack.monitoring.exporter.ExportException: exporters are either not ready or faulty
at org.elasticsearch.xpack.monitoring.exporter.Exporters.export(Exporters.java:188) ~[x-pack-5.0.1.jar:5.0.1]
at org.elasticsearch.xpack.monitoring.AgentService$ExportingWorker.run(AgentService.java:208) [x-pack-5.0.1.jar:5.0.1]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]

kibana
log [09:26:31.950] [error][status][ui settings] Status changed from uninitialized to red - Elasticsearch plugin is red
Status changed from uninitialized to red - Elasticsearch plugin is red

Describe the feature:
no details ，after the fallowing of official website and someone passage ，this happen 。

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
