### ISSUE TITLE
Painless EqualsTests fails

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#21801]
The following tests sometimes fails on CI:
- org.elasticsearch.painless.EqualsTests.testBranchEqualsDefAndPrimitive
- org.elasticsearch.painless.EqualsTests.testBranchNotEqualsDefAndPrimitive 

See 
http://build-us-00.elastic.co/job/es_core_master_windows-2012-r2/4296/

<details>

Suite: org.elasticsearch.painless.EqualsTests
  2> REPRODUCE WITH: gradle :modules:lang-painless:test -Dtests.seed=B924F6F1A1067BD7 -Dtests.class=org.elasticsearch.painless.EqualsTests -Dtests.method="testBranchNotEqualsDefAndPrimitive" -Dtests.es.logger.level=DEBUG -Dtests.assertion.disabled=org.elasticsearch -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=1024m -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:+UseCompressedOops -XX:+AggressiveOpts" -Dtests.locale=es-CO -Dtests.timezone=Australia/Yancowinna

FAILURE 0.02s J3 | EqualsTests.testBranchNotEqualsDefAndPrimitive <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<true> but was:<false>
   > 	at __randomizedtesting.SeedInfo.seed([B924F6F1A1067BD7:C01A301A262FF1C3]:0)
   > 	at org.elasticsearch.painless.EqualsTests.testBranchNotEqualsDefAndPrimitive(EqualsTests.java:151)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> REPRODUCE WITH: gradle :modules:lang-painless:test -Dtests.seed=B924F6F1A1067BD7 -Dtests.class=org.elasticsearch.painless.EqualsTests -Dtests.method="testBranchEqualsDefAndPrimitive" -Dtests.es.logger.level=DEBUG -Dtests.assertion.disabled=org.elasticsearch -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=1024m -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:+UseCompressedOops -XX:+AggressiveOpts" -Dtests.locale=es-CO -Dtests.timezone=Australia/Yancowinna

FAILURE 0.01s J3 | EqualsTests.testBranchEqualsDefAndPrimitive <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<false> but was:<true>
   > 	at __randomizedtesting.SeedInfo.seed([B924F6F1A1067BD7:2022DE1D46A4EABF]:0)
   > 	at org.elasticsearch.painless.EqualsTests.testBranchEqualsDefAndPrimitive(EqualsTests.java:134)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> NOTE: leaving temporary files on disk at: C:\jenkins\workspace\es_core_master_windows-2012-r2\modules\lang-painless\build\testrun\test\J3\temp\org.elasticsearch.painless.EqualsTests_B924F6F1A1067BD7-001

  2> NOTE: test params are: codec=Asserting(Lucene62): {}, docValues:{}, maxPointsInLeafNode=1446, maxMBSortInHeap=6.240739765052881, sim=ClassicSimilarity, locale=es-CO, timezone=Australia/Yancowinna

  2> NOTE: Windows Server 2012 R2 6.3 amd64/Oracle Corporation 1.8.0_60 (64-bit)/cpus=8,threads=1,free=864776112,total=1037959168

  2> NOTE: All tests run in this JVM: [SubtractionTests, XorTests, NoSemiColonTests, PromotionTests, ListTests, AugmentationTests, CastTests, EqualsTests]

Completed [27/45] on J3 in 0.19s, 10 tests, 2 failures <<< FAILURES!
</details>

**Comment by tlrx** [comment]
@jdconrad I'm assigning this to you since you worked on this recently
