### ISSUE TITLE
Failed to start elasticsearch after reinstall

### ISSUE THREAD

**Issue by tianchao-haohan** [elastic/elasticsearch#21818]
**Elasticsearch version**: 5.0.0-alpha1

**Plugins installed**: []

**JVM version**:1.8.0_60

**OS version**:SUSE Enterprise 12

**Description of the problem including expected versus actual behavior**:
remove 5.0.0-alpha1 with rpm -ev. then install elasticsearch-2.4.1. Failed to start elasticsearch

**Steps to reproduce**:
 1. Install elasticsearch-5.0.0-alpha1
 2. uninstall elasticsearch-5.0.0-alpha1
 3. install elasticsearch-2.4.1
 4. start elasticsearch with sudo systemctl start   elasticsearch 
 5. ps -ef | grep elastic
elastic+  6400     1  0 03:17 pts/1    00:00:00 /usr/bin/java -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Djna.nosys=true -Des.path.home=/usr/share/elasticsearch -cp /usr/share/elasticsearch/lib/elasticsearch-2.4.1.jar:/usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch start -d -p /var/run/elasticsearch.pid --default.config=/etc/elasticsearch/elasticsearch.yml --default.path.home=/usr/share/elasticsearch --default.path.logs=/var/log/elasticsearch --default.path.data=/var/lib/elasticsearch --default.path.work=/tmp/elasticsearch --default.path.conf=/etc/elasticsearch                                                                                                           
 6. /bin/netstat -nap | grep 9200, nothing could be found
 7. No logs under /var/log/elasticsearch
 8. Failed to "curl -XGET localhost:9200", network host in elasticsearch.yml has been configured to 0.0.0.0
**Provide logs (if relevant)**:

**Describe the feature**:  jstack the pid:
"Signal Dispatcher" #5 daemon prio=9 os_prio=0 tid=0x00007fcfc0172000 nid=0x4dd0 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Surrogate Locker Thread (Concurrent GC)" #4 daemon prio=9 os_prio=0 tid=0x00007fcfc0170800 nid=0x4dcf waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007fcfc0134000 nid=0x4dce in Object.wait() [0x00007fcf734fb000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000c00070b8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        - locked <0x00000000c00070b8> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007fcfc0132000 nid=0x4dcd in Object.wait() [0x00007fcf735fc000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000c0006af8> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
        - locked <0x00000000c0006af8> (a java.lang.ref.Reference$Lock)

"main" #1 prio=5 os_prio=0 tid=0x00007fcfc0009800 nid=0x4db9 runnable [0x00007fcfc7955000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.fs.UnixNativeDispatcher.stat0(Native Method)
        at sun.nio.fs.UnixNativeDispatcher.stat(UnixNativeDispatcher.java:286)
        at sun.nio.fs.UnixFileAttributes.get(UnixFileAttributes.java:70)
        at sun.nio.fs.UnixFileStore.devFor(UnixFileStore.java:55)
        at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:70)
        at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:48)
        at sun.nio.fs.LinuxFileSystem.getFileStore(LinuxFileSystem.java:112)
        at sun.nio.fs.UnixFileSystem$FileStoreIterator.readNext(UnixFileSystem.java:213)
        at sun.nio.fs.UnixFileSystem$FileStoreIterator.hasNext(UnixFileSystem.java:224)
        - locked <0x00000000c0b74e48> (a sun.nio.fs.UnixFileSystem$FileStoreIterator)
        at org.apache.lucene.util.IOUtils.getFileStore(IOUtils.java:515)
        at org.apache.lucene.util.IOUtils.spinsLinux(IOUtils.java:459)
        at org.apache.lucene.util.IOUtils.spins(IOUtils.java:448)
        at org.elasticsearch.env.ESFileStore.<init>(ESFileStore.java:57)
        at org.elasticsearch.env.Environment.<clinit>(Environment.java:90)
        at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:81)
        at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:107)
        at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:100)
        at org.elasticsearch.bootstrap.BootstrapCLIParser.<init>(BootstrapCLIParser.java:48)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:242)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

"VM Thread" os_prio=0 tid=0x00007fcfc012d000 nid=0x4dcc runnable 

"Gang worker#0 (Parallel GC Threads)" os_prio=0 tid=0x00007fcfc001a800 nid=0x4dba runnable 

"Gang worker#1 (Parallel GC Threads)" os_prio=0 tid=0x00007fcfc001c000 nid=0x4dbb runnable

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
