### ISSUE TITLE
Java native custom plugin issue with ES 5.0

### ISSUE THREAD

**Issue by rboorugu** [elastic/elasticsearch#21832]
**Elasticsearch version**:

**Plugins installed**: []

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

We use a java plugin with elastic search which implements Map Reduce, have made necessary changes to load it in ES 5.0, but am not able to find an answer for one of it - detailed description below.

Below is code for INIT which used to work fine in ES2.0 which initializes resultIds, citedIds for some reason i am not able to access these variables in MapScript - i get a null pointer exception. 

 public static class ForeciteInitScriptFactory implements NativeScriptFactory {

        @Override
        @SuppressWarnings("unchecked")
        public ExecutableScript newScript(final Map<String, Object> params) {
            return new AbstractExecutableScript() {
                @Override
                public Object run() {
                    Map<String, Object> agg = new HashMap<String, Object>();
                    agg.put("resultIds", new ArrayList<Integer>());
                    agg.put("citedIds", new ArrayList<Integer>());                    
                    params.put("_agg", agg);
                    return null;
                }
            };
        }

        @Override
        public boolean needsScores() {
            return false;
        }
    }    

I've made some changes  to make it work in 5.0 (changes below) but i am still not sure why above is not working - i basically removed everything from AbstractExecutableScript and put it inside of newScript?

    public class ForeciteInitScriptFactory implements NativeScriptFactory {

        @Override
        @SuppressWarnings("unchecked")
        public ExecutableScript newScript(final Map<String, Object> params) {
            Map<String, Object> agg = new HashMap<String, Object>();
                    agg.put("resultIds", new ArrayList<Integer>());
                    agg.put("citedIds", new ArrayList<Integer>());
                    params.put("_agg", agg);
            /*Logger logger = LogManager.getLogger(ForecitePlugin.class.getName());
                    logger.info("logging start here IntScript before run: RB");
                    logger.info(params);*/
                    //return params;
            return new AbstractExecutableScript() {
                 @Override
                public Object run() {                         
                    return null;
                }
            };
        }

        @Override
        public boolean needsScores() {
            return false;
        }

		@Override
		public String getName() {
			// TODO Auto-generated method stub
			return "forecite_init";
		}
    }

**Comment by rjernst** [comment]
>  i get a null pointer exception

Can you please share the stack trace?

**Comment by rboorugu** [comment]
hope below helps.

Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, source={
  "query" : {
    "function_score" : {
      "query" : {
        "bool" : {
          "should" : [
            {
              "term" : {
                "FullCitation" : {
                  "value" : "us",
                  "boost" : 1.0
                }
              }
            },
            {
              "term" : {
                "Content" : {
                  "value" : "us",
                  "boost" : 1.0
                }
              }
            }
          ],
          "disable_coord" : false,
          "adjust_pure_negative" : true,
          "boost" : 1.0
        }
      },
      "functions" : [ ],
      "score_mode" : "multiply",
      "max_boost" : 3.4028235E38,
      "boost" : 1.0
    }
  },
  "stored_fields" : "FastcaseId",
  "aggregations" : {
    "forecite" : {
      "scripted_metric" : {
        "init_script" : {
          "inline" : "forecite_init",
          "lang" : "native"
        },
        "map_script" : {
          "inline" : "forecite_map",
          "lang" : "native"
        },
        "combine_script" : {
          "inline" : "forecite_combine",
          "lang" : "native"
        },
        "reduce_script" : {
          "inline" : "forecite_reduce",
          "lang" : "native"
        },
        "params" : {
          "take" : 3,
          "skip" : 0
        }
      }
    }
  },
  "highlight" : {
    "fields" : {
      "Content" : {
        "pre_tags" : [
          "<span class=\"highlight\">"
        ],
        "post_tags" : [
          "</span>"
        ],
        "fragment_size" : 300,
        "number_of_fragments" : 1,
        "type" : "plain"
      }
    }
  },
  "ext" : { }
}}]
org.elasticsearch.transport.RemoteTransportException: [6KDxkRO][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: java.lang.NullPointerException
        at com.fastcase.elasticsearch.plugins.forecite.ForecitePlugin$ForeciteMapScriptFactory.newScript(ForecitePlugin.java:84) ~[?:?]
        at org.elasticsearch.script.NativeScriptEngineService.search(NativeScriptEngineService.java:75) ~[elasticsearch-5.0.0.jar:5.0.0]
        at org.elasticsearch.script.ScriptService.search(ScriptService.java:499) ~[elasticsearch-5.0.0.jar:5.0.0]
        at org.elasticsearch.index.query.QueryShardContext.lambda$getLazySearchScript$2(QueryShardContext.java:358) ~[elasticsearch-5.0.0.jar:5.0.0]
        at org.elasticsearch.search.aggregations.metrics.scripted.ScriptedMetricAggregatorFactory.createInternal(ScriptedMetricAggregatorFactory.java:76) ~[elasticsearch-5.0.0.jar:5.0.0]
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:225) ~[elasticsearch-5.0.0.jar:5.0.0]
        at org.elasticsearch.search.aggregations.AggregatorFactories.createTopLevelAggregators(AggregatorFactories.java:102) ~[elasticsearch-5.0.0.jar:5.0.0]
        at org.elasticsearch.search.aggregations.AggregationPhase.preProcess(AggregationPhase.java:61) ~[elasticsearch-5.0.0.jar:5.0.0]
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:104) ~[elasticsearch-5.0.0.jar:5.0.0]
        at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:238) ~[elasticsearch-5.0.0.jar:5.0.0]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:251) ~[elasticsearch-5.0.0.jar:5.0.0]
        at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$6(SearchTransportService.java:276) ~[elasticsearch-5.0.0.jar:5.0.0]
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-5.0.0.jar:5.0.0]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.0.0.jar:5.0.0]
        at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:548) [elasticsearch-5.0.0.jar:5.0.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) [elasticsearch-5.0.0.jar:5.0.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.0.0.jar:5.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]

**Comment by s1monw** [comment]
@rboorugu what is in ForecitePlugin.java:84 ? can you provide that java file (the entire file?)

**Comment by rjernst** [comment]
Looks like it comes from [here](https://github.com/neolee11/exp-cloud-formation/blob/master/elasticsearch-forecite-script/src/main/java/com/fastcase/elasticsearch/plugins/forecite/ForecitePlugin.java#L84).

The problem is your init script replaces `_agg` in params. That variable is supplied by the script metric agg setup, and should be modified, but not overwritten. The reason this works when modifying params outside of executing the script is `_agg` then becomes part of the params passed into the scripted metric construction.

The correct newScript method for your init script would be something like this:
```
    @Override
    @SuppressWarnings("unchecked")
    public ExecutableScript newScript(final Map<String, Object> params) {   
        return new AbstractExecutableScript() {
             @Override
            public Object run() {            
                Map<String, Object> agg = (Map<String, Object>)params.get("_agg");
                agg.put("resultIds", new ArrayList<Integer>());
                agg.put("citedIds", new ArrayList<Integer>());         
                return null;
            }
        };
    }
```
