### ISSUE TITLE
DeleteResponse#toString having trouble in 5.0+

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#21872]
Reported [here](https://discuss.elastic.co/t/preparedelete-returns-jsongenerator-error/67547). [gist](https://gist.github.com/anonymous/a7a898f1446683bb95bf31bc1b23a898) with the stacktrace.

I haven't confirmed it myself but the report looks fairly conclusive.

**Comment by jasontedor** [comment]
I think this is already fixed by #21319. Note the key part of the stack trace:

```
Error building toString out of XContent: com.fasterxml.jackson.core.JsonGenerationException: Can not write a field name, expecting a value
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1886)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeFieldName(UTF8JsonGenerator.java:185)
	at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.writeFieldName(JsonXContentGenerator.java:187)
	at org.elasticsearch.common.xcontent.XContentBuilder.field(XContentBuilder.java:244)
	at org.elasticsearch.common.xcontent.XContentBuilder.startObject(XContentBuilder.java:220)
	at org.elasticsearch.action.support.replication.ReplicationResponse$ShardInfo.toXContent(ReplicationResponse.java:148)
	at org.elasticsearch.common.Strings.toString(Strings.java:901)
	at org.elasticsearch.common.Strings.toString(Strings.java:887)
	at org.elasticsearch.action.support.replication.ReplicationResponse$ShardInfo.toString(ReplicationResponse.java:165)
```

This was fixed in 5.0.1.

**Comment by Vivek-Patil** [comment]
@jasontedor @clintongormley 
I am getting the same error while I am trying to get a document from ES 5.2.2

code snippet: 
GetResponse getFields = client.prepareGet(index, esType.getType(), id).get();

Elastic search Client Library version: 5.2.2

Error building toString out of XContent: com.fasterxml.jackson.core.JsonGenerationException: Can not start an object, expecting field name (context: Object)
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1897)
	at com.fasterxml.jackson.core.json.JsonGeneratorImpl._reportCantWriteValueExpectName(JsonGeneratorImpl.java:244)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._verifyValueWrite(UTF8JsonGenerator.java:1027)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeStartObject(UTF8JsonGenerator.java:313)
	at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.writeStartObject(JsonXContentGenerator.java:161)
	at org.elasticsearch.common.xcontent.XContentBuilder.startObject(XContentBuilder.java:217)
	at org.elasticsearch.index.get.GetResult.toXContent(GetResult.java:251)
	at org.elasticsearch.action.get.GetResponse.toXContent(GetResponse.java:158)
	at org.elasticsearch.common.Strings.toString(Strings.java:901)
	at org.elasticsearch.action.get.GetResponse.toString(GetResponse.java:197)
	at com.crowdfire.payments.dao.PayloadDumpDao.getPayloadDump(PayloadDumpDao.java:53)
	at com.crowdfire.payments.service.PayloadDumpService.getPayloadDump(PayloadDumpService.java:58)
	at com.crowdfire.payments.service.PayloadDumpServiceTest.createPayloadDump(PayloadDumpServiceTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by cbuescher** [comment]
@Vivek-Patil that is already tracked in #23505, and it is fixed in the next minor release. Should only happen on 5.2.x
