### ISSUE TITLE
java.lang.NoClassDefFoundError at service start

### ISSUE THREAD

**Issue by nono1974** [elastic/elasticsearch#21957]
**Elasticsearch version**: 5.0.2

**Plugins installed**: kibana, beat

**JVM version**: 1.8.0.122

**OS version**: windows server 2012 R2 64bits

**Description of the problem including expected versus actual behavior**:

I have update with the last version of elasticsearch-service.bat in order to fix (JAVA_HOME) bug and try to install and start service mode. The elasticsearch.bat is working but the service on is getting error and not start the service with this error :

2016-12-04 00:38:35 Commons Daemon procrun stderr initialized
java.lang.NoClassDefFoundError: org/elasticsearch/bootstrap/Elasticsearch
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.bootstrap.Elasticsearch
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Exception in thread "main" 

**Steps to reproduce**:
 1. run elasticsearch-service.bat install
 2. 
 3.

**Provide logs (if relevant)**:
2016-12-04 00:38:35 Commons Daemon procrun stderr initialized
java.lang.NoClassDefFoundError: org/elasticsearch/bootstrap/Elasticsearch
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.bootstrap.Elasticsearch
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Exception in thread "main"

**Describe the feature**:

**Comment by jasontedor** [comment]
I think that your installation is busted. I recommend removing the service (`elasticsearch-service.bat remove`), reinstalling from the zip distribution, and reinstalling the service (`elasticsearch-service.bat remove`). If the first step fails, continue with reinstalling from the zip distribution, then remove and reinstall the service from the new install. Beyond that, please ask additional questions on the [forum](https://discuss.elastic.co); Elastic reserves GitHub for verified bug reports and feature requests.
