### ISSUE TITLE
NoNodesAvailable from java client

### ISSUE THREAD

**Issue by nugusbayevkk** [elastic/elasticsearch#21966]
Hello guys.
I have problem with connection from java client to elasticsearch.
I install on linux rhel 7.1 elasticsearch version 5.0.2(and 5.0.1- 2 version, mad to try) .
Exuciting of the follow command return this infoirmation:
elasticsearch-5.0.2]$ curl localhost:9200
{
  "name" : "node-3",
  "cluster_name" : "eventhandler-test-db",
  "cluster_uuid" : "xb38NQ14SNuyh1eUKA0LbA",
  "version" : {
    "number" : "5.0.2",
    "build_hash" : "f6b4951",
    "build_date" : "2016-11-24T10:07:18.101Z",
    "build_snapshot" : false,
    "lucene_version" : "6.2.1"
  },
  "tagline" : "You Know, for Search"

then, in java project i am using next libraries: elasticsearch-5.0.2.jar,  transport-5.0.2.jar, and lucene-*-6.2.1.kar.

 TransportClient client = new PreBuiltTransportClient(Settings.EMPTY); 
  client.addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("SERVER_NAME"), 9300));
  System.out.println("OOO this not showed"+client.connectedNodes());

and my elasticsearch configuration:
elasticsearch-5.0.2]$ cat ./config/elasticsearch.yml |grep -v "#" |grep -v "^$"

cluster.name: eventhandler-test-db
node.name: node-3
node.master: true
node.data: true
path.logs: /data/nugusbayev_repo/logs/elasticsearch/node3
network.publish_host: SERVER_NAME
network.bind_host: 0.0.0.0
discovery.zen.ping.unicast.hosts: ["127.0.0.1", "localhost","SERVER_NAME"]

and i have next exceptions:

 cause
 NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{luQtmBg3T6OBJ4IYKBSIKg}{IP_ADRES OF MY SERVER}{IP_ADRESS:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:328)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:226)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:339)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:403)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:62)
	at kz.ksp.dsm.spring.service.EventServiceImpl.getEventsStats(EventServiceImpl.java:164)

Help me please, because i cannot fix this problem. may be i don't inderstood something. 
I need in help. Thanks a lot of .

**Comment by dadoonet** [comment]
We will be happy to help you on discuss.elastic.co.

This space is only for confirmed bugs.

Thanks

**Comment by nugusbayevkk** [comment]
Here:
TransportClient client = new PreBuiltTransportClient(Settings.EMPTY);
client.addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("SERVER_NAME"), 9300));
System.out.println("OOO this not showed"+client.connectedNodes());
 i tried to use next Settings:
Settings settings = Settings.builder().put("cluster.name", "eventhandler-test-db").build();
  TransportClient client = new PreBuiltTransportClient(settings); 

But it no helped me.

**Comment by nugusbayevkk** [comment]
Ok, Thanks you. I will open issue there.
