### ISSUE TITLE
Terminate node on repeated iSCSI connection errors to underlying storage

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#21986]
1.7.x

Currently, when there are repeated iSCSI connection errors thrown by the kernel:

```
Dec  1 12:55:13 node_name iscsid: Kernel reported iSCSI connection 4:0 error (1020 - ISCSI_ERR_TCP_CONN_CLOSE: TCP connection closed) state (3)
Dec  1 12:55:13 node_name iscsid: Kernel reported iSCSI connection 3:0 error (1020 - ISCSI_ERR_TCP_CONN_CLOSE: TCP connection closed) state (3)
Dec  1 12:55:15 node_name iscsid: connect to 10.7.15.14:3260 failed (Connection refused)
Dec  1 12:55:16 node_name iscsid: connect to 10.7.15.13:3260 failed (Connection refused)
Dec  1 12:55:19 node_name iscsid: connect to 10.7.15.14:3260 failed (Connection refused)
Dec  1 12:55:19 node_name iscsid: connect to 10.7.15.13:3260 failed (Connection refused)
Dec  1 12:55:55 node_name iscsid: connect to 10.7.15.14:3260 failed (No route to host)
Dec  1 12:55:56 node_name iscsid: connect to 10.7.15.13:3260 failed (No route to host)
Dec  1 12:56:01 node_name iscsid: connect to 10.7.15.14:3260 failed (No route to host)
Dec  1 12:56:02 node_name iscsid: connect to 10.7.15.13:3260 failed (No route to host)
Dec  1 12:56:07 node_name iscsid: connect to 10.7.15.14:3260 failed (No route to host)
Dec  1 12:56:08 node_name iscsid: connect to 10.7.15.13:3260 failed (No route to host)
Dec  1 12:56:14 node_name iscsid: connect to 10.7.15.14:3260 failed (No route to host)
Dec  1 12:56:14 node_name iscsid: connect to 10.7.15.13:3260 failed (No route to host)
Dec  1 12:56:20 node_name iscsid: connect to 10.7.15.14:3260 failed (No route to host)
Dec  1 12:56:20 node_name iscsid: connect to 10.7.15.13:3260 failed (No route to host)
Dec  1 12:56:26 node_name iscsid: connect to 10.7.15.14:3260 failed (No route to host)
Dec  1 12:56:26 node_name iscsid: connect to 10.7.15.13:3260 failed (No route to host)
Dec  1 12:56:32 node_name iscsid: connect to 10.7.15.14:3260 failed (No route to host)
Dec  1 12:56:32 node_name iscsid: connect to 10.7.15.13:3260 failed (No route to host)
Dec  1 12:56:38 node_name iscsid: connect to 10.7.15.14:3260 failed (No route to host)
Dec  1 12:56:38 node_name iscsid: connect to 10.7.15.13:3260 failed (No route to host)
Dec  1 12:56:44 node_name iscsid: connect to 10.7.15.14:3260 failed (No route to host)
Dec  1 12:56:44 node_name iscsid: connect to 10.7.15.13:3260 failed (No route to host)
Dec  1 12:56:50 node_name iscsid: connect to 10.7.15.14:3260 failed (No route to host)
Dec  1 12:56:50 node_name iscsid: connect to 10.7.15.13:3260 failed (No route to host)
Dec  1 12:56:56 node_name iscsid: connect to 10.7.15.14:3260 failed (No route to host)
Dec  1 12:56:56 node_name iscsid: connect to 10.7.15.13:3260 failed (No route to host)
Dec  1 12:57:02 node_name iscsid: connect to 10.7.15.14:3260 failed (No route to host)
Dec  1 12:57:03 node_name iscsid: connect to 10.7.15.13:3260 failed (No route to host)
Dec  1 12:57:08 node_name iscsid: connect to 10.7.15.14:3260 failed (No route to host)
Dec  1 12:57:09 node_name iscsid: connect to 10.7.15.13:3260 failed (No route to host)
Dec  1 12:57:12 node_name kernel: session4: session recovery timed out after 120 secs
Dec  1 12:57:12 node_name multipathd: 8:64: mark as failed
Dec  1 12:57:12 node_name multipathd: mpatha: remaining active paths: 3
Dec  1 12:57:12 node_name kernel: sd 14:0:0:1: rejecting I/O to offline device
```
[messages_c.txt.zip](https://github.com/elastic/elasticsearch/files/632154/messages_c.txt.zip)

The master node will throw repeated timeout errors on monitoring apis:

```
[2016-12-01 13:32:21,896][DEBUG][action.admin.cluster.node.stats] [master_node] failed to execute on node [REYaXyK1S3CLWL_3SaMxww]
org.elasticsearch.transport.ReceiveTimeoutTransportException: [problem_node][inet[problem_node/10.7.3.78:9300]][cluster:monitor/nodes/stats[n]] request_id [344895239] timed out after [15000ms]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:529)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

The problem_node itself does not write any log entries out.  A thread dump on the node shows a lot of blocked threads.

[ES_ThreadDump.txt.zip](https://github.com/elastic/elasticsearch/files/632144/ES_ThreadDump.txt.zip)

The master_node does not end up dropping the problem node from the cluster and the problem node has to be shutdown manually.  It will be helpful for admins if the ES node can kill itself so that admins can tell quite quickly that something has gone wrong.

**Comment by jasontedor** [comment]
If these errors are not being delivered to Elasticsearch, and it appears that they are not, there is not much reasonable that we can do here.

**Comment by clintongormley** [comment]
Closing as can't fix
