### ISSUE TITLE
ExceptionInInitializerError: AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")

### ISSUE THREAD

**Issue by petrikoz** [elastic/elasticsearch#21992]
I have error after start cluster.
I also tried run elasticsearch with Docker: work nice.

**Elasticsearch version**: 5.0.2

**Plugins installed**: [I don't know. I just install Elasticsearch]

**JVM version**:
```
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
```

**OS version**: Ubuntu 16.04.1 LTS

**Description of the problem including expected versus actual behavior**:
Cluster fail with message:
```
fatal error in thread [main], exiting
```
See logs below for more information.

**Steps to reproduce**:
1. I tried install from official docs and from artifacts.elastic.co (with `apt`).
    Set `-Xms512m` and `-Xmx512m` (I have only 2 G physical memory and need it for other services) in `/etc/elasticsearch/jvm.options`.
2. Started elasticsearch with `/etc/init.d/elasticsearch start`.
3. Got error.

**Provide logs (if relevant)**:
```
[2016-12-06T11:55:16,208][INFO ][o.e.n.Node               ] [] initializing ...
[2016-12-06T11:55:16,799][INFO ][o.e.e.NodeEnvironment    ] [ObwiA7t] using [1] data paths, mounts [[/ (/dev/mapper/petr--test--server--vg-root)]], net usable_space [59.3gb], net total_space [71gb], spins? [possibly], types [ext4]
[2016-12-06T11:55:16,800][INFO ][o.e.e.NodeEnvironment    ] [ObwiA7t] heap size [495.3mb], compressed ordinary object pointers [true]
[2016-12-06T11:55:16,810][INFO ][o.e.n.Node               ] [ObwiA7t] node name [ObwiA7t] derived from node ID; set [node.name] to override
[2016-12-06T11:55:16,866][INFO ][o.e.n.Node               ] [ObwiA7t] version[5.0.2], pid[3288], build[f6b4951/2016-11-24T10:07:18.101Z], OS[Linux/4.4.0-51-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/9-internal/9-i
nternal+0-2016-04-14-195246.buildd.src]
[2016-12-06T11:55:21,618][INFO ][o.e.p.PluginsService     ] [ObwiA7t] loaded module [aggs-matrix-stats]
[2016-12-06T11:55:21,619][INFO ][o.e.p.PluginsService     ] [ObwiA7t] loaded module [ingest-common]
[2016-12-06T11:55:21,619][INFO ][o.e.p.PluginsService     ] [ObwiA7t] loaded module [lang-expression]
[2016-12-06T11:55:21,619][INFO ][o.e.p.PluginsService     ] [ObwiA7t] loaded module [lang-groovy]
[2016-12-06T11:55:21,619][INFO ][o.e.p.PluginsService     ] [ObwiA7t] loaded module [lang-mustache]
[2016-12-06T11:55:21,619][INFO ][o.e.p.PluginsService     ] [ObwiA7t] loaded module [lang-painless]
[2016-12-06T11:55:21,620][INFO ][o.e.p.PluginsService     ] [ObwiA7t] loaded module [percolator]
[2016-12-06T11:55:21,620][INFO ][o.e.p.PluginsService     ] [ObwiA7t] loaded module [reindex]
[2016-12-06T11:55:21,620][INFO ][o.e.p.PluginsService     ] [ObwiA7t] loaded module [transport-netty3]
[2016-12-06T11:55:21,620][INFO ][o.e.p.PluginsService     ] [ObwiA7t] loaded module [transport-netty4]
[2016-12-06T11:55:21,621][INFO ][o.e.p.PluginsService     ] [ObwiA7t] no plugins loaded
[2016-12-06T11:55:24,503][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [main], exiting
java.lang.ExceptionInInitializerError
        at org.apache.lucene.analysis.miscellaneous.StemmerOverrideFilter$Builder.build(StemmerOverrideFilter.java:205) ~[lucene-analyzers-common-6.2.1.jar:6.2.1 43ab70147eb494324a1410f7a9f16a896a59bc6f - shalin - 2016-09-15 05:15:51]
        at org.apache.lucene.analysis.nl.DutchAnalyzer.<init>(DutchAnalyzer.java:133) ~[lucene-analyzers-common-6.2.1.jar:6.2.1 43ab70147eb494324a1410f7a9f16a896a59bc6f - shalin - 2016-09-15 05:15:51]
        at org.apache.lucene.analysis.nl.DutchAnalyzer.<init>(DutchAnalyzer.java:106) ~[lucene-analyzers-common-6.2.1.jar:6.2.1 43ab70147eb494324a1410f7a9f16a896a59bc6f - shalin - 2016-09-15 05:15:51]
        at org.elasticsearch.indices.analysis.PreBuiltAnalyzers$20.create(PreBuiltAnalyzers.java:246) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.indices.analysis.PreBuiltAnalyzers.getAnalyzer(PreBuiltAnalyzers.java:487) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.index.analysis.AnalysisRegistry$PrebuiltAnalysis.<init>(AnalysisRegistry.java:335) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.index.analysis.AnalysisRegistry$PrebuiltAnalysis.<init>(AnalysisRegistry.java:320) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.index.analysis.AnalysisRegistry.<init>(AnalysisRegistry.java:55) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.indices.analysis.AnalysisModule.<init>(AnalysisModule.java:175) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.node.Node.<init>(Node.java:304) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.node.Node.<init>(Node.java:217) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:196) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:196) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:291) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.cli.Command.main(Command.java:62) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.0.2.jar:5.0.2]
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
        at java.security.AccessControlContext.checkPermission(java.base@9-internal/AccessControlContext.java:468) ~[?:?]
        at java.security.AccessController.checkPermission(java.base@9-internal/AccessController.java:894) ~[?:?]
        at java.lang.SecurityManager.checkPermission(java.base@9-internal/SecurityManager.java:541) ~[?:?]
        at java.lang.Class.checkMemberAccess(java.base@9-internal/Class.java:2584) ~[?:?]
        at java.lang.Class.getDeclaredFields(java.base@9-internal/Class.java:2092) ~[?:?]
        at org.apache.lucene.util.RamUsageEstimator$1.run(RamUsageEstimator.java:339) ~[lucene-core-6.2.1.jar:6.2.1 43ab70147eb494324a1410f7a9f16a896a59bc6f - shalin - 2016-09-15 05:15:20]
        at org.apache.lucene.util.RamUsageEstimator$1.run(RamUsageEstimator.java:336) ~[lucene-core-6.2.1.jar:6.2.1 43ab70147eb494324a1410f7a9f16a896a59bc6f - shalin - 2016-09-15 05:15:20]
        at java.security.AccessController.doPrivileged(java.base@9-internal/Native Method) ~[?:?]
        at org.apache.lucene.util.RamUsageEstimator.shallowSizeOfInstance(RamUsageEstimator.java:336) ~[lucene-core-6.2.1.jar:6.2.1 43ab70147eb494324a1410f7a9f16a896a59bc6f - shalin - 2016-09-15 05:15:20]
        at org.apache.lucene.util.RamUsageEstimator.shallowSizeOf(RamUsageEstimator.java:313) ~[lucene-core-6.2.1.jar:6.2.1 43ab70147eb494324a1410f7a9f16a896a59bc6f - shalin - 2016-09-15 05:15:20]
        at org.apache.lucene.util.fst.ByteSequenceOutputs.<clinit>(ByteSequenceOutputs.java:154) ~[lucene-core-6.2.1.jar:6.2.1 43ab70147eb494324a1410f7a9f16a896a59bc6f - shalin - 2016-09-15 05:15:20]
        ... 21 more
```

**Comment by s1monw** [comment]
your java9 openJDK build looks ancient `2016-04-14` can you use a recent one and report back or if you wanna run in production I'd recommend to use java8 instead unless you are happy to take a walk on the wild side :)

**Comment by petrikoz** [comment]
Hm...
I found some strange thing:
`openjdk-9-jre-headless` still stay in system when I removed `openjdk-9-jre` and installed `openjdk-8-jre`.

And command 'java -version' returned 9 version.
I know it just now. My mistake took your time. Sorry!
Full remove openjdk 9 and clean install openjdk 8 solve my problem.

Thank you!

**Comment by s1monw** [comment]
YW
