### ISSUE TITLE
ERROE:ELasticSearch 5.0 .q not  working  with Windows Server 2008 R2 

### ISSUE THREAD

**Issue by NeverforgetZ** [elastic/elasticsearch#22014]
![qq 20161207111334](https://cloud.githubusercontent.com/assets/11733776/20953409/5bca6d7c-bc6e-11e6-8b42-265d60d29f0a.png)

[2016-12-07T09:22:01,527][INFO ][o.e.n.Node               ] [] initializing ...
[2016-12-07T09:22:01,938][INFO ][o.e.e.NodeEnvironment    ] [2tlAoxL] using [1] data paths, mounts [[(C:)]], net usable_space [1.5tb], net total_space [1.9tb], spins? [unknown], types [NTFS]
[2016-12-07T09:22:01,940][INFO ][o.e.e.NodeEnvironment    ] [2tlAoxL] heap size [1.9gb], compressed ordinary object pointers [true]
[2016-12-07T09:22:01,942][INFO ][o.e.n.Node               ] [2tlAoxL] node name [2tlAoxL] derived from node ID; set [node.name] to override
[2016-12-07T09:22:01,963][INFO ][o.e.n.Node               ] [2tlAoxL] version[5.0.1], pid[6108], build[080bb47/2016-11-11T22:08:49.812Z], OS[Windows Server 2008 R2/6.1/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_112/25.112-b15]
[2016-12-07T09:22:05,208][INFO ][o.e.p.PluginsService     ] [2tlAoxL] loaded module [aggs-matrix-stats]
[2016-12-07T09:22:05,223][INFO ][o.e.p.PluginsService     ] [2tlAoxL] loaded module [ingest-common]
[2016-12-07T09:22:05,224][INFO ][o.e.p.PluginsService     ] [2tlAoxL] loaded module [lang-expression]
[2016-12-07T09:22:05,224][INFO ][o.e.p.PluginsService     ] [2tlAoxL] loaded module [lang-groovy]
[2016-12-07T09:22:05,224][INFO ][o.e.p.PluginsService     ] [2tlAoxL] loaded module [lang-mustache]
[2016-12-07T09:22:05,224][INFO ][o.e.p.PluginsService     ] [2tlAoxL] loaded module [lang-painless]
[2016-12-07T09:22:05,224][INFO ][o.e.p.PluginsService     ] [2tlAoxL] loaded module [percolator]
[2016-12-07T09:22:05,226][INFO ][o.e.p.PluginsService     ] [2tlAoxL] loaded module [reindex]
[2016-12-07T09:22:05,228][INFO ][o.e.p.PluginsService     ] [2tlAoxL] loaded module [transport-netty3]
[2016-12-07T09:22:05,228][INFO ][o.e.p.PluginsService     ] [2tlAoxL] loaded module [transport-netty4]
[2016-12-07T09:22:05,230][INFO ][o.e.p.PluginsService     ] [2tlAoxL] loaded plugin [analysis-ik]
[2016-12-07T09:22:13,397][INFO ][o.e.n.Node               ] [2tlAoxL] initialized
[2016-12-07T09:22:13,399][INFO ][o.e.n.Node               ] [2tlAoxL] starting ...
[2016-12-07T09:22:13,740][ERROR][o.e.b.Bootstrap          ] [2tlAoxL] Exception
java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47) ~[?:?]
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:58) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59) ~[?:?]
	at org.elasticsearch.transport.netty4.Netty4Transport.createBootstrap(Netty4Transport.java:200) ~[?:?]
	at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:171) ~[?:?]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:182) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.node.Node.start(Node.java:525) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:211) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:288) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:112) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:103) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.cli.Command.main(Command.java:62) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:73) [elasticsearch-5.0.1.jar:5.0.1]
Caused by: io.netty.channel.ChannelException: failed to open a new selector
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:157) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:148) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:126) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[?:?]
	... 21 more
Caused by: java.io.IOException: Unable to establish loopback connection
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:94) ~[?:?]
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:61) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_112]
	at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:171) ~[?:?]
	at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50) ~[?:?]
	at java.nio.channels.Pipe.open(Pipe.java:155) ~[?:1.8.0_112]
	at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:127) ~[?:?]
	at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:155) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:148) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:126) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[?:?]
	... 21 more
Caused by: java.net.SocketException: No buffer space available (maximum connections reached?): bind
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:?]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:?]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67) ~[?:?]
	at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(PipeImpl.java:121) ~[?:?]
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:76) ~[?:?]
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:61) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_112]
	at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:171) ~[?:?]
	at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50) ~[?:?]
	at java.nio.channels.Pipe.open(Pipe.java:155) ~[?:1.8.0_112]
	at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:127) ~[?:?]
	at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:155) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:148) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:126) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[?:?]
	... 21 more
[2016-12-07T09:22:13,779][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to create a child event loop
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:116) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:103) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.cli.Command.main(Command.java:62) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:73) ~[elasticsearch-5.0.1.jar:5.0.1]
Caused by: java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47) ~[?:?]
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:58) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59) ~[?:?]
	at org.elasticsearch.transport.netty4.Netty4Transport.createBootstrap(Netty4Transport.java:200) ~[?:?]
	at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:171) ~[?:?]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:182) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.node.Node.start(Node.java:525) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:211) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:288) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:112) ~[elasticsearch-5.0.1.jar:5.0.1]
	... 6 more
Caused by: io.netty.channel.ChannelException: failed to open a new selector
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:157) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:148) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:126) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47) ~[?:?]
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:58) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59) ~[?:?]
	at org.elasticsearch.transport.netty4.Netty4Transport.createBootstrap(Netty4Transport.java:200) ~[?:?]
	at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:171) ~[?:?]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:182) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.node.Node.start(Node.java:525) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:211) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:288) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:112) ~[elasticsearch-5.0.1.jar:5.0.1]
	... 6 more
Caused by: java.io.IOException: Unable to establish loopback connection
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:94) ~[?:?]
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:61) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_112]
	at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:171) ~[?:?]
	at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50) ~[?:?]
	at java.nio.channels.Pipe.open(Pipe.java:155) ~[?:1.8.0_112]
	at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:127) ~[?:?]
	at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:155) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:148) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:126) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47) ~[?:?]
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:58) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59) ~[?:?]
	at org.elasticsearch.transport.netty4.Netty4Transport.createBootstrap(Netty4Transport.java:200) ~[?:?]
	at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:171) ~[?:?]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:182) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.node.Node.start(Node.java:525) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:211) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:288) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:112) ~[elasticsearch-5.0.1.jar:5.0.1]
	... 6 more
Caused by: java.net.SocketException: No buffer space available (maximum connections reached?): bind
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:?]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:?]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67) ~[?:?]
	at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(PipeImpl.java:121) ~[?:?]
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:76) ~[?:?]
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:61) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_112]
	at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:171) ~[?:?]
	at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50) ~[?:?]
	at java.nio.channels.Pipe.open(Pipe.java:155) ~[?:1.8.0_112]
	at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:127) ~[?:?]
	at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:155) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:148) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:126) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) ~[?:?]
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47) ~[?:?]
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:58) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72) ~[?:?]
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59) ~[?:?]
	at org.elasticsearch.transport.netty4.Netty4Transport.createBootstrap(Netty4Transport.java:200) ~[?:?]
	at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:171) ~[?:?]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:182) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.node.Node.start(Node.java:525) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:211) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:288) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:112) ~[elasticsearch-5.0.1.jar:5.0.1]
	... 6 more
[2016-12-07T09:22:13,852][INFO ][o.e.n.Node               ] [2tlAoxL] stopping ...
[2016-12-07T09:22:13,860][INFO ][o.e.n.Node               ] [2tlAoxL] stopped
[2016-12-07T09:22:13,860][INFO ][o.e.n.Node               ] [2tlAoxL] closing ...
[2016-12-07T09:22:13,883][INFO ][o.e.n.Node               ] [2tlAoxL] closed

**Comment by ywelsch** [comment]
> Caused by: java.net.SocketException: No buffer space available (maximum connections reached?): bind

Looks like it's not an issue with ES but your Windows version.

I've quickly done some googling and found
- http://stackoverflow.com/questions/10088363/java-net-socketexception-no-buffer-space-available-maximum-connections-reached
- https://support.microsoft.com/en-us/kb/2577795

Please report back if that fixed your issue.

**Comment by NeverforgetZ** [comment]
thanks

**Comment by colings86** [comment]
No further feedback. Assuming the issue was fixed by the above
