### ISSUE TITLE
5.1 bootstrap error when setting node.local

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch#22064]
I'm on Windows 10 running 5.1.1 and our single node configuration is blowing up (was working on 5.0). There is nothing in the change log about this. 

https://github.com/exceptionless/Exceptionless/blob/feature/elastic5/build/elasticsearch.yml

```
[2016-12-08T20:44:07,655][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Unknown discovery type [local]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.cli.Command.main(Command.java:62) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.1.1.jar:5.1.1]
Caused by: java.lang.IllegalArgumentException: Unknown discovery type [local]
        at org.elasticsearch.discovery.DiscoveryModule.<init>(DiscoveryModule.java:93) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.node.Node.<init>(Node.java:410) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.node.Node.<init>(Node.java:229) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:214) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:214) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:306) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.1.1.jar:5.1.1]
        ... 6 more
```

**Comment by jasontedor** [comment]
Your config shows `discovery.type` set to `local`, and your error message is about `discovery.type` `local`. Local discovery was in fact removed in 5.1.1 in #20960, there was no notice since it had no purpose other than in the tribe service and being used in tests when there are multiple nodes running inside the same test JVM.

Can you say what you're trying to accomplish and maybe I can point you to the right settings?

**Comment by jasontedor** [comment]
You can just set `transport.type=local`, you do not need to set `discovery.type=local` and I think that that recommendation should be removed from docs that you link to. Also, note that local transport is removed in 6.0.0 in #20695.

**Comment by jasontedor** [comment]
Closed by c40233316b995b8f769307e7fb5852fbf300df77

**Comment by niemyjski** [comment]
So what should we do in 6.0? I'm only asking cause every release these days breaks me and I haven't even shipped :(

**Comment by jasontedor** [comment]
Why do you need to isolate the node? Why isn't binding to localhost sufficient? If not, bind to localhost and use `iptables/pfctl/wf.msc` to drop all traffic to the bound transport port.

**Comment by niemyjski** [comment]
That will work :), I just wanted to specify it in configuration (as you previously could)

**Comment by rjernst** [comment]
Setting `discovery.type` to `none` should work. This is the same that tribe node uses internally.
