### ISSUE TITLE
Fatal error with ingest-attachment plugin

### ISSUE THREAD

**Issue by chrduf** [elastic/elasticsearch#22077]
I am getting a fatal error when trying to index the attached stripped down document using the ingest-attachment plugin. This causes my cluster to reboot and does not give me an email notification. It looks to be having a problem with the embedded Visio diagram.

Version: 5.1.1 (Elastic Cloud)
ClusterId: 7e7501
Node: instance-0000000005
Plugin: ingest-attachment

Link to problematic doc: https://1drv.ms/w/s!ApTXXtrEV_GGiosenEfoUSk1rRnuYA 

Error Information

```
Dec 8 21:42:34 ERROR org.elasticsearch.bootstrap.ElasticsearchUncaughtExceptionHandler i5@z0
```

```
[2016-12-08T21:42:34,628][ERROR][org.elasticsearch.bootstrap.ElasticsearchUncaughtExceptionHandler] fatal error in thread [elasticsearch[index][T#1]], exiting java.lang.NoClassDefFoundError: com/graphbuilder/curve/Point
 at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_72]
 at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_72]
 at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_72]
 at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[?:1.8.0_72]
 at org.apache.poi.xdgf.util.ObjectFactory.put(ObjectFactory.java:34) ~[?:?]
 at org.apache.poi.xdgf.usermodel.section.geometry.GeometryRowFactory.(GeometryRowFactory.java:39) ~[?:?]
 at org.apache.poi.xdgf.usermodel.section.GeometrySection.(GeometrySection.java:55) ~[?:?]
 at org.apache.poi.xdgf.usermodel.XDGFSheet.(XDGFSheet.java:77) ~[?:?]
 at org.apache.poi.xdgf.usermodel.XDGFShape.(XDGFShape.java:113) ~[?:?]
 at org.apache.poi.xdgf.usermodel.XDGFShape.(XDGFShape.java:107) ~[?:?]
 at org.apache.poi.xdgf.usermodel.XDGFBaseContents.onDocumentRead(XDGFBaseContents.java:82) ~[?:?]
 at org.apache.poi.xdgf.usermodel.XDGFMasterContents.onDocumentRead(XDGFMasterContents.java:66) ~[?:?]
 at org.apache.poi.xdgf.usermodel.XDGFMasters.onDocumentRead(XDGFMasters.java:101) ~[?:?]
 at org.apache.poi.xdgf.usermodel.XmlVisioDocument.onDocumentRead(XmlVisioDocument.java:106) ~[?:?]
 at org.apache.poi.POIXMLDocument.load(POIXMLDocument.java:190) ~[?:?]
 at org.apache.poi.xdgf.usermodel.XmlVisioDocument.(XmlVisioDocument.java:79) ~[?:?]
 at org.apache.poi.xdgf.extractor.XDGFVisioExtractor.(XDGFVisioExtractor.java:41) ~[?:?]
 at org.apache.poi.extractor.ExtractorFactory.createExtractor(ExtractorFactory.java:207) ~[?:?]
 at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:86) ~[?:?]
 at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:87) ~[?:?]
 at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[?:?]
 at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120) ~[?:?]
 at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:72) ~[?:?]
 at org.apache.tika.extractor.ParsingEmbeddedDocumentExtractor.parseEmbedded(ParsingEmbeddedDocumentExtractor.java:102) ~[?:?]
 at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedFile(AbstractOOXMLExtractor.java:311) ~[?:?]
 at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedParts(AbstractOOXMLExtractor.java:202) ~[?:?]
 at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.getXHTML(AbstractOOXMLExtractor.java:115) ~[?:?]
 at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:112) ~[?:?]
 at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:87) ~[?:?]
 at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) ~[?:?]
 at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120) ~[?:?]
 at org.apache.tika.Tika.parseToString(Tika.java:568) ~[?:?]
 at org.elasticsearch.ingest.attachment.TikaImpl$1.run(TikaImpl.java:94) ~[?:?]
 at org.elasticsearch.ingest.attachment.TikaImpl$1.run(TikaImpl.java:91) ~[?:?]
 at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_72]
 at org.elasticsearch.ingest.attachment.TikaImpl.parse(TikaImpl.java:91) ~[?:?]
 at org.elasticsearch.ingest.attachment.AttachmentProcessor.execute(AttachmentProcessor.java:72) ~[?:?]
 at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:100) ~[elasticsearch-5.1.1.jar:5.1.1]
 at org.elasticsearch.ingest.Pipeline.execute(Pipeline.java:58) ~[elasticsearch-5.1.1.jar:5.1.1]
 at org.elasticsearch.ingest.PipelineExecutionService.innerExecute(PipelineExecutionService.java:166) ~[elasticsearch-5.1.1.jar:5.1.1]
 at org.elasticsearch.ingest.PipelineExecutionService.access$000(PipelineExecutionService.java:41) ~[elasticsearch-5.1.1.jar:5.1.1]
 at org.elasticsearch.ingest.PipelineExecutionService$1.doRun(PipelineExecutionService.java:65) ~[elasticsearch-5.1.1.jar:5.1.1]
 at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:527) ~[elasticsearch-5.1.1.jar:5.1.1]
 at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.1.1.jar:5.1.1]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_72]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_72]
 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72] 
Caused by: java.lang.ClassNotFoundException: com.graphbuilder.curve.Point
 at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_72]
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72]
 at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814) ~[?:1.8.0_72]
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72]
 ... 47 more
```

**Comment by jasontedor** [comment]
This is due to a missing transitive dependency: `com.github.virtuald:curvesapi:1.04`:

```
_transitive_org.apache.poi:poi-ooxml:3.15
\--- org.apache.poi:poi-ooxml:3.15
     +--- org.apache.poi:poi:3.15
     |    +--- commons-codec:commons-codec:1.10
     |    \--- org.apache.commons:commons-collections4:4.1
     +--- org.apache.poi:poi-ooxml-schemas:3.15
     |    \--- org.apache.xmlbeans:xmlbeans:2.6.0
     |         \--- stax:stax-api:1.0.1
     \--- com.github.virtuald:curvesapi:1.04
```

It's not ideal, but I think that you can work around this for now by dropping this dependency (and any of its transitive dependencies) in plugins/ingest-attachment.

**Comment by dadoonet** [comment]
He can't do that. He is on cloud.
I'm currently reproducing it.

**Comment by jasontedor** [comment]
> He can't do that. He is on cloud.

I didn't notice that but that is indeed unfortunate.

**Comment by dadoonet** [comment]
I can totally reproduce the hard failure locally.
Thanks a lot @chrduf for providing the file which is causing that.
Working on a fix ATM. We have to fix 2 things IMO:

* catch the exception correctly and just fail the ingest pipeline (don't stop the node basically)
* then try to see if we can add safely the missing dependency

**Comment by jasontedor** [comment]
> This causes my cluster to reboot and does not give me an email notification.

We will look into why this is the case (that you're not receiving the email notification).

**Comment by dadoonet** [comment]
@chrduf I'd like to use your file https://1drv.ms/w/s!ApTXXtrEV_GGiosenEfoUSk1rRnuYA as an input for a test case. Do you allow us doing so?

**Comment by chrduf** [comment]
yes, you can use that document
