### ISSUE TITLE
Elasticsearch is terminated when running a scripted aggregation post-filter

### ISSUE THREAD

**Issue by fassisrosa** [elastic/elasticsearch#22083]
**Elasticsearch version**: 

5.1.1, 5.0.0

**Plugins installed**: 

Out of the box install. Scripting enabled by setting in elasticsearch.yml:

`script.inline: true
`

**JVM version**: 

```
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
**OS version**:
```

**Description of the problem including expected versus actual behavior**:

Running a scripted post-filter on an aggregation causes Elasticsearch to fail with exception and stop running altogether. Elasticsearch server process is terminated. This happens both on Windows 2012R2 and Linux Ubuntu.

**Steps to reproduce**:
 1. Run the following curl commands to reproduce:

```
curl -XPOST 192.168.79.135:9200/script_error/data  -d'
{ 
  "id": 1, 
  "numerical": 100 
} 
 '
curl -XGET 192.168.79.135:9200/script_error/_search -d'
{ 
  "size": 0, 
  "aggregations": { 
    "byId": { 
      "terms": { 
        "field": "id" 
      }, 
      "aggregations": { 
        "var_numerical": { 
          "avg": { 
            "field": "numerical" 
          } 
        }, 
        "post": { 
          "bucket_selector": { 
            "buckets_path": { 
              "var_numerical": "var_numerical" 
            }, 
            "script": { 
              "inline": "(var_numerical >= 11111111111111111111111111111 && var_numerical <= 9007199254740991)", 
              "lang": "groovy" 
            } 
          } 
        } 
      } 
    } 
  } 
} 
'
```

**Provide logs (if relevant)**:
In logs I see:
```
[2016-12-09T13:36:55,149][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [WIN2K12R2IMAGE] fatal error in thread [elasticsearch[WIN2K12R2IMAGE][search][T#3]], exiting
java.lang.NoClassDefFoundError: java/math/BigInteger
	at e9629ba47b3c2eaf8b157811d3f81bd8a5e4111f.__$swapInit(e9629ba47b3c2eaf8b157811d3f81bd8a5e4111f) ~[?:?]
	at e9629ba47b3c2eaf8b157811d3f81bd8a5e4111f.<clinit>(e9629ba47b3c2eaf8b157811d3f81bd8a5e4111f) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_112]
	at org.elasticsearch.script.groovy.GroovyScriptEngineService.createScript(GroovyScriptEngineService.java:179) ~[?:?]
	at org.elasticsearch.script.groovy.GroovyScriptEngineService.executable(GroovyScriptEngineService.java:195) ~[?:?]
	at org.elasticsearch.script.ScriptService.executable(ScriptService.java:483) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.aggregations.pipeline.bucketselector.BucketSelectorPipelineAggregator.reduce(BucketSelectorPipelineAggregator.java:103) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:144) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:158) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.action.search.SearchPhaseController.merge(SearchPhaseController.java:493) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction$2.doRun(SearchQueryThenFetchAsyncAction.java:132) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:504) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.0.0.jar:5.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.ClassNotFoundException: java.math.BigInteger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_112]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_112]
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:677) ~[?:?]
	at groovy.lang.GroovyClassLoader$InnerLoader.loadClass(GroovyClassLoader.java:425) ~[?:?]
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:787) ~[?:?]
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:775) ~[?:?]
	... 19 more

```

**Comment by clintongormley** [comment]
@jasontedor any thoughts?

**Comment by mrdgan** [comment]
BigInteger ?

**Comment by rjernst** [comment]
Groovy has been removed for 6.0, and painless fails up front when compiling the script (since the integer literal is too long to be stored by a `long`.). So I'm going to close this.
