### ISSUE TITLE
Better logging for bin/elasticsearch-plugin tool

### ISSUE THREAD

**Issue by n0othing** [elastic/elasticsearch#22084]
Saw an issue where `elasticsearch-plugin install x-pack` failed because a prior version was installed-- but the logging makes it look like something's wrong the with x-pack binary you're attempting to install:

```
esadmin@ubuntu-LTS16:~/Desktop/elasticsearch-5.1.1$ bin/elasticsearch-plugin install file:///home/esadmin/Downloads/x-pack-5.1.1.zip
-> Downloading file:///home/esadmin/Downloads/x-pack-5.1.1.zip
[=================================================] 100%   
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [x-pack] is incompatible with Elasticsearch [5.1.1]. Was designed for version [5.0.0]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:108)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:292)
	at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:451)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:432)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:474)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:195)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
	at org.elasticsearch.cli.Command.main(Command.java:62)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:42)

```

In the above scenario, I was installing x-pack v 5.1.1 on ES 5.1.1, but hadn't uninstalled x-pack 5.0.0. 

Our docs _do_ instruct users to uninstall old versions first, but it would be helpful to catch the error and let the user know they need to remove the old version.

**Comment by jasontedor** [comment]
Closed by #22305
