### ISSUE TITLE
[CI] TermsTests.testFromXContent fails due to unexected "num_partitions" field

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#22091]
Getting this failure:

```
ERROR   0.92s | TermsTests.testFromXContent <<< FAILURES!
   > Throwable #1: java.lang.IllegalArgumentException: [terms] unknown field [num_partitions], parser not found
   > 	at __randomizedtesting.SeedInfo.seed([D4C0C57513CD8E64:F5A8F06D9A6A6EBE]:0)
   > 	at org.elasticsearch.common.xcontent.ObjectParser.getParser(ObjectParser.java:401)
   > 	at org.elasticsearch.common.xcontent.ObjectParser.parse(ObjectParser.java:161)
   > 	at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregationBuilder.parse(TermsAggregationBuilder.java:99)
   > 	at org.elasticsearch.search.aggregations.BaseAggregationTestCase.testFromXContent(BaseAggregationTestCase.java:122)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> NOTE: leaving temporary files on disk at: /home/hinmanm/es/elasticsearch/core/build/testrun/test/J0/temp/org.elasticsearch.search.aggregations.bucket.TermsTests_D4C0C57513CD8E64-001
  2> NOTE: test params are: codec=Asserting(Lucene62): {}, docValues:{}, maxPointsInLeafNode=1756, maxMBSortInHeap=7.792531579773628, sim=RandomSimilarity(queryNorm=true,coord=crazy): {}, locale=fr-CH, timezone=Egypt
  2> NOTE: Linux 4.8.10-200.fc24.x86_64 amd64/Oracle Corporation 1.8.0_77 (64-bit)/cpus=4,threads=1,free=460500176,total=514850816
  2> NOTE: All tests run in this JVM: [TermsTests]
```

From: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=opensuse/374/console

Which reproduces locally for me with:

```
gradle :core:test -Dtests.seed=D4C0C57513CD8E64 -Dtests.class=org.elasticsearch.search.aggregations.bucket.TermsTests -Dtests.method="testFromXContent" -Dtests.security.manager=true -Dtests.locale=fr-CH -Dtests.timezone=Egypt
```

**Comment by jpountz** [comment]
Fixed via 20ff703
