### ISSUE TITLE
x-pack offline installation : failure

### ISSUE THREAD

**Issue by MarneusCalgarXP** [elastic/elasticsearch#22109]
**Elasticsearch version**: 5.1.1

**Plugins installed**: [none]

**JVM version**: 1.8.0_101-b13 64bits

**OS version**: Centos 6

**Description of the problem including expected versus actual behavior**:
When trying to install x-pack offline as indicated by official documentation (https://www.elastic.co/guide/en/x-pack/5.0/installing-xpack.html#xpack-installing-offline), I get an error:

```
$ ./bin/elasticsearch-plugin install file:///path/to/elasticsearch-5.1.1/plugins/x-pack-5.1.1.zip
-> Downloading file:///path/to/elasticsearch-5.1.1/plugins/x-pack-5.1.1.zip
[=================================================] 100%Â Â 
Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [x-pack-5.1.1.zip]. Was the plugin built before 2.0?
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:295)
        at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:451)
        at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:432)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:474)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:195)
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
        at org.elasticsearch.cli.Command.main(Command.java:62)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:42)
Caused by: java.nio.file.FileSystemException: /path/to/elasticsearch-5.1.1/plugins/x-pack-5.1.1.zip/plugin-descriptor.properties: Not a directory
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:86)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:292)
        ... 11 more
```

**Steps to reproduce**:
 1. Download and unzip elasticsearch 5.1.1
 2. Download offline x-pack package (wget https://artifacts.elastic.co/downloads/packs/x-pack/x-pack-5.1.1.zip ) (into plugins directory)
 3. Try to install x-pack as described in documentation (./bin/elasticsearch-plugin install file:///path/to/elasticsearch-5.1.1/plugins//x-pack-5.1.1.zip)

**Provide logs (if relevant)**:

```
-> Downloading file:///path/to/elasticsearch-5.1.1/plugins/x-pack-5.1.1.zip
[=================================================] 100%Â Â 
Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [x-pack-5.1.1.zip]. Was the plugin built before 2.0?
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:295)
        at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:451)
        at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:432)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:474)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:195)
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
        at org.elasticsearch.cli.Command.main(Command.java:62)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:42)
Caused by: java.nio.file.FileSystemException: /path/to/elasticsearch-5.1.1/plugins/x-pack-5.1.1.zip/plugin-descriptor.properties: Not a directory
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:86)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:292)
        ... 11 more
```

**Workaround**:
* $ cd /path/to/elasticsearch-5.1.1/plugins
* $ unzip x-pack-5.1.1.zip "elasticsearch/*"
* $ mv elasticsearch x-pack

EDITED 2016-12-15 : I downloaded the x-pack zip file into the plugins directory

**Comment by dadoonet** [comment]
I just followed the same steps as you did and I can't reproduce it.

```sh
wget https://artifacts.elastic.co/downloads/packs/x-pack/x-pack-5.1.1.zip
bin/elasticsearch-plugin install file:///Users/dpilato/Downloads/x-pack-5.1.1.zip 
```

Gave:

```
$ bin/elasticsearch-plugin install file:///Users/dpilato/Downloads/x-pack-5.1.1.zip 
-> Downloading file:///Users/dpilato/Downloads/x-pack-5.1.1.zip
...
```

That's strange you are seeing this message.
What gives `bin/elasticsearch-plugin list`?

**Comment by dadoonet** [comment]
I feel like you have somewhere an old version of the PluginManager. It looks like a 2.x message here.

**Comment by clintongormley** [comment]
> Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [x-pack-5.1.1.zip]. Was the plugin built before 2.0?

It looks like you downloaded the zip file into the plugins directory

**Comment by MarneusCalgarXP** [comment]
@dadoonet after install:
`$ ./bin/elasticsearch-plugin list
xpack
`

@clintongormley yes in fact, I used to download the zip file into the plugins directory and tried to install it from this location (/path/to/elasticsearch-5.1.1/plugins).

**Comment by clintongormley** [comment]
@MarneusCalgarXP that's the cause of the problem.  the installer is trying to verify the plugins that are already there, and it comes across your zip download which shouldn't be there, so throws an exception.  move it somewhere else and everything will work.
