### ISSUE TITLE
Add support for Debug.explain in scripted aggs

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#22118]
When you try to debug a painless script in scripted aggs like `"Debug.explain('foo bar');` you are getting back:

```
Caused by: RemoteTransportException[[fJZh-wm][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: ScriptException[runtime error]; nested: NotSerializableExceptionWrapper[painless_explain_error: null];
Caused by: ScriptException[runtime error]; nested: NotSerializableExceptionWrapper[painless_explain_error: null];
	at org.elasticsearch.painless.ScriptImpl.convertToScriptException(ScriptImpl.java:181)
	at org.elasticsearch.painless.ScriptImpl.run(ScriptImpl.java:126)
	at org.elasticsearch.search.aggregations.metrics.scripted.ScriptedMetricAggregatorFactory.createInternal(ScriptedMetricAggregatorFactory.java:81)
	at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:225)
	at org.elasticsearch.search.aggregations.AggregatorFactories.createTopLevelAggregators(AggregatorFactories.java:102)
	at org.elasticsearch.search.aggregations.AggregationPhase.preProcess(AggregationPhase.java:61)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:104)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:259)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:273)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:300)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:297)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:577)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:527)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: NotSerializableExceptionWrapper[painless_explain_error: null]
	at org.elasticsearch.painless.Debug.explain(Debug.java:41)
	at org.elasticsearch.painless.Executable$Script.execute(Debug.explain('bla ' + 1); params._agg.heights = [] @ <inline script>:15)
	at org.elasticsearch.painless.ScriptImpl.run(ScriptImpl.java:123)
	... 16 more
```

**Comment by jdconrad** [comment]
@nik9000 Any thoughts on why this might happen?

**Comment by nik9000** [comment]
> @nik9000 Any thoughts on why this might happen?

Looks like @dadoonet's already figured it out: #22125.  I'll have a look at fixing both issues soon! It'll be a historical expidition to figure out why we caught all exceptions and did nothing - probably to do with aggs across many indices.

**Comment by nik9000** [comment]
Same comment as https://github.com/elastic/elasticsearch/issues/22125#issuecomment-267691599: we do throw the exception and it is in the http response, but we don't return a non-200 response code because not all the shards failed. That is how elasticsearch handles partial success, for better or for worse.
