### ISSUE TITLE
SearchTemplateRequestBuilder breaking change from 5.0 to 5.1

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#22119]
**Elasticsearch version**: 5.1.1
**Description of the problem including expected versus actual behavior**:

I'm using the following Java code against a Node running elasticsearch 5.0.1:

My `pom.xml` file:

```xml
<dependencies>
    <dependency>
        <groupId>org.elasticsearch.client</groupId>
        <artifactId>transport</artifactId>
        <version>5.0.1</version>
    </dependency>
</dependencies>
```

My code:

```java
client.admin().cluster().preparePutStoredScript()
        .setScriptLang("mustache")
        .setId("template_gender")
        .setSource(new BytesArray(
                "{\n" +
                        "    \"template\" : {\n" +
                        "        \"query\" : {\n" +
                        "            \"match\" : {\n" +
                        "                \"gender\" : \"{{param_gender}}\"\n" +
                        "            }\n" +
                        "        }\n" +
                        "    }\n" +
                        "}")).get();

Map<String, Object> template_params = new HashMap<>();
template_params.put("param_gender", "male");

SearchTemplateResponse str = new SearchTemplateRequestBuilder(client)
        .setScript("template_gender")
        .setScriptType(ScriptService.ScriptType.STORED)
        .setRequest(new SearchRequest())
        .setScriptParams(template_params)
        .get();
SearchResponse sr = str.getResponse();
```

Everything works fine.

Then I upgrade the server to 5.1.1. Note that I don't upgrade the TransportClient version.

It now fails with:

```
java.lang.IllegalStateException: Error reading ScriptType id [15] from stream, expected one of [2 [file], 1 [stored], 0 [inline]]

	at org.elasticsearch.script.ScriptType.readFrom(ScriptType.java:79)
	at org.elasticsearch.script.mustache.SearchTemplateRequest.readFrom(SearchTemplateRequest.java:147)
	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1340)
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1242)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:536)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:490)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
```

It means that we changed the serialization between 5.0 and 5.1.
It also means to me that we probably can not do rolling upgrades when people are using the Search Template feature (not tested though).
Also probably means that people can't upgrade their client application to 5.1.1 then smoothly upgrade their nodes from 5.0 to 5.1. Not tested yet but will do it soonish.

I believe this has been introduced by #21136 which has been backported to 5.1 with https://github.com/elastic/elasticsearch/commit/02d8522e7d166f11ff456cbc0774ef62904bd68c.

**Comment by dadoonet** [comment]
When running a 5.1 Transport client on a 5.0 node, changing the code with:

```java
SearchTemplateResponse str = new SearchTemplateRequestBuilder(client)
        .setScript("template_gender")
        .setScriptType(ScriptType.STORED)
        .setRequest(new SearchRequest())
        .setScriptParams(template_params)
        .get();
```

you get:

```
NotSerializableExceptionWrapper[class_cast_exception: java.lang.Integer cannot be cast to java.util.Map
]
	at org.elasticsearch.common.io.stream.StreamInput.readMap(StreamInput.java:460)
	at org.elasticsearch.script.mustache.SearchTemplateRequest.readFrom(SearchTemplateRequest.java:129)
	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1303)
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1205)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:513)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:467)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dadoonet** [comment]
I created a mixed cluster running one 5.0 and one 5.1 nodes.
Using the REST interface, I can't reproduce the problem. So it's only when using the TransportClient apparently.

Script used:

```sh
curl -XDELETE localhost:9200/test?pretty
curl -XPUT localhost:9200/test/person/1?pretty -d '
{
	"gender": "male"
}
'
curl -XPOST localhost:9200/_search/template/template_gender
{
    "template": {
        "query": {
            "match": {
                "gender": "{{param_gender}}"
            }
        }
    }
}
```

Then

```sh
# Trying node 1 (running 5.0.1)
curl localhost:9200/_search/template?pretty -d '
{
    "id" : "template_gender",
    "params": {
    	"param_gender": "male"
    }
}
'
# Trying node 2 (running 5.1.1)
curl localhost:9201/_search/template?pretty -d '
{
    "id" : "template_gender",
    "params": {
    	"param_gender": "male"
    }
}
'
```

**Comment by javanna** [comment]
This seems to be an unwanted breaking change in the java api between 5.0 and 5.1. It wasn't picked up though and at this point we don't release 5.0.x nor 5.1.x anymore, hence I don't think there's anything we can about it, it is too late to fix it. Closing.
