### ISSUE TITLE
ClassNotFoundException: org.elasticsearch.plugins.NetworkPlugin

### ISSUE THREAD

**Issue by tademeit** [elastic/elasticsearch#22112]
**Elasticsearch version**:
2.4.0

**Plugins installed**: 
[ ]

**JVM version**: 
1.8.0

**OS version**:
Win 10 Pro

**Description of the problem including expected versus actual behavior**:
When I want to start a TransportClient my Log says that the NetworkPlugin cound not be found.

**Steps to reproduce**:
 1. Set up a Transport Client
 		Settings settings = Settings.builder().put("cluster.name", "clusterName").build();
		TransportClient client = new PreBuiltTransportClient(settings)
        .addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("localhost"), 9300));

**Provide logs (if relevant)**:
java.lang.ClassNotFoundException: org.elasticsearch.plugins.NetworkPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_60]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_60]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_60]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_60]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_60]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_60]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_60]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_60]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_60]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_60]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_60]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_60]

**Comment by dadoonet** [comment]
Please describe how you configured your project on discuss.elastic.co. We can help you there.
You probably forgot something.
Also if you are using a dependency manager like maven share your `pom.xml` file.

Have a look at the doc here: https://www.elastic.co/guide/en/elasticsearch/client/java-api/2.4/_maven_repository.html

This place is for confirmed issues. Thanks!
