### ISSUE TITLE
Warning Unable to install syscall filter whenever Elasticsearch starts

### ISSUE THREAD

**Issue by bwf93** [elastic/elasticsearch#22207]
**Elasticsearch version**: 5.1.1

**Plugins installed**: None

**JVM version**: 1.8.0_111

**OS version**: Windows 7

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Start Elasticsearch
 2. See warning

Elasticsearch still works but there is a warning about syscalls

```
[2016-12-15T15:14:07,580][WARN ][o.e.b.JNANatives         ] unable to install syscall filter:
java.lang.UnsupportedOperationException: AssignProcessToJobObject: 5
        at org.elasticsearch.bootstrap.Seccomp.windowsImpl(Seccomp.java:613) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.bootstrap.Seccomp.init(Seccomp.java:643) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.bootstrap.JNANatives.trySeccomp(JNANatives.java:215) [elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.bootstrap.Natives.trySeccomp(Natives.java:99) [elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:105) [elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:176) [elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:306) [elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) [elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) [elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) [elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) [elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.cli.Command.main(Command.java:62) [elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) [elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)
 [elasticsearch-5.1.1.jar:5.1.1]
[2016-12-15T15:14:07,680][INFO ][o.e.n.Node               ] [] initializing ...
[2016-12-15T15:14:07,742][INFO ][o.e.e.NodeEnvironment    ] [t71HDWo] using [1] data paths, mounts [[OSDisk (C:)]], net usable_space [37.4gb], net total_space [238.1gb], spins? [unknown], types [NTFS]
```

**Comment by jasontedor** [comment]
This error code correlates to `ERROR_ACCESS_DENIED` when we invoke `AssignProcessToJobObject` when trying to assign Elasticsearch to a job object that we created to limit the ability to fork within Elasticsearch. It is a limitation that exists on Windows 7 that you can not assign a process to a job if it is already assigned to a job (this is not a limitation that exists on Windows 10).

The question is, why is Elasticsearch already assigned to a job? I think that you're running into this because of the Program Compatibility Assistant. Program Compatibility Assistant assigns processes to jobs as part of executing its functionality. To remove this warning message you can do one of the following:
 - disable Program Compatibility Assistant by running services.msc, scrolling to Program Compatibility Assistant and stopping the service
 - do not start Elasticsearch in a manner that subjects it to the Program Compatibility Assistant (for example, start Elasticsearch from the command line)
 - disable the system call filter *at your own risk*; to do this, start Elasticsearch with `bootstrap.seccomp` set to `false` (note that starting in Elasticsearch 5.2.0, this setting is deprecated and you should use `bootstrap.system_call_filter` instead).

As you note, this warning is benign in the sense that Elasticsearch still starts, but you're at increased risk of arbitrary code execution attacks against Elasticsearch.

Lastly, please note that Elastic [does not officially support](https://www.elastic.co/support/matrix) Elasticsearch on Windows 7.
