### ISSUE TITLE
Epath.conf  leads to exception reading jvm.options

### ISSUE THREAD

**Issue by mr-mos** [elastic/elasticsearch#22228]
**Elasticsearch version**:
5.1.1

**Plugins installed**: []

**JVM version**:
8u111

**OS version**:
Windows 7

**Description of the problem including expected versus actual behavior**:
Changed the config-location with -Epath.conf=....  and renamed the config-folder in the install-directory.
"jvm.options" are read from the wrong place. Exception because file couldn't be read,

**Steps to reproduce**:
 1. elasticsearch-5.1.1\bin\elasticsearch.bat -Epath.conf=\your-path\elasticsearch-data\config
 2. rename  %ES/config
 3. start ES

**Provide logs (if relevant)**:

FINDSTR: D:\mydir\elasticsearch-5.1.1\bin\\..\config\jvm.options could not be opened
2016-12-16 14:50:53,375 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at org.apache.logging.log4j.core.jmx.Server.register(Server.java:389)

**Comment by jasontedor** [comment]
> FINDSTR: D:\mydir\elasticsearch-5.1.1\bin\..\config\jvm.options could not be opened

If you move `jvm.options`, you need to set the `ES_JVM_OPTIONS`environment variable to the new location (full path, including the name of the file).
