### ISSUE TITLE
UnsupportedClassVersionError: ... Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by mtaylor769** [elastic/elasticsearch#22244]
I have read this and several other articles that state that JRE8 should be installed. I am still getting this error after installing JRE8u111 from the Oracle Developer Website:
https://github.com/elastic/elasticsearch/issues/21102

**Hardware Overview:**

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro8,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.4 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	8 GB
  Boot ROM Version:	MBP81.0047.B2C
  SMC Version (system):	1.68f99
  Serial Number (system):	C02GP06RDY77
  Hardware UUID:	21900919-C001-5A47-9BDA-9344FAD83E61
  Sudden Motion Sensor:
  State:	Enabled

**Java 8 Update 111:
  Version:**	
  Source:	3rd Party
  Install Date:	12/16/16, 5:26 PM

**Elasticsearch version**:
5.1.1
**Plugins installed**: []
Clean install
**JVM version**:

**OS version**:
10.11.6
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. try to start elastic search from clean install using provided installation documentation
 2.
 3.

**Provide logs (if relevant)**:
elasticsearch-5.1.1> bin/elasticsearch
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/bootstrap/Elasticsearch : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Describe the feature**:

**Comment by dadoonet** [comment]
Did you set JAVA_HOME?

**Comment by jasontedor** [comment]
If you're running into this then it is definitely the case that your Java 8 installation is not being picked up. From the same shell, you can try `java -version` and I suspect that you'll see the bundled Java 6 that some applications on the Mac require (for example, Minecraft for a long time forced you to install Java 6). You can fix this by setting `JAVA_HOME` to point to the path of your Java 8 installation.
