### ISSUE TITLE
Unable to create S3 snapshot repo - no_class_def_found_error: Could not initialize class com.amazonaws.services.s3.internal.S3ErrorResponseHandler

### ISSUE THREAD

**Issue by ranguard** [elastic/elasticsearch#22271]
**Elasticsearch version**: 2.4.3

**Plugins installed**: [ 'cloud-aws' (2.4.3) and kopf ]

https://gist.github.com/ranguard/d7844dc5f6c6e31170a0b4d4f1c0a344

**JVM version**: 

Whatever puppet installs ( https://github.com/metacpan/metacpan-puppet/blob/master/modules/metacpan_elasticsearch/manifests/instance.pp#L37 )...

```sh
/usr/lib/jvm/java-7-openjdk-amd64/bin/java -version
java version "1.7.0_03"
OpenJDK Runtime Environment (IcedTea7 2.1.7) (7u3-2.1.7-1)
OpenJDK 64-Bit Server VM (build 22.0-b10, mixed mode)
```

**OS version**: Debian 7.11

**Description of the problem including expected versus actual behavior**:

Unable to create S3 snapshot repo:
```
no_class_def_found_error: Could not initialize class com.amazonaws.services.s3.internal.S3ErrorResponseHandler
```

**Steps to reproduce / Provide logs (if relevant)**:

See steps and stack trace here:

https://gist.github.com/ranguard/1cde5ef1fcda670f5eee80637c1c991d

**Comment by dadoonet** [comment]
Can you upgrade your Java version and see if it fixes your problem?

**Comment by ranguard** [comment]
Hi,

What should I upgrade it to? And is there any knock on effect for ES cluster?... this is a production env.

Many thanks

**Comment by clintongormley** [comment]
@dadoonet I think we may be missing transitive dependencies. This seems similar to https://github.com/databricks/spark-redshift/issues/103

**Comment by clintongormley** [comment]
@ranguard could you try adding `joda-time-2.8.1.jar`  to your plugins/cloud-aws/ directory?

https://mvnrepository.com/artifact/joda-time/joda-time/2.8.1

If that doesn't work, try adding:

* `jackson-core-2.5.3.jar` https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core/2.5.3
* `jackson-dataformat-cbor-2.5.3.jar` https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-cbor/2.5.3

**Comment by ranguard** [comment]
https://mvnrepository.com/artifact/joda-time/joda-time/2.8.1 lead to:

```
[2016-12-20 18:53:29,680][ERROR][bootstrap                ] Exception
java.lang.IllegalStateException: failed to load bundle [file:/usr/share/elasticsearch/plugins/cloud-aws/cloud-aws-2.4.3.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/commons-codec-1.6.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/aws-java-sdk-kms-1.10.69.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/aws-java-sdk-s3-1.10.69.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/jackson-annotations-2.5.0.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/httpclient-4.3.6.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/aws-java-sdk-core-1.10.69.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/aws-java-sdk-ec2-1.10.69.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/commons-logging-1.1.3.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/joda-time-2.8.1.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/jackson-databind-2.5.3.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/httpcore-4.3.3.jar] due to jar hell
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:421)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129)
	at org.elasticsearch.node.Node.<init>(Node.java:158)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:45)
Caused by: java.lang.IllegalStateException: jar hell!
class: org.joda.time.base.AbstractDateTime
jar1: /usr/share/elasticsearch/lib/joda-time-2.9.5.jar
jar2: /usr/share/elasticsearch/plugins/cloud-aws/joda-time-2.8.1.jar
	at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:280)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:186)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:419)
	... 7 more
```

Also adding `jackson-core-2.5.3.jar` and `jackson-dataformat-cbor-2.5.3.jar` also BOOM...
```
[2016-12-20 18:57:49,766][ERROR][bootstrap                ] Exception
java.lang.IllegalStateException: failed to load bundle [file:/usr/share/elasticsearch/plugins/cloud-aws/cloud-aws-2.4.3.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/commons-codec-1.6.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/aws-java-sdk-kms-1.10.69.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/aws-java-sdk-s3-1.10.69.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/jackson-annotations-2.5.0.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/httpclient-4.3.6.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/aws-java-sdk-core-1.10.69.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/aws-java-sdk-ec2-1.10.69.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/jackson-core-2.5.3.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/commons-logging-1.1.3.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/joda-time-2.8.1.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/jackson-dataformat-cbor-2.5.3.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/jackson-databind-2.5.3.jar, file:/usr/share/elasticsearch/plugins/cloud-aws/httpcore-4.3.3.jar] due to jar hell
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:421)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129)
	at org.elasticsearch.node.Node.<init>(Node.java:158)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:45)
Caused by: java.lang.IllegalStateException: jar hell!
class: com.fasterxml.jackson.core.Base64Variant
jar1: /usr/share/elasticsearch/lib/jackson-core-2.8.1.jar
jar2: /usr/share/elasticsearch/plugins/cloud-aws/jackson-core-2.5.3.jar
	at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:280)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:186)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:419)
	... 7 more
```

For reference my `cloud-aws` folder looked like this:
```
-rw-r--r-- 1 root root  229998 Apr 24  2015 jackson-core-2.5.3.jar
-rw-r--r-- 1 root root   46519 Apr 25  2015 jackson-dataformat-cbor-2.5.3.jar
-rw-r--r-- 1 root root  621931 Jun 15  2015 joda-time-2.8.1.jar
-rw-r--r-- 1 root root   39815 Dec 18 08:32 jackson-annotations-2.5.0.jar
-rw-r--r-- 1 root root  232771 Dec 18 08:32 commons-codec-1.6.jar
-rw-r--r-- 1 root root   55989 Dec 18 08:32 cloud-aws-2.4.3.jar
-rw-r--r-- 1 root root  622188 Dec 18 08:32 aws-java-sdk-s3-1.10.69.jar
-rw-r--r-- 1 root root  345717 Dec 18 08:32 aws-java-sdk-kms-1.10.69.jar
-rw-r--r-- 1 root root  592008 Dec 18 08:32 httpclient-4.3.6.jar
-rw-r--r-- 1 root root  619790 Dec 18 08:32 aws-java-sdk-core-1.10.69.jar
-rw-r--r-- 1 root root    1638 Dec 18 08:32 plugin-security.policy
-rw-r--r-- 1 root root    2706 Dec 18 08:32 plugin-descriptor.properties
-rw-r--r-- 1 root root 1143162 Dec 18 08:32 jackson-databind-2.5.3.jar
-rw-r--r-- 1 root root  282793 Dec 18 08:32 httpcore-4.3.3.jar
-rw-r--r-- 1 root root   62050 Dec 18 08:32 commons-logging-1.1.3.jar
-rw-r--r-- 1 root root 3193658 Dec 18 08:32 aws-java-sdk-ec2-1.10.69.jar
-rw-r--r-- 1 root root      15 Dec 18 08:32 .name
```

**Comment by dadoonet** [comment]
I remember an old issue with very old versions of Java7 with AWS SDK.
Upgrading to latest java7 patch solved the issue.

Was related to date indeed.

So could you try to update your Java 7 version?

**Comment by ranguard** [comment]
Whats the best way to do that? - I am using the puppet module with java_install = true

Thanks

**Comment by ranguard** [comment]
Worked it out - some packages had been kept back, and also we didn't have debian security in the apt list on those boxes!

So although the puppet config was the same, there was a Java version difference, this version worked:

```
java version "1.7.0_111"
OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-2~deb7u1)
OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)
```

Many thanks for the assist

**Comment by dadoonet** [comment]
Thanks a lot for confirming @ranguard!
