### ISSUE TITLE
ES 5.0.1 cluster node crash. TransportService is closed stopped can't send request

### ISSUE THREAD

**Issue by kevin-tang-rs** [elastic/elasticsearch#22381]
**Elasticsearch version**:
5.0.1
**Plugins installed**: [none]

**JVM version**:
openjdk version "1.8.0_91"
**OS version**:
ubuntu 14.04.1
**Description of the problem including expected versus actual behavior**:
in cluster nodes there are many error log. include
1. org.elasticsearch.transport.SendRequestTransportException: [1][172.16.2.171:20152][indices:data/read/search[phase/query]]
	at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:504) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:459) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:452) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.search.SearchTransportService.sendExecuteQuery(SearchTransportService.java:110) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction.sendExecuteFirstPhase(SearchQueryThenFetchAsyncAction.java:66) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.performFirstPhase(AbstractSearchAsyncAction.java:161) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:257) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:170) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:955) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.transport.TransportService$3.doRun(TransportService.java:230) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:520) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.0.1.jar:5.0.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: org.elasticsearch.transport.TransportException: TransportService is closed stopped can't send request
	at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:484)

2. high disk watermark [90%] exceeded on [mVzAi6quTsiZenL7_3Lv9A][2][/var/asp_data/elasticsearch/5c689076-ca09-11e6-af07-00e04c681f50/nodes/0] free: 1.3gb[2%], shards will be relocated away from this node    (there are much space in hard disk)

3. [2016-12-29T18:46:26,465][WARN ][o.e.t.TransportService   ] [2] Transport response handler not found of id [11849]
[2016-12-29T18:46:26,465][WARN ][o.e.t.TransportService   ] [2] Transport response handler not found of id [11850]
[2016-12-29T18:46:26,465][WARN ][o.e.t.TransportService   ] [2] Transport response handler not found of id [11851]
[2016-12-29T18:46:26,468][WARN ][o.e.t.TransportService   ] [2] Transport response handler not found of id [11815]
[2016-12-29T18:46:26,718][ERROR][i.n.u.c.D.rejectedExecution] Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:836) ~[netty-common-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:342) ~[netty-common-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:335) ~[netty-common-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:761) ~[netty-common-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:767) [netty-common-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:435) [netty-common-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:120) [netty-common-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1022) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:835) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:804) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:841) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at org.elasticsearch.http.netty4.Netty4HttpChannel.sendResponse(Netty4HttpChannel.java:138) [transport-netty4-5.0.1.jar:5.0.1]
	at org.elasticsearch.http.HttpServer$ResourceHandlingHttpChannel.sendResponse(HttpServer.java:184) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.rest.action.RestResponseListener.processResponse(RestResponseListener.java:37) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:47) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:91) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:87) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.support.TransportAction$ResponseFilterChain.proceed(TransportAction.java:224) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:82) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.support.TransportAction$ResponseFilterChain.proceed(TransportAction.java:222) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.ingest.IngestActionFilter.apply(IngestActionFilter.java:89) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.support.TransportAction$ResponseFilterChain.proceed(TransportAction.java:222) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.support.TransportAction$FilteredActionListener.onResponse(TransportAction.java:249) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.support.TransportAction$FilteredActionListener.onResponse(TransportAction.java:235) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.search.TransportMultiSearchAction$1.handleResponse(TransportMultiSearchAction.java:128) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.search.TransportMultiSearchAction$1.onResponse(TransportMultiSearchAction.java:117) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.search.TransportMultiSearchAction$1.onResponse(TransportMultiSearchAction.java:113) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:91) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:87) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.support.TransportAction$ResponseFilterChain.proceed(TransportAction.java:224) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:82) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.support.TransportAction$ResponseFilterChain.proceed(TransportAction.java:222) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.ingest.IngestActionFilter.apply(IngestActionFilter.java:89) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.support.TransportAction$ResponseFilterChain.proceed(TransportAction.java:222) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.support.TransportAction$FilteredActionListener.onResponse(TransportAction.java:249) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.support.TransportAction$FilteredActionListener.onResponse(TransportAction.java:235) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction$2.doRun(SearchQueryThenFetchAsyncAction.java:135) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:520) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.0.1.jar:5.0.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Operation**:
 1. create 2 nodes cluster
 2. do many query search

**Comment by colings86** [comment]
Hi @kevin-tang-rs 

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The Github issues list is reserved for bug reports and feature requests only. For the description you have provided it is not clear that this is a bug and it looks like you have multiple issues on your cluster including disk space issues. 

Please feel free to ask question on the discuss forum where you can find help on configuration and use of Elasticsearch in order to get your cluster into a stable state. 

If you believe there is a bug with Elasticsearch please provide clear reproducible steps that can be performed on a fresh cluster and reproduce the issue you are seeing.

thanks
