### ISSUE TITLE
Partial snapshots with ArrayIndexOutOfBoundsException failure

### ISSUE THREAD

**Issue by 8bitint** [elastic/elasticsearch#22409]
**Elasticsearch version**: 2.3.4

**Plugins installed**: []

**JVM version**: Oracle 1.8.0_40

**OS version**: Oracle Enterprise Linux 6.3

**Description of the problem including expected versus actual behavior**:

We are seeing partial snapshots being created with ArrayIndexOutOfBoundsExceptions after a week of successful snapshot creation. The failures we are seeing are:

```
{
      "shard_id": 2,
      "status": "INTERNAL_SERVER_ERROR",
      "node_id": "bmYrf6rCS7OdPB_LWDXrqQ",
      "index": "805330515.indexname_0",
      "reason": "IndexShardSnapshotFailedException[256]; nested: ArrayIndexOutOfBoundsException[256]; "
}
```

Our current workaround is to remove the the snapshot repository and recreate it. We are then able to create full snapshots for a week or two.

**Steps to reproduce**:
 1. Trigger a snapshot

**Provide logs (if relevant)**:

```
5330503.comments][2]] [hostname 20170102232100364] failed to create snapshot
** [out :: hostname] org.elasticsearch.index.snapshots.IndexShardSnapshotFailedException: 256
 ** [out :: hostname] at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository.snapshot(BlobStoreIndexShardRepository.java:201)
 ** [out :: hostname] at org.elasticsearch.snapshots.SnapshotShardsService.snapshot(SnapshotShardsService.java:340)
 ** [out :: hostname] at org.elasticsearch.snapshots.SnapshotShardsService.access$200(SnapshotShardsService.java:76)
 ** [out :: hostname] at org.elasticsearch.snapshots.SnapshotShardsService$1.doRun(SnapshotShardsService.java:296)
 ** [out :: hostname] at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
 ** [out :: hostname] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 ** [out :: hostname] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 ** [out :: hostname] at java.lang.Thread.run(Thread.java:745)
 ** [out :: hostname] Caused by: java.lang.ArrayIndexOutOfBoundsException: 256
 ** [out :: hostname] at com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer.addName(ByteQuadsCanonicalizer.java:853)
 ** [out :: hostname] at com.fasterxml.jackson.dataformat.smile.SmileParser._addDecodedToSymbols(SmileParser.java:1613)
 ** [out :: hostname] at com.fasterxml.jackson.dataformat.smile.SmileParser._handleFieldName(SmileParser.java:1528)
 ** [out :: hostname] at com.fasterxml.jackson.dataformat.smile.SmileParser.nextToken(SmileParser.java:587)
 ** [out :: hostname] at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:53)
 ** [out :: hostname] at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardSnapshots.fromXContent(BlobStoreIndexShardSnapshots.java:262)
 ** [out :: hostname] at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardSnapshots.fromXContent(BlobStoreIndexShardSnapshots.java:48)
 ** [out :: hostname] at org.elasticsearch.repositories.blobstore.BlobStoreFormat.read(BlobStoreFormat.java:107)
 ** [out :: hostname] at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.readBlob(ChecksumBlobStoreFormat.java:102)
 ** [out :: hostname] at org.elasticsearch.repositories.blobstore.BlobStoreFormat.read(BlobStoreFormat.java:83)
 ** [out :: hostname] at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$Context.buildBlobStoreIndexShardSnapshots(BlobStoreIndexShardRepository.java:469)
 ** [out :: hostname] at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.snapshot(BlobStoreIndexShardRepository.java:537)
 ** [out :: hostname] at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository.snapshot(BlobStoreIndexShardRepository.java:191)
 ** [out :: hostname] ... 7 common frames omitted
 ** [out :: hostname] 2017-01-03T10:21:00,803+11:00 [] [] [@] [] [] [elasticsearch[hostname][clusterService#updateTask][T#1]] INFO  o.elasticsearch.snapshots - [hostname] snapshot [indexname_20170102232100364] is done
```

**Comment by ywelsch** [comment]
This seems to be a bug in the third-party JSON parser library that ES uses. Upgrade ES to v2.4.3 which has a newer version of the Jackson dependency. /cc: @tlrx

**Comment by 8bitint** [comment]
Thanks for getting back to us. We'll try the upgrade in the next couple of weeks.
