### ISSUE TITLE
ReceiveTimeoutTransportException

### ISSUE THREAD

**Issue by srithank** [elastic/elasticsearch#22453]
**Elasticsearch version**: 2.3.3

**OS version**:windows2012 r2, 8gb RAM,

**Description of the problem including expected versus actual behavior**:
i'm getting timed out on the kibana( Request Timeout after 30000ms)

This is the clusterhealth
```
{
"cluster_name": "elk",
"status": "green",
"timed_out": false,
"number_of_nodes": 3,
"number_of_data_nodes": 3,
"active_primary_shards": 3346,
"active_shards": 6692,
"relocating_shards": 2,
"initializing_shards": 0,
"unassigned_shards": 0,
"delayed_unassigned_shards": 0,
"number_of_pending_tasks": 9,
"number_of_in_flight_fetch": 0,
"task_max_waiting_in_queue_millis": 102585,
"active_shards_percent_as_number": 100
}
```

**Provide logs (if relevant)**:
This is the elastic search logs
 ```
[2017-01-05 10:28:43,596][DEBUG][action.admin.cluster.node.stats] [dt1elastic01] failed to execute on node [qr3HuGq7S9ChFzSrGoastA]
ReceiveTimeoutTransportException[[dt1elastic02][10.90.8.187:9300][cluster:monitor/nodes/stats[n]] request_id [222281] timed out after [15001ms]]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-01-05 10:29:43,601][DEBUG][action.admin.cluster.node.stats] [dt1elastic01] failed to execute on node [qr3HuGq7S9ChFzSrGoastA]
ReceiveTimeoutTransportException[[dt1elastic02][10.90.8.187:9300][cluster:monitor/nodes/stats[n]] request_id [222417] timed out after [15001ms]]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

What steps should I follow to fix this error?

**Comment by jasontedor** [comment]
There is not enough information to debug this. I suggest opening a topic on the [forum](https://discuss.elastic.co) as we reserve GitHub for verified bug reports and feature requests.
