### ISSUE TITLE
cannot find ActiveShardCount

### ISSUE THREAD

**Issue by listenyourheart** [elastic/elasticsearch#22505]
Hello , 

When I call the delete API by query with this code 
BulkIndexByScrollResponse response =
                DeleteByQueryAction.INSTANCE.newRequestBuilder(client)
                        .filter(QueryBuilders.matchQuery(esProjectIdField, projectId))
                        .source(index)
                        .get();

I get this error : 

java.lang.ClassNotFoundException: org.elasticsearch.action.support.ActiveShardCount
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_111]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_111]
	at org.elasticsearch.index.reindex.AbstractBulkByScrollRequest.<init>(AbstractBulkByScrollRequest.java:77) ~[reindex-client-5.1.1.jar:5.1.1]
	at org.elasticsearch.index.reindex.DeleteByQueryRequest.<init>(DeleteByQueryRequest.java:57) ~[reindex-client-5.1.1.jar:5.1.1]
	at org.elasticsearch.index.reindex.DeleteByQueryRequest.<init>(DeleteByQueryRequest.java:53) ~[reindex-client-5.1.1.jar:5.1.1]
	at org.elasticsearch.index.reindex.DeleteByQueryRequestBuilder.<init>(DeleteByQueryRequestBuilder.java:38) ~[reindex-client-5.1.1.jar:5.1.1]
	at org.elasticsearch.index.reindex.DeleteByQueryRequestBuilder.<init>(DeleteByQueryRequestBuilder.java:32) ~[reindex-client-5.1.1.jar:5.1.1]
	at org.elasticsearch.index.reindex.DeleteByQueryAction.newRequestBuilder(DeleteByQueryAction.java:36) ~[reindex-client-5.1.1.jar:5.1.1]

I tried with the version 5.0.0 and 5.1.1 , 
I can not find this class **ActiveShardCount** in the package **org.elasticsearch.action.support.**
do you have already encounter this problem ?
thank you for help

**Comment by clintongormley** [comment]
@nik9000 @tlrx could you shed any light here?

**Comment by tlrx** [comment]
The `ActiveShardCount` class has been added in #18985 and has not moved since version 5.0.0-alpha5. Can you try to declare both `elasticsearch` and `reindex-client` as dependencies in your project and use `client.execute(DeleteByQueryAction.INSTANCE, new DeleteByQueryRequest(searchRequest))` instead?

**Comment by listenyourheart** [comment]
Hello, thank you for reply , 
I finally found my problem ! is that the server version elastic search is 2.4 while the java API I was using is 5.0.0. I solved my problem by doing a first query get with filters then a delete by id

**Comment by listenyourheart** [comment]
@clintongormley @tlrx  thank you
