### ISSUE TITLE
failed to flush export bulks

### ISSUE THREAD

**Issue by wh211212** [elastic/elasticsearch#22516]
**Elasticsearch version**:Elasticsearch 5.1.1

**Plugins installed**: []x-pack

**JVM version**:1.8.0_111

**OS version**:CentOS 7.3 CentOS 6.8

**Description of the problem including expected versus actual behavior**:
after install x-pack ,restart Elasticsearch faild,export some error
**Steps to reproduce**:
 1. I remove data path all file,then restart Elasticsearch  still failed
 2. 
 3.

**Provide logs (if relevant)**:
[2017-01-10T12:03:32,508][ERROR][o.e.x.m.AgentService     ] [elastic-2] exception when exporting documents
org.elasticsearch.xpack.monitoring.exporter.ExportException: failed to flush export bulks
	at org.elasticsearch.xpack.monitoring.exporter.ExportBulk$Compound.doFlush(ExportBulk.java:148) ~[x-pack-5.1.1.jar:5.1.1]
	at org.elasticsearch.xpack.monitoring.exporter.ExportBulk.close(ExportBulk.java:77) ~[x-pack-5.1.1.jar:5.1.1]
	at org.elasticsearch.xpack.monitoring.exporter.Exporters.export(Exporters.java:194) ~[x-pack-5.1.1.jar:5.1.1]
	at org.elasticsearch.xpack.monitoring.AgentService$ExportingWorker.run(AgentService.java:208) [x-pack-5.1.1.jar:5.1.1]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Describe the feature**:

**Comment by clintongormley** [comment]
Please consult the Elasticsearch logs to find out the problem.  
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks

**Comment by rprots** [comment]
Related: https://discuss.elastic.co/t/errors-after-installing-x-pack/64210
