### ISSUE TITLE
Unhandled query size parameter

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#22530]
**Elasticsearch version**: ES 5.x

**Plugins installed**: none

**JVM version**: Any

**OS version**: Any

[1] Using `-1` for the size returns top 10 results

```
POST /_search
{
  "size": -1
}
```

[2] Using any number `<-1` returns an unhandled Lucene error:

```
POST /_search
{
  "size": -2
}


# Result


[2017-01-10T13:30:28,890][DEBUG][o.e.a.s.TransportSearchAction] [oZ4lS-x] All shards failed for phase: [query]
org.elasticsearch.transport.RemoteTransportException: [oZ4lS-x][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: Query Failed [Failed to execute main query]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:405) ~[elasticsearch-5.1.0.jar:5.1.0]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:106) ~[elasticsearch-5.1.0.jar:5.1.0]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:259) ~[elasticsearch-5.1.0.jar:5.1.0]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:273) ~[elasticsearch-5.1.0.jar:5.1.0]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:300) ~[elasticsearch-5.1.0.jar:5.1.0]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:297) ~[elasticsearch-5.1.0.jar:5.1.0]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.1.0.jar:5.1.0]
	at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:577) [elasticsearch-5.1.0.jar:5.1.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:527) [elasticsearch-5.1.0.jar:5.1.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.1.0.jar:5.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.IllegalArgumentException: numHits must be > 0; please use TotalHitCountCollector if you just need the total hit count
	at org.apache.lucene.search.TopScoreDocCollector.create(TopScoreDocCollector.java:170) ~[lucene-core-6.3.0.jar:6.3.0 a66a44513ee8191e25b477372094bfa846450316 - shalin - 2016-11-02 19:47:11]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:219) ~[elasticsearch-5.1.0.jar:5.1.0]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:106) ~[elasticsearch-5.1.0.jar:5.1.0]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:259) ~[elasticsearch-5.1.0.jar:5.1.0]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:273) ~[elasticsearch-5.1.0.jar:5.1.0]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:300) ~[elasticsearch-5.1.0.jar:5.1.0]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:297) ~[elasticsearch-5.1.0.jar:5.1.0]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.1.0.jar:5.1.0]
	at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:577) ~[elasticsearch-5.1.0.jar:5.1.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:527) ~[elasticsearch-5.1.0.jar:5.1.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.1.0.jar:5.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_45]
```

I think that the `QueryPhase` class should catch this before being an exception, so we avoid the exception thrown by `TopScoreDocCollector`. In other words, any number below 0 should return a custom Elasticsearch exception.

Also, reading the code i don't understand why `-1` is just handled correctly.

**Comment by makeyang** [comment]
@gmoskovicz  cause -1 is taken is not set and then it will be set default value.

**Comment by makeyang** [comment]
@clintongormley  I give a pull request to fix this issue. it is: https://github.com/elastic/elasticsearch/pull/22579
can you please help to review it? thanks
