### ISSUE TITLE
[CI] NullPointerException in TermsAggregatorTests.testTermsAggregator on master

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#22602]
With this failure:

```
ERROR   2.57s | TermsAggregatorTests.testTermsAggregator <<< FAILURES!
   > Throwable #1: ElasticsearchException[java.lang.NullPointerException]; nested: NullPointerException;
   > 	at __randomizedtesting.SeedInfo.seed([4A11D54417D68D31:CD798C901EBD89AD]:0)
   > 	at org.elasticsearch.index.fielddata.plain.SortedSetDVOrdinalsIndexFieldData.loadGlobal(SortedSetDVOrdinalsIndexFieldData.java:102)
   > 	at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals$FieldData.globalOrdinalsValues(ValuesSource.java:150)
   > 	at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals.globalMaxOrd(ValuesSource.java:123)
   > 	at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.doCreateInternal(TermsAggregatorFactory.java:118)
   > 	at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:55)
   > 	at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:221)
   > 	at org.elasticsearch.search.aggregations.AggregatorTestCase.createAggregator(AggregatorTestCase.java:111)
   > 	at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorTests.testTermsAggregator(TermsAggregatorTests.java:77)
   > 	at java.lang.Thread.run(Thread.java:745)
   > Caused by: java.lang.NullPointerException
   > 	at org.elasticsearch.index.fielddata.plain.SortedSetDVOrdinalsIndexFieldData.loadGlobal(SortedSetDVOrdinalsIndexFieldData.java:97)
   > 	... 44 more
  2> NOTE: leaving temporary files on disk at: /home/hinmanm/es/elasticsearch/core/build/testrun/test/J0/temp/org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorTests_4A11D54417D68D31-001
  2> NOTE: test params are: codec=Asserting(Lucene62): {}, docValues:{string=DocValuesFormat(name=Asserting)}, maxPointsInLeafNode=1027, maxMBSortInHeap=6.243270599203402, sim=RandomSimilarity(queryNorm=true,coord=no): {}, locale=en-MT, timezone=Asia/Dushanbe
  2> NOTE: Linux 4.8.15-300.fc25.x86_64 amd64/Oracle Corporation 1.8.0_111 (64-bit)/cpus=4,threads=1,free=457397376,total=514850816
  2> NOTE: All tests run in this JVM: [TermsAggregatorTests]
Completed [1/1] in 5.03s, 1 test, 1 error <<< FAILURES!
```

Seen from CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-intake/579/console

Reproduces with:

```
gradle :core:test -Dtests.seed=4A11D54417D68D31 -Dtests.class=org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorTests -Dtests.method="testTermsAggregator" -Dtests.security.manager=true -Dtests.locale=en-MT -Dtests.timezone=Asia/Dushanbe
```

**Comment by jimczi** [comment]
I pushed a fix in master and 5.x for this:
https://github.com/elastic/elasticsearch/commit/f18d5f22ce8649ac5ca58c7c275946e6a069ca84
