### ISSUE TITLE
Bootstrap failed

### ISSUE THREAD

**Issue by tramchamploo** [elastic/elasticsearch#22604]
**Elasticsearch version**:
5.1.2
**Plugins installed**: [none]

**JVM version**:
JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_65/25.65-b01
**OS version**:
OS[Linux/3.10.0-229.el7.x86_64/amd64]

Elasticsearch directory owner is user I logged in and not root. On my other machines, bootstrap is fine.
```
[2017-01-13T15:09:01,463][INFO ][o.e.p.PluginsService     ] [node-10.69.2.221] no plugins loaded
[2017-01-13T15:09:03,737][INFO ][o.e.n.Node               ] [node-10.69.2.221] initialized
[2017-01-13T15:09:03,737][INFO ][o.e.n.Node               ] [node-10.69.2.221] starting ...
[2017-01-13T15:09:03,777][INFO ][i.n.u.i.PlatformDependent] Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
[2017-01-13T15:09:03,905][INFO ][o.e.t.TransportService   ] [node-10.69.2.221] publish_address {10.69.2.221:9300}, bound_addresses {10.69.2.221:9300}
[2017-01-13T15:09:03,910][INFO ][o.e.b.BootstrapCheck     ] [node-10.69.2.221] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2017-01-13T15:09:03,913][ERROR][o.e.b.Bootstrap          ] [node-10.69.2.221] node validation exception
bootstrap checks failed
initial heap size [260046848] not equal to maximum heap size [4152360960]; this can cause resize pauses and prevents mlockall from locking the entire heap
[2017-01-13T15:09:03,916][INFO ][o.e.n.Node               ] [node-10.69.2.221] stopping ...



2017-01-13 15:12:31,612 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at org.apache.logging.log4j.core.jmx.Server.register(Server.java:389)
        at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:167)
        at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:541)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:258)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:206)
        at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:220)
        at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:197)
        at org.elasticsearch.common.logging.LogConfigurator.configureStatusLogger(LogConfigurator.java:125)
        at org.elasticsearch.common.logging.LogConfigurator.configureWithoutConfig(LogConfigurator.java:67)
        at org.elasticsearch.cli.Command.main(Command.java:85)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)


2017-01-13 15:12:32,013 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at org.apache.logging.log4j.core.jmx.Server.register(Server.java:389)
        at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:167)
        at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:140)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:541)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:258)
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:116)
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:83)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:272)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112)
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
        at org.elasticsearch.cli.Command.main(Command.java:88)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)

[2017-01-13T15:12:32,213][INFO ][o.e.n.Node               ] [node-10.69.2.221] initializing ...
[2017-01-13T15:12:32,326][INFO ][o.e.e.NodeEnvironment    ] [node-10.69.2.221] using [1] data paths, mounts [[/data0 (/dev/sda7)]], net usable_space [83.3gb], net total_space [235.5gb], spins? [possibly], types [ext4]
[2017-01-13T15:12:32,326][INFO ][o.e.e.NodeEnvironment    ] [node-10.69.2.221] heap size [3.4gb], compressed ordinary object pointers [true]
[2017-01-13T15:12:32,327][INFO ][o.e.n.Node               ] [node-10.69.2.221] node name [node-10.69.2.221], node ID [Vhv-FpAbTla_8ehUSnrDQA]
[2017-01-13T15:12:32,330][INFO ][o.e.n.Node               ] [node-10.69.2.221] version[5.1.2], pid[227827], build[c8c4c16/2017-01-11T20:18:39.146Z], OS[Linux/3.10.0-229.el7.x86_64/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_65/25.65-b01]
[2017-01-13T15:12:33,348][INFO ][o.e.p.PluginsService     ] [node-10.69.2.221] loaded module [aggs-matrix-stats]
[2017-01-13T15:12:33,348][INFO ][o.e.p.PluginsService     ] [node-10.69.2.221] loaded module [ingest-common]
[2017-01-13T15:12:33,348][INFO ][o.e.p.PluginsService     ] [node-10.69.2.221] loaded module [lang-expression]
[2017-01-13T15:12:33,349][INFO ][o.e.p.PluginsService     ] [node-10.69.2.221] loaded module [lang-groovy]
[2017-01-13T15:12:33,349][INFO ][o.e.p.PluginsService     ] [node-10.69.2.221] loaded module [lang-mustache]
[2017-01-13T15:12:33,349][INFO ][o.e.p.PluginsService     ] [node-10.69.2.221] loaded module [lang-painless]
[2017-01-13T15:12:33,349][INFO ][o.e.p.PluginsService     ] [node-10.69.2.221] loaded module [percolator]
[2017-01-13T15:12:33,349][INFO ][o.e.p.PluginsService     ] [node-10.69.2.221] loaded module [reindex]
[2017-01-13T15:12:33,349][INFO ][o.e.p.PluginsService     ] [node-10.69.2.221] loaded module [transport-netty3]
[2017-01-13T15:12:33,349][INFO ][o.e.p.PluginsService     ] [node-10.69.2.221] loaded module [transport-netty4]
[2017-01-13T15:12:33,350][INFO ][o.e.p.PluginsService     ] [node-10.69.2.221] no plugins loaded
[2017-01-13T15:12:35,602][INFO ][o.e.n.Node               ] [node-10.69.2.221] initialized
[2017-01-13T15:12:35,602][INFO ][o.e.n.Node               ] [node-10.69.2.221] starting ...
[2017-01-13T15:12:35,641][INFO ][i.n.u.i.PlatformDependent] Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
[2017-01-13T15:12:35,770][INFO ][o.e.t.TransportService   ] [node-10.69.2.221] publish_address {10.69.2.221:9300}, bound_addresses {10.69.2.221:9300}
[2017-01-13T15:12:35,776][INFO ][o.e.b.BootstrapCheck     ] [node-10.69.2.221] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2017-01-13T15:12:35,778][ERROR][o.e.b.Bootstrap          ] [node-10.69.2.221] node validation exception
bootstrap checks failed
initial heap size [260046848] not equal to maximum heap size [4152360960]; this can cause resize pauses and prevents mlockall from locking the entire heap
[2017-01-13T15:12:35,782][INFO ][o.e.n.Node               ] [node-10.69.2.221] stopping ...

Exception: java.security.AccessControlException thrown from the UncaughtExceptionHandler in thread "Thread-4"
```

**Comment by dadoonet** [comment]
Please ask your questions on discuss.elastic.co.

Fix your environment here according to the guide (search for bootstrap checks)
