### ISSUE TITLE
org.elasticsearch.ElasticsearchParseException: No processor type exists with name "my plugin name"

### ISSUE THREAD

**Issue by deerawan** [elastic/elasticsearch#22676]
**Elasticsearch version**: 5.0.0

**Plugins installed**: my custom processor plugin

**JVM version**: 1.8.0_111

**OS version**: OSX El Capitan

**Description of the problem including expected versus actual behavior**:
1. I created my custom processor plugin with name "tax_date"
2. I installed it using `elasticsearch-plugin install` command
3. I removed the plugin using `elasticsearch-remove` command
4. I kept getting error said that  *org.elasticsearch.ElasticsearchParseException: No processor type exists with name tax_date*
5. Restart elasticsearch doesn't solve this issue. 

**Steps to reproduce**:
same as above. I have ensured that my plugin was not there in "loaded plugin" list. 

**Provide logs (if relevant)**:
![image](https://cloud.githubusercontent.com/assets/1243921/22062080/8723972a-ddaa-11e6-9aac-898d863a4c32.png)

```
[2017-01-18T18:10:14,607][INFO ][o.e.n.Node               ] [WYiAAg0] started
[2017-01-18T18:10:15,368][WARN ][o.e.c.s.ClusterService   ] [WYiAAg0] failed to notify ClusterStateListener
org.elasticsearch.ElasticsearchParseException: No processor type exists with name [tax_date]
	at org.elasticsearch.ingest.ConfigurationUtils.readProcessor(ConfigurationUtils.java:312) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.ingest.ConfigurationUtils.readProcessorConfigs(ConfigurationUtils.java:251) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.ingest.Pipeline$Factory.create(Pipeline.java:122) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.ingest.PipelineStore.innerUpdatePipelines(PipelineStore.java:79) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.ingest.PipelineStore.clusterChanged(PipelineStore.java:66) ~[elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.cluster.service.ClusterService.runTasksForExecutor(ClusterService.java:708) [elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.cluster.service.ClusterService$UpdateTask.run(ClusterService.java:894) [elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:444) [elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:237) [elasticsearch-5.0.0.jar:5.0.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:200) [elasticsearch-5.0.0.jar:5.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by clintongormley** [comment]
You have provided zero information about your custom plugin, where the problem seems to reside.

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
