### ISSUE TITLE
Dependency on org.apache.logging.log4j:log4j-api can't be optional

### ISSUE THREAD

**Issue by Gordiychuk** [elastic/elasticsearch#22671]
Dependency on transport client not enough for use transport client. 

```
<dependency>
    <groupId>org.elasticsearch.client</groupId>
    <artifactId>transport</artifactId>
    <version>5.1.2</version>
</dependency>
```

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.elasticsearch.client.Client]: Factory method 'elasticSearchClient' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/logging/log4j/Logger
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 98 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/Logger
	at org.elasticsearch.common.logging.Loggers.getLogger(Loggers.java:105)
	at org.elasticsearch.common.logging.Loggers.getLogger(Loggers.java:72)
	at org.elasticsearch.common.component.AbstractComponent.<init>(AbstractComponent.java:37)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:98)
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:94)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:119)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:247)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:125)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:111)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:101)
	at com.netcracker.search.worker.config.SpringConfiguration.elasticSearchClient(SpringConfiguration.java:43)
	at com.netcracker.search.worker.config.SpringConfiguration$$EnhancerBySpringCGLIB$$493d1f4d.CGLIB$elasticSearchClient$0(<generated>)
	at com.netcracker.search.worker.config.SpringConfiguration$$EnhancerBySpringCGLIB$$493d1f4d$$FastClassBySpringCGLIB$$8d72f9f6.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
	at com.netcracker.search.worker.config.SpringConfiguration$$EnhancerBySpringCGLIB$$493d1f4d.elasticSearchClient(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 99 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 120 common frames omitted
```

Dependency tree for transport client looks like 

```
[INFO] +- org.elasticsearch.client:transport:jar:5.1.2:compile
[INFO] |  +- org.elasticsearch.plugin:transport-netty3-client:jar:5.1.2:compile
[INFO] |  |  \- io.netty:netty:jar:3.10.6.Final:compile
[INFO] |  +- org.elasticsearch.plugin:transport-netty4-client:jar:5.1.2:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.6.Final:compile
[INFO] |  |  +- io.netty:netty-codec:jar:4.1.6.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.6.Final:compile
[INFO] |  |  +- io.netty:netty-common:jar:4.1.6.Final:compile
[INFO] |  |  +- io.netty:netty-handler:jar:4.1.6.Final:compile
[INFO] |  |  +- io.netty:netty-resolver:jar:4.1.6.Final:compile
[INFO] |  |  \- io.netty:netty-transport:jar:4.1.6.Final:compile
[INFO] |  +- org.elasticsearch.plugin:reindex-client:jar:5.1.2:compile
[INFO] |  |  \- org.elasticsearch.client:rest:jar:5.1.2:compile
[INFO] |  |     +- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
[INFO] |  |     +- org.apache.httpcomponents:httpcore:jar:4.4.5:compile
[INFO] |  |     +- org.apache.httpcomponents:httpasyncclient:jar:4.1.2:compile
[INFO] |  |     +- org.apache.httpcomponents:httpcore-nio:jar:4.4.5:compile
[INFO] |  |     \- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  +- org.elasticsearch.plugin:lang-mustache-client:jar:5.1.2:compile
[INFO] |  |  \- com.github.spullara.mustache.java:compiler:jar:0.9.3:compile
[INFO] |  \- org.elasticsearch.plugin:percolator-client:jar:5.1.2:compile
```

As you can see, optional dependency on log4j absent and as a result, we can't use transport client without add manually dependency on log4j-api. 

Let's change line https://github.com/elastic/elasticsearch/blob/master/core/build.gradle#L84
from 
```
 compile "org.apache.logging.log4j:log4j-api:${versions.log4j}", optional
```
to 
```
 compile "org.apache.logging.log4j:log4j-api:${versions.log4j}"
```

**Comment by jasontedor** [comment]
I don't think this is right, I think you can use a bridge to SLF4J and use another logging framework. And if that's not right, we should make it right instead of making this dependency non-optional.

**Comment by Gordiychuk** [comment]
> I don't think this is right, I think you can use a bridge to SLF4J and use another logging framework.

Yes, we can, but bridge uses as implementation for API. 
```
  compile "org.apache.logging.log4j:log4j-api:${versions.log4j}", optional //api
  compile "org.apache.logging.log4j:log4j-core:${versions.log4j}", optional //impl
```
I want to save dependency on implementation as optional. In dependency tree will exists only log4j-api, and it allow user specify which implementation use bridge over slf4j or log4j. 

```
<dependency>
    <groupId>org.elasticsearch.client</groupId>
    <artifactId>transport</artifactId>
    <version>5.1.2</version>
</dependency>
<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-slf4j-impl</artifactId>
    <version>2.7</version>
</dependency>
```

**Comment by Gordiychuk** [comment]
@jasontedor do you want replace inside elasticsearch logging from log4j to slf4j?

**Comment by jasontedor** [comment]
This works for me, this is an example using logback instead of Log4j 2, and the Log4j 2 dependency is not on the classpath, just the bridge. I think this establishes the dependency is not required, and we definitely do not want to make it required.

`build.gradle`:

```gradle
group 'me.tedor.jason'
version '1.0.0-SNAPSHOT'

apply plugin: 'java'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile group: 'org.elasticsearch.client', name: 'transport', version: '5.1.2'
    compile group: 'org.apache.logging.log4j', name: 'log4j-to-slf4j', version: '2.7'
    compile group: 'org.slf4j', name: 'slf4j-api', version: '1.7.21'
    compile group: 'ch.qos.logback', name: 'logback-classic', version: '1.1.8'
    testCompile group: 'junit', name: 'junit', version: '4.11'
}

task runTransportClientExample(type: JavaExec) {
    classpath = sourceSets.main.runtimeClasspath

    main = 'me.tedor.jason.transport_client_example.TransportClientExample'

    args commandLineArgs
}
```

`settings.gradle`:

```gradle
rootProject.name = 'transport-client-example'
```

`src/main/java/me/tedor/jason/transport_client_example/TransportClientExample.java`:

```java
package me.tedor.jason.transport_client_example;

import org.elasticsearch.client.transport.TransportClient;
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.common.transport.InetSocketTransportAddress;
import org.elasticsearch.transport.client.PreBuiltTransportClient;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.net.InetAddress;

public class TransportClientExample {

    public static void main(String[] args) {
        if (args.length != 1) {
            throw new IllegalArgumentException("usage: me.tedor.jason.TransportClientExample [index]");
        }
        new TransportClientExample().run(args[0]);
    }

    private final Logger logger = LoggerFactory.getLogger(getClass());
    private final TransportClient client =
            new PreBuiltTransportClient(Settings.EMPTY)
                    .addTransportAddress(new InetSocketTransportAddress(InetAddress.getLoopbackAddress(), 9300));

    private TransportClientExample() {
        final Logger rootLogger = LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);
    }

    private void run(final String index) {
        logger.info("client will create index [{}]", index);
        client.admin().indices().prepareCreate(index).get();
        logger.info("client successfully created index [{}]", index);
        logger.info("client will delete index [{}]", index);
        client.admin().indices().prepareDelete(index).get();
        logger.info("client successfully deleted index [{}]", index);
    }

}
```

`src/main/resources/logback.xml`:

```xml
<configuration debug="true">

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="info">
        <appender-ref ref="STDOUT" />
    </root>
</configuration>
```

And then:

```bash
09:56:59 [jason:~/src/jasontedor/transport-client-example] 1 $ gradle runTransportClientExample -PcommandLineArgs=test-index
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:runTransportClientExample
09:58:27,138 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
09:58:27,138 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
09:58:27,138 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/Users/jason/src/jasontedor/transport-client-example/build/resources/main/logback.xml]
09:58:27,219 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:58:27,221 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
09:58:27,227 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
09:58:27,249 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
09:58:27,249 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
09:58:27,249 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
09:58:27,250 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@445b84c0 - Registering current configuration as safe fallback point
09:58:27.490 [main] INFO  o.e.plugins.PluginsService - no modules loaded
09:58:27.494 [main] INFO  o.e.plugins.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
09:58:27.494 [main] INFO  o.e.plugins.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
09:58:27.494 [main] INFO  o.e.plugins.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
09:58:27.494 [main] INFO  o.e.plugins.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
09:58:27.494 [main] INFO  o.e.plugins.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
09:58:28.351 [main] INFO  m.t.j.t.TransportClientExample - client will create index [test-index]
09:58:28.587 [main] INFO  m.t.j.t.TransportClientExample - client successfully created index [test-index]
09:58:28.587 [main] INFO  m.t.j.t.TransportClientExample - client will delete index [test-index]
09:58:28.821 [main] INFO  m.t.j.t.TransportClientExample - client successfully deleted index [test-index]

BUILD SUCCESSFUL

Total time: 4.707 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.13/userguide/gradle_daemon.html
09:58:29 [jason:~/src/jasontedor/transport-client-example] $ 
```

And on my cluster:

```
[2017-01-18T09:58:17,183][INFO ][o.e.n.Node               ] [] initializing ...
[2017-01-18T09:58:17,239][INFO ][o.e.e.NodeEnvironment    ] [23YKuCt] using [1] data paths, mounts [[/ (/dev/disk1)]], net usable_space [240.5gb], net total_space [464.7gb], spins? [unknown], types [hfs]
[2017-01-18T09:58:17,239][INFO ][o.e.e.NodeEnvironment    ] [23YKuCt] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-01-18T09:58:17,240][INFO ][o.e.n.Node               ] node name [23YKuCt] derived from node ID [23YKuCtmR0uV5VXxExRHCQ]; set [node.name] to override
[2017-01-18T09:58:17,242][INFO ][o.e.n.Node               ] version[5.1.2], pid[50823], build[c8c4c16/2017-01-11T20:18:39.146Z], OS[Mac OS X/10.12.2/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_121/25.121-b13]
[2017-01-18T09:58:17,806][INFO ][o.e.p.PluginsService     ] [23YKuCt] loaded module [aggs-matrix-stats]
[2017-01-18T09:58:17,807][INFO ][o.e.p.PluginsService     ] [23YKuCt] loaded module [ingest-common]
[2017-01-18T09:58:17,807][INFO ][o.e.p.PluginsService     ] [23YKuCt] loaded module [lang-expression]
[2017-01-18T09:58:17,807][INFO ][o.e.p.PluginsService     ] [23YKuCt] loaded module [lang-groovy]
[2017-01-18T09:58:17,807][INFO ][o.e.p.PluginsService     ] [23YKuCt] loaded module [lang-mustache]
[2017-01-18T09:58:17,807][INFO ][o.e.p.PluginsService     ] [23YKuCt] loaded module [lang-painless]
[2017-01-18T09:58:17,807][INFO ][o.e.p.PluginsService     ] [23YKuCt] loaded module [percolator]
[2017-01-18T09:58:17,807][INFO ][o.e.p.PluginsService     ] [23YKuCt] loaded module [reindex]
[2017-01-18T09:58:17,807][INFO ][o.e.p.PluginsService     ] [23YKuCt] loaded module [transport-netty3]
[2017-01-18T09:58:17,808][INFO ][o.e.p.PluginsService     ] [23YKuCt] loaded module [transport-netty4]
[2017-01-18T09:58:17,808][INFO ][o.e.p.PluginsService     ] [23YKuCt] no plugins loaded
[2017-01-18T09:58:19,164][INFO ][o.e.n.Node               ] initialized
[2017-01-18T09:58:19,164][INFO ][o.e.n.Node               ] [23YKuCt] starting ...
[2017-01-18T09:58:19,311][INFO ][o.e.t.TransportService   ] [23YKuCt] publish_address {127.0.0.1:9300}, bound_addresses {[fe80::1]:9300}, {[::1]:9300}, {127.0.0.1:9300}
[2017-01-18T09:58:22,368][INFO ][o.e.c.s.ClusterService   ] [23YKuCt] new_master {23YKuCt}{23YKuCtmR0uV5VXxExRHCQ}{5yShIZ1lQRmbGJOsVtTF9A}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-01-18T09:58:22,386][INFO ][o.e.h.HttpServer         ] [23YKuCt] publish_address {127.0.0.1:9200}, bound_addresses {[fe80::1]:9200}, {[::1]:9200}, {127.0.0.1:9200}
[2017-01-18T09:58:22,386][INFO ][o.e.n.Node               ] [23YKuCt] started
[2017-01-18T09:58:22,391][INFO ][o.e.g.GatewayService     ] [23YKuCt] recovered [0] indices into cluster_state
[2017-01-18T09:58:28,422][INFO ][o.e.c.m.MetaDataCreateIndexService] [23YKuCt] [test-index] creating index, cause [api], templates [], shards [5]/[1], mappings []
```

**Comment by jasontedor** [comment]
> do you want replace inside elasticsearch logging from log4j to slf4j?

No, that's not going to happen. It's simpler for the server to support exactly one logging framework, and I do not like abstraction layers that do not let you take advantage of the preferred underlying implementation (you have to code to the lowest common denominator).

**Comment by Gordiychuk** [comment]
Ok, i agree it works. But if we check dependency list for `org.apache.logging.log4j:log4j-to-slf4j` we will find in list `org.apache.logging.log4j:log4j-api`. API jar in dependency list allow us not fail with `ClassNotFoundException`, and if user not add implementation to dependency list we will get warning, but code will still work. 
I thinks optional dependency, it's dependency without that code can still works, it our case it's not true.

**Comment by jasontedor** [comment]
> I thinks optional dependency, it's dependency without that code can still works, it our case it's not true.

Please provide a stack trace.

**Comment by Gordiychuk** [comment]
@jasontedor 

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.elasticsearch.client.Client]: Factory method 'elasticSearchClient' threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/logging/log4j/Logger
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 98 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/Logger
	at org.elasticsearch.common.logging.Loggers.getLogger(Loggers.java:105)
	at org.elasticsearch.common.logging.Loggers.getLogger(Loggers.java:72)
	at org.elasticsearch.common.component.AbstractComponent.<init>(AbstractComponent.java:37)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:98)
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:94)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:119)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:247)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:125)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:111)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:101)
	at com.netcracker.search.worker.config.SpringConfiguration.elasticSearchClient(SpringConfiguration.java:43)
	at com.netcracker.search.worker.config.SpringConfiguration$$EnhancerBySpringCGLIB$$493d1f4d.CGLIB$elasticSearchClient$0(<generated>)
	at com.netcracker.search.worker.config.SpringConfiguration$$EnhancerBySpringCGLIB$$493d1f4d$$FastClassBySpringCGLIB$$8d72f9f6.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
	at com.netcracker.search.worker.config.SpringConfiguration$$EnhancerBySpringCGLIB$$493d1f4d.elasticSearchClient(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 99 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 120 common frames omitted
```

**Comment by jasontedor** [comment]
You're not providing enough information here, what are you binding the logging to?

**Comment by jasontedor** [comment]
Again, you either have to pull in the optional Log4j 2 dependencies, or use the SLF4J bridge like I showed. So, what I'm looking for from you is a problem where you pulled in the dependencies and it didn't work, or you pulled in the bridge and it didn't work. But if you're not pulling in either then of course you're going to have problems.

**Comment by Gordiychuk** [comment]
As i sad before, client not working without additional dependency. Adding dependency to log4j or bridge solve it proble, but it's looks like WA. Because for example if my problem use only sl4j and I want use transport client i get exception about until not add bridge or log4j-api.

**Comment by jasontedor** [comment]
> Adding dependency to log4j or bridge solve it proble, but it's looks like WA.

I'm so sorry, but I do not understand "WA"? Can you elaborate what you mean here?

> Because for example if my problem use only sl4j and I want use transport client i get exception about until not add bridge or log4j-api.

We document this though, the dependency is optional, you [have to use it], or [use the bridge](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/_using_another_logger.html).

**Comment by mrmiroslav** [comment]
This is all great, I have been trying in a variety of ways now, including adding "log4j-to-slf4j".

However I am getting stuck on:

```
com.google.cloud.dataflow.sdk.util.UserCodeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.AbstractMethodError: org.apache.logging.slf4j.SLF4JLogger.isEnabled(Lorg/apache/logging/log4j/Level;Lorg/apache/logging/log4j/Marker;Ljava/lang/String;Ljava/lang/Object;)Z
```

**Comment by junghoahnsc** [comment]
We had the same issue with the transport 5.2.1. I tried to use the bridge, but got the same `java.lang.AbstractMethodError` error.

Is there any workaround on this?

**Comment by jasontedor** [comment]
I think that this is caused by version mismatches. I would suggest opening a topic on [forum](https://discuss.elastic.co), link to it from here, and I (or someone else from the community) will try to help. Please post as much detail as possible.

**Comment by sprgn** [comment]
Same issue here.  This dependency on log4j-core is a very hard dependency on a logging implementation.  Is there not a way to disable log4j when elasticsearch is used as part of an app that uses other logging implementation other than log4j?

**Comment by hristo-vrigazov** [comment]
+1

**Comment by jasontedor** [comment]
I do not understand why this issue continues to receive attention. I have shown [previously](https://github.com/elastic/elasticsearch/issues/22671#issuecomment-273498813) that the dependency on log4j-api is optional, you can use another logging implementation in your application without relying on this dependency.

@sprgn Would you please explain why you think that log4j-core is required (see my previous example, I think it's not, you can use a different logging implementation in your application)?

@hristo-vrigazov Why did you +1 this issue, what are you trying to communicate? I want to help you.

**Comment by Gordiychuk** [comment]
@jasontedor dependency to core can't be required, but dependency to api required to avoid this problem in future, when someone add dependency on elasticsearch and it's not work because need add additional transitive dependency that not describe in poms.

**Comment by jasontedor** [comment]
Okay, I understand the source of the confusion. Thank you @Gordiychuk.

**Comment by hristo-vrigazov** [comment]
@jasontedor +1 usually means "I am also experiencing this problem". I understand that you are trying to help, but it is annoying to be forced to add a bridge or log4j just because I want to use a simple client for Elastic. I understand that it is not the end of the world, but if every framework in the world forced you to add additional things outside of what it is meant to do, it would quickly become extremely difficult to track what is needed and why. What bugs me even more that this problem with log4j appears at runtime. If I start cleaning up dependencies and delete the bridge dependency, everything will build and will be fine and only when I am using the application will the problem appear.

**Comment by jasontedor** [comment]
@Gordiychuk I opened #25136 to address the confusion on the API dependency.

**Comment by jasontedor** [comment]
@hristo-vrigazov Yeah, no one likes that the transport client is so heavily entangled with the server implementation. I wish we could snap our fingers and make it go away but we can't. It's a very long road for us to build a client that is as functional at a high-level as the transport client yet for it to not be dependent on the server implementation. For now, the best we can do is iterate on what we have. I hope marking the API dependency as non-optional at least clarifies the situation.

**Comment by Gordiychuk** [comment]
@jasontedor good, thanks.

**Comment by rosacanada** [comment]
I had the same issue on Tomcat which hosts multiple applications. It happens when redeploy an app or deploy new app. Even the app run well before, without any config/ dependency change, just redeploy fail with this error.  Whenever it happens, restart Tomcat solved the issue for my case.
