### ISSUE TITLE
[Tests] TopHitsAggregatorTests#testInsideTerms fails reproducibly

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#22818]
This one fails reproducibly on master (2abe948cd7b492f583cae066f59904c0f4253d20): 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-unix-compatibility/os=ubuntu/475

'''
gradle :core:test -Dtests.seed=E1AB0588265D530F -Dtests.class=org.elasticsearch.search.aggregations.metrics.tophits.TopHitsAggregatorTests -Dtests.method="testInsideTerms" -Dtests.security.manager=true -Dtests.locale=en-IE -Dtests.timezone=Israel
'''

Error looks like this:
```
ERROR   0.04s J1 | TopHitsAggregatorTests.testInsideTerms <<< FAILURES!
   > Throwable #1: java.lang.ClassCastException: org.apache.lucene.index.ParallelCompositeReader cannot be cast to org.apache.lucene.index.DirectoryReader
   > 	at __randomizedtesting.SeedInfo.seed([E1AB0588265D530F:11E1E897EE56B196]:0)
   > 	at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals$FieldData.globalOrdinalsValues(ValuesSource.java:150)
   > 	at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals.globalMaxOrd(ValuesSource.java:123)
   > 	at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.doCreateInternal(TermsAggregatorFactory.java:118)
   > 	at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:55)
   > 	at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:221)
   > 	at org.elasticsearch.search.aggregations.AggregatorTestCase.createAggregator(AggregatorTestCase.java:121)
   > 	at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:167)
   > 	at org.elasticsearch.search.aggregations.metrics.tophits.TopHitsAggregatorTests.testCase(TopHitsAggregatorTests.java:135)
   > 	at org.elasticsearch.search.aggregations.metrics.tophits.TopHitsAggregatorTests.testInsideTerms(TopHitsAggregatorTests.java:83)
   > 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cbuescher** [comment]
@nik9000 would you mind taking a look since you recently introduced that test?

**Comment by nik9000** [comment]
Sure!

**Comment by nik9000** [comment]
I fixed it by being careful about getting the reader. The same fix that the `TermsAggregatorTests` uses.

master: 1baa884ab784c4bd78b719d1ea3b4f7fc42dc3bf
5.x:
