### ISSUE TITLE
Assertion tripping in InternalEngine#canOptimizeAddDocument(...)

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#22833]
The assertion seems only to be tripping for index request without an id and when an index request is being retried:

```
[2017-01-27T12:10:53,773][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [elasticsearch[OaSsFEU][index][T#5]], exiting
java.lang.AssertionError: version: 1 type: EXTERNAL
    at org.elasticsearch.index.engine.InternalEngine.canOptimizeAddDocument(InternalEngine.java:447) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.index.engine.InternalEngine.innerIndex(InternalEngine.java:498) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:390) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:556) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:545) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:238) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:166) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:68) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:935) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:905) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:114) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:321) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:263) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:885) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:882) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.index.shard.IndexShardOperationsLock.acquire(IndexShardOperationsLock.java:142) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock(IndexShard.java:1654) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:894) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.action.support.replication.TransportReplicationAction.access$400(TransportReplicationAction.java:93) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:280) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:259) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:251) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:618) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_92]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_92]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
```

I'm not sure how the version type gets set to external for primary operations, but it should end up in this state. On the application side the version type doesn't get set, but even it was set to EXTERNAL then  `IndexRequest#validate(...)` should have failed.

**Comment by bleskes** [comment]
I researched this and it seems it is cause by a concurrent index deletion and indexing. There is a short window (between successful indexing and translog sync) where index deletion (or shard close) can trigger a retry after the request has been prepared for replication. We are working on making the index request immutable which will fix this. Also, this is not really an issue (but it should be fixed) because the retry protection in the engine will do the right thing if assertions are not enabled.

**Comment by bleskes** [comment]
IndexRequests are now immutable, which means this can be closed.
