### ISSUE TITLE
Play Framework and java.lang.NoClassDefFoundError: org/jboss/netty/channel/ReceiveBufferSizePredictorFactory

### ISSUE THREAD

**Issue by konradr25** [elastic/elasticsearch#22847]
**Elasticsearch version**:

elasticsearch-5.1.2

**Plugins installed**: []

**JVM version**:
1.8
**OS version**:
Windows 10
**Description of the problem including expected versus actual behavior**:
I struggle with integration of Transport Client, version 5.1.2 and Play Framework (2.5.4). I get an exception when I want to create an instance of TransportClient.

**Steps to reproduce**:
 1. new PreBuiltTransportClient(Settings.EMPTY)
                    .addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("127.0.0.1"), 9300));
 2. Expect exception

**Provide logs (if relevant)**:

java.lang.NoClassDefFoundError: org/jboss/netty/channel/ReceiveBufferSizePredictorFactory
	at org.elasticsearch.transport.Netty3Plugin.getSettings(Netty3Plugin.java:47)
	at org.elasticsearch.plugins.PluginsService.lambda$getPluginSettings$0(PluginsService.java:83)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.elasticsearch.plugins.PluginsService.getPluginSettings(PluginsService.java:83)
Caused by: java.lang.ClassNotFoundException: org.jboss.netty.channel.ReceiveBufferSizePredictorFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.elasticsearch.transport.Netty3Plugin.getSettings(Netty3Plugin.java:47)
	at org.elasticsearch.plugins.PluginsService.lambda$getPluginSettings$0(PluginsService.java:83)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)

**Comment by dadoonet** [comment]
May be Play comes with another version of netty than the one expected here?

**Comment by jasontedor** [comment]
I think that you have classpath problems. If you have additional questions, please ask on the [forum](https://discuss.elastic.co); Elastic reserves GitHub for verified bug reports and feature requests.
