### ISSUE TITLE
Wrong config directory is picked up

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#22861]
The packaging tests fail with:

```
Jan 30 12:43:18 ubuntu elasticsearch[5661]: Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.nio.file.NoSuchFileException
Jan 30 12:43:18 ubuntu elasticsearch[5661]: Likely root cause: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/config
Jan 30 12:43:18 ubuntu elasticsearch[5661]: at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
Jan 30 12:43:18 ubuntu elasticsearch[5661]: at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
Jan 30 12:43:18 ubuntu elasticsearch[5661]: at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
Jan 30 12:43:18 ubuntu elasticsearch[5661]: at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
Jan 30 12:43:18 ubuntu elasticsearch[5661]: at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
Jan 30 12:43:18 ubuntu elasticsearch[5661]: at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
Jan 30 12:43:18 ubuntu elasticsearch[5661]: at java.nio.file.Files.readAttributes(Files.java:1737)
Jan 30 12:43:18 ubuntu elasticsearch[5661]: at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
Jan 30 12:43:18 ubuntu elasticsearch[5661]: at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
Jan 30 12:43:18 ubuntu elasticsearch[5661]: at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
Jan 30 12:43:18 ubuntu elasticsearch[5661]: at java.nio.file.Files.walkFileTree(Files.java:2662)
Jan 30 12:43:18 ubuntu elasticsearch[5661]: at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:99)
Jan 30 12:43:18 ubuntu elasticsearch[5661]: at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:82)
Jan 30 12:43:18 ubuntu elasticsearch[5661]: at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:305)
```

The config directory is in `/etc/elasticsearch` but Elasticsearch picks up `/usr/share/elasticsearch/config`.

The problem has been introduced in https://github.com/elastic/elasticsearch/commit/aad51d44ab7363e53da773afa4707e0165eebda0#diff-192de7116527350709fbca18fe4d2087

Example build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-tests/898/console
Reproduction (on master): `gradle -Pvagrant.boxes=debian-8 packagingTest`

**Comment by danielmitterdorfer** [comment]
@rjernst Could you please have a look?
