### ISSUE TITLE
Queries with Enums throws  java.io.IOException: can not write type [Enum]

### ISSUE THREAD

**Issue by pnjc** [elastic/elasticsearch#22867]
**Elasticsearch version**: 5.1.2

**Plugins installed**: [no]

**JVM version**:1.8

**OS version**:Linux

**Description of the problem including expected versus actual behavior**:
I'm not sure if it is a bug,but at least under ES 2.3.5 Java client,it was able to write something like this

`public enum ExampleEnum
{
TEST1,TEST2
}`

`BoolQueryBuilder qb;
qb = boolQuery().must(matchQuery("enumFieldinStoredDocument",ExampleEnum.TEST2 ));`

now it's necessary to write .toString() to prevent exceptions

`qb.must(matchQuery("enumFieldinStoredDocument",ExampleEnum.TEST2.toString()));` 

or

`qb.must(matchQuery("enumFieldinStoredDocument",ExampleEnum.TEST2.name()));`

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:
```
Caused by: UncategorizedExecutionException[Failed execution]; nested: IOException[can not write type [ExampleEnum]];
	at org.elasticsearch.action.support.AdapterActionFuture.rethrowExecutionException(AdapterActionFuture.java:87) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:46) [elasticsearch-5.1.2.jar:5.1.2]...
```
```
Caused by: java.io.IOException: can not write type [class com.ExampleEnum]
	at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:639) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.index.query.BaseTermQueryBuilder.doWriteTo(BaseTermQueryBuilder.java:134) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.index.query.AbstractQueryBuilder.writeTo(AbstractQueryBuilder.java:73) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:841) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.index.query.AbstractQueryBuilder.writeQueries(AbstractQueryBuilder.java:249) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.index.query.BoolQueryBuilder.doWriteTo(BoolQueryBuilder.java:100) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.index.query.AbstractQueryBuilder.writeTo(AbstractQueryBuilder.java:73) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:841) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.common.io.stream.StreamOutput.writeOptionalNamedWriteable(StreamOutput.java:852) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.search.builder.SearchSourceBuilder.writeTo(SearchSourceBuilder.java:250) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.common.io.stream.StreamOutput.writeOptionalWriteable(StreamOutput.java:716) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.action.search.SearchRequest.writeTo(SearchRequest.java:337) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.transport.TcpTransport.buildMessage(TcpTransport.java:1093) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.transport.TcpTransport.sendRequest(TcpTransport.java:949) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:520) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:465) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.action.TransportActionNodeProxy.execute(TransportActionNodeProxy.java:51) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.client.transport.TransportProxyClient.lambda$execute$0(TransportProxyClient.java:59) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:231) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:345) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:403) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54) [elasticsearch-5.1.2.jar:5.1.2]
	at com.ES.doquery(ES.java:429) [classes:]
	... 183 more
```

**Comment by cbuescher** [comment]
@pnjc thanks for reporting this. The reason that using Enums directly in ES 2.x java client worked was that requests were internally converted from the java to the representation on the Rest layer. This implicitly converted enums to their String representation, so the search was actually performed on that. Now (version >5) we send search requests from the transport client via the internal transport protocol, which doesn't convert those enums to Strings, so as you noted you need to do this step on your side now. So this behaviour is not unexpected.
I agree that this isn't totally clear from the API currently. Maybe we could try to detect enums and convert them to their String value, although it is not always clear if that is what the user intended to search for.

**Comment by javanna** [comment]
-1 on doing magic. I think we should only support registered types. The fact that enums previously worked was more a side-effect of how queries were parsed later. If we have to do something, I think we should rather fail when these non supported types are set rather than only when serializing them, which is a bit too late.

**Comment by colings86** [comment]
I agree with @javanna here, we should only support registered types, closing this issue. If anyone objects please reopen and comment

**Comment by nikoladstankovic** [comment]
Hi there,

I have same exception when retrieving results using Spring Boot's ElasticsearchTemplate. 
When calling elasticsearchTemplate.queryForPage(searchQuery, MyClass.class); exception is thrown.
Can someone help me to resolve this issue?

Elasticsearch 5.5.3 (previous 1.7.x when this worked)
Java Spring Boot 2.0.4 (previous 1.3.x)
Spring Data Elasticsearch 3.0.9

Stacktrace:
ERROR c.j.c.e.MyClassElasticTemplate  - Failed execution
UncategorizedExecutionException[Failed execution]; nested: IOException[can not write type [class X.enums.BaseType]];
	at org.elasticsearch.action.support.AdapterActionFuture.rethrowExecutionException(AdapterActionFuture.java:89)
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:47)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.getSearchResponse(ElasticsearchTemplate.java:941)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.getSearchResponse(ElasticsearchTemplate.java:937)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.doSearch(ElasticsearchTemplate.java:928)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.queryForPage(ElasticsearchTemplate.java:308)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.queryForPage(ElasticsearchTemplate.java:303)
...
