### ISSUE TITLE
Windows 10 Insider build blocks on boot

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#22888]
**NOTE** this is on the latest Windows 10 Insider build (1607 build 1519.1000) and JDK:

```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

The latest Windows 10 stable version is **NOT AFFECTED** so no blocker for release. 

Starting elasticsearch gets blocked on calling:

`getLoadAndScaleToPercent:29, Probes (org.elasticsearch.monitor)`

And more specifically invoking the `getSystemCpuLoad` method. This thread never completes.

This affects all `2.x` and `5.x`

Full thread state:

>"main@2" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.management.OperatingSystemImpl.getSystemCpuLoad(OperatingSystemImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.elasticsearch.monitor.Probes.getLoadAndScaleToPercent(Probes.java:29)
	  at org.elasticsearch.monitor.os.OsProbe.getSystemCpuPercent(OsProbe.java:174)
	  at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:463)
	  at org.elasticsearch.monitor.os.OsService.<init>(OsService.java:45)
	  at org.elasticsearch.monitor.MonitorService.<init>(MonitorService.java:45)
	  at org.elasticsearch.node.Node.<init>(Node.java:345)
	  at org.elasticsearch.node.Node.<init>(Node.java:232)
	  at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:241)
	  at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:241)
	  at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333)
	  at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121)
	  at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112)
	  at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	  at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	  at org.elasticsearch.cli.Command.main(Command.java:88)
	  at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89)
	  at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)

> "elasticsearch[pmTaQcI][[timer]]@2681" daemon prio=5 tid=0x15 nid=NA sleeping
  java.lang.Thread.State: TIMED_WAITING
	  at java.lang.Thread.sleep(Thread.java:-1)
	  at org.elasticsearch.threadpool.ThreadPool$EstimatedTimeThread.run(ThreadPool.java:498)

> "Finalizer@3789" daemon prio=8 tid=0x3 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	  at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

> "Reference Handler@3790" daemon prio=10 tid=0x2 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:502)
	  at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	  at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

> "Attach Listener@3787" daemon prio=5 tid=0x5 nid=NA runnable
  java.lang.Thread.State: RUNNABLE

> "Signal Dispatcher@3788" daemon prio=9 tid=0x4 nid=NA runnable
  java.lang.Thread.State: RUNNABLE

Something to keep an eye on going forward.

**Comment by clintongormley** [comment]
@Mpdreamz when is this likely to be released?  we should mark this issue as a blocker for the appropriate time so that we don't forget to check the status of this issue

**Comment by Mpdreamz** [comment]
Most likely with the "Creators Update" scheduled in April, I switched to Ubuntu for a while and will keep updating on the insider builds. 

Will try and get an isolated reproduction going next week it may need to be reported to Oracle and/or Microsoft

**Comment by clintongormley** [comment]
thanks @Mpdreamz

**Comment by Mpdreamz** [comment]
w00t, it automagically fixed itself today `15025` no longer exhibits this issue.

**Comment by nik9000** [comment]
Nice!
