### ISSUE TITLE
ElasticSearch 5.1.1 Cluster is slow and timeout

### ISSUE THREAD

**Issue by hailima** [elastic/elasticsearch#22896]
**Elasticsearch version**:5.1.1

**Plugins installed**: [None]

**JVM version**:1.8

**OS version**: 101-Ubuntu SMP Tue Jul 15 17:58:37 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Hi, 

I installed two-node ES 5.1.1 cluster, use Java client to create index, update its mapping and indexing sample data. From time to time, I got timeout exception for "create-index"  action, if try it again, it could either work or not. Please advise what could be the issue with my cluster?  Is there anyway to change the config for 30s timeout?  Thanks!

org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (create-index [pwindex], cause [api]) within 30s
	at org.elasticsearch.cluster.service.ClusterService.lambda$null$4(ClusterService.java:449) ~[elasticsearch-5.1.1.jar:5.1.1]	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:458) ~[elasticsearch-5.1.1.jar:5.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_112]

I also use the remote reindex to migrate indexed data from ES 1.4.4 to 5.1.1. From time to time, got similar exceptions for the action "put-mapping".  Any solution or suggestion to it?  The index has 6M docs, each doc has a different doc type, but, all docs have the same field mappings (8 fields)  

org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-mapping) within 30s
	at org.elasticsearch.cluster.service.ClusterService.lambda$null$4(ClusterService.java:449) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:458) [elasticsearch-5.1.1.jar:5.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

**Comment by clintongormley** [comment]
Hi @hailima 

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks

**Comment by hailima** [comment]
Thanks and will do. But, i am not sure that it's not a bug since I can constantly reproduce the issue.
