### ISSUE TITLE
UpdateByQueryWhileModifyingTests.testUpdateWhileReindexing test failure

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#22938]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-unix-compatibility/os=sles/495/console

```
Suite: org.elasticsearch.index.reindex.UpdateByQueryWhileModifyingTests
  1> [2017-02-02T19:13:02,600][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] [testUpdateWhileReindexing]: before test
  1> [2017-02-02T19:13:02,602][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] [UpdateByQueryWhileModifyingTests#testUpdateWhileReindexing]: setting up test
  1> [2017-02-02T19:13:02,602][INFO ][o.e.t.InternalTestCluster] Setup InternalTestCluster [SUITE-CHILD_VM=[2]-CLUSTER_SEED=[-1530270894255747086]-HASH=[A70CDA325E18]-cluster] with seed [EAC362BAB9C44FF2] using [1] dedicated masters, [1] (data) nodes and [0] coord only nodes (min_master_nodes are [auto-managed])
  1> [2017-02-02T19:13:02,604][INFO ][o.e.n.Node               ] [node_sm0] initializing ...
  1> [2017-02-02T19:13:02,606][INFO ][o.e.e.NodeEnvironment    ] [node_sm0] using [1] data paths, mounts [[/ (/dev/xvda1)]], net usable_space [460.3gb], net total_space [492gb], spins? [unknown], types [ext4]
  1> [2017-02-02T19:13:02,606][INFO ][o.e.e.NodeEnvironment    ] [node_sm0] heap size [491mb], compressed ordinary object pointers [true]
  1> [2017-02-02T19:13:02,607][INFO ][o.e.n.Node               ] [node_sm0] node name [node_sm0], node ID [GMysUt0YSEqsob4JKjrwwQ]
  1> [2017-02-02T19:13:02,607][INFO ][o.e.n.Node               ] [node_sm0] version[5.3.0-SNAPSHOT], pid[26261], build[4ead294/2017-02-02T17:41:23.807Z], OS[Linux/4.4.38-93-default/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_121/25.121-b13]
  1> [2017-02-02T19:13:02,607][WARN ][o.e.n.Node               ] [node_sm0] version [5.3.0-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
  1> [2017-02-02T19:13:02,607][INFO ][o.e.p.PluginsService     ] [node_sm0] no modules loaded
  1> [2017-02-02T19:13:02,607][INFO ][o.e.p.PluginsService     ] [node_sm0] loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
  1> [2017-02-02T19:13:02,607][INFO ][o.e.p.PluginsService     ] [node_sm0] loaded plugin [org.elasticsearch.node.NodeMocksPlugin]
  1> [2017-02-02T19:13:02,608][INFO ][o.e.p.PluginsService     ] [node_sm0] loaded plugin [org.elasticsearch.search.MockSearchService$TestPlugin]
  1> [2017-02-02T19:13:02,608][INFO ][o.e.p.PluginsService     ] [node_sm0] loaded plugin [org.elasticsearch.test.ESIntegTestCase$TestSeedPlugin]
  1> [2017-02-02T19:13:02,608][INFO ][o.e.p.PluginsService     ] [node_sm0] loaded plugin [org.elasticsearch.test.discovery.TestZenDiscovery$TestPlugin]
  1> [2017-02-02T19:13:02,608][INFO ][o.e.p.PluginsService     ] [node_sm0] loaded plugin [org.elasticsearch.test.transport.AssertingLocalTransport$TestPlugin]
  1> [2017-02-02T19:13:02,608][INFO ][o.e.p.PluginsService     ] [node_sm0] loaded plugin [org.elasticsearch.test.transport.MockTransportService$TestPlugin]
  1> [2017-02-02T19:13:02,608][INFO ][o.e.p.PluginsService     ] [node_sm0] loaded plugin [org.elasticsearch.transport.MockTcpTransportPlugin]
  1> [2017-02-02T19:13:02,659][INFO ][o.e.n.Node               ] [node_sm0] initialized
  1> [2017-02-02T19:13:02,661][INFO ][o.e.n.Node               ] [node_sd1] initializing ...
  1> [2017-02-02T19:13:02,663][INFO ][o.e.e.NodeEnvironment    ] [node_sd1] using [1] data paths, mounts [[/ (/dev/xvda1)]], net usable_space [460.3gb], net total_space [492gb], spins? [unknown], types [ext4]
  1> [2017-02-02T19:13:02,663][INFO ][o.e.e.NodeEnvironment    ] [node_sd1] heap size [491mb], compressed ordinary object pointers [true]
  1> [2017-02-02T19:13:02,663][INFO ][o.e.n.Node               ] [node_sd1] node name [node_sd1], node ID [oQ86VVxvS8SgIRdEUmIQ7A]
  1> [2017-02-02T19:13:02,663][INFO ][o.e.n.Node               ] [node_sd1] version[5.3.0-SNAPSHOT], pid[26261], build[4ead294/2017-02-02T17:41:23.807Z], OS[Linux/4.4.38-93-default/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_121/25.121-b13]
  1> [2017-02-02T19:13:02,663][WARN ][o.e.n.Node               ] [node_sd1] version [5.3.0-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
  1> [2017-02-02T19:13:02,664][INFO ][o.e.p.PluginsService     ] [node_sd1] no modules loaded
  1> [2017-02-02T19:13:02,664][INFO ][o.e.p.PluginsService     ] [node_sd1] loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
  1> [2017-02-02T19:13:02,664][INFO ][o.e.p.PluginsService     ] [node_sd1] loaded plugin [org.elasticsearch.node.NodeMocksPlugin]
  1> [2017-02-02T19:13:02,664][INFO ][o.e.p.PluginsService     ] [node_sd1] loaded plugin [org.elasticsearch.search.MockSearchService$TestPlugin]
  1> [2017-02-02T19:13:02,664][INFO ][o.e.p.PluginsService     ] [node_sd1] loaded plugin [org.elasticsearch.test.ESIntegTestCase$TestSeedPlugin]
  1> [2017-02-02T19:13:02,664][INFO ][o.e.p.PluginsService     ] [node_sd1] loaded plugin [org.elasticsearch.test.discovery.TestZenDiscovery$TestPlugin]
  1> [2017-02-02T19:13:02,664][INFO ][o.e.p.PluginsService     ] [node_sd1] loaded plugin [org.elasticsearch.test.transport.AssertingLocalTransport$TestPlugin]
  1> [2017-02-02T19:13:02,664][INFO ][o.e.p.PluginsService     ] [node_sd1] loaded plugin [org.elasticsearch.test.transport.MockTransportService$TestPlugin]
  1> [2017-02-02T19:13:02,664][INFO ][o.e.p.PluginsService     ] [node_sd1] loaded plugin [org.elasticsearch.transport.MockTcpTransportPlugin]
  1> [2017-02-02T19:13:02,704][INFO ][o.e.n.Node               ] [node_sd1] initialized
  1> [2017-02-02T19:13:02,705][INFO ][o.e.n.Node               ] [node_sm0] starting ...
  1> [2017-02-02T19:13:02,705][INFO ][o.e.n.Node               ] [node_sd1] starting ...
  1> [2017-02-02T19:13:02,707][INFO ][o.e.t.t.MockTransportService] [node_sm0] publish_address {local[25]}, bound_addresses {local[25]}
  1> [2017-02-02T19:13:02,707][INFO ][o.e.t.t.MockTransportService] [node_sd1] publish_address {local[26]}, bound_addresses {local[26]}
  1> [2017-02-02T19:13:02,708][INFO ][o.e.t.d.MockZenPing      ] [node_sd1] pinging using mock zen ping
  1> [2017-02-02T19:13:02,709][INFO ][o.e.t.d.MockZenPing      ] [node_sm0] pinging using mock zen ping
  1> [2017-02-02T19:13:02,709][INFO ][o.e.c.s.ClusterService   ] [node_sm0] new_master {node_sm0}{GMysUt0YSEqsob4JKjrwwQ}{yHdhA81XRMeqILq2UGSmXw}{local}{local[25]}, reason: zen-disco-elected-as-master ([0] nodes joined)
  1> [2017-02-02T19:13:02,710][INFO ][o.e.n.Node               ] [node_sm0] started
  1> [2017-02-02T19:13:02,712][INFO ][o.e.c.s.ClusterService   ] [node_sm0] added {{node_sd1}{oQ86VVxvS8SgIRdEUmIQ7A}{xzJKyaITR6GEHT0LFy_2LQ}{local}{local[26]},}, reason: zen-disco-node-join[{node_sd1}{oQ86VVxvS8SgIRdEUmIQ7A}{xzJKyaITR6GEHT0LFy_2LQ}{local}{local[26]}]
  1> [2017-02-02T19:13:02,714][INFO ][o.e.c.s.ClusterService   ] [node_sd1] detected_master {node_sm0}{GMysUt0YSEqsob4JKjrwwQ}{yHdhA81XRMeqILq2UGSmXw}{local}{local[25]}, added {{node_sm0}{GMysUt0YSEqsob4JKjrwwQ}{yHdhA81XRMeqILq2UGSmXw}{local}{local[25]},}, reason: zen-disco-receive(from master [master {node_sm0}{GMysUt0YSEqsob4JKjrwwQ}{yHdhA81XRMeqILq2UGSmXw}{local}{local[25]} committed version [2]])
  1> [2017-02-02T19:13:02,714][INFO ][o.e.n.Node               ] [node_sd1] started
  1> [2017-02-02T19:13:02,715][INFO ][o.e.p.PluginsService     ] [transport_client_node_sm0] no modules loaded
  1> [2017-02-02T19:13:02,715][INFO ][o.e.p.PluginsService     ] [transport_client_node_sm0] loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
  1> [2017-02-02T19:13:02,715][INFO ][o.e.p.PluginsService     ] [transport_client_node_sm0] loaded plugin [org.elasticsearch.test.transport.AssertingLocalTransport$TestPlugin]
  1> [2017-02-02T19:13:02,720][INFO ][o.e.g.GatewayService     ] [node_sm0] recovered [0] indices into cluster_state
  1> [2017-02-02T19:13:02,732][INFO ][o.e.t.TransportService   ] [transport_client_node_sm0] publish_address {local[27]}, bound_addresses {local[27]}
  1> [2017-02-02T19:13:02,734][INFO ][o.e.p.PluginsService     ] [transport_client_node_sd1] no modules loaded
  1> [2017-02-02T19:13:02,734][INFO ][o.e.p.PluginsService     ] [transport_client_node_sd1] loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
  1> [2017-02-02T19:13:02,734][INFO ][o.e.p.PluginsService     ] [transport_client_node_sd1] loaded plugin [org.elasticsearch.test.transport.AssertingLocalTransport$TestPlugin]
  1> [2017-02-02T19:13:02,744][INFO ][o.e.t.TransportService   ] [transport_client_node_sd1] publish_address {local[28]}, bound_addresses {local[28]}
  1> [2017-02-02T19:13:02,746][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] test using _default_ mappings: [{"_default_":{}}]
  1> [2017-02-02T19:13:02,758][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] [UpdateByQueryWhileModifyingTests#testUpdateWhileReindexing]: all set up test
  1> [2017-02-02T19:13:02,771][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Index [1] docs async: [true] bulk: [false]
  1> [2017-02-02T19:13:02,783][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [auto(bulk api)], templates [random_index_template], shards [1]/[0], mappings [_default_]
  1> [2017-02-02T19:13:02,801][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][0]] ...]).
  1> [2017-02-02T19:13:02,813][INFO ][o.e.c.m.MetaDataMappingService] [node_sm0] [test/0J0DyUWwSby_oaxLHv3drA] create_mapping [test]
  1> [2017-02-02T19:13:02,894][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 2 with version 3. Retrying.
  1> [2017-02-02T19:13:02,972][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 5 with version 7. Retrying.
  1> [2017-02-02T19:13:02,998][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 5 with version 9. Retrying.
  1> [2017-02-02T19:13:03,126][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 8 with version 14. Retrying.
  1> [2017-02-02T19:13:03,302][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 17 with version 24. Retrying.
  1> [2017-02-02T19:13:03,313][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 17 with version 25. Retrying.
  1> [2017-02-02T19:13:03,458][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 24 with version 33. Retrying.
  2> REPRODUCE WITH: gradle :modules:reindex:test -Dtests.seed=C4E5233E1481C46E -Dtests.class=org.elasticsearch.index.reindex.UpdateByQueryWhileModifyingTests -Dtests.method="testUpdateWhileReindexing" -Dtests.security.manager=true -Dtests.locale=ja-JP -Dtests.timezone=Poland
  1> [2017-02-02T19:13:03,506][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 26 with version 37. Retrying.
  1> [2017-02-02T19:13:03,541][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 27 with version 39. Retrying.
  1> [2017-02-02T19:13:03,552][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 27 with version 40. Retrying.
  1> [2017-02-02T19:13:03,565][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 27 with version 41. Retrying.
  1> [2017-02-02T19:13:03,755][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 36 with version 51. Retrying.
  1> [2017-02-02T19:13:03,773][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 36 with version 53. Retrying.
  1> [2017-02-02T19:13:03,842][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 39 with version 57. Retrying.
  1> [2017-02-02T19:13:03,853][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 39 with version 58. Retrying.
  1> [2017-02-02T19:13:03,866][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 39 with version 59. Retrying.
  1> [2017-02-02T19:13:03,880][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 39 with version 60. Retrying.
  1> [2017-02-02T19:13:03,896][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 39 with version 61. Retrying.
  1> [2017-02-02T19:13:03,912][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 39 with version 62. Retrying.
  1> [2017-02-02T19:13:03,940][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 39 with version 64. Retrying.
  1> [2017-02-02T19:13:03,953][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 39 with version 65. Retrying.
  1> [2017-02-02T19:13:03,965][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] Caught expected version conflict trying to perform mutation number 39 with version 66. Retrying.
  1> [2017-02-02T19:13:03,991][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] [UpdateByQueryWhileModifyingTests#testUpdateWhileReindexing]: cleaning up after test
  1> [2017-02-02T19:13:04,002][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/0J0DyUWwSby_oaxLHv3drA] deleting index
  1> [2017-02-02T19:13:04,019][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] [UpdateByQueryWhileModifyingTests#testUpdateWhileReindexing]: cleaned up after test
  1> [2017-02-02T19:13:04,019][INFO ][o.e.i.r.UpdateByQueryWhileModifyingTests] [testUpdateWhileReindexing]: after test
ERROR   1.43s J2 | UpdateByQueryWhileModifyingTests.testUpdateWhileReindexing <<< FAILURES!
   > Throwable #1: java.lang.RuntimeException: Failed to index after [10] attempts. Too many version conflicts!
   > 	at __randomizedtesting.SeedInfo.seed([C4E5233E1481C46E:696F96E69C9CDAA]:0)
   > 	at org.elasticsearch.index.reindex.UpdateByQueryWhileModifyingTests.testUpdateWhileReindexing(UpdateByQueryWhileModifyingTests.java:83)
   > 	at java.lang.Thread.run(Thread.java:745)
  1> [2017-02-02T19:13:04,033][INFO ][o.e.n.Node               ] [node_sd1] stopping ...
  1> [2017-02-02T19:13:04,034][INFO ][o.e.c.s.ClusterService   ] [node_sm0] removed {{node_sd1}{oQ86VVxvS8SgIRdEUmIQ7A}{xzJKyaITR6GEHT0LFy_2LQ}{local}{local[26]},}, reason: zen-disco-node-left({node_sd1}{oQ86VVxvS8SgIRdEUmIQ7A}{xzJKyaITR6GEHT0LFy_2LQ}{local}{local[26]}), reason(left)[{node_sd1}{oQ86VVxvS8SgIRdEUmIQ7A}{xzJKyaITR6GEHT0LFy_2LQ}{local}{local[26]} left]
  1> [2017-02-02T19:13:04,034][INFO ][o.e.n.Node               ] [node_sd1] stopped
  1> [2017-02-02T19:13:04,034][INFO ][o.e.n.Node               ] [node_sd1] closing ...
  1> [2017-02-02T19:13:04,037][INFO ][o.e.n.Node               ] [node_sd1] closed
  1> [2017-02-02T19:13:04,039][INFO ][o.e.n.Node               ] [node_sm0] stopping ...
  1> [2017-02-02T19:13:04,041][INFO ][o.e.n.Node               ] [node_sm0] stopped
  1> [2017-02-02T19:13:04,041][INFO ][o.e.n.Node               ] [node_sm0] closing ...
  1> [2017-02-02T19:13:04,044][INFO ][o.e.n.Node               ] [node_sm0] closed
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+5.x+multijob-unix-compatibility/os/sles/modules/reindex/build/testrun/test/J2/temp/org.elasticsearch.index.reindex.UpdateByQueryWhileModifyingTests_C4E5233E1481C46E-001
  2> NOTE: test params are: codec=Lucene62, sim=RandomSimilarity(queryNorm=true,coord=yes): {}, locale=ja-JP, timezone=Poland
  2> NOTE: Linux 4.4.38-93-default amd64/Oracle Corporation 1.8.0_121 (64-bit)/cpus=4,threads=1,free=306746240,total=490209280
  2> NOTE: All tests run in this JVM: [ReindexFailureTests, ReindexVersioningTests, ReindexFromRemoteWithAuthTests, RetryTests, DeleteByQueryBasicTests, UpdateByQueryWhileModifyingTests]
```

**Comment by nik9000** [comment]
I pushed fixes for this test bug to 5.2, 5.x, and master.
