### ISSUE TITLE
"Failed to clear scroll" when reindexing from 1.x to 5.2.0

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#22937]
**Environment**:
Reindexing from ES 1.7.5 -> ES 5.2.0

**Description**:

This error message is output repeatedly during reindex.  The reindex can complete successfully, but perhaps not efficiently.

```
2017-02-02T13:02:16,867][WARN ][o.e.i.r.TransportReindexAction] [CBuuMNt] Failed to clear scroll [c2NhbjswOzE7dG90YWxfaGl0czoyOw==]
org.elasticsearch.client.ResponseException: DELETE http://127.0.0.1:9201/_search/scroll: HTTP/1.1 404 Not Found
{}
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:311) [rest-5.2.0.jar:5.2.0]
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:300) [rest-5.2.0.jar:5.2.0]
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119) [httpcore-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177) [httpasyncclient-4.1.2.jar:4.1.2]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436) [httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326) [httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) [httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) [httpasyncclient-4.1.2.jar:4.1.2]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) [httpasyncclient-4.1.2.jar:4.1.2]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) [httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) [httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) [httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) [httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) [httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) [httpcore-nio-4.4.5.jar:4.4.5]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588) [httpcore-nio-4.4.5.jar:4.4.5]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```

**Notable**:
- Problem does not happen with 1.x -> 5.1.x
- Problem does not happen with 2.x -> 5.2.0

**Comment by nik9000** [comment]
I saw it today. This comes from a fix we did in 5.2 where we were more careful to actually clear the scroll, I think. I'll investigate, but I believe it can safely be ignored.
