### ISSUE TITLE
In some cases FVH returns StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by oleg-andreyev** [elastic/elasticsearch#22997]
**Elasticsearch version**: 2.4.1

**Lucena version**: 5.5.2

**Plugins installed**: delete-by-query, head

**JVM version**: 1.8.0_60

**OS version**: centos-release-6-8.el6.centos.12.3.x86_64

**Steps to reproduce**:
<details>

```
# bug
DELETE es_bug_test

PUT es_bug_test
{
  "mappings": {
    "product": {
      "properties": {
        "description": {
          "type": "string",
          "analyzer": "generic_text",
          "search_analyzer": "generic_text_search",
          "fielddata": {
            "format": "disabled"
          }
        },
        "clean_description": {
          "type": "string",
          "analyzer": "generic_text",
          "search_analyzer": "generic_text_search",
          "norms": {
            "enabled": false
          },
          "index_options": "docs",
          "store": true,
          "fielddata": {
            "format": "disabled"
          },
          "term_vector": "with_positions_offsets"
        },
        "full_name": {
          "type": "multi_field",
          "fields": {
            "regular": {
              "type": "string",
              "analyzer": "generic_text",
              "search_analyzer": "generic_text_search"
            },
            "wo_norms": {
              "type": "string",
              "analyzer": "generic_text",
              "search_analyzer": "generic_text_search",
              "norms": {
                "enabled": false
              }
            },
            "wo_norms_freqs": {
              "type": "string",
              "analyzer": "generic_text",
              "search_analyzer": "generic_text_search",
              "norms": {
                "enabled": false
              },
              "index_options": "docs"
            },
            "long_terms": {
              "type": "string",
              "analyzer": "long_terms",
              "norms": {
                "enabled": false
              },
              "index_options": "docs"
            },
            "small_terms": {
              "type": "string",
              "analyzer": "small_terms",
              "norms": {
                "enabled": false
              }
            },
            "small_w_norms": {
              "type": "string",
              "analyzer": "small_terms"
            },
            "sorting": {
              "type": "string",
              "analyzer": "op_keyword",
              "norms": {
                "enabled": false
              },
              "index_options": "docs"
            },
            "highlighting": {
              "type": "string",
              "analyzer": "generic_text",
              "search_analyzer": "generic_text_search",
              "store": true,
              "term_vector": "with_positions_offsets"
            },
            "spelling": {
              "type": "string",
              "analyzer": "spell",
              "search_analyzer": "standard"
            },
            "spelling_word": {
              "type": "string",
              "analyzer": "standard"
            },
            "related": {
              "type": "string",
              "analyzer": "related_searches"
            }
          }
        }
      }
    }
  },
  "settings": {
    "number_of_shards": "1",
    "number_of_replicas": 0,
    "max_result_window": 130000,
    "index": {
      "analysis": {
        "analyzer": {
          "related_searches": {
            "type": "custom",
            "tokenizer": "whitespace",
            "filter": [
              "len5_20",
              "lowercase",
              "asciifolding",
              "related_search_delimiter",
              "stop"
            ]
          },
          "small_terms": {
            "type": "custom",
            "tokenizer": "whitespace",
            "filter": [
              "short_word_delimiter",
              "len1_4",
              "lowercase",
              "asciifolding",
              "op_synonyms",
              "stop",
              "snow_english",
              "unique"
            ]
          },
          "generic_text": {
            "type": "custom",
            "tokenizer": "whitespace",
            "filter": [
              "short_word_delimiter",
              "lowercase",
              "asciifolding",
              "op_synonyms",
              "stop",
              "snow_english"
            ],
            "char_filter": "html_strip"
          },
          "generic_text_search": {
            "type": "custom",
            "tokenizer": "whitespace",
            "filter": [
              "short_word_delimiter",
              "lowercase",
              "asciifolding",
              "stop",
              "snow_english"
            ],
            "char_filter": "html_strip"
          },
          "spell": {
            "type": "custom",
            "tokenizer": "whitespace",
            "filter": [
              "lowercase",
              "op_synonyms",
              "spell_ngram"
            ]
          },
          "op_keyword": {
            "type": "custom",
            "tokenizer": "keyword",
            "filter": [
              "lowercase",
              "trim"
            ]
          },
          "long_terms": {
            "type": "custom",
            "tokenizer": "whitespace",
            "filter": [
              "len5_20",
              "lowercase",
              "asciifolding",
              "op_synonyms",
              "stop",
              "snow_english",
              "unique"
            ]
          }
        },
        "filter": {
          "spell_ngram": {
            "type": "nGram",
            "min_gram": 3,
            "max_gram": 4
          },
          "len1_4": {
            "type": "length",
            "min": 1,
            "max": 4
          },
          "len5_20": {
            "type": "length",
            "min": 5,
            "max": 20
          },
          "snow_english": {
            "type": "snowball",
            "language": "English"
          },
          "short_word_delimiter": {
            "type": "word_delimiter",
            "generate_word_parts": true,
            "generate_number_parts": true,
            "catenate_words": true,
            "catenate_numbers": true,
            "catenate_all": true,
            "split_on_case_change": true,
            "preserve_original": true
          },
          "related_search_delimiter": {
            "type": "word_delimiter",
            "generate_word_parts": false,
            "generate_number_parts": true,
            "catenate_words": false,
            "catenate_numbers": false,
            "catenate_all": false,
            "split_on_case_change": false,
            "preserve_original": false,
            "split_on_numerics": true,
            "stem_english_possessive": true
          },
          "op_synonyms": {
            "type": "synonym",
            "ignore_case": true,
            "expand": true,
            "synonyms": [
              "riflescopes, rifle scopes",
              "riflescope, rifle scope"
            ]
          }
        }
      }
    }
  }
}

POST es_bug_test/product
{
  "full_name": "Pelican Storm Cases Photographer's Organizer for Pelican Storm Casess",
  "clean_description": "\nPelican Storm Case Photographer's Organizers present the professional photographer with an array of compartments including an assortment of elastic strapping and mesh nylon zipper pockets to house, protect and organize all photo gear in your Storm Case. The Storm Case Accessory is water resistant and durable enough for any type of environment. Velcro straps are provided to ensure a tight and organized fit, while the dry box accessory also offers expandable folder pockets that will help you store important gear for the next photo shoot such as rechargeable batteries, digital camera, and all other kinds of digital camera accessories.\nAvailable Options for Storm Case Photographer's Organizer\n\niM2300-PHOTOPALLET: Storm Case Photographer's Organizer for iM2300 Water Proof Storm Case\niM24XX-PHOTOPALLET: Storm Case Photographer's Organizer for iM2400 Waterproof Storm Case\niM26XX-PHOTOPALLET: Storm Case Photographer's Organizer for iM2600 and iM2620 Water Resistant Storm Cases\n\n\n\nFeatures of Pelican Storm Cases Photo Organizer\n\nElastic strapping\nMesh nylon zipper pockets\nWater resistant\nVelcro straps provided\n\n\n\nPackage Content\n\nPelican Storm Case Photographer's Organizer for Storm Cases\n\n",
  "description": "<div id=\"product-caption-block-description\" class=\"product-caption-block\">\n<p><strong>Pelican Storm Case Photographer's Organizers</strong> present the professional photographer with an array of compartments including an assortment of elastic strapping and mesh nylon zipper pockets to house, protect and organize all <strong>photo gear</strong> in your <strong><a href=\"http://www.dummy-web-site.com/storm-cases-brand.html\">Storm Case</a></strong>. The <strong><a href=\"http://www.dummy-web-site.com/storm-cases-dry-box-accessories.html\">Storm Case Accessory</a></strong> is water resistant and durable enough for any type of environment. <strong>Velcro straps</strong> are provided to ensure a tight and organized fit, while the <strong><a href=\"http://www.dummy-web-site.com/dry-box-accessories.html\">dry box accessory</a></strong> also offers expandable <strong>folder pockets</strong> that will help you store important gear for the next photo shoot such as <strong><a href=\"http://www.dummy-web-site.com/batteries.html\">rechargeable batteries</a></strong>, <strong><a href=\"http://www.dummy-web-site.com/cameras.html\">digital camera</a></strong>, and all other kinds of <strong><a href=\"http://www.dummy-web-site.com/digital-camera-accessories.html\">digital camera accessories</a></strong>.</p>\n<h3>Available Options for Storm Case Photographer's Organizer</h3>\n<ul>\n<li>iM2300-PHOTOPALLET: Storm Case Photographer's Organizer for iM2300 Water Proof Storm Case</li>\n<li>iM24XX-PHOTOPALLET: Storm Case Photographer's Organizer for iM2400 Waterproof Storm Case</li>\n<li>iM26XX-PHOTOPALLET: Storm Case Photographer's Organizer for iM2600 and iM2620 Water Resistant Storm Cases</li>\n</ul>\n</div>\n<div id=\"product-caption-block-features\" class=\"product-caption-block\">\n<h3>Features of Pelican Storm Cases Photo Organizer</h3>\n<ul>\n<li>Elastic strapping</li>\n<li>Mesh nylon zipper pockets</li>\n<li>Water resistant</li>\n<li>Velcro straps provided</li>\n</ul>\n</div>\n<div id=\"product-caption-block-package-content\" class=\"product-caption-block\">\n<h3>Package Content</h3>\n<ul>\n<li><strong>Pelican Storm Case Photographer's Organizer for Storm Cases</strong></li>\n</ul>\n</div>"
}

POST es_bug_test/_refresh

GET es_bug_test/product/_search

GET es_bug_test/product/_search
{
  "highlight": {
    "require_field_match": false,
    "pre_tags": [
      "<strong>"
    ],
    "post_tags": [
      "</strong>"
    ],
    "fields": {
      "full_name.highlighting": {
        "number_of_fragments": 0
      },
      "clean_description": {
        "fragment_size": 100,
        "number_of_fragments": 7
      }
    }
  },
  "query": {
    "bool": {
      "must": [
        {
          "function_score": {
            "score_mode": "multiply",
            "query": {
              "bool": {
                "must": [
                  {
                    "bool": {
                      "minimum_should_match": "100%",
                      "should": [
                        {
                          "dis_max": {
                            "queries": [
                              {
                                "query_string": {
                                  "default_field": "full_name.wo_norms_freqs",
                                  "query": "pelican",
                                  "default_operator": "and",
                                  "minimum_should_match": "100%",
                                  "boost": 1.5
                                }
                              },
                              {
                                "query_string": {
                                  "default_field": "clean_description",
                                  "query": "pelican",
                                  "default_operator": "and",
                                  "minimum_should_match": "100%",
                                  "boost": 0.2
                                }
                              },
                              {
                                "query_string": {
                                  "default_field": "full_name.regular",
                                  "query": "pelican",
                                  "auto_generate_phrase_queries": true,
                                  "phrase_slop": 3,
                                  "use_dis_max": true,
                                  "tie_breaker": 0.1,
                                  "boost": 0.2
                                }
                              }
                            ],
                            "tie_breaker": 0.1
                          }
                        },
                        {
                          "dis_max": {
                            "queries": [
                              {
                                "query_string": {
                                  "default_field": "full_name.wo_norms_freqs",
                                  "query": "im26xx\\-photopallet",
                                  "default_operator": "and",
                                  "minimum_should_match": "100%",
                                  "boost": 1.5
                                }
                              },
                              {
                                "query_string": {
                                  "default_field": "clean_description",
                                  "query": "im26xx\\-photopallet",
                                  "default_operator": "and",
                                  "minimum_should_match": "100%",
                                  "boost": 0.2
                                }
                              },
                              {
                                "query_string": {
                                  "default_field": "full_name.regular",
                                  "query": "im26xx\\-photopallet",
                                  "auto_generate_phrase_queries": true,
                                  "phrase_slop": 3,
                                  "use_dis_max": true,
                                  "tie_breaker": 0.1,
                                  "boost": 0.2
                                }
                              }
                            ],
                            "tie_breaker": 0.1
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
```
</details>

**Provide logs (if relevant)**:
<details>

```
[2017-02-06 15:12:07,722][DEBUG][action.search            ] [localhost] [es_bug_test][0], node[-1KvMUg-QKuwDtkQ8aVv8w], [P], v[2], s[STARTED], a[id=YnoIc0ktQ3myY7vBUeiXFg]: Failed to execute [org.elasticsearch.action.search.SearchRequest@52d5aa43]
RemoteTransportException[[localhost][127.0.0.1:9300][indices:data/read/search[phase/query+fetch]]]; nested: FetchPhaseExecutionException[Fetch Failed [Failed to highlight field [clean_description]]]; nested: StringIndexOutOfBoundsException[String index out of range: -16];
Caused by: FetchPhaseExecutionException[Fetch Failed [Failed to highlight field [clean_description]]]; nested: StringIndexOutOfBoundsException[String index out of range: -16];
        at org.elasticsearch.search.highlight.FastVectorHighlighter.highlight(FastVectorHighlighter.java:169)
        at org.elasticsearch.search.highlight.HighlightPhase.hitExecute(HighlightPhase.java:140)
        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:188)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:490)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:392)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:389)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -16
        at java.lang.String.substring(Unknown Source)
        at org.apache.lucene.search.vectorhighlight.BaseFragmentsBuilder.makeFragment(BaseFragmentsBuilder.java:179)
        at org.elasticsearch.search.highlight.vectorhighlight.SimpleFragmentsBuilder.makeFragment(SimpleFragmentsBuilder.java:43)
        at org.apache.lucene.search.vectorhighlight.BaseFragmentsBuilder.createFragments(BaseFragmentsBuilder.java:144)
        at org.apache.lucene.search.vectorhighlight.FastVectorHighlighter.getBestFragments(FastVectorHighlighter.java:186)
        at org.elasticsearch.search.highlight.FastVectorHighlighter.highlight(FastVectorHighlighter.java:146)
        ... 12 more
[2017-02-06 15:12:07,723][DEBUG][action.search            ] [localhost] All shards failed for phase: [query_fetch]
RemoteTransportException[[localhost][127.0.0.1:9300][indices:data/read/search[phase/query+fetch]]]; nested: FetchPhaseExecutionException[Fetch Failed [Failed to highlight field [clean_description]]]; nested: StringIndexOutOfBoundsException[String index out of range: -16];
Caused by: FetchPhaseExecutionException[Fetch Failed [Failed to highlight field [clean_description]]]; nested: StringIndexOutOfBoundsException[String index out of range: -16];
        at org.elasticsearch.search.highlight.FastVectorHighlighter.highlight(FastVectorHighlighter.java:169)
        at org.elasticsearch.search.highlight.HighlightPhase.hitExecute(HighlightPhase.java:140)
        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:188)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:490)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:392)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:389)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -16
        at java.lang.String.substring(Unknown Source)
        at org.apache.lucene.search.vectorhighlight.BaseFragmentsBuilder.makeFragment(BaseFragmentsBuilder.java:179)
        at org.elasticsearch.search.highlight.vectorhighlight.SimpleFragmentsBuilder.makeFragment(SimpleFragmentsBuilder.java:43)
        at org.apache.lucene.search.vectorhighlight.BaseFragmentsBuilder.createFragments(BaseFragmentsBuilder.java:144)
        at org.apache.lucene.search.vectorhighlight.FastVectorHighlighter.getBestFragments(FastVectorHighlighter.java:186)
        at org.elasticsearch.search.highlight.FastVectorHighlighter.highlight(FastVectorHighlighter.java:146)
        ... 12 more
[2017-02-06 15:12:07,723][WARN ][rest.suppressed          ] path: /es_bug_test/product/_search, params: {index=es_bug_test, type=product}
Failed to execute phase [query_fetch], all shards failed; shardFailures {[-1KvMUg-QKuwDtkQ8aVv8w][es_bug_test][0]: RemoteTransportException[[localhost][127.0.0.1:9300][indices:data/read/search[phase/query+fetch]]]; nested: FetchPhaseExecutionException[Fetch Failed [Failed to highlight field [clean_description]]]; nested: StringIndexOutOfBoundsException[String index out of range: -16]; }
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:206)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:152)
        at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:872)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:850)
        at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:387)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: [String index out of range: -16]; nested: StringIndexOutOfBoundsException[String index out of range: -16];
        at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:386)
        at org.elasticsearch.action.search.SearchPhaseExecutionException.guessRootCauses(SearchPhaseExecutionException.java:152)
        at org.elasticsearch.action.search.SearchPhaseExecutionException.getCause(SearchPhaseExecutionException.java:99)
        at java.lang.Throwable.printStackTrace(Unknown Source)
        at java.lang.Throwable.printStackTrace(Unknown Source)
        at org.apache.log4j.DefaultThrowableRenderer.render(DefaultThrowableRenderer.java:60)
        at org.apache.log4j.spi.ThrowableInformation.getThrowableStrRep(ThrowableInformation.java:87)
        at org.apache.log4j.spi.LoggingEvent.getThrowableStrRep(LoggingEvent.java:413)
        at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:313)
        at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
        at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
        at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
        at org.apache.log4j.Category.callAppenders(Category.java:206)
        at org.apache.log4j.Category.forcedLog(Category.java:391)
        at org.apache.log4j.Category.log(Category.java:856)
        at org.elasticsearch.common.logging.log4j.Log4jESLogger.internalWarn(Log4jESLogger.java:135)
        at org.elasticsearch.common.logging.support.AbstractESLogger.warn(AbstractESLogger.java:109)
        at org.elasticsearch.rest.BytesRestResponse.convert(BytesRestResponse.java:134)
        at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:96)
        at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:87)
        at org.elasticsearch.rest.action.support.RestActionListener.onFailure(RestActionListener.java:60)
        at org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:95)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.raiseEarlyFailure(AbstractSearchAsyncAction.java:294)
        ... 10 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -16
        at java.lang.String.substring(Unknown Source)
        at org.apache.lucene.search.vectorhighlight.BaseFragmentsBuilder.makeFragment(BaseFragmentsBuilder.java:179)
        at org.elasticsearch.search.highlight.vectorhighlight.SimpleFragmentsBuilder.makeFragment(SimpleFragmentsBuilder.java:43)
        at org.apache.lucene.search.vectorhighlight.BaseFragmentsBuilder.createFragments(BaseFragmentsBuilder.java:144)
        at org.apache.lucene.search.vectorhighlight.FastVectorHighlighter.getBestFragments(FastVectorHighlighter.java:186)
        at org.elasticsearch.search.highlight.FastVectorHighlighter.highlight(FastVectorHighlighter.java:146)
        at org.elasticsearch.search.highlight.HighlightPhase.hitExecute(HighlightPhase.java:140)
        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:188)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:490)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:392)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:389)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        ... 3 more

```

</details>

Exception: `Failed to highlight field [clean_description]`, but if I remove:

```
...
{
"query_string": {
  "default_field": "full_name.regular",
  "query": "pelican",
  "auto_generate_phrase_queries": true,
  "phrase_slop": 3,
  "use_dis_max": true,
  "tie_breaker": 0.1,
  "boost": 0.2
}
...
{
"query_string": {
  "default_field": "full_name.regular",
  "query": "im26xx\\-photopallet",
  "auto_generate_phrase_queries": true,
  "phrase_slop": 3,
  "use_dis_max": true,
  "tie_breaker": 0.1,
  "boost": 0.2
}
...
```
no exception is thrown

**Comment by clintongormley** [comment]
This is still broken with the FVH in 5.x, but (good news), the new [unified highlighter](https://github.com/elastic/elasticsearch/pull/21621) handles this properly.

**Comment by oleg-andreyev** [comment]
Could be please explain why this is happening?
Are there any plans for fixing this bug in 2.x?

If there are not plans for fixing this issue, it can be closed in favor of UH, and let's hope it will resolve this issue.

**Comment by clintongormley** [comment]
i don't know exactly but the FVH is buggy - probably due to bad positions and offsets.  This is in Lucene, not ES.  No fixes have been made to FVH in Lucene for ages I believe, but the new unified highlighter handles these cases properly.  I very much doubt the FVH is going to be fixed.

**Comment by oleg-andreyev** [comment]
Thanks, I'll close this issue in favor of UH
