### ISSUE TITLE
Ingest geoip plugin install reporting built for 5.1.2 under 5.2.0

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#23029]
**Elasticsearch version**: 5.2.0

**Plugins installed**: [ingest-geoip]

**JVM version**: 1.8.0_121

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behaviour**: Trying to install the ingest-geoip plugin and it's reporting that it is built for 5.1.2, not 5.2.0.

**Steps to reproduce**:
 1. `sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install ingest-geoip` OR
 2. `wget https://artifacts.elastic.co/downloads/elasticsearch-plugins/ingest-geoip/ingest-geoip-5.2.0.zip` AND 
 3. `sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install file:///home/vagrant/ingest-geoip-5.2.0.zip`

**Provide logs (if relevant)**:
Step 1;
```
vagrant@vagrant-ubuntu-trusty-64:~$ sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install ingest-geoip
-> Downloading ingest-geoip from elastic
[=================================================] 100%
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [x-pack] is incompatible with Elasticsearch [5.2.0]. Was designed for version [5.1.2]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:108)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:292)
	at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:463)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:444)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:486)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:195)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

Steps 2 and 3;
```
vagrant@vagrant-ubuntu-trusty-64:~$ wget https://artifacts.elastic.co/downloads/elasticsearch-plugins/ingest-geoip/ingest-geoip-5.2.0.zip
--2017-02-07 22:17:44--  https://artifacts.elastic.co/downloads/elasticsearch-plugins/ingest-geoip/ingest-geoip-5.2.0.zip
Resolving artifacts.elastic.co (artifacts.elastic.co)... 23.21.105.193, 54.83.207.241, 184.72.218.178, ...
Connecting to artifacts.elastic.co (artifacts.elastic.co)|23.21.105.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31958996 (30M) [application/zip]
Saving to: ‘ingest-geoip-5.2.0.zip’

100%[====================================================================================================================================================================================================>] 31,958,996   503KB/s   in 70s

2017-02-07 22:18:55 (444 KB/s) - ‘ingest-geoip-5.2.0.zip’ saved [31958996/31958996]

vagrant@vagrant-ubuntu-trusty-64:~$ sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install file:///home/vagrant/ingest-geoip-5.2.0.zip
-> Downloading file:///home/vagrant/ingest-geoip-5.2.0.zip
[=================================================] 100%
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [x-pack] is incompatible with Elasticsearch [5.2.0]. Was designed for version [5.1.2]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:108)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:292)
	at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:463)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:444)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:486)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:195)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

**Comment by jasontedor** [comment]
No, the problem here is that x-pack is still on version 5.1.2, it needs to be upgraded first.

```
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [x-pack] is incompatible with Elasticsearch [5.2.0]. Was designed for version [5.1.2]
```

**Comment by markwalkom** [comment]
Damn it, how can I be so blind.

Sorry about the noise.

**Comment by Laxman-SM** [comment]
Hi i saw this issue again  after upgrading elastic search to 5.5.0.
./elasticsearch-plugin  list
ingest-geoip
WARNING: plugin [ingest-geoip] is incompatible with version [5.5.0]; was designed for version [5.4.1]
ingest-user-agent
WARNING: plugin [ingest-user-agent] is incompatible with version [5.5.0]; was designed for version [5.4.1]
x-pack
WARNING: plugin [x-pack] is incompatible with version [5.5.0]; was designed for version [5.4.1]

this break my logstash functionality. so due to this unable to start my ES service

**Comment by jasontedor** [comment]
@Laxman-SM You have to upgrade your plugins.
