### ISSUE TITLE
discovery-ec2 issue

### ISSUE THREAD

**Issue by jjhesk** [elastic/elasticsearch#23036]
Plugin Discover-ec2

Using version 2.4.0 cloud-aws.

Starting elasticsearch: Exception in thread "main" java.lang.IllegalArgumentException: No automatic endpoint could be derived from region [us-west-b2]
	at org.elasticsearch.cloud.aws.AwsEc2ServiceImpl.client(AwsEc2ServiceImpl.java:184)
	at org.elasticsearch.discovery.ec2.AwsEc2UnicastHostsProvider.<init>(AwsEc2UnicastHostsProvider.java:75)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at <<<guice>>>
	at org.elasticsearch.node.Node.<init>(Node.java:213)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
                                                           [FAILED]

Trigger: `sudo service elasticsearch start` with root permission on aws linux

**Comment by dadoonet** [comment]
Use endpoint instead. See https://github.com/elastic/elasticsearch/issues/22306#issuecomment-268547104

Note that region is deprecated in 5.3 and removed in 6.0.
