### ISSUE TITLE
MatchQuery use Date with Elasticsearch5.2.0,catch java.lang.IllegalArgumentException: Invalid format

### ISSUE THREAD

**Issue by engimatic** [elastic/elasticsearch#23138]
**Elasticsearch version**:5.2.0

**Plugins installed**: []

**JVM version**:1.8.0_121-b13

**OS version**:Centos6.8

When I update my Elasticsearch from 2.2.1 to 5.2.0,some of my code run with error
When I want to get data from Elasticsearch use above method,I hava catch the error like this 

```
private <T> ArrayList<T> connectES(Date timestamp, String index, String type, Class<T> clazz) {

        ArrayList<T> values = new ArrayList<>();
        if (!client.admin().indices().prepareExists(index).execute().actionGet().isExists()) {
            System.out.println("索引" + index + "不存在");
            return values;
        }

        SearchResponse scrollResp = client.prepareSearch(index)
                .setTypes(type).setSearchType(SearchType.QUERY_THEN_FETCH)
                .setQuery(QueryBuilders.matchQuery("start_timestamp", timestamp))
                .setScroll(new TimeValue(60000))
                .setSize(10000).execute().actionGet();


        System.out.println(scrollResp.getHits().getTotalHits());


        while (true) {
            for (SearchHit hit : scrollResp.getHits().getHits()) {
                T value = JSON.parseObject(hit.sourceAsString(), clazz);
                values.add(value);
            }
            scrollResp = client.prepareSearchScroll(scrollResp.getScrollId()).setScroll(new TimeValue(60000)).execute
                    ().actionGet();
            //Break condition: No hits are returned
            if (scrollResp.getHits().getHits().length == 0) {
                break;
            }
        }
        return values;
    }
```
`Caused by: RemoteTransportException[[node-hot][10.128.9.207:9300][indices:data/read/search[phase/query]]]; nested: QueryShardException[failed to create query: {
  "match" : {
    "start_timestamp" : {
      "query" : "2017-02-13T07:00:00.000Z",
      "operator" : "OR",
      "prefix_length" : 0,
      "max_expansions" : 50,
      "fuzzy_transpositions" : true,
      "lenient" : false,
      "zero_terms_query" : "NONE",
      "boost" : 1.0
    }
  }
}]; nested: IllegalArgumentException[Invalid format: "Mon Feb 13 15:00:00 CST 2017"];
Caused by: [http-stat-session-2017.02.09/0eW3RdA6QButDqpNWF2uLg] QueryShardException[failed to create query: {
  "match" : {
    "start_timestamp" : {
      "query" : "2017-02-13T07:00:00.000Z",
      "operator" : "OR",
      "prefix_length" : 0,
      "max_expansions" : 50,
      "fuzzy_transpositions" : true,
      "lenient" : false,
      "zero_terms_query" : "NONE",
      "boost" : 1.0
    }
  }
}]; nested: IllegalArgumentException[Invalid format: "Mon Feb 13 15:00:00 CST 2017"];
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:333)
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:311)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:671)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:540)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:516)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:251)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:298)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:295)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1488)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Invalid format: "Mon Feb 13 15:00:00 CST 2017"
	at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187)
	at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:826)
	at org.elasticsearch.index.mapper.LegacyDateFieldMapper$DateFieldType.parseValue(LegacyDateFieldMapper.java:265)
	at org.elasticsearch.index.mapper.LegacyDateFieldMapper$DateFieldType.indexedValueForSearch(LegacyDateFieldMapper.java:277)
	at org.elasticsearch.index.mapper.TermBasedFieldType.termQuery(TermBasedFieldType.java:54)
	at org.elasticsearch.index.mapper.LegacyNumberFieldMapper$NumberFieldType.termQuery(LegacyNumberFieldMapper.java:117)
	at org.elasticsearch.index.search.MatchQuery.termQuery(MatchQuery.java:279)
	at org.elasticsearch.index.search.MatchQuery.blendTermQuery(MatchQuery.java:402)
	at org.elasticsearch.index.search.MatchQuery.parse(MatchQuery.java:243)
	at org.elasticsearch.index.query.MatchQueryBuilder.doToQuery(MatchQueryBuilder.java:466)
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97)
	at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$1(QueryShardContext.java:312)
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:329)
	... 14 more`

**Comment by engimatic** [comment]
Otherwith,when I try to use rangeQuery,I hava also catch with some error
```
private <T> ArrayList<T> connectES2(Calendar timestamp, String index, String type, Class<T> clazz) {

        ArrayList<T> values = new ArrayList<>();
        if (!client.admin().indices().prepareExists(index).execute().actionGet().isExists()) {
            System.out.println("索引" + index + "不存在");
            return values;
        }
        timestamp.add(Calendar.SECOND,10);
        Date end = timestamp.getTime();
        timestamp.add(Calendar.MINUTE,-1);
        Date start = timestamp.getTime();
        SearchResponse scrollResp = client.prepareSearch(index)
                .setTypes(type).setSearchType(SearchType.QUERY_THEN_FETCH)
                .setQuery(QueryBuilders.rangeQuery("start_timestamp").from(start).to(end))
                .setScroll(new TimeValue(60000))
                .setSize(10000).execute().actionGet();


        System.out.println(scrollResp.getHits().getTotalHits());


        while (true) {
            for (SearchHit hit : scrollResp.getHits().getHits()) {
                T value = JSON.parseObject(hit.sourceAsString(), clazz);
                values.add(value);
            }
            scrollResp = client.prepareSearchScroll(scrollResp.getScrollId()).setScroll(new TimeValue(60000)).execute
                    ().actionGet();
            //Break condition: No hits are returned
            if (scrollResp.getHits().getHits().length == 0) {
                break;
            }
        }
        return values;
    }
```
```
Exception in thread "main" Failed to execute phase [query], all shards failed; shardFailures {[sMXWKy4XSFOVQ1d8oZFWyw][http-stat-session-2017.02.09][0]: RemoteTransportException[[node-hot][10.128.9.207:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [Mon Feb 13 14:59:10 CST 2017] with format [strict_date_optional_time||epoch_millis]]; nested: IllegalArgumentException[Parse failure at index [0] of [Mon Feb 13 14:59:10 CST 2017]]; }{[sMXWKy4XSFOVQ1d8oZFWyw][http-stat-session-2017.02.09][1]: RemoteTransportException[[node-hot][10.128.9.207:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [Mon Feb 13 14:59:10 CST 2017] with format [strict_date_optional_time||epoch_millis]]; nested: IllegalArgumentException[Parse failure at index [0] of [Mon Feb 13 14:59:10 CST 2017]]; }{[sMXWKy4XSFOVQ1d8oZFWyw][http-stat-session-2017.02.09][2]: RemoteTransportException[[node-hot][10.128.9.207:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [Mon Feb 13 14:59:10 CST 2017] with format [strict_date_optional_time||epoch_millis]]; nested: IllegalArgumentException[Parse failure at index [0] of [Mon Feb 13 14:59:10 CST 2017]]; }{[sMXWKy4XSFOVQ1d8oZFWyw][http-stat-session-2017.02.09][3]: RemoteTransportException[[node-hot][10.128.9.207:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [Mon Feb 13 14:59:10 CST 2017] with format [strict_date_optional_time||epoch_millis]]; nested: IllegalArgumentException[Parse failure at index [0] of [Mon Feb 13 14:59:10 CST 2017]]; }{[sMXWKy4XSFOVQ1d8oZFWyw][http-stat-session-2017.02.09][4]: RemoteTransportException[[node-hot][10.128.9.207:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [Mon Feb 13 14:59:10 CST 2017] with format [strict_date_optional_time||epoch_millis]]; nested: IllegalArgumentException[Parse failure at index [0] of [Mon Feb 13 14:59:10 CST 2017]]; }
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:208)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$100(AbstractSearchAsyncAction.java:52)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:143)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1024)
	at org.elasticsearch.transport.TcpTransport.lambda$handleException$17(TcpTransport.java:1411)
	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:109)
	at org.elasticsearch.transport.TcpTransport.handleException(TcpTransport.java:1409)
	at org.elasticsearch.transport.TcpTransport.handlerResponseError(TcpTransport.java:1401)
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1345)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:527)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:481)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
Caused by: RemoteTransportException[[node-hot][10.128.9.207:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [Mon Feb 13 14:59:10 CST 2017] with format [strict_date_optional_time||epoch_millis]]; nested: IllegalArgumentException[Parse failure at index [0] of [Mon Feb 13 14:59:10 CST 2017]];
Caused by: ElasticsearchParseException[failed to parse date field [Mon Feb 13 14:59:10 CST 2017] with format [strict_date_optional_time||epoch_millis]]; nested: IllegalArgumentException[Parse failure at index [0] of [Mon Feb 13 14:59:10 CST 2017]];
	at org.elasticsearch.common.joda.DateMathParser.parseDateTime(DateMathParser.java:213)
	at org.elasticsearch.common.joda.DateMathParser.parse(DateMathParser.java:66)
	at org.elasticsearch.index.mapper.LegacyDateFieldMapper$DateFieldType.parseToMilliseconds(LegacyDateFieldMapper.java:396)
	at org.elasticsearch.index.mapper.LegacyDateFieldMapper$DateFieldType.isFieldWithinQuery(LegacyDateFieldMapper.java:350)
	at org.elasticsearch.index.query.RangeQueryBuilder.getRelation(RangeQueryBuilder.java:462)
	at org.elasticsearch.index.query.RangeQueryBuilder.doRewrite(RangeQueryBuilder.java:469)
	at org.elasticsearch.index.query.AbstractQueryBuilder.rewrite(AbstractQueryBuilder.java:264)
	at org.elasticsearch.search.builder.SearchSourceBuilder.rewrite(SearchSourceBuilder.java:860)
	at org.elasticsearch.search.internal.ShardSearchLocalRequest.rewrite(ShardSearchLocalRequest.java:232)
	at org.elasticsearch.search.internal.ShardSearchTransportRequest.rewrite(ShardSearchTransportRequest.java:166)
	at org.elasticsearch.search.SearchService.createSearchContext(SearchService.java:584)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:534)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:516)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:251)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:298)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:295)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1488)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Parse failure at index [0] of [Mon Feb 13 14:59:10 CST 2017]
	at org.elasticsearch.common.joda.DateMathParser.parseDateTime(DateMathParser.java:207)
	... 22 more

```

**Comment by engimatic** [comment]
I have resolved this issue.
The resolve method is easy.
With elastic2.2,we can use java.util.Date,but in elastic5.2,we should use org.joda.time.DateTime.Just do it like this
```
pre: QueryBuilders.matchQuery("start_timestamp", timestamp)
current: QueryBuilders.matchQuery("start_timestamp", new DateTime(timestamp))
```

**Comment by jayrorodrigues** [comment]
Thank's.
