### ISSUE TITLE
Throw NoNodeAvailableException after long scroll

### ISSUE THREAD

**Issue by phamptu** [elastic/elasticsearch#23137]
**Elasticsearch version**: 2.4.1

**Plugins installed**: [Sql, Head]

**JVM version**: 1.8

**OS version**: Ubuntu 16.04

**Description of the problem including expected versus actual behavior**: 
Throw NoNodeAvailableException after long scroll time. 

**Steps to reproduce**:
 1. Put 100 M of row into one index
 2. Using scroll to get all document by specific fields
 3. ES exception throw after scroll hundred time

**Provide logs (if relevant)**:
05:16:57.621 [main] WARN  c.d.r.export_data.ExportMissMatchDoc - NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{127.0.0.1:9300}]]
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{127.0.0.1:9300}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
        at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56)

**Describe the feature**:

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
