### ISSUE TITLE
[Tests] Occasional failure: IndexLookupIT.testCallWithDifferentFlagsFails

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#23203]
Spate of occasional failures recently on master with this error:

	  1> [2017-02-16T05:53:41,605][INFO ][o.e.s.IndexLookupIT      ] [IndexLookupIT#testCallWithDifferentFlagsFails]: cleaned up after test
	  1> [2017-02-16T05:53:41,605][INFO ][o.e.s.IndexLookupIT      ] [testCallWithDifferentFlagsFails]: after test
	  2> REPRODUCE WITH: gradle :core:integTest -Dtests.seed=CB09BE6BB3CAF2BA -Dtests.class=org.elasticsearch.script.IndexLookupIT -Dtests.method="testCallWithDifferentFlagsFails" -Dtests.security.manager=true -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" -Dtests.locale=fi-FI -Dtests.timezone=America/Miquelon
	FAILURE 0.36s J1 | IndexLookupIT.testCallWithDifferentFlagsFails <<< FAILURES!
	   > Throwable #1: java.lang.AssertionError: 
	   > Expected: <1>
	   >      but: was <2>
	   > 	at __randomizedtesting.SeedInfo.seed([CB09BE6BB3CAF2BA:DF6CD06AF0DAFC69]:0)
	   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	   > 	at org.elasticsearch.script.IndexLookupIT.testCallWithDifferentFlagsFails(IndexLookupIT.java:590)
	   > 	at java.lang.Thread.run(Thread.java:745)

Would not reproduce locally so opening this issue to track similar failures

**Comment by markharwood** [comment]
Managed to reproduce. The test seems strange - it assumes either >1 shards fail without throwing an exception or that exactly one of them should fail and throw an exception. 
I can see in a reproducable case (seed 6B40AF951FC8500E) that 2 shards report failure messages and an exception is thrown.

Presumably the general error-handling contract for search is if >1 primary shard succeeds then there is no exception and we report the partial failures. Only if _all_ shards fail do we then throw an exception. Is this true @s1monw ? If so the test does not test this contract properly.
