### ISSUE TITLE
Get NumberFormatException when input string > 2^31

### ISSUE THREAD

**Issue by charz** [elastic/elasticsearch#23235]
**Elasticsearch version**: 2.1.0 

**Plugins installed**: []

**JVM version**: 1.8.0_121

**OS version**: Ubuntu 14.04.2 LTS

**Description of the problem including expected versus actual behavior**:

When I do a bulk post with a large number (`> 2^31`) for content-length, I got 400 error due to an exception.

**Steps to reproduce**:

```
$ cat test.json ; curl -s -XPOST localhost:9200/bbk_idx/4 --data-binary "@test.json"
{
  "content-type" : "application\/octet-stream",
  "last-modified" : 1437426922000,
  "x-timestamp" : 1437426921794,
  "x-swift-object" : "demo.obj",
  "x-swift-account" : "AUTH_demo",
  "content-length" : "2147483646",
  "etag" : "7a6f8d3760aaab4d3a9d41785519947b",
  "x-swift-container" : "container"
}

{"_index":"bbk_idx","_type":"4","_id":"AVpMhBgtQm440Iyz7XhV","_version":1,"_shards":{"total":1,"successful":1,"failed":0},"created":true}vagrant@vagrant-ubuntu-trusty-64:~$ cat test.json ; curl -s -XPOST localhost:9200/bbk_idx/4 --data-binary "@test.json"                               


~$ cat bad.json ; curl -s -XPOST localhost:9200/bbk_idx/4 --data-binary "@bad.json"
{
  "content-type" : "application\/octet-stream",
  "last-modified" : 1437426922000,
  "x-timestamp" : 1437426921794,
  "x-swift-object" : "demo.obj",
  "x-swift-account" : "AUTH_demo",
  "content-length" : "2147483699",
  "etag" : "7a6f8d3760aaab4d3a9d41785519947b",
  "x-swift-container" : "container"
}

{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse [content-length]"}],"type":"mapper_parsing_exception","reason":"failed to parse [content-length]","caused_by":{"type":"number_format_exception","reason":"For input string: \"2147483699\""}},"status":400}
``` 

**Provide logs (if relevant)**:

```
[2017-02-17 14:40:51,704][DEBUG][action.index             ] [ansible-es-1] [bbk_idx][0], node[eJ3JivobT4uP2P_JTAMUPw], [P], v[2], s[STARTED], a[id=XlK50ZItS7Sjv5iaL7xZGA]: Failed to execute [index {[bbk_idx][4][AVpMhLv3Qm440Iyz7XhW], source[{
  "content-type" : "application\/octet-stream",
  "last-modified" : 1437426922000,
  "x-timestamp" : 1437426921794,
  "x-swift-object" : "demo.obj",
  "x-swift-account" : "AUTH_demo",
  "content-length" : "2147483699",
  "etag" : "7a6f8d3760aaab4d3a9d41785519947b",
  "x-swift-container" : "container"
}

]}]
MapperParsingException[failed to parse [content-length]]; nested: NumberFormatException[For input string: "2147483699"];
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:339)
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:314)
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:441)
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:267)
	at org.elasticsearch.index.mapper.DocumentParser.innerParseDocument(DocumentParser.java:127)
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:79)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:318)
	at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:516)
	at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:507)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.prepareIndexOperationOnPrimary(TransportReplicationAction.java:1052)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.executeIndexRequestOnPrimary(TransportReplicationAction.java:1060)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:170)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.performOnPrimary(TransportReplicationAction.java:579)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase$1.doRun(TransportReplicationAction.java:452)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "2147483699"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.intValue(AbstractXContentParser.java:126)
	at org.elasticsearch.index.mapper.core.IntegerFieldMapper.innerParseCreateField(IntegerFieldMapper.java:288)
	at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:213)
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:331)
	... 17 more
[2017-02-17 14:40:51,705][INFO ][rest.suppressed          ] /bbk_idx/4 Params: {index=bbk_idx, type=4}
MapperParsingException[failed to parse [content-length]]; nested: NumberFormatException[For input string: "2147483699"];
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:339)
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:314)
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:441)
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:267)
	at org.elasticsearch.index.mapper.DocumentParser.innerParseDocument(DocumentParser.java:127)
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:79)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:318)
	at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:516)
	at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:507)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.prepareIndexOperationOnPrimary(TransportReplicationAction.java:1052)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.executeIndexRequestOnPrimary(TransportReplicationAction.java:1060)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:170)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.performOnPrimary(TransportReplicationAction.java:579)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase$1.doRun(TransportReplicationAction.java:452)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "2147483699"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.intValue(AbstractXContentParser.java:126)
	at org.elasticsearch.index.mapper.core.IntegerFieldMapper.innerParseCreateField(IntegerFieldMapper.java:288)
	at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:213)
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:331)
	... 17 more
```

**Describe the feature**:

**Comment by jpountz** [comment]
I think you should map your field as a `long`? It is currently mapped as an integer, so all values are expected to be between `-2^31` and `2^31-1`.
