### ISSUE TITLE
ES Crashes When Using A Nest Document Agg, Then Specifying The Path A Second Time

### ISSUE THREAD

**Issue by neoform** [elastic/elasticsearch#23299]
**Elasticsearch version**: 5.2.1

**Plugins installed**: []

**JVM version**: 1.8.0_121

**OS version**: Debian 8

**Description of the problem including expected versus actual behavior**:

**Possibly related to Issue**: #23280

**Steps to reproduce**:
 1. Create an agg that makes use of nested document.
 2. In a sub-agg, list that path a second time.
 3. Execute search
 4. ElasticSearch crashes

**Provide logs (if relevant)**:

```
[2017-02-21T21:19:15,059][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [elasticsearch[ddjlYjR][search][T#3]], exiting
java.lang.AssertionError: null
	at org.apache.lucene.search.join.ToParentBlockJoinQuery$BlockJoinScorer$1.nextDoc(ToParentBlockJoinQuery.java:289) ~[lucene-join-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:44:23]
	at org.apache.lucene.search.join.ToParentBlockJoinQuery$BlockJoinScorer$1.advance(ToParentBlockJoinQuery.java:382) ~[lucene-join-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:44:23]
	at org.elasticsearch.common.lucene.Lucene$3.get(Lucene.java:785) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregator$1.collect(FilterAggregator.java:63) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectExistingBucket(BucketsAggregator.java:80) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectBucket(BucketsAggregator.java:72) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.search.aggregations.bucket.nested.NestedAggregator$1.collect(NestedAggregator.java:89) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.search.aggregations.AggregatorFactory$MultiBucketAggregatorWrapper$1.collect(AggregatorFactory.java:137) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectExistingBucket(BucketsAggregator.java:80) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectBucket(BucketsAggregator.java:72) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.search.aggregations.bucket.global.GlobalAggregator$1.collect(GlobalAggregator.java:51) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:82) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:221) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:172) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:669) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:473) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
	at org.elasticsearch.search.aggregations.AggregationPhase.execute(AggregationPhase.java:127) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:112) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:246) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:360) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.action.search.SearchTransportService$9.messageReceived(SearchTransportService.java:322) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.action.search.SearchTransportService$9.messageReceived(SearchTransportService.java:319) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:610) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.2.1.jar:5.2.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Describe the feature**:

```javascript
{
    "timeout": "6s",
    "index": "product",
    "type": "product",
    "from": 0,
    "size": 40,
    "body": {
        "_source": [
            "mpn",
            "cheapest_product_id",
            "price",
            "price_discount_percent",
            "price_discount_amount",
            "product_count",
            "rank_weight",
            "product.id",
            "product.price",
            "product.status_id"
        ],
        "query": {
            "function_score": {
                "query": {
                    "bool": {
                        "filter": [
                            {
                                "nested": {
                                    "path": "product",
                                    "query": {
                                        "bool": {
                                            "filter": [
                                                {
                                                    "term": {
                                                        "product.status_id": 1
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        ]
                    }
                },
                "functions": [
                    {
                        "field_value_factor": {
                            "field": "product_count",
                            "factor": 50,
                            "modifier": "log1p"
                        }
                    },
                    {
                        "field_value_factor": {
                            "field": "rank_weight",
                            "modifier": "reciprocal",
                            "missing": 1
                        }
                    }
                ]
            }
        },
        "aggs": {
            "brands": {
                "global": {},
                "aggs": {
                    "brands": {
                        "nested": {
                            "path": "product.brand"
                        },
                        "aggs": {
                            "brands": {
                                "filter": {
                                    "bool": {
                                        "filter": [
                                            {
                                                "nested": {
                                                    "path": "product",
                                                    "query": {
                                                        "bool": {
                                                            "filter": [
                                                                {
                                                                    "term": {
                                                                        "product.status_id": 1
                                                                    }
                                                                }
                                                            ]
                                                        }
                                                    }
                                                }
                                            }
                                        ]
                                    }
                                },
                                "aggs": {
                                    "brands": {
                                        "nested": {
                                            "path": "product.brand"
                                        },
                                        "aggs": {
                                            "brands": {
                                                "terms": {
                                                    "field": "product.brand.id",
                                                    "size": 30
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```
For comparison, this query does not crash the server.

```javascript
{
    "timeout": "6s",
    "index": "product",
    "type": "product",
    "from": 0,
    "size": 40,
    "body": {
        "_source": [
            "mpn",
            "cheapest_product_id",
            "price",
            "price_discount_percent",
            "price_discount_amount",
            "product_count",
            "rank_weight",
            "product.id",
            "product.price",
            "product.status_id"
        ],
        "query": {
            "function_score": {
                "query": {
                    "bool": {
                        "filter": [
                            {
                                "nested": {
                                    "path": "product",
                                    "query": {
                                        "bool": {
                                            "filter": [
                                                {
                                                    "term": {
                                                        "product.status_id": 1
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        ]
                    }
                },
                "functions": [
                    {
                        "field_value_factor": {
                            "field": "product_count",
                            "factor": 50,
                            "modifier": "log1p"
                        }
                    },
                    {
                        "field_value_factor": {
                            "field": "rank_weight",
                            "modifier": "reciprocal",
                            "missing": 1
                        }
                    }
                ]
            }
        },
        "aggs": {
            "brands": {
                "global": {},
                "aggs": {
                    "brands": {
                        "filter": {
                            "bool": {
                                "filter": [
                                    {
                                        "nested": {
                                            "path": "product",
                                            "query": {
                                                "bool": {
                                                    "filter": [
                                                        {
                                                            "term": {
                                                                "product.status_id": 1
                                                            }
                                                        }
                                                    ]
                                                }
                                            }
                                        }
                                    }
                                ]
                            }
                        },
                        "aggs": {
                            "brands": {
                                "nested": {
                                    "path": "product.brand"
                                },
                                "aggs": {
                                    "brands": {
                                        "terms": {
                                            "field": "product.brand.id",
                                            "size": 30
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by jpountz** [comment]
This seems to be the same issue as #23280 indeed.

**Comment by neoform** [comment]
Thought so. Outcome was slightly different though, since this actually kills the ES instance completely.

**Comment by jpountz** [comment]
Right, this is because you added `-ea` to tje JVM options and Elasticsearch hit an assertion error, which makes the node stop.

Closing in favour of #23280.
