### ISSUE TITLE
2.4.1 reindex api - Invalid index name [_reindex]

### ISSUE THREAD

**Issue by bezoadam** [elastic/elasticsearch#23368]
**Elasticsearch version**: 2.4.1

**Plugins installed**: []

**JVM version**:1.8.0_121

**OS version**:macOS Sierra

**Description of the problem including expected versus actual behavior**:
I am trying to use _reindex api. Receiving this error 

> "reason":"Invalid index name [_reindex], must not start with '_'"

**Steps to reproduce**:
 1. Executing this code `curl -XPUT localhost:9200/_reindex -d '{
  "source": {
    "index": "web"
  },
  "dest": {
    "index": "web03"
  }
}'`

**Provide logs (if relevant)**:
elasticsearch log
`[2017-02-25 10:07:10,964][DEBUG][action.admin.indices.create] [Warren III Worthington] [_reindex] failed to create
[_reindex] InvalidIndexNameException[Invalid index name [_reindex], must not start with '_']
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDataCreateIndexService.java:148)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validate(MetaDataCreateIndexService.java:431)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$100(MetaDataCreateIndexService.java:95)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1.execute(MetaDataCreateIndexService.java:190)
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

plugins and modules installed

`[2017-02-25 09:28:20,237][INFO ][plugins                  ] [Warren III Worthington] modules [reindex, lang-expression, lang-groovy], plugins [], sites []`

**Comment by dadoonet** [comment]
Wrong HTTP Verb.
Should be POST.

See https://www.elastic.co/guide/en/elasticsearch/reference/5.2/docs-reindex.html#docs-reindex

**Comment by bezoadam** [comment]
You are rigth, sorry my mistake. I apologize.
