### ISSUE TITLE
ES 5.2.1 and enabling cors does not work

### ISSUE THREAD

**Issue by heikkis** [elastic/elasticsearch#23409]
**Elasticsearch version**: 5.2.1
**Plugins installed**: none
**JVM version**:  OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)

**OS version**: Docker Ubuntu (sebp/elk:521)

**Description of the problem including expected versus actual behavior**:

Using metricbeat with ELK stack 5.2.1.

Added these lines

http.cors.enabled: true
http.cors.allow-origin: "*"

to /etc/elasticsearch/elasticsearch.yml and restarted the system. Still no cors headers is added.

I checked with configuration error that the config file is in use for elastic search.

Tested headers:
```
curl -H "User-Agent: Mozilla" -H "Origin: http://example.com" -i localhost:9206
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 327

{
  "name" : "l2cjPKp",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "sbZUro92QpGGVrhlsscx8A",
  "version" : {
    "number" : "5.2.1",
    "build_hash" : "db0d481",
    "build_date" : "2017-02-09T22:05:32.386Z",
    "build_snapshot" : false,
    "lucene_version" : "6.4.1"
  },
  "tagline" : "You Know, for Search"
}
```
**Steps to reproduce**:
 1. Docker image sebp/elk:521
 2. Add config lines to elasticsearch.yml
 3. No cors header is added by elastic search

**Provide logs (if relevant)**:

**Comment by heikkis** [comment]
```
# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
#cluster.name: my-application
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
#node.name: node-1
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
#path.data: /path/to/data
#
# Path to log files:
#
#path.logs: /path/to/logs
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: 0.0.0.0
#
# Set a custom port for HTTP:
#
#http.port: {{ elk_stack.docker_elk_elasticsearch_json_port }}
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#discovery.zen.ping.unicast.hosts: ["host1", "host2"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of master-eligible nodes / 2 + 1):
#
#discovery.zen.minimum_master_nodes: 3
#
# For more information, consult the zen discovery module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true

#xpack.security.enabled: {{elk_stack.docker_xpack_security_enabled}}
#xpack.monitoring.enabled: false

http.cors.enabled: true
http.cors.allow-origin: "*"

```

**Comment by heikkis** [comment]
```
-bash-4.2$ docker top elk_stack_nginx_monitoring
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                10218               9508                0                   15:59               ?                   00:00:00            /bin/bash /usr/local/bin/start.sh
root                10270               10218               0                   15:59               ?                   00:00:00            /usr/sbin/cron
mongod              10302               10218               7                   15:59               ?                   00:00:28            /usr/bin/java -Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -server -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -Djdk.io.permissionsUseCanonicalPath=true -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -XX:+HeapDumpOnOutOfMemoryError -Des.path.home=/opt/elasticsearch -cp /opt/elasticsearch/lib/elasticsearch-5.2.1.jar:/opt/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -d -p /var/run/elasticsearch/elasticsearch.pid -Edefault.path.logs=/var/log/elasticsearch -Edefault.path.data=/var/lib/elasticsearch -Edefault.path.conf=/etc/elasticsearch
logstash            10642               10218               18                  15:59               ?                   00:01:07            /usr/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -Djava.awt.headless=true -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=/opt/logstash -Xmx1g -Xms256m -Xss2048k -Djffi.boot.library.path=/opt/logstash/vendor/jruby/lib/jni -Xbootclasspath/a:/opt/logstash/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/opt/logstash/vendor/jruby -Djruby.lib=/opt/logstash/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main /opt/logstash/lib/bootstrap/environment.rb logstash/runner.rb --path.config /etc/logstash/conf.d --path.logs /var/log/logstash
993                 10662               10218               1                   15:59               ?                   00:00:05            /opt/kibana/bin/../node/bin/node --max-old-space-size=250 --no-warnings /opt/kibana/bin/../src/cli -l /var/log/kibana/kibana5.log
root                10665               10218               0                   15:59               ?                   00:00:00            tail -f /var/log/elasticsearch/elasticsearch.log /var/log/logstash/logstash-plain.log /var/log/kibana/kibana5.log
-bash-4.2$
```

**Comment by clintongormley** [comment]
Adding the config that you mentioned works just fine. I think you may be adding it to the wrong place.  Not sure which docker image you're using, but if it is ours, then the config is in `/usr/share/elasticsearch/config`.  See https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-configuration-methods

**Comment by heikkis** [comment]
Hello @clintongormley!

The command running elastic search has parameter:
-Edefault.path.conf=/etc/elasticsearch

If I make on error to my config file elastic search does not start at all and error is shown correctly. There are nothing in path /usr/share/elasticsearch/ .

**Comment by heikkis** [comment]
Full command for elastic search:

/usr/bin/java -Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -server -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -Djdk.io.permissionsUseCanonicalPath=true -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -XX:+HeapDumpOnOutOfMemoryError -Des.path.home=/opt/elasticsearch -cp /opt/elasticsearch/lib/elasticsearch-5.2.1.jar:/opt/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -d -p /var/run/elasticsearch/elasticsearch.pid -Edefault.path.logs=/var/log/elasticsearch -Edefault.path.data=/var/lib/elasticsearch -Edefault.path.conf=/etc/elasticsearch

**Comment by heikkis** [comment]
root@6dd211281f8a:/# cat /etc/elasticsearch/elasticsearch.yml | grep -v -F '#'
network.host: 0.0.0.0

http.cors.enabled: true
http.cors.allow-origin: "*"
root@6dd211281f8a:/#

**Comment by heikkis** [comment]
Showing the configuration file is used:

`docker exec elk_stack_nginx_monitoring sh -c 'echo testing >> /etc/elasticsearch/elasticsearch.yml; cat /etc/elasticsearch/elasticsearch.yml | grep -v -F "#"'`

After restarting the container I got error msg:

```
 * Starting Elasticsearch Server
Exception in thread "main" SettingsException[Failed to load settings from /etc/elasticsearch/elasticsearch.yml]; nested: MarkedYAMLException[while scanning a simple key
 in 'reader', line 95, column 1:
    testing
    ^
could not find expected ':'
 in 'reader', line 96, column 1:
    testing
    ^
...
http.cors.enabled: true
http.cors.allow-origin: "*"
testing
testing
; line: 94, column: 28]]; nested: ScannerException[while scanning a simple key
 in 'reader', line 95, column 1:
    testing
    ^
could not find expected ':'
 in 'reader', line 96, column 1:
    testing
    ^
];
Likely root cause: while scanning a simple key
 in 'reader', line 95, column 1:
    testing
    ^
could not find expected ':'
 in 'reader', line 96, column 1:
    testing
    ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465)
	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:340)
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:55)
	at org.elasticsearch.common.settings.loader.XContentSettingsLoader.serializeObject(XContentSettingsLoader.java:105)
	at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(XContentSettingsLoader.java:75)
	at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(XContentSettingsLoader.java:52)
	at org.elasticsearch.common.settings.loader.YamlSettingsLoader.load(YamlSettingsLoader.java:50)
	at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:925)
	at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Settings.java:914)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:102)
	at org.elasticsearch.bootstrap.Bootstrap.initialEnvironment(Bootstrap.java:257)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:297)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)
Refer to the log for complete error details.
   ...fail!
```

**Comment by heikkis** [comment]
My mistake could be port configuration mismatch. I will look into it more. Thanks for encouragement 👍

**Comment by heikkis** [comment]
Kibana issue https://github.com/elastic/kibana/issues/10620 created because it seems to be Kibana issue.
