### ISSUE TITLE
GetResponse.toString method throws exception

### ISSUE THREAD

**Issue by nikpanos** [elastic/elasticsearch#23505]
Elasticsearch version: 5.2.2
JVM version: 1.8
OS: Windows 10
I am able to reproduce the bug on all 5.2.x versions of client transport library.

I have a GetResponse object which i want to display in console by calling the toString method. It throws the following exception:
Error building toString out of XContent: com.fasterxml.jackson.core.JsonGenerationException: Can not start an object, expecting field name (context: Object)
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1897)
	at com.fasterxml.jackson.core.json.JsonGeneratorImpl._reportCantWriteValueExpectName(JsonGeneratorImpl.java:244)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._verifyValueWrite(UTF8JsonGenerator.java:1027)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeStartObject(UTF8JsonGenerator.java:313)
	at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.writeStartObject(JsonXContentGenerator.java:161)
	at org.elasticsearch.common.xcontent.XContentBuilder.startObject(XContentBuilder.java:217)
	at org.elasticsearch.index.get.GetResult.toXContent(GetResult.java:251)
	at org.elasticsearch.action.get.GetResponse.toXContent(GetResponse.java:158)
	at org.elasticsearch.common.Strings.toString(Strings.java:901)
	at org.elasticsearch.action.get.GetResponse.toString(GetResponse.java:197)
	at gr.unipi.elastic.App.main(App.java:48)

**Comment by cbuescher** [comment]
I can reproduce this, but it should only affect the 5.2.x releases and is already fixed in the next minor version (5.3). In the meantime you can use `org.elasticsearch.common.Strings.toString(getResponse, false)` as a temporary workaround. @javanna do you think there should be a fix on the 5.2 branch in case there is going to be a 5.2.3 release?

**Comment by fangqiao** [comment]
Please do fix this ASAP. I have a production system that dump the getResponse  result as json string to  a custom REST client by relying on this toString method. It caused serious problem.

**Comment by cbuescher** [comment]
Fixed in 5.3 and upwards, closing this after adding tests to the related branches.

**Comment by javanna** [comment]
@fangqiao do you mean that you are using the output of the toString method to send the request via a REST client? If that is the case, I would recommend to move your code to calling the `toXContent` method instead. In fact, there is no guarantee that the `toString` method will always print out valid json, we could potentially change that in the future.

**Comment by fangqiao** [comment]
@javana Thanks. It was a quick and dirty solution. Shall follow your suggestions.
