### ISSUE TITLE
Reading aggregation cache throw EOFException

### ISSUE THREAD

**Issue by FrankXia** [elastic/elasticsearch#23529]
**Elasticsearch version**: 
5.1.2

**Plugins installed**: [] 
Custom plugin for multi-buket aggregation

**JVM version**:
1.8.0_121

**OS version**: 
MacOS 10.12.3

**Description of the problem including expected versus actual behavior**:
When aggregation cache is turned on ("size":0), the intermediate multi-bucket aggregation results are written to cache via API call writeTo(StreamOutput out) but when the data was read back via Bucket(StreamInput in), the data didn't get read back correctly and the ES server throw an EOFException. 

    @Override
    public void writeTo(StreamOutput out) throws IOException {
      System.out.println();
      System.out.println("out.squareCode =" + squareCode);
      System.out.println("out.docCount =" + docCount);
      System.out.println("out.precision =" + precision);
      out.writeVLong(squareCode);
      out.writeVLong(docCount);
      out.writeVInt(precision);
      aggregations.writeTo(out);
    }

    /**
     * Read from a stream.
     */
    private Bucket(StreamInput in) throws IOException {
      System.out.println();
      squareCode = in.readLong();
      System.out.println("in.squareCode =" + squareCode);
      docCount = in.readVLong();
      System.out.println("in.docCount =" + docCount);
      precision = in.readVInt();
      System.out.println("in.precision =" + precision);
      aggregations = InternalAggregations.readAggregations(in);
    }

These are sample output from above "writeTo" method, 
out.squareCode =61
out.docCount =16
out.precision =2

out.squareCode =45
out.docCount =11
out.precision =2

out.squareCode =61
out.docCount =19
out.precision =2

The following are the reading back data via Bucket(StreamInput in) before thrown EOFException, 
in.squareCode =4400863460650320384
in.docCount =40
in.precision =1

in.squareCode =4400019035719926272
in.docCount =0
in.precision =0

in.squareCode =3248223431288750592
in.docCount =0
in.precision =0

We expect to receive the same data that were written to the cache. 

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:
org.elasticsearch.transport.RemoteTransportException: [lBmUdf8][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.ElasticsearchException: java.io.EOFException
	at org.elasticsearch.ExceptionsHelper.convertToRuntime(ExceptionsHelper.java:48) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:292) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:300) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:297) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:577) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:527) [elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.1.2.jar:5.1.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.io.EOFException
	at org.elasticsearch.common.bytes.BytesReferenceStreamInput.readByte(BytesReferenceStreamInput.java:51) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper.readByte(BytesReference.java:231) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.common.io.stream.FilterStreamInput.readByte(FilterStreamInput.java:40) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.common.io.stream.StreamInput.readInt(StreamInput.java:173) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.common.io.stream.StreamInput.readLong(StreamInput.java:212) ~[elasticsearch-5.1.2.jar:5.1.2]
	at com.esri.arcgis.bds.aggregation.bucket.squaregrid.LongInternalSquareGrid$Bucket.<init>(LongInternalSquareGrid.java:36) ~[?:?]
	at com.esri.arcgis.bds.aggregation.bucket.squaregrid.LongInternalSquareGrid$Bucket.<init>(LongInternalSquareGrid.java:17) ~[?:?]
	at com.esri.arcgis.bds.aggregation.bucket.squaregrid.LongInternalSquareGrid.lambda$new$4(LongInternalSquareGrid.java:113) ~[?:?]
	at org.elasticsearch.common.io.stream.StreamInput.readList(StreamInput.java:859) ~[elasticsearch-5.1.2.jar:5.1.2]
	at com.esri.arcgis.bds.aggregation.bucket.squaregrid.LongInternalSquareGrid.<init>(LongInternalSquareGrid.java:113) ~[?:?]
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:40) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.search.aggregations.InternalAggregations.lambda$readFrom$2(InternalAggregations.java:200) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.common.io.stream.StreamInput.readList(StreamInput.java:859) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.search.aggregations.InternalAggregations.readFrom(InternalAggregations.java:200) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.search.aggregations.InternalAggregations.readAggregations(InternalAggregations.java:190) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.search.aggregations.bucket.InternalSingleBucketAggregation.<init>(InternalSingleBucketAggregation.java:61) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.search.aggregations.bucket.filter.InternalFilter.<init>(InternalFilter.java:39) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:40) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.search.aggregations.InternalAggregations.lambda$readFrom$2(InternalAggregations.java:200) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.common.io.stream.StreamInput.readList(StreamInput.java:859) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.search.aggregations.InternalAggregations.readFrom(InternalAggregations.java:200) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.search.aggregations.InternalAggregations.readAggregations(InternalAggregations.java:190) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.search.query.QuerySearchResult.readFromWithId(QuerySearchResult.java:221) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.indices.IndicesService.loadIntoContext(IndicesService.java:1171) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:257) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:273) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:300) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:297) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:577) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:527) ~[elasticsearch-5.1.2.jar:5.1.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.1.2.jar:5.1.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_121]

**Comment by colings86** [comment]
I think the error might be in your `writeTo()` and `readFrom()` implementations. in you `writeTo()` method above you are doing `out.writeVLong(squareCode);` (writing a VLong) but in the `readFrom()` method above you are doing `squareCode = in.readLong();` (reading a Long instead of a VLong). This will mean the read method will in some case read past the long into the next field causing it to get to the end of the stream before it expects to.

**Comment by sherry-ger** [comment]
Aligning read and write resolved the issue.  Closing.
