### ISSUE TITLE
Killing the elected master causes all other nodes in cluster to immediately exit

### ISSUE THREAD

**Issue by loren** [elastic/elasticsearch#23615]
**Elasticsearch version**: 5.2.2

**Plugins installed**: [x-pack]

**JVM version**: 8u121

**OS version**: CentOS Linux release 7.3.1611 (Core)

**Description of the problem including expected versus actual behavior**:
From https://discuss.elastic.co/t/problem-with-master-re-election-under-zendiscovery-5-2-2/78617:
Killing the elected master elasticsearch process causes all other nodes to throw an exception and immediately exit. I expected a master re-election to take place instead.

I do **not** see this behavior in 5.2.0, so it seems to be a regression.

**Steps to reproduce**:
I have 7 elasticsearch nodes distributed around 5 EC2 instances running CentOS. The 7 nodes are composed of 3 master-only nodes, 2 data-only, 1 ingest-only, and 1 coordinator-only. X-pack is installed.

The general `elasticsearch.yml` template looks like this:
```yml
discovery.zen.ping.unicast.hosts:
  - "master-0-node.{{FRAMEWORK_NAME}}.mesos:{{MASTER_NODE_TRANSPORT_PORT}}"
  - "master-1-node.{{FRAMEWORK_NAME}}.mesos:{{MASTER_NODE_TRANSPORT_PORT}}"
  - "master-2-node.{{FRAMEWORK_NAME}}.mesos:{{MASTER_NODE_TRANSPORT_PORT}}"
discovery.zen.minimum_master_nodes: 2
network.host:
  - "_site_"
  - "_local_"
cluster.name: {{FRAMEWORK_NAME}}
node.name: {{TASK_NAME}}
path.data: "container-path/data"
path.logs: "container-path/logs"
http.port: {{PORT_HTTP}}
transport.tcp.port: {{PORT_TRANSPORT}}
bootstrap.memory_lock: false
node.master: {{MASTER_ENABLED}}
node.data: {{DATA_ENABLED}}
node.ingest: {{INGEST_ENABLED}}
metrics.statsd.host: {{STATSD_UDP_HOST}}
metrics.statsd.port: {{STATSD_UDP_PORT}}
```
It then gets interpolated for each node based on those env vars.

1. `kill -9` elasticsearch process of elected master
2. watch entire cluster shut down

**Provide logs (if relevant)**:
```
[2017-03-14T22:45:10,208][INFO ][o.e.d.z.ZenDiscovery ] [master-1-node] master_left [{master-0-node}{SzqZbCT_SfGjukio5cYrBg}{v58Bm3MKR4-Ucf1cEmBkmw}{10.0.1.79}{10.0.1.79:9300}], reason [transport disconnected]
[2017-03-14T22:45:10,210][WARN ][o.e.d.z.ZenDiscovery ] [master-1-node] master left (reason = transport disconnected), current nodes: nodes: 
{master-1-node}{DL_sqiHoRg2bLCiD9tWh-w}{Ty-AlN5cRTWEBObmCJ9Z3g}{10.0.1.87}{10.0.1.87:9300}, local
{ingest-0-node}{tsGRRLHWSG6DOZ-b9A-wRg}{XXhtyKeLS9W4x6HmpNxitw}{10.0.2.99}{10.0.2.99:1028}
{data-0-node}{szxoWgObSaS8gE4BaSn5nw}{vC1s4MiXQPa9d2CEsyrLCg}{10.0.1.227}{10.0.1.227:1026}
{coordinator-0-node}{OxleJ2AcRlib9I18Vm1mOw}{DmUC-IUCTDW8GULDHYxbfQ}{10.0.1.227}{10.0.1.227:1028}
{master-0-node}{SzqZbCT_SfGjukio5cYrBg}{v58Bm3MKR4-Ucf1cEmBkmw}{10.0.1.79}{10.0.1.79:9300}, master
{master-2-node}{wr9bqzZ4SeeJflwtE88hSA}{7rCvWpSLSuOdIk6nohbGuw}{10.0.1.190}{10.0.1.190:9300}
{data-1-node}{WVL4cVOlTFesySvUv2gR0g}{jG105Vj9Rl6J5C-qFE19dw}{10.0.2.99}{10.0.2.99:1026}

[2017-03-14T22:45:10,226][WARN ][o.e.c.NodeConnectionsService] [master-1-node] failed to connect to node {master-0-node}{SzqZbCT_SfGjukio5cYrBg}{v58Bm3MKR4-Ucf1cEmBkmw}{10.0.1.79}{10.0.1.79:9300} (tried [1] times)
org.elasticsearch.transport.ConnectTransportException: [master-0-node][10.0.1.79:9300] connect_timeout[30s]
at org.elasticsearch.transport.netty4.Netty4Transport.connectToChannels(Netty4Transport.java:370) ~[?:?]
at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:495) ~[elasticsearch-5.2.2.jar:5.2.2]
at org.elasticsearch.transport.TcpTransport.connectToNode(TcpTransport.java:460) ~[elasticsearch-5.2.2.jar:5.2.2]
at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:318) ~[elasticsearch-5.2.2.jar:5.2.2]
at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:305) ~[elasticsearch-5.2.2.jar:5.2.2]
at org.elasticsearch.cluster.NodeConnectionsService.validateNodeConnected(NodeConnectionsService.java:121) [elasticsearch-5.2.2.jar:5.2.2]
at org.elasticsearch.cluster.NodeConnectionsService.connectToNodes(NodeConnectionsService.java:87) [elasticsearch-5.2.2.jar:5.2.2]
at org.elasticsearch.cluster.service.ClusterService.publishAndApplyChanges(ClusterService.java:775) [elasticsearch-5.2.2.jar:5.2.2]
at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:628) [elasticsearch-5.2.2.jar:5.2.2]
at org.elasticsearch.cluster.service.ClusterService$UpdateTask.run(ClusterService.java:1112) [elasticsearch-5.2.2.jar:5.2.2]
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:527) [elasticsearch-5.2.2.jar:5.2.2]
at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:238) [elasticsearch-5.2.2.jar:5.2.2]
at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:201) [elasticsearch-5.2.2.jar:5.2.2]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 10.0.1.79/10.0.1.79:9300
at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:346) ~[?:?]
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[?:?]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:630) ~[?:?]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:527) ~[?:?]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:481) ~[?:?]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441) ~[?:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[?:?]
... 1 more
[2017-03-14T22:45:10,349][INFO ][o.e.n.Node ] [master-1-node] stopping ...
```

Seems like when Netty complains about "Connection refused", it's fatal.

**Comment by jasontedor** [comment]
Let's keep the discussion on the [forum](https://discuss.elastic.co/t/problem-with-master-re-election-under-zendiscovery-5-2-2/78617) instead of fracturing the discussion. We can reopen here if there is a verified bug, but this absolutely does not reproduce with your steps. I suspect that there is something about your setup that you're not telling us.
