### ISSUE TITLE
elasticsearch5.2.1 install plugin by local failure

### ISSUE THREAD

**Issue by hexian55** [elastic/elasticsearch#23693]
**Elasticsearch version**:
5.2.1
**Plugins installed**: [search-guard-5-5.2.1-11,analysis-smartcn-5.2.1]

**JVM version**:
1.8
**OS version**:
centos7.0
**Description of the problem including expected versus actual behavior**:
bin/elasticsearch-plugin install by local failure
**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

hi
when I install plugin by local  always failure .
eg:  install search-guard-5-5.2.1-11 and analysis-smartcn-5.2.1
I download search-guard from https://repo1.maven.org/maven2/com/floragunn/search-guard-5/5.2.1-11/search-guard-5-5.2.1-11.zip

bin/elasticsearch-plugin install file:///home/work/app/elasticsearch/plugins/search-guard-5-5.2.1-11.zip
error log:
-> Downloading file:///home/work/app/elasticsearch/plugins/search-guard-5-5.2.1-11.zip
[=================================================] 100%
Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [search-guard-5-5.2.1-11.zip]. Was the plugin built before 2.0?
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:295)
	at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:463)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:444)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:486)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:195)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
Caused by: java.nio.file.FileSystemException: /home/work/app/elasticsearch/plugins/search-guard-5-5.2.1-11.zip/plugin-descriptor.properties: Not a directory
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:86)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:292)
	... 11 more

when I unzip the file,
ls 
commons-cli-1.3.1.jar             netty-transport-4.1.7.Final.jar
guava-19.0.jar                    plugin-descriptor.properties
netty-buffer-4.1.7.Final.jar      plugin-security.policy
netty-codec-4.1.7.Final.jar       search-guard-5-5.2.1-11.jar
netty-codec-http-4.1.7.Final.jar  search-guard-ssl-5.2.1-20.jar
netty-common-4.1.7.Final.jar      sgconfig
netty-handler-4.1.7.Final.jar     tools
netty-resolver-4.1.7.Final.jar    transport-netty4-client-5.2.1.jar

cat  plugin-descriptor.properties
description=Provide access control related features for Elasticsearch 5
version=5.2.1-11
name=search-guard-5
classname=com.floragunn.searchguard.SearchGuardPlugin
java.version=1.8
elasticsearch.version=5.2.1

When I install analysis-smartcn-5.2.1,It's the same error
please help me.thx

**Comment by johtani** [comment]
Please ask questions on [the forum](https://discuss.elastic.co/c/elasticsearch). Elastic reserves GitHub for verified bug reports and feature requests.

**Comment by hexian55** [comment]
@johtani   please see  https://discuss.elastic.co/t/elasticsearch5-2-1-install-plugin-by-local-failure/79546
