### ISSUE TITLE
CI: BasicAnalysisBackwardCompatibilityIT.testAnalyzerTokensAfterUpgrade fails 

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#23700]
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+2.4+periodic/2188

I have trouble reproducing this right now on the 2.4 branch so far, but there are similar failures in the past on the 2.4 branch, e.g.
http://build-us-00.elastic.co/job/es_core_24_windows-2012-r2/2198/
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+2.4+periodic/2101

The errors look like this:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+2.4+periodic/2188/consoleFull
```
[2017-03-22 15:21:47,485][INFO ][node                     ] [external_ReindexBackwardsCompatibilityIT_0] started
Suite: org.elasticsearch.bwcompat.BasicAnalysisBackwardCompatibilityIT
  2> REPRODUCE WITH: mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch.qa.backwards:2.3 -Dtests.seed=C44DC1BBE1D7B14 -Dtests.class=org.elasticsearch.bwcompat.BasicAnalysisBackwardCompatibilityIT -Dtests.method="testAnalyzerTokensAfterUpgrade" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=ar-LB -Dtests.timezone=Asia/Tel_Aviv
FAILURE 38.4s J0 | BasicAnalysisBackwardCompatibilityIT.testAnalyzerTokensAfterUpgrade <<<
   > Throwable #1: java.lang.AssertionError: failed for term: 6𐒠𐒐 field: field_56 analyzer: type=string,analyzer=arabic input: \ud801\udca6\ud801\udca0\ud801\udc90 wlreih kkzk
   > Expected: "60\ud801\udc90"
   >      but: was "6\ud801\udca0\ud801\udc90"
   > 	at __randomizedtesting.SeedInfo.seed([C44DC1BBE1D7B14:28485A8F8B73F00]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.bwcompat.BasicAnalysisBackwardCompatibilityIT.testAnalyzerTokensAfterUpgrade(BasicAnalysisBackwardCompatibilityIT.java:100)
   > 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cbuescher** [comment]
The errors I looked at seem to center around `arabic` and `sonari`

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+2.4+periodic/2101/consoleFull
```
[2017-03-15 09:12:22,232][TRACE][action.search.type       ] [external_BasicBackwardsCompatibilityIT_0] Moving to second phase, based on results from: [hbNL7zVSQrype2-UHCTfdg][test][0],[hbNL7zVSQrype2-UHCTfdg][test][1],[um1IDY4NSzWjSZY0d1PphQ][test][2],[hbNL7zVSQrype2-UHCTfdg][test][3],[um1IDY4NSzWjSZY0d1PphQ][test][4],[um1IDY4NSzWjSZY0d1PphQ][test][5],[um1IDY4NSzWjSZY0d1PphQ][test][6],[um1IDY4NSzWjSZY0d1PphQ][test][7] (cluster state version: 15)
Suite: org.elasticsearch.bwcompat.BasicAnalysisBackwardCompatibilityIT
  2> REPRODUCE WITH: mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch.qa.backwards:2.2 -Dtests.seed=714E14C8016AD001 -Dtests.class=org.elasticsearch.bwcompat.BasicAnalysisBackwardCompatibilityIT -Dtests.method="testAnalyzerTokensAfterUpgrade" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=he -Dtests.timezone=Africa/Tunis
FAILURE 31.0s J0 | BasicAnalysisBackwardCompatibilityIT.testAnalyzerTokensAfterUpgrade <<<
   > Throwable #1: java.lang.AssertionError: failed for term: 7𐒣 field: field_2 analyzer: type=string,analyzer=arabic input: \ud801\udca7\ud801\udca3 rr eckvjzl \u05bf\uf559&\udb1b\ude76& \u18d2\u18ce\u18ff  swxia \u0320\u0354 KF(f wupwj xj
   > Expected: "73"
   >      but: was "7\ud801\udca3"
   > 	at __randomizedtesting.SeedInfo.seed([714E14C8016AD001:7F8E4D7B47C09415]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.bwcompat.BasicAnalysisBackwardCompatibilityIT.testAnalyzerTokensAfterUpgrade(BasicAnalysisBackwardCompatibilityIT.java:100)
   > 	at java.lang.Thread.run(Thread.java:745)
```

http://build-us-00.elastic.co/job/es_core_24_windows-2012-r2/2198/consoleFull
```
2> REPRODUCE WITH: mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch.qa.backwards:2.3 -Dtests.seed=B2252C4F39920047 -Dtests.class=org.elasticsearch.bwcompat.BasicAnalysisBackwardCompatibilityIT -Dtests.method="testAnalyzerTokensAfterUpgrade" -Des.logger.level=DEBUG -Dtests.nightly=false -Dtests.client.ratio=0.0 -Dtests.heap.size=512m -Des.node.mode=network -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:+UseCompressedOops -XX:+AggressiveOpts -Djava.net.preferIPv4Stack=true" -Dtests.locale=th -Dtests.timezone=Australia/West
FAILURE 32.4s | BasicAnalysisBackwardCompatibilityIT.testAnalyzerTokensAfterUpgrade <<<
   > Throwable #1: java.lang.AssertionError: failed for term: 3? field: field_224 analyzer: type=string,analyzer=sorani input: {1,5})j mqq pwMXNqtzrl yggb  \u2144\u211b\u2136\u2113 <scr \uf345\uf3aa\uf48c\ue82b\ue759\uf6d6 \ud801\udca3\ud801\udca2 pvjtFzw  ryrt kxzkwv \u512a ilppb i \uf494\ua555 \ud909\udd05\u02ad\uf0ff n
   > Expected: "32"
   >      but: was "3\ud801\udca2"
   > 	at __randomizedtesting.SeedInfo.seed([B2252C4F39920047:BCE575FC7F384453]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.bwcompat.BasicAnalysisBackwardCompatibilityIT.testAnalyzerTokensAfterUpgrade(BasicAnalysisBackwardCompatibilityIT.java:100)
   > 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tbrooks8** [comment]
It looks to me like this failed again today.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+2.4+periodic/2344/console

Suite: org.elasticsearch.bwcompat.BasicAnalysisBackwardCompatibilityIT
  2> REPRODUCE WITH: mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch.qa.backwards:2.3 -Dtests.seed=3891813BCB76E3F6 -Dtests.class=org.elasticsearch.bwcompat.BasicAnalysisBackwardCompatibilityIT -Dtests.method="testAnalyzerTokensAfterUpgrade" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=tr -Dtests.timezone=America/Nome
FAILURE 33.9s J0 | BasicAnalysisBackwardCompatibilityIT.testAnalyzerTokensAfterUpgrade <<<
   > Throwable #1: java.lang.AssertionError: failed for term: 6𐒣𐒍 field: field_106 analyzer: type=string,analyzer=sorani input: \u1a05J \uf609'\u05d4\uab44 \u0ea8h\u0629\u494d\u055d mzkulo thin \ud83c\udc59 vazvf \ud801\udca6\ud801\udca3\ud801\udc8d\ud801\udcab rygtt  \ua8e3\ua8ef\ua8e1\ua8ec ur ](ct bug
   > Expected: "63\ud801\udc8d"
   >      but: was "6\ud801\udca3\ud801\udc8d"
   > 	at __randomizedtesting.SeedInfo.seed([3891813BCB76E3F6:3651D8888DDCA7E2]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.bwcompat.BasicAnalysisBackwardCompatibilityIT.testAnalyzerTokensAfterUpgrade(BasicAnalysisBackwardCompatibilityIT.java:100)

**Comment by cbuescher** [comment]
Closing as a duplicate of #24345
