### ISSUE TITLE
Bucket Selector aggregation failing with nested and parent/child structures.

### ISSUE THREAD

**Issue by james08** [elastic/elasticsearch#23727]
**Elasticsearch version**:
Version: 5.2.2, Build: f9d9b74/2017-02-24T17:26:45.835Z, JVM: 1.8.0_121

**Plugins installed**: []
None.

**JVM version**:
JVM: 1.8.0_121

**OS version**:
Mac OS Sierra 10.12.3 

**Description of the problem including expected versus actual behavior**:
I'm using a bucket_selector (part of pipeline aggretions). Goal (expected behaviour): for a parent/child or nested relationship: buckets are on a parent field, aggregate over a child field, filter out buckets based on result of that aggregate. I've tested with data in a nested structure and data in a parent/child structure, I've included steps to reproduce both below.

**Steps to reproduce with nested structure**:
```

DELETE pipelinetest
 
PUT pipelinetest
{
   "mappings": {
      "team": {
         "properties": {
            "name": {
               "type": "keyword"
            },
            "description": {
               "type": "text"
            },
            "memberCount": {
               "type": "integer"
            },
            "developer": {
               "type": "nested",
               "properties": {
                  "gender": {
                     "type": "keyword"
                  },
                  "height": {
                     "type": "integer"
                  },
                  "name": {
                     "type": "text"
                  },
                  "laptop": {
                     "type": "nested",
                     "properties": {
                        "color": {
                           "type": "keyword"
                        },
                        "brand": {
                           "type": "keyword"
                        },
                        "hasTouchBar": {
                           "type": "keyword"
                        },
                        "age": {
                           "type": "integer"
                        }
                     }
                  }
               }
            }
         }
      }
   }
}

PUT pipelinetest/team/1
{
   "name": "Monoceros",
   "description": "Auckland Analytics",
   "memberCount": 4,
   "developer": [
      {
         "name": "James",
         "gender": "Male",
         "height": "185",
         "laptop": [
            {
               "color": "Gun Metal",
               "brand": "Apple",
               "hasTouchBar": "True",
               "age": "1"
            }
         ]
      },
      {
         "name": "John",
         "gender": "Male",
         "height": "184",
         "laptop": [
            {
               "color": "Silver",
               "brand": "Apple",
               "hasTouchBar": "False",
               "age": "2"
            }
         ]
      },
      {
         "name": "Kate",
         "gender": "Female",
         "height": "170",
         "laptop": [
            {
               "color": "Silver",
               "brand": "Apple",
               "hasTouchBar": "False",
               "age": "2"
            }
         ]
      },
      {
         "name": "Samuel",
         "gender": "Male",
         "height": "168",
         "laptop": [
            {
               "color": "Gun Metal",
               "brand": "Apple",
               "hasTouchBar": "True",
               "age": "1"
            },
            {
               "color": "Gun Metal",
               "brand": "Apple",
               "hasTouchBar": "True",
               "age": "1"
            }
         ]
      }
   ]
}


GET pipelinetest/team/_search
{
   "aggs": {
      "developers": {
         "nested": {
            "path": "developer.laptop"
         },
         "aggs": {
            "sum_age": {
               "sum": {
                  "field": "developer.laptop.age"
               }
            },
            "age_bucket_filter": {
               "bucket_selector": {
                  "buckets_path": {
                     "sumAge": "sum_age"
                  },
                  "script": "params.sumAge >= 7"
               }
            }
         }
      }
   },
   "size": 0
}
```

**Result**
```
{
   "error": {
      "root_cause": [],
      "type": "reduce_search_phase_exception",
      "reason": "[reduce] ",
      "phase": "fetch",
      "grouped": true,
      "failed_shards": [],
      "caused_by": {
         "type": "class_cast_exception",
         "reason": "org.elasticsearch.search.aggregations.bucket.nested.InternalNested cannot be cast to org.elasticsearch.search.aggregations.InternalMultiBucketAggregation"
      }
   },
   "status": 503
}
```

**Steps to reproduce with parent/child structure**:
```
DELETE pipelinetest
 
PUT pipelinetest
{
   "mappings": {
       "team": {
         "properties": {
            "teamName": {
               "type": "keyword"
            },
            "description": {
               "type": "text"
            },
            "memberCount": {
               "type": "integer"
            }
         }
      },
      "developer": {
          "_parent": {
            "type": "team"
         },
         "properties": {
            "gender": {
               "type": "keyword"
            },
            "height": {
               "type": "integer"
            },
            "name": {
               "type": "keyword"
            }
         }
      },
      "laptop": {
         "_parent": {
            "type": "developer"
         },
         "properties": {
            "color": {
               "type": "keyword"
            },
            "brand": {
               "type": "keyword"
            },
            "hasTouchBar": {
               "type": "keyword"
            },
            "age": {
               "type": "integer"
            }
         }
      }
   }
}

POST pipelinetest/team/_bulk
{"index":{"_id":"1", "routing":"1"}}
{"teamName":"Monoceros", "description": "Auckland Analytics", "memberCount":4}
{"index":{"_id":"2", "routing":"1"}}
{"teamName":"The Avengers", "description": "They have a hulk.", "memberCount":5}
 
POST pipelinetest/developer/_bulk
{"index":{"_id":"1", "parent":"1", "routing":"1"}}
{"name": "James", "gender":"M", "height":185}
{"index":{"_id":"2", "_parent":"1", "routing":"1"}}
{"name": "Kate","gender":"F","height":170}
{"index":{"_id":"3", "_parent":"1", "routing":"1"}}
{"name": "Samuel","gender":"M","height":168}
{"index":{"_id":"4", "_parent":"1", "routing":"1"}}
{"name": "John","gender":"M","height":184}
{"index":{"_id":"5", "parent":"2", "routing":"1"}}
{"name": "Iron Man", "gender":"M", "height":175}
{"index":{"_id":"6", "_parent":"2", "routing":"1"}}
{"name": "Hulk","gender":"M","height":230}
{"index":{"_id":"7", "_parent":"2", "routing":"1"}}
{"name": "Thor","gender":"M","height":192}
{"index":{"_id":"8", "_parent":"2", "routing":"1"}}
{"name": "Hawk","gender":"M","height":180}
{"index":{"_id":"9", "_parent":"2", "routing":"1"}}
{"name": "Black Widow","gender":"F","height":163}
 
POST pipelinetest/laptop/_bulk
{"index":{"_id":"1", "parent":"1", "routing":"1"}}
{"color": "gun metal", "hasTouchBar":"Y", "brand":"Apple","age":1}
{"index":{"_id":"2", "parent":"2", "routing":"1"}}
{"color": "silver", "hasTouchBar":"N", "brand":"Apple","age":2}
{"index":{"_id":"3", "parent":"3", "routing":"1"}}
{"color": "N/A", "hasTouchBar":"N/A", "brand":"N/A","age":0}
{"index":{"_id":"4", "parent":"3", "routing":"1"}}
{"color": "gun metal", "hasTouchBar":"Y", "brand":"Apple","age":1}
{"index":{"_id":"5", "parent":"4", "routing":"1"}}
{"color": "silver", "hasTouchBar":"N", "brand":"Apple","age":2}
{"index":{"_id":"6", "parent":"5", "routing":"1"}}
{"color": "gun metal", "hasTouchBar":"Y", "brand":"Apple","age":1}
{"index":{"_id":"7", "parent":"7", "routing":"1"}}
{"color": "silver", "hasTouchBar":"N", "brand":"Apple","age":2}
{"index":{"_id":"8", "parent":"6", "routing":"1"}}
{"color": "N/A", "hasTouchBar":"N/A", "brand":"N/A","age":0}
{"index":{"_id":"9", "parent":"8", "routing":"1"}}
{"color": "gun metal", "hasTouchBar":"Y", "brand":"Apple","age":1}
{"index":{"_id":"10", "parent":"9", "routing":"1"}}
{"color": "silver", "hasTouchBar":"N", "brand":"Apple","age":2}

GET pipelinetest/_search
{
   "size": 0,
   "aggs": {
      "by-team": {
         "terms": {
            "field": "teamName"
         },
         "aggs": {
            "developers": {
               "children": {
                  "type": "developer"
               },
               "aggs": {
                  "sum_height": {
                     "sum": {
                        "field": "height"
                     }
                  },
                  "sum_bucket_filter": {
                     "bucket_selector": {
                        "buckets_path": {
                           "sumHeight": "sum_height"
                        },
                        "script": "params.sumHeight >= 800"
                     }
                  }
               }
            }
         }
      }
   }
}
```

**Result**
```
{
   "error": {
      "root_cause": [],
      "type": "reduce_search_phase_exception",
      "reason": "[reduce] ",
      "phase": "fetch",
      "grouped": true,
      "failed_shards": [],
      "caused_by": {
         "type": "class_cast_exception",
         "reason": "org.elasticsearch.search.aggregations.bucket.children.InternalChildren cannot be cast to org.elasticsearch.search.aggregations.InternalMultiBucketAggregation"
      }
   },
   "status": 503
}

```

**Provide logs (if relevant)**:
Error on nested structure:
```
[2017-03-24T08:42:57,118][DEBUG][o.e.a.s.TransportSearchAction] [OqJZzsc] failed to reduce search
org.elasticsearch.action.search.ReduceSearchPhaseException: [reduce]
	at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction$2.onFailure(SearchQueryThenFetchAsyncAction.java:151) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:581) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-5.2.2.jar:5.2.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassCastException: org.elasticsearch.search.aggregations.bucket.nested.InternalNested cannot be cast to org.elasticsearch.search.aggregations.InternalMultiBucketAggregation
	at org.elasticsearch.search.aggregations.pipeline.bucketselector.BucketSelectorPipelineAggregator.reduce(BucketSelectorPipelineAggregator.java:85) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:136) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:158) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.action.search.SearchPhaseController.merge(SearchPhaseController.java:489) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction$2.doRun(SearchQueryThenFetchAsyncAction.java:140) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.2.2.jar:5.2.2]
	... 3 more
```

Error on parent/child structure:
```
[2017-03-24T08:43:54,134][DEBUG][o.e.a.s.TransportSearchAction] [OqJZzsc] failed to reduce search
org.elasticsearch.action.search.ReduceSearchPhaseException: [reduce]
	at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction$2.onFailure(SearchQueryThenFetchAsyncAction.java:151) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:581) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-5.2.2.jar:5.2.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassCastException: org.elasticsearch.search.aggregations.bucket.children.InternalChildren cannot be cast to org.elasticsearch.search.aggregations.InternalMultiBucketAggregation
	at org.elasticsearch.search.aggregations.pipeline.bucketselector.BucketSelectorPipelineAggregator.reduce(BucketSelectorPipelineAggregator.java:85) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:136) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:158) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.search.aggregations.bucket.terms.InternalTerms$Bucket.reduce(InternalTerms.java:135) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.search.aggregations.bucket.terms.InternalTerms.doReduce(InternalTerms.java:234) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:134) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:158) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.action.search.SearchPhaseController.merge(SearchPhaseController.java:489) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction$2.doRun(SearchQueryThenFetchAsyncAction.java:140) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.2.2.jar:5.2.2]
	... 3 more
```

**Comment by clintongormley** [comment]
the `bucket_selector` script is for selecting buckets.  In your first example, you have no bucket aggregation to produce buckets, so you have nowhere to use the `bucket_selector` agg.

In your second example, you're applying the `bucket_selector` agg to the wrong level.  Try this instead:

```
GET pipelinetest/_search
{
  "size": 0,
  "aggs": {
    "by-team": {
      "terms": {
        "field": "teamName"
      },
      "aggs": {
        "developers": {
          "children": {
            "type": "developer"
          },
          "aggs": {
            "sum_height": {
              "sum": {
                "field": "height"
              }
            }
          }
        },
        "sum_bucket_filter": {
          "bucket_selector": {
            "buckets_path": {
              "sumHeight": "developers>sum_height"
            },
            "script": "params.sumHeight >= 800"
          }
        }
      }
    }
  }
}
```

**Comment by james08** [comment]
Thanks Clinton. I'm hoping a similar pattern will work with the nested structure. I'll give it a try.
