### ISSUE TITLE
Test Failure: UnicastZenPingTests. testInvalidHosts

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#23738]
Failed for the first time https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+nfs/125/console

```
REPRODUCE WITH: gradle :core:test -Dtests.seed=FB4F26491CE0555A -Dtests.class=org.elasticsearch.discovery.zen.UnicastZenPingTests -Dtests.method="testInvalidHosts" -Dtests.security.manager=true -Dtests.locale=de-LU -Dtests.timezone=Asia/Sakhalin
  1> [2017-03-24T21:05:42,135][INFO ][o.e.d.z.UnicastZenPingTests] [testInvalidHosts]: after test
FAILURE 2.68s J2 | UnicastZenPingTests.testInvalidHosts <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: a collection with size <1>
   >      but: collection size was <0>
   > 	at __randomizedtesting.SeedInfo.seed([FB4F26491CE0555A:EA7ACEBC73BE77AE]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.discovery.zen.UnicastZenPingTests.testInvalidHosts(UnicastZenPingTests.java:799)
   > 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jasontedor** [comment]
This test has failed once since, in May, and there have been changes in this area. If this test fails again, we can open a new issue.
