### ISSUE TITLE
Restart on yum upgrade fails.

### ISSUE THREAD

**Issue by Gacko** [elastic/elasticsearch#23785]
**Elasticsearch version**: 5.2.2 -> 5.3.0, maybe 5.2.1 -> 5.2.2 also.

**Plugins installed**: None but the default ones.

**JVM version**:
```
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**OS version**: Not relevant. Well, any Linux distribution using `yum`.

**Description of the problem including expected versus actual behavior**:
Having `RESTART_ON_UPGRADE` enabled in `/etc/sysconfig/elasticsearch` automatically stops Elasticsearch on `yum upgrade` but it fails to start again due to an exception. See logs below.

**Steps to reproduce**:
 1. Run Elasticsearch 5.2.2 (5.2.1 and 5.2.0 may be affected, too).
 2. Run `yum upgrade`
 3. See Elasticsearch gets stopped.
 4. Recognize it's not coming up again ;)

**Provide logs (if relevant)**:
```
[2017-03-29T09:20:42,135][INFO ][o.e.n.Node               ] [my-node-name-here] stopping ...
[2017-03-29T09:20:42,162][INFO ][o.e.n.Node               ] [my-node-name-here] stopped
[2017-03-29T09:20:42,162][INFO ][o.e.n.Node               ] [my-node-name-here] closing ...
[2017-03-29T09:20:42,486][INFO ][o.e.n.Node               ] [my-node-name-here] closed
[2017-03-29T09:20:45,893][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.IllegalStateException: /usr/share/elasticsearch/lib/elasticsearch-5.2.2.jar requires Elasticsearch 5.2.2, your system: 5.3.0
	at org.elasticsearch.bootstrap.JarHell.checkManifest(JarHell.java:225) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:178) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:88) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:230) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cli.Command.main(Command.java:88) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) [elasticsearch-5.3.0.jar:5.3.0]
[2017-03-29T09:20:45,902][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [my-node-name-here] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: /usr/share/elasticsearch/lib/elasticsearch-5.2.2.jar requires Elasticsearch 5.2.2, your system: 5.3.0
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.0.jar:5.3.0]
Caused by: java.lang.IllegalStateException: /usr/share/elasticsearch/lib/elasticsearch-5.2.2.jar requires Elasticsearch 5.2.2, your system: 5.3.0
	at org.elasticsearch.bootstrap.JarHell.checkManifest(JarHell.java:225) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:178) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:88) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:230) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.0.jar:5.3.0]
	... 6 more
```

**Comment by rjernst** [comment]
Can you please do an `ls` in `/usr/share/elasticsearch/lib/` and past the output here? It seems like the upgrade did not remove all previously installed files.

**Comment by Gacko** [comment]
It does remove the old library and installs the new one but attemps to load the old, removed one.

**Comment by jasontedor** [comment]
> It does remove the old library and installs the new one but attemps to load the old, removed one.

It's not trying to load an old one, it's checking the manifest of the jar that is actually executing and the manifest of that jar says it's an old version.

**Comment by jasontedor** [comment]
Can you please send us this jar?

**Comment by Gacko** [comment]
Just to clarify... `yum upgrade` removes files related to the old RPM or no longer included in the new RPM, installs news files from the new RPM and restarts Elasticsearch using systemd, right?

Is it possible the old JAR is still there when the `postinst` script is called and removed afterwards? Because the old JAR is missing after a simple `yum upgrade` without a `RESTART_ON_UPGRADE` triggered restart and `systemctl restart elasticsearch` works fine, too.

I'm not having a yum-based box around right now but I'm having a apt-based one running Elasticsearch 5.2.2. I'll backup the `/usr/share/elasticsearch` directory before upgrading and try upgrading later.

**Comment by Gacko** [comment]
Okay. Upgrade works using `apt`. Got to kickstart a virtual box with a `yum`-based distro...

**Comment by jasontedor** [comment]
> Just to clarify... yum upgrade removes files related to the old RPM or no longer included in the new RPM, installs news files from the new RPM and restarts Elasticsearch using SystemD in the postinst script, right?

There are complicated rules around what is preserved regarding config files, but the nut of the situation is other than data, logs, and config, all files are removed from the old installation. After installation, you are correct that a restart is performed with systemd or Sys V init.

> Is it possible the old JAR is still there when the postinst script is called and removed afterwards?

No, the symptoms here are of a completely garbage jar, a jar whose manifest indicates it was built for 5.2.2, but whose code indicates it was built for 5.3.0. This does not match the content of the jars that was distributed with either 5.2.2 or 5.3.0. That's why I asked for the jar, something is incredibly wrong here, and I'm unconvinced our build system produced this jar.

Also, to be clear, we have packaging tests that test upgrading from the RPM against all previously released versions in the 5.x series.

**Comment by Gacko** [comment]
I added the Elasticsearch YUM repository as described here https://www.elastic.co/guide/en/elasticsearch/reference/current/rpm.html, installed Elasticsearch using `yum install elasticsearch` (was version 5.2.2 at the time I did so), configured it to restart on upgrade and let it run for some time. The next time I did a `yum upgrade` it got updated to 5.3.0 and failed to restart.

Unfortunately I do not have a backup of the installed version 5.2.2 nor do I have access to the server at the moment. The only thing I can do is kickstarting a whole new CentOS 7 box and try to reproduce the exception.

**Comment by jasontedor** [comment]
> The only thing I can do is kickstarting a whole new CentOS 7 box and trying to reproduce the exception.

I understand that it will take you time to do this. Yet, without a reliable reproduction or at least the inciminating jar there isn't much we can do here since it does not reproduce. If you do have the time do this, it will be appreciated. Otherwise, we will have to close this as can not reproduce.

**Comment by Gacko** [comment]
I could not reproduce this using a fresh CentOS 7 installation. I'll backup my Elasticsearch installation the next time I do an upgrade from the official Elasticsearch repo using the production system which is running on Oracle Linux.

**Comment by jasontedor** [comment]
Okay, thanks for reporting back, it's appreciated. If this happens again indeed a snapshot of the system in the before state will be helpful but even a copy of the jar in the after state will help tremendously. Cheers!

**Comment by Gacko** [comment]
I just upgraded from 5.3.0 to 5.3.1. Different JAR, same behavior:

```
root@hostname:~# cp -r /usr/share/elasticsearch elasticsearch-5.3.0
root@hostname:~# yum --version
3.4.3
  Installed: rpm-4.11.3-21.el7.x86_64 at 2017-03-13 13:35
  Built    : None at 2016-09-02 22:09
  Committed: Florian Festi <ffesti@redhat.com> at 2016-07-26

  Installed: yum-3.4.3-150.0.1.el7.noarch at 2017-03-13 13:35
  Built    : None at 2016-11-04 05:59
  Committed: EL Errata <el-errata_ww@oracle.com> at 2016-11-03

  Installed: yum-rhn-plugin-2.6.3-1.el7.noarch at 2017-03-03 14:43
  Built    : Koji at 2016-11-10 10:44
  Committed: Gennadii Altukhov <galt@redhat.com> at 2016-11-09
root@hostname:~# yum upgrade elasticsearch
Loaded plugins: langpacks, rhnplugin
This system is receiving updates from RHN Classic or Red Hat Satellite.
elasticsearch-5.x                                                                                                                                                                                                                                        | 1.3 kB  00:00:00     
[...]                                                                                                                                                                                                                                 | 1.0 kB  00:00:00     
Resolving Dependencies
--> Running transaction check
---> Package elasticsearch.noarch 0:5.3.0-1 will be updated
---> Package elasticsearch.noarch 0:5.3.1-1 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================================================================================================================================================================================================================
 Package                                                             Arch                                                         Version                                                         Repository                                                               Size
================================================================================================================================================================================================================================================================================
Updating:
 elasticsearch                                                       noarch                                                       5.3.1-1                                                         elasticsearch-5.x                                                        32 M

Transaction Summary
================================================================================================================================================================================================================================================================================
Upgrade  1 Package

Total download size: 32 M
Is this ok [y/d/N]: y
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
elasticsearch-5.3.1.rpm                                                                                                                                                                                                                                  |  32 MB  00:00:02     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : elasticsearch-5.3.1-1.noarch                                                                                                                                                                                                                                 1/2 
Restarting elasticsearch service... OK
  Cleanup    : elasticsearch-5.3.0-1.noarch                                                                                                                                                                                                                                 2/2 
  Verifying  : elasticsearch-5.3.1-1.noarch                                                                                                                                                                                                                                 1/2 
  Verifying  : elasticsearch-5.3.0-1.noarch                                                                                                                                                                                                                                 2/2 

Updated:
  elasticsearch.noarch 0:5.3.1-1                                                                                                                                                                                                                                                

Complete!
root@hostname:~# tail -n 50 /var/log/elasticsearch/cluster-name.log 
[2017-04-25T07:56:55,898][INFO ][o.e.n.Node               ] [node-name] stopping ...
[2017-04-25T07:56:55,929][INFO ][o.e.n.Node               ] [node-name] stopped
[2017-04-25T07:56:55,930][INFO ][o.e.n.Node               ] [node-name] closing ...
[2017-04-25T07:56:55,943][INFO ][o.e.n.Node               ] [node-name] closed
[2017-04-25T07:57:01,521][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-name] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: org.elasticsearch.bootstrap.BootstrapException: java.io.FileNotFoundException: /usr/share/elasticsearch/lib/lucene-sandbox-6.4.1.jar (No such file or directory)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.1.jar:5.3.1]
Caused by: org.elasticsearch.bootstrap.BootstrapException: java.io.FileNotFoundException: /usr/share/elasticsearch/lib/lucene-sandbox-6.4.1.jar (No such file or directory)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.1.jar:5.3.1]
	... 6 more
Caused by: java.io.FileNotFoundException: /usr/share/elasticsearch/lib/lucene-sandbox-6.4.1.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_121]
	at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_121]
	at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_121]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_121]
	at java.util.jar.JarFile.<init>(JarFile.java:103) ~[?:1.8.0_121]
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:175) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:88) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:230) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.1.jar:5.3.1]
	... 6 more
root@hostname:~# systemctl start elasticsearch
root@hostname:~# tail -n 50 /var/log/elasticsearch/cluster-name.log 
[2017-04-25T07:56:55,898][INFO ][o.e.n.Node               ] [node-name] stopping ...
[2017-04-25T07:56:55,929][INFO ][o.e.n.Node               ] [node-name] stopped
[2017-04-25T07:56:55,930][INFO ][o.e.n.Node               ] [node-name] closing ...
[2017-04-25T07:56:55,943][INFO ][o.e.n.Node               ] [node-name] closed
[2017-04-25T07:57:01,521][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-name] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: org.elasticsearch.bootstrap.BootstrapException: java.io.FileNotFoundException: /usr/share/elasticsearch/lib/lucene-sandbox-6.4.1.jar (No such file or directory)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.1.jar:5.3.1]
Caused by: org.elasticsearch.bootstrap.BootstrapException: java.io.FileNotFoundException: /usr/share/elasticsearch/lib/lucene-sandbox-6.4.1.jar (No such file or directory)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.1.jar:5.3.1]
	... 6 more
Caused by: java.io.FileNotFoundException: /usr/share/elasticsearch/lib/lucene-sandbox-6.4.1.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_121]
	at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_121]
	at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_121]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_121]
	at java.util.jar.JarFile.<init>(JarFile.java:103) ~[?:1.8.0_121]
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:175) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:88) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:230) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.1.jar:5.3.1]
	... 6 more
[2017-04-25T08:00:04,258][INFO ][o.e.n.Node               ] [node-name] initializing ...
[2017-04-25T08:00:04,424][INFO ][o.e.e.NodeEnvironment    ] [node-name] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [5.9gb], net total_space [14.6gb], spins? [unknown], types [rootfs]
[2017-04-25T08:00:04,425][INFO ][o.e.e.NodeEnvironment    ] [node-name] heap size [7.9gb], compressed ordinary object pointers [true]
[2017-04-25T08:00:04,456][INFO ][o.e.n.Node               ] [node-name] node name [node-name], node ID [Wch9nH_-SEGeTWDw2_84bQ]
[2017-04-25T08:00:04,456][INFO ][o.e.n.Node               ] [node-name] version[5.3.1], pid[3521], build[5f9cf58/2017-04-17T15:52:53.846Z], OS[Linux/3.10.0-514.10.2.el7.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_121/25.121-b13]
[2017-04-25T08:00:05,388][INFO ][o.e.p.PluginsService     ] [node-name] loaded module [aggs-matrix-stats]
[2017-04-25T08:00:05,388][INFO ][o.e.p.PluginsService     ] [node-name] loaded module [ingest-common]
[2017-04-25T08:00:05,388][INFO ][o.e.p.PluginsService     ] [node-name] loaded module [lang-expression]
[2017-04-25T08:00:05,388][INFO ][o.e.p.PluginsService     ] [node-name] loaded module [lang-groovy]
[2017-04-25T08:00:05,388][INFO ][o.e.p.PluginsService     ] [node-name] loaded module [lang-mustache]
[2017-04-25T08:00:05,388][INFO ][o.e.p.PluginsService     ] [node-name] loaded module [lang-painless]
[2017-04-25T08:00:05,388][INFO ][o.e.p.PluginsService     ] [node-name] loaded module [percolator]
[2017-04-25T08:00:05,388][INFO ][o.e.p.PluginsService     ] [node-name] loaded module [reindex]
[2017-04-25T08:00:05,388][INFO ][o.e.p.PluginsService     ] [node-name] loaded module [transport-netty3]
[2017-04-25T08:00:05,389][INFO ][o.e.p.PluginsService     ] [node-name] loaded module [transport-netty4]
[2017-04-25T08:00:05,389][INFO ][o.e.p.PluginsService     ] [node-name] no plugins loaded
[2017-04-25T08:00:08,347][INFO ][o.e.n.Node               ] [node-name] initialized
[2017-04-25T08:00:08,347][INFO ][o.e.n.Node               ] [node-name] starting ...
[2017-04-25T08:00:08,578][INFO ][o.e.t.TransportService   ] [node-name] publish_address {bind-ip:9300}, bound_addresses {bind-ip:9300}
[2017-04-25T08:00:08,586][INFO ][o.e.b.BootstrapChecks    ] [node-name] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2017-04-25T08:00:11,641][INFO ][o.e.c.s.ClusterService   ] [node-name] new_master {node-name}{Wch9nH_-SEGeTWDw2_84bQ}{-SC0zaNPSnK1L0-OZvJT3g}{bind-ip}{bind-ip:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-04-25T08:00:11,663][INFO ][o.e.h.n.Netty4HttpServerTransport] [node-name] publish_address {bind-ip:9200}, bound_addresses {bind-ip:9200}
[2017-04-25T08:00:11,667][INFO ][o.e.n.Node               ] [node-name] started
```

Where do you want me to put the 5.3.0 backup?

**Comment by jasontedor** [comment]
@Gacko This is different than the problem that you reported before yet seemingly similar.

There's something very puzzling about your system, I do think this is ultimately specific to your environment and not a problem with the packaging (and again, this doesn't reproduce for me where I just tried on Oracle 7, and it doesn't reproduce in our packaging tests which we test across a variety of OS (e.g., CentOS 6, CentOS 7, RHEL 6, RHEL 7, Oracle 6, Oracle 7, Fedora 24, etc.)).

Here's why I think this. The logs indicate that the node is failing unable to find `/usr/share/elasticsearch/lib/lucene-sandbox-6.4.1.jar` during the part of the jar hell check where we check the jars on the classpath. The jars on the classpath are set by the startup scripts where we specify it as `/usr/share/elasticsearch/lib/elasticsearch-5.3.1.jar:/usr/share/elasticsearch/lib/*`. This will be glob expanded by the shell before Elasticsearch starts and so ultimately Elasticsearch will see the contents of the lib folder as the shell saw them before Elasticsearch started.

This means that the running Elasticsearch instance thinks that `/usr/share/elasticsearch/lib/lucene-sandbox-6.4.1.jar` is on the classpath, yet that file can not be found. It's as if the moment before starting Elasticsearch, the filesystem told the shell that `/usr/share/elasticsearch/lib/lucene-sandbox-6.4.1.jar` was there, and then after starting Elasticsearch it was not (it's important to note that 5.3.0 depends on Lucene 6.4.1, and 5.3.1 depends on Lucene 6.4.2, but important to note that we do not specify these dependencies explicitly on the classpath, we simply rely on the shell's glob expansion).

> Where do you want me to put the 5.3.0 backup?

Based on the above analysis, I don't think examining this is going to shed any light on this at all. I think you need to think about things that are specific to your environment. Sorry, it's likely we will close this one as unable to reproduce.

**Comment by Gacko** [comment]
Ok, thank you very much. I'll keep this in mind the next time I update and disable RESTART_ON_UPGRADE. The problem itself won't a big deal to me in the future since we're going to move over to Docker soon and I just wanted to make sure this is not related to Elasticsearch.

**Comment by jasontedor** [comment]
> I just wanted to make sure this is not related to Elasticsearch.

Indeed, I appreciate the additional information you provided today. I feel very confident in saying that this is not an Elasticsearch issue.

**Comment by sbruno** [comment]
I just came across this same problem when doing an upgrade from elasticsearch 7.10.0 to 7.10.2.

What I do to reproduce it is starting a Centos 7 virtual machine and run:
```
rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

cat > /etc/yum.repos.d/elasticsearch.repo << EOF
[elasticsearch]
name=Elasticsearch repository for 7.x packages
baseurl=https://artifacts.elastic.co/packages/7.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=0
autorefresh=1
type=rpm-md
EOF

yum install -y --enablerepo=elasticsearch elasticsearch-7.10.0-1

systemctl daemon-reload
systemctl enable elasticsearch.service
systemctl start elasticsearch.service

sed -i 's/#RESTART_ON_UPGRADE=true/RESTART_ON_UPGRADE=true/' /etc/sysconfig/elasticsearch

yum install -y --enablerepo=elasticsearch elasticsearch-7.10.2-1
```


I tried to debug the problem so I created RPM packages where I added `find /usr/share/elasticsearch/lib`  commands in the `post`, `prerm` and `postrm` scripts

Turns out that `post` of the new package is executed before the old package is removed and actually `find` command shows that jar files for both packages exist at the same time. Sounds weird but that's what I see. And the service is restarted in the `post`.

In fact I then tried doing upgrades on other versions and got different errors, but all of them seem to be related with having both packages installed at the same time.
When upgrading form 7.11.0 to 7.12.0 I get:
```
2021-04-16T18:53:58,634][WARN ][stderr                   ] [host3] Exception in thread "main" java.lang.AssertionError: Lucene version mismatch this version of Elasticsearch requires lucene version [8.7.0]  but the current lucene version is [8.8.0]
[2021-04-16T18:53:58,636][WARN ][stderr                   ] [host3]     at org.elasticsearch.bootstrap.Bootstrap.checkLucene(Bootstrap.java:460)
[2021-04-16T18:53:58,636][WARN ][stderr                   ] [host3]     at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:380)
[2021-04-16T18:53:58,636][WARN ][stderr                   ] [host3]     at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
[2021-04-16T18:53:58,636][WARN ][stderr                   ] [host3]     at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
[2021-04-16T18:53:58,637][WARN ][stderr                   ] [host3]     at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
[2021-04-16T18:53:58,637][WARN ][stderr                   ] [host3]     at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
[2021-04-16T18:53:58,637][WARN ][stderr                   ] [host3]     at org.elasticsearch.cli.Command.main(Command.java:79)
[2021-04-16T18:53:58,637][WARN ][stderr                   ] [host3]     at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115)
[2021-04-16T18:53:58,637][WARN ][stderr                   ] [host3]     at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81)
```

On another upgrade combination I got:
```
Apr 16 16:31:50 host8 systemd-entrypoint[4179]: Exception in thread "main" java.lang.IllegalArgumentException: expected one argument specifying path to ES_PATH_CONF but was [/etc/elasticsearch, /usr/share/elasticsearch/plugins]
Apr 16 16:31:50 host8 systemd-entrypoint[4179]: 	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:82)
```

I tried moving the restart code from `post` to `posttrans`, which executes after the old package is removed, and it worked but I think that that way it is not possible to conditionally run it on upgrades but not in clean installations since `$1` will always be `0`. That is my understanding of it.
