### ISSUE TITLE
s3 repository with AWS instance profile not working

### ISSUE THREAD

**Issue by r0c** [elastic/elasticsearch#23780]
**Elasticsearch version**: 5.2

**Plugins installed**: [repository-s3]

**JVM version**: 
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode

**OS version**: CentOS Linux release 7.3.1611 (Core)

**Description of the problem including expected versus actual behavior**: 
I am using repository-s3 with aws instance profile,  but got Access Denied error with http code 500.

Here are the command and output:
```
[root@ip-10-99-3-140 bin]# curl -XPUT '10.99.3.140:9200/_snapshot/my_s3_repository_3?pretty' -H 'Content-Type: application/json' -d'
{
  "type": "s3",
  "settings": {
    "bucket": "elasticsearchbucket-14lu5ab5ncv3a",
    "region": "us-west-2"
  }
}'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "repository_verification_exception",
        "reason" : "[my_s3_repository_3] path  is not accessible on master node"
      }
    ],
    "type" : "repository_verification_exception",
    "reason" : "[my_s3_repository_3] path  is not accessible on master node",
    "caused_by" : {
      "type" : "i_o_exception",
      "reason" : "Unable to upload object tests-NxZaN5PAQOOZH7c528Krrg/master.dat-temp",
      "caused_by" : {
        "type" : "amazon_s3_exception",
        "reason" : "Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 99B74F2EF8BBBD0C)"
      }
    }
  },
  "status" : 500
}
```

The ec2 instance has the iam role and policies for accessing this bucket:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::elasticsearchbucket-14lu5ab5ncv3a/*",
                "arn:aws:s3:::elasticsearchbucket-14lu5ab5ncv3a"
            ],
            "Effect": "Allow"
        }
    ]
}
```

I want to know how to get it working. 
**Provide logs (if relevant)**:
```
[2017-03-28T20:52:11,513][WARN ][r.suppressed             ] path: /_snapshot/my_s3_repository_3, params: {pretty=, repository=my_s3_repository_3}
org.elasticsearch.repositories.RepositoryVerificationException: [my_s3_repository_3] path  is not accessible on master node
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:734) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.repositories.RepositoriesService.verifyRepository(RepositoriesService.java:210) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.repositories.RepositoriesService$VerifyingRegisterRepositoryListener.onResponse(RepositoriesService.java:413) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.repositories.RepositoriesService$VerifyingRegisterRepositoryListener.onResponse(RepositoriesService.java:398) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.cluster.AckedClusterStateUpdateTask.onAllNodesAcked(AckedClusterStateUpdateTask.java:64) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.cluster.service.ClusterService$SafeAckedClusterStateTaskListener.onAllNodesAcked(ClusterService.java:1047) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.cluster.service.ClusterService$AckCountDownListener.onNodeAck(ClusterService.java:1305) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.cluster.service.ClusterService$DelegetingAckListener.onNodeAck(ClusterService.java:1245) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.cluster.service.ClusterService.publishAndApplyChanges(ClusterService.java:828) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:628) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.cluster.service.ClusterService$UpdateTask.run(ClusterService.java:1112) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:527) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:238) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:201) [elasticsearch-5.2.0.jar:5.2.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.io.IOException: Unable to upload object tests-NxZaN5PAQOOZH7c528Krrg/master.dat-temp
        at org.elasticsearch.cloud.aws.blobstore.DefaultS3OutputStream.upload(DefaultS3OutputStream.java:119) ~[?:?]
        at org.elasticsearch.cloud.aws.blobstore.DefaultS3OutputStream.flush(DefaultS3OutputStream.java:99) ~[?:?]
        at org.elasticsearch.cloud.aws.blobstore.S3OutputStream.flushBuffer(S3OutputStream.java:71) ~[?:?]
        at org.elasticsearch.cloud.aws.blobstore.S3OutputStream.close(S3OutputStream.java:89) ~[?:?]
        at org.apache.lucene.util.IOUtils.close(IOUtils.java:89) ~[lucene-core-6.4.0.jar:6.4.0 bbe4b08cc1fb673d0c3eb4b8455f23ddc1364124 - jim - 2017-01-17 15:57:29]
        at org.apache.lucene.util.IOUtils.close(IOUtils.java:76) ~[lucene-core-6.4.0.jar:6.4.0 bbe4b08cc1fb673d0c3eb4b8455f23ddc1364124 - jim - 2017-01-17 15:57:29]
        at org.elasticsearch.common.io.Streams.copy(Streams.java:85) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.common.io.Streams.copy(Streams.java:57) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.cloud.aws.blobstore.S3BlobContainer.writeBlob(S3BlobContainer.java:108) ~[?:?]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:727) ~[elasticsearch-5.2.0.jar:5.2.0]
        ... 16 more
        Suppressed: java.io.IOException: Unable to upload object tests-NxZaN5PAQOOZH7c528Krrg/master.dat-temp
                at org.elasticsearch.cloud.aws.blobstore.DefaultS3OutputStream.upload(DefaultS3OutputStream.java:119) ~[?:?]
                at org.elasticsearch.cloud.aws.blobstore.DefaultS3OutputStream.flush(DefaultS3OutputStream.java:99) ~[?:?]
                at org.elasticsearch.cloud.aws.blobstore.S3OutputStream.flushBuffer(S3OutputStream.java:71) ~[?:?]
                at org.elasticsearch.cloud.aws.blobstore.S3OutputStream.close(S3OutputStream.java:89) ~[?:?]
                at org.elasticsearch.cloud.aws.blobstore.S3BlobContainer.writeBlob(S3BlobContainer.java:109) ~[?:?]
                at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:727) ~[elasticsearch-5.2.0.jar:5.2.0]
                at org.elasticsearch.repositories.RepositoriesService.verifyRepository(RepositoriesService.java:210) [elasticsearch-5.2.0.jar:5.2.0]
                at org.elasticsearch.repositories.RepositoriesService$VerifyingRegisterRepositoryListener.onResponse(RepositoriesService.java:413) [elasticsearch-5.2.0.jar:5.2.0]
                at org.elasticsearch.repositories.RepositoriesService$VerifyingRegisterRepositoryListener.onResponse(RepositoriesService.java:398) [elasticsearch-5.2.0.jar:5.2.0]
                at org.elasticsearch.cluster.AckedClusterStateUpdateTask.onAllNodesAcked(AckedClusterStateUpdateTask.java:64) [elasticsearch-5.2.0.jar:5.2.0]
                at org.elasticsearch.cluster.service.ClusterService$SafeAckedClusterStateTaskListener.onAllNodesAcked(ClusterService.java:1047) [elasticsearch-5.2.0.jar:5.2.0]
                at org.elasticsearch.cluster.service.ClusterService$AckCountDownListener.onNodeAck(ClusterService.java:1305) [elasticsearch-5.2.0.jar:5.2.0]
                at org.elasticsearch.cluster.service.ClusterService$DelegetingAckListener.onNodeAck(ClusterService.java:1245) [elasticsearch-5.2.0.jar:5.2.0]
                at org.elasticsearch.cluster.service.ClusterService.publishAndApplyChanges(ClusterService.java:828) [elasticsearch-5.2.0.jar:5.2.0]
                at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:628) [elasticsearch-5.2.0.jar:5.2.0]
                at org.elasticsearch.cluster.service.ClusterService$UpdateTask.run(ClusterService.java:1112) [elasticsearch-5.2.0.jar:5.2.0]
                at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:527) [elasticsearch-5.2.0.jar:5.2.0]
                at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:238) [elasticsearch-5.2.0.jar:5.2.0]
                at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:201) [elasticsearch-5.2.0.jar:5.2.0]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
                at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
        Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 4A6546566DF33ED9)
                at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1389) ~[?:?]
                at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:902) ~[?:?]
                at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607) ~[?:?]
                at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376) ~[?:?]
                at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338) ~[?:?]
                at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287) ~[?:?]
                at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3654) ~[?:?]
                at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1354) ~[?:?]
                at org.elasticsearch.cloud.aws.blobstore.DefaultS3OutputStream.doUpload(DefaultS3OutputStream.java:149) ~[?:?]
                at org.elasticsearch.cloud.aws.blobstore.DefaultS3OutputStream.upload(DefaultS3OutputStream.java:112) ~[?:?]
                ... 21 more
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 99B74F2EF8BBBD0C)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1389) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:902) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3654) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1354) ~[?:?]
        at org.elasticsearch.cloud.aws.blobstore.DefaultS3OutputStream.doUpload(DefaultS3OutputStream.java:149) ~[?:?]
        at org.elasticsearch.cloud.aws.blobstore.DefaultS3OutputStream.upload(DefaultS3OutputStream.java:112) ~[?:?]
        at org.elasticsearch.cloud.aws.blobstore.DefaultS3OutputStream.flush(DefaultS3OutputStream.java:99) ~[?:?]
        at org.elasticsearch.cloud.aws.blobstore.S3OutputStream.flushBuffer(S3OutputStream.java:71) ~[?:?]
        at org.elasticsearch.cloud.aws.blobstore.S3OutputStream.close(S3OutputStream.java:89) ~[?:?]
        at org.apache.lucene.util.IOUtils.close(IOUtils.java:89) ~[lucene-core-6.4.0.jar:6.4.0 bbe4b08cc1fb673d0c3eb4b8455f23ddc1364124 - jim - 2017-01-17 15:57:29]
        at org.apache.lucene.util.IOUtils.close(IOUtils.java:76) ~[lucene-core-6.4.0.jar:6.4.0 bbe4b08cc1fb673d0c3eb4b8455f23ddc1364124 - jim - 2017-01-17 15:57:29]
        at org.elasticsearch.common.io.Streams.copy(Streams.java:85) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.common.io.Streams.copy(Streams.java:57) ~[elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.cloud.aws.blobstore.S3BlobContainer.writeBlob(S3BlobContainer.java:108) ~[?:?]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:727) ~[elasticsearch-5.2.0.jar:5.2.0]
        ... 16 more

```

**Describe the feature**:

**Comment by abeyad** [comment]
Kindly ask any questions on the https://discuss.elastic.co forum we provide.  We reserve Github for bugs and feature requests.  Thank you.
