### ISSUE TITLE
MultiClusterSearchYamlTestSuiteIT{p0=/10_basic/Index data and search on the old cluster} fails

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#23790]
* Link to failed build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=fedora/757/console
* Reproduction line: `gradle :qa:multi-cluster-search:remoteClusterTestRunner -Dtests.seed=2C5B47B8A3E32364 -Dtests.class=org.elasticsearch.upgrades.MultiClusterSearchYamlTestSuiteIT -Dtests.method="test {p0=/10_basic/Index data and search on the old cluster}" -Dtests.security.manager=true -Dtests.locale=hu-HU -Dtests.timezone=Africa/Lagos -Dtests.rest.suite=remote_cluster`
* Does not reproduce locally; failed only once more two days ago in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/2228/console (I checked all failures in the last year).

Failure output:

```
Suite: org.elasticsearch.upgrades.MultiClusterSearchYamlTestSuiteIT
  1> [2017-03-28T21:41:23,829][INFO ][o.e.u.MultiClusterSearchYamlTestSuiteIT] [test {p0=/10_basic/Index data and search on the old cluster}]: before test
  1> [2017-03-28T21:41:23,846][INFO ][o.e.u.MultiClusterSearchYamlTestSuiteIT] initializing REST clients against [http://[::1]:43685, http://[::1]:41113]
  1> [2017-03-28T21:41:24,392][INFO ][o.e.u.MultiClusterSearchYamlTestSuiteIT] initializing yaml client, minimum es version: [6.0.0-alpha1] master version: [6.0.0-alpha1] hosts: [http://[::1]:43685, http://[::1]:41113]
  1> [2017-03-28T21:41:25,641][INFO ][o.e.u.MultiClusterSearchYamlTestSuiteIT] [test {p0=/10_basic/Index data and search on the old cluster}]: after test
  1> [2017-03-28T21:41:25,660][INFO ][o.e.u.MultiClusterSearchYamlTestSuiteIT] Stash dump on failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "took" : 134,
  1>       "timed_out" : false,
  1>       "_shards" : {
  1>         "total" : 3,
  1>         "successful" : 3,
  1>         "failed" : 0
  1>       },
  1>       "hits" : {
  1>         "total" : 5,
  1>         "max_score" : 1.0,
  1>         "hits" : [
  1>           {
  1>             "_index" : "test_index",
  1>             "_type" : "test_type",
  1>             "_id" : "AVsWptjSUpYF0tZRx4kZ",
  1>             "_score" : 1.0,
  1>             "_source" : {
  1>               "filter_field" : 0,
  1>               "f1" : "remote_cluster"
  1>             }
  1>           },
  1>           {
  1>             "_index" : "test_index",
  1>             "_type" : "test_type",
  1>             "_id" : "AVsWptjSUpYF0tZRx4kV",
  1>             "_score" : 1.0,
  1>             "_source" : {
  1>               "filter_field" : 1,
  1>               "f1" : "remote_cluster"
  1>             }
  1>           },
  1>           {
  1>             "_index" : "test_index",
  1>             "_type" : "test_type",
  1>             "_id" : "AVsWptjSUpYF0tZRx4kX",
  1>             "_score" : 1.0,
  1>             "_source" : {
  1>               "filter_field" : 1,
  1>               "f1" : "remote_cluster"
  1>             }
  1>           },
  1>           {
  1>             "_index" : "test_index",
  1>             "_type" : "test_type",
  1>             "_id" : "AVsWptjSUpYF0tZRx4kW",
  1>             "_score" : 1.0,
  1>             "_source" : {
  1>               "filter_field" : 0,
  1>               "f1" : "remote_cluster"
  1>             }
  1>           },
  1>           {
  1>             "_index" : "test_index",
  1>             "_type" : "test_type",
  1>             "_id" : "AVsWptjSUpYF0tZRx4kY",
  1>             "_score" : 1.0,
  1>             "_source" : {
  1>               "filter_field" : 0,
  1>               "f1" : "remote_cluster"
  1>             }
  1>           }
  1>         ]
  1>       },
  1>       "aggregations" : {
  1>         "cluster" : {
  1>           "doc_count_error_upper_bound" : 0,
  1>           "sum_other_doc_count" : 0,
  1>           "buckets" : [
  1>             {
  1>               "key" : "remote_cluster",
  1>               "doc_count" : 5
  1>             }
  1>           ]
  1>         }
  1>       }
  1>     }
  1>   }
  1> }]
  2> REPRODUCE WITH: gradle :qa:multi-cluster-search:remoteClusterTestRunner -Dtests.seed=2C5B47B8A3E32364 -Dtests.class=org.elasticsearch.upgrades.MultiClusterSearchYamlTestSuiteIT -Dtests.method="test {p0=/10_basic/Index data and search on the old cluster}" -Dtests.security.manager=true -Dtests.locale=hu-HU -Dtests.timezone=Africa/Lagos -Dtests.rest.suite=remote_cluster
FAILURE 1.85s | MultiClusterSearchYamlTestSuiteIT.test {p0=/10_basic/Index data and search on the old cluster} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [/10_basic:45]: hits.total didn't match expected value:
   >                     hits.total: expected [6] but was [5]
   > 	at __randomizedtesting.SeedInfo.seed([2C5B47B8A3E32364:A40F78620D1F4E9C]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:377)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:357)
   > 	at java.lang.Thread.run(Thread.java:745)
   > Caused by: java.lang.AssertionError: hits.total didn't match expected value:
   >                     hits.total: expected [6] but was [5]
   > 	at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:87)
   > 	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:373)
   > 	... 38 more
```

Likely cause: The cause seems to be related to a problem during bulk indexing. In the node logs, we see the following output:

```
[2017-03-28T20:41:25,132][DEBUG][o.e.a.b.TransportShardBulkAction] [test_index][0] failed to execute bulk item (index) BulkShardRequest [[test_index][0]] containing [2] requests and a refresh
java.lang.NullPointerException: null
	at org.apache.lucene.util.AttributeSource.clearAttributes(AttributeSource.java:272) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.document.Field$StringTokenStream.incrementToken(Field.java:641) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:746) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:447) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:403) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:232) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:478) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1569) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1314) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:674) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.engine.InternalEngine.indexIntoLucene(InternalEngine.java:625) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:587) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:561) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:549) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:452) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequest(TransportShardBulkAction.java:134) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:218) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:117) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:75) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:967) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:945) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:113) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:327) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:269) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:900) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:897) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.shard.IndexShardOperationsLock.acquire(IndexShardOperationsLock.java:147) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock(IndexShard.java:1792) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:909) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.access$400(TransportReplicationAction.java:94) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:286) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:265) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:257) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:623) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:613) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

As this might indicate a problem in Lucene, I'm assigning it to you @jpountz for further dispatching.

**Comment by jpountz** [comment]
This is one of the impossible NPEs we have seen in our Fedora testing environment.
