### ISSUE TITLE
[CI] field collapsing on inner hits REST test failure

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#23852]
Seeing a failure in CI related to field collapsing on inner hits:

```
java.lang.AssertionError: Failure at [search/110_field_collapsing:128]: hits.hits.0.inner_hits.sub_hits.hits.total didn't match expected value:
hits.hits.0.inner_hits.sub_hits.hits.total: expected [1] but was [0]

	at __randomizedtesting.SeedInfo.seed([C79CDE5BCF1C833F:4FC8E18161E0EEC7]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:377)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:357)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

From: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=fedora/773/console

I haven't been able to reproduce it, but here is the line:

```
gradle :distribution:integ-test-zip:integTestRunner -Dtests.seed=C79CDE5BCF1C833F -Dtests.class=org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT -Dtests.method="test {p0=search/110_field_collapsing/field collapsing and inner_hits}" -Dtests.security.manager=true -Dtests.locale=es-PA -Dtests.timezone=GB
```

**Comment by dakrone** [comment]
@jimczi I assigned you since I believe you are most familiar with field collapsing, but feel free to assign elsewhere if someone else is better suited.

**Comment by javanna** [comment]
@jimczi do you recall if this was fixed?

**Comment by jimczi** [comment]
This happened once and it is non-reproducible.
I'll reopen if I see the failure again
