### ISSUE TITLE
CI: Test Failure SignificantTermsIT.testPartiallyUnmappedWithFormat

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#23873]
Was unable to reproduce this locally, an NPE coming up, resulting in a failed shard response from a quick look...

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=fedora/782/consoleFull

```
 REPRODUCE WITH: gradle :core:integTest -Dtests.seed=D2B25C8FF918C259 -Dtests.class=org.elasticsearch.search.aggregations.bucket.SignificantTermsIT -Dtests.method="testPartiallyUnmappedWithFormat" -Dtests.security.manager=true -Dtests.locale=es-PA -Dtests.timezone=America/Monterrey
FAILURE 0.05s J2 | SignificantTermsIT.testPartiallyUnmappedWithFormat <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Unexpected ShardFailures: [shard [[lC_J_oqxTqepARH_NWOv0w][test][2]], reason [RemoteTransportException[[node_s1][127.0.0.1:9682][indices:data/read/search[phase/query]]]; nested: NullPointerException; ], cause [java.lang.NullPointerException
   > 	at org.elasticsearch.search.aggregations.bucket.significant.SignificantTermsAggregatorFactory.doCreateInternal(SignificantTermsAggregatorFactory.java:241)
   > 	at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:55)
   > 	at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:221)
   > 	at org.elasticsearch.search.aggregations.AggregatorFactories.createTopLevelAggregators(AggregatorFactories.java:221)
   > 	at org.elasticsearch.search.aggregations.AggregationPhase.preProcess(AggregationPhase.java:55)
   > 	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:106)
   > 	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:246)
   > 	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:260)
   > 	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:330)
   > 	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:327)
   > 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
   > 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1482)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   > 	at java.lang.Thread.run(Thread.java:745)
```

@jpountz could you take a look?

**Comment by jpountz** [comment]
This is one of the impossible NPEs we have seen recently in our Fedora testing environment.
