### ISSUE TITLE
ingest-attachment consumes too much heap space 

### ISSUE THREAD

**Issue by rreverol** [elastic/elasticsearch#23882]
**Elasticsearch version**: 5.3

**Plugins installed**: [ingest-attachment]

**JVM version**: 1.8.0_121

**OS version**: Windows 10

**Description of the problem including expected versus actual behavior**:

I am trying to index 300 pdf documents with sizes between 400.000 and 1.500.000 characters. I am running just one ES Node in my local machine with 16 Gb. I have tried with serveral max heap configurations. I also installed the depracated mapping plugin and it worked just fine.

[Read more](https://discuss.elastic.co/t/ingest-attachment-performance-issue/81039)

**Steps to reproduce**:
 1.Install ingest-attachment
 2.Index a PDF file with more that 500.000 characters
 3.Look at the logs. You should see the error.

**Provide logs (if relevant)**:
```
[2017-04-03T14:55:42,309][INFO ][o.e.c.m.MetaDataMappingService] [node-name] [bpic/LczHwOoMRG2JSVQvw_yQmQ] update_mapping [document]
[2017-04-03T14:56:04,338][INFO ][o.e.m.j.JvmGcMonitorService] [node-name] [gc][5920] overhead, spent [604ms] collecting in the last [1.5s]
[2017-04-03T14:56:05,652][INFO ][o.e.m.j.JvmGcMonitorService] [node-name] [gc][5921] overhead, spent [471ms] collecting in the last [1.3s]
[2017-04-03T14:56:07,213][INFO ][o.e.m.j.JvmGcMonitorService] [node-name] [gc][5922] overhead, spent [577ms] collecting in the last [1.5s]
[2017-04-03T14:56:09,249][INFO ][o.e.m.j.JvmGcMonitorService] [node-name] [gc][5924] overhead, spent [479ms] collecting in the last [1s]
[2017-04-03T14:56:10,277][WARN ][o.e.m.j.JvmGcMonitorService] [node-name] [gc][5925] overhead, spent [653ms] collecting in the last [1s]
[2017-04-03T14:56:11,303][INFO ][o.e.m.j.JvmGcMonitorService] [node-name] [gc][5926] overhead, spent [338ms] collecting in the last [1s]
[2017-04-03T14:56:12,718][INFO ][o.e.m.j.JvmGcMonitorService] [node-name] [gc][5927] overhead, spent [559ms] collecting in the last [1.4s]
[2017-04-03T14:56:13,821][INFO ][o.e.m.j.JvmGcMonitorService] [node-name] [gc][5928] overhead, spent [281ms] collecting in the last [1.1s]
[2017-04-03T14:56:15,118][WARN ][o.e.m.j.JvmGcMonitorService] [node-name] [gc][5929] overhead, spent [1.1s] collecting in the last [1.2s]
[2017-04-03T14:56:16,833][WARN ][o.e.m.j.JvmGcMonitorService] [node-name] [gc][5930] overhead, spent [1.4s] collecting in the last [1.7s]
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid13752.hprof ...
[2017-04-03T14:56:18,501][WARN ][o.e.m.j.JvmGcMonitorService] [node-name] [gc][5931] overhead, spent [1.4s] collecting in the last [1.6s]
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid5636.hprof ...
Heap dump file created [4210465346 bytes in 44.132 secs]
[2017-04-03T15:19:00,734][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [hackett-bpic-docs] fatal error in thread [elasticsearch[hackett-bpic-docs][index][T#7]], exiting
java.lang.OutOfMemoryError: Java heap space
        at org.apache.lucene.index.FreqProxTermsWriterPerField$FreqProxPostingsArray.<init>(FreqProxTermsWriterPerField.java:210) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76
d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
        at org.apache.lucene.index.FreqProxTermsWriterPerField$FreqProxPostingsArray.newInstance(FreqProxTermsWriterPerField.java:230) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0
aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
        at org.apache.lucene.index.ParallelPostingsArray.grow(ParallelPostingsArray.java:46) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02
-01 14:43:32]
        at org.apache.lucene.index.TermsHashPerField$PostingsBytesStartArray.grow(TermsHashPerField.java:250) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e -
jpountz - 2017-02-01 14:43:32]
        at org.apache.lucene.util.BytesRefHash.add(BytesRefHash.java:271) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
        at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:149) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:4
3:32]
        at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:766) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz
 - 2017-02-01 14:43:32]
        at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:417) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz -
2017-02-01 14:43:32]
        at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:373) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz
 - 2017-02-01 14:43:32]
        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:231) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e -
jpountz - 2017-02-01 14:43:32]
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:478) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-
01 14:43:32]
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1575) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:4
3:32]
        at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1320) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:3
2]
        at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:558) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.index.engine.InternalEngine.innerIndex(InternalEngine.java:520) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:409) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:556) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:546) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:213) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.index.TransportIndexAction.onPrimaryShard(TransportIndexAction.java:166) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.index.TransportIndexAction.onPrimaryShard(TransportIndexAction.java:68) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.support.replication.TransportWriteAction.shardOperationOnPrimary(TransportWriteAction.java:76) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.support.replication.TransportWriteAction.shardOperationOnPrimary(TransportWriteAction.java:49) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:914) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:884) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:113) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:327) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:262) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:864) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:861) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.index.shard.IndexShardOperationsLock.acquire(IndexShardOperationsLock.java:147) ~[elasticsearch-5.2.2.jar:5.2.2]
        at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock(IndexShard.java:1652) ~[elasticsearch-5.2.2.jar:5.2.2]
```

**Comment by jasontedor** [comment]
Can you share a heap dump?

**Comment by jasontedor** [comment]
I hope that you do not mind that I edited your post to format the logs (I wrapped them in triple backticks).

**Comment by colings86** [comment]
No further feedback, closing. If you have the heap dump or are otherwise able to recreate the issue please comment and we can reopen
