### ISSUE TITLE
Elastic 5.2.1 & x-pack : unable to define action.auto_create_index ?

### ISSUE THREAD

**Issue by MarneusCalgarXP** [elastic/elasticsearch#23919]
**Elasticsearch version**: 5.2.1

**Plugins installed**: [x-pack] (only monitoring enabled, withc basic licence)

elastic.yml:

```
xpack.security.enabled: false
xpack.graph.enabled: false
xpack.watcher.enabled: false

```

**JVM version**: 1.8.0_101-b13

**OS version**: Centos 6 64bit

**Description of the problem including expected versus actual behavior**:
When trying to define

**Steps to reproduce**:
 1. add the following line in elastic.yml:
`action.auto_create_index: +.monitoring-*,+logstash*,+performance*,-*`
 2. start elasticsearch

**Provide logs (if relevant)**:

```
[2017-04-05T17:10:45,770][ERROR][o.e.b.Bootstrap          ] Exception
org.elasticsearch.ElasticsearchException: Failed to load plugin class [org.elasticsearch.xpack.XPackPlugin]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:384) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:336) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:132) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.node.Node.<init>(Node.java:297) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.node.Node.<init>(Node.java:232) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:241) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:241) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) [elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) [elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) [elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) [elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) [elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.cli.Command.main(Command.java:88) [elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) [elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) [elasticsearch-5.2.1.jar:5.2.1]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_101]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:373) ~[elasticsearch-5.2.1.jar:5.2.1]
        ... 14 more
Caused by: java.lang.IllegalArgumentException: the [action.auto_create_index] setting value [.watches, .triggered_watches, +.watcher-history-*, +.monitoring-*, -*] is t
oo restrictive. disable [action.auto_create_index] or set it to [.watches, .triggered_watches, .watcher-history-*]
        at org.elasticsearch.xpack.watcher.Watcher.validAutoCreateIndex(Watcher.java:389) ~[?:?]
        at org.elasticsearch.xpack.watcher.Watcher.<init>(Watcher.java:186) ~[?:?]
        at org.elasticsearch.xpack.XPackPlugin.<init>(XPackPlugin.java:199) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_101]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:373) ~[elasticsearch-5.2.1.jar:5.2.1]
        ... 14 more

```

**Note**

I tried several variations of the config line, still the same error :

`action.auto_create_index: .watches,.triggered_watches,.watcher-history-*,+.monitoring-*,+logstash*,+performance*,-*`

`action.auto_create_index: +.watches,+.triggered_watches,+.watcher-history-*,+.monitoring-*,+logstash*,+performance*,-*`

`action.auto_create_index: +.watches,+.triggered_watches,+.watcher-history-*,+.monitoring-*,+logstash*,+performance*`

`action.auto_create_index: .watches,.triggered_watches,.watcher-history-*,+.monitoring-*,+logstash*,+performance*`

`action.auto_create_index: .watches,.triggered_watches,.watcher-history-*`

**Comment by cbuescher** [comment]
@MarneusCalgarXP thanks, I got the same error with your settings on 5.2.2, but
```
action.auto_create_index: +.watches,+.triggered_watches,+.watcher-history-*,+.monitoring-*,+logstash*,+performa    nce*,-*
```
worked for me. However, I think watcher shouldn't perform those checks if it is disabled. Maybe @spinscale has an opinion on that?

**Comment by spinscale** [comment]
@cbuescher yes you are right, that should not happen. I will fix it on the x-pack side.

**Comment by spinscale** [comment]
This will be fixed in the next patch release of Elasticsearch/X-pack 5.3 - thanks so much for reporting!
