### ISSUE TITLE
MultiClusterSearchYamlTestSuiteIT {p0=/10_basic/Index data and search on the mixed cluster} failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#23944]
This failure doesn't reproduce. 

Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=fedora/799

```
REPRODUCE WITH: gradle :qa:multi-cluster-search:mixedClusterTestRunner -Dtests.seed=18B085DB832CAF1E -Dtests.class=org.elasticsearch.upgrades.MultiClusterSearchYamlTestSuiteIT -Dtests.method="test {p0=/10_basic/Index data and search on the mixed cluster}" -Dtests.security.manager=true -Dtests.locale=lt -Dtests.timezone=Mexico/BajaNorte -Dtests.rest.suite=multi_cluster
FAILURE 1.53s | MultiClusterSearchYamlTestSuiteIT.test {p0=/10_basic/Index data and search on the mixed cluster} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [/10_basic:38]: hits.total didn't match expected value:
   >                     hits.total: expected [11] but was [10]
   > 	at __randomizedtesting.SeedInfo.seed([18B085DB832CAF1E:90E4BA012DD0C2E6]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:377)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:357)
   > 	at java.lang.Thread.run(Thread.java:745)
   > Caused by: java.lang.AssertionError: hits.total didn't match expected value:
   >                     hits.total: expected [11] but was [10]
   > 	at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:87)
   > 	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:373)
   > 	... 38 more
```

**Comment by martijnvg** [comment]
@javanna Perhaps, let me check the node logs on slave machine.

**Comment by martijnvg** [comment]
This also seems to be caused by an failure during indexing, but it is a different one than in #23790

```
[2017-04-06T10:47:17,625][INFO ][o.e.n.Node               ] [node-0] initializing ...
[2017-04-06T10:47:17,717][INFO ][o.e.e.NodeEnvironment    ] [node-0] using [1] data paths, mounts [[/ (/dev/xvda1)]], net usable_space [405.4gb], net total_space [492gb], spins? [no], types [ext4]
[2017-04-06T10:47:17,717][INFO ][o.e.e.NodeEnvironment    ] [node-0] heap size [494.9mb], compressed ordinary object pointers [true]
[2017-04-06T10:47:17,718][INFO ][o.e.n.Node               ] [node-0] node name [node-0], node ID [NNzpFYEySUKrH73cbQYcZA]
[2017-04-06T10:47:17,718][INFO ][o.e.n.Node               ] [node-0] version[6.0.0-alpha1-SNAPSHOT], pid[26110], build[042f756/2017-04-06T09:57:13.391Z], OS[Linux/4.9.14-200.fc25.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_121/25.121-b14]
[2017-04-06T10:47:17,718][WARN ][o.e.n.Node               ] [node-0] version [6.0.0-alpha1-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
[2017-04-06T10:47:18,700][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [aggs-matrix-stats]
[2017-04-06T10:47:18,701][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [ingest-common]
[2017-04-06T10:47:18,701][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [lang-expression]
[2017-04-06T10:47:18,701][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [lang-mustache]
[2017-04-06T10:47:18,701][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [lang-painless]
[2017-04-06T10:47:18,701][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [percolator]
[2017-04-06T10:47:18,701][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [reindex]
[2017-04-06T10:47:18,702][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [repository-url]
[2017-04-06T10:47:18,702][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [transport-netty4]
[2017-04-06T10:47:18,702][INFO ][o.e.p.PluginsService     ] [node-0] no plugins loaded
[2017-04-06T10:47:20,283][INFO ][o.e.d.DiscoveryModule    ] [node-0] using discovery type [zen]
[2017-04-06T10:47:20,902][INFO ][o.e.n.Node               ] [node-0] initialized
[2017-04-06T10:47:20,902][INFO ][o.e.n.Node               ] [node-0] starting ...
[2017-04-06T10:47:21,023][INFO ][o.e.t.TransportService   ] [node-0] publish_address {127.0.0.1:43673}, bound_addresses {[::1]:41061}, {127.0.0.1:43673}
[2017-04-06T10:47:24,080][INFO ][o.e.c.s.ClusterService   ] [node-0] new_master {node-0}{NNzpFYEySUKrH73cbQYcZA}{XrABsgC_SP6aEM2COIb7Qw}{127.0.0.1}{127.0.0.1:43673}{testattr=test}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-04-06T10:47:24,100][INFO ][o.e.h.n.Netty4HttpServerTransport] [node-0] publish_address {127.0.0.1:34623}, bound_addresses {[::1]:43879}, {127.0.0.1:34623}
[2017-04-06T10:47:24,111][INFO ][o.e.g.GatewayService     ] [node-0] recovered [0] indices into cluster_state
[2017-04-06T10:47:24,260][INFO ][o.e.n.Node               ] [node-0] started
[2017-04-06T10:47:26,612][INFO ][o.e.c.m.MetaDataCreateIndexService] [node-0] [test_index] creating index, cause [api], templates [], shards [2]/[0], mappings []
[2017-04-06T10:47:26,790][INFO ][o.e.c.r.a.AllocationService] [node-0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test_index][0], [test_index][1]] ...]).
[2017-04-06T10:47:26,892][DEBUG][o.e.a.b.TransportShardBulkAction] [test_index][0] failed to execute bulk item (index) BulkShardRequest [[test_index][0]] containing [3] requests and a refresh
org.elasticsearch.index.mapper.MapperParsingException: failed to parse
	at org.elasticsearch.index.mapper.DocumentParser.wrapInMapperParsingException(DocumentParser.java:174) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:68) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:261) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:536) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:512) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.prepareIndexOperationOnPrimary(TransportShardBulkAction.java:480) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:492) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequest(TransportShardBulkAction.java:137) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:231) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:120) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:78) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:967) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:945) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:113) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:327) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:269) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:900) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:897) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.shard.IndexShardOperationsLock.acquire(IndexShardOperationsLock.java:147) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock(IndexShard.java:1792) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:909) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction.access$400(TransportReplicationAction.java:94) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:286) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:265) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:257) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:623) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at org.joda.time.format.DateTimeParserBucket$SavedState.<init>(DateTimeParserBucket.java:521) ~[joda-time-2.9.5.jar:2.9.5]
	at org.joda.time.format.DateTimeParserBucket.saveState(DateTimeParserBucket.java:354) ~[joda-time-2.9.5.jar:2.9.5]
	at org.joda.time.format.DateTimeFormatterBuilder$MatchingParser.parseInto(DateTimeFormatterBuilder.java:2592) ~[joda-time-2.9.5.jar:2.9.5]
	at org.joda.time.format.DateTimeFormatterBuilder$Composite.parseInto(DateTimeFormatterBuilder.java:2516) ~[joda-time-2.9.5.jar:2.9.5]
	at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:179) ~[joda-time-2.9.5.jar:2.9.5]
	at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:826) ~[joda-time-2.9.5.jar:2.9.5]
	at org.elasticsearch.index.mapper.DocumentParser.createBuilderFromDynamicValue(DocumentParser.java:701) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.mapper.DocumentParser.parseDynamicValue(DocumentParser.java:782) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:581) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:394) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:371) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.mapper.DocumentParser.internalParseDocument(DocumentParser.java:92) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:65) ~[elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:6.0.0-alpha1-SNAPSHOT]
	... 31 more
[2017-04-06T10:47:26,913][INFO ][o.e.c.m.MetaDataMappingService] [node-0] [test_index/Txezute9TJmbNv9IXdl8PA] create_mapping [test_type]
[2017-04-06T10:47:27,512][INFO ][o.e.c.s.ClusterSettings  ] [node-0] updating [search.remote.test_remote_cluster.seeds] from [[]] to [["[::1]:40209"]]
```

**Comment by s1monw** [comment]
thanks for the investigation @martijnvg I was pretty puzzled when I looked at the logs

**Comment by s1monw** [comment]
@martijnvg I think this should be assigned to somebody else?

**Comment by jasontedor** [comment]
I'm closing this one, we are tracking it internally as a possible infrastructure issue: either bad hardware on the slave, or a JVM bug. It's looking less likely it's the former, and more likely it's the latter.
