### ISSUE TITLE
QueryStringQueryBuilderTests.testExistsFieldQuery fails

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#23979]
This test has been failing in the last few hours on both master and 5.x.

```
Expected: (<(ConstantScore(_field_names:mapped_date) | ConstantScore(_field_names:mapped_object.mapped_date) | ConstantScore(_field_names:mapped_object.mapped_int) | ConstantScore(_field_names:foo) | ConstantScore(_field_names:mapped_double) | ConstantScore(_field_names:mapped_int) | ConstantScore(_field_names:mapped_string_2) | ConstantScore(_field_names:mapped_string))> or <ConstantScore(_field_names:_all)>)
      but: was <*:*>
 	at __randomizedtesting.SeedInfo.seed([5490B50F282310:BF422B7E7FEC8FD8]:0)
 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
 	at org.elasticsearch.index.query.QueryStringQueryBuilderTests.testExistsFieldQuery(QueryStringQueryBuilderTests.java:873)
 	at java.lang.Thread.run(Thread.java:745)
```

I suspect it may have to do with #23967.

**Comment by javanna** [comment]
@jimczi can you have a look please?

**Comment by jimczi** [comment]
Thanks @javanna 
I pushed https://github.com/elastic/elasticsearch/commit/e32c16e3494c449d50f4a3479492434b854382fa
