### ISSUE TITLE
[2.4] Cryptic error messages for pipeline aggregations when the aggregation name matches the aggregation type

### ISSUE THREAD

**Issue by kujon** [elastic/elasticsearch#24023]
Consider the following aggregation:

```json
{
    "histogram": {
        "date_histogram": {
            "field": "timestamp",
            "interval": "day"
        },
        "aggs": {
            "quantity": {
                "sum": {
                    "field": "price"
                }
            }
        }
    }
}
```

The only unusual thing here is that its name happens to be the same as one of the aggregation types, but it works just fine. That is until you add a pipeline aggregation:

```json
{
    "histogram": {
        "date_histogram": {
            "field": "timestamp",
            "interval": "day"
        },
        "aggs": {
            "quantity": {
                "sum": {
                    "field": "price"
                }
            }
        }
    },
    "average_of_histogram": {
        "avg_bucket": {
            "buckets_path": "histogram>quantity"
        }
    }
}
```

ES fails to reduce the search and blows up with the following message:
```
[2017-04-10 15:20:35,870][DEBUG][action.search ] [Marvel Girl] failed to reduce search
Failed to execute phase [fetch], [reduce]
at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction$2.onFailure(SearchQueryThenFetchAsyncAction.java:146)
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: org.elasticsearch.search.aggregations.metrics.sum.InternalSum cannot be cast to org.elasticsearch.search.aggregations.InternalMultiBucketAggregation
at org.elasticsearch.search.aggregations.pipeline.bucketmetrics.BucketMetricsPipelineAggregator.doReduce(BucketMetricsPipelineAggregator.java:70)
at org.elasticsearch.search.aggregations.pipeline.SiblingPipelineAggregator.reduce(SiblingPipelineAggregator.java:56)
at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:155)
at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:170)
at org.elasticsearch.search.aggregations.bucket.InternalSingleBucketAggregation.doReduce(InternalSingleBucketAggregation.java:93)
at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:153)
at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:170)
at org.elasticsearch.search.controller.SearchPhaseController.merge(SearchPhaseController.java:411)
at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction$2.doRun(SearchQueryThenFetchAsyncAction.java:132)
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
```

Should something be done about those error messages being a little bit more descriptive? Should aggregations disallow certain 'reserved keywords' as their names explicitly?

**Comment by colings86** [comment]
@kujon I tried reproducing your bug on both the master branch and on the 2.4.4 release of Elasticsearch and I wasn't able to get the error you got above, instead the aggregations completed successfully. The script I used was:

```

PUT test
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0
  },
  "mappings": {
    "doc": {
      "properties": {
        "timestamp": {
          "type": "date"
        }
      }
    }
  }
}

POST test/doc/1
{
  "timestamp": "2017-01-01",
  "price": 100
}

POST test/doc/2
{
  "timestamp": "2017-01-02",
  "price": 200
}

POST test/doc/3
{
  "timestamp": "2017-01-03",
  "price": 300
}

POST test/doc/4
{
  "timestamp": "2017-01-04",
  "price": 400
}

POST test/_search
{
  "size": 0,
  "aggs": {
    "histogram": {
      "date_histogram": {
        "field": "timestamp",
        "interval": "day"
      },
      "aggs": {
        "quantity": {
          "sum": {
            "field": "price"
          }
        }
      }
    },
    "average_of_histogram": {
      "avg_bucket": {
        "buckets_path": "histogram>quantity"
      }
    }
  }
}
```

Could you try running the above script on your environment and see if the error reproduces?  Could you also confirm the exact version of ES that you are running (e.g. 2.4.4)?

The curious thing here is that the buckets path should have already been validated as pointing to a suitable aggregation earlier than this so the cast attempted here should in theory be safe.

**Comment by colings86** [comment]
No further feedback, closing. If you are able to provide more feedback please comment on this issue and we can reopen
