### ISSUE TITLE
GoogleCloudStorageBlobStoreRepositoryTests : NPE in ZenDiscovery.findMaster

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#24027]
Some of the `GoogleCloudStorageBlobStoreRepositoryTests` tests failed at the same time in this run: 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-intake/995 .

I found some NPEs when trying to find a master in the logs, here is the stacktrace:

```
1> [2017-04-10T08:53:08,926][ERROR][o.e.t.d.TestZenDiscovery ] [node_sc1] unexpected error while joining cluster, trying again
  1> java.lang.NullPointerException: null
  1> 	at java.util.stream.FindOps$FindSink$OfRef.<init>(FindOps.java:190) ~[?:1.8.0_121]
  1> 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_121]
  1> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_121]
  1> 	at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469) ~[?:1.8.0_121]
  1> 	at org.elasticsearch.discovery.zen.ZenDiscovery.findMaster(ZenDiscovery.java:896) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:386) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
```

**Comment by javanna** [comment]
@boaz could you have a look at this or further dispatch it?

**Comment by abeyad** [comment]
This also seems to be one of those strange JVM exceptions.  `FindOps.java` line 190 appears to be the start of the `OfRef<T>` class definition.

**Comment by bleskes** [comment]
the ZenDiscovery line is 
``` 
       assert fullPingResponses.stream().map(ZenPing.PingResponse::node)
            .filter(n -> n.equals(localNode)).findAny().isPresent() == false;
```

it *might* be that `ZenPing.PingResponse::node` returns null

**Comment by bleskes** [comment]
@abeyad can you dig a bit in that direction?

**Comment by abeyad** [comment]
@bleskes I am closing this as we are tracking these JVM exceptions elsewhere.
