### ISSUE TITLE
GoogleCloudStorageBlobStoreRepositoryTests.testSnapshotAndRestore failure

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#24026]
Failure was on 5.x branch: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-unix-compatibility/os=fedora/668.

```
> Expected: an empty iterable
   >      but: [<RemoteTransportException[[transport_client_node_s1][local[4]][indices:data/write/index]]; nested: NullPointerException;>]
   > 	at __randomizedtesting.SeedInfo.seed([A275D6F5C772A3C9:6212B5861ABD5EFE]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1443)
   > 	at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1363)
   > 	at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1347)
   > 	at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1323)
   > 	at org.elasticsearch.repositories.blobstore.ESBlobStoreRepositoryIntegTestCase.addRandomDocuments(ESBlobStoreRepositoryIntegTestCase.java:227)
   > 	at org.elasticsearch.repositories.blobstore.ESBlobStoreRepositoryIntegTestCase.testSnapshotAndRestore(ESBlobStoreRepositoryIntegTestCase.java:62)
```

The `NullPointerException` seems to be while indexing, here is the stacktrace:

```
  1> [2017-04-10T17:38:31,943][INFO ][o.e.r.g.GoogleCloudStorageBlobStoreRepositoryTests] Action Failed
  1> org.elasticsearch.transport.RemoteTransportException: [transport_client_node_s1][local[4]][indices:data/write/index]
  1> Caused by: java.lang.NullPointerException
  1> 	at org.apache.lucene.index.DocumentsWriterPerThread.<init>(DocumentsWriterPerThread.java:190) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
  1> 	at org.apache.lucene.index.DocumentsWriter.ensureInitialized(DocumentsWriter.java:410) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
  1> 	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:473) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
  1> 	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1569) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
  1> 	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1314) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
  1> 	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:639) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.index.engine.InternalEngine.indexIntoLucene(InternalEngine.java:583) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:483) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:556) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:545) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:484) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:143) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:113) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:69) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:939) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:908) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:113) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:322) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:264) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:888) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:885) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.index.shard.IndexShardOperationsLock.acquire(IndexShardOperationsLock.java:147) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock(IndexShard.java:1654) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:897) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction.access$400(TransportReplicationAction.java:93) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:281) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:260) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:252) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:627) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_121]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_121]
  1> 	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_121]
```

**Comment by javanna** [comment]
Not too sure who to assign here but maybe @ywelsch would like to have a look given that the problem is when indexing. Feel free to reassign or further dispatch it.

**Comment by abeyad** [comment]
Seems like one of those strange JVM exceptions.  In this case, the stack trace for the NPE is coming from an end curly brace (`}`): https://github.com/apache/lucene-solr/blob/releases/lucene-solr/6.5.0/lucene/core/src/java/org/apache/lucene/index/DocumentsWriterPerThread.java#L190

**Comment by jasontedor** [comment]
I think we can close this since we're tracking it elsewhere.

**Comment by javanna** [comment]
thanks for clarifying, I was ready to blame my IDE for linking to the wrong source code :) I will watch out for these NPEs.
