### ISSUE TITLE
Cannot start elasticsearch because of java.security.AccessControlException

### ISSUE THREAD

**Issue by grapemix** [elastic/elasticsearch#24062]
**Elasticsearch version**:
5.3.0 thru deb
 
**JVM version**:
openjdk-9-jre-headless & openjdk-8-jre-headless

I tried both, but still no luck

**OS version**:
Ubuntu 16.04 in aws

**Description of the problem including expected versus actual behavior**:
Cannot even start elasticsearch. I saw a bug from https://github.com/elastic/elasticsearch/issues/18761
But installing openjdk-9-jre-headless | openjdk-8-jre-headless do not solve my problem. Any ideas?

**Steps to reproduce**:
 1. sudo service elasticsearch start
 2. 
 3.

**Provide logs (if relevant)**:
From elasticsearch.log

[2017-04-12 08:09:28,552][INFO ][node                     ] [Atlas] version[2.2.0], pid[28877], build[8ff36d1/2016-01-27T13:32:39Z]
[2017-04-12 08:09:28,553][INFO ][node                     ] [Atlas] initializing ...
[2017-04-12 08:09:29,485][INFO ][plugins                  ] [Atlas] modules [lang-expression, lang-groovy], plugins [], sites []
[2017-04-12 08:09:29,534][INFO ][env                      ] [Atlas] using [1] data paths, mounts [[/ (/dev/xvda1)]], net usable_space [4.6gb], net total_space [7.7gb], spins? [no], types [ext4]
[2017-04-12 08:09:29,534][INFO ][env                      ] [Atlas] heap size [1015.6mb], compressed ordinary object pointers [true]
[2017-04-12 08:09:29,568][ERROR][bootstrap                ] Exception
java.lang.Error: java.security.AccessControlException: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")
	at com.twitter.jsr166e.Striped64.<clinit>(Striped64.java:319)
	at org.elasticsearch.common.metrics.CounterMetric.<init>(CounterMetric.java:28)
	at org.elasticsearch.common.util.concurrent.EsAbortPolicy.<init>(EsAbortPolicy.java:30)
	at org.elasticsearch.common.util.concurrent.EsExecutors.newFixed(EsExecutors.java:80)
	at org.elasticsearch.threadpool.ThreadPool.rebuild(ThreadPool.java:482)
	at org.elasticsearch.threadpool.ThreadPool.build(ThreadPool.java:400)
	at org.elasticsearch.threadpool.ThreadPool.<init>(ThreadPool.java:232)
	at org.elasticsearch.node.Node.<init>(Node.java:158)
	at org.elasticsearch.node.Node.<init>(Node.java:128)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.security.AccessControlException: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")
	at java.security.AccessControlContext.checkPermission(java.base@9-internal/AccessControlContext.java:468)
	at java.security.AccessController.checkPermission(java.base@9-internal/AccessController.java:894)
	at java.lang.SecurityManager.checkPermission(java.base@9-internal/SecurityManager.java:541)
	at java.lang.reflect.AccessibleObject.checkPermission(java.base@9-internal/AccessibleObject.java:74)
	at java.lang.reflect.Field.setAccessible(java.base@9-internal/Field.java:163)
	at com.twitter.jsr166e.Striped64$1.run(Striped64.java:340)
	at com.twitter.jsr166e.Striped64$1.run(Striped64.java:336)
	at java.security.AccessController.doPrivileged(java.base@9-internal/Native Method)
	at com.twitter.jsr166e.Striped64.getUnsafe(Striped64.java:335)
	at com.twitter.jsr166e.Striped64.<clinit>(Striped64.java:312)
	... 12 more

**Comment by spinscale** [comment]
the elasticsearch.log shows version `2.2.0`, see

```
[2017-04-12 08:09:28,552][INFO ][node ] [Atlas] version[2.2.0], pid[28877], build[8ff36d1/2016-01-27T13:32:39Z]
```

are you sure you did a full upgrade to 5.3.0 - maybe there are some leftovers?

**Comment by grapemix** [comment]
That is totally my problem. The elasticsearch service started from systemd is unable to output to my log and hence cause log file data contamination. Besides, don't ever try to modify the group from the systemd service file. It just not working and cause a lot of trouble.

The bright side is I just tested bunch of combination of elasticsearch vs jdk.

es 2.2.0 works w/ openjdk-8-jre-headless in ubuntu 16
es 5.3.0 works w/ openjdk-8-jre-headless in ubuntu 16
es 5.3.0 works w/ openjdk-9-jre-headless in ubuntu 16

Finally, sorry for your time and confusion.
