### ISSUE TITLE
InternalTopHistTests fails with a particular seed on master

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#24083]
Reproduce command: 
```
gradle :core:test -Dtests.seed=4CB60CE3DF057B4C -Dtests.class=org.elasticsearch.search.aggregations.metrics.tophits.InternalTopHitsTests -Dtests.method="testReduceRandom" -Dtests.security.manager=true -Dtests.locale=sr-Latn-ME -Dtests.timezone=America/Mendoza
```

error:
```
FAILURE 1.28s | InternalTopHitsTests.testReduceRandom <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Didn't match expected value:
   >                           hits:
   >                             hits: same [empty list]
   >                        max_score: expected [1.4E-45] but not found
   >                            total: same [368137]
   >    at __randomizedtesting.SeedInfo.seed([4CB60CE3DF057B4C:8C8BA0F2F958E21A]:0)
   >    at org.elasticsearch.test.ESTestCase.assertEqualsWithErrorMessageFromXContent(ESTestCase.java:1037)
   >    at org.elasticsearch.search.aggregations.metrics.tophits.InternalTopHitsTests.assertReduced(InternalTopHitsTests.java:159)
   >    at org.elasticsearch.search.aggregations.metrics.tophits.InternalTopHitsTests.assertReduced(InternalTopHitsTests.java:52)
   >    at org.elasticsearch.search.aggregations.InternalAggregationTestCase.testReduceRandom(InternalAggregationTestCase.java:81)
   >    at java.lang.Thread.run(Thread.java:745)
  2> NOTE: leaving temporary files on disk at: /Users/colings86/dev/work/git/elasticsearch-lucene7/core/build/testrun/test/J0/temp/org.elasticsearch.search.aggregations.metrics.tophits.InternalTopHitsTests_4CB60CE3DF057B4C-001
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=1027, maxMBSortInHeap=5.568395574389006, sim=RandomSimilarity(queryNorm=false): {}, locale=sr-Latn-ME, timezone=America/Mendoza
  2> NOTE: Mac OS X 10.12.4 x86_64/Oracle Corporation 1.8.0_112 (64-bit)/cpus=8,threads=1,free=469457424,total=514850816
  2> NOTE: All tests run in this JVM: [InternalTopHitsTests]
Completed [1/1] in 2.59s, 1 test, 1 failure <<< FAILURES!
```

It looks like in this case we have 1 shard to reduce which has an unmapped top hits response. The test expects the max score to be `Float.MIN_VALUE` but the actual max score is `Float.NaN`. Maybe the test should be checking if there are any hits an setting the expected max score to `Float.NAN`?

/cc @nik9000  does that sound sensible to you?

**Comment by nik9000** [comment]
> /cc @nik9000 does that sound sensible to you?

I don't remember! I'll have another look in a bit.

**Comment by nik9000** [comment]
Looks like @abeyad got it while I wasn't paying attention in 5e54c0261a7fbcec9624e2279c667283354934b8.

**Comment by nik9000** [comment]
Looks like @abeyad got it while I wasn't paying attention in 5e54c0261a7fbcec9624e2279c667283354934b8.
