### ISSUE TITLE
[TEST] ReindexClientYamlTestSuiteIT multiple slices with wait_for_completion failure

### ISSUE THREAD

**Issue by abeyad** [elastic/elasticsearch#24094]
I could not get it to reproduce, but this is the reproduction line:
```
gradle :modules:reindex:integTest -Dtests.seed=22EAF2551503EF -Dtests.class=org.elasticsearch.index.reindex.ReindexClientYamlTestSuiteIT -Dtests.method="test {yaml=update_by_query/70_slices/Multiple slices with wait_for_completion=false}" -Dtests.security.manager=true -Dtests.locale=ar -Dtests.timezone=America/Matamoros
```

The failure message:
```
 > Throwable #1: java.lang.AssertionError: Failure at [update_by_query/70_slices:119]: response.failures didn't match the expected value:
   >              response.failures: 
   >   received [1] more entries than expected
   > 	at __randomizedtesting.SeedInfo.seed([22EAF2551503EF:8876D528FBE96E17]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:310)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:290)
   > 	at java.lang.Thread.run(Thread.java:745)
   > Caused by: java.lang.AssertionError: response.failures didn't match the expected value:
   >              response.failures: 
   >   received [1] more entries than expected
   > 	at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:84)
   > 	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:306)
```

See https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.1+multijob-unix-compatibility/os=fedora/201/console

**Comment by nik9000** [comment]
It *looks* like one of those creepy null pointer exceptions on fedora. The build is gone and it doesn't reproduce too. So I'm gonna close this and hope we catch the next one. Or we get to the bottom of fedora's NPEs....
