### ISSUE TITLE
Elasticsearch 5.3.0 update happend Negative longs unsupported, use writeLong or writeZLong for negative numbers [-1]

### ISSUE THREAD

**Issue by liuguangmin** [elastic/elasticsearch#24105]
**Elasticsearch version**:5.3.0

**Plugins installed**: [ik,mmseg,pinyin,x-pack]

**JVM version**:java_1.8 -Xms2g -Xmx2g

**OS _version**:Linux
****
**Description of the problem including expected versus actual behavior**:
update elasticsearch5.2.2 to elasticsearch5.3.0, In this process,the index status cannot get ,because in the index status message contains negative -1 so invoke the org.elasticsearch.common.io.stream.StreamOutput.writeVLong() method
throw  Negative longs unsupported, use writeLong or writeZLong for negative numbers [-1].
but this is in elasticsearch5.2.2 not happend.
===================================================
   public void writeVLong(long i) throws IOException {
        if (i < 0) {
            throw new IllegalStateException("Negative longs unsupported, use writeLong or writeZLong for negative numbers [" + i + "]");
        }
        writeVLongNoCheck(i);
    }
============================================
I had rebuild index but this not take  effect

**Provide logs (if relevant)**:
 failed to execute [indices:monitor/stats] on node [oZzo0dKWSZaCctRHnojZMg]
org.elasticsearch.transport.RemoteTransportException: [datagrand-data-2][10.172.80.229:9300][indices:monitor/stats[n]]
Caused by: java.lang.IllegalStateException: Negative longs unsupported, use writeLong or writeZLong for negative numbers [-1]
        at org.elasticsearch.common.io.stream.StreamOutput.writeVLong(StreamOutput.java:219) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.index.search.stats.SearchStats$Stats.writeTo(SearchStats.java:204) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.index.search.stats.SearchStats.writeTo(SearchStats.java:353) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.io.stream.StreamOutput.writeOptionalStreamable(StreamOutput.java:723) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.admin.indices.stats.CommonStats.writeTo(CommonStats.java:255) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.admin.indices.stats.ShardStats.writeTo(ShardStats.java:102) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.io.stream.StreamOutput.writeOptionalStreamable(StreamOutput.java:723) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$NodeResponse.writeTo(TransportBroadcastByNodeAction.java:574) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TcpTransport.buildMessage(TcpTransport.java:1179) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TcpTransport.sendResponse(TcpTransport.java:1123) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TcpTransport.sendResponse(TcpTransport.java:1101) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TcpTransportChannel.sendResponse(TcpTransportChannel.java:67) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TcpTransportChannel.sendResponse(TcpTransportChannel.java:61) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.DelegatingTransportChannel.sendResponse(DelegatingTransportChannel.java:58) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.RequestHandlerRegistry$TransportChannelWrapper.sendResponse(RequestHandlerRegistry.java:111) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.messageReceived(TransportBroadcastByNodeAction.java:425) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransportRequestHandler.messageReceived(TransportBroadcastByNodeAction.java:399) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1488) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:613) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.3.0.jar:5.3.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by jasontedor** [comment]
Can you share the current output of `/_stats/search?level=shards`?

**Comment by liuguangmin** [comment]
I remove node.ingest:false from ES cluster coordinating node ,the error disappear 
but I don't understand why

**Comment by jasontedor** [comment]
Because that requires a node restart and cleared the offending stats.

**Comment by liuguangmin** [comment]
sorry   I might have said something wrong
 the question is below：
before I modify ,I set the data node config:
node.master: false
node.data: true
node.ingest: true

I modify ago
node.master: false
node.data: true
node.ingest: false

and I move "node.ingest: true "to coordinating node
and the  coordinating node's config is:
node.master: false
node.data: false

**Comment by jasontedor** [comment]
If you are able to reproduce this, please feel free to open a new issue.
