### ISSUE TITLE
[TEST] Netty hangs on node startup

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#24103]
Test failure:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/2443/consoleFull

Relevant log lines:

```
  2> WARNING: Suite execution timed out: org.elasticsearch.http.DetailedErrorsEnabledIT
  2> ==== jstack at approximately timeout time ====
...
3) Thread[id=20, name=test_SUITE-CHILD_VM=[0]-CLUSTER_SEED=[-2061051122656044513]-HASH=[CE61632AD5D6]-cluster[T#1], state=WAITING, group=TGRP-DetailedErrorsEnabledIT]
  2>         at java.lang.Object.wait(Native Method)
  2>         at java.lang.Object.wait(Object.java:502)
  2>         at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:254)
  2>         at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:135)
  2>         at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:28)
  2>         at io.netty.util.concurrent.DefaultPromise.syncUninterruptibly(DefaultPromise.java:340)
  2>         at io.netty.channel.DefaultChannelPromise.syncUninterruptibly(DefaultChannelPromise.java:123)
  2>         at io.netty.channel.DefaultChannelPromise.syncUninterruptibly(DefaultChannelPromise.java:28)
  2>         at org.elasticsearch.transport.netty4.Netty4Transport.bind(Netty4Transport.java:427)
  2>         at org.elasticsearch.transport.netty4.Netty4Transport.bind(Netty4Transport.java:93)
  2>         at org.elasticsearch.transport.TcpTransport.lambda$bindToPort$2(TcpTransport.java:719)
  2>         at org.elasticsearch.transport.TcpTransport$$Lambda$1301/1035060863.onPortNumber(Unknown Source)
  2>         at org.elasticsearch.common.transport.PortsRange.iterate(PortsRange.java:70)
  2>         at org.elasticsearch.transport.TcpTransport.bindToPort(TcpTransport.java:717)
  2>         at org.elasticsearch.transport.TcpTransport.bindServer(TcpTransport.java:701)
  2>         at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:171)
  2>         at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:66)
  2>         at org.elasticsearch.transport.TransportService.doStart(TransportService.java:196)
  2>         at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:66)
  2>         at org.elasticsearch.node.Node.start(Node.java:602)
  2>         at org.elasticsearch.test.InternalTestCluster$NodeAndClient.startNode(InternalTestCluster.java:862)
  2>         at org.elasticsearch.test.InternalTestCluster$$Lambda$1283/2064488749.run(Unknown Source)
  2>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  2>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  2>         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569)
  2>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  2>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  2>         at java.lang.Thread.run(Thread.java:745)
```

**Comment by jasontedor** [comment]
I do not think we have seen this again, please correct me if that's wrong (but there should be other build failures recorded here, if so). The logs for this specific failure are cleaned up, so there's no information about this failure. I'm going to close this issue, we can reopen if it occurs again.
