### ISSUE TITLE
[TEST] DocsClientYamlTestSuiteIT test {yaml=reference/aggregations/metrics/scripted-metric-aggregation/line_56}

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#24112]
Test failure:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.4+multijob-unix-compatibility/os=fedora/8/console

Relevant log lines:

```
{yaml=reference/aggregations/metrics/scripted-metric-aggregation/line_56}]: after test
  1> [2017-04-14T17:32:30,611][INFO ][o.e.s.DocsClientYamlTestSuiteIT] Stash dump on failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "took" : 90,
  1>       "timed_out" : false,
  1>       "_shards" : {
  1>         "total" : 2,
  1>         "successful" : 1,
  1>         "failed" : 0
  1>       },
  1>       "hits" : {
  1>         "total" : 2,
  1>         "max_score" : 0.0,
  1>         "hits" : [ ]
  2> REPRODUCE WITH: gradle :docs:integTestRunner -Dtests.seed=81C3D7C8B4C92E7A -Dtests.class=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT -Dtests.method="test {yaml=reference/aggregations/metrics/scripted-metric-aggregation/line_56}" -Dtests.security.manager=true -Dtests.locale=sl -Dtests.timezone=Israel
  1>       },
  1>       "aggregations" : {
  1>         "profit" : {
  1>           "value" : 190.0
  1>         }
  1>       }
  1>     }
  1>   }
  1> }]
  1> [2017-04-14T17:32:30,612][ERROR][o.e.s.DocsClientYamlTestSuiteIT] This failing test was generated by documentation starting at reference/aggregations/metrics/scripted-metric-aggregation.asciidoc:line_56. It may include many snippets. See docs/README.asciidoc for an explanation of test generation.
FAILURE 0.54s | DocsClientYamlTestSuiteIT.test {yaml=reference/aggregations/metrics/scripted-metric-aggregation/line_56} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [reference/aggregations/metrics/scripted-metric-aggregation:137]: $body didn't match the expected value:
   >                          $body: 
   >                          _shards: 
   >                             failed: same [0]
   >                         successful: same [1]
   >                              total: same [2]
   >                     aggregations: 
   >                             profit: 
   >                                value: expected [240.0] but was [190.0]
   >                             hits: 
   >                               hits: same [empty list]
   >                          max_score: same [0.0]
   >                              total: same [2]
   >                        timed_out: same [false]
   >                             took: same [90]
   > 	at __randomizedtesting.SeedInfo.seed([81C3D7C8B4C92E7A:997E8121A354382]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:379)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:359)
   > 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by nik9000** [comment]
I'll have a look on Monday. Feel free to skip if it is consistent.

**Comment by nik9000** [comment]
```
  1>       "_shards" : {
  1>         "total" : 2,
  1>         "successful" : 1,
  1>         "failed" : 0
  1>       },
```

It lost half the docs.....

**Comment by nik9000** [comment]
This build has long since gone off the CI machine and I don't have enough information for now. It looks like the shard we wanted to query was not available and I don't have enough information to track down why.
