### ISSUE TITLE
[TEST] NPE in UpgradeClusterClientYamlTestSuiteIT#"Test rolling upgrade for stored scripts between the old namespace and the new namespace"

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#24139]
Does not reproduce for me.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-intake/1028/console

```
gradle :qa:rolling-upgrade:upgradedClusterTestRunner -Dtests.seed=159A8B0455457423 -Dtests.class=org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT -Dtests.method="test {p0=/10_basic/Test rolling upgrade for stored scripts between the old namespace and the new namespace}" -Dtests.security.manager=true -Dtests.locale=vi-VN -Dtests.timezone=America/Denver -Dtests.rest.suite=upgraded_cluster
```

```
java.lang.AssertionError: Failure at [/10_basic:139]: hits.total didn't match the expected value:
                    hits.total: expected [2] but was [1]

	at __randomizedtesting.SeedInfo.seed([159A8B0455457423:9DCEB4DEFBB919DB]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:379)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:359)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1713)
...
```

Seems to have been caused by an NPE with the script query:

```
[2017-04-17T13:06:34,138][INFO ][o.e.u.UpgradeClusterClientYamlTestSuiteIT] [test {p0=/10_basic/Test rolling upgrade for stored scripts between the old namespace and the new namespace}]: after test
  1> [2017-04-17T13:06:34,142][INFO ][o.e.u.UpgradeClusterClientYamlTestSuiteIT] Stash dump on failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "took" : 356,
  1>       "timed_out" : false,
  1>       "_shards" : {
  1>         "total" : 5,
  1>         "successful" : 4,
  1>         "failed" : 1,
  1>         "failures" : [
  1>           {
  1>             "shard" : 2,
  1>             "index" : "stored_index",
  1>             "node" : "wp5TNZyEQ_-TQjpzVjCTlQ",
  1>             "reason" : {
  1>               "type" : "null_pointer_exception",
  1>               "reason" : null
  1>             }
  1>           }
  1>         ]
  1>       },
  1>       "hits" : {
  1>         "total" : 1,
  1>         "max_score" : null,
  1>         "hits" : [
  1>           {
  1>             "_index" : "stored_index",
  1>             "_type" : "test",
  1>             "_id" : "AVt9TsgfS_0pphnPX_JH",
  1>             "_score" : null,
  1>             "fields" : {
  1>               "script_painless" : [
  1>                 3.0
  1>               ],
  1>               "script_expressions" : [
  1>                 3.0
  1>               ]
  1>             },
  1>             "sort" : [
  1>               3.0
  1>             ]
  1>           }
  1>         ]
  1>       }
  1>     }
  1>   }
  1> }]
```

```
org.elasticsearch.transport.RemoteTransportException: [wp5TNZy][127.0.0.1:42537][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: Query Failed [Failed to execute main query]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:414) ~[elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:108) ~[elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:246) ~[elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:260) ~[elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:331) ~[elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:328) ~[elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:627) [elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at org.apache.lucene.index.DocValues.docsWithValue(DocValues.java:186) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.codecs.lucene54.Lucene54DocValuesProducer.getDocsWithField(Lucene54DocValuesProducer.java:1101) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.codecs.perfield.PerFieldDocValuesFormat$FieldsReader.getDocsWithField(PerFieldDocValuesFormat.java:341) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.index.CodecReader.getDocsWithField(CodecReader.java:184) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.index.FilterLeafReader.getDocsWithField(FilterLeafReader.java:472) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.index.DocValues.getDocsWithField(DocValues.java:321) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.search.FieldComparator$NumericComparator.getDocsWithValue(FieldComparator.java:172) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.search.FieldComparator$NumericComparator.doSetNextReader(FieldComparator.java:155) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.search.SimpleFieldComparator.getLeafComparator(SimpleFieldComparator.java:36) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.search.FieldValueHitQueue.getComparators(FieldValueHitQueue.java:180) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.search.TopFieldCollector$SimpleFieldCollector.getLeafCollector(TopFieldCollector.java:100) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.search.FilterCollector.getLeafCollector(FilterCollector.java:40) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.elasticsearch.search.query.CancellableCollector.getLeafCollector(CancellableCollector.java:61) ~[elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:660) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:473) ~[lucene-core-6.5.0.jar:6.5.0 4b16c9a10c3c00cafaf1fc92ec3276a7bc7b8c95 - jimczi - 2017-03-21 20:40:22]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:388) ~[elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:108) ~[elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:246) ~[elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:260) ~[elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:331) ~[elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:328) ~[elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:627) ~[elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.5.0-SNAPSHOT.jar:5.5.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_121]
```

Which is weird, because that NPE seems to be here:

```java
  public static Bits docsWithValue(final SortedNumericDocValues dv, final int maxDoc) {
    return new Bits() {     // <---------- NPE
      @Override
      public boolean get(int index) {
        dv.setDocument(index);
        return dv.count() != 0;
      }

      @Override
      public int length() {
        return maxDoc;
      }
    };
  }
```

And I'm not sure how that NPEs?  This was on Fedora 25 / Java 1.8.0_121, perhaps this another one of those flaky NPE cases?  Assigning to @jpountz because it appears to be most directly Lucene related, but /cc @jasontedor because of NPE and @jdconrad because of stored scripts :)

**Comment by jasontedor** [comment]
Thanks for digging @polyfractal. I agree this is another spooky NPE and I don't think we need a separate issue for these as we are currently tracking it elsewhere.

**Comment by polyfractal** [comment]
:+1:
