### ISSUE TITLE
CI Failure: org.elasticsearch.recovery.RelocationIT testIndexAndRelocateConcurrently

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#24167]
Unable to reproduce locally.

CI Failure:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/852/consoleFull

Reproduce With:
gradle :core:integTest -Dtests.seed=4856A7A6357BA799 -Dtests.class=org.elasticsearch.recovery.RelocationIT -Dtests.method="testIndexAndRelocateConcurrently" -Dtests.security.manager=true -Dtests.locale=sk -Dtests.timezone=America/Argentina/Rio_Gallegos

**Comment by jdconrad** [comment]
@bleskes Will do.

**Comment by ywelsch** [comment]
The test encounters a local checkpoint mismatch, probably because the translog is missing an entry (replica cannot advance local checkpoint).

Relevant log lines:

```
   > Throwable #1: java.lang.AssertionError: Some expected ids were not found in search results: [ꩣꩺꩪ꩹ꩣ꩸ꩪꩿ꩸a180, եՍճՂմ֏ԽդՍa216, 𓇨𓏀𓆨𓈡aa238, ꓛꓵꓶꓘꓷꓑꓝꓼꓚa226, ㆴㆠㆳㆩㆢㆭㆾㆡㆠa137, 󠄱󠄼󠇗󠄝aa240, 🉢🉡🊪🈵aa126, 〚〄〼〻〃〳」〦〡a122, ᥃ᤔᤪ᤮ᤓ᥆᤿᥆᥉a149, 𐋘𐋒𐋀𐋟aa207, ꥧꥫꥧꥡꥴꥼꥹꥬꥳa206, ︉︁︌︆︀︊️︉︃a121, ╷╄┴┩╺┌┅╖╓a182]. Total shards: 3 Successful shards: 3 & 0 shard failures:
   > Expected: <0>
   >      but: was <13>
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertSearchHits(ElasticsearchAssertions.java:229)
   > 	at org.elasticsearch.recovery.RelocationIT.testIndexAndRelocateConcurrently(RelocationIT.java:512)
   > 	at java.lang.Thread.run(Thread.java:745)Throwable #2: java.lang.AssertionError: [test][0], node[g-azBk_eSQOcK9hsQcsYow], [R], s[STARTED], a[id=g7JRvvK8RAWPlZIKShHfIQ] local checkpoint mismatch
   > Expected: <73L>
   >      but: was <53L>
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.recovery.RelocationIT.lambda$beforeIndexDeletion$1(RelocationIT.java:132)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:711)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:685)
   > 	at org.elasticsearch.recovery.RelocationIT.beforeIndexDeletion(RelocationIT.java:116)
   > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:579)
   > 	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2058)
   > 	at java.lang.Thread.run(Thread.java:745)
   > 	Suppressed: java.lang.AssertionError: [test][0], node[g-azBk_eSQOcK9hsQcsYow], [R], s[STARTED], a[id=g7JRvvK8RAWPlZIKShHfIQ] local checkpoint mismatch
   > Expected: <73L>
   >      but: was <53L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.recovery.RelocationIT.lambda$beforeIndexDeletion$1(RelocationIT.java:132)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:699)
   > 		... 38 more
```

I'll have to dig deeper what's causing this /cc: @jasontedor 
More recent failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux/883/consoleFull

**Comment by ywelsch** [comment]
I've closely examined the failure here:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux/883/consoleFull

What is happening here is the following. We have 4 nodes:

```
{node_t0}{L3CpmEfoTMuwIFXLNEy4yA}{olvHdPIXRI-g6hl46IOImA}{127.0.0.1}{127.0.0.1:9400}{color=blue}, master
{node_t1}{OJ_UPhr4S8GEepzK3zNR1Q}{TV4yTxtKRxa_9oF_s9yWBw}{127.0.0.1}{127.0.0.1:9401}{color=blue}
{node_t2}{poCFuyO6Ss6wqlv_amKDKw}{ZWhmdAHmT2uQ9xM1WxSOIA}{127.0.0.1}{127.0.0.1:9402}{color=red}
{node_t3}{cYkbR4D_TCeQ6CxzlUd_RQ}{bgCrxqWzQvOfBWyYNOXW9A}{127.0.0.1}{127.0.0.1:9403}{color=red}
```

and are in a state where we have a relocating primary (from node_t2 to node_t0) together with a relocating replica (from node_t3 to node_t1):

```
cluster state version: 14
  --------[test][2], node[poCFuyO6Ss6wqlv_amKDKw], relocating [L3CpmEfoTMuwIFXLNEy4yA], [P], s[RELOCATING], a[id=iAUBqd0rSbyA-B9-f8mbRQ, rId=xKA60_nPQaWDi-sh9NvGHg]
  --------[test][2], node[cYkbR4D_TCeQ6CxzlUd_RQ], relocating [OJ_UPhr4S8GEepzK3zNR1Q], [R], s[RELOCATING], a[id=jrBmMQUoRb6gi1LniVy-3w, rId=mcc4_uPbQi-qmxM9jApG5A]
```

Primary relocation completes before the replica relocation, which means that replica recovery is cancelled by changing the allocation id of the replica relocation target (see #23926):

```
cluster state version: 15
  --------[test][2], node[L3CpmEfoTMuwIFXLNEy4yA], [P], s[STARTED], a[id=xKA60_nPQaWDi-sh9NvGHg]
  --------[test][2], node[cYkbR4D_TCeQ6CxzlUd_RQ], relocating [OJ_UPhr4S8GEepzK3zNR1Q], [R], s[RELOCATING], a[id=jrBmMQUoRb6gi1LniVy-3w, rId=7JPzU857TwepFt0r0Xkkpw]
```

This cluster state is first applied on the node that has the replica relocation target, which then removes the shard as the allocation id changed, creates a new initializing shard and restarts recovery from the new primary:

```
[2017-04-25T15:10:00,165][DEBUG][o.e.i.c.IndicesClusterStateService] [node_t1] [test][2] removing shard (stale allocation id, stale [test][2], node[OJ_UPhr4S8GEepzK3zNR1Q], relocating [cYkbR4D_TCeQ6CxzlUd_RQ], [R], recovery_source[peer recovery], s[INITIALIZING], a[id=mcc4_uPbQi-qmxM9jApG5A, rId=jrBmMQUoRb6gi1LniVy-3w], new [test][2], node[OJ_UPhr4S8GEepzK3zNR1Q], relocating [cYkbR4D_TCeQ6CxzlUd_RQ], [R], recovery_source[peer recovery], s[INITIALIZING], a[id=7JPzU857TwepFt0r0Xkkpw, rId=jrBmMQUoRb6gi1LniVy-3w])

[2017-04-25T15:10:00,173][TRACE][o.e.i.r.PeerRecoveryTargetService] [node_t1] [test][2] started recovery from {node_t0}{L3CpmEfoTMuwIFXLNEy4yA}{olvHdPIXRI-g6hl46IOImA}{127.0.0.1}{127.0.0.1:9400}{color=blue}, id [448]

[2017-04-25T15:10:00,175][TRACE][o.e.i.r.PeerRecoveryTargetService] [node_t1] [test][2] preparing for sequence-number-based recovery starting at local checkpoint [0] from [{node_t0}{L3CpmEfoTMuwIFXLNEy4yA}{olvHdPIXRI-g6hl46IOImA}{127.0.0.1}{127.0.0.1:9400}{color=blue}]
```

The new primary goes ahead with the recovery using sequence numbers:

```
[2017-04-25T15:10:00,175][TRACE][o.e.i.r.PeerRecoverySourceService] [node_t0] [test][2] starting recovery to {node_t1}{OJ_UPhr4S8GEepzK3zNR1Q}{TV4yTxtKRxa_9oF_s9yWBw}{127.0.0.1}{127.0.0.1:9401}{color=blue}

[2017-04-25T15:10:00,176][TRACE][o.e.i.r.RecoverySourceHandler] [node_t0] [test][2][recover to node_t1] performing sequence numbers based recovery. starting at [0]
```

Note that in contrast to recoveries that go through phase 1 (and call acquireIndexCommit), sequence number based recoveries (afaics) can be done on a shard that is not marked as STARTED yet. The critical part here is that node_t0 which is the primary relocation target has not applied the cluster state yet where it knows that the relocation successfully completed, it's shard state is currently in POST_RECOVERY. Another critical aspect is that recovery validation only checks that the recovery source node knows that there is an initializing shard on the recovery target node but does not check whether that shard has the correct allocation id. This means that the recovery source node thinks in this case that the recovery target on node_t1 has allocation id `mcc4_uPbQi-qmxM9jApG5A` instead of `7JPzU857TwepFt0r0Xkkpw`. This means that other index requests that arrive on the primary after the recovery is started, are replicated to node_t1 by using the wrong allocation id. This leads to an allocation mismatch failure on the target node:

```
[2017-04-25T15:10:00,195][TRACE][o.e.a.b.TransportShardBulkAction] [node_t0] [[test][2]] failure while performing [indices:data/write/bulk[s]] on replica [test][2], node[OJ_UPhr4S8GEepzK3zNR1Q], relocating [cYkbR4D_TCeQ6CxzlUd_RQ], [R], recovery_source[peer recovery], s[INITIALIZING], a[id=mcc4_uPbQi-qmxM9jApG5A, rId=jrBmMQUoRb6gi1LniVy-3w], request [BulkShardRequest [[test][2]] containing [index {[test][type1][ऺॺॻलु़ॊफॆa121], source[{"field1":"one hundred twenty-one "}]}]]
  1> org.elasticsearch.transport.RemoteTransportException: [node_t1][127.0.0.1:9401][indices:data/write/bulk[s][r]]
  1> Caused by: org.elasticsearch.index.shard.ShardNotFoundException: expected aID [mcc4_uPbQi-qmxM9jApG5A] but found [7JPzU857TwepFt0r0Xkkpw]
  1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncReplicaAction.doRun(TransportReplicationAction.java:568) ~[main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[main/:?]
  1> 	at ...
```

As this is a `ShardNotFoundException`, we just ignore it on the sender site (i.e. don't fail the target shard). This means that that write is not properly replicated to the target shard, resulting in the missing write on the replica:

```
> Throwable #1: java.lang.AssertionError: Some expected ids were not found in search results: [ऺॺॻलु़ॊफॆa121]. Total shards: 10 Successful shards: 10 & 0 shard failures:
   > Expected: <0>
   >      but: was <1>
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertSearchHits(ElasticsearchAssertions.java:229)
   > 	at org.elasticsearch.recovery.RelocationIT.testIndexAndRelocateConcurrently(RelocationIT.java:512)
   > 	at java.lang.Thread.run(Thread.java:745)Throwable #2: java.lang.AssertionError: [test][2], node[OJ_UPhr4S8GEepzK3zNR1Q], [R], s[STARTED], a[id=7JPzU857TwepFt0r0Xkkpw] local checkpoint mismatch
   > Expected: <21L>
   >      but: was <15L>
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.recovery.RelocationIT.lambda$beforeIndexDeletion$1(RelocationIT.java:132)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:711)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:685)
   > 	at org.elasticsearch.recovery.RelocationIT.beforeIndexDeletion(RelocationIT.java:116)
   > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:579)
   > 	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2057)
   > 	at java.lang.Thread.run(Thread.java:745)
   > 	Suppressed: java.lang.AssertionError: [test][2], node[OJ_UPhr4S8GEepzK3zNR1Q], [R], s[STARTED], a[id=7JPzU857TwepFt0r0Xkkpw] local checkpoint mismatch
   > Expected: <21L>
   >      but: was <15L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.recovery.RelocationIT.lambda$beforeIndexDeletion$1(RelocationIT.java:132)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:699)
   > 		... 38 more
   > 	Suppressed: java.lang.AssertionError: [test][2], node[OJ_UPhr4S8GEepzK3zNR1Q], [R], s[STARTED], a[id=7JPzU857TwepFt0r0Xkkpw] local checkpoint mismatch
   > Expected: <21L>
   >      but: was <15L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.recovery.RelocationIT.lambda$beforeIndexDeletion$1(RelocationIT.java:132)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:699)
   > 		... 38 more
```

I've opened #24333 as a fix
