### ISSUE TITLE
org.elasticsearch.http.netty4.Netty4ClientYamlTestSuiteIT.test fails

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#24189]
Example build failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.1+multijob-unix-compatibility/os=oraclelinux/206/consoleFull

Example trace:

```
ERROR   60.0s | Netty4ClientYamlTestSuiteIT.test {yaml=create/60_refresh/When refresh url parameter is an empty string that means "refresh immediately"} <<< FAILURES!
   > Throwable #1: java.io.IOException: listener timeout after waiting for [30000] ms
   > 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:617)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:184)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:163)
   > 	at org.elasticsearch.test.rest.yaml.ClientYamlTestClient.readMasterAndMinNodeVersion(ClientYamlTestClient.java:96)
   > 	at org.elasticsearch.test.rest.yaml.ClientYamlTestClient.<init>(ClientYamlTestClient.java:74)
   > 	at org.elasticsearch.test.rest.yaml.ClientYamlTestExecutionContext.initClient(ClientYamlTestExecutionContext.java:121)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.reset(ESClientYamlSuiteTestCase.java:248)
   > 	at java.lang.Thread.run(Thread.java:745)Throwable #2: java.io.IOException: listener timeout after waiting for [30000] ms
   > 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:617)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:184)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:146)
   > 	at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:167)
   > 	at org.elasticsearch.test.rest.ESRestTestCase.after(ESRestTestCase.java:123)
   > 	at java.lang.Thread.run(Thread.java:745)
```

* Branch 5.1
* Reproduction line: `REPRODUCE WITH: gradle :modules:transport-netty4:integTest -Dtests.seed=14C8E6DEC5497F59 -Dtests.class=org.elasticsearch.http.netty4.Netty4ClientYamlTestSuiteIT -Dtests.method="test {yaml=create/60_refresh/When refresh url parameter is an empty string that means "refresh immediately"}" -Dtests.security.manager=true -Dtests.locale=es-CR -Dtests.timezone=Antarctica/Troll` (does not reproduce locally)
* Frequency: This failure has never occurred in CI within the last year. It does not reproduce locally.

The trace above however just shows the victim. The real problem is that Netty is not responding. Attached are the [complete contents of the build folder](https://github.com/elastic/elasticsearch/files/935194/build-netty4.zip) in the Netty 4 module from the mentioned build.

Initially assigning to you Jason, but please feel free to reassign.

**Comment by jasontedor** [comment]
The JVM crashed with a segmentation fault in a compiler thread:

```
Current thread (0x00007fe37c167000):  JavaThread "C2 CompilerThread1" daemon [_thread_in_native, id=24642, stack(0x00007fe36c72b000,0x00007fe36c82c000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000000
```
