### ISSUE TITLE
gcs-repository snapshot creation times out systematically

### ISSUE THREAD

**Issue by thaDude** [elastic/elasticsearch#24192]
**Elasticsearch version**: 5.2.2
**Plugins installed**: x-pack, repository-gcs, custom update plugin
**JVM version**: 1.8.0_121
**OS version**: Debian 8.7

**Description of the problem including expected versus actual behavior**:
`gcs-repository` snapshot creation times out systematically after 20-30 mins with 1-2 shards of 63 not being snapshot correctly. It is not always the same index/shards that fail.

Repository configuration looks like:
```
{
  "type": "gcs",
  "settings": {
    "bucket": "backup.<replaced>.com",
    "service_account": "_default_",
    "base_path": "elasticsearch/snapshots-v5",
    "compress": "true",
    "max_snapshot_bytes_per_sec": "100mb"
  }
}
```

We never encountered this issue with filesystem-type snapshots. Total data size is ~180GB for 63 primary shards. We are not network bound when creating the snapshot. I am not sure the `max_snapshot_bytes_per_sec` value is taken into account for GCS snapshot creation but we are far from the 100mb/sec, typically between 20-40mb/sec. The cluster is typically not under heavy load at the time of snapshotting.

The logs look like:
```
elasticsearch[host-001][snapshot][T#3] WARN SnapshotShardsService - [[<idx_prefix_replaced>_4][0]] [gcs_repository:production-20170416/FRMNyP3cQ5Wac169TkoqCg] failed to create snapshot [<idx_prefix_replaced>_4/XUIEUgG-Q9yDguJXHHaVhw][[<idx_prefix_replaced>_4][0]] IndexShardSnapshotFailedException[Failed to perform snapshot (index files)]; nested: SocketTimeoutException[Read timed out];
    at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotContext.snapshot(BlobStoreRepository.java:1366)
    at org.elasticsearch.repositories.blobstore.BlobStoreRepository.snapshotShard(BlobStoreRepository.java:961)
    at org.elasticsearch.snapshots.SnapshotShardsService.snapshot(SnapshotShardsService.java:382)
    at org.elasticsearch.snapshots.SnapshotShardsService.access$200(SnapshotShardsService.java:88)
    at org.elasticsearch.snapshots.SnapshotShardsService$1.doRun(SnapshotShardsService.java:335)
    at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotContext.snapshotFile(BlobStoreRepository.java:1422)
    at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotContext.snapshot(BlobStoreRepository.java:1364)
elasticsearch[host-003][snapshot][T#3] WARN SnapshotShardsService - [[<idx_prefix_replaced>_0][2]] [gcs_repository:production-20170416/FRMNyP3cQ5Wac169TkoqCg] failed to create snapshot [<idx_prefix_replaced>_0/mij0Os3cQHK936GRI32VyQ][[<idx_prefix_replaced>_0][2]] IndexShardSnapshotFailedException[Failed to perform snapshot (index files)]; nested: GoogleJsonResponseException[503 Service Unavailable
    at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotContext.snapshot(BlobStoreRepository.java:1366)
    at org.elasticsearch.repositories.blobstore.BlobStoreRepository.snapshotShard(BlobStoreRepository.java:961)
    at org.elasticsearch.snapshots.SnapshotShardsService.snapshot(SnapshotShardsService.java:382)
    at org.elasticsearch.snapshots.SnapshotShardsService.access$200(SnapshotShardsService.java:88)
    at org.elasticsearch.snapshots.SnapshotShardsService$1.doRun(SnapshotShardsService.java:335)
    at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotContext.snapshotFile(BlobStoreRepository.java:1422)
    at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotContext.snapshot(BlobStoreRepository.java:1364)
elasticsearch[host-004][clusterService#updateTask][T#1] INFO SnapshotShardsService - snapshot [gcs_repository:production-20170416/FRMNyP3cQ5Wac169TkoqCg] is done
```

and the snapshot REST API confirms this:
```
{
  "snapshots": [
    {
      "snapshot": "production-20170416",
      "uuid": "FRMNyP3cQ5Wac169TkoqCg",
      "version_id": 5020299,
      "version": "5.2.2",
      "indices": [
        <index>
      ],
      "state": "PARTIAL",
      "start_time": "2017-04-16T03:25:01.398Z",
      "start_time_in_millis": 1492313101398,
      "end_time": "2017-04-16T03:45:05.453Z",
      "end_time_in_millis": 1492314305453,
      "duration_in_millis": 1204055,
      "failures": [
        {
          "index": "<idx_prefix_replaced>_4",
          "index_uuid": "<idx_prefix_replaced>_4",
          "shard_id": 0,
          "reason": "IndexShardSnapshotFailedException[Failed to perform snapshot (index files)]; nested: SocketTimeoutException[Read timed out]; ",
          "node_id": "fgf_Y7ZiQBSYmTg7vOeiHw",
          "status": "INTERNAL_SERVER_ERROR"
        },
        {
          "index": "<idx_prefix_replaced>_0",
          "index_uuid": "<idx_prefix_replaced>_0",
          "shard_id": 2,
          "reason": "IndexShardSnapshotFailedException[Failed to perform snapshot (index files)]; nested: GoogleJsonResponseException[503 Service Unavailable\nService Unavailable]; ",
          "node_id": "d1yE_amoTu6XF-6cPuL7SQ",
          "status": "INTERNAL_SERVER_ERROR"
        }
      ],
      "shards": {
        "total": 63,
        "failed": 2,
        "successful": 61
      }
    }
  ]
}
```

I inquired in the discussion [group](https://discuss.elastic.co/t/snapshot-to-gcs-repository-times-out/82768) without much success.

**Comment by abeyad** [comment]
@thaDude I responded on the discussion forum post, so I'm closing this one as we reserve github for confirmed bug reports and feature requests, so we can re-open this if we determine that you're issue is a bug in Elasticsearch itself.
