### ISSUE TITLE
run the elasticsearch source code in eclipse,console print:Unsupported transport.type []

### ISSUE THREAD

**Issue by liuguangmin** [elastic/elasticsearch#24199]
**Elasticsearch version**:5.3.0

**Plugins installed**: []

**JVM version**:1.8.0_121

**OS version**:win7

l get elasticsearch source code(gradle project) import eclipse(my eclipse is neo.3 release)
when i run org.elasticsearch.bootstrap.Elasticsearch.main()method in eclipse 
the console printf:
[2017-04-20T10:21:35,231][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Unsupported transport.type []
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[1/:?]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[1/:?]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[1/:?]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[1/:?]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[1/:?]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[1/:?]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[1/:?]
Caused by: java.lang.IllegalStateException: Unsupported transport.type []
	at org.elasticsearch.common.network.NetworkModule.getTransportSupplier(NetworkModule.java:211) ~[1/:?]
	at org.elasticsearch.node.Node.<init>(Node.java:406) ~[1/:?]
	at org.elasticsearch.node.Node.<init>(Node.java:236) ~[1/:?]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:221) ~[1/:?]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[1/:?]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:339) ~[1/:?]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[1/:?]
	... 6 more
2017-04-20 10:21:35,243 Thread-4 ERROR Could not unregister MBeans for org.apache.logging.log4j2:type=73d16e93 java.security.AccessControlException: access denied ("javax.management.MBeanPermission" "-#-[-]" "queryNames")
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.security.AccessController.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:335)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:259)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:247)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:338)
	at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:136)
	at org.apache.logging.log4j.core.config.Configurator.shutdown(Configurator.java:344)
	at org.elasticsearch.bootstrap.Bootstrap$5.run(Bootstrap.java:196)

2017-04-20 10:21:35,246 Thread-4 ERROR Could not unregister MBeans for org.apache.logging.log4j2:type=73d16e93,component=StatusLogger java.security.AccessControlException: access denied ("javax.management.MBeanPermission" "-#-[-]" "queryNames")
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.security.AccessController.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:335)
	at org.apache.logging.log4j.core.jmx.Server.unregisterStatusLogger(Server.java:288)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:262)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:247)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:338)
	at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:136)
	at org.apache.logging.log4j.core.config.Configurator.shutdown(Configurator.java:344)
	at org.elasticsearch.bootstrap.Bootstrap$5.run(Bootstrap.java:196)

2017-04-20 10:21:35,249 Thread-4 ERROR Could not unregister MBeans for org.apache.logging.log4j2:type=73d16e93,component=ContextSelector java.security.AccessControlException: access denied ("javax.management.MBeanPermission" "-#-[-]" "queryNames")
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.security.AccessController.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:335)
	at org.apache.logging.log4j.core.jmx.Server.unregisterContextSelector(Server.java:293)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:263)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:247)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:338)
	at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:136)
	at org.apache.logging.log4j.core.config.Configurator.shutdown(Configurator.java:344)
	at org.elasticsearch.bootstrap.Bootstrap$5.run(Bootstrap.java:196)

2017-04-20 10:21:35,255 Thread-4 ERROR Could not unregister MBeans for org.apache.logging.log4j2:type=73d16e93,component=Loggers,name=* java.security.AccessControlException: access denied ("javax.management.MBeanPermission" "-#-[-]" "queryNames")
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.security.AccessController.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:335)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerConfigs(Server.java:299)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:264)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:247)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:338)
	at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:136)
	at org.apache.logging.log4j.core.config.Configurator.shutdown(Configurator.java:344)
	at org.elasticsearch.bootstrap.Bootstrap$5.run(Bootstrap.java:196)

2017-04-20 10:21:35,257 Thread-4 ERROR Could not unregister MBeans for org.apache.logging.log4j2:type=73d16e93,component=Appenders,name=* java.security.AccessControlException: access denied ("javax.management.MBeanPermission" "-#-[-]" "queryNames")
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.security.AccessController.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:335)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAppenders(Server.java:311)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:265)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:247)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:338)
	at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:136)
	at org.apache.logging.log4j.core.config.Configurator.shutdown(Configurator.java:344)
	at org.elasticsearch.bootstrap.Bootstrap$5.run(Bootstrap.java:196)

2017-04-20 10:21:35,258 Thread-4 ERROR Could not unregister MBeans for org.apache.logging.log4j2:type=73d16e93,component=AsyncAppenders,name=* java.security.AccessControlException: access denied ("javax.management.MBeanPermission" "-#-[-]" "queryNames")
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.security.AccessController.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:335)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAsyncAppenders(Server.java:317)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:266)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:247)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:338)
	at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:136)
	at org.apache.logging.log4j.core.config.Configurator.shutdown(Configurator.java:344)
	at org.elasticsearch.bootstrap.Bootstrap$5.run(Bootstrap.java:196)

2017-04-20 10:21:35,259 Thread-4 ERROR Could not unregister MBeans for org.apache.logging.log4j2:type=73d16e93,component=AsyncLoggerRingBuffer java.security.AccessControlException: access denied ("javax.management.MBeanPermission" "-#-[-]" "queryNames")
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.security.AccessController.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:335)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAsyncLoggerRingBufferAdmins(Server.java:323)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:267)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:247)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:338)
	at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:136)
	at org.apache.logging.log4j.core.config.Configurator.shutdown(Configurator.java:344)
	at org.elasticsearch.bootstrap.Bootstrap$5.run(Bootstrap.java:196)

2017-04-20 10:21:35,264 Thread-4 ERROR Could not unregister MBeans for org.apache.logging.log4j2:type=73d16e93,component=Loggers,name=*,subtype=RingBuffer java.security.AccessControlException: access denied ("javax.management.MBeanPermission" "-#-[-]" "queryNames")
	at java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.security.AccessController.checkPermission(Unknown Source)
	at java.lang.SecurityManager.checkPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanPermission(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.queryNames(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.queryNames(Unknown Source)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAllMatching(Server.java:335)
	at org.apache.logging.log4j.core.jmx.Server.unregisterAsyncLoggerConfigRingBufferAdmins(Server.java:329)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:268)
	at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:247)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:338)
	at org.apache.logging.log4j.core.AbstractLifeCycle.stop(AbstractLifeCycle.java:136)
	at org.apache.logging.log4j.core.config.Configurator.shutdown(Configurator.java:344)
	at org.elasticsearch.bootstrap.Bootstrap$5.run(Bootstrap.java:196)

============================================================

I remember 5.0.1 source code can run without Unsupported transport.type []
so I want to know how to solve the problem ,or the config change ?

**Comment by jasontedor** [comment]
If you try to run it like this, you won't have any modules on the classpath that provide a networking implementation. The security manager violations come from not having a jvm.options file that disables Log4j 2 from using JMX.

**Comment by jasontedor** [comment]
Also, the reason that it worked in 5.0.1 but not in 5.1.1 and beyond is because we removed local transport which provided a default implementation.

**Comment by kkewwei** [comment]
can you tell me details about the solution? I have spent too much  on solving it. very think you

**Comment by kkewwei** [comment]
ok, I solve it.

**Comment by sscarduzio** [comment]
how?

**Comment by kkewwei** [comment]
I see the source code and knows that the code loading those plugins is in node.java, In node.java, es will load plugin from ${path.home}/modules, so I copy the modules dictory from root code to it ,and it is solved.
