### ISSUE TITLE
DiscoveryWithServiceDisruptionsIT.testIsolatedUnicastNodes: failed to reach a stable cluster of [4] nodes

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#24191]
Example build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.1+multijob-unix-compatibility/os=debian/206/consoleFull

Exception trace:

```
Throwable #1: java.lang.AssertionError: failed to reach a stable cluster of [4] nodes. Tried via [node_t2]. last cluster state:
   > cluster uuid: uCBnqun0Rt6pT9075k3bgQ
   > version: 4
   > state uuid: QbFJ3nVbTPOdsXs8yVJHhw
   > from_diff: false
   > meta data version: 1
   > nodes: 
   >    {node_t3}{v6CU-mFHTdKrOjajuwUeNg}{OFA4l360QROJaZcxNIgvbQ}{127.0.0.1}{127.0.0.1:30217}
   >    {node_t2}{HvyZwyynRLqpOG6podHBNQ}{LZIeAY3AQXyGFb6xBUa17Q}{127.0.0.1}{127.0.0.1:30216}, local, master
   >    {node_t1}{iIRj_lzhTjGDo_tsXqHrLw}{xPOVpPyoRvmYHSnEs4ScFA}{127.0.0.1}{127.0.0.1:30215}
   > routing_table (version 1):
   > routing_nodes:
   > -----node_id[iIRj_lzhTjGDo_tsXqHrLw][V]
   > -----node_id[v6CU-mFHTdKrOjajuwUeNg][V]
   > -----node_id[HvyZwyynRLqpOG6podHBNQ][V]
   > ---- unassigned
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureStableCluster(ESIntegTestCase.java:1125)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureStableCluster(ESIntegTestCase.java:1104)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureStableCluster(ESIntegTestCase.java:1100)
   > 	at org.elasticsearch.discovery.DiscoveryWithServiceDisruptionsIT.testIsolatedUnicastNodes(DiscoveryWithServiceDisruptionsIT.java:919)
   > 	at java.lang.Thread.run(Thread.java:745)Throwable #2: java.lang.AssertionError: cluster failed to form after disruption was healed
   > 	at org.elasticsearch.test.disruption.NetworkDisruption.ensureNodeCount(NetworkDisruption.java:86)
   > 	at org.elasticsearch.test.disruption.NetworkDisruption.removeAndEnsureHealthy(NetworkDisruption.java:82)
   > 	at org.elasticsearch.test.InternalTestCluster.clearDisruptionScheme(InternalTestCluster.java:1795)
   > 	at org.elasticsearch.test.InternalTestCluster.clearDisruptionScheme(InternalTestCluster.java:1787)
   > 	at org.elasticsearch.test.ESIntegTestCase.clearDisruptionScheme(ESIntegTestCase.java:672)
   > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:529)
   > 	at org.elasticsearch.test.ESIntegTestCase.after(ESIntegTestCase.java:2004)
   > 	at java.lang.Thread.run(Thread.java:745)
```

* branch: 5.1
* reproduction line: `gradle :core:integTest -Dtests.seed=5DB24F622A86708D -Dtests.class=org.elasticsearch.discovery.DiscoveryWithServiceDisruptionsIT -Dtests.method="testIsolatedUnicastNodes" -Dtests.security.manager=true -Dtests.locale=en-NZ -Dtests.timezone=Brazil/DeNoronha'`
* reproducability: does not reproduce locally; failed 35 times within the last year in CI

Attached is the [full build log](https://github.com/elastic/elasticsearch/files/935409/build_log.txt).

**Comment by ywelsch** [comment]
After a network disruption was healed, the node that was separated from the cluster did not rejoin it, as it previously was the master and batch-removed all nodes from its cluster state when it got partitioned away. As it only had itself on the unicast ping list, it could not find the nodes of the previous cluster. This behavior has been changed/fixed in 5.2 (the node does not make changes to disco-nodes list when it is not master anymore): https://github.com/elastic/elasticsearch/pull/21092
