### ISSUE TITLE
when I run the elasticsearch source, the console is print version [6.0.0-alpha1-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production

### ISSUE THREAD

**Issue by liuguangmin** [elastic/elasticsearch#24228]
@jasontedor 

hi jason ,yesterday(China) I have ask you a question about run the elasticsearch source code in my local eclipse,
my elasticsearch : 5.3.0
     jdk:1.8 
     system:win7
I do allow this step:
(1) import elasticsearch 5.3.0 source code into eclipse
(2) I down executable file from https://www.elastic.co/downloads/elasticsearch, I down the file is elasticsearch-5.3.0.zip ,I copy the file modules  from elasticsearch-5.3.0.zip  to my source code's config path 
(3) run the source code 

the following print in console is：
============================================================
[2017-04-21T10:40:26,766][INFO ][o.e.n.Node               ] [] initializing ...
[2017-04-21T10:40:27,143][INFO ][o.e.e.NodeEnvironment    ] [mdkCxIS] using [1] data paths, mounts [[Windows7_OS (C:)]], net usable_space [130.2gb], net total_space [224.2gb], spins? [unknown], types [NTFS]
[2017-04-21T10:40:27,144][INFO ][o.e.e.NodeEnvironment    ] [mdkCxIS] heap size [1.7gb], compressed ordinary object pointers [true]
[2017-04-21T10:40:27,149][INFO ][o.e.n.Node               ] node name [mdkCxIS] derived from node ID [mdkCxISESYOK28TdFhYI1A]; set [node.name] to override
[2017-04-21T10:40:27,149][INFO ][o.e.n.Node               ] version[6.0.0-alpha1-SNAPSHOT], pid[200564], build[Unknown/Unknown], OS[Windows 7/6.1/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_131/25.131-b11]
# [2017-04-21T10:40:27,151][WARN ][o.e.n.Node               ] version [6.0.0-alpha1-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
[2017-04-21T10:40:27,202][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: plugin [aggs-matrix-stats] is incompatible with version [6.0.0-alpha1]; was designed for version [5.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[1/:?]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[1/:?]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[1/:?]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[1/:?]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[1/:?]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[1/:?]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[1/:?]
Caused by: java.lang.IllegalArgumentException: plugin [aggs-matrix-stats] is incompatible with version [6.0.0-alpha1]; was designed for version [5.3.0]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146) ~[1/:?]
	at org.elasticsearch.plugins.PluginsService.getModuleBundles(PluginsService.java:273) ~[1/:?]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:117) ~[1/:?]
	at org.elasticsearch.node.Node.<init>(Node.java:294) ~[1/:?]
	at org.elasticsearch.node.Node.<init>(Node.java:236) ~[1/:?]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:221) ~[1/:?]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[1/:?]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:339) ~[1/:?]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[1/:?]
	... 6 more
===============================================================[2017- # 04-21T10:40:27,151][WARN ][o.e.n.Node               ] version [6.0.0-alpha1-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production

 so I question this the version [6.0.0-alpha1-SNAPSHOT] is what ？  Is the plugin [aggs-matrix-stats] 

but I get the plugin-descriptor.properties:
description=Adds aggregations whose input are a list of numeric fields and output includes a matrix.
#
# 'version': plugin's version
version=5.3.0
#
# 'name': the plugin name
name=aggs-matrix-stats
#
# 'classname': the name of the class to load, fully-qualified.
classname=org.elasticsearch.search.aggregations.matrix.MatrixAggregationPlugin
#
# 'java.version' version of java the code is built against
# use the system property java.specification.version
# version string must be a sequence of nonnegative decimal integers
# separated by "."'s and may have leading zeros
java.version=1.8
#
# 'elasticsearch.version' version of elasticsearch compiled against
elasticsearch.version=5.3.0
====
so i strange ?

**Comment by jasontedor** [comment]
Please don't ping people directly. Please post questions on the forum. Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by liuguangmin** [comment]
sorry sorry
