### ISSUE TITLE
When I run the elasticsearch source, theconsole is print version [6.0.0-alpha1-SNAPSHOT] is a pre-release version ofElasticsearch and is not suitable for production

### ISSUE THREAD

**Issue by liuguangmin** [elastic/elasticsearch#24246]
hi Team , I have ask your a question about run the elasticsearch source code in my local eclipse,
my elasticsearch : 5.3.0
jdk:1.8
system:win7
I do allow this step:
(1) import elasticsearch 5.3.0 source code into eclipse
(2) I down executable file from https://www.elastic.co/downloads/elasticsearch, I down the file is elasticsearch-5.3.0.zip ,I copy the file modules from elasticsearch-5.3.0.zip to my source code's config path
(3) run the source code

the following print in console is：

[2017-04-21T10:40:26,766][INFO ][o.e.n.Node ] [] initializing ...
[2017-04-21T10:40:27,143][INFO ][o.e.e.NodeEnvironment ] [mdkCxIS] using [1] data paths, mounts [[Windows7_OS (C:)]], net usable_space [130.2gb], net total_space [224.2gb], spins? [unknown], types [NTFS]
[2017-04-21T10:40:27,144][INFO ][o.e.e.NodeEnvironment ] [mdkCxIS] heap size [1.7gb], compressed ordinary object pointers [true]
[2017-04-21T10:40:27,149][INFO ][o.e.n.Node ] node name [mdkCxIS] derived from node ID [mdkCxISESYOK28TdFhYI1A]; set [node.name] to override
[2017-04-21T10:40:27,149][INFO ][o.e.n.Node ] version[6.0.0-alpha1-SNAPSHOT], pid[200564], build[Unknown/Unknown], OS[Windows 7/6.1/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_131/25.131-b11]

[2017-04-21T10:40:27,151][WARN ][o.e.n.Node ] version [6.0.0-alpha1-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production

[2017-04-21T10:40:27,202][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: plugin [aggs-matrix-stats] is incompatible with version [6.0.0-alpha1]; was designed for version [5.3.0]
at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[1/:?]
at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[1/:?]
at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[1/:?]
at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[1/:?]
at org.elasticsearch.cli.Command.main(Command.java:88) ~[1/:?]
at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[1/:?]
at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[1/:?]
Caused by: java.lang.IllegalArgumentException: plugin [aggs-matrix-stats] is incompatible with version [6.0.0-alpha1]; was designed for version [5.3.0]
at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146) ~[1/:?]
at org.elasticsearch.plugins.PluginsService.getModuleBundles(PluginsService.java:273) ~[1/:?]
at org.elasticsearch.plugins.PluginsService.(PluginsService.java:117) ~[1/:?]
at org.elasticsearch.node.Node.(Node.java:294) ~[1/:?]
at org.elasticsearch.node.Node.(Node.java:236) ~[1/:?]
at org.elasticsearch.bootstrap.Bootstrap$6.(Bootstrap.java:221) ~[1/:?]
at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[1/:?]
at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:339) ~[1/:?]
at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[1/:?]
... 6 more
===============================================================[2017- 04-21T10:40:27,151][WARN ][o.e.n.Node ] version [6.0.0-alpha1-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production

so I question this the version [6.0.0-alpha1-SNAPSHOT] is what ？ Is the plugin [aggs-matrix-stats]

but I get the plugin-descriptor.properties:
Elasticsearch plugin descriptor file
description=Adds aggregations whose input are a list of numeric fields and output includes a matrix.
version=5.3.0
name=aggs-matrix-stats
classname=org.elasticsearch.search.aggregations.matrix.MatrixAggregationPlugin
java.version=1.8
elasticsearch.version=5.3.0
so i strange ?

**Comment by jasontedor** [comment]
I don't understand why you keep posting the same question despite my request that you post this on [forum](https://discuss.elastic.co). I think that you're running against master with modules that were built against 5.3.0, that is flat out not going to work. Again, we reserve GitHub for bugs and feature requests, you can use the forum for questions.

**Comment by liuguangmin** [comment]
this is because today I following you advise put the problem to the formum , but nobody response.what's more I can run the executable file is normal but the source code is run  unnormal,the modules is same,
I compile the modules source ,and put the jar to the source code ,but the question is alive, I solve the problem a day ,but I can find a best way , so I think this is may be a source code problem

**Comment by liuguangmin** [comment]
so great sorry

**Comment by jasontedor** [comment]
> this is because today I following you advise put the problem to the formum , but nobody response.

I found your [post](https://discuss.elastic.co/t/when-i-run-the-elasticsearch-source-theconsole-is-print-version-6-0-0-alpha1-snapshot-is-a-pre-release-version-ofelasticsearch-and-is-not-suitable-for-production/83140), it's from eleven hours ago. There is no SLA on the forum, your expectation that you receive a response so quickly, or even at all, is not reasonable and needs to adjusted. Please follow our community guidelines.

**Comment by jasontedor** [comment]
Please see our [guidelines](https://www.elastic.co/community/codeofconduct):

> **Be patient.** This mostly applies to forums, mailing lists, and code contributions (i.e. asynchronous forms of communication). Communities are often built on volunteer time both from participants and organizers. It is possible that your question or code contribution or suggestion might not receive an immediate response. Be patient and consider the norms of the community. One reminder ping is welcome, many reminder pings in rapid succession are not a good display of patience. Similarly, posting the same question in multiple threads is frowned upon and should not be done.

**Comment by liuguangmin** [comment]
OK great sorry ，I will follow our community guidelines.THX,
Forgive me before failing to comply with community regulations， I will remeber and obey the guidelines
