### ISSUE TITLE
Referencing _score in scripted metric causes NullPointerException

### ISSUE THREAD

**Issue by winstonewert** [elastic/elasticsearch#24259]
**Elasticsearch version**: 5.3.1

**Plugins installed**:  None

**JVM version**: openjdk version "1.8.0_111"

**OS version**: Ubuntu 16.04.1 LTS

**Description of the problem including expected versus actual behavior**:

I send the following query:

```
    {
      "query": {
        "match_phrase": {
          "text": {
            "query": "apples"
          }
        }
      },
      "aggs": {
        "score_total": {
          "scripted_metric": {
            "init_script": "params._agg.total = 0",
            "map_script": "params._agg.total += _score",
            "combine_script": "return params._agg.total",
            "reduce_script": "double total = 0; for (a in params._aggs) { total += a } return total"
          }
        }
      }
    }

```
I expect it to give me a total over all the scores, Instead I get:

```
{
  "took": 5,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 4,
    "failed": 1,
    "failures": [
      {
        "shard": 2,
        "index": "ewert-small",
        "node": "PJJPkWJ4Q1GnvBo50Ml0zQ",
        "reason": {
          "type": "script_exception",
          "reason": "runtime error",
          "script_stack": [
            "<<< unknown portion of script >>>"
          ],
          "script": "params._agg.total += _score",
          "lang": "painless",
          "caused_by": {
            "type": "null_pointer_exception",
            "reason": null
          }
        }
      }
    ]
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  },
  "aggregations": {
    "score_total": {
      "value": 0
    }
  }
}
```
Sample from the log:
```
org.elasticsearch.transport.RemoteTransportException: [PJJPkWJ][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: Query Failed [Failed to execute main query]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:423) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:108) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:247) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:261) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:331) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:328) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:618) [elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.3.1.jar:5.3.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: org.elasticsearch.script.ScriptException: runtime error
	at org.elasticsearch.painless.ScriptImpl.convertToScriptException(ScriptImpl.java:181) ~[?:?]
	at org.elasticsearch.painless.ScriptImpl.run(ScriptImpl.java:128) ~[?:?]
	at org.elasticsearch.search.aggregations.metrics.scripted.ScriptedMetricAggregator$1.collect(ScriptedMetricAggregator.java:71) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:82) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.apache.lucene.search.MultiCollector$MultiLeafCollector.collect(MultiCollector.java:174) ~[lucene-core-6.4.2.jar:6.4.2 34a975ca3d4bd7fa121340e5bcbf165929e0542f - ishan - 2017-03-01 23:23:13]
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:221) ~[lucene-core-6.4.2.jar:6.4.2 34a975ca3d4bd7fa121340e5bcbf165929e0542f - ishan - 2017-03-01 23:23:13]
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:172) ~[lucene-core-6.4.2.jar:6.4.2 34a975ca3d4bd7fa121340e5bcbf165929e0542f - ishan - 2017-03-01 23:23:13]
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39) ~[lucene-core-6.4.2.jar:6.4.2 34a975ca3d4bd7fa121340e5bcbf165929e0542f - ishan - 2017-03-01 23:23:13]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:669) ~[lucene-core-6.4.2.jar:6.4.2 34a975ca3d4bd7fa121340e5bcbf165929e0542f - ishan - 2017-03-01 23:23:13]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:473) ~[lucene-core-6.4.2.jar:6.4.2 34a975ca3d4bd7fa121340e5bcbf165929e0542f - ishan - 2017-03-01 23:23:13]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:397) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:108) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:247) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:261) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:331) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:328) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:618) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.3.1.jar:5.3.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at org.elasticsearch.painless.Executable$Script.execute(params._agg.total += _score) ~[?:?]
	at org.elasticsearch.painless.ScriptImpl.run(ScriptImpl.java:123) ~[?:?]
	at org.elasticsearch.search.aggregations.metrics.scripted.ScriptedMetricAggregator$1.collect(ScriptedMetricAggregator.java:71) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:82) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.apache.lucene.search.MultiCollector$MultiLeafCollector.collect(MultiCollector.java:174) ~[lucene-core-6.4.2.jar:6.4.2 34a975ca3d4bd7fa121340e5bcbf165929e0542f - ishan - 2017-03-01 23:23:13]
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:221) ~[lucene-core-6.4.2.jar:6.4.2 34a975ca3d4bd7fa121340e5bcbf165929e0542f - ishan - 2017-03-01 23:23:13]
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:172) ~[lucene-core-6.4.2.jar:6.4.2 34a975ca3d4bd7fa121340e5bcbf165929e0542f - ishan - 2017-03-01 23:23:13]
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39) ~[lucene-core-6.4.2.jar:6.4.2 34a975ca3d4bd7fa121340e5bcbf165929e0542f - ishan - 2017-03-01 23:23:13]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:669) ~[lucene-core-6.4.2.jar:6.4.2 34a975ca3d4bd7fa121340e5bcbf165929e0542f - ishan - 2017-03-01 23:23:13]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:473) ~[lucene-core-6.4.2.jar:6.4.2 34a975ca3d4bd7fa121340e5bcbf165929e0542f - ishan - 2017-03-01 23:23:13]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:397) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:108) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:247) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:261) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:331) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:328) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:618) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-5.3.1.jar:5.3.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.3.1.jar:5.3.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_111]
```

**Comment by NatKarmios** [comment]
I'd be happy to take a look at it.

**Comment by winstonewert** [comment]
I went ahead an attached a debug to my elasticsearch instance, and I believe I've found the problem:

https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/aggregations/metrics/scripted/ScriptedMetricAggregator.java#L66

The mapScript parameter should be leafMapScript. The LeafBucketCollectorBase ignore the values parameter unless it implements ScorerAware. LeafMapScript implements it, but mapScript does not.

**Comment by colings86** [comment]
Could you explain your use-case a bit? Combining scores in an aggregation is not generally that useful as the value of a document's score is not meaningful outside of being compared to another document's scores. 

Also, in your case it seems like you could use the sum aggregation with a script returning the score to achieve the same result as you are trying to do with the scripted_metric aggregation here. Something like:
```
"total_score": {
  "sum": {
    "script": "_score"
  }
}
```

I'm hesitant to enable the score to be accessed in this aggregation since its not clear to me why it would be useful to aggregate on the score in any aggregation least of all this one?

**Comment by winstonewert** [comment]
Obviously, the aggregation presented in the example is really silly. Its a bug report, I'm showing the simplest case that fails.

My actual case involves aggregating the score into different buckets (possibly multiple per document) based on the other fields in the document.

You can already aggregate over the scores using the non-scripted metrics, so it makes little sense to me to object to doing so in a scripted metric. 

As you can see from my diagnosis above and my pull request fixing the bug, it looks like the code is trying to make scores in script metric works, but fails to do so because of a typo.

**Comment by colings86** [comment]
> Obviously, the aggregation presented in the example is really silly. Its a bug report, I'm showing the simplest case that fails.

Ok, fair enough. I was asking because I am interested to know of a use case that aggregates scores and in that use case what those aggregated scores represent which is useful/meaningful.

> You can already aggregate over the scores using the non-scripted metrics, so it makes little sense to me to object to doing so in a scripted metric.

This is true. I guess my point here was whether it actually makes sense for aggregations on scores to be supported in any aggregation, but thats probably better left for a separate issue. 

> As you can see from my diagnosis above and my pull request fixing the bug, it looks like the code is trying to make scores in script metric works, but fails to do so because of a typo.

I hadn't seen your [PR](https://github.com/elastic/elasticsearch/pull/24295), thanks for raising one. Looking at the history of the file it looks like https://github.com/elastic/elasticsearch/commit/967a4e2a861b703706540b5c61b54d659b5a3e58 
may have stopped the scores from being accessible from the scripted_metric aggregator but wasn't picked up because as we did not see the score being useful for this aggregation so it was never considered/tested. I'll review your PR and hopefully we can get it in.
