### ISSUE TITLE
[TEST] Failures on NFS due to requests not being acked

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#24304]
Build URL:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+nfs/204/consoleFull

There are two failures in `AliasRoutingIT` here but they are probably related so I put them in one issue. This test in on NFS so I assume that is a factor here given I can't reproduce this locally. It should also be noted that after this test was run other tests ran but then a node in the test cluster appeared to die with errors like:

```
org.apache.lucene.store.AlreadyClosedException: FileLock invalidated by an external force: 
NativeFSLock(path=/var/lib/jenkins/workspace/elastic+elasticsearch+master+nfs/core/build/testrun/integTest/J1/temp/org.elasticsearch.search.child.ChildQuerySearchIT_2FF077E78FBAE61
-001/tempDir-002/data/nodes/0/node.lock,impl=sun.nio.ch.FileLockImpl[0:9223372036854775807 exclusive invalid],creationTime=2017-04-25T04:19:56.298Z)
```

I'm unsure if this is related or not.

Reproduce commands (cannot reproduce locally):
```
gradle :core:integTest -Dtests.seed=2FF077E78FBAE61 -Dtests.class=org.elasticsearch.routing.AliasRoutingIT -Dtests.method="testAliasSearchRouting" -Dtests.security.manager=true -Dtests.locale=ar-SY -Dtests.timezone=US/Pacific
```
```
gradle :core:integTest -Dtests.seed=2FF077E78FBAE61 -Dtests.class=org.elasticsearch.routing.AliasRoutingIT -Dtests.method="testAliasSearchRoutingWithConcreteAndAliasedIndices_issue3268" -Dtests.security.manager=true -Dtests.locale=ar-SY -Dtests.timezone=US/Pacific
```

Stack traces:
```
  2> REPRODUCE WITH: gradle :core:integTest -Dtests.seed=2FF077E78FBAE61 -Dtests.class=org.elasticsearch.routing.AliasRoutingIT -Dtests.method="testAliasSearchRouting" -Dtests.security.manager=true -Dtests.locale=ar-SY -Dtests.timezone=US/Pacific
FAILURE  129s J1 | AliasRoutingIT.testAliasSearchRouting <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Delete Index failed - not acked
   > Expected: <true>
   >      but: was <false>
   > 	at __randomizedtesting.SeedInfo.seed([2FF077E78FBAE61:34C1D692D180424A]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:131)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:127)
   > 	at org.elasticsearch.test.TestCluster.wipeIndices(TestCluster.java:140)
   > 	at org.elasticsearch.test.TestCluster.wipe(TestCluster.java:77)
   > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:580)
   > 	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2057)
   > 	at java.lang.Thread.run(Thread.java:745)
```
```
  2> REPRODUCE WITH: gradle :core:integTest -Dtests.seed=2FF077E78FBAE61 -Dtests.class=org.elasticsearch.routing.AliasRoutingIT -Dtests.method="testAliasSearchRoutingWithConcreteAndAliasedIndices_issue3268" -Dtests.security.manager=true -Dtests.locale=ar-SY -Dtests.timezone=US/Pacific
FAILURE  144s J1 | AliasRoutingIT.testAliasSearchRoutingWithConcreteAndAliasedIndices_issue3268 <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Delete Index failed - not acked
   > Expected: <true>
   >      but: was <false>
   > 	at __randomizedtesting.SeedInfo.seed([2FF077E78FBAE61:A816863BAF69B4BC]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:131)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:127)
   > 	at org.elasticsearch.test.TestCluster.wipeIndices(TestCluster.java:140)
   > 	at org.elasticsearch.test.TestCluster.wipe(TestCluster.java:77)
   > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:580)
   > 	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2057)
   > 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by colings86** [comment]
Another failure:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+nfs/203/consoleFull

This time the tests are different but the AssertionError is the same (not acked). Also in this build the node did not seem to fail later with the fileLock errors.

```
Throwable #1: java.lang.AssertionError: Delete Index failed - not acked
   > Expected: <true>
   >      but: was <false>
  2> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  2> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   > 	at __randomizedtesting.SeedInfo.seed([9A3213C74DAFA953:65EA37870ABA126D]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:131)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:127)
  2> 	at java.lang.Thread.run(Thread.java:745)
  2> 	Locked synchronizers:
   > 	at org.elasticsearch.test.TestCluster.wipeIndices(TestCluster.java:140)
   > 	at org.elasticsearch.test.TestCluster.wipe(TestCluster.java:77)
   > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:580)
  2> 	- java.util.concurrent.ThreadPoolExecutor$Worker@87fb450
```

**Comment by s1monw** [comment]
I wonder if this is related to running checkindex on so many shards and slow disks:
```
 1> [2017-04-24T21:02:16,197][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_s0] [index_2/xlZQeAfcSK6i0gOWUMchfA] deleting index
  1> [2017-04-24T21:02:16,357][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index_2][0] start check index
  1> [2017-04-24T21:02:16,908][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index_2][0] end check index
  1> [2017-04-24T21:02:18,044][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index_2][1] start check index
  1> [2017-04-24T21:02:18,651][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index_2][1] end check index
  1> [2017-04-24T21:02:19,817][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index_2][2] start check index
  1> [2017-04-24T21:02:20,478][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index_2][2] end check index
  1> [2017-04-24T21:02:22,214][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index_2][3] start check index
  1> [2017-04-24T21:02:23,014][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index_2][3] end check index
  1> [2017-04-24T21:02:24,396][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index_2][4] start check index
  1> [2017-04-24T21:02:24,873][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index_2][4] end check index
  1> [2017-04-24T21:02:25,895][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index_2][5] start check index
  1> [2017-04-24T21:02:26,618][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index_2][5] end check index
  1> [2017-04-24T21:02:27,891][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index_2][6] start check index
  1> [2017-04-24T21:02:28,558][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index_2][6] end check index
  1> [2017-04-24T21:02:29,710][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index_2][7] start check index
  1> [2017-04-24T21:02:30,372][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index_2][7] end check index
  1> [2017-04-24T21:02:31,861][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index][0] start check index
  1> [2017-04-24T21:02:32,432][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index][0] end check index
  1> [2017-04-24T21:02:33,612][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index][1] start check index
  1> [2017-04-24T21:02:34,096][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index][1] end check index
  1> [2017-04-24T21:02:34,949][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index][2] start check index
  1> [2017-04-24T21:02:35,427][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index][2] end check index
  1> [2017-04-24T21:02:36,364][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index][3] start check index
  1> [2017-04-24T21:02:36,867][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index][3] end check index
  1> [2017-04-24T21:02:37,779][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index][4] start check index
  1> [2017-04-24T21:02:38,415][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index][4] end check index
  1> [2017-04-24T21:02:39,580][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index][5] start check index
  1> [2017-04-24T21:02:40,083][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index][5] end check index
  1> [2017-04-24T21:02:41,074][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index][6] start check index
  1> [2017-04-24T21:02:41,593][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index][6] end check index
  1> [2017-04-24T21:02:42,343][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index][7] start check index
  1> [2017-04-24T21:02:42,696][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index][7] end check index
  1> [2017-04-24T21:02:43,584][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index][8] start check index
  1> [2017-04-24T21:02:44,020][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s1] [index][8] end check index
  1> [2017-04-24T21:02:45,714][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s0] [index_2][0] start check index
  1> [2017-04-24T21:02:46,221][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s0] [index_2][0] end check index
  1> [2017-04-24T21:02:46,336][INFO ][o.e.r.AliasRoutingIT     ] [testAliasSearchRoutingWithConcreteAndAliasedIndices_issue3268]: after test
  2> REPRODUCE WITH: gradle :core:integTest -Dtests.seed=2FF077E78FBAE61 -Dtests.class=org.elasticsearch.routing.AliasRoutingIT -Dtests.method="testAliasSearchRoutingWithConcreteAndAliasedIndices_issue3268" -Dtests.security.manager=true -Dtests.locale=ar-SY -Dtests.timezone=US/Pacific
FAILURE  144s J1 | AliasRoutingIT.testAliasSearchRoutingWithConcreteAndAliasedIndices_issue3268 <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Delete Index failed - not acked
   > Expected: <true>
   >      but: was <false>
   > 	at __randomizedtesting.SeedInfo.seed([2FF077E78FBAE61:A816863BAF69B4BC]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:131)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:127)
   > 	at org.elasticsearch.test.TestCluster.wipeIndices(TestCluster.java:140)
   > 	at org.elasticsearch.test.TestCluster.wipe(TestCluster.java:77)
   > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:580)
   > 	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2057)
   > 	at java.lang.Thread.run(Thread.java:745)
```

each checkindex (per-shard) takes 2 seconds which piles up quickly and that means the ack times out. I wonder if we should opt-out of this on the NFS builds to speed things up?

**Comment by nik9000** [comment]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+nfs/215/consoleFull looks like the same problem on NFS but without the index checking. It looks like it is *still* too slow....

**Comment by imotov** [comment]
Looks like it failed again with the same stacktrace as in @nik9000's comment https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+nfs/230/console

**Comment by danielmitterdorfer** [comment]
Another failure in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+nfs/233/console for the test case `AliasRoutingIT.testAliasSearchRoutingWithConcreteAndAliasedIndices_issue3268`.

**Comment by ywelsch** [comment]
The NFS tests never pass... should we disable them altogether until we know what the root cause is?
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+nfs/

**Comment by jasontedor** [comment]
We are going to disable the NFS builds indeed.
