### ISSUE TITLE
AWS Cloud plugin: Creation of S3 snapshot sometimes raises MultiObjectDeleteException

### ISSUE THREAD

**Issue by apepper** [elastic/elasticsearch#24306]
**Elasticsearch version**: 2.4.4

**Plugins installed**: 
 * `cloud-aws` (`2.4.4`)
 * `elasticsearch-head` (`master-20170214`)
 * `elasticsearch-kopf` (`2.1.2`)
 * `license` (`2.4.4`)
 * `marvel-agent` (`2.4.4`)

**JVM version**: `jdk-8u121`

**OS version**: Amazon Linux `2016.09`

**Description of the problem including expected versus actual behavior**:

We are doing regular snapshots of our elasticsearch cluster to S3 for years now. For this we create a fresh snapshot every day and add incremental snapshots every hour. 

But since two weeks we see occasional errors, while creating a new snapshot. Specifically the following call:

```
PUT _snapshot/my_s3_repository
{
  "type": "s3",
  "settings": {
    "bucket": "my_bucket_name",
    "region": "eu-west",
    "base_path": "my_base_path",
    "server_side_encryption": true,
  }
}
```

Fails with:

```
{
  "error": {
    "root_cause": [
      {
        "type": "multi_object_delete_exception",
        "reason": "One or more objects could not be deleted (Service: null; Status Code: 200; Error Code: null; Request ID: 104DA412C8DDAF8D)"
      }
    ],
    "type": "multi_object_delete_exception",
    "reason": "One or more objects could not be deleted (Service: null; Status Code: 200; Error Code: null; Request ID: 104DA412C8DDAF8D)"
  },
  "status": 500
}
```

So far we saw this error twice. So the last two weeks 2 out of 336 snapshots failed because of this error. Please notice, that both errors did not happen during the first snapshot (a new snapshot) of the day, but during the day (so an incremental snapshot). The next snapshot an hour later works as usual.

Our elasticsearch cluster runs on aws ec2 private instances in `eu-west-1`, so in the same region, as the S3 bucket. During the two incidents monitoring of the cluster showed no connectivity issues.

**Provide logs (if relevant)**:

Logs of the first incident:

```
[2017-04-13 11:00:02,212][INFO ][repositories             ] [cms-elasticsearch-prod71.localdomain] update repository [2017-04-13-elasticsearch-cms-prod-cluster-2017-02-15-10-59]
[2017-04-13 11:00:17,151][INFO ][snapshots                ] [cms-elasticsearch-prod71.localdomain] snapshot [2017-04-13-elasticsearch-cms-prod-cluster-2017-02-15-10-59:2017-04-13t11:00] is done
[2017-04-13 12:00:02,806][INFO ][repositories             ] [cms-elasticsearch-prod71.localdomain] update repository [2017-04-13-elasticsearch-cms-prod-cluster-2017-02-15-10-59]
[2017-04-13 12:00:10,012][WARN ][repositories             ] [cms-elasticsearch-prod71.localdomain] [2017-04-13-elasticsearch-cms-prod-cluster-2017-02-15-10-59] failed to finish repository verification
com.amazonaws.services.s3.model.MultiObjectDeleteException: One or more objects could not be deleted (Service: null; Status Code: 200; Error Code: null; Request ID: BLANKED1), S3 Extended Request ID: BLANKED2=
  at com.amazonaws.services.s3.AmazonS3Client.deleteObjects(AmazonS3Client.java:1734)
  at org.elasticsearch.cloud.aws.blobstore.S3BlobStore.delete(S3BlobStore.java:172)
  at org.elasticsearch.repositories.blobstore.BlobStoreRepository.endVerification(BlobStoreRepository.java:658)
  at org.elasticsearch.repositories.RepositoriesService$3.onResponse(RepositoriesService.java:218)
  at org.elasticsearch.repositories.RepositoriesService$3.onResponse(RepositoriesService.java:214)
  at org.elasticsearch.repositories.VerifyNodeRepositoryAction.finishVerification(VerifyNodeRepositoryAction.java:116)
  at org.elasticsearch.repositories.VerifyNodeRepositoryAction$1.handleResponse(VerifyNodeRepositoryAction.java:99)
  at org.elasticsearch.repositories.VerifyNodeRepositoryAction$1.handleResponse(VerifyNodeRepositoryAction.java:95)
  at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:158)
  at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:124)
  at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
  at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
  at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
  at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
  at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
  at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
  at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
  at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
  at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
  at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
[2017-04-13 12:00:10,013][WARN ][rest.suppressed          ] path: //_snapshot/2017-04-13-elasticsearch-cms-prod-cluster-2017-02-15-10-59, params: {repository=2017-04-13-elasticsearch-cms-prod-cluster-2017-02-15-10-59}
com.amazonaws.services.s3.model.MultiObjectDeleteException: One or more objects could not be deleted (Service: null; Status Code: 200; Error Code: null; Request ID: BLANKED1), S3 Extended Request ID: BLANKED2=
  at com.amazonaws.services.s3.AmazonS3Client.deleteObjects(AmazonS3Client.java:1734)
  at org.elasticsearch.cloud.aws.blobstore.S3BlobStore.delete(S3BlobStore.java:172)
  at org.elasticsearch.repositories.blobstore.BlobStoreRepository.endVerification(BlobStoreRepository.java:658)
  at org.elasticsearch.repositories.RepositoriesService$3.onResponse(RepositoriesService.java:218)
  at org.elasticsearch.repositories.RepositoriesService$3.onResponse(RepositoriesService.java:214)
  at org.elasticsearch.repositories.VerifyNodeRepositoryAction.finishVerification(VerifyNodeRepositoryAction.java:116)
  at org.elasticsearch.repositories.VerifyNodeRepositoryAction$1.handleResponse(VerifyNodeRepositoryAction.java:99)
  at org.elasticsearch.repositories.VerifyNodeRepositoryAction$1.handleResponse(VerifyNodeRepositoryAction.java:95)
  at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:158)
  at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:124)
  at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
  at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
  at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
  at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
  at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
  at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
  at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
  at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
  at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
  at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
[2017-04-13 12:43:48,766][INFO ][cluster.metadata         ] [cms-elasticsearch-prod71.localdomain] [scrivito-cms-objs-v11] update_mapping [objs]
[2017-04-13 13:00:02,177][INFO ][repositories             ] [cms-elasticsearch-prod71.localdomain] update repository [2017-04-13-elasticsearch-cms-prod-cluster-2017-02-15-10-59]
[2017-04-13 13:00:36,147][INFO ][snapshots                ] [cms-elasticsearch-prod71.localdomain] snapshot [2017-04-13-elasticsearch-cms-prod-cluster-2017-02-15-10-59:2017-04-13t13:00] is done
```

Logs of the second incident:

```
[2017-04-19 06:00:02,433][INFO ][repositories             ] [cms-elasticsearch-prod71.localdomain] update repository [2017-04-19-elasticsearch-cms-prod-cluster-2017-02-15-10-59]
[2017-04-19 06:00:16,633][INFO ][snapshots                ] [cms-elasticsearch-prod71.localdomain] snapshot [2017-04-19-elasticsearch-cms-prod-cluster-2017-02-15-10-59:2017-04-19t06:00] is done
[2017-04-19 07:00:02,541][INFO ][repositories             ] [cms-elasticsearch-prod71.localdomain] update repository [2017-04-19-elasticsearch-cms-prod-cluster-2017-02-15-10-59]
[2017-04-19 07:00:09,177][WARN ][repositories             ] [cms-elasticsearch-prod71.localdomain] [2017-04-19-elasticsearch-cms-prod-cluster-2017-02-15-10-59] failed to finish repository verification
com.amazonaws.services.s3.model.MultiObjectDeleteException: One or more objects could not be deleted (Service: null; Status Code: 200; Error Code: null; Request ID: BLANKED3), S3 Extended Request ID: BLANKED4=
  at com.amazonaws.services.s3.AmazonS3Client.deleteObjects(AmazonS3Client.java:1734)
  at org.elasticsearch.cloud.aws.blobstore.S3BlobStore.delete(S3BlobStore.java:172)
  at org.elasticsearch.repositories.blobstore.BlobStoreRepository.endVerification(BlobStoreRepository.java:658)
  at org.elasticsearch.repositories.RepositoriesService$3.onResponse(RepositoriesService.java:218)
  at org.elasticsearch.repositories.RepositoriesService$3.onResponse(RepositoriesService.java:214)
  at org.elasticsearch.repositories.VerifyNodeRepositoryAction.finishVerification(VerifyNodeRepositoryAction.java:116)
  at org.elasticsearch.repositories.VerifyNodeRepositoryAction$1.handleResponse(VerifyNodeRepositoryAction.java:99)
  at org.elasticsearch.repositories.VerifyNodeRepositoryAction$1.handleResponse(VerifyNodeRepositoryAction.java:95)
  at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:158)
  at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:124)
  at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
  at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
  at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
  at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
  at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
  at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
  at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
  at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
  at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
  at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
[2017-04-19 07:00:09,177][WARN ][rest.suppressed          ] path: //_snapshot/2017-04-19-elasticsearch-cms-prod-cluster-2017-02-15-10-59, params: {repository=2017-04-19-elasticsearch-cms-prod-cluster-2017-02-15-10-59}
com.amazonaws.services.s3.model.MultiObjectDeleteException: One or more objects could not be deleted (Service: null; Status Code: 200; Error Code: null; Request ID: BLANKED3), S3 Extended Request ID: BLANKED4=
  at com.amazonaws.services.s3.AmazonS3Client.deleteObjects(AmazonS3Client.java:1734)
  at org.elasticsearch.cloud.aws.blobstore.S3BlobStore.delete(S3BlobStore.java:172)
  at org.elasticsearch.repositories.blobstore.BlobStoreRepository.endVerification(BlobStoreRepository.java:658)
  at org.elasticsearch.repositories.RepositoriesService$3.onResponse(RepositoriesService.java:218)
  at org.elasticsearch.repositories.RepositoriesService$3.onResponse(RepositoriesService.java:214)
  at org.elasticsearch.repositories.VerifyNodeRepositoryAction.finishVerification(VerifyNodeRepositoryAction.java:116)
  at org.elasticsearch.repositories.VerifyNodeRepositoryAction$1.handleResponse(VerifyNodeRepositoryAction.java:99)
  at org.elasticsearch.repositories.VerifyNodeRepositoryAction$1.handleResponse(VerifyNodeRepositoryAction.java:95)
  at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:158)
  at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:124)
  at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
  at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
  at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
  at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
  at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
  at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
  at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
  at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
  at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
  at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
[2017-04-19 08:00:02,334][INFO ][repositories             ] [cms-elasticsearch-prod71.localdomain] update repository [2017-04-19-elasticsearch-cms-prod-cluster-2017-02-15-10-59]
[2017-04-19 08:00:27,047][INFO ][snapshots                ] [cms-elasticsearch-prod71.localdomain] snapshot [2017-04-19-elasticsearch-cms-prod-cluster-2017-02-15-10-59:2017-04-19t08:00] is done
```

**Comment by abeyad** [comment]
@apepper thanks for reporting this.  Did you recently upgrade your ES version to 2.4.4 or have you been on it for a while (longer than the problem has been manifesting)?  Also, why are you recreating the repository every time you want to take a snapshot?  That is not needed, you can simply take snapshots once the repository has been created once for the cluster.

The error is happening during repository verification after creation - by default when a repository is created in a cluster, a test is run to ensure that every node in the cluster is able to write to the repository, so the master node writes a new folder off the base_path called `tests-{seed}` and has each node write a blob to that folder, and once it verified that it can write to the repository, it subsequently deletes that `tests-{seed}` folder off the base_path.  The error is happening as a result of attempting to delete `tests-{seed}` and all the blobs created in it - it seems some of the blobs could not be deleted, or there was a concurrent request and the blobs were attempted to be deleted twice.  Its not clear to me yet how this can happen, given the code and the stack trace shown (unless some side process outside of ES deleted those objects).

Note that you can sidestep the verification process by passing in the request param `verify=false`, and this may be a good solution for you in the interim, i.e.
```
PUT _snapshot/my_s3_repository?verify=false
{
  "type": "s3",
  "settings": {
    "bucket": "my_bucket_name",
    "region": "eu-west",
    "base_path": "my_base_path",
    "server_side_encryption": true,
  }
}
```

But as I mentioned, you don't need to call this every time - once you've created the repository once in the cluster, all you need to do is use the [create snapshot API](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/modules-snapshots.html#_snapshot) to create snapshots.

**Comment by apepper** [comment]
@abeyad: Thanks for getting back to me.

>Did you recently upgrade your ES version to 2.4.4 or have you been on it for a while (longer than the problem has been manifesting)?

We do use ES 2.4.4 in production since early march 2017. So about two months now. The problem did manifest twice during that time.

> Also, why are you recreating the repository every time you want to take a snapshot? That is not needed, you can simply take snapshots once the repository has been created once for the cluster.

Because so far we did not have problems with just registering the snapshot repository, whenever we want to create a new snapshot. But we can modify our backup script to be a noop, if the snapshot repository is already created. So instead of 24 times a day, only 1 time a day the endpoint in question is called. So the bug can than only occur 1/24 of the time.

> Note that you can sidestep the verification process by passing in the request param verify=false, and this may be a good solution for you in the interim [...]

Thanks for pointing out a workaround. But I don't feel comfortable to disable the verification just to avoid a warning.

**Comment by abeyad** [comment]
> We do use ES 2.4.4 in production since early march 2017. So about two months now. The problem did manifest twice during that time.

Did the problem manifest before upgrading to 2.4.4 as well?  Or only since you've upgraded to 2.4.4?  And from which version did you upgrade?

Also, did you notice a new master node election around the time the failure occurred?  The logs would've indicated something like "new master"

**Comment by apepper** [comment]
> Did the problem manifest before upgrading to 2.4.4 as well? Or only since you've upgraded to 2.4.4? And from which version did you upgrade?

The problem manifested after upgrading to `2.4.4`. Previously we had several different versions of elasticsearch running, all without problems regarding S3 snapshots. The latest prior to `2.4.4` was `2.4.1`.

> Also, did you notice a new master node election around the time the failure occurred? The logs would've indicated something like "new master"

According to the logs there where no master node election during that time. The specific cluster consists of three AWS EC2 instances running in a VPC and is running for about two months now. During that time no instance was rebooted or added after the initial start. So master node election is probably not triggering this bug.

**Comment by tlrx** [comment]
We failed to reproduce this issue on our side and we didn't have any other bug report like this since this issue was created. We talked about this with @ywelsch today and we suggest that you upgrade your cluster to a more recent version (2.4 is not supported anymore) and see if the issue appears again.

**Comment by christian-ertl** [comment]
This still occurs with ES 7.16.2/ECE 2.10.1.

**Comment by DaveCTurner** [comment]
You'll need to sort this out with Dell. See [these docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-register-repository.html#self-managed-repo-types), particularly:

> Note that some storage systems claim to be compatible with these repository types without emulating their behaviour in full. Elasticsearch requires full compatibility. In particular the alternative implementation must support the same set of API endpoints, return the same errors in case of failures, and offer equivalent consistency guarantees and performance even when accessed concurrently by multiple nodes. Incompatible error codes, consistency or performance may be particularly hard to track down since errors, consistency failures, and performance issues are usually rare and hard to reproduce.

> You can perform some basic checks of the suitability of your storage system using the [Repository analysis](https://www.elastic.co/guide/en/elasticsearch/reference/current/repo-analysis-api.html) API. If this API does not complete successfully, or indicates poor performance, then your storage system is not fully compatible and is therefore unsuitable for use as a snapshot repository. **You will need to work with the supplier of your storage system to address any incompatibilities you encounter.**

**Comment by razorworks** [comment]
> You'll need to sort this out with Dell. See [these docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-register-repository.html#self-managed-repo-types), particularly:

I know. :/
Thanks for your assistance.
