### ISSUE TITLE
[CI] Thread leaks in org.elasticsearch.test.disruption.LongGCDisruptionTests

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#24353]
After https://github.com/elastic/elasticsearch/pull/24338 we still see a failure where threads are being leaked:

```
com.carrotsearch.randomizedtesting.ThreadLeakError: 2 threads leaked from SUITE scope at org.elasticsearch.test.disruption.LongGCDisruptionTests: 
   1) Thread[id=37, name=[test_node][7], state=RUNNABLE, group=TGRP-LongGCDisruptionTests]
        at org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testBlockingTimeout$1(LongGCDisruptionTests.java:90)
        at org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$58/1661470889.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)
   2) Thread[id=39, name=[test_node][9], state=RUNNABLE, group=TGRP-LongGCDisruptionTests]
        at org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testBlockingTimeout$1(LongGCDisruptionTests.java:90)
        at org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$58/1661470889.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)
	at __randomizedtesting.SeedInfo.seed([BAFB5D60272923A9]:0)
com.carrotsearch.randomizedtesting.ThreadLeakError: There are still zombie threads that couldn't be terminated:
   1) Thread[id=37, name=[test_node][7], state=RUNNABLE, group=TGRP-LongGCDisruptionTests]
        at org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testBlockingTimeout$1(LongGCDisruptionTests.java:90)
        at org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$58/1661470889.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)
   2) Thread[id=39, name=[test_node][9], state=RUNNABLE, group=TGRP-LongGCDisruptionTests]
        at org.elasticsearch.test.disruption.LongGCDisruptionTests.lambda$testBlockingTimeout$1(LongGCDisruptionTests.java:90)
        at org.elasticsearch.test.disruption.LongGCDisruptionTests$$Lambda$58/1661470889.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)
	at __randomizedtesting.SeedInfo.seed([BAFB5D60272923A9]:0)
```

Seen at https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/2595/console

**Comment by jasontedor** [comment]
This build did not include #24338.
