### ISSUE TITLE
[TEST] GeoDistanceQueryBuilderTests.testToQuery fails

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#24368]
Failure:

```
FAILURE 0.04s J2 | GeoDistanceQueryBuilderTests.testToQuery <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: a numeric value within <1.0E-6> of <1660.9751718359562>
   >      but: <77.04177711499645> differed by <1583.9333937209597>
   > 	at __randomizedtesting.SeedInfo.seed([2685BCB68849EDBB:D17EBE88F9CA2851]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
> 	at org.elasticsearch.index.query.GeoDistanceQueryBuilderTests.assertGeoPointQuery(GeoDistanceQueryBuilderTests.java:168)
   > 	at org.elasticsearch.index.query.GeoDistanceQueryBuilderTests.doAssertLuceneQuery(GeoDistanceQueryBuilderTests.java:141)
   > 	at org.elasticsearch.index.query.GeoDistanceQueryBuilderTests.doAssertLuceneQuery(GeoDistanceQueryBuilderTests.java:49)
   > 	at org.elasticsearch.test.AbstractQueryTestCase.assertLuceneQuery(AbstractQueryTestCase.java:676)
   > 	at org.elasticsearch.test.AbstractQueryTestCase.testToQuery(AbstractQueryTestCase.java:590)
   > 	at org.elasticsearch.index.query.GeoDistanceQueryBuilderTests.testToQuery(GeoDistanceQueryBuilderTests.java:132)
   > 	at java.lang.Thread.run(Thread.java:745)
```

Build output: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-windows-compatibility/76/consoleFull

Seed to reproduce failure:

```
gradle :core:test -Dtests.seed=2685BCB68849EDBB -Dtests.class=org.elasticsearch.index.query.GeoDistanceQueryBuilderTests -Dtests.method="testToQuery" -Dtests.security.manager=true -Dtests.locale=ga-IE -Dtests.timezone=America/Santo_Domingo
```

**Comment by colings86** [comment]
This seed no longer reproduces on 5.6 and the test has changed significantly in 6.0+. Additionally I ran the test on the 5.6 branch with `-Dtests.iters=1000` and could not produce a failure so I'm going to close this issue
