### ISSUE TITLE
Strange failure in DelayedAllocationIT.testDelayedAllocationTimesOut

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#24394]
[This](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/99/consoleFull) build turned up a strange failure:

```
FAILURE 70.1s J2 | DelayedAllocationIT.testDelayedAllocationTimesOut <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: timed out waiting for green state
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureColor(ESIntegTestCase.java:944)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:910)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:899)
   > 	at org.elasticsearch.cluster.routing.DelayedAllocationIT.testDelayedAllocationTimesOut(DelayedAllocationIT.java:100)
   > 	at java.lang.Thread.run(Thread.java:745)Throwable #2: java.lang.AssertionError: ClusterHealthResponse has timed out - returned: [{"cluster_name":"TEST-CHILD_VM=[2]-CLUSTER_SEED=[-7901628312211415262]-HASH=[461A857603028]-cluster","status":"green","timed_out":true,"number_of_nodes":3,"number_of_data_nodes":3,"active_primary_shards":1,"active_shards":2,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0}]
   > Expected: is <false>
   >      but: was <true>
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertNoTimeout(ElasticsearchAssertions.java:118)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureClusterSizeConsistency(ESIntegTestCase.java:1089)
   > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:564)
   > 	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2059)
   > 	at java.lang.Thread.run(Thread.java:745)
```

The weird thing here is that DelayedAllocationIT.java:100 isn't a call to `ensureGreen`. There are `ensureGreen` calls all around that line, but not 100.

**Comment by nik9000** [comment]
> The weird thing here is that DelayedAllocationIT.java:100 isn't a call to ensureGreen. There are ensureGreen calls all around that line, but not 100.

Ignore that. I had 5.x open.... Line 100 is indeed ensureGreen: https://github.com/elastic/elasticsearch/blob/master/core/src/test/java/org/elasticsearch/cluster/routing/DelayedAllocationIT.java#L100.

**Comment by ywelsch** [comment]
I've pushed 9c55bca8fb which should fix this. There was a race introduced in https://github.com/elastic/elasticsearch/pull/24236 between updating the node failure detector and using the correct state as basis to determine if failures should be handled.
