### ISSUE TITLE
IndicesStatsTests.testRefreshListeners sporadically fails

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#24417]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+nfs/223

Seems like the expected refresh listener never shows up:

```
2> REPRODUCE WITH: gradle :core:test -Dtests.seed=34653F54E65651D5 -Dtests.class=org.elasticsearch.action.admin.indices.stats.IndicesStatsTests -Dtests.method="testRefreshListeners" -Dtests.security.manager=true -Dtests.locale=ar-SY -Dtests.timezone=PST8PDT
FAILURE 16.6s J1 | IndicesStatsTests.testRefreshListeners <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<1> but was:<0>
   > 	at __randomizedtesting.SeedInfo.seed([34653F54E65651D5:AFCC896A9005279D]:0)
   > 	at org.elasticsearch.action.admin.indices.stats.IndicesStatsTests.lambda$testRefreshListeners$0(IndicesStatsTests.java:130)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:716)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:690)
   > 	at org.elasticsearch.action.admin.indices.stats.IndicesStatsTests.testRefreshListeners(IndicesStatsTests.java:127)
   > 	at java.lang.Thread.run(Thread.java:745)
   > 	Suppressed: java.lang.AssertionError: expected:<1> but was:<0>
   > 		at org.elasticsearch.action.admin.indices.stats.IndicesStatsTests.lambda$testRefreshListeners$0(IndicesStatsTests.java:130)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
   > 		... 39 more
   > 	Suppressed: java.lang.AssertionError: expected:<1> but was:<0>
   > 		at org.elasticsearch.action.admin.indices.stats.IndicesStatsTests.lambda$testRefreshListeners$0(IndicesStatsTests.java:130)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
   > 		... 39 more
   > 	Suppressed: java.lang.AssertionError: expected:<1> but was:<0>
   > 		at org.elasticsearch.action.admin.indices.stats.IndicesStatsTests.lambda$testRefreshListeners$0(IndicesStatsTests.java:130)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
   > 		... 39 more
   > 	Suppressed: java.lang.AssertionError: expected:<1> but was:<0>
   > 		at org.elasticsearch.action.admin.indices.stats.IndicesStatsTests.lambda$testRefreshListeners$0(IndicesStatsTests.java:130)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
   > 		... 39 more
   > 	Suppressed: java.lang.AssertionError: expected:<1> but was:<0>
   > 		at org.elasticsearch.action.admin.indices.stats.IndicesStatsTests.lambda$testRefreshListeners$0(IndicesStatsTests.java:130)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
   > 		... 39 more
   > 	Suppressed: java.lang.AssertionError: expected:<1> but was:<0>
   > 		at org.elasticsearch.action.admin.indices.stats.IndicesStatsTests.lambda$testRefreshListeners$0(IndicesStatsTests.java:130)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
   > 		... 39 more
   > 	Suppressed: java.lang.AssertionError: expected:<1> but was:<0>
   > 		at org.elasticsearch.action.admin.indices.stats.IndicesStatsTests.lambda$testRefreshListeners$0(IndicesStatsTests.java:130)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
   > 		... 39 more
   > 	Suppressed: java.lang.AssertionError: expected:<1> but was:<0>
   > 		at org.elasticsearch.action.admin.indices.stats.IndicesStatsTests.lambda$testRefreshListeners$0(IndicesStatsTests.java:130)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
   > 		... 39 more
   > 	Suppressed: java.lang.AssertionError: expected:<1> but was:<0>
   > 		at org.elasticsearch.action.admin.indices.stats.IndicesStatsTests.lambda$testRefreshListeners$0(IndicesStatsTests.java:130)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
   > 		... 39 more
   > 	Suppressed: java.lang.AssertionError: expected:<1> but was:<0>
   > 		at org.elasticsearch.action.admin.indices.stats.IndicesStatsTests.lambda$testRefreshListeners$0(IndicesStatsTests.java:130)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
   > 		... 39 more
   > 	Suppressed: java.lang.AssertionError: expected:<1> but was:<0>
   > 		at org.elasticsearch.action.admin.indices.stats.IndicesStatsTests.lambda$testRefreshListeners$0(IndicesStatsTests.java:130)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
   > 		... 39 more
   > 	Suppressed: java.lang.AssertionError: expected:<1> but was:<0>
   > 		at org.elasticsearch.action.admin.indices.stats.IndicesStatsTests.lambda$testRefreshListeners$0(IndicesStatsTests.java:130)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
   > 		... 39 more
   > 	Suppressed: java.lang.AssertionError: expected:<1> but was:<0>
   > 		at org.elasticsearch.action.admin.indices.stats.IndicesStatsTests.lambda$testRefreshListeners$0(IndicesStatsTests.java:130)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:704)
   > 		... 39 more
```

**Comment by javanna** [comment]
I am assigning you @nik9000 because I think you are familiar with the test, feel free to reassign though if needed.

**Comment by nik9000** [comment]
I pushed 62712bf653f0a71e4e0b4468a55c774e91702f2a to get more information the next time this fails.

**Comment by nik9000** [comment]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+nfs/257/console
