### ISSUE TITLE
Can not fix unclosed brackets in pattern replace char filter

### ISSUE THREAD

**Issue by yoshioiwamoto** [elastic/elasticsearch#24476]
**Elasticsearch version:**
5.3.2

**Plugins installed:**
x-pack, analysis-icu

**JVM version:**
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

**OS version:**
Linux 4.4.0-72-generic # 93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description:**
After create a regex pattern with unclosed brackets the index settings can not be updated to fix it, also the index can not be opened again.

**Steps to reproduce:**

 1. Create a test index with a pattern replace char filter. The pattern_replace has a working pattern. 
```
PUT /test
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0,
    "analysis": {
      "char_filter": {
        "my_normalizer": {
          "type": "pattern_replace",
          "pattern": "([\\w+])", // working pattern
          "replacement": "$1"
        }
      }
    }
  }
}
```

Result:
```
{
  "acknowledged": true,
  "shards_acknowledged": true
}
```

 2. Close the index

`POST /test/_close`

 3. Update the char_filter with a unclosed pattern.

```
PUT /test/_settings
{
  "analysis": {
      "char_filter": {
      "my_normalizer": {
        "type": "pattern_replace",
        "pattern": "([\\w+)", // without "]"
        "replacement": "$1"
      }
    }
  }
}
```

The pattern is wrong but no warning is given:
```
{
  "acknowledged": true
}
```

 4. Now the index can not be opened.
`
POST /test/_open`

Result:
```
{
  "error": {
    "root_cause": [
      {
        "type": "exception",
        "reason": "Failed to verify index [test/n3rzxZvSTfe4GxvbhDYQYA]"
      }
    ],
    "type": "exception",
    "reason": "Failed to verify index [test/n3rzxZvSTfe4GxvbhDYQYA]",
    "caused_by": {
      "type": "pattern_syntax_exception",
      "reason": "Unclosed character class near index 5\n([\\w+)\n     ^"
    }
  },
  "status": 500
}
```

 5. The wrong pattern can not be fixed.

```
PUT /test/_settings
{
  "analysis": {
      "char_filter": {
      "my_normalizer": {
        "type": "pattern_replace",
        "pattern": "([\\w+])", // fixed
        "replacement": "$1"
      }
    }
  }
}
```

Result:
```
{
  "error": {
    "root_cause": [
      {
        "type": "pattern_syntax_exception",
        "reason": "Unclosed character class near index 5\n([\\w+)\n     ^"
      }
    ],
    "type": "pattern_syntax_exception",
    "reason": "Unclosed character class near index 5\n([\\w+)\n     ^"
  },
  "status": 400
}
```

**Log:**
```
[2017-05-03T21:32:59,786][DEBUG][o.e.a.a.i.s.p.TransportUpdateSettingsAction] [notebookavell] failed to update settings on indices [[[test/8NEkZ6ziSWehmTIzm3RZ6A]]]
java.util.regex.PatternSyntaxException: Unclosed character class near index 5
([\w+)
     ^
    at java.util.regex.Pattern.error(Pattern.java:1955) ~[?:1.8.0_121]
    at java.util.regex.Pattern.clazz(Pattern.java:2548) ~[?:1.8.0_121]
    at java.util.regex.Pattern.sequence(Pattern.java:2063) ~[?:1.8.0_121]
    at java.util.regex.Pattern.expr(Pattern.java:1996) ~[?:1.8.0_121]
    at java.util.regex.Pattern.group0(Pattern.java:2905) ~[?:1.8.0_121]
    at java.util.regex.Pattern.sequence(Pattern.java:2051) ~[?:1.8.0_121]
    at java.util.regex.Pattern.expr(Pattern.java:1996) ~[?:1.8.0_121]
    at java.util.regex.Pattern.compile(Pattern.java:1696) ~[?:1.8.0_121]
    at java.util.regex.Pattern.<init>(Pattern.java:1351) ~[?:1.8.0_121]
    at java.util.regex.Pattern.compile(Pattern.java:1054) ~[?:1.8.0_121]
    at org.elasticsearch.common.regex.Regex.compile(Regex.java:159) ~[elasticsearch-5.3.2.jar:5.3.2]
    at org.elasticsearch.index.analysis.PatternReplaceCharFilterFactory.<init>(PatternReplaceCharFilterFactory.java:43) ~[elasticsearch-5.3.2.jar:5.3.2]
    at org.elasticsearch.indices.analysis.AnalysisModule$1.get(AnalysisModule.java:351) ~[elasticsearch-5.3.2.jar:5.3.2]
    at org.elasticsearch.index.analysis.AnalysisRegistry.buildMapping(AnalysisRegistry.java:342) ~[elasticsearch-5.3.2.jar:5.3.2]
    at org.elasticsearch.index.analysis.AnalysisRegistry.buildCharFilterFactories(AnalysisRegistry.java:181) ~[elasticsearch-5.3.2.jar:5.3.2]
    at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:153) ~[elasticsearch-5.3.2.jar:5.3.2]
    at org.elasticsearch.index.IndexService.<init>(IndexService.java:145) ~[elasticsearch-5.3.2.jar:5.3.2]
    at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:363) ~[elasticsearch-5.3.2.jar:5.3.2]
    at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:427) ~[elasticsearch-5.3.2.jar:5.3.2]
    at org.elasticsearch.indices.IndicesService.verifyIndexMetadata(IndicesService.java:460) ~[elasticsearch-5.3.2.jar:5.3.2]
    at org.elasticsearch.cluster.metadata.MetaDataUpdateSettingsService$2.execute(MetaDataUpdateSettingsService.java:289) ~[elasticsearch-5.3.2.jar:5.3.2]
    at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45) ~[elasticsearch-5.3.2.jar:5.3.2]
    at org.elasticsearch.cluster.service.ClusterService.executeTasks(ClusterService.java:679) ~[elasticsearch-5.3.2.jar:5.3.2]
    at org.elasticsearch.cluster.service.ClusterService.calculateTaskOutputs(ClusterService.java:658) ~[elasticsearch-5.3.2.jar:5.3.2]
    at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:617) [elasticsearch-5.3.2.jar:5.3.2]
    at org.elasticsearch.cluster.service.ClusterService$UpdateTask.run(ClusterService.java:1117) [elasticsearch-5.3.2.jar:5.3.2]
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.3.2.jar:5.3.2]
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:238) [elasticsearch-5.3.2.jar:5.3.2]
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:201) [elasticsearch-5.3.2.jar:5.3.2]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by ywelsch** [comment]
Thank you for the detailed report and the great reproduction.
@jimczi can you have a look please?

**Comment by jimczi** [comment]
This is a bad bug originally reported by https://github.com/elastic/elasticsearch/issues/23787
I'll work on a fix.
Thanks @yoshioiwamoto
