### ISSUE TITLE
Elasticsearch-5.4.0 installation fails in bootstrap check

### ISSUE THREAD

**Issue by bipeens** [elastic/elasticsearch#24508]
**Elasticsearch version**: 5.4.0

**Plugins installed**: 
repository-s3
x-pack
discovery-ec2

**JVM version** (`java -version`): 1.8.0_91

**OS version** (`uname -a` if on a Unix-like system):
Docker alpine 3.4 image
Linux  4.8.3-1.el7.elrepo.x86_64 #1 SMP Thu Oct 20 11:46:47 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Elasticsearch-5.4.0 installation fails in bootstrap check. It gives FilenotFoundException for /tmp/controller_log_295 file. Elasticsearch run using elasticuser whereas /tmp has root privileges. I am not sure why it is referencing /tmp folder.

**Steps to reproduce**:

 1. Installed elasticsearch 5.4.0 in alpine 3.4 docker image.
 2. Installed plugins
 3. Start elasticsearch 

**Provide logs (if relevant)**:

`[2017-05-05T09:34:13,526][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Failed to create native process factories for Machine Learning]; nested: FileNotFoundException[/tmp/controller_log_295 (No such file or directory)];
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.4.0.jar:5.4.0]
Caused by: org.elasticsearch.ElasticsearchException: Failed to create native process factories forMachine Learning
        at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLearning.java:297) ~[?:?]
		 at org.elasticsearch.xpack.XPackPlugin.createComponents(XPackPlugin.java:288) ~[?:?]
        at org.elasticsearch.node.Node.lambda$new$7(Node.java:410) ~[elasticsearch-5.4.0.jar:5.4.0]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_91]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_91]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_91]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_91]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_91]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_91]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_91]
        at org.elasticsearch.node.Node.<init>(Node.java:412) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.4.0.jar:5.4.0]
        ... 6 more
Caused by: java.io.FileNotFoundException: /tmp/controller_log_295 (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_91]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_91]
        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_91]
        at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[?:1.8.0_91]`

**Comments**: It was running properly on elasticsearch-5.3.2 version.

**Comment by clintongormley** [comment]
@bipeens You have installed X-Pack with the new machine-learning feature, which doesn't work on Alpine Linux.  Alpine Linux is not a supported OS: https://www.elastic.co/support/matrix

We provide [official Docker images](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) which run centos-7

**Comment by bipeens** [comment]
We had Elasticsearch-5.3.2 working on Alpine Linux. Is it because of new machine-learning feature added to  5.4 version. Also is there any plan to support in future, or is there any option for machine-learning feature to be disabled.

**Comment by jasontedor** [comment]
This is not a bootstrap check, this is just failing because the ML executable failed.

>  Is there any plan to support in future

No.

> or is there any option for machine-learning feature to be disabled?

You can use `xpack.ml.enabled` set to `false`

**Comment by bipeens** [comment]
@jasontedor, yes disabling machine-learning worked and ES cluster is up and running. If would be nice to have it supported in future releases.
Thanks for your help.
