### ISSUE TITLE
CI: Backwards50ClientYamlTestSuiteIT.scroll/10_basic/Basic scroll with 1 shard failed

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#24562]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.4+multijob-windows-compatibility/73/consoleFull

reason

```
  1> [2017-05-09T14:47:16,668][INFO ][o.e.b.Backwards50ClientYamlTestSuiteIT] Stash dump on failure [{
  1>   "stash" : {
  1>     "scroll_id" : "DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAAAkUWTnlhYXBjVXFUdjJFdy1hc3FMVkZrQQ==",
  1>     "body" : {
  1>       "_scroll_id" : "DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAAAkUWTnlhYXBjVXFUdjJFdy1hc3FMVkZrQQ==",
  1>       "took" : 1,
  1>       "timed_out" : false,
  1>       "_shards" : {
  1>         "total" : 1,
  1>         "successful" : 1,
  1>         "failed" : 0
  1>       },
  1>       "hits" : {
  1>         "total" : 2,
  1>         "max_score" : null,
  1>         "hits" : [
  1>           {
  1>             "_index" : "test_scroll",
  1>             "_type" : "test",
  1>             "_id" : "42",
  1>             "_score" : null,
  1>             "_source" : {
  1>               "foo" : 1
  1>             },
  1>             "sort" : [
  1>               1
  1>             ]
  1>           }
  1>         ]
  1>       }
  1>     }
  1>   }
  1> }]

FAILURE 0.16s | Backwards50ClientYamlTestSuiteIT.test {p0=scroll/10_basic/Basic scroll with 1 shard} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [scroll/10_basic:126]: hits.hits.0._id didn't match the expected value:
   >                hits.hits.0._id: expected [43] but was [42]
   > 	at __randomizedtesting.SeedInfo.seed([C0ABB8B890ED9893:48FF87623E11F56B]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:379)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:359)
   > 	at java.lang.Thread.run(Thread.java:745)
   > Caused by: java.lang.AssertionError: hits.hits.0._id didn't match the expected value:
   >                hits.hits.0._id: expected [43] but was [42]
   > 	at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:92)
   > 	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
   > 	at 
```

```
REPRODUCE WITH: gradle :qa:backwards-5.0:integTestRunner -Dtests.seed=C0ABB8B890ED9893 -Dtests.class=org.elasticsearch.backwards.Backwards50ClientYamlTestSuiteIT -Dtests.method="test {p0=scroll/10_basic/Basic scroll with 1 shard}" -Dtests.security.manager=true -Dtests.locale=en-GB -Dtests.timezone=Asia/Aqtobe
```

could not repro localy

@jimczi assigning it to you, since you added this test today.

**Comment by spinscale** [comment]
this one seems to be another one (one master due to a fix around this) https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/1213/console

**Comment by jimczi** [comment]
Fixed by https://github.com/elastic/elasticsearch/commit/b6c714ccc8a2f670de2c0d7cd872335a4c5410c0
