### ISSUE TITLE
[CI] org.elasticsearch.index.replication.IndexLevelReplicationTests.testCheckpointsAdvance fails reproducibly

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#24602]
Fails with the following:

```
==> Test Info: seed=B4AC2695A7576B7; jvm=1; suite=1
Suite: org.elasticsearch.index.replication.IndexLevelReplicationTests
  1> [2017-05-10T09:25:35,242][INFO ][o.e.i.r.IndexLevelReplicationTests] [testCheckpointsAdvance]: before test
  1> numDocs: 0
  1> [2017-05-10T09:25:36,526][INFO ][o.e.i.r.IndexLevelReplicationTests] [testCheckpointsAdvance]: after test
  2> REPRODUCE WITH: gradle :core:test -Dtests.seed=B4AC2695A7576B7 -Dtests.class=org.elasticsearch.index.replication.IndexLevelReplicationTests -Dtests.method="testCheckpointsAdvance" -Dtests.security.manager=true -Dtests.jvms=2 -Dtests.locale=sk-SK -Dtests.timezone=Etc/GMT+11
FAILURE 1.41s | IndexLevelReplicationTests.testCheckpointsAdvance <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: [test][0], node[s1], [R], s[STARTED], a[id=jOiRILNrSXq-UaYTAotrPg] global checkpoint mismatch
   > Expected: <-2L>
   >      but: was <-1L>
   > 	at __randomizedtesting.SeedInfo.seed([B4AC2695A7576B7:554B23C843CFAD5A]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.index.replication.IndexLevelReplicationTests.testCheckpointsAdvance(IndexLevelReplicationTests.java:187)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> NOTE: leaving temporary files on disk at: /home/hinmanm/es/elasticsearch/core/build/testrun/test/J0/temp/org.elasticsearch.index.replication.IndexLevelReplicationTests_B4AC2695A7576B7-001
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=597, maxMBSortInHeap=5.757966437017982, sim=RandomSimilarity(queryNorm=true): {}, locale=sk-SK, timezone=Etc/GMT+11
  2> NOTE: Linux 4.10.13-200.fc25.x86_64 amd64/Oracle Corporation 1.8.0_111 (64-bit)/cpus=4,threads=1,free=423806312,total=514850816
  2> NOTE: All tests run in this JVM: [IndexLevelReplicationTests]
Completed [1/1] in 2.58s, 1 test, 1 failure <<< FAILURES!
```

And reproduces consistently with

```
gradle :core:test -Dtests.seed=B4AC2695A7576B7 -Dtests.class=org.elasticsearch.index.replication.IndexLevelReplicationTests -Dtests.method="testCheckpointsAdvance" -Dtests.security.manager=true -Dtests.locale=sk-SK -Dtests.timezone=Etc/GMT+11
```

**Comment by jasontedor** [comment]
Closed by b6cb9a4e8a1f644127b5b30acb0c064932a28d8e
