### ISSUE TITLE
[CI] org.elasticsearch.index.reindex.remote.RemoteRequestBuildersTests testInitialSearchParamsFields fails on 5.4 due to extra search params

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#24628]
Seeing this failure:

```
java.lang.AssertionError: 
Expected: map containing ["fields"->"_source,_id,_parent,_routing,_ttl"]
     but: map was [<size=-1>, <fields=_source,_id,_parent,_routing,_ttl,_source>, <version=null>]
	at __randomizedtesting.SeedInfo.seed([AFFEEC0B404892D4:C8CC89B5649DFD1F]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.elasticsearch.index.reindex.remote.RemoteRequestBuildersTests.testInitialSearchParamsFields(RemoteRequestBuildersTests.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

And it reproduces for me with:

```
gradle :modules:reindex:test -Dtests.seed=FDD4FBA1D902995D -Dtests.class=org.elasticsearch.index.reindex.remote.RemoteRequestBuildersTests -Dtests.method="testInitialSearchParamsFields" -Dtests.security.manager=true -Dtests.locale=da -Dtests.timezone=Asia/Pyongyang
```

Here's a failure log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.4+multijob-windows-compatibility/85/console

**Comment by dakrone** [comment]
Marked with awaitsfix in 7eaf201cda1579f8e25b609907b9ca00a5d9abc6
