### ISSUE TITLE
CI Failure :plugins:repository-hdfs:krb5kdcUpdate

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#24641]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.4+java9-periodic/354/consoleFull

On 5.4, I'm not sure what the cause is I can't reproduce, but this stack trace looks suspect:

```
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/shared_helpers.rb:103:in `expand_path': couldn't find HOME environment -- expanding `~' (ArgumentError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/shared_helpers.rb:103:in `expand_path'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/shared_helpers.rb:103:in `user_data_path'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:16:in `user_plugins_file'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:27:in `instance'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant.rb:247:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/bin/vagrant:62:in `<main>'
:plugins:repository-hdfs:krb5kdcUpdate FAILED
```
Assigning to @jbaiera as he touched the gradle build file 2 days ago.

**Comment by jbaiera** [comment]
This is being addressed in https://github.com/elastic/elasticsearch/pull/24636. Tests were muted with https://github.com/elastic/elasticsearch/pull/24643.

**Comment by jbaiera** [comment]
This should be fixed now.
