### ISSUE TITLE
Python plugin is broken in ES 5x

### ISSUE THREAD

**Issue by serj-p** [elastic/elasticsearch#24646]
**Elasticsearch version**: 5.3.2

**Plugins installed**: [lang-python]

**JVM version** (`java -version`): openjdk version "1.8.0_121"

**OS version** : Linux  4.4.23-31.54.amzn1.x86_64

**Description of the problem including expected versus actual behavior**:

Execution of inline python script gives 500 error which is Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/usr/share/elasticsearch/plugins/lang-python/jython-standalone-2.7.0.jar" "read")

I played with elasticsearch/plugins/lang-python/plugin-descriptor.properties and /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/lib/security/java.policy but nothing seems to affect this permission.

**Steps to reproduce**:

1) bin/elasticsearch-plugin install lang-python
2) run any query having script with lang python
3) observe Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/usr/share/elasticsearch/plugins/lang-python/jython-standalone-2.7.0.jar" "read") in logs.

**Provide logs (if relevant)**:
```
[2017-05-12T13:45:27,251][DEBUG][o.e.a.s.TransportSearchAction] [search2c1-es-01] [contacts_v3.2][2], node[S5JR-RacRJqNrqrf6iUBNA], [P], s[STARTED], a[id=_-XvfmEBSKKiluiMo0urgA]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[contacts_v3.2], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_alisases_to_multiple_indices=true, forbid_closed_indices=true], types=[facebook_profile, gplus_profile], routing='null', preference='null', requestCache=null, scroll=null, source={
  "size" : 0,
  "version" : true,
  "_source" : {
    "includes" : [ ],
    "excludes" : [ ]
  },
  "aggregations" : {
    "company_filter" : {
      "filter" : {
        "term" : {
          "company_id" : {
            "value" : "4c2118ad54397f271b000000",
            "boost" : 1.0
          }
        }
      },
      "aggregations" : {
        "pre_filtering" : {
          "filter" : {
            "bool" : {
              "should" : [
                {
                  "bool" : {
                    "filter" : [
                      {
                        "type" : {
                          "value" : "facebook_profile",
                          "boost" : 1.0
                        }
                      },
                      {
                        "nested" : {
                          "query" : {
                            "bool" : {
                              "filter" : [
                                {
                                  "exists" : {
                                    "field" : "education.name",
                                    "boost" : 1.0
                                  }
                                }
                              ],
                              "disable_coord" : false,
                              "adjust_pure_negative" : true,
                              "boost" : 1.0
                            }
                          },
                          "path" : "education",
                          "ignore_unmapped" : false,
                          "score_mode" : "avg",
                          "boost" : 1.0
                        }
                      }
                    ],
                    "disable_coord" : false,
                    "adjust_pure_negative" : true,
                    "boost" : 1.0
                  }
                },
                {
                  "bool" : {
                    "filter" : [
                      {
                        "type" : {
                          "value" : "gplus_profile",
                          "boost" : 1.0
                        }
                      },
                      {
                        "nested" : {
                          "query" : {
                            "bool" : {
                              "filter" : [
                                {
                                  "exists" : {
                                    "field" : "organizations.name",
                                    "boost" : 1.0
                                  }
                                },
                                {
                                  "term" : {
                                    "organizations.otype" : {
                                      "value" : "school",
                                      "boost" : 1.0
                                    }
                                  }
                                }
                              ],
                              "disable_coord" : false,
                              "adjust_pure_negative" : true,
                              "boost" : 1.0
                            }
                          },
                          "path" : "organizations",
                          "ignore_unmapped" : false,
                          "score_mode" : "avg",
                          "boost" : 1.0
                        }
                      }
                    ],
                    "disable_coord" : false,
                    "adjust_pure_negative" : true,
                    "boost" : 1.0
                  }
                }
              ],
              "disable_coord" : false,
              "adjust_pure_negative" : true,
              "boost" : 1.0
            }
          },
          "aggregations" : {
            "top_n_metric" : {
              "scripted_metric" : {
                "init_script" : {
                  "inline" : "from collections import defaultdict;_agg[\"fields_to_parents\"] = defaultdict(set)",
                  "lang" : "python"
                },
                "map_script" : {
                  "inline" : "analyze = lambda t: [w.strip() for w in t.lower().split()];starts = lambda words_pref, words_source: all([any([ws.startswith(wp) for ws in words_source])for wp in words_pref]);SUGGEST = lambda t, f: starts(analyze(t), analyze(f)) if t else True;VARS = {\"text\": u\"\", \"accum\": set([])};C_VARS = {\"nested_field\": u\"name\", \"nested_path\": u\"education\", \"nested_filters\": {}, \"type\": u\"facebook_profile\"};works = (C_VARS[\"type\"] == _doc[\"_type\"][0] and _source.get(C_VARS[\"nested_path\"])) or set();condition = lambda w: C_VARS[\"nested_field\"] in w and all((w.get(nf) == nv) for nf, nv in C_VARS[\"nested_filters\"].iteritems()) and SUGGEST(VARS[\"text\"], w[C_VARS[\"nested_field\"]]);VARS[\"accum\"] |= {w[C_VARS[\"nested_field\"]] for w in works if condition(w)};C_VARS = {\"nested_field\": u\"name\", \"nested_path\": u\"organizations\", \"nested_filters\": {u\"otype\": u\"school\"}, \"type\": u\"gplus_profile\"};works = (C_VARS[\"type\"] == _doc[\"_type\"][0] and _source.get(C_VARS[\"nested_path\"])) or set();condition = lambda w: C_VARS[\"nested_field\"] in w and all((w.get(nf) == nv) for nf, nv in C_VARS[\"nested_filters\"].iteritems()) and SUGGEST(VARS[\"text\"], w[C_VARS[\"nested_field\"]]);VARS[\"accum\"] |= {w[C_VARS[\"nested_field\"]] for w in works if condition(w)};VARS[\"accum\"] = {s.lower().strip() for s in VARS[\"accum\"]};pid = \"\".join(_doc[\"_parent\"]) if VARS[\"accum\"] else None;[_agg[\"fields_to_parents\"][v].add(pid) for v in VARS[\"accum\"]]",
                  "lang" : "python"
                },
                "combine_script" : {
                  "inline" : "{f: list(parents) for f, parents in _agg[\"fields_to_parents\"].iteritems()}",
                  "lang" : "python"
                },
                "reduce_script" : {
                  "inline" : "sorted([(k, len(set(v))) for k, v in reduce(lambda aggregated_dict, d: {kl: (vl + d[kl] if kl in d else vl) for kl, vl in aggregated_dict.iteritems()},filter(None, _aggs),{k: list() for d in filter(None, _aggs) for k in d}).iteritems()], key=lambda kv: kv[1], reverse=True)[:100]",
                  "lang" : "python"
                }
              }
            }
          }
        }
      }
    }
  }
}}] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [search2c1-es-01][172.18.0.16:9300][indices:data/read/search[phase/query]]
Caused by: org.python.core.PyException
        at org.python.core.Py.JavaError(Py.java:546) ~[?:?]
        at org.python.core.PyTableCode.call(PyTableCode.java:170) ~[?:?]
        at org.python.core.PyCode.call(PyCode.java:18) ~[?:?]
        at org.python.core.Py.runCode(Py.java:1386) ~[?:?]
        at org.python.core.__builtin__.eval(__builtin__.java:497) ~[?:?]
        at org.python.core.__builtin__.eval(__builtin__.java:501) ~[?:?]
        at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259) ~[?:?]
        at org.elasticsearch.script.python.PythonScriptEngineService$4.run(PythonScriptEngineService.java:275) ~[?:?]
        at org.elasticsearch.script.python.PythonScriptEngineService$4.run(PythonScriptEngineService.java:272) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at org.elasticsearch.script.python.PythonScriptEngineService.evalRestricted(PythonScriptEngineService.java:272) ~[?:?]
        at org.elasticsearch.script.python.PythonScriptEngineService.access$100(PythonScriptEngineService.java:55) ~[?:?]
        at org.elasticsearch.script.python.PythonScriptEngineService$PythonExecutableScript.run(PythonScriptEngineService.java:176) ~[?:?]
        at org.elasticsearch.search.aggregations.metrics.scripted.ScriptedMetricAggregatorFactory.createInternal(ScriptedMetricAggregatorFactory.java:79) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:221) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorFactory.asMultiBucketAggregator(AggregatorFactory.java:235) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.metrics.scripted.ScriptedMetricAggregatorFactory.createInternal(ScriptedMetricAggregatorFactory.java:63) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:221) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorFactories.createSubAggregators(AggregatorFactories.java:208) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorBase.<init>(AggregatorBase.java:78) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.<init>(BucketsAggregator.java:48) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.bucket.SingleBucketAggregator.<init>(SingleBucketAggregator.java:38) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregator.<init>(FilterAggregator.java:51) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregatorFactory.createInternal(FilterAggregatorFactory.java:51) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:221) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorFactories.createSubAggregators(AggregatorFactories.java:208) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorBase.<init>(AggregatorBase.java:78) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.<init>(BucketsAggregator.java:48) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.bucket.SingleBucketAggregator.<init>(SingleBucketAggregator.java:38) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregator.<init>(FilterAggregator.java:51) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregatorFactory.createInternal(FilterAggregatorFactory.java:51) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:221) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorFactories.createTopLevelAggregators(AggregatorFactories.java:224) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregationPhase.preProcess(AggregationPhase.java:57) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:106) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:247) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:261) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:331) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:328) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:618) [elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.3.2.jar:5.3.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/usr/share/elasticsearch/plugins/lang-python/jython-standalone-2.7.0.jar" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_121]
        at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_121]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_121]
        at java.lang.SecurityManager.checkRead(SecurityManager.java:888) ~[?:1.8.0_121]
        at java.util.zip.ZipFile.<init>(ZipFile.java:210) ~[?:1.8.0_121]
        at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_121]
        at java.util.zip.ZipFile.<init>(ZipFile.java:163) ~[?:1.8.0_121]
        at org.python.modules.zipimport.zipimporter.makeBundle(zipimporter.java:304) ~[?:?]
        at org.python.modules.zipimport.zipimporter.makeBundle(zipimporter.java:38) ~[?:?]
        at org.python.core.util.importer.getModuleCode(importer.java:197) ~[?:?]
        at org.python.core.util.importer.importer_load_module(importer.java:95) ~[?:?]
        at org.python.modules.zipimport.zipimporter.zipimporter_load_module(zipimporter.java:163) ~[?:?]
        at org.python.modules.zipimport.zipimporter$zipimporter_load_module_exposer.__call__(Unknown Source) ~[?:?]
        at org.python.core.PyBuiltinMethodNarrow.__call__(PyBuiltinMethodNarrow.java:46) ~[?:?]
        at org.python.core.imp.loadFromLoader(imp.java:587) ~[?:?]
        at org.python.core.imp.find_module(imp.java:537) ~[?:?]
        at org.python.core.imp.import_next(imp.java:840) ~[?:?]
        at org.python.core.imp.import_module_level(imp.java:959) ~[?:?]
        at org.python.core.imp.importName(imp.java:1062) ~[?:?]
        at org.python.core.ImportFunction.__call__(__builtin__.java:1280) ~[?:?]
        at org.python.core.PyObject.__call__(PyObject.java:431) ~[?:?]
        at org.python.core.__builtin__.__import__(__builtin__.java:1232) ~[?:?]
        at org.python.core.imp.importFromAs(imp.java:1156) ~[?:?]
        at org.python.core.imp.importFrom(imp.java:1132) ~[?:?]
        at org.python.pycode._pyx0.f$0(<script>:1) ~[?:?]
        at org.python.pycode._pyx0.call_function(<script>) ~[?:?]
        at org.python.core.PyTableCode.call(PyTableCode.java:167) ~[?:?]
        at org.python.core.PyCode.call(PyCode.java:18) ~[?:?]
        at org.python.core.Py.runCode(Py.java:1386) ~[?:?]
        at org.python.core.__builtin__.eval(__builtin__.java:497) ~[?:?]
        at org.python.core.__builtin__.eval(__builtin__.java:501) ~[?:?]
        at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259) ~[?:?]
        at org.elasticsearch.script.python.PythonScriptEngineService$4.run(PythonScriptEngineService.java:275) ~[?:?]
        at org.elasticsearch.script.python.PythonScriptEngineService$4.run(PythonScriptEngineService.java:272) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at org.elasticsearch.script.python.PythonScriptEngineService.evalRestricted(PythonScriptEngineService.java:272) ~[?:?]
        at org.elasticsearch.script.python.PythonScriptEngineService.access$100(PythonScriptEngineService.java:55) ~[?:?]
        at org.elasticsearch.script.python.PythonScriptEngineService$PythonExecutableScript.run(PythonScriptEngineService.java:176) ~[?:?]
        at org.elasticsearch.search.aggregations.metrics.scripted.ScriptedMetricAggregatorFactory.createInternal(ScriptedMetricAggregatorFactory.java:79) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:221) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorFactory.asMultiBucketAggregator(AggregatorFactory.java:235) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.metrics.scripted.ScriptedMetricAggregatorFactory.createInternal(ScriptedMetricAggregatorFactory.java:63) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:221) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorFactories.createSubAggregators(AggregatorFactories.java:208) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorBase.<init>(AggregatorBase.java:78) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.<init>(BucketsAggregator.java:48) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.bucket.SingleBucketAggregator.<init>(SingleBucketAggregator.java:38) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregator.<init>(FilterAggregator.java:51) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregatorFactory.createInternal(FilterAggregatorFactory.java:51) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:221) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorFactories.createSubAggregators(AggregatorFactories.java:208) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorBase.<init>(AggregatorBase.java:78) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.<init>(BucketsAggregator.java:48) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.bucket.SingleBucketAggregator.<init>(SingleBucketAggregator.java:38) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregator.<init>(FilterAggregator.java:51) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregatorFactory.createInternal(FilterAggregatorFactory.java:51) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:221) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregatorFactories.createTopLevelAggregators(AggregatorFactories.java:224) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.aggregations.AggregationPhase.preProcess(AggregationPhase.java:57) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:106) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:247) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:261) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:331) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:328) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:618) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-5.3.2.jar:5.3.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.3.2.jar:5.3.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_121]
```

**Comment by markharwood** [comment]
Related with examples of policy grant attempts: https://discuss.elastic.co/t/problem-with-python-scripting/75866

**Comment by jasontedor** [comment]
This does not make sense (we grant read permissions to everything under plugins), and this does not reproduce for me (nor in our tests, of course). I think we need a more through reproduction.

**Comment by serj-p** [comment]
@jasontedor I found what is causing the issue. As soon as I start using std python library it starts to fail. Elasticsearch 2.4 didn't behave like that, but I had security manager disabled.

Minimal example to reproduce:
```
curl -XPOST 127.0.0.1:9200/test_index/test_type -d '{"test":"test"}'

curl -XPOST 127.0.0.1:9200/_search -d '{"aggs": {"test":{"scripted_metric": {"map_script": {"lang": "python", "inline": "lambda: 1"}}}}}' --- works

curl -XPOST 127.0.0.1:9200/_search -d '{"aggs": {"test":{"scripted_metric": {"map_script": {"lang": "python", "inline": "from collections import defaultdict;"}}}}}' --- can't access jython-standalone-2.7.0.jar

```

**Comment by jasontedor** [comment]
This indeed reproduces. Thank you, we will take a look.

**Comment by jasontedor** [comment]
I spent some time looking into this. It looks like this plugin is a lacking a lot of permissions that would make this work due to the restrictions that we place on the script engine for security reasons. It will be difficult to track down exactly which permissions are needed to make this and other cases work without also introducing security issues.  I'll mark this as adopt-me in case anybody is motivated to fix it, but I must tell you that this plugin is deprecated and will be removed in 6.0, so it is quite likely that this will simply never be fixed.

**Comment by jasontedor** [comment]
I think we should close this. It's getting late in the 5.x development cycle for this to be picked up for a deprecated plugin. If someone disagrees, please comment or reopen.

**Comment by SehgalDivij** [comment]
Lend me a hand here. I need to execute some super important python scripts but this gets in the way. Or suggest me the nearest alternative.(I'll try js in the meanwhile)

**Comment by SehgalDivij** [comment]
Update. Seems like JS won't cut it. Reason: I cannot find enough learning material to get going with file based js scripts.
