### ISSUE TITLE
[CI] Netty4HeadBodyIsEmptyIT testHeadRoot (seccomp unavailable)

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#24699]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/2829/consoleFull

Seccomp is logging an interesting error message:

```
  1> java.lang.UnsupportedOperationException: seccomp unavailable: CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER are needed
  1> 	at org.elasticsearch.bootstrap.SystemCallFilter.linuxImpl(SystemCallFilter.java:363) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
  1> 	at org.elasticsearch.bootstrap.SystemCallFilter.init(SystemCallFilter.java:638) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
  1> 	at org.elasticsearch.bootstrap.JNANatives.tryInstallSystemCallFilter(JNANatives.java:215) [elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
  1> 	at org.elasticsearch.bootstrap.Natives.tryInstallSystemCallFilter(Natives.java:99) [elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
  1> 	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:110) [elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
  1> 	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:80) [framework-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
```

Does not reproduce
gradle :modules:transport-netty4:integTestRunner -Dtests.seed=E74D7E67115C9823 -Dtests.class=org.elasticsearch.rest.Netty4HeadBodyIsEmptyIT -Dtests.method="testHeadRoot" -Dtests.security.manager=true -Dtests.locale=hu -Dtests.timezone=CST6CDT

Assiging to @rjernst by default, sorry if I'm mistaken

**Comment by s1monw** [comment]
I think that's just due to the fact that it's not available on this slave? That's not an issue IMO. The test failure is unrelated to seccomp.

**Comment by davidkyle** [comment]
@s1monw Makes sense, closing the issue.
