### ISSUE TITLE
[CI] IdsQueryBuilderTests testToQuery Failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#24708]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-unix-compatibility/os=debian/776/console

Reproduces with 
```
 gradle :core:test -Dtests.seed=98CCA12A2C5B5C36 -Dtests.class=org.elasticsearch.index.query.IdsQueryBuilderTests -Dtests.method="testToQuery" -Dtests.security.manager=true -Dtests.locale=cs -Dtests.timezone=Etc/GMT+8
```

```
   > Throwable #1: java.lang.AssertionError: 
   > Expected: an instance of org.elasticsearch.common.lucene.search.MatchNoDocsQuery
   >      but: <MatchNoDocsQuery("No mappings")> is a org.apache.lucene.search.MatchNoDocsQuery
   >    at __randomizedtesting.SeedInfo.seed([98CCA12A2C5B5C36:6F37A3145DD899DC]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.index.query.IdsQueryBuilderTests.doAssertLuceneQuery(IdsQueryBuilderTests.java:77)
   >    at org.elasticsearch.index.query.IdsQueryBuilderTests.doAssertLuceneQuery(IdsQueryBuilderTests.java:36)
   >    at org.elasticsearch.test.AbstractQueryTestCase.assertLuceneQuery(AbstractQueryTestCase.java:675)
   >    at org.elasticsearch.test.AbstractQueryTestCase.testToQuery(AbstractQueryTestCase.java:589)
   >    at java.lang.Thread.run(Thread.java:745)
```

@jpountz the random task picker has assigned this one to you

**Comment by davidkyle** [comment]
Closed by https://github.com/elastic/elasticsearch/commit/db3d1286708fe905ec29a670e660ac79b6c3ba41

**Comment by jpountz** [comment]
Thanks @jimczi and @davidkyle !
