### ISSUE TITLE
[CI]  SimpleValidateQueryIT#testExplainWithRewriteValidateQueryAllShards Failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#24718]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-intake/1206/consoleFull

Reproducible failure with the stack trace:
```
   > Expected: "+MatchNoDocsQuery(\"empty MultiPhraseQuery\") +MatchNoDocsQuery[\"No terms supplied for org.elasticsearch.common.lucene.search.MultiPhrasePrefixQuery\"]"
   >      but: was "+MatchNoDocsQuery(\"empty MultiPhraseQuery\") +MatchNoDocsQuery(\"No terms supplied for org.elasticsearch.common.lucene.search.MultiPhrasePrefixQuery\")"
   > 	at __randomizedtesting.SeedInfo.seed([16B67BC72A108FF:C94BDD019D2226CD]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.validate.SimpleValidateQueryIT.assertExplanations(SimpleValidateQueryIT.java:334)
   > 	at org.elasticsearch.validate.SimpleValidateQueryIT.testExplainWithRewriteValidateQueryAllShards(SimpleValidateQueryIT.java:283)
```

Reproduce with:
```
gradle :core:integTest -Dtests.seed=16B67BC72A108FF -Dtests.class=org.elasticsearch.validate.SimpleValidateQueryIT -Dtests.method="testExplainWithRewriteValidateQueryAllShards" -Dtests.security.manager=true -Dtests.locale=hi -Dtests.timezone=Mexico/General
```

**Comment by jimczi** [comment]
Thanks @davidkyle 
I pushed https://github.com/elastic/elasticsearch/commit/9597c1c5cb7b4eced8ff4004662c0ee2112343e3
