### ISSUE TITLE
es.pid file not deleted when integration tests failed / crashed

### ISSUE THREAD

**Issue by jsuchenia** [elastic/elasticsearch#24715]
**Elasticsearch version**:
5.4.0
**Plugins installed**: []
I'm compiling my own plugin

**JVM version** (`java -version`):
Oracle Corporation 1.8.0_65 [Java HotSpot(TM) 64-Bit Server VM 25.65-b01]

**OS version** (`uname -a` if on a Unix-like system):
Mac OS X 10.12.4 (x86_64)

**Gradle version**:
3.5

**Description of the problem including expected versus actual behaviour**:
When compiling my own, standalone plugin with integration test I'm getting an error:
```
:integTestCluster#init UP-TO-DATE
:integTestCluster#prepareCluster.cleanShared
:integTestCluster#clean
:integTestCluster#checkPrevious
jps -l
48050 org.gradle.launcher.daemon.bootstrap.GradleDaemon
46947 org.jetbrains.idea.maven.server.RemoteMavenServer
48115 sun.tools.jps.Jps
48102 org.gradle.wrapper.GradleWrapperMain
46873

:integTestCluster#checkPrevious FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integTestCluster#checkPrevious'.
> Could not get unknown property 'pidFile' for task ':integTestCluster#checkPrevious' of type org.gradle.api.tasks.Exec.
```
**Steps to reproduce**:
Problem is visible from-time-to-time, after failed integration test there is a file es.pid with old pid.
To reproduce:
 ```
echo 1234 > ./build/cluster/integTestCluster\ node0/es.pid
```

Solution is to delete a file:
```
rm ./build/cluster/integTestCluster\ node0/es.pid
```
This problem happened when I created two tests that inherits from `ESRestTestCase`, one failed and created unresolvable problem (left pid file on a disk)

**Provide logs (if relevant)**:
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':integTestCluster#checkPrevious'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:98)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:68)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'pidFile' for task ':integTestCluster#checkPrevious' of type org.gradle.api.tasks.Exec.
        at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:85)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:62)
        at org.gradle.api.tasks.Exec_Decorated.getProperty(Unknown Source)
        at org.elasticsearch.gradle.test.ClusterFormationTasks$_configureCheckPreviousTask_closure26$_closure51.doCall(ClusterFormationTasks.groovy:642)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:656)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:637)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:115)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:90)
        ... 20 more
```

**Comment by nik9000** [comment]
I've seen this from time to time when I crash a node while doing `gradle run`.

**Comment by jasontedor** [comment]
Clean up here is never going to be perfect, gradle clean solves the issue.

**Comment by jsuchenia** [comment]
@jasontedor Root cause of this ticket is that error code is misleading because there is a bug in an exception handling. Here is a simple fix (there are no `pidFile` and `pid` variables, you have to use `node.pidFile` and `ext.pid`:
```
diff --git a/buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy b/buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy
index b5a70c86ad..6ad3361e61 100644
--- a/buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy
+++ b/buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy
@@ -639,8 +639,8 @@ class ClusterFormationTasks {
                 if (out.contains("${pid} org.elasticsearch.bootstrap.Elasticsearch") == false) {
                     logger.error('jps -l')
                     logger.error(out)
-                    logger.error("pid file: ${pidFile}")
-                    logger.error("pid: ${pid}")
+                    logger.error("pid file: ${node.pidFile}")
+                    logger.error("pid: ${ext.pid}")
                     throw new GradleException("jps -l did not report any process with org.elasticsearch.bootstrap.Elasticsearch\n" +
                             "Did you run gradle clean? Maybe an old pid file is still lying around.")
                 } else {
```

**Comment by jasontedor** [comment]
Thanks for that @jsuchenia! I pushed 8e2ab43009f4c3b5af349829464622180c853a99 and 73315eca1178613099aacf080e0b2fb7436a2e1a.
