### ISSUE TITLE
Test Failure on 5.4 FieldStatsTests

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#24739]
Reproduces and related to [this commit ](https://github.com/elastic/elasticsearch/commit/8659a5d419cdead65427fa43579e68b69559eef8)

	REPRODUCE WITH: gradle :core:test -Dtests.seed=8942B50F37BCF6AA -Dtests.class=org.elasticsearch.fieldstats.FieldStatsTests -Dtests.method="testGeopoint" -Dtests.security.manager=true -Dtests.locale=sr-Latn-BA -Dtests.timezone=Africa/Sao_Tome
	ERROR   0.13s J1 | FieldStatsTests.testGeopoint <<< FAILURES!
	Throwable #1: java.lang.NullPointerException
		at __randomizedtesting.SeedInfo.seed([8942B50F37BCF6AA:F140AF8BC223C385]:0)
		at org.elasticsearch.fieldstats.FieldStatsTests.testGeopoint(FieldStatsTests.java:709)
		at java.lang.Thread.run(Thread.java:745)
	[2017-05-17T12:50:11,996][INFO ][o.e.f.FieldStatsTests    ] [testDouble]: before test

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.4+multijob-unix-compatibility/os=amazon/98/console

**Comment by davidkyle** [comment]
Closing as already tracked in #24703
