### ISSUE TITLE
default.path.repo removed from ES 5.4?

### ISSUE THREAD

**Issue by trawler** [elastic/elasticsearch#24741]
I was trying to set up a shared NFS directory for ES snapshots, per the documentation here: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#_shared_file_system_repository

I found that adding:
```
path:
  repo:
   - /opt/backup
```
or 
`path.repo: [ "/opt/backup" ]
`
 to elasticsearch.yml, but no matter how I tried, I couldn't get ES to recognise this path:
```
Caused by: org.elasticsearch.repositories.RepositoryException: [kibana_backup] location [/opt/backup] doesn't match any of the locations specified by path.repo because this setting is empty
        at org.elasticsearch.repositories.fs.FsRepository.<init>(FsRepository.java:91) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.repositories.RepositoriesModule.lambda$new$0(RepositoriesModule.java:49) ~[elasticsearch-5.4.0.jar:5.4.0]
```

So after some digging, I decided to add the following lines to /usr/lib/systemd/system/elasticsearch:

```
[Service]
Environment=ES_HOME=/usr/share/elasticsearch
Environment=CONF_DIR=/etc/elasticsearch
Environment=DATA_DIR=/var/lib/elasticsearch
Environment=LOG_DIR=/var/log/elasticsearch
Environment=PID_DIR=/var/run/elasticsearch
Environment=REPO_DIR=/opt/backup


ExecStart=/usr/share/elasticsearch/bin/elasticsearch \
                                                -p ${PID_DIR}/elasticsearch.pid \
                                                --quiet \
                                                -Edefault.path.logs=${LOG_DIR} \
                                                -Edefault.path.data=${DATA_DIR} \
                                                -Edefault.path.repo=${REPO_DIR} \
                                                -Edefault.path.conf=${CONF_DIR}

```

But after restarting the service, I get this error in the log file:

```
java.lang.IllegalArgumentException: unknown setting [default.path.repo] did you mean any of [default.path.conf, default.path.logs]?
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:293) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:256) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:139) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.node.Node.<init>(Node.java:342) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.4.0.jar:5.4.0]
```

**Elasticsearch version**:
`5.4.0`

**JVM version** 
`1.8.0_102`

**OS version** 
`Ubuntu 16.04.2 LTS`

**Comment by jasontedor** [comment]
This is covered in the [migration docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-5.4.html#breaking_54_settings_changes) for 5.4.0.
