### ISSUE TITLE
Spaces within comma separated list value for action.auto_create_index results in 'value is too restrictive' error on startup

### ISSUE THREAD

**Issue by geekpete** [elastic/elasticsearch#24784]
**Elasticsearch version**: 

**Plugins installed**: []

**JVM version** (`java -version`): 
```
$ java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system): 
OSX 
```
Darwin  16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
```
**Description of the problem including expected versus actual behavior**:
Spaces within comma separated list value for action.auto_create_index results in value is too restrictive error on startup

**Steps to reproduce**:

Existing ticket for similar error but fix only addressed whitespace at head/tail of the value string using .trim():
https://github.com/elastic/elasticsearch/issues/21449

To replicate, unzip a specific version tarball of Elasticsearch, edit the elasticsearch.yml and add the config line to the end.

Adding this will result in a working start up:
```
action.auto_create_index: .monitoring-kibana*,.monitoring-data*,.watches,.kibana,.watcher-history*,.monitoring-es*,.security,.triggered_watches
```

When the csv list has spaces after commas (or even just one space in one location after a comma):
```
action.auto_create_index: .monitoring-kibana*, .monitoring-data*, .watches, .kibana, .watcher-history*, .monitoring-es*, .security, .triggered_watches
```

then Elasticsearch startup will fail with:

```
[2017-05-19T14:23:29,005][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Failed to load plugin class [org.elasticsearch.xpack.XPackPlugin]]; nested: InvocationTargetException; nested: IllegalArgumentException[the [action.auto_create_index] setting value [.monitoring-kibana*,.monitoring-data*,.watches,.kibana,.watcher-history*,.monitoring-es*, .security,.triggered_watches] is too restrictive. disable [action.auto_create_index] or set it to [.security]];
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.3.2.jar:5.3.2]
Caused by: org.elasticsearch.ElasticsearchException: Failed to load plugin class [org.elasticsearch.xpack.XPackPlugin]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:394) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:346) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.node.Node.<init>(Node.java:309) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.2.jar:5.3.2]
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_77]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:383) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:346) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.node.Node.<init>(Node.java:309) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.2.jar:5.3.2]
	... 6 more
Caused by: java.lang.IllegalArgumentException: the [action.auto_create_index] setting value [.monitoring-kibana*,.monitoring-data*,.watches,.kibana,.watcher-history*,.monitoring-es*, .security,.triggered_watches] is too restrictive. disable [action.auto_create_index] or set it to [.security]
	at org.elasticsearch.xpack.security.Security.validateAutoCreateIndex(Security.java:718) ~[?:?]
	at org.elasticsearch.xpack.security.Security.<init>(Security.java:208) ~[?:?]
	at org.elasticsearch.xpack.XPackPlugin.<init>(XPackPlugin.java:200) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_77]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:383) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:346) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.node.Node.<init>(Node.java:309) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.3.2.jar:5.3.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.3.2.jar:5.3.2]
	... 6 more
```

Tested against the following versions:
- 5.0.0 - no error
- 5.0.1 - error
- 5.0.2 - no error
- 5.1.1 - error
- 5.1.2 - no error
- 5.3.2 - error
- 5.4.0 - error

So the documentation example shows no space after commas:
>Automatic index creation can include a pattern based white/black list, for example, set action.auto_create_index to +aaa*,-bbb*,+ccc*,-* (+ meaning allowed, and - meaning disallowed).

https://www.elastic.co/guide/en/elasticsearch/reference/5.4/docs-index_.html#index-creation

If we want to be strict then we could both mention the strict requirement in the docs and throw a clearer error in the logs "no spaces allowed in the comma separated list",etc.

**Comment by martijnvg** [comment]
Looks like an xpack issue and moved the issue there.
