### ISSUE TITLE
An assertion trips when master opens an index from before 5.x

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#24809]
When running with assertions enabled and starting up with an index from before those made by the 5.x branch this exception is thrown:

```
|    [2017-05-19T14:51:32,710][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-1] fatal error in thread [elasticsearch[node-1][generic][T#4]], exiting
|    java.lang.AssertionError: recovery from remote but max_unsafe_auto_id_timestamp is not found in commit
|       at org.elasticsearch.index.shard.IndexShard.assertMaxUnsafeAutoIdInCommit(IndexShard.java:1093) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
|       at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:1072) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
|       at org.elasticsearch.index.shard.IndexShard.skipTranslogRecovery(IndexShard.java:1115) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
|       at org.elasticsearch.indices.recovery.RecoveryTarget.prepareForTranslogOperations(RecoveryTarget.java:362) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
|       at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$PrepareForTranslogOperationsRequestHandler.messageReceived(PeerRecoveryTargetService.java:385) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
|       at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$PrepareForTranslogOperationsRequestHandler.messageReceived(PeerRecoveryTargetService.java:379) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
|       at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
|       at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
|       at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1501) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
|       at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
|       at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
|       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_111]
|       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_111]
|       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by bleskes** [comment]
just to be clear - which version made the index?

**Comment by nik9000** [comment]
5.0.0-5.4.1 seem to have this problem.

**Comment by nik9000** [comment]
I didn't check 2.x because those aren't supposed to work.

**Comment by bleskes** [comment]
closed by https://github.com/bleskes/elasticsearch/commit/e4aa18451c0b8301579d5d8cd3c03504b20fb458
