### ISSUE TITLE
Unable to send the json documents to elasticsearch server

### ISSUE THREAD

**Issue by shyamalaponnada** [elastic/elasticsearch#24805]
Hi everyone,

I have able to start the ES and trying to send the json document to the server by using
curl -XPUT 'http://localhost:9200/test/test/1' -d @test22.json
but i am getting the error "curl: (52) Empty reply from server"

i have checked my log file it throwing an error of below
atio.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
atio.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
atio.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:474)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:428)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
        at java.lang.Thread.run(Thread.java:745)

Can any one suggest me what is the issue and how to fix it?

**Comment by jasontedor** [comment]
We can not assess this without the contents of `test22.json`, and seeing the full log message would help. Yet, Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
