### ISSUE TITLE
new plugins add into elasticsearch when invoking the plugins appear a big problem

### ISSUE THREAD

**Issue by liuguangmin** [elastic/elasticsearch#24839]
elasticsearch :5.3.0
java:1.8.0
OS:linux
maven configuration :: 
	<name>es-segment</name>
	<url>http://maven.apache.org</url>

	<properties>
		<elasticsearch.version>5.3.0</elasticsearch.version>
		<jdk.version>1.8</jdk.version>
		<encode.version>UTF-8</encode.version>
		<gson.version>2.7</gson.version>
		<junit.version>4.12</junit.version>
		<commons.version>2.4.2</commons.version>
		<thrift.version>0.9.3</thrift.version>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>${jdk.version}</source>
					<target>${jdk.version}</target>
					<skipTests>true</skipTests>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.10</version>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/lib</outputDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.elasticsearch</groupId>
			<artifactId>elasticsearch</artifactId>
			<version>${elasticsearch.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.thrift</groupId>
			<artifactId>libthrift</artifactId>
			<version>${thrift.version}</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>${gson.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			# <artifactId>commons-pool2</artifactId>
			<version>${commons.version}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.6.4</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.6.4</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
		</dependency>
	</dependencies>
# I develop a analyzer plugin through rpc invoke the analyzer.the analyzer plugin is normal load ,but when I  invoke the analyzer , a big problem is print ,
the analyzer is setting below:
PUT /my_index
{
  "settings": {
    "analysis": {
      "analyzer": {
        "name_analyzer": {
          "type":"nlp_rpc",
          "rpcHost": "127.0.0.9",
          "rpcPort": 9999,
          "segMode": "search",
          "withStopWord": false,
          "poolSize": 200
        }
      }
    }
  }
}
# And the opeartion is run normal,I invoke the analyzer as below:
GET my_index/_analyze
{
  "analyzer":"name_analyzer",
  "text":"elasticsearch is great ! And I love elasticsearch very much!"
}
# when I run the opeartion ,the error happen:
[2017-05-23T17:34:03,817][DEBUG][o.e.a.a.i.a.TransportAnalyzeAction] [es-1] null: failed to execute [org.elasticsearch.action.admin.indices.analyze.AnalyzeRequest@3d063b00]
org.elasticsearch.transport.RemoteTransportException: [es-1][10.25.114.90:9301][indices:admin/analyze[s]]
Caused by: java.security.AccessControlException: access denied ("javax.management.MBeanServerPermission" "createMBeanServer")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_121]
        at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_121]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_121]
        at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:465) ~[?:1.8.0_121]
        at org.apache.commons.pool2.impl.BaseGenericObjectPool.jmxRegister(BaseGenericObjectPool.java:940) ~[?:?]
        at org.apache.commons.pool2.impl.BaseGenericObjectPool.<init>(BaseGenericObjectPool.java:133) ~[?:?]
        at org.apache.commons.pool2.impl.GenericObjectPool.<init>(GenericObjectPool.java:107) ~[?:?]
        at com.datagrand.rpc.client.WordsegRpcClientPool.<init>(WordsegRpcClientPool.java:27) ~[?:?]
        at com.datagrand.rpc.client.WordsegRpcClientPool.getPool(WordsegRpcClientPool.java:47) ~[?:?]
        at com.datagrand.analysis.lucene.WordsegRpcTokenizer.<init>(WordsegRpcTokenizer.java:35) ~[?:?]
        at com.datagrand.analysis.lucene.WordsegRpcAnalyzer.createComponents(WordsegRpcAnalyzer.java:29) ~[?:?]
        at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:134) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
        at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:198) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.simpleAnalyze(TransportAnalyzeAction.java:216) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:201) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:149) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:76) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:294) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:287) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:618) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:613) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.3.0.jar:5.3.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[2017-05-23T17:34:03,831][WARN ][r.suppressed             ] path: /my_index/_analyze, params: {index=my_index}
org.elasticsearch.transport.RemoteTransportException: [es-1][10.25.114.90:9301][indices:admin/analyze[s]]
Caused by: java.security.AccessControlException: access denied ("javax.management.MBeanServerPermission" "createMBeanServer")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_121]
        at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_121]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_121]
        at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:465) ~[?:1.8.0_121]
        at org.apache.commons.pool2.impl.BaseGenericObjectPool.jmxRegister(BaseGenericObjectPool.java:940) ~[?:?]
        at org.apache.commons.pool2.impl.BaseGenericObjectPool.<init>(BaseGenericObjectPool.java:133) ~[?:?]
        at org.apache.commons.pool2.impl.GenericObjectPool.<init>(GenericObjectPool.java:107) ~[?:?]
        at com.datagrand.rpc.client.WordsegRpcClientPool.<init>(WordsegRpcClientPool.java:27) ~[?:?]
        at com.datagrand.rpc.client.WordsegRpcClientPool.getPool(WordsegRpcClientPool.java:47) ~[?:?]
        at com.datagrand.analysis.lucene.WordsegRpcTokenizer.<init>(WordsegRpcTokenizer.java:35) ~[?:?]
        at com.datagrand.analysis.lucene.WordsegRpcAnalyzer.createComponents(WordsegRpcAnalyzer.java:29) ~[?:?]
        at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:134) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
        at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:198) ~[lucene-core-6.4.1.jar:6.4.1 72f75b2503fa0aa4f0aff76d439874feb923bb0e - jpountz - 2017-02-01 14:43:32]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.simpleAnalyze(TransportAnalyzeAction.java:216) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:201) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:149) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:76) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:294) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:287) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:618) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:613) [elasticsearch-5.3.0.jar:5.3.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.3.0.jar:5.3.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
==================================
#my elasticsearch  course as below:
searcho+ 13747  3.6 16.7 12496288 2731836 pts/0 Sl+ 17:27   0:58 /bin/java -Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -server -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -Djdk.io.permissionsUseCanonicalPath=true -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -XX:+HeapDumpOnOutOfMemoryError -Des.path.home=/data/searchonline/test_es/elasticsearch-5.3.0 -cp /data/searchonline/test_es/elasticsearch-5.3.0/lib/elasticsearch-5.3.0.jar:/data/searchonline/test_es/elasticsearch-5.3.0/lib/* org.elasticsearch.bootstrap.Elasticsearch

**Comment by jasontedor** [comment]
Elasticsearch runs under the security manager. Plugins require permissions. As a developer you have to add them. This is covered in the [plugin docs](https://www.elastic.co/guide/en/elasticsearch/plugins/5.4/plugin-authors.html#plugin-authors-jsm). If you need help please use the [forum](https://discuss.elastic.co).

**Comment by liuguangmin** [comment]
THX  I had solved the problem add  the security manager
