### ISSUE TITLE
[TEST] Auto queue sizing test failure

### ISSUE THREAD

**Issue by abeyad** [elastic/elasticsearch#24832]
The `QueueResizingEsThreadPoolExecutorTests#testAutoQueueSizingDown` test failed today, though I cannot reproduce the failure locally.

Reproduce line:
```
gradle :core:test -Dtests.seed=635A179DD82A56EF -Dtests.class=org.elasticsearch.common.util.concurrent.QueueResizingEsThreadPoolExecutorTests -Dtests.method="testAutoQueueSizingDown" -Dtests.security.manager=true -Dtests.locale=fi -Dtests.timezone=US/Mountain
```

Error:
```
ERROR   0.25s J0 | QueueResizingEsThreadPoolExecutorTests.testAutoQueueSizingDown <<< FAILURES!
   > Throwable #1: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=61, name=queuetest[T#7], state=RUNNABLE, group=TGRP-QueueResizingEsThreadPoolExecutorTests]
   > 	at __randomizedtesting.SeedInfo.seed([635A179DD82A56EF:F542F5E48CE974A7]:0)
   > Caused by: java.lang.AssertionError: cannot calculate for instantaneous tasks
   > 	at __randomizedtesting.SeedInfo.seed([635A179DD82A56EF]:0)
   > 	at org.elasticsearch.common.util.concurrent.QueueResizingEsThreadPoolExecutor.calculateLambda(QueueResizingEsThreadPoolExecutor.java:98)
   > 	at org.elasticsearch.common.util.concurrent.QueueResizingEsThreadPoolExecutor.afterExecute(QueueResizingEsThreadPoolExecutor.java:150)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1150)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dakrone** [comment]
Link to logs in case I need them: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/2908/console

**Comment by dakrone** [comment]
I pushed some additional assert logging in 82a369737b59b9230813841ceb7d611c22e21755

**Comment by dakrone** [comment]
Resolved in https://github.com/elastic/elasticsearch/commit/fe02350e73701abb283084325daf999f580244a4
