### ISSUE TITLE
Unable to set script.allowed_types/allowed_contexts in elasticsearch.yml

### ISSUE THREAD

**Issue by ycombinator** [elastic/elasticsearch#24830]
**Elasticsearch version**: `master`, with `build_date`: `2017-05-22T16:59:52.342Z` and `build_hash`: 5ae48f7

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_121

**OS version** (`uname -a` if on a Unix-like system): Mac OS X 10.12.4

**Description of the problem including expected versus actual behavior**:

I was unable to set either the `script.allowed_types` or the `script.allowed_contexts` setting in `elasticsearch.yml`. Upon starting up Elasticsearch, the following exception is thrown:

```
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [script.allowed_contexts] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
```

Complete stack trace is further below.

**Steps to reproduce**:

1. Edit `elasticsearch.yml`.
2. Set `script.allowed_types: none`.
3. Start elasticsearch.
4. Repeat steps for `script.allowed_contexts: none`.

**Provide logs (if relevant)**:

```
[2017-05-22T10:56:43,463][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [script.allowed_contexts] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
Caused by: java.lang.IllegalArgumentException: unknown setting [script.allowed_contexts] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:293) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:256) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
        at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:139) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
        at org.elasticsearch.node.Node.<init>(Node.java:332) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
        at org.elasticsearch.node.Node.<init>(Node.java:241) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:330) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-6.0.0-alpha2-SNAPSHOT.jar:6.0.0-alpha2-SNAPSHOT]
        ... 6 more
```

**Comment by s1monw** [comment]
@jdconrad can you take a look

**Comment by jdconrad** [comment]
Argh, I think I simply typed the setting names incorrectly :/

It should be script.types_allowed and script.contexts_allowed

**Comment by ycombinator** [comment]
Yep, those worked! Sounds like this is just a doc update issue then. Thanks @jdconrad!

**Comment by jdconrad** [comment]
@ycombinator I'm actually going to change this to *match* the documentation, so please don't get attached to the current ones.
