### ISSUE TITLE
How to get environment variblae in elasticsearch.yml file in elasticsearch-5.4.0

### ISSUE THREAD

**Issue by Git-Rajkumar** [elastic/elasticsearch#24882]
I have installed elasticsearch-5.4.0, **its not take my envornoment variable in elasticsearch.yml file**  
its throw "**Exception in thread "main" java.lang.IllegalArgumentException: Could not resolve placeholder 'DOCKER_IP**'"
I follow this [document](https://www.elastic.co/guide/en/beats/filebeat/current/using-environ-vars.html), same confiuration works in elasticsearch2.4.2, but not works 5.4.0 
        
 **elasticsearch.yml:**

            network.host: ${DOCKER_IP}
             http.port: 9200
             action.destructive_requires_name: true

**Full Error:**

                Exception in thread "main" java.lang.IllegalArgumentException: Could not resolve placeholder 'DOCKER_IP'
           	at org.elasticsearch.common.settings.PropertyPlaceholder.parseStringValue(PropertyPlaceholder.java:116)
           	at org.elasticsearch.common.settings.PropertyPlaceholder.replacePlaceholders(PropertyPlaceholder.java:69)
           	at org.elasticsearch.common.settings.Settings$Builder.replacePropertyPlaceholders(Settings.java:1096)
           	at org.elasticsearch.common.settings.Settings$Builder.replacePropertyPlaceholders(Settings.java:1056)
           	at org.elasticsearch.node.InternalSettingsPreparer.initializeSettings(InternalSettingsPreparer.java:136)
           	at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:115)
           	at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:72)
           	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
           	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
           	at org.elasticsearch.cli.Command.main(Command.java:88)
           	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
           	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)

       Suggest me How to fix this issue.

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

I see you opened there https://discuss.elastic.co/t/how-to-get-environment-variblae-in-elasticsearch-yml-file-in-elasticsearch-5-4-0/87091/1 so let's keep the discussion there.

**Comment by colings86** [comment]
I just tried this on 5.4.0 and it picked up my environment variable fine so I don't think there is a bug here. The most likely cause is that `DOCKER_IP` is not being set in your environment so Elasticsearch is not able to resolve the value, I would check your environment to see why the variable might not be set. If you have further questions please raise them on https://discuss.elastic.co

**Comment by Git-Rajkumar** [comment]
@colings86  my environment variable set correctly , I tried to get DOCKER_IP value via terminal its get right value.
   
      echo $DOCKER_IP
