### ISSUE TITLE
SearchResponseTests.testFromXContent fails with a specific seed

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#24891]
Log is here: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu/1022/consoleFull

The problem reproduces locally for me:

```
gradle :core:test -Dtests.seed=F9669D4F3CD3E5FA -Dtests.class=org.elasticsearch.action.search.SearchResponseTests -Dtests.method="testFromXContent" -Dtests.security.manager=true -Dtests.locale=es-CO -Dtests.timezone=Europe/Podgorica
```

The error is this:

```
ERROR   26.7s | SearchResponseTests.testFromXContent <<< FAILURES!
   > Throwable #1: java.lang.OutOfMemoryError: GC overhead limit exceeded
   >    at __randomizedtesting.SeedInfo.seed([F9669D4F3CD3E5FA:D80EA857B5740520]:0)
   >    at java.util.LinkedHashMap.newNode(LinkedHashMap.java:256)
   >    at java.util.HashMap.putVal(HashMap.java:630)
   >    at java.util.HashMap.put(HashMap.java:611)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:978)
   >    at org.elasticsearch.test.ESTestCase.shuffleList(ESTestCase.java:955)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:976)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:974)
   >    at org.elasticsearch.test.ESTestCase.shuffleList(ESTestCase.java:955)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:976)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:974)
   >    at org.elasticsearch.test.ESTestCase.shuffleList(ESTestCase.java:955)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:976)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:974)
   >    at org.elasticsearch.test.ESTestCase.shuffleList(ESTestCase.java:955)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:976)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:974)
   >    at org.elasticsearch.test.ESTestCase.shuffleList(ESTestCase.java:955)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:976)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:974)
   >    at org.elasticsearch.test.ESTestCase.shuffleList(ESTestCase.java:955)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:976)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:974)
   >    at org.elasticsearch.test.ESTestCase.shuffleMap(ESTestCase.java:974)
   >    at org.elasticsearch.test.ESTestCase.shuffleXContent(ESTestCase.java:943)
   >    at org.elasticsearch.test.ESTestCase.toShuffledXContent(ESTestCase.java:908)
   >    at org.elasticsearch.action.search.SearchResponseTests.testFromXContent(SearchResponseTests.java:104)
```

Failure is seed-specific, as this works:

```
gradle :core:test -Dtests.class=org.elasticsearch.action.search.SearchResponseTests -Dtests.method="testFromXContent" -Dtests.security.manager=true
```

**Comment by droberts195** [comment]
@jpountz the build triage doc said search issues should be assigned to you - please reassign if I've misinterpreted which area this failure is in.

**Comment by javanna** [comment]
@trlx was looking at this the other day, this failure has to do with search response parsing for the high level REST client.

**Comment by nik9000** [comment]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu/1039/console

```
Suite: org.elasticsearch.action.search.SearchResponseTests
  1> [2017-05-30T15:12:57,391][INFO ][o.e.a.s.SearchResponseTests] [testToXContent]: before test
  2> REPRODUCE WITH: gradle :core:test -Dtests.seed=A6FB15086B495830 -Dtests.class=org.elasticsearch.action.search.SearchResponseTests -Dtests.method="testFromXContent" -Dtests.security.manager=true -Dtests.locale=zh-CN -Dtests.timezone=PLT
  1> [2017-05-30T15:12:57,394][INFO ][o.e.a.s.SearchResponseTests] [testToXContent]: after test
  1> [2017-05-30T15:12:57,396][INFO ][o.e.a.s.SearchResponseTests] [testFromXContentWithFailures]: before test
  1> [2017-05-30T15:12:57,487][INFO ][o.e.a.s.SearchResponseTests] [testFromXContentWithFailures]: after test
  1> [2017-05-30T15:12:57,489][INFO ][o.e.a.s.SearchResponseTests] [testFromXContent]: before test
  1> [2017-05-30T15:13:28,060][INFO ][o.e.a.s.SearchResponseTests] [testFromXContent]: after test
ERROR   30.6s J2 | SearchResponseTests.testFromXContent <<< FAILURES!
   > Throwable #1: java.lang.OutOfMemoryError: GC overhead limit exceeded
   > 	at __randomizedtesting.SeedInfo.seed([A6FB15086B495830:87932010E2EEB8EA]:0)
   > 	at java.util.HashMap.resize(HashMap.java:703)
   > 	at java.util.HashMap.putVal(HashMap.java:628)
   > 	at java.util.HashMap.put(HashMap.java:611)
   > 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:321)
   > 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:378)
   > 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:320)
   > 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:378)
   > 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readList(AbstractXContentParser.java:363)
   > 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:380)
   > 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:320)
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-unix-compatibility/os/ubuntu/core/build/testrun/test/J2/temp/org.elasticsearch.action.search.SearchResponseTests_A6FB15086B495830-001
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=831, maxMBSortInHeap=5.329173905152863, sim=RandomSimilarity(queryNorm=false): {}, locale=zh-CN, timezone=PLT
  2> NOTE: Linux 4.8.0-51-generic amd64/Oracle Corporation 1.8.0_131 (64-bit)/cpus=8,threads=1,free=445461912,total=477626368
   > 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:378)
   > 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:320)
   > 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:378)
   > 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:320)
   > 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:378)
   > 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readList(AbstractXContentParser.java:363)
   > 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:380)
   > 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:320)
   > 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:378)
   > 	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:320)
```
