### ISSUE TITLE
ES error :Negative longs unsupported, use writeLong or writeZLong for negative numbers [-1]

### ISSUE THREAD

**Issue by liuguangmin** [elastic/elasticsearch#24918]
ES:5.4.0
java:1.8
OS:linux

# when I run the ES a week time ,I find the ES cluster console print:
========================== ===========================
[2017-05-27T11:15:08,145][DEBUG][o.e.a.a.i.s.TransportIndicesStatsAction] [datagrand-master-2] failed to execut
e [indices:monitor/stats] on node [csuTIh78RTGau49x96OeDA]
org.elasticsearch.transport.RemoteTransportException: [datagrand-data-4][10.171.56.84:9300][indices:monitor/sta
ts[n]]
Caused by: java.lang.IllegalStateException: Negative longs unsupported, use writeLong or writeZLong for negativ
e numbers [-1]
        at org.elasticsearch.common.io.stream.StreamOutput.writeVLong(StreamOutput.java:219) ~[elasticsearch-5.
4.0.jar:5.4.0]
        at org.elasticsearch.index.search.stats.SearchStats$Stats.writeTo(SearchStats.java:204) ~[elasticsearch
-5.4.0.jar:5.4.0]
        at org.elasticsearch.index.search.stats.SearchStats.writeTo(SearchStats.java:353) ~[elasticsearch-5.4.0
.jar:5.4.0]
        at org.elasticsearch.common.io.stream.StreamOutput.writeOptionalStreamable(StreamOutput.java:723) ~[ela
sticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.action.admin.indices.stats.CommonStats.writeTo(CommonStats.java:255) ~[elasticsear
ch-5.4.0.jar:5.4.0]
        at org.elasticsearch.action.admin.indices.stats.ShardStats.writeTo(ShardStats.java:102) ~[elasticsearch
-5.4.0.jar:5.4.0]
        at org.elasticsearch.common.io.stream.StreamOutput.writeOptionalStreamable(StreamOutput.java:723) ~[ela
sticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$NodeResponse.writeTo(
TransportBroadcastByNodeAction.java:574) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.transport.TcpTransport.buildMessage(TcpTransport.java:1210) ~[elasticsearch-5.4.0.
jar:5.4.0]
        at org.elasticsearch.transport.TcpTransport.sendResponse(TcpTransport.java:1154) ~[elasticsearch-5.4.0.
jar:5.4.0]
        at org.elasticsearch.transport.TcpTransport.sendResponse(TcpTransport.java:1132) ~[elasticsearch-5.4.0.
jar:5.4.0]
        at org.elasticsearch.transport.TcpTransportChannel.sendResponse(TcpTransportChannel.java:67) ~[elastics
earch-5.4.0.jar:5.4.0]
        at org.elasticsearch.transport.TcpTransportChannel.sendResponse(TcpTransportChannel.java:61) ~[elastics
earch-5.4.0.jar:5.4.0]
        at org.elasticsearch.transport.DelegatingTransportChannel.sendResponse(DelegatingTransportChannel.java:
60) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.transport.RequestHandlerRegistry$TransportChannelWrapper.sendResponse(RequestHandl
erRegistry.java:111) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransp
ortRequestHandler.messageReceived(TransportBroadcastByNodeAction.java:425) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$BroadcastByNodeTransp
ortRequestHandler.messageReceived(TransportBroadcastByNodeAction.java:399) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
 ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.jav
a:69) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1519) ~[elasticsearc
h-5.4.0.jar:5.4.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(Threa
dContext.java:638) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsea
rch-5.4.0.jar:5.4.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
========================== ========================
# I get the ES source find the queryCurrent in the org.elasticsearch.index.search.stats.SearchStats.Stats class  is -1
so the ES cluster get negative value from node ,and use the method  writeVLong 
the method is below:
========== ================ ===============
 /**
     * Writes a non-negative long in a variable-length format. Writes between one and ten bytes. Smaller values take fewer bytes. Negative
     * numbers use ten bytes and trip assertions (if running in tests) so prefer {@link #writeLong(long)} or {@link #writeZLong(long)} for
     * negative numbers.
     */
    public void writeVLong(long i) throws IOException {
        if (i < 0) {
            throw new IllegalStateException("Negative longs unsupported, use writeLong or writeZLong for negative numbers [" + i + "]");
        }
        writeVLongNoCheck(i);
    }
=============== ================= =================================

# So I want to know what happend when the cluser communication ? and why the queryCurrent is become negative?

**Comment by jasontedor** [comment]
I suspect that we have a double decrement bug and I suspect this duplicates #24872.

**Comment by jasontedor** [comment]
We indeed have a double decrement bug, and this indeed duplicates #24872. I'm closing this in favor of that issue and will open a fix soon.
