### ISSUE TITLE
delayed_unassigned_shards not picked from returning node

### ISSUE THREAD

**Issue by ywilkof** [elastic/elasticsearch#24921]
Hello,

We have a 6 node cluster, on top of EC2 instances. All are data nodes and master-eligible nodes. (It's a full Spot machine cluster where all machines can go up and down) 
Sometimes we replace node instances expecting a new instance to return (with the same EBS, hence has all the necessary data) within a few minutes, and for that we are using the index.unassigned.node_left.delayed_timeout  setting. 
Sometimes this feature works correctly, and when the node returns the delayed unassigned shards are picked up immediately and cluster recovery is immediate with minimum data  transfer from other nodes. However, at times, although the cluster is delaying the assignment of the shards, and the node returns within the timeout limit, it does not assign them back to the node, which results in the delayed_shards becoming unassigned shards - leading to data transfer, and post relocation of shards. I verified that the EBS is mounted correctly before Elasticsearch nodestarts.
Looking at my logs, I can see the node is lost and the shards are  delayed.
It is also clear in the logs that leaving instance is back within 2 mins, which should result in immediate allocation of the delayed shards.  I highlighted in the logs what I believe is relevant.

Is this the expected behavior when the node goes down? Thoughts on this would be appreciated. Thanks in advance! 

My cluster state before:

{
   "cluster_name": "elaclu",
   "status": "yellow",
   "timed_out": false,
   "number_of_nodes": 6,
   "number_of_data_nodes": 6,
   "active_primary_shards": 52,
   "active_shards": 91,
   "relocating_shards": 1,
   "initializing_shards": 2,
   "unassigned_shards": 15,
   "delayed_unassigned_shards": 15,
   "number_of_pending_tasks": 0,
   "number_of_in_flight_fetch": 0,
   "task_max_waiting_in_queue_millis": 0,
   "active_shards_percent_as_number": 84.25925925925925
}

my cluster  state  after a few minutes:
{
   "cluster_name": "elaclu",
   "status": "yellow",
   "timed_out": false,
   "number_of_nodes": 6,
   "number_of_data_nodes": 6,
   "active_primary_shards": 52,
   "active_shards": 92,
   "relocating_shards": 1,
   "initializing_shards": 2,
   "unassigned_shards": 14,
   "delayed_unassigned_shards": 0,
   "number_of_pending_tasks": 0,
   "number_of_in_flight_fetch": 0,
   "task_max_waiting_in_queue_millis": 0,
   "active_shards_percent_as_number": 85.18518518518519
}

 And it stays  like  that for about 20 mins, until all shards are assigned eventually. 

cluster settings:

{
   "persistent": {},
   "transient": {
      "cluster": {
         "routing": {
            "allocation": {
               "enable": "all"
            }
         }
      }
   }
}

**Elasticsearch version**: 2.4.4

**Plugins installed**: [cloud-aws]

**JVM version** 1.8.0_131

**OS version**: 4.4.0-77

**Logs:**

[2017-05-27 07:20:17,196][WARN ][transport.netty          ] [Helmut Zemo] exception caught on transport layer [[id: 0x4b6dac95, /10.1.2.82:37064 => /10.1.7.29:9300]], closing connection
java.io.IOException: No route to host
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[2017-05-27 07:20:35,372][WARN ][transport.netty          ] [Helmut Zemo] exception caught on transport layer [[id: 0x48cccb19, /10.1.2.82:37060 => /10.1.7.29:9300]], closing connection
java.io.IOException: No route to host
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[2017-05-27 07:20:54,060][WARN ][transport.netty          ] [Helmut Zemo] exception caught on transport layer [[id: 0x41813568, /10.1.2.82:37062 => /10.1.7.29:9300]], closing connection
java.io.IOException: No route to host
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[2017-05-27 07:37:47,283][INFO ][cluster.routing.allocation] [Helmut Zemo] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[profiles-second-party][10]] ...]).
[2017-05-27 07:45:15,102][DEBUG][action.admin.cluster.node.stats] [Helmut Zemo] failed to execute on node [PbUh6zhnT8-wJVjzkKpzew]
ReceiveTimeoutTransportException[[All-American][10.1.8.96:9300][cluster:monitor/nodes/stats[n]] request_id [1293628] timed out after [15000ms]]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:698)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
**[2017-05-27 07:46:03,692][INFO ][cluster.routing.allocation] [Helmut Zemo] Cluster health status changed from [GREEN] to [YELLOW] (reason: [{All-American}{PbUh6zhnT8-wJVjzkKpzew}{10.1.8.96}{10.1.8.96:9300}{max_local_storage_nodes=1, master=true} failed to ping, tried [3] times, each with maximum [30s] timeout]).
[2017-05-27 07:46:03,692][INFO ][cluster.service          ] [Helmut Zemo] removed {{All-American}{PbUh6zhnT8-wJVjzkKpzew}{10.1.8.96}{10.1.8.96:9300}{max_local_storage_nodes=1, master=true},}, reason: zen-disco-node-failed({All-American}{PbUh6zhnT8-wJVjzkKpzew}{10.1.8.96}{10.1.8.96:9300}{max_local_storage_nodes=1, master=true}), reason(failed to ping, tried [3] times, each with maximum [30s] timeout)**
[2017-05-27 07:46:03,751][WARN ][cluster.action.shard     ] [Helmut Zemo] [profiles-second-party][3] received shard failed for target shard [[profiles-second-party][3], node[PbUh6zhnT8-wJVjzkKpzew], [R], v[138], s[STARTED], a[id=11Dhlxc_SL-TGyrQ3MIa4g]], indexUUID [7wwgfPsiRPy0xNn_jBpFyw], message [failed to perform indices:data/write/bulk[s] on replica on node {All-American}{PbUh6zhnT8-wJVjzkKpzew}{10.1.8.96}{10.1.8.96:9300}{max_local_storage_nodes=1, master=true}], failure [NodeDisconnectedException[[All-American][10.1.8.96:9300][indices:data/write/bulk[s][r]] disconnected]]
NodeDisconnectedException[[All-American][10.1.8.96:9300][indices:data/write/bulk[s][r]] disconnected]
**[2017-05-27 07:46:03,756][INFO ][cluster.routing          ] [Helmut Zemo] delaying allocation for [18] unassigned shards, next check in [5m]**
[2017-05-27 07:46:03,757][WARN ][cluster.action.shard     ] [Helmut Zemo] [profiles-second-party][3] received shard failed for target shard [[profiles-second-party][3], node[PbUh6zhnT8-wJVjzkKpzew], [R], v[138], s[STARTED], a[id=11Dhlxc_SL-TGyrQ3MIa4g]], indexUUID [7wwgfPsiRPy0xNn_jBpFyw], message [failed to perform indices:data/write/bulk[s] on replica on node {All-American}{PbUh6zhnT8-wJVjzkKpzew}{10.1.8.96}{10.1.8.96:9300}{max_local_storage_nodes=1, master=true}], failure [NodeDisconnectedException[[All-American][10.1.8.96:9300][indices:data/write/bulk[s][r]] disconnected]]
NodeDisconnectedException[[All-American][10.1.8.96:9300][indices:data/write/bulk[s][r]] disconnected]
[2017-05-27 07:46:03,834][DEBUG][action.admin.cluster.node.info] [Helmut Zemo] failed to execute on node [PbUh6zhnT8-wJVjzkKpzew]
NodeDisconnectedException[[All-American][10.1.8.96:9300][cluster:monitor/nodes/info[n]] disconnected]
[2017-05-27 07:46:03,835][DEBUG][action.admin.indices.stats] [Helmut Zemo] failed to execute [indices:monitor/stats] on node [PbUh6zhnT8-wJVjzkKpzew]
NodeDisconnectedException[[All-American][10.1.8.96:9300][indices:monitor/stats[n]] disconnected]
[2017-05-27 07:46:03,834][DEBUG][action.admin.cluster.node.info] [Helmut Zemo] failed to execute on node [PbUh6zhnT8-wJVjzkKpzew]
NodeDisconnectedException[[All-American][10.1.8.96:9300][cluster:monitor/nodes/info[n]] disconnected]
[2017-05-27 07:46:03,836][DEBUG][action.admin.indices.stats] [Helmut Zemo] failed to execute [indices:monitor/stats] on node [PbUh6zhnT8-wJVjzkKpzew]
NodeDisconnectedException[[All-American][10.1.8.96:9300][indices:monitor/stats[n]] disconnected]
[2017-05-27 07:46:03,842][DEBUG][action.admin.cluster.node.stats] [Helmut Zemo] failed to execute on node [PbUh6zhnT8-wJVjzkKpzew]
NodeDisconnectedException[[All-American][10.1.8.96:9300][cluster:monitor/nodes/stats[n]] disconnected]
**[2017-05-27 07:47:13,380][INFO ][cluster.service          ] [Helmut Zemo] added {{Madame Menace}{AaT8D-D8QK6m4Vbvr542Bw}{10.1.4.99}{10.1.4.99:9300}{max_local_storage_nodes=1, master=true},}, reason: zen-disco-join(join from node[{Madame Menace}{AaT8D-D8QK6m4Vbvr542Bw}{10.1.4.99}{10.1.4.99:9300}{max_local_storage_nodes=1, master=true}])**

**Comment by abeyad** [comment]
With delayed allocation, if there was no other node with shard data to assign the replica to, and that node comes back online before the delay allocation timeout, it is still possible for the node at that point to have 0 matching bytes with the primary shard - this can happen if a Lucene merge took place on the primary which rendered all the segment files (that underpin the shard data) as completely different from the shard data on the node that rejoined.  If there are no matching bytes, then there is no reason to favor that node for allocation over other nodes in the cluster.  That could be one possible explanation for what you are seeing.  Note that we are working on changing this with [sequence numbers](https://github.com/elastic/elasticsearch/issues/10708), which will allow faster recovery in situations where the documents are mostly the same but the underlying files that contain them in Lucene have diverged completely.

Lastly, if you could kindly ask such questions on the [discussion forum](https://discuss.elastic.co/) we provide in the future.  We reserve Github for known bug reports and feature requests.

**Comment by bleskes** [comment]
>  Note that we are working on changing this with sequence numbers, which will allow faster recover

If you want all the details, you can watch [this talk from Elastic{ON} 17](https://www.elastic.co/elasticon/conf/2017/sf/consensus-and-reception-in-elasticsearch).

**Comment by ywilkof** [comment]
Thank you @abeyad  and @bleskes for your answers. I apologize for opening this ticket in the wrong forum.
