### ISSUE TITLE
[CI] ClusterDisruptionIT.testAckedIndexing fails

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#24932]
The test `ClusterDisruptionIT.testAckedIndexing` fails today on CI: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+java9-periodic/2689/consoleFull

Note that the test used java 9. I didn't manage to reproduce it locally, it seems that the test is correctly executed but fails in the after test cleaning method:

```
ERROR   20.1s J1 | ClusterDisruptionIT.testAckedIndexing <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected index shard counter on shard [test][2] on node node_t1 to be 0 but was 1. Current replication tasks on node:
   > {
   >   "tasks" : { }
   > }
   > 	at org.elasticsearch.test.InternalTestCluster.lambda$assertShardIndexCounter$5(InternalTestCluster.java:1158)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:726)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:700)
   > 	at org.elasticsearch.test.InternalTestCluster.assertShardIndexCounter(InternalTestCluster.java:1139)
   > 	at org.elasticsearch.test.InternalTestCluster.beforeIndexDeletion(InternalTestCluster.java:1109)
   > 	at org.elasticsearch.test.ESIntegTestCase.beforeIndexDeletion(ESIntegTestCase.java:611)
   > 	at org.elasticsearch.discovery.AbstractDisruptionTestCase.beforeIndexDeletion(AbstractDisruptionTestCase.java:111)
   > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:581)
   > 	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2058)
```

Reproduce with:
```
gradle :core:integTest -Dtests.seed=3372D7F1BE882873 -Dtests.class=org.elasticsearch.discovery.ClusterDisruptionIT -Dtests.method="testAckedIndexing" -Dtests.security.manager=true -Dtests.jvm.argline="--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.nio.file=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED --add-opens=java.base/java.util.regex=ALL-UNNAMED" -Dtests.locale=ar-KW -Dtests.timezone=Indian/Maldives
```

[consoleText.txt](https://github.com/elastic/elasticsearch/files/1035443/consoleText.txt)

**Comment by tlrx** [comment]
It might have a duplicate: #25286

**Comment by spinscale** [comment]
another one https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/810/

[full console text output](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/810/consoleText)

**Comment by jasontedor** [comment]
There have been many changes in the replication layer in the past few months that could impact this test. I have not seen any recent failures along these lines, so I think this issue should be closed in favor of a new issue if these failures occur again.
