### ISSUE TITLE
[CI] TranslogTests.testConcurrentWriteViewsAndSnapshot fails

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#24933]
The test `TranslogTests.testConcurrentWriteViewsAndSnapshot` fails on CI:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/2978/consoleFull

With the errror:
```
ERROR   0.19s J2 | TranslogTests.testConcurrentWriteViewsAndSnapshot <<< FAILURES!
   > Throwable #1: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=66, name=writer_1, state=RUNNABLE, group=TGRP-TranslogTests]
   > 	at __randomizedtesting.SeedInfo.seed([250508E42C3AD98D:1DCF1C9F7AD2A0E]:0)
   > Caused by: java.lang.AssertionError: tried to commit generation [10] before minimum generation [12]
   > 	at __randomizedtesting.SeedInfo.seed([250508E42C3AD98D]:0)
   > 	at org.elasticsearch.index.translog.Translog.assertCommittedGenerationIsInValidRange(Translog.java:1480)
   > 	at org.elasticsearch.index.translog.Translog.commit(Translog.java:1462)
   > 	at org.elasticsearch.index.translog.TranslogTests$1.doRun(TranslogTests.java:724)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	at java.lang.Thread.run(Thread.java:748)
```

It does not reproduce locally with:
```
gradle :core:test -Dtests.seed=250508E42C3AD98D -Dtests.class=org.elasticsearch.index.translog.TranslogTests -Dtests.method="testConcurrentWriteViewsAndSnapshot" -Dtests.security.manager=true -Dtests.locale=en-AU -Dtests.timezone=Africa/Gaborone
```

**Comment by tlrx** [comment]
@bleskes It looks like you modified this test recently, that's why I assigned it to you. Feel free to reassign if needed.
