### ISSUE TITLE
data node is down suddenly when we merge  segment force 

### ISSUE THREAD

**Issue by showmeall** [elastic/elasticsearch#24994]
**Describe the feature**:

**Elasticsearch version**: 2.4.0

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0

**OS version** (`uname -a` if on a Unix-like system): centos 7.2

**Description of the problem including expected versus actual behavior**:

we want merge segment due to the segments count is about 1000 now,  when we merge  segment force 
,  one of data node is down suddenly.  and we can not restart it now.
command :   curl -XPOST 'http://localhost:9200/index/_forcemerge?max_num_segments=90'

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
[2017-06-01 11:09:36,214][WARN ][cluster.action.shard     ] [es-node-1] [indexname][0] received shard failed for target shard [[indexname][0], node[MJx1IjEKQWycQ87u4a6s1w], [P], v[76], s[INITIALIZING], a[id=ij9FJhDHQACpuXbf2pT4IA], unassigned_info[[reason=CLUSTER_RECOVERED], at[2017-06-01T03:09:35.786Z]]], indexUUID [0AHoKY3AT2StEMNJ13_yCQ], message [failed recovery], failure [IndexShardRecoveryException[failed to fetch index version after copying it over]; nested: CorruptIndexException[Format version is not supported (resource BufferedChecksumIndexInput(NIOFSIndexInput(path="/dbfile/es-data/es/nodes/0/indices/indexname/0/index/segments_9r3"))): -787420858 (needs to be between 1071082519 and 1071082519). This version of Lucene only supports indexes created with release 4.0 and later. (resource=preexisting_corruption)]; nested: IndexFormatTooOldException[Format version is not supported (resource BufferedChecksumIndexInput(NIOFSIndexInput(path="/dbfile/es-data/es/nodes/0/indices/indexname/0/index/segments_9r3"))): -787420858 (needs to be between 1071082519 and 1071082519). This version of Lucene only supports indexes created with release 4.0 and later.]; ]
[indexname][[indexname][0]] IndexShardRecoveryException[failed to fetch index version after copying it over]; nested: CorruptIndexException[Format version is not supported (resource BufferedChecksumIndexInput(NIOFSIndexInput(path="/dbfile/es-data/es/nodes/0/indices/indexname/0/index/segments_9r3"))): -787420858 (needs to be between 1071082519 and 1071082519). This version of Lucene only supports indexes created with release 4.0 and later. (resource=preexisting_corruption)]; nested: IndexFormatTooOldException[Format version is not supported (resource BufferedChecksumIndexInput(NIOFSIndexInput(path="/dbfile/es-data/es/nodes/0/indices/indexname/0/index/segments_9r3"))): -787420858 (needs to be between 1071082519 and 1071082519). This version of Lucene only supports indexes created with release 4.0 and later.];
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:224)
        at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
        at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.lucene.index.CorruptIndexException: Format version is not supported (resource BufferedChecksumIndexInput(NIOFSIndexInput(path="/dbfile/es-data/es/nodes/0/indices/indexname/0/index/segments_9r3"))): -787420858 (needs to be between 1071082519 and 1071082519). This version of Lucene only supports indexes created with release 4.0 and later. (resource=preexisting_corruption)
        at org.elasticsearch.index.store.Store.failIfCorrupted(Store.java:583)
        at org.elasticsearch.index.store.Store.failIfCorrupted(Store.java:563)
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:197)
        ... 5 more
Caused by: org.apache.lucene.index.IndexFormatTooOldException: Format version is not supported (resource BufferedChecksumIndexInput(NIOFSIndexInput(path="/dbfile/es-data/es/nodes/0/indices/indexname/0/index/segments_9r3"))): -787420858 (needs to be between 1071082519 and 1071082519). This version of Lucene only supports indexes created with release 4.0 and later.
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:299)
        at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:493)
        at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:490)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:731)
        at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:683)
        at org.apache.lucene.index.SegmentInfos.readLatestCommit(SegmentInfos.java:490)
        at org.elasticsearch.common.lucene.Lucene.readSegmentInfos(Lucene.java:95)
        at org.elasticsearch.index.store.Store.readSegmentsInfo(Store.java:163)
        at org.elasticsearch.index.store.Store.access$200(Store.java:87)
        at org.elasticsearch.index.store.Store$MetadataSnapshot.loadMetadata(Store.java:815)
        at org.elasticsearch.index.store.Store$MetadataSnapshot.<init>(Store.java:764)
        at org.elasticsearch.index.store.Store.getMetadata(Store.java:233)
        at org.elasticsearch.index.store.Store.getMetadataOrEmpty(Store.java:192)
        at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:160)
        at org.elasticsearch.indices.recovery.RecoveryTarget.access$1100(RecoveryTarget.java:69)
        at org.elasticsearch.indices.recovery.RecoveryTarget$RecoveryRunner.doRun(RecoveryTarget.java:508)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        ... 3 more

**Comment by jpountz** [comment]
There are two reasons why you might be getting this exception, either you have an index created by Elasticsearch 0.90 or less in your data directory, or your segments file got corrupted. Have you upgraded recently?

**Comment by showmeall** [comment]
we have not upgraded ES version recently ,but we update it to 2.4  9 mouth ago , we use 1.7 before

**Comment by jpountz** [comment]
Then I would lean towards a recent corruption. What error do you get when you try to restart? The corruption of a shard should not hold a node from starting, so I'm wondering whether there is an other issue (that might be related to this one?).

**Comment by colings86** [comment]
No further feedback. If you still have this issue please comment answering the above questions and we can re-open
