### ISSUE TITLE
one of Shard lost suddenly 

### ISSUE THREAD

**Issue by showmeall** [elastic/elasticsearch#25041]
**Describe the feature**:
one of Shard lost suddenly , and we try restart the cluster , can not find it ,please check the debug log as bellow,  we lost the data now, someone please help us , how can we Repair it. thanks

**Elasticsearch version**: 2.4.0

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0

**OS version** (`uname -a` if on a Unix-like system): centos 6.2

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

[2017-06-02 18:42:18,272][DEBUG][action.bulk              ] [es-node-2] failed to execute [BulkShardRequest to [esindex] containing [3] requests] on [[esindex][1]]
[esindex][[esindex][1]] EngineClosedException[CurrentState[CLOSED] Closed]
        at org.elasticsearch.index.engine.Engine.ensureOpen(Engine.java:329)
        at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:448)
        at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:601)
        at org.elasticsearch.index.engine.Engine$Index.execute(Engine.java:836)
        at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:236)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:327)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:120)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:68)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:648)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:271)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2017-06-02 18:42:18,272][WARN ][transport                ] [es-node-2] Transport response handler not found of id [11842463]
[2017-06-02 18:42:18,272][WARN ][transport                ] [es-node-2] Transport response handler not found of id [11842464]
[2017-06-02 18:42:18,272][WARN ][transport                ] [es-node-2] Transport response handler not found of id [11842467]
[2017-06-02 18:42:18,272][WARN ][transport                ] [es-node-2] Transport response handler not found of id [11842465]
[2017-06-02 18:42:18,366][WARN ][index.engine             ] [es-node-2] [esindex][1] failed engine [recovery]
org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=1iawyzb actual=1c7gs86 (resource=name [_8y1c.cfs], length [5243493218], checksum [1iawyzb], writtenBy [5.5.2]) (resource=VerifyingIndexOutput(_8y1c.cfs))
        at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1318)
        at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1295)
        at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1328)
        at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:455)
        at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:419)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:293)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2017-06-02 18:42:18,477][WARN ][indices.cluster          ] [es-node-2] [[esindex][1]] marking and sending shard failed due to [engine failure, reason [recovery]]
org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=1iawyzb actual=1c7gs86 (resource=name [_8y1c.cfs], length [5243493218], checksum [1iawyzb], writtenBy [5.5.2]) (resource=VerifyingIndexOutput(_8y1c.cfs))
        at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1318)
        at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1295)
        at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1328)
        at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:455)
        at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:419)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:293)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by bleskes** [comment]
Sadly, that shard copy got corrupted. I presume it was your only copy and you have no snapshots as backup. You may try to use the [`index.shard.check_index_on_startup`](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/index-modules.html#_static_index_settings) but note that it's dangerous so read up carefully. If you have any more questions please ask on our discuss.elastic.co forum. We keep github for issues and feature requests.
