### ISSUE TITLE
[CI] SimulatePipelineRequestTests.testSerializationWithXContentBwc fails on master reproducibly

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#25055]
```
FAILURE 0.09s | SimulatePipelineRequestTests.testSerializationWithXContentBwc <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: array lengths differed, expected.length=8 actual.length=12
   > 	at __randomizedtesting.SeedInfo.seed([931DD38E84CFACD2:D472B31596283867]:0)
   > 	at org.elasticsearch.action.ingest.SimulatePipelineRequestTests.testSerializationWithXContentBwc(SimulatePipelineRequestTests.java:88)
   > 	at java.lang.Thread.run(Thread.java:748)
  2> NOTE: leaving temporary files on disk at: /home/hinmanm/es/elasticsearch/core/build/testrun/test/J0/temp/org.elasticsearch.action.ingest.SimulatePipelineRequestTests_931DD38E84CFACD2-001
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=154, maxMBSortInHeap=5.53405481744115, sim=RandomSimilarity(queryNorm=true): {}, locale=de, timezone=Pacific/Port_Moresby
  2> NOTE: Linux 4.11.3-200.fc25.x86_64 i386/Oracle Corporation 1.8.0_131 (32-bit)/cpus=8,threads=1,free=458437240,total=514588672
  2> NOTE: All tests run in this JVM: [SimulatePipelineRequestTests]
```

This looks like a BWC issue. It reproduces for me every time with:

```
gradle :core:test -Dtests.seed=931DD38E84CFACD2 -Dtests.class=org.elasticsearch.action.ingest.SimulatePipelineRequestTests -Dtests.method="testSerializationWithXContentBwc" -Dtests.security.manager=true -Dtests.locale=de -Dtests.timezone=Pacific/Port_Moresby
```

**Comment by dakrone** [comment]
Assigning this to you @jaymode since your name comes up with git blame on the test

**Comment by dakrone** [comment]
Hmm.. I dug into this more, it turns out that these reliably fail if the JDK can't load JNA. I've reverted my machine from u131 to u121 and this is now fixed. (131 couldn't load JDK for some reason!?)
