### ISSUE TITLE
Posting highlighter rest tests keeps failing

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#25169]
see https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-unix-compatibility/os=debian/855

```
FAILURE 0.20s | IntegTestZipClientYamlTestSuiteIT.test {p0=search.highlight/20_postings/Postings highlighter should have deprecation warning} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [search.highlight/20_postings:46]: did not get expected warning header [
   > 	[postings] highlighter is deprecated, please use [unified] instead
   > ]
   > 	at __randomizedtesting.SeedInfo.seed([EE6511BD80FB0E91:66312E672E076369]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:345)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:325)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.lang.AssertionError: did not get expected warning header [
   > 	[postings] highlighter is deprecated, please use [unified] instead
   > ]
```

Reproduction line (doesn't reproduce reliably): 

```
gradle :distribution:integ-test-zip:integTestRunner -Dtests.seed=EE6511BD80FB0E91 -Dtests.class=org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT -Dtests.method="test {p0=search.highlight/20_postings/Postings highlighter should have deprecation warning}" -Dtests.security.manager=true -Dtests.locale=es-CR -Dtests.timezone=SystemV/MST7MDT
```

**Comment by jpountz** [comment]
This one starts to be a bit old and is not a big deal so I'm closing. Please reopen if you disagree.
