### ISSUE TITLE
New 5.4.1 cluster on EC2 fails with "handshake failed. unexpected remote node"

### ISSUE THREAD

**Issue by andreausu** [elastic/elasticsearch#25259]
**Elasticsearch version**: 5.4.1

**Plugins installed**: [discovery-ec2]

**JVM version** (`java -version`): JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_131/25.131-b11]

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 16.04

**Description of the problem including expected versus actual behavior**:

This seems related to https://github.com/elastic/elasticsearch/issues/24575 even if it should've been fixed in 5.4.1.
Basically I'm trying to set up a new cluster on AWS EC2 but as soon as I setup the second node the first one becomes unavailable (`master_not_discovered_exception`, full error in the error log below).

**Steps to reproduce**:

Setup 2 new EC2 instances in 2 steps using the official ansible playbook with the following config:

```
---

- hosts: tag_Role_elasticsearch_logs_production
  user: ubuntu
  sudo: true

  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
    - name: Install aptitude for Ansible
      raw: test -e /usr/bin/aptitude || (apt -y update && apt install -y aptitude)
      changed_when: False
    - setup:

  roles:
    - { role: ansible-elasticsearch, es_instance_name: "{{ ansible_hostname }}", es_data_dirs: "/opt/elasticsearch/data", es_log_dir: "/opt/elasticsearch/logs",
        es_config: {
          cluster.name: "prima-logs-production",
          bootstrap.memory_lock: true,
          discovery.zen.hosts_provider: "ec2",
          cloud.aws.region: "eu-west-1",
          discovery.ec2.groups: "sg-a6d731de",
          discovery.ec2.host_type: "private_dns",
          network.bind_host: 0.0.0.0
        }
      }

  vars:
    es_version_lock: false
    es_heap_size: 4g
    es_major_version: 5.x
    es_version: 5.4.1
    es_start_service: true
    es_plugins_reinstall: true
    es_plugins:
      - plugin: discovery-ec2
```

First node that stopped working when the second node was started (the service restarts are made by ansible):

```
[2017-06-15T15:22:41,110][INFO ][o.e.n.Node               ] [10.33.3.54-ip-10-33-3-54] initializing ...
[2017-06-15T15:22:41,200][INFO ][o.e.e.NodeEnvironment    ] [10.33.3.54-ip-10-33-3-54] using [1] data paths, mounts [[/ (/dev/xvda1)]], net usable_space [482.5gb], net total_space [484.6gb], spins? [no], types [ext4]
[2017-06-15T15:22:41,201][INFO ][o.e.e.NodeEnvironment    ] [10.33.3.54-ip-10-33-3-54] heap size [3.9gb], compressed ordinary object pointers [true]
[2017-06-15T15:22:41,202][INFO ][o.e.n.Node               ] [10.33.3.54-ip-10-33-3-54] node name [10.33.3.54-ip-10-33-3-54], node ID [hH1GaZyETSqQpvryQ8VMcQ]
[2017-06-15T15:22:41,203][INFO ][o.e.n.Node               ] [10.33.3.54-ip-10-33-3-54] version[5.4.1], pid[12899], build[2cfe0df/2017-05-29T16:05:51.443Z], OS[Linux/4.4.0-1013-aws/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_131/25.131-b11]
[2017-06-15T15:22:41,203][INFO ][o.e.n.Node               ] [10.33.3.54-ip-10-33-3-54] JVM arguments [-Xms4g, -Xmx4g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/usr/share/elasticsearch]
[2017-06-15T15:22:42,633][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [aggs-matrix-stats]
[2017-06-15T15:22:42,633][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [ingest-common]
[2017-06-15T15:22:42,633][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [lang-expression]
[2017-06-15T15:22:42,634][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [lang-groovy]
[2017-06-15T15:22:42,634][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [lang-mustache]
[2017-06-15T15:22:42,634][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [lang-painless]
[2017-06-15T15:22:42,634][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [percolator]
[2017-06-15T15:22:42,634][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [reindex]
[2017-06-15T15:22:42,634][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [transport-netty3]
[2017-06-15T15:22:42,634][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [transport-netty4]
[2017-06-15T15:22:42,635][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded plugin [discovery-ec2]
[2017-06-15T15:22:45,405][INFO ][o.e.d.DiscoveryModule    ] [10.33.3.54-ip-10-33-3-54] using discovery type [zen]
[2017-06-15T15:22:46,030][INFO ][o.e.n.Node               ] [10.33.3.54-ip-10-33-3-54] initialized
[2017-06-15T15:22:46,031][INFO ][o.e.n.Node               ] [10.33.3.54-ip-10-33-3-54] starting ...
[2017-06-15T15:22:46,218][INFO ][o.e.t.TransportService   ] [10.33.3.54-ip-10-33-3-54] publish_address {127.0.0.1:9300}, bound_addresses {[::]:9300}
[2017-06-15T15:22:46,227][INFO ][o.e.b.BootstrapChecks    ] [10.33.3.54-ip-10-33-3-54] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2017-06-15T15:22:50,091][INFO ][o.e.c.s.ClusterService   ] [10.33.3.54-ip-10-33-3-54] new_master {10.33.3.54-ip-10-33-3-54}{hH1GaZyETSqQpvryQ8VMcQ}{L7mjja2FQe6lBV31H8WnMQ}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-06-15T15:22:50,125][INFO ][o.e.h.n.Netty4HttpServerTransport] [10.33.3.54-ip-10-33-3-54] publish_address {127.0.0.1:9200}, bound_addresses {[::]:9200}
[2017-06-15T15:22:50,127][INFO ][o.e.n.Node               ] [10.33.3.54-ip-10-33-3-54] started
[2017-06-15T15:22:50,186][INFO ][o.e.g.GatewayService     ] [10.33.3.54-ip-10-33-3-54] recovered [0] indices into cluster_state
[2017-06-15T16:00:28,098][INFO ][o.e.n.Node               ] [10.33.3.54-ip-10-33-3-54] stopping ...
[2017-06-15T16:00:28,110][INFO ][o.e.n.Node               ] [10.33.3.54-ip-10-33-3-54] stopped
[2017-06-15T16:00:28,110][INFO ][o.e.n.Node               ] [10.33.3.54-ip-10-33-3-54] closing ...
[2017-06-15T16:00:28,122][INFO ][o.e.n.Node               ] [10.33.3.54-ip-10-33-3-54] closed
[2017-06-15T16:00:30,485][INFO ][o.e.n.Node               ] [10.33.3.54-ip-10-33-3-54] initializing ...
[2017-06-15T16:00:30,559][INFO ][o.e.e.NodeEnvironment    ] [10.33.3.54-ip-10-33-3-54] using [1] data paths, mounts [[/ (/dev/xvda1)]], net usable_space [482.5gb], net total_space [484.6gb], spins? [no], types [ext4]
[2017-06-15T16:00:30,559][INFO ][o.e.e.NodeEnvironment    ] [10.33.3.54-ip-10-33-3-54] heap size [3.9gb], compressed ordinary object pointers [true]
[2017-06-15T16:00:30,561][INFO ][o.e.n.Node               ] [10.33.3.54-ip-10-33-3-54] node name [10.33.3.54-ip-10-33-3-54], node ID [hH1GaZyETSqQpvryQ8VMcQ]
[2017-06-15T16:00:30,561][INFO ][o.e.n.Node               ] [10.33.3.54-ip-10-33-3-54] version[5.4.1], pid[22726], build[2cfe0df/2017-05-29T16:05:51.443Z], OS[Linux/4.4.0-1013-aws/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_131/25.131-b11]
[2017-06-15T16:00:30,561][INFO ][o.e.n.Node               ] [10.33.3.54-ip-10-33-3-54] JVM arguments [-Xms4g, -Xmx4g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/usr/share/elasticsearch]
[2017-06-15T16:00:32,107][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [aggs-matrix-stats]
[2017-06-15T16:00:32,108][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [ingest-common]
[2017-06-15T16:00:32,108][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [lang-expression]
[2017-06-15T16:00:32,108][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [lang-groovy]
[2017-06-15T16:00:32,108][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [lang-mustache]
[2017-06-15T16:00:32,108][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [lang-painless]
[2017-06-15T16:00:32,108][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [percolator]
[2017-06-15T16:00:32,108][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [reindex]
[2017-06-15T16:00:32,108][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [transport-netty3]
[2017-06-15T16:00:32,108][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded module [transport-netty4]
[2017-06-15T16:00:32,110][INFO ][o.e.p.PluginsService     ] [10.33.3.54-ip-10-33-3-54] loaded plugin [discovery-ec2]
[2017-06-15T16:00:34,980][INFO ][o.e.d.DiscoveryModule    ] [10.33.3.54-ip-10-33-3-54] using discovery type [zen]
[2017-06-15T16:00:35,547][INFO ][o.e.n.Node               ] [10.33.3.54-ip-10-33-3-54] initialized
[2017-06-15T16:00:35,547][INFO ][o.e.n.Node               ] [10.33.3.54-ip-10-33-3-54] starting ...
[2017-06-15T16:00:35,724][INFO ][o.e.t.TransportService   ] [10.33.3.54-ip-10-33-3-54] publish_address {127.0.0.1:9300}, bound_addresses {[::]:9300}
[2017-06-15T16:00:35,736][INFO ][o.e.b.BootstrapChecks    ] [10.33.3.54-ip-10-33-3-54] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2017-06-15T16:00:39,862][WARN ][o.e.d.z.ZenDiscovery     ] [10.33.3.54-ip-10-33-3-54] failed to connect to master [{10.33.3.45-ip-10-33-3-45}{gw7g-PF8Tm2oxChEQIHWNg}{BDhWOA-iR1-ORSYNijJPGA}{127.0.0.1}{127.0.0.1:9300}], retrying...
org.elasticsearch.transport.ConnectTransportException: [10.33.3.45-ip-10-33-3-45][127.0.0.1:9300] handshake failed. unexpected remote node {10.33.3.54-ip-10-33-3-54}{hH1GaZyETSqQpvryQ8VMcQ}{d08Cz7N5RsGrcbSQQGR6vQ}{127.0.0.1}{127.0.0.1:9300}
        at org.elasticsearch.transport.TransportService.lambda$connectToNode$3(TransportService.java:319) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.transport.TcpTransport.connectToNode(TcpTransport.java:474) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:315) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:302) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.discovery.zen.ZenDiscovery.joinElectedMaster(ZenDiscovery.java:468) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:420) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.discovery.zen.ZenDiscovery.joinElectedMaster(ZenDiscovery.java:468) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:420) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.discovery.zen.ZenDiscovery.access$4100(ZenDiscovery.java:83) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.discovery.zen.ZenDiscovery$JoinThreadControl$1.run(ZenDiscovery.java:1197) [elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.4.1.jar:5.4.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

```

Second node that it's working:

```
[2017-06-15T16:00:30,600][INFO ][o.e.n.Node               ] [10.33.3.45-ip-10-33-3-45] initializing ...
[2017-06-15T16:00:30,690][INFO ][o.e.e.NodeEnvironment    ] [10.33.3.45-ip-10-33-3-45] using [1] data paths, mounts [[/ (/dev/xvda1)]], net usable_space [482.6gb], net total_space [484.6gb], spins? [no], types [ext4]
[2017-06-15T16:00:30,691][INFO ][o.e.e.NodeEnvironment    ] [10.33.3.45-ip-10-33-3-45] heap size [3.9gb], compressed ordinary object pointers [true]
[2017-06-15T16:00:30,698][INFO ][o.e.n.Node               ] [10.33.3.45-ip-10-33-3-45] node name [10.33.3.45-ip-10-33-3-45], node ID [gw7g-PF8Tm2oxChEQIHWNg]
[2017-06-15T16:00:30,698][INFO ][o.e.n.Node               ] [10.33.3.45-ip-10-33-3-45] version[5.4.1], pid[5779], build[2cfe0df/2017-05-29T16:05:51.443Z], OS[Linux/4.4.0-1013-aws/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_131/25.131-b11]
[2017-06-15T16:00:30,698][INFO ][o.e.n.Node               ] [10.33.3.45-ip-10-33-3-45] JVM arguments [-Xms4g, -Xmx4g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/usr/share/elasticsearch]
[2017-06-15T16:00:32,301][INFO ][o.e.p.PluginsService     ] [10.33.3.45-ip-10-33-3-45] loaded module [aggs-matrix-stats]
[2017-06-15T16:00:32,301][INFO ][o.e.p.PluginsService     ] [10.33.3.45-ip-10-33-3-45] loaded module [ingest-common]
[2017-06-15T16:00:32,301][INFO ][o.e.p.PluginsService     ] [10.33.3.45-ip-10-33-3-45] loaded module [lang-expression]
[2017-06-15T16:00:32,301][INFO ][o.e.p.PluginsService     ] [10.33.3.45-ip-10-33-3-45] loaded module [lang-groovy]
[2017-06-15T16:00:32,301][INFO ][o.e.p.PluginsService     ] [10.33.3.45-ip-10-33-3-45] loaded module [lang-mustache]
[2017-06-15T16:00:32,301][INFO ][o.e.p.PluginsService     ] [10.33.3.45-ip-10-33-3-45] loaded module [lang-painless]
[2017-06-15T16:00:32,302][INFO ][o.e.p.PluginsService     ] [10.33.3.45-ip-10-33-3-45] loaded module [percolator]
[2017-06-15T16:00:32,302][INFO ][o.e.p.PluginsService     ] [10.33.3.45-ip-10-33-3-45] loaded module [reindex]
[2017-06-15T16:00:32,302][INFO ][o.e.p.PluginsService     ] [10.33.3.45-ip-10-33-3-45] loaded module [transport-netty3]
[2017-06-15T16:00:32,302][INFO ][o.e.p.PluginsService     ] [10.33.3.45-ip-10-33-3-45] loaded module [transport-netty4]
[2017-06-15T16:00:32,303][INFO ][o.e.p.PluginsService     ] [10.33.3.45-ip-10-33-3-45] loaded plugin [discovery-ec2]
[2017-06-15T16:00:35,315][INFO ][o.e.d.DiscoveryModule    ] [10.33.3.45-ip-10-33-3-45] using discovery type [zen]
[2017-06-15T16:00:35,939][INFO ][o.e.n.Node               ] [10.33.3.45-ip-10-33-3-45] initialized
[2017-06-15T16:00:35,940][INFO ][o.e.n.Node               ] [10.33.3.45-ip-10-33-3-45] starting ...
[2017-06-15T16:00:36,113][INFO ][o.e.t.TransportService   ] [10.33.3.45-ip-10-33-3-45] publish_address {127.0.0.1:9300}, bound_addresses {[::]:9300}
[2017-06-15T16:00:36,123][INFO ][o.e.b.BootstrapChecks    ] [10.33.3.45-ip-10-33-3-45] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2017-06-15T16:00:39,984][INFO ][o.e.c.s.ClusterService   ] [10.33.3.45-ip-10-33-3-45] new_master {10.33.3.45-ip-10-33-3-45}{gw7g-PF8Tm2oxChEQIHWNg}{BDhWOA-iR1-ORSYNijJPGA}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-06-15T16:00:40,016][INFO ][o.e.h.n.Netty4HttpServerTransport] [10.33.3.45-ip-10-33-3-45] publish_address {127.0.0.1:9200}, bound_addresses {[::]:9200}
[2017-06-15T16:00:40,019][INFO ][o.e.g.GatewayService     ] [10.33.3.45-ip-10-33-3-45] recovered [0] indices into cluster_state
[2017-06-15T16:00:40,020][INFO ][o.e.n.Node               ] [10.33.3.45-ip-10-33-3-45] started
```

The port 9300 is open both ways (successful connection using telnet).

**Provide logs (if relevant)**:

ES Config:

```
bootstrap.memory_lock: true
cloud.aws.region: eu-west-1
cluster.name: prima-logs-production
discovery.ec2.groups: sg-a6d731de
discovery.ec2.host_type: private_dns
discovery.zen.hosts_provider: ec2
network.bind_host: 0.0.0.0
node.name: 10.33.3.37-ip-10-33-3-37

#################################### Paths ####################################

# Path to directory containing configuration (this file and logging.yml):
path.conf: /etc/elasticsearch/ip-10-33-3-37
path.data: /opt/elasticsearch/data/10.33.3.37-ip-10-33-3-37
path.logs: /opt/elasticsearch/logs/10.33.3.37-ip-10-33-3-37
```

ES response of the first node that isn't connecting:

```
{
"name": "10.33.3.54-ip-10-33-3-54",
"cluster_name": "prima-logs-production",
"cluster_uuid": "_na_",
"version": {
"number": "5.4.1",
"build_hash": "2cfe0df",
"build_date": "2017-05-29T16:05:51.443Z",
"build_snapshot": false,
"lucene_version": "6.5.1"
},
"tagline": "You Know, for Search"
}
```

ES response of the second node:

```
{
"name": "10.33.3.45-ip-10-33-3-45",
"cluster_name": "prima-logs-production",
"cluster_uuid": "lTqWpjaITWWL0x52_4sIZA",
"version": {
"number": "5.4.1",
"build_hash": "2cfe0df",
"build_date": "2017-05-29T16:05:51.443Z",
"build_snapshot": false,
"lucene_version": "6.5.1"
},
"tagline": "You Know, for Search"
}
```

**Comment by andreausu** [comment]
Nevermind, I forgot to set some bind parameters in my config (I had previously only set `network.bind_host`), it's now working with:

```
network.host: "0.0.0.0",
network.bind_host: "0.0.0.0",
network.publish_host: "0.0.0.0"
```

I think that the error message could be improved though.

**Comment by previa** [comment]
hi  andreausu,

I am using the settings as follow in elasticsearch.yml.

network.host: 0.0.0.0
network.bind_host: 0.0.0.0
network.publish_host: 0.0.0.0

but still got the same error.

LOG:

[2017-07-06T17:28:21,076][WARN ][o.e.d.z.ZenDiscovery     ] [slave] failed to connect to master [{master}{uXblLn3xQzOOpTn76jTzfw}{01nOIQNdTYi0WfQFv47GlQ}{172.17.0.2}{172.17.0.2:9300}{ml.enabled=true}], retrying...
org.elasticsearch.transport.ConnectTransportException: [master][172.17.0.2:9300] handshake failed. unexpected remote node {slave}{exBbDVGeToSDRzLLmOh8-g}{fWgOl6QYTdWheTIOM8pVNQ}{172.17.0.2}{172.17.0.2:9300}{ml.enabled=true}
        at org.elasticsearch.transport.TransportService.lambda$connectToNode$3(TransportService.java:319) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.transport.TcpTransport.connectToNode(TcpTransport.java:466) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:315) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:302) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.discovery.zen.ZenDiscovery.joinElectedMaster(ZenDiscovery.java:468) [elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:420) [elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.discovery.zen.ZenDiscovery.access$4100(ZenDiscovery.java:83) [elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.discovery.zen.ZenDiscovery$JoinThreadControl$1.run(ZenDiscovery.java:1197) [elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.4.0.jar:5.4.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by rajashreetutgirl** [comment]
Hello Andreausu,

Did you get the solution for the problem? Even Im facing the same issue. Im trying to create cluster in VBox.

**Comment by donaldduckcheshta** [comment]
Hi All , did you get chance to resolve this issue ? If yes , then please suggest

**Comment by DaveCTurner** [comment]
The information you need is in the first two lines of the log message:

```
[2017-07-06T17:28:21,076][WARN ][o.e.d.z.ZenDiscovery ] [slave] failed to connect to master [{master}{uXblLn3xQzOOpTn76jTzfw}{01nOIQNdTYi0WfQFv47GlQ}{172.17.0.2}{172.17.0.2:9300}{ml.enabled=true}], retrying...
org.elasticsearch.transport.ConnectTransportException: [master][172.17.0.2:9300] handshake failed. unexpected remote node {slave}{exBbDVGeToSDRzLLmOh8-g}{fWgOl6QYTdWheTIOM8pVNQ}{172.17.0.2}{172.17.0.2:9300}{ml.enabled=true}
```

Specifically, this node is trying to connect to a node called `master` at `172.17.0.2:9300` but when it connected to that address it found a node with a different id instead. Each node in your cluster needs to have a unique address, and be accessible at this address from every other node in the cluster.

For further help please open a new thread on the discussion forum at https://discuss.elastic.co/c/elasticsearch - this issue is well over a year old and will likely not receive further attention.
