### ISSUE TITLE
'default.path.data' Access Denied Prevents Startup when another data directory is used. 

### ISSUE THREAD

**Issue by Budman17r** [elastic/elasticsearch#25265]
**Elasticsearch version**: 5.4

**Plugins installed**: [ X-pack ]

**JVM version** (`java -version`): Java Version "1.8.0_121

**OS version** (`uname -a` if on a Unix-like system):Linux SERVERNAME 3.10.0-327.36.2.el7.x86_64 #1 SMP Tue Sep 27 16:01:21 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: When changing the Data directory in the elasticsearch.yml to something else, and attempting to delete /var/lib/elasticsearch

**Steps to reproduce**: delete /var/lib/elasticsearch, and attempt to start/restart Elastic.

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

I guess it doesn't make sense to have the folder when its not being used. It also doesn't make sense that it prevents startup when its not there. 

**Provide logs (if relevant)**:

[2017-06-15T13:39:36,507][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [servername] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Unable to access 'default.path.data' (/var/lib/elasticsearch)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.4.0.jar:5.4.0]
Caused by: java.lang.IllegalStateException: Unable to access 'default.path.data' (/var/lib/elasticsearch)
        at org.elasticsearch.bootstrap.Security.addPath(Security.java:413) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:292) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:224) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Security.configure(Security.java:114) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:237) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:360) ~[elasticsearch-5.4.0.jar:5.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.4.0.jar:5.4.0]
        ... 6 more

**Comment by jasontedor** [comment]
Well, I can see why you think that although I have some clarifying explanations here. You see, there was a nasty bug introduced in 5.3.0 which caused data to be sprayed into `default.path.data` even if the user did not intend to (because they had set `path.data`). Starting in 5.3.1, we want to check if a user ended up in this awful situation. To do this, we need to grant read permission (from a security manager perspective) on the directory (you need read permissions after the security manager is installed to even check if the directory exists!). When we add permissions for a directory, we ensure the directory exists so that we do not later run into an access control exception (filesystem permissions issue; fail early, fail often). So you see, we could unconditionally grant the read permission here without checking existence but then there's the problem that `Files#exists` will return false if we do not have filesystem permissions to read the directory and we would rather fail in this case then have the filesystems permissions be messed up preventing us from being able to detect whether or not the user ended up in a bad situation as a result of the `path.data/default.path.data` bug. Since we create the directory on package installation, it's unlikely that most users are going to run into a problem here. Another point is that `default.path.data` is going to be removed in 6.0.0. Given all this together, I lean towards leaving this as is.
