### ISSUE TITLE
CI: IndicesRequestIT fails reproducibly on master

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#25284]
This seems to fail reproducibly on current master (5f18791f1ce461bc12c1841294f6bb66b039a4b1):

```
gradle :core:integTest -Dtests.seed=97B4463A8E331DB7 -Dtests.class=org.elasticsearch.action.IndicesRequestIT
```

Errors look like this:

```
   > Throwable #1: java.lang.AssertionError:
   > Expected: an empty iterable
   >      but: [<indices:admin/delete=[org.elasticsearch.action.admin.indices.delete.DeleteIndexRequest@52873cda]>]
   >    at __randomizedtesting.SeedInfo.seed([97B4463A8E331DB7:9957C6E58E0FEFEF]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.action.IndicesRequestIT.assertAllRequestsHaveBeenConsumed(IndicesRequestIT.java:671)
   >    at org.elasticsearch.action.IndicesRequestIT.cleanUp(IndicesRequestIT.java:175)
   >    at java.lang.Thread.run(Thread.java:745)
```

Since this fails a lot on master currently I will go and mute the test for now.

**Comment by cbuescher** [comment]
An example failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/3228/console
