### ISSUE TITLE
Null pointer exception when using _score in a script query

### ISSUE THREAD

**Issue by msimos** [elastic/elasticsearch#25304]
**Elasticsearch version**:

Elasticsearch 5.4.0

**Plugins installed**: []

X-Pack

**JVM version** (`java -version`):

1.8

**OS version** (`uname -a` if on a Unix-like system):

Fedora Linux

**Description of the problem including expected versus actual behavior**:

This example:

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-using.html#_request_examples

Results in a null pointer exception:

        "reason": {
          "type": "null_pointer_exception",
          "reason": null
        }

In the logs you see:

Caused by: java.lang.NullPointerException
        at org.elasticsearch.painless.ScriptImpl.getScore(ScriptImpl.java:187) ~[?:?]
        at org.elasticsearch.painless.ScriptImpl$$Lambda$2467/72004285.apply(Unknown Source) ~[?:?]
        at org.elasticsearch.painless.ScriptImpl.run(ScriptImpl.java:133) ~[?:?]
        at org.elasticsearch.index.query.ScriptQueryBuilder$ScriptQuery$1$1.get(ScriptQueryBuilder.java:186) ~[elasticsearch-5.4.0.jar:5.4.0]

Is this appropriate to access _score in a script query? And would it be correct to instead use a script_score instead to calculate the score. Not sure if this is a bug or just a documentation issue since the error doesn't tell you anything about what is wrong. 

**Steps to reproduce**:

 1. Copy and paste the example here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-using.html#_request_examples

 2. Run query and it results in a null pointer exception

**Comment by clintongormley** [comment]
Fixed in 5.4.1 https://github.com/elastic/elasticsearch/pull/24295
