### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT.test {p0=indices.analyze/10_analyze/Custom filter in request} randomly fails

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#25316]
CI link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/1457/consoleFull

Reproduce with (could not reproduce locally):
````
gradle :qa:mixed-cluster:v5.6.0-SNAPSHOT#mixedClusterTestRunner -Dtests.seed=29A0EC0C1D01898C -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT -Dtests.method="test {p0=indices.analyze/10_analyze/Custom filter in request}" -Dtests.security.manager=true -Dtests.locale=it -Dtests.timezone=America/Cancun
````

Full error:
````
[2017-06-20T09:10:28,982][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] Stash dump on failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "detail" : {
  1>         "custom_analyzer" : true,
  1>         "charfilters" : [ ],
  1>         "tokenizer" : {
  1>           "name" : "standard",
  1>           "tokens" : [
  1>             {
  1>               "token" : "foo",
  1>               "start_offset" : 0,
  1>               "end_offset" : 3,
  1>               "type" : "<ALPHANUM>",
  1>               "position" : 0,
  1>               "bytes" : "[66 6f 6f]",
  1>               "positionLength" : 1
  1>             },
  1>             {
  1>               "token" : "bar",
  1>               "start_offset" : 4,
  1>               "end_offset" : 7,
  1>               "type" : "<ALPHANUM>",
  1>               "position" : 1,
  1>               "bytes" : "[62 61 72]",
  1>               "positionLength" : 1
  1>             },
  1>             {
  1>               "token" : "buzz",
  1>               "start_offset" : 8,
  1>               "end_offset" : 12,
  1>               "type" : "<ALPHANUM>",
  1>               "position" : 2,
  1>               "bytes" : "[62 75 7a 7a]",
  1>               "positionLength" : 1
  1>             }
  1>           ]
  1>         },
  1>         "tokenfilters" : [
  1>           {
  1>             "name" : "_anonymous_tokenfilter_[0]",
  1>             "tokens" : [
  1>               {
  1>                 "token" : "bar",
  1>                 "start_offset" : 4,
  1>                 "end_offset" : 7,
  1>                 "type" : "<ALPHANUM>",
  1>                 "position" : 1,
  1>                 "bytes" : "[62 61 72]",
  1>                 "positionLength" : 1
  1>               }
  1>             ]
  1>           }
  1>         ]
  1>       }
  1>     }
  1>   }
  1> }]
FAILURE 0.03s | MixedClusterClientYamlTestSuiteIT.test {p0=indices.analyze/10_analyze/Custom filter in request} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [indices.analyze/10_analyze:76]: detail.tokenfilters.0.name didn't match expected value:
   >     detail.tokenfilters.0.name: expected [_anonymous_tokenfilter] but was [_anonymous_tokenfilter_[0]]
   > 	at __randomizedtesting.SeedInfo.seed([29A0EC0C1D01898C:A1F4D3D6B3FDE474]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:348)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:328)
   > 	at java.lang.Thread.run(Thread.java:745)
   > Caused by: java.lang.AssertionError: detail.tokenfilters.0.name didn't match expected value:
   >     detail.tokenfilters.0.name: expected [_anonymous_tokenfilter] but was [_anonymous_tokenfilter_[0]]
   > 	at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:87)
   > 	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:344)
   > 	... 37 more
````

**Comment by dimitris-athanasiou** [comment]
Another instance: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/1458/console

**Comment by dakrone** [comment]
To link the issues, this was a byproduct of #8049
