### ISSUE TITLE
Search with explain sometimes fail

### ISSUE THREAD

**Issue by igorbunova** [elastic/elasticsearch#25330]
**Elasticsearch version**: 5.4.1

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_131

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 16.04

**Description of the problem including expected versus actual behavior**:
search query fails when explain parameter is set to true.

**Steps to reproduce**:
Use transport client in java code.
Fails randomly in tests, looks like it is data dependent.

**Provide logs (if relevant)**:
Exception in thread "elasticsearch[BHybiKz][search][T#6]" java.lang.AssertionError: input 1.3065281278905116E-105 out of float scope for function score deviation: 1.0
	at org.elasticsearch.common.lucene.search.function.CombineFunction.toFloat(CombineFunction.java:133)
	at org.elasticsearch.index.query.functionscore.DecayFunctionBuilder$AbstractDistanceScoreFunction$1.explainScore(DecayFunctionBuilder.java:551)
	at org.elasticsearch.common.lucene.search.function.FiltersFunctionScoreQuery$CustomBoostFactorWeight.explain(FiltersFunctionScoreQuery.java:220)
	at org.apache.lucene.search.IndexSearcher.explain(IndexSearcher.java:723)
	at org.apache.lucene.search.IndexSearcher.explain(IndexSearcher.java:700)
	at org.elasticsearch.search.internal.ContextIndexSearcher.explain(ContextIndexSearcher.java:140)
	at org.elasticsearch.search.fetch.subphase.ExplainFetchSubPhase.hitExecute(ExplainFetchSubPhase.java:41)
	at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:161)
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:298)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:273)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:339)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:336)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:627)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jpountz** [comment]
I think we should just remove this assertion that failed, we can't guaratee it will pass all the time.
