### ISSUE TITLE
Failed to run Elasticsearch

### ISSUE THREAD

**Issue by zak1994** [elastic/elasticsearch#25366]
Elasticsearch version: 2.0.2
JVM version (`java -version`): 7

Please I'm new in Elasticsearch, when i want to run elastic I had this Error.

[2017-06-22 15:12:53,017][WARN ][cluster.action.shard     ] [Living Planet] [dubai-dep][0] received shard failed for [dubai-dep][0], node[iXCi74XGT8-jvaT2nvrkgA], [P], v[7], s[INITIALIZING], a[id=vzdWowPOS96uG-R1kjTlrw], unassigned_info[[reason=ALLOCATION_FAILED], at[2017-06-22T15:12:52.894Z], details[failed recovery, failure IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to create engine]; nested: AccessDeniedException[/elasticsearch/data/elastic_stack/elasticsearch-2.0.2/data/zakaria/nodes/0/indices/dubai-dep/0/index/write.lock]; ]], indexUUID [BBKOSi1zQmiTnxPk7ZvpNA], message [failed recovery], failure [IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to create engine]; nested: AccessDeniedException[/elasticsearch/data/elastic_stack/elasticsearch-2.0.2/data/zakaria/nodes/0/indices/dubai-dep/0/index/write.lock]; ]
[dubai-dep][[dubai-dep][0]] IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to create engine]; nested: AccessDeniedException[/elasticsearch/data/elastic_stack/elasticsearch-2.0.2/data/zakaria/nodes/0/indices/dubai-dep/0/index/write.lock];
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:258)
        at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:60)
        at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:133)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: [dubai-dep][[dubai-dep][0]] EngineCreationFailureException[failed to create engine]; nested: AccessDeniedException[/elasticsearch/data/elastic_stack/elasticsearch-2.0.2/data/zakaria/nodes/0/indices/dubai-dep/0/index/write.lock];
        at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:135)
        at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
        at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1349)
        at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1344)
        at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:889)
        at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:866)
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:249)
        ... 5 more
Caused by: java.nio.file.AccessDeniedException: /elasticsearch/data/elastic_stack/elasticsearch-2.0.2/data/zakaria/nodes/0/indices/dubai-dep/0/index/write.lock
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
        at java.nio.channels.FileChannel.open(FileChannel.java:287)
        at java.nio.channels.FileChannel.open(FileChannel.java:334)
        at org.apache.lucene.store.NativeFSLockFactory$NativeFSLock.obtain(NativeFSLockFactory.java:137)
        at org.apache.lucene.store.Lock.obtain(Lock.java:77)
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:780)
        at org.elasticsearch.index.engine.InternalEngine.createWriter(InternalEngine.java:1065)
        at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:129)
        ... 11 more
[2017-06-22 15:12:53,022][WARN ][gateway                  ] [Living Planet] [twitter]: failed to write index state
java.nio.file.AccessDeniedException: /elasticsearch/data/elastic_stack/elasticsearch-2.0.2/data/zakaria/nodes/0/indices/twitter/_state/state-24.st.tmp
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:430)
        at java.nio.file.Files.newOutputStream(Files.java:172)
        at org.elasticsearch.gateway.MetaDataStateFormat.write(MetaDataStateFormat.java:112)
        at org.elasticsearch.gateway.MetaStateService.writeIndex(MetaStateService.java:135)
        at org.elasticsearch.gateway.GatewayMetaState.clusterChanged(GatewayMetaState.java:158)
        at org.elasticsearch.gateway.Gateway.clusterChanged(Gateway.java:185)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:494)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:225)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:188)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by nik9000** [comment]
We try to keep things like this on the [forum](https://discuss.elastic.co/).

Here is your hint though:
```
[2017-06-22 15:12:53,022][WARN ][gateway ] [Living Planet] [twitter]: failed to write index state
java.nio.file.AccessDeniedException: /elasticsearch/data/elastic_stack/elasticsearch-
```

I expect that the user running Elasticsearch can't write to that directory any more. I'd go ask on the forum if you need more help.
