### ISSUE TITLE
[CI] TemplateUpgradeServiceIT.testTemplateUpdate failure

### ISSUE THREAD

**Issue by tbrooks8** [elastic/elasticsearch#25382]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/357/console

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/1159/console

```
FAILURE 12.0s J2 | TemplateUpgradeServiceIT.testTemplateUpdate <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <3>
   >      but: was <4>
   > 	at __randomizedtesting.SeedInfo.seed([43CE48AB8C847E3F:58F7390846BF13AC]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.cluster.metadata.TemplateUpgradeServiceIT.lambda$testTemplateUpdate$0(TemplateUpgradeServiceIT.java:111)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:722)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:696)
   > 	at org.elasticsearch.cluster.metadata.TemplateUpgradeServiceIT.testTemplateUpdate(TemplateUpgradeServiceIT.java:109)
   > 	at java.lang.Thread.run(Thread.java:745)
   > 	Suppressed: java.lang.AssertionError: 
   > Expected: <3>
   >      but: was <4>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.cluster.metadata.TemplateUpgradeServiceIT.lambda$testTemplateUpdate$0(TemplateUpgradeServiceIT.java:111)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
   > 		... 39 more
   > 	Suppressed: java.lang.AssertionError: 
   > Expected: <3>
   >      but: was <4>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.cluster.metadata.TemplateUpgradeServiceIT.lambda$testTemplateUpdate$0(TemplateUpgradeServiceIT.java:111)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
   > 		... 39 more
   > 	Suppressed: java.lang.AssertionError: 
   > Expected: <3>
   >      but: was <4>
```

REPRODUCE WITH: gradle :core:integTest -Dtests.seed=43CE48AB8C847E3F -Dtests.class=org.elasticsearch.cluster.metadata.TemplateUpgradeServiceIT -Dtests.method="testTemplateUpdate" -Dtests.security.manager=true -Dtests.locale=ru-RU -Dtests.timezone=America/Indiana/Indianapolis

**Comment by tbrooks8** [comment]
Another:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian/1157/console

**Comment by imotov** [comment]
This test didn't fail since the fix above was pushed on Jun 26th. Closing.
