### ISSUE TITLE
org.elasticsearch.search.basic.SearchWithRandomIOExceptionsIT#testRandomDirectoryIOExceptions() fails in CI

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#25418]
* Build failure link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/368/consoleFull
* Error message: 

```
   > Caused by: java.lang.AssertionError: local checkpoint [-2] for allocation ID [pYaRZ11-Rs-zMCSo8uu_vg] violates being at least the global checkpoint [5]
   > 	at __randomizedtesting.SeedInfo.seed([2595C06C2A73369E]:0)
   > 	at org.elasticsearch.index.seqno.GlobalCheckpointTracker.updateAllocationIdsFromPrimaryContext(GlobalCheckpointTracker.java:411)
   > 	at org.elasticsearch.index.seqno.SequenceNumbersService.updateAllocationIdsFromPrimaryContext(SequenceNumbersService.java:186)
   > 	at org.elasticsearch.index.shard.IndexShard.updateAllocationIdsFromPrimaryContext(IndexShard.java:1710)
   > 	at org.elasticsearch.indices.recovery.RecoveryTarget.handoffPrimaryContext(RecoveryTarget.java:383)
   > 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$HandoffPrimaryContextRequestHandler.messageReceived(PeerRecoveryTargetService.java:425)
   > 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$HandoffPrimaryContextRequestHandler.messageReceived(PeerRecoveryTargetService.java:420)
   > 	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30)
   > 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
   > 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1525)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   > 	at java.lang.Thread.run(Thread.java:745)
```

* Reproduction line: `gradle :core:integTest -Dtests.seed=2595C06C2A73369E -Dtests.class=org.elasticsearch.search.basic.SearchWithRandomIOExceptionsIT -Dtests.method="testRandomDirectoryIOExceptions" -Dtests.security.manager=true -Dtests.locale=no -Dtests.timezone=Europe/Minsk` (Does not reproduce locally)
* Analysis: It's hard to tell (for me) from the output but this may be related to #25122.

**Comment by jasontedor** [comment]
Duplicates #25415
