### ISSUE TITLE
org.elasticsearch.recovery.FullRollingRestartIT#testFullRollingRestart fails in CI

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#25420]
* Test failure link: 	https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/836/console
* Failure output: 

```
ERROR   63.5s J2 | FullRollingRestartIT.testFullRollingRestart <<< FAILURES!
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=1069, maxMBSortInHeap=5.470706583403575, sim=RandomSimilarity(queryNorm=true): {}, locale=ar-SA, timezone=Etc/GMT
   > Throwable #1: java.lang.AssertionError: cluster health request timed out
   > 	at org.elasticsearch.recovery.FullRollingRestartIT.assertTimeout(FullRollingRestartIT.java:48)
   > 	at org.elasticsearch.recovery.FullRollingRestartIT.testFullRollingRestart(FullRollingRestartIT.java:101)
   > 	at java.lang.Thread.run(Thread.java:745)Throwable #2: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=8246, name=elasticsearch[node_t0][generic][T#2], state=RUNNABLE, group=TGRP-FullRollingRestartIT]
   > Caused by: java.lang.AssertionError: local checkpoint [-2] for allocation ID [uPkNGQ4LQhOkUcBCJ2m9dw] violates being at least the global checkpoint [667]
   > 	at __randomizedtesting.SeedInfo.seed([E368B9D19416FD9C]:0)
   > 	at org.elasticsearch.index.seqno.GlobalCheckpointTracker.updateAllocationIdsFromPrimaryContext(GlobalCheckpointTracker.java:411)
   > 	at org.elasticsearch.index.seqno.SequenceNumbersService.updateAllocationIdsFromPrimaryContext(SequenceNumbersService.java:186)
   > 	at org.elasticsearch.index.shard.IndexShard.updateAllocationIdsFromPrimaryContext(IndexShard.java:1710)
   > 	at org.elasticsearch.indices.recovery.RecoveryTarget.handoffPrimaryContext(RecoveryTarget.java:383)
   > 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$HandoffPrimaryContextRequestHandler.messageReceived(PeerRecoveryTargetService.java:425)
   > 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$HandoffPrimaryContextRequestHandler.messageReceived(PeerRecoveryTargetService.java:420)
   > 	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30)
   > 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
   > 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1525)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   > 	at java.lang.Thread.run(Thread.java:745)

```

* Reproduction line: `gradle :core:integTest -Dtests.seed=CB3F72B60DA71626 -Dtests.class=org.elasticsearch.recovery.FullRollingRestartIT -Dtests.method="testFullRollingRestart" -Dtests.security.manager=true -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" -Dtests.locale=en-IN -Dtests.timezone=Asia/Barnaul`
* Frequency: reproduces always.

It seems to have the same root cause as #25418.

**Comment by jasontedor** [comment]
Duplicates #25415
