### ISSUE TITLE
[CI] DocsClientYamlTestSuiteIT test {yaml=painless/painless-getting-started/line_186}

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#25466]
```
  1> [2017-06-29T03:20:41,177][INFO ][o.e.s.DocsClientYamlTestSuiteIT] [test {yaml=painless/painless-getting-started/line_186}]: after test
  1> [2017-06-29T03:20:41,182][INFO ][o.e.s.DocsClientYamlTestSuiteIT] Stash dump on failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "took" : 20,
  1>       "timed_out" : false,
  1>       "_shards" : {
  1>         "total" : 5,
  1>         "successful" : 1,
  1>         "failed" : 4,
  1>         "failures" : [
  1>           {
  1>             "shard" : 1,
  1>             "index" : "hockey",
  1>             "node" : "8sXFD-bAQcWdlzQ6waGkwg",
  1>             "reason" : {
  1>               "type" : "script_exception",
  1>               "reason" : "runtime error",
  1>               "script_stack" : [
  1>                 "doc.born.value.year",
  1>                 "              ^---- HERE"
  1>               ],
  1>               "script" : "doc.born.value.year",
  1>               "lang" : "painless",
  1>               "caused_by" : {
  1>                 "type" : "illegal_argument_exception",
  1>                 "reason" : "Unable to find dynamic field [year] for class [java.lang.Long]."
  1>               }
  1>             }
  1>           }
  1>         ]
  1>       },
  1>       "hits" : {
  1>         "total" : 11,
  1>         "max_score" : 1.0,
  1>         "hits" : [ ]
  1>       }
  1>     }
  1>   }
  1> }]
  1> [2017-06-29T03:20:41,182][ERROR][o.e.s.DocsClientYamlTestSuiteIT] This failing test was generated by documentation starting at painless/painless-getting-started.asciidoc:line_186. It may include many snippets. See docs/README.asciidoc for an explanation of test generation.
FAILURE 0.17s | DocsClientYamlTestSuiteIT.test {yaml=painless/painless-getting-started/line_186} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [painless/painless-getting-started:207]: field [_shards.failures] has a true value but it shouldn't
   > Expected: ("" or equalToIgnoringCase("false") or "0")
   >      but: was "[{shard=1, index=hockey, node=8sXFD-bAQcWdlzQ6waGkwg, reason={type=script_exception, reason=runtime error, script_stack=[doc.born.value.year,               ^---- HERE], script=doc.born.value.year, lang=painless, caused_by={type=illegal_argument_exception, reason=Unable to find dynamic field [year] for class [java.lang.Long].}}}]"
   > 	at __randomizedtesting.SeedInfo.seed([F4967EB1159B27E:871D5831BFA5DF86]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:345)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:325)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.lang.AssertionError: field [_shards.failures] has a true value but it shouldn't
   > Expected: ("" or equalToIgnoringCase("false") or "0")
   >      but: was "[{shard=1, index=hockey, node=8sXFD-bAQcWdlzQ6waGkwg, reason={type=script_exception, reason=runtime error, script_stack=[doc.born.value.year,               ^---- HERE], script=doc.born.value.year, lang=painless, caused_by={type=illegal_argument_exception, reason=Unable to find dynamic field [year] for class [java.lang.Long].}}}]"
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.test.rest.yaml.section.IsFalseAssertion.doAssert(IsFalseAssertion.java:59)
   > 	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:341)
   > 	... 37 more
```

```
gradle :docs:integTestRunner -Dtests.seed=F4967EB1159B27E -Dtests.class=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT -Dtests.method="test {yaml=painless/painless-getting-started/line_186}" -Dtests.security.manager=true -Dtests.locale=es-CO -Dtests.timezone=Africa/El_Aaiun
```

This ~~doesn't~~ **does** reproduce. I don't follow why it doesn't fail on master. I guess the `born` field doesn't get picked up as a date field.

Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-intake/1394/consoleText

**Comment by martijnvg** [comment]
This fixed the painless getting started on 5.x branch: 5b80d8d6f9c569258374509d7a612087ed503daf
and this on 5.5 branch: 1884e34c94a99e6617eb019a6e1b50e8d6fcc175
