### ISSUE TITLE
[CI] SetsTests.testDifference failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#25464]
```
FAILURE 0.11s | SetsTests.testDifference <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: max must be >= min: 0, -1
   >    at __randomizedtesting.SeedInfo.seed([7C1DF73383BC80:C090FDC50BC15D71]:0)
   >    at com.carrotsearch.randomizedtesting.generators.RandomNumbers.randomIntBetween(RandomNumbers.java:16)
   >    at com.carrotsearch.randomizedtesting.RandomizedTest.randomInt(RandomizedTest.java:163)
   >    at org.elasticsearch.test.ESTestCase.randomInt(ESTestCase.java:533)
   >    at org.elasticsearch.test.ESTestCase.randomSubsetOf(ESTestCase.java:832)
   >    at org.elasticsearch.common.util.set.SetsTests.randomSets(SetsTests.java:80)
   >    at org.elasticsearch.common.util.set.SetsTests.testDifference(SetsTests.java:38)
   >    at java.lang.Thread.run(Thread.java:748)
```

Reproduces with: gradle :core:test -Dtests.seed=7C1DF73383BC80 -Dtests.class=org.elasticsearch.common.util.set.SetsTests -Dtests.method="testDifference" -Dtests.security.manager=true

Looks like a test issue.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+java9-periodic/3040/console

**Comment by martijnvg** [comment]
Fixed via: efb44895d1603f9b6797b3c36e56d6b66222c9d2
