### ISSUE TITLE
[CI] SearchWithRandomIOExceptionsIT#testRandomDirectoryIOExceptions failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#25467]
Fails getting into a green state after the test ran:

```
java.lang.AssertionError: timed out waiting for green state
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureColor(ESIntegTestCase.java:944)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:910)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:899)
   > 	at org.elasticsearch.search.basic.SearchWithRandomIOExceptionsIT.testRandomDirectoryIOExceptions(SearchWithRandomIOExceptionsIT.java:191)
   > 	at java.lang.Thread.run(Thread.java:745)Throwable #2: java.lang.AssertionError: All incoming requests on node [node_sd5] should have finished. Expected 0 but got 182
   > Expected: <0L>
   >      but: was <182L>
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.test.InternalTestCluster.lambda$assertRequestsFinished$17(InternalTestCluster.java:2072)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:722)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:696)
   > 	at org.elasticsearch.test.InternalTestCluster.assertRequestsFinished(InternalTestCluster.java:2069)
   > 	at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2048)
   > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:586)
   > 	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2067)
   > 	at java.lang.Thread.run(Thread.java:745)
```

Likely cause looks to be this:

```
Caused by: java.lang.AssertionError: local checkpoint [-2] for allocation ID [lVoxeGWQS3ub9lQD41DqmA] violates being at least the global checkpoint [3]
   > 	at __randomizedtesting.SeedInfo.seed([49D96F7A83402E01]:0)
   > 	at org.elasticsearch.index.seqno.GlobalCheckpointTracker.updateAllocationIdsFromPrimaryContext(GlobalCheckpointTracker.java:411)
   > 	at org.elasticsearch.index.seqno.SequenceNumbersService.updateAllocationIdsFromPrimaryContext(SequenceNumbersService.java:186)
   > 	at org.elasticsearch.index.shard.IndexShard.updateAllocationIdsFromPrimaryContext(IndexShard.java:1707)
   > 	at org.elasticsearch.indices.recovery.RecoveryTarget.handoffPrimaryContext(RecoveryTarget.java:383)
   > 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$HandoffPrimaryContextRequestHandler.messageReceived(PeerRecoveryTargetService.java:425)
   > 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$HandoffPrimaryContextRequestHandler.messageReceived(PeerRecoveryTargetService.java:420)
   > 	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30)
   > 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
   > 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1525)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   > 	at java.lang.Thread.run(Thread.java:745)
```

Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=sles/1182/consoleText

**Comment by martijnvg** [comment]
Another similar failure that also shows a timeout when waiting to get in a green state:

(sys out and error out get mixed together....)

```
WARNING: Uncaught exception in thread: Thread[elasticsearch[node_s1][generic][T#6],5,TGRP-SearchWithRandomIOExceptionsIT]
  2> java.lang.AssertionError: local checkpoint [-2] for allocation ID [WpXAFOO4R1qco1_j4RzTZg] violates being at least the global checkpoint [15]
  1> [2017-06-29T05:49:06,412][WARN ][o.e.d.i.m.UidFieldMapper ] Fielddata access on the _uid field is deprecated, use _id instead
  1> [2017-06-29T05:49:06,417][INFO ][o.e.s.b.SearchWithRandomIOExceptionsIT] Match all Successful shards: [9]  numShards: [9]
  1> [2017-06-29T05:49:06,418][INFO ][o.e.c.m.MetaDataIndexStateService] [node_s1] closing indices [[[test/U4rCROC5Q4iaAMZlIBDh7Q]]]
  1> [2017-06-29T05:49:06,429][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s2] [test][0] start check index
  1> [2017-06-29T05:49:06,431][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s0] [test][1] start check index
  1> [2017-06-29T05:49:06,439][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s2] [test][0] end check index
  1> [2017-06-29T05:49:06,439][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s0] [test][1] end check index
  1> [2017-06-29T05:49:06,447][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s2] [test][2] start check index
  1> [2017-06-29T05:49:06,449][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s0] [test][3] start check index
  1> [2017-06-29T05:49:06,455][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s2] [test][2] end check index
  1> [2017-06-29T05:49:06,464][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s0] [test][3] end check index
  1> [2017-06-29T05:49:06,465][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s2] [test][3] start check index
  2> 	at __randomizedtesting.SeedInfo.seed([1C7E3EB249EDF639]:0)
  2> 	at org.elasticsearch.index.seqno.GlobalCheckpointTracker.updateAllocationIdsFromPrimaryContext(GlobalCheckpointTracker.java:411)
  1> [2017-06-29T05:49:06,474][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s0] [test][5] start check index
  2> 	at org.elasticsearch.index.seqno.SequenceNumbersService.updateAllocationIdsFromPrimaryContext(SequenceNumbersService.java:186)
  2> 	at org.elasticsearch.index.shard.IndexShard.updateAllocationIdsFromPrimaryContext(IndexShard.java:1707)
  1> [2017-06-29T05:49:06,475][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s2] [test][3] end check index
  1> [2017-06-29T05:49:06,483][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s2] [test][4] start check index
  2> 	at org.elasticsearch.indices.recovery.RecoveryTarget.handoffPrimaryContext(RecoveryTarget.java:383)
  1> [2017-06-29T05:49:06,483][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s0] [test][5] end check index
  1> [2017-06-29T05:49:06,490][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s2] [test][4] end check index
  1> [2017-06-29T05:49:06,493][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s0] [test][6] start check index
  2> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$HandoffPrimaryContextRequestHandler.messageReceived(PeerRecoveryTargetService.java:425)
  1> [2017-06-29T05:49:06,505][INFO ][o.e.t.s.MockFSIndexStore$Listener] [node_s0] [test][6] end check index
  2> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$HandoffPrimaryContextRequestHandler.messageReceived(PeerRecoveryTargetService.java:420)
  2> 	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30)
  2> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
  2> 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1525)
  2> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
  2> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  2> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  2> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  2> 	at java.lang.Thread.run(Thread.java:745)
```

I also saw this in the log that may be helpful:

```
[2017-06-29T05:49:36,744][WARN ][o.e.i.c.IndicesClusterStateService] [node_s1] [[test][0]] marking and sending shard failed due to [failed recovery]
  1> org.elasticsearch.indices.recovery.RecoveryFailedException: [test][0]: Recovery failed from {node_s2}{_Hxlo9MVRLeWjBpKP4zWTA}{pzt94GY9RbOVpIDwvVX1Kw}{127.0.0.1}{127.0.0.1:9581} into {node_s1}{TRUI9CxQRoi7_KNVgnhhQg}{ynucPtglSdmGkzv3LAR8jw}{127.0.0.1}{127.0.0.1:9582} (failed to retry recovery)
  1> 	at org.elasticsearch.indices.recovery.RecoveriesCollection.resetRecovery(RecoveriesCollection.java:122) ~[main/:?]
  1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.retryRecovery(PeerRecoveryTargetService.java:153) ~[main/:?]
  1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.retryRecovery(PeerRecoveryTargetService.java:149) ~[main/:?]
  1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.doRecovery(PeerRecoveryTargetService.java:256) ~[main/:?]
  1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.access$900(PeerRecoveryTargetService.java:75) ~[main/:?]
  1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$RecoveryRunner.doRun(PeerRecoveryTargetService.java:616) ~[main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_60]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_60]
  1> 	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_60]
  1> Caused by: java.lang.IllegalStateException: cannot reset recovery as previous attempt made it past finalization step
  1> 	at org.elasticsearch.indices.recovery.RecoveryTarget.resetRecovery(RecoveryTarget.java:216) ~[main/:?]
  1> 	at org.elasticsearch.indices.recovery.RecoveriesCollection.resetRecovery(RecoveriesCollection.java:108) ~[main/:?]
  1> 	... 10 more
  1> [2017-06-29T05:49:36,745][WARN ][o.e.c.a.s.ShardStateAction] [node_s1] [test][0] received shard failed for shard id [[test][0]], allocation id [7sMj5hryQZiudlEshYF9mg], primary term [0], message [failed recovery], failure [RecoveryFailedException[[test][0]: Recovery failed from {node_s2}{_Hxlo9MVRLeWjBpKP4zWTA}{pzt94GY9RbOVpIDwvVX1Kw}{127.0.0.1}{127.0.0.1:9581} into {node_s1}{TRUI9CxQRoi7_KNVgnhhQg}{ynucPtglSdmGkzv3LAR8jw}{127.0.0.1}{127.0.0.1:9582} (failed to retry recovery)]; nested: IllegalStateException[cannot reset recovery as previous attempt made it past finalization step]; ]
  1> org.elasticsearch.indices.recovery.RecoveryFailedException: [test][0]: Recovery failed from {node_s2}{_Hxlo9MVRLeWjBpKP4zWTA}{pzt94GY9RbOVpIDwvVX1Kw}{127.0.0.1}{127.0.0.1:9581} into {node_s1}{TRUI9CxQRoi7_KNVgnhhQg}{ynucPtglSdmGkzv3LAR8jw}{127.0.0.1}{127.0.0.1:9582} (failed to retry recovery)
  1> 	at org.elasticsearch.indices.recovery.RecoveriesCollection.resetRecovery(RecoveriesCollection.java:122) ~[main/:?]
  1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.retryRecovery(PeerRecoveryTargetService.java:153) ~[main/:?]
  1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.retryRecovery(PeerRecoveryTargetService.java:149) ~[main/:?]
  1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.doRecovery(PeerRecoveryTargetService.java:256) ~[main/:?]
  1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.access$900(PeerRecoveryTargetService.java:75) ~[main/:?]
  1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$RecoveryRunner.doRun(PeerRecoveryTargetService.java:616) ~[main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_60]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_60]
  1> 	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_60]
  1> Caused by: java.lang.IllegalStateException: cannot reset recovery as previous attempt made it past finalization step
  1> 	at org.elasticsearch.indices.recovery.RecoveryTarget.resetRecovery(RecoveryTarget.java:216) ~[main/:?]
  1> 	at org.elasticsearch.indices.recovery.RecoveriesCollection.resetRecovery(RecoveriesCollection.java:108) ~[main/:?]
  1> 	... 10 more
```

Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/846/consoleFull

**Comment by jasontedor** [comment]
Duplicates #25415
