### ISSUE TITLE
[CI] Failure in SmokeTestMultiNodeClientYamlTestSuiteIT indices.stats/20_translog/Translog retention

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#25490]
Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu/1187/console

Stash dump:

```
  1> [2017-06-29T22:41:29,217][INFO ][o.e.s.SmokeTestMultiNodeClientYamlTestSuiteIT] Stash dump on failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "_shards" : {
  1>         "total" : 10,
  1>         "successful" : 9,
  1>         "failed" : 0
  1>       },
  1>       "_all" : {
  1>         "primaries" : {
  1>           "translog" : {
  1>             "operations" : 1,
  1>             "size_in_bytes" : 368,
  1>             "uncommitted_operations" : 0,
  1>             "uncommitted_size_in_bytes" : 215
  1>           }
  1>         },
  1>         "total" : {
  1>           "translog" : {
  1>             "operations" : 1,
  1>             "size_in_bytes" : 540,
  1>             "uncommitted_operations" : 0,
  1>             "uncommitted_size_in_bytes" : 387
  1>           }
  1>         }
  1>       },
  1>       "indices" : {
  1>         "test" : {
  1>           "primaries" : {
  1>             "translog" : {
  1>               "operations" : 1,
  1>               "size_in_bytes" : 368,
  1>               "uncommitted_operations" : 0,
  1>               "uncommitted_size_in_bytes" : 215
  1>             }
  1>           },
  1>           "total" : {
  1>             "translog" : {
  1>               "operations" : 1,
  1>               "size_in_bytes" : 540,
  1>               "uncommitted_operations" : 0,
  1>               "uncommitted_size_in_bytes" : 387
  1>             }
  1>           }
  1>         }
  1>       }
  1>     },
  1>     "empty_size" : 215
  1>   }
  1> }]
```

Stack trace:

```
   > Throwable #1: java.lang.AssertionError: Failure at [indices.stats/20_translog:59]: indices.test.primaries.translog.size_in_bytes didn't match expected value:
   > indices.test.primaries.translog.size_in_bytes: expected [215] but was [368]
   > 	at __randomizedtesting.SeedInfo.seed([E1A2E125DDBD422A:69F6DEFF73412FD2]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:348)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:328)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.lang.AssertionError: indices.test.primaries.translog.size_in_bytes didn't match expected value:
   > indices.test.primaries.translog.size_in_bytes: expected [215] but was [368]
   > 	at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:87)
   > 	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:344)
   > 	... 37 more
```

Reproduction command:

```
gradle :qa:smoke-test-multinode:integTestRunner -Dtests.seed=E1A2E125DDBD422A -Dtests.class=org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT -Dtests.method="test {yaml=indices.stats/20_translog/Translog retention}" -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=America/Godthab
```

This did not reproduce on my laptop.

**Comment by droberts195** [comment]
@bleskes I have assigned this to you as you created the test fairly recently - apologies if you're the wrong person

**Comment by bleskes** [comment]
fixed by https://github.com/elastic/elasticsearch/commit/a6db0ea9087619d8b9bca2dfdd11a921012990de
