### ISSUE TITLE
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}

### ISSUE THREAD

**Issue by luyee** [elastic/elasticsearch#25526]
transport version  5.4.0

```
	         <dependency>
		    <groupId>org.elasticsearch.client</groupId>
		    <artifactId>transport</artifactId>
		    <version>5.4.0</version>
		</dependency>
```
es version 5.4.0

es 's  yml

```
cluster.name: elasticsearch
network.host: 172.28.3.169
network.publish_host: 172.28.3.169
network.bind_host: 172.28.3.169
transport.tcp.port: 9999

```

client 
```
Settings settings = Settings.builder()
				.put("cluster.name", "elasticsearch") 
				/* .put("client.transport.ignore_cluster_name",true) */
				.put("client.transport.sniff", true) // auto
				.build();

		String ip = "172.28.3.169";
		int port = 9999;
		TransportClient client = new PreBuiltTransportClient(settings)
				.addTransportAddress(new InetSocketTransportAddress(InetAddress
						.getByName(ip), port));
		BulkRequestBuilder bulkRequestBuilder = client.prepareBulk();
		HashMap<String, Object> hashMap = new HashMap<String, Object>();
		hashMap.put("user", "kimchy");
		hashMap.put("id", String.valueOf(System.currentTimeMillis()));
		hashMap.put("message", "trying out Elasticsearch");

		IndexRequestBuilder builder = client.prepareIndex("indexname",
				"indextype", hashMap.get("id").toString());

		builder.setSource(hashMap);

		bulkRequestBuilder.add(builder);
		BulkResponse response = bulkRequestBuilder.execute().actionGet();
```
put("client.transport.sniff", false) works well  , however  put("client.transport.sniff", true)  get exception 

```
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{XrTFgdVeRo2gfbQiqWLRrQ}{172.28.3.169}{172.28.3.169:9999}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:348)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:246)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)

```

but transport-client   in 5.4.1 
```
	         <dependency>
		    <groupId>org.elasticsearch.client</groupId>
		    <artifactId>transport</artifactId>
		    <version>5.4.1</version>
		</dependency>
```

put("client.transport.sniff", true),  it works

**Comment by javanna** [comment]
Please ask questions like this in our forum at https://discuss.elastic.co/ . We reserve github issues for verified bugs or feature requests.
