### ISSUE TITLE
TransportSerializationException

### ISSUE THREAD

**Issue by flefebure** [elastic/elasticsearch#25564]
With a 5.4.3 single node cluster and a 5.4.3 java client, last JDK, all centos Linux : I meet the following error when the x-pack is installed on the cluster (with config  xpack.security.enabled: false) 

```
org.elasticsearch.transport.TransportSerializationException: Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.state.ClusterStateResponse]
        at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:1442) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1414) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) ~[transport-netty4-client-5.4.3.jar:5.4.3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[netty-codec-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[netty-codec-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[netty-codec-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) ~[netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) ~[netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) ~[netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) ~[netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) ~[netty-transport-4.1.11.Final.jar:4.1.11.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-common-4.1.11.Final.jar:4.1.11.Final]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.cluster.metadata.MetaData$Custom][ml]
        at org.elasticsearch.common.io.stream.NamedWriteableRegistry.getReader(NamedWriteableRegistry.java:112) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:45) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:39) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.cluster.metadata.MetaData.readFrom(MetaData.java:675) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.cluster.ClusterState.readFrom(ClusterState.java:659) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.action.admin.cluster.state.ClusterStateResponse.readFrom(ClusterStateResponse.java:58) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:1439) ~[elasticsearch-5.4.3.jar:5.4.3]
        ... 23 common frames omitted

```
The problem should be related to https://discuss.elastic.co/t/remote-transport-exception-in-5-1-1-w-jdk-1-8-0-111/69607/16
But this discussion related issues are supposed to be closed (dec 2016) so...

Franck

**Comment by jasontedor** [comment]
This is the repository for open source Elasticsearch only yet the issue you are seeing here is from closed source X-Pack. As such, I would like to ask you to post a topic on the [forum](https://discuss.elastic.co) in the X-Pack category.

**Comment by akshaymaniyar** [comment]
@flefebure : Were you able to solve it? I am facing the same issue

**Comment by flefebure** [comment]
Hi,
You may have a look to this thread : https://discuss.elastic.co/t/bulk-indexing-with-x-pack-exception/92086

**Comment by akshaymaniyar** [comment]
Thanks. I had started this thread https://discuss.elastic.co/t/transport-client-error-after-installing-x-pack-on-es-5-5-1/97021

And got a similar response.

So are you now using the xpack-transport-client or you were able to use the normal transport client with xpack.ml.enabled: false?

**Comment by lobodpav** [comment]
Setting up the `xpack.ml.enabled: false` option along with `xpack.security.enabled: false` solved the issue on my end. See https://discuss.elastic.co/t/bulk-indexing-with-x-pack-exception/92086/5.

**Comment by tlapusan** [comment]
> Setting up the `xpack.ml.enabled: false` option along with `xpack.security.enabled: false` solved the issue on my end. See https://discuss.elastic.co/t/bulk-indexing-with-x-pack-exception/92086/5.

Thanks @lobodpav 
Thanks @
