### ISSUE TITLE
Failure after installing ingest-geoip plugin when using a custom config directory

### ISSUE THREAD

**Issue by sophiec20** [elastic/elasticsearch#25666]
**Elasticsearch version**: 5.6-SNAPSHOT

**Plugins installed**: X-Pack, Ingest Geoip, Ingest User Agent

**JVM version** (`java -version`):
`openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)`

**OS version** (`uname -a` if on a Unix-like system):
`Linux ip-10-0-1-124 4.4.35-33.55.amzn1.x86_64 #1 SMP Tue Dec 6 20:30:04 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:
Elasticsearch fails to start after installing the ingest-geoip plugin, when using a custom `path.conf`

If I manually create a directory called `ingest-geoip` under `path.conf`, then elasticsearch starts without error.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Run `bin/elasticsearch-plugin install file:///path_to_plugin/ingest-geoip-5.6.0-SNAPSHOT.zip`
 2. Start elasticsearch using a custom `path.conf`
 3. Check the elasticsearch.log

**Provide logs (if relevant)**:
```[2017-07-12T10:29:01,885][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.RuntimeException: java.nio.file.NoSuchFileException: /data/5.6-elastic-20170711/config-node1/ingest-geoip
        at org.elasticsearch.ingest.geoip.IngestGeoIpPlugin.getProcessors(IngestGeoIpPlugin.java:74) ~[?:?]
        at org.elasticsearch.ingest.IngestService.<init>(IngestService.java:58) ~[elasticsearch-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.elasticsearch.node.Node.<init>(Node.java:354) ~[elasticsearch-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) ~[elasticsearch-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:341) [elasticsearch-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) [elasticsearch-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) [elasticsearch-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) [elasticsearch-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) [elasticsearch-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.elasticsearch.cli.Command.main(Command.java:88) [elasticsearch-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) [elasticsearch-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) [elasticsearch-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
Caused by: java.nio.file.NoSuchFileException: /data/5.6-elastic-20170711/config-node1/ingest-geoip
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427) ~[?:?]
        at java.nio.file.Files.newDirectoryStream(Files.java:457) ~[?:1.8.0_131]
        at java.nio.file.Files.list(Files.java:3451) ~[?:1.8.0_131]
        at org.elasticsearch.ingest.geoip.IngestGeoIpPlugin.loadDatabaseReaders(IngestGeoIpPlugin.java:85) ~[?:?]
        at org.elasticsearch.ingest.geoip.IngestGeoIpPlugin.getProcessors(IngestGeoIpPlugin.java:72) ~[?:?]
        ... 13 more
[2017-07-12T10:29:01,897][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [node1] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /data/5.6-elastic-20170711/config-node1/ingest-geoip
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.6.0-SNAPSHOT.jar:5.6.0-SNAPSHOT]```

**Comment by jasontedor** [comment]
The ingest-geoip ships with databases that are stored in the config folder for the plugin (so they are installed in `config/ingest-geoip` when you install the plugin).  These databases are needed when the plugin starts. If you use a custom config path, you either need to:
 - specify this custom config path when you install the plugin so that the databases are installed in the correct location
 - move the databases from where they are currently installed to the proper subdirectory of the config path

```
07:34:44 [jason:~/src…stic/elasticsearch-5.x] 5.x+ ± tree /tmp/config
/tmp/config
├── elasticsearch.yml
├── jvm.options
└── log4j2.properties

0 directories, 3 files
07:35:16 [jason:~/src…stic/elasticsearch-5.x] 5.x+ 64 ± CONF_DIR=/tmp/config ~/elasticsearch/elasticsearch-5.6.0-SNAPSHOT/bin/elasticsearch-plugin file:///Users/jason/src/elastic/elasticsearch-5.x/plugins/ingest-geoip/build/distributions/ingest-geoip-5.6.0-SNAPSHOT.zip 
CONF_DIR=/tmp/config ~/elasticsearch/elasticsearch-5.6.0-SNAPSHOT/bin/elasticsearch-plugin install file:///Users/jason/src/elastic/elasticsearch-5.x/plugins/ingest-geoip/build/distributions/ingest-geoip-5.6.0-SNAPSHOT.zip 
-> Downloading file:///Users/jason/src/elastic/elasticsearch-5.x/plugins/ingest-geoip/build/distributions/ingest-geoip-5.6.0-SNAPSHOT.zip
[=================================================] 100%   
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]-> Installed ingest-geoip
07:35:16 [jason:~/src…stic/elasticsearch-5.x] 5.x+ 64 ± 
07:35:28 [jason:~/src…stic/elasticsearch-5.x] 5.x+ 1 ± tree /tmp/config
/tmp/config
├── elasticsearch.yml
├── ingest-geoip
│   ├── GeoLite2-City.mmdb.gz
│   └── GeoLite2-Country.mmdb.gz
├── jvm.options
└── log4j2.properties

1 directory, 5 files
07:35:30 [jason:~/src…stic/elasticsearch-5.x] 5.x+ ± 
```

**Comment by sophiec20** [comment]
Not a bug. Thanks. Closing.
