### ISSUE TITLE
java.lang.IndexOutOfBoundsException: readerIndex(537868) + length(1)

### ISSUE THREAD

**Issue by YDHui** [elastic/elasticsearch#25663]
Hi,there is always a warn in my elasticsearch logs ,the logs content is 

> [2017-07-12T00:29:07,787][WARN ][o.e.a.a.c.n.s.TransportNodesStatsAction] [es_10.10.16.14] not accumulating exceptions, excluding exception from response
org.elasticsearch.action.FailedNodeException: Failed node [6IUf6qgJQuWKeubXVz_OCg]
at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onFailure(TransportNodesAction.java:247) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$300(TransportNodesAction.java:160) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleException(TransportNodesAction.java:219) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:955) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.transport.TcpTransport.lambda$handleException$15(TcpTransport.java:1277) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.threadpool.ThreadPool.lambda$static$0(ThreadPool.java:147) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.transport.TcpTransport.handleException(TcpTransport.java:1275) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:1240) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1213) [elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) [transport-netty4-5.0.1.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [netty-codec-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:513) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:467) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437) [netty-transport-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty-common-4.1.5.Final.jar:4.1.5.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: org.elasticsearch.transport.RemoteTransportException: [Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.stats.NodeStats]]
Caused by: org.elasticsearch.transport.TransportSerializationException: Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.stats.NodeStats]
	at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:1241) ~[elasticsearch-5.0.1.jar:5.0.1]
	... 23 more
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(587550) + length(1) exceeds writerIndex(587550): UnpooledDuplicatedByteBuf(ridx: 587550, widx: 587550, cap: 1048576, unwrapped: PooledHeapByteBuf(ridx: 6, widx: 587550, cap: 1048576))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1395) ~[?:?]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687) ~[?:?]
	at org.elasticsearch.transport.netty4.ByteBufStreamInput.readByte(ByteBufStreamInput.java:126) ~[?:?]
	at org.elasticsearch.common.io.stream.FilterStreamInput.readByte(FilterStreamInput.java:39) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.common.io.stream.StreamInput.readString(StreamInput.java:334) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.monitor.jvm.JvmStats$MemoryPool.<init>(JvmStats.java:423) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.common.io.stream.StreamInput.readList(StreamInput.java:842) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.monitor.jvm.JvmStats$Mem.<init>(JvmStats.java:484) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.monitor.jvm.JvmStats.<init>(JvmStats.java:143) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:682) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.action.admin.cluster.node.stats.NodeStats.readFrom(NodeStats.java:216) ~[elasticsearch-5.0.1.jar:5.0.1]
	at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:1238) ~[elasticsearch-5.0.1.jar:5.0.1]
	... 23 more

My ES status is green and is work fine ,but i don't know why it show this logs
My ES version is 5.0.1,Thanks

**Comment by jasontedor** [comment]
There was a serialization bug due to a race condition early in the life of 5.x. It is fixed in 5.1.2, you should upgrade to at least this version.

**Comment by hjxhjh** [comment]
@jasontedor is this bug exist in version 2.4.5?

**Comment by jasontedor** [comment]
@hjxhjh No.
