### ISSUE TITLE
FullClusterRestartIT testSearch failure: upgraded versions assertion failed

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#25678]
build log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=amazon/1235/console

commit the issue is sourcing from: https://github.com/elastic/elasticsearch/commit/141aa226f4159ad57640a2029fa6ee29679d83f3

must be a timing issue due to upgrade api not yet fully completed?

I cannot reproduce locally with:

```
gradle :qa:full-cluster-restart:v5.6.0-SNAPSHOT#upgradedClusterTestRunner -Dtests.seed=1EB039452E8C78C4 -Dtests.class=org.elasticsearch.upgrades.FullClusterRestartIT -Dtests.method="testSearch" -Dtests.security.manager=true -Dtests.locale=ar-BH -Dtests.timezone=Israel
```

stacktrace:
```
  1> [2017-07-12T10:39:25,800][INFO ][o.e.u.FullClusterRestartIT] [testSearch]: after test
FAILURE 0.77s | FullClusterRestartIT.testSearch <<< FAILURES!
   > Throwable #1: java.lang.AssertionError
   > 	at __randomizedtesting.SeedInfo.seed([1EB039452E8C78C4:8C09AC106A95206B]:0)
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-unix-compatibility/os/amazon/qa/full-cluster-restart/build/testrun/v5.6.0-SNAPSHOT#upgradedClusterTestRunner/J0/temp/org.elasticsearch.upgrades.FullClusterRestartIT_1EB039452E8C78C4-001
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=1693, maxMBSortInHeap=6.590434489707286, sim=RandomSimilarity(queryNorm=true): {}, locale=ar-BH, timezone=Israel
  2> NOTE: Linux 4.4.44-39.55.amzn1.x86_64 amd64/Oracle Corporation 1.8.0_121 (64-bit)/cpus=4,threads=1,free=462886672,total=514850816
  2> NOTE: All tests run in this JVM: [FullClusterRestartIT]
   > 	at org.elasticsearch.upgrades.FullClusterRestartIT.assertUpgradeWorks(FullClusterRestartIT.java:483)
   > 	at org.elasticsearch.upgrades.FullClusterRestartIT.testSearch(FullClusterRestartIT.java:156)
   > 	at java.lang.Thread.run(Thread.java:745)
  1> [2017-07-12T10:39:25,815][INFO ][o.e.u.FullClusterRestartIT] [testRecovery]: before test
  1> [2017-07-12T10:39:25,876][INFO ][o.e.u.FullClusterRestartIT] [testRecovery]: after test
```

**Comment by talevy** [comment]
@martijnvg since it seems this assertion was used to avoid such timing problems, think you can take a look?

**Comment by martijnvg** [comment]
@talevy As far as I understand the upgrade api, it doesn't do anything in the background. If the api call return successfully it should have the upgrade. 

I fail to understand why this keeps failing. In this #25311 I tracked this failure, but without success. Something odd is going on here. Lets continue tracking this failure there?

**Comment by talevy** [comment]
ah OK! sure thing, will close this issue

**Comment by talevy** [comment]
dup of https://github.com/elastic/elasticsearch/issues/25311
