### ISSUE TITLE
DiscoveryWithServiceDisruptionsIT testAckedIndexing failure

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#25676]
There is a failure in one of the tests against service disruptions

build logs: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-unix-compatibility/os=ubuntu/962/console

reproduces with:
```
gradle :core:integTest -Dtests.seed=AFD59E58C9D4FD21 -Dtests.class=org.elasticsearch.discovery.DiscoveryWithServiceDisruptionsIT -Dtests.method="testAckedIndexing" -Dtests.security.manager=true -Dtests.locale=es-GT -Dtests.timezone=US/Michigan
```

failure snippet:

```
 1> [2017-07-12T02:02:41,667][INFO ][o.e.d.DiscoveryWithServiceDisruptionsIT] [testAckedIndexing]: after test
ERROR   13.5s J0 | DiscoveryWithServiceDisruptionsIT.testAckedIndexing <<< FAILURES!
   > Throwable #1: NoShardAvailableActionException[No shard available for [get [test][type][3]: routing [null]]]
   > 	at __randomizedtesting.SeedInfo.seed([AFD59E58C9D4FD21:25142AAB95A91B6A]:0)
   > 	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.perform(TransportSingleShardAction.java:209)
   > 	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.start(TransportSingleShardAction.java:186)
   > 	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction.doExecute(TransportSingleShardAction.java:95)
   > 	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction.doExecute(TransportSingleShardAction.java:59)
   > 	at org.elasticsearch.action.support.TransportAction.doExecute(TransportAction.java:146)
   > 	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:170)
   > 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:142)
   > 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:84)
   > 	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83)
   > 	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72)
   > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
   > 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
   > 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
   > 	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:62)
   > 	at org.elasticsearch.discovery.DiscoveryWithServiceDisruptionsIT.testAckedIndexing(DiscoveryWithServiceDisruptionsIT.java:609)
   > 	at java.lang.Thread.run(Thread.java:748)
Completed [285/315] on J0 in 192.64s, 18 tests, 1 error <<< FAILURES!
```

**Comment by bleskes** [comment]
I'll take this. I already started working this morning.

**Comment by bleskes** [comment]
A test failure from 2017, I don't this is worth chasing anymore... closing.
