### ISSUE TITLE
[CI] CompletionSuggestSearchIT testOptimzedPrunesDeletedDocs fails on 2.4

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#25687]
console logs:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+2.4+multijob-unix-compatibility/os=centos/102/console

reproduce with:
```
mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch:elasticsearch -Dtests.seed=DA9230B9D12F3BC -Dtests.class=org.elasticsearch.search.suggest.CompletionSuggestSearchIT -Dtests.method="testOptimzedPrunesDeletedDocs" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=en-SG -Dtests.timezone=Australia/Sydney
```

stacktrace:

```
   > Throwable #1: java.lang.AssertionError: Expected options [The Prodigy, Turbonegro, The Prodigy Firestarter, Turbonegro Get it on] length to be 3, but was 4
   > Expected: is <3>
   >      but: was <4>
   > 	at __randomizedtesting.SeedInfo.seed([DA9230B9D12F3BC:1DF1C91008677166]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.search.suggest.CompletionSuggestSearchIT.assertSuggestions(CompletionSuggestSearchIT.java:870)
   > 	at org.elasticsearch.search.suggest.CompletionSuggestSearchIT.assertSuggestionsNotInOrder(CompletionSuggestSearchIT.java:847)
   > 	at org.elasticsearch.search.suggest.CompletionSuggestSearchIT.testOptimzedPrunesDeletedDocs(CompletionSuggestSearchIT.java:1065)
```

**Comment by talevy** [comment]
Closing since it may very well be a no-op and just CI artifacts.
