### ISSUE TITLE
[CI] UUIDTests.testCompression fails to achieve expected compression

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#25714]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/3527/console

```
  1> [2017-07-14T02:45:57,237][INFO ][o.e.c.UUIDTests          ] [testCompression]: before test
  1> [2017-07-14T02:46:02,874][INFO ][o.e.c.UUIDTests          ] 500000 docs indexed at 10000 docs/s required 5.1mb bytes of disk space, or 10.9006 bytes per document. Took: 4.8s.
  1> [2017-07-14T02:46:06,210][INFO ][o.e.c.UUIDTests          ] 500000 docs indexed at 1000 docs/s required 6.2mb bytes of disk space, or 13.097472 bytes per document. Took: 3s.
  1> [2017-07-14T02:46:06,211][INFO ][o.e.c.UUIDTests          ] [testCompression]: after test
FAILURE 8.99s J2 | UUIDTests.testCompression <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: a value less than <13.0>
   >      but: <13.097472> was greater than <13.0>
   > 	at __randomizedtesting.SeedInfo.seed([E40FEE4F3D88213F:1F3AC8293756D16C]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.common.UUIDTests.testCompression(UUIDTests.java:124)
   > 	at java.lang.Thread.run(Thread.java:748)
```

Surprisingly it doesn't reproduce with 

```
gradle :core:test -Dtests.seed=E40FEE4F3D88213F -Dtests.class=org.elasticsearch.common.UUIDTests -Dtests.method="testCompression" -Dtests.security.manager=true -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" -Dtests.locale=hr -Dtests.timezone=Australia/Lindeman
```

**Comment by jpountz** [comment]
Hmm, I suspect we need to force SerialMergeScheduler if we want this test to be reproducible. I'll fix.
