### ISSUE TITLE
java.lang.ClassNotFoundException: org.elasticsearch.plugins.NetworkPlugin

### ISSUE THREAD

**Issue by ziadloo** [elastic/elasticsearch#25730]
**Describe the feature**:

Unable to add Elasticsearch to a Spring Boot project, facing `java.lang.ClassNotFoundException: org.elasticsearch.plugins.NetworkPlugin`

**Elasticsearch version**: 5.5.0

**Plugins installed**: []

**JVM version** (`java -version`):
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```
**OS version** (`uname -a` if on a Unix-like system):
```
Linux flash 4.4.0-83-generic #106~14.04.1-Ubuntu SMP Mon Jun 26 18:10:19 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
**Description of the problem including expected versus actual behavior**:

Adding the Elasticsearch's dependencies to a Spring Boot project and trying to instantiate a `TransportClient` object leads to `java.lang.ClassNotFoundException: org.elasticsearch.plugins.NetworkPlugin`.

The expected result is that it shouldn't throw a ClassNotFoundException exception.

**Steps to reproduce**:

 1. Download a Spring [sample project](https://github.com/spring-guides/gs-rest-service.git)
 2. Modify the pom.xml to add Elasticsearch dependencies:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.springframework</groupId>
    <artifactId>gs-rest-service</artifactId>
    <version>0.1.0</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.3.RELEASE</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>transport</artifactId>
            <version>5.5.0</version>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>5.5.0</version>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.8.2</version>
        </dependency>
    </dependencies>

    <properties>
        <java.version>1.8</java.version>
        <elasticsearch.version>5.5.0</elasticsearch.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>spring-releases</id>
            <url>https://repo.spring.io/libs-release</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>spring-releases</id>
            <url>https://repo.spring.io/libs-release</url>
        </pluginRepository>
    </pluginRepositories>
</project>
```
 3. Try to instantiate a TransportClient object like this:
```
Settings settings = Settings
    .builder()
    .build();

TransportClient client = new PreBuiltTransportClient(settings)
    .addTransportAddress(new InetSocketTransportAddress(
        InetAddress.getByName("localhost"), 9300
    ));
```
**Provide logs (if relevant)**:
```
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.plugins.NetworkPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_131]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_131]
	... 56 common frames omitted
```

**Comment by cbuescher** [comment]
The class that is missing is in the `elasticsearch-5.5.0.jar` that is available on Maven Central (I just downloaded it there and checked). So if this class is missing from your applications classpath, either the dependency wasn't resolved correctly or there is something wrong with the classpath setup (either in your IDE or however you start your application). 

Since Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions like this, I'd ask you to raise your question there.

**Comment by nitinsridhar** [comment]
Similar issue I'm getting here

**Comment by hcxin** [comment]
Hit the same issue ,have resolved it after checking my classpath. you can check if the elasticsearch-5.5.0.jar in your classpath.
