### ISSUE TITLE
[CI] NioSocketChannelTests#testConnectFails failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#25763]
Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/1299/consoleFull

Does not reproduce.

```
Suite: org.elasticsearch.transport.nio.channel.NioSocketChannelTests
  1> [2560-07-18T12:35:40,665][INFO ][o.e.t.n.c.NioSocketChannelTests] [testClose]: before test
  1> [2560-07-18T12:35:40,747][INFO ][o.e.t.n.c.NioSocketChannelTests] [testClose]: after test
  1> [2560-07-18T12:35:40,761][INFO ][o.e.t.n.c.NioSocketChannelTests] [testConnectFails]: before test
  1> [2560-07-18T12:35:40,829][INFO ][o.e.t.n.c.NioSocketChannelTests] [testConnectFails]: after test
  2> REPRODUCE WITH: gradle :test:framework:test -Dtests.seed=30F3C2E69EACE9C6 -Dtests.class=org.elasticsearch.transport.nio.channel.NioSocketChannelTests -Dtests.method="testConnectFails" -Dtests.security.manager=true -Dtests.locale=th-TH-u-nu-thai-x-lvariant-TH -Dtests.timezone=Asia/Thimphu
FAILURE 0.09s J1 | NioSocketChannelTests.testConnectFails <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: an instance of java.net.ConnectException
   >      but: <java.net.SocketException: Connection reset by peer> is a java.net.SocketException
   > 	at __randomizedtesting.SeedInfo.seed([30F3C2E69EACE9C6:BC89BACC588335B8]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-unix-compatibility/os/centos/test/framework/build/testrun/test/J1/temp/org.elasticsearch.transport.nio.channel.NioSocketChannelTests_30F3C2E69EACE9C6-001
   > 	at org.elasticsearch.transport.nio.channel.NioSocketChannelTests.testConnectFails(NioSocketChannelTests.java:69)
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=1720, maxMBSortInHeap=5.825794236367283, sim=RandomSimilarity(queryNorm=true): {}, locale=th-TH-u-nu-thai-x-lvariant-TH, timezone=Asia/Thimphu
  2> NOTE: Linux 3.10.0-514.10.2.el7.x86_64 amd64/Oracle Corporation 1.8.0_131 (64-bit)/cpus=4,threads=1,free=478454368,total=514850816
  2> NOTE: All tests run in this JVM: [TeardownSectionTests, SocketSelectorTests, MockSearchServiceTests, ElasticsearchAssertionsTests, ClientYamlTestSectionTests, NioClientTests, NioSocketChannelTests]
   > 	at java.lang.Thread.run(Thread.java:748)
  1> [2560-07-18T12:35:40,858][INFO ][o.e.t.n.c.NioSocketChannelTests] [testConnectSucceeds]: before test
  1> [2560-07-18T12:35:40,910][INFO ][o.e.t.n.c.NioSocketChannelTests] [testConnectSucceeds]: after test
Completed [12/41] on J1 in 0.50s, 3 tests, 1 failure <<< FAILURES!
```

**Comment by tbrooks8** [comment]
This (finicky) test has been been greatly modified in this commit c7a7c69b2bc1013a9b624052f24f63b37759b42d. With that change we do not use real sockets and should not encounter this failure again.
