### ISSUE TITLE
[CI] ClusterDisruptionIT.testAckedIndexing fails

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#25765]
Encountered another ack indexing failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/3580/consoleFull

Actual failure:

```
ClusterDisruptionIT.testAckedIndexing <<< FAILURES!
   > Throwable #1: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=7061, name=elasticsearch[node_t2][bulk][T#1], state=RUNNABLE, group=TGRP-ClusterDisruptionIT]
   > 	at __randomizedtesting.SeedInfo.seed([BD856C14EBA7C8B2:3744D8E7B7DA2EF9]:0)
   > Caused by: java.lang.AssertionError
   > 	at __randomizedtesting.SeedInfo.seed([BD856C14EBA7C8B2]:0)
   > 	at org.elasticsearch.index.seqno.GlobalCheckpointTracker.getReplicationGroup(GlobalCheckpointTracker.java:271)
   > 	at org.elasticsearch.index.seqno.SequenceNumbersService.getReplicationGroup(SequenceNumbersService.java:180)
   > 	at org.elasticsearch.index.shard.IndexShard.getReplicationGroup(IndexShard.java:1736)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.getReplicationGroup(TransportReplicationAction.java:1012)
   > 	at org.elasticsearch.action.support.replication.ReplicationOperation.checkActiveShardCount(ReplicationOperation.java:235)
   > 	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:96)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:338)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:282)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:927)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:924)
   > 	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:235)
   > 	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2091)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:936)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction.access$400(TransportReplicationAction.java:94)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:299)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:278)
   > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:265)
   > 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
   > 	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:650)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jasontedor** [comment]
Closed by fd5710195212534c260e2d496adee26e12f190f7 and #25822
