### ISSUE TITLE
TruncateTranslogIT#testCorruptTranslogTruncation() failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#25761]
Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian/1291/consoleFull

Reproduce line: `gradle :core:integTest -Dtests.seed=F5D0058DCDCC25AD -Dtests.class=org.elasticsearch.index.translog.TruncateTranslogIT -Dtests.method="testCorruptTranslogTruncation" -Dtests.security.manager=true -Dtests.locale=nl-BE -Dtests.timezone=America/Adak` (does not reproduce)

Failure:

```
FAILURE 1.65s J0 | TruncateTranslogIT.testCorruptTranslogTruncation <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: {
   >   "size" : {
   >     "total_in_bytes" : 197,
   >     "reused_in_bytes" : 0,
   >     "recovered_in_bytes" : 197,
   >     "percent" : "100.0%"
   >   },
   >   "files" : {
   >     "total" : 1,
   >     "reused" : 0,
   >     "recovered" : 1,
   >     "percent" : "100.0%"
   >   },
   >   "total_time_in_millis" : 2,
   >   "source_throttle_time_in_millis" : 0,
   >   "target_throttle_time_in_millis" : 0
   > }
   > Expected: <0>
   >      but: was <1>
   > 	at __randomizedtesting.SeedInfo.seed([F5D0058DCDCC25AD:49F51FDD21F64E05]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.index.translog.TruncateTranslogIT.testCorruptTranslogTruncation(TruncateTranslogIT.java:223)
   > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by martijnvg** [comment]
Other occurrences:
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=opensuse/1296/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+oracle-periodic/56/consoleFull
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/1296/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu/1296/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=sles/1294/console
