### ISSUE TITLE
Cryptic error message for pipeline aggregations based on combination of nested and reverse_nested aggs

### ISSUE THREAD

**Issue by kujon** [elastic/elasticsearch#25775]
ES version **2.4.1**:

Consider the following mapping:

```json
{
    "timestamp_source": {
        "type": "nested",
        "properties": {
            "my_timestamp_1": {
                "type": "date"
            },
            "my_timestamp_2": {
                "type": "date"
            }
        }
    },
    "quantity": {
        "type": "float"
    }
}
```

and the following document:

```json
{
    "timestamp_source": [
        {
            "my_timestamp_1": "2014-05-11T23:52:38+0000",
            "my_timestamp_2": "2015-05-11T23:52:38+0000"
        },
        {
            "my_timestamp_1": "2016-05-11T23:52:38+0000",
            "my_timestamp_2": "2017-05-11T23:52:38+0000"
        }
    ],
    "quantity": 42
}
```

I'm after bucketing the timestamps, summing the quantities and calculating the `avg_bucket`. However the following query fails w/ a cryptic error msg:

```bash
curl -XGET 'localhost:9200/my_index/_search?pretty&size=0' -d '
{
    "query": {
        "match_all": {}
    },
    "aggs": {
        "by_frequency": {
            "nested": {
                "path": "timestamp_source"
            },
            "aggs": {
                "by_frequency": {
                    "date_histogram": {
                        "field": "timestamp_source.my_timestamp_1",
                        "interval": "month",
                        "min_doc_count": 0
                    },
                    "aggs": {
                        "total": {
                            "reverse_nested": {},
                            "aggs": {
                                "total": {
                                    "sum": {
                                        "field": "quantity"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "monthly_average": {
            "avg_bucket": {
                "buckets_path": "by_frequency>by_frequency>total>total",
                "gap_policy": "insert_zeros"
            }
        }
    }
}
'

{
  "error" : {
    "root_cause" : [ ],
    "type" : "reduce_search_phase_exception",
    "reason" : "[reduce] ",
    "phase" : "fetch",
    "grouped" : true,
    "failed_shards" : [ ],
    "caused_by" : {
      "type" : "class_cast_exception",
      "reason" : null
    }
  },
  "status" : 503
}
```

**Actual behaviour**

The error message isn't descriptive enough.

**Expected behaviour**

The 'reason' field explains in more detail the reasons behind failure.

Alternatively (if this query is valid), the query succeeds.

**Comment by colings86** [comment]
I agree that the error message isn't very helpful here, my guess is that you hit a bug with the validation of the buckets path. There will be a stack trace in the server logs relating to that ClassCastException, could you paste it here so we can fix the bug in the validation?

Although there is a bug in the validation your request should fail because the `*_bucket` aggregations need to be direct-siblings to the multi-bucket aggregations they are working on, if you move your `monthly_average` aggregation so its a sub-aggregation to your `by_frequency` `nested` aggregations an a sibling to the `by_frequency` `date_histogram` aggregation, and change the `buckets+path` to `by_frequency>total>total` I think it might work.

**Comment by kujon** [comment]
The stack trace is:
```
[2017-07-18 14:33:48,542][WARN ][rest.suppressed ] path: /some_crazy_schema_v4/_search, params: {pretty=, size=0, index=some_crazy_schema_v4}
Failed to execute phase [fetch], [reduce]
at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction$2.onFailure(SearchQueryThenFetchAsyncAction.java:146)
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException
[2017-07-18 14:38:25,821][DEBUG][action.search ] [In-Betweener] failed to reduce search
Failed to execute phase [fetch], [reduce]
at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction$2.onFailure(SearchQueryThenFetchAsyncAction.java:146)
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException
```

**Comment by kujon** [comment]
Also thanks a lot for your suggestion, it worked!

**Comment by colings86** [comment]
So having dug into this a bit, the error was exactly because of the problem I outlined with your request but it isn't particularly helpful to the end user. I am working on a fix to make this validation happen earlier and give back a more descriptive message for the next person who makes the same kind of mistake

thanks @kujon for raising this
