### ISSUE TITLE
After upgrade .deb package on Ubuntu, es tries to write log to wrong dir

### ISSUE THREAD

**Issue by LeeDr** [elastic/elasticsearch#25782]
**Elasticsearch version**: 6.0.0-Beta1-SNAPSHOT

**Plugins installed**: [x-pack]

**JVM version** (`java -version`): openjdk version "1.8.0_111"

**OS version** (`uname -a` if on a Unix-like system): Linux packer-virtualbox-iso-1494168020 4.4.0-75-generic #96~14.04.1-Ubuntu SMP Thu Apr 20 11:06:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
After upgrading Elasticsearch from 5.6.0-SNAPSHOT to the latest 6.0.0-beta1-SNAPSHOT I get an error in the log that it can't write the access log.  5.6.0 was logging to `/var/log/elasticsearch/` but the error message indicates 6.0 is trying to write to `/usr/share/elasticsearch/logs`

**Steps to reproduce**:

1. On Ubuntu wget http://snapshots.elastic.co/downloads/elasticsearch/elasticsearch-5.6.0-SNAPSHOT.deb
2. `dpkg -i elasticsearch-5.6.0-SNAPSHOT.deb`
3. `service elasticsearch start`
4. I also installed 3 beats, logstash, kibana, and x-pack, but I don't think any of that matters
5. I modified elasticsearch.yml with the settings below, but they're mostly for x-pack and shouldn't affect the logging location
6. wget http://snapshots.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0-beta1-SNAPSHOT.deb
7. `dpkg -i elasticsearch-6.0.0-beta1-SNAPSHOT.deb`
8. `service elasticsearch restart`
9. See the error below

```
root@packer-virtualbox-iso-1494168020:/vagrant/qa# service elasticsearch restart
 * Starting Elasticsearch Server
2017-07-19 00:41:55,484 main ERROR Unable to create file /usr/share/elasticsearch/logs/elasticsearch_access.log java.io.IOException: Could not create directory /usr/share/elasticsearch/logs
```

My elasticsearch.yml modifications;
```
xpack.ssl.certificate: ./x-pack/elasticsearch.crt
xpack.ssl.key: ./x-pack/elasticsearch.key
xpack.ssl.certificate_authorities: [./x-pack/ca.crt]
xpack.security.http.ssl.enabled: true
network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 0
xpack.notification.email.account:
  gmail_account:
    profile: gmail
    smtp:
      auth: true
      starttls.enable: true
      host: smtp.mailgun.org
      port: 587
      user: infra@elastic.co
      password: **********
```

**Provide logs (if relevant)**:  More complete log output;
```
root@packer-virtualbox-iso-1494168020:/vagrant/qa# service elasticsearch restart
 * Starting Elasticsearch Server                                                                                                                                                                        2017-07-19 00:41:55,484 main ERROR Unable to create file /usr/share/elasticsearch/logs/elasticsearch_access.log java.io.IOException: Could not create directory /usr/share/elasticsearch/logs
        at org.apache.logging.log4j.core.util.FileUtils.mkdir(FileUtils.java:119)
        at org.apache.logging.log4j.core.util.FileUtils.makeParentDirs(FileUtils.java:136)
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:573)
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:554)
        at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:112)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:114)
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:155)
        at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:131)
        at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:60)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:952)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:892)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:508)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:232)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:261)
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:164)
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:120)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:289)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:74)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
        at org.elasticsearch.cli.Command.main(Command.java:88)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)
```

**Comment by jasontedor** [comment]
This should be an X-Pack issue, not an open source Elasticsearch issue.

**Comment by sandstrom** [comment]
I have the same issue, and I'm not using X-pack.
