### ISSUE TITLE
[CI] search/140_pre_filter_search_shards/pre_filter_shard_size with shards that have no hit fails

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#25832]
This test failed once today. This failure is different compared to previous ones as this one comes from an execution against a single node.

It doesn't reproduce for me.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=fedora/1325

```
> Throwable #1: java.lang.AssertionError: Failure at [search/140_pre_filter_search_shards:119]: _shards.successful didn't match expected value:
   >             _shards.successful: expected [3] but was [2]
   > 	at __randomizedtesting.SeedInfo.seed([B4ACA90E4E588704:3CF896D4E0A4EAFC]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:348)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:328)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.lang.AssertionError: _shards.successful didn't match expected value:
   >             _shards.successful: expected [3] but was [2]
   > 	at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:87)
   > 	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:344)
   > 	... 37 more
```

Here is the response that triggers the failure:

```
  1>   "stash" : {
  1>     "body" : {
  1>       "took" : 0,
  1>       "timed_out" : false,
  1>       "_shards" : {
  1>         "total" : 3,
  1>         "successful" : 2,
  1>         "skipped" : 1,
  1>         "failed" : 0
  1>       },
  1>       "hits" : {
  1>         "total" : 0,
  1>         "max_score" : 0.0,
  1>         "hits" : [ ]
  1>       }
  1>     }
  1>   }
  1> }]
```

**Comment by javanna** [comment]
@s1monw I assigned you because this is related to your recent changes on search execution. Can you have a look please?

**Comment by s1monw** [comment]
fixed by https://github.com/elastic/elasticsearch/pull/25818
