### ISSUE TITLE
Snapshot serialization test fails when master is bumped to 7.0

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#25870]
```
2> REPRODUCE WITH: gradle :core:test -Dtests.seed=D78936E98B6752B8 -Dtests.class=org.elasticsearch.cluster.serialization.ClusterSerializationTests -Dtests.method="testSnapshotDeletionsInProgressSerialization" -Dtests.security.manager=true -Dtests.locale=ja -Dtests.timezone=Atlantic/Jan_Mayen
FAILURE 0.05s J3 | ClusterSerializationTests.testSnapshotDeletionsInProgressSerialization <<< FAILURES!
   > Throwable #1: java.lang.AssertionError:
   > Expected: null
   >      but: was <SnapshotDeletionsInProgress[snap1]>
   >    at __randomizedtesting.SeedInfo.seed([D78936E98B6752B8:172D0F0A24A4B9]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.cluster.serialization.ClusterSerializationTests.testSnapshotDeletionsInProgressSerialization(ClusterSerializationTests.java:150)
   >    at java.lang.Thread.run(Thread.java:745)```

**Comment by ywelsch** [comment]
I've pushed 7e08753bd2
