### ISSUE TITLE
IndexingIT fails on master after version bump to 7.0

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#25873]
```
  2> REPRODUCE WITH: gradle :qa:mixed-cluster:v6.1.0-SNAPSHOT#mixedClusterTestRunner -Dtests.seed=D8650EF5DF79185C -Dtests.class=org.elasticsearch.backwards.IndexingIT -Dtests.method="testSeqNoCheckpoints" -Dtests.security.manager=true -Dtests.locale=ar-MA -Dtests.timezone=Asia/Jayapura
FAILURE 11.7s | IndexingIT.testSeqNoCheckpoints <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: max_seq no on Node{id='4QdNo4euThOdeBy6Q7dpvA', nodeName='node-0', version=6.1.0} is wrong
   > Expected: <-1L>
   >      but: was <2L>
   >    at __randomizedtesting.SeedInfo.seed([D8650EF5DF79185C:E909E43E15E69D00]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:297)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:722)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:696)
   >    at org.elasticsearch.backwards.IndexingIT.assertSeqNoOnShards(IndexingIT.java:278)
   >    at org.elasticsearch.backwards.IndexingIT.testSeqNoCheckpoints(IndexingIT.java:217)
   >    at java.lang.Thread.run(Thread.java:745)
   >    Suppressed: java.lang.AssertionError: max_seq no on Node{id='4QdNo4euThOdeBy6Q7dpvA', nodeName='node-0', version=6.1.0} is wrong
   > Expected: <-1L>
   >      but: was <2L>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:297)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
   >            ... 40 more
   >    Suppressed: java.lang.AssertionError: max_seq no on Node{id='4QdNo4euThOdeBy6Q7dpvA', nodeName='node-0', version=6.1.0} is wrong
   > Expected: <-1L>
   >      but: was <2L>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:297)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
   >            ... 40 more
   >    Suppressed: java.lang.AssertionError: max_seq no on Node{id='4QdNo4euThOdeBy6Q7dpvA', nodeName='node-0', version=6.1.0} is wrong
   > Expected: <-1L>
   >      but: was <2L>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:297)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
   >            ... 40 more
   >    Suppressed: java.lang.AssertionError: max_seq no on Node{id='4QdNo4euThOdeBy6Q7dpvA', nodeName='node-0', version=6.1.0} is wrong
   > Expected: <-1L>
   >      but: was <2L>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:297)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
   >            ... 40 more
   >    Suppressed: java.lang.AssertionError: max_seq no on Node{id='4QdNo4euThOdeBy6Q7dpvA', nodeName='node-0', version=6.1.0} is wrong
   > Expected: <-1L>
   >      but: was <2L>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:297)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
   >            ... 40 more
   >    Suppressed: java.lang.AssertionError: max_seq no on Node{id='4QdNo4euThOdeBy6Q7dpvA', nodeName='node-0', version=6.1.0} is wrong
   > Expected: <-1L>
   >      but: was <2L>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:297)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
   >            ... 40 more
   >    Suppressed: java.lang.AssertionError: max_seq no on Node{id='4QdNo4euThOdeBy6Q7dpvA', nodeName='node-0', version=6.1.0} is wrong
   > Expected: <-1L>
   >      but: was <2L>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:297)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
   >            ... 40 more
   >    Suppressed: java.lang.AssertionError: max_seq no on Node{id='4QdNo4euThOdeBy6Q7dpvA', nodeName='node-0', version=6.1.0} is wrong
   > Expected: <-1L>
   >      but: was <2L>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:297)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
   >            ... 40 more
   >    Suppressed: java.lang.AssertionError: max_seq no on Node{id='4QdNo4euThOdeBy6Q7dpvA', nodeName='node-0', version=6.1.0} is wrong
   > Expected: <-1L>
   >      but: was <2L>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:297)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
   >            ... 40 more
   >    Suppressed: java.lang.AssertionError: max_seq no on Node{id='4QdNo4euThOdeBy6Q7dpvA', nodeName='node-0', version=6.1.0} is wrong
   > Expected: <-1L>
   >      but: was <2L>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:297)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
   >            ... 40 more
   >    Suppressed: java.lang.AssertionError: max_seq no on Node{id='4QdNo4euThOdeBy6Q7dpvA', nodeName='node-0', version=6.1.0} is wrong
   > Expected: <-1L>
   >      but: was <2L>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:297)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
   >            ... 40 more
   >    Suppressed: java.lang.AssertionError: max_seq no on Node{id='4QdNo4euThOdeBy6Q7dpvA', nodeName='node-0', version=6.1.0} is wrong
   > Expected: <-1L>
   >      but: was <2L>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:297)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
   >            ... 40 more
   >    Suppressed: java.lang.AssertionError: max_seq no on Node{id='4QdNo4euThOdeBy6Q7dpvA', nodeName='node-0', version=6.1.0} is wrong
   > Expected: <-1L>
   >      but: was <2L>
   >            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >            at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:297)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
   >            ... 40 more
```

**Comment by s1monw** [comment]
fixed in https://github.com/elastic/elasticsearch/pull/25876
