### ISSUE TITLE
Tcp and nio transport test failures on version bump to 7.0

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#25893]
Two test failures, but they are the exact same:

```
  2> REPRODUCE WITH: gradle :test:framework:test -Dtests.seed=15A33AAAA8383DC4 -Dtests.class=org.elasticsearch.transport.nio.SimpleNioTransportTests -Dtests.method="testTransportStatsWithException" -Dtests.security.manager=true -Dtests.locale=hr -Dtests.timezone=Asia/Nicosia
FAILURE 0.06s J0 | SimpleNioTransportTests.testTransportStatsWithException <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<189> but was:<187>
   >    at __randomizedtesting.SeedInfo.seed([15A33AAAA8383DC4:D9231B7D2322A8CF]:0)
   >    at org.elasticsearch.transport.AbstractSimpleTransportTestCase.testTransportStatsWithException(AbstractSimpleTransportTestCase.java:2425)
   >    at java.lang.Thread.run(Thread.java:745)
```

```
  2> REPRODUCE WITH: gradle :test:framework:test -Dtests.seed=15A33AAAA8383DC4 -Dtests.class=org.elasticsearch.transport.MockTcpTransportTests -Dtests.method="testTransportStatsWithException" -Dtests.security.manager=true -Dtests.locale=lv-LV -Dtests.timezone=America/Maceio
FAILURE 0.02s J3 | MockTcpTransportTests.testTransportStatsWithException <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<189> but was:<187>
   >    at __randomizedtesting.SeedInfo.seed([15A33AAAA8383DC4:D9231B7D2322A8CF]:0)
   >    at org.elasticsearch.transport.AbstractSimpleTransportTestCase.testTransportStatsWithException(AbstractSimpleTransportTestCase.java:2425)
   >    at java.lang.Thread.run(Thread.java:745)
```

**Comment by s1monw** [comment]
this will be fixed in https://github.com/elastic/elasticsearch/pull/25876
