### ISSUE TITLE
Receiving "client.transport.NoNodeAvailableException: None of the configured nodes are available" from Client application Post elastic Search Upgrade  to 5.5.1

### ISSUE THREAD

**Issue by diwakar222** [elastic/elasticsearch#25914]
i have java Application using elastic search client (**org.elasticsearch.client:transport:5.4.1**) and was able to save data to elastic search. 

Recently the infrastructure team **upgraded the elastic search to 5.5.1** , After this upgrade my application is no longer able to save data to elastic search. I have also upgraded my client jar to **org.elasticsearch.client:transport:5.5.1** but is not helping and i am seeing following exception

Wed Jul 26 10:42:10 MDT 2017 ERROR [APP: XYZ-service]com.comcast.activation.elasticsearch.connector.ElasticSearchConnector:indexInsertDocuments - General Exception while inserting elastic search : ERROR_DETAILS: org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{127.0.0.54}{127.0.0.54:9300}]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56)
	at com.comcast.activation.elasticsearch.connector.ElasticSearchConnector.indexInsertDocuments(ElasticSearchConnector.java:106)

could you pls provide me as to why this issue is happening ?

**Comment by rjernst** [comment]
Please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports.
