### ISSUE TITLE
NoClassDefFoundError-org/elasticsearch/index/reindex/ReindexAction

### ISSUE THREAD

**Issue by falltodis** [elastic/elasticsearch#25927]
**Elasticsearch version**: 5.5.0

**Plugins installed**: default

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): mac
**dependency**
![image](https://user-images.githubusercontent.com/7006864/28660965-ac49cbfa-72e7-11e7-9e34-6c55e8f40546.png)

**Provide logs (if relevant)**:
The default setting and got a exception below

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/index/reindex/ReindexAction
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:419)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:102)
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:101)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:126)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:268)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:130)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:116)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:106)
	at com.fourthDimension.faceRecognition.faceRecognition.FaceRecognitionApplication.detectFace(FaceRecognitionApplication.java:46)
	at com.fourthDimension.faceRecognition.faceRecognition.FaceRecognitionApplication.main(FaceRecognitionApplication.java:86)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.index.reindex.ReindexAction
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

**Comment by danielmitterdorfer** [comment]
Hi @falltodis, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. Thank you!

I've checked the [transport client's POM](http://central.maven.org/maven2/org/elasticsearch/client/transport/5.5.0/transport-5.5.0.pom) in Maven central and it looks fine. `org.elasticsearch.index.reindex.ReindexAction` is contained in Elasticsearch core which should be pulled in as a transitive dependency. So you should check your dependency graph.

**Comment by falltodis** [comment]
Sorry for reply this issue.  I searched for class `ReindexAction` but  not found.
![image](https://user-images.githubusercontent.com/7006864/28707762-30c585bc-73ac-11e7-8f6e-d0ac8c05062c.png)
This [documnet](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/_maven_repository.html) says the only pom I shoud add is transport client's POM which I have added it.
thanks

**Comment by danielmitterdorfer** [comment]
This is correct. If you have a look at the POM that I've linked to in my previous comment you will see that Elasticsearch core is a transitive dependency of the transport client. Hence, it looks to me that your dependency resolution is broken.

You can try the following:

```bash
mkdir example
cd example
cat >build.gradle <<EOL
plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    compile "org.elasticsearch.client:transport:5.5.0"
}
EOL
gradle dependencies
```

You will see the dependency tree that Gradle resolves. For me this produces the following output (only showing the compile dependencies here for brevity):

```
compile - Dependencies for source set 'main' (deprecated, use 'implementation ' instead).
\--- org.elasticsearch.client:transport:5.5.0
     +--- org.elasticsearch:elasticsearch:5.5.0
     |    +--- org.apache.lucene:lucene-core:6.6.0
     |    +--- org.apache.lucene:lucene-analyzers-common:6.6.0
     |    +--- org.apache.lucene:lucene-backward-codecs:6.6.0
     |    +--- org.apache.lucene:lucene-grouping:6.6.0
     |    +--- org.apache.lucene:lucene-highlighter:6.6.0
     |    +--- org.apache.lucene:lucene-join:6.6.0
     |    +--- org.apache.lucene:lucene-memory:6.6.0
     |    +--- org.apache.lucene:lucene-misc:6.6.0
     |    +--- org.apache.lucene:lucene-queries:6.6.0
     |    +--- org.apache.lucene:lucene-queryparser:6.6.0
     |    +--- org.apache.lucene:lucene-sandbox:6.6.0
     |    +--- org.apache.lucene:lucene-spatial:6.6.0
     |    +--- org.apache.lucene:lucene-spatial-extras:6.6.0
     |    +--- org.apache.lucene:lucene-spatial3d:6.6.0
     |    +--- org.apache.lucene:lucene-suggest:6.6.0
     |    +--- org.elasticsearch:securesm:1.1
     |    +--- net.sf.jopt-simple:jopt-simple:5.0.2
     |    +--- com.carrotsearch:hppc:0.7.1
     |    +--- joda-time:joda-time:2.9.5
     |    +--- org.yaml:snakeyaml:1.15
     |    +--- com.fasterxml.jackson.core:jackson-core:2.8.6
     |    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-smile:2.8.6
     |    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.8.6
     |    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.8.6
     |    +--- com.tdunning:t-digest:3.0
     |    +--- org.hdrhistogram:HdrHistogram:2.1.9
     |    +--- org.apache.logging.log4j:log4j-api:2.8.2
     |    \--- org.elasticsearch:jna:4.4.0
     +--- org.elasticsearch.plugin:transport-netty3-client:5.5.0
     |    \--- io.netty:netty:3.10.6.Final
     +--- org.elasticsearch.plugin:transport-netty4-client:5.5.0
     |    +--- io.netty:netty-buffer:4.1.11.Final
     |    +--- io.netty:netty-codec:4.1.11.Final
     |    +--- io.netty:netty-codec-http:4.1.11.Final
     |    +--- io.netty:netty-common:4.1.11.Final
     |    +--- io.netty:netty-handler:4.1.11.Final
     |    +--- io.netty:netty-resolver:4.1.11.Final
     |    \--- io.netty:netty-transport:4.1.11.Final
     +--- org.elasticsearch.plugin:reindex-client:5.5.0
     |    \--- org.elasticsearch.client:rest:5.5.0
     |         +--- org.apache.httpcomponents:httpclient:4.5.2
     |         +--- org.apache.httpcomponents:httpcore:4.4.5
     |         +--- org.apache.httpcomponents:httpasyncclient:4.1.2
     |         +--- org.apache.httpcomponents:httpcore-nio:4.4.5
     |         +--- commons-codec:commons-codec:1.10
     |         \--- commons-logging:commons-logging:1.1.3
     +--- org.elasticsearch.plugin:lang-mustache-client:5.5.0
     |    \--- com.github.spullara.mustache.java:compiler:0.9.3
     +--- org.elasticsearch.plugin:percolator-client:5.5.0
     \--- org.elasticsearch.plugin:parent-join-client:5.5.0
```

It seems that transitive dependencies are not resolved correctly in your scenario and you should investigate why.

**Comment by falltodis** [comment]
Thanks for your reply~ I found the dependencies`org.elasticsearch:elasticsearch 5.5.0` would be redirect to `5.4.1` when add the repo `repo.spring.io`

**Comment by xeraa** [comment]
IMO this is because of a dependency from Spring Boot Autoconfig to Spring Data. If you are using Spring Boot 1.5 you will get the currently stable version of Spring Data (codename Ingalls), which has a hard dependency on Elasticsearch 2.4. You need to use the current development version of Spring Data (codename Kay) to get support for Elasticsearch 5.x. This version is included in the development version of Spring Boot 2 already.

You can try it out with the following *build.gradle*  when you switch between `springBootVersion = '2.0.0.M3'` and `springBootVersion = '1.5.6.RELEASE'` and then check dependencies with `gradle dependencies` (maybe with `gradle dependencies | grep elasticsearch` to see the relevant parts).

```
buildscript {
	ext {
		springBootVersion = '2.0.0.M3'
	}
	repositories {
maven {
        url 'https://repo.spring.io/libs-milestone'
    }
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'

version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
maven {
        url 'https://repo.spring.io/libs-milestone'
    }
}


dependencies {
	compile('org.apache.logging.log4j:log4j-core:2.8.2')
	compile('org.springframework.boot:spring-boot-starter:${springBootVersion}')
	compile('org.springframework.boot:spring-boot-starter-web:${springBootVersion}')
	compile('org.elasticsearch.client:transport:5.5.0')
}
```
