### ISSUE TITLE
Skip hidden files like .DS_Store in plugins directory

### ISSUE THREAD

**Issue by jochenkressin** [elastic/elasticsearch#26000]
This seems to be a re-occurrence of #12433.

Elasticsearch version: 5.5.0 and 5.5.1
Operating System: Mac OS X 10.11.5

If there is any hidden file in the elasticsearch/plugins directory, like .DS_Store on Mac OS X, Elasticsearch interprets this file as a plugin directory and fails to start:

```
[2017-08-01T17:04:08,486][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: org.elasticsearch.bootstrap.BootstrapException: java.nio.file.FileSystemException: /xx/xx/elasticsearch-5.5.0/plugins/.DS_Store/plugin-descriptor.properties: Not a directory
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.5.0.jar:5.5.0]
Caused by: org.elasticsearch.bootstrap.BootstrapException: java.nio.file.FileSystemException: /xx/xx/elasticsearch-5.5.0/plugins/.DS_Store/plugin-descriptor.properties: Not a directory
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:169) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.0.jar:5.5.0]
	... 6 more
Caused by: java.nio.file.FileSystemException: /xx/xx/elasticsearch-5.5.0/plugins/.DS_Store/plugin-descriptor.properties: Not a directory
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[?:1.8.0_31]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_31]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_31]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_31]
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_31]
	at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_31]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_31]
	at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_31]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:114) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:80) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:167) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.0.jar:5.5.0]
	... 6 more
```

The same happens if you try to install a plugin and a hidden file is in the elasticsearch/plugins directory:

```
Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [.DS_Store]. Was the plugin built before 2.0?
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:334)
	at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:518)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:500)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:543)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:217)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:201)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
Caused by: java.nio.file.FileSystemException: /xx/xx/elasticsearch-5.5.0/plugins/.DS_Store/plugin-descriptor.properties: Not a directory
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:114)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:331)
	... 11 more
```

**Comment by dadoonet** [comment]
This leniency has been removed on purpose. See #23982.
