### ISSUE TITLE
[CI] Node startup times exceeding 30 second integTestCluster#wait window.

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#26063]
Seen a good number of build failures that have failed due to the `integTestCluster#wait` task timing out. Looking at the stack traces from jstack, it seems that the process is usually making progress toward node start up. In some cases, it looks like the wait check just barely misses the boat, as the thread dump shows that the node is already started (6.x):

```
|    "elasticsearch[keepAlive/6.1.0]" #11 prio=5 os_prio=31 tid=0x00007fd3534f2000 nid=0x7903 waiting on condition [0x0000700002b14000]
|       java.lang.Thread.State: WAITING (parking)
|    	at sun.misc.Unsafe.park(Native Method)
|    	- parking to wait for  <0x00000007aac29550> (a java.util.concurrent.CountDownLatch$Sync)
|    	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
|    	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
|    	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
|    	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
|    	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
|    	at org.elasticsearch.bootstrap.Bootstrap$1.run(Bootstrap.java:83)
|    	at java.lang.Thread.run(Thread.java:748)
```

On this run we have a node still waiting on finding a master (6.0, master branches): 
```
|    "main" #1 prio=5 os_prio=31 tid=0x00007f9f43805800 nid=0x1703 waiting on condition [0x0000700000219000]
|       java.lang.Thread.State: WAITING (parking)
|    	at sun.misc.Unsafe.park(Native Method)
|    	- parking to wait for  <0x00000007a0525f40> (a java.util.concurrent.CountDownLatch$Sync)
|    	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
|    	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
|    	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
|    	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
|    	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
|    	at org.elasticsearch.node.Node.start(Node.java:643)
|    	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:261)
|    	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:331)
|    	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121)
|    	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112)
|    	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:69)
|    	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
|    	at org.elasticsearch.cli.Command.main(Command.java:88)
|    	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
|    	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85)
```

It seems that this problem is most commonly occurring on the darwin-compatibility runs.

**Comment by clintongormley** [comment]
Could this be because there is there is no entry in ´/etc/hosts` for localhost?  That causes a delay on osx

**Comment by jasontedor** [comment]
There was a period of time when the jobs on macOS were failing with this error frequently, but I have not seen that happen in awhile. I think that we can close this one.
