### ISSUE TITLE
Java Heap Space

### ISSUE THREAD

**Issue by samuel-miller** [elastic/elasticsearch#26087]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 5.5.0, Build: 260387d/2017-06-30T23:16:05.735Z, 
**Plugins installed**: []
s3-repository
ec2-discovery
**JVM version** (`java -version`):
JVM: 1.8.0_144

-Xms16g
-Xmx16g
.
.
.
**OS version** (`uname -a` if on a Unix-like system):
3.13.0-119-generic #166-Ubuntu SMP Wed May 3 12:18:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Install & run Elasticsearch, install s3-repository, ingest 280G of (json log) data
 2. set up a cluster of 5 nodes.
 3. On any node execute: `curl -XPUT 'localhost:9200/_snapshot/s3_repository?pretty' -H 'Content-Type: application/json' -d'
{
  "type": "s3",
  "settings": {
    "access_key":"<REDACTED>",
    "secret_key":"<REDACTED>",
    "bucket": "<redacted>-logs",
    "base_path": "/elk/20170807",
    "region": "us-west",
    "endpoint":"s3-us-west-2.amazonaws.com"
    }
}
'`

**Provide logs (if relevant)**:
[2017-08-07T20:56:20,192][INFO ][o.e.m.j.JvmGcMonitorService] [node-1] [gc][16] overhead, spent [323ms] collecting in the last [1s]
[2017-08-07T20:56:45,212][INFO ][o.e.m.j.JvmGcMonitorService] [node-1] [gc][41] overhead, spent [313ms] collecting in the last [1s]
[2017-08-07T20:57:18,222][INFO ][o.e.m.j.JvmGcMonitorService] [node-1] [gc][74] overhead, spent [328ms] collecting in the last [1s]
[2017-08-07T20:57:49,232][INFO ][o.e.m.j.JvmGcMonitorService] [node-1] [gc][105] overhead, spent [290ms] collecting in the last [1s]
[2017-08-07T20:58:07,932][ERROR][o.e.t.n.Netty4Utils      ] fatal error on the network layer
        at org.elasticsearch.transport.netty4.Netty4Utils.maybeDie(Netty4Utils.java:179)
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.exceptionCaught(Netty4MessageChannelHandler.java:83)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
        at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:850)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:364)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:748)
[2017-08-07T20:58:07,936][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-1] fatal error in thread [Thread-5], exiting
java.lang.OutOfMemoryError: Java heap space
        at org.elasticsearch.repositories.s3.S3OutputStream.<init>(S3OutputStream.java:63) ~[?:?]
        at org.elasticsearch.repositories.s3.DefaultS3OutputStream.<init>(DefaultS3OutputStream.java:76) ~[?:?]
        at org.elasticsearch.repositories.s3.S3BlobContainer.createOutput(S3BlobContainer.java:120) ~[?:?]
        at org.elasticsearch.repositories.s3.S3BlobContainer.writeBlob(S3BlobContainer.java:99) ~[?:?]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.verify(BlobStoreRepository.java:1018) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.repositories.VerifyNodeRepositoryAction.doVerify(VerifyNodeRepositoryAction.java:117) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.repositories.VerifyNodeRepositoryAction.access$300(VerifyNodeRepositoryAction.java:50) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.repositories.VerifyNodeRepositoryAction$VerifyNodeRepositoryRequestHandler.messageReceived(VerifyNodeRepositoryAction.java:153) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.repositories.VerifyNodeRepositoryAction$VerifyNodeRepositoryRequestHandler.messageReceived(VerifyNodeRepositoryAction.java:148) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1544) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:110) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1501) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1385) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]

**Comment by samuel-miller** [comment]
just replicated without any additional hosts, the host has 60+GB of memory, and yet I'm apparently running out of heap space

**Comment by cbuescher** [comment]
Hi, are you doing any other operation on the cluster prior to starting snapshoting? From the first loglines it looks there is some GC going on already, any idea what might be going on at that point? Also please explain what you mean by "60+GB of memory", from the above info it looks like your JVM gets 16GB (which I think should be enough).

**Comment by samuel-miller** [comment]
The underlying host has 60+ GB of memory; if the answer is bumping the JVM settings to something higher than 16GB, that isn't a problem. However, I've read that diminishing returns severely impact anything over 32GB, so I don't really want to do that, unless it will fix the problem.

Yes, when I start ES on the host, ES began by initiating 150+ GC threads. I was using this host to also run Logstash, Kibana and Apache for an ELK stack. I've disabled all of my Beats log shippers for the time being, because being unable to snapshot the indices prevents this from being ready for production. Without the input the host cpu/memory metrics look very underutilized, but even now (with an extremely low cpu/io utilization), running the curl snapshot command kills the process on this host.  

If there is another more reliable way to take snapshots to be stored on S3, I'd be interested in anything to get this cluster to be stable.

**Comment by cbuescher** [comment]
Hi @samuel-miller, I talked to somebody more familiar with the S3 repository and it looks like your nodes were already  pretty close to the OOM (not sure why) and the S3 just triggers the OOM.
The error happened in the repository verification step, which is just a small write on the repository, so this alone shouldn't cause it. 
So the interesting question is how the heap situation looks like before trying to do the snapshot. Given that you seem to supply a reasonable amount of heap it would be interesting to see where all that goes. However, an analysis of that might go beyond what we usually provide here on Github, as we try to limit this to bug reports and feature request. We have a [forum](https://discuss.elastic.co) that would be better suited for this kind of discussion. Would you mind me closing this issue and reopening a thread in the Forums once you can provide more information about heap usage etc?

**Comment by samuel-miller** [comment]
Christoph,

Please go ahead and close the issue, I believe the root cause was that the
Elasticsearch cluster was underscaled for the volume of data coming in, and
we had no buffer to regulate it. Since adding such a buffer (in the form of
a kafka cluster) the problem appears to have been mitigated. Thank you.

Samuel Miller

On Tue, Aug 15, 2017 at 5:32 AM, Christoph Büscher <notifications@github.com

**Comment by cbuescher** [comment]
@samuel-miller thanks, and don't hesitate to opene another issue in the discuss forums if you run into other problems, we welcome discussions about scaling/memory consumption etc... there and try to help.
