### ISSUE TITLE
[CI] DiscoveryWithServiceDisruptionsIT#testAckedIndexing fails with IndexNotFoundException

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#26108]
Did not reproduce for me in 50 runs.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+aggressive-opts/46/console

@bleskes is this up you're alley?

```
gradle :core:integTest \
  -Dtests.seed=FEE8D9CDC3880926 \
  -Dtests.class=org.elasticsearch.discovery.DiscoveryWithServiceDisruptionsIT \
  -Dtests.method="testAckedIndexing" \
  -Dtests.security.manager=true \
  -Dtests.jvm.argline="-XX:+AggressiveOpts" \
  -Dtests.locale=ar-LB \
  -Dtests.timezone=America/Guyana
```

```
NoShardAvailableActionException[No shard available for [get [test][type][3]: routing [null]]]; nested: RemoteTransportException[[node_t1][127.0.0.1:30101][indices:data/read/get[s]]]; nested: IndexNotFoundException[no such index];
	at __randomizedtesting.SeedInfo.seed([FEE8D9CDC3880926:74296D3E9FF5EF6D]:0)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.perform(TransportSingleShardAction.java:209)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.onFailure(TransportSingleShardAction.java:196)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.access$1300(TransportSingleShardAction.java:123)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleException(TransportSingleShardAction.java:252)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1067)
	at org.elasticsearch.transport.TcpTransport.lambda$handleException$16(TcpTransport.java:1451)
	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:110)
	at org.elasticsearch.transport.TcpTransport.handleException(TcpTransport.java:1449)
	at org.elasticsearch.transport.TcpTransport.handlerResponseError(TcpTransport.java:1441)
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1385)
	at org.elasticsearch.transport.MockTcpTransport.readMessage(MockTcpTransport.java:173)
	at org.elasticsearch.transport.MockTcpTransport.access$1000(MockTcpTransport.java:70)
	at org.elasticsearch.transport.MockTcpTransport$MockChannel$1.lambda$doRun$0(MockTcpTransport.java:346)
	at org.elasticsearch.common.util.CancellableThreads.executeIO(CancellableThreads.java:105)
	at org.elasticsearch.transport.MockTcpTransport$MockChannel$1.doRun(MockTcpTransport.java:346)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: RemoteTransportException[[node_t1][127.0.0.1:30101][indices:data/read/get[s]]]; nested: IndexNotFoundException[no such index];
Caused by: [test/KP3jQJReT0iqTe8ZgrcHqw] IndexNotFoundException[no such index]
	at org.elasticsearch.indices.IndicesService.indexServiceSafe(IndicesService.java:382)
	at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:88)
	at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:44)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:294)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:287)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1528)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bleskes** [comment]
This was opened long time ago and I dropped the ball on it. I don't think it makes sense to chase it now as many things have changed. Closing.
