### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT fielddata issues

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#26129]
could not reproduce, but CI is failing frequently on this.

link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/1046/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/3850/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=opensuse/1410/console

```
> There were test failures: 2 suites, 689 tests, 5 failures, 17 ignored (17 assumptions) [seed: E709E299BE7B9695]

REPRODUCE WITH: gradle :qa:mixed-cluster:v6.1.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=E709E299BE7B9695 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=search/110_field_collapsing/field collapsing, inner_hits and maxConcurrentGroupRequests}" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-IQ \
  -Dtests.timezone=Europe/Andorra

REPRODUCE WITH: gradle :qa:mixed-cluster:v6.1.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=E709E299BE7B9695 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=search/90_search_after/search with search_after parameter}" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-IQ \
  -Dtests.timezone=Europe/Andorra

REPRODUCE WITH: gradle :qa:mixed-cluster:v6.1.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=E709E299BE7B9695 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=search/110_field_collapsing/field collapsing and multiple inner_hits}" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-IQ \
  -Dtests.timezone=Europe/Andorra

REPRODUCE WITH: gradle :qa:mixed-cluster:v6.1.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=E709E299BE7B9695 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=search/110_field_collapsing/field collapsing and inner_hits}" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-IQ \
  -Dtests.timezone=Europe/Andorra

REPRODUCE WITH: gradle :qa:mixed-cluster:v6.1.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=E709E299BE7B9695 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=msearch/20_typed_keys/Multisearch test with typed_keys parameter}" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-IQ \
  -Dtests.timezone=Europe/Andorra
Stacktraces attached for these tests:

org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT test {p0=msearch/20_typed_keys/Multisearch test with typed_keys parameter}
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT test {p0=search/110_field_collapsing/field collapsing and inner_hits}
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT test {p0=search/110_field_collapsing/field collapsing and multiple inner_hits}
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT test {p0=search/110_field_collapsing/field collapsing, inner_hits and maxConcurrentGroupRequests}
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT test {p0=search/90_search_after/search with search_after parameter}
```

stacktrace:
```
Caused by: java.lang.IllegalArgumentException: Fielddata is disabled on text fields by default. Set fielddata=true on [bar] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.
	at org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType.fielddataBuilder(TextFieldMapper.java:288) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:115) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.index.query.QueryShardContext.getForField(QueryShardContext.java:168) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:278) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:154) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:687) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:531) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:507) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:303) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:289) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:285) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:952) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
[2017-08-09T06:21:35,174][DEBUG][o.e.a.s.TransportSearchAction] [node-2] [test2][1], node[5c63mMdET4-DT1RdwNdnaw], [R], s[STARTED], a[id=V4sUJ4kQRw2BgxZUlXW0NQ]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false], types=[], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=20, batchedReduceSize=512, preFilterShardSize=128, source={
  "sort" : [
    {
      "bar" : {
        "order" : "asc"
      }
    },
    {
      "baz" : {
        "order" : "asc"
      }
    }
  ]
}}] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [node-3][127.0.0.1:50023][indices:data/read/search[phase/query]]
```

**Comment by jimczi** [comment]
Fixed by https://github.com/elastic/elasticsearch/commit/15598f2174453fb65f23e18ecf77eee8e802459d
