### ISSUE TITLE
[bug report]java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getClassLoader")

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#26139]
Elasticsearch version:
5.5.1
Plugins installed: []
default
mmseg word
JVM version:
jdk1.8.0_60
OS version:
CentOS Linux release 7.1.1503
Description of the problem including expected versus actual behavior:
try to create class dynamic in plugin and it throws exception below:
Caused by: java.security.AccessControlException: access denied (“java.lang.RuntimePermission” “getClassLoader”)
at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_111]
at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_111]
at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_111]
at java.lang.ClassLoader.checkClassLoaderPermission(ClassLoader.java:1528) ~[?:1.8.0_111]
at java.lang.Thread.getContextClassLoader(Thread.java:1440) ~[?:1.8.0_111]
at com.jd.jsf.gd.util.ClassLoaderUtils.getCurrentClassLoader(ClassLoaderUtils.java:43) ~[?:?]
at com.jd.jsf.gd.util.ClassLoaderUtils.forName(ClassLoaderUtils.java:97) ~[?:?]
at com.jd.jsf.gd.util.ClassLoaderUtils.forName(ClassLoaderUtils.java:81) ~[?:?]
at com.jd.jsf.gd.config.AbstractConsumerConfig.getProxyClass(AbstractConsumerConfig.java:215) ~[?:?]
at com.jd.jsf.gd.config.ConsumerConfig.refer(Consu
merConfig.java:91) ~[?:?]

my policy file is below:
grant {
permission java.lang.RuntimePermission “", "”;
};

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

BTW read https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugin-authors.html#plugin-authors-jsm
