### ISSUE TITLE
[CI] KeyedLockTests.testIfMapEmptyAfterLotsOfAcquireAndReleases fails with NPE

### ISSUE THREAD

**Issue by andyb-elastic** [elastic/elasticsearch#26172]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/3870

I couldn't reproduce this locally. I think this may be something in ESTestCase or randomizedtesting rather than KeyedLockTests since the call to scaledRandomIntBetween looks pretty innocuous.

Reproduce line from log
```
gradle :core:test \
  -Dtests.seed=2430BE548F8FDCF7 \
  -Dtests.class=org.elasticsearch.common.util.concurrent.KeyedLockTests \
  -Dtests.method="testIfMapEmptyAfterLotsOfAcquireAndReleases" \
  -Dtests.security.manager=true \
  -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" \
  -Dtests.locale=ar-YE \
  -Dtests.timezone=America/Costa_Rica
```

```
   > Throwable #1: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=2004, name=Thread-591, state=RUNNABLE, group=TGRP-KeyedLockTests]
   > 	at __randomizedtesting.SeedInfo.seed([2430BE548F8FDCF7:A52F8BD93F9B39E]:0)
   > Caused by: java.lang.NullPointerException
   > 	at __randomizedtesting.SeedInfo.seed([2430BE548F8FDCF7]:0)
   > 	at com.carrotsearch.randomizedtesting.GroupEvaluator.isGroupEnabled(GroupEvaluator.java:176)
   > 	at com.carrotsearch.randomizedtesting.RandomizedContext.isNightly(RandomizedContext.java:125)
   > 	at com.carrotsearch.randomizedtesting.RandomizedTest.isNightly(RandomizedTest.java:82)
   > 	at com.carrotsearch.randomizedtesting.RandomizedTest.scaledRandomIntBetween(RandomizedTest.java:323)
   > 	at org.elasticsearch.test.ESTestCase.scaledRandomIntBetween(ESTestCase.java:451)
   > 	at org.elasticsearch.common.util.concurrent.KeyedLockTests$AcquireAndReleaseThread.run(KeyedLockTests.java:94)
```

**Comment by jpountz** [comment]
It looks like a JVM bug to me?

**Comment by ywelsch** [comment]
AFAICS this is a test bug. `KeyedLockTests` calls `RandomizedTest.scaledRandomIntBetween` from multiple threads which uses `RandomizedTest.isNightly()` whereas that method is not concurrency-safe (see implementation of `GroupEvaluator.isGroupEnabled`)

**Comment by ywelsch** [comment]
Fixed by https://github.com/elastic/elasticsearch/commit/52d627b66f0142e38ed9b318d94ede71c1b9df3c
