### ISSUE TITLE
Index tombstones size configuration is unable to be set as it's unrecognised

### ISSUE THREAD

**Issue by geekpete** [elastic/elasticsearch#26191]
The configuration setting for Index Tombstones "cluster.indices.tombstones.size" described here: https://www.elastic.co/guide/en/elasticsearch/reference/current/misc-cluster.html#cluster-max-tombstones

is unable to be set and a startup exception is thrown suggesting the configuration is an unknown setting.

**Elasticsearch version** (`bin/elasticsearch --version`):
- tested on
  - 5.4.3
  - 5.5.1

**Plugins installed**: []

**JVM version** (`java -version`):
```
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
- Tested on:
  - OSX
    - `Darwin Petes-MBP 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`
  - Linux
    - `Linux inspiron 4.11.11-300.fc26.x86_64 #1 SMP Mon Jul 17 16:32:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

 1. Run up Elasticsearch and use this setting in the configuration:
    - `cluster.indices.tombstones.size: 1`
 2. Start Elasticsearch and check logs, which should contain a startup exception:
    - `org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting.....`

**Provide logs (if relevant)**:
```
[2017-08-14T18:07:21,539][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [cluster.indices.tombstones.size] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.5.1.jar:5.5.1]
Caused by: java.lang.IllegalArgumentException: unknown setting [cluster.indices.tombstones.size] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:293) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:256) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:139) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.node.Node.<init>(Node.java:343) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.node.Node.<init>(Node.java:244) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.1.jar:5.5.1]
        ... 6 more
```

**Comment by ywelsch** [comment]
I've opened #26193
