### ISSUE TITLE
[CI] IndexWithShadowReplicasIT testIndexWithFewDocuments fails in 5.5

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#26241]
The test failed in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.5+multijob-windows-compatibility/39/consoleFull.

It looks like an assertion in `ThreadContext` (line 447) tripped: `assert existingValues.size() == existingUniqueValues.size();`

Reproduce command:

```
gradle :core:integTest -Dtests.seed=26D39E8A3373256B -Dtests.class=org.elasticsearch.index.IndexWithShadowReplicasIT -Dtests.method="testIndexWithFewDocuments" -Dtests.security.manager=true -Dtests.locale=ar -Dtests.timezone=Atlantic/Cape_Verde
```

Cannot reproduce locally.

**Comment by dakrone** [comment]
I've been looking into this but I haven't been able to determine a cause or solution. Since shadow replicas are removed in 6.0 I'm going to close this, if it fails a second time we can re-open and take another look.

**Comment by andy-elastic** [comment]
Another one from today https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.5+multijob-unix-compatibility/os=centos/124/console

Here's the stack trace for future reference

```
23:02:22   1> [2017-09-14T01:02:03,354][INFO ][o.e.i.IndexWithShadowReplicasIT] [testIndexWithFewDocuments]: after test
23:02:22 ERROR   32.0s J0 | IndexWithShadowReplicasIT.testIndexWithFewDocuments <<< FAILURES!
23:02:22    > Throwable #1: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=1697, name=elasticsearch[node_t1][clusterService#updateTask][T#1], state=RUNNABLE, group=TGRP-IndexWithShadowReplicasIT]
23:02:22    > 	at __randomizedtesting.SeedInfo.seed([640935868A4179FC:8395E1A8635387E7]:0)
23:02:22    > Caused by: java.lang.AssertionError
23:02:22    > 	at __randomizedtesting.SeedInfo.seed([640935868A4179FC]:0)
23:02:22    > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ThreadContextStruct.putResponse(ThreadContext.java:447)
23:02:22    > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ThreadContextStruct.access$1100(ThreadContext.java:352)
23:02:22    > 	at org.elasticsearch.common.util.concurrent.ThreadContext.addResponseHeader(ThreadContext.java:280)
23:02:22    > 	at org.elasticsearch.common.logging.DeprecationLogger.deprecated(DeprecationLogger.java:285)
23:02:22    > 	at org.elasticsearch.common.logging.DeprecationLogger.deprecated(DeprecationLogger.java:124)
23:02:22    > 	at org.elasticsearch.index.store.FsDirectoryService.newFSDirectory(FsDirectoryService.java:111)
23:02:22    > 	at org.elasticsearch.index.store.FsDirectoryService.newDirectory(FsDirectoryService.java:90)
23:02:22    > 	at org.elasticsearch.test.store.MockFSDirectoryService.newDirectory(MockFSDirectoryService.java:107)
23:02:22    > 	at org.elasticsearch.index.store.Store.<init>(Store.java:159)
23:02:22    > 	at org.elasticsearch.index.IndexService.createShard(IndexService.java:346)
23:02:22    > 	at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:500)
23:02:22    > 	at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:148)
23:02:22    > 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.createShard(IndicesClusterStateService.java:542)
23:02:22    > 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.createOrUpdateShards(IndicesClusterStateService.java:519)
23:02:22    > 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:204)
23:02:22    > 	at org.elasticsearch.cluster.service.ClusterService.callClusterStateAppliers(ClusterService.java:814)
23:02:22    > 	at org.elasticsearch.cluster.service.ClusterService.publishAndApplyChanges(ClusterService.java:768)
23:02:22    > 	at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:587)
23:02:22    > 	at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.run(ClusterService.java:263)
23:02:22    > 	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
23:02:22    > 	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
23:02:22    > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569)
23:02:22    > 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247)
23:02:22    > 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210)
23:02:22    > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
23:02:22    > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
23:02:22    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mayya-sharipova** [comment]
Another test failure from today on 5.6: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+periodic/2137/console
```
./gradlew :core:integTest \
  -Dtests.seed=2654AAF9700A7101 \
  -Dtests.class=org.elasticsearch.index.IndexWithShadowReplicasIT \
  -Dtests.method="testIndexWithFewDocuments" \
  -Dtests.security.manager=true \
  -Dtests.locale=fr-FR \
  -Dtests.timezone=Etc/GMT+1
```

**Comment by colings86** [comment]
Shadow replicas is gone now so closing this issue

**Comment by jasontedor** [comment]
I do not think this is a shadow replicas issue. Instead, I think it might be indicative of a problem with how we de-deduplicate deprecation messages on a thread context.

**Comment by jasontedor** [comment]
I pushed 424be027283588ac5fb76dffbee1c1cb88e75ff5 and backported it all the way to 5.6 so that if this fails again we should have more information about the failure.

**Comment by dakrone** [comment]
Since we haven't had more movement on this in a month since Jason pushed his additional debugging, I'm going to close this, if it happens again with the additional logging we can re-open and investigate.
