### ISSUE TITLE
failure using Windows junctions for data dir

### ISSUE THREAD

**Issue by jmlucjav** [elastic/elasticsearch#26306]
**Elasticsearch version** 
Version: 6.0.0-beta1-SNAPSHOT, Build: Unknown/2017-08-13T15:13:28.500Z, JVM: 1.8.0_102

**JVM version**
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**OS version**
win10, 64b

**Description of the problem including expected versus actual behavior**:
If you use windows junctions to make the data/logs dirs point to other directories, ES fails to start

**Steps to reproduce**:

1. create the target dirs, and setup junctions, in %ES_HOME%, run:
```
mkdir D:\es\logs
mkdir D:\es\data
mklink /J logs D:\es\logs
mklink /J data D:\es\data
```

2. start ES
```
[2017-08-21T12:16:21,329][INFO ][o.e.n.Node               ] [] initializing ...
[2017-08-21T12:16:21,349][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.security.AccessControlException: access denied ("java.io.FilePermission" "D:\es\data\nodes\0" "write")
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:69) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "D:\es\data\nodes\0" "write")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_102]
        at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_102]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_102]
        at java.lang.SecurityManager.checkWrite(SecurityManager.java:979) ~[?:1.8.0_102]
        at sun.nio.fs.WindowsPath.checkWrite(WindowsPath.java:799) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:491) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_102]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_102]
        at java.nio.file.Files.createDirectories(Files.java:727) ~[?:1.8.0_102]
        at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:92) ~[lucene-core-7.0.0-snapshot-00142c9.jar:7.0.0-snapshot-00142c9 00142c921322a92de5007be2a114893aaa072498 - jpountz - 2017-07-11 09:24:13]
        at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41) ~[lucene-core-7.0.0-snapshot-00142c9.jar:7.0.0-snapshot-00142c9 00142c921322a92de5007be2a114893aaa072498 - jpountz - 2017-07-11 09:24:13]
        at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45) ~[lucene-core-7.0.0-snapshot-00142c9.jar:7.0.0-snapshot-00142c9 00142c921322a92de5007be2a114893aaa072498 - jpountz - 2017-07-11 09:24:13]
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:209) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
        at org.elasticsearch.node.Node.<init>(Node.java:260) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
        at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.0.0-beta1-SNAPSHOT.jar:6.0.0-beta1-SNAPSHOT]
        ... 6 more
```

The dir d:\es\data\nodes\0\ has been created, but it is empty.

**Comment by jimczi** [comment]
It seems that the `SecurityManager` cannot handle junctions correctly. There is a similar bug in Lucene:
https://issues.apache.org/jira/browse/LUCENE-6644
@jasontedor is there anything we can do ?

**Comment by jmlucjav** [comment]
FYI, I tried with the target dirs being in the same disk ES_HOME is, and it failed too, but with a different error msg.

**Comment by jasontedor** [comment]
The Lucene issue is closed as won't fix. Without that being fixed, there's nothing that we can do. Even if the Lucene issue were fixed, I'm still not sure if we should do anything. This is the first time this issue has come up in two years of the security manager. Junctions can only be used to point to local volumes on the same computer, so there's a workaround: change the Elasticsearch configuration to point to that local volume directly instead of via the junction.

**Comment by jmlucjav** [comment]
@jasontedor I did not post the msg as I was in a hurry and thought that fixing the diff disk scenario would automatically fix the other one (intuitively the diff disk case should be as hard as or harder to fix).  But if this is a no fix why should the other one be different? Anyway, this is in my dev machine, so I can overcome the issue several ways, thanks.

**Comment by jasontedor** [comment]
I can't answer your question without knowing what the second issue is.
