### ISSUE TITLE
[CI] Multiple failures for :qa:mixed-cluster:v6.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#26314]
CI links:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+aggressive-opts/615/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/3993/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+java9-periodic/3693/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+oracle-periodic/469/console

trace:

```
org.elasticsearch.transport.RemoteTransportException: [node-2][127.0.0.1:40307][indices:data/read/search[phase/query]]
Caused by: java.lang.IllegalArgumentException: Fielddata is disabled on text fields by default. Set fielddata=true on [bar] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.
	at org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType.fielddataBuilder(TextFieldMapper.java:288) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
...
org.elasticsearch.transport.RemoteTransportException: [node-2][127.0.0.1:40307][indices:data/read/search[phase/query]]
Caused by: java.lang.IllegalArgumentException: Expected numeric type on field [string_field], but got [keyword]
	at org.elasticsearch.search.aggregations.support.ValuesSourceConfig.numericField(ValuesSourceConfig.java:307) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
	at org.elasticsearch.search.aggregations.support.ValuesSourceConfig.originalValuesSource(ValuesSourceConfig.java:290) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
```

I cannot reproduce with current master..

```
REPRODUCE WITH: gradle :qa:mixed-cluster:v6.1.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=86374FA8D9FBF79B \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=count/20_query_string/count with query_string parameters}" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-BH \
  -Dtests.timezone=US/Eastern

REPRODUCE WITH: gradle :qa:mixed-cluster:v6.1.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=86374FA8D9FBF79B \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=explain/30_query_string/explain with query_string parameters}" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-BH \
  -Dtests.timezone=US/Eastern

REPRODUCE WITH: gradle :qa:mixed-cluster:v6.1.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=86374FA8D9FBF79B \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=search/60_query_string/search with query_string parameters}" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-BH \
  -Dtests.timezone=US/Eastern

REPRODUCE WITH: gradle :qa:mixed-cluster:v6.1.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=7F3C7CDE11BBCD8D \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=search/30_limits/Request window limits with scroll}" \
  -Dtests.security.manager=true \
  -Dtests.locale=fr-LU \
  -Dtests.timezone=America/Argentina/Cordoba
```

**Comment by jasontedor** [comment]
I think the true failure is higher in the logs. In the first three I see a message:

```
  1> Caused by: RemoteTransportException[[node-2][127.0.0.1:40038][indices:data/read/explain[s]]]; nested: IllegalStateException[unexpected byte [0x32]];
  1> Caused by: java.lang.IllegalStateException: unexpected byte [0x32]
```

or something similar. These serialization failures then lead to the test failures for these tests.

In the fourth I see:

```
1>             "reason" : "Validation Failed: 1: using [from] is not allowed in a scroll context;",
  1>             "stack_trace" : "[Validation Failed: 1: using [from] is not allowed in a scroll context;]; nested: ActionRequestValidationException[Validation Failed: 1: using [from] is not allowed in a scroll context;];
```

I think there's a common cause to all of these, a BWC change that the build was not ready for. For the former I think that it's #26145 and for the latter that would be #26235.

So, these appear to have been temporary build failures that no longer reproduce now that all branches have caught up.
