### ISSUE TITLE
[TEST] testAutoQueueSizingWithMin trips assertion

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#26332]
QueueResizingEsThreadPoolExecutorTests.testAutoQueueSizingWithMin trips an assertion. Reproduces for me when running the test often enough.

Failure:

```
java.lang.AssertionError: cannot calculate for instantaneous tasks, got: 0
	at __randomizedtesting.SeedInfo.seed([8435AB382A4D9B90]:0)
	at org.elasticsearch.common.util.concurrent.QueueResizingEsThreadPoolExecutor.calculateLambda(QueueResizingEsThreadPoolExecutor.java:106)
	at org.elasticsearch.common.util.concurrent.QueueResizingEsThreadPoolExecutor.afterExecute(QueueResizingEsThreadPoolExecutor.java:177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1150)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Failing test run:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.0+aggressive-opts/133/consoleFull

**Comment by dakrone** [comment]
Resolved this in the linked commit, I just misspelled "Resolved" so it didn't auto-close..
