### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/lucene/util/SetOnce

### ISSUE THREAD

**Issue by chenweichu3** [elastic/elasticsearch#26342]
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/lucene/util/SetOnce
	at org.elasticsearch.cli.Command.<init>(Command.java:58)
	at org.elasticsearch.cli.EnvironmentAwareCommand.<init>(EnvironmentAwareCommand.java:39)
	at org.elasticsearch.bootstrap.Elasticsearch.<init>(Elasticsearch.java:53)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:83)
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.util.SetOnce
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more

**Comment by cbuescher** [comment]
This means, "org/apache/lucene/util/SetOnce" is not on your classpath. It should normally be part of the Lucene jar.
As Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions like this, I hope you don't mind me closing this.
