### ISSUE TITLE
Warnings of "IllegalStateException: unexpected docvalues type NONE for field '_parent'" on upgraded index

### ISSUE THREAD

**Issue by abhiCR7** [elastic/elasticsearch#26341]
It is the same problem that was reported with this [issue](https://github.com/elastic/elasticsearch/issues/25849). 
My current version 5.5.2, build date 14th Aug 2017.
Exceptions I'm getting are: 
`[2017-08-23T18:05:35,501][WARN ][o.e.i.w.ShardIndexWarmerService] [node_1] [index1][0] failed to warm-up global ordinals for [_parent]
org.elasticsearch.ElasticsearchException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: unexpected docvalues type NONE for field '_parent' (expected one of [SORTED, SORTED_SET]). Re-index with correct docvalues type.
	at org.elasticsearch.index.fielddata.plain.SortedSetDVOrdinalsIndexFieldData.loadGlobal(SortedSetDVOrdinalsIndexFieldData.java:120) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.fielddata.plain.SortedSetDVOrdinalsIndexFieldData.loadGlobal(SortedSetDVOrdinalsIndexFieldData.java:45) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.IndexWarmer$FieldDataWarmer.lambda$warmReader$1(IndexWarmer.java:141) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.5.2.jar:5.5.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: unexpected docvalues type NONE for field '_parent' (expected one of [SORTED, SORTED_SET]). Re-index with correct docvalues type.
	at org.elasticsearch.common.cache.Cache.computeIfAbsent(Cache.java:404) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache.load(IndicesFieldDataCache.java:154) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.fielddata.plain.SortedSetDVOrdinalsIndexFieldData.loadGlobal(SortedSetDVOrdinalsIndexFieldData.java:115) ~[elasticsearch-5.5.2.jar:5.5.2]
	... 6 more
Caused by: java.lang.IllegalStateException: unexpected docvalues type NONE for field '_parent' (expected one of [SORTED, SORTED_SET]). Re-index with correct docvalues type.
	at org.apache.lucene.index.DocValues.checkField(DocValues.java:212) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
	at org.apache.lucene.index.DocValues.getSortedSet(DocValues.java:306) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
	at org.elasticsearch.index.fielddata.plain.SortedSetDVBytesAtomicFieldData.getOrdinalsValues(SortedSetDVBytesAtomicFieldData.java:53) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.fielddata.ordinals.GlobalOrdinalsBuilder.build(GlobalOrdinalsBuilder.java:63) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.fielddata.plain.SortedSetDVOrdinalsIndexFieldData.localGlobalDirect(SortedSetDVOrdinalsIndexFieldData.java:127) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.fielddata.plain.SortedSetDVOrdinalsIndexFieldData.localGlobalDirect(SortedSetDVOrdinalsIndexFieldData.java:45) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache.lambda$load$1(IndicesFieldDataCache.java:157) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.common.cache.Cache.computeIfAbsent(Cache.java:401) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.indices.fielddata.cache.IndicesFieldDataCache$IndexFieldCache.load(IndicesFieldDataCache.java:154) ~[elasticsearch-5.5.2.jar:5.5.2]
	at org.elasticsearch.index.fielddata.plain.SortedSetDVOrdinalsIndexFieldData.loadGlobal(SortedSetDVOrdinalsIndexFieldData.java:115) ~[elasticsearch-5.5.2.jar:5.5.2]
	... 6 more`

It would be really helpful if anyone can help me with this. The migration-helper plugin suggested no action required.

**Comment by jimczi** [comment]
As mentioned in the fix this should not be a problem. We introduced this bug in 5.5 but it doesn't mean that your index or cluster is broken. It's annoying because the exception is logged on every refresh (and at startup) but it's only because it tries to load global ordinals for a field that does not exist. There is a fix in the upcoming release of es (5.6), in the mean time you can just ignore the exception since it doesn't prevent the use of the parent/child feature.

**Comment by abhiCR7** [comment]
@jimczi Thanks for the clarification. Though seeing the `warn` i was relieved but wanted to be sure before I go ahead with the upgrade in production from 2.x to 5.x
