### ISSUE TITLE
can not write type [class java.math.BigDecimal] on Script usage

### ISSUE THREAD

**Issue by mosinnik** [elastic/elasticsearch#26364]
When i try use Script in update to emulate upsert on condition i found error:
```
Caused by: java.io.IOException: can not write type [class java.math.BigDecimal]
	at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:655) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.common.io.stream.StreamOutput.lambda$static$11(StreamOutput.java:570) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:653) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.common.io.stream.StreamOutput.lambda$static$11(StreamOutput.java:570) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:653) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.common.io.stream.StreamOutput.lambda$static$11(StreamOutput.java:570) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:653) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.common.io.stream.StreamOutput.lambda$static$11(StreamOutput.java:570) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:653) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.common.io.stream.StreamOutput.writeMap(StreamOutput.java:443) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.script.Script.writeTo(Script.java:566) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.action.update.UpdateRequest.writeTo(UpdateRequest.java:886) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.action.DocWriteRequest.writeDocumentRequest(DocWriteRequest.java:198) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.action.bulk.BulkRequest.writeTo(BulkRequest.java:638) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.transport.TcpTransport.buildMessage(TcpTransport.java:1235) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.transport.TcpTransport.sendRequestToChannel(TcpTransport.java:1094) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.transport.TcpTransport.access$1200(TcpTransport.java:116) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.transport.TcpTransport$NodeChannels.sendRequest(TcpTransport.java:445) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:586) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:519) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:507) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.action.TransportActionNodeProxy.execute(TransportActionNodeProxy.java:51) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.client.transport.TransportProxyClient.lambda$execute$0(TransportProxyClient.java:59) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:250) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:363) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54) ~[elasticsearch-5.5.1.jar:5.5.1]
	... 4 more
```
Creating update request with simple script code:
```
Map<String, Object> params = new HashMap<>();
params.put("receiveTimeMs", prepared.receiveTimeMs);
params.put("newSource", prepared.source);

Script script = new Script(
	ScriptType.INLINE,
	"painless",
	"if(ctx._source.meta.receiveTimeMs >= params.receiveTimeMs) {" +
		" ctx.op = 'noop' " +
		"} else {" +
		" ctx._source.meta = params.newSource.meta;" +
		" ctx._source.responsemessage = params.newSource.responsemessage;" +
		"}",
	params
);
return new UpdateRequest()
	.index(prepared.index)
	.type(prepared.type)
	.id(prepared.id)
	.routing(prepared.routing)
	.upsert(toInsertRequest(prepared))
	.script(script);
```
`params` - HashMap, 
`newSource` contains objects and on of then is BigDecimal.
If i make only IndexRequest it's all right.
On update with script - fail.

ES transport client 5.5.1

Is it painless restrictions or may be fixed?

**Comment by jdconrad** [comment]
I don't think this is specifically a Painless issue.  I think this is similar to (https://discuss.elastic.co/t/bigdecimals-in-scripts-causing-issues/26976).  Unfortunately, it looks like the work around may be to not use BigDecimal in this case.

**Comment by mosinnik** [comment]
Of course i created some crutches for converting BD to double. But the point is on indexing BD works well, on script updating - no. I think should be same-same. Isn't?

**Comment by jdconrad** [comment]
@nik9000 Is this something you might be able to explain off the top of your head?

**Comment by nik9000** [comment]
This doesn't work with update because we serialize the parameters with [this](https://github.com/elastic/elasticsearch/blob/5.4/core/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java#L509-L624). But with indexing we [serialize](https://github.com/elastic/elasticsearch/blob/5.4/core/src/main/java/org/elasticsearch/action/index/IndexRequest.java#L358-L380) the source map to JSON/YAML/whatever before throwing it over the wire.

I'd love to improve the error messaging here but I'm not sure there is much point given that we're hoping folks with transition from the transport client to the high level rest client which doesn't have this problem because *everything* is turned into JSON.
