### ISSUE TITLE
ScheduledNodeSampler still running after TransportClient was closed

### ISSUE THREAD

**Issue by hosuaby** [elastic/elasticsearch#26416]
# Bug report
**Concern**: Elasticsearch Java client
**Java version**: JDK 1.8
**Elastic version**: 2.4
**Elastic java client version**: 2.4.6

# Description
When TransportClient is closed using method _close()_ all threads of this client are stoped except one: ScheduledNodeSampler. It can be detected as following:
1. Instantiate a new client with:
```java
final TransportClient client = TransportClient
                .builder()
                ...
                .build();
```

2. Shutdown the client (application must still running)
```java
client.close()
```

3. Shutdown the cluster

4. Observe logs of application. Every 5 seconds exception Stacktrace will be printed:
```
batch-admin_1    | 08:53:33.145 [INFO ] [elasticsearch[Madcap][generic][T#2]] [cdirect] org.elasticsearch.client.transport - [Madcap] failed to connect to node [{#transport#-1}{elasticsearch}{172.20.0.2:9300}], removed from nodes list
batch-admin_1    | org.elasticsearch.transport.ConnectTransportException: [][172.20.0.2:9300] connect_timeout[30s]
batch-admin_1    | 	at org.elasticsearch.transport.netty.NettyTransport.connectToChannelsLight(NettyTransport.java:967) ~[elasticsearch-2.4.6.jar:2.4.6]
batch-admin_1    | 	at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:933) ~[elasticsearch-2.4.6.jar:2.4.6]
batch-admin_1    | 	at org.elasticsearch.transport.netty.NettyTransport.connectToNodeLight(NettyTransport.java:906) ~[elasticsearch-2.4.6.jar:2.4.6]
batch-admin_1    | 	at org.elasticsearch.transport.TransportService.connectToNodeLight(TransportService.java:267) ~[elasticsearch-2.4.6.jar:2.4.6]
batch-admin_1    | 	at org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler.doSample(TransportClientNodesService.java:390) ~[elasticsearch-2.4.6.jar:2.4.6]
batch-admin_1    | 	at org.elasticsearch.client.transport.TransportClientNodesService$NodeSampler.sample(TransportClientNodesService.java:336) [elasticsearch-2.4.6.jar:2.4.6]
batch-admin_1    | 	at org.elasticsearch.client.transport.TransportClientNodesService$ScheduledNodeSampler.run(TransportClientNodesService.java:369) [elasticsearch-2.4.6.jar:2.4.6]
batch-admin_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
batch-admin_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
batch-admin_1    | 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
batch-admin_1    | Caused by: java.net.NoRouteToHostException: No route to host
batch-admin_1    | 	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_121]
batch-admin_1    | 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_121]
batch-admin_1    | 	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152) ~[netty-3.10.6.Final.jar:na]
batch-admin_1    | 	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105) ~[netty-3.10.6.Final.jar:na]
batch-admin_1    | 	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79) ~[netty-3.10.6.Final.jar:na]
batch-admin_1    | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[netty-3.10.6.Final.jar:na]
batch-admin_1    | 	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42) ~[netty-3.10.6.Final.jar:na]
batch-admin_1    | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.6.Final.jar:na]
batch-admin_1    | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[netty-3.10.6.Final.jar:na]
batch-admin_1    | 	... 3 common frames omitted
```

**Comment by hosuaby** [comment]
False alarm. My code had on unclosed client. Everything works fine. TransportClient closes well
