### ISSUE TITLE
EvilLoggerTest failures on java 9 with upgrade to log4j 2.9

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#26464]
We started seeing test failures on java 9 because log4j emits some exception when we are looking for a different elastic exception.

Example failure:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.0+java9-periodic/434/console

```
22:40:39   2> REPRODUCE WITH: gradle :qa:evil-tests:test -Dtests.seed=5BBA8AAA3C467CDB -Dtests.class=org.elasticsearch.common.logging.EvilLoggerTests -Dtests.method="testLocationInfoTest" -Dtests.security.manager=false -Dtests.jvm.argline="--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.nio.file=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED --add-opens=java.base/java.util.regex=ALL-UNNAMED" -Dtests.locale=rof-TZ -Dtests.timezone=Zulu
22:40:39   1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:802) [randomizedtesting-runner-2.5.2.jar:?]
22:40:39   1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:852) [randomizedtesting-runner-2.5.2.jar:?]
22:40:39   1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:863) [randomizedtesting-runner-2.5.2.jar:?]
22:40:39   1> 	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) [lucene-test-framework-7.0.0-snapshot-d94a5f0.jar:7.0.0-snapshot-d94a5f0 d94a5f00f08c1d0552320d3a87daeec9fab29c2f - jpountz - 2017-08-30 13:24:05]
22:40:39   1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) [randomizedtesting-runner-2.5.2.jar:?]
22:40:39   1> 	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41) [lucene-test-framework-7.0.0-snapshot-d94a5f0.jar:7.0.0-snapshot-d94a5f0 d94a5f00f08c1d0552320d3a87daeec9fab29c2f - jpountz - 2017-08-30 13:24:05]
22:40:39   1> 	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) [randomizedtesting-runner-2.5.2.jar:?]
22:40:39   1> 	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) [randomizedtesting-runner-2.5.2.jar:?]
22:40:39   1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) [randomizedtesting-runner-2.5.2.jar:?]
22:40:39   1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) [randomizedtesting-runner-2.5.2.jar:?]
22:40:39   1> 	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53) [lucene-test-framework-7.0.0-snapshot-d94a5f0.jar:7.0.0-snapshot-d94a5f0 d94a5f00f08c1d0552320d3a87daeec9fab29c2f - jpountz - 2017-08-30 13:24:05]
22:40:39   1> 	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) [lucene-test-framework-7.0.0-snapshot-d94a5f0.jar:7.0.0-snapshot-d94a5f0 d94a5f00f08c1d0552320d3a87daeec9fab29c2f - jpountz - 2017-08-30 13:24:05]
22:40:39   1> 	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) [lucene-test-framework-7.0.0-snapshot-d94a5f0.jar:7.0.0-snapshot-d94a5f0 d94a5f00f08c1d0552320d3a87daeec9fab29c2f - jpountz - 2017-08-30 13:24:05]
22:40:39   1> 	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54) [lucene-test-framework-7.0.0-snapshot-d94a5f0.jar:7.0.0-snapshot-d94a5f0 d94a5f00f08c1d0552320d3a87daeec9fab29c2f - jpountz - 2017-08-30 13:24:05]
22:40:39   1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) [randomizedtesting-runner-2.5.2.jar:?]
22:40:39   1> 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368) [randomizedtesting-runner-2.5.2.jar:?]
22:40:39   1> 	at java.lang.Thread.run(Thread.java:844) [?:?]```

**Comment by rjernst** [comment]
@jasontedor I assigned to you for now. I will awaitsfix the tests. Feel free to reassign if you think someone else would be better to investigate.
