### ISSUE TITLE
elasticsearch 5.5.2 startup error with x-pack-5.5.2?but elasticsearch 5.5.2 startup OK without x-pack-5.5.2

### ISSUE THREAD

**Issue by kervin521** [elastic/elasticsearch#26489]
C:\Users>elasticsearch
[2017-09-04T16:51:29,094][INFO ][o.e.n.Node               ] [] initializing ...
[2017-09-04T16:51:29,277][INFO ][o.e.e.NodeEnvironment    ] [GSe1Il3] using [1] data paths, mounts [[鏁版嵁 (D:)]], net
usable_space [193.3gb], net total_space [299.9gb], spins? [unknown], types [NTFS]
[2017-09-04T16:51:29,279][INFO ][o.e.e.NodeEnvironment    ] [GSe1Il3] heap size [1.9gb], compressed ordinary object poin
ters [true]
[2017-09-04T16:51:29,282][INFO ][o.e.n.Node               ] node name [GSe1Il3] derived from node ID [GSe1Il3KRDSJ3LNW1r
tRzg]; set [node.name] to override
[2017-09-04T16:51:29,282][INFO ][o.e.n.Node               ] version[5.5.2], pid[3756], build[b2f0c09/2017-08-14T12:33:14
.154Z], OS[Windows 7/6.1/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_144/25.144-b01]
[2017-09-04T16:51:29,283][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:
CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=
true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio
.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j
2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Delasticsearch, -Des.path.home=D:\WebServe
r\ELK\elasticsearch-5.5.2]
[2017-09-04T16:51:39,141][INFO ][o.e.p.PluginsService     ] [GSe1Il3] loaded module [aggs-matrix-stats]
[2017-09-04T16:51:39,681][INFO ][o.e.p.PluginsService     ] [GSe1Il3] loaded module [ingest-common]
[2017-09-04T16:51:39,698][INFO ][o.e.p.PluginsService     ] [GSe1Il3] loaded module [lang-expression]
[2017-09-04T16:51:39,698][INFO ][o.e.p.PluginsService     ] [GSe1Il3] loaded module [lang-groovy]
[2017-09-04T16:51:39,703][INFO ][o.e.p.PluginsService     ] [GSe1Il3] loaded module [lang-mustache]
[2017-09-04T16:51:39,715][INFO ][o.e.p.PluginsService     ] [GSe1Il3] loaded module [lang-painless]
[2017-09-04T16:51:39,715][INFO ][o.e.p.PluginsService     ] [GSe1Il3] loaded module [parent-join]
[2017-09-04T16:51:39,719][INFO ][o.e.p.PluginsService     ] [GSe1Il3] loaded module [percolator]
[2017-09-04T16:51:39,725][INFO ][o.e.p.PluginsService     ] [GSe1Il3] loaded module [reindex]
[2017-09-04T16:51:39,731][INFO ][o.e.p.PluginsService     ] [GSe1Il3] loaded module [transport-netty3]
[2017-09-04T16:51:39,737][INFO ][o.e.p.PluginsService     ] [GSe1Il3] loaded module [transport-netty4]
[2017-09-04T16:51:39,752][INFO ][o.e.p.PluginsService     ] [GSe1Il3] loaded plugin [x-pack]
[2017-09-04T16:52:23,599][DEBUG][o.e.a.ActionModule       ] Using REST wrapper from plugin org.elasticsearch.xpack.XPack
Plugin
[2017-09-04T16:52:47,431][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Failed to create native process factories for Machi
ne Learning]; nested: FileNotFoundException[\\.\pipe\controller_log_3756 (绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆?];
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.5.2.
jar:5.5.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.5.2.jar:5.5.2]
Caused by: org.elasticsearch.ElasticsearchException: Failed to create native process factories for Machine Learning
        at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLearning.java:293) ~[?:?]
        at org.elasticsearch.xpack.XPackPlugin.createComponents(XPackPlugin.java:288) ~[?:?]
        at org.elasticsearch.node.Node.lambda$new$7(Node.java:411) ~[elasticsearch-5.5.2.jar:5.5.2]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_144]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_144]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_144]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_144]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_144]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_144]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_144]
        at org.elasticsearch.node.Node.<init>(Node.java:413) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.node.Node.<init>(Node.java:244) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.2.jar:5.5.2]
        ... 6 more
Caused by: java.io.FileNotFoundException: \\.\pipe\controller_log_3756 (绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆?
        at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_144]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_144]
        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_144]
        at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[?:1.8.0_144]
        at org.elasticsearch.xpack.ml.utils.NamedPipeHelper$PrivilegedInputPipeOpener.run(NamedPipeHelper.java:297) ~[?:
?]
        at org.elasticsearch.xpack.ml.utils.NamedPipeHelper$PrivilegedInputPipeOpener.run(NamedPipeHelper.java:286) ~[?:
?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_144]
        at org.elasticsearch.xpack.ml.utils.NamedPipeHelper.openNamedPipeInputStream(NamedPipeHelper.java:139) ~[?:?]
        at org.elasticsearch.xpack.ml.utils.NamedPipeHelper.openNamedPipeInputStream(NamedPipeHelper.java:106) ~[?:?]
        at org.elasticsearch.xpack.ml.job.process.ProcessPipes.connectStreams(ProcessPipes.java:140) ~[?:?]
        at org.elasticsearch.xpack.ml.job.process.NativeController.<init>(NativeController.java:67) ~[?:?]
        at org.elasticsearch.xpack.ml.job.process.NativeControllerHolder.getNativeController(NativeControllerHolder.java
:50) ~[?:?]
        at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLearning.java:283) ~[?:?]
        at org.elasticsearch.xpack.XPackPlugin.createComponents(XPackPlugin.java:288) ~[?:?]
        at org.elasticsearch.node.Node.lambda$new$7(Node.java:411) ~[elasticsearch-5.5.2.jar:5.5.2]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_144]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_144]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_144]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_144]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_144]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_144]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_144]
        at org.elasticsearch.node.Node.<init>(Node.java:413) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.node.Node.<init>(Node.java:244) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.2.jar:5.5.2]
        ... 6 more

**Comment by kervin521** [comment]
elasticsearch 5.5.2 startup successfully without x-pack-5.5.2

**Comment by davidkyle** [comment]
Hi @kervin521 Did you raise this issue on the discuss forum https://discuss.elastic.co/t/failed-to-create-native-process-factories-for-machine-learning/98798 it looks like a very similar problem. 

I'd like to help you diagnose the problem but I think discuss.elastic.co would be a better place to handle it. Can you move the ticket to discuss please.

**Comment by jasontedor** [comment]
@kervin521 This repository is for open source Elasticsearch only, we do not handle X-Pack issues here. For that, there is the [forum](https://discuss.elastic.co) as @davidkyle mentioned where you can use the [X-Pack category](https://discuss.elastic.co/c/x-pack).
