### ISSUE TITLE
log4j UnsupportedCharsetException cp65001 after Elasticsearch 6.0.0-Beta2 bat run 

### ISSUE THREAD

**Issue by net1pei** [elastic/elasticsearch#26518]
Elasticsearch version (bin/elasticsearch --version):
6.0.0-Beta2

Plugins installed:
No

JVM version (java -version):
1.8.0_144

OS version (uname -a if on a Unix-like system):
Win7-SP1, 64 bit

Description of the problem including expected versus actual behavior:

Install Elasticsearch 6.0.0-Beta2 ZIP, URL: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0-beta2.zip

After unzip into E:\ES\elasticsearch-6.0.0-beta2 , when run in DOS, then get an error:
E:\ES\elasticsearch-6.0.0-beta2\bin>elasticsearch.bat
2017-09-06 19:43:55,657 main ERROR Unable to inject fields into builder class for plugin type class org.apache.logging.log4j.core.appender.ConsoleAppender, elem
ent Console. java.nio.charset.UnsupportedCharsetException: cp65001
        at java.nio.charset.Charset.forName(Unknown Source)
        at org.apache.logging.log4j.util.PropertiesUtil.getCharsetProperty(PropertiesUtil.java:146)
        at org.apache.logging.log4j.util.PropertiesUtil.getCharsetProperty(PropertiesUtil.java:134)
        at org.apache.logging.log4j.core.appender.ConsoleAppender$Target.getCharset(ConsoleAppender.java:85)
        at org.apache.logging.log4j.core.appender.ConsoleAppender$Target$1.getDefaultCharset(ConsoleAppender.java:71)
        at org.apache.logging.log4j.core.appender.ConsoleAppender$Builder.build(ConsoleAppender.java:218)
        at org.apache.logging.log4j.core.appender.ConsoleAppender$Builder.build(ConsoleAppender.java:185)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:952)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:892)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:508)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:232)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:261)
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:164)
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:120)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:290)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:130)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:121)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:69)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85)

2017-09-06 19:43:55,701 main ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.appender.ConsoleAppender for element Console. ja
va.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.ConsoleAppender
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:224)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:130)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:952)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:892)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:508)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:232)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:261)
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:164)
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:120)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:290)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:130)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:121)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:69)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85)

2017-09-06 19:43:55,764 main ERROR Null object returned for Console in Appenders.
2017-09-06 19:43:55,781 main ERROR Unable to locate appender "console" for logger config "root"

**Comment by jasontedor** [comment]
Duplicates #25981
