### ISSUE TITLE
some UNASSIGNED shards kill the cluster

### ISSUE THREAD

**Issue by mars00772** [elastic/elasticsearch#26545]
hi ,I am using ES 5.5 with the hot-warm architecture suggested by [here](https://www.elastic.co/blog/hot-warm-architecture-in-elasticsearch-5-x).by marking indices `warm`, he transfer indices to the warm nodes from hot nodes automatically.

i have 68 indices everyday, 21 shards each indices  cause i have 21 hot nodes with SSD, and the store size is 1.5T everyday.(I found one index is huge:1T above.) , I also have 5 warm node with 48T hdd hard disk.
the warm nodes using 30GB jvm memory setting, still having the the following log .
```
[2017-09-06T15:23:23,583][INFO ][o.e.m.j.JvmGcMonitorService] [_GgVD4J] [gc][old][158124][26565] duration [5.2s], collections [1]/[5.6s], total [5.2s]/[2h], memory [29.8gb]->[28.9gb]/[29.8gb], all_pools {[young] [1.1gb]->[430.9mb]/[1.1gb]}{[survivor] [107.7mb]->[0b]/[149.7mb]}{[old] [28.5gb]->[28.5gb]/[28.5gb]}
[2017-09-06T15:23:36,217][INFO ][o.e.m.j.JvmGcMonitorService] [_GgVD4J] [gc][old][158128][26567] duration [5.2s], collections [1]/[5.6s], total [5.2s]/[2h], memory [29.8gb]->[28.9gb]/[29.8gb], all_pools {[young] [1.1gb]->[388.9mb]/[1.1gb]}{[survivor] [115.3mb]->[0b]/[149.7mb]}{[old] [28.5gb]->[28.5gb]/[28.5gb]}
[2017-09-06T15:23:48,736][INFO ][o.e.m.j.JvmGcMonitorService] [_GgVD4J] [gc][old][158132][26569] duration [5.1s], collections [1]/[5.6s], total [5.1s]/[2h], memory [29.7gb]->[28.9gb]/[29.8gb], all_pools {[young] [1.1gb]->[394.6mb]/[1.1gb]}{[survivor] [100.3mb]->[0b]/[149.7mb]}{[old] [28.5gb]->[28.5gb]/[28.5gb]}
[2017-09-06T15:23:48,737][WARN ][o.e.m.j.JvmGcMonitorService] [_GgVD4J] [gc][158132] overhead, spent [5.1s] collecting in the last [5.6s]
[2017-09-06T15:23:54,639][WARN ][o.e.m.j.JvmGcMonitorService] [_GgVD4J] [gc][158134] overhead, spent [4.4s] collecting in the last [4.9s]
[2017-09-06T15:24:01,120][WARN ][o.e.m.j.JvmGcMonitorService] [_GgVD4J] [gc][158136] overhead, spent [4.6s] collecting in the last [5.4s]
[2017-09-06T15:24:07,129][WARN ][o.e.m.j.JvmGcMonitorService] [_GgVD4J] [gc][158138] overhead, spent [4.2s] collecting in the last [5s]
```
I restart the warm node ,and got lots of `UNASSIGNED ` shards, now the cluster is dead,the master node kept telling:
```
[2017-09-08T13:58:14,426][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [BrSJ2NM] failed to put mappings on indices [[[pdc_20170908/37e0NIffQ6-Y_Cr5Bau5qQ]]], type [log]
org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-mapping) within 30s
        at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$null$0(ClusterService.java:255) [elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher$$Lambda$2434/1961004673.accept(Unknown Source) [elasticsearch-5.5.0.jar:5.5.0]
        at java.util.ArrayList.forEach(ArrayList.java:1249) [?:1.8.0_40]
        at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$onTimeout$1(ClusterService.java:254) [elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher$$Lambda$2433/1790943430.run(Unknown Source) [elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.5.0.jar:5.5.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_40]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
```

**Comment by bleskes** [comment]
It seems like the cluster is suffering from memory pressure and this slows things down too much. Please open a discussion topic on discuss.elastic.co and people can try to help further. We try to keep github for concrete issues and feature requests. If your problem ends up being a code issue we can open a new ticket here.
