### ISSUE TITLE
Cross Cluster Search fails for AWS regions using DNS or public IPs.

### ISSUE THREAD

**Issue by ajoliveira** [elastic/elasticsearch#26615]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.5.2

**Plugins installed**: discovery-ec2

**JVM version** (`java -version`): openjdk version "1.8.0_141"

**OS version** (`uname -a` if on a Unix-like system): Amazon Linux - Linux east1 4.9.43-17.38.amzn1.x86_64 #1 SMP Thu Aug 17 00:20:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Trying to run Cross Cluster Search (CCS) in AWS for 2 clusters that are in different AWS regions. I would like to use DNS or public IPs via the discovery-ec2 plugin so that no IP addresses have to be 'hard-coded' in the config files for the nodes, cluster(s) or ELB's.

It appears that using CCS and Transport Profiles are in conflict because the "publish_host" setting reverts to the default value after nodes are discovered - see testing steps below.  I'm attempting to do this so that the public DNS name or public IP addresses can be used for CCS communication but DNS or internal IPs for the region continue to be used for node communication within each cluster. 

**Steps to reproduce**:
This can also be done with a single node in each region but the use of 2+ nodes per region helped to ensure that cluster communication was maintained within that region, etc.

1. Create 2 clusters with 2 nodes each - NYC (east1 & east2) and SEA (west1 & west2).  Final configuration version attached.
[node_configurations.txt](https://github.com/elastic/elasticsearch/files/1297836/node_configurations.txt)

2. Install and configure discovery-ec2 plugin

3. Configure "east1" to use CCS for "west1" using public DNS, for example, on "east1" set:
```
search.remote.connect: true
search.remote.cluster_west.seeds: [ "ec2-54-X-X-X.us-west-1.compute.amazonaws.com:9300" ]
```

4. With "west1" using default discovery-ec2 options, both SEA nodes communicate via 10.X.X.X addresses:
```
network.host: _site_
network.publish_host: _ec2:privateIp_
transport.host: _site_
transport.publish_host: _ec2:privateIp_
```

5. Attempting a CCS query on "east1" results in a connection failure due to the internal IP addressing:
```
[ec2-user@east1]$ curl -u elastic:changeme -XGET east1:9200/cluster_west:my-index/_search?pretty

{
  "error" : {
    "root_cause" : [
      {
        "type" : "connect_transport_exception",
        "reason" : "[sea-west-1][10.232.9.80:9300] connect_timeout[30s]"
      }
    ],
    "type" : "transport_exception",
    "reason" : "unable to communicate with remote cluster [cluster_west]",
    "caused_by" : {
      "type" : "connect_transport_exception",
      "reason" : "[sea-west-1][10.232.9.80:9300] connect_timeout[30s]",
      "caused_by" : {
        "type" : "connect_timeout_exception",
        "reason" : "connection timed out: ip-10-232-9-80.us-west-1.compute.internal/10.232.9.80:9300"
      }
    }
  },
  "status" : 500
}
```

Changing 4) above to `transport.publish_host: _ec2:publicDns_ or _ec2:publicIpv4_` means CCS request will be successful on "east1", but now SEA nodes will also try to connect via public DNS or IP which may not be supported or available for all nodes in the cluster if they are in VPC or do not have public DNS or IPs.

6. Update configuration on SEA (west1) node to use Transport Profiles, for example:
```
network.host: _site_
network.publish_host: _ec2:privateIp_
transport.profiles.default.port: 9300-9400
transport.profiles.default.bind_host: _site_
transport.profiles.default.publish_host: _ec2:privateIp_
transport.profiles.ccs.port: 9500-9600
transport.profiles.ccs.bind_host: _site_
transport.profiles.ccs.publish_host: _ec2:publicIpv4_
```
and update "east1" to use "ccs" profile port of 9500, ex:
```
search.remote.cluster_west.seeds: [ "ec2-54-X-X-X.us-west-1.compute.amazonaws.com:9500" ]
```
This is supposed to allow the SEA nodes to use 10.X.X.X:9300 for node communication and configures port 9500 for external requests from "east1" in the NYC cluster.

ES startup log shows:
```
[2017-09-12T04:58:32,410][INFO ][o.e.t.TransportService   ] [sea-west-1] publish_address {10.232.9.80:9300}, bound_addresses {10.232.9.80:9300}
[2017-09-12T04:58:32,411][INFO ][o.e.t.TransportService   ] [sea-west-1] profile [ccs]: publish_address {54.215.58.0:9500}, bound_addresses {10.232.9.80:9500}
```

7. Making the same curl request as 5) still doesn't appear to work as desired. "east1" does make a connection to "west1" on port 9500 (verified via netstat) but it looks like the CCS request again defaults to trying to connect on port 9300 using the internal DNS name or IP of "west1" after the initial connection on port 9500.
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "connect_transport_exception",
        "reason" : "[sea-west-1][10.232.9.80:9300] connect_timeout[30s]"
      }
    ],
    "type" : "transport_exception",
    "reason" : "unable to communicate with remote cluster [cluster_west]",
    "caused_by" : {
      "type" : "connect_transport_exception",
      "reason" : "[sea-west-1][10.232.9.80:9300] connect_timeout[30s]",
      "caused_by" : {
        "type" : "connect_timeout_exception",
        "reason" : "connection timed out: ip-10-232-9-80.us-west-1.compute.internal/10.232.9.80:9300"
      }
    }
  },
  "status" : 500
}
```

**Provide logs (if relevant)**:
Error logged in "east1"
```
[2017-09-13T00:38:44,746][WARN ][o.e.t.RemoteClusterService] [nyc-east-1] failed to update seed list for cluster: cluster_west
org.elasticsearch.transport.ConnectTransportException: [sea-west-1][10.232.9.80:9300] connect_timeout[30s]
        at org.elasticsearch.transport.netty4.Netty4Transport.connectToChannels(Netty4Transport.java:361) ~[?:?]
        at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:548) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.transport.TcpTransport.connectToNode(TcpTransport.java:472) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:332) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.transport.RemoteClusterConnection$ConnectHandler.lambda$collectRemoteNodes$1(RemoteClusterConnection.java:364) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.common.util.CancellableThreads.executeIO(CancellableThreads.java:105) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.transport.RemoteClusterConnection$ConnectHandler.collectRemoteNodes(RemoteClusterConnection.java:354) [elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.transport.RemoteClusterConnection$ConnectHandler$1.doRun(RemoteClusterConnection.java:341) [elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.5.2.jar:5.5.2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.5.2.jar:5.5.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: ip-10-232-9-80.us-west-1.compute.internal/10.232.9.80:9300
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267) ~[?:?]
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[?:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[?:?]
        ... 1 more
.
.
[2017-09-13T00:40:09,393][WARN ][r.suppressed             ] path: /cluster_west:my-index/_search, params: {pretty=, index=cluster_west:my-index}
org.elasticsearch.transport.TransportException: unable to communicate with remote cluster [cluster_west]
        at org.elasticsearch.transport.RemoteClusterService$1.onFailure(RemoteClusterService.java:242) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:67) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.action.ActionListener.onFailure(ActionListener.java:101) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.transport.RemoteClusterConnection$ConnectHandler$1.lambda$doRun$1(RemoteClusterConnection.java:336) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:67) [elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.transport.RemoteClusterConnection$ConnectHandler.collectRemoteNodes(RemoteClusterConnection.java:405) [elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.transport.RemoteClusterConnection$ConnectHandler$1.doRun(RemoteClusterConnection.java:341) [elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.5.2.jar:5.5.2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.5.2.jar:5.5.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: org.elasticsearch.transport.ConnectTransportException: [sea-west-1][10.232.9.80:9300] connect_timeout[30s]
        at org.elasticsearch.transport.netty4.Netty4Transport.connectToChannels(Netty4Transport.java:361) ~[?:?]
        at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:548) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.transport.TcpTransport.connectToNode(TcpTransport.java:472) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:332) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.transport.RemoteClusterConnection$ConnectHandler.lambda$collectRemoteNodes$1(RemoteClusterConnection.java:364) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.common.util.CancellableThreads.executeIO(CancellableThreads.java:105) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.transport.RemoteClusterConnection$ConnectHandler.collectRemoteNodes(RemoteClusterConnection.java:354) ~[elasticsearch-5.5.2.jar:5.5.2]
        ... 8 more
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: ip-10-232-9-80.us-west-1.compute.internal/10.232.9.80:9300
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267) ~[?:?]
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[?:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[?:?]
        ... 1 more
```

**Comment by s1monw** [comment]
I have been thinking about this and from my perspective there needs to be a secure channel between these clusters to communicate otherwise we can't support this. I wonder if a VPN would be the right option here? I mean if you allow a certain profile to be exposed via _ec2:publicIpv4_ it's as good as just using the plublic IP everywhere? There needs to be some way of protecting the exposed services anyway no?

**Comment by s1monw** [comment]
closing this for now given the explain above and the lack of responses
