### ISSUE TITLE
Exception making http rest request when generating password

### ISSUE THREAD

**Issue by depelteau** [elastic/elasticsearch#26631]
**Elasticsearch version**
Version: 6.0.0-beta2, Build: 23ffa4f/2017-08-29T01:53:03.739Z, JVM: 1.8.0_144

**Plugins installed**
X-Pack for Elasticsearch

**JVM version**
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**OS version**
Windows 2016 Server Standard 64bit

**Description of the problem including expected versus actual behavior**:
Unable to generate or enter a password after installing X-Pack. Getting Java exception errors.

**Steps to reproduce**:

 1. Install X-Pack for Elasticsearch
`bin\elasticsearch-plugin install x-pack`

 2. Generate a password with either interactive or auto parameters

`bin\x-pack\setup-passwords.bat auto`
OR
`bin\x-pack\setup-passwords.bat interactive`

 3. 
```
Initiating the setup of reserved user [elastic, kibana, logstash_system]  passwords.
You will be prompted to enter passwords as the process progresses.
Please confirm that you would like to continue [y/N]
```

Press Y

 4. 
Enter password for [elastic]: ********
Reenter password for [elastic]: ********

 5. Both interactive or auto get the same result:

```
Exception making http rest request for user [elastic]
Exception in thread "main" java.io.IOException: No handler found for uri [/_xpack/security/user/elastic/_password] and method [PUT]
        at org.elasticsearch.xpack.security.authc.esnative.tool.CommandLineHttpClient.postURL(CommandLineHttpClient.java:116)
        at org.elasticsearch.xpack.security.authc.esnative.tool.SetupPasswordTool$SetupCommand.changePassword(SetupPasswordTool.java:249)
        at org.elasticsearch.xpack.security.authc.esnative.tool.SetupPasswordTool$SetupCommand.changePasswords(SetupPasswordTool.java:237)
        at org.elasticsearch.xpack.security.authc.esnative.tool.SetupPasswordTool$InteractiveSetup.execute(SetupPasswordTool.java:166)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:69)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.xpack.security.authc.esnative.tool.SetupPasswordTool.main(SetupPasswordTool.java:91)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://10.1.5.60:9200/_xpack/security/user/elastic/_password
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at org.elasticsearch.xpack.security.authc.esnative.tool.CommandLineHttpClient.postURL(CommandLineHttpClient.java:110)
        ... 9 more
```

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
This repository is for open source Elasticsearch only. We do not handle closed X-Pack issues here. Instead, for that, we ask that you report through the [forum](https://discuss.elastic.co).
