### ISSUE TITLE
IntelliJ IDEA 2017.2.3 x64 run  testCase fail

### ISSUE THREAD

**Issue by sshling** [elastic/elasticsearch#26652]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.4.3

**Plugins installed**: none

**JVM version** (`java -version`): 1.8.144

**OS version** (`uname -a` if on a Unix-like system):  windows 7

**Description of the problem including expected versus actual behavior**:

- just clone from github 
- run  "gradle idea"  
- import to idea 
- just test `org.elasticsearch.cluster.ClusterInfoServiceIT#testClusterInfoServiceCollectsInformation`

**The Exception**  :   maybe it's  a IDE or environment problem
```
java.lang.RuntimeException: found jar hell in test classpath

	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:91)
	at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:171)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:592)
Caused by: java.lang.IllegalStateException: jar hell!
duplicate jar on classpath: D:\Program Files\JetBrains\IntelliJ IDEA 2017.2.3\lib\idea_rt.jar;D:\Program Files\JetBrains\IntelliJ IDEA 2017.2.3\plugins\junit\lib\junit-rt.jar;D:\Program Files\JetBrains\IntelliJ IDEA 2017.2.3\plugins\junit\lib\junit5-rt.jar;D:\proJava\jdk1.8.0_144\jre\lib\charsets.jar;D:\proJava\jdk1.8.0_144\jre\lib\deploy.jar;D:\proJava\jdk1.8.0_144\jre\lib\ext\access-bridge-64.jar;D:\proJava\jdk1.8.0_144\jre\lib\ext\cldrdata.jar;D:\proJava\jdk1.8.0_144\jre\lib\ext\dnsns.jar;D:\proJava\jdk1.8.0_144\jre\lib\ext\jaccess.jar;D:\proJava\jdk1.8.0_144\jre\lib\ext\jfxrt.jar;D:\proJava\jdk1.8.0_144\jre\lib\ext\localedata.jar;D:\proJava\jdk1.8.0_144\jre\lib\ext\nashorn.jar;D:\proJava\jdk1.8.0_144\jre\lib\ext\sunec.jar;D:\proJava\jdk1.8.0_144\jre\lib\ext\sunjce_provider.jar;D:\proJava\jdk1.8.0_144\jre\lib\ext\sunmscapi.jar;D:\proJava\jdk1.8.0_144\jre\lib\ext\sunpkcs11.jar;D:\proJava\jdk1.8.0_144\jre\lib\ext\zipfs.jar;D:\proJava\jdk1.8.0_144\jre\lib\javaws.jar;D:\proJava\jdk1.8.0_144\jre\lib\jce.jar;D:\proJava\jdk1.8.0_144\jre\lib\jfr.jar;D:\proJava\jdk1.8.0_144\jre\lib\jfxswt.jar;D:\proJava\jdk1.8.0_144\jre\lib\jsse.jar;D:\proJava\jdk1.8.0_144\jre\lib\management-agent.jar;D:\proJava\jdk1.8.0_144\jre\lib\plugin.jar;D:\proJava\jdk1.8.0_144\jre\lib\resources.jar;D:\proJava\jdk1.8.0_144\jre\lib\rt.jar;D:\ws\open\elasticsearch\core\build-idea\classes\test;D:\ws\open\elasticsearch\core\build-idea\classes\main;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-core\6.5.1\64ba6eab21a7dd5d80b55632d4bb09be4f1ea7e1\lucene-core-6.5.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-analyzers-common\6.5.1\39dbaaea114a1be3c52f2faba64a36323d95ebc2\lucene-analyzers-common-6.5.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-backward-codecs\6.5.1\e5bc976457f3217b74cf35af8747ad664219c25e\lucene-backward-codecs-6.5.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-grouping\6.5.1\4eff2dbfd60667da8961070c693e534fce56c3ea\lucene-grouping-6.5.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-highlighter\6.5.1\277fa328c1c6200eab3aa811bd203994a62225b4\lucene-highlighter-6.5.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-join\6.5.1\850bb5c330fca052dbf4b191b05c9f7806517af7\lucene-join-6.5.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-memory\6.5.1\b495b8129ce8ea6e86e396574e1932108aabdb4c\lucene-memory-6.5.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-misc\6.5.1\3c18dce20c432c5caa435ed000e8366cc0630368\lucene-misc-6.5.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-queries\6.5.1\48f80f7b52f4ded001db8a1b7faa0b911955e9cb\lucene-queries-6.5.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-queryparser\6.5.1\d93fe8eabd82c8f6951eeece76a6a3faf6ff0471\lucene-queryparser-6.5.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-sandbox\6.5.1\1d7765bcaa2dcbee8083a4ecad74783849d83b4\lucene-sandbox-6.5.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-spatial\6.5.1\b7d2b87ee7da03324fc117f8634862243dfd2389\lucene-spatial-6.5.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-spatial-extras\6.5.1\f58d228e73dcf28f0dcebe95661991361155c753\lucene-spatial-extras-6.5.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-spatial3d\6.5.1\31b64548b138c34c4d88f7d628bdeba17b3c2b16\lucene-spatial3d-6.5.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-suggest\6.5.1\a9bcff6fec09a2b5d4ae82acfdc65db15bc3ecd6\lucene-suggest-6.5.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.elasticsearch\securesm\1.1\1e423447d020041534be94c0f31a49fbdc1f2950\securesm-1.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\net.sf.jopt-simple\jopt-simple\5.0.2\98cafc6081d5632b61be2c9e60650b64ddbc637c\jopt-simple-5.0.2.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.carrotsearch\hppc\0.7.1\8b5057f74ea378c0150a1860874a3ebdcb713767\hppc-0.7.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\joda-time\joda-time\2.9.5\5f01da7306363fad2028b916f3eab926262de928\joda-time-2.9.5.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.yaml\snakeyaml\1.15\3b132bea69e8ee099f416044970997bde80f4ea6\snakeyaml-1.15.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-core\2.8.6\2ef7b1cc34de149600f5e75bc2d5bf40de894e60\jackson-core-2.8.6.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.dataformat\jackson-dataformat-smile\2.8.6\71590ad45cee21249774e2f93e5eca66e446cef3\jackson-dataformat-smile-2.8.6.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.dataformat\jackson-dataformat-yaml\2.8.6\8bd44d50f9a6cdff9c7578ea39d524eb519e35ab\jackson-dataformat-yaml-2.8.6.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.dataformat\jackson-dataformat-cbor\2.8.6\b88721371cfa2d7242bb5e52fe70861aa061c050\jackson-dataformat-cbor-2.8.6.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.tdunning\t-digest\3.0\84ccf145ac2215e6bfa63baa3101c0af41017cfc\t-digest-3.0.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.hdrhistogram\HdrHistogram\2.1.9\e4631ce165eb400edecfa32e03d3f1be53dee754\HdrHistogram-2.1.9.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.locationtech.spatial4j\spatial4j\0.6\21b15310bddcfd8c72611c180f20cf23279809a3\spatial4j-0.6.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.vividsolutions\jts\1.13\3ccfb9b60f04d71add996a666ceb8902904fd805\jts-1.13.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-api\2.8.2\e590eeb783348ce8ddef205b82127f9084d82bf3\log4j-api-2.8.2.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-core\2.8.2\979fc0cf8460302e4ffbfe38c1b66a99450b0bb7\log4j-core-2.8.2.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-1.2-api\2.8.2\f1543534b8413aac91fa54d1fff65dfff76818cd\log4j-1.2-api-2.8.2.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.elasticsearch\jna\4.4.0\6edc9b4514969d768039acf43f04210b15658cd7\jna-4.4.0.jar;D:\ws\open\elasticsearch\test\framework\build-idea\classes\main;C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.google.jimfs\jimfs\1.1\8fbd0579dc68aba6186935cc1bee21d2f3e7ec1c\jimfs-1.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.google.guava\guava\18.0\cce0823396aa693798f8882e64213b1772032b09\guava-18.0.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\com.carrotsearch.randomizedtesting\randomizedtesting-runner\2.5.0\2d00ff1042ae258f33830f26f9b30fc3a43d37e1\randomizedtesting-runner-2.5.0.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\junit\junit\4.11\4e031bb61df09069aeb2bffb4019e7a5034a4ee0\junit-4.11.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.hamcrest\hamcrest-all\1.3\63a21ebc981131004ad02e0434e799fd7f3a8d5a\hamcrest-all-1.3.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-test-framework\6.5.1\85f0b6993b0c269e92f157fa8225cf8b158d2a19\lucene-test-framework-6.5.1.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.lucene\lucene-codecs\6.5.1\9f70b551c0f3798a82fa5dd66fe051671eba81f7\lucene-codecs-6.5.1.jar;D:\ws\open\elasticsearch\client\rest\build-idea\classes\main;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpclient\4.5.2\733db77aa8d9b2d68015189df76ab06304406e50\httpclient-4.5.2.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpcore\4.4.5\e7501a1b34325abb00d17dde96150604a0658b54\httpcore-4.4.5.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\commons-logging\commons-logging\1.1.3\f6f66e966c70a83ffbdb6f17a0919eaf7c8aca7f\commons-logging-1.1.3.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\commons-codec\commons-codec\1.10\4b95f4897fa13f2cd904aee711aeafc0c5295cd8\commons-codec-1.10.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.elasticsearch\securemock\1.2\98201d4ad5ac93f6b415ae9172d52b5e7cda490e\securemock-1.2.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpasyncclient\4.1.2\95aa3e6fb520191a0970a73cf09f62948ee614be\httpasyncclient-4.1.2.jar;C:\Users\admin\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpcore-nio\4.4.5\f4be009e7505f6ceddf21e7960c759f413f15056\httpcore-nio-4.4.5.jar;D:\Program Files\JetBrains\IntelliJ IDEA 2017.2.3\lib\idea_rt.jar
	at org.elasticsearch.bootstrap.JarHell.parseClassPath(JarHell.java:142)
	at org.elasticsearch.bootstrap.JarHell.parseClassPath(JarHell.java:99)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:90)
	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:89)
	... 4 more


```

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
