### ISSUE TITLE
[CI] UpgradeClusterClientYamlTestSuiteIT warning header missing

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#26689]
```
REPRODUCE WITH: gradle :qa:rolling-upgrade:v5.0.0#oldClusterTestRunner -Dtests.seed=502F0C5BE273AE6A -Dtests.class=org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT -Dtests.method="test {p0=old_cluster/10_basic/Index data, search, and create things in the cluster state that we'll validate are there after the ugprade}" -Dtests.security.manager=true -Dtests.locale=ar-JO -Dtests.timezone=Europe/Ljubljana -Dtests.rest.suite=old_cluster
FAILURE 2.40s | UpgradeClusterClientYamlTestSuiteIT.test {p0=old_cluster/10_basic/Index data, search, and create things in the cluster state that we'll validate are there after the ugprade} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [old_cluster/10_basic:88]: did not get expected warning header [
   >    The stored search template API is deprecated. Use stored scripts instead.
   > ]
   >    at __randomizedtesting.SeedInfo.seed([502F0C5BE273AE6A:D87B33814C8FC392]:0)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:350)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:330)
   >    at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.lang.AssertionError: did not get expected warning header [
   >    The stored search template API is deprecated. Use stored scripts instead.
   > ]
   >    at org.elasticsearch.test.rest.yaml.section.DoSection.checkWarningHeaders(DoSection.java:290)
   >    at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:234)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:346)
   >    ... 38 more
  2> NOTE: leaving temporary files on disk at: /home/mvg/dev/projects/elasticsearch/5.x/elasticsearch/qa/rolling-upgrade/build/testrun/v5.0.0#oldClusterTestRunner/J0/temp/org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT_502F0C5BE273AE6A-001
```

This test failure does reproduce.

Build urls: 
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+bwc-tests/167/consoleText
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+bwc-tests/166/console

**Comment by colings86** [comment]
@martijnvg I think this problem is now solved as the test is skipped not when running against clusters which are < 5.6.0 (see https://github.com/elastic/elasticsearch/blob/5.6/qa/rolling-upgrade/src/test/resources/rest-api-spec/test/old_cluster/10_basic.yaml#L4-L6). So this could be closed now?

**Comment by jpountz** [comment]
Agreed with Colin, this seems to have been fixed in https://github.com/elastic/elasticsearch/pull/26713. Closing. Feel free to reopen if there are leftovers to fix.
