### ISSUE TITLE
Broken mapper-murmur3 java plugin for local nodes

### ISSUE THREAD

**Issue by AlexKolpa** [elastic/elasticsearch#26709]
Bug report:

**Elasticsearch version**: 5.3.3

**Plugins installed**: [analysis-icu, x-pack, mapper-murmur3]

**JVM version**: 1.8.0_144

**OS version**: 4.12.8-2-ARCH

**Description of the problem including expected versus actual behavior**:

Since 5.2.0, the signature of `FieldMapper.parseCreateField` has changed from using `Field` to `IndexableField` (see 1792f1bb2b58aa6502466b3a06a9fb138e61b447 for change).
Additionally, in v5.0.0-beta1 the package for `TypeParsers` was changed from `org.elasticsearch.index.mapper.core` to `org.elasticsearch.index.mapper` (see 0d6ac57acf0d94315abd5d2dda48aac30e56246a for change).

Because the `org.elasticsearch.plugin:mapper-murmur3` is still on `5.0.0-alpha5`, it is not compatible with any release since ` v5.0.0-beta1` due to the aforementioned incompatible changes. Ideally a new version for this plugin would be released that is compatible with the latest versions. Right now we are forced to fork this plugin for our tests, where we set up a local node with these plugins.

**Steps to reproduce**:

Using `org.elasticsearch:elasticsearch:5.3.3` and `org.elasticsearch.plugin:mapper-murmur3:5.0.0-alpha5`, extend and initialize a `Node` as follows:

```java
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.node.InternalSettingsPreparer;
import org.elasticsearch.node.Node;
import org.elasticsearch.plugin.mapper.MapperMurmur3Plugin;

private class NodeWithPlugins extends Node {
	NodeWithPlugins(Settings settings, Collection<Class<? extends Plugin>> classpathPlugins) {
		super(InternalSettingsPreparer.prepareEnvironment(settings, null), classpathPlugins);
	}

	public static void main(String[] args) {
		Node node = new NodeWithPlugins(<settings>, new ArrayList<>(MapperMurmur3Plugin.class));
		node.start();
	}
}
```

**Provide logs (if relevant)**: Here is the ClassDefNotFoundError:

```java
java.lang.NoClassDefFoundError: org/elasticsearch/index/mapper/core/TypeParsers
	at org.elasticsearch.index.mapper.murmur3.Murmur3FieldMapper$TypeParser.parse(Murmur3FieldMapper.java:99)
	at org.elasticsearch.index.mapper.TypeParsers.parseMultiField(TypeParsers.java:340)
	at org.elasticsearch.index.mapper.TypeParsers.parseField(TypeParsers.java:274)
	at org.elasticsearch.index.mapper.KeywordFieldMapper$TypeParser.parse(KeywordFieldMapper.java:158)
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:277)
	at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:199)
	at org.elasticsearch.index.mapper.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:102)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:111)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:91)
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:327)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:258)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1.execute(MetaDataCreateIndexService.java:371)
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
	at org.elasticsearch.cluster.service.ClusterService.executeTasks(ClusterService.java:679)
	at org.elasticsearch.cluster.service.ClusterService.calculateTaskOutputs(ClusterService.java:658)
	at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:617)
	at org.elasticsearch.cluster.service.ClusterService$UpdateTask.run(ClusterService.java:1117)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:238)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:201)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.index.mapper.core.TypeParsers
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more
```

**Comment by s1monw** [comment]
we [don't support embedded](https://www.elastic.co/blog/elasticsearch-the-server) nodes anymore. That's also why we don't publish these artifacts anymore.

**Comment by AlexKolpa** [comment]
Ah, I wasn't aware of that. Thanks for the update!
