### ISSUE TITLE
TranslogWriter.assertNoSeqNumberConflict failure

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#26710]
I got this locally when trying to reproduce with https://github.com/elastic/elasticsearch/issues/26707. I got it with:
```
 gradle :core:integTest -Dtests.seed=B93BBCA37C85D2DE -Dtests.class=org.elasticsearch.discovery.ClusterDisruptionIT -Dtests.method="testAckedIndexing" -Dtests.security.manager=true -Dtests.locale=sk -Dtests.timezone=GB
```

I'll try again and see if it reproduces but even if it does I'm not sure shipping my laptop to @bleskes is an option.

```
  2> sep 19, 2017 2:47:15 PM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
  2> WARNING: Uncaught exception in thread: Thread[elasticsearch[node_t1][generic][T#6],5,TGRP-ClusterDisruptionIT]
  2> java.lang.AssertionError: seqNo [2] was processed twice in generation [1], with different data. prvOp [Index{id='9', type='type', seqNo=2, primaryTerm=1}], newOp [Index{id='10', type='type', seqNo=2, primaryTerm=2}]
  2>    at __randomizedtesting.SeedInfo.seed([B93BBCA37C85D2DE]:0)
  2>    at org.elasticsearch.index.translog.TranslogWriter.assertNoSeqNumberConflict(TranslogWriter.java:222)
  2>    at org.elasticsearch.index.translog.TranslogWriter.add(TranslogWriter.java:207)
  2>    at org.elasticsearch.index.translog.Translog.add(Translog.java:505)
  2>    at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:690)
  2>    at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:702)
  2>    at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:671)
  2>    at org.elasticsearch.index.shard.IndexShard.applyTranslogOperation(IndexShard.java:1189)
  2>    at org.elasticsearch.indices.recovery.RecoveryTarget.indexTranslogOperations(RecoveryTarget.java:395)
  2>    at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$TranslogOperationsRequestHandler.messageReceived(PeerRecoveryTargetService.java:442)
  2>    at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$TranslogOperationsRequestHandler.messageReceived(PeerRecoveryTargetService.java:433)
  2>    at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30)
  2>    at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:67)
  2>    at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1525)
  2>    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
  2>    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  2>    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  2>    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  2>    at java.lang.Thread.run(Thread.java:745)
  2> Caused by: java.lang.RuntimeException: stack capture previous op
  2>    at org.elasticsearch.index.translog.TranslogWriter.assertNoSeqNumberConflict(TranslogWriter.java:226)
  2>    ... 17 more
```

https://gist.github.com/nik9000/64a24a1ee19855658c967681c67cb155

**Comment by jasontedor** [comment]
I can definitively say that this is caused solely by #26707.
