### ISSUE TITLE
[CI] Failure of CoreFullClusterRestartIT testRecovery

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#26733]
This failed in https://internal-ci.elastic.co/job/elastic+x-pack-elasticsearch+6.0+intake/49/console

The error is:

```
09:18:21 FAILURE 0.15s | CoreFullClusterRestartIT.testRecovery <<< FAILURES!
09:18:21    > Throwable #1: java.lang.AssertionError: expected at least 1 current segment after translog recovery. Actual: 0
09:18:21    > 	at __randomizedtesting.SeedInfo.seed([F2C7DF2B4633D36E:3337A6876B6319C9]:0)
09:18:21    > 	at org.elasticsearch.upgrades.FullClusterRestartIT.testRecovery(FullClusterRestartIT.java:670)
09:18:21    > 	at java.lang.Thread.run(Thread.java:748)
```

This reproduces locally for me with:

```
REPRODUCE WITH: gradle :x-pack-elasticsearch:qa:full-cluster-restart:with-system-key:v5.6.2-SNAPSHOT#upgradedClusterTestRunner \
  -Dtests.seed=F2C7DF2B4633D36E \
  -Dtests.class=org.elasticsearch.xpack.restart.CoreFullClusterRestartIT \
  -Dtests.method="testRecovery" \
  -Dtests.security.manager=true \
  -Dtests.locale=ja \
  -Dtests.timezone=America/Indiana/Knox
```

**Comment by jasontedor** [comment]
This is an X-Pack test so should not be in this repository.
