### ISSUE TITLE
Online plugin Installation looks for sha1, we now only produce sha512

### ISSUE THREAD

**Issue by skearns64** [elastic/elasticsearch#26746]
In 6.0.0 RC1 BC1, when installing a plugin that gets downloaded, the plugin itself downloads fine, but the plugin installer fails to retrieve the plugin's .sha1 file. This appears to be because we switched to producing sha512 in the build system. 

```
 ES_JAVA_OPTS="-Des.plugins.staging=<staging build id>" bin/elasticsearch-plugin install repository-s3
-> Downloading repository-s3 from elastic
[=================================================] 100%   
Exception in thread "main" java.io.FileNotFoundException: https://staging.elastic.co/6.0.0-rc1-c8f2d2ee/downloads/elasticsearch-plugins/repository-s3/repository-s3-6.0.0-rc1.zip.sha1
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1045)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZipAndChecksum(InstallPluginCommand.java:372)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:221)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:211)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:202)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

**Comment by dliappis** [comment]
@skearns64 I am hitting this when trying to build Docker images with 5.6.2-BC1:

```
Step 12/20 : RUN for PLUGIN in x-pack ingest-user-agent ingest-geoip; do       eval ES_JAVA_OPTS="-Des.plugins.staging=cb620858" elasticsearch-plugin install --batch "$PLUGIN";     done
 ---> Running in ad92634ba17f
-> Downloading x-pack from elastic
[=================================================] 100%?? 
Exception in thread "main" java.io.FileNotFoundException: https://staging.elastic.co/5.6.2-cb620858/downloads/elasticsearch-plugins/x-pack/x-pack-5.6.2.zip.sha1
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at java.net.URL.openStream(URL.java:1045)
        at org.elasticsearch.plugins.InstallPluginCommand.downloadZipAndChecksum(InstallPluginCommand.java:375)
        at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:225)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:215)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:201)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

I guess the PRs to move to sha512 haven't been backported to 5.6/5.5; does this warrant a new issue or just re-opening this, as I don't see a version label.

**Comment by jasontedor** [comment]
@dliappis I will backport the change to 5.6.

**Comment by jasontedor** [comment]
@dliappis I have backported this to 5.6.

**Comment by drewr** [comment]
Thanks all for catching and working on this. I should have seen it coming when creating elastic/release-manager#153 and raised some downstream visibility. ⛵️

**Comment by dliappis** [comment]
@jasontedor Confirming that the latest `5.6.2-0836ee74` pulls plugins correctly and uses the right sha512 digests.
