### ISSUE TITLE
[CI] org.elasticsearch.index.reindex.CancelTests

### ISSUE THREAD

**Issue by andyb-elastic** [elastic/elasticsearch#26758]
It looks like the reindex response times out because some slice tasks don't complete in time (though they do appear to all acknowledge the cancellation). I couldn't find a cause. Neither of these reproduce, and they fail very rarely.

1. 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.5+multijob-unix-compatibility/os=fedora/141

```
ERROR   32.1s J0 | CancelTests.testUpdateByQueryCancelWithWorkers <<< FAILURES!
   > Throwable #1: java.lang.RuntimeException: Exception while waiting for the response. Running tasks: {"tasks":{"ip0U-jljTBy-m2SBtaJb1g:2794":{"node":"ip0U-jljTBy-m2SBtaJb1g","id":2794,"type":"transport","action":"indices:data/write/update/byquery","status":{"slice_id":3,"total":102,"updated":1,"created":0,"deleted":0,"batches":1,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":0.0,"canceled":"by user request","throttled_until_millis":9223372006812},"description":"update-by-query [reindex-cancel-index]","start_time_in_millis":1505837598023,"running_time_in_nanos":30191506121,"cancellable":true,"parent_task_id":"ip0U-jljTBy-m2SBtaJb1g:2754"},"ip0U-jljTBy-m2SBtaJb1g:2796":{"node":"ip0U-jljTBy-m2SBtaJb1g","id":2796,"type":"transport","action":"indices:data/write/update/byquery","status":{"slice_id":4,"total":62,"updated":1,"created":0,"deleted":0,"batches":1,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":0.0,"canceled":"by user request","throttled_until_millis":9223372006813},"description":"update-by-query [reindex-cancel-index]","start_time_in_millis":1505837598024,"running_time_in_nanos":30190750346,"cancellable":true,"parent_task_id":"ip0U-jljTBy-m2SBtaJb1g:2754"}}}
   > 	at __randomizedtesting.SeedInfo.seed([75824B2D7BD47309:BA7D75A63797A55B]:0)
   > 	at org.elasticsearch.index.reindex.CancelTests.testCancel(CancelTests.java:168)
   > 	at org.elasticsearch.index.reindex.CancelTests.testUpdateByQueryCancelWithWorkers(CancelTests.java:249)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.util.concurrent.TimeoutException: Timeout waiting for task.
   > 	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:232)
   > 	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:67)
   > 	at org.elasticsearch.index.reindex.CancelTests.testCancel(CancelTests.java:164)
   > 	... 38 more
```

```
  2> REPRODUCE WITH: gradle :modules:reindex:test -Dtests.seed=75824B2D7BD47309 -Dtests.class=org.elasticsearch.index.reindex.CancelTests -Dtests.method="testUpdateByQueryCancelWithWorkers" -Dtests.security.manager=true -Dtests.locale=vi -Dtests.timezone=Africa/Addis_Ababa
```

[build-141-CancelTests.txt](https://github.com/elastic/elasticsearch/files/1325536/build-141-CancelTests.txt)

2. 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.5+multijob-unix-compatibility/os=fedora/147

```
ERROR   30.8s J0 | CancelTests.testDeleteByQueryCancelWithWorkers <<< FAILURES!
   > Throwable #1: java.lang.RuntimeException: Exception while waiting for the response. Running tasks: {"tasks":{"hyCyfCVLTeezK3EWp56Kkg:5514":{"node":"hyCyfCVLTeezK3EWp56Kkg","id":5514,"type":"transport","action":"indices:data/write/delete/byquery","status":{"slice_id":4,"total":22,"updated":0,"created":0,"deleted":10,"batches":10,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":0.0,"canceled":"by user request","throttled_until_millis":9223372006847},"description":"delete-by-query [reindex-cancel-index]","start_time_in_millis":1506007215407,"running_time_in_nanos":30092761872,"cancellable":true,"parent_task_id":"hyCyfCVLTeezK3EWp56Kkg:5491"},"hyCyfCVLTeezK3EWp56Kkg:5492":{"node":"hyCyfCVLTeezK3EWp56Kkg","id":5492,"type":"transport","action":"indices:data/write/delete/byquery","status":{"slice_id":0,"total":20,"updated":0,"created":0,"deleted":13,"batches":13,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":0.0,"canceled":"by user request","throttled_until_millis":9223372006847},"description":"delete-by-query [reindex-cancel-index]","start_time_in_millis":1506007215384,"running_time_in_nanos":30116660285,"cancellable":true,"parent_task_id":"hyCyfCVLTeezK3EWp56Kkg:5491"}}}
   > 	at __randomizedtesting.SeedInfo.seed([C3AA7D4DC8ACFF46:8CDCB30F1668EBA1]:0)
   > 	at org.elasticsearch.index.reindex.CancelTests.testCancel(CancelTests.java:168)
   > 	at org.elasticsearch.index.reindex.CancelTests.testDeleteByQueryCancelWithWorkers(CancelTests.java:259)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.util.concurrent.TimeoutException: Timeout waiting for task.
   > 	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:232)
   > 	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:67)
   > 	at org.elasticsearch.index.reindex.CancelTests.testCancel(CancelTests.java:164)
   > 	... 38 more
```

```
  2> REPRODUCE WITH: gradle :modules:reindex:test -Dtests.seed=C3AA7D4DC8ACFF46 -Dtests.class=org.elasticsearch.index.reindex.CancelTests -Dtests.method="testDeleteByQueryCancelWithWorkers" -Dtests.security.manager=true -Dtests.locale=sl-SI -Dtests.timezone=Europe/Zurich
```

[build-147-CancelTests.txt](https://github.com/elastic/elasticsearch/files/1325537/build-147-CancelTests.txt)

**Comment by andyb-elastic** [comment]
Another one in 6.1

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.1+aggressive-opts/121/console

[build-121-CancelTests.testReindexCancelWithWorkers.txt](https://github.com/elastic/elasticsearch/files/1598553/build-121-CancelTests.testReindexCancelWithWorkers.txt)

**Comment by andyb-elastic** [comment]
Another in 6.1

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.1+multijob-unix-compatibility/os=opensuse/185/console

[build-185-CancelTests.txt](https://github.com/elastic/elasticsearch/files/1635928/build-185-CancelTests.txt)

**Comment by nik9000** [comment]
I'm going to snag this and see if I can reproduce it.

**Comment by nik9000** [comment]
Of course I can't reproduce it. But I've pushed some code that'll give us more information the next time it fails....

**Comment by nik9000** [comment]
I pushed 6f64e9728bdd1b6fd1a4c5e8648384e4ff00a472 to see if that'll track down the cause. Then it failed locally for me while I was testing the backport, tripping the new assertion! Maybe I found it!

**Comment by nik9000** [comment]
I'm going to let this one stay closed. It it occurs again I'll reopen.
