### ISSUE TITLE
Cross cluster search sometimes fails

### ISSUE THREAD

**Issue by greentruff** [elastic/elasticsearch#26833]
**Elasticsearch version**: Version: 5.6.2, Build: 57e20f3/2017-09-23T13:16:45.703Z, JVM: 1.8.0_144

**Plugins installed**: []

**Description of the problem including expected versus actual behavior**:
When doing a cross-cluster search on a remote alias, the remote master will drop encounter a serialization error and will drop the connection with a remote node.

The client receives the following error: 
```
{"error":{"root_cause":[{"type":"transport_serialization_exception","reason":"Failed to deserialize response of type [org.elasticsearch.search.fetch.QueryFetchSearchResult]"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"concrete-index","node":"a1P-CIioRmeJ96CqoWo0gA","reason":{"type":"transport_serialization_exception","reason":"Failed to deserialize response of type [org.elasticsearch.search.fetch.QueryFetchSearchResult]","caused_by":{"type":"index_out_of_bounds_exception","reason":"readerIndex(45) + length(1) exceeds writerIndex(45): UnpooledDuplicatedByteBuf(ridx: 45, widx: 45, cap: 65536, unwrapped: PooledHeapByteBuf(ridx: 6, widx: 45, cap: 65536))"}}}]},"status":500}
```

This issue does not always reproduce but I have noticed the following:
- For an index with a one shard and one replica, it happens if there are three cluster nodes but not two.
- It can be possible to mitigate the problem by assigning certain nodes to master and making them gateway nodes.
- The issue sometimes triggers on a concrete index although less reliably

**Steps to reproduce**:

1. Setup clusters

Local client cluster:
```
$ elasticsearch-5.6.2/bin/elasticsearch \
  -Epath.data=./data.client \
  -Epath.logs=logs.client \
  -Ecluster.name=client \
  -Etransport.tcp.port=9300 \
  -Ehttp.port=9200 \
  -d
```

Remote cluster:
```
$ elasticsearch-5.6.2/bin/elasticsearch \
  -Epath.data=./data.remote1 \
  -Epath.logs=./logs.remote1 \
  -Ecluster.name=remote \
  -Etransport.tcp.port=9310 \
  -Ehttp.port=9210 \
  -Ediscovery.zen.ping.unicast.hosts=localhost:9320 \
  -d
$ elasticsearch-5.6.2/bin/elasticsearch \
  -Epath.data=./data.remote2 \
  -Epath.logs=./logs.remote2 \
  -Ecluster.name=remote \
  -Etransport.tcp.port=9320 \
  -Ehttp.port=9220 \
  -Ediscovery.zen.ping.unicast.hosts=localhost:9310 \
  -d
$ elasticsearch-5.6.2/bin/elasticsearch \
  -Epath.data=./data.remote3 \
  -Epath.logs=./logs.remote3 \
  -Ecluster.name=remote \
  -Etransport.tcp.port=9330 \
  -Ehttp.port=9230 \
  -Ediscovery.zen.ping.unicast.hosts=localhost:9310 \
  -d
```

2. Wait for the nodes to start
3. Add a seed for cross cluster search to the local node
```
curl -XPUT 'http://localhost:9200/_cluster/settings?pretty' -H 'Content-Type: application/json' -d'
{
  "transient": {
    "search.remote.remote.seeds": "127.0.0.1:9310"
  }
}'
```
4. Create the remote index
```
curl -XPUT 'http://localhost:9210/concrete-index?pretty' -H 'Content-Type: application/json' -d'
{
    "settings" : {
        "index" : {
            "number_of_shards" : 1,
            "number_of_replicas" : 1
        }
    },
    "aliases" : {
        "alias" : {}
    }
}'
```

5. Execute a search
```
curl 'http://localhost:9200/remote:alias/_search?pretty'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "transport_serialization_exception",
        "reason" : "Failed to deserialize response of type [org.elasticsearch.search.fetch.QueryFetchSearchResult]"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "concrete-index",
        "node" : "D7hySVoNTzK41TZdXsYElA",
        "reason" : {
          "type" : "transport_serialization_exception",
          "reason" : "Failed to deserialize response of type [org.elasticsearch.search.fetch.QueryFetchSearchResult]",
          "caused_by" : {
            "type" : "index_out_of_bounds_exception",
            "reason" : "readerIndex(45) + length(1) exceeds writerIndex(45): UnpooledDuplicatedByteBuf(ridx: 45, widx: 45, cap: 65536, unwrapped: PooledHeapByteBuf(ridx: 6, widx: 45, cap: 65536))"
          }
        }
      }
    ]
  },
  "status" : 500
}
```

**Comment by greentruff** [comment]
I have experimented with this issue a bit more and I have noticed that the behavior does not seem linked to aliases. Instead, it seems linked to whether the gateway node the client node communicates with has the data being requested. I'll update the issue description accordingly.

**Comment by javanna** [comment]
thanks a lot for opening this issue @greentruff . I was just able to reproduce this. I will dig and find out what causes it.

**Comment by greentruff** [comment]
Ok thanks @javanna. If it helps at all, I was able to reproduce the issue more reliably by having a single gateway node which is not a data node.

**Comment by javanna** [comment]
Attaching the stacktrace for future reference:

```
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(45) + length(1) exceeds writerIndex(45): UnpooledDuplicatedByteBuf(ridx: 45, widx: 45, cap: 65536, unwrapped: PooledHeapByteBuf(ridx: 6, widx: 45, cap: 65536))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396) ~[?:?]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687) ~[?:?]
	at org.elasticsearch.transport.netty4.ByteBufStreamInput.readByte(ByteBufStreamInput.java:135) ~[?:?]
	at org.elasticsearch.common.io.stream.FilterStreamInput.readByte(FilterStreamInput.java:40) ~[elasticsearch-5.6.2.jar:5.6.2]
	at org.elasticsearch.common.io.stream.StreamInput.readInt(StreamInput.java:173) ~[elasticsearch-5.6.2.jar:5.6.2]
	at org.elasticsearch.common.io.stream.StreamInput.readLong(StreamInput.java:215) ~[elasticsearch-5.6.2.jar:5.6.2]
	at org.elasticsearch.search.fetch.FetchSearchResult.readFrom(FetchSearchResult.java:90) ~[elasticsearch-5.6.2.jar:5.6.2]
	at org.elasticsearch.search.fetch.FetchSearchResult.readFetchSearchResult(FetchSearchResult.java:83) ~[elasticsearch-5.6.2.jar:5.6.2]
	at org.elasticsearch.search.fetch.QueryFetchSearchResult.readFrom(QueryFetchSearchResult.java:90) ~[elasticsearch-5.6.2.jar:5.6.2]
	at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:1417) ~[elasticsearch-5.6.2.jar:5.6.2]
```

**Comment by javanna** [comment]
hi @greentruff thanks again for reporting this. Turns out it was happening only when search went to a single shard. When have an optimization there to perform query and fetch in the same round rather than in separate rounds, but the proxying layer didn't support that optimization hence whenever you went through a gateway node, the response couldn't be serialized back to the coordinating node.

**Comment by greentruff** [comment]
Thanks a lot for the speedy fix !

**Comment by ramramra** [comment]
Hi Javanna 
I face the issue in cross cluster search in my environment the error code shows  503 handshake issue .Herei am using the same authority certificates i am using both the clusters but still i am facing the error in cross cluster connection could you response  ASAP
