### ISSUE TITLE
Elasticsearch 5.6.2 crashes on CentOS 7

### ISSUE THREAD

**Issue by larsuhartmann** [elastic/elasticsearch#26877]
**Elasticsearch version** (`bin/elasticsearch --version`): Version: 5.6.2, Build: 57e20f3/2017-09-23T13:16:45.703Z, JVM: 1.8.0_144

**Plugins installed**: []

**JVM version** (`java -version`): openjdk version "1.8.0_144"

**OS version** (`uname -a` if on a Unix-like system): 3.10.0-693.2.2.el7.x86_64

**Description of the problem including expected versus actual behavior**:

Elasticsearch won't start on CentOS 7

the log shows the following:

org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: plugin [mapper-attachments] is incompatible with version [5.6.2]; was designed for version [5.6.0]

**Steps to reproduce**:

**Provide logs (if relevant)**:

[2017-10-04T09:17:14,727][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: plugin [mapper-attachments] is incompatible with version [5.6.2]; was designed for version [5.6.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.2.jar:5.6.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.2.jar:5.6.2]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.6.2.jar:5.6.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.2.jar:5.6.2]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.2.jar:5.6.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.2.jar:5.6.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.2.jar:5.6.2]
Caused by: java.lang.IllegalArgumentException: plugin [mapper-attachments] is incompatible with version [5.6.2]; was designed for version [5.6.0]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146) ~[elasticsearch-5.6.2.jar:5.6.2]
        at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:76) ~[elasticsearch-5.6.2.jar:5.6.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:168) ~[elasticsearch-5.6.2.jar:5.6.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.2.jar:5.6.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.2.jar:5.6.2]

**Comment by tvernum** [comment]
How did you install elasticsearch-5.6.2 ?

- Did you upgrade an existing installation?
- Did you install from a `.zip`, `.tgz` or `.rpm`?

**Comment by larsuhartmann** [comment]
i upgraded using yum update using the official centos repo

**Comment by larsuhartmann** [comment]
also downgrading to 5.6.0 seems to "fix" the problem

**Comment by tvernum** [comment]
It looks like you didn't upgrade your plugins.
The upgrade instructions are here: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/rolling-upgrades.html
Step 4 requires that you install new versions of all plugins.

**Comment by tvernum** [comment]
I'm going to close this because it doesn't look like it's actually a bug.
Please re-open it if the problem still exists after you reinstall your plugins,

**Comment by larsuhartmann** [comment]
Calling /usr/share/elasticsearch/bin/elasticsearch-plugin  list

gives me:
mapper-attachments
WARNING: plugin [mapper-attachments] is incompatible with version [5.6.2]; was designed for version [5.6.0]

**Comment by larsuhartmann** [comment]
Thanks for your help!
