### ISSUE TITLE
java.lang.NoClassDefFoundError: org/elasticsearch/common/transport/TransportAddress

### ISSUE THREAD

**Issue by Canappeco** [elastic/elasticsearch#26960]
**Describe the feature**:
I am using `mvn package` to build a jar and want to run the main function in the jar. `mvn package` is successful, but when I run `java -classpath ./target/socket-server-1.0-SNAPSHOT.jar cn.zmhappy.es.Server`, something bad happened as follow:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/common/transport/TransportAddress
        at cn.faceall.es.Server.main(Server.java:52)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.common.transport.TransportAddress
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more
```

my pom.xml:
```
<dependencies>
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>5.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>transport</artifactId>
            <version>5.3.0</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20160810</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.8.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.8.2</version>
        </dependency>
</dependencies>
```

I try to search in `~/.m2/repository/org/elasticsearch/`, but I can't find `common` under this directory. Besides, the application can run successfully locally. I wonder how to deal with this problem.

**Elasticsearch version** (`bin/elasticsearch --version`): 5.3.0
**JVM version** (`java -version`): 1.8.0_144

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
