### ISSUE TITLE
Elasticsearch does not start when launched from a symlinked directory. 

### ISSUE THREAD

**Issue by quijote** [elastic/elasticsearch#26966]
**Elasticsearch version** (`bin/elasticsearch --version`): Version: 5.6.3, Build: 1a2f265/2017-10-06T20:33:39.012Z, JVM: 1.8.0_144

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_144

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**:
Elasticsearch does not start when launched from a symlinked directory. 

	C:\temp\elastic\elasticsearch-5.6.3>bin\elasticsearch
	[2017-10-11T14:01:44,342][INFO ][o.e.n.Node               ] [] initializing ...
	[2017-10-11T14:01:44,374][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
	org.elasticsearch.bootstrap.StartupException: java.security.AccessControlException: access denied ("java.io.FilePermission" "D:\temp\elastic\elasticsearch-5.6.3\data\nodes\0" "write")
			at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.3.jar:5.6.3]
			at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.3.jar:5.6.3]
			at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.3.jar:5.6.3]
			at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.3.jar:5.6.3]
			at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.3.jar:5.6.3]
			at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.3.jar:5.6.3]
			at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.3.jar:5.6.3]
	Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "D:\temp\elastic\elasticsearch-5.6.3\data\nodes\0" "write")
			at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_144]
			at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_144]
			at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_144]
			at java.lang.SecurityManager.checkWrite(SecurityManager.java:979) ~[?:1.8.0_144]
			at sun.nio.fs.WindowsPath.checkWrite(WindowsPath.java:799) ~[?:?]
			at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:491) ~[?:?]
			at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_144]
			at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_144]
			at java.nio.file.Files.createDirectories(Files.java:727) ~[?:1.8.0_144]
			at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:92) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
			at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
			at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
			at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:226) ~[elasticsearch-5.6.3.jar:5.6.3]
			at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.6.3.jar:5.6.3]
			at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.3.jar:5.6.3]
			at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.3.jar:5.6.3]
			at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.3.jar:5.6.3]
			at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.3.jar:5.6.3]
			at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.3.jar:5.6.3]
			... 6 more

**Steps to reproduce**:

1. Create directory C:\temp
2. Create directory D:\temp\elastic
3. Create a symlink from C:\temp\elastic to D:\temp\elastic
	C:\temp>mklink /D elastic D:\temp\elastic
4. Extract Elasticsearch ZIP in C:\temp\elastic
5. Launch elasticsearch from C:\temp\elastic
	C:\temp\elastic\elasticsearch-5.6.3>bin\elasticsearch

It seems that write access is restricted to C:\temp\elastic\elasticsearch-5.6.3 but later attempted for D:\temp\elastic\elasticsearch-5.6.3

**Comment by jasontedor** [comment]
We do not allow writes through symlinks, only reading through symlinks (e.g., we will follow a symlink to a configuration file). To workaround this, you can try setting path.data to `D:\temp\elastic\elasticsearch-5.6.3\data` explicitly in which case we will grant Elasticsearch write permissions to this directory.
