### ISSUE TITLE
BWC tests failing on newer kernel versions

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#26968]
BWC tests are currently [failing on CI](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+bwc-tests/236/consoleFull) due to an [inability to correctly parse v2 cgroups in older ES versions](https://github.com/elastic/elasticsearch/pull/23493). The reason it shows now is that CI is running newer Linux kernels (>= 4.5) now (e.g. 4.12.13-300.fc26.x86_64).

Example failures:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+bwc-tests/236/consoleFull

Logging output:

```
Warning: Ignoring JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
Please pass JVM parameters via ES_JAVA_OPTS instead
[2017-10-11T10:46:06,929][INFO ][o.e.n.Node               ] [] initializing ...
[2017-10-11T10:46:07,014][INFO ][o.e.e.NodeEnvironment    ] [maF_24j] using [1] data paths, mounts [[/ (/dev/xvda1)]], net usable_space [798.1gb], net total_space [1007.8gb], spins? [no], types [ext4]
[2017-10-11T10:46:07,014][INFO ][o.e.e.NodeEnvironment    ] [maF_24j] heap size [494.9mb], compressed ordinary object pointers [true]
[2017-10-11T10:46:07,016][INFO ][o.e.n.Node               ] node name [maF_24j] derived from node ID [maF_24j9RbSyk_3xCzUu-A]; set [node.name] to override
[2017-10-11T10:46:07,018][INFO ][o.e.n.Node               ] version[5.1.1], pid[25091], build[5395e21/2016-12-06T12:36:15.409Z], OS[Linux/4.12.13-300.fc26.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_141/25.141-b16]
[2017-10-11T10:46:07,983][INFO ][o.e.p.PluginsService     ] [maF_24j] loaded module [aggs-matrix-stats]
[2017-10-11T10:46:07,984][INFO ][o.e.p.PluginsService     ] [maF_24j] loaded module [ingest-common]
[2017-10-11T10:46:07,984][INFO ][o.e.p.PluginsService     ] [maF_24j] loaded module [lang-expression]
[2017-10-11T10:46:07,984][INFO ][o.e.p.PluginsService     ] [maF_24j] loaded module [lang-groovy]
[2017-10-11T10:46:07,984][INFO ][o.e.p.PluginsService     ] [maF_24j] loaded module [lang-mustache]
[2017-10-11T10:46:07,984][INFO ][o.e.p.PluginsService     ] [maF_24j] loaded module [lang-painless]
[2017-10-11T10:46:07,985][INFO ][o.e.p.PluginsService     ] [maF_24j] loaded module [percolator]
[2017-10-11T10:46:07,985][INFO ][o.e.p.PluginsService     ] [maF_24j] loaded module [reindex]
[2017-10-11T10:46:07,985][INFO ][o.e.p.PluginsService     ] [maF_24j] loaded module [transport-netty3]
[2017-10-11T10:46:07,985][INFO ][o.e.p.PluginsService     ] [maF_24j] loaded module [transport-netty4]
[2017-10-11T10:46:07,986][INFO ][o.e.p.PluginsService     ] [maF_24j] no plugins loaded
[2017-10-11T10:46:08,908][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [main], exiting
java.lang.AssertionError: 0::/system.slice/runsvdir.service
	at org.elasticsearch.monitor.os.OsProbe.getControlGroups(OsProbe.java:210) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:402) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:454) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.monitor.os.OsService.<init>(OsService.java:45) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.monitor.MonitorService.<init>(MonitorService.java:45) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.node.Node.<init>(Node.java:345) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.node.Node.<init>(Node.java:229) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:214) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:214) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:306) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.cli.Command.main(Command.java:62) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.1.1.jar:5.1.1]
```

What should we do?

**Comment by dliappis** [comment]
From a CI PoV I can only see two options:

1. Limit the eligible CI targets for executing the BWC tests to distributions committed to run an [LTS Linux kernel](https://www.kernel.org/category/releases.html). Just the other day, there was an announcement that all new [LTS kernels will be supported for 6 years](https://www.theregister.co.uk/2017/10/03/linux_kernel_long_term_support_extended_from_two_to_six_years/), up from the current two. Some older LTS kernels have also been bumped to get supported for 6 years, see the [EOL table here](https://www.kernel.org/category/releases.html):

    ![image](https://user-images.githubusercontent.com/1754575/31443631-a38ffce0-aea2-11e7-9ef1-00515dea1a33.png)

    Practically then, we could only target BWC tests to run on those distros: ubuntu-16.04, ubuntu-14.04, centos-7, centos-6 (and oraclelinux equivalents), debian-8 and sles-12. Periodically updated distributions like OpenSUSE, Fedora and rolling update style such as AmazonLinux should not be included in the BWC testing, until the tests stop including Elasticsearch <5.3.1 which doesn't have the cgroup v2 fix.

2. Since the BWC tests are periodical, not triggered by commit events, we can just add a check in the test suite to skip/return success if kernel>4.5. As long as the LTS based distributions mentioned in 1. are not EOLed there will always be slaves (and they are the majority in number) where CI will schedule the tests to run on.

**Comment by jasontedor** [comment]
This will be closed by #28267, #28268, and #28278.

**Comment by jasontedor** [comment]
Closed by #28267, #28268, and #28278

**Comment by dakrone** [comment]
I think this has recurred, there's another failure https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+bwc-tests/585/console

```
...
|    [2018-02-06T23:15:46,787][INFO ][o.e.p.PluginsService     ] [node-0] no plugins loaded
|    [2018-02-06T23:15:47,528][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-0] fatal error in thread [main], exiting
|    java.lang.AssertionError: 0::/system.slice/runsvdir.service
|    	at org.elasticsearch.monitor.os.OsProbe.getControlGroups(OsProbe.java:210) ~[elasticsearch-5.1.1.jar:5.1.1]
|    	at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:402) ~[elasticsearch-5.1.1.jar:5.1.1]
|    	at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:454) ~[elasticsearch-5.1.1.jar:5.1.1]
|    	at org.elasticsearch.monitor.os.OsService.<init>(OsService.java:45) ~[elasticsearch-5.1.1.jar:5.1.1]
|    	at org.elasticsearch.monitor.MonitorService.<init>(MonitorService.java:45) ~[elasticsearch-5.1.1.jar:5.1.1]
|    	at org.elasticsearch.node.Node.<init>(Node.java:345) ~[elasticsearch-5.1.1.jar:5.1.1]
|    	at org.elasticsearch.node.Node.<init>(Node.java:229) ~[elasticsearch-5.1.1.jar:5.1.1]
|    	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:214) ~[elasticsearch-5.1.1.jar:5.1.1]
|    	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:214) ~[elasticsearch-5.1.1.jar:5.1.1]
|    	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:306) ~[elasticsearch-5.1.1.jar:5.1.1]
|    	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.1.1.jar:5.1.1]
|    	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.1.1.jar:5.1.1]
|    	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.1.1.jar:5.1.1]
|    	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) ~[elasticsearch-5.1.1.jar:5.1.1]
|    	at org.elasticsearch.cli.Command.main(Command.java:62) ~[elasticsearch-5.1.1.jar:5.1.1]
|    	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.1.1.jar:5.1.1]
|    	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.1.1.jar:5.1.1]
```

The kernel version is 4.13.16-200.fc26.x86_64, though, since the ES version is 5.1.1 maybe there's not much we want to do about it? @jasontedor what do you think?

**Comment by jasontedor** [comment]
Version 5.1.1 is suppose to be skipped here. See the changes in #28268.

**Comment by jasontedor** [comment]
Oh, I see the problem. It’s the verify version constants test. I will address.

**Comment by jasontedor** [comment]
@dakrone I pushed d815f5fdd1237b2719ca5a2ce66ee0ba1e4da315 and cherry-picked this to all the places where it is relevant:
 - 6.x: d815f5fdd1237b2719ca5a2ce66ee0ba1e4da315
 - 6.2: e31736706a1fe6b06909b82e8a70bcd34d051ad1
 - 6.1: fbb6e1afb0d71cb0d387c76eed2ea680181e5126
 - 5.6: f8bc4322b811748e64f1c4752e5786ebdd7e299e
