### ISSUE TITLE
RestHighLevelClient fails to parse ShardSearchFailure on Scroll

### ISSUE THREAD

**Issue by sschepens** [elastic/elasticsearch#27055]
When Scrolling, `ShardSearchFailures` returned by ElasticSearch return no `index`, this in turn makes `RestHighLevelClient` fail to parse them, because `Index` [requires name not to be null](https://github.com/elastic/elasticsearch/blob/5.6/core/src/main/java/org/elasticsearch/index/Index.java#L53)

We're seeing the following exceptions:
```
java.io.IOException: Unable to parse response body for Response{requestLine=GET /_search/scroll HTTP/1.1, host=http://unrouted.ds-apicore-misc-01.ds:80, response=HTTP/1.1 200 OK}
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:394)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:361)
	at org.elasticsearch.client.RestHighLevelClient.searchScroll(RestHighLevelClient.java:321)
	...
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at org.elasticsearch.index.Index.<init>(Index.java:53)
	at org.elasticsearch.action.search.ShardSearchFailure.fromXContent(ShardSearchFailure.java:213)
	at org.elasticsearch.action.search.SearchResponse.fromXContent(SearchResponse.java:297)
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:505)
	at org.elasticsearch.client.RestHighLevelClient.lambda$performRequestAndParseEntity$2(RestHighLevelClient.java:361)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:392)
	... 39 more
```

We're in the process of migrating our `TransportClients` to `RestHighLevelClient`, when using `TransportClient` this exceptions did not occur.

On `TransportClient` this translates to having a response with the following shard failures:
```
shard [_na], reason [RemoteTransportException[[i-0ad52147150c19404][10.64.92.24:9300][indices:data/read/search[phase/query/scroll]]]; nested: SearchContextMissingException[No search context found for id [5862]]; ], cause [SearchContextMissingException[No search context found for id [5862]]
```

**Elasticsearch version** 5.6.3

Edit:

This apparently seems to happen because on Scrolls the `shardTarget` of a `ShardSearchFailure` can be [null](https://github.com/elastic/elasticsearch/blob/5.6/core/src/main/java/org/elasticsearch/action/search/ShardSearchFailure.java#L170), but when parsing itself with `fromXContent` [it always tries to instantiate one with null values](https://github.com/elastic/elasticsearch/blob/5.6/core/src/main/java/org/elasticsearch/action/search/ShardSearchFailure.java#L214).

**Comment by javanna** [comment]
hi @sschepens thanks a lot for opening this issue and for the analysis that alright headed me in the right direction. We did have an integration test for the `SearchContextMissingException` case but it didn't cover partial failures, where the target comes back null. I am going to open a PR with a fix.

**Comment by sschepens** [comment]
thanks @javanna !
