### ISSUE TITLE
[CI] InternalMatrixStatsTests. testFromXContentWithRandomFields fails because expected exception not thrown 

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#27141]
Build URL: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/4795/console

Reproduce command (this reproduces locally for me:
```
gradle :modules:aggs-matrix-stats:test \
  -Dtests.seed=C787D0F8C37CCF8B \
  -Dtests.class=org.elasticsearch.search.aggregations.matrix.stats.InternalMatrixStatsTests \
  -Dtests.method="testFromXContentWithRandomFields" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-TN \
  -Dtests.timezone=Etc/GMT+2
```

Failure stack trace:
```
  2> REPRODUCE WITH: gradle :modules:aggs-matrix-stats:test -Dtests.seed=C787D0F8C37CCF8B -Dtests.class=org.elasticsearch.search.aggregations.matrix.stats.InternalMatrixStatsTests -Dtests.method="testFromXContentWithRandomFields" -Dtests.security.manager=true -Dtests.locale=ar-TN -Dtests.timezone=Etc/GMT+2
FAILURE 1.34s | InternalMatrixStatsTests.testFromXContentWithRandomFields <<< FAILURES!
   > Throwable #1: junit.framework.AssertionFailedError: Expected exception IllegalArgumentException but no exception was thrown
   >    at __randomizedtesting.SeedInfo.seed([C787D0F8C37CCF8B:C592FDB998BB475E]:0)
   >    at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2672)
   >    at org.elasticsearch.search.aggregations.matrix.stats.InternalMatrixStatsTests.assertFromXContent(InternalMatrixStatsTests.java:213)
   >    at org.elasticsearch.search.aggregations.matrix.stats.InternalMatrixStatsTests.assertFromXContent(InternalMatrixStatsTests.java:45)
   >    at org.elasticsearch.test.InternalAggregationTestCase.testFromXContentWithRandomFields(InternalAggregationTestCase.java:310)
   >    at java.lang.Thread.run(Thread.java:745)
```

**Comment by colings86** [comment]
@nknize could you take a look at this?

**Comment by cbuescher** [comment]
I think I see the problem, looks like we got really unlucky with the randomization on this one. I will have a PR that makes this more stable shortly.

**Comment by cbuescher** [comment]
Fixed by b88dbe
