### ISSUE TITLE
DocumentMissingException during Logstash scripted upsert

### ISSUE THREAD

**Issue by rfraposa** [elastic/elasticsearch#27148]
**Describe the feature**: I am performing a scripted upsert using Logstash. The setup works fine on ES 5.x, but fails on 6.0.rc1 throwing a org.elasticsearch.index.engine.DocumentMissingException

**Elasticsearch version** (`bin/elasticsearch --version`): 6.0.0.rc1

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

I created a gist to make it easier to reproduce the error:
https://gist.github.com/rfraposa/83c5c526c2a6c55417d4dcd8748fa26e

**Provide logs (if relevant)**:
```
[2017-10-27T07:56:12,853][DEBUG][o.e.a.b.TransportShardBulkAction] [my_destination][0] failed to execute bulk item (update) BulkShardRequest [[my_destination][0]] containing [2] requests
org.elasticsearch.index.engine.DocumentMissingException: [doc][1234]: document missing
	at org.elasticsearch.action.update.UpdateHelper.prepareUpsert(UpdateHelper.java:132) ~[elasticsearch-6.0.0-rc1.jar:6.0.0-rc1]
	at org.elasticsearch.action.update.UpdateHelper.prepare(UpdateHelper.java:88) ~[elasticsearch-6.0.0-rc1.jar:6.0.0-rc1]
	at org.elasticsearch.action.update.UpdateHelper.prepare(UpdateHelper.java:77) ~[elasticsearch-6.0.0-rc1.jar:6.0.0-rc1]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeUpdateRequestOnce(TransportShardBulkAction.java:343) ~[elasticsearch-6.0.0-rc1.jar:6.0.0-rc1]
...
```

**Comment by morphers82** [comment]
I had a problem like this using php client.  It was because I didn't include the upsert field while doing a scripted_upsert

**Comment by rfraposa** [comment]
I am using Logstash with the following output:

```
output {
	elasticsearch {
		action => "update"
 		index => "my_destination"
		document_type => "doc"
		document_id => "%{trip_id}"
		scripted_upsert => true
		script => "update_my_docs"
		script_type => "indexed"
		script_lang => "painless"
		script_var_name => "event"
		upsert => "null"
	}
}
```

It is certainly possible that this is a bug with Logstash.

**Comment by rfraposa** [comment]
I spoke with @andrewvc on the Logstash team and they found a small bug in the bulk upsert request sent by LS. Closing this issue for now, in hopes that the fix will resolve this issue.
