### ISSUE TITLE
[CI] IndexingIT#testSeqNoCheckpoints fails on 6.x

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#27228]
* Build failure link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/577/console
* Error message: 
```
09:40:33 FAILURE 10.5s | IndexingIT.testSeqNoCheckpoints <<< FAILURES!
09:40:33    > Throwable #1: java.lang.AssertionError: max_seq no on Node{id='E7cOjPeMS-mKLykbS-Q7SA', nodeName='node-0', version=6.0.0} is wrong
09:40:33    > Expected: <-1L>
09:40:33    >      but: was <4L>
09:40:33    > 	at __randomizedtesting.SeedInfo.seed([EC8A38525928113:3FA4494EEF0D044F]:0)
09:40:33    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
09:40:33    > 	at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
09:40:33    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:725)
09:40:33    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:699)
09:40:33    > 	at org.elasticsearch.backwards.IndexingIT.assertSeqNoOnShards(IndexingIT.java:262)
09:40:33    > 	at org.elasticsearch.backwards.IndexingIT.testSeqNoCheckpoints(IndexingIT.java:202)
09:40:33    > 	at java.lang.Thread.run(Thread.java:748)
09:40:33    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='E7cOjPeMS-mKLykbS-Q7SA', nodeName='node-0', version=6.0.0} is wrong
09:40:33    > Expected: <-1L>
09:40:33    >      but: was <4L>
09:40:33    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
09:40:33    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
09:40:33    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:713)
09:40:33    > 		... 40 more
09:40:33    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='E7cOjPeMS-mKLykbS-Q7SA', nodeName='node-0', version=6.0.0} is wrong
09:40:33    > Expected: <-1L>
09:40:33    >      but: was <4L>
09:40:33    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
09:40:33    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
09:40:33    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:713)
09:40:33    > 		... 40 more
09:40:33    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='E7cOjPeMS-mKLykbS-Q7SA', nodeName='node-0', version=6.0.0} is wrong
09:40:33    > Expected: <-1L>
09:40:33   2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+6.x+intake/qa/mixed-cluster/build/testrun/v6.0.0-SNAPSHOT#mixedClusterTestRunner/J0/temp/org.elasticsearch.backwards.IndexingIT_EC8A38525928113-001
09:40:33   2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=604, maxMBSortInHeap=6.174016538066457, sim=RandomSimilarity(queryNorm=false): {}, locale=ar-MA, timezone=America/Maceio
09:40:33    >      but: was <4L>
09:40:33   2> NOTE: Linux 4.9.0-3-amd64 amd64/Oracle Corporation 1.8.0_141 (64-bit)/cpus=4,threads=1,free=433943112,total=514850816
09:40:33   2> NOTE: All tests run in this JVM: [IndexingIT]
09:40:33    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
09:40:33    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
09:40:33    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:713)
09:40:33    > 		... 40 more
09:40:33    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='E7cOjPeMS-mKLykbS-Q7SA', nodeName='node-0', version=6.0.0} is wrong
09:40:33    > Expected: <-1L>
09:40:33    >      but: was <4L>
09:40:33    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
09:40:33    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
09:40:33    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:713)
09:40:33    > 		... 40 more
09:40:33    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='E7cOjPeMS-mKLykbS-Q7SA', nodeName='node-0', version=6.0.0} is wrong
09:40:33    > Expected: <-1L>
09:40:33    >      but: was <4L>
09:40:33    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
09:40:33    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
09:40:33    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:713)
09:40:33    > 		... 40 more
09:40:33    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='E7cOjPeMS-mKLykbS-Q7SA', nodeName='node-0', version=6.0.0} is wrong
09:40:33    > Expected: <-1L>
09:40:33    >      but: was <4L>
09:40:33    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
09:40:33    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
09:40:33    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:713)
09:40:33    > 		... 40 more
09:40:33    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='E7cOjPeMS-mKLykbS-Q7SA', nodeName='node-0', version=6.0.0} is wrong
09:40:33    > Expected: <-1L>
09:40:33    >      but: was <4L>
09:40:33    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
09:40:33    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
09:40:33    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:713)
09:40:33    > 		... 40 more
09:40:33    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='E7cOjPeMS-mKLykbS-Q7SA', nodeName='node-0', version=6.0.0} is wrong
09:40:33    > Expected: <-1L>
09:40:33    >      but: was <4L>
09:40:33    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
09:40:33    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
09:40:33    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:713)
09:40:33    > 		... 40 more
09:40:33    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='E7cOjPeMS-mKLykbS-Q7SA', nodeName='node-0', version=6.0.0} is wrong
09:40:33    > Expected: <-1L>
09:40:33    >      but: was <4L>
09:40:33    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
09:40:33    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
09:40:33    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:713)
09:40:33    > 		... 40 more
09:40:33    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='E7cOjPeMS-mKLykbS-Q7SA', nodeName='node-0', version=6.0.0} is wrong
09:40:33    > Expected: <-1L>
09:40:33    >      but: was <4L>
09:40:33    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
09:40:33    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
09:40:33    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:713)
09:40:33    > 		... 40 more
09:40:33    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='E7cOjPeMS-mKLykbS-Q7SA', nodeName='node-0', version=6.0.0} is wrong
09:40:33    > Expected: <-1L>
09:40:33    >      but: was <4L>
09:40:33    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
09:40:33    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
09:40:33    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:713)
09:40:33    > 		... 40 more
09:40:33    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='E7cOjPeMS-mKLykbS-Q7SA', nodeName='node-0', version=6.0.0} is wrong
09:40:33    > Expected: <-1L>
09:40:33    >      but: was <4L>
09:40:33    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
09:40:33    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
09:40:33    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:713)
09:40:33    > 		... 40 more
09:40:33    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='E7cOjPeMS-mKLykbS-Q7SA', nodeName='node-0', version=6.0.0} is wrong
09:40:33    > Expected: <-1L>
09:40:33    >      but: was <4L>
09:40:33    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
09:40:33    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
09:40:33    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:713)
09:40:33    > 		... 40 more
```

* Reproduction line:
```
gradle :qa:mixed-cluster:v6.0.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=EC8A38525928113 \
  -Dtests.class=org.elasticsearch.backwards.IndexingIT \
  -Dtests.method="testSeqNoCheckpoints" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-MA \
  -Dtests.timezone=America/Maceio
```

**Comment by jasontedor** [comment]
I'm reassigning this to myself because I think I see the problem already.

**Comment by cbuescher** [comment]
@jasontedor do you think this is a test or more of a test infra problem? Asking because if its the later it might be related to other test failures that I'm looking at currently.

**Comment by jasontedor** [comment]
I think it's a problem specific to this test (i.e., a test bug).

**Comment by cbuescher** [comment]
Another one, in case you need more data points: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/578/console

**Comment by jasontedor** [comment]
Closed by bc63691eda1eaa8c4aaa9c251dee5d39b2914b3e

**Comment by cbuescher** [comment]
Could you take another look at a later failure that seems to include your fix on the 6.0 branch?

```
10:44:55 Checking out Revision 38328b33fa32de79c6bf7ee85ea025431e64671c (refs/remotes/origin/6.0)
10:44:55  > git config core.sparsecheckout # timeout=20
10:44:55  > git checkout -f 38328b33fa32de79c6bf7ee85ea025431e64671c
10:44:56 Commit message: "Fix sequence number assertions in BWC tests"
10:44:56  > git rev-list a8dbde6ae2608aa0e06bba0b256d63e4365d9454 # timeout=20
```

I'm not sure if there is anything special about the mixed cluster tests in this case:

```
11:30:24   2> REPRODUCE WITH: gradle :qa:mixed-cluster:v5.6.4-SNAPSHOT#mixedClusterTestRunner -Dtests.seed=6257E4F15DF2C13A -Dtests.class=org.elasticsearch.backwards.IndexingIT -Dtests.method="testSeqNoCheckpoints" -Dtests.security.manager=true -Dtests.locale=de-CH -Dtests.timezone=Europe/Podgorica
11:30:24 FAILURE 11.0s | IndexingIT.testSeqNoCheckpoints <<< FAILURES!
11:30:24    > Throwable #1: java.lang.AssertionError: max_seq no on Node{id='6DaPPL8cQJiqAStVx6BsbQ', nodeName='node-2', version=6.0.0} is wrong
11:30:24    > Expected: <11L>
11:30:24    >      but: was <3L>
11:30:24    > 	at __randomizedtesting.SeedInfo.seed([6257E4F15DF2C13A:533B0E3A976D4466]:0)
11:30:24    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:30:24    > 	at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
11:30:24    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:722)
11:30:24    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:696)
11:30:24    > 	at org.elasticsearch.backwards.IndexingIT.assertSeqNoOnShards(IndexingIT.java:262)
11:30:24    > 	at org.elasticsearch.backwards.IndexingIT.testSeqNoCheckpoints(IndexingIT.java:223)
11:30:24    > 	at java.lang.Thread.run(Thread.java:745)
11:30:24    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='6DaPPL8cQJiqAStVx6BsbQ', nodeName='node-2', version=6.0.0} is wrong
11:30:24    > Expected: <11L>
11:30:24    >      but: was <3L>
11:30:24    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:30:24    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
11:30:24    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
11:30:24    > 		... 40 more
11:30:24    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='6DaPPL8cQJiqAStVx6BsbQ', nodeName='node-2', version=6.0.0} is wrong
11:30:24    > Expected: <11L>
11:30:24    >      but: was <3L>
11:30:24    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:30:24   2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+6.0+intake/qa/mixed-cluster/build/testrun/v5.6.4-SNAPSHOT#mixedClusterTestRunner/J0/temp/org.elasticsearch.backwards.IndexingIT_6257E4F15DF2C13A-001
11:30:24   2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=1404, maxMBSortInHeap=5.100370776080765, sim=RandomSimilarity(queryNorm=true): {}, locale=de-CH, timezone=Europe/Podgorica
11:30:24    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
11:30:24   2> NOTE: Linux 4.4.49-92.14-default amd64/Oracle Corporation 1.8.0_121 (64-bit)/cpus=4,threads=1,free=429185928,total=514850816
11:30:24   2> NOTE: All tests run in this JVM: [IndexingIT]
11:30:24    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
11:30:24    > 		... 40 more
11:30:24    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='6DaPPL8cQJiqAStVx6BsbQ', nodeName='node-2', version=6.0.0} is wrong
11:30:24    > Expected: <11L>
11:30:24    >      but: was <3L>
11:30:24    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:30:24    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
11:30:24    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
11:30:24    > 		... 40 more
11:30:24    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='6DaPPL8cQJiqAStVx6BsbQ', nodeName='node-2', version=6.0.0} is wrong
11:30:24    > Expected: <11L>
11:30:24    >      but: was <3L>
11:30:24    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:30:24    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
11:30:24    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
11:30:24    > 		... 40 more
11:30:24    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='6DaPPL8cQJiqAStVx6BsbQ', nodeName='node-2', version=6.0.0} is wrong
11:30:24    > Expected: <11L>
11:30:24    >      but: was <3L>
11:30:24    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:30:24    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
11:30:24    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
11:30:24    > 		... 40 more
11:30:24    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='6DaPPL8cQJiqAStVx6BsbQ', nodeName='node-2', version=6.0.0} is wrong
11:30:24    > Expected: <11L>
11:30:24    >      but: was <3L>
11:30:24    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:30:24    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
11:30:24    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
11:30:24    > 		... 40 more
11:30:24    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='6DaPPL8cQJiqAStVx6BsbQ', nodeName='node-2', version=6.0.0} is wrong
11:30:24    > Expected: <11L>
11:30:24    >      but: was <3L>
11:30:24    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:30:24    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
11:30:24    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
11:30:24    > 		... 40 more
11:30:24    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='6DaPPL8cQJiqAStVx6BsbQ', nodeName='node-2', version=6.0.0} is wrong
11:30:24    > Expected: <11L>
11:30:24    >      but: was <3L>
11:30:24    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:30:24    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
11:30:24    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
11:30:24    > 		... 40 more
11:30:24    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='6DaPPL8cQJiqAStVx6BsbQ', nodeName='node-2', version=6.0.0} is wrong
11:30:24    > Expected: <11L>
11:30:24    >      but: was <3L>
11:30:24    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:30:24    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
11:30:24    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
11:30:24    > 		... 40 more
11:30:24    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='6DaPPL8cQJiqAStVx6BsbQ', nodeName='node-2', version=6.0.0} is wrong
11:30:24    > Expected: <11L>
11:30:24    >      but: was <3L>
11:30:24    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:30:24    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
11:30:24    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
11:30:24    > 		... 40 more
11:30:24    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='6DaPPL8cQJiqAStVx6BsbQ', nodeName='node-2', version=6.0.0} is wrong
11:30:24    > Expected: <11L>
11:30:24    >      but: was <3L>
11:30:24    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:30:24    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
11:30:24    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
11:30:24    > 		... 40 more
11:30:24    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='6DaPPL8cQJiqAStVx6BsbQ', nodeName='node-2', version=6.0.0} is wrong
11:30:24    > Expected: <11L>
11:30:24    >      but: was <3L>
11:30:24    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:30:24    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
11:30:25    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
11:30:25    > 		... 40 more
11:30:25    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='6DaPPL8cQJiqAStVx6BsbQ', nodeName='node-2', version=6.0.0} is wrong
11:30:25    > Expected: <11L>
11:30:25    >      but: was <3L>
11:30:25    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:30:25    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
11:30:25    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
11:30:25    > 		... 40 more
```

**Comment by jasontedor** [comment]
The assertions were correct as-was on 6.0, where there is a 5.6 node in play that is not maintaining sequence numbers when it acts as the primary. Therefore I should not have backported the fix that was applicable to the 6.x branch to 6.0. I have reverted this in df0eae2a3cf5add16481dcf25afad792d69438d0.

**Comment by cbuescher** [comment]
@jasontedor sorry to bother yet another time, but I'm still getting similar errors on the 6.0 branch:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.0+intake/433/consoleFull

```
12:14:39  > git checkout -f df0eae2a3cf5add16481dcf25afad792d69438d0
12:14:40 Commit message: "Revert "Remove checkpoint tracker bit sets setting""
```

```
13:01:06   2> REPRODUCE WITH: gradle :qa:mixed-cluster:v5.6.4-SNAPSHOT#mixedClusterTestRunner -Dtests.seed=F9E2FADEDD2FFE3B -Dtests.class=org.elasticsearch.backwards.IndexingIT -Dtests.method="testSeqNoCheckpoints" -Dtests.security.manager=true -Dtests.locale=sr-BA -Dtests.timezone=VST
13:01:06 FAILURE 11.5s | IndexingIT.testSeqNoCheckpoints <<< FAILURES!
13:01:06    > Throwable #1: java.lang.AssertionError: max_seq no on Node{id='Jl6oXYmqTP2VZvxepcka7Q', nodeName='node-2', version=6.0.0} is wrong
13:01:06    > Expected: <8L>
13:01:06    >      but: was <0L>
13:01:06    > 	at __randomizedtesting.SeedInfo.seed([F9E2FADEDD2FFE3B:C88E101517B07B67]:0)
13:01:06    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
13:01:06    > 	at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
13:01:06    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:722)
13:01:06    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:696)
13:01:06    > 	at org.elasticsearch.backwards.IndexingIT.assertSeqNoOnShards(IndexingIT.java:262)
13:01:06    > 	at org.elasticsearch.backwards.IndexingIT.testSeqNoCheckpoints(IndexingIT.java:223)
13:01:06    > 	at java.lang.Thread.run(Thread.java:745)
13:01:06    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='Jl6oXYmqTP2VZvxepcka7Q', nodeName='node-2', version=6.0.0} is wrong
13:01:06    > Expected: <8L>
13:01:06    >      but: was <0L>
13:01:06    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
13:01:06    > 		at org.elasticsearch.backwards.IndexingIT.lambda$assertSeqNoOnShards$3(IndexingIT.java:281)
13:01:06    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:710)
13:01:06    > 		... 40 more
13:01:06    > 	Suppressed: java.lang.AssertionError: max_seq no on Node{id='Jl6oXYmqTP2VZvxepcka7Q', nodeName='node-2', version=6.0.0} is wrong
```

I might have misunderstood sth. but I thought 38328b33fa32de79c6bf7ee8 should have been reverted, but the above commit seems to have reverted another commit?

**Comment by jasontedor** [comment]
I'm really not sure how that happened. I have fixed this.

**Comment by cbuescher** [comment]
np, thanks, will keep an eye on it ;-)
