### ISSUE TITLE
[CI] QueryStringQueryBuilderTests testExistsFieldQuery Fails

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#27246]
Reproducible failure on 6.x and master

```
FAILURE 1.92s | QueryStringQueryBuilderTests.testExistsFieldQuery <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <ConstantScore(_field_names:mapped_string)>
   >      but: was <ConstantScore(NormsFieldExistsQuery [field=mapped_string])>
   >    at __randomizedtesting.SeedInfo.seed([955B16736446AFFF:2A4DADB814820337]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.index.query.QueryStringQueryBuilderTests.testExistsFieldQuery(QueryStringQueryBuilderTests.java:812)
   >    at java.lang.Thread.run(Thread.java:745)
```

The reproduce line for master is 
```
gradle :core:test \
  -Dtests.seed=955B16736446AFFF \
  -Dtests.class=org.elasticsearch.index.query.QueryStringQueryBuilderTests \
  -Dtests.method="testExistsFieldQuery" \
  -Dtests.security.manager=true \
  -Dtests.locale=bg \
  -Dtests.timezone=Asia/Jerusalem
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/715/console

**Comment by droberts195** [comment]
For the seed in the original repro this now works.  But with a different seed I am now seeing this fail with expected and actual flipped around from the original failure:

```
gradle :core:test -Dtests.seed=8A602A36C25DDC8A -Dtests.class=org.elasticsearch.index.query.QueryStringQueryBuilderTests -Dtests.method="testExistsFieldQuery" -Dtests.security.manager=true -Dtests.locale=lt -Dtests.timezone=Indian/Mayotte
```

results in:

```
FAILURE 1.22s | QueryStringQueryBuilderTests.testExistsFieldQuery <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <ConstantScore(NormsFieldExistsQuery [field=mapped_string])>
   >      but: was <ConstantScore(_field_names:mapped_string)>
   >    at __randomizedtesting.SeedInfo.seed([8A602A36C25DDC8A:357691FDB2997042]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.index.query.QueryStringQueryBuilderTests.testExistsFieldQuery(QueryStringQueryBuilderTests.java:813)
   >    at java.lang.Thread.run(Thread.java:745)
```

So it seems that at present the actual result can be one of two values: the one that was expected first thing this morning and the one it was changed to in the initial fix for this issue.

**Comment by jimczi** [comment]
Thanks for reopening @droberts195, I missed the BWC layer of this test. 
I pushed a change to fix the issue completely.
