### ISSUE TITLE
UncategorizedExecutionException[Failed execution]; nested: IOException[can not write type [class java.math.BigDecimal]];

### ISSUE THREAD

**Issue by mustafaakin** [elastic/elasticsearch#27270]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.5

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_144

**OS version** (`uname -a` if on a Unix-like system): OSX High Sierra

**Description of the problem including expected versus actual behavior**:

I have the following query that is sent by transport client, generated by some code, I got it from the debug mode:

```json
{
  "size" : 0,
  "aggregations" : {
    "osman" : {
      "meta" : {
        "order" : 0
      },
      "filter" : {
        "bool" : {
          "must" : [
            {
              "range" : {
                "age" : {
                  "from" : "10",
                  "to" : null,
                  "include_lower" : false,
                  "include_upper" : true,
                  "boost" : 1.0
                }
              }
            }
          ],
          "disable_coord" : false,
          "adjust_pure_negative" : true,
          "boost" : 1.0
        }
      },
      "aggregations" : {
        "inner" : {
          "avg" : {
            "field" : "age"
          }
        }
      }
    }
  }
}
```

It throws the following exception:

```java
UncategorizedExecutionException[Failed execution]; nested: IOException[can not write type [class java.math.BigDecimal]];
	at org.elasticsearch.action.support.AdapterActionFuture.rethrowExecutionException(AdapterActionFuture.java:89)
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:76)
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:63)
	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:69)
```

It executes nicely via the rest API in Kibana:

```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 7,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "osman": {
      "meta": {
        "order": 0
      },
      "doc_count": 6,
      "inner": {
        "value": 38.166666666666664
      }
    }
  }
}
```

**Comment by mustafaakin** [comment]
Sorry, I saw that my parser put 10 as BigDecimal, but why does it fail for bigdecimal? I suppose it is because there is no serialization for BigDecimal over the wire?

**Comment by jasontedor** [comment]
That's correct, serialization of `BigDecimal` is not supported.

**Comment by vermarajput** [comment]
I understand that serialization of BigDecimal or LocalDate is not supported, howver, is there any work around the same??

**Comment by jasontedor** [comment]
@vermarajput Please see #17006.
