### ISSUE TITLE
[CI] DocsClientYamlTestSuiteIT {yaml=reference/getting-started/line_356} test failure

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#27277]
Reproduce line:

```
gradle :docs:integTestRunner -Dtests.seed=4D6A2945D2595613 -Dtests.class=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT -Dtests.method="test {yaml=reference/getting-started/line_356}" -Dtests.security.manager=true -Dtests.locale=et-EE -Dtests.timezone=Asia/Istanbul
```

But could not reproduce locally.

Failure:

```
10:21:14   1> [2017-11-06T13:20:17,362][INFO ][o.e.s.DocsClientYamlTestSuiteIT] Stash dump on failure [{
10:21:14   1>   "stash" : {
10:21:14   1>     "body" : "health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size
10:21:14   1> yellow open   customer LiR7IDcfS1yB023CfHFtRg   5   1          0            0      1.1kb          1.1kb
10:21:14   1> "
10:21:14   1>   }
10:21:14   1> }]
10:21:14   1> [2017-11-06T13:20:17,363][ERROR][o.e.s.DocsClientYamlTestSuiteIT] This failing test was generated by documentation starting at reference/getting-started.asciidoc:line_356. It may include many snippets. See docs/README.asciidoc for an explanation of test generation.
10:21:14 FAILURE 0.11s | DocsClientYamlTestSuiteIT.test {yaml=reference/getting-started/line_356} <<< FAILURES!
10:21:14    > Throwable #1: java.lang.AssertionError: Failure at [reference/getting-started:70]: field [$body] was expected to match the provided regex but didn't
10:21:14    > Expected: health \s+status \s+index    \s+uuid                   \s+pri \s+rep \s+docs.count \s+docs.deleted \s+store.size \s+pri.store.size\s* yellow \s+open   \s+customer \s+.+   \s+5   \s+1          \s+0            \s+0       \s+\d+b           \s+\d+b\s*
10:21:14    >      but: was "health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size\nyellow open   customer LiR7IDcfS1yB023CfHFtRg   5   1          0            0      1.1kb          1.1kb\n"
10:21:14    > 	at __randomizedtesting.SeedInfo.seed([4D6A2945D2595613:C53E169F7CA53BEB]:0)
10:21:14    > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:352)
10:21:14    > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:332)
10:21:14    > 	at java.lang.Thread.run(Thread.java:748)
10:21:14    > Caused by: java.lang.AssertionError: field [$body] was expected to match the provided regex but didn't
10:21:14    > Expected: health \s+status \s+index    \s+uuid                   \s+pri \s+rep \s+docs.count \s+docs.deleted \s+store.size \s+pri.store.size\s* yellow \s+open   \s+customer \s+.+   \s+5   \s+1          \s+0            \s+0       \s+\d+b           \s+\d+b\s*
10:21:14    >      but: was "health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size\nyellow open   customer LiR7IDcfS1yB023CfHFtRg   5   1          0            0      1.1kb          1.1kb\n"
10:21:14    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
10:21:14    > 	at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:67)
10:21:14    > 	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
10:21:14    > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:348)
10:21:14    > 	... 37 more
```

**Comment by javanna** [comment]
I think the regex should be updated, the index got for some reason bigger than a kb and the unit returned is not b anymore but rather kb. I think we have a regex for these cases in other yaml tests.

**Comment by cbuescher** [comment]
I saw this in a PR the other day: https://github.com/elastic/elasticsearch/pull/26879/files
@spinscale should this be backported?

**Comment by cbuescher** [comment]
Ah, corrections, that PR is not even on master. But it should fix this issue.

**Comment by javanna** [comment]
I am not sure it fixes it completely, I will comment there.

**Comment by dimitris-athanasiou** [comment]
@cbuescher Given the PR you mentioned is now merged and the test failure has not appeared again, should we close this?

**Comment by cbuescher** [comment]
@dimitris-athanasiou yes, I think this can be closed. @javanna please reopen if you think differently.
