### ISSUE TITLE
Timeout requests after upgrade to 5.6.3

### ISSUE THREAD

**Issue by rvojcik** [elastic/elasticsearch#27303]
**Elasticsearch version** (`bin/elasticsearch --version`):

5.6.3

**Plugins installed**: []
x-pack
mapper-size

**JVM version** (`java -version`):
Oracle JRE 1.8.0-102

**OS version** (`uname -a` if on a Unix-like system):
Debian Wheezy
`Linux esdb2 4.4.82-ls-2 #2 SMP Tue Aug 22 16:46:15 CEST 2017 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:
Many requests timeout.
For example
* mapping
* allocation
* snapshot create/restore

**Provide logs (if relevant)**:
```
[2017-11-07T13:45:40,315][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [esdb2] failed to put mappings on indices [[[lslogbeat-2017.11.07/ybyWgKnaRd23NnBxbj7IOg]]], type [1510057956]
org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-mapping) within 30s
    at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$null$0(ClusterService.java:255) ~[elasticsearch-5.6.3.jar:5.6.3]
    at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_102]
    at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$onTimeout$1(ClusterService.java:254) ~[elasticsearch-5.6.3.jar:5.6.3]
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.6.3.jar:5.6.3]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
[2017-11-07T13:45:40,315][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [esdb2] failed to put mappings on indices [[[lslogbeat-2017.11.07/ybyWgKnaRd23NnBxbj7IOg]]], type [1510057956]
org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-mapping) within 30s
    at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$null$0(ClusterService.java:255) ~[elasticsearch-5.6.3.jar:5.6.3]
    at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_102]
    at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$onTimeout$1(ClusterService.java:254) ~[elasticsearch-5.6.3.jar:5.6.3]
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.6.3.jar:5.6.3]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
[2017-11-07T13:45:40,315][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [esdb2] failed to put mappings on indices [[[lslogbeat-2017.11.07/ybyWgKnaRd23NnBxbj7IOg]]], type [1510057956]
org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-mapping) within 30s
    at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$null$0(ClusterService.java:255) ~[elasticsearch-5.6.3.jar:5.6.3]
    at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_102]
    at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$onTimeout$1(ClusterService.java:254) ~[elasticsearch-5.6.3.jar:5.6.3]
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.6.3.jar:5.6.3]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
[2017-11-07T13:45:40,315][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [esdb2] failed to put mappings on indices [[[lslogbeat-2017.11.07/ybyWgKnaRd23NnBxbj7IOg]]], type [1510057956]
org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-mapping) within 30s
    at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$null$0(ClusterService.java:255) ~[elasticsearch-5.6.3.jar:5.6.3]
    at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_102]
    at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.lambda$onTimeout$1(ClusterService.java:254) ~[elasticsearch-5.6.3.jar:5.6.3]
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.6.3.jar:5.6.3]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
[2017-11-07T13:45:40,600][WARN ][o.e.c.s.ClusterService   ] [esdb2] cluster state update task [put-mapping[1510057717, 1510057717, 1510057717, 1510057717, 1510057717, 1510057717, 1510057717, 1510057717, 1510057954, 1510057954, 1510057954, 1510057971, 1510058317, 1510058318, 1510057972, 1510057953, 1510057973, 1510057976, 1510057954, 1510057954, 1510058191, 1510058191, 1510058098, 1510058099, 1510058192, 1510058193, 1510058196, 1510058312, 1510058313, 1510058087, 1510058197, 1510058318, 1510058088, 1510058319, 1510057728]] took [2m] above the warn threshold of 30s
```

**Comment by DaveCTurner** [comment]
Hi @rvojcik! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a configuration question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
