### ISSUE TITLE
[TEST] ESLoggingHandlerIT.testLoggingHandler failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#27338]
Build failure:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+java9-periodic/4603/console

Relevant log output:

```
06:57:52   1> [2017-11-10T06:57:48,101][TRACE][o.e.t.n.ESLoggingHandler ] an exception occurred formatting a trace message
06:57:52   1> java.io.IOException: Invalid string; unexpected character: 171 hex: ab
06:57:52   1> 	at org.elasticsearch.common.io.stream.StreamInput.readString(StreamInput.java:375) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
06:57:52   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ThreadContextStruct.<init>(ThreadContext.java:362) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
06:57:52   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ThreadContextStruct.<init>(ThreadContext.java:352) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
06:57:52   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext.readHeaders(ThreadContext.java:186) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
06:57:52   1> 	at org.elasticsearch.transport.netty4.ESLoggingHandler.format(ESLoggingHandler.java:105) ~[main/:?]
06:57:52   1> 	at org.elasticsearch.transport.netty4.ESLoggingHandler.format(ESLoggingHandler.java:50) [main/:?]
06:57:52   1> 	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:239) [netty-handler-4.1.13.Final.jar:4.1.13.Final]
06:57:52   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
06:57:52   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
06:57:52   1> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
06:57:52   1> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
06:57:52   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
06:57:52   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
06:57:52   1> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
06:57:52   1> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
06:57:52   1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
06:57:52   1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
06:57:52   1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
06:57:52   1> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
06:57:52   1> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.13.Final.jar:4.1.13.Final]
06:57:52   1> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]


00:44:13   1> [2017-11-06T01:44:10,386][INFO ][o.e.t.n.ESLoggingHandlerIT] [testLoggingHandler]: after test
00:44:13 FAILURE 2.60s | ESLoggingHandlerIT.testLoggingHandler <<< FAILURES!
00:44:13    > Throwable #1: java.lang.AssertionError: hot threads request
00:44:13    > Expected: <true>
00:44:13    >      but: was <false>
00:44:13    > 	at __randomizedtesting.SeedInfo.seed([46F99DB116F1541A:17661C86887BC59C]:0)
00:44:13    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
00:44:13    > 	at org.elasticsearch.test.MockLogAppender$PatternSeenEventExcpectation.assertMatched(MockLogAppender.java:153)
00:44:13    > 	at org.elasticsearch.test.MockLogAppender.assertAllExpectationsMatched(MockLogAppender.java:62)
00:44:13    > 	at org.elasticsearch.transport.netty4.ESLoggingHandlerIT.testLoggingHandler(ESLoggingHandlerIT.java:80)
00:44:13    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:44:13    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:44:13    > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:44:13    > 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
00:44:13    > 	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by jasontedor** [comment]
Duplicates #27306
