### ISSUE TITLE
Elasticsearch v.5.6.4 impossible to start with my Ubuntu 16.04

### ISSUE THREAD

**Issue by Sethenssen** [elastic/elasticsearch#27347]
**Elasticsearch version** (`Version: 5.6.4`):

**Plugins installed**: [`No`]

**JVM version** (`openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
`):

**OS version** (`Linux ruby 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`):

**Description of the problem including expected versus actual behavior**:
Hi, maybe something wrong with a lib missing or something else ? But I already done apt update && upgrade. JVM & JRE installed.
But it's not working and I don't know where I'm wrong.
Thanks for helping me.

**Steps to reproduce**:

 1. /etc/init.d/elasticsearch start
 2. /etc/init.d/elasticsearch status
 3. elasticsearch is failed

**Provide logs (if relevant)**:

**My computer:**
```
:: Finding distro...found as 'Ubuntu 16.04'
:: Finding hostname and user...found as 'root@ruby'
:: Finding kernel version...found as 'x86_64 Linux 4.10.0-38-generic'
:: Finding current CPU...found as 'Intel Core i7-6600U CPU @ 3.4GHz'
:: Finding current GPU...found as 'Not Found'
:: Finding current RAM usage...found as '2082MiB / 15937MiB'
```

jvm.options:
`-Xms2g
-Xmx2g`

elasticsearch.yml everything is commented except:
`http.port: 9200`

-----------------------------------
Here the status command:
-----------------------------------

`/etc/init.d/elasticsearch status`

```
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since ven. 2017-11-10 23:32:19 CET; 1s ago
     Docs: http://www.elastic.co
  Process: 5457 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid --quiet -Edefault.path.logs=${LOG_DIR} -Edefault.path.data=${DATA_DIR} -Edefault.path.conf=${CONF_DIR} (code=exited, status=1/FAILURE)
  Process: 5449 ExecStartPre=/usr/share/elasticsearch/bin/elasticsearch-systemd-pre-exec (code=exited, status=0/SUCCESS)
 Main PID: 5457 (code=exited, status=1/FAILURE)

nov. 10 23:32:17 ruby elasticsearch[5457]:         java.net.MalformedURLException: no protocol: ${codebase.httpasyncclient-4.1.2.jar}
nov. 10 23:32:17 ruby elasticsearch[5457]: java.security.policy : erreur d'ajout d'entrée :
nov. 10 23:32:17 ruby elasticsearch[5457]:         java.net.MalformedURLException: no protocol: ${codebase.securesm-1.1.jar}
nov. 10 23:32:17 ruby elasticsearch[5457]: java.security.policy : erreur d'ajout d'entrée :
nov. 10 23:32:17 ruby elasticsearch[5457]:         java.net.MalformedURLException: no protocol: ${codebase.lucene-core-6.6.1.jar}
nov. 10 23:32:17 ruby elasticsearch[5457]: java.security.policy : erreur d'ajout d'entrée :
nov. 10 23:32:17 ruby elasticsearch[5457]:         java.net.MalformedURLException: no protocol: ${codebase.lucene-misc-6.6.1.jar}
nov. 10 23:32:19 ruby systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
nov. 10 23:32:19 ruby systemd[1]: elasticsearch.service: Unit entered failed state.
nov. 10 23:32:19 ruby systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
```

----------------------------------------
Here the /var/log/elasticsearch
----------------------------------------

`cat elasticsearch.log`

```
[2017-11-10T23:32:17,747][INFO ][o.e.n.Node               ] [] initializing ...
[2017-11-10T23:32:17,823][INFO ][o.e.e.NodeEnvironment    ] [RQp07WJ] using [1] data paths, mounts [[/ (/dev/sda2)]], net usable_space [194.2gb], net total_space [218.4gb], spins? [no], types [ext4]
[2017-11-10T23:32:17,823][INFO ][o.e.e.NodeEnvironment    ] [RQp07WJ] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-11-10T23:32:17,824][INFO ][o.e.n.Node               ] node name [RQp07WJ] derived from node ID [RQp07WJoQoquruouO1g-dA]; set [node.name] to override
[2017-11-10T23:32:17,824][INFO ][o.e.n.Node               ] version[5.6.4], pid[5457], build[8bbedf5/2017-10-31T18:55:38.105Z], OS[Linux/4.10.0-38-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/9-internal/9-internal+0-2016-04-14-195246.buildd.src]
[2017-11-10T23:32:17,824][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/usr/share/elasticsearch]
[2017-11-10T23:32:18,666][INFO ][o.e.p.PluginsService     ] [RQp07WJ] loaded module [aggs-matrix-stats]
[2017-11-10T23:32:18,670][INFO ][o.e.p.PluginsService     ] [RQp07WJ] loaded module [ingest-common]
[2017-11-10T23:32:18,671][INFO ][o.e.p.PluginsService     ] [RQp07WJ] loaded module [lang-expression]
[2017-11-10T23:32:18,671][INFO ][o.e.p.PluginsService     ] [RQp07WJ] loaded module [lang-groovy]
[2017-11-10T23:32:18,671][INFO ][o.e.p.PluginsService     ] [RQp07WJ] loaded module [lang-mustache]
[2017-11-10T23:32:18,671][INFO ][o.e.p.PluginsService     ] [RQp07WJ] loaded module [lang-painless]
[2017-11-10T23:32:18,671][INFO ][o.e.p.PluginsService     ] [RQp07WJ] loaded module [parent-join]
[2017-11-10T23:32:18,671][INFO ][o.e.p.PluginsService     ] [RQp07WJ] loaded module [percolator]
[2017-11-10T23:32:18,671][INFO ][o.e.p.PluginsService     ] [RQp07WJ] loaded module [reindex]
[2017-11-10T23:32:18,671][INFO ][o.e.p.PluginsService     ] [RQp07WJ] loaded module [transport-netty3]
[2017-11-10T23:32:18,671][INFO ][o.e.p.PluginsService     ] [RQp07WJ] loaded module [transport-netty4]
[2017-11-10T23:32:18,672][INFO ][o.e.p.PluginsService     ] [RQp07WJ] no plugins loaded
[2017-11-10T23:32:19,360][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [main], exiting
java.lang.ExceptionInInitializerError: null
	at org.apache.lucene.analysis.miscellaneous.StemmerOverrideFilter$Builder.build(StemmerOverrideFilter.java:205) ~[lucene-analyzers-common-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:55:17]
	at org.apache.lucene.analysis.nl.DutchAnalyzer.<init>(DutchAnalyzer.java:133) ~[lucene-analyzers-common-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:55:17]
	at org.apache.lucene.analysis.nl.DutchAnalyzer.<init>(DutchAnalyzer.java:106) ~[lucene-analyzers-common-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:55:17]
	at org.elasticsearch.indices.analysis.PreBuiltAnalyzers$20.create(PreBuiltAnalyzers.java:246) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.indices.analysis.PreBuiltAnalyzers.getAnalyzer(PreBuiltAnalyzers.java:487) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.index.analysis.AnalysisRegistry$PrebuiltAnalysis.<init>(AnalysisRegistry.java:407) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.index.analysis.AnalysisRegistry$PrebuiltAnalysis.<init>(AnalysisRegistry.java:392) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.index.analysis.AnalysisRegistry.<init>(AnalysisRegistry.java:62) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.indices.analysis.AnalysisModule.<init>(AnalysisModule.java:177) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.node.Node.<init>(Node.java:340) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.4.jar:5.6.4]
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:468) ~[?:?]
	at java.security.AccessController.checkPermission(AccessController.java:894) ~[?:?]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:541) ~[?:?]
	at java.lang.Class.checkMemberAccess(Class.java:2584) ~[?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2092) ~[?:?]
	at org.apache.lucene.util.RamUsageEstimator$1.run(RamUsageEstimator.java:339) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.util.RamUsageEstimator$1.run(RamUsageEstimator.java:336) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.apache.lucene.util.RamUsageEstimator.shallowSizeOfInstance(RamUsageEstimator.java:336) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.util.RamUsageEstimator.shallowSizeOf(RamUsageEstimator.java:313) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.util.fst.ByteSequenceOutputs.<clinit>(ByteSequenceOutputs.java:154) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	... 21 more
```

**Comment by jasontedor** [comment]
You are trying to run on an extremely old early access build of JDK 9. First, this will not work, fundamental things have changed from those early EA builds to the GA build. Second, we do not even support the GA build at this time. Please use JDK 8, which we support.
