### ISSUE TITLE
[CI] QueueResizingEsThreadPoolExecutorTests fails on instantaneous tasks

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#27371]
I see a handful of tests tripping [this assertion that tasks should take more than 0ns to execute](https://github.com/elastic/elasticsearch/blob/a566942219d8a84deee719adb46860f69499431a/core/src/main/java/org/elasticsearch/common/util/concurrent/QueueResizingEsThreadPoolExecutor.java#L104) which looks like this:

```
queue capacity = 200, frame size = 10, targeted response rate = 1ms, task execution EWMA = 0s, adjustment amount = 50, QueueResizingEsThreadPoolExecutor[test-threadpool, queue capacity = 100, org.elasticsearch.common.util.concurrent.QueueResizingEsThreadPoolExecutor@3600de3f[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]]]
  1> [2017-11-14T11:20:10,206][INFO ][o.e.c.u.c.QueueResizingEsThreadPoolExecutorTests] --> executing a task [1] times
  1> [2017-11-14T11:20:10,207][INFO ][o.e.c.u.c.QueueResizingEsThreadPoolExecutorTests] --> executing a task [1] times
  1> [2017-11-14T11:20:10,214][INFO ][o.e.c.u.c.QueueResizingEsThreadPoolExecutorTests] --> executing a task [1] times
  1> [2017-11-14T11:20:10,215][INFO ][o.e.c.u.c.QueueResizingEsThreadPoolExecutorTests] --> executing a task [1] times
  1> [2017-11-14T11:20:10,215][INFO ][o.e.c.u.c.QueueResizingEsThreadPoolExecutorTests] --> executing a task [1] times
  1> [2017-11-14T11:20:10,216][INFO ][o.e.c.u.c.QueueResizingEsThreadPoolExecutorTests] [testExecutionEWMACalculation]: after test
  2> نوف 14, 2017 11:20:10 ص com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
  2> WARNING: Uncaught exception in thread: Thread[queuetest[T#2],5,TGRP-QueueResizingEsThreadPoolExecutorTests]
  2> java.lang.AssertionError: cannot calculate for instantaneous tasks, got: 0
  2> 	at __randomizedtesting.SeedInfo.seed([19F06E6F28AF3DC2]:0)
  2> 	at org.elasticsearch.common.util.concurrent.QueueResizingEsThreadPoolExecutor.calculateLambda(QueueResizingEsThreadPoolExecutor.java:104)
  2> 	at org.elasticsearch.common.util.concurrent.QueueResizingEsThreadPoolExecutor.afterExecute(QueueResizingEsThreadPoolExecutor.java:175)
  2> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1157)
  2> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  2> 	at java.lang.Thread.run(Thread.java:748)
  2> REPRODUCE WITH: gradle :core:test -Dtests.seed=19F06E6F28AF3DC2 -Dtests.class=org.elasticsearch.common.util.concurrent.QueueResizingEsThreadPoolExecutorTests -Dtests.method="testExecutionEWMACalculation" -Dtests.security.manager=true -Dtests.locale=ar-MA -Dtests.timezone=Pacific/Norfolk
ERROR   0.04s J1 | QueueResizingEsThreadPoolExecutorTests.testExecutionEWMACalculation <<< FAILURES!
```

The examples include the following:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=centos/325
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/1323
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/299
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/4838
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/231

This seems related to the (resolved) issue #26332, but this still looks to be an issue.

The zero duration comes from TimedRunnable#getTotalNanos() which subtracts two times obtained using `System.nanoTime()` and [its docs](https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#nanoTime()) say

> This method provides nanosecond precision, but not necessarily nanosecond resolution (that is, how frequently the value changes) - no guarantees are made except that the resolution is at least as good as that of `currentTimeMillis()`.

This means that occasionally getting 0 as the duration of a no-op task isn't totally unexpected, if you're unlucky and your timer resolution isn't very good.

**Comment by DaveCTurner** [comment]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.0+multijob-unix-compatibility/351/os=ubuntu/ was another one.
