### ISSUE TITLE
[CI] LowercaseProcessorTests fail with IllegalArgumentException

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#27373]
Seen in CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/707/console

This reproduces reliably on a variety of commits _with this seed_:

```
gradle :modules:ingest-common:test \
  -Dtests.seed=8E4B4EC280F97BC \
  -Dtests.class=org.elasticsearch.ingest.common.LowercaseProcessorTests \
  -Dtests.method="testTargetField" \
  -Dtests.security.manager=true \
  -Dtests.locale=pl-PL \
  -Dtests.timezone=Asia/Harbin
```

yields

```
Suite: org.elasticsearch.ingest.common.LowercaseProcessorTests
  1> [2017-11-14T11:37:22,242][WARN ][o.e.b.JNANatives         ] Unable to lock JVM Memory: error=78, reason=Function not implemented
  1> [2017-11-14T11:37:22,244][WARN ][o.e.b.JNANatives         ] This can result in part of the JVM being swapped out.
  1> [2017-11-14T19:37:27,752][INFO ][o.e.i.c.LowercaseProcessorTests] [testTargetField]: before test
  1> [2017-11-14T19:37:27,857][INFO ][o.e.i.c.LowercaseProcessorTests] [testTargetField]: after test
  2> REPRODUCE WITH: gradle :modules:ingest-common:test -Dtests.seed=8E4B4EC280F97BC -Dtests.class=org.elasticsearch.ingest.common.LowercaseProcessorTests -Dtests.method="testTargetField" -Dtests.security.manager=true -Dtests.locale=pl-PL -Dtests.timezone=Asia/Harbin
ERROR   0.16s | LowercaseProcessorTests.testTargetField <<< FAILURES!
   > Throwable #1: java.lang.IllegalArgumentException: cannot set [foo] with parent object of type [java.lang.String] as part of path [nBqeevOq.NxdLUNHAOe.񾭛.foo]
   >    at __randomizedtesting.SeedInfo.seed([8E4B4EC280F97BC:63A2C22235A8728D]:0)
   >    at org.elasticsearch.ingest.IngestDocument.setFieldValue(IngestDocument.java:506)
   >    at org.elasticsearch.ingest.IngestDocument.setFieldValue(IngestDocument.java:403)
   >    at org.elasticsearch.ingest.common.AbstractStringProcessor.execute(AbstractStringProcessor.java:67)
   >    at org.elasticsearch.ingest.common.AbstractStringProcessorTestCase.testTargetField(AbstractStringProcessorTestCase.java:111)
   >    at java.lang.Thread.run(Thread.java:748)
  2> NOTE: leaving temporary files on disk at: /Users/davidturner/src/elasticsearch-6.x/modules/ingest-common/build/testrun/test/J0/temp/org.elasticsearch.ingest.common.LowercaseProcessorTests_8E4B4EC280F97BC-001
  2> NOTE: test params are: codec=Lucene70, sim=RandomSimilarity(queryNorm=false): {}, locale=pl-PL, timezone=Asia/Harbin
  2> NOTE: Mac OS X 10.12.6 x86_64/Oracle Corporation 1.8.0_144 (64-bit)/cpus=8,threads=1,free=452972432,total=514850816
  2> NOTE: All tests run in this JVM: [LowercaseProcessorTests]
Completed [1/1] in 11.02s, 1 test, 1 error <<< FAILURES!
```

**Comment by talevy** [comment]
I'll take a look at this
