### ISSUE TITLE
[CI] remote.info/10_info/"Get an empty remote info" fails on 5.6 because of spec name change

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#27396]
1703c54c27f8f256def48015214e927a0407ff54 changed the namespacing of remote_info to [`cluster.remote_info`](https://github.com/elastic/elasticsearch/blob/5.6/rest-api-spec/src/main/resources/rest-api-spec/api/cluster.remote_info.json), but the test `remote.info/10_info` still [points at the old `remote.info` on 5.6](https://github.com/elastic/elasticsearch/blob/5.6/rest-api-spec/src/main/resources/rest-api-spec/test/remote.info/10_info.yaml#L7)

I think... only quickly skimmed the situation :)

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+intake/317/console

```
java.lang.RuntimeException: Failure at [remote.info/10_info:6]: rest api [remote.info] doesn't exist in the rest spec
	at __randomizedtesting.SeedInfo.seed([93166365EBE61884:1B425CBF451A757C]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:348)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:330)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
```

**Comment by clintongormley** [comment]
Sorry, fixed.
