### ISSUE TITLE
XContentBuilder.ensureNoSelfReferences() throws ConcurrentModificationException

### ISSUE THREAD

**Issue by floragunncom** [elastic/elasticsearch#27399]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.0.0-rc2, 6.0.0 GA

**Plugins installed**: []

**JVM version** (`java -version`):
Java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Mac OSX 10.10.5

**Description of the problem including expected versus actual behavior**:
XContentBuilder.ensureNoSelfReferences throws ConcurrentModificationException

<pre>
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_31]
	at java.util.HashMap$ValueIterator.next(HashMap.java:1458) ~[?:1.8.0_31]
	at org.elasticsearch.common.xcontent.XContentBuilder.ensureNoSelfReferences(XContentBuilder.java:1091) ~[elasticsearch-6.0.0-rc2.jar:6.0.0-rc2]
	at org.elasticsearch.common.xcontent.XContentBuilder.ensureNoSelfReferences(XContentBuilder.java:1092) ~[elasticsearch-6.0.0-rc2.jar:6.0.0-rc2]
	at org.elasticsearch.common.xcontent.XContentBuilder.ensureNoSelfReferences(XContentBuilder.java:1071) ~[elasticsearch-6.0.0-rc2.jar:6.0.0-rc2]
	at org.elasticsearch.common.xcontent.XContentBuilder.map(XContentBuilder.java:872) ~[elasticsearch-6.0.0-rc2.jar:6.0.0-rc2]
	at org.elasticsearch.action.index.IndexRequest.source(IndexRequest.java:314) ~[elasticsearch-6.0.0-rc2.jar:6.0.0-rc2]
	at org.elasticsearch.action.index.IndexRequest.source(IndexRequest.java:303) ~[elasticsearch-6.0.0-rc2.jar:6.0.0-rc2]
	at org.elasticsearch.action.index.IndexRequestBuilder.setSource(IndexRequestBuilder.java:97) ~[elasticsearch-6.0.0-rc2.jar:6.0.0-rc2]
</pre>

**Comment by jasontedor** [comment]
This appears to be client side and this needs a reproduction as I suspect user error allowing concurrent modification error. I suspect that `source` is being reused and modified by multiple threads and that's going to lead to this.

**Comment by jasontedor** [comment]
No additional feedback, closing.
