### ISSUE TITLE
Provide more actionable error message when installing an offline plugin in the plugins directory

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#27401]
Today if you try to install a plugin from a distribution that sits inside the plugins directory, you get a non-actionable error message:

```
Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [x-pack-5.6.3.zip]. Was the plugin built before 2.0?
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:334)
	at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:545)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:527)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:570)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:218)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:202)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

This is deliberate, we do not want anything in the plugins directory that is not a plugin, but we could provide a more actionable error message here. This behavior will be documented clearly after #27400 so this is low-priority.

**Comment by mayya-sharipova** [comment]
We have reverted the commit for this PR, as  Windows tests were failing: https://internal-ci.elastic.co/job/elastic+x-pack-elasticsearch+master+multijob-windows-compatibility/1536/console

```
15:11:45 Starting process 'command 'cmd''. Working directory: C:\Users\jenkins\workspace\elastic+x-pack-elasticsearch+master+multijob-windows-compatibility\elasticsearch-extra\x-pack-elasticsearch\docs\build\cluster\integTestCluster node0\cwd Command: cmd /C call C:\Users\jenkins\WORKSP~1\ELASTI~3\ELASTI~1\X-PACK~1\docs\build\cluster\INTEGT~1\ELASTI~1.0-A\bin\elasticsearch-plugin install file:/C:/Users/jenkins/workspace/elastic+x-pack-elasticsearch+master+multijob-windows-compatibility/elasticsearch-extra/x-pack-elasticsearch/docs/build/cluster/integTestCluster%20node0/plugins%20tmp/x-pack-7.0.0-alpha1-SNAPSHOT.zip
15:11:45 Successfully started process 'command 'cmd''
15:11:47 -> Downloading file:/C:/Users/jenkins/workspace/elastic x-pack-elasticsearch master multijob-windows-compatibility/elasticsearch-extra/x-pack-elasticsearch/docs/build/cluster/integTestCluster node0/plugins tmp/x-pack-7.0.0-alpha1-SNAPSHOT.zip
15:11:47 Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/jenkins/workspace/elastic+x-pack-elasticsearch+master+multijob-windows-compatibility/elasticsearch-extra/x-pack-elasticsearch/docs/build/cluster/integTestCluster%20node0/plugins%20tmp/x-pack-7.0.0-alpha1-SNAPSHOT.zip
15:11:47 	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
15:11:47 	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
15:11:47 	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
15:11:47 	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
15:11:47 	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
15:11:47 	at java.base/java.nio.file.Paths.get(Paths.java:84)
15:11:47 	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:332)
15:11:47 	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:254)
15:11:47 	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:222)
15:11:47 	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:213)
15:11:47 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
15:11:47 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
15:11:47 	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
15:11:47 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
15:11:47 	at org.elasticsearch.cli.Command.main(Command.java:90)
15:11:47 	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)
15:11:47 :x-pack-elasticsearch:docs:integTestCluster#installPluginPlugin FAILED
15:11:47 :x-pack-elasticsearch:docs:integTestCluster#installPluginPlugin (Thread[Task worker for ':' Thread 2,5,main]) completed. Took 1.191 secs.
```

Citing Jason Tedor here:

> we should step back and slowly try to fix the issue without builds for an entire OS failing over and over; ...the other problem that i see here is a suppress forbidden on the method that you changed yesterday which let Paths#get slipped in unnoticed; this is not your fault, but this is why i prefer that when we suppressed forbidden it’s tightly scoped (like move the forbidden invocation to its own method and suppress there and never add code to that other method) ... we suppress there for `getInputStream` which means adding any other forbidden API will now go unnoticed.. i wish suppress forbidden could be applied to a statement only, this to me is its biggest downside

**Comment by jasontedor** [comment]
@mayya-sharipova Is there anything that I can do to help on this one?

**Comment by williamrandolph** [comment]
This still reproduces. From a `7.6.2` build:

```
cd plugins/
curl -O https://artifacts.elastic.co/downloads/elasticsearch-plugins/discovery-ec2/discovery-ec2-7.6.2.zip
cd ..
bin/elasticsearch-plugin install file:///Users/wbrafford/work/es-builds/7.6.2/elasticsearch-7.6.2/plugins/discovery-ec2-7.6.2.zip
```

I don't think it would be too hard to fix this.

**Comment by interpreter95** [comment]
Hi @mayya-sharipova ,

Are you still working on this issue?
Otherwise, I'd like to try my hands on it 😃

**Comment by GiBot2** [comment]
I would like to help with this issue, but I'm unable to reproduce it.

I tried building version 7.6.2, mentioned by @williamrandolph, but the "./gradlew localDistro" throws an error. I also tried building the most recent version, but I couldn't find the executable called elasticsearch-plugins, which is the one I would use to reproduce the specific issue and check if the changes I made locally fixed it.

Can you help me?

**Comment by ChrisHegarty** [comment]
As of time of writing, with version 8, here is the latest error message when trying to install an already installed plugin:

The salient part of the message is:
  `already exists; if you need to update the plugin, uninstall it first using command 'remove discovery-ec2'`

e.g.
```
$ ./elasticsearch-8.0.0-SNAPSHOT/bin/elasticsearch-plugin install  file:///Users/chegar/git/elasticsearch/distribution/archives/darwin-aarch64-tar/build/install/elasticsearch-8.0.0-SNAPSHOT/plugins/discovery-ec2/discovery-ec2-7.6.2.zip 
-> Installing file:///Users/chegar/git/elasticsearch/distribution/archives/darwin-aarch64-tar/build/install/elasticsearch-8.0.0-SNAPSHOT/plugins/discovery-ec2/discovery-ec2-7.6.2.zip
-> Downloading file:///Users/chegar/git/elasticsearch/distribution/archives/darwin-aarch64-tar/build/install/elasticsearch-8.0.0-SNAPSHOT/plugins/discovery-ec2/discovery-ec2-7.6.2.zip
[=================================================] 100%   
-> Failed installing file:///Users/chegar/git/elasticsearch/distribution/archives/darwin-aarch64-tar/build/install/elasticsearch-8.0.0-SNAPSHOT/plugins/discovery-ec2/discovery-ec2-7.6.2.zip
-> Rolling back file:///Users/chegar/git/elasticsearch/distribution/archives/darwin-aarch64-tar/build/install/elasticsearch-8.0.0-SNAPSHOT/plugins/discovery-ec2/discovery-ec2-7.6.2.zip
-> Rolled back file:///Users/chegar/git/elasticsearch/distribution/archives/darwin-aarch64-tar/build/install/elasticsearch-8.0.0-SNAPSHOT/plugins/discovery-ec2/discovery-ec2-7.6.2.zip

ERROR: plugin directory [/Users/chegar/git/elasticsearch/distribution/archives/darwin-aarch64-tar/build/install/elasticsearch-8.0.0-SNAPSHOT/plugins/discovery-ec2] already exists; if you need to update the plugin, uninstall it first using command 'remove discovery-ec2'
```
