### ISSUE TITLE
[CI] MultiMatchQueryBuilderTests.testToQuery

### ISSUE THREAD

**Issue by andyb-elastic** [elastic/elasticsearch#27462]
Consistently reproduces locally

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/784/console

```
gradle :core:test -Dtests.seed=B6DE214910D3B042 -Dtests.class=org.elasticsearch.index.query.MultiMatchQueryBuilderTests -Dtests.method="testToQuery" -Dtests.security.manager=true -Dtests.locale=id-ID -Dtests.timezone=America/Cayman
```

```
FAILURE 0.22s J1 | MultiMatchQueryBuilderTests.testToQuery <<< FAILURES!
   > Throwable #1: java.lang.AssertionError:
   > Expected: ((((((((((((an instance of org.apache.lucene.search.BoostQuery or an instance of org.apache.lucene.search.TermQuery) or an instance of org.elasticsearch.common.lucene.all.AllTermQuery) or an instance of org.apache.lucene.search.BooleanQuery) or an instance of org.apache.lucene.search.DisjunctionMaxQuery) or an instance of org.apache.lucene.search.FuzzyQuery) or an instance of org.elasticsearch.common.lucene.search.MultiPhrasePrefixQuery) or an instance of org.apache.lucene.search.MatchAllDocsQuery) or an instance of org.apache.lucene.queries.ExtendedCommonTermsQuery) or an instance of org.apache.lucene.search.MatchNoDocsQuery) or an instance of org.apache.lucene.search.PhraseQuery) or an instance of org.apache.lucene.search.PointRangeQuery) or an instance of org.apache.lucene.search.IndexOrDocValuesQuery)
   >      but: was <blended(terms:[mapped_string:, mapped_string_2:^5.0])>
   >    at __randomizedtesting.SeedInfo.seed([B6DE214910D3B042:41252377615075A8]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.index.query.MultiMatchQueryBuilderTests.doAssertLuceneQuery(MultiMatchQueryBuilderTests.java:162)
   >    at org.elasticsearch.index.query.MultiMatchQueryBuilderTests.doAssertLuceneQuery(MultiMatchQueryBuilderTests.java:61)
   >    at org.elasticsearch.test.AbstractQueryTestCase.assertLuceneQuery(AbstractQueryTestCase.java:678)
   >    at org.elasticsearch.test.AbstractQueryTestCase.testToQuery(AbstractQueryTestCase.java:592)
   >    at java.lang.Thread.run(Thread.java:748)
```

Looks like @jimczi made some changes to this class a few days ago on 6.x, so assigning there, feel free to send it back if unrelated

**Comment by jimczi** [comment]
Fixed by https://github.com/elastic/elasticsearch/commit/3437191f172e53cc6f1beebdd322df48d73fb923
Thanks @andyb-elastic
