### ISSUE TITLE
Translog [internal:index/shard/recovery/start_recovery]]; nested: AlreadyClosedException[translog is already closed]

### ISSUE THREAD

**Issue by wuyunfeng** [elastic/elasticsearch#27465]
I find these related issues:
https://github.com/elastic/elasticsearch/pull/19035
https://github.com/elastic/elasticsearch/pull/15420
https://github.com/elastic/elasticsearch/issues/15333

Hope some one can explain my problem more definitely. thanks a lot.

Elasticsearch version 2.3
**Plugins installed**: [ crate-core ,discovery-srv]

**JVM version** (`java -version`):1.8.0_121

**OS version** (`uname -a` if on a Unix-like system):Linux  localhost 2.6.32_1-19-0-0 #2 SMP Wed Aug 31 20:43:21 CST 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Our online ES-cluster suffer disk full exception
 2. we delete  a lot of indices to release disk space
 3.  node enter recovery phrase, some index always sitting in initializing state, we found AlreadyClosedException[translog is already closed]. some index's log is similar althrough the following log display different index name.

**Provide logs (if relevant)**:

a lot of such below logs:
[2017-11-13 13:58:51,732][ERROR][index.engine             ] [Tommy] [iam-proxy-2017-11-13][5] failed to merge
java.io.IOException: No space left on device
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211)
        at java.nio.channels.Channels.writeFullyImpl(Channels.java:78)
        at java.nio.channels.Channels.writeFully(Channels.java:101)
        at java.nio.channels.Channels.access$000(Channels.java:61)
        at java.nio.channels.Channels$1.write(Channels.java:174)
        at org.apache.lucene.store.FSDirectory$FSIndexOutput$1.write(FSDirectory.java:278)
        at java.util.zip.CheckedOutputStream.write(CheckedOutputStream.java:73)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
        at org.apache.lucene.store.OutputStreamIndexOutput.writeBytes(OutputStreamIndexOutput.java:53)
        at org.apache.lucene.store.RateLimitedIndexOutput.writeBytes(RateLimitedIndexOutput.java:73)
        at org.apache.lucene.store.DataOutput.writeBytes(DataOutput.java:52)
        at org.apache.lucene.util.packed.DirectWriter.flush(DirectWriter.java:86)
        at org.apache.lucene.util.packed.DirectWriter.add(DirectWriter.java:78)
        at org.apache.lucene.codecs.lucene54.Lucene54DocValuesConsumer.addNumericField(Lucene54DocValuesConsumer.java:245)
        at org.apache.lucene.codecs.lucene54.Lucene54DocValuesConsumer.addSortedField(Lucene54DocValuesConsumer.java:614)
        at org.apache.lucene.codecs.lucene54.Lucene54DocValuesConsumer.addSortedSetField(Lucene54DocValuesConsumer.java:653)
        at org.apache.lucene.codecs.perfield.PerFieldDocValuesFormat$FieldsWriter.addSortedSetField(PerFieldDocValuesFormat.java:131
)
        at org.apache.lucene.codecs.DocValuesConsumer.mergeSortedSetField(DocValuesConsumer.java:736)
        at org.apache.lucene.codecs.DocValuesConsumer.merge(DocValuesConsumer.java:219)
        at org.apache.lucene.index.SegmentMerger.mergeDocValues(SegmentMerger.java:150)
        at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:105)

[DEBUG][indices.recovery         ] [Shang-Chi] [iam-risk-2017-11-15][6] Got exception on recovery
RemoteTransportException[[Tommy][10.59.23.39:9200][internal:index/shard/recovery/start_recovery]]; nested: AlreadyClosedException[tran
slog is already closed];
Caused by: org.apache.lucene.store.AlreadyClosedException: translog is already closed
        at org.elasticsearch.index.translog.Translog.ensureOpen(Translog.java:1904)
        at org.elasticsearch.index.translog.Translog.newView(Translog.java:629)
        at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:122)
        at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:128)
        at org.elasticsearch.indices.recovery.RecoverySource.access$200(RecoverySource.java:52)
        at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:
137)
        at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:
134)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:300)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by jasontedor** [comment]
I do not see a bug here, instead a situation that arose after you ran out of disk space. Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by wuyunfeng** [comment]
@jasontedor 

Our online cluster state is always yellow, because some replica shard is always in initializing state. and the 

> 

 [internal:index/shard/recovery/start_recovery]]; nested: AlreadyClosedException[tran
slog is already closed]

>  periodic log such message.  The recovery do not finished forever because encountering **translog AlreadyClosedException**

**Comment by wuyunfeng** [comment]
@jasontedor 
The `RecoveryTarget`  method `doRecovery` snippet `if (cause instanceof AlreadyClosedException) {
                onGoingRecoveries.failRecovery(recoveryStatus.recoveryId(), new RecoveryFailedException(request, "source shard is closed", cause), false);
                return;
            }`
The **AlreadyClosedException**  seems not report to  **master** the failed recovery message,so the master always sign this shard in **initializing** state, result in the cluster always **yellow**.
`{
   "cluster_name": "xxxxx",
   "status": "yellow",
   "timed_out": false,
   "number_of_nodes": 7,
   "number_of_data_nodes": 4,
   "active_primary_shards": 1500,
   "active_shards": 2990,
   "relocating_shards": 0,
   "initializing_shards": 11,
   "unassigned_shards": 1,
   "delayed_unassigned_shards": 0,
   "number_of_pending_tasks": 0,
   "number_of_in_flight_fetch": 0,
   "task_max_waiting_in_queue_millis": 0,
   "active_shards_percent_as_number": 99.60026648900732
}`

**Comment by songtianyi** [comment]
@jasontedor 
It is a bug or flaw! Please reopen the issue.
Obviously, after disk space released, ES should auto recover from the bad situation like other services.
As i know, restart is the only option for ES 2.2.2 version.
[Same question](https://discuss.elastic.co/t/elasticsearch-didnt-auto-recover-from-disk-space-full/110172) in es forum
