### ISSUE TITLE
[CI] RemoteClusterConnectionTests#testRemoteConnectionInfoBwComp test failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#27490]
This failure reproduces.

```
Suite: org.elasticsearch.transport.RemoteClusterConnectionTests
  1> [2017-11-22T09:53:50,683][WARN ][o.e.b.JNANatives         ] Unable to lock JVM Memory: error=12, reason=Cannot allocate memory
  1> [2017-11-22T09:53:50,685][WARN ][o.e.b.JNANatives         ] This can result in part of the JVM being swapped out.
  1> [2017-11-22T09:53:50,685][WARN ][o.e.b.JNANatives         ] Increase RLIMIT_MEMLOCK, soft limit: 65536, hard limit: 65536
  1> [2017-11-22T09:53:50,685][WARN ][o.e.b.JNANatives         ] These can be adjusted by modifying /etc/security/limits.conf, for example: 
  1>    # allow user 'mvg' mlockall
  1>    mvg soft memlock unlimited
  1>    mvg hard memlock unlimited
  1> [2017-11-22T09:53:50,686][WARN ][o.e.b.JNANatives         ] If you are logged in interactively, you will have to re-login for the new limits to take effect.
  1> [2017-11-22T03:53:51,150][INFO ][o.e.t.RemoteClusterConnectionTests] [testRemoteConnectionInfoBwComp]: before test
  1> [2017-11-22T03:53:51,186][INFO ][o.e.t.RemoteClusterConnectionTests] [testRemoteConnectionInfoBwComp]: after test
  2> REPRODUCE WITH: gradle :core:test -Dtests.seed=78B866491658224A -Dtests.class=org.elasticsearch.transport.RemoteClusterConnectionTests -Dtests.method="testRemoteConnectionInfoBwComp" -Dtests.security.manager=true -Dtests.locale=es-PE -Dtests.timezone=America/Indiana/Petersburg
FAILURE 0.13s | RemoteClusterConnectionTests.testRemoteConnectionInfoBwComp <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: illegal transport ID from node of version: 5.6.5 got: 1024 expected: 1
   >    at __randomizedtesting.SeedInfo.seed([78B866491658224A:4FA0695EA23DC024]:0)
   >    at org.elasticsearch.common.transport.TransportAddress.<init>(TransportAddress.java:84)
   >    at org.elasticsearch.common.transport.TransportAddress.<init>(TransportAddress.java:73)
   >    at org.elasticsearch.common.io.stream.StreamInput.readList(StreamInput.java:909)
   >    at org.elasticsearch.transport.RemoteConnectionInfo.<init>(RemoteConnectionInfo.java:61)
   >    at org.elasticsearch.transport.RemoteClusterConnectionTests.testRemoteConnectionInfoBwComp(RemoteClusterConnectionTests.java:791)
   >    at java.lang.Thread.run(Thread.java:748)
  2> NOTE: leaving temporary files on disk at: /home/mvg/dev/projects/elasticsearch/6.x/elasticsearch/core/build/testrun/test/J0/temp/org.elasticsearch.transport.RemoteClusterConnectionTests_78B866491658224A-001
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=216, maxMBSortInHeap=5.117707204542016, sim=RandomSimilarity(queryNorm=true): {}, locale=es-PE, timezone=America/Indiana/Petersburg
  2> NOTE: Linux 4.4.0-98-generic amd64/Oracle Corporation 1.8.0_144 (64-bit)/cpus=12,threads=1,free=422866072,total=514850816
  2> NOTE: All tests run in this JVM: [RemoteClusterConnectionTests]
Completed [1/1] in 0.89s, 1 test, 1 failure <<< FAILURES!

```

**Comment by martijnvg** [comment]
Fixed via: https://github.com/elastic/elasticsearch/commit/9ea29d73a9b90b7cd9bd338cfc7e7abaa9bc9634
