### ISSUE TITLE
Visuals based on a boolean, ends up in a java.lang.IllegalArgumentException: Can't parse boolean value [0], expected [true] or [false]

### ISSUE THREAD

**Issue by spiderdaimi** [elastic/elasticsearch#27492]
**Elasticsearch version**
```
Version: 6.0.0, Build: 8f0685b/2017-11-10T18:41:22.859Z, JVM: 1.8.0_151
```

**Plugins installed**
No

**JVM version**
```
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode
```

**OS version**
```
Linux 888bdca2031d 4.9.49-moby #1 SMP Wed Sep 27 23:17:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:
Visuals based on a boolean, ends up in a `java.lang.IllegalArgumentException: Can't parse boolean value [0], expected [true] or [false]` Exception when applying a filter through these. 
_Not sure if this is an ES or a Kibana issue_?

**Steps to reproduce**:
1: Spin up a docker based on 6.0.0 
```
docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it --name elk6 sebp/elk:600
```

2: Autocreate index by PUT
```
curl -XGET http://127.0.0.1:9200/_cat/indices?v
health status index   uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   .kibana 8xgP-GdLTxS7aQjOZvR3kQ   1   1          1            0      3.6kb          3.6kb

curl -H "Content-type: application/json" -XPUT localhost:9200/myindex/mytype/one -d '{
  "a": 3,
  "foo": false
}'
{"_index":"myindex","_type":"mytype","_id":"one","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1}

curl -XGET http://127.0.0.1:9200/_cat/indices?v
health status index   uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   myindex Gu9HKs9xQsGzB7QfgrY2HQ   5   1          1            0      3.2kb          3.2kb
yellow open   .kibana 8xgP-GdLTxS7aQjOZvR3kQ   1   1          1            0      3.6kb          3.6kb
```

3: Create index pattern from Kibana Management

4: Create visual TagCloud on Term foo

5: Click 'false' to add a filter. Will produce Exception. See attachment and log.

<img width="1326" alt="screen shot 2017-11-22 at 13 38 52" src="https://user-images.githubusercontent.com/33057894/33129481-42c64644-cf90-11e7-80b6-abe021b90797.png">

**Provide logs (if relevant)**:
```
[2017-11-22T12:38:48,080][DEBUG][o.e.a.s.TransportSearchAction] [ptUUvKG] All shards failed for phase: [query]
org.elasticsearch.index.query.QueryShardException: failed to create query: {
  "bool" : {
    "must" : [
      {
        "match_all" : {
          "boost" : 1.0
        }
      },
      {
        "match_phrase" : {
          "foo" : {
            "query" : 0,
            "slop" : 0,
            "boost" : 1.0
          }
        }
      }
    ],
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:327) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:310) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:669) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:530) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:506) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:302) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:288) [elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:284) [elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:964) [elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.0.0.jar:6.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IllegalArgumentException: Can't parse boolean value [0], expected [true] or [false]
	at org.elasticsearch.index.mapper.BooleanFieldMapper$BooleanFieldType.indexedValueForSearch(BooleanFieldMapper.java:164) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.index.mapper.TermBasedFieldType.termQuery(TermBasedFieldType.java:54) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.index.mapper.BooleanFieldMapper$BooleanFieldType.termQuery(BooleanFieldMapper.java:121) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.index.search.MatchQuery.termQuery(MatchQuery.java:289) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.index.search.MatchQuery.blendTermQuery(MatchQuery.java:469) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.index.search.MatchQuery.parse(MatchQuery.java:253) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.index.query.MatchPhraseQueryBuilder.doToQuery(MatchPhraseQueryBuilder.java:152) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:98) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:405) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:379) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:98) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$2(QueryShardContext.java:311) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:323) ~[elasticsearch-6.0.0.jar:6.0.0]
	... 13 more
```

**Comment by cbuescher** [comment]
@spiderdaimi thanks for opening the issue. The rejection of "0" as a boolean value is expected in 6.0, all values other than `true/"true"` and `false/"false"` have been deprecated in 5.3.0 and are not supported any more in 6.0 (https://www.elastic.co/guide/en/elasticsearch/reference/5.6/boolean.html) 
I don't fully know how this query gets created on the Kibana side, I assume you are also using the current 6.0 version there. I will move this issue over to the Kibana folks.

**Comment by cbuescher** [comment]
@spiderdaimi Github doesn't seem to allow moving issues to other repos easily, I tried using https://github-issue-mover.appspot.com/ but that apparently would open the new issue in my name, so can I ask you to re-open this issue in the Kibana repo at https://github.com/elastic/kibana yourself? Sorry for that.

**Comment by spiderdaimi** [comment]
Sure, I will. Thx for fast feedback.

**Comment by spiderdaimi** [comment]
Recreated here: https://github.com/elastic/kibana/issues/15114

**Comment by reganp** [comment]
When is this issue being fixed?  I'm getting it in latest Kibana version now.
