### ISSUE TITLE
QueryBuilderBWCIT failing on 6.x

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#27510]
```
   > Throwable #1: java.io.EOFException
   >    at __randomizedtesting.SeedInfo.seed([4F6E53F00DC6A3E0:4CF2BF33E469C0F0]:0)
   >    at org.elasticsearch.common.io.stream.InputStreamStreamInput.readByte(InputStreamStreamInput.java:59)
   >    at org.elasticsearch.common.io.stream.FilterStreamInput.readByte(FilterStreamInput.java:40)
   >    at org.elasticsearch.common.io.stream.StreamInput.readVInt(StreamInput.java:187)
   >    at org.elasticsearch.common.io.stream.StreamInput.readArraySize(StreamInput.java:951)
   >    at org.elasticsearch.common.io.stream.StreamInput.readString(StreamInput.java:347)
   >    at org.elasticsearch.common.unit.Fuzziness.<init>(Fuzziness.java:83)
   >    at org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:733)
   >    at org.elasticsearch.index.query.MatchQueryBuilder.<init>(MatchQueryBuilder.java:129)
   >    at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:46)
   >    at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:39)
   >    at org.elasticsearch.bwc.QueryBuilderBWCIT.testQueryBuilderBWC(QueryBuilderBWCIT.java:206)
   >    at java.lang.Thread.run(Thread.java:748)
```

This reproduces as follows:

```
REPRODUCE WITH: gradle :qa:query-builder-bwc:v5.6.5-SNAPSHOT#upgradedQueryBuilderTestRunner \
  -Dtests.seed=4F6E53F00DC6A3E0 \
  -Dtests.class=org.elasticsearch.bwc.QueryBuilderBWCIT \
  -Dtests.method="testQueryBuilderBWC" \
  -Dtests.security.manager=true \
  -Dtests.locale=en \
  -Dtests.timezone=Etc/UTC
```

See e.g. https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/717

This is testing BWC against 5.6.5 which hasn't been under test recently because of #27397, but now that's been merged this has shown up.

**Comment by martijnvg** [comment]
This qa test was designed to run only against 6.0+ nodes. I'll fix that in this qa module's gradle file.

**Comment by martijnvg** [comment]
Fixed by the 3 above commits in the respective 6.x, 6.1 and 6.0 branches.
