### ISSUE TITLE
AssertionError in InternalEngineTests.testRefreshScopedSearcher

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#27514]
`InternalEngineTests.testRefreshScopedSearcher` threw an `AssertionError` in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/858/console

```
FAILURE 0.12s J0 | InternalEngineTests.testRefreshScopedSearcher <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected same:<IndexSearcher(ElasticsearchDirectoryReader(FilterLeafReader(_0(7.1.0):c10) FilterLeafReader(_1(7.1.0):c1)); executor=null)> was not:<IndexSearcher(ElasticsearchDirectoryReader(FilterLeafReader(_0(7.1.0):c10) FilterLeafReader(_1(7.1.0):c1)); executor=null)>
   > 	at __randomizedtesting.SeedInfo.seed([168988A8C61979AC:7115CA98C7335368]:0)
   > 	at org.elasticsearch.index.engine.InternalEngineTests.testRefreshScopedSearcher(InternalEngineTests.java:3950)
   > 	at java.lang.Thread.run(Thread.java:745)
```

```
REPRODUCE WITH: gradle :core:test \
  -Dtests.seed=168988A8C61979AC \
  -Dtests.class=org.elasticsearch.index.engine.InternalEngineTests \
  -Dtests.method="testRefreshScopedSearcher" \
  -Dtests.security.manager=true \
  -Dtests.locale=pt \
  -Dtests.timezone=JST
```

This did not reproduce for me locally.

**Comment by dnhatn** [comment]
Another instance on master but did not reproduce for locally. https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/5547/console

```
./gradlew :server:test \
  -Dtests.seed=8A11D983DCE84E35 \
  -Dtests.class=org.elasticsearch.index.engine.InternalEngineTests \
  -Dtests.method="testRefreshScopedSearcher" \
  -Dtests.security.manager=true \
  -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" \
  -Dtests.locale=es-PA \
  -Dtests.timezone=Pacific/Guadalcanal
```

Log: [testRefreshScopedSearcher.txt](https://github.com/elastic/elasticsearch/files/1669749/testRefreshScopedSearcher.txt)
