### ISSUE TITLE
elasticsearch packaging: x-pack missing from packaging process

### ISSUE THREAD

**Issue by minfrin** [elastic/elasticsearch#27561]
**Elasticsearch version** (`bin/elasticsearch --version`):

Version: 6.0.0, Build: 8f0685b/2017-11-10T18:41:22.859Z, JVM: 1.8.0_151

**Plugins installed**: []

**JVM version** (`java -version`):

openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Linux elastic01 4.4.0-1041-aws #50-Ubuntu SMP Wed Nov 15 22:18:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

- Install elasticsearch from debian package on Ubuntu Xenial

- Attempt to install x-pack as follows:

sudo bin/elasticsearch-plugin install x-pack

- Installation fails as below.

**Provide logs (if relevant)**:

root@zonza5-hg-unstable-black-elastic01:/usr/share/elasticsearch# sudo bin/elasticsearch-plugin install x-pack

Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at org.elasticsearch.plugins.InstallPluginCommand.urlExists(InstallPluginCommand.java:298)
	at org.elasticsearch.plugins.InstallPluginCommand.getElasticUrl(InstallPluginCommand.java:265)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:221)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:213)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:204)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

The package appears to be making an unaudited call to the internet in an attempt to download and install x-pack from an undisclosed location, rather than just installing the elasticsearch-x-pack package from the repo.

The documented workaround is to download and install x-pack manually, however this defeats the purpose of packaging.

To fix this, package x-pack.

**Comment by jasontedor** [comment]
This would be treated as an issue in the plugin installer (not as an X-Pack issue). As such, it is an open source issue which is handled here. However, this issue does not reproduce and I suspect a problem on your end.

```bash
10:58:21 ⌂66% [jason:~] $ curl -sS -L https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0.tar.gz | tar x -C ~/elasticsearch/
10:58:28 ⌂63% [jason:~] $ yes | ~/elasticsearch/elasticsearch-6.0.0/bin/elasticsearch-plugin install x-pack
-> Downloading x-pack from elastic
[=================================================] 100%   
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission \\.\pipe\* read,write
* java.lang.RuntimePermission accessClassInPackage.com.sun.activation.registries
* java.lang.RuntimePermission getClassLoader
* java.lang.RuntimePermission setContextClassLoader
* java.lang.RuntimePermission setFactory
* java.net.SocketPermission * connect,accept,resolve
* java.security.SecurityPermission createPolicy.JavaPolicy
* java.security.SecurityPermission getPolicy
* java.security.SecurityPermission putProviderProperty.BC
* java.security.SecurityPermission setPolicy
* java.util.PropertyPermission * read,write
* java.util.PropertyPermission sun.nio.ch.bugLevel write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@        WARNING: plugin forks a native controller        @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
This plugin launches a native controller that is not subject to the Java
security manager nor to system call filters.
Elasticsearch keystore is required by plugin [x-pack], creating...
-> Installed x-pack
10:58:43 [jason:~] $ ~/elasticsearch/elasticsearch-6.0.0/bin/elasticsearch-plugin list
x-pack
```

> The package appears to be making an unaudited call to the internet in an attempt to download and install x-pack from an undisclosed location, rather than just installing the elasticsearch-x-pack package from the repo.

I'm not sure what you mean by this. The plugin is an official plugin. As such, it's downloaded from artifacts.elastic.co via HTTPS. Plugins are not distributed via apt-get and yum repositories.

**Comment by minfrin** [comment]
> I'm not sure what you mean by this.

At the very least, the bin/elasticsearch-plugin tool is making a call to the internet, ignoring the http_proxy/https_proxy environment variables. This is why we're failing in our environment - our servers don't have access to the net.

This attempt by elasticsearch-plugin to bypass the packaging defeats the packaging process.

**Comment by jasontedor** [comment]
Did you set the proxy as explained in the docs?

**Comment by minfrin** [comment]
I didn't do any special setup, no - as a command line tool I was expecting http_proxy and friends to be picked up automatically from the environment in the usual way.

**Comment by jasontedor** [comment]
They are not in Java, you have to set those system properties that are mentioned in the docs.
