### ISSUE TITLE
[CI] CoreFullClusterRestartIT testRecovery fails to find old segments

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#27649]
see https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+oracle-periodic/1556/console

```
REPRODUCE WITH: gradle :qa:full-cluster-restart:v6.1.0-SNAPSHOT#upgradedClusterTestRunner \
  -Dtests.seed=BA8111C3B9EB2432 \
  -Dtests.class=org.elasticsearch.upgrades.FullClusterRestartIT \
  -Dtests.method="testRecovery" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-VE \
  -Dtests.timezone=MET
```

```
java.lang.AssertionError: expected at least 1 old segment. Actual: 0
	at __randomizedtesting.SeedInfo.seed([BA8111C3B9EB2432:7B71686F94BBEE95]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failEquals(Assert.java:185)
	at org.junit.Assert.assertNotEquals(Assert.java:199)
	at org.elasticsearch.upgrades.FullClusterRestartIT.testRecovery(FullClusterRestartIT.java:697)
```

**Comment by bleskes** [comment]
This has been resolved.
