### ISSUE TITLE
[TEST] RecoveryIT testRelocationWithConcurrentIndexing fails randomly on 6.x

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#27674]
Build link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=oraclelinux/390/consoleFull

Reproduce (cannot reproduce locally):

```
gradle :qa:rolling-upgrade:v6.1.0-SNAPSHOT#mixedClusterTestRunner -Dtests.seed=F975F1EC42AA64E8 -Dtests.class=org.elasticsearch.upgrades.RecoveryIT -Dtests.method="testRelocationWithConcurrentIndexing" -Dtests.security.manager=true -Dtests.locale=en-AU -Dtests.timezone=America/Nassau
```

Failure:

```
> Throwable #1: java.net.ConnectException
17:27:13    > 	at __randomizedtesting.SeedInfo.seed([F975F1EC42AA64E8:4512F8F325D10AD0]:0)
17:27:13    > 	at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:168)
17:27:13    > 	at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:561)
17:27:13    > 	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:822)
17:27:13    > 	at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:183)
17:27:13    > 	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:210)
17:27:13    > 	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:155)
17:27:13    > 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
17:27:13    > 	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192)
17:27:13    > 	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
17:27:13    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dnhatn** [comment]
Log: 
[testRelocationWithConcurrentIndexing.txt](https://github.com/elastic/elasticsearch/files/1579665/testRelocationWithConcurrentIndexing.txt)

**Comment by dnhatn** [comment]
Looks like that we could not bootstrap ES because seccomp was unavailable. @jasontedor, Could you please take a look on this? Thank you.

```
Suite: org.elasticsearch.upgrades.RecoveryIT
  1> [2017-12-05T17:27:09,296][WARN ][o.e.b.JNANatives         ] unable to install syscall filter: 
  1> java.lang.UnsupportedOperationException: seccomp unavailable: CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER are needed
  2> REPRODUCE WITH: gradle :qa:rolling-upgrade:v6.1.0-SNAPSHOT#mixedClusterTestRunner -Dtests.seed=F975F1EC42AA64E8 -Dtests.class=org.elasticsearch.upgrades.RecoveryIT -Dtests.method="testRelocationWithConcurrentIndexing" -Dtests.security.manager=true -Dtests.locale=en-AU -Dtests.timezone=America/Nassau
  1> 	at org.elasticsearch.bootstrap.SystemCallFilter.linuxImpl(SystemCallFilter.java:341) ~[elasticsearch-6.2.0-SNAPSHOT.jar:6.2.0-SNAPSHOT]
  1> 	at org.elasticsearch.bootstrap.SystemCallFilter.init(SystemCallFilter.java:616) ~[elasticsearch-6.2.0-SNAPSHOT.jar:6.2.0-SNAPSHOT]
  1> 	at org.elasticsearch.bootstrap.JNANatives.tryInstallSystemCallFilter(JNANatives.java:258) [elasticsearch-6.2.0-SNAPSHOT.jar:6.2.0-SNAPSHOT]
  1> 	at org.elasticsearch.bootstrap.Natives.tryInstallSystemCallFilter(Natives.java:113) [elasticsearch-6.2.0-SNAPSHOT.jar:6.2.0-SNAPSHOT]
  1> 	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:109) [elasticsearch-6.2.0-SNAPSHOT.jar:6.2.0-SNAPSHOT]
  1> 	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:80) [framework-6.2.0-SNAPSHOT.jar:6.2.0-SNAPSHOT]
  1> 	at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:190) [framework-6.2.0-SNAPSHOT.jar:6.2.0-SNAPSHOT]
  1> 	at java.lang.Class.forName0(Native Method) [?:1.8.0_151]
  1> 	at java.lang.Class.forName(Class.java:348) [?:1.8.0_151]
  1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:592) [randomizedtesting-runner-2.5.2.jar:?]
  1> [2017-12-05T17:27:09,308][WARN ][o.e.b.JNANatives         ] Unable to lock JVM Memory: error=12, reason=Cannot allocate memory
  1> [2017-12-05T17:27:09,308][WARN ][o.e.b.JNANatives         ] This can result in part of the JVM being swapped out.
  1> [2017-12-05T17:27:09,309][WARN ][o.e.b.JNANatives         ] Increase RLIMIT_MEMLOCK, soft limit: 65536, hard limit: 65536
  1> [2017-12-05T17:27:09,309][WARN ][o.e.b.JNANatives         ] These can be adjusted by modifying /etc/security/limits.conf, for example: 
  1> 	# allow user 'jenkins' mlockall
  1> 	jenkins soft memlock unlimited
  1> 	jenkins hard memlock unlimited
  1> [2017-12-05T17:27:09,309][WARN ][o.e.b.JNANatives         ] If you are logged in interactively, you will have to re-login for the new limits to take effect.
  1> [2017-12-05T12:27:09,987][INFO ][o.e.u.RecoveryIT         ] [testRelocationWithConcurrentIndexing]: before test
  1> [2017-12-05T12:27:10,012][INFO ][o.e.u.RecoveryIT         ] initializing REST clients against [http://[::1]:45460]
  1> [2017-12-05T12:27:12,015][INFO ][o.e.u.RecoveryIT         ] [testRelocationWithConcurrentIndexing]: after test
ERROR   2.09s | RecoveryIT.testRelocationWithConcurrentIndexing <<< FAILURES!
   > Throwable #1: java.net.ConnectException
   > 	at __randomizedtesting.SeedInfo.seed([F975F1EC42AA64E8:4512F8F325D10AD0]:0)
   > 	at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:168)
   > 	at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:561)
   > 	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:822)
   > 	at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:183)
   > 	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:210)
   > 	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:155)
   > 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
   > 	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192)
   > 	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
   > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jasontedor** [comment]
`seccomp` being unavailable should not prevent startup unless bootstrap checks are enforced which they are not in tests since we bind to localhost. Please double check the logs.

**Comment by dnhatn** [comment]
Closing. This test has not failed for the last three months.
