### ISSUE TITLE
[CI] OpenCloseIndexIT.testOpenWaitingForActiveShardsFailed 

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#27670]
Link to build:
```
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/795/console
```

Reproduce:
```
gradle :core:integTest -Dtests.seed=C76BEE284B3397DD -Dtests.class=org.elasticsearch.indices.state.OpenCloseIndexIT -Dtests.method="testOpenWaitingForActiveShardsFailed" -Dtests.security.manager=true -Dtests.locale=mt-MT -Dtests.timezone=America/Aruba
```

But could not reproduce locally.

Fails with:
```
> Throwable #1: java.lang.AssertionError: OpenIndexResponse failed - not acked
14:34:40    > Expected: <true>
14:34:40    >      but: was <false>
14:34:40    > 	at __randomizedtesting.SeedInfo.seed([C76BEE284B3397DD:BD466411F015E4D4]:0)
14:34:40    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
14:34:40    > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:124)
14:34:40    > 	at org.elasticsearch.indices.state.OpenCloseIndexIT.testOpenWaitingForActiveShardsFailed(OpenCloseIndexIT.java:311)
14:34:40    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jpountz** [comment]
Fixed via https://github.com/elastic/elasticsearch/commit/0b102f63721472d7de89c21c78c9210aed90e7de.
