### ISSUE TITLE
exception occur when use performRequestAsync

### ISSUE THREAD

**Issue by OuyangKevin** [elastic/elasticsearch#27684]
**Describe the feature**:

when i use performRequestAsync like this,it occur exeception:

```
public static HashMap<String, String> baseParams = new HashMap<String,String>();

    public static BasicHeader header = new BasicHeader("Content-Type","application/json");

    static{
        baseParams.put("pretty", "true");
    }

    public static void main(String[] args) throws Exception {
        final int port = 9200;
        List<String> ips = new ArrayList<String>();
        ips.add("127.0.0.1");

        RestClient client;
        HttpHost[] hosts = new HttpHost[ips.size()];
        for (int i = 0; i < ips.size(); i++) {
            String ip = ips.get(i);
            HttpHost host = new HttpHost(ip, port, "http");
            hosts[i] = host;
        }

        RestClientBuilder builder = RestClient.builder(hosts);
        client = builder.build();

        Map<String,Object> data1 = new HashMap<String,Object>();
        data1.put("name","kevin.yang");
        data1.put("age",1);
        String paramsJson = JSON.toJSONString(data1);

        HttpEntity entity = new NStringEntity(paramsJson, ContentType.APPLICATION_JSON);
        String endPoint = "/yiling001/test";

        for(int i=0;i<100;i++){
            client.performRequestAsync("POST", endPoint+i,baseParams, entity,new ResponseListener(){

                public void onSuccess(Response response) {

                    System.out.println("success:"+response);
                }

                public void onFailure(Exception e) {
                    e.printStackTrace();
                    System.out.println("error:"+e);
                }
            },header);
        }
        System.out.println("end ....");
        while(true){
            TimeUnit.SECONDS.sleep(1);
        }

    }
```

exception:
```
java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:209)
	at org.apache.http.impl.nio.reactor.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:177)
	at org.apache.http.impl.nio.codecs.AbstractContentEncoder.doWriteChunk(AbstractContentEncoder.java:178)
	at org.apache.http.impl.nio.codecs.AbstractContentEncoder.doWriteChunk(AbstractContentEncoder.java:164)
	at org.apache.http.impl.nio.codecs.AbstractContentEncoder.writeToBuffer(AbstractContentEncoder.java:151)
	at org.apache.http.impl.nio.codecs.LengthDelimitedEncoder.write(LengthDelimitedEncoder.java:112)
	at org.apache.http.nio.entity.NStringEntity.produceContent(NStringEntity.java:174)
	at org.apache.http.nio.protocol.BasicAsyncRequestProducer.produceContent(BasicAsyncRequestProducer.java:125)
	at org.apache.http.impl.nio.client.MainClientExec.produceContent(MainClientExec.java:262)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.produceContent(DefaultClientExchangeHandlerImpl.java:136)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.outputReady(HttpAsyncRequestExecutor.java:241)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.produceOutput(DefaultNHttpClientConnection.java:290)
	at org.apache.http.impl.nio.client.InternalIODispatch.onOutputReady(InternalIODispatch.java:86)
	at org.apache.http.impl.nio.client.InternalIODispatch.onOutputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.outputReady(AbstractIODispatch.java:145)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.writable(BaseIOReactor.java:188)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:341)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:748)
```

and

```
java.util.concurrent.TimeoutException
	at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:364)
	at org.apache.http.nio.pool.AbstractNIOConnPool.processNextPendingRequest(AbstractNIOConnPool.java:344)
	at org.apache.http.nio.pool.AbstractNIOConnPool.release(AbstractNIOConnPool.java:318)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.releaseConnection(PoolingNHttpClientConnectionManager.java:303)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.releaseConnection(AbstractClientExchangeHandler.java:239)
	at org.apache.http.impl.nio.client.MainClientExec.responseCompleted(MainClientExec.java:387)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:168)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:748)
```

the rest client version is:

```
<dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>rest</artifactId>
            <version>6.0.0-alpha1</version>
        </dependency>
```

and while use 6.0.0 ,it is the same!

**Elasticsearch version** (`bin/elasticsearch --version`):
5.5.3

**Plugins installed**: []
none

**JVM version** (`java -version`):
client JVM is 1.7

**OS version** (`uname -a` if on a Unix-like system):
Mac os

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

 1. run the code multi times;
 2. if i send performRequestAsync 5 times,maybe 4 success, 1 fail ; i use wireshark and find it made 5 TCP connection ,and only send 4 HTTP request

3. is it bug or my wrong setting?

**Provide logs (if relevant)**:

**Comment by OuyangKevin** [comment]
any master here?

**Comment by ankurjha7** [comment]
I tried to replicate the same on a newer version (6.0.1) . How over could not replicate the issue. The only difference in my request was that instead of changing the type for each iteration , i changed the data and made the entry and could see the same reflected in elastic. Can you please try to replicate the issue on a newer version ?

**Comment by nik9000** [comment]
I think the `TimeoutException` sounds like #24069. I'm unable to reproduce the `IllegalArgumentException`.
