### ISSUE TITLE
On ES upgrade from 5.5.1 to 5.6.3 , ES Instances Fails when removing and disabling expired X-Pack Security

### ISSUE THREAD

**Issue by sandeep-developer** [elastic/elasticsearch#27694]
Upgrading from  ES 5.5.1 to 5.5.4
**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []X-pack

**JVM version** (`java -version`):
1.8.0_144
**OS version** (`uname -a` if on a Unix-like system):
Window 2012 R2
**Description of the problem including expected versus actual behavior**:
After Upgrade , i have removed the expired X-Pack plugin  but after removing ES not coming up and throwing exception 
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Upgrade ES from 5.x to 5.y (y>x) and make sure on lower version 5.x Expired X-Pack  enabled which is of no use once its expired.
 2. When ES gets upgraded to 5.y then remove the x-pack plugin from Elastic Search
 3. Restart Elastic Search , you will see the below log exception

**Provide logs (if relevant)**:
ES Logs 

[2017-12-07T00:42:10,102][INFO ][o.e.n.Node               ]  version[5.6.3], pid[11308], build[1a2f265/2017-10-06T20:33:39.012Z], OS[Windows Server 2012 R2/6.3/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_144/25.144-b01]
[2017-12-07T00:42:10,103][INFO ][o.e.n.Node               ] JVM arguments [-XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.enforce.bootstrap.checks=true, -Xmx14336m, -Xms14336m, -Delasticsearch, -Des.path.home=C:\Program Files\Elastic\Elasticsearch]
[2017-12-07T00:42:11,052][INFO ][o.e.p.PluginsService     ] loaded module [aggs-matrix-stats]
[2017-12-07T00:42:11,052][INFO ][o.e.p.PluginsService     ]  loaded module [ingest-common]
[2017-12-07T00:42:11,052][INFO ][o.e.p.PluginsService     ]  loaded module [lang-expression]
[2017-12-07T00:42:11,052][INFO ][o.e.p.PluginsService     ]  loaded module [lang-groovy]
[2017-12-07T00:42:11,052][INFO ][o.e.p.PluginsService     ]  loaded module [lang-mustache]
[2017-12-07T00:42:11,052][INFO ][o.e.p.PluginsService     ] loaded module [lang-painless]
[2017-12-07T00:42:11,052][INFO ][o.e.p.PluginsService     ]  loaded module [parent-join]
[2017-12-07T00:42:11,052][INFO ][o.e.p.PluginsService     ]  loaded module [percolator]
[2017-12-07T00:42:11,053][INFO ][o.e.p.PluginsService     ]  loaded module [reindex]
[2017-12-07T00:42:11,053][INFO ][o.e.p.PluginsService     ]  loaded module [transport-netty3]
[2017-12-07T00:42:11,053][INFO ][o.e.p.PluginsService     ]  loaded module [transport-netty4]
[2017-12-07T00:42:11,053][INFO ][o.e.p.PluginsService     ]  no plugins loaded
[2017-12-07T00:42:11,673][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.IllegalArgumentException: unknown setting [xpack.security.enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:293) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:256) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:139) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.node.Node.<init>(Node.java:344) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) [elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) [elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) [elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) [elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) [elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) [elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) [elasticsearch-5.6.3.jar:5.6.3]
[2017-12-07T00:42:11,679][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [ICEDEVESEARCH] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [xpack.security.enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.3.jar:5.6.3]
Caused by: java.lang.IllegalArgumentException: unknown setting [xpack.security.enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:293) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:256) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:139) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.node.Node.<init>(Node.java:344) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.3.jar:5.6.3]
	... 6 more

**Comment by jasontedor** [comment]
From your logs:

```
[2017-12-07T00:42:11,673][ERROR][o.e.b.Bootstrap ] Exception
java.lang.IllegalArgumentException: unknown setting [xpack.security.enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
```

You removed X-Pack but you're still using an X-Pack setting. Elasticsearch is strict about parsing settings (do you really want to have X-Pack security settings enabled and have them ignored if X-Pack is not installed)? No, you do not.

This is expected behavior for the settings infrastructure within Elasticsearch. I am closing this as not a bug.

**Comment by sandeep-developer** [comment]
No i understand that, but  i am not using X-Pack security , and i have already disabled X-Pack, do you know what is the workaround so that i should not encounter this issue . What is the solution?

**Comment by jasontedor** [comment]
Remove the setting. Please ask additional questions on the [forum](https://discuss.elastic.co). This space is reserved for verified bug reports and feature requests only.
