### ISSUE TITLE
Plugin [repository-azure] is incompatible with version [5.5.2]

### ISSUE THREAD

**Issue by megaherz2525** [elastic/elasticsearch#27700]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 5.5.2, Build: b2f0c09/2017-08-14T12:33:14.154Z, JVM: 1.8.0_151

**Plugins installed**: [repository-azure] 

**JVM version** (`java -version`):
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
*Oracle Java

**OS version** (`uname -a` if on a Unix-like system):
Linux es-mst1  4.11.0-1015-azure #15-Ubuntu SMP Thu Nov 2 17:19:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Steps to reproduce**:

 1. Install Elasticsearch with version 5.5.2 (with basic configuration)
 2. Install azure repository plugin: "/usr/share/elasticsearch/bin/elasticsearch-plugin install repository-azure"
 3. Add to /etc/elasticsearch/elasticsearch.yml, in the end of file two strings:
     -  cloud.azure.storage.default.account: some-account-storage-name
      - cloud.azure.storage.default.key: access-key-to-some-account-storage

 4. Restart  Elasticsearch: "systemctl restart  elasticsearch"

**Provide logs (if relevant)**:
[2017-12-07T10:47:29,075][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.IllegalArgumentException: plugin [repository-azure] is incompatible with version [5.5.2]; was designed for version [5.5.1]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:76) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:167) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) [elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) [elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) [elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) [elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) [elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.cli.Command.main(Command.java:88) [elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) [elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) [elasticsearch-5.5.2.jar:5.5.2]
[2017-12-07T10:47:29,103][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [dev-es-mst-01] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: plugin [repository-azure] is incompatible with version [5.5.2]; was designed for version [5.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.5.2.jar:5.5.2]
Caused by: java.lang.IllegalArgumentException: plugin [repository-azure] is incompatible with version [5.5.2]; was designed for version [5.5.1]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:146) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:76) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:167) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.2.jar:5.5.2]
        ... 6 more

**Comment by dadoonet** [comment]
Can you ls -l your plugins/repository-azure dir?

**Comment by rjernst** [comment]
Please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports.

You need to uninstall plugins and reinstall them for each upgrade.
