### ISSUE TITLE
[CI] MigrationDocumentationIT#testClusterHealth failed

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#27754]
This test has been failed recently but I could not reproduce it locally.

```
 gradle :client:rest-high-level:integTestRunner \
  -Dtests.seed=A72A1EF88C187DAB \
  -Dtests.class=org.elasticsearch.client.documentation.MigrationDocumentationIT \
  -Dtests.method="testClusterHealth" \
  -Dtests.security.manager=true \
  -Dtests.jvm.argline="-XX:+AggressiveOpts" \
  -Dtests.locale=fr \
  -Dtests.timezone=Europe/Isle_of_Man
```

Some instances:

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+aggressive-opts/526/console

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/406/console

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+aggressive-opts/525/console

Log: [testClusterHealth.txt](https://github.com/elastic/elasticsearch/files/1548097/testClusterHealth.txt)

**Comment by tlrx** [comment]
Reopened, my fix wasn't enough:

See https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+oracle-periodic/1836/consoleFull
```
19:25:13 Suite: org.elasticsearch.client.documentation.MigrationDocumentationIT
19:25:13   1> [2017-12-13T15:24:43,100][INFO ][o.e.c.d.MigrationDocumentationIT] [testClusterHealth]: before test
19:25:13   1> [2017-12-13T15:24:43,101][INFO ][o.e.c.d.MigrationDocumentationIT] initializing REST clients against [http://[::1]:44177]
19:25:13   1> [2017-12-13T15:25:13,143][INFO ][o.e.c.d.MigrationDocumentationIT] [testClusterHealth]: after test
19:25:13   2> REPRODUCE WITH: gradle :client:rest-high-level:integTestRunner -Dtests.seed=273C8EDBE09ED260 -Dtests.class=org.elasticsearch.client.documentation.MigrationDocumentationIT -Dtests.method="testClusterHealth" -Dtests.security.manager=true -Dtests.locale=es-ES -Dtests.timezone=America/Lower_Princes
19:25:13 ERROR   30.1s | MigrationDocumentationIT.testClusterHealth <<< FAILURES!
19:25:13    > Throwable #1: java.io.IOException: listener timeout after waiting for [30000] ms
19:25:13    > 	at __randomizedtesting.SeedInfo.seed([273C8EDBE09ED260:B5813BE74B82DED7]:0)
19:25:13   2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+master+oracle-periodic/client/rest-high-level/build/testrun/integTestRunner/J0/temp/org.elasticsearch.client.documentation.MigrationDocumentationIT_273C8EDBE09ED260-001
19:25:13   2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=1905, maxMBSortInHeap=6.140447784373265, sim=RandomSimilarity(queryNorm=true): {}, locale=es-ES, timezone=America/Lower_Princes
19:25:13   2> NOTE: Linux 4.4.49-92.14-default amd64/Oracle Corporation 1.8.0_144 (64-bit)/cpus=4,threads=1,free=385731456,total=514850816
19:25:13   2> NOTE: All tests run in this JVM: [SearchDocumentationIT, SearchIT, CrudIT, PingAndInfoIT, MainDocumentationIT, IndicesClientIT, CRUDDocumentationIT, IndicesClientDocumentationIT, MigrationDocumentationIT]
19:25:13    > 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:663)
19:25:13    > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:222)
19:25:13    > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:194)
19:25:13    > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:173)
19:25:13    > 	at org.elasticsearch.client.documentation.MigrationDocumentationIT.testClusterHealth(MigrationDocumentationIT.java:110)
19:25:13    > 	at java.lang.Thread.run(Thread.java:748)
19:25:13   1> [2017-12-13T15:25:13,159][INFO ][o.e.c.d.MigrationDocumentationIT] [testCreateIndex]: before test
19:25:13   1> [2017-12-13T15:25:13,205][INFO ][o.e.c.d.MigrationDocumentationIT] [testCreateIndex]: after test
19:25:13   1> [2017-12-13T15:25:13,209][INFO ][o.e.c.d.MigrationDocumentationIT] [testRequests]: before test
19:25:13   1> [2017-12-13T15:25:13,324][INFO ][o.e.c.d.MigrationDocumentationIT] [testRequests]: after test
19:25:13 Completed [9/9] in 30.25s, 3 tests, 1 error <<< FAILURES!
```

**Comment by danielmitterdorfer** [comment]
Another instance is https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/1065/console:

```
10:55:07 ERROR   30.0s | MigrationDocumentationIT.testClusterHealth <<< FAILURES!
10:55:07    > Throwable #1: java.io.IOException: listener timeout after waiting for [30000] ms
10:55:07    > 	at __randomizedtesting.SeedInfo.seed([E2A4C7B08239E4C2:7019728C2925E875]:0)
10:55:07    > 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:663)
10:55:07    > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:222)
10:55:07    > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:194)
10:55:07    > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:173)
10:55:07    > 	at org.elasticsearch.client.documentation.MigrationDocumentationIT.testClusterHealth(MigrationDocumentationIT.java:110)
10:55:07    > 	at java.lang.Thread.run(Thread.java:748)
```

reproduction line: 

```
gradle :client:rest-high-level:integTestRunner -Dtests.seed=E2A4C7B08239E4C2 -Dtests.class=org.elasticsearch.client.documentation.MigrationDocumentationIT -Dtests.method="testClusterHealth" -Dtests.security.manager=true -Dtests.locale=uk-UA -Dtests.timezone=Indian/Kerguelen
```

**Comment by javanna** [comment]
Could it be there is some index created with default settings and the tests run against a single node cluster? That way the cluster could never be green?

**Comment by tlrx** [comment]
That's what I suspect too but I didn't investigate more for now. I'll look at it later

**Comment by DaveCTurner** [comment]
I muted this test in b1039164a1.

**Comment by tlrx** [comment]
@DaveCTurner Thanks! I created #27899 as the issue is in another test.
