### ISSUE TITLE
Term vectors / artifical documents example doesn't work

### ISSUE THREAD

**Issue by DavidNemeskey** [elastic/elasticsearch#27771]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 6.0.1, Build: 601be4a/2017-12-04T09:29:09.525Z, JVM: 1.8.0_151

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
The ["artifical documents" example](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-termvectors.html#docs-termvectors-artificial-doc) in the term vectors API doesn't work. Neither does the one below.

I get the following error message:
```JSON
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_state_exception",
        "reason" : "Something is wrong with the field statistics of the term vector request: Values are \nsum_doc_freq 0\ndoc_count 0\nsum_ttf 0"
      }
    ],
    "type" : "illegal_state_exception",
    "reason" : "Something is wrong with the field statistics of the term vector request: Values are \nsum_doc_freq 0\ndoc_count 0\nsum_ttf 0"
  },
  "status" : 500
}
```

**Steps to reproduce**:

Just follow the commands on the linked page.

**Provide logs (if relevant)**:
```
[2017-12-12T12:35:52,493][WARN ][r.suppressed             ] path: /twitter/tweet/_termvectors, params: {pretty=, index=twitter, type=tweet}
java.lang.IllegalStateException: Something is wrong with the field statistics of the term vector request: Values are 
sum_doc_freq 0
doc_count 0
sum_ttf 0
	at org.elasticsearch.action.termvectors.TermVectorsResponse.buildFieldStatistics(TermVectorsResponse.java:322) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.action.termvectors.TermVectorsResponse.buildField(TermVectorsResponse.java:205) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.action.termvectors.TermVectorsResponse.toXContent(TermVectorsResponse.java:192) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.rest.action.RestToXContentListener.buildResponse(RestToXContentListener.java:47) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.rest.action.RestToXContentListener.buildResponse(RestToXContentListener.java:42) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.rest.action.RestToXContentListener.buildResponse(RestToXContentListener.java:34) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.rest.action.RestResponseListener.processResponse(RestResponseListener.java:37) ~[elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:47) [elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:85) [elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:81) [elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:247) [elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:233) [elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1062) [elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1136) [elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1126) [elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1115) [elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.transport.DelegatingTransportChannel.sendResponse(DelegatingTransportChannel.java:60) [elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.transport.RequestHandlerRegistry$TransportChannelWrapper.sendResponse(RequestHandlerRegistry.java:108) [elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:295) [elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:287) [elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30) [elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:659) [elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-6.0.1.jar:6.0.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.0.1.jar:6.0.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by cbuescher** [comment]
@DavidNemeskey this works for me, you need to follow the whole example including the mapping setup at the front of the page. When I leave that and use dynamic mapping I get the error you described, but that is expected since the term vectors are not stored then.

**Comment by DavidNemeskey** [comment]
You are right; I must have missed when that code failed to run, since I already had the twitter index at that point.

In my defense, this seems to be a problem with the whole tutorial: the same indices are created over and over again, sometimes with different mappings, sometimes with the same. Sometimes they contain the fields that are used in the demonstrated queries, sometimes not. It would be much clearer if there were a few fixed indices created at the very beginning, and all queries would be run against those.

**Comment by cbuescher** [comment]
> the same indices are created over and over again, sometimes with different mappings, sometimes with the same

Thanks for the feedback, I agree this can be confusing. On the other hand, there are so many small variations in the index setup that you need in order to demonstrate a certain feature that I think it would be difficult to create just a few "tutorial" indices. In the end this is more of a reference guide and a lot of people don't systematically work through the whole documentation, so repeating a minimal setup for each feature makes sence to me.

**Comment by DavidNemeskey** [comment]
Fair enough. I was aware of that when I wrote the previous comment -- I am not sure either what the best solution would be.
