### ISSUE TITLE
NPE with _cat/indices, _cat/nodes, _cat/allocation with Elasticsearch 6.0.1 

### ISSUE THREAD

**Issue by louloupw22** [elastic/elasticsearch#27781]
Hello, I have just migrated to elasticsearch 6.0.1 (I was using 5.6.5 before). I have some problem with cat API as when I :

```
GET /_cat/allocation?v
GET /_cat/indices?v
GET /_cat/nodes
```
I receive this message

```
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": null
      }
    ],
    "type": "null_pointer_exception",
    "reason": null
  },
  "status": 500
}
```
and also in powershell :

```
[WARN ][r.suppressed             ] path: /_cat/indices, params: {v=}
        java.lang.NullPointerException: null
        at org.elasticsearch.common.io.stream.StreamOutput.writeStringList(StreamOutput.java:949) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.cluster.metadata.IndexTemplateMetaData.writeTo(IndexTemplateMetaData.java:248) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.cluster.metadata.MetaData.writeTo(MetaData.java:695) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.cluster.ClusterState.writeTo(ClusterState.java:686) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.discovery.zen.PublishClusterStateAction.serializeFullClusterState(PublishClusterStateAction.java:351) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.action.admin.cluster.state.TransportClusterStateAction.masterOperation(TransportClusterStateAction.java:136) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.action.admin.cluster.state.TransportClusterStateAction.masterOperation(TransportClusterStateAction.java:44) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:87) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:166) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:139) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:163) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.start(TransportMasterNodeAction.java:126) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:104) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:54) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:167) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:139) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:81) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:405) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:712) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.state(AbstractClient.java:748) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.rest.action.cat.RestIndicesAction.lambda$doCatRequest$0(RestIndicesAction.java:91) ~[elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:97) [elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:240) [elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:336) [elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:174) [elasticsearch-6.0.1.jar:6.0.1]
                at org.elasticsearch.http.netty4.Netty4HttpServerTransport.dispatchRequest(Netty4HttpServerTransport.java:491) [transport-netty4-6.0.1.jar:6.0.1]
                at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:80) [transport-netty4-6.0.1.jar:6.0.1]
```

However I have a good answer when I ask GET _cat/recovery for example and index can also be retrieved.

Does anyone have an idea of the problem ?
I have also opened a discussion [here ](https://discuss.elastic.co/t/problem-with-cat-indices-cat-nodes-cat-allocation-with-elasticsearch6-0-1/111370)

Thank you

**Comment by dnhatn** [comment]
@louloupw22 Are you running a single cluster node? I suspect that you've upgraded to 6.x, then downgraded to 5.x, then upgraded to 6.x again. This caused the `index_patterns` be null.

**Comment by louloupw22** [comment]
@dnhatn Yes I am running a single cluster node. What you say is possible because my previous kibana index was out of date with the migration so I changed the index, try to restart the previous elasticsearch version (I deleted it now). How can I check the index_patterns (I see a lot of  in indexing tags in the JSON docs) and what can I do to change it if it is null ?

**Comment by dnhatn** [comment]
@louloupw22 Thank you for your input.

`GET /_templates` returns all existing index templates in your cluster. You can workaround this issue by updating `index_patterns` manually for these existing index templates. Please refer the index template documentation at https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html.

**Comment by dnhatn** [comment]
I am closing this. The PR https://github.com/elastic/elasticsearch/pull/27662 prevents this issue from happening.

**Comment by louloupw22** [comment]
Thank you @dnhatn for your help.
However when I do GET /_templates I can see information like this one : 
```
{
  ".ml-notifications": {
    "order": 0,
    "version": 5060399,
    "index_patterns": null,
    "settings": {
      "index": {
        "mapper": {
          "dynamic": "true"
        },
        "mapping": {
          "single_type": "true"
        },
        "unassigned": {
          "node_left": {
            "delayed_timeout": "1m"
          }
        },
        "number_of_shards": "1"
      }
    },
    "mappings": {
      "audit_message": {
        "properties": {
          "job_id": {
            "type": "keyword"
          },
          "level": {
            "type": "keyword"
          },
          "message": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              }
            }
          },
          "timestamp": {
            "type": "date"
          },
          "node_name": {
            "type": "keyword"
          }
        }
      }
    },
    "aliases": {}
  }
```
and all the null index_patterns concerns index that were created when I used X-pack (that I have deleted since because of other bugs it triggered from time to time). So I do not know how to update manually the index_patterns (try some PUT _template/template_1 but did not change my problem).

**Comment by dnhatn** [comment]
> try some PUT _template/template_1 but did not change my problem

@louloupw22  You need to overwrite the existing templates; not putting a new template.

**Comment by louloupw22** [comment]
@dnhatn OK thank you, I got your point. And is there anywhere I could find what the new _template of version 6.0.1 should look like (I understood  it does not support multi-type indices from here https://www.elastic.co/guide/en/elasticsearch/reference/5.6/removal-of-types.html) ? However is there something special I should specify for index_patterns ? Where can I find the information I should overwrite ?

**Comment by carantunes** [comment]
@louloupw22  are you using a docker image? I had the same problem and already fixed it.
