### ISSUE TITLE
Master node not discovered in CI

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#27818]
_Note: These are three different test cases that fail but it appears to be the same cause, hence I just created one ticket._

Example build failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/5368/console

The [full build log](https://github.com/elastic/elasticsearch/files/1559329/build.log.zip) is attached.

failing tests:

```
org.elasticsearch.indices.state.RareClusterStateIT#testDelayedMappingPropagationOnPrimary
org.elasticsearch.cluster.routing.PrimaryAllocationIT#testDoNotAllowStaleReplicasToBePromotedToPrimary
org.elasticsearch.cluster.MinimumMasterNodesIT#testSimpleMinimumMasterNodes
```

Example failure message (more of them in the attached log):

```
ERROR   61.2s J2 | MinimumMasterNodesIT.testSimpleMinimumMasterNodes <<< FAILURES!
   > Throwable #1: MasterNotDiscoveredException[null]
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:230)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:317)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:244)
   > 	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:581)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:566)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   > 	at java.lang.Thread.run(Thread.java:748)Throwable #2: MasterNotDiscoveredException[null]
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:230)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:317)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:244)
   > 	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:581)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:566)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   > 	at java.lang.Thread.run(Thread.java:748)
```

before this failure we see in the log:

```
  1> [2017-12-14T08:01:25,025][WARN ][o.e.d.z.UnicastZenPing   ] [node_t1] [299] failed send ping to {#zen_unicast_127.0.0.1_3#}{QVh9ejEISw-Mkk7JqYIF1g}{127.0.0.1}{127.0.0.1:9623}
  1> java.lang.IllegalStateException: handshake failed, mismatched cluster name [Cluster [SUITE-CHILD_VM=[2]-CLUSTER_SEED=[-3582321890366079432]-HASH=[4DDF2E03F454A3]-cluster]] - {#zen_unicast_127.0.0.1_3#}{QVh9ejEISw-Mkk7JqYIF1g}{127.0.0.1}{127.0.0.1:9623}
```

Reproduction line:

```
REPRODUCE WITH: gradle :core:integTest \
  -Dtests.seed=3049C5F03325CE2F \
  -Dtests.class=org.elasticsearch.cluster.MinimumMasterNodesIT \
  -Dtests.method="testSimpleMinimumMasterNodes" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-GT \
  -Dtests.timezone=America/Eirunepe

REPRODUCE WITH: gradle :core:integTest \
  -Dtests.seed=3049C5F03325CE2F \
  -Dtests.class=org.elasticsearch.cluster.routing.PrimaryAllocationIT \
  -Dtests.method="testDoNotAllowStaleReplicasToBePromotedToPrimary" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-TN \
  -Dtests.timezone=Australia/Adelaide

REPRODUCE WITH: gradle :core:integTest \
  -Dtests.seed=3049C5F03325CE2F \
  -Dtests.class=org.elasticsearch.indices.state.RareClusterStateIT \
  -Dtests.method="testDelayedMappingPropagationOnPrimary" \
  -Dtests.security.manager=true \
  -Dtests.locale=sk-SK \
  -Dtests.timezone=Asia/Kathmandu
```

reproduces locally: no (I ran a full build with `gradle :core:integTest -Dtests.seed=3049C5F03325CE2F -Dtests.security.manager=true -Dtests.locale=sk-SK -Dtests.timezone=Asia/Kathmandu`)

failure frequency:

* `RareClusterStateIT#testDelayedMappingPropagationOnPrimary`: 10 times within the last year (out of that 6 times since December 11)
* `PrimaryAllocationIT#testDoNotAllowStaleReplicasToBePromotedToPrimary`: 15 times within the last year (out of that 10 times since December 11)
* `MinimumMasterNodesIT#testSimpleMinimumMasterNodes`: 20 times within the last year (out of that 12 times since December 11)

**Comment by danielmitterdorfer** [comment]
Another instance on 6.1: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.1+periodic/260/console and [full build log](https://github.com/elastic/elasticsearch/files/1559391/build.log.zip)
