### ISSUE TITLE
bug: logging via log4j2 JsonLayout fails with log4j security error

### ISSUE THREAD

**Issue by cdaringe** [elastic/elasticsearch#27874]
# problem statement

- configuring ES to log via JSON fails with security exception

# context

- i want my ES docker image to log JSON lines to stdout
- i have configured the image with a config file, and associated log4j2 jars
- on run, log4j2 complains about a security exception
  - i have also set ownership of the config file and jars to match those existing in the image.  more below

----

**Elasticsearch version** (`bin/elasticsearch --version`):

6.1.0

**Plugins installed**: []

**JVM version** (`java -version`):
whatever ships in docker 6.1.0, 1.8.0_151

**OS version** (`uname -a` if on a Unix-like system):
centos, see docker image

**Description of the problem including expected versus actual behavior**:

configuring the ES image for JSON logging results in log4j2 complaining about a security expeption and exiting.  #20304 & #20805 addressed what i thought was the same issue, yet the issue persists.

**Steps to reproduce**:

1. setup a log4j2 config file (example provided below)
1. grab the associated jackson jars that log4j2 needs for json logging (i won't provide these, they are fetchable from jcenter.  they are used clearly in the cmd below)
1. run the image

```sh
docker run -it \
  -v `pwd`/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties \
  -v `pwd`/jackson-databind-2.8.10.jar:/usr/share/elasticsearch/lib/jackson-databind-2.8.10.jar \
  -v `pwd`/jackson-annotations-2.8.10.jar:/usr/share/elasticsearch/lib/jackson-annotations-2.8.10.jar \
  docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0
```

```properties
# log4j2.properties
status = error
dest = err
name = PropertiesConfig

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = JsonLayout
appender.console.layout.compact= true
appender.console.layout.eventEol= true
appender.console.layout.locationInfo= true
appender.console.layout.stacktraceAsString= true

rootLogger.level = info
rootLogger.appenderRef.stdout.ref = STDOUT
````

**Provide logs (if relevant)**:

```
🛰  $ docker run -it \
  -v `pwd`/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties \
  -v `pwd`/jackson-databind-2.8.10.jar:/usr/share/elasticsearch/lib/jackson-databind-2.8.10.jar \
  -v `pwd`/jackson-annotations-2.8.10.jar:/usr/share/elasticsearch/lib/jackson-annotations-2.8.10.jar \
  docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0

2017-12-18 19:23:20,723 main ERROR An exception occurred processing Appender STDOUT java.security.AccessControlException: access denied ("java.lang.RuntimeP
ermission" "accessDeclaredMembers")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.Class.checkMemberAccess(Class.java:2348)
        at java.lang.Class.getDeclaredMethods(Class.java:1974)
        at com.fasterxml.jackson.databind.util.ClassUtil.getDeclaredMethods(ClassUtil.java:944)
        at com.fasterxml.jackson.databind.introspect.AnnotatedClass._findClassMethods(AnnotatedClass.java:1196)
        at com.fasterxml.jackson.databind.introspect.AnnotatedClass._addMemberMethods(AnnotatedClass.java:741)
        at com.fasterxml.jackson.databind.introspect.AnnotatedClass._resolveMemberMethods(AnnotatedClass.java:554)
        at com.fasterxml.jackson.databind.introspect.AnnotatedClass.resolveMemberMethods(AnnotatedClass.java:541)
        at com.fasterxml.jackson.databind.introspect.AnnotatedClass.memberMethods(AnnotatedClass.java:340)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addMethods(POJOPropertiesCollector.java:512)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:303)
        at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueMethod(POJOPropertiesCollector.java:173)
        at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueMethod(BasicBeanDescription.java:224)
        at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(BasicSerializerFactory.java:350)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:219)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:168)
        at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1308)
        at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1258)
        at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:500)
        at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:698)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:270)
        at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1429)
        at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1158)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1004)
        at org.apache.logging.log4j.core.layout.AbstractJacksonLayout.toSerializable(AbstractJacksonLayout.java:213)
        at org.apache.logging.log4j.core.layout.JsonLayout.toSerializable(JsonLayout.java:254)
        at org.apache.logging.log4j.core.layout.AbstractJacksonLayout.toSerializable(AbstractJacksonLayout.java:193)
        at org.apache.logging.log4j.core.layout.JsonLayout.toSerializable(JsonLayout.java:60)
        at org.apache.logging.log4j.core.layout.AbstractJacksonLayout.toSerializable(AbstractJacksonLayout.java:34)
        at org.apache.logging.log4j.core.layout.AbstractStringLayout.toByteArray(AbstractStringLayout.java:299)
        at org.apache.logging.log4j.core.layout.AbstractLayout.encode(AbstractLayout.java:210)
        at org.apache.logging.log4j.core.layout.AbstractLayout.encode(AbstractLayout.java:37)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:177)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
        at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
        at org.apache.logging.log4j.spi.ExtendedLoggerWrapper.logMessage(ExtendedLoggerWrapper.java:217)
        at org.elasticsearch.common.logging.PrefixLogger.logMessage(PrefixLogger.java:102)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2116)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2100)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1994)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1966)
        at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1303)
        at org.elasticsearch.node.Node.<init>(Node.java:254)
        at org.elasticsearch.node.Node.<init>(Node.java:245)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85)
```

**Comment by jasontedor** [comment]
Duplicates #22103

**Comment by cdaringe** [comment]
hi @jasontedor, thanks for the xref. 

however, i did in fact see #22103.  you can see the the errors i present and the errors they present are similar, but different.  same objective, but perhaps _slightly_ different failure mode.

in the docker context, it's not abundantly clear where to set those policies values that you articulated in that issue.

```sh
[root@94d395433e1e elasticsearch]# grep -irn RuntimePermission
plugins/ingest-geoip/plugin-security.policy:26:  permission java.lang.RuntimePermission "accessDeclaredMembers";
modules/lang-mustache/plugin-security.policy:22:  permission java.lang.RuntimePermission "accessDeclaredMembers";
modules/lang-painless/plugin-security.policy:22:  permission java.lang.RuntimePermission "accessDeclaredMembers";
modules/lang-expression/plugin-security.policy:22:  permission java.lang.RuntimePermission "accessDeclaredMembers";
```

i tried updating ^^^ listed policy files, but alas, the issue persists.  can you lend a hand and point me to where those settings would go?

**Comment by jasontedor** [comment]
You need to grant the permission to core Elasticsearch; add a file named `.java.policy` in the home directory of the user that you run Elasticsearch as and add the grant. Note that this impacts *any* JVM not limited to Elasticsearch that is run by this user. Does this help?

**Comment by cdaringe** [comment]
Yes, it completely helps! :)  Thx!

For those who are in docker-land and want to see how i overcame it, have the following assets to build my ES json logging docker image:

```Dockerfile
ARG FROM
# eg. elasticsearch:6.1.0
FROM $FROM
COPY setup-json-logging.sh .
RUN bash setup-json-logging.sh clean-jackson-jars
# squash log4j properties outright, as there's no great way to unset
# existing log configuration values.
COPY log4j2.properties /usr/share/elasticsearch/config/log4j2.properties
# build/libs/*.jar expands to the jackson core, annotations, and databind jars
COPY build/libs/*.jar /usr/share/elasticsearch/lib/
RUN chown 1000:0 /usr/share/elasticsearch/config/log4j2.properties && \
  chmod 0664 /usr/share/elasticsearch/config/log4j2.properties & \
  chown -R 1000:0 /usr/share/elasticsearch/lib/ && \
  bash setup-json-logging.sh update-jvm-perms
```

```sh
#! /bin/bash
# setup-json-logging.sh
DEPENDENCY_JAR_GLOBS=("*jackson-core*.jar" "*jackson-databind*.jar" "*jackson-annotations*.jar")

# purge jackson jars, bring our own
if [ "$1" == "clean-jackson-jars" ]
then
  echo cleaning jackson jars
  for glob in ${DEPENDENCY_JAR_GLOBS[@]}
  do
    echo testing for $glob
    find . -name "$glob" | while read -r line;
    do
      printf "\tpurging $line\n"
      rm -f $line
    done
  done
fi

# loosen the JVM perms so we can configure our own logger
# {@see https://github.com/elastic/elasticsearch/issues/22103}
if [ "$1" == "update-jvm-perms" ]
then
  read -d '' JAVA_POLICY << EOF
grant {
  permission java.lang.RuntimePermission "accessDeclaredMembers";
  permission java.lang.reflect.ReflectPermission "suppressAccessChecks";
};
EOF
  echo "$JAVA_POLICY" > .java.policy
fi
```

```properties
# log4j2.properties
status = error
dest = err
name = PropertiesConfig

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = JsonLayout
appender.console.layout.compact= true
appender.console.layout.eventEol= true
appender.console.layout.locationInfo= true
appender.console.layout.stacktraceAsString= true

rootLogger.level = info
rootLogger.appenderRef.stdout.ref = STDOUT
```

**Comment by jasontedor** [comment]
> Yes, it completely helps! :) Thx!

You are very welcome. :smile:
