### ISSUE TITLE
[CI] Timeout waiting to lock file hash cache

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#27895]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux/1804/console

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type FileHasher using GradleUserHomeScopeServices.createCachingFileHasher().
> Timeout waiting to lock file hash cache (/var/lib/jenkins/.gradle/caches/4.4/fileHashes). It is currently in use by another Gradle instance.
  Owner PID: 31662
  Our PID: 1499
  Owner Operation: 
  Our operation: 
  Lock file: /var/lib/jenkins/.gradle/caches/4.4/fileHashes/fileHashes.lock

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.internal.service.ServiceCreationException: Could not create service of type FileHasher using GradleUserHomeScopeServices.createCachingFileHasher().
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:797)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:748)
	at
...
Caused by: org.gradle.cache.LockTimeoutException: Timeout waiting to lock file hash cache (/var/lib/jenkins/.gradle/caches/4.4/fileHashes). It is currently in use by another Gradle instance.
Owner PID: 31662
Our PID: 1499
Owner Operation: 
Our operation: 
Lock file: /var/lib/jenkins/.gradle/caches/4.4/fileHashes/fileHashes.lock
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.lock(DefaultFileLockManager.java:280)
	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.<init>(DefaultFileLockManager.java:150)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:100)
	at org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess.incrementLockCount(LockOnDemandCrossProcessCacheAccess.java:105)
	at ...
```

NB this seems to be using Gradle 4.4, which is unexpected to me.

**Comment by jasontedor** [comment]
This is closed by increasing the Gradle daemon heap size to 1536m.
