### ISSUE TITLE
[CI] JVM ended with an exception

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#27907]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.1+intake/104/console failed as follows:

```
[ant:junit4] ERROR: JVM J0 ended with an exception: Quit event not received from the forked process? This may indicate JVM crash or runner bugs.
	at com.carrotsearch.ant.tasks.junit4.JUnit4.executeSlave(JUnit4.java:1540)
	at com.carrotsearch.ant.tasks.junit4.JUnit4.access$000(JUnit4.java:126)
	at com.carrotsearch.ant.tasks.junit4.JUnit4$2.call(JUnit4.java:982)
:plugins:discovery-ec2:test FAILED
```

Possibly related to https://github.com/elastic/elasticsearch/issues/27898 and the move to Gradle 4.4?

**Comment by jasontedor** [comment]
This failure is not actionable without logs. I am closing this, we can try again if this recurs.
