### ISSUE TITLE
StartOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards

### ISSUE THREAD

**Issue by boliza** [elastic/elasticsearch#27987]
**Bug report**
1. Elasticsearch version:6.0.0
2. Plugins installed: [hanlp](https://github.com/shikeio/hanlp-ext) x-pack
3. JVM version:1.8.0_144
4. OS version:CentOS 7.3 64

**mapping is**
```json
PUT test/_mapping/test
{
  "properties": {
    "content":{
      "type": "text", 
      "analyzer": "hanlp-index"
    }
  }
}
```

these request passed:
```json
PUT test/test/1
{
  "content":"中华人民共和国"
}
PUT test/test/2
{
  "content":["中华","地大物博"]
}
```

but this one failed:
```json
PUT test/test/3
{
  "content":["中华人民共和国","地大物博"]
}
```

response is:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=1,endOffset=5,lastStartOffset=4 for field 'content'"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=1,endOffset=5,lastStartOffset=4 for field 'content'"
  },
  "status": 400
}
```

the exception is:
```
[2017-12-26T19:15:47,819][DEBUG][o.e.a.b.TransportShardBulkAction] [test][4] failed to execute bulk item (index) BulkShardRequest [[test][4]] containing [inde
x {[test][test][3], source[{
  "content":["中华人民共和国","地大物博"]
}
]}]
java.lang.IllegalArgumentException: startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=1,en
dOffset=5,lastStartOffset=4 for field 'content'
        at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:767) ~[lucene-core-7.0.1.jar:7.0.1 8d6c3889aa543954424d8ac1d
bb3f03bf207140b - sarowe - 2017-10-02 14:36:35]
        at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:430) ~[lucene-core-7.0.1.jar:7.0.1 8d6c3889aa543954424d8ac1dbb3
f03bf207140b - sarowe - 2017-10-02 14:36:35]
        at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:392) ~[lucene-core-7.0.1.jar:7.0.1 8d6c3889aa543954424d8ac1d
bb3f03bf207140b - sarowe - 2017-10-02 14:36:35]
        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:239) ~[lucene-core-7.0.1.jar:7.0.1 8d6c3889aa54395442
4d8ac1dbb3f03bf207140b - sarowe - 2017-10-02 14:36:35]
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:481) ~[lucene-core-7.0.1.jar:7.0.1 8d6c3889aa543954424d8ac1dbb3f03bf207
140b - sarowe - 2017-10-02 14:36:35]
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1717) ~[lucene-core-7.0.1.jar:7.0.1 8d6c3889aa543954424d8ac1dbb3f03bf207140b - 
sarowe - 2017-10-02 14:36:35]
        at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1462) ~[lucene-core-7.0.1.jar:7.0.1 8d6c3889aa543954424d8ac1dbb3f03bf207140b - sar
owe - 2017-10-02 14:36:35]
        at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:892) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.index.engine.InternalEngine.indexIntoLucene(InternalEngine.java:834) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:700) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:727) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:696) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:662) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:548) ~[elasticsearch-6.0.0.jar:6.
:
```

**Comment by DaveCTurner** [comment]
I'm expecting this to be a bug in the third-party `hanlp-index` plugin that you're using. I have tried to build this plugin by cloning the repository and following [the instructions](https://github.com/shikeio/hanlp-ext/tree/master/es-plugin) as best as I can understand them using Google Translate, but the instructions still refer to version `5.4.3` in places and I haven't succeeded in getting this plugin working with version `6.0.0` as mentioned above, even after some changes and other debugging effort. Unfortunately I can't justify spending much more time trying to get this working right now so I can reproduce it.

Could you run the following two tests which should run the analyser in a more isolated fashion, and report the results?

```
GET /_analyze?pretty
{
  "analyzer" : "hanlp-index",
  "text" : ["中华人民共和国"]
}
```

```
GET /_analyze?pretty
{
  "analyzer" : "hanlp-index",
  "text" : ["地大物博"]
}
```

**Comment by boliza** [comment]
Request 1
```json
GET /_analyze?pretty
{
  "analyzer" : "hanlp-index",
  "text" : ["中华人民共和国"]
}
```

response is:
```json
{
  "tokens": [
    {
      "token": "中华人民共和国",
      "start_offset": 0,
      "end_offset": 7,
      "type": "ns",
      "position": 0
    },
    {
      "token": "中华人民",
      "start_offset": 0,
      "end_offset": 4,
      "type": "nz",
      "position": 1
    },
    {
      "token": "中华",
      "start_offset": 0,
      "end_offset": 2,
      "type": "nz",
      "position": 2
    },
    {
      "token": "华人",
      "start_offset": 1,
      "end_offset": 3,
      "type": "n",
      "position": 3
    },
    {
      "token": "人民共和国",
      "start_offset": 2,
      "end_offset": 7,
      "type": "nz",
      "position": 4
    },
    {
      "token": "人民",
      "start_offset": 2,
      "end_offset": 4,
      "type": "n",
      "position": 5
    },
    {
      "token": "共和国",
      "start_offset": 4,
      "end_offset": 7,
      "type": "n",
      "position": 6
    },
    {
      "token": "共和",
      "start_offset": 4,
      "end_offset": 6,
      "type": "n",
      "position": 7
    }
  ]
}
```
Request 2
```
GET /_analyze?pretty
{
  "analyzer" : "hanlp-index",
  "text" : ["地大物博"]
}
```

response is:
```json
{
  "tokens": [
    {
      "token": "地大物博",
      "start_offset": 0,
      "end_offset": 4,
      "type": "nz",
      "position": 0
    },
    {
      "token": "地大",
      "start_offset": 0,
      "end_offset": 2,
      "type": "nz",
      "position": 1
    }
  ]
}
```

**Comment by boliza** [comment]
@DaveCTurner I need help to run the plugin test,be this work fine when the field value is not a list(array).
I also think is a issue just of the plugin , maybe some bugs in the [file](https://github.com/shikeio/hanlp-ext/blob/master/common/src/main/java/com/hankcs/lucene/HanLPTokenizer.java)

**Comment by DaveCTurner** [comment]
Hmm, ok, I can't see anything obviously wrong there. Thanks for trying.

I'm going to close this here as it seems more likely to be an issue in the third-party plugin than in Elasticsearch itself, and I've not been able to reproduce it after a reasonable amount of effort. Could you raise this with the plugin author and/or take this discussion over to https://discuss.elastic.co please? Feel free to add a link to the resulting issue/discussion here so that others can follow the thread if they come across a similar issue.

**Comment by boliza** [comment]
I have fix the bug in my plugin. But this plugin have a bug in highlighting. Could you help me , I'am not familiar with Lucene . Should I take a discussion in  https://discuss.elastic.co?

**Comment by DaveCTurner** [comment]
@boliza yes, please take this discussion to https://discuss.elastic.co. Feel free to add a link to the discussion here so that others can follow the thread if they come across a similar issue.
