### ISSUE TITLE
[CI] ReindexFailureTests testAbortOnVersionConflict, testFailuresCauseAbortDefault, testResponseOnSearchFailure

### ISSUE THREAD

**Issue by andyb-elastic** [elastic/elasticsearch#28053]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=centos/479/console

[build-479-ReindexFailureTests.txt](https://github.com/elastic/elasticsearch/files/1598563/build-479-ReindexFailureTests.txt)

```
ERROR   51.4s J3 | ReindexFailureTests.testResponseOnSearchFailure <<< FAILURES!
   > Throwable #1: java.lang.AssertionError:
   > Expected: an empty iterable
   > dices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd3][127.0.0.1:35162][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd3][127.0.0.1:35162][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd3][127.0.0.1:35162][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd3][127.0.0.1:35162][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd3][127.0.0.1:35162][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd3][127.0.0.1:35162][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd3][127.0.0.1:35162][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd1][127.0.0.1:43434][indices:data/write/index]]; nested: RemoteTransportException[[node_sd3][127.0.0.1:35162][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd1][127.0.0.1:43434][indices:data/write/index]]; nested: RemoteTransportException[[node_sd3][127.0.0.1:35162][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd1][127.0.0.1:43434][indices:data/write/index]]; nested: RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<RemoteTransportException[[node_sd1][127.0.0.1:43434][indices:data/write/index]]; nested: IndexNotFoundException[no such index];>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFounption[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>]
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1451)
   >    at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1369)
   >    at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1353)
   >    at org.elasticsearch.index.reindex.ReindexFailureTests.indexDocs(ReindexFailureTests.java:128)
   >    at org.elasticsearch.index.reindex.ReindexFailureTests.testResponseOnSearchFailure(ReindexFailureTests.java:100)
   >    at java.lang.Thread.run(Thread.java:748)Throwable #2: java.lang.AssertionError: There are still [1] in-flight contexts. The first one's creation site is listed as the cause of this exception.
   >    at org.elasticsearch.search.MockSearchService.assertNoInFlightContext(MockSearchService.java:51)
   >    at org.elasticsearch.test.ESTestCase.lambda$ensureAllSearchContextsReleased$4(ESTestCase.java:421)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:731)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:705)
   >    at org.elasticsearch.test.ESTestCase.ensureAllSearchContextsReleased(ESTestCase.java:421)
   >    at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2072)
   >    at java.lang.Thread.run(Thread.java:748)
   >    Suppressed: java.lang.AssertionError: There are still [1] in-flight contexts. The first one's creation site is listed as the cause of this exception.
   >            at org.elasticsearch.search.MockSearchService.assertNoInFlightContext(MockSearchService.java:51)
   >            at org.elasticsearch.test.ESTestCase.lambda$ensureAllSearchContextsReleased$4(ESTestCase.java:421)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:719)
   >            ... 37 more
```

```
gradle :modules:reindex:test \
  -Dtests.seed=401B0C5B3206920F \
  -Dtests.class=org.elasticsearch.index.reindex.ReindexFailureTests \
  -Dtests.method="testAbortOnVersionConflict" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Latn \
  -Dtests.timezone=America/Cuiaba
```

**Comment by nik9000** [comment]
Ok. I can't reproduce this one but I have a theory and I'll push a clean up that might prevent this in the future. Might.

**Comment by nik9000** [comment]
I pushed eded5bc4f3776c9841a4995972f29c6c07d81c46 to try and prevent this from happening again but it might not work. I wasn't able to reproduce locally so it is kind of a shot in the dark.

**Comment by dakrone** [comment]
I searched through my mail and wasn't able to find another failure from this after the push Nik made, so I am closing this for now.

**Comment by colings86** [comment]
This seems to have occurred again in http://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/2202

**Comment by nik9000** [comment]
:cry:

**Comment by DaveCTurner** [comment]
Not sure if it helps, but in the logs I see an earlier assertion failure:

```
  2> WARNING: Uncaught exception in thread: Thread[elasticsearch[node_sd1][clusterApplierService#updateTask][T#1],5,TGRP-ReindexFailureTests]
  2> java.lang.AssertionError
  2>  at __randomizedtesting.SeedInfo.seed([401B0C5B3206920F]:0)
  2>  at org.elasticsearch.index.search.stats.ShardSearchStats.onFreeScrollContext(ShardSearchStats.java:182)
  2>  at org.elasticsearch.index.shard.SearchOperationListener$CompositeListener.onFreeScrollContext(SearchOperationListener.java:233)
  2>  at org.elasticsearch.search.SearchService.freeContext(SearchService.java:638)
  2>  at org.elasticsearch.search.SearchService.freeAllContextForIndex(SearchService.java:625)
  2>  at org.elasticsearch.search.SearchService.afterIndexRemoved(SearchService.java:231)
  2>  at org.elasticsearch.index.CompositeIndexEventListener.afterIndexRemoved(CompositeIndexEventListener.java:195)
  2>  at org.elasticsearch.indices.IndicesService.removeIndex(IndicesService.java:557)
  2>  at org.elasticsearch.indices.cluster.IndicesClusterStateService.deleteIndices(IndicesClusterStateService.java:285)
  2>  at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:219)
  2>  at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$6(ClusterApplierService.java:498)
  2>  at java.lang.Iterable.forEach(Iterable.java:75)
  2>  at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:495)
  2>  at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:482)
  2>  at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:432)
  2>  at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:161)
  2>  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:566)
  2>  at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
  2>  at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
  2>  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
```

**Comment by nik9000** [comment]
I've added the 6.5.0 label to this. I'm honestly not that involved with reindex at this point so I'm not sure I'm the right person for this. But i don't think *anyone* is super involved in reindex right now.

For what it is worth: this looks to only be an issue on 6.x. The test is only muted in 6.x and i haven't seen a fairly of it in master.

**Comment by ywelsch** [comment]
I've unmuted testResponseOnSearchFailure on 6.x (see 7159c022205). I don't think that this is a reindex bug, but as @DaveCTurner pointed out, a problem in another component. As there are no recent failures, there is nothing we can investigate here. I'm therefore closing this issue. If there are more occurrences of this, please reopen and provide a link to a recent failure.

**Comment by dnhatn** [comment]
Another instance on master: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/3712/

```
java.lang.AssertionError: There are still [1] in-flight contexts. The first one's creation site is listed as the cause of this exception.
	at org.elasticsearch.search.MockSearchService.assertNoInFlightContext(MockSearchService.java:51)
	at org.elasticsearch.test.ESTestCase.lambda$ensureAllSearchContextsReleased$6(ESTestCase.java:503)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:862)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:836)
	at org.elasticsearch.test.ESTestCase.ensureAllSearchContextsReleased(ESTestCase.java:503)
```
```
REPRODUCE WITH: ./gradlew :modules:reindex:test --tests "org.elasticsearch.index.reindex.ReindexFailureTests.testResponseOnSearchFailure" -Dtests.seed=25A63C7B43796EB8 -Dtests.security.manager=true -Dtests.locale=az -Dtests.timezone=Africa/Ceuta -Dcompiler.java=12 -Druntime.java=11
```

Log: [reindex.txt](https://github.com/elastic/elasticsearch/files/3217741/reindex.txt)

**Comment by dnhatn** [comment]
It seems there's a race between releasing scrolls and deleting indices.

```
2> may 24, 2019 6:05:51 PM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
  2> WARNING: Uncaught exception in thread: Thread[elasticsearch[node_sd2][clusterApplierService#updateTask][T#1],5,TGRP-ReindexFailureTests]
  2> java.lang.AssertionError
  2> 	at __randomizedtesting.SeedInfo.seed([25A63C7B43796EB8]:0)
  2> 	at org.elasticsearch.index.search.stats.ShardSearchStats.onFreeScrollContext(ShardSearchStats.java:166)
  2> 	at org.elasticsearch.index.shard.SearchOperationListener$CompositeListener.onFreeScrollContext(SearchOperationListener.java:232)
  2> 	at org.elasticsearch.search.SearchService.freeContext(SearchService.java:655)
  2> 	at org.elasticsearch.search.SearchService.freeAllContextForIndex(SearchService.java:642)
  2> 	at org.elasticsearch.search.SearchService.afterIndexRemoved(SearchService.java:273)
  2> 	at org.elasticsearch.index.CompositeIndexEventListener.afterIndexRemoved(CompositeIndexEventListener.java:201)
  2> 	at org.elasticsearch.indices.IndicesService.removeIndex(IndicesService.java:701)
  2> 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.deleteIndices(IndicesClusterStateService.java:321)
  2> 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:255)
  2> 	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$5(ClusterApplierService.java:489)
  2> 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
  2> 	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:487)
  2> 	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:464)
  2> 	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:418)
  2> 	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:165)
  2> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:687)
  2> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
  2> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
  2> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  2> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  2> 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by henningandersen** [comment]
I think the race is between creating a new search context and deleting an index. When creating a new search context, we add it to the set of active contexts first and then notify listener. When deactivating a search context, we remove it from set of active contexts and then notify listener. This can go wrong, in case the deactivation happens between adding to the set and notifying the listener.
#20916 mentions that `testSearchWhileIndexDeleted` failed during PR build, might be similar issue.
