### ISSUE TITLE
Memory not reclaimed by GC

### ISSUE THREAD

**Issue by ripjarphil** [elastic/elasticsearch#28062]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.5.1

**JVM version**:
`
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
`

**OS version**: `Linux box3-3 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem**:

The memory used by our elastic cluster grew massively over an 8 hour period, and memory was not freed by the GC. During this time we were performing the following on the cluster:

 * indexing about 300k documents over 8 hours
 * scroll over 67 million documents. Scroll size was 100 and scroll parameter was '5m'. 
 * very very few searches/queries, if any.

The scroll was started on 2017-12-28, so when this runaway memory usage was observed it had been running for almost 2 days. The index we're scrolling over is about 2.7TB in size, 67 million documents and is spread over 27 shards across 9 nodes.

The indexing is happening on a different index to the one that is being scrolled.

It looks like the GC runs, but is unable to recover any memory. 

I would like to understand what is happening, and whether this use case is triggering a bug in Elastic? Please let me know if there is any other relevant information I should provide.

**Provide logs (if relevant)**:

```
[2017-12-30T00:03:25,547][INFO ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][young][681591][154802] duration [740ms], collections [1]/[1.1s], total [740ms]/[2.9h], memory [9.6gb]->[8.8gb]/[29.8gb], all_pools {[young] [758.1mb]->[6mb]/[865.3mb]}{[survivor] [37.5mb]->[41mb]/[108.1mb]}{[old] [8.8gb]->[8.8gb]/[28.9gb]}
[2017-12-30T02:46:35,000][INFO ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][young][691310][156235] duration [801ms], collections [1]/[1s], total [801ms]/[3h], memory [15gb]->[14.4gb]/[29.8gb], all_pools {[young] [769.4mb]->[40.6mb]/[865.3mb]}{[survivor] [64.4mb]->[108.1mb]/[108.1mb]}{[old] [14.2gb]->[14.2gb]/[28.9gb]}
[2017-12-30T06:54:18,101][INFO ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][young][706070][159171] duration [988ms], collections [1]/[1.2s], total [988ms]/[3.1h], memory [10.3gb]->[9.6gb]/[29.8gb], all_pools {[young] [861.1mb]->[18.8mb]/[865.3mb]}{[survivor] [108.1mb]->[108.1mb]/[108.1mb]}{[old] [9.4gb]->[9.5gb]/[28.9gb]}
[2017-12-30T07:10:25,618][INFO ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][young][707025][159322] duration [708ms], collections [1]/[1.5s], total [708ms]/[3.1h], memory [12.2gb]->[11.6gb]/[29.8gb], all_pools {[young] [770mb]->[33.2mb]/[865.3mb]}{[survivor] [108.1mb]->[108.1mb]/[108.1mb]}{[old] [11.4gb]->[11.5gb]/[28.9gb]}
[2017-12-30T07:54:21,818][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][young][709626][159767] duration [1.2s], collections [1]/[2s], total [1.2s]/[3.1h], memory [24.1gb]->[23.5gb]/[29.8gb], all_pools {[young] [796.8mb]->[18mb]/[865.3mb]}{[survivor] [108.1mb]->[108.1mb]/[108.1mb]}{[old] [23.2gb]->[23.4gb]/[28.9gb]}
[2017-12-30T08:00:02,691][INFO ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][young][709961][159818] duration [772ms], collections [1]/[1.4s], total [772ms]/[3.1h], memory [26gb]->[25.4gb]/[29.8gb], all_pools {[young] [743.8mb]->[4.2mb]/[865.3mb]}{[survivor] [108.1mb]->[108.1mb]/[108.1mb]}{[old] [25.1gb]->[25.3gb]/[28.9gb]}
[2017-12-30T08:05:57,862][INFO ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][young][710312][159872] duration [853ms], collections [1]/[1.1s], total [853ms]/[3.1h], memory [27.6gb]->[26.9gb]/[29.8gb], all_pools {[young] [812.7mb]->[358.8kb]/[865.3mb]}{[survivor] [108.1mb]->[108.1mb]/[108.1mb]}{[old] [26.7gb]->[26.8gb]/[28.9gb]}
[2017-12-30T08:07:06,969][INFO ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][young][710379][159881] duration [922ms], collections [1]/[1.9s], total [922ms]/[3.1h], memory [28gb]->[27.4gb]/[29.8gb], all_pools {[young] [820.9mb]->[16.8mb]/[865.3mb]}{[survivor] [108.1mb]->[108.1mb]/[108.1mb]}{[old] [27.1gb]->[27.2gb]/[28.9gb]}
[2017-12-30T08:09:42,187][INFO ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][young][710531][159904] duration [726ms], collections [1]/[1.7s], total [726ms]/[3.1h], memory [28.1gb]->[27.6gb]/[29.8gb], all_pools {[young] [535.2mb]->[5.8mb]/[865.3mb]}{[survivor] [108.1mb]->[90.5mb]/[108.1mb]}{[old] [27.5gb]->[27.5gb]/[28.9gb]}
[2017-12-30T08:12:18,255][INFO ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][young][710685][159933] duration [718ms], collections [1]/[1s], total [718ms]/[3.1h], memory [29.4gb]->[28.6gb]/[29.8gb], all_pools {[young] [844.9mb]->[3.5mb]/[865.3mb]}{[survivor] [108.1mb]->[108.1mb]/[108.1mb]}{[old] [28.4gb]->[28.5gb]/[28.9gb]}
[2017-12-30T08:14:24,685][INFO ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][young][710702][159935] duration [827ms], collections [1]/[1.8m], total [827ms]/[3.1h], memory [29.6gb]->[28.4gb]/[29.8gb], all_pools {[young] [840.9mb]->[301.3mb]/[865.3mb]}{[survivor] [108.1mb]->[0b]/[108.1mb]}{[old] [28.7gb]->[28.1gb]/[28.9gb]}
[2017-12-30T08:14:24,685][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][old][710702][70] duration [1.8m], collections [1]/[1.8m], total [1.8m]/[2.6m], memory [29.6gb]->[28.4gb]/[29.8gb], all_pools {[young] [840.9mb]->[301.3mb]/[865.3mb]}{[survivor] [108.1mb]->[0b]/[108.1mb]}{[old] [28.7gb]->[28.1gb]/[28.9gb]}
[2017-12-30T08:14:25,685][INFO ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][young][710703][159936] duration [813ms], collections [1]/[1.1s], total [813ms]/[3.1h], memory [28.4gb]->[28.6gb]/[29.8gb], all_pools {[young] [301.3mb]->[33.1mb]/[865.3mb]}{[survivor] [0b]->[108.1mb]/[108.1mb]}{[old] [28.1gb]->[28.5gb]/[28.9gb]}
[2017-12-30T08:16:23,778][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][old][710704][71] duration [1.9m], collections [1]/[1.9m], total [1.9m]/[4.5m], memory [28.6gb]->[28.7gb]/[29.8gb], all_pools {[young] [33.1mb]->[44.1mb]/[865.3mb]}{[survivor] [108.1mb]->[0b]/[108.1mb]}{[old] [28.5gb]->[28.6gb]/[28.9gb]}
[2017-12-30T08:17:48,492][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][old][710705][72] duration [1.4m], collections [1]/[1.4m], total [1.4m]/[6m], memory [28.7gb]->[28.7gb]/[29.8gb], all_pools {[young] [44.1mb]->[15.4mb]/[865.3mb]}{[survivor] [0b]->[0b]/[108.1mb]}{[old] [28.6gb]->[28.7gb]/[28.9gb]}
[2017-12-30T08:19:24,172][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][old][710706][73] duration [1.5m], collections [1]/[1.5m], total [1.5m]/[7.5m], memory [28.7gb]->[28.9gb]/[29.8gb], all_pools {[young] [15.4mb]->[62.4mb]/[865.3mb]}{[survivor] [0b]->[0b]/[108.1mb]}{[old] [28.7gb]->[28.8gb]/[28.9gb]}
[2017-12-30T08:20:56,286][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][old][710707][74] duration [1.5m], collections [1]/[1.5m], total [1.5m]/[9.1m], memory [28.9gb]->[29gb]/[29.8gb], all_pools {[young] [62.4mb]->[128.5mb]/[865.3mb]}{[survivor] [0b]->[0b]/[108.1mb]}{[old] [28.8gb]->[28.9gb]/[28.9gb]}
[2017-12-30T08:22:58,643][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][old][710708][75] duration [2m], collections [1]/[2m], total [2m]/[11.1m], memory [29gb]->[29.7gb]/[29.8gb], all_pools {[young] [128.5mb]->[794.5mb]/[865.3mb]}{[survivor] [0b]->[0b]/[108.1mb]}{[old] [28.9gb]->[28.9gb]/[28.9gb]}
[2017-12-30T08:24:26,254][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][old][710710][76] duration [1.4m], collections [1]/[1.4m], total [1.4m]/[12.5m], memory [29.8gb]->[29.3gb]/[29.8gb], all_pools {[young] [865.3mb]->[464.2mb]/[865.3mb]}{[survivor] [97.2mb]->[0b]/[108.1mb]}{[old] [28.9gb]->[28.9gb]/[28.9gb]}
[2017-12-30T08:26:31,524][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][old][710712][77] duration [2m], collections [1]/[2m], total [2m]/[14.6m], memory [29.8gb]->[29.6gb]/[29.8gb], all_pools {[young] [865.3mb]->[735mb]/[865.3mb]}{[survivor] [54.8mb]->[0b]/[108.1mb]}{[old] [28.9gb]->[28.9gb]/[28.9gb]}
[2017-12-30T08:28:08,424][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][old][710713][78] duration [1.5m], collections [1]/[1.5m], total [1.5m]/[16.2m], memory [29.6gb]->[29.7gb]/[29.8gb], all_pools {[young] [735mb]->[865.3mb]/[865.3mb]}{[survivor] [0b]->[2.2mb]/[108.1mb]}{[old] [28.9gb]->[28.9gb]/[28.9gb]}
[2017-12-30T08:30:02,460][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][old][710714][79] duration [1.8m], collections [1]/[1.9m], total [1.8m]/[18m], memory [29.7gb]->[29.8gb]/[29.8gb], all_pools {[young] [865.3mb]->[865.3mb]/[865.3mb]}{[survivor] [2.2mb]->[28.2mb]/[108.1mb]}{[old] [28.9gb]->[28.9gb]/[28.9gb]}
[2017-12-30T08:31:26,668][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][old][710715][80] duration [1.3m], collections [1]/[1.4m], total [1.3m]/[19.4m], memory [29.8gb]->[29.8gb]/[29.8gb], all_pools {[young] [865.3mb]->[865.3mb]/[865.3mb]}{[survivor] [28.2mb]->[77mb]/[108.1mb]}{[old] [28.9gb]->[28.9gb]/[28.9gb]}
[2017-12-30T08:33:30,638][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][old][710716][81] duration [2m], collections [1]/[2m], total [2m]/[21.5m], memory [29.8gb]->[29.8gb]/[29.8gb], all_pools {[young] [865.3mb]->[865.3mb]/[865.3mb]}{[survivor] [77mb]->[90.7mb]/[108.1mb]}{[old] [28.9gb]->[28.9gb]/[28.9gb]}
[2017-12-30T08:35:09,158][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][old][710717][82] duration [1.6m], collections [1]/[1.6m], total [1.6m]/[23.1m], memory [29.8gb]->[29.8gb]/[29.8gb], all_pools {[young] [865.3mb]->[865.3mb]/[865.3mb]}{[survivor] [90.7mb]->[90mb]/[108.1mb]}{[old] [28.9gb]->[28.9gb]/[28.9gb]}
[2017-12-30T08:37:17,525][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][old][710718][83] duration [2.1m], collections [1]/[2.1m], total [2.1m]/[25.3m], memory [29.8gb]->[29.8gb]/[29.8gb], all_pools {[young] [865.3mb]->[865.3mb]/[865.3mb]}{[survivor] [90mb]->[102.1mb]/[108.1mb]}{[old] [28.9gb]->[28.9gb]/[28.9gb]}
[2017-12-30T08:38:50,814][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][old][710719][84] duration [1.5m], collections [1]/[1.5m], total [1.5m]/[26.8m], memory [29.8gb]->[29.8gb]/[29.8gb], all_pools {[young] [865.3mb]->[865.3mb]/[865.3mb]}{[survivor] [102.1mb]->[106mb]/[108.1mb]}{[old] [28.9gb]->[28.9gb]/[28.9gb]}
[2017-12-30T08:51:45,761][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][old][710720][92] duration [12.9m], collections [8]/[4.6m], total [12.9m]/[39.7m], memory [29.8gb]->[29.8gb]/[29.8gb], all_pools {[young] [865.3mb]->[865.3mb]/[865.3mb]}{[survivor] [106mb]->[108mb]/[108.1mb]}{[old] [28.9gb]->[28.9gb]/[28.9gb]}
[2017-12-30T10:52:59,952][WARN ][o.e.c.s.ClusterService   ] [box1-2] cluster state update task [zen-disco-receive(from master [master {box3-1}{Ac6MqR9tROioMFgKsfK-Xg}{TRONPx01S2-KSnuPVDHPdQ}{box3-1}{10.10.10.160:9300} committed version [27635]])] took [44.2s] above the warn threshold of 30s
[2017-12-30T11:01:34,122][INFO ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][young][560][27] duration [889ms], collections [1]/[1s], total [889ms]/[5.9s], memory [2.2gb]->[1.4gb]/[29.8gb], all_pools {[young] [857.3mb]->[3.1mb]/[865.3mb]}{[survivor] [106.9mb]->[84.5mb]/[108.1mb]}{[old] [1.3gb]->[1.3gb]/[28.9gb]}
```

**Comment by spinscale** [comment]
Indeed no reclamation seems of the old space seems to happen.

a heap dump (which may contain sensitive information as it is a memory copy) might shed some more light on this. Have you tried taking and analysing one? Or did you go out of memory and potentially one has already been written to disk?

Did you do a restart between 08:51 and 11:01? Somehow there is suddently a ton of free memory? The message at 10:52 indicates that a small cluster state update also took a mere 44 seconds.

Just to verify: You did not accidentally keep opening new scrolls and the others had a crazy high timeout or something? Checking the number of open search contexts in the stats API would help to verify this.

Also has an out of memory exception occured somewhere in the logs already?

**Comment by ripjarphil** [comment]
The elastic process was reaped by the OS between 08:51 and 11:01 which is why the memory usage suddenly dropped. 

I've just checked the code again, and we're not opening new scrolls (this was a prime suspect on our side too). Though the scroll size was bumped to 4000, instead of 100 as previously stated. 

We don't have output from the _stats endpoint for this period. At the moment, the number of open search contexts is 0. When we run a similar scroll operation again, I can update this ticket with the number of open search contexts.

**Comment by ripjarphil** [comment]
We had another node disappear briefly from the cluster. The disconnection error from another node is as follows:
```
org.elasticsearch.transport.NodeDisconnectedException: [dhproc2-2][10.10.10.164:9300][indices:monitor/stats[n]] disconnected
[2018-01-03T19:36:22,333][DEBUG][o.e.a.a.i.s.TransportIndicesStatsAction] [dhproc3-1] failed to execute [indices:monitor/stats] on node [urTijqtcTG-5_Fp4WlcJBQ]
org.elasticsearch.transport.NodeNotConnectedException: [dhproc2-2][10.10.10.164:9300] Node not connected
        at org.elasticsearch.transport.TcpTransport.getConnection(TcpTransport.java:654) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.transport.TcpTransport.getConnection(TcpTransport.java:116) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.transport.TransportService.getConnection(TransportService.java:530) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:493) [elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction.sendNodeRequest(TransportBroadcastByNodeAction.java:322) [elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction.start(TransportBroadcastByNodeAction.java:311) [elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction.doExecute(TransportBroadcastByNodeAction.java:234) [elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction.doExecute(TransportBroadcastByNodeAction.java:79) [elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:170) [elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:142) [elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:84) [elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) [elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72) [elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408) [elasticsearch-5.5.1.jar:5.5.1]
```

The logs from the node that died is as follows. It looks like there was some huge and long GC periods.

```
[2018-01-03T19:34:19,439][INFO ][o.e.m.j.JvmGcMonitorService] [dhproc2-2] [gc][369756] overhead, spent [312ms] collecting in the last [1.1s]
[2018-01-03T19:36:03,999][WARN ][o.e.m.j.JvmGcMonitorService] [dhproc2-2] [gc][old][369757][135] duration [1.7m], collections [1]/[1.7m], total [1.7m]/[22m], memory [28.7gb]->[27.7gb]/[29.8gb], all_pool
s {[young] [7.6mb]->[183.3mb]/[865.3mb]}{[survivor] [108.1mb]->[0b]/[108.1mb]}{[old] [28.6gb]->[27.5gb]/[28.9gb]}
[2018-01-03T19:36:04,000][WARN ][o.e.m.j.JvmGcMonitorService] [dhproc2-2] [gc][369757] overhead, spent [1.7m] collecting in the last [1.7m]
[2018-01-03T19:36:03,995][WARN ][o.e.a.b.TransportShardBulkAction] [dhproc2-2] [[news_1487808000000][2]] failed to perform indices:data/write/bulk[s] on replica [news_1487808000000][2], node[kCkNOqdFTeu
WmMExF_P1Pg], [R], s[STARTED], a[id=zXh2iS9ZQzmoZ2Mdefs_7Q]
org.elasticsearch.transport.RemoteTransportException: [dhproc1-3][10.10.10.168:9300][indices:data/write/bulk[s][r]]
Caused by: java.lang.IllegalStateException: active primary shard cannot be a replication target before  relocation hand off [news_1487808000000][2], node[kCkNOqdFTeuWmMExF_P1Pg], [P], s[STARTED], a[id=z
Xh2iS9ZQzmoZ2Mdefs_7Q], state is [STARTED]
        at org.elasticsearch.index.shard.IndexShard.verifyReplicationTarget(IndexShard.java:1141) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.shard.IndexShard.acquireReplicaOperationLock(IndexShard.java:1666) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncReplicaAction.doRun(TransportReplicationAction.java:566) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$ReplicaOperationTransportHandler.messageReceived(TransportReplicationAction.java:451) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$ReplicaOperationTransportHandler.messageReceived(TransportReplicationAction.java:441) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1544) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.5.1.jar:5.5.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
[2018-01-03T19:36:03,987][WARN ][o.e.a.b.TransportShardBulkAction] [dhproc2-2] [[historic_news_dj_1306368000000][1]] failed to perform indices:data/write/bulk[s] on replica [historic_news_dj_1306368000000][1], 
```

**Comment by ripjarphil** [comment]
> Also has an out of memory exception occured somewhere in the logs already?

From the logs, the original elastic node was not reaped by the OS. It ran out of memory.
```
[2017-12-30T10:27:45,760][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [dhproc2-2] fatal error in thread [Thread-684115], exiting
java.lang.OutOfMemoryError: Java heap space
```

**Comment by jasontedor** [comment]
Can you verify if in your startup logs you have `-Dio.netty.recycler.maxCapacityPerThread=0` (you can also get this from the nodes API)?

**Comment by ripjarphil** [comment]
`-Dio.netty.recycler.maxCapacityPerThread=0` is set in our jvm.options file.

**Comment by jasontedor** [comment]
Okay, as @spinscale asked:

>a heap dump (which may contain sensitive information as it is a memory copy) might shed some more light on this. Have you tried taking and analysing one? Or did you go out of memory and potentially one has already been written to disk?

We are not going to be able to help you without a heap dump analysis.

**Comment by ripjarphil** [comment]
Some more details about our cluster.

* 9 nodes
  * Each node has 128GB memory, 30GB allocated to elastic
  * 4 x 4 JBOD disks on each node
  * 8 physical CPU cores on each node
  * 2507 shards on the index.

**Comment by ripjarphil** [comment]
@jasontedor @spinscale 

A heap dump is going to be 30GB in size. Could you tell us what tell tale signs we should be looking for in a heap dump?

**Comment by jasontedor** [comment]
You need to find out what is consuming the majority of the heap.

**Comment by ripjarphil** [comment]
The following is the output from `GET /_nodes/stats/indices/search` while we're scrolling over 9719627 documents across 62 indexes. The documents span 3 years of data.

The number of `open_contexts` does not increase. 

Will attempt to generate an inspect a heap dump.

```
{
    "_nodes": {
        "total": 8,
        "successful": 8,
        "failed": 0
    },
    "cluster_name": "dch-op-cluster",
    "nodes": {
        "Ac6MqR9tROioMFgKsfK-Xg": {
            "timestamp": 1515409198083,
            "name": "dhproc3-1",
            "host": "dhproc3-1",
            "roles": [
                "master",
                "data",
                "ingest"
            ],
            "indices": {
                "search": {
                    "open_contexts": 41,
                    "query_total": 6803151,
                    "query_time_in_millis": 14470298,
                    "query_current": 0,
                    "fetch_total": 12529,
                    "fetch_time_in_millis": 1734415,
                    "fetch_current": 0,
                    "scroll_total": 1034,
                    "scroll_time_in_millis": 3656412643,
                    "scroll_current": 42,
                    "suggest_total": 0,
                    "suggest_time_in_millis": 0,
                    "suggest_current": 0
                }
            }
        },
        "fEEZg21jSi63Q7Ki_4A9zA": {
            "timestamp": 1515409198082,
            "name": "dhproc2-1",
            "host": "dhproc2-1",
            "roles": [
                "master",
                "data",
                "ingest"
            ],
            "indices": {
                "search": {
                    "open_contexts": 36,
                    "query_total": 3169912,
                    "query_time_in_millis": 920046,
                    "query_current": 0,
                    "fetch_total": 259,
                    "fetch_time_in_millis": 3945,
                    "fetch_current": 0,
                    "scroll_total": 120,
                    "scroll_time_in_millis": 24498384,
                    "scroll_current": 36,
                    "suggest_total": 0,
                    "suggest_time_in_millis": 0,
                    "suggest_current": 0
                }
            }
        },
        "uToW7PcsTLe6TtmP639JDw": {
            "timestamp": 1515409198083,
            "name": "dhproc3-2",
            "host": "dhproc3-2",
            "roles": [
                "master",
                "data",
                "ingest"
            ],
            "indices": {
                "search": {
                    "open_contexts": 45,
                    "query_total": 19005631,
                    "query_time_in_millis": 43362682,
                    "query_current": 0,
                    "fetch_total": 457662,
                    "fetch_time_in_millis": 40447166,
                    "fetch_current": 0,
                    "scroll_total": 12384,
                    "scroll_time_in_millis": 6440899159,
                    "scroll_current": 50,
                    "suggest_total": 0,
                    "suggest_time_in_millis": 0,
                    "suggest_current": 0
                }
            }
        },
        "kCkNOqdFTeuWmMExF_P1Pg": {
            "timestamp": 1515409198083,
            "name": "dhproc1-3",
            "host": "dhproc1-3",
            "roles": [
                "master",
                "data",
                "ingest"
            ],
            "indices": {
                "search": {
                    "open_contexts": 38,
                    "query_total": 18600539,
                    "query_time_in_millis": 49222913,
                    "query_current": 0,
                    "fetch_total": 440033,
                    "fetch_time_in_millis": 44770292,
                    "fetch_current": 0,
                    "scroll_total": 12121,
                    "scroll_time_in_millis": 5895367424,
                    "scroll_current": 41,
                    "suggest_total": 0,
                    "suggest_time_in_millis": 0,
                    "suggest_current": 0
                }
            }
        },
        "urTijqtcTG-5_Fp4WlcJBQ": {
            "timestamp": 1515409198083,
            "name": "dhproc2-2",
            "host": "dhproc2-2",
            "roles": [
                "master",
                "data",
                "ingest"
            ],
            "indices": {
                "search": {
                    "open_contexts": 37,
                    "query_total": 7877251,
                    "query_time_in_millis": 16841893,
                    "query_current": 0,
                    "fetch_total": 9133,
                    "fetch_time_in_millis": 22955430,
                    "fetch_current": 0,
                    "scroll_total": 1055,
                    "scroll_time_in_millis": 4011974305,
                    "scroll_current": 41,
                    "suggest_total": 0,
                    "suggest_time_in_millis": 0,
                    "suggest_current": 0
                }
            }
        },
        "bU_fxjk_SliE0DTSerCdsA": {
            "timestamp": 1515409198083,
            "name": "dhproc2-3",
            "host": "dhproc2-3",
            "roles": [
                "master",
                "data",
                "ingest"
            ],
            "indices": {
                "search": {
                    "open_contexts": 46,
                    "query_total": 7082100,
                    "query_time_in_millis": 9959213,
                    "query_current": 0,
                    "fetch_total": 8536,
                    "fetch_time_in_millis": 530097,
                    "fetch_current": 0,
                    "scroll_total": 1249,
                    "scroll_time_in_millis": 4468727118,
                    "scroll_current": 50,
                    "suggest_total": 0,
                    "suggest_time_in_millis": 0,
                    "suggest_current": 0
                }
            }
        },
        "-_KLxepPTSWUyXV7K0Phcg": {
            "timestamp": 1515409198083,
            "name": "dhproc3-3",
            "host": "dhproc3-3",
            "roles": [
                "master",
                "data",
                "ingest"
            ],
            "indices": {
                "search": {
                    "open_contexts": 29,
                    "query_total": 19578142,
                    "query_time_in_millis": 51957058,
                    "query_current": 0,
                    "fetch_total": 477278,
                    "fetch_time_in_millis": 41974012,
                    "fetch_current": 0,
                    "scroll_total": 12157,
                    "scroll_time_in_millis": 7535575289,
                    "scroll_current": 31,
                    "suggest_total": 0,
                    "suggest_time_in_millis": 0,
                    "suggest_current": 0
                }
            }
        },
        "rTxbE6QrTTGoiEv1pFr2RQ": {
            "timestamp": 1515409198083,
            "name": "dhproc1-2",
            "host": "dhproc1-2",
            "roles": [
                "master",
                "data",
                "ingest"
            ],
            "indices": {
                "search": {
                    "open_contexts": 38,
                    "query_total": 8176481,
                    "query_time_in_millis": 15678450,
                    "query_current": 0,
                    "fetch_total": 10176,
                    "fetch_time_in_millis": 16098189,
                    "fetch_current": 0,
                    "scroll_total": 1124,
                    "scroll_time_in_millis": 4570583655,
                    "scroll_current": 39,
                    "suggest_total": 0,
                    "suggest_time_in_millis": 0,
                    "suggest_current": 0
                }
            }
        }
    }
}
```

**Comment by ripjarphil** [comment]
We're working on getting the heap dump. We had the `-XX:+HeapDumpOnOutOfMemoryError` flag set but we hadn't specified `-XX:HeapDumpPath`. We have this specified now so the next time we get and `OutOfMemory` exception we will have a heap dump.

Our master node became unresponsive yesterday as a result of long GC pauses, but it eventually recovered. 
Once the master became unresponsive, the other nodes started GC'ing more frequently and for longer until they eventually ran out of memory.

```
super-cluster-2018-01-18.log:[2018-01-18T22:55:27,361][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][200157] overhead, spent [513ms] collecting in the last [1s]
super-cluster-2018-01-18.log:[2018-01-18T22:55:37,769][INFO ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][200167] overhead, spent [547ms] collecting in the last [1.4s]
super-cluster-2018-01-18.log:[2018-01-18T22:55:43,775][INFO ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][200173] overhead, spent [276ms] collecting in the last [1s]
super-cluster-2018-01-18.log:[2018-01-18T22:57:14,217][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][200175] overhead, spent [1.4m] collecting in the last [1.4m]
super-cluster-2018-01-18.log:[2018-01-18T22:57:15,266][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][200176] overhead, spent [587ms] collecting in the last [1s]
super-cluster-2018-01-18.log:[2018-01-18T22:58:29,821][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][200177] overhead, spent [1.2m] collecting in the last [1.2m]
super-cluster-2018-01-18.log:[2018-01-18T22:59:37,090][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][200178] overhead, spent [1.1m] collecting in the last [1.1m]
super-cluster-2018-01-18.log:[2018-01-18T23:00:43,707][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][200179] overhead, spent [1.1m] collecting in the last [1.1m]
super-cluster-2018-01-18.log:[2018-01-18T23:01:39,442][WARN ][o.e.m.j.JvmGcMonitorService] [box1-2] [gc][200180] overhead, spent [55.3s] collecting in the last [55.7s]
```
From the logs you can see a step change in the time spent in GC from 22:57 when the master dropped off.

The next time an OutOfMemory occurs, we will have a heap dump.

**Comment by ripjarphil** [comment]
We're seeing a lot of GC pauses at the moment. The output of `hot_threads` is attached.
It looks like we're spending a lot of CPU time doing `merges` and `management`.

Is this normal? What could be the cause of this?

[hot_threads.txt](https://github.com/elastic/elasticsearch/files/1647351/hot_threads.txt)

**Comment by jasontedor** [comment]
No additional feedback, closing.
