### ISSUE TITLE
[CI] PluginsServiceTests: Could not remove the files on Windows

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#28079]
Looks like all these are failing identically on windows, after: https://github.com/elastic/elasticsearch/commit/d36ec180295db3cbe574d050e5c27cfe0a1390bf .

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1066/
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1067
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1068

```
11:52:33    > Throwable #1: java.io.IOException: Could not remove the following files (in the order of attempts):
11:52:33    >    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\core\build\testrun\test\J2\temp\org.elasticsearch.plugins.PluginsServiceTests_24496493EC2B967E-001\tempDir-002\plugins\nonextensible\plugin.jar: java.nio.file.FileSystemException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\core\build\testrun\test\J2\temp\org.elasticsearch.plugins.PluginsServiceTests_24496493EC2B967E-001\tempDir-002\plugins\nonextensible\plugin.jar: The process cannot access the file because it is being used by another process.
11:52:33    >    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\core\build\testrun\test\J2\temp\org.elasticsearch.plugins.PluginsServiceTests_24496493EC2B967E-001\tempDir-002\plugins\nonextensible: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\core\build\testrun\test\J2\temp\org.elasticsearch.plugins.PluginsServiceTests_24496493EC2B967E-001\tempDir-002\plugins\nonextensible
11:52:33    >    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\core\build\testrun\test\J2\temp\org.elasticsearch.plugins.PluginsServiceTests_24496493EC2B967E-001\tempDir-002\plugins: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\core\build\testrun\test\J2\temp\org.elasticsearch.plugins.PluginsServiceTests_24496493EC2B967E-001\tempDir-002\plugins
11:52:33    >    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\core\build\testrun\test\J2\temp\org.elasticsearch.plugins.PluginsServiceTests_24496493EC2B967E-001\tempDir-002: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\core\build\testrun\test\J2\temp\org.elasticsearch.plugins.PluginsServiceTests_24496493EC2B967E-001\tempDir-002
11:52:33    >    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\core\build\testrun\test\J2\temp\org.elasticsearch.plugins.PluginsServiceTests_24496493EC2B967E-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\core\build\testrun\test\J2\temp\org.elasticsearch.plugins.PluginsServiceTests_24496493EC2B967E-001
11:52:33    > 	at __randomizedtesting.SeedInfo.seed([24496493EC2B967E]:0)
11:52:33    > 	at org.apache.lucene.util.IOUtils.rm(IOUtils.java:329)
11:52:33    > 	at java.lang.Thread.run(Thread.java:745)
```

Ryan can you take a look please?

**Comment by rjernst** [comment]
Closing in favor of #28095
