### ISSUE TITLE
Error connecting ElasticSearch 5.4.3 or 5.4.1 maven project java

### ISSUE THREAD

**Issue by khalildiouri** [elastic/elasticsearch#28112]
I'm working on an app maven java using websphere server 8.5 and elasticsearch 5.4 

this is all my dependencies for ES 5

	[	<dependency>
			<groupId>org.elasticsearch.client</groupId>
			<artifactId>transport</artifactId>
			<version>5.4.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.7</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.7</version>
		</dependency>]

I when I start my server (of course es 5 is already started on 9200 localhost) I got this error

[[05/01/18 19:54:31:660 WET] 00000054 SystemErr     R ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
    [05/01/18 19:54:33:373 WET] 000000b9 SystemErr     R Exception in thread "elasticsearch[_client_][management][T#1]" java.lang.AbstractMethodError: org/elasticsearch/transport/TcpTransport.connectToChannels(Lorg/elasticsearch/cluster/node/DiscoveryNode;Lorg/elasticsearch/transport/ConnectionProfile;)Lorg/elasticsearch/transport/TcpTransport$NodeChannels;
    [05/01/18 19:54:33:373 WET] 000000b9 SystemErr     R    at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:534)
    [05/01/18 19:54:33:373 WET] 000000b9 SystemErr     R    at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:116)
    [05/01/18 19:54:33:373 WET] 000000b9 SystemErr     R    at org.elasticsearch.transport.TransportService.openConnection(TransportService.java:334)
    [05/01/18 19:54:33:373 WET] 000000b9 SystemErr     R    at org.elasticsearch.client.transport.TransportClientNodesService$SniffNodesSampler$1.doRun(TransportClientNodesService.java:507)
    [05/01/18 19:54:33:373 WET] 000000b9 SystemErr     R    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
    [05/01/18 19:54:33:373 WET] 000000b9 SystemErr     R    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    [05/01/18 19:54:33:373 WET] 000000b9 SystemErr     R    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
    [05/01/18 19:54:33:373 WET] 000000b9 SystemErr     R    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    [05/01/18 19:54:33:373 WET] 000000b9 SystemErr     R    at java.lang.Thread.run(Thread.java:785)
  ]

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by khalildiouri** [comment]
can you see please https://discuss.elastic.co/t/error-connecting-elasticsearch-5-4-3-or-5-4-1-maven-project-java/114345
