### ISSUE TITLE
[CI] Vagrant Fedora26 packaging test failures

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#28135]
Build reproduce command: `./gradlew :qa:vagrant:vagrantFedora26#packagingTest -Dtests.seed=7025CFAE3D65AD38`

I was not able to reproduce.

The problem is that an unexpected health status is returned.

```
# --2018-01-08 14:17:33--  (try:119)  http://localhost:9200/_cluster/health
# Connecting to localhost (localhost)|::1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|127.0.0.1|:9200... failed: Connection refused.
# Retrying.
# 
# --2018-01-08 14:17:34--  (try:120)  http://localhost:9200/_cluster/health
# Connecting to localhost (localhost)|::1|:9200... failed: Connection refused.
# Connecting to # Connecting to 
localhost (localhost)|127.0.0.1|:9200... failed: Connection refused.
# Giving up.
# 
# Looks like elasticsearch never started. Here is its log:
# The elasticsearch log doesn't exist. Maybe /var/log/messages has something:
# tail: cannot open '/var/log/messages' for reading: No such file or directory
localhost (localhost)|127.0.0.1|:9200... failed: Connection refused.
# Giving up.
# 
# Looks like elasticsearch never started. Here is its log:
# The elasticsearch log doesn't exist. Maybe /var/log/messages has something:
# tail: cannot open '/var/log/messages' for reading: No such file or directory
not ok 214 [UPGRADE] check elasticsearch version is old version
not ok 214 [UPGRADE] check elasticsearch version is old version
# (from function `check_elasticsearch_version' in file /project/build/bats/utils/utils.bash, line 465,
# (from function `check_elasticsearch_version' in file /project/build/bats/utils/utils.bash, line 465,
#  in test file /project/build/bats/tests/80_upgrade.bats, line 62)
#  in test file /project/build/bats/tests/80_upgrade.bats, line 62)
#   `check_elasticsearch_version "$(cat upgrade_from_version)"' failed
#   `check_elasticsearch_version "$(cat upgrade_from_version)"' failed
not ok 215 [UPGRADE] index some documents into a few indexes
not ok 215 [UPGRADE] index some documents into a few indexes
# (in test file /project/build/bats/tests/80_upgrade.bats, line 66)
# (in test file /project/build/bats/tests/80_upgrade.bats, line 66)
#   `curl -s -H "Content-Type: application/json" -XPOST localhost:9200/library/book/1?pretty -d '{' failed with status 7
#   `curl -s -H "Content-Type: application/json" -XPOST localhost:9200/library/book/1?pretty -d '{' failed with status 7
not ok 216 [UPGRADE] verify that the documents are there
not ok 216 [UPGRADE] verify that the documents are there
# (in test file /project/build/bats/tests/80_upgrade.bats, line 78)
# (in test file /project/build/bats/tests/80_upgrade.bats, line 78)
#   `curl -s localhost:9200/library/book/1?pretty | grep Elasticsearch' failed
#   `curl -s localhost:9200/library/book/1?pretty | grep Elasticsearch' failed
ok 217 [UPGRADE] stop old version
ok 218 [UPGRADE] install version under test
not ok 219 [UPGRADE] start version under test
not ok 219 [UPGRADE] start version under test
# (from function `wait_for_elasticsearch_status' in file /project/build/bats/utils/utils.bash, line 454,
# (from function `wait_for_elasticsearch_status' in file /project/build/bats/utils/utils.bash, line 454,
#  from function `start_elasticsearch_service' in file /project/build/bats/utils/utils.bash, line 312,
#  from function `start_elasticsearch_service' in file /project/build/bats/utils/utils.bash, line 312,
#  in test file /project/build/bats/tests/80_upgrade.bats, line 96)
#  in test file /project/build/bats/tests/80_upgrade.bats, line 96)
#   `start_elasticsearch_service yellow library' failed
#   `start_elasticsearch_service yellow library' failed
# Making sure elasticsearch is up...
# --2018-01-08 14:17:35--  http://localhost:9200/_cluster/health
# Making sure elasticsearch is up...
# --2018-01-08 14:17:35--  http://localhost:9200/_cluster/health
# Resolving localhost (localhost)... ::1, 127.0.0.1
# Resolving localhost (localhost)... ::1, 127.0.0.1
# Connecting to localhost (localhost)|::1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|::1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|127.0.0.1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|127.0.0.1|:9200... failed: Connection refused.
# Retrying.
# 
# Retrying.
# 
# --2018-01-08 14:17:36--  (try: 2)  http://localhost:9200/_cluster/health
# --2018-01-08 14:17:36--  (try: 2)  http://localhost:9200/_cluster/health
# Connecting to localhost (localhost)|::1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|127.0.0.1|:9200... failed: Connection refused.
# Retrying.
# 
# Connecting to localhost (localhost)|::1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|127.0.0.1|:9200... failed: Connection refused.
# Retrying.
# 
# --2018-01-08 14:17:37--  (try: 3)  http://localhost:9200/_cluster/health
# --2018-01-08 14:17:37--  (try: 3)  http://localhost:9200/_cluster/health
# Connecting to localhost (localhost)|::1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|::1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|127.0.0.1|:9200... failed: Connection refused.
# Retrying.
# Connecting to localhost (localhost)|127.0.0.1|:9200... failed: Connection refused.
# Retrying.
# 
# 
# --2018-01-08 14:17:38--  (try: 4)  http://localhost:9200/_cluster/health
# --2018-01-08 14:17:38--  (try: 4)  http://localhost:9200/_cluster/health
# Connecting to localhost (localhost)|::1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|::1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|127.0.0.1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|127.0.0.1|:9200... failed: Connection refused.
# Retrying.
# Retrying.
# 
# --2018-01-08 14:17:39--  (try: 5)  http://localhost:9200/_cluster/health
# 
# --2018-01-08 14:17:39--  (try: 5)  http://localhost:9200/_cluster/health
# Connecting to localhost (localhost)|::1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|::1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|127.0.0.1|:9200... failed: Connection refused.
# Retrying.
# 
# --2018-01-08 14:17:40--  (try: 6)  http://localhost:9200/_cluster/health
# Connecting to localhost (localhost)|::1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|127.0.0.1|:9200... failed: Connection refused.
# Retrying.
# 
# --2018-01-08 14:17:40--  (try: 6)  http://localhost:9200/_cluster/health
# Connecting to localhost (localhost)|::1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|127.0.0.1|:9200... failed: Connection refused.
# Retrying.
# 
# Connecting to localhost (localhost)|127.0.0.1|:9200... failed: Connection refused.
# Retrying.
# 
# --2018-01-08 14:17:41--  (try: 7)  http://localhost:9200/_cluster/health
# --2018-01-08 14:17:41--  (try: 7)  http://localhost:9200/_cluster/health
# Connecting to localhost (localhost)|::1|:9200... connected.
# Connecting to localhost (localhost)|::1|:9200... connected.
# HTTP request sent, awaiting response... 200 OK
# HTTP request sent, awaiting response... 200 OK
# Length: 223 [application/json]
# Saving to: ‘STDOUT’
# Length: 223 [application/json]
# Saving to: ‘STDOUT’
# {"cluster_name":"elasticsearch","status":"green","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":0,"active_shards":0,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0}
# {"cluster_name":"elasticsearch","status":"green","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":0,"active_shards":0,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0}
#      0K                                                       100% 57.5M=0s
# 
# 2018-01-08 14:17:41 (57.5 MB/s) - written to stdout [389]
#      0K                                                       100% 57.5M=0s
# 
# 2018-01-08 14:17:41 (57.5 MB/s) - written to stdout [389]
# 
# Trying to connect to elasticsearch and wait for expected status yellow for index library
# 
# Trying to connect to elasticsearch and wait for expected status yellow for index library
# {
#   "cluster_name" : "elasticsearch",
#   "status" : "red",
# {
#   "cluster_name" : "elasticsearch",
#   "status" : "red",
#   "timed_out" : true,
#   "timed_out" : true,
#   "number_of_nodes" : 1,
#   "number_of_nodes" : 1,
#   "number_of_data_nodes" : 1,
#   "number_of_data_nodes" : 1,
#   "active_primary_shards" : 0,
#   "active_primary_shards" : 0,
#   "active_shards" : 0,
#   "active_shards" : 0,
#   "relocating_shards" : 0,
#   "relocating_shards" : 0,
#   "initializing_shards" : 0,
#   "initializing_shards" : 0,
#   "unassigned_shards" : 0,
#   "unassigned_shards" : 0,
#   "delayed_unassigned_shards" : 0,
#   "delayed_unassigned_shards" : 0,
#   "number_of_pending_tasks" : 0,
#   "number_of_pending_tasks" : 0,
#   "number_of_in_flight_fetch" : 0,
#   "number_of_in_flight_fetch" : 0,
#   "task_max_waiting_in_queue_millis" : 0,
#   "task_max_waiting_in_queue_millis" : 0,
#   "active_shards_percent_as_number" : 100.0
#   "active_shards_percent_as_number" : 100.0
# }
# }
# Connected
# Connected
# Checking that the cluster health matches the waited for status...
# Checking that the cluster health matches the waited for status...
# unexpected status:  'green' wanted 'yellow'
# unexpected status:  'green' wanted 'yellow'
ok 220 [UPGRADE] check elasticsearch version is version under test
not ok 221 [UPGRADE] verify that the documents are there after restart
not ok 221 [UPGRADE] verify that the documents are there after restart
# (in test file /project/build/bats/tests/80_upgrade.bats, line 105)
# (in test file /project/build/bats/tests/80_upgrade.bats, line 105)
#   `curl -s localhost:9200/library/book/1?pretty | grep Elasticsearch' failed
#   `curl -s localhost:9200/library/book/1?pretty | grep Elasticsearch' failed
ok 222 [UPGRADE] stop version under test
ok 223 [REINSTALL] install
ok 224 [REINSTALL] purge elasticsearch
ok 225 [REINSTALL] chown directories
ok 226 [REINSTALL] reinstall elasticsearch
ok 227 [REINSTALL] check ownership
```

Build links:
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.1+packaging-tests/137/consoleText
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+packaging-tests/469/consoleText

**Comment by cbuescher** [comment]
This looks similar: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+packaging-tests/472/console

**Comment by martijnvg** [comment]
So it turns out that this failure does reproduce on the 6.x branch for me with the following command: `./gradlew clean :qa:vagrant:vagrantFedora26#packagingTest -Dtests.seed=742B4549302B0167`

I ssh-ed into vagrant box and I found this bit in `/var/log/elasticsearch/elasticsearch.log`, which I think causes the failure:

```
[2018-01-09T11:34:13,130][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Matcher.java:536) ~[?:1.8.0_151]
        at org.elasticsearch.monitor.os.OsProbe.getControlGroups(OsProbe.java:216) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:414) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:466) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.monitor.os.OsService.<init>(OsService.java:45) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.monitor.MonitorService.<init>(MonitorService.java:45) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.node.Node.<init>(Node.java:345) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.node.Node.<init>(Node.java:232) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:241) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:241) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) [elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) [elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) [elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) [elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) [elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.cli.Command.main(Command.java:88) [elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) [elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) [elasticsearch-5.2.1.jar:5.2.1]
[2018-01-09T11:34:13,134][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: No match found
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.2.1.jar:5.2.1]
Caused by: java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Matcher.java:536) ~[?:1.8.0_151]
        at org.elasticsearch.monitor.os.OsProbe.getControlGroups(OsProbe.java:216) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:414) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:466) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.monitor.os.OsService.<init>(OsService.java:45) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.monitor.MonitorService.<init>(MonitorService.java:45) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.node.Node.<init>(Node.java:345) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.node.Node.<init>(Node.java:232) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:241) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:241) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.2.1.jar:5.2.1]
        ... 6 more
```

**Comment by jasontedor** [comment]
Duplicates #26968

**Comment by jasontedor** [comment]
Relates #28278
