### ISSUE TITLE
[Jenkins] Failure in org.elasticsearch.index.engine.InternalEngineTests.testTranslogReplayWithFailure

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#28167]
Failed on 6.x: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=amazon/521/console

Reproduce command (reproduces locally for me):
```
./gradlew :core:test -Dtests.seed=5AB1CBA8567E99FC -Dtests.class=org.elasticsearch.index.engine.InternalEngineTests -Dtests.method="testTranslogReplayWithFailure" -Dtests.security.manager=true -Dtests.locale=he -Dtests.timezone=Atlantic/Reykjavik
```

Exception:
```
ERROR   1.13s | InternalEngineTests.testTranslogReplayWithFailure <<< FAILURES!
   > Throwable #1: [index][[index][0]] FlushFailedEngineException[Flush failed]; nested: CorruptIndexException[failed engine (reason: [refresh failed source[version_table_flush]]) (resource=preexisting_corruption)]; nested: IOException[failed engine (reason: [refresh failed source[version_table_flush]])]; nested: CorruptIndexException[Problem reading index from store(MockDirectoryWrapper(RAMDirectory@4bec077e lockFactory=org.apache.lucene.store.SingleInstanceLockFactory@62757fd8)) (resource=store(MockDirectoryWrapper(RAMDirectory@4bec077e lockFactory=org.apache.lucene.store.SingleInstanceLockFactory@62757fd8)))]; nested: FileNotFoundException[a random IOException (_1.cfs)];
   >    at __randomizedtesting.SeedInfo.seed([5AB1CBA8567E99FC:B360CB91E358DFA1]:0)
   >    at org.elasticsearch.index.engine.InternalEngine.refreshLastCommittedSegmentInfos(InternalEngine.java:1558)
   >    at org.elasticsearch.index.engine.InternalEngine.flush(InternalEngine.java:1520)
   >    at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslogInternal(InternalEngine.java:458)
   >    at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:394)
   >    at org.elasticsearch.index.engine.EngineTestCase.createEngine(EngineTestCase.java:341)
   >    at org.elasticsearch.index.engine.EngineTestCase.createEngine(EngineTestCase.java:302)
   >    at org.elasticsearch.index.engine.EngineTestCase.createEngine(EngineTestCase.java:291)
   >    at org.elasticsearch.index.engine.EngineTestCase.createEngine(EngineTestCase.java:260)
   >    at org.elasticsearch.index.engine.InternalEngineTests.testTranslogReplayWithFailure(InternalEngineTests.java:2430)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
   > Caused by: org.apache.lucene.index.CorruptIndexException: failed engine (reason: [refresh failed source[version_table_flush]]) (resource=preexisting_corruption)
   >    at org.elasticsearch.index.store.Store.failIfCorrupted(Store.java:635)
   >    at org.elasticsearch.index.store.Store.failIfCorrupted(Store.java:615)
   >    at org.elasticsearch.index.store.Store.readCommittedSegmentsInfo(Store.java:193)
   >    at org.elasticsearch.index.store.Store.readLastCommittedSegmentsInfo(Store.java:185)
   >    at org.elasticsearch.index.engine.InternalEngine.refreshLastCommittedSegmentInfos(InternalEngine.java:1549)
   >    ... 44 more
   > Caused by: java.io.IOException: failed engine (reason: [refresh failed source[version_table_flush]])
   >    at org.elasticsearch.index.engine.Engine.failEngine(Engine.java:914)
   >    at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:1392)
   >    at org.elasticsearch.index.engine.InternalEngine.flush(InternalEngine.java:1515)
   >    at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslogInternal(InternalEngine.java:458)
   >    at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:394)
   >    at org.elasticsearch.index.engine.EngineTestCase.createEngine(EngineTestCase.java:341)
   >    at org.elasticsearch.index.engine.EngineTestCase.createEngine(EngineTestCase.java:302)
   >    at org.elasticsearch.index.engine.EngineTestCase.createEngine(EngineTestCase.java:291)
   >    at org.elasticsearch.index.engine.EngineTestCase.createEngine(EngineTestCase.java:260)
   >    at org.elasticsearch.index.engine.InternalEngineTests.testTranslogReplayWithFailure(InternalEngineTests.java:2418)
   >    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.lang.Thread.run(Thread.java:844)
   > Caused by: org.apache.lucene.index.CorruptIndexException: Problem reading index from store(MockDirectoryWrapper(RAMDirectory@4bec077e lockFactory=org.apache.lucene.store.SingleInstanceLockFactory@62757fd8)) (resource=store(MockDirectoryWrapper(RAMDirectory@4bec077e lockFactory=org.apache.lucene.store.SingleInstanceLockFactory@62757fd8)))
   >    at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:140)
   >    at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:78)
   >    at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:208)
   >    at org.apache.lucene.index.ReadersAndUpdates.getReadOnlyClone(ReadersAndUpdates.java:258)
   >    at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:105)
   >    at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:490)
   >    at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:293)
   >    at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:268)
   >    at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:258)
   >    at org.apache.lucene.index.FilterDirectoryReader.doOpenIfChanged(FilterDirectoryReader.java:104)
   >    at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:140)
   >    at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:156)
   >    at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
   >    at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
   >    at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
   >    at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:1382)
   >    ... 44 more
   > Caused by: java.io.FileNotFoundException: a random IOException (_1.cfs)
   >    at org.apache.lucene.store.MockDirectoryWrapper.maybeThrowIOExceptionOnOpen(MockDirectoryWrapper.java:575)
   >    at org.apache.lucene.store.MockDirectoryWrapper.openInput(MockDirectoryWrapper.java:744)
   >    at org.apache.lucene.store.FilterDirectory.openInput(FilterDirectory.java:99)
   >    at org.apache.lucene.codecs.lucene50.Lucene50CompoundReader.<init>(Lucene50CompoundReader.java:78)
   >    at org.apache.lucene.codecs.lucene50.Lucene50CompoundFormat.getCompoundReader(Lucene50CompoundFormat.java:71)
   >    at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:99)
   >    ... 59 more
```

**Comment by dnhatn** [comment]
@bleskes I am looking at this.

**Comment by dnhatn** [comment]
This was fixed by https://github.com/elastic/elasticsearch/pull/28228
