### ISSUE TITLE
Elasticsearch problem every milliseconde 

### ISSUE THREAD

**Issue by adrien-vinet** [elastic/elasticsearch#28235]
Hello all,

I contact you because I have a problem with my elasticsearch server.

My configuration :

- Serveur front whit haproxy
- 2 serveurs with elastic search

My haproxy configuration :

```
listen elasticsearch-cluster
	bind 127.0.0.1:9200
        option httpchk
        balance roundrobin
    	server ipvr5.yoomap 172.16.0.5:9200 check
    	server ipvr6.yoomap 172.16.0.6:9200 check backup
```
My elasticsearch configuration (version 2.4.4) :

```
# Elasticsearch 2.X configuration for Yoomap
cluster.name: yoomap_preprod_2
http.port: 9200
node.name: s5.yoomap
discovery.zen.ping.unicast.hosts: ["172.16.0.5", "172.16.0.6"]
network.host: [_eth1_]
network.bind_host: [_eth1_]
node.data: true
node.master: true
bootstrap.mlockall: true
index.query.bool.max_clause_count: 4096
action.auto_create_index: false
```

I have this problem on the log file :

```
[2018-01-16 07:45:06,244][WARN ][http.netty               ] [s5.yoomap] Caught exception while handling client http traffic, closing connection [id: 0x532248d5, /172.16.0.5:53849 => /172.16.0.5:9200]
java.io.IOException: Connection re-initialized by the correspondent
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:384)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Do you have a solution to this problem?

**Comment by tvernum** [comment]
Could you please ask this question on our [discuss forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support. Those forums are designed to support the kinds of conversations that are necessary for this sort of troubleshooting and problem diagnosis.

Elastic uses GitHub issues for tracking clearly identified bugs and feature requests. Since your issue doesn't concern a specific bug, I'm going to close this ticket, but I'm sure someone will be able to help you work through this issue on the [forums](https://discuss.elastic.co/c/elasticsearch) .

Thank you.
