### ISSUE TITLE
elasticsearch6.0,xpack.ssl,Cross Cluster Search

### ISSUE THREAD

**Issue by BigbigY** [elastic/elasticsearch#28318]
I installed elasticsearch6.0.0, and x-pack, and the cluster configured SSL. How do I need to solve the SSL authentication problem with my two clusters?
Thank you very much！

**Comment by BigbigY** [comment]
This is my execution on a cluster.
```
curl -XPUT -u elastic:'ll1~YNi1=gk%qH~C9+xZ' '10.81.91.121:9200/_cluster/settings?pretty' -H 'Content-Type: application/json' -d'
{
  "persistent": {
    "search": {
      "remote": {
        "cluster_rd": {
          "seeds": [
            "10.81.91.121:9300"
          ]
        },
        "cluster_op": {
          "seeds": [
            "10.135.197.9:9300"
          ]
        }
      }
    }
  }
}
'
```
Here is the log：
```
[2018-01-20T22:49:17,809][INFO ][o.e.c.s.ClusterSettings  ] [node-1] updating [search.remote.cluster_rd.seeds] from [[]] to [["10.81.91.121:9300"]]
[2018-01-20T22:49:17,809][INFO ][o.e.c.s.ClusterSettings  ] [node-1] updating [search.remote.cluster_op.seeds] from [[]] to [["10.135.197.9:9300"]]
[2018-01-20T22:49:17,809][INFO ][o.e.c.s.ClusterSettings  ] [node-1] updating [search.remote.cluster_op.seeds] from [[]] to [["10.135.197.9:9300"]]
[2018-01-20T22:49:17,816][INFO ][o.e.c.s.ClusterSettings  ] [node-1] updating [search.remote.cluster_rd.seeds] from [[]] to [["10.81.91.121:9300"]]
[2018-01-20T22:49:17,861][WARN ][o.e.t.RemoteClusterService] [node-1] failed to update seed list for cluster: cluster_op
org.elasticsearch.transport.ConnectTransportException: [][10.135.197.9:9300] general node connection failure
	at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:612) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:121) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.transport.TransportService.openConnection(TransportService.java:353) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.transport.RemoteClusterConnection$ConnectHandler.lambda$collectRemoteNodes$2(RemoteClusterConnection.java:412) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.transport.RemoteClusterConnection$ConnectHandler$$Lambda$2556/151659047.run(Unknown Source) ~[?:?]
	at org.elasticsearch.common.util.CancellableThreads.executeIO(CancellableThreads.java:105) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.transport.RemoteClusterConnection$ConnectHandler.collectRemoteNodes(RemoteClusterConnection.java:409) [elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.transport.RemoteClusterConnection$ConnectHandler$1.doRun(RemoteClusterConnection.java:396) [elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.0.0.jar:6.0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-6.0.0.jar:6.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.IllegalStateException: handshake failed
	at org.elasticsearch.transport.TcpTransport.executeHandshake(TcpTransport.java:1614) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:598) ~[elasticsearch-6.0.0.jar:6.0.0]
	... 14 more
Caused by: org.elasticsearch.transport.TransportException: connection reset
	at org.elasticsearch.transport.TcpTransport.onChannelClosed(TcpTransport.java:1656) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.transport.TcpTransport.lambda$openConnection$10(TcpTransport.java:579) ~[elasticsearch-6.0.0.jar:6.0.0]
	at org.elasticsearch.transport.TcpTransport$$Lambda$2560/1012722958.accept(Unknown Source) ~[?:?]
	at org.elasticsearch.transport.netty4.Netty4Transport.lambda$connectToChannels$2(Netty4Transport.java:277) ~[?:?]
	at org.elasticsearch.transport.netty4.Netty4Transport$$Lambda$2562/337945818.operationComplete(Unknown Source) ~[?:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507) ~[?:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481) ~[?:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420) ~[?:?]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) ~[?:?]
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82) ~[?:?]
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1057) ~[?:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:686) ~[?:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:664) ~[?:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:607) ~[?:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:85) ~[?:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:142) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[?:?]
	... 1 more
```

**Comment by jasontedor** [comment]
Sorry that this repository is for open source Elasticsearch only. For X-Pack, we ask that you use the [forum](https://discuss.elastic.co).
