### ISSUE TITLE
IllegalStateException on data nodes when upgrading 5.6.5 to 6.1.1

### ISSUE THREAD

**Issue by yawboateng** [elastic/elasticsearch#28351]
So i was running 5.4, upgraded that to 5.6.5 (the official docker image on top of kubernetes), and used the migration assistant from the kibana ui to migrate the indexes but after upgrading the cluster to 6.1.1, the container is in a crash loop with the following logs:

```
[2018-01-24T04:35:44,015][ERROR][o.e.g.GatewayMetaState   ] [sJP3p8k] failed to read local state, exiting...
java.lang.IllegalStateException: index and alias names need to be unique, but the following duplicates were found [.watches (alias of [.watches-6/FbLIamfiTieF8hzOKJWbpQ])]
	at org.elasticsearch.cluster.metadata.MetaData$Builder.build(MetaData.java:1032) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.gateway.MetaStateService.loadFullState(MetaStateService.java:73) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:92) [elasticsearch-5.6.5.jar:5.6.5]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_151]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_151]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_151]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_151]
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:49) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:825) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:50) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:825) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:50) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:191) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:183) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:818) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:183) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:173) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:161) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:96) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:42) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.node.Node.<init>(Node.java:499) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.node.Node.<init>(Node.java:245) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) [elasticsearch-5.6.5.jar:5.6.5]
[2018-01-24T04:35:44,277][ERROR][o.e.g.GatewayMetaState   ] [sJP3p8k] failed to read local state, exiting...
```

Note: i have the basic license and do not use watcher. is there a way to recover from this state without losing any data?

**Comment by ywelsch** [comment]
You can delete the directory named `FbLIamfiTieF8hzOKJWbpQ` in your data directory (under `nodes/0/indices`, which is the watcher index that conflicts with the alias.

**Comment by yawboateng** [comment]
This keeps happening even after the upgrade and running v6 for a while now. my data nodes randomly goes in a crashloop with same error but on the kibana index and i end up having to delete and re create.

```
[2018-02-15T15:08:53,635][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [elasticsearch-data-ss-2] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: index and alias names need to be unique, but the following duplicates were found [.kibana (alias of [.kibana-6/_ixMMN4zRK2YKBzfQmUwzA])]
```

**Comment by ywelsch** [comment]
> and i end up having to delete and re create.

what do you mean by that? Are you deleting the folder on disk as I suggested above, or are you issuing a DELETE command on the index?

**Comment by yawboateng** [comment]
the folder

**Comment by ywelsch** [comment]
what do you mean by recreate then? Why are you recreating the folder?

**Comment by yawboateng** [comment]
as in rerun the steps at:
https://www.elastic.co/guide/en/kibana/6.0/migrating-6.0-index.html

**Comment by ywelsch** [comment]
I don't understand why you would rerun those steps as you're already on 6.0?

**Comment by yawboateng** [comment]
Because after deleting, the UI was still showing the error:
`Your Kibana index is out of date, reset it or use the X-Pack upgrade assistant.`

didint happen on the most recent delete though. 


anyway, I randomly get that same error for some of my indexes that I've created an  alias for...runs ok for weeks then all of a sudden, it goes into a crashloop

```
[2018-02-15T15:08:53,635][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [elasticsearch-data-ss-2] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: index and alias names need to be unique, but the following duplicates were found [yawboateng-2018.01.29 (alias of [yawboateng-2018.01.29.v1/EyFtdHEMT5qPYd1r58x8fw])]
```

should we not be creating aliases? 

I did my in other to change the number of shards from the default 5. 

steps:

1, create a new index, set the new number of shards, and replicas (number_of_shards and number_of_replicas)
2, re-index the old indexes to use the new one
3, create an aliases between the old index name and the new one
4, delete the old index

**Comment by yawboateng** [comment]
hit it again:
```
[2018-02-19T16:52:09,863][ERROR][o.e.g.GatewayMetaState   ] [elasticsearch-data-ss-2] failed to read local state, exiting...
java.lang.IllegalStateException: index and alias names need to be unique, but the following duplicates were found [.kibana (alias of [.kibana-6/_ixMMN4zRK2YKBzfQmUwzA])]
	at org.elasticsearch.cluster.metadata.MetaData$Builder.build(MetaData.java:948) ~[elasticsearch-6.1.1.jar:6.1.1]
```

Note i did  not recreate the steps: https://github.com/elastic/elasticsearch/issues/28351#issuecomment-366189216

**Comment by yawboateng** [comment]
just upgraded from 6.1 to 6.2 and kibana is showing:

`plugin:elasticsearch@6.2.1 | Your Kibana index is out of date, reset it or use the X-Pack upgrade assistant.`

which i believe ill have to rerun: https://github.com/elastic/elasticsearch/issues/28351#issuecomment-365998467 again
