### ISSUE TITLE
[CI] RequestTests#testSearch fails with NPE

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#28388]
Link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+multijob-unix-compatibility/os=centos/612/console

Failure:
```
java.lang.NullPointerException
	at __randomizedtesting.SeedInfo.seed([7A40FF09261C0606:E8F96A5C62055EA9]:0)
	at org.elasticsearch.client.RequestTests.assertToXContentBody(RequestTests.java:787)
	at org.elasticsearch.client.RequestTests.testSearch(RequestTests.java:754)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1713)
	at 
```

Reproduce locally:
```
REPRODUCE WITH: ./gradlew :client:rest-high-level:test \
  -Dtests.seed=7A40FF09261C0606 \
  -Dtests.class=org.elasticsearch.client.RequestTests \
  -Dtests.method="testSearch" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-NI \
  -Dtests.timezone=Canada/Atlantic
```

**Comment by cbuescher** [comment]
Closed by #28391
