### ISSUE TITLE
[CI] InstallPluginCommandTests fails on Windows

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#28415]
There are several instances of this failure across all branches on Windows, latest from today: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1182/console

```
REPRODUCE WITH: gradlew :distribution:tools:plugin-cli:test \
  -Dtests.seed=CF27A2AD2D708EFD \
  -Dtests.class=org.elasticsearch.plugins.InstallPluginCommandTests \
  -Dtests.security.manager=false \
  -Dtests.locale=en-US \
  -Dtests.timezone=UTC
```

```
ERROR   0.00s J0 | InstallPluginCommandTests (suite) <<< FAILURES!
   > Throwable #1: java.io.IOException: Could not remove the following files (in the order of attempts):
   >    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\distribution\tools\plugin-cli\build\testrun\test\J0\temp\org.elasticsearch.plugins.InstallPluginCommandTests_CF27A2AD2D708EFD-001\install-plugin-command-tests-031: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\distribution\tools\plugin-cli\build\testrun\test\J0\temp\org.elasticsearch.plugins.InstallPluginCommandTests_CF27A2AD2D708EFD-001\install-plugin-command-tests-031
   >    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\distribution\tools\plugin-cli\build\testrun\test\J0\temp\org.elasticsearch.plugins.InstallPluginCommandTests_CF27A2AD2D708EFD-001\install-plugin-command-tests-031\plugins: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\distribution\tools\plugin-cli\build\testrun\test\J0\temp\org.elasticsearch.plugins.InstallPluginCommandTests_CF27A2AD2D708EFD-001\install-plugin-command-tests-031\plugins
   >    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\distribution\tools\plugin-cli\build\testrun\test\J0\temp\org.elasticsearch.plugins.InstallPluginCommandTests_CF27A2AD2D708EFD-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\distribution\tools\plugin-cli\build\testrun\test\J0\temp\org.elasticsearch.plugins.InstallPluginCommandTests_CF27A2AD2D708EFD-001
   > 	at __randomizedtesting.SeedInfo.seed([CF27A2AD2D708EFD]:0)
   > 	at org.apache.lucene.util.IOUtils.rm(IOUtils.java:329)
   > 	at java.lang.Thread.run(Thread.java:748)
```

Need to see if it is reproducable on Windows.

**Comment by cbuescher** [comment]
Looks like something is wrong with the `testMetaPluginPolicyConfirmation` test that was recently added, I can reproduce the failure on Windows now with:

```
 gradle :distribution:tools:plugin-cli:test -Dtests.class=org.elasticsearch.plugins.InstallPluginCommandTests -Dtests.method="testMetaPluginPolicyConfirmation"
```

**Comment by cbuescher** [comment]
Since this is failing consistently on all Windows builds on master, 6.x and 6.2 I will @AwaitsFix the `testMetaPluginPolicyConfirmation` test for now. @rjernst let me know if you disagree or have an idea for a fix.

**Comment by cbuescher** [comment]
Finally got to the cause of this. It turns out that the new test was iterating over a stream of files for an assertion via `Files.list(env.v2().pluginsFile())` which should be closed after use. This seems to be tolerated by most Linux implementations but Windows seems to be picky here. I will have a PR up shortly.

**Comment by jasontedor** [comment]
Thank you for the persistence @cbuescher!
