### ISSUE TITLE
[CI] Failure in SuggestStatsIT testSimpleStats

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#28543]
Link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/2018/console

```
00:24:36 FAILURE 4.45s J1 | SuggestStatsIT.testSimpleStats <<< FAILURES!
00:24:36    > Throwable #1: java.lang.AssertionError: 
00:24:36    > Expected: a value greater than <0L>
00:24:36    >      but: <0L> was equal to <0L>
00:24:36    > 	at __randomizedtesting.SeedInfo.seed([FDC21049ED079812:B806696314BB0DE2]:0)
00:24:36    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
00:24:36    > 	at org.elasticsearch.index.suggest.stats.SuggestStatsIT.testSimpleStats(SuggestStatsIT.java:127)
00:24:36    > 	at java.lang.Thread.run(Thread.java:748)
```

Doesn't reproduce locally for me so far with:
```
./gradlew :server:integTest -Dtests.seed=FDC21049ED079812 -Dtests.class=org.elasticsearch.index.suggest.stats.SuggestStatsIT -Dtests.method="testSimpleStats" -Dtests.security.manager=true -Dtests.locale=ar-BH -Dtests.timezone=Australia/Eucla
```

**Comment by cbuescher** [comment]
The particular assertion tripping here is checking `assertThat(suggestStats.getSuggestTimeInMillis(), greaterThan(0L)`)`. When I run this test on a somewhat bigger machine locally I cannot get it to fail but I get close to execution times as low as 5-7ms, so I think it is entirely possible that on faster machines this might occasionally get rounded to 0ms. I think we can relax the assertion to `greaterThanOrEqualTo(0L)`. I will check if there are other similar occurances in this integration test and open a PR.
