### ISSUE TITLE
[CI] TikaDocTests and AttachmentProcessorTests failing on oracle-java10-periodic

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#28568]
The following tests fail reproducibly for the java-10 builds on master and 6.x:

I can reproduce this locally using Oracle Corporation 10-ea [Java HotSpot(TM) 64-Bit Server VM 10-ea+42] on master with

```
REPRODUCE WITH: ./gradlew :plugins:ingest-attachment:test \
  -Dtests.seed=1E6696FD299DB332 \
  -Dtests.class=org.elasticsearch.ingest.attachment.TikaDocTests \
  -Dtests.method="testFiles" \
  -Dtests.security.manager=true \
  -Dtests.locale=so-ET \
  -Dtests.timezone=Europe/Vatican

REPRODUCE WITH: ./gradlew :plugins:ingest-attachment:test \
  -Dtests.seed=1E6696FD299DB332 \
  -Dtests.class=org.elasticsearch.ingest.attachment.AttachmentProcessorTests \
  -Dtests.method="testWordDocumentWithVisioSchema" \
  -Dtests.security.manager=true \
  -Dtests.locale=fr-NE \
  -Dtests.timezone=US/Central

REPRODUCE WITH: ./gradlew :plugins:ingest-attachment:test \
  -Dtests.seed=1E6696FD299DB332 \
  -Dtests.class=org.elasticsearch.ingest.attachment.AttachmentProcessorTests \
  -Dtests.method="testVisioIsExcluded" \
  -Dtests.security.manager=true \
  -Dtests.locale=fr-NE \
  -Dtests.timezone=US/Central

REPRODUCE WITH: ./gradlew :plugins:ingest-attachment:test \
  -Dtests.seed=1E6696FD299DB332 \
  -Dtests.class=org.elasticsearch.ingest.attachment.AttachmentProcessorTests \
  -Dtests.method="testWordDocument" \
  -Dtests.security.manager=true \
  -Dtests.locale=fr-NE \
  -Dtests.timezone=US/Central
```

The failures look like:
```
1> [2018-02-08T14:38:51,961][INFO ][o.e.i.a.TikaDocTests     ] [testFiles]: after test
  2> REPRODUCE WITH: ./gradlew :plugins:ingest-attachment:test -Dtests.seed=D3DABC16A6A59FDE -Dtests.class=org.elasticsearch.ingest.attachment.TikaDocTests -Dtests.method="testFiles" -Dtests.security.manager=true -Dtests.locale=uk-UA -Dtests.timezone=Asia/Tehran
FAILURE 5.01s | TikaDocTests.testFiles <<< FAILURES!
   > Throwable #1: java.lang.AssertionError
   >    at __randomizedtesting.SeedInfo.seed([D3DABC16A6A59FDE:BAC7D990F4786C5C]:0)
   >    at org.elasticsearch.ingest.attachment.TikaDocTests.assertParseable(TikaDocTests.java:66)
   >    at org.elasticsearch.ingest.attachment.TikaDocTests.testFiles(TikaDocTests.java:56)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
```

Which just seems the documents are not parsed at all. Also I see several warning in the beginning of the test run:
```
  2> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
  2> SLF4J: Defaulting to no-operation (NOP) logger implementation
  2> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
  2> лют. 08, 2018 2:38:49 ПП org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
  2> WARNING: JBIG2ImageReader not loaded. jbig2 files will be ignored
  2> See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
  2> for optional dependencies.
  2> TIFFImageWriter not loaded. tiff files will not be processed
  2> See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
  2> for optional dependencies.
  2> J2KImageReader not loaded. JPEG2000 files will not be processed.
  2> See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
  2> for optional dependencies.
  2> лют. 08, 2018 2:38:49 ПП org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
  2> WARNING: org.xerial's sqlite-jdbc is not loaded.
  2> Please provide the jar on your classpath to parse sqlite files.
  2> See tika-parsers/pom.xml for the correct version.
```

Instances of recent failures:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+oracle-java10-periodic/69/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+oracle-java10-periodic/68/console

**Comment by cbuescher** [comment]
Looks like the problem is hidden somewhere in  `TikaImpl#parse` which returns an empty result for the affected tests when run on jdk 10, while the results look okay on jdk 9. It probably makes sense to temporarily disable these tests on jdk 10 for now.

**Comment by tvernum** [comment]
Per https://github.com/elastic/elasticsearch/pull/28570#issuecomment-364330623, this seem to be due to a JDK change that adds a `getDeclaredMember` call inside `java.util.ZipFile`
