### ISSUE TITLE
[CI] SizeBlockingQueueTests.testQueueSize fails on 6.x

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#28579]
I am seeing this failure every once in a while:

```
Suite: org.elasticsearch.common.util.concurrent.SizeBlockingQueueTests
  1> [2018-02-08T18:01:44,333][INFO ][o.e.c.u.c.SizeBlockingQueueTests] [testQueueSize]: before test
  1> [2018-02-08T18:01:44,355][INFO ][o.e.c.u.c.SizeBlockingQueueTests] [testQueueSize]: after test
  2> REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=69113FDE6E332977 -Dtests.class=org.elasticsearch.common.util.concurrent.SizeBlockingQueueTests -Dtests.method="testQueueSize" -Dtests.security.manager=true -Dtests.jvms=3 -Dtests.locale=id-ID -Dtests.timezone=Africa/Conakry
FAILURE 0.04s J2 | SizeBlockingQueueTests.testQueueSize <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <20>
   >      but: was <0>
   > 	at __randomizedtesting.SeedInfo.seed([69113FDE6E332977:1884A5ABD4B7A214]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.common.util.concurrent.SizeBlockingQueueTests.testQueueSize(SizeBlockingQueueTests.java:91)
   > 	at java.lang.Thread.run(Thread.java:748)
  2> NOTE: leaving temporary files on disk at: /home/hinmanm/es/elasticsearch/server/build/testrun/test/J2/temp/org.elasticsearch.common.util.concurrent.SizeBlockingQueueTests_69113FDE6E332977-001
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=374, maxMBSortInHeap=7.113482659052134, sim=RandomSimilarity(queryNorm=true): {}, locale=id-ID, timezone=Africa/Conakry
  2> NOTE: Linux 4.14.16-300.fc27.x86_64 amd64/Oracle Corporation 1.8.0_151 (64-bit)/cpus=8,threads=1,free=330397240,total=532152320
```

When running *all* tests (I haven't been able to reproduce it running as a single test)

Related to #28557

**Comment by dakrone** [comment]
Here's one that just failed in our CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux/2025/console

**Comment by cbuescher** [comment]
I was just looking into this, I think I have a solution, will open a PR
