### ISSUE TITLE
[CI] OOM on DateDerivativeIT using Zing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#28578]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+zing/113/console

Several OOM Failures like this:
```
12:57:10   2> WARNING: Uncaught exception in thread: Thread[elasticsearch[node_sd2][clusterService#updateTask][T#1],5,TGRP-DateDerivativeIT]
12:57:10   2> java.lang.OutOfMemoryError: unable to create new native thread
12:57:10   2> 	at __randomizedtesting.SeedInfo.seed([97CB3E9C6F503D51]:0)
12:57:10   2> 	at java.lang.Thread.start0(Native Method)
12:57:10   2> 	at java.lang.Thread.start(Thread.java:717)
12:57:10   2> 	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
12:57:10   2> 	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025)
12:57:10   2> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12:57:10   2> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:57:10   2> 	at java.lang.Thread.run(Thread.java:748)
12:57:10   2> Feb 08, 2018 6:37:01 AM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
```

```
./gradlew :core:integTest -Dtests.seed=97CB3E9C6F503D51 -Dtests.class=org.elasticsearch.search.aggregations.pipeline.DateDerivativeIT -Dtests.method="testSingleValuedFieldNormalised_timeZone_CET_DstStart" -Dtests.security.manager=true -Dtests.locale=ro -Dtests.timezone=Canada/Saskatchewan
```

**Comment by colings86** [comment]
Possibly another instance of this but this time I can't see a specific test that is failing and I don't see an OOM: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+zing/116/console

**Comment by colings86** [comment]
Another instance of a JVM crash on zing: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+zing/115/console

**Comment by jasontedor** [comment]
We are disabling these builds.
