### ISSUE TITLE
Error when upgrading with x-pack : FileAlreadyExistsException: /usr/share/elasticsearch/bin/x-pack/croneval.bat

### ISSUE THREAD

**Issue by MarneusCalgarXP** [elastic/elasticsearch#28597]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.1 

```Version: 6.2.1, Build: 7299dc3/2018-02-07T19:34:26.990113Z, JVM: 1.8.0_161```

**Plugins installed**: [x-pack]

**JVM version** (`java -version`): OpenJDK 1.8.0 161 64bits

```
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system): 
 ```
Linux localhost.localdomain 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:

After uninstalling elasticsearch 6.1.3 with x-pack and reinstalling 6.2.1, a security error prevents new installation (file already exist error, see logs bellow)

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. ```wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.1.3.rpm```
 2. ```rpm -i elasticsearch-6.1.3.rpm```
 3. ```cd /usr/share/elasticsearch/```
 4. ```./bin/elasticsearch-plugin install x-pack```
 5. ```rpm -e elasticsearch-6.1.3```
 6. ```cd ~```
 7. ```wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.1.rpm```
 8. ```rpm -i elasticsearch-6.2.1.rpm```
 9. ```cd /usr/share/elasticsearch/```
 10. ```./bin/elasticsearch-plugin install x-pack```

**Provide logs (if relevant)**:

```
# ./bin/elasticsearch-plugin install x-pack
-> Downloading x-pack from elastic
[=================================================] 100%  
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission \\.\pipe\* read,write
* java.lang.RuntimePermission accessClassInPackage.com.sun.activation.registries
* java.lang.RuntimePermission getClassLoader
* java.lang.RuntimePermission setContextClassLoader
* java.lang.RuntimePermission setFactory
* java.net.SocketPermission * connect,accept,resolve
* java.security.SecurityPermission createPolicy.JavaPolicy
* java.security.SecurityPermission getPolicy
* java.security.SecurityPermission putProviderProperty.BC
* java.security.SecurityPermission setPolicy
* java.util.PropertyPermission * read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]y
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@        WARNING: plugin forks a native controller        @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
This plugin launches a native controller that is not subject to the Java
security manager nor to system call filters.

Continue with installation? [y/N]y
Exception in thread "main" java.nio.file.FileAlreadyExistsException: /usr/share/elasticsearch/bin/x-pack/croneval.bat
        at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:551)
        at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
        at java.nio.file.Files.copy(Files.java:1274)
        at org.elasticsearch.plugins.InstallPluginCommand.installBin(InstallPluginCommand.java:782)
        at org.elasticsearch.plugins.InstallPluginCommand.installPluginSupportFiles(InstallPluginCommand.java:733)
        at org.elasticsearch.plugins.InstallPluginCommand.installMetaPlugin(InstallPluginCommand.java:683)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:621)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:223)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)
```

**Comment by colings86** [comment]
The old version of the X-Pack plugin needs to be removed using `./bin/elasticsearch-plugin remove x-pack` before installing the new version of the plugin (between steps 9 and 10 in your recreation steps). Please see the following documentation for more information on the process of upgrading X-Pack:
https://www.elastic.co/guide/en/x-pack/6.2/xpack-upgrading.html
