### ISSUE TITLE
environment is not locked Caused by: java.nio.file.NoSuchFileException

### ISSUE THREAD

**Issue by dzyangxi** [elastic/elasticsearch#28620]
ElasticSearch 5.5.3

JVM version (java -version): Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

OS version (linux): Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-32-generic x86_64)

[2018-02-11T10:23:46,025][WARN ][o.e.c.s.ClusterService   ] [avatar] failed to notify ClusterStateListener
java.lang.IllegalStateException: environment is not locked
	at org.elasticsearch.env.NodeEnvironment.assertEnvIsLocked(NodeEnvironment.java:944) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.env.NodeEnvironment.availableIndexFolders(NodeEnvironment.java:820) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.gateway.MetaStateService.loadIndicesStates(MetaStateService.java:89) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.gateway.DanglingIndicesState.findNewDanglingIndices(DanglingIndicesState.java:131) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.gateway.DanglingIndicesState.findNewAndAddDanglingIndices(DanglingIndicesState.java:116) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.gateway.DanglingIndicesState.processDanglingIndices(DanglingIndicesState.java:81) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.gateway.DanglingIndicesState.clusterChanged(DanglingIndicesState.java:185) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.cluster.service.ClusterService.lambda$publishAndApplyChanges$7(ClusterService.java:777) ~[elasticsearch-5.5.3.jar:5.5.3]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) [?:1.8.0_151]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742) [?:1.8.0_151]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) [?:1.8.0_151]
	at org.elasticsearch.cluster.service.ClusterService.publishAndApplyChanges(ClusterService.java:774) [elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:587) [elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.run(ClusterService.java:263) [elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) [elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) [elasticsearch-5.5.3.jar:5.5.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.nio.file.NoSuchFileException: /home/user/elk/elasticsearch/data/nodes/0/node.lock
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144) ~[?:?]
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1737) ~[?:1.8.0_151]
	at org.apache.lucene.store.NativeFSLockFactory$NativeFSLock.ensureValid(NativeFSLockFactory.java:177) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]

**Comment by jbaiera** [comment]
Thanks for including the stack trace on this issue, but could you elaborate further on how you are reaching this error?

**Comment by rjernst** [comment]
@dzyangxi  Can you please add more detailed instructions on how to reproduce this?

**Comment by jmngpt** [comment]
Seeing that this issue didn't come to a resolution, I'm posting my experience with the same problem. 

System: single node running ES 5.6 on ubuntu server 16.04.5, multiple data paths, 4 vCPU 16GB RAM 8GB heap. 

I came across the same error message after I manually emptied the node's data directories. I can't recall if the elasticsearch service was running, but I think not; also, I had tried to delete the index via http, but the service didn't respond. After starting the elasticsearch service, `service elasticsearch status` reports "loaded / active" , but a GET to `/_nodes/stats` outputs the following message:

 ```
"_nodes" : {
    "total" : 1,
    "successful" : 0,
    "failed" : 1,
    "failures" : [
      {
        "type" : "failed_node_exception",
        "reason" : "Failed node [QuC1Bb85Tl-UMIVvPLTPEw]",
        "caused_by" : {
          "type" : "illegal_state_exception",
          "reason" : "environment is not locked",
          "caused_by" : {
            "type" : "no_such_file_exception",
            "reason" : "/mnt/esdata01/nodes/0/node.lock"
          }
        }
      }
    ]
  }
```

In the end, `service elasticsearch restart` made this (understandable) issue disappear. 

I'm guessing that between trying to delete the index and then just deleting the index's files (because the http api was not responding to `curl -XDELETE /server/index` ) while the cluster wasn't on green status, ES' internal state/metadata got "messed up".
