### ISSUE TITLE
Support Map entry key type other than String in Painless

### ISSUE THREAD

**Issue by cbismuth** [elastic/elasticsearch#28635]
**Describe the feature**: support `Map` entry key type other than `String` in Painless

**Elasticsearch version**: `6.1.1`

**Plugins installed**: []

**JVM version**: `1.8.0_151`

**OS version** (`uname -a` if on a Unix-like system): `Linux dmal-insels02 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:

When sharing a Map instance between nodes in Painless, keys have to be String instances. A better approach could be to support any type supported by the String#valueOf API.

**Steps to reproduce**:

 1. Setup a multi-nodes Elasticsearch instance
 2. Create a Painless script with a init phase with a `Map<Long, Long>` variable and a reduce phase to aggregate these values
 3. See error in log output file `Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: class_cast_exception: java.lang.Long cannot be cast to java.lang.String
`

It may be implement in the line shown below.

https://github.com/elastic/elasticsearch/blob/v6.2.1/server/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java#L571

**Provide logs (if relevant)**:

```
org.elasticsearch.transport.RemoteTransportException: [dmal-insels04][10.10.13.220:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: class_cast_exception: java.lang.Long cannot be cast to java.lang.String
	at org.elasticsearch.common.io.stream.StreamOutput.lambda$static$11(StreamOutput.java:571) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:662) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.common.io.stream.StreamOutput.lambda$static$11(StreamOutput.java:572) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:662) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.search.aggregations.metrics.scripted.InternalScriptedMetric.doWriteTo(InternalScriptedMetric.java:66) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.search.aggregations.InternalAggregation.writeTo(InternalAggregation.java:103) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:883) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteableList(StreamOutput.java:961) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.search.aggregations.InternalAggregations.writeTo(InternalAggregations.java:99) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.search.query.QuerySearchResult.writeToNoId(QuerySearchResult.java:334) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.search.query.QuerySearchResult.writeTo(QuerySearchResult.java:315) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.transport.TcpTransport.buildMessage(TcpTransport.java:1234) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.transport.TcpTransport.sendResponse(TcpTransport.java:1187) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.transport.TcpTransport.sendResponse(TcpTransport.java:1169) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.transport.TcpTransportChannel.sendResponse(TcpTransportChannel.java:62) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.transport.TcpTransportChannel.sendResponse(TcpTransportChannel.java:56) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:54) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.action.search.SearchTransportService$6$1.onResponse(SearchTransportService.java:380) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.action.search.SearchTransportService$6$1.onResponse(SearchTransportService.java:376) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:310) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:306) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:996) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.1.jar:6.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by rjernst** [comment]
This has nothing to do with painless. It is a result of how scripted aggs passes data across nodes. It needs to serialize the data, and any Map is serialized to a json object, which must have string keys.

/cc @colings86

**Comment by cbismuth** [comment]
Oh, yes... my bad, thank you @rjernst (y)
