### ISSUE TITLE
ES 6.1.1: receiving TransportShardMultiTermsVectorAction exception

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch#28642]
ES 6.1.1
NEST 6.0

In perusing my ES logs, I've noticed that I'm rather frequently seeing `TransportShardMultiTermsVectorAction` exceptions.  I'm not exactly sure what a **MultiTermsVector** even is.  Anyway, I'm trying to determine the exact request that's producing this but, in the meantime, I wanted to enter this issue since I expect it's beyond my control.  Here's an example from my log:
```
[2018-02-12T20:30:59,803][DEBUG][o.e.a.t.TransportShardMultiTermsVectorAction]
[ES-MYNODE1] [my_index][9] failed to execute multi term vectors for [my_type]/[3288128]
org.elasticsearch.ElasticsearchException: failed to execute term vector request
	at org.elasticsearch.index.termvectors.TermVectorsService.getTermVectors(TermVectorsService.java:150) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.index.termvectors.TermVectorsService.getTermVectors(TermVectorsService.java:77) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.action.termvectors.TransportShardMultiTermsVectorAction.shardOperation(TransportShardMultiTermsVectorAction.java:86) [elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.action.termvectors.TransportShardMultiTermsVectorAction.shardOperation(TransportShardMultiTermsVectorAction.java:42) [elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:294) [elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:287) [elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30) [elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:652) [elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) [elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.1.1.jar:6.1.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NullPointerException
	at org.elasticsearch.action.termvectors.TermVectorsWriter.setFields(TermVectorsWriter.java:82) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.action.termvectors.TermVectorsResponse.setFields(TermVectorsResponse.java:360) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.index.termvectors.TermVectorsService.getTermVectors(TermVectorsService.java:146) ~[elasticsearch-6.1.1.jar:6.1.1]
	... 13 more
```

**Comment by jbaiera** [comment]
Hi @tdoman - Since this is a NPE on a request I feel like it's worth investigating further. Could you include any other information about the clients accessing your cluster (Kibana, Logstash, etc..). It looks like specifically a client is executing a Multi Term Vectors request ([docs here](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/docs-multi-termvectors.html)), which pulls information about term fields from multiple documents and how they are tokenized.

**Comment by tdoman** [comment]
@jbaiera Thanks!  Sure, the only clients really hitting this system (an occasional kibana dev tools usage but not accessing this stuff) are via our Web App which uses NEST 6.0.  The errors seem to be sporadic and I have not been able to determine which requests cause it.  My best guess right now is that it is a periodically ephemeral issue cuz doing the same actions as reported by our QA, I can't dupe it and neither can they at this time.  When the exception is logged, it is always surrounding our "user content" indexes that are defined something like this:
```
PUT my_index_v1
{
  "settings": {
    "number_of_shards": 20
  },
  "mappings": {
    "my_type": {
      "dynamic": "strict",
```
within these, we have regular fields, nested fields, object fields, multi-fields, etc. but nothing I'd expect is too crazy.

**Comment by talevy** [comment]
Pinging @elastic/es-search-aggs

**Comment by talevy** [comment]
@tdoman this is interesting, indeed.

Would you mind sharing your full mapping

and an appropriately redacted source of your document `my_index_v1/my_type/3288128`

I am having trouble seeing how it is possible that we picked up this field as if it had a terms vector, but 
turned out not to.

**Comment by tdoman** [comment]
Yeah, I'd be willing to provide you a non-redacted version of our template, one of our mappings that's involved in this problem, and a sample source document if I can send it directly to your e-mail instead of including them here.  Meanwhile, let me give you some additional detail from what I'm seeing.  The indexes involved in this are always our "user" indexes (as opposed to other indexes) and have 20 shards each instead of the default 5.  Also, sometimes we'll search these indexes w/ a routing argument and sometimes not.

**Comment by tdoman** [comment]
@talevy Can I e-mail you the details?  We're seeing some intermittent problems that I wonder if they are related to this.  As I was mentioning, I'd be happy to provide unredacted files directly to you.

**Comment by tdoman** [comment]
@talevy @jbaiera anything I can do to move this investigation along and get you the information you need for this issue?  These `TransportShardMultiTermsVectorAction` severely clutter our logs and I'm not still sure of the impact but, as I've said, it only happens on our "user" indexes which have 20 shards each.  I did a little more research into `_termvectors` which looks like a pretty cool feature but alas, we do not use them in our application unless the C# .NET NEST library does something w/ them under the covers.  I tried some manual `_termvectors` and `mtermvectors` queries which worked just fine (ie. they returned results which looked fine, no exceptions).

**Comment by talevy** [comment]
hi @tdoman, apologies for letting this fall through the cracks for such a long time. How has your usage changed since this experience; are you still running into this issue?

**Comment by tdoman** [comment]
Thanks @talevy, I just reviewed my logs and I haven't seen that occur for over a month.  That is as mysterious as the source of the exception in the first place.  Perhaps a process we had accessing ES has changed but our version of ES hasn't.  For now, I'll go ahead and close this issue and reopen it if I discover it happening again.

**Comment by talevy** [comment]
glad to hear it hasn't been an issue for you! 👍
