### ISSUE TITLE
org.elasticsearch.index.store.CorruptedFileIT.testReplicaCorruption fails on 6.2 on windows

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#28689]
Build URL: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+multijob-windows-compatibility/102/console

Reproduce command (does not reproduce locally):
```
gradlew :server:integTest -Dtests.seed=61D4E20F8D5605B4 -Dtests.class=org.elasticsearch.index.store.CorruptedFileIT -Dtests.method="testReplicaCorruption" -Dtests.security.manager=true -Dtests.locale=et-EE -Dtests.timezone=Brazil/East
```

Failure output:
```
08:43:54   1> org.elasticsearch.indices.recovery.RecoveryFailedException: [test][0]: Recovery failed from {node_sd1}{jMzQ547AQtK1eI1DylRRKg}{vImfhP3OTz6oT5_UmkGF2w}{127.0.0.1}{127.0.0.1:57384} into {node_sd2}{FoLDzscZSWeK7uSKAA4zQA}{BlKZ2W1tQZ-7-gg_f63qMQ}{127.0.0.1}{127.0.0.1:57385}
08:43:54   1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.doRecovery(PeerRecoveryTargetService.java:287) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.access$900(PeerRecoveryTargetService.java:80) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$RecoveryRunner.doRun(PeerRecoveryTargetService.java:632) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:635) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[main/:?]
08:43:54   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_162]
08:43:54   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_162]
08:43:54   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
08:43:54   1> Caused by: org.elasticsearch.transport.RemoteTransportException: [node_sd1][127.0.0.1:57384][internal:index/shard/recovery/start_recovery]
08:43:54   1> Caused by: org.elasticsearch.index.engine.RecoveryEngineException: Phase[1] prepare target for translog failed
08:43:54   1> 	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:194) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.indices.recovery.PeerRecoverySourceService.recover(PeerRecoverySourceService.java:98) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.indices.recovery.PeerRecoverySourceService.access$000(PeerRecoverySourceService.java:50) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.indices.recovery.PeerRecoverySourceService$StartRecoveryTransportRequestHandler.messageReceived(PeerRecoverySourceService.java:107) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.indices.recovery.PeerRecoverySourceService$StartRecoveryTransportRequestHandler.messageReceived(PeerRecoverySourceService.java:104) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1555) ~[main/:?]
08:43:54   1> 	... 5 more
08:43:54   1> Caused by: org.elasticsearch.transport.RemoteTransportException: [node_sd2][127.0.0.1:57385][internal:index/shard/recovery/prepare_translog]
08:43:54   1> Caused by: org.elasticsearch.index.engine.EngineCreationFailureException: failed to create engine
08:43:54   1> 	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:206) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:152) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:2163) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:2145) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:1376) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.index.shard.IndexShard.openIndexAndSkipTranslogRecovery(IndexShard.java:1342) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.indices.recovery.RecoveryTarget.prepareForTranslogOperations(RecoveryTarget.java:371) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$PrepareForTranslogOperationsRequestHandler.messageReceived(PeerRecoveryTargetService.java:406) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$PrepareForTranslogOperationsRequestHandler.messageReceived(PeerRecoveryTargetService.java:400) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1555) ~[main/:?]
08:43:54   1> 	... 5 more
08:43:54   1> Caused by: org.elasticsearch.index.translog.TranslogCorruptedException: expected shard UUID [58 77 39 2d 4e 6e 41 76 54 44 32 79 7a 48 7a 54 63 6b 53 6a 64 41] but got: [6b 34 41 57 31 42 33 6f 52 74 6d 7a 45 62 4b 43 53 31 52 51 45 41] this translog file belongs to a different translog. path:C:\Users\jenkins\workspace\elastic+elasticsearch+6.2+multijob-windows-compatibility\server\build\testrun\integTest\J2\temp\org.elasticsearch.index.store.CorruptedFileIT_61D4E20F8D5605B4-001\tempDir-002\data\nodes\1\indices\ADl5rMV4S4aeixiedoV5ag\0\translog\translog-2.tlog
08:43:54   1> 	at org.elasticsearch.index.translog.TranslogReader.open(TranslogReader.java:131) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.index.translog.Translog.openReader(Translog.java:292) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:238) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.index.translog.Translog.<init>(Translog.java:176) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:523) ~[main/:?]
08:43:54   2> REPRODUCE WITH: gradlew :server:integTest -Dtests.seed=61D4E20F8D5605B4 -Dtests.class=org.elasticsearch.index.store.CorruptedFileIT -Dtests.method="testReplicaCorruption" -Dtests.security.manager=true -Dtests.locale=et-EE -Dtests.timezone=Brazil/East
08:43:54 
08:43:54   1> 	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:185) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:152) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:2163) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:2145) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:1376) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.index.shard.IndexShard.openIndexAndSkipTranslogRecovery(IndexShard.java:1342) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.indices.recovery.RecoveryTarget.prepareForTranslogOperations(RecoveryTarget.java:371) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$PrepareForTranslogOperationsRequestHandler.messageReceived(PeerRecoveryTargetService.java:406) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$PrepareForTranslogOperationsRequestHandler.messageReceived(PeerRecoveryTargetService.java:400) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[main/:?]
08:43:54   1> 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1555) ~[main/:?]
08:43:54   1> 	... 5 more
```

@dnhatn @ywelsch - @bleskes mentioned that this might be because recent relevant commits to fix this were only back-ported to 6.3 and might need to be back-ported to 6.2 as well?

**Comment by ywelsch** [comment]
I've backported #28604 to 6.2 branch now

**Comment by colings86** [comment]
Thanks @ywelsch
