### ISSUE TITLE
`UnicastZenPingTests.testSimplePings` failure

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#28685]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1247/consoleFull

```
20:15:03 FAILURE 4.03s J2 | UnicastZenPingTests.testSimplePings <<< FAILURES!
20:15:03    > Throwable #1: java.lang.AssertionError: node [UZP_D] ping count to [UZP_C] is unexpected
20:15:03    > Expected: <3>
20:15:03    >      but: was <2>
20:15:03    > 	at __randomizedtesting.SeedInfo.seed([B4A2932E8FCBE6DF:DF5E390A022617FF]:0)
20:15:03    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
20:15:03    > 	at org.elasticsearch.discovery.zen.UnicastZenPingTests.assertPingCount(UnicastZenPingTests.java:752)
20:15:03    > 	at org.elasticsearch.discovery.zen.UnicastZenPingTests.testSimplePings(UnicastZenPingTests.java:262)
20:15:03    > 	at java.lang.Thread.run(Thread.java:748)
```

```
REPRODUCE WITH: gradlew :server:test -Dtests.seed=B4A2932E8FCBE6DF -Dtests.class=org.elasticsearch.discovery.zen.UnicastZenPingTests -Dtests.method="testSimplePings" -Dtests.security.manager=true -Dtests.locale=ar-KW -Dtests.timezone=America/Cayman
```

I tried to reproduce 3 times without success.

cc @elastic/es-distributed 

[consoleText.txt](https://github.com/elastic/elasticsearch/files/1728427/consoleText.txt)

**Comment by bleskes** [comment]
@tlrx do you mind taking a look?

**Comment by cbuescher** [comment]
Another one:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+multijob-windows-compatibility/250/console

**Comment by DaveCTurner** [comment]
Another one: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+multijob-windows-compatibility/416

**Comment by jtibshirani** [comment]
This test failed again -- build information below.

CI link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/1050/console

Command to reproduce:
```
gradlew :server:test \
  -Dtests.seed=181102B7CE1F39F0 \
  -Dtests.class=org.elasticsearch.discovery.zen.UnicastZenPingTests \
  -Dtests.method="testSimplePings" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-VE \
  -Dtests.timezone=America/Blanc-Sablon
```

Stack trace:
```
FAILURE 2.92s J1 | UnicastZenPingTests.testSimplePings <<< FAILURES!
20:24:08    > Throwable #1: java.lang.AssertionError: node [UZP_A] ping count to [UZP_B] is unexpected
20:24:08    > Expected: <3>
20:24:08    >      but: was <2>
20:24:08    > 	at __randomizedtesting.SeedInfo.seed([181102B7CE1F39F0:73EDA89343F2C8D0]:0)
20:24:08    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
20:24:08    > 	at org.elasticsearch.discovery.zen.UnicastZenPingTests.assertPingCount(UnicastZenPingTests.java:752)
20:24:08    > 	at org.elasticsearch.discovery.zen.UnicastZenPingTests.testSimplePings(UnicastZenPingTests.java:235)
20:24:08    > 	at java.lang.Thread.run(Thread.java:748)```

**Comment by cbuescher** [comment]
This also appeared on 5.6 so I muted it there as well: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+multijob-windows-compatibility/1114/console
Muted in https://github.com/elastic/elasticsearch/commit/e521a9aa4e99bb20e0a3d264f23217ace3c18e23

**Comment by ywelsch** [comment]
The root cause here is:

```
[2018-05-29T03:03:50,295][WARN ][o.e.d.z.UnicastZenPingTests$1] [UZP_C] exception caught on transport layer [MockChannel{profile='default', isOpen=true, localAddress=/127.0.0.1:49968, isServerSocket=false}], closing connection

  1> java.net.SocketException: Software caused connection abort: recv failed
  1> 	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_172]
  1> 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_172]
  1> 	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_172]
  1> 	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_172]
  1> 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_172]
  1> 	at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[?:1.8.0_172]
  1> 	at org.elasticsearch.common.io.stream.InputStreamStreamInput.read(InputStreamStreamInput.java:84) ~[main/:?]
  1> 	at org.elasticsearch.transport.MockTcpTransport.readMessage(MockTcpTransport.java:151) ~[framework-5.6.10-SNAPSHOT.jar:?]
  1> 	at org.elasticsearch.transport.MockTcpTransport.access$900(MockTcpTransport.java:71) ~[framework-5.6.10-SNAPSHOT.jar:?]
  1> 	at org.elasticsearch.transport.MockTcpTransport$MockChannel$1.lambda$doRun$0(MockTcpTransport.java:347) ~[framework-5.6.10-SNAPSHOT.jar:?]
  1> 	at org.elasticsearch.common.util.CancellableThreads.executeIO(CancellableThreads.java:105) ~[main/:?]
  1> 	at org.elasticsearch.transport.MockTcpTransport$MockChannel$1.doRun(MockTcpTransport.java:347) [framework-5.6.10-SNAPSHOT.jar:?]
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```

It's only failing on Windows, and only sporadically. Googling for this shows all kind of possible causes, most of which cannot be influenced by the software that's experiencing the issues. Anyhow, asserting the exact ping count is not that important for the test, so I've weakened the assertion on Windows and reactivated the test (a9af5ca6387).

**Comment by jkakavas** [comment]
I'll reopen this as the same test fails - granted, not for the same reason. If deemed necessary, I can take this to a different issue
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1028

```
1> [2019-01-15T23:53:33,907][WARN ][o.e.d.z.UnicastZenPing   ] [UZP_A] [1] failed send ping to {127.0.0.1:57723}{pOGFpelDRRaotPaxo0uqaQ}{127.0.0.1}{127.0.0.1:57723}
  1> java.lang.IllegalStateException: handshake failed, mismatched cluster name [Cluster [mismatch]] - {127.0.0.1:57723}{pOGFpelDRRaotPaxo0uqaQ}{127.0.0.1}{127.0.0.1:57723}
  1> 	at org.elasticsearch.transport.TransportService.handshake(TransportService.java:422) ~[main/:?]
  1> 	at org.elasticsearch.transport.TransportService.handshake(TransportService.java:386) ~[main/:?]
  1> 	at org.elasticsearch.discovery.zen.UnicastZenPing$PingingRound.getOrConnect(UnicastZenPing.java:371) ~[main/:?]
  1> 	at org.elasticsearch.discovery.zen.UnicastZenPing$3.doRun(UnicastZenPing.java:476) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [main/:?]
  1> 	at org.elasticsearch.discovery.zen.UnicastZenPingTests$TestUnicastZenPing$1.doRun(UnicastZenPingTests.java:881) [test/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
```

**Comment by ywelsch** [comment]
@jkakavas grep for `AssertionError` in the output. That will give you the reason why the test failed. The above is just a random log line that will also happen on a healthy run of the test, as the test simulates failures.
I've looked at the failure here and it is caused by CI being very slow. Unless we rewrite all our tests to accommodate for horrible slow timing behavior as part of the CI, there is nothing we can do here, but need to investigate a test infrastructure problem.
