### ISSUE TITLE
ES Crash: 'Failed to close SearcherManager'

### ISSUE THREAD

**Issue by DropCloth** [elastic/elasticsearch#28687]
Hello !

**Description of the problem including expected versus actual behavior**:
I'm currently testing my ES cluster by simulating generic failures. I have 5 nodes, with the Elasticsearch replication enabled: 5 shards, the replication factor is 1. They are all data nodes, master is chosen automatically.

I manually shutdown a node to see how the cluster is reallocating the missing shards, and to see if the cluster could handle this kind of situation.
However, another node left the cluster 10 hours after the first one, but without any action from me.
The log file is very small to debug the problem (cf. the end of the post), and I don't find any related issue about it.
With this second node leaving the cluster, it went red which wasn't the expected result.

**Steps to reproduce**:

 1. Stop the Elasticsearch service on a node 
 2. Wait for failure

**OS version** : Ubuntu Server 16.04

**Elasticsearch version** : 5.6.4

**JVM version** : 1.8.0_131

**Plugins installed**: None

**Provide logs (if relevant)**:
[2018-02-15T01:04:41,065][WARN ][o.e.i.e.Engine           ] [my-server03] [fw_5][3] Failed to close SearcherManager
java.lang.NullPointerException: null
	at java.util.Collections$UnmodifiableCollection.size(Collections.java:1030) ~[?:1.8.0_131]
	at java.util.HashSet.<init>(HashSet.java:118) ~[?:1.8.0_131]
	at org.apache.lucene.index.SegmentCommitInfo.files(SegmentCommitInfo.java:220) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.index.SegmentInfos.files(SegmentInfos.java:792) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.index.IndexFileDeleter.decRef(IndexFileDeleter.java:649) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.index.IndexWriter.decRefDeleter(IndexWriter.java:5027) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.index.StandardDirectoryReader.doClose(StandardDirectoryReader.java:381) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.index.IndexReader.decRef(IndexReader.java:253) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.index.IndexReader.close(IndexReader.java:403) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.index.FilterDirectoryReader.doClose(FilterDirectoryReader.java:134) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.index.IndexReader.decRef(IndexReader.java:253) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.search.SearcherManager.decRef(SearcherManager.java:149) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.search.SearcherManager.decRef(SearcherManager.java:58) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.search.ReferenceManager.release(ReferenceManager.java:274) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.search.ReferenceManager.swapReference(ReferenceManager.java:62) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.search.ReferenceManager.close(ReferenceManager.java:146) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.util.IOUtils.close(IOUtils.java:89) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.util.IOUtils.close(IOUtils.java:76) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.elasticsearch.index.engine.InternalEngine.closeNoLock(InternalEngine.java:1330) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.index.engine.Engine.failEngine(Engine.java:805) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:915) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.index.shard.IndexShard.refresh(IndexShard.java:632) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.index.IndexService.maybeRefreshEngine(IndexService.java:690) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.index.IndexService.access$400(IndexService.java:92) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.index.IndexService$AsyncRefreshTask.runInternal(IndexService.java:832) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.index.IndexService$BaseAsyncTask.run(IndexService.java:743) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.6.4.jar:5.6.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[2018-02-15T01:04:41,129][WARN ][o.e.i.e.Engine           ] [my-server03] [fw_5][3] failed to rollback writer on close
java.lang.NullPointerException: null
	at org.apache.lucene.index.IndexFileDeleter.decRef(IndexFileDeleter.java:581) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.index.IndexFileDeleter.checkpoint(IndexFileDeleter.java:534) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.index.IndexWriter.rollbackInternalNoCommit(IndexWriter.java:2248) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.index.IndexWriter.rollbackInternal(IndexWriter.java:2193) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.apache.lucene.index.IndexWriter.rollback(IndexWriter.java:2186) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
	at org.elasticsearch.index.engine.InternalEngine.closeNoLock(InternalEngine.java:1342) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.index.engine.Engine.failEngine(Engine.java:805) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:915) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.index.shard.IndexShard.refresh(IndexShard.java:632) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.index.IndexService.maybeRefreshEngine(IndexService.java:690) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.index.IndexService.access$400(IndexService.java:92) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.index.IndexService$AsyncRefreshTask.runInternal(IndexService.java:832) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.index.IndexService$BaseAsyncTask.run(IndexService.java:743) [elasticsearch-5.6.4.jar:5.6.4]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [elasticsearch-5.6.4.jar:5.6.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by bleskes** [comment]
@jpountz this smells similar to https://github.com/elastic/elasticsearch/pull/28656 . Do you mind taking a look?

**Comment by s1monw** [comment]
@bleskes this sounds more like a JVM bug that we saw often with totally impossible NPEs. The places show in the stacktrace can't be `null` I checked both. I recommend upgrading to a newer JVM @jpountz feel free to close

**Comment by bleskes** [comment]
@s1monw thanks for reminding me. The NPE in the collection class is indeed crazy.

@DropCloth please upgrade your JVM. This should help.
