### ISSUE TITLE
ES_PATH_CONF on Windows not working

### ISSUE THREAD

**Issue by curdincaspar** [elastic/elasticsearch#28704]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.2.1

**Plugins installed**: []
None

**JVM version** (`java -version`):
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Windows 10 Enterprise (most recent version)

**Description of the problem including expected versus actual behavior**:
Having a system environment variable named ES_PATH_CONF with the value "C:\elasticsearch-config" and no config folder in the ES home directory results in not being able to start ES.

**Steps to reproduce**:

1. Copy the ES folder to C:\elasticsearch
2. Install the ES service
3. Move the config folder to C:\elasticsearch-config
4. Create a system env var "ES_PATH_CONF" with value "C:\elasticsearch-config"
3. Start the service

**Provide logs (if relevant)**:
2018-02-16 15:49:19 Commons Daemon procrun stderr initialized
Exception in thread "main" .BootstrapException: java.nio.file.NoSuchFileException: C:\elasticsearch\config
Likely root cause: java.nio.file.NoSuchFileException: C:\elasticsearch\config
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
	at java.nio.file.Files.readAttributes(Unknown Source)
	at java.nio.file.FileTreeWalker.getAttributes(Unknown Source)
	at java.nio.file.FileTreeWalker.visit(Unknown Source)
	at java.nio.file.FileTreeWalker.walk(Unknown Source)
	at java.nio.file.Files.walkFileTree(Unknown Source)
	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:147)
	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:119)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:291)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85)
Refer to the log for complete error details.

**Comment by jasontedor** [comment]
`ES_PATH_CONF` is only respected when the service is installed. Once the service is installed, execution of Elasticsearch is taken away from the startup scripts. The [docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/zip-windows.html) say this:

> The Elasticsearch service can be configured prior to installation by setting the following environment variables[...]
> .
> .
> .
> `ES_PATH_CONF`::
