### ISSUE TITLE
ConfigSyncService] [node01] Failed to start ConfigFileUpdater. org.elasticsearch.ElasticsearchSecurityException: action [indices:admin/exists] is unauthorized for user [_system] with x-pack

### ISSUE THREAD

**Issue by acossette1979** [elastic/elasticsearch#28735]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.1.0
**Plugins installed**: []
node01 analysis-fess     6.1.0
node01 analysis-ja       6.1.0
node01 analysis-synonym  6.1.0
node01 configsync        6.1.0
node01 dataformat        6.1.0
node01 ingest-geoip      6.1.0
node01 ingest-user-agent 6.1.0
node01 langfield         6.1.0
node01 minhash           6.1.0
node01 x-pack            6.1.0

**JVM version** (`java -version`):
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux 2be743d835de 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 13 10:46:25 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
When loading x-pack, the configsync plugin failed action [indices:admin/exists] is unauthorized for user [_system]

**Steps to reproduce**:
FROM docker.elastic.co/elasticsearch/elasticsearch:6.1.0
Install plugin.
Start ES.
(same image work if removing x-pack)

**Provide logs (if relevant)**:
[2018-02-19T20:19:32,638][INFO ][o.e.p.PluginsService     ] [node01] loaded module [aggs-matrix-stats]
[2018-02-19T20:19:32,639][INFO ][o.e.p.PluginsService     ] [node01] loaded module [analysis-common]
[2018-02-19T20:19:32,639][INFO ][o.e.p.PluginsService     ] [node01] loaded module [ingest-common]
[2018-02-19T20:19:32,639][INFO ][o.e.p.PluginsService     ] [node01] loaded module [lang-expression]
[2018-02-19T20:19:32,639][INFO ][o.e.p.PluginsService     ] [node01] loaded module [lang-mustache]
[2018-02-19T20:19:32,639][INFO ][o.e.p.PluginsService     ] [node01] loaded module [lang-painless]
[2018-02-19T20:19:32,639][INFO ][o.e.p.PluginsService     ] [node01] loaded module [mapper-extras]
[2018-02-19T20:19:32,639][INFO ][o.e.p.PluginsService     ] [node01] loaded module [parent-join]
[2018-02-19T20:19:32,639][INFO ][o.e.p.PluginsService     ] [node01] loaded module [percolator]
[2018-02-19T20:19:32,639][INFO ][o.e.p.PluginsService     ] [node01] loaded module [reindex]
[2018-02-19T20:19:32,639][INFO ][o.e.p.PluginsService     ] [node01] loaded module [repository-url]
[2018-02-19T20:19:32,639][INFO ][o.e.p.PluginsService     ] [node01] loaded module [transport-netty4]
[2018-02-19T20:19:32,639][INFO ][o.e.p.PluginsService     ] [node01] loaded module [tribe]
[2018-02-19T20:19:32,640][INFO ][o.e.p.PluginsService     ] [node01] loaded plugin [analysis-fess]
[2018-02-19T20:19:32,640][INFO ][o.e.p.PluginsService     ] [node01] loaded plugin [analysis-ja]
[2018-02-19T20:19:32,640][INFO ][o.e.p.PluginsService     ] [node01] loaded plugin [analysis-synonym]
[2018-02-19T20:19:32,640][INFO ][o.e.p.PluginsService     ] [node01] loaded plugin [configsync]
[2018-02-19T20:19:32,640][INFO ][o.e.p.PluginsService     ] [node01] loaded plugin [dataformat]
[2018-02-19T20:19:32,640][INFO ][o.e.p.PluginsService     ] [node01] loaded plugin [ingest-geoip]
[2018-02-19T20:19:32,640][INFO ][o.e.p.PluginsService     ] [node01] loaded plugin [ingest-user-agent]
[2018-02-19T20:19:32,640][INFO ][o.e.p.PluginsService     ] [node01] loaded plugin [langfield]
[2018-02-19T20:19:32,640][INFO ][o.e.p.PluginsService     ] [node01] loaded plugin [minhash]
[2018-02-19T20:19:32,640][INFO ][o.e.p.PluginsService     ] [node01] loaded plugin [x-pack]
[2018-02-19T20:19:35,081][INFO ][o.e.x.m.j.p.l.CppLogMessageHandler] [controller/120] [Main.cc@128] controller (64 bit): Version 6.1.0 (Build f3e883f11f2d23) Copyright (c) 2017 Elasticsearch BV
[2018-02-19T20:19:35,417][INFO ][o.e.d.DiscoveryModule    ] [node01] using discovery type [zen]
[2018-02-19T20:19:36,033][INFO ][o.e.n.Node               ] [node01] initialized
[2018-02-19T20:19:36,034][INFO ][o.e.n.Node               ] [node01] starting ...
[2018-02-19T20:19:36,217][INFO ][o.e.t.TransportService   ] [node01] publish_address {172.17.0.2:9300}, bound_addresses {[::]:9300}
[2018-02-19T20:19:36,230][INFO ][o.e.b.BootstrapChecks    ] [node01] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2018-02-19T20:19:39,299][INFO ][o.e.c.s.MasterService    ] [node01] zen-disco-elected-as-master ([0] nodes joined), reason: new_master {node01}{in4BvtX7RyG3WFvmfwwjvQ}{nqe84wLnSkq8wFHIuL7sWQ}{172.17.0.2}{172.17.0.2:9300}{ml.machine_memory=67388583936, ml.max_open_jobs=20, ml.enabled=true}
[2018-02-19T20:19:39,304][INFO ][o.e.c.s.ClusterApplierService] [node01] new_master {node01}{in4BvtX7RyG3WFvmfwwjvQ}{nqe84wLnSkq8wFHIuL7sWQ}{172.17.0.2}{172.17.0.2:9300}{ml.machine_memory=67388583936, ml.max_open_jobs=20, ml.enabled=true}, reason: apply cluster state (from master [master {node01}{in4BvtX7RyG3WFvmfwwjvQ}{nqe84wLnSkq8wFHIuL7sWQ}{172.17.0.2}{172.17.0.2:9300}{ml.machine_memory=67388583936, ml.max_open_jobs=20, ml.enabled=true} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)]])
[2018-02-19T20:19:39,320][INFO ][o.e.x.s.t.n.SecurityNetty4HttpServerTransport] [node01] publish_address {172.17.0.2:9200}, bound_addresses {[::]:9200}
[2018-02-19T20:19:39,321][INFO ][o.e.n.Node               ] [node01] started
[2018-02-19T20:19:39,374][

ERROR][o.c.e.c.s.ConfigSyncService] [node01] Failed to start ConfigFileUpdater.

org.elasticsearch.ElasticsearchSecurityException: action [indices:admin/exists] is unauthorized for user [_system]
	at org.elasticsearch.xpack.security.support.Exceptions.authorizationError(Exceptions.java:42) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationService.denialException(AuthorizationService.java:589) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationService.denial(AuthorizationService.java:560) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:168) ~[?:?]
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$authorizeRequest$4(SecurityActionFilter.java:178) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.maybeRun(AuthorizationUtils.java:182) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.setRunAsRoles(AuthorizationUtils.java:176) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.authorize(AuthorizationUtils.java:158) ~[?:?]
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.authorizeRequest(SecurityActionFilter.java:192) ~[?:?]
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$3(SecurityActionFilter.java:168) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$writeAuthToContext$23(AuthenticationService.java:453) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.writeAuthToContext(AuthenticationService.java:462) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$handleNullToken$16(AuthenticationService.java:355) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.handleNullToken(AuthenticationService.java:362) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.consumeToken(AuthenticationService.java:277) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$extractToken$7(AuthenticationService.java:249) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.extractToken(AuthenticationService.java:266) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$null$0(AuthenticationService.java:201) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.xpack.security.authc.TokenService.getAndValidateToken(TokenService.java:239) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$2(AuthenticationService.java:197) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$4(AuthenticationService.java:228) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:239) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:193) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:147) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:116) ~[?:?]
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.applyInternal(SecurityActionFilter.java:167) ~[?:?]
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.apply(SecurityActionFilter.java:126) ~[?:?]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:139) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:81) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:405) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1253) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:71) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.codelibs.elasticsearch.configsync.service.ConfigSyncService.checkIfIndexExists(ConfigSyncService.java:226) ~[?:?]
	at org.codelibs.elasticsearch.configsync.service.ConfigSyncService.access$300(ConfigSyncService.java:79) ~[?:?]
	at org.codelibs.elasticsearch.configsync.service.ConfigSyncService$1.lambda$afterStart$2(ConfigSyncService.java:209) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:85) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:81) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.onResponse(TransportMasterNodeAction.java:150) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.onResponse(TransportMasterNodeAction.java:147) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.action.admin.cluster.health.TransportClusterHealthAction$3.onNewClusterState(TransportClusterHealthAction.java:175) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onNewClusterState(ClusterStateObserver.java:303) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.clusterChanged(ClusterStateObserver.java:191) ~[elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateListeners$7(ClusterApplierService.java:506) ~[elasticsearch-6.1.0.jar:6.1.0]
	at java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3527) [?:1.8.0_151]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743) [?:1.8.0_151]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) [?:1.8.0_151]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:503) [elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:486) [elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:429) [elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:158) [elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:568) [elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) [elasticsearch-6.1.0.jar:6.1.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) [elasticsearch-6.1.0.jar:6.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[2018-02-19T20:19:39,388][INFO ][o.e.g.GatewayService     ] [node01] recovered [0] indices into cluster_state

**Comment by jasontedor** [comment]
I am sorry to tell you that we do not support X-Pack on this repository, it’s for open source Elasticsearch only. Additionally we do not support the Config Sync plugin. Please use the [forum](https://discuss.elastic.co) and contact the plugin author.
