### ISSUE TITLE
CreateIndexRequest doesn't work

### ISSUE THREAD

**Issue by vbeskrovnov** [elastic/elasticsearch#28761]
Bug report 
------------

**Elasticsearch version** (`bin/elasticsearch --version`): "6.2.0"

**Plugins installed**: []

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Java API version**: `org.elasticsearch.client:elasticsearch-rest-high-level-client:6.2.2`

**Description of the problem including expected versus actual behavior**:
Index creating with `RestHighLevelClient` and `CreateIndexRequest` failed with the following stacktrace
```
java.lang.IncompatibleClassChangeError: Class org.elasticsearch.action.admin.indices.create.CreateIndexRequest does not implement the requested interface org.elasticsearch.common.xcontent.ToXContent

	at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:416)
	at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:405)
	at org.elasticsearch.client.Request.createEntity(Request.java:450)
	at org.elasticsearch.client.Request.createIndex(Request.java:178)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:485)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:474)
	at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:77)
...
```

**Steps to reproduce**:

 1. Create instance of `RestHighLevelClient`
 2. Create `CreateIndexRequest`
 3. Execute `client.indices().create(createIndexRequest);`
Code example:
```
    RestHighLevelClient client = new RestHighLevelClient(RestClient
        .builder(new HttpHost("localhost", 9200)));
    CreateIndexRequest createIndexRequest = new CreateIndexRequest(TEST_ITEM_INDEX_NAME);
    String source =
          "{\n"
        + "  \"properties\": {\n"
        + "    \"email\": {\n"
        + "      \"type\": \"keyword\"\n"
        + "    }\n"
        + "  }\n"
        + "}";
    createIndexRequest.mapping("item", source, XContentType.JSON);

    client.indices().create(createIndexRequest);
```

**Provide logs (if relevant)**:

```
java.lang.IncompatibleClassChangeError: Class org.elasticsearch.action.admin.indices.create.CreateIndexRequest does not implement the requested interface org.elasticsearch.common.xcontent.ToXContent

	at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:416)
	at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:405)
	at org.elasticsearch.client.Request.createEntity(Request.java:450)
	at org.elasticsearch.client.Request.createIndex(Request.java:178)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:485)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:474)
	at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:77)
...
```

**Additional info**:
`org.elasticsearch.client.Request#createEntity` use `ToXContent` as first parameter's type, but in `org.elasticsearch.client.Request#createIndex:178` we pass `CreateIndexRequest` in `org.elasticsearch.client.Request#createEntity` as first parameter. But `CreateIndexRequest` doesn't implement `ToXContent`. maybe this is root cause of the problem.
And also  `client.indices().createAsync()` works as expected.

Thank you!

**Comment by javanna** [comment]
hi @vbeskrovnov is it possible that you have two different Elasticsearch jars in your classpath from different versions? `CreateIndexRequest` in the 6.2 branch does implement `ToXContent`, in fact if it didn't our own code wouldn't even compile.

**Comment by vbeskrovnov** [comment]
Hi, @javanna , thank you for response! Yes, you are right, sorry for wasting your time!
