### ISSUE TITLE
Exception when index is empty and I try to search/sort

### ISSUE THREAD

**Issue by ptahchiev** [elastic/elasticsearch#28811]
Hello,
I'm using elasticsearch 5.6.7. When my index is empty and I try to perform a search I get the following exception:
```
2017-11-24 12:00:10,489 org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/storefront].[dispatcherServlet] [https-jsse-nio-127.0.0.1-8112-exec-10] ERROR: Servlet.service() for servlet [dispatcherServlet] in context with path [/storefront] threw exception [Request processing failed; nested exception is Failed to execute phase [dfs], all shards failed; shardFailures {[JNL-DkvbTx6qGJnoMLHA8Q][products][0]: RemoteTransportException[[JNL-Dkv][local[1]][indices:data/read/search[phase/dfs]]]; nested: QueryShardException[No mapping found for [id] in order to sort on]; }{[JNL-DkvbTx6qGJnoMLHA8Q][products][1]: RemoteTransportException[[JNL-Dkv][local[1]][indices:data/read/search[phase/dfs]]]; nested: QueryShardException[No mapping found for [id] in order to sort on]; }{[JNL-DkvbTx6qGJnoMLHA8Q][products][2]: RemoteTransportException[[JNL-Dkv][local[1]][indices:data/read/search[phase/dfs]]]; nested: QueryShardException[No mapping found for [id] in order to sort on]; }{[JNL-DkvbTx6qGJnoMLHA8Q][products][3]: RemoteTransportException[[JNL-Dkv][local[1]][indices:data/read/search[phase/dfs]]]; nested: QueryShardException[No mapping found for [id] in order to sort on]; }{[JNL-DkvbTx6qGJnoMLHA8Q][products][4]: RemoteTransportException[[JNL-Dkv][local[1]][indices:data/read/search[phase/dfs]]]; nested: QueryShardException[No mapping found for [id] in order to sort on]; }] with root cause
[products/z_MQYeznRiCLS39mKX6Etg] QueryShardException[No mapping found for [id] in order to sort on]
	at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:262)
	at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:156)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:630)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:481)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:457)
	at org.elasticsearch.search.SearchService.executeDfsPhase(SearchService.java:222)
	at org.elasticsearch.action.search.SearchTransportService$5.messageReceived(SearchTransportService.java:319)
	at org.elasticsearch.action.search.SearchTransportService$5.messageReceived(SearchTransportService.java:316)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:644)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-11-24 12:00:10,500 com.samplestore.storefront.controller.misc.SamplestoreErrorController [https-jsse-nio-127.0.0.1-8112-exec-10] ERROR: [timestamp=Fri Nov 24 12:00:10 EET 2017, status=500, error=Internal Server Error, message=all shards failed, path=/storefront/en/GB/Women%27s/c/womens]

```
Java version is 1.8
OS is Ubuntu Linux 16.04
No elasticsearch plugins installed.

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by jasontedor** [comment]
There is no bug here, you do not have an `id` field defined in your mapping. You can not sort on a field that does not exist, this has nothing do with whether or not the index is empty.
