### ISSUE TITLE
OutOfMemoryError occured in master node due to cardinality aggregation

### ISSUE THREAD

**Issue by wyukawa** [elastic/elasticsearch#28832]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
6.1.2

**Plugins installed**: []
x-pack monitoring

**JVM version** (`java -version`):
1.8.0_151

**OS version** (`uname -a` if on a Unix-like system):
CentOS 7.4
```
# uname -a
Linux ... 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:
OutOfMemoryError occured in master/kibana node due to cardinality aggregation.
We have 3 master nodes.

Java heap of master node is 4GB.
After this issue, I increase java heap to 12GB.

**Steps to reproduce**:

I'm sorry not to reproduce...

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

elasticsearch log
```
[2018-02-21T22:24:58,264][ERROR][o.e.t.n.Netty4Utils      ] fatal error on the network layer
        at org.elasticsearch.transport.netty4.Netty4Utils.maybeDie(Netty4Utils.java:185)
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.exceptionCaught(Netty4MessageChannelHandler.java:73)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
        at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:850)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:364)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:748)
[2018-02-21T22:24:58,264][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [...] fatal error in thread [Thread-19], exiting
java.lang.OutOfMemoryError: Java heap space
```

I analyze heap dump with MAT.

Here is the result.

![](https://gyazo.com/86bcdb2a146a93367665554df8d6e18d.png)

```
  at org.elasticsearch.common.util.BigArrays.newIntArray(JZ)Lorg/elasticsearch/common/util/IntArray; (BigArrays.java:564)
  at org.elasticsearch.common.util.BigArrays.newIntArray(J)Lorg/elasticsearch/common/util/IntArray; (BigArrays.java:573)
  at org.elasticsearch.search.aggregations.metrics.cardinality.HyperLogLogPlusPlus$Hashset.values(J)Lorg/elasticsearch/common/util/IntArray; (HyperLogLogPlusPlus.java:540)
  at org.elasticsearch.search.aggregations.metrics.cardinality.HyperLogLogPlusPlus.merge(JLorg/elasticsearch/search/aggregations/metrics/cardinality/HyperLogLogPlusPlus;J)V (HyperLogLogPlusPlus.java:211)
  at org.elasticsearch.search.aggregations.metrics.cardinality.InternalCardinality.merge(Lorg/elasticsearch/search/aggregations/metrics/cardinality/InternalCardinality;)V (InternalCardinality.java:106)
  at org.elasticsearch.search.aggregations.metrics.cardinality.InternalCardinality.doReduce(Ljava/util/List;Lorg/elasticsearch/search/aggregations/InternalAggregation$ReduceContext;)Lorg/elasticsearch/search/aggregations/InternalAggregation; (InternalCardinality.java:93)
  at org.elasticsearch.search.aggregations.InternalAggregation.reduce(Ljava/util/List;Lorg/elasticsearch/search/aggregations/InternalAggregation$ReduceContext;)Lorg/elasticsearch/search/aggregations/InternalAggregation; (InternalAggregation.java:120)
  at org.elasticsearch.search.aggregations.InternalAggregations.reduce(Ljava/util/List;Lorg/elasticsearch/search/aggregations/InternalAggregation$ReduceContext;)Lorg/elasticsearch/search/aggregations/InternalAggregations; (InternalAggregations.java:77)
  at org.elasticsearch.search.aggregations.bucket.histogram.InternalDateHistogram$Bucket.reduce(Ljava/util/List;Lorg/elasticsearch/search/aggregations/InternalAggregation$ReduceContext;)Lorg/elasticsearch/search/aggregations/bucket/histogram/InternalDateHistogram$Bucket; (InternalDateHistogram.java:135)
  at org.elasticsearch.search.aggregations.bucket.histogram.InternalDateHistogram.reduceBuckets(Ljava/util/List;Lorg/elasticsearch/search/aggregations/InternalAggregation$ReduceContext;)Ljava/util/List; (InternalDateHistogram.java:345)
  at org.elasticsearch.search.aggregations.bucket.histogram.InternalDateHistogram.doReduce(Ljava/util/List;Lorg/elasticsearch/search/aggregations/InternalAggregation$ReduceContext;)Lorg/elasticsearch/search/aggregations/InternalAggregation; (InternalDateHistogram.java:436)
  at org.elasticsearch.search.aggregations.InternalAggregation.reduce(Ljava/util/List;Lorg/elasticsearch/search/aggregations/InternalAggregation$ReduceContext;)Lorg/elasticsearch/search/aggregations/InternalAggregation; (InternalAggregation.java:120)
  at org.elasticsearch.search.aggregations.InternalAggregations.reduce(Ljava/util/List;Lorg/elasticsearch/search/aggregations/InternalAggregation$ReduceContext;)Lorg/elasticsearch/search/aggregations/InternalAggregations; (InternalAggregations.java:77)
  at org.elasticsearch.search.aggregations.bucket.terms.InternalTerms$Bucket.reduce(Ljava/util/List;Lorg/elasticsearch/search/aggregations/InternalAggregation$ReduceContext;)Lorg/elasticsearch/search/aggregations/bucket/terms/InternalTerms$Bucket; (InternalTerms.java:142)
  at org.elasticsearch.search.aggregations.bucket.terms.InternalTerms.doReduce(Ljava/util/List;Lorg/elasticsearch/search/aggregations/InternalAggregation$ReduceContext;)Lorg/elasticsearch/search/aggregations/InternalAggregation; (InternalTerms.java:286)
  at org.elasticsearch.search.aggregations.InternalAggregation.reduce(Ljava/util/List;Lorg/elasticsearch/search/aggregations/InternalAggregation$ReduceContext;)Lorg/elasticsearch/search/aggregations/InternalAggregation; (InternalAggregation.java:120)
  at org.elasticsearch.search.aggregations.InternalAggregations.reduce(Ljava/util/List;Lorg/elasticsearch/search/aggregations/InternalAggregation$ReduceContext;)Lorg/elasticsearch/search/aggregations/InternalAggregations; (InternalAggregations.java:77)
  at org.elasticsearch.action.search.SearchPhaseController.reduceAggs(Ljava/util/List;Ljava/util/List;Lorg/elasticsearch/search/aggregations/InternalAggregation$ReduceContext;)Lorg/elasticsearch/search/aggregations/InternalAggregations; (SearchPhaseController.java:523)
  at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(Ljava/util/Collection;Ljava/util/List;Ljava/util/List;Lorg/elasticsearch/action/search/SearchPhaseController$TopDocsStats;IZ)Lorg/elasticsearch/action/search/SearchPhaseController$ReducedQueryPhase; (SearchPhaseController.java:500)
  at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(Ljava/util/Collection;ZZ)Lorg/elasticsearch/action/search/SearchPhaseController$ReducedQueryPhase; (SearchPhaseController.java:417)
  at org.elasticsearch.action.search.SearchPhaseController$1.reduce()Lorg/elasticsearch/action/search/SearchPhaseController$ReducedQueryPhase; (SearchPhaseController.java:736)
  at org.elasticsearch.action.search.FetchSearchPhase.innerRun()V (FetchSearchPhase.java:102)
  at org.elasticsearch.action.search.FetchSearchPhase.access$000(Lorg/elasticsearch/action/search/FetchSearchPhase;)V (FetchSearchPhase.java:45)
  at org.elasticsearch.action.search.FetchSearchPhase$1.doRun()V (FetchSearchPhase.java:87)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun()V (ThreadContext.java:637)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run()V (AbstractRunnable.java:37)
  at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun()V (TimedRunnable.java:41)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run()V (AbstractRunnable.java:37)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run()V (ThreadPoolExecutor.java:624)
  at java.lang.Thread.run()V (Thread.java:748)
```

I guess cardinality aggregation is related to this issue.
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html

If it's possible to specify default precision_threshold value in kibana, it seems to be good.
But I couldn't https://github.com/elastic/kibana/issues/6859

**Comment by tlrx** [comment]
This looks similar to #26525

/cc @elastic/es-search-aggs

**Comment by colings86** [comment]
Closing in favour of #26525
