### ISSUE TITLE
Refine plugin-descriptor.properties searching logic in PluginService.java

### ISSUE THREAD

**Issue by dingminyi** [elastic/elasticsearch#28848]
Hi Team,
We are uploading our Elasticsearch clusters from old Elasticsearch versions, but we found such error while deploying the new version ES with puppet module:
```
[2018-02-28T00:03:32,066][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [pronto-pre-g2-hm8h-phx02-1516805102-3-2055140-pronto] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: org.elasticsearch.bootstrap.BootstrapException: java.nio.file.FileSystemException: /usr/share/elasticsearch/plugins/x-pack/.name/plugin-descriptor.properties: Not a directory
    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.2.2.jar:6.2.2]
    at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.2.2.jar:6.2.2]
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.2.2.jar:6.2.2]
Caused by: java.nio.file.FileSystemException: /usr/share/elasticsearch/plugins/x-pack/.name/plugin-descriptor.properties: Not a directory
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[?:1.8.0_151]
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_151]
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_151]
    at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_151]
    at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_151]
    at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_151]
    at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_151]
    at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_151]
    at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:202) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:184) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:75) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:167) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.2.jar:6.2.2]
    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.2.jar:6.2.2]
    ... 6 more
```
After investigate the code, we found that now Elasticsearch will take every file and folder under the meta plugin folder as folders. 
https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/plugins/PluginsService.java#L355
```
    private static Tuple<List<Path>, Map<String, List<Path>>> findGroupedPluginDirs(final Path rootPath) throws IOException {
        final List<Path> plugins = new ArrayList<>();
        final Map<String, List<Path>> metaPlugins = new LinkedHashMap<>();
        final Set<String> seen = new HashSet<>();
        if (Files.exists(rootPath)) {
            try (DirectoryStream<Path> stream = Files.newDirectoryStream(rootPath)) {
                for (Path plugin : stream) {
                    if (FileSystemUtils.isDesktopServicesStore(plugin) ||
                            plugin.getFileName().toString().startsWith(".removing-")) {
                        continue;
                    }
                    if (seen.add(plugin.getFileName().toString()) == false) {
                        throw new IllegalStateException("duplicate plugin: " + plugin);
                    }
                    if (MetaPluginInfo.isMetaPlugin(plugin)) {
                        final String name = plugin.getFileName().toString();
                        try (DirectoryStream<Path> subStream = Files.newDirectoryStream(plugin)) {
                            for (Path subPlugin : subStream) {
                                if (MetaPluginInfo.isPropertiesFile(subPlugin) ||
                                        FileSystemUtils.isDesktopServicesStore(subPlugin)) {
                                    continue;
                                }
                                if (seen.add(subPlugin.getFileName().toString()) == false) {
                                    throw new IllegalStateException("duplicate plugin: " + subPlugin);
                                }
                                metaPlugins.computeIfAbsent(name, n -> new ArrayList<>()).add(subPlugin);
                            }
                        }
                    } else {
                        plugins.add(plugin);
                    }
                }
            }
        }
        return Tuple.tuple(plugins, metaPlugins);
    }
```
I guess a directory filter for the Files.newDirectoryStream will make the logic more compatible to different cloud orchestration solutions and it will not break the origin purpose of code, what do you think? 

PS. We know that the plugin provider in puppet module has just updated its logic 15 days ago, but rollout puppet module will impact hundreds of nodes, dozens of clusters in our production environment. That will take huge human efforts to rollout and monitoring.

**Comment by jasontedor** [comment]
FYI @elastic/es-core-infra.

**Comment by jasontedor** [comment]
This was caused by some management that the puppet module use to do for installed plugins. However, a change has been made to the puppet module so that this management is no longer necessary and these files will not be placed in plugin directories any longer. I know that you're aware that a new version of the puppet module incorporating this change has been released. We think that users should upgrade to that, and we will not treat this as an issue in Elasticsearch.
