### ISSUE TITLE
Issues running three node cluster

### ISSUE THREAD

**Issue by dmaulick** [elastic/elasticsearch#28844]
- Elasticsearch version: (6.2.1)
- OS: Unix

I am attempting to start a 3 node cluster 
I have two issues/questions in regards to my configuration.

1) 
 This is my first configuration in the elasticsearch.yml file

node.name: 127x16
path.logs: //home/dmaul/569/machines/16/logs
path.data: //home/dmaul/569/machines/16/data
network.host: 129.65.221.26
discovery.zen.ping.uincast.hosts: ["127x16", "127x17", "127x18"]

The other nodes are named 127x17 and  127x18. 
(I realize I will want to have the discovery.zen.minimum_master_nodes to avoid split brain, however at this point I am just trying to get a running cluster and not too worried about efficiency)

With the above configuration, I receive the first stack trace labelled "STACK 1 of 2" below. According to the Elasticsearch documentation my syntax: "discovery.zen.ping.uincast.hosts: ["127x16", "127x17", "127x18"]" should work. However, the bootstrap seems to not accept that line.

2) 
My secondary question is in regards to my configuration when I remove discovery.zen.ping.uincast.hosts: ["127x16", "127x17", "127x18"].
So now in elasticsearch.yml file:

node.name: 127x16
path.logs: //home/dmaul/569/machines/16/logs
path.data: //home/dmaul/569/machines/16/data
network.host: 129.65.221.26

Again with the other nodes named 127x17 and 127x18. 

I receive a different Stack trace, labeled "STACK 2 of 2" below.
According to the documentation, to address the two listed bootstrap issues I must update admin config files in the following way:

To address [1] (increasing max file descriptors):
I added this line to my /etc/security/limits.conf: 
elasticsearch - nofile 70000

To address [2] (increase virtual memory):
I added this line to my /etc/sysctl.conf:
vm.max_mao_count=262144

But even with both of those files changed I still get this issue.

//STACK 1 of 2**************************************************

[2018-02-27T14:40:04,700][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [127x16] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [discovery.zen.ping.uincast.hosts] please check that any required plugins are installed, or check the   breaking changes documentation for removed settings
   at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.2.1.jar:6.2.1]
   at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.2.1.jar:6.2.1]
   at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.2.1.jar:6.2.1]
   at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.2.1.jar:6.2.1]
   at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.2.1.jar:6.2.1]
   at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.2.1.jar:6.2.1]
   at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.2.1.jar:6.2.1]
Caused by: java.lang.IllegalArgumentException: unknown setting [discovery.zen.ping.uincast.hosts] please check that any required plugins are installed, or check the breaking changes documentation for   removed settings
   at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:346) ~[elasticsearch-6.2.1.jar:6.2.1]
   at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:310) ~[elasticsearch-6.2.1.jar:6.2.1]
   at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:284) ~[elasticsearch-6.2.1.jar:6.2.1]
   at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:134) ~[elasticsearch-6.2.1.jar:6.2.1]
   at org.elasticsearch.node.Node.<init>(Node.java:331) ~[elasticsearch-6.2.1.jar:6.2.1]
   at org.elasticsearch.node.Node.<init>(Node.java:246) ~[elasticsearch-6.2.1.jar:6.2.1]
   at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.2.1.jar:6.2.1]
   at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.2.1.jar:6.2.1]
   at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.1.jar:6.2.1]
   at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.1.jar:6.2.1]
   ... 6 more

//*****************************************************************

//STACK 2 of 2*****************************************************

ERROR: [2] bootstrap checks failed
[1]: max file descriptors [4096] for elasticsearch process is too low, increase to at least [65536]
[2]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
[2018-02-27T15:07:09,937][INFO ][o.e.n.Node               ] [127x16] stopping ...
[2018-02-27T15:07:10,010][INFO ][o.e.n.Node               ] [127x16] stopped
[2018-02-27T15:07:10,010][INFO ][o.e.n.Node               ] [127x16] closing ...
[2018-02-27T15:07:10,025][INFO ][o.e.n.Node               ] [127x16] closed

//************************************************************************

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
