### ISSUE TITLE
a new node  can't added cluster ,what's the problem with that?

### ISSUE THREAD

**Issue by Berny-Chen** [elastic/elasticsearch#28863]
**Elasticsearch version** (`bin/elasticsearch --version`):
elasticsearch-6.1.0-1.noarch

**Plugins installed**: []
RPM

**JVM version** (`java -version`):
java version "1.8.0_131"

**OS version** (`uname -a` if on a Unix-like system):
CentOS release 6.9 (Final)

**Description of the problem including expected versus actual behavior**:
a new node  can't added cluster ,what's the problem with that?

**Provide logs (if relevant)**:
[2018-03-01T18:09:25,388][WARN ][o.e.d.z.ZenDiscovery     ] [ES-node5-Prod-alidc-0gow] master left (reason = transport disconnected), current nodes: nodes: 
   {ES-node6-Prod-alidc-0gow}{9z3JlbqlTlSjKaPmvkC8mQ}{ILn8aXdORCiulLbHwzxk9w}{172.19.6.125}{172.19.6.125:9300}, master
   {ES-node3-Prod-alidc-0gow}{vzlVHAVJQwKN-pUc_Z-dOg}{ISAMp3ZBTx-HzbJjATXCTA}{172.19.6.130}{172.19.6.130:9300}
   {ES-node1-Prod-alidc-0gow}{nnkT3W-hRniH-t0edRfAzg}{ig9j1cVCRSqf0JuK7FycRQ}{172.19.6.128}{172.19.6.128:9300}
   {ES-node2-Prod-alidc-0gow}{OR_iHSF_QUCK1yYNO-3_5Q}{zzQpgoZPTo2SEKpM9BRhuw}{172.19.6.129}{172.19.6.129:9300}
   {ES-node5-Prod-alidc-0gow}{qsR9cz9LRPqco27GPJrnxA}{DbFQlX5jRB-eSiIAWq65bQ}{172.19.6.124}{172.19.6.124:9300}, local

[2018-03-01T18:09:29,401][INFO ][o.e.c.s.ClusterApplierService] [ES-node5-Prod-alidc-0gow] detected_master {ES-node6-Prod-alidc-0gow}{9z3JlbqlTlSjKaPmvkC8mQ}{ILn8aXdORCiulLbHwzxk9w}{172.19.6.125}{172.19.6.125:9300}, reason: apply cluster state (from master [master {ES-node6-Prod-alidc-0gow}{9z3JlbqlTlSjKaPmvkC8mQ}{ILn8aXdORCiulLbHwzxk9w}{172.19.6.125}{172.19.6.125:9300} committed version [22655]])
[2018-03-01T18:09:34,407][WARN ][o.e.i.c.IndicesClusterStateService] [ES-node5-Prod-alidc-0gow] [[search][2]] marking and sending shard failed due to [failed to create shard]
java.io.IOException: failed to obtain in-memory shard lock
        at org.elasticsearch.index.IndexService.createShard(IndexService.java:389) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:510) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:141) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.createShard(IndicesClusterStateService.java:552) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.createOrUpdateShards(IndicesClusterStateService.java:529) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:231) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$6(ClusterApplierService.java:495) ~[elasticsearch-6.1.0.jar:6.1.0]
        at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_131]
        at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:492) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:479) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:429) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:158) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:568) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) [elasticsearch-6.1.0.jar:6.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.elasticsearch.env.ShardLockObtainFailedException: [search][2]: obtaining shard lock timed out after 5000ms
        at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:668) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:587) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.index.IndexService.createShard(IndexService.java:327) ~[elasticsearch-6.1.0.jar:6.1.0]
        ... 17 more
[2018-03-01T18:09:34,417][INFO ][dynamic-synonym          ] beforeIndexRemoved ! indexName:search
[2018-03-01T18:09:34,417][INFO ][dynamic-synonym          ] closeDynamicSynonym！ indexName:search scheduledFutures.size:0 dynamicSynonymFilters.size:0
[2018-03-01T18:10:02,815][WARN ][o.e.t.n.Netty4Transport  ] [ES-node5-Prod-alidc-0gow] send message failed [channel: org.elasticsearch.transport.netty4.NettyTcpChannel@211b0b13]
java.nio.channels.ClosedChannelException: null
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[?:?]
[2018-03-01T18:10:02,935][WARN ][o.e.t.n.Netty4Transport  ] [ES-node5-Prod-alidc-0gow] send message failed [channel: org.elasticsearch.transport.netty4.NettyTcpChannel@67001fe1]
java.nio.channels.ClosedChannelException: null
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[?:?]
[2018-03-01T18:10:29,421][INFO ][o.e.d.z.ZenDiscovery     ] [ES-node5-Prod-alidc-0gow] master_left [{ES-node6-Prod-alidc-0gow}{9z3JlbqlTlSjKaPmvkC8mQ}{ILn8aXdORCiulLbHwzxk9w}{172.19.6.125}{172.19.6.125:9300}], reason [failed to ping, tried [50] times, each with  maximum [3m] timeout]
[2018-03-01T18:10:29,422][WARN ][o.e.d.z.ZenDiscovery     ] [ES-node5-Prod-alidc-0gow] master left (reason = failed to ping, tried [50] times, each with  maximum [3m] timeout), current nodes: nodes: 
   {ES-node6-Prod-alidc-0gow}{9z3JlbqlTlSjKaPmvkC8mQ}{ILn8aXdORCiulLbHwzxk9w}{172.19.6.125}{172.19.6.125:9300}, master
   {ES-node3-Prod-alidc-0gow}{vzlVHAVJQwKN-pUc_Z-dOg}{ISAMp3ZBTx-HzbJjATXCTA}{172.19.6.130}{172.19.6.130:9300}
   {ES-node1-Prod-alidc-0gow}{nnkT3W-hRniH-t0edRfAzg}{ig9j1cVCRSqf0JuK7FycRQ}{172.19.6.128}{172.19.6.128:9300}
   {ES-node2-Prod-alidc-0gow}{OR_iHSF_QUCK1yYNO-3_5Q}{zzQpgoZPTo2SEKpM9BRhuw}{172.19.6.129}{172.19.6.129:9300}
   {ES-node5-Prod-alidc-0gow}{qsR9cz9LRPqco27GPJrnxA}{DbFQlX5jRB-eSiIAWq65bQ}{172.19.6.124}{172.19.6.124:9300}, local

[2018-03-01T18:10:32,438][INFO ][o.e.c.s.ClusterApplierService] [ES-node5-Prod-alidc-0gow] detected_master {ES-node6-Prod-alidc-0gow}{9z3JlbqlTlSjKaPmvkC8mQ}{ILn8aXdORCiulLbHwzxk9w}{172.19.6.125}{172.19.6.125:9300}, reason: apply cluster state (from master [master {ES-node6-Prod-alidc-0gow}{9z3JlbqlTlSjKaPmvkC8mQ}{ILn8aXdORCiulLbHwzxk9w}{172.19.6.125}{172.19.6.125:9300} committed version [22661]])
[2018-03-01T18:10:32,438][INFO ][dynamic-synonym          ] beforeIndexRemoved ! indexName:user
[2018-03-01T18:10:32,439][INFO ][dynamic-synonym          ] closeDynamicSynonym！ indexName:user scheduledFutures.size:0 dynamicSynonymFilters.size:0
[2018-03-01T18:10:37,438][INFO ][o.e.i.s.TransportNodesListShardStoreMetaData] [ES-node5-Prod-alidc-0gow] [search][2]: failed to obtain shard lock
org.elasticsearch.env.ShardLockObtainFailedException: [search][2]: obtaining shard lock timed out after 5000ms
        at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:668) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:587) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.index.store.Store.readMetadataSnapshot(Store.java:430) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.listStoreMetaData(TransportNodesListShardStoreMetaData.java:150) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.nodeOperation(TransportNodesListShardStoreMetaData.java:109) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.nodeOperation(TransportNodesListShardStoreMetaData.java:61) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:140) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:262) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:258) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1554) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.1.0.jar:6.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[2018-03-01T18:10:37,439][WARN ][o.e.t.n.Netty4Transport  ] [ES-node5-Prod-alidc-0gow] send message failed [channel: org.elasticsearch.transport.netty4.NettyTcpChannel@4886895c]
java.nio.channels.ClosedChannelException: null
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[?:?]
[2018-03-01T18:11:02,458][INFO ][o.e.d.z.ZenDiscovery     ] [ES-node5-Prod-alidc-0gow] master_left [{ES-node6-Prod-alidc-0gow}{9z3JlbqlTlSjKaPmvkC8mQ}{ILn8aXdORCiulLbHwzxk9w}{172.19.6.125}{172.19.6.125:9300}], reason [failed to ping, tried [50] times, each with  maximum [3m] timeout]
[2018-03-01T18:11:02,458][WARN ][o.e.d.z.ZenDiscovery     ] [ES-node5-Prod-alidc-0gow] master left (reason = failed to ping, tried [50] times, each with  maximum [3m] timeout), current nodes: nodes: 
   {ES-node6-Prod-alidc-0gow}{9z3JlbqlTlSjKaPmvkC8mQ}{ILn8aXdORCiulLbHwzxk9w}{172.19.6.125}{172.19.6.125:9300}, master
   {ES-node3-Prod-alidc-0gow}{vzlVHAVJQwKN-pUc_Z-dOg}{ISAMp3ZBTx-HzbJjATXCTA}{172.19.6.130}{172.19.6.130:9300}
   {ES-node1-Prod-alidc-0gow}{nnkT3W-hRniH-t0edRfAzg}{ig9j1cVCRSqf0JuK7FycRQ}{172.19.6.128}{172.19.6.128:9300}
   {ES-node2-Prod-alidc-0gow}{OR_iHSF_QUCK1yYNO-3_5Q}{zzQpgoZPTo2SEKpM9BRhuw}{172.19.6.129}{172.19.6.129:9300}
   {ES-node5-Prod-alidc-0gow}{qsR9cz9LRPqco27GPJrnxA}{DbFQlX5jRB-eSiIAWq65bQ}{172.19.6.124}{172.19.6.124:9300}, local

[2018-03-01T18:11:07,471][INFO ][o.e.c.s.ClusterApplierService] [ES-node5-Prod-alidc-0gow] detected_master {ES-node6-Prod-alidc-0gow}{9z3JlbqlTlSjKaPmvkC8mQ}{ILn8aXdORCiulLbHwzxk9w}{172.19.6.125}{172.19.6.125:9300}, reason: apply cluster state (from master [master {ES-node6-Prod-alidc-0gow}{9z3JlbqlTlSjKaPmvkC8mQ}{ILn8aXdORCiulLbHwzxk9w}{172.19.6.125}{172.19.6.125:9300} committed version [22664]])
[2018-03-01T18:11:12,488][WARN ][o.e.i.c.IndicesClusterStateService] [ES-node5-Prod-alidc-0gow] [[search][2]] marking and sending shard failed due to [failed to create shard]
java.io.IOException: failed to obtain in-memory shard lock
        at org.elasticsearch.index.IndexService.createShard(IndexService.java:389) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:510) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:141) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.createShard(IndicesClusterStateService.java:552) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.createOrUpdateShards(IndicesClusterStateService.java:529) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:231) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$6(ClusterApplierService.java:495) ~[elasticsearch-6.1.0.jar:6.1.0]
        at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_131]
        at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:492) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:479) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:429) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:158) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:568) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) [elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) [elasticsearch-6.1.0.jar:6.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.elasticsearch.env.ShardLockObtainFailedException: [search][2]: obtaining shard lock timed out after 5000ms
        at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:668) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:587) ~[elasticsearch-6.1.0.jar:6.1.0]
        at org.elasticsearch.index.IndexService.createShard(IndexService.java:327) ~[elasticsearch-6.1.0.jar:6.1.0]

**Comment by javanna** [comment]
hi @Berny-Chen could you please ask your question on our forums at https://discuss.elastic.co/ ? We reserve github for bugs and feature requests.
