### ISSUE TITLE
Unknown setting [es.enforce.bootstrap.checks] in docker.elastic.co/elasticsearch/elasticsearch:6.2.2

### ISSUE THREAD

**Issue by MetalArend** [elastic/elasticsearch#28872]
**ElasticSearch version**: docker.elastic.co/elasticsearch/elasticsearch:6.2.2 on docker 17.12.0-ce, build c97c6d6 inside a CentOS 7 vagrant box

**Description of the problem including expected versus actual behavior**:

Adding the setting `es.enforce.bootstrap.checks` on the 6.2.2 version docker container throws the error `unknown setting [es.enforce.bootstrap.checks] please check that any required plugins are installed, or check the breaking changes documentation for removed settings`. I could not find a docker repository, so I hope reporting it here is okay?

**Steps to reproduce**:

I am running the latest (current) version of ElasticSearch from an official docker image as a service in a docker-compose file called swarm.yml. I declared this service as follows:

```
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=6_2_2-cluster
      - es.enforce.bootstrap.checks=true
      - bootstrap.memory_lock=false
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elk
    ports:
      - target: 9200
      - target: 9300
```
I run this stack with the command `docker stack deploy --compose-file swarm.yml`, and start following the logs with `docker service logs --follow <stackname>_elasticsearch`.

I tried adding the `es.enforce.bootstrap.checks=true` both in the environment, as well as `-Des.enforce.bootstrap.checks=true` inside the ES_JAVA_OPTS string, and both give me the same error: `org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [es.enforce.bootstrap.checks] please check that any required plugins are installed, or check the breaking changes documentation for removed settings`. Afaik this option is still mentioned in the current 6.2 documentation, as well as on master.

I actually expected the bootstrap checks to fail, but not on providing their value. I can't figure out why this is failing, or which setting to use.

**Provide logs (if relevant)**:

```
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:34,336][INFO ][o.e.n.Node               ] [] initializing ...
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:34,418][INFO ][o.e.e.NodeEnvironment    ] [2GwlB1E] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/mapper/VolGroup00-LogVol00)]], net usable_space [34.7gb], net total_space [37.4gb], types [xfs]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:34,418][INFO ][o.e.e.NodeEnvironment    ] [2GwlB1E] heap size [495.3mb], compressed ordinary object pointers [true]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:34,432][INFO ][o.e.n.Node               ] node name [2GwlB1E] derived from node ID [2GwlB1E1TcKKJnLINWHimA]; set [node.name] to override
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:34,433][INFO ][o.e.n.Node               ] version[6.2.2], pid[1], build[10b1edd/2018-02-16T19:01:30.685723Z], OS[Linux/3.10.0-693.11.6.el7.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_161/25.161-b14]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:34,433][INFO ][o.e.n.Node               ] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch.8DdktKnh, -XX:+HeapDumpOnOutOfMemoryError, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Des.cgroups.hierarchy.override=/, -Xms512m, -Xmx512m, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,678][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded module [aggs-matrix-stats]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,678][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded module [analysis-common]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,678][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded module [ingest-common]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,679][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded module [lang-expression]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,679][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded module [lang-mustache]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,679][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded module [lang-painless]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,679][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded module [mapper-extras]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,679][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded module [parent-join]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,679][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded module [percolator]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,679][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded module [rank-eval]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,679][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded module [reindex]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,679][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded module [repository-url]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,680][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded module [transport-netty4]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,680][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded module [tribe]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,680][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded plugin [ingest-geoip]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,680][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded plugin [ingest-user-agent]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,680][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded plugin [x-pack-core]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,680][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded plugin [x-pack-deprecation]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,680][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded plugin [x-pack-graph]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,680][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded plugin [x-pack-logstash]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,680][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded plugin [x-pack-ml]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,681][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded plugin [x-pack-monitoring]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,681][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded plugin [x-pack-security]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,681][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded plugin [x-pack-upgrade]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:36,681][INFO ][o.e.p.PluginsService     ] [2GwlB1E] loaded plugin [x-pack-watcher]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | [2018-03-01T17:48:38,708][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [es.enforce.bootstrap.checks] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.2.2.jar:6.2.2]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.2.2.jar:6.2.2]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.2.2.jar:6.2.2]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.2.2.jar:6.2.2]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | 	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.2.2.jar:6.2.2]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.2.2.jar:6.2.2]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.2.2.jar:6.2.2]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | Caused by: java.lang.IllegalArgumentException: unknown setting [es.enforce.bootstrap.checks] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | 	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:346) ~[elasticsearch-6.2.2.jar:6.2.2]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | 	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:310) ~[elasticsearch-6.2.2.jar:6.2.2]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | 	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:284) ~[elasticsearch-6.2.2.jar:6.2.2]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | 	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:134) ~[elasticsearch-6.2.2.jar:6.2.2]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | 	at org.elasticsearch.node.Node.<init>(Node.java:331) ~[elasticsearch-6.2.2.jar:6.2.2]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | 	at org.elasticsearch.node.Node.<init>(Node.java:246) ~[elasticsearch-6.2.2.jar:6.2.2]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.2.2.jar:6.2.2]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.2.2.jar:6.2.2]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.2.jar:6.2.2]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.2.jar:6.2.2]
es622_elasticsearch.1.lghtgi9ebvye@localhost.localdomain    | 	... 6 more
```

**Comment by dadoonet** [comment]
I believe it should be written as:

```yml
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=6_2_2-cluster
      - enforce.bootstrap.checks=true
      - bootstrap.memory_lock=false
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elk
    ports:
      - target: 9200
      - target: 9300
```

**Comment by jasontedor** [comment]
You set this via JVM options, so either by binding jvm.options and adding the configuration there, or via `ES_JAVA_OPTS`.

```
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true"
```

**Comment by MetalArend** [comment]
I was already hitting me on the head, but then I tried it, and alas...

```
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [enforce.bootstrap.checks] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
```

**Comment by MetalArend** [comment]
As I said in the original report, I tried it both the environment setting way, as the way @jasontedor described. But apparently the service logs are kept between redeploys, so the error was kept in the logs, but not reproduced. Thanks, @jasontedor.
