### ISSUE TITLE
"failed to add query" when restarting elasticsearch, when Percolator query contains a term filter defined in another document

### ISSUE THREAD

**Issue by davidscottcohen** [elastic/elasticsearch#28914]
**Elasticsearch version** (`bin/elasticsearch --version`):

Version: 2.4.4, Build: fcbb46d/2017-01-03T11:33:16Z, JVM: 1.8.0_121

**Plugins installed**: []

**JVM version** (`java -version`):

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode

**OS version** (`uname -a` if on a Unix-like system):

Linux 2.6.32-696.20.1.el6.x86_64 #1 SMP Fri Jan 26 17:51:45 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
When using Percolator, where the query has a term filter where the terms are in another document, Elasticsearch will not be able to reload the query on restart.

Below I show the simplest and most guaranteed reproduction, which is a cluster with 1 shard and 0 replicas.  We've seen this same behavior (but less consistently) on larger clusters.

**Steps to reproduce**:

I will define some json files above, and refer to them in the steps:

**index.json**:
```
{
    "settings" : {
	"number_of_shards" : 1,
	"number_of_replicas": 0
    },
    "mappings" : {
      ".percolator" : {
        "properties" : {
	  "query" : {
            "type" : "object",
	    "enabled" : false
	  }
	}
      },
      "filter" : {
	"properties" : {
          "value" : {
            "type" : "string"
          }
        }
      },
      "doc" : {
        "properties" : {
          "message" : {
            "type" : "string"
          }
        }
      }
    }
}
```

**filter.json**
```
{
    "value" : [ "foo", "bar", "baz" ]
}
```

**percolator.json**
```
{
  "query" : {
      "terms" : {
	"message" : {
          "index" : "my-index",
          "type" : "filter",
          "id" : 1,
          "path" : "value"
	}
      }
    }
}
```

**doc.json**
```
{
  "message": "foo"
}
```

 1. `curl -XPUT localhost:9200/my-index -d @index.json`
 2. `curl -XPUT localhost:9200/my-index/filter/1 -d @filter.json`
 3. `curl -XPUT localhost:9200/my-index/doc/1 -d @doc.json`
 4. `curl -XPUT localhost:9200/my-index/.percolator/1 -d @percolator.json`
 5. `curl -XGET localhost:9200/my-index/doc/1/_percolate`
 6. Observe that percolate matched query with ID 1
 7. Restart elasticsearch
 8. Note the errors that print out (copied below)
 9. Repeat Step 5, note that we no longer match query with ID 1.

Expected: Restarting Elasticsearch should not break Percolator
Actual: Percolator query does not work after restart.

**Provide logs (if relevant)**:

```
[2018-03-06 11:35:19,406][WARN ][bootstrap                ] unable to install syscall filter: seccomp unavailable: CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER are needed
[2018-03-06 11:35:19,583][INFO ][node                     ] [Vakume] version[2.4.4], pid[10912], build[fcbb46d/2017-01-03T11:33:16Z]
[2018-03-06 11:35:19,583][INFO ][node                     ] [Vakume] initializing ...
[2018-03-06 11:35:20,078][INFO ][plugins                  ] [Vakume] modules [reindex, lang-expression, lang-groovy], plugins [], sites []
[2018-03-06 11:35:20,095][INFO ][env                      ] [Vakume] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [42.2gb], net total_space [46.5gb], spins? [unknown], types [rootfs]
[2018-03-06 11:35:20,095][INFO ][env                      ] [Vakume] heap size [990.7mb], compressed ordinary object pointers [true]
[2018-03-06 11:35:21,727][INFO ][node                     ] [Vakume] initialized
[2018-03-06 11:35:21,727][INFO ][node                     ] [Vakume] starting ...
[2018-03-06 11:35:21,799][INFO ][transport                ] [Vakume] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2018-03-06 11:35:21,810][INFO ][discovery                ] [Vakume] elasticsearch/TO-R_JE0TLy9czpjguj38A
[2018-03-06 11:35:24,864][INFO ][cluster.service          ] [Vakume] new_master {Vakume}{TO-R_JE0TLy9czpjguj38A}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2018-03-06 11:35:24,891][INFO ][http                     ] [Vakume] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
[2018-03-06 11:35:24,891][INFO ][node                     ] [Vakume] started
[2018-03-06 11:35:24,925][INFO ][gateway                  ] [Vakume] recovered [1] indices into cluster_state
[2018-03-06 11:35:25,341][WARN ][index.percolator         ] [Vakume] [my-index][0] failed to add query [1]
[my-index] PercolatorException[failed to parse query [null]]; nested: NoShardAvailableActionException[No shard available for [get [my-index][filter][1]: routing [null]]]; nested: RemoteTransportException[[Vakume][127.0.0.1:9300][indices:data/read/get[s]]]; nested: IllegalIndexShardStateException[CurrentState[RECOVER\
ING] operations only allowed when shard state is one of [POST_RECOVERY, STARTED, RELOCATED]];
        at org.elasticsearch.index.percolator.PercolatorQueriesRegistry.parsePercolatorDocument(PercolatorQueriesRegistry.java:182)
        at org.elasticsearch.index.percolator.QueriesLoaderCollector.collect(QueriesLoaderCollector.java:80)
        at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:221)
        at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:172)
        at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:821)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:535)
        at org.elasticsearch.index.percolator.PercolatorQueriesRegistry$ShardLifecycleListener.loadQueries(PercolatorQueriesRegistry.java:264)
        at org.elasticsearch.index.percolator.PercolatorQueriesRegistry$ShardLifecycleListener.beforeIndexShardPostRecovery(PercolatorQueriesRegistry.java:245)
        at org.elasticsearch.indices.InternalIndicesLifecycle.beforeIndexShardPostRecovery(InternalIndicesLifecycle.java:126)
        at org.elasticsearch.index.shard.IndexShard.postRecovery(IndexShard.java:883)
        at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:248)
        at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
        at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: NoShardAvailableActionException[No shard available for [get [my-index][filter][1]: routing [null]]]; nested: RemoteTransportException[[Vakume][127.0.0.1:9300][indices:data/read/get[s]]]; nested: IllegalIndexShardStateException[CurrentState[RECOVERING] operations only allowed when shard state is one of [PO\
ST_RECOVERY, STARTED, RELOCATED]];
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.perform(TransportSingleShardAction.java:199)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.onFailure(TransportSingleShardAction.java:186)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.access$1300(TransportSingleShardAction.java:115)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleException(TransportSingleShardAction.java:240)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:874)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:852)
        at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:389)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
        ... 3 more
Caused by: RemoteTransportException[[Vakume][127.0.0.1:9300][indices:data/read/get[s]]]; nested: IllegalIndexShardStateException[CurrentState[RECOVERING] operations only allowed when shard state is one of [POST_RECOVERY, STARTED, RELOCATED]];
Caused by: [my-index][[my-index][0]] IllegalIndexShardStateException[CurrentState[RECOVERING] operations only allowed when shard state is one of [POST_RECOVERY, STARTED, RELOCATED]]
        at org.elasticsearch.index.shard.IndexShard.readAllowed(IndexShard.java:1038)
        at org.elasticsearch.index.shard.IndexShard.get(IndexShard.java:655)
        at org.elasticsearch.index.get.ShardGetService.innerGet(ShardGetService.java:173)
        at org.elasticsearch.index.get.ShardGetService.get(ShardGetService.java:86)
        at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:101)
        at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:44)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:282)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:275)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:378)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2018-03-06 11:35:25,351][INFO ][cluster.routing.allocation] [Vakume] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[my-index][0]] ...]).
```

**Comment by spinscale** [comment]
version 2.4.4 is no longer supported, as Elasticsearch is already two major versions ahead. Percolator has also massively changed to become a query in Elasticsearch 5.x upwards.

Can you check if this problem still persists in the most recent major version of Elasticsearch. If not, I will close this issue.

**Comment by martijnvg** [comment]
@davidscottcohen This problem cannot occur in ES 5.0 and later. The way the `terms` query is executed inside a percolator query has changed completely and the terms are now fetched when the percolator query is indexed, this to avoid problems like you've encounter here.

I will close this issue, please comment if you have questions.
