### ISSUE TITLE
QueryRescorerIT.testRescoreAfterCollapse fails reproducibly

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#28932]
After #28521 was merged, `QueryRescorerIT.testRescoreAfterCollapse` has been failing repeatedly with the following error:

```
FAILURE 3.90s | QueryRescorerIT.testRescoreAfterCollapse <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: iterable over ["2", "3"] in any order
   >      but: Not matched: "4"
   > 	at __randomizedtesting.SeedInfo.seed([30FBB95F5B7604EB:98BFA1EB1D7DB3B1]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.search.functionscore.QueryRescorerIT.testRescoreAfterCollapse(QueryRescorerIT.java:795)
   > 	at java.lang.Thread.run(Thread.java:748)
```

This reproduces on 6.x for me with:

```
./gradlew :server:integTest -Dtests.seed=30FBB95F5B7604EB -Dtests.class=org.elasticsearch.search.functionscore.QueryRescorerIT -Dtests.method="testRescoreAfterCollapse" -Dtests.security.manager=true -Dtests.locale=und -Dtests.timezone=Europe/Berlin
```

And can be seen here: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/772/console

**Comment by jimczi** [comment]
Thanks @dakrone, https://github.com/elastic/elasticsearch/pull/28521 has been reverted in https://github.com/elastic/elasticsearch/commit/bc8b3fc71ca405832b410a97fc3bd3589ff12f34 so I am closing this issue.
