### ISSUE TITLE
[TEST] GeoIpProcessorFactoryTests fails handling files on Windows

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#29001]
GeoIP cannot clean up the database files because they are still being used by another test?

build failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1368/console

```
20:49:52   1> [2018-03-12T21:49:49,082][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testBuildWithCountryDbAndAsnFields]: before test
20:49:52 
20:49:52   1> [2018-03-12T21:49:49,083][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testBuildWithCountryDbAndAsnFields]: after test
20:49:52 
20:49:52 ERROR   0.00s J1 | GeoIpProcessorFactoryTests (suite) <<< FAILURES!
20:49:52 
20:49:52   2> NOTE: All tests run in this JVM: [GeoIpProcessorFactoryTests]
20:49:52 
20:49:52    > Throwable #1: java.io.IOException: Could not remove the following files (in the order of attempts):
20:49:52    >    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\plugins\ingest-geoip\build\testrun\test\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_A72F0DB2EDA125D3-001\tempDir-002\ingest-geoip\GeoLite2-ASN.mmdb: java.nio.file.FileSystemException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\plugins\ingest-geoip\build\testrun\test\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_A72F0DB2EDA125D3-001\tempDir-002\ingest-geoip\GeoLite2-ASN.mmdb: The process cannot access the file because it is being used by another process.
20:49:52    >    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\plugins\ingest-geoip\build\testrun\test\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_A72F0DB2EDA125D3-001\tempDir-002\ingest-geoip\GeoLite2-City.mmdb: java.nio.file.FileSystemException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\plugins\ingest-geoip\build\testrun\test\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_A72F0DB2EDA125D3-001\tempDir-002\ingest-geoip\GeoLite2-City.mmdb: The process cannot access the file because it is being used by another process.
20:49:52    >    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\plugins\ingest-geoip\build\testrun\test\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_A72F0DB2EDA125D3-001\tempDir-002\ingest-geoip\GeoLite2-Country.mmdb: java.nio.file.FileSystemException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\plugins\ingest-geoip\build\testrun\test\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_A72F0DB2EDA125D3-001\tempDir-002\ingest-geoip\GeoLite2-Country.mmdb: The process cannot access the file because it is being used by another process.
20:49:52    >    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\plugins\ingest-geoip\build\testrun\test\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_A72F0DB2EDA125D3-001\tempDir-002\ingest-geoip: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\plugins\ingest-geoip\build\testrun\test\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_A72F0DB2EDA125D3-001\tempDir-002\ingest-geoip
20:49:52    >    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\plugins\ingest-geoip\build\testrun\test\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_A72F0DB2EDA125D3-001\tempDir-002: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\plugins\ingest-geoip\build\testrun\test\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_A72F0DB2EDA125D3-001\tempDir-002
20:49:52    >    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\plugins\ingest-geoip\build\testrun\test\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_A72F0DB2EDA125D3-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\plugins\ingest-geoip\build\testrun\test\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_A72F0DB2EDA125D3-001
20:49:52    > 	at __randomizedtesting.SeedInfo.seed([A72F0DB2EDA125D3]:0)
20:49:52    > 	at org.apache.lucene.util.IOUtils.rm(IOUtils.java:329)
20:49:52    > 	at java.lang.Thread.run(Thread.java:748)
20:49:52 Completed [2/3] on J1 in 6.90s, 12 tests, 1 error <<< FAILURES!
20:49:52 
20:49:55 Suite: org.elasticsearch.ingest.geoip.GeoIpProcessorTests
20:49:55 Completed [3/3] on J2 in 10.06s, 12 tests
20:49:55 
20:49:55 Tests with failures:
20:49:55   - org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests (suite)```

**Comment by jasontedor** [comment]
It is because these files can not be deleted while a mapped byte buffer that is backed by a memory mappings of these files has not been garbage collected. We should merely skip these tests on Windows.

**Comment by talevy** [comment]
cool.

I will go ahead and add an `assumeTrue` in the right places in this test class as to skip this on Windows

**Comment by jasontedor** [comment]
Thanks @talevy.

**Comment by talevy** [comment]
Any suggestions on how to go about doing this?

issue: If one sticks a `assumeFalse(..., Windows)`  in the `BeforeClass` segment, all the tests within 
the suite are skipped, which leads to the suite to fail.

Since the problem is outside the scope of any one test, I can't think of anything cleaner than moving the `BeforeClass` and `AfterClass` methods to be called internally within each test method, and introducing a dummy test that will never be skipped.

**Comment by danielmitterdorfer** [comment]
I can take that one @talevy.
