### ISSUE TITLE
index.merge.scheduler.max_thread_count error in elasticsearch.yml

### ISSUE THREAD

**Issue by kervin521** [elastic/elasticsearch#29054]
elasticsearch guid link :https://www.elastic.co/guide/cn/elasticsearch/guide/current/indexing-performance.html

in elasticsearch.yml setting:
index.merge.scheduler.max_thread_count: 1

but it startup error : 

Found index level settings on node level configuration.

Since elasticsearch 5.x index level settings can NOT be set on the nodes
configuration like the elasticsearch.yaml, in system properties or command line
arguments.In order to upgrade all indices the settings must be updated via the
/${index}/_settings API. Unless all settings are dynamic all indices must be closed
in order to apply the upgradeIndices created in the future should use index templates
to set default values.

Please ensure all required values are updated on all indices by executing:

curl -XPUT 'http://localhost:9200/_all/_settings?preserve_existing=true' -d '{
  "index.merge.scheduler.max_thread_count" : "1"
}'
*************************************************************************************

[2018-03-14T17:44:31,999][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [elasticsearch] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: node settings must not contain any index level settings
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.4.1.jar:5.4.1]
Caused by: java.lang.IllegalArgumentException: node settings must not contain any index level settings
        at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:132) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.node.Node.<init>(Node.java:343) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.node.Node.<init>(Node.java:242) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:350) ~[elasticsearch-5.4.1.jar:5.4.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.4.1.jar:5.4.1]
        ... 6 more

**Comment by colings86** [comment]
Hi @kervin521, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. Thank you!

This is not a bug. As the error explains, since 5.x we do not allow settings that start with `index.*` to be set in the elasticsearch.yml file. You will need to remove these settings from the elasticsearch.yml file and add them to your indices using [index templates](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/indices-templates.html) and/or the [update index settings API](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/indices-update-settings.html).
