### ISSUE TITLE
[ci] testPrimaryReplicaResyncFailed fails

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#29060]
CI failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=sles/800/consoleFull

Output:

```
13:30:08 FAILURE 19.9s J2 | PrimaryAllocationIT.testPrimaryReplicaResyncFailed <<< FAILURES!
13:30:08    > Throwable #1: java.lang.AssertionError: 
13:30:08    > Expected: a collection with size <2>
13:30:08    >      but: collection size was <1>
13:30:08    > 	at __randomizedtesting.SeedInfo.seed([FD72C6962ACD56CD:32B7E1ED02EDC35D]:0)
13:30:08    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
13:30:08    > 	at org.elasticsearch.cluster.routing.PrimaryAllocationIT.lambda$testPrimaryReplicaResyncFailed$7(PrimaryAllocationIT.java:383)
13:30:08    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:734)
13:30:08    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:708)
13:30:08    > 	at org.elasticsearch.cluster.routing.PrimaryAllocationIT.testPrimaryReplicaResyncFailed(PrimaryAllocationIT.java:381)
```

/cc: @elastic/es-distributed

**Comment by dnhatn** [comment]
CI Log: [resync-test.txt](https://github.com/elastic/elasticsearch/files/1826741/resync-test.txt)

**Comment by bleskes** [comment]
@dnhatn is there a concrete plan for this one?

**Comment by dnhatn** [comment]
@bleskes  I am looking at this now.
