### ISSUE TITLE
[CI] GetResultTests testToAndFromXContent() failure

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#29080]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=oraclelinux/803/console

I can reproduce with
```
./gradlew :server:test   -Dtests.seed=F8AFBCE0BED19183   -Dtests.class=org.elasticsearch.index.get.GetResultTests   -Dtests.method="testToAndFromXContent"   -Dtests.security.manager=true   -Dtests.locale=uk-UA   -Dtests.timezone=Africa/Nouakchott
```
and will look into it

**Comment by cbuescher** [comment]
Most likely related:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=debian/803/console

```
REPRODUCE WITH: ./gradlew :server:test \
  -Dtests.seed=51F0874FCD02DF31 \
  -Dtests.class=org.elasticsearch.index.get.GetResultTests \
  -Dtests.method="testToAndFromXContentEmbedded" \
  -Dtests.security.manager=true \
  -Dtests.locale=is \
  -Dtests.timezone=America/Rankin_Inlet
```

**Comment by cbuescher** [comment]
These failures are cause by changes made in #28972 which seems to have changed some assumptions about how SMILE and CBOR write `byte[]` values. I'm not sure if the test assumtions are wrong or something in the xContent serialization changed unintentionally, I'll open a PR shortly that adjusts the test setup slightly but will probably disable the failing tests in the meantime.

**Comment by pgomulka** [comment]
The problem seems to be occurring again

does not reproduce for me though
```
REPRODUCE WITH: ./gradlew :server:test \
  -Dtests.seed=191A8C8BD80E0BF9 \
  -Dtests.class=org.elasticsearch.index.get.GetResultTests \
  -Dtests.method="testToAndFromXContentEmbedded" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Latn \
  -Dtests.timezone=Africa/Lubumbashi \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

```
Suite: org.elasticsearch.index.query.IntervalBuilderTests
Completed [212/1213] on J3 in 0.25s, 6 tests

Suite: org.elasticsearch.index.get.GetResultTests
  1> [2018-12-17T16:33:43,390][INFO ][o.e.i.g.GetResultTests   ] [testToAndFromXContent] before test
  1> [2018-12-17T16:33:43,408][INFO ][o.e.i.g.GetResultTests   ] [testToAndFromXContent] after test
  1> [2018-12-17T16:33:43,410][INFO ][o.e.i.g.GetResultTests   ] [testGetSourceAsBytes] before test
  1> [2018-12-17T16:33:43,412][INFO ][o.e.i.g.GetResultTests   ] [testGetSourceAsBytes] after test
  1> [2018-12-17T16:33:43,427][INFO ][o.e.i.g.GetResultTests   ] [testEqualsAndHashcode] before test
  1> [2018-12-17T16:33:43,430][INFO ][o.e.i.g.GetResultTests   ] [testEqualsAndHashcode] after test
  1> [2018-12-17T16:33:43,441][INFO ][o.e.i.g.GetResultTests   ] [testToXContentEmbeddedNotFound] before test
  1> [2018-12-17T16:33:43,442][INFO ][o.e.i.g.GetResultTests   ] [testToXContentEmbeddedNotFound] after test
  1> [2018-12-17T16:33:43,445][INFO ][o.e.i.g.GetResultTests   ] [testToAndFromXContentEmbedded] before test
  1> [2018-12-17T16:33:43,451][INFO ][o.e.i.g.GetResultTests   ] [testToAndFromXContentEmbedded] after test
FAILURE 0.05s J5 | GetResultTests.testToAndFromXContentEmbedded <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected: org.elasticsearch.index.get.GetResult<{
   >   "_index" : null,
   >   "_type" : null,
   >   "_id" : null,
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+master+intake/server/build/testrun/test/J5/temp/org.elasticsearch.index.get.GetResultTests_191A8C8BD80E0BF9-001
  2> NOTE: test params are: codec=Asserting(Lucene80): {}, docValues:{}, maxPointsInLeafNode=292, maxMBSortInHeap=5.385706637104219, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@1a72a0e), locale=sr-Latn, timezone=Africa/Lubumbashi
   >   "_seq_no" : 2821624607299586225,
   >   "_primary_term" : 71,
  2> NOTE: Linux 4.16.8-300.fc28.x86_64 amd64/Oracle Corporation 1.8.0_192 (64-bit)/cpus=16,threads=1,free=478709224,total=519569408
   >   "_ignored" : [
  2> NOTE: All tests run in this JVM: [VersionTypeTests, ClusterChangedEventTests, TransportTasksActionTests, BucketScriptTests, RootObjectMapperTests, FilterAllocationDeciderTests, RewriteableTests, FieldFilterMapperPluginTests, GetResponseTests, CancellableThreadsTests, NodeInfoStreamingTests, HumanReadableIndexSettingsTests, MurmurHash3Tests, CompletionFieldMapperTests, SortBuilderTests, AggregationCollectorTests, RestExplainActionTests, JacksonLocationTests, TypeFieldMapperTests, XContentBuilderTests, GetResultTests]
   >     "bPOnc"
   >   ],
   >   "_size" : "Iwg",
   >   "_timestamp" : "zjlYsNrL",
   >   "found" : true,
   >   "_source" : {
   >     "RYVeMq" : "WZpIX",
   >     "mdpbBUxZ" : [
   >       {
   >         "iEpbsqODPX" : "fZjNMN",
   >         "YnvmHM" : "MNKptcA",
   >         "muTJTviCJv" : "ATAGgzMF",
   >         "AoIPuXhN" : "ILndesZeii"
   >       },
   >       {
   >         "KSTEGLAI" : 2456841961461020281,
   >         "GChrTxPVW" : "mhCnGCzBog",
   >         "SBTdZiE" : -3220527271125005118
   >       },
   >       {
   >         "FexTiIpm" : "UjOkzKeBb"
   >       },
   >       {
   >         "xjFoFNGtCg" : 0.7478763431908205,
   >         "sihcDE" : -4511678292845039938,
   >         "QMmvgG" : 0.5985500938244123,
   >         "BZtLSc" : 0.32762126512410417
   >       },
   >       {
   >         "lfgVdfplMe" : 0.07731378865228922,
   >         "zIXjvrRx" : "GeITvDS",
   >         "YWJPFu" : "bnau"
   >       }
   >     ],
   >     "kGFZDBQRL" : {
   >       "gqxumUDBm" : "PNgQwDa",
   >       "OqlDAX" : {
   >         "FcbJztm" : "fEB"
   >       },
   >       "IrEeHV" : {
   >         "KcrFvvV" : {
   >           "GyJNstTr" : 4024591634763594630,
   >           "LACWaCgsm" : [
   >             {
   >               "dQaOOoAny" : 0.15732765468344279,
   >               "UAZTOcNSpJ" : "AJwuQhgd"
   >             },
   >             {
   >               "OOzsfuj" : "kVLgMWfKx",
   >               "DNDupc" : "ahAf",
   >               "onPmcv" : "avcqSqcYqt",
   >               "mIuDkUxABA" : "YMjtmXO",
   >               "TSPLZURyR" : 0.10700387438721548
   >             },
   >             {
   >               "orukGlv" : "vlHDp",
   >               "XVIpeUrf" : "GtSuOwF",
   >               "evUUZJLacm" : -2708454255391328974
   >             },
   >             {
   >               "ijBNNr" : "efvYOaWa",
   >               "wORAbwDwTP" : 0.5294999673088226,
   >               "gVDzdhOSBq" : "NoCaxjBL"
   >             }
   >           ]
   >         },
   >         "dIjABsAxX" : {
   >           "fLgmkpSA" : -3895094984495233586,
   >           "QQvgyxaBxf" : "pBTNtZbE",
   >           "AvXLjdkf" : "SJpdFO",
   >           "AxcsHTVw" : "mUAlNZQuKc",
   >           "mFtZzzTZk" : {
   >             "hmxbMfMaJ" : 0.44229261635103667,
   >             "KLiWtSHG" : 0.08376628232822814
   >           }
   >         }
   >       }
   >     }
   >   },
   >   "fields" : {
   >     "ludWBUdufX" : [
   >       13250,
   >       -3815,
   >       16064,
   >       -6547,
   >       -21341
   >     ],
   >     "ykhUhH" : [
   >       -1933135152
   >     ],
   >     "HEc" : [
   >       0.9251104
   >     ],
   >     "nSiAKK" : [
   >       "x5ls74Gn5ISC3YTzpJyl7qug7q6tw6jsl5pDIu+BpAckxJrzopSLyaTwtr2P7qi5zKXylJCaEz3zgKOJDNi37qyB75C1CVzurrvuhKzxvIm115h675in0Yg=",
   >       "8Z2tqVTyqqi374626p+47qyNQA7JqdWd1oTzsoqB8bixodmzxanwqKCi47efQBLPie6YvdSk77uY6bmx856Boe+hh+yvpO+Nu3g=",
   >       "8LyGiH/guLHvq6/Tn+65pu+YuXbzn6usRuacudqiw6XunLZjw4I=",
   >       "3bruuYHxtKWU2YTugLHupqLZuOqpiMei7qix7omp35zxorut74uX7pKC3Y7qm6rytJC58aKfot2d75qy7qmCeuuksBjvjYl48LeboO63ouu1kg==",
   >       "4pyL2Z3ri5X0i7+ew7B+0aPyhIaP7omMLuyqhcSf4KWc7rCKw7/Wg+ORoe++onLknKTvmLrisK/yjKa/fei+p9KbOOGDryPvoJXCreWgoeavge2Cp9me6KaJUOW2h+6ovcqTd++sgtq2HHPmlYd1"
   >     ]
   >   }
   > }> but was: org.elasticsearch.index.get.GetResult<{
   >   "_index" : null,
   >   "_type" : null,
   >   "_id" : null,
   >   "_seq_no" : 2821624607299586225,
   >   "_primary_term" : 71,
   >   "_ignored" : [
   >     "bPOnc"
   >   ],
   >   "_size" : "Iwg",
   >   "_timestamp" : "zjlYsNrL",
   >   "found" : true,
   >   "_source" : {
   >     "RYVeMq" : "WZpIX",
   >     "mdpbBUxZ" : [
   >       {
   >         "iEpbsqODPX" : "fZjNMN",
   >         "YnvmHM" : "MNKptcA",
   >         "muTJTviCJv" : "ATAGgzMF",
   >         "AoIPuXhN" : "ILndesZeii"
   >       },
   >       {
   >         "KSTEGLAI" : 2456841961461020281,
   >         "GChrTxPVW" : "mhCnGCzBog",
   >         "SBTdZiE" : -3220527271125005118
   >       },
   >       {
   >         "FexTiIpm" : "UjOkzKeBb"
   >       },
   >       {
   >         "xjFoFNGtCg" : 0.7478763431908205,
   >         "sihcDE" : -4511678292845039938,
   >         "QMmvgG" : 0.5985500938244123,
   >         "BZtLSc" : 0.32762126512410417
   >       },
   >       {
   >         "lfgVdfplMe" : 0.07731378865228922,
   >         "zIXjvrRx" : "GeITvDS",
   >         "YWJPFu" : "bnau"
   >       }
   >     ],
   >     "kGFZDBQRL" : {
   >       "gqxumUDBm" : "PNgQwDa",
   >       "OqlDAX" : {
   >         "FcbJztm" : "fEB"
   >       },
   >       "IrEeHV" : {
   >         "KcrFvvV" : {
   >           "GyJNstTr" : 4024591634763594630,
   >           "LACWaCgsm" : [
   >             {
   >               "dQaOOoAny" : 0.15732765468344279,
   >               "UAZTOcNSpJ" : "AJwuQhgd"
   >             },
   >             {
   >               "OOzsfuj" : "kVLgMWfKx",
   >               "DNDupc" : "ahAf",
   >               "onPmcv" : "avcqSqcYqt",
   >               "mIuDkUxABA" : "YMjtmXO",
   >               "TSPLZURyR" : 0.10700387438721548
   >             },
   >             {
   >               "orukGlv" : "vlHDp",
   >               "XVIpeUrf" : "GtSuOwF",
   >               "evUUZJLacm" : -2708454255391328974
   >             },
   >             {
   >               "ijBNNr" : "efvYOaWa",
   >               "wORAbwDwTP" : 0.5294999673088226,
   >               "gVDzdhOSBq" : "NoCaxjBL"
   >             }
   >           ]
   >         },
   >         "dIjABsAxX" : {
   >           "fLgmkpSA" : -3895094984495233586,
   >           "QQvgyxaBxf" : "pBTNtZbE",
   >           "AvXLjdkf" : "SJpdFO",
   >           "AxcsHTVw" : "mUAlNZQuKc",
   >           "mFtZzzTZk" : {
   >             "hmxbMfMaJ" : 0.44229261635103667,
   >             "KLiWtSHG" : 0.08376628232822814
   >           }
   >         }
   >       }
   >     }
   >   },
   >   "fields" : {
   >     "ludWBUdufX" : [
   >       13250,
   >       -3815,
   >       16064,
   >       -6547,
   >       -21341
   >     ],
   >     "ykhUhH" : [
   >       -1933135152
   >     ],
   >     "HEc" : [
   >       0.9251104
   >     ],
   >     "nSiAKK" : [
   >       "x5ls74Gn5ISC3YTzpJyl7qug7q6tw6jsl5pDIu+BpAckxJrzopSLyaTwtr2P7qi5zKXylJCaEz3zgKOJDNi37qyB75C1CVzurrvuhKzxvIm115h675in0Yg=",
   >       "8Z2tqVTyqqi374626p+47qyNQA7JqdWd1oTzsoqB8bixodmzxanwqKCi47efQBLPie6YvdSk77uY6bmx856Boe+hh+yvpO+Nu3g=",
   >       "8LyGiH/guLHvq6/Tn+65pu+YuXbzn6usRuacudqiw6XunLZjw4I=",
   >       "3bruuYHxtKWU2YTugLHupqLZuOqpiMei7qix7omp35zxorut74uX7pKC3Y7qm6rytJC58aKfot2d75qy7qmCeuuksBjvjYl48LeboO63ouu1kg==",
   >       "4pyL2Z3ri5X0i7+ew7B+0aPyhIaP7omMLuyqhcSf4KWc7rCKw7/Wg+ORoe++onLknKTvmLrisK/yjKa/fei+p9KbOOGDryPvoJXCreWgoeavge2Cp9me6KaJUOW2h+6ovcqTd++sgtq2HHPmlYd1"
   >     ]
   >   }
   > }>
   > 	at __randomizedtesting.SeedInfo.seed([191A8C8BD80E0BF9:497347C58B44DF81]:0)
   > 	at org.elasticsearch.index.get.GetResultTests.testToAndFromXContentEmbedded(GetResultTests.java:110)
   > 	at java.lang.Thread.run(Thread.java:748)
  1> [2018-12-17T16:33:43,492][INFO ][o.e.i.g.GetResultTests   ] [testToXContent] before test
  1> [2018-12-17T16:33:43,495][INFO ][o.e.i.g.GetResultTests   ] [testToXContent] after test
  1> [2018-12-17T16:33:43,511][INFO ][o.e.i.g.GetResultTests   ] [testToXContentEmbedded] before test
  1> [2018-12-17T16:33:43,512][INFO ][o.e.i.g.GetResultTests   ] [testToXContentEmbedded] after test
Completed [213/1213] on J5 in 0.20s, 7 tests, 1 failure <<< FAILURES!
```

**Comment by bleskes** [comment]
I think this one is mine. Looking.

**Comment by bleskes** [comment]
so it turns this broke with https://github.com/elastic/elasticsearch/pull/36597 . It reproduces fairly easily. I'll reach out to discuss with @javanna

**Comment by javanna** [comment]
thanks for the ping @bleskes . I am going to open a PR also for the issue that was causing these failures to not repeat with the same seed.
