### ISSUE TITLE
Sudden data loss!

### ISSUE THREAD

**Issue by n1im** [elastic/elasticsearch#29139]
**Elasticsearch version**  : 5.6.8

**Plugins installed**: [] No plugins

**JVM version** (`java -version`): 8

**OS version** (`uname -a` if on a Unix-like system): Linux Centos 7

**Description of the problem including expected versus actual behavior**:

I have an elastic search cluster of 1 node in my environment. 

The cluster was running fine from months. 

Today all of a sudden I saw no data in the data directory.

Just like that.

We can't even know why did it happen

We did not take any backup or snapshots.

Is there anyway to recover the lost data?

**Provide logs (if relevant)**:

Elasticsearch logs:

`2018-03-18T20:55:32,950][WARN ][r.suppressed ] path: /_search/scroll, params: {pretty=}
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
at org.elasticsearch.action.search.SearchScrollAsyncAction.onShardFailure(SearchScrollAsyncAction.java:269) ~[elasticsearch-5.6.8.jar:5.6.8]
at org.elasticsearch.action.search.SearchScrollAsyncAction.run(SearchScrollAsyncAction.java:158) ~[elasticsearch-5.6.8.jar:5.6.8]
at org.elasticsearch.action.search.SearchScrollAsyncAction.lambda$run$0(SearchScrollAsyncAction.java:110) ~[elasticsearch-5.6.8.jar:5.6.8]
at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:59) ~[elasticsearch-5.6.8.jar:5.6.8]
[2018-03-18T21:27:40,709][INFO ][o.e.c.m.MetaDataDeleteIndexService] [nfc-server] [logstash-2018.02.26/nKlg0SZ-QSqj9hOdQQI9Gw] deleting index
[2018-03-18T21:27:40,710][INFO ][o.e.c.m.MetaDataDeleteIndexService] [nfc-server] [logstash-2018.03.09/gH4W1EwdQayWOJIa7vUXnw] deleting index
[2018-03-18T21:27:40,710][INFO ][o.e.c.m.MetaDataDeleteIndexService] [nfc-server] [logstash-2017.12.14/Dfz4TS4rTnG-q_FsBcEpIg] deleting index
[2018-03-18T21:27:40,710][INFO ][o.e.c.m.MetaDataDeleteIndexService] [nfc-server] [logstash-2017.12.07/bhhGQsF5TUmAYRa8gOTo_w] deleting index
[2018-03-18T21:27:40,710][INFO ][o.e.c.m.MetaDataDeleteIndexService] [nfc-server] [logstash-2018.01.16/VoxuRIUcSVm8H9Ycchsteg] deleting index
[2018-03-18T21:27:40,710][INFO ][o.e.c.m.MetaDataDeleteIndexService] [nfc-server] [logstash-2018.01.22/JwmOheLdQCCltcEpdubkcg] deleting index
[2018-03-18T21:27:40,710][INFO ][o.e.c.m.MetaDataDeleteIndexService] [nfc-server] [logstash-2017.09.14/Hln9N7ViRW-_OONI0sEt8Q] deleting index`

Kibana logs:

`Mar 18 21:27:56 localhost.localdomain kibana[4946]: {"type":"log","@timestamp":"2018-03-18T21:27:56Z","tags":["status","plugin:elasticsearch@5.6.8","error"],"pid":4946,"state":"red","message":"Status changed fro
m green to red - all shards failed: [search_phase_execution_exception] all shards failed","prevState":"green","prevMsg":"Kibana index ready"}
Mar 18 21:27:56 localhost.localdomain kibana[4946]: {"type":"log","@timestamp":"2018-03-18T21:27:56Z","tags":["status","ui settings","error"],"pid":4946,"state":"red","message":"Status changed from green to red 
- Elasticsearch plugin is red","prevState":"green","prevMsg":"Ready"}
Mar 18 21:28:11 localhost.localdomain kibana[4946]: {"type":"log","@timestamp":"2018-03-18T21:28:11Z","tags":["status","plugin:elasticsearch@5.6.8","info"],"pid":4946,"state":"yellow","message":"Status changed f
rom red to yellow - No existing Kibana index found","prevState":"red","prevMsg":"all shards failed: [search_phase_execution_exception] all shards failed"}
Mar 18 21:28:11 localhost.localdomain kibana[4946]: {"type":"log","@timestamp":"2018-03-18T21:28:11Z","tags":["status","ui settings","info"],"pid":4946,"state":"yellow","message":"Status changed from red to yell
ow - Elasticsearch plugin is yellow","prevState":"red","prevMsg":"Elasticsearch plugin is red"}
Mar 18 21:28:12 localhost.localdomain kibana[4946]: {"type":"log","@timestamp":"2018-03-18T21:28:12Z","tags":["status","plugin:elasticsearch@5.6.8","info"],"pid":4946,"state":"green","message":"Status changed fr
om yellow to green - Kibana index ready","prevState":"yellow","prevMsg":"No existing Kibana index found"}
Mar 18 21:28:12 localhost.localdomain kibana[4946]: {"type":"log","@timestamp":"2018-03-18T21:28:12Z","tags":["status","ui settings","info"],"pid":4946,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Elasticsearch plugin is yellow"}`

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

Here apparently "someone" asked to delete some indices:

```
[2018-03-18T21:27:40,709][INFO ][o.e.c.m.MetaDataDeleteIndexService] [nfc-server] [logstash-2018.02.26/nKlg0SZ-QSqj9hOdQQI9Gw] deleting index 
[2018-03-18T21:27:40,710][INFO ][o.e.c.m.MetaDataDeleteIndexService] [nfc-server] [logstash-2018.03.09/gH4W1EwdQayWOJIa7vUXnw] deleting index 
[2018-03-18T21:27:40,710][INFO ][o.e.c.m.MetaDataDeleteIndexService] [nfc-server] [logstash-2017.12.14/Dfz4TS4rTnG-q_FsBcEpIg] deleting index 
[2018-03-18T21:27:40,710][INFO ][o.e.c.m.MetaDataDeleteIndexService] [nfc-server] [logstash-2017.12.07/bhhGQsF5TUmAYRa8gOTo_w] deleting index 
[2018-03-18T21:27:40,710][INFO ][o.e.c.m.MetaDataDeleteIndexService] [nfc-server] [logstash-2018.01.16/VoxuRIUcSVm8H9Ycchsteg] deleting index 
[2018-03-18T21:27:40,710][INFO ][o.e.c.m.MetaDataDeleteIndexService] [nfc-server] [logstash-2018.01.22/JwmOheLdQCCltcEpdubkcg] deleting index 
[2018-03-18T21:27:40,710][INFO ][o.e.c.m.MetaDataDeleteIndexService] [nfc-server] [logstash-2017.09.14/Hln9N7ViRW-_OONI0sEt8Q] deleting index
```

**Comment by n1im** [comment]
Will do.
Is there a way to trace back to the someone who asked to delete ?

**Comment by dadoonet** [comment]
> Is there a way to trace back to the someone who asked to delete ?

X-Pack security (commercial plugin) helps to:

* prevent that
* have audit logging on who did what

But better to discuss that on discuss.elastic.co. Thanks
