### ISSUE TITLE
[CI] MasterDisruptionIT testMasterNodeGCs fails ocassionaly

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#29175]
Seen today:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=centos/824/console

and a couple of days ago:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.1+aggressive-opts/10/console

Not reproducable locally so far:
```
REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=43D04A6C4FBD8535 \
  -Dtests.class=org.elasticsearch.discovery.MasterDisruptionIT \
  -Dtests.method="testMasterNodeGCs" \
  -Dtests.security.manager=true \
  -Dtests.locale=be-BY \
  -Dtests.timezone=America/Mexico_City
```

There are several timeouts in the log:
```
16:59:22   1> [2018-03-20T10:57:57,522][WARN ][o.e.d.z.UnicastZenPing   ] [node_t2] failed to send ping to [{node_t1}{DeehtQA4Q9KLlM4Lx4rb6A}{wprQ7qShRSGl4wuP2invGg}{127.0.0.1}{127.0.0.1:30218}]
16:59:22   1> org.elasticsearch.transport.ReceiveTimeoutTransportException: [node_t1][127.0.0.1:30218][internal:discovery/zen/unicast] request_id [24] timed out after [3750ms]
16:59:22   1> 	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:981) [main/:?]
16:59:22   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573) [main/:?]
16:59:22   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
16:59:22   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
16:59:22   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
16:59:22   1> [2018-03-20T10:57:57,525][WARN ][o.e.d.z.UnicastZenPing   ] [node_t0] failed to send ping to [{node_t1}{DeehtQA4Q9KLlM4Lx4rb6A}{wprQ7qShRSGl4wuP2invGg}{127.0.0.1}{127.0.0.1:30218}]
16:59:22   1> org.elasticsearch.transport.ReceiveTimeoutTransportException: [node_t1][127.0.0.1:30218][internal:discovery/zen/unicast] request_id [24] timed out after [3755ms]
16:59:22   1> 	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:981) [main/:?]
16:59:22   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573) [main/:?]
16:59:22   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
16:59:22   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
16:59:22   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

Later I see this exception.
```
16:59:27 ERROR   35.4s J1 | MasterDisruptionIT.testMasterNodeGCs <<< FAILURES!
16:59:27    > Throwable #1: MasterNotDiscoveredException[null]
16:59:27    > 	at __randomizedtesting.SeedInfo.seed([43D04A6C4FBD8535:81B0F91CFAF0B415]:0)
16:59:27    > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:213)
16:59:27    > 	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:317)
16:59:27    > 	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:244)
16:59:27    > 	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:577)
16:59:27    > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573)
16:59:27    > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:59:27    > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:59:27    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bleskes** [comment]
sadly, we dropped the ball on this one and the logs are no longer available. Without them I don't think it's worthwhile to chase this one. I'm closing this. If it happens again, we'll reopen.

**Comment by gwbrown** [comment]
This failed today on 5.6: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+multijob-darwin-compatibility/272/

Logs are attached to prevent losing them again.
[272.txt](https://github.com/elastic/elasticsearch/files/2920319/272.txt)

**Comment by ywelsch** [comment]
given that this is 5.6 which will be EOL soon, I don't think it makes sense chasing that one down.
