### ISSUE TITLE
Grok pipeline definition parameter "pattern_definitions" cause the master node shut down

### ISSUE THREAD

**Issue by ivanjz93** [elastic/elasticsearch#29257]
When I use the api to define an pipeline like this:
`
{
  "processors" : [
    {
      "grok" : {
        "field": "message",
        "patterns": ["..."],
        "pattern_definitions":{
        	"JAVACLASS":"\\s*%{JAVACLASS}
        }
      }
    }
  ]
}`

Note the "pattern_definitions" parameter, I use the old value of "JAVACLASS" pattern  to overwrite JAVACLASS. It cause the master node shut down.

Maybe it is not a correct operate to define a customer pattern like this, but master node shut down immediately is a problem.

**Comment by martijnvg** [comment]
Hey @ivanjz93 I tried to reproduce it here locally, but here the put pipeline api did not fail.
Can you provide all the exact commands to lead to the master node shutdown? Provide any errors you saw in the log? Also what version of ES are you using?

**Comment by ivanjz93** [comment]
Hi, @martijnvg.

The version is 6.2.3.

The command like this:
`PUT _ingest/pipeline/log-filebeat-pipeline
{
  "description" : "extract structured log information",
  "processors" : [
    {
      "grok" : {
        "field": "message",
        "patterns": ["%{TIMESTAMP_ISO8601:time} %{THREADNAME:thread_name} %{LOGLEVEL:level} %{JAVACLASS:class} %{JAVASTACKTRACEPART1:stracktrace} %{JAVALOGMESSAGE:content}"],
        "pattern_definitions":{
        	"THREADNAME":"\\[%{WORD}\\]\\s*",
        	"JAVACLASS":"\\s*%{JAVACLASS}",
        	"JAVASTACKTRACEPART1": "%{JAVACLASS}\\.%{WORD}\\(%{JAVAFILE:file}:%{NUMBER:line}\\):"
        }
      }
    }
  ]
}`
And the error log is (omit many same lines in the end)

> java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[?:?]
[2018-03-26T11:58:00,909][INFO ][o.e.c.r.a.AllocationService] [es-1] Cluster health status changed from [GREEN] to [YELLOW] (reason: [{es-2}{7GdKsmEUT9-g-h8KYwd3_g}{imnenS_cQ2aRO-V7mdJgCQ}{nn1-ha}{172.16.0.21:9300} transport disconnected]).
[2018-03-26T11:57:59,791][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [es-1] fatal error in thread [Thread-6], exiting
java.lang.StackOverflowError: null
	at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3799) ~[?:1.8.0_161]
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660) ~[?:1.8.0_161]
	at java.util.regex.Pattern$Branch.match(Pattern.java:4606) ~[?:1.8.0_161]
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604) ~[?:1.8.0_161]
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604) ~[?:1.8.0_161]
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4570) ~[?:1.8.0_161]
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4719) ~[?:1.8.0_161]
	at java.util.regex.Pattern$Curly.match0(Pattern.java:4281) ~[?:1.8.0_161]
	at java.util.regex.Pattern$Curly.match(Pattern.java:4236) ~[?:1.8.0_161]
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4660) ~[?:1.8.0_161]
	at java.util.regex.Pattern$Branch.match(Pattern.java:4606) ~[?:1.8.0_161]
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604) ~[?:1.8.0_161]
	at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3800) ~[?:1.8.0_161]
	at java.util.regex.Pattern$Start.match(Pattern.java:3463) ~[?:1.8.0_161]
	at java.util.regex.Matcher.search(Matcher.java:1248) ~[?:1.8.0_161]
	at java.util.regex.Matcher.find(Matcher.java:664) ~[?:1.8.0_161]
	at java.util.Formatter.parse(Formatter.java:2549) ~[?:1.8.0_161]
	at java.util.Formatter.format(Formatter.java:2501) ~[?:1.8.0_161]
	at java.util.Formatter.format(Formatter.java:2455) ~[?:1.8.0_161]
	at java.lang.String.format(String.java:2981) ~[?:1.8.0_161]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:122) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]
	at org.elasticsearch.ingest.common.Grok.toRegex(Grok.java:127) ~[?:?]

**Comment by martijnvg** [comment]
@ivanjz93 Thanks, my node died here too. I'll look into how to fix this.
