### ISSUE TITLE
[CI] CompositeValuesCollectorQueueTests.testRandomDoubleAndLong

### ISSUE THREAD

**Issue by andyb-elastic** [elastic/elasticsearch#29269]
On 6.x. This reproduces

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/844/console

[build-844.txt](https://github.com/elastic/elasticsearch/files/1853135/build-844.txt)

```
REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=96D08ABDE6FE249A -Dtests.class=org.elasticsearch.search.aggregations.bucket.composite.CompositeValuesCollectorQueueTests -Dtests.method="testRandomDoubleAndLong" -Dtests.security.manager=true -Dtests.locale=ar-LB -Dtests.timezone=Chile/EasterIsland
```

```
ERROR   0.61s J1 | CompositeValuesCollectorQueueTests.testRandomDoubleAndLong <<< FAILURES!
   > Throwable #1: java.lang.NullPointerException
   >    at __randomizedtesting.SeedInfo.seed([96D08ABDE6FE249A:7D70A6EB56765BD2]:0)
   >    at org.elasticsearch.index.fielddata.SortableLongBitsToSortedNumericDoubleValues.advanceExact(SortableLongBitsToSortedNumericDoubleValues.java:42)
   >    at org.elasticsearch.search.aggregations.bucket.composite.DoubleValuesSource$1.collect(DoubleValuesSource.java:95)
   >    at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:82)
   >    at org.elasticsearch.search.aggregations.bucket.composite.CompositeValuesCollectorQueueTests.testRandomCase(CompositeValuesCollectorQueueTests.java:264)
   >    at org.elasticsearch.search.aggregations.bucket.composite.CompositeValuesCollectorQueueTests.testRandomCase(CompositeValuesCollectorQueueTests.java:136)
   >    at org.elasticsearch.search.aggregations.bucket.composite.CompositeValuesCollectorQueueTests.testRandomDoubleAndLong(CompositeValuesCollectorQueueTests.java:79)
   >    at java.lang.Thread.run(Thread.java:748)
   >    Suppressed: java.lang.RuntimeException: MockDirectoryWrapper: cannot close: there are still 10 open files: {_1_Lucene70_0.dvd=1, _0_Lucene70_0.dvd=1, _2_Lucene70_0.dvd=1, _2.fdt=1, _1.dim=1, _0.dim=1, _3.fdt=1, _2.dim=1, _0.fdt=1, _1.fdt=1}
   >            at org.apache.lucene.store.MockDirectoryWrapper.close(MockDirectoryWrapper.java:841)
   >            at org.elasticsearch.search.aggregations.bucket.composite.CompositeValuesCollectorQueueTests.$closeResource(CompositeValuesCollectorQueueTests.java:280)
   >            at org.elasticsearch.search.aggregations.bucket.composite.CompositeValuesCollectorQueueTests.testRandomCase(CompositeValuesCollectorQueueTests.java:280)
   >            ... 39 more
   >    Caused by: java.lang.RuntimeException: unclosed IndexInput: _3.fdt
   >            at org.apache.lucene.store.MockDirectoryWrapper.addFileHandle(MockDirectoryWrapper.java:732)
   >            at org.apache.lucene.store.MockDirectoryWrapper.openInput(MockDirectoryWrapper.java:776)
   >            at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader.<init>(CompressingStoredFieldsReader.java:150)
   >            at org.apache.lucene.codecs.compressing.CompressingStoredFieldsFormat.fieldsReader(CompressingStoredFieldsFormat.java:121)
   >            at org.apache.lucene.codecs.lucene50.Lucene50StoredFieldsFormat.fieldsReader(Lucene50StoredFieldsFormat.java:173)
   >            at org.apache.lucene.codecs.asserting.AssertingStoredFieldsFormat.fieldsReader(AssertingStoredFieldsFormat.java:43)
   >            at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:125)
   >            at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:78)
   >            at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:64)
   >            at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:56)
   >            at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:675)
   >            at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:79)
   >            at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:63)
   >            at org.elasticsearch.search.aggregations.bucket.composite.CompositeValuesCollectorQueueTests.testRandomCase(CompositeValuesCollectorQueueTests.java:206)
   >            ... 39 more
```

**Comment by jimczi** [comment]
Thanks @andyb-elastic
