### ISSUE TITLE
[CI] SnapshotShardsServiceIT.testRetryPostingSnapshotStatusMessages

### ISSUE THREAD

**Issue by andyb-elastic** [elastic/elasticsearch#29270]
Does not reproduce

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/845/console

[build-845.txt](https://github.com/elastic/elasticsearch/files/1853256/build-845.txt)

```
REPRODUCE WITH: ./gradlew :server:integTest -Dtests.seed=9F5B75498AD2386A -Dtests.class=org.elasticsearch.snapshots.SnapshotShardsServiceIT -Dtests.method="testRetryPostingSnapshotStatusMessages" -Dtests.security.manager=true -Dtests.locale=ar-SD -Dtests.timezone=America/Coral_Harbour
```

```
ERROR   14.6s J2 | SnapshotShardsServiceIT.testRetryPostingSnapshotStatusMessages <<< FAILURES!
   > Throwable #1: java.lang.AssertionError:
   > Expected: every item is <DONE>
   >      but: an item was <STARTED>
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.snapshots.SnapshotShardsServiceIT.lambda$testRetryPostingSnapshotStatusMessages$1(SnapshotShardsServiceIT.java:98)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:734)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:708)
   >    at org.elasticsearch.snapshots.SnapshotShardsServiceIT.testRetryPostingSnapshotStatusMessages(SnapshotShardsServiceIT.java:93)
   >    at java.lang.Thread.run(Thread.java:748)
```

**Comment by tlrx** [comment]
On slow machines this test might require more than 10 secs for the snapshot to complete. I increased the assertBusy loop to 30s in https://github.com/elastic/elasticsearch/commit/ae2a9f710850a2cc892dc2110776eae9bd1dc75d.

**Comment by original-brownbear** [comment]
The failure here was just in `6.x` which was missing the increased timeout. I cherry-picked the 30s timeouts to `6.x` in 41dd1f4ec80  :)
