### ISSUE TITLE
install x-pack for elasticsearch 6.2.3 incompatible with version 6.2.2

### ISSUE THREAD

**Issue by clemensloebig** [elastic/elasticsearch#29346]
After upgrading elasticsearch from 6.2.2 to 6.2.3
try to install elasticsearch X-Pack with 

```
/usr/share/elasticsearch/bin/elasticsearch-plugin install x-pack
```

Output:

```
-> Downloading x-pack from elastic
[=================================================] 100%  
Exception in thread "main" java.lang.IllegalArgumentException: plugin [ingest-user-agent] is incompatible with version [6.2.3]; was designed for version [6.2.2]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:237)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:349)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:328)
        at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:600)
        at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:588)
        at org.elasticsearch.plugins.InstallPluginCommand.installMetaPlugin(InstallPluginCommand.java:667)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:621)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:223)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)

```

also not working with:

```
 wget https://artifacts.elastic.co/downloads/packs/x-pack/x-pack-6.2.3.zip
/usr/share/elasticsearch/bin/elasticsearch-plugin install file:///x-pack-6.2.3.zip

-> Downloading file:///home/User/x-pack-6.2.3.zip
[=================================================] 100%  
Exception in thread "main" java.lang.IllegalArgumentException: plugin [ingest-user-agent] is incompatible with version [6.2.3]; was designed for version [6.2.2]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:237)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:349)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:328)
        at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:600)
        at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:588)
        at org.elasticsearch.plugins.InstallPluginCommand.installMetaPlugin(InstallPluginCommand.java:667)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:621)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:223)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)

```

**Elasticsearch version** (`bin/elasticsearch --version`):
6.2.3

**Plugins installed**: []
x-pack

**JVM version** (`java -version`):
java version "1.8.0_161

**OS version** (`uname -a` if on a Unix-like system):
Linux 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tvernum** [comment]
@clemensloebig 
The error you are getting is for the `ingest-user-agent` plugin, not for x-pack.

The upgrade process needs to be:
- remove all plugins
- install required plugins.

You cannot do each plugin one-by-one.

**Comment by clemensloebig** [comment]
yes i removed all plugins than tried with:

```
/usr/share/elasticsearch/bin/elasticsearch-plugin install x-pa
```

and the Output was:

```
-> Downloading x-pack from elastic
[=================================================] 100%  
Exception in thread "main" java.lang.IllegalArgumentException: plugin [ingest-user-agent] is incompatible with version [6.2.3]; was designed for version [6.2.2]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:237)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:349)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:328)
        at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:600)
        at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:588)
        at org.elasticsearch.plugins.InstallPluginCommand.installMetaPlugin(InstallPluginCommand.java:667)
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:621)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:223)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)

```

**Comment by clemensloebig** [comment]
I found the issue, there was another installed like "ingest-user-agent", after i removed the plugin also, i can install x-pack

But the Error Message should be more clear, like
"There is another Plugin installed that is incompatible with this Version of Elasticsearch"
