### ISSUE TITLE
ES use 100% cpu resource due to same spacial query

### ISSUE THREAD

**Issue by showmeall** [elastic/elasticsearch#29352]
**Describe the feature**:   our es just have one node, and it is dead sometimes,  we can see there have a lot of tasks when check  http://localhost:9200/_tasks?pretty&detailed , it will continual  a few hours，in this time we can not connected the ES,  the CPU is used above 100%. we think some spacial query make this happen,  like : +<a+href="/taodns/domain/"> , do you have any solution for this problem?

**Elasticsearch version** (`bin/elasticsearch --version`): 2.4.0

**Plugins installed**: [head] 

**JVM version** (`java -version`): 1.8.0

**OS version** (`uname -a` if on a Unix-like system): centos 7.2

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. server hardware , CPU E5-2630 v3 @ 2.40GHz, 128G memory
 2. 32 G for ES
 3. ES settting

threadpool.bulk.type: fixed
threadpool.bulk.size: 16
threadpool.bulk.queue_size: 1000

threadpool.index.type: fixed
threadpool.index.size: 32
threadpool.index.queue_size: 1000

threadpool.search.type: fixed
threadpool.search.size: 49
threadpool.search.queue_size: 3000

4. cpu info
![image](https://user-images.githubusercontent.com/24838796/38251390-e2ec10da-3783-11e8-88d0-e32f23d18a4f.png)

**Provide logs (if relevant)**:
[2018-04-03 20:51:19,742][DEBUG][action.search            ] [es-node-100] [75232] Failed to execute fetch phase
RemoteTransportException[[es-node-100][10.10.10.10:9300][indices:data/read/search[phase/fetch/id]]]; nested: EsRejectedExecutionException[rejected execution of org.elasticsearch.transport.TransportService$4@40b5cfcb on EsThreadPoolExecutor[search, queue capacity = 3000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@1732bdf2[Running, pool size = 49, active threads = 49, queued tasks = 3000, completed tasks = 113941]]];
Caused by: EsRejectedExecutionException[rejected execution of org.elasticsearch.transport.TransportService$4@40b5cfcb on EsThreadPoolExecutor[search, queue capacity = 3000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@1732bdf2[Running, pool size = 49, active threads = 49, queued tasks = 3000, completed tasks = 113941]]]
        at org.elasticsearch.common.util.concurrent.EsAbortPolicy.rejectedExecution(EsAbortPolicy.java:50)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
        at org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor.execute(EsThreadPoolExecutor.java:85)
        at org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:372)
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:327)
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:299)
        at org.elasticsearch.search.action.SearchServiceTransportAction.sendExecuteFetch(SearchServiceTransportAction.java:204)
        at org.elasticsearch.search.action.SearchServiceTransportAction.sendExecuteFetch(SearchServiceTransportAction.java:196)
        at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction.executeFetch(SearchQueryThenFetchAsyncAction.java:94)
        at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction.moveToSecondPhase(SearchQueryThenFetchAsyncAction.java:88)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.innerMoveToSecondPhase(AbstractSearchAsyncAction.java:374)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:171)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onResponse(AbstractSearchAsyncAction.java:147)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onResponse(AbstractSearchAsyncAction.java:144)
        at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:41)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:836)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:820)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:810)
        at org.elasticsearch.transport.DelegatingTransportChannel.sendResponse(DelegatingTransportChannel.java:58)
        at org.elasticsearch.transport.RequestHandlerRegistry$TransportChannelWrapper.sendResponse(RequestHandlerRegistry.java:140)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:369)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by showmeall** [comment]
and we can not cancel tasks ,use curl -XPOST '10.10.10.10:9200/_tasks/_cancel?node_id=A3VEFscYSbioibfJHwnUuQ&actions=*search&pretty'

**Comment by romseygeek** [comment]
Hi @showmeall, we try to reserve github issues for enhancement requests or bug reports.  Things like performance issues are better discussed on our forums at https://discuss.elastic.co - I hope you don't mind if I close this.
