### ISSUE TITLE
QueryAnalyzerTests failing since recent commit

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#29363]
This is from another PR CI failure:

```
REPRODUCE WITH: ./gradlew :modules:percolator:test -Dtests.seed=56E400870DFCE81C -Dtests.class=org.elasticsearch.percolator.QueryAnalyzerTests -Dtests.method="testExactMatch_booleanQuery" -Dtests.security.manager=true -Dtests.locale=zh-HK -Dtests.timezone=America/Argentina/Catamarca
FAILURE 0.09s | QueryAnalyzerTests.testExactMatch_booleanQuery <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: msm is at least two so result.minimumShouldMatch should 2 too
   > Expected: <2>
   >      but: was <1>
   >    at __randomizedtesting.SeedInfo.seed([56E400870DFCE81C:3EFE623A852957C5]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.percolator.QueryAnalyzerTests.testExactMatch_booleanQuery(QueryAnalyzerTests.java:426)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
  2> NOTE: leaving temporary files on disk at: /home/jason/src/elastic/elasticsearch/modules/percolator/build/testrun/test/J0/temp/org.elasticsearch.percolator.QueryAnalyzerTests_56E400870DFCE81C-001
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=395, maxMBSortInHeap=7.800278966437485, sim=RandomSimilarity(queryNorm=false): {}, locale=zh-HK, timezone=America/Argentina/Catamarca
  2> NOTE: Linux 4.15.13-300.fc27.x86_64 amd64/Oracle Corporation 10 (64-bit)/cpus=20,threads=1,free=509509512,total=536870912
  2> NOTE: All tests run in this JVM: [QueryAnalyzerTests]
Completed [1/1] in 0.69s, 1 test, 1 failure <<< FAILURES!
```

From `git bisect`, it looks like the culprit is:

```
05:37:27 3d [jason@totoro:~/src/elastic/elasticsearch] dc1c16964a+ ± git bisect good
8cdd950056b722e7086f48fb84cf6c29ccf31bd3 is the first bad commit
commit 8cdd950056b722e7086f48fb84cf6c29ccf31bd3
Author: Adrien Grand <jpountz@gmail.com>
Date:   Tue Apr 3 16:44:26 2018 +0200

    Fix some query extraction bugs. (#29283)
    
    While playing with the percolator I found two bugs:
     - Sometimes we set a min_should_match that is greater than the number of
       extractions. While this doesn't cause direct trouble, it does when the query
       is nested into a boolean query and the boolean query tries to compute the
       min_should_match for the entire query based on its own min_should_match and
       those of the sub queries. So I changed the code to throw an exception when
       min_should_match is greater than the number of extractions.
     - Boolean queries claim matches are verified when in fact they shouldn't. This
       is due to the fact that boolean queries assume that they are verified if all
       sub clauses are verified but things are more complex than that, eg.
       conjunctions that are nested in a disjunction or disjunctions that are nested
       in a conjunction can generally not be verified without running the query.

:040000 040000 bf10fc4198e43c17d96bf55329f397a91f3f72b1 ad69b9119d00655673aae59b72139d986bd00ab1 M	modules
```

**Comment by jasontedor** [comment]
I pushed a19fd5636b8062abd7daf543539ae34aa0281ef1.

**Comment by jasontedor** [comment]
To be clear, the above commit is to mark the test as needing a fix.

**Comment by jpountz** [comment]
Thanks @jasontedor!
