### ISSUE TITLE
[CI] QueryBuilderBWCIT#testQueryBuilderBWC fails

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#29376]
The test `QueryBuilderBWCIT#testQueryBuilderBWC` started failing recently. The query returns no hit while we expect at least one.

```
ERROR   1.55s | QueryBuilderBWCIT.testQueryBuilderBWC <<< FAILURES!
   > Throwable #1: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
   > 	at __randomizedtesting.SeedInfo.seed([6066C9849A19CFA1:63FA254773B6ACB1]:0)
   > 	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
   > 	at java.util.ArrayList.get(ArrayList.java:433)
   > 	at org.elasticsearch.bwc.QueryBuilderBWCIT.testQueryBuilderBWC(QueryBuilderBWCIT.java:211)
   > 	at java.lang.Thread.run(Thread.java:748)
```

I can reproduce this locally.

```
./gradlew :qa:query-builder-bwc:v6.0.0#upgradedQueryBuilderTestRunner \
  -Dtests.seed=F37C3D6E1E51335C \
  -Dtests.class=org.elasticsearch.bwc.QueryBuilderBWCIT \
  -Dtests.method="testQueryBuilderBWC" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-SV \
  -Dtests.timezone=America/Miquelon
```

Looks like that the test started failing since the commit `8cdd950056b722e7086f48fb84cf6c29ccf31bd3`.

**Comment by jpountz** [comment]
I disabled the query that triggers this failure and will work on a fix tomorrow. This highlighted an actual bug.
