### ISSUE TITLE
[CI] CandidateQueryTests#testDuel failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#29393]
```
   > Expected: <829L>
   >      but: was <828L>
   >    at __randomizedtesting.SeedInfo.seed([4066BC2B6E5FC61C:CE6062B30D75E0E]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.percolator.CandidateQueryTests.duelRun(CandidateQueryTests.java:874)
   >    at org.elasticsearch.percolator.CandidateQueryTests.testDuel(CandidateQueryTests.java:264)
```

Reproduces on 6.x and master branches:
```
./gradlew :modules:percolator:test \
  -Dtests.seed=4066BC2B6E5FC61C \
  -Dtests.class=org.elasticsearch.percolator.CandidateQueryTests \
  -Dtests.method="testDuel" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-EA \
  -Dtests.timezone=Asia/Vladivostok
```

**Comment by jpountz** [comment]
We looked into it with @martijnvg, this is a bug in the handling of `minimum_should_match` when the query mixes term and range queries. The query that triggers this failure is `((#unknown_field:zeSEYxqF) -unknown_field:bOQpDgol int_field:[495376381 TO 495376381] int_field:[949349031 TO 949349031])~2`.
