### ISSUE TITLE
[CI] TranslogTests#testFatalIOExceptionsWhileWritingConcurrently failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#29390]
A reproducible failure with an assertion error
```
FAILURE 0.42s | TranslogTests.testFatalIOExceptionsWhileWritingConcurrently <<< FAILURES!
   > Throwable #1: java.lang.AssertionError
   >    at __randomizedtesting.SeedInfo.seed([4E4569681BD5E1BB:198DEEA7190343F8]:0)
   >    at org.elasticsearch.index.translog.TranslogTests.testFatalIOExceptionsWhileWritingConcurrently(TranslogTests.java:1872)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
```

```
./gradlew :server:test \
  -Dtests.seed=4E4569681BD5E1BB \
  -Dtests.class=org.elasticsearch.index.translog.TranslogTests \
  -Dtests.method="testFatalIOExceptionsWhileWritingConcurrently" \
  -Dtests.security.manager=true \
  -Dtests.locale=it-IT \
  -Dtests.timezone=America/Martinique
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/1896/console

**Comment by jasontedor** [comment]
This one is caused by #29264.

**Comment by jasontedor** [comment]
I opened #29401.
