### ISSUE TITLE
[CI] testEnsureWeReconnect fails recently

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#29547]
`RemoteClusterClientTests#testEnsureWeReconnect` fails recently but is not reproducible locally.

```
   > 	at org.elasticsearch.transport.RemoteClusterClientTests.lambda$testEnsureWeReconnect$1(RemoteClusterClientTests.java:85)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:751)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:725)
   > 	at org.elasticsearch.transport.RemoteClusterClientTests.testEnsureWeReconnect(RemoteClusterClientTests.java:85)
   > 	at java.lang.Thread.run(Thread.java:748)
   > 	Suppressed: java.lang.AssertionError
   > 		at org.elasticsearch.transport.RemoteClusterClientTests.lambda$testEnsureWeReconnect$1(RemoteClusterClientTests.java:85)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:739)
   > 		... 39 more
```

Some instances:

1. https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/2320/console

2. https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=amazon/945/console

**Comment by dnhatn** [comment]
I muted the test in fd161d2659429a48e64fe5253ed40f3bfd0ad991
