### ISSUE TITLE
ElasticsearchStatusException[Elasticsearch exception [type=illegal_argument_exception, reason=request [/es_test/test/_search] contains unrecognized parameters: [batched_reduce_size], [typed_keys]]]

### ISSUE THREAD

**Issue by kervin521** [elastic/elasticsearch#29551]
I use elasticsearch-rest-high-level-client to access elasticsearch Search API.
It has no problem in elasticsearch 5.4.1, but the below error occurs against elasticsearch 5.3.0 when executing this snippet.

```
SearchSourceBuilder search = new SearchSourceBuilder();
		search.query(boolquery);
		search.from((pageNo-1)*pageSize);
		search.size(pageSize);
		search.explain(false);
		SearchRequest request = new SearchRequest();
		request.searchType(SearchType.DFS_QUERY_THEN_FETCH);
		request.source(search);
		request.indices(indexs.split(","));
		request.types(types.split(","));
		SearchResponse response = client.search(request);
```

```
ElasticsearchStatusException[Elasticsearch exception [type=illegal_argument_exception, reason=request [/es_test/test/_search] contains unrecognized parameters: [batched_reduce_size], [typed_keys]]]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177)
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:526)
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:502)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:409)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:382)
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:323)
	at com.ucloudlink.css.elasticsearch.api.HighRestElasticsearch.selectMatchAll(HighRestElasticsearch.java:511)
	at com.ucloudlink.css.elasticsearch.ElasticsearchRestTest.read21(ElasticsearchRestTest.java:86)
	at com.ucloudlink.css.elasticsearch.ElasticsearchRestTest.main(ElasticsearchRestTest.java:135)
	Suppressed: org.elasticsearch.client.ResponseException: GET http://localhost:9200/es_test/test/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&search_type=dfs_query_then_fetch&batched_reduce_size=512: HTTP/1.1 400 Bad Request
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/es_test/test/_search] contains unrecognized parameters: [batched_reduce_size], [typed_keys]"}],"type":"illegal_argument_exception","reason":"request [/es_test/test/_search] contains unrecognized parameters: [batched_reduce_size], [typed_keys]"},"status":400}
		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:354)
		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:343)
		at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
		at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
		at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
		at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
		at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
		at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
		at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
		at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
		at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
		at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
		at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
		at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
		at java.lang.Thread.run(Thread.java:748)
```

**Comment by kervin521** [comment]
elasticsearch 5.3.0

**Comment by javanna** [comment]
hi @kervin521 thanks for opening this issue. The stacktrace is pretty clear to me having worked on the high-level REST client, but would you mind please editing the description to make it a bit more human readable, so that everybody understands where the error comes from, how to trigger it etc.? Thank you!

**Comment by kervin521** [comment]
elasticsearch : 5.3.0
elasticsearch-rest-high-level-client:5.6.0

I use elasticsearch-rest-high-level-client to access elasticsearch Search API.
It has no problem in elasticsearch 5.4.1,but it has occurred above error in elasticsearch 5.3.0

                       SearchSourceBuilder search = new SearchSourceBuilder();
			search.query(boolquery);
			search.from((pageNo-1)*pageSize);
			search.size(pageSize);
			search.explain(false);
			SearchRequest request = new SearchRequest();
			request.searchType(SearchType.DFS_QUERY_THEN_FETCH);
			request.source(search);
			request.indices(indexs.split(","));
			request.types(types.split(","));
			SearchResponse response = client.search(request);

**Comment by javanna** [comment]
thanks @kervin521 I edited the description of the issue and added your info. 

From our [docs](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/5.6/java-rest-high-compatibility.html): "The 5.6 client can communicate with any 5.6.x Elasticsearch node. Previous 5.x minor versions like 5.5.x, 5.4.x etc. are not (fully) supported."

The 5.6 client sends all the parameters that Elasticsearch 5.6 supports, hence some parameters may not be recognized by earlier versions of Elasticsearch. Unfortunately there isn't even a work-around here as the parameter is always sent, the conclusion here is that the Search API cannot be used with 5.3 or earlier versions. We don't consider this a bug though as we never meant to support earlier versions than 5.6 when implementing the high-level REST client.
