### ISSUE TITLE
[CI] FullClusterRestartIT.testNewReplicasWork failed for 6.x 

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#29557]
Link to build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/946/console

Reproduce:

```
REPRODUCE WITH: ./gradlew :qa:full-cluster-restart:v6.2.4-SNAPSHOT#oldClusterTestRunner -Dtests.seed=81C8D63494D3BA1A -Dtests.class=org.elasticsearch.upgrades.FullClusterRestartIT -Dtests.method="testNewReplicasWork" -Dtests.security.manager=true -Dtests.locale=es-UY -Dtests.timezone=US/Alaska
```

Failure:

```
ERROR    696s | FullClusterRestartIT.testNewReplicasWork <<< FAILURES!
10:30:10    > Throwable #1: java.lang.Exception: Test abandoned because suite timeout was reached.
10:30:10   2> 	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
10:30:10   2> 	- locked sun.nio.ch.Util$3@39c1d877
10:30:10    > 	at __randomizedtesting.SeedInfo.seed([81C8D63494D3BA1A]:0)
10:30:10   1> [2018-04-17T02:30:08,756][INFO ][o.e.u.FullClusterRestartIT] [testNewReplicasWork]: after test
10:30:10   2> 	- locked java.util.Collections$UnmodifiableSet@45f17477
10:30:10   2> 	- locked sun.nio.ch.KQueueSelectorImpl@576278e8
10:30:10   1> [2018-04-17T02:30:08,771][ERROR][o.a.h.i.n.c.InternalHttpAsyncClient] I/O reactor terminated abnormally
10:30:10   1> java.io.InterruptedIOException: null
10:30:10   2> 	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
10:30:10   2> 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:255)
10:30:10   1> 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.doShutdown(AbstractMultiworkerIOReactor.java:462) ~[httpcore-nio-4.4.5.jar:4.4.5]
10:30:10   2> 	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
10:30:10   2> 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
10:30:10   2> 	at java.lang.Thread.run(Thread.java:748)
10:30:10   1> 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:374) ~[httpcore-nio-4.4.5.jar:4.4.5]
10:30:10   2> "I/O dispatcher 5" ID=20 RUNNABLE (in native code)
10:30:10   2> 	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
10:30:10   1> 	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192) ~[httpasyncclient-4.1.2.jar:4.1.2]
10:30:10   1> 	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) [httpasyncclient-4.1.2.jar:4.1.2]
10:30:10   2> 	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
10:30:10   2> 	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
10:30:10   2> 	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
10:30:10   2> 	- locked sun.nio.ch.Util$3@6f634178
10:30:10   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
10:30:10   2> 	- locked java.util.Collections$UnmodifiableSet@58d62e83
10:30:10   2> 	- locked sun.nio.ch.KQueueSelectorImpl@16caab22
10:30:10   2> 	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
10:30:10   1> [2018-04-17T02:30:09,320][ERROR][o.a.h.i.n.c.InternalHttpAsyncClient] I/O reactor terminated abnormally
10:30:10   1> java.io.InterruptedIOException: null
```

Could not reproduce locally.

**Comment by dimitris-athanasiou** [comment]
More timeouts in: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/1959/console. Probably related.

**Comment by dimitris-athanasiou** [comment]
And another: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/1960/console

**Comment by romseygeek** [comment]
More failures:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/1967/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/955/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/956/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/1969/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/957/console

This seems to be failing every time on the multijob tests, so I'll mute it.

**Comment by jasontedor** [comment]
The problem appears to be the hardware, it’s underpowered. I don’t think muting will help, I think another test will end up timing out. We are working on provisioning new hardware and should pull these machines from the rotation in the meantime. Muting though would silence this on every other platform where the test is fine.

**Comment by romseygeek** [comment]
Thanks @jasontedor .  Is there an infra ticket that I can link this to?

**Comment by bleskes** [comment]
I believe this is the issue: https://github.com/elastic/infra/issues/4620 . Closing.
