### ISSUE TITLE
IllegalArgumentException: cannot set discovery.zen.minimum_master_nodes to more than the current master nodes count [1]

### ISSUE THREAD

**Issue by wuyunfeng** [elastic/elasticsearch#29573]
**Describe the feature**:failed to apply cluster settings
java.lang.IllegalArgumentException: can't update [discovery.zen.minimum_master_nodes] from [1] to [2]

**Elasticsearch version** (`bin/elasticsearch --version`):5.5.0

**Plugins installed**: [ik]

**JVM version** (`java -version`):JDK 1.8

**OS version** (`uname -a` if on a Unix-like system): Centos7.2

**Description of the problem including expected versus actual behavior**: enlarge elasticsearch one node to two node failure
Expected: We do not hope modify the `unicast.hosts` list manually to build the cluster
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. We start a single Elasticsearch Node A, configure the discovery.zen.ping.unicast.hosts: NodeA:port
 2. Start another Elasticsearch Node B,configure the discovery.zen.ping.unicast.hosts: NodeA:port,NodeB:port
 3. Dynamically update cluster setting:discovery.zen.minimum_master_nodes from 1 to 2
 4. restart the Node A, Node A elect self to master and throw java.lang.IllegalArgumentException: cannot set discovery.zen.minimum_master_nodes to more than the current master nodes count [1]
 

**Provide logs (if relevant)**:
[2018-04-18T09:51:47,747][WARN ][o.e.c.s.ClusterSettings  ] [B-i9l9Q] failed to apply settings
java.lang.IllegalArgumentException: illegal value can't update [discovery.zen.minimum_master_nodes] from [1] to [2]
	at org.elasticsearch.common.settings.Setting$Updater.getValue(Setting.java:610) ~[baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater.updater(AbstractScopedSettings.java:344) ~[baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:164) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.ClusterService.publishAndApplyChanges(ClusterService.java:761) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:587) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.run(ClusterService.java:263) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) [baidu-elasticsearch-5.5.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: cannot set discovery.zen.minimum_master_nodes to more than the current master nodes count [1]
	at org.elasticsearch.discovery.zen.ZenDiscovery.lambda$new$2(ZenDiscovery.java:187) ~[baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.settings.Setting$Updater.getValue(Setting.java:608) ~[baidu-elasticsearch-5.5.0.jar:?]
	... 13 more
[2018-04-18T09:51:47,748][WARN ][o.e.c.s.ClusterService   ] [B-i9l9Q] failed to apply cluster settings
java.lang.IllegalArgumentException: illegal value can't update [discovery.zen.minimum_master_nodes] from [1] to [2]
	at org.elasticsearch.common.settings.Setting$Updater.getValue(Setting.java:610) ~[baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater.updater(AbstractScopedSettings.java:344) ~[baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:164) ~[baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.ClusterService.publishAndApplyChanges(ClusterService.java:761) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:587) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.run(ClusterService.java:263) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) [baidu-elasticsearch-5.5.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: cannot set discovery.zen.minimum_master_nodes to more than the current master nodes count [1]
	at org.elasticsearch.discovery.zen.ZenDiscovery.lambda$new$2(ZenDiscovery.java:187) ~[baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.settings.Setting$Updater.getValue(Setting.java:608) ~[baidu-elasticsearch-5.5.0.jar:?]
	... 13 more
[2018-04-18T09:51:47,771][WARN ][o.e.c.s.ClusterSettings  ] [B-i9l9Q] failed to prepareCommit settings for [Updater for: {
  "key" : "discovery.zen.minimum_master_nodes",
  "properties" : [
    "Dynamic",
    "NodeScope"
  ],
  "is_group_setting" : false,
  "default" : "-1"
}]
java.lang.IllegalArgumentException: illegal value can't update [discovery.zen.minimum_master_nodes] from [1] to [2]
	at org.elasticsearch.common.settings.Setting$Updater.getValue(Setting.java:610) ~[baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater.updater(AbstractScopedSettings.java:344) ~[baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:164) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.ClusterService.publishAndApplyChanges(ClusterService.java:761) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:587) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.run(ClusterService.java:263) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) [baidu-elasticsearch-5.5.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: cannot set discovery.zen.minimum_master_nodes to more than the current master nodes count [1]
	at org.elasticsearch.discovery.zen.ZenDiscovery.lambda$new$2(ZenDiscovery.java:187) ~[baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.settings.Setting$Updater.getValue(Setting.java:608) ~[baidu-elasticsearch-5.5.0.jar:?]
	... 13 more
[2018-04-18T09:51:47,772][WARN ][o.e.c.s.ClusterSettings  ] [B-i9l9Q] failed to apply settings
java.lang.IllegalArgumentException: illegal value can't update [discovery.zen.minimum_master_nodes] from [1] to [2]
	at org.elasticsearch.common.settings.Setting$Updater.getValue(Setting.java:610) ~[baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater.updater(AbstractScopedSettings.java:344) ~[baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:164) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.ClusterService.publishAndApplyChanges(ClusterService.java:761) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:587) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.run(ClusterService.java:263) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) [baidu-elasticsearch-5.5.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: cannot set discovery.zen.minimum_master_nodes to more than the current master nodes count [1]
	at org.elasticsearch.discovery.zen.ZenDiscovery.lambda$new$2(ZenDiscovery.java:187) ~[baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.settings.Setting$Updater.getValue(Setting.java:608) ~[baidu-elasticsearch-5.5.0.jar:?]
	... 13 more
[2018-04-18T09:51:47,773][WARN ][o.e.c.s.ClusterService   ] [B-i9l9Q] failed to apply cluster settings
java.lang.IllegalArgumentException: illegal value can't update [discovery.zen.minimum_master_nodes] from [1] to [2]
	at org.elasticsearch.common.settings.Setting$Updater.getValue(Setting.java:610) ~[baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater.updater(AbstractScopedSettings.java:344) ~[baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:164) ~[baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.ClusterService.publishAndApplyChanges(ClusterService.java:761) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:587) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.run(ClusterService.java:263) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) [baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) [baidu-elasticsearch-5.5.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: cannot set discovery.zen.minimum_master_nodes to more than the current master nodes count [1]
	at org.elasticsearch.discovery.zen.ZenDiscovery.lambda$new$2(ZenDiscovery.java:187) ~[baidu-elasticsearch-5.5.0.jar:?]
	at org.elasticsearch.common.settings.Setting$Updater.getValue(Setting.java:608) ~[baidu-elasticsearch-5.5.0.jar:?]
	... 13 more

**Comment by bleskes** [comment]
Your problem is that once node A starts again it can't find node B, which is master and elects itself as master (because the min master nodes in it's yml file is still 1). It then can't import the cluster state on disk (which is good because otherwise you'd have both A & B as master).

When changing the cluster size you must make sure to also change the nodes yml files to reflect the update situation. This is needed for exactly the use case you are testing - when a node is restarted it uses the yml file to find other nodes and join the cluster. Since the node was just started, the configuration is the only thing it has access to.

**Comment by DaveCTurner** [comment]
It'd be best to ask this question in the [discussion forum](https://discuss.elastic.co/c/elasticsearch) as we prefer to use Github issues for bug reports and feature requests only.

In this case, [it's important that `discovery.zen.minimum_master_nodes` is set to a number greater than half of your master-eligible nodes at all times](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/discovery-settings.html#minimum_master_nodes). This effectively means it must be set to `2` in the `elasticsearch.yml` file, because that value is used when a node starts up until it successfully forms a cluster and recovers the value that was dynamically set.

I'm closing this issue here, but if you would like to discuss further then please open a thread in the discussion forum.

**Comment by bleskes** [comment]
@wuyunfeng we're working on it . See (some) details at the end of https://www.elastic.co/elasticon/conf/2018/sf/elasticsearch-consensus-the-past-the-present-and-the-future

**Comment by wuyunfeng** [comment]
@bleskes Thanks. Appreciate that.
