### ISSUE TITLE
org.elasticsearch.common.cache.Cache deadlock when loader throws Error

### ISSUE THREAD

**Issue by nomoa** [elastic/elasticsearch#30201]
Hi,
I'm currently investigating what seems to be a deadlock issue in `org.elasticsearch.common.cache.Cache` (ref https://github.com/o19s/elasticsearch-learning-to-rank/issues/153). It was reported to happen on 5.5 and 6.2.

Reading the stack I understand that the `CompletableFuture` created just before calling the loader method in `computeIfAbsent` and stored in `Cache.CacheSegment#map` is never resolved.
One possibility would be that the loader method throws an Error (or anything extending Throwable but not Exception).

This simple test case allows to reproduce the issue:
```java
        Cache<String, String> cache = CacheBuilder.<String, String>builder().build();;

        try {
            cache.computeIfAbsent("test", (s) -> {
                throw new Error("test");
            });
        } catch (Error e) {
            e.printStackTrace();
        }
        cache.computeIfAbsent("test", (s) -> "s" ); // Deadlock
```
I believe that `computeIfAbsent` should catch `Throwable` instead of `Exception`.

See https://github.com/elastic/elasticsearch/blob/dfc7ca72147d11b2757c5feec84aa1dedcfef4b3/server/src/main/java/org/elasticsearch/common/cache/Cache.java#L413

**Comment by jasontedor** [comment]
I am not sure that I agree. An error should tear the server down; if that is not happening because the error is being swallowed, that's the bug.

**Comment by nomoa** [comment]
Thanks for having a look, so if I understand your position properly I need to continue my investigations on the bug downstream to understand why the Error has not brought the server down (assuming that my assumption to explain the deadlock stack reported there is correct).

**Comment by nomoa** [comment]
Tested this by injecting an Error and the server properly crashed after logging the exception:
```
[2018-04-29T18:28:04,994][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [elasticsearch[vf0a0em][search][T#1]], exiting
java.lang.AssertionError: BOOM!
	at com.o19s.es.ltr.feature.store.index.Caches.lambda$cacheLoad$7(Caches.java:146) ~[?:?]
	at org.elasticsearch.common.cache.Cache.computeIfAbsent(Cache.java:412) ~[elasticsearch-6.2.2.jar:6.2.2]
	at com.o19s.es.ltr.feature.store.index.Caches.cacheLoad(Caches.java:140) ~[?:?]
	at com.o19s.es.ltr.feature.store.index.Caches.loadFeatureSet(Caches.java:130) ~[?:?]
	at com.o19s.es.ltr.feature.store.index.CachedFeatureStore.loadSet(CachedFeatureStore.java:51) ~[?:?]
	at com.o19s.es.ltr.query.StoredLtrQueryBuilder.doToQuery(StoredLtrQueryBuilder.java:140) ~[?:?]
	at com.o19s.es.ltr.query.StoredLtrQueryBuilder.doToQuery(StoredLtrQueryBuilder.java:45) ~[?:?]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-6.2.2.jar:6.2.2]
[...]
```

So I understand that it's not worth trying to make this Cache implementation resilient to such errors and having it in a deadlock state after these is not much a problem since the server should crash anyways.

I'll continue investigating as my first guess to explain the lock states seems to be wrong.

Thanks and sorry for the noise.
