### ISSUE TITLE
when using update api to elasticsearch, elasticsearch primary shard and replication shard are both failed

### ISSUE THREAD

**Issue by highmoutain** [elastic/elasticsearch#30204]
**Elasticsearch version** (`bin/elasticsearch --version`):  5.1.1

**Plugins installed**: []  no

**JVM version** (`java -version`): 1.8.0_77

**OS version** (`uname -a` if on a Unix-like system): CentOS Linux release 7.2.1511 (Core) 

**Description of the problem including expected versus actual behavior**:
when using update api ,highly concurrency , primary shard and replication shard all failed.
And this happened many times in 2 machines. So I think tihs is a bug.

**Provide logs (if relevant)**:

[2018-04-27T12:02:22,797][WARN ][o.e.c.a.s.ShardStateAction] [172.20.3.2] [analytics_profile_12014][7] received shard failed for shard id [[analytics_profile_12014][7]], allocation id [xIEoF3JaTLWQz6X2KxMWRA], primary term [0], message [shard failure, reason [refresh failed]], failure [EOFException[read past EOF: MMapIndexInput(path="/mnt/esdata2/nodes/0/indices/fzJHAFdQQQO5zPL70D2b6g/7/index/_fqb1.cfe")]]
java.io.EOFException: read past EOF: MMapIndexInput(path="/mnt/esdata2/nodes/0/indices/fzJHAFdQQQO5zPL70D2b6g/7/index/_fqb1.cfe")
        Suppressed: org.apache.lucene.index.CorruptIndexException: checksum status indeterminate: remaining=0, please run checkindex for more details (resource=BufferedChecksumIndexInput(MMapIndexInput(path="/mnt/esdata2/nodes/0/indices/fzJHAFdQQQO5zPL70D2b6g/7/index/_fqb1.cfe")))
org.elasticsearch.action.FailedNodeException: Failed node [BbfFMNRpRvW5p8LDs3rquQ]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleException(TransportNodesAction.java:219) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:984) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.transport.TcpTransport.lambda$handleException$17(TcpTransport.java:1314) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.transport.TcpTransport.handleException(TcpTransport.java:1312) [elasticsearch-5.1.1.jar:5.1.1]
Caused by: org.elasticsearch.transport.RemoteTransportException: [172.20.3.2_1][172.20.3.2:9301][internal:cluster/nodes/indices/shard/store[n]]
Caused by: org.elasticsearch.ElasticsearchException: Failed to list store metadata for shard [[analytics_action_12014_201804][15]]
Caused by: org.apache.lucene.index.CorruptIndexException: failed engine (reason: [corrupt file (source: [index])]) (resource=preexisting_corruption)
Caused by: java.io.IOException: failed engine (reason: [corrupt file (source: [index])])
Caused by: org.apache.lucene.index.CorruptIndexException: compound sub-files must have a valid codec header and footer: file is too small (0 bytes) (resource=BufferedChecksumIndexInput(MMapIndexInput(path="/mnt/esdata1/nodes/0/indices/cBECbko7SMKP3oXsTGi_kg/15/index/_2kqi.fdx")))
[2018-04-27T12:02:22,800][WARN ][o.e.c.a.s.ShardStateAction] [172.20.3.2] [analytics_profile_12014][18] received shard failed for shard id [[analytics_profile_12014][18]], allocation id [7TieFxLRRZ-28uOsPFr1yQ], primary term [0], message [shard failure, reason [refresh failed]], failure [EOFException[read past EOF: MMapIndexInput(path="/mnt/esdata2/nodes/0/indices/fzJHAFdQQQO5zPL70D2b6g/18/index/_fhe2.cfe")]]
java.io.EOFException: read past EOF: MMapIndexInput(path="/mnt/esdata2/nodes/0/indices/fzJHAFdQQQO5zPL70D2b6g/18/index/_fhe2.cfe")
        Suppressed: org.apache.lucene.index.CorruptIndexException: checksum status indeterminate: remaining=0, please run checkindex for more details (resource=BufferedChecksumIndexInput(MMapIndexInput(path="/mnt/esdata2/nodes/0/indices/fzJHAFdQQQO5zPL70D2b6g/18/index/_fhe2.cfe")))

**Comment by highmoutain** [comment]
And I using checkIndex tool, it says there is no problem

**Comment by dnhatn** [comment]
@highmoutain Sorry a late response but there is no SLA.

The log shows that your index is corrupted. In particular "/mnt/esdata2/nodes/0/indices/fzJHAFdQQQO5zPL70D2b6g/18/index/_fhe2.cfe" is empty while it should not. This might possibly be related to your filesystem or hardware. Which filesystem are you using? Can you also please check your hardware?

**Comment by highmoutain** [comment]
@dnhatn  hi, thanks for your reply.
filesystem is xfs. 
I check through chechindex and /var/log/messages, there is no problem.
And this problem happens in 2 machines, so I do not think it's  a hardware problem.

Do I need check hard disk through other tools?

**Comment by javanna** [comment]
ping @elastic/es-distributed

**Comment by ywelsch** [comment]
it looks like this one fell off the radar. @highmoutain is this still an issue with newer ES versions? I'm closing this issue for now, but will also reopen and reinvestigate if need be.

**Comment by wangxilong1991** [comment]
there is always a similar problem in 6.5.4
----------------------------------------------------------------
[2019-03-20T07:39:04,464][WARN ][o.e.i.e.Engine           ] [node-02] [test][2] failed engine [refresh failed source[api]]
org.apache.lucene.index.CorruptIndexException: compound sub-files must have a valid codec header and footer: file is too small (0 bytes) (resource=BufferedChecksumIndexInput(MMapIndexInput(path="/data1/esdata/es1/nodes/0/indices/iX61hBJBScGThUrc60VKlQ/2/index/_1hy4.fdx")))
	at org.apache.lucene.codecs.CodecUtil.verifyAndCopyIndexHeader(CodecUtil.java:282) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
	at org.apache.lucene.codecs.lucene50.Lucene50CompoundFormat.write(Lucene50CompoundFormat.java:92) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
	at org.apache.lucene.index.IndexWriter.createCompoundFile(IndexWriter.java:4997) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
	at org.apache.lucene.index.DocumentsWriterPerThread.sealFlushedSegment(DocumentsWriterPerThread.java:576) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:515) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:554) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
