### ISSUE TITLE
[CCR] ShardChangesIT#testFollowIndex fails on the master branch

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#30227]
This failure happened on my CI but I have not figured out the reason. I opened this to make sure that we will have a look at it. 

I can reproduce this locally.

```
./gradlew :x-pack:plugin:ccr:internalClusterTest \
-Dtests.seed=73E17BC6D8FB4F03 \
-Dtests.class=org.elasticsearch.xpack.ccr.ShardChangesIT \
-Dtests.method="testFollowIndex" \
-Dtests.security.manager=true \
-Dtests.locale=nmg -Dtests.timezone=Asia/Tbilisi
```

Assertion error:

```
> Throwable #1: java.lang.AssertionError
   >    at __randomizedtesting.SeedInfo.seed([73E17BC6D8FB4F03:908DB4F4E1437689]:0)
   >    at org.elasticsearch.xpack.ccr.ShardChangesIT.lambda$assertExpectedDocumentRunnable$5(ShardChangesIT.java:266)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:754)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:728)
   >    at org.elasticsearch.xpack.ccr.ShardChangesIT.testFollowIndex(ShardChangesIT.java:174)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
   >    Suppressed: java.lang.AssertionError
   >            at org.elasticsearch.xpack.ccr.ShardChangesIT.lambda$assertExpectedDocumentRunnable$5(ShardChangesIT.java:266)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:742)
   >            ... 38 more

```

**Comment by martijnvg** [comment]
This is fixed by #30238
