### ISSUE TITLE
[CI] RollupIT#testBig fails

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#30232]
I can reproduce this locally.

```
./gradlew :x-pack:plugin:rollup:internalClusterTest \
-Dtests.seed=38E445F745E9BA6E \
-Dtests.class=org.elasticsearch.xpack.rollup.RollupIT \
-Dtests.method="testBig" \
-Dtests.security.manager=true \
-Dtests.jvms=8 \
-Dtests.locale=luy \
-Dtests.timezone=Pacific/Apia
```

Assertion error

```
FAILURE 7.99s | RollupIT.testBig <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <89L>
   >      but: was <88L>
   >    at __randomizedtesting.SeedInfo.seed([38E445F745E9BA6E:37DA9EAD70777305]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.xpack.rollup.RollupIT.testBig(RollupIT.java:429)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by polyfractal** [comment]
I haven't been able to replicate this locally yet, but it failed again three days ago with:

```
./gradlew :x-pack:plugin:rollup:internalClusterTest \
  -Dtests.seed=4C51DCAD1A755E3F \
  -Dtests.class=org.elasticsearch.xpack.rollup.RollupIT \
  -Dtests.method="testBig" \
  -Dtests.security.manager=true \
  -Dtests.locale=uk-UA \
  -Dtests.timezone=Africa/Libreville
```

Going to work through the test and see if there's something obviously missing, or where additional logging could be added.
