### ISSUE TITLE
Completion suggester fails when empty regex query is provided.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#30286]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.3.0

**Description of the problem including expected versus actual behavior**:
Note that this issue only reproduces with Java assertions enabled.

When running completion suggestions with a context, the suggester fails when an empty regex is provided (`regex: ""`). In particular, it produces an assertion failure:

```
java.lang.AssertionError: input should not end with the context separator
	at __randomizedtesting.SeedInfo.seed([F0F1F91ACBC1094E]:0)
	at org.apache.lucene.search.suggest.document.ContextQuery$ContextCompletionWeight.setInnerWeight(ContextQuery.java:295)
	at org.apache.lucene.search.suggest.document.ContextQuery$ContextCompletionWeight.setNextMatch(ContextQuery.java:274)
	at org.apache.lucene.search.suggest.document.NRTSuggester.lookup(NRTSuggester.java:221)
	at org.apache.lucene.search.suggest.document.CompletionScorer.score(CompletionScorer.java:70)
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39)
...
```

I haven't looked into the issue, and it may quite low priority, but I figured I'd file an issue since assertion failures are often high signal.

**Steps to reproduce**:
First, run elasticsearch with assertions enabled. When running from source, this might look like `export JAVA_OPTS="-ea"; ./gradlew run`.

Then, run through the commands in the following gist: https://gist.github.com/jtibshirani/a4b68ed34063ebf930dcb09201ad4f8b

**Comment by mP1** [comment]
please provide mapping, put documents and query for easy replay.

**Comment by colings86** [comment]
@mP1 the linked gist in the description appears to already have commands for reproducing the issue

**Comment by jtibshirani** [comment]
This should likely be fixed in Lucene -- filed an issue in the Lucene JIRA to track: https://issues.apache.org/jira/browse/LUCENE-8287

**Comment by jtibshirani** [comment]
Closing, as this is now fixed in Lucene and the change was included in a recent upgrade.
