### ISSUE TITLE
[CI] JdbcSqlSpecIT fails: "Expected more data..."

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#30292]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux/2389/console

REPRODUCE WITH lines both reproduce a failure for me:

```
./gradlew :x-pack:qa:sql:security:ssl:integTestRunner \
  -Dtests.seed=1118CB444CAB2365 \
  -Dtests.class=org.elasticsearch.xpack.qa.sql.security.JdbcSqlSpecIT \
  -Dtests.method="test {agg.testAggMultiWithHaving}" \
  -Dtests.security.manager=true \
  -Dtests.locale=ko-KR \
  -Dtests.timezone=Asia/Jerusalem

./gradlew :x-pack:qa:sql:security:ssl:integTestRunner \
  -Dtests.seed=1118CB444CAB2365 \
  -Dtests.class=org.elasticsearch.xpack.qa.sql.security.JdbcSqlSpecIT \
  -Dtests.method="test {agg.testAggMultiWithHavingOnCount}" \
  -Dtests.security.manager=true \
  -Dtests.locale=ko-KR \
  -Dtests.timezone=Asia/Jerusalem
```

```
   > Throwable #1: java.lang.AssertionError: Expected more data but no more entries found after [0]
   >    at __randomizedtesting.SeedInfo.seed([1118CB444CAB2365:994CF49EE2574E9D]:0)
   >    at org.elasticsearch.xpack.qa.sql.security.JdbcSqlSpecIT.agg.testAggMultiWithHaving(agg.sql-spec:279)
   >    at org.elasticsearch.xpack.qa.sql.jdbc.JdbcAssert.doAssertResultSetData(JdbcAssert.java:114)
   >    at org.elasticsearch.xpack.qa.sql.jdbc.JdbcAssert.assertResultSetData(JdbcAssert.java:103)
   >    at org.elasticsearch.xpack.qa.sql.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:37)
   >    at org.elasticsearch.xpack.qa.sql.jdbc.SpecBaseIntegrationTestCase.assertResults(SpecBaseIntegrationTestCase.java:103)
   >    at org.elasticsearch.xpack.qa.sql.jdbc.SqlSpecTestCase.doTest(SqlSpecTestCase.java:67)
   >    at org.elasticsearch.xpack.qa.sql.jdbc.SpecBaseIntegrationTestCase.test(SpecBaseIntegrationTestCase.java:76)
   >    at java.lang.Thread.run(Thread.java:748)
```

**Comment by DaveCTurner** [comment]
These test cases are read from a file which doesn't apparently have any way to mute individual cases, so I muted the whole suite in b9e1860f36b.
