### ISSUE TITLE
[CI] MustacheException: Failed to get value for ctx @[query-template:1]

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#30291]
CI output: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/1918/console

```
* What went wrong:
Execution failed for task ':x-pack:qa:smoke-test-watcher:integTestRunner'.
> At least one slave process threw an exception, first: Quit event not received from the forked process? This may indicate JVM crash or runner bugs.
```

No `REPRODUCE WITH` line, but the logs contain this which could be the culprit:

```
[2018-05-01T08:15:13,470][ERROR][o.e.s.m.MustacheScriptEngine] Error running com.github.mustachejava.codes.DefaultMustache@4191618e
com.github.mustachejava.MustacheException: Failed to get value for ctx @[query-template:1]
	at com.github.mustachejava.codes.ValueCode.execute(ValueCode.java:74) ~[compiler-0.9.3.jar:?]
	at com.github.mustachejava.codes.DefaultMustache.run(DefaultMustache.java:34) ~[compiler-0.9.3.jar:?]
	at com.github.mustachejava.codes.DefaultCode.execute(DefaultCode.java:162) ~[compiler-0.9.3.jar:?]
	at com.github.mustachejava.codes.DefaultMustache.execute(DefaultMustache.java:55) ~[compiler-0.9.3.jar:?]
	at com.github.mustachejava.Mustache.execute(Mustache.java:38) ~[compiler-0.9.3.jar:?]
	at org.elasticsearch.script.mustache.MustacheScriptEngine$MustacheExecutableScript.lambda$execute$0(MustacheScriptEngine.java:111) ~[lang-mustache-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.elasticsearch.script.mustache.MustacheScriptEngine$MustacheExecutableScript.execute(MustacheScriptEngine.java:110) [lang-mustache-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.xpack.watcher.common.text.TextTemplateEngine.render(TextTemplateEngine.java:57) [x-pack-watcher-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.xpack.watcher.actions.logging.ExecutableLoggingAction.execute(ExecutableLoggingAction.java:46) [x-pack-watcher-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.xpack.core.watcher.actions.ActionWrapper.execute(ActionWrapper.java:144) [x-pack-core-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.xpack.watcher.execution.ExecutionService.executeInner(ExecutionService.java:475) [x-pack-watcher-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.xpack.watcher.execution.ExecutionService.execute(ExecutionService.java:305) [x-pack-watcher-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.xpack.watcher.transport.actions.execute.TransportExecuteWatchAction$1.doRun(TransportExecuteWatchAction.java:154) [x-pack-watcher-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:625) [elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.IllegalArgumentException: Iterable object is self-referencing itself
	at org.elasticsearch.common.util.CollectionUtils.ensureNoSelfReferences(CollectionUtils.java:253) ~[elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.common.util.CollectionUtils.ensureNoSelfReferences(CollectionUtils.java:256) ~[elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.common.util.CollectionUtils.ensureNoSelfReferences(CollectionUtils.java:256) ~[elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.common.util.CollectionUtils.ensureNoSelfReferences(CollectionUtils.java:256) ~[elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.common.util.CollectionUtils.ensureNoSelfReferences(CollectionUtils.java:231) ~[elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.script.mustache.CustomReflectionObjectHandler.stringify(CustomReflectionObjectHandler.java:160) ~[?:?]
	at com.github.mustachejava.codes.ValueCode.execute(ValueCode.java:69) ~[?:?]
	... 20 more
[2018-05-01T08:15:13,475][ERROR][o.e.x.w.a.l.ExecutableLoggingAction] [node-0] failed to execute action [_inlined_/my-logging]
org.elasticsearch.script.GeneralScriptException: Error running com.github.mustachejava.codes.DefaultMustache@4191618e
	at org.elasticsearch.script.mustache.MustacheScriptEngine$MustacheExecutableScript.execute(MustacheScriptEngine.java:116) ~[?:?]
	at org.elasticsearch.xpack.watcher.common.text.TextTemplateEngine.render(TextTemplateEngine.java:57) ~[?:?]
	at org.elasticsearch.xpack.watcher.actions.logging.ExecutableLoggingAction.execute(ExecutableLoggingAction.java:46) ~[?:?]
	at org.elasticsearch.xpack.core.watcher.actions.ActionWrapper.execute(ActionWrapper.java:144) [x-pack-core-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.xpack.watcher.execution.ExecutionService.executeInner(ExecutionService.java:475) [x-pack-watcher-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.xpack.watcher.execution.ExecutionService.execute(ExecutionService.java:305) [x-pack-watcher-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.xpack.watcher.transport.actions.execute.TransportExecuteWatchAction$1.doRun(TransportExecuteWatchAction.java:154) [x-pack-watcher-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:625) [elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: com.github.mustachejava.MustacheException: Failed to get value for ctx @[query-template:1]
	at com.github.mustachejava.codes.ValueCode.execute(ValueCode.java:74) ~[?:?]
	at com.github.mustachejava.codes.DefaultMustache.run(DefaultMustache.java:34) ~[?:?]
	at com.github.mustachejava.codes.DefaultCode.execute(DefaultCode.java:162) ~[?:?]
	at com.github.mustachejava.codes.DefaultMustache.execute(DefaultMustache.java:55) ~[?:?]
	at com.github.mustachejava.Mustache.execute(Mustache.java:38) ~[?:?]
	at org.elasticsearch.script.mustache.MustacheScriptEngine$MustacheExecutableScript.lambda$execute$0(MustacheScriptEngine.java:111) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.elasticsearch.script.mustache.MustacheScriptEngine$MustacheExecutableScript.execute(MustacheScriptEngine.java:110) ~[?:?]
	... 13 more
Caused by: java.lang.IllegalArgumentException: Iterable object is self-referencing itself
	at org.elasticsearch.common.util.CollectionUtils.ensureNoSelfReferences(CollectionUtils.java:253) ~[elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.common.util.CollectionUtils.ensureNoSelfReferences(CollectionUtils.java:256) ~[elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.common.util.CollectionUtils.ensureNoSelfReferences(CollectionUtils.java:256) ~[elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.common.util.CollectionUtils.ensureNoSelfReferences(CollectionUtils.java:256) ~[elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.common.util.CollectionUtils.ensureNoSelfReferences(CollectionUtils.java:231) ~[elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.script.mustache.CustomReflectionObjectHandler.stringify(CustomReflectionObjectHandler.java:160) ~[?:?]
	at com.github.mustachejava.codes.ValueCode.execute(ValueCode.java:69) ~[?:?]
	at com.github.mustachejava.codes.DefaultMustache.run(DefaultMustache.java:34) ~[?:?]
	at com.github.mustachejava.codes.DefaultCode.execute(DefaultCode.java:162) ~[?:?]
	at com.github.mustachejava.codes.DefaultMustache.execute(DefaultMustache.java:55) ~[?:?]
	at com.github.mustachejava.Mustache.execute(Mustache.java:38) ~[?:?]
	at org.elasticsearch.script.mustache.MustacheScriptEngine$MustacheExecutableScript.lambda$execute$0(MustacheScriptEngine.java:111) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.elasticsearch.script.mustache.MustacheScriptEngine$MustacheExecutableScript.execute(MustacheScriptEngine.java:110) ~[?:?]
	... 13 more
```

**Comment by rjernst** [comment]
The test seems to have failed because the jvm died.

```
08:15:21 * What went wrong:
08:15:21 Execution failed for task ':x-pack:qa:smoke-test-watcher:integTestRunner'.
08:15:21 > At least one slave process threw an exception, first: Quit event not received from the forked process? This may indicate JVM crash or runner bugs.
```

/cc @s1monw @spinscale

**Comment by spinscale** [comment]
I dont think that this is a problem with the tests itself. Checking the `x-pack/qa/smoke-test-watcher/build/testrun/integTestRunner/temp/junit4-J0-20180501_081459_8628720121421837627595.events` file, it shows that all the tests ran successfully and the test suite completed.

But then the test runner seems to have a different opinion about that and thus emits this error message. These are the last lines of the above file

```
[
 "TEST_FINISHED",
 {
  "description": "ID#testSimpleParameterReplace(org.elasticsearch.smoketest.WatcherTemplateIT)",
  "startTimestamp": 1525162517114,
  "executionTime": 7
 }
]

[
 "SUITE_COMPLETED",
 {
  "description": "ID#org.elasticsearch.smoketest.WatcherTemplateIT",
  "startTimestamp": 1525162516933,
  "executionTime": 190
 }
]

[
 "IDLE",
 {}
]

[
 "QUIT",
 {}
]
```

I have another test run, where the exact same issue has happened in a completely different test: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java8,nodes=virtual&&linux/28/console

**Comment by jakelandis** [comment]
Closing due to lack of activity and no actionable items. (nothing was muted and all links have gone stale)
