### ISSUE TITLE
[CI] ConnectionClosedException in RestClientSingleHostIntegTests

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#30305]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=amazon/2390/console yielded a failure with this stack trace:

```
Suite: org.elasticsearch.client.RestClientSingleHostIntegTests
ERROR   0.02s J0 | RestClientSingleHostIntegTests.testHeaders <<< FAILURES!
   > Throwable #1: org.apache.http.ConnectionClosedException: Connection closed
   >  at __randomizedtesting.SeedInfo.seed([9FFF61FF6DF2A0BF:552F51A0E4C041DF]:0)
   >  at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:718)
   >  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
   >  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198)
   >  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:177)
   >  at org.elasticsearch.client.RestClientSingleHostIntegTests.testHeaders(RestClientSingleHostIntegTests.java:177)
   >  at java.lang.Thread.run(Thread.java:748)
   > Caused by: org.apache.http.ConnectionClosedException: Connection closed
   >  at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.endOfInput(HttpAsyncRequestExecutor.java:344)
   >  at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:261)
   >  at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
   >  at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
   >  at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
   >  at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
   >  at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
   >  at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
   >  at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
   >  at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
   >  at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
   >  ... 1 more
Completed [6/13] on J0 in 1.63s, 7 tests, 1 error <<< FAILURES!
```

No `REPRODUCE WITH` line was given, and there's not obviously any further logs on the worker.

**Comment by jdconrad** [comment]
I believe this issue is the same as (https://github.com/elastic/elasticsearch/issues/29558).  Closing in favour of the other.
