### ISSUE TITLE
[CI] ClassNotFoundException: org.elasticsearch.http.netty4.Netty4HttpChannel

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#30308]
https://internal-ci.elastic.co/job/elastic+x-pack-elasticsearch+6.2+matrix-java-periodic/ES_BUILD_JAVA=java9,ES_RUNTIME_JAVA=java9,nodes=linux/26/console failed with apparently a premature EOF in a classloader:

```
|    [2018-05-01T15:10:14,498][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [cluster1-node1] fatal error in thread [Thread-4], exiting
|    java.lang.NoClassDefFoundError: org/elasticsearch/http/netty4/Netty4HttpChannel
|     at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:76) ~[?:?]
|     at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
|     at org.elasticsearch.http.netty4.pipelining.HttpPipeliningHandler.channelRead(HttpPipeliningHandler.java:68) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
|     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[?:?]
|     at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
|     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
|     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
|     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[?:?]
|     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
|     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
|     at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
|     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
|     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
|     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) ~[?:?]
|     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) ~[?:?]
|     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) ~[?:?]
|     at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545) ~[?:?]
|     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) ~[?:?]
|     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) ~[?:?]
|     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[?:?]
|     at java.lang.Thread.run(Thread.java:844) [?:?]
|    Caused by: java.lang.ClassNotFoundException: org.elasticsearch.http.netty4.Netty4HttpChannel
|     at java.net.URLClassLoader$1.run(URLClassLoader.java:455) ~[?:?]
|     at java.net.URLClassLoader$1.run(URLClassLoader.java:447) ~[?:?]
|     at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
|     at java.net.URLClassLoader.findClass(URLClassLoader.java:446) ~[?:?]
|     at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?]
|     at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:890) ~[?:?]
|     at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
|     ... 46 more
|    Caused by: java.io.EOFException: Detect premature EOF
|     at jdk.internal.loader.Resource.getBytes(Resource.java:131) ~[?:?]
|     at java.net.URLClassLoader.defineClass(URLClassLoader.java:540) ~[?:?]
|     at java.net.URLClassLoader.access$100(URLClassLoader.java:83) ~[?:?]
|     at java.net.URLClassLoader$1.run(URLClassLoader.java:453) ~[?:?]
|     at java.net.URLClassLoader$1.run(URLClassLoader.java:447) ~[?:?]
|     at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
|     at java.net.URLClassLoader.findClass(URLClassLoader.java:446) ~[?:?]
|     at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?]
|     at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:890) ~[?:?]
|     at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
|     ... 46 more
```

I couldn't see anything that obviously explains this in the logs or on the worker, but I didn't have a good idea what I should be looking for either. No `REPRODUCE WITH` line given.

**Comment by jasontedor** [comment]
I do not think this build failure is actionable. It appears that something catastrophic happened to a build artifact leading to a truncated class file. This is most likely an internal infrastructure issue and not a build issue. Closing.
