### ISSUE TITLE
[CI] XPackRestIT fails due to leftover tasks not finishing

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#30328]
Source: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1635/console

A couple of tests fail because monitoring still seems to be running and thus there are still pending tasks trying to index monitoring data.

```
FAILURE 10.6s | XPackRestIT.test {p0=ml/datafeeds_crud/Test update datafeed to point to job already attached to another datafeed} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 2 active tasks found:
   > indices:data/write/bulk        MXy7fTeyTh-GSMwcpc9i2A:30899 -                            transport 1525231261749 03:21:01 10.6s       127.0.0.1 node-0 requests[12], indices[.monitoring-es-6-2018.05.02]
   > indices:data/write/bulk[s]     MXy7fTeyTh-GSMwcpc9i2A:30900 MXy7fTeyTh-GSMwcpc9i2A:30899 transport 1525231261749 03:21:01 10.6s       127.0.0.1 node-0 requests[12], index[.monitoring-es-6-2018.05.02]
   >  expected:<0> but was:<2>
   >    at __randomizedtesting.SeedInfo.seed([69F937F1A352D486:E1AD082B0DAEB97E]:0)
   >    at org.elasticsearch.xpack.test.rest.XPackRestTestHelper.lambda$waitForPendingTasks$2(XPackRestTestHelper.java:110)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:754)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:728)
   >    at org.elasticsearch.xpack.test.rest.XPackRestTestHelper.waitForPendingTasks(XPackRestTestHelper.java:90)
   >    at org.elasticsearch.xpack.test.rest.XPackRestIT.cleanup(XPackRestIT.java:215)
   >    at java.lang.Thread.run(Thread.java:748)
```

None of the failed tests needed monitoring though

```
Tests with failures:
  - org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=ml/datafeeds_crud/Test update datafeed to point to job already attached to another datafeed}
  - org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=ml/jobs_get_result_overall_buckets/Test overall buckets given top_n is greater than the job count}
  - org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=ml/delete_model_snapshot/Test valid delete snapshot}
  - org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=watcher/ack_watch/20_ack_individual_action/Test ack watch api on an individual action}
  - org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=ml/datafeeds_crud/Test put datafeed whose id is already taken}
```

**Comment by spinscale** [comment]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+multijob-unix-compatibility/os=debian/22/console is another one

**Comment by dnhatn** [comment]
Another instance on 6.x: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=amazon/1052/console

Log: [pending-tasks.txt](https://github.com/elastic/elasticsearch/files/1996029/pending-tasks.txt)

Failed tests:
```
- org.elasticsearch.xpack.test.rest.XPackRestIT test {p0=ml/delete_job_force/Test cannot force delete a non-existent job}
- org.elasticsearch.xpack.test.rest.XPackRestIT test {p0=ml/filter_crud/Test get filter API with bad ID}
- org.elasticsearch.xpack.test.rest.XPackRestIT test {p0=ml/jobs_crud/Test cannot create job with existing result document}
- org.elasticsearch.xpack.test.rest.XPackRestIT test {p0=watcher/activate_watch/10_basic/Non existent watch returns 404}
- org.elasticsearch.xpack.test.rest.XPackRestIT test {p0=watcher/execute_watch/10_basic/Execute unknown watch results in 404}
```

Error:

```
   > 	Suppressed: java.lang.AssertionError: 2 active tasks found:
   > indices:data/write/bulk        y95D-pJJQpqYy0it6ptZqw:29351 -                            transport 1526050835082 15:00:35 1.5s        127.0.0.1 node-0 requests[12], indices[.monitoring-es-6-2018.05.11]
   > indices:data/write/bulk[s]     y95D-pJJQpqYy0it6ptZqw:29352 y95D-pJJQpqYy0it6ptZqw:29351 transport 1526050835082 15:00:35 1.5s        127.0.0.1 node-0 requests[12], index[.monitoring-es-6-2018.05.11]
   >  expected:<0> but was:<2>
   > 		at org.elasticsearch.xpack.test.rest.XPackRestTestHelper.lambda$waitForPendingTasks$2(XPackRestTestHelper.java:110)
   > 		at org.elastics
```

**Comment by romseygeek** [comment]
Another instance of this:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux/2430/console

**Comment by dakrone** [comment]
I tried reproducing this to pinpoint it, but I was unable to. Since we haven't had an occurrence since last May, I think it's safe to close.

Another note though, the original error mentions the .monitoring-es-* indices, however, these tests use the .monitoring-logstash-* indices.
