### ISSUE TITLE
[CI] ml.integration.DeleteExpiredDataIT 

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#30377]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+periodic/56/console

Cannot reproduce it on my machine hence why I think it's a timeout failure.
From the logs:

```
java.util.concurrent.ExecutionException: RemoteTransportException[[node-0][[::1]:41294][cluster:admin/xpack/ml/delete_expired_data]]; nested: ElasticsearchException[[model-plots-it-test-by-field-with-terms] Search for expired snapshots failed]; nested: IndexNotFoundException[no such index];
	at __randomizedtesting.SeedInfo.seed([3128A1E3C5727F08:F9678C4FAC6E121A]:0)
	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:265)
	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:252)
	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:94)
	at org.elasticsearch.xpack.ml.integration.DeleteExpiredDataIT.testDeleteExpiredData(DeleteExpiredDataIT.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by dimitris-athanasiou** [comment]
I found the problem that's causing this. Pushing a fix shortly.
