### ISSUE TITLE
[CI] SplitIndexIT fails with Lucene-7.4 snapshot

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#30416]
This test starts failing more often after upgrading to Lucene-7.4 snapshot. Most of the failures are on Windows. It may relate to this Lucene failure https://elasticsearch-ci.elastic.co/job/apache+lucene-solr+master/27765/consoleText.

Error: `still has pending deleted files; cannot initialize IndexWriter`

```
  1> Caused by: java.lang.IllegalArgumentException: Directory store(MMapDirectory@C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\server\build\testrun\integTest\J1\temp\org.elasticsearch.action.admin.indices.create.SplitIndexIT_734B52BB31887C24-001\tempDir-002\data\nodes\1\indices\Ru5mKdhxQpaT3gWmSTvH2w\16\index lockFactory=org.apache.lucene.store.NativeFSLockFactory@66502081) still has pending deleted files; cannot initialize IndexWriter
  1> 	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:698) ~[lucene-core-7.4.0-snapshot-1ed95c097b.jar:7.4.0-snapshot-1ed95c097b 1ed95c097b82ee5f175e93f3fe62572abe064da6 - jimczi - 2018-05-03 16:16:13]
  1> 	at org.elasticsearch.index.store.Store.newIndexWriter(Store.java:1635) ~[main/:?]
  1> 	at org.elasticsearch.index.store.Store.bootstrapNewHistory(Store.java:1487) ~[main/:?]
  1> 	at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:393) ~[main/:?]
  1> 	at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromLocalShards$3(StoreRecovery.java:133) ~[main/:?]
  1> 	at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:301) ~[main/:?]
  1> 	at org.elasticsearch.index.shard.StoreRecovery.recoverFromLocalShards(StoreRecovery.java:123) ~[main/:?]
  1> 	at org.elasticsearch.index.shard.IndexShard.recoverFromLocalShards(IndexShard.java:1520) ~[main/:?]
  1> 	at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$8(IndexShard.java:2042) ~[main/:?]
  1> 	... 4 more
```

Some CI instances:

1. https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1608/consoleText

2. https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1609/console

Log: 
[shrink.txt](https://github.com/elastic/elasticsearch/files/1978298/shrink.txt)

**Comment by dnhatn** [comment]
Ping @simonw and @elastic/es-search-aggs

**Comment by dnhatn** [comment]
I muted the test at https://github.com/elastic/elasticsearch/commit/9c77eab91553a989ee096786651bb6981b973c5c.

**Comment by bleskes** [comment]
I muted the entire suit as we have similar failures in many tests.

**Comment by s1monw** [comment]
I opened #30567 for this
