### ISSUE TITLE
[CI] TransportSamlLogoutActionTests.testLogoutInvalidatesToken PrivilegedActionException

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#30445]
Was able to reproduce locally.

Reproduce:

```
./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=1182D37B3D2E4ECE \
  -Dtests.class=org.elasticsearch.xpack.security.action.saml.TransportSamlLogoutActionTests \
  -Dtests.method="testLogoutInvalidatesToken" \
  -Dtests.security.manager=true \
  -Dtests.locale=az-Latn \
  -Dtests.timezone=Europe/Isle_of_Man
```

Stack:

```
  2> REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test -Dtests.seed=1182D37B3D2E4ECE -Dtests.class=org.elasticsearch.xpack.security.action.saml.TransportSamlLogoutActionTests -Dtests.method="testLogoutInvalidatesToken" -Dtests.security.manager=true -Dtests.locale=az-Latn -Dtests.timezone=Europe/Isle_of_Man
ERROR   1.01s | TransportSamlLogoutActionTests.testLogoutInvalidatesToken <<< FAILURES!
   > Throwable #1: java.security.PrivilegedActionException: net.shibboleth.utilities.java.support.component.ComponentInitializationException: Error refreshing metadata during init
   >    at java.base/java.security.AccessController.doPrivileged(Native Method)
   >    at org.elasticsearch.xpack.security.authc.saml.SamlRealm.initialiseResolver(SamlRealm.java:595)
   >    at org.elasticsearch.xpack.security.authc.saml.SamlRealm.parseFileSystemMetadata(SamlRealm.java:560)
   >    at org.elasticsearch.xpack.security.authc.saml.SamlRealm.initializeResolver(SamlRealm.java:486)
   >    at org.elasticsearch.xpack.security.authc.saml.SamlRealm.create(SamlRealm.java:184)
   >    at org.elasticsearch.xpack.security.action.saml.TransportSamlLogoutActionTests.setup(TransportSamlLogoutActionTests.java:201)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
   > Caused by: net.shibboleth.utilities.java.support.component.ComponentInitializationException: Error refreshing metadata during init
   >    at org.opensaml.saml.metadata.resolver.impl.AbstractReloadingMetadataResolver.initMetadataResolver(AbstractReloadingMetadataResolver.java:264)
   >    at org.opensaml.saml.metadata.resolver.impl.AbstractMetadataResolver.doInitialize(AbstractMetadataResolver.java:287)
   >    at net.shibboleth.utilities.java.support.component.AbstractInitializableComponent.initialize(AbstractInitializableComponent.java:61)
   >    at org.elasticsearch.xpack.security.authc.saml.SamlRealm.lambda$initialiseResolver$10(SamlRealm.java:596)
   >    ... 41 more
   > Caused by: net.shibboleth.utilities.java.support.resolver.ResolverException: net.shibboleth.utilities.java.support.resolver.ResolverException: Unable to unmarshall metadata
   >    at org.opensaml.saml.metadata.resolver.impl.AbstractReloadingMetadataResolver.refresh(AbstractReloadingMetadataResolver.java:297)
   >    at org.opensaml.saml.metadata.resolver.impl.AbstractReloadingMetadataResolver.initMetadataResolver(AbstractReloadingMetadataResolver.java:262)
   >    ... 44 more
   > Caused by: net.shibboleth.utilities.java.support.resolver.ResolverException: Unable to unmarshall metadata
   >    at org.opensaml.saml.metadata.resolver.impl.AbstractReloadingMetadataResolver.unmarshallMetadata(AbstractReloadingMetadataResolver.java:344)
   >    at org.opensaml.saml.metadata.resolver.impl.AbstractReloadingMetadataResolver.processNewMetadata(AbstractReloadingMetadataResolver.java:381)
   >    at org.opensaml.saml.metadata.resolver.impl.AbstractReloadingMetadataResolver.refresh(AbstractReloadingMetadataResolver.java:291)
   >    ... 45 more
   > Caused by: org.opensaml.core.xml.io.UnmarshallingException: org.opensaml.core.xml.io.UnmarshallingException: Invalid key usage type: signing
   >    at org.opensaml.saml.metadata.resolver.impl.AbstractMetadataResolver.unmarshallMetadata(AbstractMetadataResolver.java:355)
   >    at org.opensaml.saml.metadata.resolver.impl.AbstractReloadingMetadataResolver.unmarshallMetadata(AbstractReloadingMetadataResolver.java:340)
   >    ... 47 more
   > Caused by: org.opensaml.core.xml.io.UnmarshallingException: Invalid key usage type: signing
   >    at org.opensaml.saml.saml2.metadata.impl.KeyDescriptorUnmarshaller.processAttribute(KeyDescriptorUnmarshaller.java:61)
   >    at org.opensaml.core.xml.io.AbstractXMLObjectUnmarshaller.unmarshallAttribute(AbstractXMLObjectUnmarshaller.java:197)
   >    at org.opensaml.core.xml.io.AbstractXMLObjectUnmarshaller.unmarshall(AbstractXMLObjectUnmarshaller.java:94)
   >    at org.opensaml.core.xml.io.AbstractXMLObjectUnmarshaller.unmarshallChildElement(AbstractXMLObjectUnmarshaller.java:311)
   >    at org.opensaml.core.xml.io.AbstractXMLObjectUnmarshaller.unmarshall(AbstractXMLObjectUnmarshaller.java:106)
   >    at org.opensaml.core.xml.io.AbstractXMLObjectUnmarshaller.unmarshallChildElement(AbstractXMLObjectUnmarshaller.java:311)
   >    at org.opensaml.core.xml.io.AbstractXMLObjectUnmarshaller.unmarshall(AbstractXMLObjectUnmarshaller.java:106)
   >    at org.opensaml.saml.metadata.resolver.impl.AbstractMetadataResolver.unmarshallMetadata(AbstractMetadataResolver.java:352)
   >    ... 48 moreThrowable #2: java.lang.NullPointerException
   >    at org.elasticsearch.xpack.security.action.saml.TransportSamlLogoutActionTests.cleanup(TransportSamlLogoutActionTests.java:207)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)

```

**Comment by jdconrad** [comment]
@tvernum Please feel free to re-assign as appropriate - noticed you were the last one with changes to these tests I believe.

**Comment by tvernum** [comment]
This is due to https://github.com/elastic/x-pack-elasticsearch/issues/2815
We have a workaround in most of the SAML tests, it looks like this one got missed.

Will fix.

**Comment by tvernum** [comment]
This is because fb8adb4a1c6c3d8a4f8074dbffae7ee92e97e1cd didn't get backported correctly to 6.3/6.x.

I have now backported them as
- ae5ac44
- 485af9e
