### ISSUE TITLE
Elasticsearch windows service fails to register service stoppage event

### ISSUE THREAD

**Issue by askids** [elastic/elasticsearch#30482]
hi,

**Elasticsearch version** (`bin/elasticsearch --version`): 5.5.1
**Plugins installed**: [X-pack basic, Readonlyrest 1.16.15, Search Guard SSL]
**JVM version** (`java -version`): JRE 64bit
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): Windows 2012 R2 standard
**Description of the problem including expected versus actual behavior**:
When Elasticsearch windows service fails due to an uncaught exception, it does not register a service stopped event. Currently, we have monitoring in place for windows services to get an alert, whenever the service is stopped or started. Due to Elasticsearch failing to register the event, we don't get an alert. If I manually stop the service, then we see the windows event getting logged and alert also gets generated.

ES is being run as a single node cluster.

**Steps to reproduce**:
Not sure how to reproduce it. Logs says that its an out of memory error and there is a ElasticsearchUncaughtExceptionHandler entry.

**Provide logs (if relevant)**:
```
[2018-05-08T23:01:19,022][WARN ][o.e.c.r.a.DiskThresholdMonitor] [XXXXXXXX-YYYYYYYYY] high disk watermark [90%] exceeded on [OdQ_MbyjRoq8SoTCMZ7gbQ][XXXXXXXX-YYYYYYYYY][D:\Sites\xxxxxxxx\Databases\yyyyyyyy\nodes\0] free: 2.6gb[8.6%], shards will be relocated away from this node
[2018-05-08T23:01:21,141][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246978] overhead, spent [2.1s] collecting in the last [2.2s]
[2018-05-08T23:01:22,149][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246979] overhead, spent [1.6s] collecting in the last [1.8s]
[2018-05-08T23:01:23,340][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246980] overhead, spent [1.1s] collecting in the last [1.1s]
[2018-05-08T23:01:27,975][INFO ][t.b.r.c.s.SettingsPoller ] [CLUSTERWIDE SETTINGS] Cluster not ready...
[2018-05-08T23:01:28,042][ERROR][o.e.x.m.c.i.IndexStatsCollector] [XXXXXXXX-YYYYYYYYY] collector [index-stats] timed out when collecting data
[2018-05-08T23:01:28,042][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246981] overhead, spent [4.4s] collecting in the last [4.7s]
[2018-05-08T23:01:29,066][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246982] overhead, spent [1s] collecting in the last [1s]
[2018-05-08T23:01:30,263][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246983] overhead, spent [1.1s] collecting in the last [1.1s]
[2018-05-08T23:01:31,875][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246984] overhead, spent [1.5s] collecting in the last [1.6s]
[2018-05-08T23:01:33,050][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246985] overhead, spent [1s] collecting in the last [1.1s]
[2018-05-08T23:01:36,410][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246986] overhead, spent [2.3s] collecting in the last [1.1s]
[2018-05-08T23:01:37,813][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246987] overhead, spent [2.2s] collecting in the last [3.5s]
[2018-05-08T23:01:38,814][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246988] overhead, spent [961ms] collecting in the last [1s]
[2018-05-08T23:01:40,172][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246989] overhead, spent [1.3s] collecting in the last [1.3s]
[2018-05-08T23:01:42,630][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246990] overhead, spent [1s] collecting in the last [1s]
[2018-05-08T23:01:45,018][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246991] overhead, spent [3.6s] collecting in the last [3.7s]
[2018-05-08T23:01:45,024][INFO ][t.b.r.c.s.SettingsPoller ] [CLUSTERWIDE SETTINGS] Cluster not ready...
[2018-05-08T23:01:47,566][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246992] overhead, spent [2.3s] collecting in the last [2.5s]
[2018-05-08T23:01:47,587][ERROR][o.e.x.m.c.i.IndicesStatsCollector] [XXXXXXXX-YYYYYYYYY] collector [indices-stats] timed out when collecting data
[2018-05-08T23:01:49,736][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246993] overhead, spent [2.1s] collecting in the last [2.1s]
[2018-05-08T23:01:51,027][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246994] overhead, spent [1.2s] collecting in the last [1.2s]
[2018-05-08T23:01:51,039][INFO ][t.b.r.c.s.SettingsPoller ] [CLUSTERWIDE SETTINGS] Cluster not ready...
[2018-05-08T23:01:52,074][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246995] overhead, spent [1s] collecting in the last [1s]
[2018-05-08T23:01:53,349][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246996] overhead, spent [1.2s] collecting in the last [1.2s]
[2018-05-08T23:01:55,748][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246997] overhead, spent [2.2s] collecting in the last [2.4s]
[2018-05-08T23:01:57,538][INFO ][t.b.r.c.s.SettingsPoller ] [CLUSTERWIDE SETTINGS] Cluster not ready...
[2018-05-08T23:01:58,879][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246998] overhead, spent [3s] collecting in the last [3.1s]
[2018-05-08T23:02:00,149][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][246999] overhead, spent [1.1s] collecting in the last [1.2s]
[2018-05-08T23:02:01,775][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][247000] overhead, spent [1.5s] collecting in the last [1.6s]
[2018-05-08T23:02:02,717][INFO ][t.b.r.c.s.SettingsPoller ] [CLUSTERWIDE SETTINGS] Cluster not ready...
[2018-05-08T23:02:04,147][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][247001] overhead, spent [2.2s] collecting in the last [2.3s]
[2018-05-08T23:02:06,193][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][247002] overhead, spent [1.9s] collecting in the last [2s]
[2018-05-08T23:02:07,824][INFO ][t.b.r.c.s.SettingsPoller ] [CLUSTERWIDE SETTINGS] Cluster not ready...
[2018-05-08T23:02:10,758][INFO ][o.e.c.r.a.DiskThresholdMonitor] [XXXXXXXX-YYYYYYYYY] low disk watermark [85%] exceeded on [OdQ_MbyjRoq8SoTCMZ7gbQ][XXXXXXXX-YYYYYYYYY][D:\Sites\xxxxxxxx\Databases\yyyyyyyy\nodes\0] free: 4gb[13.4%], replicas will not be assigned to this node
[2018-05-08T23:02:13,709][INFO ][t.b.r.c.s.SettingsPoller ] [CLUSTERWIDE SETTINGS] Cluster not ready...
[2018-05-08T23:02:14,614][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][247003] overhead, spent [5.2s] collecting in the last [1.6s]
[2018-05-08T23:02:15,676][INFO ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][247004] overhead, spent [3.8s] collecting in the last [7.8s]
[2018-05-08T23:02:18,197][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][247005] overhead, spent [2.4s] collecting in the last [2.5s]
[2018-05-08T23:02:24,891][INFO ][t.b.r.c.s.SettingsPoller ] [CLUSTERWIDE SETTINGS] Cluster not ready...
[2018-05-08T23:02:24,892][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][247006] overhead, spent [6.4s] collecting in the last [1s]
[2018-05-08T23:02:28,373][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][247008] overhead, spent [2.3s] collecting in the last [2.3s]
[2018-05-08T23:02:30,932][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][247009] overhead, spent [2.5s] collecting in the last [2.5s]
[2018-05-08T23:02:30,937][INFO ][t.b.r.c.s.SettingsPoller ] [CLUSTERWIDE SETTINGS] Cluster not ready...
[2018-05-08T23:02:31,998][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][247010] overhead, spent [1s] collecting in the last [1s]
[2018-05-08T23:02:41,065][INFO ][t.b.r.c.s.SettingsPoller ] [CLUSTERWIDE SETTINGS] Cluster not ready...
[2018-05-08T23:02:42,108][WARN ][o.e.m.j.JvmGcMonitorService] [XXXXXXXX-YYYYYYYYY] [gc][247011] overhead, spent [9.4s] collecting in the last [1.5s]
[2018-05-08T23:02:46,632][INFO ][t.b.r.c.s.SettingsPoller ] [CLUSTERWIDE SETTINGS] Cluster not ready...
[2018-05-08T23:02:52,851][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [XXXXXXXX-YYYYYYYYY] fatal error in thread [elasticsearch[XXXXXXXX-YYYYYYYYY][generic][T#2]], exiting
java.lang.OutOfMemoryError: Java heap space
	at org.apache.lucene.index.ParallelPostingsArray.<init>(ParallelPostingsArray.java:33) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
	at org.apache.lucene.index.FreqProxTermsWriterPerField$FreqProxPostingsArray.<init>(FreqProxTermsWriterPerField.java:205) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
	at org.apache.lucene.index.FreqProxTermsWriterPerField$FreqProxPostingsArray.newInstance(FreqProxTermsWriterPerField.java:230) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
	at org.apache.lucene.index.ParallelPostingsArray.grow(ParallelPostingsArray.java:46) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
	at org.apache.lucene.index.TermsHashPerField$PostingsBytesStartArray.grow(TermsHashPerField.java:250) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
	at org.apache.lucene.util.BytesRefHash.add(BytesRefHash.java:271) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
	at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:149) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:796) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:447) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:403) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:232) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:478) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1571) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
	at org.elasticsearch.index.engine.InternalEngine.update(InternalEngine.java:740) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.index.engine.InternalEngine.indexIntoLucene(InternalEngine.java:603) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:505) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:556) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.index.shard.IndexShard.access$300(IndexShard.java:142) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.index.shard.IndexShard$IndexShardRecoveryPerformer.index(IndexShard.java:1841) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.index.shard.TranslogRecoveryPerformer.performRecoveryOperation(TranslogRecoveryPerformer.java:165) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.index.shard.TranslogRecoveryPerformer.recoveryFromSnapshot(TranslogRecoveryPerformer.java:86) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.index.shard.IndexShard$IndexShardRecoveryPerformer.recoveryFromSnapshot(IndexShard.java:1836) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:241) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:220) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:91) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:1036) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:990) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:360) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:90) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.index.shard.StoreRecovery$$Lambda$1788/209912095.run(Unknown Source) ~[?:?]
	at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:257) ~[elasticsearch-5.5.1.jar:5.5.1]
	at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:88) ~[elasticsearch-5.5.1.jar:5.5.1]
```

**Comment by jpountz** [comment]
cc @elastic/microsoft

**Comment by jasontedor** [comment]
I do not think that you want to rely on the stop event being registered to monitor whether or not the Elasticsearch service is healthy. The problem here is that if, for example, there is a JVM crash then it is also the case that the stop method would not be called, the application is terminating abnormally. In this case, you would be left with the service not running yet no stop event being registered. We treat a fatal error (such as an out of memory error) the same way: we immediately terminate the running JVM without calling allowing any shutdown code to execute as we do not trust the state of the JVM at this point.

As such, I am going to close this as won't fix and I encourage you to find a different method for monitoring the health of the Elasticsearch service on Windows.

**Comment by jasontedor** [comment]
> So why can't the stop event be registered?

It’s not that it *can’t*, it’s that we *won’t*. As I explained:

> We treat a fatal error (such as an out of memory error) the same way [as a JVM crash]: we immediately terminate the running JVM without calling allowing any shutdown code to execute as we do not trust the state of the JVM at this point.

It’s a deliberate decision to not execute any shutdown code as we do not trust the state of the JVM.

**Comment by askids** [comment]
On a side note, how does Elastic stack monitor other windows services? Won't it also be relying on the registered windows events?
