### ISSUE TITLE
[CI] InternalExtendedStatsTests.testReduceRandom fails assertion

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#30506]
https://github.com/elastic/elasticsearch/issues/24931 popped up again on current master:

reproduce with: 

```
./gradlew :server:test -Dtests.seed=97B9AEB9875197B5 -Dtests.class=org.elasticsearch.search.aggregations.metrics.InternalExtendedStatsTests -Dtests.method="testReduceRandom" -Dtests.security.manager=true -Dtests.locale=de-CH -Dtests.timezone=Europe/Sofia
```

```
FAILURE 0.03s J2 | InternalExtendedStatsTests.testReduceRandom <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<321.2197163576493> but was:<321.2197163657984>
   > 	at __randomizedtesting.SeedInfo.seed([97B9AEB9875197B5:578402A8A10C0EE3]:0)
   > 	at org.elasticsearch.search.aggregations.metrics.InternalExtendedStatsTests.assertReduced(InternalExtendedStatsTests.java:87)
   > 	at org.elasticsearch.search.aggregations.metrics.InternalExtendedStatsTests.assertReduced(InternalExtendedStatsTests.java:37)
   > 	at org.elasticsearch.test.InternalAggregationTestCase.testReduceRandom(InternalAggregationTestCase.java:262)
```

**Comment by colings86** [comment]
@polyfractal would you be able to take a look?
