### ISSUE TITLE
[CI] IntegTestZipClientYamlTestSuiteIT indices.split fails on windows tests

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#30503]
Two rest tests keep failing due to timeouts on multijob-windows-compatibility.

links:

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1620/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/1047/console

reproduce:

```
./gradlew :distribution:archives:integ-test-zip:integTestRunner \
  -Dtests.seed=F724E83BFA960B1D \
  -Dtests.class=org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT \
  -Dtests.method="test {p0=indices.split/20_source_mapping/Split index ignores target template mapping}" \
  -Dtests.security.manager=true \
  -Dtests.locale=it-CH \
  -Dtests.timezone=Etc/GMT-7

./gradlew :distribution:archives:integ-test-zip:integTestRunner \
  -Dtests.seed=F724E83BFA960B1D \
  -Dtests.class=org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT \
  -Dtests.method="test {p0=indices.split/10_basic/Split from 1 to N}" \
  -Dtests.security.manager=true \
  -Dtests.locale=it-CH \
  -Dtests.timezone=Etc/GMT-7
```

Only `test {p0=indices.split/20_source_mapping/Split index ignores target template mapping}` fails on `6.x`, both fail on `master`

stacktrace:

```
  1> [2018-05-10T06:02:54,341][INFO ][o.e.t.r.IntegTestZipClientYamlTestSuiteIT] [test {p0=indices.split/20_source_mapping/Split index ignores target template mapping}]: before test

  1> [2018-05-10T06:03:24,426][INFO ][o.e.t.r.IntegTestZipClientYamlTestSuiteIT] Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "cluster_name" : "distribution_archives_integ-test-zip_integTestCluster",
  1>       "status" : "green",
  1>       "timed_out" : false,
  1>       "number_of_nodes" : 1,
  1>       "number_of_data_nodes" : 1,
  1>       "active_primary_shards" : 1,
  1>       "active_shards" : 1,
  1>       "relocating_shards" : 0,
  1>       "initializing_shards" : 0,
  1>       "unassigned_shards" : 0,
  1>       "delayed_unassigned_shards" : 0,
  1>       "number_of_pending_tasks" : 0,
  1>       "number_of_in_flight_fetch" : 0,
  1>       "task_max_waiting_in_queue_millis" : 0,
  1>       "active_shards_percent_as_number" : 100.0
  1>     }
  1>   }
  1> }]

  1> [2018-05-10T06:03:24,482][INFO ][o.e.t.r.IntegTestZipClientYamlTestSuiteIT] [test {p0=indices.split/20_source_mapping/Split index ignores target template mapping}]: after test

  2> REPRODUCE WITH: gradlew :distribution:archives:integ-test-zip:integTestRunner -Dtests.seed=F724E83BFA960B1D -Dtests.class=org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT -Dtests.method="test {p0=indices.split/20_source_mapping/Split index ignores target template mapping}" -Dtests.security.manager=true -Dtests.locale=it-CH -Dtests.timezone=Etc/GMT-7

ERROR   30.2s | IntegTestZipClientYamlTestSuiteIT.test {p0=indices.split/20_source_mapping/Split index ignores target template mapping} <<< FAILURES!
   > Throwable #1: java.lang.RuntimeException: Failure at [indices.split/20_source_mapping:57]: listener timeout after waiting for [30000] ms
   > 	at __randomizedtesting.SeedInfo.seed([F724E83BFA960B1D:7F70D7E1546A66E5]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:358)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:333)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.io.IOException: listener timeout after waiting for [30000] ms
   > 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:794)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:174)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:268)
   > 	at org.elasticsearch.test.rest.yaml.ClientYamlTestClient.callApi(ClientYamlTestClient.java:173)
   > 	at org.elasticsearch.test.rest.yaml.ClientYamlTestExecutionContext.callApiInternal(ClientYamlTestExecutionContext.java:158)
   > 	at org.elasticsearch.test.rest.yaml.ClientYamlTestExecutionContext.callApi(ClientYamlTestExecutionContext.java:90)
   > 	at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:223)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:349)
   > 	... 37 more
```

**Comment by jasontedor** [comment]
I suspect this is the same as #30416; these tests should be skipped and folded into that single issue.

**Comment by talevy** [comment]
@jasontedor woops, didn't see the connection. I'll update the awaitsfix bugUrl links later and close this issue in favor of the other
