### ISSUE TITLE
Error while creating repository type:azure| RepositoryVerificationException

### ISSUE THREAD

**Issue by ritxos** [elastic/elasticsearch#30568]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 2.4.1

**Plugins installed**: [cloud-azure -->  2.4.1]

**JVM version** (`java -version`):openjdk version "1.8.0_171"

**OS version** (`uname -a` if on a Unix-like system): CentOS 6.7  x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

cloud azure plugin for ES backup is not able to create reposotiry type azure --curl -XPUT http://localhost:9200/_snapshot/backup-test -d '{ "type": "azure" }'

Its throwing error shown in logs.
**Important:** it is able to create a default container called elasticsearch-snapshots under specified storage account

**Steps to reproduce**:
**tail of elasticsearch.yml**

http.cors.enabled: true
http.cors.allow-origin: "*"

cloud.azure.storage.default.account: xxxxxxxxxxxxxxxxx
cloud.azure.storage.default.key: xxxxxxxxxxxxxxxxx

**Provide logs (if relevant)**:
```
[2018-05-14 09:55:37,262][WARN ][rest.suppressed          ] path: /_snapshot/backup-test, params: {repository=backup-test}
RepositoryVerificationException[[backup-test] [-ig2axJpTRKq_cnvDlk0jQ, 'RepositoryVerificationException[[backup-test] a file written by master to the store [elasticsearch-snapshots] cannot be accessed on the node [{Adobeidx-dev-elasticsearch-master-AS0}{-ig2axJpTRKq_cnvDlk0jQ}{10.67.1.201}{10.67.1.201:9300}{max_local_storage_nodes=1, data=false, master=true}]. This might indicate that the store [elasticsearch-snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node]'], [qEfi7CbFRzixLG1lb-_wpg, 'RemoteTransportException[[Adobeidx-dev-elasticsearch-master-AS2][10.67.1.203:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[backup-test] a file written by master to the store [elasticsearch-snapshots] cannot be accessed on the node [{Adobeidx-dev-elasticsearch-master-AS2}{qEfi7CbFRzixLG1lb-_wpg}{10.67.1.203}{10.67.1.203:9300}{max_local_storage_nodes=1, data=false, master=true}]. This might indicate that the store [elasticsearch-snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node];'], [0k66VNK5R9-JkE3ILVYyXw, 'RemoteTransportException[[Adobeidx-dev-elasticsearch-master-AS1][10.67.1.202:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[backup-test] a file written by master to the store [elasticsearch-snapshots] cannot be accessed on the node [{Adobeidx-dev-elasticsearch-master-AS1}{0k66VNK5R9-JkE3ILVYyXw}{10.67.1.202}{10.67.1.202:9300}{max_local_storage_nodes=1, data=false, master=true}]. This might indicate that the store [elasticsearch-snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node];'], [Q605qroUTYiJtJWZdEVkdA, 'RemoteTransportException[[adobeidx-dev-elasticsearch-data-SS000000.1u5kw5wmbcsuncze0uc1yey2xb.cx.internal.cloudapp.net][10.67.1.196:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[backup-test] a file written by master to the store [elasticsearch-snapshots] cannot be accessed on the node [{adobeidx-dev-elasticsearch-data-SS000000.1u5kw5wmbcsuncze0uc1yey2xb.cx.internal.cloudapp.net}{Q605qroUTYiJtJWZdEVkdA}{10.67.1.196}{10.67.1.196:9300}{max_local_storage_nodes=1, master=false}]. This might indicate that the store [elasticsearch-snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node];'], [vcVys6hXTKO6z8qwSqucKQ, 'RemoteTransportException[[adobeidx-dev-elasticsearch-data-SS000001.1u5kw5wmbcsuncze0uc1yey2xb.cx.internal.cloudapp.net][10.67.1.197:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[backup-test] a file written by master to the store [elasticsearch-snapshots] cannot be accessed on the node [{adobeidx-dev-elasticsearch-data-SS000001.1u5kw5wmbcsuncze0uc1yey2xb.cx.internal.cloudapp.net}{vcVys6hXTKO6z8qwSqucKQ}{10.67.1.197}{10.67.1.197:9300}{max_local_storage_nodes=1, master=false}]. This might indicate that the store [elasticsearch-snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node];'], [biturw8YQEqmW0XuhU2ZTw, 'RemoteTransportException[[adobeidx-dev-elasticsearch-data-SS000002.1u5kw5wmbcsuncze0uc1yey2xb.cx.internal.cloudapp.net][10.67.1.198:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[backup-test] a file written by master to the store [elasticsearch-snapshots] cannot be accessed on the node [{adobeidx-dev-elasticsearch-data-SS000002.1u5kw5wmbcsuncze0uc1yey2xb.cx.internal.cloudapp.net}{biturw8YQEqmW0XuhU2ZTw}{10.67.1.198}{10.67.1.198:9300}{max_local_storage_nodes=1, master=false}]. This might indicate that the store [elasticsearch-snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node];']]]
	at org.elasticsearch.repositories.RepositoriesService$VerifyingRegisterRepositoryListener$1.onResponse(RepositoriesService.java:440)
	at org.elasticsearch.repositories.RepositoriesService$VerifyingRegisterRepositoryListener$1.onResponse(RepositoriesService.java:436)
	at org.elasticsearch.repositories.RepositoriesService$3.onResponse(RepositoriesService.java:224)
	at org.elasticsearch.repositories.RepositoriesService$3.onResponse(RepositoriesService.java:214)
	at org.elasticsearch.repositories.VerifyNodeRepositoryAction.finishVerification(VerifyNodeRepositoryAction.java:116)
	at org.elasticsearch.repositories.VerifyNodeRepositoryAction$1.handleException(VerifyNodeRepositoryAction.java:107)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleException(MessageChannelHandler.java:184)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handlerResponseError(MessageChannelHandler.java:174)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:122)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
