### ISSUE TITLE
[CI] CorruptedFileIT.testCorruptPrimaryNoReplica

### ISSUE THREAD

**Issue by vladimirdolzhenko** [elastic/elasticsearch#30741]
similar to https://github.com/elastic/elasticsearch/issues/8515 - but it has been reported that original root cause was solved.

LOG: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1726/console

```
 2> REPRODUCE WITH: ./gradlew :server:integTest -Dtests.seed=9C447E00AC0E83A0 -Dtests.class=org.elasticsearch.index.store.CorruptedFileIT -Dtests.method="testCorruptPrimaryNoReplica" -Dtests.security.manager=true -Dtests.locale=ar-JO -Dtests.timezone=America/Argentina/Ushuaia
FAILURE  303s J0 | CorruptedFileIT.testCorruptPrimaryNoReplica <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: is <RED>
   >      but: was <GREEN>
   > 	at __randomizedtesting.SeedInfo.seed([9C447E00AC0E83A0:B978C8BE40A1B7B7]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.index.store.CorruptedFileIT.testCorruptPrimaryNoReplica(CorruptedFileIT.java:285)
   > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dnhatn** [comment]
This may relate to #30577. I will look at this.

**Comment by dnhatn** [comment]
I have reproduced and verified that this test and #30577 are caused by the same source.
