### ISSUE TITLE
[ci] RecoveryDuringReplicationTests.testRecoveryAfterPrimaryPromotion

### ISSUE THREAD

**Issue by andyb-elastic** [elastic/elasticsearch#30767]
On 6.3, doesn't reproduce for me

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java8,nodes=virtual&&linux/54/console

[build-54.txt](https://github.com/elastic/elasticsearch/files/2024329/build-54.txt)

```
./gradlew :server:test -Dtests.seed=D285400CC661A041 -Dtests.class=org.elasticsearch.index.replication.RecoveryDuringReplicationTests -Dtests.method="testRecoveryAfterPrimaryPromotion" -Dtests.security.manager=true -Dtests.locale=ar -Dtests.timezone=America/Boise
```

```
  1> [2018-05-21T14:13:22,449][WARN ][o.e.i.e.Engine           ] [s1] [test][0] failed engine [exception during primary-replica resync]
  1> java.util.ConcurrentModificationException: null
  1>    at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361) ~[?:1.8.0_162]
  1>    at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_162]
  1>    at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[?:1.8.0_162]
  1>    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:1.8.0_162]
  1>    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_162]
  1>    at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_162]
  1>    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_162]
  1>    at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_162]
  1>    at org.elasticsearch.index.replication.ESIndexLevelReplicationTestCase$ReplicationAction$ReplicasRef.performOn(ESIndexLevelReplicationTestCase.java:523) ~[test/:?]
  1>    at org.elasticsearch.action.support.replication.ReplicationOperation.performOnReplica(ReplicationOperation.java:162) ~[main/:?]
  1>    at org.elasticsearch.action.support.replication.ReplicationOperation.performOnReplicas(ReplicationOperation.java:150) ~[main/:?]
  1>    at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:121) ~[main/:?]
  1>    at org.elasticsearch.index.replication.ESIndexLevelReplicationTestCase$ReplicationAction.execute(ESIndexLevelReplicationTestCase.java:456) ~[test/:?]
  1>    at org.elasticsearch.index.replication.ESIndexLevelReplicationTestCase$ReplicationGroup.lambda$new$0(ESIndexLevelReplicationTestCase.java:140) ~[test/:?]
  1>    at org.elasticsearch.index.shard.PrimaryReplicaSyncer$SnapshotSender.doRun(PrimaryReplicaSyncer.java:256) ~[main/:?]
  1>    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[main/:?]
  1>    at org.elasticsearch.index.shard.PrimaryReplicaSyncer.resync(PrimaryReplicaSyncer.java:169) ~[main/:?]
  1>    at org.elasticsearch.index.shard.PrimaryReplicaSyncer.resync(PrimaryReplicaSyncer.java:137) ~[main/:?]
  1>    at org.elasticsearch.index.replication.ESIndexLevelReplicationTestCase$ReplicationGroup.lambda$promoteReplicaToPrimary$8(ESIndexLevelReplicationTestCase.java:293) ~[test/:?]
  1>    at org.elasticsearch.index.shard.IndexShard.lambda$updateShardState$0(IndexShard.java:503) ~[main/:?]
  1>    at org.elasticsearch.index.shard.IndexShardOperationPermits.doBlockOperations(IndexShardOperationPermits.java:177) [main/:?]
  1>    at org.elasticsearch.index.shard.IndexShardOperationPermits.access$000(IndexShardOperationPermits.java:54) [main/:?]
  1>    at org.elasticsearch.index.shard.IndexShardOperationPermits$1.doRun(IndexShardOperationPermits.java:143) [main/:?]
  1>    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:724) [main/:?]
  1>    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [main/:?]
  1>    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
  1>    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
  1>    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

**Comment by ywelsch** [comment]
I've pushed a fix: f9e8afd357b
