### ISSUE TITLE
[ci] GeoDistanceTests.testReadFromSerializationBWC

### ISSUE THREAD

**Issue by andyb-elastic** [elastic/elasticsearch#30764]
A couple of these on 5.6

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+multijob-unix-compatibility/os=sles/1099/console

```
 2> REPRODUCE WITH: ./gradlew :core:test -Dtests.seed=7CA8D5A7E57960B5 -Dtests.class=org.elasticsearch.common.geo.GeoDistanceTests -Dtests.me
thod="testReadFromSerializationBWC" -Dtests.security.manager=true -Dtests.locale=vi-VN -Dtests.timezone=Asia/Dacca                            
ERROR   0.31s | GeoDistanceTests.testReadFromSerializationBWC <<< FAILURES!                                                                   
   > Throwable #1: java.io.IOException: Unknown GeoDistance ordinal [2]
   >    at __randomizedtesting.SeedInfo.seed([7CA8D5A7E57960B5:1459AC1C89232B9D]:0)                                                           
   >    at org.elasticsearch.common.geo.GeoDistance.readFromStream(GeoDistance.java:65)                                                       
   >    at org.elasticsearch.common.geo.GeoDistanceTests.testReadFromSerializationBWC(GeoDistanceTests.java:85)                               
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                     
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                   
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                           
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)  
   >    at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by talevy** [comment]
interesting... taking a look. thanks @andyb-elastic

**Comment by andyb-elastic** [comment]
@talevy np I'm gonna mute it for now

**Comment by talevy** [comment]
This should be fixed by https://github.com/elastic/elasticsearch/commit/9fac1315de6695e16b6ac94f4bb76f57be3a93e8
