### ISSUE TITLE
[ci] ClusterStatsTests.testClusterStats

### ISSUE THREAD

**Issue by andyb-elastic** [elastic/elasticsearch#30770]
On 5.6, doesn't reproduce. Opening this because I'm pretty sure I've triaged this test a couple of times

https://internal-ci.elastic.co/job/elastic+x-pack-elasticsearch+5.6+multijob-windows-compatibility/1703

[build-1703.txt](https://github.com/elastic/elasticsearch/files/2024512/build-1703.txt)

```
gradlew :x-pack-elasticsearch:plugin:test -Dtests.seed=388A867F89019B8C -Dtests.class=org.elasticsearch.xpack.monitoring.resolver.cluster.ClusterStatsTests -Dtests.method="testClusterStats" -Dtests.security.manager=true -Dtests.locale=hu -Dtests.timezone=Antarctica/DumontDUrvill
```

The exception that bubbles up

```
   > Throwable #1: Failed to execute phase [query], all shards failed^M
   >    at __randomizedtesting.SeedInfo.seed([388A867F89019B8C:3CB91C12F761DFA]:0)^M
   >    at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:272)^M
^M
   >    at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:130)^M
   >    at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:241)^M
```

From node logs

```
  1> Caused by: org.elasticsearch.xpack.monitoring.exporter.ExportException: failed to flush export bulks^M
  1>    at org.elasticsearch.xpack.monitoring.exporter.ExportBulk$Compound.lambda$null$0(ExportBulk.java:167) ~[main/:?]^M
  1>    ... 65 more^M
  1> Caused by: org.elasticsearch.xpack.monitoring.exporter.ExportException: bulk [default_local] reports failures when exporting documents^M
  1>    at org.elasticsearch.xpack.monitoring.exporter.local.LocalBulk.throwExportException(LocalBulk.java:126) ~[main/:?]^M
  1>    ... 63 more^M
```

**Comment by whw-github** [comment]
I am also a problem. Have you found a solution?
