### ISSUE TITLE
Issue with running tests (requiring ES server startup) on a custom junit runner

### ISSUE THREAD

**Issue by shashanka981** [elastic/elasticsearch#30802]
@RunWith(MyCustomRunner.class)
public class TestESIndeingPerformance{

@BeforeClass
public static void setup(){
// start Elasticsearch server
}

@test
public void performindexing() {
// java apis to initiate indexing
}

}

Hi , 

We are using ElasticSearch 5.6.9 and we are seeing an exception during ES server startup....This was working well with ES 2.4 version...The error basically suggests to use Randomized runner annotation on the test class....but i am looking for a way to use my own custom junit runner and should be able to start the server without having to annotate the test class with randomized runner.I am not using any ElasticSearch helper tests to start the cluster

org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.IllegalStateException: running tests but failed to invoke RandomizedContext#getRandom
  at org.elasticsearch.action.bulk.CustomTransportBulkAction.<init>(Unknown Source)
  while locating org.elasticsearch.action.bulk.CustomTransportBulkAction
Caused by: java.lang.IllegalStateException: running tests but failed to invoke RandomizedContext#getRandom
	at org.elasticsearch.common.Randomness.get(Randomness.java:105)
	at org.elasticsearch.action.ingest.IngestActionForwarder.<init>(IngestActionForwarder.java:42)
	at org.elasticsearch.action.bulk.CustomTransportBulkAction.<init>(CustomTransportBulkAction.java:122)
	at org.elasticsearch.action.bulk.CustomTransportBulkAction.<init>(CustomTransportBulkAction.java:101)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:49)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:825)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:50)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:191)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:183)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:818)
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:183)
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:173)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:161)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:96)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:42)
	at org.elasticsearch.node.Node.<init>(Node.java:499)
	at com.pega.platform.search.internal.ESSearchProviderEmbedded$ESNode.<init>(ESSearchProviderEmbedded.java:234)
	at com.pega.platform.search.internal.ESSearchProviderEmbedded.invokeES(ESSearchProviderEmbedded.java:239)
	at com.pega.platform.search.internal.ESSearchProviderEmbedded.initializeElasticSearchNode(ESSearchProviderEmbedded.java:206)
	at com.pega.platform.search.internal.ESSearchProviderEmbedded.startSearch(ESSearchProviderEmbedded.java:76)
	at com.pega.platform.search.searchmanager.internal.AbstractSearchManager.startSearch(AbstractSearchManager.java:22)
	at com.pega.platform.pegasearch.searchmanager.internal.PegaSearchProviderImpl._initializeFTS(PegaSearchProviderImpl.java:309)
	at com.pega.platform.pegasearch.searchmanager.internal.PegaSearchProviderImpl.initializeFTS(PegaSearchProviderImpl.java:179)
	at com.pega.platform.pegasearch.searchmanager.internal.PegaSearchManagerImpl.initializeFTS(PegaSearchManagerImpl.java:120)
	at com.pega.pegarules.search.internal.PRSearchProviderImpl.initializeFTS(PRSearchProviderImpl.java:152)
	at com.pega.pegarules.search.internal.es.data.TestESState._initializeToTestESServer(TestESState.java:173)
	at com.pega.pegarules.search.internal.es.data.TestESState.startTestESServer(TestESState.java:83)
	at com.pega.pegarules.search.internal.es.TestElasticSearchV7$3.action(TestElasticSearchV7.java:176)
	at com.pega.pegarules.engine.typeapi.UserSession$12.run(UserSession.java:1719)
	at com.pega.pegarules.session.internal.PRSessionProviderImpl.performTargetActionWithLock(PRSessionProviderImpl.java:1367)
	at com.pega.pegarules.session.internal.PRSessionProviderImpl.doWithRequestorLocked(PRSessionProviderImpl.java:1108)
	at com.pega.pegarules.session.internal.PRSessionProviderImpl.doWithRequestorLocked(PRSessionProviderImpl.java:915)
	at com.pega.pegarules.engine.typeapi.UserSession.doWithSession(UserSession.java:1672)
	at com.pega.pegarules.engine.typeapi.UserSession.doWithSession(UserSession.java:1650)
	at com.pega.pegarules.engine.typeapi.UserSession.doWithSession(UserSession.java:1645)
	at com.pega.pegarules.engine.typeapi.UserSession.doWithSession(UserSession.java:1640)
	at com.pega.pegarules.search.internal.es.TestElasticSearchV7.setupOnce(TestElasticSearchV7.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.pega.pegarules.unittest.util.BeforeAndAfter$1.evaluate(BeforeAndAfter.java:49)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.elasticsearch.common.Randomness.get(Randomness.java:101)
	... 65 more
Caused by: java.lang.IllegalStateException: No context information for thread: Thread[id=1, name=L34990WIN, state=RUNNABLE, group=main]. Is this thread running under a class com.carrotsearch.randomizedtesting.RandomizedRunner runner context? Add @RunWith(class com.carrotsearch.randomizedtesting.RandomizedRunner.class) to your test class. Make sure your code accesses random contexts within @BeforeClass and @AfterClass boundary (for example, static test class initializers are not permitted to access random contexts).
	at com.carrotsearch.randomizedtesting.RandomizedContext.context(RandomizedContext.java:244)
	at com.carrotsearch.randomizedtesting.RandomizedContext.current(RandomizedContext.java:151)
	... 70 more

2) Error injecting constructor, java.lang.IllegalArgumentException: transport handlers for action indices:data/write/custom-bulk is already registered
  at org.elasticsearch.action.bulk.CustomTransportBulkAction.<init>(Unknown Source)
  while locating org.elasticsearch.action.bulk.CustomTransportBulkAction
  while locating org.elasticsearch.action.support.TransportAction annotated with @org.elasticsearch.common.inject.multibindings.Element(setName=,uniqueId=67)
Caused by: java.lang.IllegalArgumentException: transport handlers for action indices:data/write/custom-bulk is already registered
	at org.elasticsearch.transport.TransportService.registerRequestHandler(TransportService.java:743)
	at org.elasticsearch.transport.TransportService.registerRequestHandler(TransportService.java:737)
	at org.elasticsearch.action.support.HandledTransportAction.<init>(HandledTransportAction.java:50)
	at org.elasticsearch.action.support.HandledTransportAction.<init>(HandledTransportAction.java:43)
	at org.elasticsearch.action.bulk.CustomTransportBulkAction.<init>(CustomTransportBulkAction.java:113)
	at org.elasticsearch.action.bulk.CustomTransportBulkAction.<init>(CustomTransportBulkAction.java:101)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:49)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:825)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
	at org.elasticsearch.common.inject.InternalFactoryToProvide...

**Comment by colings86** [comment]
We require that if Elasticsearch is started with JUnit on the classpath that RandomizedRunner is used in the test suite. This is because there are elements within the server that use RNG and requiring RandomizedRunner on the classspath when running Junit tests means that we can make these RNG's deterministic so we can reproduce failures more easily. This is built into the server itself (see `Randomness` class) so we cannot make mistakes and accidentally create a test that is hard to reproduce.

Additionally, we do not advise writing tests which run against an embedded server as running the Elasticsearch server embedded is not a supported mode. It looks like from the name of your test that you are writing performance tests so its especially important that you do not run again an embedded server as the results of your test will be affected by the fact that the server is running embedded (for example, because the heap is shared GC pauses will not be realistic since it will need to mark and clean up object both from the server and from the test).

Instead we recommend that you run Elasticsearch separately to your test suite in a configuration as close to your production scenario as possible (e.g. using the same machine specs, OS version, JVM version, etc.). This makes the test fair since you are testing against an Elasticsearch server which is running in the manner it expects.

You might also be interested in looking at Rally ([https://esrally.readthedocs.io/en/stable/](https://esrally.readthedocs.io/en/stable/)) which was built specifically to help run performance tests against Elasticsearch servers. You can write tests in Rally that run your specific workloads against Elasticsearch and output detailed results. You can even run competitions to determine, for example, which server configuration suits your workloads the best.
