### ISSUE TITLE
6.3 BWC tests fail due to cluster not forming in time

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#30872]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+bwc-tests/76/console failed with:

```
Execution failed for task ':qa:full-cluster-restart:v6.2.3#oldClusterTestCluster#wait'.
```

There was a period of 1 minute (12:21:39 to 12:22:39) when the two nodes appear to have done nothing.

From https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+bwc-tests/76/artifact/qa/full-cluster-restart/build/cluster/v6.2.3%23oldClusterTestCluster%20node0/elasticsearch-6.2.3/logs/full-cluster-restart.log we have:

```
[2018-05-25T12:21:39,480][DEBUG][i.n.u.Recycler           ] -Dio.netty.recycler.ratio: disabled
[2018-05-25T12:21:39,588][DEBUG][o.e.a.a.c.h.TransportClusterHealthAction] [node-0] no known master node, scheduling a retry
[2018-05-25T12:22:39,735][DEBUG][o.e.d.z.ZenDiscovery     ] [node-0] filtered ping responses: (ignore_non_masters [false])
	--> ping_response{node [{node-1}{7we3cM92RBiEeyHOLXPnNA}{JJqxkZNHQzmb5h4hPpcIeg}{127.0.0.1}{127.0.0.1:42703}{testattr=test}], id[1], master [null],cluster_state_version [-1], cluster_name[full-cluster-restart]}
	--> ping_response{node [{node-0}{yIxEqDBZTyWeG1BDRkpkuw}{4yPA2SMJTaG3e7U8bUpxmQ}{127.0.0.1}{127.0.0.1:36596}{testattr=test}], id[22], master [null],cluster_state_version [-1], cluster_name[full-cluster-restart]}
[2018-05-25T12:22:39,763][DEBUG][o.e.a.a.c.h.TransportClusterHealthAction] [node-0] timed out while retrying [cluster:monitor/health] after failure (timeout [30s])
[2018-05-25T12:22:39,766][DEBUG][o.e.c.s.MasterService    ] [node-0] processing [zen-disco-election-stop [{node-1}{7we3cM92RBiEeyHOLXPnNA}{JJqxkZNHQzmb5h4hPpcIeg}{127.0.0.1}{127.0.0.1:42703}{testattr=test} elected]]: execute
[2018-05-25T12:22:39,766][WARN ][r.suppressed             ] path: /_cluster/health, params: {wait_for_status=yellow, wait_for_nodes=>=2}
org.elasticsearch.discovery.MasterNotDiscoveredException: null
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:213) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:317) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:244) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:581) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573) [elasticsearch-6.2.3.jar:6.2.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
[2018-05-25T12:22:39,779][DEBUG][o.e.c.s.MasterService    ] [node-0] processing [zen-disco-election-stop [{node-1}{7we3cM92RBiEeyHOLXPnNA}{JJqxkZNHQzmb5h4hPpcIeg}{127.0.0.1}{127.0.0.1:42703}{testattr=test} elected]]: took [11ms] no change in cluster state
```

And from https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+bwc-tests/76/artifact/qa/full-cluster-restart/build/cluster/v6.2.3%23oldClusterTestCluster%20node1/elasticsearch-6.2.3/logs/full-cluster-restart.log we have:

```
[2018-05-25T12:21:39,431][DEBUG][i.n.u.Recycler           ] -Dio.netty.recycler.ratio: disabled
[2018-05-25T12:22:39,754][DEBUG][o.e.d.z.ZenDiscovery     ] [node-1] filtered ping responses: (ignore_non_masters [false])
	--> ping_response{node [{node-0}{yIxEqDBZTyWeG1BDRkpkuw}{4yPA2SMJTaG3e7U8bUpxmQ}{127.0.0.1}{127.0.0.1:36596}{testattr=test}], id[19], master [null],cluster_state_version [-1], cluster_name[full-cluster-restart]}
	--> ping_response{node [{node-1}{7we3cM92RBiEeyHOLXPnNA}{JJqxkZNHQzmb5h4hPpcIeg}{127.0.0.1}{127.0.0.1:42703}{testattr=test}], id[5], master [null],cluster_state_version [-1], cluster_name[full-cluster-restart]}
[2018-05-25T12:22:39,756][DEBUG][o.e.d.z.ZenDiscovery     ] [node-1] elected as master, waiting for incoming joins ([1] needed)
```

**Comment by droberts195** [comment]
There's a very similar problem on the 6.x branch in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+bwc-tests/896/console

```
> Task :x-pack:qa:full-cluster-restart:without-system-key:v6.3.0-SNAPSHOT#oldClusterTestCluster#wait FAILED
```

The two node logs are https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+bwc-tests/896/artifact/x-pack/qa/full-cluster-restart/without-system-key/build/cluster/v6.3.0-SNAPSHOT%23oldClusterTestCluster%20node1/elasticsearch-6.3.0-SNAPSHOT/logs/full-cluster-restart.log and https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+bwc-tests/896/artifact/x-pack/qa/full-cluster-restart/without-system-key/build/cluster/v6.3.0-SNAPSHOT%23oldClusterTestCluster%20node0/elasticsearch-6.3.0-SNAPSHOT/logs/full-cluster-restart.log

Possibly some sort of SSL problem is involved here:

```
[2018-05-25T15:15:41,809][DEBUG][o.e.a.a.c.h.TransportClusterHealthAction] [node-0] no known master node, scheduling a retry
[2018-05-25T15:15:41,916][DEBUG][i.n.h.s.SslHandler       ] [id: 0x7d4fdc0e, L:/0:0:0:0:0:0:0:1:43166 - R:/0:0:0:0:0:0:0:1:43038] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
[2018-05-25T15:15:43,027][DEBUG][i.n.h.s.SslHandler       ] [id: 0x5252e761, L:/127.0.0.1:58202 - R:127.0.0.1/127.0.0.1:45288] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
[2018-05-25T15:15:43,237][DEBUG][i.n.h.s.SslHandler       ] [id: 0x21ef999c, L:/127.0.0.1:41841 - R:/127.0.0.1:45342] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
[2018-05-25T15:15:43,837][DEBUG][o.e.d.z.ZenDiscovery     ] [node-0] filtered ping responses: (ignore_non_masters [false])
	--> ping_response{node [{node-1}{4EaAwbvGTOyfrDoaLjYIRQ}{9WuQfjivQzqFa31aJwAR7g}{127.0.0.1}{127.0.0.1:45288}{testattr=test, ml.machine_memory=16825737216, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true}], id[6], master [null],cluster_state_version [-1], cluster_name[full-cluster-restart]}
	--> ping_response{node [{node-0}{cPxoRyj2SXWAhTirMYyeWA}{B5H7cRAkT5u_v6R2kx5mkQ}{127.0.0.1}{127.0.0.1:41841}{ml.machine_memory=16825737216, xpack.installed=true, testattr=test, ml.max_open_jobs=20, ml.enabled=true}], id[46], master [null],cluster_state_version [-1], cluster_name[full-cluster-restart]}
[2018-05-25T15:15:44,135][DEBUG][i.n.h.s.SslHandler       ] [id: 0x7d4fdc0e, L:/0:0:0:0:0:0:0:1:43166 - R:/0:0:0:0:0:0:0:1:43038] Swallowing a harmless 'connection reset by peer / broken pipe' error that occurred while writing close_notify in response to the peer's close_notify
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:?]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:283) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:250) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:226) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:382) ~[?:?]
	at io.netty.buffer.PooledHeapByteBuf.setBytes(PooledHeapByteBuf.java:261) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343) ~[netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.16.Final.jar:4.1.16.Final]
	at java.lang.Thread.run(Thread.java:844) [?:?]
[2018-05-25T15:16:14,951][DEBUG][o.e.a.a.c.h.TransportClusterHealthAction] [node-0] timed out while retrying [cluster:monitor/health] after failure (timeout [30s])
[2018-05-25T15:15:44,136][DEBUG][i.n.h.s.SslHandler       ] [id: 0x21ef999c, L:/127.0.0.1:41841 - R:/127.0.0.1:45342] Swallowing a harmless 'connection reset by peer / broken pipe' error that occurred while writing close_notify in response to the peer's close_notify
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:?]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:283) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:250) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:226) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:382) ~[?:?]
	at io.netty.buffer.PooledHeapByteBuf.setBytes(PooledHeapByteBuf.java:261) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343) ~[netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.16.Final.jar:4.1.16.Final]
	at java.lang.Thread.run(Thread.java:844) [?:?]
[2018-05-25T15:16:14,956][DEBUG][o.e.c.s.MasterService    ] [node-0] processing [zen-disco-election-stop [{node-1}{4EaAwbvGTOyfrDoaLjYIRQ}{9WuQfjivQzqFa31aJwAR7g}{127.0.0.1}{127.0.0.1:45288}{testattr=test, ml.machine_memory=16825737216, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true} elected]]: execute
[2018-05-25T15:16:15,008][WARN ][r.suppressed             ] path: /_cluster/health, params: {wait_for_status=yellow, wait_for_nodes=2}
org.elasticsearch.discovery.MasterNotDiscoveredException: null
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:223) [elasticsearch-6.3.0-SNAPSHOT.jar:6.3.0-SNAPSHOT]
	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:317) [elasticsearch-6.3.0-SNAPSHOT.jar:6.3.0-SNAPSHOT]
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:244) [elasticsearch-6.3.0-SNAPSHOT.jar:6.3.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:576) [elasticsearch-6.3.0-SNAPSHOT.jar:6.3.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:625) [elasticsearch-6.3.0-SNAPSHOT.jar:6.3.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
[2018-05-25T15:16:15,048][DEBUG][o.e.c.s.MasterService    ] [node-0] processing [zen-disco-election-stop [{node-1}{4EaAwbvGTOyfrDoaLjYIRQ}{9WuQfjivQzqFa31aJwAR7g}{127.0.0.1}{127.0.0.1:45288}{testattr=test, ml.machine_memory=16825737216, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true} elected]]: took [56ms] no change in cluster state
[2018-05-25T15:16:15,054][WARN ][o.e.d.z.ZenDiscovery     ] [node-0] failed to connect to master [{node-1}{4EaAwbvGTOyfrDoaLjYIRQ}{9WuQfjivQzqFa31aJwAR7g}{127.0.0.1}{127.0.0.1:45288}{testattr=test, ml.machine_memory=16825737216, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true}], retrying...
org.elasticsearch.transport.ConnectTransportException: [node-1][127.0.0.1:45288] connect_exception
	at org.elasticsearch.transport.TcpChannel.awaitConnected(TcpChannel.java:165) ~[elasticsearch-6.3.0-SNAPSHOT.jar:6.3.0-SNAPSHOT]
	at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:612) ~[elasticsearch-6.3.0-SNAPSHOT.jar:6.3.0-SNAPSHOT]
	at org.elasticsearch.transport.TcpTransport.connectToNode(TcpTransport.java:511) ~[elasticsearch-6.3.0-SNAPSHOT.jar:6.3.0-SNAPSHOT]
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:331) ~[elasticsearch-6.3.0-SNAPSHOT.jar:6.3.0-SNAPSHOT]
	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:318) ~[elasticsearch-6.3.0-SNAPSHOT.jar:6.3.0-SNAPSHOT]
	at org.elasticsearch.discovery.zen.ZenDiscovery.joinElectedMaster(ZenDiscovery.java:509) [elasticsearch-6.3.0-SNAPSHOT.jar:6.3.0-SNAPSHOT]
	at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:477) [elasticsearch-6.3.0-SNAPSHOT.jar:6.3.0-SNAPSHOT]
	at org.elasticsearch.discovery.zen.ZenDiscovery.access$2500(ZenDiscovery.java:90) [elasticsearch-6.3.0-SNAPSHOT.jar:6.3.0-SNAPSHOT]
	at org.elasticsearch.discovery.zen.ZenDiscovery$JoinThreadControl$1.run(ZenDiscovery.java:1247) [elasticsearch-6.3.0-SNAPSHOT.jar:6.3.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:625) [elasticsearch-6.3.0-SNAPSHOT.jar:6.3.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedSocketException: Connection reset by peer: 127.0.0.1/127.0.0.1:45288
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323) ~[?:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[?:?]
	... 1 more
Caused by: java.net.SocketException: Connection reset by peer
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323) ~[?:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[?:?]
	... 1 more
```

**Comment by ywelsch** [comment]
The issue seem to have stopped occurring these last days, so I'm closing this.

**Comment by ywelsch** [comment]
@jkakavas as you've opened this, can you add more info here as to why?

**Comment by jkakavas** [comment]
Apologies, I had it opened in a tab ,probably a click missfire
