### ISSUE TITLE
ingest-user-agent integ tests failed while wiping cluster between tests

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#30881]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1769/console suffered two test failures while running the integ tests for the ingest-user-agent plugin:

```
org.elasticsearch.ingest.useragent.IngestUserAgentClientYamlTestSuiteIT test {yaml=ingest-useragent/20_useragent_processor/Test user agent processor with defaults}
org.elasticsearch.ingest.useragent.IngestUserAgentClientYamlTestSuiteIT test {yaml=ingest-useragent/30_custom_regex/Test user agent processor with custom regex file}
```

However, on closer examination it wasn't the tests themselves that failed but the cleanup in between tests.

The first exception is this:

```
   > Throwable #1: java.io.IOException: listener timeout after waiting for [30000] ms
   > 	at __randomizedtesting.SeedInfo.seed([95955EB3606B1633:1DC16169CE977BCB]:0)
   > 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:794)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:174)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:219)
   > 	at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:234)
   > 	at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:150)
   > 	at java.lang.Thread.run(Thread.java:748)
```

The node log shows this:

```
[2018-05-25T15:14:05,868][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node-0] [test/DozuAJmXTNOaPxo2lxRywQ] deleting index
[2018-05-25T15:14:36,048][INFO ][o.e.c.m.MetaDataCreateIndexService] [node-0] [test] creating index, cause [auto(bulk api)], templates [], shards [5]/[1], mappings []
[2018-05-25T15:14:36,117][WARN ][o.e.a.b.TransportShardBulkAction] [node-0] unexpected error during the primary phase for action [indices:data/write/bulk[s]], request [BulkShardRequest [[test][3]] containing [index {[test][test][1], source[{"field1":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.149 Safari/537.36","user_agent":{"os":"Other","name":"Test","os_name":"Other","device":"Other"}}]}]]
org.elasticsearch.index.IndexNotFoundException: no such index
	at org.elasticsearch.cluster.routing.RoutingTable.shardRoutingTable(RoutingTable.java:137) ~[elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.primary(TransportReplicationAction.java:791) [elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:726) [elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$2.onNewClusterState(TransportReplicationAction.java:877) [elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onNewClusterState(ClusterStateObserver.java:303) [elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.clusterChanged(ClusterStateObserver.java:191) [elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateListeners$7(ClusterApplierService.java:506) [elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3585) [?:?]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735) [?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) [?:?]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:503) [elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:486) [elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:430) [elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:160) [elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:625) [elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) [elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) [elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
[2018-05-25T15:14:36,208][INFO ][o.e.c.m.MetaDataMappingService] [node-0] [test/r4CPzmugTNW5RKSz6RZopw] create_mapping [test]
[2018-05-25T15:14:36,257][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node-0] [test/r4CPzmugTNW5RKSz6RZopw] deleting index
```

It looks like deleting the `test` index took longer than 30 seconds, causing the client to give up.  Then the following test caused the index to be recreated by indexing a document into it.  But the routing got confused between the old `test` index and the new `test` index.

**Comment by talevy** [comment]
Closing since this looks unrelated to the user-agent tests specifically and most likely a CI blurp.
