### ISSUE TITLE
[CI] CliSelectIT#testMultiLineSelect failure

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#30912]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/2082/console

Cannot reproduce locally, but these are the lines (interestingly logged twice?):

```
19:50:42   2> REPRODUCE WITH: ./gradlew :x-pack:qa:sql:multinode:integTestRunner -Dtests.seed=FC98E0C4FEE9571A -Dtests.class=org.elasticsearch.xpack.qa.sql.multinode.CliSelectIT -Dtests.method="testMultiLineSelect" -Dtests.security.manager=true -Dtests.locale=bg-BG -Dtests.timezone=MST
19:50:42   2> REPRODUCE WITH: ./gradlew :x-pack:qa:sql:multinode:integTestRunner -Dtests.seed=FC98E0C4FEE9571A -Dtests.class=org.elasticsearch.xpack.qa.sql.multinode.CliSelectIT -Dtests.method="testMultiLineSelect" -Dtests.security.manager=true -Dtests.locale=bg-BG -Dtests.timezone=MST
```

Error:
```
19:50:42    > Throwable #1: org.junit.ComparisonFailure: expected:<[?1l>[?1000l[?2004l[[?1h=[?2004h[33m   | [0mFRO]M> but was:<[?1l>[?1000l[?2004l[]M>
19:50:42    > 	at org.elasticsearch.xpack.qa.sql.cli.EmbeddedCli.command(EmbeddedCli.java:247)
19:50:42    > 	at org.elasticsearch.xpack.qa.sql.cli.CliIntegrationTestCase.command(CliIntegrationTestCase.java:72)
19:50:42    > 	at org.elasticsearch.xpack.qa.sql.cli.SelectTestCase.testMultiLineSelect(SelectTestCase.java:24)
19:50:42    > 	at java.lang.Thread.run(Thread.java:748)Throwable #2: java.lang.AssertionError: unconsumed lines
19:50:42    > Expected: an empty collection
19:50:42    >      but: <[test;, [?1h=[?2004h[33m   | [0mFROM, [?1l>[?1000l[?2004l[?1h=[?2004h[33m   | [0mtest;, [?1l>[?1000l[?2004l  test_field   , ---------------, test_value     ]>
19:50:42    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
19:50:42    > 	at org.elasticsearch.xpack.qa.sql.cli.EmbeddedCli.close(EmbeddedCli.java:212)
19:50:42    > 	at org.elasticsearch.xpack.qa.sql.cli.CliIntegrationTestCase.orderlyShutdown(CliIntegrationTestCase.java:50)
19:50:42    > 	at java.lang.Thread.run(Thread.java:748)
```

Since as far as I could search this only happened once so far I will not disable it for now.

**Comment by imotov** [comment]
@colings86 I can keep an eye for it. It didn't fail once in the last time 8 weeks and all logs from the previous failures are long gone now. It is not reproducible, so I cannot really act on it at the moment.

**Comment by colings86** [comment]
I'm going to close this as its not 12 weeks since we've seen a failure and without logs there isn't much we can do. If this reproduces on CI please re-open and add the relevant info
