### ISSUE TITLE
[CI] Windows compatibility tests fail trying to install analysis-icu

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#30915]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/1087/console

Looks like this isn't the first failure of this kind, at least since #1084 this looks similar:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/

The error suggests either the file is not there or the path is somehow wrong:

```
18:43:05 -> Downloading file:/C:/Users/jenkins/workspace/elastic elasticsearch 6.x multijob-windows-compatibility/docs/build/cluster/integTestCluster--batch0node0/plugins--batch0tmp/analysis-icu-6.4.0-SNAPSHOT.zip
18:43:05 Exception in thread "main" java.io.FileNotFoundException: C:\Users\jenkins\workspace\elastic+elasticsearch+6.x+multijob-windows-compatibility\docs\build\cluster\integTestCluster--batch0node0\plugins--batch0tmp\analysis-icu-6.4.0-SNAPSHOT.zip (The system cannot find the path specified)
18:43:05 	at java.io.FileInputStream.open0(Native Method)
18:43:05 	at java.io.FileInputStream.open(FileInputStream.java:195)
18:43:05 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
18:43:05 	at java.io.FileInputStream.<init>(FileInputStream.java:93)
18:43:05 	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
18:43:05 	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
18:43:05 
18:43:05 	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:381)
18:43:05 	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:279)
18:43:05 	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:230)
18:43:05 	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:217)
18:43:05 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
18:43:05 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
18:43:05 	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:79)
18:43:05 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
18:43:05 	at org.elasticsearch.cli.Command.main(Command.java:90)
18:43:05 	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)
18:43:05 :docs:integTestCluster#installAnalysisIcuPlugin (Thread[Task worker for ':',5,main]) completed. Took 1.372 secs.
```

**Comment by cbuescher** [comment]
Also: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/1088/console

**Comment by jasontedor** [comment]
It can not easily be muted other than disabling all Windows builds; effectively installation of any plugin in CI for Windows will be broken right now until this can be addressed. The problem is the spaces in the path names and poor argument substitution.

**Comment by ywelsch** [comment]
@jasontedor Can you assign someone to work on this? Having no green builds on Windows CI (see https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/) for over a week is not acceptable.

**Comment by jasontedor** [comment]
I opened #31034.
