### ISSUE TITLE
[CI] PutIndexTemplateRequestTests.testFromXContent fails reproducibly

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#30911]
I saw at least two instances today:

On 6.x: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java10,nodes=virtual&&linux/80/console

This reproduces on 6.x for me:
```
REPRODUCE WITH: ./gradlew :server:test \
  -Dtests.seed=4077509E4F46A969 \
  -Dtests.class=org.elasticsearch.action.admin.indices.template.put.PutIndexTemplateRequestTests \
  -Dtests.method="testFromXContent" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-CC \
  -Dtests.timezone=US/Pacific-New
```

```
10:35:30    > Throwable #1: java.lang.AssertionError: 
10:35:30    > Expected: <[org.elasticsearch.action.admin.indices.alias.Alias@df79bfbc, org.elasticsearch.action.admin.indices.alias.Alias@6d4376, org.elasticsearch.action.admin.indices.alias.Alias@d8ddcb43]>
10:35:30    >      but: was <[org.elasticsearch.action.admin.indices.alias.Alias@6d4376, org.elasticsearch.action.admin.indices.alias.Alias@d9ea79d7, org.elasticsearch.action.admin.indices.alias.Alias@d8ddcb43]>
10:35:30    > 	at __randomizedtesting.SeedInfo.seed([4077509E4F46A969:611F6586C6E149B3]:0)
10:35:30    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
10:35:30    > 	at org.elasticsearch.action.admin.indices.template.put.PutIndexTemplateRequestTests.assertEqualInstances(PutIndexTemplateRequestTests.java:189)
10:35:30    > 	at org.elasticsearch.action.admin.indices.template.put.PutIndexTemplateRequestTests.assertEqualInstances(PutIndexTemplateRequestTests.java:48)
```

**Comment by cbuescher** [comment]
Little bit older, also 6.x: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=sles/1084/console

```
REPRODUCE WITH: ./gradlew :server:test \
  -Dtests.seed=C71E6952CE9AC649 \
  -Dtests.class=org.elasticsearch.action.admin.indices.template.put.PutIndexTemplateRequestTests \
  -Dtests.method="testFromXContent" \
  -Dtests.security.manager=true \
  -Dtests.locale=nn-NO \
  -Dtests.timezone=Pacific/Tahiti
```

**Comment by cbuescher** [comment]
One of the aliases with a weird unicode name cannot be parsed back exactly:
expected: {"¥ÛøÀ»ÅÄÌa":{"index_routing":"ꡟꡒꡑꡏꡧꡒꡐꡏꡨa","search_routing":"a"}}
actual: {"¥ÛøÀ» ÅÄÌa":{"index_routing":"ꡟꡒꡑꡏꡧꡒꡐꡏꡨa","search_routing":"a"}}

The Character that doesn't survive the roundtrip seems to be https://unicode-table.com/en/search/?q=%C2%85. I'm not sure if randomRealisticUnicodeOfLengthBetween() as the alias name should be used in the randomization, although it seems to work most of the time.

**Comment by cbuescher** [comment]
This small test shouws the problem is particular to the Yaml xContent type. There parsing the offending fieldname back to a map fails:

```
public void testWeirdFieldName() throws IOException {
        String badName = new String(new char[] { 165, 219, 248, 192, 187, 133, 197, 196, 204, 97 });
        XContentBuilder builder = XContentFactory.contentBuilder(XContentType.YAML);
        builder.startObject();
        builder.field(badName, "value");
        builder.endObject();
        try (XContentParser parser = createParser(builder)) {
            Map<String, Object> map = parser.map();
            assertEquals(1, map.keySet().size());
            assertEquals("value", map.get(badName));
        }
    }
```
