### ISSUE TITLE
[CI] qa:rolling-upgrade test fail for XPackIT#testIndexTemplatesCreated

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#30925]
Several of these failures occuring atm on 6.x and 6.3, they are running the upgrade tests from 5.6 or 6.2 (pre-xpack) clusters.

One example:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+default-distro-bwc-tests/14/console

```
REPRODUCE WITH: ./gradlew :qa:rolling-upgrade:v5.6.4#upgradedClusterTestRunner -Dtests.seed=EFB59C3CA8522ACC -Dtests.class=org.elasticsearch.upgrades.XPackIT -Dtests.method="testIndexTemplatesCreated" -Dtests.security.manager=true -Dtests.locale=vi -Dtests.timezone=Asia/Kuching -Dtests.distribution=zip
```

```
Throwable #1: java.lang.AssertionError: expected:<[.ml-anomalies-, .ml-meta, .ml-notifications, .ml-state, .triggered_watches, .watch-history-8, .watches, logstash-index-template, security-index-template, security_audit_log]> but was:<[.ml-anomalies-, .ml-meta, .ml-notifications, .ml-state, .monitoring-alerts, .monitoring-beats, .monitoring-es, .monitoring-kibana, .monitoring-logstash, .triggered_watches, .watch-history-8, .watches, logstash-index-template, security-index-template, security_audit_log]>
07:57:25    > 	at __randomizedtesting.SeedInfo.seed([EFB59C3CA8522ACC:F92DBA3047E2D5C3]:0)
07:57:25    > 	at org.elasticsearch.upgrades.XPackIT.lambda$testIndexTemplatesCreated$0(XPackIT.java:119)
07:57:25    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:767)
07:57:25    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:741)
07:57:25    > 	at org.elasticsearch.upgrades.XPackIT.testIndexTemplatesCreated(XPackIT.java:101)
07:57:25    > 	at java.lang.Thread.run(Thread.java:748)
```

The error looks like there are indices missing, the expected ones are:
```
.ml-anomalies-, 
.ml-meta, 
.ml-notifications, 
.ml-state, 
.triggered_watches, 
.watch-history-8, 
.watches, 
logstash-index-template, 
security-index-template, 
security_audit_log
```

but the actual ones are:
```
.ml-anomalies-, 
.ml-meta, 
.ml-notifications, 
.ml-state, 
.monitoring-alerts, 
.monitoring-beats, 
.monitoring-es, 
.monitoring-kibana, 
.monitoring-logstash, 
.triggered_watches, 
.watch-history-8, 
.watches, 
logstash-index-template, 
security-index-template, 
security_audit_log
```

So all the ".monitoring" indices are whats extra.

I cannot reproduce using the exact reproduce line from above (fails with There were no executed tests: 1 suite, 1 test, 1 ignored (1 assumption)), when I run `./gradlew :qa:rolling-upgrade:v5.6.4#upgradedClusterTestRunner` it passes.

**Comment by cbuescher** [comment]
Other occurences:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+default-distro/15/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+default-distro-bwc-tests/15/console

**Comment by cbuescher** [comment]
@nik9000 looks like you just recently added that test, can you take a look?

**Comment by nik9000** [comment]
I'll take it!

**Comment by nik9000** [comment]
I believe I fixed it with the commits above!
