### ISSUE TITLE
Timeout occurred in master node due to long metaspace gc

### ISSUE THREAD

**Issue by wyukawa** [elastic/elasticsearch#30991]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
6.2.2

**Plugins installed**: []
x-pack monitoring

**JVM version** (`java -version`):
1.8.0_151

**OS version** (`uname -a` if on a Unix-like system):
CentOS 7.4
```
# uname -a
Linux ... 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:
We can't access data in kibana/elasticsearch when long time(e.g. 20s) gc in master node occurs even though we set CircuitBreaker.
It seems metaspace gc trouble.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

heap setting
```
-Xms12g
-Xmx12g
```

CircuitBreaker setting
```
indices.breaker.total.limit: 20%
indices.breaker.request.limit: 1%
indices.breaker.fielddata.limit: 10%
```

elasticsearch.log
```
[2018-05-30T14:28:37,211][DEBUG][o.e.a.s.TransportSearchAction] [SOMEHOST] [hoge-2018.05.29][81], node[uGzsizf6QIGTNvPzpelfjw], [P], s[STARTED], a[id=_yV5yM-jSxSH5rIFoPiFHg]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[hoge-*], indicesOptions=IndicesOptions[id=39, ignore_unava
ilable=true, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false], types=[], routing='null', preference='1527657970087', requestCache=null, scroll=null, maxConcurrentShardRequests=150, batchedReduceSize=512, preFilterShardSize=64, source={"size"
:0,"query":{"bool":{"must":[{"match_all":{"boost":1.0}},{"match_phrase":{"productKey":{"query":"fuga","slop":0,"boost":1.0}}},{"match_phrase":{"eventType":{"query":"event","slop":0,"boost":1.0}}},{"match_phrase":{"content.event.category":{"query":"scroll_view_sampled","slop":0,"boost":1.0}}},{"range":{"@timestamp":{"from":1527053306882,"to":152765810688
2,"include_lower":true,"include_upper":true,"format":"epoch_millis","boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}},"_source":{"includes":[],"excludes":[]},"stored_fields":"*","docvalue_fields":["@timestamp","sessionTime","time","timestamp"],"script_fields":{},"aggregations":{"2":{"terms":{"field":"userId","size":1000000,"min_doc_count":1,"shard_min_do
c_count":0,"show_term_doc_count_error":false,"order":[{"_count":"desc"},{"_key":"asc"}]}}}}}] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [OTHERHOST][...:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: Query Failed [Failed to execute main query]
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:290) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:107) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.indices.IndicesService.lambda$loadIntoContext$14(IndicesService.java:1133) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.indices.IndicesService.lambda$cacheShardLevelResult$15(IndicesService.java:1186) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.indices.IndicesRequestCache$Loader.load(IndicesRequestCache.java:160) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.indices.IndicesRequestCache$Loader.load(IndicesRequestCache.java:143) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.cache.Cache.computeIfAbsent(Cache.java:412) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.indices.IndicesRequestCache.getOrCompute(IndicesRequestCache.java:116) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.indices.IndicesService.cacheShardLevelResult(IndicesService.java:1192) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.indices.IndicesService.loadIntoContext(IndicesService.java:1132) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:305) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:340) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:316) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:312) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:1002) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.2.2.jar:6.2.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: org.elasticsearch.common.breaker.CircuitBreakingException: [request] Data too large, data for [<reused_arrays>] would be [349147352/332.9mb], which is larger than the limit of [319680020/304.8mb]
        at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.circuitBreak(ChildMemoryCircuitBreaker.java:98) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.limit(ChildMemoryCircuitBreaker.java:170) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.addEstimateBytesAndMaybeBreak(ChildMemoryCircuitBreaker.java:123) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.BigArrays.adjustBreaker(BigArrays.java:408) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.BigArrays.newIntArray(BigArrays.java:558) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.BigArrays.resize(BigArrays.java:582) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.BigArrays.grow(BigArrays.java:597) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.grow(BucketsAggregator.java:68) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator.getLeafCollector(GlobalOrdinalsStringTermsAggregator.java:137) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.search.aggregations.AggregatorBase.getLeafCollector(AggregatorBase.java:167) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.search.aggregations.AggregatorBase.getLeafCollector(AggregatorBase.java:40) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.apache.lucene.search.MultiCollector.getLeafCollector(MultiCollector.java:121) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
        at org.apache.lucene.search.FilterCollector.getLeafCollector(FilterCollector.java:40) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
        at org.elasticsearch.search.query.CancellableCollector.getLeafCollector(CancellableCollector.java:51) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:651) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
        at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:191) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:462) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:265) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:107) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.indices.IndicesService.lambda$loadIntoContext$14(IndicesService.java:1133) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.indices.IndicesService.lambda$cacheShardLevelResult$15(IndicesService.java:1186) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.indices.IndicesRequestCache$Loader.load(IndicesRequestCache.java:160) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.indices.IndicesRequestCache$Loader.load(IndicesRequestCache.java:143) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.cache.Cache.computeIfAbsent(Cache.java:412) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.indices.IndicesRequestCache.getOrCompute(IndicesRequestCache.java:116) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.indices.IndicesService.cacheShardLevelResult(IndicesService.java:1192) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.indices.IndicesService.loadIntoContext(IndicesService.java:1132) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:305) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:340) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:316) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:312) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:1002) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.2.2.jar:6.2.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_151]
[2018-05-30T14:28:52,198][ERROR][o.e.x.m.c.i.IndexStatsCollector] [SOMEHOST] collector [index-stats] timed out when collecting data
[2018-05-30T14:28:52,201][WARN ][o.e.m.j.JvmGcMonitorService] [SOMEHOST] [gc][old][7947902][3039] duration [14.7s], collections [1]/[15.5s], total [14.7s]/[5.7m], memory [10.5gb]->[7.5gb]/[11.7gb], all_pools {[young] [1gb]->[142.1mb]/[1.8gb]}{[survivor] [232.9mb]->[0b]/[232.9mb]}{[old] [9.2gb]->[7.5gb]/[9.7gb]}
[2018-05-30T14:28:52,202][WARN ][o.e.m.j.JvmGcMonitorService] [SOMEHOST] [gc][7947902] overhead, spent [14.7s] collecting in the last [15.5s]
[2018-05-30T14:28:54,449][WARN ][o.e.m.j.JvmGcMonitorService] [SOMEHOST] [gc][young][7947903][479782] duration [1.4s], collections [1]/[2.2s], total [1.4s]/[5.7h], memory [7.5gb]->[9.1gb]/[11.7gb], all_pools {[young] [142.1mb]->[3.9mb]/[1.8gb]}{[survivor] [0b]->[232.9mb]/[232.9mb]}{[old] [7.5gb]->[8.8gb]/[9.7gb]}
[2018-05-30T14:28:54,449][WARN ][o.e.m.j.JvmGcMonitorService] [SOMEHOST] [gc][7947903] overhead, spent [1.4s] collecting in the last [2.2s]
[2018-05-30T14:29:16,897][ERROR][o.e.x.m.c.i.IndexRecoveryCollector] [SOMEHOST] collector [index_recovery] timed out when collecting data
[2018-05-30T14:29:16,977][WARN ][o.e.m.j.JvmGcMonitorService] [SOMEHOST] [gc][old][7947905][3040] duration [21.3s], collections [1]/[21.5s], total [21.3s]/[6m], memory [10.8gb]->[10.5gb]/[11.7gb], all_pools {[young] [1.7gb]->[801.6mb]/[1.8gb]}{[survivor] [232.9mb]->[0b]/[232.9mb]}{[old] [8.8gb]->[9.7gb]/[9.7gb]}
[2018-05-30T14:29:16,978][WARN ][o.e.m.j.JvmGcMonitorService] [SOMEHOST] [gc][7947905] overhead, spent [21.3s] collecting in the last [21.5s]
[2018-05-30T14:29:16,984][DEBUG][o.e.a.a.c.n.s.TransportNodesStatsAction] [SOMEHOST] failed to execute on node [MnmJrA8JTb6IJBOz8QOJlw]
org.elasticsearch.transport.ReceiveTimeoutTransportException: [OTHERHOST][...:9300][cluster:monitor/nodes/stats[n]] request_id [3719416549] timed out after [24770ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:982) [elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573) [elasticsearch-6.2.2.jar:6.2.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[2018-05-30T14:29:17,031][DEBUG][o.e.a.a.c.n.s.TransportNodesStatsAction] [SOMEHOST] failed to execute on node [FU9MpUVaRE-3aL6ZSunCKw]
org.elasticsearch.transport.ReceiveTimeoutTransportException: [OTHERHOST][...:9300][cluster:monitor/nodes/stats[n]] request_id [3719416563] timed out after [24818ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:982) [elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573) [elasticsearch-6.2.2.jar:6.2.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[2018-05-30T14:29:17,096][DEBUG][o.e.a.a.c.n.s.TransportNodesStatsAction] [SOMEHOST] failed to execute on node [b60sT9k7QRK755i1dZhVeA]
org.elasticsearch.transport.ReceiveTimeoutTransportException: [OTHERHOST][...:9300][cluster:monitor/nodes/stats[n]] request_id [3719416565] timed out after [24782ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:982) [elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573) [elasticsearch-6.2.2.jar:6.2.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[2018-05-30T14:29:37,977][WARN ][o.e.m.j.JvmGcMonitorService] [SOMEHOST] [gc][old][7947906][3041] duration [20s], collections [1]/[20.9s], total [20s]/[6.4m], memory [10.5gb]->[10.9gb]/[11.7gb], all_pools {[young] [801.6mb]->[1.2gb]/[1.8gb]}{[survivor] [0b]->[0b]/[232.9mb]}{[old] [9.7gb]->[9.7gb]/[9.7gb]}
[2018-05-30T14:29:37,977][WARN ][o.e.m.j.JvmGcMonitorService] [SOMEHOST] [gc][7947906] overhead, spent [20s] collecting in the last [20.9s]
[2018-05-30T14:30:04,329][WARN ][o.e.m.j.JvmGcMonitorService] [SOMEHOST] [gc][old][7947907][3042] duration [25.5s], collections [1]/[26.3s], total [25.5s]/[6.8m], memory [10.9gb]->[11.5gb]/[11.7gb], all_pools {[young] [1.2gb]->[1.7gb]/[1.8gb]}{[survivor] [0b]->[0b]/[232.9mb]}{[old] [9.7gb]->[9.7gb]/[9.7gb]}
[2018-05-30T14:30:04,329][WARN ][o.e.m.j.JvmGcMonitorService] [SOMEHOST] [gc][7947907] overhead, spent [25.5s] collecting in the last [26.3s]
[2018-05-30T14:30:26,730][WARN ][o.e.m.j.JvmGcMonitorService] [SOMEHOST] [gc][old][7947909][3043] duration [21s], collections [1]/[21.3s], total [21s]/[7.1m], memory [11.7gb]->[11.5gb]/[11.7gb], all_pools {[young] [1.8gb]->[1.8gb]/[1.8gb]}{[survivor] [229.8mb]->[34.9mb]/[232.9mb]}{[old] [9.7gb]->[9.7gb]/[9.7gb]}
[2018-05-30T14:30:26,730][WARN ][o.e.m.j.JvmGcMonitorService] [SOMEHOST] [gc][7947909] overhead, spent [21s] collecting in the last [21.3s]
[2018-05-30T14:30:53,198][WARN ][o.e.m.j.JvmGcMonitorService] [SOMEHOST] [gc][old][7947912][3044] duration [23.8s], collections [1]/[24.4s], total [23.8s]/[7.5m], memory [11.7gb]->[11.5gb]/[11.7gb], all_pools {[young] [1.8gb]->[1.8gb]/[1.8gb]}{[survivor] [199.9mb]->[17.2mb]/[232.9mb]}{[old] [9.7gb]->[9.7gb]/[9.7gb]}
[2018-05-30T14:30:53,199][WARN ][o.e.m.j.JvmGcMonitorService] [SOMEHOST] [gc][7947912] overhead, spent [23.8s] collecting in the last [24.4s]
[2018-05-30T14:30:53,291][DEBUG][o.e.a.a.c.n.s.TransportNodesStatsAction] [SOMEHOST] failed to execute on node [XpcprzYeQJijywnkuJtDeg]
org.elasticsearch.transport.ReceiveTimeoutTransportException: [OTHERHOST][...:9300][cluster:monitor/nodes/stats[n]] request_id [3719456832] timed out after [26424ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:982) [elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573) [elasticsearch-6.2.2.jar:6.2.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

gc.log
```
2018-05-30T14:28:36.239+0900: 7949531.608: [CMS-concurrent-preclean-start]
2018-05-30T14:28:37.441+0900: 7949532.810: [GC (Allocation Failure) 2018-05-30T14:28:37.441+0900: 7949532.810: [ParNew: 2146944K->2146944K(2146944K), 0.0000268 secs]2018-05-30T14:28:37.441+0900: 7949532.810: [CMS2018-05-30T14:28:37.527+0900: 7949532.896: [CMS-concurrent-preclean: 1.262/1.288 secs] [Times: user=2.42 sys=0.63, real=1.29 secs]
 (concurrent mode failure): 9742574K->7940028K(10197440K), 14.7147751 secs] 11889518K->7940028K(12344384K), [Metaspace: 70788K->70788K(1116160K)], 14.7151336 secs] [Times: user=12.57 sys=2.15, real=14.72 secs]
2018-05-30T14:28:52.964+0900: 7949548.334: [GC (Allocation Failure) 2018-05-30T14:28:52.965+0900: 7949548.334: [ParNew: 1908416K->238528K(2146944K), 1.4565839 secs] 9848444K->9549914K(12344384K), 1.4569066 secs] [Times: user=34.87 sys=0.00, real=1.45 secs]
2018-05-30T14:28:54.425+0900: 7949549.795: [GC (CMS Initial Mark) [1 CMS-initial-mark: 9311386K(10197440K)] 9550295K(12344384K), 0.0196434 secs] [Times: user=0.40 sys=0.00, real=0.02 secs]
2018-05-30T14:28:54.445+0900: 7949549.815: [CMS-concurrent-mark-start]
2018-05-30T14:28:55.533+0900: 7949550.902: [GC (Allocation Failure) 2018-05-30T14:28:55.533+0900: 7949550.902: [ParNew: 2146944K->2146944K(2146944K), 0.0000279 secs]2018-05-30T14:28:55.533+0900: 7949550.902: [CMS2018-05-30T14:28:58.156+0900: 7949553.525: [CMS-concurrent-mark: 3.705/3.711 secs] [Times: user=27.75 sys=3.38, real=3.71 secs]
 (concurrent mode failure): 9311386K->10197439K(10197440K), 21.3634210 secs] 11458330K->10583627K(12344384K), [Metaspace: 70788K->70788K(1116160K)], 21.3637966 secs] [Times: user=32.59 sys=2.83, real=21.37 secs]
2018-05-30T14:29:17.887+0900: 7949573.256: [Full GC (Allocation Failure) 2018-05-30T14:29:17.887+0900: 7949573.256: [CMS: 10197439K->10181654K(10197440K), 19.7006804 secs] 12337332K->11353065K(12344384K), [Metaspace: 70791K->70791K(1116160K)], 19.7010907 secs] [Times: user=17.58 sys=2.12, real=19.70 secs]
2018-05-30T14:29:37.595+0900: 7949592.964: [GC (CMS Initial Mark) [1 CMS-initial-mark: 10181654K(10197440K)] 11370886K(12344384K), 0.3532521 secs] [Times: user=0.33 sys=0.03, real=0.35 secs]
2018-05-30T14:29:37.949+0900: 7949593.318: [CMS-concurrent-mark-start]
2018-05-30T14:29:38.658+0900: 7949594.027: [Full GC (Allocation Failure) 2018-05-30T14:29:38.658+0900: 7949594.027: [CMS2018-05-30T14:29:42.781+0900: 7949598.150: [CMS-concurrent-mark: 4.819/4.832 secs] [Times: user=38.20 sys=2.77, real=4.83 secs]
 (concurrent mode failure): 10181654K->10185968K(10197440K), 25.5792084 secs] 12308899K->11706894K(12344384K), [Metaspace: 70792K->70792K(1116160K)], 25.5795259 secs] [Times: user=46.53 sys=0.68, real=25.58 secs]
2018-05-30T14:30:05.349+0900: 7949620.718: [Full GC (Allocation Failure) 2018-05-30T14:30:05.349+0900: 7949620.718: [CMS: 10191835K->10197440K(10197440K), 20.4127981 secs] 12336543K->11955426K(12344384K), [Metaspace: 70793K->70793K(1116160K)], 20.4131327 secs] [Times: user=20.42 sys=0.00, real=20.41 secs]
2018-05-30T14:30:25.808+0900: 7949641.177: [GC (CMS Initial Mark) [1 CMS-initial-mark: 10197440K(10197440K)] 12106231K(12344384K), 0.6783025 secs] [Times: user=1.00 sys=0.00, real=0.68 secs]
2018-05-30T14:30:26.487+0900: 7949641.856: [CMS-concurrent-mark-start]
2018-05-30T14:30:29.269+0900: 7949644.639: [Full GC (Allocation Failure) 2018-05-30T14:30:29.269+0900: 7949644.639: [CMS2018-05-30T14:30:31.261+0900: 7949646.630: [CMS-concurrent-mark: 4.750/4.774 secs] [Times: user=48.86 sys=3.24, real=4.77 secs]
 (concurrent mode failure): 10197440K->10197439K(10197440K), 23.8162608 secs] 12344384K->12116548K(12344384K), [Metaspace: 70804K->70804K(1116160K)], 23.8165894 secs] [Times: user=33.98 sys=1.50, real=23.82 secs]
2018-05-30T14:30:55.093+0900: 7949670.462: [GC (CMS Initial Mark) [1 CMS-initial-mark: 10197439K(10197440K)] 12258648K(12344384K), 0.7639411 secs] [Times: user=1.00 sys=0.00, real=0.77 secs]
2018-05-30T14:30:55.857+0900: 7949671.227: [CMS-concurrent-mark-start]
2018-05-30T14:30:57.144+0900: 7949672.513: [Full GC (Allocation Failure) 2018-05-30T14:30:57.144+0900: 7949672.513: [CMS2018-05-30T14:31:00.623+0900: 7949675.992: [CMS-concurrent-mark: 4.739/4.766 secs] [Times: user=38.71 sys=1.52, real=4.76 secs]
 (concurrent mode failure): 10197439K->10197439K(10197440K), 26.3049095 secs] 12344372K->12177146K(12344384K), [Metaspace: 70796K->70796K(1116160K)], 26.3052205 secs] [Times: user=44.75 sys=0.37, real=26.31 secs]
 ```

**Comment by tlrx** [comment]
The query contains a term aggregation with `"size": 1000000`, so in the worst cases the node has to compute 1000000 buckets in memory. This adds pressure on memory and can lead to long GCs.  maybe you want to reduce the number of buckets to return, or if you want them all I suggest to use composite aggregation to paginate the results (see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-composite-aggregation.html).
