### ISSUE TITLE
Application using ElasticSearch 6.2.x fails to deploy on TomEE 7.0.4 when 6.1.x deploys flawlessly

### ISSUE THREAD

**Issue by djr4488** [elastic/elasticsearch#31021]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.4

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_171

**OS version** (`uname -a` if on a Unix-like system): (Official Docker image)

**Description of the problem including expected versus actual behavior**:
Fails to deploy on TomEE 7.0.x

**Steps to reproduce**:
I am using Java EE 7, using my own EE producer for a RestHighLevelClient

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. No issues with 6.1.x code it deploys and app works fine
 2. When attempting to use 6.2.x code it fails to deploy with stack trace below
 3.

**Provide logs (if relevant)**:
01-Jun-2018 03:12:44.497 INFO [localhost-startStop-1] org.apache.openejb.util.JarExtractor.extract Extracted path: /usr/local/tomee/webapps/ROOT
01-Jun-2018 03:12:46.428 SEVERE [localhost-startStop-1] sun.reflect.NativeMethodAccessorImpl.invoke ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.tomee.catalina.TomEERuntimeException: org.apache.openejb.OpenEJBException: Unable to create annotation scanner for web module : null
at org.apache.tomee.catalina.TomcatWebAppBuilder.loadApplication(TomcatWebAppBuilder.java:2305)
at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1188)
at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1125)
at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:133)
at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5105)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
... 10 more
Caused by: org.apache.openejb.OpenEJBException: Unable to create annotation scanner for web module : null
at org.apache.openejb.config.DeploymentLoader.addWebModule(DeploymentLoader.java:886)
at org.apache.openejb.config.DeploymentLoader.load(DeploymentLoader.java:233)
at org.apache.tomee.catalina.TomcatWebAppBuilder.loadApplication(TomcatWebAppBuilder.java:2303)
... 16 more
Caused by: java.lang.IllegalArgumentException
at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
at org.apache.xbean.finder.AnnotationFinder.readClassDef(AnnotationFinder.java:1169)
at org.apache.xbean.finder.AnnotationFinder.<init>(AnnotationFinder.java:147)
at org.apache.xbean.finder.AnnotationFinder.<init>(AnnotationFinder.java:160)
at org.apache.openejb.config.FinderFactory$OpenEJBAnnotationFinder.<init>(FinderFactory.java:546)
at org.apache.openejb.config.FinderFactory.newFinder(FinderFactory.java:267)
at org.apache.openejb.config.FinderFactory.create(FinderFactory.java:80)
at org.apache.openejb.config.FinderFactory.createFinder(FinderFactory.java:69)
at org.apache.openejb.config.DeploymentLoader.addWebModule(DeploymentLoader.java:878)
... 18 more
2018-06-01T03:12:46.490200800Z 
01-Jun-2018 03:12:46.428 SEVERE [localhost-startStop-1] sun.reflect.NativeMethodAccessorImpl.invoke Error deploying web application archive [/usr/local/tomee/webapps/ROOT.war]
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:756)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
2018-06-01T03:12:46.507613900Z

**Comment by dadoonet** [comment]
I can't see anything related to elasticsearch in your stacktrace.

I think it's better to open a question on discuss.elastic.co.

**Comment by djr4488** [comment]
I can do that, but the particular error in question indicates it doesn't like a particular build of a class(likely built with Java 10).  6.1.x deploys fine.  So was wondering if something changed in the build 6.2.x build process.

The only hint that the above might be it:
Caused by: java.lang.IllegalArgumentException
at org.apache.xbean.asm5.ClassReader.(Unknown Source)
at org.apache.xbean.asm5.ClassReader.(Unknown Source)
at org.apache.xbean.asm5.ClassReader.(Unknown Source)

And after doing a fairly thorough search for reasons that might cause this came upon a particular similar issue:
https://java.wekeepcoding.com/article/12122117/tomee+webservice+doesn't+deploy+-+asm+error+-+Unable+to+create+annotation+scanner+for+web+module+simple-webservice%3A+43626

The only change was updating to ElasticSearch 6.2.4, when I downgrade back to 6.1.4 everything continues to work.

**Comment by colings86** [comment]
Elasticsearch is not designed to the run embedded in a web container, and this mode of running it is not supported (see the last section in https://www.elastic.co/blog/elasticsearch-the-server). the server is designed to be run as a standalone server and run as described in the installation documentation (see https://www.elastic.co/guide/en/elasticsearch/reference/current/install-elasticsearch.html)

**Comment by dadoonet** [comment]
@colings86 I agree but here I feel like he is just trying to use the HL CLient:

> I am using Java EE 7, using my own EE producer for a RestHighLevelClient

@djr4488 Could you share the `pom.xml` file or gradle deps of your project and confirm that you are not starting elasticsearch, the server, from your application?

**Comment by colings86** [comment]
@djr4488 @dadoonet Sorry I had missed that this is an application using the Elasticsearch client that is deployed in a web container.

**Comment by djr4488** [comment]
This is the pom.xml of the JAR I am using as long as I downgrade to 6.1.4, everything works, 6.2.x I get the above stack traces on deployment.  

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.djr.elastic</groupId>
    <artifactId>elasticee-core</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <elastic.search.version>6.1.2</elastic.search.version>

        <!-- maven build properties -->
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!-- java ee -->
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <version>7.0</version>
            <scope>provided</scope>
        </dependency>

        <!-- logging -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.7</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.0.13</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.0.13</version>
            <scope>compile</scope>
        </dependency>

        <!-- elasticsearch -->
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>${elastic.search.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-client</artifactId>
            <version>${elastic.search.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-high-level-client</artifactId>
            <version>${elastic.search.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>transport</artifactId>
            <version>${elastic.search.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-client-sniffer</artifactId>
            <version>${elastic.search.version}</version>
            <scope>compile</scope>
        </dependency>

        <!-- testing -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.10</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-all</artifactId>
            <version>1.8.4</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.weld.se</groupId>
            <artifactId>weld-se</artifactId>
            <version>2.4.4.Final</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.hk2</groupId>
            <artifactId>hk2</artifactId>
            <version>2.4.0-b11</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-common</artifactId>
            <version>2.16</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jglue.cdi-unit</groupId>
            <artifactId>cdi-unit</artifactId>
            <version>4.0.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hsqldb</groupId>
            <artifactId>hsqldb</artifactId>
            <version>2.3.4</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.6.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by dadoonet** [comment]
Not sure if it will change anything but I'd remove from your `pom.xml`:

```xml
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>${elastic.search.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-client</artifactId>
            <version>${elastic.search.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>transport</artifactId>
            <version>${elastic.search.version}</version>
            <scope>compile</scope>
        </dependency>
```

Only `elasticsearch-rest-high-level-client` is needed and optionally `elasticsearch-rest-client-sniffer`.

**Comment by djr4488** [comment]
I gave that a try, it didn't work.

**Comment by dadoonet** [comment]
Is there a way to create a minimal project that reproduce the problem? And share it on GitHub?

**Comment by djr4488** [comment]
Yes, I can do that.  I will have to do that later today though.

**Comment by djr4488** [comment]
Took me a little bit but I have a project on my github EventLog which has a server module that when deployed to TomEE 7.0.4 displays the behavior as described above. When using 6.2.x cannot deploy the server when using 6.1.x it deploys and works fine.

**Comment by jasontedor** [comment]
I don't think this is an Elasticsearch issue. Either it is a bug in the JDK 9 compiler or a bug in ASM/Tomcat.

**Comment by Gyanar-git** [comment]
Hi All,
I have upgraded the rest high level client from 5.6.5 to 7.3.2,i am seeing the below exceptions for the same:It works perfectly fine when i tried to downgraded to 5.6.5.Can anyone help me the root cause of this issue.I could see some blogs related to the same,but didn't find the solutions yet.Can anyone help me on this.

Caused by: org.apache.openejb.OpenEJBException: Unable to create annotation scanner for web module oi: null
at org.apache.openejb.config.DeploymentLoader.addWebModule(DeploymentLoader.java:844)
at org.apache.openejb.config.DeploymentLoader.load(DeploymentLoader.java:216)
at org.apache.tomee.catalina.TomcatWebAppBuilder.loadApplication(TomcatWebAppBuilder.java:2148)
... 17 more
Caused by: java.lang.IllegalArgumentException
at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
at org.apache.xbean.finder.AnnotationFinder.readClassDef(AnnotationFinder.java:1148)
at org.apache.xbean.finder.AnnotationFinder.<init>(AnnotationFinder.java:139)
at org.apache.xbean.finder.AnnotationFinder.<init>(AnnotationFinder.java:152)
at org.apache.openejb.config.FinderFactory$OpenEJBAnnotationFinder.<init>(FinderFactory.java:514)
at org.apache.openejb.config.FinderFactory.newFinder(FinderFactory.java:259)
at org.apache.openejb.config.FinderFactory.create(FinderFactory.java:77)
at org.apache.openejb.config.FinderFactory.createFinder(FinderFactory.java:66)
at org.apache.openejb.config.DeploymentLoader.addWebModule(DeploymentLoader.java:836)
... 19 more
