### ISSUE TITLE
[CI] EOFException in mixed cluster startup

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#31059]
Errors don't have a reproduce line but occur in startup of mixed clusters.
This is from a PRs CI test:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/10973/consoleFull

```
08:58:14 |    [2018-06-04T08:57:43,226][WARN ][o.e.t.n.Netty4Transport  ] [node-0] exception caught on transport layer [NettyTcpChannel{localAddress=/0:0:0:0:0:0:0:1:39476, remoteAddress=/0:0:0:0:0:0:0:1:40016}], closing connection
08:58:14 |    java.io.EOFException: tried to read: 105 bytes but only 22 remaining
08:58:14 |    	at org.elasticsearch.transport.netty4.ByteBufStreamInput.ensureCanReadBytes(ByteBufStreamInput.java:75) ~[?:?]
08:58:14 |    	at org.elasticsearch.common.io.stream.FilterStreamInput.ensureCanReadBytes(FilterStreamInput.java:80) ~[elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
08:58:14 |    	at org.elasticsearch.common.io.stream.StreamInput.readArraySize(StreamInput.java:1010) ~[elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
08:58:14 |    	at org.elasticsearch.common.io.stream.StreamInput.readString(StreamInput.java:373) ~[elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
08:58:14 |    	at org.elasticsearch.common.io.stream.StreamInput.readStringArray(StreamInput.java:468) ~[elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
08:58:14 |    	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1523) ~[elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
08:58:14 |    	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1415) ~[elasticsearch-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
08:58:14 |    	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:64) ~[transport-netty4-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
```

Similar thing seems to have happened on other branches as well, also apparently in 6.4.0 mixed cluster tests:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+index-lifecycle+feature-branch/45/consoleFull

**Comment by colings86** [comment]
This might be caused by this commit: https://github.com/elastic/elasticsearch/commit/4522b57e079a71c6f8f097dadae2405513f74e0f

The master branch does not seem to be failing though so it could be that last good commit has not caught up for PR branches and feature branches?

**Comment by cbuescher** [comment]
Upon further inspection, this seems to be fixed on master.
