### ISSUE TITLE
MatchPhrase*QueryBuilderTests fails in CI

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#31064]
CI link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1809/console

Failure:

```
11:11:45    > Throwable #1: java.lang.IllegalArgumentException: Can only use phrase queries on text fields - not on [mapped_date] which is of type [date]
11:11:45    > 	at __randomizedtesting.SeedInfo.seed([3D403AF9E530D9AB:CABB38C794B31C41]:0)
11:11:45    > 	at org.elasticsearch.index.mapper.MappedFieldType.phraseQuery(MappedFieldType.java:388)
11:11:45    > 	at org.elasticsearch.index.search.MatchQuery$MatchQueryBuilder.analyzePhrase(MatchQuery.java:364)
11:11:45    > 	at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:330)
11:11:45    > 	at org.elasticsearch.index.search.MatchQuery$MatchQueryBuilder.createFieldQuery(MatchQuery.java:409)
11:11:45    > 	at org.apache.lucene.util.QueryBuilder.createPhraseQuery(QueryBuilder.java:123)
11:11:45    > 	at org.elasticsearch.index.search.MatchQuery.parse(MatchQuery.java:293)
11:11:45    > 	at org.elasticsearch.index.query.MatchPhraseQueryBuilder.doToQuery(MatchPhraseQueryBuilder.java:183)
11:11:45    > 	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:98)
11:11:45    > 	at org.elasticsearch.test.AbstractQueryTestCase.testToQuery(AbstractQueryTestCase.java:416)
11:11:45    > 	at java.lang.Thread.run(Thread.java:748)
```

Reproduction line:

```
./gradlew :server:test \
  -Dtests.seed=3D403AF9E530D9AB \
  -Dtests.class=org.elasticsearch.index.query.MatchPhraseQueryBuilderTests \
  -Dtests.method="testToQuery" \
  -Dtests.security.manager=true \
  -Dtests.locale=zh \
  -Dtests.timezone=Pacific/Enderbury
```

and

```
./gradlew :server:test \
  -Dtests.seed=3D403AF9E530D9AB \
  -Dtests.class=org.elasticsearch.index.query.MatchPhrasePrefixQueryBuilderTests \
  -Dtests.method="testToQuery" \
  -Dtests.security.manager=true \
  -Dtests.locale=is \
  -Dtests.timezone=SystemV/MST7
```

Caused by https://github.com/elastic/elasticsearch/commit/8f4711f3f6fc6a5a190951de4df173eeee015918

@romseygeek can you please have a look at this one?

**Comment by danielmitterdorfer** [comment]
Closing as duplicate https://github.com/elastic/elasticsearch/issues/31061.
