### ISSUE TITLE
rankeval.RatedRequestsTests testXContentParsingIsNotLenient fails with NPE

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#31104]
REPRODUCE WITH: ./gradlew :modules:rank-eval:test \
  -Dtests.seed=2F3026AD21935B22 \
  -Dtests.class=org.elasticsearch.index.rankeval.RatedRequestsTests \
  -Dtests.method="testXContentParsingIsNotLenient" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-SY \
  -Dtests.timezone=Antarctica/McMurdo

A link to Jenkins failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux/2479/console

Reproduces for me on my local Mac machine with the following error stack:

```
ERROR   0.23s | RatedRequestsTests.testXContentParsingIsNotLenient <<< FAILURES!
   > Throwable #1: java.lang.NullPointerException
   >    at __randomizedtesting.SeedInfo.seed([2F3026AD21935B22:6B790599FD67DC25]:0)
   >    at org.elasticsearch.index.rankeval.RatedRequestsTests.testXContentParsingIsNotLenient(RatedRequestsTests.java:143)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
  2> NOTE: leaving temporary files on disk at: /Users/mayyasharipova/Elastic/elasticsearch/modules/rank-eval/build/testrun/test/J0/temp/org.elasticsearch.index.rankeval.RatedRequestsTests_2F3026AD21935B22-001
  2> NOTE: test params are: codec=Asserting(Lucene70), sim=RandomSimilarity(queryNorm=true): {}, locale=ar-SY, timezone=Antarctica/McMurdo
  2> NOTE: Mac OS X 10.13.4 x86_64/Oracle Corporation 10-ea (64-bit)/cpus=8,threads=1,free=464731344,total=536870912
  2> NOTE: All tests run in this JVM: [RatedRequestsTests]
Completed [1/1] in 1.71s, 1 test, 1 error <<< FAILURES!
```

**Comment by cbuescher** [comment]
This is caused by a slight change in the expected exception structure under some circumstances. It will not always fail, but often enough to be annoying so I muted the test for now.
