### ISSUE TITLE
[CI] IndicesLifecycleListenerIT#testIndexStateShardChanged failure on 6.2

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#31188]
Looking at the failure, the issue isn't actually that the test fails, but that files still exist on disk after removing the shard directory:

```
 > Throwable #1: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=8685, name=elasticsearch[node_t0][clusterApplierService#updateTask][T#1], state=RUNNABLE, group=TGRP-IndicesLifecycleListenerIT]
   > 	at __randomizedtesting.SeedInfo.seed([DA76AA10955DDB25:CA365D30E63F51C]:0)
   > Caused by: java.lang.AssertionError
   > 	at __randomizedtesting.SeedInfo.seed([DA76AA10955DDB25]:0)
   > 	at org.elasticsearch.env.NodeEnvironment.deleteShardDirectoryUnderLock(NodeEnvironment.java:460)
   > 	at org.elasticsearch.env.NodeEnvironment.deleteShardDirectorySafe(NodeEnvironment.java:400)
   > 	at org.elasticsearch.indices.IndicesService.deleteShardStore(IndicesService.java:719)
   > 	at org.elasticsearch.indices.store.IndicesStore$ShardActiveResponseHandler.lambda$allNodesResponded$2(IndicesStore.java:289)
   > 	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$runOnApplierThread$0(ClusterApplierService.java:307)
   > 	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.apply(ClusterApplierService.java:156)
   > 	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:400)
   > 	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:161)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573)
   > 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
   > 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   > 	at java.lang.Thread.run(Thread.java:748)
```

The failed assertion is:

```
...
        logger.trace("deleted shard {} directory, paths: [{}]", shardId, paths);
        assert FileSystemUtils.exists(paths) == false;
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+release-tests/413/console

**Comment by jasontedor** [comment]
I am relabeling this since it's about index shard state changes. I also think that it might be related to a test issue that is already open.

**Comment by DaveCTurner** [comment]
This looks like the race condition we're working on in #29140, so I think this is ok to close:

```
  1> Caused by: java.io.IOException: failed to read [id:1, legacy:false, file:/var/lib/jenkins/workspace/elastic+elasticsearch+6.2+release-tests/server/build/testrun/integTest/J2/temp/org.elasticsearch.indices.IndicesLifecycleListenerIT_DA76AA10955DDB25-001/tempDir-002/d1/nodes/0/indices/en3MD-tbQJCeENhHI97v6g/2/_state/state-1.st]
  1> 	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:327) ~[main/:?]
  1> 	at org.elasticsearch.index.shard.ShardPath.loadShardPath(ShardPath.java:122) ~[main/:?]
  1> 	at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.listStoreMetaData(TransportNodesListShardStoreMetaData.java:142) ~[main/:?]
  1> 	at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.nodeOperation(TransportNodesListShardStoreMetaData.java:109) ~[main/:?]
  1> 	at org.elasticsearch.indices.store.TransportNodesListShardStoreMetaData.nodeOperation(TransportNodesListShardStoreMetaData.java:61) ~[main/:?]
  1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:140) ~[main/:?]
  1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:262) ~[main/:?]
  1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:258) ~[main/:?]
  1> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[main/:?]
  1> 	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:656) ~[main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) ~[main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[main/:?]
  1> 	... 3 more
  1> Caused by: java.nio.file.NoSuchFileException: /var/lib/jenkins/workspace/elastic+elasticsearch+6.2+release-tests/server/build/testrun/integTest/J2/temp/org.elasticsearch.indices.IndicesLifecycleListenerIT_DA76AA10955DDB25-001/tempDir-002/d1/nodes/0/indices/en3MD-tbQJCeENhHI97v6g/2/_state/state-1.st
  1> 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:?]
  1> 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
  1> 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
```

**Comment by jasontedor** [comment]
Thanks @DaveCTurner, that's the one that I was thinking of.
