### ISSUE TITLE
[TEST] WatchBackwardsCompatibilityIT.testWatcherRestart failing

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#31196]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1846/console

Reproduction steps:

```
./gradlew :x-pack:qa:rolling-upgrade:with-system-key:v5.6.10-SNAPSHOT#twoThirdsUpgradedTestRunner -Dtests.seed=7C807A34A424F2C8 -Dtests.class=org.elasticsearch.upgrades.WatchBackwardsCompatibilityIT -Dtests.method="testWatcherRestart" -Dtests.security.manager=true -Dtests.locale=id-ID -Dtests.timezone=America/Thule
```

Relevant output:

```
Throwable #1: org.junit.ComparisonFailure: modern node [Sb1oWY7pQ9OwWiivhUrsGg] is not started expected:<st[opp]ed> but was:<st[art]ed>
   > 	at __randomizedtesting.SeedInfo.seed([7C807A34A424F2C8:E9D874BBEF382B91]:0)
   > 	at org.elasticsearch.upgrades.WatchBackwardsCompatibilityIT.lambda$ensureWatcherStartedOnModernNodes$17(WatchBackwardsCompatibilityIT.java:336)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:767)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:741)
   > 	at org.elasticsearch.upgrades.WatchBackwardsCompatibilityIT.lambda$ensureWatcherStartedOnModernNodes$18(WatchBackwardsCompatibilityIT.java:327)
   > 	at org.elasticsearch.upgrades.WatchBackwardsCompatibilityIT.executeAgainstMasterNode(WatchBackwardsCompatibilityIT.java:273)
   > 	at org.elasticsearch.upgrades.WatchBackwardsCompatibilityIT.ensureWatcherStartedOnModernNodes(WatchBackwardsCompatibilityIT.java:327)
   > 	at org.elasticsearch.upgrades.WatchBackwardsCompatibilityIT.testWatcherRestart(WatchBackwardsCompatibilityIT.java:188)
   > 	at java.lang.Thread.run(Thread.java:748)
   > 	Suppressed: org.junit.ComparisonFailure: modern node [Sb1oWY7pQ9OwWiivhUrsGg] is not started expected:<st[opp]ed> but was:<st[art]ed>
   > 		at org.elasticsearch.upgrades.WatchBackwardsCompatibilityIT.lambda$ensureWatcherStartedOnModernNodes$17(WatchBackwardsCompatibilityIT.java:336)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:755)
   > 		... 42 more
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+6.x+intake/x-pack/qa/rolling-upgrade/with-system-key/build/testrun/v5.6.10-SNAPSHOT#twoThirdsUpgradedTestRunner/J0/temp/org.elasticsearch.upgrades.WatchBackwardsCompatibilityIT_7C807A34A424F2C8-001
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=27, maxMBSortInHeap=5.594564139501403, sim=RandomSimilarity(queryNorm=true): {}, locale=id-ID, timezone=America/Thule
  2> NOTE: Linux 3.16.0-4-amd64 amd64/Oracle Corporation 1.8.0_172 (64-bit)/cpus=16,threads=1,free=396907864,total=514850816
  2> NOTE: All tests run in this JVM: [IndexAuditUpgradeIT, WatchBackwardsCompatibilityIT]
Completed [2/5] in 13.09s, 3 tests, 1 failure <<< FAILURES!
```

There's not thing stored in the temporary files:

```
jenkins@worker-02a46c5b7f9fd3b1f:~/workspace/elastic+elasticsearch+6.x+intake/x-pack/qa/rolling-upgrade/with-system-key/build/testrun/v5.6.10-SNAPSHOT#twoThirdsUpgradedTestRunner/J0/temp/org.elasticsearch.upgrades.WatchBackwardsCompatibilityIT_7C807A34A424F2C8-001$ find .
.
./extra0
./tempDir-001
./tempDir-001/extra0
```

**Comment by dliappis** [comment]
It appears that https://github.com/elastic/elasticsearch/commit/7be13e54c2043cdb29f928ddf82224cddda5a310 didn't fix those.

**Comment by dliappis** [comment]
Interestingly enough the next job succeeded, however, the commit 5e1cef992b953b2ce078a1628b98f0277cc8d1b3 used in this failed job: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1846/console already included the fix https://github.com/elastic/elasticsearch/commit/7be13e54c2043cdb29f928ddf82224cddda5a310.

**Comment by nik9000** [comment]
I pushed https://github.com/elastic/elasticsearch/commit/c5d38adc14bce1f81c8f3ab65f400c6eadbba412 which should fix this.
