### ISSUE TITLE
Gradle the master branch met AbstractMethodError

### ISSUE THREAD

**Issue by godlockin** [elastic/elasticsearch#31236]
ES master branch
gradle 4.8
jdk 10
windows 7

when i try to build ES by gradle, i always met the java.lang.AbstractMethodError, and it may caused by the sub project client:test

is there some Jar conflicts in master branch?

org.gradle.api.GradleScriptException: A problem occurred evaluating project ':client:test'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:92)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:204)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:209)
        at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:61)
...

Caused by: java.lang.AbstractMethodError
        at org.gradle.api.plugins.quality.internal.AbstractCodeQualityPlugin.createConfigurations(AbstractCodeQualityPlugin.java:106)
        at ru.vyarus.gradle.plugin.animalsniffer.AnimalSnifferPlugin.super$2$createConfigurations(AnimalSnifferPlugin.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by godlockin** [comment]
run the [gradle clean --stacktrace] in ES root dir and met the error

**Comment by jasontedor** [comment]
A few things here. First, we do not support Gradle 4.8 at this time, please use the Gradle wrapper provided in the project which is currently set to Gradle 4.7. See #31230 to track when we upgrade to Gradle 4.8. Additionally, the specific issue referenced here is already addressed by #31178. That said, even if you pull latest, Gradle 4.8 will still not function with the build. Again, please use the provided wrapper so that you always use a supported version of Gradle.

**Comment by godlockin** [comment]
o, thx jasontedor, the Gradle 4.7 works

**Comment by hongbeiti** [comment]
修改buildSrc/build.gradle里 ru.vyarus:gradle-animalsniffer-plugin:1.4.5 , 依赖变成1.4.5就能正常build了，v6.0.1版本已测试

**Comment by SeekerGalahad** [comment]
@hongbeiti 
My version 5.6.0.
it works, thx
