### ISSUE TITLE
CI: ScriptedMetricAggregatorTests testSelfReferencingAggStateAfterMap fails reproducibly

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#31307]
Found failure in PR build, but was able to reproduce it on master https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/11646/console

```
  2> REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=FB4E4946C6EABFE1 -Dtests.class=org.elasticsearch.search.aggregations.metrics.scripted.ScriptedMetricAggregatorTests -Dtests.method="testSelfReferencingAggStateAfterMap" -Dtests.security.manager=true -Dtests.locale=und -Dtests.timezone=Iceland
FAILURE 0.01s | ScriptedMetricAggregatorTests.testSelfReferencingAggStateAfterMap <<< FAILURES!
   > Throwable #1: junit.framework.AssertionFailedError: Expected exception IllegalArgumentException but no exception was thrown
   >    at __randomizedtesting.SeedInfo.seed([FB4E4946C6EABFE1:5C2FC010C227E5E2]:0)
   >    at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2686)
   >    at org.elasticsearch.search.aggregations.metrics.scripted.ScriptedMetricAggregatorTests.testSelfReferencingAggStateAfterMap(ScriptedMetricAggregatorTests.java:315)
```

**Comment by cbuescher** [comment]
I think I found the problem, will open a PR.
