### ISSUE TITLE
ResourceWatcherService Exception even on changing the permissions

### ISSUE THREAD

**Issue by emanzaman** [elastic/elasticsearch#31321]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.8

**Plugins installed**: None

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system):   2.6.32-220.17.1.el6.x86_64 

**Description of the problem including expected versus actual behavior**:
ResourceWatcherService throws FilePermission Exception even on changing the permissions for the scripts directoy to "drwxrwxr-x"
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
[2018-06-14T07:13:31,627][WARN ][o.e.t.ThreadPool         ] failed to run scheduled task [org.elasticsearch.watcher.ResourceWatcherService$ResourceMonitor@3f813572] on thread pool [same]
java.security.AccessControlException: access denied ("java.io.FilePermission" "/apps/IRDuatrun/rsu/ldn/uat/elasticsearch/bin/scripts" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_66]
        at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_66]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_66]
        at java.lang.SecurityManager.checkRead(SecurityManager.java:888) ~[?:1.8.0_66]
        at sun.nio.fs.UnixPath.checkRead(UnixPath.java:795) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.checkAccess(UnixFileSystemProvider.java:290) ~[?:?]
        at java.nio.file.Files.exists(Files.java:2385) ~[?:1.8.0_66]
        at org.elasticsearch.watcher.FileWatcher$FileObserver.checkAndNotify(FileWatcher.java:93) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.watcher.FileWatcher.doCheckAndNotify(FileWatcher.java:70) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.watcher.AbstractResourceWatcher.checkAndNotify(AbstractResourceWatcher.java:44) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.watcher.ResourceWatcherService$ResourceMonitor.run(ResourceWatcherService.java:197) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.threadpool.ThreadPool$ReschedulingRunnable.doRun(ThreadPool.java:811) [elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.threadpool.ThreadPool$LoggingRunnable.run(ThreadPool.java:436) [elasticsearch-5.6.8.jar:5.6.8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_66]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

Config Directory: /apps/IRDuatrun/rsu/ldn/uat/elasticsearch/etc/config

**Comment by tvernum** [comment]
@emanzaman Please fill in the rest of the details in the template.
- What is your elasticsearch version?
- What plugins do you have?

And then, please tell us about the file that is causing this issue?
- Your exception message has a blank - did you redact the filename, or is that really the error message?
- Where is that file located?
- What is the config directory for your elasticsearch node?

I suspect the problem is that you're trying to read a file outside of the ES config directory, and the elasticsearch security manager prevents that.

**Comment by emanzaman** [comment]
Sorry for the incomplete information provided. Updated the issue.

**Comment by tvernum** [comment]
This is better suited to the forums.
- https://discuss.elastic.co/t/resourcewatcherservice-exception-even-on-changing-the-permissions/135868
