### ISSUE TITLE
current license is non-compliant for [jdbc]  in 6.3

### ISSUE THREAD

**Issue by liguodongIOT** [elastic/elasticsearch#31418]
when i use jdbc in  es 6.3, i have a problem that  current license is non-compliant for [jdbc] .

```
java.sql.SQLInvalidAuthorizationSpecException: current license is non-compliant for [jdbc]
	at org.elasticsearch.xpack.sql.client.shared.JreHttpUrlConnection$SqlExceptionType.asException(JreHttpUrlConnection.java:306)
	at org.elasticsearch.xpack.sql.client.shared.JreHttpUrlConnection.parserError(JreHttpUrlConnection.java:183)
	at org.elasticsearch.xpack.sql.client.shared.JreHttpUrlConnection.request(JreHttpUrlConnection.java:158)
	at org.elasticsearch.xpack.sql.client.HttpClient.lambda$post$0(HttpClient.java:101)
	at org.elasticsearch.xpack.sql.client.shared.JreHttpUrlConnection.http(JreHttpUrlConnection.java:62)
	at org.elasticsearch.xpack.sql.client.HttpClient.lambda$post$1(HttpClient.java:100)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.xpack.sql.client.HttpClient.post(HttpClient.java:99)
	at org.elasticsearch.xpack.sql.client.HttpClient.query(HttpClient.java:77)
	at org.elasticsearch.xpack.sql.jdbc.net.client.JdbcHttpClient.query(JdbcHttpClient.java:51)
	at org.elasticsearch.xpack.sql.jdbc.jdbc.JdbcStatement.initResultSet(JdbcStatement.java:162)
	at org.elasticsearch.xpack.sql.jdbc.jdbc.JdbcStatement.execute(JdbcStatement.java:153)
	at org.elasticsearch.xpack.sql.jdbc.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:42)
```

**Comment by tvernum** [comment]
Elastic uses GitHub issues for tracking clearly identified bugs and feature requests.  
Questions such as this one belong on our [discuss forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support. Those forums are designed to support the kinds of conversations that are necessary for this sort of troubleshooting and problem diagnosis.

[JDBC requires a Platinum (or trial) license](https://www.elastic.co/subscriptions). If you have any futher questions, please raise make use of the forums.
