### ISSUE TITLE
CI: YAML test missing warning about delimited_payload_filter  in 6.x

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#31422]
Latest failure https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1931/console

	08:35:19   1> [2018-06-19T04:35:15,429][INFO ][o.e.a.c.CommonAnalysisClientYamlTestSuiteIT] [test {yaml=analysis-common/40_token_filters/delimited_payload_filter}]: after test
	08:35:19   2> REPRODUCE WITH: ./gradlew :modules:analysis-common:integTestRunner -Dtests.seed=E933B1D4E0ED6F76 -Dtests.class=org.elasticsearch.analysis.common.CommonAnalysisClientYamlTestSuiteIT -Dtests.method="test {yaml=analysis-common/40_token_filters/delimited_payload_filter}" -Dtests.security.manager=true -Dtests.locale=sr-Latn-ME -Dtests.timezone=America/Caracas
	08:35:19 FAILURE 0.14s | CommonAnalysisClientYamlTestSuiteIT.test {yaml=analysis-common/40_token_filters/delimited_payload_filter} <<< FAILURES!
	08:35:19    > Throwable #1: java.lang.AssertionError: Failure at [analysis-common/40_token_filters:1035]: did not get expected warning header [
	08:35:19    > 	Deprecated [delimited_payload_filter] used, replaced by [delimited_payload]
	08:35:19    > ]
	08:35:19    > 	at __randomizedtesting.SeedInfo.seed([E933B1D4E0ED6F76:61678E0E4E11028E]:0)
	08:35:19    > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:381)
	08:35:19    > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:358)
	08:35:19    > 	at java.lang.Thread.run(Thread.java:748)
	08:35:19    > Caused by: java.lang.AssertionError: did not get expected warning header [
	08:35:19    > 	Deprecated [delimited_payload_filter] used, replaced by [delimited_payload]
	08:35:19    > ]
	08:35:19    > 	at org.elasticsearch.test.rest.yaml.section.DoSection.checkWarningHeaders(DoSection.java:321)
	08:35:19    > 	at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:256)
	08:35:19    > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:374)
	08:35:19    > 	... 37 more

**Comment by cbuescher** [comment]
This reproduces for me locally on 6.x, not running it into it on master (I think the failing test is only on 6.x).
I will disable the test for now.

**Comment by cbuescher** [comment]
I have a hunch that "Use system context for cluster state update tasks (#31241) (commit: 78869eb)" changed something about the deprecation headers but haven't found the exact problem yet.

**Comment by cbuescher** [comment]
Found the problematic commit, its 78869eb71e700dbde9238d62e78ccc6a78bf9470 on the 6.x branch (which is the backport of #31241). When reverting it the tests pass. I think its only not failing on master because the particular test for deprecation warning headers is missing there (because the specific filter in question was removed on master). However I think this might effect deprecation warning headers in general. Digging...

**Comment by cbuescher** [comment]
@markharwood turns out my analysis was right but @ywelsch already has a PR open that seems to adress this in https://github.com/elastic/elasticsearch/pull/31241.
