### ISSUE TITLE
RestClientMultipleHostsIntegTests testNodeSelector fails on windows

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#31457]
There's a few of LL client failures, all of them on 6.x and windows:
```
java.lang.AssertionError: expected:<Connection refused> but was:<null>
	at __randomizedtesting.SeedInfo.seed([429EEC8C470749C5:26A699538C5AFAE7]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.elasticsearch.client.RestClientMultipleHostsIntegTests.testNodeSelector(RestClientMultipleHostsIntegTests.java:217)
	....
```
that @nik9000 's commit https://github.com/elastic/elasticsearch/commit/045f76d67f37f315fc42a3960ce88500e105f0d6 should have fixed this, but does it really? The message is null and not different. But the fix does appear to have worked on master yet not 6.x .

6.x failures:
https://groups.google.com/a/elastic.co/forum/#!searchin/build-elasticsearch/testNodeSelector|sort:date/build-elasticsearch/pIw1GjQIYAo/yf1OwCTgBAAJ
https://groups.google.com/a/elastic.co/forum/#!searchin/build-elasticsearch/testNodeSelector|sort:date/build-elasticsearch/BplpN0Ln0O4/jRVETj-TBQAJ
https://groups.google.com/a/elastic.co/forum/#!searchin/build-elasticsearch/testNodeSelector|sort:date/build-elasticsearch/45F3X_52Hd8/IPUoGGsdBQAJ

All of them tripping the same assertion about the connection error message.

**Comment by nik9000** [comment]
Oh man! I thought I had fixed it..... Grumble Windows, grumble.
