### ISSUE TITLE
IngestAttachmentClientYamlTestSuiteIT fails on jdk 11

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#31456]
Reproducible with:
```
./gradlew :plugins:ingest-attachment:integTestRunner \
  -Dtests.seed=60D84CAF3939D163 \
  -Dtests.class=org.elasticsearch.ingest.attachment.IngestAttachmentClientYamlTestSuiteIT \
  -Dtests.security.manager=true -Dtests.locale=en-IO -Dtests.timezone=Europe/Minsk
```
on the `feature/31230_gradle48_jdk11` feature branch. 
(Make sure to re-enable the `integTest` task in Gradle, since there's a single test, couldn't use `@AwaitsFix`)
 
From the failure log:
```
   >                 \ Your document contained more than 30 characters, and so your requested\
   >                 \ limit has been reached. To receive the full text of the document,\
   >                 \ increase your limit. (Text up to the limit is however available).\n\
```

**Comment by atorok** [comment]
Failure in CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+31230_gradle48_jdk11+matrix-java-feature-branch/2/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java10,nodes=virtual&&linux/

**Comment by dadoonet** [comment]
@tballison Does this ring a bell?

```
1> Caused by: java.lang.IllegalStateException: Can't overwrite cause with org.apache.tika.sax.WriteOutContentHandler$WriteLimitReachedException: Your document contained more than 30 characters, and so your requested limit has been reached. To receive the full text of the document, increase your limit. (Text up to the limit is however available).
  1> 	at java.base/java.lang.Throwable.initCause(Throwable.java:462)
  1> 	at org.apache.tika.sax.TaggedSAXException.<init>(TaggedSAXException.java:41)
  1> 	at org.apache.tika.sax.TaggedContentHandler.handleException(TaggedContentHandler.java:113)
  1> 	at org.apache.tika.sax.ContentHandlerDecorator.characters(ContentHandlerDecorator.java:148)
  1> 	at org.apache.tika.sax.ContentHandlerDecorator.characters(ContentHandlerDecorator.java:146)
  1> 	at org.apache.tika.sax.SafeContentHandler.access$001(SafeContentHandler.java:46)
  1> 	at org.apache.tika.sax.SafeContentHandler$1.write(SafeContentHandler.java:82)
  1> 	at org.apache.tika.sax.SafeContentHandler.filter(SafeContentHandler.java:140)
  1> 	at org.apache.tika.sax.SafeContentHandler.characters(SafeContentHandler.java:287)
  1> 	at org.apache.tika.sax.XHTMLContentHandler.characters(XHTMLContentHandler.java:279)
  1> 	at org.apache.tika.parser.txt.TXTParser.parse(TXTParser.java:104)
  1> 	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
  1> 	... 16 more
  1> Caused by: org.apache.tika.sax.TaggedSAXException: Your document contained more than 30 characters, and so your requested limit has been reached. To receive the full text of the document, increase your limit. (Text up to the limit is however available).
  1> org.apache.tika.sax.WriteOutContentHandler$WriteLimitReachedException: Your document contained more than 30 characters, and so your requested limit has been reached. To receive the full text of the document, increase your limit. (Text up to the limit is however available).
  1> 	... 26 more
  1> Caused by: org.apache.tika.sax.WriteOutContentHandler$WriteLimitReachedException: Your document contained more than 30 characters, and so your requested limit has been reached. To receive the full text of the document, increase your limit. (Text up to the limit is however available).
  1> 	at org.apache.tika.sax.WriteOutContentHandler.characters(WriteOutContentHandler.java:141)
  1> 	at org.apache.tika.sax.ContentHandlerDecorator.characters(ContentHandlerDecorator.java:146)
  1> 	at org.apache.tika.sax.xpath.MatchingContentHandler.characters(MatchingContentHandler.java:85)
  1> 	at org.apache.tika.sax.ContentHandlerDecorator.characters(ContentHandlerDecorator.java:146)
  1> 	at org.apache.tika.sax.ContentHandlerDecorator.characters(ContentHandlerDecorator.java:146)
  1> 	at org.apache.tika.sax.SecureContentHandler.characters(SecureContentHandler.java:270)
  1> 	at org.apache.tika.sax.ContentHandlerDecorator.characters(ContentHandlerDecorator.java:146)
  1> 	... 24 more
```

**Comment by tballison** [comment]
Y.  This is the real culprit:

> 1> Caused by: java.lang.IllegalStateException: Can't overwrite cause with org.apache.tika.sax.WriteOutContentHandler$WriteLimitReachedException:

I think we're coming up on a release of Tika 1.19 which will solve this.  I want to fix this before that release:
 [TIKA-2674 -- update deps for Java 11](https://issues.apache.org/jira/browse/TIKA-2674)

**Comment by atorok** [comment]
Some addition test failures with the same reason:
  - https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+31230_gradle48_jdk11+matrix-java-feature-branch/3/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8,nodes=virtual&&linux/testReport/junit/org.elasticsearch.smoketest/DocsClientYamlTestSuiteIT/test__yaml_plugins_ingest_attachment_line_164_/
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+31230_gradle48_jdk11+matrix-java-feature-branch/3/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8,nodes=virtual&&linux/testReport/junit/org.elasticsearch.smoketest/DocsClientYamlTestSuiteIT/test__yaml_plugins_ingest_attachment_line_117_/

**Comment by tballison** [comment]
Tika 1.19 is out.  Give it a try.

**Comment by tballison** [comment]
w00t!  Thank you @jkakavas and team!
