### ISSUE TITLE
[v6.2.2]ES often happen Frequently  error of timeout question now and then

### ISSUE THREAD

**Issue by kervin521** [elastic/elasticsearch#31570]
2018-06-20 02:04:40,228 [TaskHandleThreadPool-thread-6]-[com.glocalme.css.analyse.elasticsearch.dao.VsimAssignLogDao]-WARN onFailure:{createTime=2018-06-18T21:27:40.536+0000, mvnoId=570e05e256a5951a9d725f0b, imei=250000000001222, imsi=452015000009619, sessionId=f0126f038a8b4115963c606f6c89b1e9, type=3, streamNo=0d2ea2daf65ec4b1dc9c5a427847aa80, userCode=WWS_T0001222_01@163.com} java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
	at org.apache.http.util.Asserts.check(Asserts.java:46) ~[httpcore-4.4.4.jar:4.4.4]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90) ~[httpasyncclient-4.1.2.jar:4.1.2]
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123) ~[httpasyncclient-4.1.2.jar:4.1.2]
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:347) ~[elasticsearch-rest-client-6.2.4.jar:6.2.4]
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:329) [elasticsearch-rest-client-6.2.4.jar:6.2.4]
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:272) [elasticsearch-rest-client-6.2.4.jar:6.2.4]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAsync(RestHighLevelClient.java:537) [elasticsearch-rest-high-level-client-6.2.4.jar:6.2.4]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAsyncAndParseEntity(RestHighLevelClient.java:515) [elasticsearch-rest-high-level-client-6.2.4.jar:6.2.4]
	at org.elasticsearch.client.RestHighLevelClient.indexAsync(RestHighLevelClient.java:344) [elasticsearch-rest-high-level-client-6.2.4.jar:6.2.4]
	at com.glocalme.css.analyse.elasticsearch.dao.VsimAssignLogDao.indexAsync(VsimAssignLogDao.java:233) [css-analyse-service-1.0.0.jar:?]
	at com.glocalme.css.analyse.elasticsearch.dao.VsimAssignLogDao.index(VsimAssignLogDao.java:213) [css-analyse-service-1.0.0.jar:?]
	at com.glocalme.css.analyse.task.OnlineUserMonitorTask.listen(OnlineUserMonitorTask.java:145) [css-analyse-service-1.0.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:95) [guava-19.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:154) [guava-19.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:80) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456) [guava-19.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:76) [guava-19.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:119) [guava-19.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:215) [guava-19.0.jar:?]
	at com.glocalme.css.analyse.schedule.executors.ReclaimEventExecutor.execute(ReclaimEventExecutor.java:47) [css-analyse-service-1.0.0.jar:?]
	at com.glocalme.css.common.kafka.AbstractMessageExecutor$1.run(AbstractMessageExecutor.java:88) [css-common-1.0.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

2018-06-19 00:09:44,036 [TaskHandleThreadPool-thread-8]-[com.glocalme.css.analyse.elasticsearch.dao.DispatchLogFullDao]-ERROR DispatchLog insert failed! java.io.IOException: listener timeout after waiting for [300000] ms
at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:665) ~[elasticsearch-rest-client-6.2.4.jar:6.2.4]
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:223) ~[elasticsearch-rest-client-6.2.4.jar:6.2.4]
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:195) ~[elasticsearch-rest-client-6.2.4.jar:6.2.4]
at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:488) ~[elasticsearch-rest-high-level-client-6.2.4.jar:6.2.4]
at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:474) ~[elasticsearch-rest-high-level-client-6.2.4.jar:6.2.4]
at org.elasticsearch.client.RestHighLevelClient.index(RestHighLevelClient.java:335) ~[elasticsearch-rest-high-level-client-6.2.4.jar:6.2.4]
at com.glocalme.css.analyse.elasticsearch.dao.DispatchLogFullDao.insert(DispatchLogFullDao.java:56) [css-analyse-service-1.0.0.jar:?]
at com.glocalme.css.analyse.schedule.executors.DispatchLogExecutor.execute(DispatchLogExecutor.java:65) [css-analyse-service-1.0.0.jar:?]
at com.glocalme.css.common.kafka.AbstractMessageExecutor$1.run(AbstractMessageExecutor.java:88) [css-common-1.0.0.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by markharwood** [comment]
I'm not sure this classifies as a bug. If your system is under excessive load you may expect to see timeouts. Your comment doesn't say if this was the case. Also, it looks like you might be indexing individual documents from Kafka - it is more efficient to use the `bulk` api to add documents.

If you feel there is a genuine bug please provide more details and I can reopen this issue

**Comment by kervin521** [comment]
@markharwood details above

**Comment by kervin521** [comment]
![image](https://user-images.githubusercontent.com/9798724/41902044-0c088cdc-7965-11e8-8e61-de6a07a1df04.png)

**Comment by kervin521** [comment]
![image](https://user-images.githubusercontent.com/9798724/41902079-24f156ca-7965-11e8-9862-d7f8ccead297.png)

**Comment by markharwood** [comment]
Thanks for the added details however this is intended as a place to track bugs or new features.

If you want help in diagnosing performance issues in your system I suggest posting in the [discuss forums](https://discuss.elastic.co/c/elasticsearch) (note - please post text there rather than screenshots).
