### ISSUE TITLE
Test: ClientYamlSuiteRestApiParser cannot parse test specs without parts that require a body

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#31649]
The api json file parser seems to not correctly parse spec files that do not have any path parameters but have the `body` field set and required.

This test (added in `ClientYamlSuiteRestApiParserTests`) fails

```java
    public void testRequiredBodyWithoutUrlParts() throws Exception {
        String spec = "{\n" +
            "  \"count\": {\n" +
            "    \"documentation\": \"whatever\",\n" +
            "    \"methods\": [ \"GET\", \"POST\" ],\n" +
            "    \"url\": {\n" +
            "      \"path\": \"/whatever\",\n" +
            "      \"paths\": [ \"/whatever\" ]\n" +
            "    },\n" +
            "    \"body\": {\n" +
            "      \"description\" : \"whatever\",\n" +
            "      \"required\" : true\n" +
            "    }\n" +
            "  }\n" +
            "}";
        parser = createParser(YamlXContent.yamlXContent, spec);
        ClientYamlSuiteRestApi restApi = new ClientYamlSuiteRestApiParser().parse("count.json", parser);

        assertThat(restApi, notNullValue());
    }
```

fails with

```

java.lang.AssertionError: Expected [END_OBJECT] but was [null]

	at __randomizedtesting.SeedInfo.seed([ED4984B513DDA0D0:BDED9C135058595]:0)
	at org.elasticsearch.test.rest.yaml.restspec.ClientYamlSuiteRestApiParser.parse(ClientYamlSuiteRestApiParser.java:155)
	at org.elasticsearch.test.rest.yaml.restspec.ClientYamlSuiteRestApiParserTests.testRequiredBodyWithoutUrlParts(ClientYamlSuiteRestApiParserTests.java:110)
```

**Comment by spinscale** [comment]
small update: adding an emtpy `"parts" : {}` makes this test pass.

```
String spec = "{\n" +
            "  \"count\": {\n" +
            "    \"documentation\": \"whatever\",\n" +
            "    \"methods\": [ \"GET\", \"POST\" ],\n" +
            "    \"url\": {\n" +
            "      \"path\": \"/whatever\",\n" +
            "      \"paths\": [ \"/whatever\" ],\n" +
            "      \"parts\": {} \n" +
            "    },\n" +
            "    \"body\": {\n" +
            "      \"description\" : \"whatever\",\n" +
            "      \"required\" : true\n" +
            "    }\n" +
            "  }\n" +
            "}";
```

I'm good with closing this then as well.

**Comment by spinscale** [comment]
Also it seems, that if you include a `params` part, parsing works, as done in https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/src/test/resources/rest-api-spec/api/xpack.ml.validate.json and https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/src/test/resources/rest-api-spec/api/xpack.ml.validate_detector.json - which both also contain a `body` part
