### ISSUE TITLE
[CI] NamingConventionsTaskIT fails assertion about test naming

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#31665]
`NamingConventionsTaskIT` has been failing on two tests: `testNameCheckFailsAsItShould` and `testNameCheckFailsAsItShouldWithMain`.

@atorok is working on it, just opening this issue to keep track of the awaitsFix.

Most recent failure:  https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2220/console

```
java.lang.AssertionError: expected:  'Classes ending with [Tests] or [IT] or extending [UnitTestCase] must be in src/test/java:' but it was not found in the output
	at __randomizedtesting.SeedInfo.seed([BF170365C0072BBC:9223A5975F0FE26A]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.elasticsearch.gradle.precommit.NamingConventionsTaskIT.testNameCheckFailsAsItShouldWithMain(NamingConventionsTaskIT.java:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1713)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:907)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:916)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:802)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:852)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:863)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$2.evaluate(ThreadLeakControl.java:404)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSuite(RandomizedRunner.java:678)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.access$200(RandomizedRunner.java:140)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:598)
```

```
java.lang.AssertionError: expected:  'Found inner classes that are tests, which are excluded from the test runner:' but it was not found in the output
	at __randomizedtesting.SeedInfo.seed([BF170365C0072BBC:9135BE74FA9DCEBA]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.elasticsearch.gradle.precommit.NamingConventionsTaskIT.testNameCheckFailsAsItShould(NamingConventionsTaskIT.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1713)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:907)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:916)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:802)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:852)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:863)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$2.evaluate(ThreadLeakControl.java:404)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSuite(RandomizedRunner.java:678)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.access$200(RandomizedRunner.java:140)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:598)
```

**Comment by atorok** [comment]
I  believe the test was in fact picking up a problem.
After it was ignored there was this subsequent failure:
```
00:14:56 > Task :qa:ccs-unavailable-clusters:namingConventions FAILED
00:14:56 
00:14:56 Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/test/NamingConventionsCheck has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
00:14:56 > Task :qa:ccs-unavailable-clusters:integTestCluster#stop
00:14:56 	at java.lang.ClassLoader.defineClass1(Native Method)
00:14:56 
00:14:56 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
00:14:56 Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
00:14:56 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
00:14:56 See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings
00:14:56 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
00:14:56 223 actionable tasks: 222 executed, 1 up-to-date
00:14:56 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
00:14:56 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
00:14:56 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
00:14:56 	at java.security.AccessController.doPrivileged(Native Method)
00:14:56 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
00:14:56 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
00:14:56 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
00:14:56 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
00:14:56 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

**Comment by atorok** [comment]
I can reproduce this locally with `export RUNTIME_JAVA_HOME=$JAVA8_HOME`. 
`JAVA_HOME` is jdk 10, so compile will also use 10. 
That means that we'll try to run the newer class version on the older JVM, which won't work. 
I know how to fix this, but I'm still struggling to understand why this broke with the change I did.
