### ISSUE TITLE
[CI] RollupIT#testTwoJobsStartStopDeleteOne fails

### ISSUE THREAD

**Issue by vladimirdolzhenko** [elastic/elasticsearch#31810]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/2536/console

is *not* reproducible locally

```
00:51:11 FAILURE 6.42s | RollupIT.testTwoJobsStartStopDeleteOne <<< FAILURES!
00:51:11    > Throwable #1: java.lang.AssertionError: Accounting breaker not reset to 0 on node: node_s0
00:51:11    > Expected: <0L>
00:51:11    >      but: was <11421L>
00:51:11    > 	at __randomizedtesting.SeedInfo.seed([698DCF0963902073:4F0D6EF289903D04]:0)
00:51:11    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
00:51:11    > 	at org.elasticsearch.test.InternalTestCluster.ensureEstimatedStats(InternalTestCluster.java:2020)
00:51:11    > 	at org.elasticsearch.test.TestCluster.assertAfterTest(TestCluster.java:93)
00:51:11    > 	at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2051)
00:51:11    > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:586)
00:51:11    > 	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2159)
00:51:11    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vladimirdolzhenko** [comment]
duplicate of https://github.com/elastic/elasticsearch/issues/30290
