### ISSUE TITLE
[CI] TribeIntegrationTests failures

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#31865]
Failed tests:
org.elasticsearch.tribe.TribeIntegrationTests.testGlobalReadWriteBlocks
org.elasticsearch.tribe.TribeIntegrationTests.testMergingCustomMetaData
org.elasticsearch.tribe.TribeIntegrationTests.testMergingRemovedCustomMetaData
org.elasticsearch.tribe.TribeIntegrationTests.testCloseAndOpenIndex
org.elasticsearch.tribe.TribeIntegrationTests.testClusterStateNodes
org.elasticsearch.tribe.TribeIntegrationTests.testMergingMultipleCustomMetaData
org.elasticsearch.tribe.TribeIntegrationTests.testOnConflictDrop
org.elasticsearch.tribe.TribeIntegrationTests.testOnConflictPrefer
org.elasticsearch.tribe.TribeIntegrationTests.testIndexWriteBlocks
org.elasticsearch.tribe.TribeIntegrationTests.testTribeOnOneCluster

Most of these test fail like this:

```
1> [2018-07-06T13:38:07,364][INFO ][o.e.t.TribeIntegrationTests] [testMergingMultipleCustomMetaData]: after test
ERROR   60.3s J0 | TribeIntegrationTests.testMergingMultipleCustomMetaData <<< FAILURES!
   > Throwable #1: java.lang.IllegalStateException: cluster failed to form with expected nodes [{node_sc0}{FSZqaa2vRuqzMrUqY9aTKQ}{L1ytK9qsRYaFlZbAxuGUHQ}{127.0.0.1}{127.0.0.1:35921}] and actual nodes nodes: 
   >    {node_sc0/4ThwrP__T_-3fktZAAAAAA}{XpaKPJyVQaSEYHp2H-uGTQ}{SSaMMhnfQC6DwUaRb0_b2A}{127.0.0.1}{127.0.0.1:9300}{tribe.name=4ThwrP__T_-3fktZAAAAAA}
   >    {cluster_1m0}{tbKXbERYRrqKbLt04iPgDw}{dy2sD_YFQkeENix-iTXBMA}{127.0.0.1}{127.0.0.1:39481}{tribe.name=4ThwrP__T_-3fktZAAAAAA}
   >    {cluster_1d3}{owMY00sGSJeLjaxrxihFHw}{piPD74UMTauGUJDDmASc_w}{127.0.0.1}{127.0.0.1:36585}{tribe.name=4ThwrP__T_-3fktZAAAAAA}
   >    {cluster_2m0}{vk2vX3ENQMW5sTiX6wr-jw}{9SmszrYkRjGFcn8PYDOZtw}{127.0.0.1}{127.0.0.1:40459}{tribe.name=uzN6XwAAQAC2bD7M_____w}
   >    {node_sc0/uzN6XwAAQAC2bD7M_____w}{brZmdxX3TkWSWDKeI4l24w}{78GXDVO9Sd6nlZR435MgwA}{127.0.0.1}{127.0.0.1:9301}{tribe.name=uzN6XwAAQAC2bD7M_____w}
   >    {node_sc0}{FSZqaa2vRuqzMrUqY9aTKQ}{L1ytK9qsRYaFlZbAxuGUHQ}{127.0.0.1}{127.0.0.1:35921}, local
   >    {cluster_2d2}{JASgBRbdRKCotGVNx0Qy0g}{XoW_c0gPSDaDRwO6BYVIYQ}{127.0.0.1}{127.0.0.1:44857}{tribe.name=uzN6XwAAQAC2bD7M_____w}
   >    {cluster_2d3}{N8IAbmHSRaKuwtaM4p2yAw}{KJtl3tzNThyUFtU_XMkWiA}{127.0.0.1}{127.0.0.1:43037}{tribe.name=uzN6XwAAQAC2bD7M_____w}
   >    {cluster_1d2}{hrR1ULsQRM2SXz602hx2VQ}{W9Ob4XUBS3qDuj4irT3H_w}{127.0.0.1}{127.0.0.1:42937}{tribe.name=4ThwrP__T_-3fktZAAAAAA}
   >    {cluster_2d4}{j6bM8pNSRJSDMoU2VFuTzA}{nt96cghkRd6-ierd-c40NQ}{127.0.0.1}{127.0.0.1:34721}{tribe.name=uzN6XwAAQAC2bD7M_____w}
   >    {cluster_1d1}{lWJLiLQzQ6mGyjW7x8K2EA}{rgxQvo3HRlyWR0-UCj84lw}{127.0.0.1}{127.0.0.1:42245}{tribe.name=4ThwrP__T_-3fktZAAAAAA}
   >    {cluster_2d1}{DxMI3GVsTeCEzv5946o3vg}{zv1caqymQqKPSPbuNj_CuQ}{127.0.0.1}{127.0.0.1:36507}{tribe.name=uzN6XwAAQAC2bD7M_____w}
   > 	at org.elasticsearch.test.InternalTestCluster.validateClusterFormed(InternalTestCluster.java:1073)
   > 	at org.elasticsearch.test.InternalTestCluster.validateClusterFormed(InternalTestCluster.java:1048)
   > 	at org.elasticsearch.test.InternalTestCluster.startNodes(InternalTestCluster.java:1680)
   > 	at org.elasticsearch.test.InternalTestCluster.startNode(InternalTestCluster.java:1646)
   > 	at org.elasticsearch.tribe.TribeIntegrationTests.startTribeNode(TribeIntegrationTests.java:251)
   > 	at org.elasticsearch.tribe.TribeIntegrationTests.startTribeNode(TribeIntegrationTests.java:247)
   > 	at org.elasticsearch.tribe.TribeIntegrationTests.testMergingMultipleCustomMetaData(TribeIntegrationTests.java:570)
   > 	at java.lang.Thread.run(Thread.java:748)Throwable #2: java.lang.AssertionError: ClusterHealthResponse has timed out - returned: [{"cluster_name":"SUITE-CHILD_VM=[0]-CLUSTER_SEED=[7037611908051590172]-HASH=[E05ED487F7FC8]-cluster","status":"green","timed_out":true,"number_of_nodes":12,"number_of_data_nodes":7,"active_primary_shards":0,"active_shards":0,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0}]
   > Expected: is <false>
   >      but: was <true>
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertNoTimeout(ElasticsearchAssertions.java:102)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureClusterSizeConsistency(ESIntegTestCase.java:1111)
   > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:570)
   > 	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2179)
   > 	at java.lang.Thread.run(Thread.java:748)
```

Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/2034/

**Comment by ywelsch** [comment]
Thanks @martijnvg. I've pushed d1fa9fa which fixes and reenables the test.
