### ISSUE TITLE
[CI] BWC CoreFullClusterRestartIT testRecovery failurew

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#31996]
Seems similar to #27817, but I opened a new since that has been closed a while ago.

```
FAILURE 0.09s | CoreFullClusterRestartIT.testRecovery <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: mismatch while checking for translog recovery
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+master+bwc-tests/x-pack/qa/full-cluster-restart/without-system-key/build/testrun/v6.0.0#upgradedClusterTestRunner/J0/temp/org.elasticsearch.xpack.restart.CoreFullClusterRestartIT_1DADF4E005D45916-001
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=1083, maxMBSortInHeap=7.249448543229284, sim=RandomSimilarity(queryNorm=false): {}, locale=th-TH-u-nu-thai-x-lvariant-TH, timezone=America/North_Dakota/Center
  2> NOTE: Linux 4.4.0-1060-aws amd64/Oracle Corporation 1.8.0_172 (64-bit)/cpus=16,threads=1,free=477159568,total=514850816
   > testrecovery 0 existing_store done 0
   > testrecovery 0 peer           done 0
   > testrecovery 1 existing_store done 0
   > testrecovery 1 peer           done 0
   > testrecovery 2 existing_store done 0
   > testrecovery 2 peer           done 0
  2> NOTE: All tests run in this JVM: [FullClusterRestartIT, CoreFullClusterRestartIT]
   > testrecovery 3 existing_store done 0
   > testrecovery 3 peer           done 0
   > testrecovery 4 existing_store done 0
   > testrecovery 4 peer           done 47
   >  expected:<false> but was:<true>
   > 	at __randomizedtesting.SeedInfo.seed([1DADF4E005D45916:DC5D8D4C288493B1]:0)
   > 	at org.elasticsearch.upgrades.FullClusterRestartIT.testRecovery(FullClusterRestartIT.java:764)
   > 	at java.lang.Thread.run(Thread.java:748)
```

The reproduce command does not reproduce.

Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+bwc-tests/1246/console

[1246.log](https://github.com/elastic/elasticsearch/files/2188451/1246.log)

**Comment by andyb-elastic** [comment]
Another on 6.x - apologies attaching the log isn't working for me right now

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=oraclelinux/1197/console
