### ISSUE TITLE
[CI] AutodetectMemoryLimitIT#testTooManyPartitions fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#32033]
Failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1754/console

Doesn't reproduce locally:
```
REPRODUCE WITH: gradlew :x-pack:qa:ml-native-multi-node-tests:integTestRunner \
  -Dtests.seed=9CADA5C6DD8AA7EB \
  -Dtests.class=org.elasticsearch.xpack.ml.integration.AutodetectMemoryLimitIT \
  -Dtests.method="testTooManyPartitions" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-DO \
  -Dtests.timezone=CNT
```

Error:
```
java.lang.AssertionError: 
Expected: <hard_limit>
     but: was <soft_limit>
	at __randomizedtesting.SeedInfo.seed([9CADA5C6DD8AA7EB:ABF1C3C801E93F48]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.ml.integration.AutodetectMemoryLimitIT.testTooManyPartitions(AutodetectMemoryLimitIT.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1713)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:907)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:943)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:957)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:916)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:802)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:852)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:863)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by droberts195** [comment]
I think this is a Windows-only problem, and this is why it didn't reproduce locally.  C++ standard library objects can have different sizes on each implementation of the standard library and this has led to the memory usage not being as high on Windows for this particular test.

**Comment by cbuescher** [comment]
Theres just another one on master (also on Windows): https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1755/console

I'm not sure we can mute tests based on OS versions, this seems to be failing quite consistently. Maybe wait for another failure before disabling it altogether for all platforms? Or is this test very important so it should keep running on other OSes?

**Comment by droberts195** [comment]
They're in the release tests.  I have started a _non-_snapshot build of the ML C++.  I think it must be that the non-snapshot build isn't up-to-date, hence this is failing only for release builds.

**Comment by droberts195** [comment]
Build 813 is already running - it will fail in the same way as before.  But build 814 should succeed.  Let's wait and see if 814 succeeds before muting the test.  (Any muting would be too late for 813 anyway.)

**Comment by cbuescher** [comment]
Another one:  https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/813/console

**Comment by cbuescher** [comment]
Ah, that was the one already running, sorry for the noise.

**Comment by droberts195** [comment]
Build 814 worked, so the problem was that the non-snapshot ML C++ build was old, and it's up-to-date now.

**Comment by cbuescher** [comment]
@droberts195 should we close then? We can always reopen if it turns out it still fails?
