### ISSUE TITLE
[CI] Flaky OldWatcherIndicesBackwardsCompatibilityTests on 5.6 (mostly Windows)

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#32031]
Seen this today, but there are several instances of this failing, mostly on Windows compatibility tests.
Failure today: https://internal-ci.elastic.co/job/elastic+x-pack-elasticsearch+5.6+multijob-windows-compatibility/2009/console

This doesn't reproduce locally so far:
```
REPRODUCE WITH: gradlew :x-pack-elasticsearch:plugin:test \
  -Dtests.seed=E6DE29391EA55FF7 \
  -Dtests.class=org.elasticsearch.xpack.watcher.OldWatcherIndicesBackwardsCompatibilityTests \
  -Dtests.method="testOldIndexes" \
  -Dtests.security.manager=true \
  -Dtests.locale=et-EE \
  -Dtests.timezone=Asia/Tokyo

REPRODUCE WITH: gradlew :x-pack-elasticsearch:plugin:test \
  -Dtests.seed=E6DE29391EA55FF7 \
  -Dtests.class=org.elasticsearch.xpack.watcher.OldWatcherIndicesBackwardsCompatibilityTests \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=UTC

REPRODUCE WITH: gradlew :x-pack-elasticsearch:plugin:test \
  -Dtests.seed=E6DE29391EA55FF7 \
  -Dtests.class=org.elasticsearch.xpack.watcher.OldWatcherIndicesBackwardsCompatibilityTests \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=UTC
```

There are several errors in the logs, but this is the earlierst exception I could find so far, which hints at something being wrong while loading state files:
```
org.elasticsearch.action.FailedNodeException: Failed node [Os5CTMIYQbONErCOqX7m8g]
23:50:52   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onFailure(TransportNodesAction.java:239) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$200(TransportNodesAction.java:153) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleException(TransportNodesAction.java:211) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1085) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1189) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1167) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.transport.DelegatingTransportChannel.sendResponse(DelegatingTransportChannel.java:70) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.transport.RequestHandlerRegistry$TransportChannelWrapper.sendResponse(RequestHandlerRegistry.java:123) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.onFailure(SecurityServerTransportInterceptor.java:249) ~[main/:?]
23:50:52   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:110) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.lambda$messageReceived$0(SecurityServerTransportInterceptor.java:307) ~[main/:?]
23:50:52   1> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:59) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$authorizeAsync$5(ServerTransportFilter.java:208) ~[main/:?]
23:50:52   1> 	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.maybeRun(AuthorizationUtils.java:127) ~[main/:?]
23:50:52   1> 	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.setRunAsRoles(AuthorizationUtils.java:121) ~[main/:?]
23:50:52   1> 	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.authorize(AuthorizationUtils.java:103) ~[main/:?]
23:50:52   1> 	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.authorizeAsync(ServerTransportFilter.java:210) ~[main/:?]
23:50:52   1> 	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$inbound$2(ServerTransportFilter.java:168) ~[main/:?]
23:50:52   1> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:59) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$2(AuthenticationService.java:212) ~[main/:?]
23:50:52   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$4(AuthenticationService.java:246) ~[main/:?]
23:50:52   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:257) [main/:?]
23:50:52   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:210) [main/:?]
23:50:52   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:159) [main/:?]
23:50:52   1> 	at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:122) [main/:?]
23:50:52   1> 	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.inbound(ServerTransportFilter.java:146) [main/:?]
23:50:52   1> 	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:314) [main/:?]
23:50:52   1> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) [elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:662) [elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:675) [elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
23:50:52   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
23:50:52   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
23:50:52   1> Caused by: org.elasticsearch.transport.RemoteTransportException: [node_t3][127.0.0.1:30317][internal:gateway/local/started_shards[n]]
23:50:52   1> Caused by: org.elasticsearch.ElasticsearchException: failed to load started shards
23:50:52   1> 	at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:171) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:61) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:140) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:262) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:258) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:258) ~[main/:?]
23:50:52   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	... 25 more
23:50:52   1> Caused by: org.elasticsearch.ElasticsearchException: java.io.IOException: failed to read [id:2, legacy:false, file:C:\Users\jenkins\workspace\elastic+x-pack-elasticsearch+5.6+multijob-windows-compatibility\elasticsearch-extra\x-pack-elasticsearch\plugin\build\testrun\test\J2\temp\org.elasticsearch.xpack.watcher.OldWatcherIndicesBackwardsCompatibilityTests_E6DE29391EA55FF7-001\tempDir-010\nodes\0\indices\6elC0yA_QyGKv5077xLqWQ\_state\state-2.st]
23:50:52   1> 	at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:196) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:335) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:127) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:61) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:140) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:262) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:258) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:258) ~[main/:?]
23:50:52   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	... 25 more
23:50:52   1> Caused by: java.io.IOException: failed to read [id:2, legacy:false, file:C:\Users\jenkins\workspace\elastic+x-pack-elasticsearch+5.6+multijob-windows-compatibility\elasticsearch-extra\x-pack-elasticsearch\plugin\build\testrun\test\J2\temp\org.elasticsearch.xpack.watcher.OldWatcherIndicesBackwardsCompatibilityTests_E6DE29391EA55FF7-001\tempDir-010\nodes\0\indices\6elC0yA_QyGKv5077xLqWQ\_state\state-2.st]
23:50:52   1> 	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:328) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:127) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:61) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:140) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:262) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:258) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:258) ~[main/:?]
23:50:52   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	... 25 more
23:50:52   1> Caused by: java.nio.file.NoSuchFileException: C:\Users\jenkins\workspace\elastic+x-pack-elasticsearch+5.6+multijob-windows-compatibility\elasticsearch-extra\x-pack-elasticsearch\plugin\build\testrun\test\J2\temp\org.elasticsearch.xpack.watcher.OldWatcherIndicesBackwardsCompatibilityTests_E6DE29391EA55FF7-001\tempDir-010\nodes\0\indices\6elC0yA_QyGKv5077xLqWQ\_state\state-2.st
23:50:52   1> 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79) ~[?:?]
23:50:52   1> 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:?]
23:50:52   1> 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[?:?]
23:50:52   1> 	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230) ~[?:?]
23:50:52   1> 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newByteChannel(FilterFileSystemProvider.java:212) ~[lucene-test-framework-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:40]
23:50:52   1> 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newByteChannel(FilterFileSystemProvider.java:212) ~[lucene-test-framework-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:40]
23:50:52   1> 	at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_162]
23:50:52   1> 	at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_162]
23:50:52   1> 	at org.apache.lucene.store.SimpleFSDirectory.openInput(SimpleFSDirectory.java:77) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]
23:50:52   1> 	at org.elasticsearch.gateway.MetaDataStateFormat.read(MetaDataStateFormat.java:188) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:323) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:127) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.gateway.TransportNodesListGatewayStartedShards.nodeOperation(TransportNodesListGatewayStartedShards.java:61) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:140) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:262) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:258) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:258) ~[main/:?]
23:50:52   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.6.11-SNAPSHOT.jar:5.6.11-SNAPSHOT]
23:50:52   1> 	... 25 more
```

**Comment by cbuescher** [comment]
Similar looking occurances in the last month:

July 5:
https://internal-ci.elastic.co/job/elastic+x-pack-elasticsearch+5.6+multijob-windows-compatibility/1965/console

June 30:
https://internal-ci.elastic.co/job/elastic+x-pack-elasticsearch+5.6+multijob-windows-compatibility/1933/console

**Comment by colings86** [comment]
Another instance of this failure: https://internal-ci.elastic.co/job/elastic+x-pack-elasticsearch+5.6+multijob-windows-compatibility/328/console

**Comment by astefan** [comment]
FWIW I tried to reproduce this failure on my Windows machine, but failed.

**Comment by dakrone** [comment]
These classes don't even exist any more in 6.x, so I'm going to close this.
