### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT fails for "search.inner_hits/10_basic" and "search/110_field_collapsing"

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#32055]
Failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2320/console

Errors:
```
java.lang.AssertionError: Failure at [search/110_field_collapsing:157]: hits.total didn't match expected value:
                    hits.total: expected [6] but was [5]

	at __randomizedtesting.SeedInfo.seed([3996C2C8187055DE:B1C2FD12B68C3826]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:395)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:372)
[...]
```
```
java.lang.AssertionError: Failure at [search/110_field_collapsing:255]: hits.total didn't match expected value:
                    hits.total: expected [6] but was [4]

	at __randomizedtesting.SeedInfo.seed([3996C2C8187055DE:B1C2FD12B68C3826]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:395)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:372)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[...]
```
```
java.lang.AssertionError: Failure at [search/110_field_collapsing:157]: hits.total didn't match expected value:
                    hits.total: expected [6] but was [5]

	at __randomizedtesting.SeedInfo.seed([3996C2C8187055DE:B1C2FD12B68C3826]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:395)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:372)
[...]
```
```
java.lang.AssertionError: Failure at [search.inner_hits/10_basic:32]: hits.total didn't match expected value:
                    hits.total: expected [1] but was [0]

	at __randomizedtesting.SeedInfo.seed([3996C2C8187055DE:B1C2FD12B68C3826]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:395)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:372)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
```
java.lang.AssertionError: Failure at [search/110_field_collapsing:118]: hits.total didn't match expected value:
                    hits.total: expected [6] but was [1]

	at __randomizedtesting.SeedInfo.seed([3996C2C8187055DE:B1C2FD12B68C3826]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:395)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:372)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

At least the first case reproduces locally for me:
```
REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v6.4.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=3996C2C8187055DE \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=search.inner_hits/10_basic/Nested doc version and seqIDs}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-GT \
  -Dtests.timezone=America/Inuvik

REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v6.4.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=3996C2C8187055DE \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=search/110_field_collapsing/field collapsing, inner_hits and maxConcurrentGroupRequests}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-GT \
  -Dtests.timezone=America/Inuvik

REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v6.4.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=3996C2C8187055DE \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=search/110_field_collapsing/field collapsing and multiple inner_hits}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-GT \
  -Dtests.timezone=America/Inuvik

REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v6.4.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=3996C2C8187055DE \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=search/110_field_collapsing/field collapsing, inner_hits and version}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-GT \
  -Dtests.timezone=America/Inuvik

REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v6.4.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=3996C2C8187055DE \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=search/110_field_collapsing/no hits and inner_hits}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-GT \
  -Dtests.timezone=America/Inuvik

REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v6.4.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=3996C2C8187055DE \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=search.inner_hits/10_basic/Nested inner hits}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-GT \
  -Dtests.timezone=America/Inuvik

REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v6.4.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=3996C2C8187055DE \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=search/110_field_collapsing/field collapsing and inner_hits}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-GT \
  -Dtests.timezone=America/Inuvik
```

**Comment by cbuescher** [comment]
Both tests seem to fail quite often also with other seeds, at least in the "mixed-cluster:v6.4.0-SNAPSHOT" scenario. I think it makes sense to mute them.

**Comment by cbuescher** [comment]
I muted the whole yml test suites for all versions on master: https://github.com/elastic/elasticsearch/commit/466235288e8fc74d265fbf6f98d044572a60a460
