### ISSUE TITLE
[CI] CreateIndexIT.testIndexWithUnknownSetting failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#32118]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2335/

The error is 
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=6940, name=elasticsearch[node_td3][write][T#1], state=RUNNABLE, group=TGRP-CreateIndexIT]
	at __randomizedtesting.SeedInfo.seed([4C96DA64C5B54786:A3C49766AA9A4A5B]:0)
Caused by: java.lang.AssertionError: shard term already update.  op term [2], shardTerm [3]
	at __randomizedtesting.SeedInfo.seed([4C96DA64C5B54786]:0)
	at org.elasticsearch.index.shard.IndexShard.lambda$acquireReplicaOperationPermit$9(IndexShard.java:2225)
	at org.elasticsearch.index.shard.IndexShardOperationPermits.doBlockOperations(IndexShardOperationPermits.java:173)
	at org.elasticsearch.index.shard.IndexShardOperationPermits.blockOperations(IndexShardOperationPermits.java:110)
	at org.elasticsearch.index.shard.IndexShard.acquireReplicaOperationPermit(IndexShard.java:2224)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncReplicaAction.doRun(TransportReplicationAction.java:616)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReplicaOperationTransportHandler.messageReceived(TransportReplicationAction.java:493)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReplicaOperationTransportHandler.messageReceived(TransportReplicationAction.java:479)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63)
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1679)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Does not reproduce 
```
./gradlew :server:integTest \
  -Dtests.seed=4C96DA64C5B54786 \
  -Dtests.class=org.elasticsearch.action.admin.indices.create.CreateIndexIT \
  -Dtests.method="testIndexWithUnknownSetting" \
  -Dtests.security.manager=true \
  -Dtests.locale=pt \
  -Dtests.timezone=US/Pacific-New
```

**Comment by ywelsch** [comment]
Closed by #32442. If this still occurs, please reopen.
