### ISSUE TITLE
[CI] RecoveryDuringReplicationTests.testRecoveryAfterPrimaryPromotion failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#32127]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu&&virtual/2563/

Failed with the error 
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=848, name=elasticsearch[org.elasticsearch.index.replication.RecoveryDuringReplicationTests][write][T#1], state=RUNNABLE, group=TGRP-RecoveryDuringReplicationTests]
	at __randomizedtesting.SeedInfo.seed([29BFDA931A3872E7:FCA847367D3E76B1]:0)
Caused by: java.lang.UnsupportedOperationException
	at __randomizedtesting.SeedInfo.seed([29BFDA931A3872E7]:0)
	at org.elasticsearch.index.replication.ESIndexLevelReplicationTestCase$ReplicationAction$ReplicasRef.failShardIfNeeded(ESIndexLevelReplicationTestCase.java:553)
	at org.elasticsearch.action.support.replication.ReplicationOperation$1.onFailure(ReplicationOperation.java:189)
	at org.elasticsearch.index.replication.ESIndexLevelReplicationTestCase$ReplicationAction$ReplicasRef$1.onFailure(ESIndexLevelReplicationTestCase.java:543)
	at org.elasticsearch.index.shard.IndexShard$3.onFailure(IndexShard.java:2288)
	at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:50)
	at org.elasticsearch.index.shard.IndexShardOperationPermits$PermitAwareThreadedActionListener$1.onFailure(IndexShardOperationPermits.java:379)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:708)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Does not reproduce
```
./gradlew :server:test \
  -Dtests.seed=29BFDA931A3872E7 \
  -Dtests.class=org.elasticsearch.index.replication.RecoveryDuringReplicationTests \
  -Dtests.method="testRecoveryAfterPrimaryPromotion" \
  -Dtests.security.manager=true \
  -Dtests.locale=uk-UA \
  -Dtests.timezone=America/Port_of_Spain
```

**Comment by bleskes** [comment]
I looked at this a bit and pushed a changed that will make it easier to debug the next time it fails

**Comment by original-brownbear** [comment]
I would suggest closing this. This failure hasn't occurred again since it was reported here as far as I can see.

**Comment by ywelsch** [comment]
agree -> close
