### ISSUE TITLE
[CI] SSLConfigurationReloaderTests fail on Java 11

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#32124]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/180
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/181

The failures are due to the test timing out
```
java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).
	at __randomizedtesting.SeedInfo.seed([5DB61DD425F081B]:0)
``` 

And the logs show some interesting errors
```
1> java.lang.NullPointerException: null
1> 	at org.elasticsearch.xpack.core.ssl.SSLService$SSLContextHolder.invalidateSessions(SSLService.java:552) ~[main/:?]
1> 	at org.elasticsearch.xpack.core.ssl.SSLService$SSLContextHolder.reload(SSLService.java:558) ~[main/:?]
1> 	at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloader.reloadSSLContext(SSLConfigurationReloader.java:80) ~[main/:?]
1> 	at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests$5.reloadSSLContext(SSLConfigurationReloaderTests.java:447) ~[test/:?]
1> 	at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloader$ChangeListener.onFileChanged(SSLConfigurationReloader.java:120) ~
```

The test fails with a different error when I run it with Java 11
```
ERROR   0.06s | SSLConfigurationReloaderTests.testReloadingTrustStore <<< FAILURES!
   > Throwable #1: java.lang.RuntimeException: Error connecting to the mock server
   >    at __randomizedtesting.SeedInfo.seed([5DB61DD425F081B:A93AE0D293F69319]:0)
   >    at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests.lambda$testReloadingTrustStore$13(SSLConfigurationReloaderTests.java:216)
   >    at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests.validateSSLConfigurationIsReloaded(SSLConfigurationReloaderTests.java:455)
   >    at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests.testReloadingTrustStore(SSLConfigurationReloaderTests.java:238)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   >    at java.base/java.lang.Thread.run(Thread.java:834)
   > Caused by: java.lang.NullPointerException
   >    at java.base/sun.security.ssl.SSLSessionImpl.getLocalPrincipal(SSLSessionImpl.java:661)
   >    at org.apache.http.impl.client.DefaultUserTokenHandler.getUserToken(DefaultUserTokenHandler.java:83)
   >    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:327)
   >    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
   >    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
   >    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
   >    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
   >    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
   >    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
   >    at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests.lambda$testReloadingTrustStore$12(SSLConfigurationReloaderTests.java:214)
   >    at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests.lambda$privilegedConnect$24(SSLConfigurationReloaderTests.java:533)
   >    at java.base/java.security.AccessController.doPrivileged(Native Method)
   >    at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests.privilegedConnect(SSLConfigurationReloaderTests.java:532)
   >    at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests.lambda$testReloadingTrustStore$13(SSLConfigurationReloaderTests.java:214)
   >    ... 38 more
```

**Reproduce:**
```
./gradlew :x-pack:plugin:core:test \
  -Dtests.seed=5DB61DD425F081B \
  -Dtests.class=org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=Etc/UTC
```

**Comment by cbuescher** [comment]
Some more of these today:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/185/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/186/console

**Comment by tvernum** [comment]
The original issue:

```
   > Caused by: java.lang.NullPointerException
   >    at java.base/sun.security.ssl.SSLSessionImpl.getLocalPrincipal(SSLSessionImpl.java:661)
```

should be fixed now, that was a bug in earlier JDK11 builds, that's fixed in ea11.

However there seems to be another issue to do with getting sessions by id.

This code:
```
       private void invalidateSessions(SSLSessionContext sslSessionContext) {
            Enumeration<byte[]> sessionIds = sslSessionContext.getIds();
            while (sessionIds.hasMoreElements()) {
                byte[] sessionId = sessionIds.nextElement();
                sslSessionContext.getSession(sessionId).invalidate();
            }
        }
```
is cause a NPE on the `getSession` which is strange since the ID came from `getIds` on the same object.

@jkakavas is investigating.

**Comment by jkakavas** [comment]
It looks as if we get a rogue session in the sessionCache with JDK11. 

The behavior of JDK10 is that `getIds()` returns one sessionId ( as expected as there has only been one connection to the MockServer that uses this context ) while in JDK11 we get 2 sessionIds and the following two cases 
- Both sessionIds can be used to `getSession()` an `SSLSession`. The two SSLSessions seem to be almost identical but one is missing information regarding localPrincipal and localCertificates. In this case the test passes. 
- One of the `sessionIds` can be used to `getSession()` an `SSLSession` while the other causes `getSession()` to return `null` which leads to an NPE.

This behavior only manifests when attempting to get the sessions for the serverContext and thus affects `testPEMKeyConfigReloading` and `testReloadingKeyStore`

**Comment by tvernum** [comment]
> One of the sessionIds can be used to getSession() an SSLSession while the other causes getSession() to return null which leads to an NPE.

Is it that the first invalidation causes the second session to be removed as well? Or was it always associated with a null `SSLSession?`

**Comment by tvernum** [comment]
Words are hard, and I realise my previous question isn't 100% clear so for clarification.
If we had the following code:


      public void testSessions(SSLSessionContext sslSessionContext) {
            List<byte[]> sessionIds = Collections.list(sslSessionContext.getIds());
            for (byte[] sessionId : sessionIds) {
                SSLSession session = sslSessionContext.getSession(sessionId)
                Objects.requireNotNull(session); // <<- A
            }
            for (byte[] sessionId : sessionIds) {
                SSLSession session = sslSessionContext.getSession(sessionId)
                Objects.requireNotNull(session); // <<- B
                session.invalidate();
            }
        } 

would we see a failure at A or at B (on the 2nd iteration of the loop)?

**Comment by jkakavas** [comment]
This seems to be related to SSL Session initialization in TLS1.3. 

For TLSv1.2 : 
```
net.ssl|DEBUG|0F|TEST-SSLConfigurationReloaderTests.testPEMKeyConfigReloading-seed#[AAAF4D15951F68D8]|2018-07-23 03:55:55.846 EDT|SSLCipher.java:436|jdk.net.keyLimits:  entry = AES/GCM/NoPadding KeyUpdate 2^37. AES/GCM/NOPADDING:KEYUPDATE = 137438953472
javax.net.ssl|ALL|13|HTTP-Dispatcher|2018-07-23 03:55:57.126 EDT|SSLSessionImpl.java:202|Session initialized:  Session(1532332557126|SSL_NULL_WITH_NULL_NULL)
javax.net.ssl|ALL|13|HTTP-Dispatcher|2018-07-23 03:55:57.135 EDT|X509Authentication.java:241|No X.509 cert selected for EC
javax.net.ssl|ALL|13|HTTP-Dispatcher|2018-07-23 03:55:57.135 EDT|X509Authentication.java:241|No X.509 cert selected for EC
javax.net.ssl|ALL|13|HTTP-Dispatcher|2018-07-23 03:55:57.150 EDT|SSLSessionImpl.java:428|Negotiating session:  Session(1532332557126|TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384)
javax.net.ssl|ALL|0F|TEST-SSLConfigurationReloaderTests.testPEMKeyConfigReloading-seed#[AAAF4D15951F68D8]|2018-07-23 03:55:57.242 EDT|SSLSessionImpl.java:202|Session initialized:  Session(1532332557242|TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384)
```

while for `TLSv1.3`:
```
javax.net.ssl|DEBUG|0F|TEST-SSLConfigurationReloaderTests.testPEMKeyConfigReloading-seed#[19D93C9F49C87B1F]|2018-07-23 09:57:37.348 CEST|SSLCipher.java:436|jdk.net.keyLimits:  entry = AES/GCM/NoPadding KeyUpdate 2^37. AES/GCM/NOPADDING:KEYUPDATE = 137438953472
javax.net.ssl|ALL|13|HTTP-Dispatcher|2018-07-23 09:57:38.351 CEST|SSLSessionImpl.java:202|Session initialized:  Session(1532332658350|SSL_NULL_WITH_NULL_NULL)
javax.net.ssl|ALL|13|HTTP-Dispatcher|2018-07-23 09:57:38.354 CEST|SSLSessionImpl.java:428|Negotiating session:  Session(1532332658350|TLS_AES_128_GCM_SHA256)
javax.net.ssl|DEBUG|13|HTTP-Dispatcher|2018-07-23 09:57:38.368 CEST|SSLCipher.java:1823|KeyLimit read side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|13|HTTP-Dispatcher|2018-07-23 09:57:38.370 CEST|SSLCipher.java:1977|KeyLimit write side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|ALL|13|HTTP-Dispatcher|2018-07-23 09:57:38.372 CEST|X509Authentication.java:241|No X.509 cert selected for EC
javax.net.ssl|ALL|13|HTTP-Dispatcher|2018-07-23 09:57:38.372 CEST|X509Authentication.java:241|No X.509 cert selected for EC
javax.net.ssl|ALL|13|HTTP-Dispatcher|2018-07-23 09:57:38.372 CEST|X509Authentication.java:241|No X.509 cert selected for EC
javax.net.ssl|DEBUG|13|HTTP-Dispatcher|2018-07-23 09:57:38.423 CEST|SSLCipher.java:1977|KeyLimit write side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|ALL|0F|TEST-SSLConfigurationReloaderTests.testPEMKeyConfigReloading-seed#[19D93C9F49C87B1F]|2018-07-23 09:57:38.425 CEST|SSLSessionImpl.java:202|Session initialized:  Session(1532332658425|TLS_AES_128_GCM_SHA256)
javax.net.ssl|DEBUG|0F|TEST-SSLConfigurationReloaderTests.testPEMKeyConfigReloading-seed#[19D93C9F49C87B1F]|2018-07-23 09:57:38.429 CEST|SSLCipher.java:1823|KeyLimit read side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|0F|TEST-SSLConfigurationReloaderTests.testPEMKeyConfigReloading-seed#[19D93C9F49C87B1F]|2018-07-23 09:57:38.430 CEST|SSLCipher.java:1977|KeyLimit write side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|0F|TEST-SSLConfigurationReloaderTests.testPEMKeyConfigReloading-seed#[19D93C9F49C87B1F]|2018-07-23 09:57:38.476 CEST|SSLCipher.java:1823|KeyLimit read side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|13|HTTP-Dispatcher|2018-07-23 09:57:38.479 CEST|SSLCipher.java:1823|KeyLimit read side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|ALL|13|HTTP-Dispatcher|2018-07-23 09:57:38.480 CEST|SSLSessionImpl.java:202|Session initialized:  Session(1532332658350|TLS_AES_128_GCM_SHA256)
javax.net.ssl|DEBUG|0F|TEST-SSLConfigurationReloaderTests.testPEMKeyConfigReloading-seed#[19D93C9F49C87B1F]|2018-07-23 09:57:38.483 CEST|SSLCipher.java:1977|KeyLimit write side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|ALL|0F|TEST-SSLConfigurationReloaderTests.testPEMKeyConfigReloading-seed#[19D93C9F49C87B1F]|2018-07-23 09:57:38.504 CEST|SSLSessionImpl.java:202|Session initialized:  Session(1532332658425|TLS_AES_128_GCM_SHA256)
``` 

This test uses a MockHttpServer and an SSLContext that is not bound by the `supportedProtocols` as an ES node would, and an Http client ( Apache HTTPClient ) that in jdk11 uses TLSv1.3 by default. This has the effect that TLSv1.3 is used and that leads to the observed behavior. 
I will pin the HTTP client to use TLSv1.2 (even in JDK11) for now so that the failures are mitigated here and we will address TLSv1.3 support holistically starting in https://github.com/elastic/elasticsearch/issues/32276

**Comment by tvernum** [comment]
> I will pin the HTTP client to use TLSv1.2

Can we try pinning the server instead? We can't control clients, and we want to know that we can handle a TLSv1.3 client, even if that means forcing it to downgrade to 1.2

**Comment by jkakavas** [comment]
> We can't control clients, and we want to know that we can handle a TLSv1.3 client, even if that means forcing it to downgrade to 1.2

Sure. We don't test any of our server side SSL configuration/behavior here (apart from the key/trust material reloading) and this is why I didn't opt to do so for downgrading the protocol version. If this was an ES node, it would fail the request with a protocol unsupported error though (for TLSv1.3 ) so we'd need to pin both the client and the server.

**Comment by jkakavas** [comment]
Rethinking this, it would require a rewrite of this test to use our `SSLSessionFactory` in order to apply the `SSLParameters` with the supported protocols and - more importantly - I think graceful downgrade of the TLS version should probably be tested on its own in our SSLServiceTests.

**Comment by andyb-elastic** [comment]
I muted a couple that have been failing frequently https://github.com/elastic/elasticsearch/commit/d43c3a18b9e729c4d3a9ad3be8efe32eb1722c09

**Comment by tbrooks8** [comment]
Reopening as I think there was another failure related to this today:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/273/console

**Comment by tbrooks8** [comment]
```
17:27:12   1> java.lang.NullPointerException: null
17:27:12   1> 	at org.elasticsearch.xpack.core.ssl.SSLService$SSLContextHolder.invalidateSessions(SSLService.java:552) ~[main/:?]
17:27:12   1> 	at org.elasticsearch.xpack.core.ssl.SSLService$SSLContextHolder.reload(SSLService.java:558) ~[main/:?]
17:27:12   1> 	at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloader.reloadSSLContext(SSLConfigurationReloader.java:80) ~[main/:?]
17:27:12   1> 	at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests$5.reloadSSLContext(SSLConfigurationReloaderTests.java:450) ~[test/:?]
17:27:12   1> 	at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloader$ChangeListener.onFileChanged(SSLConfigurationReloader.java:120) ~[main/:?]
17:27:12   1> 	at org.elasticsearch.watcher.FileWatcher$FileObserver.onFileChanged(FileWatcher.java:279) [elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
17:27:12   1> 	at org.elasticsearch.watcher.FileWatcher$FileObserver.checkAndNotify(FileWatcher.java:131) [elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
```

**Comment by jakelandis** [comment]
Another instance of this : https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/281/console
```
REPRODUCE WITH: ./gradlew :x-pack:plugin:core:test \
  -Dtests.seed=118A2BD57101A474 \
  -Dtests.class=org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests \
  -Dtests.method="testReloadingKeyStore" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-SX \
  -Dtests.timezone=US/Central \
  -Dcompiler.java=10 \
  -Druntime.java=11
```

**Comment by imotov** [comment]
Failed again today https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/301/console

```
./gradlew :x-pack:plugin:core:test \
  -Dtests.seed=83F9ABD7B2538517 \
  -Dtests.class=org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests \
  -Dtests.method="testReloadingKeyStore" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-ER \
  -Dtests.timezone=Africa/Bujumbura \
  -Dcompiler.java=11 \
  -Druntime.java=11
```

**Comment by jkakavas** [comment]
Our `MockWebServer` doesn't take into consideration the `supported_protocols` and as such even if it is initialized with a TLSv1.2 SslContext, if it receives a request that uses TLSv1.3 ( which is what the HttpClient does by default in Jdk-11) it will create TLSv1.3 sessions - so the original issue manifests again. I will pin the client to TLS1.2 too.

**Comment by jaymode** [comment]
I just ran into this issue locally with the updated elasticsearch-ci that uses Java 11. This was a build off of the 6.x branch:

```
Suite: org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests
  1> [2018-09-28T05:03:12,031][INFO ][o.e.x.c.s.SSLConfigurationReloaderTests] [testTrustStoreReloadException] before test
  1> [2018-09-28T05:03:12,389][INFO ][o.e.x.c.s.SSLConfigurationReloaderTests] [testTrustStoreReloadException] after test
  1> [2018-09-28T05:03:12,400][INFO ][o.e.x.c.s.SSLConfigurationReloaderTests] [testReloadingKeyStore] before test
  1> [2018-09-28T05:03:12,894][INFO ][o.e.t.h.MockWebServer    ] [testReloadingKeyStore] bound HTTP mock server to [127.0.0.1:34123]
  1> [2018-09-28T05:03:13,456][WARN ][o.e.w.FileWatcher        ] [reload tests] cannot notify file changes listener
  1> java.lang.NullPointerException: null
  1> 	at org.elasticsearch.xpack.core.ssl.SSLService$SSLContextHolder.invalidateSessions(SSLService.java:552) ~[main/:?]
  1> 	at org.elasticsearch.xpack.core.ssl.SSLService$SSLContextHolder.reload(SSLService.java:558) ~[main/:?]
  1> 	at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloader.reloadSSLContext(SSLConfigurationReloader.java:80) ~[main/:?]
  1> 	at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests$5.reloadSSLContext(SSLConfigurationReloaderTests.java:450) ~[test/:?]
  1> 	at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloader$ChangeListener.onFileChanged(SSLConfigurationReloader.java:120) ~[main/:?]
  1> 	at org.elasticsearch.watcher.FileWatcher$FileObserver.onFileChanged(FileWatcher.java:279) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.watcher.FileWatcher$FileObserver.checkAndNotify(FileWatcher.java:131) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.watcher.FileWatcher$FileObserver.updateChildren(FileWatcher.java:215) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.watcher.FileWatcher$FileObserver.checkAndNotify(FileWatcher.java:117) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.watcher.FileWatcher.doCheckAndNotify(FileWatcher.java:70) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.watcher.AbstractResourceWatcher.checkAndNotify(AbstractResourceWatcher.java:44) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.watcher.ResourceWatcherService$ResourceMonitor.run(ResourceWatcherService.java:197) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:182) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.threadpool.ThreadPool$LoggingRunnable.run(ThreadPool.java:447) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
  1> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
  1> 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
  1> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
  1> 	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Reproduce line:

```
./gradlew :x-pack:plugin:core:test -Dtests.seed=7D7A54BFB3B2AF9C -Dtests.class=org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests -Dtests.method="testReloadingKeyStore" -Dtests.security.manager=true -Dtests.jvms=6 -Dtests.locale=sr-Latn -Dtests.timezone=Australia/Lindeman -Dcompiler.java=11 -Druntime.java=11
```

JDK 11 info:

```
  JDK Version           : 11 (Oracle Corporation 11 [OpenJDK 64-Bit Server VM 11+28])
```

Is there a reason why we haven't added a null check here?

**Comment by jkakavas** [comment]
> Is there a reason why we haven't added a null check here?

This seemed to be related to TLS1.3 and we wanted to investigate why we end up with duplicate sessions in the session cache for each connection. ( The issue here manifested due to the duplicate - same sessionId - sessions in the session cache. Invalidating by sessionId removed both so the second getSession() threw an NPE )

**Comment by jshnaidman** [comment]
Probably related to [JDK-8239925](https://bugs.openjdk.org/browse/JDK-8239925)
