### ISSUE TITLE
write full path for files logged in all CorruptIndexException messages

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#32136]
**Describe the feature**:
Log full path for any `CorruptIndexException` messages. It is logged in some instances, but not all. 

`resource=name [_8wy.fdt]` logged without path:
```
[2018-05-17T21:19:03,555][WARN ][o.e.i.c.IndicesClusterStateService] [hostb] [[an_index][3]] marking and sending shard failed due to [failed recovery]
org.elasticsearch.indices.recovery.RecoveryFailedException: [an_index][3]: Recovery failed from {hosta}{FkB2o7OPO1zvjS_Q0BrA}{LtT6CcyzR-WYFtmOXUgg}{10.1.2.3}{10.1.2.3:9300}{ml.max_open_jobs=10, ml.enabled=true} into {hostb}{WcfmKKiomrpWSKLb-Q}{saj9QReFElZtWDeHWQ}{10.1.2.4}{10.1.2.4:9300}{ml.max_open_jobs=10, ml.enabled=true}
	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.doRecovery(PeerRecoveryTargetService.java:314) [elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.access$900(PeerRecoveryTargetService.java:73) [elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$RecoveryRunner.doRun(PeerRecoveryTargetService.java:556) [elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:674) [elasticsearch-5.6.8.jar:5.6.8]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.8.jar:5.6.8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
<truncated>
Caused by: org.elasticsearch.transport.RemoteTransportException: [hosta][10.1.2.3:9300][internal:index/shard/recovery/start_recovery]
Caused by: org.elasticsearch.index.engine.RecoveryEngineException: Phase[1] phase1 failed
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:140) ~[elasticsearch-5.6.8.jar:5.6.8]
<truncated>
Caused by: org.elasticsearch.indices.recovery.RecoverFilesRecoveryException: Failed to transfer [15] files with total size of [20.6gb]
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:337) ~[elasticsearch-5.6.8.jar:5.6.8]
<truncated>
Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=1kx10z4 actual=1hdpsa2 (resource=name [_8wy.fdt], length [9894922455], checksum [1kx10z4], writtenBy [6.6.1]) (resource=VerifyingIndexOutput(_8wy.fdt))
```

`_ni_Lucene50_0.doc` logged with path:
```
[2018-07-16T01:16:51,543][WARN ][o.e.c.a.s.ShardStateAction] [hostc] [another_index][27] received shard failed for shard id [[another_index][27]], allocation id [jUAyqycJRrWNn4k4iOxmog], primary term [0], message [shard failure, reason [corrupt file (source: [index])]], failure [AlreadyClosedException[this IndexWriter is closed]; nested: CorruptIndexException[checksum failed (hardware problem?) : expected=171ad61b actual=effb05fc (resource=BufferedChecksumIndexInput(MMapIndexInput(path="/volumes/data/elasticsearch/cluster_name/nodes/0/indices/6-Vi1WR7RKGv3YUUaeA/27/index/_ni_Lucene50_0.doc")))]; ]
org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
```

Knowing the full path will help identify the problem physical drive if the node is using multiple data paths. Checking kernel messages will also help identify problem hardware, but sometimes the file system checker does its work and kernel logs go away which can leave the admin poking around the file system to locate a problem shard. This can be very time consuming for large clusters.

**Comment by ahmedmi9** [comment]
I would like to work on this ...Can I proceed?

**Comment by ahmedmi9** [comment]
Thanks, @jasontedor. Since this will be my first contribution this project, I might take some time to analyze and little help from you guys. So please bear with me.

**Comment by bipgen** [comment]
If this issue is not resolved yet, i would like to have a go at it.

**Comment by ahmedmi9** [comment]
Sure @bipgen , you can go ahead as this has not been resolved yet. @jasontedor extremely sorry, after initial setup I got super busy on other stuff and could not give time on this.

**Comment by vladimirdolzhenko** [comment]
I would like to add to pay attention to `TranslogCorruptedException` messages as well - corruption of translog is same important as corruption of Lucene index (that is stored actually in `CorruptIndexException`)

**Comment by jevalen4868** [comment]
Hello folks, if this fella is open I'd like to take a look.

**Comment by h-hub** [comment]
Hi guys, May start working on this ? No body has commented on this since 24th of Sep.

**Comment by vladimirdolzhenko** [comment]
@h-hub sure! contributors are always welcome

**Comment by h-hub** [comment]
@vladimirdolzhenko Thanks and this will help me to get started wit open source

**Comment by Gregovich1** [comment]
https://github.com/elastic/elasticsearch/blob/46962308aa9eb274231ba79ce295baad54ce015a/server/src/main/java/org/elasticsearch/index/store/Store.java#L1237

This line is generating the unhelpful message.
metaData.name needs to be populated with the full path, but after a few hours of searching, we could not find if or where the full path is included in that object.

**Comment by h-hub** [comment]
@jasontedor Thanks and will do so.

**Comment by camilin87** [comment]
@inqueue Can this issue be closed then?

> @h-hub We just fixed this with #36851. Please pull the latest. In the future, please open a new issue for better visibility.

**Comment by jasontedor** [comment]
> Can this issue be closed then?

@camilin87 My [comment](
https://github.com/elastic/elasticsearch/issues/32136#issuecomment-448678389) "We just fixed this with #36851." was about a [test failure](
https://github.com/elastic/elasticsearch/issues/32136#issuecomment-448677558) reported within this issue, not about this issue itself.

**Comment by allanamancio** [comment]
I would like to work on this issue. Is it possible?

**Comment by ywelsch** [comment]
@Gregovich1 made a good point here. The information requested here is not available at the point where the exception is generated. The case we're looking at is the peer recovery where we verify on the recovery target that the index we're writing is not corrupted. If there is a corruption, we only know the filename of the original file on the recovery source that had that corruption, but not the full path to the file (which is irrelevant for the recovery target).

I wonder if we should do the checksum verification on the recovery source while sending the file chunks, which would allow us to identify the correct full path of the file that's corrupted. This will create a tiny bit more overhead on the source side, but I think that's ok (needs benchmarking). We can then still do extra validation on the target side, if need be.

I've marked this as `team-discuss` to get some feedback on my suggestion.
@allanamancio let's hold off on working on this until we have a plan on how to address it.

**Comment by DaveCTurner** [comment]
https://github.com/elastic/elasticsearch/issues/71205 will remove the ambiguity about the path to the directory containing the index, so I think we can close this.
