### ISSUE TITLE
Initialization of LoggingDeprecationHandler fails because of missing log4j core dependency

### ISSUE THREAD

**Issue by florian-perrotti** [elastic/elasticsearch#32151]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
6.3.0 
**Plugins installed**: []

**JVM version** (`java -version`):
1.8.0
**OS version** (`uname -a` if on a Unix-like system):
AIX ***** 1 7 00C7EE054C00
**Description of the problem including expected versus actual behavior**:

When trying to index a document using the rest high level client, we have the following error message
`java.lang.NoClassDefFoundError: org.apache.logging.log4j.core.Appender` because as we are using the logback we do not have the log4j-core dependency.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Use logback with log4j-to-slf4j
 2. Use the `index` method on `RestHighLevelClient` with and `IndexRequest`:
```java 
      IndexRequest request = new IndexRequest(index, "doc", id);
      request.source(source, XContentType.JSON);
      highElasticClient.index(request);
```

**Provide logs (if relevant)**:

```
java.lang.NoClassDefFoundError: org.apache.logging.log4j.core.Appender
        at org.elasticsearch.common.xcontent.LoggingDeprecationHandler.<clinit>(LoggingDeprecationHandler.java:45)
        at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:651)
        at org.elasticsearch.client.RestHighLevelClient.lambda$performRequestAndParseEntity$2(RestHighLevelClient.java:508)
        at org.elasticsearch.client.RestHighLevelClient$$Lambda$203.000000002585ACF0.apply(Unknown Source)
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:539)
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508)
        at org.elasticsearch.client.RestHighLevelClient.index(RestHighLevelClient.java:348)
```

We have tried using [this](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/_using_another_logger.html) but as some of the classes in [Loggers.java](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/common/logging/Loggers.java#L27) are actually coming from log4j-core they are nowhere to be found.

Any ideas on something we can try to have these operations working and logs redirected to logback ?
Thanks in advance

**Comment by jasontedor** [comment]
@nik9000 or @dakrone Can one of you pick this one up?

**Comment by nik9000** [comment]
@dakrone I think we should use forbidden apis to ban LoggingDeprecationHandler from the high level rest client. What do you think?

**Comment by dakrone** [comment]
@nik9000 I think that sounds reasonable

**Comment by nik9000** [comment]
I'm gonna do this.

**Comment by nik9000** [comment]
@florian-perrotti - I'll push a fix and it'll release the next time we cut a release.

What is happening is that the high level rest client shares a bunch of stuff with the Elasticsearch server so it includes the server. We'd like to only include the request and responses but that'll take some doing. Anyway, because it is available, we started using a portion of the server that logs deprecation warnings. It needs log4j's implementation, not log4j's API. This was a mistake. Luckily I spent a while refactoring things so this implementation is pluggable so I'm plugging something else in and I'm using one of our static analysis tools to forbid this particular implementation in the high level client. It isn't a guarantee that we won't accidentally drag log4j's implementation in again, but it is something.

**Comment by nik9000** [comment]
Hmm - on second look, it actually may not require log4j's implementation. You could try adding log4j2's [bridge](https://logging.apache.org/log4j/log4j-2.2/log4j-to-slf4j/index.html) to slf4j.

**Comment by florian-perrotti** [comment]
@nik9000 thanks for the feedback !
I'll be sure to upgrade to the next version when it is released. For now we included `log4j-core` (not ideal) to avoid this issue even if we might loose some logs for the time being.

Regarding your second comment, I tried that but it didn't work. 
If I take a look at the adapter's [code](https://github.com/apache/logging-log4j2/blob/master/log4j-to-slf4j), it makes sense that it does not right? In the `pom.xml` the `log4j-core` is nowhere to be found and there are no classes with the same full name so when it comes to [Loggers.java](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/common/logging/Loggers.java#L27) it would still be the same no? 
Does this makes sense to you? I might be missing something...

**Comment by nik9000** [comment]
> Does this makes sense to you? I might be missing something...

Yeah, it does. I was missing that `LoggingDeprecationHandler` goes through `Loggers` instead of `LogManager` and I was only reading `DeprecationLogger`. `Loggers` needs log4's implementation which is a shame. Though that does imply some follow up changes I could make to the high level rest client to make it less likely to fail like this again.

Best would be if we could run the tests without log4j's implementation jar on the classpath but we can't because our tests use it....

**Comment by nik9000** [comment]
You should see this fixed in the 6.4.0 release of the client.

**Comment by florian-perrotti** [comment]
Perfect thanks a lot!

**Comment by kosa1234** [comment]
@nik9000 - I am also facing the same issue. I am on 6.4.2 version. The stacktrace looks like below - 
 java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.common.xcontent.LoggingDeprecationHandler
	at org.elasticsearch.action.update.UpdateRequest.toXContent(UpdateRequest.java:868)
	at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:349)
	at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:335)
	at org.elasticsearch.client.RequestConverters.createEntity(RequestConverters.java:1145)
	at org.elasticsearch.client.RequestConverters.update(RequestConverters.java:553)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1252)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1231)
	at org.elasticsearch.client.RestHighLevelClient.update(RestHighLevelClient.java:634)
	at co.quicko.api.elastic.LatestElasticUtil.update(LatestElasticUtil.java:122)
	at co.quicko.api.elastic.LatestElasticDaemon.update(LatestElasticDaemon.java:183)
	at co.quicko.api.elastic.ElasticTrigger.update(ElasticTrigger.java:127)
	at co.quicko.api.elastic.ElasticTrigger.onTrigger(ElasticTrigger.java:103)
	at co.quicko.api.gestor.GestorFactory$AsyncTriggerExecutor.run(GestorFactory.java:494)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.IllegalStateException: Failed to close the XContentBuilder
		at org.elasticsearch.common.xcontent.XContentBuilder.close(XContentBuilder.java:924)
		at org.elasticsearch.common.xcontent.XContentHelper.$closeResource(XContentHelper.java:113)
		at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:354)
		... 18 more
	Caused by: java.io.IOException: Unclosed object or array found
		at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.close(JsonXContentGenerator.java:444)
		at org.elasticsearch.common.xcontent.XContentBuilder.close(XContentBuilder.java:922)
		... 20 more

**Comment by kosa1234** [comment]
@nik9000 - I am also facing the same issue. I am on 6.4.2 version. The stacktrace looks like below -
`java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.common.xcontent.LoggingDeprecationHandler at org.elasticsearch.action.update.UpdateRequest.toXContent(UpdateRequest.java:868) at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:349) at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:335) at org.elasticsearch.client.RequestConverters.createEntity(RequestConverters.java:1145) at org.elasticsearch.client.RequestConverters.update(RequestConverters.java:553) at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1252) at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1231) at org.elasticsearch.client.RestHighLevelClient.update(RestHighLevelClient.java:634)`

**Comment by nik9000** [comment]
@kosa1234, I've filed a new issue for this.
