### ISSUE TITLE
[CI] NPE in ActiveDirectorySessionFactoryTests

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#32199]
Failure: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/2567/console

```
REPRODUCE WITH: ./gradlew :x-pack:qa:third-party:active-directory:test \
  -Dtests.seed=AA11A8306C06B78E \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.ADLdapUserSearchSessionFactoryTests \
  -Dtests.method="testUserSearchWithActiveDirectory" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-CA \
  -Dtests.timezone=Australia/Currie

REPRODUCE WITH: ./gradlew :x-pack:qa:third-party:active-directory:test \
  -Dtests.seed=AA11A8306C06B78E \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactoryTests \
  -Dtests.method="testAdAuth" \
  -Dtests.security.manager=true \
  -Dtests.locale=mt \
  -Dtests.timezone=US/Samoa

REPRODUCE WITH: ./gradlew :x-pack:qa:third-party:active-directory:test \
  -Dtests.seed=AA11A8306C06B78E \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactoryTests \
  -Dtests.method="testAuthenticate" \
  -Dtests.security.manager=true \
  -Dtests.locale=mt \
  -Dtests.timezone=US/Samoa

REPRODUCE WITH: ./gradlew :x-pack:qa:third-party:active-directory:test \
  -Dtests.seed=AA11A8306C06B78E \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactoryTests \
  -Dtests.method="testAdAuthAvengers" \
  -Dtests.security.manager=true \
  -Dtests.locale=mt \
  -Dtests.timezone=US/Samoa

REPRODUCE WITH: ./gradlew :x-pack:qa:third-party:active-directory:test \
  -Dtests.seed=AA11A8306C06B78E \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactoryTests \
  -Dtests.method="testAuthenticateWithSAMAccountName" \
  -Dtests.security.manager=true \
  -Dtests.locale=mt \
  -Dtests.timezone=US/Samoa

REPRODUCE WITH: ./gradlew :x-pack:qa:third-party:active-directory:test \
  -Dtests.seed=AA11A8306C06B78E \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactoryTests \
  -Dtests.method="testAuthenticateBaseGroupSearch" \
  -Dtests.security.manager=true \
  -Dtests.locale=mt \
  -Dtests.timezone=US/Samoa

REPRODUCE WITH: ./gradlew :x-pack:qa:third-party:active-directory:test \
  -Dtests.seed=AA11A8306C06B78E \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactoryTests \
  -Dtests.method="testAuthenticateWithUserPrincipalName" \
  -Dtests.security.manager=true \
  -Dtests.locale=mt \
  -Dtests.timezone=US/Samoa

REPRODUCE WITH: ./gradlew :x-pack:qa:third-party:active-directory:test \
  -Dtests.seed=AA11A8306C06B78E \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactoryTests \
  -Dtests.method="testCustomUserFilter" \
  -Dtests.security.manager=true \
  -Dtests.locale=mt \
  -Dtests.timezone=US/Samoa

REPRODUCE WITH: ./gradlew :x-pack:qa:third-party:active-directory:test \
  -Dtests.seed=AA11A8306C06B78E \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactoryTests \
  -Dtests.method="testStandardLdapConnection" \
  -Dtests.security.manager=true \
  -Dtests.locale=mt \
  -Dtests.timezone=US/Samoa

REPRODUCE WITH: ./gradlew :x-pack:qa:third-party:active-directory:test \
  -Dtests.seed=AA11A8306C06B78E \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactoryTests \
  -Dtests.method="testAuthenticateBaseUserSearch" \
  -Dtests.security.manager=true \
  -Dtests.locale=mt \
  -Dtests.timezone=US/Samoa
```

The log contains several NPEs like this one:
```
15:32:53   1> [2018-07-19T23:32:52,755][INFO ][o.e.x.s.a.l.ADLdapUserSearchSessionFactoryTests] [testUserSearchWithActiveDirectory]: after test
15:32:53 ERROR   0.88s J0 | ADLdapUserSearchSessionFactoryTests.testUserSearchWithActiveDirectory <<< FAILURES!
15:32:53    > Throwable #1: java.lang.NullPointerException: SSL Configuration cannot be null
15:32:53    > 	at __randomizedtesting.SeedInfo.seed([AA11A8306C06B78E:9D7FF1EF7DCCD8C4]:0)
15:32:53    > 	at java.util.Objects.requireNonNull(Objects.java:228)
15:32:53    > 	at org.elasticsearch.xpack.core.ssl.SSLService.sslContextHolder(SSLService.java:274)
15:32:53    > 	at org.elasticsearch.xpack.core.ssl.SSLService.sslContext(SSLService.java:266)
15:32:53    > 	at org.elasticsearch.xpack.core.ssl.SSLService.sslSocketFactory(SSLService.java:199)
15:32:53    > 	at org.elasticsearch.xpack.security.authc.ldap.support.SessionFactory.serverSet(SessionFactory.java:186)
15:32:53    > 	at org.elasticsearch.xpack.security.authc.ldap.support.SessionFactory.<init>(SessionFactory.java:78)
15:32:53    > 	at org.elasticsearch.xpack.security.authc.ldap.PoolingSessionFactory.<init>(PoolingSessionFactory.java:65)
15:32:53    > 	at org.elasticsearch.xpack.security.authc.ldap.LdapUserSearchSessionFactory.<init>(LdapUserSearchSessionFactory.java:47)
15:32:53    > 	at org.elasticsearch.xpack.security.authc.ldap.LdapUserSearchSessionFactoryTests.getLdapUserSearchSessionFactory(LdapUserSearchSessionFactoryTests.java:587)
15:32:53    > 	at org.elasticsearch.xpack.security.authc.ldap.ADLdapUserSearchSessionFactoryTests.testUserSearchWithActiveDirectory(ADLdapUserSearchSessionFactoryTests.java:95)
```

**Comment by cbuescher** [comment]
I was able to reproduce this locally now (after a long smb-fixture setup). Running:

```
./gradlew :x-pack:qa:third-party:active-directory:test \
  -Dtests.seed=AA11A8306C06B78E \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.ADLdapUserSearchSessionFactoryTests \
  -Dtests.method="testUserSearchWithActiveDirectory" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-CA \
  -Dtests.timezone=Australia/Currie
```

Results in:

```
> Throwable #1: java.lang.NullPointerException: SSL Configuration cannot be null
   >    at __randomizedtesting.SeedInfo.seed([AA11A8306C06B78E:9D7FF1EF7DCCD8C4]:0)
   >    at java.base/java.util.Objects.requireNonNull(Objects.java:246)
   >    at org.elasticsearch.xpack.core.ssl.SSLService.sslContextHolder(SSLService.java:274)
   >    at org.elasticsearch.xpack.core.ssl.SSLService.sslContext(SSLService.java:266)
   >    at org.elasticsearch.xpack.core.ssl.SSLService.sslSocketFactory(SSLService.java:199)
   >    at org.elasticsearch.xpack.security.authc.ldap.support.SessionFactory.serverSet(SessionFactory.java:186)
   >    at org.elasticsearch.xpack.security.authc.ldap.support.SessionFactory.<init>(SessionFactory.java:78)
   >    at org.elasticsearch.xpack.security.authc.ldap.PoolingSessionFactory.<init>(PoolingSessionFactory.java:65)
   >    at org.elasticsearch.xpack.security.authc.ldap.LdapUserSearchSessionFactory.<init>(LdapUserSearchSessionFactory.java:47)
   >    at org.elasticsearch.xpack.security.authc.ldap.LdapUserSearchSessionFactoryTests.getLdapUserSearchSessionFactory(LdapUserSearchSessionFactoryTests.java:587)
   >    at org.elasticsearch.xpack.security.authc.ldap.ADLdapUserSearchSessionFactoryTests.testUserSearchWithActiveDirectory(ADLdapUserSearchSessionFactoryTests.java:95)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by tvernum** [comment]
Fix by https://github.com/elastic/elasticsearch/commit/6f2b7dc9fe6143d2cc2bf26d83983a3a49c40b90
