### ISSUE TITLE
[CI] SessionFactoryLoadBalancingTests testRoundRobinWithFailures fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#32190]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/1190/console

Could not reproduce with:
```
REPRODUCE WITH: gradlew :x-pack:plugin:security:test \
  -Dtests.seed=16B5154ACCB4889F \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.support.SessionFactoryLoadBalancingTests \
  -Dtests.method="testRoundRobinWithFailures" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-QA \
  -Dtests.timezone=US/Central

REPRODUCE WITH: gradlew :x-pack:plugin:security:test \
  -Dtests.seed=16B5154ACCB4889F \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.support.SessionFactoryLoadBalancingTests \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=UTC
```

Looks like there are connection issues:
```
10:27:12   2> WARNING: Suite execution timed out: org.elasticsearch.xpack.security.authc.ldap.support.SessionFactoryLoadBalancingTests
10:27:12   1> java.net.BindException: Address already in use: connect
10:27:12   2> ==== jstack at approximately timeout time ====
10:27:12   1> 	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_172]
10:27:12   1> 	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_172]
10:27:12   2> "elasticsearch[SessionFactoryLoadBalancingTests thread pool][[timer]]" ID=2333 TIMED_WAITING
10:27:12   2> 	at java.lang.Thread.sleep(Native Method)
10:27:12   1> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_172]
10:27:12   2> 	at org.elasticsearch.threadpool.ThreadPool$CachedTimeThread.run(ThreadPool.java:543)
10:27:12   2> "LDAP Listener Thread (listening on port 63056)" ID=2331 RUNNABLE (in native code)
10:27:12   2> 	at java.net.DualStackPlainSocketImpl.accept0(Native Method)
10:27:12   2> 	at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:131)
10:27:12   1> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_172]
10:27:12   1> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_172]
10:27:12   1> 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_172]
10:27:12   1> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_172]
10:27:12   1> 	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_172]
10:27:12   1> 	at org.elasticsearch.mocksocket.MockSocket.access$101(MockSocket.java:32) ~[mocksocket-1.2.jar:?]
10:27:12   2> 	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
10:27:12   2> 	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
10:27:12   1> 	at org.elasticsearch.mocksocket.MockSocket.lambda$connect$0(MockSocket.java:66) ~[mocksocket-1.2.jar:?]
10:27:12   1> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_172]
10:27:12   1> 	at org.elasticsearch.mocksocket.MockSocket.connect(MockSocket.java:65) ~[mocksocket-1.2.jar:?]
10:27:12   1> 	at org.elasticsearch.mocksocket.MockSocket.connect(MockSocket.java:59) ~[mocksocket-1.2.jar:?]
10:27:12   2> 	- locked java.net.SocksSocketImpl@1d4bb36e
10:27:12   1> 	at java.net.Socket.<init>(Socket.java:434) ~[?:1.8.0_172]
10:27:12   1> 	at java.net.Socket.<init>(Socket.java:328) ~[?:1.8.0_172]
10:27:12   1> 	at org.elasticsearch.mocksocket.MockSocket.<init>(MockSocket.java:54) ~[mocksocket-1.2.jar:?]
```

This leads to test timeouts later.

**Comment by cbuescher** [comment]
This one from earlier this week looks similar:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1758/console

Note: also on Windows, maybe the test is flaky just there?

**Comment by atorok** [comment]
and annother: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/10/consoleFull

**Comment by cbuescher** [comment]
Another one: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/20/consoleFull

**Comment by atorok** [comment]
There's another https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/44/console  will mute the test.

**Comment by gwbrown** [comment]
Another one today in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+periodic/138/

This has failed a few times lately so I'm going to mute this test in master, 6.x, and 6.6.

**Comment by jaymode** [comment]
@bizybot I have some ideas to improve this so I reassigned to myself
