### ISSUE TITLE
[CI] index.fielddata.ScriptDocValuesDatesTests failure

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#32227]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=centos/1192/console

Reproducable locally:
```
./gradlew :server:test -Dtests.seed=88E2FE5089CFA4F1 -Dtests.class=org.elasticsearch.index.fielddata.ScriptDocValuesDatesTests -Dtests.method="test" -Dtests.security.manager=true -Dtests.locale=fr-LU -Dtests.timezone=Pacific/Fakaofo
```

Error:

```
Suite: org.elasticsearch.index.fielddata.ScriptDocValuesDatesTests
  1> [2018-07-20T20:25:01,872][INFO ][o.e.i.f.ScriptDocValuesDatesTests] [test]: before test
  1> [2018-07-20T20:25:02,363][INFO ][o.e.i.f.ScriptDocValuesDatesTests] [test]: after test
  2> REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=88E2FE5089CFA4F1 -Dtests.class=org.elasticsearch.index.fielddata.ScriptDocValuesDatesTests -Dtests.method="test" -Dtests.security.manager=true -Dtests.locale=fr-LU -Dtests.timezone=Pacific/Fakaofo
FAILURE 0.64s | ScriptDocValuesDatesTests.test <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: iterable over ["getDate is no longer necessary on date fields as the value is now a date.", "getDates is no longer necessary on date fields as the values are now dates."] in any order
   >      but: No item matches: "getDate is no longer necessary on date fields as the value is now a date." in ["getDates is no longer necessary on date fields as the values are now dates."]
   >    at __randomizedtesting.SeedInfo.seed([88E2FE5089CFA4F1:B6C18A2733C909]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.index.fielddata.ScriptDocValuesDatesTests.test(ScriptDocValuesDatesTests.java:101)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
  2> NOTE: leaving temporary files on disk at: /home/hendrik/work/git-elastic/elasticsearch/server/build/testrun/test/J0/temp/org.elasticsearch.index.fielddata.ScriptDocValuesDatesTests_88E2FE5089CFA4F1-001
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=1760, maxMBSortInHeap=6.11519377933257, sim=RandomSimilarity(queryNorm=true): {}, locale=fr-LU, timezone=Pacific/Fakaofo
  2> NOTE: Linux 4.13.0-45-generic amd64/Oracle Corporation 10 (64-bit)/cpus=4,threads=1,free=507139152,total=536870912
  2> NOTE: All tests run in this JVM: [ScriptDocValuesDatesTests]
Completed [1/1] in 4.44s, 1 test, 1 failure <<< FAILURES!
```

Quick investigation result: Seems to be randomization problem, the line:

https://github.com/elastic/elasticsearch/blob/6.x/server/src/test/java/org/elasticsearch/index/fielddata/ScriptDocValuesDatesTests.java#L66

does not get called for this seed.

Not muting the test for now as it succeeds for other seeds.

**Comment by jdconrad** [comment]
Another one (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+release-tests/898/console)

@rjernst Are you the best person to take a look at this?
