### ISSUE TITLE
[ci] UpgradeClusterClientYamlTestSuiteIT - master fails when writing DocStats

### ISSUE THREAD

**Issue by andyb-elastic** [elastic/elasticsearch#32303]
Doesn't reproduce locally

Failing tests are

```
old_cluster/40_ml_datafeed_crud/Put job and datafeed in old cluster
old_cluster/50_ml_jobs_crud/Put job with empty strings in the configuration
```

```
REPRODUCE WITH: ./gradlew :x-pack-elasticsearch:qa:rolling-upgrade:without-ssl-with-system-key:v5.0.2#oldClusterTestRunner \
  -Dtests.seed=90BB3616D77785F0 \
  -Dtests.class=org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=old_cluster/40_ml_datafeed_crud/Put job and datafeed in old cluster}" \
  -Dtests.security.manager=true \
  -Dtests.locale=hr \
  -Dtests.timezone=EST5EDT \
  -Dtests.rest.suite=old_cluster \
  -Dtests.rest.blacklist=old_cluster/40_ml_datafeed_crud/*,old_cluster/50_ml_jobs_crud/*
```

https://internal-ci.elastic.co/job/elastic+x-pack-elasticsearch+5.6+bwc-tests/911/console

ci logs
[build-911.txt](https://github.com/elastic/elasticsearch/files/2221314/build-911.txt)

integ test cluster node 0 log
[run.log](https://github.com/elastic/elasticsearch/files/2221316/run.log)

integ test cluster node 1 log
[run.log](https://github.com/elastic/elasticsearch/files/2221317/run.log)

From the cluster logs for node0

```
[2018-07-23T03:55:15,185][INFO ][o.e.x.m.e.Exporters      ] [j7cI6y5] skipping exporter [default_local] as it isn't ready yet
[2018-07-23T03:55:15,186][ERROR][o.e.x.m.AgentService     ] [j7cI6y5] exception when exporting documents
org.elasticsearch.xpack.monitoring.exporter.ExportException: exporters are either not ready or faulty
        at org.elasticsearch.xpack.monitoring.exporter.Exporters.export(Exporters.java:188) ~[x-pack-5.0.2.jar:5.0.2]
        at org.elasticsearch.xpack.monitoring.AgentService$ExportingWorker.run(AgentService.java:208) [x-pack-5.0.2.jar:5.0.2]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[2018-07-23T03:55:17,901][INFO ][o.e.c.s.ClusterService   ] [j7cI6y5] detected_master {Ko7SxWG}{Ko7SxWGzRbqJYL-GcmG_8A}{lEEDF8DcT_eFtVh3m0Z72w}{127.0.0.1}{127.0.0.1:46645}{testattr=test}, added {{Ko7SxWG}{Ko7SxWGzRbqJYL-GcmG_8A}{lEEDF8DcT_eFtVh3m0Z72w}{127.0.0.1}{127.0.0.1:46645}{testattr=test},}, reason: zen-disco-receive(from master [master {Ko7SxWG}{Ko7SxWGzRbqJYL-GcmG_8A}{lEEDF8DcT_eFtVh3m0Z72w}{127.0.0.1}{127.0.0.1:46645}{testattr=test} committed version [1]])
[2018-07-23T03:55:26,727][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [elasticsearch[j7cI6y5][management][T#1]], exiting
java.lang.AssertionError
        at org.elasticsearch.common.io.stream.StreamOutput.writeVLong(StreamOutput.java:218) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.index.shard.DocsStats.writeTo(DocsStats.java:77) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.action.admin.indices.stats.CommonStats.writeTo(CommonStats.java:278) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.indices.NodeIndicesStats.writeTo(NodeIndicesStats.java:175) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.action.admin.cluster.node.stats.NodeStats.writeTo(NodeStats.java:235) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.transport.TcpTransport.buildMessage(TcpTransport.java:1056) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.transport.TcpTransport.sendResponse(TcpTransport.java:1005) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.transport.TcpTransportChannel.sendResponse(TcpTransportChannel.java:67) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.transport.TcpTransportChannel.sendResponse(TcpTransportChannel.java:61) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.transport.DelegatingTransportChannel.sendResponse(DelegatingTransportChannel.java:58) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.transport.RequestHandlerRegistry$TransportChannelWrapper.sendResponse(RequestHandlerRegistry.java:111) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:270) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:266) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:206) ~[?:?]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1348) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:527) ~[elasticsearch-5.0.2.jar:5.0.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.0.2.jar:5.0.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by jasontedor** [comment]
This is because of #22317. The way to avoid this in these tests is to disable monitoring collection on older versions that were susceptible to this bug.

**Comment by jasontedor** [comment]
Since this impacts 5.6 and the X-Pack source is in a different non-public repository for this branch, I have opened a PR internally to address.

**Comment by jasontedor** [comment]
Closed by a PR on an internal repository.
