### ISSUE TITLE
[ci] IndicesClusterStateServiceRandomUpdatesTests.testRandomClusterStateUpdates

### ISSUE THREAD

**Issue by andyb-elastic** [elastic/elasticsearch#32308]
Doesn't reproduce. Has occurred 6 times in the last 90 days

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/2576/console

[build-2576.txt](https://github.com/elastic/elasticsearch/files/2221493/build-2576.txt)

```
REPRODUCE WITH: ./gradlew :server:test \
  -Dtests.seed=BDB828B6AFCB1CB3 \
  -Dtests.class=org.elasticsearch.indices.cluster.IndicesClusterStateServiceRandomUpdatesTests \
  -Dtests.method="testRandomClusterStateUpdates" \
  -Dtests.security.manager=true \
  -Dtests.locale=hi-IN \
  -Dtests.timezone=Canada/Mountain
```

```
FAILURE 0.16s J0 | IndicesClusterStateServiceRandomUpdatesTests.testRandomClusterStateUpdates <<< FAILURES!                                                                                  
   > Throwable #1: java.lang.AssertionError: a replica can only be promoted when active. current: [index_ytqkcgwvfrlcilx][0], node[node_002], [R], recovery_source[peer recovery], s[INITIALIZING], a[id=96qpiMtlQ_ODQQrpk67g6g], unassigned_info[[reason=INDEX_CREATED], at[2018-07-23T23:45:43.608Z], delayed=false, allocation_status[no_attempt]] new: [index_ytqkcgwvfrlcilx][0], node[node_002], [P], recovery_source[existing recovery], s[INITIALIZING], a[id=96qpiMtlQ_ODQQrpk67g6g], unassigned_info[[reason=ALLOCATION_FAILED], at[2018-07-23T23:45:43.639Z], failed_attempts[1], delayed=false, details[failed shard on node [node_003]: fake shard failure, failure Exception[null]], allocation_status[no_attempt]]                                                   
   >    at __randomizedtesting.SeedInfo.seed([BDB828B6AFCB1CB3:C53F2165F0F0CAFA]:0)           
   >    at org.elasticsearch.indices.cluster.AbstractIndicesClusterStateServiceTestCase$MockIndexShard.updateShardState(AbstractIndicesClusterStateServiceTestCase.java:365)                 
   >    at org.elasticsearch.indices.cluster.IndicesClusterStateService.updateShard(IndicesClusterStateService.java:582)                                                                     
   >    at org.elasticsearch.indices.cluster.IndicesClusterStateService.createOrUpdateShards(IndicesClusterStateService.java:529)                                                            
   >    at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:230)                                                               
   >    at org.elasticsearch.indices.cluster.IndicesClusterStateServiceRandomUpdatesTests.testRandomClusterStateUpdates(IndicesClusterStateServiceRandomUpdatesTests.java:127)               
   >    at java.lang.Thread.run(Thread.java:748) 
```

**Comment by dnhatn** [comment]
@bleskes is working on the fix.

**Comment by droberts195** [comment]
Another 6.4 failure: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+multijob-unix-compatibility/os=opensuse/6/console
