### ISSUE TITLE
[CI] RangeQueryBuilderTests.testToQuery fails occasionally on 6.x

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#32343]
Saw this locally first, but also found a CI run failing: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/2138/console

This reproduce line in the CI failure unfortunately doesn't reproduce it for me locally:
```
./gradlew :server:test \
  -Dtests.seed=D173DFCE4EA25D4A \
  -Dtests.class=org.elasticsearch.index.query.RangeQueryBuilderTests \
  -Dtests.method="testToQuery" \
  -Dtests.security.manager=true \
  -Dtests.locale=he \
  -Dtests.timezone=IST
```

But I found a seed that does. I think it might be different when running single tests because the problem might be triggered somewhere in the setup:
```
./gradlew :server:test \
  -Dtests.seed=9B1D92FC83143757 \
  -Dtests.class=org.elasticsearch.index.query.RangeQueryBuilderTests
```

Running this fails the test reproducibly for me. Running from my IDE I get:
```
[2018-07-24T15:02:17,101][WARN ][o.e.d.s.ScriptModule     ] Script: returning default values for missing document values is deprecated. Set system property '-Des.scripting.exception_for_missing_value=true' to make behaviour compatible with future major versions.
```
Error in the console output:
```
   > Throwable #1: java.lang.UnsupportedOperationException
   >    at __randomizedtesting.SeedInfo.seed([9B1D92FC83143757:6CE690C2F297F2BD]:0)
   >    at org.elasticsearch.index.query.RangeQueryBuilderTests.doAssertLuceneQuery(RangeQueryBuilderTests.java:236)
   >    at org.elasticsearch.index.query.RangeQueryBuilderTests.doAssertLuceneQuery(RangeQueryBuilderTests.java:60)
   >    at org.elasticsearch.test.AbstractQueryTestCase.assertLuceneQuery(AbstractQueryTestCase.java:516)
   >    at org.elasticsearch.test.AbstractQueryTestCase.testToQuery(AbstractQueryTestCase.java:430)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
```

But the real problem seems to be this:
```
java.lang.AssertionError: unexpected warning headers expected null, but was:<[299 Elasticsearch-6.4.0-SNAPSHOT-Unknown "Script: returning default values for missing document values is deprecated. Set system property '-Des.scripting.exception_for_missing_value=true' to make behaviour compatible with future major versions." "Tue, 24 Jul 2018 19:02:17 GMT"]>
	at __randomizedtesting.SeedInfo.seed([9B1D92FC83143757:6CE690C2F297F2BD]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at org.elasticsearch.test.ESTestCase.ensureNoWarnings(ESTestCase.java:359)
	at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:346)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1713)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:965)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:916)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:802)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:852)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:863)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

Looks like something in the test setup is hitting the ScriptModule ctor in a way that this deprecation warning is logged and screws up the test later.

**Comment by cbuescher** [comment]
This is where the deprecation warning gets logged: https://github.com/elastic/elasticsearch/blob/6.x/server/src/main/java/org/elasticsearch/script/ScriptModule.java#L96

**Comment by jtibshirani** [comment]
I think there are two separate issues here -- the first is a bug I introduced in `RangeQueryBuilderTests` while backporting field aliases. This looks to be the cause of the CI failure, and I'm investigating it now.

I've only seen the script deprecation warning cause failures when running from an IDE, not on CI (or running locally using gradle). I think @mayya-sharipova has been looking into fixing the IDE-related failures.

**Comment by cbuescher** [comment]
@jtibshirani thanks, do you have any idea why the reproduction information in the CI failure itself does not work if the problem indeed was introduced by backporting field aliases? I'm curious why this doesn't work.

**Comment by jtibshirani** [comment]
I'm sorry, I missed that in your above description. I will take a closer look, maybe it's not as simple an issue as I was thinking.

**Comment by mayya-sharipova** [comment]
@cbuescher @jtibshirani  Tests failing on running from IDE  on 6.x is indeed the problem I introduced. As @cbuescher noted, it is indeed because of the deprecation warning in ScriptModule.  We have a tentative solution for it, and I will try to implement it tomorrow.  Sorry for this.

**Comment by dakrone** [comment]
Another failure (if it helps): https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/2142/consoleFull

**Comment by jtibshirani** [comment]
I can reproduce both instances of the error through the gradle reproduce line, if I pretend in the test that the current version is something in `5.x`, like `5.6.0`. The error that was causing the test failure was

```
ERROR   0.95s | RangeQueryBuilderTests.testToQuery <<< FAILURES!
   > Throwable #1: java.lang.UnsupportedOperationException
   >    at __randomizedtesting.SeedInfo.seed([9B44659863E52D55:6CBF67A61266E8BF]:0)
   >    at org.elasticsearch.index.query.RangeQueryBuilderTests.doAssertLuceneQuery(RangeQueryBuilderTests.java:236)
```

This allowed me to narrow in on some faulty logic I introduced in the field-aliases backport, and I pushed a fix in https://github.com/elastic/elasticsearch/commit/2d7c614. With the fix, I was able to successfully run the reproduce commands, and also run the test many times locally (with the older version number set). The problem @mayya-sharipova is looking into should not be causing CI failures, so I think we're good to close out the issue.

One thing that would still be good to dig into (as @cbuescher pointed out above): I'm not sure why the reproduce line only worked when the current version was set to `5.x`, instead of the latest `6.x` release. Is it possible that as part of the build, we're running this suite using an older version?

**Comment by cbuescher** [comment]
> One thing that would still be good to dig into (as @cbuescher pointed out above): I'm not sure why the reproduce lines from jenkins only worked when the current version was set to 5.x, instead of the latest 6.x release. Is it possible that as part of the build, we're running this suite using an older version?

@jtibshirani thanks for pushing the fix, the test failures seem to be gone on 6.x for now. I'll try dig into the weird reproduction behaviour a bit today and will close this issue afterwards (even if I don't find anything for now...)

**Comment by cbuescher** [comment]
I opened #32400 for the reproducibility issue and will close this issue since the failure causing this is fixed.
