### ISSUE TITLE
[CI] Tests failures in server due to MasterNotDiscoveredException on 6.x

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#32358]
Link to build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/2429/console

There are 2 tests failing there in a similar way. I suspect the underlying cause is the same as in both cases I see a `MasterNotDiscoveredException` so I'm grouping them together.

The 2 failures are:

```
ERROR   36.3s J1 | RecoveryFromGatewayIT.testRecoveryDifferentNodeOrderStartup <<< FAILURES!
   > Throwable #1: ElasticsearchException[failed to update minimum master node to [1] (current masters [1])]; nested: MasterNotDiscoveredException;
   > 	at __randomizedtesting.SeedInfo.seed([37172630A243372B:FED2345689CD7C31]:0)
   > 	at org.elasticsearch.test.InternalTestCluster.updateMinMasterNodes(InternalTestCluster.java:1723)
   > 	at org.elasticsearch.test.InternalTestCluster.stopNodesAndClients(InternalTestCluster.java:1392)
   > 	at org.elasticsearch.test.InternalTestCluster.stopNodesAndClient(InternalTestCluster.java:1385)
   > 	at org.elasticsearch.test.InternalTestCluster.stopRandomNode(InternalTestCluster.java:1325)
   > 	at org.elasticsearch.gateway.RecoveryFromGatewayIT.testRecoveryDifferentNodeOrderStartup(RecoveryFromGatewayIT.java:503)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: MasterNotDiscoveredException[null]
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:223)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:317)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:244)
   > 	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:573)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

with reproduce line:

```
./gradlew :server:integTest -Dtests.seed=37172630A243372B -Dtests.class=org.elasticsearch.gateway.RecoveryFromGatewayIT -Dtests.method="testRecoveryDifferentNodeOrderStartup" -Dtests.security.manager=true -Dtests.locale=hr -Dtests.timezone=Etc/GMT-11
```

and:

```
ERROR   70.6s J0 | MasterDisruptionIT.testIsolateMasterAndVerifyClusterStateConsensus <<< FAILURES!
   > Throwable #1: MasterNotDiscoveredException[NodeDisconnectedException[[node_t1][127.0.0.1:30133][cluster:monitor/health] disconnected]]; nested: NodeDisconnectedException[[node_t1][127.0.0.1:30133][cluster:monitor/health] disconnected];
   > 	at __randomizedtesting.SeedInfo.seed([37172630A243372B:84C4296EB852883E]:0)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:223)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:317)
   > 	at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:145)
   > 	at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:117)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.retry(TransportMasterNodeAction.java:208)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.access$500(TransportMasterNodeAction.java:108)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$3.handleException(TransportMasterNodeAction.java:194)
   > 	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1068)
   > 	at org.elasticsearch.transport.TransportService.lambda$onConnectionClosed$8(TransportService.java:928)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   > 	at java.lang.Thread.run(Thread.java:748)
```

with reproduce:

```
./gradlew :server:integTest -Dtests.seed=37172630A243372B -Dtests.class=org.elasticsearch.discovery.MasterDisruptionIT -Dtests.method="testIsolateMasterAndVerifyClusterStateConsensus" -Dtests.security.manager=true -Dtests.locale=ko -Dtests.timezone=Africa/Porto-Novo
```

Cannot reproduce either locally and I could not figure out why the problem occurs.

I'll refrain from disabling the tests just yet until we get some feedback.

**Comment by DaveCTurner** [comment]
I looked into this. `RecoveryFromGatewayIT#testRecoveryDifferentNodeOrderStartup` starts two nodes, one after the other, and then stops them one after the other in the same order. It's the second `stopRandomNode` call that fails, in the process of updating `minimum_master_nodes` (from 1 to 1, a no-op update). The stopping of the first node causes the second node to elect itself as master which, as far as I can tell, happens concurrently with the settings update. The `MasterNotDiscoveredException` exception here is thrown from `TransportMasterNodeAction.AsyncSingleAction.retry` which indicates that something failed during the settings update, causing a retry, but then the retry doesn't fire when the cluster state is updated, and eventually it times out.

I tried sleeping in various positions to try and see if I could find a race here but could not. I will enable some more detailed logging and wait for the next occurrence.

**Comment by ywelsch** [comment]
I've had a quick look at the logs. This is actually duplicates #32552. What's happening is that the current master node is shut down, which results in a cluster state update on the remaining node to elect itself as master. That new master will publish a cluster state update that contains both itself and the node that went down (we only remove the previous master node in a follow-up cluster state update task). The cluster state update task that elects the new master (and still has the two nodes in it) takes more than 30 seconds to be applied on the remaining node, because it tries to reestablish a connection to the shut down node, reflected in the following two log lines:

```
[2018-07-25T20:25:58,431][WARN ][o.e.c.NodeConnectionsService] [node_t1] failed to connect to node {node_t0}{7e7GNnI5ROy2fs_BATut1A}{yD2oWXSOS5SiG2Uwij1qKQ}{127.0.0.1}{127.0.0.1:34419} (tried [1] times)

[2018-07-25T20:25:58,433][WARN ][o.e.c.s.ClusterApplierService] [node_t1] cluster state applier task [apply cluster state (from master [master {node_t1}{gEOhkCThQWW4H0xiigwMGw}{amlOqG1bQDeNdGY50XOV1A}{127.0.0.1}{127.0.0.1:36908} committed version [13] source [zen-disco-elected-as-master ([0] nodes joined)[, ]]])] took [32.9s] above the warn threshold of 30s
```

This results in the queued settings update task to time out.
