### ISSUE TITLE
[CI] RangeFieldMapperTests failed due to unterminated threads

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#32369]
Build link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2401/console

Failure:

```
ERROR   0.00s J1 | RangeFieldMapperTests (suite) <<< FAILURES!
14:49:19    > Throwable #1: com.carrotsearch.randomizedtesting.ThreadLeakError: 2 threads leaked from SUITE scope at org.elasticsearch.index.mapper.RangeFieldMapperTests: 
14:49:19    >    1) Thread[id=1553, name=elasticsearch[node_s_0][__mock_network_thread][T#2], state=RUNNABLE, group=TGRP-RangeFieldMapperTests]
14:49:19    >         at java.net.PlainSocketImpl.socketAccept(Native Method)
14:49:19    >         at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
14:49:19    >         at java.net.ServerSocket.implAccept(ServerSocket.java:545)
14:49:19    >         at java.net.ServerSocket.accept(ServerSocket.java:513)
14:49:19    >         at org.elasticsearch.mocksocket.MockServerSocket.access$101(MockServerSocket.java:32)
14:49:19    >         at org.elasticsearch.mocksocket.MockServerSocket.lambda$accept$0(MockServerSocket.java:53)
14:49:19    >         at org.elasticsearch.mocksocket.MockServerSocket$$Lambda$1737/460128403.run(Unknown Source)
14:49:19    >         at java.security.AccessController.doPrivileged(Native Method)
14:49:19    >         at org.elasticsearch.mocksocket.MockServerSocket.accept(MockServerSocket.java:53)
14:49:19    >         at org.elasticsearch.transport.MockTcpTransport$MockChannel.accept(MockTcpTransport.java:273)
14:49:19    >         at org.elasticsearch.transport.MockTcpTransport$1.doRun(MockTcpTransport.java:128)
14:49:19    >         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
14:49:19    >         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:49:19    >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:49:19    >         at java.lang.Thread.run(Thread.java:748)
14:49:19    >    2) Thread[id=1552, name=elasticsearch[node_s_0][__mock_network_thread][T#1], state=RUNNABLE, group=TGRP-RangeFieldMapperTests]
14:49:19    >         at java.net.PlainSocketImpl.socketAccept(Native Method)
14:49:19    >         at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
14:49:19    >         at java.net.ServerSocket.implAccept(ServerSocket.java:545)
14:49:19    >         at java.net.ServerSocket.accept(ServerSocket.java:513)
14:49:19    >         at org.elasticsearch.mocksocket.MockServerSocket.access$101(MockServerSocket.java:32)
14:49:19    >         at org.elasticsearch.mocksocket.MockServerSocket.lambda$accept$0(MockServerSocket.java:53)
14:49:19    >         at org.elasticsearch.mocksocket.MockServerSocket$$Lambda$1737/460128403.run(Unknown Source)
14:49:19    >         at java.security.AccessController.doPrivileged(Native Method)
14:49:19    >         at org.elasticsearch.mocksocket.MockServerSocket.accept(MockServerSocket.java:53)
14:49:19    >         at org.elasticsearch.transport.MockTcpTransport$MockChannel.accept(MockTcpTransport.java:273)
14:49:19    >         at org.elasticsearch.transport.MockTcpTransport$1.doRun(MockTcpTransport.java:128)
14:49:19    >         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
14:49:19    >         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:49:19    >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:49:19    >         at java.lang.Thread.run(Thread.java:748)
14:49:19    > 	at __randomizedtesting.SeedInfo.seed([52D6EBFEF1E0C47A]:0)Throwable #2: com.carrotsearch.randomizedtesting.ThreadLeakError: There are still zombie threads that couldn't be terminated:
14:49:19    >    1) Thread[id=1553, name=elasticsearch[node_s_0][__mock_network_thread][T#2], state=RUNNABLE, group=TGRP-RangeFieldMapperTests]
14:49:19    >         at java.net.PlainSocketImpl.socketAccept(Native Method)
14:49:19    >         at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
14:49:19    >         at java.net.ServerSocket.implAccept(ServerSocket.java:545)
14:49:19    >         at java.net.ServerSocket.accept(ServerSocket.java:513)
14:49:19    >         at org.elasticsearch.mocksocket.MockServerSocket.access$101(MockServerSocket.java:32)
14:49:19    >         at org.elasticsearch.mocksocket.MockServerSocket.lambda$accept$0(MockServerSocket.java:53)
14:49:19    >         at org.elasticsearch.mocksocket.MockServerSocket$$Lambda$1737/460128403.run(Unknown Source)
14:49:19    >         at java.security.AccessController.doPrivileged(Native Method)
14:49:19    >         at org.elasticsearch.mocksocket.MockServerSocket.accept(MockServerSocket.java:53)
14:49:19    >         at org.elasticsearch.transport.MockTcpTransport$MockChannel.accept(MockTcpTransport.java:273)
14:49:19    >         at org.elasticsearch.transport.MockTcpTransport$1.doRun(MockTcpTransport.java:128)
14:49:19    >         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
14:49:19    >         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:49:19    >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:49:19    >         at java.lang.Thread.run(Thread.java:748)
14:49:19    >    2) Thread[id=1552, name=elasticsearch[node_s_0][__mock_network_thread][T#1], state=RUNNABLE, group=TGRP-RangeFieldMapperTests]
14:49:19    >         at java.net.PlainSocketImpl.socketAccept(Native Method)
14:49:19    >         at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
14:49:19    >         at java.net.ServerSocket.implAccept(ServerSocket.java:545)
14:49:19    >         at java.net.ServerSocket.accept(ServerSocket.java:513)
14:49:19    >         at org.elasticsearch.mocksocket.MockServerSocket.access$101(MockServerSocket.java:32)
14:49:19    >         at org.elasticsearch.mocksocket.MockServerSocket.lambda$accept$0(MockServerSocket.java:53)
14:49:19    >         at org.elasticsearch.mocksocket.MockServerSocket$$Lambda$1737/460128403.run(Unknown Source)
14:49:19    >         at java.security.AccessController.doPrivileged(Native Method)
14:49:19    >         at org.elasticsearch.mocksocket.MockServerSocket.accept(MockServerSocket.java:53)
14:49:19    >         at org.elasticsearch.transport.MockTcpTransport$MockChannel.accept(MockTcpTransport.java:273)
14:49:19    >         at org.elasticsearch.transport.MockTcpTransport$1.doRun(MockTcpTransport.java:128)
14:49:19    >         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
14:49:19    >         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:49:19    >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:49:19    >         at java.lang.Thread.run(Thread.java:748)
14:49:19    > 	at __randomizedtesting.SeedInfo.seed([52D6EBFEF1E0C47A]:0)
14:49:19 Completed [780/1115] on J1 in 28.53s, 11 tests, 2 errors <<< FAILURES!
```

Reproduce with:

```
./gradlew :server:test -Dtests.seed=52D6EBFEF1E0C47A -Dtests.class=org.elasticsearch.index.mapper.RangeFieldMapperTests -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=Etc/UTC
```

Does not reproduce locally for me.

**Comment by colings86** [comment]
I suspect this was either a transient error or a bug in the network layer that was quickly fixed. Searching through the build failure emails I found a lot of these thread leak failures with these same 2 threads referenced (`_mock_netowrk_thread`) on the 25th July 2018 and no more in the 9 days since. I'm going to close this for now but we can reopen if we think my assessment is false. /cc @tbrooks8
