### ISSUE TITLE
[CI] ConvertProcessorTests.testConvertIntHexError occasionally fails

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#32370]
Build link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2403/console

Failure:

```
FAILURE 0.02s J1 | ConvertProcessorTests.testConvertIntHexError <<< FAILURES!
16:12:34    > Throwable #1: junit.framework.AssertionFailedError: Expected exception IllegalArgumentException but no exception was thrown
16:12:34   2> NOTE: Linux 4.4.103-6.38-default amd64/Oracle Corporation 1.8.0_172 (64-bit)/cpus=16,threads=1,free=392839560,total=514850816
16:12:34    > 	at __randomizedtesting.SeedInfo.seed([824DEFADB99C72AC:406271664BE4837E]:0)
16:12:34    > 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2686)
16:12:34    > 	at org.elasticsearch.ingest.common.ConvertProcessorTests.testConvertIntHexError(ConvertProcessorTests.java:75)
16:12:34   2> NOTE: All tests run in this JVM: [SplitProcessorTests, DateProcessorFactoryTests, URLDecodeProcessorTests, GsubProcessorTests, GrokProcessorFactoryTests, LowercaseProcessorTests, SetProcessorTests, ConvertProcessorTests]
16:12:34    > 	at java.lang.Thread.run(Thread.java:748)
16:12:34   1> [2018-07-25T21:12:34,506][INFO ][o.e.i.c.ConvertProcessorTests] [testConvertStringList]: before test
16:12:34   1> [2018-07-25T21:12:34,507][INFO ][o.e.i.c.ConvertProcessorTests] [testConvertStringList]: after test
16:12:34   1> [2018-07-25T21:12:34,510][INFO ][o.e.i.c.ConvertProcessorTests] [testConvertNullField]: before test
16:12:34   1> [2018-07-25T21:12:34,510][INFO ][o.e.i.c.ConvertProcessorTests] [testConvertNullField]: after test
16:12:34   1> [2018-07-25T21:12:34,513][INFO ][o.e.i.c.ConvertProcessorTests] [testAutoConvertDoubleNotMatched]: before test
16:12:34   1> [2018-07-25T21:12:34,514][INFO ][o.e.i.c.ConvertProcessorTests] [testAutoConvertDoubleNotMatched]: after test
16:12:34   1> [2018-07-25T21:12:34,516][INFO ][o.e.i.c.ConvertProcessorTests] [testConvertLongHexError]: before test
16:12:34   1> [2018-07-25T21:12:34,517][INFO ][o.e.i.c.ConvertProcessorTests] [testConvertLongHexError]: after test
16:12:34   1> [2018-07-25T21:12:34,519][INFO ][o.e.i.c.ConvertProcessorTests] [testConvertDoubleError]: before test
16:12:34   1> [2018-07-25T21:12:34,520][INFO ][o.e.i.c.ConvertProcessorTests] [testConvertDoubleError]: after test
16:12:34 Completed [34/48] on J1 in 0.33s, 35 tests, 1 failure <<< FAILURES!
```

Reproduce with:

```
./gradlew :modules:ingest-common:test -Dtests.seed=824DEFADB99C72AC -Dtests.class=org.elasticsearch.ingest.common.ConvertProcessorTests -Dtests.method="testConvertIntHexError" -Dtests.security.manager=true -Dtests.locale=es-PE -Dtests.timezone=PLT
```

Reproduces locally; I will mute the test.

**Comment by javanna** [comment]
another one, it reproduces with the seed 

```
11:33:12 FAILURE 0.03s J1 | ConvertProcessorTests.testConvertLongHexError <<< FAILURES!
11:33:12    > Throwable #1: junit.framework.AssertionFailedError: Expected exception IllegalArgumentException but no exception was thrown
11:33:12    > 	at __randomizedtesting.SeedInfo.seed([B0D2D67F37309C5E:819DA1D648AC73]:0)
11:33:12   2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+master+intake/modules/ingest-common/build/testrun/test/J1/temp/org.elasticsearch.ingest.common.ConvertProcessorTests_B0D2D67F37309C5E-001
11:33:12   2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=1571, maxMBSortInHeap=7.703711302238175, sim=RandomSimilarity(queryNorm=true): {}, locale=lt-LT, timezone=BST
11:33:12   2> NOTE: Linux 4.4.0-1057-aws amd64/Oracle Corporation 1.8.0_172 (64-bit)/cpus=16,threads=1,free=422639816,total=514850816
11:33:12    > 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2687)
11:33:12    > 	at org.elasticsearch.ingest.common.ConvertProcessorTests.testConvertLongHexError(ConvertProcessorTests.java:146)
11:33:12   2> NOTE: All tests run in this JVM: [FailProcessorFactoryTests, GsubProcessorTests, ConvertProcessorTests]
11:33:12    > 	at java.lang.Thread.run(Thread.java:748)
```

```
REPRODUCE WITH: ./gradlew :modules:ingest-common:test -Dtests.seed=B0D2D67F37309C5E -Dtests.class=org.elasticsearch.ingest.common.ConvertProcessorTests -Dtests.method="testConvertLongHexError" -Dtests.security.manager=true -Dtests.locale=lt-LT -Dtests.timezone=BST
```

**Comment by javanna** [comment]
I have muted this test.

**Comment by javanna** [comment]
Sorry about the confusion, we have the same failures for `testConvertIntHexError` and `testConvertLongHexError`. I have muted both tests in master and 6.x.

This one is from 6.x:

```
09:01:45 FAILURE 0.02s J1 | ConvertProcessorTests.testConvertIntHexError <<< FAILURES!
09:01:45    > Throwable #1: junit.framework.AssertionFailedError: Expected exception IllegalArgumentException but no exception was thrown
09:01:45    > 	at __randomizedtesting.SeedInfo.seed([8E27C30076A6948A:4C085DCB84DE6558]:0)
09:01:45    > 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2686)
09:01:45    > 	at org.elasticsearch.ingest.common.ConvertProcessorTests.testConvertIntHexError(ConvertProcessorTests.java:75)
09:01:45    > 	at java.lang.Thread.run(Thread.java:748)
```

```
REPRODUCE WITH: ./gradlew :modules:ingest-common:test -Dtests.seed=8E27C30076A6948A -Dtests.class=org.elasticsearch.ingest.common.ConvertProcessorTests -Dtests.method="testConvertIntHexError" -Dtests.security.manager=true -Dtests.locale=bg-BG -Dtests.timezone=Arctic/Longyearbye
```

**Comment by jasontedor** [comment]
There is a PR for this: #32415

**Comment by javanna** [comment]
Thanks @ywelsch kindly pointed out the same to me, and also the error which is:

```
08:42:18    > Throwable #1: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=3973, name=elasticsearch[node_t2][write][T#1], state=RUNNABLE, group=TGRP-ClusterDisruptionIT]
08:42:18    > 	at __randomizedtesting.SeedInfo.seed([E77D94CFECE59A17:4127A25150EDF080]:0)
08:42:18    > Caused by: java.lang.AssertionError: shard term already update.  op term [2], shardTerm [3]
08:42:18    > 	at __randomizedtesting.SeedInfo.seed([E77D94CFECE59A17]:0)
08:42:18    > 	at org.elasticsearch.index.shard.IndexShard.lambda$acquireReplicaOperationPermit$9(IndexShard.java:2269)
08:42:18    > 	at org.elasticsearch.index.shard.IndexShardOperationPermits.doBlockOperations(IndexShardOperationPermits.java:177)
08:42:18    > 	at org.elasticsearch.index.shard.IndexShardOperationPermits.blockOperations(IndexShardOperationPermits.java:114)
08:42:18    > 	at org.elasticsearch.index.shard.IndexShard.acquireReplicaOperationPermit(IndexShard.java:2268)
08:42:18    > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncReplicaAction.doRun(TransportReplicationAction.java:633)
08:42:18    > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
08:42:18    > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReplicaOperationTransportHandler.messageReceived(TransportReplicationAction.java:510)
08:42:18    > 	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReplicaOperationTransportHandler.messageReceived(TransportReplicationAction.java:490)
08:42:18    > 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
08:42:18    > 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1605)
08:42:18    > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723)
08:42:18    > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
08:42:18    > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
08:42:18    > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
08:42:18    > 	at java.lang.Thread.run(Thread.java:748)
```

Closing, without muting this specific test.
