### ISSUE TITLE
FullClusterRestartIT#testRecovery fails on CI

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#32426]
This may be similar to #31062 but the error looks different and it happens on master, so I went for opening a new issue. I was not able to reproduce this failure.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+default-distro-bwc-tests/210

```
09:24:41 FAILURE 0.12s | FullClusterRestartIT.testRecovery <<< FAILURES!
09:24:41    > Throwable #1: java.lang.AssertionError: expected at least 1 old segment. segments:
09:24:41    > p 0 testrecovery 7.5.0
09:24:41    > p 0 testrecovery 7.5.0
09:24:41    > p 0 testrecovery 7.5.0
09:24:41    > p 0 testrecovery 7.5.0
09:24:41    > p 0 testrecovery 7.5.0
09:24:41    > p 0 testrecovery 7.5.0
09:24:41    > p 0 testrecovery 7.5.0
09:24:41    > p 1 testrecovery 7.5.0
09:24:41    > p 1 testrecovery 7.5.0
09:24:41    > p 1 testrecovery 7.5.0
09:24:41    > p 1 testrecovery 7.5.0
09:24:41    > p 1 testrecovery 7.5.0
09:24:41    > p 1 testrecovery 7.5.0
09:24:41    > p 2 testrecovery 7.5.0
09:24:41    > p 2 testrecovery 7.5.0
09:24:41    > p 2 testrecovery 7.5.0
09:24:41    > p 2 testrecovery 7.5.0
09:24:41    > p 2 testrecovery 7.5.0
09:24:41    > p 2 testrecovery 7.5.0
09:24:41    > p 2 testrecovery 7.5.0
09:24:41    > p 3 testrecovery 7.5.0
09:24:41    > p 3 testrecovery 7.5.0
09:24:41    > p 3 testrecovery 7.5.0
09:24:41    > p 3 testrecovery 7.5.0
09:24:41    > p 3 testrecovery 7.5.0
09:24:41    > p 3 testrecovery 7.5.0
09:24:41    > p 4 testrecovery 7.5.0
09:24:41    > p 4 testrecovery 7.5.0
09:24:41    > p 4 testrecovery 7.5.0
09:24:41    > p 4 testrecovery 7.5.0
09:24:41    > p 4 testrecovery 7.5.0
09:24:41    > p 4 testrecovery 7.5.0
09:24:41    > p 4 testrecovery 7.5.0
09:24:41    > r 0 testrecovery 7.5.0
09:24:41    > r 0 testrecovery 7.5.0
09:24:41    > r 0 testrecovery 7.5.0
09:24:41    > r 0 testrecovery 7.5.0
09:24:41    > r 0 testrecovery 7.5.0
09:24:41    > r 0 testrecovery 7.5.0
09:24:41    > r 0 testrecovery 7.5.0
09:24:41    > r 0 testrecovery 7.5.0
09:24:41    > r 0 testrecovery 7.5.0
09:24:41    > r 0 testrecovery 7.5.0
09:24:41    > r 1 testrecovery 7.5.0
09:24:41    > r 1 testrecovery 7.5.0
09:24:41    > r 1 testrecovery 7.5.0
09:24:41    > r 1 testrecovery 7.5.0
09:24:41    > r 1 testrecovery 7.5.0
09:24:41    > r 1 testrecovery 7.5.0
09:24:41    > r 1 testrecovery 7.5.0
09:24:41    > r 2 testrecovery 7.5.0
09:24:41    > r 2 testrecovery 7.5.0
09:24:41    > r 2 testrecovery 7.5.0
09:24:41    > r 2 testrecovery 7.5.0
09:24:41    > r 2 testrecovery 7.5.0
09:24:41    > r 2 testrecovery 7.5.0
09:24:41    > r 2 testrecovery 7.5.0
09:24:41    > r 2 testrecovery 7.5.0
09:24:41    > r 2 testrecovery 7.5.0
09:24:41    > r 2 testrecovery 7.5.0
09:24:41    > r 3 testrecovery 7.5.0
09:24:41    > r 3 testrecovery 7.5.0
09:24:41    > r 3 testrecovery 7.5.0
09:24:41    > r 3 testrecovery 7.5.0
09:24:41    > r 3 testrecovery 7.5.0
09:24:41    > r 3 testrecovery 7.5.0
09:24:41    > r 3 testrecovery 7.5.0
09:24:41    > r 3 testrecovery 7.5.0
09:24:41    > r 3 testrecovery 7.5.0
09:24:41    > r 4 testrecovery 7.5.0
09:24:41    > r 4 testrecovery 7.5.0
09:24:41    > r 4 testrecovery 7.5.0
09:24:41    > r 4 testrecovery 7.5.0
09:24:41    > r 4 testrecovery 7.5.0
09:24:41    > r 4 testrecovery 7.5.0
09:24:41    > r 4 testrecovery 7.5.0
09:24:41    > . Actual: 0
09:24:41    > 	at __randomizedtesting.SeedInfo.seed([6036560F44CF9AF4:A1C62FA3699F5053]:0)
09:24:41    > 	at org.elasticsearch.upgrades.FullClusterRestartIT.testRecovery(FullClusterRestartIT.java:772)
09:24:41    > 	at java.lang.Thread.run(Thread.java:748)
```

```
REPRODUCE WITH: ./gradlew :qa:full-cluster-restart:v6.5.0-SNAPSHOT#upgradedClusterTestRunner -Dtests.seed=6036560F44CF9AF4 -Dtests.class=org.elasticsearch.upgrades.FullClusterRestartIT -Dtests.method="testRecovery" -Dtests.security.manager=true -Dtests.locale=ar-OM -Dtests.timezone=US/Michigan -Dtests.distribution=zip
```

**Comment by dnhatn** [comment]
This test failed in a short window after we upgraded to Lucene-7.5.0 in 6.x and but had not adjusted that bump in the master. This is fixed in 5decb23687eb19ed1d229c19382897f5010fb5ed.

/cc @jimczi
