### ISSUE TITLE
InternalEngineTests#testSeqNoAndCheckpoints fails on CI

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#32430]
This test has not failed in months, so I assume this is a new problem:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2416

This failure reproduces for me with the seed (although the failure is not consistently the same, I get e.g. Expected: <22L> but: was <113L>):

```
REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=8E5B87EDB16C765A -Dtests.class=org.elasticsearch.index.engine.InternalEngineTests -Dtests.method="testSeqNoAndCheckpoints" -Dtests.security.manager=true -Dtests.locale=et -Dtests.timezone=America/Moncton
```

```
08:40:35 FAILURE 0.10s J3 | InternalEngineTests.testSeqNoAndCheckpoints <<< FAILURES!
08:40:35    > Throwable #1: java.lang.AssertionError: 
08:40:35    > Expected: <22L>
08:40:35    >      but: was <184L>
08:40:35    > 	at __randomizedtesting.SeedInfo.seed([8E5B87EDB16C765A:4C2A82C018830CFE]:0)
08:40:35    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
08:40:35    > 	at org.elasticsearch.index.engine.InternalEngineTests.testSeqNoAndCheckpoints(InternalEngineTests.java:2110)
08:40:35    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dnhatn** [comment]
This test starts failing after we upgraded to Lucene-7.5-snapshot. I am looking at this.
