### ISSUE TITLE
FlushIT#testDoNotRenewSyncedFlushWhenAllSealed fails on CI

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#32436]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/2168/1

This one reproduces for me with the seed on both master and 6.x.

```
16:35:10 FAILURE 0.51s J3 | FlushIT.testDoNotRenewSyncedFlushWhenAllSealed <<< FAILURES!
16:35:10    > Throwable #1: java.lang.AssertionError: 
16:35:10    > Expected: <3>
16:35:10    >      but: was <0>
16:35:10    > 	at __randomizedtesting.SeedInfo.seed([43D9764F86E61665:1EE62FCD108854E7]:0)
16:35:10    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
16:35:10    > 	at org.elasticsearch.indices.flush.FlushIT.testDoNotRenewSyncedFlushWhenAllSealed(FlushIT.java:316)
16:35:10    > 	at java.lang.Thread.run(Thread.java:748)
```

```
16:35:10   2> REPRODUCE WITH: ./gradlew :server:integTest -Dtests.seed=43D9764F86E61665 -Dtests.class=org.elasticsearch.indices.flush.FlushIT -Dtests.method="testDoNotRenewSyncedFlushWhenAllSealed" -Dtests.security.manager=true -Dtests.locale=ru -Dtests.timezone=Europe/Helsinki
```

**Comment by dnhatn** [comment]
This test started failing after we upgraded to Lucene-7.5. I will look at this soon.
