### ISSUE TITLE
[CI] Password verification failed in FIPS mode

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#32486]
Build failure link [FIPS build #209](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8fips,nodes=virtual&&linux/209/console)

Example build failure output:

```
04:26:33 |    org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load plugin class [org.elasticsearch.xpack.core.XPackPlugin]
04:26:33 |    	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
[...]
04:26:33 |    Caused by: org.elasticsearch.ElasticsearchException: failed to initialize a TrustManagerFactory
04:26:33 |    	at org.elasticsearch.xpack.core.ssl.DefaultJDKTrustConfig.createTrustManager(DefaultJDKTrustConfig.java:39) ~[?:?]
[...]
04:26:33 |    Caused by: java.security.KeyStoreException: problem accessing trust store
04:26:33 |    	at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:73) ~[?:?]
04:26:33 |    	at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:278) ~[?:?]
04:26:33 |    	at org.elasticsearch.xpack.core.ssl.CertParsingUtils.trustManager(CertParsingUtils.java:277) ~[?:?]
04:26:33 |    	at org.elasticsearch.xpack.core.ssl.DefaultJDKTrustConfig.createTrustManager(DefaultJDKTrustConfig.java:37) ~[?:?]
[...]
04:26:33 |    Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
04:26:33 |    	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:780) ~[?:?]
[...]
04:26:33 |    Caused by: java.security.UnrecoverableKeyException: Password verification failed
04:26:33 |    	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:778) ~[?:?]
[...]
```

It appears as if the password is not provided although earlier in the startup log we see:

```
04:26:33 |    [2018-07-31T04:12:25,481][INFO ][o.e.n.Node               ] [node-0] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch.kf0Uey9A, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -XX:UseAVX=2, -Dio.netty.allocator.type=unpooled, -Xms512m, -Xmx512m, -Djavax.net.ssl.keyStorePassword=password, -Djavax.net.ssl.trustStorePassword=password, -ea, -esa, -Des.path.home=/var/lib/jenkins/workspace/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA/java11/ES_RUNTIME_JAVA/java8fips/nodes/virtual&&linux/docs/build/cluster/integTestCluster node0/elasticsearch-7.0.0-alpha1-SNAPSHOT, -Des.path.conf=/var/lib/jenkins/workspace/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA/java11/ES_RUNTIME_JAVA/java8fips/nodes/virtual&&linux/docs/build/cluster/integTestCluster node0/elasticsearch-7.0.0-alpha1-SNAPSHOT/config, -Des.distribution.flavor=default, -Des.distribution.type=zip]
```

i.e. `-Djavax.net.ssl.keyStorePassword=password, -Djavax.net.ssl.trustStorePassword=password` are recognized. I could not reproduce this locally as I could not create a proper FIPS JVM installation on my machine.

Further related test failures:

* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java8fips,nodes=virtual&&linux/209/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java8fips,nodes=virtual&&linux/207/console

**Comment by jkakavas** [comment]
This will be addressed by https://github.com/elastic/infra/pull/6219

**Comment by jkakavas** [comment]
Closing this as https://github.com/elastic/infra/pull/6219 is merged
