### ISSUE TITLE
How to solve ：Exception in thread "main" java.nio.file.NoSuchFileException:

### ISSUE THREAD

**Issue by xajhwj** [elastic/elasticsearch#32531]
C:\Users\52526>java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

C:\Users\52526>e:

E:\>cd E:\SotfwareInstall\ElasticSearch\elasticsearch-6.3.2\bin

E:\SotfwareInstall\ElasticSearch\elasticsearch-6.3.2\bin>elasticsearch.bat
Exception in thread "main" java.nio.file.NoSuchFileException: E:\SotfwareInstall\ElasticSearch\6.3.2\config\jvm.options
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:231)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:369)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:415)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.base/java.nio.file.Files.newInputStream(Files.java:154)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:58)

**Comment by ywelsch** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by nsteup** [comment]
E:\elastic\elasticsearch-7.6.1-windows-x86_64_2\elasticsearch-7.6.1\bin>elasticsearch.bat
Exception in thread "main" java.nio.file.NoSuchFileException: D:\elastic\conf\jvm.options
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.base/java.nio.file.Files.newInputStream(Files.java:155)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:64)

**Comment by nsteup** [comment]
i solve it 
maybe you install elasticsearch.msi or other version was run in your system .
check ES_HOME and ES_PATH_CONF in System variables 
set ES_HOME to your easticsearch directory 
set ES_PATH_CONF to easticsearch directory /conf
