### ISSUE TITLE
[CI] o.e.x.r.CoreFullClusterRestartIT fails with security_exception

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#32538]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+bwc-tests/239/console fails as follows:

```
  2> REPRODUCE WITH: ./gradlew :x-pack:qa:full-cluster-restart:with-system-key:v5.2.1#oldClusterTestRunner -Dtests.seed=E86D733EBBB51CB2 -Dtests.class=org.elasticsearch.xpack.restart.CoreFullClusterRestartIT -Dtests.method="testNewReplicasWork" -Dtests.security.manager=true -Dtests.locale=no-NO -Dtests.timezone=America/Paramaribo
   > Throwable #1: org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:39602], URI [/testnewreplicaswork/doc/159], status line [HTTP/1.1 403 Forbidden]
   > {"error":{"root_cause":[{"type":"security_exception","reason":"action [indices:data/write/index[p]] is unauthorized for user [_system]"}],"type":"security_exception","reason":"action [indices:data/write/index[p]] is unauthorized for user [_system]"},"status":403}
   > 	at __randomizedtesting.SeedInfo.seed([E86D733EBBB51CB2:92E98675E3BFF56E]:0)
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+6.3+bwc-tests/x-pack/qa/full-cluster-restart/with-system-key/build/testrun/v5.2.1#oldClusterTestRunner/J0/temp/org.elasticsearch.xpack.restart.CoreFullClusterRestartIT_E86D733EBBB51CB2-001
   > 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:705)
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=456, maxMBSortInHeap=6.312129179504499, sim=RandomSimilarity(queryNorm=true): {}, locale=no-NO, timezone=America/Paramaribo
  2> NOTE: Linux 4.4.103-6.38-default amd64/Oracle Corporation 1.8.0_172 (64-bit)/cpus=16,threads=1,free=427394144,total=514850816
  2> NOTE: All tests run in this JVM: [CoreFullClusterRestartIT]
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198)
   > 	at org.elasticsearch.upgrades.FullClusterRestartIT.indexRandomDocuments(FullClusterRestartIT.java:1032)
   > 	at org.elasticsearch.upgrades.FullClusterRestartIT.testNewReplicasWork(FullClusterRestartIT.java:207)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:39602], URI [/testnewreplicaswork/doc/159], status line [HTTP/1.1 403 Forbidden]
   > {"error":{"root_cause":[{"type":"security_exception","reason":"action [indices:data/write/index[p]] is unauthorized for user [_system]"}],"type":"security_exception","reason":"action [indices:data/write/index[p]] is unauthorized for user [_system]"},"status":403}
   > 	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:377)
   > 	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:366)
   > 	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
   > 	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
   > 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
   > 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
   > 	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
   > 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
   > 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
   > 	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
   > 	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
   > 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
   > 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
   > 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
   > 	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
   > 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
   > 	... 1 more
  1> [2018-08-01T00:20:48,809][INFO ][o.e.x.r.CoreFullClusterRestartIT] [testShrink]: before test
  1> [2018-08-01T00:20:49,003][INFO ][o.e.x.r.CoreFullClusterRestartIT] Indexing 809 random documents
  1> [2018-08-01T00:21:00,104][INFO ][o.e.x.r.CoreFullClusterRestartIT] There are still tasks running after this test that might break subsequent tests [internal:index/shard/recovery/start_recovery].
  1> [2018-08-01T00:21:00,104][INFO ][o.e.x.r.CoreFullClusterRestartIT] [testShrink]: after test
  1> [2018-08-01T00:21:00,111][INFO ][o.e.x.r.CoreFullClusterRestartIT] [testClusterState]: before test
  1> [2018-08-01T00:21:00,277][INFO ][o.e.x.r.CoreFullClusterRestartIT] There are still tasks running after this test that might break subsequent tests [internal:index/shard/recovery/file_chunk, internal:index/shard/recovery/start_recovery].
  1> [2018-08-01T00:21:00,278][INFO ][o.e.x.r.CoreFullClusterRestartIT] [testClusterState]: after test
Completed [1/2] in 54.23s, 11 tests, 1 error, 1 skipped <<< FAILURES!
```

The `REPRODUCE WITH` line does not reproduce this failure. However, I see a few similar failures in the past, including:

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+bwc-tests/49/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+bwc-tests/866/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+bwc-tests/835/console

(also some from internal CI)

It's possible this is related to https://github.com/elastic/elasticsearch/issues/30097, there's not enough information in that to know either way.

The log from the server indicates:

```
[2018-08-01T03:20:48,692][DEBUG][r.suppressed             ] path: /testnewreplicaswork/doc/159, params: {index=testnewreplicaswork, id=159, type=doc}
org.elasticsearch.transport.RemoteTransportException: [node-0][127.0.0.1:41474][indices:data/write/index[p]]
Caused by: org.elasticsearch.ElasticsearchSecurityException: action [indices:data/write/index[p]] is unauthorized for user [_system]
        at org.elasticsearch.xpack.security.support.Exceptions.authorizationError(Exceptions.java:45) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationService.denialException(AuthorizationService.java:420) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationService.denial(AuthorizationService.java:391) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:145) ~[?:?]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$null$2(ServerTransportFilter.java:163) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.maybeRun(AuthorizationUtils.java:127) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.setRunAsRoles(AuthorizationUtils.java:121) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.authorize(AuthorizationUtils.java:102) ~[?:?]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$inbound$3(ServerTransportFilter.java:166) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:56) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$0(AuthenticationService.java:182) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$2(AuthenticationService.java:201) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:213) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:180) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:142) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:114) ~[?:?]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.inbound(ServerTransportFilter.java:142) ~[?:?]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:296) ~[?:?]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1488) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596) ~[elasticsearch-5.2.1.jar:5.2.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.2.1.jar:5.2.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:844) [?:?]
```

What is strange about this is that this is document number 159 that's failing. I'm not sure if that's supposed to be running as the `_system` user.

**Comment by ywelsch** [comment]
duplicates #30565
