### ISSUE TITLE
[CI] WildflyIT failure recommends reproduction with `ant test`

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#32572]
In https://github.com/elastic/elasticsearch/issues/32534 the failure of the `WildflyIT` test recommended:

```
  2> NOTE: reproduce with: ant test  -Dtestcase=WildflyIT -Dtests.seed=E6F2F43820D93CA5 -Dtests.slow=true -Dtests.badapples=true -Dtests.locale=es-VE -Dtests.timezone=Australia/Adelaide -Dtests.asserts=true -Dtests.file.encoding=UTF8
```

I do not seem to have, or need, `ant` installed in order to run this test, so I wonder if this `reproduce with` line harks back to an earlier era and should be updated to an equivalent `./gradlew` line.

**Comment by atorok** [comment]
This change would fix the reproduction line:
```
diff --git a/qa/wildfly/src/test/java/org/elasticsearch/wildfly/WildflyIT.java b/qa/wildfly/src/test/java/org/elasticsearch/wildfly/WildflyIT.java
index 46fafebeb4e..9edff3c61c5 100644
--- a/qa/wildfly/src/test/java/org/elasticsearch/wildfly/WildflyIT.java
+++ b/qa/wildfly/src/test/java/org/elasticsearch/wildfly/WildflyIT.java
@@ -27,7 +27,6 @@ import org.apache.http.entity.StringEntity;
 import org.apache.http.impl.client.CloseableHttpClient;
 import org.apache.http.impl.client.HttpClientBuilder;
 import org.apache.http.util.EntityUtils;
-import org.apache.lucene.util.LuceneTestCase;
 import org.elasticsearch.Build;
 import org.elasticsearch.Version;
 import org.elasticsearch.cluster.ClusterModule;
@@ -37,6 +36,7 @@ import org.elasticsearch.common.xcontent.NamedXContentRegistry;
 import org.elasticsearch.common.xcontent.XContentBuilder;
 import org.elasticsearch.common.xcontent.XContentParser;
 import org.elasticsearch.common.xcontent.json.JsonXContent;
+import org.elasticsearch.test.ESTestCase;
 
 import java.io.IOException;
 import java.net.URI;
@@ -50,7 +50,7 @@ import static org.hamcrest.Matchers.containsInAnyOrder;
 import static org.hamcrest.Matchers.equalTo;
 import static org.hamcrest.Matchers.instanceOf;
 
-public class WildflyIT extends LuceneTestCase {
+public class WildflyIT extends ESTestCase {
 
     public void testTransportClient() throws URISyntaxException, IOException {
         try (CloseableHttpClient client = HttpClientBuilder.create().build()) {
```

But the test fails, probably the reason for not using ESTestCase was to get around security. 

```
> Task :qa:wildfly:integTestRunner
==> Test Info: seed=72E6FC7CE68533DC; jvm=1; suite=1

   > Throwable #1: java.security.AccessControlException: access denied ("java.net.SocketPermission" "127.0.0.1:36531" "connect,resolve")
   > 	at __randomizedtesting.SeedInfo.seed([72E6FC7CE68533DC:1E50B89D76A3FD79]:0)
   > 	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
   > 	at java.base/java.security.AccessController.checkPermission(AccessController.java:895)
   > 	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:335)
   > 	at java.base/java.lang.SecurityManager.checkConnect(SecurityManager.java:837)
   > 	at java.base/java.net.Socket.connect(Socket.java:586)
   > 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
   > 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
   > 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
   > 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
   > 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
   > 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
   > 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
   > 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
   > 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
   > 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
   > 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
   > 	at org.elasticsearch.wildfly.WildflyIT.testTransportClient(WildflyIT.java:83)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   > 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   > 	at java.base/java.lang.Thread.run(Thread.java:844)

```
