### ISSUE TITLE
Unknown license version found after failed upgrade to 6.4.0 staging, rollback to 6.3.2

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch#32571]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.0 MSI built from Staging zip distribution hash 26ea826c

**Plugins installed**: []

**JVM version** (`java -version`):

java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

```powershell
Get-CimInstance Win32_OperatingSystem | Select-Object Caption, Version, ServicePackMajorVersion, OSArchitecture, CSName

Caption                 : Microsoft Windows Server 2012 R2 Standard Evaluation
Version                 : 6.3.9600
ServicePackMajorVersion : 0
OSArchitecture          : 64-bit
CSName                  : VAGRANT-2012-R2
```

**Description of the problem including expected versus actual behavior**:

The Windows Installer integration test scenario `SilentInstall-FailUpgrade` tests the failure scenario when upgrading from one version of Elasticsearch to another, using the MSI Windows Installer. The scenario first installs one version, asserts installation is good, then runs an upgrade to upgrade to a later version, deliberately failing the upgrade at the very end of the upgrade process. It then asserts that Elasticsearch has been successfully rolled back to the prior version, that the prior version Elasticsearch service is installed and that Elasticsearch is operable.

When running this scenario with released MSI 6.3.2 version going to a 6.4.0 MSI built from Staging zip distribution hash 26ea826c, the 6.3.2 Elasticsearch service after the failed upgrade fails to start successfully. Checking the elasticsearch log file, the issue is

```
[2018-08-02T04:57:37,413][ERROR][o.e.g.GatewayMetaState   ] [VAGRANT-2012-R2] failed to read local state, exiting...
org.elasticsearch.ElasticsearchException: java.io.IOException: failed to read [id:23, legacy:false, file:C:\ProgramData\Elastic\Elasticsearch\data\nodes\0\_state\global-23.st]
    at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:199) ~[elasticsearch-6.3.2.jar:6.3.2]
    at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:331) ~[elasticsearch-6.3.2.jar:6.3.2]
    at org.elasticsearch.gateway.MetaStateService.loadGlobalState(MetaStateService.java:112) ~[elasticsearch-6.3.2.jar:6.3.2]
    at org.elasticsearch.gateway.MetaStateService.loadFullState(MetaStateService.java:56) ~[elasticsearch-6.3.2.jar:6.3.2]
    at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:88) [elasticsearch-6.3.2.jar:6.3.2]
    at org.elasticsearch.node.Node.<init>(Node.java:432) [elasticsearch-6.3.2.jar:6.3.2]
    at org.elasticsearch.node.Node.<init>(Node.java:252) [elasticsearch-6.3.2.jar:6.3.2]
    at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) [elasticsearch-6.3.2.jar:6.3.2]
    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) [elasticsearch-6.3.2.jar:6.3.2]
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) [elasticsearch-6.3.2.jar:6.3.2]
    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) [elasticsearch-6.3.2.jar:6.3.2]
    at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) [elasticsearch-6.3.2.jar:6.3.2]
    at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.3.2.jar:6.3.2]
    at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.3.2.jar:6.3.2]
    at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.3.2.jar:6.3.2]
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.3.2.jar:6.3.2]
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) [elasticsearch-6.3.2.jar:6.3.2]
Caused by: java.io.IOException: failed to read [id:23, legacy:false, file:C:\ProgramData\Elastic\Elasticsearch\data\nodes\0\_state\global-23.st]
    at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:325) ~[elasticsearch-6.3.2.jar:6.3.2]
    ... 15 more
Caused by: org.elasticsearch.ElasticsearchException: Unknown license version found, please upgrade all nodes to the latest elasticsearch-license plugin
    at org.elasticsearch.license.License.fromXContent(License.java:482) ~[?:?]
    at org.elasticsearch.license.LicensesMetaData.fromXContent(LicensesMetaData.java:132) ~[?:?]
    at org.elasticsearch.common.xcontent.NamedXContentRegistry$Entry.lambda$new$0(NamedXContentRegistry.java:63) ~[elasticsearch-x-content-6.3.2.jar:6.3.2]
    at org.elasticsearch.common.xcontent.NamedXContentRegistry.parseNamedObject(NamedXContentRegistry.java:141) ~[elasticsearch-x-content-6.3.2.jar:6.3.2]
    at org.elasticsearch.common.xcontent.support.AbstractXContentParser.namedObject(AbstractXContentParser.java:433) ~[elasticsearch-x-content-6.3.2.jar:6.3.2]
    at org.elasticsearch.cluster.metadata.MetaData$Builder.fromXContent(MetaData.java:1177) ~[elasticsearch-6.3.2.jar:6.3.2]
    at org.elasticsearch.cluster.metadata.MetaData$1.fromXContent(MetaData.java:1220) ~[elasticsearch-6.3.2.jar:6.3.2]
    at org.elasticsearch.cluster.metadata.MetaData$1.fromXContent(MetaData.java:1211) ~[elasticsearch-6.3.2.jar:6.3.2]
    at org.elasticsearch.gateway.MetaDataStateFormat.read(MetaDataStateFormat.java:199) ~[elasticsearch-6.3.2.jar:6.3.2]
    at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:320) ~[elasticsearch-6.3.2.jar:6.3.2]
    ... 15 more
```

Specifically,

```
org.elasticsearch.ElasticsearchException: Unknown license version found, please upgrade all nodes to the latest elasticsearch-license plugin
```

The configuration file of 6.3.2 after failed upgrade is

```
bootstrap.memory_lock: false
cluster.name: elasticsearch
http.port: 9200
node.data: true
node.ingest: true
node.master: true
node.max_local_storage_nodes: 1
node.name: VAGRANT-2012-R2
path.data: C:\ProgramData\Elastic\Elasticsearch\data
path.logs: C:\ProgramData\Elastic\Elasticsearch\logs
transport.tcp.port: 9300
xpack.license.self_generated.type: basic
xpack.security.enabled: false
```

Since the integration test deliberatelys fail the upgrade _at the very end of the process_, Elasticsearch 6.4.0 Windows Service will have been installed and started, which may now changed the state of data state.

Would it be expected that 6.3.2 would be able to successfully start after such events? When rolling back from a failed upgrade from 6.3.0 to versions prior to 6.3.x e.g. 6.2.4, I don't recall seeing this issue before.

**Steps to reproduce**:

 1. Clone [`windows-installer` repo](https://github.com/elastic/windows-installers)
 2. Checkout `fix/es-home-fresh-install` branch
 3. Copy 6.4.0 elasticsearch zip distribution from staging build 26ea826c to the `build/in` directory in `windows-installer`
4. Ensure vagrant and virtual box are installed.
5. Ensure access to Windows Vagrant image `elastic/windows-2012_r2-x86_64`
6. Run the following from the root of the repo

    ```
    .\build.bat integrate es r:6.3.2,6.4.0 local *FailUpgrade* skiptests -nodestroy -gui
    ```
7. Observe 7 failing tests related to Elasticsearch service 6.3.2 version failing to start after the failed upgrade is rolled back.

**Comment by ywelsch** [comment]
This test is bogus. Downgrading is and has never been supported, in particular not after the node has been successfully started. While it may work (or just silently mangle stuff in some cases) there is no precedent that this a supported routine.

**Comment by russcam** [comment]
Chatted with @tvernum about this. Since we're effectively testing an unsupported scenario (downgrading to a previous version), I'm going to close this issue.
