### ISSUE TITLE
org.elasticsearch.xpack.qa.sql.nosecurity.JdbcSqlSpecIT Fails on Upper and lower casing functions

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#32589]
Build URL:
```
http://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=amazon/2595
```

Reproduce commands:
```
./gradlew :x-pack:qa:sql:no-security:integTestRunner \
  -Dtests.seed=5870E6CDF96A6756 \
  -Dtests.class=org.elasticsearch.xpack.qa.sql.nosecurity.JdbcSqlSpecIT \
  -Dtests.method="test {string-functions.testUpperCasingTheSecondLetterFromTheRightFromFirstName}" \
  -Dtests.security.manager=true \
  -Dtests.locale=tr \
  -Dtests.timezone=America/Dawson

./gradlew :x-pack:qa:sql:no-security:integTestRunner \
  -Dtests.seed=5870E6CDF96A6756 \
  -Dtests.class=org.elasticsearch.xpack.qa.sql.nosecurity.JdbcSqlSpecIT \
  -Dtests.method="test {string-functions.testSelectInsertWithLcaseAndLengthWithOrderBy}" \
  -Dtests.security.manager=true \
  -Dtests.locale=tr \
  -Dtests.timezone=America/Dawson

./gradlew :x-pack:qa:sql:no-security:integTestRunner \
  -Dtests.seed=5870E6CDF96A6756 \
  -Dtests.class=org.elasticsearch.xpack.qa.sql.nosecurity.JdbcSqlSpecIT \
  -Dtests.method="test {string-functions.testUpperCasingTheSecondLetterFromTheRightFromFirstNameWithOrderByAndGroupBy}" \
  -Dtests.security.manager=true \
  -Dtests.locale=tr \
  -Dtests.timezone=America/Dawson
```

Errors looks to be expecting diacritics on the output but not finding them and instead finding a normalised character. e.g.:
```
14:46:33 FAILURE 0.08s | JdbcSqlSpecIT.test {string-functions.testUpperCasingTheSecondLetterFromTheRightFromFirstName} <<< FAILURES!
14:46:33    > Throwable #1: org.junit.ComparisonFailure: Different result for column [f], entry [2] expected:<Ala[İ]n> but was:<Ala[I]n>
14:46:33    > 	at __randomizedtesting.SeedInfo.seed([5870E6CDF96A6756:D024D91757960AAE]:0)
14:46:33    > 	at org.elasticsearch.xpack.qa.sql.nosecurity.JdbcSqlSpecIT.string-functions.testUpperCasingTheSecondLetterFromTheRightFromFirstName(string-functions.sql-spec:145)
14:46:33    > 	at org.elasticsearch.xpack.qa.sql.jdbc.JdbcAssert.doAssertResultSetData(JdbcAssert.java:199)
14:46:33    > 	at org.elasticsearch.xpack.qa.sql.jdbc.JdbcAssert.assertResultSetData(JdbcAssert.java:133)
14:46:33    > 	at org.elasticsearch.xpack.qa.sql.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:58)
14:46:33    > 	at org.elasticsearch.xpack.qa.sql.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:45)
14:46:33    > 	at org.elasticsearch.xpack.qa.sql.jdbc.SpecBaseIntegrationTestCase.assertResults(SpecBaseIntegrationTestCase.java:123)
14:46:33    > 	at org.elasticsearch.xpack.qa.sql.jdbc.SqlSpecTestCase.doTest(SqlSpecTestCase.java:66)
14:46:33    > 	at org.elasticsearch.xpack.qa.sql.jdbc.SpecBaseIntegrationTestCase.test(SpecBaseIntegrationTestCase.java:88)
14:46:33    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by colings86** [comment]
Muted these tests on master in https://github.com/elastic/elasticsearch/commit/4cdbb425425e9a8f3280bcf72430ab03d4bce461

**Comment by dakrone** [comment]
Another instance of this on 6.x: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+release-tests/921/console

I backported Colin's mute to the 6.x branch

**Comment by astefan** [comment]
Thanks @dakrone. PR coming in: https://github.com/elastic/elasticsearch/pull/32604

**Comment by dnhatn** [comment]
@astefan I am reopening this because it still fails with Locale `az-Cyrl-AZ`. I think we need to add to `az-Cyrl-AZ` to the ignored locale list.

CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/236/console

**Comment by astefan** [comment]
@dnhatn thanks. I'm looking into it.
