### ISSUE TITLE
unable to load JNA native support library, native methods will be disabled.

### ISSUE THREAD

**Issue by mayurvenkat** [elastic/elasticsearch#32600]
**Describe the feature**:

**Elasticsearch version**
 (Version: 5.6.3, Build: 1a2f265/2017-10-06T20:33:39.012Z, JVM: 1.8.0_162):

**Plugins installed**: [No]

**JVM version** (java version "1.6.0_121"):

**OS version** (SunOS 5.10 Generic_150400-40 sun4v sparc sun4v):

**Description of the problem including expected versus actual behavior**:
When i try to run Elasticsearch i get this error

unable to load JNA native support library, native methods will be disabled

**Provide logs (if relevant)**:
[2018-08-02T12:37:24,218][WARN ][o.e.b.Natives            ] unable to load JNA native support library, native methods will be disabled.
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/sunos-sparcv9/libjnidispatch.so) not found in resource path 

([file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/snakeyaml-1.15.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/lucene-highlighter-6.6.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/spatial4j-0.6.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/lucene-misc-6.6.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/log4j-core-2.9.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/lucene-analyzers-common-6.6.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/lucene-suggest-6.6.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/lucene-join-6.6.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/lucene-sandbox-6.6.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/jna-4.4.0-1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/jackson-core-2.8.6.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/lucene-queries-6.6.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/lucene-grouping-6.6.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/lucene-backward-codecs-6.6.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/log4j-api-2.9.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/lucene-memory-6.6.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/jackson-dataformat-yaml-2.8.6.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/hppc-0.7.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/jackson-dataformat-cbor-2.8.6.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/lucene-spatial-6.6.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/jts-1.13.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/plugin-cli-5.6.3.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/jackson-dataformat-smile-2.8.6.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/jopt-simple-5.0.2.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/joda-time-2.9.5.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/lucene-spatial-extras-6.6.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/t-digest-3.0.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/elasticsearch-5.6.3.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/HdrHistogram-2.1.9.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/log4j-1.2-api-2.9.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/lucene-queryparser-6.6.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/lucene-spatial3d-6.6.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/lucene-core-6.6.1.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/java-version-checker-5.6.3.jar, file:/opt_local/mspcrm/TactiX/elasticsearch-5.6.3_master/lib/securesm-1.1.jar])
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:962) ~[jna-4.4.0-1.jar:4.4.0 (b0)]
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922) ~[jna-4.4.0-1.jar:4.4.0 (b0)]
        at com.sun.jna.Native.<clinit>(Native.java:190) ~[jna-4.4.0-1.jar:4.4.0 (b0)]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_162]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_162]
        at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:45) [elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:105) [elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:195) [elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) [elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) [elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) [elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) [elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) [elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) [elasticsearch-5.6.3.jar:5.6.3]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) [elasticsearch-5.6.3.jar:5.6.3]

**Comment by tvernum** [comment]
We do not [support running on Solaris](https://www.elastic.co/support/matrix#matrix_os), and only ship with JNA support for operating systems that we do support.

You will need to run Elasticsearch on a supported OS.
