### ISSUE TITLE
java client  error: java.lang.ClassNotFoundException: org.elasticsearch.script.ScriptEngine

### ISSUE THREAD

**Issue by Crab2died** [elastic/elasticsearch#32736]
1. elasticsearch version 6.3.2
2. java client version
```
<dependency>
    <groupId>org.elasticsearch.client</groupId>
    <artifactId>transport</artifactId>
    <version>6.3.2</version>
</dependency>
```
3. error
````
java.lang.NoClassDefFoundError: org/elasticsearch/script/ScriptEngine

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:427)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:104)
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:104)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:129)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:268)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:128)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:114)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:104)
	at com.github.crab2died.ElasticClientTests.initClient(ElasticClientTests.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.script.ScriptEngine
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more
````

**Comment by vladimirdolzhenko** [comment]
@Crab2died I see that [transport-6.3.2.pom](http://central.maven.org/maven2/org/elasticsearch/client/transport/6.3.2/transport-6.3.2.pom) has dependency on 
```
<dependency>
  <groupId>org.elasticsearch</groupId> 
  <artifactId>elasticsearch</artifactId>
  <version>6.3.2</version>
  <scope>compile</scope>
</dependency>
```
it contains `org.elasticsearch.script.ScriptEngine` - most probably transitive dependencies don't work for you - it could be shaded by some other problems within your pom-file. 

you can check dependencies with `mvn dependency:tree -Dverbose`

**Comment by rjernst** [comment]
Please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports.
