### ISSUE TITLE
.watcher-history-7 template not setting the correct field limit

### ISSUE THREAD

**Issue by danielkasen** [elastic/elasticsearch#32919]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.3.2

The watch history template doesn't set the field limit high enough:

```{
  ".watch-history-7": {
    "order": 2147483647,
    "index_patterns": [
      ".watcher-history-7*"
    ],
    "settings": {
      "index": {
        "format": "6",
        "number_of_shards": "1",
        "auto_expand_replicas": "0-1",
        "number_of_replicas": "0"
      }
    },```

So when the index gets created and things attempt to be placed into the index you get an ERROR

``` [i-0a4118fbd2e37211a] failed to update watch record [OWWYBIn3RvCZi-zfIMzSdQ_kibana_version_mismatch_735cbadc-ddd5-404a-bb4f-08208dd0b414-2018-08-16T18:40:55.048Z]
java.lang.IllegalArgumentException: Limit of total fields [1000] in index [.watcher-history-7-2018.08.16] has been exceeded
	at org.elasticsearch.index.mapper.MapperService.checkTotalFieldsLimit(MapperService.java:630) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:463) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:356) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:288) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:313) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:630) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:267) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:197) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:132) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:626) [elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) ~[elasticsearch-6.3.2.jar:6.3.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]```

**Comment by spinscale** [comment]
can you share the output of 

```
GET .watcher-history-7-2018.08.16/_mapping
```

in a gist? Would like to know what is causing this - by default we are far away from that limit. My only explanation would be that you have a lot of metadata, but let's take a look first and then continue with assumptions.

**Comment by danielkasen** [comment]
[mapping.txt](https://github.com/elastic/elasticsearch/files/2298000/mapping.txt)

Hopefully this works :)

**Comment by spinscale** [comment]
the mapping does not look excessive and not near the 1k limit.

Does this happen when you only run the internal watches or did you add any watches yourself?

**Comment by danielkasen** [comment]
We have custom watches.

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
