### ISSUE TITLE
[CI] DateTimeUnitTests.testConversion fails with unknown time zone ID HST

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#32927]
```
Suite: org.elasticsearch.common.rounding.DateTimeUnitTests
  1> [2018-08-16T14:47:51,594][INFO ][o.e.c.r.DateTimeUnitTests] [testConversion] before test
  1> [2018-08-16T14:47:51,742][INFO ][o.e.c.r.DateTimeUnitTests] [testConversion] after test
  2> REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=5AB2A395D4041BDE -Dtests.class=org.elasticsearch.common.rounding.DateTimeUnitTests -Dtests.method="testConversion" -Dtests.security.manager=true -Dtests.locale=es-DO -Dtests.timezone=PNT -Dcompiler.java=10 -Druntime.java=8
ERROR   0.20s | DateTimeUnitTests.testConversion <<< FAILURES!
   > Throwable #1: java.time.zone.ZoneRulesException: Unknown time-zone ID: HST
   > 	at __randomizedtesting.SeedInfo.seed([5AB2A395D4041BDE:5CBA26AFF9CB444A]:0)
   > 	at java.time.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:272)
   > 	at java.time.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:227)
   > 	at java.time.ZoneRegion.ofId(ZoneRegion.java:120)
   > 	at java.time.ZoneId.of(ZoneId.java:411)
   > 	at java.time.ZoneId.of(ZoneId.java:359)
   > 	at org.elasticsearch.common.rounding.DateTimeUnitTests.testConversion(DateTimeUnitTests.java:72)
   > 	at java.lang.Thread.run(Thread.java:748)
  2> NOTE: leaving temporary files on disk at: /home/hinmanm/es/elasticsearch/server/build/testrun/test/J0/temp/org.elasticsearch.common.rounding.DateTimeUnitTests_5AB2A395D4041BDE-001
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=1404, maxMBSortInHeap=6.233009351798742, sim=RandomSimilarity(queryNorm=false): {}, locale=es-DO, timezone=PNT
  2> NOTE: Linux 4.17.14-202.fc28.x86_64 amd64/Oracle Corporation 1.8.0_161 (64-bit)/cpus=8,threads=1,free=415073840,total=514850816
  2> NOTE: All tests run in this JVM: [DateTimeUnitTests]
Completed [1/1] in 1.15s, 1 test, 1 error <<< FAILURES!
```

This reproduced for me on master with:

```
./gradlew :server:test -Dtests.seed=5AB2A395D4041BDE -Dtests.class=org.elasticsearch.common.rounding.DateTimeUnitTests -Dtests.method="testConversion" -Dtests.security.manager=true -Dtests.locale=es-DO -Dtests.timezone=PNT -Dcompiler.java=10 -Druntime.java=8
```

**Comment by spinscale** [comment]
closed by https://github.com/elastic/elasticsearch/commit/0d92f377fd3ecc9c6336f4770fc92951368a2aec
