### ISSUE TITLE
SQL: ArrayIndexOutOfBoundsException: 0 when selecting wildcard and nested wildcard fields

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#32951]
For the following mapping:

```
    "mappings" : {
      "test" : {
        "properties" : {
          "simple" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "simple_nested" : {
            "type" : "nested",
            "properties" : {
              "field2" : {
                "type" : "text",
                "fields" : {
                  "keyword" : {
                    "type" : "keyword",
                    "ignore_above" : 256
                  }
                }
              }
            }
          }
        }
      }
    }
```

and test data `{"simple_nested":{"field2":"text5"},"simple":"text4"}` the following exception is thrown when running `SELECT simple_nested.*, simple FROM test2`:

```
Server error [Server encountered an error [0]. [java.lang.ArrayIndexOutOfBoundsException: 0
        at org.elasticsearch.xpack.sql.execution.search.SearchHitRowSet.getColumn(SearchHitRowSet.java:111)
        at org.elasticsearch.xpack.sql.session.AbstractRowSet.column(AbstractRowSet.java:18)
        at org.elasticsearch.xpack.sql.session.RowView.forEachColumn(RowView.java:38)
        at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.lambda$createResponse$2(TransportSqlQueryAction.java:91)
        at org.elasticsearch.xpack.sql.session.RowSet.forEachRow(RowSet.java:32)
        at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.createResponse(TransportSqlQueryAction.java:89)
        at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.createResponse(TransportSqlQueryAction.java:84)
        at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.lambda$operation$0(TransportSqlQueryAction.java:66)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.xpack.sql.execution.search.Querier$ScrollActionListener.lambda$handleResponse$0(Querier.java:328)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.lambda$clear$3(Querier.java:432)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:66)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:62)
        at org.elasticsearch.action.search.ClearScrollController.onFreedContext(ClearScrollController.java:130)
        at org.elasticsearch.action.search.ClearScrollController.lambda$cleanScrollIds$2(ClearScrollController.java:115)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:46)
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1088)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1164)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1154)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1143)
        at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:54)
        at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$1(SearchTransportService.java:316)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63)
        at org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:689)
        at org.elasticsearch.transport.TransportService.access$000(TransportService.java:76)
        at org.elasticsearch.transport.TransportService$3.sendRequest(TransportService.java:134)
        at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:635)
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:554)
        at org.elasticsearch.action.search.SearchTransportService.sendFreeContext(SearchTransportService.java:110)
        at org.elasticsearch.action.search.ClearScrollController.lambda$cleanScrollIds$4(ClearScrollController.java:114)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.action.search.SearchScrollAsyncAction.collectNodesAndRun(SearchScrollAsyncAction.java:129)
        at org.elasticsearch.action.search.ClearScrollController.cleanScrollIds(ClearScrollController.java:105)
        at org.elasticsearch.action.search.ClearScrollController.lambda$new$1(ClearScrollController.java:71)
        at org.elasticsearch.action.search.ClearScrollController.run(ClearScrollController.java:80)
        at org.elasticsearch.action.search.TransportClearScrollAction.doExecute(TransportClearScrollAction.java:49)
        at org.elasticsearch.action.search.TransportClearScrollAction.doExecute(TransportClearScrollAction.java:31)
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:143)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:119)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:62)
        at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83)
        at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:400)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:70)
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.clear(Querier.java:430)
        at org.elasticsearch.xpack.sql.execution.search.Querier$ScrollActionListener.handleResponse(Querier.java:327)
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.onResponse(Querier.java:405)
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.onResponse(Querier.java:381)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:66)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:62)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onResponse(AbstractSearchAsyncAction.java:313)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onResponse(AbstractSearchAsyncAction.java:50)
        at org.elasticsearch.action.search.FetchSearchPhase$3.run(FetchSearchPhase.java:212)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:160)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:153)
        at org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:119)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:160)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:153)
        at org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:205)
        at org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$2(FetchSearchPhase.java:104)
        at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:110)
        at org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:44)
        at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:86)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by lemonostif** [comment]
To add some details to this, with a little search I found [this](https://www.elastic.co/blog/an-introduction-to-elasticsearch-sql-with-practical-examples-part-2) blog post that proves that this is an acceptable use case. Looking at the org.elasticsearch.xpack.sql.execution.search.SearchHitRowSet class, I think that the way the constructor sets up the innerHint property needs a second thought, since it just grabs the value from the last column (propably pressuming it is a nested one?). Consequently, a workaround for the above problem is to reorder the columns in the select clause, leaving the nested one in the end as follows: SELECT simple, simple_nested.* FROM test2

**Comment by astefan** [comment]
Master: https://github.com/elastic/elasticsearch/commit/253152172c8ba1a17884ef4c19de128d4653242d
6.x (6.6.0): https://github.com/elastic/elasticsearch/commit/0fc5b2a7be5fae0c09ba3515f769e4cf63d55628
6.5 (6.5.1): https://github.com/elastic/elasticsearch/commit/3f95d4c6b611b8562f2db6594edb0916a833346c
