### ISSUE TITLE
Elasticsearch installed with RPM fails to restart after yum update

### ISSUE THREAD

**Issue by bpri** [elastic/elasticsearch#32961]
Bug report

**Elasticsearch version** (`bin/elasticsearch --version`): 
Version: 6.3.2, Build: default/rpm/053779d/2018-07-20T05:20:23.451332Z, JVM: 1.8.0_181

**Plugins installed**: [ingest-user-agent, ingest-geoip]

**JVM version** (`java -version`):
1.8.0_181

**OS version** (`uname -a` if on a Unix-like system):
RHEL 7.5

**Description of the problem including expected versus actual behavior**:
elasticsearch fails to restart after yum update due to incompatible plugins.    Please include a rpm postinstall script to update plugins to same version as rpm installed Elasticsearch version, so that if a separate operations team yum updates the VMs, elasticsearch will come back after reboot.

**Steps to reproduce**:
 1. install elasticsearch repo in /etc/yum.repos.d
 2. install Elasticsearch via RPM package (in this case latest was 6.2.4 when installed): yum install elasticsearch
 3. install plugins required for filebeat-apache2: sudo bin/elasticsearch-plugin install  ingest-user-agent
 4. after update to Elasticsearch (in this case 6.3.2) :  'yum update' VM to get latest RPM package
 5. when elasticsearch tries to restart it fails with incompatible plugins

**Provide logs (if relevant)**:
[2018-08-17T13:09:02,941][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.IllegalArgumentException: Plugin [ingest-user-agent] was built for Elasticsearch version 6.2.4 but version 6.3.2 is running
        at org.elasticsearch.plugins.PluginsService.verifyCompatibility(PluginsService.java:421) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:618) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:557) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:162) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.node.Node.<init>(Node.java:311) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) [elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) [elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) [elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.3.2.jar:6.3.2]
        at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.3.2.jar:6.3.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) [elasticsearch-6.3.2.jar:6.3.2]

**Comment by rjernst** [comment]
Plugins can come from anywhere, including the local filesystem, and their source is not tracked by Elasticsearch. So we do not have the information necessary to upgrade them (nor would this work in the non-packaged case of zip/tar). The need to manually upgrade plugins is mentioned in [upgrade documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html) (see step 6). Since there is nothing we can do about this, I'm going to close this issue.
