### ISSUE TITLE
UpdateRequest.fromXContent or JsonXContentParser.nextToken loop forever resulting  http_server_worker thread too busy to accept any connections. 

### ISSUE THREAD

**Issue by wuyunfeng** [elastic/elasticsearch#33010]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):5.5.0

**Plugins installed**: []

**JVM version** (`java -version`):1.8

**OS version** (`uname -a` if on a Unix-like system):Linux es-node-1 3.10.0-693.21.1.el7.x86_64, 6core, 30G memory

**Description of the problem including expected versus actual behavior**:  curl -XGET http://localhost:8200 stuck until reset by peer exception

**Steps to reproduce**:
 we start Elasticseaerch cluster with 4 nodes, we run some update API in this cluster：

```
index/type/{ID}/_update" -d '{"doc":{"f1":"xxx","f2":"xxx"},"doc_as_upsert":true}',
```
after insert some document, we stop update relevant index, we do not perform any operation on the cluster,
but we find the cpu usage reached to 100%,  run the `ss -an | grep 8200`command line below, we find:

![image](https://user-images.githubusercontent.com/5183061/44382797-03d0a080-a549-11e8-91d1-151682f8b1c4.png)

we print the jstack for those node with 100% cpu usage, find:

![image](https://user-images.githubusercontent.com/5183061/44382967-97a26c80-a549-11e8-8caa-f6c63f348b4c.png)

about 6 http_server_work thread running forever(6 core)

`I guess may be some extreme scenario trigger the Elasticsearch internal bug resulting in the http server work running forever even ignore the tcp accept queue(in other words,  the server was too busy to invoke tcp accept new connection), the LISTEN state TCP RECV-Q exceeds the max_some_conn resulting in reject any connection from client.`

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. we can not reproduce this scenario, we just reserver only one node having this problem, the other nodes we restart and this may not happen 

**Provide logs (if relevant)**:

the elasitcsearch process have no logs to print, we just invoke `jstack` on the stack and running the `netstat apn | grep 8200` or `ss -an | grep 8200`,

I wonder weather this is a elasticsearch internal bug which may triggered in extreme scenario,
the `http_server_work` stacktrace below:
elasticsearch[UYc-RX2][http_server_worker][T#10]" #154 daemon prio=5 os_prio=0 tid=0x00007f6344044000 nid=0x81c5 runnable [
0x00007f62f19ef000]
   java.lang.Thread.State: RUNNABLE
        at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:55)
        at org.elasticsearch.action.update.UpdateRequest.fromXContent(UpdateRequest.java:788)
        at org.elasticsearch.rest.action.document.RestUpdateAction.lambda$prepareRequest$0(RestUpdateAction.java:90)
        at org.elasticsearch.rest.action.document.RestUpdateAction$$Lambda$1728/1931072261.accept(Unknown Source)
        at org.elasticsearch.rest.RestRequest.applyContentParser(RestRequest.java:361)
        at org.elasticsearch.rest.action.document.RestUpdateAction.prepareRequest(RestUpdateAction.java:89)
        at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:64)
        at com.baidu.elasticsearch.BaiduPackPlugin.lambda$null$0(BaiduPackPlugin.java:79)
        at com.baidu.elasticsearch.BaiduPackPlugin$$Lambda$1580/409439411.handleRequest(Unknown Source)
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:262)
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:200)
        at org.elasticsearch.http.netty4.Netty4HttpServerTransport.dispatchRequest(Netty4HttpServerTransport.java:505)
        at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:72)
"elasticsearch[UYc-RX2][http_server_worker][T#12]" #171 daemon prio=5 os_prio=0 tid=0x00007f6344048800 nid=0x81ee runnable [
0x00007f62f19ae000]
   java.lang.Thread.State: RUNNABLE
        at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:55)
        at org.elasticsearch.action.update.UpdateRequest.fromXContent(UpdateRequest.java:788)
        at org.elasticsearch.rest.action.document.RestUpdateAction.lambda$prepareRequest$0(RestUpdateAction.java:90)
        at org.elasticsearch.rest.action.document.RestUpdateAction$$Lambda$1728/1931072261.accept(Unknown Source)
        at org.elasticsearch.rest.RestRequest.applyContentParser(RestRequest.java:361)
        at org.elasticsearch.rest.action.document.RestUpdateAction.prepareRequest(RestUpdateAction.java:89)
        at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:64)
        at com.baidu.elasticsearch.BaiduPackPlugin.lambda$null$0(BaiduPackPlugin.java:79)
        at com.baidu.elasticsearch.BaiduPackPlugin$$Lambda$1580/409439411.handleRequest(Unknown Source)
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:262)
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:200)
        at org.elasticsearch.http.netty4.Netty4HttpServerTransport.dispatchRequest(Netty4HttpServerTransport.java:505)
        at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:72)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at org.elasticsearch.http.netty4.pipelining.HttpPipeliningHandler.channelRead(HttpPipeliningHandler.java:63)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)

**Comment by wuyunfeng** [comment]
Netty4HttpServerTransport at module netty4, set the parent and child EventLoopGroup with one:
            serverBootstrap = new ServerBootstrap();
            serverBootstrap.group(new NioEventLoopGroup(workerCount, daemonThreadFactory(settings,
                HTTP_SERVER_WORKER_THREAD_NAME_PREFIX)));
this setting will result in the ServerSocketChannel acceptor run in the http_server_worker#1 thread, maybe the http_server_worker#1 can do lots of SocketChannel read/write IO，JSON Parsing etc，if JSON Parse enter dead loop such as depicted above,  Http Server would not accept any connections .  
  Why set the parent and child group using the same group and the `acceptor` thread just one only?  any other reason?

**Comment by wuyunfeng** [comment]
@elastic/es-core-infra

**Comment by dakrone** [comment]
I think this is pretty stale and the internals of how networking works in ES has changed quite a bit since when this was opened. For now I'm going to close this, but if you still see this on later versions ES (7.x) please let us know and we can re-open it.
