### ISSUE TITLE
Disabling xpack in version 6.3

### ISSUE THREAD

**Issue by csandanov** [elastic/elasticsearch#33014]
**Elasticsearch version** (`bin/elasticsearch --version`): 
```
Version: 6.3.2, Build: default/tar/053779d/2018-07-20T05:20:23.451332Z, JVM: 1.8.0_171
```

**JVM version** (`java -version`): 
```
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (IcedTea 3.8.0) (Alpine 8.171.11-r0)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system): Alpine Linux 3.8

**Description of the problem including expected versus actual behavior**:

I maintain [alpine-based elasticseach image](https://github.com/wodby/elasticsearch) and since the version 6.3 I got the following error during the start:

```
[WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [92243bbf-6c74-4700-b6dc-0d2043fcaf25] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: org.elasticsearch.bootstrap.BootstrapException: java.io.IOException: Cannot run program "/usr/share/elasticsearch/modules/x-pack/x-pack-ml/platform/linux-x86_64/bin/controller": error=2, No such file or directory
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.3.2.jar:6.3.2]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.3.2.jar:6.3.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.3.2.jar:6.3.2]
Caused by: org.elasticsearch.bootstrap.BootstrapException: java.io.IOException: Cannot run program "/usr/share/elasticsearch/modules/x-pack/x-pack-ml/platform/linux-x86_64/bin/controller": error=2, No such file or directory
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:168) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.3.2.jar:6.3.2]
	... 6 more
Caused by: java.io.IOException: Cannot run program "/usr/share/elasticsearch/modules/x-pack/x-pack-ml/platform/linux-x86_64/bin/controller": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[?:1.8.0_171]
	at org.elasticsearch.bootstrap.Spawner.spawnNativeController(Spawner.java:118) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.bootstrap.Spawner.spawnNativeControllers(Spawner.java:86) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:166) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.3.2.jar:6.3.2]
	... 6 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method) ~[?:1.8.0_171]
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247) ~[?:1.8.0_171]
	at java.lang.ProcessImpl.start(ProcessImpl.java:134) ~[?:1.8.0_171]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[?:1.8.0_171]
	at org.elasticsearch.bootstrap.Spawner.spawnNativeController(Spawner.java:118) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.bootstrap.Spawner.spawnNativeControllers(Spawner.java:86) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:166) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.3.2.jar:6.3.2]
	... 6 more
```

I found [this post](https://discuss.elastic.co/t/elasticsearch-failing-to-start-due-to-x-pack/85125/6) on discuss.elastic.co saying that ML does not work on Alpine and can be disabled by adding `xpack.ml.enabled: false` in `elasticsearch.yml`. However that did not help and I had to entirely remove `/usr/share/elasticsearch/modules/x-pack` (in 6.2 there was no such directory), this helped but I wonder is this a correct way to disable x-pack? Is x-pack no longer a plugin and comes pre-built?

**Comment by tvernum** [comment]
> Is x-pack no longer a plugin and comes pre-built?

As of 6.3, the default distribution of Elasticsearch automatically includes X-Pack.
You can also install a "OSS" version of Elasticsearch that does not include X-Pack - see https://www.elastic.co/downloads/elasticsearch-oss

Note though, that we explicitly don't support Alpine Linux (due to issues with musl libc), so it's possible that a future release of Elasticseach-OSS might also break on Alpine (we simply don't test it, so we wouldn't necessarily know that something had broken).

**Comment by davidkyle** [comment]
Hi @csandanov,

Github is used for feature requests, bug reports and submitting PRs. The discuss forum you linked to is the best place to ask these kind of questions. 

I'm closing issue, as @tvernum said you can use OSS elasticsearch if you don't wish to use x-pack otherwise please ask the question in the [x-pack forum](https://discuss.elastic.co/c/x-pack)

**Comment by csandanov** [comment]
@tvernum thanks

btw, the musl issue that was originally reported has been fixed a while ago https://github.com/elastic/elasticsearch-docker/issues/76#issuecomment-410942407
