### ISSUE TITLE
[CI] GraphExploreResponseTests.testFromXContent fails

### ISSUE THREAD

**Issue by vladimirdolzhenko** [elastic/elasticsearch#33086]
```
Suite: org.elasticsearch.protocol.xpack.graph.GraphExploreResponseTests
  1> [2018-08-23T05:01:44,073][INFO ][o.e.p.x.g.GraphExploreResponseTests] [testFromXContentWithFailures] before test
  1> [2018-08-23T05:01:45,305][INFO ][o.e.p.x.g.GraphExploreResponseTests] [testFromXContentWithFailures] after test
  1> [2018-08-23T05:01:45,310][INFO ][o.e.p.x.g.GraphExploreResponseTests] [testFromXContent] before test
  1> [2018-08-23T05:01:45,525][INFO ][o.e.p.x.g.GraphExploreResponseTests] [testFromXContent] after test
  2> REPRODUCE WITH: ./gradlew :x-pack:protocol:test -Dtests.seed=280221F02AE6E6DA -Dtests.class=org.elasticsearch.protocol.xpack.graph.GraphExploreResponseTests -Dtests.method="testFromXContent" -Dtests.security.manager=true -Dtests.locale=fr-BE -Dtests.timezone=America/Rio_Branco -Dcompiler.java=10 -Druntime.java=8
FAILURE 0.24s J2 | GraphExploreResponseTests.testFromXContent <<< FAILURES!
   > Throwable #1: arrays first differed at element [29]; expected:<org.elasticsearch.protocol.xpack.graph.Connection@75d26158> but was:<org.elasticsearch.protocol.xpack.graph.Connection@5a3a5b58>
   > 	at __randomizedtesting.SeedInfo.seed([280221F02AE6E6DA:96A14E8A3410600]:0)
   > 	at org.elasticsearch.protocol.xpack.graph.GraphExploreResponseTests.assertEqualInstances(GraphExploreResponseTests.java:102)
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+6.x+periodic/x-pack/protocol/build/testrun/test/J2/temp/org.elasticsearch.protocol.xpack.graph.GraphExploreResponseTests_280221F02AE6E6DA-001
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=1761, maxMBSortInHeap=7.7452117757666, sim=RandomSimilarity(queryNorm=false): {}, locale=fr-BE, timezone=America/Rio_Branco
  2> NOTE: Linux 3.10.0-862.3.2.el7.x86_64 amd64/Oracle Corporation 1.8.0_181 (64-bit)/cpus=16,threads=1,free=418005096,total=514850816
  2> NOTE: All tests run in this JVM: [OpenJobResponseTests, InfluencerTests, CategorizationAnalyzerConfigTests, PutWatchResponseTests, BucketInfluencerTests, GraphExploreResponseTests]
   > 	at org.elasticsearch.protocol.xpack.graph.GraphExploreResponseTests.assertEqualInstances(GraphExploreResponseTests.java:37)
   > 	at org.elasticsearch.test.AbstractXContentTestCase.testFromXContent(AbstractXContentTestCase.java:61)
   > 	at org.elasticsearch.test.AbstractXContentTestCase.testFromXContent(AbstractXContentTestCase.java:76)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.lang.AssertionError: expected:<org.elasticsearch.protocol.xpack.graph.Connection@75d26158> but was:<org.elasticsearch.protocol.xpack.graph.Connection@5a3a5b58>
   > 	... 44 more
Completed [23/47] on J2 in 1.51s, 2 tests, 1 failure <<< FAILURES!
```

logs: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/2602/console

the result of https://github.com/elastic/elasticsearch/pull/33025

it is fully reproducible locally in `6.x` branch with
```
./gradlew :x-pack:protocol:test -Dtests.seed=280221F02AE6E6DA -Dtests.class=org.elasticsearch.protocol.xpack.graph.GraphExploreResponseTests -Dtests.method="testFromXContent" -Dtests.security.manager=true -Dtests.locale=fr-BE -Dtests.timezone=America/Rio_Branco -Dcompiler.java=10 -Druntime.java=8
```

**Comment by markharwood** [comment]
Fixed in 6.x 6a92a3555c48d4a7a77b1e457657f61c08e104ee and master f860e589a629bd89f24f022a50c8a2fcb7a77673

**Comment by vladimirdolzhenko** [comment]
thanks @markharwood
