### ISSUE TITLE
[CI] org.elasticsearch.xpack.core.scheduler.SchedulerEngineTests.testListenersThrowingExceptionsDoNotCauseOtherListenersToBeSkipped failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#33124]
This reproduced for me locally in 5 out of 100 iterations. My failed tests' seeds:

```
org.elasticsearch.xpack.core.scheduler.SchedulerEngineTests.testListenersThrowingExceptionsDoNotCauseOtherListenersToBeSkipped { seed=[AF9B118B1B6BF07F:C6A368EB43605FF9]}
org.elasticsearch.xpack.core.scheduler.SchedulerEngineTests.testListenersThrowingExceptionsDoNotCauseOtherListenersToBeSkipped { seed=[AF9B118B1B6BF07F:4BDB8DDBA0A127C5]}
org.elasticsearch.xpack.core.scheduler.SchedulerEngineTests.testListenersThrowingExceptionsDoNotCauseOtherListenersToBeSkipped { seed=[AF9B118B1B6BF07F:264696D95DC37ED8]}
org.elasticsearch.xpack.core.scheduler.SchedulerEngineTests.testListenersThrowingExceptionsDoNotCauseOtherListenersToBeSkipped { seed=[AF9B118B1B6BF07F:4D657BEF6DF4387B]}
org.elasticsearch.xpack.core.scheduler.SchedulerEngineTests.testListenersThrowingExceptionsDoNotCauseOtherListenersToBeSkipped { seed=[AF9B118B1B6BF07F:B9187963AB208801]}
```

```
gradlew :x-pack:plugin:core:test -Dtests.seed=AF9B118B1B6BF07F -Dtests.class=org.elasticsearch.xpack.core.scheduler.SchedulerEngineTests -Dtests.method="testListenersThrowingExceptionsDoNotCauseOtherListenersToBeSkipped" -Dtests.security.manager=true -Dtests.locale=no -Dtests.timezone=Etc/GMT+6 -Dcompiler.java=10 -Druntime.java=8
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2587/console

```
15:09:24     > 	at __randomizedtesting.SeedInfo.seed([AF9B118B1B6BF07F:DFEED126D92DE366]:0)
15:09:24     > 	at org.elasticsearch.xpack.core.scheduler.SchedulerEngineTests.assertFailedListenerLogMessage(SchedulerEngineTests.java:147)
15:09:24     > 	at org.elasticsearch.xpack.core.scheduler.SchedulerEngineTests.testListenersThrowingExceptionsDoNotCauseOtherListenersToBeSkipped(SchedulerEngineTests.java:88)
15:09:24     > 	at java.lang.Thread.run(Thread.java:748)
```

The test class involved in the failure was added 3 days ago in [this commit](https://github.com/elastic/elasticsearch/commit/ad0a965db9af15c49618a2f65c847ad4bbae1547).

@jasontedor can you have a look at this failure?

**Comment by jasontedor** [comment]
Closed by 9fddf7e6a3ce13597d21c61d9818e301016b7b03
