### ISSUE TITLE
[CI] org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT termvectors/50_nested/Termvectors on nested fields should return empty results

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#33134]
This failed multiple times in the last 24 hours, it seems to have started failing after this commit: https://github.com/elastic/elasticsearch/commit/8f16696fe12bd406327b0f715f513a33c642ec37
I reproduced this locally only once, when I ran the entire suite, as below. But I wasn't able to reproduce this constantly (even with the entire suite).

```
gradlew :qa:mixed-cluster:v6.5.0-SNAPSHOT#mixedClusterTestRunner -Dtests.seed=A4E6BD58E9C9DC1C -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT -Dtests.security.manager=true -Dtests.locale=ar -Dtests.timezone=Asia/Beirut -Dcompiler.java=10 -Druntime.java=8
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian/2629/console

Part of the stacktrace:
```
01:18:37    1> [2018-08-24T01:17:06,796][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] [p0=termvectors/50_nested/Termvectors on nested fields should return empty results] after test
01:18:37  FAILURE 0.27s | MixedClusterClientYamlTestSuiteIT.test {p0=termvectors/50_nested/Termvectors on nested fields should return empty results} <<< FAILURES!
01:18:37     > Throwable #1: java.lang.AssertionError: Failure at [termvectors/50_nested:46]: field [term_vectors.nested1\.nested1-text] has a true value but it shouldn't
01:18:37     > Expected: ("" or equalToIgnoringCase("false") or "0")
01:18:37     >      but: was "{field_statistics={sum_doc_freq=1, doc_count=1, sum_ttf=1}, terms={text1={term_freq=1, tokens=[{position=0, start_offset=0, end_offset=5}]}}}"
01:18:37     > 	at __randomizedtesting.SeedInfo.seed([A4E6BD58E9C9DC1C:2CB282824735B1E4]:0)
01:18:37     > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:383)
01:18:37     > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:360)
01:18:37     > 	at java.lang.Thread.run(Thread.java:748)
01:18:37     > Caused by: java.lang.AssertionError: field [term_vectors.nested1\.nested1-text] has a true value but it shouldn't
01:18:37     > Expected: ("" or equalToIgnoringCase("false") or "0")
01:18:37     >      but: was "{field_statistics={sum_doc_freq=1, doc_count=1, sum_ttf=1}, terms={text1={term_freq=1, tokens=[{position=0, start_offset=0, end_offset=5}]}}}"
01:18:37     > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
01:18:37     > 	at org.elasticsearch.test.rest.yaml.section.IsFalseAssertion.doAssert(IsFalseAssertion.java:59)
01:18:37     > 	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
01:18:37     > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:376)
01:18:37     > 	... 37 more
01:18:37    1> [2018-08-24T01:17:06,804][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] [p0=indices.delete_alias/all_path_options/check delete with blank index and blank alias] before test
```

**Comment by astefan** [comment]
No longer applicable. [This commit](https://github.com/elastic/elasticsearch/commit/6f1ee76443c4d04095bce2c34a8cb474c5854e4a) reverted a previous one that added the faulty test.
