### ISSUE TITLE
java.lang.IllegalStateException: Message not fully read (response) for requestId [4504014635], handler 

### ISSUE THREAD

**Issue by weizijun** [elastic/elasticsearch#33151]
Describe the feature:

Elasticsearch version (bin/elasticsearch --version):
2.3.3

Plugins installed: []
delete-by-query
license
marvel-agent

JVM version (java -version):
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

OS version (uname -a if on a Unix-like system):
2.6.32-573.18.1.el6.toav2.x86_64 #1 SMP Sun Jul 17 12:44:29 CST 2016 x86_64 x86_64 x86_64 GNU/Linux

Description of the problem including expected versus actual behavior:
master sometime appear this exception:Message not fully read (response) for requestId [4504014635], handler.
this will cause datanode reconnect master.when primary\slave shard's datanode reconnect successively,this will cause data loss.

Provide logs (if relevant):
[2018-08-25 12:45:40,337][WARN ][transport.netty          ] [xxx] exception caught on transport layer [[id: 0xed06abb3, /xxx(master ip):26945 => /xxx(datanode ip):9301]], closing connection
java.lang.IllegalStateException: Message not fully read (response) for requestId [4504014635], handler [org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction$1@213f95a3], error [false]; resetting
        at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:146)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2018-08-25 12:45:40,338][DEBUG][cluster.service          ] [xxx] processing [zen-disco-node_failed({
DiscoveryNodes.toString()}), reason transport disconnected]: execute

**Comment by jasontedor** [comment]
Heya, sorry to hear that you’re having trouble. Though for us 2.3.3 is end-of-life and we no longer support it. If you can reproduce this issue on a supported version we would take a look.
