### ISSUE TITLE
[CI] GraphExplorer.testFromXContentWithFailures fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#33231]
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=fedora/1258/console

This reproduces locally for me with:
```
./gradlew :x-pack:plugin:core:test \
  -Dtests.seed=D6E662ED87F0B085 \
  -Dtests.class=org.elasticsearch.protocol.xpack.graph.GraphExploreResponseTests \
  -Dtests.method="testFromXContentWithFailures" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-EC \
  -Dtests.timezone=America/Santiago \
  -Dcompiler.java=10 \
  -Druntime.java=8
```

Error:
```
FAILURE 1.61s | GraphExploreResponseTests.testFromXContentWithFailures <<< FAILURES!
   > Throwable #1: arrays first differed at element [90]; expected:<field1:wmDMD> but was:<field1:xGHbA>
   >    at __randomizedtesting.SeedInfo.seed([D6E662ED87F0B085:96929E5D4A35B194]:0)
   >    at org.elasticsearch.protocol.xpack.graph.GraphExploreResponseTests.assertEqualInstances(GraphExploreResponseTests.java:98)
   >    at org.elasticsearch.test.AbstractXContentTestCase.testFromXContent(AbstractXContentTestCase.java:61)
   >    at org.elasticsearch.protocol.xpack.graph.GraphExploreResponseTests.testFromXContentWithFailures(GraphExploreResponseTests.java:118)
   >    at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.lang.AssertionError: expected:<field1:wmDMD> but was:<field1:xGHbA>
   >    ... 43 more
```

Looks quite similar to #33086 which should be fixed on 6.x. and master, this is another test method though. @markharwood Do you immediately see what is wrong here, since you already fixed a very similar looking issue? Otherwise I could also take a look at it.

**Comment by markharwood** [comment]
In follow up tests porting this fix I discovered another variant with seed 57C56B8D4FCC8802 
- this seed randomises the "connections" array as opposed to the "vertices" array.
I added "connections" to the list of fields that shouldn't be randomised in 6.x and master
