### ISSUE TITLE
[CI] Several failures in LicensingTests

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#33249]
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java10,nodes=virtual&&linux/268/console

No local reproduction possible so far:
```
REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=7387056134887B36 \
  -Dtests.class=org.elasticsearch.license.LicensingTests \
  -Dtests.method="testEnableDisableBehaviour" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-DK \
  -Dtests.timezone=Europe/Nicosia \
  -Dcompiler.java=11 \
  -Druntime.java=10

REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=7387056134887B36 \
  -Dtests.class=org.elasticsearch.license.LicensingTests \
  -Dtests.method="testEnableDisableBehaviour" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-DK \
  -Dtests.timezone=Europe/Nicosia \
  -Dcompiler.java=11 \
  -Druntime.java=10

REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=7387056134887B36 \
  -Dtests.class=org.elasticsearch.license.LicensingTests \
  -Dtests.method="testNodeJoinWithoutSecurityExplicitlyEnabled" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-DK \
  -Dtests.timezone=Europe/Nicosia \
  -Dcompiler.java=11 \
  -Druntime.java=10

REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=7387056134887B36 \
  -Dtests.class=org.elasticsearch.license.LicensingTests \
  -Dtests.method="testNodeJoinWithoutSecurityExplicitlyEnabled" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-DK \
  -Dtests.timezone=Europe/Nicosia \
  -Dcompiler.java=11 \
  -Druntime.java=10

REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=7387056134887B36 \
  -Dtests.class=org.elasticsearch.license.LicensingTests \
  -Dtests.method="testSecurityActionsByLicenseType" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-DK \
  -Dtests.timezone=Europe/Nicosia \
  -Dcompiler.java=11 \
  -Druntime.java=10

REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=7387056134887B36 \
  -Dtests.class=org.elasticsearch.license.LicensingTests \
  -Dtests.method="testSecurityActionsByLicenseType" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-DK \
  -Dtests.timezone=Europe/Nicosia \
  -Dcompiler.java=11 \
  -Druntime.java=10
```

There are NoNodeAvailableExceptions in the log like this
```
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{u-pdTjagT32wM2-SiWN_tw}{127.0.0.1}{127.0.0.1:30480}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:349)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:247)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:57)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:381)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:388)
	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:65)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:388)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:377)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:45)
	at org.elasticsearch.test.ESIntegTestCase.index(ESIntegTestCase.java:1284)
	at org.elasticsearch.license.LicensingTests.testEnableDisableBehaviour(LicensingTests.java:154)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at 
```

But there are also Warnings like this about missing master nodes:
```
19:24:27   1> [2018-08-29T20:24:17,131][WARN ][o.e.t.d.TestZenDiscovery ] [node_s1] not enough master nodes (has [1], but needed [2]), current nodes: nodes: 
19:24:27   1>    {node_s1}{E7lCWxY3ShOidywR3fs0RQ}{5ne4jBqbS4-Tb-hmwpLTrQ}{127.0.0.1}{127.0.0.1:30480}{xpack.installed=true}, local, master
19:24:27   1>    {node_s0}{JANOf3tyRq6awWUkD2pajw}{J-27NZVhS0GygKaQUfcdAA}{127.0.0.1}{127.0.0.1:30479}{xpack.installed=true}
19:24:27   1>    {node_sc2}{EH8xlnDsTQas9XOQeEv47A}{2yx3d8LCRi2eUGuyzjbPuA}{127.0.0.1}{127.0.0.1:30481}{xpack.installed=true}
```

So I suspect something is also wrong in cluster formation.

**Comment by dnhatn** [comment]
Another instance: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/2375/console

**Comment by jaymode** [comment]
This has not reproduced recently and the relevant logs are gone so I am going to close this for now.
