### ISSUE TITLE
[Build] Gradle 5.0 deprecation: should not remove tasks 

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#33343]
Gradle deprecated removing a task if it's added as a dependency. 
```
Do not remove a Task instance from a task dependency set when it contains a Provider to the Task instance. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0.
	at org.gradle.api.internal.tasks.DefaultTaskDependency$TaskDependencySet.remove(DefaultTaskDependency.java:245)
	at java_util_Set$remove$0.call(Unknown Source)
	at com.carrotsearch.gradle.junit4.RandomizedTestingPlugin.replaceTestTask(RandomizedTestingPlugin.groovy:98)
	at com.carrotsearch.gradle.junit4.RandomizedTestingPlugin$replaceTestTask$0.callStatic(Unknown Source)
	at com.carrotsearch.gradle.junit4.RandomizedTestingPlugin.apply(RandomizedTestingPlugin.groovy:22)
	at com.carrotsearch.gradle.junit4.RandomizedTestingPlugin.apply(RandomizedTestingPlugin.groovy)
[...]
```

"Provider to the Task instance" is part of the delayed task ( a.k.a lazy task ) improvements added in 4.8, documented and refined in 4.9, and in this case it's not something we can control as the initial `test` task is represented as a provider, we have no control to change that, we also don't have control to prevent adding it as a dependency. 

This will effectively prevent us from replacing the `test` task in Gradle 5.0.
Some options that come to mind:
 - disable `test` and create a new `randomizedTest` task instead 
 - use the Gradle test runner. This will require us to configure the security manager as described in #31496.  We will not have randomization of class order unless gradle/gradle#5760 is addressed . We will still have randomization of method order. 
 - we can probably start hacking around it, like excluding all tests and adding a task action to run the randomized testing ant runner, but we don't want to go there.

**Comment by atorok** [comment]
Relates to #31496
