### ISSUE TITLE
[CI] CCR - testValidateFollowingIndexSettings fails

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#33379]
I have not looked into the failure. I open this issue so that we can mute the test.

CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=sles/2651/console

Log: [validate_follow_setting.txt.zip](https://github.com/elastic/elasticsearch/files/2348569/validate_follow_setting.txt.zip)

Reproduce command:

```
./gradlew :x-pack:plugin:ccr:internalClusterTest \
  -Dtests.seed=7E4E234E7384C59F \
  -Dtests.class=org.elasticsearch.xpack.ccr.ShardChangesIT \
  -Dtests.method="testValidateFollowingIndexSettings" \
  -Dtests.security.manager=true \
  -Dtests.locale=id \
  -Dtests.timezone=Australia/Lindeman \
  -Dcompiler.java=10 \
  -Druntime.java=8
```

**Comment by martijnvg** [comment]
I think the reason that this test failed is because not all leader shard copies were ready and the test does not wait for all leader shard copies to be ready before executing the follow api.

```
 2.29s J1 | ShardChangesIT.testValidateFollowingIndexSettings <<< FAILURES!
   > Throwable #1: java.lang.IllegalArgumentException: Not all copies of follow shard are started
   >    at org.elasticsearch.xpack.ccr.action.ShardFollowTasksExecutor.validate(ShardFollowTasksExecutor.java:77)
   >    at org.elasticsearch.xpack.ccr.action.ShardFollowTasksExecutor.validate(ShardFollowTasksExecutor.java:53)
   >    at org.elasticsearch.persistent.PersistentTasksClusterService$1.execute(PersistentTasksClusterService.java:77)
   >    at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
   >    at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:639)
   >    at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:268)
   >    at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198)
   >    at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133)
   >    at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
   >    at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
   >    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624)
   >    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
   >    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
   >    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   >    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

**Comment by martijnvg** [comment]
This test no longer exists.
