### ISSUE TITLE
[CI] ShardFollowTaskReplicationTests#testSimpleCcrReplication

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#33493]
```
2> REPRODUCE WITH: ./gradlew :x-pack:plugin:ccr:test -Dtests.seed=B68A5D5B439E7327 -Dtests.class=org.elasticsearch.xpack.ccr.action.ShardFollowTaskReplicationTests -Dtests.method="testSimpleCcrReplication" -Dtests.security.manager=true -Dtests.locale=ar-IQ -Dtests.timezone=America/Blanc-Sablon -Dcompiler.java=10 -Druntime.java=8
01:03:39 Suite: org.elasticsearch.xpack.ccr.action.ShardFollowTaskReplicationTests
01:03:39   1> [2018-09-06T21:03:25,510][INFO ][o.e.x.c.a.ShardFollowTaskReplicationTests] [testSimpleCcrReplication] before test
01:03:39   1> [2018-09-06T21:03:28,243][INFO ][o.e.x.c.a.ShardFollowNodeTask] [testSimpleCcrReplication] [follow_index][0] Started to follow leader shard [leader_index][0], followGlobalCheckPoint=-1, mappingVersion=1
01:03:39   1> [2018-09-06T21:03:38,751][INFO ][o.e.x.c.a.ShardFollowTaskReplicationTests] [testSimpleCcrReplication] after test
01:03:39 FAILURE 13.4s J3 | ShardFollowTaskReplicationTests.testSimpleCcrReplication <<< FAILURES!
01:03:39    > Throwable #1: java.lang.AssertionError: 
01:03:39    > Expected: <90L>
01:03:39    >      but: was <52L>
01:03:39    > 	at __randomizedtesting.SeedInfo.seed([B68A5D5B439E7327:47C7CC420EE021C5]:0)
01:03:39    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
01:03:39    > 	at org.elasticsearch.xpack.ccr.action.ShardFollowTaskReplicationTests.lambda$testSimpleCcrReplication$1(ShardFollowTaskReplicationTests.java:81)
01:03:39    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:848)
01:03:39    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:822)
01:03:39   2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-unix-compatibility/os/fedora/x-
```
I'm unable to reproduce.

Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=fedora/2657/console

**Comment by bleskes** [comment]
@martijnvg I presume you are still looking at this? I'm assigning it to you but please feel free to correct it if I'm wrong.

**Comment by martijnvg** [comment]
yes, I’m.

**Comment by dnhatn** [comment]
The build log is gone. I am closing this and reopen if it fails again.
