### ISSUE TITLE
x-pack: Elasticsearch 6.4.0 version x-pack may use part 6.3.2 version code

### ISSUE THREAD

**Issue by Simolx** [elastic/elasticsearch#33547]
**Elasticsearch version** (`bin/elasticsearch --version`):
`Version: 6.4.0, Build: default/tar/595516e/2018-08-17T23:18:47.308994Z, JVM: 1.8.0_181`
**Plugins installed**: []

**JVM version** (`java -version`):
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```
**OS version** (`uname -a` if on a Unix-like system):
`Linux Simon 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
**Description of the problem including expected versus actual behavior**:
I download elasticsearch-6.4.0.tar.gz from https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.0.tar.gz, and get source from https://github.com/elastic/elasticsearch.git. Then I build some modules in x-pack from source code with tag v6.4.0 and replace the jar in `$ES_HOME/modules`. When I start elasticsearch with command `${ES_HOME}/bin/elasticsearch`, I get the exception:
```
[2018-09-09T14:04:31,772][INFO ][o.e.d.DiscoveryModule    ] [node-dev] using discovery type [single-node]
[2018-09-09T14:04:31,818][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-dev] fatal error in thread [main], exiting
java.lang.NoSuchMethodError: org.elasticsearch.xpack.core.scheduler.SchedulerEngine.<init>(Ljava/time/Clock;)V
        at org.elasticsearch.xpack.rollup.Rollup.getPersistentTasksExecutor(Rollup.java:197) ~[?:?]
        at org.elasticsearch.node.Node.lambda$new$12(Node.java:489) ~[elasticsearch-6.4.0.jar:6.4.0]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_181]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_181]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_181]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_181]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_181]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_181]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_181]
        at org.elasticsearch.node.Node.<init>(Node.java:491) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.node.Node.<init>(Node.java:256) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.4.0.jar:6.4.0]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.4.0.jar:6.4.0]
```
Then I check the file `modules/x-pack-rollup/x-pack-rollup-6.4.0.jar` extracted from elasticsearch-6.4.0.tar.gz, I found this code in class `org.elasticsearch.xpack.rollup.Rollup`:
```java
    public List<PersistentTasksExecutor<?>> getPersistentTasksExecutor(ClusterService clusterService, ThreadPool threadPool, Client client) {
        if (this.enabled && !this.transportClientMode) {
            SchedulerEngine schedulerEngine = new SchedulerEngine(this.getClock());
            return Collections.singletonList(new RollupJobPersistentTasksExecutor(this.settings, client, schedulerEngine, threadPool));
        } else {
            return Collections.emptyList();
        }
    }
```
This is the x-pack 6.3.2 code. For x-pack 6.4.0, the correct may be:
```java
    @Override
    public List<PersistentTasksExecutor<?>> getPersistentTasksExecutor(ClusterService clusterService,
                                                                       ThreadPool threadPool, Client client) {
        if (enabled == false || transportClientMode ) {
            return emptyList();
        }

        SchedulerEngine schedulerEngine = new SchedulerEngine(settings, getClock());
        return Collections.singletonList(new RollupJobTask.RollupJobPersistentTasksExecutor(settings, client, schedulerEngine, threadPool));
``` 
While I don't confirm if there are other x-pack modules in version 6.4.0 that use version 6.3.2.

**Comment by jasontedor** [comment]
The v6.4.0 tag in the repository is wrong, it is not pointing to the commit used for the 6.4.0 release. Currently it is pointing to 1a122904dd29df3f8692310437fd37267706d84b yet it should be 595516e45d054483dcdaf12f0468a59cb34bb568.

I can imagine this having cost you precious time, I am so sorry that you were led astray by this. We will take steps in our release process to ensure that a mistake like this does not happen again.

Download 6.4.0:

```
08:45:54 1d [jason@totoro:~] $ cd /tmp
08:49:37 1d [jason@totoro:/tmp] $ mkdir -p elasticsearch/6.4.0
08:49:51 1d [jason@totoro:/tmp] $ cd elasticsearch/6.4.0/
08:49:54 1d [jason@totoro:/tmp/elasticsearch/6.4.0] $ curl -L https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.0.tar.gz | tar zx --strip-components=1 -C .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 93.3M  100 93.3M    0     0  19.0M      0  0:00:04  0:00:04 --:--:-- 27.6M
08:50:47 1d [jason@totoro:/tmp/elasticsearch/6.4.0] $ cd modules/x-pack-rollup/
```

Extract the rollup JAR:

```
08:51:11 1d [jason@totoro:/tmp/elasticsearch/6.4.0/modules/x-pack-rollup] $ mkdir jar
08:51:18 1d [jason@totoro:/tmp/elasticsearch/6.4.0/modules/x-pack-rollup] $ cp x-pack-rollup-6.4.0.jar jar
08:51:21 1d [jason@totoro:/tmp/elasticsearch/6.4.0/modules/x-pack-rollup] $ cd jar
08:51:22 1d [jason@totoro:/tmp/elasticsearch/6.4.0/modules/x-pack-rollup/jar] $ jar xf x-pack-rollup-6.4.0.jar 
bash: jar: command not found...
08:51:29 1d [jason@totoro:/tmp/elasticsearch/6.4.0/modules/x-pack-rollup/jar] 127 $ /opt/java/jdk-10/bin/jar xf x-pack-rollup-6.4.0.jar 
```

Check the manifest:

```
08:51:38 1d [jason@totoro:/tmp/elasticsearch/6.4.0/modules/x-pack-rollup/jar] $ cat META-INF/MANIFEST.MF 
Manifest-Version: 1.0
Implementation-Title: org.elasticsearch.plugin#rollup;6.4.0
Implementation-Version: 6.4.0
Built-Status: integration
Built-By: vagrant
Built-OS: Linux
Build-Date: 2018-08-17T23:23:09.084479Z
Gradle-Version: 4.9
Created-By: 10+46 (Oracle Corporation)
Build-Java-Version: 1.10
Module-Source: /x-pack/plugin/rollup
Module-Origin: git@github.com:elastic/elasticsearch.git
Change: 595516e
Branch: 595516e45d054483dcdaf12f0468a59cb34bb568
X-Compile-Target-JDK: 1.8
X-Compile-Source-JDK: 1.8
X-Compile-Elasticsearch-Version: 6.4.0
X-Compile-Lucene-Version: 7.4.0
X-Compile-Elasticsearch-Snapshot: false

```

Looks good. Let's disassemble the code:

```
08:51:58 1d [jason@totoro:/tmp/elasticsearch/6.4.0/modules/x-pack-rollup/jar] $ /opt/java/jdk-10/bin/javap -c org.elasticsearch.xpack.rollup.Rollup
Compiled from "Rollup.java"
public class org.elasticsearch.xpack.rollup.Rollup extends org.elasticsearch.plugins.Plugin implements org.elasticsearch.plugins.ActionPlugin,org.elasticsearch.plugins.PersistentTaskPlugin {
  public static final java.lang.String BASE_PATH;

  public static final int ROLLUP_VERSION_V1;

  public static final int ROLLUP_VERSION_V2;

  public static final int CURRENT_ROLLUP_VERSION;

  public static final java.lang.String TASK_THREAD_POOL_NAME;

  public static final java.lang.String SCHEDULE_THREAD_POOL_NAME;

  public static final java.lang.String MAPPING_METADATA_PLACEHOLDER;

  public static final java.lang.String ROLLUP_TEMPLATE_VERSION_FIELD;

  public static final java.lang.String ROLLUP_TEMPLATE_VERSION_PATTERN;

  public static final java.lang.String DYNAMIC_MAPPING_TEMPLATE;

  public static final java.util.Set<java.lang.String> HEADER_FILTERS;

  public org.elasticsearch.xpack.rollup.Rollup(org.elasticsearch.common.settings.Settings);
    Code:
       0: aload_0
       1: invokespecial #3                  // Method org/elasticsearch/plugins/Plugin."<init>":()V
       4: aload_0
       5: aload_1
       6: putfield      #4                  // Field settings:Lorg/elasticsearch/common/settings/Settings;
       9: aload_0
      10: getstatic     #5                  // Field org/elasticsearch/xpack/core/XPackSettings.ROLLUP_ENABLED:Lorg/elasticsearch/common/settings/Setting;
      13: aload_1
      14: invokevirtual #6                  // Method org/elasticsearch/common/settings/Setting.get:(Lorg/elasticsearch/common/settings/Settings;)Ljava/lang/Object;
      17: checkcast     #7                  // class java/lang/Boolean
      20: invokevirtual #8                  // Method java/lang/Boolean.booleanValue:()Z
      23: putfield      #9                  // Field enabled:Z
      26: aload_0
      27: aload_1
      28: invokestatic  #10                 // Method org/elasticsearch/xpack/core/XPackPlugin.transportClientMode:(Lorg/elasticsearch/common/settings/Settings;)Z
      31: putfield      #11                 // Field transportClientMode:Z
      34: return

  public java.util.Collection<java.lang.Object> createComponents(org.elasticsearch.client.Client, org.elasticsearch.cluster.service.ClusterService, org.elasticsearch.threadpool.ThreadPool, org.elasticsearch.watcher.ResourceWatcherService, org.elasticsearch.script.ScriptService, org.elasticsearch.common.xcontent.NamedXContentRegistry, org.elasticsearch.env.Environment, org.elasticsearch.env.NodeEnvironment, org.elasticsearch.common.io.stream.NamedWriteableRegistry);
    Code:
       0: invokestatic  #12                 // Method java/util/Collections.emptyList:()Ljava/util/List;
       3: areturn

  public java.util.Collection<org.elasticsearch.common.inject.Module> createGuiceModules();
    Code:
       0: new           #13                 // class java/util/ArrayList
       3: dup
       4: invokespecial #14                 // Method java/util/ArrayList."<init>":()V
       7: astore_1
       8: aload_0
       9: getfield      #11                 // Field transportClientMode:Z
      12: ifeq          17
      15: aload_1
      16: areturn
      17: aload_1
      18: invokedynamic #15,  0             // InvokeDynamic #0:configure:()Lorg/elasticsearch/common/inject/Module;
      23: invokeinterface #16,  2           // InterfaceMethod java/util/List.add:(Ljava/lang/Object;)Z
      28: pop
      29: aload_1
      30: areturn

  protected org.elasticsearch.license.XPackLicenseState getLicenseState();
    Code:
       0: invokestatic  #17                 // Method org/elasticsearch/xpack/core/XPackPlugin.getSharedLicenseState:()Lorg/elasticsearch/license/XPackLicenseState;
       3: areturn

  public java.util.List<org.elasticsearch.rest.RestHandler> getRestHandlers(org.elasticsearch.common.settings.Settings, org.elasticsearch.rest.RestController, org.elasticsearch.common.settings.ClusterSettings, org.elasticsearch.common.settings.IndexScopedSettings, org.elasticsearch.common.settings.SettingsFilter, org.elasticsearch.cluster.metadata.IndexNameExpressionResolver, java.util.function.Supplier<org.elasticsearch.cluster.node.DiscoveryNodes>);
    Code:
       0: aload_0
       1: getfield      #9                  // Field enabled:Z
       4: ifne          11
       7: invokestatic  #12                 // Method java/util/Collections.emptyList:()Ljava/util/List;
      10: areturn
      11: bipush        8
      13: anewarray     #18                 // class org/elasticsearch/rest/RestHandler
      16: dup
      17: iconst_0
      18: new           #19                 // class org/elasticsearch/xpack/rollup/rest/RestRollupSearchAction
      21: dup
      22: aload_1
      23: aload_2
      24: invokespecial #20                 // Method org/elasticsearch/xpack/rollup/rest/RestRollupSearchAction."<init>":(Lorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/rest/RestController;)V
      27: aastore
      28: dup
      29: iconst_1
      30: new           #21                 // class org/elasticsearch/xpack/rollup/rest/RestPutRollupJobAction
      33: dup
      34: aload_1
      35: aload_2
      36: invokespecial #22                 // Method org/elasticsearch/xpack/rollup/rest/RestPutRollupJobAction."<init>":(Lorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/rest/RestController;)V
      39: aastore
      40: dup
      41: iconst_2
      42: new           #23                 // class org/elasticsearch/xpack/rollup/rest/RestStartRollupJobAction
      45: dup
      46: aload_1
      47: aload_2
      48: invokespecial #24                 // Method org/elasticsearch/xpack/rollup/rest/RestStartRollupJobAction."<init>":(Lorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/rest/RestController;)V
      51: aastore
      52: dup
      53: iconst_3
      54: new           #25                 // class org/elasticsearch/xpack/rollup/rest/RestStopRollupJobAction
      57: dup
      58: aload_1
      59: aload_2
      60: invokespecial #26                 // Method org/elasticsearch/xpack/rollup/rest/RestStopRollupJobAction."<init>":(Lorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/rest/RestController;)V
      63: aastore
      64: dup
      65: iconst_4
      66: new           #27                 // class org/elasticsearch/xpack/rollup/rest/RestDeleteRollupJobAction
      69: dup
      70: aload_1
      71: aload_2
      72: invokespecial #28                 // Method org/elasticsearch/xpack/rollup/rest/RestDeleteRollupJobAction."<init>":(Lorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/rest/RestController;)V
      75: aastore
      76: dup
      77: iconst_5
      78: new           #29                 // class org/elasticsearch/xpack/rollup/rest/RestGetRollupJobsAction
      81: dup
      82: aload_1
      83: aload_2
      84: invokespecial #30                 // Method org/elasticsearch/xpack/rollup/rest/RestGetRollupJobsAction."<init>":(Lorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/rest/RestController;)V
      87: aastore
      88: dup
      89: bipush        6
      91: new           #31                 // class org/elasticsearch/xpack/rollup/rest/RestGetRollupCapsAction
      94: dup
      95: aload_1
      96: aload_2
      97: invokespecial #32                 // Method org/elasticsearch/xpack/rollup/rest/RestGetRollupCapsAction."<init>":(Lorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/rest/RestController;)V
     100: aastore
     101: dup
     102: bipush        7
     104: new           #33                 // class org/elasticsearch/xpack/rollup/rest/RestGetRollupIndexCapsAction
     107: dup
     108: aload_1
     109: aload_2
     110: invokespecial #34                 // Method org/elasticsearch/xpack/rollup/rest/RestGetRollupIndexCapsAction."<init>":(Lorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/rest/RestController;)V
     113: aastore
     114: invokestatic  #35                 // Method java/util/Arrays.asList:([Ljava/lang/Object;)Ljava/util/List;
     117: areturn

  public java.util.List<org.elasticsearch.plugins.ActionPlugin$ActionHandler<? extends org.elasticsearch.action.ActionRequest, ? extends org.elasticsearch.action.ActionResponse>> getActions();
    Code:
       0: aload_0
       1: getfield      #9                  // Field enabled:Z
       4: ifne          11
       7: invokestatic  #12                 // Method java/util/Collections.emptyList:()Ljava/util/List;
      10: areturn
      11: bipush        8
      13: anewarray     #36                 // class org/elasticsearch/plugins/ActionPlugin$ActionHandler
      16: dup
      17: iconst_0
      18: new           #36                 // class org/elasticsearch/plugins/ActionPlugin$ActionHandler
      21: dup
      22: getstatic     #37                 // Field org/elasticsearch/xpack/core/rollup/action/RollupSearchAction.INSTANCE:Lorg/elasticsearch/xpack/core/rollup/action/RollupSearchAction;
      25: ldc           #38                 // class org/elasticsearch/xpack/rollup/action/TransportRollupSearchAction
      27: iconst_0
      28: anewarray     #39                 // class java/lang/Class
      31: invokespecial #40                 // Method org/elasticsearch/plugins/ActionPlugin$ActionHandler."<init>":(Lorg/elasticsearch/action/GenericAction;Ljava/lang/Class;[Ljava/lang/Class;)V
      34: aastore
      35: dup
      36: iconst_1
      37: new           #36                 // class org/elasticsearch/plugins/ActionPlugin$ActionHandler
      40: dup
      41: getstatic     #41                 // Field org/elasticsearch/xpack/core/rollup/action/PutRollupJobAction.INSTANCE:Lorg/elasticsearch/xpack/core/rollup/action/PutRollupJobAction;
      44: ldc           #42                 // class org/elasticsearch/xpack/rollup/action/TransportPutRollupJobAction
      46: iconst_0
      47: anewarray     #39                 // class java/lang/Class
      50: invokespecial #40                 // Method org/elasticsearch/plugins/ActionPlugin$ActionHandler."<init>":(Lorg/elasticsearch/action/GenericAction;Ljava/lang/Class;[Ljava/lang/Class;)V
      53: aastore
      54: dup
      55: iconst_2
      56: new           #36                 // class org/elasticsearch/plugins/ActionPlugin$ActionHandler
      59: dup
      60: getstatic     #43                 // Field org/elasticsearch/xpack/core/rollup/action/StartRollupJobAction.INSTANCE:Lorg/elasticsearch/xpack/core/rollup/action/StartRollupJobAction;
      63: ldc           #44                 // class org/elasticsearch/xpack/rollup/action/TransportStartRollupAction
      65: iconst_0
      66: anewarray     #39                 // class java/lang/Class
      69: invokespecial #40                 // Method org/elasticsearch/plugins/ActionPlugin$ActionHandler."<init>":(Lorg/elasticsearch/action/GenericAction;Ljava/lang/Class;[Ljava/lang/Class;)V
      72: aastore
      73: dup
      74: iconst_3
      75: new           #36                 // class org/elasticsearch/plugins/ActionPlugin$ActionHandler
      78: dup
      79: getstatic     #45                 // Field org/elasticsearch/xpack/core/rollup/action/StopRollupJobAction.INSTANCE:Lorg/elasticsearch/xpack/core/rollup/action/StopRollupJobAction;
      82: ldc           #46                 // class org/elasticsearch/xpack/rollup/action/TransportStopRollupAction
      84: iconst_0
      85: anewarray     #39                 // class java/lang/Class
      88: invokespecial #40                 // Method org/elasticsearch/plugins/ActionPlugin$ActionHandler."<init>":(Lorg/elasticsearch/action/GenericAction;Ljava/lang/Class;[Ljava/lang/Class;)V
      91: aastore
      92: dup
      93: iconst_4
      94: new           #36                 // class org/elasticsearch/plugins/ActionPlugin$ActionHandler
      97: dup
      98: getstatic     #47                 // Field org/elasticsearch/xpack/core/rollup/action/DeleteRollupJobAction.INSTANCE:Lorg/elasticsearch/xpack/core/rollup/action/DeleteRollupJobAction;
     101: ldc           #48                 // class org/elasticsearch/xpack/rollup/action/TransportDeleteRollupJobAction
     103: iconst_0
     104: anewarray     #39                 // class java/lang/Class
     107: invokespecial #40                 // Method org/elasticsearch/plugins/ActionPlugin$ActionHandler."<init>":(Lorg/elasticsearch/action/GenericAction;Ljava/lang/Class;[Ljava/lang/Class;)V
     110: aastore
     111: dup
     112: iconst_5
     113: new           #36                 // class org/elasticsearch/plugins/ActionPlugin$ActionHandler
     116: dup
     117: getstatic     #49                 // Field org/elasticsearch/xpack/core/rollup/action/GetRollupJobsAction.INSTANCE:Lorg/elasticsearch/xpack/core/rollup/action/GetRollupJobsAction;
     120: ldc           #50                 // class org/elasticsearch/xpack/rollup/action/TransportGetRollupJobAction
     122: iconst_0
     123: anewarray     #39                 // class java/lang/Class
     126: invokespecial #40                 // Method org/elasticsearch/plugins/ActionPlugin$ActionHandler."<init>":(Lorg/elasticsearch/action/GenericAction;Ljava/lang/Class;[Ljava/lang/Class;)V
     129: aastore
     130: dup
     131: bipush        6
     133: new           #36                 // class org/elasticsearch/plugins/ActionPlugin$ActionHandler
     136: dup
     137: getstatic     #51                 // Field org/elasticsearch/xpack/core/rollup/action/GetRollupCapsAction.INSTANCE:Lorg/elasticsearch/xpack/core/rollup/action/GetRollupCapsAction;
     140: ldc           #52                 // class org/elasticsearch/xpack/rollup/action/TransportGetRollupCapsAction
     142: iconst_0
     143: anewarray     #39                 // class java/lang/Class
     146: invokespecial #40                 // Method org/elasticsearch/plugins/ActionPlugin$ActionHandler."<init>":(Lorg/elasticsearch/action/GenericAction;Ljava/lang/Class;[Ljava/lang/Class;)V
     149: aastore
     150: dup
     151: bipush        7
     153: new           #36                 // class org/elasticsearch/plugins/ActionPlugin$ActionHandler
     156: dup
     157: getstatic     #53                 // Field org/elasticsearch/xpack/core/rollup/action/GetRollupIndexCapsAction.INSTANCE:Lorg/elasticsearch/xpack/core/rollup/action/GetRollupIndexCapsAction;
     160: ldc           #54                 // class org/elasticsearch/xpack/rollup/action/TransportGetRollupIndexCapsAction
     162: iconst_0
     163: anewarray     #39                 // class java/lang/Class
     166: invokespecial #40                 // Method org/elasticsearch/plugins/ActionPlugin$ActionHandler."<init>":(Lorg/elasticsearch/action/GenericAction;Ljava/lang/Class;[Ljava/lang/Class;)V
     169: aastore
     170: invokestatic  #35                 // Method java/util/Arrays.asList:([Ljava/lang/Object;)Ljava/util/List;
     173: areturn

  public java.util.List<org.elasticsearch.threadpool.ExecutorBuilder<?>> getExecutorBuilders(org.elasticsearch.common.settings.Settings);
    Code:
       0: iconst_0
       1: aload_0
       2: getfield      #9                  // Field enabled:Z
       5: if_icmpeq     15
       8: aload_0
       9: getfield      #11                 // Field transportClientMode:Z
      12: ifeq          19
      15: invokestatic  #12                 // Method java/util/Collections.emptyList:()Ljava/util/List;
      18: areturn
      19: new           #55                 // class org/elasticsearch/threadpool/FixedExecutorBuilder
      22: dup
      23: aload_1
      24: ldc           #56                 // String rollup_indexing
      26: iconst_4
      27: iconst_4
      28: ldc           #57                 // String xpack.rollup.task_thread_pool
      30: invokespecial #58                 // Method org/elasticsearch/threadpool/FixedExecutorBuilder."<init>":(Lorg/elasticsearch/common/settings/Settings;Ljava/lang/String;IILjava/lang/String;)V
      33: astore_2
      34: aload_2
      35: invokestatic  #59                 // Method java/util/Collections.singletonList:(Ljava/lang/Object;)Ljava/util/List;
      38: areturn

  public java.util.List<org.elasticsearch.persistent.PersistentTasksExecutor<?>> getPersistentTasksExecutor(org.elasticsearch.cluster.service.ClusterService, org.elasticsearch.threadpool.ThreadPool, org.elasticsearch.client.Client);
    Code:
       0: aload_0
       1: getfield      #9                  // Field enabled:Z
       4: ifeq          14
       7: aload_0
       8: getfield      #11                 // Field transportClientMode:Z
      11: ifeq          18
      14: invokestatic  #12                 // Method java/util/Collections.emptyList:()Ljava/util/List;
      17: areturn
      18: new           #60                 // class org/elasticsearch/xpack/core/scheduler/SchedulerEngine
      21: dup
      22: aload_0
      23: invokevirtual #61                 // Method getClock:()Ljava/time/Clock;
      26: invokespecial #62                 // Method org/elasticsearch/xpack/core/scheduler/SchedulerEngine."<init>":(Ljava/time/Clock;)V
      29: astore        4
      31: new           #63                 // class org/elasticsearch/xpack/rollup/job/RollupJobTask$RollupJobPersistentTasksExecutor
      34: dup
      35: aload_0
      36: getfield      #4                  // Field settings:Lorg/elasticsearch/common/settings/Settings;
      39: aload_3
      40: aload         4
      42: aload_2
      43: invokespecial #64                 // Method org/elasticsearch/xpack/rollup/job/RollupJobTask$RollupJobPersistentTasksExecutor."<init>":(Lorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/client/Client;Lorg/elasticsearch/xpack/core/scheduler/SchedulerEngine;Lorg/elasticsearch/threadpool/ThreadPool;)V
      46: invokestatic  #59                 // Method java/util/Collections.singletonList:(Ljava/lang/Object;)Ljava/util/List;
      49: areturn

  protected java.time.Clock getClock();
    Code:
       0: invokestatic  #65                 // Method java/time/Clock.systemUTC:()Ljava/time/Clock;
       3: areturn

  static {};
    Code:
       0: ldc           #68                 // String ${rollup.dynamic_template.version}
       2: invokestatic  #69                 // Method java/util/regex/Pattern.quote:(Ljava/lang/String;)Ljava/lang/String;
       5: putstatic     #70                 // Field ROLLUP_TEMPLATE_VERSION_PATTERN:Ljava/lang/String;
       8: ldc           #71                 // String /rollup-dynamic-template.json
      10: getstatic     #72                 // Field org/elasticsearch/Version.CURRENT:Lorg/elasticsearch/Version;
      13: invokevirtual #73                 // Method org/elasticsearch/Version.toString:()Ljava/lang/String;
      16: getstatic     #70                 // Field ROLLUP_TEMPLATE_VERSION_PATTERN:Ljava/lang/String;
      19: invokestatic  #74                 // Method org/elasticsearch/xpack/core/template/TemplateUtils.loadTemplate:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
      22: putstatic     #75                 // Field DYNAMIC_MAPPING_TEMPLATE:Ljava/lang/String;
      25: new           #76                 // class java/util/HashSet
      28: dup
      29: iconst_2
      30: anewarray     #77                 // class java/lang/String
      33: dup
      34: iconst_0
      35: ldc           #78                 // String es-security-runas-user
      37: aastore
      38: dup
      39: iconst_1
      40: ldc           #79                 // String _xpack_security_authentication
      42: aastore
      43: invokestatic  #35                 // Method java/util/Arrays.asList:([Ljava/lang/Object;)Ljava/util/List;
      46: invokespecial #80                 // Method java/util/HashSet."<init>":(Ljava/util/Collection;)V
      49: putstatic     #81                 // Field HEADER_FILTERS:Ljava/util/Set;
      52: return
}
08:53:13 1d [jason@totoro:/tmp/elasticsearch/6.4.0/modules/x-pack-rollup/jar] $ 
```

Looking more closely at `org.elasticsearch.xpack.rollup.Rollup#getPersistentTasksExecutor`:

```
  public java.util.List<org.elasticsearch.persistent.PersistentTasksExecutor<?>> getPersistentTasksExecutor(org.elasticsearch.cluster.service.ClusterService, org.elasticsearch.threadpool.ThreadPool, org.elasticsearch.client.Client);
    Code:
       0: aload_0
       1: getfield      #9                  // Field enabled:Z
       4: ifeq          14
       7: aload_0
       8: getfield      #11                 // Field transportClientMode:Z
      11: ifeq          18
      14: invokestatic  #12                 // Method java/util/Collections.emptyList:()Ljava/util/List;
      17: areturn
      18: new           #60                 // class org/elasticsearch/xpack/core/scheduler/SchedulerEngine
      21: dup
      22: aload_0
      23: invokevirtual #61                 // Method getClock:()Ljava/time/Clock;
      26: invokespecial #62                 // Method org/elasticsearch/xpack/core/scheduler/SchedulerEngine."<init>":(Ljava/time/Clock;)V
      29: astore        4
      31: new           #63                 // class org/elasticsearch/xpack/rollup/job/RollupJobTask$RollupJobPersistentTasksExecutor
      34: dup
      35: aload_0
      36: getfield      #4                  // Field settings:Lorg/elasticsearch/common/settings/Settings;
      39: aload_3
      40: aload         4
      42: aload_2
      43: invokespecial #64                 // Method org/elasticsearch/xpack/rollup/job/RollupJobTask$RollupJobPersistentTasksExecutor."<init>":(Lorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/client/Client;Lorg/elasticsearch/xpack/core/scheduler/SchedulerEngine;Lorg/elasticsearch/threadpool/ThreadPool;)V
      46: invokestatic  #59                 // Method java/util/Collections.singletonList:(Ljava/lang/Object;)Ljava/util/List;
      49: areturn

```

This looks like the code matching the commit hash: https://github.com/elastic/elasticsearch/blob/595516e45d054483dcdaf12f0468a59cb34bb568/x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/Rollup.java#L190-L199

The problem here is that the v6.4.0 tag was applied incorrectly:

```
09:09:47 1d [jason@totoro:/tmp/elasticsearch/6.4.0/modules/x-pack-rollup/jar] $ git -C ~/src/elastic/elasticsearch rev-list -n 1 v6.4.0
1a122904dd29df3f8692310437fd37267706d84b
```

That is wrong, per the manifest it should be: `595516e45d054483dcdaf12f0468a59cb34bb568`

I will fix the tag later this morning.

**Comment by jasontedor** [comment]
I removed the incorrect tag and pushed the correct tag.
