### ISSUE TITLE
[CI] CcrMultiClusterLicenseIT.testAutoFollow failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#33570]
Windows related problem:

```
All tests run in this JVM: [CcrMultiClusterLicenseIT]
20:16:01    >     at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
20:16:01    >     at java.security.AccessController.checkPermission(AccessController.java:884)
20:16:01 
20:16:01    >     at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
20:16:01    >     at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
20:16:01    >     at sun.nio.fs.WindowsChannelFactory.open(WindowsChannelFactory.java:293)
20:16:01    >     at sun.nio.fs.WindowsChannelFactory.newFileChannel(WindowsChannelFactory.java:162)
20:16:01    >     at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:225)
20:16:01    >     at java.nio.file.Files.newByteChannel(Files.java:361)
20:16:01    >     at java.nio.file.Files.newByteChannel(Files.java:407)
20:16:01    >     at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
20:16:01    >     at org.apache.lucene.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:192)
20:16:01    >     at org.apache.lucene.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:192)
20:16:01    >     at org.apache.lucene.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:192)
20:16:01    >     at org.apache.lucene.mockfile.HandleTrackingFS.newInputStream(HandleTrackingFS.java:92)
20:16:01    >     at org.apache.lucene.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:192)
20:16:01    >     at org.apache.lucene.mockfile.HandleTrackingFS.newInputStream(HandleTrackingFS.java:92)
20:16:01    >     at org.apache.lucene.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:192)
20:16:01    >     at java.nio.file.Files.newInputStream(Files.java:152)
20:16:01    >     at java.nio.file.Files.newBufferedReader(Files.java:2784)
20:16:01    >     at java.nio.file.Files.readAllLines(Files.java:3202)
20:16:01    >     at java.nio.file.Files.readAllLines(Files.java:3242)
20:16:01    >     at org.elasticsearch.xpack.ccr.CcrMultiClusterLicenseIT.lambda$testAutoFollow$0(CcrMultiClusterLicenseIT.java:57)
20:16:01    >     at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
20:16:01    >     at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:821)
20:16:01    >     at org.elasticsearch.xpack.ccr.CcrMultiClusterLicenseIT.testAutoFollow(CcrMultiClusterLicenseIT.java:56)
20:16:01    >     at java.lang.Thread.run(Thread.java:748)
```

Two build failure thus far:
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/1281/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1863/console

**Comment by martijnvg** [comment]
This test has been moved to new downgrade to basic qa module and is enabled on Windows. I small part that does not work on Windows is not executed when running test on Windows. I think that this is ok.
