### ISSUE TITLE
Getting conflict with existing mapping when upgrading from 6.2 to 6.3

### ISSUE THREAD

**Issue by kylelyk** [elastic/elasticsearch#33611]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.3

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_172

**OS version** (`uname -a` if on a Unix-like system): MacOS (Darwin Kernel Version 15.6.0)

**Description of the problem including expected versus actual behavior**:
After upgrading from Elasticsearch 6.2 to 6.3, we're getting these errors in the logs, which can cause the entire cluster to go down for a moment.

**Steps to reproduce**:

I think I've been able to narrow down the problem to the following steps, however it does not happen very often when manually testing it, but our integration tests catch it almost every time.

```
PUT test
{
  "settings": {
    "analysis": {
      "analyzer": {
        "text_en_splitting": {
          "type": "custom",
          "char_filter": [
            "html_strip"
          ],
          "tokenizer": "whitespace",
          "filter": [
            "asciifolding",
            "word_delimiter_custom",
            "lowercase",
            "porter_stem"
          ]
        }
      },
      "filter": {
        "word_delimiter_custom": {
          "type": "word_delimiter",
          "catenate_words": true,
          "catenate_numbers": true,
          "split_on_case_change": false
        }
      },
      "normalizer": {
        "lower_case_ascii": {
          "type": "custom",
          "char_filter": [],
          "filter": [
            "lowercase",
            "asciifolding"
          ]
        }
      }
    },
    "index": {
      "number_of_shards": 4,
      "number_of_replicas": 0,
      "refresh_interval": "1s",
      "mapping": {
        "total_fields": {
          "limit": 40000
        }
      }
    },
    "similarity": {
      "custom_similarity": {
        "type": "scripted",
        "script": {
          "source": "int threshold = 5; double tf = Math.sqrt(doc.freq); if (doc.freq > threshold) { tf /= Math.exp(doc.freq); } double idf = Math.log((field.docCount+1.0)/(term.docFreq+1.0)) + 1.0; double norm = 1/Math.sqrt(doc.length); return query.boost * tf * idf * norm;"
        }
      }
    }
  },
  "mappings": {
    "_doc": {
      "_routing": {
        "required": true
      },
      "dynamic": "strict",
      "properties": {
        "details": {
          "properties": {
            "master": {
              "type": "text",
              "analyzer": "text_en_splitting",
              "similarity": "custom_similarity"
            },
            "other": {
              "type": "object",
              "dynamic": true
            }
          }
        }
      }
    }
  }
}
```

```
POST test/_doc/1?routing=1
{"details.master":"foo"}
```

```
GET test/_search
{
  "query": {
    "term": {
      "details.master": {
        "value": "foo"
      }
    }
  }
}
```

The weird thing is that these queries succeed, but then at some point the cluster encounters the exception, and new queries fail due to the cluster being offline.

**Provide logs (if relevant)**:
```
[2018-09-11T18:41:47,813][WARN ][o.e.c.r.a.AllocationService] [kIvzo8F] failing shard [failed shard, shard [ce][0], node[kIvzo8FnRM6luAJF3MkFMA], [P], s[STARTED], a[id=z-Krv7QCR5mhKzUP9Sgmpw], message [failed to update mapping for index], failure [IllegalArgumentException[Mapper for [details.master] conflicts with existing mapping in other types:
[mapper [details.master] has different [similarity]]]], markAsStale [true]]
java.lang.IllegalArgumentException: Mapper for [details.master] conflicts with existing mapping in other types:
[mapper [details.master] has different [similarity]]
	at org.elasticsearch.index.mapper.FieldTypeLookup.checkCompatibility(FieldTypeLookup.java:130) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.index.mapper.FieldTypeLookup.copyAndAddAll(FieldTypeLookup.java:94) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:439) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:356) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:305) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.index.mapper.MapperService.updateMapping(MapperService.java:235) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.index.IndexService.updateMapping(IndexService.java:525) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.updateIndices(IndicesClusterStateService.java:487) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:226) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$6(ClusterApplierService.java:496) ~[elasticsearch-6.3.2.jar:6.3.2]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_172]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:493) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:480) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:431) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:161) ~[elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:626) [elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) [elasticsearch-6.3.2.jar:6.3.2]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) [elasticsearch-6.3.2.jar:6.3.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
[2018-09-11T18:41:47,816][INFO ][o.e.c.r.a.AllocationService] [kIvzo8F] Cluster health status changed from [GREEN] to [RED] (reason: [shards failed [[ce][3], [ce][2], [ce][1], [ce][0]] ...]).
[2018-09-11T18:41:48,038][INFO ][o.e.c.r.a.AllocationService] [kIvzo8F] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[ce][0], [ce][2]] ...]).
```

**Comment by jimczi** [comment]
Ouch this is a bad bug, I can reproduce with this recreation:

````
PUT example
{ 
	"properties": {
		"text": {
			"type": "text",
			"similarity": "classic",
			"fielddata": true
		}
	}
} 

POST example/doc/_mappings
{ 
	"properties": {
		"text": {
			"type": "text",
			"similarity": "classic",
			"fielddata": true
		}
	}
} 
`````
The second command fails with the following error:
````
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "Mapper for [text] conflicts with existing mapping in other types:\n[mapper [text] has different [similarity]]"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "Mapper for [text] conflicts with existing mapping in other types:\n[mapper [text] has different [similarity]]"
    },
    "status": 400
}
````
The bug was introduced in 6.3 where it is now impossible to update a field if it uses an explicit similarity. I think I know why this bug occurs but I need to understand why it was never caught in our tests.

**Comment by jimczi** [comment]
I just merged the fix in the 6.4 branch so it will be part of 6.4.1 when it's released.
Thanks for reporting @kylelyk !

**Comment by jimczi** [comment]
Sorry @kylelyk that's not possible. We publish bugfix releases for the last minor of the current and last major version (5.6.x and 6.4.x at the moment) so you'll need to wait for 6.4.1.
