### ISSUE TITLE
SourceOnlySnapshotShardTests testRestoreMinmal

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#33689]
This reproduces locally for me (on master 3914a980f799b39a0c2983fba964):
```
./gradlew :x-pack:plugin:core:test -Dtests.seed=69555F822415CEA1 -Dtests.class=org.elasticsearch.snapshots.SourceOnlySnapshotShardTests -Dtests.method="testRestoreMinmal" -Dtests.security.manager=true -Dtests.locale=hu-HU -Dtests.timezone=America/Argentina/Ushuaia -Dcompiler.java=10 -Druntime.java=8

   > Throwable #1: java.lang.AssertionError: expected:<15> but was:<21>
   >    at __randomizedtesting.SeedInfo.seed([69555F822415CEA1:F482086E86FD706F]:0)
   >    at org.elasticsearch.snapshots.SourceOnlySnapshotShardTests.testRestoreMinmal(SourceOnlySnapshotShardTests.java:227)
   >    at java.lang.Thread.run(Thread.java:748)

```
Originally, I got the failure in a PR branch: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/17335/console

**Comment by dnhatn** [comment]
I've muted this test on master and 6.x.
