### ISSUE TITLE
SearchAsyncActionTests.testFanOutAndCollect throws RejectedExecutionException

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#33699]
I dug into #29242 again and tried to reproduce the problem at 5a3fd8e4e7c8d2721b3542ffa859c9245678d6c2 by running the affected test repeatedly until it failed by using:

    date | tee pass-times.log; while ./gradlew --console=plain :server:test -Dtests.class=org.elasticsearch.action.search.SearchAsyncActionTests -Dtests.method="testFanOutAndCollect" 2>&1 > testoutput.log; do date | tee -a pass-times.log; done

After around 1000 iterations (6 hours) it failed with a different issue:

```
  2> ༩ ༡༣, ༢༠༡༨ ༢:༤༧:༢༧ ཕྱི་ཆ་ com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
  2> WARNING: Uncaught exception in thread: Thread[Thread-1,5,TGRP-SearchAsyncActionTests]
  2> java.util.concurrent.RejectedExecutionException: Task org.elasticsearch.action.search.InitialSearchPhase$1@db8dd7d rejected from java.util.concurrent.ThreadPoolExecutor@2e3a06e7[Terminated,
 pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
  2>    at __randomizedtesting.SeedInfo.seed([CAEABDE40791E9D5]:0)
  2>    at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2080)
  2>    at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:832)
  2>    at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
  2>    at org.elasticsearch.action.search.InitialSearchPhase.fork(InitialSearchPhase.java:174)
  2>    at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:167)
  2>    at org.elasticsearch.action.search.InitialSearchPhase.executeNext(InitialSearchPhase.java:239)
  2>    at org.elasticsearch.action.search.InitialSearchPhase.lambda$performPhaseOnShard$4(InitialSearchPhase.java:293)
  2>    at org.elasticsearch.action.search.InitialSearchPhase$PendingExecutions.tryRun(InitialSearchPhase.java:214)
  2>    at org.elasticsearch.action.search.InitialSearchPhase$PendingExecutions.finishAndRunNext(InitialSearchPhase.java:208)
  2>    at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:169)
  2>    at org.elasticsearch.action.search.InitialSearchPhase.executeNext(InitialSearchPhase.java:239)
  2>    at org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:50)
  2>    at org.elasticsearch.action.search.InitialSearchPhase$2.innerOnResponse(InitialSearchPhase.java:270)
  2>    at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:45)
  2>    at org.elasticsearch.action.search.SearchAsyncActionTests$7.lambda$executePhaseOnShard$1(SearchAsyncActionTests.java:334)
  2>    at java.base/java.lang.Thread.run(Thread.java:844)
  2> REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=CAEABDE40791E9D5 -Dtests.class=org.elasticsearch.action.search.SearchAsyncActionTests -Dtests.method="testFanOutAndCollect" -Dtests.security.manager=true -Dtests.locale=dz -Dtests.timezone=Etc/GMT+11 -Dcompiler.java=10 -Druntime.java=10
ERROR   0.14s | SearchAsyncActionTests.testFanOutAndCollect <<< FAILURES!
   > Throwable #1: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=18, name=Thread-1, state=RUNNABLE, group=TGRP-SearchAsyncActionTests]
   >    at __randomizedtesting.SeedInfo.seed([CAEABDE40791E9D5:B11B3894FE3A2856]:0)
   > Caused by: java.util.concurrent.RejectedExecutionException: Task org.elasticsearch.action.search.InitialSearchPhase$1@db8dd7d rejected from java.util.concurrent.ThreadPoolExecutor@2e3a06e7[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
   >    at __randomizedtesting.SeedInfo.seed([CAEABDE40791E9D5]:0)
   >    at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2080)
   >    at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:832)
   >    at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
   >    at org.elasticsearch.action.search.InitialSearchPhase.fork(InitialSearchPhase.java:174)
   >    at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:167)
   >    at org.elasticsearch.action.search.InitialSearchPhase.executeNext(InitialSearchPhase.java:239)
   >    at org.elasticsearch.action.search.InitialSearchPhase.lambda$performPhaseOnShard$4(InitialSearchPhase.java:293)
   >    at org.elasticsearch.action.search.InitialSearchPhase$PendingExecutions.tryRun(InitialSearchPhase.java:214)
   >    at org.elasticsearch.action.search.InitialSearchPhase$PendingExecutions.finishAndRunNext(InitialSearchPhase.java:208)
   >    at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:169)
   >    at org.elasticsearch.action.search.InitialSearchPhase.executeNext(InitialSearchPhase.java:239)
   >    at org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:50)
   >    at org.elasticsearch.action.search.InitialSearchPhase$2.innerOnResponse(InitialSearchPhase.java:270)
   >    at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:45)
   >    at org.elasticsearch.action.search.SearchAsyncActionTests$7.lambda$executePhaseOnShard$1(SearchAsyncActionTests.java:334)
   >    at java.base/java.lang.Thread.run(Thread.java:844)
  2> NOTE: test params are: codec=Asserting(Lucene80): {}, docValues:{}, maxPointsInLeafNode=1617, maxMBSortInHeap=7.294998490965383, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@5ee576f6), locale=dz, timezone=Etc/GMT+11
  2> NOTE: Linux 4.13.0-32-generic amd64/Oracle Corporation 10 (64-bit)/cpus=8,threads=1,free=494096088,total=536870912
  2> NOTE: All tests run in this JVM: [SearchAsyncActionTests]

FAILURE: Build failed with an exception.
```

I initially saw this kind of failure using `-Dtests.iters=1000`, which yielded this failure after only a few runs, but was unsure whether it might have been a symptom of the `tests.iters` setting. This confirms that it can also occur if the test runs individually.

**Comment by DaveCTurner** [comment]
I can confirm that this still happens with latest `master` (6c07d105f3c0cb27610affa463910e96e3e1609f). Looking in more depth at the stack trace, the task that is being rejected seems to be `pendingExecutions::finishAndRunNext` which apparently runs after each phase (including the last), and the test does not wait for this to have happened before shutting the executor down.

**Comment by danielmitterdorfer** [comment]
We discussed this one in the test triage power hour. Instead of scheduling new tasks unconditionally, we should rather use `scheduleUnlessShuttingDown()` to avoid this situation. See also the related refactoring effort #36318 (which is intended to replace call sites where we have manually implemented the mitigation that is missing here with `scheduleUnlessShuttingDown()`).
