### ISSUE TITLE
[CI] FullClusterRestartSettingsUpgradeIT reproducibly fails

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#33697]
The latest failure:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+bwc-tests/1438/console

I was able to reproduce it on master with:

```
REPRODUCE WITH: ./gradlew :qa:full-cluster-restart:v6.0.0#oldClusterTestRunner \
  -Dtests.seed=FD2648429FDB5919 \
  -Dtests.class=org.elasticsearch.upgrades.FullClusterRestartSettingsUpgradeIT \
  -Dtests.method="testRemoteClusterSettingsUpgraded" \
  -Dtests.security.manager=true \
  -Dtests.locale=is-IS \
  -Dtests.timezone=Asia/Riyadh \
  -Dcompiler.java=10 \
  -Druntime.java=8
```

Failure:

```
   > Throwable #1: org.elasticsearch.client.ResponseException: method [PUT], host [http://[::1]:57554], URI [/_cluster/settings], status line [HTTP/1.1 400 Bad Request]
   > {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"persistent setting [search.remote.foo.skip_unavailable], not dynamically updateable"}],"type":"illegal_argument_exception","reason":"persistent setting [search.remote.foo.skip_unavailable], not dynamically updateable"},"status":400}
   >    at __randomizedtesting.SeedInfo.seed([FD2648429FDB5919:6DF23EACEBD0F731]:0)
   >    at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:681)
   >    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:216)
   >    at org.elasticsearch.upgrades.FullClusterRestartSettingsUpgradeIT.testRemoteClusterSettingsUpgraded(FullClusterRestartSettingsUpgradeIT.java:61)
   >    at java.lang.Thread.run(Thread.java:748)
   > Caused by: org.elasticsearch.client.ResponseException: method [PUT], host [http://[::1]:57554], URI [/_cluster/settings], status line [HTTP/1.1 400 Bad Request]
   > {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"persistent setting [search.remote.foo.skip_unavailable], not dynamically updateable"}],"type":"illegal_argument_exception","reason":"persistent setting [search.remote.foo.skip_unavailable], not dynamically updateable"},"status":400}
   >    at org.elasticsearch.client.RestClient$1.completed(RestClient.java:301)
   >    at org.elasticsearch.client.RestClient$1.completed(RestClient.java:290)
   >    at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
   >    at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
   >    at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
   >    at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
   >    at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
   >    at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
   >    at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
   >    at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
   >    at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
   >    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
   >    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
   >    at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
   >    at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
   >    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
   >    ... 1 more
```

**Comment by jasontedor** [comment]
Closed by d65ff17b7edbed50e947e863d981a850de0736da
