### ISSUE TITLE
testMaxSizeExceededOnResize fails to create array to resize

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#33750]
There have been a few failures recently of `BigArraysTests#testMaxSizeExceededOnResize` in which we hit a `CircuitBreakingException` on this line:

https://github.com/elastic/elasticsearch/blob/46ac8d1a51339972f9647775155dc1a2ee1ca624/server/src/test/java/org/elasticsearch/common/util/BigArraysTests.java#L363

The full stack trace from https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian/1/console follows:

```
java.lang.reflect.InvocationTargetException
	at __randomizedtesting.SeedInfo.seed([9ECB54FC37009C71:A6FDADAB65815066]:0)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.elasticsearch.common.util.BigArraysTests.testMaxSizeExceededOnResize(BigArraysTests.java:363)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
Caused by: CircuitBreakingException[[parent] Data too large, data for [<reused_arrays>] would be [491472096/468.7mb], which is larger than the limit of [489108275/466.4mb], real usage: [491390176/468.6mb], new bytes reserved: [81920/80kb]]
	at org.elasticsearch.indices.breaker.HierarchyCircuitBreakerService.checkParentLimit(HierarchyCircuitBreakerService.java:300)
	at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.addEstimateBytesAndMaybeBreak(ChildMemoryCircuitBreaker.java:128)
	at org.elasticsearch.common.util.BigArrays.adjustBreaker(BigArrays.java:407)
	at org.elasticsearch.common.util.BigArrays.newByteArray(BigArrays.java:474)
	at org.elasticsearch.common.util.BigArrays.newByteArray(BigArrays.java:489)
	... 42 more
```

This may relate to 46ac8d1a51339972f9647775155dc1a2ee1ca624, although there seem to have been failures of this nature before that was merged. Unfortunately the build logs for the similar-looking failures were lost in the move so it's not clear.

The `REPRODUCE WITH` line follows, although it does not reproduce for me.

```
REPRODUCE WITH: ./gradlew :server:test \
  -Dtests.seed=9ECB54FC37009C71 \
  -Dtests.class=org.elasticsearch.common.util.BigArraysTests \
  -Dtests.method="testMaxSizeExceededOnResize" \
  -Dtests.security.manager=true \
  -Dtests.locale=cs \
  -Dtests.timezone=Australia/LHI \
  -Dcompiler.java=10 \
  -Druntime.java=8
```

@jpountz could you have a look at this?

**Comment by jpountz** [comment]
I'll just disable the real-memory circuit breaker entirely in this test like @danielmitterdorfer did in 5236f2b1af88bd493c05ea619b96877d38e940bf.

**Comment by cbuescher** [comment]
I just ran into this again in a PR on a branch that contains  b06a082: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/439/console

```
18:13:35    > Throwable #1: java.lang.reflect.InvocationTargetException
18:13:35    > 	at __randomizedtesting.SeedInfo.seed([A5BCCF97E347CCDA:9D8A36C0B1C600CD]:0)
18:13:35    > 	at org.elasticsearch.common.util.BigArraysTests.testMaxSizeExceededOnResize(BigArraysTests.java:364)
18:13:35    > 	at java.lang.Thread.run(Thread.java:748)
18:13:35    > Caused by: CircuitBreakingException[[request] Data too large, data for [<reused_arrays>] would be [2818048/2.6mb], which is larger than the limit of [2817079/2.6mb]]
18:13:35    > 	at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.circuitBreak(ChildMemoryCircuitBreaker.java:98)
18:13:35    > 	at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.limit(ChildMemoryCircuitBreaker.java:170)
18:13:35    > 	at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.addEstimateBytesAndMaybeBreak(ChildMemoryCircuitBreaker.java:123)
18:13:35    > 	at org.elasticsearch.common.util.BigArrays.adjustBreaker(BigArrays.java:407)
18:13:35    > 	at org.elasticsearch.common.util.BigArrays.newLongArray(BigArrays.java:608)
18:13:35    > 	at org.elasticsearch.common.util.BigArrays.newLongArray(BigArrays.java:623)
18:13:35    > 	... 42 more
```

Looks very similar, so I'm reopening for further investigation.

**Comment by danielmitterdorfer** [comment]
I had a quick look and this failure reproduces always for me with reproduction line from the failed build above:

```
./gradlew :server:test -Dtests.seed=A5BCCF97E347CCDA -Dtests.class=org.elasticsearch.common.util.BigArraysTests -Dtests.method="testMaxSizeExceededOnResize" -Dtests.security.manager=true -Dtests.locale=sr-CS -Dtests.timezone=America/Cayman -Dcompiler.java=10 -Druntime.java=8
```

I think this is a test bug and the problem boils down to the fact that the calculation in the following line is not taking object alignment into consideration when creating the array initially?

https://github.com/elastic/elasticsearch/blob/b654d986d7814b66808e40dfe8a4a891b7d6a7f4/server/src/test/java/org/elasticsearch/common/util/BigArraysTests.java#L363

Instead I think we need to use the same calculation approach as `BigArrays` in order to get an accurate upper bound?

**Comment by jpountz** [comment]
+1 to ignore shallow size in the test and reserve 100 bytes less in the test

**Comment by dliappis** [comment]
Observed again in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/107/console

Fails consistent on my workstation:

**Reproduction:**
```
./gradlew :server:test \
  -Dtests.seed=A5B1126BC2578184 \
  -Dtests.class=org.elasticsearch.common.util.BigArraysTests \
  -Dtests.method="testMaxSizeExceededOnResize" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-KW \
  -Dtests.timezone=Asia/Vladivostok \
  -Dcompiler.java=10 \
  -Druntime.java=8
```
