### ISSUE TITLE
Failure in SourceOnlySnapshotTests.testSourceOnlyRandom

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#33755]
```
./gradlew :x-pack:plugin:core:test \
  -Dtests.seed=3573246BA8A76617 \
  -Dtests.class=org.elasticsearch.snapshots.SourceOnlySnapshotTests \
  -Dtests.method="testSourceOnlyRandom" \
  -Dtests.security.manager=true \
  -Dtests.locale=el-GR \
  -Dtests.timezone=ECT \
  -Dcompiler.java=10 \
  -Druntime.java=8
```

yielded

```
FAILURE 7.07s | SourceOnlySnapshotTests.testSourceOnlyRandom <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<600> but was:<979>
   >    at __randomizedtesting.SeedInfo.seed([3573246BA8A76617:C6419F8A6436F980]:0)
   >    at org.elasticsearch.snapshots.SourceOnlySnapshotTests.testSourceOnlyRandom(SourceOnlySnapshotTests.java:93)
   >    at java.lang.Thread.run(Thread.java:748)
```

on 6.x (a7ea5e0360218ff2687de9b3b6c1b50676577c18) 

This was found in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=oraclelinux/2/console

@s1monw could you take a look please?

**Comment by s1monw** [comment]
@jakelandis looking
