### ISSUE TITLE
[CI] SSLDriverTests failures with jdk11-ea-28

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#33751]
Starting with ea-28 release of JDK11, the error message of `SSLException` for protocol mismatch changed to 
> The client supported protocol versions [TLSv1.1] are not accepted by server preferences [TLS12]

from 

> Received fatal alert: protocol_version

Furthermore, the error on which we match in `SSLDriverTests#failedCloseAlert()` changed to `Received fatal alert: protocol_version` from `Received fatal alert: handshake_failure`

Example failures:
https://elasticsearch-ci.elastic.co/view/Elasticsearch/job/elastic+elasticsearch+master+matrix-java-periodic/5/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/consoleText
https://elasticsearch-ci.elastic.co/view/Elasticsearch/job/elastic+elasticsearch+master+matrix-java-periodic/5/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/consoleText

Error: 
```
FAILURE 0.13s J3 | SSLDriverTests.testHandshakeFailureBecauseProtocolMismatch <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Unexpected exception message: The client supported protocol versions [TLSv1.1] are not accepted by server preferences [TLS12]
   > 	at __randomizedtesting.SeedInfo.seed([F3726E243A1C5828:6FE73CB5EEEC9980]:0)
   > 	at org.elasticsearch.xpack.security.transport.nio.SSLDriverTests.testHandshakeFailureBecauseProtocolMismatch(SSLDriverTests.java:140)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   > 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   > 	at java.base/java.lang.Thread.run(Thread.java:834)
  1> [2018-09-17T01:44:47,943][INFO ][o.e.x.s.t.n.SSLDriverTests] [testRenegotiate] before test
  1> [2018-09-17T01:44:48,104][INFO ][o.e.x.s.t.n.SSLDriverTests] [testRenegotiate] after test
Completed [4/198] on J3 in 3.14s, 6 tests, 1 failure, 1 skipped <<< FAILURES!
```

REPRO LINE ( needs jdk11-ea28 locally):
```
./gradlew :x-pack:plugin:security:test -Dtests.seed=F3726E243A1C5828 -Dtests.class=org.elasticsearch.xpack.security.transport.nio.SSLDriverTests -Dtests.method="testHandshakeFailureBecauseProtocolMismatch" -Dtests.security.manager=true -Dtests.locale=kam-KE -Dtests.timezone=Canada/Eastern -Dcompiler.java=10 -Druntime.java=11
```

**Comment by tbrooks8** [comment]
Should be fixed by #34398
