### ISSUE TITLE
Review fix for NPE in _cat/shards 

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#33877]
I pushed https://github.com/elastic/elasticsearch/commit/46a458c to `6.x` to fix a NPE that was breaking CI.

I believe the fix is correct - that we never want to call `func` with a null argument (because it is typically the method receiver), but would appreciate a post-hoc review.

We may also want to port that fix to master.

```
00:13:16   2> REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v5.6.13-SNAPSHOT#mixedClusterTestRunner -Dtests.seed=2CF3115B7B3E5340 -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT -Dtests.method="test {p0=cat.shards/10_basic/Test cat shards using wildcards}" -Dtests.security.manager=true -Dtests.locale=en-PH -Dtests.timezone=Asia/Karachi -Dcompiler.java=10 -Druntime.java=8
00:13:16   1>         "type" : "null_pointer_exception",
00:13:16   1>         "reason" : null,
00:13:16   1>         "stack_trace" : "java.lang.NullPointerException
00:13:16   1> 	at org.elasticsearch.rest.action.cat.RestShardsAction.getOrNull(RestShardsAction.java:198)
00:13:16   1> 	at org.elasticsearch.rest.action.cat.RestShardsAction.buildTable(RestShardsAction.java:331)
00:13:16   1> 	at org.elasticsearch.rest.action.cat.RestShardsAction.access$000(RestShardsAction.java:63)
00:13:16   1> 	at org.elasticsearch.rest.action.cat.RestShardsAction$1$1.buildResponse(RestShardsAction.java:97)
00:13:16   1> 	at org.elasticsearch.rest.action.cat.RestShardsAction$1$1.buildResponse(RestShardsAction.java:94)
00:13:16   1> 	at org.elasticsearch.rest.action.RestResponseListener.processResponse(RestResponseListener.java:37)
00:13:16   1> 	at org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:47)
00:13:16   1> 	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:85)
00:13:16   1> 	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:81)
```

**Provide logs (if relevant)**:

**Comment by s1monw** [comment]
pure gold 🤦‍♂️
