### ISSUE TITLE
[CI] IndexShardTests.testIndexCheckOnStartup failure

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#33881]
Reproduces reliably for me on `6.x` (but seems to be specific to this seed)
```
05:23:59   2> REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=714504A126B124F7 -Dtests.class=org.elasticsearch.index.shard.IndexShardTests -Dtests.method="testIndexCheckOnStartup" -Dtests.security.manager=true -Dtests.locale=es-NI -Dtests.timezone=Europe/Sofia -Dcompiler.java=10 -Druntime.java=8
05:23:59 Suite: org.elasticsearch.index.shard.IndexShardTests
```
```
05:23:59   1> [2018-09-20T08:23:51,459][INFO ][o.e.i.s.IndexShardTests  ] [testIndexCheckOnStartup] before test
05:23:59   1> [2018-09-20T08:23:51,604][INFO ][test                     ] [testIndexCheckOnStartup] Corrupting file --  flipping at position 2519 from ffffff8e to ffffff8f file: _0.cfs
05:23:59   1> [2018-09-20T08:23:51,605][INFO ][test                     ] [testIndexCheckOnStartup] Checksum before: [3342765594] after: [3342765594] checksum value after corruption: 3342765850] file: _0.cfs length: 2521
05:23:59   1> [2018-09-20T08:23:51,689][INFO ][o.e.i.s.IndexShardTests  ] [testIndexCheckOnStartup] after test
05:23:59 FAILURE 0.25s J3 | IndexShardTests.testIndexCheckOnStartup <<< FAILURES!
05:23:59    > Throwable #1: junit.framework.AssertionFailedError: Expected exception IndexShardRecoveryException but no exception was thrown
05:23:59    > 	at __randomizedtesting.SeedInfo.seed([714504A126B124F7:70E3D1082C37E62F]:0)
05:23:59    > 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2693)
05:23:59    > 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2678)
05:23:59    > 	at org.elasticsearch.index.shard.IndexShardTests.testIndexCheckOnStartup(IndexShardTests.java:2673)
05:23:59    > 	at java.lang.Thread.run(Thread.java:748)
```
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/34/consoleFull

**Comment by jpountz** [comment]
@vladimirdolzhenko can you have a look?

**Comment by vladimirdolzhenko** [comment]
@jpountz sure
