### ISSUE TITLE
AbstractScalaEsScalaSparkSQL.testEsDataFrame3WriteDecimalType fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#33982]
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch-hadoop+6.4+periodic/10/console

Couldn't find a Reproduce line in the logs so far, but the failure looks like:

```
06:45:10     [2018-09-24T04:40:28,674][ERROR][org.apache.spark.executor.Executor] Exception in task 0.0 in stage 9132.0 (TID 9332)
06:45:10     org.elasticsearch.hadoop.serialization.EsHadoopSerializationException: Decimal types are not supported by Elasticsearch - consider using a different type (such as string)
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.writePrimitive(DataFrameValueWriter.scala:178) ~[main/:?]
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:104) ~[main/:?]
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$writeStruct$1.apply(DataFrameValueWriter.scala:83) ~[main/:?]
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$writeStruct$1.apply(DataFrameValueWriter.scala:78) ~[main/:?]
06:45:10     	at scala.collection.Iterator$class.foreach(Iterator.scala:891) ~[scala-library-2.11.12.jar:?]
06:45:10     	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334) ~[scala-library-2.11.12.jar:?]
06:45:10     	at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44) ~[scala-library-2.11.12.jar:?]
06:45:10     	at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37) ~[scala-library-2.11.12.jar:?]
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.writeStruct(DataFrameValueWriter.scala:78) ~[main/:?]
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:70) ~[main/:?]
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:53) ~[main/:?]
06:45:10     	at org.elasticsearch.hadoop.serialization.builder.ContentBuilder.value(ContentBuilder.java:53) ~[elasticsearch-hadoop-mr-6.4.2-SNAPSHOT.jar:6.4.2-SNAPSHOT]
06:45:10     	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.doWriteObject(TemplatedBulk.java:71) ~[elasticsearch-hadoop-mr-6.4.2-SNAPSHOT.jar:6.4.2-SNAPSHOT]
06:45:10     	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:58) ~[elasticsearch-hadoop-mr-6.4.2-SNAPSHOT.jar:6.4.2-SNAPSHOT]
06:45:10     	at org.elasticsearch.hadoop.serialization.bulk.BulkEntryWriter.writeBulkEntry(BulkEntryWriter.java:68) ~[elasticsearch-hadoop-mr-6.4.2-SNAPSHOT.jar:6.4.2-SNAPSHOT]
06:45:10     	at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:170) ~[elasticsearch-hadoop-mr-6.4.2-SNAPSHOT.jar:6.4.2-SNAPSHOT]
06:45:10     	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:67) ~[main/:?]
06:45:10     	at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101) ~[main/:?]
06:45:10     	at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101) ~[main/:?]
06:45:10     	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87) ~[spark-core_2.11-2.3.0.jar:2.3.0]
06:45:10     	at org.apache.spark.scheduler.Task.run(Task.scala:109) ~[spark-core_2.11-2.3.0.jar:2.3.0]
06:45:10     	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345) [spark-core_2.11-2.3.0.jar:2.3.0]
06:45:10     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
06:45:10     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
06:45:10     	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
06:45:10     [2018-09-24T04:40:28,676][WARN ][org.apache.spark.scheduler.TaskSetManager] Lost task 0.0 in stage 9132.0 (TID 9332, localhost, executor driver): org.elasticsearch.hadoop.serialization.EsHadoopSerializationException: Decimal types are not supported by Elasticsearch - consider using a different type (such as string)
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.writePrimitive(DataFrameValueWriter.scala:178)
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:104)
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$writeStruct$1.apply(DataFrameValueWriter.scala:83)
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$writeStruct$1.apply(DataFrameValueWriter.scala:78)
06:45:10     	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
06:45:10     	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
06:45:10     	at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44)
06:45:10     	at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37)
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.writeStruct(DataFrameValueWriter.scala:78)
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:70)
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:53)
06:45:10     	at org.elasticsearch.hadoop.serialization.builder.ContentBuilder.value(ContentBuilder.java:53)
06:45:10     	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.doWriteObject(TemplatedBulk.java:71)
06:45:10     	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:58)
06:45:10     	at org.elasticsearch.hadoop.serialization.bulk.BulkEntryWriter.writeBulkEntry(BulkEntryWriter.java:68)
06:45:10     	at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:170)
06:45:10     	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:67)
06:45:10     	at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101)
06:45:10     	at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101)
06:45:10     	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
06:45:10     	at org.apache.spark.scheduler.Task.run(Task.scala:109)
06:45:10     	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
06:45:10     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
06:45:10     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
06:45:10     	at java.lang.Thread.run(Thread.java:748)
06:45:10 
```

**Comment by cbuescher** [comment]
@jbaiera could you take a look

**Comment by cbuescher** [comment]
I moved this to https://github.com/elastic/elasticsearch-hadoop/issues/1193
