### ISSUE TITLE
[CI] Failure in InternalTopHitsTests#testReduceRandom

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#33993]
Built: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/16/console

Reproduces with:
```
./gradlew :server:test \
  -Dtests.seed=6B8570B9A843D345 \
  -Dtests.class=org.elasticsearch.search.aggregations.metrics.InternalTopHitsTests \
  -Dtests.method="testReduceRandom" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-IE \
  -Dtests.timezone=Asia/Bahrain \
  -Dcompiler.java=10 \
  -Druntime.java=8
```

Failure:
```
java.lang.AssertionError: Didn't match expected value:
                          hits: 
                            hits: same [empty list]
                       max_score: expected [null] but was [1.4E-45]
                           total: same [483783]

	at __randomizedtesting.SeedInfo.seed([6B8570B9A843D345:ABB8DCA88E1E4A13]:0)
	at org.elasticsearch.test.ESTestCase.assertEqualsWithErrorMessageFromXContent(ESTestCase.java:1245)
	at org.elasticsearch.search.aggregations.metrics.InternalTopHitsTests.assertReduced(InternalTopHitsTests.java:203)
```

**Comment by cbuescher** [comment]
First failure of this kind in a while, I assume it fails on this very specific seed, so not muting it right now, but please do if you see this again.
