### ISSUE TITLE
[CI] SSL setup fails in tests

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#33998]
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=opensuse/20/consoleFull

Couldn't reproduce this, with several local runs yet:
```
./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=8F67CB2DAC5BD0EE \
  -Dtests.class=org.elasticsearch.integration.ShrinkIndexWithSecurityTests \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=Etc/UTC \
  -Dcompiler.java=10 \
  -Druntime.java=8
```

The failure appears to be happening already at test setup time:
```
14:48:55   2> WARNING: Uncaught exception in thread: Thread[elasticsearch[node_sm2][generic][T#4],5,TGRP-ShrinkIndexWithSecurityTests]
14:48:55   2> java.lang.AssertionError: Must have SslHandler
14:48:55   1> [2018-09-24T03:48:54,584][INFO ][o.e.n.Node               ] [suite] stopped
14:48:55   1> [2018-09-24T03:48:54,585][INFO ][o.e.n.Node               ] [suite] closing ...
14:48:55   1> [2018-09-24T03:48:54,586][INFO ][o.e.n.Node               ] [suite] closed
14:48:55   1> [2018-09-24T03:48:54,631][INFO ][o.e.n.Node               ] [suite] stopping ...
14:48:55   2> 	at __randomizedtesting.SeedInfo.seed([8F67CB2DAC5BD0EE]:0)
14:48:55   2> 	at org.elasticsearch.xpack.security.transport.SSLEngineUtils.getSSLEngine(SSLEngineUtils.java:62)
14:48:55   2> 	at org.elasticsearch.xpack.security.transport.SSLEngineUtils.extractClientCertificates(SSLEngineUtils.java:39)
14:48:55   2> 	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.inbound(ServerTransportFilter.java:113)
14:48:55   2> 	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:307)
14:48:55   2> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63)
14:48:55   2> 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1448)
14:48:55   2> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723)
14:48:55   2> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
14:48:55   2> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:48:55   2> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

**Comment by jasontedor** [comment]
@tbrooks8 Can you look at this one as a networking issue?

**Comment by danielmitterdorfer** [comment]
We have the same failure (but in a different test) in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8,nodes=virtual&&linux/58/consoleFull:

```
08:01:45   2> WARNING: Uncaught exception in thread: Thread[elasticsearch[node_tm2][generic][T#2],5,TGRP-AuditTrailSettingsUpdateTests]
08:01:45   2> java.lang.AssertionError: Must have SslHandler
08:01:45   2> 	at __randomizedtesting.SeedInfo.seed([EC493D28E6D8B77E]:0)
08:01:45   2> 	at org.elasticsearch.xpack.security.transport.SSLEngineUtils.getSSLEngine(SSLEngineUtils.java:62)
08:01:45   2> 	at org.elasticsearch.xpack.security.transport.SSLEngineUtils.extractClientCertificates(SSLEngineUtils.java:39)
08:01:45   2> 	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.inbound(ServerTransportFilter.java:113)
08:01:45   2> 	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:307)
08:01:45   2> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63)
08:01:45   2> 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1448)
08:01:45   2> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723)
08:01:45   2> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
08:01:45   2> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
```

Reproduction line:

```
./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=EC493D28E6D8B77E \
  -Dtests.class=org.elasticsearch.xpack.security.audit.logfile.AuditTrailSettingsUpdateTests \
  -Dtests.method="testDynamicRequestBodySettings" \
  -Dtests.security.manager=true \
  -Dtests.locale=is \
  -Dtests.timezone=America/Dawson \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Does not reproduce locally (I tested 100 iterations).
