### ISSUE TITLE
[Test] MovAvgIT#testBadModelParams needs clarification

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#34046]
Currently the "testBadModelParams" method does seem to pass regardless of whether bad
model parameters are used or not. My guess is that its supposed to be testing that an exception is 
thrown if you provide invalid model parameters. From a conversation with @colings86 we think that
the padding parameter passed in ensure the alpha and beta values are invalid, but that seems to be
trappy because if the randomness selects simple or linear models the padding isn’t used and the model 
will be valid. I will @AwaitsFix the test in the course of https://github.com/elastic/elasticsearch/pull/31876
where I stumbled into it, but create this issue for further investigation.

**Comment by cbuescher** [comment]
Another MovAvgIT test (testHoltWintersNotEnoughData) fails for a similar reason:

```
./gradlew :server:integTest -Dtests.seed=CE15410BFF4D8B8A -Dtests.class=org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgIT -Dtests.method="testHoltWintersNotEnoughData" -Dtests.security.manager=true -Dtests.locale=fi -Dtests.timezone=JST -Dcompiler.java=10 -Druntime.java=8
```
```
FAILURE 0.39s | MovAvgIT.testHoltWintersNotEnoughData <<< FAILURES!
   > Throwable #1: junit.framework.AssertionFailedError: Expected exception SearchPhaseExecutionException but no exception was thrown
   >    at __randomizedtesting.SeedInfo.seed([CE15410BFF4D8B8A:A5C013FEF4A98B75]:0)
   >    at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2687)
   >    at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2672)
   >    at org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgIT.testHoltWintersNotEnoughData(MovAvgIT.java:856)
   >    at java.lang.Thread.run(Thread.java:748)
```

I think this needs a similar treatment like the issue mentioned above. The test it muted now as well, would be good to clean this up in one go.
