### ISSUE TITLE
[CI] SplitIndexIT failing on Windows

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#34080]
The last couple of master branch builds on Windows have both failed in SplitIndexIT:

* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/23/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/24/console

The underlying errors are all "access denied" errors on the mock file system, for example:

```
11:57:23   1> java.io.IOException: could not remove the following files (in the order of attempts):
11:57:23   1>    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\server\build\testrun\integTest\J1\temp\org.elasticsearch.action.admin.indices.create.ShrinkIndexIT_405F969E6898DB55-001\tempDir-002\data\nodes\4\indices\B7bnisfXSMyFJxC9q7WYIw\1\index\_1.cfs: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\server\build\testrun\integTest\J1\temp\org.elasticsearch.action.admin.indices.create.ShrinkIndexIT_405F969E6898DB55-001\tempDir-002\data\nodes\4\indices\B7bnisfXSMyFJxC9q7WYIw\1\index\_1.cfs
11:57:23   1>    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\server\build\testrun\integTest\J1\temp\org.elasticsearch.action.admin.indices.create.ShrinkIndexIT_405F969E6898DB55-001\tempDir-002\data\nodes\4\indices\B7bnisfXSMyFJxC9q7WYIw\1\index\_0.fdt: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\server\build\testrun\integTest\J1\temp\org.elasticsearch.action.admin.indices.create.ShrinkIndexIT_405F969E6898DB55-001\tempDir-002\data\nodes\4\indices\B7bnisfXSMyFJxC9q7WYIw\1\index\_0.fdt
```

```
00:02:41   1> Caused by: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\server\build\testrun\integTest\J2\temp\org.elasticsearch.routing.PartitionedRoutingIT_5A9F10A979AB2913-001\tempDir-002\data\nodes\2\indices\KiXyWWFtR-eDKkRq7WbiQQ\0\index\recovery.2djnkuBpQRaGON-ebaigZg._0.cfs -> C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\server\build\testrun\integTest\J2\temp\org.elasticsearch.routing.PartitionedRoutingIT_5A9F10A979AB2913-001\tempDir-002\data\nodes\2\indices\KiXyWWFtR-eDKkRq7WbiQQ\0\index\_0.cfs
00:02:41 
00:02:41   1> 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83) ~[?:?]
00:02:41 
00:02:41   1> 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[?:?]
00:02:41 
00:02:41   1> 	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301) ~[?:?]
00:02:41 
00:02:41   1> 	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287) ~[?:?]
00:02:41 
00:02:41   1> 	at org.apache.lucene.mockfile.FilterFileSystemProvider.move(FilterFileSystemProvider.java:147) ~[lucene-test-framework-8.0.0-snapshot-7d0a7782fa.jar:8.0.0-snapshot-7d0a7782fa 7d0a7782fa7e99250bccfb4d3e995485c3f0ca19 - jimczi - 2018-09-18 14:02:40]
```

This feels like something similar to #30416 which was fixed by #30571, but maybe something changed in Lucene 8 that means the fix needs to be updated?

**Comment by droberts195** [comment]
Some repro commands are:

```
./gradlew :server:integTest \
  -Dtests.seed=405F969E6898DB55 \
  -Dtests.class=org.elasticsearch.action.admin.indices.create.SplitIndexIT \
  -Dtests.method="testSplitFromOneToN" \
  -Dtests.security.manager=true \
  -Dtests.locale=fr-FR \
  -Dtests.timezone=Europe/Astrakhan \
  -Dcompiler.java=10 \
  -Druntime.java=8

./gradlew :server:integTest \
  -Dtests.seed=405F969E6898DB55 \
  -Dtests.class=org.elasticsearch.action.admin.indices.create.ShrinkIndexIT \
  -Dtests.method="testCreateShrinkIndexToN" \
  -Dtests.security.manager=true \
  -Dtests.locale=nl \
  -Dtests.timezone=IST \
  -Dcompiler.java=10 \
  -Druntime.java=8
```

**Comment by droberts195** [comment]
I muted `SplitIndexIT.testSplitFromOneToN` and `ShrinkIndexIT.testCreateShrinkIndexToN` on Windows only in 1413ace74f82ad22ec9f2ad74645faa85d5a2f25

**Comment by s1monw** [comment]
I am pretty sure this is entirely unrelated to the referenced PRs and issues. This seems to be an infra issue and a duplicate of https://github.com/elastic/elasticsearch/issues/33857 @droberts195 WDYT?
