### ISSUE TITLE
[CI] MovAvgIT.testHoltWintersNotEnoughData

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#34098]
Fails reproducibly and likely caused by #31876 I will mute the test

```
./gradlew :server:integTest -Dtests.seed=CE15410BFF4D8B8A -Dtests.class=org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgIT -Dtests.method="testHoltWintersNotEnoughData" -Dtests.security.manager=true -Dtests.locale=fi -Dtests.timezone=JST -Dcompiler.java=10 -Druntime.java=8
```

```
2> REPRODUCE WITH: ./gradlew :server:integTest -Dtests.seed=CE15410BFF4D8B8A -Dtests.class=org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgIT -Dtests.method="testHoltWintersNotEnoughData" -Dtests.security.manager=true -Dtests.locale=fi -Dtests.timezone=JST -Dcompiler.java=10 -Druntime.java=8
FAILURE 0.39s | MovAvgIT.testHoltWintersNotEnoughData <<< FAILURES!
   > Throwable #1: junit.framework.AssertionFailedError: Expected exception SearchPhaseExecutionException but no exception was thrown
   >    at __randomizedtesting.SeedInfo.seed([CE15410BFF4D8B8A:A5C013FEF4A98B75]:0)
   >    at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2687)
   >    at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2672)
   >    at org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgIT.testHoltWintersNotEnoughData(MovAvgIT.java:856)
   >    at java.lang.Thread.run(Thread.java:748)
```

**Comment by cbuescher** [comment]
@s1monw thanks, this should have been muted in the commit as well (the test was already borked but didn't throw the exception that we get now). Somehow this slipped CI due to lucky randomization. This is probably best handled as part of https://github.com/elastic/elasticsearch/issues/34046 since it is a similar issue. I will close this in favour of https://github.com/elastic/elasticsearch/issues/34046 and update the @AwaitsFix accordingly.
