### ISSUE TITLE
[CI] InternalEngineTests.testOutOfOrderDocsOnReplicaOldPrimary

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#34110]
Fails reproducibly
`
REPRODUCE WITH: gradlew :server:test -Dtests.seed=1863D78D1D8C8B5F -Dtests.class=org.elasticsearch.index.engine.InternalEngineTests -Dtests.method="testOutOfOrderDocsOnReplicaOldPrimary" -Dtests.security.manager=true -Dtests.locale=nl-BE -Dtests.timezone=Asia/Kashgar -Dcompiler.java=10 -Druntime.java=8
`
```
FAILURE 1.63s | InternalEngineTests.testOutOfOrderDocsOnReplicaOldPrimary <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: id=_id:[fe 1f] seq_no=10 msu=-1
   >    at __randomizedtesting.SeedInfo.seed([1863D78D1D8C8B5F:4AC0F0E6A26075A0]:0)
   >    at org.elasticsearch.index.engine.InternalEngine.assertMaxSeqNoOfUpdatesIsAdvanced(InternalEngine.java:2660)
   >    at org.elasticsearch.index.engine.InternalEngine.indexIntoLucene(InternalEngine.java:1045)
   >    at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:877)
   >    at org.elasticsearch.index.engine.InternalTestEngine.index(InternalTestEngine.java:57)
   >    at org.elasticsearch.index.engine.EngineTestCase.assertOpsOnReplica(EngineTestCase.java:709)
   >    at org.elasticsearch.index.engine.InternalEngineTests.testOutOfOrderDocsOnReplicaOldPrimary(InternalEngineTests.java:1641)
   >    at java.lang.Thread.run(Thread.java:748)
```

CI link here:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java8,nodes=virtual&&linux/26/console

**Comment by dnhatn** [comment]
This is fixed by f6100419fe51fc325dcad494525145acb2460015.
