### ISSUE TITLE
[HLRC] GetPipelineResponse.isFound() is useless

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#34119]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.1

I wanted to test the existence of an ingest pipeline with:

```java
return client.ingest().getPipeline(new GetPipelineRequest(pipelineName), RequestOptions.DEFAULT).isFound();
```

This sadly does not work when the pipeline does not exist as an `ElasticsearchStatusException` is thrown instead:

```
ElasticsearchStatusException[Unable to parse response body
]; nested: ResponseException[method [GET], host [http://localhost:9200], URI [/_ingest/pipeline/fscrawler_elasticsearch_client_i_t_test_pipeline_foo?master_timeout=30s], status line [HTTP/1.1 404 Not Found]
{}]; nested: ResponseException[method [GET], host [http://localhost:9200], URI [/_ingest/pipeline/fscrawler_elasticsearch_client_i_t_test_pipeline_foo?master_timeout=30s], status line [HTTP/1.1 404 Not Found]
{}];
	at __randomizedtesting.SeedInfo.seed([15212568BCF52185:5EB9DA33ECB6D90F]:0)
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1386)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1269)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1231)
	at org.elasticsearch.client.IngestClient.getPipeline(IngestClient.java:85)
	at fr.pilato.elasticsearch.crawler.fs.client.v6.ElasticsearchClientV6.isExistingPipeline(ElasticsearchClientV6.java:231)
	at fr.pilato.elasticsearch.crawler.fs.test.integration.ElasticsearchClientIT.testPipeline(ElasticsearchClientIT.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1737)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:934)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:970)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:943)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:829)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:879)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:890)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.IllegalStateException: Failed to parse elasticsearch status exception: no exception was found
		at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:174)
		at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1406)
		at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1382)
		... 25 more
Caused by: org.elasticsearch.client.ResponseException: method [GET], host [http://localhost:9200], URI [/_ingest/pipeline/fscrawler_elasticsearch_client_i_t_test_pipeline_foo?master_timeout=30s], status line [HTTP/1.1 404 Not Found]
{}
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:920)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:227)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1256)
	... 24 more
Caused by: org.elasticsearch.client.ResponseException: method [GET], host [http://localhost:9200], URI [/_ingest/pipeline/fscrawler_elasticsearch_client_i_t_test_pipeline_foo?master_timeout=30s], status line [HTTP/1.1 404 Not Found]
{}
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:540)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:529)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	... 1 more
```

To work around this, I need to write:

```java
        try {
            return client.ingest().getPipeline(new GetPipelineRequest(pipelineName), RequestOptions.DEFAULT).isFound();
        } catch (ElasticsearchStatusException e) {
            if (e.status().getStatus() == 404) {
                return false;
            }
            throw new IOException(e);
        }
```

If this is the expected behavior, may be we should document it in the REST documentation?

**Comment by javanna** [comment]
this looks like a bug to me, like other CRUD api, get pipeline should be configured to not throw exception when 404 is returned, rather return a valid response which returns a proper `isFound()` flag.

**Comment by benwtrent** [comment]
Code fix has been merged and back ported. Should be available in 6.4.3
