### ISSUE TITLE
RangeQueryBuilderTests testToQuery  fails with Use of short timezone id deprecated

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#34188]
RangeQueryBuilderTests testToQuery  fails on 6.x 

The failure reproduces on my local machine

Log https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/33/console  

gradlew :server:test \
  -Dtests.seed=E8DA5AFE04722E5B \
  -Dtests.class=org.elasticsearch.index.query.RangeQueryBuilderTests \
  -Dtests.method="testToQuery" \
  -Dtests.security.manager=true \
  -Dtests.locale=ru-RU \
  -Dtests.timezone=Libya \
  -Dcompiler.java=10 \
  -Druntime.java=8

**Comment by mayya-sharipova** [comment]
The problem is related to the recent conversion fro joda to java date.
Attaching stack here:

```
java.lang.AssertionError: unexpected warning headers expected null, but was:<[299 Elasticsearch-6.5.0-SNAPSHOT-Unknown "Use of short timezone id MST is deprecated. Use -07:00 instead" "Sun, 30 Sep 2018 18:22:14 GMT"]>
	at __randomizedtesting.SeedInfo.seed([E8DA5AFE04722E5B:1F2158C075F1EBB1]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at org.elasticsearch.test.ESTestCase.ensureNoWarnings(ESTestCase.java:377)
	at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:355)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jtibshirani** [comment]
@rjernst I went to go unmute the test (https://github.com/elastic/elasticsearch/blob/master/test/framework/src/main/java/org/elasticsearch/test/AbstractQueryTestCase.java#L416) and noticed that the same repro command fails on master.

**Comment by rjernst** [comment]
My PR didn't quite fix it. See this followup https://github.com/elastic/elasticsearch/pull/35145

**Comment by davidkyle** [comment]
Reopening due to a failure on 6.5. Was the fix backported?

```
./gradlew :server:test \
  -Dtests.seed=DFE8975EF5515367 \
  -Dtests.class=org.elasticsearch.index.query.RangeQueryBuilderTests \
  -Dtests.method="testToQuery" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-AR \
  -Dtests.timezone=America/Belem \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

```
java.lang.AssertionError: unexpected warning headers expected null, but was:<[299 Elasticsearch-6.5.0-SNAPSHOT-Unknown "Use of short timezone id HST is deprecated. Use -10:00 instead" "Fri, 02 Nov 2018 15:22:30 GMT"]>
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.5+intake/36/console
