### ISSUE TITLE
[CI] SSLServiceTests failed once, not reproducible

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#34227]
The following failure was only observed once, but might be worth looking at in more depth:

https://internal-ci.elastic.co/job/elastic+x-pack-elasticsearch+5.6+multijob-unix-compatibility/117/consoleText

Logs show:

```
  1> [2018-10-01T19:14:19,065][INFO ][o.e.x.s.SSLServiceTests  ] [testThatSSLIOSessionStrategyWithoutSettingsWorks]: before test
  2> تشرين الأول 01, 2018 7:15:18 م com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
  2> WARNING: Uncaught exception in thread: Thread[I/O dispatcher 10,5,TGRP-SSLServiceTests]
  2> java.lang.AssertionError: 
  2> Expected: a value less than <300>
  2>      but: <504> was greater than <300>
  2> 	at __randomizedtesting.SeedInfo.seed([A93623303C47001C]:0)
  2> 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
  1> [2018-10-01T19:15:18,655][INFO ][o.e.x.s.SSLServiceTests  ] [testThatSSLIOSessionStrategyWithoutSettingsWorks]: after test
  2> 	at org.junit.Assert.assertThat(Assert.java:956)
  2> 	at org.junit.Assert.assertThat(Assert.java:923)
  2> 	at org.elasticsearch.xpack.ssl.SSLServiceTests$AssertionCallback.completed(SSLServiceTests.java:520)
  2> 	at org.elasticsearch.xpack.ssl.SSLServiceTests$AssertionCallback.completed(SSLServiceTests.java:516)
  2> 	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
  2> 	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
  2> 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
  2> 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
  2> 	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
  2> 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
  2> 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
  2> 	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
  2> 	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
  2> 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
  2> 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
  2> 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
  2> 	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
  2> 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
  2> 	at java.lang.Thread.run(Thread.java:748)
```

Subsequent builds with the same commit succeeded.

**Reproduction line**:

`./gradlew :x-pack-elasticsearch:plugin:test -Dtests.seed=A93623303C47001C -Dtests.class=org.elasticsearch.xpack.ssl.SSLServiceTests -Dtests.network=true -Dtests.method="testThatSSLIOSessionStrategyWithoutSettingsWorks" -Dtests.security.manager=true -Dtests.locale=ar-LB -Dtests.timezone=America/Marigot`

I have been **unable** to reproduce this (using java-10) with 100 iterations:

```
./gradlew :x-pack-elasticsearch:plugin:test -Dtests.iters=100 -Dtests.seed=A93623303C47001C -Dtests.class=org.elasticsearch.xpack.ssl.SSLServiceTests -Dtests.network=true -Dtests.method="testThatSSLIOSessionStrategyWithoutSettingsWorks" -Dtests.security.manager=true -Dtests.locale=ar-LB -Dtests.timezone=America/Marigot
```

**Comment by danielmitterdorfer** [comment]
This test tries to hit https://elastic.co/ and at the time the test ran there seemed to be an issue with the website as it returned HTTP 504 instead of 2xx. Therefore, closing as this was related to an external event.
