### ISSUE TITLE
Version 6.4.2 does not start (java.lang.NoSuchFieldError: LOG_DEFAULT_LEVEL_SETTING)

### ISSUE THREAD

**Issue by najamansari** [elastic/elasticsearch#34303]
**Elasticsearch version**: 6.4.2

**Plugins installed**: None

**JVM version**: openjdk version "10.0.2" 2018-07-17

**OS version**: Fedora 28 (4.18.9-200.fc28.x86_64 #1 SMP Thu Sep 20 02:43:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)

**Description of the problem including expected versus actual behavior**:
I upgraded from ElasticSearch version 6.2.0 to 6.4.2 using the RPM package. After the installation, when I tried restarting ES, it didn't work. Checking the system logs (via `journalctl`), I found the following exception:

```
Exception in thread "main" java.lang.NoSuchFieldError: LOG_DEFAULT_LEVEL_SETTING
        at org.elasticsearch.common.logging.LogConfigurator.configureLoggerLevels(LogConfigurator.java:180)
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:165)
        at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:119)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:294)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86)
```

I've tried this with both the "OSS" and "basic" versions. The error also occurs if I attempt a clean installation.

**Steps to reproduce**:

 1. Download ElasticSearch 6.4.2 RPM (https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.2.rpm)
 2. Install the RPM: `sudo dnf install elasticsearch-6.4.2.rpm`
 3. Watch system logs (`journalctl -f`) while starting ES (`sudo systemctl start elasticsearch`), the stack trace given above is generated

Relevant section of logs given above.

**Comment by jasontedor** [comment]
I am sorry that you're having trouble with this.

The field that is referenced here *definitely* exists in 6.4.2: https://github.com/elastic/elasticsearch/blob/04711c21227efda954d15c23857ad04b9f669076/server/src/main/java/org/elasticsearch/common/logging/Loggers.java#L50-L51

I think that something is wrong with your installation. I think this because I have no issues starting Elasticsearch 6.4.2 installed from the RPM.

```
fedora-28:~$ sudo rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
fedora-28:~$ sudo vi /etc/yum.repos.d/elasticsearch.repo
fedora-28:~$ sudo dnf install elasticsearch
Elasticsearch repository for 6.x packages                                                                               21 MB/s | 6.5 MB     00:00    
Last metadata expiration check: 0:00:01 ago on Thu 04 Oct 2018 10:25:27 PM UTC.
Dependencies resolved.
=======================================================================================================================================================
 Package                               Arch                           Version                          Repository                                 Size
=======================================================================================================================================================
Installing:
 elasticsearch                         noarch                         6.4.2-1                          elasticsearch-6.x                          93 M

Transaction Summary
=======================================================================================================================================================
Install  1 Package

Total download size: 93 M
Installed size: 144 M
Is this ok [y/N]: y
Downloading Packages:
elasticsearch-6.4.2.rpm                                                                                                 50 MB/s |  93 MB     00:01    
-------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                   50 MB/s |  93 MB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                               1/1 
  Running scriptlet: elasticsearch-6.4.2-1.noarch                                                                                                  1/1 
Creating elasticsearch group... OK
Creating elasticsearch user... OK
  Installing       : elasticsearch-6.4.2-1.noarch                                                                                                  1/1 
  Running scriptlet: elasticsearch-6.4.2-1.noarch                                                                                                  1/1 
### NOT starting on installation, please execute the following statements to configure elasticsearch service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable elasticsearch.service
### You can start elasticsearch service by executing
 sudo systemctl start elasticsearch.service
Created elasticsearch keystore in /etc/elasticsearch
  Verifying        : elasticsearch-6.4.2-1.noarch                                                                                                  1/1 

Installed:
  elasticsearch.noarch 6.4.2-1                                                                                                                         

Complete!
fedora-28:~$ sudo systemctl start elasticsearch
fedora-28:~$ curl -XGET localhost:9200/?pretty=true
{
  "name" : "GLnn01t",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "M_L_7QvtStyPYpr2OTeP8w",
  "version" : {
    "number" : "6.4.2",
    "build_flavor" : "default",
    "build_type" : "rpm",
    "build_hash" : "04711c2",
    "build_date" : "2018-09-26T13:34:09.098244Z",
    "build_snapshot" : false,
    "lucene_version" : "7.4.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
fedora-28:~$ 
```

And, we have packaging tests on Fedora 28 to this effect as well.

That is, I think this is an environmental issue and not a bug.

I would be happy to help you try to debug this, but we reserve GitHub for verified bug reports and feature requests, preferring to use the [forums](https://discuss.elastic.co) for troubleshooting user issues. We can always come back here if we find out there that there is indeed a bug.

If you open a topic on the forum, you can link to it from here and either someone from the community will help you, or I will try to.

**Comment by najamansari** [comment]
Hi Jason,

Thanks for taking a look, I'll open up a thread on the forum.

**Comment by najamansari** [comment]
Hi Jason,

Thanks for taking a look, I'll open up a thread on the forum.
