### ISSUE TITLE
Unexpected ResponseException ("document_already_exists_exception")

### ISSUE THREAD

**Issue by gugumonster** [elastic/elasticsearch#34320]
**Elasticsearch version**: 2.0.1

{
  "version" : {
    "number" : "2.0.1",
    "build_hash" : "1ebe2f1ab149d45b08d5336b12eb14eb8a3814af",
    "build_timestamp" : "2015-11-18T17:42:23Z",
    "build_snapshot" : false,
    "lucene_version" : "5.2.1"
  },
  "tagline" : "You Know, for Search"
}

**JVM version**: Java 8 update 162 (8.0.1620.12)

**OS version**: Windows Server 2012 R2 Standard

**Description of the problem including expected versus actual behavior**:

Hello,

we are using Elasticsearch 2.0.1 and access it via the Java REST API in version 5.5.0 (org.elasticsearch.client:rest). We experienced the following problem (which happened so far only twice and without being able to reproduce it):

When attempting to create a document in an index we receive a org.elasticsearch.client.ResponseException, with the reason that the document already exists (status code 409).

Full stack trace:
`org.elasticsearch.client.ResponseException: POST http://ESSERVER:9200/lx-ad-phonebook/LXContact/5c9f6b96-f52a-4321-bf30-823e28cd5ae0/_create: HTTP/1.1 409 Conflict
{"error":{"root_cause":[{"type":"document_already_exists_exception","reason":"[LXContact][5c9f6b96-f52a-4321-bf30-823e28cd5ae0]: document already exists","shard":"1","index":"lx-ad-phonebook"}],"type":"document_already_exists_exception","reason":"[LXContact][5c9f6b96-f52a-4321-bf30-823e28cd5ae0]: document already exists","shard":"1","index":"lx-ad-phonebook"},"status":409}
at org.elasticsearch.client.RestClient$1.completed(RestClient.java:354)
at org.elasticsearch.client.RestClient$1.completed(RestClient.java:343)
at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
at java.lang.Thread.run(Thread.java:748)
Suppressed: java.net.SocketTimeoutException
at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:375)
at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92)
at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39)
at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:263)
at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:492)
at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:213)
at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
... 3 more`

When looking into the index, we also see the very same document we actually wanted to create (same ID, same payload properties).
So at first it looks like an issue on our side and that Elasticsearch is behaving correctly, but our client is the only client accessing the index and whenver a document is supposed to be created, we generate a UUID for it (via `java.util.UUID.randomUUID().toString()`).
While we know that there is a theoretical chance that this UUID generation could result in generating the same ID twice, we highly doubt that this is the case (also because it appeared for a second time now within 3 days; and the payload data would most likely differ as well on the second creation).

Our assumption here is that either the Java REST API or the Elasticsearch server behave incorrect here.
Could it be that (in some rare situations) the Java REST API attempts to insert a document twice or simply the server returns this error although the document could be created successfully?
Is this a known issue in general?

Best regards!

**Comment by javanna** [comment]
hi @gugumonster , can you reproduce this or is it a one-off type of error? How many nodes is the REST client pointing to?

**Comment by ywelsch** [comment]
This is possible when sending the request to a node, and then the connection drops (or the node fails) upon which the client retries the request, running in the above situation. The (suppressed) `java.net.SocketTimeoutException` in the above stacktrace indicates that there indeed was an issue with the original request, and that this request got retried. As the request you're using is not idempotent, you're running into the above error message.

**Comment by gugumonster** [comment]
We use 2 nodes and couldn't reproduce this, but the answer from @ywelsch makes sense and fits our attached stack trace.
Thank you for your answers!

**Comment by javanna** [comment]
thanks for getting back to us @gugumonster , the fact that you are using more than one node confirms that retries come into place, which could be seen also from the stacktrace as Yannick mentioned.
