### ISSUE TITLE
SQL query failed with in nested array.

### ISSUE THREAD

**Issue by spinwang** [elastic/elasticsearch#34403]
**Elasticsearch version** (`6.4.0 docker image`)

**Steps to reproduce**:
```
PUT test
PUT test/_mapping/_doc
{
  "properties": {
      "data": {
        "properties": {
          "results": {
          "type": "nested",
          "properties": {
            "barcode": {
              "type": "keyword",
              "fields": {
                "text": {
                  "type": "text"
                }
              }
            },
            "metric": {
              "type": "keyword",
              "fields": {
                "text": {
                  "type": "text"
                }
              }
            },
            "modifier": {
              "type": "keyword",
              "fields": {
                "text": {
                  "type": "text"
                }
              }
            },
            "unit": {
              "type": "keyword",
              "fields": {
                "text": {
                  "type": "text"
                }
              }
            },
            "value": {
              "type": "double",
              "fields": {
                "keyword": {
                  "type": "keyword"
                },
                "text": {
                  "type": "text"
                }
              },
              "ignore_malformed": true
            }
          }
        }
      }
    }
  }
}
```
```
PUT test/_doc/1
{
  "fileId":"1",
  "data":{
    "study":{"name":"M","number":"4","start_date":"2018-04-28","end_date":"2018-05-02","source":"A"},
    "assay":{"sub_type":"M"},
    "results":[{
      "barcode": "01",
      "metric":"m",
      "value":0.9235,
      "modifier":">",
      "unit":"n"
    },{
      "barcode":"01",
      "metric":"n",
      "value":75.591,
      "modifier":">",
      "unit":"min"
    }]
  }
}
```
```
POST /_xpack/sql?format=csv
{
  "query": "SELECT data.results.* FROM test"
}
```
**Provide logs (if relevant)**:
Error message
```JSON
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": null
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "Partial shards failure",
    "phase": "fetch",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 3,
        "index": "test",
        "node": "RxLQEIJNTSiz2Wfua1z8Mw",
        "reason": {
          "type": "null_pointer_exception",
          "reason": null
        }
      }
    ]
  },
  "status": 500
}
```

Elasticsearch log
```
elasticsearch_1  | [2018-10-11T15:48:24,117][WARN ][r.suppressed             ] path: /_xpack/sql, params: {format=csv}
elasticsearch_1  | org.elasticsearch.action.search.SearchPhaseExecutionException: Partial shards failure
elasticsearch_1  |      at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:293) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:145) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:205) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$2(FetchSearchPhase.java:104) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.action.search.CountedCollector.countDown(CountedCollector.java:53) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.action.search.CountedCollector.onFailure(CountedCollector.java:76) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.action.search.FetchSearchPhase$2.onFailure(FetchSearchPhase.java:172) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:526) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1068) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1165) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1149) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:66) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.onFailure(SecurityServerTransportInterceptor.java:242) [x-pack-security-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:309) [x-pack-security-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:665) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
elasticsearch_1  |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
elasticsearch_1  |      at java.lang.Thread.run(Thread.java:844) [?:?]
elasticsearch_1  | Caused by: org.elasticsearch.ElasticsearchException$1
elasticsearch_1  |      at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:657) ~[elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.action.search.SearchPhaseExecutionException.guessRootCauses(SearchPhaseExecutionException.java:170) ~[elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.action.search.SearchPhaseExecutionException.getCause(SearchPhaseExecutionException.java:111) ~[elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:139) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:122) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:351) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:64) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.layout.PatternLayout$PatternSerializer.toSerializable(PatternLayout.java:334) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:233) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:218) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:58) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:177) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:464) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:448) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:431) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146) [log4j-core-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.spi.ExtendedLoggerWrapper.logMessage(ExtendedLoggerWrapper.java:217) [log4j-api-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.elasticsearch.common.logging.PrefixLogger.logMessage(PrefixLogger.java:103) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2170) [log4j-api-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2125) [log4j-api-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2108) [log4j-api-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1997) [log4j-api-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1859) [log4j-api-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.apache.logging.log4j.spi.AbstractLogger.warn(AbstractLogger.java:2644) [log4j-api-2.11.1.jar:2.11.1]
elasticsearch_1  |      at org.elasticsearch.rest.BytesRestResponse.build(BytesRestResponse.java:133) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:96) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:91) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:58) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:91) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:68) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.onFailure(Querier.java:441) [x-pack-sql-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:91) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.action.search.AbstractSearchAsyncAction.raisePhaseFailure(AbstractSearchAsyncAction.java:233) [elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      ... 25 more
elasticsearch_1  | Caused by: java.lang.NullPointerException
elasticsearch_1  |      at org.elasticsearch.search.fetch.FetchPhase.createNestedSearchHit(FetchPhase.java:282) ~[elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:147) ~[elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.search.fetch.subphase.InnerHitsFetchSubPhase.hitsExecute(InnerHitsFetchSubPhase.java:69) ~[elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:165) ~[elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:516) ~[elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.action.search.SearchTransportService$11.messageReceived(SearchTransportService.java:439) ~[elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.action.search.SearchTransportService$11.messageReceived(SearchTransportService.java:436) ~[elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:251) ~[?:?]
elasticsearch_1  |      at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.4.0.jar:6.4.0]
elasticsearch_1  |      ... 10 more
```

**Comment by astefan** [comment]
There are high chances this issue is the same as https://github.com/elastic/elasticsearch/issues/32941

**Comment by spinwang** [comment]
@astefan thanks! Do you know if there is any resolution for this?

**Comment by astefan** [comment]
I've tested your scenario in 7.0 and it doesn't reproduce. I've asked in https://github.com/elastic/elasticsearch/issues/32941 for the 7.x fix to be backported to 6.5 if possible. If the fix makes it in 6.5.0 I would suggest testing again in that version. I'll do the test myself as well.

**Comment by spinwang** [comment]
@astefan thanks! Look forward to hearing back about this.

**Comment by astefan** [comment]
@spinwang The backporting happened and I tested your scenario on 6.5 branch and it doesn't reproduce anymore. I'll go ahead and close this one now. Thank you for taking SQL for a spin and we are looking forward to more successful tests from your side.
