### ISSUE TITLE
[CI] FollowIndexIT failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#34443]
Test fails verifying whether ccr monitoring docs have been indexed.

```
FAILURE 12.5s | FollowIndexIT.testFollowIndex <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: a value equal to or greater than <1>
   >      but: <0> was less than <1>
   > 	at __randomizedtesting.SeedInfo.seed([161686B51A49BEB4:F57A498723F1873E]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.xpack.ccr.FollowIndexIT.verifyCcrMonitoring(FollowIndexIT.java:221)
   > 	at org.elasticsearch.xpack.ccr.FollowIndexIT.lambda$testFollowIndex$2(FollowIndexIT.java:82)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:848)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:822)
   > 	at org.elasticsearch.xpack.ccr.FollowIndexIT.testFollowIndex(FollowIndexIT.java:82)
   > 	at java.lang.Thread.run(Thread.java:748)
```

This test failure does not reproduce. 

Build urls:
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/46

**Comment by martijnvg** [comment]
This hasn't been failing for a while now, so I'm closing it for now. If this failure re-occurs then we can re-open this issue.
