### ISSUE TITLE
Missing /proc/diskstats file

### ISSUE THREAD

**Issue by acarstoiu** [elastic/elasticsearch#34450]
**Elasticsearch version**: 5.6.11

**Plugins installed**: []

**JVM version**: 1.8.0_181

**OS version**: RHEL 7 on OpenVZ

**Steps to reproduce**:
Every 30s, Elasticsearch outputs this in its log:

```
2018-10-15T13:51:21,276][DEBUG][o.e.m.f.FsProbe          ] [d603ff5ac6] unexpected exception processing /proc/diskstats for devices [Tuple [v1=144, v2=21]]
java.nio.file.NoSuchFileException: /proc/diskstats
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:?]
        at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_181]
        at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_181]
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_181]
        at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_181]
        at java.nio.file.Files.newBufferedReader(Files.java:2784) ~[?:1.8.0_181]
        at java.nio.file.Files.readAllLines(Files.java:3202) ~[?:1.8.0_181]
        at java.nio.file.Files.readAllLines(Files.java:3242) ~[?:1.8.0_181]
        at org.elasticsearch.monitor.fs.FsProbe.readProcDiskStats(FsProbe.java:126) ~[elasticsearch-5.6.11.jar:5.6.11]
        at org.elasticsearch.monitor.fs.FsProbe.ioStats(FsProbe.java:85) [elasticsearch-5.6.11.jar:5.6.11]
        at org.elasticsearch.monitor.fs.FsProbe.stats(FsProbe.java:68) [elasticsearch-5.6.11.jar:5.6.11]
        at org.elasticsearch.monitor.fs.FsService.stats(FsService.java:60) [elasticsearch-5.6.11.jar:5.6.11]
        at org.elasticsearch.monitor.fs.FsService.access$200(FsService.java:33) [elasticsearch-5.6.11.jar:5.6.11]
        at org.elasticsearch.monitor.fs.FsService$FsInfoCache.refresh(FsService.java:78) [elasticsearch-5.6.11.jar:5.6.11]
        at org.elasticsearch.monitor.fs.FsService$FsInfoCache.refresh(FsService.java:67) [elasticsearch-5.6.11.jar:5.6.11]
        at org.elasticsearch.common.util.SingleObjectCache.getOrRefresh(SingleObjectCache.java:54) [elasticsearch-5.6.11.jar:5.6.11]
        at org.elasticsearch.monitor.fs.FsService.stats(FsService.java:55) [elasticsearch-5.6.11.jar:5.6.11]
        at org.elasticsearch.node.NodeService.stats(NodeService.java:110) [elasticsearch-5.6.11.jar:5.6.11]
        at org.elasticsearch.action.admin.cluster.node.stats.TransportNodesStatsAction.nodeOperation(TransportNodesStatsAction.java:77) [elasticsearch-5.6.11.jar:5.6.11]
        at org.elasticsearch.action.admin.cluster.node.stats.TransportNodesStatsAction.nodeOperation(TransportNodesStatsAction.java:42) [elasticsearch-5.6.11.jar:5.6.11]
        at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:140) [elasticsearch-5.6.11.jar:5.6.11]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:262) [elasticsearch-5.6.11.jar:5.6.11]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:258) [elasticsearch-5.6.11.jar:5.6.11]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) [elasticsearch-5.6.11.jar:5.6.11]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:662) [elasticsearch-5.6.11.jar:5.6.11]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:675) [elasticsearch-5.6.11.jar:5.6.11]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.11.jar:5.6.11]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```
Ok, it's a known problem caused by the virtualization environment and apparently Elasticsearch can work just fine without these kernel stats. Therefore, can we have some configuration flag that tells Elasticsearch to just give up collecting these stats twice every minute?
If there already is such a flag, please point me to it (didn't show up at search). Thanks.

**Comment by spinscale** [comment]
As we neither test nor support OpenVZ at the moment,  we will not invest too much time in this ourselves. Sorry for this!

However in this particular case, you could potentially just reduce the logging for the `org.elasticsearch.monitor.fs` to `INFO` level and you would be good to go as the above message is on `DEBUG` level.

I will close this issue and would like to ask you to open a new topic in the [Elasticsearch discussion forum](https://discuss.elastic.co/c/elasticsearch) for further topics. Thanks a lot!
