### ISSUE TITLE
SSLTrustRestrictionsTests fail on cleanup

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#34502]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/63 has failed during cleanup with:

```
23:55:07 ERROR   0.00s J2 | SSLTrustRestrictionsTests (suite) <<< FAILURES!
23:55:07    > Throwable #1: java.io.IOException: Could not remove the following files (in the order of attempts):
23:55:07    >    /private/var/lib/jenkins/workspace/elastic+elasticsearch+6.x+multijob-darwin-compatibility/x-pack/plugin/security/build/testrun/test/J2/temp/org.elasticsearch.xpack.ssl.SSLTrustRestrictionsTests_4568FAB59B696BBA-001/tempDir-003/trust_restrictions.yml: java.io.IOException: access denied: /private/var/lib/jenkins/workspace/elastic+elasticsearch+6.x+multijob-darwin-compatibility/x-pack/plugin/security/build/testrun/test/J2/temp/org.elasticsearch.xpack.ssl.SSLTrustRestrictionsTests_4568FAB59B696BBA-001/tempDir-003/trust_restrictions.yml
23:55:07    >    /private/var/lib/jenkins/workspace/elastic+elasticsearch+6.x+multijob-darwin-compatibility/x-pack/plugin/security/build/testrun/test/J2/temp/org.elasticsearch.xpack.ssl.SSLTrustRestrictionsTests_4568FAB59B696BBA-001/tempDir-003: java.nio.file.DirectoryNotEmptyException: /private/var/lib/jenkins/workspace/elastic+elasticsearch+6.x+multijob-darwin-compatibility/x-pack/plugin/security/build/testrun/test/J2/temp/org.elasticsearch.xpack.ssl.SSLTrustRestrictionsTests_4568FAB59B696BBA-001/tempDir-003
23:55:07    >    /private/var/lib/jenkins/workspace/elastic+elasticsearch+6.x+multijob-darwin-compatibility/x-pack/plugin/security/build/testrun/test/J2/temp/org.elasticsearch.xpack.ssl.SSLTrustRestrictionsTests_4568FAB59B696BBA-001: java.nio.file.DirectoryNotEmptyException: /private/var/lib/jenkins/workspace/elastic+elasticsearch+6.x+multijob-darwin-compatibility/x-pack/plugin/security/build/testrun/test/J2/temp/org.elasticsearch.xpack.ssl.SSLTrustRestrictionsTests_4568FAB59B696BBA-001
23:55:07    > 	at __randomizedtesting.SeedInfo.seed([4568FAB59B696BBA]:0)
23:55:07    > 	at org.apache.lucene.util.IOUtils.rm(IOUtils.java:318)
23:55:07    > 	at java.lang.Thread.run(Thread.java:748)
23:55:07 Completed [89/195] on J2 in 3.05s, 3 tests, 1 error <<< FAILURES!
```

All output before that looks expected to me but for completeness, I am attaching the [complete log snippet for this test suite](https://github.com/elastic/elasticsearch/files/2481658/SSLTrustRestrictionsTests_full_log.txt).

What's noticeable: This build failed on MacOS 10.13.3. I wonder whether some lingering thread holds onto the file `trust_restrictions.yml` and at this point I am not sure whether this is a problem specific to this test or whether this is a general problem on MacOS 10.13 which uses [APFS](https://en.wikipedia.org/wiki/Apple_File_System).

**Comment by jaymode** [comment]
@tvernum can you take a look?
