### ISSUE TITLE
[CI] SSLException: Received close_notify during handshake

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#34514]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+multijob-windows-compatibility/64/consoleFull has failed with:

```
12:42:32   1> io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received close_notify during handshake
12:42:32   1> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-codec-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
12:42:32   1> Caused by: javax.net.ssl.SSLException: Received close_notify during handshake
12:42:32   1> 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[?:?]
12:42:32   1> 	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[?:?]
12:42:32   1> 	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[?:?]
12:42:32   1> 	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1776) ~[?:?]
12:42:32   1> 	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083) ~[?:?]
12:42:32   1> 	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[?:?]
12:42:32   1> 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:?]
12:42:32   1> 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_181]
12:42:32   1> 	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:281) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1215) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1127) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162) ~[netty-handler-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.16.Final.jar:4.1.16.Final]
12:42:32   1> 	... 15 more
```

reproduction line of the build above with build id `20181016071459-6169C3F9 (does not reproduce locally):

```
gradlew :x-pack:qa:tribe-tests-with-security:test \
  -Dtests.seed=E96200A29197A00B \
  -Dtests.class=org.elasticsearch.xpack.security.SecurityTribeTests \
  -Dtests.security.manager=true \
  -Dtests.locale=de-LU \
  -Dtests.timezone=Australia/Tasmania
```

reproduction line of build id `20181008232140-2FF07565 (does not reproduce locally): 

```
./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=103C6D419C2C4438 \
  -Dtests.class=org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests \
  -Dtests.method="testSendRandomRequests" \
  -Dtests.security.manager=true \
  -Dtests.locale=sq \
  -Dtests.timezone=MST7MDT \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

reproduction line of build id `20181007194343-B582AB07` (does not reproduce locally):

``` 
/gradlew :x-pack:qa:tribe-tests-with-security:test \
  -Dtests.seed=E256452AFB8FDE46 \
  -Dtests.class=org.elasticsearch.xpack.security.SecurityTribeTests \
  -Dtests.method="testRetrieveRolesOnTribeNode" \
  -Dtests.security.manager=true \
  -Dtests.locale=lv-LV \
  -Dtests.timezone=Africa/Nouakchott
``` 

So far we have the following build ids that failed with this error:

| build id                | JDK version | OS / Distro    | branch | 
|-------------------------|-------------|----------------|--------| 
| 20181016071459-6169C3F9 | 10+46       | Windows 2012   | 6.4    | 
| 20181010113501-73ECBC82 | 10+46       | Oracle Linux 7 | 6.4    | 
| 20181008232140-2FF07565 | 8           | Ubuntu 16.04   | master | 
| 20181007194343-B582AB07 | 10+46       | CentOS 7       | 6.4    | 

This exception is raised when a sender sends `close_notify` to the recipient to indicate it will not send
 any more messages on this connection (see also [RFC5246](https://tools.ietf.org/html/rfc5246#section-7.2.1)). The question is why this happens during the SSL handshake.
 
I wonder whether this could be caused by a similar issue in Netty as addressed in https://github.com/elastic/elasticsearch/pull/30337 although I did not find anything related in recent Netty tickets. From the mix of failures on different operating systems I think we can rule out the OS.

**Comment by tbrooks8** [comment]
I don't understand why this exception would cause the build to fail? This is exception should fine in some circumstances. If we decide to close a channel during a handshake, we will send close_notify. That generates an exception on the other side. But that exception should be handleable (to a same extent that a normal network exception in handleable). I *think* the only reason it should lead the build to fail is if it inhibits some expected operation.

The linked CI failure is not available to me to explore further.

**Comment by original-brownbear** [comment]
I think we can remove the `7.0.0` label here, the tests in question aren't in `master` anymore?

**Comment by jaymode** [comment]
Given the apparent lack of a new occurrence of this issue and the build logs are no longer available, I am going to close this issue as we cannot really take an action at this point.

**Comment by jtibshirani** [comment]
I'm going to re-open this, because another build just failed with the same issue. I uploaded the build log
to help with the investigation.

Reproduction line:
```
./gradlew :x-pack:plugin:security:unitTest \
  -Dtests.seed=58A5B0016A16883C \
  -Dtests.class=org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests \
  -Dtests.method="testTcpHandshake" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-NZ \
  -Dtests.timezone=Etc/GMT+12 \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

The stacktrace in the original issue description was logged at WARN. Here is the subsequent ERROR line in the logs:
```
1> [2019-01-25T07:24:00,527][ERROR][i.n.u.c.D.rejectedExecution] [org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests] Failed to submit a listener notification task. Event loop shut down?
  1> java.util.concurrent.RejectedExecutionException: event executor terminated
  1> 	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:867) ~[netty-common-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328) ~[netty-common-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321) ~[netty-common-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:778) ~[netty-common-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:768) [netty-common-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432) [netty-common-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:112) [netty-common-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:89) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1017) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:825) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
```

Build log file: [ssl-failure.txt](https://github.com/elastic/elasticsearch/files/2797645/ssl-failure.txt)

**Comment by jaymode** [comment]
Also failed a little over a week ago, https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1975/console. @tbrooks8 any thoughts on what's going on in these tests?

**Comment by jaymode** [comment]
I came across a similar failure where one of these tests fail, https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/617/console. In this case, the tls handshake times out after 10 seconds:

```
 1> [2019-03-18T19:05:29,411][WARN ][o.e.t.OutboundHandler    ] [TS_B] send message failed [channel: Netty4TcpChannel{localAddress=0.0.0.0/0.0.0.0:54902, remoteAddress=/127.0.0.1:42523}]
  1> javax.net.ssl.SSLException: handshake timed out
  1> 	at io.netty.handler.ssl.SslHandler.handshake(...)(Unknown Source) ~[netty-handler-4.1.32.Final.jar:4.1.32.Final]
  1> [2019-03-18T19:05:29,449][WARN ][o.e.t.TcpTransport       ] [TS_A] exception caught on transport layer [Netty4TcpChannel{localAddress=0.0.0.0/0.0.0.0:42523, remoteAddress=/127.0.0.1:55028}], closing connection
  1> io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received close_notify during handshake
  1> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472) ~[netty-codec-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-codec-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [netty-common-4.1.32.Final.jar:4.1.32.Final]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
  1> Caused by: javax.net.ssl.SSLException: Received close_notify during handshake
  1> 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[?:?]
  1> 	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1647) ~[?:?]
  1> 	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1615) ~[?:?]
  1> 	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1757) ~[?:?]
  1> 	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1070) ~[?:?]
  1> 	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:896) ~[?:?]
  1> 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:766) ~[?:?]
  1> 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_202]
  1> 	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:295) ~[netty-handler-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1301) ~[netty-handler-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1203) ~[netty-handler-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247) ~[netty-handler-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.32.Final.jar:4.1.32.Final]
  1> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-codec-4.1.32.Final.jar:4.1.32.Final]
  1> 	... 15 more
  1> [2019-03-18T19:05:29,637][INFO ][o.e.x.s.t.n.SimpleSecurityNetty4ServerTransportTests] [testVersionFrom0to1] after test
ERROR   13.8s J7 | SimpleSecurityNetty4ServerTransportTests.testVersionFrom0to1 <<< FAILURES!
   > Throwable #1: ConnectTransportException[[TS_A][127.0.0.1:42523] general node connection failure]; nested: TransportException[handshake failed because connection reset];
   > 	at __randomizedtesting.SeedInfo.seed([ABF380092BBE0CE3:180C00A44B516A8E]:0)
   > 	at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener$1.onFailure(TcpTransport.java:1282)
   > 	at org.elasticsearch.transport.TransportHandshaker$HandshakeResponseHandler.handleLocalException(TransportHandshaker.java:155)
   > 	at org.elasticsearch.transport.TransportHandshaker.lambda$sendHandshake$0(TransportHandshaker.java:67)
   > 	at org.elasticsearch.action.ActionListener.lambda$wrap$0(ActionListener.java:84)
   > 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)
   > 	at org.elasticsearch.action.ActionListener.lambda$toBiConsumer$3(ActionListener.java:112)
   > 	at org.elasticsearch.common.concurrent.CompletableContext.lambda$addListener$0(CompletableContext.java:39)
   > 	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
   > 	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
   > 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
   > 	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
   > 	at org.elasticsearch.common.concurrent.CompletableContext.complete(CompletableContext.java:61)
   > 	at org.elasticsearch.transport.netty4.Netty4TcpChannel.lambda$new$0(Netty4TcpChannel.java:51)
   > 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
   > 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
   > 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
   > 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
   > 	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
   > 	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
   > 	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1152)
   > 	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:768)
   > 	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:744)
   > 	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:615)
   > 	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1376)
   > 	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:624)
   > 	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:608)
   > 	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:465)
   > 	at io.netty.handler.ssl.SslUtils.handleHandshakeFailure(SslUtils.java:350)
   > 	at io.netty.handler.ssl.SslHandler$5.run(SslHandler.java:1782)
   > 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
   > 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
   > 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
   > 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
```

This did not reproduce locally.

```
./gradlew :x-pack:plugin:security:unitTest \
  -Dtests.seed=ABF380092BBE0CE3 \
  -Dtests.class=org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests \
  -Dtests.method="testVersionFrom0to1" \
  -Dtests.security.manager=true \
  -Dtests.locale=pl \
  -Dtests.timezone=CAT \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

@tbrooks8 @original-brownbear any thoughts?

**Comment by tbrooks8** [comment]
As I've mentioned in the past I think the name of this issue does not describe the reason for the failure. A `close_notify` during a handshake should be fine which is why we recently stopped logging that at warn level (although if it is a suppressed exception we will still see it depending on the top-level exception). I am in agreement that the SSL handshake timed-out after 10 seconds (based on the logs). That is the default configuration for netty ssl handshakes (10 seconds).

We do not currently have a timeout for nio SSL handshakes (just the 30 second total connection setup timeout). I guess I would be interested if we ever see the `SimpleSecurityNioTransportTests` fail due to timeout?

I guess there are two theories immediately:

1. Is there an occasionally circumstance in CI where 10 seconds is too short and the handshake times out?
2. Is there a rare bug in the netty `SslHandler` where the handshake does not progress leading to a timeout? 

Both of those would describe a world where `SimpleSecurityNetty4ServerTransportTests` occasionally fails but `SimpleSecurityNioTransportTests` does not.

**Comment by original-brownbear** [comment]
@tbrooks8 @jaymode it looks like the last failure with this `close_notify` exception was on Mar. 21st, maybe we can close this? If my memory serves me correctly, we did fix a few performance issues with CI at the end of March so maybe @tbrooks8 's theory `1` was correct here (obviously it could be a million other things :))?

**Comment by tbrooks8** [comment]
Yeah I think we should close it. @jaymode ?

**Comment by jaymode** [comment]
Agree on closing.
