### ISSUE TITLE
SQL: CASTing from two columns throws error

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#34542]
```
sql> SELECT CAST((CAST(languages AS BIT) OR CAST(salary AS BIT)) AS INT) FROM test_emp;
Server error [Server encountered an error [Unresolved input - needs resolving first]. [SqlIllegalArgumentException[Unresolved input - needs resolving first]
        at org.elasticsearch.xpack.sql.expression.gen.pipeline.CommonNonExecutableInput.asProcessor(CommonNonExecutableInput.java:25)
        at org.elasticsearch.xpack.sql.expression.gen.pipeline.UnaryPipe.asProcessor(UnaryPipe.java:59)
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseAggActionListener.createExtractor(Querier.java:286)
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseAggActionListener.initBucketExtractors(Querier.java:257)
        at org.elasticsearch.xpack.sql.execution.search.Querier$ImplicitGroupActionListener.handleBuckets(Querier.java:177)
        at org.elasticsearch.xpack.sql.execution.search.Querier$ImplicitGroupActionListener.handleResponse(Querier.java:170)
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.onResponse(Querier.java:406)
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.onResponse(Querier.java:382)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:66)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:62)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onResponse(AbstractSearchAsyncAction.java:313)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onResponse(AbstractSearchAsyncAction.java:50)
        at org.elasticsearch.action.search.FetchSearchPhase$3.run(FetchSearchPhase.java:212)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:160)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:153)
        at org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:119)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:160)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:153)
        at org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:205)
        at org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$2(FetchSearchPhase.java:104)
        at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:110)
        at org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:44)
        at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:86)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
]]
```

**Comment by matriv** [comment]
Cannot reproduce. Probably resolved by: #34573
