### ISSUE TITLE
SQL: Cannot use NOT in SELECT clause when table columns are used.

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#34558]
`SELECT NOT emp_no = 1 FROM test_emp`  throws:
```
java.sql.SQLException: Server encountered an error [Not supported yet]. [SqlIllegalArgumentException[Not supported yet]
	at org.elasticsearch.xpack.sql.expression.predicate.Not.asScript(Not.java:58)
	at org.elasticsearch.xpack.sql.expression.function.scalar.ScalarFunction.toAttribute(ScalarFunction.java:38)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldProject.rule(QueryFolder.java:140)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldProject.rule(QueryFolder.java:106)
```

but it works if everything is a literal: `SELECT NOT 1 > 2`

Need to implement `asScript` and `makePipe` in `Not` unary scalar function.

**Comment by costin** [comment]
This has been addressed by #34848
