### ISSUE TITLE
SQL: selecting a constant and a grouped value doesn't currently work

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#34583]
At the moment something like
```
select 1, max(salary) from test_emp;
select 1, count(*) from test_emp group by gender;
```
will throw an error:

```
Server error [Server encountered an error [Schema [1:integer,MAX(salary):integer] and values [74999.0] are out of sync]. [SqlIllegalArgumentException[Schema [1:integer,MAX(salary):integer] and values [74999.0] are out of sync]
        at org.elasticsearch.xpack.sql.util.Check.isTrue(Check.java:18)
        at org.elasticsearch.xpack.sql.session.Rows.singleton(Rows.java:47)
        at org.elasticsearch.xpack.sql.execution.search.Querier$ImplicitGroupActionListener.handleBuckets(Querier.java:182)
        at org.elasticsearch.xpack.sql.execution.search.Querier$ImplicitGroupActionListener.handleResponse(Querier.java:163)
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.onResponse(Querier.java:406)
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.onResponse(Querier.java:382)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:66)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:62)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onResponse(AbstractSearchAsyncAction.java:313)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onResponse(AbstractSearchAsyncAction.java:50)
```

This issue has been spun off from https://github.com/elastic/elasticsearch/issues/31863

**Comment by matriv** [comment]
Those issues have been fixed.
