### ISSUE TITLE
SQL: CASTing `text` fields that also have a keyword sub-field will not use the sub-field

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#34608]
```
sql> select cast(first_name as varchar) from test_emp where cast(first_name as varchar)='alejandro' limit 5;
Server error [Server sent bad type [search_phase_execution_exception]. Original type was [all shards failed]. [Failed to execute phase [query], all shards failed; shardFailures {[1xf7J15UQ6-6Eagq0pzBBg][test_emp][0]: RemoteTransportException[[node-0][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: ScriptException[runtime error]; nested: IllegalArgumentException[Fielddata is disabled on text fields by default. Set fielddata=true on [first_name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.]; }
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:293)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:133)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:254)
        at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:106)
```

This is not necessarily a bug, more of an improvement. We are using the same approach in some of the string functions, where in Painless scripts we use the `exactAttribute()` value.

**Comment by matriv** [comment]
This seems to be fixed:
```
select cast(first_name as varchar) from test_emp where cast(first_name as varchar)='Alejandro';
```
gives:
```
cast(first_name as varchar)
---------------------------
Alejandro                  
```
and
```
select cast(first_name as varchar) from test_emp where cast(first_name as varchar)='alejandro' limit 5;
```
gives:
```
cast(first_name as varchar)
---------------------------
```
