### ISSUE TITLE
[TEST] Settings version check tripping in BWC tests

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#34602]
Relates to #34566

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+default-distro-bwc-tests/1/console

```
[2018-10-16T23:43:48,540][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-3] fatal error in thread [elasticsearch[node-3][clusterApplierService#updateTask][T#1]], exiting
23:44:20 java.lang.AssertionError: null
23:44:20 	at org.elasticsearch.index.IndexService.updateMetaData(IndexService.java:633) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
23:44:20 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.updateIndices(IndicesClusterStateService.java:491) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
23:44:20 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:226) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
23:44:20 	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$6(ClusterApplierService.java:478) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
23:44:20 	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
...
```

**Comment by jasontedor** [comment]
This build is from before #34566 being integrated and I believe is addressed by that PR. I will close this issue; we can reopen if this is not the case.
