### ISSUE TITLE
[TEST] DeprecatedLoggingAuditTrailTests failing on 6.x

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#34627]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/12/console

Output:

```
java.lang.AssertionError: unexpected warning headers expected null, but was:<[299 Elasticsearch-6.5.0-SNAPSHOT-1ff55f4 "[xpack.security.audit.logfile.prefix.emit_node_host_address] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version." "Thu, 18 Oct 2018 14:36:29 GMT", 299 Elasticsearch-6.5.0-SNAPSHOT-1ff55f4 "[xpack.security.audit.logfile.prefix.emit_node_host_name] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version." "Thu, 18 Oct 2018 14:36:29 GMT", 299 Elasticsearch-6.5.0-SNAPSHOT-1ff55f4 "[xpack.security.audit.logfile.prefix.emit_node_name] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version." "Thu, 18 Oct 2018 14:36:29 GMT"]>
	at __randomizedtesting.SeedInfo.seed([BAC761BB535D285F:44117AB72C278C35]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at org.elasticsearch.test.ESTestCase.ensureNoWarnings(ESTestCase.java:377)
	at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:355)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

Probably relates to https://github.com/elastic/elasticsearch/pull/34475

**Comment by ywelsch** [comment]
I've pushed 06230bde6f7 to mute these tests.

**Comment by albertzaharovits** [comment]
Thank you @ywelsch .
> Probably relates to #34475

You are right. I have pushed 6cf8a40 to fix it.
