### ISSUE TITLE
[TEST] GetUserPrivilegesResponseTests#testSerialization failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#34631]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/6/consoleText

reproducible with

```
./gradlew :x-pack:plugin:core:test -Dtests.seed=8BE719D19FE47313 -Dtests.class=org.elasticsearch.xpack.core.security.action.user.GetUserPrivilegesResponseTests -Dtests.method="testSerialization" -Dtests.security.manager=true -Dtests.locale=ar-LB -Dtests.timezone=America/Barbados -Dcompiler.java=11 -Druntime.java=8
```

Output:

```
 > Throwable #1: java.lang.AssertionError: 
   > Expected: <[Indices[indices=[WcqW], privileges=[Hds,QTq,hLl,lNp,xEH], fls=[FieldGrantExcludeGroup[grant=ivGEE,WcTrK; exclude=MWcXa,DQtqw,JIEkB]], dls=[lfsOPF,WpVNsS,BqroZz]], Indices[indices=[jIfp,uEId], privileges=[CCoSBJ,FVBtoY,YbyPNM], dls=[bQdpY]], Indices[indices=[ABx,SDJ,hkw,jmb,sbU,tyg], privileges=[CQXYXl,CRLZqD,UGGTPw,XWpoVR,odyXeC,qonneq,zJTkeG], fls=[FieldGrantExcludeGroup[grant=PUoiv; exclude=YMmTL,yIToL]], dls=[JokC]], Indices[indices=[AlUyc,ExxmV,FdpWZ,PovBz,ZobJo,smAqE], privileges=[PtB,QHd], fls=[FieldGrantExcludeGroup[grant=Eprlk; exclude=Kbkfu,RxBFX]], dls=[DRyXMG,KOUQKH,KxbYmM]]]>
   >      but: was <[Indices[indices=[WcqW], privileges=[hLl,xEH,Hds,QTq,lNp], fls=[FieldGrantExcludeGroup[grant=ivGEE,WcTrK; exclude=MWcXa,DQtqw,JIEkB]], dls=[WpVNsS,lfsOPF,BqroZz]], Indices[indices=[jIfp,uEId], privileges=[CCoSBJ,FVBtoY,YbyPNM], dls=[bQdpY]], Indices[indices=[AlUyc,ExxmV,ZobJo,FdpWZ,PovBz,smAqE], privileges=[QHd,PtB], fls=[FieldGrantExcludeGroup[grant=Eprlk; exclude=Kbkfu,RxBFX]], dls=[KOUQKH,DRyXMG,KxbYmM]], Indices[indices=[SDJ,tyg,hkw,jmb,ABx,sbU], privileges=[CQXYXl,zJTkeG,odyXeC,UGGTPw,XWpoVR,qonneq,CRLZqD], fls=[FieldGrantExcludeGroup[grant=PUoiv; exclude=YMmTL,yIToL]], dls=[JokC]]]>
   > 	at __randomizedtesting.SeedInfo.seed([8BE719D19FE47313:DF3F7899B8B64E8F]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.xpack.core.security.action.user.GetUserPrivilegesResponseTests.testSerialization(GetUserPrivilegesResponseTests.java:58)
   > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by albertzaharovits** [comment]
FYI @tvernum when backporting https://github.com/elastic/elasticsearch/pull/33928
