### ISSUE TITLE
RollupIndexerIndexingTests#testRandomizedDateHisto fails with assertion error.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#34762]
The failure reliably reproduces for me locally on master and 6.x. We've also seen CI failures on 6.4 (that might require a different set of parameters to reproduce).

---

Link to the build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/8/console

Command to reproduce: 
```
 ./gradlew :x-pack:plugin:rollup:test \
  -Dtests.seed=B8C2D1D7B200C9BB \
  -Dtests.class=org.elasticsearch.xpack.rollup.job.RollupIndexerIndexingTests \
  -Dtests.method="testRandomizedDateHisto" \
  -Dtests.security.manager=true \
  -Dtests.locale=fr-CA \
  -Dtests.timezone=Asia/Anadyr \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Relevant excerpt from the logs:
```
FAILURE 2.72s | RollupIndexerIndexingTests.testRandomizedDateHisto <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: a value greater than <0>
   >      but: <0> was equal to <0>
   >    at __randomizedtesting.SeedInfo.seed([B8C2D1D7B200C9BB:56314A37A321B66]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.xpack.rollup.job.RollupIndexerIndexingTests.lambda$testRandomizedDateHisto$6(RollupIndexerIndexingTests.java:443)
   >    at org.elasticsearch.xpack.rollup.job.RollupIndexerIndexingTests.executeTestCase(RollupIndexerIndexingTests.java:499)
   >    at org.elasticsearch.xpack.rollup.job.RollupIndexerIndexingTests.testRandomizedDateHisto(RollupIndexerIndexingTests.java:442)
   >    at java.lang.Thread.run(Thread.java:748)
```

**Comment by polyfractal** [comment]
Ah, I see it.  The random timestamps were landing too close to the current time, so an unlucky rollup interval would round such that the doc isn't included and the test fails.

Will push a fix to make sure the test docs are always within the search boundary.

**Comment by jtibshirani** [comment]
Forgot to comment earlier -- I muted the test in 90fd15bb563160e59b582f359e764aa99a966bc6.

**Comment by polyfractal** [comment]
This should be fixed... I just forgot to close the issue :)
