### ISSUE TITLE
CharArraysTests#testCharsBeginsWith fails with an assertion error.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#34765]
The failure reliably reproduces for me locally on master and 6.x.

---

Link to the build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/14/console

Command to reproduce: 
```
./gradlew :libs:core:test \
  -Dtests.seed=35653EB3A532F612 \
  -Dtests.class=org.elasticsearch.common.CharArraysTests \
  -Dtests.method="testCharsBeginsWith" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-DZ \
  -Dtests.timezone=Africa/Bujumbura \
  -Dcompiler.java=11 \
  -Druntime.java=11
```

Relevant excerpt from the logs:
```
FAILURE 0.39s | CharArraysTests.testCharsBeginsWith <<< FAILURES!
   > Throwable #1: java.lang.AssertionError
   >    at __randomizedtesting.SeedInfo.seed([35653EB3A532F612:78C0CECE95797639]:0)
   >    at org.elasticsearch.common.CharArraysTests.testCharsBeginsWith(CharArraysTests.java:50)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   >    at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by jtibshirani** [comment]
Muted the test in 5a4866f67d3aac0580cc3b1bc692af8e1b38a3be.
