### ISSUE TITLE
XPackIT#testCreateRollup fails because metric cannot be set on date field

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#34764]
Fails reliably on 6.x, and reproduces locally.  A recent failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+default-distro/21/console

```
./gradlew :qa:rolling-upgrade:v6.4.3-SNAPSHOT#bwcTest \
  -Dtests.seed=AE3FBBEC43E28A31 \
  -Dtests.class=org.elasticsearch.upgrades.XPackIT \
  -Dtests.method="testCreateRollup" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-SY \
  -Dtests.timezone=America/Juneau \
  -Dtests.distribution=zip \
  -Dcompiler.java=11 \
  -Druntime.java=8
```
```
{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[node-1][127.0.0.1:35046][cluster:admin/xpack/rollup/put]"}],"type":"illegal_argument_exception","reason":"Validation Failed: 1: The field referenced by a metric group must be a [numeric] type, but found [date] for field [timestamp];"},"status":400}
	at __randomizedtesting.SeedInfo.seed([AE3FBBEC43E28A31:B40A7BCC3BC7C969]:0)
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:926)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229)
	at org.elasticsearch.upgrades.XPackIT.testCreateRollup(XPackIT.java:244)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

I'm fairly sure this caused by #34379.  I think the request is going to an upgraded node so it gets the new defaults, but the master is still an old node so it fails the validation.

@benwtrent could you take a look?

I'm also going to mute the test.

**Comment by benwtrent** [comment]
@polyfractal yeah, I will take a gander. Maybe a goose as well.

**Comment by benwtrent** [comment]
This BWC issue should be corrected through the revert of the troubling commit. The new PR https://github.com/elastic/elasticsearch/pull/34831 will be part of 6.6. Since it takes the minimum node version into account, it should not have this issue.

**Comment by benwtrent** [comment]
https://github.com/elastic/elasticsearch/pull/34831 Has been closed and we have opted for a different solution to this problem. See PR for details.
