### ISSUE TITLE
NodeSubclassTests#testReplaceChildren fails with an assertion error.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#34775]
The failure reliably reproduces for me locally on master and 6.x.

---

Link to the build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=sles/14/console

Command to reproduce: 
```
./gradlew :x-pack:plugin:sql:test \
  -Dtests.seed=A14809E189F6E91E \
  -Dtests.class=org.elasticsearch.xpack.sql.tree.NodeSubclassTests \
  -Dtests.method="testReplaceChildren {p0=class org.elasticsearch.xpack.sql.expression.predicate.operator.comparison.InPipe}" \
  -Dtests.security.manager=true \
  -Dtests.locale=hr-HR \
  -Dtests.timezone=Europe/Oslo \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Relevant excerpt from the logs:
```
 <<< FAILURES!
   > Throwable #1: java.lang.IllegalArgumentException: expected at least [2] children but received [1]
   >    at __randomizedtesting.SeedInfo.seed([A14809E189F6E91E:98B7AAAC70F0C9E0]:0)
   >    at org.elasticsearch.xpack.sql.expression.predicate.operator.comparison.InPipe.replaceChildren(InPipe.java:33)
   >    at org.elasticsearch.xpack.sql.expression.predicate.operator.comparison.InPipe.replaceChildren(InPipe.java:21)
   >    at org.elasticsearch.xpack.sql.tree.NodeSubclassTests.testReplaceChildren(NodeSubclassTests.java:183)
   >    at java.lang.Thread.run(Thread.java:748)
```

**Comment by jtibshirani** [comment]
Muted the test in 1f42024243aa083d8b1cdb6827d7a691fae6d071.

**Comment by gwbrown** [comment]
I think this is a duplicate of https://github.com/elastic/elasticsearch/issues/34754

Thanks for muting the test!

**Comment by jtibshirani** [comment]
Thanks @gwbrown, I forgot to search through existing issues first! I'll close this out in favor of the existing one.
