### ISSUE TITLE
TribeClientYamlTestSuiteIT fails with a 'master not discovered' exception.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#34785]
This failure reliably reproduces for me locally on 6.x.

---

Link to the build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+default-distro/22/console

Command to reproduce:
```
./gradlew :qa:smoke-test-tribe-node:integTestRunner \
  -Dtests.seed=84307D98419C3703 \
  -Dtests.class=org.elasticsearch.tribe.TribeClientYamlTestSuiteIT \
  -Dtests.method="test {yaml=tribe/10_basic/Tribe node test}" \
  -Dtests.security.manager=true \
  -Dtests.locale=ga-IE \
  -Dtests.timezone=America/Maceio \
  -Dtests.distribution=zip \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Relevant excerpt from the logs:
```
ERROR   1.30s | TribeClientYamlTestSuiteIT.test {yaml=tribe/10_basic/Tribe node test} <<< FAILURES!
   > Throwable #1: org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:40200], URI [/_xpack/rollup/job/_all], status line [HTTP/1.1 503 Service Unavailable]
   > {"error":{"root_cause":[{"type":"master_not_discovered_exception","reason":"no known master nodes"}],"type":"master_not_discovered_exception","reason":"no known master nodes"},"status":503}
   >    at __randomizedtesting.SeedInfo.seed([84307D98419C3703:C644242EF605AFB]:0)
   >    at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:926)
   >    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229)
   >    at org.elasticsearch.test.rest.ESRestTestCase.wipeRollupJobs(ESRestTestCase.java:464)
   >    at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:389)
   >    at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:184)
   >    at java.lang.Thread.run(Thread.java:748)
   > Caused by: org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:40200], URI [/_xpack/rollup/job/_all], status line [HTTP/1.1 503 Service Unavailable]
   > {"error":{"root_cause":[{"type":"master_not_discovered_exception","reason":"no known master nodes"}],"type":"master_not_discovered_exception","reason":"no known master nodes"},"status":503}
   >    at org.elasticsearch.client.RestClient$1.completed(RestClient.java:546)
   >    at org.elasticsearch.client.RestClient$1.completed(RestClient.java:531)
   >    at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
   >    at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
   >    at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
   >    at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
   >    at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
   >    at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
   >    at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
   >    at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
   >    at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
   >    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
   >    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
   >    at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
   >    at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
   >    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
   >    ... 1 more
```

Full build log: [build_log.txt](https://github.com/elastic/elasticsearch/files/2508622/build_log.txt)

**Comment by jtibshirani** [comment]
After digging into this more, it looks closely related to https://github.com/elastic/elasticsearch/issues/34629. Please feel free to close if it'd be better to track everything there.

**Comment by nik9000** [comment]
I'll have a look and see if the fix for #34629 also fixes this.

**Comment by nik9000** [comment]
The fix for #34629 does not fix this, but the fix is in line with other changes to that file so I'll push it in a few minutes.

**Comment by nik9000** [comment]
Er, how about when I finish the backport I'm working on.

**Comment by nik9000** [comment]
Done! Thanks for pining me @jtibshirani!
