### ISSUE TITLE
[CI] IndexShardTests.testConcurrentTermIncreaseOnReplicaShard failed on 6.4

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#34862]
The test `IndexShardTests.testConcurrentTermIncreaseOnReplicaShard` failed today on the 6.4 branch:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+release-tests/25

with the error:
```
java.lang.IllegalArgumentException: unexpected mapping update
```

The test execution log is: 
[consoleText.txt](https://github.com/elastic/elasticsearch/files/2515360/consoleText.txt)

I can/can't reproduce the error using:
```
gradlew :server:test -Dtests.seed=934A6D0349D74193 -Dtests.class=org.elasticsearch.index.shard.IndexShardTests -Dtests.method="testConcurrentTermIncreaseOnReplicaShard" -Dtests.security.manager=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=ar -Dtests.timezone=ROK
```

**Comment by DaveCTurner** [comment]
I looked into this some more. I'm not sure the `unexpected mapping update` is the issue, because I also found this:

```
   > Throwable #1: java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).
   > 	at __randomizedtesting.SeedInfo.seed([934A6D0349D74193]:0)Throwable #2: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=1816, name=elasticsearch[org.elasticsearch.index.shard.IndexShardTests][index][T#1], state=RUNNABLE, group=TGRP-IndexShardTests]
   > Caused by: java.lang.AssertionError: 
   > Expected: <92L>
   >      but: was <93L>
   > 	at __randomizedtesting.SeedInfo.seed([934A6D0349D74193]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.index.shard.IndexShardTests$9.onResponse(IndexShardTests.java:1000)
   > 	at org.elasticsearch.index.shard.IndexShardTests$9.onResponse(IndexShardTests.java:996)
   > 	at org.elasticsearch.index.shard.IndexShard$3.onResponse(IndexShard.java:2357)
   > 	at org.elasticsearch.index.shard.IndexShard$3.onResponse(IndexShard.java:2337)
   > 	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)
   > 	at org.elasticsearch.index.shard.IndexShardOperationPermits$PermitAwareThreadedActionListener$1.doRun(IndexShardOperationPermits.java:378)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   > 	at java.lang.Thread.run(Thread.java:748)
```

The failing assertion is here:

https://github.com/elastic/elasticsearch/blob/5d0699b30f82bb410f3eb97c53efbd4e9b2a8fba/server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java#L1000

This might mean that the race fixed in #32442 is still present, or may be something else? @ywelsch do you have any thoughts?

Also I think we should release that `releasable` in a `finally` block rather than keeping hold of it and letting the suite time out when that assertion fails.
