### ISSUE TITLE
JdbcSqlSpecIT fails  filter.testWhereWithInAndNullHandling1 and  filter.testWhereWithInAndNullHandling2

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#35042]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=amazon/26/console

```
REPRODUCE WITH: ./gradlew :x-pack:qa:sql:no-security:integTestRunner \
  -Dtests.seed=8B0871DD2413BBC0 \
  -Dtests.class=org.elasticsearch.xpack.qa.sql.nosecurity.JdbcSqlSpecIT \
  -Dtests.method="test {filter.testWhereWithInAndNullHandling2}" \
  -Dtests.security.manager=true \
  -Dtests.locale=ca-ES \
  -Dtests.timezone=Africa/Monrovia \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :x-pack:qa:sql:no-security:integTestRunner \
  -Dtests.seed=8B0871DD2413BBC0 \
  -Dtests.class=org.elasticsearch.xpack.qa.sql.nosecurity.JdbcSqlSpecIT \
  -Dtests.method="test {filter.testWhereWithInAndNullHandling1}" \
  -Dtests.security.manager=true \
  -Dtests.locale=ca-ES \
  -Dtests.timezone=Africa/Monrovia \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Reproducible for me on `master`  with a following stack trace for `testWhereWithInAndNullHandling2`:

FAILURE 2.66s | JdbcSqlSpecIT.test {filter.testWhereWithInAndNullHandling2} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Elasticsearch [JdbcResultSet:row 1] still has data after [0] entries:
   > Brender
   >    at __randomizedtesting.SeedInfo.seed([8B0871DD2413BBC0:35C4E078AEFD638]:0)
   >    at org.elasticsearch.xpack.qa.sql.nosecurity.JdbcSqlSpecIT.filter.testWhereWithInAndNullHandling2(filter.sql-spec:106)
   >    at org.elasticsearch.xpack.qa.sql.jdbc.JdbcAssert.doAssertResultSetData(JdbcAssert.java:214)
   >    at org.elasticsearch.xpack.qa.sql.jdbc.JdbcAssert.assertResultSetData(JdbcAssert.java:130)
   >    at org.elasticsearch.xpack.qa.sql.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:55)
   >    at org.elasticsearch.xpack.qa.sql.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:42)
   >    at org.elasticsearch.xpack.qa.sql.jdbc.SpecBaseIntegrationTestCase.assertResults(SpecBaseIntegrationTestCase.java:124)
   >    at org.elasticsearch.xpack.qa.sql.jdbc.SqlSpecTestCase.doTest(SqlSpecTestCase.java:94)
   >    at org.elasticsearch.xpack.qa.sql.jdbc.SpecBaseIntegrationTestCase.test(SpecBaseIntegrationTestCase.java:89)
   >    at java.lang.Thread.run(Thread.java:748)

**Comment by mayya-sharipova** [comment]
The failure seems to be related to these particular seeds. Running tests with other seeds succeed.
