### ISSUE TITLE
failed to verify minimum version with XPACK monitor and seperate cluster

### ISSUE THREAD

**Issue by danielkasen** [elastic/elasticsearch#35057]
**Elasticsearch version** (`bin/elasticsearch --version`): 
6.3.2

**Plugins installed**: []

**JVM version** (`java -version`): 
1.8

**OS version** (`uname -a` if on a Unix-like system): 
Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:
Shipping monitoring metrics to a seperate ECE cluster eventually stops working and only gets fixed by restarting each node in the sending cluster. Initially the monitoring events flow correctly and even after the issue starts you can send POST commands from the data node into the ECE monitoring cluster. The only things I can find in the logs to show this behavior is occurring is the following:

**Steps to reproduce**:

 1. Set up a seperate monitoring cluster in ECE 
 2. Start shipping monitoring events to the cluster
 3. Wait for a network blip 
 4. Search for the error 

**Provide logs (if relevant)**:

```
 failed to verify minimum version [6.0.0-alpha1] on the [xpack.monitoring.exporters.monitoring_endpoint] monitoring cluster
java.io.IOException: null
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:728) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:177) ~[elasticsearch-rest-client-6.3.2.jar:6.3.2]
	at org.elasticsearch.xpack.monitoring.exporter.http.VersionHttpResource.doCheckAndPublish(VersionHttpResource.java:62) [x-pack-monitoring-6.3.2.jar:6.3.2]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpResource.checkAndPublish(HttpResource.java:156) [x-pack-monitoring-6.3.2.jar:6.3.2]
	at org.elasticsearch.xpack.monitoring.exporter.http.MultiHttpResource.doCheckAndPublish(MultiHttpResource.java:64) [x-pack-monitoring-6.3.2.jar:6.3.2]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpResource.checkAndPublish(HttpResource.java:156) [x-pack-monitoring-6.3.2.jar:6.3.2]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpResource.blockUntilCheckAndPublish(HttpResource.java:132) [x-pack-monitoring-6.3.2.jar:6.3.2]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpResource.checkAndPublishIfDirty(HttpResource.java:116) [x-pack-monitoring-6.3.2.jar:6.3.2]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpExporter.isExporterReady(HttpExporter.java:641) [x-pack-monitoring-6.3.2.jar:6.3.2]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpExporter.openBulk(HttpExporter.java:647) [x-pack-monitoring-6.3.2.jar:6.3.2]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpExporter.openBulk(HttpExporter.java:70) [x-pack-monitoring-6.3.2.jar:6.3.2]
	at org.elasticsearch.xpack.monitoring.exporter.Exporters.openBulk(Exporters.java:115) [x-pack-monitoring-6.3.2.jar:6.3.2]
	at org.elasticsearch.xpack.monitoring.exporter.Exporters.export(Exporters.java:186) [x-pack-monitoring-6.3.2.jar:6.3.2]
	at org.elasticsearch.xpack.monitoring.MonitoringService$MonitoringExecution$1.doRun(MonitoringService.java:258) [x-pack-monitoring-6.3.2.jar:6.3.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.3.2.jar:6.3.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:626) [elasticsearch-6.3.2.jar:6.3.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.net.ConnectException
	at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:168) ~[?:?]
	at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:561) ~[?:?]
	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:822) ~[?:?]
	at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:183) ~[?:?]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:210) ~[?:?]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:155) ~[?:?]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348) ~[?:?]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192) ~[?:?]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) ~[?:?]
	... 1 more```

**Comment by priyaprabhakar777** [comment]
Hey anyone can help on this. Still getting the same message

**Comment by s1monw** [comment]
it looks like you are hitting a timeout on the cluster you want to export to. 
```
Caused by: java.net.ConnectException
	at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:168) ~[?:?]
```
is the cluster reachable and the hostname correct? Anyway this doesn't seem like a bug and we reserve this issue tracker for bugs and feature requests. Can you raise your issue on https://discuss@elastic.co

**Comment by s1monw** [comment]
hmm, I am reopening this. I didn't read it all the way I think. 

@danielkasen can you elaborate what you mean by _network blib_?

**Comment by danielkasen** [comment]
Blip not blib. But I have a hunch this exists in a thread and then it doesn't retry the connection. Basically it works for about a week then just stops.

**Comment by danielkasen** [comment]
I can also log into one of the machines producing this and curl the monitoring cluster just fine.

**Comment by woodlee** [comment]
We also see this behavior (and have come to the same conclusion that restarting nodes in the sending cluster is the only way to fix it) on ES 6.5.2. Everything works fine for a few days, then these errors begin to appear and eventually all monitoring data is lost. All sending cluster nodes have repetitions of the logs:

```
[2018-12-26T11:54:28,080][WARN ][o.e.x.m.e.h.NodeFailureListener] [grids2-es-master-10-0-40-162] connection failed to node at [https://grids2-es-monitor.<redacted>:9200]
[2018-12-26T11:54:28,080][ERROR][o.e.x.m.e.h.VersionHttpResource] [grids2-es-master-10-0-40-162] failed to verify minimum version [6.0.0-alpha1] on the [xpack.monitoring.exporters.id1] monitoring cluster
java.io.IOException: No route to host
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:954) ~[elasticsearch-rest-client-6.5.2.jar:6.5.2]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229) ~[elasticsearch-rest-client-6.5.2.jar:6.5.2]
	at org.elasticsearch.xpack.monitoring.exporter.http.VersionHttpResource.doCheckAndPublish(VersionHttpResource.java:59) [x-pack-monitoring-6.5.2.jar:6.5.2]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpResource.checkAndPublish(HttpResource.java:156) [x-pack-monitoring-6.5.2.jar:6.5.2]
	at org.elasticsearch.xpack.monitoring.exporter.http.MultiHttpResource.doCheckAndPublish(MultiHttpResource.java:64) [x-pack-monitoring-6.5.2.jar:6.5.2]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpResource.checkAndPublish(HttpResource.java:156) [x-pack-monitoring-6.5.2.jar:6.5.2]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpResource.blockUntilCheckAndPublish(HttpResource.java:132) [x-pack-monitoring-6.5.2.jar:6.5.2]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpResource.checkAndPublishIfDirty(HttpResource.java:116) [x-pack-monitoring-6.5.2.jar:6.5.2]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpExporter.isExporterReady(HttpExporter.java:679) [x-pack-monitoring-6.5.2.jar:6.5.2]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpExporter.openBulk(HttpExporter.java:685) [x-pack-monitoring-6.5.2.jar:6.5.2]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpExporter.openBulk(HttpExporter.java:71) [x-pack-monitoring-6.5.2.jar:6.5.2]
	at org.elasticsearch.xpack.monitoring.exporter.Exporters.openBulk(Exporters.java:116) [x-pack-monitoring-6.5.2.jar:6.5.2]
	at org.elasticsearch.xpack.monitoring.exporter.Exporters.export(Exporters.java:187) [x-pack-monitoring-6.5.2.jar:6.5.2]
	at org.elasticsearch.xpack.monitoring.MonitoringService$MonitoringExecution$1.doRun(MonitoringService.java:288) [x-pack-monitoring-6.5.2.jar:6.5.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.5.2.jar:6.5.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) [elasticsearch-6.5.2.jar:6.5.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171) ~[?:?]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145) ~[?:?]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348) ~[?:?]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192) ~[?:?]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) ~[?:?]
	... 1 more
```

...and restarting only the (lone) monitoring node is ineffective at fixing it. Posts elsewhere suggested DNS caching issues but in our case we're on AWS with hostnames that contain the IP address, and no nodes have recently been replaced, so this seems unlikely in our case. No unusual logs on the monitoring node, and pings / curls from the other nodes to the monitoring node work fine:

```
[root@grids2-es-master-10-0-40-162 elasticsearch]# curl https://grids2-es-monitor.<redacted>:9200
{
  "name" : "grids2-es-monitor-10-0-40-218",
  "cluster_name" : "grids2-es-monitor",
  "cluster_uuid" : "CWkssNwaR-SBr_6kwThXyw",
  "version" : {
    "number" : "6.5.2",
    "build_flavor" : "default",
    "build_type" : "rpm",
    "build_hash" : "9434bed",
    "build_date" : "2018-11-29T23:58:20.891072Z",
    "build_snapshot" : false,
    "lucene_version" : "7.5.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by woodlee** [comment]
Oh, another thing worthy of note is that we have filebeat exporting the Elasticsearch process's logs from the sending cluster's nodes to the monitoring node's ES instance, and this continues to work fine. It's only the monitoring data that has failed.

**Comment by rvodden** [comment]
I can trigger this behaviour by changing the IP address of the monitoring cluster. (Or by waiting for the IP of the aws ELB to change, in my case). I'm going to do some digging and see which part of the code is not honouring the DNS timeouts.

**Comment by rvodden** [comment]
I'm unable to find anything which implies its not honoring that timeout. We are experiencing exactly the same issue though:

```
failed to verify minimum version [6.0.0-alpha1] on the [xpack.monitoring.exporters.elkelk] monitoring cluster
java.io.IOException: No route to host
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:954) ~[elasticsearch-rest-client-6.5.4.jar:6.5.4]
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229) ~[elasticsearch-rest-client-6.5.4.jar:6.5.4]
	at org.elasticsearch.xpack.monitoring.exporter.http.VersionHttpResource.doCheckAndPublish(VersionHttpResource.java:59) [x-pack-monitoring-6.5.4.jar:6.5.4]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpResource.checkAndPublish(HttpResource.java:156) [x-pack-monitoring-6.5.4.jar:6.5.4]
	at org.elasticsearch.xpack.monitoring.exporter.http.MultiHttpResource.doCheckAndPublish(MultiHttpResource.java:64) [x-pack-monitoring-6.5.4.jar:6.5.4]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpResource.checkAndPublish(HttpResource.java:156) [x-pack-monitoring-6.5.4.jar:6.5.4]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpResource.blockUntilCheckAndPublish(HttpResource.java:132) [x-pack-monitoring-6.5.4.jar:6.5.4]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpResource.checkAndPublishIfDirty(HttpResource.java:116) [x-pack-monitoring-6.5.4.jar:6.5.4]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpExporter.isExporterReady(HttpExporter.java:679) [x-pack-monitoring-6.5.4.jar:6.5.4]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpExporter.openBulk(HttpExporter.java:685) [x-pack-monitoring-6.5.4.jar:6.5.4]
	at org.elasticsearch.xpack.monitoring.exporter.http.HttpExporter.openBulk(HttpExporter.java:71) [x-pack-monitoring-6.5.4.jar:6.5.4]
	at org.elasticsearch.xpack.monitoring.exporter.Exporters.openBulk(Exporters.java:116) [x-pack-monitoring-6.5.4.jar:6.5.4]
	at org.elasticsearch.xpack.monitoring.exporter.Exporters.export(Exporters.java:187) [x-pack-monitoring-6.5.4.jar:6.5.4]
	at org.elasticsearch.xpack.monitoring.MonitoringService$MonitoringExecution$1.doRun(MonitoringService.java:288) [x-pack-monitoring-6.5.4.jar:6.5.4]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.5.4.jar:6.5.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) [elasticsearch-6.5.4.jar:6.5.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171) ~[?:?]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145) ~[?:?]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348) ~[?:?]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192) ~[?:?]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) ~[?:?]
```

And again, we have filebeat export logs to the exact same endpoint from the same machine - which is where I extracted that log from.

**Comment by woodlee** [comment]
According to [this](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/networkaddress-cache-ttl.html), as of ES 6.5, domain name resolutions are being cached indefinitely. So that could certainly explain the behavior when one is behind e.g. an AWS ELB.

We're gonna try adding `-Dsun.net.inetaddr.ttl=60` to the `ES_JAVA_OPTS` in our `/etc/sysconfig/elasticsearch` files to hopefully force re-resolution every minute, and see how it goes. There are security drawbacks related to DNS spoofing from doing this, so use your own discretion as to whether you feel it's safe for your case!

It appears that ES themselves instituted [a 60s DNS TTL override](https://www.elastic.co/guide/en/elasticsearch/reference/6.6/networkaddress-cache-ttl.html) as of 6.6, so upgrading may be an easier resolution for some.

**Comment by danielkasen** [comment]
Yea, sadly i'm blocked on our upgrade path atm. I'll try that option and see if it fixes it for now. Thanks.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
