### ISSUE TITLE
SQL: SELECTing a sub-field from a nested field throws an error

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#35077]
At the moment we do not support more than one level deep nested documents. The test below shows an incorrect behavior where SQL assumes the sub-field of a nested field is another level of nesting (`dep` is a nested document, `dep.dep_name.keyword` is the `keyword` sub-field of `dep.dep_name`).

```
sql> SELECT first_name, dep.dep_name,dep.dep_name.keyword FROM test_emp;

Server error [Server encountered an error [Multi-nested docs not yet supported [dep, dep.dep_name]]. [SqlIllegalArgumentException[Multi-nested docs not yet supported [dep, dep.dep_name]]
        at org.elasticsearch.xpack.sql.execution.search.SearchHitRowSet.<init>(SearchHitRowSet.java:58)
        at org.elasticsearch.xpack.sql.execution.search.SchemaSearchHitRowSet.<init>(SchemaSearchHitRowSet.java:24)
        at org.elasticsearch.xpack.sql.execution.search.Querier$ScrollActionListener.lambda$handleResponse$0(Querier.java:330)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.lambda$clear$3(Querier.java:434)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:66)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:62)
        at org.elasticsearch.action.search.ClearScrollController.onFreedContext(ClearScrollController.java:130)
        at org.elasticsearch.action.search.ClearScrollController.lambda$cleanScrollIds$2(ClearScrollController.java:115)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:48)
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1117)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1203)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1183)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1172)
        at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:54)
        at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$1(SearchTransportService.java:311)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63)
        at org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:708)
        at org.elasticsearch.transport.TransportService.access$000(TransportService.java:82)
        at org.elasticsearch.transport.TransportService$3.sendRequest(TransportService.java:151)
        at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:654)
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:569)
        at org.elasticsearch.action.search.SearchTransportService.sendFreeContext(SearchTransportService.java:110)
        at org.elasticsearch.action.search.ClearScrollController.lambda$cleanScrollIds$4(ClearScrollController.java:114)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.action.search.SearchScrollAsyncAction.collectNodesAndRun(SearchScrollAsyncAction.java:129)
        at org.elasticsearch.action.search.ClearScrollController.cleanScrollIds(ClearScrollController.java:105)
        at org.elasticsearch.action.search.ClearScrollController.lambda$new$1(ClearScrollController.java:71)
        at org.elasticsearch.action.search.ClearScrollController.run(ClearScrollController.java:80)
        at org.elasticsearch.action.search.TransportClearScrollAction.doExecute(TransportClearScrollAction.java:49)
        at org.elasticsearch.action.search.TransportClearScrollAction.doExecute(TransportClearScrollAction.java:31)
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:143)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:119)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:62)
        at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83)
        at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:388)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:70)
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.clear(Querier.java:432)
        at org.elasticsearch.xpack.sql.execution.search.Querier$ScrollActionListener.handleResponse(Querier.java:329)
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.onResponse(Querier.java:407)
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.onResponse(Querier.java:383)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:66)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:62)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onResponse(AbstractSearchAsyncAction.java:313)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onResponse(AbstractSearchAsyncAction.java:50)
        at org.elasticsearch.action.search.FetchSearchPhase$3.run(FetchSearchPhase.java:212)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:160)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:153)
        at org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:119)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:160)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:153)
        at org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:205)
        at org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$2(FetchSearchPhase.java:104)
        at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:110)
        at org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:44)
        at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:86)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:726)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by matriv** [comment]
@elastic/es-ql

**Comment by wchaparro** [comment]
Stale issue, not going to address. Closing as won't do.

Reopen if prioritization is incorrect.
