### ISSUE TITLE
[CI] NamedPipeHelperNoBootstrapTests failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#35196]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.5+multijob-windows-compatibility/15/console

Failed on Windows, 6.5 branch

```
FAILURE 0.25s | NamedPipeHelperNoBootstrapTests.testOpenForOutput <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected null, but was:<java.io.IOException: ConnectNamedPipe failed for pipe \\.\pipe\outputPipe8392 with error 232>
   > 	at __randomizedtesting.SeedInfo.seed([9E604FEB07AB2303:1F6877F777AAA670]:0)

   > 	at org.elasticsearch.xpack.ml.utils.NamedPipeHelperNoBootstrapTests.testOpenForOutput(NamedPipeHelperNoBootstrapTests.java:337)
   > 	at java.lang.Thread.run(Thread.java:748)
```

Error code 232 is [ERROR_NO_DATA](https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes--0-499-)

Reproduce:
```
ant test  \
  -Dtestcase=NamedPipeHelperNoBootstrapTests \
  -Dtests.method=testOpenForOutput \
  -Dtests.seed=9E604FEB07AB2303 \
  -Dtests.slow=true \
  -Dtests.badapples=true \
  -Dtests.locale=pt-PT \
  -Dtests.timezone=Africa/Algiers \
  -Dtests.asserts=true \
  -Dtests.file.encoding=Cp1252
```

**Comment by davidkyle** [comment]
Researching this I came across the term 'benign error message' which should be an oxymoron but is a thing. 

From the microsoft [docs](https://msdn.microsoft.com/en-us/library/aa365146.aspx) 

`
ConnectNamedPipe returns zero, and GetLastError returns ERROR_NO_DATA if the previous client has closed its handle...
`

In this case the error comes from the server side. The client connected to the server wrote a message then closed its connection before the server had chance to read the message. The client connection is [closed]( https://github.com/elastic/elasticsearch/blob/28d12b05b77472d0596df319d7129cea3ba9154a/x-pack/plugin/ml/qa/no-bootstrap-tests/src/test/java/org/elasticsearch/xpack/ml/utils/NamedPipeHelperNoBootstrapTests.java#L327) before the server thread joins hence the race. The test fails very rarely.

**Comment by droberts195** [comment]
The production code doesn't contain anything specific to handle this case, so I was wondering if the production code could also suffer from this.

I think the answer is that it can't (except in the case of some other major error), because we connect the output of the native process after connecting the input, and the Java side won't do anything with either of the pipes until all are connected.  So in the event of the input pipe in the C++ process being closed by the Java in between creating and connecting the pipe, it would be because of some major event like the whole JVM being shut down, and in this situation it would be reasonable for the C++ to consider it a fatal error.

**Comment by Luegg** [comment]
> Given that the test has not failed in the last 12 months I added a [comment](https://github.com/elastic/elasticsearch/commit/85f8458f0641554cdc4f85bbba4f465f70529031) to the code describing possible failure scenarios. If the failure repeats the test should be re-worked.

@davidkyle We just had another occurrence of the failure today: https://gradle-enterprise.elastic.co/s/mzmxwfpjxljdw/console-log?anchor=3096

There were some in the past few months: https://gradle-enterprise.elastic.co/s/j7hjif573fd62/console-log?anchor=3460 and https://gradle-enterprise.elastic.co/s/xongv52lwgjiu/console-log?anchor=6579

**Comment by davidkyle** [comment]
Thanks @Luegg for digging into the failure history.

I found [5 failures in the last 2 years](https://build-stats.elastic.co/goto/03425f32123904bf64d4ebea46fc1c0a) all of which were on the 6.8 branch. Given that this is a problem with the test which does not affect production code and the fact that the failures are rare only on occurring on the 6.8 branch we won't be prioritising a fix.
