### ISSUE TITLE
Composite aggregation cannot be sorted by _key with bucket_sort pipeline aggregation

### ISSUE THREAD

**Issue by ItamarBenjamin** [elastic/elasticsearch#35256]
**Elasticsearch version** : 6.4.2

**Plugins installed**: []

**JVM version**: openjdk 10.0.2

**OS version** : UBUNTU-16.04 offical elastic docker

**Description of the problem including expected versus actual behavior**:

when running a composite aggregation and trying to sort on the aggregation keys, getting 503 and class cast exception.

**Steps to reproduce**:

`curl localhost:9200/reproduce -X PUT`

`curl localhost:9200/reproduce/_doc/1 -X POST -H Content-Type:application/json -d '{ "foo" : 1, "bar" : 2}'`

` curl localhost:9200/reproduce/_search -X POST -H Content-Type:application/json -d'{
    "aggs": {
        "sales_per_month": {
            "aggs": {
                "sales_bucket_sort": {
                    "bucket_sort": {
                        "sort": [
                            {
                                "_key": {
                                    "order": "asc"
                                }
                            }
                        ]
                    }
                }
            },
            "composite": {
                "sources" : [
                    { "product": { "terms" : { "field": "foo" } } }
                ]
            }
        }
    },
    "size": 0
}'
`
 returns this error:
`{"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"","phase":"fetch","grouped":true,"failed_shards":[],"caused_by":{"type":"class_cast_exception","reason":"org.elasticsearch.search.aggregations.bucket.composite.InternalComposite$ArrayMap cannot be cast to java.base/java.lang.Comparable"}},"status":503}`

**Provide logs (if relevant)**:
`
org.elasticsearch.action.search.SearchPhaseExecutionException:
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:293) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.search.FetchSearchPhase$1.onFailure(FetchSearchPhase.java:91) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:708) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.4.2.jar:6.4.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.ClassCastException: org.elasticsearch.search.aggregations.bucket.composite.InternalComposite$ArrayMap cannot be cast to java.base/java.lang.Comparable
        at org.elasticsearch.search.aggregations.pipeline.bucketsort.BucketSortPipelineAggregator$ComparableBucket.resolveAndCacheSortValues(BucketSortPipelineAggregator.java:137) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.search.aggregations.pipeline.bucketsort.BucketSortPipelineAggregator$ComparableBucket.<init>(BucketSortPipelineAggregator.java:129) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.search.aggregations.pipeline.bucketsort.BucketSortPipelineAggregator$ComparableBucket.<init>(BucketSortPipelineAggregator.java:120) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.search.aggregations.pipeline.bucketsort.BucketSortPipelineAggregator.reduce(BucketSortPipelineAggregator.java:103) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:138) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:77) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.search.SearchPhaseController.reduceAggs(SearchPhaseController.java:525) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:502) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:419) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.search.SearchPhaseController$1.reduce(SearchPhaseController.java:738) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:101) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:44) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:86) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.4.2.jar:6.4.2]
`

**Comment by ItamarBenjamin** [comment]
added PR that solves this issue: https://github.com/elastic/elasticsearch/pull/36407
pinging @elastic/es-search-aggs

**Comment by polyfractal** [comment]
Closing as I believe #36407 fixed this.
