### ISSUE TITLE
LocalIndexFollowingIT.testDoNotCreateFollowerIfLeaderDoesNotHaveSoftDeletes fails on 6.5

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#35292]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.5+intake/46/

Error: 

```
02:29:42 FAILURE 0.23s J0 | LocalIndexFollowingIT.testDoNotCreateFollowerIfLeaderDoesNotHaveSoftDeletes <<< FAILURES!
02:29:42    > Throwable #1: java.lang.AssertionError: 
02:29:42    > Expected: <false>
02:29:42    >      but: was <true>
02:29:42    > 	at __randomizedtesting.SeedInfo.seed([7A3C89DA3BCA17DD:65C26CBF6FEF0B39]:0)
02:29:42    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
02:29:42    > 	at org.elasticsearch.xpack.ccr.LocalIndexFollowingIT.testDoNotCreateFollowerIfLeaderDoesNotHaveSoftDeletes(LocalIndexFollowingIT.java:83)
```

Reproduce line (does not seem to repro though):

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:ccr:internalClusterTest -Dtests.seed=7A3C89DA3BCA17DD -Dtests.class=org.elasticsearch.xpack.ccr.LocalIndexFollowingIT -Dtests.method="testDoNotCreateFollowerIfLeaderDoesNotHaveSoftDeletes" -Dtests.security.manager=true -Dtests.locale=es-AR -Dtests.timezone=America/New_York -Dcompiler.java=11 -Druntime.java=8
```

**Comment by dnhatn** [comment]
This is fixed by https://github.com/elastic/elasticsearch/commit/a937d7f5f3bc92fcbc2e789ec97b16f9e652194a. Thanks @martijnvg.
