### ISSUE TITLE
java error elasticsearch-certurtil

### ISSUE THREAD

**Issue by jacobbogers** [elastic/elasticsearch#35311]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 6.4.3, Build: default/rpm/fe40335/2018-10-30T23:17:19.084789Z, JVM: 1.8.0_191

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux linuxkit-00155dce5d17 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
elasticsearch-certutil doesnt work, I cannot generate cert file

**Steps to reproduce**:

Issue command  
bin/elasticsearch-certutil cert -ca elastic-stack-ca.p12

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

Follow steps when you run the command (enter password or just press enter asked)

**Provide logs (if relevant)**:
Exception in thread "main" java.nio.file.NoSuchFileException: elastic-stack-ca.p12
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.xpack.core.ssl.CertParsingUtils.readKeyStore(CertParsingUtils.java:68)
        at org.elasticsearch.xpack.core.ssl.CertParsingUtils.readPkcs12KeyPairs(CertParsingUtils.java:127)
        at org.elasticsearch.xpack.security.cli.CertificateTool$CertificateCommand.lambda$loadPkcs12CA$1(CertificateTool.java:341)
        at org.elasticsearch.xpack.security.cli.CertificateTool.withPassword(CertificateTool.java:931)
        at org.elasticsearch.xpack.security.cli.CertificateTool.access$100(CertificateTool.java:85)
        at org.elasticsearch.xpack.security.cli.CertificateTool$CertificateCommand.loadPkcs12CA(CertificateTool.java:340)
        at org.elasticsearch.xpack.security.cli.CertificateTool$CertificateCommand.getCAInfo(CertificateTool.java:328)
        at org.elasticsearch.xpack.security.cli.CertificateTool$GenerateCertificateCommand.execute(CertificateTool.java:684)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.xpack.security.cli.CertificateTool.main(CertificateTool.java:137)

**Comment by andyb-elastic** [comment]
I'm not able to reproduce this issue on 6.4.3. Make sure that your ca cert file `elastic-stack-ca.p12` is readable by the user you're running `elasticsearch-certutil` as.

We use this issue tracker for bug reports and feature requests. There's an active community in the [forums](https://discuss.elastic.co/) that can help with questions like this.

**Comment by yuanshi1602** [comment]
@tvernum  The  issue has been resolved，I make spelling mistakes。。。elastic-sack-ca.p12
