### ISSUE TITLE
[CI] Failure in SslIntegrationTests.testThatTransportClientUsingSSLv3ProtocolIsRejected 

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#35360]
This seems to have been broken in #35144 / f395b1e.
Reproduces locally.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/45/console

```
./gradlew :x-pack:plugin:security:test -Dtests.seed=447D7874AF93DCF8 -Dtests.class=org.elasticsearch.xpack.security.transport.ssl.SslIntegrationTests -Dtests.method="testThatTransportClientUsingSSLv3ProtocolIsRejected" -Dtests.security.manager=true -Dtests.locale=nl-NL -Dtests.timezone=UCT -Dcompiler.java=11 -Druntime.java=11
```

```
  > Throwable #1: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=160, name=Thread-1, state=RUNNABLE, group=TGRP-SslIntegrationTests]
   >    at __randomizedtesting.SeedInfo.seed([447D7874AF93DCF8:9CD5162256A743F1]:0)
   > Caused by: java.lang.AssertionError
   >    at __randomizedtesting.SeedInfo.seed([447D7874AF93DCF8]:0)
   >    at io.netty.handler.ssl.SslHandler.handshake(SslHandler.java:1747)
   >    at io.netty.handler.ssl.SslHandler.startHandshakeProcessing(SslHandler.java:1666)
   >    at io.netty.handler.ssl.SslHandler.channelActive(SslHandler.java:1807)
```

**Comment by tvernum** [comment]
Ping: @tbrooks8 - I think this broke in your recent change

**Comment by tvernum** [comment]
I muted this test (0b24c4f)

**Comment by tbrooks8** [comment]
I think this has exposed a bug in netty. I opened an issue.

@netty/netty#8479

**Comment by tvernum** [comment]
This has been muted on 6.x as well.
