### ISSUE TITLE
CI: BalanceConfigurationTests.testReplicaBalance fails in a reproducible way

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#35365]
Going to mute the test.

## Reproduction line 
**does** reproduce
```
./gradlew :server:test \
  -Dtests.seed=DDBE7ADDD8F01971 \
  -Dtests.class=org.elasticsearch.cluster.routing.allocation.BalanceConfigurationTests \
  -Dtests.method="testReplicaBalance" \
  -Dtests.security.manager=true \
  -Dtests.locale=cs \
  -Dtests.timezone=Australia/Brisbane \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

## Example relevant log:
```
23:35:47   2> REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=DDBE7ADDD8F01971 -Dtests.class=org.elasticsearch.cluster.routing.allocation.BalanceConfigurationTests -Dtests.method="testReplicaBalance" -Dtests.security.manager=true -Dtests.locale=cs -Dtests.timezone=Australia/Brisbane -Dcompiler.java=11 -Druntime.java=8
23:35:47   1> [2018-11-08T07:35:47,314][INFO ][o.e.c.r.a.BalanceConfigurationTests] [testReplicaBalance] complete rebalancing
23:35:47   2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+master+intake/server/build/testrun/test/J0/temp/org.elasticsearch.cluster.routing.allocation.BalanceConfigurationTests_DDBE7ADDD8F01971-001
23:35:47   1> [2018-11-08T07:35:47,315][INFO ][o.e.c.r.a.BalanceConfigurationTests] [testReplicaBalance] after test
23:35:47   2> NOTE: test params are: codec=Asserting(Lucene80): {}, docValues:{}, maxPointsInLeafNode=1291, maxMBSortInHeap=7.145509876487136, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@74dca44f), locale=cs, timezone=Australia/Brisbane
23:35:47 FAILURE 0.21s J0 | BalanceConfigurationTests.testReplicaBalance <<< FAILURES!
23:35:47   2> NOTE: Linux 4.4.156-94.64-default amd64/Oracle Corporation 1.8.0_192 (64-bit)/cpus=16,threads=1,free=362555832,total=519569408
23:35:47    > Throwable #1: java.lang.AssertionError: 
23:35:47   2> NOTE: All tests run in this JVM: [NodeInfoStreamingTests, CountDownTests, FileInfoTests, QueryRescoreModeTests, KeyStoreWrapperTests, RetryTests, ClusterApplierServiceTests, FieldMemoryStatsTests, DoubleTermsTests, LuceneChangesSnapshotTests, SignificantLongTermsTests, RootObjectMapperTests, RestIndicesActionTests, BulkByScrollTaskStatusOrExceptionTests, BalanceConfigurationTests]
23:35:47    > Expected: a value equal to or greater than <4>
23:35:47    >      but: <3> was less than <4>
23:35:47    > 	at __randomizedtesting.SeedInfo.seed([DDBE7ADDD8F01971:B47081853A0CDBC0]:0)
23:35:47    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
23:35:47    > 	at org.elasticsearch.cluster.routing.allocation.BalanceConfigurationTests.assertReplicaBalance(BalanceConfigurationTests.java:209)
23:35:47    > 	at org.elasticsearch.cluster.routing.allocation.BalanceConfigurationTests.testReplicaBalance(BalanceConfigurationTests.java:112)
23:35:47    > 	at java.lang.Thread.run(Thread.java:748)
```

## Frequency

6 times this week on an upwards trend.

**Comment by s1monw** [comment]
@vladimirdolzhenko can you look. it seems you touched it last?

**Comment by atorok** [comment]
I should have mentioned that the test fails with this  seed even without the changes made by @vladimirdolzhenko
