### ISSUE TITLE
CI: OOM in __mock_network_thread

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#35374]
## Example build failure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/132/console

## Reproduction line 
does not reproduce locally
```
./gradlew :server:integTest \
  -Dtests.seed=19E21C2B8FC27FC8 \
  -Dtests.class=org.elasticsearch.persistent.decider.EnableAssignmentDeciderIT \
  -Dtests.method="testEnableAssignmentAfterRestart" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-SD \
  -Dtests.timezone=America/Danmarkshavn \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

## Example relevant log:
```
Captured an uncaught exception in thread: Thread[id=1393, name=elasticsearch[node_s2][__mock_network_thread][T#17], state=RUNNABLE, group=TGRP-EnableAssignmentDeciderIT]
--
```

```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=1393, name=elasticsearch[node_s2][__mock_network_thread][T#17], state=RUNNABLE, group=TGRP-EnableAssignmentDeciderIT]
Caused by: java.lang.OutOfMemoryError: Java heap space
	at __randomizedtesting.SeedInfo.seed([19E21C2B8FC27FC8]:0)
	at org.elasticsearch.transport.MockTcpTransport.readMessage(MockTcpTransport.java:154)
	at org.elasticsearch.transport.MockTcpTransport.access$800(MockTcpTransport.java:69)
	at org.elasticsearch.transport.MockTcpTransport$MockChannel$2.lambda$doRun$0(MockTcpTransport.java:334)
	at org.elasticsearch.transport.MockTcpTransport$MockChannel$2$$Lambda$1501/1218045512.run(Unknown Source)
	at org.elasticsearch.common.util.CancellableThreads.executeIO(CancellableThreads.java:106)
	at org.elasticsearch.transport.MockTcpTransport$MockChannel$2.doRun(MockTcpTransport.java:334)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## Frequency

The OOM for this thread shows up in logs 35 times this week and 95 times last week   across all builds.

**Comment by DaveCTurner** [comment]
Possibly this duplicates https://github.com/elastic/elasticsearch/issues/34458

**Comment by vladimirdolzhenko** [comment]
I did head dump analysis of several heaps and pretty sure it is the same as pointed @tvernum by at https://github.com/elastic/elasticsearch/issues/34458#issuecomment-437210009
