### ISSUE TITLE
[CI] EvilOSProbeTests failure

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#35448]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=oraclelinux/53/console

```
REPRODUCE WITH: ./gradlew :qa:evil-tests:test \
  -Dtests.seed=81D331009B2950AB \
  -Dtests.class=org.elasticsearch.monitor.os.EvilOsProbeTests \
  -Dtests.method="testOsPrettyName" \
  -Dtests.security.manager=false \
  -Dtests.locale=ca \
  -Dtests.timezone=Asia/Yerevan \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

The relevant OS name is "Oracle Linux Server 6.9"

**Comment by jasontedor** [comment]
What’s the actual failure here? It would be helpful to include that in these CI reports since the logs get swept away over time.

**Comment by romseygeek** [comment]
The failure message is:
```
java.lang.AssertionError: PRETTY_NAME="Oracle Linux Server 6.9" 
	at __randomizedtesting.SeedInfo.seed([81D331009B2950AB:5D31F9920ADE06AB]:0)
	at org.elasticsearch.monitor.os.EvilOsProbeTests.testOsPrettyName(EvilOsProbeTests.java:43)
```

**Comment by jasontedor** [comment]
From:

```
Suite: org.elasticsearch.monitor.os.EvilOsProbeTests
  1> [2018-11-12T11:02:34,037][INFO ][o.e.m.o.EvilOsProbeTests ] [testOsPrettyName] before test
  1> [2018-11-12T11:02:34,044][INFO ][o.e.m.o.EvilOsProbeTests ] [testOsPrettyName] after test
  2> REPRODUCE WITH: ./gradlew :qa:evil-tests:test -Dtests.seed=81D331009B2950AB -Dtests.class=org.elasticsearch.monitor.os.EvilOsProbeTests -Dtests.method="testOsPrettyName" -Dtests.security.manager=false -Dtests.locale=ca -Dtests.timezone=Asia/Yerevan -Dcompiler.java=11 -Druntime.java=8
FAILURE 0.01s J1 | EvilOsProbeTests.testOsPrettyName <<< FAILURES!
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+6.x+multijob-unix-compatibility/os/oraclelinux/qa/evil-tests/build/testrun/test/J1/temp/org.elasticsearch.monitor.os.EvilOsProbeTests_81D331009B2950AB-001
   > Throwable #1: java.lang.AssertionError: PRETTY_NAME="Oracle Linux Server 6.9" 
   > 	at __randomizedtesting.SeedInfo.seed([81D331009B2950AB:5D31F9920ADE06AB]:0)
   > 	at org.elasticsearch.monitor.os.EvilOsProbeTests.testOsPrettyName(EvilOsProbeTests.java:43)
   > 	at java.lang.Thread.run(Thread.java:748)
Completed [10/17] on J1 in 0.03s, 1 test, 1 failure <<< FAILURES!
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=1865, maxMBSortInHeap=7.76329077261664, sim=RandomSimilarity(queryNorm=false): {}, locale=ca, timezone=Asia/Yerevan

  2> NOTE: Linux 2.6.32-696.el6.x86_64 amd64/Oracle Corporation 1.8.0_192 (64-bit)/cpus=16,threads=1,free=460224760,total=514850816
  2> NOTE: All tests run in this JVM: [EvilLoggerConfigurationTests, SystemCallFilterTests, EvilBootstrapChecksTests, EvilOsProbeTests]
```

It appears there is an extraneous space at the end of the line:

```
[jason@worker-0a3897bad8c89d902 ~]$ cat /etc/os-release 
NAME="Oracle Linux Server" 
VERSION="6.9" 
ID="ol" 
VERSION_ID="6.9" 
PRETTY_NAME="Oracle Linux Server 6.9" 
ANSI_COLOR="0;31" 
CPE_NAME="cpe:/o:oracle:linux:6:9:server"
HOME_URL="https://linux.oracle.com/" 
BUG_REPORT_URL="https://bugzilla.oracle.com/" 

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 6" 
ORACLE_BUGZILLA_PRODUCT_VERSION=6.9 
ORACLE_SUPPORT_PRODUCT="Oracle Linux" 
ORACLE_SUPPORT_PRODUCT_VERSION=6.9
[jason@worker-0a3897bad8c89d902 ~]$ cat /etc/os-release | xxd
0000000: 4e41 4d45 3d22 4f72 6163 6c65 204c 696e  NAME="Oracle Lin
0000010: 7578 2053 6572 7665 7222 200a 5645 5253  ux Server" .VERS
0000020: 494f 4e3d 2236 2e39 2220 0a49 443d 226f  ION="6.9" .ID="o
0000030: 6c22 200a 5645 5253 494f 4e5f 4944 3d22  l" .VERSION_ID="
0000040: 362e 3922 200a 5052 4554 5459 5f4e 414d  6.9" .PRETTY_NAM
0000050: 453d 224f 7261 636c 6520 4c69 6e75 7820  E="Oracle Linux 
0000060: 5365 7276 6572 2036 2e39 2220 0a41 4e53  Server 6.9" .ANS
0000070: 495f 434f 4c4f 523d 2230 3b33 3122 200a  I_COLOR="0;31" .
0000080: 4350 455f 4e41 4d45 3d22 6370 653a 2f6f  CPE_NAME="cpe:/o
0000090: 3a6f 7261 636c 653a 6c69 6e75 783a 363a  :oracle:linux:6:
00000a0: 393a 7365 7276 6572 220a 484f 4d45 5f55  9:server".HOME_U
00000b0: 524c 3d22 6874 7470 733a 2f2f 6c69 6e75  RL="https://linu
00000c0: 782e 6f72 6163 6c65 2e63 6f6d 2f22 200a  x.oracle.com/" .
00000d0: 4255 475f 5245 504f 5254 5f55 524c 3d22  BUG_REPORT_URL="
00000e0: 6874 7470 733a 2f2f 6275 677a 696c 6c61  https://bugzilla
00000f0: 2e6f 7261 636c 652e 636f 6d2f 2220 0a0a  .oracle.com/" ..
0000100: 4f52 4143 4c45 5f42 5547 5a49 4c4c 415f  ORACLE_BUGZILLA_
0000110: 5052 4f44 5543 543d 224f 7261 636c 6520  PRODUCT="Oracle 
0000120: 4c69 6e75 7820 3622 200a 4f52 4143 4c45  Linux 6" .ORACLE
0000130: 5f42 5547 5a49 4c4c 415f 5052 4f44 5543  _BUGZILLA_PRODUC
0000140: 545f 5645 5253 494f 4e3d 362e 3920 0a4f  T_VERSION=6.9 .O
0000150: 5241 434c 455f 5355 5050 4f52 545f 5052  RACLE_SUPPORT_PR
0000160: 4f44 5543 543d 224f 7261 636c 6520 4c69  ODUCT="Oracle Li
0000170: 6e75 7822 200a 4f52 4143 4c45 5f53 5550  nux" .ORACLE_SUP
0000180: 504f 5254 5f50 524f 4455 4354 5f56 4552  PORT_PRODUCT_VER
0000190: 5349 4f4e 3d36 2e39 0a                   SION=6.9.
```

and

```
07:50:59 [jason:~] $ curl -sS -L https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=oraclelinux/53/consoleText | grep PRETTY_NAME | xxd
00000000: 2020 203e 2054 6872 6f77 6162 6c65 2023     > Throwable #
00000010: 313a 206a 6176 612e 6c61 6e67 2e41 7373  1: java.lang.Ass
00000020: 6572 7469 6f6e 4572 726f 723a 201b 5b31  ertionError: .[1
00000030: 3b33 316d 1b5b 4b50 5245 5454 595f 4e41  ;31m.[KPRETTY_NA
00000040: 4d45 1b5b 6d1b 5b4b 3d22 4f72 6163 6c65  ME.[m.[K="Oracle
00000050: 204c 696e 7578 2053 6572 7665 7220 362e   Linux Server 6.
00000060: 3922 200a                                9" .
```

**Comment by jasontedor** [comment]
I opened #35451.
