### ISSUE TITLE
[CI] Broken packaging tests on Centos6

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#35440]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-tests/77/console

Reproduces reliably
```
./gradlew :qa:vagrant:vagrantCentos6#batsPackagingTest
```

```
04:25:49 # Caused by: java.nio.file.NoSuchFileException: /usr/lib/os-release
04:25:49 # 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:?]
04:25:49 # 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
04:25:49 # 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
04:25:49 # 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:?]
```

Seems to be triggered by #35352 (730ec1d)

**Comment by dliappis** [comment]
Unfortunately `/etc/os-release` isn't available on CentOS/RHEL <7; the available file is `/etc/redhat-release`. I guess we could add another case in [here](https://github.com/elastic/elasticsearch/pull/35352/files#diff-9c14f590953a8b8f88dfc2b0249dc237R581) for `/etc/redhat-release`) until RHEL-6 becomes truly EOL, which seems to be [far in the future](https://access.redhat.com/support/policy/updates/errata#).

**Comment by romseygeek** [comment]
Also causing failures in `:test:framework` on CentOS:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+periodic/160/console

```
Caused by: java.nio.file.NoSuchFileException: /usr/lib/os-release
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at org.apache.lucene.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:192)
	at org.apache.lucene.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:192)
	at org.apache.lucene.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:192)
	at org.apache.lucene.mockfile.HandleTrackingFS.newInputStream(HandleTrackingFS.java:92)
	at org.apache.lucene.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:192)
	at org.apache.lucene.mockfile.HandleTrackingFS.newInputStream(HandleTrackingFS.java:92)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at java.nio.file.Files.newBufferedReader(Files.java:2784)
	at java.nio.file.Files.readAllLines(Files.java:3202)
	at java.nio.file.Files.readAllLines(Files.java:3242)
	at org.elasticsearch.monitor.os.OsProbe.readOsRelease(OsProbe.java:582)
	at org.elasticsearch.monitor.os.OsProbe.getPrettyName(OsProbe.java:543)
	at org.elasticsearch.monitor.os.OsProbe.osInfo(OsProbe.java:530)
	at org.elasticsearch.monitor.os.OsService.<init>(OsService.java:45)
	at org.elasticsearch.monitor.MonitorService.<init>(MonitorService.java:47)
	at org.elasticsearch.node.Node.<init>(Node.java:398)
	... 45 more
```

**Comment by jasontedor** [comment]
I opened #35453.
