### ISSUE TITLE
[CI] :plugins:repository-s3:s3Fixture failure on 6.4

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#35461]
Starting up the Amazon S3 fixture fails with the error message:

```
Exception in thread "main" java.lang.IllegalArgumentException: bucket null is already registered
15:25:44 
15:25:44     	at org.elasticsearch.repositories.s3.AmazonS3Fixture$Bucket.<init>(AmazonS3Fixture.java:453)
15:25:44     	at org.elasticsearch.repositories.s3.AmazonS3Fixture$Bucket.<init>(AmazonS3Fixture.java:429)
15:25:44     	at org.elasticsearch.repositories.s3.AmazonS3Fixture.<init>(AmazonS3Fixture.java:92)
15:25:44     	at org.elasticsearch.repositories.s3.AmazonS3Fixture.main(AmazonS3Fixture.java:175)
```

See https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+third-party-tests-s3/10 for an example.  It looks as though this particular job has never passed?

**Comment by jaymode** [comment]
Another failure https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+third-party-tests-s3/14/console

**Comment by DaveCTurner** [comment]
Another: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+third-party-tests-s3/15/consoleText

**Comment by tlrx** [comment]
@vladimirdolzhenko Does it ring a bell to you? I'm wondering if #32353 should be backported to 6.4

**Comment by vladimirdolzhenko** [comment]
@tlrx yes, you're right, did we have third party tests for 6.4 before ?

**Comment by tlrx** [comment]
@vladimirdolzhenko I'm not sure when they were added (@fatmcgav might know). Anyway, would backporting #32353 fix the test?

**Comment by fatmcgav** [comment]
So the CI jobs for 'third-party' testing on S3 for `master` and `6.x` were added on 26th June via https://github.com/elastic/infra/pull/5680.

This was expanded to cover `6.4` and `6.5` as part of https://github.com/elastic/infra/pull/7604, as confirmed in https://github.com/elastic/infra/issues/1063#issuecomment-434221017 with @jasontedor 

HTH
