### ISSUE TITLE
[CI] AutoFollowIT#testConflictingPatterns failing

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#35480]
Hey all, not sure if this is real or not, but popped up on my PR test. May be worth investigating?

CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/2600/

```
./gradlew :x-pack:plugin:ccr:internalClusterTest -Dtests.seed=4205CBCCCD58E520 -Dtests.class=org.elasticsearch.xpack.ccr.AutoFollowIT -Dtests.method="testConflictingPatterns" -Dtests.security.manager=true -Dtests.locale=es-PY -Dtests.timezone=Pacific/Majuro -Dcompiler.java=11 -Druntime.java=8
```

stacks

```
  1> Caused by: org.elasticsearch.transport.RemoteTransportException: [leader0][127.0.0.1:53885][indices:data/read/xpack/ccr/shard_changes[s]]
  1> Caused by: org.elasticsearch.index.shard.IndexShardClosedException: CurrentState[CLOSED] Closed
  1> 	at org.elasticsearch.index.shard.GlobalCheckpointListeners.close(GlobalCheckpointListeners.java:158) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:103) ~[elasticsearch-core-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:61) ~[elasticsearch-core-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.index.shard.IndexShard.close(IndexShard.java:1187) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.index.IndexService.closeShard(IndexService.java:436) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.index.IndexService.removeShard(IndexService.java:419) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.index.IndexService.close(IndexService.java:277) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.indices.IndicesService.removeIndex(IndicesService.java:638) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.deleteIndices(IndicesClusterStateService.java:286) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
```

**Comment by javanna** [comment]
Same test but a different failure here: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/72 .

```
16:58:09 FAILURE 30.1s J0 | AutoFollowIT.testConflictingPatterns <<< FAILURES!
16:58:09    > Throwable #1: java.lang.AssertionError: 
16:58:09    > Expected: <0L>
16:58:09    >      but: was <1L>
16:58:09    > 	at __randomizedtesting.SeedInfo.seed([D307FB40E8829BD7:C074EF21CD3507C2]:0)
16:58:09    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
16:58:09    > 	at org.elasticsearch.xpack.ccr.AutoFollowIT.lambda$testConflictingPatterns$6(AutoFollowIT.java:217)
16:58:09    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:848)
16:58:09    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:822)
16:58:09    > 	at org.elasticsearch.xpack.ccr.AutoFollowIT.testConflictingPatterns(AutoFollowIT.java:214)
16:58:09    > 	at java.lang.Thread.run(Thread.java:748)
16:58:09    > 	Suppressed: java.lang.AssertionError: 
16:58:09    > Expected: <1L>
16:58:09    >      but: was <0L>
16:58:09    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
16:58:09    > 		at org.elasticsearch.xpack.ccr.AutoFollowIT.lambda$testConflictingPatterns$6(AutoFollowIT.java:216)
16:58:09    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:836)
16:58:09    > 		... 39 more
16:58:09    > 	Suppressed: java.lang.AssertionError: 
16:58:09    > Expected: <1L>
16:58:09    >      but: was <0L>
16:58:09    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
16:58:09    > 		at org.elasticsearch.xpack.ccr.AutoFollowIT.lambda$testConflictingPatterns$6(AutoFollowIT.java:216)
16:58:09    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:836)
16:58:09    > 		... 39 more
16:58:09    > 	Suppressed: java.lang.AssertionError: .....................
```

**Comment by martijnvg** [comment]
The leader index gets created and at the same time the auto follow coordinator fetch the remote cluster state. Not all primary shards have been allocated, because the create index request for leader index has not returned. This causes index following to fail, because not all primary shards have history uuid in its index shard stats.

I will work on a change that let the auto follow coordinator wait with auto following an index until all primary have been started. This should avoid these situations.

**Comment by martijnvg** [comment]
Another instance of this failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.5+multijob-darwin-compatibility/64/console
