### ISSUE TITLE
[CI] DocsClientYamlTestSuiteIT {yaml=reference/ilm/apis/explain/line_49} failure

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#35515]
The docs test for {yaml=reference/ilm/apis/explain/line_49} failed in CI.

Build link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=fedora/56/console

Reproduce line:

```
./gradlew :docs:integTestRunner \
  -Dtests.seed=23723CB858621B1E \
  -Dtests.class=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT \
  -Dtests.method="test {yaml=reference/ilm/apis/explain/line_49}" \
  -Dtests.security.manager=true \
  -Dtests.locale=el-GR \
  -Dtests.timezone=America/Argentina/Catamarca \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Failure:

```
java.lang.RuntimeException: Failure at [reference/ilm/apis/explain:60]: stashed value not found for key [body.indices.my_index.lifecycle_date_millis]
	at __randomizedtesting.SeedInfo.seed([23723CB858621B1E:AB260362F69E76E6]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:408)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:383)
```

**Comment by hendrikmuhs** [comment]
happened again: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=fedora/57/consoleFull
