### ISSUE TITLE
Connection issues in CoreFullClusterRestart tests on 6.4

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#35520]
A couple of builds have failed in the CoreFullClusterRestartIT test. The tests see listener timeouts and refused connections. It is not clear to me what causes this. Example builds:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+periodic/168/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+bwc-tests/54/console

```
java.io.IOException: listener timeout after waiting for [30000] ms
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:899)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:227)
	at org.elasticsearch.upgrades.FullClusterRestartIT.indexRandomDocuments(FullClusterRestartIT.java:1086)
	at org.elasticsearch.upgrades.FullClusterRestartIT.testShrinkAfterUpgrade(FullClusterRestartIT.java:451)
```

```
java.net.ConnectException: Connection refused
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:943)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:227)
	at org.elasticsearch.test.rest.ESRestTestCase.wipeSnapshots(ESRestTestCase.java:307)
	at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:297)
	at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:176)
```

**Comment by DaveCTurner** [comment]
It very much looks like one of the two nodes just vanished. `node-1`'s logs look normal until the end:

```
[2018-11-13T20:40:29,432][DEBUG][o.e.x.s.a.e.ReservedRealm] [node-1] user [test_user] not found in cache for realm [reserved], proceeding with normal authentication
[2018-11-13T20:40:29,432][DEBUG][o.e.x.s.a.f.FileRealm    ] [node-1] realm [default_file] authenticated user [test_user], with roles [[superuser]]
[2018-11-13T20:40:29,445][DEBUG][o.e.x.s.a.e.ReservedRealm] [node-1] user [test_user] not found in cache for realm [reserved], proceeding with normal authentication
[2018-11-13T20:40:29,445][DEBUG][o.e.x.s.a.f.FileRealm    ] [node-1] realm [default_file] authenticated user [test_user], with roles [[superuser]]
[2018-11-13T20:40:29,462][DEBUG][o.e.x.s.a.e.ReservedRealm] [node-1] user [test_user] not found in cache for realm [reserved], proceeding with normal authentication
[2018-11-13T20:40:29,462][DEBUG][o.e.x.s.a.f.FileRealm    ] [node-1] realm [default_file] authenticated user [test_user], with roles [[superuser]]
[2018-11-13T20:40:29,474][DEBUG][o.e.x.s.a.e.ReservedRealm] [node-1] user [test_user] not found in cache for realm [reserved], proceeding with normal authentication
[2018-11-13T20:40:29,474][DEBUG][o.e.x.s.a.f.FileRealm    ] [node-1] realm [default_file] authenticated user [test_user], with roles [[superuser]]
[2018-11-13T20:40:29,489][DEBUG][o.e.x.s.a.e.ReservedRealm] [node-1] user [test_user] not found in cache for realm [reserved], proceeding with normal authentication
[2018-11-13T20:40:29,489][DEBUG][o.e.x.s.a.f.FileRealm    ] [node-1] realm [default_file] authenticated user [test_user], with roles [[superuser]]
// (END OF FILE)
```

At approximately the same time we get `NodeDisconnectedException`s on the other node:

```
[2018-11-13T20:40:29,577][DEBUG][o.e.c.a.s.ShardStateAction] [node-0] [testshrinkafterupgrade][2] sending [internal:cluster/shard/failure] to [YfNyHp11Stmcv_deOYm3hQ] for shard entry [shard id [[testshrinkafterupgrade][2]], allocation id [MGgoRdWZQFe6tDX0vgk8Hw], primary term [1], message [failed to perform indices:admin/flush[s] on replica [testshrinkafterupgrade][2], node[gwX81RPDTASGiIRET9iwaQ], [R], recovery_source[peer recovery], s[INITIALIZING], a[id=MGgoRdWZQFe6tDX0vgk8Hw], unassigned_info[[reason=INDEX_CREATED], at[2018-11-13T20:40:28.940Z], delayed=false, allocation_status[no_attempt]]], failure [NodeDisconnectedException[[node-1][127.0.0.1:35896][indices:admin/flush[s][r]] disconnected]]]
```

I think there's no information about why this node failed, but https://github.com/elastic/elasticsearch/issues/35587#issuecomment-439087392 might help hear too.

**Comment by talevy** [comment]
Closing due to no mentions of re-occurrences of this issue
in current development branches. 6.4 CI was disabled.
