### ISSUE TITLE
Parse errors in SamlAuthenticatorTests

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#35579]
A variety of `SamlAuthenticatorTests` failed with similar-looking messages about parse failures:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java10,nodes=virtual&&linux/60/console

```
ElasticsearchSecurityException[Failed to parse SAML message]; nested: SAXParseException[src-resolve: Cannot resolve the name 'samlp:ExtensionsType' to a(n) 'type definition' component.];
	at __randomizedtesting.SeedInfo.seed([17C4304BB3DF01F8:C8E2BB7156DFE519]:0)
	at org.elasticsearch.xpack.security.authc.saml.SamlUtils.samlException(SamlUtils.java:114)
	at org.elasticsearch.xpack.security.authc.saml.SamlRequestHandler.parseSamlMessage(SamlRequestHandler.java:292)
	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticator.authenticate(SamlAuthenticator.java:69)
	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticatorTests.testExpiredAuthnStatementSessionIsRejected(SamlAuthenticatorTests.java:774)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1713)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:907)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:943)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:957)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:916)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:802)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:852)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:863)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.xml.sax.SAXParseException; systemId: file:/var/lib/jenkins/workspace/elastic+elasticsearch+6.4+matrix-java-periodic/ES_BUILD_JAVA/java10/ES_RUNTIME_JAVA/java10/nodes/virtual&&linux/x-pack/plugin/security/build/resources/main/org/elasticsearch/xpack/security/authc/saml/saml-schema-protocol-2.0.xsd; lineNumber: 41; columnNumber: 61; src-resolve: Cannot resolve the name 'samlp:ExtensionsType' to a(n) 'type definition' component.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4212)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaError(XSDHandler.java:4195)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getGlobalDecl(XSDHandler.java:1770)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseNamedElement(XSDElementTraverser.java:405)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDElementTraverser.traverseGlobal(XSDElementTraverser.java:242)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.traverseSchemas(XSDHandler.java:1462)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:644)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.processJAXPSchemaSource(XMLSchemaLoader.java:844)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:606)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2710)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2069)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:829)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3058)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:821)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:532)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:122)
	at org.elasticsearch.xpack.security.authc.saml.SamlRequestHandler.parseSamlMessage(SamlRequestHandler.java:286)
	... 38 more
```

```

REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=17C4304BB3DF01F8 \
  -Dtests.class=org.elasticsearch.xpack.security.authc.saml.SamlAuthenticatorTests \
  -Dtests.method="testContentIsAcceptedIfRestrictedToOurAudience" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Cyrl-XK \
  -Dtests.timezone=Pacific/Kiritimati

REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=17C4304BB3DF01F8 \
  -Dtests.class=org.elasticsearch.xpack.security.authc.saml.SamlAuthenticatorTests \
  -Dtests.method="testParsingRejectsTamperedContent" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Cyrl-XK \
  -Dtests.timezone=Pacific/Kiritimati

REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=17C4304BB3DF01F8 \
  -Dtests.class=org.elasticsearch.xpack.security.authc.saml.SamlAuthenticatorTests \
  -Dtests.method="testSuccessfullyParseContentWithMultipleValidAttributes" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Cyrl-XK \
  -Dtests.timezone=Pacific/Kiritimati

REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=17C4304BB3DF01F8 \
  -Dtests.class=org.elasticsearch.xpack.security.authc.saml.SamlAuthenticatorTests \
  -Dtests.method="testSignatureWrappingAttackFour" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Cyrl-XK \
  -Dtests.timezone=Pacific/Kiritimati

REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=17C4304BB3DF01F8 \
  -Dtests.class=org.elasticsearch.xpack.security.authc.saml.SamlAuthenticatorTests \
  -Dtests.method="testIncorrectSigningKeyIsRejected" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Cyrl-XK \
  -Dtests.timezone=Pacific/Kiritimati

REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=17C4304BB3DF01F8 \
  -Dtests.class=org.elasticsearch.xpack.security.authc.saml.SamlAuthenticatorTests \
  -Dtests.method="testIncorrectRecipientIsRejected" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Cyrl-XK \
  -Dtests.timezone=Pacific/Kiritimati

REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=17C4304BB3DF01F8 \
  -Dtests.class=org.elasticsearch.xpack.security.authc.saml.SamlAuthenticatorTests \
  -Dtests.method="testContentIsRejectedIfNotMarkedAsSuccess" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Cyrl-XK \
  -Dtests.timezone=Pacific/Kiritimati

REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=17C4304BB3DF01F8 \
  -Dtests.class=org.elasticsearch.xpack.security.authc.saml.SamlAuthenticatorTests \
  -Dtests.method="testExpiredAuthnStatementSessionIsRejected" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Cyrl-XK \
  -Dtests.timezone=Pacific/Kiritimati

REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=17C4304BB3DF01F8 \
  -Dtests.class=org.elasticsearch.xpack.security.authc.saml.SamlAuthenticatorTests \
  -Dtests.method="testAssertionWithoutAuthnStatementIsRejected" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Cyrl-XK \
  -Dtests.timezone=Pacific/Kiritimati

REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=17C4304BB3DF01F8 \
  -Dtests.class=org.elasticsearch.xpack.security.authc.saml.SamlAuthenticatorTests \
  -Dtests.method="testIncorrectDestinationIsRejected" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Cyrl-XK \
  -Dtests.timezone=Pacific/Kiritimati
```

A possibly-related failure occurred here, although only in one test: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java10,nodes=virtual&&linux/35/console

I tried one of the `REPRODUCE WITH` lines above and it did not fail for me.

**Comment by jaymode** [comment]
@jkakavas can you take a look at this? I'm not sure if it has happened again or not, so that's also something to look into.

**Comment by jkakavas** [comment]
I couldn't come to a meaningful conclusion about what could have caused it. This definitely looks related to `-Dtests.locale=sr-Cyrl-XK` but I have been unable to reproduce it locally in6.4 or any of the branches for that matter. Given that we haven't seen this again apart from that specific time and only in 6.4, I will close this issue
