### ISSUE TITLE
CI logs are sometimes heavily interleaved

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#35588]
For instance, this build's output contains the following text: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java8fips,nodes=virtual&&linux/59/console

```
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:159) [x-pack-5.6.14-SNAPSHOT.jar:5.6.14-SNAPSHOT]
	at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:122) [x-pack-5.6.14-SNAPSHOT.jar:5.6.14-SNAPSHOT]
-----------
	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.inbound(ServerTransportFilter.java:146) [x-pack-5.6.14-SNAPSHOT.jar:5.6.14-SNAPSHOT]
* What went wrong:
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:314) [x-pack-5.6.14-SNAPSHOT.jar:5.6.14-SNAPSHOT]
Execution failed for task ':x-pack:qa:full-cluster-restart:with-system-key:v5.6.14-SNAPSHOT#oldClusterTestCluster#node0.stop'.
> Process 'command 'kill'' finished with non-zero exit value 1

	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) [elasticsearch-5.6.14-SNAPSHOT.jar:5.6.14-SNAPSHOT]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:662) [elasticsearch-5.6.14-SNAPSHOT.jar:5.6.14-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:675) [elasticsearch-5.6.14-SNAPSHOT.jar:5.6.14-SNAPSHOT]
* Try:
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.14-SNAPSHOT.jar:5.6.14-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
==============================================================================

[2018-11-14T22:11:36,748][WARN ][o.e.a.a.i.f.TransportShardFlushAction] [node-1] [[testshrink][3]] failed to perform indices:admin/flush[s] on replica [testshrink][3], node[VQE8MrTsSwuxGnne49sQiw], [R], s[STARTED], a[id=a6CYj0ibRBaBqrUbSltgWw]
org.elasticsearch.transport.NodeNotConnectedException: [node-0][127.0.0.1:38552] Node not connected
* Get more help at https://help.gradle.org
	at org.elasticsearch.transport.TcpTransport.getConnection(TcpTransport.java:640) ~[elasticsearch-5.6.14-SNAPSHOT.jar:5.6.14-SNAPSHOT]
	at org.elasticsearch.transport.TcpTransport.getConnection(TcpTransport.java:117) ~[elasticsearch-5.6.14-SNAPSHOT.jar:5.6.14-SNAPSHOT]

	at org.elasticsearch.transport.TransportService.getConnection(TransportService.java:548) ~[elasticsearch-5.6.14-SNAPSHOT.jar:5.6.14-SNAPSHOT]
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:524) [elasticsearch-5.6.14-SNAPSHOT.jar:5.6.14-SNAPSHOT]
BUILD FAILED in 2h 22m 25s
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReplicasProxy.performOn(TransportReplicationAction.java:1001) [elasticsearch-5.6.14-SNAPSHOT.jar:5.6.14-SNAPSHOT]
	at org.elasticsearch.action.support.replication.ReplicationOperation.performOnReplica(ReplicationOperation.java:185) [elasticsearch-5.6.14-SNAPSHOT.jar:5.6.14-SNAPSHOT]
	at org.elasticsearch.action.support.replic
```

Avoiding this kind of interleaving would, I feel, significantly simplify the task of tracking down the cause of a CI failure. Is there anything we can do to improve this?

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/2884/console

A possibly-related observation is that in the above PR build the existence of the checkstyle violation is reported at the bottom of the build, but the actual violation is many hundreds of lines above, separated by BWC build output logs. It'd be great if these things were in a more obvious order.

**Comment by atorok** [comment]
There are two things here. 
One form is from  `ClusterFormationTasks` and the way these stream logs output and stderr.
It's something that I would like to address in test clusters. The output and error go to files there and it's logged on failure in a controlled fashion, so might already be better. 

The other comes from  `--parallel` and how tasks in flight are still completed after one fails. 
For that I proposed elastic/infra#7892

**Comment by atorok** [comment]
WE reduced console output verbosity and mostly rely on build-scans now so I think this is no longer an issue
