### ISSUE TITLE
testUseClusterByUpToDateTask expected UP_TO_DATE but was SUCCESS

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#35581]
The following build failed:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/185/console

The relevant part of the log looks to be the following:

```
org.elasticsearch.gradle.testclusters.TestClustersPluginIT > testUseClusterByUpToDateTask FAILED
    java.lang.AssertionError: Expected task to be up to date but it was: SUCCESS

    Output is:
    The client will now receive all logging from the daemon (pid: 21443). The daemon log file: /tmp/.gradle-test-kit-jenkins/test-kit-daemon/4.10/daemon-21443.out.log
    Starting 2nd build in daemon [uptime: 3.657 secs, performance: 99%, no major garbage collections]
    Closing daemon's stdin at end of input.
    The daemon will no longer process any standard input.
    Using 16 worker leases.
    Starting Build
    Settings evaluated using settings file '/var/lib/jenkins/workspace/elastic+elasticsearch+6.x+intake/buildSrc/src/testKit/testclusters/settings.gradle'.
    Projects loaded. Root project using build file '/var/lib/jenkins/workspace/elastic+elasticsearch+6.x+intake/buildSrc/src/testKit/testclusters/build.gradle'.
    Included projects: [root project 'testclusters']

    > Configure project :
    Evaluating root project 'testclusters' using build file '/var/lib/jenkins/workspace/elastic+elasticsearch+6.x+intake/buildSrc/src/testKit/testclusters/build.gradle'.
    Cluster myTestCluster depends on org.elasticsearch.distribution.zip:elasticsearch:6.6.0-SNAPSHOT@zip
    All projects evaluated.
    Selected primary task 'upToDate1' from project :
    Selected primary task 'upToDate2' from project :
    Tasks to be executed: [task ':syncTestClustersArtifacts', task ':upToDate1', task ':upToDate2']
    Locking configuration of `ElasticsearchNode{name='myTestCluster'}`
    Locking configuration of `ElasticsearchNode{name='myTestCluster'}`
    :syncTestClustersArtifacts (Thread[Task worker for ':',5,main]) started.

    > Task :syncTestClustersArtifacts
    Task ':syncTestClustersArtifacts' is not up-to-date because:
      No history is available.
    :syncTestClustersArtifacts (Thread[Task worker for ':',5,main]) completed. Took 3.57 secs.
    :upToDate1 (Thread[Task worker for ':',5,main]) started.

    > Task :upToDate1
    Skipping task ':upToDate1' as it has no actions.
    :upToDate1 (Thread[Task worker for ':',5,main]) completed. Took 0.001 secs.
    :upToDate2 (Thread[Task worker for ':',5,main]) started.

    > Task :upToDate2
    Skipping task ':upToDate2' as it has no actions.
    :upToDate2 (Thread[Task worker for ':',5,main]) completed. Took 0.0 secs.

    BUILD SUCCESSFUL in 3s
    1 actionable task: 1 executed
     expected:<UP_TO_DATE> but was:<SUCCESS>
        at __randomizedtesting.SeedInfo.seed([F8C5716618E2C25E:4D4188AFC49A8B30]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.elasticsearch.gradle.test.GradleIntegrationTestCase.assertTaskUpToDate(GradleIntegrationTestCase.java:113)
        at org.elasticsearch.gradle.testclusters.TestClustersPluginIT.testUseClusterByUpToDateTask(TestClustersPluginIT.java:59)
```

Looking at build-stats there seems to have been a flurry of such failures in PR builds at around the same time, but otherwise only very occasional mentions of this test in the last year. Not muting it.

**Comment by atorok** [comment]
Thanks for reporting @DaveCTurner !
I pushed a fix for this right after the failure you linked to 6db1a9e32cc.
Subsequent runs failed differently so I'm going to close this.

**Comment by DaveCTurner** [comment]
Got it, sorry for the noise. I saw those comments in the test and thought perhaps the flakiness extended past the first run sometimes, but didn't realise you'd only just introduced them.
