### ISSUE TITLE
IpFilteringIntegrationTests#testThatIpFilteringIsAppliedForProfile failed due to connection refused

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#35584]
This build failed: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java8,nodes=virtual&&linux/59/console

The test log is as follows:

```
  1> [2018-11-14T16:17:29,889][INFO ][o.e.x.s.t.f.IpFilteringIntegrationTests] [testThatIpFilteringIsAppliedForProfile]: before test
  1> [2018-11-14T16:17:29,889][INFO ][o.e.x.s.t.f.IpFilteringIntegrationTests] [IpFilteringIntegrationTests#testThatIpFilteringIsAppliedForProfile]: setting up test
  1> [2018-11-14T16:17:29,890][INFO ][o.e.x.s.a.l.LoggingAuditTrail] [127.0.0.1] [node_s0] [transport] [access_granted]	origin_type=[local_node], origin_address=[127.0.0.1], principal=[test_user], realm=[file], roles=[user], action=[cluster:admin/settings/update], request=[ClusterUpdateSettingsRequest]
  1> [2018-11-14T16:17:29,902][INFO ][o.e.c.m.TemplateUpgradeService] [node_s0] Starting template upgrade to version 6.4.4, 1 templates will be updated and 0 will be removed
  1> [2018-11-14T16:17:29,907][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_s0] adding template [security-index-template] for index patterns [.security-*]
  1> [2018-11-14T16:17:29,916][INFO ][o.e.c.m.TemplateUpgradeService] [node_s0] Templates were upgraded successfuly to version 6.4.4
  1> [2018-11-14T16:17:29,918][INFO ][o.e.n.Node               ] [node_s0] stopping ...
  1> [2018-11-14T16:17:29,940][INFO ][o.e.n.Node               ] [node_s0] stopped
  1> [2018-11-14T16:17:29,940][INFO ][o.e.n.Node               ] [node_s0] closing ...
  1> [2018-11-14T16:17:29,947][INFO ][o.e.n.Node               ] [node_s0] closed
  1> [2018-11-14T16:17:29,948][INFO ][o.e.t.InternalTestCluster] Successfully wiped data directory for node location: /var/lib/jenkins/workspace/elastic+elasticsearch+6.4+matrix-java-periodic/ES_BUILD_JAVA/java10/ES_RUNTIME_JAVA/java8/nodes/virtual&&linux/x-pack/plugin/security/build/testrun/test/J2/temp/org.elasticsearch.xpack.security.transport.filter.IpFilteringIntegrationTests_C74DBACEF7B47797-001/tempDir-004/d1/nodes/0
  1> [2018-11-14T16:17:29,948][INFO ][o.e.t.InternalTestCluster] Successfully wiped data directory for node location: /var/lib/jenkins/workspace/elastic+elasticsearch+6.4+matrix-java-periodic/ES_BUILD_JAVA/java10/ES_RUNTIME_JAVA/java8/nodes/virtual&&linux/x-pack/plugin/security/build/testrun/test/J2/temp/org.elasticsearch.xpack.security.transport.filter.IpFilteringIntegrationTests_C74DBACEF7B47797-001/tempDir-004/d0/nodes/0
  1> [2018-11-14T16:17:29,948][INFO ][o.e.x.s.t.f.IpFilteringIntegrationTests] [IpFilteringIntegrationTests#testThatIpFilteringIsAppliedForProfile]: all set up test
  1> [2018-11-14T16:17:29,953][INFO ][o.e.n.Node               ] [node_s0] initializing ...
  1> [2018-11-14T16:17:29,957][INFO ][o.e.e.NodeEnvironment    ] [node_s0] using [2] data paths, mounts [[/ (rootfs)]], net usable_space [462.1gb], net total_space [503.8gb], types [rootfs]
  1> [2018-11-14T16:17:29,957][INFO ][o.e.e.NodeEnvironment    ] [node_s0] heap size [491mb], compressed ordinary object pointers [true]
  1> [2018-11-14T16:17:29,958][INFO ][o.e.n.Node               ] [node_s0] node name [node_s0], node ID [2vc3m46IROmgqkb_e0_wog]
  1> [2018-11-14T16:17:29,958][INFO ][o.e.n.Node               ] [node_s0] version[6.4.4-SNAPSHOT], pid[15179], build[unknown/unknown/f415244/2018-11-14T19:46:56.321139Z], OS[Linux/3.16.0-6-amd64/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_192/25.192-b12]
  1> [2018-11-14T16:17:29,958][INFO ][o.e.n.Node               ] [node_s0] JVM arguments [-Dfile.encoding=UTF8, -ea, -esa, -Xmx512m, -Xms512m, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/var/lib/jenkins/workspace/elastic+elasticsearch+6.4+matrix-java-periodic/ES_BUILD_JAVA/java10/ES_RUNTIME_JAVA/java8/nodes/virtual&&linux/x-pack/plugin/security/build/heapdump, -Dtests.prefix=tests, -Dtests.seed=C74DBACEF7B47797, -Dtests.security.manager=true, -Djava.io.tmpdir=./temp, -Dtests.gradle=true, -Des.set.netty.runtime.available.processors=false, -Dtests.artifact=security, -Des.scripting.exception_for_missing_value=true, -Djava.awt.headless=true, -Dtests.task=:x-pack:plugin:security:test, -Djna.nosys=true, -Dtests.logger.level=WARN, -Djunit4.childvm.cwd=/var/lib/jenkins/workspace/elastic+elasticsearch+6.4+matrix-java-periodic/ES_BUILD_JAVA/java10/ES_RUNTIME_JAVA/java8/nodes/virtual&&linux/x-pack/plugin/security/build/testrun/test/J2, -Djunit4.childvm.id=2, -Djunit4.childvm.count=4]
  1> [2018-11-14T16:17:29,958][WARN ][o.e.n.Node               ] [node_s0] version [6.4.4-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
  1> [2018-11-14T16:17:29,962][INFO ][o.e.p.PluginsService     ] [node_s0] no modules loaded
  1> [2018-11-14T16:17:29,962][INFO ][o.e.p.PluginsService     ] [node_s0] loaded plugin [org.elasticsearch.analysis.common.CommonAnalysisPlugin]
  1> [2018-11-14T16:17:29,962][INFO ][o.e.p.PluginsService     ] [node_s0] loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
  1> [2018-11-14T16:17:29,962][INFO ][o.e.p.PluginsService     ] [node_s0] loaded plugin [org.elasticsearch.test.ESIntegTestCase$AssertActionNamePlugin]
  1> [2018-11-14T16:17:29,962][INFO ][o.e.p.PluginsService     ] [node_s0] loaded plugin [org.elasticsearch.test.ESIntegTestCase$TestSeedPlugin]
  1> [2018-11-14T16:17:29,962][INFO ][o.e.p.PluginsService     ] [node_s0] loaded plugin [org.elasticsearch.test.InternalSettingsPlugin]
  1> [2018-11-14T16:17:29,962][INFO ][o.e.p.PluginsService     ] [node_s0] loaded plugin [org.elasticsearch.test.discovery.TestZenDiscovery$TestPlugin]
  1> [2018-11-14T16:17:29,962][INFO ][o.e.p.PluginsService     ] [node_s0] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
  1> [2018-11-14T16:17:29,962][INFO ][o.e.p.PluginsService     ] [node_s0] loaded plugin [org.elasticsearch.xpack.security.LocalStateSecurity]
  1> [2018-11-14T16:17:30,583][INFO ][o.e.x.s.a.s.FileRolesStore] [node_s0] parsed [1] roles from file [/var/lib/jenkins/workspace/elastic+elasticsearch+6.4+matrix-java-periodic/ES_BUILD_JAVA/java10/ES_RUNTIME_JAVA/java8/nodes/virtual&&linux/x-pack/plugin/security/build/testrun/test/J2/temp/org.elasticsearch.xpack.security.transport.filter.IpFilteringIntegrationTests_C74DBACEF7B47797-001/tempDir-003/SUITE-0/config/roles.yml]
  1> [2018-11-14T16:17:30,601][INFO ][o.e.d.DiscoveryModule    ] [node_s0] using discovery type [test-zen]
  1> [2018-11-14T16:17:30,623][INFO ][o.e.n.Node               ] [node_s0] initialized
  1> [2018-11-14T16:17:30,623][INFO ][o.e.n.Node               ] [node_s0] starting ...
  1> [2018-11-14T16:17:30,629][INFO ][o.e.t.TransportService   ] [node_s0] publish_address {127.0.0.1:30361}, bound_addresses {127.0.0.1:30361}
  1> [2018-11-14T16:17:30,629][INFO ][o.e.t.TransportService   ] [node_s0] profile [client]: publish_address {127.0.0.1:58509}, bound_addresses {127.0.0.1:58509}, {[::1]:58508}
  1> [2018-11-14T16:17:30,631][INFO ][o.e.t.d.MockZenPing      ] [node_s0] pinging using mock zen ping
  1> [2018-11-14T16:17:30,633][INFO ][o.e.c.s.MasterService    ] [node_s0] zen-disco-elected-as-master ([0] nodes joined)[, ], reason: new_master {node_s0}{2vc3m46IROmgqkb_e0_wog}{gTLPKczOROSp8M9feGOyYg}{127.0.0.1}{127.0.0.1:30361}{xpack.installed=true}
  1> [2018-11-14T16:17:30,633][INFO ][o.e.c.s.ClusterApplierService] [node_s0] new_master {node_s0}{2vc3m46IROmgqkb_e0_wog}{gTLPKczOROSp8M9feGOyYg}{127.0.0.1}{127.0.0.1:30361}{xpack.installed=true}, reason: apply cluster state (from master [master {node_s0}{2vc3m46IROmgqkb_e0_wog}{gTLPKczOROSp8M9feGOyYg}{127.0.0.1}{127.0.0.1:30361}{xpack.installed=true} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)[, ]]])
  1> [2018-11-14T16:17:30,649][INFO ][o.e.x.s.t.n.SecurityNetty4HttpServerTransport] [node_s0] publish_address {127.0.0.1:55600}, bound_addresses {[::1]:45652}, {127.0.0.1:55600}
  1> [2018-11-14T16:17:30,649][INFO ][o.e.n.Node               ] [node_s0] started
  1> [2018-11-14T16:17:30,652][INFO ][o.e.g.GatewayService     ] [node_s0] recovered [0] indices into cluster_state
  1> [2018-11-14T16:17:30,681][INFO ][o.e.x.s.t.f.IpFilteringIntegrationTests] connecting to localhost/127.0.0.1:58508
  1> [2018-11-14T16:17:30,682][INFO ][o.e.x.s.t.f.IpFilteringIntegrationTests] [IpFilteringIntegrationTests#testThatIpFilteringIsAppliedForProfile]: cleaning up after test
  1> [2018-11-14T16:17:30,724][INFO ][o.e.l.LicenseService     ] [node_s0] license [23ecf91e-e913-4ab4-98b9-d9f5424faee7] mode [trial] - valid
  1> [2018-11-14T16:17:30,726][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_s0] removing template [security_audit_log]
  1> [2018-11-14T16:17:30,730][INFO ][o.e.c.m.TemplateUpgradeService] [node_s0] Starting template upgrade to version 6.4.4, 1 templates will be updated and 0 will be removed
  1> [2018-11-14T16:17:30,733][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_s0] adding template [security_audit_log] for index patterns [.security_audit_log*]
  1> [2018-11-14T16:17:30,737][INFO ][o.e.c.m.TemplateUpgradeService] [node_s0] Templates were upgraded successfuly to version 6.4.4
  1> [2018-11-14T16:17:30,738][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_s0] removing template [security-index-template]
  1> [2018-11-14T16:17:30,744][INFO ][o.e.c.m.TemplateUpgradeService] [node_s0] Starting template upgrade to version 6.4.4, 1 templates will be updated and 0 will be removed
  1> [2018-11-14T16:17:30,748][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_s0] adding template [security-index-template] for index patterns [.security-*]
  1> [2018-11-14T16:17:30,751][INFO ][o.e.c.m.TemplateUpgradeService] [node_s0] Templates were upgraded successfuly to version 6.4.4
  1> [2018-11-14T16:17:30,753][INFO ][o.e.x.s.t.f.IpFilteringIntegrationTests] [IpFilteringIntegrationTests#testThatIpFilteringIsAppliedForProfile]: cleaned up after test
  1> [2018-11-14T16:17:30,753][INFO ][o.e.x.s.t.f.IpFilteringIntegrationTests] [testThatIpFilteringIsAppliedForProfile]: after test
ERROR   0.89s J2 | IpFilteringIntegrationTests.testThatIpFilteringIsAppliedForProfile <<< FAILURES!
   > Throwable #1: java.net.ConnectException: Connection refused (Connection refused)
   > 	at __randomizedtesting.SeedInfo.seed([C74DBACEF7B47797:DDA439BDA55B298F]:0)
   > 	at java.net.PlainSocketImpl.socketConnect(Native Method)
   > 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
   > 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
   > 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
   > 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
   > 	at java.net.Socket.connect(Socket.java:589)
   > 	at org.elasticsearch.xpack.security.transport.filter.IpFilteringIntegrationTests.lambda$trySocketConnection$0(IpFilteringIntegrationTests.java:77)
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+6.4+matrix-java-periodic/ES_BUILD_JAVA/java10/ES_RUNTIME_JAVA/java8/nodes/virtual&&linux/x-pack/plugin/security/build/testrun/test/J2/temp/org.elasticsearch.xpack.security.transport.filter.IpFilteringIntegrationTests_C74DBACEF7B47797-001
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=1230, maxMBSortInHeap=7.351264520082991, sim=RandomSimilarity(queryNorm=false): {}, locale=lv, timezone=US/East-Indiana
   > 	at org.elasticsearch.xpack.core.common.socket.SocketAccess.lambda$doPrivileged$0(SocketAccess.java:42)
  2> NOTE: Linux 3.16.0-6-amd64 amd64/Oracle Corporation 1.8.0_192 (64-bit)/cpus=16,threads=1,free=297622072,total=503840768
   > 	at java.security.AccessController.doPrivileged(Native Method)
   > 	at org.elasticsearch.xpack.core.common.socket.SocketAccess.doPrivileged(SocketAccess.java:41)
   > 	at org.elasticsearch.xpack.security.transport.filter.IpFilteringIntegrationTests.trySocketConnection(IpFilteringIntegrationTests.java:77)
  2> NOTE: All tests run in this JVM: [DistinguishedNamePredicateTests, ShrinkIndexWithSecurityTests, DocumentLevelSecurityRandomTests, KerberosRealmTests, SamlPrepareAuthenticationRequestTests, ResizeRequestInterceptorTests, SecurityContextTests, PermissionTests, TransportChangePasswordActionTests, NativeUsersStoreTests, UsernamePasswordTokenTests, SamlBaseRestHandlerTests, SamlUtilsTests, IndexPrivilegeTests, FIPS140SecureSettingsBootstrapCheckTests, SetupPasswordToolTests, HasPrivilegesRequestBuilderTests, SamlAuthenticatorTests, SessionFactoryTests, TransportPutUserActionTests, AuthenticationServiceTests, MultipleIndicesPermissionsTests, LdapRealmTests, ClearRolesCacheTests, SSLTrustRestrictionsTests, SamlMetadataCommandTests, IPHostnameVerificationTests, SecurityRestFilterTests, KerberosAuthenticationTokenTests, PutPrivilegesRequestBuilderTests, TransportPutRoleActionTests, SecurityServerTransportInterceptorTests, SecurityTests, SslNullCipherTests, SecuritySearchOperationListenerTests, NativeRolesStoreTests, ClusterPrivilegeTests, LicensingTests, TokenPassphraseBootstrapCheckTests, TokenSSLBootsrapCheckTests, SecurityActionMapperTests, PutRoleMappingRequestTests, PutUserRequestBuilderTests, TransportDeleteUserActionTests, AuditLevelTests, AuditTrailServiceTests, AuditUtilTests, IndexAuditTrailMutedTests, IndexAuditTrailTests, TokenAuthIntegTests, NativeRoleMappingStoreTests, AnalyzeTests, IndicesAndAliasesResolverTests, FieldDataCacheWithFieldSubsetReaderTests, FieldExtractorTests, IndicesAccessControlTests, CompositeRolesStoreTests, ServerTransportFilterTests, IPFilterTests, IpFilteringIntegrationTests]
   > 	at org.elasticsearch.xpack.security.transport.filter.IpFilteringIntegrationTests.testThatIpFilteringIsAppliedForProfile(IpFilteringIntegrationTests.java:69)
```

The claimed `REPRODUCE WITH` line does not reproduce for me:

```
./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=C74DBACEF7B47797 \
  -Dtests.class=org.elasticsearch.xpack.security.transport.filter.IpFilteringIntegrationTests \
  -Dtests.method="testThatIpFilteringIsAppliedForProfile" \
  -Dtests.security.manager=true \
  -Dtests.locale=lv \
  -Dtests.timezone=US/East-Indiana
```

I see only very occasional failures of this test in the history so will not mute it yet.

I wonder if the IPv4/IPv6 discrepancy is relevant here:

```
  1> [2018-11-14T16:17:30,629][INFO ][o.e.t.TransportService   ] [node_s0] profile [client]: publish_address {127.0.0.1:58509}, bound_addresses {127.0.0.1:58509}, {[::1]:58508}
...
  1> [2018-11-14T16:17:30,681][INFO ][o.e.x.s.t.f.IpFilteringIntegrationTests] connecting to localhost/127.0.0.1:58508
```

**Comment by original-brownbear** [comment]
Fix suggestion in https://github.com/elastic/elasticsearch/pull/35730
