### ISSUE TITLE
[CI] IndexLifecycleIT testExplainLifecycle failed

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#35690]
`org.elasticsearch.client.IndexLifecycleIT testExplainLifecycle` failed in 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=fedora/66/console

The error is:

```
FAILURE 0.75s | IndexLifecycleIT.testExplainLifecycle <<< FAILURES!
   > Throwable #1: org.junit.ComparisonFailure: expected:<[hot]> but was:<[new]>
   > 	at __randomizedtesting.SeedInfo.seed([2D97AA5C29728549:70BCBFDFAEA6B189]:0)
   > 	at org.elasticsearch.client.IndexLifecycleIT.testExplainLifecycle(IndexLifecycleIT.java:204)
   > 	at java.lang.Thread.run(Thread.java:748)
```

This problem did not reproduce locally for me using:

```
./gradlew :client:rest-high-level:integTestRunner \
  -Dtests.seed=2D97AA5C29728549 \
  -Dtests.class=org.elasticsearch.client.IndexLifecycleIT \
  -Dtests.method="testExplainLifecycle" \
  -Dtests.security.manager=true \
  -Dtests.locale=lt-LT \
  -Dtests.timezone=Libya \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

**Comment by talevy** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/35716
