### ISSUE TITLE
NoClassDefFoundError RestHighLevelClient

### ISSUE THREAD

**Issue by grugna** [elastic/elasticsearch#35711]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.0.0-alpha1

**Plugins installed**: []

**JVM version** (`java -version`): 10.0.1

**OS version** (`uname -a` if on a Unix-like system): 18.2.0 Darwin Kernel

**Description of the problem including expected versus actual behavior**:
I am creating a RestHighLevelClient and I get a NoClassDefFoundError

**Steps to reproduce**:
`RestHighLevelClient client = new RestHighLevelClient(RestClient.builder(new HttpHost(hostName, 9200, "http")));`

Where hostName = "localhost"

**Provide logs (if relevant)**:

`Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.client.RestHighLevelClient
	at com.lucagraglia.cluelesselasticbackend.model.elasticsearch.ElasticSearchClient.getElasticClient(ElasticSearchClient.java:33) ~[classes/:na]
	at com.lucagraglia.cluelesselasticbackend.model.elasticsearch.ElasticSearchClient.getClient(ElasticSearchClient.java:21) ~[classes/:na]
	at com.lucagraglia.cluelesselasticbackend.service.impl.ElasticSearchServiceImpl.<init>(ElasticSearchServiceImpl.java:39) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170) ~[spring-beans-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	... 32 common frames omitted`

**Comment by rjernst** [comment]
There is not enough information here to investigate. Can you please provide the entire log output? `NoClassDefFoundError` is usually the result of a static init failure earlier during startup.

**Comment by grugna** [comment]
That was the earliest part of the log, it wasn't finding RestHighLevelClient. I added

`<dependency>
        <groupId>org.elasticsearch</groupId>
        <artifactId>elasticsearch</artifactId>
        <version>7.0.0-alpha1</version>
        </dependency>`

and I got a class missing from Lucene.

Then I solved the problem going back to version 6.5.0.
