### ISSUE TITLE
[CI] org.elasticsearch.gateway.RecoveryFromGatewayIT testReuseInFileBasedPeerRecovery failed on master

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#35772]
`org.elasticsearch.gateway.RecoveryFromGatewayIT testReuseInFileBasedPeerRecovery` failed on `master` in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/262/console

```
FAILURE 14.9s J3 | RecoveryFromGatewayIT.testReuseInFileBasedPeerRecovery <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: data should have been reused
   > Expected: a value greater than <0L>
   >      but: <0L> was equal to <0L>
   > 	at __randomizedtesting.SeedInfo.seed([70E60C9DAF0AE4D7:267EE9092F52398C]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.gateway.RecoveryFromGatewayIT.testReuseInFileBasedPeerRecovery(RecoveryFromGatewayIT.java:487)
   > 	at java.lang.Thread.run(Thread.java:748)
```

Does not easily reproduce locally with (but randomly failed for me locally today):

```
> There were test failures: 308 suites, 2281 tests, 1 failure, 25 ignored (25 assumptions) [seed: 70E60C9DAF0AE4D7]

REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=70E60C9DAF0AE4D7 \
  -Dtests.class=org.elasticsearch.gateway.RecoveryFromGatewayIT \
  -Dtests.method="testReuseInFileBasedPeerRecovery" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-SY \
  -Dtests.timezone=Europe/Vaduz \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

**Comment by ywelsch** [comment]
@bleskes could you help with this?
