### ISSUE TITLE
XPackRestIT.rollup/delete_job/Test delete running job fails on 6.5

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#35779]
Failure (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.5+periodic/159):

```
08:05:49    > Throwable #1: java.lang.AssertionError: Failure at [rollup/delete_job:180]: task_failures.0.reason.reason didn't match expected value:
08:05:49    >  task_failures.0.reason.reason: expected [Could not delete job [foo] because indexer state is [STARTED].  Job must be [STOPPED] before deletion.] but was [Could not delete job [foo] because indexer state is [INDEXING].  Job must be [STOPPED] before deletion.]
08:05:49    > 	at __randomizedtesting.SeedInfo.seed([F7C34AC7EB4C1045:7F97751D45B07DBD]:0)
08:05:49    > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:382)
08:05:49    > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:359)
08:05:49    > 	at java.lang.Thread.run(Thread.java:748)
08:05:49    > Caused by: java.lang.AssertionError: task_failures.0.reason.reason didn't match expected value:
08:05:49    >  task_failures.0.reason.reason: expected [Could not delete job [foo] because indexer state is [STARTED].  Job must be [STOPPED] before deletion.] but was [Could not delete job [foo] because indexer state is [INDEXING].  Job must be [STOPPED] before deletion.]
08:05:49    > 	at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:87)
08:05:49    > 	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
08:05:49    > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:375)
08:05:49    > 	... 38 more
```

Reproduce line (it does not repro for me): 

```
./gradlew :x-pack:plugin:integTestRunner -Dtests.seed=F7C34AC7EB4C1045 -Dtests.class=org.elasticsearch.xpack.test.rest.XPackRestIT -Dtests.method="test {p0=rollup/delete_job/Test delete running job}" -Dtests.security.manager=true -Dtests.locale=sv -Dtests.timezone=Asia/Choibalsan -Dcompiler.java=11 -Druntime.java=8 -Dtests.rest.blacklist=getting_started/10_monitor_cluster_health/*
```

**Comment by javanna** [comment]
@polyfractal I wonder if this is something you are familiar with, I haven't muted the test yet as I have only seen one failure ever.

**Comment by polyfractal** [comment]
I will take a look, thanks for the ping @javanna

**Comment by polyfractal** [comment]
Right, so the test failed because it happened to query the job when it had moved into the `INDEXING` state, which is sorta like a subset of the `STARTED` state.

Ideally this would be fixed with a regex that checks `(STARTED|INDEXING)`, but there are some regex issues with yaml tests right now.  I'll open an issue about that in a few.

I think this can be fixed by just setting the job cron to run in a prior year (e.g. to never run) which will make sure we never actually move to `INDEXING` during the tests.  Will push a fix to the relevant branches in a minute
