### ISSUE TITLE
x-pack-sql-jdbc-6.5.1.jar报错Caused by: java.lang.NoClassDefFoundError: org/elasticsearch/xpack/sql/client/Version

### ISSUE THREAD

**Issue by sunyaf** [elastic/elasticsearch#35786]
Caused by: java.lang.NoClassDefFoundError: org/elasticsearch/xpack/sql/client/Version
	at org.elasticsearch.xpack.sql.jdbc.jdbcx.JdbcDataSource.<clinit>(JdbcDataSource.java:28) ~[x-pack-sql-jdbc-6.5.1.jar:6.5.1]
	at cc.youshu.eurekaclient.config.EsDruidDataSourceConfig.esDataSource(EsDruidDataSourceConfig.java:43) ~[classes/:na]

**Comment by tlrx** [comment]
Hi, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elastic forums](https://discuss.elastic.co/) instead. Thank you!

**Comment by costin** [comment]
This is an actual bug that made it into the 6.5.1 release.
There is a PR in place to fix this for 6.5.2, namely https://github.com/elastic/elasticsearch/pull/35602

Cheers
