### ISSUE TITLE
ES run in Docker, started, but with some problem

### ISSUE THREAD

**Issue by chunzhenzyd** [elastic/elasticsearch#35902]
[root@localhost ims]# docker logs --details ims_elasticsearch
 2018-11-26 09:56:35,625 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
 	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
 	at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
 	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
 	at org.apache.logging.log4j.core.jmx.Server.register(Server.java:393)
 	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:168)
 	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:141)
 	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:558)
 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:207)
 	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:220)
 	at org.apache.logging.log4j.core.config.Configurator.initialize(Configurator.java:197)
 	at org.elasticsearch.common.logging.LogConfigurator.configureStatusLogger(LogConfigurator.java:175)
 	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:143)
 	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:122)
 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:307)
 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132)
 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123)
 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70)
 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
 	at org.elasticsearch.cli.Command.main(Command.java:90)
 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)
 
 2018-11-26 09:56:35,766 main ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
 	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
 	at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
 	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
 	at org.apache.logging.log4j.core.jmx.Server.register(Server.java:393)
 	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:168)
 	at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:141)
 	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:558)
 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
 	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:166)
 	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:122)
 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:307)
 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132)
 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123)
 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70)
 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
 	at org.elasticsearch.cli.Command.main(Command.java:90)
 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)
 
 [2018-11-26T09:56:36,267][INFO ][o.e.n.Node               ] [] initializing ...
 [2018-11-26T09:56:36,501][INFO ][o.e.e.NodeEnvironment    ] [kUaTvX0] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/mapper/centos-root)]], net usable_space [39gb], net total_space [49.9gb], spins? [possibly], types [xfs]
 [2018-11-26T09:56:36,502][INFO ][o.e.e.NodeEnvironment    ] [kUaTvX0] heap size [411mb], compressed ordinary object pointers [true]
 [2018-11-26T09:56:36,504][INFO ][o.e.n.Node               ] node name [kUaTvX0] derived from node ID [kUaTvX0eRp-au13d8O69Og]; set [node.name] to override
 [2018-11-26T09:56:36,504][INFO ][o.e.n.Node               ] version[5.6.12], pid[1], build[cfe3d9f/2018-09-10T20:12:43.732Z], OS[Linux/3.10.0-862.9.1.el7.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_181/25.181-b13]
 [2018-11-26T09:56:36,504][INFO ][o.e.n.Node               ] JVM arguments [-Des.path.home=/usr/share/elasticsearch]
 [2018-11-26T09:56:38,347][INFO ][o.e.p.PluginsService     ] [kUaTvX0] loaded module [aggs-matrix-stats]
 [2018-11-26T09:56:38,348][INFO ][o.e.p.PluginsService     ] [kUaTvX0] loaded module [ingest-common]
 [2018-11-26T09:56:38,348][INFO ][o.e.p.PluginsService     ] [kUaTvX0] loaded module [lang-expression]
 [2018-11-26T09:56:38,348][INFO ][o.e.p.PluginsService     ] [kUaTvX0] loaded module [lang-groovy]
 [2018-11-26T09:56:38,348][INFO ][o.e.p.PluginsService     ] [kUaTvX0] loaded module [lang-mustache]
 [2018-11-26T09:56:38,348][INFO ][o.e.p.PluginsService     ] [kUaTvX0] loaded module [lang-painless]
 [2018-11-26T09:56:38,349][INFO ][o.e.p.PluginsService     ] [kUaTvX0] loaded module [parent-join]
 [2018-11-26T09:56:38,349][INFO ][o.e.p.PluginsService     ] [kUaTvX0] loaded module [percolator]
 [2018-11-26T09:56:38,349][INFO ][o.e.p.PluginsService     ] [kUaTvX0] loaded module [reindex]
 [2018-11-26T09:56:38,349][INFO ][o.e.p.PluginsService     ] [kUaTvX0] loaded module [transport-netty3]
 [2018-11-26T09:56:38,349][INFO ][o.e.p.PluginsService     ] [kUaTvX0] loaded module [transport-netty4]
 [2018-11-26T09:56:38,350][INFO ][o.e.p.PluginsService     ] [kUaTvX0] no plugins loaded
 [2018-11-26T09:56:40,958][INFO ][o.e.d.DiscoveryModule    ] [kUaTvX0] using discovery type [zen]
 [2018-11-26T09:56:41,571][INFO ][o.e.n.Node               ] initialized
 [2018-11-26T09:56:41,571][INFO ][o.e.n.Node               ] [kUaTvX0] starting ...
 [2018-11-26T09:56:41,635][INFO ][i.n.u.i.PlatformDependent] Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
 [2018-11-26T09:56:41,779][INFO ][o.e.t.TransportService   ] [kUaTvX0] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
 [2018-11-26T09:56:41,793][WARN ][o.e.b.BootstrapChecks    ] [kUaTvX0] initial heap size [31457280] not equal to maximum heap size [484442112]; this can cause resize pauses and prevents mlockall from locking the entire heap
 [2018-11-26T09:56:41,793][WARN ][o.e.b.BootstrapChecks    ] [kUaTvX0] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
 [2018-11-26T09:56:44,863][INFO ][o.e.c.s.ClusterService   ] [kUaTvX0] new_master {kUaTvX0}{kUaTvX0eRp-au13d8O69Og}{IXed5devSmak2S11c6eF0A}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)[, ]
 [2018-11-26T09:56:44,909][INFO ][o.e.h.n.Netty4HttpServerTransport] [kUaTvX0] publish_address {172.18.1.15:9200}, bound_addresses {0.0.0.0:9200}
 [2018-11-26T09:56:44,909][INFO ][o.e.n.Node               ] [kUaTvX0] started
 [2018-11-26T09:56:45,086][INFO ][o.e.g.GatewayService     ] [kUaTvX0] recovered [0] indices into cluster_state

**Comment by cbuescher** [comment]
Hi @chunzhenzyd ! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
