### ISSUE TITLE
[CI] HLRC failure in org.elasticsearch.client.security.GetRolesRequestTests

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#35947]
seen in: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux/84/consoleFull

Reproduces with this test seed:

```
./gradlew :client:rest-high-level:test -Dtests.seed=3A985E23287F431E -Dtests.class=org.elasticsearch.client.security.GetRolesRequestTests -Dtests.method="testEqualsHashCode" -Dtests.security.manager=true -Dtests.locale=no -Dtests.timezone=Antarctica/Palmer -Dcompiler.java=11 -Druntime.java=8
```

failure:

```
Suite: org.elasticsearch.client.security.GetRolesRequestTests
  1> [2018-11-27T09:21:06,171][INFO ][o.e.c.s.GetRolesRequestTests] [testEqualsHashCode] before test
  1> [2018-11-27T09:21:07,637][INFO ][o.e.c.s.GetRolesRequestTests] [testEqualsHashCode] after test
  2> REPRODUCE WITH: ./gradlew :client:rest-high-level:test -Dtests.seed=3A985E23287F431E -Dtests.class=org.elasticsearch.client.security.GetRolesRequestTests -Dtests.method="testEqualsHashCode" -Dtests.security.manager=true -Dtests.locale=no -Dtests.timezone=Antarctica/Palmer -Dcompiler.java=11 -Druntime.java=8
FAILURE 1.76s | GetRolesRequestTests.testEqualsHashCode <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: GetRolesRequest mutation should not be equal to original
   > Expected: not <org.elasticsearch.client.security.GetRolesRequest@1f>
   >      but: was <org.elasticsearch.client.security.GetRolesRequest@1f>
   >    at __randomizedtesting.SeedInfo.seed([3A985E23287F431E:52603A28E339CEAB]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.test.EqualsHashCodeTestUtils.checkEqualsAndHashCode(EqualsHashCodeTestUtils.java:82)
   >    at org.elasticsearch.client.security.GetRolesRequestTests.testEqualsHashCode(GetRolesRequestTests.java:44)
   >    at java.lang.Thread.run(Thread.java:748)
 ...
  2> NOTE: All tests run in this JVM: [GetRolesRequestTests]
Completed [1/1] in 9.46s, 1 test, 1 failure <<< FAILURES!
```
Assuming security is responsible for there HLRC, if not, please re-label.

@tvernum maybe this is fixed with https://github.com/elastic/elasticsearch/pull/35932 ??

**Comment by jkakavas** [comment]
@hendrikmuhs thanks, yes, this is fixed by #35932 , I will merge that now that CI is green to spare us from additional failures
