### ISSUE TITLE
Log4J Core is still leaking into the High Level REST Client

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#35953]
@kosa1234 has [reported](https://github.com/elastic/elasticsearch/issues/32151#issuecomment-440677221) another place where we leak the log4j-core dependency into the high level rest client. This comes about because we use the server's request objects in the high level rest client. We've actually started the process of removing these, but they are still around. So I'm not sure that we should work super hard to build something automatic to prevent these. On the other hand, they are super nasty when they happen.

[These](https://github.com/elastic/elasticsearch/blob/6.4/server/src/main/java/org/elasticsearch/action/update/UpdateRequest.java#L869-L873) lines are the problem.

**Comment by tiitginter** [comment]
Why still not fixed?

**Comment by hub-cap** [comment]
Hi we have to work on a more holistic fix for splitting the client from server code. It is something on the roadmap, but we cannot comment on when it may be done / ready. There are some prerequisites that need to happen, and those are in flight now. Im sorry that it has not been fixed fully yet, but rest assured that it will be fixed and we are discussing ways to fix this. If you have a specific call that you are using that can be fixed, we welcome contributions to help fix those.

**Comment by pan3793** [comment]
If it's really hard to spilt server dependency, consider use shadow and relocate as a short term solution? Just like Hadoop client solution https://issues.apache.org/jira/browse/HADOOP-11656

**Comment by hashhar** [comment]
Is there any progress on this?

After excluding `commons-logging` (due to some classpath issues) I see failures like:

```
java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.common.logging.DeprecationLogger
	at org.elasticsearch.index.query.AbstractQueryBuilder.<clinit>(AbstractQueryBuilder.java:58)
	at io.trino.plugin.elasticsearch.ElasticsearchQueryBuilder.buildSearchQuery(ElasticsearchQueryBuilder.java:60)
	at io.trino.plugin.elasticsearch.ScanQueryPageSource.<init>(ScanQueryPageSource.java:114)
	at io.trino.plugin.elasticsearch.ElasticsearchPageSourceProvider.createPageSource(ElasticsearchPageSourceProvider.java:78)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:68)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:308)
	at io.trino.operator.Driver.processInternal(Driver.java:388)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:693)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1092)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:488)
	at io.trino.$gen.Trino_testversion____20220313_171245_9.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Is there some workaround for the time being at-least?

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
