### ISSUE TITLE
[CI] org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT failures /_rollup/job/_all

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#35979]
A number of MixedClusterClientYamlTestSuiteIT tests fail in master : 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+default-distro-bwc-tests/128/console

All fail with a`404` for `/_rollup/job/_all`
```
Caused by: org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:41221], URI [/_rollup/job/_all], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"_rollup","index_uuid":"_na_","index":"_rollup"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"_rollup","index_uuid":"_na_","index":"_rollup"},"status":404}
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:307)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:292)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	... 1 more
```

**Comment by polyfractal** [comment]
Seems to be related to https://github.com/elastic/elasticsearch/pull/35962, where it's using the new endpoint on old nodes.  Will get a fix up in a minute.
