### ISSUE TITLE
[CI] CombinedDeletionPolicyTests#testAcquireIndexCommit fails

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#35994]
This failed on 6.x in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/340/console with 
```
java.lang.AssertionError: 
Expected: <-30L>
     but: was <-1L>
	at __randomizedtesting.SeedInfo.seed([DC25BCF3CE87AAF8:47F4C9DA66EB95FC]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.index.engine.CombinedDeletionPolicyTests.testAcquireIndexCommit(CombinedDeletionPolicyTests.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

It reproduces locally also with that seed.

```
./gradlew :server:test \
  -Dtests.seed=DC25BCF3CE87AAF8 \
  -Dtests.class=org.elasticsearch.index.engine.CombinedDeletionPolicyTests \
  -Dtests.method="testAcquireIndexCommit" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-PR \
  -Dtests.timezone=Europe/Isle_of_Man \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

**Comment by dnhatn** [comment]
This is a test bug - fixed in https://github.com/elastic/elasticsearch/commit/cef30247c092d8bbc14d416f707a69102c4f85f3.

**Comment by droberts195** [comment]
The same test failed again today in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/599/console with a different seed:

```
./gradlew :server:unitTest \
  -Dtests.seed=9E3BD526DA4990E7 \
  -Dtests.class=org.elasticsearch.index.engine.CombinedDeletionPolicyTests \
  -Dtests.method="testAcquireIndexCommit" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-OM \
  -Dtests.timezone=Pacific/Bougainville \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

The error is this:

```
FAILURE 1.02s | CombinedDeletionPolicyTests.testAcquireIndexCommit <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <0L>
   >      but: was <-1L>
   >    at __randomizedtesting.SeedInfo.seed([9E3BD526DA4990E7:5EAA00F7225AFE3]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.index.engine.CombinedDeletionPolicyTests.testAcquireIndexCommit(CombinedDeletionPolicyTests.java:131)
   >    at java.lang.Thread.run(Thread.java:745)
```

With seed `9E3BD526DA4990E7` it reproduces locally 100% of the time with the same error on my CentOS 7 machine.

If I change the seed it doesn't reproduce, so it's seed specific.

@dnhatn if you think this is completely different to the original problem of this issue then I'm happy to transfer it to a different issue - just let me know if you'd prefer this.
