### ISSUE TITLE
Unable to parse response from ClearScrollRequest

### ISSUE THREAD

**Issue by Jens-vd** [elastic/elasticsearch#36011]
**Elasticsearch version** (`bin/elasticsearch --version`): 2.4.4

**High Level Rest Client version**: 6.4.3

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_171

**OS version** (`uname -a` if on a Unix-like system): 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

A `java.io.IOException` is thrown when sending a Clear Scroll Request to Elastic Search. Response code 200 seems to indicate the operation was successful, but its response could not be parsed by the High Level Rest Client.
Expected behaviour is that no exception is thrown.

**Steps to reproduce**:

With version 6.4.3 of the High Level Rest Client, the following code produces the exception:

```
private final RestHighLevelClient client;

private void clearScrollIfFinished(SearchResponse searchResponse) {
        if (searchResponse.getHits().getHits().length == 0) {
            ClearScrollRequest clearScrollRequest = new ClearScrollRequest();
            clearScrollRequest.addScrollId(searchResponse.getScrollId());

            try {
                LOGGER.debug("Clearing scroll with scrollId={}", searchResponse.getScrollId());
                client.clearScroll(clearScrollRequest, RequestOptions.DEFAULT);
            } catch (IOException e) {
                LOGGER.warn("Clear Scroll Request could not be processed", e);
            }
        }
    }
```

**Provide logs (if relevant)**:

```
DEBUG com.company.service.ElasticSearchClient - Clearing scroll with scrollId=cXVlcnlUaGVuRmV0Y2g7NzsyMTUyNzM6NGtncXlCQldTY3VYdzRTZXRXcnpXZzsyMTUyNzQ6NGtncXlCQldTY3VYdzRTZXRXcnpXZzsyMTUyNzU6NGtncXlCQldTY3VYdzRTZXRXcnpXZzsyMTUyNzc6NGtncXlCQldTY3VYdzRTZXRXcnpXZzsyMTUyNzY6NGtncXlCQldTY3VYdzRTZXRXcnpXZzsyMTUyNzk6NGtncXlCQldTY3VYdzRTZXRXcnpXZzsyMTUyNzg6NGtncXlCQldTY3VYdzRTZXRXcnpXZzswOw==
WARN  com.company.service.ElasticSearchClient - Clear Scroll Request could not be processed
java.io.IOException: Unable to parse response body for Response{requestLine=DELETE /_search/scroll HTTP/1.1, host=https://logging-es:9200, response=HTTP/1.1 200 OK}
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1275) ~[elasticsearch-rest-high-level-client-6.4.3.jar:6.4.3]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1231) ~[elasticsearch-rest-high-level-client-6.4.3.jar:6.4.3]
	at org.elasticsearch.client.RestHighLevelClient.clearScroll(RestHighLevelClient.java:947) ~[elasticsearch-rest-high-level-client-6.4.3.jar:6.4.3]
```

```
Caused by: java.lang.IllegalArgumentException: Required [succeeded, num_freed]
	at org.elasticsearch.common.xcontent.ConstructingObjectParser$Target.finish(ConstructingObjectParser.java:449) ~[elasticsearch-x-content-6.5.0.jar:6.5.0]
	at org.elasticsearch.common.xcontent.ConstructingObjectParser$Target.access$000(ConstructingObjectParser.java:350) ~[elasticsearch-x-content-6.5.0.jar:6.5.0]
	at org.elasticsearch.common.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:169) ~[elasticsearch-x-content-6.5.0.jar:6.5.0]
	at org.elasticsearch.common.xcontent.ConstructingObjectParser.apply(ConstructingObjectParser.java:161) ~[elasticsearch-x-content-6.5.0.jar:6.5.0]
	at org.elasticsearch.action.search.ClearScrollResponse.fromXContent(ClearScrollResponse.java:95) ~[elasticsearch-6.4.3.jar:6.4.3]
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1406) ~[elasticsearch-rest-high-level-client-6.4.3.jar:6.4.3]
	at org.elasticsearch.client.RestHighLevelClient.lambda$performRequestAndParseEntity$9(RestHighLevelClient.java:1232) ~[elasticsearch-rest-high-level-client-6.4.3.jar:6.4.3]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1273) ~[elasticsearch-rest-high-level-client-6.4.3.jar:6.4.3]
	... 116 more
```

**Comment by nik9000** [comment]
Oooooh!


> Elasticsearch version (bin/elasticsearch --version): 2.4.4
> High Level Rest Client version: 6.4.3

This isn't going to work. We work to make the client forwards compatible with newer versions of Elasticsearch but it isn't compatible with older versions of Elasticsearch. It might work, but I'm not surprised it doesn't in this case.
