### ISSUE TITLE
SQL: Exception thrown for query with constant filtering

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#36055]
```
SELECT SUM({fn CONVERT(1, SQL_BIGINT)}) AS "sum_Number of Records_ok"
FROM test_emp
WHERE ('All' = 'All')
HAVING (COUNT(1) > 0);
```
throws:
```
java.sql.SQLException: Server encountered an error [Schema [sum_Number of Records_ok:long] and values [0.0, 100] are out of sync]. [SqlIllegalArgumentException[Schema [sum_Number of Records_ok:long] and values [0.0, 100] are out of sync]
	at org.elasticsearch.xpack.sql.util.Check.isTrue(Check.java:18)
	at org.elasticsearch.xpack.sql.session.Rows.singleton(Rows.java:47)
	at org.elasticsearch.xpack.sql.execution.search.Querier$ImplicitGroupActionListener.handleBuckets(Querier.java:182)
	at org.elasticsearch.xpack.sql.execution.search.Querier$ImplicitGroupActionListener.handleResponse(Querier.java:163)
	at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.onResponse(Querier.java:408)
	at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.onResponse(Querier.java:384)
	at org.elasticsearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:97)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by matriv** [comment]
@elastic/es-ql

**Comment by matriv** [comment]
Not valid anymore, the behavior has been fixed.
