### ISSUE TITLE
Scripting: Execute Painless API fails when communicating across nodes

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#36050]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.1

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Start two elasticsearch, one named `first`, one named `second`. The `first` one should be the where you connect kibana to, to make sure this works (just start it as the first one, so it will bind to port 9200)

```
 ./elasticsearch-6.5.1/bin/elasticsearch -Enode.name=first
 ./elasticsearch-6.5.1/bin/elasticsearch -Enode.name=second
```

Open Kibana, run this in console

```
DELETE my-index

PUT /my-index
{
  "settings": {
    "index.routing.allocation.include._name": "first",
    "index.number_of_shards": 1,
    "index.number_of_replicas": 0
  },
  "mappings": {
    "_doc": {
      "properties": {
        "field": {
          "type": "keyword"
        }
      }
    }
  }
}

# all shards assigned on first node
GET _cat/shards/my-index

# this works
POST /_scripts/painless/_execute
{
  "script": {
    "source": "doc['field'].value.length() <= params.max_length",
    "params": {
      "max_length": 4
    }
  },
  "context": "filter",
  "context_setup": {
    "index": "my-index",
    "document": {
      "field": "four"
    }
  }
}

# move index to second node
PUT /my-index/_settings
{
  "settings": {
    "index.routing.allocation.include._name": "second"
  }
}

# all shards assigned on second node
GET _cat/shards/my-index

# NPE baby!
POST /_scripts/painless/_execute
{
  "script": {
    "source": "doc['field'].value.length() <= params.max_length",
    "params": {
      "max_length": 4
    }
  },
  "context": "filter",
  "context_setup": {
    "index": "my-index",
    "document": {
      "field": "four"
    }
  }
}
```

The NPE is the following

```
[2018-11-29T14:00:49,023][WARN ][r.suppressed             ] [first] path: /_scripts/painless/_execute, params: {pretty=}
org.elasticsearch.transport.RemoteTransportException: [second][127.0.0.1:9301][cluster:admin/scripts/painless/execute[s]]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
	at org.elasticsearch.index.mapper.SourceToParse.<init>(SourceToParse.java:56) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.index.mapper.SourceToParse.source(SourceToParse.java:32) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.painless.PainlessExecuteAction$TransportAction.prepareRamIndex(PainlessExecuteAction.java:597) ~[?:?]
	at org.elasticsearch.painless.PainlessExecuteAction$TransportAction.innerShardOperation(PainlessExecuteAction.java:547) ~[?:?]
	at org.elasticsearch.painless.PainlessExecuteAction$TransportAction.shardOperation(PainlessExecuteAction.java:536) ~[?:?]
	at org.elasticsearch.painless.PainlessExecuteAction$TransportAction.shardOperation(PainlessExecuteAction.java:475) ~[?:?]
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.doRun(TransportSingleShardAction.java:112) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) ~[elasticsearch-6.5.1.jar:6.5.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.5.1.jar:6.5.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by martijnvg** [comment]
Whoops. That should be fixed.
