### ISSUE TITLE
SQL: Error in painless script generation for complex string functions

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#36061]
```
SELECT {fn CONVERT({fn CONCAT({fn LTRIM({fn CONVERT(emp_no, SQL_VARCHAR)})}, {fn LTRIM({fn CONVERT(languages, SQL_VARCHAR)})})}, SQL_BIGINT)} AS "TEMP"
FROM test_emp
GROUP BY 1;
```
throws:
```
Caused by: ScriptException[runtime error]; nested: NotSerializableExceptionWrapper[class_cast_exception: class java.lang.Long cannot be cast to class java.lang.String (java.lang.Long and java.lang.String are in module java.base of loader 'bootstrap')];
	at org.elasticsearch.painless.PainlessScript.convertToScriptException(PainlessScript.java:94)
	at org.elasticsearch.painless.PainlessScript$Script.execute(InternalSqlScriptUtils.concat(InternalSqlScriptUtils.ltrim(InternalSqlScriptUtils.docValue(doc,params.v0)),InternalSqlScriptUtils.ltrim(InternalSqlScriptUtils.docValue(doc,params.v1))):23)
	at org.elasticsearch.search.aggregations.support.values.ScriptLongValues.advanceExact(ScriptLongValues.java:51)
	at org.elasticsearch.search.aggregations.bucket.composite.LongValuesSource$1.collect(LongValuesSource.java:156)
	at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:82)
	at org.elasticsearch.search.aggregations.bucket.composite.CompositeAggregator$1.collect(CompositeAggregator.java:177)
	at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:82)
	at org.apache.lucene.search.MatchAllDocsQuery$1$1.score(MatchAllDocsQuery.java:62)
	at org.elasticsearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:56)
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:652)
	at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:177)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:443)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:277)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:115)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:334)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:381)
	at org.elasticsearch.search.SearchService.access$100(SearchService.java:123)
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:343)
```

**Comment by astefan** [comment]
This is not about string functions, but more about casting inside scripts.

**Comment by astefan** [comment]
master (7.0.0): https://github.com/elastic/elasticsearch/commit/b15f27f6a6bed3c349169a7c928e6c5460548bdb
6.x (6.6.0): https://github.com/elastic/elasticsearch/commit/c84222723e2839af43106c26bbc19a96511a88c9
