### ISSUE TITLE
SQL: GroupBy with ordinal and HAVING with constants throws error

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#36060]
```
SELECT gender as g,
  SUM({fn CONVERT(1, SQL_BIGINT)}) AS cnt
FROM test_emp
GROUP BY 1
HAVING ((SUM({fn CONVERT(1, SQL_BIGINT)}) >= 0) AND (SUM({fn CONVERT(1, SQL_BIGINT)}) <= 577));
```
throws:
```
Caused by: java.lang.IllegalArgumentException: No aggregation found for path [36]
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.resolvePipelineAggregatorOrder(AggregatorFactories.java:418)
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.resolvePipelineAggregatorOrder(AggregatorFactories.java:356)
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:326)
	at org.elasticsearch.search.aggregations.AggregatorFactory.<init>(AggregatorFactory.java:188)
	at org.elasticsearch.search.aggregations.bucket.composite.CompositeAggregationFactory.<init>(CompositeAggregationFactory.java:40)
	at org.elasticsearch.search.aggregations.bucket.composite.CompositeAggregationBuilder.doBuild(CompositeAggregationBuilder.java:193)
	at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:139)
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:333)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:808)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:619)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:595)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:371)
	at org.elasticsearch.search.SearchService.access$100(SearchService.java:123)
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:343)
```

**Comment by matriv** [comment]
@elastic/es-ql

**Comment by matriv** [comment]
This issue has been fixed.
