### ISSUE TITLE
[CI] Release tests failures in RollupDocumentationIT#testStartRollupJob and IndicesClientDocumentationIT

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#36072]
@polyfractal possible also related to https://github.com/elastic/elasticsearch/issues/36044, but I'm filing an issue just because its in the client documentation tests. Please close if the cause looks the same to you.

Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/155/console

Errors look like this.
```
org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:36868], URI [/_rollup/job/job_1/_stop?wait_for_completion=true&timeout=10s], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"timeout_exception","reason":"Timed out after [10s] while waiting for rollup job [job_1] to stop"}],"type":"timeout_exception","reason":"Timed out after [10s] while waiting for rollup job [job_1] to stop"},"status":500}
	at __randomizedtesting.SeedInfo.seed([C5062A02705C78A2:9328F53D498CBBE1]:0)
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:687)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:218)
	at org.elasticsearch.test.rest.ESRestTestCase.wipeRollupJobs(ESRestTestCase.java:495)
	at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:407)
	at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:193)
```

I tried reproducing locally using this, but changed `-Dbuild.snapshot=false` to `-Dbuild.snapshot=true` because otherwise I was getting "Property license.key must be set for release build" errors. I couldn't reproduce this this small change so far:
```
REPRODUCE WITH: ./gradlew :client:rest-high-level:integTestRunner \
  -Dtests.seed=C5062A02705C78A2 \
  -Dtests.class=org.elasticsearch.client.documentation.RollupDocumentationIT \
  -Dtests.method="testStartRollupJob" \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=ar-SY \
  -Dtests.timezone=America/Santarem \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :client:rest-high-level:integTestRunner \
  -Dtests.seed=C5062A02705C78A2 \
  -Dtests.class=org.elasticsearch.client.documentation.IndicesClientDocumentationIT \
  -Dtests.method="testGetMapping" \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=ar-MA \
  -Dtests.timezone=Pacific/Niue \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :client:rest-high-level:integTestRunner \
  -Dtests.seed=C5062A02705C78A2 \
  -Dtests.class=org.elasticsearch.client.documentation.IndicesClientDocumentationIT \
  -Dtests.method="testClearCache" \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=ar-MA \
  -Dtests.timezone=Pacific/Niue \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :client:rest-high-level:integTestRunner \
  -Dtests.seed=C5062A02705C78A2 \
  -Dtests.class=org.elasticsearch.client.documentation.IndicesClientDocumentationIT \
  -Dtests.method="testRolloverIndex" \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=ar-MA \
  -Dtests.timezone=Pacific/Niue \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :client:rest-high-level:integTestRunner \
  -Dtests.seed=C5062A02705C78A2 \
  -Dtests.class=org.elasticsearch.client.documentation.IndicesClientDocumentationIT \
  -Dtests.method="testSplitIndex" \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=ar-MA \
  -Dtests.timezone=Pacific/Niue \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

**Comment by polyfractal** [comment]
:tada:  when it rains it pours :)

I suspect it's related, but not positive.  Will dig a bit.

**Comment by polyfractal** [comment]
I believe this is the same as https://github.com/elastic/elasticsearch/issues/35295, e.g. timeouts in `RollupDocumentationIT#testStartRollupJob()`.  Going to close this one in favor of #35295
