### ISSUE TITLE
NodeNotConnectedException gets logged when calling cluster APIs from a client node

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#3617]
If we have a cluster with two or more client nodes, and we call the nodes stats (or nodes info) api connecting to one of the client nodes, we don't get back the information about the other client nodes in the cluster, and the following exception gets logged, which is rather annoying especially when calling those apis every n seconds for monitoring purposes. 

```
[2013-09-04 14:41:19,983][DEBUG][action.admin.cluster.node.info] [Vakume] failed to execute on node [D4d2wy10Qr-HKgWcSRVoUQ]
org.elasticsearch.transport.SendRequestTransportException: [Gremlin][inet[/10.20.100.106:9301]][cluster/nodes/info/n]
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:203)
	at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction.start(TransportNodesOperationAction.java:172)
	at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction.access$300(TransportNodesOperationAction.java:102)
	at org.elasticsearch.action.support.nodes.TransportNodesOperationAction.doExecute(TransportNodesOperationAction.java:73)
	at org.elasticsearch.action.support.nodes.TransportNodesOperationAction.doExecute(TransportNodesOperationAction.java:43)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:61) 

................................

Caused by: org.elasticsearch.transport.NodeNotConnectedException: [Gremlin][inet[/10.20.100.106:9301]] Node not connected
	at org.elasticsearch.transport.netty.NettyTransport.nodeChannel(NettyTransport.java:806)
	at org.elasticsearch.transport.netty.NettyTransport.sendRequest(NettyTransport.java:520)
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:188)
```

The reason for this is that we prevent client-to-client node communication. A workaround would be to filter out the client nodes (but the local one) like this:

`curl -XGET 'http://localhost:9202/_nodes/master:true,data:true,_local`

This could be fixed, as mentioned in #3542, by redirecting the request (`TransportNodesOperationAction`) to either a data or master node, in case the node it's sending the request from is a client node, so that we make sure that we can gather information about all the nodes in the cluster (including client ones).

**Comment by clintongormley** [comment]
As of 2.0, this no longer logs a NodeNotConnectedException, but it still doesn't return information about other client nodes.

**Comment by javanna** [comment]
I just tested this again, and I confirm that no exception is logged anymore since 2.0 but client nodes are missing if you originally hit one of the clients nodes. Closing in favour of #16815 which is exactly the same.
