### ISSUE TITLE
RollingUpgrade test fails due to missing request id

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#36199]
Branch: 6.x
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+bwc-tests/111/consoleFull

Failed task:

```
:x-pack:qa:rolling-upgrade:with-system-key:v5.6.0#oneThirdUpgradedTestCluster#wait
```

There is no reproduction line as an assertion has tripped.  The relevant failure trace is:

```
02:44:04 |    [2018-12-04T01:42:10,755][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [upgraded-node-0] fatal error in thread [elasticsearch[upgraded-node-0][refresh][T#1]], exiting
02:44:04 |    java.lang.AssertionError: Attempt to authorize action [indices:admin/refresh[s][r]] for [_xpack] without an existing request-id
02:44:04 |    	at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:148) ~[?:?]
02:44:04 |    	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$executeAsUser$4(ServerTransportFilter.java:184) ~[?:?]
02:44:04 |    	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.maybeRun(AuthorizationUtils.java:177) ~[?:?]
02:44:04 |    	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.setRunAsRoles(AuthorizationUtils.java:171) ~[?:?]
02:44:04 |    	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.authorize(AuthorizationUtils.java:159) ~[?:?]
02:44:04 |    	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$executeAsUser$5(ServerTransportFilter.java:187) ~[?:?]
02:44:04 |    	at org.elasticsearch.xpack.core.security.SecurityContext.executeAsUser(SecurityContext.java:94) ~[?:?]
02:44:04 |    	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.executeAsUser(ServerTransportFilter.java:180) ~[?:?]
02:44:04 |    	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.executeAsOldVersionXPackUser(ServerTransportFilter.java:175) ~[?:?]
02:44:04 |    	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$inbound$3(ServerTransportFilter.java:149) ~[?:?]
02:44:04 |    	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60) ~[elasticsearch-6.6.0-SNAPSHOT.jar:6.6.0-SNAPSHOT]
02:44:04 |    	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$2(AuthenticationService.java:177) ~[?:?]
02:44:04 |    	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$4(AuthenticationService.java:210) ~[?:?]
02:44:04 |    	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:221) ~[?:?]
02:44:04 |    	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:175) ~[?:?]
02:44:04 |    	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:134) ~[?:?]
02:44:04 |    	at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:104) ~[?:?]
02:44:04 |    	at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.inbound(ServerTransportFilter.java:130) ~[?:?]
02:44:04 |    	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:306) ~[?:?]
02:44:04 |    	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.6.0-SNAPSHOT.jar:6.6.0-SNAPSHOT]
02:44:04 |    	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1346) ~[elasticsearch-6.6.0-SNAPSHOT.jar:6.6.0-SNAPSHOT]
02:44:04 |    	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759) ~[elasticsearch-6.6.0-SNAPSHOT.jar:6.6.0-SNAPSHOT]
02:44:04 |    	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.6.0-SNAPSHOT.jar:6.6.0-SNAPSHOT]
02:44:04 |    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
02:44:04 |    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
02:44:04 |    	at java.lang.Thread.run(Thread.java:834) [?:?]
```

I've also attached:

* [full build log](https://github.com/elastic/elasticsearch/files/2642898/full-build.log.zip)
* [cluster logs](https://github.com/elastic/elasticsearch/files/2642899/cluster-logs.zip) from the failing test

It seems this assertion has been added very recently so I wonder whether there are some missing edge cases? @tvernum can you please have a look at this one?

**Comment by danielmitterdorfer** [comment]
A very similar failure has occured in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+bwc-tests/112/console:

```
09:46:15 [2018-12-04T08:46:12,152][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [upgraded-node-0] fatal error in thread [elasticsearch[upgraded-node-0][management][T#1]], exiting
09:46:15 java.lang.AssertionError: Attempt to authorize action [indices:monitor/stats[n]] for [_xpack] without an existing request-id
09:46:15 	at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:148) ~[?:?]
```

**Comment by tvernum** [comment]
As best I can tell, we have a situation where there is a `User` with a principal of `_xpack` which is logically the `XPackUser` but is not actually `XPackUser.INSTANCE`.

That's not supposed to happen - `InternalUserSerializationHelper` should deserialize it to that instance. I could work around it in that `assert` (and I may need to) but this points to something more significant, so I'm going to spend some time working out what's going on there.

**Comment by martijnvg** [comment]
Another instance of this failure happened on 6.x branch: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+bwc-tests/136/console

```
[2018-12-10T23:42:03,450][INFO ][o.e.x.w.WatcherService   ] [upgraded-node-0] paused watch execution, reason [pausing watcher, cluster contains old nodes not supportin
g distributed watch execution], cancelled [0] queued tasks
[2018-12-10T23:42:03,507][INFO ][o.e.x.w.WatcherService   ] [upgraded-node-0] paused watch execution, reason [pausing watcher, cluster contains old nodes not supportin
g distributed watch execution], cancelled [0] queued tasks
[2018-12-10T23:42:03,532][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [upgraded-node-0] fatal error in thread [elasticsearch[upgraded-node-0][refresh][T#1]], e
xiting
java.lang.AssertionError: Attempt to authorize action [indices:admin/refresh[s][r]] for [_xpack] without an existing request-id
        at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:148) ~[?:?]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$executeAsUser$4(ServerTransportFilter.java:184) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.maybeRun(AuthorizationUtils.java:177) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.setRunAsRoles(AuthorizationUtils.java:171) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.authorize(AuthorizationUtils.java:159) ~[?:?]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$executeAsUser$5(ServerTransportFilter.java:187) ~[?:?]
        at org.elasticsearch.xpack.core.security.SecurityContext.executeAsUser(SecurityContext.java:94) ~[?:?]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.executeAsUser(ServerTransportFilter.java:180) ~[?:?]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.executeAsOldVersionXPackUser(ServerTransportFilter.java:175) ~[?:?]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$inbound$3(ServerTransportFilter.java:149) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60) ~[elasticsearch-6.6.0-SNAPSHOT.jar:6.6.0-SNAPSHOT]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$2(AuthenticationService.java:177) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$4(AuthenticationService.java:210) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:221) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:175) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:134) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:104) ~[?:?]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.inbound(ServerTransportFilter.java:130) ~[?:?]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:306) ~[?:?]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.6.0-SNAPSHOT.jar:6.6.0-SNAPSHOT]
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1346) ~[elasticsearch-6.6.0-SNAPSHOT.jar:6.6.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759) ~[elasticsearch-6.6.0-SNAPSHOT.jar:6.6.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.6.0-SNAPSHOT.jar:6.6.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by martijnvg** [comment]
Another instance of this test failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+bwc-tests/137/console

```
[2018-12-11T11:15:30,375][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [upgraded-node-0] fatal error in thread [elasticsearch[upgraded-node-0][management][T#1]], exiting
java.lang.AssertionError: Attempt to authorize action [indices:monitor/stats[n]] for [_xpack] without an existing request-id
        at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:148) ~[?:?]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$executeAsUser$4(ServerTransportFilter.java:184) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.maybeRun(AuthorizationUtils.java:177) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.setRunAsRoles(AuthorizationUtils.java:171) ~[?:?]
        at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.authorize(AuthorizationUtils.java:159) ~[?:?]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$executeAsUser$5(ServerTransportFilter.java:187) ~[?:?]
        at org.elasticsearch.xpack.core.security.SecurityContext.executeAsUser(SecurityContext.java:94) ~[?:?]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.executeAsUser(ServerTransportFilter.java:180) ~[?:?]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.executeAsOldVersionXPackUser(ServerTransportFilter.java:175) ~[?:?]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.lambda$inbound$3(ServerTransportFilter.java:149) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60) ~[elasticsearch-6.6.0-SNAPSHOT.jar:6.6.0-SNAPSHOT]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$2(AuthenticationService.java:177) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$4(AuthenticationService.java:210) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:221) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:175) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:134) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:104) ~[?:?]
        at org.elasticsearch.xpack.security.transport.ServerTransportFilter$NodeProfile.inbound(ServerTransportFilter.java:130) ~[?:?]
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:306) ~[?:?]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.6.0-SNAPSHOT.jar:6.6.0-SNAPSHOT]
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1346) ~[elasticsearch-6.6.0-SNAPSHOT.jar:6.6.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759) ~[elasticsearch-6.6.0-SNAPSHOT.jar:6.6.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.6.0-SNAPSHOT.jar:6.6.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by jaymode** [comment]
I think we are losing the requestId when we switch users and rewrite authentication in `executeAsOldVersionXPackUser`

**Comment by tvernum** [comment]
We might well be, but we should not be requiring a request-id for internal users (such as `_xpack`), so this assert shouldn't be tripped.

**Comment by astefan** [comment]
And another one, similar but on a different action: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+bwc-tests/141/console

```
09:03:03  |    [2018-12-12T07:01:09,210][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [upgraded-node-0] fatal error in thread [elasticsearch[upgraded-node-0][management][T#1]], exiting
09:03:03  |    java.lang.AssertionError: Attempt to authorize action [cluster:monitor/xpack/ml/job/stats/get[n]] for [_xpack] without an existing request-id
09:03:03  |    	at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:148) ~[?:?]
```

**Comment by jaymode** [comment]
https://github.com/elastic/elasticsearch/commit/677baf841e58bdd115274470384f5f07c1375268 should fix this
