### ISSUE TITLE
Test Failure: NetworkDisruptionIT fails 

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#36205]
As part of  #36107 tests that did not run before from `tests/framework` are enabled uncovering these failures.

Reproduce with (note that changes from #36107 and un-muting are required to reproduce):
```
./gradlew :test:framework:integTest -Dtests.seed=B9241F7F0412788F
```
Fails with (specific to this seed):
```
FAILURE 1.44s J0 | NetworkDisruptionIT.testNetworkPartitionRemovalRestoresConnections <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: max must be >= min: 1, 0
   >    at __randomizedtesting.SeedInfo.seed([B9241F7F0412788F:78B82F532E5AB157]:0)
   >    at com.carrotsearch.randomizedtesting.generators.RandomNumbers.randomIntBetween(RandomNumbers.java:16)
   >    at org.elasticsearch.test.ESTestCase.randomIntBetween(ESTestCase.java:539)
   >    at org.elasticsearch.test.disruption.NetworkDisruptionIT.testNetworkPartitionRemovalRestoresConnections(NetworkDisruptionIT.java:64)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   >    at java.base/java.lang.Thread.run(Thread.java:834)
IGNOR/A 0.00s J0 | NetworkDisruptionIT.testNetworkPartitionWithNodeShutdown
```

And:
```
  2> REPRODUCE WITH: ./gradlew :test:framework:integTest -Dtests.seed=41410B614A82118A -Dtests.class=org.elasticsearch.test.disruption.NetworkDisruptionIT -Dtests.method="testNetworkPartitionWithNodeShutdown" -Dtests.security.manager=true -Dtests.locale=no -Dtests.timezone=Europe/Vaduz -Dcompiler.java=11 -Druntime.java=11
ERROR   35.5s J0 | NetworkDisruptionIT.testNetworkPartitionWithNodeShutdown <<< FAILURES!
   > Throwable #1: ElasticsearchException[failed to update minimum master node to [1] (current masters [2])]; nested: MasterNotDiscoveredException[FailedToCommitClusterStateException[timed out while waiting for enough masters to ack sent cluster state. [1] left]]; nested: FailedToCommitClusterStateException[timed out while waiting for enough masters to ack sent cluster state. [1] left];
   >    at __randomizedtesting.SeedInfo.seed([41410B614A82118A:1DCCF52EC8AF773]:0)
   >    at org.elasticsearch.test.InternalTestCluster.updateMinMasterNodes(InternalTestCluster.java:1926)
   >    at org.elasticsearch.test.InternalTestCluster.stopNodesAndClients(InternalTestCluster.java:1606)
   >    at org.elasticsearch.test.InternalTestCluster.stopNodesAndClient(InternalTestCluster.java:1599)
   >    at org.elasticsearch.test.InternalTestCluster.stopRandomNode(InternalTestCluster.java:1508)
   >    at org.elasticsearch.test.disruption.NetworkDisruptionIT.testNetworkPartitionWithNodeShutdown(NetworkDisruptionIT.java:50)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   >    at java.base/java.lang.Thread.run(Thread.java:834)
   > Caused by: MasterNotDiscoveredException[FailedToCommitClusterStateException[timed out while waiting for enough masters to ack sent cluster state. [1] left]]; nested: FailedToCommitClusterStateException[timed out while waiting for enough masters to ack sent cluster state. [1] left];
   >    at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:259)
   >    at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:322)
   >    at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:146)
   >    at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:117)
   >    at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.retry(TransportMasterNodeAction.java:243)
   >    at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.access$400(TransportMasterNodeAction.java:141)
   >    at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.onFailure(TransportMasterNodeAction.java:199)
   >    at org.elasticsearch.cluster.AckedClusterStateUpdateTask.onFailure(AckedClusterStateUpdateTask.java:79)
   >    at org.elasticsearch.action.admin.cluster.settings.TransportClusterUpdateSettingsAction$1.onFailure(TransportClusterUpdateSettingsAction.java:176)
   >    at org.elasticsearch.cluster.service.MasterService$SafeClusterStateTaskListener.onFailure(MasterService.java:457)
   >    at org.elasticsearch.cluster.service.MasterService$TaskOutputs.lambda$publishingFailed$0(MasterService.java:361)
   >    at java.util.ArrayList.forEach(ArrayList.java:1540)
   >    at org.elasticsearch.cluster.service.MasterService$TaskOutputs.publishingFailed(MasterService.java:361)
   >    at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:235)
   >    at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:137)
   >    at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
   >    at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
   >    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660)
   >    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
   >    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
   >    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
   >    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   >    at java.lang.Thread.run(Thread.java:834)
   > Caused by: FailedToCommitClusterStateException[timed out while waiting for enough masters to ack sent cluster state. [1] left]
   >    at org.elasticsearch.discovery.zen.PublishClusterStateAction$SendingController.waitForCommit(PublishClusterStateAction.java:541)
   >    at org.elasticsearch.discovery.zen.PublishClusterStateAction.innerPublish(PublishClusterStateAction.java:199)
   >    at org.elasticsearch.discovery.zen.PublishClusterStateAction.publish(PublishClusterStateAction.java:162)
   >    at org.elasticsearch.discovery.zen.ZenDiscovery.publish(ZenDiscovery.java:340)
   >    at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:230)
   >    ... 9 more
```

**Comment by jaymode** [comment]
@andrershov it looks you did some work here. Should we consider this addressed since your PR has been merged?

**Comment by original-brownbear** [comment]
I think this can be closed, it's specific to Zen1 and the code in that raised the assertion here doesn't exist anymore.
