### ISSUE TITLE
SearchAsyncActionTests testLimitConcurrentShardRequests fails with RejectedExecutionException

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#36221]
Failure link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=opensuse/98/consoleFull

Error message:

```
13:08:25 ERROR   0.11s J1 | SearchAsyncActionTests.testLimitConcurrentShardRequests <<< FAILURES!
13:08:25    > Throwable #1: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=265, name=Thread-54, state=RUNNABLE, group=TGRP-SearchAsyncActionTests]
13:08:25    > Caused by: java.util.concurrent.RejectedExecutionException: Task org.elasticsearch.action.search.InitialSearchPhase$1@32524f5f rejected from java.util.concurrent.ThreadPoolExecutor@30e9de81[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 3]
13:08:25    > 	at __randomizedtesting.SeedInfo.seed([326E2801814230CE]:0)
13:08:25    > 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
13:08:25    > 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
13:08:25    > 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.fork(InitialSearchPhase.java:173)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:166)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.executeNext(InitialSearchPhase.java:237)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.lambda$performPhaseOnShard$4(InitialSearchPhase.java:290)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase$PendingExecutions.tryRun(InitialSearchPhase.java:213)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase$PendingExecutions.finishAndRunNext(InitialSearchPhase.java:207)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:168)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.executeNext(InitialSearchPhase.java:237)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:50)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase$2.innerOnResponse(InitialSearchPhase.java:267)
13:08:25    > 	at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:45)
13:08:25    > 	at org.elasticsearch.action.search.SearchAsyncActionTests$7.lambda$executePhaseOnShard$1(SearchAsyncActionTests.java:337)
13:08:25    > 	at java.lang.Thread.run(Thread.java:748)Throwable #2: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=264, name=Thread-53, state=RUNNABLE, group=TGRP-SearchAsyncActionTests]
13:08:25    > Caused by: java.util.concurrent.RejectedExecutionException: Task org.elasticsearch.action.search.InitialSearchPhase$1@2ea5ff4d rejected from java.util.concurrent.ThreadPoolExecutor@30e9de81[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 4]
13:08:25    > 	at __randomizedtesting.SeedInfo.seed([326E2801814230CE]:0)
13:08:25    > 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
13:08:25    > 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
13:08:25    > 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.fork(InitialSearchPhase.java:173)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:166)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.executeNext(InitialSearchPhase.java:237)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.lambda$performPhaseOnShard$4(InitialSearchPhase.java:290)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase$PendingExecutions.tryRun(InitialSearchPhase.java:213)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase$PendingExecutions.finishAndRunNext(InitialSearchPhase.java:207)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:168)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.executeNext(InitialSearchPhase.java:237)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:50)
13:08:25    > 	at org.elasticsearch.action.search.InitialSearchPhase$2.innerOnResponse(InitialSearchPhase.java:267)
13:08:25    > 	at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:45)
13:08:25    > 	at org.elasticsearch.action.search.SearchAsyncActionTests$7.lambda$executePhaseOnShard$1(SearchAsyncActionTests.java:337)
13:08:25    > 	at java.lang.Thread.run(Thread.java:748)
```

Reproduction line: 

```
./gradlew :server:test \
  -Dtests.seed=326E2801814230CE \
  -Dtests.class=org.elasticsearch.action.search.SearchAsyncActionTests \
  -Dtests.method="testLimitConcurrentShardRequests" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-LY \
  -Dtests.timezone=Atlantic/Stanley \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

This has failed 32 times in CI within the last 6 months. Also, #33699 seems related.

**Comment by danielmitterdorfer** [comment]
We discussed this one in the test triage power hour. This failure occurs due to the same reason as mentioned by David's analysis in https://github.com/elastic/elasticsearch/issues/33699#issuecomment-431062736.

Instead of scheduling new tasks unconditionally, we should rather use `scheduleUnlessShuttingDown()` to avoid this situation. See also the related refactoring effort #36318 (which is intended to replace call sites where we have manually implemented the mitigation that is missing here with `scheduleUnlessShuttingDown()`).
