### ISSUE TITLE
Packaging: investigate jdk-11 startup problems on SUSE 15 Leap

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#36256]
as per discussion here:
https://discuss.elastic.co/t/es-6-5-1-fatal-error-on-launch-with-jdk-11-no-error-runs-ok-with-jdk-1-8/157944/5

Elasticsearch is failing to start on Suse Leap 15 and jdk 11 from this linux distro. 
https://download.opensuse.org/repositories/Java:/Factory/openSUSE_Leap_15.0/x86_64/java-11-openjdk-headless-11.0.1.0-lp150.101.2.x86_64.rpm
We are not supporting this distro at the moment, but most likely we will plan to do that in near future due to end of maintenance for previous version.

```
18-12-05T11:26:23,994][INFO ][o.e.p.PluginsService     ] [y2cwFBj] no plugins loaded
[2018-12-05T11:26:28,285][INFO ][o.e.x.s.a.s.FileRolesStore] [y2cwFBj] parsed [0] roles from file [/etc/elasticsearch/roles.yml]
[2018-12-05T11:26:28,629][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [y2cwFBj] fatal error in thread [main], exiting
java.lang.ExceptionInInitializerError: null
        at org.elasticsearch.xpack.watcher.Watcher.createComponents(Watcher.java:289) ~[?:?]
        at org.elasticsearch.node.Node.lambda$new$11(Node.java:472) ~[elasticsearch-6.5.1.jar:6.5.1]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_171]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_171]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_171]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_171]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_171]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_171]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_171]
        at org.elasticsearch.node.Node.<init>(Node.java:475) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.5.1.jar:6.5.1]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.5.1.jar:6.5.1]
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "setFactory")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_171]
        at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_171]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_171]
        at java.lang.SecurityManager.checkSetFactory(SecurityManager.java:1664) ~[?:1.8.0_171]
        at javax.activation.CommandMap.setDefaultCommandMap(CommandMap.java:91) ~[?:1.8.0_171]
        at org.elasticsearch.xpack.watcher.notification.email.Account.lambda$static$0(Account.java:51) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
        at org.elasticsearch.xpack.watcher.notification.email.Account.<clinit>(Account.java:43) ~[?:?]
        ... 21 more
```
It is however correctly starting up on JDK dowloaded from https://jdk.java.net/11/
https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz
It is also starting up ok on that distro with JDK10 from that linux repo:
https://download.opensuse.org/repositories/Java:/Factory/openSUSE_Leap_15.0/x86_64/java-10-openjdk-headless-10.0.2.0-lp150.83.1.x86_64.rpm

just comparing the content of these RPM does not indicate any differences

**Comment by pgomulka** [comment]
User's security access logs when starting elasticsearch:
```
https://gist.github.com/pgomulka/8e5c4e24bea30800f71f8e08c19a80c7
```

Reproduced locally problem. Different access logs, but with the same exception in elasticsearch.log
```
https://gist.github.com/pgomulka/1da4b46ce285b04d9ec72602a71a2ce7
```

**Comment by pgomulka** [comment]
closing as suse15 is no longer supported

**Comment by rjernst** [comment]
@pgomulka Fwiw, we do support opensuse15 leap, it is just that we did not yet for 6.5.1. You can see recent OSes we are adding support (testing) for here: https://github.com/elastic/elasticsearch/issues/51481. We have had that particular OS in for a few months and CI is green: https://elasticsearch-ci.elastic.co/view/Elasticsearch%207.9/job/elastic+elasticsearch+7.9+multijob-unix-compatibility/os=opensuse-15-1&&immutable/

**Comment by pgomulka** [comment]
@rjernst ah you are right. I forgot that 42 +1 in suse math is 15 :)
The compatibility matrix confused me and I forgot about that versioning oddity.
I will reopen and give it last try

**Comment by pgomulka** [comment]
I replayed the steps with jdk 11 available now in SUSE repo, It works now
 (it was updated from https://download.opensuse.org/repositories/Java:/Factory/openSUSE_Leap_15.0/x86_64/java-11-openjdk-headless-11.0.1.0-lp150.101.2.x86_64.rpm to https://download.opensuse.org/repositories/Java:/Factory/openSUSE_Leap_15.2/x86_64/java-11-openjdk-11.0.8.0-lp152.156.5.x86_64.rpm)

steps
```
wget https://download.opensuse.org/repositories/Java:/Factory/openSUSE_Leap_15.2/x86_64/java-11-openjdk-headless-11.0.8.0-lp152.156.5.x86_64.rpm
zypper install java-11-openjdk-headless-11.0.8.0-lp152.156.5.x86_64.rpm
wget https://download.opensuse.org/repositories/Java:/Factory/openSUSE_Leap_15.2/x86_64/java-11-openjdk-11.0.8.0-lp152.156.5.x86_64.rpm
zypper install java-11-openjdk-11.0.8.0-lp152.156.5.x86_64.rpm

installed ES as per https://www.elastic.co/guide/en/elasticsearch/reference/6.8/rpm.html

started with systemd and confimed in logs that it uses installed JDK

[2020-08-20T14:57:20,530][INFO ][o.e.n.Node               ] [Lf1QBqo] version[6.8.12], pid[2614], build[default/rpm/7a15d2a/2020-08-12T07:27:20.804867Z], OS[Linux/4.12.14-lp151.28.52-default/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/11.0.8/11.0.8+10-suse-lp152.156.5-x8664]
```
closing as the issue is resolved.
