### ISSUE TITLE
Mixed cluster multi termvectors test failing in CI

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#36281]
In CI on master the MixedClusterClientYamlTestSuiteIT is failing on the `mtermvectors/10_basic/Basic tests for multi termvector get` test. A value in the response is null when it is expected to be not null.

Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/300/console

Reproduce:

```
./gradlew :qa:mixed-cluster:v6.6.0#mixedClusterTestRunner -Dtests.seed=B04BD3B8E4C8EFF8 -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT -Dtests.method="test {p0=mtermvectors/10_basic/Basic tests for multi termvector get}" -Dtests.security.manager=true -Dtests.locale=et -Dtests.timezone=Asia/Chongqing -Dcompiler.java=11 -Druntime.java=8
```

Error:

```
java.lang.AssertionError: Failure at [mtermvectors/10_basic:74]: field [docs.0.term_vectors.text.terms.brown.term_freq] is null
	at __randomizedtesting.SeedInfo.seed([B04BD3B8E4C8EFF8:381FEC624A348200]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:407)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:384)
```

Stash of response:

```
12:14:56   1> [2018-12-06T03:12:00,343][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] Stash dump on test failure [{
12:14:56   1>   "stash" : {
12:14:56   1>     "body" : {
12:14:56   1>       "docs" : [
12:14:56   1>         {
12:14:56   1>           "_index" : "testidx",
12:14:56   1>           "_type" : "_doc",
12:14:56   1>           "_id" : "testing_document",
12:14:56   1>           "_version" : 0,
12:14:56   1>           "found" : false,
12:14:56   1>           "took" : 0
12:14:56   1>         }
12:14:56   1>       ]
12:14:56   1>     }
12:14:56   1>   }
12:14:56   1> }]
```

**Comment by jaymode** [comment]
Muted in 5ba0ed9c8f57b954a122a5b364b09da5551118fd

**Comment by jaymode** [comment]
You are correct @jtibshirani, thank you for pointing that out. I have reverted muting this test.
