### ISSUE TITLE
 org.elasticsearch.bootstrap.BootstrapException: java.lang.IllegalStateException: running tests but failed to invoke RandomizedContext#getRandom

### ISSUE THREAD

**Issue by panchen66** [elastic/elasticsearch#36353]
When I run version 6.3.2 locally ，Report errors：
`Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.lang.IllegalStateException: running tests but failed to invoke RandomizedContext#getRandom
Likely root cause: java.lang.IllegalStateException: No context information for thread: Thread[id=1, name=main, state=RUNNABLE, group=main]. Is this thread running under a class com.carrotsearch.randomizedtesting.RandomizedRunner runner context? Add @RunWith(class com.carrotsearch.randomizedtesting.RandomizedRunner.class) to your test class. Make sure your code accesses random contexts within @BeforeClass and @AfterClass boundary (for example, static test class initializers are not permitted to access random contexts).
	at com.carrotsearch.randomizedtesting.RandomizedContext.context(RandomizedContext.java:248)
	at com.carrotsearch.randomizedtesting.RandomizedContext.current(RandomizedContext.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.elasticsearch.common.Randomness.get(Randomness.java:102)
	at org.elasticsearch.common.Randomness.createSecure(Randomness.java:122)
	at org.elasticsearch.common.settings.KeyStoreWrapper.addBootstrapSeed(KeyStoreWrapper.java:184)
	at org.elasticsearch.common.settings.KeyStoreWrapper.create(KeyStoreWrapper.java:177)
	at org.elasticsearch.bootstrap.Bootstrap.loadSecureSettings(Bootstrap.java:233)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:291)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:137)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:128)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:94)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:87)
Refer to the log for complete error details.`

What led to this?

**Comment by colings86** [comment]
How are you running Elasticsearch locally? This error usually indicates you are trying to run the Elasticsearch server either directly form an IDE or embedded in a JVM. Elasticsearch is designed to be run as a standalone server inside its own JVM.

**Comment by panchen66** [comment]
First of all,i run “gradlew eclipse”，then import in eclipse as General projects.Last , i
 run as java application for Elasticsearch.java

**Comment by danielmitterdorfer** [comment]
This is unfortunately not supported. Please see our [testing docs](https://github.com/elastic/elasticsearch/blob/master/TESTING.asciidoc#launching-and-debugging-from-an-ide) how to run / debug Elasticsearch from an IDE.
