### ISSUE TITLE
StackOverflowError somewhere in the cluster applier thread

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#36360]
A user reported that their master node died with the following exception

```
[2018-11-16T09:59:05,744][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [REDACTED] fatal error in thread [elasticsearch[REDACTED][clusterApplierService#updateTask][T#1]], exiting
java.lang.StackOverflowError: null
        at java.util.Collections$UnmodifiableList$1.<init>(Collections.java:1339) ~[?:1.8.0_111]
        at java.util.Collections$UnmodifiableList.listIterator(Collections.java:1337) ~[?:1.8.0_111]
        at java.util.Collections$UnmodifiableList$1.<init>(Collections.java:1339) ~[?:1.8.0_111]
        at java.util.Collections$UnmodifiableList.listIterator(Collections.java:1337) ~[?:1.8.0_111]
```

This repeats until the end of the file. As far as I can tell, this can't be an _infinite_ recursion, but it could be very deeply nested if an unmodifiable list is repeatedly rewrapped.

It is possible this was introduced by #31957 which looks like it might re-wraps some lists in `unmodifiableList` each time a new `DatafeedConfig` is constructed.

**Comment by dimitris-athanasiou** [comment]
Ouch. That is horrible. I'll work on a fix for this asap.
