### ISSUE TITLE
Elasticsearch fails to start intermittently. GC logs could be written node.lock if there is no output file specified.

### ISSUE THREAD

**Issue by dsshane** [elastic/elasticsearch#36393]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.2

**Plugins installed**: [AWS and Azure repository]

**JVM version** (`java -version`): OpenJDK 8 | 10

**OS version** (`uname -a` if on a Unix-like system): Windows Server 2012 R2

**Description of the problem including expected versus actual behavior**: Elasticsearch fails to start sometimes. I am seeing this most on VMs, especially when the system|disk is busy. Delete the data dir and retry may start properly sometime.

[2018-12-07T01:42:56,594][ERROR][o.e.b.Bootstrap          ] Exception
org.apache.lucene.store.AlreadyClosedException: Unexpected lock file size: 7999, (lock=NativeFSLock(path=C:\arcgisdatastore\elasticdata\nodes\0\node.lock,impl=sun.nio.ch.FileLockImpl[0:9223372036854775807 exclusive valid],creationTime=2018-12-07T09:42:50.290506Z))
                at org.apache.lucene.store.NativeFSLockFactory$NativeFSLock.ensureValid(NativeFSLockFactory.java:184) ~[lucene-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:51:45]
                at org.elasticsearch.env.NodeEnvironment.assertEnvIsLocked(NodeEnvironment.java:918) ~[elasticsearch-6.4.2.jar:6.4.2]
                at org.elasticsearch.env.NodeEnvironment.nodePaths(NodeEnvironment.java:720) ~[elasticsearch-6.4.2.jar:6.4.2]
                at org.elasticsearch.monitor.fs.FsProbe.stats(FsProbe.java:57) ~[elasticsearch-6.4.2.jar:6.4.2]
                at org.elasticsearch.monitor.fs.FsService.stats(FsService.java:65) ~[elasticsearch-6.4.2.jar:6.4.2]
                at org.elasticsearch.monitor.fs.FsService.<init>(FsService.java:56) ~[elasticsearch-6.4.2.jar:6.4.2]
                at org.elasticsearch.monitor.MonitorService.<init>(MonitorService.java:50) ~[elasticsearch-6.4.2.jar:6.4.2]
                at org.elasticsearch.node.Node.<init>(Node.java:367) ~[elasticsearch-6.4.2.jar:6.4.2]
                at org.elasticsearch.node.Node.<init>(Node.java:256) ~[elasticsearch-6.4.2.jar:6.4.2]
                at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.4.2.jar:6.4.2]
                at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.4.2.jar:6.4.2]
                at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) [elasticsearch-6.4.2.jar:6.4.2]
                at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) [elasticsearch-6.4.2.jar:6.4.2]
                at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) [elasticsearch-6.4.2.jar:6.4.2]
                at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.4.2.jar:6.4.2]
                at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.4.2.jar:6.4.2]
                at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.4.2.jar:6.4.2]
                at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.4.2.jar:6.4.2]
                at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) [elasticsearch-6.4.2.jar:6.4.2]

**Comment by jbaiera** [comment]
@dsshane Is the directory that the node is using on the local filesystem or is it configured through some sort of remote/network based storage?

**Comment by dsshane** [comment]
@jbaiera It is local file system, on a virtual machine.

**Comment by danielmitterdorfer** [comment]
@dsshane if the issue occurs again, can you please issue the following commands and paste the output?

```
# go to the directory where the node lock file is located - I'll use the one from the example above
cd C:\arcgisdatastore\elasticdata\nodes\0\
dir node.lock
# get info about your file system
fsutil fsinfo volumeinfo c:
```

Can you please also attach the `node.lock` file to this ticket then? Note that you'll need to zip it  because Github only allows to upload certain file types.

Also, can you please clarify what you mean by:

> I am seeing this most on VMs, especially when the system|disk is busy.

How do you determine that the disk is busy? Is it busy before you start Elasticsearch? What process is using the disk?

Finally, do you run any virus scanner on this system?

**Comment by dsshane** [comment]
[nodelock.zip](https://github.com/elastic/elasticsearch/files/2672514/nodelock.zip)

@danielmitterdorfer Please find the node.lock in the attached zip file; and the following is the output of fsutil:

c:\arcgisdatastore\elasticdata\nodes\0>fsutil fsinfo volumeinfo c:
Volume Name : OSDisk
Volume Serial Number : 0x2e134eac
Max Component Length : 255
File System Name : NTFSv
Supports Case-sensitive filenames
Preserves Case of filenames
Supports Unicode in filenames
Preserves & Enforces ACL's
Supports file-based Compression
Supports Disk Quotas
Supports Sparse files
Supports Reparse Points
Supports Object Identifiers
Supports Encrypted File System
Supports Named Streams
Supports Transactions
Supports Hard Links
Supports Extended Attributes
Supports Open By FileID
Supports USN Journal

By saying system|disk is busy, I mean:  if I start other parts of my application first (databases, web app, etc) and then Elasticsearch, we saw this problem _intermittently_; We have rarely seen this issue when just run Elasticsearch by itself (without start any other application). 

Yes, Sophos Anti-Virus is running on the machine.

**Comment by dsshane** [comment]
[jvm.zip](https://github.com/elastic/elasticsearch/files/2672693/jvm.zip)

@danielmitterdorfer That is very interesting, indeed. Don't understand how the jvm GC log was written into node.lock :). Please see attached jvm.zip for the jvm.properties.

**Comment by danielmitterdorfer** [comment]
Thanks. I had a look at your `jvm.options` and it seems your GC log configuration is broken (to be clear: I don't think that this should lead to GC logs showing up in `node.lock` but it should be fixed anyway):

Can you please *replace* the line:

```
9-:-Xlog:gc*
```

with this one:

```
9-:-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m
```

This will write the GC logs to the file `logs/gc.log`.

Then please stop Elasticsearch, be sure to cleanup any broken `node.lock` files that might still be around and start it again.

Can you please report here whether this has fixed your issue around `node.lock`?

**Comment by dsshane** [comment]
@danielmitterdorfer Thanks a lot! I am actually thinking about removing the entire -Xlog flag. Will that work?

**Comment by danielmitterdorfer** [comment]
Yes. you can also remove the entire line as well. Note that Elasticsearch does not write any garbage collection log as a consequence.

**Comment by dsshane** [comment]
@danielmitterdorfer Remove the -Xlog:gc seems working, at least have not reproduced it since yesterday. Thanks.

**But still believe that the problem should be fixed to make sure that no GC log or any other log written into the node.lock(critical system file), no matter the log output file is provided or not.**

**Comment by danielmitterdorfer** [comment]
Thanks for your feedback. Based on this I close the issue.

> But still believe that the problem should be fixed to make sure that no GC log or any other log written into the node.lock(critical system file), no matter the log output file is provided or not.

I understand that wish but what you are asking for is next to impossible to achieve (I am open for suggestions though :)). We are already taking care that Elasticsearch refuses to start if this file has been tampered with (this is what you have experienced) and we have not only the file size check but several others in place that ensure the integrity of this file. However, It can always happen that e.g. due to a misconfiguration this file is invalid. E.g. nothing is stopping you from creating a file with that name with a text editor and saving some text in it (similarly for misconfiguration of the JVM parameters), or telling some other program to write its log files to that file and then starting Elasticsearch. You cannot really prevent such scenarios and that's why we have those checks in place to fail early, refuse to start and tell you that there is a serious problem with integrity.

**Comment by dsshane** [comment]
@danielmitterdorfer Thanks for your help and your comment.

 But I am some kind of disagree with what you said. It will be a very simple change. If -Xlog:gc is set, but there is no output file, just provide a default location under the log_dir. And actually, I don't agree that this is a misconfiguration by not providing a GC log location.  For a robust system, it should take care of this internally. Further more, why the GC log goes to the **system critical file** but not other file(i.e,  log file)?
