### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT explain/11_basic_with_types/Explain body without query element failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#36469]
Build log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/666/console

Reproduces with: `./gradlew :qa:mixed-cluster:v6.6.0#mixedClusterTestRunner -Dtests.seed=D39E8465F0EDD878 -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT -Dtests.method="test {p0=explain/11_basic_with_types/Explain body without query element}" -Dtests.security.manager=true -Dtests.locale=en-CA -Dtests.timezone=America/Fort_Nelson -Dcompiler.java=11 -Druntime.java=8`

Relevant build log:

```
1> [2018-12-10T21:40:45,702][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] [p0=explain/11_basic_with_types/Explain body without query element] before test
  1> [2018-12-10T21:40:45,882][WARN ][o.e.c.RestClient         ] [[I/O dispatcher 2]] request [PUT http://[::1]:41496/test_1?error_trace=true] returned 1 warnings: [29
9 Elasticsearch-6.6.0-SNAPSHOT-32344e7 "the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you
 must manage this on the create index request or with an index template" "Tue, 11 Dec 2018 04:40:45 GMT"]
  1> [2018-12-10T21:40:45,990][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "_index" : "test_1",
  1>       "_type" : "_explain",
  1>       "_id" : "id_1",
  1>       "found" : false
  1>     }
  1>   }
  1> }]
  1> [2018-12-10T21:40:46,057][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] [p0=explain/11_basic_with_types/Explain body without query element] after test
FAILURE 0.36s | MixedClusterClientYamlTestSuiteIT.test {p0=explain/11_basic_with_types/Explain body without query element} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [explain/11_basic_with_types:58]: expected [400] status code but api [explain] returned [404 Not Found] [{"_index":"test_1","_type":"_explain","_id":"id_1","found":false}]
   > Expected: <400>
   >      but: was <404>
   >    at __randomizedtesting.SeedInfo.seed([D39E8465F0EDD878:5BCABBBF5E11B580]:0)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:407)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:384)
   >    at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.lang.AssertionError: expected [400] status code but api [explain] returned [404 Not Found] [{"_index":"test_1","_type":"_explain","_id":"id_1","found":false}]
   > Expected: <400>
   >      but: was <404>
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.test.rest.yaml.section.DoSection.assertStatusCode(DoSection.java:345)
   >    at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:263)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:400)
   >    ... 37 more
```

Related PR: #35611

**Comment by martijnvg** [comment]
Another instance: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/669/console

**Comment by jtibshirani** [comment]
Thank you @martijnvg for muting this, and sorry for the trouble. I've fixed the test in https://github.com/elastic/elasticsearch/commit/eb733f404aa9ce97a5c2fe6a6980521a9c455c74.
