### ISSUE TITLE
[CI] InternalEngineTests#testRebuildLocalCheckpointTracker test failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#36470]
Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.5+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/93/console

Does not reproduce for me.

Relevant build log:

```
1> [2018-12-10T22:07:38,378][INFO ][o.e.i.e.InternalEngineTests] [testRebuildLocalCheckpointTracker] after test
FAILURE 0.19s J2 | InternalEngineTests.testRebuildLocalCheckpointTracker <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: seq_no=41 max_seq_no=57 checkpoint=57
   > Expected: <false>
   >      but: was <true>
   > 	at __randomizedtesting.SeedInfo.seed([2F728EA92D51477F:A32D4F9849005BBA]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.index.engine.InternalEngineTests.testRebuildLocalCheckpointTracker(InternalEngineTests.java:5315)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   > 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   > 	at java.base/java.lang.Thread.run(Thread.java:834)
  1> [2018-12-10T22:07:38,402][INFO ][o.e.i.e.InternalEngineTests] [testIndexWriterIFDInfoStream] before test
```

**Comment by dnhatn** [comment]
This test still fails on the master branch. Some instances:
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/224/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/821/console
