### ISSUE TITLE
Netty4HttpRequestSizeLimitIT testDoesNotLimitExcludedRequests fails reproducibly

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#36496]
I hit the following failure in `Netty4HttpRequestSizeLimitIT#testDoesNotLimitExcludedRequests` locally and it consistently reproduces on master as of writing (commit 084e06e481bc14f0ec1a71cc0444b1e05a1bbe20).

Failure:

```
FAILURE 40.5s | Netty4HttpRequestSizeLimitIT.testDoesNotLimitExcludedRequests <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failed to get all expected responses.
   >    at __randomizedtesting.SeedInfo.seed([898AB80ABB9F5DAD:73FB0193B66107ED]:0)
   >    at org.elasticsearch.http.netty4.Netty4HttpClient.sendRequests(Netty4HttpClient.java:150)
   >    at org.elasticsearch.http.netty4.Netty4HttpClient.processRequestsWithBody(Netty4HttpClient.java:130)
   >    at org.elasticsearch.http.netty4.Netty4HttpClient.put(Netty4HttpClient.java:116)
   >    at org.elasticsearch.http.netty4.Netty4HttpRequestSizeLimitIT.testDoesNotLimitExcludedRequests(Netty4HttpRequestSizeLimitIT.java:124)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   >    at java.base/java.lang.Thread.run(Thread.java:834)
```

Reproduce line:

```
./gradlew :modules:transport-netty4:integTestRunner -Dtests.seed=898AB80ABB9F5DAD -Dtests.class=org.elasticsearch.http.netty4.Netty4HttpRequestSizeLimitIT -Dtests.method="testDoesNotLimitExcludedRequests" -Dtests.security.manager=true -Dtests.locale=en-PK -Dtests.timezone=SystemV/YST9YDT -Dcompiler.java=11 -Druntime.java=11
```

**Comment by original-brownbear** [comment]
Also found a way to speed up the underlying setting update logic in https://github.com/elastic/elasticsearch/pull/36560 I think.
