### ISSUE TITLE
Pagerduty Integration Warning on Non-Secure Setting When Secure Setting exists

### ISSUE THREAD

**Issue by danielkasen** [elastic/elasticsearch#36516]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.1

Setting up the PD integration using the Keystore method and ES likes to complain about the service_api_key

**Steps to reproduce**:

 1. Add the integration Key to the Keystore 
`echo <PD_Integration> | /usr/share/elasticsearch/bin/elasticsearch-keystore add --stdin xpack.notification.pagerduty.account.watcher-default.secure_service_api_key`
 2. Add the Dynamic account
```
PUT _cluster/settings
{ "xpack": {
      "notification" : {
        "pagerduty" : {
          "account" : {
            "kibana-logs" : {
              "event_defaults" : {
                "description" : "kibana-logs Pagerduty Integration"
              }
            }
        }
   }
 }
}
 ```

**Provide logs (if relevant)**:

```
 [i-0cdae7c8b49b3ab1e]failed to apply settings
org.elasticsearch.common.settings.SettingsException: invalid pagerduty account [kibana-logs]. missing required [service_api_key] setting
	at org.elasticsearch.xpack.watcher.notification.pagerduty.PagerDutyAccount.getServiceKey(PagerDutyAccount.java:62) ~[?:?]
	at org.elasticsearch.xpack.watcher.notification.pagerduty.PagerDutyAccount.<init>(PagerDutyAccount.java:36) ~[?:?]
	at org.elasticsearch.xpack.watcher.notification.pagerduty.PagerDutyService.createAccount(PagerDutyService.java:54) ~[?:?]
	at org.elasticsearch.xpack.watcher.notification.pagerduty.PagerDutyService.createAccount(PagerDutyService.java:23) ~[?:?]
	at org.elasticsearch.xpack.watcher.notification.NotificationService.buildAccounts(NotificationService.java:76) ~[?:?]
```

**Comment by danielkasen** [comment]
I can try. Is there a commit you could point me to, it'd help me get the bandwidth to prioritize this.

**Comment by danielkasen** [comment]
After upgrading this appears to be resolved. Thank you.

**Comment by innovia** [comment]
@spinscale can you please share how you got pagerduty configured - the docs are way outdated and wrong, been spending 4 hours straight on trying now
