### ISSUE TITLE
[CI] testCorruptFileThenSnapshotAndRestore fails

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#36526]
Build failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/705/console

Reproduce command:

```
./gradlew :server:integTest \
  -Dtests.seed=7CC5E12B116EE7EF \
  -Dtests.class=org.elasticsearch.index.store.CorruptedFileIT \
  -Dtests.method="testCorruptFileThenSnapshotAndRestore" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-NI \
  -Dtests.timezone=America/Puerto_Rico \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Log:

```
2-12T00:39:28,545][INFO ][o.e.i.s.CorruptedFileIT  ] [testCorruptFileThenSnapshotAndRestore] Index [221] docs async: [true] bulk: [false]
  1> [2018-12-12T00:39:28,547][WARN ][o.e.i.IndexSettings      ] [node_s0] [test] [index.merge.enabled] is set to false, this should only be used in tests and can cause serious problems in production environments
  1> [2018-12-12T00:39:28,549][INFO ][o.e.c.m.MetaDataMappingService] [node_s0] [test/eD6rpLjqTyC4pjUH0FwtvA] create_mapping [type]
  1> [2018-12-12T00:39:28,567][WARN ][o.e.i.IndexSettings      ] [node_s0] [test] [index.merge.enabled] is set to false, this should only be used in tests and can cause serious problems in production environments
  1> [2018-12-12T00:39:28,910][INFO ][o.e.t.CorruptionUtils    ] [testCorruptFileThenSnapshotAndRestore] Corrupting file --  flipping at position 907 from 72 to 73 file: _3.cfs
  1> [2018-12-12T00:39:28,912][INFO ][o.e.t.CorruptionUtils    ] [testCorruptFileThenSnapshotAndRestore] Checksum before: [999714073] after: [161080920] checksum value after corruption: 999714073] file: _3.cfs length: 2284
  1> [2018-12-12T00:39:28,912][INFO ][o.e.i.s.CorruptedFileIT  ] [testCorruptFileThenSnapshotAndRestore] --> shard [test][2], node[ONuHLlycR6OL81UlFk5aVA], [P], s[STARTED], a[id=XPSQ4UN1TDufxKK3h56rZA] has a corrupted file
  1> [2018-12-12T00:39:28,912][INFO ][o.e.i.s.CorruptedFileIT  ] [testCorruptFileThenSnapshotAndRestore] -->  creating repository
  1> [2018-12-12T00:39:28,928][INFO ][o.e.r.RepositoriesService] [node_s0] put repository [test-repo]
  1> [2018-12-12T00:39:28,963][INFO ][o.e.i.s.CorruptedFileIT  ] [testCorruptFileThenSnapshotAndRestore] --> snapshot
  1> [2018-12-12T00:39:28,990][INFO ][o.e.s.SnapshotsService   ] [node_s0] snapshot [test-repo:test-snap/hRZIxqy3RGm_t_khLuZA6w] started
  1> [2018-12-12T00:39:29,096][INFO ][o.e.s.SnapshotsService   ] [node_s0] snapshot [test-repo:test-snap/hRZIxqy3RGm_t_khLuZA6w] completed with state [SUCCESS]
  1> [2018-12-12T00:39:29,128][INFO ][o.e.i.s.CorruptedFileIT  ] [testCorruptFileThenSnapshotAndRestore] --> snapshot terminated with state SUCCESS
  1> [2018-12-12T00:39:29,138][INFO ][o.e.i.s.CorruptedFileIT  ] [testCorruptFileThenSnapshotAndRestore] [CorruptedFileIT#testCorruptFileThenSnapshotAndRestore]: cleaning up after test
  1> [2018-12-12T00:39:29,155][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_s0] [test/eD6rpLjqTyC4pjUH0FwtvA] deleting index
  1> [2018-12-12T00:39:29,238][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_s0] removing template [random_index_template]
  1> [2018-12-12T00:39:29,258][INFO ][o.e.r.RepositoriesService] [node_s0] delete repository [test-repo]
  1> [2018-12-12T00:39:29,276][INFO ][o.e.i.s.CorruptedFileIT  ] [testCorruptFileThenSnapshotAndRestore] [CorruptedFileIT#testCorruptFileThenSnapshotAndRestore]: cleaned up after test
  1> [2018-12-12T00:39:29,276][INFO ][o.e.i.s.CorruptedFileIT  ] [testCorruptFileThenSnapshotAndRestore] after test
FAILURE 1.22s J7 | CorruptedFileIT.testCorruptFileThenSnapshotAndRestore <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <PARTIAL>
   >      but: was <SUCCESS>
   > 	at __randomizedtesting.SeedInfo.seed([7CC5E12B116EE7EF:B1115BAA8372AD8C]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.index.store.CorruptedFileIT.testCorruptFileThenSnapshotAndRestore(CorruptedFileIT.java:531)
   > 	at java.lang.Thread.run(Thread.java:748)
```

I believe this failure relates to soft-deletes (https://github.com/elastic/elasticsearch/pull/36141).

**Comment by s1monw** [comment]
@ywelsch @andrershov  I assigned this to me. I have a fix ready.

**Comment by dnhatn** [comment]
@s1monw This test still fails. Some instances:
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/793/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu&&virtual/120/console

Log:

```
1> [2018-12-15T17:16:35,239][INFO ][o.e.i.s.CorruptedFileIT  ] [testCorruptFileThenSnapshotAndRestore] Index [614] docs async: [false] bulk: [true] partitions [18]
  1> [2018-12-15T17:16:35,307][WARN ][o.e.i.IndexSettings      ] [node_sm0] [test] [index.merge.enabled] is set to false, this should only be used in tests and can cause serious problems in production environments
  1> [2018-12-15T17:16:35,314][INFO ][o.e.c.m.MetaDataMappingService] [node_sm0] [test/TRRNthQ7QaOSlMChccmHhw] create_mapping [type]
  1> [2018-12-15T17:16:35,362][WARN ][o.e.i.IndexSettings      ] [node_sm0] [test] [index.merge.enabled] is set to false, this should only be used in tests and can cause serious problems in production environments
  1> [2018-12-15T17:16:37,519][INFO ][o.e.t.CorruptionUtils    ] [testCorruptFileThenSnapshotAndRestore] Corrupting file --  flipping at position 446 from 57 to 58 file: _1.cfs
  1> [2018-12-15T17:16:37,520][INFO ][o.e.t.CorruptionUtils    ] [testCorruptFileThenSnapshotAndRestore] Checksum before: [825308441] after: [663104317] checksum value after corruption: 825308441] file: _1.cfs length: 3059
  1> [2018-12-15T17:16:37,521][INFO ][o.e.i.s.CorruptedFileIT  ] [testCorruptFileThenSnapshotAndRestore] --> shard [test][5], node[9AzNi0R4Qw28xpBmEmHNkw], [P], s[STARTED], a[id=PLC3bd4JSBCE8QYcrPHQwQ] has a corrupted file
  1> [2018-12-15T17:16:37,521][INFO ][o.e.i.s.CorruptedFileIT  ] [testCorruptFileThenSnapshotAndRestore] -->  creating repository
  1> [2018-12-15T17:16:37,539][INFO ][o.e.r.RepositoriesService] [node_sm0] put repository [test-repo]
  1> [2018-12-15T17:16:37,578][INFO ][o.e.i.s.CorruptedFileIT  ] [testCorruptFileThenSnapshotAndRestore] --> snapshot
  1> [2018-12-15T17:16:37,612][INFO ][o.e.s.SnapshotsService   ] [node_sm0] snapshot [test-repo:test-snap/baTyAPaPSuaDe8bl4x5G1A] started
  1> [2018-12-15T17:16:38,052][INFO ][o.e.s.SnapshotsService   ] [node_sm0] snapshot [test-repo:test-snap/baTyAPaPSuaDe8bl4x5G1A] completed with state [SUCCESS]
  1> [2018-12-15T17:16:38,082][INFO ][o.e.i.s.CorruptedFileIT  ] [testCorruptFileThenSnapshotAndRestore] --> snapshot terminated with state SUCCESS
  1> [2018-12-15T17:16:38,093][INFO ][o.e.i.s.CorruptedFileIT  ] [testCorruptFileThenSnapshotAndRestore] [CorruptedFileIT#testCorruptFileThenSnapshotAndRestore]: cleaning up after test
  1> [2018-12-15T17:16:38,129][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/TRRNthQ7QaOSlMChccmHhw] deleting index
  1> [2018-12-15T17:16:38,241][WARN ][o.e.i.IndexSettings      ] [node_sm0] [test] [index.merge.enabled] is set to false, this should only be used in tests and can cause serious problems in production environments
  1> [2018-12-15T17:16:38,242][WARN ][o.e.i.IndexSettings      ] [node_sm0] [test] [index.merge.enabled] is set to false, this should only be used in tests and can cause serious problems in production environments
  1> [2018-12-15T17:16:38,249][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
  1> [2018-12-15T17:16:38,261][INFO ][o.e.r.RepositoriesService] [node_sm0] delete repository [test-repo]
  1> [2018-12-15T17:16:38,275][INFO ][o.e.i.s.CorruptedFileIT  ] [testCorruptFileThenSnapshotAndRestore] [CorruptedFileIT#testCorruptFileThenSnapshotAndRestore]: cleaned up after test
  1> [2018-12-15T17:16:38,276][INFO ][o.e.i.s.CorruptedFileIT  ] [testCorruptFileThenSnapshotAndRestore] after test
FAILURE 3.61s J7 | CorruptedFileIT.testCorruptFileThenSnapshotAndRestore <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <PARTIAL>
   >      but: was <SUCCESS>
   > 	at __randomizedtesting.SeedInfo.seed([DC853C211AEE5A36:115186A088F21055]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.index.store.CorruptedFileIT.testCorruptFileThenSnapshotAndRestore(CorruptedFileIT.java:531)
   > 	at java.lang.Thread.run(Thread.java:748)

**Comment by spinscale** [comment]
another one https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8fips,nodes=virtual&&linux/125/console - so just waiting for the PR to be merged
