### ISSUE TITLE
[CI] MasterDisruptionIT.testFailWithMinimumMasterNodesConfigured fails with AssertionError: wrong master on node

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#36547]
Couldn't reproduce it locally. Initial report [here](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/202/console).

`gradlew :server:integTest   -Dtests.seed=CB78964A31A41973 -Dtests.class=org.elasticsearch.discovery.MasterDisruptionIT -Dtests.method="testFailWithMinimumMasterNodesConfigured" -Dtests.security.manager=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=hr -Dtests.timezone=Indian/Cocos -Dcompiler.java=11 -Druntime.java=8`

```
java.lang.AssertionError: wrong master on node [node_t0]. cluster_state:
cluster uuid: YARNArQdRkK_u6kOO0wr1A
version: 7
state uuid: N7Dv3JGdQKKbJwqkf5LokA
from_diff: false
meta data version: 2
   coordination_metadata:
      term: 2
      last_committed_config: VotingConfiguration{j93CCaCERLWEBO0DApPVCQ,nqEQzYg-S2e0DU9zhWlFIA,w71IK2jZTjW-bWHTtJNDpA}
      last_accepted_config: VotingConfiguration{j93CCaCERLWEBO0DApPVCQ,nqEQzYg-S2e0DU9zhWlFIA,w71IK2jZTjW-bWHTtJNDpA}
      voting tombstones: []
metadata customs:
   index-graveyard: IndexGraveyard[[]]
nodes: 
   {node_t2}{nqEQzYg-S2e0DU9zhWlFIA}{lHEH5ZSQSJSiTACfdLEesQ}{127.0.0.1}{127.0.0.1:33574}
   {node_t1}{j93CCaCERLWEBO0DApPVCQ}{1J2HRNsvSzeHjba-wIqyiA}{127.0.0.1}{127.0.0.1:36024}, master
   {node_t0}{w71IK2jZTjW-bWHTtJNDpA}{Fug8yEG1SjSYLQXXtF4iqw}{127.0.0.1}{127.0.0.1:45382}, local
routing_table (version 1):
routing_nodes:
-----node_id[j93CCaCERLWEBO0DApPVCQ][V]
-----node_id[w71IK2jZTjW-bWHTtJNDpA][V]
-----node_id[nqEQzYg-S2e0DU9zhWlFIA][V]
---- unassigned

Expected: "node_t0"
     but: was "node_t1"
	at __randomizedtesting.SeedInfo.seed([CB78964A31A41973:99BF1E06E9BE4C24]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.discovery.AbstractDisruptionTestCase.lambda$assertMaster$2(AbstractDisruptionTestCase.java:202)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:847)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:821)
	at org.elasticsearch.discovery.AbstractDisruptionTestCase.assertMaster(AbstractDisruptionTestCase.java:196)
	at org.elasticsearch.discovery.MasterDisruptionIT.testFailWithMinimumMasterNodesConfigured(MasterDisruptionIT.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.AssertionError: wrong master on node [node_t0]. cluster_state:
cluster uuid: YARNArQdRkK_u6kOO0wr1A
version: 7
state uuid: N7Dv3JGdQKKbJwqkf5LokA
from_diff: false
meta data version: 2
   coordination_metadata:
      term: 2
      last_committed_config: VotingConfiguration{j93CCaCERLWEBO0DApPVCQ,nqEQzYg-S2e0DU9zhWlFIA,w71IK2jZTjW-bWHTtJNDpA}
      last_accepted_config: VotingConfiguration{j93CCaCERLWEBO0DApPVCQ,nqEQzYg-S2e0DU9zhWlFIA,w71IK2jZTjW-bWHTtJNDpA}
      voting tombstones: []
metadata customs:
   index-graveyard: IndexGraveyard[[]]
nodes: 
   {node_t2}{nqEQzYg-S2e0DU9zhWlFIA}{lHEH5ZSQSJSiTACfdLEesQ}{127.0.0.1}{127.0.0.1:33574}
   {node_t1}{j93CCaCERLWEBO0DApPVCQ}{1J2HRNsvSzeHjba-wIqyiA}{127.0.0.1}{127.0.0.1:36024}, master
   {node_t0}{w71IK2jZTjW-bWHTtJNDpA}{Fug8yEG1SjSYLQXXtF4iqw}{127.0.0.1}{127.0.0.1:45382}, local
routing_table (version 1):
routing_nodes:
-----node_id[j93CCaCERLWEBO0DApPVCQ][V]
-----node_id[w71IK2jZTjW-bWHTtJNDpA][V]
-----node_id[nqEQzYg-S2e0DU9zhWlFIA][V]
---- unassigned

Expected: "node_t0"
     but: was "node_t1"
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.elasticsearch.discovery.AbstractDisruptionTestCase.lambda$assertMaster$2(AbstractDisruptionTestCase.java:202)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 40 more
```

**Comment by DaveCTurner** [comment]
This is a bit of a puzzle. Pertinent log messages:

```
  1> [2018-12-12T15:08:13,996][INFO ][o.e.t.d.NetworkDisruption] [testFailWithMinimumMasterNodesConfigured] stop disrupting (disruption scheme: network disconnects, disrupted links: two partitions (partition 1: [node_t0] and partition 2:
  1> [2018-12-12T15:08:13,997][DEBUG][o.e.d.MasterDisruptionIT ] [testFailWithMinimumMasterNodesConfigured] ensuring cluster is stable with [3] nodes. access node: [node_t1]. timeout: [30s]
  1> [2018-12-12T15:08:13,997][TRACE][o.e.c.s.MasterService    ] [node_t0] will process [cluster_health (wait_for_events [LANGUID])]
  1> [2018-12-12T15:08:13,997][DEBUG][o.e.c.s.MasterService    ] [node_t0] processing [cluster_health (wait_for_events [LANGUID])]: execute
  1> [2018-12-12T15:08:13,997][DEBUG][o.e.c.s.MasterService    ] [node_t0] processing [cluster_health (wait_for_events [LANGUID])]: took [0s] no change in cluster state
... activity on [node_t2] only ...
  1> [2018-12-12T15:08:15,980][DEBUG][o.e.c.c.FollowersChecker ] [node_t0] FollowerChecker{discoveryNode={node_t1}{j93CCaCERLWEBO0DApPVCQ}{1J2HRNsvSzeHjba-wIqyiA}{127.0.0.1}{127.0.0.1:36024}, failureCountSinceLastSuccess=1, [cluster.fault
  1> [2018-12-12T15:08:15,980][DEBUG][o.e.c.c.LeaderChecker    ] [node_t1] 1 consecutive failures (limit [cluster.fault_detection.leader_check.retry_count] is 1) so leader [{node_t0}{w71IK2jZTjW-bWHTtJNDpA}{Fug8yEG1SjSYLQXXtF4iqw}{127.0.0
  1> [2018-12-12T15:08:15,980][DEBUG][o.e.c.c.Coordinator      ] [node_t1] onLeaderFailure: becoming CANDIDATE (was FOLLOWER, lastKnownLeader was [Optional[{node_t0}{w71IK2jZTjW-bWHTtJNDpA}{Fug8yEG1SjSYLQXXtF4iqw}{127.0.0.1}{127.0.0.1:453
  1> [2018-12-12T15:08:15,980][TRACE][o.e.c.s.MasterService    ] [node_t0] will process [node-left[{node_t1}{j93CCaCERLWEBO0DApPVCQ}{1J2HRNsvSzeHjba-wIqyiA}{127.0.0.1}{127.0.0.1:36024} followers check retry count exceeded]]
  1> [2018-12-12T15:08:15,981][DEBUG][o.e.c.s.MasterService    ] [node_t0] processing [node-left[{node_t1}{j93CCaCERLWEBO0DApPVCQ}{1J2HRNsvSzeHjba-wIqyiA}{127.0.0.1}{127.0.0.1:36024} followers check retry count exceeded]]: execute
...
  1> [2018-12-12T15:08:19,455][WARN ][o.e.t.TransportService   ] [node_t1] Received response for a request that has timed out, sent [4402ms] ago, timed out [3402ms] ago, action [internal:coordination/fault_detection/leader_check], node [{
  1> [2018-12-12T15:08:19,457][WARN ][o.e.t.TransportService   ] [node_t0] Received response for a request that has timed out, sent [4402ms] ago, timed out [3402ms] ago, action [internal:coordination/fault_detection/follower_check], node
```

We remove the network disruption. A couple of seconds later some health checks time out, disrupting the cluster. It recovers but with a different master. The timed-out health checks come through eventually.

**Comment by DaveCTurner** [comment]
Ah, this happened on the day that CI was running very slowly, resulting in other timeout-related failures such as https://github.com/elastic/elasticsearch/issues/36556. I blame that.

**Comment by gwbrown** [comment]
This happened again today in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1215 - I'm inclined to agree with the assessment that it's timing-related, but I figured I'd add to this record just in case.

**Comment by jaymode** [comment]
I hit a failure in a PR today build (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/4971/console). A master was not elected during the run of the test:

```
ERROR   84.8s J0 | MasterDisruptionIT.testFailWithMinimumMasterNodesConfigured <<< FAILURES!
   > Throwable #1: MasterNotDiscoveredException[null]
   > 	at __randomizedtesting.SeedInfo.seed([69F853B3DBA3D412:3B3FDBFF03B98145]:0)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:259)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:322)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:249)
   > 	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:565)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   > 	at java.lang.Thread.run(Thread.java:748)
```

The timing (84s) indicates that there may be some serious slowness when compared to my MBP running the reproduce line and completing the test in 7.2s. Adding here in case it isn't just a slow CI worker.

**Comment by jbaiera** [comment]
To add to the pile: Saw this on an intake build failure https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1347/

Seems that node 2 times out with the master node around the time that the master loses connection with node 1 (the unlucky one). Seems that at this point node 2 can form a cluster with node 1 (not sure if the two of them are partitioned the same way that the master node is with the unlucky node).
