### ISSUE TITLE
[CI] ClusterInfoServiceIT.testClusterInfoServiceInformationClearOnError failures on master and 6.x

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#36554]
On 6.x https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/578/console:

```
REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=A4B290E7B8F374EE \
  -Dtests.class=org.elasticsearch.cluster.ClusterInfoServiceIT \
  -Dtests.method="testClusterInfoServiceInformationClearOnError" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-AE \
  -Dtests.timezone=Africa/Niamey \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

On master https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/339/console:

```
REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=82D50716404C8197 \
  -Dtests.class=org.elasticsearch.cluster.ClusterInfoServiceIT \
  -Dtests.method="testClusterInfoServiceInformationClearOnError" \
  -Dtests.security.manager=true \
  -Dtests.locale=ca \
  -Dtests.timezone=America/Montreal \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

It doesn't reproduce for me in 50 attempts.

```
java.lang.AssertionError: 
Expected: a value greater than <0>
     but: <0> was equal to <0>
	at __randomizedtesting.SeedInfo.seed([82D50716404C8197:1992237DE5ABEA32]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.cluster.ClusterInfoServiceIT.testClusterInfoServiceInformationClearOnError(ClusterInfoServiceIT.java:244)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jaymode** [comment]
It looks like this issue is still occurring. I hit this on a PR build:

```
14:04:19 FAILURE 28.8s J7 | ClusterInfoServiceIT.testClusterInfoServiceInformationClearOnError <<< FAILURES!
14:04:19    > Throwable #1: java.lang.AssertionError: 
14:04:19    > Expected: a value greater than <0>
14:04:19    >      but: <0> was equal to <0>
14:04:19    > 	at __randomizedtesting.SeedInfo.seed([244E3223CBDCED3D:BF0916486E3B8698]:0)
14:04:19    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
14:04:19    > 	at org.elasticsearch.cluster.ClusterInfoServiceIT.testClusterInfoServiceInformationClearOnError(ClusterInfoServiceIT.java:250)
14:04:19    > 	at java.lang.Thread.run(Thread.java:748)
```

```
./gradlew :server:integTest -Dtests.seed=244E3223CBDCED3D -Dtests.class=org.elasticsearch.cluster.ClusterInfoServiceIT -Dtests.method="testClusterInfoServiceInformationClearOnError" -Dtests.security.manager=true -Dtests.locale=id -Dtests.timezone=SystemV/CST6CDT -Dcompiler.java=11 -Druntime.java=8
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/5009/console

**Comment by ywelsch** [comment]
No recent failures
