### ISSUE TITLE
[CI] MasterDisruptionIT.testStaleMasterNotHijackingMajority failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#36556]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/713/console

```
REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=6092CAC83281214F \
  -Dtests.class=org.elasticsearch.discovery.MasterDisruptionIT \
  -Dtests.method="testStaleMasterNotHijackingMajority" \
  -Dtests.security.manager=true \
  -Dtests.locale=ko \
  -Dtests.timezone=America/Los_Angeles \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

I couldn't reproduce this in 20 attempts locally. Even after using the second seed (`@Seed("3F9487C7135AFE43")`) for the `testStaleMasterNotHijackingMajority` method.

```
java.lang.AssertionError: [node_t1] Each node should only record two master node transitions
Expected: <2>
     but: was <4>
	at __randomizedtesting.SeedInfo.seed([6092CAC83281214F:3F9487C7135AFE43]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.discovery.MasterDisruptionIT.testStaleMasterNotHijackingMajority(MasterDisruptionIT.java:254)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by DaveCTurner** [comment]
The test looks like it was on its way to succeeding: the stale master's attempt to hijack the majority was indeed rejected. But then everything just stopped for a couple of seconds. Here are two consecutive log messages:

```
  1> [2018-12-12T02:59:28,338][DEBUG][o.e.c.c.FollowersChecker ] [node_t2] FollowerChecker{discoveryNode={node_t1}{dwb5ZtKJQuKob831mBwHbQ}{UwM2TS65SCGUGxFjgmAeRA}{127.0.0.1}{127.0.0.1:41016}, failureCountSinceLastSu
  1> [2018-12-12T02:59:30,327][DEBUG][o.e.c.c.FollowersChecker ] [node_t1] FollowerChecker{discoveryNode={node_t0}{8_x-CYYnQZWpDuebKkt0dA}{d-sWRk6tRU2tuHuNiJX-Rg}{127.0.0.1}{127.0.0.1:58859}, failureCountSinceLastSu
```

The failure detector is set to be quite enthusiastic in `AbstractDisruptionTestCase`: a single 1-second pause is enough to trip it, so the inexplicable pause means the master fails and then recovers, resulting in 4 master transitions instead of 2.

I can't think of a good way to tell that this disruption to the master was external and not to do with the stale master. Maybe we should tone down the failure detector a bit if this is happening too much?

**Comment by DaveCTurner** [comment]
Chalking this failure up to some more widespread issues that CI was having that day with tests pausing and hitting timeouts, so there's no more action to take here.

**Comment by dimitris-athanasiou** [comment]
This has happened again today in the `7.0` branch: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+multijob-darwin-compatibility/4/consoleText

Same failure:

```
FAILURE 4.91s J1 | MasterDisruptionIT.testStaleMasterNotHijackingMajority <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: [node_t2] Each node should only record two master node transitions
   > Expected: a collection with size <2>
   >      but: collection size was <4>
   > 	at __randomizedtesting.SeedInfo.seed([3B285D3A59ED58:5F3D65521B823254]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.discovery.MasterDisruptionIT.testStaleMasterNotHijackingMajority(MasterDisruptionIT.java:176)
   > 	at java.lang.Thread.run(Thread.java:748)
```

Reproduce:

```
./gradlew :server:integTest -Dtests.seed=3B285D3A59ED58 -Dtests.class=org.elasticsearch.discovery.MasterDisruptionIT -Dtests.method="testStaleMasterNotHijackingMajority" -Dtests.security.manager=true -Dtests.locale=lt-LT -Dtests.timezone=Asia/Chongqing -Dcompiler.java=11 -Druntime.java=8
```

I'm reopening as might need more investigation @DaveCTurner

**Comment by DaveCTurner** [comment]
Thanks @dimitris-athanasiou. This failure was still a "CI just stopped doing stuff" issue but for just over a second which is kinda reasonable:

```
  1> [2019-02-08T23:33:14,039][TRACE][o.e.c.s.MasterService    ] [node_t2] will process [node-left[{node_t0}{GPBmjAIJQx6eIa5B5QBpDQ}{EB_YqBPyRViZdiGSh8n1Vw}{127.0.0.1}{127.0.0.1:64226} followers check retry count exceeded]]
  1> [2019-02-08T23:33:14,039][DEBUG][o.e.c.s.MasterService    ] [node_t2] processing [node-left[{node_t0}{GPBmjAIJQx6eIa5B5QBpDQ}{EB_YqBPyRViZdiGSh8n1Vw}{127.0.0.1}{127.0.0.1:64226} followers check retry count exceeded]]: execute
  1> [2019-02-08T23:33:14,048][WARN ][o.e.t.TransportService   ] [node_t2] Received response for a request that has timed out, sent [2006ms] ago, timed out [1123ms] ago, action [internal:coordination/fault_detection/leader_check], node [{node_t0}{GPBmjAIJQx6eIa5B5QBpDQ}{EB_YqBPyRViZdiGSh8n1Vw}{127.0.0.1}{127.0.0.1:6422
  1> [2019-02-08T23:33:14,049][TRACE][o.e.c.s.MasterService    ] [node_t2] cluster state updated, source [node-left[{node_t0}{GPBmjAIJQx6eIa5B5QBpDQ}{EB_YqBPyRViZdiGSh8n1Vw}{127.0.0.1}{127.0.0.1:64226} followers check retry count exceeded]]
  1> [2019-02-08T23:33:14,049][INFO ][o.e.c.s.MasterService    ] [node_t2] node-left[{node_t0}{GPBmjAIJQx6eIa5B5QBpDQ}{EB_YqBPyRViZdiGSh8n1Vw}{127.0.0.1}{127.0.0.1:64226} followers check retry count exceeded], term: 2, version: 6, reason: removed {{node_t0}{GPBmjAIJQx6eIa5B5QBpDQ}{EB_YqBPyRViZdiGSh8n1Vw}{127.0.0.1}{127
  1> [2019-02-08T23:33:14,049][DEBUG][o.e.c.s.MasterService    ] [node_t2] publishing cluster state version [6]
  1> org.elasticsearch.transport.RemoteTransportException: [node_t2][127.0.0.1:64227][internal:coordination/fault_detection/follower_check]
  1> [2019-02-08T23:33:14,088][DEBUG][o.e.c.c.PublicationTransportHandler] [node_t2] resending full cluster state to node {node_t0}{GPBmjAIJQx6eIa5B5QBpDQ}{EB_YqBPyRViZdiGSh8n1Vw}{127.0.0.1}{127.0.0.1:64226} reason RemoteTransportException[[node_t0][127.0.0.1:64226][internal:cluster/coordination/publish_state]]; nested
  1> [2019-02-08T23:33:14,088][DEBUG][o.e.c.c.PublicationTransportHandler] [node_t2] received diff cluster state version [5] with uuid [hW7jR-WDTQCQtBkGQdctwg], diff size [249]
  1> [2019-02-08T23:33:15,275][DEBUG][o.e.c.c.C.CoordinatorPublication] [node_t2] cancel: [Publication{term=2, version=6}] cancelled before committing (reason: timed out after 1s)
  1> [2019-02-08T23:33:15,276][DEBUG][o.e.c.c.C.CoordinatorPublication] [node_t2] onPossibleCompletion: [Publication{term=2, version=6}] commit failed
  1> [2019-02-08T23:33:15,276][DEBUG][o.e.c.c.C.CoordinatorPublication] [node_t2] publication ended unsuccessfully: Publication{term=2, version=6}
  1> [2019-02-08T23:33:15,276][DEBUG][o.e.c.c.Coordinator      ] [node_t2] Publication.onCompletion(false): coordinator becoming CANDIDATE in term 2 (was LEADER, lastKnownLeader was [Optional[{node_t2}{42gzLYX5Q66FoCoE5OUbqg}{Sf3osMk2QhSZVinkWvs09g}{127.0.0.1}{127.0.0.1:64227}]])
```

As this test is structured today we rely on that timeout being a bit sensitive, but I will think about some alternatives.

**Comment by droberts195** [comment]
The same test failed in the same way again in the macOS build like the previous one:

```
FAILURE 6.22s J1 | MasterDisruptionIT.testStaleMasterNotHijackingMajority <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: [node_t2] Each node should only record two master node transitions
   > Expected: a collection with size <2>
   >      but: collection size was <4>
   > 	at __randomizedtesting.SeedInfo.seed([C64F0105C19FC26:5362BD1F7DC2232A]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.discovery.MasterDisruptionIT.testStaleMasterNotHijackingMajority(MasterDisruptionIT.java:176)
   > 	at java.lang.Thread.run(Thread.java:748)
```

The build log is https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-darwin-compatibility/60/console

There's a question mark over that macOS CI worker, as every build on it fails for one reason or another.  Since the problem is not being observed in Linux builds I won't mute the test.

**Comment by original-brownbear** [comment]
@DaveCTurner I can reproduce this fairly reliably on OSX, running:

```
while ./gradlew :server:integTest -Dtests.seed=17D9B38A9300AD04 -Dtests.class=org.elasticsearch.discovery.MasterDisruptionIT -Dtests.method="testStaleMasterNotHijackingMajority" -Dtests.security.manager=true -Dtests.locale=et-EE -Dtests.timezone=Africa/Dar_es_Salaam -Dcompiler.java=11 -Druntime.java=8
```

(takes ~10 iterations on average to fail on `master`)
