### ISSUE TITLE
SQL: NULLIF doesn't work in GROUP BY and ORDER BY (scripting with NULLIF)

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#36631]
At the moment, anything using NULLIF scripting doesn't seem to work:
* `SELECT NULLIF(int0, int1) FROM calcs GROUP BY NULLIF(int0, int1)`
* `SELECT NULLIF(int0, int1) FROM calcs ORDER BY NULLIF(int0, int1)`

First one returns the following error:
```
Server error [Server sent bad type [search_phase_execution_exception]. Original type was [all shards failed]. [Failed to execute phase [query], all shards failed; shardFailures {[hxHMy92JSMybd1gNKH8S6w][calcs][0]: RemoteTransportException[[node-0][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: ScriptException[compile error]; nested: IllegalArgumentException[invalid sequence of tokens near ['{'].]; nested: NoViableAltException; }
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:293)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:133)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:254)
        at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:106)
```

And this is because the script generated for it looks like this: 

```
"script": {
    "source": "{sql}.nullif(InternalSqlScriptUtils.docValue(doc,params.v0),InternalSqlScriptUtils.docValue(doc,params.v1))",
    "lang": "painless",
    "params": {
        "v0": "int0",
        "v1": "int1"
    }
}
```

The second query (ORDER BY) returns this:

```
Server error [Server sent bad type [search_phase_execution_exception]. Original type was [all shards failed]. [Failed to execute phase [query], all shards failed; shardFailures {[hxHMy92JSMybd1gNKH8S6w][calcs][0]: RemoteTransportException[[node-0][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: ScriptException[compile error]; nested: ClassCastException[Cannot cast from [java.lang.Object] to [java.lang.Number].]; }
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:293)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:133)
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:254)
        at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:106)
        at org.elasticsearch.action.search.InitialSearchPhase.access$200(InitialSearchPhase.java:50)
```

And this is because the painless script method returns Object - `Object nullif(Object, Object)` - which should be converted to the Painless script output - of type `number` - and upon checking the two types Painless will complain as not being compatible. Probably the `nullif` Painless method should be re-defined as `def nullif(Object, Object)` which should automatically cast the values.

**Comment by matriv** [comment]
@astefan Nice catch, thank you!
