### ISSUE TITLE
Removing remote cluster that is in use by auto-follow pattern causes crash

### ISSUE THREAD

**Issue by jen-huang** [elastic/elasticsearch#36667]
I have a remote cluster which is in use by a CCR auto-follow pattern:

`GET _remote/info`:
```
{
  "prod2" : {
    "seeds" : [
      "127.0.0.1:9400"
    ],
    "connected" : true,
    "num_nodes_connected" : 1,
    "max_connections_per_cluster" : 3,
    "initial_connect_timeout" : "30s",
    "skip_unavailable" : false
  }
}
```

`GET _ccr/auto_follow`:
```
{
  "patterns" : [
    {
      "name" : "pattern1",
      "pattern" : {
        "remote_cluster" : "prod2",
        "leader_index_patterns" : [
          "test*"
        ],
        "follow_index_pattern" : "{{leader_index}}"
      }
    }
  ]
}
```

When I remove the remote cluster, ES throws repeated errors until it crashes with `ERROR ES exited with code 126`:

```
PUT _cluster/settings
{
  "persistent": {
    "cluster": {
      "remote": {
        "prod2": {
          "seeds" : null,
          "skip_unavailable": null
        }
      }
    }
  }
}
```

```
   │ info [o.e.x.c.a.AutoFollowCoordinator] [Jens-MacBook-Pro.local] failure occurred while fetching cluster state for auto follow pattern [pattern1]
   │      java.lang.IllegalArgumentException: unknown cluster alias [prod2]
   │      	at org.elasticsearch.transport.RemoteClusterService.getRemoteClusterClient(RemoteClusterService.java:495) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.client.node.NodeClient.getRemoteClusterClient(NodeClient.java:123) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:165) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.getRemoteClusterState(AutoFollowCoordinator.java:161) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:275) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.finalise(AutoFollowCoordinator.java:407) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.lambda$start$1(AutoFollowCoordinator.java:289) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.lambda$getRemoteClusterState$0(AutoFollowCoordinator.java:165) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:178) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.getRemoteClusterState(AutoFollowCoordinator.java:161) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:275) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.finalise(AutoFollowCoordinator.java:407) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.lambda$start$1(AutoFollowCoordinator.java:289) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.lambda$getRemoteClusterState$0(AutoFollowCoordinator.java:165) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:178) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.getRemoteClusterState(AutoFollowCoordinator.java:161) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:275) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.finalise(AutoFollowCoordinator.java:407) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.lambda$start$1(AutoFollowCoordinator.java:289) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.lambda$getRemoteClusterState$0(AutoFollowCoordinator.java:165) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:178) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.getRemoteClusterState(AutoFollowCoordinator.java:161) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:275) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.finalise(AutoFollowCoordinator.java:407) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.lambda$start$1(AutoFollowCoordinator.java:289) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.lambda$getRemoteClusterState$0(AutoFollowCoordinator.java:165) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:178) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.getRemoteClusterState(AutoFollowCoordinator.java:161) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:275) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.finalise(AutoFollowCoordinator.java:407) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.lambda$start$1(AutoFollowCoordinator.java:289) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.lambda$getRemoteClusterState$0(AutoFollowCoordinator.java:165) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:178) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.getRemoteClusterState(AutoFollowCoordinator.java:161) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:275) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.finalise(AutoFollowCoordinator.java:407) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.lambda$start$1(AutoFollowCoordinator.java:289) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.lambda$getRemoteClusterState$0(AutoFollowCoordinator.java:165) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:178) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.getRemoteClusterState(AutoFollowCoordinator.java:161) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:275) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.finalise(AutoFollowCoordinator.java:407) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.lambda$start$1(AutoFollowCoordinator.java:289) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.lambda$getRemoteClusterState$0(AutoFollowCoordinator.java:165) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:178) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.getRemoteClusterState(AutoFollowCoordinator.java:161) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:275) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.finalise(AutoFollowCoordinator.java:407) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch
   │ info .xpack.ccr.action.AutoFollowCoordinator$AutoFollower.lambda$start$1(AutoFollowCoordinator.java:289) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.lambda$getRemoteClusterState$0(AutoFollowCoordinator.java:165) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:178) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.getRemoteClusterState(AutoFollowCoordinator.java:161) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:275) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.finalise(AutoFollowCoordinator.java:407) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.lambda$start$1(AutoFollowCoordinator.java:289) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.lambda$getRemoteClusterState$0(AutoFollowCoordinator.java:165) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:178) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.getRemoteClusterState(AutoFollowCoordinator.java:161) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:275) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.finalise(AutoFollowCoordinator.java:407) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.lambda$start$1(AutoFollowCoordinator.java:289) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.lambda$getRemoteClusterState$0(AutoFollowCoordinator.java:165) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:178) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.getRemoteClusterState(AutoFollowCoordinator.java:161) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:275) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.finalise(AutoFollowCoordinator.java:407) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.lambda$start$1(AutoFollowCoordinator.java:289) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.lambda$getRemoteClusterState$0(AutoFollowCoordinator.java:165) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:178) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.getRemoteClusterState(AutoFollowCoordinator.java:161) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:275) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.finalise(AutoFollowCoordinator.java:407) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.lambda$start$1(AutoFollowCoordinator.java:289) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.lambda$getRemoteClusterState$0(AutoFollowCoordinator.java:165) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:178) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.getRemoteClusterState(AutoFollowCoordinator.java:161) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:275) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.finalise(AutoFollowCoordinator.java:407) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.lambda$start$1(AutoFollowCoordinator.java:289) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.lambda$getRemoteClusterState$0(AutoFollowCoordinator.java:165) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:178) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.getRemoteClusterState(AutoFollowCoordinator.java:161) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:275) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.finalise(AutoFollowCoordinator.java:407) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.lambda$start$1(AutoFollowCoordinator.java:289) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.lambda$getRemoteClusterState$0(AutoFollowCoordinator.java:165) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:178) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.getRemoteClusterState(AutoFollowCoordinator.java:161) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:275) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.finalise(AutoFollowCoordinator.java:407) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.lambda$start$1(AutoFollowCoordinator.java:289) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.lambda$getRemoteClusterState$0(AutoFollowCoordinator.java:165) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.CcrLicenseChecker.checkRemoteClusterLicenseAndFetchClusterState(CcrLicenseChecker.java:178) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.getRemoteClusterState(AutoFollowCoordinator.java:161) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.start(AutoFollowCoordinator.java:275) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.finalise(AutoFollowCoordinator.java:407) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$AutoFollower.lambda$start$1(AutoFollowCoordinator.java:289) [x-pack-ccr-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
   │      	at org.elasticsearch.xpack.ccr.action.AutoFollowCoordinator$2.lambda
```

**Comment by cjcenizal** [comment]
CC @jasontedor
