### ISSUE TITLE
[CI] JdbcSqlSpecIT datetime.testCurrentTimestampMinute failures

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#36695]
```
REPRODUCE WITH: ./gradlew :x-pack:plugin:sql:qa:single-node:integTestRunner -Dtests.seed=C2E3FE5C3E1B9D71 -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcSqlSpecIT -Dtests.method="test {datetime.testCurrentTimestampMinute}" -Dtests.security.manager=true -Dtests.locale=lv -Dtests.timezone=Pacific/Chatham -Dcompiler.java=11 -Druntime.java=8
```

This failed in a PR run with 
```
11:00:56 FAILURE 0.02s | JdbcSqlSpecIT.test {datetime.testCurrentTimestampMinute} <<< FAILURES!
11:00:56    > Throwable #1: java.lang.AssertionError: Different result for column [result], entry [1] expected:<45> but was:<0>
11:00:56    > 	at __randomizedtesting.SeedInfo.seed([C2E3FE5C3E1B9D71:4AB7C18690E7F089]:0)
11:00:56    > 	at org.elasticsearch.xpack.sql.qa.single_node.JdbcSqlSpecIT.datetime.testCurrentTimestampMinute(datetime.sql-spec:129)
11:00:56    > 	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.doAssertResultSetData(JdbcAssert.java:255)
11:00:56    > 	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSetData(JdbcAssert.java:180)
11:00:56    > 	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:83)
11:00:56    > 	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:67)
11:00:56    > 	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:56)
11:00:56    > 	at org.elasticsearch.xpack.sql.qa.jdbc.SpecBaseIntegrationTestCase.assertResults(SpecBaseIntegrationTestCase.java:127)
11:00:56    > 	at org.elasticsearch.xpack.sql.qa.jdbc.SqlSpecTestCase.doTest(SqlSpecTestCase.java:95)
11:00:56    > 	at org.elasticsearch.xpack.sql.qa.jdbc.SpecBaseIntegrationTestCase.test(SpecBaseIntegrationTestCase.java:88)
11:00:56    > 	at java.lang.Thread.run(Thread.java:748)
```

It reproduces locally also

**Comment by jkakavas** [comment]
Possibly relates to #36562

**Comment by costin** [comment]
I'll push a fix - this relates to the timezone difference between H2 and ES, the former always picks the local timezone and doesn't allow one to be specified creating some weird issues.

**Comment by pgomulka** [comment]
@costin can we also backport this to 6.x?

it just occured on 6.x intake
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/651/console

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:sql:qa:security:without-ssl:integTestRunner \
  -Dtests.seed=4622CF2F57404E46 \
  -Dtests.class=org.elasticsearch.xpack.sql.qa.security.JdbcSqlSpecIT \
  -Dtests.method="test {datetime.testCurrentTimestampMinute}" \
  -Dtests.security.manager=true \
  -Dtests.locale=it-CH \
  -Dtests.timezone=Iran \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

**Comment by astefan** [comment]
@pgomulka I'll do it

**Comment by astefan** [comment]
Done. With https://github.com/elastic/elasticsearch/commit/07b469e8ec0fe2cb7e79be2488462f45867546d4
