### ISSUE TITLE
[CI] LocalIndexFollowingIT.testFollowStatsApiFollowerIndexFiltering fails

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#36696]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.5+periodic/315/console
Does not reproduce for me locally
```
REPRODUCE WITH: ./gradlew :x-pack:plugin:ccr:internalClusterTest \
  -Dtests.seed=C146D25F2418328F \
  -Dtests.class=org.elasticsearch.xpack.ccr.LocalIndexFollowingIT \
  -Dtests.method="testFollowStatsApiFollowerIndexFiltering" \
  -Dtests.security.manager=true \
  -Dtests.locale=nn-NO \
  -Dtests.timezone=America/El_Salvador \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

```
 2> java.lang.IllegalArgumentException: no such remote cluster: local
  2> 	at __randomizedtesting.SeedInfo.seed([C146D25F2418328F]:0)
  2> 	at org.elasticsearch.transport.RemoteClusterService.ensureConnected(RemoteClusterService.java:352)
  2> 	at org.elasticsearch.transport.RemoteClusterAwareClient.doExecute(RemoteClusterAwareClient.java:49)
  2> 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:395)
  2> 	at org.elasticsearch.xpack.ccr.action.ShardFollowTasksExecutor$1.innerSendShardChangesRequest(ShardFollowTasksExecutor.java:244)
  2> 	at org.elasticsearch.xpack.ccr.action.ShardFollowNodeTask.sendShardChangesRequest(ShardFollowNodeTask.java:255)
  2> 	at org.elasticsearch.xpack.ccr.action.ShardFollowNodeTask.lambda$sendShardChangesRequest$3(ShardFollowNodeTask.java:278)
  2> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624)
  2> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  2> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  2> 	at java.lang.Thread.run(Thread.java:748)
```

It seems to be failing once in a while since 15th Dec 2018. 
https://build-stats.elastic.co/goto/b58444cfa8f318cbcc9055e35fef0793

**Comment by pgomulka** [comment]
also fails on https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/122/console

**Comment by martijnvg** [comment]
Hey @pgomulka this test should be fixed by the following commits that have been pushed this morning.

master: https://github.com/elastic/elasticsearch/commit/f27d2c292797c28ba73f27b5d32928d2c4a5ac2f
6.x: https://github.com/elastic/elasticsearch/commit/3a4fb891ba9abe6d1136d53bf90f763a95727e4d
6.5: https://github.com/elastic/elasticsearch/commit/405ff61677921f3e93169c874653c4bc8c2157b9

Please re-open if this test fails based on commits on or after the mentioned commits.
