### ISSUE TITLE
AssertionError in InternalEngine.canOptimizeAddDocument()

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#36732]
NB this failure was on 5.6.

Assertion error stack trace:

```
   > Caused by: java.lang.AssertionError: version: 1 type: EXTERNAL
   >    at __randomizedtesting.SeedInfo.seed([CF4D1445224A4474]:0)
   >    at org.elasticsearch.index.engine.InternalEngine.canOptimizeAddDocument(InternalEngine.java:424)
   >    at org.elasticsearch.index.engine.InternalEngine.planIndexingAsPrimary(InternalEngine.java:562)
   >    at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:493)
   >    at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:557)
   >    at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:546)
   >    at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:493)
   >    at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:145)
   >    at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:114)
   >    at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:69)
   >    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:975)
   >    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:944)
   >    at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:113)
   >    at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:345)
   >    at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:270)
   >    at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:924)
   >    at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:921)
   >    at org.elasticsearch.index.shard.IndexShardOperationsLock.acquire(IndexShardOperationsLock.java:151)
   >    at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationLock(IndexShard.java:1659)
   >    at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:933)
   >    at org.elasticsearch.action.support.replication.TransportReplicationAction.access$500(TransportReplicationAction.java:92)
   >    at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:291)
   >    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   >    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:266)
   >    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:248)
   >    at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
   >    at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:662)
   >    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:675)
   >    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   >    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   >    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   >    at java.lang.Thread.run(Thread.java:748)
```

Full log from the test here: [fail.txt.gz](https://github.com/elastic/elasticsearch/files/2687266/fail.txt.gz)

Internal CI run: https://internal-ci.elastic.co/job/elastic+x-pack-elasticsearch+5.6+multijob-windows-compatibility/508/consoleText

**Comment by ywelsch** [comment]
I think this is caused by the fact that index requests are mutable in 5.x (this was fixed by https://github.com/elastic/elasticsearch/pull/23038 in 6.0). What's happening is that an IndexRequest that was just indexed into the primary is mutated for replication, but if we then bubble up to the ReroutePhase (on same node) because of retry, we will be sending the mutated request to another primary, which makes things go *boom* like in the above assertion. Fixing this would require substantial changes to 5.x, which we can't make. I'm inclined to close this one as WontFix.
