### ISSUE TITLE
ScriptDocValuesMissingV7BehaviourTests fails on 6.x

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#36831]
All tests in ScriptDocValuesMissingV7BehaviourTests fail on 6.x. See for instance https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/706 .

```
11:05:11   2> REPRODUCE WITH: ./gradlew :server:unitTest -Dtests.seed=3C76A5057B432D71 -Dtests.class=org.elasticsearch.index.fielddata.ScriptDocValuesMissingV7BehaviourTests -Dtests.method="testExceptionForMissingValueLong" -Dtests.security.manager=true -Dtests.locale=be-BY -Dtests.timezone=Asia/Magadan -Dcompiler.java=11 -Druntime.java=8
11:05:11   2> REPRODUCE WITH: ./gradlew :server:unitTest -Dtests.seed=3C76A5057B432D71 -Dtests.class=org.elasticsearch.index.fielddata.ScriptDocValuesMissingV7BehaviourTests -Dtests.method="testExceptionForMissingValueLong" -Dtests.security.manager=true -Dtests.locale=be-BY -Dtests.timezone=Asia/Magadan -Dcompiler.java=11 -Druntime.java=8
11:05:11   2> REPRODUCE WITH: ./gradlew :server:unitTest -Dtests.seed=3C76A5057B432D71 -Dtests.class=org.elasticsearch.index.fielddata.ScriptDocValuesMissingV7BehaviourTests -Dtests.method="testExceptionForMissingValueDate" -Dtests.security.manager=true -Dtests.locale=be-BY -Dtests.timezone=Asia/Magadan -Dcompiler.java=11 -Druntime.java=8
11:05:11   2> REPRODUCE WITH: ./gradlew :server:unitTest -Dtests.seed=3C76A5057B432D71 -Dtests.class=org.elasticsearch.index.fielddata.ScriptDocValuesMissingV7BehaviourTests -Dtests.method="testExceptionForMissingValueDate" -Dtests.security.manager=true -Dtests.locale=be-BY -Dtests.timezone=Asia/Magadan -Dcompiler.java=11 -Druntime.java=8
11:05:11   2> REPRODUCE WITH: ./gradlew :server:unitTest -Dtests.seed=3C76A5057B432D71 -Dtests.class=org.elasticsearch.index.fielddata.ScriptDocValuesMissingV7BehaviourTests -Dtests.method="testFalseForMissingValueBoolean" -Dtests.security.manager=true -Dtests.locale=be-BY -Dtests.timezone=Asia/Magadan -Dcompiler.java=11 -Druntime.java=8
11:05:11   2> REPRODUCE WITH: ./gradlew :server:unitTest -Dtests.seed=3C76A5057B432D71 -Dtests.class=org.elasticsearch.index.fielddata.ScriptDocValuesMissingV7BehaviourTests -Dtests.method="testFalseForMissingValueBoolean" -Dtests.security.manager=true -Dtests.locale=be-BY -Dtests.timezone=Asia/Magadan -Dcompiler.java=11 -Druntime.java=8
11:05:11   2> REPRODUCE WITH: ./gradlew :server:unitTest -Dtests.seed=3C76A5057B432D71 -Dtests.class=org.elasticsearch.index.fielddata.ScriptDocValuesMissingV7BehaviourTests -Dtests.method="testNullForMissingValueGeo" -Dtests.security.manager=true -Dtests.locale=be-BY -Dtests.timezone=Asia/Magadan -Dcompiler.java=11 -Druntime.java=8
11:05:11   2> REPRODUCE WITH: ./gradlew :server:unitTest -Dtests.seed=3C76A5057B432D71 -Dtests.class=org.elasticsearch.index.fielddata.ScriptDocValuesMissingV7BehaviourTests -Dtests.method="testNullForMissingValueGeo" -Dtests.security.manager=true -Dtests.locale=be-BY -Dtests.timezone=Asia/Magadan -Dcompiler.java=11 -Druntime.java=8
```

```
11:05:11 Suite: org.elasticsearch.index.fielddata.ScriptDocValuesMissingV7BehaviourTests
11:05:11   1> [2018-12-19T21:05:11,629][INFO ][o.e.i.f.ScriptDocValuesMissingV7BehaviourTests] [testExceptionForMissingValueLong] before test
11:05:11   1> [2018-12-19T21:05:11,638][WARN ][o.e.d.i.f.S.Longs        ] [testExceptionForMissingValueLong] returning default values for missing document values is deprecated. Set system property '-Des.scripting.exception_for_missing_value=true' to make behaviour compatible with future major versions!
11:05:11 FAILURE 0.03s J5 | ScriptDocValuesMissingV7BehaviourTests.testExceptionForMissingValueLong <<< FAILURES!
11:05:11    > Throwable #1: junit.framework.AssertionFailedError: Expected exception IllegalStateException but no exception was thrown
11:05:11    > 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2697)
11:05:12    > 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2682)
11:05:12    > 	at org.elasticsearch.index.fielddata.ScriptDocValuesMissingV7BehaviourTests.testExceptionForMissingValueLong(ScriptDocValuesMissingV7BehaviourTests.java:44)
11:05:12    > 	at java.lang.Thread.run(Thread.java:748)Throwable #2: java.lang.AssertionError: unexpected warning headers expected null, but was:<[299 Elasticsearch-6.6.0-SNAPSHOT-Unknown "returning default values for missing document values is deprecated. Set system property '-Des.scripting.exception_for_missing_value=true' to make behaviour compatible with future major versions!" "Wed, 19 Dec 2018 10:05:11 GMT"]>
11:05:12    > 	at org.elasticsearch.test.ESTestCase.ensureNoWarnings(ESTestCase.java:378)
11:05:12    > 	at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:356)
11:05:12    > 	at java.lang.Thread.run(Thread.java:748)
11:05:12   1> [2018-12-19T21:05:11,655][INFO ][o.e.i.f.ScriptDocValuesMissingV7BehaviourTests] [testExceptionForMissingValueDate] before test
11:05:12   1> [2018-12-19T21:05:11,657][WARN ][o.e.d.i.f.S.Dates        ] [testExceptionForMissingValueDate] returning default values for missing document values is deprecated. Set system property '-Des.scripting.exception_for_missing_value=true' to make behaviour compatible with future major versions!
11:05:12 FAILURE 0.01s J5 | ScriptDocValuesMissingV7BehaviourTests.testExceptionForMissingValueDate <<< FAILURES!
11:05:12    > Throwable #1: junit.framework.AssertionFailedError: Expected exception IllegalStateException but no exception was thrown
11:05:12    > 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2697)
11:05:12    > 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2682)
11:05:12    > 	at org.elasticsearch.index.fielddata.ScriptDocValuesMissingV7BehaviourTests.testExceptionForMissingValueDate(ScriptDocValuesMissingV7BehaviourTests.java:60)
11:05:12    > 	at java.lang.Thread.run(Thread.java:748)Throwable #2: java.lang.AssertionError: unexpected warning headers expected null, but was:<[299 Elasticsearch-6.6.0-SNAPSHOT-Unknown "returning default values for missing document values is deprecated. Set system property '-Des.scripting.exception_for_missing_value=true' to make behaviour compatible with future major versions!" "Wed, 19 Dec 2018 10:05:11 GMT"]>
11:05:12    > 	at org.elasticsearch.test.ESTestCase.ensureNoWarnings(ESTestCase.java:378)
11:05:12    > 	at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:356)
11:05:12    > 	at java.lang.Thread.run(Thread.java:748)
11:05:12   1> [2018-12-19T21:05:11,665][INFO ][o.e.i.f.ScriptDocValuesMissingV7BehaviourTests] [testFalseForMissingValueBoolean] before test
11:05:12   1> [2018-12-19T21:05:11,668][WARN ][o.e.d.i.f.S.Booleans     ] [testFalseForMissingValueBoolean] returning default values for missing document values is deprecated. Set system property '-Des.scripting.exception_for_missing_value=true' to make behaviour compatible with future major versions!
11:05:12 FAILURE 0.01s J5 | ScriptDocValuesMissingV7BehaviourTests.testFalseForMissingValueBoolean <<< FAILURES!
11:05:12    > Throwable #1: junit.framework.AssertionFailedError: Expected exception IllegalStateException but no exception was thrown
11:05:12    > 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2697)
11:05:12    > 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2682)
11:05:12    > 	at org.elasticsearch.index.fielddata.ScriptDocValuesMissingV7BehaviourTests.testFalseForMissingValueBoolean(ScriptDocValuesMissingV7BehaviourTests.java:75)
11:05:12    > 	at java.lang.Thread.run(Thread.java:748)Throwable #2: java.lang.AssertionError: unexpected warning headers expected null, but was:<[299 Elasticsearch-6.6.0-SNAPSHOT-Unknown "returning default values for missing document values is deprecated. Set system property '-Des.scripting.exception_for_missing_value=true' to make behaviour compatible with future major versions!" "Wed, 19 Dec 2018 10:05:11 GMT"]>
11:05:12    > 	at org.elasticsearch.test.ESTestCase.ensureNoWarnings(ESTestCase.java:378)
11:05:12    > 	at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:356)
11:05:12    > 	at java.lang.Thread.run(Thread.java:748)
11:05:12   1> [2018-12-19T21:05:11,672][INFO ][o.e.i.f.ScriptDocValuesMissingV7BehaviourTests] [testNullForMissingValueGeo] before test
11:05:12   1> [2018-12-19T21:05:11,674][WARN ][o.e.d.i.f.S.GeoPoints    ] [testNullForMissingValueGeo] returning default values for missing document values is deprecated. Set system property '-Des.scripting.exception_for_missing_value=true' to make behaviour compatible with future major versions!
11:05:12 FAILURE 0.01s J5 | ScriptDocValuesMissingV7BehaviourTests.testNullForMissingValueGeo <<< FAILURES!
11:05:12    > Throwable #1: junit.framework.AssertionFailedError: Expected exception IllegalStateException but no exception was thrown
11:05:12    > 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2697)
11:05:12    > 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2682)
11:05:12    > 	at org.elasticsearch.index.fielddata.ScriptDocValuesMissingV7BehaviourTests.testNullForMissingValueGeo(ScriptDocValuesMissingV7BehaviourTests.java:85)
11:05:12    > 	at java.lang.Thread.run(Thread.java:748)Throwable #2: java.lang.AssertionError: unexpected warning headers expected null, but was:<[299 Elasticsearch-6.6.0-SNAPSHOT-Unknown "returning default values for missing document values is deprecated. Set system property '-Des.scripting.exception_for_missing_value=true' to make behaviour compatible with future major versions!" "Wed, 19 Dec 2018 10:05:11 GMT"]>
11:05:12    > 	at org.elasticsearch.test.ESTestCase.ensureNoWarnings(ESTestCase.java:378)
11:05:12    > 	at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:356)
11:05:12    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by javanna** [comment]
I muted these tests.

**Comment by atorok** [comment]
I missed a few updates when back porting the `unitTest` task. 
Corrected and un-muted the tests.
