### ISSUE TITLE
stackoverflowerror when bulk data or update task

### ISSUE THREAD

**Issue by FarmerLinT** [elastic/elasticsearch#36881]
**Describe the feature**:
our nodes are crashing caused by stackoverflowerror often，if happens when bulk data or update task。

**Elasticsearch version** (`bin/elasticsearch --version`):
 5.5.1

**Plugins installed**: 
elasticsearch-sql-5.5.1

**JVM version** (`java -version`):
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux 3.10.0.-229.el77.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64  x86_64  GNU/Linux 

**Description of the problem including expected versus actual behavior**:
our nodes are crashing caused by stackoverflowerror often，if happens when bulk data(datanode) or update task(master)。
It's on a cluster with 7 datanodes, 3700 indices,  9500 shards, 70 To of total data, 30 billions documents.

**Steps to reproduce**:
Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.It seems to happens on a bulk or updatetask request but I don't know which one.

**Provide logs (if relevant)**:

> datanode crash log:
[2018-12-20T13:33:11,525][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [datanode001] fatal error in thread [elasticsearch[datanode001][bulk][T#4]], exiting
java.lang.StackOverflowError: null
        at java.util.Spliterators$IteratorSpliterator.estimateSize(Spliterators.java:1821) ~[?:1.8.0_111]
        at java.util.Spliterator.getExactSizeIfKnown(Spliterator.java:408) ~[?:1.8.0_111]
        at java.util.stream.AbstractPipeline.exactOutputSizeIfKnown(AbstractPipeline.java:466) ~[?:1.8.0_111]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:544) ~[?:1.8.0_111]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:1.8.0_111]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438) ~[?:1.8.0_111]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:511) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:477) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.index.mapper.ObjectMapper.toXContent(ObjectMapper.java:525) ~[elasticsearch-5.5.1.jar:5.5.1]
		
		

> master crash log:
[2018-12-20T13:35:15,933][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [master001] fatal error in thread [elasticsearch[master001][clusterService#updateTask][T#1]], exiting
java.lang.StackOverflowError: null
        at com.fasterxml.jackson.core.util.InternCache.intern(InternCache.java:61) ~[jackson-core-2.8.6.jar:2.8.6]
        at com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer.addName(ByteQuadsCanonicalizer.java:813) ~[jackson-core-2.8.6.jar:2.8.6]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.addName(UTF8StreamJsonParser.java:2394) ~[jackson-core-2.8.6.jar:2.8.6]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.parseEscapedName(UTF8StreamJsonParser.java:2034) ~[jackson-core-2.8.6.jar:2.8.6]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.parseName(UTF8StreamJsonParser.java:1925) ~[jackson-core-2.8.6.jar:2.8.6]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseName(UTF8StreamJsonParser.java:1747) ~[jackson-core-2.8.6.jar:2.8.6]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:776) ~[jackson-core-2.8.6.jar:2.8.6]
        at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:55) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:310) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:317) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:317) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:317) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:317) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:317) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:317) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:317) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:317) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:317) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:317) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:317) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:317) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:317) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:317) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:317) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:317) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:317) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMap(AbstractXContentParser.java:317) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue(AbstractXContentParser.java:375) ~[elasticsearch-5.5.1.jar:5.5.1]

**Comment by markharwood** [comment]
First observation is that this is a lot of indices. If possible it would make sense to reduce this number.

Looks like the error is happening when attempting to update the cluster state which holds the mappings for all indices in the cluster. With dynamic mappings it is is possible that new documents can explode the set of fields associated with an index mapping although we have safeguards to limit the number of fields.
Would it be possible to get a copy of your [cluster state](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-state.html) somehow?
Or at least some indication of the size of this output.

**Comment by FarmerLinT** [comment]
Sorry, I can't give you a copy of our cluster state. The cluster state data size is 19MB.
 What do you mean by “some indication of the size of this output”. We use dynamic templates like that: "dynamic_templates":[{"str":{"match":"*","match_mapping_type":"string","mapping":{"ignore_above":"32766","index":"not_analyzed","type":"keyword"}}}].
StackOverflowError happens not only  update the cluster state, but also during bulk insert data to cluster.

**Comment by markharwood** [comment]
>What do you mean by “some indication of the size of this output”.

It's fine - I meant this:

>The cluster state data size is 19MB.

That's not the biggest I've heard of. 

>StackOverflowError happens not only update the cluster state, but also during bulk insert data to cluster.

A bulk insert of data can bring new fields which in turn will try update the cluster state. It's conceivable a "poison document" could have excessive nesting to produce an overflow e.g. 

    { foo1: { foo2:{ foo3:{ foo4: { foo5: {foo6: { foo7 ......

Does this seem likely? It will be hard to debug further without seeing the cluster state. Perhaps you can anonymise the field/index names by replacing them with numbers e.g a hash of the strings?

**Comment by andrershov** [comment]
No further feedback received. @FarmerLinT if you have the requested 
information please add it in a comment and we can look at re-opening 
this issue.
