### ISSUE TITLE
ES fails to retrieve snapshot from GCS

### ISSUE THREAD

**Issue by dmnfortytwo** [elastic/elasticsearch#36892]
**Elasticsearch version** (`bin/elasticsearch --version`):
`Version: 6.2.2, Build: 10b1edd/2018-02-16T19:01:30.685723Z, JVM: 1.8.0_181`

**Plugins installed**: 
```repository-gcs
- Plugin information:
Name: repository-gcs
Description: The GCS repository plugin adds Google Cloud Storage support for repositories.
Version: 6.2.2
Native Controller: false
Requires Keystore: false
Extended Plugins: []
 * Classname: org.elasticsearch.repositories.gcs.GoogleCloudStoragePlugin
```

**JVM version** (`java -version`):
```java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```
**OS version** (`uname -a` if on a Unix-like system):
`Linux elasticsearch-gce-be-10.domain 4.15.0-1018-gcp #19-Ubuntu SMP Thu Aug 16 13:38:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:
Sometimes elasticsearch fails to retrieve snapshot from gcs repo with first try. This puts whole cluster into red state and makes monitoring team nervous.

**Steps to reproduce**:
* configure repo in google cloud like this:
```# curl -sXGET localhost:9200/_snapshot/archive?pretty
{
  "archive" : {
    "type" : "gcs",
    "settings" : {
      "bucket" : "my_bucket",
      "client" : "elasticsearch",
      "max_restore_bytes_per_sec" : "160mb",
      "max_snapshot_bytes_per_sec" : "160mb"
    }
  }
}
```
* Add new large (40G+) indices to archive
* Try to restore a few one-by-one
* Restore will fail and you'll see an error like this (see below)
* Few minutes later restore will continue, but cluster health will stay red until it finishes
```
[2018-12-18T18:21:43,045][WARN ][o.e.c.a.s.ShardStateAction] [esmaster-gce-be-2] [team_logs--2018.09.04][1] received shard failed for shard id [[team_logs--2018.09.04][1]], allocation id [y2pCEt_[72/43121]
jEjGQ], primary term [0], message [failed recovery], failure [RecoveryFailedException[[team_logs--2018.09.04][1]: Recovery failed on {elasticsearch-gce-be-6}{aG29GP2tQd22_whltBTMdw}{S4KZvtUIRAuyMFIEsZMcpA}{10
.132.0.30}{10.132.0.30:9300}{rack_id=europe-west1-d}]; nested: IndexShardRecoveryException[failed recovery]; nested: IndexShardRestoreFailedException[restore failed]; nested: IndexShardRestoreFailedException[fa$
led to restore snapshot [all-2018.09.04/p3EzllljTjK0TRFbNTNhTg]]; nested: IndexShardRestoreFailedException[Failed to recover index]; nested: IOException[Connection closed prematurely: bytesRead = 16777216, Cont$
nt-Length = 44104724]; ]
org.elasticsearch.indices.recovery.RecoveryFailedException: [team_logs--2018.09.04][1]: Recovery failed on {elasticsearch-gce-be-6}{aG29GP2tQd22_whltBTMdw}{S4KZvtUIRAuyMFIEsZMcpA}{10.132.0.30}{10.132.0.30:93$
0}{rack_id=europe-west1-d}
        at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$7(IndexShard.java:2065) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573) ~[elasticsearch-6.2.2.jar:6.2.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: org.elasticsearch.index.shard.IndexShardRecoveryException: failed recovery
        at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:342) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.StoreRecovery.recoverFromRepository(StoreRecovery.java:275) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.IndexShard.restoreFromRepository(IndexShard.java:1613) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$7(IndexShard.java:2061) ~[elasticsearch-6.2.2.jar:6.2.2]
        ... 4 more
Caused by: org.elasticsearch.index.snapshots.IndexShardRestoreFailedException: restore failed
        at org.elasticsearch.index.shard.StoreRecovery.restore(StoreRecovery.java:463) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromRepository$5(StoreRecovery.java:277) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:300) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.StoreRecovery.recoverFromRepository(StoreRecovery.java:275) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.IndexShard.restoreFromRepository(IndexShard.java:1613) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$7(IndexShard.java:2061) ~[elasticsearch-6.2.2.jar:6.2.2]
        ... 4 more
Caused by: org.elasticsearch.index.snapshots.IndexShardRestoreFailedException: failed to restore snapshot [all-2018.09.04/p3EzllljTjK0TRFbNTNhTg]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.restoreShard(BlobStoreRepository.java:827) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.StoreRecovery.restore(StoreRecovery.java:448) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromRepository$5(StoreRecovery.java:277) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:300) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.StoreRecovery.recoverFromRepository(StoreRecovery.java:275) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.IndexShard.restoreFromRepository(IndexShard.java:1613) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$7(IndexShard.java:2061) ~[elasticsearch-6.2.2.jar:6.2.2]
        ... 4 more
Caused by: org.elasticsearch.index.snapshots.IndexShardRestoreFailedException: Failed to recover index
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository$RestoreContext.restore(BlobStoreRepository.java:1518) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.restoreShard(BlobStoreRepository.java:825) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.StoreRecovery.restore(StoreRecovery.java:448) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromRepository$5(StoreRecovery.java:277) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:300) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.StoreRecovery.recoverFromRepository(StoreRecovery.java:275) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.IndexShard.restoreFromRepository(IndexShard.java:1613) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$7(IndexShard.java:2061) ~[elasticsearch-6.2.2.jar:6.2.2]
        ... 4 more
Caused by: java.io.IOException: Connection closed prematurely: bytesRead = 16777216, Content-Length = 44104724
        at com.google.api.client.http.javanet.NetHttpResponse$SizeValidatingInputStream.throwIfFalseEOF(NetHttpResponse.java:202) ~[?:?]
        at com.google.api.client.http.javanet.NetHttpResponse$SizeValidatingInputStream.read(NetHttpResponse.java:171) ~[?:?]
        at org.elasticsearch.index.snapshots.blobstore.SlicedInputStream.read(SlicedInputStream.java:92) ~[elasticsearch-6.2.2.jar:6.2.2]
        at java.io.FilterInputStream.read(FilterInputStream.java:133) ~[?:1.8.0_181]
        at org.elasticsearch.index.snapshots.blobstore.RateLimitingInputStream.read(RateLimitingInputStream.java:69) ~[elasticsearch-6.2.2.jar:6.2.2]
        at java.io.FilterInputStream.read(FilterInputStream.java:107) ~[?:1.8.0_181]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository$RestoreContext.restoreFile(BlobStoreRepository.java:1572) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository$RestoreContext.restore(BlobStoreRepository.java:1515) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.restoreShard(BlobStoreRepository.java:825) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.StoreRecovery.restore(StoreRecovery.java:448) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromRepository$5(StoreRecovery.java:277) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:300) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.StoreRecovery.recoverFromRepository(StoreRecovery.java:275) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.IndexShard.restoreFromRepository(IndexShard.java:1613) ~[elasticsearch-6.2.2.jar:6.2.2]
        at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$7(IndexShard.java:2061) ~[elasticsearch-6.2.2.jar:6.2.2]
        ... 4 more
```

**Comment by ywelsch** [comment]
@dmnfortytwo Can you check if the same issue exists in newer versions of ES? This sounds more like a Google Cloud Service problem than a problem with the ES GCS plugin.

**Comment by dmnfortytwo** [comment]
>Can you check if the same issue exists in newer versions of ES?

I'd say no, sorry. Upgrading cluster 'just to test' will cost us too much in terms of human resources at the moment.

>This sounds more like a Google Cloud Service problem than a problem with the ES GCS plugin.

I've got in touch with Google Enterprise Support and they believe that the problem is not on their side.

As for me, plugin shouldn't fail on error, just because nothing is guaranteed to be alive in cloud.

**Comment by dmnfortytwo** [comment]
How can I check what version of Google API library is used by plugin in my setup?

**Comment by ywelsch** [comment]
For [ES 6.2.2, it's 1.23.0.](https://github.com/elastic/elasticsearch/blob/v6.2.2/plugins/repository-gcs/build.gradle#L26)

**Comment by dmnfortytwo** [comment]
How can I use specific version of google lib? I need at least 1.52
