### ISSUE TITLE
TransportTasksActionTests testTaskLevelActionFailures

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#36906]
does NOT reproduce for me on master:

 ./gradlew :server:unitTest -Dtests.seed=13A82671D40F53CA -Dtests.class=org.elasticsearch.action.admin.cluster.node.tasks.TransportTasksActionTests -Dtests.method="testTaskLevelActionFailures" -Dtests.security.manager=true -Dtests.locale=el-CY -Dtests.timezone=Antarctica/Macquarie -Dcompiler.java=11 -Druntime.java=8

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/930/console

Stacktrace
```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([13A82671D40F53CA:31D593D34BEB3791]:0)
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.elasticsearch.action.admin.cluster.node.tasks.TransportTasksActionTests.startBlockingTestNodesAction(TransportTasksActionTests.java:294)
	at org.elasticsearch.action.admin.cluster.node.tasks.TransportTasksActionTests.startBlockingTestNodesAction(TransportTasksActionTests.java:257)
	at org.elasticsearch.action.admin.cluster.node.tasks.TransportTasksActionTests.startBlockingTestNodesAction(TransportTasksActionTests.java:251)
	at org.elasticsearch.action.admin.cluster.node.tasks.TransportTasksActionTests.testTaskLevelActionFailures(TransportTasksActionTests.java:570)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

**Comment by original-brownbear** [comment]
I haven't seen this happen again ever since it was reported more than 2 weeks ago.
Now that #36976 prevented this test from leaking memory I was able to run multiple 10k of iterations here and couldn't make it fail locally either => closing.
