### ISSUE TITLE
SQL: Enhance error message for PERCENTILE and PERCENTILE_RANK functions when a field is used as second parameter

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#36903]
```
sql> select percentile(salary, languages) from test_emp;
Server error [Server encountered an error [Cannot determine value for languages{f}#509]. [SqlIllegalArgumentException[Cannot determine value for languages{f}#509]
        at org.elasticsearch.xpack.sql.expression.Foldables.valueOf(Foldables.java:25)
        at org.elasticsearch.xpack.sql.expression.Foldables.doubleValueOf(Foldables.java:48)
        at org.elasticsearch.xpack.sql.expression.function.aggregate.Percentile.innerName(Percentile.java:64)
        at org.elasticsearch.xpack.sql.expression.function.aggregate.InnerAggregate.<init>(InnerAggregate.java:32)
        at org.elasticsearch.xpack.sql.expression.function.aggregate.InnerAggregate.<init>(InnerAggregate.java:25)
        at org.elasticsearch.xpack.sql.optimizer.Optimizer$ReplaceAggsWithPercentiles.rule(Optimizer.java:553)
        at org.elasticsearch.xpack.sql.optimizer.Optimizer$ReplaceAggsWithPercentiles.lambda$apply$2(Optimizer.java:527)
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:182)
```

**Comment by matriv** [comment]
This is actually a valid limitation, those aggregates operate on a bucket of grouped values with a constant percentage argument. It doesn't make sense to have the percentage from a field as this might change between rows. I've changed the label to enhancement and rephrased the title to enhance the error message.
