### ISSUE TITLE
UpdateMappingIntegrationIT testUpdateMappingConcurrently failure

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#36916]
Test failed on master:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/939/console

Does NOT reproduce for me on master:
```
REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=621A6D79BEBF07 \
  -Dtests.class=org.elasticsearch.indices.mapping.UpdateMappingIntegrationIT \
  -Dtests.method="testUpdateMappingConcurrently" \
  -Dtests.security.manager=true \
  -Dtests.locale=lt \
  -Dtests.timezone=Pacific/Honolulu \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Relevant stack trace:
```
20:14:40    2> java.lang.AssertionError:
20:14:40    2> Expected: <true>

20:14:40    2>      but: was <false>

20:14:40    2>  at __randomizedtesting.SeedInfo.seed([621A6D79BEBF07]:0)
20:14:40    2>  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
20:14:40    2>  at org.junit.Assert.assertThat(Assert.java:956)
20:14:40    2>  at org.junit.Assert.assertThat(Assert.java:923)
20:14:40    2>  at org.elasticsearch.indices.mapping.UpdateMappingIntegrationIT.lambda$testUpdateMappingConcurrently$0(UpdateMappingIntegrationIT.java:229)
```

**Comment by ywelsch** [comment]
Closing this as we're missing recent logs. Please reopen if there is a recent occurrence with logs.
