### ISSUE TITLE
java.lang.IllegalArgumentException: unknown setting [cloud.discovery.zen.hosts_provider] please check that any required plugins are installed, or check  the breaking changes documentation for removed settings

### ISSUE THREAD

**Issue by shaunc869** [elastic/elasticsearch#36925]
**Elasticsearch version**: 6.5

**Plugins installed**: [discovery-gce]

**JVM version** (`java -version`):1.8.0_181

**OS version** (`uname -a` if on a Unix-like system): SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

After installing the plugin with the recommended config of:

cloud:
  gce:
      project_id: myprojectid
      zone: us-central1-a
discovery:
      zen.hosts_provider: gce

it's supposed to boot fine, but instead, I get the error in the logs:

java.lang.IllegalArgumentException: unknown setting [cloud.discovery.zen.hosts_provider] please check that any required plugins are installed, or check  the breaking changes documentation for removed settings

**Steps to reproduce**:

 1. Install elasticsearch
 2. Install gce-discovery plugin.
 3. Update config
4. Restart

**Provide logs (if relevant)**:

[2018-12-21T02:21:53,321][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [wy6-zJd] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [cloud.discovery.zen.hosts_provider] please check that any required plugins are installed, or check t
he breaking changes documentation for removed settings
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.5.1.jar:6.5.1]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.5.1.jar:6.5.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.5.1.jar:6.5.1]

**Comment by tvernum** [comment]
This appears to be a problem with your configuration file. It looks like you have used incorrect indentation while copying from the documentation.

If you would like to work through this problem, could you please ask question on our [discussion forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support.
This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help you if you need further assistance.
As such, I hope you don't mind that I close this.

Thank you.
