### ISSUE TITLE
Refering to a result from a GROUP BY subquery returns 

### ISSUE THREAD

**Issue by eariasp** [elastic/elasticsearch#36939]
Installation and machine:
ES 6.4.3 installation in a ES aws hosted instance

Description:
An a query using a subquery involving a GROUP BY this error is launched:

```
Server error [Server encountered an error []. [Failed to execute phase [fetch], 
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:293)
	at org.elasticsearch.action.search.FetchSearchPhase$1.onFailure(FetchSearchPhase.java:91)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:708)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: ScriptException[compile error]; nested: IllegalArgumentException[Variable [doc] is not defined.];
	at org.elasticsearch.painless.PainlessScriptEngine.convertToScriptException(PainlessScriptEngine.java:510)
	at org.elasticsearch.painless.PainlessScriptEngine.compile(PainlessScriptEngine.java:430)
	at org.elasticsearch.painless.PainlessScriptEngine.compile(PainlessScriptEngine.java:170)
	at org.elasticsearch.script.ScriptService.compile(ScriptService.java:334)
	at org.elasticsearch.search.aggregations.pipeline.bucketselector.BucketSelectorPipelineAggregator.reduce(BucketSelectorPipelineAggregator.java:86)
	at org.elasticsearch.search.aggregations.InternalAggregation.reduce(InternalAggregation.java:138)
	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:90)
	at org.elasticsearch.action.search.SearchPhaseController.reduceAggs(SearchPhaseController.java:525)
	at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:502)
	at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:419)
	at org.elasticsearch.action.search.SearchPhaseController$1.reduce(SearchPhaseController.java:738)
	at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:101)
	at org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:44)
	at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:86)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	... 5 more
Caused by: java.lang.IllegalArgumentException: Variable [doc] is not defined.
	at org.elasticsearch.painless.PainlessScript$Script.compile(InternalSqlScriptUtils.nullSafeFilter(InternalSqlScriptUtils.eq(InternalSqlScriptUtils.docValue(doc,params.v0),params.v1)):97)
	at org.elasticsearch.painless.Locals.getVariable(Locals.java:179)
	at org.elasticsearch.painless.Locals.getVariable(Locals.java:177)
	at org.elasticsearch.painless.node.EVariable.analyze(EVariable.java:54)
	at org.elasticsearch.painless.node.PSubCallInvoke.analyze(PSubCallInvoke.java:61)
	at org.elasticsearch.painless.node.PCallInvoke.analyze(PCallInvoke.java:89)
	at org.elasticsearch.painless.node.PSubCallInvoke.analyze(PSubCallInvoke.java:61)
	at org.elasticsearch.painless.node.PCallInvoke.analyze(PCallInvoke.java:89)
	at org.elasticsearch.painless.node.PSubCallInvoke.analyze(PSubCallInvoke.java:61)
	at org.elasticsearch.painless.node.PCallInvoke.analyze(PCallInvoke.java:89)
	at org.elasticsearch.painless.node.SExpression.analyze(SExpression.java:54)
	at org.elasticsearch.painless.node.SSource.analyze(SSource.java:227)
	at org.elasticsearch.painless.node.SSource.analyze(SSource.java:185)
	at org.elasticsearch.painless.Compiler.compile(Compiler.java:225)
	at org.elasticsearch.painless.PainlessScriptEngine$5.run(PainlessScriptEngine.java:423)
	at org.elasticsearch.painless.PainlessScriptEngine$5.run(PainlessScriptEngine.java:419)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.painless.PainlessScriptEngine.compile(PainlessScriptEngine.java:419)
	... 19 more
]]
```

Steps to reproduce:

 1. load data:

```
curl -X DELETE "localhost:9200/test_groupby_subquery"
curl -X PUT "localhost:9200/test_groupby_subquery"
curl -X PUT "localhost:9200/test_groupby_subquery/_mapping/_doc" -H 'Content-Type: application/json' -d'
{
"properties": {
"id": { "type": "long" } 
}
}
'

curl -X PUT "localhost:9200/test_groupby_subquery/_doc/1" -H 'Content-Type: application/json' -d' { "id": "1"} '
curl -X PUT "localhost:9200/test_groupby_subquery/_doc/2" -H 'Content-Type: application/json' -d' { "id": "2"} '
curl -X PUT "localhost:9200/test_groupby_subquery/_doc/3" -H 'Content-Type: application/json' -d' { "id": "3"} '
curl -X PUT "localhost:9200/test_groupby_subquery/_doc/4" -H 'Content-Type: application/json' -d' { "id": "4"} '
curl -X PUT "localhost:9200/test_groupby_subquery/_doc/5" -H 'Content-Type: application/json' -d' { "id": "5"} '
curl -X PUT "localhost:9200/test_groupby_subquery/_doc/6" -H 'Content-Type: application/json' -d' { "id": "6"} '
curl -X PUT "localhost:9200/test_groupby_subquery/_doc/7" -H 'Content-Type: application/json' -d' { "id": "7"} '
curl -X PUT "localhost:9200/test_groupby_subquery/_doc/8" -H 'Content-Type: application/json' -d' { "id": "8"} '
curl -X PUT "localhost:9200/test_groupby_subquery/_doc/9" -H 'Content-Type: application/json' -d' { "id": "9"} '
curl -X PUT "localhost:9200/test_groupby_subquery/_doc/10" -H 'Content-Type: application/json' -d' { "id": "10"} '
```

 2. in a ES sql client execute:
`select * from (select id from test_groupby_subquery GROUP by id) where id = 3;`

This should return a row with the value 3.

**Comment by gwbrown** [comment]
I'm not sure whether or not to tag this as a bug because this may be a case that's not supported.  Can someone from @elastic/es-sql take a look?

**Comment by astefan** [comment]
Had a look at this scenario and, yes, it's unsupported. The issue here is that `where id=3` should act on the value of a grouping (`GROUP BY id`) and this should, in fact, be a `HAVING` condition (condition applied on the result of an aggregation). Thinking about this purely from Elasticsearch point of view, a valid query would involve a [`terms` aggregation  and, with some limitations, a filter applied to it](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values_3).
But then, doing `SELECT * FROM (SELECT id FROM test_groupby_subquery GROUP BY id) WHERE X`, means that the `WHERE` part should support all types of conditions that wouldn't work with the `terms` agg [limitations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values_3) I mentioned above.
