### ISSUE TITLE
[CI] xpack.sql.qa.single_node.JdbcResultSetIT.testGettingBooleanValues

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#36932]
6.6

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:sql:qa:single-node:integTestRunner \
  -Dtests.seed=5A3B907794ADADE2 \
  -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT \
  -Dtests.method="testGettingBooleanValues" \
  -Dtests.security.manager=true \
  -Dtests.locale=mt-MT \
  -Dtests.timezone=Etc/GMT-12 \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

```
org.junit.ComparisonFailure: expected:<...83938-12-08T17:49:09[]Z] of type [DATE] to...> but was:<...83938-12-08T17:49:09[.000]Z] of type [DATE] to...>
	at __randomizedtesting.SeedInfo.seed([5A3B907794ADADE2:100DC6AD1604A45F]:0)
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.lambda$testGettingBooleanValues$116(ResultSetTestCase.java:781)
	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1249)
	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.testGettingBooleanValues(ResultSetTestCase.java:763)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

```
Suite: org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT
  1> [2018-12-22T00:02:29,920][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testValidGetObjectCalls] before test
  1> [2018-12-22T00:02:29,922][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testValidGetObjectCalls] initializing REST clients against [http://[::1]:43743]
  1> [2018-12-22T00:02:30,160][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testValidGetObjectCalls] after test
  1> [2018-12-22T00:02:30,168][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingDateWithoutCalendar] before test
  2> REPRODUCE WITH: ./gradlew :x-pack:plugin:sql:qa:single-node:integTestRunner -Dtests.seed=5A3B907794ADADE2 -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT -Dtests.method="testGettingBooleanValues" -Dtests.security.manager=true -Dtests.locale=mt-MT -Dtests.timezone=Etc/GMT-12 -Dcompiler.java=11 -Druntime.java=8
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+6.6+multijob-unix-compatibility/os/debian/x-pack/plugin/sql/qa/single-node/build/testrun/integTestRunner/J0/temp/org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT_5A3B907794ADADE2-001
  1> [2018-12-22T00:02:30,355][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingDateWithoutCalendar] after test
  1> [2018-12-22T00:02:30,363][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testNoInfiniteRecursiveGetObjectCalls] before test
  1> [2018-12-22T00:02:30,512][WARN ][o.e.c.RestClient         ] [[I/O dispatcher 225]] request [PUT http://[::1]:43743/library/doc/1?refresh=true] returned 1 warnings: [299 Elasticsearch-6.6.0-SNAPSHOT-3f18092 "the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you must manage this on the create index request or with an index template" "Fri, 21 Dec 2018 12:02:30 GMT"]
  1> [2018-12-22T00:02:30,597][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testNoInfiniteRecursiveGetObjectCalls] after test
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=1422, maxMBSortInHeap=7.840843277915525, sim=RandomSimilarity(queryNorm=false): {}, locale=mt-MT, timezone=Etc/GMT-12
  2> NOTE: Linux 4.9.0-8-amd64 amd64/Oracle Corporation 1.8.0_192 (64-bit)/cpus=16,threads=1,free=485614552,total=516947968
  2> NOTE: All tests run in this JVM: [CliFetchSizeIT, JdbcSimpleExampleIT, CliErrorsIT, CliSelectIT, JdbcFetchSizeIT, JdbcConnectionIT, CliShowIT, JdbcResultSetIT]
  1> [2018-12-22T00:02:30,607][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidDoubleWithCasting] before test
  1> [2018-12-22T00:02:30,774][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidDoubleWithCasting] after test
  1> [2018-12-22T00:02:30,783][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingTimestampWithoutCalendar] before test
  1> [2018-12-22T00:02:30,986][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingTimestampWithoutCalendar] after test
  1> [2018-12-22T00:02:30,996][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidByteWithoutCasting] before test
  1> [2018-12-22T00:02:31,191][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidByteWithoutCasting] after test
  1> [2018-12-22T00:02:31,198][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidLongWithCasting] before test
  1> [2018-12-22T00:02:31,365][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidLongWithCasting] after test
  1> [2018-12-22T00:02:31,381][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidIntegerWithoutCasting] before test
  1> [2018-12-22T00:02:31,567][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidIntegerWithoutCasting] after test
  1> [2018-12-22T00:02:31,577][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testUnsupportedUpdateMethods] before test
  1> [2018-12-22T00:02:31,729][WARN ][o.e.c.RestClient         ] [[I/O dispatcher 225]] request [PUT http://[::1]:43743/test/doc/1?refresh=true] returned 1 warnings: [299 Elasticsearch-6.6.0-SNAPSHOT-3f18092 "the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you must manage this on the create index request or with an index template" "Fri, 21 Dec 2018 12:02:31 GMT"]
  1> [2018-12-22T00:02:31,820][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testUnsupportedUpdateMethods] after test
  1> [2018-12-22T00:02:31,826][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingInvalidByte] before test
  1> [2018-12-22T00:02:32,018][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingInvalidByte] after test
  1> [2018-12-22T00:02:32,027][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingTimeWithoutCalendar] before test
  1> [2018-12-22T00:02:32,210][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingTimeWithoutCalendar] after test
  1> [2018-12-22T00:02:32,223][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidIntegerWithCasting] before test
  1> [2018-12-22T00:02:32,382][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidIntegerWithCasting] after test
  1> [2018-12-22T00:02:32,392][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testUnsupportedGetMethods] before test
  1> [2018-12-22T00:02:32,536][WARN ][o.e.c.RestClient         ] [[I/O dispatcher 225]] request [PUT http://[::1]:43743/test/doc/1?refresh=true] returned 1 warnings: [299 Elasticsearch-6.6.0-SNAPSHOT-3f18092 "the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you must manage this on the create index request or with an index template" "Fri, 21 Dec 2018 12:02:32 GMT"]
  1> [2018-12-22T00:02:32,615][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testUnsupportedGetMethods] after test
  1> [2018-12-22T00:02:32,623][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidLongWithoutCasting] before test
  1> [2018-12-22T00:02:32,794][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidLongWithoutCasting] after test
  1> [2018-12-22T00:02:32,801][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidShortWithoutCasting] before test
  1> [2018-12-22T00:02:32,974][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidShortWithoutCasting] after test
  1> [2018-12-22T00:02:32,981][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidByteWithCasting] before test
  1> [2018-12-22T00:02:33,136][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidByteWithCasting] after test
  1> [2018-12-22T00:02:33,145][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidFloatWithoutCasting] before test
  1> [2018-12-22T00:02:33,311][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidFloatWithoutCasting] after test
  1> [2018-12-22T00:02:33,320][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingTimeWithCalendar] before test
  1> [2018-12-22T00:02:33,514][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingTimeWithCalendar] after test
  1> [2018-12-22T00:02:33,522][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingTimestampWithCalendar] before test
  1> [2018-12-22T00:02:33,715][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingTimestampWithCalendar] after test
  1> [2018-12-22T00:02:33,721][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidFloatWithCasting] before test
  1> [2018-12-22T00:02:33,879][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidFloatWithCasting] after test
  1> [2018-12-22T00:02:33,887][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingInvalidDouble] before test
  1> [2018-12-22T00:02:34,060][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingInvalidDouble] after test
  1> [2018-12-22T00:02:34,067][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingInvalidLong] before test
  1> [2018-12-22T00:02:34,243][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingInvalidLong] after test
  1> [2018-12-22T00:02:34,251][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingInvalidShort] before test
  1> [2018-12-22T00:02:34,420][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingInvalidShort] after test
  1> [2018-12-22T00:02:34,427][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingInvalidFloat] before test
  1> [2018-12-22T00:02:34,599][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingInvalidFloat] after test
  1> [2018-12-22T00:02:34,606][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingDateWithCalendar] before test
  1> [2018-12-22T00:02:34,788][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingDateWithCalendar] after test
  1> [2018-12-22T00:02:34,795][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingBooleanValues] before test
  1> [2018-12-22T00:02:35,014][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingBooleanValues] after test
FAILURE 0.24s | JdbcResultSetIT.testGettingBooleanValues <<< FAILURES!
   > Throwable #1: org.junit.ComparisonFailure: expected:<...83938-12-08T17:49:09[]Z] of type [DATE] to...> but was:<...83938-12-08T17:49:09[.000]Z] of type [DATE] to...>
   > 	at __randomizedtesting.SeedInfo.seed([5A3B907794ADADE2:100DC6AD1604A45F]:0)
   > 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.lambda$testGettingBooleanValues$116(ResultSetTestCase.java:781)
   > 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1249)
   > 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.testGettingBooleanValues(ResultSetTestCase.java:763)
   > 	at java.lang.Thread.run(Thread.java:748)
  1> [2018-12-22T00:02:35,031][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidShortWithCasting] before test
  1> [2018-12-22T00:02:35,179][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidShortWithCasting] after test
  1> [2018-12-22T00:02:35,186][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidDoubleWithoutCasting] before test
  1> [2018-12-22T00:02:35,364][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingValidDoubleWithoutCasting] after test
  1> [2018-12-22T00:02:35,371][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingInvalidInteger] before test
  1> [2018-12-22T00:02:35,539][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingInvalidInteger] after test
Completed [8/19] in 5.65s, 29 tests, 1 failure <<< FAILURES!
```

**Comment by astefan** [comment]
master (7.0.0): https://github.com/elastic/elasticsearch/commit/9a6c61015c1ac91e5ba7e826f3d63d2ecd9263bd
6.x (6.7.0): https://github.com/elastic/elasticsearch/commit/fb4bd3b16eff35983e67356af88610decb018c4e
6.6 (6.6.0): https://github.com/elastic/elasticsearch/commit/fe7914aa170d59260d91b903067ee8d7c914dce3
