### ISSUE TITLE
Realm cache.ttl set to -1 throws error.

### ISSUE THREAD

**Issue by A-Hall** [elastic/elasticsearch#36951]
**Elasticsearch version** (`bin/elasticsearch --version`): at least 6.4.2 - 6.5.4

**JVM version** (`java -version`):
```
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system): CentOS Linux release 7.5.1804

**Description of the problem including expected versus actual behavior**: Setting realm `cache.ttl` to `-1` throws an error.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Set cache.ttl to -1:
```xpack:
  security:
    authc:
      realms:
        ldap1:
          type: ldap
          order: 0
          url: "ldap://ldap:389"
          bind_dn: "cn=read-only-admin,dc=example,dc=com"
          bind_password: password
          user_search:
            base_dn: "dc=example,dc=com"
          group_search:
            base_dn: "dc=example,dc=com"
          unmapped_groups_as_roles: false
	  cache.ttl: -1
```

 2. Node continuously throws error below.

**Provide logs (if relevant)**:

```
[2018-12-21T16:20:20,235][ERROR][o.e.x.m.c.c.ClusterStatsCollector] [MiT-O0s] collector [cluster_stats] failed to collect data
java.lang.NullPointerException: null
        at org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealm.getCacheSize(CachingUsernamePasswordRealm.java:190) ~[?:?]
        at org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealm.lambda$usageStats$4(CachingUsernamePasswordRealm.java:184) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.xpack.core.security.authc.Realm.usageStats(Realm.java:141) ~[?:?]
        at org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealm.usageStats(CachingUsernamePasswordRealm.java:183) ~[?:?]
        at org.elasticsearch.xpack.security.authc.ldap.LdapRealm.usageStats(LdapRealm.java:164) ~[?:?]
        at org.elasticsearch.xpack.security.authc.Realms.usageStats(Realms.java:242) ~[?:?]
        at org.elasticsearch.xpack.security.SecurityFeatureSet.usage(SecurityFeatureSet.java:142) ~[?:?]
        at org.elasticsearch.xpack.core.action.TransportXPackUsageAction.lambda$masterOperation$0(TransportXPackUsageAction.java:72) ~[?:?]
        at org.elasticsearch.xpack.core.common.IteratingActionListener.run(IteratingActionListener.java:81) ~[?:?]
        at org.elasticsearch.xpack.core.action.TransportXPackUsageAction.masterOperation(TransportXPackUsageAction.java:94) ~[?:?]
        at org.elasticsearch.xpack.core.action.TransportXPackUsageAction.masterOperation(TransportXPackUsageAction.java:32) ~[?:?]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:88) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:174) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) ~[elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.4.2.jar:6.4.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by jasontedor** [comment]
Thanks for reporting @A-Hall.
