### ISSUE TITLE
 Data too large, data for [<reused_arrays>] would be [3844551592/3.5gb

### ISSUE THREAD

**Issue by ithjz** [elastic/elasticsearch#36987]
org.elasticsearch.transport.RemoteTransportException: [node-1][192.168.7.128:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.common.breaker.CircuitBreakingException: [request] Data too large, data for [<reused_arrays>] would be [3844551592/3.5gb], which is larger than the limit of [3844551475/3.5gb]
	at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.circuitBreak(ChildMemoryCircuitBreaker.java:98) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.limit(ChildMemoryCircuitBreaker.java:170) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.addEstimateBytesAndMaybeBreak(ChildMemoryCircuitBreaker.java:123) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.common.util.BigArrays.adjustBreaker(BigArrays.java:407) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.common.util.BigArrays.validate(BigArrays.java:455) ~[elasticsearch-6.5.4.jar:6.5.4]

**Comment by atorok** [comment]
This post does not include very much information that might be helpful to start
to try and answer it. Questions like this often go unanswered. You can make it
more likely to receive an answer by adding more information that you think
would be helpful to readers, such as:

- details of the investigations that you have already performed
- things you have already tried when looking for a solution
- requests made to Elasticsearch and their responses (properly formatted using
  the </> button)
- log messages, including any stack traces (also properly formatted using </>)

It would be great if you could update your post to solve this.

**Comment by danielmitterdorfer** [comment]
[Circuit breakers](https://www.elastic.co/guide/en/elasticsearch/reference/current/circuit-breaker.html) in Elasticsearch should prevent that an overly expensive request takes down a node due to an OutOfMemoryError. What you are seeing here is completely expected behavior. It just means that the request is considered too large and hence it is rejected. Please see the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/circuit-breaker.html) for more details and please stop by in our [discussion forum](https://discuss.elastic.co/c/elasticsearch) if you have more questions. :)
