### ISSUE TITLE
Docs PR builds fail on old branches

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#37002]
In #36999 I tried to open a docs PR against the 6.3 branch, but this failed the `oss-distro-docs` check for various reasons like the following:

```
  1> [2018-12-27T08:07:24,619][INFO ][o.e.s.DocsClientYamlTestSuiteIT] [test {yaml=reference/licensing/get-trial-status/line_40}]: before test
  1> [2018-12-27T08:07:24,624][INFO ][o.e.s.DocsClientYamlTestSuiteIT] Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "error" : {
  1>         "root_cause" : [
  1>           {
  1>             "type" : "index_not_found_exception",
  1>             "reason" : "no such index",
  1>             "resource.type" : "index_expression",
  1>             "resource.id" : "_xpack",
  1>             "index_uuid" : "_na_",
  1>             "index" : "_xpack",
  1>             "stack_trace" : "[_xpack] IndexNotFoundException[no such index]
  1> 	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:182)
  1> 	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:121)
  1> 	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteSingleIndex(IndexNameExpressionResolver.java:251)
  1> 	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.<init>(TransportSingleShardAction.java:146)
  1> 	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.<init>(TransportSingleShardAction.java:123)
  1> 	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction.doExecute(TransportSingleShardAction.java:95)
  1> 	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction.doExecute(TransportSingleShardAction.java:59)
  1> 	at org.elasticsearch.action.support.TransportAction.doExecute(TransportAction.java:143)
  1> 	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:167)
  1> 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:139)
  1> 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:81)
  1> 	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:87)
  1> 	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:76)
  1> 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:405)
  1> 	at org.elasticsearch.client.support.AbstractClient.get(AbstractClient.java:497)
  1> 	at org.elasticsearch.rest.action.document.RestGetAction.lambda$prepareRequest$0(RestGetAction.java:81)
  1> 	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:97)
  1> 	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:239)
  1> 	at org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:335)
  1> 	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:173)
  1> 	at org.elasticsearch.http.netty4.Netty4HttpServerTransport.dispatchRequest(Netty4HttpServerTransport.java:503)
  2> REPRODUCE WITH: ./gradlew :docs:integTestRunner -Dtests.seed=D7B0CE006562FFB6 -Dtests.class=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT -Dtests.method="test {yaml=reference/licensing/get-trial-status/line_40}" -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=America/Argentina/Ushuaia -Dtests.distribution=oss-zip
```

Not sure if this is to be expected or not, and if it is expected I'm also not sure how (or even whether) we should make changes to old docs like this.

**Comment by nik9000** [comment]
We do tend to backport changes to docs where possible, yeah. I don't expect this but I remember we had some issues around waiting for the xpack index that we ended up solving later on. Since the OSS doc tests nuke every index there are a lot of times when this might happen.

Given that it is in an old branch if it doesn't happen on every build I'd be ok with retrying the build. It isn't great, but I don't think we'd backport whatever fixes this because it is in the server and not in the tests. I think.

**Comment by DaveCTurner** [comment]
It seems fairly consistently broken.

Opening a PR against 6.3 is a somewhat strange thing to do, granted, but it doesn't make sense to apply #36999 to anything later.

**Comment by danielmitterdorfer** [comment]
I'm closing this one for now as the `docs-check` builds on the 6.0, 6.1, 6.2 and 6.3 branches were all green as far as history reaches back (the whole previous month) except for [one failure on the 6.0 branch](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.0+docs-check/8/console) which failed due an unrelated network issue:

```
10:56:59 > Could not resolve all files for configuration ':benchmarks:classpath'.
10:56:59    > Could not resolve commons-io:commons-io:2.4.
10:56:59      Required by:
10:56:59          project :benchmarks > com.github.jengelman.gradle.plugins:shadow:1.2.4
10:56:59       > Could not resolve commons-io:commons-io:2.4.
10:56:59          > Could not get resource 'https://plugins.gradle.org/m2/commons-io/commons-io/2.4/commons-io-2.4.pom'.
10:56:59             > Could not HEAD 'https://plugins.gradle.org/m2/commons-io/commons-io/2.4/commons-io-2.4.pom'.
10:56:59                > Read timed out
```
