### ISSUE TITLE
LdapSessionFactoryTests fails on master

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#37013]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8fips,nodes=virtual&&linux/145/

```
07:02:56   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:security:unitTest -Dtests.seed=2AC4384D3530AF3 -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.LdapSessionFactoryTests -Dtests.method="testBindWithReadTimeout" -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Africa/Harare -Dcompiler.java=11 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password
07:02:56   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:security:unitTest -Dtests.seed=2AC4384D3530AF3 -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.LdapSessionFactoryTests -Dtests.method="testBindWithReadTimeout" -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Africa/Harare -Dcompiler.java=11 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password
07:02:56   1> [2018-12-28T08:02:55,729][INFO ][o.e.x.s.a.l.LdapSessionFactoryTests] [testBindWithReadTimeout] after test
07:02:56 ERROR   0.10s J5 | LdapSessionFactoryTests.testBindWithReadTimeout <<< FAILURES!
07:02:56    > Throwable #1: LDAPException(resultCode=82 (local error), errorMessage='An error occurred while attempting to create an SSL client socket factory:  KeyManagementException(FIPS mode: only SunJSSE TrustManagers may be used), ldapSDKVersion=4.0.8, revision=28812')
07:02:56    > 	at com.unboundid.ldap.listener.InMemoryListenerConfig.createLDAPSConfig(InMemoryListenerConfig.java:346)
07:02:56    > 	at com.unboundid.ldap.listener.InMemoryListenerConfig.createLDAPSConfig(InMemoryListenerConfig.java:258)
07:02:56   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:security:unitTest -Dtests.seed=2AC4384D3530AF3 -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.LdapSessionFactoryTests -Dtests.method="testBindWithTemplates" -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Africa/Harare -Dcompiler.java=11 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password
07:02:56   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:security:unitTest -Dtests.seed=2AC4384D3530AF3 -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.LdapSessionFactoryTests -Dtests.method="testBindWithTemplates" -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Africa/Harare -Dcompiler.java=11 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password
07:02:56   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:security:unitTest -Dtests.seed=2AC4384D3530AF3 -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.LdapSessionFactoryTests -Dtests.method="testGroupLookupBase" -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Africa/Harare -Dcompiler.java=11 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password
07:02:56    > 	at org.elasticsearch.xpack.security.authc.ldap.support.LdapTestCase.startLdap(LdapTestCase.java:90)
07:02:56   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:security:unitTest -Dtests.seed=2AC4384D3530AF3 -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.LdapSessionFactoryTests -Dtests.method="testGroupLookupBase" -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Africa/Harare -Dcompiler.java=11 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password
07:02:56   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:security:unitTest -Dtests.seed=2AC4384D3530AF3 -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.LdapSessionFactoryTests -Dtests.method="testGroupLookupSubtree" -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Africa/Harare -Dcompiler.java=11 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password
07:02:56   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:security:unitTest -Dtests.seed=2AC4384D3530AF3 -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.LdapSessionFactoryTests -Dtests.method="testGroupLookupSubtree" -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Africa/Harare -Dcompiler.java=11 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password
07:02:56   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:security:unitTest -Dtests.seed=2AC4384D3530AF3 -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.LdapSessionFactoryTests -Dtests.method="testBindWithBogusTemplates" -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Africa/Harare -Dcompiler.java=11 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password
07:02:56    > 	at java.lang.Thread.run(Thread.java:748)
07:02:56   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:security:unitTest -Dtests.seed=2AC4384D3530AF3 -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.LdapSessionFactoryTests -Dtests.method="testBindWithBogusTemplates" -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Africa/Harare -Dcompiler.java=11 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password
07:02:56    > Caused by: java.security.KeyManagementException: FIPS mode: only SunJSSE TrustManagers may be used
07:02:56   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:security:unitTest -Dtests.seed=2AC4384D3530AF3 -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.LdapSessionFactoryTests -Dtests.method="testSslTrustIsReloaded" -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Africa/Harare -Dcompiler.java=11 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password
07:02:56    > 	at sun.security.ssl.SSLContextImpl.chooseTrustManager(SSLContextImpl.java:120)
07:02:56    > 	at sun.security.ssl.SSLContextImpl.engineInit(SSLContextImpl.java:83)
07:02:56    > 	at javax.net.ssl.SSLContext.init(SSLContext.java:282)
07:02:56   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:security:unitTest -Dtests.seed=2AC4384D3530AF3 -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.LdapSessionFactoryTests -Dtests.method="testSslTrustIsReloaded" -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Africa/Harare -Dcompiler.java=11 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password
07:02:56    > 	at com.unboundid.util.ssl.SSLUtil.createSSLContext(SSLUtil.java:394)
07:02:56    > 	at com.unboundid.util.ssl.SSLUtil.createSSLContext(SSLUtil.java:367)
07:02:56    > 	at com.unboundid.util.ssl.SSLUtil.createSSLSocketFactory(SSLUtil.java:443)
07:02:56   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:security:unitTest -Dtests.seed=2AC4384D3530AF3 -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.LdapSessionFactoryTests -Dtests.method="testGroupLookupOneLevel" -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Africa/Harare -Dcompiler.java=11 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password
07:02:56   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:security:unitTest -Dtests.seed=2AC4384D3530AF3 -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.LdapSessionFactoryTests -Dtests.method="testGroupLookupOneLevel" -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Africa/Harare -Dcompiler.java=11 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password
```

```
07:02:56 ERROR   0.06s J5 | LdapSessionFactoryTests.testBindWithTemplates <<< FAILURES!
07:02:56    > Throwable #1: LDAPException(resultCode=82 (local error), errorMessage='An error occurred while attempting to create an SSL client socket factory:  KeyManagementException(FIPS mode: only SunJSSE TrustManagers may be used), ldapSDKVersion=4.0.8, revision=28812')
07:02:56    > 	at com.unboundid.ldap.listener.InMemoryListenerConfig.createLDAPSConfig(InMemoryListenerConfig.java:346)
07:02:56    > 	at com.unboundid.ldap.listener.InMemoryListenerConfig.createLDAPSConfig(InMemoryListenerConfig.java:258)
07:02:56    > 	at org.elasticsearch.xpack.security.authc.ldap.support.LdapTestCase.startLdap(LdapTestCase.java:90)
07:02:56    > 	at java.lang.Thread.run(Thread.java:748)
07:02:56    > Caused by: java.security.KeyManagementException: FIPS mode: only SunJSSE TrustManagers may be used
07:02:56    > 	at sun.security.ssl.SSLContextImpl.chooseTrustManager(SSLContextImpl.java:120)
07:02:56    > 	at sun.security.ssl.SSLContextImpl.engineInit(SSLContextImpl.java:83)
07:02:56    > 	at javax.net.ssl.SSLContext.init(SSLContext.java:282)
07:02:56    > 	at com.unboundid.util.ssl.SSLUtil.createSSLContext(SSLUtil.java:394)
07:02:56    > 	at com.unboundid.util.ssl.SSLUtil.createSSLContext(SSLUtil.java:367)
07:02:56    > 	at com.unboundid.util.ssl.SSLUtil.createSSLSocketFactory(SSLUtil.java:443)
07:02:56    > 	at com.unboundid.ldap.listener.InMemoryListenerConfig.createLDAPSConfig(InMemoryListenerConfig.java:341)
07:02:56    > 	... 38 moreThrowable #2: java.lang.NullPointerException
07:02:56    > 	at org.elasticsearch.xpack.security.authc.ldap.support.LdapTestCase.stopLdap(LdapTestCase.java:114)
07:02:56    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jkakavas** [comment]
Probably related to https://github.com/elastic/elasticsearch/pull/36937. It's already late for Tim, I'll take a look shortly and address this or at least mute the offending tests

**Comment by javanna** [comment]
thanks @jkakavas !!
