### ISSUE TITLE
LocalIndexFollowingIT#testRemoveRemoteConnection fails on master

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#37014]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/145/console

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:ccr:internalClusterTest -Dtests.seed=9D13A2A7D33D5F51 -Dtests.class=org.elasticsearch.xpack.ccr.LocalIndexFollowingIT -Dtests.method="testRemoveRemoteConnection" -Dtests.security.manager=true -Dtests.locale=zh-Hans -Dtests.timezone=Australia/Lindeman -Dcompiler.java=11 -Druntime.java=11
```

```
06:49:29 ERROR   20.1s J5 | LocalIndexFollowingIT.testRemoveRemoteConnection <<< FAILURES!
06:49:29    > Throwable #1: java.lang.AssertionError: 
06:49:29    > Expected: <1L>
06:49:29    >      but: was <-1L>
06:49:29    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
06:49:29    > 	at org.elasticsearch.xpack.ccr.LocalIndexFollowingIT.lambda$testRemoveRemoteConnection$5(LocalIndexFollowingIT.java:136)
06:49:29    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:847)
06:49:29    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:821)
06:49:29    > 	at org.elasticsearch.xpack.ccr.LocalIndexFollowingIT.testRemoveRemoteConnection(LocalIndexFollowingIT.java:127)
06:49:29    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
06:49:29    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
06:49:29    > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:49:29    > 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
06:49:29    > 	at java.base/java.lang.Thread.run(Thread.java:834)
06:49:29    > 	Suppressed: java.lang.AssertionError: 
06:49:29    > Expected: <2L>
06:49:29    >      but: was <1L>
06:49:29    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
06:49:29    > 		at org.elasticsearch.xpack.ccr.LocalIndexFollowingIT.lambda$testRemoveRemoteConnection$5(LocalIndexFollowingIT.java:129)
06:49:29    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
06:49:29    > 		... 38 more
06:49:29    > 	Suppressed: java.lang.AssertionError: 
06:49:29    > Expected: <2L>
06:49:29    >      but: was <1L>
06:49:29    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
06:49:29    > 		at org.elasticsearch.xpack.ccr.LocalIndexFollowingIT.lambda$testRemoveRemoteConnection$5(LocalIndexFollowingIT.java:129)
06:49:29    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
06:49:29    > 		... 38 more
06:49:29    > 	Suppressed: java.lang.AssertionError: 
06:49:29    > Expected: <2L>
06:49:29    >      but: was <1L>
06:49:29    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
06:49:29    > 		at org.elasticsearch.xpack.ccr.LocalIndexFollowingIT.lambda$testRemoveRemoteConnection$5(LocalIndexFollowingIT.java:129)
06:49:29    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
06:49:29    > 		... 38 more
06:49:29    > 	Suppressed: java.lang.AssertionError: 
06:49:29    > Expected: <2L>
06:49:29    >      but: was <1L>
06:49:29    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
06:49:29    > 		at org.elasticsearch.xpack.ccr.LocalIndexFollowingIT.lambda$testRemoveRemoteConnection$5(LocalIndexFollowingIT.java:129)
06:49:29    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
06:49:29    > 		... 38 more
06:49:29    > 	Suppressed: java.lang.AssertionError: 
06:49:29    > Expected: <2L>
06:49:29    >      but: was <1L>
06:49:29    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
06:49:29    > 		at org.elasticsearch.xpack.ccr.LocalIndexFollowingIT.lambda$testRemoveRemoteConnection$5(LocalIndexFollowingIT.java:129)
06:49:29    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
06:49:29    > 		... 38 more
06:49:29    > 	Suppressed: java.lang.AssertionError: 
06:49:29    > Expected: <2L>
06:49:29    >      but: was <1L>
06:49:29    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
06:49:29    > 		at org.elasticsearch.xpack.ccr.LocalIndexFollowingIT.lambda$testRemoveRemoteConnection$5(LocalIndexFollowingIT.java:129)
06:49:29    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
06:49:29    > 		... 38 more
06:49:29    > 	Suppressed: java.lang.AssertionError: 
06:49:29    > Expected: <2L>
06:49:29    >      but: was <1L>
06:49:29    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
06:49:29    > 		at org.elasticsearch.xpack.ccr.LocalIndexFollowingIT.lambda$testRemoveRemoteConnection$5(LocalIndexFollowingIT.java:129)
06:49:29    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
06:49:29    > 		... 38 more
06:49:29    > 	Suppressed: java.lang.AssertionError: 
06:49:29    > Expected: <1L>
06:49:29    >      but: was <-1L>
06:49:29    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
06:49:29    > 		at org.elasticsearch.xpack.ccr.LocalIndexFollowingIT.lambda$testRemoveRemoteConnection$5(LocalIndexFollowingIT.java:136)
06:49:29    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
06:49:29    > 		... 38 more
06:49:29    > 	Suppressed: java.lang.AssertionError: 
06:49:29    > Expected: <1L>
06:49:29    >      but: was <-1L>
06:49:29    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
06:49:29    > 		at org.elasticsearch.xpack.ccr.LocalIndexFollowingIT.lambda$testRemoveRemoteConnection$5(LocalIndexFollowingIT.java:136)
06:49:29    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
06:49:29    > 		... 38 more
06:49:29    > 	Suppressed: java.lang.AssertionError: 
06:49:29    > Expected: <1L>
06:49:29    >      but: was <-1L>
06:49:29    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
06:49:29    > 		at org.elasticsearch.xpack.ccr.LocalIndexFollowingIT.lambda$testRemoveRemoteConnection$5(LocalIndexFollowingIT.java:136)
06:49:29    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
06:49:29    > 		... 38 more
06:49:29    > 	Suppressed: java.lang.AssertionError: 
06:49:29    > Expected: <1L>
06:49:29    >      but: was <-1L>
06:49:29    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
06:49:29    > 		at org.elasticsearch.xpack.ccr.LocalIndexFollowingIT.lambda$testRemoveRemoteConnection$5(LocalIndexFollowingIT.java:136)
06:49:29    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
06:49:29    > 		... 38 more
06:49:29    > 	Suppressed: java.lang.AssertionError: 
06:49:29    > Expected: <1L>
06:49:29    >      but: was <-1L>
06:49:29    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
06:49:29    > 		at org.elasticsearch.xpack.ccr.LocalIndexFollowingIT.lambda$testRemoveRemoteConnection$5(LocalIndexFollowingIT.java:136)
06:49:29    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
06:49:29    > 		... 38 more
06:49:29    > 	Suppressed: java.lang.AssertionError: 
06:49:29    > Expected: <1L>
06:49:29    >      but: was <-1L>
06:49:29    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
06:49:29    > 		at org.elasticsearch.xpack.ccr.LocalIndexFollowingIT.lambda$testRemoveRemoteConnection$5(LocalIndexFollowingIT.java:136)
06:49:29    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
06:49:29    > 		... 38 moreThrowable #2: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=48, name=elasticsearch[node_s_0][ccr][T#8], state=RUNNABLE, group=TGRP-LocalIndexFollowingIT]
06:49:29    > Caused by: java.lang.IllegalArgumentException: no such remote cluster: local
06:49:29    > 	at __randomizedtesting.SeedInfo.seed([9D13A2A7D33D5F51]:0)
06:49:29    > 	at org.elasticsearch.transport.RemoteClusterService.getRemoteClusterConnection(RemoteClusterService.java:378)
06:49:29    > 	at org.elasticsearch.transport.RemoteClusterService.ensureConnected(RemoteClusterService.java:368)
06:49:29    > 	at org.elasticsearch.transport.RemoteClusterAwareClient.doExecute(RemoteClusterAwareClient.java:48)
06:49:29    > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:393)
06:49:29    > 	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:682)
06:49:29    > 	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.state(AbstractClient.java:712)
06:49:29    > 	at org.elasticsearch.xpack.ccr.action.ShardFollowTasksExecutor$1.innerUpdateMapping(ShardFollowTasksExecutor.java:127)
06:49:29    > 	at org.elasticsearch.xpack.ccr.action.ShardFollowNodeTask.updateMapping(ShardFollowNodeTask.java:409)
06:49:29    > 	at org.elasticsearch.xpack.ccr.action.ShardFollowNodeTask.lambda$updateMapping$12(ShardFollowNodeTask.java:409)
06:49:29    > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660)
06:49:29    > 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
06:49:29    > 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
06:49:29    > 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by javanna** [comment]
another occurrence, this time on 6.6: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8fips,nodes=virtual&&linux/18/console

**Comment by javanna** [comment]
I muted this test on master, 6.x and 6.6.

**Comment by martijnvg** [comment]
The test failed, because the follower shard didn't have the expected global checkpoint. This test changes the remote cluster connection that running shard follow tasks are using. Previously (at the time the test failed) shard follow tasks could fail with a non retryable error, which causes the shard follow tasks to stop. Recently a change was merged that makes shard follow tasks more resilient against remote cluster connections changes. I think that this will fix this test too, I will re-enable this test soon.
