### ISSUE TITLE
SimpleNetty4TransportTests.testTransportProfilesWithPortAndHost fails

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#37019]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.5+multijob-unix-compatibility/os=sles/128/console

```
REPRODUCE WITH: ./gradlew :modules:transport-netty4:test -Dtests.seed=7ECABC3D0F1BD511 -Dtests.class=org.elasticsearch.transport.netty4.SimpleNetty4TransportTests -Dtests.method="testTransportProfilesWithPortAndHost" -Dtests.security.manager=true -Dtests.locale=zh-HK -Dtests.timezone=SystemV/PST8PDT -Dcompiler.java=11 -Druntime.java=8
```

```
16:10:42 ERROR   31.1s J3 | SimpleNetty4TransportTests.testTransportProfilesWithPortAndHost <<< FAILURES!
16:10:42    > Throwable #1: ConnectTransportException[[TS_B][127.0.0.1:32933] connect_timeout[30s]]
16:10:42    > 	at __randomizedtesting.SeedInfo.seed([7ECABC3D0F1BD511:5626532DDCFC1E0A]:0)
16:10:42    > 	at org.elasticsearch.transport.TcpChannel.awaitConnected(TcpChannel.java:163)
16:10:42    > 	at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:454)
16:10:42    > 	at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:117)
16:10:42    > 	at org.elasticsearch.test.transport.StubbableTransport.openConnection(StubbableTransport.java:135)
16:10:42    > 	at org.elasticsearch.transport.ConnectionManager.internalOpenConnection(ConnectionManager.java:237)
16:10:42    > 	at org.elasticsearch.transport.ConnectionManager.connectToNode(ConnectionManager.java:119)
16:10:42    > 	at org.elasticsearch.test.transport.StubbableConnectionManager.connectToNode(StubbableConnectionManager.java:114)
16:10:42    > 	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:369)
16:10:42    > 	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:356)
16:10:42    > 	at org.elasticsearch.transport.AbstractSimpleTransportTestCase.setUp(AbstractSimpleTransportTestCase.java:155)
16:10:42    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by original-brownbear** [comment]
This looks to be an incredibly slow test run.
I see multiple tests taking 30s+  in the logs, when the same suite takes ~4s overall on my local machine (all individual tests are sub-second):

```
HEARTBEAT J3 PID(22060@elasticsearch-ci-immutable-sles-12-1546007215663452139): 2018-12-28T15:09:54, stalled for 30.7s at: SimpleNetty4TransportTests.testRegisterHandlerTwice
[ant:junit4] JVM J0: stderr was not empty, see: /var/lib/jenkins/workspace/elastic+elasticsearch+6.5+multijob-unix-compatibility/os/sles/modules/transport-netty4/build/testrun/test/temp/junit4-J0-20181228_150754_57414314479677210177470.syserr
HEARTBEAT J3 PID(22060@elasticsearch-ci-immutable-sles-12-1546007215663452139): 2018-12-28T15:10:08, stalled for 11.2s at: SimpleNetty4TransportTests.testTimeoutSendExceptionWithDelayedResponse
HEARTBEAT J3 PID(22060@elasticsearch-ci-immutable-sles-12-1546007215663452139): 2018-12-28T15:10:18, stalled for 21.2s at: SimpleNetty4TransportTests.testTimeoutSendExceptionWithDelayedResponse
HEARTBEAT J3 PID(22060@elasticsearch-ci-immutable-sles-12-1546007215663452139): 2018-12-28T15:10:28, stalled for 31.2s at: SimpleNetty4TransportTests.testTimeoutSendExceptionWithDelayedResponse
HEARTBEAT J3 PID(22060@elasticsearch-ci-immutable-sles-12-1546007215663452139): 2018-12-28T15:10:38, stalled for 41.2s at: SimpleNetty4TransportTests.testTimeoutSendExceptionWithDelayedResponse
```

It seems we had issues with very slow SLES runs before here https://github.com/elastic/elasticsearch/issues/30295#issuecomment-387149428 ...  maybe this is just an infra issue?
