### ISSUE TITLE
DateMathExpressionResolverTests fails on master

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#37037]
Three tests have started failing over the weekend, I believe it has to do with the end of the year approaching. Not sure if the failures may be related to datetime changes. They happen only in master:

```
org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests testExpression_CustomFormat
org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests testExpression_CustomTimeZoneInIndexName
org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests testExpression_EscapeDateFormat
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/447/console

They easily reproduce:

```
06:36:03   2> REPRODUCE WITH: ./gradlew :server:unitTest -Dtests.seed=57AEC52CB025A748 -Dtests.class=org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests -Dtests.method="testExpression_EscapeDateFormat" -Dtests.security.manager=true -Dtests.locale=da-DK -Dtests.timezone=Indian/Mayotte -Dcompiler.java=11 -Druntime.java=8
06:36:03   2> REPRODUCE WITH: ./gradlew :server:unitTest -Dtests.seed=57AEC52CB025A748 -Dtests.class=org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests -Dtests.method="testExpression_CustomFormat" -Dtests.security.manager=true -Dtests.locale=da-DK -Dtests.timezone=Indian/Mayotte -Dcompiler.java=11 -Druntime.java=8
06:36:03   2> REPRODUCE WITH: ./gradlew :server:unitTest -Dtests.seed=57AEC52CB025A748 -Dtests.class=org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests -Dtests.method="testExpression_CustomTimeZoneInIndexName" -Dtests.security.manager=true -Dtests.locale=da-DK -Dtests.timezone=Indian/Mayotte -Dcompiler.java=11 -Druntime.java=8
```

```
06:36:03 FAILURE 0.02s J5 | DateMathExpressionResolverTests.testExpression_EscapeDateFormat <<< FAILURES!
06:36:03    > Throwable #1: java.lang.AssertionError: 
06:36:03    > Expected: ".marvel-{year}2018"
06:36:03    >      but: was ".marvel-{year}2019"
06:36:03    > 	at __randomizedtesting.SeedInfo.seed([57AEC52CB025A748:C795FA0EBA4BCE4B]:0)
06:36:03    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
06:36:03    > 	at org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests.testExpression_EscapeDateFormat(DateMathExpressionResolverTests.java:111)
06:36:03 FAILURE 0.00s J5 | DateMathExpressionResolverTests.testExpression_CustomFormat <<< FAILURES!
06:36:03    > Throwable #1: java.lang.AssertionError: 
06:36:03    > Expected: ".marvel-2018.12.30"
06:36:03    >      but: was ".marvel-2019.12.30"
06:36:03    > 	at __randomizedtesting.SeedInfo.seed([57AEC52CB025A748:6DA2B3B50CD96D0C]:0)
06:36:03    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
06:36:03    > 	at org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests.testExpression_CustomFormat(DateMathExpressionResolverTests.java:97)
06:36:03 FAILURE 0.01s J5 | DateMathExpressionResolverTests.testExpression_CustomTimeZoneInIndexName <<< FAILURES!
06:36:03    > Throwable #1: java.lang.AssertionError: 
06:36:03    > Expected: ".marvel-2018.12.30"
06:36:03    >      but: was ".marvel-2019.12.30"
06:36:03    > 	at __randomizedtesting.SeedInfo.seed([57AEC52CB025A748:C7B07BB86A595B07]:0)
06:36:03    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
06:36:03    > 	at org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests.testExpression_CustomTimeZoneInIndexName(DateMathExpressionResolverTests.java:153)
```

**Comment by javanna** [comment]
I muted these tests on master.

**Comment by javanna** [comment]
I also muted RolloverIT#testRolloverWithDateMath which times out:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1006/console

```
REPRODUCE WITH: ./gradlew :server:integTest -Dtests.seed=697269496BDB2D94 -Dtests.class=org.elasticsearch.action.admin.indices.rollover.RolloverIT -Dtests.method="testRolloverWithDateMath" -Dtests.security.manager=true -Dtests.locale=is-IS -Dtests.timezone=Asia/Katmandu -Dcompiler.java=11 -Druntime.java=8
```

Fails with `[testRolloverWithDateMath] ensureGreen timed out`.

I am adding this to an existing issue as I suspect this failure has to do with date math issues changes, same reason for the above failues.

**Comment by danielmitterdorfer** [comment]
@rjernst / @spinscale could you please have a look at this one as it might also be related to the Joda time -> Java time migration?

**Comment by danielmitterdorfer** [comment]
^ Please disregard - I somehow missed that there is already an open PR that addresses this.
