### ISSUE TITLE
SQL: testCurrentTimestampYear fails around New Years Eve

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#37045]
This one was tested today (14:59 PM GMT, December 31st 2018), when in the time zone used in the test the clock already turned 2019 (12:59 AM, January 1st 2019).

```
  2> REPRODUCE WITH: gradlew :x-pack:plugin:sql:qa:security:with-ssl:integTestRunner -Dtests.seed=CF0CBFE0B2953F9F -Dtests.class=org.elasticsearch.xpack.sql.qa.security.JdbcSqlSpecIT -Dtests.method="test {datetime.testCurrentTimestampYear}" -Dtests.security.manager=true -Dtests.locale=bg -Dtests.timezone=Pacific/Guam -Dcompiler.java=11 -Druntime.java=8
FAILURE 3.85s | JdbcSqlSpecIT.test {datetime.testCurrentTimestampYear} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Different result for column [result], entry [1] expected:<2019> but was:<2018>
   >    at __randomizedtesting.SeedInfo.seed([CF0CBFE0B2953F9F:4758803A1C695267]:0)
   >    at org.elasticsearch.xpack.sql.qa.security.JdbcSqlSpecIT.datetime.testCurrentTimestampYear(datetime.sql-spec:120)
   >    at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.doAssertResultSetData(JdbcAssert.java:255)
   >    at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSetData(JdbcAssert.java:180)
   >    at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:83)
   >    at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:67)
   >    at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:56)
   >    at org.elasticsearch.xpack.sql.qa.jdbc.SpecBaseIntegrationTestCase.assertResults(SpecBaseIntegrationTestCase.java:127)
   >    at org.elasticsearch.xpack.sql.qa.jdbc.SqlSpecTestCase.doTest(SqlSpecTestCase.java:95)
   >    at org.elasticsearch.xpack.sql.qa.jdbc.SpecBaseIntegrationTestCase.test(SpecBaseIntegrationTestCase.java:88)
   >    at java.lang.Thread.run(Thread.java:748)
```

**Comment by astefan** [comment]
We always consider UTC as the timezone (since ES stores dates in UTC), so this is not a true issue, more of a limitation around testing NOW()/CURRENT_TIMESTAMP().

**Comment by bpintea** [comment]
A subsequent occurrence (raised initially in #50547):

**test2**
`org.elasticsearch.xpack.sql.qa.security.JdbcSqlSpecIT.test {datetime.testCurrentTimestampYear}`
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/13008/
```
java.lang.AssertionError: Different result for column [result], entry [1] expected:<2020> but was:<2019>
	at __randomizedtesting.SeedInfo.seed([727B38BA942A8BFC:FA2F07603AD6E604]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.doAssertResultSetData(JdbcAssert.java:310)
	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSetData(JdbcAssert.java:203)
	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:100)
	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:84)
	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:73)
	at org.elasticsearch.xpack.sql.qa.jdbc.SpecBaseIntegrationTestCase.assertResults(SpecBaseIntegrationTestCase.java:131)
	at org.elasticsearch.xpack.sql.qa.jdbc.SqlSpecTestCase.doTest(SqlSpecTestCase.java:93)
	at org.elasticsearch.xpack.sql.qa.jdbc.SpecBaseIntegrationTestCase.test(SpecBaseIntegrationTestCase.java:92)
```
`./gradlew ':x-pack:plugin:sql:qa:security:with-ssl:integTestRunner' --tests "org.elasticsearch.xpack.sql.qa.security.JdbcSqlSpecIT" -Dtests.method="test {datetime.testCurrentTimestampYear}" -Dtests.seed=727B38BA942A8BFC -Dtests.security.manager=true -Dtests.locale=ja-JP -Dtests.timezone=Asia/Ulan_Bator -Dcompiler.java=13`

this does not reproduce as it only failed for few hours in the first test due to zone offset +2
and in test2 possibly up to an offset provided in tests.timezone/locale
