### ISSUE TITLE
[CI] testRollupIDSchemeAfterRestart failure on BWC 6.3.0

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#37064]
Fails reproducibly (with all/multiple seeds) against 6.3.0 (but not 6.5.0)
```
./gradlew :x-pack:qa:full-cluster-restart:with-system-key:v6.3.0#upgradedClusterTestRunner -Dtests.seed=60A7CAF1992A4836 -Dtests.class=org.elasticsearch.xpack.restart.FullClusterRestartIT -Dtests.method="testRollupIDSchemeAfterRestart" -Dtests.security.manager=true -Dtests.locale=nl-NL -Dtests.timezone=America/Argentina/ComodRivadavia -Dcompiler.java=11 -Druntime.java=8
```

```
02:07:39 ERROR   0.06s | FullClusterRestartIT.testRollupIDSchemeAfterRestart <<< FAILURES!
02:07:39    > Throwable #1: org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:33259], URI [/id-test-rollup/doc/2], status line [HTTP/1.1 201 Created]
02:07:39    > Warnings: [[types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id}).]
02:07:39    > {"_index":"id-test-rollup","_type":"doc","_id":"2","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":0,"_primary_term":2}
02:07:39    > 	at __randomizedtesting.SeedInfo.seed([60A7CAF1992A4836:38C9E8CC16F7BE41]:0)
02:07:39    > 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:690)
02:07:39    > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:218)
02:07:39    > 	at org.elasticsearch.xpack.restart.FullClusterRestartIT.testRollupIDSchemeAfterRestart(FullClusterRestartIT.java:368)
02:07:39    > 	at java.lang.Thread.run(Thread.java:748)
02:07:39    > Caused by: org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:33259], URI [/id-test-rollup/doc/2], status line [HTTP/1.1 201 Created]
02:07:39    > Warnings: [[types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id}).]
02:07:39    > {"_index":"id-test-rollup","_type":"doc","_id":"2","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":0,"_primary_term":2}
02:07:39    > 	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:304)
02:07:39    > 	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:294)
02:07:39    > 	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
02:07:39    > 	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
02:07:39    > 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
02:07:39    > 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
02:07:39    > 	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
02:07:39    > 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
02:07:39    > 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
02:07:39    > 	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
02:07:39    > 	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
02:07:39    > 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
02:07:39    > 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
02:07:39    > 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
02:07:39    > 	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
02:07:39    > 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
02:07:39    > 	... 1 more
```

**Comment by jtibshirani** [comment]
This test was missing an expected warning declaration around typed index requests. I pushed https://github.com/elastic/elasticsearch/commit/265fdce312fbe8301d7f563eeaf9c0b8da6bfd61 to fix it.
