### ISSUE TITLE
Intermittent MapperParsingException for Date values from XContentBuilder

### ISSUE THREAD

**Issue by daniellawry** [elastic/elasticsearch#37146]
**Elasticsearch version**: 6.2.4
**JVM version**: 8 (1.8.0_92)
**OS version**: Windows 10 Pro

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

When using an XContentBuilder to populate a date field with a valid Java Date object, the indexing request occasionally returns with the following exception

```
MapperParsingException[failed to parse [EXPIRY_DATE:Job]]; nested: IllegalArgumentException[Invalid format: "57275-07-28T20:55:02.000Z" is malformed at "5-07-28T20:55:02.000Z"];
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:302)
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:485)
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:607)
	at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:407)
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:384)
	at org.elasticsearch.index.mapper.DocumentParser.internalParseDocument(DocumentParser.java:93)
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:67)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:261)
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:714)
	at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:692)
	at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:673)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:548)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequest(TransportShardBulkAction.java:140)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:236)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:123)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:110)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:72)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1034)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1012)
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:103)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:359)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.onResponse(TransportReplicationAction.java:299)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:975)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$1.onResponse(TransportReplicationAction.java:972)
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:238)
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2221)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:984)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.access$500(TransportReplicationAction.java:98)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:320)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:295)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:282)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
	at org.elasticsearch.transport.TransportService$7.doR
```

This happens intermittently and the documents this occurs with are never identical. It occurs in approximately 2-3 document indexing attempts in thousands.

We have a backup queue in the database to log these exceptions and retry the indexing request on a schedule and the next time the same document is indexed it indexes successfully without throwing the MapperParsingExeception

Index mappings:
```javascript
{
  "owp": {
    "mappings": {
      "_doc": {
        "dynamic_templates": [
          {
            "BOOLEAN_VALUE": {
              "match": "*",
              "match_mapping_type": "boolean",
              "mapping": {
                "fields": {
                  "raw": {
                    "type": "boolean"
                  }
                },
                "type": "boolean"
              }
            }
          },
          {
            "DATE_VALUE": {
              "match": "*",
              "match_mapping_type": "date",
              "mapping": {
                "type": "date"
              }
            }
          },
          {
            "DOUBLE_VALUE": {
              "match": "*",
              "match_mapping_type": "double",
              "mapping": {
                "type": "double"
              }
            }
          },
          {
            "LONG_VALUE": {
              "match": "*",
              "match_mapping_type": "long",
              "mapping": {
                "type": "long"
              }
            }
          },
          {
            "STRING_VALUE": {
              "match": "*",
              "match_mapping_type": "string",
              "mapping": {
                "analyzer": "standard_text_index_analyzer",
                "fields": {
                  "raw": {
                    "type": "keyword"
                  },
                  "sort": {
                    "normalizer": "default_normalizer",
                    "type": "keyword"
                  }
                },
                "search_analyzer": "standard_text_search_analyzer",
                "search_quote_analyzer": "standard_text_search_analyzer",
                "type": "text"
              }
            }
          },
          {
            "COMMENT": {
              "match": "*",
              "match_mapping_type": "object",
              "mapping": {
                "include_in_parent": true,
                "properties": {
                  "DATE": {
                    "type": "date"
                  },
                  "TASK_NAME": {
                    "type": "text",
                    "fields": {
                      "raw": {
                        "type": "keyword"
                      },
                      "sort": {
                        "normalizer": "default_normalizer",
                        "type": "keyword"
                      }
                    }
                  },
                  "CONTENT": {
                    "search_analyzer": "standard_text_search_analyzer",
                    "search_quote_analyzer": "standard_text_search_analyzer",
                    "analyzer": "standard_text_index_analyzer",
                    "type": "text",
                    "fields": {
                      "raw": {
                        "type": "keyword"
                      },
                      "sort": {
                        "normalizer": "default_normalizer",
                        "type": "keyword"
                      }
                    }
                  },
                  "USER": {
                    "type": "text",
                    "fields": {
                      "raw": {
                        "type": "keyword"
                      },
                      "sort": {
                        "normalizer": "default_normalizer",
                        "type": "keyword"
                      }
                    }
                  }
                },
                "type": "nested"
              }
            }
          }
        ],
        "numeric_detection": true,
        "properties": {
          "Comments:Job": {
            "type": "nested",
            "include_in_parent": true,
            "properties": {
              "CONTENT": {
                "type": "text",
                "fields": {
                  "raw": {
                    "type": "keyword"
                  },
                  "sort": {
                    "type": "keyword",
                    "normalizer": "default_normalizer"
                  }
                },
                "analyzer": "standard_text_index_analyzer",
                "search_analyzer": "standard_text_search_analyzer"
              },
              "DATE": {
                "type": "date"
              },
              "TASK_NAME": {
                "type": "text",
                "fields": {
                  "raw": {
                    "type": "keyword"
                  },
                  "sort": {
                    "type": "keyword",
                    "normalizer": "default_normalizer"
                  }
                }
              },
              "USER": {
                "type": "text",
                "fields": {
                  "raw": {
                    "type": "keyword"
                  },
                  "sort": {
                    "type": "keyword",
                    "normalizer": "default_normalizer"
                  }
                }
              }
            }
          },
          "DOCUMENT_MAX_RETRY_LIMIT:Job": {
            "type": "long"
          },
          "EDIT_JOB_ID:Job": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            },
            "analyzer": "standard_text_index_analyzer",
            "search_analyzer": "standard_text_search_analyzer"
          },
          "ERROR_QUEUE_BATCH_SIZE:Job": {
            "type": "long"
          },
          "ERROR_QUEUE_CHECK_INTERVAL:Job": {
            "type": "long"
          },
          "EVENT_ID:Job": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            },
            "analyzer": "standard_text_index_analyzer",
            "search_analyzer": "standard_text_search_analyzer"
          },
          "EXPIRY_DATE:Job": {
            "type": "date"
          },
          "Expire Time:Job": {
            "type": "date"
          },
          "INDEX_QUEUE_BATCH_SIZE:Job": {
            "type": "long"
          },
          "LeadTranslator:Task": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            },
            "analyzer": "standard_text_index_analyzer",
            "search_analyzer": "standard_text_search_analyzer"
          },
          "MEDAS_CONCEPT_BATCH_SIZE:Job": {
            "type": "long"
          },
          "MEDAS_CONCEPT_MODEL_BATCH_SIZE:Job": {
            "type": "long"
          },
          "MEDAS_RELATIONSHIP_BATCH_SIZE:Job": {
            "type": "long"
          },
          "MEDAS_RELATIONSHIP_MODEL_BATCH_SIZE:Job": {
            "type": "long"
          },
          "OBJ_ID:Job": {
            "type": "long"
          },
          "OWP_JOB_BATCH_SIZE:Job": {
            "type": "long"
          },
          "OWP_TASK_BATCH_SIZE:Job": {
            "type": "long"
          },
          "PROJECT_DB:Job": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            },
            "analyzer": "standard_text_index_analyzer",
            "search_analyzer": "standard_text_search_analyzer"
          },
          "PROJECT_DB_THREAD_COUNT:Job": {
            "type": "long"
          },
          "PROJECT_ID:Job": {
            "type": "long"
          },
          "PROJECT_INDEXER_THREAD_COUNT:Job": {
            "type": "long"
          },
          "PROJECT_NAME:Job": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            },
            "analyzer": "standard_text_index_analyzer",
            "search_analyzer": "standard_text_search_analyzer"
          },
          "QUEUE_CHECK_INTERVAL:Job": {
            "type": "long"
          },
          "RationalForChange:Job": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            },
            "analyzer": "standard_text_index_analyzer",
            "search_analyzer": "standard_text_search_analyzer"
          },
          "TargetCompletionDate:Job": {
            "type": "date"
          },
          "TranslationLanguage:Job": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            },
            "analyzer": "standard_text_index_analyzer",
            "search_analyzer": "standard_text_search_analyzer"
          },
          "UserName:Job": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            },
            "analyzer": "standard_text_index_analyzer",
            "search_analyzer": "standard_text_search_analyzer"
          },
          "_SYS_ATTACHMENTS:Standard": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            }
          },
          "_SYS_JOB_ATTACHED_TO:Standard": {
            "type": "nested",
            "include_in_parent": true,
            "properties": {
              "CATEGORY": {
                "type": "keyword"
              },
              "JOB_ID": {
                "type": "keyword"
              },
              "PROCESS_NAME": {
                "type": "keyword"
              },
              "PROCESS_REF": {
                "type": "keyword"
              }
            }
          },
          "_SYS_JOB_COMPLETE_DATE:Standard": {
            "type": "date"
          },
          "_SYS_JOB_CREATOR:Standard": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            }
          },
          "_SYS_JOB_DUE_DATE:Standard": {
            "type": "date"
          },
          "_SYS_JOB_DURATION:Standard": {
            "type": "double"
          },
          "_SYS_JOB_ID:Standard": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            }
          },
          "_SYS_JOB_ID_NUMERIC:Standard": {
            "type": "integer"
          },
          "_SYS_JOB_INITATION_DATE:Standard": {
            "type": "date"
          },
          "_SYS_JOB_LAST_UPDATE:Standard": {
            "type": "date"
          },
          "_SYS_JOB_LAST_UPDATE_BY:Standard": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            }
          },
          "_SYS_JOB_NAME:Standard": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            },
            "analyzer": "edge_ngram_text_index_analyzer",
            "search_analyzer": "standard_text_search_analyzer"
          },
          "_SYS_JOB_PRIORITY_NAME:Standard": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            }
          },
          "_SYS_JOB_SCHEDULED_END_DATE:Standard": {
            "type": "date"
          },
          "_SYS_JOB_SCHEDULED_START_DATE:Standard": {
            "type": "date"
          },
          "_SYS_JOB_START_DATE:Standard": {
            "type": "date"
          },
          "_SYS_JOB_STATUS_ID:Standard": {
            "type": "short"
          },
          "_SYS_JOB_STATUS_NAME:Standard": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            }
          },
          "_SYS_PROCESS_DEFINITION_NAME:Standard": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            }
          },
          "_SYS_PROCESS_ID:Standard": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            }
          },
          "_SYS_PROCESS_ID_NUMERIC:Standard": {
            "type": "integer"
          },
          "_SYS_PROCESS_REF:Standard": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            }
          },
          "_SYS_TASK_ASSIGNED_TO:Standard": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            }
          },
          "_SYS_TASK_AUTOMATED:Standard": {
            "type": "boolean"
          },
          "_SYS_TASK_AVAILABLE_DATE:Standard": {
            "type": "date"
          },
          "_SYS_TASK_COMPLETE_DATE:Standard": {
            "type": "date"
          },
          "_SYS_TASK_DUE_DATE:Standard": {
            "type": "date"
          },
          "_SYS_TASK_ID:Standard": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            }
          },
          "_SYS_TASK_ID_NUMERIC:Standard": {
            "type": "integer"
          },
          "_SYS_TASK_ITERATION:Standard": {
            "type": "short"
          },
          "_SYS_TASK_LAST_UPDATE_BY:Standard": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            }
          },
          "_SYS_TASK_LAST_UPDATE_DATE:Standard": {
            "type": "date"
          },
          "_SYS_TASK_NAME:Standard": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            }
          },
          "_SYS_TASK_STATUS_ID:Standard": {
            "type": "short"
          },
          "_SYS_TASK_STATUS_NAME:Standard": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            }
          },
          "_SYS_TASK_TYPE_ID:Standard": {
            "type": "short"
          },
          "_SYS_TASK_TYPE_NAME:Standard": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            }
          },
          "_SYS_WAIT_STATUS:Standard": {
            "type": "boolean"
          },
          "_SYS_WATCHED_JOB:Standard": {
            "type": "boolean"
          },
          "channel:Job": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            },
            "analyzer": "standard_text_index_analyzer",
            "search_analyzer": "standard_text_search_analyzer"
          },
          "collectionTitle:Job": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            },
            "analyzer": "standard_text_index_analyzer",
            "search_analyzer": "standard_text_search_analyzer"
          },
          "default_country_owner:Job": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            },
            "analyzer": "standard_text_index_analyzer",
            "search_analyzer": "standard_text_search_analyzer"
          },
          "exportTOCOnly:Job": {
            "type": "boolean",
            "fields": {
              "raw": {
                "type": "boolean"
              }
            }
          },
          "fixAttachment:Job": {
            "type": "boolean",
            "fields": {
              "raw": {
                "type": "boolean"
              }
            }
          },
          "fixCrossRef:Job": {
            "type": "boolean",
            "fields": {
              "raw": {
                "type": "boolean"
              }
            }
          },
          "fixMigratedTranslationID:Job": {
            "type": "boolean",
            "fields": {
              "raw": {
                "type": "boolean"
              }
            }
          },
          "fixRelatedLink:Job": {
            "type": "boolean",
            "fields": {
              "raw": {
                "type": "boolean"
              }
            }
          },
          "fromImport:Job": {
            "type": "boolean",
            "fields": {
              "raw": {
                "type": "boolean"
              }
            }
          },
          "includeDeprecated:Job": {
            "type": "boolean",
            "fields": {
              "raw": {
                "type": "boolean"
              }
            }
          },
          "join_field": {
            "type": "join",
            "eager_global_ordinals": true,
            "relations": {
              "job": "task"
            }
          },
          "nodeId:Job": {
            "type": "long"
          },
          "node_id:Job": {
            "type": "long"
          },
          "objIDs:Job": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            },
            "analyzer": "standard_text_index_analyzer",
            "search_analyzer": "standard_text_search_analyzer"
          },
          "onlyDeprecated:Job": {
            "type": "boolean",
            "fields": {
              "raw": {
                "type": "boolean"
              }
            }
          },
          "p1:Job": {
            "type": "long"
          },
          "ppid:Job": {
            "type": "long"
          },
          "rationalForChange:Job": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            },
            "analyzer": "standard_text_index_analyzer",
            "search_analyzer": "standard_text_search_analyzer"
          },
          "requestor:Job": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            },
            "analyzer": "standard_text_index_analyzer",
            "search_analyzer": "standard_text_search_analyzer"
          },
          "setDefaultScope:Job": {
            "type": "boolean",
            "fields": {
              "raw": {
                "type": "boolean"
              }
            }
          },
          "target:Job": {
            "type": "text",
            "fields": {
              "raw": {
                "type": "keyword"
              },
              "sort": {
                "type": "keyword",
                "normalizer": "default_normalizer"
              }
            },
            "analyzer": "standard_text_index_analyzer",
            "search_analyzer": "standard_text_search_analyzer"
          },
          "targetPublicationDate:Job": {
            "type": "date"
          },
          "type": {
            "type": "keyword"
          },
          "vsId:Job": {
            "type": "long"
          }
        }
      }
    }
  }
}
```

Java Code (XContentBuilder):
```java
// Setup for the Java code. Also note that only the portion of code responsible for the field from the stacktrace is being shown here

XContentBuilder builder = XContentFactory.jsonBuilder();
SimpleDateFormat dateTimeFormat = new SimpleDateFormat("EEE MMM dd HH:mm:ss zzz yyyy");
String rawDateTimeString = "Fri Feb 01 15:55:02 EST 2019";
String fieldId = "EXPIRY_DATE:Job";

...

Date dateTimeValue = null;
try {
	dateTimeValue = dateTimeFormat.parse(rawDateTimeString);
} catch (ParseException | NumberFormatException e) {
	String message = "DateTime value '" + rawDateTimeString + "' could not be matched against the datetime format '" + dateTimeFormat.toPattern() + "' for DateTime field " + fieldId;
	log.error(message);
}
if (dateTimeValue != null) {
	builder.field(fieldId, dateTimeValue);
}
```

The exact values for the value and field in the Java Code above were those that triggered the particular stacktrace above. In the above code, the String value "Fri Feb 01 15:55:02 EST 2019" is parsed into a Java Date using the SimpleDateFormat pattern of "EEE MMM dd HH:mm:ss zzz yyyy". There's no ParseException or NumberFormatException thrown (e.g. no error logged) and the dateTimeValue parameter is not null and so the Date dateTimeValue value for the EXPIRY_DATE:Job field is added to the for the EXPIRY_DATE:Job field in the elasticsearch mapping.

As you can probably see, we're just handing a Date object to the XContentBuilder to handle internally.

Java Code (Submitting the request):
```java
// Assuming the XContentBuilder buider object referenced in the previous Java block is present...

IndexRequestBuilder requestBuilder = getESClient().prepareIndex("owp", "_doc", documentId)									.setSource(builder);
if (routingId != null) {
	requestBuilder.setRouting(routingId);
}
if (refreshPolicy != null) {
	requestBuilder.setRefreshPolicy(refreshPolicy);
}

try {
	IndexResponse response = requestBuilder.get();
	indexedCount.incrementAndGet();
} catch (Exception e) {
	log.error(e.getMessage(), e);
	recordIndexingMessage(documentId, IndexingMessageType.FAILURE, e.getMessage(), indexingErrorMap);
	erroredCount.incrementAndGet();
}
```

No routingId or refreshPolicy are being used for this example but the MapperParsingException is thrown during the requestBuilder.get() call.

Again this happens intermittently so it's very hard to reproduce consistantly. Our only workaround currently is to re-queue the errored documents for re-indexing when this happens.

**Comment by daniellawry** [comment]
On a side note, I've found that it can be any date field, not just EXPIRY_DATE:Job. We've also seen it happend with targetPublicationDate:Job.

**Comment by romseygeek** [comment]
`SimpleDateFormat` is not thread safe - are you sharing the format object among multiple threads?

**Comment by daniellawry** [comment]
Checking back in. Any updates, @romseygeek ?

**Comment by javanna** [comment]
Hi, do you still have this problem? Were you able to recreate it consistently? Also, I see that your client code was using the java API which has been replaced in the meantime, so maybe that is also a factor in whether this is still a problem.

**Comment by javanna** [comment]
Closing for lack of activity, please add a comment if you still experience this problem.
