### ISSUE TITLE
[CI] NoMasterNodeIT.testNoMasterActions failures

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#37158]
I have seen this both in a PR and several jenkins runs today:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/3643/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1065/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8,nodes=virtual&&linux/156/console

It doesn't reproduce for me locally so far, but here is a reproduce output:
```
./gradlew :server:integTest -Dtests.seed=9B242048CDCF445E -Dtests.class=org.elasticsearch.cluster.NoMasterNodeIT -Dtests.method="testNoMasterActions" -Dtests.security.manager=true -Dtests.locale=lt-LT -Dtests.timezone=AST -Dcompiler.java=11 -Druntime.java=8
```

I see several warnings in the log like this:
```
22:05:36   1> [2019-01-04T12:05:04,321][WARN ][o.e.c.s.MasterService    ] [node_t0] failing [elected-as-master ([1] nodes joined)[{node_t1}{GqYC_Nu8Q0mFMbrIg85I0w}{eN9G1ElBRh-21DUgCFaTHw}{127.0.0.1}{127.0.0.1:43436} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_]]: failed to commit cluster state version [1]
22:05:36   1> org.elasticsearch.cluster.coordination.FailedToCommitClusterStateException: node stepped down as leader during publication
22:05:37   1> 	at org.elasticsearch.cluster.coordination.Coordinator.publish(Coordinator.java:862) ~[main/:?]
22:05:37   1> 	at org.elasticsearch.cluster.service.MasterService.publish(MasterService.java:253) [main/:?]
22:05:37   1> 	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:239) [main/:?]
22:05:37   1> 	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:143) [main/:?]
22:05:37   1> 	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [main/:?]
22:05:37   1> 	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [main/:?]
22:05:37   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660) [main/:?]
22:05:37   1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) [main/:?]
22:05:37   1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) [main/:?]
22:05:37   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
22:05:37   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
22:05:37   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
```

Followed by the following:
```
22:05:37   1> [2019-01-04T12:05:05,579][ERROR][o.e.c.c.Coordinator      ] [node_t0] unexpected failure during [node-left]
22:05:37   1> org.elasticsearch.cluster.coordination.FailedToCommitClusterStateException: publication failed
22:05:37   1> 	at org.elasticsearch.cluster.coordination.Coordinator$CoordinatorPublication$2.onFailure(Coordinator.java:1153) ~[main/:?]
22:05:37   1> 	at org.elasticsearch.common.util.concurrent.ListenableFuture$1.run(ListenableFuture.java:95) ~[main/:?]
22:05:37   1> 	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:140) ~[main/:?]
22:05:37   1> 	at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:86) ~[main/:?]
22:05:37   1> 	at org.elasticsearch.common.util.concurrent.ListenableFuture.addListener(ListenableFuture.java:54) ~[main/:?]
22:05:37   1> 	at org.elasticsearch.cluster.coordination.Coordinator$CoordinatorPublication.onCompletion(Coordinator.java:1107) ~[main/:?]
22:05:37   1> 	at org.elasticsearch.cluster.coordination.Publication.onPossibleCompletion(Publication.java:116) ~[main/:?]
22:05:37   1> 	at org.elasticsearch.cluster.coordination.Publication.onPossibleCommitFailure(Publication.java:164) ~[main/:?]
22:05:37   1> 	at org.elasticsearch.cluster.coordination.Publication.start(Publication.java:70) ~[main/:?]
22:05:37   1> 	at org.elasticsearch.cluster.coordination.Coordinator.publish(Coordinator.java:912) ~[main/:?]
22:05:37   1> 	at org.elasticsearch.cluster.service.MasterService.publish(MasterService.java:253) [main/:?]
22:05:37   1> 	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:239) [main/:?]
22:05:37   1> 	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:143) [main/:?]
22:05:37   1> 	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [main/:?]
22:05:37   1> 	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [main/:?]
22:05:37   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660) [main/:?]
22:05:37   1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) [main/:?]
22:05:37   1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) [main/:?]
22:05:37   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
22:05:37   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
22:05:37   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
```

**Comment by ywelsch** [comment]
This test was fixed by #37150
