### ISSUE TITLE
Old test started failing: org.elasticsearch.index.shard.RefreshListenersTests.testConcurrentRefresh

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#37261]
## Example build failure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1132/console

## Reproduction line 
does not reproduce locally
```
./gradlew :server:unitTest \
  -Dtests.seed=592CA98116641665 \
  -Dtests.class=org.elasticsearch.index.shard.RefreshListenersTests \
  -Dtests.method="testConcurrentRefresh" \
  -Dtests.security.manager=true \
  -Dtests.locale=nn-NO \
  -Dtests.timezone=Pacific/Galapagos \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

## Example relevant log:
```
00:13:11 FAILURE 28.6s J2 | RefreshListenersTests.testConcurrentRefresh <<< FAILURES!
00:13:11    > Throwable #1: java.lang.AssertionError
00:13:11    > 	at __randomizedtesting.SeedInfo.seed([592CA98116641665:9E66D31297C8B40F]:0)
00:13:11    > 	at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testConcurrentRefresh$8(RefreshListenersTests.java:283)
00:13:11    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:847)
00:13:11    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:821)
00:13:11    > 	at org.elasticsearch.index.shard.RefreshListenersTests.testConcurrentRefresh(RefreshListenersTests.java:283)
00:13:11    > 	at java.lang.Thread.run(Thread.java:748)
00:13:11    > 	Suppressed: java.lang.AssertionError
00:13:11    > 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testConcurrentRefresh$8(RefreshListenersTests.java:283)
00:13:11    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
00:13:11    > 		... 39 more
00:13:11    > 	Suppressed: java.lang.AssertionError
00:13:11    > 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testConcurrentRefresh$8(RefreshListenersTests.java:283)
00:13:11    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
00:13:11    > 		... 39 more
00:13:11    > 	Suppressed: java.lang.AssertionError
00:13:11    > 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testConcurrentRefresh$8(RefreshListenersTests.java:283)
00:13:11    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
00:13:11    > 		... 39 more
00:13:11    > 	Suppressed: java.lang.AssertionError
00:13:11    > 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testConcurrentRefresh$8(RefreshListenersTests.java:283)
00:13:11    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
00:13:11    > 		... 39 more
00:13:11    > 	Suppressed: java.lang.AssertionError
00:13:11    > 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testConcurrentRefresh$8(RefreshListenersTests.java:283)
00:13:11    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
00:13:11    > 		... 39 more
00:13:11    > 	Suppressed: java.lang.AssertionError
00:13:11    > 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testConcurrentRefresh$8(RefreshListenersTests.java:283)
00:13:11    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
00:13:11    > 		... 39 more
00:13:11    > 	Suppressed: java.lang.AssertionError
00:13:11    > 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testConcurrentRefresh$8(RefreshListenersTests.java:283)
00:13:11    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
00:13:11    > 		... 39 more
00:13:11    > 	Suppressed: java.lang.AssertionError
00:13:11    > 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testConcurrentRefresh$8(RefreshListenersTests.java:283)
00:13:11    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
00:13:11    > 		... 39 more
00:13:11    > 	Suppressed: java.lang.AssertionError
00:13:11    > 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testConcurrentRefresh$8(RefreshListenersTests.java:283)
00:13:11    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
00:13:11    > 		... 39 more
00:13:11    > 	Suppressed: java.lang.AssertionError
00:13:11    > 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testConcurrentRefresh$8(RefreshListenersTests.java:283)
00:13:11    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
00:13:11    > 		... 39 more
00:13:11    > 	Suppressed: java.lang.AssertionError
00:13:11    > 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testConcurrentRefresh$8(RefreshListenersTests.java:283)
00:13:11    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
00:13:11    > 		... 39 more
00:13:11    > 	Suppressed: java.lang.AssertionError
00:13:11    > 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testConcurrentRefresh$8(RefreshListenersTests.java:283)
00:13:11    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
00:13:11    > 		... 39 more
00:13:11    > 	Suppressed: java.lang.AssertionError
00:13:11    > 		at org.elasticsearch.index.shard.RefreshListenersTests.lambda$testConcurrentRefresh$8(RefreshListenersTests.java:283)
00:13:11    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
00:13:11    > 		... 39 more
```

## Frequency
Failed 6 times Today, once yesterday and once last year on December 12th

**Comment by atorok** [comment]
Test muted in 7ff846ffb24

**Comment by atorok** [comment]
another occurrence: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1131/console

**Comment by original-brownbear** [comment]
This is really tricky. It looks like these runs are all freakishly slow. 
They fail after ~ 30s in all the cases posted here and other tests in the logs either fail as well or are extremely slow too (Coordinator tests take ~15s on my local box but took 70s+ in these runs for example).
The fact that we even get to ~30s in this test is interesting (takes ~3s on my local box with the seed here) because it means we are waiting for multiple seconds on this [busy assert](https://github.com/elastic/elasticsearch/blob/master/server/src/test/java/org/elasticsearch/index/shard/RefreshListenersTests.java#L284) overall.
Maybe the fact that we're running 8 JVMs on 16 cores is coming around to bite us here? This test, for example, is running 1 completely hot thread + the main test thread that's pretty hot too. Given that we're also running only 512MB heap for the JVMs in these tests it seems possible that with GC in the mix we could get some pretty long blocks, doesn't it?

**Comment by original-brownbear** [comment]
=> In light of the above, I'd vote to close this issue.

**Comment by atorok** [comment]
The change to run more JVMs for the tests went in at least one moth before this started to fail,  and it does so on a range of different type of workers. 
We had 7 failures on the 7th , then one on 19th and 20th in December, and now in January 9 on th 8th and 20 on the 9th when I muted the test ( I muted the test on that day).  

I tried to reproduce it locally by generating artificial load of different types with `stress` and was still unable to do so.

**Comment by original-brownbear** [comment]
@atorok yea it's probably not the parallelism in isolation. The thing is, the fact that this test in particular randomly failed on one day makes me suspicious of the infra because it's using a lot of CPU + GC (from the Lucene writer that is called in a hot loop) + it's pretty vulnerable to GC pauses as well.

**Comment by ywelsch** [comment]
I've pushed 3a929c7aeac to see if that fixes the issue.

**Comment by ywelsch** [comment]
Looks like there were no more failures. Backporting the fix and closing this.
