### ISSUE TITLE
multiple test failures in ChildQuerySearchIT

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#37266]
## Example build failure

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=zulu11,nodes=virtual&&linux/169/console

But this failed on intake too:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1120/console

## Reproduction line 
does not reproduce locally
```
REPRODUCE WITH: ./gradlew :modules:parent-join:integTestRunner \
  -Dtests.seed=C74D403BEAA3E517 \
  -Dtests.class=org.elasticsearch.join.query.ChildQuerySearchIT \
  -Dtests.method="testParentChildQueriesViaScrollApi" \
  -Dtests.security.manager=true \
  -Dtests.locale=cgg-UG \
  -Dtests.timezone=America/Detroit \
  -Dcompiler.java=12 \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew :modules:parent-join:integTestRunner \
  -Dtests.seed=C74D403BEAA3E517 \
  -Dtests.class=org.elasticsearch.join.query.ChildQuerySearchIT \
  -Dtests.method="testParentChildQueriesViaScrollApi" \
  -Dtests.security.manager=true \
  -Dtests.locale=cgg-UG \
  -Dtests.timezone=America/Detroit \
  -Dcompiler.java=12 \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew :modules:parent-join:integTestRunner \
  -Dtests.seed=C74D403BEAA3E517 \
  -Dtests.class=org.elasticsearch.join.query.ChildQuerySearchIT \
  -Dtests.method="testParentChildQueriesViaScrollApi" \
  -Dtests.security.manager=true \
  -Dtests.locale=cgg-UG \
  -Dtests.timezone=America/Detroit \
  -Dcompiler.java=12 \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew :modules:parent-join:integTestRunner \
  -Dtests.seed=C74D403BEAA3E517 \
  -Dtests.class=org.elasticsearch.join.query.ChildQuerySearchIT \
  -Dtests.method="testSimpleQueryRewrite" \
  -Dtests.security.manager=true \
  -Dtests.locale=cgg-UG \
  -Dtests.timezone=America/Detroit \
  -Dcompiler.java=12 \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew :modules:parent-join:integTestRunner \
  -Dtests.seed=C74D403BEAA3E517 \
  -Dtests.class=org.elasticsearch.join.query.ChildQuerySearchIT \
  -Dtests.method="testSimpleQueryRewrite" \
  -Dtests.security.manager=true \
  -Dtests.locale=cgg-UG \
  -Dtests.timezone=America/Detroit \
  -Dcompiler.java=12 \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew :modules:parent-join:integTestRunner \
  -Dtests.seed=C74D403BEAA3E517 \
  -Dtests.class=org.elasticsearch.join.query.ChildQuerySearchIT \
  -Dtests.method="testNamedFilters" \
  -Dtests.security.manager=true \
  -Dtests.locale=cgg-UG \
  -Dtests.timezone=America/Detroit \
  -Dcompiler.java=12 \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew :modules:parent-join:integTestRunner \
  -Dtests.seed=C74D403BEAA3E517 \
  -Dtests.class=org.elasticsearch.join.query.ChildQuerySearchIT \
  -Dtests.method="testNamedFilters" \
  -Dtests.security.manager=true \
  -Dtests.locale=cgg-UG \
  -Dtests.timezone=America/Detroit \
  -Dcompiler.java=12 \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew :modules:parent-join:integTestRunner \
  -Dtests.seed=C74D403BEAA3E517 \
  -Dtests.class=org.elasticsearch.join.query.ChildQuerySearchIT \
  -Dtests.method="testScoreForParentChildQueriesWithFunctionScore" \
  -Dtests.security.manager=true \
  -Dtests.locale=cgg-UG \
  -Dtests.timezone=America/Detroit \
  -Dcompiler.java=12 \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew :modules:parent-join:integTestRunner \
  -Dtests.seed=C74D403BEAA3E517 \
  -Dtests.class=org.elasticsearch.join.query.ChildQuerySearchIT \
  -Dtests.method="testScoreForParentChildQueriesWithFunctionScore" \
  -Dtests.security.manager=true \
  -Dtests.locale=cgg-UG \
  -Dtests.timezone=America/Detroit \
  -Dcompiler.java=12 \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew :modules:parent-join:integTestRunner \
  -Dtests.seed=C74D403BEAA3E517 \
  -Dtests.class=org.elasticsearch.join.query.ChildQuerySearchIT \
  -Dtests.method="testParentChildCaching" \
  -Dtests.security.manager=true \
  -Dtests.locale=cgg-UG \
  -Dtests.timezone=America/Detroit \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

## Example relevant log:
```
06:51:29 ERROR   0.05s | ChildQuerySearchIT.testDeletedParent <<< FAILURES!
06:51:29    > Throwable #1: NoNodeAvailableException[None of the configured nodes were available: [{node_s1}{5TFPbgbaSwmKh78Ox8oiFw}{X7JH7fPoRMK_Hwyc3FmsmA}{127.0.0.1}{127.0.0.1:33019}]]; nested: NodeNotConnectedException[[node_s1][127.0.0.1:33019] Node not connected];
06:51:29    > 	at org.elasticsearch.client.transport.TransportClientNodesService$RetryListener.onFailure(TransportClientNodesService.java:295)
06:51:29    > 	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:53)
06:51:29    > 	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:534)
06:51:29    > 	at org.elasticsearch.action.TransportActionNodeProxy.execute(TransportActionNodeProxy.java:48)
06:51:29    > 	at org.elasticsearch.client.transport.TransportProxyClient.lambda$execute$0(TransportProxyClient.java:57)
06:51:29    > 	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:254)
06:51:29    > 	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:57)
06:51:29    > 	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:386)
06:51:29    > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:393)
06:51:29    > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:382)
06:51:29    > 	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1217)
06:51:29    > 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:45)
06:51:29    > 	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:52)
06:51:29    > 	at org.elasticsearch.test.TestCluster.wipeAllTemplates(TestCluster.java:167)
06:51:29    > 	at org.elasticsearch.test.TestCluster.wipe(TestCluster.java:80)
06:51:29    > 	at org.elasticsearch.test.ESIntegTestCase.lambda$beforeInternal$0(ESIntegTestCase.java:378)
06:51:29    > 	at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:187)
06:51:29    > 	at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:211)
06:51:29    > 	at org.elasticsearch.test.ESIntegTestCase.beforeInternal(ESIntegTestCase.java:386)
06:51:29    > 	at org.elasticsearch.test.ESIntegTestCase.setupTestCluster(ESIntegTestCase.java:2217)
06:51:29    > 	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
06:51:29    > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:51:29    > 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
06:51:29    > 	at java.base/java.lang.Thread.run(Thread.java:834)
06:51:29    > Caused by: NodeNotConnectedException[[node_s1][127.0.0.1:33019] Node not connected]
06:51:29    > 	at org.elasticsearch.transport.ConnectionManager.getConnection(ConnectionManager.java:156)
06:51:29    > 	at org.elasticsearch.transport.TransportService.getConnection(TransportService.java:558)
06:51:29    > 	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:530)
06:51:29    > 	... 51 moreThrowable #2: NoNodeAvailableException[None of the configured nodes were available: [{node_s1}{5TFPbgbaSwmKh78Ox8oiFw}{X7JH7fPoRMK_Hwyc3FmsmA}{127.0.0.1}{127.0.0.1:33019}]]; nested: NodeNotConnectedException[[node_s1][127.0.0.1:33019] Node not connected];
06:51:29    > 	at org.elasticsearch.client.transport.TransportClientNodesService$RetryListener.onFailure(TransportClientNodesService.java:295)
06:51:29    > 	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:53)
06:51:29    > 	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:534)
06:51:29    > 	at org.elasticsearch.action.TransportActionNodeProxy.execute(TransportActionNodeProxy.java:48)
06:51:29    > 	at org.elasticsearch.client.transport.TransportProxyClient.lambda$execute$0(TransportProxyClient.java:57)
06:51:29    > 	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:254)
06:51:29    > 	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:57)
06:51:29    > 	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:386)
06:51:29    > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:393)
06:51:29    > 	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:65)
06:51:29    > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:393)
06:51:29    > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:382)
06:51:29    > 	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:676)
06:51:29    > 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:45)
06:51:29    > 	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:52)
06:51:29    > 	at org.elasticsearch.test.ESIntegTestCase.ensureClusterStateConsistency(ESIntegTestCase.java:1139)
06:51:29    > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:573)
06:51:29    > 	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2231)
06:51:29    > 	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
06:51:29    > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:51:29    > 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
06:51:29    > 	at java.base/java.lang.Thread.run(Thread.java:834)
06:51:29    > Caused by: NodeNotConnectedException[[node_s1][127.0.0.1:33019] Node not connected]
06:51:29    > 	at org.elasticsearch.transport.ConnectionManager.getConnection(ConnectionManager.java:156)
06:51:29    > 	at org.elasticsearch.transport.TransportService.getConnection(TransportService.java:558)
06:51:29    > 	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:530)
06:51:29    > 	... 48 more
06:51:29   1> [2019-01-08T23:50:08,328][INFO ][o.e.n.Node               ] [suite] stopping ...
```

## Frequency
Yesterday saw 10 failures on master build alone.

**Comment by atorok** [comment]
Muted in 7de4d2cb0fb
