### ISSUE TITLE
[CI] UnicastZenPingTests.testInvalidHosts

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#37268]
## Example build failure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/309/console

## Reproduction line 
does not reproduce locally
```
REPRODUCE WITH: ./gradlew :server:unitTest \
  -Dtests.seed=86FB7F4B57514FBE \
  -Dtests.class=org.elasticsearch.discovery.zen.UnicastZenPingTests \
  -Dtests.method="testInvalidHosts" \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=ar-YE \
  -Dtests.timezone=Asia/Brunei \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

## Example relevant log:
```
FAILURE 21.5s J2 | UnicastZenPingTests.testInvalidHosts <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: a collection with size <1>
   >      but: collection size was <0>
   > 	at __randomizedtesting.SeedInfo.seed([86FB7F4B57514FBE:97CE97BE380F6D4A]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.discovery.zen.UnicastZenPingTests.testInvalidHosts(UnicastZenPingTests.java:726)
   > 	at java.lang.Thread.run(Thread.java:748)
```

## Frequency
4 times Today. 

Related: #23738

**Comment by dakrone** [comment]
This does not appear to be a timeout issue, the code in question that fails:

```java
        final List<TransportAddress> transportAddresses = UnicastZenPing.resolveHostsLists(
            executorService,
            logger,
            Arrays.asList("127.0.0.1:9300:9300", "127.0.0.1:9301"),
            1,
            transportService,
            TimeValue.timeValueSeconds(1));
        assertThat(transportAddresses, hasSize(1)); // only one of the two is valid and will be used
```

Does take a little bit of time (22 seconds), but doesn't run into the timeout error that would be thrown by `resolveHostsLists`. Instead it appears that the the error is valid.

**Comment by ywelsch** [comment]
This looks to be a timeout issue (can be verified by changing `TimeValue.timeValueSeconds(1)` to something lower such as `TimeValue.timeValueMillis(1)`. I've pushed 4d3928d4449
