### ISSUE TITLE
Test failure: UpdateMappingIntegrationIT.testDynamicUpdates

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#37263]
## Example build failure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1145/consoleFull

## Reproduction line 
does not reproduce locally
```
./gradlew :server:integTest \
  -Dtests.seed=EA14BF6B2F1596A0 \
  -Dtests.class=org.elasticsearch.indices.mapping.UpdateMappingIntegrationIT \
  -Dtests.method="testDynamicUpdates" \
  -Dtests.security.manager=true \
  -Dtests.locale=fi-FI \
  -Dtests.timezone=Atlantic/Cape_Verde \
  -Dcompiler.java=11 \
  -Druntime.java=8

```

## Example relevant log:
```
13:37:53   1> [2019-01-09T10:36:56,651][INFO ][o.e.i.m.UpdateMappingIntegrationIT] [node_s1] Action Failed
13:37:53   1> org.elasticsearch.ElasticsearchTimeoutException: Failed to acknowledge mapping update within [13s]
13:37:53   1> 	at org.elasticsearch.cluster.action.index.MappingUpdatedAction.updateMappingOnMaster(MappingUpdatedAction.java:88) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.cluster.action.index.MappingUpdatedAction.updateMappingOnMaster(MappingUpdatedAction.java:78) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction$ConcreteMappingUpdatePerformer.updateMappings(TransportShardBulkAction.java:519) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.lambda$executeIndexRequestOnPrimary$5(TransportShardBulkAction.java:465) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeOnPrimaryWhileHandlingMappingUpdates(TransportShardBulkAction.java:488) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:459) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:218) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:161) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:153) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:141) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:79) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1034) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1012) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:102) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.runWithPrimaryShardReference(TransportReplicationAction.java:414) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$doRun$0(TransportReplicationAction.java:360) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60) [main/:?]
13:37:53   1> 	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:269) [main/:?]
13:37:53   1> 	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:236) [main/:?]
13:37:53   1> 	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2356) [main/:?]
13:37:53   1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryOperationPermit(TransportReplicationAction.java:971) [main/:?]
13:37:53   1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:359) [main/:?]
13:37:53   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [main/:?]
13:37:53   1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:314) [main/:?]
13:37:53   1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:306) [main/:?]
13:37:53   1> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) [main/:?]
13:37:53   1> 	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:688) [main/:?]
13:37:53   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759) [main/:?]
13:37:53   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [main/:?]
13:37:53   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
13:37:53   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
13:37:53   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
13:37:53   1> [2019-01-09T10:36:56,673][INFO ][o.e.i.m.UpdateMappingIntegrationIT] [transport_client_node_sc2] Action Failed
13:37:53   1> org.elasticsearch.transport.RemoteTransportException: [node_sc2][127.0.0.1:38638][indices:data/write/index]
13:37:53   1> Caused by: org.elasticsearch.ElasticsearchTimeoutException: Failed to acknowledge mapping update within [13s]
13:37:53   1> 	at org.elasticsearch.cluster.action.index.MappingUpdatedAction.updateMappingOnMaster(MappingUpdatedAction.java:88) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.cluster.action.index.MappingUpdatedAction.updateMappingOnMaster(MappingUpdatedAction.java:78) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction$ConcreteMappingUpdatePerformer.updateMappings(TransportShardBulkAction.java:519) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.lambda$executeIndexRequestOnPrimary$5(TransportShardBulkAction.java:465) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeOnPrimaryWhileHandlingMappingUpdates(TransportShardBulkAction.java:488) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeIndexRequestOnPrimary(TransportShardBulkAction.java:459) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:218) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:161) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:153) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:141) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:79) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1034) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:1012) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:102) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.runWithPrimaryShardReference(TransportReplicationAction.java:414) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$doRun$0(TransportReplicationAction.java:360) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:269) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:236) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2356) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryOperationPermit(TransportReplicationAction.java:971) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:359) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:314) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:306) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:688) ~[main/:?]
13:37:53   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759) [main/:?]
13:37:53   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [main/:?]
13:37:53   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
13:37:53   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
13:37:53   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]

[..]

13:37:53 FAILURE 57.1s J3 | UpdateMappingIntegrationIT.testDynamicUpdates <<< FAILURES!
13:37:53    > Throwable #1: java.lang.AssertionError: 
13:37:53    > Expected: an empty iterable
13:37:53    >      but: [<ElasticsearchTimeoutException[Failed to acknowledge mapping update within [13s]]>,<RemoteTransportException[[node_sc2][127.0.0.1:38638][indices:data/write/index]]; nested: ElasticsearchTimeoutException[Failed to acknowledge mapping update within [13s]];>]
13:37:53    > 	at __randomizedtesting.SeedInfo.seed([EA14BF6B2F1596A0:6ACD8921D12AC84]:0)
13:37:53    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
13:37:53    > 	at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1553)
13:37:53    > 	at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1467)
13:37:53    > 	at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1450)
13:37:53    > 	at org.elasticsearch.indices.mapping.UpdateMappingIntegrationIT.testDynamicUpdates(UpdateMappingIntegrationIT.java:83)
13:37:53    > 	at java.lang.Thread.run(Thread.java:748)
```

## Frequency

No more than 2 failures per day, doesn't fail daily, started failing on Dec. 12th.

**Comment by ywelsch** [comment]
This looks to be a CI / infrastructure problem. This test does a ton of mapping updates, and the timeout is randomized by the test with a value between 10 and 30 seconds (in the failed test run here it was randomly set to 13 seconds). We can see that during the test there are already prior multi-second pauses before the failure, and also GC warnings around the same timeframes.

```
1> [2019-01-09T10:36:35,366][INFO ][o.e.c.m.MetaDataMappingService] [node_s1] [test/0TZpE3ABQtyx4qv_MzrRNQ] update_mapping [type]
  1> [2019-01-09T10:36:35,391][INFO ][o.e.c.m.MetaDataMappingService] [node_s1] [test/0TZpE3ABQtyx4qv_MzrRNQ] update_mapping [type]
  1> [2019-01-09T10:36:35,412][INFO ][o.e.c.m.MetaDataMappingService] [node_s1] [test/0TZpE3ABQtyx4qv_MzrRNQ] update_mapping [type]
  1> [2019-01-09T10:36:35,434][INFO ][o.e.c.m.MetaDataMappingService] [node_s1] [test/0TZpE3ABQtyx4qv_MzrRNQ] update_mapping [type]
  1> [2019-01-09T10:36:35,454][INFO ][o.e.c.m.MetaDataMappingService] [node_s1] [test/0TZpE3ABQtyx4qv_MzrRNQ] update_mapping [type]
  1> [2019-01-09T10:36:35,851][INFO ][o.e.m.j.JvmGcMonitorService] [node_s1] [gc][16] overhead, spent [274ms] collecting in the last [1s]
  1> [2019-01-09T10:36:40,967][INFO ][o.e.c.m.MetaDataMappingService] [node_s1] [test/0TZpE3ABQtyx4qv_MzrRNQ] update_mapping [type]
  1> [2019-01-09T10:36:41,004][INFO ][o.e.c.m.MetaDataMappingService] [node_s1] [test/0TZpE3ABQtyx4qv_MzrRNQ] update_mapping [type]
  1> [2019-01-09T10:36:41,010][INFO ][o.e.c.m.MetaDataMappingService] [node_s1] [test/0TZpE3ABQtyx4qv_MzrRNQ] update_mapping [type]
  1> [2019-01-09T10:36:41,064][INFO ][o.e.c.m.MetaDataMappingService] [node_s1] [test/0TZpE3ABQtyx4qv_MzrRNQ] update_mapping [type]
  1> [2019-01-09T10:36:41,068][INFO ][o.e.c.m.MetaDataMappingService] [node_s1] [test/0TZpE3ABQtyx4qv_MzrRNQ] update_mapping [type]
  1> [2019-01-09T10:36:41,098][INFO ][o.e.c.m.MetaDataMappingService] [node_s1] [test/0TZpE3ABQtyx4qv_MzrRNQ] update_mapping [type]
```

Maybe take this to the infra team to check the CI workers?

**Comment by atorok** [comment]
Here's a different run on a different worker, this time ephemeral and immutable: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1146/consoleFull

**Comment by atorok** [comment]
related #36759

**Comment by original-brownbear** [comment]
Just a note: I'm not so sure this is a timeout/infra problem. I just ran into it today on my fast and stable machine.
Relevant logs attached:
[Uploading fail.log…]()
locally.

**Comment by ywelsch** [comment]
I've pushed 859e2f5 as a fix
