### ISSUE TITLE
[CI] CloseWhileRelocatingShardsIT.testCloseWhileRelocatingShards

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#37274]
## Example build failure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1156/console

## Reproduction line 
**does** reproduce locally
```
./gradlew :server:integTest \
  -Dtests.seed=ECD17CF0692217A \
  -Dtests.class=org.elasticsearch.indices.state.CloseWhileRelocatingShardsIT \
  -Dtests.method="testCloseWhileRelocatingShards" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=Asia/Famagusta \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

## Example relevant log:
```
19:48:36    > Throwable #1: java.lang.AssertionError: Consider that the test failed if no indices were successfully closed
19:48:36    > Expected: a value greater than <0>
19:48:36    >      but: <0> was equal to <0>
19:48:36    > 	at __randomizedtesting.SeedInfo.seed([ECD17CF0692217A:2146095A290C77C0]:0)
19:48:36    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
19:48:36    > 	at org.elasticsearch.indices.state.CloseWhileRelocatingShardsIT.testCloseWhileRelocatingShards(CloseWhileRelocatingShardsIT.java:185)
19:48:36    > 	at java.lang.Thread.run(Thread.java:748)
```

## Frequency
first of it's kind, "lucky" seed.

**Comment by atorok** [comment]
Another one on intake: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1200/console

Muted test in 82ca2d62dec
