### ISSUE TITLE
[CI] MasterDisruptionIT.testVerifyApiBlocksDuringPartition

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#37276]
## Example build failure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/255/console

## Reproduction line 
does not reproduce locally
```
 ./gradlew :server:integTest \
  -Dtests.seed=32FB7E7C042DD526 \
  -Dtests.class=org.elasticsearch.discovery.MasterDisruptionIT \
  -Dtests.method="testVerifyApiBlocksDuringPartition" \
  -Dtests.security.manager=true \
  -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" \
  -Dtests.locale=it-IT \
  -Dtests.timezone=Asia/Vladivostok \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

## Example relevant log:
```
java.lang.AssertionError: node [node_t2] still has [{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}] as master expected null, but was:<{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}>
	at __randomizedtesting.SeedInfo.seed([32FB7E7C042DD526:D24311287CFEA6AC]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at org.elasticsearch.discovery.AbstractDisruptionTestCase.lambda$assertNoMaster$0(AbstractDisruptionTestCase.java:172)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:847)
	at org.elasticsearch.discovery.AbstractDisruptionTestCase.assertNoMaster(AbstractDisruptionTestCase.java:169)
	at org.elasticsearch.discovery.MasterDisruptionIT.testVerifyApiBlocksDuringPartition(MasterDisruptionIT.java:411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.AssertionError: node [node_t2] still has [{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}] as master expected null, but was:<{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotNull(Assert.java:755)
		at org.junit.Assert.assertNull(Assert.java:737)
		at org.elasticsearch.discovery.AbstractDisruptionTestCase.lambda$assertNoMaster$0(AbstractDisruptionTestCase.java:172)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 39 more
	Suppressed: java.lang.AssertionError: node [node_t2] still has [{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}] as master expected null, but was:<{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotNull(Assert.java:755)
		at org.junit.Assert.assertNull(Assert.java:737)
		at org.elasticsearch.discovery.AbstractDisruptionTestCase.lambda$assertNoMaster$0(AbstractDisruptionTestCase.java:172)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 39 more
	Suppressed: java.lang.AssertionError: node [node_t2] still has [{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}] as master expected null, but was:<{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotNull(Assert.java:755)
		at org.junit.Assert.assertNull(Assert.java:737)
		at org.elasticsearch.discovery.AbstractDisruptionTestCase.lambda$assertNoMaster$0(AbstractDisruptionTestCase.java:172)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 39 more
	Suppressed: java.lang.AssertionError: node [node_t2] still has [{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}] as master expected null, but was:<{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotNull(Assert.java:755)
		at org.junit.Assert.assertNull(Assert.java:737)
		at org.elasticsearch.discovery.AbstractDisruptionTestCase.lambda$assertNoMaster$0(AbstractDisruptionTestCase.java:172)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 39 more
	Suppressed: java.lang.AssertionError: node [node_t2] still has [{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}] as master expected null, but was:<{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotNull(Assert.java:755)
		at org.junit.Assert.assertNull(Assert.java:737)
		at org.elasticsearch.discovery.AbstractDisruptionTestCase.lambda$assertNoMaster$0(AbstractDisruptionTestCase.java:172)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 39 more
	Suppressed: java.lang.AssertionError: node [node_t2] still has [{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}] as master expected null, but was:<{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotNull(Assert.java:755)
		at org.junit.Assert.assertNull(Assert.java:737)
		at org.elasticsearch.discovery.AbstractDisruptionTestCase.lambda$assertNoMaster$0(AbstractDisruptionTestCase.java:172)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 39 more
	Suppressed: java.lang.AssertionError: node [node_t2] still has [{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}] as master expected null, but was:<{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotNull(Assert.java:755)
		at org.junit.Assert.assertNull(Assert.java:737)
		at org.elasticsearch.discovery.AbstractDisruptionTestCase.lambda$assertNoMaster$0(AbstractDisruptionTestCase.java:172)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 39 more
	Suppressed: java.lang.AssertionError: node [node_t2] still has [{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}] as master expected null, but was:<{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotNull(Assert.java:755)
		at org.junit.Assert.assertNull(Assert.java:737)
		at org.elasticsearch.discovery.AbstractDisruptionTestCase.lambda$assertNoMaster$0(AbstractDisruptionTestCase.java:172)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 39 more
	Suppressed: java.lang.AssertionError: node [node_t2] still has [{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}] as master expected null, but was:<{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotNull(Assert.java:755)
		at org.junit.Assert.assertNull(Assert.java:737)
		at org.elasticsearch.discovery.AbstractDisruptionTestCase.lambda$assertNoMaster$0(AbstractDisruptionTestCase.java:172)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 39 more
	Suppressed: java.lang.AssertionError: node [node_t2] still has [{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}] as master expected null, but was:<{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotNull(Assert.java:755)
		at org.junit.Assert.assertNull(Assert.java:737)
		at org.elasticsearch.discovery.AbstractDisruptionTestCase.lambda$assertNoMaster$0(AbstractDisruptionTestCase.java:172)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 39 more
	Suppressed: java.lang.AssertionError: node [node_t2] still has [{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}] as master expected null, but was:<{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotNull(Assert.java:755)
		at org.junit.Assert.assertNull(Assert.java:737)
		at org.elasticsearch.discovery.AbstractDisruptionTestCase.lambda$assertNoMaster$0(AbstractDisruptionTestCase.java:172)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 39 more
	Suppressed: java.lang.AssertionError: node [node_t2] still has [{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}] as master expected null, but was:<{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotNull(Assert.java:755)
		at org.junit.Assert.assertNull(Assert.java:737)
		at org.elasticsearch.discovery.AbstractDisruptionTestCase.lambda$assertNoMaster$0(AbstractDisruptionTestCase.java:172)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
		... 39 more
	Suppressed: java.lang.AssertionError: node [node_t2] still has [{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}] as master expected null, but was:<{node_t1}{VahkyeueTTmabr5-LtOD0A}{Owvct2T0RNC-RdRPKCZ5hg}{127.0.0.1}{127.0.0.1:42061}>
		at org.junit.Assert.fail(Assert.java:88)
		at org.junit.Assert.failNotNull(Assert.java:755)
		at org.junit.Assert.assertNull(Assert.java:737)
		at org.elasticsearch.discovery.AbstractDisruptionTestCase.lambda$assertNoMaster$0(AbstractDisruptionTestCase.java:172)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
```

## Frequency
6 times Today

**Comment by atorok** [comment]
Other tests seem to fail similarly: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/253/console

**Comment by gwbrown** [comment]
This test also sometimes fails with a different error exception:

```
[test/EIGGObEaTSmz58bMFgbKbg] IndexNotFoundException[no such index [test]]
	at __randomizedtesting.SeedInfo.seed([7124FAC68D24427B:919C9592F5F731F1]:0)
	at org.elasticsearch.indices.IndicesService.indexServiceSafe(IndicesService.java:422)
	at org.elasticsearch.test.InternalTestCluster.lambda$assertSameDocIdsOnShards$8(InternalTestCluster.java:1362)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:821)
	at org.elasticsearch.test.InternalTestCluster.assertSameDocIdsOnShards(InternalTestCluster.java:1352)
	at org.elasticsearch.discovery.AbstractDisruptionTestCase.beforeIndexDeletion(AbstractDisruptionTestCase.java:110)
	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:589)
	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2231)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

As in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1216/console
This is a weird one: It will go for a long time between failing, then fail 10 times in one day. Might be worth muting this.

**Comment by ywelsch** [comment]
@dnhatn this last one looks different, and could be fixed by using `indexService` with a null check instead of `indexServiceSafe`? Can you make a fix?

**Comment by ywelsch** [comment]
I've looked at the original failure here (reported by @atorok). The reason for the failure is that the test relies on the failure detector triggering after reasonable amount of time. The transport-level timeout is set in these tests to 1s, but it triggers after only 16s in this CI run:

```
1> [2019-01-10T04:11:38,678][DEBUG][o.e.c.c.FollowersChecker ] [node_t1] FollowerChecker{discoveryNode={node_t2}{sA6WouIzQv-C3SH8YfD1kQ}{atRNexMdRFSzXs6-D2Dh1A}{127.0.0.1}{127.0.0.1:45701}, failureCountSinceLastSuccess=1, [cluster.fault_detection.follower_check.retry_count]=1} failed too many times
  1> org.elasticsearch.transport.ReceiveTimeoutTransportException: [node_t2][127.0.0.1:45701][internal:coordination/fault_detection/follower_check] request_id [68] timed out after [16816ms]
  1> 	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:1012) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660) [main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
``` 

The assert busy here that fails only polls for 10 seconds, though, which is reasonable given that the failure detector is supposed to kick the node out after 1s. I'm not sure why the transport request takes 16s to timeout.

This looks quite similar to https://github.com/elastic/elasticsearch/issues/37275#issuecomment-454023328

**Comment by dnhatn** [comment]
@ywelsch I pushed https://github.com/elastic/elasticsearch/commit/1e3702da0b54e32b0e4aaa8ea1955cbbe4215afa to relax the assertion `assertSameDocIdsOnShards`.

**Comment by jkakavas** [comment]
This failed also on 6.x in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1034 with a connection exception this time. Adding it as a data point with a reservation, but it is the first of the 3 tests that failed in this build. (The other two were Discovery related too `DiscoveryDisruptionIT#testElectMasterWithLatestVersion` and `ClusterDisruptionIT#testAckedIndexing`)  

```
1> org.elasticsearch.transport.ConnectTransportException: [node_t0][127.0.0.1:38795] connect_exception
  1> 	at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onFailure(TcpTransport.java:1566) ~[main/:?]
  1> 	at org.elasticsearch.action.ActionListener.lambda$toBiConsumer$2(ActionListener.java:100) ~[main/:?]
  1> 	at org.elasticsearch.common.concurrent.CompletableContext.lambda$addListener$0(CompletableContext.java:42) ~[elasticsearch-core-6.7.0-SNAPSHOT.jar:6.7.0-SNAPSHOT]
  1> 	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[?:1.8.0_192]
  1> 	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[?:1.8.0_192]
  1> 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_192]
  1> 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_192]
  1> 	at org.elasticsearch.common.concurrent.CompletableContext.completeExceptionally(CompletableContext.java:57) ~[elasticsearch-core-6.7.0-SNAPSHOT.jar:6.7.0-SNAPSHOT]
  1> 	at org.elasticsearch.transport.MockTcpTransport.lambda$initiateChannel$0(MockTcpTransport.java:195) ~[framework-6.7.0-SNAPSHOT.jar:?]
  1> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_192]
  1> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_192]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
  1> Caused by: java.net.ConnectException: Connection refused (Connection refused)
  1> 	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_192]
  1> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_192]
  1> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_192]
  1> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_192]
  1> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_192]
  1> 	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_192]
  1> 	at org.elasticsearch.mocksocket.MockSocket.access$101(MockSocket.java:32) ~[mocksocket-1.2.jar:?]
  1> 	at org.elasticsearch.mocksocket.MockSocket.lambda$connect$0(MockSocket.java:66) ~[mocksocket-1.2.jar:?]
  1> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_192]
  1> 	at org.elasticsearch.mocksocket.MockSocket.connect(MockSocket.java:65) ~[mocksocket-1.2.jar:?]
  1> 	at org.elasticsearch.mocksocket.MockSocket.connect(MockSocket.java:59) ~[mocksocket-1.2.jar:?]
  1> 	at org.elasticsearch.transport.MockTcpTransport.lambda$initiateChannel$0(MockTcpTransport.java:190) ~[framework-6.7.0-SNAPSHOT.jar:?]
  1> 	... 5 more
```

**Comment by ywelsch** [comment]
No recent failures
