### ISSUE TITLE
CI: GeoIpProcessorFactoryTests fail on windows

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#37342]
```
02:51:39 IGNOR/A 0.00s J0 | GeoIpProcessorFactoryTests.testBuildFields
02:51:39    > Assumption #1: windows deletion behavior is asinine
02:51:39 ERROR   0.00s J0 | GeoIpProcessorFactoryTests (suite) <<< FAILURES!
02:51:39    > Throwable #1: java.io.IOException: Could not remove the following files (in the order of attempts):
02:51:39    >    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\modules\ingest-geoip\build\testrun\unitTest\J0\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_5AA4C8CA7DBA6055-001\tempDir-005\ingest-geoip\GeoIP2-City.mmdb: java.nio.file.FileSystemException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\modules\ingest-geoip\build\testrun\unitTest\J0\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_5AA4C8CA7DBA6055-001\tempDir-005\ingest-geoip\GeoIP2-City.mmdb: The process cannot access the file because it is being used by another process.
02:51:39    >    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\modules\ingest-geoip\build\testrun\unitTest\J0\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_5AA4C8CA7DBA6055-001\tempDir-005\ingest-geoip: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\modules\ingest-geoip\build\testrun\unitTest\J0\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_5AA4C8CA7DBA6055-001\tempDir-005\ingest-geoip
02:51:39    >    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\modules\ingest-geoip\build\testrun\unitTest\J0\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_5AA4C8CA7DBA6055-001\tempDir-005: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\modules\ingest-geoip\build\testrun\unitTest\J0\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_5AA4C8CA7DBA6055-001\tempDir-005
02:51:39    >    C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\modules\ingest-geoip\build\testrun\unitTest\J0\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_5AA4C8CA7DBA6055-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\modules\ingest-geoip\build\testrun\unitTest\J0\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_5AA4C8CA7DBA6055-001
02:51:39    > 	at __randomizedtesting.SeedInfo.seed([5AA4C8CA7DBA6055]:0)
02:51:39    > 	at org.apache.lucene.util.IOUtils.rm(IOUtils.java:318)
02:51:39    > 	at java.lang.Thread.run(Thread.java:748)
02:51:39 Completed [2/4] on J0 in 7.82s, 15 tests, 1 error, 12 skipped <<< FAILURES!
```

Relates to #29001 cc @danielmitterdorfer

**Comment by atorok** [comment]
This is still failing Windows builds in CI. My attempt to mute was only partially successful. 
I took a quick look but couldn't figure out where the thread from the failure originates. 
The test itself does skip on Windows.

**Comment by atorok** [comment]
This still fails on `6.8` : https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+multijob-windows-compatibility/37

**Comment by davidkyle** [comment]
Another Windows failure on 6.8: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+multijob-windows-compatibility/69/console

```
java.io.IOException: Could not remove the following files (in the order of attempts):
   C:\Users\jenkins\workspace\elastic+elasticsearch+6.8+multijob-windows-compatibility\modules\ingest-geoip\build\testrun\unitTest\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorNonIngestNodeTests_741A4555102E93A1-001\tempDir-005\GeoLite2-ASN.mmdb: java.nio.file.FileSystemException: C:\Users\jenkins\workspace\elastic+elasticsearch+6.8+multijob-windows-compatibility\modules\ingest-geoip\build\testrun\unitTest\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorNonIngestNodeTests_741A4555102E93A1-001\tempDir-005\GeoLite2-ASN.mmdb: The process cannot access the file because it is being used by another process.

   C:\Users\jenkins\workspace\elastic+elasticsearch+6.8+multijob-windows-compatibility\modules\ingest-geoip\build\testrun\unitTest\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorNonIngestNodeTests_741A4555102E93A1-001\tempDir-005\GeoLite2-City.mmdb: java.nio.file.FileSystemException: C:\Users\jenkins\workspace\elastic+elasticsearch+6.8+multijob-windows-compatibility\modules\ingest-geoip\build\testrun\unitTest\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorNonIngestNodeTests_741A4555102E93A1-001\tempDir-005\GeoLite2-City.mmdb: The process cannot access the file because it is being used by another process.

   C:\Users\jenkins\workspace\elastic+elasticsearch+6.8+multijob-windows-compatibility\modules\ingest-geoip\build\testrun\unitTest\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorNonIngestNodeTests_741A4555102E93A1-001\tempDir-005\GeoLite2-Country.mmdb: java.nio.file.FileSystemException: C:\Users\jenkins\workspace\elastic+elasticsearch+6.8+multijob-windows-compatibility\modules\ingest-geoip\build\testrun\unitTest\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorNonIngestNodeTests_741A4555102E93A1-001\tempDir-005\GeoLite2-Country.mmdb: The process cannot access the file because it is being used by another process.

   C:\Users\jenkins\workspace\elastic+elasticsearch+6.8+multijob-windows-compatibility\modules\ingest-geoip\build\testrun\unitTest\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorNonIngestNodeTests_741A4555102E93A1-001\tempDir-005: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+6.8+multijob-windows-compatibility\modules\ingest-geoip\build\testrun\unitTest\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorNonIngestNodeTests_741A4555102E93A1-001\tempDir-005
   C:\Users\jenkins\workspace\elastic+elasticsearch+6.8+multijob-windows-compatibility\modules\ingest-geoip\build\testrun\unitTest\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorNonIngestNodeTests_741A4555102E93A1-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+6.8+multijob-windows-compatibility\modules\ingest-geoip\build\testrun\unitTest\J1\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorNonIngestNodeTests_741A4555102E93A1-001

	at __randomizedtesting.SeedInfo.seed([741A4555102E93A1]:0)
	at org.apache.lucene.util.IOUtils.rm(IOUtils.java:318)
	at org.apache.lucene.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:216)
	at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

That other process needs to stop using those files. What a file hog

**Comment by davidkyle** [comment]
Reading the surrounding tickets I see actual problem is that the [muting of GeoIpProcessorNonIngestNodeTests#testLazyLoading](https://github.com/elastic/elasticsearch/commit/14d74eb30b11f0534925f1b2b9b2098c3421b69e) on Windows had not been backported to 6.8. 

The test is not expected to work on Windows due to the way the OS holds onto memory mapped files (see #29001). `GeoIpProcessorNonIngestNodeTests` was probably failing because the files created by `GeoIpProcessorNonIngestNodeTests` were leaking into that test. Muting `GeoIpProcessorNonIngestNodeTests#testLazyLoading` in dc42f23f1705d6340fda03cfe452511a5b463db9 closes this issue.
