### ISSUE TITLE
[CI] Matrix builds running OpenJDK12 fail with "Unsupported class file major version 56"

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#37371]
The Java Matrix builds appear to be failing, with the failure:
```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 56
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:158)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:146)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:284)
	at org.elasticsearch.xpack.test.feature_aware.FeatureAwareCheck.checkClass(FeatureAwareCheck.java:138)
	at org.elasticsearch.xpack.test.feature_aware.FeatureAwareCheck$1.visitFile(FeatureAwareCheck.java:78)
	at org.elasticsearch.xpack.test.feature_aware.FeatureAwareCheck$1.visitFile(FeatureAwareCheck.java:73)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2801)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2873)
	at org.elasticsearch.xpack.test.feature_aware.FeatureAwareCheck.checkDirectories(FeatureAwareCheck.java:73)
	at org.elasticsearch.xpack.test.feature_aware.FeatureAwareCheck.main(FeatureAwareCheck.java:47)
```

So far this appears to only be happening on builds with `ES_RUNTIME_JAVA=openjdk12`.

Links:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=openjdk12,nodes=virtual&&linux/172/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk12,nodes=virtual&&linux/172/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk12,nodes=virtual&&linux/173/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=openjdk12,nodes=virtual&&linux/173/console

This often presents with the failure message `Execution failed for task ':x-pack:plugin:ccr:featureAwareCheck'.`, but I don't think it's directly related to CCR and at least once has had the failure message `Execution failed for task ':x-pack:plugin:monitoring:featureAwareCheck'.`

**Comment by atorok** [comment]
Reproducible wiht : 
```
./gradlew featureAwareCheck -Druntime.java=12
```
