### ISSUE TITLE
auth: basic auth if credentials in LDAP backend changed

### ISSUE THREAD

**Issue by Alufolie303** [elastic/elasticsearch#37406]
**Elasticsearch version** (`bin/elasticsearch --version`): Version: 6.5.0, Build: default/deb/816e6f6/2018-11-09T18:58:36.352602Z, JVM: 1.8.0_191

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "1.8.0_191"

**OS version** (`uname -a` if on a Unix-like system):
Linux 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
With active Kibana/ Elasticsearch session and after changing account credentials in LDAP backend basic auth comes up in the Kibana Webinterface, instead of the expected Kibana login interface. I don't know if there is a LDAP Sync or something similar, to be sure the old credentials are not cached, wait 24h after changing the password in the backend. Maybe someone knows the correct behaviour or can give a link to the code/ documentation.

I'm just using LDAP auth. Maybe someone can check if AD auth is also affected.

expected behavior:
Asking for username/ password in Kibana UI.

actual behavior:
Prompting for username/ password in basic auth popup.

<details>
  <summary>LDAP Config:</summary>

```
xpack.security.authc.realms:
    realm1:
        type: native
        order: 0
        enabled: true

    realm2:
        type: ldap
        order: 1
        enabled: true
        url: "ldaps://ldap.example.com:636"
        bind_dn: "cn=Public,dc=example,dc=com"
        bind_password: password
        user_search:
            base_dn: "ou=people,ou=de,dc=example,dc=com"
            attribute: uid
```

</details>

**Steps to reproduce**:
1. Authenticate to Elasticsearch/ Kibana and close your browser
2. Change Password in LDAP authentication backend
4. wait some time for LDAP resync ( to be sure wait >24h)
3. re-open Kibana in your browser
4. Basic-Auth prompt comes up

**Provide logs (if relevant)**:
<details>
  <summary>elasticsearch debug log entries</summary>

```
[2019-01-14T09:00:21,850][DEBUG][o.e.x.s.a.l.LdapRealm    ] [ES-NODE] Exception occurred during authenticate for ldap/realm2
com.unboundid.ldap.sdk.LDAPBindException: invalid credentials
        at com.unboundid.ldap.sdk.LDAPConnection.bind(LDAPConnection.java:2273) ~[unboundid-ldapsdk-4.0.8.jar:4.0.8]
        at com.unboundid.ldap.sdk.LDAPConnectionPool.bindAndRevertAuthentication(LDAPConnectionPool.java:1619) ~[unboundid-ldapsdk-4.0.8.jar:4.0.8]
        at org.elasticsearch.xpack.security.authc.ldap.support.LdapUtils$1.lambda$doRun$0(LdapUtils.java:136) ~[x-pack-security-6.5.0.jar:6.5.0]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
        at org.elasticsearch.xpack.security.authc.ldap.support.LdapUtils.privilegedConnect(LdapUtils.java:75) ~[x-pack-security-6.5.0.jar:6.5.0]
        at org.elasticsearch.xpack.security.authc.ldap.support.LdapUtils$1.doRun(LdapUtils.java:136) [x-pack-security-6.5.0.jar:6.5.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) [elasticsearch-6.5.0.jar:6.5.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.5.0.jar:6.5.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[2019-01-14T09:00:21,869][WARN ][o.e.x.s.a.AuthenticationService] [ES-NODE] Authentication to realm realm2 failed - authenticate failed (Caused by LDAPException(resultCode=49 (invalid credentials), errorMessage='invalid credentials', ldapSDKVersion=4.0.8, revision=28812))
[2019-01-14T09:00:21,869][DEBUG][r.suppressed             ] [ES-NODE] path: /_xpack/security/_authenticate, params: {}
org.elasticsearch.ElasticsearchSecurityException: unable to authenticate user [username] for REST request [/_xpack/security/_authenticate]
        at org.elasticsearch.xpack.core.security.support.Exceptions.authenticationError(Exceptions.java:18) ~[?:?]
        at org.elasticsearch.xpack.core.security.authc.DefaultAuthenticationFailureHandler.createAuthenticationError(DefaultAuthenticationFailureHandler.java:161) ~[?:?]
        at org.elasticsearch.xpack.core.security.authc.DefaultAuthenticationFailureHandler.failedAuthentication(DefaultAuthenticationFailureHandler.java:89) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$AuditableRestRequest.authenticationFailed(AuthenticationService.java:573) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.consumeUser(AuthenticationService.java:363) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$consumeToken$14(AuthenticationService.java:301) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60) ~[elasticsearch-6.5.0.jar:6.5.0]
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43) ~[elasticsearch-6.5.0.jar:6.5.0]
        at org.elasticsearch.xpack.core.common.IteratingActionListener.onResponse(IteratingActionListener.java:115) ~[?:?]
        at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$consumeToken$11(AuthenticationService.java:286) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60) ~[elasticsearch-6.5.0.jar:6.5.0]
        at org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealm.lambda$authenticateWithCache$4(CachingUsernamePasswordRealm.java:172) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60) [elasticsearch-6.5.0.jar:6.5.0]
        at org.elasticsearch.xpack.security.authc.ldap.LdapRealm$LdapSessionActionListener.onFailure(LdapRealm.java:277) [x-pack-security-6.5.0.jar:6.5.0]
        at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:50) [elasticsearch-6.5.0.jar:6.5.0]
        at org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:42) [elasticsearch-6.5.0.jar:6.5.0]
        at org.elasticsearch.xpack.security.authc.ldap.support.LdapUtils$1.onFailure(LdapUtils.java:142) [x-pack-security-6.5.0.jar:6.5.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:708) [elasticsearch-6.5.0.jar:6.5.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-6.5.0.jar:6.5.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```
</details>

**Comment by Alufolie303** [comment]
Elasticsearch behaviour seems to be correct. 
Issue recreated at Kibana repo -> [https://github.com/elastic/kibana/issues/28665](url)

Sorry for circumstances.
