### ISSUE TITLE
IndexShardRetentionLeaseTests.testCommit fails reproducibly

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#37420]
This test fails reproducibly in master, even though the first failure happened in one of the feature branches.

```
./gradlew :server:unitTest \
  -Dtests.seed=4959C1A2083CBDC5 \
  -Dtests.class=org.elasticsearch.index.shard.IndexShardRetentionLeaseTests \
  -Dtests.method="testCommit" \
  -Dtests.security.manager=true \
  -Dtests.locale=th \
  -Dtests.timezone=Europe/Kaliningrad \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

exception

```
  1> [2019-01-14T15:49:16,484][INFO ][o.e.i.s.IndexShardRetentionLeaseTests] [testCommit] before test
  1> [2019-01-14T15:49:18,272][INFO ][o.e.i.s.IndexShardRetentionLeaseTests] [testCommit] after test
  2> REPRODUCE WITH: ./gradlew :server:unitTest -Dtests.seed=4959C1A2083CBDC5 -Dtests.class=org.elasticsearch.index.shard.IndexShardRetentionLeaseTests -Dtests.method="testCommit" -Dtests.security.manager=true -Dtests.locale=th -Dtests.timezone=Europe/Kaliningrad -Dcompiler.java=11 -Druntime.java=8
ERROR   2.21s | IndexShardRetentionLeaseTests.testCommit <<< FAILURES!
   > Throwable #1: java.lang.IllegalArgumentException: Should specify at least one expected element
   >    at __randomizedtesting.SeedInfo.seed([4959C1A2083CBDC5:1648025D25B01DED]:0)
   >    at org.hamcrest.collection.IsIterableContainingInOrder$MatchSeries.<init>(IsIterableContainingInOrder.java:46)
   >    at org.hamcrest.collection.IsIterableContainingInOrder.matchesSafely(IsIterableContainingInOrder.java:23)
   >    at org.hamcrest.collection.IsIterableContainingInOrder.matchesSafely(IsIterableContainingInOrder.java:14)
   >    at org.hamcrest.TypeSafeDiagnosingMatcher.matches(TypeSafeDiagnosingMatcher.java:55)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:12)
   >    at org.elasticsearch.index.shard.IndexShardRetentionLeaseTests.testCommit(IndexShardRetentionLeaseTests.java:164)
   >    at java.lang.Thread.run(Thread.java:748)
  2> NOTE: leaving temporary files on disk at: /Users/alr/devel/elastic/elasticsearch/elasticsearch/server/build/testrun/unitTest/J0/temp/org.elasticsearch.index.shard.IndexShardRetentionLeaseTests_4959C1A2083CBDC5-001
  2> NOTE: test params are: codec=Asserting(Lucene80): {}, docValues:{}, maxPointsInLeafNode=1028, maxMBSortInHeap=5.426271818735822, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@2fe6b6f6), locale=th, timezone=Europe/Kaliningrad
  2> NOTE: Mac OS X 10.14.2 x86_64/Oracle Corporation 1.8.0_171 (64-bit)/cpus=8,threads=1,free=412495640,total=514850816
  2> NOTE: All tests run in this JVM: [IndexShardRetentionLeaseTests]
Completed [1/1] in 3.59s, 1 test, 1 error <<< FAILURES!
```

This test was added in #37375

**Comment by davidkyle** [comment]
I hit this in a PR build and have muted the test in 1abe5df09c7635175e0b6216bb58563d6c879eac (master)

**Comment by markharwood** [comment]
Reproduces on 6.x too
