### ISSUE TITLE
SQL: exception triggered by subselect

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#37424]
[Adding it for later verification, once subselects are implemented.]

This query: `SELECT "COL" FROM (SELECT 1 AS "COL") AS "CHECKTOP" LIMIT 1` will trigger an error answer:
```{"error":{"root_cause":[{"type":"sql_illegal_argument_exception","reason":"Encountered a bug; LocalExec[COL{c}#843=1] is a LocalExec but is not empty"}],"type":"sql_illegal_argument_exception","reason":"Encountered a bug; LocalExec[COL{c}#843=1] is a LocalExec but is not empty"},"status":500}``` with exception:

```
Server error [Server encountered an error [Encountered a bug; LocalExec[COL{c}#12=1] is a LocalExec but is not empty]. [SqlIllegalArgumentException[Encountered a bug; LocalExec[COL{c}#12=1] is a LocalExec but is not empty]
        at org.elasticsearch.xpack.sql.planner.QueryFolder$PropagateEmptyLocal.rule(QueryFolder.java:544)
        at org.elasticsearch.xpack.sql.tree.Node.lambda$transformUp$11(Node.java:196)
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:190)
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:196)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:569)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:565)
        at org.elasticsearch.xpack.sql.rule.RuleExecutor$Transformation.<init>(RuleExecutor.java:82)
        at org.elasticsearch.xpack.sql.rule.RuleExecutor.executeWithInfo(RuleExecutor.java:158)
        at org.elasticsearch.xpack.sql.rule.RuleExecutor.execute(RuleExecutor.java:130)
        at org.elasticsearch.xpack.sql.planner.QueryFolder.fold(QueryFolder.java:84)
        at org.elasticsearch.xpack.sql.planner.Planner.foldPlan(Planner.java:38)
        at org.elasticsearch.xpack.sql.planner.Planner.plan(Planner.java:28)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$physicalPlan$4(SqlSession.java:153)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$optimizedPlan$3(SqlSession.java:149)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.xpack.sql.session.SqlSession.preAnalyze(SqlSession.java:141)
        at org.elasticsearch.xpack.sql.session.SqlSession.analyzedPlan(SqlSession.java:103)
        at org.elasticsearch.xpack.sql.session.SqlSession.optimizedPlan(SqlSession.java:149)
        at org.elasticsearch.xpack.sql.session.SqlSession.physicalPlan(SqlSession.java:153)
        at org.elasticsearch.xpack.sql.session.SqlSession.sqlExecutable(SqlSession.java:162)
        at org.elasticsearch.xpack.sql.session.SqlSession.sql(SqlSession.java:157)
        at org.elasticsearch.xpack.sql.execution.PlanExecutor.sql(PlanExecutor.java:85)
        at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.operation(TransportSqlQueryAction.java:82)
        [...]
```

**Comment by bpintea** [comment]
One more instance, probably similar cause:
```
SELECT {fn CONVERT({fn TRUNCATE({fn EXTRACT(YEAR FROM "Custom SQL Query"."now()")},0)}, SQL_BIGINT)} AS "yr_now()_ok"
FROM (
  select now()
) "Custom SQL Query"
GROUP BY {fn CONVERT({fn TRUNCATE({fn EXTRACT(YEAR FROM "Custom SQL Query"."now()")},0)}, SQL_BIGINT)}
```

triggers 

`[Elastic][EsODBC 8.0.0(7.0.0-alpha2-29-g28e5616+,u,d) Driver]sql_illegal_argument_exception: Encountered a bug; LocalExec[now(){c}#975=2019-02-12T14:48:36Z] is a LocalExec but is not empty`

**Comment by bpintea** [comment]
This has been fixed in the meantime and works with current master.
