### ISSUE TITLE
[CI] SplitIndexIT.testSplitFromOneToN failure in master

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#37468]
Console Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1275/console
Couldn't manage to reproduce locally (50+ iterations)

```
REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=568A8B3288557B06 \
  -Dtests.class=org.elasticsearch.action.admin.indices.create.SplitIndexIT \
  -Dtests.method="testSplitFromOneToN" \
  -Dtests.security.manager=true \
  -Dtests.locale=fr-LU \
  -Dtests.timezone=Australia/Currie \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Failure is spotted here:
```
  1> [2019-01-15T21:21:21,957][WARN ][o.e.t.TransportService   ] [node_sm0] Received response for a request that has timed out, sent [38425ms] ago, timed out [8405ms] ago, action [internal:coordination/fault_detection/follower_check], node [{node_sd1}{suLYoyJ8TVmQPCsTS6DG_Q}{3BSo_m2YRrqi9SbAtsr0ew}{127.0.0.1}{127.0.0.1:35565}], id [860]
  1> [2019-01-15T21:21:21,957][WARN ][o.e.t.TransportService   ] [node_sd1] Received response for a request that has timed out, sent [38222ms] ago, timed out [8204ms] ago, action [internal:coordination/fault_detection/leader_check], node [{node_sm0}{fdm-Qc70SiuX7EbUp1I4qg}{LvasTfxJToCOlq2tgL1S-Q}{127.0.0.1}{127.0.0.1:39281}], id [359]
  1> [2019-01-15T21:21:21,957][WARN ][o.e.t.TransportService   ] [node_sm0] Received response for a request that has timed out, sent [15810ms] ago, timed out [800ms] ago, action [cluster:monitor/nodes/stats[n]], node [{node_sd2}{EWE7Xj-BT-q2DhKqNYipBg}{fj2xWHPmQN6Gt3CbsP1nEA}{127.0.0.1}{127.0.0.1:42509}], id [862]
  1> [2019-01-15T21:21:21,959][WARN ][o.e.t.TransportService   ] [node_sm0] Received response for a request that has timed out, sent [38625ms] ago, timed out [8605ms] ago, action [internal:coordination/fault_detection/follower_check], node [{node_sd2}{EWE7Xj-BT-q2DhKqNYipBg}{fj2xWHPmQN6Gt3CbsP1nEA}{127.0.0.1}{127.0.0.1:42509}], id [859]
  1> [2019-01-15T21:21:21,960][WARN ][o.e.t.TransportService   ] [node_sm0] Received response for a request that has timed out, sent [38625ms] ago, timed out [8605ms] ago, action [internal:coordination/fault_detection/follower_check], node [{node_sd3}{FK5iNOB1TVmbfPcm6WmDpw}{nZIzyt23S6iMmx3THufTaQ}{127.0.0.1}{127.0.0.1:33985}], id [858]
  1> [2019-01-15T21:21:21,960][WARN ][o.e.t.TransportService   ] [node_sd3] Received response for a request that has timed out, sent [38427ms] ago, timed out [8405ms] ago, action [internal:coordination/fault_detection/leader_check], node [{node_sm0}{fdm-Qc70SiuX7EbUp1I4qg}{LvasTfxJToCOlq2tgL1S-Q}{127.0.0.1}{127.0.0.1:39281}], id [285]
  1> [2019-01-15T21:21:21,960][WARN ][o.e.t.TransportService   ] [node_sd2] Received response for a request that has timed out, sent [38423ms] ago, timed out [8405ms] ago, action [internal:coordination/fault_detection/leader_check], node [{node_sm0}{fdm-Qc70SiuX7EbUp1I4qg}{LvasTfxJToCOlq2tgL1S-Q}{127.0.0.1}{127.0.0.1:39281}], id [324]
  1> [2019-01-15T21:21:21,980][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [source/oee_L_jKQc-4dsHzKFhzGw] deleting index
  1> [2019-01-15T21:21:21,980][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [first_split/e6DYeEH2Qw-buoUzVEqdvw] deleting index
  1> [2019-01-15T21:21:21,984][WARN ][o.e.i.IndicesService     ] [node_sd1] [source/oee_L_jKQc-4dsHzKFhzGw] failed to delete index
  1> org.elasticsearch.env.ShardLockObtainFailedException: [source][0]: obtaining shard lock timed out after 0ms
  1> 	at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:726) ~[main/:?]
  1> 	at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:645) ~[main/:?]
  1> 	at org.elasticsearch.env.NodeEnvironment.lockAllForIndex(NodeEnvironment.java:591) ~[main/:?]
  1> 	at org.elasticsearch.env.NodeEnvironment.deleteIndexDirectorySafe(NodeEnvironment.java:544) ~[main/:?]
  1> 	at org.elasticsearch.indices.IndicesService.deleteIndexStoreIfDeletionAllowed(IndicesService.java:750) ~[main/:?]
  1> 	at org.elasticsearch.indices.IndicesService.deleteIndexStore(IndicesService.java:737) ~[main/:?]
  1> 	at org.elasticsearch.indices.IndicesService.removeIndex(IndicesService.java:641) ~[main/:?]
  1> 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.deleteIndices(IndicesClusterStateService.java:301) ~[main/:?]
  1> 	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:235) ~[main/:?]
  1> 	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$6(ClusterApplierService.java:488) ~[main/:?]
  1> 	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_192]
  1> 	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:485) [main/:?]
  1> 	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:472) [main/:?]
  1> 	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:422) [main/:?]
  1> 	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:166) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) [main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
  1> [2019-01-15T21:21:22,014][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
  1> [2019-01-15T21:21:22,016][WARN ][o.e.i.c.IndicesClusterStateService] [node_sd1] [[first_split][4]] marking and sending shard failed due to [failed recovery]
  1> org.elasticsearch.indices.recovery.RecoveryFailedException: [first_split][4]: Recovery failed on {node_sd1}{suLYoyJ8TVmQPCsTS6DG_Q}{3BSo_m2YRrqi9SbAtsr0ew}{127.0.0.1}{127.0.0.1:35565}
  1> 	at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$9(IndexShard.java:2246) ~[main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660) [main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
  1> Caused by: org.elasticsearch.index.IndexNotFoundException: no such index [first_split]
  1> 	at org.elasticsearch.cluster.metadata.MetaData.getIndexSafe(MetaData.java:651) ~[main/:?]
  1> 	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:229) ~[main/:?]
  1> 	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:686) ~[main/:?]
  1> 	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:311) ~[main/:?]
  1> 	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:211) ~[main/:?]
  1> 	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:143) ~[main/:?]
  1> 	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[main/:?]
  1> 	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660) ~[main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) ~[main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) ~[main/:?]
  1> 	... 3 more
  1> [2019-01-15T21:21:22,022][INFO ][o.e.a.a.i.c.SplitIndexIT ] [testSplitFromOneToN] [SplitIndexIT#testSplitFromOneToN]: cleaned up after test
  1> [2019-01-15T21:21:22,022][INFO ][o.e.a.a.i.c.SplitIndexIT ] [testSplitFromOneToN] after test
FAILURE 40.0s J7 | SplitIndexIT.testSplitFromOneToN <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: ResizeResponse failed - index creation acked but not all shards were started
   > 	at __randomizedtesting.SeedInfo.seed([568A8B3288557B06:9C7F27B00D00F934]:0)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:125)
   > 	at org.elasticsearch.action.admin.indices.create.SplitIndexIT.splitToN(SplitIndexIT.java:203)
   > 	at org.elasticsearch.action.admin.indices.create.SplitIndexIT.testSplitFromOneToN(SplitIndexIT.java:98)
   > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jakelandis** [comment]
Closing this failure. This test was never muted and has no intake or periodic test failures in the past 2 months. There was 1 PR test failure, but it looked related to the PR itself. This is not reproducible and if it repeats again then the test should be muted and a new issue should be logged.

**Comment by Shaybs** [comment]
I just got the same error.
