### ISSUE TITLE
[CI] LegacyNestedObjectMapperTests failure in 6.5

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#37469]
Console log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.5+intake/285/console
Cannot reproduce locally (50 iterations).

```
REPRODUCE WITH: ./gradlew :server:test \
  -Dtests.seed=835CBE1899A649C1 \
  -Dtests.class=org.elasticsearch.index.mapper.LegacyNestedObjectMapperTests \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=Etc/UTC \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :server:test \
  -Dtests.seed=835CBE1899A649C1 \
  -Dtests.class=org.elasticsearch.index.mapper.LegacyNestedObjectMapperTests \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=Etc/UTC \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Leaked threads:
```
12:55:39   2> INFO: Starting to interrupt leaked threads:
12:55:39    > 	at __randomizedtesting.SeedInfo.seed([835CBE1899A649C1]:0)Throwable #2: com.carrotsearch.randomizedtesting.ThreadLeakError: There are still zombie threads that couldn't be terminated:
12:55:39    >    1) Thread[id=882, name=elasticsearch[node_s_0][__mock_network_thread][T#1], state=RUNNABLE, group=TGRP-LegacyNestedObjectMapperTests]
12:55:39   2>    1) Thread[id=882, name=elasticsearch[node_s_0][__mock_network_thread][T#1], state=RUNNABLE, group=TGRP-LegacyNestedObjectMapperTests]
12:55:39    >         at java.net.PlainSocketImpl.socketAccept(Native Method)
12:55:39   2>    2) Thread[id=883, name=elasticsearch[node_s_0][__mock_network_thread][T#2], state=RUNNABLE, group=TGRP-LegacyNestedObjectMapperTests]
12:55:39    >         at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
12:55:39   2> Jan 15, 2019 10:55:39 AM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
12:55:39   2> SEVERE: There are still zombie threads that couldn't be terminated:
12:55:39    >         at java.net.ServerSocket.implAccept(ServerSocket.java:545)
12:55:39    >         at java.net.ServerSocket.accept(ServerSocket.java:513)
12:55:39    >         at org.elasticsearch.mocksocket.MockServerSocket.access$101(MockServerSocket.java:32)
12:55:39   2>    1) Thread[id=882, name=elasticsearch[node_s_0][__mock_network_thread][T#1], state=RUNNABLE, group=TGRP-LegacyNestedObjectMapperTests]
12:55:39   2>         at java.net.PlainSocketImpl.socketAccept(Native Method)
12:55:39    >         at org.elasticsearch.mocksocket.MockServerSocket.lambda$accept$0(MockServerSocket.java:53)
12:55:39    >         at org.elasticsearch.mocksocket.MockServerSocket$$Lambda$1480/1195405039.run(Unknown Source)
12:55:39    >         at java.security.AccessController.doPrivileged(Native Method)
12:55:39    >         at org.elasticsearch.mocksocket.MockServerSocket.accept(MockServerSocket.java:53)
12:55:39   2>         at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
12:55:39    >         at org.elasticsearch.transport.MockTcpTransport$MockChannel.accept(MockTcpTransport.java:285)
12:55:39   2>         at java.net.ServerSocket.implAccept(ServerSocket.java:545)
12:55:39    >         at org.elasticsearch.transport.MockTcpTransport$1.doRun(MockTcpTransport.java:131)
12:55:39   2>         at java.net.ServerSocket.accept(ServerSocket.java:513)
12:55:39   2>         at org.elasticsearch.mocksocket.MockServerSocket.access$101(MockServerSocket.java:32)
12:55:39    >         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
12:55:39    >         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:55:39    >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:55:39   2>         at org.elasticsearch.mocksocket.MockServerSocket.lambda$accept$0(MockServerSocket.java:53)
12:55:39    >         at java.lang.Thread.run(Thread.java:748)
12:55:39   2>         at org.elasticsearch.mocksocket.MockServerSocket$$Lambda$1480/1195405039.run(Unknown Source)
12:55:39    >    2) Thread[id=883, name=elasticsearch[node_s_0][__mock_network_thread][T#2], state=RUNNABLE, group=TGRP-LegacyNestedObjectMapperTests]
12:55:39    >         at java.net.PlainSocketImpl.socketAccept(Native Method)
12:55:39    >         at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
12:55:39    >         at java.net.ServerSocket.implAccept(ServerSocket.java:545)
12:55:39   2>         at java.security.AccessController.doPrivileged(Native Method)
12:55:39    >         at java.net.ServerSocket.accept(ServerSocket.java:513)
12:55:39   2>         at org.elasticsearch.mocksocket.MockServerSocket.accept(MockServerSocket.java:53)
12:55:39    >         at org.elasticsearch.mocksocket.MockServerSocket.access$101(MockServerSocket.java:32)
12:55:39    >         at org.elasticsearch.mocksocket.MockServerSocket.lambda$accept$0(MockServerSocket.java:53)
12:55:39   2>         at org.elasticsearch.transport.MockTcpTransport$MockChannel.accept(MockTcpTransport.java:285)
12:55:39    >         at org.elasticsearch.mocksocket.MockServerSocket$$Lambda$1480/1195405039.run(Unknown Source)
12:55:39   2>         at org.elasticsearch.transport.MockTcpTransport$1.doRun(MockTcpTransport.java:131)
12:55:39   2>         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
12:55:39   2>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:55:39    >         at java.security.AccessController.doPrivileged(Native Method)
12:55:39   2>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:55:39   2>         at java.lang.Thread.run(Thread.java:748)
12:55:39   2>    2) Thread[id=883, name=elasticsearch[node_s_0][__mock_network_thread][T#2], state=RUNNABLE, group=TGRP-LegacyNestedObjectMapperTests]
12:55:39    >         at org.elasticsearch.mocksocket.MockServerSocket.accept(MockServerSocket.java:53)
12:55:39   2>         at java.net.PlainSocketImpl.socketAccept(Native Method)
12:55:39    >         at org.elasticsearch.transport.MockTcpTransport$MockChannel.accept(MockTcpTransport.java:285)
12:55:39   2>         at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
12:55:39    >         at org.elasticsearch.transport.MockTcpTransport$1.doRun(MockTcpTransport.java:131)
12:55:39    >         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
12:55:39    >         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:55:39    >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:55:39    >         at java.lang.Thread.run(Thread.java:748)
12:55:39    > 	at __randomizedtesting.SeedInfo.seed([835CBE1899A649C1]:0)
12:55:39 Completed [610/1160] on J2 in 28.21s, 1 test, 2 errors <<< FAILURES!
12:55:39 
12:55:39   2>         at java.net.ServerSocket.implAccept(ServerSocket.java:545)
12:55:39 Suite: org.elasticsearch.common.bytes.BytesArrayTests
12:55:39   2>         at java.net.ServerSocket.accept(ServerSocket.java:513)
12:55:39   2>         at org.elasticsearch.mocksocket.MockServerSocket.access$101(MockServerSocket.java:32)
12:55:39 Completed [611/1160] on J2 in 0.01s, 31 tests, 31 skipped
12:55:39   2>         at org.elasticsearch.mocksocket.MockServerSocket.lambda$accept$0(MockServerSocket.java:53)
12:55:39 
12:55:39   2>         at org.elasticsearch.mocksocket.MockServerSocket$$Lambda$1480/1195405039.run(Unknown Source)
12:55:39   2>         at java.security.AccessController.doPrivileged(Native Method)
12:55:39 Suite: org.elasticsearch.deps.joda.SimpleJodaTests
12:55:39   2>         at org.elasticsearch.mocksocket.MockServerSocket.accept(MockServerSocket.java:53)
12:55:39 Completed [612/1160] on J2 in 0.00s, 24 tests, 24 skipped
12:55:39   2>         at org.elasticsearch.transport.MockTcpTransport$MockChannel.accept(MockTcpTransport.java:285)
12:55:39 
12:55:39 Suite: org.elasticsearch.search.aggregations.bucket.FilterTests
12:55:39   2>         at org.elasticsearch.transport.MockTcpTransport$1.doRun(MockTcpTransport.java:131)
12:55:39   2>         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
12:55:39 Completed [613/1160] on J2 in 0.00s, 7 tests, 7 skipped
12:55:39 
12:55:39   2>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:55:39 Suite: org.elasticsearch.common.unit.DistanceUnitTests
12:55:39 Completed [614/1160] on J2 in 0.00s, 5 tests, 5 skipped
12:55:39   2>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:55:39 
12:55:39   2>         at java.lang.Thread.run(Thread.java:748)
12:55:39 Suite: org.elasticsearch.index.analysis.CustomNormalizerTests
12:55:39   2> REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=835CBE1899A649C1 -Dtests.class=org.elasticsearch.index.mapper.LegacyNestedObjectMapperTests -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=Etc/UTC -Dcompiler.java=11 -Druntime.java=8
12:55:39 Completed [615/1160] on J2 in 0.00s, 6 tests, 6 skipped
12:55:39   2> REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=835CBE1899A649C1 -Dtests.class=org.elasticsearch.index.mapper.LegacyNestedObjectMapperTests -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=Etc/UTC -Dcompiler.java=11 -Druntime.java=8
12:55:39 
```

**Comment by tlrx** [comment]
This looks very similar to #37543 and [other issues](https://github.com/elastic/elasticsearch/search?q=__mock_network_thread&type=Issues)

**Comment by talevy** [comment]
closing in favor of: https://github.com/elastic/elasticsearch/issues/37469
