### ISSUE TITLE
Terms in _id Field are not correct UTF-8

### ISSUE THREAD

**Issue by cgoller** [elastic/elasticsearch#37525]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.0

**Plugins installed**: none

**JVM version** (`java -version`): 1.8.0_126

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**:

It seems that terms in the _id field are not correct UTF-8. This causes problems when Lucene tries to generate a char[] or a String for these terms eg, with UnicodeUtil.UTF8toUTF16.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create Index

PUT my_index
{
  "settings": {
    "number_of_shards" : 1
  },
    "mappings" : {
    "_doc": {
      "properties" : {
        "body" : {
          "type" : "text", 
          "index" : true, 
          "analyzer": "standard",  
          "search_analyzer": "standard",
          "index_options": "offsets"
        }
      }
    }
  }
}

 2. Insert Document

PUT /my_index/_doc/1
{
  "body":  "aaa bbb ccc ddd eee fff ggg"
}

 3. Use UnifiedHighlighter with a query that enforces Analysis-Mode and a filter for the _id fields

GET /my_index/_search
{
    "query" : {
        "bool": {
          "must": [ 
            {
            "span_containing" : {
              "little" : {
                "span_term" : { "body" : "ccc" }
              },
              "big" : {
                "span_near" : {
                    "clauses" : [
                        { "span_term" : { "body" : "bbb" } },
                        { "span_term" : { "body" : "ddd" } }
                    ],
                    "slop" : 5,
                    "in_order" : true
                }
              }
            }
            }
          ],
			    "filter": [
            	{ "term": { "_id": "1" } }
          ]	
        }
      },
	 "_source": {
	    "includes": ["body"],
	    "excludes": []
	  },
     "highlight" : {
      "fields": {
		  "body": {
			"type": "unified",
			"number_of_fragments" : 10,
			"fragment_size" : 100
			}
		},
    "require_field_match": false
	}
}

**Provide logs (if relevant)**:

Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at org.apache.lucene.util.UnicodeUtil.UTF8toUTF16(UnicodeUtil.java:602) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
	at org.apache.lucene.util.UnicodeUtil.UTF8toUTF16(UnicodeUtil.java:626) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
	at org.apache.lucene.util.automaton.DaciukMihovAutomatonBuilder.build(DaciukMihovAutomatonBuilder.java:303) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
	at org.apache.lucene.util.automaton.Automata.makeStringUnion(Automata.java:581) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
	at org.apache.lucene.search.uhighlight.MemoryIndexOffsetStrategy.buildCombinedAutomaton(MemoryIndexOffsetStrategy.java:67) ~[lucene-highlighter-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:02:19]
	at org.apache.lucene.search.uhighlight.MemoryIndexOffsetStrategy.<init>(MemoryIndexOffsetStrategy.java:57) ~[lucene-highlighter-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:02:19]
	at org.apache.lucene.search.uhighlight.UnifiedHighlighter.getOffsetStrategy(UnifiedHighlighter.java:866) ~[lucene-highlighter-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:02:19]
	at org.apache.lucene.search.uhighlight.CustomUnifiedHighlighter.getFieldHighlighter(CustomUnifiedHighlighter.java:149) ~[elasticsearch-6.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:02:19]
	at org.apache.lucene.search.uhighlight.UnifiedHighlighter.highlightFieldsAsObjects(UnifiedHighlighter.java:574) ~[lucene-highlighter-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:02:19]
	at org.apache.lucene.search.uhighlight.CustomUnifiedHighlighter.highlightField(CustomUnifiedHighlighter.java:107) ~[elasticsearch-6.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:02:19]
	at org.elasticsearch.search.fetch.subphase.highlight.UnifiedHighlighter.highlight(UnifiedHighlighter.java:128) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.search.fetch.subphase.highlight.HighlightPhase.hitExecute(HighlightPhase.java:110) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:159) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:413) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:388) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.search.SearchService.access$100(SearchService.java:121) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:339) ~[elasticsearch-6.5.0.jar:6.5.0]
	... 9 more

**Comment by jimczi** [comment]
Thanks for reporting @cgoller, I agree that the analysis should not be needed for this kind of query (`span_containing`) but this is a different bug. Thanks for pointing the Lucene [issue](https://issues.apache.org/jira/browse/LUCENE-8637). 
Regarding the issue with the `_id` field, I think we should be able to filter queries that target this field when we highlight.  This field uses a special encoding that is not compatible with the re-analysis of the unified highlighter and there should be no use case where highlighting the `_id` is required. 
As a workaround before the fix you can set `require_field_match` to true in the highlighter option. With this option activated, only the queries that target the highlighted field (`body`) are extracted from the main query.

**Comment by cgoller** [comment]
Thanks. My recommendation for the customer is to use an additional field for the document id. I guess they use filters on the id only for test purposes anyway.

From my Lucene perspective: I consider it quite risky to to use terms with such a special encoding that actually breaks Lucene APIs.
