### ISSUE TITLE
Java client API - toXContent() on aggregations from search response causes exception

### ISSUE THREAD

**Issue by Ghost93** [elastic/elasticsearch#37636]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.4, running on cloud.elastic.co (using AWS eu-west-1 region)

**Description of the problem including expected versus actual behavior**:
Hi, 
The following code produces JsonMappingException:
```java
SearchResponse searchResponse = this.highLevelRestClient.search(searchRequest);
XContentBuilder builder = CborXContent.contentBuilder(); 
searchResponse.getAggregations().toXContent(builder, ToXContent.EMPTY_PARAMS);
ObjectMapper cborObjectMapper = new ObjectMapper(new CBORFactory());
JsonNode jsonNode = cborObjectMapper.readTree(builder.bytes().streamInput());
```

If we don't call ```getAggregations()``` and read ```searchResponse``` directly it works, but we only need the aggregations :v: 

The same code works when running on ```getHits()``` (in relevant queries).

```searchRequest``` (in json form, I spared the ~100 LOC of creating it):
```json
{
    "size": 0,
    "query": {
        "bool": {
            "must": [
                {
                    "range": {
                        "censored_field_2": {
                            "from": "2018-05-31T21:00:00.000Z",
                            "to": null,
                            "include_lower": true,
                            "include_upper": true,
                            "boost": 1.0
                        }
                    }
                },
                {
                    "term": {
                        "censored_field_1": {
                            "value": 460563723,
                            "boost": 1.0
                        }
                    }
                }
            ],
            "adjust_pure_negative": true,
            "boost": 1.0
        }
    },
    "aggregations": {
        "agg1": {
            "date_histogram": {
                "field": "censored_field_2",
                "interval": "1M",
                "offset": 0,
                "order": {
                    "_key": "asc"
                },
                "keyed": false,
                "min_doc_count": 0
            },
            "aggregations": {
                "avg_censored_field_3": {
                    "avg": {
                        "field": "censored_field_3"
                    }
                },
                "avg_censored_field_4": {
                    "avg": {
                        "field": "censored_field_4"
                    }
                },
                "avg_censored_field_5": {
                    "avg": {
                        "field": "censored_field_5"
                    }
                },
                "censored_field_6": {
                    "value_count": {
                        "field": "censored_field_6"
                    }
                },
                "censored_field_7": {
                    "filter": {
                        "exists": {
                            "field": "censored_field_7.point",
                            "boost": 1.0
                        }
                    },
                    "aggregations": {
                        "points": {
                            "top_hits": {
                                "from": 0,
                                "size": 100,
                                "version": false,
                                "explain": false,
                                "_source": {
                                    "includes": [
                                        "censored_field_7.point"
                                    ],
                                    "excludes": []
                                }
                            }
                        }
                    }
                }
            }
        },
        "agg2": {
            "terms": {
                "field": "censored_field_8.city",
                "size": 5,
                "min_doc_count": 1,
                "shard_min_doc_count": 0,
                "show_term_doc_count_error": false,
                "order": [
                    {
                        "_count": "desc"
                    },
                    {
                        "_key": "asc"
                    }
                ]
            }
        }
    }
}
```

Thanks

**Comment by danielmitterdorfer** [comment]
@Ghost93 can you please include the exact stack trace including the exception message in your report?

**Comment by Ghost93** [comment]
@danielmitterdorfer 
Sure.

```java
com.fasterxml.jackson.core.JsonGenerationException: Can not write a field name, expecting a value
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1897)
	at com.fasterxml.jackson.dataformat.cbor.CBORGenerator.writeFieldName(CBORGenerator.java:329)
	at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.writeFieldName(JsonXContentGenerator.java:183)
	at org.elasticsearch.common.xcontent.XContentBuilder.field(XContentBuilder.java:246)
	at org.elasticsearch.common.xcontent.XContentBuilder.startObject(XContentBuilder.java:222)
	at org.elasticsearch.search.aggregations.Aggregations.toXContent(Aggregations.java:119)
	at com.github.ghost93.dal.elasticsearch.ElasticDalImpl.getAgg(DalImpl.java:1961)
	at com.github.ghost93.dal.elasticsearch.ElasticDalImpl.getData(DalImpl.java:1757)
	at TEST.main(TEST.java:40)
````

**Comment by Ghost93** [comment]
btw, maybe I should mention my ```pom.xml``` dependency versions:

```xml
<dependency>
      <groupId>org.elasticsearch</groupId>
      <artifactId>elasticsearch</artifactId>
      <version>6.2.4</version>
    </dependency>
    <dependency>
      <groupId>org.elasticsearch.client</groupId>
      <artifactId>elasticsearch-rest-high-level-client</artifactId>
      <version>6.2.4</version>
    </dependency>
    <dependency>
      <groupId>org.elasticsearch.client</groupId>
      <artifactId>elasticsearch-rest-client</artifactId>
      <version>6.2.4</version>
    </dependency>
    <dependency>
      <groupId>org.elasticsearch.client</groupId>
      <artifactId>x-pack-transport</artifactId>
      <version>6.2.4</version>
    </dependency>
```

**Comment by javanna** [comment]
hi @Ghost93 , you are printing out a partial object, rather than the whole search response, meaning that you end up trying to output `"aggregations" : {}` which needs to be wrapped in curly brackets. If you wish to output only the aggs part properly, you need to first call `builder.startObject();` and `builder.endObject()` at the end. Or even better, `Aggregations` implements `ToXContentFragment` which indicates that the output is not a complete json object. You can use `XContentHelper#toXContent` which detects that and adds the wrapper anonymous object when necessary.
