### ISSUE TITLE
Faraday::ConnectionFailed: read function returned funny value

### ISSUE THREAD

**Issue by swzensar8** [elastic/elasticsearch#37630]
I am getting this error for large(1 MB) data sync from one application to rails application and after sync I am doing elasticsearch indexing. Previously I used ruby 2.3.3 and rails 4.2.7 it was working fine with large data also but now I have updated ruby to 2.5.1 and rails 4.2.10 and its giving "Faraday::ConnectionFailed: read function returned funny value" error while indexing large data.

**Tried with listed version of elasticsearch gem**

elasticsearch (6.1.0, 2.0.2) 
elasticsearch-api (6.1.0, 2.0.2) 
elasticsearch-model (6.0.0, 2.0.1) 
elasticsearch-rails (6.0.0, 2.0.1)
elasticsearch-transport (6.1.0, 2.0.2)

**Also tried with faraday and faraday_middleware gem update**

faraday (0.15.4, 0.9.2) 
faraday_middleware (0.12.2)

Adaptor and version is: gem 'patron', '~> 0.4.18'

**Details of gemfile.lock**
elasticsearch (2.0.2)
  elasticsearch-api (= 2.0.2)
  elasticsearch-transport (= 2.0.2)
elasticsearch-api (2.0.2)
  multi_json
elasticsearch-model (2.0.1)
  activesupport (> 3)
  elasticsearch (~> 2)
  hashie
elasticsearch-rails (2.0.1)
elasticsearch-transport (2.0.2)
  faraday
  multi_json

faraday (0.9.2)
  multipart-post (>= 1.2, < 3)
faraday_middleware (0.12.2)
  faraday (>= 0.7.4, < 1.0)

googleauth (0.5.1)
  faraday (~> 0.9)

oauth2 (1.0.0)
  faraday (>= 0.8, < 0.10)
  jwt (~> 1.0)
  multi_json (~> 1.3)
  multi_xml (~> 0.5)
  rack (~> 1.2)
omniauth (1.8.1)
  hashie (>= 3.4.6, < 3.6.0)
  rack (>= 1.6.2, < 3)
omniauth-oauth2 (1.2.0)
  faraday (>= 0.8, < 0.10)
  multi_json (~> 1.3)
  oauth2 (~> 1.0)
  omniauth (~> 1.2)

signet (0.7.3)
  addressable (~> 2.3)
  faraday (~> 0.9) 

**Also tried using the ideas from**
https://stackoverflow.com/questions/33565919/searchkick-with-elasticsearch-returns-faradayconnectionfailed-execution-expi

Elasticsearch::Model.client = Elasticsearch::Client.new(log: logging, adapter: :patron, url: ENV['ELASTICSEARCH_URL'], retry_on_failure: true, transport_options: {request: {timeout: 250}})

**Error detail:**

[Faraday::ConnectionFailed] Cannot connect to {:scheme=>"https", :user=>nil, :password=>nil, :host=>"example.com", :path=>"", :port=>443, :protocol=>"https"} after 4 tries
rake aborted!
Faraday::ConnectionFailed: read function returned funny value
/www/rails/app/models/concerns/searchable.rb:34:in `index_document'
/www/rails/lib/drupal/drupal_changes.rb:21:in `block (2 levels) in process'
/www/rails/lib/drupal/drupal_changes.rb:12:in `block in process'
/www/rails/lib/drupal/drupal_changes.rb:9:in `loop'
/www/rails/lib/drupal/drupal_changes.rb:9:in `process'
/www/rails/lib/tasks/drupal_change_syncronizer.rake:106:in `block (2 levels) in <top (required)>'
/www/rails/lib/tasks/drupal_change_syncronizer.rake:115:in `block (3 levels) in <top (required)>'
/www/rails/lib/tasks/drupal_change_syncronizer.rake:13:in `if_not_syncing'
/www/rails/lib/tasks/drupal_change_syncronizer.rake:112:in `block (2 levels) in <top (required)>'
/opt/rubies/ruby-2.5.1/bin/bundle:30:in `block in <main>'
/opt/rubies/ruby-2.5.1/bin/bundle:22:in `<main>'
Patron::Error: read function returned funny value

https://stackoverflow.com/questions/54266205/faradayconnectionfailed-read-function-returned-funny-value#54266205

Please help. Thanks in advance.

**Comment by swzensar8** [comment]
I have updated patron gem to latest version 0.13.1 its working.
