### ISSUE TITLE
Stackoverflow Crash

### ISSUE THREAD

**Issue by davidt99** [elastic/elasticsearch#37637]
**Elasticsearch version**: 6.5.4

**Plugins installed**: []

**JVM version**:
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**OS version**:
Linux name 4.4.0-138-generic #&#x2060;164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

The elasticsearch service crashed, the logs indicate stackoverflow

**Steps to reproduce**:

The elasticsearch is used with kibana, not sure what query caused it. I looked at the kibana logs, didn't see any noticable query.

**Provide logs (if relevant)**:
```
[2019-01-20T09:57:20,198][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [name] fatal error in thread [Thread-23366], exiting
java.lang.StackOverflowError: null
        at org.apache.lucene.util.automaton.RegExp.parseSimpleExp(RegExp.java:1109) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseCharClassExp(RegExp.java:1092) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseComplExp(RegExp.java:1080) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseRepeatExp(RegExp.java:1049) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1042) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1044) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        ...
```

**Comment by danielmitterdorfer** [comment]
This is caused by a regex query that is too complex (related to issues like https://github.com/elastic/elasticsearch/issues/28344). I suggest you lower the soft limit on the maximum length of a regex query by lowering the index setting [`index.max_regex_length`](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/index-modules.html#dynamic-index-settings) from its default value of 1000 (characters). This will make the respective query fail early instead of causing problems on the server-side. The specific failure should then point you to the query and allow you to fix it.

**Comment by YakobovLior** [comment]
Hey @danielmitterdorfer,
Can you instruct how to change this setting? is is possible through cluster settings API? Or should I write it in elasticsearch.yml and restart each node in the cluster?

Thanks,
Liot

**Comment by danielmitterdorfer** [comment]
Please ask question in the future in the forum on Discuss instead of closed issues. If you follow the doc link you'll see that this is a dynamic **index** setting (**not** a cluster setting) so you can change this via the index settings API.

**Comment by YakobovLior** [comment]
Hey again @danielmitterdorfer ,
Thank you for the response, next time I will open a new issue for this case.
I do have a last question though - if this is an index setting, that means that I need to run:
1. PUT /_settings (to apply on all indices) 
2. Include this setting in all of my templates?

Thanks again,
Lior
