### ISSUE TITLE
[CI] NullPointerException in PutMappingRequestTests

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#37654]
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/195/

	java.lang.NullPointerException
		at __randomizedtesting.SeedInfo.seed([CC504FAEFA4AB2B3:ED387AB673ED5269]:0)
		at org.elasticsearch.client.indices.PutMappingRequestTests.assertEqualInstances(PutMappingRequestTests.java:59)
		at org.elasticsearch.client.indices.PutMappingRequestTests.assertEqualInstances(PutMappingRequestTests.java:29)
		at org.elasticsearch.test.AbstractXContentTestCase$XContentTester.test(AbstractXContentTestCase.java:137)
		at org.elasticsearch.test.AbstractXContentTestCase.testFromXContent(AbstractXContentTestCase.java:196)

Reproduces with : 

    ./gradlew :client:rest-high-level:unitTest -Dtests.seed=CC504FAEFA4AB2B3 -Dtests.class=org.elasticsearch.client.indices.PutMappingRequestTests -Dtests.method="testFromXContent" -Dtests.security.manager=true -Dtests.locale=es-MX -Dtests.timezone=America/Havana -Dcompiler.java=11 -Druntime.java=8

**Comment by spinscale** [comment]
I muted this test in 7173aa213ab219bbac37de417cf6fe1246592467 due to some failures in feature branches and PRs

**Comment by cbuescher** [comment]
Got a fix ready at #37665

**Comment by jtibshirani** [comment]
Thanks @cbuescher for fixing this! Next time I'll run some local tests with the `@Repeat` annotation you pointed me to.
