### ISSUE TITLE
Null pointer exception when nested top_hits inside terms

### ISSUE THREAD

**Issue by BastianHofmann** [elastic/elasticsearch#37650]
I'm using the official Docker image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4

**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.4

**Plugins installed**: []

**JVM version** (`java -version`): 11.0.1

**OS version** (`uname -a` if on a Unix-like system): Linux 267b34f6bf59 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

When having a nested `top_hits` aggregation inside a nested `terms` aggregation inside a `children` aggregation, I'm getting a `null_pointer_exception`. I expect to get a valid response.

**Steps to reproduce**:

 1. create mapping

```
PUT http://localhost:9200/test

{
    "mappings": {
        "doc": {
            "properties": {
                "docType": {
                    "type": "text"
                },
                "userId": {
                    "type": "long"
                },
                "userName": {
                    "type": "text"
                },
                "title": {
                    "type": "text"
                },
                "joinField": {
                    "type": "join",
                    "relations": {
                        "post": "comment"
                    }
                }
            }
        }
    }
}
```
 2. insert example post

```
PUT http://localhost:9200/test/doc/1
{
    "joinField": {
        "name": "post"
    },
    "docType": "post",
    "title": "Example Post"
}
```

 3. insert comment
```
PUT http://localhost:9200/test/doc/2?routing=1

{
	"joinField": {
		"name": "comment",
		"parent": "1"
	},
	"userId": 22,
	"userName": "John Doe",
	"title": "Random comment",
	"docType": "comment"
}
```

4. Perform search

```
POST http://localhost:9200/test/doc/_search

{
	"aggs": {
		"to-comment": {
			"children": {
				"type": "comment"
			},
			"aggs": {
				"by-user": {
					"terms": {
						"field": "userId"
					},
					"aggs": {
						"data": {
							"top_hits": {
								"size": 1
							}
						}
					}	
				}
			}
		}
	},
	"query": {
		"bool": {
			"filter": [
				{
					"term": {
						"docType": "post"
					}
				}
			]
		}
	}
}
```

Response:
```
{
    "took": 10,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 4,
        "skipped": 0,
        "failed": 1,
        "failures": [
            {
                "shard": 3,
                "index": "test",
                "node": "0RbF1bIbRO-yN5C1m-HXPA",
                "reason": {
                    "type": "null_pointer_exception",
                    "reason": null
                }
            }
        ]
    },
    "hits": {
        "total": 0,
        "max_score": null,
        "hits": []
    },
    "aggregations": {
        "to-comment": {
            "doc_count": 0,
            "by-user": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 0,
                "buckets": []
            }
        }
    }
}
```

It works if I remove the query, but in the actual hits I want to get all the posts only. It also works if I remove the terms aggregations, but I want to filter the posts by other queries (e.g. match on title).

**Comment by jimczi** [comment]
Thanks for reporting @BastianHofmann and thanks for investigating @danielmitterdorfer .
The NPE occurs because we expect that query and aggregation match the same document when we try to rebuild a scorer (breadth_first mode of the `terms` aggregation). This is not the case here since the `children` aggregator switches the context of the query to documents that don't necessarily match the parent query. This is not an issue when the score of documents is not needed but the `top_docs` aggregation accesses the `_score` by default to sort the hits. 
A simple workaround is to add a `sort` criteria to the `top_docs` aggregation:
````

"top_hits": {
  "sort": ["_doc"]
}
````

I don't know what is the expectation here but if the score of a child document should be equal to the score of its parent we would need to save each parent's score during the collection. Considering that this would require 4 bytes per document I don't think we should allow the `_score` to be used in a sub-aggregation of a `children` agg, it is too costly. Instead we could simply throw an error that explain why the score cannot be used.

**Comment by BastianHofmann** [comment]
@jimczi thank you for the provided workaround. This would certainly work for my use case, since I don't care which document is returned by the top_hits aggregation (all of the documents in the bucket will have the same user).
An error that explains why the score cannot be used would certainly be helpful.

**Comment by polyfractal** [comment]
https://github.com/elastic/elasticsearch/pull/43028 should "fix" this, but in the meantime master no longer appears to NPE.  It doesn't return the documents in the hits, but you don't get an exception anymore either:

```json
{
  "took" : 7,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 0.0,
    "hits" : [
      {
        "_index" : "test",
        "_id" : "1",
        "_score" : 0.0,
        "_source" : {
          "joinField" : {
            "name" : "post"
          },
          "docType" : "post",
          "title" : "Example Post"
        }
      }
    ]
  },
  "aggregations" : {
    "to-comment" : {
      "doc_count" : 1,
      "by-user" : {
        "doc_count_error_upper_bound" : 0,
        "sum_other_doc_count" : 0,
        "buckets" : [
          {
            "key" : 22,
            "doc_count" : 1,
            "data" : {
              "hits" : {
                "total" : {
                  "value" : 0,
                  "relation" : "eq"
                },
                "max_score" : null,
                "hits" : [ ]
              }
            }
          }
        ]
      }
    }
  }
}
```

**Comment by salvatore-campagna** [comment]
I tried to reproduce this on current master (8.4.0) and I don't see any NPE. Also I don't see any results. @BastianHofmann what is the valid response you expect?

**Comment by martijnvg** [comment]
When running in ES with assertions enabled the follow assertion error is thrown in [BestBucketsDeferringCollector](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/search/aggregations/bucket/BestBucketsDeferringCollector.java#L193):

```
[ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [runTask-0] fatal error in thread [elasticsearch[runTask-0][search][T#1]], exiting java.lang.AssertionError
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.BestBucketsDeferringCollector.prepareSelectedBuckets(BestBucketsDeferringCollector.java:193)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.DeferableBucketAggregator.prepareSubAggs(DeferableBucketAggregator.java:100)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildSubAggsForBuckets(BucketsAggregator.java:173)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildSubAggsForAllBuckets(BucketsAggregator.java:238)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.terms.NumericTermsAggregator.access$000(NumericTermsAggregator.java:48)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.terms.NumericTermsAggregator$StandardTermsResultStrategy.buildSubAggs(NumericTermsAggregator.java:277)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.terms.NumericTermsAggregator$StandardTermsResultStrategy.buildSubAggs(NumericTermsAggregator.java:257)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.terms.NumericTermsAggregator$ResultStrategy.buildAggregations(NumericTermsAggregator.java:177)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.terms.NumericTermsAggregator.buildAggregations(NumericTermsAggregator.java:117)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildSubAggsForBuckets(BucketsAggregator.java:176)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildAggregationsForSingleBucket(BucketsAggregator.java:306)
»       at org.elasticsearch.join@8.5.0-SNAPSHOT/org.elasticsearch.join.aggregations.ParentToChildrenAggregator.buildAggregations(ParentToChildrenAggregator.java:43)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.Aggregator.buildTopLevel(Aggregator.java:154)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.AggregationPhase.execute(AggregationPhase.java:112)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:86)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:464)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:627)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.SearchService.lambda$executeQueryPhase$2(SearchService.java:489)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:892)
»       at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
»       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
»       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
»       at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by martijnvg** [comment]
Actually NPE is still occurring:

```
java.lang.NullPointerException: Cannot invoke "org.apache.lucene.search.Scorer.iterator()" because "scorer" is null
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.BestBucketsDeferringCollector.prepareSelectedBuckets(BestBucketsDeferringCollector.java:177)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.DeferableBucketAggregator.prepareSubAggs(DeferableBucketAggregator.java:100)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildSubAggsForBuckets(BucketsAggregator.java:173)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildSubAggsForAllBuckets(BucketsAggregator.java:238)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.terms.NumericTermsAggregator.access$000(NumericTermsAggregator.java:48)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.terms.NumericTermsAggregator$StandardTermsResultStrategy.buildSubAggs(NumericTermsAggregator.java:277)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.terms.NumericTermsAggregator$StandardTermsResultStrategy.buildSubAggs(NumericTermsAggregator.java:257)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.terms.NumericTermsAggregator$ResultStrategy.buildAggregations(NumericTermsAggregator.java:177)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.terms.NumericTermsAggregator.buildAggregations(NumericTermsAggregator.java:117)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildSubAggsForBuckets(BucketsAggregator.java:176)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildAggregationsForSingleBucket(BucketsAggregator.java:306)
        at org.elasticsearch.join@8.5.0-SNAPSHOT/org.elasticsearch.join.aggregations.ParentToChildrenAggregator.buildAggregations(ParentToChildrenAggregator.java:43)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.Aggregator.buildTopLevel(Aggregator.java:154)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.aggregations.AggregationPhase.execute(AggregationPhase.java:112)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:86)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:464)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:627)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.search.SearchService.lambda$executeQueryPhase$2(SearchService.java:489)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:892)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

The NPE occurred with the following reproduction (had to update the original reproduction to 8.x reality):

```
PUT test
{
    "mappings": {
        "properties": {
            "docType": {
                "type": "text"
            },
            "userId": {
                "type": "long"
            },
            "userName": {
                "type": "text"
            },
            "title": {
                "type": "text"
            },
            "joinField": {
                "type": "join",
                "relations": {
                    "post": "comment"
                }
            }
        }
    }
}

PUT /test/_doc/1
{
    "joinField": {
        "name": "post"
    },
    "docType": "post",
    "title": "Example Post"
}

PUT /test/_doc/2?routing=1
{
	"joinField": {
		"name": "comment",
		"parent": "1"
	},
	"userId": 22,
	"userName": "John Doe",
	"title": "Random comment",
	"docType": "comment"
}

POST /test/_search
{
	"aggs": {
		"to-comment": {
			"children": {
				"type": "comment"
			},
			"aggs": {
				"by-user": {
					"terms": {
						"field": "userId"
					},
					"aggs": {
						"data": {
							"top_hits": {
								"size": 1
							}
						}
					}	
				}
			}
		}
	},
	"query": {
		"bool": {
			"filter": [
				{
					"term": {
						"docType": "post"
					}
				}
			]
		}
	}
}
Response:

{
    "took": 10,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 4,
        "skipped": 0,
        "failed": 1,
        "failures": [
            {
                "shard": 3,
                "index": "test",
                "node": "0RbF1bIbRO-yN5C1m-HXPA",
                "reason": {
                    "type": "null_pointer_exception",
                    "reason": null
                }
            }
        ]
    },
    "hits": {
        "total": 0,
        "max_score": null,
        "hits": []
    },
    "aggregations": {
        "to-comment": {
            "doc_count": 0,
            "by-user": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 0,
                "buckets": []
            }
        }
    }
}
```
