### ISSUE TITLE
[CI]: PutRoleRequestTests.testSerializationBetweenV63AndV70 fails reproducibly

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#37662]
This one fails reproducibly on master for me

```
./gradlew :x-pack:plugin:core:unitTest -Dtests.seed=B39F3326811270C6 -Dtests.class=org.elasticsearch.xpack.core.security.action.role.PutRoleRequestTests -Dtests.method="testSerializationBetweenV63AndV70" -Dtests.security.manager=true -Dtests.locale=pl -Dtests.timezone=Europe/Budapest -Dcompiler.java=11 -Druntime.java=8
```

results in

```
  1> [2019-01-21T15:57:01,255][INFO ][o.e.x.c.s.a.r.PutRoleRequestTests] [testSerializationBetweenV63AndV70] before test
  1> [2019-01-21T15:57:01,818][INFO ][o.e.x.c.s.a.r.PutRoleRequestTests] [testSerializationBetweenV63AndV70] after test
  2> REPRODUCE WITH: ./gradlew :x-pack:plugin:core:unitTest -Dtests.seed=B39F3326811270C6 -Dtests.class=org.elasticsearch.xpack.core.security.action.role.PutRoleRequestTests -Dtests.method="testSerializationBetweenV63AndV70" -Dtests.security.manager=true -Dtests.locale=pl -Dtests.timezone=Europe/Budapest -Dcompiler.java=11 -Druntime.java=8
ERROR   0.64s | PutRoleRequestTests.testSerializationBetweenV63AndV70 <<< FAILURES!
   > Throwable #1: java.lang.UnsupportedOperationException: can't read named writeable from StreamInput
   >    at __randomizedtesting.SeedInfo.seed([B39F3326811270C6:8E2C96AC0D2309A1]:0)
   >    at org.elasticsearch.common.io.stream.StreamInput.readNamedWriteable(StreamInput.java:878)
   >    at org.elasticsearch.xpack.core.security.authz.privilege.ConditionalClusterPrivileges.lambda$static$0(ConditionalClusterPrivileges.java:42)
   >    at org.elasticsearch.common.io.stream.StreamInput.readArray(StreamInput.java:733)
   >    at org.elasticsearch.xpack.core.security.authz.privilege.ConditionalClusterPrivileges.readArray(ConditionalClusterPrivileges.java:53)
   >    at org.elasticsearch.xpack.core.security.action.role.PutRoleRequest.readFrom(PutRoleRequest.java:173)
   >    at org.elasticsearch.xpack.core.security.action.role.PutRoleRequestTests.testSerializationBetweenV63AndV70(PutRoleRequestTests.java:89)
   >    at java.lang.Thread.run(Thread.java:748)
  2> NOTE: leaving temporary files on disk at: /Users/alr/devel/elastic/elasticsearch/elasticsearch/x-pack/plugin/core/build/testrun/unitTest/J0/temp/org.elasticsearch.xpack.core.security.action.role.PutRoleRequestTests_B39F3326811270C6-001
  2> NOTE: test params are: codec=Asserting(Lucene80): {}, docValues:{}, maxPointsInLeafNode=1200, maxMBSortInHeap=6.471625680380947, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@70d19c9d), locale=pl, timezone=Europe/Budapest
  2> NOTE: Mac OS X 10.14.2 x86_64/Oracle Corporation 1.8.0_171 (64-bit)/cpus=8,threads=1,free=382720096,total=514850816
  2> NOTE: All tests run in this JVM: [PutRoleRequestTests]
Completed [1/1] in 2.22s, 1 test, 1 error <<< FAILURES!
```

there is also another test failure in CI where this test failed: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1395/console

**Comment by spinscale** [comment]
I muted these in master and 6.x
