### ISSUE TITLE
[CI] Cannot load security plugin under 8FIPS

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#37682]
`org.elasticsearch.xpack.security.LocalStateSecurity` cannot be loaded due to FIPS mode:

```
Caused by: java.security.KeyStoreException: FIPS mode: KeyStore must be from provider BCFIPS
	at sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(KeyManagerFactoryImpl.java:67)
	at javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:256)
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8fips,nodes=virtual&&linux/195/console

**Comment by jkakavas** [comment]
This fails because #36846 added a JKS keystore to be used as a keystore in the node settings.
