### ISSUE TITLE
[CI] AsyncTwoPhaseIndexerTests.testStateMachine failure

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#37695]
Looks like a transient failure due to a slow start that could be fixed through a barrier

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/365/console 
```
Expected: <INDEXING>
     but: was <STARTED>
	at __randomizedtesting.SeedInfo.seed([FF9B9C9FA14FF48D:9332E084D9C2EAE3]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.core.indexing.AsyncTwoPhaseIndexerTests.testStateMachine(AsyncTwoPhaseIndexerTests.java:204)
```

**Comment by colings86** [comment]
Please remember to add relevant labels to all issues created. At the very least this should include an area label since without an area label issues may fall through the cracks and be missed by teams.

**Comment by pgomulka** [comment]
Reproduce line
```
/gradlew :x-pack:plugin:core:unitTest -Dtests.seed=FF9B9C9FA14FF48D -Dtests.class=org.elasticsearch.xpack.core.indexing.AsyncTwoPhaseIndexerTests -Dtests.method="testStateMachine" -Dtests.security.manager=true  -Dtests.locale=ko-KR -Dtests.timezone=Zulu -Dcompiler.java=11 -Druntime.java=8 
```
