### ISSUE TITLE
[CI] MasterDisruptionIT.testFailWithMinimumMasterNodesConfigured

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#37699]
Not sure if the Lucene upgrade affected the test suite but there are two failures in
MasterDisruptionIT.testFailWithMinimumMasterNodesConfigured which looks important enough to not mute it as it deserves immediate attention.

```
Expected: "node_t2"
     but: was "node_t1"
	at __randomizedtesting.SeedInfo.seed([4E701D1D163A434D:1CB79551CE20161A]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.discovery.AbstractDisruptionTestCase.lambda$assertMaster$2(AbstractDisruptionTestCase.java:202)
```
See 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1420/console 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian/197/console

**Comment by costin** [comment]
Another failure at https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1429/console
