### ISSUE TITLE
FilterAggregatorTests#testRandom fails with an assertion error.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#37743]
Stack trace:

```
FAILURE 3.01s | FilterAggregatorTests.testRandom <<< FAILURES!
> Throwable #1: java.lang.AssertionError
>    at __randomizedtesting.SeedInfo.seed([B3115850EE7E9E4F:C15D7D5F5F1E283C]:0)
>    at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregatorTests.testRandom(FilterAggregatorTests.java:102)
>    at java.lang.Thread.run(Thread.java:748)
```

Reproduction line:

```
./gradlew :server:unitTest -Dtests.seed=B3115850EE7E9E4F \
    -Dtests.class=org.elasticsearch.search.aggregations.bucket.filter.FilterAggregatorTests \
    -Dtests.method="testRandom"
```

The failure may be due to the recent PR #36020.

**Comment by spinscale** [comment]
I just muted this one, failed locally for me as well.

**Comment by polyfractal** [comment]
Will take a look!
