### ISSUE TITLE
[CI] DynamicMappingIT testMappingsPropagatedToMasterNodeImmediately fails

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#37816]
`DynamicMappingIT testMappingsPropagatedToMasterNodeImmediately` failed in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1152/console

The error is:

```
12:34:53 FAILURE 0.22s J6 | DynamicMappingIT.testMappingsPropagatedToMasterNodeImmediately <<< FAILURES!
12:34:53    > Throwable #1: java.lang.AssertionError
12:34:53    > 	at __randomizedtesting.SeedInfo.seed([C13A3C57FAFE9674:4CE8785023961AD4]:0)
12:34:53    > 	at org.elasticsearch.index.mapper.DynamicMappingIT.assertMappingsHaveField(DynamicMappingIT.java:61)
12:34:53    > 	at org.elasticsearch.index.mapper.DynamicMappingIT.testMappingsPropagatedToMasterNodeImmediately(DynamicMappingIT.java:75)
12:34:53    > 	at java.lang.Thread.run(Thread.java:748)
```

I could not reproduce this locally using:

```
./gradlew :server:integTest \
  -Dtests.seed=C13A3C57FAFE9674 \
  -Dtests.class=org.elasticsearch.index.mapper.DynamicMappingIT \
  -Dtests.method="testMappingsPropagatedToMasterNodeImmediately" \
  -Dtests.security.manager=true \
  -Dtests.locale=cs-CZ \
  -Dtests.timezone=Europe/Monaco \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

**Comment by droberts195** [comment]
I muted this test for 6.x in 1bcc7b1004c1c336caaea87af0ecd30b06f05da6

**Comment by droberts195** [comment]
This also affects master.

This failure occurred in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1493/console:

```
13:18:38 FAILURE 0.61s J4 | DynamicMappingIT.testMappingsPropagatedToMasterNodeImmediately <<< FAILURES!
13:18:38    > Throwable #1: java.lang.AssertionError
13:18:38    > 	at __randomizedtesting.SeedInfo.seed([A491240509B193BC:29436002D0D91F1C]:0)
13:18:38    > 	at org.elasticsearch.index.mapper.DynamicMappingIT.assertMappingsHaveField(DynamicMappingIT.java:70)
13:18:38    > 	at org.elasticsearch.index.mapper.DynamicMappingIT.testMappingsPropagatedToMasterNodeImmediately(DynamicMappingIT.java:84)
13:18:38    > 	at java.lang.Thread.run(Thread.java:748)
```

The repro command for this build was:

```
./gradlew :server:integTest \
  -Dtests.seed=A491240509B193BC \
  -Dtests.class=org.elasticsearch.index.mapper.DynamicMappingIT \
  -Dtests.method="testMappingsPropagatedToMasterNodeImmediately" \
  -Dtests.security.manager=true \
  -Dtests.locale=pt-PT \
  -Dtests.timezone=America/Eirunepe \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

I muted the test for master too in a81931bb2a9c6e2ee260dc8515b8c3b2b2ea3651

**Comment by atorok** [comment]
This reproduced locally for me with a loop: 
```
while ./gradlew :server:integTest -Dtests.seed=6F0955888A93B810 -Dtests.class=org.elasticsearch.index.mapper.DynamicMappingIT  ; do 
        echo  AGAIN
done
```

**Comment by cbuescher** [comment]
> This reproduced locally for me with a loop:

Which branch is this? Asking because the seed which triggerst the behaviour might be different on different branches.

**Comment by cbuescher** [comment]
I get it to fail running in a loop on master with seed `A491240509B193BC:29436002D0D91F1C` maybe 2 out of ten times.

**Comment by dnhatn** [comment]
This test is obsolete since #31140 where an index request with dynamic mapping update no longer requires acking. I pushed https://github.com/elastic/elasticsearch/commit/3ccd4887556726f13ef07ad6ab1733a010018119 to this test. /cc @ywelsch.
