### ISSUE TITLE
[CI] SimpleClusterStateIT testMetadataVersion failed

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#37820]
`SimpleClusterStateIT testMetadataVersion` failed in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1151/console

The error was:

```
12:29:14 FAILURE 0.66s J5 | SimpleClusterStateIT.testMetadataVersion <<< FAILURES!
12:29:14    > Throwable #1: java.lang.AssertionError: 
12:29:14    > Expected: <81L>
12:29:14    >      but: was <82L>
12:29:14    > 	at __randomizedtesting.SeedInfo.seed([1E57DA32C36FCB37:F1520789EF481A64]:0)
12:29:14    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
12:29:14    > 	at org.elasticsearch.cluster.SimpleClusterStateIT.testMetadataVersion(SimpleClusterStateIT.java:126)
12:29:14    > 	at java.lang.Thread.run(Thread.java:748)
```

This did not reproduce for me locally using:

```
./gradlew :server:integTest \
  -Dtests.seed=1E57DA32C36FCB37 \
  -Dtests.class=org.elasticsearch.cluster.SimpleClusterStateIT \
  -Dtests.method="testMetadataVersion" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Latn-ME \
  -Dtests.timezone=NZ \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

**Comment by droberts195** [comment]
The test has been muted in 6.x in 1c3730478d6cbe417e4335f1dd86b4809cc068d8

**Comment by droberts195** [comment]
A very similar error occurred in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1149/consoleText:

```
FAILURE 0.86s J5 | SimpleClusterStateIT.testMetadataVersion <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <84L>
   >      but: was <85L>
   > 	at __randomizedtesting.SeedInfo.seed([C69507D5DD461A67:2990DA6EF161CB34]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.cluster.SimpleClusterStateIT.testMetadataVersion(SimpleClusterStateIT.java:122)
   > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dnhatn** [comment]
I am on it now.

**Comment by droberts195** [comment]
This has just failed on master too, in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/200/console:

```
16:37:08 FAILURE 3.05s J4 | SimpleClusterStateIT.testMetadataVersion <<< FAILURES!
16:37:08    > Throwable #1: java.lang.AssertionError: 
16:37:08    > Expected: <361L>
16:37:08    >      but: was <362L>
16:37:08    > 	at __randomizedtesting.SeedInfo.seed([63FD97398FF731EE:8CF84A82A3D0E0BD]:0)
16:37:08    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
16:37:08    > 	at org.elasticsearch.cluster.SimpleClusterStateIT.testMetadataVersion(SimpleClusterStateIT.java:133)
16:37:08    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:37:08    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:37:08    > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:37:08    > 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
16:37:08    > 	at java.base/java.lang.Thread.run(Thread.java:834)
```

The repro command was:

```
./gradlew :server:integTest \
  -Dtests.seed=63FD97398FF731EE \
  -Dtests.class=org.elasticsearch.cluster.SimpleClusterStateIT \
  -Dtests.method="testMetadataVersion" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-SS \
  -Dtests.timezone=Europe/Andorra \
  -Dcompiler.java=11 \
  -Druntime.java=11
```

I muted the test in master too in 0e36adc35fafbb0a3fb5bfa459f9cb7fac520785
