### ISSUE TITLE
[CI] NoMasterNodeIT testNoMasterActionsWriteMasterBlock failed

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#37823]
`NoMasterNodeIT testNoMasterActionsWriteMasterBlock` failed in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1485/console

The error was:

```
11:09:37 FAILURE 13.4s J3 | NoMasterNodeIT.testNoMasterActionsWriteMasterBlock <<< FAILURES!
11:09:37    > Throwable #1: java.lang.AssertionError
11:09:37    > 	at __randomizedtesting.SeedInfo.seed([35EF03EC1BBFBF36:D6D9FD7B132A51C7]:0)
11:09:37    > 	at org.elasticsearch.cluster.NoMasterNodeIT.testNoMasterActionsWriteMasterBlock(NoMasterNodeIT.java:224)
11:09:37    > 	at java.lang.Thread.run(Thread.java:748)
```

This did not reproduce locally for me using:

```
./gradlew :server:integTest \
  -Dtests.seed=35EF03EC1BBFBF36 \
  -Dtests.class=org.elasticsearch.cluster.NoMasterNodeIT \
  -Dtests.method="testNoMasterActionsWriteMasterBlock" \
  -Dtests.security.manager=true \
  -Dtests.locale=fr \
  -Dtests.timezone=SystemV/EST5EDT \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

**Comment by droberts195** [comment]
I muted the test on master in bd02ca4b7b066de1e77cf9246c5a1674af1ea71a

**Comment by henningandersen** [comment]
I un-muted the test on master in 7487be3d3c9d82960e5a71743f4f3401bf9cfc74.

Examining this, my conclusion is that this test experienced a 10s+ stall in the CI system and that this is the primary cause. 6 other concurrently running tests experienced the same problem and they all seems to be able to run in less than one second. The total run time of the :server:integTest part of the build was around twice of what is normal.

Hoping that CI no longer experience these problems, I un-muted the test.

The concurrently running tests were these:
```
HEARTBEAT J6 PID(22047@elasticsearch-ci-immutable-debian-9-1548326412351234576): 2019-01-24T11:09:30, stalled for 11.2s at: Zen1IT.testZen1NodesJoiningZen2Cluster
HEARTBEAT J1 PID(21977@elasticsearch-ci-immutable-debian-9-1548326412351234576): 2019-01-24T11:09:34, stalled for 11.2s at: SnapshotDisruptionIT.testDisruptionOnSnapshotInitialization
HEARTBEAT J3 PID(21976@elasticsearch-ci-immutable-debian-9-1548326412351234576): 2019-01-24T11:09:34, stalled for 10.3s at: NoMasterNodeIT.testNoMasterActionsWriteMasterBlock
HEARTBEAT J5 PID(21982@elasticsearch-ci-immutable-debian-9-1548326412351234576): 2019-01-24T11:09:36, stalled for 10.9s at: ClusterAllocationExplainIT.testUnassignedReplicaDelayedAllocation
HEARTBEAT J0 PID(21974@elasticsearch-ci-immutable-debian-9-1548326412351234576): 2019-01-24T11:09:36, stalled for 10.8s at: AvgBucketIT (suite)
HEARTBEAT J7 PID(21975@elasticsearch-ci-immutable-debian-9-1548326412351234576): 2019-01-24T11:09:36, stalled for 11.0s at: FunctionScoreIT.testScriptScoresNested
HEARTBEAT J2 PID(22017@elasticsearch-ci-immutable-debian-9-1548326412351234576): 2019-01-24T11:09:36, stalled for 10.8s at: LegacyUpdateMappingIntegrationIT.testUpdateDefaultMappingSettings
```

Please re-open this issue if this test starts failing again.
