### ISSUE TITLE
Force values to be same type as mapping field type

### ISSUE THREAD

**Issue by KongoPL** [elastic/elasticsearch#37865]
**Elasticsearch version** (`bin/elasticsearch --version`): Version: 6.4.2, Build: default/zip/04711c2/2018-09-26T13:34:09.098244Z, JVM: 11.0.2

**Plugins installed**: all defaults

**JVM version** (`java -version`):
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): Windows 10 Home x64

**Description of the problem including expected versus actual behavior**:
I was messing with updating documents by query. I discovered that if we have numeric field in mapping (like long, float or int) and we inserted numeric value as string ("123456" instead of 123456) value is inserted as we give it (123456 or "123456" instead of 123456).
The point is that during writing simple painless script like `ctx._source.myField *= 2` value does not multiply (what happens if we inserted "123456" instead of 123456). In that case I have to cast value to certain type and then I'm able to do math operation (i.e. `ctx._source.myField = Long.parseLong(ctx._source.myField) * 2`).

Also, I saw that this value is really stored as string when we inserted it as "123456" (I had java error about casting problems from string to number. Also JSON response confirms it).

IMHO if mapping says that field is numeric, it should cast value to numeric ("123456" -> 123456) during insert.

**Steps to reproduce**:

```
PUT /xd/
{
    "mappings" : {
        "_doc" : {
            "properties" : {
                "field" : { "type" : "long" }
            }
        }
    }
}

POST /xd/_doc/numeric
{
    "field": 1234567890123
}

POST /xd/_update_by_query
{
  "script": {
    "source": "ctx._source.field *= 2",
    "lang": "painless"
  },
  "query": {
    "term": {
      "_id": "numeric"
    }
  }
}

// Now value is 2469135780246 (OK)

POST /xd/_doc/string
{
    "field": "1234567890123"
}

POST /xd/_update_by_query
{
  "script": {
    "source": "ctx._source.field *= 2",
    "lang": "painless"
  },
  "query": {
    "term": {
      "_id": "string"
    }
  }
}
```

Last one request returns error and ElasticSearch says this:
```
[2019-01-25T15:07:08,168][WARN ][r.suppressed             ] path: /xd/_update_by_query, params: {index=xd}
org.elasticsearch.script.ScriptException: runtime error
        at org.elasticsearch.painless.PainlessScript.convertToScriptException(PainlessScript.java:94) ~[?:?]
        at org.elasticsearch.painless.PainlessScript$Script.execute(ctx._source.field *= 2:12) ~[?:?]
        at org.elasticsearch.painless.ScriptImpl.run(ScriptImpl.java:105) ~[?:?]
        at org.elasticsearch.index.reindex.AbstractAsyncBulkByScrollAction$ScriptApplier.apply(AbstractAsyncBulkByScrollAction.java:819) ~[reindex-6.4.2.jar:6.4.2]
        at org.elasticsearch.index.reindex.AbstractAsyncBulkByScrollAction$ScriptApplier.apply(AbstractAsyncBulkByScrollAction.java:768) ~[reindex-6.4.2.jar:6.4.2]
        at org.elasticsearch.index.reindex.AbstractAsyncBulkByScrollAction.buildBulk(AbstractAsyncBulkByScrollAction.java:216) [reindex-6.4.2.jar:6.4.2]
        at org.elasticsearch.index.reindex.AbstractAsyncBulkByScrollAction.prepareBulkRequest(AbstractAsyncBulkByScrollAction.java:326) [reindex-6.4.2.jar:6.4.2]
        at org.elasticsearch.index.reindex.AbstractAsyncBulkByScrollAction$1.doRun(AbstractAsyncBulkByScrollAction.java:289) [reindex-6.4.2.jar:6.4.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.index.reindex.WorkerBulkByScrollTaskState$RunOnce.doRun(WorkerBulkByScrollTaskState.java:321) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.index.reindex.WorkerBulkByScrollTaskState$DelayedPrepareBulkRequest$1.doRun(WorkerBulkByScrollTaskState.java:257) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) [elasticsearch-6.4.2.jar:6.4.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.4.2.jar:6.4.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: Cannot apply [*] operation to types [java.lang.String] and [java.lang.Integer].
        at org.elasticsearch.painless.DefMath.mul(DefMath.java:228) ~[?:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710) ~[?:?]
        at org.elasticsearch.painless.DefBootstrap$MIC.fallback(DefBootstrap.java:317) ~[?:?]
        at org.elasticsearch.painless.PainlessScript$Script.execute(ctx._source.field *= 2:22) ~[?:?]
        ... 16 more
```

However, this will work (cause I casted this value to long by myself):

```
POST /xd/_update_by_query
{
  "script": {
    "source": "ctx._source.field = Long.parseLong(ctx._source.field) * 2",
    "lang": "painless"
  },
  "query": {
    "term": {
      "_id": "string"
    }
  }
}
```

Thanks for review and for answers!

**Comment by danielmitterdorfer** [comment]
This is expected as you are accessing the `_source` field which is stored *as is* (i.e. how you provided it in your original request) without any coercion. You can prevent that such documents get added to the index by specifying `"coerce": false` in your mapping:

```
PUT /xd/
{
    "mappings" : {
        "_doc" : {
            "properties" : {
                "field" : { 
                     "type" : "long",
                    "coerce": false
                }
            }
        }
    }
}
```

If you then issue:

```

POST /xd/_doc/string
{
    "field": "1234567890123"
}
```

you'll get an error immediately:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "failed to parse field [field] of type [long]"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "failed to parse field [field] of type [long]",
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "Long value passed as String"
    }
  },
  "status" : 400
}
```

If you have any other questions, we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. Thank you!
