### ISSUE TITLE
NestedAggregatorTests.testDoubleNestingMax Fails Reproducibly on Master

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#37873]
The following fails for me on 100% of runs:

```sh
./gradlew :server:unitTest -Dtests.seed=85B26AEC7ADE72D4 -Dtests.class=org.elasticsearch.search.aggregations.bucket.nested.NestedAggregatorTests -Dtests.method="testDoubleNestingMax" -Dtests.security.manager=true -Dtests.locale=es-PA -Dtests.timezone=Africa/Dakar -Dcompiler.java=11 -Druntime.java=8
```

with:

```sh
> Task :server:unitTest
   [junit4] <JUnit4> says aloha! Master seed: 85B26AEC7ADE72D4
==> Test Info: seed=85B26AEC7ADE72D4; jvm=1; suite=1

  1> [2019-01-25T15:42:55,487][INFO ][o.e.s.a.b.n.NestedAggregatorTests] [testDoubleNestingMax] before test
  1> [2019-01-25T15:42:56,343][INFO ][o.e.s.a.b.n.NestedAggregatorTests] [testDoubleNestingMax] after test
  2> REPRODUCE WITH: ./gradlew :server:unitTest -Dtests.seed=85B26AEC7ADE72D4 -Dtests.class=org.elasticsearch.search.aggregations.bucket.nested.NestedAggregatorTests -Dtests.method="testDoubleNestingMax" -Dtests.security.manager=true -Dtests.locale=es-PA -Dtests.timezone=Africa/Dakar -Dcompiler.java=11 -Druntime.java=8
FAILURE 0.90s | NestedAggregatorTests.testDoubleNestingMax <<< FAILURES!
   > Throwable #1: java.lang.AssertionError
   >    at __randomizedtesting.SeedInfo.seed([85B26AEC7ADE72D4:E811D01792C4B519]:0)
   >    at org.elasticsearch.search.aggregations.bucket.nested.NestedAggregatorTests.testDoubleNestingMax(NestedAggregatorTests.java:227)
   >    at java.lang.Thread.run(Thread.java:748)
  2> NOTE: leaving temporary files on disk at: /home/brownbear/src/elasticsearch/server/build/testrun/unitTest/J0/temp/org.elasticsearch.search.aggregations.bucket.nested.NestedAggregatorTests_85B26AEC7ADE72D4-001
  2> NOTE: test params are: codec=Asserting(Lucene80): {_type=PostingsFormat(name=Asserting), _id=PostingsFormat(name=Asserting)}, docValues:{_primary_term=DocValuesFormat(name=Lucene70)}, maxPointsInLeafNode=1163, maxMBSortInHeap=6.667414161248388, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@2990fc36), locale=es-PA, timezone=Africa/Dakar
  2> NOTE: Linux 4.18.0-13-generic amd64/Oracle Corporation 1.8.0_191 (64-bit)/cpus=16,threads=1,free=417625768,total=514850816
  2> NOTE: All tests run in this JVM: [NestedAggregatorTests]
Completed [1/1] in 2.23s, 1 test, 1 failure <<< FAILURES!


> Task :server:unitTest FAILED
Tests with failures:
  - org.elasticsearch.search.aggregations.bucket.nested.NestedAggregatorTests.testDoubleNestingMax

   [junit4] JVM J0:     0.32 ..     3.42 =     3.10s
   [junit4] Execution time total: 3.43 sec.
   [junit4] Tests summary: 1 suite, 1 test, 1 failure


```

**Comment by polyfractal** [comment]
This appears to be another `hasValue()` failure, similar to https://github.com/elastic/elasticsearch/issues/37743.  I'm looking into #37743 right now, will see about fixing this issue next.

Sorry for the noise!
