### ISSUE TITLE
TestClustersPluginIT fails with connection errors

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#37889]
I haven't been able to reproduce the failures locally. This looks similar to #37218, but the failure mode seems different.

Just today, I've seen this test suite fail in CI ~10 times. The test seems to fail on master as well as 6.x.

---

Link to the build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1195

Relevant excerpt from the logs:
```
 Caused by: java.lang.IllegalStateException: Connection attempt to node{::myTestCluster} failed
    	at org.elasticsearch.gradle.testclusters.ElasticsearchNode.lambda$waitForUri$2(ElasticsearchNode.java:163)
    	at org.elasticsearch.gradle.testclusters.ElasticsearchNode.lambda$waitForAllConditions$7(ElasticsearchNode.java:414)
    	... 74 more
    	Suppressed: java.lang.IllegalStateException: Connection attempt to node{::myTestCluster} failed
    		at org.elasticsearch.gradle.testclusters.ElasticsearchNode.lambda$waitForUri$2(ElasticsearchNode.java:163)
    		at org.elasticsearch.gradle.testclusters.ElasticsearchNode.lambda$waitForAllConditions$7(ElasticsearchNode.java:414)
    		at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
    		at org.elasticsearch.gradle.testclusters.ElasticsearchNode.waitForAllConditions(ElasticsearchNode.java:401)
    		at org.elasticsearch.gradle.testclusters.ElasticsearchNode.getHttpSocketURI(ElasticsearchNode.java:229)
    		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
    		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
    		at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76)
    		at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:63)
    		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
    		at build_2kot767fmb696rtvvmg8tn437$_run_closure1$_closure11$_closure16.doCall(/var/lib/jenkins/workspace/elastic+elasticsearch+6.x+intake/buildSrc/src/testKit/testclusters/build.gradle:34)
    		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
    		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
    		at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
    		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
    		at groovy.lang.Closure.call(Closure.java:411)
    		at groovy.lang.Closure.call(Closure.java:427)
    		at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:647)
    		at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:620)
    		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:284)
    		at 
```

**Comment by jtibshirani** [comment]
Perhaps this should be filed in another issue, but I also wanted to note that `BuildExamplePluginsIT#testCurrentExamplePlugin` has been frequently failing with a timeout, often in the same run as a `TestClustersPluginIT` failure.

Link to an example build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+multijob-unix-compatibility/os=fedora/75/console

Excerpt from logs:
```
 Caused by: java.io.FileNotFoundException: /tmp/junit16456469239498008045/build/cluster/integTestCluster node0/elasticsearch-6.6.0-SNAPSHOT/logs/transport.ports (No such file or directory)
    	at org.elasticsearch.gradle.test.NodeInfo.transportUri(NodeInfo.groovy:298)
    	at org.elasticsearch.gradle.test.NodeInfo$transportUri$5.call(Unknown Source)
    	at org.elasticsearch.gradle.test.ClusterConfiguration$_closure2.doCall(ClusterConfiguration.groovy:110)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at org.elasticsearch.gradle.test.ClusterFormationTasks$_configureWaitTask_closure27$_closure48.doCall(ClusterFormationTasks.groovy:715)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	... 53 more
```

**Comment by jtibshirani** [comment]
I temporarily muted both tests in https://github.com/elastic/elasticsearch/commit/24ff23812e730730408c72d44d9f7ea4928d3c91.

**Comment by atorok** [comment]
`BuildExamplePluginsIT` does not use testclusters (yet)  I think the failures in the former were  due to slow infrastructure.  I'm going to unmute it.
