### ISSUE TITLE
TransformIntegrationTests#testSearchTransform can fail with an assertion error

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#37882]
Unfortunately the failure doesn't reproduce for me locally.

---

Link to the build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1189

Command to reproduce: 
```
./gradlew :x-pack:plugin:watcher:unitTest \
  -Dtests.seed=7025F52611D9E3C2 \
  -Dtests.class=org.elasticsearch.xpack.watcher.transform.TransformIntegrationTests \
  -Dtests.method="testSearchTransform" \
  -Dtests.security.manager=true \
  -Dtests.locale=el-CY \
  -Dtests.timezone=US/Michigan \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Relevant excerpt from the logs:
```
09:57:34 FAILURE 1.65s J3 | TransformIntegrationTests.testSearchTransform <<< FAILURES!
09:57:34    > Throwable #1: java.lang.AssertionError: could not find watch [_id2] to trigger
09:57:34    > Expected: is <true>
09:57:34    >      but: was <false>
09:57:34    > 	at __randomizedtesting.SeedInfo.seed([7025F52611D9E3C2:20E5361838A201DD]:0)
09:57:34    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
09:57:34    > 	at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase$TimeWarp.trigger(AbstractWatcherIntegrationTestCase.java:569)
09:57:34    > 	at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase$TimeWarp.trigger(AbstractWatcherIntegrationTestCase.java:559)
09:57:34    > 	at org.elasticsearch.xpack.watcher.transform.TransformIntegrationTests.testSearchTransform(TransformIntegrationTests.java:186)
09:57:34    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jtibshirani** [comment]
Since this test has failed several times in the past month, I muted it in https://github.com/elastic/elasticsearch/commit/455f223c3a8526d7462159ab362754c890d2af6f.

**Comment by jtibshirani** [comment]
I wasn't able to make progress debugging this locally, so I unmuted the test and enabled logging on both master + 6.x.

**Comment by jtibshirani** [comment]
As @jaymode described in #35503, the issue seems to be that after the tests starts, there can be a change in local shard routing, which then causes the watch service to be loaded. This in turn calls `ScheduleTriggerEngineMock#pauseExecution`, which clears all watches that this mock object holds. Subsequent calls to `ScheduleTriggerEngineMock#trigger` then fail to find the requested watches.

Prior to #39277 (where we stopped triggering watches through `TimeWarp`) I'm able to consistently reproduce the error message above if I simulate a change in shard routing, and repeat the test 10 times:

```
--- a/x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/WatcherLifeCycleService.java
+++ b/x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/WatcherLifeCycleService.java
@@ -137,7 +137,7 @@ public class WatcherLifeCycleService implements ClusterStateListener {
             .sorted(Comparator.comparing(ShardRouting::hashCode))
             .collect(Collectors.toList());
 
-        if (previousShardRoutings.get().equals(localAffectedShardRoutings) == false) {
+        if (Math.random() < 0.1 || previousShardRoutings.get().equals(localAffectedShardRoutings) == false) {
             if (watcherService.validate(event.state())) {
                 previousShardRoutings.set(localAffectedShardRoutings);
                 if (state.get() == WatcherState.STARTED) {
```

With #39277, I'm no longer able to reproduce the issue. This is because when we execute a watch through the client, we load it from the index instead of retrieving it from the mock object `ScheduleTriggerEngineMock`.

For this reason, I'm planning to close the issue as 'resolved'. If we see this test fail in the same way again, we can re-open it.
