### ISSUE TITLE
GeoWKTShapeParserTests#testParseGeometryCollection fails with an IllegalArgumentException

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#37894]
This reproduces for me locally with the line below. It seems to only fail on master, and not 6.x.

---

Link to the build:https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+corretto-periodic/ES_BUILD_JAVA=java11,label=amazon/75/

Command to reproduce: 
```
./gradlew :server:unitTest \
  -Dtests.seed=31C073EB0CC10A18 \
  -Dtests.class=org.elasticsearch.common.geo.GeoWKTShapeParserTests \
  -Dtests.method="testParseGeometryCollection" \
  -Dtests.security.manager=true \
  -Dtests.locale=fr-FR \
  -Dtests.timezone=America/Danmarkshavn \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Relevant excerpt from the logs:
```
ERROR   0.60s | GeoWKTShapeParserTests.testParseGeometryCollection <<< FAILURES!
   > Throwable #1: java.lang.IllegalArgumentException: the list of shapes cannot be null or empty
   >    at __randomizedtesting.SeedInfo.seed([31C073EB0CC10A18:BF67513903E6CFA7]:0)
   >    at org.elasticsearch.geo.geometry.GeometryCollection.<init>(GeometryCollection.java:40)
   >    at org.elasticsearch.common.geo.builders.GeometryCollectionBuilder.buildGeometry(GeometryCollectionBuilder.java:195)
   >    at org.elasticsearch.common.geo.GeoWKTShapeParserTests.testParseGeometryCollection(GeoWKTShapeParserTests.java:441)
   >    at java.lang.Thread.run(Thread.java:748)
```

**Comment by jtibshirani** [comment]
I temporarily muted the test in e41ccdc1a01278c0930500ec27b07353e1d50c81.
