### ISSUE TITLE
DynamicMappingIT#testConflictingDynamicMappings can fail with IllegalArgumentException

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#37898]
I wasn't able to reproduce this locally, but the same error has popped up a few times on CI in the past couple days. It looks like we might receive an unexpected exception type when merging conflicting mappings.

---

Link to the build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+release-tests/408

Command to reproduce: 
```
./gradlew :server:integTest \
  -Dtests.seed=3735D88AEB8647FB \
  -Dtests.class=org.elasticsearch.index.mapper.DynamicMappingIT \
  -Dtests.method="testConflictingDynamicMappings" \
```

Relevant excerpt from logs:
```
ERROR   0.12s J7 | DynamicMappingIT.testConflictingDynamicMappings <<< FAILURES!
   > Throwable #1: java.lang.IllegalArgumentException: mapper [foo] of different type, current_type [long], merged_type [text]
   > 	at __randomizedtesting.SeedInfo.seed([3735D88AEB8647FB:55D09E8433A4A293]:0)
   > 	at org.elasticsearch.index.mapper.FieldMapper.doMerge(FieldMapper.java:354)
   > 	at org.elasticsearch.index.mapper.NumberFieldMapper.doMerge(NumberFieldMapper.java:1093)
   > 	at org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:340)
   > 	at org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:52)
   > 	at org.elasticsearch.index.mapper.ObjectMapper.doMerge(ObjectMapper.java:487)
   > 	at org.elasticsearch.index.mapper.RootObjectMapper.doMerge(RootObjectMapper.java:278)
   > 	at org.elasticsearch.index.mapper.ObjectMapper.merge(ObjectMapper.java:457)
   > 	at org.elasticsearch.index.mapper.RootObjectMapper.merge(RootObjectMapper.java:273)
   > 	at org.elasticsearch.index.mapper.Mapping.merge(Mapping.java:91)
   > 	at org.elasticsearch.index.mapper.DocumentMapper.merge(DocumentMapper.java:339)
   > 	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:286)
   > 	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:232)
   > 	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:642)
   > 	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:271)
   > 	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:201)
   > 	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:136)
```

**Comment by jtibshirani** [comment]
I temporarily muted the test in https://github.com/elastic/elasticsearch/commit/afc60bb0e51aff57b8916401d693add63d56d0b8.

**Comment by romseygeek** [comment]
This just failed in the 6.7 branch - was the fix supposed to be backported?

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+multijob-unix-compatibility/os=ubuntu-14.04&&immutable/32/console

**Comment by jpountz** [comment]
Apparently I failed to backport it. I'll do it today, thanks for noticing!

**Comment by jpountz** [comment]
Done.
