### ISSUE TITLE
RecoveryWhileUnderLoadIT#testRecoverWhileUnderLoadAllocateReplicasRelocatePrimariesTest fails with an assertion error

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#37895]
This fails reproducibly for me on master using the command below. It looks like it could be related to the change around total hit count tracking.

---

Link to the build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian/204

Command to reproduce: 
```
./gradlew :server:integTest \
  -Dtests.seed=51FB0CF3C03F1401 \
  -Dtests.class=org.elasticsearch.recovery.RecoveryWhileUnderLoadIT \
  -Dtests.method="testRecoverWhileUnderLoadAllocateReplicasRelocatePrimariesTest" \
  -Dtests.security.manager=true \
  -Dtests.locale=mk \
  -Dtests.timezone=Etc/GMT+11 \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Relevant excerpt from the logs:
```
FAILURE 10.9s J7 | RecoveryWhileUnderLoadIT.testRecoverWhileUnderLoadAllocateReplicasRelocatePrimariesTest <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Count is 10000+ hits but 10000 was expected.  Total shards: 6 Successful shards: 6 & 0 shard failures:
   > 	at __randomizedtesting.SeedInfo.seed([51FB0CF3C03F1401:88D2AE326490CEAB]:0)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertHitCount(ElasticsearchAssertions.java:256)
   > 	at org.elasticsearch.recovery.RecoveryWhileUnderLoadIT.iterateAssertCount(RecoveryWhileUnderLoadIT.java:358)
   > 	at org.elasticsearch.recovery.RecoveryWhileUnderLoadIT.testRecoverWhileUnderLoadAllocateReplicasRelocatePrimariesTest(RecoveryWhileUnderLoadIT.java:169)
   > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jtibshirani** [comment]
I temporarily muted the test in 23b0d9b3ed7f212e0a7c80c9eb08d215b4840784.

**Comment by ywelsch** [comment]
@jimczi can you have a look?
