### ISSUE TITLE
Reproducible Failure in GeoHashGridTests#testFromXContentWithRandomFields in Master

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#37892]
The following fails for me 100% of the time:

```sh
./gradlew :server:unitTest -Dtests.seed=CAB66323227CFF59 -Dtests.class=org.elasticsearch.search.aggregations.bucket.geogrid.GeoHashGridTests -Dtests.method="testFromXContentWithRandomFields" -Dtests.security.manager=true -Dtests.locale=sr-Latn -Dtests.timezone=NZ -Dcompiler.java=11 -Druntime.java=8
```

as:

```sh
> Task :server:unitTest
   [junit4] <JUnit4> says olá! Master seed: CAB66323227CFF59
==> Test Info: seed=CAB66323227CFF59; jvm=1; suite=1

  1> [2019-01-26T11:34:24,209][INFO ][o.e.s.a.b.g.GeoHashGridTests] [testFromXContentWithRandomFields] before test
  1> [2019-01-26T11:34:24,401][INFO ][o.e.s.a.b.g.GeoHashGridTests] [testFromXContentWithRandomFields] after test
  2> REPRODUCE WITH: ./gradlew :server:unitTest -Dtests.seed=CAB66323227CFF59 -Dtests.class=org.elasticsearch.search.aggregations.bucket.geogrid.GeoHashGridTests -Dtests.method="testFromXContentWithRandomFields" -Dtests.security.manager=true -Dtests.locale=sr-Latn -Dtests.timezone=NZ -Dcompiler.java=11 -Druntime.java=8
FAILURE 0.65s | GeoHashGridTests.testFromXContentWithRandomFields <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<1946022914> but was:<405797868>
   >    at __randomizedtesting.SeedInfo.seed([CAB66323227CFF59:C8A34E6279BB778C]:0)
   >    at org.elasticsearch.test.InternalMultiBucketAggregationTestCase.assertBucket(InternalMultiBucketAggregationTestCase.java:167)
   >    at org.elasticsearch.test.InternalMultiBucketAggregationTestCase.assertMultiBucketsAggregations(InternalMultiBucketAggregationTestCase.java:140)
   >    at org.elasticsearch.test.InternalMultiBucketAggregationTestCase.assertFromXContent(InternalMultiBucketAggregationTestCase.java:102)
   >    at org.elasticsearch.test.InternalAggregationTestCase.testFromXContentWithRandomFields(InternalAggregationTestCase.java:353)
   >    at java.lang.Thread.run(Thread.java:748)
  2> NOTE: leaving temporary files on disk at: /home/brownbear/src/elasticsearch/server/build/testrun/unitTest/J0/temp/org.elasticsearch.search.aggregations.bucket.geogrid.GeoHashGridTests_CAB66323227CFF59-001
  2> NOTE: test params are: codec=Asserting(Lucene80): {}, docValues:{}, maxPointsInLeafNode=591, maxMBSortInHeap=5.3612445948387, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@5a72a72d), locale=sr-Latn, timezone=NZ
  2> NOTE: Linux 4.18.0-13-generic amd64/Oracle Corporation 1.8.0_191 (64-bit)/cpus=16,threads=1,free=445481912,total=514850816
  2> NOTE: All tests run in this JVM: [GeoHashGridTests]
Completed [1/1] in 1.49s, 1 test, 1 failure <<< FAILURES!


> Task :server:unitTest FAILED
Tests with failures:
  - org.elasticsearch.search.aggregations.bucket.geogrid.GeoHashGridTests.testFromXContentWithRandomFields

   [junit4] JVM J0:     0.31 ..     1.96 =     1.66s
   [junit4] Execution time total: 2.10 sec.
   [junit4] Tests summary: 1 suite, 1 test, 1 failure

FAILURE: Build failed with an exception.

```

**Comment by talevy** [comment]
looking into this

**Comment by talevy** [comment]
After running 10000 successful iterations of these tests with https://github.com/elastic/elasticsearch/commit/eb973a47441313e2699857fceba7a871fac7384f, 
this should be fixed.

sorry for the noise!
