### ISSUE TITLE
RetentionLeaseSyncIT#testRetentionLeasesSyncedOnAdd fails with a NullPointerException

### ISSUE THREAD

**Issue by hub-cap** [elastic/elasticsearch#37926]
Reproduces locally. Failing the 6.x intake build.

Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1218/console

```
./gradlew :server:integTest \                                                                                                                       src/elasticsearch-6 (6.x ⚡) marceline
  -Dtests.seed=697E1A9AD54B6588 \
  -Dtests.class=org.elasticsearch.index.seqno.RetentionLeaseSyncIT \
  -Dtests.method="testRetentionLeasesSyncedOnAdd" \
  -Dtests.security.manager=true \
  -Dtests.locale=ko \
  -Dtests.timezone=Pacific/Majuro \
  -Dcompiler.java=11 \
```

relevant lines from log

```
ERROR   0.43s J7 | RetentionLeaseSyncIT.testRetentionLeasesSyncedOnAdd <<< FAILURES!
   > Throwable #1: java.lang.NullPointerException
   > 	at __randomizedtesting.SeedInfo.seed([BD2B7A767CF5DE44:4E7639B55CBD6969]:0)
   > 	at java.util.Objects.requireNonNull(Objects.java:203)
   > 	at org.elasticsearch.index.seqno.RetentionLease.decodeRetentionLeases(RetentionLease.java:209)
   > 	at org.elasticsearch.index.seqno.RetentionLeaseSyncIT.testRetentionLeasesSyncedOnAdd(RetentionLeaseSyncIT.java:78)
   > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jasontedor** [comment]
Closed by af134b5751396e9274f55a3b3200d3df0cfca56d
