### ISSUE TITLE
CI: SimpleGetFieldMappingsIT testSimpleGetFieldMappingsWithDefaults fails with NPE

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#37928]
## Example build failure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+corretto-periodic/ES_BUILD_JAVA=java11,label=amazon/79/console

## Reproduction line 
does not reproduce locally
```
./gradlew :server:integTest -Dtests.seed=797A064C3876272 -Dtests.class=org.elasticsearch.indices.mapping.SimpleGetFieldMappingsIT -Dtests.method="testSimpleGetFieldMappingsWithDefaults" -Dtests.security.manager=true -Dtests.locale=saq-KE -Dtests.timezone=Asia/Rangoon -Dcompiler.java=11 -Druntime.java=11
```

## Example relevant log:
```
ERROR   0.74s J6 | SimpleGetFieldMappingsIT.testSimpleGetFieldMappingsWithDefaults <<< FAILURES!
   > Throwable #1: java.lang.NullPointerException
   >    at __randomizedtesting.SeedInfo.seed([797A064C3876272:268BF528655F4903]:0)
   >    at org.elasticsearch.indices.mapping.SimpleGetFieldMappingsIT.testSimpleGetFieldMappingsWithDefaults(SimpleGetFieldMappingsIT.java:156)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   >    at java.base/java.lang.Thread.run(Thread.java:834)

```

## Frequency
Just this once, but I was able to reproduce it on master when running tests in a loop on a VM running centos 7 CI image. I'm still running it locally but no reproduction so far.

**Comment by atorok** [comment]
I got another reproduction, but it only reproduced after more than an hour and 7 iterations of internal cluster test runs
