### ISSUE TITLE
CcrRepositoryIT.testIndividualActionsTimeout failing

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#38027]
Failing on intake-master
`
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1648/console
`

but unfortunately does not reproduce for me 
```
./gradlew :x-pack:plugin:ccr:internalClusterTest \
  -Dtests.seed=75F3403255B8F3AF \
  -Dtests.class=org.elasticsearch.xpack.ccr.CcrRepositoryIT \
  -Dtests.method="testIndividualActionsTimeout" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-AE \
  -Dtests.timezone=Europe/Saratov \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

relates https://github.com/elastic/elasticsearch/issues/37887

**Comment by pgomulka** [comment]
assertion failure log
```
java.lang.AssertionError: expected:<0> but was:<1>
	at __randomizedtesting.SeedInfo.seed([75F3403255B8F3AF:11EEACEEE6CAC19C]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.elasticsearch.xpack.ccr.CcrRepositoryIT.testIndividualActionsTimeout(CcrRepositoryIT.java:370)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by atorok** [comment]
Seems like this fails less often but there are still failures 

## Example build failure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu-14.04&&virtual/215/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1684/console

## Reproduction line 
does not reproduce locally
```
./gradlew :x-pack:plugin:ccr:internalClusterTest -Dtests.seed=36B1DA4D705F0B8F -Dtests.class=org.elasticsearch.xpack.ccr.CcrRepositoryIT -Dtests.method="testIndividualActionsTimeout" -Dtests.security.manager=true -Dtests.locale=mt -Dtests.timezone=Atlantic/Madeira -Dcompiler.java=11 -Druntime.java=8
```

## Example relevant log:
```
11:26:45   1> org.apache.lucene.util.SetOnce$AlreadySetException: The object cannot be set twice!
11:26:45   1> 	at org.apache.lucene.util.SetOnce.set(SetOnce.java:69) ~[lucene-core-8.0.0-snapshot-83f9835.jar:8.0.0-snapshot-83f9835 83f9835a47a00a2ec58a4cf5fc0d492497cf7898 - jpountz - 2019-01-21 13:06:00]
11:26:45   1> 	at org.elasticsearch.common.logging.NodeAndClusterIdConverter.setNodeIdAndClusterId(NodeAndClusterIdConverter.java:59) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
11:26:45   1> 	at org.elasticsearch.common.logging.NodeAndClusterIdStateListener.onNewClusterState(NodeAndClusterIdStateListener.java:69) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
11:26:45   1> 	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onNewClusterState(ClusterStateObserver.java:308) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
11:26:45   1> 	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.clusterChanged(ClusterStateObserver.java:193) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
11:26:45   1> 	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateListeners$6(ClusterApplierService.java:481) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
11:26:45   1> 	at java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3527) [?:1.8.0_202]
11:26:45   1> 	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743) [?:1.8.0_202]
11:26:45   1> 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) [?:1.8.0_202]
11:26:45   1> 	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:478) [elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
11:26:45   1> 	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:467) [elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
11:26:45   1> 	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:414) [elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
11:26:45   1> 	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:165) [elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
11:26:45   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
11:26:45   1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
11:26:45   1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
11:26:45   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
11:26:45   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
11:26:45   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]


11:26:45 FAILURE 14.9s J3 | CcrRepositoryIT.testIndividualActionsTimeout <<< FAILURES!
11:26:45    > Throwable #1: java.lang.AssertionError: 
11:26:45    > Expected: a value greater than <0>
11:26:45    >      but: <0> was equal to <0>
11:26:45    > 	at __randomizedtesting.SeedInfo.seed([36B1DA4D705F0B8F:52AC3691C32D39BC]:0)
11:26:45    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:26:45    > 	at org.elasticsearch.xpack.ccr.CcrRepositoryIT.testIndividualActionsTimeout(CcrRepositoryIT.java:372)
11:26:45    > 	at java.lang.Thread.run(Thread.java:748)
```

## Frequency

6 time Today

**Comment by pgomulka** [comment]
The exceptions from the NodeAndClusterIdListener should not be causing these tests to fail, but I have create a PR to fix this anyway. 
https://github.com/elastic/elasticsearch/pull/38110
