### ISSUE TITLE
throw unknown parameter [serialization.format] when spark create elasticsearch jdbc connection

### ISSUE THREAD

**Issue by fjbreeze** [elastic/elasticsearch#38068]
configuration: 
```
jdbcUrl: jdbc:es://http://192.168.1.81:9200
driverClass: org.elasticsearch.xpack.sql.jdbc.jdbc.JdbcDriver
```
spark create ***elasticsearch jdbc*** connection throw follow exception, but ignore unknown parameter when use ***mysql jdbc*** or ***postgresql jdbc***
```
Exception in thread "main" org.elasticsearch.xpack.sql.jdbc.JdbcSQLException: Unknown parameter [serialization.format] ; did you mean []
	at org.elasticsearch.xpack.sql.jdbc.jdbc.JdbcConfiguration.create(JdbcConfiguration.java:95)
	at org.elasticsearch.xpack.sql.jdbc.jdbc.JdbcDriver.initCfg(JdbcDriver.java:82)
	at org.elasticsearch.xpack.sql.jdbc.jdbc.JdbcDriver.connect(JdbcDriver.java:76)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$createConnectionFactory$1.apply(JdbcUtils.scala:59)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$createConnectionFactory$1.apply(JdbcUtils.scala:50)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:58)
	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation.<init>(JDBCRelation.scala:113)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:45)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:335)
	at org.apache.spark.sql.hive.ConnectorCatalog$$anon$1.load(ConnectorCatalog.scala:108)
	at org.apache.spark.sql.hive.ConnectorCatalog$$anon$1.load(ConnectorCatalog.scala:74)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2379)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2342)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2257)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4000)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4004)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4874)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4880)
	at com.google.common.cache.LocalCache$LocalLoadingCache.apply(LocalCache.java:4898)
	at org.apache.spark.sql.hive.SnappyStoreHiveCatalog.getCachedHiveTable(SnappyStoreHiveCatalog.scala:312)
	at org.apache.spark.sql.hive.SnappyStoreHiveCatalog.lookupRelation(SnappyStoreHiveCatalog.scala:654)
	at org.apache.spark.sql.hive.SnappyStoreHiveCatalog.lookupRelation(SnappyStoreHiveCatalog.scala:738)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.org$apache$spark$sql$catalyst$analysis$Analyzer$ResolveRelations$$lookupTableFromCatalog(Analyzer.scala:457)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$$anonfun$apply$8.applyOrElse(Analyzer.scala:479)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$$anonfun$apply$8.applyOrElse(Analyzer.scala:464)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$resolveOperators$1.apply(LogicalPlan.scala:61)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$resolveOperators$1.apply(LogicalPlan.scala:61)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperators(LogicalPlan.scala:60)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$1.apply(LogicalPlan.scala:58)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$1.apply(LogicalPlan.scala:58)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:307)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:188)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:305)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperators(LogicalPlan.scala:58)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$1.apply(LogicalPlan.scala:58)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$1.apply(LogicalPlan.scala:58)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:307)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:188)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:305)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperators(LogicalPlan.scala:58)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$1.apply(LogicalPlan.scala:58)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$1.apply(LogicalPlan.scala:58)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:307)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:188)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:305)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperators(LogicalPlan.scala:58)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$1.apply(LogicalPlan.scala:58)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan$$anonfun$1.apply(LogicalPlan.scala:58)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:307)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:188)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:305)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperators(LogicalPlan.scala:58)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.apply(Analyzer.scala:464)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.apply(Analyzer.scala:454)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:85)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1$$anonfun$apply$1.apply(RuleExecutor.scala:82)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:82)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor$$anonfun$execute$1.apply(RuleExecutor.scala:74)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:74)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:69)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:67)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:50)
	at org.apache.spark.sql.SnappySession.executePlan(SnappySession.scala:228)
	at org.apache.spark.sql.SnappySession$.sqlPlan(SnappySession.scala:2257)
	at org.apache.spark.sql.SnappySession$$anonfun$sql$1.apply(SnappySession.scala:203)
	at org.apache.spark.sql.SnappySession$$anonfun$sql$1.apply(SnappySession.scala:203)
	at org.apache.spark.sql.aqp.SnappyContextFunctions.sql(SnappyContextFunctions.scala:110)
	at org.apache.spark.sql.SnappySession.sql(SnappySession.scala:203)
	at org.apache.spark.sql.SnappySession.sql(SnappySession.scala:79)
	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:700)
Caused by: org.elasticsearch.xpack.sql.client.ClientException: Unknown parameter [serialization.format] ; did you mean []
	at org.elasticsearch.xpack.sql.client.ConnectionConfiguration.checkPropertyNames(ConnectionConfiguration.java:153)
	at org.elasticsearch.xpack.sql.client.ConnectionConfiguration.<init>(ConnectionConfiguration.java:88)
	at org.elasticsearch.xpack.sql.jdbc.jdbc.JdbcConfiguration.<init>(JdbcConfiguration.java:148)
	at org.elasticsearch.xpack.sql.jdbc.jdbc.JdbcConfiguration.create(JdbcConfiguration.java:91)
	... 77 more
```

**Comment by costin** [comment]
@fjbreeze I'm not sure what this report is about? The JDBC driver complains that it has received a setting that it does not know about.
This is on purpose - somebody tries to configure Elasticsearch and it sets something that doesn't exist; the driver indicates that by throwing the exception.
The solution is to not set arbitrary parameters (like `serialization.format`).

**Comment by fjbreeze** [comment]
@costin I only set  `jdbcUrl= jdbc:es://http://192.168.1.81:9200` and `driverClass:org.elasticsearch.xpack.sql.jdbc.jdbc.JdbcDriver`, but throw ClientException  when i query. I didn't set any parameter like `serialization.format`

**Comment by costin** [comment]
I see, likely the rest of the parameters are added by Spark. A workaround would be to add a dedicated option to disable validation of all passed params.
@astefan can you please look into it?

**Comment by astefan** [comment]
master (8.0.0): https://github.com/elastic/elasticsearch/commit/38fbf9792bcf4fe66bb3f17589e5fe6d29748d07
7.x (7.1.0): https://github.com/elastic/elasticsearch/commit/92206c85676e2158d781f8785280d49a25c35e38
7.0 (7.0.0): https://github.com/elastic/elasticsearch/commit/42255a1e095c787b7051739a75b9d7a9c2d1b3a9
6.7 (6.7.0): https://github.com/elastic/elasticsearch/commit/19071e8d05d565f99abf4abdb20ffcf2c7080d6c
6.6 (6.6.2): https://github.com/elastic/elasticsearch/commit/19c42e6dc0e51a9f387ea9704ef4350199a5f6c1
