### ISSUE TITLE
[CI] CloseWhileRelocatingShardsIT.testCloseWhileRelocatingShards failures

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#38090]
See https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+internalClusterTest/173/console for an example failure

It looks to be a timing issue, it doesn't reproduce for me:
```
./gradlew :server:integTest \
  -Dtests.seed=B04B0599D97CB9C5 \
  -Dtests.class=org.elasticsearch.indices.state.CloseWhileRelocatingShardsIT \
  -Dtests.method="testCloseWhileRelocatingShards" \
  -Dtests.security.manager=true \
  -Dtests.locale=ro \
  -Dtests.timezone=Europe/London \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

```
2> WARNING: Uncaught exception in thread: Thread[elasticsearch[node_sd2][generic][T#4],5,TGRP-CloseWhileRelocatingShardsIT]
  2> java.lang.AssertionError: java.lang.InterruptedException
  2> 	at __randomizedtesting.SeedInfo.seed([B04B0599D97CB9C5]:0)
  2> 	at org.elasticsearch.indices.state.CloseWhileRelocatingShardsIT.lambda$testCloseWhileRelocatingShards$1(CloseWhileRelocatingShardsIT.java:159)
  2> 	at org.elasticsearch.test.transport.StubbableTransport$WrappedConnection.sendRequest(StubbableTransport.java:223)
  2> 	at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:626)
  2> 	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:541)
  2> 	at org.elasticsearch.transport.TransportService.submitRequest(TransportService.java:503)
  2> 	at org.elasticsearch.transport.TransportService.submitRequest(TransportService.java:494)
  2> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.lambda$doRecovery$3(PeerRecoveryTargetService.java:263)
  2> 	at org.elasticsearch.common.util.CancellableThreads.executeIO(CancellableThreads.java:108)
  2> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.doRecovery(PeerRecoveryTargetService.java:257)
  2> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService.access$500(PeerRecoveryTargetService.java:84)
  2> 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$RecoveryRunner.doRun(PeerRecoveryTargetService.java:658)
  2> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751)
  2> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  2> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  2> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  2> 	at java.lang.Thread.run(Thread.java:748)
  2> Caused by: java.lang.InterruptedException
  2> 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998)
  2> 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
  2> 	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
  2> 	at org.elasticsearch.indices.state.CloseWhileRelocatingShardsIT.lambda$testCloseWhileRelocatingShards$1(CloseWhileRelocatingShardsIT.java:156)
  2> 	... 15 more
```

**Comment by atorok** [comment]
I don't see any failures on master, maybe the fix in #37274 didn't work for 6.x ?

**Comment by atorok** [comment]
This was muted in  fe0a52ed3b64

**Comment by tlrx** [comment]
@atorok The issue here is a bit different so I told Alan to create a new issue.

**Comment by tlrx** [comment]
Reopened: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+internalClusterTest/283/consoleFull

**Comment by jtibshirani** [comment]
I just saw another failure pop up on master intake: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part1/3897/

@tlrx I'm having trouble telling whether I should re-open this issue or file a new one, figured I'd just link to the failure so you're aware.
