### ISSUE TITLE
testRestoreIncreasesPrimaryTerms fails on 6.x

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#38223]
I can reproduce this locally with the following command.

```
./gradlew :server:integTest \
  -Dtests.seed=8E0D4395046AC9E0 \
  -Dtests.class=org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT \
  -Dtests.method="testRestoreIncreasesPrimaryTerms" \
  -Dtests.security.manager=true \
  -Dtests.locale=el \
  -Dtests.timezone=Pacific/Tahiti \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

```
AILURE 2.48s | SharedClusterSnapshotRestoreIT.testRestoreIncreasesPrimaryTerms <<< FAILURES!
   > Throwable #1: java.lang.AssertionError:
   > Expected: <4L>
   >      but: was <5L>
   >    at __randomizedtesting.SeedInfo.seed([8E0D4395046AC9E0:46EF6D1E229D6B72]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.testRestoreIncreasesPrimaryTerms(SharedClusterSnapshotRestoreIT.java:3746)
   >    at java.lang.Thread.run(Thread.java:748)
```

CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1325/console

Relates #38177

**Comment by tlrx** [comment]
Closed by #38314
