### ISSUE TITLE
[CI] Failure in Windows12 packaging test

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#38321]
The master packaging tests seem to be failing for a while with what looks like a windows-related issue to me for a couple of days now. 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-tests/

I see this failure in the logs when running the `windows-2012r2` tests

```
15:13:57 There was 1 failure:
15:13:57 1) test90SecurityCliPackaging(org.elasticsearch.packaging.test.DefaultZipTests)
15:13:57 java.lang.AssertionError: 
15:13:57 Expected: is <64>
15:13:57      but: was <1>
15:13:57 	at __randomizedtesting.SeedInfo.seed([5F328DE0CFD6C181:99DBC7CFA37C8F84]:0)
15:13:57 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
15:13:57 	at org.junit.Assert.assertThat(Assert.java:956)
15:13:57 	at org.junit.Assert.assertThat(Assert.java:923)
15:13:57 	at org.elasticsearch.packaging.test.ArchiveTestCase.lambda$test90SecurityCliPackaging$14(ArchiveTestCase.java:296)
15:13:57 	at org.elasticsearch.packaging.util.Platforms.onWindows(Platforms.java:70)
15:13:57 	at org.elasticsearch.packaging.test.ArchiveTestCase.test90SecurityCliPackaging(ArchiveTestCase.java:300)
15:13:57 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:13:57 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:13:57 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:13:57 	at java.lang.reflect.Method.invoke(Method.java:498)
15:13:57 	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
15:13:57 	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
15:13:57 	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
15:13:57 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
15:13:57 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
15:13:57 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
15:13:57 	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
15:13:57 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
15:13:57 	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
15:13:57 	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
15:13:57 	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
15:13:57 	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
15:13:57 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
15:13:57 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
15:13:57 	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
15:13:57 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$2.evaluate(ThreadLeakControl.java:404)
15:13:57 	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSuite(RandomizedRunner.java:708)
15:13:57 	at com.carrotsearch.randomizedtesting.RandomizedRunner.access$200(RandomizedRunner.java:138)
15:13:57 	at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:629)
15:13:57
```

**Comment by cbuescher** [comment]
Possibly related: https://github.com/elastic/elasticsearch/pull/37956

**Comment by danielmitterdorfer** [comment]
@tvernum can you please have a look at this as Christoph indicates it seems related to #37956?

**Comment by cbuescher** [comment]
I'm not 100% sure but I think the failures on 6.x. are similar:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+packaging-tests

e.g: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+packaging-tests/447/console

```
13:49:40 > Task :qa:vagrant:vagrantWindows2012r2#javaPackagingTest FAILED
13:49:40 1) test90SecurityCliPackaging(org.elasticsearch.packaging.test.DefaultZipTests)
13:49:40 java.lang.AssertionError: 
13:49:40 Expected: is <64>
13:49:40 :qa:vagrant:vagrantWindows2012r2#javaPackagingTest (Thread[Execution worker for ':' Thread 4,5,main]) completed. Took 1 mins 26.082 secs.
13:49:40 :qa:vagrant:vagrantWindows2012r2#halt (Thread[Execution worker for ':' Thread 4,5,main]) started.
13:49:40      but: was <1>
13:49:40 	at __randomizedtesting.SeedInfo.seed([7A586F5F100FBDF4:BCB125707CA5F3F1]:0)
13:49:40 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
13:49:40 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
13:49:40 	at org.elasticsearch.packaging.test.ArchiveTestCase.lambda$test90SecurityCliPackaging$14(ArchiveTestCase.java:320)
13:49:40 	at org.elasticsearch.packaging.util.Platforms.onWindows(Platforms.java:69)
13:49:40 	at org.elasticsearch.packaging.test.ArchiveTestCase.test90SecurityCliPackaging(ArchiveTestCase.java:324)
```

**Comment by tvernum** [comment]
*sigh* Windows. I'll make the test more tolerant of the various exit codes.

**Comment by original-brownbear** [comment]
Another one https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-tests/417/console

```
JUnit version 4.12
...........
Time: 156.577
There was 1 failure:
1) test90SecurityCliPackaging(org.elasticsearch.packaging.test.DefaultZipTests)
java.lang.AssertionError: 
Expected: is <64>
     but: was <1>
	at __randomizedtesting.SeedInfo.seed([E6D69DFFF5555180:203FD7D099FF1F85]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.packaging.test.ArchiveTestCase.lambda$test90SecurityCliPackaging$14(ArchiveTestCase.java:296)
	at org.elasticsearch.packaging.util.Platforms.onWindows(Platforms.java:70)
	at org.elasticsearch.packaging.test.ArchiveTestCase.test90SecurityCliPackaging(ArchiveTestCase.java:300)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
REPRODUCE WITH: ./gradlew ":qa:vagrant:vagrantWindows2012r2#javaPackagingTest" -Dtests.seed=5C771BE2101C3946 
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)

	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
> Task :qa:vagrant:vagrantWindows2012r2#javaPackagingTest FAILED
```
