### ISSUE TITLE
[CI] SpecificMasterNodesIT#testElectOnlyBetweenMasterNodes fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#38331]
Seen at least three times in master in the last few days:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/497/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1777/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1710/console

Latest reproduce line:
```
./gradlew :server:integTest \
  -Dtests.seed=2CFBF83AF54213EC \
  -Dtests.class=org.elasticsearch.cluster.SpecificMasterNodesIT \
  -Dtests.method="testElectOnlyBetweenMasterNodes" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-DZ \
  -Dtests.timezone=Africa/Kinshasa \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Running repeatedly on Ubuntu didn't reproduce after 50 runs.

Logs contain NPEs:
```
14:52:15   1> java.lang.NullPointerException: null
14:52:15   1> 	at org.elasticsearch.test.InternalTestCluster.getMasterName(InternalTestCluster.java:1913) ~[framework-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
14:52:15   1> 	at org.elasticsearch.test.InternalTestCluster.getMasterName(InternalTestCluster.java:1902) ~[framework-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
14:52:15   1> 	at org.elasticsearch.test.InternalTestCluster.nonMasterClient(InternalTestCluster.java:776) ~[framework-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
14:52:15   1> 	at org.elasticsearch.cluster.SpecificMasterNodesIT.lambda$testElectOnlyBetweenMasterNodes$0(SpecificMasterNodesIT.java:122) ~[test/:?]
14:52:15   1> 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:846) [framework-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
```
But there are also several earlier connection Exceptions like:

```
14:52:14   1> Caused by: java.net.ConnectException: Connection refused
```

**Comment by cbuescher** [comment]
@ywelsch @DaveCTurner to mute or not to mute? 💀

**Comment by cbuescher** [comment]
Muted on master with  5ee7232.

**Comment by tlrx** [comment]
Failed again today on 7.x:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/337/consoleFull

with:
```
16:37:13 ERROR   3.47s J7 | SpecificMasterNodesIT.testElectOnlyBetweenMasterNodes <<< FAILURES!
16:37:13    > Throwable #1: java.lang.NullPointerException
16:37:13    > 	at __randomizedtesting.SeedInfo.seed([974B8C1608DDBAFC:DDD67F1D39FAAFDE]:0)
16:37:13    > 	at org.elasticsearch.cluster.SpecificMasterNodesIT.lambda$testElectOnlyBetweenMasterNodes$0(SpecificMasterNodesIT.java:123)
16:37:13    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:856)
16:37:13    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:842)
16:37:13    > 	at org.elasticsearch.cluster.SpecificMasterNodesIT.testElectOnlyBetweenMasterNodes(SpecificMasterNodesIT.java:121)
16:37:13    > 	at java.lang.Thread.run(Thread.java:748)
```

And it does not reproduce with
```
./gradlew :server:integTest -Dtests.seed=974B8C1608DDBAFC -Dtests.class=org.elasticsearch.cluster.SpecificMasterNodesIT -Dtests.method="testElectOnlyBetweenMasterNodes" -Dtests.security.manager=true -Dtests.locale=sk -Dtests.timezone=America/Belize -Dcompiler.java=11 -Druntime.java=8
```

I muted the test on master (f1d801ce58a64a7cd36288ce2c411b7851f53735) and 7.x (983b5d1c0eb1b1feb9e7c36efc9d795631041786) since it failed on those two branches in the last 30 days.

**Comment by ywelsch** [comment]
Mute this as well in 7.0 branch

**Comment by ywelsch** [comment]
I've reeenabled this test on master to get more recent failures
