### ISSUE TITLE
[CI] NodeStatsMonitoringDocTests#testToUTC fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#38359]
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1812/console

Couldn't reproduce locally but looks like a date formatting issue.
```
./gradlew :x-pack:plugin:monitoring:unitTest \
  -Dtests.seed=1B6F728E6033F9E8 \
  -Dtests.class=org.elasticsearch.xpack.monitoring.collector.node.NodeStatsMonitoringDocTests \
  -Dtests.method="testToUTC" \
  -Dtests.security.manager=true \
  -Dtests.locale=lv-LV \
  -Dtests.timezone=GMT0 \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

```
org.junit.ComparisonFailure: expected:<2019-02-04T16:31:46[]Z> but was:<2019-02-04T16:31:46[.000]Z>
	at __randomizedtesting.SeedInfo.seed([1B6F728E6033F9E8:F583DD13D392E2A0]:0)
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.elasticsearch.xpack.monitoring.exporter.BaseMonitoringDocTestCase.testToUTC(BaseMonitoringDocTestCase.java:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
```

**Comment by original-brownbear** [comment]
Another one:

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:monitoring:unitTest \
  -Dtests.seed=B80D9741EB4E54A0 \
  -Dtests.class=org.elasticsearch.xpack.monitoring.collector.ml.JobStatsMonitoringDocTests \
  -Dtests.method="testToUTC" \
  -Dtests.security.manager=true \
  -Dtests.locale=he-IL \
  -Dtests.timezone=America/Shiprock \
  -Dcompiler.java=11 \
  -Druntime.java=8
```


https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1828/console

**Comment by pgomulka** [comment]
to be fair, this test does not adds more coverage. 
The whole body could be replaced with just a call `dateTimeFormatter.formatMillis(timestamp);`
i will cover that scenario from failure in `DateFormattersTests`
