### ISSUE TITLE
LocalExporterIntegTests#testExport can fail with assertion error.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#38378]
This error consistently reproduces locally on 6.x.

---

Command to reproduce: 
```
./gradlew :x-pack:plugin:monitoring:unitTest \
    -Dtests.seed=6489BCFAE7072B31 \
    -Dtests.class=org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterIntegTests \
    -Dtests.method="testExport" \
    -Dtests.security.manager=true \
    -Dtests.locale=es-HN \
    -Dtests.timezone=Etc/GMT+1 \
    -Dcompiler.java=11 \
    -Druntime.java=8
```

Relevant excerpt from the logs:
```
14:47:02 FAILURE 12.0s J0 | LocalExporterIntegTests.testExport <<< FAILURES!
14:47:02    > Throwable #1: org.junit.ComparisonFailure: Expected .monitoring-kibana-6-60884505.09.24 but got .monitoring-kibana-6-+60884505.09.24 expected:<...monitoring-kibana-6-[]60884505.09.24> but was:<...monitoring-kibana-6-[+]60884505.09.24>
14:47:02    > 	at __randomizedtesting.SeedInfo.seed([6489BCFAE7072B31:F68413CC699722AF]:0)
14:47:02    > 	at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterIntegTests.checkMonitoringDocs(LocalExporterIntegTests.java:295)
14:47:02    > 	at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterIntegTests.testExport(LocalExporterIntegTests.java:123)
14:47:02    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jdconrad** [comment]
Guessing it's probably this change (https://github.com/elastic/elasticsearch/pull/38309). What I'm not sure of is whether the expected output should be changed here or not to have the `+` as part of the date for this index name.  Maybe @spinscale can confirm and comment?
