### ISSUE TITLE
core.ml.calendars tests failing after version bump

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#38575]
After doing the version bumps in #38513 we have these failures locally:
```
2> REPRODUCE WITH: ./gradlew :x-pack:plugin:core:unitTest -Dtests.seed=376ACFDEC0FA510A -Dtests.class=org.elasticsearch.xpack.core.ml.calendars.ScheduledEventTests -Dtests.method="testEqualsAndHashcode" -Dtests.security.manager=true -Dtests.locale=fr-CA -Dtests.timezone=Eire -Dcompiler.java=11 -Druntime.java=11
FAILURE 0.01s J1 | ScheduledEventTests.testEqualsAndHashcode <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: ScheduledEvent hashcode is different from copies hashcode
   > Expected: <1814201430>
   >      but: was <2104666966>
   >    at __randomizedtesting.SeedInfo.seed([376ACFDEC0FA510A:4665B7130F1D1825]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.test.EqualsHashCodeTestUtils.checkEqualsAndHashCode(EqualsHashCodeTestUtils.java:90)
   >    at org.elasticsearch.test.AbstractWireTestCase.testEqualsAndHashcode(AbstractWireTestCase.java:61)
   >    at jdk.internal.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   >    at java.base/java.lang.Thread.run(Thread.java:834)
  1> [2019-02-07T15:51:43,756][INFO ][o.e.x.c.m.c.ScheduledEventTests] [testStrictParser] before test
  1> [2019-02-07T15:51:43,757][INFO ][o.e.x.c.m.c.ScheduledEventTests] [testStrictParser] after test
  1> [2019-02-07T15:51:43,758][INFO ][o.e.x.c.m.c.ScheduledEventTests] [testSerialization] before test
  1> [2019-02-07T15:51:43,758][INFO ][o.e.x.c.m.c.ScheduledEventTests] [testSerialization] after test
  2> REPRODUCE WITH: ./gradlew :x-pack:plugin:core:unitTest -Dtests.seed=376ACFDEC0FA510A -Dtests.class=org.elasticsearch.xpack.core.ml.calendars.ScheduledEventTests -Dtests.method="testSerialization" -Dtests.security.manager=true -Dtests.locale=fr-CA -Dtests.timezone=Eire -Dcompiler.java=11 -Druntime.java=11
FAILURE 0.00s J1 | ScheduledEventTests.testSerialization <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<1743851377> but was:<-1870282015>
   >    at __randomizedtesting.SeedInfo.seed([376ACFDEC0FA510A:63B2AE96E7A86C96]:0)
   >    at org.elasticsearch.test.AbstractWireTestCase.assertEqualInstances(AbstractWireTestCase.java:91)
   >    at org.elasticsearch.test.AbstractWireTestCase.assertSerialization(AbstractWireTestCase.java:84)
   >    at org.elasticsearch.test.AbstractWireTestCase.assertSerialization(AbstractWireTestCase.java:79)
   >    at org.elasticsearch.test.AbstractWireTestCase.testSerialization(AbstractWireTestCase.java:71)
   >    at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   >    at java.base/java.lang.Thread.run(Thread.java:834)
  1> [2019-02-07T15:51:43,760][INFO ][o.e.x.c.m.c.ScheduledEventTests] [testFromXContent] before test
  1> [2019-02-07T15:51:43,760][INFO ][o.e.x.c.m.c.ScheduledEventTests] [testFromXContent] after test
  2> REPRODUCE WITH: ./gradlew :x-pack:plugin:core:unitTest -Dtests.seed=376ACFDEC0FA510A -Dtests.class=org.elasticsearch.xpack.core.ml.calendars.ScheduledEventTests -
Dtests.method="testFromXContent" -Dtests.security.manager=true -Dtests.locale=fr-CA -Dtests.timezone=Eire -Dcompiler.java=11 -Druntime.java=11
FAILURE 0.00s J1 | ScheduledEventTests.testFromXContent <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<1350791987> but was:<1613511283>
   >    at __randomizedtesting.SeedInfo.seed([376ACFDEC0FA510A:1602FAC6495DB1D0]:0)
   >    at org.elasticsearch.test.AbstractWireTestCase.assertEqualInstances(AbstractWireTestCase.java:91)
   >    at org.elasticsearch.test.AbstractSerializingTestCase.lambda$testFromXContent$0(AbstractSerializingTestCase.java:47)
   >    at org.elasticsearch.test.AbstractXContentTestCase$XContentTester.test(AbstractXContentTestCase.java:137)
   >    at org.elasticsearch.test.AbstractSerializingTestCase.testFromXContent(AbstractSerializingTestCase.java:49)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   >    at java.base/java.lang.Thread.run(Thread.java:834)
  2> NOTE: leaving temporary files on disk at: /home/alpar/work/elastic/elasticsearch-7.x/x-pack/plugin/core/build/testrun/unitTest/J1/temp/org.elasticsearch.xpack.core.ml.calendars.ScheduledEventTests_376ACFDEC0FA510A-001
  2> NOTE: test params are: codec=Asserting(Lucene80): {}, docValues:{}, maxPointsInLeafNode=1059, maxMBSortInHeap=7.104696129104226, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@4c83ccd), locale=fr-CA, timezone=Eire
  2> NOTE: Linux 4.20.6-arch1-1-ARCH amd64/Oracle Corporation 11 (64-bit)/cpus=12,threads=1,free=340244984,total=536870912
  2> NOTE: All tests run in this JVM: [XPackPluginTests, ManageApplicationPrivilegesTests, ForecastStatsTests, GetApiKeyResponseTests, PolicyStatsTests, UpdateCalendarJobActionResquestTests, OperationModeTests, ExtractorUtilsTests, DetectionRuleTests, LicensesTransportTests, GetModelSnapshotsActionRequestTests, ModelPlotConfigTests, LicenseOperationModeTests, FrozenIndexRecoveryTests, LicenseStatusTests, SecurityIndexSearcherWrapperIntegrationTests, InitializePolicyContextStepTests, SSLConfigurationReloaderTests, GetBucketActionRequestTests, CategorizerStateTests, PutLifecycleRequestTests, TermsGroupConfigSerializingTests, UpdateProcessActionRequestTests, SecurityNetty4TransportTests, InvalidateTokenRequestTests, DeleteExpiredDataActionResponseTests, JobWrapperSerializingTests, DefaultAuthenticationFailureHandlerTests, SetPriorityActionTests, ExecuteWatchResponseTests, CopyExecutionStateStepTests, GetDatafeedStatsActionRequestTests, LicenseTLSTests, JobParamsTests, PutCalendarActionResponseTests, ShrunkShardsAllocatedStepTests, MlTasksTests, DeprecationInfoActionResponseTests, PostDataActionRequestTests, WaitForFollowShardTasksStepTests, DeleteLifecycleRequestTests, MoveToStepResponseTests, GetJobStatsActionRequestTests, RevertModelSnapshotActionResponseTests, ScheduledEventTests]
Completed [276/313] on J1 in 0.03s, 7 tests, 3 failures <<< FAILURES!
```
Going to mute them to unblock the team.

**Comment by droberts195** [comment]
This is fixed in master by #38506, but the 7.x and 7.0 PRs are not merged yet.

**Comment by droberts195** [comment]
If you mute in 7.0 and 7.x only then I will unmute in #38516 and #38517 before I merge them.

**Comment by droberts195** [comment]
@tbrooks8 FYI since you are on test triage today, it looks like @atorok cherry-picked my PR into #38513, so when that is merged it will fix these failures on the 7.x branch.
