### ISSUE TITLE
[CI] ApiKeyIntegTests#testGetAndInvalidateApiKeysWithExpiredAndInvalidatedApiKey fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#38611]
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/688/consoleFull

Doesn't reproduce locally even with several runs so far:
```
./gradlew :x-pack:plugin:security:unitTest \
  -Dtests.seed=BC6B5555F5108D40 \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ApiKeyIntegTests \
  -Dtests.method="testGetAndInvalidateApiKeysWithExpiredAndInvalidatedApiKey" \
  -Dtests.security.manager=true \
  -Dtests.locale=nl \
  -Dtests.timezone=America/Inuvik \
  -Dcompiler.java=11 \
  -Druntime.java=8
```
Failure:
```
12:02:09 FAILURE 1.55s J1 | ApiKeyIntegTests.testGetAndInvalidateApiKeysWithExpiredAndInvalidatedApiKey <<< FAILURES!
12:02:09    > Throwable #1: java.lang.AssertionError: 
12:02:09    > Expected: <1>
12:02:09    >      but: was <0>
12:02:09    > 	at __randomizedtesting.SeedInfo.seed([BC6B5555F5108D40:E625A4E748834B13]:0)
12:02:09    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
12:02:09    > 	at org.elasticsearch.xpack.security.authc.ApiKeyIntegTests.verifyInvalidateResponse(ApiKeyIntegTests.java:291)
12:02:09    > 	at org.elasticsearch.xpack.security.authc.ApiKeyIntegTests.testGetAndInvalidateApiKeysWithExpiredAndInvalidatedApiKey(ApiKeyIntegTests.java:274)
```

**Comment by jkakavas** [comment]
Closing this in favor of https://github.com/elastic/elasticsearch/issues/38408, it's tracked there already and I believe that @bizybot has an idea on how it can be fixed
