### ISSUE TITLE
[CI] AnalysisModuleTests#testStandardFilterBWC fails on master

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#38635]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java11,nodes=immutable&&linux&&docker/230/console

Reproduces locally on master with:
```
./gradlew :server:unitTest \
  -Dtests.seed=19B79C99E068891A \
  -Dtests.class=org.elasticsearch.indices.analysis.AnalysisModuleTests \
  -Dtests.method="testStandardFilterBWC" \
  -Dtests.security.manager=true \
  -Dtests.locale=cs-CZ \
  -Dtests.timezone=Asia/Tbilisi \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

```
java.lang.IllegalArgumentException: The [standard] token filter has been removed.
	at __randomizedtesting.SeedInfo.seed([19B79C99E068891A:6879C7DDA92FB39F]:0)
	at org.elasticsearch.indices.analysis.AnalysisModule.lambda$setupPreConfiguredTokenFilters$1(AnalysisModule.java:189)
	at org.elasticsearch.index.analysis.PreConfiguredTokenFilter.lambda$singletonWithVersion$2(PreConfiguredTokenFilter.java:60)
	at org.elasticsearch.index.analysis.PreConfiguredTokenFilter$1.create(PreConfiguredTokenFilter.java:116)
	at org.elasticsearch.index.analysis.CustomAnalyzer.createComponents(CustomAnalyzer.java:92)
	at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:136)
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:199)
	at org.elasticsearch.indices.analysis.AnalysisModuleTests.testStandardFilterBWC(AnalysisModuleTests.java:254)
```

**Comment by cbuescher** [comment]
Will mute but it looks straigh-forward to fix, so I'll do that after muting.
