### ISSUE TITLE
[ML] MlLifeCycleService and native controller shutdown run in wrong order after CTRL+C

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#38783]
I noticed this in 6.7.0 today, but it has probably been an issue for a long time.

When an ES node is stopped with `CTRL+C`, the native controller process shuts down before the `MlLifeCycleService.stop` method is called.  This means that the `MlLifeCycleService` gets an exception when it tries to issue kill commands on running jobs via the controller, because the controller is no longer running:

```
^C[2019-02-12T13:36:09,008][INFO ][o.e.x.m.p.NativeController] [l3ctNbR] Native controller process has stopped - no new native processes can be started
[2019-02-12T13:36:09,008][INFO ][o.e.n.Node               ] [l3ctNbR] stopping ...
[2019-02-12T13:36:09,021][INFO ][o.e.x.w.WatcherService   ] [l3ctNbR] stopping watch service, reason [shutdown initiated]
[2019-02-12T13:36:09,302][ERROR][o.e.x.m.p.NativeController] [l3ctNbR] Cannot kill process with PID [5925]: native controller process has stopped
[2019-02-12T13:36:09,303][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [l3ctNbR] [farequote] [autodetect/5925] [CCmdSkeleton.cc@45] Handled 0 records
[2019-02-12T13:36:09,304][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [l3ctNbR] [farequote] [autodetect/5925] [CAnomalyJob.cc@1352] Pruning all models
[2019-02-12T13:36:09,307][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [l3ctNbR] uncaught exception in thread [Thread-2]
org.elasticsearch.ElasticsearchException: Cannot kill process with PID [5925]: native controller process has stopped
        at org.elasticsearch.xpack.ml.process.NativeController.killProcess(NativeController.java:138) ~[?:?]
        at org.elasticsearch.xpack.ml.process.AbstractNativeProcess.kill(AbstractNativeProcess.java:182) ~[?:?]
        at org.elasticsearch.xpack.ml.job.process.autodetect.AutodetectCommunicator.killProcess(AutodetectCommunicator.java:192) ~[?:?]
        at org.elasticsearch.xpack.ml.job.process.autodetect.ProcessContext$KillBuilder.kill(ProcessContext.java:132) ~[?:?]
        at org.elasticsearch.xpack.ml.job.process.autodetect.AutodetectProcessManager.killAllProcessesOnThisNode(AutodetectProcessManager.java:221) ~[?:?]
        at org.elasticsearch.xpack.ml.MlLifeCycleService.stop(MlLifeCycleService.java:55) ~[?:?]
        at org.elasticsearch.xpack.ml.MlLifeCycleService$1.beforeStop(MlLifeCycleService.java:37) ~[?:?]
        at org.elasticsearch.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:88) ~[elasticsearch-6.7.0.jar:6.7.0]
        at org.elasticsearch.node.Node.stop(Node.java:848) ~[elasticsearch-6.7.0.jar:6.7.0]
        at org.elasticsearch.node.Node.close(Node.java:871) ~[elasticsearch-6.7.0.jar:6.7.0]
        at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:103) ~[elasticsearch-core-6.7.0.jar:6.7.0]
        at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:61) ~[elasticsearch-core-6.7.0.jar:6.7.0]
        at org.elasticsearch.bootstrap.Bootstrap$4.run(Bootstrap.java:184) ~[elasticsearch-6.7.0.jar:6.7.0]
```

By contrast if ES is stopped using a `kill -INT` from another shell this doesn't happen:

```
[2019-02-12T14:03:19,498][INFO ][o.e.n.Node               ] [l3ctNbR] stopping ...
[2019-02-12T14:03:19,515][INFO ][o.e.x.w.WatcherService   ] [l3ctNbR] stopping watch service, reason [shutdown initiated]
[2019-02-12T14:03:19,915][WARN ][o.e.x.m.j.p.a.o.AutoDetectResultProcessor] [l3ctNbR] [farequote] some results not processed due to the process being killed
[2019-02-12T14:03:19,917][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [l3ctNbR] [controller/6086] [Main.cc@148] Ml controller exiting
[2019-02-12T14:03:19,918][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [l3ctNbR] [controller/6086] [CDetachedProcessSpawner.cc@177] Child process with PID 6087 was terminated by signal 15
[2019-02-12T14:03:19,919][INFO ][o.e.x.m.p.NativeController] [l3ctNbR] Native controller process has stopped - no new native processes can be started
[2019-02-12T14:03:20,297][INFO ][o.e.n.Node               ] [l3ctNbR] stopped
[2019-02-12T14:03:20,297][INFO ][o.e.n.Node               ] [l3ctNbR] closing ...
[2019-02-12T14:03:20,316][INFO ][o.e.n.Node               ] [l3ctNbR] closed
```

**Comment by droberts195** [comment]
I think the solution to this that doesn't ruin the ability to run the controller directly at a shell prompt for debugging is to call `setsid()` early in the controller's `main()` and ignore errors.  (If the controller was started directly from a shell it will be a process group leader, and `setsid()` will fail, which is fine for this case.  If the controller was started from the ES JVM then it will not be process group leader and `setsid()` will make it a process group leader, thus stopping it receiving `CTRL+C` from the terminal.)
