### ISSUE TITLE
Watcher Template Registry attempts putting policy when ILM is disabled

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#38805]
Watcher bootstraps its template/ILM-policy at startup.
Even when ILM is disabled, it attempts to insert its policy.
This will fail because ILM endpoints are not registered when 
ILM is disabled.

Here is a stack tracing the issue:

```
java.lang.IllegalStateException: failed to find action [org.elasticsearch.xpack.core.indexlifecycle.action.PutLifecycleAction@d06806ea] to execute
        at org.elasticsearch.client.node.NodeClient.transportAction(NodeClient.java:116) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:393) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.core.indexlifecycle.client.ILMClient.putLifecyclePolicy(ILMClient.java:42) ~[?:?]
        at org.elasticsearch.xpack.watcher.support.WatcherIndexTemplateRegistry.lambda$putPolicy$3(WatcherIndexTemplateRegistry.java:188) ~[?:?]
        at org.elasticsearch.xpack.core.ClientHelper.executeAsyncWithOrigin(ClientHelper.java:82) ~[?:?]
        at org.elasticsearch.xpack.watcher.support.WatcherIndexTemplateRegistry.lambda$putPolicy$4(WatcherIndexTemplateRegistry.java:171) ~[?:?]
```

**Comment by hendrikmuhs** [comment]
Note: Monitoring integration tests use a `LocalStateMonitoring` plugin which adds Watcher to the plugins it loads for the test. This has the same problem: Watcher but no ILM. The log is full of errors although the tests run fine which is questionable. Would be good if this runs clean again:

```
./gradlew :x-pack:plugin:monitoring:internalClusterTest -Dtests.class=org.elasticsearch.xpack.monitoring.integration.MonitoringIT
```
