### ISSUE TITLE
ArrayCompareConditionSearchTests thread leak suite failure

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#38875]
ArrayCompareConditionSearchTests test suite is flaky due to the integ cluster's 
SchedulerEngine's thread `trigger_engine_scheduler` not shutting down in time.

failure instance in CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk12,nodes=immutable&&linux&&docker/240/console

num occurrences: 6 times in last 6 months.

stacktrace:

```
ERROR   0.00s J2 | ArrayCompareConditionSearchTests (suite) <<< FAILURES!
   > Throwable #1: com.carrotsearch.randomizedtesting.ThreadLeakError: 1 thread leaked from SUITE scope at org.elasticsearch.xpack.watcher.condition.ArrayCompareConditionSearchTests: 
   >    1) Thread[id=337, name=elasticsearch[node_sm1][trigger_engine_scheduler][T#1], state=TIMED_WAITING, group=TGRP-ArrayCompareConditionSearchTests]
   >         at java.base@12/jdk.internal.misc.Unsafe.park(Native Method)
   >         at java.base@12/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:235)
   >         at java.base@12/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
   >         at java.base@12/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
   >         at java.base@12/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
   >         at java.base@12/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
   >         at java.base@12/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
   >         at java.base@12/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   >         at java.base@12/java.lang.Thread.run(Thread.java:835)
   > 	at __randomizedtesting.SeedInfo.seed([3D43839813A5AEA5]:0)Throwable #2: com.carrotsearch.randomizedtesting.ThreadLeakError: There are still zombie threads that couldn't be terminated:
   >    1) Thread[id=337, name=elasticsearch[node_sm1][trigger_engine_scheduler][T#1], state=TIMED_WAITING, group=TGRP-ArrayCompareConditionSearchTests]
   >         at java.base@12/jdk.internal.misc.Unsafe.park(Native Method)
   >         at java.base@12/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:235)
   >         at java.base@12/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
   >         at java.base@12/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
   >         at java.base@12/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
   >         at java.base@12/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
   >         at java.base@12/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
   >         at java.base@12/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   >         at java.base@12/java.lang.Thread.run(Thread.java:835)
   > 	at __randomizedtesting.SeedInfo.seed([3D43839813A5AEA5]:0)
Completed [111/140] on J2 in 18.31s, 1 test, 2 errors <<< FAILURES!
```

RollupIT had the same [problem](https://github.com/elastic/elasticsearch/issue/31258) because it leverages the SchedulerEngine, its [solution](https://github.com/elastic/elasticsearch/pull/31977) was to move away from integ tests and rewrite the test as rest tests. It looks like this test suite can do the same.

**Comment by talevy** [comment]
Looks like this also happens sometimes in `TransformIntegrationTests`

**Comment by jaymode** [comment]
Maybe I am missing something, but it does not look like watcher uses the SchedulerEngine as of 0c7c2f521c88293b909483235aa1c0c0b9444801. I see uses by the LicenseService, DataFrame, IndexLifecycleService, and Rollup.

LicenseService is an AbstractLifecycleService and shuts the SchedulerEngine down. I am not seeing DataFrame or Rollup shutting it down. IndexLifecycleService may have a race where an extra scheduler engine could get created. I'll pick up working on this.
