### ISSUE TITLE
[CI] MedianAbsoluteDeviationAggregatorTests.testSomeMatchesSortedNumericDocValues fails (seed-specific)

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#38937]
My PR build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/8268/console got the following error:

```
FAILURE 0.06s J4 | MedianAbsoluteDeviationAggregatorTests.testSomeMatchesSortedNumericDocValues <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: within <10.0> percent of <447718.0>
   >      but: was <501660.0>
   > 	at __randomizedtesting.SeedInfo.seed([9BA06947D4BA0876:29F621FB9B5A78F0]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.lambda$testSomeMatchesSortedNumericDocValues$6(MedianAbsoluteDeviationAggregatorTests.java:105)
   > 	at org.elasticsearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.testCase(MedianAbsoluteDeviationAggregatorTests.java:184)
   > 	at org.elasticsearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.testSomeMatchesSortedNumericDocValues(MedianAbsoluteDeviationAggregatorTests.java:98)
   > 	at java.lang.Thread.run(Thread.java:748)
```

This reproduces locally using:

```
FAILURE 0.06s J4 | MedianAbsoluteDeviationAggregatorTests.testSomeMatchesSortedNumericDocValues <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: within <10.0> percent of <447718.0>
   >      but: was <501660.0>
   > 	at __randomizedtesting.SeedInfo.seed([9BA06947D4BA0876:29F621FB9B5A78F0]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.lambda$testSomeMatchesSortedNumericDocValues$6(MedianAbsoluteDeviationAggregatorTests.java:105)
   > 	at org.elasticsearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.testCase(MedianAbsoluteDeviationAggregatorTests.java:184)
   > 	at org.elasticsearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.testSomeMatchesSortedNumericDocValues(MedianAbsoluteDeviationAggregatorTests.java:98)
   > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by henningandersen** [comment]
As far as I can see this never failed before, so will not mute it for now.
