### ISSUE TITLE
Calls to Hipchat integration in 5.6 are unauthorized

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#38994]
looks like calls to Hipchat in the 5.6 branch are unauthorized in CI

```
   > Throwable #1: java.lang.AssertionError: Expected no failures, but got [Unauthorized. The provided authentication token is invalid.]
   > Expected: is <true>
   >      but: was <false>
   > 	at __randomizedtesting.SeedInfo.seed([2A87E0C0CF9DF6AD:667C928888E1CC07]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.xpack.watcher.test.integration.HipChatServiceTests.assertSentMessagesAreValid(HipChatServiceTests.java:231)
```

```
 1> [2019-02-16T01:29:46,418][INFO ][o.e.x.w.t.i.HipChatServiceTests] Response: [status=[401], headers=[[access-control-allow-origin: [*]], [date: [Fri, 15 Feb 2019 23:29:46 GMT]], [server: [nginx]], [content-length: [104]], [connection: [keep-alive]], [content-type: [application/json]], [access-control-expose-headers: [Date, ETag, Link, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-Backoff]]], body=[{
  1>   "error": {
  1>     "code": 401,
  1>     "message": "Invalid OAuth session",
  1>     "type": "Unauthorized"
  1>   }
  1> }]]
```

failed tests:

```
org.elasticsearch.xpack.watcher.test.integration.HipChatServiceTests testDefaultValuesForColorAndFormatWorks
org.elasticsearch.xpack.watcher.test.integration.HipChatServiceTests testSendMessageIntegrationAccount
org.elasticsearch.xpack.watcher.test.integration.HipChatServiceTests testSendMessageUserAccount
org.elasticsearch.xpack.watcher.test.integration.HipChatServiceTests testSendMessageV1Account
org.elasticsearch.xpack.watcher.test.integration.HipChatServiceTests testWatchWithHipChatAction
```

**Comment by dakrone** [comment]
Related: #39160

**Comment by dakrone** [comment]
I think we can close this one now since Hipchat support has been removed.
