### ISSUE TITLE
DocsClientYamlTestSuiteIT {yaml=reference/indices/flush/line_77} failures

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#39032]
Happened over the weekend, 3 times in pull requests

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+oss-distro-docs/11482/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+oss-distro-docs/11479/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+oss-distro-docs/11478/console

It doesn't reproduce locally

```
1> [2019-02-16T17:53:02,865][INFO ][o.e.s.DocsClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "indices" : {
  1>         "twitter" : {
  1>           "shards" : {
  1>             "0" : [
  1>               {
  1>                 "commit" : {
  1>                   "id" : "grZxxUI6p7Nj8c5DtSOFDA==",
  1>                   "generation" : 3,
  1>                   "user_data" : {
  1>                     "local_checkpoint" : "-1",
  1>                     "max_unsafe_auto_id_timestamp" : "-1",
  1>                     "min_retained_seq_no" : "0",
  1>                     "translog_uuid" : "7nn0FG3TQUiSF1FgowUEnw",
  1>                     "history_uuid" : "2_qNvufiQr-cupAsMEBQcg",
  1>                     "sync_id" : "EkVW6judSOiPxB6jUd3giQ",
  1>                     "translog_generation" : "2",
  1>                     "max_seq_no" : "-1"
  1>                   },
  1>                   "num_docs" : 0
  1>                 }
  1>               }
  1>             ]
  1>           }
  1>         }
  1>       }
  1>     }
  1>   }
  1> }]
  1> [2019-02-16T17:53:02,896][INFO ][o.e.s.DocsClientYamlTestSuiteIT] [test] [yaml=reference/indices/flush/line_77] after test
  1> [2019-02-16T17:53:02,897][ERROR][o.e.s.DocsClientYamlTestSuiteIT] [test] This failing test was generated by documentation starting at reference/indices/flush.asciidoc:line_77. It may include many snippets. See docs/README.asciidoc for an explanation of test generation.
ERROR   0.19s | DocsClientYamlTestSuiteIT.test {yaml=reference/indices/flush/line_77} <<< FAILURES!
   > Throwable #1: java.lang.RuntimeException: Failure at [reference/indices/flush:102]: stashed value not found for key [body.indices.twitter.shards.0.0.commit.user_data.retention_leases]
   > 	at __randomizedtesting.SeedInfo.seed([30A19908878C797D:B8F5A6D229701485]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:389)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:364)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.lang.IllegalArgumentException: stashed value not found for key [body.indices.twitter.shards.0.0.commit.user_data.retention_leases]
   > 	at org.elasticsearch.test.rest.yaml.Stash.unstash(Stash.java:118)
   > 	at org.elasticsearch.test.rest.yaml.Stash.getValue(Stash.java:97)
   > 	at org.elasticsearch.test.rest.yaml.Stash.getValue(Stash.java:182)
   > 	at org.elasticsearch.test.rest.yaml.Stash.unstashObject(Stash.java:159)
   > 	at org.elasticsearch.test.rest.yaml.Stash.unstashObject(Stash.java:161)
   > 	at org.elasticsearch.test.rest.yaml.Stash.unstashObject(Stash.java:161)
   > 	at org.elasticsearch.test.rest.yaml.Stash.unstashObject(Stash.java:142)
   > 	at org.elasticsearch.test.rest.yaml.Stash.unstashObject(Stash.java:161)
   > 	at org.elasticsearch.test.rest.yaml.Stash.unstashObject(Stash.java:161)
   > 	at org.elasticsearch.test.rest.yaml.Stash.unstashObject(Stash.java:161)
   > 	at org.elasticsearch.test.rest.yaml.Stash.unstashObject(Stash.java:161)
   > 	at org.elasticsearch.test.rest.yaml.Stash.replaceStashedValues(Stash.java:129)
   > 	at org.elasticsearch.test.rest.yaml.section.Assertion.resolveExpectedValue(Assertion.java:53)
   > 	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:380)
   > 	... 37 more
```

**Comment by jasontedor** [comment]
That’s puzzling. Anyway, this goes away with #39004. See: https://github.com/elastic/elasticsearch/pull/39004/files#diff-31f3afe6b50f556a95a396324be535e5L107
