### ISSUE TITLE
[CI] GatewayMetaStateTests.testAtomicityWithFailures

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#39077]
The following has failed in a PR build:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/8533/console

```
REPRODUCE WITH: ./gradlew :server:unitTest -Dtests.seed=B2CA639652A398C6 -Dtests.class=org.elasticsearch.gateway.GatewayMetaStateTests -Dtests.method="testAtomicityWithFailures" -Dtests.security.manager=true -Dtests.locale=nn-NO -Dtests.timezone=Asia/Jakarta -Dcompiler.java=11 -Druntime.java=8
ERROR   0.30s | GatewayMetaStateTests.testAtomicityWithFailures <<< FAILURES!
   > Throwable #1: java.io.IOException: failed to find global metadata [generation: 0]
   >    at __randomizedtesting.SeedInfo.seed([B2CA639652A398C6:8F4B0E643D33025F]:0)
   >    at org.elasticsearch.gateway.MetaStateService.loadFullState(MetaStateService.java:85)
   >    at org.elasticsearch.gateway.GatewayMetaStateTests.testAtomicityWithFailures(GatewayMetaStateTests.java:427)
```

**It reproduces!**

I will follow up with the mute, and I will take a swing at it!

**Comment by albertzaharovits** [comment]
@andrershov I am going to relabel this and unassign myself.
Judging by your comment in https://github.com/elastic/elasticsearch/pull/39117#issuecomment-465518436 the test is better to be left disabled rather than changed. It might change when the code in main also changes.
I don't think the `>test-failure` label is suitable for these types of "known issues". For a lack of a better one, I have added the `>test` label.
