### ISSUE TITLE
[CI] XPackUsageIT#testXPackCcrUsage failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#39126]
```
2> NOTE: Linux 4.15.0-1027-gcp amd64/Oracle Corporation 1.8.0_202 (64-bit)/cpus=16,threads=1,free=369380856,total=514850816
   > Throwable #1: org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:44561], URI [/messages-20200101/_ccr/pause_follow], status line [HTTP/1.1 400 Bad Request]
   > {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"no shard follow tasks for [messages-20200101]"}],"type":"illegal_argument_exception","reason":"no shard follow tasks for [messages-20200101]"},"status":400}
  2> NOTE: All tests run in this JVM: [FollowIndexIT, XPackUsageIT]
   >    at __randomizedtesting.SeedInfo.seed([4E0146F66A0387F0:78D4F4FB5985FE7C]:0)
   >    at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:936)
   >    at org.elasticsearch.client.RestClient.performRequest(RestClient.java:233)
   >    at org.elasticsearch.xpack.ccr.ESCCRRestTestCase.pauseFollow(ESCCRRestTestCase.java:87)
   >    at org.elasticsearch.xpack.ccr.ESCCRRestTestCase.pauseFollow(ESCCRRestTestCase.java:83)
   >    at org.elasticsearch.xpack.ccr.XPackUsageIT.testXPackCcrUsage(XPackUsageIT.java:47)
   >    at java.lang.Thread.run(Thread.java:748)
```

Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+intake/140

**Comment by talevy** [comment]
I've muted these tests in the tagged versions, fyi ^

**Comment by martijnvg** [comment]
This is a test bug, sometimes index following has not yet started. The `messages-20200101` gets auto followed and we only check for the existence of the corresponding follower index and not whether index following has really started. The pause follow index api fails if there are no shard follow tasks to stop.

The fix is to ensure that index following is active.

Not that this is test problem, is only an issue for auto followed indices. This is because the test does not perform the index following, but the auto follower that runs in the background.
