### ISSUE TITLE
MinimumMasterNodesIT#testThreeNodesNoMasterBlock failures

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#39172]
Failed in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+internalClusterTest/940/consoleText

This [has failed 16 times](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testThreeNodesNoMasterBlock),sort:!(process.time-start,desc))) since it was introduced in https://github.com/elastic/elasticsearch/pull/37428 : 

```
ERROR   92.5s J3 | MinimumMasterNodesIT.testThreeNodesNoMasterBlock <<< FAILURES!
   > Throwable #1: MasterNotDiscoveredException[ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];]]; nested: ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];];
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:259)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:322)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:249)
   > 	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:549)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];]
   > 	at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:191)
   > 	at org.elasticsearch.action.admin.cluster.tasks.TransportPendingClusterTasksAction.checkBlock(TransportPendingClusterTasksAction.java:59)
   > 	at org.elasticsearch.action.admin.cluster.tasks.TransportPendingClusterTasksAction.checkBlock(TransportPendingClusterTasksAction.java:37)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:170)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.start(TransportMasterNodeAction.java:161)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:138)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:58)
   > 	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:145)
   > 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:121)
   > 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:64)
   > 	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83)
   > 	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72)
   > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:393)
   > 	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:65)
   > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:393)
   > 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:382)
   > 	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:676)
   > 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:45)
   > 	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:52)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureColor(ESIntegTestCase.java:974)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:931)
   > 	at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:920)
   > 	at org.elasticsearch.cluster.MinimumMasterNodesIT.testThreeNodesNoMasterBlock(MinimumMasterNodesIT.java:268)
   > 	... 1 moreThrowable #2: MasterNotDiscoveredException[ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];]]; nested: ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];];
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:259)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:322)
   > 	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:249)
   > 	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:549)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681)
   > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];]
   > 	at org.elasticsearch.cluster.block.ClusterBlocks.indicesAllowReleaseResources(ClusterBlocks.java:248)
   > 	at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.checkBlock(TransportDeleteIndexAction.java:81)
   > 	at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.checkBlock(TransportDeleteIndexAction.java:47)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:170)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.start(TransportMasterNodeAction.java:161)
   > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:138)
   > 	at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.doExecute(TransportDeleteIndexAction.java:76)
   > 	at org.elasticsearch.action.admin.indices.delete.TransportDeleteIndexAction.doExecute(TransportDeleteIndexAction.java:47)
   > 	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:145)
   > 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:121)
   > 	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:79)
   > 	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:74)
   > 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63)
   > 	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1077)
   > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   > 	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:192)
   > 	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1036)
   > 	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:922)
   > 	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:753)
   > 	at org.elasticsearch.transport.TcpTransport.consumeNetworkReads(TcpTransport.java:780)
   > 	at org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:241)
   > 	at org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:213)
   > 	at org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:47)
   > 	at org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:119)
   > 	at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:398)
   > 	at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:246)
   > 	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:172)
   > 	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:129)
   > 	... 1 more
Completed [219/320] on J3 in 97.37s, 3 tests, 1 error <<< FAILURES!
```

**Comment by tlrx** [comment]
This issue appears twice a day on master/7.x/7.0 branches, so I muted the test.

Last failure:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8,nodes=immutable&&linux&&docker/42/consoleFull

it does not reproduce using:
```
./gradlew :server:integTest \
  -Dtests.seed=6D83A2FB50FBAA3D \
  -Dtests.class=org.elasticsearch.cluster.MinimumMasterNodesIT \
  -Dtests.method="testThreeNodesNoMasterBlock" \
  -Dtests.security.manager=true \
  -Dtests.locale=el-GR \
  -Dtests.timezone=Antarctica/Palmer \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

Relevant execution log: [consoleText.txt](https://github.com/elastic/elasticsearch/files/2910165/consoleText.txt)

**Comment by ywelsch** [comment]
I've unmuted this test on master as it does not locally reproduce and I'm unsure if the problem here has not been solved by existing work.

**Comment by ywelsch** [comment]
No recent failure -> Closing

**Comment by iverase** [comment]
Two more failures today so it seems there is still something flaky with the test:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=fedora-29&&immutable/445/console

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+periodic/23/console

**Comment by original-brownbear** [comment]
I'll take another look

**Comment by original-brownbear** [comment]
I can reproduce this locally with a 1% rate with seed `A9E3D78D63D6D79D`.

**Comment by ywelsch** [comment]
I have a fix here: https://github.com/elastic/elasticsearch/pull/42576
