### ISSUE TITLE
CcrRetentionLeaseIT#testUnfollowFailsToRemoveRetentionLeases failure

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#39202]
exception:

```
junit.framework.AssertionFailedError: Expected exception ElasticsearchException but no exception was thrown
	at __randomizedtesting.SeedInfo.seed([1F6AEBF6C12B11A6:F576053C3B6B2CAD]:0)
	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2685)
	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2670)
	at org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.testUnfollowFailsToRemoveRetentionLeases(CcrRetentionLeaseIT.java:513)
```

This reproduces locally (occasionally)

```
./gradlew :x-pack:plugin:ccr:internalClusterTest \
  -Dtests.seed=1F6AEBF6C12B11A6 \
  -Dtests.class=org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT \
  -Dtests.method="testUnfollowFailsToRemoveRetentionLeases" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-NZ \
  -Dtests.timezone=Canada/Saskatchewan \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

CI links:

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+intake/188/console

**Comment by talevy** [comment]
Closing as duplicate of #39201
