### ISSUE TITLE
CcrRepositoryIT.testIndividualActionsTimeout failing

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#39245]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+multijob-unix-compatibility/os=ubuntu-18.04&&immutable/30/consoleFull
```
./gradlew :x-pack:plugin:ccr:internalClusterTest -Dtests.seed=2667A23CA6A21E2D -Dtests.class=org.elasticsearch.xpack.ccr.CcrRepositoryIT -Dtests.method="testIndividualActionsTimeout" -Dtests.security.manager=true -Dtests.locale=ar-YE -Dtests.timezone=Africa/Mogadishu -Dcompiler.java=11 -Druntime.java=8
```
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=openjdk12,nodes=immutable&&linux&&docker/29/consoleFull
```
./gradlew :x-pack:plugin:ccr:internalClusterTest -Dtests.seed=B87146B09D971D1A -Dtests.class=org.elasticsearch.xpack.ccr.CcrRepositoryIT -Dtests.method="testIndividualActionsTimeout" -Dtests.security.manager=true -Dtests.locale=fr-CH -Dtests.timezone=Asia/Nicosia -Dcompiler.java=11 -Druntime.java=12
```
Cannot reproduce locally. 

Two builds failing due to this test, same exception for both:

```
03:54:14   1> [2019-02-21T12:54:11,307][INFO ][o.e.x.c.CcrRepositoryIT  ] [testIndividualActionsTimeout] after test
03:54:14 FAILURE 25.4s J3 | CcrRepositoryIT.testIndividualActionsTimeout <<< FAILURES!
03:54:14    > Throwable #1: java.lang.AssertionError: [index1][0], node[_ciLl-yVQIGl6841f9jQSQ], [P], s[STARTED], a[id=0Ds8YVm2RmGPV41qAAQg2Q] has unreleased snapshotted index commits
03:54:14    > 	at __randomizedtesting.SeedInfo.seed([2667A23CA6A21E2D:427A4EE015D02C1E]:0)
03:54:14    > 	at org.elasticsearch.test.InternalTestCluster.lambda$assertNoSnapshottedIndexCommit$8(InternalTestCluster.java:1281)
03:54:14    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:858)
03:54:14    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:832)
03:54:14    > 	at org.elasticsearch.test.InternalTestCluster.assertNoSnapshottedIndexCommit(InternalTestCluster.java:1272)
03:54:14    > 	at org.elasticsearch.test.InternalTestCluster.beforeIndexDeletion(InternalTestCluster.java:1200)
03:54:14    > 	at org.elasticsearch.xpack.CcrIntegTestCase.afterTest(CcrIntegTestCase.java:194)
03:54:14    > 	at java.lang.Thread.run(Thread.java:748)
03:54:14    > 	Suppressed: java.lang.AssertionError: [index1][0], node[_ciLl-yVQIGl6841f9jQSQ], [P], s[STARTED], a[id=0Ds8YVm2RmGPV41qAAQg2Q] has unreleased snapshotted index commits
03:54:14    > 		at org.elasticsearch.test.InternalTestCluster.lambda$assertNoSnapshottedIndexCommit$8(InternalTestCluster.java:1281)
03:54:14    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:846)
03:54:14    > 		... 39 more
03:54:14    > 	Suppressed: java.lang.AssertionError: [index1][0], node[_ciLl-yVQIGl6841f9jQSQ], [P], s[STARTED], a[id=0Ds8YVm2RmGPV41qAAQg2Q] has unreleased snapshotted index commits
03:54:14    > 		at org.elasticsearch.test.InternalTestCluster.lambda$assertNoSnapshottedIndexCommit$8(InternalTestCluster.java:1281)
03:54:14    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:846)
03:54:14    > 		... 39 more
03:54:14    > 	Suppressed: java.lang.AssertionError: [index1][0], node[_ciLl-yVQIGl6841f9jQSQ], [P], s[STARTED], a[id=0Ds8YVm2RmGPV41qAAQg2Q] has unreleased snapshotted index commits
03:54:14    > 		at org.elasticsearch.test.InternalTestCluster.lambda$assertNoSnapshottedIndexCommit$8(InternalTestCluster.java:1281)
03:54:14    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:846)
03:54:14    > 		... 39 more
03:54:14    > 	Suppressed: java.lang.AssertionError: [index1][0], node[_ciLl-yVQIGl6841f9jQSQ], [P], s[STARTED], a[id=0Ds8YVm2RmGPV41qAAQg2Q] has unreleased snapshotted index commits
03:54:14    > 		at org.elasticsearch.test.InternalTestCluster.lambda$assertNoSnapshottedIndexCommit$8(InternalTestCluster.java:1281)
03:54:14    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:846)
03:54:14    > 		... 39 more
03:54:14    > 	Suppressed: java.lang.AssertionError: [index1][0], node[_ciLl-yVQIGl6841f9jQSQ], [P], s[STARTED], a[id=0Ds8YVm2RmGPV41qAAQg2Q] has unreleased snapshotted index commits
03:54:14    > 		at org.elasticsearch.test.InternalTestCluster.lambda$assertNoSnapshottedIndexCommit$8(InternalTestCluster.java:1281)
03:54:14    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:846)
03:54:14    > 		... 39 more
03:54:14    > 	Suppressed: java.lang.AssertionError: [index1][0], node[_ciLl-yVQIGl6841f9jQSQ], [P], s[STARTED], a[id=0Ds8YVm2RmGPV41qAAQg2Q] has unreleased snapshotted index commits
03:54:14    > 		at org.elasticsearch.test.InternalTestCluster.lambda$assertNoSnapshottedIndexCommit$8(InternalTestCluster.java:1281)
03:54:14    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:846)
03:54:14    > 		... 39 more
03:54:14    > 	Suppressed: java.lang.AssertionError: [index1][0], node[_ciLl-yVQIGl6841f9jQSQ], [P], s[STARTED], a[id=0Ds8YVm2RmGPV41qAAQg2Q] has unreleased snapshotted index commits
03:54:14    > 		at org.elasticsearch.test.InternalTestCluster.lambda$assertNoSnapshottedIndexCommit$8(InternalTestCluster.java:1281)
03:54:14    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:846)
03:54:14    > 		... 39 more
03:54:14    > 	Suppressed: java.lang.AssertionError: [index1][0], node[_ciLl-yVQIGl6841f9jQSQ], [P], s[STARTED], a[id=0Ds8YVm2RmGPV41qAAQg2Q] has unreleased snapshotted index commits
03:54:14    > 		at org.elasticsearch.test.InternalTestCluster.lambda$assertNoSnapshottedIndexCommit$8(InternalTestCluster.java:1281)
03:54:14    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:846)
03:54:14    > 		... 39 more
03:54:14    > 	Suppressed: java.lang.AssertionError: [index1][0], node[_ciLl-yVQIGl6841f9jQSQ], [P], s[STARTED], a[id=0Ds8YVm2RmGPV41qAAQg2Q] has unreleased snapshotted index commits
03:54:14    > 		at org.elasticsearch.test.InternalTestCluster.lambda$assertNoSnapshottedIndexCommit$8(InternalTestCluster.java:1281)
03:54:14    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:846)
03:54:14    > 		... 39 more
03:54:14    > 	Suppressed: java.lang.AssertionError: [index1][0], node[_ciLl-yVQIGl6841f9jQSQ], [P], s[STARTED], a[id=0Ds8YVm2RmGPV41qAAQg2Q] has unreleased snapshotted index commits
03:54:14    > 		at org.elasticsearch.test.InternalTestCluster.lambda$assertNoSnapshottedIndexCommit$8(InternalTestCluster.java:1281)
03:54:14    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:846)
03:54:14    > 		... 39 more
03:54:14    > 	Suppressed: java.lang.AssertionError: [index1][0], node[_ciLl-yVQIGl6841f9jQSQ], [P], s[STARTED], a[id=0Ds8YVm2RmGPV41qAAQg2Q] has unreleased snapshotted index commits
03:54:14    > 		at org.elasticsearch.test.InternalTestCluster.lambda$assertNoSnapshottedIndexCommit$8(InternalTestCluster.java:1281)
03:54:14    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:846)
03:54:14    > 		... 39 more
03:54:14    > 	Suppressed: java.lang.AssertionError: [index1][0], node[_ciLl-yVQIGl6841f9jQSQ], [P], s[STARTED], a[id=0Ds8YVm2RmGPV41qAAQg2Q] has unreleased snapshotted index commits
03:54:14    > 		at org.elasticsearch.test.InternalTestCluster.lambda$assertNoSnapshottedIndexCommit$8(InternalTestCluster.java:1281)
03:54:14    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:846)
03:54:14    > 		... 39 more
03:54:14    > 	Suppressed: java.lang.AssertionError: [index1][0], node[_ciLl-yVQIGl6841f9jQSQ], [P], s[STARTED], a[id=0Ds8YVm2RmGPV41qAAQg2Q] has unreleased snapshotted index commits
03:54:14    > 		at org.elasticsearch.test.InternalTestCluster.lambda$assertNoSnapshottedIndexCommit$8(InternalTestCluster.java:1281)
03:54:14    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:846)
03:54:14    > 		... 39 more
```

Other issues refer to this test, but they all seem to have a different cause.

**Comment by markharwood** [comment]
[Build stats ](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'test:testIndividualActionsTimeout%20AND%20class:org.elasticsearch.xpack.ccr.CcrRepositoryIT%20AND%20stacktrace:%22has%20unreleased%20snapshotted%20index%20commits%22'),sort:!(time,desc))) tracking
