### ISSUE TITLE
[CI] SplitIndexIT failure in master 

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#39242]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk12,nodes=immutable&&linux&&docker/255/consoleFull

Unable to reproduce no matter how many times it is ran. Even tried running the whole `SplitIndexIT` suite with the given parameters to see if it was somehow test interactions, but it would not reproduce. 
```
REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=E882FA6D8C5571D1 \
  -Dtests.class=org.elasticsearch.action.admin.indices.create.SplitIndexIT \
  -Dtests.method="testSplitIndexPrimaryTerm" \
  -Dtests.security.manager=true \
  -Dtests.locale=sv-AX \
  -Dtests.timezone=America/Argentina/Buenos_Aires \
  -Dcompiler.java=12 \
  -Druntime.java=12

REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=E882FA6D8C5571D1 \
  -Dtests.class=org.elasticsearch.action.admin.indices.create.SplitIndexIT \
  -Dtests.method="testCreateSplitWithIndexSort" \
  -Dtests.security.manager=true \
  -Dtests.locale=sv-AX \
  -Dtests.timezone=America/Argentina/Buenos_Aires \
  -Dcompiler.java=12 \
  -Druntime.java=12

REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=E882FA6D8C5571D1 \
  -Dtests.class=org.elasticsearch.action.admin.indices.create.SplitIndexIT \
  -Dtests.method="testSplitFromOneToN" \
  -Dtests.security.manager=true \
  -Dtests.locale=sv-AX \
  -Dtests.timezone=America/Argentina/Buenos_Aires \
  -Dcompiler.java=12 \
  -Druntime.java=12
```

Failure for all three was failing after test cleanup. 
```
22:23:16    > Throwable #1: java.lang.AssertionError: Accounting breaker not reset to 0 on node: node_s0, are there still Lucene indices around?
22:23:16    > Expected: <0L>
22:23:16    >      but: was <1254L>
22:23:16    > 	at __randomizedtesting.SeedInfo.seed([E882FA6D8C5571D1:1A1891C3EA21DD35]:0)
22:23:16    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
22:23:16    > 	at org.elasticsearch.test.InternalTestCluster.ensureEstimatedStats(InternalTestCluster.java:2461)
22:23:16    > 	at org.elasticsearch.test.TestCluster.assertAfterTest(TestCluster.java:94)
22:23:16    > 	at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2496)
22:23:16    > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:593)
22:23:16    > 	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2191)
22:23:16    > 	at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
22:23:16    > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:23:16    > 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
22:23:16    > 	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by albertzaharovits** [comment]
I believe this should be ascribed to https://github.com/elastic/elasticsearch/issues/30290 for which a potential fix in https://github.com/elastic/elasticsearch/pull/39211 has been approved.

Closing this as duplicate, please reopen if somebody feels otherwise.

**Comment by benwtrent** [comment]
@albertzaharovits excellent! Thanks for pointing that out. I will make sure additional related failures point to that fix.
