### ISSUE TITLE
EvilNodeTests failure in CI

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#39302]
This fails reproducibly in 5.6:
```
REPRODUCE WITH: ./gradlew :qa:evil-tests:test \
  -Dtests.seed=BDA213671F433276 \
  -Dtests.class=org.elasticsearch.node.EvilNodeTests \
  -Dtests.method="testDefaultPathDataIncludedInPathData" \
  -Dtests.security.manager=false \
  -Dtests.locale=pl \
  -Dtests.timezone=America/Dominica
```

```
> Throwable #1: java.nio.file.FileSystemException: /Users/romseygeek/projects/elasticsearch-5.6/qa/evil-tests/build/testrun/test/J0/temp/org.elasticsearch.node.EvilNodeTests_BDA213671F433276-001/tempDir-004/link -> /Users/romseygeek/projects/elasticsearch-5.6/qa/evil-tests/build/testrun/test/J0/temp/org.elasticsearch.node.EvilNodeTests_BDA213671F433276-001/tempDir-003: Operation not permitted
   >    at __randomizedtesting.SeedInfo.seed([BDA213671F433276:8DF45C3472C48CCF]:0)
   >    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
   >    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
   >    at sun.nio.fs.UnixFileSystemProvider.createLink(UnixFileSystemProvider.java:476)
   >    at org.apache.lucene.mockfile.FilterFileSystemProvider.createLink(FilterFileSystemProvider.java:233)
   >    at org.apache.lucene.mockfile.FilterFileSystemProvider.createLink(FilterFileSystemProvider.java:233)
   >    at java.nio.file.Files.createLink(Files.java:1086)
   >    at org.elasticsearch.node.EvilNodeTests.testDefaultPathDataIncludedInPathData(EvilNodeTests.java:61)
   >    at java.lang.Thread.run(Thread.java:748)
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+multijob-darwin-compatibility/258/console

**Comment by danielmitterdorfer** [comment]
Not sure why this one did not close automatically but it is resolved by https://github.com/elastic/elasticsearch/pull/39791.
