### ISSUE TITLE
StableMasterDisruptionIT fails in CI

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#39314]
StableMasterDisruptionIT.testFollowerCheckerDetectsUnresponsiveNodeAfterMasterReelection failed for the first time today.  The failure does not reproduce:
```
Caused by: java.lang.AssertionError: {"cluster_uuid":"wT_jvqnWSqWikWaIwpJSSg","version":5,"state_uuid":"lQhkDmd_SPOEmT1TTAsDNQ","master_node":null,"blocks":{"global":{"2":{"description":"no master","retryable":true,"levels":["write","metadata_write"]}}},"nodes":{"zHPKN-5CTsaIbXnzoAUA8w":{"name":"node_t0","ephemeral_id":"0EFqlulZQZOaUeCvXxUQiw","transport_address":"127.0.0.1:41269","attributes":{}},"nHaB1FXFRxe7roXCYCMIcg":{"name":"node_t3","ephemeral_id":"EjWuFcSMTKOXCAFsogNixQ","transport_address":"127.0.0.1:45337","attributes":{}},"zV4RHQfYRMmpvz6J1y88Bw":{"name":"node_t2","ephemeral_id":"DTtYf6TZQTK2pL15WNuiYQ","transport_address":"127.0.0.1:35081","attributes":{}},"rAYJfaApT3auq8EBxJDzMQ":{"name":"node_t1","ephemeral_id":"U2v3FHaDSRGzDhWIk_2orA","transport_address":"127.0.0.1:41383","attributes":{}}},"metadata":{"cluster_uuid":"wT_jvqnWSqWikWaIwpJSSg","cluster_coordination":{"term":1,"last_committed_config":["zV4RHQfYRMmpvz6J1y88Bw","rAYJfaApT3auq8EBxJDzMQ","zHPKN-5CTsaIbXnzoAUA8w"],"last_accepted_config":["zV4RHQfYRMmpvz6J1y88Bw","rAYJfaApT3auq8EBxJDzMQ","zHPKN-5CTsaIbXnzoAUA8w"],"voting_config_exclusions":[{"node_id":"nHaB1FXFRxe7roXCYCMIcg","node_name":"node_t3"}]},"templates":{},"indices":{},"index-graveyard":{"tombstones":[]}},"routing_table":{"indices":{}},"routing_nodes":{"unassigned":[],"nodes":{"nHaB1FXFRxe7roXCYCMIcg":[],"rAYJfaApT3auq8EBxJDzMQ":[],"zHPKN-5CTsaIbXnzoAUA8w":[],"zV4RHQfYRMmpvz6J1y88Bw":[]}}} vs {"cluster_uuid":"wT_jvqnWSqWikWaIwpJSSg","version":6,"state_uuid":"iYC-SDemQD-T76Gy_zuyng","master_node":null,"blocks":{"global":{"2":{"description":"no master","retryable":true,"levels":["write","metadata_write"]}}},"nodes":{"zHPKN-5CTsaIbXnzoAUA8w":{"name":"node_t0","ephemeral_id":"0EFqlulZQZOaUeCvXxUQiw","transport_address":"127.0.0.1:41269","attributes":{}},"nHaB1FXFRxe7roXCYCMIcg":{"name":"node_t3","ephemeral_id":"EjWuFcSMTKOXCAFsogNixQ","transport_address":"127.0.0.1:45337","attributes":{}},"zV4RHQfYRMmpvz6J1y88Bw":{"name":"node_t2","ephemeral_id":"DTtYf6TZQTK2pL15WNuiYQ","transport_address":"127.0.0.1:35081","attributes":{}},"rAYJfaApT3auq8EBxJDzMQ":{"name":"node_t1","ephemeral_id":"U2v3FHaDSRGzDhWIk_2orA","transport_address":"127.0.0.1:41383","attributes":{}}},"metadata":{"cluster_uuid":"wT_jvqnWSqWikWaIwpJSSg","cluster_coordination":{"term":3,"last_committed_config":["zV4RHQfYRMmpvz6J1y88Bw","rAYJfaApT3auq8EBxJDzMQ","zHPKN-5CTsaIbXnzoAUA8w"],"last_accepted_config":["zV4RHQfYRMmpvz6J1y88Bw","rAYJfaApT3auq8EBxJDzMQ","zHPKN-5CTsaIbXnzoAUA8w"],"voting_config_exclusions":[{"node_id":"nHaB1FXFRxe7roXCYCMIcg","node_name":"node_t3"}]},"templates":{},"indices":{},"index-graveyard":{"tombstones":[]}},"routing_table":{"indices":{}},"routing_nodes":{"unassigned":[],"nodes":{"nHaB1FXFRxe7roXCYCMIcg":[],"rAYJfaApT3auq8EBxJDzMQ":[],"zHPKN-5CTsaIbXnzoAUA8w":[],"zV4RHQfYRMmpvz6J1y88Bw":[]}}}
	at __randomizedtesting.SeedInfo.seed([93914A17FFFDFE5A]:0)
	at org.elasticsearch.cluster.coordination.Coordinator.assertPreviousStateConsistency(Coordinator.java:1007)
	at org.elasticsearch.cluster.coordination.Coordinator.publish(Coordinator.java:955)
	at org.elasticsearch.cluster.service.MasterService.publish(MasterService.java:252)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:238)
```

The assertion is tripping because it expects a `term` of `1`, but it's getting one of `3`.

Reproduce line:
```
REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=93914A17FFFDFE5A \
  -Dtests.class=org.elasticsearch.discovery.StableMasterDisruptionIT \
  -Dtests.method="testFollowerCheckerDetectsUnresponsiveNodeAfterMasterReelection" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-CS \
  -Dtests.timezone=Indian/Mayotte \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Build log:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2204/console

**Comment by ywelsch** [comment]
The logs seem to be lost on this one. I wonder though if this can occur when there's a messy election.
Assume that a node tries to become leader in term 2, and the previous state has therefore term 1. At the same time, another node tries to become leader in term 3, and publishes a state to the current node, which has not executed the `publish` method yet for becoming leader in term 2. Assume that the current node then becomes leader in term 4, before executing `publish` for term 2. In that case, the above exception will trip. One way to fix this is to adapt the condition at the beginning of `publish` from `if (mode != Mode.LEADER) {` to `if (mode != Mode.LEADER || getCurrentTerm() != clusterChangedEvent.state().term()) {` so that we don't even explore that code path. WDYT @DaveCTurner?

**Comment by DaveCTurner** [comment]
The assertion also failed on the cluster state version:

```
...,"version":5,"state_uuid":"lQhkDmd_SPOEmT1TTAsDNQ",...,"cluster_coordination":{"term":1,...
...,"version":6,"state_uuid":"iYC-SDemQD-T76Gy_zuyng",...,"cluster_coordination":{"term":3,...
              ^               ^^^^^^^^^^^^^^^^^^^^^^                                     ^
```

Rejecting early based on the term (and/or version) seems reasonable to me, it's checked in `coordinationState.get().handleClientValue(clusterState);` a few lines down anyway. We could also just move the assertion to be below the call to `handleClientValue`. But there's also this:

```
...,"master_node":null,...
```

Should we be trying to _publish_ a cluster state with no master?

**Comment by ywelsch** [comment]
> The assertion also failed on the cluster state version
yes, this fits with my scenario above.

> Should we be trying to publish a cluster state with no master?
Note that the assertion `assertPreviousStateConsistency` is comparing pre-states, not the state that is to be published, and also explicitly adding the no_master_block and setting master_node to null to make both states comparable.

I think a term check is sufficient here (one leader per term) and will open a PR for this.
