### ISSUE TITLE
SuggestSearchIT.testEmpty failure in CI

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#39315]
Failed in master for the first time today, does not reproduce

```
java.lang.AssertionError: [shard [[4C1bk--TT7KuHqh-NWQx9g][test][1]], reason [RemoteTransportException[[node_s0][127.0.0.1:36557][indices:data/read/search[phase/query]]]; nested: IllegalArgumentException[no mapping found for field [text]]; ], cause [java.lang.IllegalArgumentException: no mapping found for field [text]
	at org.elasticsearch.search.suggest.SuggestionBuilder.populateCommonFields(SuggestionBuilder.java:307)
	at org.elasticsearch.search.suggest.term.TermSuggestionBuilder.build(TermSuggestionBuilder.java:448)
	at org.elasticsearch.search.suggest.SuggestBuilder.build(SuggestBuilder.java:175)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:808)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:607)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:582)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:385)
```

Reproduce line:
```
REPRODUCE WITH: ./gradlew :server:integTest \
  -Dtests.seed=7E73F9B87A524CD5 \
  -Dtests.class=org.elasticsearch.search.suggest.SuggestSearchIT \
  -Dtests.method="testEmpty" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-SA \
  -Dtests.timezone=America/Louisville \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Log:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/1711/console

**Comment by romseygeek** [comment]
The odd thing here is that immediately before the suggestion is sent, a document is indexed with a `text` field, and then `refresh()` is called, which ought to ensure that either the mapping exists or adding the document fails.

**Comment by dakrone** [comment]
> The odd thing here is that immediately before the suggestion is sent, a document is indexed with a `text` field, and then `refresh()` is called, which ought to ensure that either the mapping exists or adding the document fails.

Not necessarily, mapping updates are asynchronous and so the document could be indexed and refreshed without the cluster state update reaching the node.
