### ISSUE TITLE
SQL: Remove grammar ambiguities caused by the `predicated`

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#39354]
The following rules:
```
booleanExpression
    : NOT booleanExpression                                                                 #logicalNot
    | EXISTS '(' query ')'                                                                  #exists
    | QUERY '(' queryString=string matchQueryOptions ')'                                    #stringQuery
    | MATCH '(' singleField=qualifiedName ',' queryString=string matchQueryOptions ')'      #matchQuery
    | MATCH '(' multiFields=string ',' queryString=string matchQueryOptions ')'             #multiMatchQuery
    | predicated                                                                            #booleanDefault
    | left=booleanExpression operator=AND right=booleanExpression                           #logicalBinary
    | left=booleanExpression operator=OR right=booleanExpression                            #logicalBinary
    ;

// workaround for:
//  https://github.com/antlr/antlr4/issues/780
//  https://github.com/antlr/antlr4/issues/781
predicated
    : valueExpression predicate?
    ;
```
together with:
```
// workaround for:
//  https://github.com/antlr/antlr4/issues/780
//  https://github.com/antlr/antlr4/issues/781
predicated
    : valueExpression predicate?
    ;
```
cause ambiguities which are detected if the  `DEBUG` variable on `SqlParser` is  set to `true`.

A unit test that fails is `SqlParserTests#testStringQuery` together with many integration tests:
```
ParsingException[line 1:110: reportAmbiguity d=60 (booleanExpression): ambigAlts={3, 6}, input='QUERY('foo', 'default_field=last_name;lenient=true', 'fuzzy_rewrite=scoring_boolean')'
]
	at __randomizedtesting.SeedInfo.seed([C9428C274E060D20:6CAFE909A9529127]:0)
	at org.elasticsearch.xpack.sql.parser.SqlParser$2.syntaxError(SqlParser.java:315)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:564)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:551)
	at org.antlr.v4.runtime.DiagnosticErrorListener.reportAmbiguity(DiagnosticErrorListener.java:104)
	at org.antlr.v4.runtime.ProxyErrorListener.reportAmbiguity(ProxyErrorListener.java:79)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.reportAmbiguity(ParserATNSimulator.java:2023)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATNWithFullContext(ParserATNSimulator.java:782)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:524)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:412)
	at org.elasticsearch.xpack.sql.parser.SqlBaseParser.booleanExpression(SqlBaseParser.java:3019)
	at org.elasticsearch.xpack.sql.parser.SqlBaseParser.querySpecification(SqlBaseParser.java:1722)
	at org.elasticsearch.xpack.sql.parser.SqlBaseParser.queryTerm(SqlBaseParser.java:1508)
	at org.elasticsearch.xpack.sql.parser.SqlBaseParser.queryNoWith(SqlBaseParser.java:1315)
	at org.elasticsearch.xpack.sql.parser.SqlBaseParser.query(SqlBaseParser.java:1259)
	at org.elasticsearch.xpack.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:609)
	at org.elasticsearch.xpack.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:190)
	at org.elasticsearch.xpack.sql.parser.SqlParser.invokeParser(SqlParser.java:135)
	at org.elasticsearch.xpack.sql.parser.SqlParser.createStatement(SqlParser.java:78)
	at org.elasticsearch.xpack.sql.parser.SqlParser.createStatement(SqlParser.java:65)
	at org.elasticsearch.xpack.sql.parser.SqlParserTests.parseStatement(SqlParserTests.java:360)
	at org.elasticsearch.xpack.sql.parser.SqlParserTests.testStringQuery(SqlParserTests.java:143)
```

Relates to #36762.

**Comment by wchaparro** [comment]
Superceded by ES|QL
