### ISSUE TITLE
:qa:full-cluster-restart bwc tests fails to extract 6.0 archive

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#39441]
Today the bwc tests failed several times on the 7.0 / 7.x branches, all with the same error:

```
Execution failed for task ':qa:full-cluster-restart:v6.0.0#oldClusterTestCluster#node0.extract'.
Could not expand ZIP '/var/lib/jenkins/.gradle/caches/modules-2/files-2.1/dnm/elasticsearch/6.0.0/8aa6c56edf30cebae13846ce5d774bfec06fed81/elasticsearch-6.0.0.tar.gz'.
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+bwc-tests/84/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+default-distro-bwc-tests/61/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+bwc-tests/78/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+bwc-tests/85/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+bwc-tests/85/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+default-distro-bwc-tests/62/consoleFull

**Comment by tlrx** [comment]
cc @atorok @rjernst

**Comment by atorok** [comment]
```
Caused by: org.gradle.api.GradleException: Could not expand ZIP '/home/alpar/.gradle/caches/modules-2/files-2.1/dnm/elasticsearch/6.0.0/8aa6c56edf30cebae13846ce5d774bfec06fed81/elasticsearch-6.0.0.tar.gz'.
        at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:104)
        at org.gradle.api.internal.file.collections.FileTreeAdapter.visit(FileTreeAdapter.java:118)
        at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl.visit(AbstractFileTree.java:189)
        at org.gradle.api.internal.file.AbstractFileTree.isEmpty(AbstractFileTree.java:68)
        at org.gradle.api.internal.file.CompositeFileCollection.isEmpty(CompositeFileCollection.java:99)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.StartSnapshotTaskInputsBuildOperationTaskExecuter.execute(StartSnapshotTaskInputsBuildOperationTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:45)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        ... 24 more
Caused by: java.util.zip.ZipException: archive is not a ZIP archive
        at org.apache.tools.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(ZipFile.java:777)
        at org.apache.tools.zip.ZipFile.positionAtCentralDirectory(ZipFile.java:713)
        at org.apache.tools.zip.ZipFile.populateFromCentralDirectory(ZipFile.java:458)
        at org.apache.tools.zip.ZipFile.<init>(ZipFile.java:216)
        at org.apache.tools.zip.ZipFile.<init>(ZipFile.java:191)
        at org.apache.tools.zip.ZipFile.<init>(ZipFile.java:151)
        at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:80)
        ... 38 more
```

**Comment by not-napoleon** [comment]
Another failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+bwc-tests/83/console

**Comment by tlrx** [comment]
I suspect this is caused by https://github.com/elastic/elasticsearch/pull/38457, 7.0 and 7.x bwc tests started to fail on CI soon after this change. cc @jbaiera

**Comment by tvernum** [comment]
This is still a problem today (2019-Mar-04).
One log here
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+bwc-tests/96/console

I won't bother commenting with additional failures today.
