### ISSUE TITLE
CcrRetentionLeaseIT testRetentionLeaseRenewalIsCancelledWhenFollowingIsPaused fails on CI

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#39509]
CcrRetentionLeaseIT testRetentionLeaseRenewalIsCancelledWhenFollowingIsPaused failed yesterday on CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/2048

It does not reproduce on master with:
```
./gradlew :x-pack:plugin:ccr:internalClusterTest \
  -Dtests.seed=8046052DD1D0D2FA \
  -Dtests.class=org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT \
  -Dtests.method="testRetentionLeaseRenewalIsCancelledWhenFollowingIsPaused" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-BA \
  -Dtests.timezone=America/Campo_Grande \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

The job execution log is 
[consoleText.txt](https://github.com/elastic/elasticsearch/files/2915322/consoleText.txt)

**Comment by gwbrown** [comment]
This failed again today in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+internalClusterTest/1493/console

Stack trace from this one is:
```
java.lang.AssertionError: 
Expected: <1551428872734L>
     but: was <1551428883142L>
	at __randomizedtesting.SeedInfo.seed([6DC9A98E216D66A5:8F62725D0881508E]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.lambda$testRetentionLeaseRenewalIsCancelledWhenFollowingIsPaused$11(CcrRetentionLeaseIT.java:712)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:868)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:842)
	at org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.testRetentionLeaseRenewalIsCancelledWhenFollowingIsPaused(CcrRetentionLeaseIT.java:693)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

Looks like this failure may have caused a bunch of errors in other tests in the same class (or maybe the other way around?), as other tests in this class fail with:
```
MasterNotDiscoveredException[NodeNotConnectedException[[leader0][127.0.0.1:35801] Node not connected]]; nested: NodeNotConnectedException[[leader0][127.0.0.1:35801] Node not connected];
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:259)
	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:322)
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:249)
	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:549)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: NodeNotConnectedException[[leader0][127.0.0.1:35801] Node not connected]
	at org.elasticsearch.transport.ConnectionManager.getConnection(ConnectionManager.java:151)
	at org.elasticsearch.test.transport.StubbableConnectionManager.getConnection(StubbableConnectionManager.java:91)
	at org.elasticsearch.transport.TransportService.getConnection(TransportService.java:557)
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:516)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:219)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onNewClusterState(TransportMasterNodeAction.java:247)
	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onNewClusterState(ClusterStateObserver.java:308)
	at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:166)
	at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:117)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.retry(TransportMasterNodeAction.java:243)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.access$400(TransportMasterNodeAction.java:141)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$3.handleException(TransportMasterNodeAction.java:229)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1118)
	at org.elasticsearch.transport.TransportService$8.run(TransportService.java:960)
	... 4 more
```

**Comment by hub-cap** [comment]
same here
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+internalClusterTest/2020/console

**Comment by danielmitterdorfer** [comment]
Another test failure in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8,nodes=immutable&&linux&&docker/66/consoleFull

See the attached [test log output](https://github.com/elastic/elasticsearch/files/2951068/test_output.log.zip) for full details.

According to build stats, this test has failed on `7.0`, `7.x` and `master` 18 times within the last 30 days and I am going to mute this test on all those branches as a consequence:

* `master`: https://github.com/elastic/elasticsearch/pull/39896
* `7.x`: https://github.com/elastic/elasticsearch/pull/39897
* `7.0`: https://github.com/elastic/elasticsearch/pull/39898

**Comment by danielmitterdorfer** [comment]
To help with future analysis here is the build-stats link (only available for authenticated users) to see the details about build failures: https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT%22%20AND%20test:%22testRetentionLeaseRenewalIsCancelledWhenFollowingIsPaused%22'),sort:!(time,desc))

**Comment by atorok** [comment]
Traces were enabled and test was (unmuted)[fdf1d4186e7]. this happened again: 
https://elasticsearch-ci.elastic.co/view/Elasticsearch/job/elastic+elasticsearch+7.1+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java11,nodes=immutable&&linux&&docker/42/
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/3657/

**Comment by mark-vieira** [comment]
Another failure today:
https://scans.gradle.com/s/dmmo5ke3mrefy/tests/htwk6wzdfugzg-dcfrcrtgnhx3a

**Comment by tvernum** [comment]
@dnhatn This just failed again on 6.8 (30150b4)

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+multijob-unix-compatibility/os=ubuntu-18.04&&immutable/42/

```
03:49:59   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:ccr:internalClusterTest -Dtests.seed=B7E62AD293D4AEE2 -Dtests.class=org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT -Dtests.method="testRetentionLeaseRenewalIsCancelledWhenFollowingIsPaused" -Dtests.security.manager=true -Dtests.locale=hi-IN -Dtests.timezone=Poland -Dcompiler.java=12 -Druntime.java=8
03:49:59 FAILURE 11.9s J4 | CcrRetentionLeaseIT.testRetentionLeaseRenewalIsCancelledWhenFollowingIsPaused <<< FAILURES!
03:49:59    > Throwable #1: java.lang.AssertionError: 
03:49:59    > Expected: <1559620168417L>
03:49:59    >      but: was <1559620178624L>
03:49:59    > 	at __randomizedtesting.SeedInfo.seed([B7E62AD293D4AEE2:554DF101BA3898C9]:0)
03:49:59    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
03:49:59    > 	at org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.lambda$testRetentionLeaseRenewalIsCancelledWhenFollowingIsPaused$11(CcrRetentionLeaseIT.java:713)
03:49:59    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:884)
03:49:59    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:858)
03:49:59    > 	at org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.testRetentionLeaseRenewalIsCancelledWhenFollowingIsPaused(CcrRetentionLeaseIT.java:694)
03:49:59    > 	at java.lang.Thread.run(Thread.java:748)
```

Doesn't reproduce.
[build log](https://github.com/elastic/elasticsearch/files/3250592/39509-build.txt)

**Comment by dnhatn** [comment]
I opened #43054 for the latest failure.
