### ISSUE TITLE
IndicesOptionsIntegrationIT.testOpenCloseApiWildcards failure on master

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#39578]
This build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/2186/console

Does not reproduce locally.

Reproduce line:
```
./gradlew :server:integTest \
  -Dtests.seed=7C805AA0C7D4E4A6 \
  -Dtests.class=org.elasticsearch.indices.IndicesOptionsIntegrationIT \
  -Dtests.method="testOpenCloseApiWildcards" \
  -Dtests.security.manager=true \
  -Dtests.locale=da-DK \
  -Dtests.timezone=Europe/San_Marino \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Stack trace:
```
 	java.lang.AssertionError: IndexNotFoundException or IndexClosedException was expected
	at __randomizedtesting.SeedInfo.seed([B1FB310D6AEF8B9C:A4012E7BDCCBCC6B]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.elasticsearch.indices.IndicesOptionsIntegrationIT.verify(IndicesOptionsIntegrationIT.java:734)
	at org.elasticsearch.indices.IndicesOptionsIntegrationIT.verify(IndicesOptionsIntegrationIT.java:721)
	at org.elasticsearch.indices.IndicesOptionsIntegrationIT.testOpenCloseApiWildcards(IndicesOptionsIntegrationIT.java:501)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)

```

This has failed several times today, so I'll mute this test in master.

**Comment by droberts195** [comment]
The same test failed with the same assertion error in 7.x:

```
FAILURE 2.77s J6 | IndicesOptionsIntegrationIT.testOpenCloseApiWildcards <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: IndexNotFoundException or IndexClosedException was expected
   > 	at __randomizedtesting.SeedInfo.seed([42255C8E0C6D03E0:57DF43F8BA494417]:0)
   > 	at org.elasticsearch.indices.IndicesOptionsIntegrationIT.verify(IndicesOptionsIntegrationIT.java:734)
   > 	at org.elasticsearch.indices.IndicesOptionsIntegrationIT.verify(IndicesOptionsIntegrationIT.java:721)
   > 	at org.elasticsearch.indices.IndicesOptionsIntegrationIT.testOpenCloseApiWildcards(IndicesOptionsIntegrationIT.java:501)
   > 	at java.lang.Thread.run(Thread.java:748)
```

The build where the failure occurred was https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+internalClusterTest/1960/console

```
./gradlew :server:integTest \
  -Dtests.seed=42255C8E0C6D03E0 \
  -Dtests.class=org.elasticsearch.indices.IndicesOptionsIntegrationIT \
  -Dtests.method="testOpenCloseApiWildcards" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-JO \
  -Dtests.timezone=SystemV/YST9YDT \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

I cherry-picked the muting commit back to the 7.x branch in e6b9262a3123a923449abaf05d71e536403ee3c7

**Comment by dnhatn** [comment]
I am on it.

**Comment by ywelsch** [comment]
AFAICS, there have been no recent failures of this anymore.
@dnhatn revert your commit and close issue?

**Comment by dnhatn** [comment]
I've removed debug log and unmuted this test on master and 7.x. I am closing this issue for it has not failed recently.
