### ISSUE TITLE
SSLConfigurationReloaderTests#testTrustStoreReloadException is buggy

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#39627]
I had a [PR failure](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/8810/testReport/junit/org.elasticsearch.xpack.core.ssl/SSLConfigurationReloaderTests/testTrustStoreReloadException/) on this test:

```
feb. 26, 2019 12:56:36 AM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[elasticsearch[reload tests][scheduler][T#1],5,TGRP-SSLConfigurationReloaderTests]
java.lang.AssertionError: reload should not be called! [truststore reload exception]
	at __randomizedtesting.SeedInfo.seed([65B68D40D12688B5]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests$3.reloadSSLContext(SSLConfigurationReloaderTests.java:412)
	at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloader$ChangeListener.onFileChanged(SSLConfigurationReloader.java:121)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.onFileChanged(FileWatcher.java:279)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.checkAndNotify(FileWatcher.java:131)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.updateChildren(FileWatcher.java:215)
	at org.elasticsearch.watcher.FileWatcher$FileObserver.checkAndNotify(FileWatcher.java:117)
	at org.elasticsearch.watcher.FileWatcher.doCheckAndNotify(FileWatcher.java:70)
	at org.elasticsearch.watcher.AbstractResourceWatcher.checkAndNotify(AbstractResourceWatcher.java:44)
	at org.elasticsearch.watcher.ResourceWatcherService$ResourceMonitor.run(ResourceWatcherService.java:193)
	at org.elasticsearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:224)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I can't reproduce it as-is, but if I do eg. a `Thread.sleep(1000);` before the final assertion then it fails all the time. The test suggests that there is something that prevents truststores to be reloaded if the file looks invalid but I can't find this logic. My understanding is that the test passes almost all the time is just because the test finishes before the thread that monitors resources has a chance to run.

**Comment by jkakavas** [comment]
This was also tracked in https://github.com/elastic/elasticsearch/issues/39260 and was resolved in https://github.com/elastic/elasticsearch/pull/39408

**Comment by jpountz** [comment]
Great, thanks @jkakavas !
