### ISSUE TITLE
HLRestClient Analyze API does not support in place analyzer

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#39670]
Tested with 6.6.1:

The following code works very well:

```java
RestHighLevelClient client = new RestHighLevelClient(
        RestClient.builder(HttpHost.create("http://localhost:9200")));
try {
    AnalyzeRequest request = new AnalyzeRequest();
    request.text("<b>Some text to analyze</b>");
    request.analyzer("keyword");
    AnalyzeResponse response = client.indices().analyze(request, RequestOptions.DEFAULT);
    System.out.println("response = " + response);
} catch (Exception e) {
    e.printStackTrace(System.err);
} finally {
    client.close();
}
```

The following code which is coming from our documentation (see https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.6/java-rest-high-analyze.html) does not work:

```java
RestHighLevelClient client = new RestHighLevelClient(
        RestClient.builder(HttpHost.create("http://localhost:9200")));

try {
    AnalyzeRequest request = new AnalyzeRequest();
    request.text("<b>Some text to analyze</b>");
    request.tokenizer("standard");
    AnalyzeResponse response = client.indices().analyze(request, RequestOptions.DEFAULT);
    System.out.println("response = " + response);
} catch (Exception e) {
    e.printStackTrace(System.err);
} finally {
    client.close();
}
```

This is generating:

```
com.fasterxml.jackson.core.JsonGenerationException: Can not write a string, expecting field name (context: Object)
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1897)
	at com.fasterxml.jackson.core.json.JsonGeneratorImpl._reportCantWriteValueExpectName(JsonGeneratorImpl.java:244)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._verifyValueWrite(UTF8JsonGenerator.java:1033)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeString(UTF8JsonGenerator.java:442)
	at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.writeString(JsonXContentGenerator.java:281)
	at org.elasticsearch.common.xcontent.XContentBuilder.value(XContentBuilder.java:660)
	at org.elasticsearch.action.admin.indices.analyze.AnalyzeRequest$NameOrDefinition.toXContent(AnalyzeRequest.java:111)
	at org.elasticsearch.action.admin.indices.analyze.AnalyzeRequest.toXContent(AnalyzeRequest.java:284)
	at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:353)
	at org.elasticsearch.client.RequestConverters.createEntity(RequestConverters.java:676)
	at org.elasticsearch.client.RequestConverters.createEntity(RequestConverters.java:671)
	at org.elasticsearch.client.IndicesRequestConverters.analyze(IndicesRequestConverters.java:422)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1758)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1732)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1694)
	at org.elasticsearch.client.IndicesClient.analyze(IndicesClient.java:1285)
	at fr.pilato.test.elasticsearch.hlclient.App.main(App.java:53)
	Suppressed: java.lang.IllegalStateException: Failed to close the XContentBuilder
		at org.elasticsearch.common.xcontent.XContentBuilder.close(XContentBuilder.java:1002)
		at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:348)
		... 8 more
	Caused by: java.io.IOException: Unclosed object or array found
		at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.close(JsonXContentGenerator.java:469)
		at org.elasticsearch.common.xcontent.XContentBuilder.close(XContentBuilder.java:1000)
		... 9 more

Process finished with exit code 0
```

This has been reported at https://discuss.elastic.co/t/analyze-with-custom-analyzer-throws-jsongenerationexception/170644

**Comment by romseygeek** [comment]
This will be fixed in 7.3.0 by #42197 which refactors things, but I'll open a separate PR for 7.2 and 6.8 to fix the immediate bug.

**Comment by hub-cap** [comment]
@romseygeek can we close this?

**Comment by romseygeek** [comment]
We can!
