### ISSUE TITLE
Error in elasticsearch : Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/tools/java_version_checker/JavaVersionChecker : Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by ritukamboj** [elastic/elasticsearch#39716]
I am getting an error with Java while trying to install elasticsearch 6.6.1

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/tools/java_version_checker/JavaVersionChecker : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

macOS High Sierra

Java Version : 
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

Thanks for any help in advance.

**Comment by jasontedor** [comment]
You’re using Java 6 which is incompatible with Elasticsearch and even our version checking tool. Please use Java 8.

**Comment by ritukamboj** [comment]
<img width="543" alt="screen shot 2019-03-05 at 5 12 50 pm" src="https://user-images.githubusercontent.com/48259256/53841155-12712900-3f6a-11e9-8d5b-ddcfa7751744.png">
 @jasontedor I do have Java 8 installed as well. :(

**Comment by jasontedor** [comment]
That means that either Java 6 is first on the path or JAVA_HOME is set to Java 6. You need to set JAVA_HOME to Java 8.

**Comment by ritukamboj** [comment]
Pardon my ignorance on the subject. I did try to look up and after you suggested Tried to change JAVA_HOME but its not visible to change it to. It only shows 1.6 as in the image show but when I go to System Preferences > Java > Its Java 8 there. 

<img width="787" alt="screen shot 2019-03-05 at 5 43 10 pm" src="https://user-images.githubusercontent.com/48259256/53842720-43ebf380-3f6e-11e9-8ef7-bc9ab5afcc78.png">

**Comment by jasontedor** [comment]
My advice would be to reinstall JDK 8, you need it installed system wide to be useful by `/usr/libexec/java_home`. Alternatively, you can locate where you have installed JDK 8 and set `JAVA_HOME` to that location. If you need additional help, please use the [forum](https://discuss.elastic.co).

**Comment by ritukamboj** [comment]
Thanks a lot @jasontedor 
Much appreciated!

**Comment by jasontedor** [comment]
You are welcome. 😄
