### ISSUE TITLE
FullClusterRestartIT#testSecurityNativeRealm fails bwc tests with two document types

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#39740]
This just happend in a PR on master

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-bwc/1325/consoleFull

```
./gradlew :x-pack:qa:full-cluster-restart:with-system-key:v7.0.0#upgradedClusterTestRunner -Dtests.seed=77AF7A3C180CFC9D -Dtests.class=org.elasticsearch.xpack.restart.FullClusterRestartIT -Dtests.method="testSecurityNativeRealm" -Dtests.security.manager=true -Dtests.locale=es-HN -Dtests.timezone=Europe/Tirane -Dcompiler.java=11 -Druntime.java=8
```
```
11:46:57 ERROR   0.25s | FullClusterRestartIT.testSecurityNativeRealm <<< FAILURES!
11:46:57    > Throwable #1: org.elasticsearch.client.ResponseException: method [PUT], host [http://[::1]:36265], URI [/_security/user/postupgrade_user], status line [HTTP/1.1 400 Bad Request]
11:46:57    > {"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[node-0][127.0.0.1:43571][indices:admin/mapping/put]"}],"type":"illegal_argument_exception","reason":"Rejecting mapping update to [.security-7] as the final mapping would have more than 1 type: [_doc, doc]"},"status":400}
11:46:57    > 	at __randomizedtesting.SeedInfo.seed([77AF7A3C180CFC9D:FC57866F22BA5C85]:0)
11:46:57    > 	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:260)
11:46:57    > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:238)
11:46:57    > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212)
11:46:57    > 	at org.elasticsearch.xpack.restart.FullClusterRestartIT.createUser(FullClusterRestartIT.java:463)
11:46:57    > 	at org.elasticsearch.xpack.restart.FullClusterRestartIT.testSecurityNativeRealm(FullClusterRestartIT.java:133)
11:46:57    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tvernum** [comment]
@cbuescher From the looks of it, I think you just need to merge master into your PR.

It doesn't look like you have commit 5e74e82 but when you run BWC tests, you'll pull in the latest from `7.0` which include the backport of that commit (82540d2).

**Comment by cbuescher** [comment]
@tvernum thanks, will try that and close if I cannot reproduce

**Comment by cbuescher** [comment]
Yes, that did it, sorry for the noise.
