### ISSUE TITLE
elasticsearch throws RepositoryMissingException with AWS S3 

### ISSUE THREAD

**Issue by nixgadget** [elastic/elasticsearch#39775]
**Elasticsearch version**: 6.6.1
**Plugins installed**: repository-s3
**JVM version** (`java -version`): 1.8u191
**OS version** (`uname -a` if on a Unix-like system): Linux 4.9.125-linuxkit (alpine)
**Description of the problem including expected versus actual behavior**: Trying to connect to a S3 bucket however it throws a `404 repository_missing_exception`.

**Steps to reproduce**:
Installed `repository-s3` plugin
Trying to create a snapshot in S3 bucket with,
```
curl -v -XPUT "http://localhost:9200/_snapshot/riro-test-es-analytics-snapshots/%3Csnapshot-%7Bnow%2Fd%7D%3E?wait_for_completion=true" -H 'Content-Type: application/json' -d "{\"type\":\"s3\", \"ignore_unavailable\": true, \"indices\":\"*\", \"settings\":{\"bucket\":\"riro-test-es-analytics-snapshots\", \"region\": \"eu-west-1\"}}"
```

However I keep getting the following error,
```
[2019-03-07T01:43:54,642][DEBUG][r.suppressed             ] [es-analytics] path: /_snapshot/riro-test-es-analytics-snapshots/%3Csnapshot-%7Bnow%2Fd%7D%3E, params: {repository=riro-test-es-analytics-snapshots, wait_for_completion=true, snapshot=<snapshot-{now/d}>}
org.elasticsearch.repositories.RepositoryMissingException: [riro-test-es-analytics-snapshots] missing
	at org.elasticsearch.repositories.RepositoriesService.repository(RepositoriesService.java:367) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.snapshots.SnapshotsService.createSnapshot(SnapshotsService.java:239) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.action.admin.cluster.snapshots.create.TransportCreateSnapshotAction.masterOperation(TransportCreateSnapshotAction.java:86) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.action.admin.cluster.snapshots.create.TransportCreateSnapshotAction.masterOperation(TransportCreateSnapshotAction.java:41) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:124) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:211) ~[elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759) [elasticsearch-6.6.1.jar:6.6.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.6.1.jar:6.6.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```
 
Curl result,
```
{"error":{"root_cause":[{"type":"repository_missing_exception","reason":"[riro-test-es-analytics-snapshots] missing"}],"type":"repository_missing_exception","reason":"[riro-test-es-analytics-snapshots] missing"},"status":404}
```

I couldnt figure out why this was happening looking at `https://github.com/elastic/elasticsearch/blob/v6.6.1/server/src/main/java/org/elasticsearch/repositories/RepositoriesService.java`

**Comment by nixgadget** [comment]
I realized after creating this issue that I was calling the wrong endpoint
