### ISSUE TITLE
Integration tests fail on Windows

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#39904]
The latest master cannot run integration tests on windows due to:
```
Exception in thread "main" java.nio.file.AccessDeniedException: C:\Windows\elasticsearch
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:504)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at org.elasticsearch.tools.launchers.TempDirectory.main(TempDirectory.java:52)
```

It looks like the temporary folder is not set which causes the default/system folder (`C:\Windows`) to be used instead which obviously fails.

From try-outs it looks commit 465343f12a54111709ca7c7cd776edcaba1e0c2b introduced this change in behavior.

**Comment by atorok** [comment]
I managed to reproduce this on a Win2012r2 image we use for packaging tests in CI. 
using `gradlew -p x-pack/plugin/sql/qa/single-node check` without setting runtime java.  I do have `TMP` set. Running the `run.bat` wrapper script doesn't reproduces the problem, which leads me to believe the problem is that env vars do not get sent when this is called. 
This reproduces with `RUNTIME_JAVA_HOME` set as well

**Comment by atorok** [comment]
I can confirm that the  env is not inherited by the wrapper script:
```
COMSPEC=C:\Windows\SYSTEM32\cmd.exe
ES_JAVA_OPTS=-Xms512m -Xmx512m  -ea -esa
ES_PATH_CONF=C:\ELASTI~1\x-pack\plugin\sql\qa\single-node\build\cluster\integTestCluster node0\elasticsearch-8.0.0-SNAPSHOT\config
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.JS;.WS;.MSC
PROMPT=$P$G
SystemRoot=C:\Windows
```
