### ISSUE TITLE
[CI] :x-pack:qa:rolling-upgrade failed to obtain in-memory shard lock

### ISSUE THREAD

**Issue by andyb-elastic** [elastic/elasticsearch#39982]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+multijob-unix-compatibility/os=ubuntu-16.04&&immutable/167/console

```
./gradlew :x-pack:qa:rolling-upgrade:without-system-key:v5.6.16#upgradedClusterTestRunner \
  -Dtests.seed=FE5CAFC90A3BCC41 \
  -Dtests.class=org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT \
  -Dtests.method="testTokenWorksInMixedOrUpgradedCluster" \
  -Dtests.security.manager=true \
  -Dtests.locale=bg-BG \
  -Dtests.timezone=US/Arizona \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

The log of `v5.6.16#twoThirdsUpgradedTestCluster node0` is full of
```
[2019-03-13T00:53:36,293][WARN ][o.e.c.r.a.AllocationService] [upgraded-node-1] failing shard [failed shard, shard [upgraded_scroll][0], node[pe1tsX0mSLiS83MPdErrLg], relocating [tbhJQKFDQDqHYv40OQTFIQ], [R], recovery_source[peer recovery], s[INITIALIZING], a[id=cXpVhmkYTbGL-wC1bEjpMA, rId=Ri0j4F2BTQStmi5EJoKiuw], expected_shard_size[230], message [failed to create shard], failure [IOException[failed to obtain in-memory shard lock]; nested: ShardLockObtainFailedException[[upgraded_scroll][0]: obtaining shard lock timed out after 5000ms]; ], markAsStale [true]]
java.io.IOException: failed to obtain in-memory shard lock
        at org.elasticsearch.index.IndexService.createShard(IndexService.java:395) ~[elasticsearch-6.6.2-SNAPSHOT.jar:6.6.2-SNAPSHOT]
        at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:610) ~[elasticsearch-6.6.2-SNAPSHOT.jar:6.6.2-SNAPSHOT]
        at org.elasticsearch.indices.IndicesService.createShard(IndicesService.java:156) ~[elasticsearch-6.6.2-SNAPSHOT.jar:6.6.2-SNAPSHOT]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.createShard(IndicesClusterStateService.java:560) ~[elasticsearch-6.6.2-SNAPSHOT.jar:6.6.2-SNAPSHOT]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.createOrUpdateShards(IndicesClusterStateService.java:537) ~[elasticsearch-6.6.2-SNAPSHOT.jar:6.6.2-SNAPSHOT]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:234) ~[elasticsearch-6.6.2-SNAPSHOT.jar:6.6.2-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$6(ClusterApplierService.java:486) ~[elasticsearch-6.6.2-SNAPSHOT.jar:6.6.2-SNAPSHOT]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:483) ~[elasticsearch-6.6.2-SNAPSHOT.jar:6.6.2-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:470) ~[elasticsearch-6.6.2-SNAPSHOT.jar:6.6.2-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:421) ~[elasticsearch-6.6.2-SNAPSHOT.jar:6.6.2-SNAPSHOT]
        at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:165) ~[elasticsearch-6.6.2-SNAPSHOT.jar:6.6.2-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660) [elasticsearch-6.6.2-SNAPSHOT.jar:6.6.2-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) [elasticsearch-6.6.2-SNAPSHOT.jar:6.6.2-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) [elasticsearch-6.6.2-SNAPSHOT.jar:6.6.2-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.elasticsearch.env.ShardLockObtainFailedException: [upgraded_scroll][0]: obtaining shard lock timed out after 5000ms
        at org.elasticsearch.env.NodeEnvironment$InternalShardLock.acquire(NodeEnvironment.java:730) ~[elasticsearch-6.6.2-SNAPSHOT.jar:6.6.2-SNAPSHOT]
        at org.elasticsearch.env.NodeEnvironment.shardLock(NodeEnvironment.java:649) ~[elasticsearch-6.6.2-SNAPSHOT.jar:6.6.2-SNAPSHOT]
        at org.elasticsearch.index.IndexService.createShard(IndexService.java:330) ~[elasticsearch-6.6.2-SNAPSHOT.jar:6.6.2-SNAPSHOT]
        ... 17 more
```

I did not see anything interesting in the other nodes' logs
[log-files.tar.gz](https://github.com/elastic/elasticsearch/files/2959482/log-files.tar.gz)

I originally thought this may have been what https://github.com/elastic/elasticsearch/pull/39922 was meant to resolve because it's a lot of the same tests and it wasn't backported to 6.6, but I do not see that same AssertionError from that issue in the test cluster's logs

The test log makes it look like this cluster did not shut down cleanly
[build-6.6-multijob-167.txt](https://github.com/elastic/elasticsearch/files/2959489/build-6.6-multijob-167.txt)

**Comment by ywelsch** [comment]
Old ES version and no recent failures.
