### ISSUE TITLE
[CI] IndicesClientIT.testGetAlias  failed in 7.0 

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#40053]
This failed once today : https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+intake/414/consoleText

```
FAILURE 0.39s | IndicesClientIT.testGetAlias <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <3>
   >      but: was <4>
   > 	at __randomizedtesting.SeedInfo.seed([7D6ACC21848938CE:4EF959EF7D88BE75]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.client.IndicesClientIT.testGetAlias(IndicesClientIT.java:1264)
   > 	at java.lang.Thread.run(Thread.java:748)
```

and I could see

```
[2019-03-14T13:57:11,944][ERROR][o.e.x.w.Watcher          ] [node-0] triggered watches could not be deleted [my_watch_id_997cf558-4b75-4e08-a017-914ac49931a1-2019-03-14T13:57:11.806Z], failure [[.triggered_watches] IndexNotFoundException[no such index [.triggered_watches]]]
... SKIPPED 53 LINES ...
[2019-03-14T13:57:13,183][ERROR][o.e.x.w.Watcher          ] [node-0] triggered watches could not be deleted [my_watch_id_0faecf2d-31ed-45b6-a391-78d48c41d51f-2019-03-14T13:57:13.085Z], failure [[.triggered_watches] IndexNotFoundException[no such index [.triggered_watches]]]
[2019-03-14T13:57:13,205][ERROR][o.e.x.w.Watcher          ] [node-0] triggered watches could not be deleted [my_watch_id_96c39ff3-7197-4fb1-8413-33653344626f-2019-03-14T13:57:13.203Z], failure [[.triggered_watches] IndexNotFoundException[no such index [.triggered_watches]]]
... SKIPPED 1831 LINES ...
[2019-03-14T13:57:44,866][ERROR][o.e.x.m.j.p.a.w.JsonDataToProcessWriter] [node-0] Cannot parse timestamp '' as epoch value
[2019-03-14T13:57:44,866][ERROR][o.e.x.m.j.p.a.w.JsonDataToProcessWriter] [node-0] Cannot parse timestamp '' as epoch value
[2019-03-14T13:57:44,877][ERROR][o.e.x.m.j.p.a.w.JsonDataToProcessWriter] [node-0] Cannot parse timestamp '' as epoch value
... SKIPPED 292 LINES ...
[2019-03-14T13:57:53,099][WARN ][o.e.x.m.d.DatafeedManager] [node-0] [start-datafeed-job] Datafeed lookback retrieved no data
... SKIPPED 605 LINES ...
```

but I'm not entirely sure whether this is related. The
```
./gradlew :client:rest-high-level:integTestRunner \
  -Dtests.seed=7D6ACC21848938CE \
  -Dtests.class=org.elasticsearch.client.IndicesClientIT \
  -Dtests.method="testGetAlias" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-DO \
  -Dtests.timezone=America/Montreal \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

does not reproduce locally. I'm not muting this since it has failed only once before ( March 8 : https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+multijob-unix-compatibility/os=ubuntu-16.04&&immutable/159/console )

**Comment by martijnvg** [comment]
Additional debug information was added via: df60f6866affac359cf1e6db8ab4ee1d14621949
but that wasn't backported to 7.0 and 6.7. I will do that now, so that if this test fails again on these branches then we have more information.

**Comment by dnhatn** [comment]
Another instance on 6.8: https://gradle-enterprise.elastic.co/s/7xiuswkdtwha6

**Comment by dakrone** [comment]
Given that it's been over a year since this failed (without muting), I am going to close this for now. We can re-open if it happens again

**Comment by hendrikmuhs** [comment]
re-appeared with debug info: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+multijob+platform-support-unix/os=ubuntu-20.04&&immutable/820/console

https://gradle-enterprise.elastic.co/s/3o7gsvhaj34t4

**Comment by dakrone** [comment]
That failure is on 6.8, and it's extremely unlikely that we would backport any kind of fix that far back. For now I am going to close this again, if it re-occurs on 7.x or 8.x then we can look into it again.
