### ISSUE TITLE
[CI] Packaging test93ElasticsearchNodeCustomDataPathAndNotEsHomeWorkDir failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#40099]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-tests/564/console and https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-tests/563/console

```
./gradlew ":qa:vagrant:vagrantCentos6#javaPackagingTest" \
  -Dtests.seed=309F2A0C5F7D5BF2 
```

The Error:

```
There were 2 failures:
1) test93ElasticsearchNodeCustomDataPathAndNotEsHomeWorkDir(org.elasticsearch.packaging.test.DefaultNoJdkLinuxTarTests)
java.lang.RuntimeException: Command was not successful: [bash -c sudo -E -u elasticsearch /tmp/elasticsearch/bin/elasticsearch -d -p /tmp/elasticsearch/elasticsearch.pid] result: <org.elasticsearch.packaging.util.Shell$Result exitCode = [1] stdout = [] stderr = [could not find java in JAVA_HOME or bundled at /tmp/elasticsearch/jdk/bin/java
]>
	at __randomizedtesting.SeedInfo.seed([EB06EA8356E8CB41:E5FBE4F0B0490495]:0)
	at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:89)
	at org.elasticsearch.packaging.util.Shell.run(Shell.java:60)
	at org.elasticsearch.packaging.util.Archives.lambda$runElasticsearch$12(Archives.java:274)
	at org.elasticsearch.packaging.util.Platforms.onLinux(Platforms.java:76)
	at org.elasticsearch.packaging.util.Archives.runElasticsearch(Archives.java:267)
	at org.elasticsearch.packaging.util.Archives.runElasticsearch(Archives.java:259)
	at org.elasticsearch.packaging.test.ArchiveTestCase.test93ElasticsearchNodeCustomDataPathAndNotEsHomeWorkDir(ArchiveTestCase.java:372)
...

2) test93ElasticsearchNodeCustomDataPathAndNotEsHomeWorkDir(org.elasticsearch.packaging.test.OssNoJdkLinuxTarTests)
java.lang.RuntimeException: Command was not successful: [bash -c sudo -E -u elasticsearch /tmp/elasticsearch/bin/elasticsearch -d -p /tmp/elasticsearch/elasticsearch.pid] result: <org.elasticsearch.packaging.util.Shell$Result exitCode = [1] stdout = [] stderr = [could not find java in JAVA_HOME or bundled at /tmp/elasticsearch/jdk/bin/java
]>
	at __randomizedtesting.SeedInfo.seed([286125A95D302B24:269C2BDABB91E4F0]:0)
	at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:89)
	at org.elasticsearch.packaging.util.Shell.run(Shell.java:60)
	at org.elasticsearch.packaging.util.Archives.lambda$runElasticsearch$12(Archives.java:274)
	at org.elasticsearch.packaging.util.Platforms.onLinux(Platforms.java:76)
	at org.elasticsearch.packaging.util.Archives.runElasticsearch(Archives.java:267)
	at org.elasticsearch.packaging.util.Archives.runElasticsearch(Archives.java:259)
	at org.elasticsearch.packaging.test.ArchiveTestCase.test93ElasticsearchNodeCustomDataPathAndNotEsHomeWorkDir(ArchiveTestCase.java:372)
...
```

**Comment by jkakavas** [comment]
This also failed in a PR: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-sample/11362/console
