### ISSUE TITLE
[CI] SamlAuthenticationIT testLoginUserWithSamlRoleMapping failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#40106]
2 recent failures both on the 7.x branch

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+periodic/209/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=zulu8,nodes=immutable&&linux&&docker/74/console

The error was the in both cases:
```
Expected: <302>
     but: was <200>
	at __randomizedtesting.SeedInfo.seed([F052FCE97D7E6799:7FBD4AC369380B44]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.lambda$submitLoginForm$2(SamlAuthenticationIT.java:378)
	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.execute(SamlAuthenticationIT.java:500)
	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.submitLoginForm(SamlAuthenticationIT.java:376)
	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.loginViaSaml(SamlAuthenticationIT.java:261)
	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.testLoginUserWithSamlRoleMapping(SamlAuthenticationIT.java:242)
```

```
./gradlew :x-pack:qa:saml-idp-tests:integTestRunner \
  -Dtests.seed=C63BEF696BFC217D \
  -Dtests.class=org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT \
  -Dtests.method="testLoginUserWithSamlRoleMapping" \
  -Dtests.security.manager=true \
  -Dtests.locale=fr-CH \
  -Dtests.timezone=Brazil/East \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

```
./gradlew :x-pack:qa:saml-idp-tests:integTestRunner \
  -Dtests.seed=F052FCE97D7E6799 \
  -Dtests.class=org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT \
  -Dtests.method="testLoginUserWithSamlRoleMapping" \
  -Dtests.security.manager=true \
  -Dtests.locale=sq-AL \
  -Dtests.timezone=Etc/Universal \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

**Comment by davidkyle** [comment]
Possibly a duplicate of #40025

**Comment by jkakavas** [comment]
https://github.com/elastic/elasticsearch/pull/40102 will fix this too
