### ISSUE TITLE
[CI] full-cluster-restart:with-system-key:v6.6.3 fails in 7.x/7.0 in a FIPS JVM

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#40103]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8fips,nodes=immutable&&linux&&docker/74/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8fips,nodes=immutable&&linux&&docker/74/console

This failed as the node didn't start 

```
17:25:08 Execution failed for task ':x-pack:qa:full-cluster-restart:with-system-key:v6.6.3#oldClusterTestCluster#wait'.
17:25:08 > Failed to locate seed node transport file [/var/lib/jenkins/workspace/elastic+elasticsearch+7.0+matrix-java-periodic/ES_BUILD_JAVA/openjdk12/ES_RUNTIME_JAVA/java8fips/nodes/immutable&&linux&&docker/x-pack/qa/full-cluster-restart/with-system-key/build/cluster/v6.6.3#oldClusterTestCluster node0/elasticsearch-6.6.3-SNAPSHOT/logs/transport.ports]: timed out waiting for it to be created after 40 seconds
```

but we don't print the logs from the nodes so there is no indication as to why the node failed to start . It reproduces with 
```
./gradlew :x-pack:qa:full-cluster-restart:with-system-key:v6.6.3#bwcTest -Druntime.java=8FIPS
```

**Comment by jkakavas** [comment]
This fails with 
```
[2019-03-15T17:59:01,609][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-0] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load plugin class [org.elasticsearch.xpack.core.XPackPlugin]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
Caused by: java.lang.IllegalStateException: failed to load plugin class [org.elasticsearch.xpack.core.XPackPlugin]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:608) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:550) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:465) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:157) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.node.Node.<init>(Node.java:337) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_171]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:599) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:550) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:465) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:157) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.node.Node.<init>(Node.java:337) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        ... 6 more
Caused by: org.elasticsearch.ElasticsearchException: failed to initialize a KeyManagerFactory
        at org.elasticsearch.xpack.core.ssl.StoreKeyConfig.createKeyManager(StoreKeyConfig.java:76) ~[?:?]
        at org.elasticsearch.xpack.core.ssl.SSLService.createSslContext(SSLService.java:365) ~[?:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1127) ~[?:1.8.0_171]
        at org.elasticsearch.xpack.core.ssl.SSLService.loadSSLConfigurations(SSLService.java:421) ~[?:?]
        at org.elasticsearch.xpack.core.ssl.SSLService.<init>(SSLService.java:96) ~[?:?]
        at org.elasticsearch.xpack.core.XPackPlugin.<init>(XPackPlugin.java:144) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_171]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:599) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:550) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:465) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:157) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.node.Node.<init>(Node.java:337) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.6.3-SNAPSHOT.jar:6.6.3-SNAPSHOT]
        ... 6 more
Caused by: java.security.KeyStoreException: FIPS mode: KeyStore must be from provider BCFIPS

```

**Comment by jkakavas** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/40105

**Comment by mayya-sharipova** [comment]
Another related failure happened today:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8fips,nodes=general-purpose/99/console

```
17:39:40 Execution failed for task ':qa:full-cluster-restart:v7.2.1#oldClusterTestCluster#wait'.
17:39:40 > Failed to locate seed node transport file [/var/lib/jenkins/workspace/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA/openjdk12/ES_RUNTIME_JAVA/java8fips/nodes/general-purpose/qa/full-cluster-restart/build/cluster/v7.2.1#oldClusterTestCluster node0/elasticsearch-7.2.1-SNAPSHOT/logs/transport.ports]: timed out waiting for it to be created after 40 seconds
```

**Comment by jkakavas** [comment]
This latest failure is probably a manifestation of https://github.com/elastic/elasticsearch/issues/41721 rather than this issue. The node logs for oldClusterTestCluster node would be revealing

**Comment by mayya-sharipova** [comment]
@jkakavas Thanks Ioannis, closing this issue again then
