### ISSUE TITLE
[CI] JobResultsProviderIT testMultipleSimultaneousJobCreations fails

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#40134]
`JobResultsProviderIT testMultipleSimultaneousJobCreations` failed in several builds, for example https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/600/console

The error is always:

```
Failed to execute phase [query], all shards failed
	at __randomizedtesting.SeedInfo.seed([7B6EEB537A6244F7:C66AAE317F6F5D44]:0)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:296)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:139)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:259)
	at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:105)
	at org.elasticsearch.action.search.InitialSearchPhase.access$200(InitialSearchPhase.java:50)
	at org.elasticsearch.action.search.InitialSearchPhase$2.onFailure(InitialSearchPhase.java:273)
	at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:59)
	at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:441)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1118)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1230)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1204)
	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:60)
	at org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:56)
	at org.elasticsearch.search.SearchService$2.onFailure(SearchService.java:365)
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:359)
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:353)
	at org.elasticsearch.search.SearchService$4.doRun(SearchService.java:1068)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:43)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:747)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This occurs during the cleanup after the actual test is complete.

The test runs as part of this suite:

```
./gradlew :x-pack:plugin:ml:internalClusterTest -Dtests.class=org.elasticsearch.xpack.ml.integration.JobResultsProviderIT
```

It never reproduces using the REPRO command in the failure emails.  I suspect it only happens when the test is run together with other tests.

**Comment by droberts195** [comment]
Muted by:

master: 7a2ff624ea745d93ebf467ef3cd03827905c0418
7.x: 64028f3d8fee6b581a08a78eda3244176369c819
7.0: 4a54dd6c831b74e601d56361f1ac6162c3222c34
6.7: f2d61d345b08c357aa3879915bde0462bb822474

**Comment by droberts195** [comment]
It's unfortunate that the exception doesn't say which index all shards failed for.

Based on previous experience of async effects of job creation interfering with cleanup in between tests it could well be the audit notifications generated by creation of the jobs that clash with deletion of the ML indices after the test completes.

The test could be changed to finish with an `assertBusy` that the number of documents in the `.ml-notifications` index is at least equal to the number of jobs that were simultaneously created.  Then no further audit notifications should be written during the post test cleanup.

**Comment by leonav0408** [comment]
Hi,
I am a beginner in open source but come with coding experience in Java and PHP.
I would like to look into this issue. I assume it is still open.

**Comment by droberts195** [comment]
@leonav0408 yes, the issue is still open and it would be great if you could look at it.

To try to reproduce it, look for the following lines in `JobResultsProviderIT.java`:

```
    @AwaitsFix(bugUrl ="https://github.com/elastic/elasticsearch/issues/40134")
    public void testMultipleSimultaneousJobCreations() {

        int numJobs = randomIntBetween(4, 7);
```

Remove the `AwaitsFix` line and try setting `numJobs` to a high number, as I suspect that will increase the likelihood of a problem.

Then to run the test suite that contains the test:

```
./gradlew :x-pack:plugin:ml:internalClusterTest
```

I never managed to reproduce it by running just the single test.  It seems that it needs the JVM to be warmed up after running other tests to have a chance of failing.

My idea for how to prevent side effects of the test clashing with the cleanup in between jobs was to add an `assertBusy` that the number of documents in the `.ml-notifications` index is at least equal to the number of jobs that were simultaneously created at the very end of `JobResultsProviderIT.testMultipleSimultaneousJobCreations()`.  Have a look at other examples of `assertBusy` in the codebase.  It runs the same lambda over and over again with a short sleep in between until it doesn't throw an `AssertionError` or 10 seconds elapses.

**Comment by leonav0408** [comment]
@droberts195 Thanks for some more pointers for me to reproduce. I will take a look at it and get back.

**Comment by mariaral** [comment]
Hello @droberts195, @leonav0408 ,

I took a look at this error and  managed to reproduce it by running just the single test in *Trace* logger mode and more than 70 simultaneous jobs. From what I understand, the test fails because two or more simultaneous `Create Jobs` requests can fail when the results index `.ml-anomalies-shared` does not exist. This can happen when the `JobResultsProvider.checkForLeftOverDocuments()` tries to query the `.ml-anomalies-shared` index right after its creation by another job/thread while the index shard is still at state **RECOVERING**. Indeed, the error I see when running the test with *Trace* logger level is: 

```
org.elasticsearch.index.shard.IllegalIndexShardStateException: CurrentState[RECOVERING] operations only allowed when shard state is one of [POST_RECOVERY, STARTED]
```

One possible solution to this would be to modify the test and execute the first job synchronously so that the index is created. But this doesn't solve the underlying problem that the test correctly detected, i.e.,  simultaneous *Create Job* requests can fail when the results index `.ml-anomalies-shared` does not exist. Would it be possible to allow reads in the **RECOVERY** phase for newly created shards or retry the query until the shard starts? What are your thoughts on this? I will be happy to provide more feedback and help towards a solution.

**Comment by droberts195** [comment]
Great job tracking that down @mariaral!

> But this doesn't solve the underlying problem that the test correctly detected

Yes, I agree.  Changing the test would just mask a problem that could affect production.

Since a newly created index cannot possibly have any documents from old jobs in it I think the solution is to ignore this specific type of error in the multi-search listener in `JobResultsProvider.checkForLeftOverDocuments`.

So where we have https://github.com/elastic/elasticsearch/blob/c1c7fa5d9c8f8423c848e196682273828bf50b3e/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/persistence/JobResultsProvider.java#L193-L194 add an extra check that detects failures due to newly created shards, logs a debug message and then ignores the exception and continues the loop instead of returning it to the listener.

As you can reproduce the problem, please could you have a go at making this change and see if it works?

**Comment by mariaral** [comment]
Great suggestion @droberts195!

However, the error in the multi-search listener at `JobResultsProvider.checkForLeftOverDocuments()` is a general `SearchPhaseExecutionException` from which I couldn’t figure out if it is caused because of the newly created shards and of course we can’t ignore every `SearchPhaseExecutionException` error. Is there something I am missing here or should I try to figure out other solutions?
