### ISSUE TITLE
SQL: passing an input to the CLI "freezes" the CLI after displaying an error message

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#40164]
```
echo "foobar" | elasticsearch-sql-cli.bat

Exception in thread "WindowsStreamPump" java.lang.NoSuchMethodError: org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(II)[Lorg/fusesource/jansi/internal/Kernel32$INPUT_RECORD;
        at org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.processConsoleInput(JansiWinSysTerminal.java:104)
        at org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:459)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

The message above will be shortly displayed in console before actually starting the SQL CLI in a semi-"frozen" mode (only CTRL+C will move the cursor to the next line nothing else will work).

**Comment by costin** [comment]
Closed by #40321
