### ISSUE TITLE
Reproducible agg-ordering.testMultipleGroupingsAndOrderingByGroupsWithFunctions_3 failure on CI

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#40165]
Failed on a [PR](https://github.com/elastic/elasticsearch/pull/40121) against 7.0 related to the migration assistant: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/10171/console

Reproduce line (reproduces for me):
```
./gradlew :x-pack:plugin:sql:qa:single-node:integTestRunner -Dtests.seed=5BB7A2137D9824B8 -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcSqlSpecIT -Dtests.method="test {agg-ordering.testMultipleGroupingsAndOrderingByGroupsWithFunctions_3}" -Dtests.security.manager=true -Dtests.locale=tr -Dtests.timezone=Europe/Zagreb -Dcompiler.java=11 -Druntime.java=8
```

Stack trace:
```
org.junit.ComparisonFailure: Different result for column [c], entry [12] expected:<ZHONGWE[İ]rosen> but was:<ZHONGWE[I]rosen>
	at __randomizedtesting.SeedInfo.seed([5BB7A2137D9824B8:D3E39DC9D3644940]:0)
	at org.elasticsearch.xpack.sql.qa.single_node.JdbcSqlSpecIT.agg-ordering.testMultipleGroupingsAndOrderingByGroupsWithFunctions_3(agg-ordering.sql-spec:120)
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.doAssertResultSetData(JdbcAssert.java:259)
	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSetData(JdbcAssert.java:181)
	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:83)
	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:67)
	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:56)
	at org.elasticsearch.xpack.sql.qa.jdbc.SpecBaseIntegrationTestCase.assertResults(SpecBaseIntegrationTestCase.java:127)
	at org.elasticsearch.xpack.sql.qa.jdbc.SqlSpecTestCase.doTest(SqlSpecTestCase.java:96)
	at org.elasticsearch.xpack.sql.qa.jdbc.SpecBaseIntegrationTestCase.test(SpecBaseIntegrationTestCase.java:88)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

Build log: [consoleText.txt](https://github.com/elastic/elasticsearch/files/2979502/consoleText.txt)

**Comment by astefan** [comment]
I think I know what is this about. I've had this before: uppercasing/lowercasing a certain letter in a specific locale. And this one came up now because those are tests I just added today.

**Comment by jaymode** [comment]
A few more failures on the 7.0 branch, https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+intake/450/console. 

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:sql:qa:single-node:integTestRunner \
  -Dtests.seed=D88CACE9A9C4772A \
  -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcSqlSpecIT \
  -Dtests.method="test {agg-ordering.testMultipleGroupingsAndOrderingByGroupsWithFunctions_1}" \
  -Dtests.security.manager=true \
  -Dtests.locale=tr-TR \
  -Dtests.timezone=America/Coral_Harbour \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :x-pack:plugin:sql:qa:single-node:integTestRunner \
  -Dtests.seed=D88CACE9A9C4772A \
  -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcSqlSpecIT \
  -Dtests.method="test {agg-ordering.testMultipleGroupingsAndOrderingByGroupsWithFunctions_3}" \
  -Dtests.security.manager=true \
  -Dtests.locale=tr-TR \
  -Dtests.timezone=America/Coral_Harbour \
  -Dcompiler.java=11 \
  -Druntime.java=8
```
