### ISSUE TITLE
MockDiskUsagesIT.testRerouteOccursOnDiskPassingHighWatermark fails in CI

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#40174]
The MockDiskUsagesIT#testRerouteOccursOnDiskPassingHighWatermark failed in CI since the node was expected to have 4 shards assigned to it but had 5. https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=immutable&&linux&&docker/81/console

Reproduce line (did not reproduce locally):

```
./gradlew :server:integTest \
  -Dtests.seed=2A58B98CB4ABA8E \
  -Dtests.class=org.elasticsearch.cluster.routing.allocation.decider.MockDiskUsagesIT \
  -Dtests.method="testRerouteOccursOnDiskPassingHighWatermark" \
  -Dtests.security.manager=true \
  -Dtests.locale=prg \
  -Dtests.timezone=Asia/Damascus \
  -Dcompiler.java=11 \
  -Druntime.java=11
```

Watermark triggered:

```
  1> [2019-03-18T18:45:27,176][WARN ][o.e.c.r.a.DiskThresholdMonitor] [node_t2] high disk watermark [90%] exceeded on [BY2R46gDQlCOF6x8VIUBvA][][/dev/null] free: 0b[0%], shards will be relocated away from this node
  1> [2019-03-18T18:45:27,178][INFO ][o.e.c.r.a.DiskThresholdMonitor] [node_t2] rerouting shards: [high disk watermark exceeded on one or more nodes]
```

Number of shards check that triggers the test failure:

```
   > Throwable #1: java.lang.AssertionError: node1 has 5 shards
   > Expected: <5>
   >      but: was <4>
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.cluster.routing.allocation.decider.MockDiskUsagesIT.lambda$testRerouteOccursOnDiskPassingHighWatermark$2(MockDiskUsagesIT.java:123)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:862)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:836)
   > 	at org.elasticsearch.cluster.routing.allocation.decider.MockDiskUsagesIT.testRerouteOccursOnDiskPassingHighWatermark(MockDiskUsagesIT.java:114)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   > 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   > 	at java.base/java.lang.Thread.run(Thread.java:834)
   > 	Suppressed: java.lang.AssertionError: node1 has 5 shards
```

**Comment by ywelsch** [comment]
more recent failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java12,nodes=immutable&&linux&&docker/121/console
