### ISSUE TITLE
FullClusterRestartIT#testWatcher failure in CI

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#40178]
The testWatcher test in the FullClusterRestartIT class failed in CI, https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2595/console. This did not reproduce for me.

Reproduce line:

```
./gradlew :x-pack:qa:full-cluster-restart:without-system-key:v7.0.0#upgradedClusterTestRunner \
  -Dtests.seed=B937D3C214B32CC5 \
  -Dtests.class=org.elasticsearch.xpack.restart.FullClusterRestartIT \
  -Dtests.method="testWatcher" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-TN \
  -Dtests.timezone=America/Swift_Current \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Error:

```
java.lang.AssertionError: 
Expected: <2>
     but: was <3>
	at __randomizedtesting.SeedInfo.seed([B937D3C214B32CC5:D4DA200FE4D2BB33]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.restart.FullClusterRestartIT.assertBasicWatchInteractions(FullClusterRestartIT.java:369)
	at org.elasticsearch.xpack.restart.FullClusterRestartIT.testWatcher(FullClusterRestartIT.java:186)
```

It looks like the test depends on versioning, but something else updates the watch between creation and the update; maybe execution of the watch?

**Comment by jaymode** [comment]
Muted on [master](267c3237958f83713a8b60b16e85452e7c2e69ab), [7.x](afaa7e60f90c3ef4ca55f20f866601addc20e64a), and [7.0](d26903d12513ad4fc38fb154edeefdfaf9ff2c6c).
