### ISSUE TITLE
NodeConnectionsServiceTests.testOnlyBlocksOnConnectionsToNewNodes failure in CI

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#40170]
This failure did not reproduce for me locally, but the logs indicate there was a timeout waiting on a cyclic barrier.

Reproduce line:

```
./gradlew :server:unitTest \
  -Dtests.seed=554DE96B7BC2A9A7 \
  -Dtests.class=org.elasticsearch.cluster.NodeConnectionsServiceTests \
  -Dtests.method="testOnlyBlocksOnConnectionsToNewNodes" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-US \
  -Dtests.timezone=America/Denver \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Error:

```
java.util.concurrent.TimeoutException
	at __randomizedtesting.SeedInfo.seed([554DE96B7BC2A9A7:49589A0B59CD9920]:0)
	at java.util.concurrent.CyclicBarrier.dowait(CyclicBarrier.java:257)
	at java.util.concurrent.CyclicBarrier.await(CyclicBarrier.java:435)
	at org.elasticsearch.cluster.NodeConnectionsServiceTests.testOnlyBlocksOnConnectionsToNewNodes(NodeConnectionsServiceTests.java:258)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

It looks like there may be a different issue that caused this:

```
  1> [2019-03-18T11:41:24,618][INFO ][o.e.c.NodeConnectionsServiceTests] [testOnlyBlocksOnConnectionsToNewNodes] before test
  1> [2019-03-18T11:41:24,756][WARN ][o.e.c.NodeConnectionsService] [org.elasticsearch.cluster.NodeConnectionsServiceTests] failed to connect to {node0}{WpLlmHiZSYmOtYRJklZTuQ}{0.0.0.0}{0.0.0.0:2} (tried [1] times)
  1> java.lang.IllegalStateException: connection manager is closed
  1> 	at org.elasticsearch.transport.ConnectionManager.ensureOpen(ConnectionManager.java:230) ~[main/:?]
  1> 	at org.elasticsearch.transport.ConnectionManager.connectToNode(ConnectionManager.java:96) ~[main/:?]
  1> 	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:343) ~[main/:?]
  1> 	at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:330) ~[main/:?]
  1> 	at org.elasticsearch.cluster.NodeConnectionsServiceTests$TestTransportService.connectToNode(NodeConnectionsServiceTests.java:372) ~[test/:?]
  1> 	at org.elasticsearch.cluster.NodeConnectionsService$ConnectionTarget$1.doRun(NodeConnectionsService.java:304) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:747) [main/:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [main/:8.0.0-SNAPSHOT]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
  1> [2019-03-18T11:41:24,760][INFO ][o.e.c.NodeConnectionsServiceTests] [testOnlyBlocksOnConnectionsToNewNodes] after test
```

Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2602/console

**Comment by DaveCTurner** [comment]
The Jenkins logs are gone and there doesn't seem to be enough information in the build scans to investigate further. This test also failed a few days later here: https://scans.gradle.com/s/4uz2odrtvfa7s/console-log?task=:server:unitTest but hasn't failed since then.

**Comment by jkakavas** [comment]
@DaveCTurner reopening this as it failed in 7.2 today. 

Build scan : https://gradle.com/s/7tnm3bnt4szh6 
Console log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk12,nodes=immutable&&linux&&docker/3/console

**Comment by ywelsch** [comment]
This failed again in a recent PR build on master:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/2129/testReport/junit/org.elasticsearch.cluster/NodeConnectionsServiceTests/testOnlyBlocksOnConnectionsToNewNodes/ as well as on 15.6.2019 in a regular CI build on master: https://gradle.com/s/b56amk7tklpl6

**Comment by DaveCTurner** [comment]
The new failures look to be a different `await()` call timing out from the earlier ones. I've run thousands of iterations locally without being able to reproduce anything. Two possibilities that come to mind are:

- a test bug in which we hit the `CyclicBarrier` twice by accident, or
- CI is slow, maybe doing GC, and stops for ≥10s.

Unfortunately there aren't many clues in the output today, so I opened #43979 to add more logging which will help to distinguish these possibilities.

**Comment by DaveCTurner** [comment]
It was neither of the possibilities I suggested above, but it was a related test bug to do with a missing happens-before relationship. I opened #44114 to fix it.
