### ISSUE TITLE
MovAvgIT#testHoltSingleValuedField fails reproducibly

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#40181]
The MovAvgIT#testHoltSingleValuedField fails reproducibly with a given seed.

```
./gradlew :server:integTest -Dtests.seed=192DFF899301D608 -Dtests.class=org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgIT -Dtests.method="testHoltSingleValuedField" -Dtests.security.manager=true -Dtests.locale=sr-CS -Dtests.timezone=Pacific/Wallis -Dcompiler.java=11 -Druntime.java=8
```

Error:

```
   > Throwable #1: java.lang.AssertionError: [value] movavg does not match expected [3.765046817215115E-7 vs 4.5550498861500755E-7] expected:<3.765046817215115E-7> but was:<4.5550498861500755E-7>
   >    at __randomizedtesting.SeedInfo.seed([192DFF899301D608:F37BC35E2F75E089]:0)
   >    at org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgIT.assertBucketContents(MovAvgIT.java:1305)
   >    at org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgIT.testHoltSingleValuedField(MovAvgIT.java:597)
   >    at java.lang.Thread.run(Thread.java:748)
```

Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+multijob-unix-compatibility/os=centos-6/81/console

**Comment by polyfractal** [comment]
Tracked this down to small differences in the aggregated vs. test values, which accumulated to make big differences in the holt movavg.

As it turns out, this is because the test is using dynamic mapping, so the doubles are being mapped as floats and losing enough precision to cause issues.  Will have a test fix up shortly
