### ISSUE TITLE
IndexingMasterFailoverIT.testMasterFailoverDuringIndexingWithMappingChanges fails in CI

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#40182]
This test failed on 6.7 in CI due to an uncaught exception https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+intake/380/console.

```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=5562, name=elasticsearch[node_td3][clusterApplierService#updateTask][T#1], state=RUNNABLE, group=TGRP-IndexingMasterFailoverIT]
Caused by: java.lang.AssertionError: expected current mapping version [2] to be less than new mapping version [1]
	at __randomizedtesting.SeedInfo.seed([2E1C5CE2B0C81EC0]:0)
	at org.elasticsearch.index.mapper.MapperService.assertMappingVersion(MapperService.java:301)
	at org.elasticsearch.index.mapper.MapperService.updateMapping(MapperService.java:250)
	at org.elasticsearch.index.IndexService.updateMapping(IndexService.java:549)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.updateIndices(IndicesClusterStateService.java:533)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:266)
	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$6(ClusterApplierService.java:484)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:481)
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:468)
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:419)
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:163)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Reproduce (does not reproduce locally): 

```
./gradlew :server:integTest \
  -Dtests.seed=2E1C5CE2B0C81EC0 \
  -Dtests.class=org.elasticsearch.action.support.master.IndexingMasterFailoverIT \
  -Dtests.method="testMasterFailoverDuringIndexingWithMappingChanges" \
  -Dtests.security.manager=true \
  -Dtests.locale=no \
  -Dtests.timezone=Singapore \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

**Comment by ywelsch** [comment]
This is an issue that can unfortunately happen with Zen Discovery when there's a very unlucky timing. This is fixed with the new cluster coordination subsystem in 7.0+. The logs have gone on this one, and there are no more recent failures (it's a very rare thing to happen). What happened here I think is that a committed cluster state update got lost, which is possible in the way that the  test operates:
- cluster with 3 master-eligible nodes and 1 data node.
- indexing with mapping updates ongoing.
- current master is partitioned away from the other nodes during a cluster state publication that updates the mappings (and increments the mapping version).
- data node receives a cluster state from the new master that does not take a previously committed cluster state from the previous master into account.

There's nothing we can do here.
