### ISSUE TITLE
IPFilterTests failures in CI

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#40194]
```
REPRODUCE WITH: ./gradlew :x-pack:plugin:security:unitTest \
  -Dtests.seed=83400A086A7E1281 \
  -Dtests.class=org.elasticsearch.xpack.security.transport.filter.IPFilterTests \
  -Dtests.method="testThatProfilesAreSupported" \
  -Dtests.security.manager=true \
  -Dtests.locale=nn-NO \
  -Dtests.timezone=America/Rankin_Inlet \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :x-pack:plugin:security:unitTest \
  -Dtests.seed=83400A086A7E1281 \
  -Dtests.class=org.elasticsearch.xpack.security.transport.filter.IPFilterTests \
  -Dtests.method="testThatProfilesAreUpdateable" \
  -Dtests.security.manager=true \
  -Dtests.locale=nn-NO \
  -Dtests.timezone=America/Rankin_Inlet \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

This has failed six times in the last six weeks, but is not reproducible

Link to build log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu-16.04&&virtual/229/console

**Comment by romseygeek** [comment]
Other failures:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=opensuse/307/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+multijob-unix-compatibility/os=opensuse/179/console

```
java.lang.AssertionError: Expected address 192.168.0.1 to be denied
	at __randomizedtesting.SeedInfo.seed([B402530CAE8CB200:FED7701F1679DA9C]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.elasticsearch.xpack.security.transport.filter.IPFilterTests.assertAddressIsDeniedForProfile(IPFilterTests.java:290)
	at org.elasticsearch.xpack.security.transport.filter.IPFilterTests.assertAddressIsDenied(IPFilterTests.java:298)
	at org.elasticsearch.xpack.security.transport.filter.IPFilterTests.testThatProfilesAreSupported(IPFilterTests.java:143)
```

**Comment by romseygeek** [comment]
The failures have all been in `multijob-unix-compatibility` jobs, on ubuntu or opensuse
