### ISSUE TITLE
elasticsearch rest client can not send request success after elasticsearch node restart

### ISSUE THREAD

**Issue by saiergong** [elastic/elasticsearch#40204]
ES version: 6.6.2
ES rest client version:6.6.2
jvm version:1.8.0_112

**Description of the problem including expected versus actual behavior**:
i use es rest client to send bulk request to es, and i use sniffer to detect my es cluster nodes.  At begin, everything is ok, but after i restart some of my es nodes, i can not send request to es at all.

**Steps to reproduce**:
 1. start my application, it will send bulk request to es periodically
 2. shutdown two of es cluster nodes, wait for a minute. My es cluster has only three nodes, and the mimum master nodes is set to 2. So after shutdown two nodes, the cluster has no master.
 3. restart the es nodes
 4. my application can not send request at all.

 **debug logs**
```
[DEBUG][2019-03-19 20:31:27,939][client.MainClientExec:121] [exchange: 605] start execution
[DEBUG][2019-03-19 20:31:27,939][protocol.RequestAddCookies:122] CookieSpec selected: default
[DEBUG][2019-03-19 20:31:27,940][protocol.RequestAuthCache:130] Re-using cached 'basic' auth scheme for http://x.x.x.x:9200
[DEBUG][2019-03-19 20:31:27,940][protocol.RequestAuthCache:144] No credentials for preemptive authentication
[DEBUG][2019-03-19 20:31:27,940][client.InternalHttpAsyncClient:352] [exchange: 605] Request connection for {}->http://x.x.x.x:9200
[DEBUG][2019-03-19 20:31:27,940][conn.PoolingNHttpClientConnectionManager:250] Connection request: [route: {}->http://x.x.x.x:9200][total kept alive: 0; route allocated: 0 of 10; total allocated: 0 of 30]
[DEBUG][2019-03-19 20:31:29,893][client.MainClientExec:121] [exchange: 606] start execution
[DEBUG][2019-03-19 20:31:29,893][protocol.RequestAddCookies:122] CookieSpec selected: default
[DEBUG][2019-03-19 20:31:29,893][protocol.RequestAuthCache:130] Re-using cached 'basic' auth scheme for http://x.x.x.x:9200
[DEBUG][2019-03-19 20:31:29,893][protocol.RequestAuthCache:144] No credentials for preemptive authentication
[DEBUG][2019-03-19 20:31:29,893][client.InternalHttpAsyncClient:352] [exchange: 606] Request connection for {}->http://x.x.x.x:9200
[DEBUG][2019-03-19 20:31:29,894][conn.PoolingNHttpClientConnectionManager:250] Connection request: [route: {}->http://x.x.x.x:9200][total kept alive: 0; route allocated: 0 of 10; total allocated: 0 of 30]
[ERROR][2019-03-19 20:31:31,893][is.ESRecordWriter:85] retry bulk request to es failed, error (java.io.IOException: listener timeout after waiting for [60000] ms), retry count (4).
[ERROR][2019-03-19 20:31:31,893][is.ESRecordWriter:86] 
java.io.IOException: listener timeout after waiting for [60000] ms
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:908)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229)
	at com.is.ESRecordWriter$2.onFailure(ESRecordWriter.java:81)
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:853)
	at org.elasticsearch.client.RestClient$1.retryIfPossible(RestClient.java:591)
	at org.elasticsearch.client.RestClient$1.failed(RestClient.java:569)
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:419)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:375)
	at org.apache.http.impl.nio.client.InternalRequestExecutor.timeout(InternalRequestExecutor.java:116)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:263)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:492)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:213)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:745)

```
The logs above will be repeated all the time.

**my application code**
```
SniffOnFailureListener sniffOnFailureListener =
                new SniffOnFailureListener();
        restClient = RestClient.builder(
                new HttpHost(seedNode, 9200, "http"))
                .setNodeSelector(NodeSelector.SKIP_DEDICATED_MASTERS)
                .setRequestConfigCallback(
                        new RestClientBuilder.RequestConfigCallback() {
                            @Override
                            public RequestConfig.Builder customizeRequestConfig(RequestConfig.Builder builder) {
                                return builder.setSocketTimeout(10000)
                                        .setConnectTimeout(10000)
                                        .setConnectionRequestTimeout(10000);
                            }
                        }
                )
                .setFailureListener(sniffOnFailureListener)
                .setMaxRetryTimeoutMillis(60000)
                .build();

        sniffer = Sniffer.builder(restClient)
                .setSniffIntervalMillis(60000)
                .setSniffAfterFailureDelayMillis(30000)
                .build();
        sniffOnFailureListener.setSniffer(sniffer);
```

**Comment by javanna** [comment]
Can you elaborate on your choice around sniff interval (60 seconds) and sniff after failure delay (30 seconds)? Have you tried increasing the maxRetryTimeout even further? Have you tried sending requests later, do you keep on getting those timeouts or do requests at some point go back to normal?

**Comment by saiergong** [comment]
```
public void bulk(String values, final String index, final String type) {
        final Request request = new Request("POST", index + "/" + type + "/_bulk");
        request.setJsonEntity(values);

        restClient.performRequestAsync(request, new ResponseListener() {
            @Override
            public void onSuccess(Response response) {
                LOG.info("success.");
            }

            @Override
            public void onFailure(Exception exception)  {
                if(exception instanceof ResponseException){

                }else {
                    int retry = 1;
                    while(true){
                        try{
                            if(retry >= 30){
                                LOG.error("failed after 30 retries, will fail this task.");
                                break;
                            }
                            //use sync method to resent request
                            Response response = restClient.performRequest(request);
                            LOG.info("resent request succeed");
                            return;
                        }catch (Exception e){
                            LOG.error("retry failed.");
                            LOG.error("",e);
                            retry++;
                            try{
                                //sleep if failed again
                                Thread.sleep(3000);
                            }catch (Exception ee){

                            }

                        }

                    }
                }

            }
        });
    }


        int count = 0;
        while(count < 40){
            StringBuilder value = new StringBuilder();
            for (int i = 0; i < 10; i++){

                value.append(metaData);
                value.append(String.format(data, i));
                value.append("\n");
            }

            value.append(metaData);
            value.append("{\"f1\":\"fff\"}");
            value.append("\n");

            //System.out.println(value.toString());
            writer.bulk(value.toString(), "test", "test");
            count++;

            try{
                Thread.sleep(10000);
            }catch (Exception e){

            }

        }
```

here is the code i testd,  i shutdown es when i sent several request,  then when i restart es, no request can be success.  And "java.io.IOException: listener timeout after waiting for [60000] ms" error repeated all the time

**Comment by javanna** [comment]
I don't think that retrying from the onFailure callback makes sense, especially using a sync call and putting sleep in there as well. I would not be surprised if this causes unexpected results. If you want to test that the client starts sending successful requests after the node it's pointing to was restarted, I would recommend that you have independent calls, rather than from a listener. Say you can schedule a request every 5/10 seconds and see when things go back to normal. Note that you are also using sniffing, and sniff on failure. What state is your cluster in once those two nodes that you shut down are back up? Have you tried sending curl requests to them?

**Comment by saiergong** [comment]
Es cluster state is green after the two nodes come back, and i can send curl request to the them. the reason i use sync request in onFailure callback is that i want to retry my request until es cluster become green if es is down.

**Comment by javanna** [comment]
Note that retrying is built-in, meaning a failed request will be retried on other nodes.  There is no automatic retry though against the same node that failed. As I said, making blocking calls in a listener callback is a bad idea and will likely cause problems. I'd recommend that you try and rely on retries on different nodes that is built-in, otherwise, if all nodes are down, you should have some kind of queue mechanism in your app rather than retrying from a listener callback.

**Comment by ebadyano** [comment]
Closing the issue as no further feedback received. @saiergong if you have any further comments please and we can look at re-opening this issue.
