### ISSUE TITLE
SQL: CI failure for JdbcResultSetIT.testGettingDateWithoutCalendar

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#40289]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+intake/338/console

This is reproducible in 6.6 only: `gradlew :x-pack:plugin:sql:qa:single-node:integTestRunner -Dtests.seed=9F4601A0B84D0E0E -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT -Dtests.method="testGettingDateWithoutCalendar" -Dtests.security.manager=true -Dtests.locale=fr-FR -Dtests.timezone=America/Costa_Rica -Dcompiler.java=11 -Druntime.java=8`

```
  2> REPRODUCE WITH: gradlew :x-pack:plugin:sql:qa:single-node:integTestRunner -Dtests.seed=9F4601A0B84D0E0E -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT -Dtests.method="testGettingDateWithoutCalendar" -Dtests.security.manager=true -Dtests.locale=fr-FR -Dtests.timezone=America/Costa_Rica -Dcompiler.java=11 -Dru

FAILURE 3.02s | JdbcResultSetIT.testGettingDateWithoutCalendar <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected: java.sql.Date<071-09-07> but was: java.sql.Date<071-09-07>
   >    at __randomizedtesting.SeedInfo.seed([9F4601A0B84D0E0E:A62FAE9BFAB593CF]:0)
   >    at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.lambda$testGettingDateWithoutCalendar$118(ResultSetTestCase.java:833)
   >    at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1312)
   >    at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.testGettingDateWithoutCalendar(ResultSetTestCase.java:821)
   >    at java.lang.Thread.run(Thread.java:748)
  2> NOTE: leaving temporary files on disk at: W:\Eclipse_workspace_6.6\elasticsearch\x-pack\plugin\sql\qa\single-node\build\testrun\integTestRunner\J0\temp\org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT_9F4601A0B84D0E0E-001
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=562, maxMBSortInHeap=6.399105159024325, sim=RandomSimilarity(queryNorm=false): {}, locale=fr-FR, timezone=America/Costa_Rica
  2> NOTE: Windows 10 10.0 amd64/Oracle Corporation 1.8.0_172 (64-bit)/cpus=8,threads=1,free=448705328,total=514850816
  2> NOTE: All tests run in this JVM: [JdbcResultSetIT]
Completed [1/1] in 5.62s, 1 test, 1 failure <<< FAILURES!
```

Original error from CI:

```
java.lang.AssertionError: expected: java.sql.Date<ï¿½071-09-07> but was: java.sql.Date<ï¿½071-09-07>
	at __randomizedtesting.SeedInfo.seed([9F4601A0B84D0E0E:A62FAE9BFAB593CF]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.lambda$testGettingDateWithoutCalendar$118(ResultSetTestCase.java:833)
	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1312)
	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.testGettingDateWithoutCalendar(ResultSetTestCase.java:821)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by matriv** [comment]
Backported to `7.x` with 143db10980c6e9ce6be3d4dd5a5b5b67e7f9e5ed
to `7.0` with 67661049503c9004fd48e10780470755a1543056
to `6.7` with 0dd8132cf733f1dcaf9159e215fae4b8b0226831
to `6.6` with a2e83fb4e002c657b5ba7a07f474fc46b62d9006

**Comment by polyfractal** [comment]
@matriv Was a backport to 6.8 missed by chance?  Just had a failure on the 6.8 branch:

https://gradle-enterprise.elastic.co/s/fkli57jh26tae

```
java.lang.AssertionError: expected: java.sql.Date<�837-11-16> but was: java.sql.Date<�837-11-16>
```

**Comment by matriv** [comment]
@polyfractal No, the cherry-picked commit is there.
I will take a look.

**Comment by matriv** [comment]
Cannot reproduce it until now.
