### ISSUE TITLE
ml/set_upgrade_mode.yml#"Setting upgrade_mode to enabled" failure on CI

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#40385]
Failed on 7.0 intake: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+intake/500/console (new intake commit is an unrelated docs change)

Reproduce line (does not reproduce locally):
```
./gradlew :x-pack:plugin:integTestRunner \
  -Dtests.seed=971A963D9AC18AC0 \
  -Dtests.class=org.elasticsearch.xpack.test.rest.XPackRestIT \
  -Dtests.method="test {p0=ml/set_upgrade_mode/Setting upgrade_mode to enabled}" \
  -Dtests.security.manager=true \
  -Dtests.locale=lt \
  -Dtests.timezone=Europe/Lisbon \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

Stack trace:
```
java.lang.RuntimeException: Had to resort to force-closing jobs, something went wrong?
	at __randomizedtesting.SeedInfo.seed([971A963D9AC18AC0:1F4EA9E7343DE738]:0)
	at org.elasticsearch.xpack.core.ml.integration.MlRestTestStateCleaner.deleteAllJobs(MlRestTestStateCleaner.java:85)
	at org.elasticsearch.xpack.core.ml.integration.MlRestTestStateCleaner.clearMlMetadata(MlRestTestStateCleaner.java:31)
	at org.elasticsearch.xpack.test.rest.XPackRestIT.clearMlState(XPackRestIT.java:270)
	at org.elasticsearch.xpack.test.rest.XPackRestIT.cleanup(XPackRestIT.java:254)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:38309], URI [/_ml/anomaly_detectors/_all/_close], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"exception","reason":"Unable to read field length from input stream\nFailed to parse length encoded header from stream\nFailed to handle all input data\nMl anomaly detector job failed\n"}],"type":"exception","reason":"Exception closing autodetect process","caused_by":{"type":"exception","reason":"Unable to read field length from input stream\nFailed to parse length encoded header from stream\nFailed to handle all input data\nMl anomaly detector job failed\n"}},"status":500}
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:260)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:238)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212)
	at org.elasticsearch.xpack.core.ml.integration.MlRestTestStateCleaner.deleteAllJobs(MlRestTestStateCleaner.java:77)
	... 37 more
```

**Comment by davidkyle** [comment]
The interesting errors come from [autodetect parsing](https://github.com/elastic/ml-cpp/blob/7.0/lib/api/CLengthEncodedInputParser.cc#L155)

```
Unable to read field length from input stream
Failed to parse length encoded header from stream
Failed to handle all input data
Ml anomaly detector job failed
```

The expected message format is 
```
--------------------------------------------------
number of fields | length of next field | field data
--------------------------------------------------
```

'number of fields' was read but parsing 'length of next field' failed. This suggests the input stream was corrupted somehow. From the messages I can't tell if the header list of field names was read or if it choked on a data record. 

I've never seen the input corrupted like this before but, obviously it can and does happen however rarely. The logs show every thing was running smoothly without excessive delays. It could be a simultaneous write to the stream but that should be impossible. I'll keep an eye out for this.

**Comment by davidkyle** [comment]
The error is that the autodetect process expects to read a number followed by that number of fields. In this case the expected number of fields is not read because the input stream was closed as the header was being written resulting in a partial write and this error. The job is closed in the post test tear down, at the same time the job is opening because upgrade mode is disabled at the end of the test which brings the job back to life (asynchronously sometime after the API call is made). 

In theory it is not possible to close the outputstream whilst it is being written to as access is guarded by an `ExecutorService` with a single worker but there is a [small window](https://github.com/elastic/elasticsearch/blob/7.0/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java#L465) where the process is visible but the header has not been written (that happens in the `init()` call), closing the outputstream at the same time will 

The fix should come quite easily and the test fails infrequently so I'll work on the fix rather than muting the test for now.
