### ISSUE TITLE
[CI] IntervalQueryBuilderTests failure

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#40436]
Reproduces on 7.x (c20ea9a)
```
./gradlew :server:unitTest \
  -Dtests.seed=6FC15D7E2936F6F \
  -Dtests.class=org.elasticsearch.index.query.IntervalQueryBuilderTests \
  -Dtests.method="testNonIndexedFields" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-CU \
  -Dtests.timezone=America/Santa_Isabel \
  -Dcompiler.java=12 \
  -Druntime.java=8
```
```
FAILURE 2.23s | IntervalQueryBuilderTests.testNonIndexedFields <<< FAILURES!
   > Throwable #1: junit.framework.AssertionFailedError: Expected exception IllegalArgumentException but no exception was thrown
   >    at __randomizedtesting.SeedInfo.seed([6FC15D7E2936F6F:507048D897C026E7]:0)
   >    at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2685)
   >    at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2670)
   >    at org.elasticsearch.index.query.IntervalQueryBuilderTests.testNonIndexedFields(IntervalQueryBuilderTests.java:301)
   >    at java.lang.Thread.run(Thread.java:745)
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=oraclelinux-7/89/console

**Comment by romseygeek** [comment]
Closed by #40418
