### ISSUE TITLE
[CI] WebhookIntegrationTests failures

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#40522]
```
FAILURE 13.1s J6 | WebhookIntegrationTests.testWebhookWithBasicAuth <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: could not find executed watch record for watch _id
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 	at __randomizedtesting.SeedInfo.seed([552D2F2E1DEA46BD:BE10AAB71FC19159]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithMinimumPerformedActionsCount$2(AbstractWatcherIntegrationTestCase.java:385)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:862)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:836)
   > 	at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.assertWatchWithMinimumPerformedActionsCount(AbstractWatcherIntegrationTestCase.java:367)
   > 	at org.elasticsearch.xpack.watcher.actions.webhook.WebhookIntegrationTests.testWebhookWithBasicAuth(WebhookIntegrationTests.java:133)
   > 	at java.lang.Thread.run(Thread.java:748)
   > 	Suppressed: java.lang.AssertionError: could not find executed watch record for watch _id
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithMinimumPerformedActionsCount$2(AbstractWatcherIntegrationTestCase.java:385)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: could not find executed watch record for watch _id
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithMinimumPerformedActionsCount$2(AbstractWatcherIntegrationTestCase.java:385)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: could not find executed watch record for watch _id
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithMinimumPerformedActionsCount$2(AbstractWatcherIntegrationTestCase.java:385)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: could not find executed watch record for watch _id
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithMinimumPerformedActionsCount$2(AbstractWatcherIntegrationTestCase.java:385)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: could not find executed watch record for watch _id
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithMinimumPerformedActionsCount$2(AbstractWatcherIntegrationTestCase.java:385)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: could not find executed watch record for watch _id
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithMinimumPerformedActionsCount$2(AbstractWatcherIntegrationTestCase.java:385)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: could not find executed watch record for watch _id
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithMinimumPerformedActionsCount$2(AbstractWatcherIntegrationTestCase.java:385)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: could not find executed watch record for watch _id
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithMinimumPerformedActionsCount$2(AbstractWatcherIntegrationTestCase.java:385)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: could not find executed watch record for watch _id
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithMinimumPerformedActionsCount$2(AbstractWatcherIntegrationTestCase.java:385)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: could not find executed watch record for watch _id
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithMinimumPerformedActionsCount$2(AbstractWatcherIntegrationTestCase.java:385)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: could not find executed watch record for watch _id
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithMinimumPerformedActionsCount$2(AbstractWatcherIntegrationTestCase.java:385)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: could not find executed watch record for watch _id
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithMinimumPerformedActionsCount$2(AbstractWatcherIntegrationTestCase.java:385)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: could not find executed watch record for watch _id
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithMinimumPerformedActionsCount$2(AbstractWatcherIntegrationTestCase.java:385)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
```

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:watcher:unitTest -Dtests.seed=552D2F2E1DEA46BD -Dtests.class=org.elasticsearch.xpack.watcher.actions.webhook.WebhookIntegrationTests -Dtests.method="testWebhookWithBasicAuth" -Dtests.security.manager=true -Dtests.locale=de-LU -Dtests.timezone=America/Boa_Vista -Dcompiler.java=12 -Druntime.java=8
```

See eg. https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2765/console

Note: the seed doesn't reproduce the issue.

testWebhookWithBasicAuth is not the only one that fails, other tests in the same suite fail too.

Maybe related to #39724 as there has been a spike of failures very recently.

**Comment by jpountz** [comment]
Closing in favor of #35503
