### ISSUE TITLE
[CI] BasicWatcherTests failures

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#40524]
```
FAILURE 12.3s J7 | BasicWatcherTests.testIndexWatchRegisterWatchBeforeTargetIndex <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 	at __randomizedtesting.SeedInfo.seed([AE0F00C9FC33449D:350AF57B1556D7F3]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithNoActionNeeded$3(AbstractWatcherIntegrationTestCase.java:442)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:862)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:836)
   > 	at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.assertWatchWithNoActionNeeded(AbstractWatcherIntegrationTestCase.java:423)
   > 	at org.elasticsearch.xpack.watcher.test.integration.BasicWatcherTests.testIndexWatchRegisterWatchBeforeTargetIndex(BasicWatcherTests.java:102)
   > 	at java.lang.Thread.run(Thread.java:748)
   > 	Suppressed: java.lang.AssertionError: 
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithNoActionNeeded$3(AbstractWatcherIntegrationTestCase.java:442)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: 
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithNoActionNeeded$3(AbstractWatcherIntegrationTestCase.java:442)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: 
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithNoActionNeeded$3(AbstractWatcherIntegrationTestCase.java:442)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: 
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithNoActionNeeded$3(AbstractWatcherIntegrationTestCase.java:442)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: 
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithNoActionNeeded$3(AbstractWatcherIntegrationTestCase.java:442)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: 
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithNoActionNeeded$3(AbstractWatcherIntegrationTestCase.java:442)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: 
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithNoActionNeeded$3(AbstractWatcherIntegrationTestCase.java:442)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: 
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithNoActionNeeded$3(AbstractWatcherIntegrationTestCase.java:442)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: 
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithNoActionNeeded$3(AbstractWatcherIntegrationTestCase.java:442)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: 
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithNoActionNeeded$3(AbstractWatcherIntegrationTestCase.java:442)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: 
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithNoActionNeeded$3(AbstractWatcherIntegrationTestCase.java:442)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: 
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithNoActionNeeded$3(AbstractWatcherIntegrationTestCase.java:442)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
   > 	Suppressed: java.lang.AssertionError: 
   > Expected: a value equal to or greater than <1L>
   >      but: <0L> was less than <1L>
   > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 		at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase.lambda$assertWatchWithNoActionNeeded$3(AbstractWatcherIntegrationTestCase.java:442)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:850)
   > 		... 40 more
```

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:watcher:unitTest -Dtests.seed=AE0F00C9FC33449D -Dtests.class=org.elasticsearch.xpack.watcher.test.integration.BasicWatcherTests -Dtests.method="testIndexWatchRegisterWatchBeforeTargetIndex" -Dtests.security.manager=true -Dtests.locale=pt-PT -Dtests.timezone=America/Iqaluit -Dcompiler.java=12 -Druntime.java=8
```

This seed doesn't reproduce for me.

See https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2764/consoleFull for more details.

Maybe related to #39724 as there has been a spike of failures very recently.

**Comment by jpountz** [comment]
Closed in favor of #35503.
