### ISSUE TITLE
[ML] DataFrameTaskFailedStateIT.testFailureStateInteraction failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#40543]
The error is 

   > Expected: "Unable to start data frame transform [failure_pivot_1] as it is in a failed state with failure: [task encountered irrecoverable failure: no such index [reviews]]. Use force start to restart data frame transform once error is resolved."
   >      but: was "Unable to start data frame transform [failure_pivot_1] as it is in state [STARTED]"
   >    at __randomizedtesting.SeedInfo.seed([372767333722BFA5:B84F6CD2013B998A]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.xpack.dataframe.integration.DataFrameTaskFailedStateIT.testFailureStateInteraction(DataFrameTaskFailedStateIT.java:48)

Which is very strange as there is an assertion that the task state is failed a few lines before.

`
 ./gradlew :x-pack:plugin:data-frame:qa:single-node-tests:integTestRunner -Dtests.seed=372767333722BFA5 -Dtests.class=org.elasticsearch.xpack.dataframe.integration.DataFrameTaskFailedStateIT -Dtests.method="testFailureStateInteraction" -Dtests.security.manager=true -Dtests.locale=smn -Dtests.timezone=America/Puerto_Rico -Dcompiler.java=12 -Druntime.java=12
`

Spotted on my local machine but no doubt it will make an appearance in CI soon.

**Comment by davidkyle** [comment]
Muted master - a8b02e8676ab653dc1ebc32f92fe2035264f82ec 7.x 13d4d73ce3ea7613471c9e4a8a5b3fd2531a4b99
