### ISSUE TITLE
DataFrameAuditorIT#testAuditorWritesAudits fails

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#40594]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8fips,nodes=immutable&&linux&&docker/96/console

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:data-frame:qa:single-node-tests:integTestRunner -Dtests.seed=A6A283B9255AF201 -Dtests.class=org.elasticsearch.xpack.dataframe.integration.DataFrameAuditorIT -Dtests.method="testAuditorWritesAudits" -Dtests.security.manager=true -Dtests.locale=ar-JO -Dtests.timezone=America/Argentina/Jujuy -Dcompiler.java=12 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password
```

```
ERROR   6.94s | DataFrameAuditorIT.testAuditorWritesAudits <<< FAILURES!
   > Throwable #1: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
   > 	at __randomizedtesting.SeedInfo.seed([A6A283B9255AF201:CA8A976C60D04866]:0)
   > 	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
   > 	at java.util.ArrayList.get(ArrayList.java:433)
   > 	at org.elasticsearch.xpack.dataframe.integration.DataFrameAuditorIT.testAuditorWritesAudits(DataFrameAuditorIT.java:69)
   > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by javanna** [comment]
muted on master and 7.x
