### ISSUE TITLE
[CI] XContentParserTests#testSubParserArray fails frequently

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#40617]
Just saw three failures in the last few hours:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2818/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+artifactory/80/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+artifactory/81/console

Reproduces locally with the following seed:
```
 ./gradlew :libs:x-content:unitTest \
  -Dtests.seed=7F3152E0775C4F75 \
  -Dtests.class=org.elasticsearch.common.xcontent.XContentParserTests \
  -Dtests.method="testSubParserArray" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-VE \
  -Dtests.timezone=America/Virgin \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

```
  > Throwable #1: java.lang.AssertionError: max must be >= min: 0, -1
   >    at __randomizedtesting.SeedInfo.seed([7F3152E0775C4F75:D0BA268FB44B084A]:0)
   >    at com.carrotsearch.randomizedtesting.generators.RandomNumbers.randomIntBetween(RandomNumbers.java:16)
   >    at com.carrotsearch.randomizedtesting.RandomizedTest.randomInt(RandomizedTest.java:164)
   >    at org.elasticsearch.test.ESTestCase.randomInt(ESTestCase.java:658)
   >    at org.elasticsearch.common.xcontent.XContentParserTests.testSubParserArray(XContentParserTests.java:393)
   >    at java.lang.Thread.run(Thread.java:748)
```

**Comment by cbuescher** [comment]
@henningandersen looks like this was just recently added by you, can you take a look? I will mute the test in the meantime.

**Comment by cbuescher** [comment]
Muted in e08881b54e79903aff0b07aceb112e0e38949afd.

**Comment by henningandersen** [comment]
Thanks @cbuescher , I opened #40626 to fix it.
