### ISSUE TITLE
[CI] InternalAggregationsTests.testSerializationFromPre_6_7_0 fails

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#40680]
`InternalAggregationsTests.testSerializationFromPre_6_7_0` failed in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+release-tests/218/console

I reproduced this locally using:

```
./gradlew :server:unitTest   -Dtests.seed=90C60FB607C6F47A   -Dtests.class=org.elasticsearch.search.aggregations.InternalAggregationsTests   -Dtests.method="testSerializationFromPre_6_7_0"   -Dtests.security.manager=true -Dtests.locale=mk   -Dtests.timezone=Indian/Mauritius   -Dcompiler.java=12   -Druntime.java=8
```

(That's the same seed as the failed CI build, but a snapshot rather than release build.)

The test repeatedly failed with that seed but sometimes passed with other seeds, so appears to be seed-specific.

The exception is:

```
   > Throwable #1: java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.search.aggregations.pipeline.PipelineAggregator][]
   > 	at __randomizedtesting.SeedInfo.seed([90C60FB607C6F47A:4BC21ACDE8469975]:0)
   > 	at org.elasticsearch.common.io.stream.NamedWriteableRegistry.getReader(NamedWriteableRegistry.java:112)
   > 	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:45)
   > 	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:39)
   > 	at org.elasticsearch.search.aggregations.InternalAggregations.lambda$readFrom$3(InternalAggregations.java:155)
   > 	at org.elasticsearch.common.io.stream.StreamInput.readCollection(StreamInput.java:990)
   > 	at org.elasticsearch.common.io.stream.StreamInput.readList(StreamInput.java:962)
   > 	at org.elasticsearch.search.aggregations.InternalAggregations.readFrom(InternalAggregations.java:154)
   > 	at org.elasticsearch.search.aggregations.InternalAggregations.readAggregations(InternalAggregations.java:143)
   > 	at org.elasticsearch.search.aggregations.bucket.histogram.InternalDateHistogram$EmptyBucketInfo.<init>(InternalDateHistogram.java:189)
   > 	at org.elasticsearch.search.aggregations.bucket.histogram.InternalDateHistogram.<init>(InternalDateHistogram.java:247)
   > 	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:46)
   > 	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:39)
   > 	at org.elasticsearch.search.aggregations.InternalAggregations.lambda$readFrom$2(InternalAggregations.java:149)
   > 	at org.elasticsearch.common.io.stream.StreamInput.readCollection(StreamInput.java:990)
   > 	at org.elasticsearch.common.io.stream.StreamInput.readList(StreamInput.java:962)
   > 	at org.elasticsearch.search.aggregations.InternalAggregations.readFrom(InternalAggregations.java:149)
   > 	at org.elasticsearch.search.aggregations.InternalAggregations.readAggregations(InternalAggregations.java:143)
   > 	at org.elasticsearch.search.aggregations.InternalAggregationsTests.testSerializationFromPre_6_7_0(InternalAggregationsTests.java:171)
   > 	at java.lang.Thread.run(Thread.java:748)
```

I noticed the test picks a random version prior to the current version.  Could the problem be that now we're on 6.7.1 that random version is sometimes 6.7.0?

**Comment by javanna** [comment]
Fixed by e069129327d3f82486c5856baef4b404d4e71926
