### ISSUE TITLE
ScriptDocValuesGeoPointsTests.testMissingValues reliably fails

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#40684]
Failed build:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/11209/

Reproduction line: 
```
./gradlew :server:unitTest -Dtests.seed=371E32FE344345FF -Dtests.class=org.elasticsearch.index.fielddata.ScriptDocValuesGeoPointsTests -Dtests.method="testMissingValues" -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=US/Hawaii -Dcompiler.java=12 -Druntime.java=8
```

Error: 
```
ERROR   0.05s J4 | ScriptDocValuesGeoPointsTests.testMissingValues <<< FAILURES!
   > Throwable #1: java.lang.NullPointerException
   > 	at __randomizedtesting.SeedInfo.seed([371E32FE344345FF:5D8360B810C9710E]:0)
   > 	at org.elasticsearch.index.fielddata.ScriptDocValues$GeoPoints.setNextDocId(ScriptDocValues.java:277)
   > 	at org.elasticsearch.index.fielddata.ScriptDocValuesGeoPointsTests.testMissingValues(ScriptDocValuesGeoPointsTests.java:124)
   > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by droberts195** [comment]
This is causing a lot of failures, for example:

* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+artifactory/130/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2866/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2867/console

I will mute it.
