### ISSUE TITLE
[CI] xpack.sql.qa.single_node.JdbcCsvSpecIT failed on master with SqlIllegalArgumentException

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#40718]
CI job https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2884/console failed on `org.elasticsearch.xpack.sql.qa.single_node.JdbcCsvSpecIT` with the following trace:

```
   > Throwable #1: java.sql.SQLException: Server encountered an error [A [date], a [time] or a [datetime] is required; received 00:10Z]. [SqlIllegalArgumentException[A [date], a [time] or a [datetime] is required; received 00:10Z]
   > 	at org.elasticsearch.xpack.sql.expression.function.scalar.datetime.BaseDateTimeProcessor.process(BaseDateTimeProcessor.java:46)
   > 	at org.elasticsearch.xpack.sql.expression.gen.processor.ChainingProcessor.doProcess(ChainingProcessor.java:45)
   > 	at org.elasticsearch.xpack.sql.expression.gen.processor.UnaryProcessor.process(UnaryProcessor.java:36)
   > 	at org.elasticsearch.xpack.sql.execution.search.extractor.ComputingExtractor.extract(ComputingExtractor.java:73)
   > 	at org.elasticsearch.xpack.sql.execution.search.CompositeAggsRowSet.extractValue(CompositeAggsRowSet.java:63)
   > 	at org.elasticsearch.xpack.sql.execution.search.CompositeAggsRowSet.extractValue(CompositeAggsRowSet.java:22)
   > 	at org.elasticsearch.xpack.sql.execution.search.ResultRowSet.getColumn(ResultRowSet.java:37)
   > 	at org.elasticsearch.xpack.sql.session.AbstractRowSet.column(AbstractRowSet.java:18)
   > 	at org.elasticsearch.xpack.sql.session.RowView.forEachColumn(RowView.java:38)
   > 	at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.lambda$createResponse$2(TransportSqlQueryAction.java:104)
   > 	at org.elasticsearch.xpack.sql.session.RowSet.forEachRow(RowSet.java:32)
   > 	at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.createResponse(TransportSqlQueryAction.java:102)
   > 	at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.lambda$operation$1(TransportSqlQueryAction.java:82)
   > 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)
   > 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)
   > 	at org.elasticsearch.xpack.sql.execution.search.CompositeAggregationCursor$1.onResponse(CompositeAggregationCursor.java:138)
   > 	at org.elasticsearch.xpack.sql.execution.search.CompositeAggregationCursor$1.onResponse(CompositeAggregationCursor.java:125)
...
```

This reproduces locally for me using:

```
$ ./gradlew :x-pack:plugin:sql:qa:single-node:integTestRunner   -Dtests.seed=C2C10705D1DFC60E   -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcCsvSpecIT   -Dtests.method="test {time.testTimeAsHavingFilter}"   -Dtests.security.manager=true   -Dtests.locale=sr-RS   -Dtests.timezone=Europe/Tiraspol   -Dcompiler.java=12   -Druntime.java=8
```

**Comment by dliappis** [comment]
Closed as duplicate of #40717
