### ISSUE TITLE
SQL [CI]: time.testTimeAsHavingFilter failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#40717]
This one is reproduceable with the command:

```
gradlew :x-pack:plugin:sql:qa:single-node:integTestRunner -Dtests.seed=C2C10705D1DFC60E -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcCsvSpecIT -Dtests.method="test {time.testTimeAsHavingFilter}" -Dtests.security.manager=true -Dtests.locale=sr-RS -Dtests.timezone=Europe/Tiraspol -Dcompiler.java=12 -Druntime.java=8
```

and

```
gradlew :x-pack:plugin:sql:qa:single-node:integTestRunner -Dtests.seed=C2C10705D1DFC60E -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcCsvSpecIT -Dtests.method="test {time.testTimeExtractTimeParts}" -Dtests.security.manager=true -Dtests.locale=sr-RS -Dtests.timezone=Europe/Tiraspol -Dcompiler.java=12 -Druntime.java=8
```

Error:

```
Suite: org.elasticsearch.xpack.sql.qa.single_node.JdbcCsvSpecIT
  1> [2019-04-02T09:25:13,616][INFO ][o.e.x.s.q.s.JdbcCsvSpecIT] [test] [time.testTimeAsHavingFilter] before test
  1> [2019-04-02T09:25:14,065][INFO ][o.e.x.s.q.s.JdbcCsvSpecIT] [test] initializing REST clients against [http://127.0.0.1:59572]
  1> [2019-04-02T09:25:17,942][INFO ][o.e.x.s.q.s.JdbcCsvSpecIT] [test] [time.testTimeAsHavingFilter] after test
  2> REPRODUCE WITH: gradlew :x-pack:plugin:sql:qa:single-node:integTestRunner -Dtests.seed=C2C10705D1DFC60E -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcCsvSpecIT -Dtests.method="test {time.testTimeAsHavingFilter}" -Dtests.security.manager=true -Dtests.locale=sr-RS -Dtests.timezone=Europe/Tiraspol -Dcompiler.java=12 -Druntime.java=8
ERROR   4.42s | JdbcCsvSpecIT.test {time.testTimeAsHavingFilter} <<< FAILURES!
   > Throwable #1: java.sql.SQLException: Server encountered an error [A [date], a [time] or a [datetime] is required; received 00:10Z]. [SqlIllegalArgumentException[A [date], a [time] or a [datetime] is required; received 00:10Z]
   >    at org.elasticsearch.xpack.sql.expression.function.scalar.datetime.BaseDateTimeProcessor.process(BaseDateTimeProcessor.java:46)
   >    at org.elasticsearch.xpack.sql.expression.gen.processor.ChainingProcessor.doProcess(ChainingProcessor.java:45)
   >    at org.elasticsearch.xpack.sql.expression.gen.processor.UnaryProcessor.process(UnaryProcessor.java:36)
   >    at org.elasticsearch.xpack.sql.execution.search.extractor.ComputingExtractor.extract(ComputingExtractor.java:73)
   >    at org.elasticsearch.xpack.sql.execution.search.CompositeAggsRowSet.extractValue(CompositeAggsRowSet.java:63)
   >    at org.elasticsearch.xpack.sql.execution.search.CompositeAggsRowSet.extractValue(CompositeAggsRowSet.java:22)
   >    at org.elasticsearch.xpack.sql.execution.search.ResultRowSet.getColumn(ResultRowSet.java:37)
   >    at org.elasticsearch.xpack.sql.session.AbstractRowSet.column(AbstractRowSet.java:18)
   >    at org.elasticsearch.xpack.sql.session.RowView.forEachColumn(RowView.java:38)
   >    at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.lambda$createResponse$2(TransportSqlQueryAction.java:104)
   >    at org.elasticsearch.xpack.sql.session.RowSet.forEachRow(RowSet.java:32)
   >    at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.createResponse(TransportSqlQueryAction.java:102)
   >    at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.lambda$operation$1(TransportSqlQueryAction.java:82)
   >    at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)
   >    at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)
   >    at org.elasticsearch.xpack.sql.execution.search.CompositeAggregationCursor$1.onResponse(CompositeAggregationCursor.java:138)
   >    at org.elasticsearch.xpack.sql.execution.search.CompositeAggregationCursor$1.onResponse(CompositeAggregationCursor.java:125)
   >    at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:68)
   >    at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64)
   >    at org.elasticsearch.action.search.AbstractSearchAsyncAction.onResponse(AbstractSearchAsyncAction.java:316)
   >    at org.elasticsearch.action.search.AbstractSearchAsyncAction.onResponse(AbstractSearchAsyncAction.java:51)
   >    at org.elasticsearch.action.search.FetchSearchPhase$3.run(FetchSearchPhase.java:213)
   >    at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:166)
   >    at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:159)
   >    at org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:120)
   >    at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:166)
   >    at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:159)
   >    at org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:206)
   >    at org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$2(FetchSearchPhase.java:104)
   >    at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:110)
   >    at org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:44)
   >    at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:86)
   >    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   >    at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:43)
   >    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:747)
   >    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
   >    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   >    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   >    at java.lang.Thread.run(Thread.java:748)
   > ]
   >    at __randomizedtesting.SeedInfo.seed([C2C10705D1DFC60E:4A9538DF7F23ABF6]:0)
   >    at org.elasticsearch.xpack.sql.client.JreHttpUrlConnection.parserError(JreHttpUrlConnection.java:178)
   >    at org.elasticsearch.xpack.sql.client.JreHttpUrlConnection.request(JreHttpUrlConnection.java:161)
   >    at org.elasticsearch.xpack.sql.client.HttpClient.lambda$post$1(HttpClient.java:104)
   >    at org.elasticsearch.xpack.sql.client.JreHttpUrlConnection.http(JreHttpUrlConnection.java:65)
   >    at org.elasticsearch.xpack.sql.client.HttpClient.lambda$post$2(HttpClient.java:103)
   >    at java.security.AccessController.doPrivileged(Native Method)
   >    at org.elasticsearch.xpack.sql.client.HttpClient.post(HttpClient.java:102)
   >    at org.elasticsearch.xpack.sql.client.HttpClient.query(HttpClient.java:79)
   >    at org.elasticsearch.xpack.sql.jdbc.JdbcHttpClient.nextPage(JdbcHttpClient.java:72)
   >    at org.elasticsearch.xpack.sql.jdbc.DefaultCursor.next(DefaultCursor.java:44)
   >    at org.elasticsearch.xpack.sql.jdbc.JdbcResultSet.next(JdbcResultSet.java:113)
   >    at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.doAssertResultSetData(JdbcAssert.java:192)
   >    at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSetData(JdbcAssert.java:180)
   >    at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:82)
   >    at org.elasticsearch.xpack.sql.qa.jdbc.CsvSpecTestCase.assertResults(CsvSpecTestCase.java:55)
   >    at org.elasticsearch.xpack.sql.qa.jdbc.CsvSpecTestCase.doTest(CsvSpecTestCase.java:48)
   >    at org.elasticsearch.xpack.sql.qa.jdbc.SpecBaseIntegrationTestCase.test(SpecBaseIntegrationTestCase.java:90)
   >    at java.lang.Thread.run(Thread.java:748)
```

**Comment by matriv** [comment]
Tests muted in master and 7.x

**Comment by matriv** [comment]
Backported to `7.x` with 3844da318fb09afbb395bd410ddc4ed082e17f6d
