### ISSUE TITLE
Inline char filter preventing rolling upgrade from 5.x to 6.x

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#40815]
A user [reported the following exception](https://discuss.elastic.co/t/encountering-only-value-lists-are-allowed-in-serialized-settings-exception-after-upgrade-to-6-7-0-from-5-6-5/175254) preventing a node from starting in a rolling upgrade from 5.6.5 to 6.7.0:

```
[2019-04-03T12:04:06,926][ERROR][o.e.b.Bootstrap          ] [node-1] Exception
org.elasticsearch.ElasticsearchException: java.io.IOException: failed to read [id:1, file:/var/lib/elasticsearch/nodes/0/_state/global-1.st]
        at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:164) ~[elasticsearch-6.7.0.jar:6.7.0]
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:304) ~[elasticsearch-6.7.0.jar:6.7.0]
        at org.elasticsearch.gateway.MetaStateService.loadGlobalState(MetaStateService.java:112) ~[elasticsearch-6.7.0.jar:6.7.0]
        at org.elasticsearch.gateway.MetaStateService.loadFullState(MetaStateService.java:57) ~[elasticsearch-6.7.0.jar:6.7.0]
        at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:88) ~[elasticsearch-6.7.0.jar:6.7.0]
        at org.elasticsearch.node.Node.<init>(Node.java:499) ~[elasticsearch-6.7.0.jar:6.7.0]
        at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.7.0.jar:6.7.0]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.7.0.jar:6.7.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.7.0.jar:6.7.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) [elasticsearch-6.7.0.jar:6.7.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-6.7.0.jar:6.7.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-6.7.0.jar:6.7.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.7.0.jar:6.7.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.7.0.jar:6.7.0]
        at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.7.0.jar:6.7.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) [elasticsearch-6.7.0.jar:6.7.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.7.0.jar:6.7.0]
Caused by: java.io.IOException: failed to read [id:1, file:/var/lib/elasticsearch/nodes/0/_state/global-1.st]
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:298) ~[elasticsearch-6.7.0.jar:6.7.0]
        ... 15 more
Caused by: java.lang.IllegalStateException: only value lists are allowed in serialized settings
        at org.elasticsearch.common.settings.Settings.fromXContent(Settings.java:692) ~[elasticsearch-6.7.0.jar:6.7.0]
```

They provided the offending file and we discovered that there was an index template with an inline `char_filter`:

```
          'brand_replacement' => [
              'tokenizer' => 'brand_replacement',
              'filter' => ['trim', 'lowercase'],
              'char_filter' => [
                 [
                   'type' => 'pattern_replace',
                   'pattern' => '-',
                   'replacement' => ' '
                  ]
              ]
          ]
```

Indeed the error is thrown on encountering a `START_OBJECT` here in the metadata file (converted to pseudo-JSON):

```
"brand_replacement":{
  "filter":
    [
      "trim",
      "lowercase"
    ],
  "char_filter":[{
```

It seems from the reference manual that these inline char filters were supported in 2.4 but dropped in 5.0. I am presuming that this template came from a pre-5.0 upgrade but haven't tested the full upgrade path to verify this. I'm not too familiar with the history of this setting and can't see anything obvious in the breaking changes docs so I'm not sure where this should have been caught.

They reported that removing the offending template allowed the upgrade to proceed.

**Comment by jimczi** [comment]
> It seems from the reference manual that these inline char filters were supported in 2.4 but dropped in 5.0. I am presuming that this template came from a pre-5.0 upgrade but haven't tested the full upgrade path to verify this. I'm not too familiar with the history of this setting and can't see anything obvious in the breaking changes docs so I'm not sure where this should have been caught.

I don't think that we ever accepted an inline `char_filter` in a custom `analyzer`. This section should contain an array of strings that reference existing char filters. However in 2.x and 5.x we leniently accept this configuration and ignore the object entirely. The index creation succeeds even if I change the inline `char_filter` with a `type` that doesn't exists:
````
 'brand_replacement' => [
              'tokenizer' => 'brand_replacement',
              'filter' => ['trim', 'lowercase'],
              'char_filter' => [
                 [
                   'type' => 'shdgdjs',
                   'pattern' => '-',
                   'replacement' => ' '
                  ]
              ]
          ]
````

The leniency was removed in https://github.com/elastic/elasticsearch/pull/26739 where arrays inside settings are not allowed to contain objects. The error message could print the offending object but I don't think we should consider this issue as a bug.

**Comment by jimczi** [comment]
We discussed internally and since this format was never supported nor documented we've decided to not consider this issue as a bug. This is the first report in the 6x series so we don't think that this leniency affects a lot of users and if it were the fix in 6x should help users to not shoot themselves in the foot.
