### ISSUE TITLE
repository-gcs plugin not working: "java.lang.RuntimePermission" "accessDeclaredMembers"

### ISSUE THREAD

**Issue by vdamianchicon** [elastic/elasticsearch#40910]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
bash-4.4# bin/elasticsearch --version
Version: 6.4.2, Build: default/tar/04711c2/2018-09-26T13:34:09.098244Z, JVM: 1.8.0_201

**Plugins installed**: []
ES_PLUGINS_INSTALL="repository-gcs,discovery-gce"

**JVM version** (`java -version`):
bash-4.4# java -version
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (IcedTea 3.11.0) (Alpine 8.201.08-r1)
OpenJDK 64-Bit Server VM (build 25.201-b08, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
FROM alpine:3.9
cat /etc/alpine-release
3.9.2
x86_64 Linux

**Description of the problem including expected versus actual behavior**:
Impossible to create a snapshot repository
**Steps to reproduce**:

PUT /_snapshot/number1
{
  "type": "gcs",
  "settings": {
    "bucket": "elasticsnapshots"
  }
}

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

note: I also see this error via 
"Error attempting to create snapshot repository: Put https://mycluster-mynamespace.svc.cluster.local:9200/_snapshot/elasticsnapshots: http: server gave HTTP response to HTTPS client"

**Provide logs (if relevant)**:
Output

{
  "error": {
    "root_cause": [
      {
        "type": "blob_store_exception",
        "reason": "Unable to check if bucket [elasticsnapshots] exists"
      }
    ],
    "type": "repository_exception",
    "reason": "[number1] cannot create blob store",
    "caused_by": {
      "type": "blob_store_exception",
      "reason": "Unable to check if bucket [elasticsnapshots] exists",
      "caused_by": {
        "type": "security_exception",
        "reason": "access denied (\"java.lang.RuntimePermission\" \"accessDeclaredMembers\")"
      }
    }
  },
  "status": 500
}

**Comment by jasontedor** [comment]
Do you have a full stacktrace from the Elasticsearch logs that we could use to debug what is happening here?

**Comment by vdamianchicon** [comment]
stacktrace from the Elasticsearch logs
`
2019-04-05 14:37:02.823 EDT
org.elasticsearch.transport.RemoteTransportException: [bb2b13c9-c902-4444-a63b-8a880d796218][xx.x.xx.xxx:9300][cluster:admin/repository/put] Caused by: org.elasticsearch.repositories.RepositoryException: [gcs] cannot create blob store at org.elasticsearch.repositories.blobstore.BlobStoreRepository.blobStore(BlobStoreRepository.java:336) ~[elasticsearch-6.4.2.jar:6.4.2] at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:635) ~[elasticsearch-6.4.2.jar:6.4.2] at org.elasticsearch.repositories.RepositoriesService.lambda$verifyRepository$2(RepositoriesService.java:218) ~[elasticsearch-6.4.2.jar:6.4.2] at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[elasticsearch-6.4.2.jar:6.4.2] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_201] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_201] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201] Caused by: org.elasticsearch.common.blobstore.BlobStoreException: Unable to check if bucket [elasticsnapshots] exists at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.doesBucketExist(GoogleCloudStorageBlobStore.java:111) ~[?:?] at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.<init>(GoogleCloudStorageBlobStore.java:77) ~[?:?] at org.elasticsearch.repositories.gcs.GoogleCloudStorageRepository.createBlobStore(GoogleCloudStorageRepository.java:135) ~[?:?] at org.elasticsearch.repositories.gcs.GoogleCloudStorageRepository.createBlobStore(GoogleCloudStorageRepository.java:46) ~[?:?] at org.elasticsearch.repositories.blobstore.BlobStoreRepository.blobStore(BlobStoreRepository.java:332) ~[elasticsearch-6.4.2.jar:6.4.2] at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:635) ~[elasticsearch-6.4.2.jar:6.4.2] at org.elasticsearch.repositories.RepositoriesService.lambda$verifyRepository$2(RepositoriesService.java:218) ~[elasticsearch-6.4.2.jar:6.4.2] at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[elasticsearch-6.4.2.jar:6.4.2] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_201] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_201] at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_201] Caused by: java.lang.SecurityException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers") at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_201] at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_201] at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_201] at java.lang.Class.checkMemberAccess(Class.java:2348) ~[?:1.8.0_201] at java.lang.Class.getDeclaredFields(Class.java:1915) ~[?:1.8.0_201] at com.google.api.client.util.ClassInfo.<init>(ClassInfo.java:171) ~[?:?] at com.google.api.client.util.ClassInfo.of(ClassInfo.java:90) ~[?:?] at com.google.api.client.util.ClassInfo.<init>(ClassInfo.java:193) ~[?:?] at com.google.api.client.util.ClassInfo.of(ClassInfo.java:90) ~[?:?] at com.google.api.client.util.ClassInfo.<init>(ClassInfo.java:193) ~[?:?] at com.google.api.client.util.ClassInfo.of(ClassInfo.java:90) ~[?:?] at com.google.api.client.util.GenericData.<init>(GenericData.java:79) ~[?:?] at com.google.api.client.util.GenericData.<init>(GenericData.java:61) ~[?:?] at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:157) ~[?:?] at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:142) ~[?:?] at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:114) ~[?:?] at com.google.cloud.ServiceOptions.getAppEngineProjectIdFromMetadataServer(ServiceOptions.java:446) ~[?:?] at com.google.cloud.ServiceOptions.getAppEngineProjectId(ServiceOptions.java:425) ~[?:?] at com.google.cloud.ServiceOptions.getDefaultProjectId(ServiceOptions.java:333) ~[?:?] at com.google.cloud.ServiceOptions.getDefaultProject(ServiceOptions.java:311) ~[?:?] at com.google.cloud.ServiceOptions.<init>(ServiceOptions.java:264) ~[?:?] at com.google.cloud.storage.StorageOptions.<init>(StorageOptions.java:83) ~[?:?] at com.google.cloud.storage.StorageOptions.<init>(StorageOptions.java:31) ~[?:?] at com.google.cloud.storage.StorageOptions$Builder.build(StorageOptions.java:78) ~[?:?] at org.elasticsearch.repositories.gcs.GoogleCloudStorageService.createClient(GoogleCloudStorageService.java:211) ~[?:?] at org.elasticsearch.repositories.gcs.GoogleCloudStorageService.lambda$refreshAndClearCache$0(GoogleCloudStorageService.java:89) ~[?:?] at org.elasticsearch.common.util.LazyInitializable.maybeCompute(LazyInitializable.java:103) ~[elasticsearch-6.4.2.jar:6.4.2] at org.elasticsearch.common.util.LazyInitializable.getOrCompute(LazyInitializable.java:81) ~[elasticsearch-6.4.2.jar:6.4.2] at org.elasticsearch.repositories.gcs.GoogleCloudStorageService.client(GoogleCloudStorageService.java:114) ~[?:?] at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.client(GoogleCloudStorageBlobStore.java:83) ~[?:?] at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.lambda$doesBucketExist$0(GoogleCloudStorageBlobStore.java:108) ~[?:?] at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201] at org.elasticsearch.repositories.gcs.SocketAccess.doPrivilegedIOException(SocketAccess.java:44) ~[?:?] at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.doesBucketExist(GoogleCloudStorageBlobStore.java:108) ~[?:?] at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.<init>(GoogleCloudStorageBlobStore.java:77) ~[?:?] at org.elasticsearch.repositories.gcs.GoogleCloudStorageRepository.createBlobStore(GoogleCloudStorageRepository.java:135) ~[?:?] at org.elasticsearch.repositories.gcs.GoogleCloudStorageRepository.createBlobStore(GoogleCloudStorageRepository.java:46) ~[?:?] at org.elasticsearch.repositories.blobstore.BlobStoreRepository.blobStore(BlobStoreRepository.java:332) ~[elasticsearch-6.4.2.jar:6.4.2] at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:635) ~[elasticsearch-6.4.2.jar:6.4.2] at org.elasticsearch.repositories.RepositoriesService.lambda$verifyRepository$2(RepositoriesService.java:218) ~[elasticsearch-6.4.2.jar:6.4.2] at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[elasticsearch-6.4.2.jar:6.4.2] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_201] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_201] at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_201]
 
Expand all | Collapse all {
 insertId:  "1ha3yeog1h9krid"  
 labels: {
  compute.googleapis.com/resource_name:  "gke-mycluster-secure-nodes-xxxxxxxx-f6jr"   
  container.googleapis.com/namespace_name:  "mynamespace"   
  container.googleapis.com/pod_name:  "mypod-xxxxxxxxxx-qb59m"   
  container.googleapis.com/stream:  "stdout"   
 }
 logName:  "projects/myproject/logs/mypod"  
 receiveTimestamp:  "2019-04-05T18:37:08.741499662Z"  
 resource: {
  labels: {
   cluster_name:  "mycluster"    
   container_name:  "mypod"    
   instance_id:  "xxxxxxxxxxxxxxxxxxx"    
   namespace_id:  "mynamespace"    
   pod_id:  "mypod-xxxxxxxxxx-qb59m"    
   project_id:  "myproject"    
   zone:  "myzone"    
  }
  type:  "container"   
 }
 severity:  "INFO"  
 textPayload:  "org.elasticsearch.transport.RemoteTransportException: [bb2b13c9-c902-4444-a63b-8a880d796218][xx.x.xx.xxx:9300][cluster:admin/repository/put]
Caused by: org.elasticsearch.repositories.RepositoryException: [gcs] cannot create blob store
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.blobStore(BlobStoreRepository.java:336) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:635) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.repositories.RepositoriesService.lambda$verifyRepository$2(RepositoriesService.java:218) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[elasticsearch-6.4.2.jar:6.4.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: org.elasticsearch.common.blobstore.BlobStoreException: Unable to check if bucket [elasticsnapshots] exists
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.doesBucketExist(GoogleCloudStorageBlobStore.java:111) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.<init>(GoogleCloudStorageBlobStore.java:77) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageRepository.createBlobStore(GoogleCloudStorageRepository.java:135) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageRepository.createBlobStore(GoogleCloudStorageRepository.java:46) ~[?:?]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.blobStore(BlobStoreRepository.java:332) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:635) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.repositories.RepositoriesService.lambda$verifyRepository$2(RepositoriesService.java:218) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[elasticsearch-6.4.2.jar:6.4.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_201]
Caused by: java.lang.SecurityException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_201]
	at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_201]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_201]
	at java.lang.Class.checkMemberAccess(Class.java:2348) ~[?:1.8.0_201]
	at java.lang.Class.getDeclaredFields(Class.java:1915) ~[?:1.8.0_201]
	at com.google.api.client.util.ClassInfo.<init>(ClassInfo.java:171) ~[?:?]
	at com.google.api.client.util.ClassInfo.of(ClassInfo.java:90) ~[?:?]
	at com.google.api.client.util.ClassInfo.<init>(ClassInfo.java:193) ~[?:?]
	at com.google.api.client.util.ClassInfo.of(ClassInfo.java:90) ~[?:?]
	at com.google.api.client.util.ClassInfo.<init>(ClassInfo.java:193) ~[?:?]
	at com.google.api.client.util.ClassInfo.of(ClassInfo.java:90) ~[?:?]
	at com.google.api.client.util.GenericData.<init>(GenericData.java:79) ~[?:?]
	at com.google.api.client.util.GenericData.<init>(GenericData.java:61) ~[?:?]
	at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:157) ~[?:?]
	at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:142) ~[?:?]
	at com.google.api.client.http.GenericUrl.<init>(GenericUrl.java:114) ~[?:?]
	at com.google.cloud.ServiceOptions.getAppEngineProjectIdFromMetadataServer(ServiceOptions.java:446) ~[?:?]
	at com.google.cloud.ServiceOptions.getAppEngineProjectId(ServiceOptions.java:425) ~[?:?]
	at com.google.cloud.ServiceOptions.getDefaultProjectId(ServiceOptions.java:333) ~[?:?]
	at com.google.cloud.ServiceOptions.getDefaultProject(ServiceOptions.java:311) ~[?:?]
	at com.google.cloud.ServiceOptions.<init>(ServiceOptions.java:264) ~[?:?]
	at com.google.cloud.storage.StorageOptions.<init>(StorageOptions.java:83) ~[?:?]
	at com.google.cloud.storage.StorageOptions.<init>(StorageOptions.java:31) ~[?:?]
	at com.google.cloud.storage.StorageOptions$Builder.build(StorageOptions.java:78) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageService.createClient(GoogleCloudStorageService.java:211) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageService.lambda$refreshAndClearCache$0(GoogleCloudStorageService.java:89) ~[?:?]
	at org.elasticsearch.common.util.LazyInitializable.maybeCompute(LazyInitializable.java:103) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.common.util.LazyInitializable.getOrCompute(LazyInitializable.java:81) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageService.client(GoogleCloudStorageService.java:114) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.client(GoogleCloudStorageBlobStore.java:83) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.lambda$doesBucketExist$0(GoogleCloudStorageBlobStore.java:108) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at org.elasticsearch.repositories.gcs.SocketAccess.doPrivilegedIOException(SocketAccess.java:44) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.doesBucketExist(GoogleCloudStorageBlobStore.java:108) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.<init>(GoogleCloudStorageBlobStore.java:77) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageRepository.createBlobStore(GoogleCloudStorageRepository.java:135) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageRepository.createBlobStore(GoogleCloudStorageRepository.java:46) ~[?:?]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.blobStore(BlobStoreRepository.java:332) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:635) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.repositories.RepositoriesService.lambda$verifyRepository$2(RepositoriesService.java:218) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[elasticsearch-6.4.2.jar:6.4.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_201]
"  
 timestamp:  "2019-04-05T18:37:02.823681497Z"  
}

........
........

",2i850ag1234k0p,container,myzone,mycluster-xxxxxxxxxx-qb59m,myproject,mycluster,clusterlongname-cluster,mynamespace,8690991249069567184,2019-04-05T18:23:04.873015693Z,INFO,gke-mycluster-secure-nodes-0b6c2c2e-f6jr,es-clientmyproject-cluster-xxxxxxxxxx-qb59m,stdout,mynamespace,projects/myproject/logs/es-clientmyproject-cluster,2019-04-05T18:23:27.110430045Z
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
",2i850ag1234k0q,container,myzone,mycluster-xxxxxxxxxx-qb59m,myproject,mycluster,clusterlongname-cluster,mynamespace,8690991249069567184,2019-04-05T18:23:15.375214393Z,INFO,gke-mycluster-secure-nodes-0b6c2c2e-f6jr,es-clientmyproject-cluster-xxxxxxxxxx-qb59m,stdout,mynamespace,projects/myproject/logs/es-clientmyproject-cluster,2019-04-05T18:23:27.110430045Z
"@     WARNING: plugin requires additional permissions     @
",2i850ag1234k0r,container,myzone,mycluster-xxxxxxxxxx-qb59m,myproject,mycluster,clusterlongname-cluster,mynamespace,8690991249069567184,2019-04-05T18:23:15.375247963Z,INFO,gke-mycluster-secure-nodes-0b6c2c2e-f6jr,es-clientmyproject-cluster-xxxxxxxxxx-qb59m,stdout,mynamespace,projects/myproject/logs/es-clientmyproject-cluster,2019-04-05T18:23:27.110430045Z
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
",2i850ag1234k0s,container,myzone,mycluster-xxxxxxxxxx-qb59m,myproject,mycluster,clusterlongname-cluster,mynamespace,8690991249069567184,2019-04-05T18:23:15.375256195Z,INFO,gke-mycluster-secure-nodes-0b6c2c2e-f6jr,es-clientmyproject-cluster-xxxxxxxxxx-qb59m,stdout,mynamespace,projects/myproject/logs/es-clientmyproject-cluster,2019-04-05T18:23:27.110430045Z
"* java.lang.RuntimePermission accessDeclaredMembers
",2i850ag1234k0t,container,myzone,mycluster-xxxxxxxxxx-qb59m,myproject,mycluster,clusterlongname-cluster,mynamespace,8690991249069567184,2019-04-05T18:23:15.375262036Z,INFO,gke-mycluster-secure-nodes-0b6c2c2e-f6jr,es-clientmyproject-cluster-xxxxxxxxxx-qb59m,stdout,mynamespace,projects/myproject/logs/es-clientmyproject-cluster,2019-04-05T18:23:27.110430045Z
"* java.lang.RuntimePermission setFactory
",2i850ag1234k0u,container,myzone,mycluster-xxxxxxxxxx-qb59m,myproject,mycluster,clusterlongname-cluster,mynamespace,8690991249069567184,2019-04-05T18:23:15.375267235Z,INFO,gke-mycluster-secure-nodes-0b6c2c2e-f6jr,es-clientmyproject-cluster-xxxxxxxxxx-qb59m,stdout,mynamespace,projects/myproject/logs/es-clientmyproject-cluster,2019-04-05T18:23:27.110430045Z
"* java.lang.reflect.ReflectPermission suppressAccessChecks
",2i850ag1234k0v,container,myzone,mycluster-xxxxxxxxxx-qb59m,myproject,mycluster,clusterlongname-cluster,mynamespace,8690991249069567184,2019-04-05T18:23:15.375272590Z,INFO,gke-mycluster-secure-nodes-0b6c2c2e-f6jr,es-clientmyproject-cluster-xxxxxxxxxx-qb59m,stdout,mynamespace,projects/myproject/logs/es-clientmyproject-cluster,2019-04-05T18:23:27.110430045Z
"* java.net.SocketPermission * connect,resolve
",2i850ag1234k0w,container,myzone,mycluster-xxxxxxxxxx-qb59m,myproject,mycluster,clusterlongname-cluster,mynamespace,8690991249069567184,2019-04-05T18:23:15.375277902Z,INFO,gke-mycluster-secure-nodes-0b6c2c2e-f6jr,es-clientmyproject-cluster-xxxxxxxxxx-qb59m,stdout,mynamespace,projects/myproject/logs/es-clientmyproject-cluster,2019-04-05T18:23:27.110430045Z
"See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
",2i850ag1234k0x,container,myzone,mycluster-xxxxxxxxxx-qb59m,myproject,mycluster,clusterlongname-cluster,mynamespace,8690991249069567184,2019-04-05T18:23:15.375283103Z,INFO,gke-mycluster-secure-nodes-0b6c2c2e-f6jr,es-clientmyproject-cluster-xxxxxxxxxx-qb59m,stdout,mynamespace,projects/myproject/logs/es-clientmyproject-cluster,2019-04-05T18:23:27.110430045Z
"for descriptions of what these permissions allow and the associated risks.
",2i850ag1234k0y,container,myzone,mycluster-xxxxxxxxxx-qb59m,myproject,mycluster,clusterlongname-cluster,mynamespace,8690991249069567184,2019-04-05T18:23:15.375288522Z,INFO,gke-mycluster-secure-nodes-0b6c2c2e-f6jr,es-clientmyproject-cluster-xxxxxxxxxx-qb59m,stdout,mynamespace,projects/myproject/logs/es-clientmyproject-cluster,2019-04-05T18:23:27.110430045Z
"-> Installed repository-gcs
",2i850ag1234k0z,container,myzone,mycluster-xxxxxxxxxx-qb59m,myproject,mycluster,clusterlongname-cluster,mynamespace,8690991249069567184,2019-04-05T18:23:15.375294330Z,INFO,gke-mycluster-secure-nodes-0b6c2c2e-f6jr,es-clientmyproject-cluster-xxxxxxxxxx-qb59m,stdout,mynamespace,projects/myproject/logs/es-clientmyproject-cluster,2019-04-05T18:23:27.110430045Z
"-> Downloading discovery-gce from elastic
",o5jse0g1fe7q00,container,myzone,mycluster-xxxxxxxxxx-qb59m,myproject,mycluster,clusterlongname-cluster,mynamespace,8690991249069567184,2019-04-05T18:23:30.508009788Z,INFO,gke-mycluster-secure-nodes-0b6c2c2e-f6jr,es-clientmyproject-cluster-xxxxxxxxxx-qb59m,stdout,mynamespace,projects/myproject/logs/es-clientmyproject-cluster,2019-04-05T18:23:35.194760426Z
`

**Comment by vdamianchicon** [comment]
Oops closed by error
just wonder if there is any other data need it to figure this one out

**Comment by vdamianchicon** [comment]
can this issue be related?
#41018

**Comment by vdamianchicon** [comment]
This issue was solved by reloading the x-pax security settings as follows:
POST _nodes/reload_secure_settings

**Comment by thodquach** [comment]
Tks @vdamianchicon ,
Your comment have me solve my problem :D
