### ISSUE TITLE
AsyncTwoPhaseIndexerTests testStateMachine CI failures

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#40946]
Several failures with the error:

```
java.lang.AssertionError: 
Expected: <6>
     but: was <5>
	at __randomizedtesting.SeedInfo.seed([F2BBC735F05D6D51:9E12BB2E88D0733F]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.core.indexing.AsyncTwoPhaseIndexerTests.testStateMachine(AsyncTwoPhaseIndexerTests.java:224)
```

Does _not_ reproduce:

```
./gradlew :x-pack:plugin:core:unitTest \
  -Dtests.seed=F2BBC735F05D6D51 \
  -Dtests.class=org.elasticsearch.xpack.core.indexing.AsyncTwoPhaseIndexerTests \
  -Dtests.method="testStateMachine" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-ZM \
  -Dtests.timezone=Atlantic/Reykjavik \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos-6/320/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=ubuntu-18.04&&immutable/95/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=ubuntu-18.04&&immutable/94/console

**Comment by davidkyle** [comment]
Muted in master 80c7c0eba6df03e60729552f4adbaa8eafb28896 and 7.x fb5d7cf237bdccfba6a00f6b3128772bdd3f4134
