### ISSUE TITLE
CreateIndexIT testCreateAndDeleteIndexConcurrently CI failures 

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#40951]
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=4657, name=elasticsearch[node_td3][write][T#1], state=RUNNABLE, group=TGRP-CreateIndexIT]
Caused by: java.lang.AssertionError: All exceptions should be handled by #executeBulkItemRequest
	at __randomizedtesting.SeedInfo.seed([EE67EAA70CCFC83F]:0)
	at org.elasticsearch.action.bulk.TransportShardBulkAction$2.onFailure(TransportShardBulkAction.java:173)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:197)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:116)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:77)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:927)
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:104)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.runWithPrimaryShardReference(TransportReplicationAction.java:364)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$doRun$0(TransportReplicationAction.java:311)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:269)
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:236)
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2513)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryOperationPermit(TransportReplicationAction.java:865)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:310)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.handlePrimaryRequest(TransportReplicationAction.java:273)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63)
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:703)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:747)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

The suite fails with a timeout exception

```
java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).
	at __randomizedtesting.SeedInfo.seed([EE67EAA70CCFC83F]:0)
```

Does not reproduce
```
 ./gradlew :server:integTest \
  -Dtests.seed=EE67EAA70CCFC83F \
  -Dtests.class=org.elasticsearch.action.admin.indices.create.CreateIndexIT \
  -Dtests.method="testCreateAndDeleteIndexConcurrently" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Latn \
  -Dtests.timezone=America/Argentina/Salta \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

Many failures in the last 24 hours:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/3002/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/654/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+artifactory/266/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/4691/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+internalClusterTest/4685/console
...

**Comment by davidkyle** [comment]
Muted on master 861a7f015331028923373f04a9d74a1de6a71460

**Comment by original-brownbear** [comment]
this should be fixed by #40947 now, will unmute
