### ISSUE TITLE
EnableAllocationShortCircuitTests CI Failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#40964]
One of these 

```
   > Throwable #1: java.lang.IllegalArgumentException: Illegal rebalance.enable value [NEW_PRIMARIES]
   >    at __randomizedtesting.SeedInfo.seed([4AA5D27894DF4C68:6923462EACD9DBE1]:0)
   >    at org.elasticsearch.cluster.routing.allocation.decider.EnableAllocationDecider$Rebalance.parse(EnableAllocationDecider.java:282)
   >    at org.elasticsearch.common.settings.Setting.get(Setting.java:412)
   >    at org.elasticsearch.common.settings.Setting.get(Setting.java:406)
   >    at org.elasticsearch.cluster.routing.allocation.decider.EnableAllocationDecider.canRebalance(EnableAllocationDecider.java:153)
   >    at org.elasticsearch.cluster.routing.allocation.decider.AllocationDeciders.canRebalance(AllocationDeciders.java:192)
   >    at org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator$Balancer.balance(BalancedShardsAllocator.java:324)
   >    at org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator.allocate(BalancedShardsAllocator.java:124)
   >    at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:413)
   >    at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:378)
   >    at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:361)
   >    at org.elasticsearch.cluster.routing.allocation.decider.EnableAllocationShortCircuitTests.testRebalancingAttemptedIfDisabledButOverridenOnSpecificIndices(EnableAllocationShortCircuitTests.java:140)
```

*Reproduces* 

```
./gradlew :server:unitTest \
  -Dtests.seed=4AA5D27894DF4C68 \
  -Dtests.class=org.elasticsearch.cluster.routing.allocation.decider.EnableAllocationShortCircuitTests \
  -Dtests.method="testRebalancingAttemptedIfDisabledButOverridenOnSpecificIndices" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-TT \
  -Dtests.timezone=Africa/Niamey \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/3014/console

**Comment by davidkyle** [comment]
Muted on master 2ae9e2731aa960f17b73402769f81eae2aa77442

**Comment by DaveCTurner** [comment]
My daft mistake, sorry, I have reverted the commit introducing this change on all affected branches and will try again shortly.

**Comment by DaveCTurner** [comment]
Relates #40942
