### ISSUE TITLE
CI Failure: DataFrameGetAndGetStatsIT testGetPersistedStatsWithoutTask

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#40963]
```
Expected: a value greater than <0>
     but: <0> was equal to <0>
	at __randomizedtesting.SeedInfo.seed([565E9E23D6E0611E:F4F08DAE1E49B812]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.dataframe.integration.DataFrameGetAndGetStatsIT.testGetPersistedStatsWithoutTask(DataFrameGetAndGetStatsIT.java:133)
```

Reproduce: 
```
./gradlew :x-pack:plugin:data-frame:qa:single-node-tests:integTestRunner \
  -Dtests.seed=565E9E23D6E0611E \
  -Dtests.class=org.elasticsearch.xpack.dataframe.integration.DataFrameGetAndGetStatsIT \
  -Dtests.method="testGetPersistedStatsWithoutTask" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-AE \
  -Dtests.timezone=Europe/Bratislava \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-darwin-compatibility/95/console

**Comment by jtibshirani** [comment]
This failed again with the same error, I'm planning to mute the test.

**Comment by benwtrent** [comment]
This seems like the `search_time_in_ms` is actually 0 for the stats (super fast searching....). That check could actually be removed, as we only care about there actually BEING stats, not that there are specific values.

I will open a pr removing the `search_time_in_ms` check. `documents_processed > 0` is a good enough check for this test.
