### ISSUE TITLE
GlobalCheckpointListenersTests testConcurrency CI Failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#40970]
Failed on 7.0 https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+multijob-unix-compatibility/os=amazon/94/console

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.elasticsearch.index.shard.GlobalCheckpointListenersTests.testConcurrency(GlobalCheckpointListenersTests.java:497)
```

and 

```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=1900, name=elasticsearch[scheduler][T#1], state=RUNNABLE, group=TGRP-GlobalCheckpointListenersTests]
Caused by: java.util.concurrent.RejectedExecutionException: Task org.elasticsearch.index.shard.GlobalCheckpointListeners$$Lambda$4255/1497499150@5d7d99fe rejected from java.util.concurrent.ThreadPoolExecutor@187f0c35[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 3]
	at __randomizedtesting.SeedInfo.seed([B5091DC2B65D1ED8]:0)
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at org.elasticsearch.index.shard.GlobalCheckpointListeners.lambda$add$3(GlobalCheckpointListeners.java:143)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExec
``` 

Does not reproduce
```
 ./gradlew :server:unitTest \
  -Dtests.seed=B5091DC2B65D1ED8 \
  -Dtests.class=org.elasticsearch.index.shard.GlobalCheckpointListenersTests \
  -Dtests.method="testConcurrency" \
  -Dtests.security.manager=true \
  -Dtests.locale=tr \
  -Dtests.timezone=Atlantic/South_Georgia \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

**Comment by jasontedor** [comment]
Closed by 321f93c4f95255536ae85cd92f9a15a79e48674e
