### ISSUE TITLE
org.elasticsearch.xpack.sql.qa.single_node.Jdbc*CsvSpecIT failing reliably

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#40994]
The failures look like:

```
2> org.junit.ComparisonFailure: Different result for column [first_name], entry [2] expected:<[Kenroku]> but was:<[Lillian]>
        at __randomizedtesting.SeedInfo.seed([8A53D22B1133691A:207EDF1BFCF04E2]:0)
        at org.elasticsearch.xpack.sql.qa.single_node.JdbcDocCsvSpecIT.docs.testFilterToday(docs.csv-spec:2415)
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.doAssertResultSetData(JdbcAssert.java:261)
        at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSetData(JdbcAssert.java:180)
        at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:82)
        at org.elasticsearch.xpack.sql.qa.single_node.JdbcDocCsvSpecIT.assertResults(JdbcDocCsvSpecIT.java:72)
        at org.elasticsearch.xpack.sql.qa.single_node.JdbcDocCsvSpecIT.doTest(JdbcDocCsvSpecIT.java:87)
```

The failures are in `test {docs.testFilterToday}` and `test {date.testCurrentDateFilter}`. I simply muted the entire suites of `JdbcCsvSpecIT` and `JdbcDocCsvSpecIT`. The seed `8A53D22B1133691A` reproduces these failures reliably.

**Comment by jasontedor** [comment]
Muted in master in b80e279bbf69d19317a1f99f9ace9506586d5d73.

**Comment by jasontedor** [comment]
I opted for more targeted muting in 529eda39ddd41156aacbc9882586081ae3a192e0.

**Comment by mark-vieira** [comment]
I've cherry picked this to [`7.x`](https://github.com/elastic/elasticsearch/commit/64c98c632a20902eeeeb4e36c762954b66b81cfd) and [`7.0`](https://github.com/elastic/elasticsearch/commit/639bfe6025337e04f5b070fbcff16549374b0232) as well.

**Comment by DaveCTurner** [comment]
Cherry-picked 639bfe6 to 6.7 as 0a88e7f0ebb since https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+intake/528/ failed for similar reasons too.
