### ISSUE TITLE
su-exec elasticsearch bin/elasticsearch-keystore list:  java.nio.file.AccessDeniedException

### ISSUE THREAD

**Issue by vdamianchicon** [elastic/elasticsearch#41018]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 6.4.2, Build: default/tar/04711c2/2018-09-26T13:34:09.098244Z, JVM: 1.8.0_201
**Plugins installed**: []
repository-gcs,discovery-gce
**JVM version** (`java -version`):
bash-4.4# java -version
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (IcedTea 3.11.0) (Alpine 8.201.08-r1)
OpenJDK 64-Bit Server VM (build 25.201-b08, mixed mode)
**OS version** (`uname -a` if on a Unix-like system):
FROM alpine:3.9
cat /etc/alpine-release
3.9.2
x86_64 Linux
**Description of the problem including expected versus actual behavior**:
su-exec elasticsearch bin/elasticsearch-keystore list
Exception in thread "main" java.nio.file.AccessDeniedException: /elasticsearch/config/elasticsearch.keystore
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at org.apache.lucene.store.SimpleFSDirectory.openInput(SimpleFSDirectory.java:77)
	at org.elasticsearch.common.settings.KeyStoreWrapper.load(KeyStoreWrapper.java:215)
	at org.elasticsearch.common.settings.ListKeyStoreCommand.execute(ListKeyStoreCommand.java:45)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:40)

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. per https://www.elastic.co/guide/en/elasticsearch/reference/6.4/secure-settings.html
     add gcs service account credentials file
 2. execute su-exec elasticsearch bin/elasticsearch-keystore list
 3. 

**Provide logs (if relevant)**:
su-exec elasticsearch bin/elasticsearch-keystore list
Exception in thread "main" java.nio.file.AccessDeniedException: /elasticsearch/config/elasticsearch.keystore
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at org.apache.lucene.store.SimpleFSDirectory.openInput(SimpleFSDirectory.java:77)
	at org.elasticsearch.common.settings.KeyStoreWrapper.load(KeyStoreWrapper.java:215)
	at org.elasticsearch.common.settings.ListKeyStoreCommand.execute(ListKeyStoreCommand.java:45)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:40)

**Comment by vdamianchicon** [comment]
changingpermissions seem to solve this issue
-rw-rw----    1 elastics root           207 Apr  9 15:53 elasticsearch.keystore
keystore.seed

**Comment by vdamianchicon** [comment]
oops closed this one by error

**Comment by vdamianchicon** [comment]
This issue was resolved by changing permissions on the elasticsearch home directory as follows:
chown -R elasticsearch:elasticsearch /elasticsearch
