### ISSUE TITLE
Docs build failing on 6.3 due to missing Java home.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#41027]
Just today the docs build failed for 6.0, 6.2, and 6.3 with the following error:

```
java.lang.IllegalArgumentException: Value '' given for org.gradle.java.home Gradle property is invalid (Java home supplied is invalid)
	at org.gradle.internal.buildoption.Origin$GradlePropertyOrigin.handleInvalidValue(Origin.java:58)
	at org.gradle.launcher.daemon.configuration.DaemonBuildOptions$JavaHomeOption.applyTo(DaemonBuildOptions.java:134)
	at org.gradle.launcher.daemon.configuration.DaemonBuildOptions$JavaHomeOption.applyTo(DaemonBuildOptions.java:123)
	at org.gradle.internal.buildoption.StringBuildOption.applyFromProperty(StringBuildOption.java:44)
```

Although we don't commit docs changes as frequently to these branches, it may be worth tracking down what is going wrong.

Link to example build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+docs-check/55/console

**Comment by rjernst** [comment]
This is an infra issue. I've moved this to their tracking.
