### ISSUE TITLE
DataFrameTransformCheckpointTests#testGetBehind fails reproducibly

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#41076]
Master intake: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/3067/console

Reproduces locally:
```
./gradlew :x-pack:plugin:data-frame:test --tests "org.elasticsearch.xpack.dataframe.transforms.DataFrameTransformCheckpointTests.testGetBehind" \
  -Dtests.seed=828273867F1FD6F7 \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-DZ \
  -Dtests.timezone=Pacific/Niue \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

```
java.lang.AssertionError: expected:<1530> but was:<1360>
        at __randomizedtesting.SeedInfo.seed([828273867F1FD6F7:48EEAF779A7DA083]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.elasticsearch.xpack.dataframe.transforms.DataFrameTransformCheckpointTests.testGetBehind(DataFrameTransformCheckpointTests.java:131)
```

**Comment by cbuescher** [comment]
Seems to fail with other random seeds as well, some pass but with few iterations I was getting it to fail again. Will mute.

**Comment by cbuescher** [comment]
Muted with https://github.com/elastic/elasticsearch/commit/78e5af5fff734176f4c270f740733d8d0067f172 on master. Will need to check if other branches are affected.

**Comment by cbuescher** [comment]
Muted on 7.x with d00d3f4afa18b3e0dc7029328d292f5a84e1ab32
