### ISSUE TITLE
SQL: Failures in JdbcDocCsvSpecIT docs.testFilterToday & testCurrentDateFilter

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#41080]
Failures on master intake: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/3066/console

For some reason I find it hard to reproduce these tests locally:
```
./gradlew :x-pack:plugin:sql:qa:single-node:integTestRunner \
  -Dtests.seed=2393ED4A20BE58C2 \
  -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcDocCsvSpecIT \
  -Dtests.method="test {docs.testFilterToday}" \
  -Dtests.security.manager=true \
  -Dtests.locale=th \
  -Dtests.timezone=SystemV/YST9YDT \
  -Dcompiler.java=12 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :x-pack:plugin:sql:qa:single-node:integTestRunner \
  -Dtests.seed=2393ED4A20BE58C2 \
  -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcCsvSpecIT \
  -Dtests.method="test {date.testCurrentDateFilter}" \
  -Dtests.security.manager=true \
  -Dtests.locale=sq-AL \
  -Dtests.timezone=America/Jujuy \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

```
org.junit.ComparisonFailure: Different result for column [first_name], entry [2] expected:<[Kenroku]> but was:<[Lillian]>
	at __randomizedtesting.SeedInfo.seed([2393ED4A20BE58C2:ABC7D2908E42353A]:0)
	at org.elasticsearch.xpack.sql.qa.single_node.JdbcDocCsvSpecIT.docs.testFilterToday(docs.csv-spec:2415)
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.doAssertResultSetData(JdbcAssert.java:261)
	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSetData(JdbcAssert.java:180)
	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:82)
	at org.elasticsearch.xpack.sql.qa.single_node.JdbcDocCsvSpecIT.assertResults(JdbcDocCsvSpecIT.java:72)
	at org.elasticsearch.xpack.sql.qa.single_node.JdbcDocCsvSpecIT.doTest(JdbcDocCsvSpecIT.java:87)
```
```
org.junit.ComparisonFailure: Different result for column [first_name], entry [2] expected:<[Kenroku]> but was:<[Lillian]>
	at __randomizedtesting.SeedInfo.seed([2393ED4A20BE58C2:ABC7D2908E42353A]:0)
	at org.elasticsearch.xpack.sql.qa.single_node.JdbcCsvSpecIT.date.testCurrentDateFilter(date.csv-spec:53)
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.doAssertResultSetData(JdbcAssert.java:261)
	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSetData(JdbcAssert.java:180)
	at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:82)
	at org.elasticsearch.xpack.sql.qa.jdbc.CsvSpecTestCase.assertResults(CsvSpecTestCase.java:59)
	at org.elasticsearch.xpack.sql.qa.jdbc.CsvSpecTestCase.executeAndAssert(CsvSpecTestCase.java:66)
	at org.elasticsearch.xpack.sql.qa.jdbc.CsvSpecTestCase.doTest(CsvSpecTestCase.java:51)
```

I though these were muted but apparently they aren't. Could somebody from the SQL team take a look if this tests fail frequently and mute in such case?

**Comment by astefan** [comment]
@cbuescher these failures should be fixed by now with https://github.com/elastic/elasticsearch/pull/40999. This could explain why you cannot repro locally.

**Comment by cbuescher** [comment]
Whats weird is this build was on commit 51b9d5ee3a4bab5e3187f5be52f9b0d8184e7963 which seems really old, but the intake build just finished now and landed in my inbox.

**Comment by cbuescher** [comment]
Got an explanation for that by @atorok, closing
