### ISSUE TITLE
SQL: Interval arithmetics failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#41200]
```
sql> SELECT CONVERT(TRUNCATE((-1 * (DAYOFYEAR(date2) - 1)),0), SQL_BIGINT) * INTERVAL '1' DAY from calcs;
Server error [Server encountered an error [A number is required; received +1 00:00:00.0]. [SqlIllegalArgumentException[A number is required; received +1 00:00:00.0]
        at org.elasticsearch.xpack.sql.expression.predicate.operator.arithmetic.BinaryArithmeticProcessor.doProcess(BinaryArithmeticProcessor.java:173)
        at org.elasticsearch.xpack.sql.expression.gen.processor.BinaryProcessor.process(BinaryProcessor.java:50)
        at org.elasticsearch.xpack.sql.execution.search.extractor.ComputingExtractor.extract(ComputingExtractor.java:78)
        at org.elasticsearch.xpack.sql.execution.search.SearchHitRowSet.extractValue(SearchHitRowSet.java:111)
        at org.elasticsearch.xpack.sql.execution.search.SearchHitRowSet.extractValue(SearchHitRowSet.java:23)
        at org.elasticsearch.xpack.sql.execution.search.ResultRowSet.getColumn(ResultRowSet.java:37)
        at org.elasticsearch.xpack.sql.session.AbstractRowSet.column(AbstractRowSet.java:18)
        at org.elasticsearch.xpack.sql.session.RowView.forEachColumn(RowView.java:38)
```

Same query, but with grouping works though:

```
sql> select CONVERT(TRUNCATE((-1 * (DAYOFYEAR(date2) - 1)),0), SQL_BIGINT) * INTERVAL '1' DAY from calcs GROUP BY 1;
CONVERT(TRUNCATE((-1 * (DAYOFYEAR(date2) - 1)),0), SQL_BIGINT) * INTERVAL '1' DAY                                   
---------------------------------------------------------------------------------                                   
-109 00:00:00.0                                                                                                     
-116 00:00:00.0                                                                                                     
-122 00:00:00.0                                                                                                     
```

The test query can be simplified to something like `select CONVERT(DAYOFYEAR(date2), SQL_BIGINT) * INTERVAL '1' DAY from calcs`

**Comment by matriv** [comment]
Backported to `7.x` with 7473742e6eb053f812d809576c78bdf80476e422
to `7.1` with 08d38da2f1ffa9f48d8565fdc85e19e56c10cde7
to `6.8` with 3a20503c7e793e01ed492733ebed8a9d2e4c0e2f
