### ISSUE TITLE
Java read from elasticsearch error

### ISSUE THREAD

**Issue by wolfelven** [elastic/elasticsearch#41235]
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
19/04/16 10:25:33 INFO SparkContext: Running Spark version 2.3.0
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.hadoop.security.authentication.util.KerberosUtil (file:/Users/xujie/Desktop/Eclipse_Project/elasticgettrace/target/elastic-get-trace-1.0-SNAPSHOT.jar) to method sun.security.krb5.Config.getInstance()
WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.security.authentication.util.KerberosUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
19/04/16 10:25:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/04/16 10:25:35 INFO SparkContext: Submitted application: ElasticJob
19/04/16 10:25:35 INFO SecurityManager: Changing view acls to: root
19/04/16 10:25:35 INFO SecurityManager: Changing modify acls to: root
19/04/16 10:25:35 INFO SecurityManager: Changing view acls groups to: 
19/04/16 10:25:35 INFO SecurityManager: Changing modify acls groups to: 
19/04/16 10:25:35 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
19/04/16 10:25:37 INFO Utils: Successfully started service 'sparkDriver' on port 51896.
19/04/16 10:25:37 INFO SparkEnv: Registering MapOutputTracker
19/04/16 10:25:37 INFO SparkEnv: Registering BlockManagerMaster
19/04/16 10:25:37 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
19/04/16 10:25:37 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
19/04/16 10:25:37 INFO DiskBlockManager: Created local directory at /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/blockmgr-790b0a9a-cc2b-4d04-ac63-9cf05676a561
19/04/16 10:25:37 INFO MemoryStore: MemoryStore started with capacity 1048.8 MB
19/04/16 10:25:38 INFO SparkEnv: Registering OutputCommitCoordinator
19/04/16 10:25:40 INFO Utils: Successfully started service 'SparkUI' on port 4040.
19/04/16 10:25:40 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://10.35.112.222:4040
19/04/16 10:25:41 INFO SparkContext: Added JAR /Users/xujie/Desktop/Eclipse_Project/elasticgettrace/target/elastic-get-trace-1.0-SNAPSHOT.jar at spark://10.35.112.222:51896/jars/elastic-get-trace-1.0-SNAPSHOT.jar with timestamp 1555381541087
19/04/16 10:25:41 INFO Executor: Starting executor ID driver on host localhost
19/04/16 10:25:41 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 51897.
19/04/16 10:25:41 INFO NettyBlockTransferService: Server created on 10.35.112.222:51897
19/04/16 10:25:41 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
19/04/16 10:25:41 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.35.112.222, 51897, None)
19/04/16 10:25:41 INFO BlockManagerMasterEndpoint: Registering block manager 10.35.112.222:51897 with 1048.8 MB RAM, BlockManagerId(driver, 10.35.112.222, 51897, None)
19/04/16 10:25:41 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.35.112.222, 51897, None)
19/04/16 10:25:41 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 10.35.112.222, 51897, None)
19/04/16 10:25:43 INFO Version: Elasticsearch Hadoop v6.4.2 [54a631a014]
19/04/16 10:25:43 INFO JavaEsRDD: Reading from [jaeger-span-2019-04-15]
Exception in thread "main" java.lang.IllegalArgumentException
	at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
	at org.apache.spark.util.ClosureCleaner$.getClassReader(ClosureCleaner.scala:46)
	at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:449)
	at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:432)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
	at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:103)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at org.apache.spark.util.FieldAccessFinder$$anon$3.visitMethodInsn(ClosureCleaner.scala:432)
	at org.apache.xbean.asm5.ClassReader.a(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.b(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.accept(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.accept(Unknown Source)
	at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:262)
	at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:261)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:261)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:159)
	at org.apache.spark.SparkContext.clean(SparkContext.scala:2292)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2066)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2092)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:939)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:938)
	at org.apache.spark.api.java.JavaRDDLike$class.collect(JavaRDDLike.scala:361)
	at org.apache.spark.api.java.AbstractJavaRDDLike.collect(JavaRDDLike.scala:45)
	at ElasticDependenciesJob.main(ElasticDependenciesJob.java:22)
19/04/16 10:25:43 INFO SparkContext: Invoking stop() from shutdown hook
19/04/16 10:25:43 INFO SparkUI: Stopped Spark web UI at http://10.35.112.222:4040
19/04/16 10:25:43 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
19/04/16 10:25:43 INFO MemoryStore: MemoryStore cleared
19/04/16 10:25:43 INFO BlockManager: BlockManager stopped
19/04/16 10:25:43 INFO BlockManagerMaster: BlockManagerMaster stopped
19/04/16 10:25:43 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
19/04/16 10:25:43 INFO SparkContext: Successfully stopped SparkContext
19/04/16 10:25:43 INFO ShutdownHookManager: Shutdown hook called
19/04/16 10:25:43 INFO ShutdownHookManager: Deleting directory /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/spark-faf0c4e6-2bc5-4df0-9218-22c8d6d0c332

**Comment by wolfelven** [comment]
when i use JavaEsSpark to read data from elasticsearch, there is an error.
That's my code:
SparkConf conf = new SparkConf(true).setMaster("local[*]").setAppName("ElasticJob");
        conf.setJars(pathToUberJar());
        conf.set("es.nodes", "***");
        conf.set("es.nodes.wan.only", "true");

        JavaSparkContext sc = new JavaSparkContext(conf);
        JavaPairRDD<String, String> json = JavaEsSpark.esJsonRDD(sc, "***");
        System.out.println("json is " + String.valueOf(json.values().collect().size()));

**Comment by matriv** [comment]
Hello @wolfelven,

I'm closing this here and I'd ask you to open this issue in our [relevant github repo](https://github.com/elastic/elasticsearch-hadoop).

Thanks!
