### ISSUE TITLE
[CI] testShardNotAvailableExceptionWhenEngineClosedConcurrently trips assertion

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#41236]
**Build:** https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/336/

**Failure**
```
org.elasticsearch.index.engine.InternalEngineTests > testShardNotAvailableExceptionWhenEngineClosedConcurrently STANDARD_ERROR
    Apr 16, 2019 1:38:45 AM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
    WARNING: Uncaught exception in thread: Thread[Thread-227,5,TGRP-InternalEngineTests]
    java.lang.AssertionError: wait_if_ongoing must be true for a force flush: force=true wait_if_ongoing=false
    	at __randomizedtesting.SeedInfo.seed([A66D675F5899286A]:0)
    	at org.elasticsearch.index.engine.InternalEngine.flush(InternalEngine.java:1690)
    	at org.elasticsearch.index.engine.InternalEngineTests$6.run(InternalEngineTests.java:3091)
```

Does not reproduce for me (on 6aa52b1ac5f35c23fb4c39f4f7020966dcbf7c9a)
```
./gradlew :server:test --tests \
"org.elasticsearch.index.engine.InternalEngineTests.testShardNotAvailableExceptionWhenEngineClosedConcurrently" \
-Dtests.seed=A66D675F5899286A -Dtests.security.manager=true \
-Dtests.locale=en-PK -Dtests.timezone=Africa/Blantyre \
-Dcompiler.java=12 -Druntime.java=11
```

**Comment by tvernum** [comment]
@dnhatn This seems to be triggering a check you added in #40213
