### ISSUE TITLE
SQL: NullPointerException when GROUPing BY

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#41239]
I think this one is from the same area of issues as https://github.com/elastic/elasticsearch/issues/41200.

```
sql> SELECT ((CONVERT("calcs"."date2", SQL_DATE) + 5 * INTERVAL '1' DAY) + CONVERT(TRUNCATE((3 * (CONVERT(TRUNCATE(QUARTER("calcs"."date2"),0), SQL_BIGINT) - 1)),0), SQL_BIGINT) * INTERVAL '1' MONTH) AS result
> FROM "calcs"
> GROUP BY 1;
Server error [Server encountered an error [null]. [java.lang.NullPointerException
        at org.elasticsearch.xpack.sql.type.DataTypeConversion.commonType(DataTypeConversion.java:75)
        at org.elasticsearch.xpack.sql.expression.predicate.operator.arithmetic.ArithmeticOperation.dataType(ArithmeticOperation.java:40)
        at org.elasticsearch.xpack.sql.expression.Expressions.isNull(Expressions.java:107)
        at org.elasticsearch.xpack.sql.tree.Node.anyMatch(Node.java:118)
        at org.elasticsearch.xpack.sql.expression.Expressions.anyMatch(Expressions.java:61)
        at org.elasticsearch.xpack.sql.optimizer.Optimizer$FoldNull.rule(Optimizer.java:1171)
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:190)
        at org.elasticsearch.xpack.sql.plan.QueryPlan.lambda$transformExpressionsUp$4(QueryPlan.java:64)
        at org.elasticsearch.xpack.sql.plan.QueryPlan.doTransformExpression(QueryPlan.java:69)
        at org.elasticsearch.xpack.sql.plan.QueryPlan.doTransformExpression(QueryPlan.java:85)
        at org.elasticsearch.xpack.sql.plan.QueryPlan.lambda$transformExpressionsUp$5(QueryPlan.java:64)
        at org.elasticsearch.xpack.sql.tree.NodeInfo.lambda$transform$0(NodeInfo.java:55)
        at org.elasticsearch.xpack.sql.tree.NodeInfo$4.innerTransform(NodeInfo.java:146)
        at org.elasticsearch.xpack.sql.tree.NodeInfo.transform(NodeInfo.java:59)
        at org.elasticsearch.xpack.sql.tree.Node.transformNodeProps(Node.java:253)
        at org.elasticsearch.xpack.sql.tree.Node.lambda$transformPropertiesUp$13(Node.java:241)
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:190)
        at org.elasticsearch.xpack.sql.tree.Node.transformPropertiesUp(Node.java:241)
        at org.elasticsearch.xpack.sql.plan.QueryPlan.transformExpressionsUp(QueryPlan.java:64)
        at org.elasticsearch.xpack.sql.optimizer.Optimizer$OptimizerExpressionRule.apply(Optimizer.java:2006)
        at org.elasticsearch.xpack.sql.optimizer.Optimizer$OptimizerExpressionRule.apply(Optimizer.java:1995)
        at org.elasticsearch.xpack.sql.rule.RuleExecutor$Transformation.<init>(RuleExecutor.java:82)
        at org.elasticsearch.xpack.sql.rule.RuleExecutor.executeWithInfo(RuleExecutor.java:158)
        at org.elasticsearch.xpack.sql.rule.RuleExecutor.execute(RuleExecutor.java:130)
        at org.elasticsearch.xpack.sql.optimizer.Optimizer.optimize(Optimizer.java:116)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$optimizedPlan$3(SqlSession.java:152)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$preAnalyze$2(SqlSession.java:140)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)
        at org.elasticsearch.xpack.sql.analysis.index.IndexResolver.lambda$resolveAsMergedMapping$3(IndexResolver.java:245)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:68)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64)
        at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.lambda$doExecute$0(TransportFieldCapabilitiesAction.java:84)
```

`SELECT (({fn CONVERT("calcs"."datetime0", SQL_DATE)} + {fn CONVERT({fn TRUNCATE((-1 * ({fn DAYOFYEAR("calcs"."datetime0")} - 1)),0)}, SQL_BIGINT)} * INTERVAL '1' DAY) + {fn CONVERT({fn TRUNCATE((3 * ({fn CONVERT({fn TRUNCATE({fn QUARTER("calcs"."datetime0")},0)}, SQL_BIGINT)} - 1)),0)}, SQL_BIGINT)} * INTERVAL '1' MONTH) AS result FROM "calcs" GROUP BY 1`

`SELECT (({fn CONVERT("calcs"."date2", SQL_DATE)} + {fn CONVERT({fn TRUNCATE((-1 * ({fn DAYOFYEAR("calcs"."date2")} - 1)),0)}, SQL_BIGINT)} * INTERVAL '1' DAY) + {fn CONVERT({fn TRUNCATE((3 * ({fn CONVERT({fn TRUNCATE({fn QUARTER("calcs"."date2")},0)}, SQL_BIGINT)} - 1)),0)}, SQL_BIGINT)} * INTERVAL '1' MONTH) AS result FROM "calcs" GROUP BY 1`

`SELECT (({fn CONVERT("calcs"."date2", SQL_DATE)} + {fn CONVERT({fn TRUNCATE((-1 * ({fn DAYOFYEAR("calcs"."date2")} - 1)),0)}, SQL_BIGINT)} * INTERVAL '1' DAY) + {fn CONVERT({fn TRUNCATE((3 * ({fn CONVERT({fn TRUNCATE({fn QUARTER("calcs"."date2")},0)}, SQL_BIGINT)} - 1)),0)}, SQL_BIGINT)} * INTERVAL '1' MONTH) AS result FROM "calcs" GROUP BY 1`

`SELECT (({fn CONVERT("calcs"."datetime0", SQL_DATE)} + {fn CONVERT({fn TRUNCATE((-1 * ({fn DAYOFYEAR("calcs"."datetime0")} - 1)),0)}, SQL_BIGINT)} * INTERVAL '1' DAY) + {fn CONVERT({fn TRUNCATE((3 * ({fn CONVERT({fn TRUNCATE({fn QUARTER("calcs"."datetime0")},0)}, SQL_BIGINT)} - 1)),0)}, SQL_BIGINT)} * INTERVAL '1' MONTH) AS result FROM "calcs" GROUP BY 1`

**Comment by matriv** [comment]
Backported to `7.x` with 7473742e6eb053f812d809576c78bdf80476e422
to `7.1` with 08d38da2f1ffa9f48d8565fdc85e19e56c10cde7
to `6.8` with 3a20503c7e793e01ed492733ebed8a9d2e4c0e2f
