### ISSUE TITLE
[CI] 6.7 NPE in CcrRetentionLeaseIT

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#41237]
From: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+multijob-darwin-compatibility/109/console (using 081e56c26990586a54156c2d3e8edb513e9a9341)

I have an unrelated problem in my 6.7 tree so I can't try to reproduce right now.

```
 1> [2019-04-16T00:51:15,347][INFO ][o.e.x.c.CcrRetentionLeaseIT] [testRetentionLeaseRenewedWhileFollowing] after test
  2> REPRODUCE WITH: ./gradlew :x-pack:plugin:ccr:internalClusterTest -Dtests.seed=99EE038EE64725C6 -Dtests.class=org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT -Dtests.method="testRetentionLeaseRenewedWhileFollowing" -Dtests.security.manager=true -Dtests.locale=ar-MA -Dtests.timezone=Europe/Gibraltar -Dcompiler.java=12 -Druntime.java=8
ERROR   0.43s J4 | CcrRetentionLeaseIT.testRetentionLeaseRenewedWhileFollowing <<< FAILURES!
   > Throwable #1: java.lang.NullPointerException
   >    at __randomizedtesting.SeedInfo.seed([99EE038EE64725C6:E83DBA929C7325AE]:0)
   >    at org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.lambda$assertRetentionLeaseRenewal$16(CcrRetentionLeaseIT.java:982)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:846)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:832)
   >    at org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.assertRetentionLeaseRenewal(CcrRetentionLeaseIT.java:974)
   >    at org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.testRetentionLeaseRenewedWhileFollowing(CcrRetentionLeaseIT.java:552)
   >    at java.lang.Thread.run(Thread.java:748)
```

**Comment by dnhatn** [comment]
I opened #43059.
