### ISSUE TITLE
SQL: handle SQL not being available on server in a more graceful way

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#41279]
Using the JDBC driver on an OSS version of Elasticsearch generates a rather un-friendly error message. The message itself is technically correct, but is not a graceful way of letting the user know that the node it's trying to connect to doesn't have SQL installed.

This issue is very similar to https://github.com/elastic/elasticsearch/issues/30009.

```
Exception in thread "main" org.elasticsearch.xpack.sql.client.ClientException: Cannot POST address http://localhost:9200/_sql?error_trace (Can't parse error from Elasticsearch [Expected [error] to be an object but was [VALUE_STRING][Incorrect HTTP method for uri [/_sql?error_trace] and method [POST], allowed: [PUT, DELETE, GET, HEAD]]] at [line 1 col 10]. Response:
{"error":"Incorrect HTTP method for uri [/_sql?error_trace] and method [POST], allowed: [PUT, DELETE, GET, HEAD]","status":405})
	at org.elasticsearch.xpack.sql.client.JreHttpUrlConnection.request(JreHttpUrlConnection.java:163)
	at org.elasticsearch.xpack.sql.client.HttpClient.lambda$post$1(HttpClient.java:103)
	at org.elasticsearch.xpack.sql.client.JreHttpUrlConnection.http(JreHttpUrlConnection.java:65)
	at org.elasticsearch.xpack.sql.client.HttpClient.lambda$post$2(HttpClient.java:102)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.xpack.sql.client.HttpClient.post(HttpClient.java:101)
	at org.elasticsearch.xpack.sql.client.HttpClient.query(HttpClient.java:78)
	at org.elasticsearch.xpack.sql.jdbc.JdbcHttpClient.query(JdbcHttpClient.java:60)
	at org.elasticsearch.xpack.sql.jdbc.JdbcStatement.initResultSet(JdbcStatement.java:160)
	at org.elasticsearch.xpack.sql.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:60)
	at com.foo.Main.main(Main.java:34)
Caused by: java.io.IOException: Can't parse error from Elasticsearch [Expected [error] to be an object but was [VALUE_STRING][Incorrect HTTP method for uri [/_sql?error_trace] and method [POST], allowed: [PUT, DELETE, GET, HEAD]]] at [line 1 col 10]. Response:
{"error":"Incorrect HTTP method for uri [/_sql?error_trace] and method [POST], allowed: [PUT, DELETE, GET, HEAD]","status":405}
	at org.elasticsearch.xpack.sql.client.RemoteFailure.parseFromResponse(RemoteFailure.java:75)
	at org.elasticsearch.xpack.sql.client.JreHttpUrlConnection.parserError(JreHttpUrlConnection.java:174)
	at org.elasticsearch.xpack.sql.client.JreHttpUrlConnection.request(JreHttpUrlConnection.java:161)
	... 10 more
Caused by: java.io.IOException: Expected [error] to be an object but was [VALUE_STRING][Incorrect HTTP method for uri [/_sql?error_trace] and method [POST], allowed: [PUT, DELETE, GET, HEAD]]
	at org.elasticsearch.xpack.sql.client.RemoteFailure.parseResponseTopLevel(RemoteFailure.java:159)
	at org.elasticsearch.xpack.sql.client.RemoteFailure.parseFromResponse(RemoteFailure.java:71)
	... 12 more
```

**Comment by astefan** [comment]
master (8.0.0): https://github.com/elastic/elasticsearch/commit/8a1ac8a3a88a325ec9b99963e0fa288c18ee0ee5
7.x (7.4.0): https://github.com/elastic/elasticsearch/commit/9567f337f5735ee21aa54c76433d764ea6b525e2
7.3 (7.3.1): https://github.com/elastic/elasticsearch/commit/41fa08ef1da44aa80565f1216e0db0c53eadc88a
7.2 (7.2.2): https://github.com/elastic/elasticsearch/commit/2ca7763e4f11e0b1a26cba09a2a550a7bbc208e2
