### ISSUE TITLE
[CI] Test Failure in org.elasticsearch.client.BulkProcessorRetryIT#testBulkRejectionLoadWithBackoff

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#41324]
This is a result of #40866 

We're running into https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/1107/console

```
  2> REPRODUCE WITH: ./gradlew :server:integTest --tests "org.elasticsearch.action.bulk.BulkProcessorRetryIT.testBulkRejectionLoadWithBackoff" -Dtests.seed=A9EF087F2D4CFAB -Dtests.security.manager=true -Dtests.locale=sr-Latn-RS -Dtests.timezone=America/Martinique -Dcompiler.java=12 -Druntime.java=8
  2> java.lang.AssertionError: Unexpected failure
        at __randomizedtesting.SeedInfo.seed([A9EF087F2D4CFAB:5EF9783BACF11D86]:0)
        at org.elasticsearch.action.bulk.BulkProcessorRetryIT.executeBulkRejectionLoad(BulkProcessorRetryIT.java:143)
        at org.elasticsearch.action.bulk.BulkProcessorRetryIT.testBulkRejectionLoadWithBackoff(BulkProcessorRetryIT.java:69)

        Caused by:
        RemoteTransportException[[node_s0][127.0.0.1:40957][indices:data/write/bulk]]; nested: EsRejectedExecutionException[rejected execution of org.elasticsearch.transport.InboundHandler$RequestHandler@61f4536b on EsThreadPoolExecutor[name = node_s0/write, queue capacity = 30, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@1494a6e[Running, pool size = 1, active threads = 1, queued tasks = 30, completed tasks = 525]]];

            Caused by:
            org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of org.elasticsearch.transport.InboundHandler$RequestHandler@61f4536b on EsThreadPoolExecutor[name = node_s0/write, queue capacity = 30, 
```

The problem here is that by moving the bulk requests' initial handling to the WRITE pool entirely we lost the bulk processor's retry functionality for the case of the initial request getting rejected outright.
We will need to discuss whether to find a way to retry this after-all or adjust the test I think.

**Comment by original-brownbear** [comment]
I will mute this for now, until we're clear on how to solve this.

**Comment by davidkyle** [comment]
This test failed again on master

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+artifactory/610/console

```
java.lang.AssertionError: Unexpected failure
	at __randomizedtesting.SeedInfo.seed([809C23D4D17E7B70:D4FBAB688F5BA95D]:0)
	at org.elasticsearch.action.bulk.BulkProcessorRetryIT.executeBulkRejectionLoad(BulkProcessorRetryIT.java:143)
	at org.elasticsearch.action.bulk.BulkProcessorRetryIT.testBulkRejectionLoadWithBackoff(BulkProcessorRetryIT.java:69)

...

Caused by: RemoteTransportException[[node_s0][127.0.0.1:44805][indices:data/write/bulk]]; nested: EsRejectedExecutionException[rejected execution of org.elasticsearch.transport.InboundHandler$RequestHandler@16966335 on EsThreadPoolExecutor[name = node_s0/write, queue capacity = 30, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@4990ff71[Running, pool size = 1, active threads = 1, queued tasks = 30, completed tasks = 1268]]];
Caused by: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of org.elasticsearch.transport.InboundHandler$RequestHandler@16966335 on EsThreadPoolExecutor[name = node_s0/write, queue capacity = 30, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@4990ff71[Running, pool size = 1, active threads = 1, queued tasks = 30, completed tasks = 1268]]
	at org.elasticsearch.common.util.concurrent.EsAbortPolicy.rejectedExecution(EsAbortPolicy.java:48)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor.execute(EsThreadPoolExecutor.java:84)
```

Does not reproduce:
```
./gradlew :server:integTest --tests "org.elasticsearch.action.bulk.BulkProcessorRetryIT.testBulkRejectionLoadWithBackoff" \
  -Dtests.seed=809C23D4D17E7B70 \
  -Dtests.security.manager=true \
  -Dtests.locale=be-BY \
  -Dtests.timezone=America/Matamoros \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

**Comment by original-brownbear** [comment]
fix incoming in https://github.com/elastic/elasticsearch/pull/41700 (reproducible by simply lowering the queue size in this test's settings to `1`, but the failure was very unlikely for queue size 30)
