### ISSUE TITLE
org.elasticsearch.transport.netty4.ESLoggingHandlerIT.testLoggingHandler Failure

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#41415]
Reproduce with: 
```
./gradlew :modules:transport-netty4:integTestRunner --tests "org.elasticsearch.transport.netty4.ESLoggingHandlerIT.testLoggingHandler" -Dtests.seed=F822CBA1D10B1A81 -Dtests.security.manager=true -Dtests.locale=is-IS -Dtests.timezone=SystemV/YST9YDT -Dcompiler.java=12 -Druntime.java=8
```

This looks fairly similar to https://github.com/elastic/elasticsearch/issues/27306 but not entirely so I'm opening a new issue instead of re-opening the old one. 
It failed on 7.x intake (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/1145/testReport/junit/org.elasticsearch.transport.netty4/ESLoggingHandlerIT/testLoggingHandler/) . This doesn't reproduce locally with the given seed but has failed 4 times in the last 6 months: 

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testLoggingHandler),sort:!(time,desc)) 

```
2019-04-22 04:53:50,511 elasticsearch[node_sm2][transport_worker][T#1] ERROR An exception occurred processing Appender mock java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at org.elasticsearch.test.MockLogAppender.append(MockLogAppender.java:54)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:464)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:448)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:431)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
	at org.apache.logging.log4j.core.config.DefaultReliabilityStrategy.log(DefaultReliabilityStrategy.java:49)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2170)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2125)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2108)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2002)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1974)
	at org.apache.logging.log4j.spi.AbstractLogger.trace(AbstractLogger.java:2303)
	at org.elasticsearch.transport.netty4.Netty4InternalESLogger.trace(Netty4InternalESLogger.java:44)
	at io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:144)
	at io.netty.handler.logging.LoggingHandler.flush(LoggingHandler.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.doFlush(Netty4MessageChannelHandler.java:163)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.flush(Netty4MessageChannelHandler.java:100)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1066)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:309)
	at org.elasticsearch.transport.netty4.Netty4TcpChannel.sendMessage(Netty4TcpChannel.java:146)
	at org.elasticsearch.transport.OutboundHandler.internalSend(OutboundHandler.java:134)
	at org.elasticsearch.transport.OutboundHandler.sendMessage(OutboundHandler.java:127)
	at org.elasticsearch.transport.OutboundHandler.sendResponse(OutboundHandler.java:107)
	at org.elasticsearch.transport.TcpTransportChannel.sendResponse(TcpTransportChannel.java:64)
	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:54)
	at org.elasticsearch.cluster.coordination.FollowersChecker.handleFollowerCheck(FollowersChecker.java:174)
	at org.elasticsearch.cluster.coordination.FollowersChecker.lambda$new$0(FollowersChecker.java:116)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63)
	at org.elasticsearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:267)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:192)
	at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:188)
	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:121)
	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:105)
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:645)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:62)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tbrooks8** [comment]
This is similar to this: #40586. Probably a case of needing to fulling setup the mock log appender before adding it as an appender.

**Comment by jasontedor** [comment]
This is caused by messages being sent outside the control of the test while expectations are being set up (which modifies the collection of expectations). Since adding a message causes an iteration of the collection of expectations, this occurring concurrently leads to a concurrent modification exception. There are two approaches here, one is to make the backing list an copy-on-write array list, and the other is to synchronize these methods. While in this specific test we could get around the issue by initializing the appender before the cluster forms (and therefore before such messages start being sent) (here it is messages from followers checker), I don't know that we can always take this approach and I would rather err on the safe side and deal with the concurrency issues. It looks like an approach with copy-on-write array list would be fine since we always set up expectations before we force some situation that we think is going to cause those expectations to be met. That means to me that we don't need to worry about synchronizing (for ordering guarantees), and using a copy-on-write array list is good so as to avoid bottlenecking these tests on logging.

I opened #41424.
