### ISSUE TITLE
[CI] Failure in PermissionsIT testWhenUserLimitedByOnlyAliasOfIndexCanWriteToIndexWhichWasRolledoverByILMPolicy

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#41440]
`PermissionsIT.testWhenUserLimitedByOnlyAliasOfIndexCanWriteToIndexWhichWasRolledoverByILMPolicy` failed in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=opensuse/351/console

The error was:

```
java.lang.RuntimeException: org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:46270], URI [/foo-logs-000002/_search], status line [HTTP/1.1 503 Service Unavailable]
{"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[]},"status":503}
	at __randomizedtesting.SeedInfo.seed([C46765F443037D6B:12B383234273C1C0]:0)
	at org.elasticsearch.xpack.security.PermissionsIT.lambda$testWhenUserLimitedByOnlyAliasOfIndexCanWriteToIndexWhichWasRolledoverByILMPolicy$4(PermissionsIT.java:186)
	at org.elasticsearch.test.ESTestCase.awaitBusy(ESTestCase.java:883)
	at org.elasticsearch.test.ESTestCase.awaitBusy(ESTestCase.java:872)
	at org.elasticsearch.xpack.security.PermissionsIT.testWhenUserLimitedByOnlyAliasOfIndexCanWriteToIndexWhichWasRolledoverByILMPolicy(PermissionsIT.java:176)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:46270], URI [/foo-logs-000002/_search], status line [HTTP/1.1 503 Service Unavailable]
{"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[]},"status":503}
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:260)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:238)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212)
	at org.elasticsearch.xpack.security.PermissionsIT.lambda$testWhenUserLimitedByOnlyAliasOfIndexCanWriteToIndexWhichWasRolledoverByILMPolicy$4(PermissionsIT.java:180)
	... 39 more
```

This did not reproduce locally using:

```
./gradlew :x-pack:plugin:ilm:qa:with-security:integTestRunner --tests "org.elasticsearch.xpack.security.PermissionsIT.testWhenUserLimitedByOnlyAliasOfIndexCanWriteToIndexWhichWasRolledoverByILMPolicy" \
  -Dtests.seed=C46765F443037D6B \
  -Dtests.security.manager=true \
  -Dtests.locale=ii \
  -Dtests.timezone=Asia/Phnom_Penh \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

**Comment by danielmitterdorfer** [comment]
We have another failure in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.1+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=zulu11,nodes=immutable&&linux&&docker/9/console

Reproduction line (does not reproduce locally):

```
./gradlew :x-pack:plugin:ilm:qa:with-security:integTestRunner --tests "org.elasticsearch.xpack.security.PermissionsIT.testWhenUserLimitedByOnlyAliasOfIndexCanWriteToIndexWhichWasRolledoverByILMPolicy" -Dtests.seed=27723EFC61E2EF2E -Dtests.security.manager=true -Dtests.locale=ne-IN -Dtests.timezone=Europe/Warsaw -Dcompiler.java=12 -Druntime.java=11
```

Failure message:

```
 java.lang.RuntimeException: org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:33629], URI [/foo-logs-000002/_search], status line [HTTP/1.1 503 Service Unavailable]
    {"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[]},"status":503}
        at __randomizedtesting.SeedInfo.seed([27723EFC61E2EF2E:F1A6D82B60925385]:0)
        at org.elasticsearch.xpack.security.PermissionsIT.lambda$testWhenUserLimitedByOnlyAliasOfIndexCanWriteToIndexWhichWasRolledoverByILMPolicy$4(PermissionsIT.java:186)
        at org.elasticsearch.test.ESTestCase.awaitBusy(ESTestCase.java:889)
        at org.elasticsearch.test.ESTestCase.awaitBusy(ESTestCase.java:878)
        at org.elasticsearch.xpack.security.PermissionsIT.testWhenUserLimitedByOnlyAliasOfIndexCanWriteToIndexWhichWasRolledoverByILMPolicy(PermissionsIT.java:176)

        Caused by:
        org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:33629], URI [/foo-logs-000002/_search], status line [HTTP/1.1 503 Service Unavailable]
        {"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[]},"status":503}
```

Also attaching the [cluster log](https://github.com/elastic/elasticsearch/files/3148176/x-pack_plugin_ilm_qa_with-security_integTestCluster.log).

**Comment by pgomulka** [comment]
Another failure : 
```

REPRODUCE WITH: ./gradlew :x-pack:plugin:ilm:qa:with-security:integTestRunner --tests "org.elasticsearch.xpack.security.PermissionsIT.testWhenUserLimitedByOnlyAliasOfIndexCanWriteToIndexWhichWasRolledoverByILMPolicy" \
  -Dtests.seed=5EC880B35B603DEF \
  -Dtests.security.manager=true \
  -Dtests.locale=pa \
  -Dtests.timezone=Asia/Seoul \
  -Dcompiler.java=12 \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew :x-pack:plugin:ilm:qa:with-security:integTestRunner --tests "org.elasticsearch.xpack.security.PermissionsIT.testWhenUserLimitedByOnlyAliasOfIndexCanWriteToIndexWhichWasRolledoverByILMPolicy" \
  -Dtests.seed=5EC880B35B603DEF \
  -Dtests.security.manager=true \
  -Dtests.locale=pa \
  -Dtests.timezone=Asia/Seoul \
  -Dcompiler.java=12 \
  -Druntime.java=11
```
https://scans.gradle.com/s/es6lo3sc42bxg

**Comment by mark-vieira** [comment]
Here's another incidence: https://gradle-enterprise.elastic.co/s/jctl6yfq3k7tw/tests/2gzwilc7fv272-asrfi26w7s552

**Comment by mark-vieira** [comment]
Here's another one of the same assertion error:

https://gradle-enterprise.elastic.co/s/cchnav6os4aj4/tests/2gzwilc7fv272-asrfi26w7s552

**Comment by mark-vieira** [comment]
This has started [regularly failing](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(message,branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:'test:%20%22testWhenUserLimitedByOnlyAliasOfIndexCanWriteToIndexWhichWasRolledoverByILMPolicy%22'),sort:!(time,desc))) with the below error since last week so I've muted this in `master`.

```
java.lang.AssertionError: 
Expected: <1>
     but: was <0>
```
