### ISSUE TITLE
[CI] UpgradeClusterClientYamlTestSuiteIT.test {p0=old_cluster/10_basic/Create an index with _all explicitly disabled} fails for 7.0.0 to 7.0.1

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#41453]
`UpgradeClusterClientYamlTestSuiteIT.test {p0=old_cluster/10_basic/Create an index with _all explicitly disabled}` is failing for builds that test upgrade from 7.0.0 to 7.0.1.

The reason is that the test is expecting the old cluster to be 6.x and when the old cluster is 7.0.0 it doesn't support the functionality that is used:

```
  1> [2019-04-24T02:14:33,961][INFO ][o.e.u.UpgradeClusterClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "error" : {
  1>         "root_cause" : [
  1>           {
  1>             "type" : "mapper_parsing_exception",
  1>             "reason" : "Root mapping definition has unsupported parameters:  [_all : {enabled=false}]",
  1>             "stack_trace" : "MapperParsingException[Root mapping definition has unsupported parameters:  [_all : {enabled=false}]]
  1>    at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:152)
  1>    at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:140)
  1>    at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:92)
  1>    at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:392)
  1>    at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:323)
  1>    at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:476)
  1>    at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47)
  1>    at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:687)
  1>    at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:310)
  1>    at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:210)
  1>    at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:142)
  1>    at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
  1>    at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
  1>    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681)
  1>    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
  1>    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
  1>    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  1>    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  1>    at java.lang.Thread.run(Thread.java:835)
  1> "
  1>           }
  1>         ],
```

It can be reproduced on the 7.0 branch with:

```
./gradlew :qa:rolling-upgrade:v7.0.0#bwcTest -Dtests.seed=6A1D067DD14D7030
```

Interestingly on the 7.x branch the test has been completely removed to avoid this problem.  I am not sure that is ideal either because then we won't be testing this aspect of the upgrade from 6.x at all.

**Comment by jimczi** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/41462
