### ISSUE TITLE
[CI] testDriverConfigurationWithSSLInURL fails

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#41557]
`testDriverConfigurationWithSSLInURL` starts failing on CI after https://github.com/elastic/elasticsearch/commit/0ca375ed42f420f4c7c4a8c489a2ecc328db3648.

```
  2> java.lang.AssertionError: Driver registration should have been successful. Error: java.sql.SQLException: No suitable driver
        at __randomizedtesting.SeedInfo.seed([D912BBBA5B9BCB6B:A9E1C8ACED9F587D]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.elasticsearch.xpack.sql.jdbc.JdbcConfigurationTests.testDriverConfigurationWithSSLInURL(JdbcConfigurationTests.java:265)
```

I can't reproduce this locally. 

```
./gradlew :x-pack:plugin:sql:jdbc:test --tests "org.elasticsearch.xpack.sql.jdbc.JdbcConfigurationTests.testDriverConfigurationWithSSLInURL" \
  -Dtests.seed=D912BBBA5B9BCB6B \
  -Dtests.security.manager=true \
  -Dtests.locale=mg-MG \
  -Dtests.timezone=America/Dawson_Creek \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

Relates #41283

**Comment by dnhatn** [comment]
@tbrooks8 Can you please have a look? Thank you!

**Comment by tbrooks8** [comment]
I don't think this relates to my change.

This fails on 7.0 (my change is not on 7.0):

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+artifactory/277/console

And on master prior to my commit:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+artifactory/548/console

**Comment by dnhatn** [comment]
@tbrooks8 Good catch. I missed that one.

**Comment by astefan** [comment]
Had a first look at this one, but I can't see how this could fail unless something did go wrong on the CI infra. And can't reproduce locally either. @dnhatn should I allow this test to run again and maybe a future failure to reveal more on the environment around the failure?

**Comment by dnhatn** [comment]
@astefan Thanks for looking. Please unmute the test and add whatever log that you need.

**Comment by astefan** [comment]
Tests are re-enabled now.

**Comment by atorok** [comment]
These seem to reproduce constantly e.x. https://gradle-enterprise.elastic.co/s/rtnrsij5womtq/tests/fswe7cwgla35g-a6pci3z7j2mns 

I'm going to mute them again to prevent them from masking other windows failures.

**Comment by romseygeek** [comment]
This is also failing on 7.x (eg https://gradle-enterprise.elastic.co/s/savqudvq7jria/console-log?task=:x-pack:plugin:sql:jdbc:test), so I will mute it there.

**Comment by iverase** [comment]
I am muting branches 7.5 and 7.4 as they are failing there as well.

**Comment by astefan** [comment]
@atorok @iverase @romseygeek were you able to repro any of these locally?

**Comment by dimitris-athanasiou** [comment]
@atorok Your mute commit https://github.com/elastic/elasticsearch/commit/3d4a7d0c6cfb3516bd1e94213788b66b42ca9cf7 seems to not actually adding and `@AwaitsFix`. Am I missing something? Just got another failure in `7.4` and looked at all the mutes which are backports of your commit.

**Comment by atorok** [comment]
@dimitris-athanasiou It adds `assumeFalse` to conditionally mute the test on windows only

**Comment by dimitris-athanasiou** [comment]
Ah, I see. It seems we're also catching  failures in darwin (e.g. https://gradle-enterprise.elastic.co/s/wnuyywau7seka/tests/fswe7cwgla35g-a6pci3z7j2mns). I'll mute using `@AwaitsFix`.

**Comment by astefan** [comment]
@dimitris-athanasiou were you able to repro this locally?

**Comment by dimitris-athanasiou** [comment]
@astefan No, it doesn't reproduce locally unfortunately.
