### ISSUE TITLE
[CI] :plugins:discovery-gce:qa:gce:integTestCluster#wait failing

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#41566]
Failed on my PR build here:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/12781/

Primary cause seems to be:

```
|    [2019-04-25T19:29:58,824][WARN ][o.e.c.g.GceInstancesServiceImpl] [node-0] Problem fetching instance list for zone test-zone
|    com.google.api.client.googleapis.json.GoogleJsonResponseException: 500 Internal Server Error
|    /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request-1/plugins/discovery-gce/qa/gce/build/generated-resources/nodes.uri
|    	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146) ~[google-api-client-1.23.0.jar:1.23.0]
|    	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113) ~[google-api-client-1.23.0.
```

Found a previous similar 6.x only issue here, unsure if related: #34272.

Seems frequency is low so did not mute.

**Comment by henningandersen** [comment]
[consoleText.txt.gz](https://github.com/elastic/elasticsearch/files/3120297/consoleText.txt.gz)

**Comment by ywelsch** [comment]
The console output linked here shows a failure of `:modules:analysis-common:test`, not GCE. The original logs have since been gone, so closing this.
