### ISSUE TITLE
[CI] TokenBackwardsCompatibilityIT testGeneratingTokenInOldCluster failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#41671]
This is a reproducible BWC failure on the 7.0 branch

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+bwc-tests/337/console

The reproduce line from the build failure:
```
./gradlew :x-pack:qa:rolling-upgrade:v7.0.0#oldClusterTestRunner --tests "org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.testGeneratingTokenInOldCluster" \
  -Dtests.seed=1D119EE50CC2B50F \
  -Dtests.security.manager=true \
  -Dtests.locale=es \
  -Dtests.timezone=America/Guatemala \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

The **actual** reproduce command
```
./gradlew :x-pack:qa:rolling-upgrade:v7.0.0#bwcTest -Dtests.class="org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT"
```

The error:
```
org.elasticsearch.client.WarningFailureException: method [PUT], host [http://[::1]:45499], URI [token_backwards_compatibility_it/doc/old_cluster_token1], status line [HTTP/1.1 201 Created]
Warnings: [[types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id}).]
{"_index":"token_backwards_compatibility_it","_type":"doc","_id":"old_cluster_token1","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1}
	at __randomizedtesting.SeedInfo.seed([1D119EE50CC2B50F:A2509A7DBEE4D041]:0)
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:256)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:238)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212)
	at org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.testGeneratingTokenInOldCluster(TokenBackwardsCompatibilityIT.java:72)
```

I think this failure is due to the assumption that the old cluster will be 6.x but with the imminent release of 7.0.1 you can perform a rolling upgrade from 7.0.0

**Comment by davidkyle** [comment]
Muted in the 7.0 branch df036bcc66ffe72a73c5ce567782d45d833eb73b

**Comment by albertzaharovits** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/41680 .
