### ISSUE TITLE
[CI] RejectedExecutionTests.testHistoryAndTriggeredOnRejection failures

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#41734]
Failed a few times in the last few days, latest on 7.x:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8,nodes=immutable&&linux&&docker/149/console

Cannot reproduce locally so far:
```
REPRODUCE WITH: ./gradlew :x-pack:plugin:watcher:test --tests "org.elasticsearch.xpack.watcher.test.integration.RejectedExecutionTests.testHistoryAndTriggeredOnRejection" \
  -Dtests.seed=D07CF9EA42AC6079 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-NI \
  -Dtests.timezone=Australia/LHI \
  -Dcompiler.java=12 \
  -Druntime.java=8
```
```
java.lang.AssertionError: 
Expected: <0L>
     but: was <1L>
	at __randomizedtesting.SeedInfo.seed([D07CF9EA42AC6079:7885EBC331CED57D]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.watcher.test.integration.RejectedExecutionTests.testHistoryAndTriggeredOnRejection(RejectedExecutionTests.java:62)
```

Earlier failures on other branches (7.0, 7.x, master):

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux-6/368/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk12,nodes=immutable&&linux&&docker/145/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/1131/console

**Comment by cbuescher** [comment]
@jakelandis looks like you just added this test recently, maybe you can take a look? I will mute it on the three failing branches in the meantime.

**Comment by cbuescher** [comment]
Muted on master with 6b056ff599, 7.x with 6b056ff599, 7.1 with 5795494f55f18 and 7.0 with 32b17125d73944ca457d8ef2fc0e122d2fb863dc

**Comment by cbuescher** [comment]
Also just one coming in from 6.7 branch:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+multijob-unix-compatibility/os=ubuntu-16.04&&immutable/142/console

**Comment by cbuescher** [comment]
Also muted on 6.8 (09d3917fcbdcffb876b5f75f936033b13d78335a) and 6.7 (dbd06b7ac494e8).
