### ISSUE TITLE
[CI] DedicatedClusterSnapshotRestoreIT#testSnapshotWithStuckNode fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#41748]
On 7.0: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java12,nodes=immutable&&linux&&docker/146/console

Could not reproduce:
```
./gradlew :server:integTest --tests "org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT.testSnapshotWithStuckNode" \
  -Dtests.seed=D48A8D256CBF1A77 \
  -Dtests.security.manager=true \
  -Dtests.locale=uz-Arab \
  -Dtests.timezone=America/Resolute \
  -Dcompiler.java=12 \
  -Druntime.java=12
```
```
java.lang.AssertionError: Unexpected file count, found: [[/var/lib/jenkins/workspace/elastic+elasticsearch+7.0+matrix-java-periodic/ES_BUILD_JAVA/openjdk12/ES_RUNTIME_JAVA/java12/nodes/immutable&&linux&&docker/server/build/testrun/integTest/temp/org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT_D48A8D256CBF1A77-001/tempDir-007/repos/LLUvkWLanN/incompatible-snapshots, /var/lib/jenkins/workspace/elastic+elasticsearch+7.0+matrix-java-periodic/ES_BUILD_JAVA/openjdk12/ES_RUNTIME_JAVA/java12/nodes/immutable&&linux&&docker/server/build/testrun/integTest/temp/org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT_D48A8D256CBF1A77-001/tempDir-007/repos/LLUvkWLanN/indices/uZ8OrjeoSqG61Xrm8o2xMA/0/__hjeEBsBwR92D5erU-tV6Ow, /var/lib/jenkins/workspace/elastic+elasticsearch+7.0+matrix-java-periodic/ES_BUILD_JAVA/openjdk12/ES_RUNTIME_JAVA/java12/nodes/immutable&&linux&&docker/server/build/testrun/integTest/temp/org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT_D48A8D256CBF1A77-001/tempDir-007/repos/LLUvkWLanN/index-0, /var/lib/jenkins/workspace/elastic+elasticsearch+7.0+matrix-java-periodic/ES_BUILD_JAVA/openjdk12/ES_RUNTIME_JAVA/java12/nodes/immutable&&linux&&docker/server/build/testrun/integTest/temp/org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT_D48A8D256CBF1A77-001/tempDir-007/repos/LLUvkWLanN/index.latest, /var/lib/jenkins/workspace/elastic+elasticsearch+7.0+matrix-java-periodic/ES_BUILD_JAVA/openjdk12/ES_RUNTIME_JAVA/java12/nodes/immutable&&linux&&docker/server/build/testrun/integTest/temp/org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT_D48A8D256CBF1A77-001/tempDir-007/repos/LLUvkWLanN/index-1]]. expected:<4> but was:<5>
	at __randomizedtesting.SeedInfo.seed([D48A8D256CBF1A77:1F6F4A5451095E18]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.elasticsearch.snapshots.AbstractSnapshotIntegTestCase.assertFileCount(AbstractSnapshotIntegTestCase.java:87)
```

**Comment by original-brownbear** [comment]
We already have one for this https://github.com/elastic/elasticsearch/issues/39852 :)
