### ISSUE TITLE
[CI] CcrRetentionLeaseIT#testUnfollowRemovesRetentionLeases fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#41756]
Slightly different from the timouts in another method in the same test suite earlier today (#41737), but might be related:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+artifactory/643/console

Could not reproduce locally.
```
./gradlew :x-pack:plugin:ccr:internalClusterTest --tests "org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.testUnfollowRemovesRetentionLeases" -Dtests.seed=A90FBA15464DA110 -Dtests.security.manager=true -Dtests.locale=ky -Dtests.timezone=Asia/Novosibirsk -Dcompiler.java=12 -Druntime.java=11
```
```
java.lang.AssertionError: 
Expected: a collection with size <1>
     but: collection size was <0>
	at __randomizedtesting.SeedInfo.seed([A90FBA15464DA110:21BF0D72D1A877A8]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.testUnfollowRemovesRetentionLeases(CcrRetentionLeaseIT.java:393)
```

**Comment by ywelsch** [comment]
Can you have a look @jasontedor?

**Comment by jasontedor** [comment]
Thanks for the ping @ywelsch, I was not aware of this otherwise. I enabled trace logging for this test, I can not make sense of this failure with the logs presented so far.
