### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext error on elasticsearch 6.5.4

### ISSUE THREAD

**Issue by abhidrona** [elastic/elasticsearch#41789]
This is happening on MacOs, and I am yet to reproduce this on Linux. Anyone else is have come across this issue? 

Elasticsearch version (bin/elasticsearch --version): 6.5.4

Plugins installed: []

JVM version (java -version): 1.8.0_171

OS version (uname -a if on a Unix-like system): MacOS

Caused by: java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_171]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_171]
	at java.security.Provider$Service.getImplClass(Provider.java:1634) ~[?:1.8.0_171]
	at java.security.Provider$Service.newInstance(Provider.java:1592) ~[?:1.8.0_171]
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236) ~[?:1.8.0_171]
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164) ~[?:1.8.0_171]
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156) ~[?:1.8.0_171]
	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96) ~[?:1.8.0_171]
	at org.elasticsearch.client.RestClientBuilder.createHttpClient(RestClientBuilder.java:207) ~[elasticsearch-rest-client-6.3.1.jar:6.3.1]
	at org.elasticsearch.client.RestClientBuilder.access$000(RestClientBuilder.java:42) ~[elasticsearch-rest-client-6.3.1.jar:6.3.1]
	at org.elasticsearch.client.RestClientBuilder$1.run(RestClientBuilder.java:186) ~[elasticsearch-rest-client-6.3.1.jar:6.3.1]
	at org.elasticsearch.client.RestClientBuilder$1.run(RestClientBuilder.java:183) ~[elasticsearch-rest-client-6.3.1.jar:6.3.1]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
	at org.elasticsearch.client.RestClientBuilder.build(RestClientBuilder.java:183) ~[elasticsearch-rest-client-6.3.1.jar:6.3.1]
	at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:204) ~[elasticsearch-rest-high-level-client-6.3.1.jar:6.3.1]
	at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:196) ~[elasticsearch-rest-high-level-client-6.3.1.jar:6.3.1]

**Comment by jbaiera** [comment]
Is this the full error message? Can you provide a reproduction of the error as well as the full error log if it is not? The NoClassDefFoundError could be from any number of static code blocks in the DefaultSSLContext's super classes.

**Comment by abhidrona** [comment]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_171]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_171]
	at java.security.Provider$Service.getImplClass(Provider.java:1634) ~[?:1.8.0_171]
	at java.security.Provider$Service.newInstance(Provider.java:1592) ~[?:1.8.0_171]
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236) ~[?:1.8.0_171]
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164) ~[?:1.8.0_171]
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156) ~[?:1.8.0_171]
	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96) ~[?:1.8.0_171]
	at org.elasticsearch.client.RestClientBuilder.createHttpClient(RestClientBuilder.java:207) ~[elasticsearch-rest-client-6.3.1.jar:6.3.1]
	at org.elasticsearch.client.RestClientBuilder.access$000(RestClientBuilder.java:42) ~[elasticsearch-rest-client-6.3.1.jar:6.3.1]
	at org.elasticsearch.client.RestClientBuilder$1.run(RestClientBuilder.java:186) ~[elasticsearch-rest-client-6.3.1.jar:6.3.1]
	at org.elasticsearch.client.RestClientBuilder$1.run(RestClientBuilder.java:183) ~[elasticsearch-rest-client-6.3.1.jar:6.3.1]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
	at org.elasticsearch.client.RestClientBuilder.build(RestClientBuilder.java:183) ~[elasticsearch-rest-client-6.3.1.jar:6.3.1]
	at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:204) ~[elasticsearch-rest-high-level-client-6.3.1.jar:6.3.1]
	at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:196) ~[elasticsearch-rest-high-level-client-6.3.1.jar:6.3.1]
	at org.apache.flink.streaming.connectors.elasticsearch6.Elasticsearch6ApiCallBridge.createClient(Elasticsearch6ApiCallBridge.java:75) ~[flink-connector-elasticsearch6_2.12-1.8.0.jar:1.8.0]
	at org.apache.flink.streaming.connectors.elasticsearch6.Elasticsearch6ApiCallBridge.createClient(Elasticsearch6ApiCallBridge.java:47) ~[flink-connector-elasticsearch6_2.12-1.8.0.jar:1.8.0]
	at org.apache.flink.streaming.connectors.elasticsearch.ElasticsearchSinkBase.open(ElasticsearchSinkBase.java:299) ~[flink-connector-elasticsearch-base_2.12-1.8.0.jar:1.8.0]
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36) ~[flink-core-1.8.0.jar:1.8.0]
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102) ~[flink-streaming-java_2.12-1.8.0.jar:1.8.0]
	at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48) ~[flink-streaming-java_2.12-1.8.0.jar:1.8.0]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:424) ~[flink-streaming-java_2.12-1.8.0.jar:1.8.0]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:290) ~[flink-streaming-java_2.12-1.8.0.jar:1.8.0]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711) ~[flink-runtime_2.12-1.8.0.jar:1.8.0]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_171]


Here is the full stack, 

I am using the elasticsearch flink connector, flink-connector-elasticsearch6_2.12. But this seem to be from elasticsearch.

**Comment by ebadyano** [comment]
@elastic/es-core-features
