### ISSUE TITLE
[CI] DeleteByQueryBasicTests.testMultipleSources failure 

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#41897]
Failed for master: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/3441/console

## Reproduction line
(does not) reproduce locally
```
REPRODUCE WITH: ./gradlew :modules:reindex:test --tests "org.elasticsearch.index.reindex.DeleteByQueryBasicTests.testMultipleSources" \
  -Dtests.seed=E9AEC2E76FFDCDE8 \
  -Dtests.security.manager=true \
  -Dtests.locale=rw-RW \
  -Dtests.timezone=Asia/Makassar \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

## Example relevant log:
```
org.elasticsearch.index.reindex.DeleteByQueryBasicTests > testMultipleSources FAILED
    java.lang.AssertionError: 
    Expected: an empty iterable
         but: [<RemoteTransportException[[node_sd4][127.0.0.1:34987][indices:data/write/index]]; nested: ProcessClusterEventTimeoutException[failed to process cluster event (put-mapping) within 12s];>,<RemoteTransportException[[node_sm2][127.0.0.1:41867][indices:data/write/index]]; nested: ProcessClusterEventTimeoutException[failed to process cluster event (put-mapping) within 12s];>,<RemoteTransportException[[node_sd4][127.0.0.1:34987][indices:data/write/index]]; nested: ProcessClusterEventTimeoutException[failed to process cluster event (put-mapping) within 12s];>,<ProcessClusterEventTimeoutException[failed to process cluster event (put-mapping) within 12s]>,<RemoteTransportException[[node_sd5][127.0.0.1:44465][indices:data/write/index]]; nested: ProcessClusterEventTimeoutException[failed to process cluster event (put-mapping) within 12s];>,<RemoteTransportException[[node_sd4][127.0.0.1:34987][indices:data/write/index]]; nested: ProcessClusterEventTimeoutException[failed to process cluster event (put-mapping) within 12s];>]
        at __randomizedtesting.SeedInfo.seed([E9AEC2E76FFDCDE8:6E07EEF385B763BC]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1519)
        at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1433)
        at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1416)
        at org.elasticsearch.index.reindex.DeleteByQueryBasicTests.testMultipleSources(DeleteByQueryBasicTests.java:283)
```

```
  1> [2019-05-07T19:39:10,142][WARN ][o.e.t.n.TestEventHandler ] [node_sm1] Slow execution on network thread [156 milliseconds]
  1> java.lang.RuntimeException: Slow exception on network thread
  1> 	at org.elasticsearch.transport.nio.TestEventHandler.maybeLogElapsedTime(TestEventHandler.java:212) [framework-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:123) [framework-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:397) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:246) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:172) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:129) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at java.lang.Thread.run(Thread.java:834) [?:?]
```

```
1> [2019-05-07T19:39:30,040][INFO ][o.e.i.r.DeleteByQueryBasicTests] [transport_client_node_sd4] Action Failed
  1> org.elasticsearch.transport.RemoteTransportException: [node_sd4][127.0.0.1:34987][indices:data/write/index]
  1> Caused by: org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-mapping) within 12s
  1> 	at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$0(MasterService.java:134) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
  1> 	at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$1(MasterService.java:133) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:687) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
  1> 	at java.lang.Thread.run(Thread.java:834) [?:?]
  1> [2019-05-07T19:39:29,904][INFO ][o.e.i.r.DeleteByQueryBasicTests] [transport_client_node_sm2] Action Failed
  1> org.elasticsearch.transport.RemoteTransportException: [node_sm2][127.0.0.1:41867][indices:data/write/index]
  1> Caused by: org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-mapping) within 12s
  1> 	at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$0(MasterService.java:134) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
  1> 	at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$1(MasterService.java:133) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:687) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
  1> 	at java.lang.Thread.run(Thread.java:834) [?:?]
  1> [2019-05-07T19:39:30,045][INFO ][o.e.i.r.DeleteByQueryBasicTests] [transport_client_node_sd4] Action Failed
  1> org.elasticsearch.transport.RemoteTransportException: [node_sd4][127.0.0.1:34987][indices:data/write/index]
  1> Caused by: org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-mapping) within 12s
  1> 	at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$0(MasterService.java:134) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
  1> 	at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$1(MasterService.java:133) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:687) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
  1> 	at java.lang.Thread.run(Thread.java:834) [?:?]
  1> [2019-05-07T19:39:30,221][INFO ][o.e.i.r.DeleteByQueryBasicTests] [node_sd5] Action Failed
  1> org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-mapping) within 12s
  1> 	at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$0(MasterService.java:134) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
  1> 	at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$1(MasterService.java:133) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:687) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
  1> 	at java.lang.Thread.run(Thread.java:834) [?:?]
  1> [2019-05-07T19:39:30,250][INFO ][o.e.i.r.DeleteByQueryBasicTests] [transport_client_node_sd5] Action Failed
  1> org.elasticsearch.transport.RemoteTransportException: [node_sd5][127.0.0.1:44465][indices:data/write/index]
  1> Caused by: org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-mapping) within 12s
  1> 	at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$0(MasterService.java:134) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
  1> 	at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$1(MasterService.java:133) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:687) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
  1> 	at java.lang.Thread.run(Thread.java:834) [?:?]
  1> [2019-05-07T19:39:30,378][INFO ][o.e.i.r.DeleteByQueryBasicTests] [transport_client_node_sd4] Action Failed
  1> org.elasticsearch.transport.RemoteTransportException: [node_sd4][127.0.0.1:34987][indices:data/write/index]
  1> Caused by: org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-mapping) within 12s
  1> 	at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$0(MasterService.java:134) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
  1> 	at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$1(MasterService.java:133) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:687) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
  1> 	at java.lang.Thread.run(Thread.java:834) [?:?]
```

## Frequency
Not often, last occurrence was 01/24/2019

**Comment by ywelsch** [comment]
The failure here shows that `indexRandom()`, which is used by many tests, failed because a mapping update took longer than 12 seconds (we randomize the timeout for these between 10 and 30 seconds). This is just an indication that the CI worker is horribly slow, and nothing specific to the test. Closing this as this is unfortunately not actionable here.
