### ISSUE TITLE
Unable to create snapshot backup repository in S3

### ISSUE THREAD

**Issue by ashish-kalbhor** [elastic/elasticsearch#41916]
**Elasticsearch version**:
```
# bin/elasticsearch --version
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Version: 6.5.4, Build: oss/tar/d2ef93d/2018-12-17T21:17:40.758843Z, JVM: 11.0.1
```

**Plugins installed**: 
```
# bin/elasticsearch-plugin list
repository-s3
```

**Description of the problem**:

When I try to create an Elasticsearch snapshot repository in S3 I get the following error:

```
$ curl -v -XPUT graylog-elasticsearch-client:9200/_snapshot/my_s3_repository -H "Content-Type: application/json" -d "{
>     \"type\": \"s3\",
>     \"settings\": {
>         \"bucket\": \"es-testbackup\",
>         \"compress\": true
>     }
> }"
> PUT /_snapshot/my_s3_repository HTTP/1.1
> User-Agent: curl/7.35.0
> Host: graylog-elasticsearch-client:9200
> Accept: */*
> Content-Type: application/json
> Content-Length: 101
> 
< HTTP/1.1 500 Internal Server Error
< content-type: application/json; charset=UTF-8
< content-length: 466
< 
{"error":{"root_cause":[{"type":"amazon_service_exception","reason":"amazon_service_exception: Internal Server Error (Service: null; Status Code: 500; Error Code: null; Request ID: null)"}],"type":"repository_exception","reason":"[my_s3_repository] cannot create blob store","caused_by":{"type":"amazon_service_exception","reason":"amazon_service_exception: Internal Server Error (Service: null; Status Code: 500; Error Code: null; Request ID: null)"}},"status":500}
```

**Steps to reproduce**:

 1. Set `s3.client.default.endpoint: "s3.us-west-1.amazonaws.com"` in elasticsearch.yml
 2. Set the s3 access keys in secure settings:

 ```
 # bin/elasticsearch-keystore list
 keystore.seed
 s3.client.default.access_key
 s3.client.default.secret_key
 ```
  Verified same AWS S3 keys work on awscli and I can upload using `aws s3 cp <>`

 3. Reload settings (just to be sure):

 ```
 $ curl -X POST "graylog-elasticsearch-client:9200/_nodes/reload_secure_settings"
 ```

 4. Create snapshot repository (fails with status code 500)

 
 ```
 $ curl -v -XPUT graylog-elasticsearch-client:9200/_snapshot/my_s3_repository -H "Content-Type: application/json" -d "{
 >     \"type\": \"s3\",
 >     \"settings\": {
 >         \"bucket\": \"es-testbackup\",
 >         \"compress\": true
 >     }
 > }"
 > PUT /_snapshot/my_s3_repository HTTP/1.1
 > User-Agent: curl/7.35.0
 > Host: graylog-elasticsearch-client:9200
 > Accept: */*
 > Content-Type: application/json
 > Content-Length: 101
 > 
 < HTTP/1.1 500 Internal Server Error
 < content-type: application/json; charset=UTF-8
 < content-length: 466
 < 
 {"error":{"root_cause":[{"type":"amazon_service_exception","reason":"amazon_service_exception: Internal Server Error (Service: null; Status Code: 500; Error Code: null; Request ID: null)"}],"type":"repository_exception","reason":"[my_s3_repository] cannot create blob store","caused_by":{"type":"amazon_service_exception","reason":"amazon_service_exception: Internal Server Error (Service: null; Status Code: 500; Error Code: null; Request ID: null)"}},"status":500}
 ```

**Provide logs (if relevant)**:

 I see this below stacktrace in ES logs:

 ```
 [2019-05-07T20:20:41,347][WARN ][r.suppressed             ] [graylog-elasticsearch-client-7c5c9956b9-7hdxj] path: /_snapshot/my_s3_repository, params: {repository=my_s3_repository}
org.elasticsearch.transport.RemoteTransportException: [graylog-elasticsearch-master-1][10.233.111.202:9300][cluster:admin/repository/put]
Caused by: org.elasticsearch.repositories.RepositoryException: [my_s3_repository] cannot create blob store
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.blobStore(BlobStoreRepository.java:336) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.repositories.s3.S3Repository.blobStore(S3Repository.java:258) ~[?:?]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:635) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.repositories.RepositoriesService.lambda$verifyRepository$2(RepositoriesService.java:218) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[elasticsearch-6.5.4.jar:6.5.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: amazon_service_exception: Internal Server Error (Service: null; Status Code: 500; Error Code: null; Request ID: null)
	at com.amazonaws.internal.EC2CredentialsUtils.handleErrorResponse(EC2CredentialsUtils.java:179) ~[?:?]
	at com.amazonaws.internal.EC2CredentialsUtils.readResource(EC2CredentialsUtils.java:126) ~[?:?]
	at com.amazonaws.auth.EC2CredentialsFetcher.fetchCredentials(EC2CredentialsFetcher.java:121) ~[?:?]
	at com.amazonaws.auth.EC2CredentialsFetcher.getCredentials(EC2CredentialsFetcher.java:82) ~[?:?]
	at com.amazonaws.auth.InstanceProfileCredentialsProvider.getCredentials(InstanceProfileCredentialsProvider.java:164) ~[?:?]
	at com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper.getCredentials(EC2ContainerCredentialsProviderWrapper.java:75) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.elasticsearch.repositories.s3.SocketAccess.doPrivileged(SocketAccess.java:42) ~[?:?]
	at org.elasticsearch.repositories.s3.S3Service$PrivilegedInstanceProfileCredentialsProvider.getCredentials(S3Service.java:184) ~[?:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1184) ~[?:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:774) ~[?:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:726) ~[?:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719) ~[?:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701) ~[?:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669) ~[?:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651) ~[?:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515) ~[?:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4443) ~[?:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4390) ~[?:?]
	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1354) ~[?:?]
	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1293) ~[?:?]
	at org.elasticsearch.repositories.s3.S3BlobStore.lambda$new$0(S3BlobStore.java:74) ~[?:?]
	at org.elasticsearch.repositories.s3.SocketAccess.lambda$doPrivilegedVoid$0(SocketAccess.java:57) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.elasticsearch.repositories.s3.SocketAccess.doPrivilegedVoid(SocketAccess.java:56) ~[?:?]
	at org.elasticsearch.repositories.s3.S3BlobStore.<init>(S3BlobStore.java:73) ~[?:?]
	at org.elasticsearch.repositories.s3.S3Repository.createBlobStore(S3Repository.java:251) ~[?:?]
	at org.elasticsearch.repositories.s3.S3Repository.createBlobStore(S3Repository.java:53) ~[?:?]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.blobStore(BlobStoreRepository.java:332) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.repositories.s3.S3Repository.blobStore(S3Repository.java:258) ~[?:?]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:635) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.repositories.RepositoriesService.lambda$verifyRepository$2(RepositoriesService.java:218) ~[elasticsearch-6.5.4.jar:6.5.4]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) ~[elasticsearch-6.5.4.jar:6.5.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
 ```

**Comment by original-brownbear** [comment]
@ashish-kalbhor 

do you get the same error if you remove the manual endpoint setting from the `elasticsearch.yml`?
It shouldn't be necessary to manually set the endpoint when using an actual AWS S3 bucket.

**Comment by original-brownbear** [comment]
Closing due to a lack of feedback, please reopen if still interested.

**Comment by ashish-kalbhor** [comment]
@original-brownbear thanks for looking into the issue! 
After carefully looking at the logs I realized I was setting the secure settings (s3 keys) only in ES data pods, and not the master/client pods. After adding these settings on all ES pods, it worked 🙂.
