### ISSUE TITLE
LicenseTribeTests failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#42004]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+multijob-unix-compatibility/os=redhat-8/155/console

```
java.lang.IllegalStateException: failed to load plugin class [org.elasticsearch.xpack.core.XPackPlugin]
	at __randomizedtesting.SeedInfo.seed([C243B7DC44DADFC4:A317BD6C5FD831E5]:0)
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:614)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:119)
	at org.elasticsearch.node.Node.<init>(Node.java:339)
	at org.elasticsearch.node.MockNode.<init>(MockNode.java:105)
	at org.elasticsearch.node.MockNode.<init>(MockNode.java:91)
	at org.elasticsearch.node.MockNode.<init>(MockNode.java:76)
	at org.elasticsearch.node.MockNode.<init>(MockNode.java:69)
	at org.elasticsearch.license.TribeTransportTestCase.testTribeSetup(TribeTransportTestCase.java:229)

       ...

	... 44 more
Caused by: org.apache.lucene.util.SetOnce$AlreadySetException: The object cannot be set twice!
	at org.apache.lucene.util.SetOnce.set(SetOnce.java:69)
	at org.elasticsearch.xpack.core.XPackPlugin.setSslService(XPackPlugin.java:158)
	at org.elasticsearch.xpack.core.XPackPlugin.<init>(XPackPlugin.java:144)
	... 49 more
```

Does not reproduce
```
 ./gradlew :x-pack:qa:tribe-tests-with-license:unitTest \
  -Dtests.seed=C243B7DC44DADFC4 \
  -Dtests.class=org.elasticsearch.license.LicenseTribeTests \
  -Dtests.method="testTribeSetup" \
  -Dtests.security.manager=true \
  -Dtests.locale=hu \
  -Dtests.timezone=America/Bahia_Banderas \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

I haven't muted this test as this is the only instance if it failing I can find

**Comment by davidkyle** [comment]
Another https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+multijob-unix-compatibility/os=redhat-8/157/console

**Comment by droberts195** [comment]
Another one on Red Hat 8, so it's looking more like it's not a coincidence: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+multijob-unix-compatibility/os=redhat-8/201/console

**Comment by tvernum** [comment]
It seems very strange that this is suddenly happening on 1 particular OS.

I've added additional logging for this test (but not the related Monitoring failure) which should give some indication of what is going on next time it fails.

**Comment by tvernum** [comment]
This issue is **on hold** because our RHEL8 builds were breaking unexpectedly, so they're not currently included in the unix matrix builds.

**Comment by jkakavas** [comment]
I'm closing this down as we're not using RHEL8 workers any more and this has not been observed in any other kinds of workers
