### ISSUE TITLE
AsyncTwoPhaseIndexerTests failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#42084]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/3534/testReport/junit/org.elasticsearch.xpack.core.indexing/AsyncTwoPhaseIndexerTests/testStateMachine/

```
Caused by: java.lang.AssertionError: 
Expected: <3>
     but: was <5>
	at __randomizedtesting.SeedInfo.seed([5119E6D95F3BD4B0]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.core.indexing.AsyncTwoPhaseIndexerTests$MockIndexer.doSaveState(AsyncTwoPhaseIndexerTests.java:113)
```

Does not reproduce
```
/gradlew :x-pack:plugin:core:test --tests "org.elasticsearch.xpack.core.indexing.AsyncTwoPhaseIndexerTests.testStateMachine" -Dtests.seed=5119E6D95F3BD4B0 -Dtests.security.manager=true -Dtests.locale=xog -Dtests.timezone=CTT -Dcompiler.java=12 -Druntime.java=11
```

**Comment by danielmitterdorfer** [comment]
This has failed again three times in the last few days:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian-9/458/console

Reproduction line: 

```
./gradlew :x-pack:plugin:core:test --tests "org.elasticsearch.xpack.core.indexing.AsyncTwoPhaseIndexerTests.testStateMachine" \
  -Dtests.seed=56843EF76319B4B0 \
  -Dtests.security.manager=true \
  -Dtests.locale=se-NO \
  -Dtests.timezone=Asia/Kashgar \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+multijob-darwin-compatibility/5/console

Reproduction line:

```
./gradlew :x-pack:plugin:core:test --tests "org.elasticsearch.xpack.core.indexing.AsyncTwoPhaseIndexerTests.testStateMachine" \
  -Dtests.seed=777CF6C4E3A7E6BA \
  -Dtests.security.manager=true \
  -Dtests.locale=en-AU \
  -Dtests.timezone=Europe/Istanbul \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=zulu11,nodes=immutable&&linux&&docker/4/console

reproduction line:

```
./gradlew :x-pack:plugin:core:test --tests "org.elasticsearch.xpack.core.indexing.AsyncTwoPhaseIndexerTests.testStateMachine" \
  -Dtests.seed=727FABDAF5E22A61 \
  -Dtests.security.manager=true \
  -Dtests.locale=en-SH \
  -Dtests.timezone=IET \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

All three of them have failed with the same message:

```
java.lang.AssertionError: 
Expected: <2>
     but: was <3>
	at __randomizedtesting.SeedInfo.seed([56843EF76319B4B0:3A2D42EC1B94AADE]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.core.indexing.AsyncTwoPhaseIndexerTests.testStateMachine(AsyncTwoPhaseIndexerTests.java:240)
[...]
```


I'll go ahead and will mute this test on `master`, `7.x` and `7.2`.
