### ISSUE TITLE
[CI] Reproducible Failure org.elasticsearch.index.analysis.PreBuiltAnalyzerTests.testThatInstancesAreCachedAndReused

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#42141]
Example failure https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/3558/testReport/junit/org.elasticsearch.index.analysis/PreBuiltAnalyzerTests/testThatInstancesAreCachedAndReused/

Reproduce line:
```
./gradlew :server:test --tests "org.elasticsearch.index.analysis.PreBuiltAnalyzerTests.testThatInstancesAreCachedAndReused" -Dtests.seed=AFD3FFC5D4359AB5 -Dtests.security.manager=true -Dtests.locale=tr-TR -Dtests.timezone=Europe/Isle_of_Man -Dcompiler.java=12 -Druntime.java=11
```

Fails with:

```
> Task :server:test


org.elasticsearch.index.analysis.PreBuiltAnalyzerTests > testThatInstancesAreCachedAndReused FAILED
    java.lang.AssertionError: expected not same
        at __randomizedtesting.SeedInfo.seed([AFD3FFC5D4359AB5:39CE17B9A3F9D456]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failSame(Assert.java:819)
        at org.junit.Assert.assertNotSame(Assert.java:798)
        at org.junit.Assert.assertNotSame(Assert.java:811)
        at org.elasticsearch.index.analysis.PreBuiltAnalyzerTests.testThatInstancesAreCachedAndReused(PreBuiltAnalyzerTests.java:74)
REPRODUCE WITH: ./gradlew :server:test --tests "org.elasticsearch.index.analysis.PreBuiltAnalyzerTests.testThatInstancesAreCachedAndReused" -Dtests.seed=AFD3FFC5D4359AB5 -Dtests.security.manager=true -Dtests.locale=tr-TR -Dtests.timezone=Europe/Isle_of_Man -Dcompiler.java=12 -Druntime.java=11

Suite: Test class org.elasticsearch.index.analysis.PreBuiltAnalyzerTests
  1> [2019-05-14T15:47:14,256][INFO ][o.e.e.NodeEnvironment    ] [testThatInstancesAreCachedAndReused] using [1] data paths, mounts [[/ (/dev/disk1s1)]], net usable_space [54.9gb], net total_space [465.6gb], types [apfs]
  1> [2019-05-14T15:47:14,273][INFO ][o.e.e.NodeEnvironment    ] [testThatInstancesAreCachedAndReused] heap size [512mb], compressed ordinary object pointers [true]
  1> [2019-05-14T15:47:14,277][INFO ][o.e.n.Node               ] [testThatInstancesAreCachedAndReused] node name [node_s_0], node ID [-ZfmpoF1RCSJyazyfgdGbQ], cluster name [single-node-cluster-CHILD_VM=[0]-CLUSTER_SEED=[-3261554140204322077]-HASH=[28873F4F32A25]]
  1> [2019-05-14T15:47:14,278][INFO ][o.e.n.Node               ] [testThatInstancesAreCachedAndReused] version[8.0.0], pid[19640], build[unknown/unknown/Unknown/Unknown], OS[Mac OS X/10.14.4/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/11/11+28]
  1> [2019-05-14T15:47:14,278][INFO ][o.e.n.Node               ] [testThatInstancesAreCachedAndReused] JVM home [/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home]
  1> [2019-05-14T15:47:14,279][INFO ][o.e.n.Node               ] [testThatInstancesAreCachedAndReused] JVM arguments [-Dcompiler.java=12, -Des.scripting.update.ctx_in_params=false, -Dgradle.dist.lib=/Users/brownbear/.gradle/wrapper/dists/gradle-5.4.1-all/3221gyojl5jsh0helicew7rwx/gradle-5.4.1/lib, -Dgradle.user.home=/Users/brownbear/.gradle, -Dgradle.worker.jar=/Users/brownbear/.gradle/caches/5.4.1/workerMain/gradle-worker.jar, -Djava.awt.headless=true, -Djna.nosys=true, -Dorg.gradle.native=false, -Druntime.java=11, -Dtests.artifact=server, -Dtests.gradle=true, -Dtests.locale=tr-TR, -Dtests.logger.level=WARN, -Dtests.security.manager=true, -Dtests.seed=AFD3FFC5D4359AB5, -Dtests.task=:server:test, -Dtests.timezone=Europe/Isle_of_Man, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/Users/brownbear/src/elasticsearch/server/build/heapdump, --illegal-access=warn, -esa, -Xms512m, -Xmx512m, -Dfile.encoding=UTF-8, -Djava.io.tmpdir=./temp, -Duser.country=DE, -Duser.language=en, -Duser.variant, -ea]
  1> [2019-05-14T15:47:14,291][INFO ][o.e.p.PluginsService     ] [testThatInstancesAreCachedAndReused] no modules loaded
  1> [2019-05-14T15:47:14,297][INFO ][o.e.p.PluginsService     ] [testThatInstancesAreCachedAndReused] loaded plugin [org.elasticsearch.test.InternalSettingsPlugin]
  1> [2019-05-14T15:47:14,298][INFO ][o.e.p.PluginsService     ] [testThatInstancesAreCachedAndReused] loaded plugin [org.elasticsearch.test.MockHttpTransport$TestPlugin]
  1> [2019-05-14T15:47:14,298][INFO ][o.e.p.PluginsService     ] [testThatInstancesAreCachedAndReused] loaded plugin [org.elasticsearch.transport.nio.MockNioTransportPlugin]
  1> [2019-05-14T15:47:16,441][INFO ][o.e.d.DiscoveryModule    ] [testThatInstancesAreCachedAndReused] using discovery type [zen] and seed hosts providers [settings]
  1> [2019-05-14T15:47:17,119][INFO ][o.e.n.Node               ] [testThatInstancesAreCachedAndReused] initialized
  1> [2019-05-14T15:47:17,119][INFO ][o.e.n.Node               ] [testThatInstancesAreCachedAndReused] starting ...
  1> [2019-05-14T15:47:17,162][INFO ][o.e.t.TransportService   ] [testThatInstancesAreCachedAndReused] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
  1> [2019-05-14T15:47:17,188][INFO ][o.e.c.c.Coordinator      ] [testThatInstancesAreCachedAndReused] setting initial configuration to VotingConfiguration{-ZfmpoF1RCSJyazyfgdGbQ}
  1> [2019-05-14T15:47:17,274][INFO ][o.e.c.s.MasterService    ] [node_s_0] elected-as-master ([1] nodes joined)[{node_s_0}{-ZfmpoF1RCSJyazyfgdGbQ}{6YK7sgeWQ6mt9F6L5y5N0A}{127.0.0.1}{127.0.0.1:9300} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 1, version: 1, reason: master node changed {previous [], current [{node_s_0}{-ZfmpoF1RCSJyazyfgdGbQ}{6YK7sgeWQ6mt9F6L5y5N0A}{127.0.0.1}{127.0.0.1:9300}]}
  1> [2019-05-14T15:47:17,306][INFO ][o.e.c.c.CoordinationState] [node_s_0] cluster UUID set to [hwiePMbLTJWhnJWduAeIHw]
  1> [2019-05-14T15:47:17,327][INFO ][o.e.c.s.ClusterApplierService] [node_s_0] master node changed {previous [], current [{node_s_0}{-ZfmpoF1RCSJyazyfgdGbQ}{6YK7sgeWQ6mt9F6L5y5N0A}{127.0.0.1}{127.0.0.1:9300}]}, term: 1, version: 1, reason: Publication{term=1, version=1}
  1> [2019-05-14T15:47:17,342][INFO ][o.e.n.Node               ] [testThatInstancesAreCachedAndReused] started
  1> [2019-05-14T15:47:17,359][INFO ][o.e.g.GatewayService     ] [node_s_0] recovered [0] indices into cluster_state
  1> [2019-05-14T15:47:17,509][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_s_0] adding template [one_shard_index_template] for index patterns [*]
  1> [2019-05-14T15:47:17,528][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_s_0] adding template [random-soft-deletes-template] for index patterns [*]
  1> [2019-05-14T15:47:17,541][INFO ][o.e.i.a.PreBuiltAnalyzerTests] [testThatInstancesAreCachedAndReused] before test
  1> [2019-05-14T15:47:17,553][INFO ][o.e.i.a.PreBuiltAnalyzerTests] [testThatInstancesAreCachedAndReused] after test
  2> REPRODUCE WITH: ./gradlew :server:test --tests "org.elasticsearch.index.analysis.PreBuiltAnalyzerTests.testThatInstancesAreCachedAndReused" -Dtests.seed=AFD3FFC5D4359AB5 -Dtests.security.manager=true -Dtests.locale=tr-TR -Dtests.timezone=Europe/Isle_of_Man -Dcompiler.java=12 -Druntime.java=11
  2> java.lang.AssertionError: expected not same
        at __randomizedtesting.SeedInfo.seed([AFD3FFC5D4359AB5:39CE17B9A3F9D456]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failSame(Assert.java:819)
        at org.junit.Assert.assertNotSame(Assert.java:798)
        at org.junit.Assert.assertNotSame(Assert.java:811)
        at org.elasticsearch.index.analysis.PreBuiltAnalyzerTests.testThatInstancesAreCachedAndReused(PreBuiltAnalyzerTests.java:74)
  1> [2019-05-14T15:47:17,596][INFO ][o.e.n.Node               ] [suite] stopping ...
  1> [2019-05-14T15:47:17,610][INFO ][o.e.n.Node               ] [suite] stopped
  1> [2019-05-14T15:47:17,610][INFO ][o.e.n.Node               ] [suite] closing ...
  1> [2019-05-14T15:47:17,623][INFO ][o.e.n.Node               ] [suite] closed
  2> NOTE: leaving temporary files on disk at: /Users/brownbear/src/elasticsearch/server/build/testrun/test/temp/org.elasticsearch.index.analysis.PreBuiltAnalyzerTests_AFD3FFC5D4359AB5-001
  2> NOTE: test params are: codec=Asserting(Lucene80), sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@7889da11), locale=tr-TR, timezone=Europe/Isle_of_Man
  2> NOTE: Mac OS X 10.14.4 x86_64/Oracle Corporation 11 (64-bit)/cpus=8,threads=1,free=458348344,total=536870912
  2> NOTE: All tests run in this JVM: [PreBuiltAnalyzerTests]

1 test completed, 1 failed

Tests with failures:
 - org.elasticsearch.index.analysis.PreBuiltAnalyzerTests.testThatInstancesAreCachedAndReused

```

**Comment by original-brownbear** [comment]
Seems this was fixed today by 32660118f4238a0047cf01ffd6be634034dba90c -> closing
