### ISSUE TITLE
Throwable: Self-suppression not permitted exception in Low Level Java Client

### ISSUE THREAD

**Issue by Jamalarm** [elastic/elasticsearch#42223]
**Elasticsearch version** 7.0.1

**Plugins installed**: None - Running on managed Elastic Cloud

**JVM version** (`java -version`): Unknown - Running on managed Elastic Cloud

**OS version** (`uname -a` if on a Unix-like system): Unknown - Running on managed Elastic Cloud

**Description of the problem including expected versus actual behavior**:

The low-level Java client will occasionally attempt to suppress an exception with itself, causing an `IllegalArgumentException` to be thrown out of the client. The method in question is at `org.elasticsearch.client.RestClient#addSuppressedException`. It contains a guard condition to make sure that `suppressedException != null` but it doesn't guard against `suppressedException == currentException` which gets through and causes `Throwable` to throw an exception, ironically.

Could you please add a guard condition in there to make sure the client is not trying to suppress an exception into itself?

**Steps to reproduce**:

This is quite difficult to reproduce unfortunately. The cases we have seen it happen are all specific to the managed Elastic Cloud.

1. Set up a single node cluster on managed Elastic Cloud
1. Have an app running that is making frequent calls to ES via the Java client (in a loop or something, in our case it's a Project Reactor pipeline)
1. Put the cluster into **maintenance mode** via the Elastic Cloud management UI. This causes all requests to the managed cluster to be rejected with an error informing you the cluster is in maintenance mode.
1. The second time a request is made (and rejected) via the low level rest client, the error will be thrown as the client attempts to suppress an exception into itself.

**Provide logs (if relevant)**:

```
16:16:39.606 [     pool-6-thread-1] ERROR  o.a.h.i.n.c.InternalHttpAsyncClient {} {} - I/O reactor terminated abnormally
org.apache.http.nio.reactor.IOReactorException: I/O dispatch worker terminated abnormally
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:359)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Self-suppression not permitted
        at java.base/java.lang.Throwable.addSuppressed(Throwable.java:1025)
        at org.elasticsearch.client.RestClient.addSuppressedException(RestClient.java:489)
        at org.elasticsearch.client.RestClient.access$1400(RestClient.java:95)
        at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.trackFailure(RestClient.java:587)
        at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:579)
        at org.elasticsearch.client.RestClient$1.failed(RestClient.java:333)
        at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionFailed(DefaultClientExchangeHandlerImpl.java:101)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:426)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.exception(HttpAsyncRequestExecutor.java:163)
        at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:276)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
        ... 1 common frames omitted
```

**Comment by Jamalarm** [comment]
This one is still hitting us, would you guys accept a PR from us to fix it? it should just be a single if statement around the `Throwable.suppress()` call.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
