### ISSUE TITLE
Test failure: org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealmTests.testCacheSettings

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#42267]
```
org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealmTests > testCacheSettings FAILED
    java.lang.IllegalArgumentException: unknown hash function [sha256]
        at __randomizedtesting.SeedInfo.seed([183260F6BD6AF4D7:455D85248CE5C0FB]:0)
        at org.elasticsearch.xpack.core.security.authc.support.Hasher.resolve(Hasher.java:454)
        at org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealm.<init>(CachingUsernamePasswordRealm.java:40)
        at org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealmTests$1.<init>(CachingUsernamePasswordRealmTests.java:81)
        at org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealmTests.testCacheSettings(CachingUsernamePasswordRealmTests.java:81)
```
It reproduces ! (against master / commit: 570e8edc1e25f1c5197307f40fd4f73e0950620f) 
```
./gradlew :x-pack:plugin:security:test --tests "org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealmTests.testCacheSettings" -Dtests.seed=183260F6BD6AF4D7 -Dtests.security.manager=true -Dtests.locale=shi-Latn-MA -Dtests.timezone=Asia/Kathmandu -Dcompiler.java=12 -Druntime.java=11
```

**Comment by talevy** [comment]
I'm piggybacking off this test issue to include this failure

```
org.elasticsearch.xpack.security.authc.file.FileRealmTests > testAuthenticateCaching FAILED
    java.lang.IllegalArgumentException: unknown hash function [sha256]
        at __randomizedtesting.SeedInfo.seed([59B2C0D8C29239CD:B20A3FBF3D6748A6]:0)
        at org.elasticsearch.xpack.core.security.authc.support.Hasher.resolve(Hasher.java:454)
        at org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealm.<init>(CachingUsernamePasswordRealm.java:40)
        at org.elasticsearch.xpack.security.authc.file.FileRealm.<init>(FileRealm.java:30)
        at org.elasticsearch.xpack.security.authc.file.FileRealmTests.testAuthenticateCaching(FileRealmTests.java:103)
REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test --tests "org.elasticsearch.xpack.security.authc.file.FileRealmTests.testAuthenticateCaching" -Dtests.seed=59B2C0D8C29239CD -Dtests.security.manager=true -Dtests.locale=nl-SX -Dtests.timezone=America/Regina -Dcompiler.java=12 -Druntime.java=12
```

muting both here #42304
