### ISSUE TITLE
RollupIndexerIndexingTests testSimpleDateHistoWithOverlappingDelay 7.x failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#42285]
A reproducible failure in the test clean up on the 7.x branch. Does not reproduce on master

```
java.lang.AssertionError: unexpected warning headers expected null, but was:<[299 Elasticsearch-7.2.0-SNAPSHOT-e838a8b "[interval] on [date_histogram] is deprecated, use [fixed_interval] or [calendar_interval] in the future."]>
	at __randomizedtesting.SeedInfo.seed([6AB4996A411D9CD3:90B9EF337683567A]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at org.elasticsearch.test.ESTestCase.ensureNoWarnings(ESTestCas
```

```
./gradlew :x-pack:plugin:rollup:test --tests "org.elasticsearch.xpack.rollup.job.RollupIndexerIndexingTests.testSimpleDateHistoWithOverlappingDelay" -Dtests.seed=6AB4996A411D9CD3 -Dtests.security.manager=true -Dtests.locale=es-UY -Dtests.timezone=America/Tijuana -Dcompiler.java=12 -Druntime.java=8
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/13832/testReport/junit/org.elasticsearch.xpack.rollup.job/RollupIndexerIndexingTests/testSimpleDateHistoWithOverlappingDelay/

**Comment by davidkyle** [comment]
Closing. This has been fixed in 0449869511dc75c399a3e60a581ae3d93cf77b74
Time to rebase my PR
