### ISSUE TITLE
[CI] ZenDiscoveryIT.testNodeFailuresAreProcessedOnce fails

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#42345]
## Reproduction line 
does not reproduce locally
```
./gradlew :server:integTest --tests "org.elasticsearch.cluster.coordination.ZenDiscoveryIT.testNodeFailuresAreProcessedOnce" -Dtests.seed=CAC4A2E7E349B590 -Dtests.security.manager=true -Dtests.locale=fr-NC -Dtests.timezone=Asia/Ulaanbaatar -Dcompiler.java=12 -Druntime.java=11
```

## Example relevant log:
```
java.lang.AssertionError: 
Expected: (<1> or <2>)
     but: was <0>
	at __randomizedtesting.SeedInfo.seed([CAC4A2E7E349B590:2A7AB0418BCD0AD4]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.cluster.coordination.ZenDiscoveryIT.testNodeFailuresAreProcessedOnce(ZenDiscoveryIT.java:129)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
```

```
[2019-05-22T06:19:25,971][WARN ][o.e.c.NodeConnectionsService] [node_t0] failed to connect to {node_t2}{m0223nFaR4mX7YXQD97i-Q}{4Vq_y6ljS7OjYhJdofOckw}{127.0.0.1}{127.0.0.1:38751} (tried [1] times)
org.elasticsearch.transport.ConnectTransportException: [node_t2][127.0.0.1:38751] connect_exception
	at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onFailure(TcpTransport.java:972) ~[main/:?]
	at org.elasticsearch.action.ActionListener.lambda$toBiConsumer$3(ActionListener.java:161) ~[main/:?]
	at org.elasticsearch.common.concurrent.CompletableContext.lambda$addListener$0(CompletableContext.java:42) ~[elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at org.elasticsearch.common.concurrent.CompletableContext.completeExceptionally(CompletableContext.java:57) ~[elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.SocketChannelContext.connect(SocketChannelContext.java:120) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.EventHandler.handleConnect(EventHandler.java:97) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.transport.nio.TestEventHandler.handleConnect(TestEventHandler.java:97) ~[framework-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.attemptConnect(NioSelector.java:405) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.setUpNewChannels(NioSelector.java:422) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.preSelect(NioSelector.java:261) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:153) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:129) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779) ~[?:?]
	at org.elasticsearch.nio.SocketChannelContext.connect(SocketChannelContext.java:117) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	... 8 more
```

```
[2019-05-22T06:19:30,196][WARN ][o.e.c.c.Coordinator      ] [node_tm0] failed to validate incoming join request from node [{node_t1}{QJFAdnDbQS6toxmBVzJkzw}{Uh15CadwS2-5yHZkysjo2g}{127.0.0.1}{127.0.0.1:39919}]
org.elasticsearch.transport.RemoteTransportException: [node_t1][127.0.0.1:39919][internal:cluster/coordination/join/validate]
Caused by: java.lang.IllegalArgumentException: Unknown NamedWriteable [org.elasticsearch.cluster.metadata.MetaData$Custom][custom_md]
	at org.elasticsearch.common.io.stream.NamedWriteableRegistry.getReader(NamedWriteableRegistry.java:112) ~[main/:?]
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:45) ~[main/:?]
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:39) ~[main/:?]
	at org.elasticsearch.cluster.metadata.MetaData.readFrom(MetaData.java:899) ~[main/:?]
	at org.elasticsearch.cluster.ClusterState.readFrom(ClusterState.java:764) ~[main/:?]
	at org.elasticsearch.cluster.coordination.ValidateJoinRequest.readFrom(ValidateJoinRequest.java:40) ~[main/:?]
	at org.elasticsearch.common.io.stream.Streamable.lambda$newWriteableReader$0(Streamable.java:51) ~[main/:?]
	at org.elasticsearch.transport.RequestHandlerRegistry.newRequest(RequestHandlerRegistry.java:56) ~[main/:?]
	at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:179) ~[main/:?]
	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:121) ~[main/:?]
	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:105) ~[main/:?]
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:660) ~[main/:?]
	at org.elasticsearch.transport.TcpTransport.consumeNetworkReads(TcpTransport.java:684) ~[main/:?]
	at org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:246) ~[framework-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:215) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:47) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:119) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:121) ~[framework-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:397) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:246) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:172) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:129) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Occurrence seems rare, not muting yet.

**Comment by ywelsch** [comment]
Can you link to the build failure please? :)

**Comment by ywelsch** [comment]
The warning log line "failed to validate incoming join request from node" is from another test btw., not the test that failed.
Anyway, I've removed the test, as it was not testing the thing it was set out to test.
