### ISSUE TITLE
[CI ] IndexRequest serialization trips Asserts during rolling upgrade test

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#42487]
The X-Pack rolling-upgrade tests from 6.0.1 to 6.8 are failing
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+bwc-tests/70/
```
./gradlew :x-pack:qa:rolling-upgrade:with-system-key:v6.0.1#bwcTest
```

because they are tripping this seqNo assertion in `IndexRequest.writeTo`

https://github.com/elastic/elasticsearch/blob/v6.8.0/server/src/main/java/org/elasticsearch/action/index/IndexRequest.java#L656-L661
```
        if (out.getVersion().onOrAfter(Version.V_6_6_0)) {
            out.writeZLong(ifSeqNo);
            out.writeVLong(ifPrimaryTerm);
        } else if (ifSeqNo != UNASSIGNED_SEQ_NO || ifPrimaryTerm != UNASSIGNED_PRIMARY_TERM) {
            assert false : "setIfMatch [" + ifSeqNo + "], currentDocTem [" + ifPrimaryTerm + "]";
            throw new IllegalStateException(
                "sequence number based compare and write is not supported until all nodes are on version 7.0 or higher. " +
                    "Stream version [" + out.getVersion() + "]");
        }
```

- The old cluster (v6.0.1) works fine.
- Then we upgrade node-0 to 6.8.x, this seems to be fine
- Then we upgrade node-1 to 6.8.x, this causes node-0 to fail

```
[2019-05-24T12:16:10,245][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [upgraded-node-0] fatal error in thread [elasticsearch[upgraded-node-0][write][T
#6]], exiting
java.lang.AssertionError: setIfMatch [717], currentDocTem [2]
        at org.elasticsearch.action.index.IndexRequest.writeTo(IndexRequest.java:657) ~[elasticsearch-6.8.1-SNAPSHOT.jar:6.8.1-SNAPSHOT]
        at org.elasticsearch.action.DocWriteRequest.writeDocumentRequest(DocWriteRequest.java:244) ~[elasticsearch-6.8.1-SNAPSHOT.jar:6.8.1-SNAPSHOT]
        at org.elasticsearch.action.bulk.BulkItemRequest.writeTo(BulkItemRequest.java:110) ~[elasticsearch-6.8.1-SNAPSHOT.jar:6.8.1-SNAPSHOT]
        at org.elasticsearch.action.bulk.BulkShardRequest.writeTo(BulkShardRequest.java:73) ~[elasticsearch-6.8.1-SNAPSHOT.jar:6.8.1-SNAPSHOT]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$ConcreteShardRequest.writeTo(TransportReplicationAction.java:1285) ~[elasti
csearch-6.8.1-SNAPSHOT.jar:6.8.1-SNAPSHOT]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$ConcreteReplicaRequest.writeTo(TransportReplicationAction.java:1341) ~[elas
ticsearch-6.8.1-SNAPSHOT.jar:6.8.1-SNAPSHOT]
```

**Comment by ywelsch** [comment]
Duplicates #40841

@jakelandis These watcher tests should perhaps be muted.

**Comment by jakelandis** [comment]
@ywelsch - I found the root cause of the failure and logged a new issue: https://github.com/elastic/elasticsearch/issues/42561  would you mind taking a look ? (The issue isn't specific to Watcher)

I am advocating commenting out the assertion over at https://github.com/elastic/elasticsearch/issues/40841#issuecomment-496025324 instead of muting these tests.
