### ISSUE TITLE
[CI] PemTrustConfigTests.testTrustConfigReloadsFileContents failure

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#42509]
## Example build failure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+periodic/587/console

## Reproduction line 
Reproduces locally
```
./gradlew :libs:elasticsearch-ssl-config:test --tests "org.elasticsearch.common.ssl.PemTrustConfigTests.testTrustConfigReloadsFileContents" \
  -Dtests.seed=6E5A773651EDE1AE \
  -Dtests.security.manager=true \
  -Dtests.locale=de-CH \
  -Dtests.timezone=Australia/Currie \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

## Example relevant log:
```
13:16:43 org.elasticsearch.common.ssl.PemTrustConfigTests > testTrustConfigReloadsFileContents FAILED
13:16:43     junit.framework.AssertionFailedError: Unexpected exception type, expected SslConfigException but got java.lang.ArrayIndexOutOfBoundsException: 0
13:16:43         at __randomizedtesting.SeedInfo.seed([6E5A773651EDE1AE:58DDCEDF0604B2E6]:0)
13:16:43         at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2700)
13:16:43         at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2689)
13:16:43         at org.elasticsearch.common.ssl.PemTrustConfigTests.assertInvalidFileFormat(PemTrustConfigTests.java:132)
13:16:43         at org.elasticsearch.common.ssl.PemTrustConfigTests.testTrustConfigReloadsFileContents(PemTrustConfigTests.java:110)
13:16:43 
13:16:43         Caused by:
13:16:43         java.lang.ArrayIndexOutOfBoundsException: 0
13:16:43             at sun.security.pkcs.ContentInfo.<init>(ContentInfo.java:135)
13:16:43             at sun.security.pkcs.PKCS7.parse(PKCS7.java:181)
13:16:43             at sun.security.pkcs.PKCS7.parse(PKCS7.java:154)
13:16:43             at sun.security.pkcs.PKCS7.<init>(PKCS7.java:136)
13:16:43             at sun.security.provider.X509Factory.parseX509orPKCS7Cert(X509Factory.java:460)
13:16:43             at sun.security.provider.X509Factory.engineGenerateCertificates(X509Factory.java:356)
13:16:43             at java.security.cert.CertificateFactory.generateCertificates(CertificateFactory.java:462)
13:16:43             at org.elasticsearch.common.ssl.PemUtils.readCertificates(PemUtils.java:596)
13:16:43             at org.elasticsearch.common.ssl.PemTrustConfig.loadCertificates(PemTrustConfig.java:83)
13:16:43             at org.elasticsearch.common.ssl.PemTrustConfig.createTrustManager(PemTrustConfig.java:73)
13:16:43             at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2695)
13:16:43             ... 3 more
13:16:43 REPRODUCE WITH: ./gradlew :libs:elasticsearch-ssl-config:test --tests "org.elasticsearch.common.ssl.PemTrustConfigTests.testTrustConfigReloadsFileContents" -Dtests.seed=6E5A773651EDE1AE -Dtests.security.manager=true -Dtests.locale=de-CH -Dtests.timezone=Australia/Currie -Dcompiler.java=12 -Druntime.java=8
13:16:43 
13:16:43 Suite: Test class org.elasticsearch.common.ssl.PemTrustConfigTests
13:16:43   1> [2019-05-24T21:16:41,801][INFO ][o.e.c.s.PemTrustConfigTests] [testBadFileFormatFails] before test
13:16:43   1> [2019-05-24T21:16:42,548][INFO ][o.e.c.s.PemTrustConfigTests] [testBadFileFormatFails] after test
13:16:43   1> [2019-05-24T21:16:42,594][INFO ][o.e.c.s.PemTrustConfigTests] [testBuildTrustConfigFromSinglePemFile] before test
13:16:43   1> [2019-05-24T21:16:42,627][INFO ][o.e.c.s.PemTrustConfigTests] [testBuildTrustConfigFromSinglePemFile] after test
13:16:43   1> [2019-05-24T21:16:42,637][INFO ][o.e.c.s.PemTrustConfigTests] [testMissingFileFailsWithMeaningfulMessage] before test
13:16:43   1> [2019-05-24T21:16:42,657][INFO ][o.e.c.s.PemTrustConfigTests] [testMissingFileFailsWithMeaningfulMessage] after test
13:16:43   1> [2019-05-24T21:16:42,667][INFO ][o.e.c.s.PemTrustConfigTests] [testBuildTrustConfigFromMultiplePemFiles] before test
13:16:43   1> [2019-05-24T21:16:42,686][INFO ][o.e.c.s.PemTrustConfigTests] [testBuildTrustConfigFromMultiplePemFiles] after test
13:16:43   1> [2019-05-24T21:16:42,710][INFO ][o.e.c.s.PemTrustConfigTests] [testEmptyFileFails] before test
13:16:43   1> [2019-05-24T21:16:42,716][INFO ][o.e.c.s.PemTrustConfigTests] [testEmptyFileFails] failure
13:16:43   1> org.elasticsearch.common.ssl.SslConfigException: failed to parse any certificates from [/var/lib/jenkins/workspace/elastic+elasticsearch+7.x+periodic/libs/ssl-config/build/testrun/test/temp/org.elasticsearch.common.ssl.PemTrustConfigTests_6E5A773651EDE1AE-001/ca-002.crt]
13:16:43   1> 	at org.elasticsearch.common.ssl.PemUtils.readCertificates(PemUtils.java:598) ~[main/:?]
13:16:43   1> 	at org.elasticsearch.common.ssl.PemTrustConfig.loadCertificates(PemTrustConfig.java:83) ~[main/:?]
13:16:43   1> 	at org.elasticsearch.common.ssl.PemTrustConfig.createTrustManager(PemTrustConfig.java:73) ~[main/:?]
13:16:43   1> 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2695) ~[lucene-test-framework-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:05]
13:16:43   1> 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2689) ~[lucene-test-framework-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:05]
13:16:43   1> 	at org.elasticsearch.common.ssl.PemTrustConfigTests.assertEmptyFile(PemTrustConfigTests.java:125) [test/:?]
13:16:43   1> 	at org.elasticsearch.common.ssl.PemTrustConfigTests.testEmptyFileFails(PemTrustConfigTests.java:70) [test/:?]
13:16:43   1> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
13:16:43   1> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
13:16:43   1> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
13:16:43   1> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49) [lucene-test-framework-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:05]
13:16:43   1> 	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) [lucene-test-framework-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:05]
13:16:43   1> 	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48) [lucene-test-framework-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:05]
13:16:43   1> 	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) [lucene-test-framework-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:05]
13:16:43   1> 	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) [lucene-test-framework-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:05]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) [lucene-test-framework-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:05]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41) [lucene-test-framework-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:05]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53) [lucene-test-framework-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:05]
13:16:43   1> 	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) [lucene-test-framework-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:05]
13:16:43   1> 	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) [lucene-test-framework-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:05]
13:16:43   1> 	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54) [lucene-test-framework-8.1.0.jar:8.1.0 dbe5ed0b2f17677ca6c904ebae919363f2d36a0a - ishan - 2019-05-09 19:34:05]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368) [randomizedtesting-runner-2.7.1.jar:?]
13:16:43   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
13:16:43   1> [2019-05-24T21:16:42,735][INFO ][o.e.c.s.PemTrustConfigTests] [testEmptyFileFails] after test
13:16:43   1> [2019-05-24T21:16:42,754][INFO ][o.e.c.s.PemTrustConfigTests] [testOneMissingFileFailsWithMeaningfulMessageEvenIfOtherFileExist] before test
13:16:43   1> [2019-05-24T21:16:42,763][INFO ][o.e.c.s.PemTrustConfigTests] [testOneMissingFileFailsWithMeaningfulMessageEvenIfOtherFileExist] after test
13:16:43   1> [2019-05-24T21:16:42,790][INFO ][o.e.c.s.PemTrustConfigTests] [testTrustConfigReloadsFileContents] before test
13:16:43   1> [2019-05-24T21:16:42,829][INFO ][o.e.c.s.PemTrustConfigTests] [testTrustConfigReloadsFileContents] after test
13:16:43   2> REPRODUCE WITH: ./gradlew :libs:elasticsearch-ssl-config:test --tests "org.elasticsearch.common.ssl.PemTrustConfigTests.testTrustConfigReloadsFileContents" -Dtests.seed=6E5A773651EDE1AE -Dtests.security.manager=true -Dtests.locale=de-CH -Dtests.timezone=Australia/Currie -Dcompiler.java=12 -Druntime.java=8
13:16:43   2> junit.framework.AssertionFailedError: Unexpected exception type, expected SslConfigException but got java.lang.ArrayIndexOutOfBoundsException: 0
13:16:43         at __randomizedtesting.SeedInfo.seed([6E5A773651EDE1AE:58DDCEDF0604B2E6]:0)
13:16:43         at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2700)
13:16:43         at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2689)
13:16:43         at org.elasticsearch.common.ssl.PemTrustConfigTests.assertInvalidFileFormat(PemTrustConfigTests.java:132)
13:16:43         at org.elasticsearch.common.ssl.PemTrustConfigTests.testTrustConfigReloadsFileContents(PemTrustConfigTests.java:110)
13:16:43 
13:16:43         Caused by:
13:16:43         java.lang.ArrayIndexOutOfBoundsException: 0
13:16:43             at sun.security.pkcs.ContentInfo.<init>(ContentInfo.java:135)
13:16:43             at sun.security.pkcs.PKCS7.parse(PKCS7.java:181)
13:16:43             at sun.security.pkcs.PKCS7.parse(PKCS7.java:154)
13:16:43             at sun.security.pkcs.PKCS7.<init>(PKCS7.java:136)
13:16:43             at sun.security.provider.X509Factory.parseX509orPKCS7Cert(X509Factory.java:460)
13:16:43             at sun.security.provider.X509Factory.engineGenerateCertificates(X509Factory.java:356)
13:16:43             at java.security.cert.CertificateFactory.generateCertificates(CertificateFactory.java:462)
13:16:43             at org.elasticsearch.common.ssl.PemUtils.readCertificates(PemUtils.java:596)
13:16:43             at org.elasticsearch.common.ssl.PemTrustConfig.loadCertificates(PemTrustConfig.java:83)
13:16:43             at org.elasticsearch.common.ssl.PemTrustConfig.createTrustManager(PemTrustConfig.java:73)
13:16:43             at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2695)
13:16:43             ... 3 more
13:16:43   2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+7.x+periodic/libs/ssl-config/build/testrun/test/temp/org.elasticsearch.common.ssl.PemTrustConfigTests_6E5A773651EDE1AE-001
13:16:43   2> NOTE: test params are: codec=Asserting(Lucene80): {}, docValues:{}, maxPointsInLeafNode=473, maxMBSortInHeap=5.857700392149913, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@29f7eaf6), locale=de-CH, timezone=Australia/Currie
13:16:43   2> NOTE: Linux 5.0.16-200.fc29.x86_64 amd64/Oracle Corporation 1.8.0_212 (64-bit)/cpus=16,threads=1,free=479454304,total=514850816
13:16:43   2> NOTE: All tests run in this JVM: [PemTrustConfigTests]
```

**Comment by matriv** [comment]
Muted test with 56677f69cf34e26912a5e9e7aca7d6f7e80c7f37 on `7.x`
