### ISSUE TITLE
[CI] GoogleCloudStorageBlobStoreRepositoryTests.testSnapshotAndRestore failure

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#42519]
## Example build failure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.1+intake/87/console

## Reproduction line 
Doesn't reproduces locally
```
./gradlew :plugins:repository-gcs:test --tests "org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStoreRepositoryTests.testSnapshotAndRestore" \
  -Dtests.seed=2B52BC99A06777E8 \
  -Dtests.security.manager=true \
  -Dtests.locale=ja-JP-u-ca-japanese-x-lvariant-JP \
  -Dtests.timezone=America/Creston \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

## Example relevant log:
```
14:11:09   1> [0001-05-24T05:11:06,556][INFO ][o.e.r.g.GoogleCloudStorageBlobStoreRepositoryTests] [testSnapshotAndRestore] -->  create random index tzbqmdctx with 465 records
14:11:09   1> [0001-05-24T05:11:06,562][INFO ][o.e.r.g.GoogleCloudStorageBlobStoreRepositoryTests] [testSnapshotAndRestore] Index [465] docs async: [false] bulk: [true] partitions [6]
14:11:09   1> [0001-05-24T05:11:06,565][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_s1] [tzbqmdctx] creating index, cause [auto(bulk api)], templates [random_index_template], shards [2]/[1], mappings []
14:11:09   1> [0001-05-24T05:11:06,643][INFO ][o.e.c.m.MetaDataMappingService] [node_s1] [tzbqmdctx/I4Nzg9T7S-C3ptAChlJ3Lw] create_mapping [tzbqmdctx]
14:11:09   1> [0001-05-24T05:11:06,828][INFO ][o.e.r.g.GoogleCloudStorageBlobStoreRepositoryTests] [testSnapshotAndRestore] -->  create snapshot x:o
14:11:09   1> [0001-05-24T05:11:06,840][WARN ][o.e.s.SnapshotsService   ] [node_s1] failed to create snapshot [o/SCE0LbxMTJGiWKYoMazshA]
14:11:09   1> org.elasticsearch.snapshots.InvalidSnapshotNameException: [x:o] Invalid snapshot name [o], snapshot with the same name already exists
14:11:09   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.initializeSnapshot(BlobStoreRepository.java:387) ~[elasticsearch-7.1.1-SNAPSHOT.jar:7.1.1-SNAPSHOT]
14:11:09   1> 	at org.elasticsearch.snapshots.SnapshotsService$2.doRun(SnapshotsService.java:413) [elasticsearch-7.1.1-SNAPSHOT.jar:7.1.1-SNAPSHOT]
14:11:09   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) [elasticsearch-7.1.1-SNAPSHOT.jar:7.1.1-SNAPSHOT]
14:11:09   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.1.1-SNAPSHOT.jar:7.1.1-SNAPSHOT]
14:11:09   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
14:11:09   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
14:11:09   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

Not muting for the moment, I found just one more failure like that.

**Comment by original-brownbear** [comment]
The fix for this is incoming in #42511
