### ISSUE TITLE
[CI] BuildExamplePluginsIT fails on MacOS

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#42607]
**Build failure**

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+multijob-darwin-compatibility/9/

**Failure output**

```
Starting process 'Gradle Test Executor 7'. Working directory: /private/var/folders/48/bbwtd6jn6dd63rmw5xmjy92r0000ln/T/junit17051616529802824665/build/testrun/integTestRunner Command: /var/lib/jenkins/.java/java8/bin/java -Dcompiler.java=12 -Des.scripting.update.ctx_in_params=false -Dexternal.address=127.0.0.1:59689 -Dgradle.dist.lib=/private/var/lib/jenkins/.gradle/wrapper/dists/gradle-5.4.1-all/3221gyojl5jsh0helicew7rwx/gradle-5.4.1/lib -Dgradle.user.home=/private/var/folders/48/bbwtd6jn6dd63rmw5xmjy92r0000ln/T/.gradle-test-kit-jenkins -Dgradle.worker.jar=/private/var/folders/48/bbwtd6jn6dd63rmw5xmjy92r0000ln/T/.gradle-test-kit-jenkins/caches/5.4.1/workerMain/gradle-worker.jar -Djava.awt.headless=true -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -Djna.nosys=true -Dorg.gradle.native=false -Druntime.java=8 -Dtests.artifact=junit17051616529802824665 -Dtests.cluster=[::1]:59701 -Dtests.gradle=true -Dtests.logger.level=WARN -Dtests.rest.cluster=[::1]:59703,127.0.0.1:59705 -Dtests.rest.load_packaged=false -Dtests.security.manager=true -Dtests.seed=1EC396FFE6946BF9 -Dtests.task=:integTestRunner -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/private/var/folders/48/bbwtd6jn6dd63rmw5xmjy92r0000ln/T/junit17051616529802824665/build/heapdump -esa -Xms512m -Xmx512m -Dfile.encoding=UTF-8 -Djava.io.tmpdir=./temp -Duser.country=US -Duser.language=en -Duser.variant -ea -cp /private/var/folders/48/bbwtd6jn6dd63rmw5xmjy92r0000ln/T/.gradle-test-kit-jenkins/caches/5.4.1/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 7'
Successfully started process 'Gradle Test Executor 7'
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Error occurred during initialization of VM
java.lang.InternalError: Could not create SecurityManager: worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager
	at sun.misc.Launcher.<init>(Launcher.java:103)
	at sun.misc.Launcher.<clinit>(Launcher.java:54)
	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1451)
	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1436)
```

**Reproducability**

The Gradle command that has been run is `./gradlew --parallel precommit buildBwc`. The failure only happens on the `7.2` builds in CI; I could not spot any problems on other builds nor could I reproduce this locally.

**Analysis**

The root cause is that the fully qualified name of the security manager class is wrong. Instead of `worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager` it should be `org.gradle.process.internal.worker.child.BootstrapSecurityManager`.

**Comment by mark-vieira** [comment]
This test has been muted and will likely be either completely reworked or removed as part of #42453.
