### ISSUE TITLE
[CI] XPackRestIT {p0=data_frame/transforms_start_stop/Test start/stop/start transform} failed

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#42650]
`:x-pack:plugin:integTestRunnerorg.elasticsearch.xpack.test.rest.XPackRestIT » test {p0=data_frame/transforms_start_stop/Test start/stop/start transform} ` failed on my PR build:

https://scans.gradle.com/s/iw2bm6sic6zck/tests/fcijb24gqtmnc-5oryj5kbqusnk?openStackTraces=WzAsMV0

```
java.lang.AssertionError: 
Failure at [data_frame/transforms_start_stop:117]: transforms.0.state.indexer_state didn't match expected value:
transforms.0.state.indexer_state: expected [stopped] but was [stopping]
Close stacktrace
at __randomizedtesting.SeedInfo.seed([9052282EE340CA79:180617F44DBCA781]:0)
at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:393)
at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:370)
at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:566)
```

Did not reproduce with the reproduction line.

**Comment by davidkyle** [comment]
Muted in 4da6453673f28b4899f92bcc9867f153332154c9
