### ISSUE TITLE
elasticsearch-shard can't  remove corrupted parts.

### ISSUE THREAD

**Issue by UnicornChan** [elastic/elasticsearch#42661]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
Discovered in version 6.5.4, then, I reproduce the bug in 7.1.0. 
Version: 7.1.0, Build: default/rpm/606a173/2019-05-16T00:43:15.323135Z, JVM: 1.8.0_162

**Plugins installed**: no plugin

**JVM version** (`java -version`):
1.8.0_162

**OS version** (`uname -a` if on a Unix-like system):
Linux node-1 3.10.0-514.el7.x86_64 CentOS Linux release 7.3

**Description of the problem including expected versus actual behavior**:

While insert data to index, power cut. After I recovery the cluster, there is a shard unassigned.
The log reported:
> "Caused by: java.io.EOFException: read past EOF. pos [32595685] length: [22920] end: [32595697]"

    I find docs say that `elasticsearch-translog` and `elasticsearch-shard` tools could delete the corrupted translog data, so that I will lost data only in translog.
But unfortunately, `elasticsearch-translog` and `elasticsearch-shard` report the error 
> "Caused by: java.io.EOFException: read past EOF. pos [32595685] length: [22920] end: [32595697]"

 too. which means I will lost all data in this shard.
    I guess the elasticsearch record offset first, write datas to translog file second. while offset write successful, but datas  write failure. The bug appear。

**Steps to reproduce**:
It's little probability to reproduce the bug by power cut. So I reproduce the bug by delete translog file.
 1. Kill elasticsearch process while insert data.
 2. cd translog dir, delete some bytes in `.tlog` file.
 3. restart cluster,  sometimes report `checksum error`, which `elasticsearch-shard` could fix. sometimes `read past EOF` report, `elasticsearch-shard` could not fix.
 4. if report `read past EOF` error, close cluster,
 5. run `bin/elasticsearch-shard remove-corrupted-data --index test --shard-id 0`, `read past EOF` error appear agin.

**Provide logs (if relevant)**:

> "stacktrace": ["org.elasticsearch.index.engine.EngineException: failed to recover from translog",
"at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslogInternal(InternalEngine.java:444) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:414) [elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:109) [elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:1401) [elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:433) [elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:95) [elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:308) [elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:93) [elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1687) [elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$9(IndexShard.java:2340) [elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [elasticsearch-7.1.0.jar:7.1.0]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",
"at java.lang.Thread.run(Thread.java:835) [?:?]",
"Caused by: java.io.EOFException: read past EOF. pos [32595685] length: [22920] end: [32595697]",
"at org.elasticsearch.common.io.Channels.readFromFileChannelWithEofException(Channels.java:103) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.translog.TranslogSnapshot.readBytes(TranslogSnapshot.java:104) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.translog.BaseTranslogReader.checksummedStream(BaseTranslogReader.java:110) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.translog.TranslogSnapshot.readOperation(TranslogSnapshot.java:81) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.translog.TranslogSnapshot.next(TranslogSnapshot.java:70) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.translog.MultiSnapshot.next(MultiSnapshot.java:78) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.shard.IndexShard.runTranslogRecovery(IndexShard.java:1357) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.shard.IndexShard.lambda$openEngineAndRecoverFromTranslog$5(IndexShard.java:1395) ~[elasticsearch-7.1.0.jar:7.1.0]",
"at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslogInternal(InternalEngine.java:442) ~[elasticsearch-7.1.0.jar:7.1.0]",
"... 13 more"] }

**Comment by DaveCTurner** [comment]
Hi @UnicornChan, I tried a few different ways to reproduce what you're describing but didn't succeed. For instance, I created an index and then deleted some bytes from a translog file and got the following exception:

```
[2019-05-29T10:37:04,800][WARN ][o.e.i.c.IndicesClusterStateService] [node-0] [[i][0]] marking and sending shard failed due to [failed recovery]
org.elasticsearch.indices.recovery.RecoveryFailedException: [i][0]: Recovery failed on {node-0}{p7lvBlzRQdi1gFUTzJJ4tw}{s84zJZyaRiSj-R2BIM4GVQ}{127.0.0.1}{127.0.0.1:9300}{ml.machine_memory=17179869184, xpack.installed=true, ml.max_open_jobs=20}
        at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$9(IndexShard.java:2344) [elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [elasticsearch-7.1.1.jar:7.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: org.elasticsearch.index.shard.IndexShardRecoveryException: failed recovery
        at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:353) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:93) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1687) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$9(IndexShard.java:2340) ~[elasticsearch-7.1.1.jar:7.1.1]
        ... 4 more
Caused by: org.elasticsearch.index.translog.TranslogCorruptedException: translog from source [data-0/nodes/0/indices/5vs0nscfSY-Mshky9SuA5g/0/translog] is corrupted
        at org.elasticsearch.index.translog.Translog.readCheckpoint(Translog.java:1823) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.translog.Translog.readGlobalCheckpoint(Translog.java:1810) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:1437) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:1398) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:433) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:95) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:308) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:93) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1687) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$9(IndexShard.java:2340) ~[elasticsearch-7.1.1.jar:7.1.1]
        ... 4 more
Caused by: java.io.EOFException
        at org.elasticsearch.common.io.stream.InputStreamStreamInput.readByte(InputStreamStreamInput.java:59) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.translog.BufferedChecksumStreamInput.readByte(BufferedChecksumStreamInput.java:62) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.io.stream.StreamInput.readInt(StreamInput.java:204) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.translog.Translog.verifyChecksum(Translog.java:1537) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.translog.TranslogHeader.read(TranslogHeader.java:153) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.translog.Translog.readCheckpoint(Translog.java:1819) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.translog.Translog.readGlobalCheckpoint(Translog.java:1810) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:1437) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:1398) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:433) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:95) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:308) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:93) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1687) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$9(IndexShard.java:2340) ~[elasticsearch-7.1.1.jar:7.1.1]
        ... 4 more
```

However, this is correctly detected by `elasticsearch-shard`, which then deletes the corrupted translog as expected:

```
$ ES_PATH_CONF=elasticsearch-7.1.1/config-0 elasticsearch-7.1.1/bin/elasticsearch-shard remove-corrupted-data --index i --shard-id 0
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
-----------------------------------------------------------------------

    WARNING: Elasticsearch MUST be stopped before running this tool.

  Please make a complete backup of your index before using this tool.

-----------------------------------------------------------------------

Opening Lucene index at data-0/nodes/0/indices/5vs0nscfSY-Mshky9SuA5g/0/index


 >> Lucene index is clean at data-0/nodes/0/indices/5vs0nscfSY-Mshky9SuA5g/0/index


Opening translog at data-0/nodes/0/indices/5vs0nscfSY-Mshky9SuA5g/0/translog


 >> Translog is corrupted at data-0/nodes/0/indices/5vs0nscfSY-Mshky9SuA5g/0/translog

-----------------------------------------------------------------------

  Documents inside of translog files will be lost.
  The following files will be DELETED at data-0/nodes/0/indices/5vs0nscfSY-Mshky9SuA5g/0/translog

  --> translog-1.ckp
  --> translog-1.tlog
  --> translog-2.ckp
  --> translog-2.tlog
  --> translog-3.tlog
  --> translog-3.tlog.orig
  --> translog-3.tlog.xxd
  --> translog.ckp

            WARNING:              YOU MAY LOSE DATA.
-----------------------------------------------------------------------
Continue and remove corrupted data from the shard ?
Confirm [y/N] y
Checking existing translog files
Reading translog UUID information from Lucene commit from shard at [data-0/nodes/0/indices/5vs0nscfSY-Mshky9SuA5g/0/index]
Translog Generation: 3
Translog UUID      : C2Qq61VsQC-J5oN7umqXUg
History UUID       : GKYLGzmeSs6JwtIYUzkc-w
Removing existing translog files
Creating new empty checkpoint at [data-0/nodes/0/indices/5vs0nscfSY-Mshky9SuA5g/0/translog/translog.ckp]
Creating new empty translog at [data-0/nodes/0/indices/5vs0nscfSY-Mshky9SuA5g/0/translog/translog-3.tlog]
Marking index with the new history uuid : FVsRXGGfSFG-QRxQDYJ_IQ
Changing allocation id AIW59M4gQRysysTityYoRw to yXGq1ZE3Qv-2lgEqKqzHyQ

You should run the following command to allocate this shard:

POST /_cluster/reroute'
{
  "commands" : [
    {
      "allocate_stale_primary" : {
        "index" : "i",
        "shard" : 0,
        "node" : "p7lvBlzRQdi1gFUTzJJ4tw",
        "accept_data_loss" : false
      }
    }
  ]
}'
```

Running the given `POST /_cluster/reroute` command does indeed allow the cluster to assign the truncated version of this shard.

Could you try and reproduce this in an otherwise empty one-node cluster? If you succeed, could you shut the cluster down, tar up the data path, and attach it to this issue?

**Comment by DaveCTurner** [comment]
Also I should note that a power failure shouldn't result in a corrupted translog. The most likely explanation is that your disk [isn't properly persisting the data that Elasticsearch writes to it](https://brad.livejournal.com/2116715.html).

**Comment by UnicornChan** [comment]
Hi，,@DaveCTurner Thank you for your reply! I think you are right, I enabled write caching on the disk.
And I hope I can detect the error by elasticsearch-shard.
while I insert data by bulk api, kill the elasticsearch.
I delete the bottom line and some bytes in translog-2.tlog, then running the elasticsearch-shard:
```
 ./bin/elasticsearch-shard remove-corrupted-data --index test --shard-id 0
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
-----------------------------------------------------------------------

    WARNING: Elasticsearch MUST be stopped before running this tool.

  Please make a complete backup of your index before using this tool.

-----------------------------------------------------------------------

Opening Lucene index at /var/lib/elasticsearch/nodes/0/indices/Cco_uj3lSFyukDTIfykF3w/0/index


 >> Lucene index is clean at /var/lib/elasticsearch/nodes/0/indices/Cco_uj3lSFyukDTIfykF3w/0/index


Opening translog at /var/lib/elasticsearch/nodes/0/indices/Cco_uj3lSFyukDTIfykF3w/0/translog

read past EOF. pos [6167711] length: [617] end: [6168285]
Exception in thread "main" java.io.EOFException: read past EOF. pos [6167711] length: [617] end: [6168285]
	at org.elasticsearch.common.io.Channels.readFromFileChannelWithEofException(Channels.java:103)
	at org.elasticsearch.index.translog.TranslogSnapshot.readBytes(TranslogSnapshot.java:104)
	at org.elasticsearch.index.translog.BaseTranslogReader.checksummedStream(BaseTranslogReader.java:110)
	at org.elasticsearch.index.translog.TranslogSnapshot.readOperation(TranslogSnapshot.java:81)
	at org.elasticsearch.index.translog.TranslogSnapshot.next(TranslogSnapshot.java:70)
	at org.elasticsearch.index.translog.MultiSnapshot.next(MultiSnapshot.java:78)
	at org.elasticsearch.index.translog.TruncateTranslogAction.isTranslogClean(TruncateTranslogAction.java:187)
	at org.elasticsearch.index.translog.TruncateTranslogAction.getCleanStatus(TruncateTranslogAction.java:86)
	at org.elasticsearch.index.shard.RemoveCorruptedShardDataCommand.lambda$execute$1(RemoveCorruptedShardDataCommand.java:329)
	at org.elasticsearch.index.shard.RemoveCorruptedShardDataCommand.findAndProcessShardPath(RemoveCorruptedShardDataCommand.java:202)
	at org.elasticsearch.index.shard.RemoveCorruptedShardDataCommand.execute(RemoveCorruptedShardDataCommand.java:282)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.index.shard.ShardToolCli.main(ShardToolCli.java:35)
```
And this is my data_path file.

[elasticsearch.zip](https://github.com/elastic/elasticsearch/files/3235320/elasticsearch.zip)

**Comment by DaveCTurner** [comment]
Thanks, that helps enormously. I think this is a bug that slipped through the tests and am working on a fix. In the meantime, you can proceed by deleting the truncated file, which will allow the `elasticsearch-shard` tool to do its thing.
