### ISSUE TITLE
[build] assertRepositoryURIUsesHttps breaks s3 repositories

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#42732]
When building a custom plugin using the build-tools jar, we get the following exception when building the 6.8.0 version:

```
Caused by: java.net.MalformedURLException: unknown protocol: s3
        at java_net_URI$toURL.call(Unknown Source)
        at org.elasticsearch.gradle.BuildPlugin.assertRepositoryURIUsesHttps(BuildPlugin.groovy:598)
        at jdk.internal.reflect.GeneratedMethodAccessor342.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.elasticsearch.gradle.BuildPlugin$_configureRepositories_closure11.doCall(BuildPlugin.groovy:567)
        at jdk.internal.reflect.GeneratedMethodAccessor341.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:70)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:105)
        at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:166)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1$1.run(DefaultCollectionCallbackActionDecorator.java:100)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:58)
        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:97)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        ... 173 more
```

This is because our build.gradle file has a repositories block like so:

```
    repositories {
        maven {
            url "s3://...
       }
    }
```

**Comment by synhershko** [comment]
This doesn't happen for 7.0.x but does for 7.1.x

**Comment by atorok** [comment]
Looks like `uri.toURL()` blows up. The  change causing this was done after `7.0` thus it's not reproducible there.  I can't think of a workaround, something we will have to look at fixing.

**Comment by atorok** [comment]
using `uri.getScheme().equals("http")` would likely work, but we should add a test for it to make sure this doesn't break again.

**Comment by synhershko** [comment]
Any chance this can be fixed? :) @atorok @rjernst

**Comment by jasontedor** [comment]
Is there a reason that you can't simply use `https://s3.amazonaws.com/...`?

**Comment by synhershko** [comment]
Because it's not public and we pass the `AWS_ ` env vars

**Comment by jasontedor** [comment]
I opened #45950.

**Comment by synhershko** [comment]
Thanks @jasontedor !
