### ISSUE TITLE
[CI] CrudIT fails

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#42881]
CrudIT starts failing on 6.8 branch after #42641 was merged.

```
./gradlew :client:rest-high-level:integTestRunner -Dtests.seed=5E5CD3BF3E49B3D8 -Dtests.class=org.elasticsearch.client.CrudIT -Dtests.method="testDelete" -Dtests.security.manager=true -Dtests.locale=es-VE -Dtests.timezone=Asia/Kashgar -Dcompiler.java=12 -Druntime.java=8
FAILURE 1.00s | CrudIT.testDelete <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: no warnings, expected: [Usage of internal versioning for optimistic concurrency control is deprecated and will be removed. Please use the `if_seq_no` and `if_primary_term` parameters instead. (request for index [index], type [type], id [id])]
   >    at __randomizedtesting.SeedInfo.seed([5E5CD3BF3E49B3D8:13036CABCE9E1A45]:0)
   >    at org.elasticsearch.test.ESTestCase.assertWarnings(ESTestCase.java:450)
   >    at org.elasticsearch.test.ESTestCase.assertWarnings(ESTestCase.java:436)
   >    at org.elasticsearch.client.CrudIT.testDelete(CrudIT.java:122)
   >    at java.lang.Thread.run(Thread.java:748)
```

**Comment by dnhatn** [comment]
Fixed in #42956.
