### ISSUE TITLE
ES crashing multiple times, over 1Billion docs a day, indexing rate falling from 25k/s to 2k/s

### ISSUE THREAD

**Issue by VRYasa** [elastic/elasticsearch#42953]
**ES crashing multiple times, over 1Billion logs a day, indexing rate falling from 25k/s to 2k/s**:

**GET /** output:
{
  "name": "es-ingest-3",
  "cluster_name": "CT",
  "cluster_uuid": "IEasdfasfsdfaf",
  "version": {
    "number": "6.1.2",
    "build_hash": "asdfasdf",
    "build_date": "2018-01-10T02:35:59.208Z",
    "build_snapshot": false,
    "lucene_version": "7.1.0",
    "minimum_wire_compatibility_version": "5.6.0",
    "minimum_index_compatibility_version": "5.0.0"
  },
  "tagline": "You Know, for Search"
}

**GET _cat/nodes?v** output:
ip            heap.percent ram.percent cpu load_1m load_5m load_15m node.role master name
10.6.128.4           19          97   4    0.46    0.34     0.36 m         -      es-master-4
10.2.0.2             37          99   9    2.22    1.91     1.56 d         -      es-data-6
10.4.128.2           11          98   3    0.77    0.66     0.46 m         -      es-master-3
10.4.0.7             35          83   2    0.42    0.45     0.43 i         -      es-ingest-1
10.4.0.3             11          90   3    0.13    0.26     0.31 m         -      es-master-1
10.1.192.2           32          99  10    1.49    1.50     1.33 d         -      es-data-0
10.2.128.2           36          99   9    1.09    1.22     1.18 d         -      es-data-5
10.8.0.2             16          99  20    5.02    4.84     4.68 d         -      es-data-8
10.7.128.5           64          66   2    0.01    0.04     0.09 i         -      es-ingest-3
10.9.0.3              26          84   6    0.49    0.48     0.44 m         *      es-master-0
10.7.0.2              14          95  10    1.03    0.95     0.82 m         -      es-master-2
10.6.0.4             60          66   2    0.01    0.07     0.12 i         -      es-ingest-2
10.9.128.2           26          99   6    1.87    1.92     1.66 d         -      es-data-7
10.3.128.2           31          99  10    1.49    1.48     1.35 d         -      es-data-2
10.1.0.2             50          99  10    1.19    1.00     0.91 d         -      es-data-4
10.3.0.9             16          99  10    1.14    1.10     1.01 d         -      es-data-1
10.5.0.2             29          99  22    2.12    2.12     1.77 d         -      es-data-3
10.7.128.6           60          66   4    0.01    0.04     0.09 i         -      es-ingest-0
10.6.128.2           58          99   8    0.10    0.22     0.24 d         -      es-data-9

**Average indexing rate**: [6k to 10k per sec]

**When I perform the following steps the indexing rate increased to 25k to 30k per sec**:
PUT /logstash-*/_settings
{
    "index" : {
        "refresh_interval" : "-1"
    }
}

PUT /logstash-*/_settings
{
    "index" : {
        "number_of_replicas" : "0"
    }
}

**By performing the above steps it improved the rate and ran very well for about 10days indexing nearly 17Billion documents. But it failed when there was a spike of 1.3 Billion documents per day. Since then, this has not been stable, every time I perform the above steps, the cluster indexing rate increases for a few hours and then crashes again.**

**Then I have been performing the following steps in the same order**: 
PUT /logstash-*/_settings
{
    "index" : {
        "number_of_replicas" : "1"
    }
}
PUT /_cluster/settings
{
    "transient" : {
        "cluster.routing.allocation.enable" : "none"
    }
}
**Waited for all the shards to be reallocated and then did the following steps**:
PUT _cluster/settings
{
  "persistent": {
    "cluster.routing.allocation.enable": "primaries"
  }
}
PUT /_cluster/settings
{
    "transient" : {
        "cluster.routing.allocation.enable" : "all"
    }
}
PUT /logstash-*/_settings
{
    "index" : {
        "refresh_interval" : "-1"
    }
}
PUT /logstash-*/_settings
{
    "index" : {
        "number_of_replicas" : "0"
    }
}

**I had to restart all Logstash containers and the indexing improved again but failed after few hours. This process keeps repeating with the following logs**:
`[2019-06-06T09:17:50,436][WARN ][o.e.c.r.a.DiskThresholdMonitor] [es-master-0] high disk watermark [50gb] exceeded on [M6fzMFiuT_Ks7R0layHpIg][es-data-9][/data/nodes/0] free: 49.9gb[5%], shards will be relocated away from this node
[2019-06-06T09:17:50,436][INFO ][o.e.c.r.a.DiskThresholdMonitor] [es-master-0] low disk watermark [100gb] exceeded on [q4M5NMS1T5GguZor8fHDSw][es-data-8][/data/nodes/0] free: 51.6gb[5.2%], replicas will not be assigned to this node
[2019-06-06T09:17:50,436][INFO ][o.e.c.r.a.DiskThresholdMonitor] [es-master-0] rerouting shards: [high disk watermark exceeded on one or more nodes]
[2019-06-06T09:18:50,724][INFO ][o.e.c.r.a.DiskThresholdMonitor] [es-master-0] low disk watermark [100gb] exceeded on [M6fzMFiuT_Ks7R0layHpIg][es-data-9][/data/nodes/0] free: 50gb[5%], replicas will not be assigned to this node
[2019-06-06T09:18:50,724][INFO ][o.e.c.r.a.DiskThresholdMonitor] [es-master-0] low disk watermark [100gb] exceeded on [q4M5NMS1T5GguZor8fHDSw][es-data-8][/data/nodes/0] free: 51.2gb[5.2%], replicas will not be assigned to this node
[2019-06-06T09:19:50,941][INFO ][o.e.c.r.a.DiskThresholdMonitor] [es-master-0] low disk watermark [100gb] exceeded on [q4M5NMS1T5GguZor8fHDSw][es-data-8][/data/nodes/0] free: 51.3gb[5.2%], replicas will not be assigned to this node
[2019-06-06T09:19:50,941][WARN ][o.e.c.r.a.DiskThresholdMonitor] [es-master-0] high disk watermark [50gb] exceeded on [M6fzMFiuT_Ks7R0layHpIg][es-data-9][/data/nodes/0] free: 49.5gb[5%], shards will be relocated away from this node
[2019-06-06T09:19:50,941][INFO ][o.e.c.r.a.DiskThresholdMonitor] [es-master-0] rerouting shards: [high disk watermark exceeded on one or more nodes]
[2019-06-06T09:20:51,070][WARN ][o.e.c.r.a.DiskThresholdMonitor] [es-master-0] high disk watermark [50gb] exceeded on [M6fzMFiuT_Ks7R0layHpIg][es-data-9][/data/nodes/0] free: 49.1gb[4.9%], shards will be relocated away from this node
[2019-06-06T09:20:51,070][INFO ][o.e.c.r.a.DiskThresholdMonitor] [es-master-0] low disk watermark [100gb] exceeded on [q4M5NMS1T5GguZor8fHDSw][es-data-8][/data/nodes/0] free: 50.7gb[5.1%], replicas will not be assigned to this node
[2019-06-06T09:20:51,070][INFO ][o.e.c.r.a.DiskThresholdMonitor] [es-master-0] rerouting shards: [high disk watermark exceeded on one or more nodes]
[2019-06-06T09:21:51,073][INFO ][o.e.c.r.a.DiskThresholdMonitor] [es-master-0] low disk watermark [100gb] exceeded on [q4M5NMS1T5GguZor8fHDSw][es-data-8][/data/nodes/0] free: 50.3gb[5.1%], replicas will not be assigned to this node
[2019-06-06T09:21:51,073][WARN ][o.e.c.r.a.DiskThresholdMonitor] [es-master-0] high disk watermark [50gb] exceeded on [M6fzMFiuT_Ks7R0layHpIg][es-data-9][/data/nodes/0] free: 48.7gb[4.9%], shards will be relocated away from this node
[2019-06-06T09:21:51,073][INFO ][o.e.c.r.a.DiskThresholdMonitor] [es-master-0] rerouting shards: [high disk watermark exceeded on one or more nodes]
[2019-06-06T09:22:51,245][WARN ][o.e.c.r.a.DiskThresholdMonitor] [es-master-0] high disk watermark [50gb] exceeded on [q4M5NMS1T5GguZor8fHDSw][es-data-8][/data/nodes/0] free: 49.8gb[5%], shards will be relocated away from this node
[2019-06-06T09:22:51,245][WARN ][o.e.c.r.a.DiskThresholdMonitor] [es-master-0] high disk watermark [50gb] exceeded on [M6fzMFiuT_Ks7R0layHpIg][es-data-9][/data/nodes/0] free: 49gb[4.9%], shards will be relocated away from this node
[2019-06-06T09:22:51,245][INFO ][o.e.c.r.a.DiskThresholdMonitor] [es-master-0] rerouting shards: [high disk watermark exceeded on one or more nodes]
`
**and**

`[2019-06-06T11:02:09,629][WARN ][o.e.c.a.s.ShardStateAction] [es-master-0] [logstash-2019.05.31][1] received shard failed for shard id [[logstash-2019.05.31][1]], allocation id [j32CrqOtR9eeqwKxujusNg], primary term [1], message [failed to perform indices:data/write/bulk[s] on replica [logstash-2019.05.31][1], node[y_u8hfExQgeHsnZUiXTgEg], relocating [q4M5NMS1T5GguZor8fHDSw], [P], s[RELOCATING], a[id=j32CrqOtR9eeqwKxujusNg, rId=xQNBvAklQCuyCwADuIOazg], expected_shard_size[34874350916]], failure [RemoteTransportException[[es-data-6][10.2.0.2:9300][indices:data/write/bulk[s][r]]]; nested: IllegalStateException[active primary shard [logstash-2019.05.31][1], node[y_u8hfExQgeHsnZUiXTgEg], relocating [q4M5NMS1T5GguZor8fHDSw], [P], s[RELOCATING], a[id=j32CrqOtR9eeqwKxujusNg, rId=xQNBvAklQCuyCwADuIOazg], expected_shard_size[34874350916] cannot be a replication target before relocation hand off, state is [CLOSED]]; ]
org.elasticsearch.transport.RemoteTransportException: [es-data-6][10.2.0.2:9300][indices:data/write/bulk[s][r]]
Caused by: java.lang.IllegalStateException: active primary shard [logstash-2019.05.31][1], node[y_u8hfExQgeHsnZUiXTgEg], relocating [q4M5NMS1T5GguZor8fHDSw], [P], s[RELOCATING], a[id=j32CrqOtR9eeqwKxujusNg, rId=xQNBvAklQCuyCwADuIOazg], expected_shard_size[34874350916] cannot be a replication target before relocation hand off, state is [CLOSED]
    at org.elasticsearch.index.shard.IndexShard.verifyReplicationTarget(IndexShard.java:1479) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.index.shard.IndexShard.ensureWriteAllowed(IndexShard.java:1462) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:683) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnReplica(IndexShard.java:674) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.action.bulk.TransportShardBulkAction.performOpOnReplica(TransportShardBulkAction.java:518) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnReplica(TransportShardBulkAction.java:480) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnReplica(TransportShardBulkAction.java:466) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnReplica(TransportShardBulkAction.java:72) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncReplicaAction.onResponse(TransportReplicationAction.java:566) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncReplicaAction.onResponse(TransportReplicationAction.java:529) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.index.shard.IndexShard$2.onResponse(IndexShard.java:2305) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.index.shard.IndexShard$2.onResponse(IndexShard.java:2283) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:238) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.index.shard.IndexShard.acquireReplicaOperationPermit(IndexShard.java:2282) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncReplicaAction.doRun(TransportReplicationAction.java:640) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.action.support.replication.TransportReplicationAction$ReplicaOperationTransportHandler.messageReceived(TransportReplicationAction.java:512) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.action.support.replication.TransportReplicationAction$ReplicaOperationTransportHandler.messageReceived(TransportReplicationAction.java:492) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1554) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:637) ~[elasticsearch-6.1.2.jar:6.1.2]
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.1.2.jar:6.1.2]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_151]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_151]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
`

**We get an average 800 Million documents everyday, sometimes we get spikes of around 1.3 Billion per day. Please suggest the best way to address this. We currently have a 7 days backlog which needs to be cleared.** 

**I am new to managing ES, please guide me.**

**Comment by DaveCTurner** [comment]
Hi @VRYasa, I think this question is better suited for the [discussion forums](http://discuss.elastic.co/c/elasticsearch). Although you might be reporting a bug I think it more likely that this is a question about how to use Elasticsearch, and your description of the problem is not precise enough for us to investigate further.

**Comment by VRYasa** [comment]
Thanks for the response. I have posted it there. https://discuss.elastic.co/t/es-crashing-multiple-times-over-1billion-docs-a-day-indexing-rate-falling-from-25k-s-to-2k-s/184628
