### ISSUE TITLE
Add null check for ParentJoinFieldMapper in ChildrenAggregationBuilder.joinFieldResolveConfig

### ISSUE THREAD

**Issue by ebadyano** [elastic/elasticsearch#42997]
A user received a NPE. It was reproduced on 6.3.1 with the following stack trace:
```
2019-06-06T13:26:49,963][DEBUG][o.e.a.s.TransportSearchAction] [hamilton] [mi_indice][2], node[ABwM3KQJQdWuKfnzwJ8pxw], [P], s[STARTED], a[id=cRQiXG2DTmijJ2IMjtYq5g]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[mi_indice], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false], types=[], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=15, batchedReduceSize=512, preFilterShardSize=128, allowPartialSearchResults=true, source={"query":{"bool":{"must":[{"bool":{"must":[{"bool":{"should":[{"range":{"posting_date":{"from":"1900-01-01T00:00:00.000Z","to":"2019-05-30T18:25:49.967Z","include_lower":true,"include_upper":true,"boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}},{"term":{"externaljob_to_child_fields.name":{"value":"externaljob","boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}},"aggregations":{"POSTING_DATES":{"date_range":{"field":"posting_date","ranges":[{"key":"ORA_LT07","from":"2019-05-23T18:25:50.006Z","to":"2019-05-30T18:25:50.006Z"},{"key":"ORA_LT30","from":"2019-04-30T18:25:50.006Z","to":"2019-05-30T18:25:50.006Z"},{"key":"ORA_GT30","from":"1900-01-01T00:00:00.000Z","to":"2019-04-30T18:25:50.006Z"}],"keyed":false}},"LOCATIONS":{"children":{"type":"externaljob_locs"}}}}}] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [washington][127.0.0.1:9302][indices:data/read/search[phase/query]]
Caused by: java.lang.NullPointerException
	at org.elasticsearch.join.aggregations.ChildrenAggregationBuilder.joinFieldResolveConfig(ChildrenAggregationBuilder.java:122) ~[?:?]
	at org.elasticsearch.join.aggregations.ChildrenAggregationBuilder.resolveConfig(ChildrenAggregationBuilder.java:113) ~[?:?]
	at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:311) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:38) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:139) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:329) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:766) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:575) ~[elasticsearch-6.3.1.jar:6.3.1]
```

in `ChildrenAggregationBuilder.joinFieldResolveConfig`

```
private void joinFieldResolveConfig(SearchContext context, ValuesSourceConfig<WithOrdinals> config) {
        ParentJoinFieldMapper parentJoinFieldMapper = ParentJoinFieldMapper.getMapper(context.mapperService()); 
        ParentIdFieldMapper parentIdFieldMapper = parentJoinFieldMapper.getParentIdFieldMapper(childType, false);
        if (parentIdFieldMapper != null) {
...
        } else {
            config.unmapped(true);
        }

```
`ParentJoinFieldMapper.getMapper` returns null when there is no parent-join field in the mapping. We already check to see if `parentIdFieldMapper` is null and use an unmapped. Should probably be doing the same for `parentJoinFieldMapper` as well.

**Comment by amogh-jrules** [comment]
Hi can I be assigned this issue?

**Comment by jasontedor** [comment]
We can not assign issues to non-members (GitHub restriction), though you are free to submit a pull request for this.

**Comment by amogh-jrules** [comment]
Okay! I am working on it

**Comment by shubh49** [comment]
@amogh-jrules Are you working on this? If not, i am willing to take this up.

**Comment by amogh-jrules** [comment]
> @amogh-jrules Are you working on this? If not, i am willing to take this up.

I am working on it, as i said. about to submit a pull request

**Comment by hassan-alam** [comment]
@amogh-jrules  Are you still working on this? Your PR hasn't been changed in a while, so if you're not on this anymore, I can take this up.

**Comment by CalumLudwig** [comment]
What is happening with this PR? It has stalled for about 2 months, is it because the commits were not squashed into 1 commit as stated in the **CONTRIBUTING.md**?

**Comment by Suchita94** [comment]
Since this bug has been open for a while, created pull request with code changes and test cases

**Comment by sd1998** [comment]
@ebadyano Is this issue resolved? If not, can I be assigned this issue?

**Comment by ebadyano** [comment]
@sd1998 It looks like it might still exist, but the method has been renamed to `protected ValuesSourceConfig resolveConfig`. Please feel free to submit a pull request for this.

**Comment by parthpunkster** [comment]
I see that this issue is still open, can I work on this?

**Comment by parthpunkster** [comment]
Can someone assign this to me?

**Comment by jimczi** [comment]
> I see that this issue is still open, can I work on this?

Sure, please do. We don't assign issue so you can open a pr that links this issue and we'll review it.

**Comment by parthpunkster** [comment]
> > I see that this issue is still open, can I work on this?
> 
> Sure, please do. We don't assign issue so you can open a pr that links this issue and we'll review it.

I have worked on this one wanted some help around verifying the change and on the process of raising a pull request.

**Comment by parthpunkster** [comment]
@jimczi I have attached the pull request. Can you please review it.
