### ISSUE TITLE
Can't Start Elastic Search

### ISSUE THREAD

**Issue by chobo2** [elastic/elasticsearch#43018]
Hi

Not sure if this is a bug or if I missed something. I installed on my windows 10 machine elastic search vis the MSI instaleld.

I used [this tutorial](https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-install.html) (thought it seems a bit out of date)

I am not trying to start it all up but I get this

```
C:\Program Files\Elastic\Elasticsearch\7.1.1\bin>elasticsearch.exe
An exception occurred while trying to start elasticsearch.: System.UnauthorizedAccessException: Access to the path 'C:\Program Files\Elastic\Elasticsearch\7.1.1\logs' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Abstractions.DirectoryWrapper.CreateDirectory(String path)
   at Elastic.ProcessHosts.Elasticsearch.Process.ElasticsearchProcess.Start()
   at Elastic.ProcessHosts.Service.Service.Run()
   at Elastic.ProcessHosts.Elasticsearch.Program.Main(String[] args)
Elasticsearch.exe does not have permission to write exception to event log
```

**Comment by gwbrown** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
