### ISSUE TITLE
Elasticsearch is failing on windows 

### ISSUE THREAD

**Issue by liza-mae** [elastic/elasticsearch#43014]
**Elasticsearch version (bin/elasticsearch --version):** 7.2 Snapshot
build_flavor: oss, build_type: zip, build_hash: ef5176a 

**JVM version (java -version):** 12.0.1

**OS version (uname -a if on a Unix-like system):** Windows 2016

**Description of the problem including expected versus actual behavior:**

Elasticsearch is throwing a fatal error after Kibana is started. 

**Steps to reproduce:**

Please include a minimal but complete recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc. The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

1. Install ES/Kibana latest 7.2 snapshot 
2. Start elasticsearch - it comes up and says started
3. Start kibana - while kibana tries to connect to elasticsearch, elasticsearch throws an error
4. Attempts to start elasticsearch again from this directory will fail with the same error 

Note I did the same steps on 7.2.0 BC5 and did not see the problem. 

**Provide logs (if relevant):**

 ./bin/elasticsearch.bat
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2019-06-09T01:27:34,175][INFO ][o.e.e.NodeEnvironment    ] [VAGRANT-2016] using [1] data paths, mounts [[Windows 2016 (C:)]], net usable_space [24gb], net total_space [59.6gb], types [NTFS]
[2019-06-09T01:27:34,175][INFO ][o.e.e.NodeEnvironment    ] [VAGRANT-2016] heap size [1007.3mb], compressed ordinary object pointers [true]
[2019-06-09T01:27:34,190][INFO ][o.e.n.Node               ] [VAGRANT-2016] node name [VAGRANT-2016], node ID [McBjQpLeSUK9eOGOdO4HuQ], cluster name [elasticsearch]
[2019-06-09T01:27:34,190][INFO ][o.e.n.Node               ] [VAGRANT-2016] version[7.2.0-SNAPSHOT], pid[3456], build[oss/zip/ef5176a/2019-06-08T03:19:08.620142Z], OS[Windows Server 2016/10.0/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/12.0.1/12.0.1+12]
[2019-06-09T01:27:34,190][INFO ][o.e.n.Node               ] [VAGRANT-2016] JVM home [C:\Progra~1\Java\jdk-12.0.1]
[2019-06-09T01:27:34,190][INFO ][o.e.n.Node               ] [VAGRANT-2016] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=C:\Users\vagrant\AppData\Local\Temp\1\elasticsearch, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -Dio.netty.allocator.type=unpooled, -XX:MaxDirectMemorySize=536870912, -Delasticsearch, -Des.path.home=C:\Users\vagrant\AppData\Local\Temp\1\elasticsearch-7.2.0-SNAPSHOT, -Des.path.conf=C:\Users\vagrant\AppData\Local\Temp\1\elasticsearch-7.2.0-SNAPSHOT\config, -Des.distribution.flavor=oss, -Des.distribution.type=zip, -Des.bundled_jd=true]
[2019-06-09T01:27:34,190][WARN ][o.e.n.Node               ] [VAGRANT-2016] version [7.2.0-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
[2019-06-09T01:27:35,690][INFO ][o.e.p.PluginsService     ] [VAGRANT-2016] loaded module [aggs-matrix-stats]
[2019-06-09T01:27:35,690][INFO ][o.e.p.PluginsService     ] [VAGRANT-2016] loaded module [analysis-common]
[2019-06-09T01:27:35,690][INFO ][o.e.p.PluginsService     ] [VAGRANT-2016] loaded module [ingest-common]
[2019-06-09T01:27:35,690][INFO ][o.e.p.PluginsService     ] [VAGRANT-2016] loaded module [ingest-geoip]
[2019-06-09T01:27:35,690][INFO ][o.e.p.PluginsService     ] [VAGRANT-2016] loaded module [ingest-user-agent]
[2019-06-09T01:27:35,690][INFO ][o.e.p.PluginsService     ] [VAGRANT-2016] loaded module [lang-expression]
[2019-06-09T01:27:35,690][INFO ][o.e.p.PluginsService     ] [VAGRANT-2016] loaded module [lang-mustache]
[2019-06-09T01:27:35,690][INFO ][o.e.p.PluginsService     ] [VAGRANT-2016] loaded module [lang-painless]
[2019-06-09T01:27:35,690][INFO ][o.e.p.PluginsService     ] [VAGRANT-2016] loaded module [mapper-extras]
[2019-06-09T01:27:35,690][INFO ][o.e.p.PluginsService     ] [VAGRANT-2016] loaded module [parent-join]
[2019-06-09T01:27:35,690][INFO ][o.e.p.PluginsService     ] [VAGRANT-2016] loaded module [percolator]
[2019-06-09T01:27:35,705][INFO ][o.e.p.PluginsService     ] [VAGRANT-2016] loaded module [rank-eval]
[2019-06-09T01:27:35,705][INFO ][o.e.p.PluginsService     ] [VAGRANT-2016] loaded module [reindex]
[2019-06-09T01:27:35,705][INFO ][o.e.p.PluginsService     ] [VAGRANT-2016] loaded module [repository-url]
[2019-06-09T01:27:35,705][INFO ][o.e.p.PluginsService     ] [VAGRANT-2016] loaded module [transport-netty4]
[2019-06-09T01:27:35,705][INFO ][o.e.p.PluginsService     ] [VAGRANT-2016] no plugins loaded
[2019-06-09T01:27:38,908][INFO ][o.e.d.DiscoveryModule    ] [VAGRANT-2016] using discovery type [zen] and seed hosts providers [settings]
[2019-06-09T01:27:39,704][INFO ][o.e.n.Node               ] [VAGRANT-2016] initialized
[2019-06-09T01:27:39,704][INFO ][o.e.n.Node               ] [VAGRANT-2016] starting ...
[2019-06-09T01:27:40,204][INFO ][o.e.t.TransportService   ] [VAGRANT-2016] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}, {[::1]:9300}
[2019-06-09T01:27:40,220][WARN ][o.e.b.BootstrapChecks    ] [VAGRANT-2016] the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured
[2019-06-09T01:27:40,235][INFO ][o.e.c.c.ClusterBootstrapService] [VAGRANT-2016] no discovery configuration found, will perform best-effort cluster bootstrapping after [3s] unless existing master is discovered
[2019-06-09T01:27:43,250][INFO ][o.e.c.c.Coordinator      ] [VAGRANT-2016] setting initial configuration to VotingConfiguration{McBjQpLeSUK9eOGOdO4HuQ}
[2019-06-09T01:27:43,406][INFO ][o.e.c.s.MasterService    ] [VAGRANT-2016] elected-as-master ([1] nodes joined)[{VAGRANT-2016}{McBjQpLeSUK9eOGOdO4HuQ}{3ke5jMCkQ1eLlNCWcY6N0g}{127.0.0.1}{127.0.0.1:9300} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 1, version: 1, reason: master node changed {previous [], current [{VAGRANT-2016}{McBjQpLeSUK9eOGOdO4HuQ}{3ke5jMCkQ1eLlNCWcY6N0g}{127.0.0.1}{127.0.0.1:9300}]}
[2019-06-09T01:27:43,422][INFO ][o.e.c.c.CoordinationState] [VAGRANT-2016] cluster UUID set to [VDeTmv8hSjGGkzrm1OCOYQ]
[2019-06-09T01:27:43,453][INFO ][o.e.c.s.ClusterApplierService] [VAGRANT-2016] master node changed {previous [], current [{VAGRANT-2016}{McBjQpLeSUK9eOGOdO4HuQ}{3ke5jMCkQ1eLlNCWcY6N0g}{127.0.0.1}{127.0.0.1:9300}]}, term: 1, version: 1, reason: Publication{term=1, version=1}
[2019-06-09T01:27:43,500][INFO ][o.e.g.GatewayService     ] [VAGRANT-2016] recovered [0] indices into cluster_state
[2019-06-09T01:27:43,500][INFO ][o.e.h.AbstractHttpServerTransport] [VAGRANT-2016] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {[::1]:9200}
[2019-06-09T01:27:43,500][INFO ][o.e.n.Node               ] [VAGRANT-2016] started
[2019-06-09T01:28:12,399][INFO ][o.e.c.m.MetaDataCreateIndexService] [VAGRANT-2016] [.kibana_1] creating index, cause [api], templates [], shards [1]/[1], mappings [_doc]
[2019-06-09T01:28:12,414][INFO ][o.e.c.r.a.AllocationService] [VAGRANT-2016] updating number_of_replicas to [0] for indices [.kibana_1]
[2019-06-09T01:28:12,758][WARN ][o.e.i.c.IndicesClusterStateService] [VAGRANT-2016] [.kibana_1][0] marking and sending shard failed due to [failed recovery]
org.elasticsearch.indices.recovery.RecoveryFailedException: [.kibana_1][0]: Recovery failed on {VAGRANT-2016}{McBjQpLeSUK9eOGOdO4HuQ}{3ke5jMCkQ1eLlNCWcY6N0g}{127.0.0.1}{127.0.0.1:9300}
        at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$9(IndexShard.java:2329) [elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:688) [elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: org.elasticsearch.index.shard.IndexShardRecoveryException: failed to recover from gateway
        at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:438) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
        at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:95) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
        at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:308) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
        at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:93) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
        at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1678) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
        at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$9(IndexShard.java:2325) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]

**Comment by jasontedor** [comment]
@liza-mae I suspect this is addressed by 2b6262957c04384261242eb8fcfe12180d4a36ed but it is hard to say without more information from the stacktrace. Can you share it?

**Comment by liza-mae** [comment]
@jasontedor The log is attached:

[Untitled document.txt](https://github.com/elastic/elasticsearch/files/3269839/Untitled.document.txt)

**Comment by jasontedor** [comment]
Thanks @liza-mae. That’s the same issue indeed, closing this as addressed by #43008.

**Comment by liza-mae** [comment]
Thanks @jasontedor confirmed it is fixed in latest snapshot for 7.2
