### ISSUE TITLE
[CI] AzureDiscoveryClusterFormationTests leaks threads

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#43048]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java12,nodes=immutable&&linux&&docker/11/testReport/org.elasticsearch.discovery.azure.classic/AzureDiscoveryClusterFormationTests/classMethod/

failed with:

```
Jun 10, 2019 4:32:16 AM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
SEVERE: There are still zombie threads that couldn't be terminated:
   1) Thread[id=28, name=server-timer, state=TIMED_WAITING, group=TGRP-AzureDiscoveryClusterFormationTests]
        at java.base@12.0.1/java.lang.Object.wait(Native Method)
        at java.base@12.0.1/java.util.TimerThread.mainLoop(Timer.java:553)
        at java.base@12.0.1/java.util.TimerThread.run(Timer.java:506)
   2) Thread[id=29, name=HTTP-Dispatcher, state=RUNNABLE, group=TGRP-AzureDiscoveryClusterFormationTests]
        at java.base@12.0.1/sun.security.ssl.SSLEngineImpl.checkParams(SSLEngineImpl.java:422)
        at java.base@12.0.1/sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:133)
        at java.base@12.0.1/sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:116)
        at java.base@12.0.1/javax.net.ssl.SSLEngine.wrap(SSLEngine.java:479)
        at platform/jdk.httpserver@12.0.1/sun.net.httpserver.SSLStreams$EngineWrapper.wrapAndSendX(SSLStreams.java:283)
        at platform/jdk.httpserver@12.0.1/sun.net.httpserver.SSLStreams.doClosure(SSLStreams.java:436)
        at platform/jdk.httpserver@12.0.1/sun.net.httpserver.SSLStreams.recvData(SSLStreams.java:410)
        at platform/jdk.httpserver@12.0.1/sun.net.httpserver.SSLStreams$InputStream.read(SSLStreams.java:522)
        at platform/jdk.httpserver@12.0.1/sun.net.httpserver.SSLStreams$InputStream.read(SSLStreams.java:591)
        at platform/jdk.httpserver@12.0.1/sun.net.httpserver.Request.readLine(Request.java:80)
        at platform/jdk.httpserver@12.0.1/sun.net.httpserver.Request.<init>(Request.java:50)
        at platform/jdk.httpserver@12.0.1/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:551)
        at platform/jdk.httpserver@12.0.1/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
        at platform/jdk.httpserver@12.0.1/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:442)
        at platform/jdk.httpserver@12.0.1/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:408)
        at java.base@12.0.1/java.lang.Thread.run(Thread.java:835)
   3) Thread[id=45, name=elasticsearch[node_s1][generic][T#2], state=RUNNABLE, group=TGRP-AzureDiscoveryClusterFormationTests]
        at java.base@12.0.1/java.net.SocketInputStream.socketRead0(Native Method)
        at java.base@12.0.1/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
        at java.base@12.0.1/java.net.SocketInputStream.read(SocketInputStream.java:168)
        at java.base@12.0.1/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base@12.0.1/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
        at java.base@12.0.1/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:165)
        at java.base@12.0.1/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
        at java.base@12.0.1/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1180)
        at java.base@12.0.1/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1091)
        at java.base@12.0.1/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at app//org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at app//org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at app//org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at app//org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
        at app//org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at app//org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at app//org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at app//org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at app//org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at app//org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at app//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at app//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at app//com.microsoft.windowsazure.management.compute.HostedServiceOperationsImpl.getDetailed(HostedServiceOperationsImpl.java:1814)
        at app//org.elasticsearch.cloud.azure.classic.management.AzureComputeServiceImpl.lambda$getServiceDetails$0(AzureComputeServiceImpl.java:102)
        at app//org.elasticsearch.cloud.azure.classic.management.AzureComputeServiceImpl$$Lambda$1727/0x0000000801793840.run(Unknown Source)
        at java.base@12.0.1/java.security.AccessController.executePrivileged(AccessController.java:781)
        at java.base@12.0.1/java.security.AccessController.doPrivileged(AccessController.java:551)
        at app//org.elasticsearch.cloud.azure.classic.management.AzureComputeServiceImpl.getServiceDetails(AzureComputeServiceImpl.java:101)
        at app//org.elasticsearch.discovery.azure.classic.AzureSeedHostsProvider.getSeedAddresses(AzureSeedHostsProvider.java:155)
        at app//org.elasticsearch.discovery.DiscoveryModule.lambda$new$3(DiscoveryModule.java:127)
        at app//org.elasticsearch.discovery.DiscoveryModule$$Lambda$1318/0x000000080168c840.getSeedAddresses(Unknown Source)
        at app//org.elasticsearch.discovery.SeedHostsResolver$1.doRun(SeedHostsResolver.java:225)
        at app//org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:758)
        at app//org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.base@12.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base@12.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base@12.0.1/java.lang.Thread.run(Thread.java:835)
   4) Thread[id=44, name=elasticsearch[node_s0][generic][T#2], state=RUNNABLE, group=TGRP-AzureDiscoveryClusterFormationTests]
        at java.base@12.0.1/java.net.SocketInputStream.socketRead0(Native Method)
        at java.base@12.0.1/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
        at java.base@12.0.1/java.net.SocketInputStream.read(SocketInputStream.java:168)
        at java.base@12.0.1/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base@12.0.1/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
        at java.base@12.0.1/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:165)
        at java.base@12.0.1/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
        at java.base@12.0.1/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1180)
        at java.base@12.0.1/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1091)
        at java.base@12.0.1/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at app//org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at app//org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at app//org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at app//org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
        at app//org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at app//org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at app//org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at app//org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at app//org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at app//org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at app//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at app//org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at app//com.microsoft.windowsazure.management.compute.HostedServiceOperationsImpl.getDetailed(HostedServiceOperationsImpl.java:1814)
        at app//org.elasticsearch.cloud.azure.classic.management.AzureComputeServiceImpl.lambda$getServiceDetails$0(AzureComputeServiceImpl.java:102)
        at app//org.elasticsearch.cloud.azure.classic.management.AzureComputeServiceImpl$$Lambda$1727/0x0000000801793840.run(Unknown Source)
        at java.base@12.0.1/java.security.AccessController.executePrivileged(AccessController.java:781)
        at java.base@12.0.1/java.security.AccessController.doPrivileged(AccessController.java:551)
        at app//org.elasticsearch.cloud.azure.classic.management.AzureComputeServiceImpl.getServiceDetails(AzureComputeServiceImpl.java:101)
        at app//org.elasticsearch.discovery.azure.classic.AzureSeedHostsProvider.getSeedAddresses(AzureSeedHostsProvider.java:155)
        at app//org.elasticsearch.discovery.DiscoveryModule.lambda$new$3(DiscoveryModule.java:127)
        at app//org.elasticsearch.discovery.DiscoveryModule$$Lambda$1318/0x000000080168c840.getSeedAddresses(Unknown Source)
        at app//org.elasticsearch.discovery.SeedHostsResolver$1.doRun(SeedHostsResolver.java:225)
        at app//org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:758)
        at app//org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.base@12.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base@12.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base@12.0.1/java.lang.Thread.run(Thread.java:835)
```

I were unable to reproduce this locally with the reproduction line:

```
 ./gradlew :plugins:discovery-azure-classic:test --tests "org.elasticsearch.discovery.azure.classic.AzureDiscoveryClusterFormationTests"   -Dtests.seed=C8A0CB3379E68CC5   -Dtests.security.manager=true   -Dtests.locale=en-US   -Dtests.timezone=Etc/UTC   -Dcompiler.java=12   -Druntime.java=12 

```

Following warnings at the end of the test might be relevant:

```
[2019-06-09T18:31:53,071][INFO ][o.a.h.i.e.RetryExec      ] [node_s1] I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://127.0.0.1:43806: The target server failed to respond
[2019-06-09T18:31:53,071][INFO ][o.a.h.i.e.RetryExec      ] [node_s0] I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://127.0.0.1:43806: The target server failed to respond
[2019-06-09T18:31:53,073][INFO ][o.a.h.i.e.RetryExec      ] [node_s1] Retrying request to {s}->https://127.0.0.1:43806
[2019-06-09T18:31:53,073][INFO ][o.a.h.i.e.RetryExec      ] [node_s0] Retrying request to {s}->https://127.0.0.1:43806
```

Gradle build scan link: https://scans.gradle.com/s/rxfo7h4uyrvbw

Will mute this, since it fails around once per week:

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:AzureDiscoveryClusterFormationTests),sort:!(time,desc))

**Comment by original-brownbear** [comment]
Think this was just a broken CI (super slow) run.
The logs contain:

```

java.lang.OutOfMemoryError: Requested array size exceeds VM limit
--
Dumping heap to /var/lib/jenkins/workspace/elastic+elasticsearch+7.2+matrix-java-periodic/ES_BUILD_JAVA/openjdk12/ES_RUNTIME_JAVA/java12/nodes/immutable&&linux&&docker/modules/lang-painless/build/heapdump/java_pid146574.hprof ...
Heap dump file created [365621873 bytes in 3.104 secs]


```

and it seems the IT cluster didn't even form properly (timeout on cluster formation). I opened #43057 regardless to make the situation a little more stable and failures easier to interpret.

**Comment by henningandersen** [comment]
I think the heap dump and OOM is expected and not part of this issue. It is provoked by WhenThingsGoWrongTests.testOutOfMemoryError. I downloaded the heap dump and it contains only around 26MB live data. Also, the message

```
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
```

just means that the max array size limit of the JVM is exceeded (typically max is Integer.MAX_VALUE minus a few).

**Comment by ywelsch** [comment]
can we close this?

**Comment by original-brownbear** [comment]
@ywelsch no I don't think so. Even if #43057 made this much less likely we still had a node hanging on shutdown here and we made no changes to the shutdown logic itself. I'll look into this again shortly and see if this happened in any build that included my changes.

**Comment by original-brownbear** [comment]
Haven't see this happen again after recent changes to the shutdown logic. Closing until it reappears.
