### ISSUE TITLE
[CI] Failure in FlushIT.testSyncedFlushSkipOutOfSyncReplicas

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#43086]
`FlushIT.testSyncedFlushSkipOutOfSyncReplicas` failed in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/23/console

The error is:

```
java.lang.AssertionError: 
Expected: <3>
     but: was <0>
	at __randomizedtesting.SeedInfo.seed([3FDE4EF3A7BE5684:E11048B864C14F83]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.indices.flush.FlushIT.testSyncedFlushSkipOutOfSyncReplicas(FlushIT.java:322)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

This did not reproduce locally for me using:

```
./gradlew :server:integTest --tests "org.elasticsearch.indices.flush.FlushIT.testSyncedFlushSkipOutOfSyncReplicas" -Dtests.seed=3FDE4EF3A7BE5684 -Dtests.security.manager=true -Dtests.locale=et-EE -Dtests.timezone=Pacific/Rarotonga -Dcompiler.java=12 -Druntime.java=11
```

The failure looks very similar to #29392, but since that was closed over a year ago I'm guessing the root cause of this is different and reopening that old issue wouldn't be very helpful, hence a new issue.

**Comment by ywelsch** [comment]
I increased test logging in c077f8c3c48

**Comment by droberts195** [comment]
A similar failure occurred in a 6.8 build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+multijob-unix-compatibility/os=fedora-29&&immutable/27/console

```
java.lang.AssertionError: 
Expected: <3>
     but: was <0>
	at __randomizedtesting.SeedInfo.seed([9A7AF184FEA205C6:44B4F7CF3DDD1CC1]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.indices.flush.FlushIT.testSyncedFlushSkipOutOfSyncReplicas(FlushIT.java:304)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

The repro command was:

```
./gradlew :server:integTest -Dtests.seed=9A7AF184FEA205C6 -Dtests.class=org.elasticsearch.indices.flush.FlushIT -Dtests.method="testSyncedFlushSkipOutOfSyncReplicas" -Dtests.security.manager=true -Dtests.locale=ar-LY -Dtests.timezone=America/Juneau -Dcompiler.java=12 -Druntime.java=8
```

This didn't reproduce locally on my 6.8 branch.

**Comment by original-brownbear** [comment]
I can easily reproduce this on `master` in just a few runs (~10).

**Comment by ywelsch** [comment]
> I can easily reproduce this on master in just a few runs (~10).

Please do share your full TRACE logs then, I can't get this to reproduce on my machine.

**Comment by original-brownbear** [comment]
[failed.log](https://github.com/elastic/elasticsearch/files/3280902/failed.log)

here you go :)

**Comment by original-brownbear** [comment]
Sorry the first one was truncated in the beginning ... this one is full.

[failed 2.log](https://github.com/elastic/elasticsearch/files/3281025/failed.2.log)

**Comment by original-brownbear** [comment]
This is the response that trips the assertions:

![Screenshot 2019-06-12 at 13 34 28](https://user-images.githubusercontent.com/6490959/59348295-0211dc80-8d17-11e9-85e2-5a55568f9b04.png)

**Comment by ywelsch** [comment]
The  relevant lines in the logs are:

```
[2019-06-12T13:06:09,980][TRACE][o.e.i.f.SyncedFlushService] [testSyncedFlushSkipOutOfSyncReplicas] [test][0] sending pre-synced flush request to [test][0], node[UMMLhkSwQqiFUu8KhAM0lw], [P], s[STARTED], a[id=LLa-xLEKREC1cqC-f-Leow]
[2019-06-12T13:06:09,980][TRACE][o.e.i.f.SyncedFlushService] [testSyncedFlushSkipOutOfSyncReplicas] [test][0] sending pre-synced flush request to [test][0], node[XsMvBzWmQDGSL-QtMgX1-g], [R], s[STARTED], a[id=9P1twPmTTXOZbnGF3c_R2w]
[2019-06-12T13:06:09,980][TRACE][o.e.i.f.SyncedFlushService] [testSyncedFlushSkipOutOfSyncReplicas] [test][0] sending pre-synced flush request to [test][0], node[wroPpzqsSHqjJlZN2RU4Vg], [R], s[STARTED], a[id=76whqbi-TTui7RunQKLJnw]


[2019-06-12T13:06:10,063][DEBUG][o.e.i.s.IndexShard       ] [node_t0] [test][0] shard is now inactive
[2019-06-12T13:06:10,064][TRACE][o.e.i.f.SyncedFlushService] [node_t0] [test][0] sending pre-synced flush request to [test][0], node[UMMLhkSwQqiFUu8KhAM0lw], [P], s[STARTED], a[id=LLa-xLEKREC1cqC-f-Leow]
[2019-06-12T13:06:10,064][TRACE][o.e.i.f.SyncedFlushService] [node_t0] [test][0] sending pre-synced flush request to [test][0], node[XsMvBzWmQDGSL-QtMgX1-g], [R], s[STARTED], a[id=9P1twPmTTXOZbnGF3c_R2w]
[2019-06-12T13:06:10,064][TRACE][o.e.i.f.SyncedFlushService] [node_t0] [test][0] sending pre-synced flush request to [test][0], node[wroPpzqsSHqjJlZN2RU4Vg], [R], s[STARTED], a[id=76whqbi-TTui7RunQKLJnw]
```


The problem seems to be that there are two concurrent synced flushes going on at the same time, which makes them fail. One is triggered by the test, the other is triggered by one of the nodes itself when it becomes inactive (see first line of second paragraph).

I don't understand how the shard can become inactive, given that it has an inactive time of 5 minutes.

```
[2019-06-12T13:06:06,756][DEBUG][o.e.i.IndexingMemoryController] [testSyncedFlushSkipOutOfSyncReplicas] using indexing buffer size [409.5mb] with indices.memory.shard_inactive_time [5m], indices.memory.interval [5s]
```

**Comment by original-brownbear** [comment]
@ywelsch thanks, that helped me find it :) We're mixing up ns and ms precision timestamps for the values we assign to `org.elasticsearch.index.engine.Engine#lastWriteNanos` so the conditional for the inactive timeout is incorrectly tripped. I'll open a PR shortly :)
