### ISSUE TITLE
[CI] Possible race condition in DataFrameUsageIT.testUsage

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#43123]
This just failed on my CI machine. I cannot reproduce it locally and I don't see any failures in CI (at least not yet). My branch included #42955 as the last commit, so it might be related.

```
[2019-06-11T19:01:28.403Z] > Task :x-pack:plugin:data-frame:qa:single-node-tests:integTestRunner
[2019-06-11T19:01:38.278Z] 
[2019-06-11T19:01:38.278Z] 
[2019-06-11T19:01:38.278Z] org.elasticsearch.xpack.dataframe.integration.DataFrameUsageIT > testUsage FAILED
[2019-06-11T19:01:38.278Z]     java.lang.AssertionError: expected:<3> but was:<2>
[2019-06-11T19:01:38.278Z]         at __randomizedtesting.SeedInfo.seed([E01CEC1BF84E8E22:5CBB70CF443256AB]:0)
[2019-06-11T19:01:38.278Z]         at org.junit.Assert.fail(Assert.java:88)
[2019-06-11T19:01:38.278Z]         at org.junit.Assert.failNotEquals(Assert.java:834)
[2019-06-11T19:01:38.278Z]         at org.junit.Assert.assertEquals(Assert.java:118)
[2019-06-11T19:01:38.278Z]         at org.junit.Assert.assertEquals(Assert.java:144)
[2019-06-11T19:01:38.278Z]         at org.elasticsearch.xpack.dataframe.integration.DataFrameUsageIT.testUsage(DataFrameUsageIT.java:109)
[2019-06-11T19:01:38.278Z] REPRODUCE WITH: ./gradlew :x-pack:plugin:data-frame:qa:single-node-tests:integTestRunner --tests "org.elasticsearch.xpack.dataframe.integration.DataFrameUsageIT.testUsage" -Dtests.seed=E01CEC1BF84E8E22 -Dtests.security.manager=true -Dtests.locale=tg -Dtests.timezone=BST -Dcompiler.java=12 -Druntime.java=12
[2019-06-11T19:01:38.278Z] 
[2019-06-11T19:01:38.278Z] Suite: Test class org.elasticsearch.xpack.dataframe.integration.DataFrameUsageIT
[2019-06-11T19:01:38.278Z]   1> [2019-06-12T01:01:31,333][INFO ][o.e.x.d.i.DataFrameUsageIT] [testUsage] before test
[2019-06-11T19:01:38.278Z]   1> [2019-06-12T01:01:31,337][INFO ][o.e.x.d.i.DataFrameUsageIT] [testUsage] initializing REST clients against [http://127.0.0.1:34183]
[2019-06-11T19:01:38.278Z]   1> [2019-06-12T01:01:37,256][INFO ][o.e.x.d.i.DataFrameUsageIT] [testUsage] after test
[2019-06-11T19:01:38.278Z]   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:data-frame:qa:single-node-tests:integTestRunner --tests "org.elasticsearch.xpack.dataframe.integration.DataFrameUsageIT.testUsage" -Dtests.seed=E01CEC1BF84E8E22 -Dtests.security.manager=true -Dtests.locale=tg -Dtests.timezone=BST -Dcompiler.java=12 -Druntime.java=12
[2019-06-11T19:01:38.278Z]   2> java.lang.AssertionError: expected:<3> but was:<2>
[2019-06-11T19:01:38.278Z]         at __randomizedtesting.SeedInfo.seed([E01CEC1BF84E8E22:5CBB70CF443256AB]:0)
[2019-06-11T19:01:38.278Z]         at org.junit.Assert.fail(Assert.java:88)
[2019-06-11T19:01:38.278Z]         at org.junit.Assert.failNotEquals(Assert.java:834)
[2019-06-11T19:01:38.278Z]         at org.junit.Assert.assertEquals(Assert.java:118)
[2019-06-11T19:01:38.278Z]         at org.junit.Assert.assertEquals(Assert.java:144)
[2019-06-11T19:01:38.278Z]         at org.elasticsearch.xpack.dataframe.integration.DataFrameUsageIT.testUsage(DataFrameUsageIT.java:109)
[2019-06-11T19:01:38.278Z]   2> NOTE: leaving temporary files on disk at: /var/jenkins_home/jobs/elasticsearch-pipeline/workspace/elasticsearch/x-pack/plugin/data-frame/qa/single-node-tests/build/testrun/integTestRunner/temp/org.elasticsearch.xpack.dataframe.integration.DataFrameUsageIT_E01CEC1BF84E8E22-001
[2019-06-11T19:01:38.278Z]   2> NOTE: test params are: codec=Asserting(Lucene80): {}, docValues:{}, maxPointsInLeafNode=802, maxMBSortInHeap=6.069203619856608, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@4adcda37), locale=tg, timezone=BST
[2019-06-11T19:01:38.278Z]   2> NOTE: Linux 5.1.6-200.fc29.x86_64 amd64/Oracle Corporation 12 (64-bit)/cpus=8,threads=1,free=389501872,total=536870912
[2019-06-11T19:01:38.278Z]   2> NOTE: All tests run in this JVM: [DataFrameGetAndGetStatsIT, DataFrameTaskFailedStateIT, DataFrameAuditorIT, DataFrameTransformProgressIT, DataFrameUsageIT]
[2019-06-11T19:02:10.204Z] 
[2019-06-11T19:02:10.204Z] 21 tests completed, 1 failed, 1 skipped
[2019-06-11T19:02:10.204Z] 
[2019-06-11T19:02:10.204Z] Tests with failures:
[2019-06-11T19:02:10.204Z]  - org.elasticsearch.xpack.dataframe.integration.DataFrameUsageIT.testUsage
```

**Comment by benwtrent** [comment]
@imotov https://github.com/elastic/elasticsearch/pull/43136 addresses this race condition and cleans up this test given the new behavior...

Sorry for failing your PR build :(

**Comment by benwtrent** [comment]
This hasn't re-occurred in the 8 days since #43136 was merged. Closing this issue
