### ISSUE TITLE
[TEST] testDataFrameTransformCrud failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#43139]
Might be related to https://github.com/elastic/elasticsearch/pull/42955

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=fedora-29&&immutable/30/console

https://gradle.com/s/e5jniskvmff3s

```
org.elasticsearch.xpack.dataframe.integration.DataFrameTransformIT > testDataFrameTransformCrud FAILED
    java.lang.AssertionError: 
    Expected: <STOPPED>
         but: was <STARTED>
        at __randomizedtesting.SeedInfo.seed([F59AFA81019F0ABF:48ED8B0F6EF832F1]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.dataframe.integration.DataFrameTransformIT.testDataFrameTransformCrud(DataFrameTransformIT.java:58)
REPRODUCE WITH: ./gradlew :x-pack:plugin:data-frame:qa:multi-node-tests:integTestRunner --tests "org.elasticsearch.xpack.dataframe.integration.DataFrameTransformIT.testDataFrameTransformCrud" -Dtests.seed=F59AFA81019F0ABF -Dtests.security.manager=true -Dtests.locale=it -Dtests.timezone=Asia/Ulan_Bator -Dcompiler.java=12 -Druntime.java=11
```

**Comment by ywelsch** [comment]
test muted in master, 7.x and 7.2
