### ISSUE TITLE
[CI] SearchAfterIT#testsShouldFail failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#43143]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=debian-9/32/console

https://gradle.com/s/n73yaa6tdwp34

Relevant log lines:

```
org.elasticsearch.search.searchafter.SearchAfterIT > testsShouldFail FAILED
    java.lang.AssertionError: 
    Expected: <class org.elasticsearch.search.SearchContextException>
         but: was <class org.elasticsearch.index.query.QueryShardException>
        at __randomizedtesting.SeedInfo.seed([B9852B2AEAA4EC39:4FD26A625A11A00E]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.search.searchafter.SearchAfterIT.testsShouldFail(SearchAfterIT.java:70)
REPRODUCE WITH: ./gradlew :server:integTest --tests "org.elasticsearch.search.searchafter.SearchAfterIT.testsShouldFail" -Dtests.seed=B9852B2AEAA4EC39 -Dtests.security.manager=true -Dtests.locale=en -Dtests.timezone=Africa/Tripoli -Dcompiler.java=12 -Druntime.java=8
```

**Comment by martijnvg** [comment]
Re-opening this issues, because this test also seems to fail in the 6.8 branch:
https://gradle-enterprise.elastic.co/s/vvkwso5lfb4cc

I think #48372 should also be backported to the 6.8 branch? Otherwise we should mute this test?

```
2> REPRODUCE WITH: ./gradlew ':server:integTest' -Dtests.seed=DCE07B90863F0160 -Dtests.class=org.elasticsearch.search.searchafter.SearchAfterIT -Dtests.method="testsShouldFail" -Dtests.security.manager=true -Dtests.locale=en-IE -Dtests.timezone=Etc/GMT-9 -Dcompiler.java=11 -Druntime.java=8
FAILURE 0.57s J11 | SearchAfterIT.testsShouldFail <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <class org.elasticsearch.search.SearchContextException>
   >      but: was <class org.elasticsearch.index.query.QueryShardException>
   > 	at __randomizedtesting.SeedInfo.seed([DCE07B90863F0160:2AB73AD8368A4D57]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.search.searchafter.SearchAfterIT.testsShouldFail(SearchAfterIT.java:70)
   > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jimczi** [comment]
I merged https://github.com/elastic/elasticsearch/pull/48372 in [6.8](https://github.com/elastic/elasticsearch/commit/f27e7c61b7c3386cc06447ff2ea3eccde81e0d2e). Thanks @martijnvg !
