### ISSUE TITLE
[CI] S3BlobStoreRepositoryTests#testSnapshotAndRestore failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#43146]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=ubuntu-18.04&&immutable/32/console

https://gradle.com/s/afowvrupoagpq

```
InvalidSnapshotNameException[[hx:j] Invalid snapshot name [j], snapshot with the same name already exists]
	at __randomizedtesting.SeedInfo.seed([79083D1C3A80F52D:B96F5E6FE74F081A]:0)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.initializeSnapshot(BlobStoreRepository.java:391)
	at org.elasticsearch.snapshots.SnapshotsService$2.doRun(SnapshotsService.java:414)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:758)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Another test is using same snapshot name:

```
[2019-06-12T09:38:26,203][INFO ][o.e.r.s.S3BlobStoreRepositoryTests] [testRetentionLeasesClearedOnRestore] -->  create snapshot edubftso:j
```

Not sure why #42511 has not fixed this, and how the repo content of one test leaks into another test.

Longer random snapshot names (see `randomAsciiName`) would probably help as well.

**Comment by ywelsch** [comment]
My mistake, #42511 was not properly backported
