### ISSUE TITLE
[CI] "Can't create extra config file" in Graph QA test

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#43196]
We see the following failure in CI when running the Graph QA tests:

```
Can't create extra config file for /var/lib/jenkins/workspace/elastic+elasticsearch+7.x+intake/x-pack/plugin/graph/qa/with-security/build/testclusters/integTest-0/config/roles.yml

org.gradle.api.tasks.TaskExecutionException:  Execution failed for task ':x-pack:plugin:graph:qa:with-security:integTestRunner'.

Caused by: 
java.io.UncheckedIOException:  Can't create extra config file for
Caused by: 
java.nio.file.FileAlreadyExistsException: /var/lib/jenkins/workspace/elastic+elasticsearch+7.x+intake/x-pack/plugin/graph/qa/with-security/build/testclusters/integTest-0/config/roles.yml
at org.elasticsearch.gradle.testclusters.ElasticsearchNode.lambda$copyExtraConfigFiles$9(ElasticsearchNode.java:352)
at org.elasticsearch.gradle.testclusters.ElasticsearchNode.copyExtraConfigFiles(ElasticsearchNode.java:345)
at org.elasticsearch.gradle.testclusters.ElasticsearchNode.start(ElasticsearchNode.java:323)
at org.elasticsearch.gradle.testclusters.ElasticsearchCluster.start(ElasticsearchCluster.java:215)
at org.elasticsearch.gradle.testclusters.TestClustersPlugin$2.lambda$beforeActions$1(TestClustersPlugin.java:200)
at org.elasticsearch.gradle.testclusters.TestClustersPlugin$2.beforeActions(TestClustersPlugin.java:199)
at jdk.internal.reflect.GeneratedMethodAccessor940.invoke(Unknown Source)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:376)
at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:358)
at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:346)
at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:157)
at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:131)
at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
at com.sun.proxy.$Proxy52.beforeActions(Unknown Source)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:212)
at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
[...]
```

* Reproduction line: `./gradlew :x-pack:plugin:graph:qa:with-security:integTest`

* [CI link](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/140/console)
* [Build scan link](https://scans.gradle.com/s/7ece5veus4wpa/failure?openFailures=WzBd&openStackTraces=WzJd#top=0)
* Failure frequency: This started on June 13 2019 and this specific error message ("Can't create extra config file") has occured 7 times since then.

This might be related to https://github.com/elastic/elasticsearch/pull/43033.

**Comment by atorok** [comment]
This happens on `7.x` because of a missing back-port (5e0a162ed66).
Now fixed by back-porting that change.
