### ISSUE TITLE
Why it reflected I run elasticsearch using root when I am not.

### ISSUE THREAD

**Issue by lukelee1987** [elastic/elasticsearch#43221]
```
[2019-06-14T14:27:05,845][INFO ][o.e.e.NodeEnvironment    ] [eta10] using [1] data paths, mounts [[/ (/dev/mapper/vg--root-lv--root)]], net usable_space [1.8tb], net total_space [2tb], types [ext4]
[2019-06-14T14:27:05,848][INFO ][o.e.e.NodeEnvironment    ] [eta10] heap size [26.6gb], compressed ordinary object pointers [true]
[2019-06-14T14:27:05,850][INFO ][o.e.n.Node               ] [eta10] node name [eta10], node ID [qDMaRgdWS92S_nyV3tQTJA], cluster name [wazuh-es]
[2019-06-14T14:27:05,850][INFO ][o.e.n.Node               ] [eta10] version[7.1.0], pid[23098], build[default/tar/606a173/2019-05-16T00:43:15.323135Z], OS[Linux/4.4.0-131-generic/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_201/25.201-b09]
[2019-06-14T14:27:05,850][INFO ][o.e.n.Node               ] [eta10] JVM home [/usr/lib/jvm/java-8-oracle/jre]
[2019-06-14T14:27:05,850][INFO ][o.e.n.Node               ] [eta10] JVM arguments [-Des.insecure.allow.root=true, -Des.path.home=/etc/elasticsearch-master, -Des.path.conf=/etc/elasticsearch-master/config, -Des.distribution.flavor=default, -Des.distribution.type=tar, -Des.bundled_jdk=true]
[2019-06-14T14:27:07,878][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [aggs-matrix-stats]
[2019-06-14T14:27:07,878][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [analysis-common]
[2019-06-14T14:27:07,878][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [ingest-common]
[2019-06-14T14:27:07,878][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [ingest-geoip]
[2019-06-14T14:27:07,878][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [ingest-user-agent]
[2019-06-14T14:27:07,878][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [lang-expression]
[2019-06-14T14:27:07,878][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [lang-mustache]
[2019-06-14T14:27:07,878][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [lang-painless]
[2019-06-14T14:27:07,878][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [mapper-extras]
[2019-06-14T14:27:07,878][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [parent-join]
[2019-06-14T14:27:07,879][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [percolator]
[2019-06-14T14:27:07,879][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [rank-eval]
[2019-06-14T14:27:07,879][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [reindex]
[2019-06-14T14:27:07,879][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [repository-url]
[2019-06-14T14:27:07,879][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [transport-netty4]
[2019-06-14T14:27:07,879][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [x-pack-ccr]
[2019-06-14T14:27:07,879][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [x-pack-core]
[2019-06-14T14:27:07,879][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [x-pack-deprecation]
[2019-06-14T14:27:07,879][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [x-pack-graph]
[2019-06-14T14:27:07,879][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [x-pack-ilm]
[2019-06-14T14:27:07,879][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [x-pack-logstash]
[2019-06-14T14:27:07,879][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [x-pack-ml]
[2019-06-14T14:27:07,879][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [x-pack-monitoring]
[2019-06-14T14:27:07,879][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [x-pack-rollup]
[2019-06-14T14:27:07,879][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [x-pack-security]
[2019-06-14T14:27:07,880][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [x-pack-sql]
[2019-06-14T14:27:07,880][INFO ][o.e.p.PluginsService     ] [eta10] loaded module [x-pack-watcher]
[2019-06-14T14:27:07,880][INFO ][o.e.p.PluginsService     ] [eta10] no plugins loaded
[2019-06-14T14:27:08,150][INFO ][i.n.u.i.PlatformDependent] [eta10] Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
[2019-06-14T14:27:12,018][INFO ][o.e.x.s.a.s.FileRolesStore] [eta10] parsed [0] roles from file [/etc/elasticsearch-master/config/roles.yml]
[2019-06-14T14:27:12,270][INFO ][i.n.u.i.PlatformDependent] [eta10] Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
[2019-06-14T14:27:12,632][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [eta10] [controller/23295] [Main.cc@109] controller (64 bit): Version 7.1.0 (Build a8ee6de8087169) Copyright (c) 2019 Elasticsearch BV
[2019-06-14T14:27:13,059][DEBUG][o.e.a.ActionModule       ] [eta10] Using REST wrapper from plugin org.elasticsearch.xpack.security.Security
[2019-06-14T14:27:13,749][INFO ][o.e.d.DiscoveryModule    ] [eta10] using discovery type [zen] and seed hosts providers [settings]
[2019-06-14T14:27:14,572][INFO ][o.e.n.Node               ] [eta10] initialized
[2019-06-14T14:27:14,572][INFO ][o.e.n.Node               ] [eta10] starting ...
[2019-06-14T14:27:14,818][INFO ][o.e.t.TransportService   ] [eta10] publish_address {10.0.106.144:9300}, bound_addresses {10.0.106.144:9300}
[2019-06-14T14:27:14,835][INFO ][o.e.b.BootstrapChecks    ] [eta10] bound or publishing to a non-loopback address, enforcing bootstrap checks
ERROR: [1] bootstrap checks failed
[1]: initial heap size [2147483648] not equal to maximum heap size [32210157568]; this can cause resize pauses and prevents mlockall from locking the entire heap
[2019-06-14T14:27:14,849][INFO ][o.e.n.Node               ] [eta10] stopping ...
2019-06-14 14:27:14,851 pool-1-thread-1 ERROR Unable to unregister MBeans java.security.AccessControlException: access denied ("javax.management.MBeanServerPermission" "createMBeanServer")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:465)
        at org.apache.logging.log4j.core.jmx.Server.unregisterLoggerContext(Server.java:248)
        at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:340)
        at org.apache.logging.log4j.core.LoggerContext$1.run(LoggerContext.java:281)
        at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry$RegisteredCancellable.run(DefaultShutdownCallbackRegistry.java:109)
        at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:74)
        at java.lang.Thread.run(Thread.java:748)
```
Hi I am running using a normal user account but why is reflected I should not run using root?

**Comment by tvernum** [comment]
Hi @lukelee1987 
Thanks very much for your interest in Elasticsearch.

I don't see anything in your log related to running as `root`. Your node failed to start because you failed the [heap size bootstrap check](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/_heap_size_check.html)
```
ERROR: [1] bootstrap checks failed
[1]: initial heap size [2147483648] not equal to maximum heap size [32210157568]; this can cause resize pauses and prevents mlockall from locking the entire heap
```

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you have any further questions about this issue, we'd appreciate if you would stop by there to ask your question. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are beter suited to these sorts of troubleshooting and problem diagnosis conversations.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.

**Comment by lukelee1987** [comment]
Hi tvernum , 

May I know in this case I have to change the -Xms and -Xmx ? 

Is there any guideline on how much should I put? Now I am putting at -Xms6g / -Xmx8g. 
But it seems there is no changes. 

ERROR: [1] bootstrap checks failed
[1]: initial heap size [2147483648] not equal to maximum heap size [32210157568]; this can cause resize pauses and prevents mlockall from locking the entire heap

Kindly assist .

**Comment by tvernum** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to the forums. If you have any further questions about this issue, we'd appreciate if you would stop by there to ask your question.
