### ISSUE TITLE
[ML] BasicDistributedJobsIT.testFailOverBasics_withDataFeeder failed

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#43289]
`BasicDistributedJobsIT.testFailOverBasics_withDataFeeder` failed in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+multijob-unix-compatibility/os=opensuse/51/console

The error was:

```
FAILURE 30.6s J2 | BasicDistributedJobsIT.testFailOverBasics_withDataFeeder <<< FAILURES!
   > Throwable #1: java.lang.AssertionError
   > 	at __randomizedtesting.SeedInfo.seed([59A83934B7E437AD:B61D65CF70E32920]:0)
   > 	at org.elasticsearch.xpack.ml.support.BaseMlIntegTestCase.lambda$awaitJobOpenedAndAssigned$4(BaseMlIntegTestCase.java:360)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:884)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:858)
   > 	at org.elasticsearch.xpack.ml.support.BaseMlIntegTestCase.awaitJobOpenedAndAssigned(BaseMlIntegTestCase.java:355)
   > 	at org.elasticsearch.xpack.ml.integration.BasicDistributedJobsIT.testFailOverBasics_withDataFeeder(BasicDistributedJobsIT.java:135)
   > 	at java.lang.Thread.run(Thread.java:748)
```

The REPRO command was:

```
./gradlew :x-pack:plugin:ml:internalClusterTest -Dtests.seed=59A83934B7E437AD -Dtests.class=org.elasticsearch.xpack.ml.integration.BasicDistributedJobsIT -Dtests.method="testFailOverBasics_withDataFeeder" -Dtests.security.manager=true -Dtests.locale=es-PY -Dtests.timezone=Asia/Khandyga -Dcompiler.java=12 -Druntime.java=8
```

The relevant section of the log was:

```
  1> [2019-06-17T23:49:02,087][INFO ][o.e.n.Node               ] [testFailOverBasics_withDataFeeder] closing ...
  1> [2019-06-17T23:49:05,059][INFO ][o.e.c.s.MasterService    ] [node_t1] zen-disco-elected-as-master ([1] nodes joined)[{node_t3}{F0l-tq76TI60eq2TU4HtCQ}{lJgucNlpQ5-qPNDcuylwAg}{127.0.0.1}{127.0.0.1:37001}{ml.machine_memory=63329808384, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true}], reason: new_master {node_t1}{4fMz7FWVTaehUtnERNDPvQ}{VsYWGtcaSEig_svhD_4fqg}{127.0.0.1}{127.0.0.1:46717}{ml.machine_memory=63329808384, xpack.installed=true, ml.max_open_jobs=20, ml.enabled=true}
  1> [2019-06-17T23:49:05,064][INFO ][o.e.c.s.ClusterApplierService] [node_t3] detected_master {node_t1}{4fMz7FWVTaehUtnERNDPvQ}{VsYWGtcaSEig_svhD_4fqg}{127.0.0.1}{127.0.0.1:46717}{ml.machine_memory=63329808384, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true}, reason: apply cluster state (from master [master {node_t1}{4fMz7FWVTaehUtnERNDPvQ}{VsYWGtcaSEig_svhD_4fqg}{127.0.0.1}{127.0.0.1:46717}{ml.machine_memory=63329808384, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true} committed version [36]])
  1> [2019-06-17T23:49:05,070][WARN ][o.e.d.z.PublishClusterStateAction] [node_t1] publishing cluster state with version [36] failed for the following nodes: [[{node_t0}{B5dBeqqFTD6iHzCYKFDmRw}{S0gkaeEmStqDxKO7UsYoCQ}{127.0.0.1}{127.0.0.1:34368}{ml.machine_memory=63329808384, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true}]]
  1> [2019-06-17T23:49:05,071][INFO ][o.e.c.s.ClusterApplierService] [node_t1] new_master {node_t1}{4fMz7FWVTaehUtnERNDPvQ}{VsYWGtcaSEig_svhD_4fqg}{127.0.0.1}{127.0.0.1:46717}{ml.machine_memory=63329808384, xpack.installed=true, ml.max_open_jobs=20, ml.enabled=true}, reason: apply cluster state (from master [master {node_t1}{4fMz7FWVTaehUtnERNDPvQ}{VsYWGtcaSEig_svhD_4fqg}{127.0.0.1}{127.0.0.1:46717}{ml.machine_memory=63329808384, xpack.installed=true, ml.max_open_jobs=20, ml.enabled=true} committed version [36] source [zen-disco-elected-as-master ([1] nodes joined)[{node_t3}{F0l-tq76TI60eq2TU4HtCQ}{lJgucNlpQ5-qPNDcuylwAg}{127.0.0.1}{127.0.0.1:37001}{ml.machine_memory=63329808384, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true}]]])
  1> [2019-06-17T23:49:05,100][INFO ][o.e.c.s.MasterService    ] [node_t1] zen-disco-node-failed({node_t0}{B5dBeqqFTD6iHzCYKFDmRw}{S0gkaeEmStqDxKO7UsYoCQ}{127.0.0.1}{127.0.0.1:34368}{ml.machine_memory=63329808384, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true}), reason(transport disconnected)[{node_t0}{B5dBeqqFTD6iHzCYKFDmRw}{S0gkaeEmStqDxKO7UsYoCQ}{127.0.0.1}{127.0.0.1:34368}{ml.machine_memory=63329808384, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true} transport disconnected], reason: removed {{node_t0}{B5dBeqqFTD6iHzCYKFDmRw}{S0gkaeEmStqDxKO7UsYoCQ}{127.0.0.1}{127.0.0.1:34368}{ml.machine_memory=63329808384, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true},}
  1> [2019-06-17T23:49:05,115][INFO ][o.e.c.s.ClusterApplierService] [node_t3] removed {{node_t0}{B5dBeqqFTD6iHzCYKFDmRw}{S0gkaeEmStqDxKO7UsYoCQ}{127.0.0.1}{127.0.0.1:34368}{ml.machine_memory=63329808384, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true},}, reason: apply cluster state (from master [master {node_t1}{4fMz7FWVTaehUtnERNDPvQ}{VsYWGtcaSEig_svhD_4fqg}{127.0.0.1}{127.0.0.1:46717}{ml.machine_memory=63329808384, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true} committed version [37]])
  1> [2019-06-17T23:49:05,130][INFO ][o.e.i.s.IndexShard       ] [node_t3] [.ml-annotations-6][0] primary-replica resync completed with 0 operations
  1> [2019-06-17T23:49:05,140][INFO ][o.e.i.s.IndexShard       ] [node_t3] [.ml-anomalies-shared][1] primary-replica resync completed with 0 operations
  1> [2019-06-17T23:49:05,146][INFO ][o.e.i.s.IndexShard       ] [node_t3] [.ml-state][1] primary-replica resync completed with 0 operations
  1> [2019-06-17T23:49:05,153][INFO ][o.e.c.s.ClusterApplierService] [node_t1] removed {{node_t0}{B5dBeqqFTD6iHzCYKFDmRw}{S0gkaeEmStqDxKO7UsYoCQ}{127.0.0.1}{127.0.0.1:34368}{ml.machine_memory=63329808384, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true},}, reason: apply cluster state (from master [master {node_t1}{4fMz7FWVTaehUtnERNDPvQ}{VsYWGtcaSEig_svhD_4fqg}{127.0.0.1}{127.0.0.1:46717}{ml.machine_memory=63329808384, xpack.installed=true, ml.max_open_jobs=20, ml.enabled=true} committed version [37] source [zen-disco-node-failed({node_t0}{B5dBeqqFTD6iHzCYKFDmRw}{S0gkaeEmStqDxKO7UsYoCQ}{127.0.0.1}{127.0.0.1:34368}{ml.machine_memory=63329808384, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true}), reason(transport disconnected)[{node_t0}{B5dBeqqFTD6iHzCYKFDmRw}{S0gkaeEmStqDxKO7UsYoCQ}{127.0.0.1}{127.0.0.1:34368}{ml.machine_memory=63329808384, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true} transport disconnected]]])
  1> [2019-06-17T23:49:05,166][INFO ][o.e.i.s.IndexShard       ] [node_t1] [.ml-state][3] primary-replica resync completed with 0 operations
  1> [2019-06-17T23:49:05,171][WARN ][o.e.x.m.MlAssignmentNotifier] [node_t1] [fail-over-basics_with-data-feeder-job] No node found to start datafeed [data_feed_id]. Reasons [awaiting reassignment after node loss]
  1> [2019-06-17T23:49:05,275][WARN ][o.e.c.r.a.AllocationService] [node_t1] [.ml-notifications][0] marking unavailable shards as stale: [AEP-nTeTR_-Ad-0QHqwHRA]
  1> [2019-06-17T23:49:05,627][INFO ][o.e.c.r.a.AllocationService] [node_t1] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[.ml-anomalies-shared][2], [.ml-config][0]] ...]).
  1> [2019-06-17T23:49:05,670][WARN ][o.e.x.m.MlAssignmentNotifier] [node_t1] [fail-over-basics_with-data-feeder-job] No node found to start datafeed [data_feed_id]. Reasons [cannot start datafeed [data_feed_id], because the job's [fail-over-basics_with-data-feeder-job] state is stale]
  1> [2019-06-17T23:49:12,095][INFO ][o.e.n.Node               ] [testFailOverBasics_withDataFeeder] closed
  1> [2019-06-17T23:49:12,095][INFO ][o.e.x.m.j.p.a.o.AutoDetectResultProcessor] [node_t0] [fail-over-basics_with-data-feeder-job] 0 buckets parsed from autodetect output
  1> [2019-06-17T23:49:22,428][INFO ][o.e.x.m.i.BasicDistributedJobsIT] [testFailOverBasics_withDataFeeder] [BasicDistributedJobsIT#testFailOverBasics_withDataFeeder]: Cleaning up datafeeds and jobs after test
```

**Comment by droberts195** [comment]
I am pretty sure the problem here is that the random node that was shut down was the master node and when a new master node was elected it had an empty ML memory tracker.  This led to the assignment of the job to a new node being deferred until after a memory tracker refresh.  Then the job should get reassigned either when there is another cluster state update or when a timer triggers.  There weren't any cluster state updates after the memory refresh completed (because it's a test cluster that's doing nothing except our test) and the default timer interval is 30 seconds, which is less than the time we wait for the job to be assigned.

So, there are two possible solutions: either increase the length of time we wait for the job to be assigned to 31 seconds or decrease the timer interval for periodic persistent task assignment rechecks to 1 second.
