### ISSUE TITLE
DataFrameTransformIT.testGetStats failure - date formatting error on 7.x

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#43324]
the tests fails non reproducibly
```
REPRODUCE WITH: ./gradlew :client:rest-high-level:integTestRunner --tests "org.elasticsearch.client.DataFrameTransformIT.testGetStats" -Dtests.seed=20C411A7A28CEBE -Dtests.security.manager=true -Dtests.locale=fr -Dtests.timezone=Asia/Urumqi -Dcompiler.java=12 -Druntime.java=8
```
https://scans.gradle.com/s/7ewwtblzmrbtc/tests/43nmsh6ur4gh6-t7wzgf4duds5a

Assertion stacktrace
```

java.lang.AssertionError: expected:<STARTED> but was:<STOPPED>
--
at __randomizedtesting.SeedInfo.seed([20C411A7A28CEBE:953D9FEC55DC36EB]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:144)
at org.elasticsearch.client.DataFrameTransformIT.lambda$testGetStats$4(DataFrameTransformIT.java:367)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:900)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:874)
at org.elasticsearch.client.DataFrameTransformIT.testGetStats(DataFrameTransformIT.java:363)


```

From logs that looks suspicious
```
[2019-06-18T08:46:06,487][ERROR][o.e.x.m.j.p.a.w.JsonDataToProcessWriter] [node-0] Cannot parse timestamp '' as epoch value
```

```
[2019-06-18T08:47:38,826][ERROR][o.e.x.i.IndexLifecycleRunner] [node-0] policy [my_policy] for index [my_index] failed on step [{"phase":"warm","action":"shrink","name":"shrink"}]. Moving to ERROR step
--
java.lang.IllegalArgumentException: the number of target shards [3] must be less that the number of source shards [2]
at org.elasticsearch.cluster.metadata.IndexMetaData.selectShrinkShards(IndexMetaData.java:1599) ~[elasticsearch-7.3.0-SNAPSHOT.jar:7.3.0-SNAPSHOT]

[2019-06-18T08:47:38,826][ERROR][o.e.x.i.IndexLifecycleRunner] [node-0] policy [my_policy] for index [my_index] failed on step [{"phase":"warm","action":"shrink","name":"shrink"}]. Moving to ERROR step
--
java.lang.IllegalArgumentException: the number of target shards [3] must be less that the number of source shards [2]
at org.elasticsearch.cluster.metadata.IndexMetaData.selectShrinkShards(IndexMetaData.java:1599) ~[elasticsearch-7.3.0-SNAPSHOT.jar:7.3.0-SNAPSHOT]
```

**Comment by pgomulka** [comment]
Not sure how this `''` timestamp could end up here. Could this be a left over from previous tests?
All the tests are using the same index `transform-source`. Would randomizing the suffix of that index help here? (can't reproduce :[ ) 
the test that run just before is `testCreateDelete`

**Comment by jbaiera** [comment]
Another instance of this today but on 7.2. Same assertion error:

Scan: https://scans.gradle.com/s/sytohsmljec54
Jenkins: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8,nodes=immutable&&linux&&docker/30/

**Comment by jbaiera** [comment]
This has been failing intermittently for at least the last week. I'm going to go ahead and mute this test.
