### ISSUE TITLE
Indexing failures at startup (ES & Kibana 7.1.1 with Docker Swarm)

### ISSUE THREAD

**Issue by j-klemm** [elastic/elasticsearch#43345]
I can move this to Kibana repo if this issue is better suited for it, but the errors are coming through the ES error logs.
**See the screen capture that I attached, that's the best way to see the problem!**
[Screen.Recording.2019-06-11.at.2.52.46.PM.zip](https://github.com/elastic/elasticsearch/files/3302951/Screen.Recording.2019-06-11.at.2.52.46.PM.zip)

**The issue**
When using ElasticSearch & Kibana deployed on a Docker Swarm, I can only successfully create index patterns & visualize data about half the time. I am just trying to set it up properly to start ingesting data, and I use the Kibana sample data to confirm that ES is working as expected. About half the time, after I initialize Docker in a Docker Stack, I am prompted to create an index pattern for the sample data, which I perform successfully. When I then go to visualize the sample data, it prompts me to create an index pattern again. 

**Steps to reproduce**:

**NOTE:** This seems to be a "random" issue, in that I've spun up clusters several times with identical setups (I use Ansible to configure EC2s, Docker, ElasticSearch & Kibana identically each time). I see the errors below about half the time. 

 1. Set up ElasticSearch & Kibana 7.1.1 cluster using Docker Stack with Docker-CE version > 17; use replicated ElasticSearch service, and Kibana in Global mode. My setup is very similar to [Elastic's documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html). See docker-compose.yml at bottom.
 2. Start the stack 
 3. Visit Kibana dashboard and import sample data
4. Create index pattern 
5. Try to visualize/create dashboard.

**Setup**
Several EC2s running CentOS 7.5 in a Docker Swarm. Kibana & Elasticsearch 7.1.1 on Docker-CE 18.09. 
Running a Docker Stack with a Docker Service of ES and Kibana on each Docker node. Load balancing and clustering is handled via an overlay network. (I don't _think_ this problem is due to anything in Docker or clustering, but I have had problems with it in the past. 
No elasticsearch.yml file; I'm passing in as environment settings using Docker. 

**Logs**

Aliasing error:
`
Jun 18 17:59:47 ip-10-30-10-103.ec2.internal elasticsearch[3031]: {"type": "server", "timestamp": "2019-06-18T17:59:47,366+0000", "level": "DEBUG", "component": "o.e.a.a.i.a.TransportIndicesAliasesAction", "cluster.name": "docker-cluster", "node.name": "elasticsearch", "cluster.uuid": "1OnV0QoiRxmssfYgG5kxQw", "node.id": "-wdfn5u4QuaFwLqFgP3Dww",  "message": "failed to perform aliases" ,
Jun 18 17:59:47 ip-10-30-10-103.ec2.internal elasticsearch[3031]: "stacktrace": ["org.elasticsearch.indices.InvalidAliasNameException: Invalid alias name [.kibana], an index exists with the same name as the alias",
Jun 18 17:59:47 ip-10-30-10-103.ec2.internal elasticsearch[3031]: "at org.elasticsearch.cluster.metadata.AliasValidator.validateAlias(AliasValidator.java:93) ~[elasticsearch-7.1.1.jar:7.1.1]",
Jun 18 17:59:47 ip-10-30-10-103.ec2.internal elasticsearch[3031]: "at org.elasticsearch.cluster.metadata.MetaDataIndexAliasesService.lambda$innerExecute$2(MetaDataIndexAliasesService.java:131) ~[elasticsearch-7.1.1.jar:7.1.1]",
.....
`
RemoteTransport error - I see this repeated 3 or 4 times before it turns GREEN again 
`
Jun 18 17:59:47 ip-10-30-10-103.ec2.internal elasticsearch[3031]: {"type": "server", "timestamp": "2019-06-18T17:59:47,761+0000", "level": "INFO", "component": "o.e.c.m.MetaDataMappingService", "cluster.name": "docker-cluster", "node.name": "elasticsearch", "cluster.uuid": "1OnV0QoiRxmssfYgG5kxQw", "node.id": "-wdfn5u4QuaFwLqFgP3Dww",  "message": "[.kibana/QOlG0ODsSDSMxpJRnbW-Tg] create_mapping [_doc]"  }
Jun 18 17:59:48 ip-10-30-10-103.ec2.internal elasticsearch[3031]: {"type": "server", "timestamp": "2019-06-18T17:59:48,566+0000", "level": "INFO", "component": "o.e.c.r.a.AllocationService", "cluster.name": "docker-cluster", "node.name": "elasticsearch", "cluster.uuid": "1OnV0QoiRxmssfYgG5kxQw", "node.id": "-wdfn5u4QuaFwLqFgP3Dww",  "message": "Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[.kibana][0]] ...])."  }
Jun 18 18:00:01 ip-10-30-10-103.ec2.internal elasticsearch[3031]: {"type": "server", "timestamp": "2019-06-18T18:00:01,069+0000", "level": "INFO", "component": "o.e.c.m.MetaDataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "elasticsearch", "cluster.uuid": "1OnV0QoiRxmssfYgG5kxQw", "node.id": "-wdfn5u4QuaFwLqFgP3Dww",  "message": "adding template [.management-beats] for index patterns [.management-beats]"  }
Jun 18 18:00:01 ip-10-30-10-103.ec2.internal elasticsearch[3031]: {"type": "server", "timestamp": "2019-06-18T18:00:01,209+0000", "level": "DEBUG", "component": "o.e.a.s.TransportSearchAction", "cluster.name": "docker-cluster", "node.name": "elasticsearch", "cluster.uuid": "1OnV0QoiRxmssfYgG5kxQw", "node.id": "-wdfn5u4QuaFwLqFgP3Dww",  "message": "[.kibana][0], node[-wdfn5u4QuaFwLqFgP3Dww], [R], s[STARTED], a[id=H3mvgGUyTGmH-Mjhv1DPfA]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[.kibana], indicesOptions=IndicesOptions[ignore_unavailable=true, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false, ignore_throttled=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=0, batchedReduceSize=512, preFilterShardSize=128, allowPartialSearchResults=true, localClusterAlias=null, getOrCreateAbsoluteStartMillis=-1, ccsMinimizeRoundtrips=true, source={\"size\":0,\"query\":{\"terms\":{\"type\":[\"dashboard\",\"visualization\",\"search\",\"index-pattern\",\"graph-workspace\",\"timelion-sheet\"],\"boost\":1.0}},\"aggregations\":{\"types\":{\"terms\":{\"field\":\"type\",\"size\":6,\"min_doc_count\":1,\"shard_min_doc_count\":0,\"show_term_doc_count_error\":false,\"order\":[{\"_count\":\"desc\"},{\"_key\":\"asc\"}]}}}}}]" ,
Jun 18 18:00:01 ip-10-30-10-103.ec2.internal elasticsearch[3031]: "stacktrace": ["org.elasticsearch.transport.RemoteTransportException: [elasticsearch][10.0.0.3:9300][indices:data/read/search[phase/query]]",
Jun 18 18:00:01 ip-10-30-10-103.ec2.internal elasticsearch[3031]: "Caused by: java.lang.IllegalArgumentException: Fielddata is disabled on text fields by default. Set fielddata=true on [type] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.",
Jun 18 18:00:01 ip-10-30-10-103.ec2.internal elasticsearch[3031]: "at org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType.fielddataBuilder(TextFieldMapper.java:767) ~[elasticsearch-7.1.1.jar:7.1.1]",
Jun 18 18:00:01 ip-10-30-10-103.ec2.internal elasticsearch[3031]: "at org.elasticsearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:116) ~[elasticsearch-7.1.1.jar:7.1.1]",
`

Ends with this after I load sample data:
`
Jun 18 18:00:54 ip-10-30-10-103.ec2.internal elasticsearch[3031]: {"type": "server", "timestamp": "2019-06-18T18:00:54,001+0000", "level": "INFO", "component": "o.e.c.m.MetaDataMappingService", "cluster.name": "docker-cluster", "node.name": "elasticsearch", "cluster.uuid": "1OnV0QoiRxmssfYgG5kxQw", "node.id": "-wdfn5u4QuaFwLqFgP3Dww",  "message": "[.kibana/QOlG0ODsSDSMxpJRnbW-Tg] update_mapping [_doc]"  }
Jun 18 18:00:54 ip-10-30-10-103.ec2.internal elasticsearch[3031]: {"type": "server", "timestamp": "2019-06-18T18:00:54,148+0000", "level": "INFO", "component": "o.e.c.m.MetaDataMappingService", "cluster.name": "docker-cluster", "node.name": "elasticsearch", "cluster.uuid": "1OnV0QoiRxmssfYgG5kxQw", "node.id": "-wdfn5u4QuaFwLqFgP3Dww",  "message": "[.kibana/QOlG0ODsSDSMxpJRnbW-Tg] update_mapping [_doc]"  }
Jun 18 18:00:55 ip-10-30-10-103.ec2.internal elasticsearch[3031]: {"type": "server", "timestamp": "2019-06-18T18:00:55,604+0000", "level": "INFO", "component": "o.e.c.m.MetaDataMappingService", "cluster.name": "docker-cluster", "node.name": "elasticsearch", "cluster.uuid": "1OnV0QoiRxmssfYgG5kxQw", "node.id": "-wdfn5u4QuaFwLqFgP3Dww",  "message": "[.kibana/QOlG0ODsSDSMxpJRnbW-Tg] update_mapping [_doc]"  }
`

**Docker/ES Settings**
docker-compose.yml:
`ersion: '3.4'
services:
  elasticsearch:
    logging:
        driver: journald
        options:
            tag: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - discovery.seed_hosts=elasticsearch1
      - cluster.initial_master_nodes=elasticsearch,elasticsearch1
      - node.name=elasticsearch
      - network.host=0.0.0.0
      - http.host=0.0.0.0
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
...
(Identical service named elasticsearch1... possibly more if using larger cluster)
...
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    ports:
      - "5601:5601"
    logging:
        driver: journald
        options:
            tag: kibana
    networks:
      - esnet
    volumes:
      - kibanadata:/usr/share/kibana
    deploy:
      mode: global

volumes:
  esdata:
    driver: local
  kibanadata:
    driver: local
networks:
  esnet:
`

**Comment by albertzaharovits** [comment]
Hi @j-klemm ,

Thank you for the effort you put in reporting this issue!
This does indeed look like a Kibana issue, because Kibana owns the user's prefs (the index pattern). But it looks like smth tries to build an alias named `.kibana` which is a reserved index used internally. Can you think of smth in your setup that might be causing this?
Given that I suspect smth on Kibana's end, I would try to simplify the ES deployment to a single node (preferably outside Docker) and repeat the flow as you've described, and when it manifests agains get the **full** logs from kibana and ES.

Thanks again!
I will try to move this issue over to the Kibana repo.
