### ISSUE TITLE
[CI] HistoryTemplateTransformMappingsTests testTransformFields fails with NPE

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#43425]
Couldn't reproduce this. Happened once, not muting the test yet.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.1+release-tests/57/console

```
  1> [2019-06-20T07:00:03,617][INFO ][o.e.x.w.h.HistoryTemplateTransformMappingsTests] [testTransformFields] [HistoryTemplateTransformMappingsTests#testTransformFields]: cleaned up after test
  1> [2019-06-20T07:00:03,618][INFO ][o.e.x.w.h.HistoryTemplateTransformMappingsTests] [testTransformFields] after test
  2> REPRODUCE WITH: ./gradlew :x-pack:plugin:watcher:test --tests "org.elasticsearch.xpack.watcher.history.HistoryTemplateTransformMappingsTests.testTransformFields" -Dtests.seed=BBEA64F9246FD0BE -Dtests.security.manager=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=cs -Dtests.timezone=Asia/Tomsk -Dcompiler.java=12 -Druntime.java=8
  2> java.lang.NullPointerException
        at __randomizedtesting.SeedInfo.seed([BBEA64F9246FD0BE:2F3CED486D934AB5]:0)
        at org.elasticsearch.xpack.watcher.history.HistoryTemplateTransformMappingsTests.lambda$testTransformFields$1(HistoryTemplateTransformMappingsTests.java:85)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1628)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.elasticsearch.xpack.watcher.history.HistoryTemplateTransformMappingsTests.lambda$testTransformFields$2(HistoryTemplateTransformMappingsTests.java:88)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:856)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:842)
        at org.elasticsearch.xpack.watcher.history.HistoryTemplateTransformMappingsTests.testTransformFields(HistoryTemplateTransformMappingsTests.java:74)
  1> [2019-06-20T07:00:03,638][INFO ][o.e.n.Node               ] [suite] stopping ...
  1> [2019-06-20T07:00:03,638][INFO ][o.e.x.w.WatcherService   ] [suite] stopping watch service, reason [shutdown initiated]
  1> [2019-06-20T07:00:03,647][INFO ][o.e.c.s.ClusterApplierService] [node_s1] master node changed {previous [{node_s0}{Wni2cs7ySv-VFI7MFhVDqA}{xSekpQUlQ324gbs5NbnSbg}{127.0.0.1}{127.0.0.1:49524}{xpack.installed=true}], current []}, term: 1, version: 43, reason: becoming candidate: onLeaderFailure
  1> [2019-06-20T07:00:03,657][WARN ][o.e.c.NodeConnectionsService] [node_s1] failed to connect to node {node_s0}{Wni2cs7ySv-VFI7MFhVDqA}{xSekpQUlQ324gbs5NbnSbg}{127.0.0.1}{127.0.0.1:49524}{xpack.installed=true} (tried [1] times)
  1> org.elasticsearch.transport.ConnectTransportException: [node_s0][127.0.0.1:49524] connect_exception
  1> 	at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onFailure(TcpTransport.java:1299) ~[elasticsearch-7.1.2.jar:7.1.2]
  1> 	at org.elasticsearch.action.ActionListener.lambda$toBiConsumer$2(ActionListener.java:99) ~[elasticsearch-7.1.2.jar:7.1.2]
  1> 	at org.elasticsearch.common.concurrent.CompletableContext.lambda$addListener$0(CompletableContext.java:42) ~[elasticsearch-core-7.1.2.jar:7.1.2]
  1> 	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[?:1.8.0_212]
  1> 	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[?:1.8.0_212]
  1> 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_212]
  1> 	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_212]
  1> 	at org.elasticsearch.common.concurrent.CompletableContext.completeExceptionally(CompletableContext.java:57) ~[elasticsearch-core-7.1.2.jar:7.1.2]
  1> 	at org.elasticsearch.nio.SocketChannelContext.connect(SocketChannelContext.java:119) ~[elasticsearch-nio-7.1.2.jar:7.1.2]
  1> 	at org.elasticsearch.nio.EventHandler.handleConnect(EventHandler.java:97) ~[elasticsearch-nio-7.1.2.jar:7.1.2]
  1> 	at org.elasticsearch.transport.nio.TestingSocketEventHandler.handleConnect(TestingSocketEventHandler.java:43) ~[framework-7.1.2.jar:7.1.2]
  1> 	at org.elasticsearch.nio.NioSelector.attemptConnect(NioSelector.java:406) ~[elasticsearch-nio-7.1.2.jar:7.1.2]
  1> 	at org.elasticsearch.nio.NioSelector.setUpNewChannels(NioSelector.java:423) ~[elasticsearch-nio-7.1.2.jar:7.1.2]
  1> 	at org.elasticsearch.nio.NioSelector.preSelect(NioSelector.java:260) ~[elasticsearch-nio-7.1.2.jar:7.1.2]
  1> 	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:153) ~[elasticsearch-nio-7.1.2.jar:7.1.2]
  1> 	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:129) ~[elasticsearch-nio-7.1.2.jar:7.1.2]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
  1> Caused by: java.net.ConnectException: Connection refused
  1> 	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
  1> 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
  1> 	at org.elasticsearch.nio.SocketChannelContext.connect(SocketChannelContext.java:116) ~[elasticsearch-nio-7.1.2.jar:7.1.2]
  1> 	... 8 more
  1> [2019-06-20T07:00:03,660][INFO ][o.e.n.Node               ] [suite] stopped
  1> [2019-06-20T07:00:03,660][INFO ][o.e.n.Node               ] [suite] closing ...
  1> [2019-06-20T07:00:03,688][INFO ][o.e.n.Node               ] [suite] closed
  1> [2019-06-20T07:00:03,688][INFO ][o.e.n.Node               ] [suite] stopping ...
  1> [2019-06-20T07:00:03,692][INFO ][o.e.x.w.WatcherService   ] [suite] stopping watch service, reason [shutdown initiated]
  1> [2019-06-20T07:00:03,703][INFO ][o.e.n.Node               ] [suite] stopped
  1> [2019-06-20T07:00:03,703][INFO ][o.e.n.Node               ] [suite] closing ...
  1> [2019-06-20T07:00:03,733][INFO ][o.e.n.Node               ] [suite] closed
```

**Comment by jakelandis** [comment]
close this issue out, this exact error was only reported once, has not happened in the past 90 days and any errors related to this class in the past 90 days are from pull requests and have multiple other failures associated.
