### ISSUE TITLE
[CI] MultiSearchRequestTests.testEmptyFirstLineX failures

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#43464]
These two reproduce for me.

`gradlew :server:test --tests "org.elasticsearch.action.search.MultiSearchRequestTests.testEmptyFirstLine2" -Dtests.seed=D340C78210D0FC2D -Dtests.security.manager=true -Dtests.locale=sv -Dtests.timezone=America/Grand_Turk -Dcompiler.java=12 -Druntime.java=8`

`gradlew :server:test --tests "org.elasticsearch.action.search.MultiSearchRequestTests.testEmptyFirstLine1" -Dtests.seed=D340C78210D0FC2D -Dtests.security.manager=true -Dtests.locale=sv -Dtests.timezone=America/Grand_Turk -Dcompiler.java=12 -Druntime.java=8`

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+multijob-windows-compatibility/32/console

Errors:

```
 Suite: Test class org.elasticsearch.action.search.MultiSearchRequestTests
08:12:18  org.elasticsearch.action.search.MultiSearchRequestTests > testEmptyFirstLine2 FAILED
08:12:18      java.lang.IllegalArgumentException: key [query] is not supported in the metadata section
08:12:18    2> REPRODUCE WITH: gradlew :server:test --tests "org.elasticsearch.action.search.MultiSearchRequestTests.testEmptyFirstLine2" -Dtests.seed=D340C78210D0FC2D -Dtests.security.manager=true -Dtests.locale=sv -Dtests.timezone=America/Grand_Turk -Dcompiler.java=12 -Druntime.java=8  2> 
08:12:18          at __randomizedtesting.SeedInfo.seed([D340C78210D0FC2D:807E8991489FC104]:0)
08:12:18    2> java.lang.IllegalArgumentException: key [query] is not supported in the metadata section
08:12:18          at org.elasticsearch.action.search.MultiSearchRequest.readMultiLineFormat(MultiSearchRequest.java:255)
08:12:18          at __randomizedtesting.SeedInfo.seed([D340C78210D0FC2D:807E8991489FC104]:0)
08:12:18          at org.elasticsearch.rest.action.search.RestMultiSearchAction.parseMultiLineRequest(RestMultiSearchAction.java:156)
08:12:18          at org.elasticsearch.action.search.MultiSearchRequest.readMultiLineFormat(MultiSearchRequest.java:255)
08:12:18          at org.elasticsearch.rest.action.search.RestMultiSearchAction.parseMultiLineRequest(RestMultiSearchAction.java:156)
08:12:18          at org.elasticsearch.action.search.MultiSearchRequestTests.parseMultiSearchRequest(MultiSearchRequestTests.java:263)
08:12:18          at org.elasticsearch.action.search.MultiSearchRequestTests.parseMultiSearchRequest(MultiSearchRequestTests.java:263)
08:12:18          at org.elasticsearch.action.search.MultiSearchRequestTests.testEmptyFirstLine2(MultiSearchRequestTests.java:202)
08:12:18  
08:12:18          at org.elasticsearch.action.search.MultiSearchRequestTests.testEmptyFirstLine2(MultiSearchRequestTests.java:202)
08:12:18  org.elasticsearch.action.search.MultiSearchRequestTests > testEmptyFirstLine1 FAILED
08:12:18    2> REPRODUCE WITH: gradlew :server:test --tests "org.elasticsearch.action.search.MultiSearchRequestTests.testEmptyFirstLine1" -Dtests.seed=D340C78210D0FC2D -Dtests.security.manager=true -Dtests.locale=sv -Dtests.timezone=America/Grand_Turk -Dcompiler.java=12 -Druntime.java=8  2> 
08:12:18      ParsingException[Expected [START_OBJECT] but found [null]]
08:12:18    2> ParsingException[Expected [START_OBJECT] but found [null]]
08:12:18          at __randomizedtesting.SeedInfo.seed([D340C78210D0FC2D:57CE6758EA6EE5D3]:0)
08:12:18          at org.elasticsearch.search.builder.SearchSourceBuilder.parseXContent(SearchSourceBuilder.java:1052)
08:12:18          at org.elasticsearch.search.builder.SearchSourceBuilder.fromXContent(SearchSourceBuilder.java:124)
08:12:18          at __randomizedtesting.SeedInfo.seed([D340C78210D0FC2D:57CE6758EA6EE5D3]:0)
08:12:18          at org.elasticsearch.action.search.MultiSearchRequestTests.lambda$parseMultiSearchRequest$3(MultiSearchRequestTests.java:265)
08:12:18          at org.elasticsearch.search.builder.SearchSourceBuilder.parseXContent(SearchSourceBuilder.java:1052)
08:12:18          at org.elasticsearch.search.builder.SearchSourceBuilder.fromXContent(SearchSourceBuilder.java:124)
08:12:18          at org.elasticsearch.action.search.MultiSearchRequest.readMultiLineFormat(MultiSearchRequest.java:274)
08:12:18          at org.elasticsearch.action.search.MultiSearchRequestTests.lambda$parseMultiSearchRequest$3(MultiSearchRequestTests.java:265)
08:12:18          at org.elasticsearch.action.search.MultiSearchRequest.readMultiLineFormat(MultiSearchRequest.java:274)
08:12:18          at org.elasticsearch.rest.action.search.RestMultiSearchAction.parseMultiLineRequest(RestMultiSearchAction.java:156)
08:12:18          at org.elasticsearch.action.search.MultiSearchRequestTests.parseMultiSearchRequest(MultiSearchRequestTests.java:263)
08:12:18          at org.elasticsearch.action.search.MultiSearchRequestTests.testEmptyFirstLine1(MultiSearchRequestTests.java:191)
08:12:18          at org.elasticsearch.rest.action.search.RestMultiSearchAction.parseMultiLineRequest(RestMultiSearchAction.java:156)
08:12:18          at org.elasticsearch.action.search.MultiSearchRequestTests.parseMultiSearchRequest(MultiSearchRequestTests.java:263)
```

**Comment by astefan** [comment]
Also, this seems to be a Windows thing...

**Comment by romseygeek** [comment]
Can this one be closed @javanna? I think #43482 should have auto-closed this one but it seems to have missed out somehow

**Comment by javanna** [comment]
Yep, thanks for the ping, it did not automatically get closed because the corresponding PR did not go to master.

**Comment by Xavifontv** [comment]
Is the `key [query] is not supported in the metadata section` issue solvable?
