### ISSUE TITLE
Task :x-pack:qa:kerberos-tests:integTestCluster#wait fails on certain Linux builds

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#43508]
This task seems to be failing consistently on certain Linux distros on the `7.2` branch.

https://scans.gradle.com/s/rmd4c3pjg3zky

Looking at the node logs it's blowing up with the following error:

```
[2019-06-21T16:14:07,521][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-0] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: security initialization failed
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
Caused by: java.lang.IllegalStateException: security initialization failed
	at org.elasticsearch.xpack.security.Security.createComponents(Security.java:384) ~[?:?]
	at org.elasticsearch.node.Node.lambda$new$9(Node.java:438) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_212]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_212]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_212]
	at org.elasticsearch.node.Node.<init>(Node.java:441) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	at org.elasticsearch.node.Node.<init>(Node.java:251) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	... 6 more
Caused by: java.lang.IllegalArgumentException: configured service key tab file [/var/lib/jenkins/workspace/elastic+elasticsearch+7.2+multijob-unix-compatibility/os/centos-6/x-pack/qa/kerberos-tests/build/cluster/integTestCluster node0/elasticsearch-7.2.0-SNAPSHOT/config/es.keytab] does not exist
	at org.elasticsearch.xpack.security.authc.kerberos.KerberosRealm.<init>(KerberosRealm.java:100) ~[?:?]
	at org.elasticsearch.xpack.security.authc.kerberos.KerberosRealm.<init>(KerberosRealm.java:75) ~[?:?]
	at org.elasticsearch.xpack.security.authc.InternalRealms.lambda$getFactories$6(InternalRealms.java:118) ~[?:?]
	at org.elasticsearch.xpack.security.authc.Realms.initRealms(Realms.java:216) ~[?:?]
	at org.elasticsearch.xpack.security.authc.Realms.<init>(Realms.java:71) ~[?:?]
	at org.elasticsearch.xpack.security.Security.createComponents(Security.java:432) ~[?:?]
	at org.elasticsearch.xpack.security.Security.createComponents(Security.java:382) ~[?:?]
	at org.elasticsearch.node.Node.lambda$new$9(Node.java:438) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_212]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_212]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_212]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_212]
	at org.elasticsearch.node.Node.<init>(Node.java:441) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	at org.elasticsearch.node.Node.<init>(Node.java:251) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.2.0-SNAPSHOT.jar:7.2.0-SNAPSHOT]
	... 6 more
```

**Comment by mark-vieira** [comment]
@atorok Thoughts on why this would be happening only on certain distributions?

**Comment by atorok** [comment]
I ran into this recently while doing some testing. I would guess that the distributions  are non ephemeral workers and this  has to do with up-to date checks (probably miss-configured task inputs/outputs ), as in it won't happen on an ephemeral worker, but it will happen after a successful run and a clean.  I didn't get any farther than this.

**Comment by dakrone** [comment]
This has been happening again more frequently:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+multijob-unix-compatibility/os=oraclelinux-6/81/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+multijob-unix-compatibility/os=centos-6/81/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+multijob-unix-compatibility/os=oraclelinux-7/81/console

**Comment by davidkyle** [comment]
And again:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+multijob-unix-compatibility/os=centos-6/86/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+multijob-unix-compatibility/os=oraclelinux-7/86/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+multijob-unix-compatibility/os=oraclelinux-6/86/console
