### ISSUE TITLE
LicensingDocumentationIT.testGetLicense fails reproducibly

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#43504]
Failure occurred in a test run for https://github.com/elastic/elasticsearch/pull/43300, which doesn't touch anything related to licensing. Looking at build stats, it looks like this has been failing quite a bit over the past few days, it first appeared on June 18 and started happening much more frequently June 20.

[Build scan](https://scans.gradle.com/s/vsd623zv3skcu/tests/43nmsh6ur4gh6-2siz2je76h6ba?openStackTraces=WzBd)

Reproduce line (reproduces locally for me, actually I can't get it to pass under any circumstances on latest master at time of writing):
```
./gradlew :client:rest-high-level:integTestRunner --tests "org.elasticsearch.client.documentation.LicensingDocumentationIT.testGetLicense" -Dtests.seed=E1D54FD70492B663 -Dtests.security.manager=true -Dtests.locale=ln-AO -Dtests.timezone=Asia/Ulaanbaatar -Dcompiler.java=12 -Druntime.java=11
```

Stack trace:
```
java.lang.AssertionError
Expected: a string containing "client_rest-high-level_integTestCluster"
     but: was "{
  "license" : {
    "status" : "active",
    "uid" : "d4453139-7060-416e-a00c-48fe1f7e7c08",
    "type" : "trial",
    "issue_date" : "2019-06-21T20:39:10.289Z",
    "issue_date_in_millis" : 1561149550289,
    "expiry_date" : "2019-07-21T20:39:10.289Z",
    "expiry_date_in_millis" : 1563741550289,
    "max_nodes" : 1000,
    "issued_to" : "integTest",
    "issuer" : "elasticsearch",
    "start_date_in_millis" : -1
  }
}
"
at __randomizedtesting.SeedInfo.seed([E1D54FD70492B663:7FC99D833236E08F]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.client.documentation.LicensingDocumentationIT.testGetLicense(LicensingDocumentationIT.java:197)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:566)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at java.lang.Thread.run(Thread.java:834)
```

I'll mute this shortly.

**Comment by tvernum** [comment]
@atorok is this related to the move to `testclusters`?
