### ISSUE TITLE
DiskDisruptionIT testGlobalCheckpointIsSafe CI failures

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#43626]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/128/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=centos-7&&immutable/85/console

Log file: https://scans.gradle.com/s/pobyhqnfcvl2a/tests/kyv2y2z3r4v7m-enli6pteu2zb2

```
java.lang.AssertionError: 
timeout while waiting for indexing threads to stop
Expected: <true>
     but: was <false>

at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.elasticsearch.test.BackgroundIndexer.stop(BackgroundIndexer.java:294)
at org.elasticsearch.test.BackgroundIndexer.close(BackgroundIndexer.java:318)
at org.elasticsearch.discovery.DiskDisruptionIT.testGlobalCheckpointIsSafe(DiskDisruptionIT.java:148)
```

Does not reproduce
```
./gradlew :server:integTest --tests "org.elasticsearch.discovery.DiskDisruptionIT.testGlobalCheckpointIsSafe" -Dtests.seed=7FAF3020ED0C329D -Dtests.security.manager=true -Dtests.locale=en-ER -Dtests.timezone=Asia/Magadan -Dcompiler.java=12 -Druntime.java=11
```

**Comment by davidkyle** [comment]
Muted master 7c3720ab166fbb8cce71d16d6cb159d1a8c9c63f and 7.x 58d0d5c51bcafaef7b91da32b6207ace6b800295

**Comment by ywelsch** [comment]
Relevant log line:

```
WARNING: Uncaught exception in thread: Thread[elasticsearch[node_t2][write][T#2],5,TGRP-DiskDisruptionIT]
java.lang.AssertionError: noop operation should never fail at document level
	at __randomizedtesting.SeedInfo.seed([7FAF3020ED0C329D]:0)
	at org.elasticsearch.index.engine.InternalEngine.innerNoOp(InternalEngine.java:1515)
	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:914)
	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:784)
	at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:756)
	at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:713)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:256)
	at org.elasticsearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:159)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:191)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:116)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:77)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:922)
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:108)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.runWithPrimaryShardReference(TransportReplicationAction.java:397)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.lambda$doRun$0(TransportReplicationAction.java:315)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)
	at org.elasticsearch.index.shard.IndexShard.lambda$wrapPrimaryOperationPermitListener$14(IndexShard.java:2532)
	at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:112)
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:269)
	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:236)
	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2506)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryOperationPermit(TransportReplicationAction.java:863)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:311)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.handlePrimaryRequest(TransportReplicationAction.java:274)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63)
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:694)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:757)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:681)
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:695)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1591)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1213)
	at org.elasticsearch.index.engine.InternalEngine.innerNoOp(InternalEngine.java:1512)
	... 31 more
```
