### ISSUE TITLE
GoogleCloudStorageThirdPartyTests testCreateSnapshot CI failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#43646]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+third-party-tests-gcs/27/console
https://scans.gradle.com/s/722rkowxm372o/tests/qkzjyhhgpm4oy-p3xibzs6lygc2

```
org.elasticsearch.repositories.gcs.GoogleCloudStorageThirdPartyTests > testCreateSnapshot FAILED
    java.lang.AssertionError: 
    Expected: not (null or a blank string)
         but: was ""
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.repositories.gcs.GoogleCloudStorageThirdPartyTests.credentials(GoogleCloudStorageThirdPartyTests.java:45)
```

This is a reproducible failure: 
```
 ./gradlew :plugins:repository-gcs:thirdPartyTest --tests "org.elasticsearch.repositories.gcs.GoogleCloudStorageThirdPartyTests.testCreateSnapshot"   -Dtests.seed=9C03D4D965FF384B   -Dtests.security.manager=true   -Dtests.locale=es-ES   -Dtests.timezone=America/Anguilla   -Dcompiler.java=12   -Druntime.java=8
```

**Comment by original-brownbear** [comment]
This looks like an infra issue, the system property for the credentials wasn't set in the test run and the test was failed as a result. Locally this will fail the same way unless you have the environment variables for the GCS auth set correctly. I'll check with infra here.

**Comment by original-brownbear** [comment]
Infra fixed this :), should be green now for new builds.
