### ISSUE TITLE
[CI] GCS Repository Tests failing

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#43674]
GCS repository tests have started failing across 7.2, 7.x and master:

### 7.2
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+third-party-tests-gcs/41/console

```
23:11:00   [2019-06-26T23:10:59,653][WARN ][o.e.n.Node               ] [integTest-0] version [7.2.1-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
23:11:00   [2019-06-26T23:10:59,947][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [integTest-0] uncaught exception in thread [main]
23:11:00   org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load plugin class [org.elasticsearch.repositories.gcs.GoogleCloudStoragePlugin]

...

23:11:00   Caused by: java.lang.IllegalArgumentException: no JSON input found
23:11:00   	at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[?:?]
23:11:00   	at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:49) ~[?:?]
23:11:00   	at com.google.api.client.json.JsonParser.startParsing(JsonParser.java:223) ~[?:?]
23:11:00   	at com.google.api.client.json.JsonParser.parse(JsonParser.java:380) ~[?:?]
23:11:00   	at com.google.api.client.json.JsonParser.parse(JsonParser.java:355) ~[?:?]
23:11:00   	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:87) ~[?:?]
23:11:00   	at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:81) ~[?:?]
23:11:00   	at com.google.auth.oauth2.ServiceAccountCredentials.fromStream(ServiceAccountCredentials.java:336) ~[?:?]
23:11:00   	at com.google.auth.oauth2.ServiceAccountCredentials.fromStream(ServiceAccountCredentials.java:316) ~[?:?]
23:11:00   	at org.elasticsearch.repositories.gcs.GoogleCloudStorageClientSettings.lambda$loadCredential$7(GoogleCloudStorageClientSettings.java:195) ~[?:?]
23:11:00   	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_212]
23:11:00   	at org.elasticsearch.repositories.gcs.SocketAccess.doPrivilegedIOException(SocketAccess.java:44) ~[?:?]
23:11:00   	at org.elasticsearch.repositories.gcs.GoogleCloudStorageClientSettings.loadCredential(GoogleCloudStorageClientSettings.java:194) ~[?:?]
23:11:00   	at org.elasticsearch.repositories.gcs.GoogleCloudStorageClientSettings.getClientSettings(GoogleCloudStorageClientSettings.java:163) ~[?:?]
23:11:00   	at org.elasticsearch.repositories.gcs.GoogleCloudStorageClientSettings.load(GoogleCloudStorageClientSettings.java:151) ~[?:?]
23:11:00   	at org.elasticsearch.repositories.gcs.GoogleCloudStoragePlugin.reload(GoogleCloudStoragePlugin.java:79) ~[?:?]
23:11:00   	at org.elasticsearch.repositories.gcs.GoogleCloudStoragePlugin.<init>
```

### 7.x / master
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+third-party-tests-gcs/27/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+third-party-tests-gcs/30/console

```
22:39:52   2> REPRODUCE WITH: ./gradlew :plugins:repository-gcs:thirdPartyTest --tests "org.elasticsearch.repositories.gcs.GoogleCloudStorageThirdPartyTests.testListChildren" -Dtests.seed=460D209B727E911F -Dtests.security.manager=true -Dtests.locale=ta -Dtests.timezone=America/Guyana -Dcompiler.java=12 -Druntime.java=11
22:39:52   2> java.lang.AssertionError: 
22:39:52     Expected: not (null or a blank string)
22:39:52          but: was ""
22:39:52         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
22:39:52         at org.junit.Assert.assertThat(Assert.java:956)
22:39:52         at org.junit.Assert.assertThat(Assert.java:923)
22:39:52         at org.elasticsearch.repositories.gcs.GoogleCloudStorageThirdPartyTests.credentials(GoogleCloudStorageThirdPartyTests.java:45)
22:39:52 
22:39:52     java.lang.NullPointerException
```

**Comment by original-brownbear** [comment]
Infra is already on it :) + we're tracking it here https://github.com/elastic/elasticsearch/issues/43646

**Comment by tvernum** [comment]
Sorry, don't know how I missed that...
