### ISSUE TITLE
[CI] DataFrameTransformIT testStartStop failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#43677]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+multijob-unix-compatibility/os=fedora-29&&immutable/91/console

https://scans.gradle.com/s/zeltjj5fzk7yw/tests/43nmsh6ur4gh6-hr7rgc6q5tply

```
java.lang.AssertionError: 

Expected: is one of {<STARTED>, <INDEXING>}
     but: was <STOPPED>

at __randomizedtesting.SeedInfo.seed([6DAAB8E4E722084D:7D6DE052C461C4AC]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.client.DataFrameTransformIT.testStartStop(DataFrameTransformIT.java:262)
```

```
./gradlew :client:rest-high-level:integTestRunner --tests "org.elasticsearch.client.DataFrameTransformIT.testStartStop" \
  -Dtests.seed=6DAAB8E4E722084D \
  -Dtests.security.manager=true \
  -Dtests.locale=nl-BE \
  -Dtests.timezone=America/Danmarkshavn \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

**Comment by benwtrent** [comment]
ugh, this MAY be that the data frame finished executing between the call to `_start` and the stats being gathered. I can take a deeper look in a little bit.

**Comment by benwtrent** [comment]
Yep, looking at the logs:
```
[2019-06-27T06:21:56,313][INFO ][o.e.x.d.t.DataFrameTransformTask] [node-0] Data frame transform [test-stop-start] indexer has stopped
```
Where the afterTest  timestamp:
```
[2019-06-27T06:21:56,665][INFO ][o.e.c.DataFrameTransformIT] [testStartStop] after test
```

The indexer stopped due to finishing reading the index before we assert on the running state. Working on a fix now.
