### ISSUE TITLE
[CI] StableMasterDisruptionIT#testFollowerCheckerDetectsUnresponsiveNodeAfterMasterReelection fails on master

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#43698]
Build scan: https://scans.gradle.com/s/fcwvctoouoaq4

Not reproducable:
```
./gradlew :server:integTest --tests "org.elasticsearch.discovery.StableMasterDisruptionIT.testFollowerCheckerDetectsUnresponsiveNodeAfterMasterReelection" -Dtests.seed=6B6429922FACA8C -Dtests.security.manager=true -Dtests.locale=zh-CN -Dtests.timezone=Africa/Freetown -Dcompiler.java=12 -Druntime.java=11
HomeTestsStableMasterDisruptionIT » testFollowerCheckerDetectsUnresponsiveNodeAfterMasterReelection
```

```
java.lang.AssertionError
: 
failed to reach a stable cluster of [3] nodes. Tried via [node_t0]. last cluster state:
cluster uuid: C2X38C9jTci3VmJcmbk6xg [committed: true]
version: 11
state uuid: 87tOXaahTzy_1Qe4chk8Ww
from_diff: false
meta data version: 7
   coordination_metadata:
      term: 4
      last_committed_config: VotingConfiguration{DWPvvucqQ2i791Wm_YnOkw,6aNAtPFJRBWpIRmOnxmSvg,CXXU7E6NRj-mofQ-FD-B8g}
      last_accepted_config: VotingConfiguration{DWPvvucqQ2i791Wm_YnOkw,6aNAtPFJRBWpIRmOnxmSvg,CXXU7E6NRj-mofQ-FD-B8g}
      voting tombstones: []
metadata customs:
   index-graveyard: IndexGraveyard[[]]
nodes: 
   {node_t0}{DWPvvucqQ2i791Wm_YnOkw}{0yIW7ZG0RTWmUcjrGseYxw}{127.0.0.1}{127.0.0.1:42613}{dim}
   {node_t2}{CXXU7E6NRj-mofQ-FD-B8g}{VG90yihVQD6ZqofLhF4xjA}{127.0.0.1}{127.0.0.1:37397}{dim}
   {node_t3}{6aNAtPFJRBWpIRmOnxmSvg}{foWAICE8TryOkFY84kRh3Q}{127.0.0.1}{127.0.0.1:42901}{dim}, master
routing_table (version 1):
routing_nodes:
-----node_id[DWPvvucqQ2i791Wm_YnOkw][V]
-----node_id[6aNAtPFJRBWpIRmOnxmSvg][V]
-----node_id[CXXU7E6NRj-mofQ-FD-B8g][V]
---- unassigned
```

**Comment by ywelsch** [comment]
Another Debian failure, tracked in https://github.com/elastic/elasticsearch/issues/43387

```
[2019-06-27T21:18:32,855][WARN ][o.e.t.n.MockNioTransport ] [node_t0] Potentially blocked execution on network thread [elasticsearch[node_t0][transport_worker][T#2]] [RUNNABLE] [39425 milliseconds]: 
  1> java.base@11.0.3/sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
  1> java.base@11.0.3/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:533)
  1> java.base@11.0.3/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:285)
  1> app//org.elasticsearch.nio.ChannelFactory$RawChannelFactory$$Lambda$1637/0x0000000100732840.run(Unknown Source)
  1> java.base@11.0.3/java.security.AccessController.doPrivileged(Native Method)
  1> app//org.elasticsearch.nio.ChannelFactory$RawChannelFactory.accept(ChannelFactory.java:225)
  1> app//org.elasticsearch.nio.ChannelFactory$RawChannelFactory.acceptNioChannel(ChannelFactory.java:181)
  1> app//org.elasticsearch.nio.ChannelFactory.acceptNioChannel(ChannelFactory.java:55)
  1> app//org.elasticsearch.nio.ServerChannelContext.acceptChannels(ServerChannelContext.java:47)
  1> app//org.elasticsearch.nio.EventHandler.acceptChannel(EventHandler.java:45)
  1> app//org.elasticsearch.transport.nio.TestEventHandler.acceptChannel(TestEventHandler.java:51)
  1> app//org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:226)
  1> app//org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:173)
  1> app//org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:130)
  1> app//org.elasticsearch.nio.NioSelectorGroup$$Lambda$1570/0x00000001006ff440.run(Unknown Source)
  1> java.base@11.0.3/java.lang.Thread.run(Thread.java:834)
  1> [2019-06-27T21:18:33,658][WARN ][o.e.t.n.MockNioTransport ] [node_t0] Slow execution on network thread [40226 milliseconds]
  1> java.lang.RuntimeException: Slow exception on network thread
  1> 	at org.elasticsearch.transport.nio.MockNioTransport$TransportThreadWatchdog.maybeLogElapsedTime(MockNioTransport.java:358) [framework-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.transport.nio.MockNioTransport$TransportThreadWatchdog.unregister(MockNioTransport.java:350) [framework-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.transport.nio.TestEventHandler.acceptChannel(TestEventHandler.java:54) [framework-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:226) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:173) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:130) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at java.lang.Thread.run(Thread.java:834) [?:?]
  1> [2019-06-27T21:18:33,658][WARN ][o.e.t.n.MockNioTransport ] [node_t1] unexpected exception while stopping nio group
  1> java.lang.IllegalStateException: Thread was interrupted while waiting for selector to close
  1> 	at org.elasticsearch.nio.NioSelector.close(NioSelector.java:212) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.nio.NioSelectorGroup.close(NioSelectorGroup.java:147) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.transport.nio.MockNioTransport.stopInternal(MockNioTransport.java:137) [framework-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.transport.TcpTransport.lambda$doStop$15(TcpTransport.java:564) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:687) [main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
  1> 	at java.lang.Thread.run(Thread.java:834) [?:?]
  1> Caused by: java.lang.InterruptedException
  1> 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1343) ~[?:?]
  1> 	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232) ~[?:?]
  1> 	at org.elasticsearch.nio.NioSelector.close(NioSelector.java:209) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	... 7 more
```
