### ISSUE TITLE
SQL: with arrayLeniency enabled (by default in JDBC) empty array of values generate exception

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#43863]
In case of JDBC (only because `field.multi.value.leniency` is enabled by default), the following test data:

```
{ "index" : { "_index" : "mjdbctest", "_type" : "_doc", "_id" : "4" } }
{ "keys" : ["key1"],"dupKeys":["dk4"]}
{ "index" : { "_index" : "mjdbctest", "_type" : "_doc", "_id" : "3" } }
{ "keys" : [],"dupKeys":["dk3"]}
```

will generate an exception for a simple query like `SELECT * FROM mjdbctest`.

```
java.sql.SQLException: Server encountered an error [Index: 0, Size: 0]. [java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.elasticsearch.xpack.sql.execution.search.extractor.FieldHitExtractor.extractFromSource(FieldHitExtractor.java:185)
	at org.elasticsearch.xpack.sql.execution.search.extractor.FieldHitExtractor.extract(FieldHitExtractor.java:117)
	at org.elasticsearch.xpack.sql.execution.search.SearchHitRowSet.extractValue(SearchHitRowSet.java:111)
	at org.elasticsearch.xpack.sql.execution.search.SearchHitRowSet.extractValue(SearchHitRowSet.java:23)
	at org.elasticsearch.xpack.sql.execution.search.ResultRowSet.getColumn(ResultRowSet.java:37)
	at org.elasticsearch.xpack.sql.session.AbstractRowSet.column(AbstractRowSet.java:18)
	at org.elasticsearch.xpack.sql.session.RowView.forEachColumn(RowView.java:38)
	at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.lambda$createResponse$2(TransportSqlQueryAction.java:104)
	at org.elasticsearch.xpack.sql.session.RowSet.forEachRow(RowSet.java:32)
	at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.createResponse(TransportSqlQueryAction.java:102)
	at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.createResponse(TransportSqlQueryAction.java:97)
	at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.lambda$operation$0(TransportSqlQueryAction.java:80)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:61)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:61)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:61)
	at org.elasticsearch.xpack.sql.execution.search.Querier$ScrollActionListener.lambda$handleResponse$0(Querier.java:499)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:61)
	at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.lambda$clear$3(Querier.java:606)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:61)
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:85)
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:81)
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)
	at org.elasticsearch.action.search.ClearScrollController.onFreedContext(ClearScrollController.java:130)
	at org.elasticsearch.action.search.ClearScrollController.lambda$cleanScrollIds$2(ClearScrollController.java:115)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:61)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:54)
```

This one happens only in pre 7.2 versions and the reason is [this fix](https://github.com/elastic/elasticsearch/commit/0b94416cc1e1c7b871e4521eb1129dca628acffa#diff-6d292f4ab3ddfc415649c328fd2faefeR211) that was added together with Geo support for SQL.

**Comment by astefan** [comment]
7.1 (7.1.2): https://github.com/elastic/elasticsearch/commit/87c0ad106476faa177240442d45d233cda2409e8
6.8 (6.8.2): https://github.com/elastic/elasticsearch/commit/85143ff53af577178d9c7e9776b6ba9751da5a7f
