### ISSUE TITLE
 java.io.StreamCorruptedException: invalid internal transport message format, got (3,0,0,2f)

### ISSUE THREAD

**Issue by Crazy-x** [elastic/elasticsearch#43896]
java.io.StreamCorruptedException: invalid internal transport message format, got (3,0,0,2f)

**Comment by Crazy-x** [comment]
Caused by: java.io.StreamCorruptedException: invalid internal transport message format, got (3,0,0,2f)
   at org.elasticsearch.transport.TcpTransport.validateMessageHeader(TcpTransport.java:1072) ~[elasticsearch-6.5.0.jar:6.5.0]
   at org.elasticsearch.transport.netty4.Netty4SizeHeaderFrameDecoder.decode(Netty4SizeHeaderFrameDecoder.java:36) ~[transport-netty4-client-6.5.0.jar:6.5.0]
   at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-codec-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-codec-4.1.30.Final.jar:4.1.30.Final]
   ... 19 more

io.netty.handler.codec.DecoderException: java.io.StreamCorruptedException: invalid internal transport message format, got (3,0,0,2f)
   at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472) ~[netty-codec-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:405) ~[netty-codec-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:372) ~[netty-codec-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355) ~[netty-codec-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.handler.logging.LoggingHandler.channelInactive(LoggingHandler.java:167) [netty-handler-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-common-4.1.30.Final.jar:4.1.30.Final]
   at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by tvernum** [comment]
Hi @Crazy-x - when you opened this issue there was a template there with various fields to fill in.
We really need that information in order to be able to do anything useful with your report.

All you have provided is a stack trace - we don't know what you were trying to do, where this stack trace came from, what version you were running, etc. etc.

If you would like assistance with this, then we need you to update the description with these fields:
```
<!-- Bug report -->

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
```

**Comment by Crazy-x** [comment]
thanks for the reminder

**Comment by Crazy-x** [comment]
!-- Bug report -->

**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.0

**Plugins installed**: elasticsearch-analysis-ik

**JVM version** (`java -version`):1.8

**OS version** (`uname -a` if on a Unix-like system):centos 7.4 by docker

**Description of the problem including expected versus actual behavior**:
This happens all the time:
 java.io.StreamCorruptedException: invalid internal transport message format, got (3,0,0,2f),
I wonder why?

**Comment by DaveCTurner** [comment]
This message indicates something other than Elasticsearch is opening a connection to Elasticsearch and sending it invalid data. I do not think this is a bug, as there's nothing we can do in Elasticsearch to prevent this, so I am closing this issue. @Crazy-x it's normally a good idea to ask questions like this on the [forums](https://discuss.elastic.co/c/elasticsearch) instead.

**Comment by Crazy-x** [comment]
> This message indicates something other than Elasticsearch is opening a connection to Elasticsearch and sending it invalid data. I do not think this is a bug, as there's nothing we can do in Elasticsearch to prevent this, so I am closing this issue

Ok, thanks.
