### ISSUE TITLE
PrimaryAllocationIT#testForceStaleReplicaToBePromotedToPrimary fails

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#44049]
This test fails every few runs with the following `AssertionError`:

```
WARNING: Uncaught exception in thread: Thread[elasticsearch[node_td1][generic][T#3],5,TGRP-PrimaryAllocationIT]
java.lang.AssertionError: max seq. no. [-1] does not match [0]
	at __randomizedtesting.SeedInfo.seed([90343DC6CDBC76CE]:0)
	at org.elasticsearch.index.engine.ReadOnlyEngine.assertMaxSeqNoEqualsToGlobalCheckpoint(ReadOnlyEngine.java:153)
	at org.elasticsearch.index.engine.ReadOnlyEngine.ensureMaxSeqNoEqualsToGlobalCheckpoint(ReadOnlyEngine.java:144)
	at org.elasticsearch.index.engine.ReadOnlyEngine.<init>(ReadOnlyEngine.java:113)
	at org.elasticsearch.index.engine.NoOpEngine.<init>(NoOpEngine.java:54)
	at org.elasticsearch.index.shard.IndexShard.innerOpenEngineAndTranslog(IndexShard.java:1522)
	at org.elasticsearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:1475)
	at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:425)
	at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:95)
	at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:300)
	at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:93)
	at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1748)
	at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$10(IndexShard.java:2402)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:687)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

This seems to happen whenever force-allocating an empty primary on a closed index. For instance:

```
./gradlew :server:integtest --tests "org.elasticsearch.cluster.routing.PrimaryAllocationIT.testForceStaleReplicaToBePromotedToPrimary" -Dtests.seed=90343DC6CDBC76CE:727A0C1AE6CED345
```

**Comment by DaveCTurner** [comment]
NB only in `master`. I also tried this on `7.x` and it seemed unaffected. @tlrx or @dnhatn would you take a look?

**Comment by davidkyle** [comment]
A recent failure on 7.x

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=debian-8&&immutable/126/console
https://gradle.com/s/eyajbd2uvfvhi

Thanks for muting @DaveCTurner

**Comment by davidkyle** [comment]
Muted on 7.x 3f3bcb23c2d27452a2e7e3d14b1b8f34353152ac and master c9925a411f9eb463f413f74f5171db2348978750
