### ISSUE TITLE
EmptyDirTaskTests testCreateEmptyDirNoPermissions failure on Windows

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#44064]
```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([47A8DFF011E54D78:276865E3D83014EF]:0)
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at org.elasticsearch.gradle.EmptyDirTaskTests.testCreateEmptyDirNoPermissions(EmptyDirTaskTests.java:64)
```

EmptyDirTaskTests line 64 is
```
        assertFalse(newEmptyFolder.canExecute());
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-windows-compatibility/88/console
https://scans.gradle.com/s/w6m7bmsnjvo6a

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/82/console
https://scans.gradle.com/s/o6t3odaam32bc

Reproduce: `:build-tools:test`

**Comment by tvernum** [comment]
Another failure (this time on a new immutable worker)
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/os=windows-2012-r2/3/
