### ISSUE TITLE
Getting i_o_exception BigInteger on documents creation/updation

### ISSUE THREAD

**Issue by larrycinnabar** [elastic/elasticsearch#44150]
Elasticsearch 7.2, java 1.8

I'm consistently getting this message in elastic logs:
```
[2019-07-09T14:15:18,836][WARN ][o.e.t.OutboundHandler    ] [banana] send message failed [channel: Netty4TcpChannel{localAddress=/****:55054, remoteAddress=****/****:9300}]
java.io.IOException: can not write type [class java.math.BigInteger]
```
It's coming with a big stack trace, and no more debug information on what exact data it happened.

On the client side, I'm sending bulk request with dozens (sometimes hundreds) index/update requests, and some of them are returning with such an error:
`{"type":"i_o_exception","reason":"can not write type [class java.math.BigInteger]"}`
It's the only error information that is returned. 

By the index of the errored response I could find the document that caused this error. Document has no big numbers at all.

It should be something internal? I've tried to send extremely big number and the error message looks like a normal validation exception - showing the problem field, etc. 
So, this case is other issue.

**Comment by iverase** [comment]
@larrycinnabar Could you provide the stack trace? That will give us some information where the error is being thrown.

**Comment by larrycinnabar** [comment]
@iverase I've edited the issue, provided the stack trace

**Comment by iverase** [comment]
What looks suspicious is the following:

```
at org.elasticsearch.script.Script.writeTo(Script.java:470) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.action.update.UpdateRequest.writeTo(UpdateRequest.java:891) ~[elasticsearch-7.2.0.jar:7.2.0]
```

Are you using an update command with a script? I think that is the issue, the script is returning a `java.math.BigInteger` object and ES does not know how to handle it.

**Comment by iverase** [comment]
@larrycinnabar could you provide more information about how you are performing those updates?

**Comment by larrycinnabar** [comment]
@iverase,
Yeap, we have upsert script that looks like this (it's not the only script, but they all are in this put-or-append manner)

```
if (!ctx._source.containsKey('timings') || ctx._source.timings.length==0) {
	ctx._source.timings = params['timings'];
} else {
	if (params.containsKey('timings') && params['timings'] != null) {
		for (newTiming in params['timings']) {
			boolean contains = false;
			for (oldTiming in ctx._source.timings) {
				if (oldTiming.key == newTiming.key) {
					contains = true;
					break;
				}
			}
	
			if (!contains) {
				ctx._source.timings.add(newTiming);
			}
		}
	}
}
```

**Comment by iverase** [comment]
It seems related to #34656.

**Comment by larrycinnabar** [comment]
@iverase,

if I send the same document again - it might be upserted successfully.

Numbers in there are not so big, example: `1562839304884` - it's a millisecond timestamp. As size of BigInt is related to available memory, can this be a memory issue?

**Comment by stu-elastic** [comment]
This looks like we're deserializing the large value in params as a BigInt, which we can't stream.  Perhaps we should deserialize it as a `long` instead if the value will fit in `long`?

**Comment by rjernst** [comment]
The solution here is to add BigInteger support to StreamInput/StreamOutput. We discussed that last week within core/infra, and agreed it is worthwhile to add. The change should be relatively simple, as BigInteger supports reading/writing as an array of bytes, but it is not a priority, so I am marking this issue as `adoptme`.

**Comment by williamrandolph** [comment]
I'm reviewing this for a Core/Infra team issue triage. It still looks like a good "help wanted" issue so I am going to leave the issue as is.

**Comment by Kiriakos1998** [comment]
Hello @williamrandolph, if  this issue is still open I would like to work on it.

**Comment by prdoyle** [comment]
@Kiriakos1998 - did you end up working on this?
