### ISSUE TITLE
Unable to upgrade kibana - forbidden

### ISSUE THREAD

**Issue by mohmad-null** [elastic/elasticsearch#44233]
Upgrading ES and Kibana from 6.3.2 to 7.2.0.

ES upgrade is fine, but when I try and run Kibana 7.2.0 I get an exception:

```
  log   [17:01:07.628] [fatal][root] { Error: [cluster_block_exception] index [.kibana] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];
    at respond (C:\\elasticSearch\kibana-oss-7.2.0-windows-x86_64\kibana-7.2.0-windows-x86_64\node_modules\elasticsearch\src\lib\transport.js:315:15)
    at checkRespForFailure (C:\\elasticSearch\kibana-oss-7.2.0-windows-x86_64\kibana-7.2.0-windows-x86_64\node_modules\elasticsearch\src\lib\transport.js:274:7)
    at HttpConnector.<anonymous> (C:\\elasticSearch\kibana-oss-7.2.0-windows-x86_64\kibana-7.2.0-windows-x86_64\node_modules\elasticsearch\src\lib\connectors\http.js:166:7)

    at IncomingMessage.wrapper (C:\\elasticSearch\kibana-oss-7.2.0-windows-x86_64\kibana-7.2.0-windows-x86_64\node_modules\elasticsearch\node_modules\lodash\lodash.js:4935:
19)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 403,
  displayName: 'AuthorizationException',
  message:
   '[cluster_block_exception] index [.kibana] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];',
  path: '/_aliases',
  query: {},
  body:
   { error:
      { root_cause: [Array],
        type: 'cluster_block_exception',
        reason:
         'index [.kibana] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];' },
     status: 403 },
  statusCode: 403,
  response:
   '{"error":{"root_cause":[{"type":"cluster_block_exception","reason":"index [.kibana] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"}],"type":"cluster_block_ex
ception","reason":"index [.kibana] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403}',
  toString: [Function],
  toJSON: [Function] }

 FATAL  [cluster_block_exception] index [.kibana] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)]; :: {"path":"/_aliases","query":{},"body":"{\"actions\":[{\"remove
_index\":{\"index\":\".kibana\"}},{\"add\":{\"index\":\".kibana_1\",\"alias\":\".kibana\"}}]}","statusCode":403,"response":"{\"error\":{\"root_cause\":[{\"type\":\"cluster_block_ex
ception\",\"reason\":\"index [.kibana] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];\"}],\"type\":\"cluster_block_exception\",\"reason\":\"index [.kibana] blocke
d by: [FORBIDDEN/12/index read-only / allow delete (api)];\"},\"status\":403}"}
```

No plugins.

This is using the OSS version of ES, so there shouldn't be any security stuff by default right?

If I then start Kibana again it says there's a database upgrade in progress and to delete it if it doesn't complete.

**Comment by cbuescher** [comment]
Hi @mohmad-null! Your question seems better suited for the support forums over at https://discuss.elastic.co. There is an elasticsearch and a Kibana section there. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a specific problem than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

**Comment by mohmad-null** [comment]
@cbuescher - This is a bug report. I don't need support with it because I simply worked around it by deleting all the kibana databases. It's a bug because a simple upgrade didn't work and it should.

**Comment by cbuescher** [comment]
My apologies, I read this as an isolated topic. I'll move this to the kibana repo though since it seems the `.kibana` index is somehow set to read_only when it shouldn't.
