### ISSUE TITLE
third-party-tests-azure-sas fail with RepositoryVerificationException

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#44328]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+third-party-tests-azure-sas/5/

```
Error Message
RepositoryVerificationException[[test-repo] path [master] is not accessible on master node]; nested: IOException[Can not write blob master.dat]; nested: StorageException[Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.];
Stacktrace
RepositoryVerificationException[[test-repo] path [master] is not accessible on master node]; nested: IOException[Can not write blob master.dat]; nested: StorageException[Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.];
	at __randomizedtesting.SeedInfo.seed([71A84792F115622:F97C11CA19A2A43B]:0)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:671)
	at org.elasticsearch.repositories.RepositoriesService.lambda$verifyRepository$7(RepositoriesService.java:239)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:699)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Can not write blob master.dat
	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:104)
	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlobAtomic(AzureBlobContainer.java:110)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:666)
	... 5 more
Caused by: com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87)
	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:313)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:185)
	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:938)
	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:768)
	at org.elasticsearch.repositories.azure.AzureStorageService.lambda$writeBlob$15(AzureStorageService.java:312)
	at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:64)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:63)
	at org.elasticsearch.repositories.azure.AzureStorageService.writeBlob(AzureStorageService.java:311)
	at org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:115)
	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:102)
	... 7 more
```

**Comment by original-brownbear** [comment]
Looks like the SAS token set by infra is wrong here, I'll raise an issue with them.

**Comment by atorok** [comment]
@original-brownbear we could also move this issue to the infra repo

**Comment by original-brownbear** [comment]
@atorok we should still leave this open imo so people don't open it again when triaging tests?

**Comment by original-brownbear** [comment]
Seems infra fixed this now :) Closing here.
