### ISSUE TITLE
:x-pack:qa:tribe-tests-with-license:integTestCluster#wait Failure

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#44489]
Numerous intake build failures. 

Example: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+intake/124/console

Spinning up the integration node cluster in version 6.8 fails with the following trace:
```
[2019-07-17T02:40:30,206][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [tribe-node] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: no executor service found for [ccr]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.8.2-SNAPSHOT.jar:6.8.2-SNAPSHOT]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.8.2-SNAPSHOT.jar:6.8.2-SNAPSHOT]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.8.2-SNAPSHOT.jar:6.8.2-SNAPSHOT]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.8.2-SNAPSHOT.jar:6.8.2-SNAPSHOT]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.8.2-SNAPSHOT.jar:6.8.2-SNAPSHOT]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.8.2-SNAPSHOT.jar:6.8.2-SNAPSHOT]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.8.2-SNAPSHOT.jar:6.8.2-SNAPSHOT]
Caused by: java.lang.IllegalArgumentException: no executor service found for [ccr]
	at org.elasticsearch.threadpool.ThreadPool.executor(ThreadPool.java:329) ~[elasticsearch-6.8.2-SNAPSHOT.jar:6.8.2-SNAPSHOT]
	at org.elasticsearch.xpack.ccr.Ccr.createComponents(Ccr.java:201) ~[?:?]
	at org.elasticsearch.node.Node.lambda$new$11(Node.java:472) ~[elasticsearch-6.8.2-SNAPSHOT.jar:6.8.2-SNAPSHOT]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at org.elasticsearch.node.Node.<init>(Node.java:475) ~[elasticsearch-6.8.2-SNAPSHOT.jar:6.8.2-SNAPSHOT]
	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.2-SNAPSHOT.jar:6.8.2-SNAPSHOT]
	at org.elasticsearch.tribe.TribePlugin$1.<init>(TribePlugin.java:88) ~[?:?]
	at org.elasticsearch.tribe.TribePlugin.lambda$nodeBuilder$1(TribePlugin.java:88) ~[?:?]
	at org.elasticsearch.tribe.TribeService.<init>(TribeService.java:169) ~[?:?]
	at org.elasticsearch.tribe.TribePlugin.createComponents(TribePlugin.java:83) ~[?:?]
	at org.elasticsearch.node.Node.lambda$new$11(Node.java:472) ~[elasticsearch-6.8.2-SNAPSHOT.jar:6.8.2-SNAPSHOT]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at org.elasticsearch.node.Node.<init>(Node.java:475) ~[elasticsearch-6.8.2-SNAPSHOT.jar:6.8.2-SNAPSHOT]
	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.2-SNAPSHOT.jar:6.8.2-SNAPSHOT]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.2-SNAPSHOT.jar:6.8.2-SNAPSHOT]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.2-SNAPSHOT.jar:6.8.2-SNAPSHOT]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.2-SNAPSHOT.jar:6.8.2-SNAPSHOT]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.2-SNAPSHOT.jar:6.8.2-SNAPSHOT]
```

This seems related to https://github.com/elastic/elasticsearch/pull/44421

**Comment by ywelsch** [comment]
I've pushed 5283924 which should fix this. Please reopen if there are more failures.

**Comment by jasontedor** [comment]
Thanks @ywelsch.
