### ISSUE TITLE
org.elasticsearch.xpack.ccr.IndexFollowingIT.testCloseLeaderIndex failure

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#44521]
Failed build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=zulu12,nodes=general-purpose/86/console

scan: https://scans.gradle.com/s/sde2dqblsr7ts

Reproduce line: 
```
./gradlew :x-pack:plugin:ccr:internalClusterTest --tests "org.elasticsearch.xpack.ccr.IndexFollowingIT.testCloseLeaderIndex" \
  -Dtests.seed=CF234888DACDB0F2 \
  -Dtests.security.manager=true \
  -Dtests.locale=pa-Guru-IN \
  -Dtests.timezone=Etc/GMT+12 \
  -Dcompiler.java=12 \
  -Druntime.java=12
```
Does not reproduce locally. 

Assertion failure:
```
2> java.lang.AssertionError:
--
Expected: <2L>
but: was <1L>
at __randomizedtesting.SeedInfo.seed([CF234888DACDB0F2:8783CF0D6B85E0F9]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.xpack.ccr.IndexFollowingIT.lambda$testCloseLeaderIndex$17(IndexFollowingIT.java:637)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:888)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:862)
at org.elasticsearch.xpack.ccr.IndexFollowingIT.testCloseLeaderIndex(IndexFollowingIT.java:637)
```

Interesting log message from the node earlier:
```

1> org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: no settings to update;
--
1> 	at org.elasticsearch.action.ValidateActions.addValidationError(ValidateActions.java:26) ~[elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.action.admin.indices.settings.put.UpdateSettingsRequest.validate(UpdateSettingsRequest.java:81) ~[elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:110) [elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:64) [elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) [elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72) [elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:394) [elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1214) [elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.updateSettings(AbstractClient.java:1590) [elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.xpack.ccr.action.ShardFollowTasksExecutor$1.lambda$innerUpdateSettings$6(ShardFollowTasksExecutor.java:190) [main/:?]
1> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) [elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:54) [elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1101) [elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:224) [elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:193) [elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:216) [elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:141) [elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:105) [elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:660) [elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.transport.TcpTransport.consumeNetworkReads(TcpTransport.java:684) [elasticsearch-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:255) [framework-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:215) [elasticsearch-nio-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:47) [elasticsearch-nio-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:119) [elasticsearch-nio-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:127) [framework-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:397) [elasticsearch-nio-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:246) [elasticsearch-nio-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:172) [elasticsearch-nio-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:129) [elasticsearch-nio-7.2.1-SNAPSHOT.jar:7.2.1-SNAPSHOT]
1> 	at java.lang.Thread.run(Thread.java:835) [?:?]
```

**Comment by dnhatn** [comment]
> 1> org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: no settings to update;

Thanks, @benwtrent. It's an actual root cause. I am working on the fix.
