### ISSUE TITLE
GeoIpProcessorFactoryTests fails on windows

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#44552]
## Error Message
```
java.io.IOException: Could not remove the following files (in the order of attempts):
   C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\modules\ingest-geoip\build\testrun\test\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_DBCCE894DA80882D-001\tempDir-007\ingest-geoip\GeoIP2-City.mmdb: java.nio.file.FileSystemException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\modules\ingest-geoip\build\testrun\test\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_DBCCE894DA80882D-001\tempDir-007\ingest-geoip\GeoIP2-City.mmdb: The process cannot access the file because it is being used by another process.

   C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\modules\ingest-geoip\build\testrun\test\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_DBCCE894DA80882D-001\tempDir-007\ingest-geoip: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\modules\ingest-geoip\build\testrun\test\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_DBCCE894DA80882D-001\tempDir-007\ingest-geoip
   C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\modules\ingest-geoip\build\testrun\test\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_DBCCE894DA80882D-001\tempDir-007: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\modules\ingest-geoip\build\testrun\test\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_DBCCE894DA80882D-001\tempDir-007
   C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\modules\ingest-geoip\build\testrun\test\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_DBCCE894DA80882D-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\modules\ingest-geoip\build\testrun\test\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_DBCCE894DA80882D-001
Stacktrace
java.io.IOException: Could not remove the following files (in the order of attempts):
   C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\modules\ingest-geoip\build\testrun\test\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_DBCCE894DA80882D-001\tempDir-007\ingest-geoip\GeoIP2-City.mmdb: java.nio.file.FileSystemException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\modules\ingest-geoip\build\testrun\test\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_DBCCE894DA80882D-001\tempDir-007\ingest-geoip\GeoIP2-City.mmdb: The process cannot access the file because it is being used by another process.

   C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\modules\ingest-geoip\build\testrun\test\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_DBCCE894DA80882D-001\tempDir-007\ingest-geoip: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\modules\ingest-geoip\build\testrun\test\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_DBCCE894DA80882D-001\tempDir-007\ingest-geoip
   C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\modules\ingest-geoip\build\testrun\test\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_DBCCE894DA80882D-001\tempDir-007: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\modules\ingest-geoip\build\testrun\test\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_DBCCE894DA80882D-001\tempDir-007
   C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\modules\ingest-geoip\build\testrun\test\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_DBCCE894DA80882D-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\modules\ingest-geoip\build\testrun\test\temp\org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests_DBCCE894DA80882D-001

	at __randomizedtesting.SeedInfo.seed([DBCCE894DA80882D]:0)
	at org.apache.lucene.util.IOUtils.rm(IOUtils.java:319)
	at org.apache.lucene.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:216)
	at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
## Standard Output
```
[2019-07-18T03:48:50,682][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testLazyLoading] before test
[2019-07-18T03:48:51,059][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testLazyLoading] after test
[2019-07-18T03:48:51,094][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testBuildIllegalFieldOption] before test
[2019-07-18T03:48:51,095][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testBuildIllegalFieldOption] after test
[2019-07-18T03:48:51,103][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testBuildDefaults] before test
[2019-07-18T03:48:51,104][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testBuildDefaults] after test
[2019-07-18T03:48:51,120][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testCountryBuildDefaults] before test
[2019-07-18T03:48:51,121][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testCountryBuildDefaults] after test
[2019-07-18T03:48:51,127][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testBuildFields] before test
[2019-07-18T03:48:51,128][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testBuildFields] after test
[2019-07-18T03:48:51,134][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testBuildNonExistingDbFile] before test
[2019-07-18T03:48:51,135][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testBuildNonExistingDbFile] after test
[2019-07-18T03:48:51,144][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testDatabaseNotExistsInDir] before test
[2019-07-18T03:48:52,278][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testDatabaseNotExistsInDir] after test
[2019-07-18T03:48:52,284][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testBuildTargetField] before test
[2019-07-18T03:48:52,284][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testBuildTargetField] after test
[2019-07-18T03:48:52,288][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testBuildDbFile] before test
[2019-07-18T03:48:52,289][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testBuildDbFile] after test
[2019-07-18T03:48:52,294][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testDatabaseExistsInConfigDir] before test
[2019-07-18T03:48:54,208][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testDatabaseExistsInConfigDir] after test
[2019-07-18T03:48:54,213][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testBuildWithAsnDbAndCityFields] before test
[2019-07-18T03:48:54,214][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testBuildWithAsnDbAndCityFields] after test
[2019-07-18T03:48:54,222][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testLoadingCustomDatabase] before test
[2019-07-18T03:48:56,598][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testLoadingCustomDatabase] after test
[2019-07-18T03:48:56,604][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testAsnBuildDefaults] before test
[2019-07-18T03:48:56,605][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testAsnBuildDefaults] after test
[2019-07-18T03:48:56,609][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testSetIgnoreMissing] before test
[2019-07-18T03:48:56,610][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testSetIgnoreMissing] after test
[2019-07-18T03:48:56,613][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testBuildWithCountryDbAndAsnFields] before test
[2019-07-18T03:48:56,614][INFO ][o.e.i.g.GeoIpProcessorFactoryTests] [testBuildWithCountryDbAndAsnFields] after test
```

## Standard Error
```REPRODUCE WITH: gradlew :modules:ingest-geoip:test --tests "org.elasticsearch.ingest.geoip.GeoIpProcessorFactoryTests" -Dtests.seed=DBCCE894DA80882D -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=GMT -Dcompiler.java=12 -Druntime.java=11
NOTE: test params are: codec=Asserting(Lucene80), sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@43e35a7c), locale=en-VC, timezone=PST
NOTE: Windows Server 2016 10.0 amd64/Oracle Corporation 11.0.3 (64-bit)/cpus=16,threads=1,free=331936736,total=536870912
NOTE: All tests run in this JVM: [GeoIpProcessorFactoryTests]```

https://gradle.com/s/xddrm4zlanktc

**Comment by andrershov** [comment]
One more failure https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/os=windows-2019/21/

**Comment by ebadyano** [comment]
One more failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-windows-compatibility/os=windows-2016/23
