### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.debug(Ljava/lang/String;Ljava/lang/Object;)V

### ISSUE THREAD

**Issue by sherwood4968** [elastic/elasticsearch#44574]
Trying to upgrade elastic version from 2.4 to 5.6.16

**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.16

**JVM version** (`java -version`):1.8

**pom.xml configurations**
   <log4j.version>2.11.1</log4j.version>
    <jboss_logging.version>3.2.1.Final</jboss_logging.version>
    <logback.version>1.1.3</logback.version>
    <slf4j.version>1.7.21</slf4j.version>
    <jackson.version>2.6.3</jackson.version>
    <jetty.version>9.2.13.v20150730</jetty.version>
    <dropwizard.version>0.9.2</dropwizard.version>
    <mysql_connector.version>5.1.35</mysql_connector.version>
    <sqlserver_connector.version>4.0</sqlserver_connector.version>
    <elasticsearch.version>5.6.16</elasticsearch.version>
    <apache_commons_io.version>2.4</apache_commons_io.version>
    <jsoup.version>1.8.3</jsoup.version>
    <hibernate.version>4.3.11.Final</hibernate.version>
    <junit.version>4.12</junit.version>
    <mockito.version>2.7.22</mockito.version>

**Error**
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.debug(Ljava/lang/String;Ljava/lang/Object;)V
	at org.elasticsearch.threadpool.ThreadPool.<init>(ThreadPool.java:203)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:132)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:268)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:133)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:119)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:109)

**additional dependency added**
<dependency>
<groupId>org.elasticsearch.client</groupId>
<artifactId>transport</artifactId>
<version>${elasticsearch.version}</version>
</dependency>

when I try to run the main class I get Logger error mention above.

**Comment by dnhatn** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
