### ISSUE TITLE
Multiple CCR tests with uncaught exception on windows

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#44610]
https://scans.gradle.com/s/vl3yktrv4xey4/tests/htwk6wzdfugzg-ntvlkoitzt6ms?openStackTraces=WzIsMSwwXQ
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=243, name=elasticsearch[follower0][generic][T#4], state=RUNNABLE, group=TGRP-AutoFollowIT]Close stacktrace
at __randomizedtesting.SeedInfo.seed([DE1704EC3D6BE8E2:CD64108D18DC74F7]:0)
Caused by: java.lang.IllegalStateException: java.lang.InterruptedExceptionClose stacktrace
at __randomizedtesting.SeedInfo.seed([DE1704EC3D6BE8E2]:0)
at org.elasticsearch.transport.ConnectionManager.close(ConnectionManager.java:259)
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:699)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException: (No message provided)Close stacktrace
at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1040)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
at org.elasticsearch.transport.ConnectionManager.close(ConnectionManager.java:256)
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:699)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.lang.Thread.run(Thread.java:834)
```

**Comment by atorok** [comment]
Fails for others as well ( in the same run as in the description )
```
:x-pack:plugin:ccr:internalClusterTestorg.elasticsearch.xpack.ccr.RestartIndexFollowingIT » classMethod (0.039s)
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=251, name=elasticsearch[followerm0][generic][T#4], state=RUNNABLE, group=TGRP-RestartIndexFollowingIT]Close stacktrace
Caused by: java.lang.IllegalStateException: java.lang.InterruptedExceptionClose stacktrace
at __randomizedtesting.SeedInfo.seed([DE1704EC3D6BE8E2]:0)
at org.elasticsearch.transport.ConnectionManager.close(ConnectionManager.java:259)
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:699)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException: (No message provided)Close stacktrace
at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1040)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
at org.elasticsearch.transport.ConnectionManager.close(ConnectionManager.java:256)
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:699)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.lang.Thread.run(Thread.java:834)
```

**Comment by atorok** [comment]
I have multiple runs on windows on my local CI and this failure only seems to happen for various CCR tests

**Comment by andrershov** [comment]
One more failure https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/94/console

**Comment by original-brownbear** [comment]
The problem here is that a transport service is not getting fully started:

```

1> [2019-07-18T17:26:02,087][WARN ][o.e.t.n.MockNioTransport ] [followerm1] Potentially blocked execution on network thread [elasticsearch[followerm1][transport_worker][T#1]] [WAITING] [2803 milliseconds]:
--
1> java.base@11.0.3/jdk.internal.misc.Unsafe.park(Native Method)
1> java.base@11.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
1> java.base@11.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
1> java.base@11.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1039)
1> java.base@11.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
1> java.base@11.0.3/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
1> app//org.elasticsearch.transport.TransportService.onRequestReceived(TransportService.java:916)
1> app//org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:161)
1> app//org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:121)
1> app//org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:105)
1> app//org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:661)
1> app//org.elasticsearch.transport.TcpTransport.consumeNetworkReads(TcpTransport.java:685)
1> app//org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:269)
1> app//org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:199)
1> app//org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:40)
1> app//org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:139)
1> app//org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:151)
1> app//org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:420)

```

=> we get stuck on the latch waiting for it to properly start up. Me and @cbuescher already investigated a similar issue in #41745 ... so @cbuescher it seems like this problem might have more to it since we're now seeing it in an IT as well.

**Comment by original-brownbear** [comment]
I opened https://github.com/elastic/elasticsearch/pull/44622 which might surface some hidden issue here. It seems to me we're handling requests on integ-test nodes that never fully started and are swallowing interrupts which would explain the situation here (io loop never stops cleanly on an stopped (then interrupted) node).

**Comment by ywelsch** [comment]
This could be fixed by https://github.com/elastic/elasticsearch/pull/44805 as well.

**Comment by ywelsch** [comment]
AFAICS this did not affect 6.8 and the tests have not been disabled there, which is why I've removed the label here. #44805 looks to fix the issue. It's only backported to 7.4, however, as it is based on other changes to 7.4.
