### ISSUE TITLE
Cannot install v6 on Buster

### ISSUE THREAD

**Issue by SoftCreatR** [elastic/elasticsearch#44648]
I am trying to install ES-6.8.1 on a fresh Debian (Buster) server. While v7* installed fine, v6 doesn't:

```
Setting up elasticsearch (6.8.1) ...
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.base/javax.crypto.SecretKeyFactory.nextSpi(SecretKeyFactory.java:303)
        at java.base/javax.crypto.SecretKeyFactory.<init>(SecretKeyFactory.java:121)
        at java.base/javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:168)
        at org.elasticsearch.common.settings.KeyStoreWrapper.createCipher(KeyStoreWrapper.java:289)
        at org.elasticsearch.common.settings.KeyStoreWrapper.encrypt(KeyStoreWrapper.java:368)
        at org.elasticsearch.common.settings.KeyStoreWrapper.save(KeyStoreWrapper.java:477)
        at org.elasticsearch.common.settings.CreateKeyStoreCommand.execute(CreateKeyStoreCommand.java:58)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:41)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
        at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:120)
        ... 13 more
Caused by: java.lang.SecurityException: Couldn't parse jurisdiction policy files in: unlimited
        at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:357)
        at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:111)
        at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:108)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:107)
        ... 13 more
dpkg: error processing package elasticsearch (--configure):
 installed elasticsearch package post-installation script subprocess returned error exit status 1
```

* = I am currently not able to use v7 due to some compatibility problems with a PHP script that we're using.

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch, and sorry that you're having trouble.

That looks like a bogus or broken JDK installation on your machine though.

The reason that 7.0.0 does not have this issue is because we include a bundled JDK there, which circumvents any issues with the JDK that you have installed locally.

We like to direct this kind of troubleshooting to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

As such, I hope you don't mind that I close this.

**Comment by SoftCreatR** [comment]
Just did that and i guess, i found the solution (at least, for me): https://discuss.elastic.co/t/cannot-install-v6-on-buster/191505

Thank you.
