### ISSUE TITLE
JvmErgonomicsTests fail on Windows -XX:MaxDirectMemorySize=0"

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#44669]
https://scans.gradle.com/s/kl3f3rsoyyvhq/tests/n22ss45luel4s-2ooa4zfpqen2y?openStackTraces=WzBd
https://scans.gradle.com/s/ba7rarvkmlhk4/tests/n22ss45luel4s-kuqbvmqx5f6fc
```
:distribution:tools:launchers:testorg.elasticsearch.tools.launchers.JvmErgonomicsTests » testMaxDirectMemorySizeChoice (0.206s)
java.lang.AssertionError: 

Expected: a collection containing "-XX:MaxDirectMemorySize=4294967296"
     but: mismatches were: [was "-Dio.netty.allocator.type=unpooled", was "-XX:MaxDirectMemorySize=0"]
Close stacktrace
at __randomizedtesting.SeedInfo.seed([4A09793D6A849E8C:648F67301FAB6D5]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.tools.launchers.JvmErgonomicsTests.testMaxDirectMemorySizeChoice(JvmErgonomicsTests.java:147)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by jasontedor** [comment]
Closed by 5c0ebe7b5f5261f5553e4d61112a4cbf1182bcad

**Comment by jdconrad** [comment]
Seems like this still happening in 7.2:
https://scans.gradle.com/s/ptdvdikx5egke/console-log
https://scans.gradle.com/s/e7xg63quy2e3s/console-log

**Comment by jasontedor** [comment]
I backported 4dd9238cc0d2b5a13d04da884399b64c13dde478 to 7.2.
