### ISSUE TITLE
PendingTasksBlocksIT#testPendingTasksWithClusterReadOnlyBlock with MasterNotDiscoveredException

### ISSUE THREAD

**Issue by ebadyano** [elastic/elasticsearch#44695]
Also other tests failing in the suite:
```
testPendingTasksWithIndexBlocks
testPendingTasksWithClusterNotRecoveredBlock
```

Link to the build:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+fast+part1/364/consoleFull
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/757/console

Command to reproduce:
```
./gradlew :server:integTest --tests "org.elasticsearch.action.admin.cluster.tasks.PendingTasksBlocksIT.testPendingTasksWithClusterReadOnlyBlock" \
  -Dtests.seed=BE942A6BB529D800 \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-BA \
  -Dtests.timezone=Asia/Bangkok \
  -Dcompiler.java=12 \
  -Druntime.java=8
```
Relevant excerpt from the logs:
```
08:45:52 org.elasticsearch.action.admin.cluster.tasks.PendingTasksBlocksIT > testPendingTasksWithClusterNotRecoveredBlock FAILED
08:45:52     ElasticsearchException[failed to update minimum master node to [3] (current masters [3])]; nested: MasterNotDiscoveredException[ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];]]; nested: ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];];
08:45:52         at org.elasticsearch.test.InternalTestCluster.updateMinMasterNodes(InternalTestCluster.java:2175)
08:45:52         at org.elasticsearch.test.InternalTestCluster.startAndPublishNodesAndClients(InternalTestCluster.java:1682)
08:45:52         at org.elasticsearch.test.InternalTestCluster.startNodes(InternalTestCluster.java:2131)
08:45:52         at org.elasticsearch.test.InternalTestCluster.startNode(InternalTestCluster.java:2066)
08:45:52         at org.elasticsearch.test.InternalTestCluster.startNode(InternalTestCluster.java:2052)
08:45:52         at org.elasticsearch.action.admin.cluster.tasks.PendingTasksBlocksIT.testPendingTasksWithClusterNotRecoveredBlock(PendingTasksBlocksIT.java:94)
08:45:52 
08:45:52         Caused by:
08:45:52         MasterNotDiscoveredException[ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];]]; nested: ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];];
08:45:52 
08:45:52             Caused by:
08:45:52             ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];]
```

**Comment by ebadyano** [comment]
Seems like it was fixed by @DaveCTurner  right after I muted the tests: https://github.com/elastic/elasticsearch/pull/44685
