### ISSUE TITLE
AzureStorageRepositoryClientYamlTestSuiteIT test fails with SnapshotCreationException

### ISSUE THREAD

**Issue by ebadyano** [elastic/elasticsearch#44712]
Link to the build:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+multijob+third-party-tests-azure-sas/5/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+multijob+third-party-tests-azure-sas/8/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+multijob+third-party-tests-azure-sas/9/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+multijob+third-party-tests-azure-sas/10/console

Command to reproduce:
```
./gradlew :plugins:repository-azure:qa:microsoft-azure-storage:integTestRunner \
  -Dtests.seed=8A38B5339259F4F5 \
  -Dtests.class=org.elasticsearch.repositories.azure.AzureStorageRepositoryClientYamlTestSuiteIT \
  -Dtests.method="test {yaml=repository_azure/10_repository/Snapshot/Restore with repository-azure}" \
  -Dtests.security.manager=true \
  -Dtests.locale=vi \
  -Dtests.timezone=Canada/Eastern \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

Relevant excerpt from the logs:
```
12:42:46   1> [2019-07-22T12:42:45,372][INFO ][o.e.r.a.AzureStorageRepositoryClientYamlTestSuiteIT] [test] Stash dump on test failure [{
12:42:46   1>   "stash" : {
12:42:46   1>     "body" : {
12:42:46   1>       "error" : {
12:42:46   1>         "root_cause" : [
12:42:46   1>           {
12:42:46   1>             "type" : "snapshot_creation_exception",
12:42:46   1>             "reason" : "[repository:snapshot-one/bdo98uAzR9myTl-DjwVsdw] failed to create snapshot",
12:42:46   1>             "stack_trace" : "SnapshotCreationException[[repository:snapshot-one/bdo98uAzR9myTl-DjwVsdw] failed to create snapshot]; nested: StorageException[This request is not authorized to perform this operation.];
12:42:46   1> 	at org.elasticsearch.repositories.azure.AzureRepository.initializeSnapshot(AzureRepository.java:169)
12:42:46   1> 	at org.elasticsearch.snapshots.SnapshotsService$2.doRun(SnapshotsService.java:413)
12:42:46   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751)
12:42:46   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
12:42:46   1> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
12:42:46   1> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
12:42:46   1> 	at java.base/java.lang.Thread.run(Thread.java:835)
12:42:46   1> Caused by: com.microsoft.azure.storage.StorageException: This request is not authorized to perform this operation.
12:42:46   1> 	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87)
12:42:46   1> 	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:313)
12:42:46   1> 	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:185)
12:42:46   1> 	at com.microsoft.azure.storage.blob.CloudBlobContainer.exists(CloudBlobContainer.java:744)
12:42:46   1> 	at com.microsoft.azure.storage.blob.CloudBlobContainer.exists(CloudBlobContainer.java:731)
12:42:46   1> 	at org.elasticsearch.repositories.azure.AzureStorageService.lambda$doesContainerExist$1(AzureStorageService.java:143)
12:42:46   1> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:551)
12:42:46   1> 	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedException(SocketAccess.java:54)
12:42:46   1> 	at org.elasticsearch.repositories.azure.AzureStorageService.doesContainerExist(AzureStorageService.java:143)
12:42:46   1> 	at org.elasticsearch.repositories.azure.AzureBlobStore.containerExist(AzureBlobStore.java:98)
12:42:46   1> 	at org.elasticsearch.repositories.azure.AzureRepository.initializeSnapshot(AzureRepository.java:164)
12:42:46   1> 	... 6 more
```

**Comment by original-brownbear** [comment]
@fatmcgav is there something different with our 6.8 builds infra wise that could explain this? (different token/key or so).

**Comment by jdconrad** [comment]
Another one:
https://scans.gradle.com/s/4dyanfv6eovfq/console-log

**Comment by original-brownbear** [comment]
Raised this with infra. It's an infra issue with the SAS token in that test as far as I can see.

**Comment by original-brownbear** [comment]
Closed via https://github.com/elastic/elasticsearch/pull/45440
