### ISSUE TITLE
Not able to run Elasticsearch successfully.

### ISSUE THREAD

**Issue by harshil9697** [elastic/elasticsearch#44733]
I am trying to run elasticsearch, but is showing this list of errors. 
Elasticsearch version : 7.2.0
Plugins installed : None
OS : Windows 8.1 Pro 64-bit(6.3, Build 9600)
Java version="1.8.0_221"

`    C:\Users\Megha\Desktop\Downloads\elasticsearch-7.2.0-windows-x86_64\elasticsearc
h-7.2.0\bin>elasticsearch
future versions of Elasticsearch will require Java 11; your Java version from [C
:\Program Files\Java\jdk1.8.0_221\jre] does not meet this requirement
[2019-07-23T11:06:47,932][INFO ][o.e.e.NodeEnvironment    ] [MEGHA-PC] using [1]
 data paths, mounts [[(C:)]], net usable_space [42.6gb], net total_space [72.8gb
], types [NTFS]
[2019-07-23T11:06:48,002][INFO ][o.e.e.NodeEnvironment    ] [MEGHA-PC] heap size
 [1.9gb], compressed ordinary object pointers [true]
[2019-07-23T11:06:48,025][INFO ][o.e.n.Node               ] [MEGHA-PC] node name
 [MEGHA-PC], node ID [kFh4MUfBToqFhm-umYRScg], cluster name [elasticsearch]
[2019-07-23T11:06:48,027][INFO ][o.e.n.Node               ] [MEGHA-PC] version[7
.2.0], pid[5000], build[default/zip/508c38a/2019-06-20T15:54:18.811730Z], OS[Win
dows 8.1/6.3/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.
8.0_221/25.221-b11]
[2019-07-23T11:06:48,044][INFO ][o.e.n.Node               ] [MEGHA-PC] JVM home
[C:\Program Files\Java\jdk1.8.0_221\jre]
[2019-07-23T11:06:48,048][INFO ][o.e.n.Node               ] [MEGHA-PC] JVM argum
ents [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFractio
n=75, -XX:+UseCMSInitiatingOccupancyOnly, -Des.networkaddress.cache.ttl=60, -Des
.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.h
eadless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFast
Throw, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.nett
y.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.d
isable.jmx=true, -Djava.io.tmpdir=C:\Users\Megha\AppData\Local\Temp\elasticsearc
h, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs
_err_pid%p.log, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringD
istribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGC
LogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Dio.netty.al
locator.type=pooled, -XX:MaxDirectMemorySize=1073741824, -Delasticsearch, -Des.p
ath.home=C:\Users\Megha\Desktop\Downloads\elasticsearch-7.2.0-windows-x86_64\ela
sticsearch-7.2.0, -Des.path.conf=C:\Users\Megha\Desktop\Downloads\elasticsearch-
7.2.0-windows-x86_64\elasticsearch-7.2.0\config, -Des.distribution.flavor=defaul
t, -Des.distribution.type=zip, -Des.bundled_jd=true]
[2019-07-23T11:07:32,533][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [aggs-matrix-stats]
[2019-07-23T11:07:32,534][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [analysis-common]
[2019-07-23T11:07:32,534][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [data-frame]
[2019-07-23T11:07:32,535][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [ingest-common]
[2019-07-23T11:07:32,535][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [ingest-geoip]
[2019-07-23T11:07:32,536][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [ingest-user-agent]
[2019-07-23T11:07:32,536][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [lang-expression]
[2019-07-23T11:07:32,538][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [lang-mustache]
[2019-07-23T11:07:32,539][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [lang-painless]
[2019-07-23T11:07:32,539][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [mapper-extras]
[2019-07-23T11:07:32,539][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [parent-join]
[2019-07-23T11:07:32,540][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [percolator]
[2019-07-23T11:07:32,541][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [rank-eval]
[2019-07-23T11:07:32,543][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [reindex]
[2019-07-23T11:07:32,546][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [repository-url]
[2019-07-23T11:07:32,547][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [transport-netty4]
[2019-07-23T11:07:32,548][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [x-pack-ccr]
[2019-07-23T11:07:32,549][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [x-pack-core]
[2019-07-23T11:07:32,550][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [x-pack-deprecation]
[2019-07-23T11:07:32,551][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [x-pack-graph]
[2019-07-23T11:07:32,552][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [x-pack-ilm]
[2019-07-23T11:07:32,553][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [x-pack-logstash]
[2019-07-23T11:07:32,554][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [x-pack-ml]
[2019-07-23T11:07:32,555][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [x-pack-monitoring]
[2019-07-23T11:07:32,557][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [x-pack-rollup]
[2019-07-23T11:07:32,559][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [x-pack-security]
[2019-07-23T11:07:32,561][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [x-pack-sql]
[2019-07-23T11:07:32,562][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] loaded mo
dule [x-pack-watcher]
[2019-07-23T11:07:32,564][INFO ][o.e.p.PluginsService     ] [MEGHA-PC] no plugin
s loaded
[2019-07-23T11:07:43,356][INFO ][o.e.x.s.a.s.FileRolesStore] [MEGHA-PC] parsed [
0] roles from file [C:\Users\Megha\Desktop\Downloads\elasticsearch-7.2.0-windows
-x86_64\elasticsearch-7.2.0\config\roles.yml]
[2019-07-23T11:08:00,522][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [M
EGHA-PC] uncaught exception in thread [main]
`
`   org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Failed to c
reate native process factories for Machine Learning]; nested: FileNotFoundExcept
ion[\\.\pipe\controller_log_5000 (The system cannot find the file specified)];
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163
) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:
150) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwar
eCommand.java:86) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:1
24) ~[elasticsearch-cli-7.2.0.jar:7.2.0]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-c
li-7.2.0.jar:7.2.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115
) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
 ~[elasticsearch-7.2.0.jar:7.2.0]
Caused by: org.elasticsearch.ElasticsearchException: Failed to create native pro
cess factories for Machine Learning
        at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLe
arning.java:455) ~[?:?]
        at org.elasticsearch.node.Node.lambda$new$9(Node.java:438) ~[elasticsear
ch-7.2.0.jar:7.2.0]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:
267) ~[?:1.8.0_221]`

`        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.j
ava:1382) ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
 ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.ja
va:472) ~[?:1.8.0_221]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java
:708) ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 ~[?:1.8.0_221]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499
) ~[?:1.8.0_221]
        at org.elasticsearch.node.Node.<init>(Node.java:441) ~[elasticsearch-7.2
.0.jar:7.2.0]
        at org.elasticsearch.node.Node.<init>(Node.java:251) ~[elasticsearch-7.2
.0.jar:7.2.0]`

`  at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[
elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[ela
sticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elas
ticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159
) ~[elasticsearch-7.2.0.jar:7.2.0]
        ... 6 more
Caused by: java.io.FileNotFoundException: \\.\pipe\controller_log_5000 (The syst
em cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_221]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_221]

        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_22
1]
        at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[?:1.8.0_221
]
        at org.elasticsearch.xpack.ml.utils.NamedPipeHelper$PrivilegedInputPipeO
pener.run(NamedPipeHelper.java:288) ~[?:?]
        at org.elasticsearch.xpack.ml.utils.NamedPipeHelper$PrivilegedInputPipeO
pener.run(NamedPipeHelper.java:277) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_
221] `

  `     at org.elasticsearch.xpack.ml.utils.NamedPipeHelper.openNamedPipeInputSt
ream(NamedPipeHelper.java:130) ~[?:?]
        at org.elasticsearch.xpack.ml.utils.NamedPipeHelper.openNamedPipeInputSt
ream(NamedPipeHelper.java:97) ~[?:?]
        at org.elasticsearch.xpack.ml.process.ProcessPipes.connectStreams(Proces
sPipes.java:131) ~[?:?]
        at org.elasticsearch.xpack.ml.process.NativeController.<init>(NativeCont
roller.java:62) ~[?:?]
        at org.elasticsearch.xpack.ml.process.NativeControllerHolder.getNativeCo
ntroller(NativeControllerHolder.java:40) ~[?:?]
        at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLe
arning.java:440) ~[?:?]
        at org.elasticsearch.node.Node.lambda$new$9(Node.java:438) ~[elasticsear
ch-7.2.0.jar:7.2.0]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:
267) ~[?:1.8.0_221]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.j
ava:1382) ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
 ~[?:1.8.0_221] `

`        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.ja
va:472) ~[?:1.8.0_221]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java
:708) ~[?:1.8.0_221]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 ~[?:1.8.0_221]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499
) ~[?:1.8.0_221]
        at org.elasticsearch.node.Node.<init>(Node.java:441) ~[elasticsearch-7.2
.0.jar:7.2.0]
        at org.elasticsearch.node.Node.<init>(Node.java:251) ~[elasticsearch-7.2
.0.jar:7.2.0]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[
elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[ela
sticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elas
ticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159
) ~[elasticsearch-7.2.0.jar:7.2.0]
        ... 6 more
`

**Comment by droberts195** [comment]
It could well be the same problem as [this forum question](https://discuss.elastic.co/t/elasticsearch-7-0-1-throws-error-in-ml-in-bootstrap-windows-2012-server/181667) in which case the solution is in [the 4th response](https://discuss.elastic.co/t/elasticsearch-7-0-1-throws-error-in-ml-in-bootstrap-windows-2012-server/181667/4) (and the note I said I'd add to the docs is the first note in both the [`.msi`](https://www.elastic.co/guide/en/elasticsearch/reference/7.2/windows.html) and [`.zip`](https://www.elastic.co/guide/en/elasticsearch/reference/7.2/zip-windows.html) installation instructions for 7.2).

If not, please can you open a new [topic tagged "stack-machine-learning" in the forum](https://discuss.elastic.co/tags/stack-machine-learning), as we prefer to use GitHub for confirmed bugs that require code changes, and this is almost certainly some sort of environmental problem.
