### ISSUE TITLE
 Unclosed object or array found

### ISSUE THREAD

**Issue by laijianbin** [elastic/elasticsearch#44732]
I meet a bug ,can you help me find the cause
Thanks

I am use ealsticsearch for batch save

elasticsearch: 6.8.0
OS: window 7
JVM: 1.8.0_201
Plugins installed : None

**Bug demo sample**

public static List<BulkItemResponse> batchSave(RestHighLevelClient client, String index, String type,
			List<Map<String, Object>> listMap) throws IOException {
		BulkRequest req = new BulkRequest();
		req.setRefreshPolicy(RefreshPolicy.IMMEDIATE);
		for (Map<String, Object> map : listMap) {
			Object esIdObj = map.get("_id");
			map.remove("_id", esIdObj);
			IndexRequest indexRequest = new IndexRequest(index, type, String.valueOf(esIdObj)).source(map);
			UpdateRequest updateRequest = new UpdateRequest(index, type, String.valueOf(esIdObj))
					.upsert(indexRequest);
			updateRequest.doc(indexRequest);
			req.add(updateRequest);
		}
		BulkResponse res = null;
		try {
			res = client.bulk(req, RequestOptions.DEFAULT);
		} catch (IOException e) {
			throw new IOException(e);
		}
		List<BulkItemResponse> failureRespList = new ArrayList<>();
		if (res.hasFailures()) {
			for (BulkItemResponse resp : res.getItems()) {
				if (resp.isFailed()) {
					failureRespList.add(resp);
				}
			}
		}
		return failureRespList;
	}

**The log**

`Exception in thread "main" java.lang.NoSuchMethodError: org.elasticsearch.action.DocWriteRequest.ifSeqNo()J
	at org.elasticsearch.client.RequestConverters.bulk(RequestConverters.java:197)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1760)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1734)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1696)
	at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:472)
	at fulltext.storage.http.impl.HighLevelClient.batchSave(HighLevelClient.java:198)
	at fulltext.storage.http.impl.HighLevelClient.main(HighLevelClient.java:99)
	Suppressed: java.lang.IllegalStateException: Failed to close the XContentBuilder
		at org.elasticsearch.common.xcontent.XContentBuilder.close(XContentBuilder.java:1002)
		at org.elasticsearch.client.RequestConverters.bulk(RequestConverters.java:163)
		... 6 more
	Caused by: java.io.IOException: Unclosed object or array found
		at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.close(JsonXContentGenerator.java:469)
		at org.elasticsearch.common.xcontent.XContentBuilder.close(XContentBuilder.java:1000)
		... 7 more`

**Maven dependencies**

<dependencies>
		<dependency>
			<groupId>org.elasticsearch.client</groupId>
			<artifactId>elasticsearch-rest-high-level-client</artifactId>
			<version>6.8.0</version>
		</dependency>
		<dependency>
			<groupId>org.elasticsearch</groupId>
			<artifactId>elasticsearch</artifactId>
			<version>6.8.0</version>
		</dependency>
	</dependencies>

**Comment by laijianbin** [comment]
My maven dependencies:
<dependencies>
		<dependency>
			<groupId>org.elasticsearch.client</groupId>
			<artifactId>elasticsearch-rest-high-level-client</artifactId>
			<version>6.8.0</version>
		</dependency>
		<dependency>
			<groupId>org.elasticsearch</groupId>
			<artifactId>elasticsearch</artifactId>
			<version>6.8.0</version>
		</dependency>
	</dependencies>

**Comment by laijianbin** [comment]
please copy this demo for recreation of the problem

public static List<BulkItemResponse> batchSave(RestHighLevelClient client, String index, String type,
			List<Map<String, Object>> listMap) throws IOException {
		BulkRequest req = new BulkRequest();
		req.setRefreshPolicy(RefreshPolicy.IMMEDIATE);
		for (Map<String, Object> map : listMap) {
			Object esIdObj = map.get("_id");
			map.remove("_id", esIdObj);
			IndexRequest indexRequest = new IndexRequest(index, type, String.valueOf(esIdObj)).source(map);
			UpdateRequest updateRequest = new UpdateRequest(index, type, String.valueOf(esIdObj))
					.upsert(indexRequest);
			updateRequest.doc(indexRequest);
			req.add(updateRequest);
		}
		BulkResponse res = null;
		try {
			res = client.bulk(req, RequestOptions.DEFAULT);
		} catch (IOException e) {
			throw new IOException(e);
		}
		List<BulkItemResponse> failureRespList = new ArrayList<>();
		if (res.hasFailures()) {
			for (BulkItemResponse resp : res.getItems()) {
				if (resp.isFailed()) {
					failureRespList.add(resp);
				}
			}
		}
		return failureRespList;
	}

**Comment by laijianbin** [comment]
I am make a mistake,I did not pass "_id"

**Comment by laijianbin** [comment]
oh, my jar not update cause this problem
