### ISSUE TITLE
:plugins:repository-azure:qa:microsoft-azure-storage failures

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#44740]
Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+multijob+third-party-tests-azure-sas/12/console
Build Scans: https://gradle.com/s/qxqjd3rfra63m

Failure: 
```
Caused by: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method org.elasticsearch.gradle.testclusters.ElasticsearchCluster#keystore.
08:04:45 Cannot resolve which method to invoke for [class java.lang.String, null] due to overlapping prototypes between:
08:04:45 	[class java.lang.String, interface java.util.function.Supplier]
08:04:45 	[class java.lang.String, interface org.elasticsearch.gradle.FileSupplier]
08:04:45 	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.lookupMethod(BeanDynamicObject.java:511)
08:04:45 	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:477)
08:04:45 	at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
08:04:45 	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:56)
08:04:45 	at build_c9he317tplhsqc5g0tilqiuzk$_run_closure4.doCall(/var/lib/jenkins/workspace/elastic+elasticsearch+7.2+multijob+third-party-tests-azure-sas/plugins/repository-azure/qa/microsoft-azure-storage/build.gradle:66)
08:04:45 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08:04:45 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
08:04:45 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08:04:45 	at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:70)
08:04:45 	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
08:04:45 	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:105)
08:04:45 	at org.gradle.api.internal.DefaultNamedDomainObjectCollection$ContainerElementsDynamicObject.tryInvokeMethod(DefaultNamedDomainObjectCollection.java:527)
08:04:45 	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:499)
08:04:45 	at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
08:04:45 	at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
08:04:45 	at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:33)
08:04:45 	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:160)
08:04:45 	at org.gradle.api.internal.FactoryNamedDomainObjectContainer_Decorated.invokeMethod(Unknown Source)
08:04:45 	at build_c9he317tplhsqc5g0tilqiuzk.run(/var/lib/jenkins/workspace/elastic+elasticsearch+7.2+multijob+third-party-tests-azure-sas/plugins/repository-azure/qa/microsoft-azure-storage/build.gradle:63)
08:04:45 	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
```

Probably related to the changes in #43782 so I'm assigning @mark-vieira to take a look

**Comment by mark-vieira** [comment]
@original-brownbear is [this CI job](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+multijob+third-party-tests-azure-sas/) even compatible with 7.2? It seems that job was added in conjunction with https://github.com/elastic/elasticsearch/pull/42982 which I don't think is applicable to that branch. Perhaps we should disable that job for 7.2?

**Comment by original-brownbear** [comment]
@mark-vieira right sorry for missing that ... `7.2` doesn't support SAS tokens so yea we should not run that job.

**Comment by mark-vieira** [comment]
There doesn't seem to be an easy way to omit a job definition based on branch with JJB. Simplest thing might be to make the job a noop based on the branch. We don't seem to have the conditional build step plugin installed so perhaps just modifying the `runbld-gradle-build-third-party-build-azure-sas` builder to check the branch and do nothing if it's not applicable?

**Comment by original-brownbear** [comment]
@mark-vieira that's fine with me if it's fine with you, we won't ever need this in `7.2` so whatever works for you works for me:)

**Comment by mark-vieira** [comment]
This has been fixed by https://github.com/elastic/infra/pull/13260.
