### ISSUE TITLE
MlDistributedFailureIT#testFullClusterRestart failing occasionally

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#44744]
See e.g. https://scans.gradle.com/s/ms5w73z6225s4/console-log?task=:x-pack:plugin:ml:internalClusterTest, but I count 23 failures over the last 30 days:

```
:x-pack:plugin:ml:internalClusterTest FAILED
--
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
WARNING: Illegal reflective access by org.mockito.cglib.core.ReflectUtils$2 (file:/var/lib/jenkins/.gradle/caches/modules-2/files-2.1/org.elasticsearch/securemock/1.2/98201d4ad5ac93f6b415ae9172d52b5e7cda490e/securemock-1.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Illegal reflective access by org.mockito.cglib.core.ReflectUtils$2 (file:/var/lib/jenkins/.gradle/caches/modules-2/files-2.1/org.elasticsearch/securemock/1.2/98201d4ad5ac93f6b415ae9172d52b5e7cda490e/securemock-1.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
 
 
org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT > testFullClusterRestart FAILED
java.lang.AssertionError
at __randomizedtesting.SeedInfo.seed([CA01567D4C855061:9B2E476CB9A918CE]:0)
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertFalse(Assert.java:64)
at org.junit.Assert.assertFalse(Assert.java:74)
at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$run$13(MlDistributedFailureIT.java:307)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:866)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:840)
at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.run(MlDistributedFailureIT.java:301)
at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testFullClusterRestart(MlDistributedFailureIT.java:112)
REPRODUCE WITH: ./gradlew :x-pack:plugin:ml:internalClusterTest --tests "org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testFullClusterRestart" -Dtests.seed=CA01567D4C855061 -Dtests.security.manager=true -Dtests.locale=nl-NL -Dtests.timezone=Asia/Bangkok -Dcompiler.java=12 -Druntime.java=11
```

Does not reproduce for me.

**Comment by atorok** [comment]
Another occurrence https://gradle-enterprise.elastic.co/s/4oiaauikdd3v2 in a  PR and one in a non PR https://gradle-enterprise.elastic.co/s/vu6slgojfywlq

**Comment by benwtrent** [comment]
Recent failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/5951/consoleFull

It seems that it is a legitimate failure due to timeout. I am adding a wait for yellow on our ML indices to reduce the amount of time we are waiting for the tasks to be assigned (since they won't be assigned until ML indices are yellow).
