### ISSUE TITLE
[CI] ConnectionManagerTests failures

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#44758]
This has failed 4 times in the last 4 days, `testConnectFailsDuringValidation` was responsible for 3 of them and `    testConcurrentConnectsAndDisconnects` for the other

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:ConnectionManagerTests),sort:!(time,desc))

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part1/381/console

Build Scans: https://gradle.com/s/h2fc43mhmbuma

Reproduction lines: 
```
REPRODUCE WITH: ./gradlew :server:test --tests "org.elasticsearch.transport.ConnectionManagerTests.testConcurrentConnectsAndDisconnects" \
  -Dtests.seed=58603A96C6436123 \
  -Dtests.security.manager=true \
  -Dtests.locale=ksf \
  -Dtests.timezone=America/Knox_IN \
  -Dcompiler.java=12 \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew :server:test --tests "org.elasticsearch.transport.ConnectionManagerTests.testConnectFailsDuringValidation" \
  -Dtests.seed=58603A96C6436123 \
  -Dtests.security.manager=true \
  -Dtests.locale=ksf \
  -Dtests.timezone=America/Knox_IN \
  -Dcompiler.java=12 \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew :server:test --tests "org.elasticsearch.transport.ConnectionManagerTests.testConcurrentConnectsAndDisconnects" \
  -Dtests.seed=58603A96C6436123 \
  -Dtests.security.manager=true \
  -Dtests.locale=ksf \
  -Dtests.timezone=America/Knox_IN \
  -Dcompiler.java=12 \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew :server:test --tests "org.elasticsearch.transport.ConnectionManagerTests.testConnectFailsDuringValidation" \
  -Dtests.seed=58603A96C6436123 \
  -Dtests.security.manager=true \
  -Dtests.locale=ksf \
  -Dtests.timezone=America/Knox_IN \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

Failure:
```
16:05:24   2> REPRODUCE WITH: ./gradlew :server:test --tests "org.elasticsearch.transport.ConnectionManagerTests.testConnectFailsDuringValidation" -Dtests.seed=58603A96C6436123 -Dtests.security.manager=true -Dtests.locale=ksf -Dtests.timezone=America/Knox_IN -Dcompiler.java=12 -Druntime.java=11
16:05:24   2> com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=11483, name=elasticsearch[ConnectionManagerTests][generic][T#1], state=RUNNABLE, group=TGRP-ConnectionManagerTests]
16:05:24 
16:05:24         Caused by:
16:05:24         java.lang.NullPointerException
16:05:24             at __randomizedtesting.SeedInfo.seed([58603A96C6436123]:0)
16:05:24             at org.elasticsearch.action.ActionListener.onFailure(ActionListener.java:193)
16:05:24             at org.elasticsearch.transport.ConnectionManager.lambda$connectToNode$4(ConnectionManager.java:187)
16:05:24             at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:70)
16:05:24             at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:64)
16:05:24             at org.elasticsearch.transport.ConnectionManagerTests.lambda$testConcurrentConnectsAndDisconnects$7(ConnectionManagerTests.java:147)
16:05:24   2> ŋ7 23, 2019 8:05:22 SÁRÚWÁ com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
16:05:24   2> WARNING: Uncaught exception in thread: Thread[elasticsearch[ConnectionManagerTests][generic][T#3],5,TGRP-ConnectionManagerTests]
16:05:24   2> java.lang.NullPointerException
16:05:24   2> 	at __randomizedtesting.SeedInfo.seed([58603A96C6436123]:0)
16:05:24   2> 	at org.elasticsearch.action.ActionListener.onFailure(ActionListener.java:193)
16:05:24   2> 	at org.elasticsearch.transport.ConnectionManager.lambda$connectToNode$4(ConnectionManager.java:187)
16:05:24   2> 	at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:70)
16:05:24   2> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:64)
16:05:24   2> 	at org.elasticsearch.transport.ConnectionManagerTests.lambda$testConcurrentConnectsAndDisconnects$7(ConnectionManagerTests.java:147)
16:05:24   2> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:699)
16:05:24   2> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
16:05:24   2> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
16:05:24   2> 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by original-brownbear** [comment]
Thanks, this reproduces easily for me locally. Fixing now:)
