### ISSUE TITLE
mixed_[CI] cluster/80_data_frame_jobs_crud/Test GET, start, and stop old cluster batch transforms

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#44807]
This has been failing quite a lot over the last couple of weeks: https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:%2280_data_frame_jobs_crud%22),sort:!(process.time-start,desc))

and failed on 7.x intake today: 

https://scans.gradle.com/s/7cqsr6aoaa6wa

Reproduction line: 
```
./gradlew :x-pack:qa:rolling-upgrade:v7.3.0#twoThirdsUpgradedTestRunner --tests "org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.test {p0=mixed_cluster/80_data_frame_jobs_crud/Test GET, start, and stop old cluster batch transforms}" -Dtests.seed=599A50ACD5F1F35F -Dtests.security.manager=true -Dtests.locale=en-AU -Dtests.timezone=Asia/Tel_Aviv -Dcompiler.java=12 -Druntime.java=8 -Dtests.rest.suite=mixed_cluster
```

Failure: 
```

org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT > test {p0=mixed_cluster/80_data_frame_jobs_crud/Test GET, start, and stop old cluster batch transforms} FAILED
--
java.lang.AssertionError: Failure at [mixed_cluster/80_data_frame_jobs_crud:134]: expected [2xx] status code but api [data_frame.start_data_frame_transform] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"exception","reason":"Starting dataframe [old-simple-transform] timed out after [30s]","stack_trace":"ElasticsearchException[Starting dataframe [old-simple-transform] timed out after [30s]]\n\tat org.elasticsearch.xpack.dataframe.action.TransportStartDataFrameTransformAction$2.onTimeout(TransportStartDataFrameTransformAction.java:331)\n\tat org.elasticsearch.persistent.PersistentTasksService$1.onTimeout(PersistentTasksService.java:173)\n\tat org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:325)\n\tat org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:252)\n\tat org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:572)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:688)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.lang.Thread.run(Thread.java:835)\n"}],"type":"exception","reason":"Starting dataframe [old-simple-transform] timed out after [30s]","stack_trace":"ElasticsearchException[Starting dataframe [old-simple-transform] timed out after [30s]]\n\tat org.elasticsearch.xpack.dataframe.action.TransportStartDataFrameTransformAction$2.onTimeout(TransportStartDataFrameTransformAction.java:331)\n\tat org.elasticsearch.persistent.PersistentTasksService$1.onTimeout(PersistentTasksService.java:173)\n\tat org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:325)\n\tat org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:252)\n\tat org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:572)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:688)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.lang.Thread.run(Thread.java:835)\n"},"status":500}]
 
```

```

[2019-07-24T14:22:15,465][INFO ][o.e.u.UpgradeClusterClientYamlTestSuiteIT] [test] Stash dump on test failure [{
--
1>   "stash" : {
1>     "body" : {
1>       "error" : {
1>         "root_cause" : [
1>           {
1>             "type" : "exception",
1>             "reason" : "Starting dataframe [old-simple-transform] timed out after [30s]",
1>             "stack_trace" : "ElasticsearchException[Starting dataframe [old-simple-transform] timed out after [30s]]
1> 	at org.elasticsearch.xpack.dataframe.action.TransportStartDataFrameTransformAction$2.onTimeout(TransportStartDataFrameTransformAction.java:331)
1> 	at org.elasticsearch.persistent.PersistentTasksService$1.onTimeout(PersistentTasksService.java:173)
1> 	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:325)
1> 	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:252)
1> 	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:572)
1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:688)
1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
1> 	at java.lang.Thread.run(Thread.java:835)
1> "
1>           }
1>         ],
1>         "type" : "exception",
1>         "reason" : "Starting dataframe [old-simple-transform] timed out after [30s]",
1>         "stack_trace" : "ElasticsearchException[Starting dataframe [old-simple-transform] timed out after [30s]]
1> 	at org.elasticsearch.xpack.dataframe.action.TransportStartDataFrameTransformAction$2.onTimeout(TransportStartDataFrameTransformAction.java:331)
1> 	at org.elasticsearch.persistent.PersistentTasksService$1.onTimeout(PersistentTasksService.java:173)
1> 	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:325)
1> 	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:252)
1> 	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:572)
1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:688)
1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
1> 	at java.lang.Thread.run(Thread.java:835)
1> "
1>       },
1>       "status" : 500
1>     }
1>   }
1> }]
```

**Comment by jkakavas** [comment]
Closing in favor of #44808
