### ISSUE TITLE
[TEST] IndexLifecycleInitialisationTests#testExplainExecution failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#44943]
Build scan: https://gradle.com/s/dxhi5ukbyipee

Relevant output:

```
org.elasticsearch.xpack.ilm.IndexLifecycleInitialisationTests > testExplainExecution FAILED
    java.time.format.DateTimeParseException: Text '2019-07-29T06:54Z' could not be parsed at index 16
        at __randomizedtesting.SeedInfo.seed([9D5B884C7F0F4F4E:97A5C8C9D42F1CBF]:0)
        at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
        at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
        at java.time.Instant.parse(Instant.java:395)
        at org.elasticsearch.xpack.ilm.IndexLifecycleInitialisationTests.testExplainExecution(IndexLifecycleInitialisationTests.java:219)
REPRODUCE WITH: ./gradlew :x-pack:plugin:ilm:test --tests "org.elasticsearch.xpack.ilm.IndexLifecycleInitialisationTests.testExplainExecution" -Dtests.seed=9D5B884C7F0F4F4E -Dtests.security.manager=true -Dtests.locale=es-CL -Dtests.timezone=America/St_Lucia -Dcompiler.java=12 -Druntime.java=8
```

**Comment by gwbrown** [comment]
Looks like this API returns dates that aren't parsable with `Instant.parse()` - `Instant.parse("2019-07-29T06:54Z");` does indeed throw an exception. It looks like `Instant.parse()` requires the seconds field to be present, as `Instant.parse("2019-07-29T06:54:00Z");` is fine.
