### ISSUE TITLE
SnapshotLifecycleServiceTests testPolicyCRUD Failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#44997]
Oh foo-1 why can't you be foo-2

```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=33, name=Thread-4, state=RUNNABLE, group=TGRP-SnapshotLifecycleServiceTests]
	at __randomizedtesting.SeedInfo.seed([8A2CBE77ADFEBB1F:630A2E905817C3E]:0)
Caused by: java.lang.AssertionError: 
Expected: "foo-2"
     but: was "foo-1"
	at __randomizedtesting.SeedInfo.seed([8A2CBE77ADFEBB1F]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.slm.SnapshotLifecycleServiceTests.lambda$testPolicyCRUD$10(SnapshotLifecycleServiceTests.java:196)
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/966/console
https://scans.gradle.com/s/wvtal77kwzovq

**Comment by jkakavas** [comment]
This has been failing once in every while since it was introduced in July 15 : https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testPolicyCRUD),sort:!(time,desc))

**Comment by davidkyle** [comment]
Muted on master 7a64117e1d5e3447744cf4779b544444a135c950 and 7.x e18e9fa8c5473da6f03987be77c1dee2db5345fb

**Comment by henningandersen** [comment]
I had another instance of this in my PR build:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/10451/console
https://gradle-enterprise.elastic.co/s/oe6bpog42o5ju/tests/rfsroxnx4sflo-7moiun2tnnjde

It was on our reindex_v2 branch, but I had just merged origin/master some hours before and I doubt the reindex changes could cause this.

Did not reproduce locally using:

```
./gradlew ':x-pack:plugin:ilm:test' --tests "org.elasticsearch.xpack.slm.SnapshotLifecycleServiceTests.testPolicyCRUD" -Dtests.seed=4F8B0454D04C415D -Dtests.security.manager=true -Dtests.locale=sr-Latn-RS -Dtests.timezone=America/Managua -Dcompiler.java=12 -Druntime.java=11
```

Exception:

```
WARNING: Uncaught exception in thread: Thread[Thread-4,5,TGRP-SnapshotLifecycleServiceTests]
java.lang.AssertionError: 
Expected: "foo-2"
     but: was "foo-1"
	at __randomizedtesting.SeedInfo.seed([4F8B0454D04C415D]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.slm.SnapshotLifecycleServiceTests.lambda$testPolicyCRUD$10(SnapshotLifecycleServiceTests.java:210)
	at org.elasticsearch.xpack.slm.SnapshotLifecycleServiceTests.lambda$testPolicyCRUD$5(SnapshotLifecycleServiceTests.java:160)
	at org.elasticsearch.xpack.slm.SnapshotLifecycleServiceTests$FakeSnapshotTask.triggered(SnapshotLifecycleServiceTests.java:323)
	at org.elasticsearch.xpack.core.scheduler.SchedulerEngine.notifyListeners(SchedulerEngine.java:182)
	at org.elasticsearch.xpack.core.scheduler.SchedulerEngine$ActiveSchedule.run(SchedulerEngine.java:210)
```

**Comment by jaymode** [comment]
This failure just occurred on a 7.x intake build:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+fast+part2/2085/
https://gradle-enterprise.elastic.co/s/44plmopn3xglw

Did not reproduce locally using:

```
./gradlew ':x-pack:plugin:ilm:test' --tests "org.elasticsearch.xpack.slm.SnapshotLifecycleServiceTests.testPolicyCRUD" -Dtests.seed=4079ED71C71FCFBC -Dtests.security.manager=true -Dtests.locale=he -Dtests.timezone=Mexico/BajaNorte -Dcompiler.java=12 -Druntime.java=8
```

Failure information and output:

```
1> [2019-11-14T12:20:03,919][INFO ][o.e.x.s.SnapshotLifecycleServiceTests] [testPolicyCRUD] before test
--
1> [2019-11-14T12:20:03,944][TRACE][o.e.x.s.SnapshotLifecycleService] [testPolicyCRUD] cancelling all snapshot lifecycle jobs
1> [2019-11-14T12:20:03,947][INFO ][o.e.x.s.SnapshotLifecycleService] [testPolicyCRUD] scheduling snapshot lifecycle job [foo-1]
1> [2019-11-14T12:20:04,002][INFO ][o.e.x.s.SnapshotLifecycleServiceTests] [[elasticsearch[trigger_engine_scheduler][T#1]]] --> fake snapshot task triggered: Event[jobName=foo-1,triggeredTime=1573762804001,scheduledTime=1573762804000]
1> [2019-11-14T12:20:04,012][DEBUG][o.e.x.s.SnapshotLifecycleService] [testPolicyCRUD] removing existing snapshot lifecycle job [foo-1] as it has been updated
1> [2019-11-14T12:20:04,013][INFO ][o.e.x.s.SnapshotLifecycleService] [testPolicyCRUD] rescheduling updated snapshot lifecycle job [foo-2]
1> [2019-11-14T12:20:05,004][INFO ][o.e.x.s.SnapshotLifecycleServiceTests] [[elasticsearch[trigger_engine_scheduler][T#1]]] --> fake snapshot task triggered: Event[jobName=foo-2,triggeredTime=1573762805011,scheduledTime=1573762805000]
1> [2019-11-14T12:20:05,018][INFO ][o.e.x.s.SnapshotLifecycleServiceTests] [[elasticsearch[trigger_engine_scheduler][T#1]]] --> fake snapshot task triggered: Event[jobName=foo-1,triggeredTime=1573762805011,scheduledTime=1573762805000]
1> [2019-11-14T12:20:05,026][ERROR][o.e.ExceptionsHelper     ] [[elasticsearch[trigger_engine_scheduler][T#1]]] fatal error
1> 	at org.elasticsearch.ExceptionsHelper.lambda$maybeDieOnAnotherThread$4(ExceptionsHelper.java:291)
1> 	at java.util.Optional.ifPresent(Optional.java:159)
1> 	at org.elasticsearch.ExceptionsHelper.maybeDieOnAnotherThread(ExceptionsHelper.java:281)
1> 	at org.elasticsearch.xpack.core.scheduler.SchedulerEngine$ActiveSchedule.run(SchedulerEngine.java:220)
1> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
1> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
1> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
1> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
1> 	at java.lang.Thread.run(Thread.java:748)
1> [2019-11-14T12:20:05,045][DEBUG][o.e.x.s.SnapshotLifecycleService] [testPolicyCRUD] cancelling snapshot lifecycle job [foo-2] as it no longer exists
1> [2019-11-14T12:20:05,047][INFO ][o.e.x.s.SnapshotLifecycleService] [testPolicyCRUD] scheduling snapshot lifecycle job [foo-3]
2> נוב 14, 2019 12:20:05 PM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
2> WARNING: Uncaught exception in thread: Thread[Thread-5,5,TGRP-SnapshotLifecycleServiceTests]
2> java.lang.AssertionError:
2> Expected: "foo-2"
2>      but: was "foo-1"
2> 	at __randomizedtesting.SeedInfo.seed([4079ED71C71FCFBC]:0)
2> 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
2> 	at org.junit.Assert.assertThat(Assert.java:956)
2> 	at org.junit.Assert.assertThat(Assert.java:923)
2> 	at org.elasticsearch.xpack.slm.SnapshotLifecycleServiceTests.lambda$testPolicyCRUD$10(SnapshotLifecycleServiceTests.java:210)
2> 	at org.elasticsearch.xpack.slm.SnapshotLifecycleServiceTests.lambda$testPolicyCRUD$5(SnapshotLifecycleServiceTests.java:160)
2> 	at org.elasticsearch.xpack.slm.SnapshotLifecycleServiceTests$FakeSnapshotTask.triggered(SnapshotLifecycleServiceTests.java:323)
2> 	at org.elasticsearch.xpack.core.scheduler.SchedulerEngine.notifyListeners(SchedulerEngine.java:183)
2> 	at org.elasticsearch.xpack.core.scheduler.SchedulerEngine$ActiveSchedule.run(SchedulerEngine.java:211)
2> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
2> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
2> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2> 	at java.lang.Thread.run(Thread.java:748)
 
1> [2019-11-14T12:20:06,037][INFO ][o.e.x.s.SnapshotLifecycleServiceTests] [[elasticsearch[trigger_engine_scheduler][T#1]]] --> fake snapshot task triggered: Event[jobName=foo-3,triggeredTime=1573762809011,scheduledTime=1573762808000]
1> [2019-11-14T12:20:06,089][TRACE][o.e.x.s.SnapshotLifecycleService] [testPolicyCRUD] cancelling all snapshot lifecycle jobs
1> [2019-11-14T12:20:06,093][INFO ][o.e.x.s.SnapshotLifecycleServiceTests] [testPolicyCRUD] after test
2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:test' --tests "org.elasticsearch.xpack.slm.SnapshotLifecycleServiceTests.testPolicyCRUD" -Dtests.seed=4079ED71C71FCFBC -Dtests.security.manager=true -Dtests.locale=he -Dtests.timezone=Mexico/BajaNorte -Dcompiler.java=12 -Druntime.java=8
```

**Comment by dnhatn** [comment]
Another instance: https://gradle-enterprise.elastic.co/s/syv4mizwetqwi

**Comment by dnhatn** [comment]
I've muted this test in 7.x.

**Comment by dnhatn** [comment]
Another instance: https://gradle-enterprise.elastic.co/s/evx76lloqok7u

```
org.elasticsearch.xpack.slm.SnapshotLifecycleServiceTests > testPolicyCRUD FAILED
    java.lang.AssertionError: 
    Expected: <2>
         but: was <3>
        at __randomizedtesting.SeedInfo.seed([A84564625E890D00:245978FCF6F6CA21]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.slm.SnapshotLifecycleServiceTests.testPolicyCRUD(SnapshotLifecycleServiceTests.java:251)
```

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:test' --tests "org.elasticsearch.xpack.slm.SnapshotLifecycleServiceTests.testPolicyCRUD" -Dtests.seed=A84564625E890D00 -Dtests.security.manager=true -Dtests.locale=hr -Dtests.timezone=Europe/Warsaw -Druntime.java=8
```

**Comment by martijnvg** [comment]
This test has failed again today: https://gradle-enterprise.elastic.co/s/efml3c5zja3sg
and it has been failing 4 times in the last 90 days: https://ci-stats.elastic.co/s/jenkins/goto/378cca80-b58e-11ec-862b-a9011215e622

and it doesn't reproduce locally.

I'm going to mute this test.

**Comment by albertzaharovits** [comment]
FYI Also fails on 7.17 https://github.com/elastic/elasticsearch/issues/44997 , but with a different error:
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:test' --tests "org.elasticsearch.xpack.slm.SnapshotLifecycleServiceTests.testPolicyCRUD" -Dtests.seed=65EC5D9A40596450 -Dtests.locale=sk-SK -Dtests.timezone=America/Monterrey -Druntime.java=20

org.elasticsearch.xpack.slm.SnapshotLifecycleServiceTests > testPolicyCRUD FAILED
    java.lang.AssertionError: 
    Expected: <2>
         but: was <3>
        at __randomizedtesting.SeedInfo.seed([65EC5D9A40596450:E9F04104E826A371]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.slm.SnapshotLifecycleServiceTests.testPolicyCRUD(SnapshotLifecycleServiceTests.java:286)
```
It only failed once in the last 7 days, but ran 700 times. I'll leave it be, unmuted.

**Comment by andreidan** [comment]
I'll leave this as `blocker` mostly due to its age but otherwise it's a low risk IMO.
