### ISSUE TITLE
Zen1IT testMixedClusterDisruption failure 

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#44999]
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=4271, name=elasticsearch[node_t1][generic][T#1], state=RUNNABLE, group=TGRP-Zen1IT]
	at __randomizedtesting.SeedInfo.seed([AF1FB5A2ED266918:31BD93082B493CBD]:0)
Caused by: java.lang.AssertionError: Interruption via Thread#interrupt() is unsupported. Use CancellableThreads#cancel() instead
	at __randomizedtesting.SeedInfo.seed([AF1FB5A2ED266918]:0)
	at org.elasticsearch.common.util.CancellableThreads.executeIO(CancellableThreads.java:111)
	at org.elasticsearch.common.util.CancellableThreads.execute(CancellableThreads.java:89)
	at org.elasticsearch.discovery.SeedHostsResolver.resolveHostsLists(SeedHostsResolver.java:148)
	at org.elasticsearch.discovery.zen.UnicastZenPing.lambda$createHostsResolver$0(UnicastZenPing.java:150)
	at org.elasticsearch.discovery.FileBasedSeedHostsProvider.getSeedAddresses(FileBasedSeedHostsProvider.java:78)
	at org.elasticsearch.discovery.DiscoveryModule.lambda$new$4(DiscoveryModule.java:142)
	at org.elasticsearch.discovery.zen.UnicastZenPing.ping(UnicastZenPing.java:196)
	at org.elasticsearch.discovery.zen.UnicastZenPing.ping(UnicastZenPing.java:185)
	at org.elasticsearch.discovery.zen.ZenDiscovery.pingAndWait(ZenDiscovery.java:962)
	at org.elasticsearch.discovery.zen.ZenDiscovery.findMaster(ZenDiscovery.java:806)
	at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:442)
	at org.elasticsearch.discovery.zen.ZenDiscovery.access$1800(ZenDiscovery.java:94)
	at org.elasticsearch.discovery.zen.ZenDiscovery$JoinThreadControl$1.run(ZenDiscovery.java:1173)
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.3+multijob-unix-compatibility/os=centos-6&&immutable/55/console
https://scans.gradle.com/s/wmjvjscjqm2j6/tests/kyv2y2z3r4v7m-ii3qqlnw5mxvg

Looks related to #44430

**Comment by davidkyle** [comment]
Muted
7.x cf78ca58e3f9c402982f039a9223042c90f5bc74
7.3 612e0466d55819ca40cee954b6ebc18ae9ecc405

**Comment by ywelsch** [comment]
I had forgotten to backport #44430 to 7.3. Fixed now, and reverted the mutes here.
