### ISSUE TITLE
FilteringAllocationIT testTransientSettingsStillApplied failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#45003]
```
java.lang.AssertionError: shard on node_t0 but should only be on the include node list: node_t5,node_t4,node_t3
	at __randomizedtesting.SeedInfo.seed([3B129C65D01A4727:A7A99B21FD38F20A]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.elasticsearch.cluster.allocation.FilteringAllocationIT.testTransientSettingsStillApplied(FilteringAllocationIT.java:213)
``` 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=debian-8&&immutable/171/console
https://gradle.com/s/mjyiygpvwyuja

Does not reproduce 
```
./gradlew :server:integTest --tests "org.elasticsearch.cluster.allocation.FilteringAllocationIT.testTransientSettingsStillApplied" \
  -Dtests.seed=3B129C65D01A4727 \
  -Dtests.security.manager=true \
  -Dtests.locale=ar \
  -Dtests.timezone=Indian/Cocos \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

**Comment by davidkyle** [comment]
There have been a few failures on the 7.x branch. Muted in 78aa6143a64d1ce59fb04d4db5dd560f60154f54
