### ISSUE TITLE
[CI] JdbcResultSetIT.testGettingBooleanValues fails

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#45035]
This is for 6.8, but I couldn't reproduce it no matter how many time I ran the tests. I'll open this issue in case there will be future failures with maybe more useful reproduceable data.

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:sql:qa:single-node:integTestRunner \
  -Dtests.seed=5640D4420A440553 \
  -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT \
  -Dtests.method="testGettingBooleanValues" \
  -Dtests.security.manager=true \
  -Dtests.locale=fa-IR \
  -Dtests.timezone=Africa/Accra \
  -Dcompiler.java=12 \
  -Druntime.java=12
```

```
05:25:20   1> [2019-07-31T02:25:12,447][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingBooleanValues] before test
05:25:20   1> [2019-07-31T02:25:12,538][WARN ][o.e.c.RestClient         ] [[I/O dispatcher 33]] request [PUT http://[::1]:43067/test] returned 1 warnings: [299 Elasticsearch-6.8.3-SNAPSHOT-bdce9ea "[types removal] The parameter include_type_name should be explicitly specified in create index requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', and requests are expected to omit the type name in mapping definitions."]
05:25:20   1> [2019-07-31T02:25:12,560][WARN ][o.e.c.RestClient         ] [[I/O dispatcher 33]] request [PUT http://[::1]:43067/test/_mapping/doc] returned 1 warnings: [299 Elasticsearch-6.8.3-SNAPSHOT-bdce9ea "[types removal] Specifying types in put mapping requests is deprecated. To be compatible with 7.0, the mapping definition should not be nested under the type name, and the parameter include_type_name must be provided and set to false."]
05:25:20   1> [2019-07-31T02:25:12,582][WARN ][o.e.c.RestClient         ] [[I/O dispatcher 33]] request [PUT http://[::1]:43067/test/_mapping/doc] returned 1 warnings: [299 Elasticsearch-6.8.3-SNAPSHOT-bdce9ea "[types removal] Specifying types in put mapping requests is deprecated. To be compatible with 7.0, the mapping definition should not be nested under the type name, and the parameter include_type_name must be provided and set to false."]
05:25:20   1> [2019-07-31T02:25:12,801][INFO ][o.e.x.s.q.s.JdbcResultSetIT] [testGettingBooleanValues] after test
05:25:20   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:sql:qa:single-node:integTestRunner -Dtests.seed=5640D4420A440553 -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT -Dtests.method="testGettingBooleanValues" -Dtests.security.manager=true -Dtests.locale=fa-IR -Dtests.timezone=Africa/Accra -Dcompiler.java=12 -Druntime.java=12
05:25:20 FAILURE 0.38s | JdbcResultSetIT.testGettingBooleanValues <<< FAILURES!
05:25:20    > Throwable #1: org.junit.ComparisonFailure: expected:<... [+260620618-11-20T0[7:14:00.194+06]:00] of type [DATETI...> but was:<... [+260620618-11-20T0[6:14:00.194+05]:00] of type [DATETI...>
05:25:20    > 	at __randomizedtesting.SeedInfo.seed([5640D4420A440553:1C76829888ED0CEE]:0)
05:25:20    > 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.lambda$testGettingBooleanValues$132(ResultSetTestCase.java:841)
05:25:20    > 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1402)
05:25:20    > 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1390)
05:25:20    > 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.testGettingBooleanValues(ResultSetTestCase.java:833)
05:25:20    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:25:20    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
05:25:20    > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:25:20    > 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
05:25:20    > 	at java.base/java.lang.Thread.run(Thread.java:835)
```

```
OS | Ubuntu 18.04.2 LTS, Linux 4.15.0-1037-gcp
-- | --
Specs | 16 CPUs, 58.98GB RAM
java.version | 12.0.2
java.vm.name | OpenJDK 64-Bit Server VM
java.vm.version | 12.0.2+10
java.runtime.version | 12.0.2+10
java.home | /var/lib/jenkins/.java/openjdk-12.0.2-linux
```

**Comment by astefan** [comment]
Another related failure. Still on 6.8.

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:sql:qa:single-node:integTestRunner \
  -Dtests.seed=29F25BB852C8DEE6 \
  -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT \
  -Dtests.method="testGettingInvalidFloat" \
  -Dtests.security.manager=true \
  -Dtests.locale=ig \
  -Dtests.timezone=Europe/Mariehamn \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

```
org.junit.ComparisonFailure: expected:<... [+250096236-03-17T0[9:47:33.531+06]:00] of type [DATETI...> but was:<... [+250096236-03-17T0[8:47:33.531+05]:00] of type [DATETI...>
	at __randomizedtesting.SeedInfo.seed([29F25BB852C8DEE6:84401ECFA3039D08]:0)
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.lambda$testGettingInvalidFloat$115(ResultSetTestCase.java:780)
	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1402)
	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1390)
	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.testGettingInvalidFloat(ResultSetTestCase.java:769)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

```
OS | Ubuntu 18.04.2 LTS, Linux 4.15.0-1037-gcp
-- | --
Specs | 16 CPUs, 58.98GB RAM
java.version | 12.0.2
java.vm.name | OpenJDK 64-Bit Server VM
java.vm.version | 12.0.2+10
java.runtime.version | 12.0.2+10
java.home | /var/lib/jenkins/.java/openjdk-12.0.2-linux
```

**Comment by astefan** [comment]
And another one.

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:sql:qa:single-node:integTestRunner \
  -Dtests.seed=F60CF76B59950A04 \
  -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT \
  -Dtests.method="testGettingInvalidLong" \
  -Dtests.security.manager=true \
  -Dtests.locale=mt \
  -Dtests.timezone=America/Asuncion \
  -Dcompiler.java=12 \
  -Druntime.java=12
```

```
org.junit.ComparisonFailure: expected:<... [+199398680-01-06T1[6:13:49.361+06]:00] of type [DATETI...> but was:<... [+199398680-01-06T1[5:13:49.361+05]:00] of type [DATETI...>
	at __randomizedtesting.SeedInfo.seed([F60CF76B59950A04:E9DD9EA14C49494C]:0)
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.lambda$testGettingInvalidLong$91(ResultSetTestCase.java:614)
	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1402)
	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1390)
	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.testGettingInvalidLong(ResultSetTestCase.java:593)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

```
OS | Ubuntu 18.04.2 LTS, Linux 4.15.0-1037-gcp
-- | --
Specs | 16 CPUs, 58.98GB RAM
java.version | 12.0.2
java.vm.name | OpenJDK 64-Bit Server VM
java.vm.version | 12.0.2+10
java.runtime.version | 12.0.2+10
java.home | /var/lib/jenkins/.java/openjdk-12.0.2-linux
```

**Comment by costin** [comment]
https://github.com/elastic/elasticsearch/issues/48978 seems to be quite similar.

**Comment by DaveCTurner** [comment]
https://gradle-enterprise.elastic.co/s/7w3napqdmw5yu looks like another

**Comment by tlrx** [comment]
Another failure https://gradle-enterprise.elastic.co/s/jycf4tpmvyvgs

**Comment by astefan** [comment]
Fixed with https://github.com/elastic/elasticsearch/pull/51592.
