### ISSUE TITLE
Update to Elasticsearch 7.3 fails if existing index uses old definition of dense vectors

### ISSUE THREAD

**Issue by kesslerm** [elastic/elasticsearch#45060]
A cluster update from 7.2.0 to 7.3.0 fails due to a mapping mismatch for dense vectors. An existing index contained field of type `dense_vector` created under version 7.0

```
{"type": "server", "timestamp": "2019-07-31T18:45:31,210+0000", "level": "ERROR", "component": "o.e.g.GatewayMetaState", "cluster.name": "docker_test", "node.name": "core3",  "message": "failed to read or upgrade local state, exiting..." ,
"stacktrace": ["java.lang.IllegalStateException: unable to upgrade the mappings for the index [[test-vector/f3AYPwzBQCWHqKWXSzTPUg]]",
"at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.checkMappingsCompatibility(MetaDataIndexUpgradeService.java:205) ~[elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.upgradeIndexMetaData(MetaDataIndexUpgradeService.java:103) ~[elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.gateway.GatewayMetaState.upgradeMetaData(GatewayMetaState.java:419) ~[elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.gateway.GatewayMetaState.upgradeMetaData(GatewayMetaState.java:153) [elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:95) [elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.node.Node.<init>(Node.java:492) [elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.node.Node.<init>(Node.java:258) [elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) [elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) [elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) [elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-7.3.0.jar:7.3.0]",
"at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-7.3.0.jar:7.3.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) [elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-7.3.0.jar:7.3.0]",
"Caused by: org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [_doc]: The [dims] property must be specified for field [dense].",
"at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:404) ~[elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:358) ~[elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:337) ~[elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.checkMappingsCompatibility(MetaDataIndexUpgradeService.java:201) ~[elasticsearch-7.3.0.jar:7.3.0]",
"... 16 more",
"Caused by: org.elasticsearch.index.mapper.MapperParsingException: The [dims] property must be specified for field [dense].",
"at org.elasticsearch.xpack.vectors.mapper.DenseVectorFieldMapper$TypeParser.parse(DenseVectorFieldMapper.java:102) ~[?:?]",
"at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:276) ~[elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:196) ~[elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.index.mapper.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:130) ~[elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:108) ~[elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:88) ~[elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:402) ~[elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:358) ~[elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:337) ~[elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.checkMappingsCompatibility(MetaDataIndexUpgradeService.java:201) ~[elasticsearch-7.3.0.jar:7.3.0]",
"... 16 more"] }
```

The node crashes at this point. Downgrade to 7.2.0 is no longer possible due to a partial upgrade having succeeded at this point.

**Comment by jasontedor** [comment]
I am removing the critical label since dense vectors are an experimental feature.

> Downgrade to 7.2.0 is no longer possible due to a partial upgrade having succeeded at this point.

Only the new node state will have been written out. You can overwrite the version with the `elasticsearch-node` tool and downgrade back to 7.2.0.

**Comment by kesslerm** [comment]
`elasticsearch-node override` from Elasticsearch 7.2 allows for the downgrade to happen successfully. For now I just removed the offending index that used the old definition of dense vectors, after which the upgrade to 7.3 succeeds.
