### ISSUE TITLE
failed to parse field [zookeeper.server.version_date] of type [date]

### ISSUE THREAD

**Issue by leonliah** [elastic/elasticsearch#45071]
Metricbeat zookeeper.

**Elasticsearch version** (`7.2`): 7.2

**Plugins installed**: []

**JVM version** (`java -version`):openjdk version "12.0.1" 2019-04-16

**OS version** (`uname -a` if on a Unix-like system): Linux elalstic-master 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

```
"zookeeper":{  
   "server":{  
      "epoch":5,
      "count":1508137,
      "connections":46,
      "node_count":1124,
      "sent":23220856,
      "received":23219049,
      "outstanding":0,
      "mode":"follower",
      "latency":{  
         "min":0,
         "avg":0,
         "max":7294
      },
      "zxid":"0x500170329",
      **_"version_date":"06/08/2017 23:26 GMT"_**
   }
}
```

```
[elasticsearch.server][DEBUG] [0] failed to execute bulk item (index) index {[metricbeat-7.2.0][_doc][cKatS2wBRMhfHyJkGuM1], source[{"@timestamp":"2019-08-01T05:35:30.421Z","event":{"dataset":"zookeeper.server","module":"zookeeper","duration":824793},"metricset":{"name":"server"},"zookeeper":{"server":{"epoch":5,"count":1508137,"connections":46,"node_count":1124,"sent":23220856,"received":23219049,"outstanding":0,"mode":"follower","latency":{"min":0,"avg":0,"max":7294},"zxid":"0x500170329","version_date":"06/08/2017 23:26 GMT"}},"ecs":{"version":"1.0.0"},"host":{"name":"qag1ge1lzoo001.ag1.taservs.net","hostname":"qag1ge1lzoo001.ag1.taservs.net","architecture":"x86_64","os":{"version":"7 (Core)","family":"redhat","name":"CentOS Linux","kernel":"3.10.0-957.21.3.el7.x86_64","codename":"Core","platform":"centos"},"id":"aff1b5cc31874aef93f1685d5dc9be50","containerized":false},"agent":{"id":"babb48fd-701a-4177-ae68-cbef04900f03","version":"7.2.0","type":"metricbeat","ephemeral_id":"a85025ac-43e8-4d85-892d-a7c0524ec30d","hostname":"qag1ge1lzoo001.ag1.taservs.net"},"cloud":{"provider":"az","instance":{"id":"571a2381-1903-4e6b-bcc7-407d274d973a","name":"qag1ge1lzoo001"},"machine":{"type":"Standard_DS2_v2"},"region":"usgovvirginia"},"service":{"type":"zookeeper","version":"3.4.11-SNAPSHOT-b3e514659393837a6e824038463c0a98efff2fdb","address":"localhost:2181"}}]}
```

```
org.elasticsearch.index.mapper.MapperParsingException: ### **_failed to parse field [zookeeper.server.version_date] of type [date]_** in document with id 'cKatS2wBRMhfHyJkGuM1'
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:280) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:488) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:614) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:427) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:395) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:485) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:505) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:418) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:395) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:485) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:505) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:418) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:395) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.mapper.DocumentParser.internalParseDocument(DocumentParser.java:112) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:71) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:267) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:764) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:741) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:713) ~[elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:256) [elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:159) [elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:191) [elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:116) [elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:77) [elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryShardReference.perform(TransportReplicationAction.java:927) [elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.action.support.replication.ReplicationOperation.execute(ReplicationOperation.java:108) [elasticsearch-7.2.0.jar:7.2.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.runWithPrimaryShardReference(TransportReplicationAction.java:398) [elasticsearch-7.2.0.jar:7.2.0]
```

**Comment by tvernum** [comment]
@leonliah It sounds like you're trying to report this as a bug in metricbeat - is that correct?
