### ISSUE TITLE
org.elasticsearch.search.aggregations.pipeline.BucketScriptAggregatorTests.testScript test failure

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#45242]
This test failed on my PR, but reproduces reliably.

```
./gradlew :server:test --tests "org.elasticsearch.search.aggregations.pipeline.BucketScriptAggregatorTests.testScript" -Dtests.seed=AD4D82C37AFE3632 -Dtests.security.manager=true -Dtests.locale=ki-KE -Dtests.timezone=AET -Dcompiler.java=12 -Druntime.java=11
```

Failure:
```
org.elasticsearch.search.aggregations.pipeline.BucketScriptAggregatorTests > testScript FAILED
    java.lang.ClassCastException: class org.apache.lucene.index.ParallelCompositeReader cannot be cast to class org.apache.lucene.index.DirectoryReader (org.apache.lucene.index.ParallelCompositeReader and org.apache.lucene.index.DirectoryReader are in unnamed module of loader 'app')
        at __randomizedtesting.SeedInfo.seed([AD4D82C37AFE3632:D8E5C3231E8EA5C0]:0)
        at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals$FieldData.globalOrdinalsValues(ValuesSource.java:160)
        at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals.globalMaxOrd(ValuesSource.java:133)
        at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.getMaxOrd(TermsAggregatorFactory.java:216)
        at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory$ExecutionMode$2.create(TermsAggregatorFactory.java:261)
        at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.doCreateInternal(TermsAggregatorFactory.java:155)
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:49)
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:217)
        at org.elasticsearch.search.aggregations.AggregatorFactory.asMultiBucketAggregator(AggregatorFactory.java:231)
        at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.doCreateInternal(TermsAggregatorFactory.java:116)
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:49)
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:217)
        at org.elasticsearch.search.aggregations.AggregatorFactories.createSubAggregators(AggregatorFactories.java:198)
        at org.elasticsearch.search.aggregations.AggregatorBase.<init>(AggregatorBase.java:77)
        at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.<init>(BucketsAggregator.java:47)
        at org.elasticsearch.search.aggregations.bucket.filter.FiltersAggregator.<init>(FiltersAggregator.java:128)
        at org.elasticsearch.search.aggregations.bucket.filter.FiltersAggregatorFactory.createInternal(FiltersAggregatorFactory.java:90)
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:217)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.createAggregator(AggregatorTestCase.java:217)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.createAggregator(AggregatorTestCase.java:198)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:368)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:335)
        at org.elasticsearch.search.aggregations.pipeline.BucketScriptAggregatorTests.testCase(BucketScriptAggregatorTests.java:117)
        at org.elasticsearch.search.aggregations.pipeline.BucketScriptAggregatorTests.testScript(BucketScriptAggregatorTests.java:88)
```

PR build failure:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/4218/

**Comment by polyfractal** [comment]
On it!
