### ISSUE TITLE
elastic search 7.3 setup

### ISSUE THREAD

**Issue by Ramizzzz** [elastic/elasticsearch#45319]
Hi 
**anyone ans me**

i download elasticsearch 7.3 version and i run <../../../elasticsearch-7.3.0\bin>elasticsearch command 

im using
 **window 10 32 bit os
 java version java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) Client VM (build 25.202-b08, mixed mode)**

**i have see the below issue:**

future versions of Elasticsearch will require Java 11; your Java version from [C:\Program Files\Java\jdk1.8.0_202\jre] does not meet this requirement
[2019-08-08T12:42:13,721][INFO ][o.e.e.NodeEnvironment    ] [DESKTOP-RQQIGQ7] using [1] data paths, mounts [[New Volume (D:)]], net usable_space [182.7gb], net total_space [199.3gb], types [NTFS]
[2019-08-08T12:42:13,721][INFO ][o.e.e.NodeEnvironment    ] [DESKTOP-RQQIGQ7] heap size [998.4mb], compressed ordinary object pointers [unknown]
[2019-08-08T12:42:13,737][INFO ][o.e.n.Node               ] [DESKTOP-RQQIGQ7] node name [DESKTOP-RQQIGQ7], node ID [0x7dDWZ_RVGIMp6MCXiGKA], cluster name [elasticsearch]
[2019-08-08T12:42:13,737][INFO ][o.e.n.Node               ] [DESKTOP-RQQIGQ7] version[7.3.0], pid[4388], build[default/zip/de777fa/2019-07-24T18:30:11.767338Z], OS[Windows 10/10.0/x86], JVM[Oracle Corporation/Java HotSpot(TM) Client VM/1.8.0_202/25.202-b08]
[2019-08-08T12:42:13,737][INFO ][o.e.n.Node               ] [DESKTOP-RQQIGQ7] JVM home [C:\Program Files\Java\jdk1.8.0_202\jre]
[2019-08-08T12:42:13,737][INFO ][o.e.n.Node               ] [DESKTOP-RQQIGQ7] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=C:\Users\ramiz\AppData\Local\Temp\elasticsearch, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Dio.netty.allocator.type=unpooled, -XX:MaxDirectMemorySize=536870912, -Delasticsearch, -Des.path.home=D:\Mellon\health-care\elasticsearch-7.3.0-windows-x86_64\elasticsearch-7.3.0, -Des.path.conf=D:\Mellon\health-care\elasticsearch-7.3.0-windows-x86_64\elasticsearch-7.3.0\config, -Des.distribution.flavor=default, -Des.distribution.type=zip, -Des.bundled_jdk=true]
[2019-08-08T12:42:16,518][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [aggs-matrix-stats]
[2019-08-08T12:42:16,519][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [analysis-common]
[2019-08-08T12:42:16,521][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [data-frame]
[2019-08-08T12:42:16,524][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [flattened]
[2019-08-08T12:42:16,525][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [ingest-common]
[2019-08-08T12:42:16,526][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [ingest-geoip]
[2019-08-08T12:42:16,527][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [ingest-user-agent]
[2019-08-08T12:42:16,527][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [lang-expression]
[2019-08-08T12:42:16,528][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [lang-mustache]
[2019-08-08T12:42:16,529][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [lang-painless]
[2019-08-08T12:42:16,534][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [mapper-extras]
[2019-08-08T12:42:16,535][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [parent-join]
[2019-08-08T12:42:16,536][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [percolator]
[2019-08-08T12:42:16,537][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [rank-eval]
[2019-08-08T12:42:16,538][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [reindex]
[2019-08-08T12:42:16,539][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [repository-url]
[2019-08-08T12:42:16,539][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [transport-netty4]
[2019-08-08T12:42:16,540][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [vectors]
[2019-08-08T12:42:16,541][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [x-pack-ccr]
[2019-08-08T12:42:16,546][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [x-pack-core]
[2019-08-08T12:42:16,547][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [x-pack-deprecation]
[2019-08-08T12:42:16,548][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [x-pack-graph]
[2019-08-08T12:42:16,548][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [x-pack-ilm]
[2019-08-08T12:42:16,549][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [x-pack-logstash]
[2019-08-08T12:42:16,550][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [x-pack-ml]
[2019-08-08T12:42:16,550][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [x-pack-monitoring]
[2019-08-08T12:42:16,551][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [x-pack-rollup]
[2019-08-08T12:42:16,552][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [x-pack-security]
[2019-08-08T12:42:16,556][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [x-pack-sql]
[2019-08-08T12:42:16,557][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [x-pack-voting-only-node]
[2019-08-08T12:42:16,557][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] loaded module [x-pack-watcher]
[2019-08-08T12:42:16,558][INFO ][o.e.p.PluginsService     ] [DESKTOP-RQQIGQ7] no plugins loaded
[2019-08-08T12:42:23,484][INFO ][o.e.x.s.a.s.FileRolesStore] [DESKTOP-RQQIGQ7] parsed [0] roles from file [D:\Mellon\health-care\elasticsearch-7.3.0-windows-x86_64\elasticsearch-7.3.0\config\roles.yml]
[2019-08-08T12:42:28,019][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [DESKTOP-RQQIGQ7] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[X-Pack is not supported and Machine Learning is not available for [windows-x86]; you can use the other X-Pack features (unsupported) by setting xpack.ml.enabled: false in elasticsearch.yml]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.3.0.jar:7.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.3.0.jar:7.3.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.3.0.jar:7.3.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-7.3.0.jar:7.3.0]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.3.0.jar:7.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.3.0.jar:7.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.3.0.jar:7.3.0]
Caused by: org.elasticsearch.ElasticsearchException: X-Pack is not supported and Machine Learning is not available for [windows-x86]; you can use the other X-Pack features (unsupported) by setting xpack.ml.enabled: false in elasticsearch.yml
        at org.elasticsearch.xpack.ml.MachineLearningFeatureSet.isRunningOnMlPlatform(MachineLearningFeatureSet.java:106) ~[?:?]
        at org.elasticsearch.xpack.ml.MachineLearningFeatureSet.isRunningOnMlPlatform(MachineLearningFeatureSet.java:97) ~[?:?]
        at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLearning.java:474) ~[?:?]
        at org.elasticsearch.node.Node.lambda$new$9(Node.java:457) ~[elasticsearch-7.3.0.jar:7.3.0]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_202]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_202]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_202]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_202]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_202]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_202]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_202]
        at org.elasticsearch.node.Node.<init>(Node.java:460) ~[elasticsearch-7.3.0.jar:7.3.0]
        at org.elasticsearch.node.Node.<init>(Node.java:258) ~[elasticsearch-7.3.0.jar:7.3.0]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.3.0.jar:7.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.3.0.jar:7.3.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.3.0.jar:7.3.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.3.0.jar:7.3.0]
        ... 6 more

**Comment by hendrikmuhs** [comment]
@Ramizzzz 

the log says it:

```
[2019-08-08T12:42:28,019][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [DESKTOP-RQQIGQ7] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[X-Pack is not supported and Machine Learning is not available for [windows-x86]; you can use the other X-Pack features (unsupported) by setting xpack.ml.enabled: false in elasticsearch.yml]
```

Windows 32 bit is an unsupported platform, see: https://www.elastic.co/support/matrix

You can still run it, but you are on your own. However ML is not supported, so you have to disable it, more information can be found on: https://www.elastic.co/guide/en/elasticsearch/reference/current/ml-settings.html

For further help please use our discuss platform: https://discuss.elastic.co/

Github issues are not meant for support but bugs and feature requests.
