### ISSUE TITLE
[CI] MockDiskUsagesIT.testAutomaticReleaseOfIndexBlock fails

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#45338]
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+release-tests/232/console

Build scan: https://gradle.com/s/wnz3akbwhhnne

Reproduce with:

```
./gradlew :server:integTest --tests "org.elasticsearch.cluster.routing.allocation.decider.MockDiskUsagesIT.testAutomaticReleaseOfIndexBlock" -Dtests.seed=815A6FA6949ACF83 -Dtests.security.manager=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=mt-MT -Dtests.timezone=Asia/Ashgabat -Dcompiler.java=12 -Druntime.java=8
```

Failure:

```
java.lang.AssertionError: Request executed with success but a ClusterBlockException was expectedClose stacktrace
at __randomizedtesting.SeedInfo.seed([815A6FA6949ACF83:CAD3581BABADC932]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertBlocked(ElasticsearchAssertions.java:166)
at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertBlocked(ElasticsearchAssertions.java:191)
at org.elasticsearch.cluster.routing.allocation.decider.MockDiskUsagesIT.testAutomaticReleaseOfIndexBlock(MockDiskUsagesIT.java:211)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at java.lang.Thread.run(Thread.java:748)
```

Could not reproduce locally.

**Comment by dimitris-athanasiou** [comment]
This test was introduced recently in https://github.com/elastic/elasticsearch/pull/42559

**Comment by dimitris-athanasiou** [comment]
Muted the test in both `master` and `7.x` by 42e8b36f5e2d134d0212baa5932e5a99f8c00386 and e53bb050dbd918d7995d3f98af6fe2b450696430 respectively.

**Comment by dakrone** [comment]
This failed again today:

```
  2> java.lang.AssertionError: Request executed with success but a ClusterBlockException was expected
        at __randomizedtesting.SeedInfo.seed([CE5B07216BD6F25A:85D2309C54E1F4EB]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertBlocked(ElasticsearchAssertions.java:166)
        at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertBlocked(ElasticsearchAssertions.java:191)
        at org.elasticsearch.cluster.routing.allocation.decider.MockDiskUsagesIT.testAutomaticReleaseOfIndexBlock(MockDiskUsagesIT.java:197)
```

Reproduction line (this did not reproduce for me) is:

```
./gradlew ':server:integTest' --tests "org.elasticsearch.cluster.routing.allocation.decider.MockDiskUsagesIT.testAutomaticReleaseOfIndexBlock" -Dtests.seed=CE5B07216BD6F25A -Dtests.security.manager=true -Dtests.locale=en-GD -Dtests.timezone=America/Catamarca -Dcompiler.java=12 -Druntime.java=12
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java12,nodes=general-purpose/240/console
https://gradle-enterprise.elastic.co/s/cyiv347vuav34
