### ISSUE TITLE
Problem reading index from store(mmapfs(/data3/nodes/1/indices/P3GEjUvnSKCnYOf_giLm7w/12/index))

### ISSUE THREAD

**Issue by liulinisgood** [elastic/elasticsearch#45430]
I met a error for a long time, it occurs at 23:10 every day , I am very puzzled.
ES version: 5.5.3
os: centos7 3.10.0-327.el7.x86_64
disk: ssd
jdk8, g1  
[2019-08-11T23:08:20,178][WARN ][o.e.i.e.Engine           ] [10.32.144.131_1] [index-2019-08-11][12] failed engine [refresh failed]
org.apache.lucene.index.CorruptIndexException: Problem reading index from store(mmapfs(/data3/nodes/1/indices/P3GEjUvnSKCnYOf_giLm7w/12/index)) (resource=store(mmapfs(/data3/nodes/1/indices/P3GEjUvnSKCnYOf_giLm7w/12/index)))
    at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:140) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
    at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:74) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
    at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:145) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
    at org.apache.lucene.index.ReadersAndUpdates.getReadOnlyClone(ReadersAndUpdates.java:197) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
    at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:103) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
    at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:467) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
    at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:291) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
    at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:266) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
    at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:256) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
    at org.apache.lucene.index.FilterDirectoryReader.doOpenIfChanged(FilterDirectoryReader.java:104) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
    at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:140) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
    at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:156) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
    at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
    at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
    at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253) ~[lucene-core-6.6.0.jar:6.6.0 5c7a7b65d2aa7ce5ec96458315c661a18b320241 - ishan - 2017-05-30 07:29:46]
    at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:910) [elasticsearch-5.5.3.jar:5.5.3]
    at org.elasticsearch.index.shard.IndexShard.refresh(IndexShard.java:632) [elasticsearch-5.5.3.jar:5.5.3]

I got these error logs above, then shard unassigned, unrecovered. The cluster health was red. I use checkIndex tool to check shard, but result was no problem.

**Comment by martijnvg** [comment]
Thanks very much for your interest in Elasticsearch. This kind of questions / problems should first be posted in the [forums](https://discuss.elastic.co/) before opening an issue in github. If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.

> I met a error for a long time, it occurs at 23:10 every day , I am very puzzled.

This looks like an automatic process doing something with ES and/or data directories.

> ES version: 5.5.3

This is an old version. I highly recommend upgrading to latest 6.8 version or later.
