### ISSUE TITLE
PutIndexTemplate request exception using high level rest client

### ISSUE THREAD

**Issue by TalRefaeli** [elastic/elasticsearch#45534]
Elasticsearch version: 7.3.0
JVM version (Both client and ES): openjdk 1.8.0.201
OS: Windows 10

Exception during put index template request using high level rest client.

We are upgrading elasticsearch from 5.6.12 to 7.3.0.
We store our index templates inside json files, and then use the client source() method to put all the json body inside the high level client request.
After the upgrade we adjusted the json template 
Running the following code will not work even though it was taken from elasticsearch official [documentation](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-put-template.html):
```
RestHighLevelClient = client = new RestHighLevelClient(RestClient.builder(new HttpHost("localhost", 9400, "http")));
PutIndexTemplateRequest request = new PutIndexTemplateRequest("my-template");
request.source("{\n" +
		"  \"index_patterns\": [\n" +
		"    \"log-*\",\n" +
		"    \"pattern-1\"\n" +
		"  ],\n" +
		"  \"order\": 1,\n" +
		"  \"settings\": {\n" +
		"    \"number_of_shards\": 1\n" +
		"  },\n" +
		"  \"mappings\": {\n" +
		"    \"properties\": {\n" +
		"      \"message\": {\n" +
		"        \"type\": \"text\"\n" +
		"      }\n" +
		"    }\n" +
		"  },\n" +
		"  \"aliases\": {\n" +
		"    \"alias-1\": {},\n" +
		"    \"{index}-alias\": {}\n" +
		"  }\n" +
		"}", XContentType.JSON);
client.indices().putTemplate(request, RequestOptions.DEFAULT);
```

Expected: index template created.
Actual: Exception is thrown.

Exception:
```
ElasticsearchStatusException[Elasticsearch exception [type=mapper_parsing_exception, reason=Failed to parse mapping [properties]: Root mapping definition has unsupported parameters:  [message : {type=text}]]]; nested: ElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=Root mapping definition has unsupported parameters:  [message : {type=text}]]];
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177)
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1727)
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1704)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1467)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1424)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1394)
	at org.elasticsearch.client.IndicesClient.putTemplate(IndicesClient.java:1049)

...

Suppressed: org.elasticsearch.client.ResponseException: method [PUT], host [http://localhost:9400], URI [/_template/my-template?master_timeout=30s&include_type_name=true], status line [HTTP/1.1 400 Bad Request]
Warnings: [[types removal] Specifying include_type_name in put index template requests is deprecated. The parameter will be removed in the next major version.]
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [message : {type=text}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [properties]: Root mapping definition has unsupported parameters:  [message : {type=text}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [message : {type=text}]"}},"status":400}
		at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:253)
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:231)
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:205)
		at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1454)
		... 32 more
Caused by: ElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=Root mapping definition has unsupported parameters:  [message : {type=text}]]]
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:491)
	at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:402)
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:432)
	at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:598)
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:169)
	... 35 more
```

To reproduce:
1. Run elasticsearch server.
2. Run the java code above.

The problem seem to be related to the put-template-request object of high level rest client which incorrectly manipulates the origin json provided by source() method.

**Comment by TalRefaeli** [comment]
We found that there's no issue when using org.elasticsearch.client.indices.PutIndexTemplateRequest instead of org.elasticsearch.action.admin.indices.template.put.PutIndexTemplateRequest so it's a solution for us.

Decide if you wish to close this or fix org.elasticsearch.action.admin.indices.template.put.PutIndexTemplateRequest usage.

Thanks,
Tal

**Comment by markharwood** [comment]
Thanks for this report, Tal.
Looks like you found the right "client" class in the end and it's unfortunate that you were able to pick the wrong one.
A long-term goal for us is to slim-down the dependencies the high-level rest client has on classes used in the server. This is a large and complex piece of work and will take time so is being done in stages. Until we fully break these dependencies, situations like yours are possible but we hope to eliminate that in future.

Closing, as  a "known issue".
