### ISSUE TITLE
[CI] SSLErrorMessageTests tests failing on Windows due to path differences

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#45598]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-windows-compatibility/os=windows-2019/70/console is an example of 5 tests that assert on the text of error messages failing because Windows paths have forward slashes instead of backslashes and begin with `C:`.  The failing tests are:

```
org.elasticsearch.xpack.ssl.SSLErrorMessageTests testMessageForCertificateAuthoritiesOutsideConfigDir
org.elasticsearch.xpack.ssl.SSLErrorMessageTests testMessageForKeyStoreOutsideConfigDir
org.elasticsearch.xpack.ssl.SSLErrorMessageTests testMessageForPemCertificateOutsideConfigDir
org.elasticsearch.xpack.ssl.SSLErrorMessageTests testMessageForPemKeyOutsideConfigDir
org.elasticsearch.xpack.ssl.SSLErrorMessageTests testMessageForTrustStoreOutsideConfigDir
```

The error messages are:

```
org.elasticsearch.xpack.ssl.SSLErrorMessageTests > testMessageForKeyStoreOutsideConfigDir FAILED
    java.lang.AssertionError: 
    Expected: a throwable with message of "failed to initialize SSL KeyManager - access to read keystore file [/this/path/is/outside/the/config/directory/file.error] is blocked; SSL resources should be placed in the [C:\\Users\\jenkins\\workspace\\elastic+elasticsearch+7.x+multijob-windows-compatibility\\os\\windows-2012-r2\\x-pack\\plugin\\security\\build\\testrun\\test\\temp\\org.elasticsearch.xpack.ssl.SSLErrorMessageTests_9140FE898925497D-001\\tempDir-003\\config] directory"
         but: was <ElasticsearchException[failed to initialize SSL KeyManager - access to read keystore file [C:\this\path\is\outside\the\config\directory\file.error] is blocked; SSL resources should be placed in the [C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\x-pack\plugin\security\build\testrun\test\temp\org.elasticsearch.xpack.ssl.SSLErrorMessageTests_9140FE898925497D-001\tempDir-003\config] directory]; nested: AccessControlException[access denied ("java.io.FilePermission" "C:\this\path\is\outside\the\config\directory\file.error" "read")];> at org.elasticsearch.xpack.core.ssl.KeyConfig.blockedKeyConfigFile(KeyConfig.java:93)
        at __randomizedtesting.SeedInfo.seed([9140FE898925497D:D767287DF541D1B9]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ssl.SSLErrorMessageTests.checkBlockedResource(SSLErrorMessageTests.java:227)
        at org.elasticsearch.xpack.ssl.SSLErrorMessageTests.checkBlockedKeyManagerResource(SSLErrorMessageTests.java:156)
        at org.elasticsearch.xpack.ssl.SSLErrorMessageTests.testMessageForKeyStoreOutsideConfigDir(SSLErrorMessageTests.java:110)
REPRODUCE WITH: gradlew :x-pack:plugin:security:test --tests "org.elasticsearch.xpack.ssl.SSLErrorMessageTests.testMessageForKeyStoreOutsideConfigDir" -Dtests.seed=9140FE898925497D -Dtests.security.manager=true -Dtests.locale=ar-SD -Dtests.timezone=SystemV/AST4 -Dcompiler.java=12 -Druntime.java=8

org.elasticsearch.xpack.ssl.SSLErrorMessageTests > testMessageForTrustStoreOutsideConfigDir FAILED
    java.lang.AssertionError: 
    Expected: a throwable with message of "failed to initialize SSL TrustManager - access to read truststore file [/this/path/is/outside/the/config/directory/file.error] is blocked; SSL resources should be placed in the [C:\\Users\\jenkins\\workspace\\elastic+elasticsearch+7.x+multijob-windows-compatibility\\os\\windows-2012-r2\\x-pack\\plugin\\security\\build\\testrun\\test\\temp\\org.elasticsearch.xpack.ssl.SSLErrorMessageTests_9140FE898925497D-001\\tempDir-005\\config] directory"
         but: was <ElasticsearchException[failed to initialize SSL TrustManager - access to read truststore file [C:\this\path\is\outside\the\config\directory\file.error] is blocked; SSL resources should be placed in the [C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\x-pack\plugin\security\build\testrun\test\temp\org.elasticsearch.xpack.ssl.SSLErrorMessageTests_9140FE898925497D-001\tempDir-005\config] directory]; nested: AccessControlException[access denied ("java.io.FilePermission" "C:\this\path\is\outside\the\config\directory\file.error" "read")];> at org.elasticsearch.xpack.core.ssl.TrustConfig.blockedTrustConfigFile(TrustConfig.java:135)
        at __randomizedtesting.SeedInfo.seed([9140FE898925497D:EB1B31CF01E3B961]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ssl.SSLErrorMessageTests.checkBlockedResource(SSLErrorMessageTests.java:227)
        at org.elasticsearch.xpack.ssl.SSLErrorMessageTests.checkBlockedTrustManagerResource(SSLErrorMessageTests.java:161)
        at org.elasticsearch.xpack.ssl.SSLErrorMessageTests.testMessageForTrustStoreOutsideConfigDir(SSLErrorMessageTests.java:122)
REPRODUCE WITH: gradlew :x-pack:plugin:security:test --tests "org.elasticsearch.xpack.ssl.SSLErrorMessageTests.testMessageForTrustStoreOutsideConfigDir" -Dtests.seed=9140FE898925497D -Dtests.security.manager=true -Dtests.locale=ar-SD -Dtests.timezone=SystemV/AST4 -Dcompiler.java=12 -Druntime.java=8

org.elasticsearch.xpack.ssl.SSLErrorMessageTests > testMessageForCertificateAuthoritiesOutsideConfigDir FAILED
    java.lang.AssertionError: 
    Expected: a throwable with message of "failed to initialize SSL TrustManager - access to read certificate_authorities file [/this/path/is/outside/the/config/directory/file.error] is blocked; SSL resources should be placed in the [C:\\Users\\jenkins\\workspace\\elastic+elasticsearch+7.x+multijob-windows-compatibility\\os\\windows-2012-r2\\x-pack\\plugin\\security\\build\\testrun\\test\\temp\\org.elasticsearch.xpack.ssl.SSLErrorMessageTests_9140FE898925497D-001\\tempDir-008\\config] directory"
         but: was <ElasticsearchException[failed to initialize SSL TrustManager - access to read certificate_authorities file [C:\this\path\is\outside\the\config\directory\file.error] is blocked; SSL resources should be placed in the [C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\x-pack\plugin\security\build\testrun\test\temp\org.elasticsearch.xpack.ssl.SSLErrorMessageTests_9140FE898925497D-001\tempDir-008\config] directory]; nested: AccessControlException[access denied ("java.io.FilePermission" "C:\this\path\is\outside\the\config\directory\file.error" "read")];> at org.elasticsearch.xpack.core.ssl.TrustConfig.blockedTrustConfigFile(TrustConfig.java:135)
        at __randomizedtesting.SeedInfo.seed([9140FE898925497D:ED4E906684B3E39E]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ssl.SSLErrorMessageTests.checkBlockedResource(SSLErrorMessageTests.java:227)
        at org.elasticsearch.xpack.ssl.SSLErrorMessageTests.checkBlockedTrustManagerResource(SSLErrorMessageTests.java:161)
        at org.elasticsearch.xpack.ssl.SSLErrorMessageTests.testMessageForCertificateAuthoritiesOutsideConfigDir(SSLErrorMessageTests.java:126)
REPRODUCE WITH: gradlew :x-pack:plugin:security:test --tests "org.elasticsearch.xpack.ssl.SSLErrorMessageTests.testMessageForCertificateAuthoritiesOutsideConfigDir" -Dtests.seed=9140FE898925497D -Dtests.security.manager=true -Dtests.locale=ar-SD -Dtests.timezone=SystemV/AST4 -Dcompiler.java=12 -Druntime.java=8

org.elasticsearch.xpack.ssl.SSLErrorMessageTests > testMessageForPemCertificateOutsideConfigDir FAILED
    java.lang.AssertionError: 
    Expected: a throwable with message of "failed to initialize SSL KeyManager - access to read certificate file [/this/path/is/outside/the/config/directory/file.error] is blocked; SSL resources should be placed in the [C:\\Users\\jenkins\\workspace\\elastic+elasticsearch+7.x+multijob-windows-compatibility\\os\\windows-2012-r2\\x-pack\\plugin\\security\\build\\testrun\\test\\temp\\org.elasticsearch.xpack.ssl.SSLErrorMessageTests_9140FE898925497D-001\\tempDir-009\\config] directory"
         but: was <ElasticsearchException[failed to initialize SSL KeyManager - access to read certificate file [C:\this\path\is\outside\the\config\directory\file.error] is blocked; SSL resources should be placed in the [C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\x-pack\plugin\security\build\testrun\test\temp\org.elasticsearch.xpack.ssl.SSLErrorMessageTests_9140FE898925497D-001\tempDir-009\config] directory]; nested: AccessControlException[access denied ("java.io.FilePermission" "C:\this\path\is\outside\the\config\directory\file.error" "read")];> at org.elasticsearch.xpack.core.ssl.KeyConfig.blockedKeyConfigFile(KeyConfig.java:93)
        at __randomizedtesting.SeedInfo.seed([9140FE898925497D:63127425517741B9]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ssl.SSLErrorMessageTests.checkBlockedResource(SSLErrorMessageTests.java:227)
        at org.elasticsearch.xpack.ssl.SSLErrorMessageTests.checkBlockedKeyManagerResource(SSLErrorMessageTests.java:156)
        at org.elasticsearch.xpack.ssl.SSLErrorMessageTests.testMessageForPemCertificateOutsideConfigDir(SSLErrorMessageTests.java:114)
REPRODUCE WITH: gradlew :x-pack:plugin:security:test --tests "org.elasticsearch.xpack.ssl.SSLErrorMessageTests.testMessageForPemCertificateOutsideConfigDir" -Dtests.seed=9140FE898925497D -Dtests.security.manager=true -Dtests.locale=ar-SD -Dtests.timezone=SystemV/AST4 -Dcompiler.java=12 -Druntime.java=8

org.elasticsearch.xpack.ssl.SSLErrorMessageTests > testMessageForPemKeyOutsideConfigDir FAILED
    java.lang.AssertionError: 
    Expected: a throwable with message of "failed to initialize SSL KeyManager - access to read key file [/this/path/is/outside/the/config/directory/file.error] is blocked; SSL resources should be placed in the [C:\\Users\\jenkins\\workspace\\elastic+elasticsearch+7.x+multijob-windows-compatibility\\os\\windows-2012-r2\\x-pack\\plugin\\security\\build\\testrun\\test\\temp\\org.elasticsearch.xpack.ssl.SSLErrorMessageTests_9140FE898925497D-001\\tempDir-010\\config] directory"
         but: was <ElasticsearchException[failed to initialize SSL KeyManager - access to read key file [C:\this\path\is\outside\the\config\directory\file.error] is blocked; SSL resources should be placed in the [C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\x-pack\plugin\security\build\testrun\test\temp\org.elasticsearch.xpack.ssl.SSLErrorMessageTests_9140FE898925497D-001\tempDir-010\config] directory]; nested: AccessControlException[access denied ("java.io.FilePermission" "C:\this\path\is\outside\the\config\directory\file.error" "read")];> at org.elasticsearch.xpack.core.ssl.KeyConfig.blockedKeyConfigFile(KeyConfig.java:93)
        at __randomizedtesting.SeedInfo.seed([9140FE898925497D:E243FC1705A5B982]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ssl.SSLErrorMessageTests.checkBlockedResource(SSLErrorMessageTests.java:227)
        at org.elasticsearch.xpack.ssl.SSLErrorMessageTests.checkBlockedKeyManagerResource(SSLErrorMessageTests.java:156)
        at org.elasticsearch.xpack.ssl.SSLErrorMessageTests.testMessageForPemKeyOutsideConfigDir(SSLErrorMessageTests.java:118)
REPRODUCE WITH: gradlew :x-pack:plugin:security:test --tests "org.elasticsearch.xpack.ssl.SSLErrorMessageTests.testMessageForPemKeyOutsideConfigDir" -Dtests.seed=9140FE898925497D -Dtests.security.manager=true -Dtests.locale=ar-SD -Dtests.timezone=SystemV/AST4 -Dcompiler.java=12 -Druntime.java=8
```

In each case `/this/path/is/outside/the/config/directory/file.error` is instead showing up as `C:\this\path\is\outside\the\config\directory\file.error`.

**Comment by droberts195** [comment]
The same problem is occurring on master branch Windows builds, for example https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/os=windows-2012-r2/78/console

I will mute on master and 7.x via #45602
