### ISSUE TITLE
Tests from DataFrameGetAndGetStatsIT fail 

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#45610]
## Example build failure
https://gradle-enterprise.elastic.co/s/gmrc7h7t4cu7w/tests/failed

## Reproduction line 
does not reproduce locally
```
REPRODUCE WITH: ./gradlew :x-pack:plugin:data-frame:qa:single-node-tests:integTestRunner --tests "org.elasticsearch.xpack.dataframe.integration.DataFrameGetAndGetStatsIT.testGetAndGetStats" -Dtests.seed=48708D28F42AAB77 -Dtests.security.manager=true -Dtests.locale=bez -Dtests.timezone=Etc/GMT+12 -Dcompiler.java=12 -Druntime.java=11
```

## Example relevant log:
```
org.elasticsearch.client.ResponseException: 
method [POST], host [http://[::1]:33841], URI [/_data_frame/transforms/pivot_continuous/_stop?wait_for_completion=true&force=false], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"illegal_state_exception","reason":"Timed out when waiting for persistent tasks after 30s"}],"type":"illegal_state_exception","reason":"Timed out when waiting for persistent tasks after 30s"},"status":500}
Close stacktrace
at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:253)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:231)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:205)
at org.elasticsearch.xpack.dataframe.integration.DataFrameRestTestCase.stopDataFrameTransform(DataFrameRestTestCase.java:247)
at org.elasticsearch.xpack.dataframe.integration.DataFrameGetAndGetStatsIT.testGetAndGetStats(DataFrameGetAndGetStatsIT.java:151)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:566)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at java.lang.Thread.run(Thread.java:834)
[2019-08-15T01:27:42,625][INFO ][o.e.x.d.i.DataFrameGetAndGetStatsIT] [testGetAndGetStats] before test
[2019-08-15T01:27:42,639][INFO ][o.e.x.d.i.DataFrameGetAndGetStatsIT] [testGetAndGetStats] initializing REST clients against [http://[::1]:33841, http://127.0.0.1:44149]
[2019-08-15T01:28:43,904][INFO ][o.e.x.d.i.DataFrameGetAndGetStatsIT] [testGetAndGetStats] There are still tasks running after this test that might break subsequent tests [data_frame/transforms[c]].
[2019-08-15T01:28:43,905][INFO ][o.e.x.d.i.DataFrameGetAndGetStatsIT] [testGetAndGetStats] after test
```

## Frequency
Frequent in the last few days

**Comment by benwtrent** [comment]
@hendrikmuhs these timeouts that occur around `stop` seem similar to the ones that occurred when I was testing failure state race conditions. Though, I was able to periodically re-create the failure state race conditions. That race condition in particular had to do with another trigger occurring while the previous one was still in `doSaveState` and attempting to wrap up.

**Comment by benwtrent** [comment]
I was able to reproduce it locally. Here are some logs (i turned on trace for async indexer and the task). Digging into it myself for a bit, but this should help if you start looking at this again before I do.
```
[2019-08-29T16:30:06,465][TRACE][o.e.x.d.t.DataFrameTransformPersistentTasksExecutor] [integTest-0] [pivot_continuous] No stats found(new transform), starting the task
[2019-08-29T16:30:06,467][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] start called with force [false] and state [{"task_state":"stopped","indexer_state":"stopped","checkpoint":0}].
[2019-08-29T16:30:06,467][INFO ][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] updating state for data frame transform to [{"task_state":"started","indexer_state":"stopped","checkpoint":0}].
[2019-08-29T16:30:06,529][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] successfully updated state for data frame transform to [{"task_state":"started","indexer_state":"stopped","checkpoint":0}].
[2019-08-29T16:30:06,533][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [data_frame/transforms/schedule_pivot_continuous] data frame indexer schedule has triggered, state: [STARTED].
[2019-08-29T16:30:06,534][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] Trigger initial run.
[2019-08-29T16:30:06,535][DEBUG][o.e.x.c.i.AsyncTwoPhaseIndexer] [integTest-0] Schedule was triggered for job [pivot_continuous], state: [STARTED]
[2019-08-29T16:30:06,536][DEBUG][o.e.x.c.i.AsyncTwoPhaseIndexer] [integTest-0] Beginning to index [pivot_continuous], state: [STARTED]
[2019-08-29T16:30:06,540][INFO ][o.e.x.d.t.DataFrameTransformPersistentTasksExecutor] [integTest-0] Successfully completed and scheduled task in node operation
[2019-08-29T16:30:06,547][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] successfully refreshed data frame transform config from index.
[2019-08-29T16:30:06,688][TRACE][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] reset the progress from [null] to [{
  "docs_remaining" : 1000,
  "total_docs" : 1000,
  "percent_complete" : 0.0,
  "docs_indexed" : 0,
  "docs_processed" : 0
}].
[2019-08-29T16:30:06,690][TRACE][o.e.x.d.t.DataFrameIndexer] [integTest-0] running full run query: {"size":0,"query":{"bool":{"filter":[{"match_all":{"boost":1.0}},{"range":{"timestamp":{"from":null,"to":1567113306557,"include_lower":true,"include_upper":false,"format":"epoch_millis","boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}},"aggregations":{"_data_frame":{"composite":{"size":500,"sources":[{"reviewer":{"terms":{"field":"user_id","missing_bucket":false,"order":"asc"}}}]},"aggregations":{"avg_rating":{"avg":{"field":"stars"}}}}}}
[2019-08-29T16:30:06,767][TRACE][o.e.x.d.t.DataFrameIndexer] [integTest-0] running full run query: {"size":0,"query":{"bool":{"filter":[{"match_all":{"boost":1.0}},{"range":{"timestamp":{"from":null,"to":1567113306557,"include_lower":true,"include_upper":false,"format":"epoch_millis","boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}},"aggregations":{"_data_frame":{"composite":{"size":500,"sources":[{"reviewer":{"terms":{"field":"user_id","missing_bucket":false,"order":"asc"}}}],"after":{"reviewer":"user_9"}},"aggregations":{"avg_rating":{"avg":{"field":"stars"}}}}}}
[2019-08-29T16:30:06,783][DEBUG][o.e.x.c.i.AsyncTwoPhaseIndexer] [integTest-0] Finished indexing for job [pivot_continuous], saving state and shutting down.
[2019-08-29T16:30:06,788][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] finished indexing for data frame transform checkpoint [0].
[2019-08-29T16:30:06,790][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] updating persistent state of transform to [{"task_state":"started","indexer_state":"started","checkpoint":1,"progress":{"docs_remaining":0,"total_docs":1000,"percent_complete":100.0,"docs_indexed":27,"docs_processed":1000}}].
[2019-08-29T16:30:06,965][TRACE][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] deleted old transform stats and state document
[2019-08-29T16:30:07,161][TRACE][o.e.x.d.p.DataFrameTransformsConfigManager] [integTest-0] found no checkpoint for transform [pivot_2], returning empty checkpoint
[2019-08-29T16:30:07,161][TRACE][o.e.x.d.p.DataFrameTransformsConfigManager] [integTest-0] found no checkpoint for transform [pivot_1], returning empty checkpoint
[2019-08-29T16:30:07,204][TRACE][o.e.x.d.p.DataFrameTransformsConfigManager] [integTest-0] found no checkpoint for transform [pivot_2], returning empty checkpoint
[2019-08-29T16:30:07,204][TRACE][o.e.x.d.p.DataFrameTransformsConfigManager] [integTest-0] found no checkpoint for transform [pivot_1], returning empty checkpoint
[2019-08-29T16:30:07,246][TRACE][o.e.x.d.p.DataFrameTransformsConfigManager] [integTest-0] found no checkpoint for transform [pivot_2], returning empty checkpoint
[2019-08-29T16:30:07,246][TRACE][o.e.x.d.p.DataFrameTransformsConfigManager] [integTest-0] found no checkpoint for transform [pivot_1], returning empty checkpoint
[2019-08-29T16:30:07,303][TRACE][o.e.x.d.p.DataFrameTransformsConfigManager] [integTest-0] found no checkpoint for transform [pivot_1], returning empty checkpoint
[2019-08-29T16:30:07,306][TRACE][o.e.x.d.p.DataFrameTransformsConfigManager] [integTest-0] found no checkpoint for transform [pivot_2], returning empty checkpoint
[2019-08-29T16:30:07,397][TRACE][o.e.x.d.p.DataFrameTransformsConfigManager] [integTest-0] found no checkpoint for transform [pivot_1], returning empty checkpoint
[2019-08-29T16:30:07,398][TRACE][o.e.x.d.p.DataFrameTransformsConfigManager] [integTest-0] found no checkpoint for transform [pivot_2], returning empty checkpoint
[2019-08-29T16:30:07,444][TRACE][o.e.x.d.p.DataFrameTransformsConfigManager] [integTest-0] found no checkpoint for transform [pivot_1], returning empty checkpoint
[2019-08-29T16:30:07,542][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [data_frame/transforms/schedule_pivot_continuous] data frame indexer schedule has triggered, state: [STARTED].
[2019-08-29T16:30:07,543][DEBUG][o.e.x.c.i.AsyncTwoPhaseIndexer] [integTest-0] Schedule was triggered for job [pivot_continuous], state: [STARTED]
[2019-08-29T16:30:07,544][DEBUG][o.e.x.c.i.AsyncTwoPhaseIndexer] [integTest-0] Beginning to index [pivot_continuous], state: [STARTED]
[2019-08-29T16:30:07,549][TRACE][o.e.x.d.c.TimeBasedCheckpointProvider] [integTest-0] query for changes based on time: {"size":0,"query":{"bool":{"filter":[{"match_all":{"boost":1.0}},{"range":{"timestamp":{"from":1567113306557,"to":1567113307549,"include_lower":true,"include_upper":false,"format":"epoch_millis","boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}},"track_total_hits":1}
[2019-08-29T16:30:07,557][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] stop called with force [false] and state [{"task_state":"started","indexer_state":"indexing","checkpoint":1,"progress":{"docs_remaining":0,"total_docs":1000,"percent_complete":100.0,"docs_indexed":27,"docs_processed":1000}}]
[2019-08-29T16:30:07,559][TRACE][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] change detected [false].
[2019-08-29T16:30:07,561][INFO ][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] data frame transform has stopped.
[2019-08-29T16:30:08,547][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:09,553][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:10,558][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:11,562][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:12,567][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:13,569][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:14,576][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:15,580][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:16,584][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:17,585][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:18,588][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:19,593][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:20,598][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:21,599][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:22,604][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:23,607][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:24,614][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:25,618][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:26,624][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:27,629][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:28,633][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:29,634][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:30,638][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:31,643][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:32,649][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:33,654][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:34,660][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:35,664][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:36,666][DEBUG][o.e.x.d.t.DataFrameTransformTask] [integTest-0] [pivot_continuous] indexer for transform has state [STOPPED]. Ignoring trigger.
[2019-08-29T16:30:37,562][WARN ][r.suppressed             ] [integTest-0] path: /_data_frame/transforms/pivot_continuous/_stop, params: {force=false, id=pivot_continuous, wait_for_completion=true}
java.lang.IllegalStateException: Timed out when waiting for persistent tasks after 30s
	at org.elasticsearch.persistent.PersistentTasksService$2.onTimeout(PersistentTasksService.java:209) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:325) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:252) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:589) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:699) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by benwtrent** [comment]
I see the cause of the issue. 

Do avoid thread lock scenarios (which periodically occurred and caused havoc), we wait to determine if there are changes until `onStart` is called. This method is called when the indexer is set to `INDEXING`, and if no changes are found it calls back to https://github.com/benwtrent/elasticsearch/blob/27fab09ba242b5c0a0c24163f538c95be8ecfbd1/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexer.java#L161

Normally this just quickly toggles the indexer between `INDEXING` and `STARTED`.

But, between that check and the call back to the `AsyncTwoPhaseIndexer`, `stop` was called. Since the indexer was set to `INDEXING` at the time, it was transitioned to `STOPPING` and `doSaveState` was never called with the indexer set to `STOPPED`. 

To fix this we need call `doSaveState` if `AsyncTwoPhaseIndexer` transitions between `STOPPING -> STOPPED` when we don't find any changes.

If we DID discover changes, its ok as eventually `checkState` is called and transitions it to `STOPPED` with a call against `doSaveState`.
