### ISSUE TITLE
ShapeQueryTests#testFieldAlias returns no hits, fails assertion 

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#45628]
Encountered this on a PR build.  Doesn't fail 100% of the time, but seems to fail once every 10-20 iterations.  Fails on this:

```
assertTrue(response.getHits().getTotalHits().value > 0);
```
So I'm assuming the cluster isn't ready yet or something (shards still allocating, refresh not performed, etc).  

Sidebar, we should probably convert this to an ESRestTestCase or a yaml test instead of ESSingleNodeTestCse

```
./gradlew :x-pack:plugin:spatial:test --tests "org.elasticsearch.xpack.spatial.search.ShapeQueryTests.testFieldAlias" -Dtests.seed=DDCE36BAC5FE6F5A -Dtests.security.manager=true -Dtests.locale=es-BR -Dtests.timezone=PRT -Dcompiler.java=12 -Druntime.java=11
```

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([DDCE36BAC5FE6F5A:E788A7DFE749FB6E]:0)
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.elasticsearch.xpack.spatial.search.ShapeQueryTests.testFieldAlias(ShapeQueryTests.java:234)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
```

**Comment by iverase** [comment]
I think this failure is related to #37356 where the index polygon and the query polygon do not intersect due to the encoding.

**Comment by davidkyle** [comment]
This also failed on 7.x with the same stack trace

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=fedora-29&&immutable/214/console
https://gradle-enterprise.elastic.co/s/jwtgvpdhqytnc

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([2DDE730C0665B688:1798E26924D222BC]:0)
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.elasticsearch.xpack.spatial.search.ShapeQueryTests.testFieldAlias(ShapeQueryTests.java:234)
```

I backported the muting in 6b391cd0d59e7fd828f7550893fb36820437c57d
