### ISSUE TITLE
CcrRollingUpgradeIT.testBiDirectionalIndexFollowing failure on CI due to failed assertion

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#45641]
This test has been failing a fair bit, but with this particular error on 7.x and in master 18 times in the past 60 days.

[Build scan](https://gradle-enterprise.elastic.co/s/lbs5gholrxjy2/tests/hoj6xeare4bli-u623xfbx7g6qc?openStackTraces=WzBd)
[Jenkins](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/1152/)

Reproduce line:
```
/gradlew :x-pack:qa:rolling-upgrade-multi-cluster:v6.8.3#leader#upgradedClusterTestRunner --tests "org.elasticsearch.upgrades.CcrRollingUpgradeIT.testBiDirectionalIndexFollowing" -Dtests.seed=D67FBE070B1760DA -Dtests.security.manager=true -Dtests.locale=sr-CS -Dtests.timezone=Asia/Qostanay -Dcompiler.java=12 -Druntime.java=8
```

Stack trace:
```
java.lang.AssertionError
: 

Expected: <896>
     but: was <768>
Close stacktrace
at __randomizedtesting.SeedInfo.seed([D67FBE070B1760DA:EBF01378324072C]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.upgrades.CcrRollingUpgradeIT.verifyTotalHitCount(CcrRollingUpgradeIT.java:365)
at org.elasticsearch.upgrades.CcrRollingUpgradeIT.lambda$assertTotalHitCount$13(CcrRollingUpgradeIT.java:355)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:895)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:869)
at org.elasticsearch.upgrades.CcrRollingUpgradeIT.assertTotalHitCount(CcrRollingUpgradeIT.java:355)
at org.elasticsearch.upgrades.CcrRollingUpgradeIT.testBiDirectionalIndexFollowing(CcrRollingUpgradeIT.java:283)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by henningandersen** [comment]
This seems to have been fixed by a recent change to the build system. Dependent tests would sometimes not run so ccr might never have been configure. Unmuted tests and will close this issue.
