### ISSUE TITLE
SQL: count()-ing without a FROM clause raises exception

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#45913]
**Elasticsearch version** (`bin/elasticsearch --version`): 8.0.0-SNAPSHOT
**Description of the problem including expected versus actual behavior**:
`Encountered a bug; LocalExec[] is a LocalExec but is not empty`
**Steps to reproduce**:
`SELECT count(*) WHERE true=true`
**Provide logs (if relevant)**:

```
[2019-08-23T17:26:02,270][WARN ][r.suppressed             ] [node-0] path: /_sql, params: {pretty=}
org.elasticsearch.xpack.sql.SqlIllegalArgumentException: Encountered a bug; LocalExec[] is a LocalExec but is not empty
        at org.elasticsearch.xpack.sql.planner.QueryFolder$PropagateEmptyLocal.rule(QueryFolder.java:563) ~[?:?]
        at org.elasticsearch.xpack.sql.tree.Node.lambda$transformUp$11(Node.java:196) ~[?:?]
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:190) ~[?:?]
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:196) ~[?:?]
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:588) ~[?:?]
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:584) ~[?:?]
        at org.elasticsearch.xpack.sql.rule.RuleExecutor$Transformation.<init>(RuleExecutor.java:82) ~[?:?]
        at org.elasticsearch.xpack.sql.rule.RuleExecutor.executeWithInfo(RuleExecutor.java:158) ~[?:?]
        at org.elasticsearch.xpack.sql.rule.RuleExecutor.execute(RuleExecutor.java:130) ~[?:?]
        at org.elasticsearch.xpack.sql.planner.QueryFolder.fold(QueryFolder.java:82) ~[?:?]
        at org.elasticsearch.xpack.sql.planner.Planner.foldPlan(Planner.java:38) ~[?:?]
        at org.elasticsearch.xpack.sql.planner.Planner.plan(Planner.java:28) ~[?:?]
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$physicalPlan$4(SqlSession.java:159) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$optimizedPlan$3(SqlSession.java:155) [x-pack-sql-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.session.SqlSession.preAnalyze(SqlSession.java:147) [x-pack-sql-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.session.SqlSession.analyzedPlan(SqlSession.java:107) [x-pack-sql-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.session.SqlSession.optimizedPlan(SqlSession.java:155) [x-pack-sql-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.session.SqlSession.physicalPlan(SqlSession.java:159) [x-pack-sql-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.session.SqlSession.sqlExecutable(SqlSession.java:168) [x-pack-sql-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.session.SqlSession.sql(SqlSession.java:163) [x-pack-sql-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.execution.PlanExecutor.sql(PlanExecutor.java:98) [x-pack-sql-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.operation(TransportSqlQueryAction.java:78) [x-pack-sql-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.doExecute(TransportSqlQueryAction.java:63) [x-pack-sql-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.doExecute(TransportSqlQueryAction.java:41) [x-pack-sql-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:153) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[...]
```

**Comment by matriv** [comment]
This doesn't occur anymore, behavior has been fixed.
