### ISSUE TITLE
[CI] org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT Failures from Cluster not Forming

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#46013]
In https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/502/ all tests in 
`org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT` failed as a result of the cluster not forming.

Reproduce line (though not really applicable since all the tests in the suite failed):

```
./gradlew :x-pack:plugin:ccr:internalClusterTest --tests "org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.testRetentionLeaseAdvancesWhileFollowing" -Dtests.seed=A1FDBF8207D8F4B8 -Dtests.security.manager=true -Dtests.locale=sbp -Dtests.timezone=JST -Dcompiler.java=12 -Druntime.java=1
```

```
org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT > testRetentionLeaseAdvancesWhileFollowing FAILED
    ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/2/no master];]

    MasterNotDiscoveredException[null]
```

[Build Scan](https://gradle-enterprise.elastic.co/s/d2fnznmtt2ewo/console-log)

**Comment by ywelsch** [comment]
The relevant exception here is:

```
WARNING: Uncaught exception in thread: Thread[elasticsearch[leader0][transport_worker][T#2],5,TGRP-CcrRetentionLeaseIT]
  2> java.lang.AssertionError: retention lease renewal for [follower_cluster/follower/en7SNpoTT12EfjfFahBWSQ-following-leader_cluster/leader/OPV3TxZpSWqrHuI420coIQ] from [ccr] renewed a lower retaining sequence number [37] than the current lease retaining sequence number [38]
  2> 	at __randomizedtesting.SeedInfo.seed([A1FDBF8207D8F4B8]:0)
  2> 	at org.elasticsearch.index.seqno.ReplicationTracker.renewRetentionLease(ReplicationTracker.java:401)
  2> 	at org.elasticsearch.index.shard.IndexShard.renewRetentionLease(IndexShard.java:2148)
  2> 	at org.elasticsearch.index.seqno.RetentionLeaseActions$Renew$TransportAction.doRetentionLeaseAction(RetentionLeaseActions.java:206)
  2> 	at org.elasticsearch.index.seqno.RetentionLeaseActions$Renew$TransportAction.doRetentionLeaseAction(RetentionLeaseActions.java:182)
  2> 	at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction.lambda$asyncShardOperation$0(RetentionLeaseActions.java:100)
  2> 	at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:112)
  2> 	at org.elasticsearch.index.shard.IndexShard.lambda$wrapPrimaryOperationPermitListener$21(IndexShard.java:2753)
  2> 	at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:112)
  2> 	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:285)
  2> 	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:237)
  2> 	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2727)
  2> 	at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction.asyncShardOperation(RetentionLeaseActions.java:97)
  2> 	at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction.asyncShardOperation(RetentionLeaseActions.java:59)
  2> 	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:289)
  2> 	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:282)
  2> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63)
  2> 	at org.elasticsearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:262)
  2> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  2> 	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:196)
  2> 	at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:183)
  2> 	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:117)
  2> 	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:101)
  2> 	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:663)
  2> 	at org.elasticsearch.transport.TcpTransport.consumeNetworkReads(TcpTransport.java:687)
  2> 	at org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:279)
  2> 	at org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:228)
  2> 	at org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:40)
  2> 	at org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:139)
  2> 	at org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:151)
  2> 	at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:420)
  2> 	at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:246)
  2> 	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:174)
  2> 	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:131)
  2> 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by dnhatn** [comment]
We renew the CCR retention lease at [a fixed interval](https://github.com/elastic/elasticsearch/blob/a5c60fb59a93d25d3534abd63a03057e514f186f/x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowTasksExecutor.java#L448), therefore it's possible to have more than one in-flight renewal requests at the same time. If requests arrive out of order, then the assertion is violated. 

@original-brownbear I can take care of this issue if you don't mind.

**Comment by original-brownbear** [comment]
@dnhatn go for it :)
