### ISSUE TITLE
[CI] :qa:full-cluster-restart:v7.3.2#upgradedClusterTest Failed on Windows

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#46014]
The test goal failed with this error:

```

* Where:
--
Build file 'C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build.gradle' line: 63
 
* What went wrong:
Execution failed for task ':qa:full-cluster-restart:v7.3.2#upgradedClusterTest'.
> Unable to delete directory 'C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro'
Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\elasticsearch-7.3.2-SNAPSHOT.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\elasticsearch-cli-7.3.2-SNAPSHOT.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\elasticsearch-core-7.3.2-SNAPSHOT.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\elasticsearch-geo-7.3.2-SNAPSHOT.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\elasticsearch-launchers-7.3.2-SNAPSHOT.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\elasticsearch-plugin-classloader-7.3.2-SNAPSHOT.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\elasticsearch-secure-sm-7.3.2-SNAPSHOT.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\elasticsearch-x-content-7.3.2-SNAPSHOT.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\HdrHistogram-2.1.9.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\hppc-0.8.1.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\jackson-core-2.8.11.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\jackson-dataformat-cbor-2.8.11.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\jackson-dataformat-smile-2.8.11.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\jackson-dataformat-yaml-2.8.11.jar

```

Not sure where this is coming from, but it seems first a cluster fails to form and then the cleanup fails because Gradle tries to delete files still in use by a running test cluster.

[Build Scan](https://scans.gradle.com/s/kcwp26sgeicyi)

**Comment by matriv** [comment]
Another failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/os=windows-2016/107/console

**Comment by matriv** [comment]
Same error for `:x-pack:plugin:ccr:qa:restart:followClusterRestartTest`
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/os=windows-2019/107/console

**Comment by henningandersen** [comment]
Similar error here, though not identical it looks like the same underlying issue:

https://gradle-enterprise.elastic.co/s/5tp5vjeeruqqk/failure?openFailures=WzBd&openStackTraces=WzFd#top=0

```
Unable to delete directory 'C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro'
  Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
  - C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro\modules\x-pack-ml\platform\windows-x86_64\bin\boost_date_time-vc141-mt-1_65_1.dll
  - C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro\modules\x-pack-ml\platform\windows-x86_64\bin\boost_filesystem-vc141-mt-1_65_1.dll
```

**Comment by atorok** [comment]
Looking at one of the stack traces of the failure:
```
at org.elasticsearch.gradle.testclusters.ElasticsearchNode.syncWithLinks(ElasticsearchNode.java:887)
at org.elasticsearch.gradle.testclusters.ElasticsearchNode.createWorkingDir(ElasticsearchNode.java:869)
at org.elasticsearch.gradle.testclusters.ElasticsearchNode.start(ElasticsearchNode.java:395)
at org.elasticsearch.gradle.testclusters.ElasticsearchNode.restart(ElasticsearchNode.java:474)
at org.elasticsearch.gradle.testclusters.ElasticsearchNode.goToNextVersion(ElasticsearchNode.java:486)
at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:158)
at org.elasticsearch.gradle.testclusters.ElasticsearchCluster.goToNextVersion(ElasticsearchCluster.java:277)
```

A restart operation is implemented as a `stop` followed by a `start`. 
The `start` does some cleanup if files exist. It's this cleanup that fails because some files can't be deleted possibly because they are still open. 
The stop does a recursive walk of processes so it's unlikely that processes linger. 
I have encountered this in testing some time ago [here](https://github.com/elastic/elasticsearch/pull/36475#discussion_r243624223).
@rjernst would you agree to add a wait and retry in case the cleanup fails here ?

**Comment by hendrikmuhs** [comment]
another one: https://gradle-enterprise.elastic.co/s/jsaajm7ezmr6q

**Comment by rjernst** [comment]
> The start does some cleanup if files exist. It's this cleanup that fails because some files can't be deleted possibly because they are still open.

How can they still be open? It looks like we always do a SIGKILL in this case, and even if we were doing a SIGTERM, there is logic in stop to wait on the pid. Retrying seems like it would be masking a different issue we need to identify.

**Comment by atorok** [comment]
@rjernst 
My understanding is that the fact that the process is no longer there doesn't guarantee that it's resources were closed. Not on windows. So if we stop elasticsearch and try to remove the files it was using in quick succession there's no way to have a guarantee that  those files were closed. 
Of course there's no way to know if the OS hasn't released the resources yet or there's something lurking, so I understand your concern, but I think a retry with a short timeout ( e.x. we try to delete for 5 seconds max before we give up ) would work if the OS is lagging behind but is not likely to help if there are processes lurking.

**Comment by droberts195** [comment]
There is a variation on this in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/os=windows-2019/129/console

```
> Unable to delete directory 'C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro\modules\x-pack-ml\platform\windows-x86_64\bin\boost_date_time-vc141-mt-x64-1_71.dll
    - C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro\modules\x-pack-ml\platform\windows-x86_64\bin\boost_filesystem-vc141-mt-x64-1_71.dll
    - C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro\modules\x-pack-ml\platform\windows-x86_64\bin\boost_iostreams-vc141-mt-x64-1_71.dll
    - C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro\modules\x-pack-ml\platform\windows-x86_64\bin\boost_program_options-vc141-mt-x64-1_71.dll
    - C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro\modules\x-pack-ml\platform\windows-x86_64\bin\boost_regex-vc141-mt-x64-1_71.dll
    - C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro\modules\x-pack-ml\platform\windows-x86_64\bin\controller.exe
    - C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro\modules\x-pack-ml\platform\windows-x86_64\bin\libapr-1.dll
    - C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro\modules\x-pack-ml\platform\windows-x86_64\bin\libapriconv-1.dll
    - C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro\modules\x-pack-ml\platform\windows-x86_64\bin\libaprutil-1.dll
    - C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro\modules\x-pack-ml\platform\windows-x86_64\bin\libMlCore.dll
    - C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro\modules\x-pack-ml\platform\windows-x86_64\bin\libxml2.dll
    - C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro\modules\x-pack-ml\platform\windows-x86_64\bin\log4cxx.dll
    - C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro\modules\x-pack-ml\platform\windows-x86_64\bin\msvcp140.dll
    - C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro\modules\x-pack-ml\platform\windows-x86_64\bin\vcruntime140.dll
    - C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro\modules\x-pack-ml\platform\windows-x86_64\bin\zlib1.dll
    - C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\ccr\qa\restart\build\testclusters\follow-cluster-0\distro\modules\x-pack-ml\platform\windows-x86_64\bin
    - and more ...
```

In this case the process that's stopping the files being deleted is the ML controller process.

Doing a `TerminateProcess` on the ES JVM will not instantly kill the controller.  Instead the controller notices that its stdin has been disconnected and exits.  But obviously there can be a few milliseconds between brutally killing the ES JVM (but not the controller) and the controller reacting.

> but I think a retry with a short timeout ( e.x. we try to delete for 5 seconds max before we give up )

5 seconds should be ample for the controller to notice that the ES JVM has died and exit by itself (especially given that this problem is fairly rare even without any retries).

The only other alternative would be for the testclusters code to kill the controller explicitly as well as the JVM before cleaning up installation directories.  But if multiple clusters are running in parallel that may not be easy.  It would need to kill the controller whose parent process is the JVM.  If it killed all processes named `controller.exe` then it would cripple the other clusters running in parallel on the same machine.  So retrying for up to 5 seconds is probably simpler.

**Comment by droberts195** [comment]
Another one like the original issue description, i.e. due to `.jar` files rather than the ML controller: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/os=windows-2016/129/console
