### ISSUE TITLE
[CI] DedicatedClusterSnapshotRestoreIT.testMasterAndDataShutdownDuringSnapshot failed on 7.3

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#46020]
https://gradle-enterprise.elastic.co/s/mn6ybih4ezo2w

failed

```
 ./gradlew :server:integTest --tests "org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT.testMasterAndDataShutdownDuringSnapshot" \
  -Dtests.seed=B78B95BC068C80D9 \
  -Dtests.security.manager=true \
  -Dtests.locale=dyo \
  -Dtests.timezone=Asia/Ashkhabad \
  -Dcompiler.java=12 \
  -Druntime.java=11

```

```
org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT > testMasterAndDataShutdownDuringSnapshot FAILED
    java.lang.AssertionError: ClusterUpdateSettingsResponse failed - not acked
    Expected: <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([B78B95BC068C80D9:6CDE8225066A2758]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:112)
        at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:100)
        at org.elasticsearch.test.InternalTestCluster.updateMinMasterNodes(InternalTestCluster.java:2161)
        at org.elasticsearch.test.InternalTestCluster.excludeMasters(InternalTestCluster.java:1856)
        at org.elasticsearch.test.InternalTestCluster.stopNodesAndClients(InternalTestCluster.java:1730)
        at org.elasticsearch.test.InternalTestCluster.stopNodesAndClient(InternalTestCluster.java:1726)
        at org.elasticsearch.test.InternalTestCluster.stopCurrentMasterNode(InternalTestCluster.java:1650)
        at org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT.testMasterAndDataShutdownDuringSnapshot(DedicatedClusterSnapshotRestoreIT.java:898)
REPRODUCE WITH: ./gradlew :server:integTest --tests "org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT.testMasterAndDataShutdownDuringSnapshot" -Dtests.seed=B78B95BC068C80D9 -Dtests.security.manager=true -Dtests.locale=dyo -Dtests.timezone=Asia/Ashkhabad -Dcompiler.java=12 -Druntime.java=11
```

seems that somehow the master failover in this test is not properly handled. Looking into it.

**Comment by original-brownbear** [comment]
Closing this, I misread the failure yesterday. This failure seems very much unrelated to the test in question and an issue with the internal test cluster code. Since this is the first time I've seen this failure, it could happen in any test and the affected code is gone in `7.x` and `master` now I'll close here.
