### ISSUE TITLE
[ML][CI] OutlierDetectionWithMissingFieldsIT has zero analyzing progress after finishing

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#46038]
Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+fast+part2/936/console

Build scan: https://gradle-enterprise.elastic.co/s/6urm7lak6mg52/tests/zcquf3hc3eoda-sovkystufd4fq?openStackTraces=WzBd

Failure:

```
java.lang.AssertionError: 

Expected: <100>
     but: was <0>

at __randomizedtesting.SeedInfo.seed([4B989193292F268C:E1F9F174EDE48A8D]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertProgress(MlNativeDataFrameAnalyticsIntegTestCase.java:135)
at org.elasticsearch.xpack.ml.integration.OutlierDetectionWithMissingFieldsIT.testMissingFields(OutlierDetectionWithMissingFieldsIT.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
```

Can't reproduce locally.

**Comment by benwtrent** [comment]
These two issues are related https://github.com/elastic/elasticsearch/issues/46122

They are exhibiting the same exact behavior. I am guessing they are the same cause.

**Comment by matriv** [comment]
Another failure: Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-windows-compatibility/os=windows-2019/99/console Build scan: https://gradle-enterprise.elastic.co/s/eofplva4q5kmi/

**Comment by dimitris-athanasiou** [comment]
OK, I'm actively investigating this one now so please bare with me

**Comment by dimitris-athanasiou** [comment]
I have found a potential race condition that is the prime suspect of those failures. Will address that and close the issue. We'll hopefully not see any more of those.
