### ISSUE TITLE
EmailSslTests failures

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#46067]
Some of the tests in EmailSslTests have failed twice in the last two days with the same error:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8fips,nodes=general-purpose/171/

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java8fips,nodes=general-purpose/170

```
Tests with failures:
- org.elasticsearch.xpack.watcher.actions.email.EmailSslTests.testCanSendMessageToSmtpServerByDisablingVerification
- org.elasticsearch.xpack.watcher.actions.email.EmailSslTests.testFailureSendingMessageToSmtpServerWithUntrustedCertificateAuthority
- org.elasticsearch.xpack.watcher.actions.email.EmailSslTests.testCanSendMessageToSmtpServerUsingTrustStore
```

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:watcher:test --tests "org.elasticsearch.xpack.watcher.actions.email.EmailSslTests.testFailureSendingMessageToSmtpServerWithUntrustedCertificateAuthority" -Dtests.seed=A1B1C9850FA48B30 -Dtests.security.manager=true -Dtests.locale=de -Dtests.timezone=Africa/Luanda -Dcompiler.java=12 -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password
07:52:06   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:watcher:test --tests 
```

```
07:52:06 org.elasticsearch.xpack.watcher.actions.email.EmailSslTests > testFailureSendingMessageToSmtpServerWithUntrustedCertificateAuthority FAILED
07:52:06     java.lang.IllegalArgumentException: unknown object in getInstance: org.bouncycastle.asn1.ASN1Integer
07:52:06         at org.bouncycastle.asn1.ASN1Sequence.getInstance(Unknown Source)
07:52:06         at org.bouncycastle.asn1.bc.ObjectStore.<init>(Unknown Source)
07:52:06         at org.bouncycastle.asn1.bc.ObjectStore.getInstance(Unknown Source)
07:52:06         at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.engineLoad(Unknown Source)
07:52:06         at java.security.KeyStore.load(KeyStore.java:1445)
07:52:06         at org.elasticsearch.xpack.watcher.actions.email.EmailSslTests.startSmtpServer(EmailSslTests.java:56)
07:52:06 
07:52:06     java.lang.NullPointerException
07:52:06         at org.elasticsearch.xpack.watcher.actions.email.EmailSslTests.stopSmtpServer(EmailSslTests.java:64)
```

```
07:52:06 org.elasticsearch.xpack.watcher.actions.email.EmailSslTests > testCanSendMessageToSmtpServerByDisablingVerification FAILED
07:52:06     java.lang.IllegalArgumentException: unknown object in getInstance: org.bouncycastle.asn1.ASN1Integer
07:52:06         at org.bouncycastle.asn1.ASN1Sequence.getInstance(Unknown Source)
07:52:06         at org.bouncycastle.asn1.bc.ObjectStore.<init>(Unknown Source)
07:52:06         at org.bouncycastle.asn1.bc.ObjectStore.getInstance(Unknown Source)
07:52:06         at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.engineLoad(Unknown Source)
07:52:06         at java.security.KeyStore.load(KeyStore.java:1445)
07:52:06         at org.elasticsearch.xpack.watcher.actions.email.EmailSslTests.startSmtpServer(EmailSslTests.java:56)
07:52:06 
07:52:06     java.lang.NullPointerException
07:52:06         at org.elasticsearch.xpack.watcher.actions.email.EmailSslTests.stopSmtpServer(EmailSslTests.java:64)

```

**Comment by jkakavas** [comment]
These should fail in FIPS as they use a JKS keystore for key material and also some have `verification_mode` to `none` . I'll adjust them
