### ISSUE TITLE
Response body of ListTasksRequest cannot be parsed

### ISSUE THREAD

**Issue by olfuerniss** [elastic/elasticsearch#46062]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 7.3.1, Build: default/tar/4749ba6/2019-08-19T20:19:25.651794Z, JVM: 11.0.4

**Plugins installed**: 
[ ingest-attachment ]

**JVM version** (`java -version`):
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Darwin OFs-MM.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:
I'm using the Java High Level REST Client. Getting tasks - while a search is still running - results in a parse exception (see Exception below).

**Steps to reproduce**:

 1. Start a search (long running search makes it easier to reproduce)
 2. Execute Java code to get the list of tasks (see code fragment below)

Is it a problem with the long value of "start_time_in_millis" (see curl output below)?

**Provide logs (if relevant)**:
```
java.io.IOException: Unable to parse response body for Response{requestLine=GET /_tasks?group_by=none&wait_for_completion=false HTTP/1.1, host=https://localhost:9200, response=HTTP/1.1 200 OK}
	at org.elasticsearch.client.RestHighLevelClient$1.onSuccess(RestHighLevelClient.java:1600)
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onSuccess(RestClient.java:556)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:300)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:294)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: cannot write time value xcontent for unknown value of type Long
	at org.elasticsearch.common.xcontent.XContentBuilder.timeField(XContentBuilder.java:731)
	at org.elasticsearch.tasks.TaskInfo.toXContent(TaskInfo.java:200)
	at org.elasticsearch.common.Strings.toString(Strings.java:778)
	at org.elasticsearch.tasks.TaskInfo.toString(TaskInfo.java:261)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
```

```
ListTasksRequest request = new ListTasksRequest();

esClient.tasks().listAsync(request, RequestOptions.DEFAULT, new ActionListener<ListTasksResponse>() {
    @Override
    public void onResponse(ListTasksResponse response) {
        List<TaskInfo> tasks = response.getTasks();
        for (TaskInfo task : tasks) {
            System.out.println("task = " + task);
        }
    }

    @Override
    public void onFailure(Exception e) {
        e.printStackTrace();
    }
});
```

```
curl 'https://localhost:9200/_tasks?group_by=none&detailed=false&wait_for_completion=false&actions=indices%3Adata%2Fread%2Fsearch*'

{
  "tasks": [
    {
      "node": "3ByFmC_STH6LuNqTXIv9qQ",
      "id": 214435,
      "type": "direct",
      "action": "indices:data/read/search[phase/query]",
      "start_time_in_millis": 1566981358433,
      "running_time_in_nanos": 2052356384,
      "cancellable": true,
      "parent_task_id": "3ByFmC_STH6LuNqTXIv9qQ:214431",
      "headers": {
        "X-Opaque-Id": "test-1234567890"
      }
    },
    {
      "node": "3ByFmC_STH6LuNqTXIv9qQ",
      "id": 214339,
      "type": "transport",
      "action": "indices:data/read/search",
      "start_time_in_millis": 1566981357131,
      "running_time_in_nanos": 3354327981,
      "cancellable": true,
      "headers": {}
    },
    {
      "node": "3ByFmC_STH6LuNqTXIv9qQ",
      "id": 214434,
      "type": "direct",
      "action": "indices:data/read/search[phase/query]",
      "start_time_in_millis": 1566981358433,
      "running_time_in_nanos": 2052508704,
      "cancellable": true,
      "parent_task_id": "3ByFmC_STH6LuNqTXIv9qQ:214431",
      "headers": {
        "X-Opaque-Id": "test-1234567890"
      }
    },
    {
      "node": "3ByFmC_STH6LuNqTXIv9qQ",
      "id": 214433,
      "type": "direct",
      "action": "indices:data/read/search[phase/query]",
      "start_time_in_millis": 1566981358433,
      "running_time_in_nanos": 2052653506,
      "cancellable": true,
      "parent_task_id": "3ByFmC_STH6LuNqTXIv9qQ:214431",
      "headers": {
        "X-Opaque-Id": "test-1234567890"
      }
    },
    {
      "node": "3ByFmC_STH6LuNqTXIv9qQ",
      "id": 214432,
      "type": "direct",
      "action": "indices:data/read/search[phase/query]",
      "start_time_in_millis": 1566981358432,
      "running_time_in_nanos": 2052790502,
      "cancellable": true,
      "parent_task_id": "3ByFmC_STH6LuNqTXIv9qQ:214431",
      "headers": {
        "X-Opaque-Id": "test-1234567890"
      }
    },
    {
      "node": "3ByFmC_STH6LuNqTXIv9qQ",
      "id": 214343,
      "type": "direct",
      "action": "indices:data/read/search[phase/query]",
      "start_time_in_millis": 1566981357131,
      "running_time_in_nanos": 3354095638,
      "cancellable": true,
      "parent_task_id": "3ByFmC_STH6LuNqTXIv9qQ:214339",
      "headers": {}
    },
    {
      "node": "3ByFmC_STH6LuNqTXIv9qQ",
      "id": 214342,
      "type": "direct",
      "action": "indices:data/read/search[phase/query]",
      "start_time_in_millis": 1566981357131,
      "running_time_in_nanos": 3354114970,
      "cancellable": true,
      "parent_task_id": "3ByFmC_STH6LuNqTXIv9qQ:214339",
      "headers": {}
    },
    {
      "node": "3ByFmC_STH6LuNqTXIv9qQ",
      "id": 214341,
      "type": "direct",
      "action": "indices:data/read/search[phase/query]",
      "start_time_in_millis": 1566981357131,
      "running_time_in_nanos": 3354138046,
      "cancellable": true,
      "parent_task_id": "3ByFmC_STH6LuNqTXIv9qQ:214339",
      "headers": {}
    },
    {
      "node": "3ByFmC_STH6LuNqTXIv9qQ",
      "id": 214436,
      "type": "direct",
      "action": "indices:data/read/search[phase/query]",
      "start_time_in_millis": 1566981358433,
      "running_time_in_nanos": 2052332276,
      "cancellable": true,
      "parent_task_id": "3ByFmC_STH6LuNqTXIv9qQ:214431",
      "headers": {
        "X-Opaque-Id": "test-1234567890"
      }
    },
    {
      "node": "3ByFmC_STH6LuNqTXIv9qQ",
      "id": 214340,
      "type": "direct",
      "action": "indices:data/read/search[phase/query]",
      "start_time_in_millis": 1566981357131,
      "running_time_in_nanos": 3354176614,
      "cancellable": true,
      "parent_task_id": "3ByFmC_STH6LuNqTXIv9qQ:214339",
      "headers": {}
    },
    {
      "node": "3ByFmC_STH6LuNqTXIv9qQ",
      "id": 214344,
      "type": "direct",
      "action": "indices:data/read/search[phase/query]",
      "start_time_in_millis": 1566981357131,
      "running_time_in_nanos": 3354080457,
      "cancellable": true,
      "parent_task_id": "3ByFmC_STH6LuNqTXIv9qQ:214339",
      "headers": {}
    },
    {
      "node": "3ByFmC_STH6LuNqTXIv9qQ",
      "id": 214431,
      "type": "transport",
      "action": "indices:data/read/search",
      "start_time_in_millis": 1566981358432,
      "running_time_in_nanos": 2053129653,
      "cancellable": true,
      "headers": {
        "X-Opaque-Id": "test-1234567890"
      }
    }
  ]
}

```

**Comment by jesinity** [comment]
Hey, as I did the twin issue I think I can pick it up!

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
