### ISSUE TITLE
RunDataFrameAnalyticsIT.testOutlierDetectionWithFewDocuments failed on 7.x

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#46063]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-windows-compatibility/os=windows-2019/96

```
REPRODUCE WITH: gradlew :x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testOutlierDetectionWithFewDocuments" -Dtests.seed=5E956C02FBB4472D -Dtests.security.manager=true -Dtests.locale=ms-MY -Dtests.timezone=America/Vancouver -Dcompiler.java=12 -Druntime.java=8
```

I was not able to reproduce this failure.

```
04:18:01   2> java.lang.AssertionError: 
04:18:01     Expected: <100>
04:18:01          but: was <0>
04:18:01         at __randomizedtesting.SeedInfo.seed([5E956C02FBB4472D:E0C58F8059F7C2C7]:0)
04:18:01         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
04:18:01         at org.junit.Assert.assertThat(Assert.java:956)
04:18:01         at org.junit.Assert.assertThat(Assert.java:923)
04:18:01         at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertProgress(MlNativeDataFrameAnalyticsIntegTestCase.java:135)
```

I also found this in the nodes logs:

```
04:18:49 ï¿½ WARN ][o.e.p.PersistentTasksClusterService] [integTest-0] persistent task datafeed-realtime-job-given-process-is-killed-datafeed failed
04:18:49 ï¿½  org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: analysis_problem_exception: ElasticsearchStatusException[Cannot perform requested action because job [realtime-job-given-process-is-killed] is not open]
04:18:49 ï¿½  	at org.elasticsearch.xpack.ml.datafeed.DatafeedJob.flushJob(DatafeedJob.java:460) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.ml.datafeed.DatafeedJob.run(DatafeedJob.java:401) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.ml.datafeed.DatafeedJob.runRealtime(DatafeedJob.java:181) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.ml.datafeed.DatafeedManager$Holder.executeRealTime(DatafeedManager.java:399) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.ml.datafeed.DatafeedManager$Holder.access$600(DatafeedManager.java:291) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.ml.datafeed.DatafeedManager$3.doRun(DatafeedManager.java:228) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773) [elasticsearch-7.4.0-SNAPSHOT.jar:7.4.0-SNAPSHOT]
04:18:49 ï¿½  	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.4.0-SNAPSHOT.jar:7.4.0-SNAPSHOT]
04:18:49 ï¿½  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
04:18:49 ï¿½  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
04:18:49 ï¿½  	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
04:18:49 ï¿½  Caused by: org.elasticsearch.ElasticsearchStatusException: Cannot perform requested action because job [realtime-job-given-process-is-killed] is not open
04:18:49 ï¿½  	at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.conflictStatusException(ExceptionsHelper.java:59) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.ml.action.TransportJobTaskAction.doExecute(TransportJobTaskAction.java:55) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.ml.action.TransportJobTaskAction.doExecute(TransportJobTaskAction.java:31) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:153) ~[elasticsearch-7.4.0-SNAPSHOT.jar:7.4.0-SNAPSHOT]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$apply$0(SecurityActionFilter.java:86) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.4.0-SNAPSHOT.jar:7.4.0-SNAPSHOT]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$authorizeRequest$4(SecurityActionFilter.java:172) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.4.0-SNAPSHOT.jar:7.4.0-SNAPSHOT]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$4(AuthorizationService.java:239) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:613) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:588) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43) ~[elasticsearch-7.4.0-SNAPSHOT.jar:7.4.0-SNAPSHOT]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authz.RBACEngine.authorizeClusterAction(RBACEngine.java:144) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeAction(AuthorizationService.java:241) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authz.AuthorizationService.maybeAuthorizeRunAs(AuthorizationService.java:225) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorize$1(AuthorizationService.java:191) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.4.0-SNAPSHOT.jar:7.4.0-SNAPSHOT]
04:18:49 ï¿½  	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43) ~[elasticsearch-7.4.0-SNAPSHOT.jar:7.4.0-SNAPSHOT]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authz.RBACEngine.lambda$resolveAuthorizationInfo$1(RBACEngine.java:117) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.4.0-SNAPSHOT.jar:7.4.0-SNAPSHOT]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRoles(CompositeRolesStore.java:193) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authz.RBACEngine.getRoles(RBACEngine.java:123) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authz.RBACEngine.resolveAuthorizationInfo(RBACEngine.java:111) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:193) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.authorizeRequest(SecurityActionFilter.java:172) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$3(SecurityActionFilter.java:158) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.4.0-SNAPSHOT.jar:7.4.0-SNAPSHOT]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$2(AuthenticationService.java:246) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$6(AuthenticationService.java:306) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:317) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:244) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:196) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:139) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.applyInternal(SecurityActionFilter.java:155) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$apply$2(SecurityActionFilter.java:100) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.core.security.SecurityContext.executeAsUser(SecurityContext.java:96) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.authz.AuthorizationUtils.switchUserBasedOnActionOriginAndExecute(AuthorizationUtils.java:115) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.apply(SecurityActionFilter.java:98) ~[?:?]
04:18:49 ï¿½  	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:151) ~[elasticsearch-7.4.0-SNAPSHOT.jar:7.4.0-SNAPSHOT]
04:18:49 ï¿½  	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:129) ~[elasticsearch-7.4.0-SNAPSHOT.jar:7.4.0-SNAPSHOT]
04:18:49 ï¿½  	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:64) ~[elasticsearch-7.4.0-SNAPSHOT.jar:7.4.0-SNAPSHOT]
04:18:49 ï¿½  	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) ~[elasticsearch-7.4.0-SNAPSHOT.jar:7.4.0-SNAPSHOT]
04:18:49 ï¿½  	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72) ~[elasticsearch-7.4.0-SNAPSHOT.jar:7.4.0-SNAPSHOT]
04:18:49 ï¿½  	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:396) ~[elasticsearch-7.4.0-SNAPSHOT.jar:7.4.0-SNAPSHOT]
04:18:49 ï¿½  	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:385) ~[elasticsearch-7.4.0-SNAPSHOT.jar:7.4.0-SNAPSHOT]
04:18:49 ï¿½  	at org.elasticsearch.xpack.ml.datafeed.DatafeedJob.flushJob(DatafeedJob.java:447) ~[?:?]
04:18:49 ï¿½  	... 10 more
```

**Comment by dimitris-athanasiou** [comment]
This is the same issue as https://github.com/elastic/elasticsearch/issues/46038. Closing this as we don't need both.
