### ISSUE TITLE
OutOfMemoryError occurred in master node due to cardinality aggregation

### ISSUE THREAD

**Issue by wyukawa** [elastic/elasticsearch#46116]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
7.1.1

**Plugins installed**: []

**JVM version** (`java -version`):
```
$ /usr/share/elasticsearch/jdk/bin/java -version
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```

**OS version** (`uname -a` if on a Unix-like system):
```
$ uname -a
Linux ... 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:
OutOfMemoryError occurred in the master node due to cardinality aggregation.
We have 3 master nodes.

Java heap of the master node is 16GB.
After this issue, I increase java heap to 20GB.

**Steps to reproduce**:
I'm sorry not to reproduce...

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
```

[2019-08-29T17:33:41,052 +0900][ERROR][o.e.ExceptionsHelper     ] [somehost] fatal error
	at org.elasticsearch.ExceptionsHelper.lambda$maybeDieOnAnotherThread$2(ExceptionsHelper.java:280)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.elasticsearch.ExceptionsHelper.maybeDieOnAnotherThread(ExceptionsHelper.java:270)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.exceptionCaught(Netty4MessageChannelHandler.java:61)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:856)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:364)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at java.base/java.lang.Thread.run(Thread.java:835)
[2019-08-29T17:33:41,017 +0900][WARN ][o.e.t.TcpTransport       ] [somehost] exception caught on transport layer [Netty4TcpChannel{localAddress=/..., remoteAddress=...}], closing connection
java.lang.Exception: java.lang.OutOfMemoryError: Java heap space
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.exceptionCaught(Netty4MessageChannelHandler.java:66) [transport-netty4-client-7.1.1.jar:7.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:856) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:364) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [netty-common-4.1.32.Final.jar:4.1.32.Final]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.elasticsearch.common.util.BigArrays.newByteArray(BigArrays.java:472) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.common.util.BigArrays.newByteArray(BigArrays.java:481) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.aggregations.metrics.HyperLogLogPlusPlus.<init>(HyperLogLogPlusPlus.java:772) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.aggregations.metrics.HyperLogLogPlusPlus.readFrom(HyperLogLogPlusPlus.java:1171) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.aggregations.metrics.InternalCardinality.<init>(InternalCardinality.java:50) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.SearchModule$$Lambda$1452/0x000000080171f440.read(Unknown Source) ~[?:?]
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:46) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:39) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.aggregations.InternalAggregations.lambda$readFrom$2(InternalAggregations.java:149) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.aggregations.InternalAggregations$$Lambda$3473/0x0000000801cb6840.read(Unknown Source) ~[?:?]
	at org.elasticsearch.common.io.stream.StreamInput.readCollection(StreamInput.java:1011) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.common.io.stream.StreamInput.readList(StreamInput.java:983) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.aggregations.InternalAggregations.readFrom(InternalAggregations.java:149) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.aggregations.InternalAggregations.readAggregations(InternalAggregations.java:143) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.aggregations.bucket.terms.InternalTerms$Bucket.<init>(InternalTerms.java:88) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.aggregations.bucket.terms.StringTerms$Bucket.<init>(StringTerms.java:53) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.aggregations.bucket.terms.StringTerms$$Lambda$3474/0x0000000801cb6c40.read(Unknown Source) ~[?:?]
	at org.elasticsearch.search.aggregations.bucket.terms.InternalMappedTerms.lambda$new$0(InternalMappedTerms.java:71) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.aggregations.bucket.terms.InternalMappedTerms$$Lambda$3475/0x0000000801cb6040.read(Unknown Source) ~[?:?]
	at org.elasticsearch.common.io.stream.StreamInput.readCollection(StreamInput.java:1011) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.common.io.stream.StreamInput.readList(StreamInput.java:983) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.aggregations.bucket.terms.InternalMappedTerms.<init>(InternalMappedTerms.java:71) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.aggregations.bucket.terms.StringTerms.<init>(StringTerms.java:123) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.SearchModule$$Lambda$1476/0x000000080172f440.read(Unknown Source) ~[?:?]
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:46) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:39) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.aggregations.InternalAggregations.lambda$readFrom$2(InternalAggregations.java:149) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.aggregations.InternalAggregations$$Lambda$3473/0x0000000801cb6840.read(Unknown Source) ~[?:?]
	at org.elasticsearch.common.io.stream.StreamInput.readCollection(StreamInput.java:1011) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.common.io.stream.StreamInput.readList(StreamInput.java:983) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.aggregations.InternalAggregations.readFrom(InternalAggregations.java:149) ~[elasticsearch-7.1.1.jar:7.1.1]
	at org.elasticsearch.search.aggregations.InternalAggregations.readAggregations(InternalAggregations.java:143) ~[elasticsearch-7.1.1.jar:7.1.1]
```

**Comment by nik9000** [comment]
I'm working on a thread that started with #54758 that should give us better control over memory usage on the coordinating node. I don't expect it to bear fruit super soon though. In the mean time I suggest lowering the size of the composite aggregation and/or lowering the precision on the cardinality agg.

Sorry this has sat for so long!

**Comment by iverase** [comment]
As #54758 has been merged, the situation should have improved quite a bit. There is no much we can do here so I am closing this issue.
