### ISSUE TITLE
[CI] RunDataFrameAnalyticsIT.testOutlierDetectionWithPreExistingDestIndex failure on master

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#46122]
Failed today on master.

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu-18.04&&immutable/232/console
Build Scans: https://gradle-enterprise.elastic.co/s/u3zm4hrvhxqk4

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testOutlierDetectionWithPreExistingDestIndex" \
  -Dtests.seed=BC684B638E6992DB \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Cyrl \
  -Dtests.timezone=SystemV/EST5 \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

Relevant stack trace:
```

org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT > testOutlierDetectionWithPreExistingDestIndex FAILED
--
java.lang.AssertionError:
Expected: <100>
but: was <0>
at __randomizedtesting.SeedInfo.seed([BC684B638E6992DB:DA2F6BBEE1550992]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertProgress(MlNativeDataFrameAnalyticsIntegTestCase.java:135)
at org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testOutlierDetectionWithPreExistingDestIndex(RunDataFrameAnalyticsIT.java:390)
```

First occurrence (new test), unable to reproduce locally.

**Comment by dimitris-athanasiou** [comment]
Indeed, this is the same problem described in #46038. Closing this in favour of the other issue.
