### ISSUE TITLE
[CI] TokenServiceTests.testTokenExpiry is flaky in 6.8

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#46132]
Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk13,nodes=general-purpose/172/console
Build Scan: https://gradle-enterprise.elastic.co/s/plowgy6q2a7jg

Reproduce with (doesn't reproduce locally):
```
./gradlew :x-pack:plugin:security:unitTest \
  -Dtests.seed=742725B6D6311224 \
  -Dtests.class=org.elasticsearch.xpack.security.authc.TokenServiceTests \
  -Dtests.method="testTokenExpiry" \
  -Dtests.security.manager=true \
  -Dtests.locale=mi \
  -Dtests.timezone=Etc/GMT-5 \
  -Dcompiler.java=12 \
  -Druntime.java=13
```

Relevant stack trace:
```

ERROR   0.27s J2 \| TokenServiceTests.testTokenExpiry <<< FAILURES!
--
> Throwable #1: java.util.concurrent.ExecutionException: ElasticsearchSecurityException[token expired]
> 	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:265)
> 	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:252)
> 	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:94)
> 	at org.elasticsearch.xpack.security.authc.TokenServiceTests.testTokenExpiry(TokenServiceTests.java:579)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
> 	at java.base/java.lang.Thread.run(Thread.java:830)
> Caused by: ElasticsearchSecurityException[token expired]
> 	at org.elasticsearch.xpack.security.authc.TokenService.expiredTokenException(TokenService.java:1368)
> 	at org.elasticsearch.xpack.security.authc.TokenService.lambda$decodeAndValidateToken$5(TokenService.java:358)
> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:61)
> 	at org.elasticsearch.xpack.security.authc.TokenService.lambda$decodeToken$8(TokenService.java:426)
> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:61)
> 	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)
> 	at org.elasticsearch.xpack.security.authc.TokenServiceTests.lambda$mockGetTokenFromId$11(TokenServiceTests.java:813)
> 	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:34)
> 	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:91)
> 	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
> 	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:38)
> 	at org.mockito.internal.creation.MethodInterceptorFilter.intercept(MethodInterceptorFilter.java:51)
> 	at org.elasticsearch.client.Client$$EnhancerByMockitoWithCGLIB$$22dfd1e6.get(<generated>)
> 	at org.elasticsearch.xpack.core.ClientHelper.executeAsyncWithOrigin(ClientHelper.java:73)
> 	at org.elasticsearch.xpack.security.authc.TokenService.lambda$decodeToken$10(TokenService.java:412)
> 	at org.elasticsearch.xpack.security.test.SecurityMocks.lambda$mockSecurityIndexManager$1(SecurityMocks.java:73)
> 	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:34)
> 	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:91)
> 	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
> 	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:38)
> 	at org.mockito.internal.creation.MethodInterceptorFilter.intercept(MethodInterceptorFilter.java:51)
> 	at org.elasticsearch.xpack.security.support.SecurityIndexManager$$EnhancerByMockitoWithCGLIB$$35f8ce05.checkIndexVersionThenExecute(<generated>)
> 	at org.elasticsearch.xpack.security.authc.TokenService.lambda$decodeToken$11(TokenService.java:406)
> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:61)
> 	at org.elasticsearch.xpack.security.authc.TokenService.decryptTokenId(TokenService.java:497)
> 	at org.elasticsearch.xpack.security.authc.TokenService.lambda$decodeToken$12(TokenService.java:401)
> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:61)
> 	at org.elasticsearch.xpack.security.authc.TokenService.getKeyAsync(TokenService.java:474)
> 	at org.elasticsearch.xpack.security.authc.TokenService.decodeToken(TokenService.java:395)
> 	at org.elasticsearch.xpack.security.authc.TokenService.decodeAndValidateToken(TokenService.java:353)
> 	at org.elasticsearch.xpack.security.authc.TokenService.getAndValidateToken(TokenService.java:314)
> 	at org.elasticsearch.xpack.security.authc.TokenServiceTests.testTokenExpiry(TokenServiceTests.java:578)
> 	... 36 moreThrowable #2: java.lang.AssertionError:
> Expected: an empty collection
>      but: <[299 Elasticsearch-6.8.3-SNAPSHOT-266de98 "[xpack.security.authc.token.compat.enabled] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version."]>
> 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
> 	at org.elasticsearch.test.ESTestCase.ensureNoWarnings(ESTestCase.java:395)
> 	at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:371)
> 	at jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
> 	at java.base/java.lang.Thread.run(Thread.java:830)

```

Seems that a backport of #42585 is missing for `6.8`

**Comment by jkakavas** [comment]
This has only failed that one time in 6.8. What's even stranger is the `AssertionError` : 
```
> Expected: an empty collection
>      but: <[299 Elasticsearch-6.8.3-SNAPSHOT-266de98 "[xpack.security.authc.token.compat.enabled] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version."]>
> 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
```

since `xpack.security.authc.token.compat.enabled` is `false` by default and we don't set it to true anywhere :hear_no_evil:
