### ISSUE TITLE
ES test   java.io.IOException: Could not remove the following files 

### ISSUE THREAD

**Issue by pengcongfa** [elastic/elasticsearch#46171]
when I test EncryptDirectoryWrapperTest which extends BaseDirectoryTestCase, it shows error:

java.io.IOException: Could not remove the following files (in the order of attempts):
   C:\Users\anthonypeng\AppData\Local\Temp\org.noop.essecure.store.encrypt.EncryptDirectoryWrapperTest_4F7D51BC9DD97FD6-001\testCopy-001: java.nio.file.DirectoryNotEmptyException: C:\Users\anthonypeng\AppData\Local\Temp\org.noop.essecure.store.encrypt.EncryptDirectoryWrapperTest_4F7D51BC9DD97FD6-001\testCopy-001
   C:\Users\anthonypeng\AppData\Local\Temp\org.noop.essecure.store.encrypt.EncryptDirectoryWrapperTest_4F7D51BC9DD97FD6-001\testCopy-001\_1.tim: java.nio.file.AccessDeniedException: C:\Users\anthonypeng\AppData\Local\Temp\org.noop.essecure.store.encrypt.EncryptDirectoryWrapperTest_4F7D51BC9DD97FD6-001\testCopy-001\_1.tim
   C:\Users\anthonypeng\AppData\Local\Temp\org.noop.essecure.store.encrypt.EncryptDirectoryWrapperTest_4F7D51BC9DD97FD6-001: java.nio.file.DirectoryNotEmptyException: C:\Users\anthonypeng\AppData\Local\Temp\org.noop.essecure.store.encrypt.EncryptDirectoryWrapperTest_4F7D51BC9DD97FD6-001

	at __randomizedtesting.SeedInfo.seed([4F7D51BC9DD97FD6]:0)
	at org.apache.lucene.util.IOUtils.rm(IOUtils.java:329)
	at org.apache.lucene.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:216)
	at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:844)

How to make this test pass ?
thanks!

**Comment by polyfractal** [comment]
Hmm, this might be a more appropriate question for the Lucene repo?  E.g. `BaseDirectoryTestCase` is a Lucene test class, so if you are extending it directly they would probably have more insight into what's going on.

If not the Lucene folks, I would recommend the [Discuss forums](https://discuss.elastic.co/).  We try to reserve the ES repo for bug reports, enhancements, etc.  Help with user issues that aren't a bug are usually better served on the forums.
