### ISSUE TITLE
[CI] SimpleSecurityNioTransportTests.testTracerLog failure for `7.3`

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#46307]
Build scan (intake): https://gradle-enterprise.elastic.co/s/ak7pb2i74idsw

Reproduce with (doesn't reproduce locally):
```
./gradlew :x-pack:plugin:security:test --tests "org.elasticsearch.xpack.security.transport.nio.SimpleSecurityNioTransportTests.testTracerLog" -Dtests.seed=33EF22DE2648D46E -Dtests.security.manager=true -Dtests.locale=en-MT -Dtests.timezone=America/Atikokan -Dcompiler.java=12 -Druntime.java=8
```

Stacktrace:
```
1> [2019-09-04T03:56:57,377][TRACE][o.e.t.T.tracer           ] [TS_B] [4][internal:testError] sent error response
--
1> java.lang.RuntimeException:
1> 	at org.elasticsearch.transport.AbstractSimpleTransportTestCase.lambda$testTracerLog$16(AbstractSimpleTransportTestCase.java:1007) ~[framework-7.3.2-SNAPSHOT.jar:7.3.2-SNAPSHOT]
1> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) ~[elasticsearch-7.3.2-SNAPSHOT.jar:7.3.2-SNAPSHOT]
1> 	at org.elasticsearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:267) ~[elasticsearch-7.3.2-SNAPSHOT.jar:7.3.2-SNAPSHOT]
1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.3.2-SNAPSHOT.jar:7.3.2-SNAPSHOT]
1> 	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:193) ~[elasticsearch-7.3.2-SNAPSHOT.jar:7.3.2-SNAPSHOT]
1> 	at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:188) ~[elasticsearch-7.3.2-SNAPSHOT.jar:7.3.2-SNAPSHOT]
1> 	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:121) ~[elasticsearch-7.3.2-SNAPSHOT.jar:7.3.2-SNAPSHOT]
1> 	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:105) ~[elasticsearch-7.3.2-SNAPSHOT.jar:7.3.2-SNAPSHOT]
1> 	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:660) ~[elasticsearch-7.3.2-SNAPSHOT.jar:7.3.2-SNAPSHOT]
1> 	at org.elasticsearch.transport.TcpTransport.consumeNetworkReads(TcpTransport.java:684) ~[elasticsearch-7.3.2-SNAPSHOT.jar:7.3.2-SNAPSHOT]
1> 	at org.elasticsearch.transport.nio.TcpReadWriteHandler.consumeReads(TcpReadWriteHandler.java:42) ~[transport-nio-client-7.3.2-SNAPSHOT.jar:7.3.2-SNAPSHOT]
1> 	at org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:200) ~[elasticsearch-nio-7.3.2-SNAPSHOT.jar:7.3.2-SNAPSHOT]
1> 	at org.elasticsearch.xpack.security.transport.nio.SSLChannelContext.read(SSLChannelContext.java:164) ~[main/:?]
1> 	at org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:119) ~[elasticsearch-nio-7.3.2-SNAPSHOT.jar:7.3.2-SNAPSHOT]
1> 	at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:408) ~[elasticsearch-nio-7.3.2-SNAPSHOT.jar:7.3.2-SNAPSHOT]
1> 	at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:244) ~[elasticsearch-nio-7.3.2-SNAPSHOT.jar:7.3.2-SNAPSHOT]
1> 	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:173) ~[elasticsearch-nio-7.3.2-SNAPSHOT.jar:7.3.2-SNAPSHOT]
1> 	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:130) ~[elasticsearch-nio-7.3.2-SNAPSHOT.jar:7.3.2-SNAPSHOT]
1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
1> [2019-09-04T03:56:57,384][TRACE][o.e.t.T.tracer           ] [TS_B] [5][internal:testNotSeen] received request
1> 2019-09-04 03:56:57,394 elasticsearch[TS_B][transport_worker][T#5] ERROR Attempted to append to non-started appender mock
1> [2019-09-04T03:56:57,386][TRACE][o.e.t.T.tracer           ] [TS_B] [5][internal:testNotSeen] sent response
2> REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test --tests "org.elasticsearch.xpack.security.transport.nio.SimpleSecurityNioTransportTests.testTracerLog" -Dtests.seed=33EF22DE2648D46E -Dtests.security.manager=true -Dtests.locale=en-MT -Dtests.timezone=America/Atikokan -Dcompiler.java=12 -Druntime.java=8
2> java.lang.AssertionError:
Expected: an empty collection
but: <[Attempted to append to non-started appender mock]>
1> [2019-09-04T03:56:57,439][INFO ][o.e.x.s.t.n.SimpleSecurityNioTransportTests] [testSNIServerNameIsPropagated] before test
1> [2019-09-04T03:56:57,542][INFO ][o.e.t.TransportService   ] [testSNIServerNameIsPropagated] publish_address {127.0.0.1:26500}, bound_addresses {[::1]:26500}, {127.0.0.1:26500}
1> [2019-09-04T03:56:57,669][INFO ][o.e.t.TransportService   ] [testSNIServerNameIsPropagated] publish_address {127.0.0.1:26501}, bound_addresses {[::1]:26501}, {127.0.0.1:26501}
1> [2019-09-04T03:56:57,827][INFO ][o.e.t.TransportService   ] [testSNIServerNameIsPropagated] publish_address {127.0.0.1:26502}, bound_addresses {[::1]:26502}, {127.0.0.1:26502}
1> [2019-09-04T03:56:57,926][INFO ][o.e.x.s.t.n.SimpleSecurityNioTransportTests] [testSNIServerNameIsPropagated] after test
1> [2019-09-04T03:56:57,929][INFO ][o.e.x.s.t.n.SimpleSecurityNioTransportTests] [testThreadContext] before test
1> [2019-09-04T03:56:57,984][INFO ][o.e.t.TransportService   ] [testThreadContext] publish_address {127.0.0.1:26500}, bound_addresses {[::1]:26500}, {127.0.0.1:26500}
1> [2019-09-04T03:56:58,103][INFO ][o.e.t.TransportService   ] [testThreadContext] publish_address {127.0.0.1:26501}, bound_addresses {[::1]:26501}, {127.0.0.1:26501}
1> [2019-09-04T03:56:58,186][INFO ][o.e.x.s.t.n.SimpleSecurityNioTransportTests] [testThreadContext] after test
1> [2019-09-04T03:56:58,191][INFO ][o.e.x.s.t.n.SimpleSecurityNioTransportTests] [testAcceptedChannelCount] before test
1> [2019-09-04T03:56:58,282][INFO ][o.e.t.TransportService   ] [testAcceptedChannelCount] publish_address {127.0.0.1:26500}, bound_addresses {[::1]:26500}, {127.0.0.1:26500}
1> [2019-09-04T03:56:58,407][INFO ][o.e.t.TransportService   ] [testAcceptedChannelCount] publish_address {127.0.0.1:26501}, bound_addresses {[::1]:26501}, {127.0.0.1:26501}
1> [2019-09-04T03:56:58,504][INFO ][o.e.x.s.t.n.SimpleSecurityNioTransportTests] [testAcceptedChannelCount] after test
1> [2019-09-04T03:56:58,508][INFO ][o.e.x.s.t.n.SimpleSecurityNioTransportTests] [testMockFailToSendNoConnectRule] before test
1> [2019-09-04T03:56:58,662][INFO ][o.e.t.TransportService   ] [testMockFailToSendNoConnectRule] publish_address {127.0.0.1:26500}, bound_addresses {[::1]:26500}, {127.0.0.1:26500}
1> [2019-09-04T03:56:58,842][INFO ][o.e.t.TransportService   ] [testMockFailToSendNoConnectRule] publish_address {127.0.0.1:26501}, bound_addresses {[::1]:26501}, {127.0.0.1:26501}
1> [2019-09-04T03:56:58,981][INFO ][o.e.x.s.t.n.SimpleSecurityNioTransportTests] [testMockFailToSendNoConnectRule] after test

```

**Comment by original-brownbear** [comment]
Closing this one since it hasn't happened again for 3 weeks now and the last failure was on the `7.3` branch anyway, see https://github.com/elastic/elasticsearch/pull/46964#issuecomment-534425809 for details.
