### ISSUE TITLE
[CI] checkpoint tracker failure in 6.8 cluster upgrade test

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#46311]
BWC tests: 6.5.0 -> 6.8

In `:x-pack:qa:full-cluster-restart:without-system-key:v6.5.0#upgradedClusterTestCluster`

- https://gradle-enterprise.elastic.co/s/gcxbry3p3y6o6/console-log?task=:x-pack:qa:full-cluster-restart:without-system-key:v6.5.0%23upgradedClusterTestCluster%23wait#L258
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+bwc/BWC_VERSION=6.5.0,nodes=centos-7&&immutable/90/console

```
[2019-09-04T10:07:34,985][INFO ][o.e.x.m.e.l.LocalExporter] [node-0] waiting for elected master node [{node-1}{Iu3gP669TKqwgd5WOGm5fw}{IadoUf9wQyGoOw05oGWWrw}{127.0.0.1}{127.0.0.1:35699}{testattr=test, ml.machine_memory=63158317056, ml.max_open_jobs=20, xpack.installed=true, ml.enabled=true}] to setup local exporter [default_local] (does it have x-pack installed?)
[2019-09-04T10:07:35,162][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-0] fatal error in thread [elasticsearch[node-0][generic][T#3]], exiting
java.lang.AssertionError: local checkpoint tracker is not updated seq_no=49 id=49
	at org.elasticsearch.index.engine.InternalEngine.compareOpToLuceneDocBasedOnSeqNo(InternalEngine.java:729) ~[elasticsearch-6.8.3-SNAPSHOT.jar:6.8.3-SNAPSHOT]
	at org.elasticsearch.index.engine.InternalEngine.planIndexingAsNonPrimary(InternalEngine.java:1012) ~[elasticsearch-6.8.3-SNAPSHOT.jar:6.8.3-SNAPSHOT]
```

**Comment by dnhatn** [comment]
Fixed in #46340
