### ISSUE TITLE
[ML][Transforms] DataFrameSurvivesUpgradeIT.testDataFramesRollingUpgrade fails

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#46341]
Build failures: 

https://gradle-enterprise.elastic.co/s/tfjp6r3wqpfdy

Relevant stacktrace:
```
[2019-09-05T12:58:36,059][ERROR][o.e.x.d.t.DataFrameTransformPersistentTasksExecutor] [v7.5.0-2] Failed to start task [continuous-data-frame-upgrade-job] in node operation
org.elasticsearch.ElasticsearchStatusException: Cannot start transform [continuous-data-frame-upgrade-job] as it is already STARTED.
	at org.elasticsearch.xpack.dataframe.transforms.DataFrameTransformTask.start(DataFrameTransformTask.java:256) [data-frame-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.xpack.dataframe.transforms.DataFrameTransformPersistentTasksExecutor.startTask(DataFrameTransformPersistentTasksExecutor.java:308) [data-frame-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.xpack.dataframe.transforms.DataFrameTransformPersistentTasksExecutor.lambda$nodeOperation$3(DataFrameTransformPersistentTasksExecutor.java:164) [data-frame-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.xpack.dataframe.persistence.DataFrameTransformsConfigManager.lambda$getTransformCheckpoint$5(DataFrameTransformsConfigManager.java:275) [data-frame-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:70) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:309) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchSearchPhase$3.run(FetchSearchPhase.java:217) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:180) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:174) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:119) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:180) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:174) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:210) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$2(FetchSearchPhase.java:104) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:110) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:44) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:86) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
Able to reproduce locally.

**Comment by tlrx** [comment]
It should have been fixed by #46337, but this test failed again today:
https://gradle-enterprise.elastic.co/s/gpsou3ytaa5t4

with the same exception.

**Comment by benwtrent** [comment]
@tlrx the checked out code for 7.5 was `7e4c633ce38807847fe1c8006e7d295b9a310ff1` (from what I can tell). Which did not include the fix.

**Comment by tlrx** [comment]
@benwtrent Sorry for the noise then, I thought I checked correctly the commit. Should this issue be closed then?

**Comment by benwtrent** [comment]
@tlrx I think so. I will go ahead and close it. We can reopen it if the test fails again with the fix :)
