### ISSUE TITLE
JvmErgonomics does not know to handle pin in parameters

### ISSUE THREAD

**Issue by tiitginter** [elastic/elasticsearch#46390]
I have elasticsearch 7.3.1 and try to start it with JVM parameters that contain %p as pid name but get exception instead.

Parameter is -XX:OnOutOfMemoryError="oomHandler %p &"

Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:

error:
Error: Could not find or load main class %p
Caused by: java.lang.ClassNotFoundException: %p
        at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
        at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
        at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)

**Comment by jasontedor** [comment]
Note that there is a [bootstrap check that prevents the use of `OnOutOfMemoryError` anyway](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/_onerror_and_onoutofmemoryerror_checks.html):

```
ERROR: [1] bootstrap checks failed
[1]: OnOutOfMemoryError [kill] requires forking but is prevented by system call filters ([bootstrap.system_call_filter=true]); upgrade to at least Java 8u92 and use ExitOnOutOfMemoryError
```

The problem, however is not the `%p` parameter, but rather JVM ergonomics is not handling the space in the JVM option.

**Comment by jasontedor** [comment]
I have edited the title of this issue to reflect the underlying problem here.
