### ISSUE TITLE
SQL: NPE when using CASE WHEN with CASTed returned value

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#46551]
`SELECT CASE WHEN salary IS NOT NULL THEN CAST(gender AS VARCHAR) ELSE gender END AS x FROM test_emp`

```
[elasticsearch] java.lang.NullPointerException: null
[elasticsearch]         at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.createResponseWithSchema(TransportSqlQueryAction.java:100) ~[?:?]
[elasticsearch]         at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.lambda$operation$0(TransportSqlQueryAction.java:80) ~[?:?]
[elasticsearch]         at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.xpack.sql.execution.search.Querier$ScrollActionListener.lambda$handleResponse$2(Querier.java:432) [x-pack-sql-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.lambda$clear$3(Querier.java:530) [x-pack-sql-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
[elasticsearch]         at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
```

**Comment by matriv** [comment]
`master` : 291017d69dfc810707c3c7c692f5a50af431b790
`7.x` : 0963e78164c46eb625a35a480f5bb8b3b00e86fa
`7.4` : 1e143f63cbb9ad39097e9bb1ff1cbe16b57c8fd8
`7.3` : 2afb7cf52c4aca6c492db88306cd40aa804a13e3
`6.8` : cb56550d26ac45dc53249f909058c12566f3a24b
