### ISSUE TITLE
Exception in thread “main” java.nio.file.AccessDeniedException while run ./bin/elasticsearch

### ISSUE THREAD

**Issue by YasiruDev** [elastic/elasticsearch#46645]
I'm trying to install ElasticSearch in to my server.When i run ./bin/elasticsearch got bellow error

```
Exception in thread "main" java.nio.file.AccessDeniedException: /var/www/elasticsearch-7.3.1/config/jvm.options
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:155)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:61)
```

**Inside Elasticsearch directory :**

```
ubuntu@ip-14-0-0-129:/var/www/elasticsearch-7.3.1$ ll
total 564
drwxr-xr-x  9 root   root   4096 Sep 12 10:28 ./
drwxr-xr-x 11 root   root   4096 Sep 11 16:42 ../
-rw-r--r--  1 root   root   1024 Sep 12 10:28 .start.swp
-rw-r--r--  1 ubuntu root  13675 Aug 20 01:48 LICENSE.txt
-rw-r--r--  1 ubuntu root 502598 Aug 20 01:53 NOTICE.txt
-rw-r--r--  1 ubuntu root   8500 Aug 20 01:47 README.textile
drwxr-xr-x  2 ubuntu root   4096 Aug 20 01:58 bin/
drwxr-xr-x  2 ubuntu root   4096 Sep 12 10:40 config/
drwxr-xr-x  3 ubuntu root   4096 Aug 20 01:58 jdk/
drwxr-xr-x  3 ubuntu root   4096 Aug 20 01:58 lib/
drwxr-xr-x  2 ubuntu root   4096 Sep 12 10:40 logs/
drwxr-xr-x 33 ubuntu root   4096 Aug 20 01:58 modules/
drwxr-xr-x  2 ubuntu root   4096 Aug 20 01:53 plugins/
-rw-------  1 root   root      2 Sep 12 10:28 start.save
```

ElasticSearch : 7.3.1
Java : 11.0.4

**Comment by jimczi** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
