### ISSUE TITLE
org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testStopOutlierDetectionWithEnoughDocumentsToScroll fails on master

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#46705]
org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testStopOutlierDetectionWithEnoughDocumentsToScroll failed on master:
```
13:40:39 org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT > testStopOutlierDetectionWithEnoughDocumentsToScroll FAILED
13:40:39     java.lang.AssertionError: 
13:40:39     Expected: <0L>
13:40:39          but: was <1L>
13:40:39         at __randomizedtesting.SeedInfo.seed([CE9E38CE5E762526:5E6FCDEAD92BA21C]:0)
13:40:39         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
13:40:39         at org.junit.Assert.assertThat(Assert.java:956)
13:40:39         at org.junit.Assert.assertThat(Assert.java:923)
13:40:39         at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.cleanUpAnalytics(MlNativeDataFrameAnalyticsIntegTestCase.java:52)
13:40:39         at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.cleanUpResources(MlNativeDataFrameAnalyticsIntegTestCase.java:45)
13:40:39         at org.elasticsearch.xpack.ml.integration.MlNativeIntegTestCase.cleanUp(MlNativeIntegTestCase.java:127)
13:40:39         at org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.cleanup(RunDataFrameAnalyticsIT.java:46)
```

The assertion fails during cleanup:
```
                assertThat(searchStoredProgress(config.getId()).getHits().getTotalHits().value, equalTo(0L));
```

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testStopOutlierDetectionWithEnoughDocumentsToScroll" \
  -Dtests.seed=CE9E38CE5E762526 \
  -Dtests.security.manager=true \
  -Dtests.locale=en-CC \
  -Dtests.timezone=Asia/Choibalsan \
  -Dcompiler.java=12 \
  -Druntime.java=11
```
Does not reproduce locally.

Build | 20190913073350-B735813E
-- | --
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/207/console
Build Scans | https://gradle-enterprise.elastic.co/s/z4parnu5jlhoyhttps://gradle-enterprise.elastic.co/s/ti53rgd66ecokhttps://gradle-enterprise.elastic.co/s/dqgzy2f5yitna

**Comment by jrodewig** [comment]
Had another instance of this:
https://gradle-enterprise.elastic.co/s/zqmybihsdsoro/failure?openFailures=WzBd&openStackTraces=WzFd#top=0

**Comment by dimitris-athanasiou** [comment]
You got to love tests! This failure revealed that we are returning the response to the stop API before the task is actually stopped. The progress document is indexed after we returned from stopped and possible called delete and thus delete is missing it. I am working on a fix.

**Comment by mark-vieira** [comment]
And another:
https://gradle-enterprise.elastic.co/s/klrshptyonuxk/tests/zcquf3hc3eoda-so3ayypsxka5i
