### ISSUE TITLE
:qa:full-cluster-restart FullClusterRestartIT.testRecovery fails

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#46712]
Likely duplicate of https://github.com/elastic/elasticsearch/issues/31062

The following can be found in the logs:
```
14:53:15   2> REPRODUCE WITH: ./gradlew ':qa:full-cluster-restart:v6.0.0#upgradedClusterTestRunner' -Dtests.seed=A55CB0DC1DA26D51 -Dtests.class=org.elasticsearch.upgrades.FullClusterRestartIT -Dtests.method="testRecovery" -Dtests.security.manager=true -Dtests.locale=de-DE -Dtests.timezone=Europe/Astrakhan -Dcompiler.java=12 -Druntime.java=8
14:53:15 FAILURE 0.06s | FullClusterRestartIT.testRecovery <<< FAILURES!
14:53:15    > Throwable #1: java.lang.AssertionError: mismatch while checking for translog recovery
14:53:15    > testrecovery 0 existing_store done 0
14:53:15    > testrecovery 0 peer           done 0
14:53:15    > testrecovery 1 existing_store done 0
14:53:15    > testrecovery 1 peer           done 0
14:53:15    > testrecovery 2 existing_store done 0
14:53:15    > testrecovery 2 peer           done 0
14:53:15    > testrecovery 3 existing_store done 0
14:53:15    > testrecovery 3 peer           done 0
14:53:15    > testrecovery 4 existing_store done 64
14:53:15    > testrecovery 4 peer           done 0
14:53:15    >  expected:<false> but was:<true>
14:53:15    > 	at __randomizedtesting.SeedInfo.seed([A55CB0DC1DA26D51:64ACC97030F2A7F6]:0)
14:53:15    > 	at org.elasticsearch.upgrades.FullClusterRestartIT.testRecovery(FullClusterRestartIT.java:794)
14:53:15    > 	at java.lang.Thread.run(Thread.java:748)
```

```
./gradlew ':qa:full-cluster-restart:v6.0.0#upgradedClusterTestRunner' \
  -Dtests.seed=A55CB0DC1DA26D51 \
  -Dtests.class=org.elasticsearch.upgrades.FullClusterRestartIT \
  -Dtests.method="testRecovery" \
  -Dtests.security.manager=true
```

Does not reproduce locally.

Build | 20190913124846-031FFA38
-- | --
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+bwc/BWC_VERSION=6.0.0,nodes=centos-7&&immutable/118/console
Build Scans | https://gradle-enterprise.elastic.co/s/ijnjpreh5erhc

**Comment by ywelsch** [comment]
Note that there are also failures on more recent versions of ES, see e.g. https://gradle-enterprise.elastic.co/s/4nskr3isf4ewe/console-log/raw which goes from v6.1.2 to 7.x.
The test fails expecting there to be no operations to be synced during peer recovery, but one of the shards has operations being synced. I wonder if the `safe commit == last commit == contains all ops` property has not been properly established on both primary and replicas before the full cluster restart. @dnhatn thoughts?

**Comment by dnhatn** [comment]
@ywelsch I am on it today.

**Comment by droberts195** [comment]
The same test failed again in the same way in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+bwc/BWC_VERSION=6.6.2,nodes=centos-7&&immutable/173/console (scan https://gradle-enterprise.elastic.co/s/n3a7fyrvg66cw)

The failure was:

```
09:51:03 org.elasticsearch.upgrades.FullClusterRestartIT > testRecovery FAILED
09:51:03     java.lang.AssertionError: mismatch while checking for translog recovery
09:51:03     testrecovery 0 existing_store done 0
09:51:03     testrecovery 0 peer           done 0
09:51:03     testrecovery 1 existing_store done 0
09:51:03     testrecovery 1 peer           done 0
09:51:03     testrecovery 2 existing_store done 0
09:51:03     testrecovery 2 peer           done 0
09:51:03     testrecovery 3 existing_store done 0
09:51:03     testrecovery 3 peer           done 0
09:51:03     testrecovery 4 existing_store done 64
09:51:03     testrecovery 4 peer           done 0
09:51:03      expected:<false> but was:<true>
09:51:03         at __randomizedtesting.SeedInfo.seed([EB8389275C0D0384:2A73F08B715DC923]:0)
09:51:03         at org.junit.Assert.fail(Assert.java:88)
09:51:03         at org.junit.Assert.failNotEquals(Assert.java:834)
09:51:03         at org.junit.Assert.assertEquals(Assert.java:118)
09:51:03         at org.elasticsearch.upgrades.FullClusterRestartIT.testRecovery(FullClusterRestartIT.java:808)
```

This did not reproduce locally using:

```
./gradlew ':qa:full-cluster-restart:v6.6.2#upgradedClusterTestRunner' --tests "org.elasticsearch.upgrades.FullClusterRestartIT.testRecovery" -Dtests.seed=EB8389275C0D0384 -Dtests.security.manager=true -Dtests.locale=ar-LY -Dtests.timezone=Australia/Darwin -Dcompiler.java=12 -Druntime.java=8
```
