### ISSUE TITLE
NoClassDefFoundError in vesion 7.3.0

### ISSUE THREAD

**Issue by freesinger** [elastic/elasticsearch#46732]
**Describe the feature**:

When I attempt to run `./elasticsearch.bat` command on my win10 PC, it comes across the `NoClassDefFoundError`  which has never occured before.

Same problem appeared when I configure ES in another server, which makes me confused.

**Elasticsearch version** (`bin/elasticsearch --version`):  7.3.0

**JVM version** :

java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

**OS version**:  Windows 10

**Provide logs (if relevant)**:

Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/fasterxml/jackson/dataformat/yaml/YAMLGenerator                                                              at org.elasticsearch.common.xcontent.XContentType$3.xContent(XContentType.java:94)                                                                                                at org.elasticsearch.common.xcontent.XContentFactory.xContent(XContentFactory.java:135)                                                                                           at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1086)                                                                                          at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Settings.java:1070)                                                                                            at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:83)                                                                           at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:95)                                                                                       at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)                                                                                         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)                                                                                                       at org.elasticsearch.cli.Command.main(Command.java:90)                                                                                                                            at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115)                                                                                                         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)                                                                                                  Caused by: java.lang.ClassNotFoundException: org.elasticsearch.fasterxml.jackson.dataformat.yaml.YAMLGenerator                                                                            at java.net.URLClassLoader.findClass(URLClassLoader.java:381)                                                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)                                                                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:357)                                                                                                                          ... 11 more

**Comment by freesinger** [comment]
I have found the problem, which is caused by my JDK files.
I reinstalled my JDK and everything ran smoothly.
