### ISSUE TITLE
[CI] org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testStopOutlierDetectionWithEnoughDocumentsToScroll fails on 7.4

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#46907]
org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testStopOutlierDetectionWithEnoughDocumentsToScroll failed on 7.4:

Logs: https://gradle-enterprise.elastic.co/s/wcgoihe5e5cnw/console-log?task=:x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner

Cannot reproduce locally with:
```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testStopOutlierDetectionWithEnoughDocumentsToScroll" \
  -Dtests.seed=2E7756CD3B416807 \
  -Dtests.security.manager=true \
  -Dtests.locale=sah \
  -Dtests.timezone=Atlantic/Faroe \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

Stacktrace:
```
org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT > testStopOutlierDetectionWithEnoughDocumentsToScroll FAILED
--
java.lang.AssertionError:
Expected: <0L>
but: was <1L>
at __randomizedtesting.SeedInfo.seed([2E7756CD3B416807:BE86A3E9BC1CEF3D]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.cleanUpAnalytics(MlNativeDataFrameAnalyticsIntegTestCase.java:54)
at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.cleanUpResources(MlNativeDataFrameAnalyticsIntegTestCase.java:45)
at org.elasticsearch.xpack.ml.integration.MlNativeIntegTestCase.cleanUp(MlNativeIntegTestCase.java:98)
at org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.cleanup(RunDataFrameAnalyticsIT.java:46)
```

Seems the same as: #46705 but the fix was already backported to 7.4

**Comment by romseygeek** [comment]
Also just failed on master :(

https://gradle-enterprise.elastic.co/s/nbuey7zc3cxaw/tests/zcquf3hc3eoda-so3ayypsxka5i

**Comment by jkakavas** [comment]
This failed [7 times in the last two days](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testStopOutlierDetectionWithEnoughDocumentsToScroll),sort:!(time,desc))) and on [master intake just now](https://gradle-enterprise.elastic.co/s/3yyujfxt3mloi) so I will mute it
