### ISSUE TITLE
[CI] :qa:full-cluster-restart:v6.2.2#upgradedClusterTestRunner test org.elasticsearch.upgrades.FullClusterRestartIT.testRecovery fails on 7.x

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#46910]
Logs: https://gradle-enterprise.elastic.co/s/da4duv2k3h4v4/console-log?task=:qa:full-cluster-restart:v6.2.2%23upgradedClusterTestRunner

Cannot reproduce locally with:
```
./gradlew ':qa:full-cluster-restart:v6.2.2#upgradedClusterTestRunner' --tests "org.elasticsearch.upgrades.FullClusterRestartIT.testRecovery" \
  -Dtests.seed=6230F4BE61354C34 \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Latn-ME \
  -Dtests.timezone=Australia/Currie \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

Stacktrace: 
```

org.elasticsearch.upgrades.FullClusterRestartIT > testRecovery FAILED
--
java.lang.AssertionError: mismatch while checking for translog recovery
testrecovery 0 existing_store done 55
testrecovery 0 peer           done 0
testrecovery 1 existing_store done 0
testrecovery 1 peer           done 0
testrecovery 2 existing_store done 0
testrecovery 2 peer           done 0
testrecovery 3 existing_store done 0
testrecovery 3 peer           done 0
testrecovery 4 existing_store done 0
testrecovery 4 peer           done 0
expected:<false> but was:<true>
at __randomizedtesting.SeedInfo.seed([6230F4BE61354C34:A3C08D124C658693]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.elasticsearch.upgrades.FullClusterRestartIT.testRecovery(FullClusterRestartIT.java:803)
```

**Comment by ywelsch** [comment]
There's already an open issue for this: #46712

**Comment by matriv** [comment]
@ywelsch Thx, somehow I missed it.
