### ISSUE TITLE
[CI] ApiKeyServiceTests#testStoreApiKey failure

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#46921]
Logs: https://gradle-enterprise.elastic.co/s/s7mmkbf7powj4/console-log?task=:x-pack:plugin:security:unitTest

Could not reproduce locally with: 
```
./gradlew ':x-pack:plugin:security:unitTest' \
  -Dtests.seed=F197439E0E1FA595 \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ApiKeyServiceTests \
  -Dtests.method="testStoreApiKey" \
  -Dtests.security.manager=true \
  -Dtests.locale=ms-MY \
  -Dtests.timezone=Asia/Amman \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

Stacktrace:
```

ERROR   0.11s J11 \| ApiKeyServiceTests.testStoreApiKey <<< FAILURES!
--
> Throwable #1: java.util.concurrent.ExecutionException: java.lang.NullPointerException
> 	at __randomizedtesting.SeedInfo.seed([F197439E0E1FA595:6F83BA551DE6F5AF]:0)
> 	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:265)
> 	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:252)
> 	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:94)
> 	at org.elasticsearch.xpack.security.authc.ApiKeyServiceTests.testStoreApiKey(ApiKeyServiceTests.java:204)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NullPointerException
> 	at java.util.Objects.requireNonNull(Objects.java:203)
> 	at org.elasticsearch.action.DocWriteResponse.<init>(DocWriteResponse.java:126)
> 	at org.elasticsearch.action.index.IndexResponse.<init>(IndexResponse.java:48)
> 	at org.elasticsearch.action.index.IndexResponse.<init>(IndexResponse.java:44)
> 	at org.elasticsearch.xpack.security.authc.ApiKeyServiceTests.lambda$testStoreApiKey$3(ApiKeyServiceTests.java:198)
> 	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:34)
> 	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:91)
> 	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
> 	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:38)
> 	at org.mockito.internal.creation.MethodInterceptorFilter.intercept(MethodInterceptorFilter.java:51)
> 	at org.elasticsearch.client.Client$$EnhancerByMockitoWithCGLIB$$c3a9e9fb.execute(<generated>)
> 	at org.elasticsearch.xpack.core.ClientHelper.executeAsyncWithOrigin(ClientHelper.java:88)
> 	at org.elasticsearch.xpack.security.authc.ApiKeyService.lambda$createApiKeyAndIndexIt$4(ApiKeyService.java:255)
> 	at org.elasticsearch.xpack.security.test.SecurityMocks.lambda$mockSecurityIndexManager$0(SecurityMocks.java:68)
> 	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:34)
> 	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:91)
> 	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
> 	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:38)
> 	at org.mockito.internal.creation.MethodInterceptorFilter.intercept(MethodInterceptorFilter.java:51)
> 	at org.elasticsearch.xpack.security.support.SecurityIndexManager$$EnhancerByMockitoWithCGLIB$$d6c2e61a.prepareIndexIfNeededThenExecute(<generated>)
> 	at org.elasticsearch.xpack.security.authc.ApiKeyService.createApiKeyAndIndexIt(ApiKeyService.java:254)
> 	at org.elasticsearch.xpack.security.authc.ApiKeyService.lambda$checkDuplicateApiKeyNameAndCreateApiKey$1(ApiKeyService.java:228)
> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:61)
> 	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)
> 	at org.elasticsearch.xpack.security.test.SecurityMocks.lambda$mockSearchHits$3(SecurityMocks.java:124)
> 	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:34)
> 	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:91)
> 	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
> 	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:38)
> 	at org.mockito.internal.creation.MethodInterceptorFilter.intercept(MethodInterceptorFilter.java:51)
> 	at org.elasticsearch.client.Client$$EnhancerByMockitoWithCGLIB$$c3a9e9fb.execute(<generated>)
> 	at org.elasticsearch.xpack.core.ClientHelper.executeAsyncWithOrigin(ClientHelper.java:88)
> 	at org.elasticsearch.xpack.security.authc.ApiKeyService.lambda$checkDuplicateApiKeyNameAndCreateApiKey$2(ApiKeyService.java:221)
> 	at org.elasticsearch.xpack.security.test.SecurityMocks.lambda$mockSecurityIndexManager$0(SecurityMocks.java:68)
> 	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:34)
> 	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:91)
> 	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
> 	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:38)
> 	at org.mockito.internal.creation.MethodInterceptorFilter.intercept(MethodInterceptorFilter.java:51)
> 	at org.elasticsearch.xpack.security.support.SecurityIndexManager$$EnhancerByMockitoWithCGLIB$$d6c2e61a.prepareIndexIfNeededThenExecute(<generated>)
> 	at org.elasticsearch.xpack.security.authc.ApiKeyService.checkDuplicateApiKeyNameAndCreateApiKey(ApiKeyService.java:220)
> 	at org.elasticsearch.xpack.security.authc.ApiKeyService.createApiKey(ApiKeyService.java:198)
> 	at org.elasticsearch.xpack.security.authc.ApiKeyServiceTests.testStoreApiKey(ApiKeyServiceTests.java:202)
> 	... 37 more
```

Seems to fail for the 1st time.

**Comment by jkakavas** [comment]
I think this failed temporarily because of #46773 and @ywelsch fixed it with https://github.com/elastic/elasticsearch/commit/c235e2065c9a5aa15e89902d09d76b4d17de980d . As such, I'm closing this
