### ISSUE TITLE
Interim Downgrade Issue with Elasticsearch (from 7.3.1 to 6.8.3)

### ISSUE THREAD

**Issue by sanjaysahu-git** [elastic/elasticsearch#46932]
**Elasticsearch version** (`bin/elasticsearch --version`):
Cluster master: `6.8.3`
Only one node upgraded to: ES version 7.3.1
```code
rpm -qa elasticsearch
elasticsearch-7.3.1-1.x86_64
```

**Plugins installed**: [N/A]

**JVM version** (`java -version`):
```code
java -version
openjdk version "11.0.4" 2019-07-16 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.4+11-LTS, mixed mode, sharing)
```

**OS version** (`uname -a` if on a Unix-like system):
```code
uname -a
Linux analytics_01 3.10.0-957.10.1.el7.x86_64 #1 SMP Thu Feb 7 07:12:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:
I have a multi-node cluster with elasticsearch version `6.8.3`. I want to upgrade my cluster to version `7.3.1`. I could successfully upgrade one node (injest) to `7.3`. I tried to rollbacl the upgraded node but elasticsearch throws exception:

`failed to read [id:4, file:/mnt/persistent/elasticsearch/indices/nodes/0/_state/node-4.st]`

**Steps to reproduce**:
 step-0. The cluster (6 injest, 6 data and 6 master-eligible nodes) is on ES version 6.8.3
 1. Before I start upgrading one node, I fixed the indices from “7.0 upgrade assistant”
 2. Upgrade one of the analytics node - (upgrade one node to 7.3 is successful)
 
```code
 GET /http://localhost:9200/
  {
  "name" : "analytics_01",
  "cluster_name" : "analytics-cluster",
  "cluster_uuid" : "T28wyP4-TIWc8Qu2DFWsyg",
  "version" : {
    "number" : "7.3.1",
    "build_flavor" : "default",
    "build_type" : "rpm",
    "build_hash" : "4749ba6",
    "build_date" : "2019-08-19T20:19:25.651794Z",
    "build_snapshot" : false,
    "lucene_version" : "8.1.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
 }
```

3. Now I want to do a rollback (interim) of the upgraded node back to version `6.8.3`. But it fails with the following exception:

**Provide logs (if relevant)**:

```
[2][2019-09-20T11:06:27,762][ERROR][o.e.b.Bootstrap          ] [analytics_01] Exception
org.elasticsearch.ElasticsearchException: java.io.IOException: failed to read [id:4, file:/mnt/persistent/elasticsearch/indices/nodes/0/_state/node-4.st]
        at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:165) ~[elasticsearch-6.8.3.jar:6.8.3]
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestStateWithGeneration(MetaDataStateFormat.java:306) ~[elasticsearch-6.8.3.jar:6.8.3]
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:324) ~[elasticsearch-6.8.3.jar:6.8.3]
        at org.elasticsearch.env.NodeEnvironment.loadOrCreateNodeMetaData(NodeEnvironment.java:417) ~[elasticsearch-6.8.3.jar:6.8.3]
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:305) ~[elasticsearch-6.8.3.jar:6.8.3]
        at org.elasticsearch.node.Node.<init>(Node.java:296) ~[elasticsearch-6.8.3.jar:6.8.3]
        at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.3.jar:6.8.3]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.3.jar:6.8.3]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.3.jar:6.8.3]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) [elasticsearch-6.8.3.jar:6.8.3]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-6.8.3.jar:6.8.3]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-6.8.3.jar:6.8.3]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.8.3.jar:6.8.3]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.8.3.jar:6.8.3]
        at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.8.3.jar:6.8.3]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) [elasticsearch-6.8.3.jar:6.8.3]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.8.3.jar:6.8.3]
Caused by: java.io.IOException: failed to read [id:4, file:/mnt/persistent/elasticsearch/indices/nodes/0/_state/node-4.st]
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestStateWithGeneration(MetaDataStateFormat.java:300) ~[elasticsearch-6.8.3.jar:6.8.3]
        ... 15 more
Caused by: org.elasticsearch.common.xcontent.XContentParseException: [-1:36] [node_meta_data] unknown field [node_version], parser not found
        at org.elasticsearch.common.xcontent.ObjectParser.getParser(ObjectParser.java:369) ~[elasticsearch-x-content-6.8.3.jar:6.8.3]
        at org.elasticsearch.common.xcontent.ObjectParser.parse(ObjectParser.java:158) ~[elasticsearch-x-content-6.8.3.jar:6.8.3]
        at org.elasticsearch.common.xcontent.ObjectParser.apply(ObjectParser.java:182) ~[elasticsearch-x-content-6.8.3.jar:6.8.3]
        at org.elasticsearch.env.NodeMetaData$1.fromXContent(NodeMetaData.java:110) ~[elasticsearch-6.8.3.jar:6.8.3]
        at org.elasticsearch.env.NodeMetaData$1.fromXContent(NodeMetaData.java:94) ~[elasticsearch-6.8.3.jar:6.8.3]
        at org.elasticsearch.gateway.MetaDataStateFormat.read(MetaDataStateFormat.java:197) ~[elasticsearch-6.8.3.jar:6.8.3]
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestStateWithGeneration(MetaDataStateFormat.java:296) ~[elasticsearch-6.8.3.jar:6.8.3]
        ... 15 more

```

**Location of the node-4.st (attached)**

```
[root@analytics_01 _state]# pwd
/mnt/persistent/elasticsearch/indices/nodes/0/_state
[root@analytics_01 _state]# ls -tlr
total 116
-rw-r--r--. 1 elasticsearch elasticsearch     89 Sep 20 10:39 node-4.st
-rw-r--r--. 1 elasticsearch elasticsearch 106737 Sep 20 10:54 global-39.st
-rw-r--r--. 1 elasticsearch elasticsearch   4083 Sep 20 10:54 manifest-11.st
```

[node-4.zip](https://github.com/elastic/elasticsearch/files/3636577/node-4.zip)

**Comment by jasontedor** [comment]
Sorry, but downgrades are simply not supported. We make no attempt to make the cluster state and other on-disk metadata forward compatible, and we think that doing so would be dangerous (since in some cases it would entail a loss of information). If you need to downgrade, you should restore from a snapshot. From our [docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/setup-upgrade.html):

> [Back up your data!](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/modules-snapshots.html) You must have a snapshot of your data to roll back to an earlier version.
