### ISSUE TITLE
ClusterShardLimitIT.testIndexCreationOverLimitFromTemplate failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#47107]
fails regularly on all active branches

```
junit.framework.AssertionFailedError: Expected exception IllegalArgumentException but no exception was thrown
        at __randomizedtesting.SeedInfo.seed([62DFAF52204E17E9:D84223E9F73D64A2]:0)
        at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2726)
        at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2711)
        at org.elasticsearch.cluster.shards.ClusterShardLimitIT.testIndexCreationOverLimitFromTemplate(ClusterShardLimitIT.java:144)
REPRODUCE WITH: ./gradlew ':server:integTest' --tests "org.elasticsearch.cluster.shards.ClusterShardLimitIT.testIndexCreationOverLimitFromTemplate" -Dtests.seed=62DFAF52204E17E9 -Dtests.security.manager=true -Dtests.locale=ar-YE -Dtests.timezone=America/El_Salvador -Dcompiler.java=12 -Druntime.java=8
```

Build scan: https://gradle-enterprise.elastic.co/s/cotrw72nsi35q

**Comment by ywelsch** [comment]
I've muted this test on all branches from 7.3 to master
