### ISSUE TITLE
AzureBlobStoreRepositoryTests.testMultipleSnapshotAndRollback failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#47120]
A NullpointerException in the SDK

```
1> Caused by: java.io.IOException: Can not write blob __sp4a6K8pRL6XeEOszzlrNw
  1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:104) ~[main/:?]
  1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.snapshotFile(BlobStoreRepository.java:1343) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository$2.doRun(BlobStoreRepository.java:1105) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	... 5 more
  1> Caused by: com.microsoft.azure.storage.StorageException: Internal Server Error
  1> 	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87) ~[azure-storage-8.4.0.jar:?]
  1> 	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:220) ~[azure-storage-8.4.0.jar:?]
  1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:1035) ~[azure-storage-8.4.0.jar:?]
  1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:864) ~[azure-storage-8.4.0.jar:?]
  1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:743) ~[azure-storage-8.4.0.jar:?]
  1> 	at org.elasticsearch.repositories.azure.AzureStorageService.lambda$writeBlob$15(AzureStorageService.java:332) ~[main/:?]
  1> 	at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:64) ~[main/:?]
  1> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
  1> 	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:63) ~[main/:?]
  1> 	at org.elasticsearch.repositories.azure.AzureStorageService.writeBlob(AzureStorageService.java:331) ~[main/:?]
  1> 	at org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:120) ~[main/:?]
  1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:102) ~[main/:?]
  1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.snapshotFile(BlobStoreRepository.java:1343) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository$2.doRun(BlobStoreRepository.java:1105) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	... 5 more
  1> Caused by: java.lang.NullPointerException
  1> 	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:202) ~[azure-storage-8.4.0.jar:?]
  1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:1035) ~[azure-storage-8.4.0.jar:?]
  1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:864) ~[azure-storage-8.4.0.jar:?]
  1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:743) ~[azure-storage-8.4.0.jar:?]
  1> 	at org.elasticsearch.repositories.azure.AzureStorageService.lambda$writeBlob$15(AzureStorageService.java:332) ~[main/:?]
  1> 	at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:64) ~[main/:?]
  1> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
  1> 	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:63) ~[main/:?]
  1> 	at org.elasticsearch.repositories.azure.AzureStorageService.writeBlob(AzureStorageService.java:331) ~[main/:?]
  1> 	at org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:120) ~[main/:?]
  1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:102) ~[main/:?]
  1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.snapshotFile(BlobStoreRepository.java:1343) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRep
```

Build scan: https://gradle-enterprise.elastic.co/s/43fhrshn37tsc

**Comment by tlrx** [comment]
This failed again on 7.5:
https://gradle-enterprise.elastic.co/s/guxpi3sxg6sm2
https://gradle-enterprise.elastic.co/s/jw7r4xc6mmwbe/tests/lgycqkw2bfw46-clvf2uhrzpiw4

**Comment by mark-vieira** [comment]
I encountered another instance of this on 7.x:

https://gradle-enterprise.elastic.co/s/42cmniylhr7g4/tests/lgycqkw2bfw46-clvf2uhrzpiw4

**Comment by tlrx** [comment]
Thanks @mark-vieira. The failure you mentioned is a bit different from the original one, so I'm closing this in favor of #48978
