### ISSUE TITLE
JvmOptionsParser - cannot resolve enviroment variables

### ISSUE THREAD

**Issue by jetnet** [elastic/elasticsearch#47133]
Version: **ES 7.3.2**
OS: **CentOS Linux release 7.6.1810 (Core)**

Change the path to `gc.log` in `jvm.options`:
```
9-:-Xlog:gc*,gc+age=trace,safepoint:file=${ES_TMPDIR}/gc.log:utctime,pid,tags:filecount=32,filesize=64m
```

ES cannot start:
```
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:
[0.000s][error][logging] Error opening log file '${ES_TMPDIR}/gc.log': No such file or directory
[0.000s][error][logging] Initialization of output 'file=${ES_TMPDIR}/gc.log' using options 'filecount=32,filesize=64m' failed.
error:
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=${ES_TMPDIR}/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
        at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
        at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
        at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)
```

**Comment by ebadyano** [comment]
I was able to reproduce the issue. Interestingly, it works with ES 7.1.0 but not with ES 7.2.0.

**Comment by ebadyano** [comment]
Seems to be related to this https://github.com/elastic/elasticsearch/pull/41962 and might be intentional. 

@jasontedor Was this intentional effect of the PR that ENV variables wont be parsed anymore?

**Comment by jasontedor** [comment]
No, that wasn't intentional. It's happening because we don't make the substitutions before starting the ergonomics JVM. I think we should solve this with an idea I've had for awhile, which is to move the substitution into the JVM options parser itself. I opened #47189 as a draft for feedback on the idea (it's a draft because it needs tests, and I haven't tested whether or not I even have the Windows implementation right).
