### ISSUE TITLE
[CI] UpdateSettingsRequestStreamableTests failure

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#47174]
Reproduces locally (on `6.8`!) :

```
./gradlew ':server:unitTest' -Dtests.seed=AE2F43E23B73AF41 -Dtests.class=org.elasticsearch.action.admin.indices.settings.put.UpdateSettingsRequestStreamableTests -Dtests.method="testEqualsAndHashcode" -Dtests.security.manager=true -Dtests.locale=lt-LT -Dtests.timezone=Europe/Uzhgorod -Dcompiler.java=12 -Druntime.java=8
```

fails with:

```
Dtests.locale=lt-LT -Dtests.timezone=Europe/Uzhgorod -Dcompiler.java=12 -Druntime.java=8
13:36:23 FAILURE 0.05s J9  | UpdateSettingsRequestStreamableTests.testEqualsAndHashcode <<< FAILURES!
13:36:23    > Throwable #1: java.lang.AssertionError: UpdateSettingsRequest mutation should not be equal to original
13:36:23    > Expected: not <indices : [index-ipta],{"EjlL":{"rNh":{"sGc":"FBL"}}}>
13:36:23    >      but: was <indices : [index-ipta],{"EjlL":{"rNh":{"sGc":"FBL"}}}>
13:36:23    > 	at __randomizedtesting.SeedInfo.seed([AE2F43E23B73AF41:DF203B2FF494E66E]:0)
13:36:23    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
13:36:23    > 	at org.elasticsearch.test.EqualsHashCodeTestUtils.checkEqualsAndHashCode(EqualsHashCodeTestUtils.java:82)
13:36:23    > 	at org.elasticsearch.test.AbstractWireTestCase.testEqualsAndHashcode(AbstractWireTestCase.java:61)
13:36:23    > 	at java.lang.Thread.run(Thread.java:748)
```

I could not find the test on new branches, might have been renamed.

**Comment by rjernst** [comment]
This was fixed several months ago in master/7.x with #39386, but never backported to 6.8. I pushed 85ed4566d76.
