### ISSUE TITLE
Updating the index causes an error with JS

### ISSUE THREAD

**Issue by farhan711** [elastic/elasticsearch#47216]
**Elasticsearch version** (`bin/elasticsearch --version`): "7.3.2",

**Plugins installed**:  NO,

**JVM version** (`java -version`): 1.8.0

**OS version** (`uname -a` if on a Unix-like system): MAC/unix

**Description of the problem including expected versus actual behavior**:  While updating the index in ES JavaScript API, occurring an error ```'[x_content_parse_exception] [1:2] [UpdateRequest] unknown field [id], parser not found'```
 Seems like something is missing. 
```try {
        const result = await client.update({
            index: "newtestdata", //constants.searchIndexes.project,
            type: "_doc",
            id: project.id.toString.toString(),
            refresh: true,
            body: project,
         });
         return result;
    }
    catch (e) {
        console.log(e);
    }``` 
So here if I add ```body: { doc: project} ``` it works fine but again in update it create new entries rather than altering the existing one.


**Steps to reproduce**: update using any JS API and will occur an error 
```{ Error: [x_content_parse_exception] [1:2] [UpdateRequest] unknown field [id], parser not found
    at respond (/Users/farhanansari/Documents/aws-pt-ftm-api/node_modules/elasticsearch/src/lib/transport.js:349:15)
    at checkRespForFailure (/Users/farhanansari/Documents/aws-pt-ftm-api/node_modules/elasticsearch/src/lib/transport.js:306:7)
    at HttpConnector.<anonymous> (/Users/farhanansari/Documents/aws-pt-ftm-api/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
    at IncomingMessage.wrapper (/Users/farhanansari/Documents/aws-pt-ftm-api/node_modules/lodash/lodash.js:4929:19)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 400,
  displayName: 'BadRequest',
  message:
   '[x_content_parse_exception] [1:2] [UpdateRequest] unknown field [id], parser not found',
  path: '/newtestdata1/_update/5d8e0ba2645806a99f5eb3d7',
  query: { type: '_doc', refresh: 'true' },
  body:
   { error:
      { root_cause: [Array],
        type: 'x_content_parse_exception',
        reason: '[1:2] [UpdateRequest] unknown field [id], parser not found' },
     status: 400 },
  statusCode: 400,
  response:
   '{"error":{"root_cause":[{"type":"x_content_parse_exception","reason":"[1:2] [UpdateRequest] unknown field [id], parser not found"}],"type":"x_content_parse_exception","reason":"[1:2] [UpdateRequest] unknown field [id], parser not found"},"status":400}',
  toString: [Function],
  toJSON: [Function] }
```

**Comment by dnhatn** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
