### ISSUE TITLE
Rest High Level Client GraalVM support

### ISSUE THREAD

**Issue by Strum355** [elastic/elasticsearch#47245]
Using the Rest High Level Client with GraalVM native image generation gives the following stacktrace at runtime. Is there any chance of seeing GraalVM native image support or are there any known workarounds?
```
Exception in thread "DefaultDispatcher-worker-2" com.oracle.svm.core.jdk.UnsupportedFeatureError: ObjectOutputStream.writeObject()
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:102)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:69)
        at org.apache.http.impl.client.BasicAuthCache.put(BasicAuthCache.java:107)
        at org.elasticsearch.client.RestClient.setNodes(RestClient.java:163)
        at org.elasticsearch.client.RestClient.<init>(RestClient.java:119)
        at org.elasticsearch.client.RestClientBuilder.build(RestClientBuilder.java:191)
        at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:274)
        at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:266)
        at xyz.noahsc.topology.AppKt.module(App.kt:43)
        at xyz.noahsc.topology.AppKt$main$server$1.invoke(App.kt:35)
        at xyz.noahsc.topology.AppKt$main$server$1.invoke(App.kt)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:293)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:137)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:257)
        at io.ktor.server.cio.CIOApplicationEngine$serverJob$1$1.invokeSuspend(CIOApplicationEngine.kt:52)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

**Comment by spinscale** [comment]
See https://github.com/oracle/graal/issues/460 - this is a limitation of graalvm at the moment, so there is not much that can be done on the elasticsearch side of things here.
