### ISSUE TITLE
Debian 10 - xpack.ml.enabled: false - elasticsearch does not start

### ISSUE THREAD

**Issue by tstoco** [elastic/elasticsearch#47265]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 7.3.2

**Plugins installed**: N/A default installation 

**JVM version** (`java -version`):

openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Debian-1deb10u1, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):
Linux WS-SVR1-HOME 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

elasticsearch does not start and in the logs it is saying : 

Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory. To bypass this problem by running Elasticsearch without machine learning functionality set [xpack.ml.enabled: false].]

**Steps to reproduce**:

1 - Install ElasticSearch as instructed by the official documentation.
2 - Start ElasticSearch using /etc/init.d/elasticsearch start

**Provide logs (if relevant)**:
```

root@WS-SVR1-HOME:/etc/elasticsearch# cat elasticsearch.yml
# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
#cluster.name: my-application
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
#node.name: node-1
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
path.data: /var/lib/elasticsearch
#
# Path to log files:
#
path.logs: /var/log/elasticsearch
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
#network.host: 192.168.0.1
#
# Set a custom port for HTTP:
#
#http.port: 9200
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when this node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#discovery.seed_hosts: ["host1", "host2"]
#
# Bootstrap the cluster using an initial set of master-eligible nodes:
#
#cluster.initial_master_nodes: ["node-1", "node-2"]
#
# For more information, consult the discovery and cluster formation module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
bootstrap.memory_lock: true
#cluster.name: fsmonitoring
#discovery:
#    zen:
#        minimum_master_nodes: 1
#        ping.unicast.hosts: backend-plugins:9300
http.port: 9200
network.host: 192.168.10.10
#node:
#    data: false
#    ingest: false
#    master: true
#node.name: master
#transport.tcp.port: 9300




#################################### Paths ####################################

# Path to directory containing configuration (this file and logging.yml):

xpack.security.enabled: false

xpack.watcher.enabled: false

xpack.ml.enabled: false

xpack.graph.enabled: false

```

elasticsearch logs :

```
[2019-09-28T14:44:14,259][INFO ][o.e.e.NodeEnvironment    ] [WS-SVR1-HOME] using [1] data paths, mounts [[/ (/dev/sda1)]], net usable_space [10.3gb], net total_space [16.2gb], types [ext4]
[2019-09-28T14:44:14,271][INFO ][o.e.e.NodeEnvironment    ] [WS-SVR1-HOME] heap size [1007.3mb], compressed ordinary object pointers [true]
[2019-09-28T14:44:14,284][INFO ][o.e.n.Node               ] [WS-SVR1-HOME] node name [WS-SVR1-HOME], node ID [N5BhVuxcRg69GLZyREhKFQ], cluster name [elasticsearch]
[2019-09-28T14:44:14,285][INFO ][o.e.n.Node               ] [WS-SVR1-HOME] version[7.3.2], pid[5799], build[default/deb/1c1faf1/2019-09-06T14:40:30.409026Z], OS[Linux/4.19.0-5-amd64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/12.0.2/12.0.2+10]
[2019-09-28T14:44:14,286][INFO ][o.e.n.Node               ] [WS-SVR1-HOME] JVM home [/usr/share/elasticsearch/jdk]
[2019-09-28T14:44:14,287][INFO ][o.e.n.Node               ] [WS-SVR1-HOME] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch-14455953153394537060, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/var/lib/elasticsearch, -XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -Dio.netty.allocator.type=unpooled, -XX:MaxDirectMemorySize=536870912, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/etc/elasticsearch, -Des.distribution.flavor=default, -Des.distribution.type=deb, -Des.bundled_jdk=true]
[2019-09-28T14:44:23,657][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [aggs-matrix-stats]
[2019-09-28T14:44:23,660][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [analysis-common]
[2019-09-28T14:44:23,662][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [data-frame]
[2019-09-28T14:44:23,666][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [flattened]
[2019-09-28T14:44:23,666][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [ingest-common]
[2019-09-28T14:44:23,667][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [ingest-geoip]
[2019-09-28T14:44:23,668][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [ingest-user-agent]
[2019-09-28T14:44:23,669][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [lang-expression]
[2019-09-28T14:44:23,672][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [lang-mustache]
[2019-09-28T14:44:23,674][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [lang-painless]
[2019-09-28T14:44:23,676][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [mapper-extras]
[2019-09-28T14:44:23,677][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [parent-join]
[2019-09-28T14:44:23,678][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [percolator]
[2019-09-28T14:44:23,679][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [rank-eval]
[2019-09-28T14:44:23,681][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [reindex]
[2019-09-28T14:44:23,682][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [repository-url]
[2019-09-28T14:44:23,683][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [transport-netty4]
[2019-09-28T14:44:23,683][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [vectors]
[2019-09-28T14:44:23,684][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [x-pack-ccr]
[2019-09-28T14:44:23,687][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [x-pack-core]
[2019-09-28T14:44:23,689][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [x-pack-deprecation]
[2019-09-28T14:44:23,690][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [x-pack-graph]
[2019-09-28T14:44:23,693][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [x-pack-ilm]
[2019-09-28T14:44:23,695][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [x-pack-logstash]
[2019-09-28T14:44:23,698][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [x-pack-ml]
[2019-09-28T14:44:23,699][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [x-pack-monitoring]
[2019-09-28T14:44:23,702][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [x-pack-rollup]
[2019-09-28T14:44:23,703][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [x-pack-security]
[2019-09-28T14:44:23,705][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [x-pack-sql]
[2019-09-28T14:44:23,706][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [x-pack-voting-only-node]
[2019-09-28T14:44:23,706][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] loaded module [x-pack-watcher]
[2019-09-28T14:44:23,710][INFO ][o.e.p.PluginsService     ] [WS-SVR1-HOME] no plugins loaded
[2019-09-28T14:44:43,139][INFO ][o.e.x.s.a.s.FileRolesStore] [WS-SVR1-HOME] parsed [0] roles from file [/etc/elasticsearch/roles.yml]
[2019-09-28T14:44:56,410][ERROR][o.e.b.Bootstrap          ] [WS-SVR1-HOME] Exception
org.elasticsearch.ElasticsearchException: Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory. To bypass this problem by running Elasticsearch without machine learning functionality set [xpack.ml.enabled: false].
        at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLearning.java:497) ~[?:?]
        at org.elasticsearch.node.Node.lambda$new$9(Node.java:457) ~[elasticsearch-7.3.2.jar:7.3.2]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at org.elasticsearch.node.Node.<init>(Node.java:460) ~[elasticsearch-7.3.2.jar:7.3.2]
        at org.elasticsearch.node.Node.<init>(Node.java:258) ~[elasticsearch-7.3.2.jar:7.3.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.3.2.jar:7.3.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.3.2.jar:7.3.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) [elasticsearch-7.3.2.jar:7.3.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-7.3.2.jar:7.3.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-7.3.2.jar:7.3.2]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-7.3.2.jar:7.3.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-7.3.2.jar:7.3.2]
        at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-7.3.2.jar:7.3.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) [elasticsearch-7.3.2.jar:7.3.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-7.3.2.jar:7.3.2]
[2019-09-28T14:44:56,466][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [WS-SVR1-HOME] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory. To bypass this problem by running Elasticsearch without machine learning functionality set [xpack.ml.enabled: false].]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.3.2.jar:7.3.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.3.2.jar:7.3.2]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.3.2.jar:7.3.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-7.3.2.jar:7.3.2]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.3.2.jar:7.3.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.3.2.jar:7.3.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.3.2.jar:7.3.2]
Caused by: org.elasticsearch.ElasticsearchException: Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory. To bypass this problem by running Elasticsearch without machine learning functionality set [xpack.ml.enabled: false].
        at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLearning.java:497) ~[?:?]
        at org.elasticsearch.node.Node.lambda$new$9(Node.java:457) ~[elasticsearch-7.3.2.jar:7.3.2]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at org.elasticsearch.node.Node.<init>(Node.java:460) ~[elasticsearch-7.3.2.jar:7.3.2]
        at org.elasticsearch.node.Node.<init>(Node.java:258) ~[elasticsearch-7.3.2.jar:7.3.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.3.2.jar:7.3.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.3.2.jar:7.3.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.3.2.jar:7.3.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.3.2.jar:7.3.2]
        ... 6 more

```

**Comment by tstoco** [comment]
The issue has been resolved removing spaces from the configuration file, since it is YAML and indentation is very important.

root@WS-SVR1-HOME:/etc/elasticsearch# curl -G http://localhost:9200
{
  "name" : "WS-SVR1-HOME",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "yQrFSzXNSuKo8kYJWmZQUg",
  "version" : {
    "number" : "7.3.2",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "1c1faf1",
    "build_date" : "2019-09-06T14:40:30.409026Z",
    "build_snapshot" : false,
    "lucene_version" : "8.1.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
