### ISSUE TITLE
PluginBuildPluginTests fails on Mac

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#47417]
This test was failing for me locally and not in CI, but turns out it's failing in our Darwin CI builds as well:

https://gradle-enterprise.elastic.co/s/t3qxgarzcyfls

Something about the randomized runner thread leak detection is tripping only on OSX. We might want to reevaluate whether we want to use any of the randomized runner stuff in `buildSrc` tests at all. We aren't actually using any of the random input capabilities, and I suspect this is just copy/paste from the regular ES code.

**Comment by mark-vieira** [comment]
pinging @atorok

**Comment by atorok** [comment]
```
3 threads leaked from TEST scope at testApply(org.elasticsearch.gradle.plugin.PluginBuildPluginTests): 
   1) Thread[id=26, name=Exec process Thread 3, state=TIMED_WAITING, group=TGRP-PluginBuildPluginTests]
        at java.base@12.0.2/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@12.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:235)
        at java.base@12.0.2/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462)
        at java.base@12.0.2/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
        at java.base@12.0.2/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
        at java.base@12.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
        at java.base@12.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
        at java.base@12.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at app//org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base@12.0.2/java.lang.Thread.run(Thread.java:835)
   2) Thread[id=25, name=Exec process Thread 2, state=TIMED_WAITING, group=TGRP-PluginBuildPluginTests]
        at java.base@12.0.2/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@12.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:235)
        at java.base@12.0.2/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462)
        at java.base@12.0.2/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
        at java.base@12.0.2/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
        at java.base@12.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
        at java.base@12.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
        at java.base@12.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at app//org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base@12.0.2/java.lang.Thread.run(Thread.java:835)
   3) Thread[id=22, name=Exec process, state=TIMED_WAITING, group=TGRP-PluginBuildPluginTests]
        at java.base@12.0.2/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@12.0.2/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:235)
        at java.base@12.0.2/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462)
        at java.base@12.0.2/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
        at java.base@12.0.2/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
        at java.base@12.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
        at java.base@12.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
        at java.base@12.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at app//org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base@12.0.2/java.lang.Thread.run(Thread.java:835)
```

I don't think we are creating Mac specific threads, so these must be leaked by Gradle. 
I'm going to turn off the check for this test.

The randomized runner has a few other features than generating predictable  pseudo random test inputs, we run with this runner for consistency with other projects.

**Comment by mark-vieira** [comment]
Looks good. Do you intend on opening a PR for that?

**Comment by atorok** [comment]
Yes, sorry I taught I did :)
