### ISSUE TITLE
SharedClusterSnapshotRestoreIT#testDeleteSnapshot fails

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#47425]
This intake build failed:

https://gradle-enterprise.elastic.co/s/svccgf6bmse26/console-log?task=:server:integTest

```
org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT > testDeleteSnapshot FAILED
    java.lang.AssertionError: 
    Expected: <83>
         but: was <84>
        at __randomizedtesting.SeedInfo.seed([7B6539B7AA32C965:2D8F03FC8B34B1E7]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.testDeleteSnapshot(SharedClusterSnapshotRestoreIT.java:1328)
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
REPRODUCE WITH: ./gradlew ':server:integTest' --tests "org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.testDeleteSnapshot" -Dtests.seed=7B6539B7AA32C965 -Dtests.security.manager=true -Dtests.locale=en-PR -Dtests.timezone=America/Curacao -Dcompiler.java=12 -Druntime.java=11
```

The `REPRODUCE WITH` line does not reproduce for me.

**Comment by original-brownbear** [comment]
I can reproduce this after ~1k runs in a loop with the test seed. -> fixing it :)

**Comment by original-brownbear** [comment]
Fix incoming in https://github.com/elastic/elasticsearch/pull/47445 ... this was accidentally caused by #47283
