### ISSUE TITLE
[CI] Failure in IndexShardIT.testLimitNumberOfRetainingTranslogFiles

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#47597]
Failed here: https://gradle-enterprise.elastic.co/s/yuhmzv3kj4gui/tests/kyv2y2z3r4v7m-g6yb5sqhunn32

```

2> REPRODUCE WITH: ./gradlew ':server:integTest' --tests "org.elasticsearch.index.shard.IndexShardIT.testLimitNumberOfRetainingTranslogFiles" -Dtests.seed=EC6B3731FFAEFFA0 -Dtests.security.manager=true -Dtests.locale=fur -Dtests.timezone=Europe/Guernsey -Dcompiler.java=12 -Druntime.java=11
--
2> java.lang.AssertionError:
Expected: (a value less than or equal to <1L> or <1L>)
but: was <2L>
at __randomizedtesting.SeedInfo.seed([EC6B3731FFAEFFA0:3F2381C9DF9A0D9F]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.index.shard.IndexShardIT.lambda$testLimitNumberOfRetainingTranslogFiles$23(IndexShardIT.java:878)
at org.elasticsearch.index.shard.IndexShardIT.testLimitNumberOfRetainingTranslogFiles(IndexShardIT.java:892)

```

**Comment by dnhatn** [comment]
Relates to #47414

**Comment by dnhatn** [comment]
Fixed in https://github.com/elastic/elasticsearch/pull/47879.
