### ISSUE TITLE
Enhance logging for slow nodes in query phase

### ISSUE THREAD

**Issue by Bukhtawar** [elastic/elasticsearch#47646]
### Problem Description

Currently if there is a node suffering from slow network or long GC pause it might potentially delay response from the query phase upto 5 minutes causing the fetch phase to fail with `SearchContextMissingException` with the below stack trace which points to a remote host where fetch failed due to the Reaper removing the context. 
There however is no information about which culprit node actually delayed the response for the query phase leading to this problem.

```
[2019-10-02T08:29:25,049][DEBUG][o.e.a.s.TransportSearchAction] [w0EOtb8] #[org.elasticsearch.transport.RemoteTransportException,org.elasticsearch.search.SearchContextMissingException]#[21208660] Failed to execute fetch phase
org.elasticsearch.transport.RemoteTransportException: [_HK9U3l][10.xxx.xx.xx:9300][indices:data/read/search[phase/fetch/id]]
Caused by: org.elasticsearch.search.SearchContextMissingException: No search context found for id [21208660]
	at org.elasticsearch.search.SearchService.findContext(SearchService.java:537) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:504) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.action.search.SearchTransportService$11.messageReceived(SearchTransportService.java:439) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.action.search.SearchTransportService$11.messageReceived(SearchTransportService.java:436) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1605) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.4.2.jar:6.4.2]
```

It would be better if the co-ordinator started to log slow responses(configurable threshold) from the query phase

**Comment by Bukhtawar** [comment]
Also since the fetch phase is not prioritized over query there is a possibility that if a node has a baclog of query fetch phase might get delayed leading to this @martijnvg

**Comment by javanna** [comment]
There are no plans around this, closing for now.
