### ISSUE TITLE
Centos7 SimpleFSIndexInput error when installing 7.3.2

### ISSUE THREAD

**Issue by TuulaP** [elastic/elasticsearch#47771]
**Elasticsearch version** : 7.3.2 

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):
3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

`more /etc/centos-release`
CentOS Linux release 7.7.1908 (Core)

**Description of the problem including expected versus actual behavior**:

Tried installing ElasticSearch 7.3.2 with this command

`sudo rpm -ivh elasticsearch-7.3.2-x86_64.rpm`

Actual behavior:

At the end got this kind of error:

```

Preparing...                          ################################# [100%]
Creating elasticsearch group... OK
Creating elasticsearch user... OK
Updating / installing...
   1:elasticsearch-0:7.3.2-1          ################################# [100%]
### NOT starting on installation, please execute the following statements to configure elasticsearch service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable elasticsearch.service
### You can start elasticsearch service by executing
 sudo systemctl start elasticsearch.service
Exception in thread "main" java.io.EOFException: read past EOF: SimpleFSIndexInput(path="/etc/elasticsearch/elasticsearch.keystore")
        at org.apache.lucene.store.BufferedIndexInput.refill(BufferedIndexInput.java:336)
        at org.apache.lucene.store.BufferedIndexInput.readByte(BufferedIndexInput.java:54)
        at org.apache.lucene.store.BufferedChecksumIndexInput.readByte(BufferedChecksumIndexInput.java:41)
        at org.apache.lucene.store.DataInput.readInt(DataInput.java:101)
        at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:194)
        at org.elasticsearch.common.settings.KeyStoreWrapper.load(KeyStoreWrapper.java:220)
        at org.elasticsearch.common.settings.UpgradeKeyStoreCommand.execute(UpgradeKeyStoreCommand.java:40)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:41)
warning: %posttrans(elasticsearch-0:7.3.2-1.x86_64) scriptlet failed, exit status 1

```

(we didn't have that keystore file earlier, so should it exist as a empty file and with which rights?)

**Steps to reproduce**:

 1.  sudo rpm -ivh elasticsearch-7.3.2-x86_64.rpm
 2.
 3.

(although we did have earlier version of elasticsearch installed, but that I did uninstall with `sudo yum remove elasticsearch` before attempting to install this newer version, but it might have left some directories with wrong permissions.)

It seems that finally elasticsearch service did start up, but I had to change the rights of the /etc/elasticsearch to let it create the keystore there.

**Comment by Natteke** [comment]
Why this tread is closed with no info?
Issue still exist in 7.8.1
