### ISSUE TITLE
[CI] XPackRestIT security/authz/14_cat_indices fails intermittently 

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#47875]
It fails on my CI machine pretty frequently, but I wasn't able to reproduce it outside of my CI environment and it didn't fail in our official CI before, but now it started to fail there as well. I have never seen it failing alone in master. It typically fails in 7.x.

The latest failure:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=opensuse-15-1&&immutable/315/console

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:integTestRunner' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=security/authz/14_cat_indices/Test empty request while single authorized closed index}" \
  -Dtests.seed=CCDF98BFD559EA77 \
  -Dtests.security.manager=true \
  -Dtests.locale=en-GB \
  -Dtests.timezone=Portugal \
  -Dcompiler.java=12 \
  -Druntime.java=8 \
  -Dtests.rest.blacklist=getting_started/10_monitor_cluster_health/*
```
The failure stack:

```
java.lang.AssertionError: Failure at [security/authz/14_cat_indices:154]: field [$body] was expected to match the provided regex but didn't
Expected: ^(yellow  \s+
   close   \s+
   index_to_monitor \s+
   ([a-zA-Z0-9=/_+]|[\\\-]){22} \s+
   1      \s+
   1      \s+
          \s+
          \s+
          \s+
          \s*
 )
 $
     but: was "red close index_to_monitor 80-7OxlvRHeL2gOm-moofg 1 1    \n"
	at __randomizedtesting.SeedInfo.seed([CCDF98BFD559EA77:448BA7657BA5878F]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:400)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:377)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: field [$body] was expected to match the provided regex but didn't
Expected: ^(yellow  \s+
   close   \s+
   index_to_monitor \s+
   ([a-zA-Z0-9=/_+]|[\\\-]){22} \s+
   1      \s+
   1      \s+
          \s+
          \s+
          \s+
          \s*
 )
 $
     but: was "red close index_to_monitor 80-7OxlvRHeL2gOm-moofg 1 1    \n"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:68)
	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:393)
	... 37 more
```

**Comment by jakelandis** [comment]
I have run this 100+ times and can not reproduce the failure. The original error was logged 3+ years ago and seems to be a case of a red vs. yellow index which can fail the test is but not what the test is testing for.  I will unmute this test in master. 
```
while ./gradlew :x-pack:plugin:yamlRestTest -Dtests.method="test {p0=security/authz/*}" --no-scan -Dtests.timestamp=$(date +%S); do        let i+=1          ;      echo "$i: $(date  +%D::%HH:%MM)";  done 
```

**Comment by gmarouli** [comment]
I just got one more occurrence of this: https://gradle-enterprise.elastic.co/s/45byngzrdmfpw/tests/task/:x-pack:plugin:yamlRestTest/details/org.elasticsearch.xpack.test.rest.XPackRestIT/test%20%7Bp0=security%2Fauthz%2F14_cat_indices%2FTest%20empty%20request%20while%20single%20authorized%20closed%20index%7D?top-execution=1

**Comment by jakelandis** [comment]
I took a look at the latest failure and it is slightly different than the failure reported originally. In the most recent failure (I can not reproduce):

The test expects:

```
yellow close index_to_monitor sssNeIfPRi2J_2fMW1-POA 1 1     
```

but finds:

```
yellow close index_to_monitor sssNeIfPRi2J_2fMW1 1 1 0 0 0b 0b 0b
```

If displayed in verbose mode these are the extra bits that cause the failure (the test expects these be omitted from the response):
```
docs.count docs.deleted store.size pri.store.size dataset.size
0          0            0b         0b             0b
```

The test is trying to assert that due to security, you will only see the `index_to_monitor`. So it is possible to adjust the regex used in the test to ignore those extra bits and still honor the intention of the test. However, I am hesitant to do that since we could be masking over a possible issue with the cat API. 

@elastic/es-data-management - Do you have any ideas to why sometimes the output of the cat API for a recently closed index would some times omit the values and other times (seemingly rarely) report 0 values ?

**Comment by gmarouli** [comment]
I cannot reproduce it locally either, but it does fail in CI for branch a lot which is very confusing.

**Comment by gmarouli** [comment]
This failure appears to be localised to my branch so I will close this issue and investigate it there.
