### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene80' does not exist

### ISSUE THREAD

**Issue by shiyu1992** [elastic/elasticsearch#47892]
**Describe the feature**:
 1.import elasticsearch7.2.0 into IDEA . when running it catch an exception. 

**Elasticsearch version 7.2.0 (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version 12.0.2  (`java -version`):

**OS version  OS Info: Windows 7 6.1 (amd64)
 (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.import elasticsearch7.2.0 into IDEA . when running it catch an exception. 

**Provide logs (if relevant)**:
[2019-10-11T08:44:44,148][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-1] fatal error in thread [main], exiting
java.lang.ExceptionInInitializerError: null
	at org.apache.lucene.codecs.Codec.reloadCodecs(Codec.java:136) ~[lucene-core-8.0.0.jar:8.0.0 2ae4746365c1ee72a0047ced7610b2096e438979 - jimczi - 2019-03-08 11:58:55]
	at org.elasticsearch.plugins.PluginsService.reloadLuceneSPI(PluginsService.java:572) ~[main/:?]
	at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:549) ~[main/:?]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:471) ~[main/:?]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:163) ~[main/:?]
	at org.elasticsearch.node.Node.<init>(Node.java:307) ~[main/:?]
	at org.elasticsearch.node.Node.<init>(Node.java:251) ~[main/:?]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[main/:?]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[main/:?]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[main/:?]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[main/:?]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[main/:?]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[main/:?]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[main/:?]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[main/:?]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[main/:?]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[main/:?]
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene80' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: []
	at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:116) ~[lucene-core-8.0.0.jar:8.0.0 2ae4746365c1ee72a0047ced7610b2096e438979 - jimczi - 2019-03-08 11:58:55]
	at org.apache.lucene.codecs.Codec$Holder.<clinit>(Codec.java:60) ~[lucene-core-8.0.0.jar:8.0.0 2ae4746365c1ee72a0047ced7610b2096e438979 - jimczi - 2019-03-08 11:58:55]
	... 17 more
Process finished with exit code 1

**Comment by romseygeek** [comment]
It sounds as though your classpath is not correctly configured.  Have you followed the steps outlined in https://www.elastic.co/blog/how-to-debug-elasticsearch-source-code-in-intellij-idea to set up your IntelliJ project?

**Comment by shiyu1992** [comment]
shorten command line: none - java [options] classname [args]
