### ISSUE TITLE
ClassificationIT.testWithOnlyTrainingRowsAndTrainingPercentIsFifty failing on master

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#47945]
I noticed this failing on my PR to master. I cannot reproduce this locally
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testWithOnlyTrainingRowsAndTrainingPercentIsFifty" \
  -Dtests.seed=13576940F02D397F \
  -Dtests.security.manager=true \
  -Dtests.locale=bg \
  -Dtests.timezone=America/Chihuahua \
  -Dcompiler.java=12 \
  -Druntime.java=11
```
build stat https://gradle-enterprise.elastic.co/s/elf4ol2d2neio

failure stacktrace
```
Expected: <stopped>
     but: was <analyzing>
Close stacktrace
at __randomizedtesting.SeedInfo.seed([13576940F02D397F:AF7270D0C052EC8A]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.lambda$waitUntilAnalyticsIsStopped$0(MlNativeDataFrameAnalyticsIntegTestCase.java:122)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:867)
at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.waitUntilAnalyticsIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:122)
at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.waitUntilAnalyticsIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:118)
at org.elasticsearch.xpack.ml.integration.ClassificationIT.testWithOnlyTrainingRowsAndTrainingPercentIsFifty(ClassificationIT.java:172)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by tlrx** [comment]
Also failed on 7.x today: https://gradle-enterprise.elastic.co/s/o3ujn4m3da3ce

**Comment by przemekwitek** [comment]
The failures are also visible here:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-6M,mode:quick,to:now))&_a=(columns:!(test.failed-testcases,test.tests,build.build-scans),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'ClassificationIT*'),sort:!(process.time-start,desc))

I'll add more descriptive error messages to help with debugging.

**Comment by iverase** [comment]
There is a failure in 7.5 that seems related:

https://gradle-enterprise.elastic.co/s/gnms3jjvsu4g4

Error is a bit different:

```
java.lang.AssertionError: 
Expected: <1>
     but: was <0>
	at __randomizedtesting.SeedInfo.seed([E437C7FD1FCEDFD8:5812DE6D2FB10A2D]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)

```

**Comment by przemekwitek** [comment]
Pasting longer stack trace which shows which method has failed:
```
org.elasticsearch.xpack.ml.integration.RegressionIT > testWithOnlyTrainingRowsAndTrainingPercentIsFifty FAILED
--
java.lang.AssertionError:
Expected: <1>
but: was <0>
at __randomizedtesting.SeedInfo.seed([E437C7FD1FCEDFD8:5812DE6D2FB10A2D]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.xpack.ml.integration.RegressionIT.assertModelStatePersisted(RegressionIT.java:332)
at org.elasticsearch.xpack.ml.integration.RegressionIT.testWithOnlyTrainingRowsAndTrainingPercentIsFifty(RegressionIT.java:228)
```

The old issue was with `state == failed`. The new issue is different, related somehow to model state persistence.

**Comment by przemekwitek** [comment]
A new failure on 7.x:
```
Build | 20191022055254-E3F46C95
Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+release-tests/489/console
Build Scans | https://gradle-enterprise.elastic.co/s/bhjlk77ykn7cm
```

**Comment by pgomulka** [comment]
failure on master https://gradle-enterprise.elastic.co/s/nq5tm7wkcz63o

**Comment by przemekwitek** [comment]
This issue has accumulated a lot of unrelated failures.
2 out of 3 are already resolved.
The tests got muted in the meantime, and new issue was created.
Let's close this issue and use https://github.com/elastic/elasticsearch/issues/48337.
