### ISSUE TITLE
CI Failures: AzureBlobStoreRepositoryTests.testIndicesDeletedFromRepository

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#47948]
This test has failed periodically (but consistently):

https://groups.google.com/a/elastic.co/forum/#!searchin/build-elasticsearch/AzureBlobStoreRepositoryTests$20testIndicesDeletedFromRepository%7Csort:date

I have not been able to reproduce but (like #47380) it also looks like its coming from the Azure plugin:

```
13:09:53   1> Caused by: com.microsoft.azure.storage.StorageException: An unknown failure occurred : Unexpected end of file from server
13:09:53   1> 	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:67) ~[azure-storage-8.4.0.jar:?]
13:09:53   1> 	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:220) ~[azure-storage-8.4.0.jar:?]
13:09:53   1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:1035) ~[azure-storage-8.4.0.jar:?]
13:09:53   1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:864) ~[azure-storage-8.4.0.jar:?]
13:09:53   1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:743) ~[azure-storage-8.4.0.jar:?]
13:09:53   1> 	at org.elasticsearch.repositories.azure.AzureStorageService.lambda$writeBlob$15(AzureStorageService.java:332) ~[main/:?]
13:09:53   1> 	at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:64) ~[main/:?]
13:09:53   1> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
13:09:53   1> 	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:63) ~[main/:?]
13:09:53   1> 	at org.elasticsearch.repositories.azure.AzureStorageService.writeBlob(AzureStorageService.java:331) ~[main/:?]
13:09:53   1> 	at org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:120) ~[main/:?]
13:09:53   1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:102) ~[main/:?]
13:09:53   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.snapshotFile(BlobStoreRepository.java:1358) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
13:09:53   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository$2.doRun(BlobStoreRepository.java:1115) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
13:09:53   1> 	... 5 more
```

```13:09:53   2> REPRODUCE WITH: ./gradlew ':plugins:repository-azure:test' --tests "org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests.testIndicesDeletedFromRepository" -Dtests.seed=D48C184AD8376ABD -Dtests.security.manager=true -Dtests.locale=lv-LV -Dtests.timezone=Pacific/Pitcairn -Dcompiler.java=12 -Druntime.java=11```

**Comment by tlrx** [comment]
The failure failure is a bit different from the one in this issue. I'm closing again and reopen #47120 instead.
