### ISSUE TITLE
Build failures in :qa:os:centos-7:batsTest in PR builds, maybe vagrant problem

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#47988]
Looks like something with the vagrant process is wrong. Haven't seen this elsewhere recently, but heres the build scan:

https://gradle-enterprise.elastic.co/s/lcwoxhknl3d52/

```
:qa:os:centos-7:batsTest.default FAILED
--
==> centos-7: Checking for updates to 'elastic/centos-7-x86_64'
centos-7: Latest installed version: 20191013.0.0
centos-7: Version constraints:
centos-7: Provider: virtualbox
==> centos-7: Box 'elastic/centos-7-x86_64' (v20191013.0.0) is running the latest version.
Exec output and error:
\| Output for vagrant: INFO global: Vagrant version: 2.2.3
\|  INFO global: Ruby version: 2.4.4
\|  INFO global: RubyGems version: 2.6.14.1
\|  INFO global: VAGRANT_PROJECT_DIR="/var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-sample/qa/os/centos-7"
\|  INFO global: VAGRANT_VAGRANTFILE="Vagrantfile"
\|  INFO global: VAGRANT_LOG="debug"
\|  INFO global: VAGRANT_CWD="/var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-sample"
\|  INFO global: VAGRANT_EXECUTABLE="/opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/bin/vagrant"
\|  INFO global: VAGRANT_INSTALLER_ENV="1"
\|  INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/opt/vagrant/embedded"
\|  INFO global: VAGRANT_INSTALLER_VERSION="2"
\|  WARN global: resolv replacement has not been enabled!
\| DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/commands/list-commands/plugin.rb
\|  INFO manager: Registered plugin: list-commands command
\| DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/commands/up/plugin.rb
\|  INFO manager: Registered plugin: up command
\| DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/commands/box/plugin.rb
\|  INFO manager: Registered plugin: box command
\| DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/commands/rdp/plugin.rb

[...]

\|  INFO manager: Registered plugin: Hyper-V provider
\| DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/providers/docker/plugin.rb
\|  INFO manager: Registered plugin: docker-provider
\|  INFO vagrant: `vagrant` invoked: ["destroy", "centos-7", "--force"]
\| DEBUG vagrant: Creating Vagrant environment
\|  INFO environment: Environment initialized (#<Vagrant::Environment:0x0000000002880228>)
\|  INFO environment:   - cwd: /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-sample
\|  INFO environment: Home path: /var/lib/jenkins/.vagrant.d
\| DEBUG environment: Effective local data path: /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-sample/.vagrant
\|  INFO environment: Local data path: /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-sample/.vagrant
\| DEBUG environment: Creating: /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-sample/.vagrant
\| DEBUG manager: Enabling localized plugins
\|  INFO manager: Plugins:
\| DEBUG bundler: Current generated plugin dependency list: []
\| DEBUG bundler: Generating new builtin set instance.
\| DEBUG bundler: Generating new plugin set instance. Skip gems - []
\| DEBUG bundler: Activating solution set: []
\|  INFO manager: Loading plugins...
\| DEBUG manager: Enabling globalized plugins
\|  INFO manager: Plugins:
\|  INFO manager:   - vagrant-cachier = [installed: 1.2.1 constraint: 1.2.1]
\| DEBUG bundler: Current generated plugin dependency list: [<Gem::Dependency type=:runtime name="vagrant-cachier" requirements="= 1.2.1">]
\| DEBUG bundler: Generating new builtin set instance.
\| DEBUG bundler: Generating new plugin set instance. Skip gems - []
\| DEBUG bundler: Activating solution set: ["vagrant-cachier-1.2.1"]
\| DEBUG bundler: Activating gem vagrant-cachier-1.2.1
\|  INFO manager: Loading plugins...
\|  INFO manager: Loading plugin `vagrant-cachier` with default require: `vagrant-cachier`
\|  INFO manager: Registered plugin: vagrant-cachier
\| DEBUG manager: Successfully loaded plugin `vagrant-cachier`.
\|  INFO loader: Set :root = ["#<Pathname:/var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-sample/Vagrantfile>"]
\| DEBUG loader: Populating proc cache for #<Pathname:/var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-sample/Vagrantfile>
\| DEBUG loader: Load procs for pathname: /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-sample/Vagrantfile
\|  INFO loader: Loading configuration in order: [:home, :root]
\| DEBUG loader: Loading from: root (evaluating)
\| DEBUG loader: Configuration loaded successfully, finalizing and returning
\| DEBUG push: finalizing
\|  INFO environment: Running hook: environment_plugins_loaded
\|  INFO runner: Preparing hooks for middleware sequence...
\|  INFO runner: 3 hooks defined.
\|  INFO runner: Running action: environment_plugins_loaded #<Vagrant::Action::Builder:0x0000000002d4aad8>
\|  INFO environment: Running hook: environment_load
\|  INFO runner: Preparing hooks for middleware sequence...
\|  INFO runner: 3 hooks defined.
\|  INFO runner: Running action: environment_load #<Vagrant::Action::Builder:0x0000000002b22300>
\| DEBUG checkpoint_client: starting plugin check
\|  INFO cli: CLI: [] "destroy" ["centos-7", "--force"]
\| DEBUG checkpoint_client: plugin check complete
\| DEBUG cli: Invoking command class: VagrantPlugins::CommandDestroy::Command ["centos-7", "--force"]
\| DEBUG checkpoint_client: no information received from checkpoint
\| DEBUG command: 'Destroy' each target VM...
\| DEBUG command: Getting target VMs for command. Arguments:
\| DEBUG command:  -- names: ["centos-7"]
\| DEBUG command:  -- options: {:reverse=>true}
\| DEBUG command: Finding machine that match name: centos-7
\|  INFO loader: Set "24120440_machine_centos-7" = ["[\"2\", #<Proc:0x0000000002b54198@/var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-sample/Vagrantfile:102>]"]
\| DEBUG loader: Populating proc cache for ["2", #<Proc:0x0000000002b54198@/var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-sample/Vagrantfile:102>]
\|  INFO loader: Loading configuration in order: [:home, :root, "24120440_machine_centos-7"]
\| DEBUG loader: Loading from: root (cache)
\| DEBUG loader: Loading from: 24120440_machine_centos-7 (evaluating)
\| DEBUG provisioner: Provisioner defined: markerfile
\| DEBUG provisioner: Provisioner defined: clean es installs in tmp
\| DEBUG provisioner: Provisioner defined: set prompt
\| DEBUG provisioner: Provisioner defined: install dependencies
\| DEBUG provisioner: Provisioner defined: install Docker using yum
\| DEBUG loader: Configuration loaded successfully, finalizing and returning
\| DEBUG push: finalizing
\|  WARN vagrantfile: Failed to locate elastic/centos-7-x86_64 with version
\|  WARN vagrantfile: Performing lookup with inital values elastic/centos-7-x86_64 with version
\|  INFO base: VBoxManage path: VBoxManage
\|  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "--version"]
\|  INFO subprocess: Command not in installer, restoring original environment...
\| DEBUG subprocess: Selecting on IO
\| DEBUG subprocess: stdout: 5.2.28r130011
\| DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
\| DEBUG subprocess: Exit status: 0
\| DEBUG meta: Finding driver for VirtualBox version: 5.2.28
\|  INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_5_2
\|  INFO base: VBoxManage path: VBoxManage
\| DEBUG environment: Initial usable provider list: [[6, :virtualbox]]
\| DEBUG environment: Priority sorted usable provider list: [:virtualbox]
\| DEBUG environment: Preferred provider list: []
\| DEBUG environment: Using provider `virtualbox` detected in configuration and usable.
\|  INFO environment: Getting machine: centos-7 (virtualbox)
\|  INFO environment: Uncached load of machine.
\|  INFO base: VBoxManage path: VBoxManage
\| DEBUG meta: Finding driver for VirtualBox version: 5.2.28
\|  INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_5_2
\|  INFO base: VBoxManage path: VBoxManage
\|  INFO loader: Set "24120440_machine_centos-7" = ["[\"2\", #<Proc:0x0000000002b54198@/var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-sample/Vagrantfile:102>]"]
\|  INFO loader: Loading configuration in order: [:home, :root, "24120440_machine_centos-7"]
\| DEBUG loader: Loading from: root (cache)
\| DEBUG loader: Loading from: 24120440_machine_centos-7 (cache)
\| DEBUG loader: Configuration loaded successfully, finalizing and returning
\| DEBUG push: finalizing
\|  INFO box_collection: Box found: elastic/centos-7-x86_64 (virtualbox)
\|  INFO environment: Running hook: authenticate_box_url
\|  INFO host: Autodetecting host type for [#<Vagrant::Environment: /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-sample>]
\| DEBUG host: Trying: alt
\| DEBUG host: Trying: arch
\| DEBUG host: Trying: suse
\| DEBUG host: Trying: slackware
\| DEBUG host: Trying: freebsd
\| DEBUG host: Trying: void
\| DEBUG host: Trying: gentoo
\| DEBUG host: Trying: redhat
\| DEBUG host: Trying: darwin
\| DEBUG host: Trying: windows
\| DEBUG host: Trying: linux
\|  INFO host: Detected: linux!
\|  INFO runner: Preparing hooks for middleware sequence...
\|  INFO runner: 4 hooks defined.
\|  INFO runner: Running action: authenticate_box_url #<Vagrant::Action::Builder:0x0000000002915828>
\|  INFO warden: Calling IN action: #<VagrantPlugins::LoginCommand::AddAuthentication:0x0000000002465a30>
\| DEBUG client: Using authentication token from disk at /var/lib/jenkins/.vagrant.d/data/vagrant_login_token
\|  INFO warden: Calling OUT action: #<VagrantPlugins::LoginCommand::AddAuthentication:0x0000000002465a30>
\|  INFO loader: Set :"22310080_elastic/centos-7-x86_64_virtualbox" = ["#<Pathname:/var/lib/jenkins/.vagrant.d/boxes/elastic-VAGRANTSLASH-centos-7-x86_64/20191013.0.0/virtualbox/Vagrantfile>"]
\| DEBUG loader: Populating proc cache for #<Pathname:/var/lib/jenkins/.vagrant.d/boxes/elastic-VAGRANTSLASH-centos-7-x86_64/20191013.0.0/virtualbox/Vagrantfile>
\| DEBUG loader: Load procs for pathname: /var/lib/jenkins/.vagrant.d/boxes/elastic-VAGRANTSLASH-centos-7-x86_64/20191013.0.0/virtualbox/Vagrantfile
\|  INFO loader: Loading configuration in order: [:"22310080_elastic/centos-7-x86_64_virtualbox", :home, :root, "24120440_machine_centos-7"]
\| DEBUG loader: Loading from: 22310080_elastic/centos-7-x86_64_virtualbox (evaluating)
\| DEBUG loader: Loading from: root (cache)
\| DEBUG loader: Loading from: 24120440_machine_centos-7 (cache)
\| DEBUG loader: Configuration loaded successfully, finalizing and returning
\| DEBUG push: finalizing
\|  INFO machine: Initializing machine: centos-7
\|  INFO machine:   - Provider: VagrantPlugins::ProviderVirtualBox::Provider
\|  INFO machine:   - Box: #<Vagrant::Box:0x0000000002d77b78>
\|  INFO machine:   - Data dir: /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-sample/.vagrant/machines/centos-7/virtualbox
\| DEBUG virtualbox: Instantiating the driver for machine ID: nil
\|  INFO base: VBoxManage path: VBoxManage
\| DEBUG meta: Finding driver for VirtualBox version: 5.2.28
\|  INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_5_2
\|  INFO base: VBoxManage path: VBoxManage
\|  INFO machine: New machine ID: nil
\| DEBUG virtualbox: Instantiating the driver for machine ID: nil
\|  INFO base: VBoxManage path: VBoxManage
\| DEBUG meta: Finding driver for VirtualBox version: 5.2.28
\|  INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_5_2
\|  INFO base: VBoxManage path: VBoxManage
\|  INFO interface: Machine: metadata ["provider", :virtualbox, {:target=>:"centos-7"}]
\|  INFO command: With machine: centos-7 (#<VagrantPlugins::ProviderVirtualBox::Provider:0x0000000002d754b8 @logger=#<Log4r::Logger:0x0000000002d75468 @fullname="vagrant::provider::virtualbox", @outputters=[], @additive=true, @name="virtualbox", @path="vagrant::provider", @parent=#<VagrantLogger:0x0000000002029610 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x0000000001d941c0 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x0000000001d94008>, @name="stderr", @level=0, @formatter=#<Vagrant::Util::LoggingFormatter:0x0000000002c12878 @formatter=#<Log4r::BasicFormatter:0x0000000001d03b98 @depth=7>>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x00000000020294d0 @level=0, @outputters=[]>, @level=1, @trace=false>, @level=1, @trace=false>, @machine=#<Vagrant::Machine: centos-7 (VagrantPlugins::ProviderVirtualBox::Provider)>, @driver=#<VagrantPlugins::ProviderVirtualBox::Driver::Meta:0x00000000027f0858 @logger=#<Log4r::Logger:0x000000000272bdf0 @fullname="vagrant::provider::virtualbox::meta", @outputters=[], @additive=true, @name="meta", @path="vagrant::provider::virtualbox", @parent=#<Log4r::Logger:0x0000000002d75468 @fullname="vagrant::provider::virtualbox", @outputters=[], @additive=true, @name="virtualbox", @path="vagrant::provider", @parent=#<VagrantLogger:0x0000000002029610 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x0000000001d941c0 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x0000000001d94008>, @name="stderr", @level=0, @formatter=#<Vagrant::Util::LoggingFormatter:0x0000000002c12878 @formatter=#<Log4r::BasicFormatter:0x0000000001d03b98 @depth=7>>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x00000000020294d0 @level=0, @outputters=[]>, @level=1, @trace=false>, @level=1, @trace=false>, @level=1, @trace=false>, @interrupted=false, @vboxmanage_path="VBoxManage", @uuid=nil, @driver=#<VagrantPlugins::ProviderVirtualBox::Driver::Version_5_2:0x0000000002583e58 @logger=#<Log4r::Logger:0x0000000002dda728 @fullname="vagrant::provider::virtualbox_5_2", @outputters=[], @additive=true, @name="virtualbox_5_2", @path="vagrant::provider", @parent=#<VagrantLogger:0x0000000002029610 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x0000000001d941c0 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x0000000001d94008>, @name="stderr", @level=0, @formatter=#<Vagrant::Util::LoggingFormatter:0x0000000002c12878 @formatter=#<Log4r::BasicFormatter:0x0000000001d03b98 @depth=7>>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x00000000020294d0 @level=0, @outputters=[]>, @level=1, @trace=false>, @level=1, @trace=false>, @interrupted=false, @vboxmanage_path="VBoxManage", @uuid=nil>, @version="5.2.28">, @cap_logger=#<Log4r::Logger:0x0000000002ac7c70 @fullname="vagrant::capability_host::vagrantplugins::providervirtualbox::provider", @outputters=[], @additive=true, @name="provider", @path="vagrant::capability_host::vagrantplugins::providervirtualbox", @parent=#<VagrantLogger:0x0000000002029610 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x0000000001d941c0 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x0000000001d94008>, @name="stderr", @level=0, @formatter=#<Vagrant::Util::LoggingFormatter:0x0000000002c12878 @formatter=#<Log4r::BasicFormatter:0x0000000001d03b98 @depth=7>>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x00000000020294d0 @level=0, @outputters=[]>, @level=1, @trace=false>, @level=1, @trace=false>, @cap_host_chain=[[:virtualbox, #<#<Class:0x0000000002ac8620>:0x0000000002a97890>]], @cap_args=[#<Vagrant::Machine: centos-7 (VagrantPlugins::ProviderVirtualBox::Provider)>], @cap_caps={:virtualbox=>#<Vagrant::Registry:0x0000000002ac8350 @items={:forwarded_ports=>#<Proc:0x0000000002c8d618@/opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/providers/virtualbox/plugin.rb:27>, :nic_mac_addresses=>#<Proc:0x0000000002c8d4d8@/opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/providers/virtualbox/plugin.rb:32>, :public_address=>#<Proc:0x0000000002c8d4b0@/opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/providers/virtualbox/plugin.rb:37>, :snapshot_list=>#<Proc:0x0000000002c8d488@/opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/providers/virtualbox/plugin.rb:42>}, @results_cache={}>, :hyperv=>#<Vagrant::Registry:0x0000000002ac81c0 @items={:public_address=>#<Proc:0x0000000002d0a0a0@/opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/providers/hyperv/plugin.rb:25>, :snapshot_list=>#<Proc:0x0000000002d09fb0@/opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/providers/hyperv/plugin.rb:30>}, @results_cache={}>, :docker=>#<Vagrant::Registry:0x0000000002ac8080 @items={:public_address=>#<Proc:0x0000000002c65438@/opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/providers/docker/plugin.rb:60>, :proxy_machine=>#<Proc:0x0000000002c65320@/opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/providers/docker/plugin.rb:65>}, @results_cache={}>}>)
\|  INFO batch_action: Batch action will parallelize: false
\|  INFO batch_action: Starting action: #<Vagrant::Machine:0x00000000026ec218> destroy {:force_confirm_destroy=>true}
\|  INFO machine: Calling action: destroy on provider VirtualBox (new VM)
\| DEBUG environment: Attempting to acquire process-lock: machine-action-820426dac3bd307b4dd393e10b378844
\| DEBUG environment: Attempting to acquire process-lock: dotlock
\|  INFO environment: Acquired process lock: dotlock
\|  INFO environment: Released process lock: dotlock
\|  WARN environment: Process-lock in use: machine-action-820426dac3bd307b4dd393e10b378844
\|  INFO environment: Running hook: environment_unload
\|  INFO runner: Preparing hooks for middleware sequence...
\|  INFO runner: 3 hooks defined.
\|  INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x0000000002d1d970>
\| ERROR vagrant: Vagrant experienced an error! Details:
\| ERROR vagrant: #<Vagrant::Errors::MachineActionLockedError: An action 'destroy' was attempted on the machine 'centos-7',
\| but another process is already executing an action on the machine.
\| Vagrant locks each machine for access by only one process at a time.
\| Please wait until the other Vagrant process finishes modifying this
\| machine, then try again.
\|
\| If you believe this message is in error, please check the process
\| listing for any "ruby" or "vagrant" processes and kill them. Then
\| try again.>
\| ERROR vagrant: An action 'destroy' was attempted on the machine 'centos-7',
\| but another process is already executing an action on the machine.
\| Vagrant locks each machine for access by only one process at a time.
\| Please wait until the other Vagrant process finishes modifying this
\| machine, then try again.
\|
\| If you believe this message is in error, please check the process
\| listing for any "ruby" or "vagrant" processes and kill them. Then
\| try again.
\| ERROR vagrant: /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/machine.rb:219:in `rescue in action'
\| /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/machine.rb:162:in `action'
\| /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
\|  INFO interface: error: An action 'destroy' was attempted on the machine 'centos-7',
\| but another process is already executing an action on the machine.
\| Vagrant locks each machine for access by only one process at a time.
\| Please wait until the other Vagrant process finishes modifying this
\| machine, then try again.
\|
\| If you believe this message is in error, please check the process
\| listing for any "ruby" or "vagrant" processes and kill them. Then
\| try again.
\| An action 'destroy' was attempted on the machine 'centos-7',
\| but another process is already executing an action on the machine.
\| Vagrant locks each machine for access by only one process at a time.
\| Please wait until the other Vagrant process finishes modifying this
\| machine, then try again.
\|
\| If you believe this message is in error, please check the process
\| listing for any "ruby" or "vagrant" processes and kill them. Then
\| try again.
\|  INFO interface: Machine: error-exit ["Vagrant::Errors::MachineActionLockedError", "An action 'destroy' was attempted on the machine 'centos-7',\nbut another process is already executing an action on the machine.\nVagrant locks each machine for access by only one process at a time.\nPlease wait until the other Vagrant process finishes modifying this\nmachine, then try again.\n\nIf you believe this message is in error, please check the process\nlisting for any \"ruby\" or \"vagrant\" processes and kill them. Then\ntry again."]
 
FAILURE: Build failed with an exception.
```

**Comment by mark-vieira** [comment]
I'm going to close this issue in favor of #47961. Also, we intend to completely remove the Vagrant-based test executions from our PR checks so this will be a non-issue.
