### ISSUE TITLE
SnapshotLifecycleRestIT » testBasicTimeBasedRetenion failure

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#48017]
This test failed in the 7.x branch following https://github.com/elastic/elasticsearch/commit/170266765b9a5c2fdf30188fa3998904e5711477.

Was not able to reproduce locally.

```
[2019-10-14T12:58:57,730][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] before test
[2019-10-14T12:59:00,370][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] --> checking to see if snapshot has been deleted...
[2019-10-14T12:59:00,389][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] --> checking to see if snapshot has been deleted...
[2019-10-14T12:59:00,400][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] --> checking to see if snapshot has been deleted...
[2019-10-14T12:59:00,419][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] --> checking to see if snapshot has been deleted...
[2019-10-14T12:59:00,438][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] --> checking to see if snapshot has been deleted...
[2019-10-14T12:59:00,462][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] --> checking to see if snapshot has been deleted...
[2019-10-14T12:59:00,503][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] --> checking to see if snapshot has been deleted...
[2019-10-14T12:59:00,582][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] --> checking to see if snapshot has been deleted...
[2019-10-14T12:59:00,723][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] --> checking to see if snapshot has been deleted...
[2019-10-14T12:59:00,990][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] --> checking to see if snapshot has been deleted...
[2019-10-14T12:59:01,511][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] --> checking to see if snapshot has been deleted...
[2019-10-14T12:59:02,695][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] --> checking to see if snapshot has been deleted...
[2019-10-14T12:59:04,771][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] --> checking to see if snapshot has been deleted...
[2019-10-14T12:59:08,894][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] --> checking to see if snapshot has been deleted...
[2019-10-14T12:59:17,109][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] --> checking to see if snapshot has been deleted...
[2019-10-14T12:59:33,534][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] --> checking to see if snapshot has been deleted...
[2019-10-14T13:00:06,337][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] --> checking to see if snapshot has been deleted...
[2019-10-14T13:00:07,631][INFO ][o.e.x.s.SnapshotLifecycleRestIT] [testBasicTimeBasedRetenion] after test
```

### Scan
https://gradle-enterprise.elastic.co/s/fw2xlp2ojjp7o/failure?openFailures=WzBd&openStackTraces=WzFd#top=0

**Comment by original-brownbear** [comment]
@dakrone @gwbrown can one of you take a look here? I tried, but I don't really understand how retention runs are counted (that's what's eventually failing here):

```

2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:qa:multi-node:integTestRunner' --tests "org.elasticsearch.xpack.slm.SnapshotLifecycleRestIT.testBasicTimeBasedRetenion" -Dtests.seed=7830545AB5631D78 -Dtests.security.manager=true -Dtests.locale=nl -Dtests.timezone=America/Aruba -Dcompiler.java=12 -Druntime.java=8
--
2> java.lang.AssertionError:
Expected: <1>
but: was <68>
at __randomizedtesting.SeedInfo.seed([7830545AB5631D78:ED373C7A97F51630]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.xpack.slm.SnapshotLifecycleRestIT.lambda$testBasicTimeBasedRetenion$11(SnapshotLifecycleRestIT.java:405)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:893)
at org.elasticsearch.xpack.slm.SnapshotLifecycleRestIT.testBasicTimeBasedRetenion(SnapshotLifecycleRestIT.java:386)

```

Maybe you'll have an easier time here than me ? :)

**Comment by dliappis** [comment]
Another occurrence: https://gradle-enterprise.elastic.co/s/27s2vumgbjtpk

**Comment by dliappis** [comment]
These have been failing for a while on [various branches](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(branch,message),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%20%22org.elasticsearch.xpack.slm.SnapshotLifecycleRestIT%22%20AND%20test:%20%22testBasicTimeBasedRetenion%22'),sort:!(time,desc))) so I raised PRs to mute in master/7.x and 7.5

**Comment by gwbrown** [comment]
I've added some extra logging in #48612 that will hopefully help catch this failure. I'll try to keep an eye out for failures but if you find a failure for this test please ping me.
