### ISSUE TITLE
ClassificationIT.testDependentVariableCardinalityTooHighError failing on master

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#48082]
I've seen this test fail a handful of times over the course of the day, a couple on master and a few times on PR test failures according to build stats. I've not been able to reproduce it locally yet.

```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testDependentVariableCardinalityTooHighError" \
  -Dtests.seed=AA98A6F1439DB43E \
  -Dtests.security.manager=true \
  -Dtests.locale=es-BZ \
  -Dtests.timezone=Pacific/Bougainville \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

Scan: https://gradle-enterprise.elastic.co/s/tfir4yhfyz3ja

Failure: 
```
org.elasticsearch.xpack.ml.integration.ClassificationIT > testDependentVariableCardinalityTooHighError FAILED
--
junit.framework.AssertionFailedError: Expected exception ElasticsearchStatusException but no exception was thrown
at __randomizedtesting.SeedInfo.seed([AA98A6F1439DB43E:2EE500419C29C471]:0)
at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2722)
at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2712)
at org.elasticsearch.xpack.ml.integration.ClassificationIT.testDependentVariableCardinalityTooHighError(ClassificationIT.java:267)
```

**Comment by benwtrent** [comment]
@jbaiera I tried to recreate this locally (running hundreds of times), but to no avail. I THINK it might be due to index refresh interval. I will experiment some to see.

**Comment by benwtrent** [comment]
OK, figured out the issue. will have a fix in a minute or two
