### ISSUE TITLE
ClassCastException when creating index with dynamic template

### ISSUE THREAD

**Issue by tiitginter** [elastic/elasticsearch#48105]
**Elasticsearch version** 7.3.2

When useing CreateIndexRequest to create index with dynamic template like https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html#match-pattern it tries to cast array of templates to map.

Wehn calling 
`action.source( source, XContentType.JSON ); `

It will end up to code that does.
```
} else if (MAPPINGS.match(name, deprecationHandler)) {
    Map<String, Object> mappings = (Map<String, Object>) entry.getValue();
     for (Map.Entry<String, Object> entry1 : mappings.entrySet()) {
           mapping(entry1.getKey(), (Map<String, Object>) entry1.getValue());
     }
}
```

Mapping part of the source
```
"mappings": {
      "dynamic_templates": [
        {
          "store_generic": {
              "match_mapping_type": "*",
              "match": "*",
              "mapping": {
                  "type": "text",
                  "analyzer": "remove_special_chars_analyzer"                         
              }
          }
        }
      ],
      "_source":{ 
         "enabled":true
      }
   }

```
With logs
```
E 1016-0822:49,519 Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map [BatchProcessor_Worker-9]
E 1016-0822:49,519 	at org.elasticsearch.action.admin.indices.create.CreateIndexRequest.source(CreateIndexRequest.java:383) [BatchProcessor_Worker-9]
E 1016-0822:49,519 	at org.elasticsearch.action.admin.indices.create.CreateIndexRequest.source(CreateIndexRequest.java:367) [BatchProcessor_Worker-9]
E 1016-0822:49,519 	at org.elasticsearch.action.admin.indices.create.CreateIndexRequest.source(CreateIndexRequest.java:338) [BatchProcessor_Worker-9]
```

**Comment by hub-cap** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html are definitely stored as an array of named objects. I have not looked into why this is happening but there is obviously a code path difference between what happens via curl/console and HLRC. I did verify that the documentation works as advertised.

**Comment by bkis** [comment]
I have the same problem using Elasticsearch 7.6.2 - is there anything I can do?

**Comment by bkis** [comment]
I just figured out that
```
org.elasticsearch.client.indices.CreateIndexRequest;
```
does the same casting `(Map<String, Object>) entry.getValue()`. Why does it work here?

**Comment by mdgilene** [comment]
This same issue occurs when attempting to get the mapping for an index with dynamic_templates (`GetMappingsResponse`). What is the status on this? It looks like this portion of the code has been completely redone for ES 8.0.0 but the problem still exists in ES 7.X

**Comment by mattc58** [comment]
We are closing this for inactivity but will reopen if necessary. The high level REST client has been deprecated in favor of the Java client.
