### ISSUE TITLE
Elasticsearch node was blocked during restart, beacuse failed to obtain node locks

### ISSUE THREAD

**Issue by liuchintao** [elastic/elasticsearch#48374]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 6.3.2

**Plugins installed**: []

**JVM version** (`java -version`): openjdk 10.0.2

**OS version** (`uname -a` if on a Unix-like system):

Linux elasticsearch-logging-master-1 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

I built a elastic stack on k8s cluster, but the elasticsearch node might be blocked when the pod restart, and it cause the elasticsearch pod restart infinitely.

It like a loop:

something was wrong => elasticsearch pod stop => elasticsearch pod restart => elasticsearch can not get lock file => this is wrong => elasticsearch pod stop => elasticsearch pod restart => ...

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. This issue appear once in a while;
 2. delete elasticsearch pod or reboot compute while elasticsearch is working;
 3. restart elasticsearch pod or start elasticsearch server.

**Provide logs (if relevant)**:

```log
+ export NODE_NAME=elasticsearch-logging-master-0
+ NODE_NAME=elasticsearch-logging-master-0
+ export NODE_MASTER=true
+ NODE_MASTER=true
+ export NODE_DATA=false
+ NODE_DATA=false
+ export HTTP_PORT=9200
+ HTTP_PORT=9200
+ export TRANSPORT_PORT=9300
+ TRANSPORT_PORT=9300
+ export MINIMUM_MASTER_NODES=2
+ MINIMUM_MASTER_NODES=2
+ chown -R elasticsearch:elasticsearch /data
+ ./bin/elasticsearch_logging_discovery
+ exec su elasticsearch -c /usr/local/bin/docker-entrypoint.sh
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2019-10-23T08:59:18,751][INFO ][o.e.n.Node               ] [elasticsearch-logging-master-0] initializing ...
[2019-10-23T08:59:18,948][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [elasticsearch-logging-master-0] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/data/kubernetes-logging]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.3.2.jar:6.3.2]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.3.2.jar:6.3.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.3.2.jar:6.3.2]
Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/data/kubernetes-logging]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:243) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.node.Node.<init>(Node.java:270) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.3.2.jar:6.3.2]
        ... 6 more
```

**Comment by williamrandolph** [comment]
@liuchintao I am sorry it has taken us so long to look at this issue.

Unfortunately, I don't think there is enough information in this ticket for us to reproduce the issue, and at this late stage you may have moved on. Additionally, it's not clear from the ticket description whether you took action on the error message:

```
failed to obtain node locks, tried [[/data/kubernetes-logging]] with lock id [0];
  maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
```

This suggests that multiple nodes were trying to use the same location on the filesystem. If that was the case in your kubernetes cluster, then Elasticsearch was behaving correctly here, and the solution would be to make sure that the nodes in the cluster have their own distinct disks or filesystem locations.

Please let me know if there is a way to reproduce this issue where the nodes are all using distinct filesystems or filesystem locations. If so, I will reopen the issue. If you need help configuring Elasticsearch, there is a lot of discussion of this error message at http://discuss.elastic.co and something there may be helpful.
