### ISSUE TITLE
Half-deleted snapshot causes the backup repository to be unusable

### ISSUE THREAD

**Issue by centic9** [elastic/elasticsearch#48398]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.8.1

**Plugins installed**: Happened with s3 repository installed, but could be reproduced locally with only the file-system repository.

**JVM version** (`java -version`): OpenJDK 8_222

**OS version** (`uname -a` if on a Unix-like system): Linux and Windows

**Description of the problem including expected versus actual behavior**:

A backup repository suddenly reports an error when iterating snapshots:

SnapshotException[[backup123:snapshot_2018-11-12-18-01-utc/oKPG3J7YS5GTT3K1LtleFg] Snapshot could not be read]; nested: SnapshotMissingException[[backup123:snapshot_2018-11-12-18-01-utc/oKPG3J7YS5GTT3K1LtleFg] is missing]; nested: NoSuchFileException[Blob object [snap-oKPG3J7YS5GTT3K1LtleFg.dat] not found: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: X; S3 Extended Request ID: X)];

We did not succeed in getting the repository back to be usable with any of the APIs which Elasticsearch offers.

**Steps to reproduce**:

1. Set up a local filesystem snapshot repository
2. Create a few snapshots of a few indices
3. Remove at least on "snap-" file in the backup repository folder
4. Looking at snapshots via REST will now return a "NoSuchFileException"
5. Try to delete the failing snapshot via REST DELETE _snapshot/<repo>/<snap-name> => it will fail
6. Try to iterate existing snapshots via REST GET _snapshot/<repo>/_all => it will fail

So we cannot remove the broken snapshot any more and we also cannot iterate existing snapshots any more, so the backup repository is broken unless I manually edit some of the index-files of the repository.

Ideally I would need a "force" parameter for the SNAPSHOT DELETE operation to get rid of this one broken snapshot entry, this would make the other snapshots available again.

**Provide logs (if relevant)**:

[2019-10-23T13:24:48,923][WARN ][r.suppressed             ] [ES] path: /_snapshot/my_fs_backup/snapshot_dev-cluster-any_1571829538238, params: {repository=my_fs_backup, snapshot=snapshot_dev-cluster-any_1571829538238}
org.elasticsearch.snapshots.SnapshotException: [my_fs_backup:snapshot_dev-cluster-any_1571829538238/paKPNiXJTm-YdkFpQhB_mQ] Snapshot could not be read
        at org.elasticsearch.snapshots.SnapshotsService.snapshots(SnapshotsService.java:212) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:136) [elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:55) [elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:124) [elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:211) [elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) [elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.8.1.jar:6.8.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.elasticsearch.snapshots.SnapshotMissingException: [my_fs_backup:snapshot_dev-cluster-any_1571829538238/paKPNiXJTm-YdkFpQhB_mQ] is missing
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getSnapshotInfo(BlobStoreRepository.java:558) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.snapshots.SnapshotsService.snapshots(SnapshotsService.java:206) ~[elasticsearch-6.8.1.jar:6.8.1]
        ... 9 more
Caused by: java.nio.file.NoSuchFileException: c:\temp\backup1\snap-paKPNiXJTm-YdkFpQhB_mQ.dat
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:231) ~[?:?]
        at java.nio.file.Files.newByteChannel(Files.java:370) ~[?:?]
        at java.nio.file.Files.newByteChannel(Files.java:421) ~[?:?]
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420) ~[?:?]
        at java.nio.file.Files.newInputStream(Files.java:155) ~[?:?]
        at org.elasticsearch.common.blobstore.fs.FsBlobContainer.readBlob(FsBlobContainer.java:120) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.readBlob(ChecksumBlobStoreFormat.java:101) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.repositories.blobstore.BlobStoreFormat.read(BlobStoreFormat.java:90) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getSnapshotInfo(BlobStoreRepository.java:556) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.snapshots.SnapshotsService.snapshots(SnapshotsService.java:206) ~[elasticsearch-6.8.1.jar:6.8.1]
        ... 9 more

**Comment by ywelsch** [comment]
Note that this is not what I would call a half-deleted snapshot (i.e. a deletion that was executed by the system and failed mid-way through), but your step 3 deliberately corrupts the repository.

Can you check if you can query the list of snapshots with `ignore_unavailable`?

**Comment by original-brownbear** [comment]
This is a known possible corruption unfortunately. It was eventually fixed and won't happen again on its own in `6.8.1` and must have broken in an earlier version. I don't think we can do much or anything here. We shouldn't do any repairs on the repo to filter out the snapshot with missing metadata as a corrupted repo could miss other files quietly as well and would give the potentially impression of being a valid backup.
-> I'd close here.

**Comment by centic9** [comment]
Sorry for being unclear, we experienced the broken repository without those reproducing-steps. However hey allow to produce a repository which shows that a single broken snapshot renders the complete repository unusable. 

Nice that there were some fixes to the deletion-functionality, we upgraded recently, so it might actually be the case. 

Overall a way to cleanly recover the repository from such a state would be good to have in the future for improved resilience.

**Comment by original-brownbear** [comment]
> However hey allow to produce a repository which shows that a single broken snapshot renders the complete repository unusable.

I would argue that this is by design. Due to the incremental nature of snapshotting one broken snapshot from a missing file may not be an isolated problem. If it's a `snap-` blob, then yes it's isolated and the way we got here was an unfortunate bug. If it were a `__fgd..`  data blob then it wouldn't be an isolated thing at all. In the end, a repository simply should never ever lose a file, if it does something is wrong.

> Overall a way to cleanly recover the repository from such a state would be good to have in the future for improved resilience.

Regardless of the above, I fully agree and it's something we're exploring at the moment.

> Nice that there were some fixes to the deletion-functionality, we upgraded recently, so it might actually be the case.

Thanks for confirming the upgrade part. I think with that we can safely close here. It's unfortunate that a past bug got us here, but nothing can be done about it here at this point I'm afraid.
