### ISSUE TITLE
Failure in testFailedRecoveryOnAllocateStalePrimaryRequiresAnotherAllocateStalePrimary

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#48529]
This build failed: https://gradle-enterprise.elastic.co/s/yeotnsmwp2diw

```
  2> REPRODUCE WITH: ./gradlew ':server:integTest' -Dtests.seed=E6DBCEDEF9F3857F -Dtests.class=org.elasticsearch.cluster.routing.AllocationIdIT -Dtests.method="testFailedRecoveryOnAllocateStalePrimaryRequiresAnotherAllocateStalePrimary" -Dtests.security.manager=true -Dtests.locale=ga -Dtests.timezone=Europe/Guernsey -Dcompiler.java=12 -Druntime.java=13
FAILURE 5.70s J2  | AllocationIdIT.testFailedRecoveryOnAllocateStalePrimaryRequiresAnotherAllocateStalePrimary <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: a collection with size <1>
   >      but: collection size was <2>
   > 	at __randomizedtesting.SeedInfo.seed([E6DBCEDEF9F3857F:6F5D392F35A83E5D]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.cluster.routing.AllocationIdIT.historyUUID(AllocationIdIT.java:214)
   > 	at org.elasticsearch.cluster.routing.AllocationIdIT.testFailedRecoveryOnAllocateStalePrimaryRequiresAnotherAllocateStalePrimary(AllocationIdIT.java:163)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   > 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   > 	at java.base/java.lang.Thread.run(Thread.java:830)
```

Build-stats shows occasional failures on `master` and `7.x` that seem unrelated to this `6.8` failure.

**Comment by ywelsch** [comment]
Hopefully closed by #48623. If not, reopen.
