### ISSUE TITLE
Failure in ILMDocumentationIT#testRetryPolicy

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#48527]
This `7.x` build failed: https://gradle-enterprise.elastic.co/s/pvagnc66sl5o6:

```
org.elasticsearch.client.documentation.ILMDocumentationIT > testRetryPolicy FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([6F6F78E6740A8698:1EAA654B22A23DCA]:0)
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertNotNull(Assert.java:712)
        at org.junit.Assert.assertNotNull(Assert.java:722)
        at org.elasticsearch.client.documentation.ILMDocumentationIT.lambda$testRetryPolicy$2(ILMDocumentationIT.java:634)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:893)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:866)
        at org.elasticsearch.client.documentation.ILMDocumentationIT.testRetryPolicy(ILMDocumentationIT.java:634)
REPRODUCE WITH: ./gradlew ':client:rest-high-level:integTestRunner' --tests "org.elasticsearch.client.documentation.ILMDocumentationIT.testRetryPolicy" -Dtests.seed=6F6F78E6740A8698 -Dtests.security.manager=true -Dtests.locale=ar-TN -Dtests.timezone=Europe/Sarajevo -Dcompiler.java=12 -Druntime.java=8
```

I don't see other (non-PR) failures of this.

**Comment by gwbrown** [comment]
This looks like an `assertBusy` that occasionally times out, likely due to CI slowness. I'll increase the timeout.
