### ISSUE TITLE
PeerRecoveryTargetServiceTests#testPrepareIndexForPeerRecovery failed in CI

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#48532]
This build fails: https://gradle-enterprise.elastic.co/s/a2blc36l3tb4k/console-log?task=:server:test

```
org.elasticsearch.indices.recovery.PeerRecoveryTargetServiceTests > testPrepareIndexForPeerRecovery FAILED
    java.lang.AssertionError: 
    Expected: <48>
         but: was <47>
        at __randomizedtesting.SeedInfo.seed([C3F8AA3D7B611EE8:18764B67EA0E4848]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.indices.recovery.PeerRecoveryTargetServiceTests.testPrepareIndexForPeerRecovery(PeerRecoveryTargetServiceTests.java:197)
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.indices.recovery.PeerRecoveryTargetServiceTests.testPrepareIndexForPeerRecovery" -Dtests.seed=C3F8AA3D7B611EE8 -Dtests.security.manager=true -Dtests.locale=ar-OM -Dtests.timezone=MST7MDT -Dcompiler.java=12 -Druntime.java=8
```

**Comment by dnhatn** [comment]
I opened https://github.com/elastic/elasticsearch/pull/48559.
