### ISSUE TITLE
SSLConfigurationReloaderTests#testPEMKeyConfigReloading failed on Windows

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#48530]
This build failed: https://gradle-enterprise.elastic.co/s/aysha3pq6qpri

```
  2> REPRODUCE WITH: gradlew ':x-pack:plugin:core:unitTest' -Dtests.seed=A23074480705437E -Dtests.class=org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests -Dtests.method="testPEMKeyConfigReloading" -Dtests.security.manager=true -Dtests.locale=en-PH -Dtests.timezone=AST -Dcompiler.java=12 -Druntime.java=8
ERROR   1.05s J2 | SSLConfigurationReloaderTests.testPEMKeyConfigReloading <<< FAILURES!
   > Throwable #1: java.lang.RuntimeException: failed to modify file
   > 	at __randomizedtesting.SeedInfo.seed([A23074480705437E:6645CB7AF59569AC]:0)
   > 	at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests.lambda$testPEMKeyConfigReloading$8(SSLConfigurationReloaderTests.java:172)
   > 	at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests.validateSSLConfigurationIsReloaded(SSLConfigurationReloaderTests.java:511)
   > 	at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests.testPEMKeyConfigReloading(SSLConfigurationReloaderTests.java:188)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+6.8+multijob-windows-compatibility\os\windows-2016\x-pack\plugin\core\build\testrun\unitTest\J2\temp\org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests_A23074480705437E-001\tempDir-004\testnode_updated.crt -> C:\Users\jenkins\workspace\elastic+elasticsearch+6.8+multijob-windows-compatibility\os\windows-2016\x-pack\plugin\core\build\testrun\unitTest\J2\temp\org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests_A23074480705437E-001\tempDir-004\testnode.crt
   > 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
   > 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
   > 	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
   > 	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
   > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.move(FilterFileSystemProvider.java:147)
   > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.move(FilterFileSystemProvider.java:147)
   > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.move(FilterFileSystemProvider.java:147)
   > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.move(FilterFileSystemProvider.java:147)
   > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.move(FilterFileSystemProvider.java:147)
   > 	at java.nio.file.Files.move(Files.java:1395)
   > 	at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests.atomicMoveIfPossible(SSLConfigurationReloaderTests.java:519)
   > 	at org.elasticsearch.xpack.core.ssl.SSLConfigurationReloaderTests.lambda$testPEMKeyConfigReloading$8(SSLConfigurationReloaderTests.java:170)
   > 	... 39 more
```

**Comment by jkakavas** [comment]
Closing this as this has not been reported again. We can always revisit if need be
