### ISSUE TITLE
[CI] RelocationIT.testIndexAndRelocateConcurrently fails on master intake

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#48625]
https://gradle-enterprise.elastic.co/s/k63bx3zx5aeg4

REPRODUCE WITH: ./gradlew ':server:integTest' --tests "org.elasticsearch.recovery.RelocationIT.testIndexAndRelocateConcurrently" -Dtests.seed=B205D9E1D369E428 -Dtests.security.manager=true -Dtests.locale=sr-BA -Dtests.timezone=America/Goose_Bay -Dcompiler.java=12 -Druntime.java=11

The failure doesn't reproduce for me

Relevant extract from the console log: 
```
java.lang.AssertionError: Unexpected ShardFailures: [[test][3] failed, reason [[test/jPGCBDDYR36D8UlPCUoAYQ][[test][3]] org.elasticsearch.action.support.broadcast.BroadcastShardOperationFailedException:
at org.elasticsearch.action.support.replication.TransportBroadcastReplicationAction.finishAndNotifyListener(TransportBroadcastReplicationAction.java:166)
...

Caused by: org.elasticsearch.transport.RemoteTransportException: [node_t3][127.0.0.1:33581][indices:admin/refresh[s][r]]
--
Caused by: java.lang.IllegalStateException: store is already closed can't increment refCount current count [0]
...

Expected: <0>
--
but: was <1>
at __randomizedtesting.SeedInfo.seed([B205D9E1D369E428:6D34D86CCF6CFB8B]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertNoFailures(ElasticsearchAssertions.java:326)
at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1367)
at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1272)
at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1255)
at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1231)
at org.elasticsearch.recovery.RelocationIT.testIndexAndRelocateConcurrently(RelocationIT.java:492)
```

**Comment by original-brownbear** [comment]
This reproduces pretty easily for me locally every few runs of that test with the given seed. I'll see if I can figure it out :)
