### ISSUE TITLE
testForceMergeWithSoftDeletesRetentionAndRecoverySource fails

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#48735]
On `master` (3e4791a4be919741664d1a75e8d9ed5a0750ca6c) I get the following failure:

```
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.index.engine.InternalEngineTests.testForceMergeWithSoftDeletesRetentionAndRecoverySource" -Dtests.seed=15017DBA718DE0ED -Dtests.security.manager=true -Dtests.jvms=4 -Dtests.locale=de-DE -Dtests.timezone=America/Cambridge_Bay -Dcompiler.java=12 -Druntime.java=12
  2> java.lang.AssertionError:
    Expected: a collection with size <0>
         but: collection size was <2>
        at __randomizedtesting.SeedInfo.seed([15017DBA718DE0ED:930E7D8A8C86530A]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.index.engine.InternalEngineTests.testForceMergeWithSoftDeletesRetentionAndRecoverySource(InternalEngineTests.java:1732)
  2> NOTE: leaving temporary files on disk at: /home/davidturner/elasticsearch/server/build/testrun/test/temp/org.elasticsearch.index.engine.InternalEngineTests_15017DBA718DE0ED-002
  2> NOTE: test params are: codec=Asserting(Lucene80), sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@6a559181), locale=de-DE, timezone=America/Cambridge_Bay
  2> NOTE: Linux 4.15.0-47-generic amd64/Oracle Corporation 12 (64-bit)/cpus=8,threads=1,free=360496288,total=536870912
  2> NOTE: All tests run in this JVM: [InternalEngineTests]
```

The `REPRODUCE WITH` line does seem to reliably reproduce this.

**Comment by dnhatn** [comment]
Relates to #48533.
