### ISSUE TITLE
FullClusterRestartIT testSlmPolicyAndStats fails

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#48741]
Logs 	

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+default-distro+bwc/BWC_VERSION=7.0.1,nodes=centos-7&&immutable/255/console

https://gradle-enterprise.elastic.co/s/wes4i2kbh7nek

Failure

```
9:04:46 org.elasticsearch.xpack.restart.FullClusterRestartIT > testSlmPolicyAndStats FAILED
09:04:46     org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:35232], URI [_slm/policy/test-policy], status line [HTTP/1.1 404 Not Found]
09:04:46     {"error":{"root_cause":[{"type":"resource_not_found_exception","reason":"snapshot lifecycle policy or policies [test-policy] not found, no policies are configured"}],"type":"resource_not_found_exception","reason":"snapshot lifecycle policy or policies [test-policy] not found, no policies are configured"},"status":404}
09:04:46         at __randomizedtesting.SeedInfo.seed([89B41EEF070A7ADB:9F225D2E268A1A87]:0)
09:04:46         at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:283)
09:04:46         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:261)
09:04:46         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
09:04:46         at org.elasticsearch.xpack.restart.FullClusterRestartIT.testSlmPolicyAndStats(FullClusterRestartIT.java:304)
```

At the time of writing this failed 27 times in 12 hours, therefore I will probably mute the test.

related #48428

**Comment by dakrone** [comment]
@jakelandis is this related to the work in #48428?

**Comment by jakelandis** [comment]
@dakrone - probably - I will take a look soon.
