### ISSUE TITLE
[CI] TimeoutCheckerTests.testWatchdog failing regularly

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#48861]
TimeoutCheckerTests.testWatchdog has been failing regularly on master and 7.x for the last few days.

master example: https://gradle-enterprise.elastic.co/s/vcaxvky7vonu6
7.x example: https://gradle-enterprise.elastic.co/s/d5bttww4yctky

The error is:

```
04:39:58 org.elasticsearch.xpack.ml.filestructurefinder.TimeoutCheckerTests > testWatchdog FAILED
04:39:58     Wanted but not invoked:
04:39:58     matcher.interrupt();
04:39:58     -> at org.elasticsearch.xpack.ml.filestructurefinder.TimeoutCheckerTests.lambda$testWatchdog$2(TimeoutCheckerTests.java:72)
04:39:58     Actually, there were zero interactions with this mock.
04:39:58         at __randomizedtesting.SeedInfo.seed([4BA94B8F714382E0:E9C403A9D4A4ABA6]:0)
04:39:58         at org.elasticsearch.xpack.ml.filestructurefinder.TimeoutCheckerTests.lambda$testWatchdog$2(TimeoutCheckerTests.java:72)
04:39:58         at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:867)
04:39:58         at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:840)
04:39:58         at org.elasticsearch.xpack.ml.filestructurefinder.TimeoutCheckerTests.testWatchdog(TimeoutCheckerTests.java:71)
```

This didn't reproduce locally on master using:

```
./gradlew ':x-pack:plugin:ml:test' --tests "org.elasticsearch.xpack.ml.filestructurefinder.TimeoutCheckerTests.testWatchdog" \
  -Dtests.seed=4BA94B8F714382E0 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-DO \
  -Dtests.timezone=ECT \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

It is probably a side effect of #48346.

**Comment by droberts195** [comment]
I muted the test:

master: 4a66cfc9686d282123659a96a3acbe1404aacdd9
7.x: c03f7ba74cad0bf3253270a98b85dbc825b8494e
