### ISSUE TITLE
Snapshot don't delete all indices from disk

### ISSUE THREAD

**Issue by cde0** [elastic/elasticsearch#48897]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.1.1

**Plugins installed**: [ default ]

**JVM version** (`java -version`): openjdk version "11.0.4" 2019-07-16

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 18.04.2 LTS - 4.15.0-55-generic  

**Description of the problem including expected versus actual behaviour**:
Delete old snapshot don't delete indices from disk.
I delete all the snapshot from my repository but the size of the Snapshot directory is 100GB, with no snapshot. 

Actual behaviour: Delete indices from disk. 

All the snapshot finish with SUCCESS status.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create snapshot 
 2. Delete snapshot

**Provide logs (if relevant)**:

```
[2019-11-07T05:00:28,854][WARN ][o.e.r.b.BlobStoreRepository] index [[test/J7jYaaEeSSanzPOPHV3GSA]] no longer part of any snapshots in the repository, but failed to clean up its index folder.
java.nio.file.FileSystemException: /mnt/ftp/indices/J7jYaaEeSSanzPOPHV3GSA/0: Operation not permitted
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:249) ~[?:?]
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105) ~[?:?]
        at java.nio.file.Files.delete(Files.java:1144) ~[?:?]
        at org.elasticsearch.common.blobstore.fs.FsBlobContainer$1.postVisitDirectory(FsBlobContainer.java:102) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.blobstore.fs.FsBlobContainer$1.postVisitDirectory(FsBlobContainer.java:99) ~[elasticsearch-7.1.1.jar:7.1.1]
        at java.nio.file.Files.walkFileTree(Files.java:2819) ~[?:?]
        at java.nio.file.Files.walkFileTree(Files.java:2873) ~[?:?]
        at org.elasticsearch.common.blobstore.fs.FsBlobContainer.deleteBlob(FsBlobContainer.java:99) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.blobstore.BlobContainer.deleteBlobIgnoringIfNotExists(BlobContainer.java:119) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.deleteSnapshot(BlobStoreRepository.java:470) [elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.snapshots.SnapshotsService.lambda$deleteSnapshotFromRepository$10(SnapshotsService.java:1314) [elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [elasticsearch-7.1.1.jar:7.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]
[2019-11-07T05:00:28,855][INFO ][o.e.s.SnapshotsService   ] snapshot [test:20191001/fh7sbOoXTuqY8MMUfYJs0w] deleted
```

After this i check the directory and is 1GB size.

**Comment by DaveCTurner** [comment]
`java.nio.file.FileSystemException: /mnt/ftp/indices/J7jYaaEeSSanzPOPHV3GSA/0: Operation not permitted`

It looks like you are using an FTP-backed repository and are not permitted to delete things from the repository. I am closing this since it seems more likely it's a problem in your environment and there is nothing actionable on the Elasticsearch side, and recommend you ask for help on the [discussion forums](https://discuss.elastic.co/c/elasticsearch) if you are still stuck.
