### ISSUE TITLE
[CI] NodeSubclassTests#testReplaceChildren fails for Pivot

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#48900]
https://gradle-enterprise.elastic.co/s/xyvdtf72vwxka/tests/ihtizrmlhavwa-jrtvjtda2so76

Reproduce (7.x) with:
```
./gradlew ':x-pack:plugin:sql:test' --tests "org.elasticsearch.xpack.sql.tree.NodeSubclassTests" -Dtests.method="testReplaceChildren {p0=class org.elasticsearch.xpack.sql.plan.logical.Pivot}" -Dtests.seed=6B69CBC6A6A01FE4 -Dtests.security.manager=true -Dtests.locale=th-TH -Dtests.timezone=Pacific/Easter -Dcompiler.java=12 -Druntime.java=8
```

Stacktrace:
```

org.elasticsearch.xpack.sql.tree.NodeSubclassTests > testReplaceChildren {p0=class org.elasticsearch.xpack.sql.plan.logical.Pivot} FAILED
--
UnresolvedException[Invalid call to dataType on an unresolved object ?rxWgKl.EFhUf]
at __randomizedtesting.SeedInfo.seed([6B69CBC6A6A01FE4:5296688B5FA63F1A]:0)
at org.elasticsearch.xpack.sql.expression.UnresolvedAttribute.dataType(UnresolvedAttribute.java:79)
at org.elasticsearch.xpack.sql.expression.Attribute.withQualifier(Attribute.java:95)
at org.elasticsearch.xpack.sql.plan.logical.Pivot.withQualifierNull(Pivot.java:47)
at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:190)
at org.elasticsearch.xpack.sql.tree.Node.lambda$transformUp$10(Node.java:188)
at org.elasticsearch.xpack.sql.tree.Node.transformChildren(Node.java:209)
at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:188)
at org.elasticsearch.xpack.sql.plan.logical.Pivot.lambda$replaceChild$0(Pivot.java:70)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
at org.elasticsearch.xpack.sql.plan.logical.Pivot.replaceChild(Pivot.java:71)
at org.elasticsearch.xpack.sql.plan.logical.Pivot.replaceChild(Pivot.java:27)
at org.elasticsearch.xpack.sql.plan.logical.UnaryPlan.replaceChildren(UnaryPlan.java:33)
at org.elasticsearch.xpack.sql.plan.logical.UnaryPlan.replaceChildren(UnaryPlan.java:19)
at org.elasticsearch.xpack.sql.tree.NodeSubclassTests.testReplaceChildren(NodeSubclassTests.java:234)
```

**Comment by dnhatn** [comment]
Another instance: https://gradle-enterprise.elastic.co/s/5uqrz5ccq45js

**Comment by not-napoleon** [comment]
Another: https://gradle-enterprise.elastic.co/s/n7c3wyqq2ofuo/

**Comment by romseygeek** [comment]
Fails for me on master too with the following reproduce line:
```
./gradlew ':x-pack:plugin:sql:test' --tests "org.elasticsearch.xpack.sql.tree.NodeSubclassTests" -Dtests.method="testReplaceChildren {p0=class org.elasticsearch.xpack.sql.plan.logical.Pivot}" -Dtests.seed=B778830AC368FB2E -Dtests.security.manager=true -Dtests.locale=ga-IE -Dtests.timezone=Asia/Kuwait
```

**Comment by costin** [comment]
More scans detailing the failure:

https://gradle-enterprise.elastic.co/s/ep7cass7ykyii
https://gradle-enterprise.elastic.co/s/zmfddxrllim4c

**Comment by hub-cap** [comment]
Another today

https://gradle-enterprise.elastic.co/s/r74udmz5mb6tc

**Comment by dimitris-athanasiou** [comment]
And another one here: https://gradle-enterprise.elastic.co/s/qy5y7uu2a6guy/tests/ihtizrmlhavwa-jrtvjtda2so76?openStackTraces=WzBd

Not sure why we haven't muted this yet. I'll find out if there's a reason and I'll mute it if there's not.

**Comment by matriv** [comment]
Muted the test for Pivot in `master`, `7.x` and `7.5`.

**Comment by matriv** [comment]
Fixed in `master` (for now) as part of #49693

**Comment by matriv** [comment]
Unmuted the test in `master` : 4b9b9edbcf2041a8619b65580bbe192bf424cebc
in `7.x` : 48e74203072182c59020f65e4777324abfc00fec

Didn't unmute for `7.5` since the #49693 refactoring won't be backported there.

**Comment by przemekwitek** [comment]
Reopening as this failed again today:


[6.8.7] https://gradle-enterprise.elastic.co/s/kyjmyf3a7dduc
[7.6.1] https://gradle-enterprise.elastic.co/s/qg6cxf4llg67u
https://gradle-enterprise.elastic.co/s/5zyaahfcoteae

Reproduce lines:
```
REPRODUCE WITH: gradlew ':x-pack:plugin:sql:test' --tests "org.elasticsearch.xpack.sql.tree.SqlNodeSubclassTests" \
  -Dtests.method="testReplaceChildren {p0=class org.elasticsearch.xpack.ql.expression.predicate.operator.comparison.In}" \
  -Dtests.seed=6CDD4667F032DF98 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-EC \
  -Dtests.timezone=Europe/Gibraltar \
  -Dcompiler.java=13

REPRODUCE WITH: gradlew ':x-pack:plugin:sql:test' --tests "org.elasticsearch.xpack.sql.tree.SqlNodeSubclassTests" \
  -Dtests.method="testReplaceChildren {p0=class org.elasticsearch.xpack.ql.expression.predicate.operator.comparison.In}" \
  -Dtests.seed=6CDD4667F032DF98 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-EC \
  -Dtests.timezone=Europe/Gibraltar \
  -Dcompiler.java=13
```

Exceprt from logs:
```
14:58:48 * What went wrong:
14:58:48 Execution failed for task ':x-pack:plugin:sql:test'.
14:58:48 > There were failing tests. See the report at: file:///C:/Users/jenkins/workspace/elastic+elasticsearch+7.x+multijob-windows-compatibility/os/windows-2016/x-pack/plugin/sql/build/reports/tests/test/index.html
```

**Comment by astefan** [comment]
@przemekwitek this is the wrong issue. The failure you report is more likely related to https://github.com/elastic/elasticsearch/issues/52951.
