### ISSUE TITLE
given  below error when i am converting elasticsearch version  6.4.2 to 7.4.2 

### ISSUE THREAD

**Issue by vgupta1234** [elastic/elasticsearch#48938]
NoNodeAvailableException[None of the configured nodes were available: [{LAPTOP-RCONJOJT}{AImXEVk5TAi2Wg_9awnUDg}{0AzHtHpGQqCND7rRSV4CvA}{127.0.0.1}{127.0.0.1:9300}{dilm}{ml.machine_memory=8494747648, ml.max_open_jobs=20, xpack.installed=true}]]; nested: NodeDisconnectedException[[LAPTOP-RCONJOJT][127.0.0.1:9300][indices:data/write/bulk] disconnected];
	at org.elasticsearch.client.transport.TransportClientNodesService$RetryListener.onFailure(TransportClientNodesService.java:294)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:59)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1120)
	at org.elasticsearch.transport.TransportService$8.run(TransportService.java:982)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:703)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by cbuescher** [comment]
Hi @ vgupta1234! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
