### ISSUE TITLE
Multiple mixed_cluster/30_ml_jobs_crud/ fail with: Unexpected job state [failed] while waiting for job to be opened

### ISSUE THREAD

**Issue by alpar-t** [elastic/elasticsearch#48933]
There seem to be other failures in this YML too, see #48383 

https://gradle-enterprise.elastic.co/s/sujff2osdiyac/tests/failed

```
reason" : "Unexpected job state [failed] while waiting for job to be opened",
        "stack_trace" : "ElasticsearchException[Unexpected job state [failed] while waiting for job to be opened]
	at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.serverError(ExceptionsHelper.java:38)
	at org.elasticsearch.xpack.ml.action.TransportOpenJobAction$JobPredicate.test(TransportOpenJobAction.java:912)
	at org.elasticsearch.xpack.ml.action.TransportOpenJobAction$JobPredicate.test(TransportOpenJobAction.java:866)
	at org.elasticsearch.persistent.PersistentTasksService.lambda$waitForPersistentTaskCondition$2(PersistentTasksService.java:156)
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.clusterChanged(ClusterStateObserver.java:188)
	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateListeners$7(ClusterApplierService.java:495)
	at java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3527)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:492)
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:475)
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:419)
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:163)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"
```

**Comment by droberts195** [comment]
From `v6.8.5-2/logs/v6.8.5.log` in the server-side logs:

```
Caused by: java.io.FileNotFoundException: /dev/shm/elastic+elasticsearch+7.x+multijob+fast+bwc/x-pack/qa/rolling-upgrade/build/testclusters/v6.8.5-2/tmp/autodetect_old-cluster-job_log_9388 (No such file or directory)
```

So it's exactly the same problem as #48941.  And this build also ran on Debian 9.

**Comment by droberts195** [comment]
Closing as it was the same underlying problem as #48941, and that is now fixed.
