### ISSUE TITLE
AutoFollowIT#testPauseAndResumeWithMultipleAutoFollowPatterns failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#48982]
This PR build failed: https://gradle-enterprise.elastic.co/s/ercrostvlu5k2/console-log?task=:x-pack:plugin:ccr:internalClusterTest

```
org.elasticsearch.xpack.ccr.AutoFollowIT > testPauseAndResumeWithMultipleAutoFollowPatterns FAILED
    java.lang.AssertionError: 
    Expected: a value equal to or greater than <9L>
         but: <8L> was less than <9L>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ccr.AutoFollowIT.lambda$testPauseAndResumeWithMultipleAutoFollowPatterns$33(AutoFollowIT.java:533)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:874)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:847)
        at org.elasticsearch.xpack.ccr.AutoFollowIT.testPauseAndResumeWithMultipleAutoFollowPatterns(AutoFollowIT.java:533)

    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=487, name=Thread-4, state=RUNNABLE, group=TGRP-AutoFollowIT]

        Caused by:
        java.lang.AssertionError
            at __randomizedtesting.SeedInfo.seed([2F4CFB3BB06F1141]:0)
            at org.junit.Assert.fail(Assert.java:86)
            at org.junit.Assert.assertTrue(Assert.java:41)
            at org.junit.Assert.assertTrue(Assert.java:52)
            at org.elasticsearch.xpack.ccr.AutoFollowIT.lambda$testPauseAndResumeWithMultipleAutoFollowPatterns$22(AutoFollowIT.java:503)
            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:874)
            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:847)
            at org.elasticsearch.xpack.ccr.AutoFollowIT.lambda$testPauseAndResumeWithMultipleAutoFollowPatterns$23(AutoFollowIT.java:503)
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ccr:internalClusterTest' --tests "org.elasticsearch.xpack.ccr.AutoFollowIT.testPauseAndResumeWithMultipleAutoFollowPatterns" -Dtests.seed=2F4CFB3BB06F1141 -Dtests.security.manager=true -Dtests.locale=ar-EG -Dtests.timezone=Africa/Porto-Novo -Dcompiler.java=12 -Druntime.java=11
```

Build stats shows other occasional failures of this test recently. The `REPRODUCE WITH` line does not reproduce it for me, but running the test in a loop did yield a failure within a few hundred attempts. There seems to be another (possibly-related) failure of this form too:

```
  2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:ccr:internalClusterTest' --tests "org.elasticsearch.xpack.ccr.AutoFollowIT.testPauseAndResumeWithMultipleAutoFollowPatterns {seed=[32D8D58CB0002449:59EC7D8F7D331D14]}" -Dtests.seed=32D8D58CB0002449 -Dtests.security.manager=true -Dtests.jvms=4 -Dtests.locale=be-BY -Dtests.timezone=America/Fort_Nelson -Dcompiler.java=12 -Druntime.java=12
  2> java.lang.AssertionError: 
    Expected: <20>
         but: was <19>
        at __randomizedtesting.SeedInfo.seed([32D8D58CB0002449:59EC7D8F7D331D14]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ccr.AutoFollowIT.testPauseAndResumeWithMultipleAutoFollowPatterns(AutoFollowIT.java:552)
```

**Comment by mayya-sharipova** [comment]
The test failed today on master.
Doesn't reproduce for me.
```
./gradlew ':x-pack:plugin:ccr:internalClusterTest' --tests "org.elasticsearch.xpack.ccr.AutoFollowIT.testPauseAndResumeAutoFollowPattern" \
  -Dtests.seed=9D9732D4ADAB6E77 \
  -Dtests.security.manager=true \
  -Dtests.locale=is-IS \
  -Dtests.timezone=America/Resolute \
  -Dcompiler.java=13
```

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk13,ES_RUNTIME_JAVA=openjdk13,nodes=general-purpose/483/console
Build Scans: https://gradle-enterprise.elastic.co/s/mcc454srxwtfi

Relevant stacktrace
```
Expected: <5>
     but: was <3>
java.lang.AssertionError: 

Expected: <5>
     but: was <3>
```
