### ISSUE TITLE
[CI] SharedClusterSnapshotRestoreIT#testGetSnapshotsRequest test failure

### ISSUE THREAD

**Issue by hub-cap** [elastic/elasticsearch#49048]
Reproduce (7.x) with:
```
./gradlew ':server:integTest' --tests "org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.testGetSnapshotsRequest" \
  -Dtests.seed=14BDD5A1147CE32 \
  -Dtests.security.manager=true \
  -Dtests.locale=zh-TW \
  -Dtests.timezone=Europe/Skopje \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

Stacktrace:
```
RepositoryException[[test-repo] Could not determine repository generation from root blobs]; nested: NoSuchFileException[/dev/shm/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA/openjdk12/ES_RUNTIME_JAVA/adoptopenjdk11/nodes/general-purpose/server/build/testrun/integTest/temp/org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT_14BDD5A1147CE32-001/tempDir-002/repos/qWSrDrNepA/index-2];
	at __randomizedtesting.SeedInfo.seed([14BDD5A1147CE32:80CBD44E913E7FFF]:0)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:911)
	at org.elasticsearch.snapshots.SnapshotsService.getRepositoryData(SnapshotsService.java:169)
	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:99)
	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:56)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:98)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$3(TransportMasterNodeAction.java:169)
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.NoSuchFileException: /dev/shm/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA/openjdk12/ES_RUNTIME_JAVA/adoptopenjdk11/nodes/general-purpose/server/build/testrun/integTest/temp/org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT_14BDD5A1147CE32-001/tempDir-002/repos/qWSrDrNepA/index-2
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:145)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at org.apache.lucene.mockfile.FilterFileSystemProvider.readAttributes(FilterFileSystemProvider.java:177)
	at org.apache.lucene.mockfile.FilterFileSystemProvider.readAttributes(FilterFileSystemProvider.java:177)
	at org.apache.lucene.mockfile.FilterFileSystemProvider.readAttributes(FilterFileSystemProvider.java:177)
	at org.apache.lucene.mockfile.FilterFileSystemProvider.readAttributes(FilterFileSystemProvider.java:177)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
	at org.elasticsearch.common.blobstore.fs.FsBlobContainer.listBlobsByPrefix(FsBlobContainer.java:100)
	at org.elasticsearch.snapshots.mockstore.BlobContainerWrapper.listBlobsByPrefix(BlobContainerWrapper.java:85)
	at org.elasticsearch.snapshots.mockstore.MockRepository$MockBlobStore$MockBlobContainer.listBlobsByPrefix(MockRepository.java:353)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.listBlobsToGetLatestIndexId(BlobStoreRepository.java:1017)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.latestIndexBlobId(BlobStoreRepository.java:999)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:909)
	... 11 more
```

**Comment by original-brownbear** [comment]
This will be fixed by #48944
