### ISSUE TITLE
[CI] buildBwcOssWindowsZip failure in windows-2016

### ISSUE THREAD

**Issue by hub-cap** [elastic/elasticsearch#49058]
https://gradle-enterprise.elastic.co/s/5zhmu5vbcn7cm

in master

```
:distribution:bwc:staged:buildBwcOssWindowsZip
```

Consistently fails with 

```

:distribution:bwc:staged:buildBwcOssWindowsZip FAILED
--
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: C:\Users\jenkins.PACKER-5DA3F31E\.gradle\wrapper\dists\gradle-5.6.2-all\9st6wgf78h16so49nn74lgtbb\gradle-5.6.2-all.zip
[7.5.0] 	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
[7.5.0] 	at org.gradle.wrapper.Install.createDist(Install.java:48)
[7.5.0] 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
[7.5.0] 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)

```

Sorry in advance for a misleading label, I did not know which area to put this under.

**Comment by atorok** [comment]
The strange thing about it is that it's not even the version of Gradle being used.

**Comment by atorok** [comment]
Could it be a race condition between `7.5` and `7.4` both try to provision the same Gradle version. We may not have seen this before because master was on the same version.

**Comment by tvernum** [comment]
Still a problem: https://gradle-enterprise.elastic.co/s/yiw44sg6rcw2s/console-log?task=:distribution:bwc:staged:buildBwcOssWindowsZip#L3

**Comment by andreidan** [comment]
This happened again: https://gradle-enterprise.elastic.co/s/fxooadqwm4wlk/console-log?task=:distribution:bwc:staged:buildBwcOssWindowsZip

**Comment by rjernst** [comment]
Closing this since it hasn't reproduced in a while, and seemed to only happen when building 7.4, which is no longer built.
