### ISSUE TITLE
Array Index Out of Bounds Exception - Elastic 6.8.2

### ISSUE THREAD

**Issue by akhileshbhatia** [elastic/elasticsearch#49072]
On executing the following curl command:

```
curl -H'content-type:application/json' 'http://localhost:9220/_msearch?error_trace=true&pretty' -d '
{"index":["companiestable"],"ignore_unavailable":true,"preference":1572975891903}
{"aggs":{"topicFilters":{"filters":{"filters":[{"span_near":{"clauses":[{"span_term":{"description":"compani"}},{"span_term":{"description":"technolog"}}],"slop":2,"in_order":false}},{"span_near":{"clauses":[{"span_term":{"description":"market"}},{"span_term":{"description":"technolog"}}],"slop":2,"in_order":false}}]},"aggs":{"sampler":{"sampler":{"shard_size":1000},"aggs":{"subtopics":{"terms":{"field":"description","size":48,"include":["market","technolog", "compani"]}}}}}}},"size":0,"_source":{"excludes":[]},"query":{"bool":{"must":[{"match_phrase":{"description":"Real Estate"}},{"wildcard":{"description":"*"}}]}}}
'
```

we get the following error:

```
{
  "responses" : [
    {
      "took" : 12,
      "timed_out" : false,
      "_shards" : {
        "total" : 5,
        "successful" : 1,
        "skipped" : 0,
        "failed" : 4,
        "failures" : [
          {
            "shard" : 1,
            "index" : "companiestable",
            "node" : "y2dEMXn3Sd6qaR4jYByMow",
            "reason" : {
              "type" : "array_index_out_of_bounds_exception",
              "reason" : "1"
            }
          }
        ]
      },
...
```
despite the query being a valid query. This is happening for elasticsearch version 6.8.2 for [this](https://drive.google.com/drive/folders/1R_IFv-c0SqMYpZDUNHY22zQ34J2cBbbj?usp=sharing) data folder.

**Comment by cbuescher** [comment]
Hi @akhileshbhatia, thanks for raising this. To get a better understanding if this is a bug or something else I'd like to ask if you can get us the stack trace leading to the ArrayIndexOutOfBoundsException from the elasticsearch logs. Also if you can share your index mapping and settings, that might help. I see you are searching across all indices, is that intended? Should all indices share the same schema?

**Comment by cbuescher** [comment]
Actually, looks like the `_search` is only targeting one index here ("companiestable"), so please ignore that part of the question. Here's the query in nicer format for future reference again:
```
{
	"aggs": {
		"topicFilters": {
			"filters": {
				"filters": [{
					"span_near": {
						"clauses": [{
							"span_term": {
								"description": "compani"
							}
						}, {
							"span_term": {
								"description": "technolog"
							}
						}],
						"slop": 2,
						"in_order": false
					}
				}, {
					"span_near": {
						"clauses": [{
							"span_term": {
								"description": "market"
							}
						}, {
							"span_term": {
								"description": "technolog"
							}
						}],
						"slop": 2,
						"in_order": false
					}
				}]
			},
			"aggs": {
				"sampler": {
					"sampler": {
						"shard_size": 1000
					},
					"aggs": {
						"subtopics": {
							"terms": {
								"field": "description",
								"size": 48,
								"include": ["market", "technolog", "compani"]
							}
						}
					}
				}
			}
		}
	},
	"size": 0,
	"_source": {
		"excludes": []
	},
	"query": {
		"bool": {
			"must": [{
				"match_phrase": {
					"description": "Real Estate"
				}
			}, {
				"wildcard": {
					"description": "*"
				}
			}]
		}
	}
}
```

**Comment by akhileshbhatia** [comment]
Here are the mappings:
```
$ curl 'http://localhost:9200/companiestable/_mappings?pretty'
{
  "companiestable" : {
    "mappings" : {
      "doc" : {
        "properties" : {
          "@timestamp" : {
            "type" : "date"
          },
          "blog_feed_url" : {
            "type" : "keyword"
          },
          "blog_url" : {
            "type" : "keyword"
          },
          "category_code" : {
            "type" : "keyword"
          },
          "city" : {
            "type" : "keyword"
          },
          "company" : {
            "properties" : {
              "category_code" : {
                "type" : "keyword"
              },
              "name" : {
                "properties" : {
                  "label" : {
                    "type" : "keyword"
                  }
                }
              },
              "number_of_employees" : {
                "type" : "float"
              }
            }
          },
          "countrycode" : {
            "type" : "keyword"
          },
          "deadpooled_date" : {
            "type" : "keyword"
          },
          "description" : {
            "type" : "text",
            "analyzer" : "english",
            "fielddata" : true
          },
          "email_address" : {
            "type" : "keyword"
          },
          "founded_date" : {
            "type" : "keyword"
          },
          "founded_month" : {
            "type" : "float"
          },
          "founded_year" : {
            "type" : "keyword"
          },
          "freebaseid" : {
            "type" : "keyword"
          },
          "hasstatus" : {
            "type" : "keyword"
          },
          "homepage_url" : {
            "type" : "keyword"
          },
          "id" : {
            "type" : "keyword"
          },
          "label" : {
            "type" : "keyword"
          },
          "label-not-analyzed" : {
            "type" : "keyword"
          },
          "location" : {
            "properties" : {
              "lat" : {
                "type" : "float"
              },
              "lon" : {
                "type" : "float"
              }
            }
          },
          "number_of_employees" : {
            "type" : "float"
          },
          "one_competitor" : {
            "type" : "keyword"
          },
          "overview" : {
            "type" : "text",
            "analyzer" : "english",
            "fielddata" : true
          },
          "permalink" : {
            "type" : "keyword"
          },
          "phone_number" : {
            "type" : "keyword"
          },
          "revenue" : {
            "type" : "keyword"
          },
          "revenuecurrency" : {
            "type" : "keyword"
          },
          "revenuedate" : {
            "type" : "keyword"
          },
          "statecode" : {
            "type" : "keyword"
          },
          "url" : {
            "type" : "keyword"
          },
          "webpage" : {
            "type" : "keyword"
          }
        }
      }
    }
  }
}
```

**Comment by akhileshbhatia** [comment]
Here are the settings

```
{
  "web-service-webhose-news-results-webhose-news" : {
    "settings" : {
      "index" : {
        "creation_date" : "1573043557213",
        "number_of_shards" : "5",
        "number_of_replicas" : "1",
        "uuid" : "qw-bFL8WT2-ocRYsTY8o0Q",
        "version" : {
          "created" : "6080299"
        },
        "provided_name" : "web-service-webhose-news-results-webhose-news"
      }
    }
  },
  "companiestable" : {
    "settings" : {
      "index" : {
        "creation_date" : "1573043721306",
        "number_of_shards" : "5",
        "number_of_replicas" : "1",
        "uuid" : "EUCotdczTnmPAQ6mIIMD7Q",
        "version" : {
          "created" : "6080299"
        },
        "provided_name" : "companiestable"
      }
    }
  },
  ".siren" : {
    "settings" : {
      "index" : {
        "creation_date" : "1573043555169",
        "number_of_shards" : "5",
        "number_of_replicas" : "1",
        "uuid" : "BpbsPKDETMeu7zkLV8wiNg",
        "version" : {
          "created" : "6080299"
        },
        "provided_name" : ".siren"
      }
    }
  },
  "watcher_alarms-2019.11.06" : {
    "settings" : {
      "index" : {
        "creation_date" : "1573043556797",
        "number_of_shards" : "5",
        "number_of_replicas" : "1",
        "uuid" : "DiWcjcg6SCmcjhk6-THSsA",
        "version" : {
          "created" : "6080299"
        },
        "provided_name" : "watcher_alarms-2019.11.06"
      }
    }
  },
  "web-service-webhose-news-invocations" : {
    "settings" : {
      "index" : {
        "creation_date" : "1573043556625",
        "number_of_shards" : "5",
        "number_of_replicas" : "1",
        "uuid" : "jYRQdliyStCOIUgyiccJoQ",
        "version" : {
          "created" : "6080299"
        },
        "provided_name" : "web-service-webhose-news-invocations"
      }
    }
  }
}
```

**Comment by akhileshbhatia** [comment]
And here is the log file [elasticsearch.log](https://github.com/elastic/elasticsearch/files/3846942/elasticsearch.log)

**Comment by cbuescher** [comment]
Thanks, from the logs, the exception seems to come from a call the SamplerAggregator makes:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at org.elasticsearch.common.util.BigArrays$ObjectArrayWrapper.get(BigArrays.java:345) ~[elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.search.aggregations.bucket.sampler.BestDocsDeferringCollector.getDocCount(BestDocsDeferringCollector.java:286) ~[elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.search.aggregations.bucket.sampler.SamplerAggregator.buildAggregation(SamplerAggregator.java:170) ~[elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.bucketAggregations(BucketsAggregator.java:141) ~[elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.search.aggregations.bucket.filter.FiltersAggregator.buildAggregation(FiltersAggregator.java:174) ~[elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.search.aggregations.AggregationPhase.execute(AggregationPhase.java:130) ~[elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:120) ~[elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.indices.IndicesService.lambda$loadIntoContext$17(IndicesService.java:1253) ~[elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.indices.IndicesService.lambda$cacheShardLevelResult$18(IndicesService.java:1309) ~[elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.indices.IndicesRequestCache$Loader.load(IndicesRequestCache.java:164) ~[elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.indices.IndicesRequestCache$Loader.load(IndicesRequestCache.java:147) ~[elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.common.cache.Cache.computeIfAbsent(Cache.java:433) ~[elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.indices.IndicesRequestCache.getOrCompute(IndicesRequestCache.java:119) ~[elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.indices.IndicesService.cacheShardLevelResult(IndicesService.java:1315) ~[elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.indices.IndicesService.loadIntoContext(IndicesService.java:1251) ~[elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:348) ~[elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:394) ~[elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.search.SearchService.access$100(SearchService.java:126) ~[elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:359) [elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:355) [elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.search.SearchService$4.doRun(SearchService.java:1107) [elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) [elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) [elasticsearch-6.8.2.jar:6.8.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.8.2.jar:6.8.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```
Lets see if this gives us a better idea about whats wrong.

**Comment by polyfractal** [comment]
Thanks for grabbing that exception @cbuescher, and thanks @akhileshbhatia for the detailed debug info! On quick skim, it seems that sampler might not be playing nice with deferred execution.  

On the road at the moment so haven't looked closely, but definitely think this is a bug somewhere.

**Comment by akhileshbhatia** [comment]
Hey guys, is there any update about this issue? Is anything going on related to it?

**Comment by JackRyanson** [comment]
@polyfractal @cbuescher glad i found this, we're experiencing exactly the same issue i believe. Is this any ETA to have this addressed? thanks all.

**Comment by polyfractal** [comment]
@akhileshbhatia @JackRyanson I don't believe anyone has looked into this particular bug yet, so a fix timeline is still unknown.  This ticket will be updated when there is progress.

@JackRyanson would you be able to paste the query/aggregation that you're using which is triggering the bug?  It might be helpful if we can see a commonality with @akhileshbhatia's query (e.g. does yours also have a filter agg? Span queries?  Terms agg? etc).  Also, may I ask what version you're on?

Does this reproduce if you use a simpler query in the `filter` agg?  The span queries are particularly complicated, so I'm wondering if it's a general problem with `sampler + filter`, or `sampler + filter + span`.  

Might be hard to disentangle since this looks like the bug is triggering due to deferred execution, which means the docs being collected will probably affect the bug triggering.

Lastly, would you mind re-running with the sampler agg's `execution_mode` set to each of these and see if one of them works or breaks?

- `"execution_hint": "map"`
- `"execution_hint": "bytes_hash"`
- `"execution_hint": "global_ordinals"`

Note: map/bytes_hash will be more expensive than the default (global ords), so make sure your cluster is healthy / has some memory before testing :)

**Comment by daniele-pini** [comment]
Hi all, I've been investigating the issue with @akhileshbhatia, looking for temporary workarounds.

The `execution_hint` just doesn't apply here, since the reported query uses a `sampler` aggregation, while the `execution_hint` seems to apply only for `diversified_sampler` aggregations.

Apart from that, I have noticed that the problem _seems_ to disappear (in all cases I tested) if I happen to add a dummy 1-bucket `terms` aggregation right before the `sampler` one, like this:
```
"aggs": {
  "dummy_terms_wrapper": {
    "terms": {
      "field": "__not_present__",
      "missing": ""
    },
    "aggs": {
      "sampler": {
        "sampler" ...
      }
    }
  }
}
```
there's a small performance hit in adding this layer, but it seems to solve the problem in our cases.

No real idea if this actually works in ALL cases, or why though - so take this 'workaround' with a grain of salt.

**Comment by polyfractal** [comment]
Ah apologies, you're right regarding `execution_hint`.  The settings are defined in the sampler aggregator code, but only used in the diversified-sampler parser which I didn't notice.

Unsure why that workaround currently works.  If it's related to deferred execution it might make sense, as multi-bucket aggs like terms aggs do some things internally (wrapping other aggs to reset ordinals) and only having a single term means only one bucket ordinal...which might fix the bug inadvertently.  A single filter agg might have a similar effect.

I see from the first post's log that this is a 6.8.2 cluster?  Could you try testing 6.8.3+ with the same data?  There was a [bugfix in 6.8.3+ that affects `sampler`](https://github.com/elastic/elasticsearch/pull/44963) (among other aggs).  Early termination was not handled correctly, and could lead to incorrect results.  The symptoms in the original bugfix ticket are different, but I could see it potentially causing array OOB issues too.  Or maybe not :)

I'm downloading the data from the OP and will see if I can recreate the issue locally.

**Comment by daniele-pini** [comment]
Thanks for the explanation, @polyfractal.

> Could you try testing 6.8.3+ with the same data?

I just tried with a fresh 6.8.5, but unfortunately I can still reproduce the problem the OP reported.
The upgrade didn't help.

**Comment by polyfractal** [comment]
Good to know, thanks for checking @daniele-pini 

I'll see if I can reproduce locally and drop some debug breakpoints to figure out what's going on :)

**Comment by fabiocorneti** [comment]
@polyfractal could the issue be that, if there are no documents to collect from the first bucket, `perBucketSamples` will not be grown at https://github.com/elastic/elasticsearch/blob/e82818a3613766c5221d9e7c3bb88f1d536083da/server/src/main/java/org/elasticsearch/search/aggregations/bucket/sampler/BestDocsDeferringCollector.java#L295-L297 , causing the out of bounds at https://github.com/elastic/elasticsearch/blob/e82818a3613766c5221d9e7c3bb88f1d536083da/server/src/main/java/org/elasticsearch/search/aggregations/bucket/sampler/BestDocsDeferringCollector.java#L308-L314 ?

---

Can be reproduced more easily with the following script on Elasticsearch 6.8.6:

```bash
curl -H "Content-Type: application/json" -XDELETE http://localhost:9200/foo
curl -H "Content-Type: application/json" -XDELETE http://localhost:9200/bar

curl -H "Content-Type: application/json" -XPUT http://localhost:9200/foo -d '{
  "settings" : {
    "index" : {
      "number_of_shards" : 1,
      "number_of_replicas" : 0
    }
  },
  "mappings": {
    "_doc": {
      "properties": {
        "description": {
          "type": "keyword"
        }
      }
    }
  }
}'
curl -H "Content-Type: application/json" -XPUT http://localhost:9200/bar -d '{
  "settings" : {
    "index" : {
      "number_of_shards" : 1,
      "number_of_replicas" : 0
    }
  },
  "mappings": {
    "_doc": {
      "properties": {
        "description": {
          "type": "keyword"
        }
      }
    }
  }
}'
curl -H "Content-Type: application/x-ndjson" -XPOST http://localhost:9200/_bulk -d '
{ "index" : { "_index" : "foo", "_type": "_doc", "_id" : "1" } }
{ "description" : "table" }
{ "index" : { "_index" : "bar", "_type": "_doc", "_id" : "1" } }
{ "description" : "table" }
{ "index" : { "_index" : "foo", "_type": "_doc", "_id" : "2" } }
{ "description" : "sofa" }
{ "index" : { "_index" : "bar", "_type": "_doc", "_id" : "2" } }
{ "description" : "rock" }
'

curl -XPOST 'http://localhost:9200/foo,bar/_refresh'

echo
echo
echo "====== SEARCH ======="
echo
echo

curl -H'content-type:application/json' 'http://localhost:9200/foo,bar/_search?error_trace=true&pretty' -d '
{
  "aggs": {
    "topicFilters": {
      "filters": {
        "filters": [{
          "term": {
            "description": "table"
          }
        }, {
          "term": {
            "description": "cat"
          }
        }]
      },
      "aggs": {
        "sampler": {
          "sampler": {
            "shard_size": 1000
          },
          "aggs": {
            "subtopics": {
              "terms": {
                "field": "description",
                "size": 48,
                "include": ["sofa", "table", "rock"]
              }
            }
          }
        }
      }
    }
  },
  "size": 1
}'
```

---

This appears to be the same bug: https://github.com/elastic/elasticsearch/issues/19891 .

**Comment by polyfractal** [comment]
@fabiocorneti I think that might be it, good work!  I still haven't had a chance to look closely (keep getting pulled away into other things), but that certainly looks like it could blow up if no buckets are collected, or if the tail end of the buckets are not collected by the sampler agg.

A simple
```
if (perBucketSamples.size() <= parentBucket) {
    return 0;
}
```

I think would safeguard against that?  Or something similar anyhow.  Want to open a PR to fix?  If not I'll see if someone on the analytics team has time to work up a fix and a test.

Cheers!

**Comment by fabiocorneti** [comment]
@polyfractal apologies, missed the notification, I'll open a PR tomorrow.

**Comment by immavalls** [comment]
@polyfractal @DaveCTurner Can we resume work on this on our side? @fabiocorneti was not able to open the PR. Thanks!

**Comment by fabiocorneti** [comment]
Hi there, sorry for the delay, I opened PR #59360  with a test case for this issue and the check.

**Comment by yogevyuval** [comment]
Hi @fabiocorneti @immavalls @polyfractal  , I know this is already closed but I just encountered something very similar while testing ES 7.9.1
Can you please take a look and tell me if this is related?
This happens on the following query when min_doc_count is 0.
The error is: Index -1 out of bounds for length 1

```
{
  "query": {
    "bool": {
      "must": [
        {
          "match_all": {}
        }
      ],
      "filter": [
        {
          "range": {
            "@timestamp": {
              "gte": "2016-08-22T15:39:52+00:00",
              "lte": "2016-08-24T14:37:05+00:00"
            }
          }
        }
      ]
    }
  },
  "aggs": {
    "1d93e6": {
      "terms": {
        "field": "srccountry.keyword_lower",
        "size": 10,
        "min_doc_count": 0,
        "missing": "N/A",
        "show_term_doc_count_error": true
      },
      "meta": {
        "as_": "terms(srccountry)",
        "field_name": "srccountry",
        "func_name": "terms",
        "type": "text"
      },
      "aggs": {
        "f28e02": {
          "sum": {
            "script": {
              "source": "1",
              "lang": "expression"
            }
          },
          "meta": {
            "as_": "count() by srccountry",
            "field_name": "",
            "func_name": "count",
            "type": "long"
          }
        }
      }
    }
  },
  "sort": [
    {
      "@timestamp": {
        "order": "desc",
        "unmapped_type": "date"
      }
    }
  ]
}
```

Stack trace


```

at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:551) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:309) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:582) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:393) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$100(AbstractSearchAsyncAction.java:68) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:245) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:59) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:403) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.transport.TransportService$6.handleException(TransportService.java:638) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1172) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1281) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1255) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:61) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.transport.TransportChannel.sendErrorResponse(TransportChannel.java:56) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:51) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:414) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:710) [elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.9.1.jar:7.9.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: org.elasticsearch.ElasticsearchException$1: Index -1 out of bounds for length 1
	at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:644) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:307) [elasticsearch-7.9.1.jar:7.9.1]
	... 21 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1
	at org.elasticsearch.common.util.BigArrays$DoubleArrayWrapper.get(BigArrays.java:257) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.aggregations.metrics.SumAggregator.buildAggregation(SumAggregator.java:117) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.aggregations.metrics.MetricsAggregator.buildAggregations(MetricsAggregator.java:51) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildSubAggsForBuckets(BucketsAggregator.java:173) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildSubAggsForAllBuckets(BucketsAggregator.java:236) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator.access$700(GlobalOrdinalsStringTermsAggregator.java:65) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator$StandardTermsResults.buildSubAggs(GlobalOrdinalsStringTermsAggregator.java:720) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator$StandardTermsResults.buildSubAggs(GlobalOrdinalsStringTermsAggregator.java:670) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator$ResultStrategy.buildAggregations(GlobalOrdinalsStringTermsAggregator.java:586) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator$ResultStrategy.access$200(GlobalOrdinalsStringTermsAggregator.java:535) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator.buildAggregations(GlobalOrdinalsStringTermsAggregator.java:193) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.aggregations.Aggregator.buildTopLevel(Aggregator.java:160) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.aggregations.AggregationPhase.execute(AggregationPhase.java:128) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:156) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:362) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:435) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.access$200(SearchService.java:136) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:396) ~[elasticsearch-7.9.1.jar:7.9.1]
	at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:412) ~[elasticsearch-7.9.1.jar:7.9.1]
```

**Comment by fabiocorneti** [comment]
@yogevyuval I think the problem you hit is https://github.com/elastic/elasticsearch/issues/62084 , fixed in https://github.com/elastic/elasticsearch/pull/62130 .
