### ISSUE TITLE
Unable to start elasticsearch service with xpack security

### ISSUE THREAD

**Issue by rehannali** [elastic/elasticsearch#49132]
**Elasticsearch version** (`bin/elasticsearch --version`):
> Version: 7.4.2, Build: default/deb/2f90bbf7b93631e52bafb59b3b049cb44ec25e96/2019-10-28T20:40:44.881551Z, JVM: 1.8.0_211
**Plugins installed**: []

**JVM version** (`java -version`):
> java version "1.8.0_211"
> Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
> Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

Hi, I install elastic search using `sudo dpkg -i /path-to-file/installer.deb` on ubuntu. Recently I tried to enable the security feature but after I add lines in elasticsearch.yml, service refuses to start it. I tried to read log, documentation but got nothing. 
If I remove xpack setting from yml file then it works fine.

I perform these steps on my mac machine and it works fine but on ubuntu, service not starting after security feature enabled.

**Configuration**

```conf
# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
cluster.name: oneload_elasticsearch
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
#node.name: node-1
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
path.data: /var/lib/elasticsearch
#
# Path to log files:
#
path.logs: /var/log/elasticsearch
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: 0.0.0.0
#
# Set a custom port for HTTP:
#
http.port: 9200
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when this node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
discovery.seed_hosts: ["127.0.0.1", "[::1]", "localhost","10.100.101.41"]
#
# Bootstrap the cluster using an initial set of master-eligible nodes:
#
#cluster.initial_master_nodes: ["node-1", "node-2"]
#
# For more information, consult the discovery and cluster formation module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
# ---------------------------------- Security ----------------------------------
xpack.security.enabled: true
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.keystore.path: /path-to-cert/elastic-certificates.p12
xpack.security.http.ssl.truststore.path: /path-to-cert/elastic-certificates.p12
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: /path-to-cert/elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: /path-to-cert/elastic-certificates.p12
```

**Provide logs (if relevant)**:

```
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:238)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:250)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:547)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:234)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:127)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:310)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.cli.Command.main(Command.java:90)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]: 2019-11-15 08:55:07,314 main ERROR Unable to invoke factory method in class org.apache.logging.log4j.core.appender.Roll
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:235)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:135)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:959
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:89
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:89
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:514)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:238)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:250)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:547)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:234)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:127)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:310)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.cli.Command.main(Command.java:90)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]: 2019-11-15 08:55:07,342 main ERROR Null object returned for RollingFile in Appenders.
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]: 2019-11-15 08:55:07,343 main ERROR Null object returned for RollingFile in Appenders.
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]: 2019-11-15 08:55:07,344 main ERROR Unable to locate appender "rolling" for logger config "root"
Nov 15 08:55:07 Oneload-QADB elasticsearch[19819]: 2019-11-15 08:55:07,344 main ERROR Unable to locate appender "rolling_old" for logger config "root"
Nov 15 08:55:08 Oneload-QADB systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
Nov 15 08:55:08 Oneload-QADB systemd[1]: Failed to start Elasticsearch.
-- Subject: Unit elasticsearch.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit elasticsearch.service has failed.
-- 
-- The result is failed.
Nov 15 08:55:08 Oneload-QADB systemd[1]: elasticsearch.service: Unit entered failed state.
Nov 15 08:55:08 Oneload-QADB systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
Nov 15 08:55:08 Oneload-QADB sudo[19780]: pam_unix(sudo:session): session closed for user root
```

**Comment by tvernum** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests. The discussion forums are beter suited to these sorts of troubleshooting and problem diagnosis conversations.

There's an active community in the forum that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Thank you.
