### ISSUE TITLE
SQL: extracting PIVOTed column by value fails

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#49163]
If extracting a pivoted column by its alias, the query works as expected:
```
sql> SELECT languages, XX FROM (SELECT languages, gender, salary FROM test_emp) PIVOT (AVG(salary) FOR gender IN ('M', 'F' as XX));
   languages   |        XX
---------------+------------------
null           |62140.666666666664
1              |47073.25
2              |50684.4
3              |53660.0
4              |49291.5
5              |46705.555555555555
```

However, if using the value:
```
sql> SELECT languages, 'F' FROM (SELECT languages, gender, salary FROM test_emp) PIVOT (AVG(salary) FOR gender IN ('M', 'F'));
```
it fails with the exception:
```
Server error [Server encountered an error [Cannot resolve field extractor index for column ['F'{c}#18512]]. [org.elasticsearch.xpack.sql.SqlIllegalArgumentException: Cannot resolve field extractor index for column ['F'{c}#18512]
        at org.elasticsearch.xpack.sql.querydsl.container.QueryContainer.columnMask(QueryContainer.java:203)
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseAggActionListener.<init>(Querier.java:376)
        at org.elasticsearch.xpack.sql.execution.search.Querier$CompositeActionListener.<init>(Querier.java:333)
        at org.elasticsearch.xpack.sql.execution.search.Querier.query(Querier.java:132)
        at org.elasticsearch.xpack.sql.plan.physical.EsQueryExec.execute(EsQueryExec.java:59)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$sql$5(SqlSession.java:164)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$physicalPlan$4(SqlSession.java:160)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$optimizedPlan$3(SqlSession.java:156)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$preAnalyze$2(SqlSession.java:144)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
        at org.elasticsearch.xpack.sql.analysis.index.IndexResolver.lambda$resolveAsMergedMapping$3(IndexResolver.java:277)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
        at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:89)
        at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:144)
        at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:138)
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)
        at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.lambda$doExecute$0(TransportFieldCapabilitiesAction.java:88)
        at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:101)
        at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:97)
        at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:89)
        at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:144)
        at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:138)
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:261)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:247)
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1049)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1127)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1107)
        at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:54)
        at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:47)
        at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:30)
        at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:58)
        at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:769)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
]]
```

**Comment by Luegg** [comment]
While looking into https://github.com/elastic/elasticsearch/issues/80952 I was thinking about this feature as well. My conclusion though was, referencing pivoted columns by their value should not be supported. It would change the normal semantics of a constant in a projection: The `'A'` in `SELECT 'A' FROM test_emp` means to output `'A'` for every record in `test_emp`.
