### ISSUE TITLE
PainlessScriptEngine.generateStatefulFactory fails with ASM 7.1/7.2

### ISSUE THREAD

**Issue by vlsi** [elastic/elasticsearch#49218]
PainlessScriptEngine.generateStatefulFactory fails with ASM 7.1/7.2

The failure is discovered with https://github.com/apache/calcite/tree/master/elasticsearch tests

**Elasticsearch version** (`bin/elasticsearch --version`): elasticsearch-7.4.2.jar, lang-painless-7.4.2.jar

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Darwin ....local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

Apache Calcite tests do not work if ASM 7.1 or later is used.

```
   Caused by: org.elasticsearch.script.GeneralScriptException: Failed to compile inline script [params._source.loc[0]] using lang [painless]
        at org.elasticsearch.script.ScriptService.compile(ScriptService.java:361) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:846) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:586) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:545) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:348) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$1(SearchService.java:340) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.ActionListener.lambda$map$2(ActionListener.java:145) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.4.2.jar:7.4.2]
        ... 9 more
    Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.Type.getTypeInternal(Type.java:443) ~[asm-7.2.jar:7.2]
        at org.objectweb.asm.Type.getType(Type.java:177) ~[asm-7.2.jar:7.2]
        at org.elasticsearch.painless.PainlessScriptEngine.generateStatefulFactory(PainlessScriptEngine.java:199) ~[lang-painless-7.4.2.jar:7.4.2]
        at org.elasticsearch.painless.PainlessScriptEngine.compile(PainlessScriptEngine.java:143) ~[lang-painless-7.4.2.jar:7.4.2]
        at org.elasticsearch.script.ScriptService.compile(ScriptService.java:356) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:846) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:586) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:545) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:348) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$1(SearchService.java:340) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.ActionListener.lambda$map$2(ActionListener.java:145) ~[elasticsearch-7.4.2.jar:7.4.2]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62) ~[elasticsearch-7.4.2.jar:7.4.2]
        ... 9 more
```

**Steps to reproduce**:

I'm afraid "build Apache Calcite" does not sound like a minimal test case, however I can provide such instructions if you want.

Here's the Elastic code:

https://github.com/elastic/elasticsearch/blob/master/modules/lang-painless/src/main/java/org/elasticsearch/painless/PainlessScriptEngine.java#L233

Painless uses `Type.getType(String)` with **String** arguments like `package/package/Class$Factory`, however, `Type.getType(String)` expects JVM descriptor like `J` for boolean, `Ljava/lang/String;` for `java.lang.String` and so on.

See tests here: 
 https://gitlab.ow2.org/asm/asm/blob/8486f1034f5634e4e2d2e95faa3bcbee4a199bd7/asm/src/test/java/org/objectweb/asm/TypeTest.java#L117

I guess you need to use `Type.getObjectType`: https://gitlab.ow2.org/asm/asm/blob/8486f1034f5634e4e2d2e95faa3bcbee4a199bd7/asm/src/test/java/org/objectweb/asm/TypeTest.java#L131-133

**Comment by jdconrad** [comment]
Confirmed the issue as ASM has changed the code for `getType` between versions.
