### ISSUE TITLE
[CI] ReindexFailureTests testResponseOnSearchFailure fails on CI

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#49295]
The test `ReindexFailureTests testResponseOnSearchFailure` failed multiple on CI today on master and 7.x branches:
https://gradle-enterprise.elastic.co/s/xjodptpkel2tq
https://gradle-enterprise.elastic.co/s/bgg6g2npo4epu
https://gradle-enterprise.elastic.co/s/kh4jcenda3mvi
https://gradle-enterprise.elastic.co/s/yxfqraa4vukpi

It reproduces locally on 7.x with :
```
./gradlew ':modules:reindex:test' --tests "org.elasticsearch.index.reindex.ReindexFailureTests.testResponseOnSearchFailure" -Dtests.seed=47226BB65839127C -Dtests.security.manager=true -Dtests.locale=de-DE -Dtests.timezone=Asia/Brunei -Dcompiler.java=12 -Druntime.java=8
```

**Comment by jimczi** [comment]
Rreopening after another failure in 7x with a different string:
````
org.elasticsearch.index.reindex.ReindexFailureTests > testResponseOnSearchFailure FAILED
--
java.lang.AssertionError:
Expected: (((a string containing "all shards failed" or a string containing "No search context found") or a string containing "no such index [source]") or a string containing "Failed to execute phase [query], Partial shards failure")
but: was "RemoteTransportException[[node_s0][127.0.0.1:37333][indices:data/write/reindex]]; nested: SearchPhaseExecutionException[Partial shards failure (1 shards unavailable)];"
at __randomizedtesting.SeedInfo.seed([E04AF90BC989047C:DBC02D3DAD32AFF6]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.index.reindex.ReindexFailureTests.testResponseOnSearchFailure(ReindexFailureTests.java:118)
REPRODUCE WITH: ./gradlew ':modules:reindex:test' --tests "org.elasticsearch.index.reindex.ReindexFailureTests.testResponseOnSearchFailure" -Dtests.seed=E04AF90BC989047C -Dtests.security.manager=true -Dtests.locale=mt-MT -Dtests.timezone=Europe/Busingen -Dcompiler.java=12 -Druntime.java=8
````

**Comment by markharwood** [comment]
Another failure today on 7.x which reproduces

    ./gradlew ':modules:reindex:test' --tests "org.elasticsearch.index.reindex.ReindexFailureTests.testResponseOnSearchFailure" -Dtests.seed=1CD9FF092A5CCFA4 -Dtests.security.manager=true -Dtests.locale=es-UY -Dtests.timezone=Mexico/BajaNorte -Dcompiler.java=12 -Druntime.java=8
