### ISSUE TITLE
SQL: "Should not fold expression" for conditional function

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#49387]
`SELECT IIF(20 = 0, NULL, salary / 20) FROM test_emp`

results in

```
org.elasticsearch.xpack.sql.SqlIllegalArgumentException: Should not fold expression
        at org.elasticsearch.xpack.sql.expression.Expression.fold(Expression.java:72) ~[?:?]
        at org.elasticsearch.xpack.sql.expression.predicate.BinaryPredicate.fold(BinaryPredicate.java:32) ~[?:?]
        at org.elasticsearch.xpack.sql.expression.predicate.conditional.Case.fold(Case.java:132) ~[?:?]
        at org.elasticsearch.xpack.sql.expression.Literal.of(Literal.java:159) ~[?:?]
        at org.elasticsearch.xpack.sql.expression.Literal.of(Literal.java:144) ~[?:?]
        at org.elasticsearch.xpack.sql.optimizer.Optimizer$ConstantFolding.rule(Optimizer.java:1238) ~[?:?]
        at org.elasticsearch.xpack.sql.tree.Node.transformDown(Node.java:174) ~[?:?]
```

**Comment by matriv** [comment]
`master` : f35c9725350e35985d8dd3001870084e1784a5ca
`7.x` : 40eb7b3dab5e58ae8c41c808397fbd7df3077328
`7.5` : 2508cc76e96143b8bfd04c2a1277107217399737
`7.4` : 73087ee44a63c541a335cbd6a322a51f88a15079
