### ISSUE TITLE
[CI] 400 Bad request creating snapshot in GoogleCloudStorageThirdPartyTests

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#49429]
org.elasticsearch.repositories.gcs.GoogleCloudStorageThirdPartyTests.testCreateSnapshot [failed](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part1/2385/testReport/junit/org.elasticsearch.repositories.gcs/GoogleCloudStorageThirdPartyTests/testCreateSnapshot/) with a "400 bad request".

Stacktrace: 

	com.google.cloud.storage.StorageException: 400 Bad Request
		at __randomizedtesting.SeedInfo.seed([4A7CE93B6DE34759:B41A7C885B50B540]:0)
		at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:227)
		at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:308)
		at com.google.cloud.storage.StorageImpl$3.call(StorageImpl.java:192)
		at com.google.cloud.storage.StorageImpl$3.call(StorageImpl.java:189)
		at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
		at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
		at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
		at com.google.cloud.storage.StorageImpl.internalCreate(StorageImpl.java:188)
		at com.google.cloud.storage.StorageImpl.create(StorageImpl.java:150)
		at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.lambda$writeBlobMultipart$8(GoogleCloudStorageBlobStore.java:308)
		at org.elasticsearch.repositories.gcs.SocketAccess.lambda$doPrivilegedVoidIOException$0(SocketAccess.java:54)
		at java.base/java.security.AccessController.doPrivileged(Native Method)
		at org.elasticsearch.repositories.gcs.SocketAccess.doPrivilegedVoidIOException(SocketAccess.java:53)
		at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.writeBlobMultipart(GoogleCloudStorageBlobStore.java:307)
		at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.writeBlob(GoogleCloudStorageBlobStore.java:221)
		at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainer.writeBlob(GoogleCloudStorageBlobContainer.java:67)
		at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainer.writeBlobAtomic(GoogleCloudStorageBlobContainer.java:72)
		at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:907)
		at org.elasticsearch.repositories.RepositoriesService$3.doRun(RepositoriesService.java:246)
		at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:688)
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:834)
	Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
		at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
		at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
		at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
		at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:528)
		at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:448)
		at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
		at com.google.cloud.storage.spi.v1.HttpStorageRpc.create(HttpStorageRpc.java:305)
    

Repro line (did not reproduce for me):

    REPRODUCE WITH: ./gradlew ':plugins:repository-gcs:qa:google-cloud-storage:thirdPartyTest' --tests "org.elasticsearch.repositories.gcs.GoogleCloudStorageThirdPartyTests.testCreateSnapshot" -Dtests.seed=4A7CE93B6DE34759 -Dtests.security.manager=false -Dtests.locale=en-GB -Dtests.timezone=Pacific/Samoa -Dcompiler.java=12

Not muting for now given I can't reproduce.

**Comment by original-brownbear** [comment]
This is running against a GCS mock as well (not a real third party test run). Likely this has similar originals #49400 and all the associated test failures.

**Comment by tlrx** [comment]
Thanks to @original-brownbear, #49518 should fix this issues. I'm closing for now and we'll reopen or reference if this issue happens again.

**Comment by benwtrent** [comment]
New build failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian-10&&immutable/443/console

```
13:08:09 org.elasticsearch.repositories.gcs.GoogleCloudStorageThirdPartyTests > testCreateSnapshot FAILED
13:08:09     com.google.cloud.storage.StorageException: 400 Bad Request
13:08:09 
13:08:09         Caused by:
13:08:09         com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
```

Reproduce line:
```
./gradlew ':plugins:repository-gcs:qa:google-cloud-storage:thirdPartyTest' --tests "org.elasticsearch.repositories.gcs.GoogleCloudStorageThirdPartyTests.testCreateSnapshot" -Dtests.seed=D18AB3DA9ABE738D -Dtests.security.manager=false -Dtests.locale=en-SG -Dtests.timezone=Etc/GMT-3 -Dcompiler.java=12
```

**Comment by ywelsch** [comment]
@original-brownbear is this still an issue?

**Comment by original-brownbear** [comment]
@ywelsch this particular exception is impossible now => let's close this one. There's still some test failures in these tests though, but I'll open a new issue or PR for those.

**Comment by original-brownbear** [comment]
Nevermind ... my bad, this si still a posisble issue sorry for the noise. Leaving this open.

**Comment by original-brownbear** [comment]
Closing this after all. The `400` that was thrown here is removed from our code. I found another spot of broken multi-part request parsing that might apply here and have caused this past `400`  that is now an assertion error (fix for that incoming in https://github.com/elastic/elasticsearch/pull/50666), but the exact error seen here isn't a thing any longer.
