### ISSUE TITLE
SQL: aliased FLOOR and CEIL functions fail with NPE

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#49556]
`SELECT FLOOR(CAST(NULL AS DOUBLE)) AS x FROM test_emp`

results in 

```
java.lang.NullPointerException: null
        at org.elasticsearch.xpack.sql.expression.function.scalar.math.Floor.fold(Floor.java:36) ~[?:?]
        at org.elasticsearch.xpack.sql.expression.NamedExpression.asPipe(NamedExpression.java:56) ~[?:?]
        at org.elasticsearch.xpack.sql.expression.function.scalar.ScalarFunction.toAttribute(ScalarFunction.java:39) ~[?:?]
        at org.elasticsearch.xpack.sql.expression.function.scalar.ScalarFunction.toAttribute(ScalarFunction.java:23) ~[?:?]
        at org.elasticsearch.xpack.sql.expression.Expressions.attribute(Expressions.java:150) ~[?:?]
        at org.elasticsearch.xpack.sql.expression.Alias.createAttribute(Alias.java:109) ~[?:?]
        at org.elasticsearch.xpack.sql.expression.Alias.toAttribute(Alias.java:95) ~[?:?]
        at org.elasticsearch.xpack.sql.optimizer.Optimizer$ReplaceFoldableAttributes.lambda$rule$0(Optimizer.java:1143) ~[?:?]
        at org.elasticsearch.xpack.sql.tree.Node.lambda$forEachDown$1(Node.java:74) ~[?:?]
        at org.elasticsearch.xpack.sql.tree.Node.forEachDown(Node.java:66) ~[?:?]
        at org.elasticsearch.xpack.sql.tree.Node.forEachDown(Node.java:72) ~[?:?]
        at org.elasticsearch.xpack.sql.optimizer.Optimizer$ReplaceFoldableAttributes.rule(Optimizer.java:1139) ~[?:?]
        at org.elasticsearch.xpack.sql.optimizer.Optimizer$ReplaceFoldableAttributes.apply(Optimizer.java:1130) ~[?:?]
        at org.elasticsearch.xpack.sql.optimizer.Optimizer$ReplaceFoldableAttributes.apply(Optimizer.java:1126) ~[?:?]
        at org.elasticsearch.xpack.sql.rule.RuleExecutor$Transformation.<init>(RuleExecutor.java:82) ~[?:?]
        at org.elasticsearch.xpack.sql.rule.RuleExecutor.executeWithInfo(RuleExecutor.java:158) ~[?:?]
        at org.elasticsearch.xpack.sql.rule.RuleExecutor.execute(RuleExecutor.java:130) ~[?:?]
        at org.elasticsearch.xpack.sql.optimizer.Optimizer.optimize(Optimizer.java:122) ~[?:?]
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$optimizedPlan$3(SqlSession.java:156) ~[?:?]
```

**Comment by astefan** [comment]
master (8.0.0): https://github.com/elastic/elasticsearch/commit/034f4cf7b4bd062c157d40f1e7a8760de31de568
7.x (7.6.0): https://github.com/astefan/elasticsearch/commit/34311dd8181d1f546d0a28ccbc5f415fa39d80a0
7.5 (7.5.1): https://github.com/elastic/elasticsearch/commit/311867e53e7c6e4e53636990f6d7fcd24fd70b21
