### ISSUE TITLE
SQL: division by zero when grouping by

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#49672]
Similar to https://github.com/elastic/elasticsearch/issues/49388, but this time on the aggregation side, where the Painless script already evaluates the value: 

```
SELECT CASE WHEN languages - 1 = 0 THEN NULL ELSE ( salary / (languages - 1) ) END AS x FROM test_emp GROUP BY 1
```

results in:

```
Caused by: java.lang.ArithmeticException: / by zero
        at org.elasticsearch.xpack.sql.expression.predicate.operator.arithmetic.Arithmetics.div(Arithmetics.java:110) ~[?:?]
        at org.elasticsearch.xpack.sql.expression.predicate.operator.arithmetic.BinaryArithmeticProcessor$NumericArithmetic.wrap(BinaryArithmeticProcessor.java:29) ~[?:?]
        at org.elasticsearch.xpack.sql.expression.predicate.operator.arithmetic.BinaryArithmeticProcessor$BinaryArithmeticOperation.doApply(BinaryArithmeticProcessor.java:131) ~[?:?]
        at org.elasticsearch.xpack.sql.expression.predicate.PredicateBiFunction.apply(PredicateBiFunction.java:24) ~[?:?]
        at org.elasticsearch.xpack.sql.expression.function.scalar.whitelist.InternalSqlScriptUtils.div(InternalSqlScriptUtils.java:198) ~[?:?]
        at org.elasticsearch.painless.PainlessScript$Script.execute(InternalSqlScriptUtils.caseFunction([InternalSqlScriptUtils.eq(InternalSqlScriptUtils.sub(InternalSqlScriptUtils.docValue(doc,params.v0),params.v1),params.v2),params.v3,InternalSqlScriptUtils.div(InternalSqlScriptUtils.docValue(doc,params.v4),InternalSqlSc ...:266) ~[?:?]
        at org.elasticsearch.search.aggregations.support.values.ScriptLongValues.advanceExact(ScriptLongValues.java:51) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.aggregations.bucket.composite.LongValuesSource$1.collect(LongValuesSource.java:174) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:82) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.aggregations.bucket.composite.CompositeAggregator$1.collect(CompositeAggregator.java:190) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:82) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
```

**Comment by matriv** [comment]
@elastic/es-ql

**Comment by matriv** [comment]
`master` : 9584b345d89f797bfb658212b928b9812804f02f
`7.x` : fdac9e99fa8bc0334768d412db8b1178094a53bf
`7.8` : 2a03a136d2a53b9068d533a27af2e31e10f9fa17
`7.7` : b640f0b4f6aa81915cebe865e221ee4028354794
