### ISSUE TITLE
[CI] SimpleDataNodesIT.testAutoExpandReplicasAdjustedWhenDataNodeJoins failure

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#49745]
`SimpleDataNodesIT.testAutoExpandReplicasAdjustedWhenDataNodeJoins` failed in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.4+multijob-unix-compatibility/os=centos-6&&immutable/188/console

with 
```
Stacktrace

java.lang.IllegalStateException: Some shards are still open after the threadpool terminated. Something is leaking index readers or store references.
	at __randomizedtesting.SeedInfo.seed([C7E368BE0EFBB53D:817AC7B44703B925]:0)
	at org.elasticsearch.node.Node.awaitClose(Node.java:903)
	at org.elasticsearch.test.InternalTestCluster$NodeAndClient.close(InternalTestCluster.java:1055)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:104)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:86)
	at org.elasticsearch.test.InternalTestCluster.close(InternalTestCluster.java:851)
	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:588)
	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2128)
```

A build scan is available at https://gradle-enterprise.elastic.co/s/wuz3ald6v3tow

I was not able to reproduce it locally with ~1000 iterations.

Reproduce with: `./gradlew ':server:integTest' --tests "org.elasticsearch.cluster.SimpleDataNodesIT.testAutoExpandReplicasAdjustedWhenDataNodeJoins" \
  -Dtests.seed=C7E368BE0EFBB53D \
  -Dtests.security.manager=true \
  -Dtests.locale=es-EC \
  -Dtests.timezone=CNT \
  -Dcompiler.java=12 \
  -Druntime.java=8
`

**Comment by ywelsch** [comment]
AFAICS this test has only been failing on the 7.4 branch (about once per week for the past 2 months), and things look to have been fixed in 7.5+. With this branch not seeing any active development anymore, I will close this issue.
