### ISSUE TITLE
[CI]JdbcResultSetIT.testGettingInvalidInteger failure

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#49769]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk13,nodes=general-purpose/362/console

Fails with: 
```
org.junit.ComparisonFailure: expected:<...e [+21464908-02-17T0[3:36:40.860+01:00]] of type [DATETIME]...> but was:<...e [+21464908-02-17T0[2:36:40.860Z]] of type [DATETIME]...> |  
> 	at __randomizedtesting.SeedInfo.seed([B5270A7B3FA31BBD:8F725AF9FEB935C9]:0)	
> 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.lambda$testGettingInvalidInteger$75(ResultSetTestCase.java:512)	
> 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1402)	
> 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1390)	
> 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.testGettingInvalidInteger(ResultSetTestCase.java:486)
```

Reproduce with: 
```
./gradlew ':x-pack:plugin:sql:qa:single-node:integTestRunner' \
  -Dtests.seed=D8675D9622BD95C7 \
  -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT \
  -Dtests.method="testGettingInvalidInteger" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-IM \
  -Dtests.timezone=Europe/Belgrade \
  -Dcompiler.java=12 \
  -Druntime.java=13
```

I was unable to reproduce it locally. It seems to have started failing on the 12th of September 2019.

There are a few build scans available:
https://gradle-enterprise.elastic.co/s/nxoci5t55ehuu/console-log?task=:x-pack:plugin:sql:qa:single-node:integTestRunner
https://gradle-enterprise.elastic.co/s/a7z2fhrwr6e4a/console-log?task=:x-pack:plugin:sql:qa:single-node:integTestRunner
https://gradle-enterprise.elastic.co/s/xh5i6lrytl5w4/console-log?task=:x-pack:plugin:sql:qa:single-node:integTestRunner
This seems to fail every now and then

**Comment by davidkyle** [comment]
Different test - **testGettingInvalidByte** but the error is the same. Again on the 6.8 branch

```

FAILURE 0.14s \| JdbcResultSetIT.testGettingInvalidByte <<< FAILURES! |  
-- | --
  | > Throwable #1: org.junit.ComparisonFailure: expected:<... [+130760646-12-05T1[1:10:27.401-04]:00] of type [DATETI...> but was:<... [+130760646-12-05T1[2:10:27.401-03]:00] of type [DATETI...> |  
  | > 	at __randomizedtesting.SeedInfo.seed([540A99E543F0E472:A65F4E4120D75F31]:0) |  
  | > 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.lambda$testGettingInvalidByte$37(ResultSetTestCase.java:274) |  
  | > 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1402) |  
  | > 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1390) |  
  | > 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.testGettingInvalidByte(ResultSetTestCase.java:238)
```

https://gradle-enterprise.elastic.co/s/iy5opbmcxjdns

```
./gradlew ':x-pack:plugin:sql:qa:single-node:integTestRunner' \
  -Dtests.seed=540A99E543F0E472 \
  -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT \
  -Dtests.method="testGettingInvalidByte" \
  -Dtests.security.manager=true \
  -Dtests.locale=so-SO \
  -Dtests.timezone=Europe/Moscow \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

**Comment by astefan** [comment]
Fixed with https://github.com/elastic/elasticsearch/pull/51592
