### ISSUE TITLE
[CI] Failure in SumIT.testSingleValuedFieldWithFormatter

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#49778]
In https://gradle-enterprise.elastic.co/s/zyfrpx2dhy4tq/console-log?anchor=4774  `7.x`

```
REPRODUCE WITH: ./gradlew ':server:integTest' --tests "org.elasticsearch.search.aggregations.metrics.SumIT.testSingleValuedFieldWithFormatter" -Dtests.seed=51FCA3F5A8A9E7FA -Dtests.security.manager=true -Dtests.locale=is-IS -Dtests.timezone=IST -Dcompiler.java=12 -Druntime.java=8
 
```

Fails with some NPE:

```

org.elasticsearch.search.aggregations.metrics.SumIT > testSingleValuedFieldWithFormatter FAILED |  
-- | --
  | Failed to execute phase [dfs_query], |  
  |   |  
  | Caused by: |  
  | java.lang.NullPointerException

```

**Comment by iverase** [comment]
I found more errors like this one, it does not reproduce. The stack trace looks like:

```
Caused by: java.lang.NullPointerException
	at org.elasticsearch.action.search.SearchProgressListener.searchShards(SearchProgressListener.java:166)
	at org.elasticsearch.action.search.SearchPhaseController$QueryPhaseResultConsumer.consumeInternal(SearchPhaseController.java:639)
	at org.elasticsearch.action.search.SearchPhaseController$QueryPhaseResultConsumer.consumeResult(SearchPhaseController.java:617)
	at org.elasticsearch.action.search.CountedCollector.onResult(CountedCollector.java:62)
	at org.elasticsearch.action.search.DfsQueryPhase$1.innerOnResponse(DfsQueryPhase.java:89)
	... 24 more
```

This seems be related with PR #49471, @jimczi any ideas?

**Comment by iverase** [comment]
I think the error come from this call:

https://github.com/elastic/elasticsearch/blob/cab99c036a665f6864dbb38fdf7059b03b0ea767/server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java#L639

This is a bit out my depth but the method is synchronised by the result that is given to the method seems to be shared across threads so I wonder if this isa concurrency issue.
