### ISSUE TITLE
[CI] Failure in MinDocCountIT.testDateHistogramCountDesc

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#49817]
In `master`:

```
./gradlew ':server:integTest' --tests "org.elasticsearch.search.aggregations.bucket.MinDocCountIT.testDateHistogramCountDesc" -Dtests.seed=2E88B31E803B0D2D -Dtests.security.manager=true -Dtests.locale=id-ID -Dtests.timezone=Portugal -Dcompiler.java=12
```

Failed with the following NPE:

```
org.elasticsearch.action.search.SearchPhaseExecutionException: (No message provided)Close stacktrace
at __randomizedtesting.SeedInfo.seed([2E88B31E803B0D2D:CAC48BB042ED425C]:0)
at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:545)
at org.elasticsearch.action.search.DfsQueryPhase$1.innerOnResponse(DfsQueryPhase.java:91)
at org.elasticsearch.action.search.DfsQueryPhase$1.innerOnResponse(DfsQueryPhase.java:84)
at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:45)
at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:29)
at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:54)
at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleResponse(SearchTransportService.java:414)
at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1049)
at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:219)
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:196)
at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:211)
at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:137)
at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:101)
at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:673)
at org.elasticsearch.transport.TcpTransport.consumeNetworkReads(TcpTransport.java:697)
at org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:276)
at org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:228)
at org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:40)
at org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:139)
at org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:151)
at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:420)
at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:246)
at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:174)
at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:131)
at java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: (No message provided)Close stacktrace
at org.elasticsearch.action.search.SearchProgressListener.searchShards(SearchProgressListener.java:165)
at org.elasticsearch.action.search.SearchPhaseController$QueryPhaseResultConsumer.consumeInternal(SearchPhaseController.java:639)
at org.elasticsearch.action.search.SearchPhaseController$QueryPhaseResultConsumer.consumeResult(SearchPhaseController.java:617)
at org.elasticsearch.action.search.CountedCollector.onResult(CountedCollector.java:62)
at org.elasticsearch.action.search.DfsQueryPhase$1.innerOnResponse(DfsQueryPhase.java:89)
at org.elasticsearch.action.search.DfsQueryPhase$1.innerOnResponse(DfsQueryPhase.java:84)
at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:45)
at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:29)
at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:54)
at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleResponse(SearchTransportService.java:414)
at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1049)
at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:219)
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:196)
at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:211)
at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:137)
at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:101)
at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:673)
at org.elasticsearch.transport.TcpTransport.consumeNetworkReads(TcpTransport.java:697)
at org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:276)
at org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:228)
at org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:40)
at org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:139)
at org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:151)
at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:420)
at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:246)
at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:174)
at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:131)
at java.lang.Thread.run(Thread.java:834)
```

**Comment by iverase** [comment]
I think this is the same as #49778

**Comment by iverase** [comment]
I am closing this issue on behalf of  #49778
