### ISSUE TITLE
Elasticsearch cant start - JvmOptionsParser exception

### ISSUE THREAD

**Issue by eserkelleci** [elastic/elasticsearch#49852]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 7.5.0, Build: default/zip/e9ccaed468e2fac2275a3761849cbee64b39519f/2019-11-26T01:06:52.518245Z, JVM: 13.0.1

**Plugins installed**: []

**JVM version** (`java -version`):
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Windows 10 Professional 
Version	10.0.18363 Build 18363

**Description of the problem including expected versus actual behavior**:
Trying to start elasticsearch through bin/elasticsearch.bat and it throws exception from JvmOptionsParser. 

**Steps to reproduce**:
 1. E:\Desktop\elasticsearch-7.5.0\bin>elasticsearch.bat

**Provide logs (if relevant)**:
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 36: **E:\Desktop\elasticsearch-7.5.0\bin\E:\Desktop\elasticsearch-7.5.0\config\jvm.options**
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:62)

**Comment by astefan** [comment]
@eserkelleci do you mind posting this question in the [forums](https://discuss.elastic.co/)?

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

For what is worth, I've just tested a vanilla ES 7.5.0 with Java 1.8.0_231 on Windows 10 Pro and I'm not seeing this issue.

**Comment by eserkelleci** [comment]
Thanks for the information. It was just a fresh setup and doesn't change anything so i thought it may be bug.
