### ISSUE TITLE
Multicast discovery is broken when network.host is set an IPv6 address

### ISSUE THREAD

**Issue by pieterlexis** [elastic/elasticsearch#4989]
At FOSDEM, I was fiddling around with ES 1.0RC1 on my laptop. When you bind explicitly to an IPv6 address, multicast discovery is broken.

When I start the instances, I get the following logs:

```
lieter $ ./bin/elasticsearch
[2014-02-02 16:19:18,501][INFO ][node                     ] [Lorvex] version[1.0.0.RC1], pid[4386], build[c6155c5/2014-01-15T17:02:32Z]
[2014-02-02 16:19:18,506][INFO ][node                     ] [Lorvex] initializing ...
[2014-02-02 16:19:18,507][DEBUG][node                     ] [Lorvex] using home [/home/lieter/workspace/elasticsearch/elasticsearch-1.0.0.RC1], config [/home/lieter/workspace/elasticsearch/elasticsearch-1.0.0.RC1/config], data [[/home/lieter/workspace/elasticsearch/elasticsearch-1.0.0.RC1/data]], logs [/home/lieter/workspace/elasticsearch/elasticsearch-1.0.0.RC1/logs], work [/home/lieter/workspace/elasticsearch/elasticsearch-1.0.0.RC1/work], plugins [/home/lieter/workspace/elasticsearch/elasticsearch-1.0.0.RC1/plugins]
[2014-02-02 16:19:18,523][INFO ][plugins                  ] [Lorvex] loaded [], sites []
[2014-02-02 16:19:18,567][DEBUG][common.compress.lzf      ] using [UnsafeChunkDecoder] decoder
[2014-02-02 16:19:18,592][DEBUG][env                      ] [Lorvex] using node location [[/home/lieter/workspace/elasticsearch/elasticsearch-1.0.0.RC1/data/elasticsearch/nodes/0]], local_node_id [0]
[2014-02-02 16:19:21,168][DEBUG][threadpool               ] [Lorvex] creating thread_pool [generic], type [cached], keep_alive [30s]
[2014-02-02 16:19:21,190][DEBUG][threadpool               ] [Lorvex] creating thread_pool [index], type [fixed], size [2], queue_size [200]
[2014-02-02 16:19:21,197][DEBUG][threadpool               ] [Lorvex] creating thread_pool [bulk], type [fixed], size [2], queue_size [50]
[2014-02-02 16:19:21,198][DEBUG][threadpool               ] [Lorvex] creating thread_pool [get], type [fixed], size [2], queue_size [1k]
[2014-02-02 16:19:21,198][DEBUG][threadpool               ] [Lorvex] creating thread_pool [search], type [fixed], size [6], queue_size [1k]
[2014-02-02 16:19:21,198][DEBUG][threadpool               ] [Lorvex] creating thread_pool [suggest], type [fixed], size [2], queue_size [1k]
[2014-02-02 16:19:21,199][DEBUG][threadpool               ] [Lorvex] creating thread_pool [percolate], type [fixed], size [2], queue_size [1k]
[2014-02-02 16:19:21,199][DEBUG][threadpool               ] [Lorvex] creating thread_pool [management], type [scaling], min [1], size [5], keep_alive [5m]
[2014-02-02 16:19:21,201][DEBUG][threadpool               ] [Lorvex] creating thread_pool [flush], type [scaling], min [1], size [1], keep_alive [5m]
[2014-02-02 16:19:21,204][DEBUG][threadpool               ] [Lorvex] creating thread_pool [merge], type [scaling], min [1], size [1], keep_alive [5m]
[2014-02-02 16:19:21,204][DEBUG][threadpool               ] [Lorvex] creating thread_pool [refresh], type [scaling], min [1], size [1], keep_alive [5m]
[2014-02-02 16:19:21,205][DEBUG][threadpool               ] [Lorvex] creating thread_pool [warmer], type [scaling], min [1], size [1], keep_alive [5m]
[2014-02-02 16:19:21,205][DEBUG][threadpool               ] [Lorvex] creating thread_pool [snapshot], type [scaling], min [1], size [1], keep_alive [5m]
[2014-02-02 16:19:21,205][DEBUG][threadpool               ] [Lorvex] creating thread_pool [optimize], type [fixed], size [1], queue_size [null]
[2014-02-02 16:19:21,267][DEBUG][transport.netty          ] [Lorvex] using worker_count[4], port[9300-9400], bind_host[null], publish_host[null], compress[false], connect_timeout[30s], connections_per_node[2/3/6/1/1], receive_predictor[512kb->512kb]
[2014-02-02 16:19:21,290][DEBUG][discovery.zen.ping.multicast] [Lorvex] using group [224.2.2.4], with port [54328], ttl [3], and address [null]
[2014-02-02 16:19:21,299][DEBUG][discovery.zen.ping.unicast] [Lorvex] using initial hosts [], with concurrent_connects [10]
[2014-02-02 16:19:21,301][DEBUG][discovery.zen            ] [Lorvex] using ping.timeout [3s], master_election.filter_client [true], master_election.filter_data [false]
[2014-02-02 16:19:21,310][DEBUG][discovery.zen.elect      ] [Lorvex] using minimum_master_nodes [-1]
[2014-02-02 16:19:21,315][DEBUG][discovery.zen.fd         ] [Lorvex] [master] uses ping_interval [1s], ping_timeout [30s], ping_retries [3]
[2014-02-02 16:19:21,343][DEBUG][discovery.zen.fd         ] [Lorvex] [node  ] uses ping_interval [1s], ping_timeout [30s], ping_retries [3]
[2014-02-02 16:19:21,465][DEBUG][monitor.jvm              ] [Lorvex] enabled [true], last_gc_enabled [false], interval [1s], gc_threshold [{old=GcThreshold{name='old', warnThreshold=10000, infoThreshold=5000, debugThreshold=2000}, default=GcThreshold{name='default', warnThreshold=10000, infoThreshold=5000, debugThreshold=2000}, young=GcThreshold{name='young', warnThreshold=1000, infoThreshold=700, debugThreshold=400}}]
[2014-02-02 16:19:21,992][DEBUG][monitor.os               ] [Lorvex] Using probe [org.elasticsearch.monitor.os.SigarOsProbe@1d3302a5] with refresh_interval [1s]
[2014-02-02 16:19:22,003][DEBUG][monitor.process          ] [Lorvex] Using probe [org.elasticsearch.monitor.process.SigarProcessProbe@7dc2445f] with refresh_interval [1s]
[2014-02-02 16:19:22,013][DEBUG][monitor.jvm              ] [Lorvex] Using refresh_interval [1s]
[2014-02-02 16:19:22,021][DEBUG][monitor.network          ] [Lorvex] Using probe [org.elasticsearch.monitor.network.SigarNetworkProbe@8a97164] with refresh_interval [5s]
[2014-02-02 16:19:22,041][DEBUG][monitor.network          ] [Lorvex] net_info
host [lieters-klaptop]
wlan0	display_name [wlan0]
		address [/2001:67c:1810:f051:222:fbff:fec9:1314%3] [/fe80:0:0:0:222:fbff:fec9:1314%3] 
		mtu [1500] multicast [true] ptp [false] loopback [false] up [true] virtual [false]
lo	display_name [lo]
		address [/0:0:0:0:0:0:0:1%1] [/127.0.0.1] 
		mtu [65536] multicast [false] ptp [false] loopback [true] up [true] virtual [false]

[2014-02-02 16:19:22,075][DEBUG][monitor.fs               ] [Lorvex] Using probe [org.elasticsearch.monitor.fs.SigarFsProbe@16c0e304] with refresh_interval [1s]
[2014-02-02 16:19:22,946][DEBUG][indices.store            ] [Lorvex] using indices.store.throttle.type [MERGE], with index.store.throttle.max_bytes_per_sec [20mb]
[2014-02-02 16:19:22,969][DEBUG][cache.memory             ] [Lorvex] using bytebuffer cache with small_buffer_size [1kb], large_buffer_size [1mb], small_cache_size [10mb], large_cache_size [500mb], direct [true]
[2014-02-02 16:19:23,005][DEBUG][script                   ] [Lorvex] using script cache with max_size [500], expire [null]
[2014-02-02 16:19:23,026][DEBUG][cluster.routing.allocation.decider] [Lorvex] using node_concurrent_recoveries [2], node_initial_primaries_recoveries [4]
[2014-02-02 16:19:23,027][DEBUG][cluster.routing.allocation.decider] [Lorvex] using [cluster.routing.allocation.allow_rebalance] with [indices_all_active]
[2014-02-02 16:19:23,035][DEBUG][cluster.routing.allocation.decider] [Lorvex] using [cluster_concurrent_rebalance] with [2]
[2014-02-02 16:19:23,047][DEBUG][gateway.local            ] [Lorvex] using initial_shards [quorum], list_timeout [30s]
[2014-02-02 16:19:23,353][DEBUG][indices.recovery         ] [Lorvex] using max_bytes_per_sec[20mb], concurrent_streams [3], file_chunk_size [512kb], translog_size [512kb], translog_ops [1000], and compress [true]
[2014-02-02 16:19:23,420][DEBUG][http.netty               ] [Lorvex] using max_chunk_size[8kb], max_header_size[8kb], max_initial_line_length[4kb], max_content_length[100mb], receive_predictor[512kb->512kb]
[2014-02-02 16:19:23,437][DEBUG][indices.memory           ] [Lorvex] using index_buffer_size [100.7mb], with min_shard_index_buffer_size [4mb], max_shard_index_buffer_size [512mb], shard_inactive_time [30m]
[2014-02-02 16:19:23,444][DEBUG][indices.cache.filter     ] [Lorvex] using [node] weighted filter cache with size [20%], actual_size [201.4mb], expire [null], clean_interval [1m]
[2014-02-02 16:19:23,453][DEBUG][indices.fielddata.cache  ] [Lorvex] using size [-1] [-1b], expire [null]
[2014-02-02 16:19:23,492][DEBUG][gateway.local.state.meta ] [Lorvex] using gateway.local.auto_import_dangled [YES], with gateway.local.dangling_timeout [2h]
[2014-02-02 16:19:23,512][DEBUG][gateway.local.state.meta ] [Lorvex] took 19ms to load state
[2014-02-02 16:19:23,513][DEBUG][gateway.local.state.shards] [Lorvex] took 0s to load started shards state
[2014-02-02 16:19:23,519][DEBUG][bulk.udp                 ] [Lorvex] using enabled [false], host [null], port [9700-9800], bulk_actions [1000], bulk_size [5mb], flush_interval [5s], concurrent_requests [4]
[2014-02-02 16:19:23,539][DEBUG][cluster.routing.allocation.decider] [Lorvex] using node_concurrent_recoveries [2], node_initial_primaries_recoveries [4]
[2014-02-02 16:19:23,542][DEBUG][cluster.routing.allocation.decider] [Lorvex] using [cluster.routing.allocation.allow_rebalance] with [indices_all_active]
[2014-02-02 16:19:23,542][DEBUG][cluster.routing.allocation.decider] [Lorvex] using [cluster_concurrent_rebalance] with [2]
[2014-02-02 16:19:23,544][DEBUG][cluster.routing.allocation.decider] [Lorvex] using node_concurrent_recoveries [2], node_initial_primaries_recoveries [4]
[2014-02-02 16:19:23,544][DEBUG][cluster.routing.allocation.decider] [Lorvex] using [cluster.routing.allocation.allow_rebalance] with [indices_all_active]
[2014-02-02 16:19:23,545][DEBUG][cluster.routing.allocation.decider] [Lorvex] using [cluster_concurrent_rebalance] with [2]
[2014-02-02 16:19:23,578][INFO ][node                     ] [Lorvex] initialized
[2014-02-02 16:19:23,579][INFO ][node                     ] [Lorvex] starting ...
[2014-02-02 16:19:23,612][DEBUG][netty.channel.socket.nio.SelectorUtil] Using select timeout of 500
[2014-02-02 16:19:23,612][DEBUG][netty.channel.socket.nio.SelectorUtil] Epoll-bug workaround enabled = false
[2014-02-02 16:19:23,853][DEBUG][transport.netty          ] [Lorvex] Bound to address [/2001:67c:1810:f051:222:fbff:fec9:1314:9300]
[2014-02-02 16:19:23,854][INFO ][transport                ] [Lorvex] bound_address {inet[/2001:67c:1810:f051:222:fbff:fec9:1314:9300]}, publish_address {inet[/2001:67c:1810:f051:222:fbff:fec9:1314:9300]}
[2014-02-02 16:19:23,932][DEBUG][discovery.zen.ping.multicast] [Lorvex] failed to send multicast ping request
java.io.IOException: Network is unreachable
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:676)
	at org.elasticsearch.discovery.zen.ping.multicast.MulticastZenPing.sendPingRequest(MulticastZenPing.java:274)
	at org.elasticsearch.discovery.zen.ping.multicast.MulticastZenPing.ping(MulticastZenPing.java:237)
	at org.elasticsearch.discovery.zen.ping.ZenPingService.ping(ZenPingService.java:149)
	at org.elasticsearch.discovery.zen.ping.ZenPingService.pingAndWait(ZenPingService.java:127)
	at org.elasticsearch.discovery.zen.ZenDiscovery.findMaster(ZenDiscovery.java:677)
	at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:297)
	at org.elasticsearch.discovery.zen.ZenDiscovery.access$500(ZenDiscovery.java:75)
	at org.elasticsearch.discovery.zen.ZenDiscovery$1.run(ZenDiscovery.java:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
[2014-02-02 16:19:25,446][DEBUG][discovery.zen.ping.multicast] [Lorvex] failed to send multicast ping request
java.io.IOException: Network is unreachable
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:676)
	at org.elasticsearch.discovery.zen.ping.multicast.MulticastZenPing.sendPingRequest(MulticastZenPing.java:274)
	at org.elasticsearch.discovery.zen.ping.multicast.MulticastZenPing.access$100(MulticastZenPing.java:61)
	at org.elasticsearch.discovery.zen.ping.multicast.MulticastZenPing$3.run(MulticastZenPing.java:244)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
[2014-02-02 16:19:26,958][DEBUG][discovery.zen            ] [Lorvex] filtered ping responses: (filter_client[true], filter_data[false]) {none}
[2014-02-02 16:19:26,970][DEBUG][cluster.service          ] [Lorvex] processing [zen-disco-join (elected_as_master)]: execute
[2014-02-02 16:19:26,972][DEBUG][cluster.service          ] [Lorvex] cluster state updated, version [1], source [zen-disco-join (elected_as_master)]
[2014-02-02 16:19:26,974][INFO ][cluster.service          ] [Lorvex] new_master [Lorvex][m6rOwyS2QKeIhpQNLptJcA][lieters-klaptop][inet[/2001:67c:1810:f051:222:fbff:fec9:1314:9300]], reason: zen-disco-join (elected_as_master)
[2014-02-02 16:19:27,043][DEBUG][transport.netty          ] [Lorvex] connected to node [[Lorvex][m6rOwyS2QKeIhpQNLptJcA][lieters-klaptop][inet[/2001:67c:1810:f051:222:fbff:fec9:1314:9300]]]
[2014-02-02 16:19:27,044][DEBUG][cluster.service          ] [Lorvex] publishing cluster state version 1
[2014-02-02 16:19:27,044][DEBUG][cluster.service          ] [Lorvex] set local cluster state to version 1
[2014-02-02 16:19:27,047][DEBUG][river.cluster            ] [Lorvex] processing [reroute_rivers_node_changed]: execute
[2014-02-02 16:19:27,047][DEBUG][river.cluster            ] [Lorvex] processing [reroute_rivers_node_changed]: no change in cluster_state
[2014-02-02 16:19:27,048][DEBUG][cluster.service          ] [Lorvex] processing [zen-disco-join (elected_as_master)]: done applying updated cluster_state (version: 1)
[2014-02-02 16:19:27,048][INFO ][discovery                ] [Lorvex] elasticsearch/m6rOwyS2QKeIhpQNLptJcA
[2014-02-02 16:19:27,066][DEBUG][cluster.service          ] [Lorvex] processing [local-gateway-elected-state]: execute
[2014-02-02 16:19:27,078][DEBUG][cluster.service          ] [Lorvex] cluster state updated, version [2], source [local-gateway-elected-state]
[2014-02-02 16:19:27,078][DEBUG][cluster.service          ] [Lorvex] publishing cluster state version 2
[2014-02-02 16:19:27,079][INFO ][http                     ] [Lorvex] bound_address {inet[/2001:67c:1810:f051:222:fbff:fec9:1314:9200]}, publish_address {inet[/2001:67c:1810:f051:222:fbff:fec9:1314:9200]}
[2014-02-02 16:19:27,083][DEBUG][cluster.service          ] [Lorvex] set local cluster state to version 2
[2014-02-02 16:19:27,090][DEBUG][river.cluster            ] [Lorvex] processing [reroute_rivers_node_changed]: execute
[2014-02-02 16:19:27,091][DEBUG][river.cluster            ] [Lorvex] processing [reroute_rivers_node_changed]: no change in cluster_state
[2014-02-02 16:19:27,102][INFO ][gateway                  ] [Lorvex] recovered [0] indices into cluster_state
[2014-02-02 16:19:27,103][DEBUG][cluster.service          ] [Lorvex] processing [local-gateway-elected-state]: done applying updated cluster_state (version: 2)
[2014-02-02 16:19:27,103][DEBUG][cluster.service          ] [Lorvex] processing [updating local node id]: execute
[2014-02-02 16:19:27,103][DEBUG][cluster.service          ] [Lorvex] cluster state updated, version [3], source [updating local node id]
[2014-02-02 16:19:27,103][DEBUG][cluster.service          ] [Lorvex] publishing cluster state version 3
[2014-02-02 16:19:27,103][DEBUG][cluster.service          ] [Lorvex] set local cluster state to version 3
[2014-02-02 16:19:27,104][DEBUG][river.cluster            ] [Lorvex] processing [reroute_rivers_node_changed]: execute
[2014-02-02 16:19:27,104][DEBUG][river.cluster            ] [Lorvex] processing [reroute_rivers_node_changed]: no change in cluster_state
[2014-02-02 16:19:27,104][DEBUG][cluster.service          ] [Lorvex] processing [updating local node id]: done applying updated cluster_state (version: 3)
[2014-02-02 16:19:27,104][INFO ][node                     ] [Lorvex] started
[2014-02-02 16:19:37,047][DEBUG][cluster.service          ] [Lorvex] processing [routing-table-updater]: execute
[2014-02-02 16:19:37,048][DEBUG][cluster.service          ] [Lorvex] processing [routing-table-updater]: no change in cluster_state
^C[2014-02-02 16:19:43,925][INFO ][node                     ] [Lorvex] stopping ...
[2014-02-02 16:19:43,961][INFO ][node                     ] [Lorvex] stopped
[2014-02-02 16:19:43,961][INFO ][node                     ] [Lorvex] closing ...
[2014-02-02 16:19:43,971][INFO ][node                     ] [Lorvex] closed
```

The configuration is as follows:
```
lieter $ egrep -v '^#|^$' config/elasticsearch.yml
network.host: 2001:67c:1810:f051:222:fbff:fec9:1314
```

But it also fails if you set `network.host` to `::1`.

**Comment by dakrone** [comment]
I believe this is fixed by https://github.com/elastic/elasticsearch/pull/12942
