### ISSUE TITLE
[CI] ConnectionManagerTests.testConcurrentConnectsAndDisconnects timed out

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#49903]
`ConnectionManagerTests.testConcurrentConnectsAndDisconnects` hit the 20 minute test timeout in a couple of builds on the 7.5 branch.

* https://gradle-enterprise.elastic.co/s/367rox57bzflk
* https://gradle-enterprise.elastic.co/s/levbg6qu3y5my

The repro commands are:

```
./gradlew ':server:test' --tests "org.elasticsearch.transport.ConnectionManagerTests.testConcurrentConnectsAndDisconnects" \
  -Dtests.seed=9A5390B666099003 \
  -Dtests.security.manager=true \
  -Dtests.locale=ksh-DE \
  -Dtests.timezone=America/Knox_IN \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

and:

```
./gradlew ':server:test' --tests "org.elasticsearch.transport.ConnectionManagerTests.testConcurrentConnectsAndDisconnects" \
  -Dtests.seed=E8171F27A4EF04C1 \
  -Dtests.security.manager=true \
  -Dtests.locale=en \
  -Dtests.timezone=America/Argentina/La_Rioja \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

Neither reproduces locally.

The error that causes this is:

```
WARNING: Uncaught exception in thread: Thread[elasticsearch[ConnectionManagerTests][generic][T#4],5,TGRP-ConnectionManagerTests]
java.lang.AssertionError: Expected node to be connected
	at __randomizedtesting.SeedInfo.seed([E8171F27A4EF04C1]:0)
	at org.elasticsearch.transport.ConnectionManagerTests.lambda$testConcurrentConnectsAndDisconnects$10(ConnectionManagerTests.java:171)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
	at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:112)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:225)
	at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:106)
	at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:98)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:98)
	at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:144)
	at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:127)
	at org.elasticsearch.transport.ConnectionManager.lambda$connectToNode$1(ConnectionManager.java:165)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
	at org.elasticsearch.transport.ConnectionManagerTests.lambda$testConcurrentConnectsAndDisconnects$7(ConnectionManagerTests.java:148)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:703)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Then the fact that the node is not connected makes the code hang for 20 minutes and trigger the test timeout.

**Comment by droberts195** [comment]
The same problem just occurred in a master branch build: https://gradle-enterprise.elastic.co/s/ndvcwkkioy3au

I will mute the test.

**Comment by droberts195** [comment]
Muting commits:

* master: d68bf19ea32da99c1bfcc1c16f851185e8d9b0e0
* 7.x: 17fa9d584485ad1db627a0494ca781a44a435964
* 7.5: b89ff63eb08794ef50658569672d1d7c2d150fe1

**Comment by DaveCTurner** [comment]
I had a go at reproducing this on 7.5 (1aa983a07c546c344c3c1c6f98684d782ac4dca8 plus a revert of b89ff63eb08794ef50658569672d1d7c2d150fe1) by running this in on a loop on my CI machine:

```
./gradlew ':server:test' --tests "org.elasticsearch.transport.ConnectionManagerTests.testConcurrentConnectsAndDisconnects" -Dtests.failfast=true -Dtests.iters=100
```

I also had `stress -c 24` running in the background in the hope that the extra CPU pressure would help to shake it out. 2½ days later it failed on the 4151th iteration:

```
> Task :server:test

org.elasticsearch.transport.ConnectionManagerTests > testConcurrentConnectsAndDisconnects {seed=[956E8C99B5983973:416EDA3121A00F7]} FAILED
    java.lang.Exception: Test abandoned because suite timeout was reached.

org.elasticsearch.transport.ConnectionManagerTests > classMethod FAILED
    java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).

org.elasticsearch.transport.ConnectionManagerTests > classMethod FAILED
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=644, name=elasticsearch[ConnectionManagerTests][generic][T#2], state=RUNNABLE, group=TGRP-ConnectionManagerTests]

        Caused by:
        java.lang.AssertionError: Expected node to be connected
            at __randomizedtesting.SeedInfo.seed([956E8C99B5983973]:0)
            at org.elasticsearch.transport.ConnectionManagerTests.lambda$testConcurrentConnectsAndDisconnects$10(ConnectionManagerTests.java:171)
            at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
            at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:112)
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
            at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:225)
            at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:106)
            at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:98)
            at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
            at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:98)
            at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:144)
            at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:127)
            at org.elasticsearch.transport.ConnectionManager.lambda$connectToNode$1(ConnectionManager.java:165)
            at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
            at org.elasticsearch.transport.ConnectionManagerTests.lambda$testConcurrentConnectsAndDisconnects$7(ConnectionManagerTests.java:148)
```

**Comment by DaveCTurner** [comment]
Reproduces more reliably with this:

```diff
diff --git a/server/src/main/java/org/elasticsearch/transport/ConnectionManager.java b/server/src/main/java/org/elasticsearch/transport/ConnectionManager.java
index 110053bcee7..260fc03a48e 100644
--- a/server/src/main/java/org/elasticsearch/transport/ConnectionManager.java
+++ b/server/src/main/java/org/elasticsearch/transport/ConnectionManager.java
@@ -124,6 +124,12 @@ public class ConnectionManager implements Closeable {
             return;
         }

+        try {
+            Thread.sleep(Randomness.get().nextInt(500));
+        } catch (InterruptedException e) {
+            throw new AssertionError(e);
+        }
+
         final ListenableFuture<Void> currentListener = new ListenableFuture<>();
         final ListenableFuture<Void> existingListener = pendingConnections.putIfAbsent(node, currentListener);
         if (existingListener != null) {
```

In the test we return the same `Transport.Connection` instance from each call to `openConnection()`, so these lines close the connection we were expecting to reuse:

```
                        if (connectedNodes.putIfAbsent(node, conn) != null) {
                            logger.debug("existing connection to node [{}], closing new redundant connection", node);
                            IOUtils.closeWhileHandlingException(conn);
```

**Comment by tbrooks8** [comment]
Thanks @DaveCTurner. That insight makes this test easy to fix.
