### ISSUE TITLE
[CI] JdbcResultSetIT.testGettingInvalidDouble failed

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#49904]
`JdbcResultSetIT.testGettingInvalidDouble` in a 6.8 build on SLES 12 SP 4:

```
FAILURE 0.23s \| JdbcResultSetIT.testGettingInvalidDouble <<< FAILURES! |  
-- | --
  | > Throwable #1: org.junit.ComparisonFailure: expected:<... [+118470389-11-05T0[8:24:00.073-03]:00] of type [DATETI...> but was:<... [+118470389-11-05T0[9:24:00.073-02]:00] of type [DATETI...> |  
  | > 	at __randomizedtesting.SeedInfo.seed([4CBBF058E6F785C6:EFBB69C6644C1613]:0) |  
  | > 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.lambda$testGettingInvalidDouble$103(ResultSetTestCase.java:697) |  
  | > 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1402) |  
  | > 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1390) |  
  | > 	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.testGettingInvalidDouble(ResultSetTestCase.java:686) |  
  | > 	at java.lang.Thread.run(Thread.java:748)
```

The build scan is https://gradle-enterprise.elastic.co/s/7iylcdr5cikpo

It's some sort of timezone problem - the expected and actual are the same time but in different timezones.  (Also, the year is ridiculously far in the future, which may be relevant.)

This did not reproduce on CentOS using:

```
./gradlew ':x-pack:plugin:sql:qa:single-node:integTestRunner' \
  -Dtests.seed=4CBBF058E6F785C6 \
  -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT \
  -Dtests.method="testGettingInvalidDouble" \
  -Dtests.security.manager=true \
  -Dtests.locale=hr \
  -Dtests.timezone=Asia/Chita \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

I don't have a SLES 12 machine to test on.  It may be that there's something different about the timezone database on SLES 12 that causes this.

**Comment by matriv** [comment]
Should be the same as #49769

**Comment by astefan** [comment]
Fixed with https://github.com/elastic/elasticsearch/pull/51592
