### ISSUE TITLE
Allow `append` processor to copy `date_range` fields

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#49907]
Currently it doesn't seem possible to copy a `date_range` field during ingestion to another field of the same type.
The input object is flattened to a String representation that doesn't get indexed properly on the target field:

```
DELETE test

PUT /test
{
  "mappings": {
    "properties": {
      "date_copy": {
        "type": "date_range"
      },
      "date": {
        "type": "date_range"
      }
    }
  }
}

PUT _ingest/pipeline/append_date_range
{
  "description": "appends the value of date to date_copy ",
  "processors": [
    {
      "append": {
        "field": "date_copy",
        "value": "{{date}}"
      }
    }
  ]
}

POST _ingest/pipeline/append_date_range/_simulate
{
  "docs": [
    {
      "_source": {
        "date": {
          "gte": "2019-11-10T01:00:00.000Z",
          "lt": "2019-11-15T01:00:00.000Z"
        }
      }
    }
  ]
}
```

This leads to:
```
{
  "docs" : [
    {
      "doc" : {
        "_index" : "_index",
        "_type" : "_doc",
        "_id" : "_id",
        "_source" : {
          "date" : {
            "lt" : "2019-11-15T01:00:00.000Z",
            "gte" : "2019-11-10T01:00:00.000Z"
          },
          "date_copy" : [
            "{lt=2019-11-15T01:00:00.000Z, gte=2019-11-10T01:00:00.000Z}"
          ]
        },
        "_ingest" : {
          "timestamp" : "2019-12-06T11:22:34.749307Z"
        }
      }
    }
  ]
}
```

The String value `{lt=2019-11-15T01:00:00.000Z, gte=2019-11-10T01:00:00.000Z}` then causes issues when trying to index the document into the target field with e.g.

```
PUT /test/_doc/1?pipeline=append_date_range
{
  "date": {
    "gte": "2019-11-10T01:00:00.000Z",
    "lt": "2019-11-15T01:00:00.000Z"
  }
}
```
which leads to the following error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "error parsing field [date_copy], expected an object but got null"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse field [date_copy] of type [date_range] in document with id '1'. Preview of field's value: '{lt=2019-11-15T01:00:00.000Z, gte=2019-11-10T01:00:00.000Z}'",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "error parsing field [date_copy], expected an object but got null"
    }
  },
  "status": 400
}

Stack:
Caused by: org.elasticsearch.index.mapper.MapperParsingException: error parsing field [date_copy], expected an object but got null
	at org.elasticsearch.index.mapper.RangeFieldMapper.parseCreateField(RangeFieldMapper.java:394) ~[elasticsearch-7.5.0.jar:7.5.0]
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:277) ~[elasticsearch-7.5.0.jar:7.5.0]
	... 162 more
```

There seem to be potential workaround using scripting but it would be interesting to investigate if this case can be supported or should be documented as unsupported instead.

**Comment by cbuescher** [comment]
fwiw, the idea to use the ingest processor for this came up in #49344 because there are also issues with the `copy_to` functionality of this field type.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
