### ISSUE TITLE
Reproducible Failure in SnapshotResiliencyTests.testSnapshotDeletesWithNodeDisconnects

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#50010]
```
./gradlew :server:test --tests "org.elasticsearch.snapshots.SnapshotResiliencyTests.testSnapshotDeletesWithNodeDisconnects" -Dtests.seed=2FBA3B0BED2EE9B8 -Dtests.locale=rwk-TZ -Dtests.timezone=America/Juneau
```

fails with:

```
java.lang.AssertionError: Condition wasn't fulfilled.

	at __randomizedtesting.SeedInfo.seed([2FBA3B0BED2EE9B8:929F382D5442975]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.elasticsearch.snapshots.SnapshotResiliencyTests.runUntil(SnapshotResiliencyTests.java:819)
	at org.elasticsearch.snapshots.SnapshotResiliencyTests.verifyReposThenStopServices(SnapshotResiliencyTests.java:251)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
```

... looking into it

**Comment by original-brownbear** [comment]
Nevermind ... this was my mistake, no test failure here ...
