### ISSUE TITLE
[CI] org.elasticsearch.xpack.ml.integration.ClassificationIT.testSingleNumericFeatureAndMixedTrainingAndNonTrainingRows failure

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#50168]
Example failure: https://gradle-enterprise.elastic.co/s/uohtdst7yu7lk

Started occurring after https://github.com/elastic/elasticsearch/pull/50040 got merged.
Stack trace:

```
org.elasticsearch.xpack.ml.integration.ClassificationIT > testSingleNumericFeatureAndMixedTrainingAndNonTrainingRows FAILED |  
-- | --
  | java.lang.AssertionError: |  
  | Expected: <1> |  
  | but: was <0> |  
  | at __randomizedtesting.SeedInfo.seed([6B678FC96FDF9BF5:7F732A40232997FC]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.junit.Assert.assertThat(Assert.java:923) |  
  | at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertModelStatePersisted(MlNativeDataFrameAnalyticsIntegTestCase.java:282) |  
  | at org.elasticsearch.xpack.ml.integration.ClassificationIT.testSingleNumericFeatureAndMixedTrainingAndNonTrainingRows(ClassificationIT.java:98)
```

Fails in https://github.com/elastic/elasticsearch/blob/68c739fff3739afc1d610855e9b3f95a9ab0ccf2/x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/MlNativeDataFrameAnalyticsIntegTestCase.java#L282

returning 0 hits.

I can reproduce it locally with:

```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testSingleNumericFeatureAndMixedTrainingAndNonTrainingRows" -Dtests.seed=6B678FC96FDF9BF5 -Dtests.security.manager=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=fi-FI -Dtests.timezone=Europe/Isle_of_Man -Dcompiler.java=13 -Dlicense.key=<path_to_release_key>
```

**Comment by dliappis** [comment]
@dimitris-athanasiou do you think you could take a look?

**Comment by martijnvg** [comment]
Another instance of this failure: https://gradle-enterprise.elastic.co/s/q4d2h6lbyzvos
