### ISSUE TITLE
[CI] Rolling upgrade tests fail in org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.test {p0=upgraded_cluster/10_basic/Continue scroll after upgrade}

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#50172]
Example failure: https://gradle-enterprise.elastic.co/s/xxmcg4qhvabtw

```
org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT > test {p0=upgraded_cluster/10_basic/Continue scroll after upgrade} FAILED |
  | java.lang.AssertionError: Failure at [upgraded_cluster/10_basic:10]: expected [2xx] status code but api [scroll] returned [404 Not Found] [{"error":{"root_cause":[{"type":"search_context_missing_exception","reason":"No search context found for id [126]","stack_trace":"org.elasticsearch.search.SearchContextMissingException: No search context found for id [126]
	at org.elasticsearch.search.SearchService.getExecutor(SearchService.java:462)
	at org.elasticsearch.search.SearchService.runAsync(SearchService.java:347)
	at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:474)
	at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$10(SearchTransportService.java:356)
```

Reproduction line:

```
./gradlew ':x-pack:qa:rolling-upgrade:v8.0.0#upgradedClusterTest' --tests "org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.test {p0=upgraded_cluster/10_basic/Continue scroll after upgrade}"   -Dtests.seed=C6C661E9EC36339D   -Dtests.security.manager=true   -Dtests.locale=sr-Latn-ME   -Dtests.timezone=Arctic/Longyearbyen   -Dcompiler.java=13   -Dtests.rest.suite=upgraded_cluster
```

I was able to reproduce locally (and on similar debian-10 CI worker) but had to use a few iterations.

**Comment by dliappis** [comment]
https://github.com/elastic/elasticsearch/pull/48525 claims to have fixed it.

**Comment by dliappis** [comment]
I will close this issue and track in the original ticket https://github.com/elastic/elasticsearch/issues/46529.
