### ISSUE TITLE
SQL: JDBC getDate() method fails with NPE for a CASTed NULL AS DATE query

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#50174]
```
Connection conn = DriverManager.getConnection(URL);
PreparedStatement statement = conn.prepareStatement("SELECT CAST(NULL AS DATE)");
ResultSet results = statement.executeQuery();
while (results.next()) {
	ResultSetMetaData resultSetMetaData = results.getMetaData();
	logger.log(resultSetMetaData.getColumnLabel(1) + ": " + results.getObject(1));
	logger.log(resultSetMetaData.getColumnLabel(1) + ": " + results.getDate(1, Calendar.getInstance()));
}
```

results in 

```
CAST(NULL AS DATE): null
Exception in thread "main" java.lang.NullPointerException
	at org.elasticsearch.xpack.sql.jdbc.JdbcResultSet.dateTimeAsMillis(JdbcResultSet.java:276)
	at org.elasticsearch.xpack.sql.jdbc.JdbcResultSet.getDate(JdbcResultSet.java:360)
```

For `SELECT CAST(NULL AS DATETIME)` the query is successful.
For `SELECT CAST(NULL AS TIME)` the query fails again with NPE.

**Comment by astefan** [comment]
master (8.0.0): https://github.com/elastic/elasticsearch/commit/08214eb1338fef5c8082c3f8b84c24dd53224ebe
7.x (7.6.0): https://github.com/elastic/elasticsearch/commit/c6fdf9ed8aee9b210eed2dae632f422861ff87f7
7.5 (7.5.2): https://github.com/elastic/elasticsearch/commit/e978e0544fb45645bed38eaeace4e15642563fb9
