### ISSUE TITLE
This version of the JDBC driver is only compatible with Elasticsearch version vUnknown [Unknown],

### ISSUE THREAD

**Issue by zhu1289303556** [elastic/elasticsearch#50201]
use jdbc 6.7.1

<dependency>
            <groupId>org.elasticsearch.plugin</groupId>
            <artifactId>x-pack-sql-jdbc</artifactId>
            <version>6.7.1</version>
        </dependency>

mvn clean package

Maven runs after packaging

java.sql.SQLException: This version of the JDBC driver is only compatible with Elasticsearch version vUnknown [Unknown], attempting to connect to a server version 6.7.1
        at org.elasticsearch.xpack.sql.jdbc.JdbcHttpClient.checkServerVersion(JdbcHttpClient.java:94)
        at org.elasticsearch.xpack.sql.jdbc.JdbcHttpClient.<init>(JdbcHttpClient.java:43)
        at org.elasticsearch.xpack.sql.jdbc.JdbcConnection.<init>(JdbcConnection.java:49)
        at org.elasticsearch.xpack.sql.jdbc.EsDriver.connect(EsDriver.java:76)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at com.example.demo.TestController.getConnection(TestController.java:36)
        at com.example.demo.TestController.selectCount(TestController.java:48)
        at com.example.demo.TestController.test(TestController.java:18)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(Framew

**Comment by zhu1289303556** [comment]
<dependency>
            <groupId>org.elasticsearch.plugin</groupId>
            <artifactId>x-pack-sql-jdbc</artifactId>
            <version>6.7.1</version>
        </dependency>

**Comment by astefan** [comment]
@zhu1289303556 let's continue the investigation in the discuss post you, also, opened https://discuss.elastic.co/t/this-version-of-the-jdbc-driver-is-only-compatible-with-elasticsearch-version-vunknown-unknown/211894

**Comment by astefan** [comment]
master (8.0.0): https://github.com/elastic/elasticsearch/commit/6247b0793c9db19a8a9fa6f0164cc14d0debed6e
7.x (7.7.0): https://github.com/elastic/elasticsearch/commit/488944f4a1ddf2be89f8098218578f6112d4d3fe
7.6 (7.6.1): https://github.com/elastic/elasticsearch/commit/3ccea311936bf22cb3f8c6dfb4ee9c3aded13b08
