### ISSUE TITLE
CsvProcessorTests#testUntrimmed fails

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#50209]
This test failed in an 7.x intake build: https://gradle-enterprise.elastic.co/s/ignvzyeja77a2. This is reproducible.

```
org.elasticsearch.ingest.common.CsvProcessorTests > testUntrimmed {quote='} FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([5F99CFEE74FB3D07:C80ADE82161D92B]:0)
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertFalse(Assert.java:64)
        at org.junit.Assert.assertFalse(Assert.java:74)
        at org.elasticsearch.ingest.common.CsvProcessorTests.testUntrimmed(CsvProcessorTests.java:190)
REPRODUCE WITH: ./gradlew ':modules:ingest-common:test' --tests "org.elasticsearch.ingest.common.CsvProcessorTests.testUntrimmed {quote='}" -Dtests.seed=5F99CFEE74FB3D07 -Dtests.security.manager=true -Dtests.locale=en -Dtests.timezone=Australia/Melbourne -Dcompiler.java=13 -Druntime.java=8
```

**Comment by probakowski** [comment]
There's problem with test code, tests above fail if random document generator add field that should not be present. I'll push fix for that soon

**Comment by henningandersen** [comment]
Failed again here: https://gradle-enterprise.elastic.co/s/tifk3drrvlpdm/tests/failed, both failures are reproducible:

```
./gradlew ':modules:ingest-common:test' --tests "org.elasticsearch.ingest.common.CsvProcessorTests.testUntrimmed {quote='}" -Dtests.seed=98F58CDA6FFFEF40 -Dtests.security.manager=true -Dtests.locale=zh -Dtests.timezone=Pacific/Gambier -Dcompiler.java=13 -Druntime.java=8

./gradlew ':modules:ingest-common:test' --tests "org.elasticsearch.ingest.common.CsvProcessorTests.testUntrimmed {quote=\"}" -Dtests.seed=98F58CDA6FFFEF40 -Dtests.security.manager=true -Dtests.locale=zh -Dtests.timezone=Pacific/Gambier -Dcompiler.java=13 -Druntime.java=8
```

**Comment by ywelsch** [comment]
More failures of this: https://gradle-enterprise.elastic.co/s/ek32eo2mm2rk4
