### ISSUE TITLE
[CI] org.elasticsearch.percolator.CandidateQueryTests.testDuel failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#50305]
```
REPRODUCE WITH: ./gradlew ':modules:percolator:test' --tests "org.elasticsearch.percolator.CandidateQueryTests.testDuel" -Dtests.seed=90ED18A4A0A763FF -Dtests.security.manager=true -Dtests.locale=el-CY -Dtests.timezone=Etc/GMT-13 -Dcompiler.java=13
```

This failure does reproduce locally for me.

```
2> java.lang.AssertionError: 
    Expected: <835L>
         but: was <834L>
        at __randomizedtesting.SeedInfo.seed([90ED18A4A0A763FF:DC6DA2A4FE2FFBED]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.percolator.CandidateQueryTests.duelRun(CandidateQueryTests.java:1056)
        at org.elasticsearch.percolator.CandidateQueryTests.testDuel(CandidateQueryTests.java:269)
```

Build urls:
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk13,ES_RUNTIME_JAVA=adoptopenjdk11,nodes=general-purpose/394/console
* https://gradle-enterprise.elastic.co/s/tep2tg7wrjfhy

**Comment by martijnvg** [comment]
This is a slightly different instance of this failure, which I expect to be related:

```
org.elasticsearch.percolator.CandidateQueryTests > testDuel FAILED
02:46:44     java.lang.AssertionError: 
02:46:44     Expected: <838L>
02:46:44          but: was <837L>
02:46:44         at __randomizedtesting.SeedInfo.seed([DC3224DB2B29D634:90B29EDB75A14E26]:0)
02:46:44         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
02:46:44         at org.junit.Assert.assertThat(Assert.java:956)
02:46:44         at org.junit.Assert.assertThat(Assert.java:923)
02:46:44         at org.elasticsearch.percolator.CandidateQueryTests.duelRun(CandidateQueryTests.java:1062)
02:46:44         at org.elasticsearch.percolator.CandidateQueryTests.testDuel(CandidateQueryTests.java:269)
```

Build urls:
* https://gradle-enterprise.elastic.co/s/zl7jpfqdzutpe
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+EAR/313/console

This also reproduces for me:

```
./gradlew ':modules:percolator:test' --tests "org.elasticsearch.percolator.CandidateQueryTests.testDuel"   -Dtests.seed=DC3224DB2B29D634
```

**Comment by martijnvg** [comment]
Other instances of this failure:
* https://gradle-enterprise.elastic.co/s/rbt3aerca7fkc/tests/zcl56apwaqq2e-lu3orqedohjb6
