### ISSUE TITLE
[CI] HistogramPercentileAggregationTests.testTDigestHistogram failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#50307]
Reproduce line:

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:analytics:test' --tests "org.elasticsearch.xpack.analytics.mapper.HistogramPercentileAggregationTests.testTDigestHistogram" -Dtests.seed=44FD6E7912D5FDE5 -Dtests.security.manager=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=it -Dtests.timezone=America/Rosario -Dcompiler.java=13 -Druntime.java=8
```

Does not reproduce locally for me.

Failure:

```
2> java.lang.AssertionError: expected:<0.43155573922885637> but was:<0.42117091333838197>
01:30:22         at __randomizedtesting.SeedInfo.seed([44FD6E7912D5FDE5:B71A4A5D4933432F]:0)
01:30:22         at org.junit.Assert.fail(Assert.java:88)
01:30:22         at org.junit.Assert.failNotEquals(Assert.java:834)
01:30:22         at org.junit.Assert.assertEquals(Assert.java:553)
01:30:22         at org.junit.Assert.assertEquals(Assert.java:683)
01:30:22         at org.elasticsearch.xpack.analytics.mapper.HistogramPercentileAggregationTests.testTDigestHistogram(HistogramPercentileAggregationTests.java:223)
```

Build urls:
* https://gradle-enterprise.elastic.co/s/jc7f7hqq3jnb4
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+release-tests/675/console

**Comment by davidkyle** [comment]
Another failure on master:
```
java.lang.AssertionError: expected:<0.20577506725945938> but was:<0.21741075266575824>Close stacktrace
at __randomizedtesting.SeedInfo.seed([E36C87306B33887B:108BA31430D536B1]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:553)
at org.junit.Assert.assertEquals(Assert.java:683)
at org.elasticsearch.xpack.analytics.mapper.HistogramPercentileAggregationTests.testTDigestHistogram(HistogramPercentileAggregationTests.java:223)
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=sles-15&&immutable/496/console
https://gradle-enterprise.elastic.co/s/nbhyub4pylwmq

Does not reproduce
```
./gradlew ':x-pack:plugin:analytics:test' --tests "org.elasticsearch.xpack.analytics.mapper.HistogramPercentileAggregationTests.testTDigestHistogram" \
  -Dtests.seed=E36C87306B33887B \
  -Dtests.security.manager=true \
  -Dtests.locale=ru \
  -Dtests.timezone=America/Montreal \
  -Dcompiler.java=13
```

**Comment by davidkyle** [comment]
Muted on master in 7309ce42c3fb106285d34e8668e03ae0582f7d8f
