### ISSUE TITLE
[CI] IndexStatsIT.testQueryCache failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#50316]
Failure:

```
FAILURE 3.53s J0  \| IndexStatsIT.testQueryCache <<< FAILURES! |  
-- | --
  | > Throwable #1: java.lang.AssertionError: |  
  | > Expected: a value greater than <0L> |  
  | >      but: <0L> was equal to <0L> |  
  | > 	at __randomizedtesting.SeedInfo.seed([8A39F72864578767:51CEA03B37EFB079]:0) |  
  | > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20) |  
  | > 	at org.elasticsearch.indices.stats.IndexStatsIT.testQueryCache(IndexStatsIT.java:295) |  
  | > 	at java.lang.Thread.run(Thread.java:748)
```

Branch: 6.8

Reproduce line:

```
./gradlew ':server:integTest' -Dtests.seed=8A39F72864578767 -Dtests.class=org.elasticsearch.indices.stats.IndexStatsIT -Dtests.method="testQueryCache" -Dtests.security.manager=true -Dtests.locale=sr-RS -Dtests.timezone=Asia/Brunei -Dcompiler.java=12 -Druntime.java=8
```

Doesn't reproduce for me.

Build log: https://gradle-enterprise.elastic.co/s/zd5tbe4e5qjci

Failure only seems to have occurred twice with the same error this month: 
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now%2FM,mode:quick,to:now%2FM))&_a=(columns:!(_source),filters:!(),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'test:testQueryCache%20AND%20class:*IndexStatsIT'),sort:!(time,desc))

**Comment by tlrx** [comment]
This test failed again today on `6.8`: https://gradle-enterprise.elastic.co/s/tfgveibpuwzo6


```
IndexStatsIT.testQueryCache <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: a value greater than <0L>
   >      but: <0L> was equal to <0L>
   > 	at __randomizedtesting.SeedInfo.seed([5D1000E02EA10A58:86E757F37D193D46]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.indices.stats.IndexStatsIT.testQueryCache(IndexStatsIT.java:296)
   > 	at java.lang.Thread.run(Thread.java:748)
```

It does not reproduce:
```
./gradlew ':server:integTest' \
  -Dtests.seed=5D1000E02EA10A58 \
  -Dtests.class=org.elasticsearch.indices.stats.IndexStatsIT \
  -Dtests.method="testQueryCache" \
  -Dtests.security.manager=true \
  -Dtests.locale=mt-MT \
  -Dtests.timezone=Europe/Volgograd \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

I'm going to mute this test on 6.8

**Comment by ywelsch** [comment]
I think we should close this one as NOFIX. ES 6.8 will be EOL in a couple of weeks.
