### ISSUE TITLE
IndexStatsIT testSegmentsStats failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#50362]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk13,ES_RUNTIME_JAVA=java11,nodes=general-purpose/396/console
https://gradle-enterprise.elastic.co/s/s2yxbphb5vs2g

```
Expected: a value greater than <0L>
     but: <0L> was equal to <0L>

at __randomizedtesting.SeedInfo.seed([640AC00B268DA531:D3217E5DBB119265]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.indices.stats.IndexStatsIT.testSegmentsStats(IndexStatsIT.java:608)
```

Does not reproduce 
```
./gradlew ':server:integTest' --tests "org.elasticsearch.indices.stats.IndexStatsIT.testSegmentsStats" \
  -Dtests.seed=640AC00B268DA531 \
  -Dtests.security.manager=true \
  -Dtests.locale=de-CH \
  -Dtests.timezone=Africa/Bangui \
  -Dcompiler.java=13
```

**Comment by davidkyle** [comment]
Not a one off but still rare so I will leave the test unmuted for now

https://gradle-enterprise.elastic.co/s/ygdjv3i3t44qa#tests
https://gradle-enterprise.elastic.co/s/5fbfvrfbowfsq#tests
