### ISSUE TITLE
[CI] InternalGeoBoundsTests.testFromXContentWithRandomFields failure

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#50505]
Failure:
```
java.lang.NullPointerException
	at __randomizedtesting.SeedInfo.seed([1C33F4DADA278134:1E26D99B81E009E1]:0)
	at org.elasticsearch.search.aggregations.metrics.ParsedGeoBounds.topLeft(ParsedGeoBounds.java:58)
	at org.elasticsearch.search.aggregations.metrics.InternalGeoBoundsTests.assertFromXContent(InternalGeoBoundsTests.java:100)
	at org.elasticsearch.search.aggregations.metrics.InternalGeoBoundsTests.assertFromXContent(InternalGeoBoundsTests.java:36)
	at org.elasticsearch.test.InternalAggregationTestCase.testFromXContentWithRandomFields(InternalAggregationTestCase.java:356)
```
Branch master and 7.6.0

Reproduce with
```
./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.metrics.InternalGeoBoundsTests.testFromXContentWithRandomFields" \
  -Dtests.seed=1C33F4DADA278134 \
  -Dtests.security.manager=true \
  -Dtests.locale=ga-IE \
  -Dtests.timezone=Atlantic/Bermuda \
  -Dcompiler.java=13
```

Build scan available at https://gradle-enterprise.elastic.co/s/7x2ct6yywkw3o

This is a regression introduced by https://github.com/elastic/elasticsearch/pull/50253

**Comment by ebadyano** [comment]
Another failure:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk13,ES_RUNTIME_JAVA=zulu11,nodes=general-purpose/425/console

**Comment by cbuescher** [comment]
Another one today:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/436/console
Build Scan: https://gradle-enterprise.elastic.co/s/wlgqig3gu635k
Tried the PR from 50506 which fixes it though.
