### ISSUE TITLE
Test: testJavaPatternDefaultYear date related SQL test fails on New Year

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#50547]
**test1**
`org.elasticsearch.ingest.common.DateProcessorTests.testJavaPatternDefaultYear`
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/12954/
`REPRODUCE WITH: ./gradlew ':modules:ingest-common:test' --tests "org.elasticsearch.ingest.common.DateProcessorTests.testJavaPatternDefaultYear" -Dtests.seed=73BA954E1E132943 -Dtests.security.manager=true -Dtests.locale=de-AT -Dtests.timezone=Asia/Chongqing -Dcompiler.java=13`
stacktrace
```
Expected: "2020-06-12T00:00:00.000+02:00"
     but: was "2019-06-12T00:00:00.000+02:00"
	at __randomizedtesting.SeedInfo.seed([73BA954E1E132943:AE4896F2A8A70FE7]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.ingest.common.DateProcessorTests.testJavaPatternDefaultYear(DateProcessorTests.java:161)
```

**test2**
(split to #37045)

**Comment by rjernst** [comment]
I'm not able to find any failures of this test in the last 6 months, and it does not reproduce for me locally. Closing until we see a recurrence.
