### ISSUE TITLE
[CI] PublishClusterStateActionTests.testFailToPublishWithLessThanMinMasterNodes ThreadLeakError

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#50593]
This happened on 7.5 branch:

Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.5+multijob-unix-compatibility/os=debian-8&&immutable/159/console
-- | --
Build Scans | https://gradle-enterprise.elastic.co/s/sdyks6rgbfpha

Could not reproduce with
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.discovery.zen.PublishClusterStateActionTests.testFailToPublishWithLessThanMinMasterNodes" -Dtests.seed=E22CE7A0B65C7735 -Dtests.security.manager=true -Dtests.locale=ar-SD -Dtests.timezone=MST -Dcompiler.java=12 -Druntime.java=8
```
Errors in log
```
org.elasticsearch.discovery.zen.PublishClusterStateActionTests > classMethod FAILED
11:12:11     com.carrotsearch.randomizedtesting.ThreadLeakError: 2 threads leaked from SUITE scope at org.elasticsearch.discovery.zen.PublishClusterStateActionTests: 
11:12:11        1) Thread[id=1176, name=elasticsearch[transport_worker][T#2], state=RUNNABLE, group=TGRP-PublishClusterStateActionTests]
11:12:11             at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
11:12:11             at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
11:12:11             at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
11:12:11             at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
11:12:11             at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
11:12:11             at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:164)
11:12:11             at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:131)
11:12:11             at org.elasticsearch.nio.NioSelectorGroup$$Lambda$2426/198850397.run(Unknown Source)
11:12:11             at java.lang.Thread.run(Thread.java:748)
11:12:11        2) Thread[id=1175, name=elasticsearch[transport_worker][T#1], state=RUNNABLE, group=TGRP-PublishClusterStateActionTests]
11:12:11             at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
11:12:11             at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
11:12:11             at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
11:12:11             at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
11:12:11             at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
11:12:11             at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:164)
11:12:11             at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:131)
11:12:11             at org.elasticsearch.nio.NioSelectorGroup$$Lambda$2426/198850397.run(Unknown Source)
11:12:11             at java.lang.Thread.run(Thread.java:748)
```

Similar looking error in

**Comment by ywelsch** [comment]
Duplicates #43387
