### ISSUE TITLE
[CI] RecoveryIT.testOperationBasedRecovery fails with "Creating indices with soft-deletes disabled" warning

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#50668]
This happened in a PR bwc run but I think its unrelated to the PR:
https://gradle-enterprise.elastic.co/s/6jzcj5caasz2i

Error in log:
```
17:40:00 org.elasticsearch.upgrades.RecoveryIT > testOperationBasedRecovery FAILED
17:40:00     org.elasticsearch.client.WarningFailureException: method [PUT], host [http://127.0.0.1:43833], URI [/test_operation_based_recovery], status line [HTTP/1.1 200 OK]
17:40:00     Warnings: [Creating indices with soft-deletes disabled is deprecated and will be removed in future Elasticsearch versions. Please do not specify value for setting [index.soft_deletes.enabled] of index [test_operation_based_recovery].]
17:40:00     {"acknowledged":true,"shards_acknowledged":true,"index":"test_operation_based_recovery"}
17:40:00         at __randomizedtesting.SeedInfo.seed([59309AD2C6D056B8:44DC96F7C056ACCF]:0)
17:40:00         at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:279)
17:40:00         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:261)
17:40:00         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
17:40:00         at org.elasticsearch.test.rest.ESRestTestCase.createIndex(ESRestTestCase.java:969)
17:40:00         at org.elasticsearch.upgrades.RecoveryIT.testOperationBasedRecovery(RecoveryIT.java:669)
```

Probably related to https://github.com/elastic/elasticsearch/pull/50502 which seems to have a pending backport that might fix this.
@dnhatn you can probably quickly tell if this is related and maybe close if the backport is imminent.

**Comment by dnhatn** [comment]
I have adjusted BWC in https://github.com/elastic/elasticsearch/commit/520958bd56cc462636165e8391ef578384353ac2. I think you need to sync your PR with the master branch.
