### ISSUE TITLE
SimpleNioTransportTests timeout failures and thread leaks 

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#50674]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian-9&&immutable/496/console
https://gradle-enterprise.elastic.co/s/kku577daudaug

Not much to go on:
```
org.elasticsearch.transport.ConnectTransportException: [TS_C][127.0.0.1:29202] connect_timeout[30s]
	at __randomizedtesting.SeedInfo.seed([E2D3E32169E136BA:E4945AD70DD97E2A]:0)
	at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onTimeout(TcpTransport.java:986)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:629)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

[2020-01-06T02:56:51,739][INFO ][o.e.t.n.SimpleNioTransportTests] [testSendRandomRequests] before test
[2020-01-06T02:56:51,799][INFO ][o.e.t.TransportService   ] [testSendRandomRequests] publish_address {127.0.0.1:29200}, bound_addresses {[::1]:29200}, {127.0.0.1:29200}
[2020-01-06T02:56:51,854][INFO ][o.e.t.TransportService   ] [testSendRandomRequests] publish_address {127.0.0.1:29201}, bound_addresses {[::1]:29201}, {127.0.0.1:29201}
[2020-01-06T02:56:51,938][INFO ][o.e.t.TransportService   ] [testSendRandomRequests] publish_address {127.0.0.1:29202}, bound_addresses {[::1]:29202}, {127.0.0.1:29202}
[2020-01-06T02:57:53,354][INFO ][o.e.t.n.SimpleNioTransportTests] [testSendRandomRequests] after test
```

The suite fails with a thread leak error https://gradle-enterprise.elastic.co/s/kku577daudaug/tests/s4pd7m5pd7eeg-cmlyka7wa42ii

```
 ./gradlew ':plugins:transport-nio:test' --tests "org.elasticsearch.transport.nio.SimpleNioTransportTests.testSendRandomRequests" \
  -Dtests.seed=E2D3E32169E136BA \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-OM \
  -Dtests.timezone=America/Argentina/Rio_Gallegos \
  -Dcompiler.java=13
```

`testHandshakeWithIncompatVersion` also test failed recently https://gradle-enterprise.elastic.co/s/xhix5l2ympgk4/tests/s4pd7m5pd7eeg-rrkxl3xj6ogs2

```
org.elasticsearch.transport.ConnectTransportException: [TS_A][127.0.0.1:27300] connect_timeout[30s]Close stacktrace
at __randomizedtesting.SeedInfo.seed([7EE2BAD9960AFA18:B942BA6F92ED2225]:0)
at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onTimeout(TcpTransport.java:986)
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:629)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.lang.Thread.run(Thread.java:834)

[2020-01-05T05:55:11,849][INFO ][o.e.t.n.SimpleNioTransportTests] [testHandshakeWithIncompatVersion] before test
[2020-01-05T05:55:11,921][INFO ][o.e.t.TransportService   ] [testHandshakeWithIncompatVersion] publish_address {127.0.0.1:27300}, bound_addresses {[::1]:27300}, {127.0.0.1:27300}
[2020-01-05T05:55:11,986][INFO ][o.e.t.TransportService   ] [testHandshakeWithIncompatVersion] publish_address {127.0.0.1:27301}, bound_addresses {[::1]:27301}, {127.0.0.1:27301}
[2020-01-05T05:56:12,072][INFO ][o.e.t.n.SimpleNioTransportTests] [testHandshakeWithIncompatVersion] after test
```

```
./gradlew ':plugins:transport-nio:test' --tests "org.elasticsearch.transport.nio.SimpleNioTransportTests.testHandshakeWithIncompatVersion" -Dtests.seed=7EE2BAD9960AFA18 -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=Etc/GMT+0 -Dcompiler.java=13
HomeTestsorg.elasticsearch.transport.nio.SimpleNioTransportTests » testHandshakeWithIncompatVersion
```

**Comment by tbrooks8** [comment]
It seems very possible that this is related to the other failures we experience on Debian. This test lacks the slow logging we often see.

**Comment by tbrooks8** [comment]
#43387 is the similar issue.

**Comment by ywelsch** [comment]
Closing in favor of #43387
