### ISSUE TITLE
SQL CLI return more informative error with PKIX failures

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#50751]
Elasticsearch SQL CLI v7.4.0, ES v7.4.0

With matching versions for SQL CLI and ES cluster, SQL CLI will return a version error if it is encounters a handshake error for SSL.

**Current behavior:**

```
./bin/elasticsearch-sql-cli https://elastic:<securepassword>@<servername>:9200
ERROR: Cannot communicate with the server https://elastic:<securepassword>@<servername>::9200. This version of CLI only works with Elasticsearch version v7.4.0 [22e1767283e61a198cb4db791ea66e3f11ab9910]
```

Add the `--debug` option to reveal the real cause is a PKIX error:

```
./bin/elasticsearch-sql-cli --debug https://elastic:<securepassword>@<servername>:9200
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Client Exception [Cannot POST address https://<servername>:9200/?error_trace (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target)]
org.elasticsearch.xpack.sql.client.ClientException: Cannot POST address https://<servername>::9200/?error_trace (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target)
        at org.elasticsearch.xpack.sql.client.JreHttpUrlConnection.request(JreHttpUrlConnection.java:164)
        at org.elasticsearch.xpack.sql.client.HttpClient.lambda$get$4(HttpClient.java:131)
        at org.elasticsearch.xpack.sql.client.JreHttpUrlConnection.http(JreHttpUrlConnection.java:66)
        at org.elasticsearch.xpack.sql.client.HttpClient.lambda$get$5(HttpClient.java:130)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
        at org.elasticsearch.xpack.sql.client.HttpClient.get(HttpClient.java:129)
        at org.elasticsearch.xpack.sql.client.HttpClient.serverInfo(HttpClient.java:60)
        at org.elasticsearch.xpack.sql.cli.command.CliSession.checkConnection(CliSession.java:63)
        at org.elasticsearch.xpack.sql.cli.Cli.checkConnection(Cli.java:138)
        at org.elasticsearch.xpack.sql.cli.Cli.execute(Cli.java:128)
        at org.elasticsearch.xpack.sql.cli.Cli.execute(Cli.java:110)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.xpack.sql.cli.Cli.main(Cli.java:58)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1331)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1206)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1153)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1460)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1368)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:437)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:171)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
        at org.elasticsearch.xpack.sql.client.JreHttpUrlConnection.request(JreHttpUrlConnection.java:154)
        ... 13 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:384)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:289)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1315)
        ... 30 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:379)
        ... 35 more
ERROR: Cannot communicate with the server https://elastic:<securepassword>@<servername>::9200. This version of CLI only works with Elasticsearch version v7.4.0 [22e1767283e61a198cb4db791ea66e3f11ab9910]
```

Would it be possible to catch PKIX errors and return a more informative message without the debug option? A tip to use the `--debug` option for further troubleshooting could also be helpful.

**Comment by wchaparro** [comment]
Superceded by ES|QL
