### ISSUE TITLE
[Issue] monitorInterval param encounter an error when modifing the rootLogger.level value

### ISSUE THREAD

**Issue by zqw226** [elastic/elasticsearch#50955]
As far as I know, the log4j2.properties file support the 'monitorInterval' param with the help of 'log4j-1.2-api-2.11.1.jar'.

However, when I set 'monitorInterval = 5' in the log4j2.properties file, and then modify the 'rootLogger.level' from 'info' to 'trace', I find an error response  in the cluster log file.

I find it is because the 'security.policy' file  in the 'elasticsearch-7.3.2.jar' may hold a too strict permmsion check. I don't know whether our official contributors or committers have noticed this problem and have got a plan to solve it.

**Elasticsearch version** (version 7.3.2):

**JVM version** (Java(TM) SE Runtime Environment (build 12.0.2+10)):

**OS version** (Darwin zmac.mshome.net 19.2.0 Darwin Kernel Version 19.2.0):

**Description of the problem
Error log is below. 
The right behavior is that I could see the trace log rather than an error response.

**Steps to reproduce**:
 1. tar xzvf elasticsearch-7.3.2-darwin-x86_64.tar
 2. vim ./config/log4j2.properties, add the 'monitorInterval = 5'
 3. ./bin/elasticsearch
 4. vim ./config/log4j2.properties, modify rootLogger.level from info to trace
 5. get the error response below

**Provide logs (if relevant)**:

2020-01-14 15:57:07,838 Log4j2-TF-2-ConfiguratonFileWatcher-2 ERROR Could not create plugin of type class org.apache.logging.log4j.core.layout.PatternLayout for element PatternLayout: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers") java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:1044)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:408)
	at java.base/java.lang.Class.checkMemberAccess(Class.java:2852)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2251)
	at org.apache.logging.log4j.core.util.TypeUtil.getAllDeclaredFields(TypeUtil.java:56)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.injectFields(PluginBuilder.java:165)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:959)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:899)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:891)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:891)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:514)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:238)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:250)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:547)
	at org.apache.logging.log4j.core.LoggerContext.onChange(LoggerContext.java:670)
	at org.apache.logging.log4j.core.config.ConfiguratonFileWatcher$ReconfigurationRunnable.run(ConfiguratonFileWatcher.java:68)
	at java.base/java.lang.Thread.run(Thread.java:835)

2020-01-14 15:57:07,841 Log4j2-TF-2-ConfiguratonFileWatcher-2 ERROR Could not create plugin of type class org.apache.logging.log4j.core.appender.rolling.DefaultRolloverStrategy for element DefaultRolloverStrategy: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers") java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:1044)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:408)
	at java.base/java.lang.Class.checkMemberAccess(Class.java:2852)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2251)
	at org.apache.logging.log4j.core.util.TypeUtil.getAllDeclaredFields(TypeUtil.java:56)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.injectFields(PluginBuilder.java:165)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:959)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:899)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:891)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:891)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:514)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:238)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:250)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:547)
	at org.apache.logging.log4j.core.LoggerContext.onChange(LoggerContext.java:670)
	at org.apache.logging.log4j.core.config.ConfiguratonFileWatcher$ReconfigurationRunnable.run(ConfiguratonFileWatcher.java:68)
	at java.base/java.lang.Thread.run(Thread.java:835)

**Comment by matriv** [comment]
It's reproduceable with `7.5.1` too.

**Comment by zqw226** [comment]
> It's reproduceable with `7.5.1` too.

Yes, infact, it is reproduceable with all the 7.x versions.  
Both the security.policy file and the BoostPermissionChecks should be modified if we want this fuction works fine. And I suggest that maybe it's better to add the monitorInterval to log4j2.properties as a default param.

**Comment by pgomulka** [comment]
@zqw226 modify log4j configuration file would result in reloading only one process (ES node). Because of this cluster settings api is a preferred way to change logging levels
https://www.elastic.co/guide/en/elasticsearch/reference/7.6/logging.html#configuring-logging-levels

**Comment by zqw226** [comment]
Well, althrough I think reloading only one instance is sometimes useful, I really agree that api is a better way.  Thanks for your reply.
I will close it now.
