### ISSUE TITLE
ClassificationIT failures on 7.x

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#51024]
I noticed .testWithOnlyTrainingRowsAndTrainingPercentIsHundred failing on my PR based on 7.x. But it seems it fails on other PRs too
`https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:ClassificationIT),sort:!(process.time-start,desc))`
This started on 15th Jan

it reproduces locally
```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testWithOnlyTrainingRowsAndTrainingPercentIsHundred" -Dtests.seed=8F881061E33C57BA -Dtests.security.manager=true -Dtests.locale=ar-OM -Dtests.timezone=Asia/Muscat -Dcompiler.java=13 -Druntime.java=8
```

```
  2> java.lang.AssertionError: 
    Expected: is <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([8F881061E33C57BA:D7905DAE1C434EAC]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ml.integration.ClassificationIT.assertTopClasses(ClassificationIT.java:515)
        at org.elasticsearch.xpack.ml.integration.ClassificationIT.testWithOnlyTrainingRowsAndTrainingPercentIsHundred(ClassificationIT.java:144)
```

**Comment by dimitris-athanasiou** [comment]
This has been fixed by https://github.com/elastic/elasticsearch/pull/50986 and its backport to 7.x.
