### ISSUE TITLE
[CI] GeoHashGridAggregatorTests and GeoTileGridAggregatorTests testBounds fails on master

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#51026]
Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos-6&&immutable/514/console

Scan: https://gradle-enterprise.elastic.co/s/uw76wiwh5reay

GeoTileGridAggregatorTests failure:

```
Expected: <114L>
     but: was <63L>
java.lang.AssertionError: 

Expected: <114L>
     but: was <63L>
Close stacktrace
at __randomizedtesting.SeedInfo.seed([492F301B5CCE5DBE:5476030234D26E0D]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.search.aggregations.bucket.geogrid.GeoGridAggregatorTestCase.lambda$testBounds$8(GeoGridAggregatorTestCase.java:180)
at org.elasticsearch.search.aggregations.bucket.geogrid.GeoGridAggregatorTestCase.testCase(GeoGridAggregatorTestCase.java:214)
at org.elasticsearch.search.aggregations.bucket.geogrid.GeoGridAggregatorTestCase.testBounds(GeoGridAggregatorTestCase.java:174)
```

GeoHashGridAggregatorTests failure:

```
Expected: <114L>
     but: was <63L>
java.lang.AssertionError: 

Expected: <114L>
     but: was <63L>
Close stacktrace
at __randomizedtesting.SeedInfo.seed([492F301B5CCE5DBE:5476030234D26E0D]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.search.aggregations.bucket.geogrid.GeoGridAggregatorTestCase.lambda$testBounds$8(GeoGridAggregatorTestCase.java:180)
at org.elasticsearch.search.aggregations.bucket.geogrid.GeoGridAggregatorTestCase.testCase(GeoGridAggregatorTestCase.java:214)
at org.elasticsearch.search.aggregations.bucket.geogrid.GeoGridAggregatorTestCase.testBounds(GeoGridAggregatorTestCase.java:174)
```

They seem related.

Reproduce with:

```
./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.geogrid.GeoTileGridAggregatorTests.testBounds" -Dtests.seed=492F301B5CCE5DBE -Dtests.security.manager=true -Dtests.locale=es-GT -Dtests.timezone=Israel -Dcompiler.java=13
```

and

```
./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.geogrid.GeoHashGridAggregatorTests.testBounds" -Dtests.seed=492F301B5CCE5DBE -Dtests.security.manager=true -Dtests.locale=ar-KW -Dtests.timezone=America/Thunder_Bay -Dcompiler.java=13
```

**Comment by astefan** [comment]
Another failure here: https://gradle-enterprise.elastic.co/s/26dceu6ixejbw
It reproduces locally with `gradlew :server:test --tests "org.elasticsearch.search.aggregations.bucket.geogrid.GeoHashGridAggregatorTests.testBounds" -Dtests.seed=E7A3B430E685B2CD -Dtests.security.manager=true -Dtests.locale=sv -Dtests.timezone=America/Virgin -Dcompiler.java=13 -Druntime.java=8`

**Comment by polyfractal** [comment]
@astefan would you mind pushing a mute to the 7.6 branch?  I muted it in master and 7.x (https://github.com/elastic/elasticsearch/issues/51103) but apparently didn't think about 7.6.

Going to close this issue in favor of https://github.com/elastic/elasticsearch/issues/51103 ... I didn't realize this issue existed when I opened the other, but now the fix (https://github.com/elastic/elasticsearch/pull/51118) references that issue :)

**Comment by astefan** [comment]
@polyfractal yes, was doing this right before your message :-).

**Comment by polyfractal** [comment]
:heart: :heart: :heart:

**Comment by markharwood** [comment]
Looks to be another [occurrence](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.9+multijob-unix-compatibility/os=ubuntu-18.04&&immutable/128/) today of failures in `GeoHashGridAggregatorTests.testBounds` and `.GeoTileGridAggregatorTests.testBounds`. Both reproduced locally on 7.9 and master with these seeds

    ./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.geogrid.GeoHashGridAggregatorTests.testBounds" -Dtests.seed=5E8630DAFF1D3F18 -Dtests.security.manager=true -Dtests.locale=pt -Dtests.timezone=America/Cuiaba -Druntime.java=8

    ./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.geogrid.GeoTileGridAggregatorTests.testBounds" -Dtests.seed=5E8630DAFF1D3F18 -Dtests.security.manager=true -Dtests.locale=en-GB -Dtests.timezone=Hongkong -Druntime.java=8


Error:

	java.lang.AssertionError: 
	Expected: <118L>
		 but: was <119L>
		at __randomizedtesting.SeedInfo.seed([5E8630DAFF1D3F18:43DF03C397010CAB]:0)
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.search.aggregations.bucket.geogrid.GeoGridAggregatorTestCase.lambda$testBounds$15(GeoGridAggregatorTestCase.java:251)
		at org.elasticsearch.search.aggregations.bucket.geogrid.GeoGridAggregatorTestCase.testCase(GeoGridAggregatorTestCase.java:289)
		at org.elasticsearch.search.aggregations.bucket.geogrid.GeoGridAggregatorTestCase.testCase(GeoGridAggregatorTestCase.java:262)
		at org.elasticsearch.search.aggregations.bucket.geogrid.GeoGridAggregatorTestCase.testBounds(GeoGridAggregatorTestCase.java:245)

**Comment by iverase** [comment]
There was a lot of work in this area lately and issues do not reproduce any more.
