### ISSUE TITLE
Problem: "unable to create new native thread" and es can not survive several second after start

### ISSUE THREAD

**Issue by wuyudian1** [elastic/elasticsearch#51134]
Problem: "unable to create new native thread" and es can not survive several second after start

**Elasticsearch version** :
```
Version: 6.3.1, Build: default/zip/eb782d0/2018-06-29T21:59:26.107521Z, JVM: 1.8.0_191
```

**Plugins installed**: []

**JVM version** (`java -version`):
```
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
```
Linux prod-ofc-s-ops-001 4.4.0-170-generic #199-Ubuntu SMP Thu Nov 14 01:45:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**jvm.options**
```ini
-Xms32g
-Xmx32g
-XX:+UseConcMarkSweepGC
-XX:CMSInitiatingOccupancyFraction=75
-XX:+UseCMSInitiatingOccupancyOnly
-XX:+AlwaysPreTouch
-Xss1m
-Djava.awt.headless=true
-Dfile.encoding=UTF-8
-Djna.nosys=true
-XX:-OmitStackTraceInFastThrow
-Dio.netty.noUnsafe=true
-Dio.netty.noKeySetOptimization=true
-Dio.netty.recycler.maxCapacityPerThread=0
-Dlog4j.shutdownHookEnabled=false
-Dlog4j2.disable.jmx=true
-Djava.io.tmpdir=${ES_TMPDIR}
-XX:+HeapDumpOnOutOfMemoryError
-XX:HeapDumpPath=data
-XX:ErrorFile=logs/hs_err_pid%p.log
8:-XX:+PrintGCDetails
8:-XX:+PrintGCDateStamps
8:-XX:+PrintTenuringDistribution
8:-XX:+PrintGCApplicationStoppedTime
8:-Xloggc:logs/gc.log
8:-XX:+UseGCLogFileRotation
8:-XX:NumberOfGCLogFiles=32
8:-XX:GCLogFileSize=64m
9-:-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m
9-:-Djava.locale.providers=COMPAT
```
**elasticsearch.yml**
```yml
cluster.name: xxxx
discovery.zen.minimum_master_nodes: 1
discovery.zen.ping.unicast.hosts: ['10.45.0.33']
node.name: prod-ofc-s-ops-001
node.master: true
network.host: 0.0.0.0
transport.tcp.port: 9300
http.port: 9200
path.data: /data/es/data
```
**ubuntu$ ulimit -a**
```bash
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 321537
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1000000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
**pstree -p|wc -l**
```
13258
```
**cat /proc/sys/kernel/pid_max**
```
1000000
```

**Steps to reproduce**:
I don't how to reproduce it in another server, because there are more than 800 indices in my es。
I think it's very hard to reproduce.

**Provide logs (if relevant)**:
```
...
[2020-01-17T12:34:29,594][INFO ][o.e.m.j.JvmGcMonitorService] [prod-ofc-s-ops-001] [gc][143] overhead, spent [279ms] collecting in the last [1s]
[2020-01-17T12:35:00,561][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [prod-ofc-s-ops-001] fatal error in thread [elasticsearch[prod-ofc-s-ops-001][write][T#28]], exiting
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method) ~[?:1.8.0_191]
        at java.lang.Thread.start(Thread.java:717) ~[?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957) ~[?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025) ~[?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by andreidan** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests. I'd also recommend
providing more information on your index/shard layout, information about 
the load of the cluster (what kind of operations were taking place, inserts, 
queries, what types of queries) around the time you encountered the 
`OutOfMemoryError` and, if possible, a memory dump (if it happens again).

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
