### ISSUE TITLE
[CI] Java8 with FIPS, 7.x PreBuiltXPackTransportClientTests testPluginInstalled failure

### ISSUE THREAD

**Issue by williamrandolph** [elastic/elasticsearch#51268]
## Example build failure

Build scan: https://gradle-enterprise.elastic.co/s/x2lhlum73adfw
Jenkins job: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk13,ES_RUNTIME_JAVA=java8fips,nodes=general-purpose/464/

## Reproduction line
There's no reproduction line, but this does reproduce locally if you follow the setup instructions [from the dev wiki](https://github.com/elastic/elasticsearch-team/blob/master/onboarding-and-how-we-work/test-triage.md#test-triage-for-java-8-fips-jvm-failures):
```
JAVA_HOME=$JAVA13_HOME ./gradlew :x-pack:transport-client:test -Druntime.java=8FIPS -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password

```

This failure reproduces on the `7.6` branch, but not on the `7.5` branch. This may have something to do with 7.6 requiring Java 13 for Java Home while 7.5 only requires Java 12.

## Example relevant log:
```
org.elasticsearch.xpack.client.PreBuiltXPackTransportClientTests > testPluginInstalled FAILED
    java.lang.RuntimeException: ElasticsearchSecurityException[failed to load SSL configuration [xpack.security.http.ssl]]; nested: ElasticsearchException[failed to initialize the SSLContext]; nested: KeyManagementException[FIPS mode: only SunJSSE TrustManagers may be used];
        at __randomizedtesting.SeedInfo.seed([A420D36ED63916A5:AC87BDE1BD2C343B]:0)
        at org.elasticsearch.xpack.core.XPackClientPlugin.getTransports(XPackClientPlugin.java:676)
        at org.elasticsearch.common.network.NetworkModule.<init>(NetworkModule.java:128)
        at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:198)
        at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:296)
        at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:130)
        at org.elasticsearch.xpack.client.PreBuiltXPackTransportClient.<init>(PreBuiltXPackTransportClient.java:47)
        at org.elasticsearch.xpack.client.PreBuiltXPackTransportClient.<init>(PreBuiltXPackTransportClient.java:42)
        at org.elasticsearch.xpack.client.PreBuiltXPackTransportClient.<init>(PreBuiltXPackTransportClient.java:38)
        at org.elasticsearch.xpack.client.PreBuiltXPackTransportClientTests.testPluginInstalled(PreBuiltXPackTransportClientTests.java:24)

        Caused by:
        ElasticsearchSecurityException[failed to load SSL configuration [xpack.security.http.ssl]]; nested: ElasticsearchException[failed to initialize the SSLContext]; nested: KeyManagementException[FIPS mode: only SunJSSE TrustManagers may be used];
            at org.elasticsearch.xpack.core.ssl.SSLService.loadConfiguration(SSLService.java:527)
            at org.elasticsearch.xpack.core.ssl.SSLService.lambda$loadSSLConfigurations$4(SSLService.java:500)
            at java.util.HashMap.forEach(HashMap.java:1289)
            at org.elasticsearch.xpack.core.ssl.SSLService.loadSSLConfigurations(SSLService.java:500)
            at org.elasticsearch.xpack.core.ssl.SSLService.<init>(SSLService.java:145)
            at org.elasticsearch.xpack.core.XPackClientPlugin.getTransports(XPackClientPlugin.java:674)
            ... 8 more

            Caused by:
            ElasticsearchException[failed to initialize the SSLContext]; nested: KeyManagementException[FIPS mode: only SunJSSE TrustManagers may be used];
                at org.elasticsearch.xpack.core.ssl.SSLService.createSslContext(SSLService.java:456)
                at org.elasticsearch.xpack.core.ssl.SSLService.createSslContext(SSLService.java:432)
                at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
                at org.elasticsearch.xpack.core.ssl.SSLService.loadConfiguration(SSLService.java:524)
                ... 13 more

                Caused by:
                java.security.KeyManagementException: FIPS mode: only SunJSSE TrustManagers may be used
                    at sun.security.ssl.SSLContextImpl.chooseTrustManager(SSLContextImpl.java:120)
                    at sun.security.ssl.SSLContextImpl.engineInit(SSLContextImpl.java:83)
                    at javax.net.ssl.SSLContext.init(SSLContext.java:282)
                    at org.elasticsearch.xpack.core.ssl.SSLService.createSslContext(SSLService.java:449)
                    ... 16 more

```

## Frequency
The 7.x FIPS Java matrix tests have been failing since at least December 11th. Since these tests run twice per day, there have been 82 failures on the record. 38 of these failures involve `testPluginInstalled`.

**Comment by jkakavas** [comment]
This looks like https://github.com/elastic/elasticsearch/issues/49837 which was supposed to be resolved by https://github.com/elastic/elasticsearch/pull/49900. I'll look into why it didn't

**Comment by jkakavas** [comment]
In #49900, we disabled the diagnostic trust manager but only in the testclusters  ( i.e applicable only to integration tests ). We need to figure out a way to do this in unit tests also

**Comment by tlrx** [comment]
This test fails 6 times a day on multiple branches (7.x, 7.6 and 7.5) with the same failure.

Last build scan: https://gradle-enterprise.elastic.co/s/qybnber4wp7pg

I'm not muting it since the jobs notifications should be removed.

**Comment by dnhatn** [comment]
Another instance https://gradle-enterprise.elastic.co/s/ydxa2sgff45us

**Comment by rjernst** [comment]
Another instance https://gradle-enterprise.elastic.co/s/3nl5ka2t53ruo

**Comment by imotov** [comment]
Just saw similar errors in several watcher tests: https://gradle-enterprise.elastic.co/s/wc4l2pohxpn2a

org.elasticsearch.xpack.watcher.test.integration.BasicWatcherTests testConditionSearchWithSource
org.elasticsearch.xpack.watcher.test.integration.BasicWatcherTests testConditionSearchWithSource
org.elasticsearch.xpack.watcher.test.integration.BasicWatcherTests testConditionSearchWithSource
org.elasticsearch.xpack.watcher.test.integration.BasicWatcherTests testIndexWatch
org.elasticsearch.xpack.watcher.test.integration.BasicWatcherTests testIndexWatch
org.elasticsearch.xpack.watcher.test.integration.BasicWatcherTests testIndexWatch
org.elasticsearch.xpack.watcher.test.integration.BasicWatcherTests testInputFiltering
org.elasticsearch.xpack.watcher.history.HistoryTemplateTransformMappingsTests testTransformFields
org.elasticsearch.xpack.watcher.history.HistoryTemplateTransformMappingsTests testTransformFields
org.elasticsearch.xpack.watcher.history.HistoryTemplateTransformMappingsTests testTransformFields

**Comment by jkakavas** [comment]
For future on triage folks, FIPS testing in 7.x still needs some work, I'll update the original email thread when this is complete.

**Comment by jkakavas** [comment]
Issues in 7.x with fips mode have been resolved, closing this
