### ISSUE TITLE
[CI] DockerTests test040CreateKeystoreManually failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#51316]
On `master`: https://gradle-enterprise.elastic.co/s/6qeixtcfcjpem

```
java.lang.RuntimeException: Command was not successful: [bash -c docker exec --user elasticsearch:root --tty a72c1570e3770ae2bebd9babcd911c534473467d20c32304ad9a98b8e74f22b5 /usr/share/elasticsearch/bin/elasticsearch-keystore create]
   result: exitCode = [126] stdout = [OCI runtime exec failed: exec failed: cannot exec a container that has stopped: unknown] stderr = []
	at __randomizedtesting.SeedInfo.seed([6E50BAE912F0DC71:2B22F2D8BE2C3B34]:0)
	at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:135)
	at org.elasticsearch.packaging.util.Shell.run(Shell.java:77)
	at org.elasticsearch.packaging.test.DockerTests.test040CreateKeystoreManually(DockerTests.java:153)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by pugnascotia** [comment]
I haven't seen that failure before. I'm inclined to attribute it to general Docker wierdness, but I'll leave the issue open for a while and we'll see if it reoccurs.

**Comment by davidkyle** [comment]
@pugnascotia it happened again

Same error 
```
java.lang.RuntimeException: Command was not successful: [bash -c docker exec --user elasticsearch:root --tty df6aa0319fab9ecb76224e5eee53adf87a0e6d3390a6d2c13a1959408b5dc528 /usr/share/elasticsearch/bin/elasticsearch-keystore create]
   result: exitCode = [126] stdout = [OCI runtime exec failed: exec failed: cannot exec a container that has stopped: unknown] stderr = []
	at __randomizedtesting.SeedInfo.seed([60620617ACBDF971:25104E2600611E34]:0)
	at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:135)
	at org.elasticsearch.packaging.util.Shell.run(Shell.java:77)
	at org.elasticsearch.packaging.test.DockerTests.test040CreateKeystoreManually(DockerTests.java:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.6+multijob+packaging-tests-unix-gcp/os=debian-9-packaging/80/console
https://gradle-enterprise.elastic.co/s/lfzcmpxye6kce

**Comment by pugnascotia** [comment]
I don't have enough to go on here, so I'll see if I can add some code to capture more information.

**Comment by mark-vieira** [comment]
@pugnascotia this is still failing on `7.6`. Do we need to backport something there, or perhaps just mute this in the meantime if we aren't going to be able to fix it soon?

**Comment by williamrandolph** [comment]
One issue here is that these tests got moved to `KeystoreManagementTests` and modified in the process, so it's hard to see the differences between what 7.x and master do, and what's happening here. I'm taking a look to see if there's a missing backport.

**Comment by williamrandolph** [comment]
It looks like the 7.7 and master branches have a few extra calls to `waitForPathToExist(keystore)` when running this test. The changes are buried deep in feature branch work on the `KeystoreManagementTests` file, so there's no good way to backport them. But I will set up a PR that adds those calls for this version of the test.

**Comment by williamrandolph** [comment]
One note — I looked at some build records and noticed that this test's recent failures seem to be on Debian 9 only. Gradle scan links: [2 March](https://gradle-enterprise.elastic.co/s/l7vqciikcvrda), [1 March](https://gradle-enterprise.elastic.co/s/y3zug32vi7q2o), [1 March](https://gradle-enterprise.elastic.co/s/r6dcqifyo6ef6), [28 February](https://gradle-enterprise.elastic.co/s/tygqnlyv77cw2), [25 February](https://gradle-enterprise.elastic.co/s/m44pengwg72qk)

**Comment by probakowski** [comment]
Another instance of this: https://gradle-enterprise.elastic.co/s/xdauqpfu3gbbi, also Debian 9

**Comment by jaymode** [comment]
Another instance https://gradle-enterprise.elastic.co/s/kcud7vntywyf6 but on Debian 10

**Comment by williamrandolph** [comment]
Closing via #53437
