### ISSUE TITLE
[CI] Test failure: ConcurrentSeqNoVersioningIT » testSeqNoCASLinearizability

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#51329]
`ConcurrentSeqNoVersioningIT.testSeqNoCASLinearizability` failed in the following build:
 https://gradle-enterprise.elastic.co/s/tngp7hvapc5c6/console-log

I wasn't able to reproduce this failure locally.

Reproduce line:
```
./gradlew ':server:integTest' --tests "org.elasticsearch.versioning.ConcurrentSeqNoVersioningIT.testSeqNoCASLinearizability" -Dtests.seed=2657E8F9B4C405BC -Dtests.security.manager=true -Dtests.locale=en-NZ -Dtests.timezone=America/Toronto -Dcompiler.java=13
```

**Comment by henningandersen** [comment]
This `ClusterDisruptionIT` test failure looks related:
https://gradle-enterprise.elastic.co/s/pvcdd3ofnjkws/tests/kyv2y2z3r4v7m-5jnxwnv3ti4aw?open-stacktraces=WzBd

in that it also has:

```
org.elasticsearch.ElasticsearchException: publication cancelled before committing: timed out after 1s
```

This affects two builds, one on 21st January and one on 22nd January:

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(_source),index:f0e86d70-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'log:%20%22publication%20cancelled%20before%20committing:%20timed%20out%20after%201s%22'),sort:!(time,desc))

**Comment by henningandersen** [comment]
One more `ClusterDisruptionIT`. It has:

```
[2020-01-25T07:40:50,994][DEBUG][o.e.g.PersistedClusterStateService] [node_t1] writing cluster state took [802ms]; wrote global metadata [false] and metadata for [1] indices and skipped [0] unchanged indices
[2020-01-25T07:40:50,995][TRACE][o.e.d.PeerFinder         ] [node_t1] deactivating and setting leader to {node_t2}{QtOY0rJkRXmpkH0xgGHoZg}{Ea30Kzn6QHC22qRyh0R3fQ}{127.0.0.1}{127.0.0.1:38941}{dim}
[2020-01-25T07:40:50,995][TRACE][o.e.d.PeerFinder         ] [node_t1] not active
[2020-01-25T07:40:51,091][DEBUG][o.e.g.PersistedClusterStateService] [node_t0] writing cluster state took [1011ms]; wrote global metadata [false] and metadata for [1] indices and skipped [0] unchanged indices
[2020-01-25T07:40:51,091][TRACE][o.e.d.PeerFinder         ] [node_t0] deactivating and setting leader to {node_t2}{QtOY0rJkRXmpkH0xgGHoZg}{Ea30Kzn6QHC22qRyh0R3fQ}{127.0.0.1}{127.0.0.1:38941}{dim}
[2020-01-25T07:40:51,091][TRACE][o.e.d.PeerFinder         ] [node_t0] not active
[2020-01-25T07:40:51,093][DEBUG][o.e.g.PersistedClusterStateService] [node_t2] writing cluster state took [1020ms]; wrote global metadata [false] and metadata for [1] indices and skipped [0] unchanged indices
```

which seems the likely cause of the publication timeout:

```
[2020-01-25T07:40:51,094][DEBUG][o.e.c.s.M.AckCountDownListener] [node_t2] ack received from node [{node_t0}{b_u8b1vZThyx--PcTJ-Cbg}{ZmPcAsP_T2y2y0RhkvXt_w}{127.0.0.1}{127.0.0.1:39767}{dim}], cluster_state update (version: 4)
org.elasticsearch.ElasticsearchException: publication cancelled before committing: timed out after 1s
	at org.elasticsearch.cluster.coordination.Publication.cancel(Publication.java:86) [main/:?]
	at org.elasticsearch.cluster.coordination.Coordinator$CoordinatorPublication$2.run(Coordinator.java:1303) [main/:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633) [main/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by henningandersen** [comment]
Running `testAckedIndexing` locally does not reveal the same long write times. Opened a [PR](#51462) to increase logging for `PersistedClusterStateService` to see if it gives a hint into where the time is spent on CI.

**Comment by ywelsch** [comment]
I wonder if we should increase the timeout. "1s" for publication timeout is very little time (same for leader and follower checks) for any small stalls to cause test failures. Also note that these tests randomly use multiple data paths, which means that the cluster state needs to be sequentially written to multiple paths. I would increase the timeouts to "5s" as this will only affect tests with NetworkUnresponsive disruption.
