### ISSUE TITLE
Reproducible failure in SearchableSnapshotDirectoryTests.testDirectoryReader

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#51326]
I got a reproducible test failure on 5efa91f393874efacbafa5f46c1d4519eda8a3c0, which is part of a PR commit but which I don't think has changed anything that would cause this:

```
org.elasticsearch.index.store.SearchableSnapshotDirectoryTests > testDirectoryReader FAILED
    java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at __randomizedtesting.SeedInfo.seed([7CFB623C04D13A8B:9EFEC0891F87DCC5]:0)
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:373)
        at java.base/java.util.ArrayList.get(ArrayList.java:425)
        at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1310)
        at org.elasticsearch.index.store.SearchableSnapshotDirectoryTests.lambda$testDirectoryReader$9(SearchableSnapshotDirectoryTests.java:148)
        at org.elasticsearch.index.store.SearchableSnapshotDirectoryTests.testDirectories(SearchableSnapshotDirectoryTests.java:315)
        at org.elasticsearch.index.store.SearchableSnapshotDirectoryTests.testDirectoryReader(SearchableSnapshotDirectoryTests.java:139)

REPRODUCE WITH ./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.index.store.SearchableSnapshotDirectoryTests.testDirectoryReader" -Dtests.seed=7CFB623C04D13A8B:9EFEC0891F87DCC5 -Dtests.security.manager=true -Dtests.jvms=4 -Dtests.locale=hi -Dtests.timezone=SystemV/HST10 -Dcompiler.java=13
```

**Comment by tlrx** [comment]
Closed by #51343
