### ISSUE TITLE
TransformTaskFailedStateIT.testForceStopFailedTransform failure

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#51360]
Seems to fail reliably for me on 7.x, although master does not reproduce. Will push a mute to just 7.x in a minute

https://gradle-enterprise.elastic.co/s/5umyhdar5us5u

```
Expected: a string matching the pattern <Failed to index documents into destination index due to permanent error: \[org.elasticsearch.xpack.transform.transforms.BulkIndexingException: Bulk index experienced \[7\] failures and at least 1 irrecoverable \[org.elasticsearch.xpack.transform.transforms.TransformException: Destination index mappings are incompatible with the transform configuration.;.*>
         but: the string was "Failed to index documents into destination index due to permanent error: [BulkIndexingException[Bulk index experienced [7] failures and at least 1 irrecoverable [TransformException[Destination index mappings are incompatible with the transform configuration.]; nested: MapperParsingException[failed to parse field [reviewer] of type [long] in document with id 'dRQkp_t5ubOfpvJaH8A0aekAAAAAAAAA'. Preview of field's value: 'user_0']; nested: IllegalArgumentException[For input string: \"user_0\"];; MapperParsingException[failed to parse field [reviewer] of type [long] in document with id 'dRQkp_t5ubOfpvJaH8A0aekAAAAAAAAA'. Preview of field's value: 'user_0']; nested: IllegalArgumentException[For input string: \"user_0\"];; java.lang.IllegalArgumentException: For input string: \"user_0\"]. Other failures: ]; nested: TransformException[Destination index mappings are incompatible with the transform configuration.]; nested: MapperParsingException[failed to parse field [reviewer] of type [long] in document with id 'dRQkp_t5ubOfpvJaH8A0aekAAAAAAAAA'. Preview of field's value: 'user_0']; nested: IllegalArgumentException[For input string: \"user_0\"];; TransformException[Destination index mappings are incompatible with the transform configuration.]; nested: MapperParsingException[failed to parse field [reviewer] of type [long] in document with id 'dRQkp_t5ubOfpvJaH8A0aekAAAAAAAAA'. Preview of field's value: 'user_0']; nested: IllegalArgumentException[For input string: \"user_0\"];; MapperParsingException[failed to parse field [reviewer] of type [long] in document with id 'dRQkp_t5ubOfpvJaH8A0aekAAAAAAAAA'. Preview of field's value: 'user_0']; nested: IllegalArgumentException[For input string: \"user_0\"];; java.lang.IllegalArgumentException: For input string: \"user_0\"]"
        at __randomizedtesting.SeedInfo.seed([3FB53C8D1073437D:EF173ECB4D24CBD2]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.transform.integration.TransformTaskFailedStateIT.testForceStopFailedTransform(TransformTaskFailedStateIT.java:81)
```

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:transform:qa:single-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.transform.integration.TransformTaskFailedStateIT.testForceStopFailedTransform" \
  -Dtests.seed=3FB53C8D1073437D \
  -Dtests.security.manager=true \
  -Dtests.locale=vi-VN \
  -Dtests.timezone=Antarctica/DumontDUrville \
  -Dcompiler.java=13 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':x-pack:plugin:transform:qa:single-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.transform.integration.TransformTaskFailedStateIT.testStartFailedTransform" \
  -Dtests.seed=3FB53C8D1073437D \
  -Dtests.security.manager=true \
  -Dtests.locale=vi-VN \
  -Dtests.timezone=Antarctica/DumontDUrville \
  -Dcompiler.java=13 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':x-pack:plugin:transform:qa:single-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.transform.integration.TransformTaskFailedStateIT.testForceStopFailedTransform" \
  -Dtests.seed=3FB53C8D1073437D \
  -Dtests.security.manager=true \
  -Dtests.locale=vi-VN \
  -Dtests.timezone=Antarctica/DumontDUrville \
  -Dcompiler.java=13 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':x-pack:plugin:transform:qa:single-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.transform.integration.TransformTaskFailedStateIT.testStartFailedTransform" \
  -Dtests.seed=3FB53C8D1073437D \
  -Dtests.security.manager=true \
  -Dtests.locale=vi-VN \
  -Dtests.timezone=Antarctica/DumontDUrville \
  -Dcompiler.java=13 \
  -Druntime.java=8
```

**Comment by hendrikmuhs** [comment]
I tracked this down, the problem is the different way exceptions are represented as strings. On `7.x` it uses simple names while on `master` `toString` produces full qualified names.

The change has been introduced in https://github.com/elastic/elasticsearch/pull/45878 with no plans to backport it to `master`.

**Comment by hendrikmuhs** [comment]
changed the title, FWIW: 

The failure is not caused because mappings are not compatible, this is what the test is about, it tests the error handling in such a case. The failure is the changed way of formatting the error message, which is different on `master` and `7.x`, see previous comment.

**Comment by hendrikmuhs** [comment]
fixed: https://github.com/elastic/elasticsearch/pull/51398
