### ISSUE TITLE
"Date aggregation per day of week" fails because of mismatched key

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#51367]
Fails reliably on 7x mixed cluster tests, looks to be related to https://github.com/elastic/elasticsearch/pull/50894.  @pgomulka can you confirm?  Not sure if this is a failure because of the core work, or because the agg is broken.  

I'm going to go ahead and re-mute the test on the 7x branch for now

https://gradle-enterprise.elastic.co/s/kai2vpaxjhiss

```
REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v7.6.0#mixedClusterTest' --tests "org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" \
  -Dtests.method="test {p0=search.aggregation/310_date_agg_per_day_of_week/Date aggregation per day of week}" \
  -Dtests.seed=DA5217E31CD2851F \
  -Dtests.security.manager=true \
  -Dtests.locale=ms-MY \
  -Dtests.timezone=America/Jamaica \
  -Dcompiler.java=13 \
  -Druntime.java=11
```
```java.lang.AssertionError: Failure at [search.aggregation/310_date_agg_per_day_of_week:44]: aggregations.test.buckets.0.key_as_string didn't match expected value:
    aggregations.test.buckets.0.key_as_string: expected String [7] but was String [1]
        at __randomizedtesting.SeedInfo.seed([DA5217E31CD2851F:52062839B22EE8E7]:0)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:405)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:382)
```

```
1>   "stash" : {
  1>     "body" : {
  1>       "took" : 106,
  1>       "timed_out" : false,
  1>       "_shards" : {
  1>         "total" : 1,
  1>         "successful" : 1,
  1>         "skipped" : 0,
  1>         "failed" : 0
  1>       },
  1>       "hits" : {
  1>         "total" : 1,
  1>         "max_score" : 1.0,
  1>         "hits" : [
  1>           {
  1>             "_index" : "test",
  1>             "_type" : "_doc",
  1>             "_id" : "1",
  1>             "_score" : 1.0,
  1>             "_source" : {
  1>               "date" : "2009-11-15T14:12:12"
  1>             }
  1>           }
  1>         ]
  1>       },
  1>       "aggregations" : {
  1>         "test" : {
  1>           "buckets" : [
  1>             {
  1>               "key_as_string" : "1",
  1>               "key" : 1258243200000,
  1>               "doc_count" : 1
  1>             }
  1>           ]
  1>         }
  1>       }
  1>     }
  1>   }
  1> }]
```

**Comment by polyfractal** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/51396 :)
