### ISSUE TITLE
Windows 7.5 vagrant packaging tests fail with refused localhost connection

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#51378]
Looks like vagrant died while trying to connect to localhost?  Several open and closed packaging tests, but I couldn't see something like this one

Not entirely sure this is the actual error, but it's the only thing in the logs that I spotted that looked like an error. Everything else just looks like debug output.

https://gradle-enterprise.elastic.co/s/qrtddgavsfh6w

```
| DEBUG winrmshell: [WinRM] Waiting for output...
| DEBUG winrmshell: [WinRM] cleaning up command_id: 5656D01E-C980-4D0A-B004-9DF15D864FC0 on shell_id 44BB310E-93A0-4BD8-B54F-EE9B0A0E5567
|  INFO environment: Running hook: environment_unload
|  INFO runner: Preparing hooks for middleware sequence...
|  INFO runner: 3 hooks defined.
|  INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x0000000002efca20>
| /opt/vagrant/embedded/gems/2.2.5/gems/httpclient-2.8.3/lib/httpclient/session.rb:623:in `rescue in create_socket': Connection refused - Connection refused - connect(2) for "127.0.0.1" port 55985 (127.0.0.1:55985) (Errno::ECONNREFUSED)
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/httpclient-2.8.3/lib/httpclient/session.rb:607:in `create_socket'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/httpclient-2.8.3/lib/httpclient/session.rb:755:in `block in connect'
| 	from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
| 	from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/httpclient-2.8.3/lib/httpclient.rb:765:in `post'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/winrm-2.3.2/lib/winrm/http/transport.rb:176:in `send_request'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/winrm-2.3.2/lib/winrm/shells/power_shell.rb:42:in `close_shell'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/winrm-2.3.2/lib/winrm/shells/base.rb:89:in `close'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/winrm-elevated-1.1.1/lib/winrm/shells/elevated.rb:64:in `close'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/winrm-2.3.2/lib/winrm/connection.rb:44:in `ensure in shell'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/winrm-2.3.2/lib/winrm/connection.rb:44:in `shell'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/communicators/winrm/shell.rb:76:in `elevated'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/communicators/winrm/communicator.rb:152:in `execute'
| 	from /var/lib/jenkins/.vagrant.d/gems/2.4.6/gems/vagrant-winrm-0.7.0/lib/vagrant-winrm/commands/winrm.rb:58:in `block (2 levels) in execute'
| 	from /var/lib/jenkins/.vagrant.d/gems/2.4.6/gems/vagrant-winrm-0.7.0/lib/vagrant-winrm/commands/winrm.rb:56:in `each'
| 	from /var/lib/jenkins/.vagrant.d/gems/2.4.6/gems/vagrant-winrm-0.7.0/lib/vagrant-winrm/commands/winrm.rb:56:in `block in execute'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/plugin/v2/command.rb:238:in `block in with_target_vms'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/plugin/v2/command.rb:232:in `each'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
| 	from /var/lib/jenkins/.vagrant.d/gems/2.4.6/gems/vagrant-winrm-0.7.0/lib/vagrant-winrm/commands/winrm.rb:49:in `execute'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/cli.rb:66:in `execute'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/environment.rb:290:in `cli'
| 	from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/bin/vagrant:182:in `<main>'

```

**Comment by polyfractal** [comment]
Hmm, this one failed with a non-zero status too: https://gradle-enterprise.elastic.co/s/ehlvx3olik4h2

I don't see an actual failure in the logs, and it's SLES, but perhaps there's something generally going wrong with exit codes and not failing per-se

**Comment by mark-vieira** [comment]
Looks like the windows vagrant builds (surprisingly) have been passing on `master` and `7.x` so I'm gonna call this issue resolved.
