### ISSUE TITLE
[CI] ClusterStatsIT.testValuesSmokeScreen failurs

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#51598]
https://gradle-enterprise.elastic.co/s/woygwmt2ys3mi

Doesn't reproduce locally so far:
```
./gradlew ':server:integTest' --tests "org.elasticsearch.action.admin.cluster.stats.ClusterStatsIT.testValuesSmokeScreen" \
  -Dtests.seed=DF9F26DEFC7E8626 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-PR \
  -Dtests.timezone=CST6CDT \
  -Dcompiler.java=13 \
  -Druntime.java=8
```

The test seems to expect some free memory stats returned by the cluster stats to be in line with what we get via the node stats, at leasts that my reading of it so far.

```
org.elasticsearch.action.admin.cluster.stats.ClusterStatsIT > testValuesSmokeScreen FAILED
    java.lang.AssertionError: {
      "cluster_uuid" : "tTAYEluSQ5K_g-TQfp1JWQ",
      "timestamp" : 1580280454131,
      "status" : "yellow",
      "indices" : {
        "count" : 1,
        "shards" : {
          "total" : 1,
          "primaries" : 1,
          "replication" : 0.0,
          "index" : {
            "shards" : {
              "min" : 1,
              "max" : 1,
              "avg" : 1.0
            },
            "primaries" : {
              "min" : 1,
              "max" : 1,
              "avg" : 1.0
            },
            "replication" : {
              "min" : 0.0,
              "max" : 0.0,
              "avg" : 0.0
            }
          }
        },
        "docs" : {
          "count" : 0,
          "deleted" : 0
        },
        "store" : {
          "size_in_bytes" : 392
        },
        "fielddata" : {
          "memory_size_in_bytes" : 0,
          "evictions" : 0
        },
        "query_cache" : {
          "memory_size_in_bytes" : 0,
          "total_count" : 0,
          "hit_count" : 0,
          "miss_count" : 0,
          "cache_size" : 0,
          "cache_count" : 0,
          "evictions" : 0
        },
        "completion" : {
          "size_in_bytes" : 0
        },
        "segments" : {
          "count" : 0,
          "memory_in_bytes" : 0,
          "terms_memory_in_bytes" : 0,
          "stored_fields_memory_in_bytes" : 0,
          "term_vectors_memory_in_bytes" : 0,
          "norms_memory_in_bytes" : 0,
          "points_memory_in_bytes" : 0,
          "doc_values_memory_in_bytes" : 0,
          "index_writer_memory_in_bytes" : 199328,
          "version_map_memory_in_bytes" : 0,
          "fixed_bit_set_memory_in_bytes" : 0,
          "max_unsafe_auto_id_timestamp" : -1,
          "file_sizes" : { }
        }
      },
      "nodes" : {
        "count" : {
          "total" : 2,
          "coordinating_only" : 0,
          "data" : 2,
          "ingest" : 2,
          "master" : 2
        },
        "versions" : [
          "7.6.0"
        ],
        "os" : {
          "available_processors" : 64,
          "allocated_processors" : 7,
          "names" : [
            {
              "name" : "Linux",
              "count" : 2
            }
          ],
          "pretty_names" : [
            {
              "pretty_name" : "openSUSE Leap 15.1",
              "count" : 2
            }
          ],
          "mem" : {
            "total_in_bytes" : 202725531648,
            "free_in_bytes" : 87953149952,
            "used_in_bytes" : 114772381696,
            "free_percent" : 43,
            "used_percent" : 57
          }
        },
        "process" : {
          "cpu" : {
            "percent" : 6
          },
          "open_file_descriptors" : {
            "min" : 158,
            "max" : 158,
            "avg" : 158
          }
        },
        "jvm" : {
          "max_uptime_in_millis" : 24154,
          "versions" : [
            {
              "version" : "1.8.0_241",
              "vm_name" : "Java HotSpot(TM) 64-Bit Server VM",
              "vm_version" : "25.241-b07",
              "vm_vendor" : "Oracle Corporation",
              "bundled_jdk" : false,
              "using_bundled_jdk" : null,
              "count" : 2
            }
          ],
          "mem" : {
            "heap_used_in_bytes" : 301897704,
            "heap_max_in_bytes" : 1029701632
          },
          "threads" : 104
        },
        "fs" : {
          "total_in_bytes" : 50681380864,
          "free_in_bytes" : 42340581376,
          "available_in_bytes" : 42340581376
        },
        "plugins" : [
          {
            "name" : "org.elasticsearch.index.MockEngineFactoryPlugin",
            "version" : "NA",
            "elasticsearch_version" : "7.6.0",
            "java_version" : "1.8",
            "description" : "classpath plugin",
            "classname" : "org.elasticsearch.index.MockEngineFactoryPlugin",
            "extended_plugins" : [ ],
            "has_native_controller" : false
          },
          {
            "name" : "org.elasticsearch.test.MockHttpTransport$TestPlugin",
            "version" : "NA",
            "elasticsearch_version" : "7.6.0",
            "java_version" : "1.8",
            "description" : "classpath plugin",
            "classname" : "org.elasticsearch.test.MockHttpTransport$TestPlugin",
            "extended_plugins" : [ ],
            "has_native_controller" : false
          },
          {
            "name" : "org.elasticsearch.transport.nio.MockNioTransportPlugin",
            "version" : "NA",
            "elasticsearch_version" : "7.6.0",
            "java_version" : "1.8",
            "description" : "classpath plugin",
            "classname" : "org.elasticsearch.transport.nio.MockNioTransportPlugin",
            "extended_plugins" : [ ],
            "has_native_controller" : false
          },
          {
            "name" : "org.elasticsearch.test.ESIntegTestCase$AssertActionNamePlugin",
            "version" : "NA",
            "elasticsearch_version" : "7.6.0",
            "java_version" : "1.8",
            "description" : "classpath plugin",
            "classname" : "org.elasticsearch.test.ESIntegTestCase$AssertActionNamePlugin",
            "extended_plugins" : [ ],
            "has_native_controller" : false
          },
          {
            "name" : "org.elasticsearch.node.NodeMocksPlugin",
            "version" : "NA",
            "elasticsearch_version" : "7.6.0",
            "java_version" : "1.8",
            "description" : "classpath plugin",
            "classname" : "org.elasticsearch.node.NodeMocksPlugin",
            "extended_plugins" : [ ],
            "has_native_controller" : false
          },
          {
            "name" : "org.elasticsearch.index.mapper.MockFieldFilterPlugin",
            "version" : "NA",
            "elasticsearch_version" : "7.6.0",
            "java_version" : "1.8",
            "description" : "classpath plugin",
            "classname" : "org.elasticsearch.index.mapper.MockFieldFilterPlugin",
            "extended_plugins" : [ ],
            "has_native_controller" : false
          },
          {
            "name" : "org.elasticsearch.test.store.MockFSIndexStore$TestPlugin",
            "version" : "NA",
            "elasticsearch_version" : "7.6.0",
            "java_version" : "1.8",
            "description" : "classpath plugin",
            "classname" : "org.elasticsearch.test.store.MockFSIndexStore$TestPlugin",
            "extended_plugins" : [ ],
            "has_native_controller" : false
          },
          {
            "name" : "org.elasticsearch.test.ESIntegTestCase$TestSeedPlugin",
            "version" : "NA",
            "elasticsearch_version" : "7.6.0",
            "java_version" : "1.8",
            "description" : "classpath plugin",
            "classname" : "org.elasticsearch.test.ESIntegTestCase$TestSeedPlugin",
            "extended_plugins" : [ ],
            "has_native_controller" : false
          }
        ],
        "network_types" : {
          "transport_types" : {
            "mock-nio" : 2
          },
          "http_types" : { }
        },
        "discovery_types" : {
          "zen" : 2
        },
        "packaging_types" : [
          {
            "flavor" : "unknown",
            "type" : "unknown",
            "count" : 2
          }
        ],
        "ingest" : {
          "number_of_pipelines" : 0,
          "processor_stats" : { }
        }
      }
    }
 expected:<92571738112> but was:<87953149952>
        at __randomizedtesting.SeedInfo.seed([DF9F26DEFC7E8626:1F70C03334F26971]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.elasticsearch.action.admin.cluster.stats.ClusterStatsIT.testValuesSmokeScreen(ClusterStatsIT.java:197)
```

**Comment by cbuescher** [comment]
Similar looking failure from Jan 20th: https://gradle-enterprise.elastic.co/s/3eiu2fqvuz6xa/console-log?task=:server:integTest

**Comment by cbuescher** [comment]
This has been open without failing again for a long time. Closing.
