### ISSUE TITLE
[CI] InternalEngineTests.testSeqNoAndCheckpoints fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#51604]
https://gradle-enterprise.elastic.co/s/wluozr3bvl37q

I was able to reproduce this locally with 
```
./gradlew ':server:test' --tests "org.elasticsearch.index.engine.InternalEngineTests.testSeqNoAndCheckpoints" \
  -Dtests.seed=757179F3489F9FB1 \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-LB \
  -Dtests.timezone=Africa/Kinshasa \
  -Dcompiler.java=13
```

Failure:
```
java.lang.AssertionError: 
Expected: <45L>
     but: was <136L>
	at __randomizedtesting.SeedInfo.seed([757179F3489F9FB1:B7007CDEE170E515]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.index.engine.InternalEngineTests.testSeqNoAndCheckpoints(InternalEngineTests.java:2491)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at 
```

**Comment by cbuescher** [comment]
This looks related, although I couldn't reproduce as easily so far. Also on 7.5
https://gradle-enterprise.elastic.co/s/ooe34eh4rv5wg/console-log?task=:server:test
```
org.elasticsearch.index.engine.InternalEngineTests > testSeqNoAndCheckpoints FAILED
    java.lang.AssertionError: 
    Expected: <167L>
         but: was <173L>
        at __randomizedtesting.SeedInfo.seed([6DE8DAB7E64B115C:AF99DF9A4FA46BF8]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.index.engine.InternalEngineTests.testSeqNoAndCheckpoints(InternalEngineTests.java:2496)
```

**Comment by cbuescher** [comment]
An one from lately on 7.6: https://gradle-enterprise.elastic.co/s/yujoidwhlcpem/console-log?task=:server:test
