### ISSUE TITLE
[CI] Failures in DocsClientYamlTestSuiteIT.test {yaml=reference/cat/line_113}

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#51619]
https://gradle-enterprise.elastic.co/s/scq64g6dtjcka

There was no reproduce line in this one, but in earlier failures looking similar, e.g https://gradle-enterprise.elastic.co/s/v75nbxeirusvy from two days ago on 7.6. Unfortunately I wasn't able to reproduce with that one either
```
./gradlew ':docs:integTestRunner' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/cat/line_113}" \
  -Dtests.seed=4A91DAF216AE3A69 \
  -Dtests.security.manager=true \
  -Dtests.locale=fr \
  -Dtests.timezone=America/St_Lucia \
  -Dcompiler.java=13 \
  -Druntime.java=8
```

Failure:
```
java.lang.AssertionError: Failure at [reference/cat:2501]: field [$body] was expected to match the provided regex but didn't
Expected: health \s+status \s+index    \s+uuid                   \s+pri \s+rep \s+docs.count \s+docs.deleted \s+store.size \s+pri.store.size\s* yellow \s+open   \s+twitter  \s+.+   \s+1   \s+1       \s+1200            \s+0      \s+\d+         \s+\d+\s* green  \s+open   \s+twitter2 \s+.+   \s+1   \s+0          \s+0            \s+0        \s+\d+          \s+\d+\s*
     but: was "health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size\ngreen  open   twitter2 YsdLw8NnTZGzSys2je8VEw   1   0          0            0        230            230\nyellow open   twitter  WJOTPDu4T2uDMZYkMXSWOw   1   1       1200            0          0              0\n"
	at __randomizedtesting.SeedInfo.seed([3E289778ECCB39B2:B67CA8A24237544A]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:405)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:382)
```

**Comment by tvernum** [comment]
Happened again: https://gradle-enterprise.elastic.co/s/hzibqpssxbshq/tests
```
java.lang.AssertionError
Failure at [reference/cat:2501]: field [$body] was expected to match the provided regex but didn't
  Expected: health \s+status \s+index    \s+uuid                   \s+pri \s+rep \s+docs.count \s+docs.deleted \s+store.size \s+pri.store.size\s* yellow \s+open   \s+twitter  \s+.+   \s+1   \s+1       \s+1200            \s+0      \s+\d+         \s+\d+\s* green  \s+open   \s+twitter2 \s+.+   \s+1   \s+0          \s+0            \s+0        \s+\d+          \s+\d+\s*
  but: was "health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size\ngreen  open   twitter2 3JSF5JbkQ-ig8q-xv8ZuKQ   1   0          0            0        208            208\nyellow open   twitter  LjOILUzFR36TlDJ4LI6FGA   1   1       1200            0        171            171\n"
```

```
Stash dump on test failure [{
  "stash" : {
    "body" : "health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   twitter2 3JSF5JbkQ-ig8q-xv8ZuKQ   1   0          0            0        208            208
yellow open   twitter  LjOILUzFR36TlDJ4LI6FGA   1   1       1200            0        171            171
"
  }
}]
```

**Comment by ywangd** [comment]
Another occurence https://gradle-enterprise.elastic.co/s/2wcgdiayn2yyu

Cannot reproduce locally
```
./gradlew ':docs:integTestRunner' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/cat/line_121}" \
  -Dtests.seed=4B2CE2239EB28C5A \
  -Dtests.security.manager=true \
  -Dtests.locale=ja-JP-u-ca-japanese-x-lvariant-JP \
  -Dtests.timezone=Pacific/Rarotonga \
  -Druntime.java=8
```

Sample error message is:
```
java.lang.AssertionError: Failure at [reference/cat:2501]: field [$body] was expected to match the provided regex but didn't
Expected: health \s+status \s+index    \s+uuid                   \s+pri \s+rep \s+docs.count \s+docs.deleted \s+store.size \s+pri.store.size\s* yellow \s+open   \s+twitter  \s+.+   \s+1   \s+1       \s+1200            \s+0      \s+\d+         \s+\d+\s* green  \s+open   \s+twitter2 \s+.+   \s+1   \s+0          \s+0            \s+0        \s+\d+          \s+\d+\s*
     but: was "health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size\ngreen  open   twitter2 uizXeNU1RTWZWH8sWG2IdA   1   0          0            0        208            208\nyellow open   twitter  5w1iObXnSw6iDaSSZLeJow   1   1       1200            0          0              0\n"
```

**Comment by gwbrown** [comment]
Another instance: https://gradle-enterprise.elastic.co/s/hf5r57idfcgri

```
Stash dump on test failure [{	
  "stash" : {	
    "body" : "health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size	
green  open   twitter2 Hyvgl2D_TWCJ7uFOL2Bu6A   1   0          0            0        208            208	
yellow open   twitter  RoFeIcykSWKHm7sfWFFL-g   1   1       1200            0        171            171	
"	
  }	
}]
```

```
./gradlew ':docs:integTestRunner' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/cat/line_121}" -Dtests.seed=A57507B3389D897A -Dtests.security.manager=true -Dtests.locale=pl -Dtests.timezone=Africa/El_Aaiun -Dtests.distribution=default -Druntime.java=8
```

Does not reproduce locally.

**Comment by matriv** [comment]
One more similar instance: https://gradle-enterprise.elastic.co/s/qy3vyaetj2ovq

```
REPRODUCE WITH: ./gradlew ':docs:integTestRunner' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/cat/line_121}" -Dtests.seed=BE393751CBCC87B4 -Dtests.security.manager=true -Dtests.locale=sr-ME -Dtests.timezone=America/Argentina/Mendoza -Druntime.java=15
```

```
  |   |  
  | org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT > test {yaml=reference/cat/line_121} FAILED |  
  | java.lang.AssertionError: Failure at [reference/cat:2501]: field [$body] was expected to match the provided regex but didn't |  
  | Expected: health \s+status \s+index    \s+uuid                   \s+pri \s+rep \s+docs.count \s+docs.deleted \s+store.size \s+pri.store.size\s* yellow \s+open   \s+twitter  \s+.+   \s+1   \s+1       \s+1200            \s+0      \s+\d+         \s+\d+\s* green  \s+open   \s+twitter2 \s+.+   \s+1   \s+0          \s+0            \s+0        \s+\d+          \s+\d+\s* |  
  | but: was "health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size\ngreen  open   twitter2 ZUkmTVQeRGKUK4r5NHFKVA   1   0          0            0        208            208\nyellow open   twitter  adflCpA0SkqltfxqTQFtLA   1   1       1200            0        171            171\n" |  
  | at __randomizedtesting.SeedInfo.seed([BE393751CBCC87B4:366D088B6530EA4C]:0) |  
  | at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:405) |  
  | at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:382) |  
  | at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
```

**Comment by dakrone** [comment]
Another occurance: https://gradle-enterprise.elastic.co/s/56e2fyfzriwbc

**Comment by DaveCTurner** [comment]
Since #60598 this now looks to be failing a lot more. See e.g. https://gradle-enterprise.elastic.co/s/gf3mlgxvh7acc/console-log?task=:docs:integTestRunner. The issue is that the order of indices returned from `GET _cat/indices` is unspecified, but the doc test requires them to be in a particular order. Adding line-breaks to the message:

    Expected: health \s+status \s+index            \s+uuid                   \s+pri \s+rep \s+docs.count \s+docs.deleted \s+store.size \s+pri.store.size\s* 
    yellow \s+open   \s+my-index-000001  \s+.+   \s+1   \s+1       \s+1200            \s+0      \s+\d+         \s+\d+\s*
    green  \s+open   \s+my-index-000002  \s+.+   \s+1   \s+0          \s+0            \s+0        \s+\d+          \s+\d+\s*	
    
    but: was "health status index           uuid                   pri rep docs.count docs.deleted store.size pri.store.size\n
    green  open   my-index-000002 _Jl-G8TyRA6Gqhp92ZJAkA   1   0          0            0        208            208\n
    yellow open   my-index-000001 Jp27XZPPTKGZwIEMBWkJAQ   1   1       1200            0        208            208\n"	

Suppressing this test:

- `7.9`: 48ce73a41910900f7e2914dd7c86ca3bada94bae
- `7.x`: 75c0e4d044afe5f3c7cb8150fdcce4467259c50e
- `master`: cddac5317cb03541f6f533ae0e3d715a769dd216

**Comment by droberts195** [comment]
Two failures in quick succession for 7.8: https://gradle-enterprise.elastic.co/s/pg6rekgq6xc24 and https://gradle-enterprise.elastic.co/s/43edksbq4lyf6

I have cherry-picked the mute to the 7.8 branch: 37184eda16a44dce1807971b62aa51ac2003edd6
