### ISSUE TITLE
Failure to connect to remote cluster may prevent node startup

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#51855]
Today, if `RemoteClusterService#initializeRemoteClusters` times out while connecting to the remote clusters then the node logs a warning and continues. However if all of the connection attempts complete before the timeout, and any of them failed, then the exception will be propagated and the node will fail at startup.

For instance, with this `elasticsearch.yml`:

```
transport.connect_timeout: 10s
cluster.remote.test_remote.seeds: 192.168.1.1:9300 ## not a node
```

I get this:

```
[2020-02-04T10:29:43,739][DEBUG][o.e.t.RemoteClusterConnection] [node-0] [test_remote] opening connection to seed node: [{test_remote#192.168.1.1:9300}{9uVe8O5nSpGLTlweWgp74Q}{192.168.1.1}{192.168.1.1:9300}{dim}] proxy address: []
[2020-02-04T10:29:53,769][WARN ][o.e.t.RemoteClusterConnection] [node-0] fetching nodes from external cluster [test_remote] failed
org.elasticsearch.transport.ConnectTransportException: [][192.168.1.1:9300] connect_timeout[10s]
	at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onTimeout(TcpTransport.java:995) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:703) ~[elasticsearch-7.5.1.jar:7.5.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
[2020-02-04T10:29:53,776][WARN ][o.e.t.RemoteClusterService] [node-0] failed to update seed list for cluster: test_remote
org.elasticsearch.transport.ConnectTransportException: [][192.168.1.1:9300] connect_timeout[10s]
	at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onTimeout(TcpTransport.java:995) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:703) ~[elasticsearch-7.5.1.jar:7.5.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
[2020-02-04T10:29:53,779][ERROR][o.e.b.Bootstrap          ] [node-0] Exception
java.lang.IllegalStateException: failed to connect to remote clusters
	at org.elasticsearch.transport.RemoteClusterService.initializeRemoteClusters(RemoteClusterService.java:450) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:241) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:59) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.node.Node.start(Node.java:688) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:273) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:358) [elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) [elasticsearch-cli-7.5.1.jar:7.5.1]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) [elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-7.5.1.jar:7.5.1]
Caused by: java.util.concurrent.ExecutionException: ConnectTransportException[[][192.168.1.1:9300] connect_timeout[10s]]
	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:266) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:239) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:65) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.transport.RemoteClusterService.initializeRemoteClusters(RemoteClusterService.java:444) ~[elasticsearch-7.5.1.jar:7.5.1]
	... 12 more
Caused by: org.elasticsearch.transport.ConnectTransportException: [][192.168.1.1:9300] connect_timeout[10s]
	at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onTimeout(TcpTransport.java:995) ~[elasticsearch-7.5.1.jar:7.5.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:703) ~[elasticsearch-7.5.1.jar:7.5.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:830) ~[?:?]
```

Roughly the same thing happens in the event of a `Connection refused`.

**Comment by DaveCTurner** [comment]
Turns out this is already open as https://github.com/elastic/elasticsearch/issues/27006 so I'm closing this.
