### ISSUE TITLE
[TEST] DocumentSubsetBitsetCacheTests.testCacheUnderConcurrentAccess failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#51914]
https://gradle-enterprise.elastic.co/s/wl7uqqpo2ep7e/tests/sbbvdtbroicas-3wxlzqkg2i6xo

```
java.lang.AssertionError: Query threads did not complete in expected timeClose stacktrace
at __randomizedtesting.SeedInfo.seed([56E0E4E4803B5BAC:BAEA805D1F939CFE]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.elasticsearch.xpack.core.security.authz.accesscontrol.DocumentSubsetBitsetCacheTests.lambda$testCacheUnderConcurrentAccess$13(DocumentSubsetBitsetCacheTests.java:396)
at org.elasticsearch.xpack.core.security.authz.accesscontrol.DocumentSubsetBitsetCacheTests.runTestOnIndices(DocumentSubsetBitsetCacheTests.java:554)
at org.elasticsearch.xpack.core.security.authz.accesscontrol.DocumentSubsetBitsetCacheTests.testCacheUnderConcurrentAccess(DocumentSubsetBitsetCacheTests.java:372)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at java.lang.Thread.run(Thread.java:748)
[2020-02-05T17:36:58,178][INFO ][o.e.x.c.s.a.a.DocumentSubsetBitsetCacheTests] [testCacheUnderConcurrentAccess] before test
[2020-02-05T17:36:58,764][INFO ][o.e.x.c.s.a.a.DocumentSubsetBitsetCache] [[pool-6-thread-13]] the Document Level Security BitSet cache is full which may impact performance; consider increasing the value of [xpack.security.dls.bitset.cache.size]
[2020-02-05T17:36:59,723][INFO ][o.e.x.c.s.a.a.DocumentSubsetBitsetCacheTests] [testCacheUnderConcurrentAccess] after test
```

Looks like the timeout chosen (1s) could be too small.

**Comment by mark-vieira** [comment]
There are a lot of these. This one is failing pretty consistently once or twice a day since it was introduced. 👍 on bumping the timeout here in necessary or perhaps trying to slim this test down a bit. 2+ seconds for a unit test seems a bit hefty IMO.

https://gradle-enterprise.elastic.co/scans/tests?failures.failureClassification=non_verification&list.offset=0&list.size=50&list.sortColumn=startTime&list.sortOrder=desc&search.buildOutcome=failure&search.buildToolType=gradle&search.buildToolType=maven&search.startTimeMax=1581058189946&search.startTimeMin=1578556800000&search.tags=CI&search.tags=not:nested&search.tags=not:pull-request&tests.container=org.elasticsearch.xpack.core.security.authz.accesscontrol.DocumentSubsetBitsetCacheTests&tests.sortField=FAILED&tests.test=testCacheUnderConcurrentAccess&tests.unstableOnly&trends.section=overview&trends.timeResolution=day&viewer.tzOffset=-480

**Comment by tvernum** [comment]
Muting

**Comment by gwbrown** [comment]
This test has been muted for over 2 years now, and running this locally several thousand time (including while heavily loading my machine) did not reproduce the failure, so I've opened https://github.com/elastic/elasticsearch/pull/91186 to unmute it. If it fails again, please agressively re-mute. If it hasn't failed in a week, I'll close this issue.

**Comment by gwbrown** [comment]
This test has been re-enabled for [a week with no failures](https://gradle-enterprise.elastic.co/scans/tests?search.rootProjectNames=elasticsearch&search.timeZoneId=America/Denver&tests.container=org.elasticsearch.xpack.core.security.authz.accesscontrol.DocumentSubsetBitsetCacheTests#), so I'm going to close this.
