### ISSUE TITLE
[CI] PermissionPrecedenceTests.testDifferentCombinationsOfIndices failed

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#51989]
The test `PermissionPrecedenceTests.testDifferentCombinationsOfIndices` failed today on CI on 7.5 branch:

```
java.lang.AssertionError
: 
All incoming requests on node [node_s1] should have finished. Expected 0 but got 322
Expected: <0L>
     but: was <322L>
```

The logs show the following warning:
```

[2020-02-06T20:28:14,781][WARN ][o.e.t.TcpTransport       ] [node_s2] exception caught on transport layer [TcpNioSocketChannel{localAddress=0.0.0.0/0.0.0.0:50738, remoteAddress=null}], closing connection
javax.net.ssl.SSLException: Closed engine without receiving the close alert message.
	at org.elasticsearch.xpack.security.transport.nio.SSLDriver.close(SSLDriver.java:165) ~[main/:?]
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:104) ~[elasticsearch-core-7.5.3-SNAPSHOT.jar:7.5.3-SNAPSHOT]
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:62) ~[elasticsearch-core-7.5.3-SNAPSHOT.jar:7.5.3-SNAPSHOT]
	at org.elasticsearch.xpack.security.transport.nio.SSLChannelContext.closeFromSelector(SSLChannelContext.java:206) ~[main/:?]
	at org.elasticsearch.nio.EventHandler.handleClose(EventHandler.java:240) [elasticsearch-nio-7.5.3-SNAPSHOT.jar:7.5.3-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.closeChannel(NioSelector.java:480) [elasticsearch-nio-7.5.3-SNAPSHOT.jar:7.5.3-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.queueChannelClose(NioSelector.java:311) [elasticsearch-nio-7.5.3-SNAPSHOT.jar:7.5.3-SNAPSHOT]
	at org.elasticsearch.xpack.security.transport.nio.SSLChannelContext.channelCloseTimeout(SSLChannelContext.java:217) [main/:?]
	at org.elasticsearch.nio.EventHandler.handleTask(EventHandler.java:178) [elasticsearch-nio-7.5.3-SNAPSHOT.jar:7.5.3-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.handleTask(NioSelector.java:274) [elasticsearch-nio-7.5.3-SNAPSHOT.jar:7.5.3-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.handleScheduledTasks(NioSelector.java:268) [elasticsearch-nio-7.5.3-SNAPSHOT.jar:7.5.3-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:184) [elasticsearch-nio-7.5.3-SNAPSHOT.jar:7.5.3-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:131) [elasticsearch-nio-7.5.3-SNAPSHOT.jar:7.5.3-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:835) [?:?]
```

It does not reproduce with:
```
./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.integration.PermissionPrecedenceTests.testDifferentCombinationsOfIndices" \
  -Dtests.seed=B9AF19744C8BB5ED \
  -Dtests.security.manager=true \
  -Dtests.locale=hr-HR \
  -Dtests.timezone=Australia/Currie \
  -Dcompiler.java=12 \
  -Druntime.java=12
```

Build scan is https://gradle-enterprise.elastic.co/s/5f3u5v42akdmu

**Comment by tlrx** [comment]
I muted the test on 7.5 in 0c1cd54e53984a18f9d5259a91392e8c09afed06

**Comment by BigPandaToo** [comment]
This specific AssertionError happened to many tests (all using TestCluster), but haven't happened since Oct 10th. Probably, but not confirmed) fixed by [this commit](https://github.com/elastic/elasticsearch/commit/2b5e337e8940d8027b10612a3b5cbd3c39fd84e2).
Ather failures of this test (NoNodeAvailableException) happened last time on Nov 10th correlate well with other tests failing with the same exception (probably a build break).
I have run this test locally with -Dtests.iters=1000 with no repro.
Considering all of this I suggest resolving this issue.
