### ISSUE TITLE
[CI] Snapshot Repository 3rd Party Test Failures

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#52064]
Two failures for GCS repository, different tests same error, file already existing:
```
[2020-02-07T14:20:27,332][INFO ][o.e.r.g.GoogleCloudStorageRepositoryClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  1>   "stash" : {	
  1>     "body" : {	
  1>       "error" : {	
  1>         "root_cause" : [	
  1>           {	
  1>             "type" : "file_already_exists_exception",	
  1>             "reason" : "7.x_integration_tests/index-794: Precondition Failed",	
  1>             "stack_trace" : "[7.x_integration_tests/index-794: Precondition Failed]; nested: FileAlreadyExistsException[7.x_integration_tests/index-794: Precondition Failed];	
  1> 	at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:644)	
  1> 	at org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:572)	
  1> 	at org.elasticsearch.rest.BytesRestResponse.build(BytesRestResponse.java:138)	
  1> 	at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:96)	
  1> 	at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:91)	
  1> 	at org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:58)	
  1> 	at org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:79)	
  1> 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$2(TransportMasterNodeAction.java:166)	
  1> 	at org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:94)	
  1> 	at org.elasticsearch.action.ActionListener$4.onFailure(ActionListener.java:173)	
  1> 	at org.elasticsearch.snapshots.SnapshotsService$8.clusterStateProcessed(SnapshotsService.java:1520)	
  1> 	at org.elasticsearch.cluster.service.MasterService$SafeClusterStateTaskListener.clusterStateProcessed(MasterService.java:534)	
  1> 	at org.elasticsearch.cluster.service.MasterService$TaskOutputs.lambda$processedDifferentClusterState$1(MasterService.java:421)	
  1> 	at java.util.ArrayList.forEach(ArrayList.java:1257)	
  1> 	at org.elasticsearch.cluster.service.MasterService$TaskOutputs.processedDifferentClusterState(MasterService.java:421)	
  1> 	at org.elasticsearch.cluster.service.MasterService.onPublicationSuccess(MasterService.java:281)	
  1> 	at org.elasticsearch.cluster.service.MasterService.publish(MasterService.java:273)	
  1> 	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:250)	
  1> 	at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73)	
  1> 	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151)	
  1> 	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)	
  1> 	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)	
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633)	
  1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)	
  1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)	
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)	
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)	
  1> 	at java.lang.Thread.run(Thread.java:748)	
  1> Caused by: java.nio.file.FileAlreadyExistsException: 7.x_integration_tests/index-794: Precondition Failed	
```

- "test {yaml=repository_gcs/10_repository/Register a repository with a" https://gradle-enterprise.elastic.co/s/x7w3oqqbjvlh2
- "test {yaml=repository_gcs/10_repository/Snapshot/Restore with repository-gcs}" https://gradle-enterprise.elastic.co/s/qwp3j7phbmiyc

Edit by @original-brownbear :

We have the same issue for S3, see https://github.com/elastic/elasticsearch/issues/52191 as well.  This is an infra issue https://github.com/elastic/elasticsearch/issues/52064#issuecomment-583639631. This may also show up on Azure until infra fixes the build job.

**Comment by original-brownbear** [comment]
This looks like a CI issue. Somehow two GCS third party runs happened at the same time and as expected conflicted with each other in the GCS repository.

One of them ran between:

```
Started today at 12:17:34 PM CET, finished today at 12:20:30 PM CET
```

```
Started today at 12:17:15 PM CET, finished today at 12:20:40 PM CET
```

I'll raise this with infra

**Comment by original-brownbear** [comment]
Same issue for S3 https://github.com/elastic/elasticsearch/issues/52191 ... seems we either gotta fix our tests to use sub-path of the paths infra passes in or fix this on the infra end. Waiting for infrastructure reponse before taking action

**Comment by original-brownbear** [comment]
I'm closing this for now. It hasn't happened again in more than a week now. Whatever work is left on the infra side to ensure this won't happen again can be tracked in the open infra issue.
