### ISSUE TITLE
[CI] S3RepositoryThirdPartyTests testCleanup failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#52191]
> RepositoryException[[test-repo] Could not read repository data because the contents of the repository do not match its expected state. This is likely the result of either concurrently modifying the contents of the repository by a process other than this cluster or an issue with the repository's underlyingstorage. The repository has been disabled to prevent corrupting its contents. To re-enable it and continue using it please remove the repository from the cluster and add it again to make the cluster recover the known state of the repository from its physical contents.]; nested: RepositoryException[[test-repo] could not read repository data from index blob]; nested: NoSuchFileException[Blob object [7.6_third_party_tests_F1B84128AFBC9306/index-0] not found: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: F47D2536C1B9782F; S3 Extended Request ID: SgQQ7ZESO4L3ti3I8kboTYftM9WBX8lBYTP+Yi9jeeIJuvf/WxPkT+n4nYRmEcDF7gagMvcNcQs=)];

<details>
 <summary>Stack trace</summary>
	at __randomizedtesting.SeedInfo.seed([F1B84128AFBC9306:A1921286D61103B3]:0)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.corruptedStateException(BlobStoreRepository.java:1121)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.lambda$getRepositoryData$41(BlobStoreRepository.java:1108)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository$2.clusterStateProcessed(BlobStoreRepository.java:1166)
	at org.elasticsearch.cluster.service.MasterService$SafeClusterStateTaskListener.clusterStateProcessed(MasterService.java:534)
	at org.elasticsearch.cluster.service.MasterService$TaskOutputs.lambda$processedDifferentClusterState$1(MasterService.java:421)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.elasticsearch.cluster.service.MasterService$TaskOutputs.processedDifferentClusterState(MasterService.java:421)
	at org.elasticsearch.cluster.service.MasterService.onPublicationSuccess(MasterService.java:281)
	at org.elasticsearch.cluster.service.MasterService.publish(MasterService.java:273)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:250)
	at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73)
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: RepositoryException[[test-repo] could not read repository data from index blob]; nested: NoSuchFileException[Blob object [7.6_third_party_tests_F1B84128AFBC9306/index-0] not found: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: F47D2536C1B9782F; S3 Extended Request ID: SgQQ7ZESO4L3ti3I8kboTYftM9WBX8lBYTP+Yi9jeeIJuvf/WxPkT+n4nYRmEcDF7gagMvcNcQs=)];
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:1193)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:1094)
	at org.elasticsearch.snapshots.SnapshotsService.getRepositoryData(SnapshotsService.java:174)
	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.lambda$masterOperation$0(TransportGetSnapshotsAction.java:100)
	at org.elasticsearch.action.support.PlainActionFuture.get(PlainActionFuture.java:32)
	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:100)
	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:57)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:99)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$3(TransportMasterNodeAction.java:170)
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	... 3 more
Caused by: java.nio.file.NoSuchFileException: Blob object [7.6_third_party_tests_F1B84128AFBC9306/index-0] not found: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: F47D2536C1B9782F; S3 Extended Request ID: SgQQ7ZESO4L3ti3I8kboTYftM9WBX8lBYTP+Yi9jeeIJuvf/WxPkT+n4nYRmEcDF7gagMvcNcQs=)
	at org.elasticsearch.repositories.s3.S3RetryingInputStream.openStream(S3RetryingInputStream.java:78)
	at org.elasticsearch.repositories.s3.S3RetryingInputStream.<init>(S3RetryingInputStream.java:64)
	at org.elasticsearch.repositories.s3.S3BlobContainer.readBlob(S3BlobContainer.java:86)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:1179)
	... 14 more
</details>

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.6+multijob+third-party-tests-s3/51/console
https://gradle-enterprise.elastic.co/s/z75xdwulzxu6q

Reproduce
```
./gradlew ':plugins:repository-s3:thirdPartyTest' --tests "org.elasticsearch.repositories.s3.S3RepositoryThirdPartyTests.testCleanup" \
  -Dtests.seed=F1B84128AFBC9306 \
  -Dtests.security.manager=true \
  -Dtests.locale=mk \
  -Dtests.timezone=Japan \
  -Dcompiler.java=13
```

**Comment by davidkyle** [comment]
It doesn't look like a transient failure but this is the only instance I found in build-stats so leaving unmuted for now.

**Comment by original-brownbear** [comment]
We have the same issue for GCS, infra is running 3rd party tests in parallel on the same path see https://github.com/elastic/elasticsearch/issues/52064

**Comment by original-brownbear** [comment]
Closing here, consolidated this with https://github.com/elastic/elasticsearch/issues/52064
