### ISSUE TITLE
[CI] ExternalTestCluster ensureEstimatedStats errors

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#52197]
The ironically named test `PreventFailingBuildIT.testSoThatTestsDoNotFail` has failed a number of times on 7.x with assertions errors in `ExternalTestCluster.ensureEstimatedStats`:.

```
java.lang.AssertionError: FixedBitSet cache size must be 0 on node: {integTest-0}{O4j40ofnS9SbW0kAauW13w}{OhAeH9E0TY-wR40Ea2GxrA}{127.0.0.1}{127.0.0.1:46333}{dim}{testattr=test, xpack.installed=true}
Expected: <0L>
     but: was <96L>
	at __randomizedtesting.SeedInfo.seed([30D5C8618BAB7026:9CAB15B4DF51DA0A]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.test.ExternalTestCluster.ensureEstimatedStats(ExternalTestCluster.java:178)
```

```
java.lang.AssertionError: Accounting breaker not reset to 0 on node: {integTest-0}{EOlEBokdTma0nmvNBUtjOw}{MlncAB9eQwGC5vViVFQgaA}{127.0.0.1}{127.0.0.1:45753}{dim}{testattr=test, xpack.installed=true}
Expected: <0L>
     but: was <4525L>
	at __randomizedtesting.SeedInfo.seed([E1B5690AD8D0B0EF:4DCBB4DF8C2A1AC3]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.test.ExternalTestCluster.ensureEstimatedStats(ExternalTestCluster.java:166)
```

The test is completely [empty](https://github.com/elastic/elasticsearch/blob/c77b80f01e142ee7aff6440163c791729d50866a/x-pack/qa/smoke-test-monitoring-with-watcher/src/test/java/org/elasticsearch/smoketest/PreventFailingBuildIT.java#L12) which I imagine is the cause of the problem. 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=ubuntu-18.04&&immutable/563/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=oraclelinux-6&&immutable/563/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=centos-6&&immutable/563/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=fedora-29&&immutable/563/console

Reproduces occasionally
```
./gradlew ':x-pack:qa:smoke-test-monitoring-with-watcher:integTestRunner' --tests "org.elasticsearch.smoketest.PreventFailingBuildIT.testSoThatTestsDoNotFail" \
  -Dtests.seed=38B89CB5D04F8F11 \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-LB \
  -Dtests.timezone=Africa/Djibouti \
  -Dcompiler.java=13
```

**Comment by davidkyle** [comment]
My local reproduction has an NPE in the log 

```
» WARN ][o.e.d.FileBasedSeedHostsProvider] [integTest-0] expected, but did not find, a dynamic hosts list at [/Source/7.x/elasticsearch/x-pack/qa/smoke-test-monitoring-with-watcher/build/testclusters/integTest-0/config/unicast_hosts.txt]
» ERROR][o.e.x.m.c.c.ClusterStatsCollector] [integTest-0] collector [cluster_stats] failed to collect data
»  java.lang.NullPointerException: null
»       at org.elasticsearch.xpack.monitoring.collector.cluster.ClusterStatsCollector.doCollect(ClusterStatsCollector.java:108) ~[x-pack-monitoring-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.xpack.monitoring.collector.Collector.collect(Collector.java:88) [x-pack-monitoring-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.xpack.monitoring.MonitoringService$MonitoringExecution$1.doRun(MonitoringService.java:251) [x-pack-monitoring-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
»       at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
»       at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
»       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
»       at java.lang.Thread.run(Thread.java:830) [?:?]
» WARN ][o.e.x.m.e.l.LocalExporter] [integTest-0] unexpected error while indexing monitoring document
»  org.elasticsearch.xpack.monitoring.exporter.ExportException: [.monitoring-es-7-2020.02.11/dlJJziIBRd-61U_zZ4p3IQ] IndexNotFoundException[no such index [.monitoring-es-7-2020.02.11]]
»       at org.elasticsearch.xpack.monitoring.exporter.local.LocalBulk.lambda$throwExportException$2(LocalBulk.java:125) ~[x-pack-monitoring-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
»       at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
»       at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
»       at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
»       at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
»       at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
»       at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
»       at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
»       at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
»       at org.elasticsearch.xpack.monitoring.exporter.local.LocalBulk.throwExportException(LocalBulk.java:126) [x-pack-monitoring-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.xpack.monitoring.exporter.local.LocalBulk.lambda$doFlush$0(LocalBulk.java:108) [x-pack-monitoring-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:70) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.ActionListener$4.onResponse(ActionListener.java:163) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.bulk.TransportBulkAction$BulkOperation$1.finishHim(TransportBulkAction.java:527) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.bulk.TransportBulkAction$BulkOperation$1.onFailure(TransportBulkAction.java:522) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:79) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.finishAsFailed(TransportReplicationAction.java:794) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:649) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$2.onNewClusterState(TransportReplicationAction.java:774) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onNewClusterState(ClusterStateObserver.java:311) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.postAdded(ClusterStateObserver.java:220) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.cluster.service.ClusterApplierService$1.run(ClusterApplierService.java:299) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
»       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
»       at java.lang.Thread.run(Thread.java:830) [?:?]
»  Caused by: org.elasticsearch.index.IndexNotFoundException: no such index [.monitoring-es-7-2020.02.11]
»       ... 12 more
»   ↑ repeated 10 times ↑
» WARN ][o.e.x.m.MonitoringService] [integTest-0] monitoring execution failed
»  org.elasticsearch.xpack.monitoring.exporter.ExportException: failed to flush export bulks
»       at org.elasticsearch.xpack.monitoring.exporter.ExportBulk$Compound.lambda$doFlush$0(ExportBulk.java:109) [x-pack-monitoring-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:71) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.xpack.monitoring.exporter.local.LocalBulk.throwExportException(LocalBulk.java:132) [x-pack-monitoring-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.xpack.monitoring.exporter.local.LocalBulk.lambda$doFlush$0(LocalBulk.java:108) [x-pack-monitoring-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:70) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.ActionListener$4.onResponse(ActionListener.java:163) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.bulk.TransportBulkAction$BulkOperation$1.finishHim(TransportBulkAction.java:527) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.bulk.TransportBulkAction$BulkOperation$1.onFailure(TransportBulkAction.java:522) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:79) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.finishAsFailed(TransportReplicationAction.java:794) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:649) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$2.onNewClusterState(TransportReplicationAction.java:774) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onNewClusterState(ClusterStateObserver.java:311) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.postAdded(ClusterStateObserver.java:220) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.cluster.service.ClusterApplierService$1.run(ClusterApplierService.java:299) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
»       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
»       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
»       at java.lang.Thread.run(Thread.java:830) [?:?]
»  Caused by: org.elasticsearch.xpack.monitoring.exporter.ExportException: bulk [default_local] reports failures when exporting documents
»       at org.elasticsearch.xpack.monitoring.exporter.local.LocalBulk.throwExportException(LocalBulk.java:121) ~[?:?]
»       ... 22 more
»   ↓ last 40 non error or warning messages from /Source/7.x/elasticsearch/x-pack/qa/smoke-test-monitoring-with-watcher/build/testclusters/integTest-0/logs/es.stdout.log ↓
» [2020-02-11T12:10:45,136][DEBUG][o.e.c.c.PublicationTransportHandler] [integTest-0] received diff cluster state version [76] with uuid [WcNI8CJWTUiX5xKHvv-tiw], diff size [154]
» [2020-02-11T12:10:45,168][INFO ][o.e.c.m.TemplateUpgradeService] [integTest-0] Starting template upgrade to version 7.7.0, 1 templates will be updated and 0 will be removed
» [2020-02-11T12:10:45,169][DEBUG][o.e.c.c.C.CoordinatorPublication] [integTest-0] publication ended successfully: Publication{term=1, version=76}
» [2020-02-11T12:10:45,175][INFO ][o.e.c.m.MetaDataIndexTemplateService] [integTest-0] adding template [.ml-config] for index patterns [.ml-config]
» [2020-02-11T12:10:45,176][DEBUG][o.e.c.c.PublicationTransportHandler] [integTest-0] received diff cluster state version [77] with uuid [47WBsXBgTWe4vELjSy6b5A], diff size [1300]
» [2020-02-11T12:10:45,206][DEBUG][o.e.c.c.C.CoordinatorPublication] [integTest-0] publication ended successfully: Publication{term=1, version=77}
» [2020-02-11T12:10:45,207][INFO ][o.e.c.m.TemplateUpgradeService] [integTest-0] Templates were upgraded successfully to version 7.7.0
» [2020-02-11T12:10:45,208][INFO ][o.e.c.m.MetaDataIndexTemplateService] [integTest-0] removing template [.ml-notifications-000001]
» [2020-02-11T12:10:45,209][DEBUG][o.e.c.c.PublicationTransportHandler] [integTest-0] received diff cluster state version [78] with uuid [JKRbBsOcTcWtmus-WddLBw], diff size [166]
» [2020-02-11T12:10:45,240][INFO ][o.e.c.m.TemplateUpgradeService] [integTest-0] Starting template upgrade to version 7.7.0, 1 templates will be updated and 0 will be removed
» [2020-02-11T12:10:45,241][DEBUG][o.e.c.c.C.CoordinatorPublication] [integTest-0] publication ended successfully: Publication{term=1, version=78}
» [2020-02-11T12:10:45,246][INFO ][o.e.c.m.MetaDataIndexTemplateService] [integTest-0] adding template [.ml-notifications-000001] for index patterns [.ml-notifications-000001]
» [2020-02-11T12:10:45,247][DEBUG][o.e.c.c.PublicationTransportHandler] [integTest-0] received diff cluster state version [79] with uuid [t4g4u3mESoKZLz0We9DorQ], diff size [407]
» [2020-02-11T12:10:45,281][DEBUG][o.e.c.c.C.CoordinatorPublication] [integTest-0] publication ended successfully: Publication{term=1, version=79}
» [2020-02-11T12:10:45,281][INFO ][o.e.c.m.TemplateUpgradeService] [integTest-0] Templates were upgraded successfully to version 7.7.0
» [2020-02-11T12:10:45,283][INFO ][o.e.c.m.MetaDataIndexTemplateService] [integTest-0] removing template [.triggered_watches]
» [2020-02-11T12:10:45,284][DEBUG][o.e.c.c.PublicationTransportHandler] [integTest-0] received diff cluster state version [80] with uuid [eUxizhkcTeqC2sylIpwVeQ], diff size [162]
» [2020-02-11T12:10:45,348][DEBUG][o.e.c.c.C.CoordinatorPublication] [integTest-0] publication ended successfully: Publication{term=1, version=80}
» [2020-02-11T12:10:45,354][INFO ][o.e.c.m.MetaDataIndexTemplateService] [integTest-0] adding template [.triggered_watches] for index patterns [.triggered_watches*]
» [2020-02-11T12:10:45,355][DEBUG][o.e.c.c.PublicationTransportHandler] [integTest-0] received diff cluster state version [81] with uuid [F8lZEQctRk6sGEPwGR53AA], diff size [438]
» [2020-02-11T12:10:45,404][DEBUG][o.e.c.c.C.CoordinatorPublication] [integTest-0] publication ended successfully: Publication{term=1, version=81}
» [2020-02-11T12:10:45,404][INFO ][o.e.c.m.MetaDataIndexTemplateService] [integTest-0] removing template [random_index_template]
» [2020-02-11T12:10:45,405][DEBUG][o.e.c.c.PublicationTransportHandler] [integTest-0] received diff cluster state version [82] with uuid [h4Iayn9vRuGViLUhWGVzPw], diff size [165]
» [2020-02-11T12:10:45,438][DEBUG][o.e.c.c.C.CoordinatorPublication] [integTest-0] publication ended successfully: Publication{term=1, version=82}
» [2020-02-11T12:10:45,440][INFO ][o.e.c.m.MetaDataIndexTemplateService] [integTest-0] removing template [.logstash-management]
» [2020-02-11T12:10:45,441][DEBUG][o.e.c.c.PublicationTransportHandler] [integTest-0] received diff cluster state version [83] with uuid [E5SqsRZhQjqWukUr86zl9A], diff size [164]
» [2020-02-11T12:10:45,472][INFO ][o.e.c.m.TemplateUpgradeService] [integTest-0] Starting template upgrade to version 7.7.0, 1 templates will be updated and 0 will be removed
» [2020-02-11T12:10:45,473][DEBUG][o.e.c.c.C.CoordinatorPublication] [integTest-0] publication ended successfully: Publication{term=1, version=83}
» [2020-02-11T12:10:45,479][INFO ][o.e.c.m.MetaDataIndexTemplateService] [integTest-0] adding template [.logstash-management] for index patterns [.logstash]
» [2020-02-11T12:10:45,480][DEBUG][o.e.c.c.PublicationTransportHandler] [integTest-0] received diff cluster state version [84] with uuid [eKsW5UY5RIqxzbZw1PpamA], diff size [470]
» [2020-02-11T12:10:45,518][DEBUG][o.e.c.c.C.CoordinatorPublication] [integTest-0] publication ended successfully: Publication{term=1, version=84}
» [2020-02-11T12:10:45,518][INFO ][o.e.c.m.TemplateUpgradeService] [integTest-0] Templates were upgraded successfully to version 7.7.0
» [2020-02-11T12:10:45,520][INFO ][o.e.c.m.MetaDataIndexTemplateService] [integTest-0] removing template [.watches]
» [2020-02-11T12:10:45,521][DEBUG][o.e.c.c.PublicationTransportHandler] [integTest-0] received diff cluster state version [85] with uuid [vBMHQIo2Sjuwm_OP8DV84Q], diff size [152]
» [2020-02-11T12:10:45,554][DEBUG][o.e.c.c.C.CoordinatorPublication] [integTest-0] publication ended successfully: Publication{term=1, version=85}
» [2020-02-11T12:10:45,561][INFO ][o.e.c.m.MetaDataIndexTemplateService] [integTest-0] adding template [.watches] for index patterns [.watches*]
» [2020-02-11T12:10:45,562][DEBUG][o.e.c.c.PublicationTransportHandler] [integTest-0] received diff cluster state version [86] with uuid [bcplGC6uT72qPoG8eVbNHg], diff size [465]
» [2020-02-11T12:10:45,618][DEBUG][o.e.c.c.C.CoordinatorPublication] [integTest-0] publication ended successfully: Publication{term=1, version=86}
» [2020-02-11T12:10:45.788348Z] [BUILD] Stopping node
```

**Comment by dnhatn** [comment]
Another instance https://gradle-enterprise.elastic.co/s/v2coswufl7wdw

**Comment by dnhatn** [comment]
Another instance https://gradle-enterprise.elastic.co/s/5ly5p5rghahyc

**Comment by martijnvg** [comment]
Thanks for triaging this failures @davidkyle and @dnhatn. I think that #52198 should fix this failure. Also the NPE that occurred should be fixed and I will open an issue for this.

**Comment by martijnvg** [comment]
After the fixes were merged this test hasn't failed any more: https://build-stats.elastic.co/goto/ab51733c787e7e5087fb4cf4dc4a0fe6
