### ISSUE TITLE
[CI] MlConfigIndexMappingsFullClusterRestartIT "testMlConfigIndexMappingsAfterMigration" throws NPE in BWC tests

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#52330]
The `org.elasticsearch.xpack.restart.MlConfigIndexMappingsFullClusterRestartIT.testMlConfigIndexMappingsAfterMigration` test is failing with an NPE in our backwards compatibility tests agains cluster versions `7.2.x` and earlier.

```
java.lang.NullPointerException: (No message provided)Close stacktrace
at __randomizedtesting.SeedInfo.seed([234483059A958EA3:27258D74F15039CE]:0)
at org.elasticsearch.xpack.restart.MlConfigIndexMappingsFullClusterRestartIT.testMlConfigIndexMappingsAfterMigration(MlConfigIndexMappingsFullClusterRestartIT.java:73)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java
```

Here are some examples (all the same):
https://gradle-enterprise.elastic.co/s/dzsbgsu6dpvws/tests/qd4sihvvde764-lapg7xdexsot2
https://gradle-enterprise.elastic.co/s/xhvdeheptfagi/tests/hq2nhp7terokm-lapg7xdexsot2
https://gradle-enterprise.elastic.co/s/tj7ecxau4tiv4/tests/2nrwnmtrro45c-lapg7xdexsot2

**Comment by mark-vieira** [comment]
FYI, this reliably reproduces locally for me so should be an easy one 😉 
https://gradle-enterprise.elastic.co/s/ttzs3rpjnv5zi/tests/2nrwnmtrro45c-lapg7xdexsot2

**Comment by mark-vieira** [comment]
To clarify since this is BWC with `7.x` versions this is happening on `master` branch builds.

**Comment by mark-vieira** [comment]
@dimitris-athanasiou mentioned he'll get to this tomorrow, so in the meantime I've muted it in 623990ea8a12af057d1f3deb4f73dea9896f61a0.
