### ISSUE TITLE
[CI] InternalTopMetricsTests.testReduceRandom failed

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#52462]
[Test failure](https://gradle-enterprise.elastic.co/s/niumdkgqi6hc2):
```
java.util.NoSuchElementException: No value presentClose stacktrace
at __randomizedtesting.SeedInfo.seed([B4D179AB99CAD593:74ECD5BABF974CC5]:0)
at java.util.Optional.get(Optional.java:148)
at org.elasticsearch.xpack.analytics.topmetrics.InternalTopMetricsTests.assertReduced(InternalTopMetricsTests.java:172)
at org.elasticsearch.xpack.analytics.topmetrics.InternalTopMetricsTests.assertReduced(InternalTopMetricsTests.java:38)
at org.elasticsearch.test.InternalAggregationTestCase.testReduceRandom(InternalAggregationTestCase.java:297)
```

Reproduces locally using:

```
./gradlew ':x-pack:plugin:analytics:test' --tests "org.elasticsearch.xpack.analytics.topmetrics.InternalTopMetricsTests.testReduceRandom"   -Dtests.seed=B4D179AB99CAD593   -Dtests.security.manager=true   -Dtests.locale=es-GT   -Dtests.timezone=Asia/Colombo   -Dcompiler.java=13
```

**Comment by mark-vieira** [comment]
As discovered during our weekly 😉 this test looks to be recently introduced (5 days ago) and has failed three times since.

@nik9000 since you're the test author perhaps you're in a good position to take a look at this?

Here are the three failures thus far (happening in `7.x` and `master`):
https://gradle-enterprise.elastic.co/s/2s2q3io5czz7g/tests/xsgvaa4zqnsq2-ltc7borl5khlq
https://gradle-enterprise.elastic.co/s/niumdkgqi6hc2/tests/xsgvaa4zqnsq2-ltc7borl5khlq
https://gradle-enterprise.elastic.co/s/43ic65l6jqu74/tests/xsgvaa4zqnsq2-ltc7borl5khlq

Same error in all.

**Comment by nik9000** [comment]
Closed the wrong issue.
