### ISSUE TITLE
Getting elasticsearch connection error.

### ISSUE THREAD

**Issue by manasatmicro** [elastic/elasticsearch#52501]
> Failed to query Elasticsearch using 'status:(*"Live"*)': ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f1fe5de4668>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f1fe5de4668>: Failed to establish a new connection: [Errno 111] Connection refused)
Traceback (most recent call last):
  File "/home/manas/Desktop/peeljobs/venv/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/manas/Desktop/peeljobs/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/manas/Desktop/peeljobs/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred
Traceback (most recent call last):
  File "/home/manas/Desktop/peeljobs/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 74, in perform_request

I got above error when i run the project i have elasticsearch version 6.8 installed in my system. Since 3 days i tried almost each method i found in google but it did not helped.

**Comment by ywelsch** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question rather than a bug, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
