### ISSUE TITLE
[CI] DebMetadataTests test05CheckLintian failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#52554]
This one failed today twice and in [this PR](https://github.com/elastic/elasticsearch/pull/52546) as well: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-unix-gcp-sample/4004

https://gradle-enterprise.elastic.co/s/gqkcaqxrdh5ci
https://gradle-enterprise.elastic.co/s/mkaimhdyjetdm

```
Error Message
java.lang.RuntimeException: Command was not successful: [bash -c lintian --fail-on-warnings /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-unix-gcp-sample/os/ubuntu-16.04-packaging/distribution/packages/no-jdk-deb/build/distributions/elasticsearch-7.7.0-SNAPSHOT-no-jdk-amd64.deb]
   result: exitCode = [1] stdout = [W: elasticsearch: hardening-no-relro usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libgcc_s.so.1
N: 92 tags overridden (32 errors, 60 warnings)] stderr = [warning: the authors of lintian do not recommend running it with root privileges!]
Stacktrace
java.lang.RuntimeException: Command was not successful: [bash -c lintian --fail-on-warnings /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-unix-gcp-sample/os/ubuntu-16.04-packaging/distribution/packages/no-jdk-deb/build/distributions/elasticsearch-7.7.0-SNAPSHOT-no-jdk-amd64.deb]
   result: exitCode = [1] stdout = [W: elasticsearch: hardening-no-relro usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libgcc_s.so.1
N: 92 tags overridden (32 errors, 60 warnings)] stderr = [warning: the authors of lintian do not recommend running it with root privileges!]
	at __randomizedtesting.SeedInfo.seed([443EBA59712C1B85:84C026B5CB587E3E]:0)
	at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:135)
	at org.elasticsearch.packaging.util.Shell.run(Shell.java:77)
	at org.elasticsearch.packaging.test.DebMetadataTests.test05CheckLintian(DebMetadataTests.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mark-vieira** [comment]
This test is definitely busted in `7.x` and `master`. See the [list of failures here](https://gradle-enterprise.elastic.co/scans/tests?failures.failureClassification=non_verification&list.offset=0&list.size=50&list.sortColumn=startTime&list.sortOrder=desc&search.buildToolType=gradle&search.buildToolType=maven&search.startTimeMax=1582271999999&search.startTimeMin=1582099200000&search.tags=CI&search.tags=not:pull-request&tests.container=org.elasticsearch.packaging.test.DebMetadataTests&tests.sortField=FAILED&tests.test=test05CheckLintian&tests.unstableOnly&trends.section=overview&trends.timeResolution=day&viewer.tzOffset=-480).

Given it's consistently failing I've muted this test in `7.x` (a8725cde53c75814ec3d1e1a0559925c682258b7) and `master` (4c98d0cefd6bd2c11bb51b03ff9702193c2078d4).

**Comment by droberts195** [comment]
This must be caused by https://github.com/elastic/ml-cpp/pull/1013

I will look into it tomorrow
