### ISSUE TITLE
[CI] RecoveryDuringReplicationTests.testResyncAfterPrimaryPromotion failing reproducibly

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#52598]
This test just failed and reproduces locally for me.

https://gradle-enterprise.elastic.co/s/lflqfnox2xl4c/tests/nfxodyych4uas-b7kbbqymo3ykc

```
    java.lang.AssertionError: 
    Expected: is <5>
         but: was <1>
        at __randomizedtesting.SeedInfo.seed([F5E9DF78AE4335DB:F82474D3A9A0FC1F]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.index.replication.RecoveryDuringReplicationTests.testResyncAfterPrimaryPromotion(RecoveryDuringReplicationTests.java:380)
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.index.replication.RecoveryDuringReplicationTests.testResyncAfterPrimaryPromotion" -Dtests.seed=F5E9DF78AE4335DB -Dtests.security.manager=true -Dtests.locale=es-ES -Dtests.timezone=Europe/Uzhgorod -Dcompiler.java=13
```

**Comment by mark-vieira** [comment]
Given this reproduced for me locally we are certain to encounter this failure again so I've muted this test in `master` with 1d0e342e8b19464f92cdccd45f9040ab67b0ac4e.

**Comment by mark-vieira** [comment]
Thanks, @ywelsch!
