### ISSUE TITLE
[CI] JdbcResultSetIT.testGettingTimeWithoutCalendar failure on 6.8

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#52650]
https://gradle-enterprise.elastic.co/s/znfjicejlmhbg

```
java.lang.AssertionError: expected: java.sql.Time<06:29:37> but was: java.sql.Time<06:29:37>
	at __randomizedtesting.SeedInfo.seed([505AA322B82E38D8:1C7592AA9695B53D]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.lambda$testGettingTimeWithoutCalendar$140(ResultSetTestCase.java:968)
	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1424)
	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.doWithQuery(ResultSetTestCase.java:1412)
	at org.elasticsearch.xpack.sql.qa.jdbc.ResultSetTestCase.testGettingTimeWithoutCalendar(ResultSetTestCase.java:963)
```

```
./gradlew ':x-pack:plugin:sql:qa:single-node:integTestRunner' \
  -Dtests.seed=505AA322B82E38D8 \
  -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT \
  -Dtests.method="testGettingTimeWithoutCalendar" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Latn-RS \
  -Dtests.timezone=Europe/Samara \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

Didn't try to reproduce this, but given [the history on a similar previous issue](https://github.com/elastic/elasticsearch/pull/51592), I'm opening this one for investigation.

**Comment by jkakavas** [comment]
Another failure today in 6.8: https://gradle-enterprise.elastic.co/s/gctso65fuspic

**Comment by matriv** [comment]
`6.8` : e6cbb428e909ca8f6f0f5e07bf51e9157ba7bc92

**Comment by matriv** [comment]
`6.8` : e6cbb428e909ca8f6f0f5e07bf51e9157ba7bc92
