### ISSUE TITLE
[CI] KibanaUserRoleIntegTests.testGetMappings failed

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#52703]
`KibanaUserRoleIntegTests.testGetMappings` failed in https://gradle-enterprise.elastic.co/s/m3c24vrdqulhc

The error was:

```
java.lang.AssertionError:
Expected: map containing ["properties"->ANYTHING]
     but: map was []
at __randomizedtesting.SeedInfo.seed([C200E0EBA372BE2A:8AD76B54A5D3320A]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.integration.KibanaUserRoleIntegTests.testGetMappings(KibanaUserRoleIntegTests.java:159)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:566)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1754)
at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:942)
at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:978)
at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:992)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:370)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:819)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:470)
at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:951)
at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:836)
at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:887)
at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:898)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:370)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:826)
```

The REPRO command for this was:

```
./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.integration.KibanaUserRoleIntegTests.testGetMappings" \
  -Dtests.seed=C200E0EBA372BE2A \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=nl \
  -Dtests.timezone=America/St_Kitts \
  -Dcompiler.java=13
```

That is hard to run locally as it requires the production license key, so I tried:

```
./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.integration.KibanaUserRoleIntegTests.testGetMappings" \
  -Dtests.seed=C200E0EBA372BE2A \
  -Dtests.security.manager=true \
  -Dtests.locale=nl \
  -Dtests.timezone=America/St_Kitts \
  -Dcompiler.java=13
```

This didn't reproduce the problem.  It _might_ be that the problem is due to something that's different in release builds.  However, this test has never failed before so it may well just be an obscure race condition.

**Comment by ywangd** [comment]
Sorry meant to comment on this earlier, but got lost in other stuff. I spent some time look at this issue, had a few theories and tried a few things but it didn't go anywhere. This particular test has only failed in such a way [once in the past year](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b646ed00-7efc-11e8-bf69-63c8ef516157,key:build.branch,negate:!t,params:(query:pull-request-2,type:phrase),type:phrase,value:pull-request-2),query:(match:(build.branch:(query:pull-request-2,type:phrase))))),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'%22KibanaUserRoleIntegTests%20testGetMappings%22%20AND%20%22map%20containing%20%5B%22properties%22-%3EANYTHING%5D%22'),sort:!(process.time-start,desc))). Since its failure, we have had quite a few releases already and it has not occured anymore. Hence I am closing it.

**Comment by javanna** [comment]
I have seen this again today: https://gradle-enterprise.elastic.co/s/hkvm377lppsuw/tests/:x-pack:plugin:security:internalClusterTest/org.elasticsearch.integration.KibanaUserRoleIntegTests/testGetMappings?top-execution=1 .

**Comment by gwbrown** [comment]
Still failing: https://gradle-enterprise.elastic.co/s/hkvm377lppsuw/tests/task/:x-pack:plugin:security:internalClusterTest/details/org.elasticsearch.integration.KibanaUserRoleIntegTests/testGetMappings?top-execution=1

**Comment by gwbrown** [comment]
That one has an easier repro line:
`./gradlew ':x-pack:plugin:security:internalClusterTest' --tests "org.elasticsearch.integration.KibanaUserRoleIntegTests.testGetMappings" -Dtests.seed=6F67924EAB32CB36 -Dtests.locale=es-GT -Dtests.timezone=Atlantic/Cape_Verde -Druntime.java=17`

But did not reproduce.
