### ISSUE TITLE
[CI] SLMSnapshotBlockingIntegTests. testSnapshotInProgress fails with RepositoryException

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#52843]
This test has failed twice in the past couple of days with the same error.

**7.6** - https://gradle-enterprise.elastic.co/s/tv5fgikdmzyr2/tests/rfsroxnx4sflo-wlzwik4zkn53q
**7.x** - https://gradle-enterprise.elastic.co/s/w6fidnrew2s2q/tests/rfsroxnx4sflo-wlzwik4zkn53q

```
org.elasticsearch.xpack.slm.SLMSnapshotBlockingIntegTests > testSnapshotInProgress FAILED
    RepositoryException[[repo-id] failed to delete snapshot [snap-ynqeulptsdal_nuh1vhz_w/MqsRQJKxT7aibyZQicRSpg]]; nested: RepositoryException[[repo-id] concurrent modification of the index-N file, expected current generation [0], actual current generation [-1]];
        at __randomizedtesting.SeedInfo.seed([6FD1076493431DF:BF421ED8C738C0D1]:0)
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.deleteSnapshot(BlobStoreRepository.java:524)
        at org.elasticsearch.snapshots.SnapshotsService.lambda$deleteSnapshotFromRepository$16(SnapshotsService.java:1497)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:1134)
        at org.elasticsearch.snapshots.SnapshotsService.lambda$deleteSnapshotFromRepository$18(SnapshotsService.java:1497)
        at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        RepositoryException[[repo-id] concurrent modification of the index-N file, expected current generation [0], actual current generation [-1]]
            at org.elasticsearch.repositories.blobstore.BlobStoreRepository.safeRepositoryData(BlobStoreRepository.java:555)
            at org.elasticsearch.repositories.blobstore.BlobStoreRepository.deleteSnapshot(BlobStoreRepository.java:517)
            ... 10 more
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:test' --tests "org.elasticsearch.xpack.slm.SLMSnapshotBlockingIntegTests.testSnapshotInProgress" -Dtests.seed=6FD1076493431DF -Dtests.security.manager=true -Dtests.locale=es-CO -Dtests.timezone=Canada/Atlantic -Dcompiler.java=13
```

Unfortunately this did not locally reproduce for me.

**Comment by jaymode** [comment]
This failed again on 7.x, https://gradle-enterprise.elastic.co/s/uvvtgbdx3m6jg/tests/rfsroxnx4sflo-wlzwik4zkn53q.

**Comment by original-brownbear** [comment]
Fix incoming in https://github.com/elastic/elasticsearch/pull/54256

**Comment by jtibshirani** [comment]
This just failed again on 7.x intake: https://gradle-enterprise.elastic.co/s/rim27jxqybchu. The errors looks to be the same:

```
 2> RepositoryException[[repo-id] failed to delete snapshot [snap-qb-k7nlpsvschbtnlnojxq/_sH8w_4EQk-CKiRF2cpYyA]]; nested: RepositoryException[[repo-id] concurrent modification of the index-N file, expected current generation [0], actual current generation [-1]];
        at __randomizedtesting.SeedInfo.seed([7C5C97BB776CC2BB:C5E39915F96033B5]:0)
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.deleteSnapshot(BlobStoreRepository.java:525)
        at org.elasticsearch.snapshots.SnapshotsService.lambda$deleteSnapshotFromRepository$16(SnapshotsService.java:1507)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:1136)
        at org.elasticsearch.snapshots.SnapshotsService.lambda$deleteSnapshotFromRepository$18(SnapshotsService.java:1507)
        at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:695)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        RepositoryException[[repo-id] concurrent modification of the index-N file, expected current generation [0], actual current generation [-1]]
            at org.elasticsearch.repositories.blobstore.BlobStoreRepository.safeRepositoryData(BlobStoreRepository.java:556)
            at org.elasticsearch.repositories.blobstore.BlobStoreRepository.deleteSnapshot(BlobStoreRepository.java:518)
            ... 10 more
```

**Comment by original-brownbear** [comment]
This is missing a few backports I'm working on at the moment, will close once those are in in a bit. Sorry for the noise.

**Comment by original-brownbear** [comment]
This should be fixed now. Backported all consistency fixes to 7.x
