### ISSUE TITLE
Tribe node partialy breaks after 20+ min of runtime.

### ISSUE THREAD

**Issue by Jeppesen-io** [elastic/elasticsearch#5284]
After a tribe node has been running for 20min to an hour or more, _hosts query fails. Others queries seem to work, unfortunately Kibana needs to use the _hosts query to work. 

The ES clusters behind the tribe node have no errors that can be seen. I've tested this with 1.0.0 and 1.0.1.

```
curl http://tribenode:9200/_hosts/
(times out)
```

No errors are seen on the ES clusters the tribe node points to.

My workaround is to restart Elasticsearch on the tribe node every 20min

Tribe node configuration

```
tribe:
  tribe_datacenter1:
    cluster.name:   prod_datacenter1
    discovery.zen.ping.multicast.enabled: false
    transport.tcp.port: 9302
    discovery.zen.ping.unicast.hosts:  ["node1.datacenter1:9300""node2.datacenter1:9300,]

  tribe_datacenter2:
    cluster.name:   prod_datacenter2
    discovery.zen.ping.multicast.enabled: false
    transport.tcp.port: 9303
    discovery.zen.ping.unicast.hosts: ["node1.datacenter2:9300""node2.datacenter2:9300,]

cluster.name: prod_tribe
node.name: tribenode.local
transport.tcp.port: 9301
path.data: /data/elasticsearch/data
path.logs: /var/log/elasticsearch
```

Some metrics pulled from the the Tribe node from Elasticsearch HQ; as you can see, not much load at all.

Heap Used:  127.6MB
Heap Committed: 2.8GB
Non Heap Used:  28.0MB
Non Heap Committed: 28.6MB
JVM Uptime: 01:47:54
Thread Count/Peak:  60 / 68
GC (Old) Count: 4
GC (Old)Time:   00:00:00
GC (Young) Count:   0
GC (Young)Time: 00:00:00
Java Version:   1.7.0_51
JVM Vendor: Oracle Corporation
JVM:    OpenJDK 64-Bit Server VM
Uptime: 00:01:12
Total Memory:   4.73 GB
Total Swap: 2.00 GB
Memory (Used/Free): 897.54 MB / 3.85 GB
Swap (Used/Free):   0 B / 2.00 GB
CPU User/Sys:   0% / 0%
CPU Idle:   99%
CPU Vendor: Intel
CPU Model:  Xeon
Total Cores:    2
Index (Queue/Peak/Active):  0/0/0
Get (Queue/Peak/Active):    0/0/0
Search (Queue/Peak/Active): 0/0/0
Bulk (Queue/Peak/Active):   0/0/0
Refresh (Queue/Peak/Active):    0/0/0
Flush (Queue/Peak/Active):  0/0/0
Merge (Queue/Peak/Active):  0/0/0
Management (Queue/Peak/Active): 0/1/1
Open File Descriptors:  389
CPU Usage:  0% of 200%
CPU System: 00:00:13
CPU User:   00:00:55
CPU Total:  00:01:08
Resident Memory:    316.3MB
Shared Memory:  12.7MB
Total Virtual Memory:   4.3GB

Errors seen on tribe node:

```
[2014-02-27 12:35:16,431][DEBUG][action.admin.cluster.node.info] [tribenode] failed to execute on node [zr5f6hDBQSGNubAhz2JX2g]
org.elasticsearch.transport.SendRequestTransportException: [tribenode/prod_datacenter2][inet[/1.1.1.1:9302]][cluster/nodes/info/n]
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:202)
        at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction.start(TransportNodesOperationAction.java:168)
        at org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction.access$300(TransportNodesOperationAction.java:102)
        at org.elasticsearch.action.support.nodes.TransportNodesOperationAction.doExecute(TransportNodesOperationAction.java:73)
        at org.elasticsearch.action.support.nodes.TransportNodesOperationAction.doExecute(TransportNodesOperationAction.java:43)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:63)
        at org.elasticsearch.client.node.NodeClusterAdminClient.execute(NodeClusterAdminClient.java:72)
        at org.elasticsearch.client.support.AbstractClusterAdminClient.nodesInfo(AbstractClusterAdminClient.java:179)
        at org.elasticsearch.rest.action.admin.cluster.node.info.RestNodesInfoAction.handleRequest(RestNodesInfoAction.java:105)
        at org.elasticsearch.rest.RestController.executeHandler(RestController.java:159)
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:142)
        at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:121)
        at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:83)
        at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:291)
        at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:43)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: org.elasticsearch.transport.NodeNotConnectedException: [tribenode/prod_datacenter2][inet[/1.1.1.1:9302]] Node not connected
        at org.elasticsearch.transport.netty.NettyTransport.nodeChannel(NettyTransport.java:859)
        at org.elasticsearch.transport.netty.NettyTransport.sendRequest(NettyTransport.java:540)
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:189)
        ... 43 more
```

**Comment by zijian1981** [comment]
i hit this issue too,es didnot report any error ,sometimes es can return result ,and in other time ,it throws index is missing exception.how can I work around? Thanks

**Comment by clintongormley** [comment]
We haven't seen this issue in recent years.  Closing
