### ISSUE TITLE
SQL cannot tranverse objects in wildcard field selection

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#52882]
If you index metricbeat system data and then try to search it with SQL using wildcard field selection it is successful if only leaf fields are present at the wildcard location, e.g.:
```
SELECT system.cpu.idle.* FROM \"metricbeat-7.6.0-2020.02.27-000001\" where metricset.name = 'cpu'
```

But throws an error if the wildcard matches an object field, e.g.:
```
SELECT system.cpu.* FROM \"metricbeat-7.6.0-2020.02.27-000001\" where metricset.name = 'cpu'
```

We should fix SQL so it can traverse object fields matching the wildcard and expend to the leaf fields those object fields contain.

The error currently thrown by the second query above is:
```
{
    "error": {
        "root_cause": [
            {
                "type": "sql_illegal_argument_exception",
                "reason": "Objects (returned by [system.cpu.idle]) are not supported"
            }
        ],
        "type": "sql_illegal_argument_exception",
        "reason": "Objects (returned by [system.cpu.idle]) are not supported"
    },
    "status": 500
}
```

stack trace:
```
[2020-02-27T11:36:37,171][WARN ][r.suppressed             ] [runTask-0] path: /_sql, params: {format=txt}
org.elasticsearch.xpack.sql.SqlIllegalArgumentException: Objects (returned by [system.cpu.idle]) are not supported
        at org.elasticsearch.xpack.sql.execution.search.extractor.FieldHitExtractor.unwrapCustomValue(FieldHitExtractor.java:125) ~[?:?]
        at org.elasticsearch.xpack.ql.execution.search.extractor.AbstractFieldHitExtractor.unwrapMultiValue(AbstractFieldHitExtractor.java:173) ~[?:?]
        at org.elasticsearch.xpack.ql.execution.search.extractor.AbstractFieldHitExtractor.extractFromSource(AbstractFieldHitExtractor.java:289) ~[?:?]
        at org.elasticsearch.xpack.ql.execution.search.extractor.AbstractFieldHitExtractor.extract(AbstractFieldHitExtractor.java:148) ~[?:?]
        at org.elasticsearch.xpack.sql.execution.search.SearchHitRowSet.extractValue(SearchHitRowSet.java:128) ~[?:?]
        at org.elasticsearch.xpack.sql.execution.search.SearchHitRowSet.extractValue(SearchHitRowSet.java:31) ~[?:?]
        at org.elasticsearch.xpack.sql.execution.search.ResultRowSet.getColumn(ResultRowSet.java:37) ~[?:?]
        at org.elasticsearch.xpack.sql.session.AbstractRowSet.column(AbstractRowSet.java:18) ~[?:?]
        at org.elasticsearch.xpack.sql.session.RowView.forEachColumn(RowView.java:38) ~[?:?]
        at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.lambda$createResponse$2(TransportSqlQueryAction.java:116) ~[?:?]
        at org.elasticsearch.xpack.sql.session.RowSet.forEachRow(RowSet.java:27) ~[?:?]
        at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.createResponse(TransportSqlQueryAction.java:114) ~[?:?]
        at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.createResponseWithSchema(TransportSqlQueryAction.java:109) ~[?:?]
        at org.elasticsearch.xpack.sql.plugin.TransportSqlQueryAction.lambda$operation$0(TransportSqlQueryAction.java:84) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.execution.search.Querier$ScrollActionListener.lambda$handleResponse$2(Querier.java:478) [x-pack-sql-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.lambda$clear$3(Querier.java:574) [x-pack-sql-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:70) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.ClearScrollController.onFreedContext(ClearScrollController.java:130) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.ClearScrollController.lambda$cleanScrollIds$2(ClearScrollController.java:115) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:54) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1116) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1194) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1174) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:54) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$1(SearchTransportService.java:289) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:748) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.transport.TransportService.access$100(TransportService.java:75) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.transport.TransportService$3.sendRequest(TransportService.java:128) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:694) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:607) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.SearchTransportService.sendFreeContext(SearchTransportService.java:106) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.ClearScrollController.lambda$cleanScrollIds$4(ClearScrollController.java:114) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.SearchScrollAsyncAction.collectNodesAndRun(SearchScrollAsyncAction.java:129) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.ClearScrollController.cleanScrollIds(ClearScrollController.java:105) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.ClearScrollController.lambda$new$1(ClearScrollController.java:71) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.ClearScrollController.run(ClearScrollController.java:80) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.TransportClearScrollAction.doExecute(TransportClearScrollAction.java:46) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.TransportClearScrollAction.doExecute(TransportClearScrollAction.java:30) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:153) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:129) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:64) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:94) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:83) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:396) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:70) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.clear(Querier.java:573) [x-pack-sql-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.execution.search.Querier$ScrollActionListener.lambda$handleResponse$3(Querier.java:478) [x-pack-sql-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.execution.search.ScrollCursor.handle(ScrollCursor.java:127) [x-pack-sql-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.execution.search.Querier$ScrollActionListener.handleResponse(Querier.java:476) [x-pack-sql-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.onResponse(Querier.java:548) [x-pack-sql-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.xpack.sql.execution.search.Querier$BaseActionListener.onResponse(Querier.java:522) [x-pack-sql-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:70) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:542) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:117) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:349) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:343) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:216) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$1(FetchSearchPhase.java:105) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:111) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:44) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:87) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
```

**Comment by wchaparro** [comment]
Superceded by ES|QL
