### ISSUE TITLE
[CI] Unix packaging tests (CertGenCliTests) fail due to missing /sbin/insserv when enabling ES systemd service

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#52909]
On the 7.6 branch, these tests:

```
org.elasticsearch.packaging.test.PackageTests  test32JavaHomeOverride
org.elasticsearch.packaging.test.CertGenCliTests  test40RunWithCert
org.elasticsearch.packaging.test.CertGenCliTests  test40RunWithCert
org.elasticsearch.packaging.test.PackageTests  test40StartServer
```

Failed because the `insserv` utility was not available:

```
10:18:46 org.elasticsearch.packaging.test.CertGenCliTests > test40RunWithCert FAILED
10:18:46     java.lang.RuntimeException: Command was not successful: [bash -c systemctl enable elasticsearch.service]
10:18:46        result: exitCode = [1] stdout = [] stderr = [Synchronizing state of elasticsearch.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
10:18:46     Executing: /usr/lib/systemd/systemd-sysv-install enable elasticsearch
10:18:46     /sbin/insserv: No such file or directory]
10:18:46         at __randomizedtesting.SeedInfo.seed([1BE0197E9FCCE1C4:838F143C878DD830]:0)
10:18:46         at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:135)
10:18:46         at org.elasticsearch.packaging.util.Shell.run(Shell.java:77)
10:18:46         at org.elasticsearch.packaging.util.Packages.runElasticsearchStartCommand(Packages.java:276)
10:18:46         at org.elasticsearch.packaging.test.PackagingTestCase.runElasticsearchStartCommand(PackagingTestCase.java:211)
10:18:46         at org.elasticsearch.packaging.test.PackagingTestCase.assertWhileRunning(PackagingTestCase.java:167)
10:18:46         at org.elasticsearch.packaging.test.CertGenCliTests.test40RunWithCert(CertGenCliTests.java:119)
```

There's no reproduction line to retry this, but the build failures can be seen at:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.6+multijob+packaging-tests-unix-gcp/os=opensuse-15-1-packaging/130/console
https://gradle-enterprise.elastic.co/s/yrjlaxunh3gii

**Comment by rjernst** [comment]
This looks to be OpenSUSE specific. There have been previous similar reports with [beats](https://discuss.elastic.co/t/insserv-compat-required-on-opensuse-leap-15/138034/2), seemingly because OpenSUSE was missing binaries systemd expected to exist, which get called when sysv init scripts exist, which we ship with in addition to our systemd service.

**Comment by rjernst** [comment]
I have been unable to find any more instances of this failure, thus I will close for now.
