### ISSUE TITLE
[CI] SqlNodeSubclassTests.testReplaceChildren fails for org.elasticsearch.xpack.ql.expression.predicate.operator.comparison.In

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#53011]
Most likely similar to https://github.com/elastic/elasticsearch/issues/52951.

```
REPRODUCE WITH: gradlew ':x-pack:plugin:sql:test' --tests "org.elasticsearch.xpack.sql.tree.SqlNodeSubclassTests" \
  -Dtests.method="testReplaceChildren {p0=class org.elasticsearch.xpack.ql.expression.predicate.operator.comparison.In}" \
  -Dtests.seed=6CDD4667F032DF98 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-EC \
  -Dtests.timezone=Europe/Gibraltar \
  -Dcompiler.java=13

REPRODUCE WITH: gradlew ':x-pack:plugin:sql:test' --tests "org.elasticsearch.xpack.sql.tree.SqlNodeSubclassTests" \
  -Dtests.method="testReplaceChildren {p0=class org.elasticsearch.xpack.ql.expression.predicate.operator.comparison.In}" \
  -Dtests.seed=6CDD4667F032DF98 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-EC \
  -Dtests.timezone=Europe/Gibraltar \
  -Dcompiler.java=13
```

```
java.lang.IllegalArgumentException: expected at least [2] children but received [1]
	at __randomizedtesting.SeedInfo.seed([6CDD4667F032DF98:5522E52A0934FF66]:0)
	at org.elasticsearch.xpack.ql.expression.predicate.operator.comparison.In.replaceChildren(In.java:52)
	at org.elasticsearch.xpack.ql.expression.predicate.operator.comparison.In.replaceChildren(In.java:33)
	at org.elasticsearch.xpack.ql.tree.NodeSubclassTests.testReplaceChildren(NodeSubclassTests.java:229)
```

**Comment by mark-vieira** [comment]
Since this has failed multiple times and reproduces locally I've muted this again in `master` (f9d5fac046b29d62fe92710c3b507d60ad37e659) and `7.x` (313d6d6f9f495a003b53ac6acd907403861bbdcf).
