### ISSUE TITLE
[CI] LocalIndicesCleanerTests.testHandlesWatcherHistory fails reproducibly

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#53025]
This test has failed a few times no on `master`:

```
org.elasticsearch.xpack.monitoring.cleaner.local.LocalIndicesCleanerTests > testHandlesWatcherHistory FAILED
    java.lang.AssertionError: 
    Expected: <7>
         but: was <6>
        at __randomizedtesting.SeedInfo.seed([4A140D21CCAC26DF:F8559B4CC0706069]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.monitoring.cleaner.local.LocalIndicesCleanerTests.lambda$assertIndicesCount$0(LocalIndicesCleanerTests.java:61)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:881)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:854)
        at org.elasticsearch.xpack.monitoring.cleaner.local.LocalIndicesCleanerTests.assertIndicesCount(LocalIndicesCleanerTests.java:54)
        at org.elasticsearch.xpack.monitoring.cleaner.local.LocalIndicesCleanerTests.testHandlesWatcherHistory(LocalIndicesCleanerTests.java:79)
REPRODUCE WITH: ./gradlew ':x-pack:plugin:monitoring:test' --tests "org.elasticsearch.xpack.monitoring.cleaner.local.LocalIndicesCleanerTests.testHandlesWatcherHistory" -Dtests.seed=4A140D21CCAC26DF -Dtests.security.manager=true -Dtests.locale=es-CL -Dtests.timezone=America/Caracas -Dcompiler.java=13
```

The example above reproduced for me locally.

https://gradle-enterprise.elastic.co/s/qevr265r5v2bo/tests/iu7lux6ygquas-ar7w2ggk5jvdw

**Comment by mark-vieira** [comment]
Since this reproduces I've muted this in `master` with 645d0bbe586f1004d5a6c5469767a69736996ed9.

**Comment by jaymode** [comment]
This one is probably caused by changing this index to be hidden. I will look into it.
