### ISSUE TITLE
InternalEngineTests.testVersionOnPrimaryWithConcurrentRefresh fails on 7.x

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#53185]
This failed today on CI. I was able to reproduce the issue randomly on my local box (1 failed out of 25 runs).

```
org.elasticsearch.index.engine.InternalEngineTests > testVersionOnPrimaryWithConcurrentRefresh {seed=[D2F9B6A214BAB707:1A2BB86EE40FBCBA]} FAILED
    org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
        at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:683)
        at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:697)
        at org.apache.lucene.index.IndexWriter.nrtIsCurrent(IndexWriter.java:5055)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:293)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:272)
        at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:262)
        at org.apache.lucene.index.FilterDirectoryReader.doOpenIfChanged(FilterDirectoryReader.java:112)
        at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:165)
        at org.elasticsearch.index.engine.ElasticsearchReaderManager.refreshIfNeeded(ElasticsearchReaderManager.java:66)
        at org.elasticsearch.index.engine.ElasticsearchReaderManager.refreshIfNeeded(ElasticsearchReaderManager.java:40)
        at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
        at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
        at org.elasticsearch.index.engine.InternalEngine$ExternalReaderManager.refreshIfNeeded(InternalEngine.java:354)
        at org.elasticsearch.index.engine.InternalEngine$ExternalReaderManager.refreshIfNeeded(InternalEngine.java:336)
        at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
        at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
        at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:1608)
        at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:1585)
        at org.elasticsearch.index.engine.InternalEngineTests.assertOpsOnPrimary(InternalEngineTests.java:2069)
        at org.elasticsearch.index.engine.InternalEngineTests.testVersionOnPrimaryWithConcurrentRefresh(InternalEngineTests.java:1930)

        Caused by:
        java.lang.RuntimeException: segments must include at least one segment
            at org.apache.lucene.index.MergePolicy$OneMerge.<init>(MergePolicy.java:233)
            at org.apache.lucene.index.IndexWriter$2.mergeFinished(IndexWriter.java:3194)
            at org.apache.lucene.index.IndexWriter.closeMergeReaders(IndexWriter.java:4440)
            at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4740)
            at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:4166)
            at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:625)
            at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.doMerge(ElasticsearchConcurrentMergeScheduler.java:101)
            at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:662)
```

https://gradle-enterprise.elastic.co/s/zyzt5krtzhnz4/console-log?task=:server:test

**Comment by jbaiera** [comment]
Muted 66788afa674

**Comment by dnhatn** [comment]
I believe this is caused by [LUCENE-8962](https://issues.apache.org/jira/browse/LUCENE-8962).
