### ISSUE TITLE
Tests failing for InternalEngineTests.testNonInternalVersioningOnPrimary

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#53182]
We have a test failure for this on master that randomly reproduces on my local machine:

```
org.elasticsearch.index.engine.InternalEngineTests > testNonInternalVersioningOnPrimary FAILED 
    java.lang.AssertionError: elasticsearch[[index][0]: Lucene Merge Thread #0]: RefCount is 0 pre-decrement for file "_4.cfe"
        at __randomizedtesting.SeedInfo.seed([D143CC6F61AAF842]:0)
        at org.apache.lucene.index.IndexFileDeleter$RefCount.DecRef(IndexFileDeleter.java:733)
        at org.apache.lucene.index.IndexFileDeleter.decRef(IndexFileDeleter.java:608)
        at org.apache.lucene.index.IndexFileDeleter.decRef(IndexFileDeleter.java:580)
        at org.apache.lucene.index.IndexWriter$2.mergeFinished(IndexWriter.java:3184)
        at org.apache.lucene.index.IndexWriter.closeMergeReaders(IndexWriter.java:4440)
        at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4740)
        at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:4166)
        at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:625)
        at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.doMerge(ElasticsearchConcurrentMergeScheduler.java:101)
        at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:662)
```

https://gradle-enterprise.elastic.co/s/3azaha44sogpu/console-log?task=:server:test
Fails in the same way intermittently on my local machine (0-2 times out of 25 runs)

**Comment by jbaiera** [comment]
Muted 72f3c688eb5

**Comment by dnhatn** [comment]
I believe this is caused by [LUCENE-8962](https://issues.apache.org/jira/browse/LUCENE-8962).
