### ISSUE TITLE
InternalEngineTests.testForceMergeWithSoftDeletesRetentionAndRecoverySource fails on 7.x

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#53190]
This test is failing on 7.x right now. Was able to reproduce it on my machine, though it's strange to me that it only ever fails the first time it is run. Running with 25 iterations it fails on the first test and passes on each of the 24 subsequent runs.

```
org.elasticsearch.index.engine.InternalEngineTests > testForceMergeWithSoftDeletesRetentionAndRecoverySource FAILED
    java.lang.AssertionError: Operation not found seq# [29], global checkpoint [13], retention policy [8], maxSeqNo [32], translog op [Delete{uid=_id:[fe 11], seqNo=29, primaryTerm=6393698793133348157, version=2}]
        at __randomizedtesting.SeedInfo.seed([EDB2AD768A37CC2D:6BBDAD46773C7FCA]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.elasticsearch.index.engine.EngineTestCase.assertConsistentHistoryBetweenTranslogAndLuceneIndex(EngineTestCase.java:1102)
        at org.elasticsearch.index.engine.InternalEngineTests.testForceMergeWithSoftDeletesRetentionAndRecoverySource(InternalEngineTests.java:1699)
```

https://gradle-enterprise.elastic.co/s/vybsiamlwzziu

**Comment by jbaiera** [comment]
Muted da8aac9e66a since this consistently fails locally.

**Comment by dnhatn** [comment]
I think we need to build a new Lucene snapshot including: https://github.com/apache/lucene-solr/pull/1313.

**Comment by dnhatn** [comment]
Close in favor of #53195.
