### ISSUE TITLE
GatewayMetaStatePersistedStateTests.testDataOnlyNodePersistence fails on 7.x

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#53193]
This test is failing on 7.x. Was able to get reproductions of the failure locally on 7.x and master:

```
org.elasticsearch.gateway.GatewayMetaStatePersistedStateTests > testDataOnlyNodePersistence FAILED
    java.lang.AssertionError: expected:<6847900867266479728> but was:<0>
        at __randomizedtesting.SeedInfo.seed([A7A8CBB0FF36C97F:12864D556F419E6D]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.elasticsearch.gateway.GatewayMetaStatePersistedStateTests.testDataOnlyNodePersistence(GatewayMetaStatePersistedStateTests.java:406)
```
https://gradle-enterprise.elastic.co/s/wpf5clcawfxfy

Since it is reproducing reliably in local on master and 7.x, I will mute the test for both of those branches.

**Comment by dnhatn** [comment]
Closes in favor of #53195.
