### ISSUE TITLE
[ML] RegressionIT.testDeleteExpiredData_RemovesUnusedState failure

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#53222]
Build link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_RUNTIME_JAVA=adoptopenjdk11,nodes=general-purpose/552/

Build scan: https://gradle-enterprise.elastic.co/s/zb5yacsugs5lu

Failure:

```
Expected: <100>
     but: was <12>
Close stacktrace
at __randomizedtesting.SeedInfo.seed([70B060F905106A19:4D7047A9B0AE438B]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertProgress(MlNativeDataFrameAnalyticsIntegTestCase.java:206)
at org.elasticsearch.xpack.ml.integration.RegressionIT.testDeleteExpiredData_RemovesUnusedState(RegressionIT.java:314)
```

Reproduce with:

```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testDeleteExpiredData_RemovesUnusedState" -Dtests.seed=70B060F905106A19 -Dtests.security.manager=true -Dtests.locale=hi -Dtests.timezone=America/Rio_Branco -Dcompiler.java=13
HomeTestsorg.elasticsearch.xpack.ml.integration.RegressionIT » testDeleteExpiredData_RemovesUnusedState
```

Can't reproduce locally.

**Comment by dimitris-athanasiou** [comment]
In this test failure progress for the `analyzing` phase was reported to be `12` after the job had finished. Looking into the logs I could not see anything abnormal. I will add additional logging and enable it for the test in order to understand how this could happen.

**Comment by mayya-sharipova** [comment]
Another failure on master today:

Log:https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/830/console
Build Scans: https://gradle-enterprise.elastic.co/s/gfklilu4gubkk
```
java.lang.AssertionError: 
Expected: <100>
     but: was <80>
	at __randomizedtesting.SeedInfo.seed([5EC28C76B207C9C2:6302AB2607B9E050]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertProgress(MlNativeDataFrameAnalyticsIntegTestCase.java:206)
```

**Comment by benwtrent** [comment]
:( that failure did not have the logging commit included. Once we have a failure with the logging commit added (https://github.com/elastic/elasticsearch/pull/53224) I think we can mute.

**Comment by droberts195** [comment]
elastic/ml-cpp#1045 is a temporary solution that should stop these failures (plus other failures that affect the C++ tests).

**Comment by dimitris-athanasiou** [comment]
And https://github.com/elastic/ml-cpp/pull/1048 should sort this out entirely.
