### ISSUE TITLE
InternalEngineTests testKeepTranslogAfterGlobalCheckpoint reproducible failure

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#53505]
`InternalEngineTests#testKeepTranslogAfterGlobalCheckpoint` failed on 7.x in CI and the failure reproduced locally for me.

```
./gradlew ':server:test' --tests "org.elasticsearch.index.engine.InternalEngineTests.testKeepTranslogAfterGlobalCheckpoint" -Dtests.seed=8FAEE298979A1A1F -Dtests.security.manager=true -Dtests.locale=uk -Dtests.timezone=Europe/Istanbul -Dcompiler.java=13
```

```
org.elasticsearch.index.engine.InternalEngineTests > testKeepTranslogAfterGlobalCheckpoint FAILED
    java.lang.AssertionError: 
    Expected: a value less than or equal to <32L>
         but: <33L> was greater than <32L>
        at __randomizedtesting.SeedInfo.seed([8FAEE298979A1A1F:92ADF96D18B4F38]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.index.engine.InternalEngineTests.testKeepTranslogAfterGlobalCheckpoint(InternalEngineTests.java:4882)
```

Build scan: https://gradle-enterprise.elastic.co/s/yxgoiqxlkrs5y

**Comment by dnhatn** [comment]
Fixed in #53704
