### ISSUE TITLE
S3RepositoryThirdPartyTests testCleanup failure in CI

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#53508]
In CI, the S3RepositoryThirdPartyTests testCleanup test failed. I checked to ensure that this is not the same issue as #52191, where multiple tests ran concurrently and it does not appear to be the case in this instance.

Reproduce line:

```
./gradlew ':plugins:repository-s3:thirdPartyTest' --tests "org.elasticsearch.repositories.s3.S3RepositoryThirdPartyTests.testCleanup" \
  -Dtests.seed=A30B885AB17443F3 \
  -Dtests.security.manager=true \
  -Dtests.locale=sq \
  -Dtests.timezone=America/Cayman \
  -Dcompiler.java=13
```

```
ElasticsearchTimeoutException[java.util.concurrent.TimeoutException: Timeout waiting for task.]; nested: TimeoutException[Timeout waiting for task.];
	at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:78)
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:61)
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:55)
	at org.elasticsearch.repositories.blobstore.BlobStoreTestUtil.assertConsistency(BlobStoreTestUtil.java:140)
	at org.elasticsearch.repositories.AbstractThirdPartyRepositoryTestCase.assertConsistentRepository(AbstractThirdPartyRepositoryTestCase.java:260)
	at org.elasticsearch.repositories.s3.S3RepositoryThirdPartyTests.lambda$assertConsistentRepository$1(S3RepositoryThirdPartyTests.java:94)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:893)
	at org.elasticsearch.repositories.s3.S3RepositoryThirdPartyTests.assertConsistentRepository(S3RepositoryThirdPartyTests.java:94)
	at org.elasticsearch.repositories.AbstractThirdPartyRepositoryTestCase.testCleanup(AbstractThirdPartyRepositoryTestCase.java:218)
```

```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=37, name=elasticsearch[node_s_0][generic][T#4], state=RUNNABLE, group=TGRP-S3RepositoryThirdPartyTests]
Caused by: java.lang.AssertionError: expected:<0> but was:<1>
	at __randomizedtesting.SeedInfo.seed([A30B885AB17443F3]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.elasticsearch.repositories.blobstore.BlobStoreTestUtil.assertIndexGenerations(BlobStoreTestUtil.java:147)
	at org.elasticsearch.repositories.blobstore.BlobStoreTestUtil.lambda$assertConsistency$0(BlobStoreTestUtil.java:129)
```

**Comment by original-brownbear** [comment]
This is a rare failure that is with 99% certainty coming from eventual consistency issues. The assertion that the `index.latest` blob is consistent with listing out the `index-N` blobs fails because an outdated `index.latest` is read. This seems to happen super rarely but I'll find a workaround for this, enhancing the test to properly spin until a consistent state is reached on S3 next week when I'm back from vacation.
