### ISSUE TITLE
TransportTasksActionTests testRunningTasksCount Failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#53594]
```
java.lang.AssertionError: expected:<2> but was:<3>
at __randomizedtesting.SeedInfo.seed([E6652F6E88B2BAA9:9AC6EF194B519F26]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at org.elasticsearch.action.admin.cluster.node.tasks.TransportTasksActionTests.testRunningTasksCount(TransportTasksActionTests.java:311)
```

https://gradle-enterprise.elastic.co/s/epykhvonxr2xw
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=opensuse-15-1&&immutable/633/console

```
 ./gradlew ':server:test' --tests "org.elasticsearch.action.admin.cluster.node.tasks.TransportTasksActionTests.testRunningTasksCount" \
  -Dtests.seed=E6652F6E88B2BAA9 \
  -Dtests.security.manager=true \
  -Dtests.locale=el \
  -Dtests.timezone=JST \
  -Dcompiler.java=13
```

Leaving unmuted as this is the only failure in the last 30 days and the test obviously needs extra logging to find out exactly which tasks were running.

**Comment by dnhatn** [comment]
I think this test failed because of the leftover from the other tests. However, I could not find it. I am closing this issue after adding debug logs to the test.

```
  1> [2020-03-15T02:51:41,728][INFO ][o.e.a.a.c.n.t.TransportTasksActionTests$1] [TransportTasksActionTests] Action on node 0
  1> [2020-03-15T02:51:41,729][INFO ][o.e.a.a.c.n.t.TransportTasksActionTests$1] [TransportTasksActionTests] Action on node 2
  1> [2020-03-15T02:51:41,729][INFO ][o.e.a.a.c.n.t.TransportTasksActionTests$1] [TransportTasksActionTests] Action on node 3
  1> [2020-03-15T02:51:41,729][INFO ][o.e.a.a.c.n.t.TransportTasksActionTests$1] [TransportTasksActionTests] Action on node 4
  1> [2020-03-15T02:51:41,736][INFO ][o.e.a.a.c.n.t.TransportTasksActionTests] [testRunningTasksCount] Awaiting for all actions to start
  1> [2020-03-15T02:51:41,736][INFO ][o.e.a.a.c.n.t.TransportTasksActionTests$1] [TransportTasksActionTests] Action on node 1
  1> [2020-03-15T02:51:41,737][INFO ][o.e.a.a.c.n.t.TransportTasksActionTests] [testRunningTasksCount] Done waiting for all actions to start
  1> [2020-03-15T02:52:11,768][INFO ][o.e.a.a.c.n.t.TransportTasksActionTests$1] [TransportTasksActionTests] Action on node 4 finished
  1> [2020-03-15T02:52:11,768][INFO ][o.e.a.a.c.n.t.TransportTasksActionTests$1] [TransportTasksActionTests] Action on node 0 finished
  1> [2020-03-15T02:52:11,768][INFO ][o.e.a.a.c.n.t.TransportTasksActionTests$1] [TransportTasksActionTests] Action on node 1 finished
  1> [2020-03-15T02:52:11,768][INFO ][o.e.a.a.c.n.t.TransportTasksActionTests$1] [TransportTasksActionTests] Action on node 2 finished
1> [2020-03-15T02:52:11,769][WARN ][o.e.t.TransportService   ] [TransportTasksActionTests] Transport response handler not found of id [9]
 1> [2020-03-15T02:52:11,768][INFO ][o.e.a.a.c.n.t.TransportTasksActionTests$1] [TransportTasksActionTests] Action on node 3 finished
```
