### ISSUE TITLE
XDocsClientYamlTestSuiteIT failure with ILM leaking tasks

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#53599]
```
3 active tasks found:
indices:data/write/bulk        oT2y26dGTVeMnp_Y_QOBdg:1821 -                           transport 1584357697516 11:21:37 141.4ms     127.0.0.1 node-0 requests[3], indices[ilm-history-2]
indices:data/write/bulk[s]     oT2y26dGTVeMnp_Y_QOBdg:1822 oT2y26dGTVeMnp_Y_QOBdg:1821 transport 1584357697516 11:21:37 141.1ms     127.0.0.1 node-0 requests[3], index[ilm-history-2-000001][0]
indices:data/write/bulk[s][p]  oT2y26dGTVeMnp_Y_QOBdg:1823 oT2y26dGTVeMnp_Y_QOBdg:1822 direct    1584357697517 11:21:37 140.5ms     127.0.0.1 node-0 requests[3], index[ilm-history-2-000001][0]
 expected:<0> but was:<3>
```

The error comes from the test cleanup

```
at __randomizedtesting.SeedInfo.seed([D3C5E258868125F6:5B91DD82287D480E]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.elasticsearch.test.rest.ESRestTestCase.lambda$waitForPendingTasks$3(ESRestTestCase.java:397)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:906)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:879)
at org.elasticsearch.test.rest.ESRestTestCase.waitForPendingTasks(ESRestTestCase.java:373)
at org.elasticsearch.xpack.test.rest.XPackRestIT.cleanup(XPackRestIT.java:207)
```
Failed on 7.x

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=debian-8&&immutable/631/console
https://gradle-enterprise.elastic.co/s/cf7fmntrkln2u

```
 ./gradlew ':x-pack:docs:integTestRunner' --tests "org.elasticsearch.smoketest.XDocsClientYamlTestSuiteIT.test {yaml=en/rest-api/security/invalidate-api-keys/line_72}" \
  -Dtests.seed=D3C5E258868125F6 \
  -Dtests.security.manager=true \
  -Dtests.locale=ar \
  -Dtests.timezone=Australia/Hobart \
  -Dcompiler.java=13
```

**Comment by dliappis** [comment]
Happened again in https://gradle-enterprise.elastic.co/s/ilifyy7bx7ouy
