### ISSUE TITLE
SharedClusterSnapshotRestoreIT testBasicWorkFlow timeout 

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#53596]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_RUNTIME_JAVA=corretto11,nodes=general-purpose/572/console
https://gradle-enterprise.elastic.co/s/e23neklzctruy/tests/kyv2y2z3r4v7m-flzpgaibakaf6

The test timed out waiting for a response, below is the client thread. There are other blocked threads.
```
"TEST-SharedClusterSnapshotRestoreIT.testBasicWorkFlow-seed#[D281C2A90534918D]" ID=30 WAITING on org.elasticsearch.common.util.concurrent.BaseFuture$Sync@22d111ed
    at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
    - waiting on org.elasticsearch.common.util.concurrent.BaseFuture$Sync@22d111ed
    at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1039)
    at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
    at app//org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:252)
    at app//org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:87)
    at app//org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:56)
    at app//org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:37)
    at app//org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.testBasicWorkFlow(SharedClusterSnapshotRestoreIT.java:273)
```

```
./gradlew ':server:integTest' --tests "org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.testBasicWorkFlow" \
  -Dtests.seed=D281C2A90534918D \
  -Dtests.security.manager=true \
  -Dtests.locale=ar \
  -Dtests.timezone=Atlantic/South_Georgia \
  -Dcompiler.java=13
```

**Comment by tbrooks8** [comment]
This is hanging on the call to restore the snapshot in the tests that I have looked at:

```
        logger.info("--> restore all indices from the snapshot");
        // This line
        RestoreSnapshotResponse restoreSnapshotResponse = client.admin().cluster().prepareRestoreSnapshot("test-repo", "test-snap")
            .setWaitForCompletion(true).execute().actionGet();
        assertThat(restoreSnapshotResponse.getRestoreInfo().totalShards(), greaterThan(0));

        ensureGreen();
        for (int i=0; i<5; i++) {
            assertHitCount(client.prepareSearch("test-idx-1").setSize(0).get(), 100L);
            assertHitCount(client.prepareSearch("test-idx-2").setSize(0).get(), 100L);
            assertHitCount(client.prepareSearch("test-idx-3").setSize(0).get(), 50L);
        }
```

**Comment by original-brownbear** [comment]
I wonder if this is just a `WindowsFS` issue along the same lines of https://github.com/elastic/elasticsearch/pull/52488. This has only happened twice (in two months and both time it was on `WindowsFS`) and it seems like we are stuck (but still doing work) on persisting cluster state/metadata on the data nodes when the test times out.

=> I'd close here given how rare this is. The only other alternative I see is to exclude `WindowsFS` from this test suite which in fact I'd rather not do because checking that we aren't deleting any open files is kind of a nice check for a snapshot related test.

=> We're ok to leave this be? :)

**Comment by original-brownbear** [comment]
Yea, I'm closing this. In the failed runs I'm seeing other tests take minutes as well. It's not like this test here is locking up, it's just that the others were so slow that this one ran into the time limit (after the others burnt through most of the 20min).
Running locally with the same seed doesn't take nearly as long (though still takes ~4min vs 1min for other FS impl) => I'd chalk these up to slow CI => closing
