### ISSUE TITLE
TimeSeriesLifecycleActionsIT testMoveToStepRereadsPolicy failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#53612]
```
org.elasticsearch.client.ResponseException: 
method [POST], host [http://127.0.0.1:60581], URI [_ilm/move/test-1], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"index [test-1] is not on current step [{\"phase\":\"hot\",\"action\":\"rollover\",\"name\":\"check-rollover-ready\"}], currently: [{\"phase\":\"hot\",\"action\":\"rollover\",\"name\":\"attempt-rollover\"}]"}],"type":"illegal_argument_exception","reason":"index [test-1] is not on current step [{\"phase\":\"hot\",\"action\":\"rollover\",\"name\":\"check-rollover-ready\"}], currently: [{\"phase\":\"hot\",\"action\":\"rollover\",\"name\":\"attempt-rollover\"}]"},"status":400}

at __randomizedtesting.SeedInfo.seed([F07F68215FC0E8D9:1E94C5D053AA5D83]:0)
at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:283)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:261)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testMoveToStepRereadsPolicy(TimeSeriesLifecycleActionsIT.java:999)
```

https://gradle-enterprise.elastic.co/s/difxc2k3viwzo/tests/ao2nxxbijves6-wpuko6jphmjui
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-windows-compatibility/os=windows-2019/499/console

```
gradlew ':x-pack:plugin:ilm:qa:multi-node:integTestRunner' --tests "org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testMoveToStepRereadsPolicy" \
  -Dtests.seed=F07F68215FC0E8D9 \
  -Dtests.security.manager=true \
  -Dtests.locale=hi \
  -Dtests.timezone=Asia/Urumqi \
  -Dcompiler.java=13
```

**Comment by DaveCTurner** [comment]
Muted this test:

- `master` == af298c6
- `7.x` == 53e2fec
- `7.7` == 357a3e6 
- `7.6` == ad2cc48f
