### ISSUE TITLE
[CI] SourceOnlySnapshotIT fails for testSnapshotAndRestore and testSnapshotAndRestoreWithNested

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#53684]
I've spotted this one after submitting a PR against 7.6 and failing consistently, just like in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/18770/console.

```
17:05:22   2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:core:internalClusterTest' --tests "org.elasticsearch.snapshots.SourceOnlySnapshotIT.testSnapshotAndRestore" -Dtests.seed=C8551ED852B77217 -Dtests.security.manager=true -Dtests.locale=pt-BR -Dtests.timezone=America/Costa_Rica -Dcompiler.java=13
17:05:22   2> Failed to execute phase [query], all shards failed; shardFailures {[cag3_5_9TKy2bHAHpZG-fg][test-idx][0]: RemoteTransportException[[node_sd2][127.0.0.1:45305][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: NotSerializableExceptionWrapper[unsupported_operation_exception: _source only indices can't be searched or filtered]; }
17:05:22         at __randomizedtesting.SeedInfo.seed([C8551ED852B77217:8327DAB8F788F20]:0)
17:05:22         at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:545)
17:05:22         at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:306)
17:05:22         at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:574)
17:05:22         at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:386)
17:05:22         at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$200(AbstractSearchAsyncAction.java:66)
17:05:22         at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:242)
17:05:22         at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73)
17:05:22         at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:59)
17:05:22         at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:423)
17:05:22         at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1130)
17:05:22         at org.elasticsearch.transport.InboundHandler.lambda$handleException$2(InboundHandler.java:244)
17:05:22         at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:225)
17:05:22         at org.elasticsearch.transport.InboundHandler.handleException(InboundHandler.java:242)
17:05:22         at org.elasticsearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:234)
17:05:22         at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:137)
17:05:22         at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:103)
17:05:22         at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:667)
17:05:22         at org.elasticsearch.transport.TcpTransport.consumeNetworkReads(TcpTransport.java:691)
17:05:22         at org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:276)
17:05:22         at org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:228)
17:05:22         at org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:40)
17:05:22         at org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:139)
17:05:22         at org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:151)
17:05:22         at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:420)
17:05:22         at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:246)
17:05:22         at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:174)
17:05:22         at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:131)
17:05:22         at java.lang.Thread.run(Thread.java:748)
17:05:22 
17:05:22         Caused by:
17:05:22         NotSerializableExceptionWrapper[unsupported_operation_exception: _source only indices can't be searched or filtered]
17:05:22             at org.elasticsearch.snapshots.SeqIdGeneratingFilterReader$SeqIdGeneratingSubReaderWrapper$1.terms(SeqIdGeneratingFilterReader.java:152)
17:05:22             at org.apache.lucene.index.FilterLeafReader.terms(FilterLeafReader.java:366)
17:05:22             at org.apache.lucene.index.TermStates.loadTermsEnum(TermStates.java:121)
17:05:22             at org.apache.lucene.index.TermStates.build(TermStates.java:109)
17:05:22             at org.apache.lucene.search.TermQuery.createWeight(TermQuery.java:199)
17:05:22             at org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:726)
17:05:22             at org.elasticsearch.search.internal.ContextIndexSearcher.createWeight(ContextIndexSearcher.java:138)
17:05:22             at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:445)
17:05:22             at org.elasticsearch.search.query.QueryPhase.searchWithCollector(QueryPhase.java:333)
17:05:22             at org.elasticsearch.search.query.QueryPhase.executeInternal(QueryPhase.java:295)
17:05:22             at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:134)
17:05:22             at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:338)
17:05:22             at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:358)
17:05:22             at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$1(SearchService.java:343)
17:05:22             at org.elasticsearch.action.ActionListener.lambda$map$2(ActionListener.java:146)
17:05:22             at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
17:05:22             at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:58)
17:05:22             at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73)
```

And, also:

```
17:05:22   2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:core:internalClusterTest' --tests "org.elasticsearch.snapshots.SourceOnlySnapshotIT.testSnapshotAndRestoreWithNested" -Dtests.seed=C8551ED852B77217 -Dtests.security.manager=true -Dtests.locale=pt-BR -Dtests.timezone=America/Costa_Rica -Dcompiler.java=13
17:05:22   2> Failed to execute phase [query], all shards failed; shardFailures {[Y8odgH8rTJWkKTXH9VhOyw][test-idx][0]: RemoteTransportException[[node_sd2][127.0.0.1:37117][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: UnsupportedOperationException[_source only indices can't be searched or filtered]; }
17:05:22         at __randomizedtesting.SeedInfo.seed([C8551ED852B77217:3FA244755A7E84F3]:0)
17:05:22         at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:545)
17:05:22         at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:306)
17:05:22         at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:574)
17:05:22         at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:386)
17:05:22         at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$200(AbstractSearchAsyncAction.java:66)
17:05:22         at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:242)
17:05:22         at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73)
17:05:22         at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:59)
17:05:22         at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:423)
17:05:22         at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1130)
17:05:22         at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1239)
17:05:22         at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1213)
17:05:22         at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:60)
17:05:22         at org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:56)
17:05:22         at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:71)
17:05:22         at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:65)
17:05:22         at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:58)
17:05:22         at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73)
17:05:22         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
17:05:22         at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)
17:05:22         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692)
17:05:22         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
17:05:22         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
17:05:22         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
17:05:22         at java.lang.Thread.run(Thread.java:748)
17:05:22 
17:05:22         Caused by:
17:05:22         [_source only indices can't be searched or filtered]; nested: UnsupportedOperationException[_source only indices can't be searched or filtered];
17:05:22             at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:644)
17:05:22             at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:304)
17:05:22             ... 23 more
17:05:22 
17:05:22             Caused by:
17:05:22             java.lang.UnsupportedOperationException: _source only indices can't be searched or filtered
17:05:22                 at org.elasticsearch.snapshots.SeqIdGeneratingFilterReader$SeqIdGeneratingSubReaderWrapper$1.terms(SeqIdGeneratingFilterReader.java:152)
17:05:22                 at org.apache.lucene.index.FilterLeafReader.terms(FilterLeafReader.java:366)
17:05:22                 at org.apache.lucene.index.TermStates.loadTermsEnum(TermStates.java:121)
17:05:22                 at org.apache.lucene.index.TermStates.build(TermStates.java:109)
17:05:22                 at org.apache.lucene.search.TermQuery.createWeight(TermQuery.java:199)
17:05:22                 at org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:726)
17:05:22                 at org.elasticsearch.search.internal.ContextIndexSearcher.createWeight(ContextIndexSearcher.java:138)
17:05:22                 at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:445)
17:05:22                 at org.elasticsearch.search.query.QueryPhase.searchWithCollector(QueryPhase.java:333)
17:05:22                 at org.elasticsearch.search.query.QueryPhase.executeInternal(QueryPhase.java:295)
17:05:22                 at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:134)
17:05:22                 at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:338)
17:05:22                 at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:358)
17:05:22                 at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$1(SearchService.java:343)
17:05:22                 at org.elasticsearch.action.ActionListener.lambda$map$2(ActionListener.java:146)
17:05:22                 at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
```

**Comment by dnhatn** [comment]
@DaveCTurner has fixed this issue in https://github.com/elastic/elasticsearch/pull/53671. @astefan Can you update your PR please?
