### ISSUE TITLE
[CI] ClassificationIT test failures

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#53691]
Surfaced [a few days ago](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+release-tests/1026/) and came back up during a [CI run](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/18802/) for PR #52382

```
09:54:38   2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testDependentVariableCardinalityTooHighButWithQueryMakesItWithinRange" -Dtests.seed=CB7F69BCEE4D2819 -Dtests.security.manager=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=ja-JP -Dtests.timezone=Etc/UTC -Dcompiler.java=13
09:54:38   2> ElasticsearchException[[memory_usage_estimation_88081] Error while closing process [Input error: unexpected parameter 'num_classes'. Please report this problem.
09:54:38     ], process errors: [Input error: unexpected parameter 'num_classes'. Please report this problem.
09:54:38     ]]; nested: ElasticsearchException[Input error: unexpected parameter 'num_classes'. Please report this problem.
09:54:38     ];
09:54:38         at __randomizedtesting.SeedInfo.seed([CB7F69BCEE4D2819:59125AEE162B239C]:0)
09:54:38         at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.serverError(ExceptionsHelper.java:55)
09:54:38         at org.elasticsearch.xpack.ml.dataframe.process.MemoryUsageEstimationProcessManager.runJob(MemoryUsageEstimationProcessManager.java:112)
09:54:38         at org.elasticsearch.xpack.ml.dataframe.process.MemoryUsageEstimationProcessManager.lambda$runJobAsync$0(MemoryUsageEstimationProcessManager.java:48)
09:54:38         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:693)
09:54:38         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
09:54:38         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
09:54:38         at java.lang.Thread.run(Thread.java:748)
09:54:38 
09:54:38         Caused by:
09:54:38         ElasticsearchException[Input error: unexpected parameter 'num_classes'. Please report this problem.
09:54:38         ]
09:54:38             at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.serverError(ExceptionsHelper.java:51)
09:54:38             at org.elasticsearch.xpack.ml.process.AbstractNativeProcess.close(AbstractNativeProcess.java:189)
09:54:38             at org.elasticsearch.xpack.ml.dataframe.process.MemoryUsageEstimationProcessManager.runJob(MemoryUsageEstimationProcessManager.java:105)
09:54:38             ... 5 more
```

**Comment by droberts195** [comment]
It’s because the latest C++ code is out of sync with the old Java code on that PR. I just updated the PR branch with latest master so it should be compatible now.

**Comment by droberts195** [comment]
The PR CI for #52382 is green after updating the branch.  I am pretty sure this was just a Java/C++ inconsistency issue that is now resolved.
