### ISSUE TITLE
[CI] TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithDeletion failures 

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#53718]
example: https://gradle-enterprise.elastic.co/s/52jb6s7kkr7ry

```
org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT > testHistoryIsWrittenWithDeletion FAILED
    java.lang.AssertionError: 
    Expected: a value equal to or greater than <1>
         but: <0> was less than <1>
        at __randomizedtesting.SeedInfo.seed([1B4D013544C0161A:C907958E0E5F69B4]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.assertHistoryIsPresent(TimeSeriesLifecycleActionsIT.java:1636)
        at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.lambda$testHistoryIsWrittenWithDeletion$109(TimeSeriesLifecycleActionsIT.java:1433)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:906)
        at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithDeletion(TimeSeriesLifecycleActionsIT.java:1432)
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:qa:multi-node:integTestRunner' --tests "org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithDeletion" -Dtests.seed=1B4D013544C0161A -Dtests.security.manager=true -Dtests.locale=en -Dtests.timezone=Africa/Conakry -Dcompiler.java=13
```

This [has been failing since March 4th](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testHistoryIsWrittenWithDeletion),sort:!(time,desc))) in master and 7.x  and this seems to correspond to when #53039 was merged so I'll assign @probakowski and mute this in master and 7.x

**Comment by andreidan** [comment]
Closing this as it has been fixed and un-muted since https://github.com/elastic/elasticsearch/pull/64521
