### ISSUE TITLE
[CI] release-tests CI fails with es.datastreams_feature_flag_registered is only supported in non-snapshot builds

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#54005]
`release-tests` builds are currently failing because data streams functionality is not being excluded.

An example is https://gradle-enterprise.elastic.co/s/yg4gygpycxpas, which failed with this error:

```
» fatal error in thread [main], exiting	
	»  java.lang.ExceptionInInitializerError	
	»  	at org.elasticsearch.node.Node.<init>(Node.java:480)	
	»  	at org.elasticsearch.node.Node.<init>(Node.java:261)	
	»  	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227)	
	»  	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227)	
	»  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393)	
	»  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)	
	»  	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)	
	»  	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)	
	»  	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)	
	»  	at org.elasticsearch.cli.Command.main(Command.java:90)	
	»  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)	
	»  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)	
	»  Caused by: java.lang.IllegalArgumentException: es.datastreams_feature_flag_registered is only supported in non-snapshot builds	
	»  	at org.elasticsearch.action.ActionModule.<clinit>(ActionModule.java:402)	
	»  	... 12 more	
```

The same thing happened with EQL when it was first added (see #51541), so the PRs linked to that issue must provide an example of how to fix it.

**Comment by danhermann** [comment]
We have https://github.com/elastic/elasticsearch/pull/54000 out to address that.
