### ISSUE TITLE
[CI] BlobStoreIncrementalityIT.testIncrementalBehaviorOnPrimaryFailover failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#54034]
This looks to be a recently added test. It's failed twice now in `7.x`, not sure if whatever the problem is also exists in `master`. The below failure reproduced locally for me:

```
org.elasticsearch.snapshots.BlobStoreIncrementalityIT > testIncrementalBehaviorOnPrimaryFailover FAILED
    java.lang.AssertionError: 
    Expected: is <4>
         but: was <0>
        at __randomizedtesting.SeedInfo.seed([33E415A7F24AEA0F:F57F696CCE8F8F00]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.snapshots.BlobStoreIncrementalityIT.assertTwoIdenticalShardSnapshots(BlobStoreIncrementalityIT.java:199)
        at org.elasticsearch.snapshots.BlobStoreIncrementalityIT.testIncrementalBehaviorOnPrimaryFailover(BlobStoreIncrementalityIT.java:127)
REPRODUCE WITH: ./gradlew ':server:integTest' --tests "org.elasticsearch.snapshots.BlobStoreIncrementalityIT.testIncrementalBehaviorOnPrimaryFailover" -Dtests.seed=33E415A7F24AEA0F -Dtests.security.manager=true -Dtests.locale=es-HN -Dtests.timezone=Pacific/Norfolk -Dcompiler.java=13
```

**Comment by mark-vieira** [comment]
@original-brownbear since you authored this test do you mind taking a look?

**Comment by mark-vieira** [comment]
I've muted this in `7.x` with be1b34c3f8fb19b40c11b483657eb1bb34f96358

**Comment by jasontedor** [comment]
I muted this in master with b56b9fb67409859acb609cfd4e6158b57d43c1a4.

**Comment by mark-vieira** [comment]
This just failed again in `master`.

https://gradle-enterprise.elastic.co/s/ah4djmwvojm3c/tests/kyv2y2z3r4v7k-ugkfmsdgmdana
