### ISSUE TITLE
[CI] Watcher SingleNodeTests testThatLoadingWithNonExistingIndexWorks fails

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#54096]
The test SingleNodeTests.testThatLoadingWithNonExistingIndexWorks failed today on 7.x:

```
Shard [.watcher-history-11-2020.03.24][0] is still locked after 5 sec waiting
java.lang.AssertionError
: 
Shard [.watcher-history-11-2020.03.24][0] is still locked after 5 sec waiting
Close stacktrace
at __randomizedtesting.SeedInfo.seed([69C5071A8D40C52E:BB158804836EBAD2]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2483)
at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:594)
at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2116)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
at java.lang.Thread.run(Thread.java:748)
```

It didn't reproduce locally using:
```
./gradlew ':x-pack:plugin:watcher:test' --tests "org.elasticsearch.xpack.watcher.test.integration.SingleNodeTests.testThatLoadingWithNonExistingIndexWorks" -Dtests.seed=69C5071A8D40C52E -Dtests.security.manager=true -Dtests.locale=fr-BE -Dtests.timezone=Turkey -Dcompiler.java=13
```

Gradle build scan: https://gradle-enterprise.elastic.co/s/smzp2a6s6n6so

It seems similar to #36782 which has been [closed recently](https://github.com/elastic/elasticsearch/issues/36782#issuecomment-595152624).

**Comment by dimitris-athanasiou** [comment]
Another failure:

[Jenkins](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_RUNTIME_JAVA=java11,nodes=general-purpose/628/console)
[Build Scan](https://gradle-enterprise.elastic.co/s/w4zoiajbqfzo6)

**Comment by nik9000** [comment]
Another! https://gradle-enterprise.elastic.co/s/slrpjishcwryy

**Comment by valeriy42** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/qr3xvlebrzuee

**Comment by pugnascotia** [comment]
@jakelandis this test just failed again - https://gradle-enterprise.elastic.co/s/he4uj4mhdi226

**Comment by javanna** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/vhcwpt6dod232/console-log?task=:x-pack:plugin:watcher:internalClusterTest

**Comment by cbuescher** [comment]
This failed again twice on 8.0 today:
https://gradle-enterprise.elastic.co/s/lldjmbfpkus36
https://gradle-enterprise.elastic.co/s/lb6dq3vuj3in2

**Comment by cbuescher** [comment]
And another one: https://gradle-enterprise.elastic.co/s/umzmo6mgwynia

**Comment by cbuescher** [comment]
Looking at the more recent failures, this is the error message I see which is slightly than the original one on this issue:
```
org.elasticsearch.xpack.watcher.test.integration.SingleNodeTests > testThatLoadingWithNonExistingIndexWorks FAILED
    Failed to execute phase [query], all shards failed; shardFailures {[R7OYMUjvRJmRduKXdBxxoA][.ds-.watcher-history-14-2022.01.12-000001][0]: [.ds-.watcher-history-14-2022.01.12-000001/7zqsGsXDRQelZoJbDSKBxQ][[.ds-.watcher-history-14-2022.01.12-000001][0]] org.elasticsearch.action.NoShardAvailableActionException: [node_s0][127.0.0.1:51488][indices:data/read/search[phase/query]]
    	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:544)
    	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:491)
    	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:343)
    	at org.elasticsearch.action.ActionListener$Delegating.onFailure(ActionListener.java:66)
    	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:48)
    	at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:651)
    	at org.elasticsearch.transport.TransportService$4.handleException(TransportService.java:719)
    	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1343)
    	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1452)
    	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1426)
    	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:50)
    	at org.elasticsearch.transport.TransportChannel.sendErrorResponse(TransportChannel.java:45)
    	at org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:41)
    	at org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:77)
    	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:28)
    	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
    	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:775)
    	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    	at java.base/java.lang.Thread.run(Thread.java:833)
    }
        at __randomizedtesting.SeedInfo.seed([D09F7AA2F863B005:24FF5BCF64DCFF9]:0)
        at app//org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:725)
        at app//org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:412)
        at app//org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:757)
        at app//org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:509)
        at app//org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:343)
        at app//org.elasticsearch.action.ActionListener$Delegating.onFailure(ActionListener.java:66)
        at app//org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:48)
        at app//org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:651)
        at app//org.elasticsearch.transport.TransportService$4.handleException(TransportService.java:719)
        at app//org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1343)
        at app//org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1452)
        at app//org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1426)
        at app//org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:50)
        at app//org.elasticsearch.transport.TransportChannel.sendErrorResponse(TransportChannel.java:45)
        at app//org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:41)
        at app//org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:77)
        at app//org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:28)
        at app//org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
        at app//org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:775)
        at app//org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.1/java.lang.Thread.run(Thread.java:833)

        Caused by:
        [.ds-.watcher-history-14-2022.01.12-000001/7zqsGsXDRQelZoJbDSKBxQ][[.ds-.watcher-history-14-2022.01.12-000001][0]] org.elasticsearch.action.NoShardAvailableActionException: [node_s0][127.0.0.1:51488][indices:data/read/search[phase/query]]
            at app//org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:544)
            at app//org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:491)
            ... 19 more
```

**Comment by valeriy42** [comment]
Another failure today on 8.1 https://gradle-enterprise.elastic.co/s/bs4xvcgps5xi2

**Comment by pugnascotia** [comment]
This test had failed 5 times in the last 7 days, all with `All shards failed`.

https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/London&tests.container=org.elasticsearch.xpack.watcher.test.integration.SingleNodeTests&tests.sortField=FAILED&tests.test=testThatLoadingWithNonExistingIndexWorks&tests.unstableOnly=true

**Comment by jtibshirani** [comment]
This test just failed again: https://gradle-enterprise.elastic.co/s/73li72g2op6m6/. I muted it in master, 8.1, 8.0, and 7.17.
