### ISSUE TITLE
[CI] TimeSeriesLifecycleActionsIT testHistoryIsWrittenWithSuccess

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#54093]
[Brand new failure](https://gradle-enterprise.elastic.co/scans/tests?failures.failureClassification=non_verification&list.offset=0&list.size=50&list.sortColumn=startTime&list.sortOrder=desc&search.buildOutcome=failure&search.buildToolType=gradle&search.buildToolType=maven&search.startTimeMax=1585060779917&search.startTimeMin=1584974379916&search.tags=CI&search.tags=not:pull-request&tests.container=org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT&tests.sortField=FAILED&tests.test=testHistoryIsWrittenWithSuccess&tests.unstableOnly=true&trends.section=overview&trends.timeResolution=day&viewer.tzOffset=120) in the TimeSeriesLifecycleActionsIT test suite.
```
./gradlew ':x-pack:plugin:ilm:qa:multi-node:integTestRunner' --tests "org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithSuccess" -Dtests.seed=8A26D59EE28A4F02 -Dtests.security.manager=true -Dtests.locale=es-CO -Dtests.timezone=Africa/Kampala -Dcompiler.java=13	
  2> java.lang.AssertionError: 	
    Expected: a value equal to or greater than <1>	
         but: <0> was less than <1>	
        at __randomizedtesting.SeedInfo.seed([8A26D59EE28A4F02:C92BF964465B5BD7]:0)	
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)	
        at org.junit.Assert.assertThat(Assert.java:956)	
        at org.junit.Assert.assertThat(Assert.java:923)	
        at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.assertHistoryIsPresent(TimeSeriesLifecycleActionsIT.java:1641)	
        at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.assertHistoryIsPresent(TimeSeriesLifecycleActionsIT.java:1564)	
        at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.lambda$testHistoryIsWrittenWithSuccess$94(TimeSeriesLifecycleActionsIT.java:1396)	
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:917)	
        at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithSuccess(TimeSeriesLifecycleActionsIT.java:1396)
```

```
ERROR][o.e.x.i.h.ILMHistoryStore] [integTest-3] failed to index 2 items into ILM history index	
»  org.elasticsearch.ElasticsearchException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: ILM history alias [ilm-history-2] already exists as concrete index	
»  	at org.elasticsearch.xpack.ilm.history.ILMHistoryStore$1.beforeBulk(ILMHistoryStore.java:96) [x-pack-ilm-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]	
»  	at org.elasticsearch.action.bulk.BulkRequestHandler.execute(BulkRequestHandler.java:58) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]	
»  	at org.elasticsearch.action.bulk.BulkProcessor.execute(BulkProcessor.java:455) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]	
»  	at org.elasticsearch.action.bulk.BulkProcessor.execute(BulkProcessor.java:464) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]	
»  	at org.elasticsearch.action.bulk.BulkProcessor.access$400(BulkProcessor.java:54) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]	
»  	at org.elasticsearch.action.bulk.BulkProcessor$Flush.run(BulkProcessor.java:504) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]	
»  	at org.elasticsearch.threadpool.Scheduler$ReschedulingRunnable.doRun(Scheduler.java:223) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]	
»  	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT]	
»  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_241]	
»  	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_241]	
»  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_241]	
»  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_241]	
»  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]	
»  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]	
»  	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]	
»  Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: ILM history alias [ilm-history-2] already exists as concrete index	
»  	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_241]	
»  	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928) ~[?:1.8.0_241]	
»  	at org.elasticsearch.xpack.ilm.history.ILMHistoryStore$1.beforeBulk(ILMHistoryStore.java:87) ~[?:?]	
»  	... 14 more	
»  Caused by: java.lang.IllegalStateException: ILM history alias [ilm-history-2] already exists as concrete index	
»  	at org.elasticsearch.xpack.ilm.history.ILMHistoryStore.ensureHistoryIndex(ILMHistoryStore.java:223) ~[?:?]	
»  	at org.elasticsearch.xpack.ilm.history.ILMHistoryStore$1.beforeBulk(ILMHistoryStore.java:82) ~[?:?]	
»  	... 14 more	
»   ↑ repeated 3 times ↑
```

I'll abstain from muting for now.

**Comment by DaveCTurner** [comment]
Another failure in https://gradle-enterprise.elastic.co/s/vfvbe3j32c6ys

**Comment by DaveCTurner** [comment]
Muted in `master`, `7.x` and `7.7`: 06ab3b5 ad3c96e 8a654b0

**Comment by andreidan** [comment]
This will be fixed once `ilm-history` is converted to a data stream.

**Comment by danielmitterdorfer** [comment]
After the test has been unmuted by @probakowski it is failing now with ([build scan](https://gradle-enterprise.elastic.co/s/sp3w6jimsmvak)):

```
07:12:05 org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT > testHistoryIsWrittenWithSuccess FAILED
07:12:05     java.lang.AssertionError: 
07:12:05     Expected: a value equal to or greater than <1>
07:12:05          but: <0> was less than <1>
07:12:05         at __randomizedtesting.SeedInfo.seed([AE2751318A600BAD:ED2A7DCB2EB11F78]:0)
07:12:05         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
07:12:05         at org.junit.Assert.assertThat(Assert.java:956)
07:12:05         at org.junit.Assert.assertThat(Assert.java:923)
07:12:05         at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.assertHistoryIsPresent(TimeSeriesLifecycleActionsIT.java:1550)
07:12:05         at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.assertHistoryIsPresent(TimeSeriesLifecycleActionsIT.java:1472)
07:12:05         at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.lambda$testHistoryIsWrittenWithSuccess$86(TimeSeriesLifecycleActionsIT.java:1237)
07:12:05         at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:950)
07:12:05         at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithSuccess(TimeSeriesLifecycleActionsIT.java:1237)
```

The reproduction line:

```

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testHistoryIsWrittenWithSuccess" \
  -Dtests.seed=AE2751318A600BAD \
  -Dtests.security.manager=true \
  -Dtests.locale=ja \
  -Dtests.timezone=Indian/Kerguelen \
  -Druntime.java=15 \
  -Dtests.fips.enabled=true
```

does not reproduce locally. I'll mute the test again.

**Comment by andreidan** [comment]
Closing this issue as `ilm-history` is now a data stream.
