### ISSUE TITLE
[CI] DockerTests test071BindMountCustomPathWithDifferentUID

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#54101]
This test started failing [since 4 days ago](https://gradle-enterprise.elastic.co/scans/tests?failures.failureClassification=non_verification&list.offset=0&list.size=50&list.sortColumn=startTime&list.sortOrder=desc&search.buildOutcome=failure&search.buildToolType=gradle&search.buildToolType=maven&search.startTimeMax=1585062168594&search.startTimeMin=1584457368594&search.tags=CI&search.tags=not:pull-request&tests.container=org.elasticsearch.packaging.test.DockerTests&tests.sortField=FAILED&tests.test=test071BindMountCustomPathWithDifferentUID&tests.unstableOnly=true&trends.section=overview&trends.timeResolution=day&viewer.tzOffset=120).
```
org.elasticsearch.packaging.test.DockerTests > test071BindMountCustomPathWithDifferentUID FAILED	
    java.lang.RuntimeException: java.io.IOException: could not remove the following files (in the order of attempts):	
       /tmp/DockerTests8885270542177492928/esDataDir/_state: java.nio.file.DirectoryNotEmptyException: /tmp/DockerTests8885270542177492928/esDataDir/_state	
       /tmp/DockerTests8885270542177492928/esDataDir: java.nio.file.DirectoryNotEmptyException: /tmp/DockerTests8885270542177492928/esDataDir	
       /tmp/DockerTests8885270542177492928: java.nio.file.DirectoryNotEmptyException: /tmp/DockerTests8885270542177492928	
        at __randomizedtesting.SeedInfo.seed([FF6827247D170879:B22468E3E7A98F41]:0)	
        at org.elasticsearch.packaging.util.FileUtils.rm(FileUtils.java:85)	
        at org.elasticsearch.packaging.test.DockerTests.teardownTest(DockerTests.java:88)	
	
        Caused by:	
        java.io.IOException: could not remove the following files (in the order of attempts):	
           /tmp/DockerTests8885270542177492928/esDataDir/_state: java.nio.file.DirectoryNotEmptyException: /tmp/DockerTests8885270542177492928/esDataDir/_state	
           /tmp/DockerTests8885270542177492928/esDataDir: java.nio.file.DirectoryNotEmptyException: /tmp/DockerTests8885270542177492928/esDataDir	
           /tmp/DockerTests8885270542177492928: java.nio.file.DirectoryNotEmptyException: /tmp/DockerTests8885270542177492928	
            at org.elasticsearch.core.internal.io.IOUtils.rm(IOUtils.java:197)	
            at org.elasticsearch.packaging.util.FileUtils.rm(FileUtils.java:83)	
            ... 1 more
```
Latest build stat https://gradle-enterprise.elastic.co/s/7lgqn5d72r7ns .

**Comment by rjernst** [comment]
Looks like we need to ensure ES is shutdown (container is removed) after the last test.

**Comment by williamrandolph** [comment]
Looks like we missed the 7.7 branch — this is on `7.x` and `7.6`. Opening a quick backport PR: https://github.com/elastic/elasticsearch/pull/54646
