### ISSUE TITLE
[CI] StratifiedCrossValidationSplitterTests.testProcess_SelectsTrainingRowsUniformly failed reproducibly

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#54122]
This test failed in one of my pull request (targeting `master`) checks and reproduced locally for me. Looks to be a newly added test so it's worth taking a look.

```
org.elasticsearch.xpack.ml.dataframe.process.crossvalidation.StratifiedCrossValidationSplitterTests > testProcess_SelectsTrainingRowsUniformly FAILED
    java.lang.AssertionError: 
    Expected: is a numeric value within <0.1> of <0.5>
         but: <0.396> differed by <0.003999999999999976> more than delta <0.1>
        at __randomizedtesting.SeedInfo.seed([D17047A4AE72588C:B8BF48790CE72C6A]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ml.dataframe.process.crossvalidation.StratifiedCrossValidationSplitterTests.testProcess_SelectsTrainingRowsUniformly(StratifiedCrossValidationSplitterTests.java:224)
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:test' --tests "org.elasticsearch.xpack.ml.dataframe.process.crossvalidation.StratifiedCrossValidationSplitterTests.testProcess_SelectsTrainingRowsUniformly" -Dtests.seed=D17047A4AE72588C -Dtests.security.manager=true -Dtests.locale=de-LU -Dtests.timezone=America/Sitka -Dcompiler.java=13
```

https://gradle-enterprise.elastic.co/s/6l4c3nq33thai/tests/7bifs6bt3pims-zc4k2r23rl7bq

**Comment by benwtrent** [comment]
I have also had `testProcess_GivenRowsWithDependentVariableValue_AndTrainingPercentIsRandom` fail due to fencepost errors. Being off by one in the gte/lte checks on 182/183

**Comment by andreidan** [comment]
Just had another occurrence of this (I think) on a PR off the latest master https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/966/

```
Expected: is a numeric value within <0.12> of <0.5>
     but: <0.626> differed by <0.006000000000000005> more than delta <0.12>
```

Build scan available here https://gradle-enterprise.elastic.co/s/pvqvjqjibtvdm
