### ISSUE TITLE
WatcherRestartIT failing on 7.x after version bump to 7.8.0

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#54220]
WatcherRestartIT failing on 7.x after version bump to 7.8.0.

```
    java.lang.AssertionError: 
    Expected: is <200>
         but: was <404>
        at __randomizedtesting.SeedInfo.seed([180735F276808A5C:8D5F3B7D3D9C5305]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.upgrades.WatcherRestartIT.validateHistoryTemplate(WatcherRestartIT.java:40)
        at org.elasticsearch.upgrades.WatcherRestartIT.testWatcherRestart(WatcherRestartIT.java:29)
```

**Comment by gwbrown** [comment]
This could be related to some changes we made to template management in 7.7 (see https://github.com/elastic/elasticsearch/pull/52962, https://github.com/elastic/elasticsearch/pull/51456). I'll look into this when I have time, but if someone else beats me to it and it is related to one of the above, please ping me.

**Comment by gwbrown** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/54237, closing.
