### ISSUE TITLE
cant start rest client to work

### ISSUE THREAD

**Issue by nicktoker** [elastic/elasticsearch#54263]
<!--
start my app on linux
elastic rest client 7.3.2

try to create search request

Caused by: java.lang.NullPointerException
at org.elasticsearch.Build.<clinit>(Build.java:145)

**Comment by nicktoker** [comment]
Caused by: java.lang.NullPointerException
at org.elasticsearch.Build.<clinit>(Build.java:48)

**Comment by nicktoker** [comment]
Caused by: java.lang.NullPointerException
at org.elasticsearch.Build.<clinit>(Build.java:145)

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
