### ISSUE TITLE
[CI] Test Failure in org.elasticsearch.script.ScriptServiceTests.testContextCacheStats

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#54324]
This just failed on CI, can't reproduce this locally though and haven't seen it before so not muting yet.

```
org.elasticsearch.script.ScriptServiceTests > testContextCacheStats FAILED
    junit.framework.AssertionFailedError: Expected exception GeneralScriptException but no exception was thrown
        at __randomizedtesting.SeedInfo.seed([4CB9D6CB3156F6BC:F21F3A8B0A50B9A]:0)
        at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2743)
        at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2733)
        at org.elasticsearch.script.ScriptServiceTests.testContextCacheStats(ScriptServiceTests.java:287)
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.script.ScriptServiceTests.testContextCacheStats" -Dtests.seed=4CB9D6CB3156F6BC -Dtests.security.manager=true -Dtests.locale=sr-Latn -Dtests.timezone=Africa/Windhoek -Dcompiler.java=13
```

**Comment by stu-elastic** [comment]
Taking a look, I just added this yesterday.

**Comment by stu-elastic** [comment]
[Muted](https://github.com/elastic/elasticsearch/pull/54352) for now.

**Comment by stu-elastic** [comment]
Issue was randomly selecting two contexts that were the same, so rate limit was being overridden.
