### ISSUE TITLE
Failed transport handshake between 6.8 and 7.6 nodes may throw a fatal AssertionError

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#54337]
Nodes send their transport handshakes with the version set to `Version.CURRENT.minimumCompatibilityVersion()`. For 6.8 nodes this is 5.6.0. When a 7.6 node receives a transport message, including a handshake, it responds using the same transport version. This means that a 7.6 node responding to a transport handshake claims to be sending a 5.6.0-compatible message. However, 7.6 nodes do not really know how to speak the 5.6.0 transport protocol. This mostly works since the format of a handshake response did not change between 5.6 and 6.0. However, the format of _error_ responses has changed, so an error response is not correctly deserialised. Worse, the incorrect deserialisation trips an assertion error that causes the 6.8 node to shut down:

```
[WARN ][org.elasticsearch.transport.TcpTransport] [REDACTED] exception caught on transport layer [Netty4TcpChannel{localAddress=/REDACTED, remoteAddress=/REDACTED}], clos
ing connection
java.lang.Exception: java.lang.AssertionError: illegal transport ID from node of version: 5.6.0 got: 1196 expected: 1
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.exceptionCaught(Netty4MessageChannelHandler.java:66) [transport-netty4-client-6.8.6.jar:6.8.6]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:856) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:364) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1436) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1203) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247) [netty-handler-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [netty-codec-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [netty-common-4.1.32.Final.jar:4.1.32.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.AssertionError: illegal transport ID from node of version: 5.6.0 got: 1196 expected: 1
        at org.elasticsearch.common.transport.TransportAddress.<init>(TransportAddress.java:86) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.transport.TransportAddress.<init>(TransportAddress.java:75) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:777) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.ActionTransportException.<init>(ActionTransportException.java:41) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.RemoteTransportException.<init>(RemoteTransportException.java:45) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.ElasticsearchException.readException(ElasticsearchException.java:306) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.io.stream.StreamInput.readException(StreamInput.java:799) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.TcpTransport.handlerResponseError(TcpTransport.java:997) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:950) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:763) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:53) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        ... 31 more
[ERROR][org.elasticsearch.bootstrap.ElasticsearchUncaughtExceptionHandler] [REDACTED] fatal error in thread [...], exiting
java.lang.AssertionError: illegal transport ID from node of version: 5.6.0 got: 1196 expected: 1
        at org.elasticsearch.common.transport.TransportAddress.<init>(TransportAddress.java:86) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.transport.TransportAddress.<init>(TransportAddress.java:75) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:777) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.ActionTransportException.<init>(ActionTransportException.java:41) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.RemoteTransportException.<init>(RemoteTransportException.java:45) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.ElasticsearchException.readException(ElasticsearchException.java:306) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.io.stream.StreamInput.readException(StreamInput.java:799) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.TcpTransport.handlerResponseError(TcpTransport.java:997) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:950) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:763) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:53) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1436) ~[?:?]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1203) ~[?:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1247) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[?:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Comment by baileygm** [comment]
I just came across this exact problem when trying to upgrade a 9-node cluster from 6.8.4 to 7.6.2

> fatal error in thread [Thread-5616], exiting java.lang.AssertionError: illegal transport ID from node of version: 5.6.0 got

Is there a work around for this problem whilst waiting for a proper fix ?

**Comment by DaveCTurner** [comment]
@baileygm do you see this happening consistently or was it a one-off? I think the only workaround today is to carry on with the upgrade. In particular if the 6.8 node has shut down then you can upgrade it to 7.6 and restart it.

**Comment by baileygm** [comment]
@DaveCTurner I upgraded one data node and 3 other nodes threw errors and disconnected
I shut down the data node, wiped it of data and rolled it back to version 6.8.4 and its just reallocating shards now as there's a fair amount of data.

I was wondering if an upgrade to an earlier version of 7.x before then upgrading again to 7.6.2 would avoid the issue.  Otherwise I am going to try and reproduce the problem offline.

**Comment by DaveCTurner** [comment]
Unfortunately I think everything in the OP about 7.6 nodes is also true of 7.0 nodes so it doesn't help to do this upgrade in multiple steps.
