### ISSUE TITLE
SnapshotResiliencyTests.testSnapshotWithNodeDisconnects test failure

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#54459]
Test failure in 7.6 branch. 

Build: https://gradle-enterprise.elastic.co/s/5qjrfa3ztjwis

```
org.elasticsearch.snapshots.SnapshotResiliencyTests > testSnapshotWithNodeDisconnects FAILED
    java.lang.AssertionError: java.lang.AssertionError: expected:<0> but was:<1>
        at __randomizedtesting.SeedInfo.seed([2023C78D75EE4499:2EEC68456F287F59]:0)
        at org.elasticsearch.repositories.blobstore.BlobStoreTestUtil.assertConsistency(BlobStoreTestUtil.java:147)
        at org.elasticsearch.snapshots.SnapshotResiliencyTests.verifyReposThenStopServices(SnapshotResiliencyTests.java:262)

        Caused by:
        java.lang.AssertionError: expected:<0> but was:<1>
            at org.junit.Assert.fail(Assert.java:88)
            at org.junit.Assert.failNotEquals(Assert.java:834)
            at org.junit.Assert.assertEquals(Assert.java:645)
            at org.junit.Assert.assertEquals(Assert.java:631)
            at org.elasticsearch.repositories.blobstore.BlobStoreTestUtil.assertIndexGenerations(BlobStoreTestUtil.java:155)
            at org.elasticsearch.repositories.blobstore.BlobStoreTestUtil.lambda$assertConsistency$0(BlobStoreTestUtil.java:130)
            at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:58)
            at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73)
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
            at org.elasticsearch.repositories.blobstore.BlobStoreTestUtil.assertConsistency(BlobStoreTestUtil.java:121)
            ... 1 more
```

Reproduce line:
```
./gradlew ':server:test' --tests "org.elasticsearch.snapshots.SnapshotResiliencyTests.testSnapshotWithNodeDisconnects" -Dtests.seed=2023C78D75EE4499 -Dtests.security.manager=true -Dtests.locale=fr-FR -Dtests.timezone=America/Punta_Arenas -Dcompiler.java=13
```

Reproduced reliably on the 7.6 branch.

**Comment by original-brownbear** [comment]
This is just a missing back-port of a test fix from a while back. I'll deal with this tomorrow, it's a test only issue :)

**Comment by original-brownbear** [comment]
https://github.com/elastic/elasticsearch/pull/54480 will fix this, closing here :)
