### ISSUE TITLE
[CI] JvmGcMonitorServiceSettingsTests.testNegativeSetting fails on CI

### ISSUE THREAD

**Issue by csoulios** [elastic/elasticsearch#54485]
Test JvmGcMonitorServiceSettingsTests.testNegativeSetting fails on CI and local master

To reproduce the failure: 

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.monitor.jvm.JvmGcMonitorServiceSettingsTests.testNegativeSetting" -Dtests.seed=879DA0AC9CDA9790 -Dtests.security.manager=true -Dtests.locale=ar -Dtests.timezone=Europe/Chisinau -Dcompiler.java=13

org.elasticsearch.monitor.jvm.JvmGcMonitorServiceSettingsTests > testNegativeSetting FAILED
    java.lang.AssertionError:
    Expected: "failed to parse setting [monitor.jvm.gc.collector.qmuVR.warn] with value [-1nanos] as a time value"
         but: was "missing gc_threshold for [monitor.jvm.gc.collector.qmuVR.info]"
        at __randomizedtesting.SeedInfo.seed([879DA0AC9CDA9790:1D7718365E5EA59A]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.monitor.jvm.JvmGcMonitorServiceSettingsTests.lambda$testNegativeSetting$5(JvmGcMonitorServiceSettingsTests.java:69)
        at org.elasticsearch.monitor.jvm.JvmGcMonitorServiceSettingsTests.execute(JvmGcMonitorServiceSettingsTests.java:165)
        at org.elasticsearch.monitor.jvm.JvmGcMonitorServiceSettingsTests.testNegativeSetting(JvmGcMonitorServiceSettingsTests.java:67)
```

**Comment by ywangd** [comment]
Failed again on 6.8 and **can be reproduced locally**

```
./gradlew ':server:unitTest' \
  -Dtests.seed=B1135B38EB239BB8 \
  -Dtests.class=org.elasticsearch.monitor.jvm.JvmGcMonitorServiceSettingsTests \
  -Dtests.method="testNegativeSetting" \
  -Dtests.security.manager=true \
  -Dtests.locale=da \
  -Dtests.timezone=America/Boa_Vista \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

Build scan:
https://gradle-enterprise.elastic.co/s/obd4misgqhycs

Sample error message:
```
java.lang.AssertionError: 
Expected: "failed to parse setting [monitor.jvm.gc.collector.pZKvo.warn] with value [-1nanos] as a time value"
     but: was "missing gc_threshold for [monitor.jvm.gc.collector.pZKvo.info]"
	at __randomizedtesting.SeedInfo.seed([B1135B38EB239BB8:2BF9E3A229A7A9B2]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.monitor.jvm.JvmGcMonitorServiceSettingsTests.lambda$testNegativeSetting$5(JvmGcMonitorServiceSettingsTests.java:69)
	at org.elasticsearch.monitor.jvm.JvmGcMonitorServiceSettingsTests.execute(JvmGcMonitorServiceSettingsTests.java:165)
	at org.elasticsearch.monitor.jvm.JvmGcMonitorServiceSettingsTests.testNegativeSetting(JvmGcMonitorServiceSettingsTests.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
