### ISSUE TITLE
org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.testReduceRandom fails

### ISSUE THREAD

**Issue by hub-cap** [elastic/elasticsearch#54540]
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.testReduceRandom" -Dtests.seed=5D0B922735110573 -Dtests.security.manager=true -Dtests.locale=vi -Dtests.timezone=ACT -Dcompiler.java=13
```

```
Suite: Test class org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests
  1> [2020-04-01T07:09:37,652][INFO ][o.e.s.a.b.h.InternalAutoDateHistogramTests] [testReduceRandom] before test
  1> [2020-04-01T07:09:37,773][INFO ][o.e.s.a.b.h.InternalAutoDateHistogramTests] [testReduceRandom] after test
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.testReduceRandom" -Dtests.seed=5D0B922735110573 -Dtests.security.manager=true -Dtests.locale=vi -Dtests.timezone=ACT -Dcompiler.java=13
  2> java.lang.AssertionError: expected:<{1583020800000=2193, 1585612800000=1561}> but was:<{1583020800000=2193, 1585699200000=1561}>
        at __randomizedtesting.SeedInfo.seed([5D0B922735110573:9D363E36134C9C25]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.assertReduced(InternalAutoDateHistogramTests.java:203)
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.assertReduced(InternalAutoDateHistogramTests.java:49)
        at org.elasticsearch.test.InternalAggregationTestCase.testReduceRandom(InternalAggregationTestCase.java:326)
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.testReduceRandom(InternalAutoDateHistogramTests.java:112)
  2> NOTE: leaving temporary files on disk at: /home/baz/src/elastic/elasticsearch/server/build/testrun/test/temp/org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests_5D0B922735110573-001
  2> NOTE: test params are: codec=Asserting(Lucene84), sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@91aab33), locale=vi, timezone=ACT
  2> NOTE: Linux 5.0.0-32-generic amd64/AdoptOpenJDK 14 (64-bit)/cpus=12,threads=1,free=487884488,total=536870912
  2> NOTE: All tests run in this JVM: [InternalAutoDateHistogramTests]

```

**Comment by ywangd** [comment]
Two more failures just now:
* https://gradle-enterprise.elastic.co/s/l5k2n2rq7sz2k
* https://gradle-enterprise.elastic.co/s/wsp272zisq7ie

Can be reproduced locally with
```
./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.testReduceRandom" \
  -Dtests.seed=7B89245A80E80B72 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-US \
  -Dtests.timezone=Australia/Broken_Hill \
  -Dcompiler.java=13
```

Sample failure message:
```
:server:test » org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests » testReduceRandom (0.082s)
expected:<{1583020800000=2179, 1585612800000=45}> but was:<{1583020800000=2179, 1585699200000=45}>
java.lang.AssertionError: expected:<{1583020800000=2179, 1585612800000=45}> but was:<{1583020800000=2179, 1585699200000=45}>
```

**Comment by nik9000** [comment]
Baz is muting this and I'll look in the morning. Oddly, I tracked this
particular seed failing back to December.
