### ISSUE TITLE
fail engine:lucene commit fail due to max_seq_no decode error

### ISSUE THREAD

**Issue by Hailei** [elastic/elasticsearch#54699]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 7.5.1

**Plugins installed**: []

**JVM version** (`java -version`):openjdk version "13.0.1" 2019-10-15

**OS version** (`uname -a` if on a Unix-like system):Linux n19-062-134 4.9.0-0.bpo.6-amd64 #1 SMP Debian 4.9.88-1+deb9u1~bpo8+1 (2018-05-13) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
 lucene commit failed  when engine flush index.because of read last commit max_seq_no. encoded max_seq_no is 1481^@76,can't decode correctly
![es_max_seq_no](https://user-images.githubusercontent.com/1724869/78330240-17ae0680-75b6-11ea-833a-cda768581240.png)

 

**Steps to reproduce**:
can't reproduce 
Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

```
[2020-04-02T17:10:37,274][WARN ][o.e.i.e.Engine           ] [)] [_v2-2020.04.02][244] failed engine [lucene commit failed]
java.lang.NumberFormatException: For input string: "1476p644"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:68) ~[?:?]
        at java.lang.Long.parseLong(Long.java:699) ~[?:?]
        at java.lang.Long.parseLong(Long.java:824) ~[?:?]
        at org.elasticsearch.index.engine.CombinedDeletionPolicy.indexOfKeptCommits(CombinedDeletionPolicy.java:208) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.index.engine.CombinedDeletionPolicy.onCommit(CombinedDeletionPolicy.java:83) ~[elasticsearch-7.5.1.jar:7.5.1]
        at org.apache.lucene.index.IndexFileDeleter.checkpoint(IndexFileDeleter.java:524) ~[lucene-core-8.3.0.jar:8.3.0 2aa586909b911e66e1d8863aa89f173d69f86cd2 - ishan - 2019-10-25 23:10:03]
        at org.apache.lucene.index.IndexWriter.finishCommit(IndexWriter.java:3497) ~[lucene-core-8.3.0.jar:8.3.0 2aa586909b911e66e1d8863aa89f173d69f86cd2 - ishan - 2019-10-25 23:10:03]
        at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3453) ~[lucene-core-8.3.0.jar:8.3.0 2aa586909b911e66e1d8863aa89f173d69f86cd2 - ishan - 2019-10-25 23:10:03]
        at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3410) ~[lucene-core-8.3.0.jar:8.3.0 2aa586909b911e66e1d8863aa89f173d69f86cd2 - ishan - 2019-10-25 23:10:03]
        at org.elasticsearch.index.engine.InternalEngine.commitIndexWriter(InternalEngine.java:2446) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.index.engine.InternalEngine.flush(InternalEngine.java:1780) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.index.shard.IndexShard.flush(IndexShard.java:1092) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.index.shard.IndexShard$6.doRun(IndexShard.java:3138) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773) [elasticsearch-7.5.1.jar:7.5.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.5.1.jar:7.5.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
```

**Comment by ywelsch** [comment]
This is very odd. I can only explain this as a bit-flip that must have occurred before writing out the respective segment. Perhaps check your hardware? Any ideas, @jpountz?

**Comment by Hailei** [comment]
> This is very odd. I can only explain this as a bit-flip that must have occurred before writing out the respective segment. Perhaps check your hardware? Any ideas, @jpountz?

@ywelsch  thanks for your explain, I will check hardware with our sys team next Tuesday

**Comment by jpountz** [comment]
I have the same interpretation as Yannick. The `^H` character is for backspace, which is ascii character `8`, which is how the number 8 is encoded as a variable-length integer. So it expects a string of length 8, which is consistent with your other segments file which also has a maximum sequence number of length 8.

The `^@` character in the middle of the sequence number is definitely wrong. I'm leaning towards a hardware issue too, especially as `^@` is not a random byte, it's how `vim` represents the NULL byte. To me the most likely explanation is faulty RAM.

**Comment by Hailei** [comment]
> I have the same interpretation as Yannick. The `^H` character is for backspace, which is ascii character `8`, which is how the number 8 is encoded as a variable-length integer. So it expects a string of length 8, which is consistent with your other segments file which also has a maximum sequence number of length 8.
> 
> The `^@` character in the middle of the sequence number is definitely wrong. I'm leaning towards a hardware issue too, especially as `^@` is not a random byte, it's how `vim` represents the NULL byte. To me the most likely explanation is faulty RAM.

Thanks,I will close this issue
