### ISSUE TITLE
SamlServiceProviderDocumentTests.testXContentRoundTripWithAllFields fails

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#54733]
https://gradle-enterprise.elastic.co/s/orte4xd75yhpk/console-log?task=:x-pack:plugin:identity-provider:test

```
org.elasticsearch.xpack.idp.saml.sp.SamlServiceProviderDocumentTests > testStreamRoundTripWithAllFields FAILED
    java.lang.AssertionError: Error when comparing xContent.
                               acs: same [https://BPrYIu.NPgwWiZR/saml/acs]
                        attributes: 
                               email: same [urn:PsPJcI.aIkYn]
                                name: same [urn:BnQXP.moCyjjS]
                           principal: same [urn:CLykwchH.EOTb]
                               roles: same [urn:ROzAKMT.ZXPYL]
                   authn_expiry_ms: same [3424948]
                      certificates: 
                        idp_metadata: 
                                     0: same [MIIDYzCCAkugAwIBAgIVAITQVqXYYUT0w04Z2gWAZ6pv7gwbMA...]
                                     1: same [MIICYjCCAcugAwIBAgIUL9T74f75INSxmpirmjJTZHJXOGAwDQ...]
                         idp_signing: 
                                     0: same [MIICYjCCAcugAwIBAgIUL9T74f75INSxmpirmjJTZHJXOGAwDQ...]
                                     1: same [MIIDYzCCAkugAwIBAgIVAITQVqXYYUT0w04Z2gWAZ6pv7gwbMA...]
                          sp_signing: 
                                     0: same [MIICYjCCAcugAwIBAgIUL9T74f75INSxmpirmjJTZHJXOGAwDQ...]
                           created: same [1585931417384]
                           enabled: same [true]
                         entity_id: same [urn:WMlzwyPe.IcSbecXh]
                     last_modified: same [1585931781053]
                              name: same [XCdUghDKK]
                    name_id_format: same [urn:oasis:names:tc:SAML:1.1:nameid-format:emailAdd...]
                        privileges: 
                            resource: same [service:YlMyAaRsGQXx:IRIOpYWXtxMm]
                               roles: 
                                     0: same [svBJBu:(sMCOqR)]
                                     1: same [Tcjlgy:(QfMvSX)]
                                     2: expected String [KwagVK:(TcJmyz)] but was String [mZhekz:(EUxfto)]
                                     3: expected String [mZhekz:(EUxfto)] but was String [KwagVK:(TcJmyz)]
                     sign_messages: same [empty list]
        at __randomizedtesting.SeedInfo.seed([A6058E14C7A36194:DCAC96F09EB255D3]:0)
        at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertToXContentEquivalent(ElasticsearchAssertions.java:661)
        at org.elasticsearch.xpack.idp.saml.sp.SamlServiceProviderDocumentTests.assertXContentRoundTrip(SamlServiceProviderDocumentTests.java:148)
        at org.elasticsearch.xpack.idp.saml.sp.SamlServiceProviderDocumentTests.testStreamRoundTripWithAllFields(SamlServiceProviderDocumentTests.java:85)

        Caused by:
        org.junit.ComparisonFailure: expected:<[KwagVK:(TcJmyz])> but was:<[mZhekz:(EUxfto])>
            at org.junit.Assert.assertEquals(Assert.java:115)
            at org.junit.Assert.assertEquals(Assert.java:144)
            at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertObjectEquals(ElasticsearchAssertions.java:729)
            at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertListEquals(ElasticsearchAssertions.java:709)
            at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertObjectEquals(ElasticsearchAssertions.java:723)
            at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertMapEquals(ElasticsearchAssertions.java:696)
            at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertObjectEquals(ElasticsearchAssertions.java:721)
            at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertMapEquals(ElasticsearchAssertions.java:696)
            at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertToXContentEquivalent(ElasticsearchAssertions.java:657)
            ... 2 more
```

Attempted to fix it with 2a38b9a31e2670e4a31d19657812774a8e936d33 but this has the same issue exactly. Muting this until we can find a proper solution on Monday

**Comment by mark-vieira** [comment]
It seems `testStreamRoundTripWithAllFields` is failing for the same reason. I've muted it as well in `master` (3b84f8ad68975c7caa15adf81b2ee4c6f0b768ff) and `7.x` (0fa8a14bcb7261987c8ac9fc80b3db834c9274b2).

**Comment by romseygeek** [comment]
This is failing on 7x as well, I'll backport the mute
