### ISSUE TITLE
TransportAnalyticsStatsActionTests fail on master

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#54744]
./gradlew ':x-pack:plugin:analytics:test' --tests "org.elasticsearch.xpack.analytics.action.TransportAnalyticsStatsActionTests.test" \
  -Dtests.seed=C06A02480587257E \
  -Dtests.security.manager=true \
  -Dtests.locale=es-PY \
  -Dtests.timezone=Africa/Luanda \
  -Dcompiler.java=13

Test with this seed reproducibly fails for me.

As the test overall doesn't fail, only with this particular seed, I am not going to mute it for now.

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=sles-12&&immutable/673/console
Build Scans: https://gradle-enterprise.elastic.co/s/nmicdnymlrs4a

Console output: 
```
java.lang.AssertionError: 
Expected: <0>
     but: was null
	at __randomizedtesting.SeedInfo.seed([C06A02480587257E:483E3D92AB7B4886]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.analytics.action.TransportAnalyticsStatsActionTests.test(TransportAnalyticsStatsActionTests.java:66)
```

**Comment by mayya-sharipova** [comment]
Actually, there were quite a number of failures so the test was muted.
