### ISSUE TITLE
[CI] InferenceIngestIT.testPipelineIngest occasionally fails

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#54786]
Jenkins: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_RUNTIME_JAVA=zulu11,nodes=general-purpose/614/console

Build scan: https://gradle-enterprise.elastic.co/s/q4hcgpbmvcn3g

Failure:

```
java.lang.AssertionError: 

Expected: a string containing "\"inference_count\":10"
     but: was "{"count":1,"trained_model_stats":[{"model_id":"test_classification","pipeline_count":0,"inference_stats":{"failure_count":0,"inference_count":11,"missing_all_fields_count":0,"time_stamp":-9223372036854775808}}]}"

at __randomizedtesting.SeedInfo.seed([3274046E5719A7DD:90289258A5A9409E]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.xpack.ml.integration.InferenceIngestIT.lambda$testPipelineIngest$0(InferenceIngestIT.java:135)
``` 

Reproduce with:

```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.InferenceIngestIT.testPipelineIngest" -Dtests.seed=3274046E5719A7DD -Dtests.security.manager=true -Dtests.locale=es-CR -Dtests.timezone=Asia/Jayapura -Dcompiler.java=13
```

I couldn't reproduce locally.

**Comment by mark-vieira** [comment]
This looks to still be failing:

https://gradle-enterprise.elastic.co/s/wo64a3vdiq7do/tests/zcquf3hc3eoc6-oe3h7fwwev7pa
https://gradle-enterprise.elastic.co/s/dkkslswr4qgam/tests/zcquf3hc3eoc6-oe3h7fwwev7pa

**Comment by mark-vieira** [comment]
I've remuted on `master` with fbda31dafb667a0842b32f3f406f668caf39daea
