### ISSUE TITLE
[CI] DockerTests.test101AllFilesAreGroupZero failures

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#54817]
Jenkins: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.7+multijob+packaging-tests-unix-gcp/os=opensuse-15-1-packaging/35/console

Build scan: https://gradle-enterprise.elastic.co/s/ob4ef4u754wzk

Failure:

```
Command was not successful: [bash -c docker exec --user elasticsearch:root --tty 23c00f11003a0ae9b922e716fb01d73022385824c70a07dc291beb1852aa72ad find . -not -gid 0]
   result: exitCode = [1] stdout = [find: './config/elasticsearch.keystore.tmp': No such file or directory
./config/elasticsearch.keystore.tmp] stderr = []

at __randomizedtesting.SeedInfo.seed([589E47BFBCC7E1FE:CAF250DF3702E9FC]:0)
at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:142)
at org.elasticsearch.packaging.util.Shell.run(Shell.java:76)
at org.elasticsearch.packaging.test.DockerTests.test101AllFilesAreGroupZero(DockerTests.java:485)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Reproduce with:

```
./gradlew :qa:os:destructiveDistroTest.default-docker --tests "org.elasticsearch.packaging.test.DockerTests.test101AllFilesAreGroupZero"
```

I couldn't reproduce the error locally.

**Comment by not-napoleon** [comment]
Another incident of this: https://gradle-enterprise.elastic.co/s/etfqcdclo6ylg

**Comment by benwtrent** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/xuivd2dnrcvx6
