### ISSUE TITLE
[CI] IndexRecoveryIT.testRecoverLocallyUpToGlobalCheckpoint fails intermittently

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#54829]
Got this error on CI today in the 7.7 branch. Looks like it has failed a few times in the last month or so on a few PR builds.

The failure:
```
org.elasticsearch.indices.recovery.IndexRecoveryIT > testRecoverLocallyUpToGlobalCheckpoint FAILED
 java.lang.AssertionError: total recovered translog operations must include both local and remote recovery
 Expected: a value equal to or greater than <89>
 but: <81> was less than <89>
 at __randomizedtesting.SeedInfo.seed([EFD4DFF3F294AE9E:158F52B7E5910AD6]:0)
 at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
 at org.junit.Assert.assertThat(Assert.java:956)
 at org.elasticsearch.indices.recovery.IndexRecoveryIT.testRecoverLocallyUpToGlobalCheckpoint(IndexRecoveryIT.java:1203)
REPRODUCE WITH: ./gradlew ':server:integTest' --tests "org.elasticsearch.indices.recovery.IndexRecoveryIT.testRecoverLocallyUpToGlobalCheckpoint" -Dtests.seed=EFD4DFF3F294AE9E -Dtests.security.manager=true -Dtests.locale=sq-AL -Dtests.timezone=Asia/Beirut -Dcompiler.java=13
```

Scan: https://gradle-enterprise.elastic.co/s/c5ubooujvkxoy

**Comment by dnhatn** [comment]
I think the test failed because a file-based recovery was performed instead of an operation-based. We need more info to debug this. I've added more assertions in https://github.com/elastic/elasticsearch/commit/3a6e0135e65e3ad4271e25bd63ab8d6e7d5fc33c. I am closing this issue. Please reopen when it fails again

**Comment by dimitris-athanasiou** [comment]
This failed again but with a different error this time:

```
java.lang.AssertionError: timed out waiting for green state
at org.junit.Assert.fail(Assert.java:88)
at org.elasticsearch.test.ESIntegTestCase.ensureColor(ESIntegTestCase.java:940)
at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:893)
at org.elasticsearch.test.ESIntegTestCase.ensureGreen(ESIntegTestCase.java:882)
at org.elasticsearch.indices.recovery.IndexRecoveryIT.testRecoverLocallyUpToGlobalCheckpoint(IndexRecoveryIT.java:1212)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
```

Jenkins: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=sles-12&&immutable/687/console
Build Scan: https://gradle-enterprise.elastic.co/s/fjxtmcsyeapuy
