### ISSUE TITLE
java.lang.IllegalStateException: Received message from unsupported version: [2.0.0] minimal compatible version is: [5.6.0]

### ISSUE THREAD

**Issue by hello4usharath** [elastic/elasticsearch#54881]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
6.1.4
**Plugins installed**: []
NA
**JVM version** (`java -version`):
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
**OS version** (`uname -a` if on a Unix-like system):
Centos 7
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
We are connecting to elasticsearch via transport port from liferay

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

[2020-04-07T05:17:30,811][WARN ][o.e.t.n.Netty4Transport  ] [vltelk-dev-md1] exception caught on transport layer [org.elasticsearch.transport.netty4.NettyTcpChannel@63391a41], closing connection
java.lang.IllegalStateException: Received message from unsupported version: [2.0.0] minimal compatible version is: [5.6.0]
        at org.elasticsearch.transport.TcpTransport.ensureVersionCompatibility(TcpTransport.java:1428) ~[elasticsearch-6.1.4.jar:6.1.4]
        at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1375) ~[elasticsearch-6.1.4.jar:6.1.4]
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:64) ~[transport-netty4-6.1.4.jar:6.1.4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [netty-codec-4.1.13.Final.jar:4.1.13.Final]

**Comment by cbuescher** [comment]
Hi @hello4usharath! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. 

In this particular case, please note:
> Received message from unsupported version: [2.0.0] minimal compatible version is: [5.6.0] 
This means that something (a node or a client node) talking the protocol of version 2.0.0 is trying to talk to a node in a 6.1.4 cluster. This is not supported. The latest version that can interact with any 6.x version is 5.6.0.
