### ISSUE TITLE
Dissallow some search body parameters to be negative

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#54958]
This follows up to #54953. Currently we check several following search parameters for illegal values in their SearchSourceBuilder setters, e.g. negative values throw IAE for:
* size
* terminateAfter
* trackTotalHits

We use those validations when parsing the above as request parameters, but we don't check values when parsing the search request body, e.g.

```
GET foo/_search
{
  "size" : -5
}
```
Throws an "illegal_argument_exception" from `TopScoreDocCollector`
```
Caused by: java.lang.IllegalArgumentException: numHits must be > 0; please use TotalHitCountCollector if you just need the total hit count
	at org.apache.lucene.search.TopScoreDocCollector.create(TopScoreDocCollector.java:227) ~[lucene-core-8.4.0.jar:8.4.0 bc02ab906445fcf4e297f4ef00ab4a54fdd72ca2 - jpountz - 2019-12-19 20:16:14]
	at org.apache.lucene.search.TopScoreDocCollector.create(TopScoreDocCollector.java:220) ~[lucene-core-8.4.0.jar:8.4.0 bc02ab906445fcf4e297f4ef00ab4a54fdd72ca2 - jpountz - 2019-12-19 20:16:14]
```

We should align the validation of the above parameters by using the same validation mechanism, i.e. using the setters when parsing the search source.

**Comment by cbuescher** [comment]
@elasticmachine update branch
