### ISSUE TITLE
[CI] ModelLoadingServiceTests.testMaxCachedLimitReached failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#54986]
This test started failing occasionally a couple of days ago starting around April 6th on `master`. Didn't reproduce for me locally though.

```
org.elasticsearch.xpack.ml.inference.loadingservice.ModelLoadingServiceTests > testMaxCachedLimitReached FAILED
    Wanted but not invoked:
    trainedModelStatsService.queueStats(
        <custom argument matcher>
    );
    -> at org.elasticsearch.xpack.ml.inference.loadingservice.ModelLoadingServiceTests.testMaxCachedLimitReached(ModelLoadingServiceTests.java:207)
    Actually, there were zero interactions with this mock.
        at __randomizedtesting.SeedInfo.seed([7E2A38F2A7D31844:A34E4080900F1C49]:0)
        at org.elasticsearch.xpack.ml.inference.loadingservice.ModelLoadingServiceTests.testMaxCachedLimitReached(ModelLoadingServiceTests.java:207)
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:test' --tests "org.elasticsearch.xpack.ml.inference.loadingservice.ModelLoadingServiceTests.testMaxCachedLimitReached" -Dtests.seed=7E2A38F2A7D31844 -Dtests.security.manager=true -Dtests.locale=zh-Hant-HK -Dtests.timezone=America/Marigot -Dcompiler.java=14
```

https://gradle-enterprise.elastic.co/s/jgxusxpctpphs/tests/7bifs6bt3pimq-zvg6hwacrq4zu

**Comment by mark-vieira** [comment]
I've muted this in `master` with d7956eedf0a988049f18a80ae103deaa3f7a598a.
