### ISSUE TITLE
[CI] S3BlobContainerRetriesTests.testReadBlobWithPrematureConnectionClose failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#54981]
This test has been failing regularly:

```
org.elasticsearch.repositories.s3.S3BlobContainerRetriesTests > testReadBlobWithPrematureConnectionClose FAILED
    junit.framework.AssertionFailedError: Expected exception ConnectionClosedException but no exception was thrown
        at __randomizedtesting.SeedInfo.seed([5BA2E4DE24942562:AF4AB9DE43CE154C]:0)
        at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2743)
        at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2733)
        at org.elasticsearch.repositories.s3.S3BlobContainerRetriesTests.testReadBlobWithPrematureConnectionClose(S3BlobContainerRetriesTests.java:338)
REPRODUCE WITH: ./gradlew ':plugins:repository-s3:test' --tests "org.elasticsearch.repositories.s3.S3BlobContainerRetriesTests.testReadBlobWithPrematureConnectionClose" -Dtests.seed=5BA2E4DE24942562 -Dtests.security.manager=true -Dtests.locale=is -Dtests.timezone=US/Alaska -Dcompiler.java=14
```

https://gradle-enterprise.elastic.co/s/t6wgno34wbqao/tests/gharp3fr6cqlc-fpge25xilemlw

As [mentioned in Slack](https://elastic.slack.com/archives/C0D8ST60Y/p1586371835370500?thread_ts=1586371746.370400&cid=C0D8ST60Y), @original-brownbear is looking into this, just though it was worth having a documented issue for posterity and so test triage isn't investigating this.

**Comment by mark-vieira** [comment]
This has been causing some noise so I went ahead and muted in `master` (df395cad51a62610ebd852211ea3abaf8fda140f) and `7.x` (264bfaca567573a8163ef0579bd63af4c499a785).
