### ISSUE TITLE
[CI] S3BlobContainerRetriesTests.testReadRangeBlobWithRetries reproducibly fails

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#54995]
This looks like a newly added test and it has failed twice today. I was able to reproduce this failure locally in both `master` and `7.x`.

```
org.elasticsearch.repositories.s3.S3BlobContainerRetriesTests > testReadRangeBlobWithRetries FAILED
    java.lang.AssertionError: array lengths differed, expected.length=1 actual.length=0
        at __randomizedtesting.SeedInfo.seed([C3C28CF1ED038A75:16B862AC62B167BA]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.internal.ComparisonCriteria.assertArraysAreSameLength(ComparisonCriteria.java:76)
        at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:37)
        at org.junit.Assert.internalArrayEquals(Assert.java:532)
        at org.junit.Assert.assertArrayEquals(Assert.java:341)
        at org.junit.Assert.assertArrayEquals(Assert.java:352)
        at org.elasticsearch.repositories.s3.S3BlobContainerRetriesTests.testReadRangeBlobWithRetries(S3BlobContainerRetriesTests.java:268)
REPRODUCE WITH: ./gradlew ':plugins:repository-s3:test' --tests "org.elasticsearch.repositories.s3.S3BlobContainerRetriesTests.testReadRangeBlobWithRetries" -Dtests.seed=C3C28CF1ED038A75 -Dtests.security.manager=true -Dtests.locale=sv-SE -Dtests.timezone=Europe/Sofia -Dcompiler.java=14
```

https://gradle-enterprise.elastic.co/s/zrusrq7cnhdve/tests/gharp3fr6cqlc-bfqjgyjdiiyka

**Comment by mark-vieira** [comment]
Since this reproduces I've muted this test in `master` and `7.x`.
