### ISSUE TITLE
[CI] CancellableTasksIT.testBanOnlyNodesWithOutstandingDescendantTasks failure

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#55107]
Jenkins: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_RUNTIME_JAVA=openjdk15,nodes=general-purpose/628/console

Build scan: https://gradle-enterprise.elastic.co/s/ngherpdl5uyiy

Failure:
```
java.lang.AssertionError: 

Expected: <[5J_RNEO5TcmDuSAcO-6EQA:15, 5J_RNEO5TcmDuSAcO-6EQA:14, 5J_RNEO5TcmDuSAcO-6EQA:20]>
     but: was <[5J_RNEO5TcmDuSAcO-6EQA:15, 5J_RNEO5TcmDuSAcO-6EQA:14, 3H15XZDRQH-YRweRFOZo9w:77, 3H15XZDRQH-YRweRFOZo9w:92, 3H15XZDRQH-YRweRFOZo9w:95, 5J_RNEO5TcmDuSAcO-6EQA:20]>

at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.action.admin.cluster.node.tasks.CancellableTasksIT.lambda$testBanOnlyNodesWithOutstandingDescendantTasks$1(CancellableTasksIT.java:197)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:892)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:865)
at org.elasticsearch.action.admin.cluster.node.tasks.CancellableTasksIT.testBanOnlyNodesWithOutstandingDescendantTasks(CancellableTasksIT.java:182)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:564)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
```

Reproduce with:
```
./gradlew ':server:integTest' --tests "org.elasticsearch.action.admin.cluster.node.tasks.CancellableTasksIT.testBanOnlyNodesWithOutstandingDescendantTasks" -Dtests.seed=FA5462CC5538DF4C -Dtests.security.manager=true -Dtests.locale=ar-OM -Dtests.timezone=Africa/Harare -Dcompiler.java=14
```

Could not reproduce locally

**Comment by dnhatn** [comment]
Close in favor of https://github.com/elastic/elasticsearch/issues/55106
