### ISSUE TITLE
[CI] DanglingIndicesIT.testDanglingIndicesAreNotRecoveredWhenNotWritten failure

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#55105]
Jenkins: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.6+matrix-java-periodic/ES_RUNTIME_JAVA=openjdk15,nodes=general-purpose/177/console

Build scan: https://gradle-enterprise.elastic.co/s/4xlkuejren27q

Failure:
```
AcknowledgedResponse failed - not acked
Expected: <true>
     but: was <false>

at __randomizedtesting.SeedInfo.seed([9A2EC38422F708A1:93CF933A649F9B5B]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:112)
at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked(ElasticsearchAssertions.java:116)
at org.elasticsearch.indices.recovery.DanglingIndicesIT$3.onNodeStopped(DanglingIndicesIT.java:142)
at org.elasticsearch.test.InternalTestCluster$NodeAndClient.closeForRestart(InternalTestCluster.java:984)
at org.elasticsearch.test.InternalTestCluster.restartNode(InternalTestCluster.java:1829)
at org.elasticsearch.test.InternalTestCluster.restartRandomDataNode(InternalTestCluster.java:1784)
at org.elasticsearch.indices.recovery.DanglingIndicesIT.testDanglingIndicesAreNotRecoveredWhenNotWritten(DanglingIndicesIT.java:137)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:564)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
```

Reproduce with:
```
./gradlew ':server:integTest' --tests "org.elasticsearch.indices.recovery.DanglingIndicesIT.testDanglingIndicesAreNotRecoveredWhenNotWritten" -Dtests.seed=9A2EC38422F708A1 -Dtests.security.manager=true -Dtests.locale=es-PA -Dtests.timezone=Asia/Seoul -Dcompiler.java=13
```

Cannot reproduce locally.

**Comment by ywelsch** [comment]
I think that this hiccup is caused by the cluster coordination layer, and a messy master election. We have a three node cluster, with node_t1 being shut down. InternalTestCluster adds a voting configuration exclusion for node_t1, which was the master at the time. That node now abdicates to node_t0 (with term 2), but node_t2 seems to be trying to elect itself as master first (in term 3), which it looks to win, with node_t1 running itself an election in term 2 (unsuccessful, then tries term 4). Ultimately node_t2 ends up winning in term 5. There was an intermediate state where node_t2 had won in term 3 and where it processed the cluster health request which confirmed that there were two nodes in the cluster.

```
1> [2020-04-13T03:46:29,618][INFO ][o.e.t.InternalTestCluster] [testDanglingIndicesAreNotRecoveredWhenNotWritten] Restarting node [node_t1] 
  1> [2020-04-13T03:46:29,619][INFO ][o.e.t.InternalTestCluster] [testDanglingIndicesAreNotRecoveredWhenNotWritten] adding voting config exclusions [node_t1] prior to restart/shutdown
  1> [2020-04-13T03:46:29,708][INFO ][o.e.c.c.Coordinator      ] [node_t1] abdicating to {node_t0}{VjxLuFUcSKKbDZf76xazPA}{95I0Y3BKTy21QrOVOt5WTQ}{127.0.0.1}{127.0.0.1:36331}{dim} with term 2
  1> [2020-04-13T03:46:29,712][INFO ][o.e.c.s.ClusterApplierService] [node_t1] master node changed {previous [{node_t1}{Rk5ZWJbhRHig0jdNn7iMFw}{Bzk-zMv3Teaqi6cAji6TiQ}{127.0.0.1}{127.0.0.1:40465}{dim}], current []}, term: 1, version: 10, reason: becoming candidate: after abdicating to {node_t0}{VjxLuFUcSKKbDZf76xazPA}{95I0Y3BKTy21QrOVOt5WTQ}{127.0.0.1}{127.0.0.1:36331}{dim}
  1> [2020-04-13T03:46:29,712][INFO ][o.e.c.s.ClusterApplierService] [node_t0] master node changed {previous [{node_t1}{Rk5ZWJbhRHig0jdNn7iMFw}{Bzk-zMv3Teaqi6cAji6TiQ}{127.0.0.1}{127.0.0.1:40465}{dim}], current []}, term: 1, version: 10, reason: becoming candidate: joinLeaderInTerm
  1> [2020-04-13T03:46:29,713][INFO ][o.e.c.s.ClusterApplierService] [node_t2] master node changed {previous [{node_t1}{Rk5ZWJbhRHig0jdNn7iMFw}{Bzk-zMv3Teaqi6cAji6TiQ}{127.0.0.1}{127.0.0.1:40465}{dim}], current []}, term: 1, version: 10, reason: becoming candidate: joinLeaderInTerm
  1> [2020-04-13T03:46:29,818][INFO ][o.e.c.s.MasterService    ] [node_t2] elected-as-master ([1] nodes joined)[{node_t2}{7PGOypgYQK-RyF6uZl9ioA}{FlGOmbwrTFaJu0zgTwJSqw}{127.0.0.1}{127.0.0.1:38241}{dim} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 3, version: 11, delta: master node changed {previous [], current [{node_t2}{7PGOypgYQK-RyF6uZl9ioA}{FlGOmbwrTFaJu0zgTwJSqw}{127.0.0.1}{127.0.0.1:38241}{dim}]}
  1> [2020-04-13T03:46:29,849][INFO ][o.e.c.s.ClusterApplierService] [node_t1] master node changed {previous [], current [{node_t2}{7PGOypgYQK-RyF6uZl9ioA}{FlGOmbwrTFaJu0zgTwJSqw}{127.0.0.1}{127.0.0.1:38241}{dim}]}, term: 3, version: 11, reason: ApplyCommitRequest{term=3, version=11, sourceNode={node_t2}{7PGOypgYQK-RyF6uZl9ioA}{FlGOmbwrTFaJu0zgTwJSqw}{127.0.0.1}{127.0.0.1:38241}{dim}}
  1> [2020-04-13T03:46:29,875][INFO ][o.e.c.s.MasterService    ] [node_t0] elected-as-master ([2] nodes joined)[{node_t0}{VjxLuFUcSKKbDZf76xazPA}{95I0Y3BKTy21QrOVOt5WTQ}{127.0.0.1}{127.0.0.1:36331}{dim} elect leader, {node_t2}{7PGOypgYQK-RyF6uZl9ioA}{FlGOmbwrTFaJu0zgTwJSqw}{127.0.0.1}{127.0.0.1:38241}{dim} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 4, version: 11, delta: master node changed {previous [], current [{node_t0}{VjxLuFUcSKKbDZf76xazPA}{95I0Y3BKTy21QrOVOt5WTQ}{127.0.0.1}{127.0.0.1:36331}{dim}]}
  1> [2020-04-13T03:46:29,876][WARN ][o.e.c.s.MasterService    ] [node_t0] failing [elected-as-master ([2] nodes joined)[{node_t0}{VjxLuFUcSKKbDZf76xazPA}{95I0Y3BKTy21QrOVOt5WTQ}{127.0.0.1}{127.0.0.1:36331}{dim} elect leader, {node_t2}{7PGOypgYQK-RyF6uZl9ioA}{FlGOmbwrTFaJu0zgTwJSqw}{127.0.0.1}{127.0.0.1:38241}{dim} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_]]: failed to commit cluster state version [11]
  1> org.elasticsearch.cluster.coordination.FailedToCommitClusterStateException: node is no longer master for term 4 while handling publication
  1> 	at org.elasticsearch.cluster.coordination.Coordinator.publish(Coordinator.java:1050) ~[main/:?]
  1> 	at org.elasticsearch.cluster.service.MasterService.publish(MasterService.java:268) [main/:?]
  1> 	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:250) [main/:?]
  1> 	at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73) [main/:?]
  1> 	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151) [main/:?]
  1> 	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [main/:?]
  1> 	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [main/:?]
  1> 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [main/:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
  1> 	at java.lang.Thread.run(Thread.java:832) [?:?]
```

I'm not sure what we should do about this one. @DaveCTurner thoughts?

**Comment by DaveCTurner** [comment]
I think we've discussed previously that acking of a specific cluster state update seems like the wrong thing to check since they can fail like this but can still be applied successfully by a subsequent update.

Really only a problem when the master isn't completely established; maybe we should call `validateClusterFormed()`?
