### ISSUE TITLE
[CI] SearchableSnapshotsIntegTests.testCreateAndRestoreSearchableSnapshot failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#55126]
This looks to be a newly added test suite which has been regularly failing. There are actually two different failure messages for this test, but they're likely related so I'll put them both here.

The first *did not* reproduce for me:
https://gradle-enterprise.elastic.co/s/bp7bfzinzgj7a/tests/inzjkvfxeeuik-jku4cqj6y3o3c
```
org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests > testCreateAndRestoreSearchableSnapshot FAILED
    java.lang.AssertionError: Expecting stats to exist for at least 1 Lucene file
    Expected: a value greater than <0>
         but: <0> was equal to <0>
        at __randomizedtesting.SeedInfo.seed([82B6C95CFDFA75FC:8D5BE276E6D244F]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.assertSearchableSnapshotStats(SearchableSnapshotsIntegTests.java:267)
        at org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testCreateAndRestoreSearchableSnapshot(SearchableSnapshotsIntegTests.java:160)
REPRODUCE WITH: ./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testCreateAndRestoreSearchableSnapshot" -Dtests.seed=82B6C95CFDFA75FC -Dtests.security.manager=true -Dtests.locale=zh-SG -Dtests.timezone=America/Knox_IN -Dcompiler.java=14
```

This one did in fact reproduce locally:
https://gradle-enterprise.elastic.co/s/4yuveowg6tzsw/tests/inzjkvfxeeuik-jku4cqj6y3o3c
```
org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests > testCreateAndRestoreSearchableSnapshot FAILED
    java.lang.AssertionError: Expected at least 1 cache read or write for _0.cfe of shard [amgquvzumi][4], node[y3zUJ5IeSn6pvfhh2OLNtw], [P], s[STARTED], a[id=ihYKI2haQcGYlxPQSu0HoQ]
    Expected: a value greater than <0L>
         but: <0L> was equal to <0L>
        at __randomizedtesting.SeedInfo.seed([592E3670FA883540:D34D410B691F64F3]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.assertSearchableSnapshotStats(SearchableSnapshotsIntegTests.java:298)
        at org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testCreateAndRestoreSearchableSnapshot(SearchableSnapshotsIntegTests.java:160)
REPRODUCE WITH: ./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testCreateAndRestoreSearchableSnapshot" -Dtests.seed=592E3670FA883540 -Dtests.security.manager=true -Dtests.locale=en-NZ -Dtests.timezone=Asia/Beirut -Dcompiler.java=14
```

**Comment by mark-vieira** [comment]
I've muted this test in `master` with 0502817aa6fe6b4a81671457e451a3350a3fad95.
