### ISSUE TITLE
[CI] SignificantLongTermsTests.testReduceRandom failure on 7x

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#55149]
This reliably reproduces:

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.significant.SignificantLongTermsTests.testReduceRandom" \
  -Dtests.seed=A4C0204845ED86F5 \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=ca-ES \
  -Dtests.timezone=America/North_Dakota/New_Salem \
  -Dcompiler.java=14
```

```
org.elasticsearch.search.aggregations.bucket.significant.SignificantLongTermsTests > testReduceRandom FAILED
    java.io.EOFException
        at __randomizedtesting.SeedInfo.seed([A4C0204845ED86F5:64FD8C5963B01FA3]:0)
        at org.elasticsearch.common.bytes.BytesReferenceStreamInput.readByte(BytesReferenceStreamInput.java:51)
        at org.elasticsearch.common.bytes.AbstractBytesReference$MarkSupportingStreamInputWrapper.readByte(AbstractBytesReference.java:202)
        at org.elasticsearch.common.io.stream.FilterStreamInput.readByte(FilterStreamInput.java:40)
        at org.elasticsearch.common.io.stream.StreamInput.readVInt(StreamInput.java:227)
        at org.elasticsearch.common.io.stream.StreamInput.readArraySize(StreamInput.java:1265)
        at org.elasticsearch.common.io.stream.StreamInput.readString(StreamInput.java:418)
        at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:38)
        at org.elasticsearch.search.aggregations.bucket.significant.InternalMappedSignificantTerms.<init>(InternalMappedSignificantTerms.java:61)
        at org.elasticsearch.search.aggregations.bucket.significant.SignificantLongTerms.<init>(SignificantLongTerms.java:114)
        at org.elasticsearch.test.ESTestCase.copyInstance(ESTestCase.java:1236)
        at org.elasticsearch.test.ESTestCase.copyWriteable(ESTestCase.java:1206)
        at org.elasticsearch.test.AbstractWireSerializingTestCase.copyInstance(AbstractWireSerializingTestCase.java:44)
```

**Comment by polyfractal** [comment]
Reproduces on master, and I bisected it to https://github.com/elastic/elasticsearch/pull/54776

I don't think the PR itself is the problem, but rather than SigTerms suffers from the same issue that @nik9000 found in scripted-metrics: that SigTerms assumes you would never perform a partial reduction, serialize the results, and then perform a final reduction.  

54776 made some changes to InternalAggTestCase which serialize-after-partial-reduce and I think that's what's breaking here.  I haven't actually dropped into the debugger yet to verify though.
