### ISSUE TITLE
[CI] RepositoryBlockIT#getRepositoryWithBlocks failure on 7.7

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#55148]
https://gradle-enterprise.elastic.co/s/fnm5hyptqjnwe/console-log?task=:server:integTest

```

1> [2020-04-14T14:31:53,966][INFO ][o.e.p.PluginsService     ] [testGetRepositoryWithBlocks] no modules loaded |  
-- | --
  | 1> [2020-04-14T14:31:53,966][INFO ][o.e.p.PluginsService     ] [testGetRepositoryWithBlocks] loaded plugin [org.elasticsearch.transport.nio.MockNioTransportPlugin] |  
  | 1> [2020-04-14T14:31:53,972][WARN ][o.e.t.TcpTransport       ] [transport_client_node_t0] exception caught on transport layer [NioSocketChannel{localAddress=null, remoteAddress=null}], closing connection |  
  | 1> java.io.IOException: Failed to initiate socket channel connection {remoteAddress=/127.0.0.1:58695}. |  
  | 1> 	at org.elasticsearch.nio.SocketChannelContext.register(SocketChannelContext.java:99) ~[elasticsearch-nio-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.nio.EventHandler.handleRegistration(EventHandler.java:65) ~[elasticsearch-nio-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.transport.nio.TestEventHandler.handleRegistration(TestEventHandler.java:75) ~[framework-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.nio.NioSelector.registerChannel(NioSelector.java:448) ~[elasticsearch-nio-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.nio.NioSelector.setUpNewChannels(NioSelector.java:440) ~[elasticsearch-nio-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.nio.NioSelector.preSelect(NioSelector.java:261) ~[elasticsearch-nio-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:155) ~[elasticsearch-nio-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:131) ~[elasticsearch-nio-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241] |  
  | 1> Caused by: java.net.BindException: Address already in use |  
  | 1> 	at sun.nio.ch.Net.connect0(Native Method) ~[?:?] |  
  | 1> 	at sun.nio.ch.Net.connect(Net.java:454) ~[?:?] |  
  | 1> 	at sun.nio.ch.Net.connect(Net.java:446) ~[?:?] |  
  | 1> 	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648) ~[?:?] |  
  | 1> 	at org.elasticsearch.nio.SocketChannelContext.lambda$connect$0(SocketChannelContext.java:374) ~[elasticsearch-nio-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_241] |  
  | 1> 	at org.elasticsearch.nio.SocketChannelContext.connect(SocketChannelContext.java:374) ~[elasticsearch-nio-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.nio.SocketChannelContext.register(SocketChannelContext.java:97) ~[elasticsearch-nio-7.7.0-SNAPSHOT.jar:7.7.0-SNAPSHOT] |  
  | 1> 	... 8 more |  
  | 1> [2020-04-14T14:32:24,098][INFO ][o.e.n.Node               ] [testGetRepositoryWithBlocks] stopping ... |  
  | 1> [2020-04-14T14:32:24,098][INFO ][o.e.n.Node               ] [testGetRepositoryWithBlocks] stopped
```

Doesn't reproduce locally, but that's unsurprising for an `Address already in use` exception.

**Comment by original-brownbear** [comment]
I looked through the build stats and this is the first and only time we appear to have run into a `BindException` like this within the last 2 months. Since it's a `BindException` on `connect` I think the most likely reason for it is simply port exhaustion. I don't think there's anything I can do here and the failure doesn't suggest that it's an issue specific to this test => I'm closing this and will keep an eye out for port exhaustion in other test failures.
