### ISSUE TITLE
SLM Retention Task Always Fails in some Situations

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#55199]
There is a problem with the way the SLM retention task waits for snapshots to complete before running its delete. The following situation appears to never result in the retention task running:

1. Schedule a snapshot ever day at midnight.
2. Schedule the retention task to run at e.g. 0:10 every day and allow it a maximum runtime of 1h (`slm.retention_duration`).

Now if our nightly snapshot takes more than 1:10, the retention task will simply time out waiting for the snapshot every time and never execute, leading to a boundless growth in the number of snapshots in the repository.

Related issues here: 

1. We are not correctly using the cluster state observer. Instead of using a predicate for the cluster state we want (without snapshots in progress), we keep re-adding it. This means the timeout only comes into play when there are no cluster state updates. With cluster state update batching, we can get into some strange situations here where back to back snapshots result in the observer never executing and being re-added forever.
2. The timeout exception is simply thrown on the CS thread without being caught (which would fail if we had tests). (also it has a typo in it) see https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/slm/SnapshotRetentionTask.java#L537

This is actually seen in the wild repeatedly.
```
[instance-0000000051] uncaught exception in thread [elasticsearch[instance-0000000051][generic][T#151]]
org.elasticsearch.ElasticsearchException: java.lang.IllegalStateException: slm retention snapshot deletion out while waiting for ongoing snapshot operations to complete
	at org.elasticsearch.xpack.slm.SnapshotRetentionTask.lambda$maybeDeleteSnapshots$15(SnapshotRetentionTask.java:328) ~[?:?]
	at org.elasticsearch.xpack.slm.SnapshotRetentionTask$NoSnapshotRunningListener.onTimeout(SnapshotRetentionTask.java:516) ~[?:?]
	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:325) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:252) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:598) ~[elasticsearch-7.6.1.jar:7.6.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633) ~[elasticsearch-7.6.1.jar:7.6.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.IllegalStateException: slm retention snapshot deletion out while waiting for ongoing snapshot operations to complete
	... 8 more
```

3. We waste a generic pool thread during the waiting for the snapshot to delete. See https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/slm/SnapshotRetentionTask.java#L347

**Comment by dakrone** [comment]
> We are not correctly using the cluster state observer. Instead of using a predicate for the cluster state we want (without snapshots in progress), we keep re-adding it. This means the timeout only comes into play when there are no cluster state updates. With cluster state update batching, we can get into some strange situations here where back to back snapshots result in the observer never executing and being re-added forever.

When originally developing this, I was not able to get the observer to work correctly (which is why it is re-added), for some reason it would only check the very next state for the predicate, and ignore the observer otherwise. It would indeed be nice to rewrite where the predicate actually works, but I'd need to investigate why it was not working with the predicate previously.

**Comment by original-brownbear** [comment]
I'm closing this, with fully concurrent snapshot operations in 7.9+ this is not an issue any longer.
We should just progress with https://github.com/elastic/elasticsearch/issues/59655 IMO to remove all the complicated logic that this issue revolves around eventually to speed up and simplify SLM :)
