### ISSUE TITLE
fial to start elasticsearch after terminated unexpectedly

### ISSUE THREAD

**Issue by iture123** [elastic/elasticsearch#55281]
One data node shut down,and the last log is follow:
   ```
 at org.elasticsearch.common.io.stream.StreamOutput.writeException(StreamOutput.java:964) ~[elasticsearch-6.6.2.jar:6.6.2]
        at org.elasticsearch.ElasticsearchException.writeStackTraces(ElasticsearchException.java:743) ~[elasticsearch-6.6.2.jar:6.6.2]
        at org.elasticsearch.common.io.stream.StreamOutput.writeException(StreamOutput.java:966) ~[elasticsearch-6.6.2.jar:6.6.2]
        at org.elasticsearch.common.io.stream.StreamOutput.writeException(StreamOutput.java:964) ~[elasticsearch-6.6.2.jar:6.6.2]
        at org.elasticsearch.ElasticsearchException.writeStackTraces(ElasticsearchException.java:743) ~[elasticsearch-6.6.2.jar:6.6
```
So I try to start it with command ‘/data/elasticsearch-6.6.2/bin/elasticsearch -d’ , but it fail , And the start log is follow.
```
[2020-04-16T14:40:50,922][INFO ][o.e.p.PluginsService     ] [node-10-165-5-200] loaded plugin [analysis-ik]
[2020-04-16T14:40:50,940][ERROR][o.e.b.Bootstrap          ] [node-10-165-5-200] Exception
java.lang.NullPointerException: null
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:273) ~[?:?]
	at org.elasticsearch.common.io.PathUtils.get(PathUtils.java:60) ~[elasticsearch-core-6.6.2.jar:6.6.2]
	at org.elasticsearch.monitor.os.OsProbe.readSysFsCgroupCpuAcctCpuAcctUsage(OsProbe.java:277) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.monitor.os.OsProbe.getCgroupCpuAcctUsageNanos(OsProbe.java:264) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:483) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:603) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.xpack.ml.MachineLearning.additionalSettings(MachineLearning.java:334) ~[?:?]
	at org.elasticsearch.plugins.PluginsService.updatedSettings(PluginsService.java:204) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.node.Node.<init>(Node.java:338) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.6.2.jar:6.6.2]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.6.2.jar:6.6.2]

```
 And then I reboot the machine，and start elasticsearch  is success.

**Comment by cbuescher** [comment]
Hi @iture123! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
