### ISSUE TITLE
[CI] MedianAbsoluteDeviationAggregatorTests testSupportedFieldTypes failure

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#55299]
Failed on 7.x: https://gradle-enterprise.elastic.co/s/qw5aep7ahy5zq

Reproduce locally with
```
./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.metrics.MedianAbsoluteDeviationAggregatorTests.testSupportedFieldTypes" \
  -Dtests.seed=72B68E96205E9CC \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Latn-RS \
  -Dtests.timezone=Pacific/Majuro \
  -Dcompiler.java=14
```

Error:
```
java.lang.AssertionError: Aggregator [median_absolute_deviation] supports field type [half_float] but executing against the field threw an exception: [Cannot add NaN]
	at __randomizedtesting.SeedInfo.seed([72B68E96205E9CC:A038D5DD1D2130FF]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.elasticsearch.search.aggregations.AggregatorTestCase.testSupportedFieldTypes(AggregatorTestCase.java:660)
```

**Comment by csoulios** [comment]
Issue fixed in #55318
