### ISSUE TITLE
[CI] AllocationRoutedStepTests testConditionMet failure

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#55313]
Failed on 6.8: https://gradle-enterprise.elastic.co/s/jbdezoevocone

Reproduces locally with:
```
./gradlew ':x-pack:plugin:core:unitTest' \                                   
  -Dtests.seed=B7AB5AD19FF8561C \
  -Dtests.class=org.elasticsearch.xpack.core.indexlifecycle.AllocationRoutedStepTests \
  -Dtests.method="testConditionMet" \
  -Dtests.security.manager=true \
  -Dtests.locale=zh-HK \
  -Dtests.timezone=America/Adak \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

Error:
```
java.lang.AssertionError: expected:<true> but was:<false>
	at __randomizedtesting.SeedInfo.seed([B7AB5AD19FF8561C:5E3F883B680B0398]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.elasticsearch.xpack.core.indexlifecycle.AllocationRoutedStepTests.assertAllocateStatus(AllocationRoutedStepTests.java:336)
	at org.elasticsearch.xpack.core.indexlifecycle.AllocationRoutedStepTests.testConditionMet(AllocationRoutedStepTests.java:97)
```

**Comment by andreidan** [comment]
I suspect it's the same cause as https://github.com/elastic/elasticsearch/issues/60520 for which I have a PR  https://github.com/elastic/elasticsearch/pull/63670 open to enhance the test logging.

**Comment by andreidan** [comment]
We have additional logging in place if this flakes again, but the test has been running in CI for months without any failure. Closing this for now.
