### ISSUE TITLE
[CI] AssertionError in GoogleCloudStorageBlobContainerRetriesTests testWriteLargeBlob

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#55317]
Failure on 7.7: https://gradle-enterprise.elastic.co/s/6q5voyyn7k3vc

I couldn't reproduce locally (even leavign out the -Dbuild.snapshot=false):
```
./gradlew ':plugins:repository-gcs:test' --tests "org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainerRetriesTests.testWriteLargeBlob" \
  -Dtests.seed=74CA5748F999C5E9 \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=ca-ES \
  -Dtests.timezone=Asia/Tomsk \
  -Dcompiler.java=14
```

There is an AssertionError in the logs like this:
```
java.lang.AssertionError: 
Expected: (<15728640> or <7388234>)
     but: was <1949696>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) ~[hamcrest-2.1.jar:2.1]
	at org.junit.Assert.assertThat(Assert.java:956) ~[junit-4.12.jar:4.12]
	at org.junit.Assert.assertThat(Assert.java:923) ~[junit-4.12.jar:4.12]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainerRetriesTests.lambda$testWriteLargeBlob$12(GoogleCloudStorageBlobContainerRetriesTests.java:411) ~[test/:?]
	at org.elasticsearch.repositories.blobstore.ESMockAPIBasedRepositoryIntegTestCase.lambda$wrap$4(ESMockAPIBasedRepositoryIntegTestCase.java:238) ~[framework-7.7.0.jar:7.7.0]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainerRetriesTests.lambda$safeHandler$13(GoogleCloudStorageBlobContainerRetriesTests.java:452) ~[test/:?]
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79) [?:1.8.0_241]
```

I found https://github.com/elastic/elasticsearch/issues/52906 but the errors in the log look different so I opted for opening a new issue, please close or continue the investigation in that one if after all the issues seem to be related.

**Comment by original-brownbear** [comment]
This looks like a different issue than the JDK8 bug, I'll take a look.

**Comment by original-brownbear** [comment]
Closed via https://github.com/elastic/elasticsearch/pull/55372
