### ISSUE TITLE
[CI] FunctionScoreQueryBuilderTests testCacheability failure

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#55331]
Failure on master: https://gradle-enterprise.elastic.co/s/dmut5fjhfhzh2

This reproduces locally with
```
./gradlew ':server:test' --tests "org.elasticsearch.index.query.functionscore.FunctionScoreQueryBuilderTests.testCacheability" \
  -Dtests.seed=E852D4E6B71A6977 \
  -Dtests.security.manager=true \
  -Dtests.locale=it \
  -Dtests.timezone=SST \
  -Dcompiler.java=14
```

Error:
```
java.lang.AssertionError: query should not be cacheable: {
  "function_score" : {
    "query" : {
      "term" : {
        "BCGkj" : {
          "value" : true,
          "boost" : 0.2
        }
      }
    },
    "functions" : [
      {
        "filter" : {
          "ids" : {
            "values" : [
              "IqbhWHRudT",
              "CY",
              "xsJoX",
              "I",
              "vYm",
              "QhctenW",
              "IrQzUnqvn",
              "m",
              "dpvkCJK"
            ],
            "boost" : 0.6666667,
            "_name" : "ohSBWZ160"
          }
        },
        "weight" : 0.92822886,
        "script_score" : {
          "script" : {
            "source" : "1",
            "lang" : "mockscript"
          }
        }
      }
    ],
    "score_mode" : "first",
    "max_boost" : 0.6829204,
    "boost" : 1.0,
    "_name" : "f161"
  }
} expected:<false> but was:<true>
	at __randomizedtesting.SeedInfo.seed([E852D4E6B71A6977:C8DBA06ABD824177]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.elasticsearch.index.query.functionscore.FunctionScoreQueryBuilderTests.testCacheability(FunctionScoreQueryBuilderTests.java:832)
```

**Comment by cbuescher** [comment]
I briefly looked into this, there's a small change in rare occasions with the expected cacheability of queries after rewriter that was introduced with https://github.com/elastic/elasticsearch/pull/55271. I think I have a fix and will open a PR.
