### ISSUE TITLE
Jar Hell with nothing else installed?

### ISSUE THREAD

**Issue by zurgeg** [elastic/elasticsearch#55427]
**Elasticsearch version** (`bin/elasticsearch --version`):  7.6.2

**Plugins installed**: []

**JVM version** (`java -version`): openjdk version "1.8.0_242"

**OS version** (`uname -a` if on a Unix-like system): Linux cs-6000-devshell-vm-cf5470f0-4c0d-4a64-a1c9-11b5054af1a2 4.19.112+ #1 SMP Sat Apr 4 00:12:45 PDT 2020 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: I have nothing installed and yet the ElasticSearch crashes with a Jar Hell error

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.
 1. Start ElasticSearch

**Provide logs (if relevant)**:

        at java.util.jar.JarFile.<init>(JarFile.java:103) ~[?:1.8.0_242]
        at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:183) ~[elasticsearch-core-7.6.2.jar:7.6.2]
        at org.elasticsearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:510) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:469) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:163) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.node.Node.<init>(Node.java:313) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.node.Node.<init>(Node.java:257) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.6.2.jar:7.6.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.6.2.jar:7.6.2]
        ... 6 more

**Comment by jasontedor** [comment]
It's highly unlikely that there is a bug here. I suspect that you've some files from a previous installation in the same directory. The top of the exception message that you've truncated would give the conflicts, which would help you track this down. Since I don't think there's a bug here, and we reserve GitHub for verified bug reports, if you need additional help tracking this down, I'd ask that you use the [forums](https://discuss.elastic.co). If you do this, it would help if you included the top of the exception message. If it turns out there is a bug here, we can reopen this.
