### ISSUE TITLE
java.nio.channels.ClosedByInterruptException

### ISSUE THREAD

**Issue by lilizhaolilizhao** [elastic/elasticsearch#55471]
**I used the restclient client to connect to es 6.3.2 and ran it for 5 months. Suddenly, I got the following error message this morning:**

java.io.IOException
at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:728)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:198)
at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:522)
at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:508)
at org.elasticsearch.client.RestHighLevelClient.index(RestHighLevelClient.java:348)
at com.xxx.m.pay.dao.es.ESDao.indexData(ESDao.java:154)
......
......
Caused by: java.nio.channels.ClosedByInterruptException
at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:658)
at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processSessionRequests(DefaultConnectingIOReactor.java:274)
at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:141)
at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:350)
at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:191)
at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
... 1 more

**Comment by jasontedor** [comment]
@lilizhaolilizhao It is difficult for us to help you when you only dump a stack trace without any surrounding context. Unless you can give us more context, ideally a reproduction, and some indication why you think there's a bug here as opposed to something that happened in your environment, we'll have to close this issue out and ask you to use the [forums](https://discuss.elastic.co) for assistance in debugging.

**Comment by jasontedor** [comment]
No additional feedback, closing.
