### ISSUE TITLE
[CI] IndexStats.testBulkStats fails looking for a stat that is zero

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#55485]
The failure looks like:

```
java.lang.AssertionError: 
Expected: a value greater than <0L>
     but: <0L> was equal to <0L>
	at __randomizedtesting.SeedInfo.seed([53E1A42B3AEEE880:D9991F5953912569]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.indices.stats.IndexStatsIT.testBulkStats(IndexStatsIT.java:1101)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

It doesn't fail with:

```
./gradlew ':server:integTest' --tests "org.elasticsearch.indices.stats.IndexStatsIT.testBulkStats" -Dtests.seed=53E1A42B3AEEE880 -Dtests.security.manager=true -Dtests.locale=id -Dtests.timezone=Australia/Brisbane -Dcompiler.java=14
```

But I have seen it a few times, @probakowski I believe this is related to #52208

**Comment by iverase** [comment]
There are a few more errors. I am muting the test in master.
