### ISSUE TITLE
[CI] GoogleCloudStorageBlobContainerRetriesTests.testReadRangeBlobWithRetries reproducibly fails with 504 Gateway error

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#55505]
There are a few failures of this test, it can be reproduce I'm master and 7x with:
```
 ./gradlew ':plugins:repository-gcs:test' --tests "org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainerRetriesTests.testReadRangeBlobWithRetries"   -Dtests.seed=B4284431404FAEFC   -Dtests.security.manager=true   -Dtests.locale=be-BY   -Dtests.timezone=Canada/Eastern   -Dcompiler.java=14
```

The error looks like:

```
com.google.cloud.storage.StorageException: 504 Gateway Timeout
        at __randomizedtesting.SeedInfo.seed([B4284431404FAEFC:6152AA6CCFFD4333]:0)
        at com.google.cloud.storage.StorageException.translate(StorageException.java:97)
        at com.google.cloud.storage.spi.v1.HttpStorageRpc.read(HttpStorageRpc.java:704)
        at com.google.cloud.storage.BlobReadChannel$1.call(BlobReadChannel.java:127)
        at com.google.cloud.storage.BlobReadChannel$1.call(BlobReadChannel.java:124)
        at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
        at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
        at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
        at com.google.cloud.storage.BlobReadChannel.read(BlobReadChannel.java:123)
        at org.elasticsearch.repositories.gcs.GoogleCloudStorageRetryingInputStream$1.lambda$read$0(GoogleCloudStorageRetryingInputStream.java:101)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
        at org.elasticsearch.repositories.gcs.SocketAccess.doPrivilegedIOException(SocketAccess.java:44)
        at org.elasticsearch.repositories.gcs.GoogleCloudStorageRetryingInputStream$1.read(GoogleCloudStorageRetryingInputStream.java:101)
        at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
        at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107)

```

Build scan: https://gradle-enterprise.elastic.co/s/byw3ghdrdexig

**Comment by iverase** [comment]
I am muting the test in master and 7.x as it can be reproduced.

**Comment by original-brownbear** [comment]
@ywelsch ping <= I think you were looking into this one
