### ISSUE TITLE
[CI] org.elasticsearch.index.reindex.CancelTests.testDeleteByQueryCancelWithWorkers

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#55647]
This failed on 7.x:

```
REPRODUCE WITH: ./gradlew ':modules:reindex:test' --tests "org.elasticsearch.index.reindex.CancelTests.testDeleteByQueryCancelWithWorkers" -Dtests.seed=3D39804563CFCD20 -Dtests.security.manager=true -Dtests.locale=mk-MK -Dtests.timezone=Atlantic/Stanley -Dcompiler.java=14
```

```

org.elasticsearch.index.reindex.CancelTests > testDeleteByQueryCancelWithWorkers FAILED
    java.lang.RuntimeException: Exception while waiting for the response. Running tasks: {
      "tasks" : [ ]
    }
        at __randomizedtesting.SeedInfo.seed([3D39804563CFCD20:724F4E07BD0BD9C7]:0)
        at org.elasticsearch.index.reindex.CancelTests.testCancel(CancelTests.java:181)
        at org.elasticsearch.index.reindex.CancelTests.testDeleteByQueryCancelWithWorkers(CancelTests.java:275)

        Caused by:
        java.util.concurrent.ExecutionException: Failed to execute phase [query], all shards failed; shardFailures {RemoteTransportException[[node_sd1][127.0.0.1:36753][indices:data/read/search[phase/query+fetch/scroll]]]; nested: TaskCancelledException[cancelled]; }
            at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:266)
            at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:239)
            at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:65)
            at org.elasticsearch.index.reindex.CancelTests.testCancel(CancelTests.java:177)
            ... 1 more

            Caused by:
            Failed to execute phase [query], all shards failed; shardFailures {RemoteTransportException[[node_sd1][127.0.0.1:36753][indices:data/read/search[phase/query+fetch/scroll]]]; nested: TaskCancelledException[cancelled]; }
                at org.elasticsearch.action.search.SearchScrollAsyncAction.onShardFailure(SearchScrollAsyncAction.java:262)
                at org.elasticsearch.action.search.SearchScrollAsyncAction$1.onFailure(SearchScrollAsyncAction.java:195)
                at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:59)
                at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:402)
                at org.elasticsearch.transport.TransportService$6.handleException(TransportService.java:639)
                at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1171)
                at org.elasticsearch.transport.InboundHandler.lambda$handleException$2(InboundHandler.java:244)
                at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:226)
                at org.elasticsearch.transport.InboundHandler.handleException(InboundHandler.java:242)
                at org.elasticsearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:234)
                at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:131)
                at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:94)
                at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:698)
                at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142)
                at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117)
                at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82)
                at org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:297)
                at org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:228)
                at org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:40)
                at org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:139)
                at org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:151)
                at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:420)
                at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:246)
                at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:174)
                at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:131)
                at java.base/java.lang.Thread.run(Thread.java:834)

                Caused by:
                RemoteTransportException[[node_sd1][127.0.0.1:36753][indices:data/read/search[phase/query+fetch/scroll]]]; nested: TaskCancelledException[cancelled];

                    Caused by:
                    TaskCancelledException[cancelled]
                        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:150)
                        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:463)
                        at org.elasticsearch.search.SearchService.lambda$executeFetchPhase$3(SearchService.java:560)
                        at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:58)
                        at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73)
                        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
                        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)
                        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:695)
                        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
```

https://gradle-enterprise.elastic.co/s/vxfc56c6tmnpc/

**Comment by probakowski** [comment]
I think we have another instance of this failure: https://gradle-enterprise.elastic.co/s/vl6n3xho2qer6/tests/5nfchac5yggno-yqqh62cuxhd6i

**Comment by droberts195** [comment]
Same thing again in https://gradle-enterprise.elastic.co/s/5pxk2rqlupt3m - `all shards failed` on a scroll.
