### ISSUE TITLE
[CI] CorruptedFileIT.testCorruptionOnNetworkLayer failure 

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#55705]
This is a new failure today but it is reproducible locally on master branch.

> ./gradlew ':server:integTest' --tests "org.elasticsearch.index.store.CorruptedFileIT.testCorruptionOnNetworkLayer" -Dtests.seed=416CE27C6D190108 -Dtests.security.manager=true -Dtests.locale=es-PE -Dtests.timezone=America/Manaus -Dcompiler.java=14 -Druntime.java=11

Build scan: https://gradle-enterprise.elastic.co/s/scdmcouk5clvs

Stacktrace:
```
Captured an uncaught exception in thread: Thread[id=1251, name=elasticsearch[node_t0][generic][T#2], state=RUNNABLE, group=TGRP-CorruptedFileIT]
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=1251, name=elasticsearch[node_t0][generic][T#2], state=RUNNABLE, group=TGRP-CorruptedFileIT]

Caused by: java.lang.AssertionError: no internal reference!!Close stacktrace
at __randomizedtesting.SeedInfo.seed([416CE27C6D190108]:0)
at org.elasticsearch.index.store.CorruptedFileIT.lambda$testCorruptionOnNetworkLayer$2(CorruptedFileIT.java:443)
at org.elasticsearch.test.transport.StubbableTransport$WrappedConnection.sendRequest(StubbableTransport.java:235)
at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:680)
at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:594)
at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:548)
at org.elasticsearch.indices.recovery.RemoteRecoveryTargetHandler$1.tryAction(RemoteRecoveryTargetHandler.java:264)
at org.elasticsearch.action.support.RetryableAction$1.doRun(RetryableAction.java:87)
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:178)
at org.elasticsearch.action.support.RetryableAction.run(RetryableAction.java:73)
at org.elasticsearch.indices.recovery.RemoteRecoveryTargetHandler.executeRetryableAction(RemoteRecoveryTargetHandler.java:274)
at org.elasticsearch.indices.recovery.RemoteRecoveryTargetHandler.writeFileChunk(RemoteRecoveryTargetHandler.java:225)
at org.elasticsearch.indices.recovery.RecoverySourceHandler$2.executeChunkRequest(RecoverySourceHandler.java:884)
at org.elasticsearch.indices.recovery.RecoverySourceHandler$2.executeChunkRequest(RecoverySourceHandler.java:848)
at org.elasticsearch.indices.recovery.MultiFileTransfer.handleItems(MultiFileTransfer.java:124)
at org.elasticsearch.indices.recovery.MultiFileTransfer$1.write(MultiFileTransfer.java:79)
at org.elasticsearch.common.util.concurrent.AsyncIOProcessor.processList(AsyncIOProcessor.java:108)
at org.elasticsearch.common.util.concurrent.AsyncIOProcessor.drainAndProcessAndRelease(AsyncIOProcessor.java:96)
at org.elasticsearch.common.util.concurrent.AsyncIOProcessor.put(AsyncIOProcessor.java:84)
at org.elasticsearch.indices.recovery.MultiFileTransfer.addItem(MultiFileTransfer.java:90)
at org.elasticsearch.indices.recovery.MultiFileTransfer.start(MultiFileTransfer.java:86)
at org.elasticsearch.indices.recovery.RecoverySourceHandler.sendFiles(RecoverySourceHandler.java:899)
at org.elasticsearch.indices.recovery.RecoverySourceHandler.lambda$phase1$23(RecoverySourceHandler.java:509)
at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:112)
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:178)
at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:106)
at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:98)
at java.util.ArrayList.forEach(ArrayList.java:1540)
at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:98)
at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:144)
at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:127)
at org.elasticsearch.action.StepListener.innerOnResponse(StepListener.java:62)
at org.elasticsearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:40)
at org.elasticsearch.action.ActionListener$4.onResponse(ActionListener.java:163)
at org.elasticsearch.action.ActionListener$6.onResponse(ActionListener.java:282)
at org.elasticsearch.action.support.RetryableAction$RetryingListener.onResponse(RetryableAction.java:118)
at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:54)
at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1101)
at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:206)
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:691)
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.lang.Thread.run(Thread.java:834)
```

**Comment by ywangd** [comment]
It is specific to the test seed. It does not fail with another seed. It is likely a rare edge case so I'll leave it without muting.

**Comment by dakrone** [comment]
This failed again today: https://gradle-enterprise.elastic.co/s/kru2adsajnluq/tests/kyv2y2z3r4v7k-wg43wloxxs2g4?open-stacktraces=WzAsMV0

**Comment by dnhatn** [comment]
This is no longer an issue with #56072, as we now use a separate ByteArrays for each chunk request. Previously (since #55353), we used BytesReference instances that are provided by BytesStreamOutput.
