### ISSUE TITLE
[CI] org.elasticsearch.discovery.ClusterDisruptionIT » testRestartNodeWhileIndexing failed on master

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#55869]
Failure looks like it missed some documents after the restart:

```
:server:integTest » org.elasticsearch.discovery.ClusterDisruptionIT » testRestartNodeWhileIndexing (56.774s)

Expected: a value equal to or greater than <100>
     but: <51> was less than <100>
java.lang.AssertionError:

Expected: a value equal to or greater than <100>
     but: <51> was less than <100>
at __randomizedtesting.SeedInfo.seed([81650DAFA571AE12:EE85DE97AD79E6E0]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.discovery.ClusterDisruptionIT.lambda$testRestartNodeWhileIndexing$10(ClusterDisruptionIT.java:492)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:892)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:865)
at org.elasticsearch.discovery.ClusterDisruptionIT.testRestartNodeWhileIndexing(ClusterDisruptionIT.java:492)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:566)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
```

The reproduce line is:

```
./gradlew ':server:integTest' --tests "org.elasticsearch.discovery.ClusterDisruptionIT.testRestartNodeWhileIndexing" -Dtests.seed=81650DAFA571AE12 -Dtests.security.manager=true -Dtests.locale=lt -Dtests.timezone=America/Panama -Dcompiler.java=14 -Druntime.java=11
```

But it doesn't reproduce for me.

Link: https://gradle-enterprise.elastic.co/s/uswlaskxqvvtw/tests/kyv2y2z3r4v7k-5jnxwnv3ti4aw?open-stacktraces=WzBd

**Comment by dnhatn** [comment]
> but: <3> was less than <100>
> but: <9> was less than <100>
> but: <18> was less than <100>
> but: <51> was less than <100>

I guess that we need to increase the time out.
