### ISSUE TITLE
Stackoverflow and too many open files

### ISSUE THREAD

**Issue by ItamarBenjamin** [elastic/elasticsearch#55893]
**Elasticsearch version** 6.8.6 docker

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** ubuntu 16

**Description of the problem including expected versus actual behavior**:

a cluster with 6 data nodes, 3 master nodes and 2 coordinating - total of 7.5K shards
each data node with 30GB of RAM, and max open files 65536

getting Too many open files errors and then stackoverflow exception.
not sure why getting the Too many open files exception...

seeing many nested exceptions like:

`
[2020-04-28T12:34:49,649][WARN ][o.e.i.e.Engine           ] [fmyinf7113-1] [mars_storage-directories_history_4b895ae4-c01d-4904-88b9-d11090dea4c6-000001][0] giving up looking for fatal errors
java.nio.file.FileSystemException: /usr/share/elasticsearch/data/nodes/0/indices/2E5BQgAiQ_u_EBSxl-JZlA/0/translog/translog-2167182483755916320.ckp: Too many open files
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
        at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:248) ~[?:?]
        at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:603) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258) ~[?:?]
        at java.nio.file.Files.copy(Files.java:1298) ~[?:?]
        at org.elasticsearch.index.translog.Translog.copyCheckpointTo(Translog.java:285) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.index.translog.Translog.rollGeneration(Translog.java:1709) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.index.engine.InternalEngine.flush(InternalEngine.java:1818) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.index.shard.IndexShard.flush(IndexShard.java:1117) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.indices.flush.SyncedFlushService.performPreSyncedFlush(SyncedFlushService.java:507) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.indices.flush.SyncedFlushService.access$500(SyncedFlushService.java:74) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.indices.flush.SyncedFlushService$PreSyncedFlushTransportHandler.messageReceived(SyncedFlushService.java:817) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.indices.flush.SyncedFlushService$PreSyncedFlushTransportHandler.messageReceived(SyncedFlushService.java:813) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:692) [elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) [elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.8.6.jar:6.8.6]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
        Suppressed: org.apache.lucene.store.AlreadyClosedException: translog [39] is already closed (path [/usr/share/elasticsearch/data/nodes/0/indices/2E5BQgAiQ_u_EBSxl-JZlA/0/translog/translog-39.tlog]
                at org.elasticsearch.index.translog.TranslogWriter.closeIntoReader(TranslogWriter.java:305) ~[elasticsearch-6.8.6.jar:6.8.6]
                at org.elasticsearch.index.translog.Translog.rollGeneration(Translog.java:1706) ~[elasticsearch-6.8.6.jar:6.8.6]
                at org.elasticsearch.index.engine.InternalEngine.flush(InternalEngine.java:1818) ~[elasticsearch-6.8.6.jar:6.8.6]
                at org.elasticsearch.index.shard.IndexShard.flush(IndexShard.java:1117) ~[elasticsearch-6.8.6.jar:6.8.6]
                at org.elasticsearch.indices.flush.SyncedFlushService.performPreSyncedFlush(SyncedFlushService.java:507) ~[elasticsearch-6.8.6.jar:6.8.6]
                at org.elasticsearch.indices.flush.SyncedFlushService.access$500(SyncedFlushService.java:74) ~[elasticsearch-6.8.6.jar:6.8.6]
                at org.elasticsearch.indices.flush.SyncedFlushService$PreSyncedFlushTransportHandler.messageReceived(SyncedFlushService.java:817) ~[elasticsearch-6.8.6.jar:6.8.6]
                at org.elasticsearch.indices.flush.SyncedFlushService$PreSyncedFlushTransportHandler.messageReceived(SyncedFlushService.java:813) ~[elasticsearch-6.8.6.jar:6.8.6]
                at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30) ~[elasticsearch-6.8.6.jar:6.8.6]
                at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.8.6.jar:6.8.6]
                at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:692) [elasticsearch-6.8.6.jar:6.8.6]
                at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) [elasticsearch-6.8.6.jar:6.8.6]
                at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.8.6.jar:6.8.6]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
                at java.lang.Thread.run(Thread.java:830) [?:?]
        Caused by: java.nio.file.FileSystemException: /usr/share/elasticsearch/data/nodes/0/indices/2E5BQgAiQ_u_EBSxl-JZlA/0/translog/translog-2167182483755916320.ckp: Too many open files
                at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]
                at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
                at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
                at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:248) ~[?:?]
                at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:603) ~[?:?]
`

and in the end 
`
 at org.elasticsearch.common.io.stream.StreamOutput.writeException(StreamOutput.java:985) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.ElasticsearchException.writeStackTraces(ElasticsearchException.java:743) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.io.stream.StreamOutput.writeException(StreamOutput.java:987) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.io.stream.StreamOutput.writeException(StreamOutput.java:985) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.ElasticsearchException.writeStackTraces(ElasticsearchException.java:743) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.io.stream.StreamOutput.writeException(StreamOutput.java:987) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.io.stream.StreamOutput.writeException(StreamOutput.java:985) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.ElasticsearchException.writeStackTraces(ElasticsearchException.java:743) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.io.stream.StreamOutput.writeException(StreamOutput.java:987) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.io.stream.StreamOutput.writeException(StreamOutput.java:985) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.ElasticsearchException.writeStackTraces(ElasticsearchException.java:743) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.io.stream.StreamOutput.writeException(StreamOutput.java:987) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.io.stream.StreamOutput.writeException(StreamOutput.java:985) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.ElasticsearchException.writeStackTraces(ElasticsearchException.java:743) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.io.stream.StreamOutput.writeException(StreamOutput.java:987) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.io.stream.StreamOutput.writeException(StreamOutput.java:985) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.ElasticsearchException.writeStackTraces(ElasticsearchException.java:743) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.io.stream.StreamOutput.writeException(StreamOutput.java:987) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.io.stream.StreamOutput.writeException(StreamOutput.java:985) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.ElasticsearchException.writeStackTraces(ElasticsearchException.java:743) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.io.stream.StreamOutput.writeException(StreamOutput.java:987) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.common.io.stream.StreamOutput.writeException(StreamOutput.java:985) ~[elasticsearch-6.8.6.jar:6.8.6]
        at org.elasticsearch.ElasticsearchException.writeStackTraces(ElasticsearchException.java:743) ~[elasticsearch-6.8.6.jar:6.8.6]

`
**Provide logs (if relevant)**:

**Comment by dnhatn** [comment]
@ItamarBenjamin Thank you for reporting this issue.

There are too many shards in the cluster that leads to running out of file descriptors. You need to add more nodes or close inactive indices.

The node dies because we serialize a circular exception. We have a fix in https://github.com/elastic/elasticsearch/pull/54147 to prevent StackOverflow if we ever serialize a circular exception. We should never create a circular exception, but from the log, we did create a one in translog. Can you share the full log file?

**Comment by dnhatn** [comment]
I think I have figured out the source. I am working on the fix.

**Comment by dnhatn** [comment]
Hi @ItamarBenjamin,

> Do you still need the log file you asked? is there a way i can send it to your personally and not post it here?

Yes, please send it to my email at: `nhat.nguyen at elastic.co`.

> I also wanted to ask - 7.5K shards for 6 data nodes is ~1250 shards per node. it doesn't seem like a very high number.

~1250 shards per node is higher than the limit that we recommend (i.e., [max 1000 shards per node](https://www.elastic.co/guide/en/elasticsearch/reference/master/misc-cluster.html#cluster-shard-limit)). Can you share the output of `GET /_stats?level=shards`? 

Thank you!

**Comment by dnhatn** [comment]
I've opened https://github.com/elastic/elasticsearch/pull/55959

**Comment by ItamarBenjamin** [comment]
Hi,
just updating this happened again after I removed many indices. Total number of shards in the cluster at the time of the crash was 4762 and cluster had the same 6 data nodes as before. most indices were undergoing heavy indexing at the time of the crash.
