### ISSUE TITLE
AsyncSearchActionIT can fail during 'after test' checks

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#55895]
The `AsyncSearchActionIT` test doesn't always pass the checks in `TestCluster#assertAfterTest`. 

Build scan: https://gradle-enterprise.elastic.co/s/byylhh2vpytkq
Example reproduce line:
```
./gradlew ':x-pack:plugin:async-search:internalClusterTest' --tests "org.elasticsearch.xpack.search.AsyncSearchActionIT.testUpdateRunningKeepAlive" -Dtests.seed=43B6F15A7AB86387 -Dtests.security.manager=true -Dtests.locale=es-CO -Dtests.timezone=Mexico/BajaNorte -Dcompiler.java=14 -Druntime.java=11
```

The failure doesn't reproduce consistently.

Excerpt from logs:

```
  2> java.lang.AssertionError: Accounting breaker not reset to 0 on node: node_sd1, are there still Lucene indices around?
    Expected: <0L>
         but: was <1222L>
        at __randomizedtesting.SeedInfo.seed([43B6F15A7AB86387:152B3C508C1EE026]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.test.InternalTestCluster.lambda$ensureEstimatedStats$37(InternalTestCluster.java:2199)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:892)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:865)
        at org.elasticsearch.test.InternalTestCluster.ensureEstimatedStats(InternalTestCluster.java:2197)
        at org.elasticsearch.test.TestCluster.assertAfterTest(TestCluster.java:90)
```

**Comment by mark-vieira** [comment]
This happened again on `7.x`.

https://gradle-enterprise.elastic.co/s/txzdcec5u2qo2/console-log?task=:x-pack:plugin:async-search:internalClusterTest
