### ISSUE TITLE
[CI] AsyncSearchActionIT aggregation tests failing assertions

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#55955]
Both `testTermsAggregation` and `testMaxMinAggregation` have been increasingly failing over the past few days with the same `AssertionError` on both `master` and `7.x` branches. The failure did not reproduce for me locally.

**7.x:**

```
org.elasticsearch.xpack.search.AsyncSearchActionIT > testTermsAggregation FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([46A29C9E371B4861:89C193D7CCFCD069]:0)
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertNotNull(Assert.java:712)
        at org.junit.Assert.assertNotNull(Assert.java:722)
        at org.elasticsearch.xpack.search.AsyncSearchIntegTestCase$2.doNext(AsyncSearchIntegTestCase.java:249)
        at org.elasticsearch.xpack.search.AsyncSearchIntegTestCase$2.next(AsyncSearchIntegTestCase.java:209)
        at org.elasticsearch.xpack.search.AsyncSearchIntegTestCase$2.next(AsyncSearchIntegTestCase.java:196)
        at org.elasticsearch.xpack.search.AsyncSearchActionIT.testTermsAggregation(AsyncSearchActionIT.java:135)
REPRODUCE WITH: ./gradlew ':x-pack:plugin:async-search:internalClusterTest' --tests "org.elasticsearch.xpack.search.AsyncSearchActionIT.testTermsAggregation" -Dtests.seed=46A29C9E371B4861 -Dtests.security.manager=true -Dtests.locale=en-CA -Dtests.timezone=Pacific/Samoa -Dcompiler.java=14 -Druntime.java=8
```

https://gradle-enterprise.elastic.co/s/ovwrt64qmcwxo/tests/i7sypgkcctyli-axz7mvyr57v3s

**Comment by mark-vieira** [comment]
I've muted both tests in `master` (6e6a10f516d59a8da51e08a4845d83ce84931ae6) and `7.x` (2fe4801ca16cab1f145cc04146999142703007fd).

**Comment by jimczi** [comment]
Thanks @mark-vieira . These failures are already fixed in https://github.com/elastic/elasticsearch/issues/55920 so I reverted the muting.
