### ISSUE TITLE
SQL: incorrect column resolution from parameter

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#56013]
```
POST _sql
{
  "query": "SELECT ?, ? FROM library",
  "params": [
    {
      "type": "INTEGER",
      "value": 1
    },
    {
      "type": "INTEGER",
      "value": 2
    }
  ],
  "mode": "jdbc",
  "version": "7.7.0"
}
```
will fail with `Unknown output attribute ?{r}#9796`.

Leaving the index out _or_ changing the parameter type (i.e. no type repetition in the list) will work as expected.

Stacktrace:
```
    java.sql.SQLException: Server encountered an error [Unknown output attribute ?{r}#27]. [org.elasticsearch.xpack.sql.SqlIllegalArgumentException: Unknown output attribute ?{r}#27
        at org.elasticsearch.xpack.sql.querydsl.container.QueryContainer.asFieldExtraction(QueryContainer.java:478)
        at org.elasticsearch.xpack.sql.querydsl.container.QueryContainer.addColumn(QueryContainer.java:445)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$PlanOutputToQueryRef.rule(QueryFolder.java:781)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$PlanOutputToQueryRef.rule(QueryFolder.java:770)
        at org.elasticsearch.xpack.ql.tree.Node.lambda$transformUp$11(Node.java:197)
        at org.elasticsearch.xpack.ql.tree.Node.transformUp(Node.java:191)
        at org.elasticsearch.xpack.ql.tree.Node.transformUp(Node.java:197)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:875)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:871)
        at org.elasticsearch.xpack.ql.rule.RuleExecutor$Transformation.<init>(RuleExecutor.java:82)
        at org.elasticsearch.xpack.ql.rule.RuleExecutor.executeWithInfo(RuleExecutor.java:158)
        at org.elasticsearch.xpack.ql.rule.RuleExecutor.execute(RuleExecutor.java:130)
        at org.elasticsearch.xpack.sql.planner.QueryFolder.fold(QueryFolder.java:111)
        at org.elasticsearch.xpack.sql.planner.Planner.foldPlan(Planner.java:38)
        at org.elasticsearch.xpack.sql.planner.Planner.plan(Planner.java:28)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$physicalPlan$4(SqlSession.java:160)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$optimizedPlan$3(SqlSession.java:156)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$preAnalyze$2(SqlSession.java:144)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
        at org.elasticsearch.xpack.ql.index.IndexResolver.lambda$resolveAsMergedMapping$3(IndexResolver.java:288)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
        at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:91)
        at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:158)
        at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:151)
        at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.lambda$doExecute$0(TransportFieldCapabilitiesAction.java:88)
        at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:101)
        at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:97)
        at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:91)
        at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:158)
        at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:151)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:261)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:247)
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1103)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1181)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1161)
        at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:54)
        at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:47)
        at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:30)
        at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:58)
        at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:691)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by palesz** [comment]
Detailed description of the root cause can be found here: https://github.com/elastic/elasticsearch/pull/63710#issuecomment-721236168
