### ISSUE TITLE
SQL: JDBC error when setting date related query params

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#56084]
```
@Test
public void testEsJdbcPreparedStatetement() {
    try (Connection connection = DriverManager.getConnection("jdbc:es://localhost:9200/", "elastic", "elastic")) {

        try(PreparedStatement preparedStatement = connection.prepareStatement("SELECT emp_no FROM test_emp WHERE birth_date = ?")) {

            java.sql.Date ts = new java.sql.Date(1510348539123L);
            preparedStatement.setObject(1, ts);
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                while (resultSet.next()) {
                    System.out.println(resultSet.getInt(1));
                }
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
```

results in:
```
java.lang.IllegalArgumentException: cannot write time value xcontent for unknown value of type class java.util.Date

	at org.elasticsearch.common.xcontent.XContentBuilder.timeValue(XContentBuilder.java:751)
	at org.elasticsearch.common.xcontent.XContentBuilder.unknownValue(XContentBuilder.java:815)
	at org.elasticsearch.common.xcontent.XContentBuilder.value(XContentBuilder.java:804)
	at org.elasticsearch.common.xcontent.XContentBuilder.field(XContentBuilder.java:789)
	at org.elasticsearch.xpack.sql.proto.SqlTypedParamValue.toXContent(SqlTypedParamValue.java:50)
	at org.elasticsearch.xpack.sql.proto.SqlQueryRequest.toXContent(SqlQueryRequest.java:186)
	at org.elasticsearch.xpack.sql.client.HttpClient.toXContent(HttpClient.java:148)
	at org.elasticsearch.xpack.sql.client.HttpClient.post(HttpClient.java:101)
	at org.elasticsearch.xpack.sql.client.HttpClient.query(HttpClient.java:81)
	at org.elasticsearch.xpack.sql.jdbc.JdbcHttpClient.query(JdbcHttpClient.java:69)
	at org.elasticsearch.xpack.sql.jdbc.JdbcStatement.initResultSet(JdbcStatement.java:160)
	at org.elasticsearch.xpack.sql.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:60)
	at PostgresJdbcTest.testEsJdbcPreparedStatetement(PostgresJdbcTest.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
	Suppressed: java.lang.IllegalStateException: Failed to close the XContentBuilder
		at org.elasticsearch.common.xcontent.XContentBuilder.close(XContentBuilder.java:1011)
		at org.elasticsearch.xpack.sql.client.HttpClient.toXContent(HttpClient.java:144)
		... 28 more
	Caused by: java.io.IOException: Unclosed object or array found
		at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.close(JsonXContentGenerator.java:469)
		at org.elasticsearch.common.xcontent.XContentBuilder.close(XContentBuilder.java:1009)
		... 29 more
```

**Comment by RikSagara** [comment]
Hi! Can I do this?

**Comment by matriv** [comment]
`master` : f8d8e971bd2c85fa4aea44b5b3ba0cdcc950a4ed
`7.x` : 575cafb8da51ba64be28c5c00d72ba3cc08194eb
`7.8` : 04ebd8253d4bf451d416e3ddacd374cf0e500001
`7.7` : 5198901e930d29c9c59d5cf2a7c6a102375147ea
