### ISSUE TITLE
[CI] AsyncSearchActionIT.testUpdateStoreKeepAlive failed on master due in in-flight contexts

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#56132]
The error was:

```
java.lang.AssertionError: There are still [1] in-flight contexts. The first one's creation site is listed as the cause of this exception.
	at __randomizedtesting.SeedInfo.seed([962F5B720CD25809:AF929F0EE181E762]:0)
	at org.elasticsearch.search.MockSearchService.assertNoInFlightContext(MockSearchService.java:52)
	at org.elasticsearch.test.ESTestCase.lambda$ensureAllSearchContextsReleased$7(ESTestCase.java:507)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:892)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:865)
	at org.elasticsearch.test.ESTestCase.ensureAllSearchContextsReleased(ESTestCase.java:507)
	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2036)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.AssertionError: There are still [1] in-flight contexts. The first one's creation site is listed as the cause of this exception.
		at org.elasticsearch.search.MockSearchService.assertNoInFlightContext(MockSearchService.java:52)
		at org.elasticsearch.test.ESTestCase.lambda$ensureAllSearchContextsReleased$7(ESTestCase.java:507)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:880)
		... 38 more
	Caused by: java.lang.RuntimeException: [ddsfvQyoTU2wLvEXTrBL9A][.async-search][0]scroll=[5m] query=[expiration_time:[-9223372036854775808 TO 1588607169435]]
		at org.elasticsearch.search.MockSearchService.addActiveContext(MockSearchService.java:60)
		at org.elasticsearch.search.MockSearchService.putContext(MockSearchService.java:78)
		at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:635)
		at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:428)
		at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:395)
		at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:411)
		at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)
		at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:691)
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		... 1 more
	Suppressed: java.lang.AssertionError: There are still [1] in-flight contexts. The first one's creation site is listed as the cause of this exception.
		at org.elasticsearch.search.MockSearchService.assertNoInFlightContext(MockSearchService.java:52)
		at org.elasticsearch.test.ESTestCase.lambda$ensureAllSearchContextsReleased$7(ESTestCase.java:507)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:880)
		... 38 more
```

The build is at: https://gradle-enterprise.elastic.co/s/e3cdtmudlnyqe

I was not able to reproduce the error with 

```
./gradlew ':x-pack:plugin:async-search:internalClusterTest' --tests "org.elasticsearch.xpack.search.AsyncSearchActionIT.testUpdateStoreKeepAlive" -Dtests.seed=962F5B720CD25809 -Dtests.security.manager=true -Dtests.locale=bg -Dtests.timezone=Australia/Eucla -Dcompiler.java=14 -Druntime.java=11
```

**Comment by jimczi** [comment]
Thanks @dakrone, this test fail for the same reason than https://github.com/elastic/elasticsearch/issues/55988 so I am closing as duplicate.
