### ISSUE TITLE
SearchableSnapshotDirectoryTests.testIndexSearcher can fail with assertion error

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#56233]
The failure consistently reproduces for me. Command:
```
./gradlew ':x-pack:plugin:searchable-snapshots:test' \
  --tests "org.elasticsearch.index.store.SearchableSnapshotDirectoryTests.testIndexSearcher" \
  -Dtests.seed=4ADEC076A04B379C -Dtests.security.manager=true -Dtests.locale=fr-FR \
  -Dtests.timezone=America/Hermosillo -Dcompiler.java=14 -Druntime.java=11
```

Build scan: https://gradle-enterprise.elastic.co/s/gee7fullo3xhm

Relevant excerpt from the logs:
```
java.lang.AssertionError: current thread [Thread[LuceneTestCase-1-thread-2,5,TGRP-SearchableSnapshotDirectoryTests]] may not read [name: __UmWBMwYMTo6pUM37x8biLg, numberOfParts: 1, partSize: 868b, partBytes: 868, metadata: name [_0_Lucene84_1.doc], length [682], checksum [1pi9tjs], writtenBy [8.5.1]]
    at org.elasticsearch.index.store.BaseSearchableSnapshotIndexInput.assertCurrentThreadMayAccessBlobStore(BaseSearchableSnapshotIndexInput.java:148)
    at org.elasticsearch.index.store.direct.DirectBlobContainerIndexInput.openBlobStream(DirectBlobContainerIndexInput.java:343)
    at org.elasticsearch.index.store.direct.DirectBlobContainerIndexInput.readInternalBytes(DirectBlobContainerIndexInput.java:133)
    at org.elasticsearch.index.store.direct.DirectBlobContainerIndexInput.readInternal(DirectBlobContainerIndexInput.java:105)
```

**Comment by jtibshirani** [comment]
Muted in eddbc784e15bf22792e7369b166b4b0c6bffa1c5.
