### ISSUE TITLE
ClassificationIT can fail with assertion error

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#56240]
The failure doesn't reproduce for me. Command:
```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testDependentVariableCardinalityTooHighButWithQueryMakesItWithinRange" \
  -Dtests.seed=8AC525342B38C5D2 \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=ja-JP \
  -Dtests.timezone=Kwajalein \
  -Dcompiler.java=14 \
  -Druntime.java=11
```

Build scan: https://gradle-enterprise.elastic.co/s/34pg7bs4j4fve

Relevant excerpt from the logs:
```
java.lang.AssertionError: progress is complete: [{"phase":"reindexing","progress_percent":100}, {"phase":"loading_data","progress_percent":100}, {"phase":"feature_selection","progress_percent":100}, {"phase":"coarse_parameter_search","progress_percent":100}, {"phase":"fine_tuning_parameters","progress_percent":100}, {"phase":"final_training","progress_percent":0}, {"phase":"writing_results","progress_percent":100}]
    Expected: is <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([8AC525342B38C5D2:18A81666D35ECE57]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertProgressComplete(MlNativeDataFrameAnalyticsIntegTestCase.java:211)
        at org.elasticsearch.xpack.ml.integration.ClassificationIT.testDependentVariableCardinalityTooHighButWithQueryMakesItWithinRange(ClassificationIT.java:396)
```

**Comment by jtibshirani** [comment]
Muted the test:
* f8221b279afc0e48cc085dafed94f0ae0496a1b9 (master)
* 63062ec7bd6c4d5160f650c046b7f910acbda58f (7.x)

**Comment by dimitris-athanasiou** [comment]
This test failure happened in release-tests which were using a snapshot of ml-cpp which was just before this problem was fixed. In particular, we can see in the logs:

```
[2020-05-05T19:23:53,534][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [integTest-2] [controller/402273] [Main.cc@110] controller (64 bit): Version 8.0.0 (Build cd335f9e1eedad) Copyright (c) 2020 Elasticsearch BV
```

and the same appears for the other 2 nodes. This tells us ml-cpp was build from commit cd335f9e1eedad which was just before 731781b476ebb479281500fc8b505abe34eeca64 where this issue was fixed.

A new non-snapshot build of ml-cpp has been kicked off. I'll unmute the tests as soon as that completes.
