### ISSUE TITLE
80_transform_jobs_crud can fail with a null pointer exception

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#56250]
It looks like `Transform#transformTaskNodes` can sometimes produce a null node ID, which causes a null pointer exception in `DiscoveryNodes.resolveNodes`.

Reproduce line:
```
./gradlew ':x-pack:qa:rolling-upgrade:v7.8.0#oneThirdUpgradedTest' --tests "org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.test {p0=mixed_cluster/80_transform_jobs_crud/Test GET, start, and stop old cluster batch transforms}" \
  -Dtests.seed=5F2B3A83763FEB92 \
  -Dtests.security.manager=true \
  -Dtests.locale=ga-IE \
  -Dtests.timezone=America/Phoenix \
  -Dcompiler.java=14 \
  -Druntime.java=11 \
  -Dtests.rest.suite=mixed_cluster
```

Build scan: https://gradle-enterprise.elastic.co/s/uwebhlksubme2

Relevant excerpt from logs:
```
  1> Caused by: java.lang.NullPointerException: Cannot invoke \"String.equals(Object)\" because \"nodeId\" is null
  1> 	at org.elasticsearch.cluster.node.DiscoveryNodes.resolveNodes(DiscoveryNodes.java:341)
  1> 	at org.elasticsearch.action.support.tasks.TransportTasksAction.resolveNodes(TransportTasksAction.java:159)
  1> 	at org.elasticsearch.action.support.tasks.TransportTasksAction$AsyncAction.<init>(TransportTasksAction.java:230)
  1> 	at org.elasticsearch.action.support.tasks.TransportTasksAction$AsyncAction.<init>(TransportTasksAction.java:215)
  1> 	at org.elasticsearch.action.support.tasks.TransportTasksAction.doExecute(TransportTasksAction.java:96)
  1> 	at org.elasticsearch.xpack.transform.action.TransportStopTransformAction.lambda$doExecute$2(TransportStopTransformAction.java:188)
  1> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
  1> 	at 
```

**Comment by jtibshirani** [comment]
Some more failures popped up that may be related:
* https://gradle-enterprise.elastic.co/s/k7dlk6gw223ke
* https://gradle-enterprise.elastic.co/s/jvgazqfk2lkze

**Comment by jtibshirani** [comment]
I muted the suite `80_transform_jobs_crud` in be5f40777557bc7e762271512f5f3add5fa5e83f.

**Comment by hendrikmuhs** [comment]
I am sure this is #56238. I took a look at build-stats: This bug never appeared on 7.x, the breaks on 7.x are due to #56196 (which happened/got muted 8 hours earlier) and breaks caused by an incomplete mute.
