### ISSUE TITLE
RegressionIt.testWithOnlyTrainingRowsAndTrainingPercentIsFifty failures

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#56282]
Two failures today with 
```
org.elasticsearch.xpack.ml.integration.RegressionIT > testWithOnlyTrainingRowsAndTrainingPercentIsFifty FAILED
    java.lang.AssertionError: progress is complete: [{"phase":"reindexing","progress_percent":100}, {"phase":"loading_data","progress_percent":100}, {"phase":"feature_selection","progress_percent":1}, {"phase":"coarse_parameter_search","progress_percent":100}, {"phase":"fine_tuning_parameters","progress_percent":100}, {"phase":"final_training","progress_percent":100}, {"phase":"writing_results","progress_percent":100}]
    Expected: is <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([5682D617C3B794D:B94D34F14C44ACB8]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertProgressComplete(MlNativeDataFrameAnalyticsIntegTestCase.java:211)
        at org.elasticsearch.xpack.ml.integration.RegressionIT.testWithOnlyTrainingRowsAndTrainingPercentIsFifty(RegressionIT.java:219)
REPRODUCE WITH: gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testWithOnlyTrainingRowsAndTrainingPercentIsFifty" -Dtests.seed=5682D617C3B794D -Dtests.security.manager=true -Dtests.locale=ru -Dtests.timezone=Asia/Baku -Dcompiler.java=14 -Druntime.java=11
```

example: https://gradle-enterprise.elastic.co/s/vbdxaoi5nsyyo

I will mute this test.

**Comment by andreidan** [comment]
Another occurrence in https://gradle-enterprise.elastic.co/s/lbbhk6fuu73m6
