### ISSUE TITLE
IndicesClusterStateService#removeIndices can trip assertion

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#56298]
I've seen builds recently where an assert is violated is `IndicesClusterStateService`:

```
» ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [asyncIntegTest-0] fatal error in thread [elasticsearch[asyncIntegTest-0][clusterApplierService#updateTask][T#1]], exiting
»  java.lang.AssertionError: index [log-000001/UaYMI02vQ6mkh_JRN9y4hQ] does not exist in the cluster state, it should either have been deleted or the cluster must be new
»  	at org.elasticsearch.indices.cluster.IndicesClusterStateService.removeIndices(IndicesClusterStateService.java:382) ~[elasticsearch-7.8.0-SNAPSHOT.jar:7.8.0-SNAPSHOT]
»  	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:238) ~[elasticsearch-7.8.0-SNAPSHOT.jar:7.8.0-SNAPSHOT]
»  	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$5(ClusterApplierService.java:517) ~[elasticsearch-7.8.0-SNAPSHOT.jar:7.8.0-SNAPSHOT]
»  	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_241]
»  	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:514) ~[elasticsearch-7.8.0-SNAPSHOT.jar:7.8.0-SNAPSHOT]
»  	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:485) ~[elasticsearch-7.8.0-SNAPSHOT.jar:7.8.0-SNAPSHOT]
```

Example build scan: https://gradle-enterprise.elastic.co/s/5s7skdig5hk46

I wanted to raise this in case it's concerning and needs investigation.

**Comment by original-brownbear** [comment]
The problem here is the new `TransportSimulateIndexTemplateAction` that adds an index to the `IndicesService` that isn't properly tracked in the cluster state and thus trips the assertion about being properly tracked in the cluster state. I was able to reproduce this reliably by writing a `EsIntegTestCase` that concurrently deletes indices and runs the simulate action ... I'm looking into how we can solve this better.
