### ISSUE TITLE
Nested terms aggregation with sort by cardinality subaggregation fails with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#56319]
**Elasticsearch version**: `7.6.2`

**JVM version**: `bundled`

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

Adding the the following IT test in https://github.com/elastic/elasticsearch/blob/master/server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/metrics/CardinalityIT.java reproduces the issue:

```
    /**
     * Reproducing bug when using terms aggregation with a cardinality subaggregation and the cardinality subaggregation
     * is used for sorting the terms buckets.
     */
    public void testTermsAggWithSortByCardinalitySubAgg() {
        final AcknowledgedResponse templateResponse = client().admin().indices()
            .putTemplate(new PutIndexTemplateRequest().mapping("test_idx",
                "{\"test_idx\": {\n" +
                    " \"properties\": {\n" +
                    " \"tag\": {\n" +
                    " \"type\": \"keyword\" \n" +
                    " }\n" +
                    " }\n" +
                    " }\n" +
                    "}", XContentType.JSON)
                .patterns(Collections.singletonList("test_idx*"))
                .name("template_test")
                .settings(Collections.singletonMap("number_of_shards", "1")))
            .actionGet();
        assertTrue(templateResponse.isAcknowledged());
        assertEquals(RestStatus.CREATED, client()
            .prepareIndex("test_idx", "_doc", "id1")
            .setSource("{ }", XContentType.JSON)
            .setRouting("1")
            .execute().actionGet().status());
        assertEquals(RestStatus.CREATED, client()
            .prepareIndex("test_idx", "_doc", "id2")
            .setSource("{ \"tag\": \"tag1\"}", XContentType.JSON)
            .setRouting("1")
            .execute().actionGet().status());
        assertEquals(RestStatus.CREATED, client()
            .prepareIndex("test_idx", "_doc", "id3")
            .setSource("{ }", XContentType.JSON)
            .setRouting("1")
            .execute().actionGet().status());
        refresh();

        AggregationBuilder aggregationBuilder = AggregationBuilders.terms("term")
            .field("_id")
            .size(1)
            .order(BucketOrder.aggregation("card", true))
            .subAggregation(AggregationBuilders.cardinality("card").field("tag").precisionThreshold(100));

        SearchResponse response = client().prepareSearch("test_idx").setSize(0).
            addAggregation(aggregationBuilder).
            execute().
            actionGet();

        assertEquals(0, response.getFailedShards());
    }
}
```

Producing the following stack trace:

```
java.lang.AssertionError: Had: [shard [[-L61MCGYS6GrI7ffJI_Pwg][idx][2]], 
  reason [RemoteTransportException[[node_s0][127.0.0.1:37501][indices:data/read/search[phase/query]]]; 
  nested: ArrayIndexOutOfBoundsException[Index 2304 out of bounds for length 2304]; ],
  cause [java.lang.ArrayIndexOutOfBoundsException: Index 2304 out of bounds for length 2304
          at org.elasticsearch.common.util.ByteUtils.readIntLE(ByteUtils.java:72)
          at org.elasticsearch.search.aggregations.metrics.cardinality.HyperLogLogPlusPlus$Hashset.get(HyperLogLogPlusPlus.java:490)
          at org.elasticsearch.search.aggregations.metrics.cardinality.HyperLogLogPlusPlus$Hashset.recomputedSize(HyperLogLogPlusPlus.java:501)
          at org.elasticsearch.search.aggregations.metrics.cardinality.HyperLogLogPlusPlus$Hashset.size(HyperLogLogPlusPlus.java:514)
          at org.elasticsearch.search.aggregations.metrics.cardinality.HyperLogLogPlusPlus.cardinalityLc(HyperLogLogPlusPlus.java:284)
          at org.elasticsearch.search.aggregations.metrics.cardinality.HyperLogLogPlusPlus.cardinality(HyperLogLogPlusPlus.java:276)
          at org.elasticsearch.search.aggregations.metrics.cardinality.CardinalityAggregator.metric(CardinalityAggregator.java:135)
          at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregator.lambda$bucketComparator$2(TermsAggregator.java:279)
          at org.elasticsearch.search.aggregations.InternalOrder$CompoundOrder$CompoundOrderComparator.compare(InternalOrder.java:274)
          at org.elasticsearch.search.aggregations.InternalOrder$CompoundOrder$CompoundOrderComparator.compare(InternalOrder.java:254)
          at org.elasticsearch.search.aggregations.bucket.terms.BucketPriorityQueue.lessThan(BucketPriorityQueue.java:36)
          at org.elasticsearch.search.aggregations.bucket.terms.BucketPriorityQueue.lessThan(BucketPriorityQueue.java:25)
          at org.apache.lucene.util.PriorityQueue.upHeap(PriorityQueue.java:254)
          at org.apache.lucene.util.PriorityQueue.add(PriorityQueue.java:131)
          at org.apache.lucene.util.PriorityQueue.insertWithOverflow(PriorityQueue.java:147)
          at org.elasticsearch.search.aggregations.bucket.terms.StringTermsAggregator.buildAggregation(StringTermsAggregator.java:146)
          at org.elasticsearch.search.aggregations.AggregationPhase.execute(AggregationPhase.java:130)
          at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:120)
          at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:350)
          at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:394)
          at org.elasticsearch.search.SearchService.access$100(SearchService.java:126)
          at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:359)
          at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:355)
          at org.elasticsearch.search.SearchService$4.doRun(SearchService.java:1114)
          at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
          at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41)
          at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751)
          at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
```

Interesting enough using the equivalent in Console (REST client) doesn't reproduce:

<details><summary>Console snippet</summary>

```
DELETE idx

POST _template/template_test?include_type_name=true
{
  "index_patterns": ["idx*"],
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0
  },
  "mappings": {
    "_doc": {
      "properties": {
        "tag": {
          "type": "keyword"
        }
      }
    }
  }
}

PUT /idx/_doc/id1?routing=3
{}
 
PUT /idx/_doc/id2?routing=3
{
  "tag": "tag1"
}

PUT /idx/_doc/id3?routing=3
{}

POST idx/_refresh

GET idx/_search?search_type=dfs_query_then_fetch
{
  "aggregations": {
    "term": {
      "terms": {
        "field": "_id",
        "size": 1,
        "min_doc_count": 1,
        "shard_min_doc_count": 0,
        "show_term_doc_count_error": false,
        "order": [
          {
            "card": "asc"
          },
          {
            "_key": "asc"
          }
        ]
      },
      "aggregations": {
        "card": {
          "cardinality": {
            "field": "tag",
            "precision_threshold": 100
          }
        }
      }
    }
  }
}
```

</details>

Also using the HLRC by adding a test case on top of doesn't reproduce the issue either:

<details><summary>HLRC test method</summary>

```
 @Test
    void nestedAggsIssue() throws Exception {
        try (RestHighLevelClient client = new RestHighLevelClient(
                RestClient.builder(HttpHost.create("http://localhost:9200")))) {

            MainResponse info = client.info(RequestOptions.DEFAULT);
            String version = info.getVersion().getNumber();
            System.out.println("version = " + version);

            AcknowledgedResponse deleteIndexResponse = client.indices().delete(new DeleteIndexRequest("idx"), RequestOptions.DEFAULT);
            assertTrue(deleteIndexResponse.isAcknowledged());

            PutIndexTemplateRequest request = new PutIndexTemplateRequest("template_test");
            request.patterns(Collections.singletonList("idx*"));
            request.settings(Settings.builder()
                    .put("index.number_of_shards", 1));
            request.mapping(
                    "idx",
                    "{\n" +
                            " \"properties\": {\n" +
                            " \"tag\": {\n" +
                            " \"type\": \"keyword\" \n" +
                            " }\n" +
                            " }\n" +
                            " }\n" +
                            "}", XContentType.JSON);
            AcknowledgedResponse putTemplateResponse = client.indices().putTemplate(request, RequestOptions.DEFAULT);

            assertTrue(putTemplateResponse.isAcknowledged());

            client.index(new IndexRequest("idx","_doc", "id1")
                            .source("{ }", XContentType.JSON)
                            .routing("3"),
                    RequestOptions.DEFAULT);

            assertEquals(RestStatus.CREATED, client.index(new IndexRequest("idx","_doc", "id2")
                            .source("{ \"tag\": \"tag1\"}", XContentType.JSON)
                            .routing("3"),
                    RequestOptions.DEFAULT).status());

            assertEquals(RestStatus.CREATED, client.index(new IndexRequest("idx","_doc", "id3")
                            .source("{ }", XContentType.JSON)
                            .routing("3"),
                    RequestOptions.DEFAULT).status());

            client.indices().refresh(new RefreshRequest("idx"), RequestOptions.DEFAULT);

            AggregationBuilder aggregationBuilder = AggregationBuilders.terms("term").
                    field("_id").
                    size(1).
                    order(BucketOrder.aggregation("card", true)).
                    subAggregation(AggregationBuilders.cardinality("card").field("tag").precisionThreshold(100));

            SearchResponse response = client.search(new SearchRequest("idx").source(
                    new SearchSourceBuilder().aggregation(aggregationBuilder)),
                    RequestOptions.DEFAULT);

            assertEquals(0, response.getFailedShards(), "Had: " + Arrays.toString(response.getShardFailures()));
        }
    }
```
</details

**Comment by csoulios** [comment]
We discussed this issue at our team meeting. We will check if this issue is still reproducible

**Comment by csoulios** [comment]
This issue can not be reproduced in `8.x` or `7.17` branches
