### ISSUE TITLE
[CI] DateUtilsTests.testTimezoneIds

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#56343]
I believe this is introduced by https://github.com/elastic/elasticsearch/pull/49748

**Build scan**:
 https://gradle-enterprise.elastic.co/s/fuzppmjzp2y2q

**Repro line**:
./gradlew ':server:unitTest' -Dtests.seed=37A37732AFD8A200 -Dtests.class=org.elasticsearch.common.time.DateUtilsTests -Dtests.method="testTimezoneIds" -Dtests.security.manager=true -Dtests.locale=es-PR -Dtests.timezone=Chile/Continental -Dcompiler.java=12 -Druntime.java=12

**Reproduces locally?**:
Yes

**Applicable branches**:
6.8

**Failure excerpt**:
```
ERROR   0.36s J4  | DateUtilsTests.testTimezoneIds <<< FAILURES!
Throwable #1: java.time.zone.ZoneRulesException: Unknown time-zone ID: Asia/Qostanay
at __randomizedtesting.SeedInfo.seed([37A37732AFD8A200:EB462AA8E274EB26]:0)
at java.base/java.time.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:279)
at java.base/java.time.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:234)
at java.base/java.time.ZoneRegion.ofId(ZoneRegion.java:120)
at java.base/java.time.ZoneId.of(ZoneId.java:408)
at java.base/java.time.ZoneId.of(ZoneId.java:356)
at org.elasticsearch.common.time.DateUtils.dateTimeZoneToZoneId(DateUtils.java:74)
at org.elasticsearch.common.time.DateUtilsTests.testTimezoneIds(DateUtilsTests.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at java.base/java.lang.Thread.run(Thread.java:835)7
```

**Comment by pgomulka** [comment]
closed by https://github.com/elastic/elasticsearch/pull/58551
