### ISSUE TITLE
[ML] MachineLearningIT.testDeleteDataFrameAnalyticsConfig failure

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#56416]
**Build scan**: https://gradle-enterprise.elastic.co/s/nd6zd5gb7t2wc

**Repro line**: ./gradlew ':client:rest-high-level:asyncIntegTestRunner' --tests "org.elasticsearch.client.MachineLearningIT.testDeleteDataFrameAnalyticsConfig" -Dtests.seed=EA819866C20BAB7B

**Reproduces locally?**: yes

**Applicable branches**: master, 7.x

**Failure excerpt**: 

```
Exception: org.elasticsearch.ElasticsearchStatusExceptionElasticsearch exception [type=resource_not_found_exception, reason=No known data frame analytics with id [delete-test-config]]
at __randomizedtesting.SeedInfo.seed([EA819866C20BAB7B:5E0260FBBE5CC7C0]:0)
at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177)
at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1897)
at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1867)
at org.elasticsearch.client.RestHighLevelClient$1.onFailure(RestHighLevelClient.java:1783)
at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:598)
at org.elasticsearch.client.RestClient$1.completed(RestClient.java:343)
at org.elasticsearch.client.RestClient$1.completed(RestClient.java:327)
at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)
at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448)
```

**Comment by dimitris-athanasiou** [comment]
Fixed in https://github.com/elastic/elasticsearch/pull/56421
