### ISSUE TITLE
_shrink fails with older indices including default mapping

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#56671]
**Elasticsearch version** : 7.x

**Description of the problem including expected versus actual behavior**:

Unable to `_shrink` an index from an older version that has both a `doc` and a [default mapping](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/default-mapping.html).

The error message produced is:

```
[Rejecting mapping update to [shrunk_index] as the final mapping would have more than 1 type: [doc, _default_]]`
```

The shrink index always has the same `index.version_created` as the original index, so it should be allowed to contain mappings that work on that version.

**Steps to reproduce**:

 1. Start Elasticsearch 6.8.8
    For example, in a new directory download this [docker-compose.yml](https://gist.github.com/dliappis/ff8ab147a22e1bd6f8860cd602e543c8#file-docker-compose-yml) and `export ELASTIC_VERSION=6.8.8 && docker-compose up`

 2. Create `twitter` index including default mapping: (for example using the DEV console by connecting to `localhost:5601`)

```
PUT twitter
{
  "mappings": {
    "_default_": {
      "properties": {
        "name": { "type": "text" }
      }
    },
    "doc": {
      "properties": {
        "name": { "type": "text" },
        "email": { "type": "keyword" }      
      }
    }
  }
}

PUT twitter/doc/id1
{
  "name": "foo",
  "email": "foo@foo.com"
}
```
3. Upgrade to Elasticsearch 7.6.2
    For example using the docker-compose file from 1.:
    ```
    docker-compose down  # this will leave the volume
    export ELASTIC_VERSION=7.6.2
    docker-compose up
    ```

4. Set `twitter` index to read-only:

```
PUT /twitter/_settings
{
  "settings": {
    "index.routing.allocation.require._name": "<replace_with_your_node_name>",
    "index.blocks.write": true
  }
}
```

5. Execute `_shrink` API:

`POST /twitter/_shrink/shrunk-twitter-index`

**Provide logs (if relevant)**:

After executing 5. we get:

```
{"type": "server", "timestamp": "2020-05-13T09:51:33,619Z", "level": "INFO", "component": "o.e.c.m.MetaDataCreateIndexService", "cluster.name": "ESCluster", "node.name": "ca6e3449dd8b", "message": "[shrunk-twitter-index] creating index, cause [shrink_index], templates [], shards [1]/[1], mappings []", "cluster.uuid": "nxxf_1AGRPW9BfQA-geqQw", "node.id": "6fWWz3CbSSegrob5KZKn7w"  }
{"type": "server", "timestamp": "2020-05-13T09:51:33,696Z", "level": "INFO", "component": "o.e.c.m.MetaDataMappingService", "cluster.name": "ESCluster", "node.name": "ca6e3449dd8b", "message": "[shrunk-twitter-index/UsHRPcOPQuOB6E5KAIJ45A] create_mapping [doc]", "cluster.uuid": "nxxf_1AGRPW9BfQA-geqQw", "node.id": "6fWWz3CbSSegrob5KZKn7w"  }
{"type": "server", "timestamp": "2020-05-13T09:51:33,746Z", "level": "DEBUG", "component": "o.e.a.a.i.m.p.TransportPutMappingAction", "cluster.name": "ESCluster", "node.name": "ca6e3449dd8b", "message": "failed to put mappings on indices [[[shrunk-twitter-index/UsHRPcOPQuOB6E5KAIJ45A]]], type [_default_]", "cluster.uuid": "nxxf_1AGRPW9BfQA-geqQw", "node.id": "6fWWz3CbSSegrob5KZKn7w" ,
"stacktrace": ["java.lang.IllegalArgumentException: Rejecting mapping update to [shrunk-twitter-index] as the final mapping would have more than 1 type: [doc, _default_]",
"at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:272) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:238) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:702) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:324) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:219) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.6.2.jar:7.6.2]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",
"at java.lang.Thread.run(Thread.java:830) [?:?]"] }
{"type": "server", "timestamp": "2020-05-13T09:51:33,752Z", "level": "WARN", "component": "o.e.i.c.IndicesClusterStateService", "cluster.name": "ESCluster", "node.name": "ca6e3449dd8b", "message": "[shrunk-twitter-index][0] marking and sending shard failed due to [failed recovery]", "cluster.uuid": "nxxf_1AGRPW9BfQA-geqQw", "node.id": "6fWWz3CbSSegrob5KZKn7w" ,
"stacktrace": ["org.elasticsearch.indices.recovery.RecoveryFailedException: [shrunk-twitter-index][0]: Recovery failed on {ca6e3449dd8b}{6fWWz3CbSSegrob5KZKn7w}{owb2NMbnSKeLxGBWuHp-xg}{192.168.80.2}{192.168.80.2:9300}{dilm}{ml.machine_memory=6501097472, xpack.installed=true, ml.max_open_jobs=20}",
"at org.elasticsearch.index.shard.IndexShard.lambda$executeRecovery$21(IndexShard.java:2633) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:71) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:88) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:680) [elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) [elasticsearch-7.6.2.jar:7.6.2]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",
"at java.lang.Thread.run(Thread.java:830) [?:?]",
"Caused by: java.lang.IllegalArgumentException: Rejecting mapping update to [shrunk-twitter-index] as the final mapping would have more than 1 type: [doc, _default_]",
"at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:272) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:238) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:702) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:324) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:219) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) ~[elasticsearch-7.6.2.jar:7.6.2]",
"at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) ~[elasticsearch-7.6.2.jar:7.6.2]",
"... 3 more"] }
```

Teardown the test environment using `docker-compose down -v`.

**Comment by dliappis** [comment]
cc @jtibshirani

**Comment by jtibshirani** [comment]
Here's my understanding of what causes the failure:
* We create the new shrink index, and copy over the mappings from the original index. By chance, we first add the doc mapping, which completes successfully (as expected).
* Then we try to add the default mapping. This fails because on 7.x, we check that new indices do not contain default mappings. The error message is a little confusing here, but it's really complaining about trying to add default mappings.

As an aside, we don't encounter this error if `_default_` happens to get added first, then `doc`. The fact that this works is a bit accidental, I don't think we explicitly thought through this case.

**Comment by Venorcis** [comment]
We're experiencing this issue too, completely preventing us from shrinking 'old' indexes.

**Comment by javanna** [comment]
default mapping was deprecated in 7.x and removed in 8.x. I lean towards closing this issue, as it does not seem worthwhile to fix this on 7.x at this point.
