### ISSUE TITLE
[CI] TaskManagerTests#testTrackingChannelTask 

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#56746]
**Build scan**: https://gradle-enterprise.elastic.co/s/hj26o74ec2b3a/tests/:server:test/org.elasticsearch.tasks.TaskManagerTests/testTrackingChannelTask

**Repro line**: ./gradlew ':server:test' --tests "org.elasticsearch.tasks.TaskManagerTests.testTrackingChannelTask" -Dtests.seed=1631CC2C8CC4FEF9 -Dtests.security.manager=true -Dtests.locale=zh -Dtests.timezone=Asia/Hebron -Dcompiler.java=14 -Druntime.java=11

**Reproduces locally?**: yes

**Applicable branches**: master

This is a new test introduced via #56620
Failed a number of times: https://build-stats.elastic.co/goto/7a90340f7200a870f56b5ff9ebad49e2

**Failure excerpt**:

```
Exception: java.lang.AssertionError
Expected: <[request-73, request-119, request-66, request-137, request-29, request-112, request-1, request-19, request-7, request-49, request-58, request-71, request-101, request-42, request-129, request-113, request-126, request-81, request-69, request-102, request-38, request-107, request-15, request-26, request-122, request-56, request-133, request-90, request-84, request-17, request-125, request-0, request-20, request-74, request-82, request-131, request-10, request-27, request-93, request-25, request-72, request-98, request-48, request-100, request-54, request-94, request-4, request-46, request-76, request-134, request-52, request-64, request-39, request-123, request-37, request-79, request-9, request-115, request-83, request-41, request-117, request-22, request-60, request-78, request-35, request-92, request-127, request-130, request-89, request-104, request-114, request-77, request-138, request-6, request-67, request-110, request-120, request-70, request-30, request-55, request-61, request-5, request-51, request-24, request-136, request-14, request-91, request-116, request-106, request-34, request-103, request-18, request-32, request-109, request-96, request-105, request-86, request-12, request-132, request-33, request-111, request-36, request-95, request-8, request-53, request-3, request-97, request-62, request-16, request-44, request-31, request-59, request-108, request-40, request-47, request-99, request-128, request-68, request-88, request-80, request-135, request-85, request-63, request-57, request-87, request-124, request-118, request-43, request-50, request-65, request-45, request-121, request-23, request-139]>
     but: was <[request-73, request-119, request-66, request-137, request-29, request-112, request-1, request-19, request-7, request-49, request-58, request-71, request-101, request-42, request-129, request-113, request-126, request-81, request-69, request-102, request-38, request-107, request-26, request-122, request-56, request-133, request-90, request-84, request-17, request-125, request-0, request-20, request-74, request-82, request-131, request-10, request-27, request-93, request-25, request-72, request-98, request-48, request-100, request-54, request-94, request-4, request-46, request-76, request-134, request-52, request-64, request-39, request-123, request-37, request-79, request-9, request-115, request-83, request-41, request-117, request-22, request-60, request-78, request-35, request-92, request-127, request-130, request-89, request-104, request-114, request-77, request-138, request-6, request-67, request-110, request-120, request-70, request-30, request-55, request-61, request-5, request-51, request-24, request-136, request-14, request-91, request-116, request-106, request-34, request-103, request-18, request-32, request-109, request-96, request-105, request-86, request-12, request-132, request-33, request-111, request-36, request-95, request-8, request-53, request-3, request-97, request-62, request-16, request-44, request-31, request-59, request-108, request-40, request-47, request-99, request-128, request-68, request-88, request-80, request-135, request-85, request-63, request-57, request-87, request-124, request-118, request-43, request-50, request-65, request-45, request-121, request-23, request-139]>
at __randomizedtesting.SeedInfo.seed([1631CC2C8CC4FEF9:81E3CD5551076F5F]:0)
•••
at org.elasticsearch.tasks.TaskManagerTests.lambda$testTrackingChannelTask$2(TaskManagerTests.java:119)
•••
at org.elasticsearch.tasks.TaskManagerTests.testTrackingChannelTask(TaskManagerTests.java:119)
```

**Comment by martijnvg** [comment]
@dnhatn You may want to look at this failure, since this test was introduced in #56620.

**Comment by DaveCTurner** [comment]
Muted in 2eae098cf01.

**Comment by DaveCTurner** [comment]
Muted on `7.x` in f0c2c255279.

**Comment by dnhatn** [comment]
Thanks Martijn. I've opened https://github.com/elastic/elasticsearch/pull/56775 to address this failure.

**Comment by dnhatn** [comment]
@nik9000 kindly pinged me on a new failure: https://gradle-enterprise.elastic.co/s/v7ognbjutfjfs/tests/:server:test/org.elasticsearch.tasks.TaskManagerTests/testTrackingChannelTask#1.

**Comment by dnhatn** [comment]
Another instance https://gradle-enterprise.elastic.co/s/imsdzll2akwzc

**Comment by nik9000** [comment]
I've re-muted the test while @dnhatn works on this!
