### ISSUE TITLE
SQL: Jdbc driver version detection fails on JBoss Wildfly

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#56759]
When loading the JDBC driver inside JBoss AP/Wildfly, the version discovery fails due to some issues with opening the jar.
```
Opening jar:file:/E:/wildfly-19.1.0.Final/modules/system/layers/base/org/elasticsearch/jdbc/main/x-pack-sql-jdbc-7.7.0.jar!/
```

The following URL, despite being returned by the AP itself when calling `conn.getInputStream`:

```java
URL url = SqlVersion.class.getProtectionDomain().getCodeSource().getLocation();
...
URLConnection conn = url.openConnection();
conn.setUseCaches(false);

try (JarInputStream jar = new JarInputStream(conn.getInputStream())) { <--
```

The underlying error seems to be:
```
Caused by: java.lang.IllegalArgumentException: Detected Elasticsearch JDBC jar but cannot retrieve its version at URLjar:file:/E:/tmp/wildfly/wildfly-19.1.0.Final/modules/system/layers/base/org/elasticsearch/jdbc/main/x-pack-sql-jdbc-7.9.0-SNAPSHOT.jar!/
        at org.elasticsearch.jdbc@7.9.0-SNAPSHOT//org.elasticsearch.xpack.sql.client.ClientVersion.extractVersion(ClientVersion.java:87)
        at org.elasticsearch.jdbc@7.9.0-SNAPSHOT//org.elasticsearch.xpack.sql.client.ClientVersion.<clinit>(ClientVersion.java:71)
        ... 19 more
Caused by: java.io.IOException: no entry name specified
        at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:160)
        at org.elasticsearch.jdbc@7.9.0-SNAPSHOT//org.elasticsearch.xpack.sql.client.ClientVersion.extractVersion(ClientVersion.java:81)
        ... 20 more
```
Which is confusing. Probably the resource/jar handling inside the server is somewhat different causing the jar to not be opened correctly. Some small tests indicate that while the URL if modified can be opened, the jar manifest is missing.
So probably a different URL/approach need to be taken to get a hold of the manifest.

As a separate issue, we could consider not detecting a version as a warning and not an exception...

**Comment by costin** [comment]
This [link](https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html/configuration_guide/overview_of_class_loading_and_modules) might provide some information.
