### ISSUE TITLE
SumAggregatorTests#testSummationAccuracy fails reproducibly

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#56757]
**Build scan**:

https://gradle-enterprise.elastic.co/s/kaniklev7exjq

**Repro line**:

`./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.metrics.SumAggregatorTests.testSummationAccuracy" -Dtests.seed=F26A4ABAC3E465CF:ABA3B862E878BBBC -Dtests.security.manager=true -Dtests.locale=de-DE -Dtests.timezone=Europe/San_Marino -Dcompiler.java=14 -Druntime.java=8`

**Reproduces locally?**:

Yes

**Applicable branches**:

I see similar failures on `7.8`, `7.x` and `master`.

**Failure excerpt**:

```
  2> java.lang.AssertionError: expected:<15.3> but was:<15.299999999999999>
        at __randomizedtesting.SeedInfo.seed([F26A4ABAC3E465CF:ABA3B862E878BBBC]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:553)
        at org.junit.Assert.assertEquals(Assert.java:683)
        at org.elasticsearch.search.aggregations.metrics.SumAggregatorTests.lambda$verifySummationOfDoubles$14(SumAggregatorTests.java:203)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.testCase(AggregatorTestCase.java:561)
        at org.elasticsearch.search.aggregations.metrics.SumAggregatorTests.testAggregation(SumAggregatorTests.java:387)
        at org.elasticsearch.search.aggregations.metrics.SumAggregatorTests.verifySummationOfDoubles(SumAggregatorTests.java:195)
        at org.elasticsearch.search.aggregations.metrics.SumAggregatorTests.testSummationAccuracy(SumAggregatorTests.java:166)
```

**Comment by DaveCTurner** [comment]
Muted in `master` (83f0ee25b9f23602fdcc2d230643bd728dfa3d85), `7.x` (63cc53e512d) and `7.8` (6e1e12c6742)

**Comment by nik9000** [comment]
I'll grab this in a few hours if no one gets to it before me.

**Comment by nik9000** [comment]
Or maybe tomorrow, I guess.
