### ISSUE TITLE
TaskManagerTests#testTrackingChannelTask failures

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#56751]
I see a number of failures of `TaskManagerTests#testTrackingChannelTask`, e.g. https://gradle-enterprise.elastic.co/s/dzpz4t5umn6xy/console-log?task=:server:test

```

2> java.lang.AssertionError: |  
-- | --
  | Expected: <[request-148, request-34, request-57, request-150, request-101, request-123, request-60, request-40, request-28, request-29, request-97, request-142, request-17, request-16, request-24, request-107, request-39, request-134, request-95, request-86, request-126, request-130, request-54, request-56, request-113, request-65, request-32, request-76, request-36, request-105, request-83, request-125, request-8, request-103, request-51, request-98, request-141, request-14, request-151, request-131, request-13, request-55, request-18, request-35, request-89, request-45, request-27, request-75, request-79, request-62, request-66, request-84, request-106, request-26, request-19, request-21, request-104, request-112, request-68, request-1, request-94, request-64, request-122, request-124, request-147, request-50, request-152, request-23, request-127, request-37, request-30, request-59, request-100, request-120, request-3, request-116, request-52, request-99, request-108, request-91, request-93, request-41, request-82, request-12, request-87, request-137, request-149, request-2, request-25, request-11, request-49, request-145, request-61, request-80, request-4, request-111, request-67, request-146, request-88, request-117, request-47, request-128, request-33, request-115, request-90, request-46, request-77, request-22, request-81, request-144, request-70, request-71, request-110, request-114, request-92, request-119, request-132, request-31, request-133, request-96, request-48, request-136, request-42, request-5, request-143, request-129, request-78, request-135, request-15, request-6, request-74, request-10, request-9, request-20, request-43, request-58, request-38, request-72, request-53, request-69, request-85, request-139, request-63, request-138, request-73, request-102, request-44, request-140, request-118, request-121, request-109]> |  
  | but: was <[request-148, request-34, request-57, request-150, request-101, request-123, request-60, request-40, request-29, request-28, request-97, request-142, request-17, request-16, request-24, request-107, request-39, request-134, request-95, request-86, request-126, request-130, request-54, request-56, request-113, request-65, request-32, request-76, request-36, request-105, request-83, request-125, request-8, request-103, request-51, request-98, request-141, request-14, request-151, request-131, request-13, request-55, request-18, request-35, request-89, request-45, request-27, request-75, request-79, request-62, request-66, request-84, request-106, request-26, request-19, request-21, request-104, request-112, request-68, request-94, request-64, request-122, request-124, request-147, request-50, request-152, request-23, request-127, request-37, request-30, request-59, request-100, request-120, request-3, request-116, request-52, request-99, request-108, request-91, request-93, request-41, request-82, request-12, request-87, request-137, request-149, request-2, request-25, request-11, request-49, request-145, request-61, request-80, request-4, request-111, request-67, request-146, request-88, request-117, request-47, request-128, request-33, request-115, request-90, request-46, request-77, request-22, request-81, request-144, request-70, request-71, request-110, request-114, request-92, request-119, request-132, request-31, request-133, request-96, request-48, request-136, request-42, request-5, request-143, request-129, request-78, request-135, request-15, request-6, request-74, request-10, request-9, request-20, request-43, request-58, request-38, request-72, request-53, request-69, request-85, request-139, request-63, request-138, request-73, request-102, request-44, request-140, request-118, request-121, request-109]> |  
  | at __randomizedtesting.SeedInfo.seed([866C88D732222E31:11BE89AEEFE1BF97]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.junit.Assert.assertThat(Assert.java:923) |  
  | at org.elasticsearch.tasks.TaskManagerTests.lambda$testTrackingChannelTask$2(TaskManagerTests.java:119) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:892) |  
  | at org.elasticsearch.tasks.TaskManagerTests.testTrackingChannelTask(TaskManagerTests.java:119)
```

I saw this same failure running the test locally in my IDE against the latest `master`. I will mute it pending further investigation.

**Comment by original-brownbear** [comment]
I think we already have an open issue for this one https://github.com/elastic/elasticsearch/issues/56746 :)

**Comment by DaveCTurner** [comment]
D'oh, thanks, wasn't expecting someone else to have triaged this so quickly. I had nearly pushed a mute linked to this issue but managed to abort that in time.
