### ISSUE TITLE
org.elasticsearch.xpack.sql.client.VersionTests.testVersionFromJar failure 

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#56854]
**Build scan**:

https://gradle-enterprise.elastic.co/s/ebqtvj3nve2cs

**Repro line**:

```
./gradlew ':x-pack:plugin:sql:sql-client:test' --tests "org.elasticsearch.xpack.sql.client.VersionTests.testVersionFromJar" -Dtests.seed=E68F964D035DA7B7 -Dtests.security.manager=true -Dtests.locale=zh-TW -Dtests.timezone=America/Port-au-Prince -Dcompiler.java=14 -Druntime.java=8
```

**Reproduces locally?**:
YES. with the given test seed. (tested against latest 7.x 813609b47c5b9916be0acb5ff56a89a504f5185b)

**Applicable branches**:
discovered and reproduced on 7.x, not sure about other branches.

**Failure history**:
It looks like it this code changed yesterday via https://github.com/elastic/elasticsearch/pull/56797 

cc: @bpintea 

**Failure excerpt**:

```
> Task :x-pack:plugin:sql:sql-client:test FAILED


org.elasticsearch.xpack.sql.client.VersionTests > testVersionFromJar FAILED
    java.security.InvalidParameterException: Invalid version initialisers [72, 100, 34]
        at __randomizedtesting.SeedInfo.seed([E68F964D035DA7B7:7AF4088C5B66BB7E]:0)
        at org.elasticsearch.xpack.sql.proto.SqlVersion.<init>(SqlVersion.java:53)
        at org.elasticsearch.xpack.sql.proto.SqlVersion.fromString(SqlVersion.java:65)
        at org.elasticsearch.xpack.sql.client.ClientVersion.extractVersion(ClientVersion.java:108)
        at org.elasticsearch.xpack.sql.client.VersionTests.testVersionFromJar(VersionTests.java:90)
REPRODUCE WITH: ./gradlew ':x-pack:plugin:sql:sql-client:test' --tests "org.elasticsearch.xpack.sql.client.VersionTests.testVersionFromJar" -Dtests.seed=E68F964D035DA7B7 -Dtests.security.manager=true -Dtests.locale=zh-TW -Dtests.timezone=America/Port-au-Prince -Dcompiler.java=14 -Druntime.java=8

Suite: Test class org.elasticsearch.xpack.sql.client.VersionTests
  1> [2020-05-15T18:37:19,131][INFO ][o.e.x.s.c.VersionTests   ] [testVersionFromJar] before test
  1> [2020-05-15T18:37:19,623][INFO ][o.e.x.s.c.VersionTests   ] [testVersionFromJar] after test
  2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:sql:sql-client:test' --tests "org.elasticsearch.xpack.sql.client.VersionTests.testVersionFromJar" -Dtests.seed=E68F964D035DA7B7 -Dtests.security.manager=true -Dtests.locale=zh-TW -Dtests.timezone=America/Port-au-Prince -Dcompiler.java=14 -Druntime.java=8
  2> java.security.InvalidParameterException: Invalid version initialisers [72, 100, 34]
        at __randomizedtesting.SeedInfo.seed([E68F964D035DA7B7:7AF4088C5B66BB7E]:0)
        at org.elasticsearch.xpack.sql.proto.SqlVersion.<init>(SqlVersion.java:53)
        at org.elasticsearch.xpack.sql.proto.SqlVersion.fromString(SqlVersion.java:65)
        at org.elasticsearch.xpack.sql.client.ClientVersion.extractVersion(ClientVersion.java:108)
        at org.elasticsearch.xpack.sql.client.VersionTests.testVersionFromJar(VersionTests.java:90)
  2> NOTE: leaving temporary files on disk at: /Users/jakelandis/workspace/7x/elasticsearch/x-pack/plugin/sql/sql-client/build/testrun/test/temp/org.elasticsearch.xpack.sql.client.VersionTests_E68F964D035DA7B7-005
  2> NOTE: test params are: codec=Asserting(Lucene84): {}, docValues:{}, maxPointsInLeafNode=1185, maxMBSortInHeap=6.418052244289037, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@2f30aa51), locale=zh-TW, timezone=America/Port-au-Prince
  2> NOTE: Mac OS X 10.15.3 x86_64/Oracle Corporation 1.8.0_211 (64-bit)/cpus=16,threads=1,free=490339424,total=514850816
  2> NOTE: All tests run in this JVM: [VersionTests]

1 test completed, 1 failed

Tests with failures:
 - org.elasticsearch.xpack.sql.client.VersionTests.testVersionFromJar
```

**Comment by bpintea** [comment]
Fixed by #56849
