### ISSUE TITLE
sql.client.VersionTests cleanup failure on Windows

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#56882]
**Build scan**:
https://gradle-enterprise.elastic.co/s/4a6jt3jrli22q

**Repro line**:
```
gradlew ':x-pack:plugin:sql:sql-client:test' --tests "org.elasticsearch.xpack.sql.client.VersionTests" \
  -Dtests.seed=7744CD7E2883EFFE \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=GMT \
  -Dcompiler.java=14 \
  -Druntime.java=11
```

**Reproduces locally?**:
Unknown, I don't have a Windows machine to test on. 

**Applicable branches**:
7.7, 7.x.m master 

**Failure history**:
Frequently since 16th May.

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:VersionTests),sort:!(time,desc))

**Failure excerpt**:
```
java.io.IOException: Could not remove the following files (in the order of attempts):
   C:\Users\jenkins\workspace\elastic+elasticsearch+7.7+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\sql\sql-client\build\testrun\test\temp\org.elasticsearch.xpack.sql.client.VersionTests_C287621E387C0F36-001\tempDir-005\es-sql-jdbc.jar: java.nio.file.FileSystemException: C:\Users\jenkins\workspace\elastic+elasticsearch+7.7+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\sql\sql-client\build\testrun\test\temp\org.elasticsearch.xpack.sql.client.VersionTests_C287621E387C0F36-001\tempDir-005\es-sql-jdbc.jar: The process cannot access the file because it is being used by another process.

   C:\Users\jenkins\workspace\elastic+elasticsearch+7.7+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\sql\sql-client\build\testrun\test\temp\org.elasticsearch.xpack.sql.client.VersionTests_C287621E387C0F36-001\tempDir-005: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+7.7+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\sql\sql-client\build\testrun\test\temp\org.elasticsearch.xpack.sql.client.VersionTests_C287621E387C0F36-001\tempDir-005
   C:\Users\jenkins\workspace\elastic+elasticsearch+7.7+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\sql\sql-client\build\testrun\test\temp\org.elasticsearch.xpack.sql.client.VersionTests_C287621E387C0F36-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+7.7+multijob-windows-compatibility\os\windows-2019\x-pack\plugin\sql\sql-client\build\testrun\test\temp\org.elasticsearch.xpack.sql.client.VersionTests_C287621E387C0F36-001

	at __randomizedtesting.SeedInfo.seed([C287621E387C0F36]:0)
	at org.apache.lucene.util.IOUtils.rm(IOUtils.java:319)
	at org.apache.lucene.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:216)
	at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by davidkyle** [comment]
Muted on 3 branches
master: 816fdc389fa5bb3b21daeb81b530527d127bfac5
7.x: 52a329fa1202c5511767e68ff7cb2790a783c4aa
7.7: 82746afcc8b40da154e6c89601cef5b266e07a80

**Comment by bpintea** [comment]
Thanks (and sorry) @davidkyle.
