### ISSUE TITLE
jvm.options not found when using Windows installer

### ISSUE THREAD

**Issue by Flogex** [elastic/elasticsearch#56934]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.7.0

**Plugins installed**:
none

**JVM version** (`java -version`):
1.8.0_251

**OS version** (`uname -a` if on a Unix-like system):
Windows 10 Enterprise, Version 1809

**Description of the problem including expected versus actual behavior**:
When trying to install Elasticsearch using the Windows Installer, it stops at the "Starting Elasticsearch service" step. In the Event Viewer, the following error is reported:

>  Elastic.ProcessHosts.Process.StartupException: Could not evaluate jvm.options file: C:\ProgramData\Elastic\Elasticsearch\config\jvm.options result: Exception in thread "main" java.nio.file.NoSuchFileException: C:\ProgramData\Elastic\Elasticsearch\config\jvm.options\jvm.options
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.readJvmOptionsFi...

So it seems like Elasticsearch looks for the file _\config\jvm.options\jvm.options_, but this does not exist.

ES_HOME and ES_PATH_CONF were not set when starting the installation.

**Steps to reproduce**:
1. Uninstall previous Elasticsearch versions and delete Elastic directory in _ProgramData_.
2. Run the Windows installer for Elasticsearch 7.7.0.
3. Keep the default values for all settings.

The same error also occurs when I try to update from 7.6.2 to 7.7.0 using the Windows Installer.

**Comment by matriv** [comment]
Closing this as it's been tracked here: https://github.com/elastic/windows-installers/issues/363
