### ISSUE TITLE
ReplicaShardAllocatorIT#testFullClusterRestartPerformNoopRecovery failed

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#57010]
**Build scan**: https://gradle-enterprise.elastic.co/s/hdysqr5ca43ae

**Repro line**:

` ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.gateway.ReplicaShardAllocatorIT.testFullClusterRestartPerformNoopRecovery" -Dtests.seed=4D289CA066996995 -Dtests.security.manager=true -Dtests.locale=en-MT -Dtests.timezone=Asia/Harbin -Dcompiler.java=14 -Druntime.java=11`

**Reproduces locally?**:

YES! Not every time tho, but definitely at least once.

**Applicable branches**:

`master`

**Failure history**:

Looks  very rare, only two failures (both PR builds) in the last 90 days:

https://build-stats.elastic.co/goto/7bfc8e670dbde7b97b0f42eb0d485748

**Failure excerpt**:

```

org.elasticsearch.gateway.ReplicaShardAllocatorIT > testFullClusterRestartPerformNoopRecovery FAILED |  
-- | --
  | java.lang.AssertionError: |  
  | Expected: an empty collection |  
  | but: <[file (name [_0.si], reused [false], length [372], recovered [372]), file (name [_3.si], reused [false], length [372], recovered [372]), file (name [_1.cfe], reused [false], length [426], recovered [426]), file (name [_1.si], reused [false], length [372], recovered [372]), file (name [_2.si], reused [false], length [372], recovered [372]), file (name [_0.cfs], reused [false], length [9459], recovered [9459]), file (name [_5.cfs], reused [false], length [2707], recovered [2707]), file (name [_2.cfs], reused [false], length [2811], recovered [2811]), file (name [_4.cfe], reused [false], length [426], recovered [426]), file (name [_3.cfe], reused [false], length [426], recovered [426]), file (name [segments_4], reused [false], length [769], recovered [769]), file (name [_1.cfs], reused [false], length [6760], recovered [6760]), file (name [_0.cfe], reused [false], length [426], recovered [426]), file (name [_2.cfe], reused [false], length [426], recovered [426]), file (name [_3.cfs], reused [false], length [3457], recovered [3457]), file (name [_5.cfe], reused [false], length [426], recovered [426]), file (name [_4.cfs], reused [false], length [2694], recovered [2694]), file (name [_4.si], reused [false], length [372], recovered [372]), file (name [_5.si], reused [false], length [372], recovered [372])]> |  
  | at __randomizedtesting.SeedInfo.seed([4D289CA066996995:A48B015963175D36]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.junit.Assert.assertThat(Assert.java:923) |  
  | at org.elasticsearch.gateway.ReplicaShardAllocatorIT.assertNoOpRecoveries(ReplicaShardAllocatorIT.java:378) |  
  | at org.elasticsearch.gateway.ReplicaShardAllocatorIT.testFullClusterRestartPerformNoopRecovery(ReplicaShardAllocatorIT.java:234) |  
  | REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.gateway.ReplicaShardAllocatorIT.testFullClusterRestartPerformNoopRecovery" -Dtests.seed=4D289CA066996995 -Dtests.security.manager=true -Dtests.locale=en-MT -Dtests.timezone=Asia/Harbin -Dcompiler.java=14 -Druntime.java=11 |  
  |  

```

**Comment by original-brownbear** [comment]
This reproduces pretty consistently for me with the given reproducer command as well => Looking into it :)
