### ISSUE TITLE
test failure: org.elasticsearch.xpack.analytics.normalize.NormalizeAggregatorTests.testTermsAggParent

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#57164]
**Build scan**:

https://gradle-enterprise.elastic.co/s/zb66vt4jdhzgk

**Repro line**:

```
./gradlew ':x-pack:plugin:analytics:test' --tests "org.elasticsearch.xpack.analytics.normalize.NormalizeAggregatorTests.testTermsAggParent" -Dtests.seed=921D46F82701E024 -Dtests.security.manager=true -Dtests.locale=sq -Dtests.timezone=America/Yellowknife -Dcompiler.java=14 -Druntime.java=11
```
**Reproduces locally?**:

Yes.

**Applicable branches**:

7.x 

**Failure history**:

Recently added feature: https://github.com/elastic/elasticsearch/pull/56399 cc: @talevy 

**Failure excerpt**:

```
org.elasticsearch.xpack.analytics.normalize.NormalizeAggregatorTests > testTermsAggParent FAILED
    java.lang.ClassCastException: class org.apache.lucene.index.ParallelCompositeReader cannot be cast to class org.apache.lucene.index.DirectoryReader (org.apache.lucene.index.ParallelCompositeReader and org.apache.lucene.index.DirectoryReader are in unnamed module of loader 'app')
        at __randomizedtesting.SeedInfo.seed([921D46F82701E024:928D3EDD3E4FD870]:0)
        at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals$FieldData.globalOrdinalsValues(ValuesSource.java:206)
        at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals.globalMaxOrd(ValuesSource.java:179)
        at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.getMaxOrd(TermsAggregatorFactory.java:300)
        at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.access$100(TermsAggregatorFactory.java:52)
        at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory$1.build(TermsAggregatorFactory.java:108)
        at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.doCreateInternal(TermsAggregatorFactory.java:274)
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:49)
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:250)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.createAggregator(AggregatorTestCase.java:244)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.createAggregator(AggregatorTestCase.java:222)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:493)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:441)
        at org.elasticsearch.xpack.analytics.normalize.NormalizeAggregatorTests.testCase(NormalizeAggregatorTests.java:165)
        at org.elasticsearch.xpack.analytics.normalize.NormalizeAggregatorTests.testTermsAggParent(NormalizeAggregatorTests.java:120)
```

**Comment by talevy** [comment]
what in the world. I'll investigate. thanks @jakelandis
