### ISSUE TITLE
[CI] RecoveryRequestTrackerTests.testIdempotencyIsEnforced failed on master

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#57199]
Build: https://gradle-enterprise.elastic.co/s/6ra77jfrlkh5y

Reproduces locally with:
```
./gradlew ':server:test' --tests "org.elasticsearch.indices.recovery.RecoveryRequestTrackerTests.testIdempotencyIsEnforced" \
  -Dtests.seed=88D97D3BD69EAAE2 \
  -Dtests.security.manager=true \
  -Dtests.locale=ms \
  -Dtests.timezone=Europe/Mariehamn \
  -Dcompiler.java=14 \
  -Druntime.java=11
```

Error:
```
org.elasticsearch.indices.recovery.RecoveryRequestTrackerTests > testIdempotencyIsEnforced FAILED
    java.lang.AssertionError: expected same:<org.elasticsearch.common.util.concurrent.UncategorizedExecutionException: Failed execution> was not:<org.elasticsearch.common.util.concurrent.UncategorizedExecutionException: Failed execution>
        at __randomizedtesting.SeedInfo.seed([88D97D3BD69EAAE2:4A41459AA2E430E4]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotSame(Assert.java:828)
        at org.junit.Assert.assertSame(Assert.java:771)
        at org.junit.Assert.assertSame(Assert.java:782)
        at org.elasticsearch.indices.recovery.RecoveryRequestTrackerTests.testIdempotencyIsEnforced(RecoveryRequestTrackerTests.java:106)
```

Other test seeds seem to be fine, so not muting for now. Please so if frequency gets annoying.

**Comment by cbuescher** [comment]
Some earlier failures this morning: https://gradle-enterprise.elastic.co/s/6prjbjwe7o2pm

**Comment by cbuescher** [comment]
Another one: https://gradle-enterprise.elastic.co/s/nbbe2o3kxggis

Still doesn't seem much but I'm going to mute on master.

**Comment by cbuescher** [comment]
Muted with https://github.com/elastic/elasticsearch/commit/773cce29619e16ebcedb57a3e0fea1b05a1e17dc

**Comment by cbuescher** [comment]
@tbrooks8 looks like this test was just added, so you might know more about it
