### ISSUE TITLE
`testSearch` in full cluster restart tests fail reproducibly in upgrade tests from 6.0.0/6.0.1 on 7.x

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#57245]
**Build scan**: https://gradle-enterprise.elastic.co/s/2ct3wagkkzlka

**Repro line**: 
```
./gradlew ':x-pack:qa:full-cluster-restart:v6.0.0#bwcTest' -Dtests.class="org.elasticsearch.xpack.restart.CoreFullClusterRestartIT" -Dtests.method="testSearch" -Dtests.seed=753FBA64CA26166D -Dtests.security.manager=true -Dtests.locale=ar-SY -Dtests.timezone=America/Menominee -Dcompiler.java=14 -Druntime.java=8
```

**Reproduces locally?**: Yes

**Applicable branches**: 7.x (failure happens on BWC tests doing a full cluster restart upgrade from 6.0.0 and 6.0.1)

**Failure history**:
[Build Stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(branch,build_url,message),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'test:%22testSearch%22'),sort:!(time,desc)))

First failure appears to have occurred on 2020-05-27 at 8:59PM MDT/UTC-6. Occurs for both `FullClusterRestartIT#testSearch` and `CoreFullClusterRestartIT#testSearch`. Failures all appear to occur during full cluster restart upgrades from 6.0.0 or 6.0.1 to builds from the 7.x branch.

**Failure excerpt**:
```
java.lang.AssertionError
: {_shards={total=1, failed=0, successful=1, skipped=0}, hits={hits=[{_index=testsearch, _type=doc, _source={field.with.dots=IcKcVSQmok, string=QvMelVukjR, bool=true, binary=uN3+r/////85N/AZAAAAAA==, float=0.7111918, int=90}, _id=86, _score=1.0}, {_index=testsearch, _type=doc, _source={field.with.dots=NDQOmRdxWs, string=NGbxLWJoFJ, bool=true, binary=uN3+r/////85N/AZAAAAAA==, float=0.047774673, int=81}, _id=87, _score=1.0}, {_index=testsearch, _type=doc, _source={field.with.dots=OBtTrYMOss, string=HKQvuhHxom, bool=false, binary=uN3+r/////85N/AZAAAAAA==, float=0.70771885, int=81}, _id=88, _score=1.0}, {_index=testsearch, _type=doc, _source={field.with.dots=AtpQPdVprv, string=EQoPMrocEg, bool=true, binary=uN3+r/////85N/AZAAAAAA==, float=0.8653538, int=13}, _id=89, _score=1.0}, {_index=testsearch, _type=doc, _source={field.with.dots=fepbXniAJL, string=NFAHxNXFDr, bool=true, binary=uN3+r/////85N/AZAAAAAA==, float=0.87794226, int=3}, _id=90, _score=1.0}, {_index=testsearch, _type=doc, _source={field.with.dots=VIDMsgETFr, string=gEmdejGaMs, bool=true, binary=uN3+r/////85N/AZAAAAAA==, float=0.2936228, int=75}, _id=91, _score=1.0}, {_index=testsearch, _type=doc, _source={field.with.dots=sDyiQONTip, string=DXZGvpCiSc, bool=true, binary=uN3+r/////85N/AZAAAAAA==, float=0.9880984, int=53}, _id=92, _score=1.0}, {_index=testsearch, _type=doc, _source={field.with.dots=lDsFpOJBCc, string=FcIojGeyie, bool=false, binary=uN3+r/////85N/AZAAAAAA==, float=0.4145916, int=12}, _id=93, _score=1.0}, {_index=testsearch, _type=doc, _source={field.with.dots=nVRJmaGaYY, string=WFRYVysQNw, bool=true, binary=uN3+r/////85N/AZAAAAAA==, float=0.059634745, int=39}, _id=94, _score=1.0}, {_index=testsearch, _type=doc, _source={field.with.dots=IKMQMQvhti, string=cRrcojYsak, bool=true, binary=uN3+r/////85N/AZAAAAAA==, float=0.17004293, int=21}, _id=95, _score=1.0}], total={value=2152, relation=eq}, max_score=1.0}, took=2, timed_out=false} expected:<2241> but was:<2152>
	at __randomizedtesting.SeedInfo.seed([BCA61B9890C0B36A:2E1F8ECDD4D9EBC5]:0)	
	at org.junit.Assert.fail(Assert.java:88)	
	at org.junit.Assert.failNotEquals(Assert.java:834)	
	at org.junit.Assert.assertEquals(Assert.java:645)	
	at org.elasticsearch.upgrades.FullClusterRestartIT.assertTotalHits(FullClusterRestartIT.java:663)	
	at org.elasticsearch.upgrades.FullClusterRestartIT.assertBasicSearchWorks(FullClusterRestartIT.java:536)	
	at org.elasticsearch.upgrades.FullClusterRestartIT.testSearch(FullClusterRestartIT.java:170)	
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
	at java.lang.reflect.Method.invoke(Method.java:498)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)	
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)	
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)	
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)	
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)	
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)	
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)	
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)	
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)	
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)	
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)	
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gwbrown** [comment]
Muted in 7.x in https://github.com/elastic/elasticsearch/pull/57249.

**Comment by cbuescher** [comment]
I did a bit of git bisecting and I think the commit where this starts failing it 343fb699a4c0ec840c8f467402201e939f856c1a. 
Using:
```
./gradlew ':x-pack:qa:full-cluster-restart:v6.0.0#bwcTest' -Dtests.class="org.elasticsearch.xpack.restart.CoreFullClusterRestartIT" -Dtests.method="testSearch" -Dtests.seed=753FBA64CA26166D -Dtests.security.manager=true -Dtests.locale=ar-SY -Dtests.timezone=America/Menominee -Dcompiler.java=14 -Druntime.java=8
```
On that commit locally I get a failure, reverting it on 7.x makes the re-run pass. I'm not sure yet how the change is related to whats happening in FullClusterRestartIT.testSearch but maybe @jtibshirani  has a better idea what might happen here. Also re-checked, it really seems to be only full cluster restart from a 6.0.0/6.0.1 version where the test fails, 6.1 seems fine.

**Comment by jtibshirani** [comment]
Thanks you @cbuescher debugging this! It looks like it wasn't actually okay to backport #56834 to 7.x, because it removes important BWC code with version 6.0. (In retrospect I should have opened a backport PR for this to get a full CI pass!)

I think the best course of action is to just revert the backport. I'll do that and re-enable the test.

**Comment by jtibshirani** [comment]
I just reverted and pushed 36e5670f763c6854c5497a7f9caf593799f1fc49 to unmute the test.

**Comment by henningandersen** [comment]
This still fails looks like i started failing [more frequently in the past week or two](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'FullClusterRestartIT+AND+testSearch'),sort:!(time,desc))).

[Failure from today](https://gradle-enterprise.elastic.co/s/ip4a5jts77e7e/tests/:qa:full-cluster-restart:v6.0.1%23upgradedClusterTest/org.elasticsearch.upgrades.FullClusterRestartIT/testSearch#1).

Following reproduces locally:

```
./gradlew ':qa:full-cluster-restart:v6.0.1#upgradedClusterTest' --tests "org.elasticsearch.upgrades.FullClusterRestartIT.testSearch"   -Dtests.seed=CD76E3D47A62746E   -Dtests.security.manager=true   -Dtests.locale=pl-PL   -Dtests.timezone=America/Lima   -Dtests.distribution=default   -Druntime.java=8
```

Also reproduces with 6.0.0 as old cluster, but not with 6.1.0.

Failure snippet:

```
java.lang.AssertionError: {_shards={total=1, failed=0, successful=1, skipped=0}, hits={hits=[{_index=testsearch, _type=doc, _source={field.with.dots=KQEHxkeINo, string=JwHPeqNPqT, bool=true, binary=342ylP////+oyvUIAAAAAA==, float=0.7119018, int=37}, _id=141, _score=1.0}, {_index=testsearch, _type=doc, _source={field.with.dots=AZDJQTPFBm, string=MopPTBcGAV, bool=true, binary=342ylP////+oyvUIAAAAAA==, float=0.29160386, int=14}, _id=142, _score=1.0}, {_index=testsearch, _type=doc, _source={field.with.dots=AHqCZtzcIs, string=orUUWkLVDI, bool=true, binary=342ylP////+oyvUIAAAAAA==, float=0.42685354, int=14}, _id=143, _score=1.0}, {_index=testsearch, _type=doc, _source={field.with.dots=oeIQFRQmtS, string=tcxiWvvYrJ, bool=false, binary=342ylP////+oyvUIAAAAAA==, float=0.9378728, int=35}, _id=144, _score=1.0}, {_index=testsearch, _type=doc, _source={field.with.dots=PEeErwoWJs, string=jKLPjeVydq, bool=true, binary=342ylP////+oyvUIAAAAAA==, float=0.845978, int=67}, _id=145, _score=1.0}, {_index=testsearch, _type=doc, _source={field.with.dots=VtrhkaPJnf, string=DnmcIlXXNT, bool=true, binary=342ylP////+oyvUIAAAAAA==, float=0.25806874, int=63}, _id=146, _score=1.0}, {_index=testsearch, _type=doc, _source={field.with.dots=pWKQbHpzWK, string=URTPFGTLtb, bool=false, binary=342ylP////+oyvUIAAAAAA==, float=0.93169653, int=72}, _id=147, _score=1.0}, {_index=testsearch, _type=doc, _source={field.with.dots=GYZJRqJESl, string=nNAcKwCQQr, bool=false, binary=342ylP////+oyvUIAAAAAA==, float=0.83365434, int=33}, _id=148, _score=1.0}, {_index=testsearch, _type=doc, _source={field.with.dots=SVIxOVofJW, string=JTCrBzqnQN, bool=false, binary=342ylP////+oyvUIAAAAAA==, float=0.26747727, int=40}, _id=149, _score=1.0}, {_index=testsearch, _type=doc, _source={field.with.dots=kAaWoERTrP, string=GfyVdYpxIC, bool=false, binary=342ylP////+oyvUIAAAAAA==, float=0.5007805, int=3}, _id=150, _score=1.0}], total={value=2282, relation=eq}, max_score=1.0}, took=11, timed_out=false} expected:<2284> but was:<2282>
        at __randomizedtesting.SeedInfo.seed([CD76E3D47A62746E:5FCF76813E7B2CC1]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.elasticsearch.upgrades.AbstractFullClusterRestartTestCase.assertTotalHits(AbstractFullClusterRestartTestCase.java:132)
        at org.elasticsearch.upgrades.FullClusterRestartIT.assertBasicSearchWorks(FullClusterRestartIT.java:536)
        at org.elasticsearch.upgrades.FullClusterRestartIT.testSearch(FullClusterRestartIT.java:170)
```

**Comment by henningandersen** [comment]
Muted again in #61133

**Comment by jtibshirani** [comment]
I confirmed that we in fact fixed the issue around May 28th when we reverted #56834. An unrelated issue popped up recently that caused the test to start failing again. I filed a new test failure issue #61305 to make it easier to track -- that way we have one issue per distinct problem/ bug fix.
