### ISSUE TITLE
[CI] Test failing due to matches of multiple legacy templates

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#57340]
It seems since May 27th, rolling upgrade test are failing in 7.x and 7.8 with the following error:

```
java.lang.AssertionError: Failure at [upgraded_cluster/40_ml_datafeed_crud:13]: got unexpected warning header [
	299 Elasticsearch-7.8.0-SNAPSHOT-32a1d304813a4dac34f2186cad48a28a83192e83 "index [airline-data] matches multiple legacy templates [global, template], composable templates will only match a single template"
]

	at __randomizedtesting.SeedInfo.seed([32827C1347501D31:BAD643C9E9AC70C9]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:405)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:382)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

examples:

https://gradle-enterprise.elastic.co/s/bvpxz6y7obu4q
https://gradle-enterprise.elastic.co/s/tzyiybdyysr4e

**Comment by dakrone** [comment]
I believe this has already been fixed in https://github.com/elastic/elasticsearch/pull/57398 so closing this
