### ISSUE TITLE
indices.create/20_mix_typeless_typeful yml test incorrect warning

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#57408]
**Build scan**:
https://gradle-enterprise.elastic.co/s/x4rshlsbvvkvq

**Repro line**:
./gradlew ':qa:smoke-test-multinode:integTestRunner' --tests "org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT" \
  -Dtests.method="test {yaml=indices.create/20_mix_typeless_typeful/Create a typeless index while there is a typed template}" \
  -Dtests.seed=1A49D0E8CAC9419D \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-SD \
  -Dtests.timezone=Europe/Moscow \
  -Druntime.java=8

**Reproduces locally?**:
Yes

**Applicable branches**:
7.x 

**Failure history**:
A small number of failures so far but it will fail every 7.x branch build

**Failure excerpt**:
```
org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT > test {yaml=indices.create/20_mix_typeless_typeful/Create a typeless index while there is a typed template} FAILED
    java.lang.AssertionError: Failure at [indices.create/20_mix_typeless_typeful:21]: got unexpected warning header [
        299 Elasticsearch-7.9.0-SNAPSHOT-72ad9a454899bf7d7ec95b370a7bbe96eff293bd "index [test-1] matches multiple legacy templates [global, test_template], composable templates will only match a single template"
    ]
```

The problem is that the expected allowed warning string does not match
```
allowed_warnings:
          - "index [test-1] matches multiple v1 templates [global, test_template], v2 index templates will only match a single index template"
``` 

In the actual message `v2 index` has changed to `composable` 
```
index [test-1] matches multiple legacy templates [global, test_template], composable templates will only match a single template
```

**Comment by davidkyle** [comment]
I will not mute this as the fix is easier than the mute

**Comment by benwtrent** [comment]
This failure exists on 7.8 builds as well:

https://gradle-enterprise.elastic.co/s/hzrhm4xscwr5e

Reproduce: 
```
 ./gradlew ':distribution:archives:integ-test-zip:integTestRunner' --tests "org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT" -Dtests.method="test {p0=indices.create/20_mix_typeless_typeful/Create a typeless index while there is a typed template}" -Dtests.seed=98BF12B53BCF2DBA -Dtests.security.manager=true -Dtests.locale=lt-LT -Dtests.timezone=Pacific/Guam -Druntime.java=8
```

```
org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT > test {p0=indices.create/20_mix_typeless_typeful/Create a typeless index while there is a typed template} FAILED
    java.lang.AssertionError: Failure at [indices.create/20_mix_typeless_typeful:21]: got unexpected warning header [
    	299 Elasticsearch-7.8.0-SNAPSHOT-c92e1f7268290ec09429316829b9d14149f62140 "index [test-1] matches multiple legacy templates [global, test_template], composable templates will only match a single template"
    ]
        at __randomizedtesting.SeedInfo.seed([98BF12B53BCF2DBA:10EB2D6F95334042]:0)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:405)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:382)
        at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.lang.AssertionError: got unexpected warning header [
        	299 Elasticsearch-7.8.0-SNAPSHOT-c92e1f7268290ec09429316829b9d14149f62140 "index [test-1] matches multiple legacy templates [global, test_template], composable templates will only match a single template"
        ]
            at org.junit.Assert.fail(Assert.java:88)
            at org.elasticsearch.test.rest.yaml.section.DoSection.checkWarningHeaders(DoSection.java:371)
            at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:293)
            at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:398)
            ... 37 more
```

**Comment by ebadyano** [comment]
@davidkyle Seems to still fail on 7.x https://gradle-enterprise.elastic.co/s/wmedisdpftrb2 
reproduced with: 
```
./gradlew ':x-pack:qa:rolling-upgrade:v7.7.2#twoThirdsUpgradedTest' --tests "org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.test {p0=mixed_cluster/80_transform_jobs_crud/Test put continuous transform on mixed cluster}" \
  -Dtests.seed=5DB0C8CC71BEC91C \
  -Dtests.security.manager=true \
  -Dtests.locale=zh-Hans-CN \
  -Dtests.timezone=Asia/Jayapura \
  -Druntime.java=15 \
  -Dtests.rest.suite=mixed_cluster
```

**Comment by davidkyle** [comment]
@ebadyano the error message is slightly different I think your failure is tracked in #56363 I've updated that issue with your failure
