### ISSUE TITLE
CentOS 7 with cPanel

### ISSUE THREAD

**Issue by fredroo** [elastic/elasticsearch#57475]
I tried with elasticsearch rpm and elastiscsearch-oss

but returned always error

what log i need put here to someone help to install correctly

**Comment by fredroo** [comment]
```
[2020-06-01T21:19:43,935][WARN ][stderr                   ] [vps.mydomain.com] JNA Warning: IOException removing temporary files: JNA temporary directory '/usr/share/elasticsearch/tmp' is not writable
[2020-06-01T21:19:43,945][WARN ][o.e.b.Natives            ] [vps.mydomain.com] unable to load JNA native support library, native methods will be disabled.
java.lang.UnsatisfiedLinkError: Failed to create temporary file for /com/sun/jna/linux-x86-64/libjnidispatch.so library: JNA temporary directory '/usr/share/elasticsearch/tmp' is not writable
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:962) ~[jna-4.5.1.jar:4.5.1 (b0)]
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922) ~[jna-4.5.1.jar:4.5.1 (b0)]
	at com.sun.jna.Native.<clinit>(Native.java:190) ~[jna-4.5.1.jar:4.5.1 (b0)]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:340) ~[?:?]
	at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:45) [elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:110) [elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178) [elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) [elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) [elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) [elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127) [elasticsearch-cli-7.7.0.jar:7.7.0]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) [elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-7.7.0.jar:7.7.0]
[2020-06-01T21:19:43,950][WARN ][o.e.b.Natives            ] [vps.mydomain.com] cannot check if running as root because JNA is not available
[2020-06-01T21:19:43,951][WARN ][o.e.b.Natives            ] [vps.mydomain.com] cannot install system call filter because JNA is not available
[2020-06-01T21:19:43,951][WARN ][o.e.b.Natives            ] [vps.mydomain.com] cannot register console handler because JNA is not available
[2020-06-01T21:19:43,954][WARN ][o.e.b.Natives            ] [vps.mydomain.com] cannot getrlimit RLIMIT_NPROC because JNA is not available
[2020-06-01T21:19:43,954][WARN ][o.e.b.Natives            ] [vps.mydomain.com] cannot getrlimit RLIMIT_AS because JNA is not available
[2020-06-01T21:19:43,954][WARN ][o.e.b.Natives            ] [vps.mydomain.com] cannot getrlimit RLIMIT_FSIZE because JNA is not available
[2020-06-01T21:19:44,050][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [vps.mydomain.com] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: org.elasticsearch.bootstrap.BootstrapException: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/tmp/5674234935512702666.tmp
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:174) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127) ~[elasticsearch-cli-7.7.0.jar:7.7.0]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.7.0.jar:7.7.0]
Caused by: org.elasticsearch.bootstrap.BootstrapException: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/tmp/5674234935512702666.tmp
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:224) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.7.0.jar:7.7.0]
	... 6 more
Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/tmp/5674234935512702666.tmp
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:375) ~[?:?]
	at java.nio.file.Files.createFile(Files.java:652) ~[?:?]
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:137) ~[?:?]
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:160) ~[?:?]
	at java.nio.file.Files.createTempFile(Files.java:917) ~[?:?]
	at org.elasticsearch.bootstrap.Security.selfTest(Security.java:404) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Security.configure(Security.java:132) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:222) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.7.0.jar:7.7.0]
	... 6 more

```

**Comment by fredroo** [comment]
chmod 0777 /usr/share/elasticsearch/

solved
