### ISSUE TITLE
:qa:repository-multi-version BWC tests failing with 

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#57650]
**Build scan**:

Lots, see e.g. https://gradle-enterprise.elastic.co/s/nrzcy2j2l4ivo

**Repro line**:

```
./gradlew ':qa:repository-multi-version:v7.4.0#Step1OldClusterTest' --tests "org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT.testReadOnlyRepo" \
  -Dtests.seed=55743EAD1D5D0105 \
  -Dtests.security.manager=true \
  -Dtests.locale=hu-HU \
  -Dtests.timezone=America/Buenos_Aires \
  -Dtests.distribution=default \
  -Druntime.java=11
```

**Reproduces locally?**:

Yep

**Applicable branches**:

Master

**Failure history**:

Looks to be caused by 7d3a7afd16a44f2c5dbdf24954986ffeda8b58e4 (i.e. #57325)

**Failure excerpt**:

```

2> REPRODUCE WITH: ./gradlew ':qa:repository-multi-version:v7.4.0#Step1OldClusterTest' --tests "org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT.testCreateAndRestoreSnapshot" -Dtests.seed=55743EAD1D5D0105 -Dtests.security.manager=true -Dtests.locale=hu-HU -Dtests.timezone=America/Buenos_Aires -Dtests.distribution=default -Druntime.java=11 |  
-- | --
  | 2> org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=illegal_argument_exception, reason=No valid expand wildcard value [hidden]] |  
  | at __randomizedtesting.SeedInfo.seed([55743EAD1D5D0105:D3CC1CF3805C60B8]:0) |  
  | at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) |  
  | at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1888) |  
  | at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1865) |  
  | at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1622) |  
  | at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1579) |  
  | at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1549) |  
  | at org.elasticsearch.client.SnapshotClient.create(SnapshotClient.java:221) |  
  | at org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT.createSnapshot(MultiVersionRepositoryAccessIT.java:291) |  
  | at org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT.testCreateAndRestoreSnapshot(MultiVersionRepositoryAccessIT.java:121)

```

**Comment by original-brownbear** [comment]
Yea looks like we'll have to adjust the test here some more to make a BwC create snapshot request. I'll deal with it shortly :)

**Comment by mark-vieira** [comment]
This is causing a ton of failures so I've gone ahead and muted this test with 9ebfbaf6e0147bd5fb404c891e8922f06b9c125d until #57661 gets merged.
