### ISSUE TITLE
search.aggregation/20_terms/string profiler expected MapStringTermsAggregator but got StringTermsAggregator

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#57684]
**Build scan**:

https://gradle-enterprise.elastic.co/s/6ismi6472kw5m/console-log?task=:qa:mixed-cluster:v7.9.0%23mixedClusterTest

**Repro line**:

`REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v7.9.0#mixedClusterTest' --tests "org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search.aggregation/20_terms/string profiler}" -Dtests.seed=743AEE0FD74F7949 -Dtests.security.manager=true -Dtests.locale=ar-TN -Dtests.timezone=Canada/Yukon -Druntime.java=11`

**Reproduces locally?**:

Yes (after a few iterations)

**Applicable branches**:

`master`

**Failure history**:

I found https://gradle-enterprise.elastic.co/s/d3waxhqslf37o which looks related but cannot see any other related failures in the last 30 days.

**Failure excerpt**:

```

org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT > test {p0=search.aggregation/20_terms/string profiler} FAILED |  
-- | --
  | java.lang.AssertionError: Failure at [search.aggregation/20_terms:801]: profile.shards.0.aggregations.0.type didn't match expected value: |  
  | profile.shards.0.aggregations.0.type: expected String [MapStringTermsAggregator] but was String [StringTermsAggregator] |  
  | at __randomizedtesting.SeedInfo.seed([743AEE0FD74F7949:FC6ED1D579B314B1]:0) |  
  | at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:405) |  
  | at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:382) |  
  | at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) |  
  | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) |  
  | at java.base/java.lang.reflect.Method.invoke(Method.java:566) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49) |  
  | at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) |  
  | at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48) |  
  | at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) |  
  | at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902) |  
  | at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41) |  
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53) |  
  | at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) |  
  | at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) |  
  | at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831) |  
  | at java.base/java.lang.Thread.run(Thread.java:834) |  
  |   |  
  | Caused by: |  
  | java.lang.AssertionError: profile.shards.0.aggregations.0.type didn't match expected value: |  
  | profile.shards.0.aggregations.0.type: expected String [MapStringTermsAggregator] but was String [StringTermsAggregator] |  
  | at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:93) |  
  | at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76) |  
  | at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:398) |  
  | ... 37 more |  
  | REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v7.9.0#mixedClusterTest' --tests "org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search.aggregation/20_terms/string profiler}" -Dtests.seed=743AEE0FD74F7949 -Dtests.security.manager=true -Dtests.locale=ar-TN -Dtests.timezone=Canada/Yukon -Druntime.java=11 |  
  |  


```

**Comment by nik9000** [comment]
Muted in https://github.com/elastic/elasticsearch/commit/4b9e378d4aaec01902e9deccc04caba6071a6d52. Backported in https://github.com/elastic/elasticsearch/commit/98c379c507a8cc93ae6015a5355fc5b6a213c0f6. Unmuted in https://github.com/elastic/elasticsearch/commit/1c7bd29f4c82a95cd4c7882737b059721ae3a351
