### ISSUE TITLE
MixedClusterClientYamlTestSuiteIT search.inner_hits/10_basic/Nested doc version and seqIDs} failure

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#57831]
**Build scan**:
https://gradle-enterprise.elastic.co/s/6v2p4uldva7yu
https://gradle-enterprise.elastic.co/s/eoao47wh52du2
https://gradle-enterprise.elastic.co/s/cjq62yrbzidu2
**Repro line**:
```
./gradlew ':qa:mixed-cluster:v7.7.2#mixedClusterTest' --tests "org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search.inner_hits/10_basic/Nested doc version and seqIDs}" -Dtests.seed=A8957CDE2B7769A4 -Dtests.security.manager=true -Dtests.locale=it-IT -Dtests.timezone=America/Caracas -Druntime.java=15
```
**Reproduces locally?**:
Yes
**Applicable branches**:
7.x
**Failure excerpt**:
In the response stash, I don't see a field called `hits.hits.0.fields._seq_no` anywhere (the `fields` key is missing?)
```
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT > test {p0=search.inner_hits/10_basic/Nested doc version and seqIDs} FAILED
    java.lang.AssertionError: Failure at [search.inner_hits/10_basic:69]: field [hits.hits.0.fields._seq_no] is null
        at __randomizedtesting.SeedInfo.seed([A8957CDE2B7769A4:20C14304858B045C]:0)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:405)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:382)
        at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.base/java.lang.Thread.run(Thread.java:832)

        Caused by:
        java.lang.AssertionError: field [hits.hits.0.fields._seq_no] is null
            at org.junit.Assert.fail(Assert.java:88)
            at org.junit.Assert.assertTrue(Assert.java:41)
            at org.junit.Assert.assertNotNull(Assert.java:712)
            at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:79)
            at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
            at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:398)
            ... 36 more
```

response body
```
  1> [2020-06-08T13:41:22,243][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "took" : 85,
  1>       "timed_out" : false,
  1>       "_shards" : {
  1>         "total" : 1,
  1>         "successful" : 1,
  1>         "skipped" : 0,
  1>         "failed" : 0
  1>       },
  1>       "hits" : {
  1>         "total" : 1,
  1>         "max_score" : 1.0,
  1>         "hits" : [
  1>           {
  1>             "_index" : "test",
  1>             "_type" : "_doc",
  1>             "_id" : "1",
  1>             "_version" : 2,
  1>             "_score" : 1.0,
  1>             "_seq_no" : 1,
  1>             "_source" : {
  1>               "nested_field" : [
  1>                 {
  1>                   "foo" : "baz"
  1>                 }
  1>               ]
  1>             },
  1>             "inner_hits" : {
  1>               "nested_field" : {
  1>                 "hits" : {
  1>                   "total" : 1,
  1>                   "max_score" : 1.0,
  1>                   "hits" : [
  1>                     {
  1>                       "_index" : "test",
  1>                       "_type" : "_doc",
  1>                       "_id" : "1",
  1>                       "_nested" : {
  1>                         "field" : "nested_field",
  1>                         "offset" : 0
  1>                       },
  1>                       "_version" : 2,
  1>                       "_score" : 1.0,
  1>                       "_seq_no" : 1,
  1>                       "_source" : {
  1>                         "foo" : "baz"
  1>                       }
  1>                     }
  1>                   ]
  1>                 }
  1>               }
  1>             }
  1>           }
  1>         ]
  1>       }
  1>     }
  1>   }
  1> }]
```

**Comment by benwtrent** [comment]
This might be an intermittent failure waiting for a backport, but I could not find anything in flight indicating this.

I pulled latest 7.x and could not reproduce locally. Such a strange failure.

**Comment by mayya-sharipova** [comment]
No more failures after the fix was merged, closing this issue.
