### ISSUE TITLE
MetadataIndexTemplateServiceTests.testUpdateComponentTemplateFailsIfResolvedIndexTemplatesWouldBeInvalid failure

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#57842]
**Build scan**: https://gradle-enterprise.elastic.co/s/q423gz7r7stn2
**Repro line**: 
```
./gradlew ':server:test' --tests "org.elasticsearch.cluster.metadata.MetadataIndexTemplateServiceTests.testUpdateComponentTemplateFailsIfResolvedIndexTemplatesWouldBeInvalid" -Dtests.seed=BEF24209C2530602 -Dtests.security.manager=true -Dtests.locale=es-SV -Dtests.timezone=US/East-Indiana -Druntime.java=8
```
**Reproduces locally?**: Yes
**Applicable branches**: 7.8
**Failure excerpt**:
```
org.elasticsearch.cluster.metadata.MetadataIndexTemplateServiceTests > testUpdateComponentTemplateFailsIfResolvedIndexTemplatesWouldBeInvalid FAILED
    java.lang.AssertionError:
    Expected: (a string containing "mapping fields [field2] cannot be replaced during template composition" or a string containing "mapper [field2] of different type, current_type [text], merged_type [ObjectMapper]")
         but: was "Can't merge a non object mapping [field2] with an object mapping [field2]"
        at __randomizedtesting.SeedInfo.seed([BEF24209C2530602:1C14F7565B1ABA64]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.cluster.metadata.MetadataIndexTemplateServiceTests.testUpdateComponentTemplateFailsIfResolvedIndexTemplatesWouldBeInvalid(MetadataIndexTemplateServiceTests.java:979)
```

**Comment by dakrone** [comment]
Resolved by #57844
