### ISSUE TITLE
[CI] failure in SSLTrustRestrictionsTests

### ISSUE THREAD

**Issue by ebadyano** [elastic/elasticsearch#57902]
**Build scan**:
https://gradle-enterprise.elastic.co/s/57ahg2efllfiy

**Repro line**:
```
./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.transport.ssl.SslMultiPortTests.testThatTransportClientWithOnlyTruststoreCanConnectToNoClientAuthProfile"   -Dtests.seed=6B63B69E4B0C9C15   -Dtests.security.manager=true   -Dtests.locale=sk-SK   -Dtests.timezone=America/Araguaina   -Druntime.java=8
```
**Reproduces locally?**:
Yes
**Applicable branches**:
7.x

**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:SSLTrustRestrictionsTests),sort:!(process.time-start,desc))

**Failure excerpt**:
```

[2020-06-09T22:01:57,899][WARN ][i.n.c.AbstractChannelHandlerContext] [transport_client_external_1] An exception 'java.lang.AssertionError: expected empty context but was {Authorization=Basic eF9wYWNrX3Jlc3RfdXNlcjp4LXBhY2stdGVzdC1wYXNzd29yZA==} on elasticsearch[transport_client_external_1][transport_worker][T#8]' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception: |  
-- | --
  | java.lang.AssertionError: expected empty context but was {Authorization=Basic eF9wYWNrX3Jlc3RfdXNlcjp4LXBhY2stdGVzdC1wYXNzd29yZA==} on elasticsearch[transport_client_external_1][transport_worker][T#8] |  
  | at org.elasticsearch.transport.Transports.assertDefaultThreadContext(Transports.java:67) ~[elasticsearch-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT] |  
  | at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelInactive(Netty4MessageChannelHandler.java:123) ~[transport-netty4-client-7.9.0-SNAPSHOT.jar:7.9.0-SNAPSHOT] |  
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [netty-transport-4.1.49.Final.jar:4.1.49.Final] |  
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [netty-transport-4.1.49.Final.jar:4.1.49.Final] |  
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) [netty-transport-4.1.49.Final.jar:4.1.49.Final] |  
  | at io.netty.handler.logging.LoggingHandler.channelInactive(LoggingHandler.java:197) [netty-handler-4.1.49.Final.jar:4.1.49.Final] |  
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) [netty-transport-4.1.49.Final.jar:4.1.49.Final] |  
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) [netty-transport-4.1.49.Final.jar:4.1.49.Final] |  
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) [netty-transport-4.1.49.Final.jar:4.1.49.Final] |  
  | at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) [netty-codec-4.1.49.Final.jar:4.1.49.Final] |  
  | at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) [netty-codec-4.1.49.Final.jar:4.1.49.Final]


```

**Comment by ywelsch** [comment]
I've reverted my commits on 7.x
