### ISSUE TITLE
can not write type [class java.math.BigInteger] error thrown while query using big int value

### ISSUE THREAD

**Issue by RashmiRam** [elastic/elasticsearch#57917]
**Elasticsearch version** (`bin/elasticsearch --version`):
`"version" : {
    "number" : "6.6.2",
    "build_flavor" : "oss",
    "build_type" : "rpm",
    "build_hash" : "3bd3e59",
    "build_date" : "2019-03-06T15:16:26.864148Z",
    "build_snapshot" : false,
    "lucene_version" : "7.6.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  }`
**Plugins installed**: []

analysis-icu
analysis-kuromoji
analysis-smartcn

**JVM version** (`java -version`):
`openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)`

**OS version** (`uname -a` if on a Unix-like system):
Amazon linux

**Description of the problem including expected versus actual behavior**:
Receiving error while querying a keyword field with bigint value

**Steps to reproduce**:

**Mapping**
`curl -XPUT localhost:9200/bigint_sample -H 'content-type:application/json' -d '{
 "mappings": {
   "testdoc": { 
     "properties": { 
       "test": { 
          "type": "keyword"  
        },
        "created_at":{
          "type": "date"
        }
      }
    }
  }
}'`

**Query**
`curl localhost:9200/bigint_sample/_search? -H 'content-type:application/json' -d '{
  "from": 0,
  "size": 30,
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
            "test": {
              "value": 80315953321748200608
            }
          }
        }
      ]
    }
  },
  "_source": {
    "includes": [
      "false"
    ],
    "excludes": []
  },
  "sort": [
    {
      "created_at": {
        "order": "desc"
      }
    }
  ]
}'`
**Provide logs (if relevant)**:

**Results in the error** 
`{
  "error": {
    "root_cause": [
      {
        "type": "i_o_exception",
        "reason": "can not write type [class java.math.BigInteger]"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "bigint_sample",
        "node": "ewretert3dsvxx454645",
        "reason": {
          "type": "i_o_exception",
          "reason": "can not write type [class java.math.BigInteger]"
        }
      }
    ],
    "caused_by": {
      "type": "i_o_exception",
      "reason": "can not write type [class java.math.BigInteger]",
      "caused_by": {
        "type": "i_o_exception",
        "reason": "can not write type [class java.math.BigInteger]"
      }
    }
  },
  "status": 500
}`

**Comment by cbuescher** [comment]
@RashmiRam thanks for raising this, I tried reproducing this with 6.6.2 but wasn't able to get the error you are seeing. Is this a single local 6.6.2 node you are running or some larger cluster? Do you see a stack-trace in the logs that you could attach?

**Comment by RashmiRam** [comment]
@cbuescher Thanks for looking into this. Even I tried running this in my local mac, I wasn't able to reproduce this. But, This is reproducible in production multi node cluster. 

Stack trace
`

[2020-06-10T07:54:29,360][WARN ][r.suppressed             ] [cluster-1-client-2]path: /bigint_sample/_search, params: {index=bigint_sample} org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:293) [elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:133) [elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:254) [elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:101) [elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:48) [elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.action.search.InitialSearchPhase$2.lambda$onFailure$1(InitialSearchPhase.java:221) [elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:175) [elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.action.search.InitialSearchPhase.access$000(InitialSearchPhase.java:48) [elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.action.search.InitialSearchPhase$2.onFailure(InitialSearchPhase.java:221) [elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73) [elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:53) [elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:462) [elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1103) [elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:660) [elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759) [elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.6.2.jar:6.6.2] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?] 	at java.lang.Thread.run(Thread.java:834) [?:?] Caused by: org.elasticsearch.ElasticsearchException$1: can not write type [class java.math.BigInteger] 	at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:657) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:131) [elasticsearch-6.6.2.jar:6.6.2] 	... 17 more Caused by: java.io.IOException: can not write type [class java.math.BigInteger] 	at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:725) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.index.query.BaseTermQueryBuilder.doWriteTo(BaseTermQueryBuilder.java:134) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.index.query.AbstractQueryBuilder.writeTo(AbstractQueryBuilder.java:80) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:975) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.index.query.AbstractQueryBuilder.writeQueries(AbstractQueryBuilder.java:264) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.index.query.BoolQueryBuilder.doWriteTo(BoolQueryBuilder.java:109) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.index.query.AbstractQueryBuilder.writeTo(AbstractQueryBuilder.java:80) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:975) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.common.io.stream.StreamOutput.writeOptionalNamedWriteable(StreamOutput.java:986) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.search.builder.SearchSourceBuilder.writeTo(SearchSourceBuilder.java:283) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.common.io.stream.StreamOutput.writeOptionalWriteable(StreamOutput.java:833) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.search.internal.ShardSearchLocalRequest.innerWriteTo(ShardSearchLocalRequest.java:254) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.search.internal.ShardSearchTransportRequest.writeTo(ShardSearchTransportRequest.java:171) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.transport.TcpTransport.buildMessage(TcpTransport.java:889) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.transport.TcpTransport.sendRequestToChannel(TcpTransport.java:740) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.transport.TcpTransport.access$300(TcpTransport.java:111) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.transport.TcpTransport$NodeChannels.sendRequest(TcpTransport.java:286) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:627) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:542) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.transport.TransportService.sendChildRequest(TransportService.java:586) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.transport.TransportService.sendChildRequest(TransportService.java:577) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.action.search.SearchTransportService.sendExecuteQuery(SearchTransportService.java:149) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction.executePhaseOnShard(SearchQueryThenFetchAsyncAction.java:54) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.action.search.InitialSearchPhase.performPhaseOnShard(InitialSearchPhase.java:212) ~[elasticsearch-6.6.2.jar:6.6.2] 	at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:110) ~[elasticsearch-6.6.2.jar:6.6.2] 	... 15 more
--


`

**Comment by cbuescher** [comment]
The problem seems to be that for `{ "term": { "test": { "value": 80315953321748200608 } } }`, the value gets parsed to a BigInteger instance by the json parser, but we cannot send those objects over the wire to another node. This explains why on a single node this wouldn't fail. I can reproduce now with one of our integration test that spins up several nodes and will open a PR to fix this, although I'm not entirely sure on which level we should prevent this.
In the meantime a workaround would be to send the value as a String: `{ "term": { "test": { "value": "80315953321748200608" } } }`. Does that work as expected then?

**Comment by RashmiRam** [comment]
Thanks for the explanation @cbuescher. Yes, we are aware of the workaround and unfortunately we don't have control over changing it to the string part of the query now. Is this the same with recent versions of ES also or specific to this version?

**Comment by cbuescher** [comment]
> Is this the same with recent versions of ES also or specific to this version?

I think its still an issue, I tested this on our master branch.

**Comment by RashmiRam** [comment]
@cbuescher which version does have this fix?

**Comment by cbuescher** [comment]
@RashmiRam this will be in the next 7.8 release. Seeing that you are still on 6, its unclear if there will be any more 6.8 patch releases. I'm currently trying to find out if a backport to 6.8 is possible in the unlikely event that we will have another release there.
