### ISSUE TITLE
SQL: JDBC: password attribute in connection string won't take escaped '&' or '='

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#57927]
If the JDBC connection string is provided the `&password=` attribute with a value containing encoded `&` or `=` characters, the parsing fails.

Ex., with `pass%3Dword`: 
```
org.elasticsearch.xpack.sql.jdbc.JdbcSQLException: Invalid parameter [password=pass=word], format needs to be key=value
	at org.elasticsearch.xpack.sql.jdbc.JdbcConfiguration.parseProperties(JdbcConfiguration.java:144)
	at org.elasticsearch.xpack.sql.jdbc.JdbcConfiguration.create(JdbcConfiguration.java:92)
	at org.elasticsearch.xpack.sql.jdbc.EsDriver.initCfg(EsDriver.java:81)
	at org.elasticsearch.xpack.sql.jdbc.EsDriver.connect(EsDriver.java:75)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
```

**Comment by bpintea** [comment]
Furthermore, if it contains leading/trailing (escaped) white space, this is trimmed away.
