### ISSUE TITLE
IndexRecoveryIT.testPeerRecoveryTrimsLocalTranslog failing sporadically

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#57949]
**Build scan**: [Most recent](https://gradle-enterprise.elastic.co/s/iojue42qdzhnu)

**Repro line**: 
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.indices.recovery.IndexRecoveryIT.testPeerRecoveryTrimsLocalTranslog" -Dtests.seed=CA6B84CD703A2B17 -Dtests.security.manager=true -Dtests.locale=es-VE -Dtests.timezone=Asia/Almaty -Druntime.java=11
```

**Reproduces locally?**: Did not reproduce locally. Tried multiple 500-iteration test runs.

**Applicable branches**: master

**Failure history**: [Build stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(message,branch),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:project,negate:!f,params:(query:elasticsearch,type:phrase),type:phrase,value:elasticsearch),query:(match:(project:(query:elasticsearch,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:test,negate:!f,params:(query:testPeerRecoveryTrimsLocalTranslog,type:phrase),type:phrase,value:testPeerRecoveryTrimsLocalTranslog),query:(match:(test:(query:testPeerRecoveryTrimsLocalTranslog,type:phrase))))),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.indices.recovery.IndexRecoveryIT%22'),sort:!(time,desc))) has this test case failing for a number of reasons, but this specific test failure seems to have started up some time in early May, and pops up every week or so.

**Failure excerpt**:
```

org.elasticsearch.indices.recovery.IndexRecoveryIT > testPeerRecoveryTrimsLocalTranslog FAILED
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=1133, name=elasticsearch[node_td1][scheduler][T#1], state=RUNNABLE, group=TGRP-IndexRecoveryIT]

        Caused by:
        org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2e4eb9c4[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@5d86406f[Wrapped task = org.elasticsearch.action.support.RetryableAction$1@50cfc861]] on org.elasticsearch.threadpool.Scheduler$SafeScheduledThreadPoolExecutor@2da6ba44[Shutting down, pool size = 1, active threads = 1, queued tasks = 2, completed tasks = 11]
            at __randomizedtesting.SeedInfo.seed([CA6B84CD703A2B17]:0)
            at org.elasticsearch.common.util.concurrent.EsAbortPolicy.rejectedExecution(EsAbortPolicy.java:48)
            at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
            at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
            at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
            at org.elasticsearch.threadpool.ThreadPool.schedule(ThreadPool.java:346)
            at org.elasticsearch.action.support.RetryableAction$RetryingListener.onFailure(RetryableAction.java:161)
            at org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:88)
            at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:694)
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:834)

    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=1181, name=elasticsearch[node_td1][scheduler][T#2], state=RUNNABLE, group=TGRP-IndexRecoveryIT]

        Caused by:
        org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@58ce594[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@7dbc4899[Wrapped task = org.elasticsearch.action.support.RetryableAction$1@21c64977]] on org.elasticsearch.threadpool.Scheduler$SafeScheduledThreadPoolExecutor@2da6ba44[Shutting down, pool size = 1, active threads = 1, queued tasks = 1, completed tasks = 12]
            at __randomizedtesting.SeedInfo.seed([CA6B84CD703A2B17]:0)
            at org.elasticsearch.common.util.concurrent.EsAbortPolicy.rejectedExecution(EsAbortPolicy.java:48)
            at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
            at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
            at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
            at org.elasticsearch.threadpool.ThreadPool.schedule(ThreadPool.java:346)
            at org.elasticsearch.action.support.RetryableAction$RetryingListener.onFailure(RetryableAction.java:161)
            at org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:88)
            at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:694)
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
            at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
            at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by dnhatn** [comment]
Fixed in #58033
