### ISSUE TITLE
Test failure for :x-pack:qa:rolling-upgrade-multi-cluster:v6.8.11#follower#oneThirdUpgradedTest

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#57969]
Not sure whether this is a transient issue when setting up the test infrastructure. But it started to occur from Jun 01 and has happened 4 times so far. The node seems crashed in the setup phase and the tests did not even get a chance to run. Looking into the logs, I noticed the following error:
```
»  2020-06-11 05:43:24,913349 UTC [543325] ERROR CNamedPipeFactory.cc@226 Unable to open named pipe /dev/shm/elastic+elasticsearch+7.x+matrix-java-periodic/ES_RUNTIME_JAVA/zulu8/nodes/general-purpose/x-pack/qa/rolling-upgrade-multi-cluster/build/testclusters/v6.8.1-follower-0/tmp/controller_log_542785 for writing: Interrupted system call
»  2020-06-11 05:43:24,913435 UTC [543325] ERROR CLogger.cc@298 Cannot log to named pipe /dev/shm/elastic+elasticsearch+7.x+matrix-java-periodic/ES_RUNTIME_JAVA/zulu8/nodes/general-purpose/x-pack/qa/rolling-upgrade-multi-cluster/build/testclusters/v6.8.1-follower-0/tmp/controller_log_542785 as it could not be opened for writing
»  2020-06-11 05:43:24,913445 UTC [543325] FATAL Main.cc@102 Could not reconfigure logging
```

The C++ code suggests it to be ML related? I am labelling this as `ml` so experts of this area can get a closer look.

**Build scan**:
* https://gradle-enterprise.elastic.co/s/hcrqg2n333qeu
* https://gradle-enterprise.elastic.co/s/u5pzxtcecn6h2
* https://gradle-enterprise.elastic.co/s/fd64ycjtlfssw
* https://gradle-enterprise.elastic.co/s/bbvp73rfgiuq4

**Repro line**:
There is no reproduction line since the tests didn't run. But I tried with
> ./gradlew ':x-pack:qa:rolling-upgrade-multi-cluster:v6.8.11#follower#oneThirdUpgradedTest' -Dtests.security.manager=true -Druntime.java=8
>
locally and it did not reproduce.

**Reproduces locally?**:
See above.

**Applicable branches**:
7.x

**Failure history**:
See build scan section.

**Failure excerpt**:
```
process was found dead while waiting for ports files, node{:x-pack:qa:rolling-upgrade-multi-cluster:v6.8.1-leader-2}
```

**Comment by droberts195** [comment]
The underlying problem is elastic/ml-cpp#564 - I'll do something about that.

**Comment by droberts195** [comment]
> The underlying problem is elastic/ml-cpp#564

Actually, although that is a problem, it's not the underlying cause of failure in this case.  The reason setting up the named pipe got interrupted is that the node was _already_ being shut down:

```
» [2020-06-11T05:43:25.143721Z] [BUILD] Stopping node
```

for the `v6.8.11-follower-0` node predates:

```
»  2020-06-11 05:43:25,183668 UTC [543320] ERROR CNamedPipeFactory.cc@226 Unable to open named pipe /dev/shm/elastic+elasticsearch+7.x+matrix-java-periodic/ES_RUNTIME_JAVA/zulu8/nodes/general-purpose/x-pack/qa/rolling-upgrade-multi-cluster/build/testclusters/v6.8.11-follower-0/tmp/controller_log_542400 for writing: Interrupted system call
»  2020-06-11 05:43:25,183740 UTC [543320] ERROR CLogger.cc@298 Cannot log to named pipe /dev/shm/elastic+elasticsearch+7.x+matrix-java-periodic/ES_RUNTIME_JAVA/zulu8/nodes/general-purpose/x-pack/qa/rolling-upgrade-multi-cluster/build/testclusters/v6.8.11-follower-0/tmp/controller_log_542400 as it could not be opened for writing
```

(That example is from https://gradle-enterprise.elastic.co/s/hcrqg2n333qeu/console-log.)

So the ML code is _not_ the root cause of the problem to set up the whole cluster.  The ML error message is a symptom of this (and definitely needs fixing because users will be confused in the same way if this happens to a production cluster).

I have a feeling that this is the real root cause:

```
[2020-06-11T05:37:16,095][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v6.8.1-leader-2] fatal error in thread [Thread-13], exiting
java.lang.AssertionError: retention lease renewal for [v6.8.1-follower/follower_index1/LSd9C3EeR9ycJeSOBhQDyg-following-leader/leader_index1/_jJZYh0JTLGXlm0TN1EfOQ] from [ccr] renewed a lower retaining sequence number [63] than the current lease retaining sequence number [64]
        at org.elasticsearch.index.seqno.ReplicationTracker.renewRetentionLease(ReplicationTracker.java:289) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.index.shard.IndexShard.renewRetentionLease(IndexShard.java:2036) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.index.seqno.RetentionLeaseActions$Renew$TransportAction.doRetentionLeaseAction(RetentionLeaseActions.java:241) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.index.seqno.RetentionLeaseActions$Renew$TransportAction.doRetentionLeaseAction(RetentionLeaseActions.java:215) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction$1.onResponse(RetentionLeaseActions.java:108) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction$1.onResponse(RetentionLeaseActions.java:103) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.index.shard.IndexShard.lambda$wrapPrimaryOperationPermitListener$14(IndexShard.java:2586) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:61) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:273) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:240) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2561) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction.asyncShardOperation(RetentionLeaseActions.java:102) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.index.seqno.RetentionLeaseActions$TransportRetentionLeaseAction.asyncShardOperation(RetentionLeaseActions.java:62) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:296) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:289) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1087) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:193) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1046) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:932) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:763) ~[elasticsearch-6.8.1.jar:6.8.1]
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:53) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[?:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[?:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) ~[?:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

That is from `v6.8.1-leader-2/logs/v6.8.1-leader.log` which can be downloaded from https://storage.cloud.google.com/elasticsearch-ci-artifacts/jobs/elastic+elasticsearch+7.x+matrix-java-periodic/ES_RUNTIME_JAVA=zulu8,nodes=general-purpose/build/31.tar.bz2

Please could somebody who knows more about CCR have a look and confirm what the root cause is.

**Comment by dnhatn** [comment]
> java.lang.AssertionError: retention lease renewal for [v6.8.1-follower/follower_index1/LSd9C3EeR9ycJeSOBhQDyg-following-leader/leader_index1/_jJZYh0JTLGXlm0TN1EfOQ] from [ccr] renewed a lower retaining sequence number [63] than the current lease retaining sequence number [64]

@droberts195 Yes, it's indeed a root cause. We fixed this issue in 6.8.5 in https://github.com/elastic/elasticsearch/pull/46420, but we could not do anything for the released versions. Here we are testing a rolling upgrade from 6.8.1. If someone hits with the same error message, please check the version and ignore it.

**Comment by ywangd** [comment]
It is kinda weird that the test says 6.8.11, but the log says 6.8.1. And 6.8.11 is not yet released. I wonder whether there is a test setup issue. @mark-vieira

**Comment by mark-vieira** [comment]
> It is kinda weird that the test says 6.8.11, but the log says 6.8.1. And 6.8.11 is not yet released. I wonder whether there is a test setup issue. @mark-vieira

Can you point me at where you are seeing this specifically (link to a line in the build scan)? The 6.8.11 version is a snapshot of the `6.8` branch. Yes, this isn't yet released, but we build the head of that branch from source to test against.

**Comment by droberts195** [comment]
Remember this is a multi-cluster test.  One of the clusters is 6.8.1 and the other is 6.8.11.

**Comment by mark-vieira** [comment]
Oh, I think I see the issue now. We are doing task name matching based on prefix. So I believe that's why were are seeing `6.8.1` show up in addition to `6.8.11`.

**Comment by mark-vieira** [comment]
> Remember this is a multi-cluster test. One of the clusters is 6.8.1 and the other is 6.8.11.

That's not the intention. This is the `7.x` branch so what we _should_ be testing in `7.9-SNAPSHOT` against `6.8.11-SNAPSHOT`. The 6.8.1 node is sneaking in somehow.

**Comment by mark-vieira** [comment]
I see what's wrong, we need to do more robust matching than `testClusters.matching { it.name.startsWith(baseName) }`. I'll submit a fix for this.

**Comment by droberts195** [comment]
The build scan for the build we're talking about is https://gradle-enterprise.elastic.co/s/hcrqg2n333qeu

**Comment by mark-vieira** [comment]
I've opened a pull request to address the issue or spinning up wrong cluster versions. That may ore may not actually be the cause of these failures though.

https://github.com/elastic/elasticsearch/pull/58063

**Comment by mark-vieira** [comment]
#58063 has been merged and backported, let's see if that sorts this out.

**Comment by ywangd** [comment]
> #58063 has been merged and backported, let's see if that sorts this out.

Thanks for sorting this out. The 4 failures linked are for 6.8.10 and 6.8.11. So a reasonable chance for them to be related to the fix.

**Comment by mark-vieira** [comment]
Yup, same issue would arise with 6.8.10 since it would have matched against 6.8.1 as well (both same prefix).
