### ISSUE TITLE
[CI] SharedClusterSnapshotRestoreIT.testSnapshotWithMissingShardLevelIndexFile failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#58050]
This file started failing Jun 12 and failed about 10 times that day so this looks to be a new issue.

**Build scan**:
https://gradle-enterprise.elastic.co/s/yhlk4shi2vuwa/tests/:server:internalClusterTest/org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT/testSnapshotWithMissingShardLevelIndexFile#1

**Repro line**:
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.testSnapshotWithMissingShardLevelIndexFile" -Dtests.seed=E1E5DF09165A58D -Dtests.security.manager=true -Dtests.locale=pl -Dtests.timezone=Africa/Niamey -Druntime.java=8	
```

**Reproduces locally?**:
Did not reproduce for me.

**Applicable branches**:
All failures were in `7.x` except for a PR build on `master` for #58033. Possibly related?

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.buildToolType=gradle&search.buildToolType=maven&search.relativeStartTime=P7D&tests.container=org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT&tests.sortField=FAILED&tests.test=testSnapshotWithMissingShardLevelIndexFile&tests.unstableOnly=true

**Failure excerpt**:

```
org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT > testSnapshotWithMissingShardLevelIndexFile FAILED
    java.lang.RuntimeException: Failed to delete expected file
        at __randomizedtesting.SeedInfo.seed([E1E5DF09165A58D:B77AC5DA538D0661]:0)
        at org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.lambda$testSnapshotWithMissingShardLevelIndexFile$8(SharedClusterSnapshotRestoreIT.java:1537)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.testSnapshotWithMissingShardLevelIndexFile(SharedClusterSnapshotRestoreIT.java:1527)

        Caused by:
        java.nio.file.NotDirectoryException: /var/lib/jenkins/workspace/elastic+elasticsearch+7.x+multijob-unix-compatibility/os/sles-15&&immutable/server/build/testrun/internalClusterTest/temp/org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT_E1E5DF09165A58D-001/tempDir-002/repos/RWRKOoUkCH/indices/extra0/0
            at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:426)
            at org.apache.lucene.mockfile.FilterFileSystemProvider.newDirectoryStream(FilterFileSystemProvider.java:223)
            at org.apache.lucene.mockfile.FilterFileSystemProvider.newDirectoryStream(FilterFileSystemProvider.java:223)
            at org.apache.lucene.mockfile.ShuffleFS.newDirectoryStream(ShuffleFS.java:49)
            at org.apache.lucene.mockfile.HandleTrackingFS.newDirectoryStream(HandleTrackingFS.java:283)
            at org.apache.lucene.mockfile.HandleTrackingFS.newDirectoryStream(HandleTrackingFS.java:283)
            at org.apache.lucene.mockfile.FilterFileSystemProvider.newDirectoryStream(FilterFileSystemProvider.java:223)
            at java.nio.file.Files.newDirectoryStream(Files.java:457)
            at java.nio.file.Files.list(Files.java:3451)
            at org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.lambda$testSnapshotWithMissingShardLevelIndexFile$8(SharedClusterSnapshotRestoreIT.java:1530)
            ... 4 more
```

**Comment by original-brownbear** [comment]
Just fixed this an hour ago https://github.com/elastic/elasticsearch/pull/58040 , shouldn't happen again :)

**Comment by mark-vieira** [comment]
Nevermind, I see now this was closed by https://github.com/elastic/elasticsearch/pull/58026
