### ISSUE TITLE
CentroidCalculatorTests testPolygonAsPoint failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#58245]
**Build scan**:
https://gradle-enterprise.elastic.co/s/pdb3fbh5avvl6/tests/:x-pack:plugin:spatial:test/org.elasticsearch.xpack.spatial.index.fielddata.CentroidCalculatorTests/testPolygonAsPoint#1

**Repro line**:
./gradlew ':x-pack:plugin:spatial:test' --tests "org.elasticsearch.xpack.spatial.index.fielddata.CentroidCalculatorTests.testPolygonAsPoint" -Dtests.seed=B380D8C378A207ED -Dtests.security.manager=true -Dtests.locale=sr-Latn-BA -Dtests.timezone=America/Bahia_Banderas -Druntime.java=11

**Reproduces locally?**:
Yes

**Applicable branches**:
8.0.0

**Failure history**:
Failed my PR build. 
I also reproduced the failure on the head of master b5490f20d04a2815d3251ae1ad4a08b6d79a7cdd

**Failure excerpt**:
    Expected: <4.6058851069340926E-229>
         but: was <4.605885106934093E-229>
        at __randomizedtesting.SeedInfo.seed([B380D8C378A207ED:BD448C9983ECDE9E]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.spatial.index.fielddata.CentroidCalculatorTests.testPolygonAsPoint(CentroidCalculatorTests.java:259)

**Comment by iverase** [comment]
I am muting it
