### ISSUE TITLE
Netty client throwing NoSuchMethodError

### ISSUE THREAD

**Issue by danaoxmt** [elastic/elasticsearch#58391]
**Elasticsearch version** (`bin/elasticsearch --version`):
$ ~/elasticsearch-6.4.2/bin/elasticsearch --version
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Version: 6.4.2

**Plugins installed**: []
org.elasticsearch.client:transport:6.4.2

**JVM version** (`java -version`):
$ java -version
java version "11.0.5" 2019-10-15 LTS

**OS version** (`uname -a` if on a Unix-like system):
Darwin Kernel Version 19.5.0

**Description of the problem including expected versus actual behavior**:
This isn't an issue in that the elasticsearch client seems to be performing as expected and is querying data successfully but there are a heap of log messages from the Netty client about fatal errors that seem to be attached to all the threads available to the Netty thread pool. It's throwing the stack trace pasted below for all threads. 

Looks like its attempting to access a method that doesnt exist in the Netty library. java.lang.NoSuchMethodError: io.netty.buffer.ByteBuf.isContiguous()

I am instantiating the client using the PreBuiltTransportClient constructor which I think is not considered best practise in favour of the HighLevelRestClient but I would have thought it would still work without throwing all these noisey log messages/ I'm not even sure that this is an issue with how the client is built it seems like an issue in the Netty library itself.

I was under the impression that https://github.com/elastic/elasticsearch/pull/22452 fixed this issue by disabling the Netty recycler but looking at the jvm.options file currently checked into Github it doesn't seem to have that property? 

**Provide logs (if relevant)**:
```
2020-06-21 11:56:41,184 DEBUG [Thread-0] DefaultListableBeanFactory:217 - Creating shared instance of singleton bean 'client'
11:56:47.816 [elasticsearch[_client_][transport_client_boss][T#1]] ERROR org.elasticsearch.transport.netty4.Netty4Utils - fatal error on the network layer
        at org.elasticsearch.transport.netty4.Netty4Utils.maybeDie(Netty4Utils.java:182)
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.exceptionCaught(Netty4MessageChannelHandler.java:73)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:381)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
Exception in thread "Thread-1"  at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.NoSuchMethodError: io.netty.buffer.ByteBuf.isContiguous()Z
        at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:83)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:274)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by jasontedor** [comment]
>Looks like its attempting to access a method that doesnt exist in the Netty library. >java.lang.NoSuchMethodError: io.netty.buffer.ByteBuf.isContiguous()

I think that you're missing the `netty-buffer` dependency from your runtime classpath. Since this is unlikely to be an Elasticsearch issue, I'm closing this. If you need further assistance, please use the [forums](https://discuss.elastic.co).

**Comment by danaoxmt** [comment]
Thanks for the reply @jasontedor was a runtime classpath issue. Cheers!
