### ISSUE TITLE
[CI] Data stream yaml test failing for mixed cluster in 7.8

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#58406]
Test indices.data_stream/10_basic/* failing and it can be reproduce, for example:

```
./gradlew ':qa:mixed-cluster:v7.8.0#mixedClusterTest' --tests "org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" \
  -Dtests.method="test {p0=indices.data_stream/10_basic/Create data stream with invalid name}" \
  -Dtests.seed=FBF2805192B9D944 \
  -Dtests.security.manager=true \
  -Dtests.locale=en-IN \
  -Dtests.timezone=Asia/Bishkek \
  -Druntime.java=8
```

Error looks like:

```
Caused by: java.lang.AssertionError: expected [400] status code but api [indices.create_data_stream] returned [405 Method Not Allowed] [{"error":"Incorrect HTTP method for uri [/_data_stream/invalid-data-stream%23-name?error_trace=true] and method [PUT], allowed: [POST]","status":405}]
Expected: <400>
     but: was <405>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.test.rest.yaml.section.DoSection.assertStatusCode(DoSection.java:388)
	at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:299)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:398)
```

**Comment by iverase** [comment]
muting tests

**Comment by martijnvg** [comment]
Thanks @iverase for muting. Actually all data streams rest tests can be muted, because data streams will not be supported in 7.8. I will go and check which other tests can be muted in 7.8 branch.

**Comment by martijnvg** [comment]
Data stream tests have been muted in the 7.8 branch.
