### ISSUE TITLE
[CI] Netty4HttpServerTransportTests.testCorsRequest failures

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#58433]
This test started failing occasionally since June 15 in 7.7, 7.8 and 7.x branches:

https://gradle-enterprise.elastic.co/s/5vv3z2vjtlsie
https://gradle-enterprise.elastic.co/s/dcnfwib2jli5u

example:

```
 ./gradlew ':modules:transport-netty4:test' --tests "org.elasticsearch.http.netty4.Netty4HttpServerTransportTests.testCorsRequest" \
  -Dtests.seed=6B3ABF72A9A87E5E \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=fr-FR \
  -Dtests.timezone=CET \
  -Druntime.java=8
```

Error:

```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=346, name=Thread-5, state=RUNNABLE, group=TGRP-Netty4HttpServerTransportTests]
	at __randomizedtesting.SeedInfo.seed([6B3ABF72A9A87E5E:D39CC37F3AB3CA5F]:0)
Caused by: java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([6B3ABF72A9A87E5E]:0)
	at org.elasticsearch.http.netty4.Netty4HttpServerTransportTests$3.dispatchRequest(Netty4HttpServerTransportTests.java:283)
	at org.elasticsearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:318)
	at org.elasticsearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:372)
	at org.elasticsearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:308)
	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:42)
	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:28)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:58)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
```

**Comment by original-brownbear** [comment]
Looks related to https://github.com/elastic/elasticsearch/issues/58296

**Comment by javanna** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/dz74pjnig7e7c/tests/:modules:transport-netty4:test/org.elasticsearch.http.netty4.Netty4HttpServerTransportTests/testCorsRequest

**Comment by javanna** [comment]
I muted this test in 7.x and 7.8

**Comment by tbrooks8** [comment]
This was unmuted in 7.x by #58505. That PR adds logging for information about failures.

**Comment by dimitris-athanasiou** [comment]
We got another failure:

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_RUNTIME_JAVA=corretto11,nodes=general-purpose/67/console

Build scan: https://gradle-enterprise.elastic.co/s/ze4cm4anbcrkk

This should have the added logging in.

**Comment by tbrooks8** [comment]
```
22:13:19   1> [2020-06-28T20:13:11,910][INFO ][o.e.h.AbstractHttpServerTransport] [testCorsRequest] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
22:13:19   1> [2020-06-28T20:13:15,565][ERROR][o.e.h.n.Netty4HttpServerTransportTests] [[elasticsearch[transport_worker][T#5]]] --> Unexpected successful request [method=GET,path=/_nodes/http]
```

This is kind of what I expected. It appears that the http server is receiving a `/_nodes/http` request. However, this test does not send this request. It only sends requests that fail. I need to look into whether this is some concurrent test that is causing this issue.

**Comment by ywelsch** [comment]
These tests could use `ESTestCase.getPortRange` instead of `0` as port, which will give them a free port in a range that's only supposed to be used by that JVM.
