### ISSUE TITLE
Grok failure log message prints wrong pipeline name [_none]

### ISSUE THREAD

**Issue by sw-jung** [elastic/elasticsearch#58478]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.5.2

**Description of the problem including expected versus actual behavior**:
When grok parse failure occurred in an ingest pipeline processing, elasticsearch logs a debug message in the cluster log.
However, this debug message prints the pipeline name as `_none` instead of the correct pipeline name.

**Steps to reproduce**:

 1. Install elasticsearch and kibana 7.5.2
 2. Run APIs below:
```http
PUT _ingest/pipeline/test-grok-pipeline
{
  "processors": [
    {
      "grok": {
        "field": "message",
        "patterns": ["%{DATESTAMP:time}: %{NUMBER:index}"]
      }
    }
  ]
}

PUT test-index/_doc/1?pipeline=test-grok-pipeline
{
  "message": "06-10-2020 04:49:01: "
}
```
 3. See elasticsearch log:
```log
[2020-06-24T17:14:44,344][DEBUG][o.e.a.b.T.BulkRequestModifier] [SWJUNG-SURFACEB] failed to execute pipeline [_none] for document [test-index/_doc/1]
org.elasticsearch.ingest.IngestProcessorException: java.lang.IllegalArgumentException: Provided Grok expressions do not match field value: [06-10-2020 04:49:01: ]
        at org.elasticsearch.ingest.CompoundProcessor.newCompoundProcessorException(CompoundProcessor.java:215) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.ingest.CompoundProcessor.lambda$innerExecute$1(CompoundProcessor.java:147) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.ingest.Processor.execute(Processor.java:54) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.ingest.CompoundProcessor.innerExecute(CompoundProcessor.java:137) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.ingest.CompoundProcessor.execute(CompoundProcessor.java:123) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.ingest.Pipeline.execute(Pipeline.java:100) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.ingest.IngestService.innerExecute(IngestService.java:505) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.ingest.IngestService.executePipelines(IngestService.java:410) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.ingest.IngestService.access$000(IngestService.java:75) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.ingest.IngestService$3.doRun(IngestService.java:384) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.5.2.jar:7.5.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.IllegalArgumentException: Provided Grok expressions do not match field value: [06-10-2020 04:49:01: ]
        at org.elasticsearch.ingest.common.GrokProcessor.execute(GrokProcessor.java:68) ~[?:?]
        at org.elasticsearch.ingest.Processor.execute(Processor.java:51) ~[elasticsearch-7.5.2.jar:7.5.2]
        ... 12 more
```

**Comment by danhermann** [comment]
Resolved by https://github.com/elastic/elasticsearch/pull/58817
