### ISSUE TITLE
[CI] :x-pack:plugin:autoscaling:test fails on 7.8

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#58529]
**Build scan**: https://gradle-enterprise.elastic.co/s/3vxkfi5pjhshe

**Repro line**: ---

**Reproduces locally?**: No

**Applicable branches**: 7.8

**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!f,value:7200000),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:f0e86d70-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'%22Task%20:x-pack:plugin:autoscaling:test%20FAILED%22'),sort:!(time,desc))

**Failure excerpt**:
```
10:25:57 Unexpected exception thrown.
10:25:57 org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:48988'.
10:25:57 	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:94)
10:25:57 	at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:270)
10:25:57 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
10:25:57 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
10:25:57 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
10:25:57 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
10:25:57 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
10:25:57 	at java.base/java.lang.Thread.run(Thread.java:832)
10:25:57 Caused by: java.lang.IllegalArgumentException
10:25:57 	at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:72)
10:25:57 	at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:52)
10:25:57 	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
10:25:57 	... 7 more
```

```
10:26:01 > Task :x-pack:plugin:autoscaling:test
10:26:01 org.gradle.internal.remote.internal.ConnectException: Could not connect to server [bfb5d210-3e34-4684-b3d0-6cb18afedeb3 port:33999, addresses:[/127.0.0.1]]. Tried addresses: [/127.0.0.1].
10:26:01 	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:67)
10:26:01 	at org.gradle.internal.remote.internal.hub.MessageHubBackedClient.getConnection(MessageHubBackedClient.java:36)
10:26:01 	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:123)
10:26:01 	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
10:26:01 	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
10:26:01 	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
10:26:01 Caused by: java.net.ConnectException: Connection refused
10:26:01 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
10:26:01 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:776)
10:26:01 	at java.base/sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:120)
10:26:01 	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.tryConnect(TcpOutgoingConnector.java:81)
10:26:01 	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:54)
10:26:01 	... 5 more
````

**Comment by jasontedor** [comment]
This looks like a build issue, not an autoscaling issue.

**Comment by rjernst** [comment]
Closing in favor of https://github.com/elastic/elasticsearch/issues/52610
