### ISSUE TITLE
"Error while loading partitions file from com/amazonaws/partitions/endpoints.json" when creating repository/sending snapshot to s3 with kvm encryption enabled

### ISSUE THREAD

**Issue by benoitvidis** [elastic/elasticsearch#58633]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.4.3

**Plugins installed**: 

- analysis-stempel
- discovery-ec2
- repository-s3

**JVM version** (`java -version`):
```
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system): Ubuntu server Xenial

**Description of the problem including expected versus actual behavior**:

After installing a new plugin (`analysis-stempel`) on an existing cluster and after reboot, sending a snapshot request suddenly fails with the exception logged below.
As far as I can see, the plugin is not the cause of it. The cluster was running fine for about 2 years in production, with daily snapshots.

[This issue](https://github.com/elastic/elasticsearch/pull/19128) presents a similar symptom but in my case, the region was set both during the snapshot registration and in elasticsearch.yml config.

From the logs, we see the aws sdk attempts to log in to s3 using sigv4, which is required by kvm encryption.
The detail of why this exception is now thrown and why the cluster was working fine till then is unclear, but the following work-around seems to work.
I am posting this issue mostly to share it if this happens to someone else.

**Work around**: 

1. switch the encryption of the bucket from KVM to AES
2. re-register the repository (required)
3. snapshots should now be accepted

I suspect that [since kvm encryption is now supported in the main branch](https://github.com/elastic/elasticsearch/pull/47466/files), this problem only occurs with older versions.

**Steps to reproduce**:

1. create a s3 bucket, activate default encryption with kvm (/aws/s3 key is fine)
2. from an ec2 instance, install elasticsearch 5.4.3 and the `repository-s3` plugin
3. grant the instance or elasticsearch permissions on the bucket
4. 
```
curl -XPUT -H "Content-type: application/json" -d '{
  "type": "s3",
  "settings": {
    "bucket": "<the bucket name>",
    "region": "<bucket region>"
  }
}' http://127.0.0.1:9200/_snapshot/repo
```

**Provide logs (if relevant)**:
```
[2020-06-26T04:30:48,497][WARN ][r.suppressed             ] path: /_snapshot/repo/202006260300, params: {repository=repo, snapshot=202006260300}
com.amazonaws.AmazonClientException: Error while loading partitions file from com/amazonaws/partitions/endpoints.json
        at com.amazonaws.partitions.PartitionsLoader.loadPartitionFromStream(PartitionsLoader.java:99) ~[?:?]
        at com.amazonaws.partitions.PartitionsLoader.build(PartitionsLoader.java:88) ~[?:?]
        at com.amazonaws.regions.RegionMetadataFactory.create(RegionMetadataFactory.java:30) ~[?:?]
        at com.amazonaws.regions.RegionUtils.initialize(RegionUtils.java:66) ~[?:?]
        at com.amazonaws.regions.RegionUtils.getRegionMetadata(RegionUtils.java:54) ~[?:?]
        at com.amazonaws.regions.RegionUtils.getRegion(RegionUtils.java:104) ~[?:?]
        at com.amazonaws.services.s3.internal.S3RequestEndpointResolver.resolveRequestEndpoint(S3RequestEndpointResolver.java:102) ~[?:?]
        at com.amazonaws.services.s3.internal.S3V4AuthErrorRetryStrategy.redirectToRegionInHeader(S3V4AuthErrorRetryStrategy.java:87) ~[?:?]
        at com.amazonaws.services.s3.internal.S3V4AuthErrorRetryStrategy.shouldRetryWithAuthParam(S3V4AuthErrorRetryStrategy.java:72) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:913) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3654) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1092) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:970) ~[?:?]
        at org.elasticsearch.repositories.s3.S3BlobContainer.readBlob(S3BlobContainer.java:82) ~[?:?]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:759) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.snapshots.SnapshotsService.getRepositoryData(SnapshotsService.java:140) ~[elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:86) [elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:51) [elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:87) [elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:166) [elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-5.4.3.jar:5.4.3]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.4.3.jar:5.4.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not access public com.amazonaws.partitions.model.Partitions(java.lang.String,java.util.List) (from class com.amazonaws.partitions.model.Partitions; failed to set access: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:270) ~[?:?]
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:245) ~[?:?]
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:143) ~[?:?]
```

**Comment by DaveCTurner** [comment]
5.4.3 was long past EOL when this was opened; from the looks of the stack trace it's unable to work out the right region, but these days you can set the signer region explicitly which should bypass whatever problems the S3 SDK appears to be hitting. We haven't had any other reports of this in the year-and-a-bit since it was opened so I believe it's no longer a valid issue and am closing it.
