### ISSUE TITLE
[CI] SamlAuthenticatorTests.testSuccessfullyParseContentFromEncryptedAssertion failure

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#58651]
**Build scan**: https://gradle-enterprise.elastic.co/s/yczk6f2jiwbbu

**Repro line**: ./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.authc.saml.SamlAuthenticatorTests.testSuccessfullyParseContentFromEncryptedAssertion" -Dtests.seed=81B483E734DC92DB -Dtests.security.manager=true -Dtests.locale=de -Dtests.timezone=BET -Druntime.java=11 -Dtests.fips.enabled=true

**Reproduces locally?**: Yes 

**Applicable branches**: master

**Failure history**:
The test failed for the first time but we also got a similar failure in https://gradle-enterprise.elastic.co/s/t5ncm7jvhfo3k where the `testSigningWhenIdpHasMultipleKeys` test  failed similarly. I think those 2 are the same issue.

[See in Kibana](https://build-stats.elastic.co/app/kibana#/visualize/edit/4f8401f0-5a22-11e9-b23c-9f9b3d85000a?_g=(refreshInterval:(pause:!f,value:10000),time:(from:now-7d%2Fd,mode:relative,to:now-0d%2Fd))&_a=(filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:project.keyword,negate:!f,params:(query:elasticsearch,type:phrase),type:phrase,value:elasticsearch),query:(match:(project.keyword:(query:elasticsearch,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:branch.keyword,negate:!f,params:!(master,'7.x','7.0','6.7'),type:phrases,value:'master,%207.x,%207.0,%206.7'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(branch.keyword:master)),(match_phrase:(branch.keyword:'7.x')),(match_phrase:(branch.keyword:'7.0')),(match_phrase:(branch.keyword:'6.7'))))))),linked:!f,query:(language:lucene,query:SamlAuthenticatorTests),uiState:(),vis:(aggs:!((enabled:!t,id:'1',params:(customLabel:'Impacted%20Builds',field:build-id),schema:metric,type:cardinality),(enabled:!t,id:'2',params:(customLabel:Test,field:test.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!f,otherBucketLabel:Other,size:20),schema:segment,type:terms),(enabled:!t,id:'3',params:(customLabel:Class,field:class.keyword,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderAgg:(enabled:!t,id:'3-orderAgg',params:(),schema:orderAgg,type:count),orderBy:custom,otherBucket:!f,otherBucketLabel:Other,size:1),schema:group,type:terms)),params:(addLegend:!t,addTimeMarker:!f,addTooltip:!t,categoryAxes:!((id:CategoryAxis-1,labels:(filter:!f,rotate:75,show:!t,truncate:100),position:bottom,scale:(type:linear),show:!t,style:(),title:(),type:category)),grid:(categoryLines:!f,style:(color:%23eee)),legendPosition:right,orderBucketsBySum:!t,seriesParams:!((data:(id:'1',label:'Impacted%20Builds'),drawLinesBetweenPoints:!t,mode:stacked,show:true,showCircles:!t,type:histogram,valueAxis:ValueAxis-1)),times:!(),type:histogram,valueAxes:!((id:ValueAxis-1,labels:(filter:!f,rotate:0,show:!t,truncate:100),name:LeftAxis-1,position:left,scale:(mode:normal,type:linear),show:!t,style:(),title:(text:'Impacted%20Builds'),type:value))),title:'Gordon:%20Top%20failing%20ES%20tests%20by%20%23%20of%20impacted%20builds',type:histogram)))
**Failure excerpt**:

```
org.bouncycastle.crypto.IllegalKeyException: Attempt to encrypt/decrypt with RSA modulus already used for sign/verify.	
at __randomizedtesting.SeedInfo.seed([81B483E734DC92DB:1848D24F26D988C7]:0)	
at org.bouncycastle.crypto.general.RSA$KeyWrapOperatorFactory$KeyWrapper.<init>(Unknown Source)	
at org.bouncycastle.crypto.general.RSA$KeyWrapOperatorFactory.createKeyWrapper(Unknown Source)	
at org.bouncycastle.crypto.general.RSA$KeyWrapOperatorFactory.createKeyWrapper(Unknown Source)	
at org.bouncycastle.jcajce.provider.BaseSingleBlockCipher.engineInit(Unknown Source)	
at org.bouncycastle.jcajce.provider.BaseSingleBlockCipher.engineInit(Unknown Source)	
at javax.crypto.Cipher.implInit(Cipher.java:839)	
at javax.crypto.Cipher.chooseProvider(Cipher.java:901)	
at javax.crypto.Cipher.init(Cipher.java:1286)	
at javax.crypto.Cipher.init(Cipher.java:1223)	
at org.apache.xml.security.encryption.XMLCipher.encryptKey(XMLCipher.java:1384)	
at org.apache.xml.security.encryption.XMLCipher.encryptKey(XMLCipher.java:1322)	
at org.apache.xml.security.encryption.XMLCipher.encryptKey(XMLCipher.java:1302)	
at org.opensaml.xmlsec.encryption.support.Encrypter.encryptKey(Encrypter.java:362)	
at org.opensaml.xmlsec.encryption.support.Encrypter.encryptKey(Encrypter.java:297)	
at org.opensaml.xmlsec.encryption.support.Encrypter.encryptKey(Encrypter.java:274)	
at org.opensaml.saml.saml2.encryption.Encrypter.encrypt(Encrypter.java:378)	
at org.opensaml.saml.saml2.encryption.Encrypter.encrypt(Encrypter.java:256)	
at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticatorTests.encryptAssertions(SamlAuthenticatorTests.java:1206)	
at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticatorTests.testSuccessfullyParseContentFromEncryptedAssertion(SamlAuthenticatorTests.java:226)	
```

**Comment by jkakavas** [comment]
@ywangd would you mind looking at this? Something in https://github.com/elastic/elasticsearch/commit/e9661558e748582c26e7581e085901fdc82406c2 made it so that the same keypair is used both for encryption and for signing and this is not allowed in FIPS 140-2, thus these tests are failing
