### ISSUE TITLE
[TEST][ML] Failures in inference_stats_crud/Test get stats given trained models

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#58662]
**Log**: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+fast+part2/565/console

**Build scan**: https://gradle-enterprise.elastic.co/s/ui72xsvizvoto

**Repro line**: ./gradlew ':x-pack:plugin:integTestRunner' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=ml/inference_stats_crud/Test get stats given trained models}" -Dtests.seed=816318538E73B1A6 -Dtests.security.manager=true -Dtests.locale=es-PE -Dtests.timezone=Pacific/Fakaofo -Druntime.java=8 -Dtests.rest.blacklist=getting_started/10_monitor_cluster_health/*

**Reproduces locally?**: No

**Applicable branches**: master/7.x

**Failure excerpt**:

```
[2020-06-29T22:13:16,752][INFO ][o.e.x.t.r.XPackRestIT    ] [test] Stash dump on test failure [{	
  "stash" : {	
    "body" : {	
      "error" : {	
        "root_cause" : [ ],	
        "type" : "exception",	
        "reason" : "Searching for stats for models [a-unused-regression-model,a-unused-regression-model1,a-used-regression-model,lang_ident_model_1] failed",	
        "caused_by" : {	
          "type" : "search_phase_execution_exception",	
          "reason" : "all shards failed",	
          "phase" : "query",	
          "grouped" : true,	
          "failed_shards" : [ ],	
          "stack_trace" : "Failed to execute phase [query], all shards failed	
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:551)	
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:309)	
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:582)	
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:393)	
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$100(AbstractSearchAsyncAction.java:68)	
	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:245)	
	at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73)	
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:59)	
	at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:403)	
	at org.elasticsearch.transport.TransportService$6.handleException(TransportService.java:638)	
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1172)	
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1281)	
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1255)	
	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:61)	
	at org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:56)	
	at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:414)	
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)	
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:710)	
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)	
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)	
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)	
	at java.lang.Thread.run(Thread.java:748)	
"	
        },	
        "stack_trace" : "ElasticsearchException[Searching for stats for models [a-unused-regression-model,a-unused-regression-model1,a-used-regression-model,lang_ident_model_1] failed]; nested: SearchPhaseExecutionException[all shards failed];	
	at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.serverError(ExceptionsHelper.java:59)	
	at org.elasticsearch.xpack.ml.inference.persistence.TrainedModelProvider.lambda$getInferenceStats$10(TrainedModelProvider.java:593)	
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)	
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)	
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:89)	
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:83)
```

**Comment by astefan** [comment]
Is this failure related to ^? https://gradle-enterprise.elastic.co/s/lh5qkbrlpbmeo/console-log?anchor=6434
Sorry if it's not and re-opening this one by mistake.

**Comment by benwtrent** [comment]
Digging through the logs:

```
[2020-07-01T11:09:34,058][DEBUG][o.e.c.c.C.CoordinatorPublication] [integTest-0] publication ended successfully: Publication{term=1, version=6340}
[2020-07-01T11:09:34,059][DEBUG][o.e.c.c.PublicationTransportHandler] [integTest-0] received diff cluster state version [6341] with uuid [lEh07d5pRLC824VOJl3nRg], diff size [181]
[2020-07-01T11:09:34,082][DEBUG][o.e.c.c.C.CoordinatorPublication] [integTest-0] publication ended successfully: Publication{term=1, version=6341}
[2020-07-01T11:09:34,083][INFO ][o.e.x.i.IndexLifecycleTransition] [integTest-0] moving index [.ml-stats-000001] from [{"phase":"hot","action":"unfollow","name":"wait-for-indexing-complete"}] to [{"phase":"hot","action":"unfollow","name":"wait-for-follow-shard-tasks"}] in policy [ml-size-based-ilm-policy]
[2020-07-01T11:09:34,084][DEBUG][o.e.c.c.PublicationTransportHandler] [integTest-0] received diff cluster state version [6342] with uuid [bP3xSLxTQxiGr4m2FpgE9Q], diff size [429]
[2020-07-01T11:09:34,092][DEBUG][o.e.c.c.C.CoordinatorPublication] [integTest-0] publication ended successfully: Publication{term=1, version=6342}
[2020-07-01T11:09:34,100][INFO ][o.e.c.m.MetadataCreateIndexService] [integTest-0] [.ml-stats-write] creating index, cause [auto(bulk api)], templates [.ml-stats], shards [1]/[1]
[2020-07-01T11:09:34,100][INFO ][o.e.c.r.a.AllocationService] [integTest-0] updating number_of_replicas to [0] for indices [.ml-stats-write]
[2020-07-01T11:09:34,101][DEBUG][o.e.c.c.PublicationTransportHandler] [integTest-0] received diff cluster state version [6343] with uuid [YwnPykaPSci00y_RDX6qBQ], diff size [1094]
[2020-07-01T11:09:34,116][DEBUG][o.e.c.c.C.CoordinatorPublication] [integTest-0] publication ended successfully: Publication{term=1, version=6343}
[2020-07-01T11:09:34,117][INFO ][o.e.x.i.IndexLifecycleTransition] [integTest-0] moving index [.ml-stats-write] from [null] to [{"phase":"new","action":"complete","name":"complete"}] in policy [ml-size-based-ilm-policy]
[2020-07-01T11:09:34,118][DEBUG][o.e.c.c.PublicationTransportHandler] [integTest-0] received diff cluster state version [6344] with uuid [xb8-4WdPR2inQk7FUamnVA], diff size [500]
[2020-07-01T11:09:34,117][ERROR][o.e.x.m.i.p.TrainedModelProvider] [integTest-0] [a-unused-regression-model] search failed for models
```

So, `.ml-stats-write` is being created as a concrete index. This should not happen. Need to investigate how to prevent this.
