### ISSUE TITLE
[CI] Failures for RemoveCorruptedShardDataCommandIT.testCorruptTranslogTruncationOfReplica

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#58671]
**Build scan**: https://gradle-enterprise.elastic.co/s/c4xzxjqoq6ij4

**Repro line**: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.index.shard.RemoveCorruptedShardDataCommandIT.testCorruptTranslogTruncationOfReplica" -Dtests.seed=43CFC5A2A11E2E8F -Dtests.security.manager=true -Dtests.locale=ca -Dtests.timezone=Asia/Riyadh -Druntime.java=8

**Reproduces locally?**: Yes

**Failure excerpt**:

```
org.elasticsearch.ElasticsearchException: Shard does not seem to be corrupted at /mnt/secret/elastic+elasticsearch+7.x+EAR/server/build/testrun/internalClusterTest/temp/org.elasticsearch.index.shard.RemoveCorruptedShardDataCommandIT_43CFC5A2A11E2E8F-001/tempDir-004/node_t2/nodes/0/indices/lc1zxYu-RWqfpeQ4EUjwZw/0 (pass --truncate-clean-translog to truncate the translog anyway)	
at __randomizedtesting.SeedInfo.seed([43CFC5A2A11E2E8F:6EE19929E0484404]:0)	
at org.elasticsearch.index.shard.RemoveCorruptedShardDataCommand.lambda$processNodePaths$2(RemoveCorruptedShardDataCommand.java:326)	
at org.elasticsearch.index.shard.RemoveCorruptedShardDataCommand.findAndProcessShardPath(RemoveCorruptedShardDataCommand.java:183)	
at org.elasticsearch.index.shard.RemoveCorruptedShardDataCommand.processNodePaths(RemoveCorruptedShardDataCommand.java:258)	
at org.elasticsearch.cluster.coordination.ElasticsearchNodeCommand.processNodePaths(ElasticsearchNodeCommand.java:158)	
at org.elasticsearch.cluster.coordination.ElasticsearchNodeCommand.execute(ElasticsearchNodeCommand.java:176)	
at org.elasticsearch.index.shard.RemoveCorruptedShardDataCommandIT.testCorruptTranslogTruncationOfReplica(RemoveCorruptedShardDataCommandIT.java:514)	
```

**Comment by dimitris-athanasiou** [comment]
It seems to reproduce for that specific seed.

**Comment by dnhatn** [comment]
Fixed in https://github.com/elastic/elasticsearch/pull/58866.
