### ISSUE TITLE
[CI] TokenBackwardsCompatibilityIT.testGeneratingTokensInOldCluster failing on 7.x

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#58807]
This test has been repeatedly failing for the past two weeks

Build scan: https://gradle-enterprise.elastic.co/s/dqls7xeilan64

Output:

```
org.elasticsearch.upgrades.IndexingIT > testIndexing FAILED
02:48:18     org.elasticsearch.client.WarningFailureException: method [PUT], host [http://127.0.0.1:46683], URI [/test_index], status line [HTTP/1.1 200 OK]
02:48:18     Warnings: [index [test_index] matches multiple legacy templates [global, xpack-prevent-bwc-deprecation-template], composable templates will only match a single template]
02:48:18     {"acknowledged":true,"shards_acknowledged":true,"index":"test_index"}
02:48:18         at __randomizedtesting.SeedInfo.seed([CBB013D90C975055:2F6A5CD02AE213DE]:0)
02:48:18         at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:289)
02:48:18         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:263)
02:48:18         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:237)
02:48:18         at org.elasticsearch.upgrades.IndexingIT.testIndexing(IndexingIT.java:77)
```

The problem seems to be related to the introduction of component templates, where a warning is now emitted due to the existing templates that are used in the system.

Marking this as both Security and Core/Features as I'm not sure which one is more applicable here.

**Comment by ywangd** [comment]
I wonder whether this can be fixed in a similar way as #56028 
Can someone who understand `default_shards` feature and/or composable templates please take a look?

**Comment by dakrone** [comment]
I believe this is a duplicate of #58258. I will take a look.

**Comment by cbuescher** [comment]
I think this failure from today looks related: https://gradle-enterprise.elastic.co/s/7nqywhqy2fu7s

**Comment by dakrone** [comment]
Fixed in #59242

**Comment by danielmitterdorfer** [comment]
We just had [another build](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=debian-9&&immutable/87/) ([build scan](https://gradle-enterprise.elastic.co/s/2urbo4eaoudwu)) which included the fix in https://github.com/elastic/elasticsearch/pull/59242, fail with the following error:

```
00:47:03     org.elasticsearch.client.WarningFailureException: method [PUT], host [http://127.0.0.1:38707], URI [token_backwards_compatibility_it/_doc/old_cluster_token1], status line [HTTP/1.1 201 Created]
00:47:03     Warnings: [index [token_backwards_compatibility_it] matches multiple legacy templates [gen-tokens-old-cluster-template, global], composable templates will only match a single template]
00:47:03     {"_index":"token_backwards_compatibility_it","_type":"_doc","_id":"old_cluster_token1","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1}
00:47:03         at __randomizedtesting.SeedInfo.seed([308BF3657CF96962:4BF6F89CCEB5F320]:0)
00:47:03         at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:289)
00:47:03         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:263)
00:47:03         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:237)
```

The reproduction line:

```
./gradlew ':x-pack:qa:rolling-upgrade:v7.8.1#oldClusterTest' --tests "org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.testGeneratingTokensInOldCluster" \
  -Dtests.seed=308BF3657CF96962 \
  -Dtests.security.manager=true \
  -Dtests.locale=ja \
  -Dtests.timezone=Etc/UCT \
  -Druntime.java=8
```

did not reproduce locally.

I think the issue is that the templates in the warning (`gen-tokens-old-cluster-template, global`) don't match the ones in #59242. @dakrone can you please have a look?

**Comment by polyfractal** [comment]
Looks to have failed again on 7.9.  I'm going to mute these in 7.8/7.9/7.x

[Build scan](https://gradle-enterprise.elastic.co/s/26qixrwtcjcqg) ([log](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.9+multijob+fast+bwc/155/console))

```
REPRODUCE WITH: ./gradlew ':x-pack:qa:rolling-upgrade:v7.8.2#oldClusterTest' --tests "org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.testRefreshingTokensInOldCluster" \
  -Dtests.seed=85781588022A9353 \
  -Dtests.security.manager=true \
  -Dtests.locale=is \
  -Dtests.timezone=Pacific/Apia \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':x-pack:qa:rolling-upgrade:v7.8.2#oldClusterTest' --tests "org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.testRefreshingTokensInOldCluster" \
  -Dtests.seed=85781588022A9353 \
  -Dtests.security.manager=true \
  -Dtests.locale=is \
  -Dtests.timezone=Pacific/Apia \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':x-pack:qa:rolling-upgrade:v7.8.2#oldClusterTest' --tests "org.elasticsearch.upgrades.IndexingIT.testIndexing" \
  -Dtests.seed=85781588022A9353 \
  -Dtests.security.manager=true \
  -Dtests.locale=hu-HU \
  -Dtests.timezone=Europe/Amsterdam \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':x-pack:qa:rolling-upgrade:v7.8.2#oldClusterTest' --tests "org.elasticsearch.upgrades.IndexingIT.testIndexing" \
  -Dtests.seed=85781588022A9353 \
  -Dtests.security.manager=true \
  -Dtests.locale=hu-HU \
  -Dtests.timezone=Europe/Amsterdam \
  -Druntime.java=8
```


```
10:02:49 org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT > testRefreshingTokensInOldCluster FAILED
10:02:49     org.elasticsearch.client.WarningFailureException: method [PUT], host [http://[::1]:42565], URI [token_backwards_compatibility_it/_doc/old_cluster_token3], status line [HTTP/1.1 201 Created]
10:02:49     Warnings: [index [token_backwards_compatibility_it] matches multiple legacy templates [global, refresh-tokens-old-cluster-template], composable templates will only match a single template]
10:02:49     {"_index":"token_backwards_compatibility_it","_type":"_doc","_id":"old_cluster_token3","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"_seq_no":0,"_primary_term":1}
10:02:49         at __randomizedtesting.SeedInfo.seed([85781588022A9353:A235F0229072377]:0)
10:02:49         at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:298)
10:02:49         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:272)
10:02:49         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246)
10:02:49         at org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.storeTokens(TokenBackwardsCompatibilityIT.java:408)
10:02:49         at org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.testRefreshingTokensInOldCluster(TokenBackwardsCompatibilityIT.java:134)



10:02:57 org.elasticsearch.upgrades.IndexingIT > testIndexing FAILED
10:02:57     org.elasticsearch.client.WarningFailureException: method [PUT], host [http://127.0.0.1:40709], URI [/test_index], status line [HTTP/1.1 200 OK]
10:02:57     Warnings: [index [test_index] matches multiple legacy templates [global, xpack-prevent-bwc-deprecation-template], composable templates will only match a single template]
10:02:57     {"acknowledged":true,"shards_acknowledged":true,"index":"test_index"}
10:02:57         at __randomizedtesting.SeedInfo.seed([85781588022A9353:61A25A81245FD0D8]:0)
10:02:57         at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:298)
10:02:57         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:272)
10:02:57         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246)
10:02:57         at org.elasticsearch.upgrades.IndexingIT.testIndexing(IndexingIT.java:77)
10:02:57 REPRODUCE WITH: ./gradlew ':x-pack:qa:rolling-upgrade:v7.8.2#oldClusterTest' --tests "
```

**Comment by danhermann** [comment]
Should be fixed by https://github.com/elastic/elasticsearch/pull/60427
