### ISSUE TITLE
[CI] HotThreadsIT.testHotThreadsDontFail failing on 6.8

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#58842]
This test failed once on 6.8

Build scan: https://gradle-enterprise.elastic.co/s/rbk4wjt4n5kg2

Output:

```
2> java.lang.AssertionError: 
  2> Expected: <4>
  2>      but: was <3>
  2> 	at __randomizedtesting.SeedInfo.seed([40525522AEC4C2EA]:0)
  2> 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
  2> 	at org.junit.Assert.assertThat(Assert.java:956)
  2> 	at org.junit.Assert.assertThat(Assert.java:923)
  2> 	at org.elasticsearch.action.admin.HotThreadsIT$1.onResponse(HotThreadsIT.java:91)
  2> 	at org.elasticsearch.action.admin.HotThreadsIT$1.onResponse(HotThreadsIT.java:84)
  2> 	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:85)
  2> 	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:81)
  2> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.finishHim(TransportNodesAction.java:251)
  2> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onOperation(TransportNodesAction.java:228)
  2> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$100(TransportNodesAction.java:151)
  2> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:205)
  2> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:195)
  2> 	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1116)
  2> 	at org.elasticsearch.transport.TcpTransport$1.doRun(TcpTransport.java:985)
  2> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  2> 	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:193)
  2> 	at org.elasticsearch.transport.TcpTransport.handleResponse(TcpTransport.java:977)
  2> 	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:952)
  2> 	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:763)
  2> 	at org.elasticsearch.transport.TcpTransport.consumeNetworkReads(TcpTransport.java:790)
  2> 	at org.elasticsearch.transport.MockTcpTransport.readMessage(MockTcpTransport.java:166)
  2> 	at org.elasticsearch.transport.MockTcpTransport.access$800(MockTcpTransport.java:75)
  2> 	at org.elasticsearch.transport.MockTcpTransport$MockChannel$2.lambda$doRun$0(MockTcpTransport.java:349)
  2> 	at org.elasticsearch.common.util.CancellableThreads.executeIO(CancellableThreads.java:108)
  2> 	at org.elasticsearch.transport.MockTcpTransport$MockChannel$2.doRun(MockTcpTransport.java:349)
  2> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  2> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  2> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  2> 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by DaveCTurner** [comment]
And another one: https://gradle-enterprise.elastic.co/s/dfgm27kbi22uu

**Comment by rjernst** [comment]
@ywelsch Given that the error here is due to a mismatch in the expected number of nodes, specifically the TestCluster appears to have less nodes than returned by the hotthreads api, is it possible the test cluster dropped a node due to the overhead of the hotthreads being requested? Do we have sufficient logging/assertions to ensure an in memory test cluster fails the test if a node fails unexpectedly?

**Comment by ywelsch** [comment]
@rjernst I don't expect a node to have dropped from the cluster, otherwise we would see it in the logs. This looks more to be failure related to the API call. Note that in the failure case the hot_threads API response (like for any `TransportNodesAction`) can contain failures, i.e. `nodeHotThreads.hasFailures` might be true here, which means that we won't have a response for every node, so perhaps add an assertion for that first, printing out `nodeHotThreads.failures()` to see what the failure is?

**Comment by rjernst** [comment]
I added additional debugging statements as suggested, but this failure has not reoccurred in the last several months. Since there is nothing actionable here, I'm going to close. We can open a new issue when it eventually reoccurs.
