### ISSUE TITLE
FsSearchableSnapshotsIT testClearCache failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#58901]
**Build scan**:
https://gradle-enterprise.elastic.co/s/yojab6qhs23go/console-log?task=:x-pack:plugin:searchable-snapshots:qa:rest:integTestRunner

**Repro line**:
```
./gradlew ':x-pack:plugin:searchable-snapshots:qa:rest:integTestRunner' --tests "org.elasticsearch.xpack.searchablesnapshots.rest.FsSearchableSnapshotsIT.testClearCache" -Dtests.seed=27D20019DDD91839 -Dtests.security.manager=true -Dtests.locale=es-PR -Dtests.timezone=Etc/Universal -Druntime.java=11
```

**Reproduces locally?**:
Nope

**Applicable branches**:
I hit it in a PR, build stats has failures on 7.x and master

**Failure history**:
A lot recently 
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:FsSearchableSnapshotsIT),sort:!(time,desc))

**Failure excerpt**:
```

java.lang.AssertionError: 
  Expected: a value greater than <198347L> 
   but: <198347L> was equal to <198347L> 
   at __randomizedtesting.SeedInfo.seed([27D20019DDD91839:E90D3AD55F4A5779]:0) 
   at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) 
   at org.junit.Assert.assertThat(Assert.java:956) 
   at org.junit.Assert.assertThat(Assert.java:923) 
   at org.elasticsearch.xpack.searchablesnapshots.AbstractSearchableSnapshotsRestTestCase.lambda$testClearCache$16(AbstractSearchableSnapshotsRestTestCase.java:207)   
   at org.elasticsearch.xpack.searchablesnapshots.AbstractSearchableSnapshotsRestTestCase.runSearchableSnapshotsTest(AbstractSearchableSnapshotsRestTestCase.java:122) 
   at org.elasticsearch.xpack.searchablesnapshots.AbstractSearchableSnapshotsRestTestCase.testClearCache(AbstractSearchableSnapshotsRestTestCase.java:190)
```

**Comment by davidkyle** [comment]
Muted on master: f5c7847 and 7.x bb96c910a58df6b7b1e0e90d49dce4167d3cc79a

**Comment by tlrx** [comment]
@davidkyle this test has been fixed yesterday in #58847 - did you check if the pull requests contained the fix of the failure?

**Comment by davidkyle** [comment]
I searched for an existing issue and did not see that a fix had gone in. 
I will revert the mutes

**Comment by tlrx** [comment]
Thanks @davidkyle ! I'm closing this for now.
