### ISSUE TITLE
[CI] WriteMemoryLimitsIT.testWriteBytesAreIncremented failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#58983]
**Build scan**:
https://gradle-enterprise.elastic.co/s/f3iosxykv6aii/tests/:server:internalClusterTest/org.elasticsearch.action.bulk.WriteMemoryLimitsIT/testWriteBytesAreIncremented#1

**Repro line**:
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.action.bulk.WriteMemoryLimitsIT.testWriteBytesAreIncremented" -Dtests.seed=E0D45B8A079853B3 -Dtests.security.manager=true -Dtests.locale=de-AT -Dtests.timezone=Etc/GMT+9 -Druntime.java=8
```

**Reproduces locally?**:
No.

**Applicable branches**:
7.x

**Failure history**:
This started failing pretty consistently on July 2nd.
https://gradle-enterprise.elastic.co/scans/tests?search.buildToolType=gradle&search.buildToolType=maven&search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.action.bulk.WriteMemoryLimitsIT&tests.sortField=FAILED&tests.test=testWriteBytesAreIncremented&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.action.bulk.WriteMemoryLimitsIT > testWriteBytesAreIncremented FAILED
    java.lang.AssertionError: expected:<21188> but was:<20864>
        at __randomizedtesting.SeedInfo.seed([E0D45B8A079853B3:D4211A236122C85A]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.elasticsearch.action.bulk.WriteMemoryLimitsIT.testWriteBytesAreIncremented(WriteMemoryLimitsIT.java:175)
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.action.bulk.WriteMemoryLimitsIT.testWriteBytesAreIncremented" -Dtests.seed=E0D45B8A079853B3 -Dtests.security.manager=true -Dtests.locale=de-AT -Dtests.timezone=Etc/GMT+9 -Druntime.java=8
```

**Comment by mark-vieira** [comment]
Given the number of failures I went ahead and muted this in `7.x` with 8fca312a3af01994dddc31164fbff186bbf043d5
