### ISSUE TITLE
Async Search is not Catching some Exceptions (and Leaking Listeners as a Result?)

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#58995]
Seeing this in production logs and it seems the same can happen in `master` still from a quick read of the code.

```
[instance-0000000292] uncaught exception in thread [elasticsearch[instance-0000000292][generic][T#36]]
org.elasticsearch.common.breaker.CircuitBreakingException: [parent] Data too large, data for [allocated_buckets] would be [4140550784/3.8gb], which is larger than the limit of [4080218931/3.7gb], real usage: [4140550784/3.8gb], new bytes reserved: [0/0b], usages [request=0/0b, fielddata=0/0b, in_flight_requests=174326758/166.2mb, accounting=0/0b]
	at org.elasticsearch.indices.breaker.HierarchyCircuitBreakerService.checkParentLimit(HierarchyCircuitBreakerService.java:347) ~[elasticsearch-7.7.1.jar:7.7.1]
	at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.addEstimateBytesAndMaybeBreak(ChildMemoryCircuitBreaker.java:128) ~[elasticsearch-7.7.1.jar:7.7.1]
	at org.elasticsearch.search.aggregations.MultiBucketConsumerService$MultiBucketConsumer.accept(MultiBucketConsumerService.java:122) ~[elasticsearch-7.7.1.jar:7.7.1]
	at org.elasticsearch.search.aggregations.InternalAggregation$ReduceContext.consumeBucketsAndMaybeBreak(InternalAggregation.java:120) ~[elasticsearch-7.7.1.jar:7.7.1]
	at org.elasticsearch.search.aggregations.bucket.terms.InternalTerms.reduce(InternalTerms.java:275) ~[elasticsearch-7.7.1.jar:7.7.1]
	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:192) ~[elasticsearch-7.7.1.jar:7.7.1]
	at org.elasticsearch.search.aggregations.bucket.histogram.InternalDateHistogram.reduceBucket(InternalDateHistogram.java:384) ~[elasticsearch-7.7.1.jar:7.7.1]
	at org.elasticsearch.search.aggregations.bucket.histogram.InternalDateHistogram.reduceBuckets(InternalDateHistogram.java:334) ~[elasticsearch-7.7.1.jar:7.7.1]
	at org.elasticsearch.search.aggregations.bucket.histogram.InternalDateHistogram.reduce(InternalDateHistogram.java:452) ~[elasticsearch-7.7.1.jar:7.7.1]
	at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:192) ~[elasticsearch-7.7.1.jar:7.7.1]
	at org.elasticsearch.search.aggregations.InternalAggregations.topLevelReduce(InternalAggregations.java:141) ~[elasticsearch-7.7.1.jar:7.7.1]
	at org.elasticsearch.xpack.search.MutableSearchResponse.toAsyncSearchResponse(MutableSearchResponse.java:159) ~[?:?]
	at org.elasticsearch.xpack.search.MutableSearchResponse.toAsyncSearchResponseWithHeaders(MutableSearchResponse.java:179) ~[?:?]
	at org.elasticsearch.xpack.search.AsyncSearchTask.getResponseWithHeaders(AsyncSearchTask.java:311) ~[?:?]
	at org.elasticsearch.xpack.search.AsyncSearchTask.lambda$internalAddCompletionListener$1(AsyncSearchTask.java:223) ~[?:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633) ~[elasticsearch-7.7.1.jar:7.7.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

We're not dealing with exceptions in code like:

```java
        if (executeImmediately) {
            listener.onResponse(getResponseWithHeaders());
        }
    }
```

in case `getResponseWithHeaders` throws anything. It seems this might (in addition to logging a warning) cause the listener to potentially be leaked?

**Comment by javanna** [comment]
Thanks for making this surface @original-brownbear , this had already surfaced from another channel and is being fixed with #57925
