### ISSUE TITLE
[CI] Reproducible Failure in InternalAutoDateHistogramTests.testReduceRandom

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#59131]
This test failed in one of my PR and can be reproduce:

```
./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.testReduceRandom" -Dtests.seed=5E4CFF4B6A47B19C -Dtests.security.manager=true -Dtests.locale=ar-YE -Dtests.timezone=Asia/Krasnoyarsk
```

Error:

```
java.lang.IllegalArgumentException: [9223372034176375807] must be <= [0]
        at __randomizedtesting.SeedInfo.seed([5E4CFF4B6A47B19C:9E71535A4C1A28CA]:0)
        at org.elasticsearch.common.LocalTimeOffset.lookup(LocalTimeOffset.java:61)
        at org.elasticsearch.common.Rounding$TimeUnitRounding.prepare(Rounding.java:419)
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.assertReduced(InternalAutoDateHistogramTests.java:157)

```

**Comment by nik9000** [comment]
Sounds like it is my bug.
