### ISSUE TITLE
[CI] Windows distroTest tests failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#59147]
https://gradle-enterprise.elastic.co/s/jrnwaxnocahvc

Failed Task:
`:qa:os:windows-2012r2:distroTest.default-windows-archive-no-jdk`

Excerpt:
```
> Task :qa:os:destructiveDistroTest.default-windows-archive-no-jdk
| 
| org.elasticsearch.packaging.test.ArchiveTests > test50StartAndStop FAILED
|     java.lang.AssertionError: 
|     Expected: expected path to exist
|          but: path C:\tmp\elasticsearch\logs\gc.log.0.current does not exist
|         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
|         at org.junit.Assert.assertThat(Assert.java:956)
|         at org.junit.Assert.assertThat(Assert.java:923)
|         at org.elasticsearch.packaging.test.ArchiveTests.test50StartAndStop(ArchiveTests.java:138)
| 
|     java.lang.RuntimeException: java.nio.file.FileSystemException: C:\tmp\elasticsearch\logs\elasticsearch.log -> C:\tmp\elasticsearch\logs\ArchiveTests.test50StartAndStop.elasticsearch.log: The process cannot access the file because it is being used by another process
|         at org.elasticsearch.packaging.util.FileUtils.mv(FileUtils.java:147)
|         at org.elasticsearch.packaging.test.PackagingTestCase.teardown(PackagingTestCase.java:187)
|         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
|         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
|         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
|         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
|         at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
|         at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
|         at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
|         at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
|         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
|         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
|         at java.base/java.lang.Thread.run(Thread.java:832)
| 
|         Caused by:
|         java.nio.file.FileSystemException: C:\tmp\elasticsearch\logs\elasticsearch.log -> C:\tmp\elasticsearch\logs\ArchiveTests.test50StartAndStop.elasticsearch.log: The process cannot access the file because it is being used by another process
|             at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
|             at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
|             at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:395)
|             at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:292)
|             at java.base/java.nio.file.Files.move(Files.java:1426)
|             at org.elasticsearch.packaging.util.FileUtils.mv(FileUtils.java:145)
```

**Comment by cbuescher** [comment]
This is an earlier one, looks similar https://gradle-enterprise.elastic.co/s/ylnewp2hi3wea/console-log?task=:qa:os:windows-2016:distroTest.default-windows-archive-no-jdk#L792

**Comment by rjernst** [comment]
This should be fixed by https://github.com/elastic/elasticsearch/pull/59257
