### ISSUE TITLE
[CI] FollowersCheckerTests#testFailsNodeThatIsUnhealthy fails on master

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#59172]
**Build scan**:
https://gradle-enterprise.elastic.co/s/uwmxo33dnzojo

**Repro line**:
```
./gradlew ':server:test' --tests "org.elasticsearch.cluster.coordination.FollowersCheckerTests.testFailsNodeThatIsUnhealthy" \
  -Dtests.seed=2C28E5E8C9CA7F3B \
  -Dtests.security.manager=true \
  -Dtests.locale=en-ZA \
  -Dtests.timezone=Etc/GMT+7 \
  -Druntime.java=11
```

**Reproduces locally?**:

Yes

**Failure excerpt**:

```
java.lang.AssertionError: 
Expected: "health check failed"
     but: was "followers check retry count exceeded"
	at __randomizedtesting.SeedInfo.seed([2C28E5E8C9CA7F3B:EF7745CE84E82FC0]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.cluster.coordination.FollowersCheckerTests.lambda$testBehaviourOfFailingNode$19(FollowersCheckerTests.java:363)
	at org.elasticsearch.cluster.coordination.FollowersChecker$FollowerChecker$2.run(FollowersChecker.java:370)
	at org.elasticsearch.cluster.coordination.DeterministicTaskQueue.runTask(DeterministicTaskQueue.java:133)
	at org.elasticsearch.cluster.coordination.DeterministicTaskQueue.runRandomTask(DeterministicTaskQueue.java:127)
	at org.elasticsearch.cluster.coordination.DeterministicTaskQueue.runAllRunnableTasks(DeterministicTaskQueue.java:77)
	at org.elasticsearch.cluster.coordination.FollowersCheckerTests.testBehaviourOfFailingNode(FollowersCheckerTests.java:372)
	at org.elasticsearch.cluster.coordination.FollowersCheckerTests.testFailsNodeThatIsUnhealthy(FollowersCheckerTests.java:310)
```

**Comment by dnhatn** [comment]
Another instance https://gradle-enterprise.elastic.co/s/6mksdzenq77hc/tests/:server:test/org.elasticsearch.cluster.coordination.FollowersCheckerTests/testFailsNodeThatIsUnhealthy#1

**Comment by danielmitterdorfer** [comment]
Another instance in https://gradle-enterprise.elastic.co/s/lb6poefv2wphw.
