### ISSUE TITLE
TransportClientIT testNodeVersionIsUpdated fails on 7.x with unknown setting 'indices.recovery.chunk_size'

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#59245]
**Build scan**:
https://gradle-enterprise.elastic.co/s/eevzsq4ahk2n2

**Repro line**:
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.client.transport.TransportClientIT.testNodeVersionIsUpdated" -Dtests.seed=7F05DA245AD35164 -Dtests.security.manager=true -Dtests.locale=sr-Latn-ME -Dtests.timezone=Asia/Ashkhabad -Druntime.java=8
```

**Reproduces locally?**:
Yep

**Applicable branches**:
7.x

**Failure history**:
This failed in a PR build of mine and then reproduced 

**Failure excerpt**:

```
org.elasticsearch.client.transport.TransportClientIT > testNodeVersionIsUpdated FAILED
    java.lang.IllegalArgumentException: unknown setting [indices.recovery.chunk_size] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
        at __randomizedtesting.SeedInfo.seed([7F05DA245AD35164:D11122FE289C9FD3]:0)
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:544)
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:489)
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:460)
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:431)
        at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:149)
        at org.elasticsearch.node.Node.<init>(Node.java:385)
        at org.elasticsearch.node.MockNode.<init>(MockNode.java:99)
        at org.elasticsearch.node.MockNode.<init>(MockNode.java:89)
        at org.elasticsearch.node.MockNode.<init>(MockNode.java:81)
        at org.elasticsearch.node.MockNode.<init>(MockNode.java:74)
        at org.elasticsearch.client.transport.TransportClientIT.testNodeVersionIsUpdated(TransportClientIT.java:70)
```

**Comment by dnhatn** [comment]
Addressed in https://github.com/elastic/elasticsearch/commit/e50a0330ec835b8b218cd99933c5182dd24e784f
