### ISSUE TITLE
FsHealthServiceTests » testLoggingOnHungIO fails on windows builds

### ISSUE THREAD

**Issue by hub-cap** [elastic/elasticsearch#59252]
**Build scan**:
https://gradle-enterprise.elastic.co/s/hpdyjffydv7om
**Repro line**:
```
gradlew ':server:test' --tests "org.elasticsearch.monitor.fs.FsHealthServiceTests.testLoggingOnHungIO" -Dtests.seed=3C203AA224C46D04 -Dtests.security.manager=true -Dtests.locale=zh -Dtests.timezone=Asia/Famagusta -Druntime.java=11
```
**Reproduces locally?**:
Windows, so unknown
**Applicable branches**:
master
**Failure history**:

This has been happening for a few days now

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.monitor.fs.FsHealthServiceTests%22%20AND%20test:%22testLoggingOnHungIO%22'),sort:!(time,asc))
**Failure excerpt**:

```
Suite: Test class org.elasticsearch.monitor.fs.FsHealthServiceTests
  1> [2020-07-08T21:11:01,327][INFO ][o.e.e.NodeEnvironment    ] [testLoggingOnHungIO] using [2] data paths, mounts [[(C:)]], net usable_space [282.6gb], net total_space [349.9gb], types [NTFS]
  1> [2020-07-08T21:11:01,327][INFO ][o.e.e.NodeEnvironment    ] [testLoggingOnHungIO] heap size [512mb], compressed ordinary object pointers [true]
  2> REPRODUCE WITH: gradlew ':server:test' --tests "org.elasticsearch.monitor.fs.FsHealthServiceTests.testLoggingOnHungIO" -Dtests.seed=3C203AA224C46D04 -Dtests.security.manager=true -Dtests.locale=zh -Dtests.timezone=Asia/Famagusta -Druntime.java=11  2> 
  2> java.lang.AssertionError: expected:<2> but was:<0>
        at __randomizedtesting.SeedInfo.seed([3C203AA224C46D04:76E1FC3AF7C253C5]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.elasticsearch.monitor.fs.FsHealthServiceTests.testLoggingOnHungIO(FsHealthServiceTests.java:164)
```

**Comment by hub-cap** [comment]
ping @DaveCTurner as this might be related to #52680
