### ISSUE TITLE
ES can't start on latest cloud 8.0 snapshot deploy

### ISSUE THREAD

**Issue by EricDavisX** [elastic/elasticsearch#59346]
Run the cloud deploy of 8.0 latest as of today (new snapshot available around 4PM)

**Plugins installed**: []
use all defaults

verified on multiple cloud regions and providers

**Description of the problem including expected versus actual behavior**:
see logs attached.

**Steps to reproduce**:
deploy to cloud - see that Kibana never comes up.  get logs and see that ES seems to have problems?  I may not be reading the logs right, please forgive.

**logs**:
[cloud-deploy-logs.txt](https://github.com/elastic/elasticsearch/files/4899829/cloud-deploy-logs.txt)

a particular log line here, latest error, of several:
	Jul 9, 2020 @ 20:18:48.000	 - 	Unable to connect to Elasticsearch. Error: [resource_already_exists_exception] index [.kibana_task_manager_1/RdWVpDqGTqy442X2O0gE-Q] already exists, with { index_uuid="RdWVpDqGTqy442X2O0gE-Q" & index=".kibana_task_manager_1" }

It sounds like a Kibana problem right?  But I have a special usage of the snapshots in place in the Endpoint Kibana demo server that we updated with *just* the kibana snapshot and it connected up fine to a 1-2 day older ES snapshot.  which is what makes me think its on ES side.  but I am not sure at all.  thank you in advance for helping this issue on towards its best home.

image seen on cloud:
<img width="380" alt="Screen Shot 2020-07-09 at 4 23 29 PM" src="https://user-images.githubusercontent.com/12970373/87097509-68677800-c213-11ea-9459-c37c16702b5c.png">

**Comment by EricDavisX** [comment]
the snapshot was built this AM, from this job:
https://internal-ci.elastic.co/view/All/job/elastic+release-manager+master+unified-snapshot/518/
518 - master - 8.0.0-28d950ce

**Comment by tylersmalley** [comment]
This error is being addressed here: https://github.com/elastic/kibana/pull/71343

From the logs it's the same error as we are seeing with our snapshot build:

```
Jul 9, 2020 @ 20:15:48.000	 - 	{ Error: [mapper_parsing_exception] unknown parameter [index] on mapper [api_key] of type [binary]
    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)
    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)
    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/lodash/lodash.js:4929:19)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Kibana has `index: false` on a binary field type. From the docs it seems like this is unnecessary but wasn't something that resulted in an exception prior to today.

We will handle this from the Kibana side and open an Elasticsearch issue with details on what the breaking change was if that is warranted.
