### ISSUE TITLE
Service not starting after uninstalling 7.3.1 and installing 7.8.0

### ISSUE THREAD

**Issue by ShirishPatel** [elastic/elasticsearch#59369]
Spend hours trying to 
1. uninstall 
2. install 
3. start elasticsearch service ( but stopping immediately )
4. giving full Read/Write permissions to Network Service + Service + Users for all folders in C:\ProgramData\Elastic + C:\Program Files\Elastic\Elasticsearch\7.8.0
5. Checked the JAVA_HOME Env
6. Checked the JRE_HOME Env etc...
7. Restarting the server
etc.. etc... etc...

Installed the old version 7.3.1 again and it started working fine..

OS : Windows Server 2012 R2
JDK : C:\Program Files\Java\jdk1.8.0_251
JRE : C:\Program Files\Java\jre1.8.0_251

**.Net Runtime Error :**

Application: elasticsearch.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Elastic.ProcessHosts.Process.StartupException
   at Elastic.ProcessHosts.Process.ProcessBase.HandleException(System.Exception)
   at System.Reactive.AnonymousObserver`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnErrorCore(System.Exception)
   at System.Reactive.ObserverBase`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnError(System.Exception)
   at System.Reactive.Observer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnError(System.Exception)
   at System.Reactive.Subjects.Subject`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnError(System.Exception)
   at System.Reactive.Linq.ObservableImpl.AsObservable`1+_[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnError(System.Exception)
   at System.Reactive.AutoDetachObserver`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnErrorCore(System.Exception)
   at System.Reactive.ObserverBase`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnError(System.Exception)
   at Elastic.ProcessHosts.Process.ObservableProcess+<>c__DisplayClass22_0.<CreateProcessExitSubscription>b__0(System.Reactive.EventPattern`1<System.Object>)
   at System.Reactive.AnonymousSafeObserver`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(System.__Canon)
   at System.Reactive.Subjects.Subject`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].OnNext(System.__Canon)
   at System.Reactive.Linq.ObservableImpl.FromEventPattern+Impl`2+<>c__DisplayClass4[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<GetHandler>b__1(System.Object, System.__Canon)
   at System.EventHandler.Invoke(System.Object, System.EventArgs)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Diagnostics.Process.CompletionCallback(System.Object, Boolean)
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context(System.Object, Boolean)
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context_f(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(System.Object, Boolean)

**Application Error :**

Faulting application name: elasticsearch.exe, version: 7.8.0.0, time stamp: 0x5ee699cb
Faulting module name: KERNELBASE.dll, version: 6.3.9600.17031, time stamp: 0x53089862
Exception code: 0xe0434352
Fault offset: 0x00000000000068d8
Faulting process id: 0x3db8
Faulting application start time: 0x01d6574aa532c678
Faulting application path: D:\Program Files\Elasticsearch\7.8.0\bin\elasticsearch.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: e41ab261-c33d-11ea-80e6-3c4a92f53034
Faulting package full name: 
Faulting package-relative application ID:

**Comment by williamrandolph** [comment]
@ShirishPatel,

I'm trying to replicate this error. A few questions:

1. Are you using the Windows MSI installer, or are you downloading the `zip` and using `elasticsearch-service.bat` to install the service?
2. How are you managing and restarting the service? On the command line or via a management program?
3. Where did the logs you posted come from?

Thanks,

-William

**Comment by williamrandolph** [comment]
Without feedback on the issue, we are unable to investigate any further, and are closing the issue.
