### ISSUE TITLE
FsHealthServiceTests testFailsHealthOnIOException on Windows

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#59380]
**Build scan**:
https://gradle-enterprise.elastic.co/s/schg2cx7kb3ja
https://gradle-enterprise.elastic.co/s/avmtx56geouvy
https://gradle-enterprise.elastic.co/s/kkawj75b45nzc

**Repro line**:
```
 gradlew ':server:test' --tests "org.elasticsearch.monitor.fs.FsHealthServiceTests.testFailsHealthOnIOException" \
  -Dtests.seed=383792DA00F947A9 \
  -Dtests.security.manager=true \
  -Dtests.locale=sv-SE \
  -Dtests.timezone=AGT \
  -Druntime.java=11
```

**Reproduces locally?**:
Unknown, Windows innit 

**Applicable branches**:
Master, 7.x

**Failure history**:
Regularly

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(branch,build_url,build.branch,build.console-url),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'FsHealthServiceTests%20testFailsHealthOnIOException'),sort:!(process.time-start,desc))

**Failure excerpt**:
```
java.lang.AssertionError: expected:<UNHEALTHY> but was:<HEALTHY>
	at __randomizedtesting.SeedInfo.seed([98825EFCB7B3E2A5:FC2CB339E1C9370]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.elasticsearch.monitor.fs.FsHealthServiceTests.testFailsHealthOnIOException(FsHealthServiceTests.java:119)
```

**Comment by davidkyle** [comment]
Muted on master: ef8b414ff86cd6de55987bb2630d6885520b05a9 and 7.x: 7dcd943e1d99798aa848b618d70da19473b25cbe
