### ISSUE TITLE
[CI] TimeSeriesDataStreamsIT.testShrinkActionInPolicyWithoutHotPhase Fails on 7.x

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#59399]
Seeing the following failure in https://gradle-enterprise.elastic.co/s/ejqcdrqr2xyim/console-log?anchor=6235 (7.x)

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:qa:multi-node:integTestRunner' --tests "org.elasticsearch.xpack.ilm.TimeSeriesDataStreamsIT.testShrinkActionInPolicyWithoutHotPhase" -Dtests.seed=5D3E4B2F86A913F0 -Dtests.security.manager=true -Dtests.locale=pt -Dtests.timezone=America/Blanc-Sablon -Druntime.java=8
```

fails with:

```
 java.lang.AssertionError: the original index must've been deleted
    Expected: is <false>
         but: was <true>
        at __randomizedtesting.SeedInfo.seed([5D3E4B2F86A913F0:68C0EF502787483F]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.xpack.ilm.TimeSeriesDataStreamsIT.testShrinkActionInPolicyWithoutHotPhase(TimeSeriesDataStreamsIT.java:96)
```

**Comment by dakrone** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/aidbqwgart5cq
