### ISSUE TITLE
Allow elastic search to only read files in template folder. Also if template is considered to be in JSON only, add a check for "*.json" extension. 

### ISSUE THREAD

**Issue by anandaverma** [elastic/elasticsearch#5956]
```
[2014-04-28 06:56:47,396][WARN ][cluster.metadata         ] [Batman(ES-Master)] [app-logstash-2013.05.01] failed to read template [/u001/logparser/tools/elasticsearch/config/templates/.svn] from config
java.io.FileNotFoundException: /u001/logparser/tools/elasticsearch/config/templates/.svn (Is a directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:137)
        at org.elasticsearch.common.io.Streams.copyToByteArray(Streams.java:84)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.findTemplates(MetaDataCreateIndexService.java:485)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.access$300(MetaDataCreateIndexService.java:86)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:175)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:300)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:135)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)
```

**Comment by clintongormley** [comment]
File-based index templates are no longer supported https://github.com/elastic/elasticsearch/pull/11052
