### ISSUE TITLE
EQL: index already created in RestEqlUsageTestCase

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#59619]
Not really an issue, but probably a check need to be added to have the index created or not. Probably created before by another IT class.

```
[endgame-1.4.0/fazm6elPRf6VY7AIXkHWHQ] ElasticsearchStatusException[Elasticsearch exception [type=resource_already_exists_exception, reason=index [endgame-1.4.0/fazm6elPRf6VY7AIXkHWHQ] already exists]]
	at __randomizedtesting.SeedInfo.seed([D498723550661908:5FD2845021625816]:0)
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:187)
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1892)
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1869)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1626)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1598)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1565)
	at org.elasticsearch.client.IndicesClient.create(IndicesClient.java:145)
	at org.elasticsearch.test.eql.DataLoader.createTestIndex(DataLoader.java:66)
	at org.elasticsearch.test.eql.DataLoader.loadDatasetIntoEs(DataLoader.java:58)
	at org.elasticsearch.test.eql.stats.RestEqlUsageTestCase.testEqlRestUsage(RestEqlUsageTestCase.java:122)
```

**Comment by astefan** [comment]
master (8.0.0): https://github.com/elastic/elasticsearch/pull/59745
7.x (7.10.0): https://github.com/elastic/elasticsearch/pull/59747
7.9 (7.9.0): https://github.com/elastic/elasticsearch/pull/59748
