### ISSUE TITLE
RestoreSnapshotRequestTests.testSource fails 

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#59641]
**Build scan**:
https://gradle-enterprise.elastic.co/s/zevkkqsykhsem

**Repro line**:
```
./gradlew ':server:test' --tests "org.elasticsearch.action.admin.cluster.snapshots.restore.RestoreSnapshotRequestTests.testSource" -Dtests.seed=CE7178843E73560F -Dtests.security.manager=true -Dtests.locale=sr-BA -Dtests.timezone=America/Argentina/La_Rioja -Druntime.java=11
```

**Reproduces locally?**:
Yes

**Applicable branches**:
master

**Failure excerpt**:

```
org.elasticsearch.action.admin.cluster.snapshots.restore.RestoreSnapshotRequestTests > testSource FAILED
    java.lang.AssertionError: expected: org.elasticsearch.action.admin.cluster.snapshots.restore.RestoreSnapshotRequest<{"indices":["cT","mnp"],"expand_wildcards":["open"],"ignore_unavailable":false,"allow_no_indices":true,"ignore_throttled":false,"rename_pattern":"忷̤?彠\uD9A1\uDF93\uDBAF\uDEC9艹\uDB88\uDEDA\uD821\uDEF0ܩ\uDB68\uDF5C◤湏\u001Eյ\uD894\uDCD2ȹ\nDﰅu[ꋸ\uDB79\uDFE5-","include_global_state":false,"partial":true,"include_aliases":false,"index_settings":{},"ignore_index_settings":[]}> but was: org.elasticsearch.action.admin.cluster.snapshots.restore.RestoreSnapshotRequest<{"indices":["cT","mnp"],"expand_wildcards":["open"],"ignore_unavailable":false,"allow_no_indices":true,"ignore_throttled":false,"rename_pattern":"忷̤?彠\uD9A1\uDF93\uDBAF\uDEC9艹\uDB88\uDEDA\uD821\uDEF0ܩ\uDB68\uDF5C◤湏\u001Eյ\uD894\uDCD2ȹ\nDﰅu[ꋸ\uDB79\uDFE5-","include_global_state":false,"partial":true,"include_aliases":false,"index_settings":{},"ignore_index_settings":[]}>
        at __randomizedtesting.SeedInfo.seed([CE7178843E73560F:4A26F83084AFFBDB]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.elasticsearch.action.admin.cluster.snapshots.restore.RestoreSnapshotRequestTests.testSource(RestoreSnapshotRequestTests.java:134)
```

**Comment by dakrone** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/iddyj3smqeaoq
