### ISSUE TITLE
A fault occurred in a recent unsafe memory access operation in compiled Java code

### ISSUE THREAD

**Issue by wenma** [elastic/elasticsearch#59744]
**Elasticsearch version** (`bin/elasticsearch --version`):
v7.7.0

**JVM version** (`java -version`):
buildin openjdk

**OS version** (`uname -a` if on a Unix-like system):
centos 7.3.1611

**Description of the problem including expected versus actual behavior**:
sometimes the ES process faulted. logs here:
```
Jul 17 11:44:51 <hostname> systemd[1]: Started Elasticsearch.
Jul 17 11:58:16 <hostname> elasticsearch[1854]: fatal error in thread [elasticsearch[data1_<hostname>][generic][T#7]], exiting
Jul 17 11:58:16 <hostname> elasticsearch[1854]: java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
Jul 17 11:58:16 <hostname> elasticsearch[1854]: at org.apache.lucene.store.BufferedChecksumIndexInput.readBytes(BufferedChecksumIndexInput.java:49)
Jul 17 11:58:16 <hostname> elasticsearch[1854]: at org.apache.lucene.store.DataInput.readBytes(DataInput.java:88)
Jul 17 11:58:16 <hostname> elasticsearch[1854]: at org.apache.lucene.store.DataInput.skipBytes(DataInput.java:338)
Jul 17 11:58:16 <hostname> elasticsearch[1854]: at org.apache.lucene.store.ChecksumIndexInput.seek(ChecksumIndexInput.java:52)
Jul 17 11:58:16 <hostname> elasticsearch[1854]: at org.apache.lucene.codecs.CodecUtil.checksumEntireFile(CodecUtil.java:525)
Jul 17 11:58:16 <hostname> elasticsearch[1854]: at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader.checkIntegrity(CompressingStoredFieldsReader.java:669)
Jul 17 11:58:16 <hostname> elasticsearch[1854]: at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.merge(CompressingStoredFieldsWriter.java:565)
Jul 17 11:58:16 <hostname> elasticsearch[1854]: at org.apache.lucene.index.SegmentMerger.mergeFields(SegmentMerger.java:229)
Jul 17 11:58:16 <hostname> elasticsearch[1854]: at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:106)
Jul 17 11:58:16 <hostname> elasticsearch[1854]: at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4463)
Jul 17 11:58:16 <hostname> elasticsearch[1854]: at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:4057)
Jul 17 11:58:16 <hostname> elasticsearch[1854]: at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:625)
Jul 17 11:58:16 <hostname> elasticsearch[1854]: at org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.doMerge(ElasticsearchConcurrentMergeScheduler.java:101)
Jul 17 11:58:16 <hostname> elasticsearch[1854]: at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:662)
Jul 17 11:58:17 <hostname> systemd[1]: elasticsearch-data1.service: main process exited, code=exited, status=128/n/a

```
it seems to be a JVM bug?

**Comment by original-brownbear** [comment]
@wenma it could be a JVM bug but more likely I think it is an issue with the underlying storage that ES is running on. I would make sure that there is no instabilities there.

That said this is not the place to track this kind of thing down I'm afraid as this appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
