### ISSUE TITLE
RepositoryAzureClientYamlTestSuiteIT test failing

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#59849]
**Build scan**:
https://gradle-enterprise.elastic.co/s/ke54ul3g3xvtw

**Repro line**:

```
REPRODUCE WITH: ./gradlew ':plugins:repository-azure:integTestRunner' --tests "org.elasticsearch.repositories.azure.RepositoryAzureClientYamlTestSuiteIT.test {yaml=repository_azure/20_repository/Snapshot/Restore with repository-azure}" \
  -Dtests.seed=DEBAABBB74FE0374 \
  -Dtests.security.manager=true \
  -Dtests.locale=mk-MK \
  -Dtests.timezone=America/Campo_Grande \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew ':plugins:repository-azure:integTestRunner' --tests "org.elasticsearch.repositories.azure.RepositoryAzureClientYamlTestSuiteIT.test {yaml=repository_azure/20_repository/Get a non existing snapshot}" \
  -Dtests.seed=DEBAABBB74FE0374 \
  -Dtests.security.manager=true \
  -Dtests.locale=mk-MK \
  -Dtests.timezone=America/Campo_Grande \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew ':plugins:repository-azure:integTestRunner' --tests "org.elasticsearch.repositories.azure.RepositoryAzureClientYamlTestSuiteIT.test {yaml=repository_azure/20_repository/Delete a non existing snapshot}" \
  -Dtests.seed=DEBAABBB74FE0374 \
  -Dtests.security.manager=true \
  -Dtests.locale=mk-MK \
  -Dtests.timezone=America/Campo_Grande \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew ':plugins:repository-azure:integTestRunner' --tests "org.elasticsearch.repositories.azure.RepositoryAzureClientYamlTestSuiteIT.test {yaml=repository_azure/20_repository/teardown}" \
  -Dtests.seed=DEBAABBB74FE0374 \
  -Dtests.security.manager=true \
  -Dtests.locale=mk-MK \
  -Dtests.timezone=America/Campo_Grande \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew ':plugins:repository-azure:integTestRunner' --tests "org.elasticsearch.repositories.azure.RepositoryAzureClientYamlTestSuiteIT.test {yaml=repository_azure/20_repository/Restore a non existing snapshot}" \
  -Dtests.seed=DEBAABBB74FE0374 \
  -Dtests.security.manager=true \
  -Dtests.locale=mk-MK \
  -Dtests.timezone=America/Campo_Grande \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew ':plugins:repository-azure:integTestRunner' --tests "org.elasticsearch.repositories.azure.RepositoryAzureClientYamlTestSuiteIT.test {yaml=repository_azure/20_repository/Register a repository with a non existing client}" \
  -Dtests.seed=DEBAABBB74FE0374 \
  -Dtests.security.manager=true \
  -Dtests.locale=mk-MK \
  -Dtests.timezone=America/Campo_Grande \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew ':plugins:repository-azure:integTestRunner' --tests "org.elasticsearch.repositories.azure.RepositoryAzureClientYamlTestSuiteIT.test {yaml=repository_azure/20_repository/Register a repository with a non existing container}" \
  -Dtests.seed=DEBAABBB74FE0374 \
  -Dtests.security.manager=true \
  -Dtests.locale=mk-MK \
  -Dtests.timezone=America/Campo_Grande \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew ':plugins:repository-azure:integTestRunner' --tests "org.elasticsearch.repositories.azure.RepositoryAzureClientYamlTestSuiteIT.test {yaml=repository_azure/20_repository/Snapshot/Restore with repository-azure}" \
  -Dtests.seed=DEBAABBB74FE0374 \
  -Dtests.security.manager=true \
  -Dtests.locale=mk-MK \
  -Dtests.timezone=America/Campo_Grande \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew ':plugins:repository-azure:integTestRunner' --tests "org.elasticsearch.repositories.azure.RepositoryAzureClientYamlTestSuiteIT.test {yaml=repository_azure/20_repository/Get a non existing snapshot}" \
  -Dtests.seed=DEBAABBB74FE0374 \
  -Dtests.security.manager=true \
  -Dtests.locale=mk-MK \
  -Dtests.timezone=America/Campo_Grande \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew ':plugins:repository-azure:integTestRunner' --tests "org.elasticsearch.repositories.azure.RepositoryAzureClientYamlTestSuiteIT.test {yaml=repository_azure/20_repository/Delete a non existing snapshot}" \
  -Dtests.seed=DEBAABBB74FE0374 \
  -Dtests.security.manager=true \
  -Dtests.locale=mk-MK \
  -Dtests.timezone=America/Campo_Grande \
  -Druntime.java=11
```

**Reproduces locally?**:
No

**Applicable branches**:
master

**Failure history**:

**Failure excerpt**:

```
10:46:42   1> [2020-07-20T04:46:41,810][INFO ][o.e.r.a.RepositoryAzureClientYamlTestSuiteIT] [test] [yaml=repository_azure/20_repository/Register a repository with a non existing client] before test
10:46:42   1> [2020-07-20T04:46:41,992][INFO ][o.e.r.a.RepositoryAzureClientYamlTestSuiteIT] [test] Stash dump on test failure [{
10:46:42   1>   "stash" : {
10:46:42   1>     "body" : {
10:46:42   1>       "error" : {
10:46:42   1>         "root_cause" : [
10:46:42   1>           {
10:46:42   1>             "type" : "repository_verification_exception",
10:46:42   1>             "reason" : "[repository] path [master_integration_tests] is not accessible on master node",
10:46:42   1>             "stack_trace" : "org.elasticsearch.repositories.RepositoryVerificationException: [repository] path [master_integration_tests] is not accessible on master node
10:46:42   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1172)
10:46:42   1> 	at org.elasticsearch.repositories.RepositoriesService$3.doRun(RepositoriesService.java:248)
10:46:42   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:706)
10:46:42   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
10:46:42   1> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
10:46:42   1> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
10:46:42   1> 	at java.base/java.lang.Thread.run(Thread.java:834)
10:46:42   1> Caused by: java.io.IOException: Can not write blob master.dat
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:117)
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlobAtomic(AzureBlobContainer.java:123)
10:46:42   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1167)
10:46:42   1> 	... 6 more
10:46:42   1> Caused by: com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
10:46:42   1> 	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87)
10:46:42   1> 	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305)
10:46:42   1> 	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:196)
10:46:42   1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:1035)
10:46:42   1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:864)
10:46:42   1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:743)
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobStore.lambda$writeBlob$18(AzureBlobStore.java:322)
10:46:42   1> 	at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:69)
10:46:42   1> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
10:46:42   1> 	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:68)
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:321)
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:115)
10:46:42   1> 	... 8 more
10:46:42   1> "
10:46:42   1>           }
10:46:42   1>         ],
10:46:42   1>         "type" : "repository_verification_exception",
10:46:42   1>         "reason" : "[repository] path [master_integration_tests] is not accessible on master node",
10:46:42   1>         "caused_by" : {
10:46:42   1>           "type" : "i_o_exception",
10:46:42   1>           "reason" : "Can not write blob master.dat",
10:46:42   1>           "caused_by" : {
10:46:42   1>             "type" : "storage_exception",
10:46:42   1>             "reason" : "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.",
10:46:42   1>             "stack_trace" : "com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
10:46:42   1> 	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87)
10:46:42   1> 	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305)
10:46:42   1> 	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:196)
10:46:42   1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:1035)
10:46:42   1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:864)
10:46:42   1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:743)
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobStore.lambda$writeBlob$18(AzureBlobStore.java:322)
10:46:42   1> 	at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:69)
10:46:42   1> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
10:46:42   1> 	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:68)
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:321)
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:115)
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlobAtomic(AzureBlobContainer.java:123)
10:46:42   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1167)
10:46:42   1> 	at org.elasticsearch.repositories.RepositoriesService$3.doRun(RepositoriesService.java:248)
10:46:42   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:706)
10:46:42   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
10:46:42   1> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
10:46:42   1> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
10:46:42   1> 	at java.base/java.lang.Thread.run(Thread.java:834)
10:46:42   1> "
10:46:42   1>           },
10:46:42   1>           "stack_trace" : "java.io.IOException: Can not write blob master.dat
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:117)
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlobAtomic(AzureBlobContainer.java:123)
10:46:42   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1167)
10:46:42   1> 	at org.elasticsearch.repositories.RepositoriesService$3.doRun(RepositoriesService.java:248)
10:46:42   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:706)
10:46:42   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
10:46:42   1> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
10:46:42   1> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
10:46:42   1> 	at java.base/java.lang.Thread.run(Thread.java:834)
10:46:42   1> Caused by: com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
10:46:42   1> 	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87)
10:46:42   1> 	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305)
10:46:42   1> 	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:196)
10:46:42   1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:1035)
10:46:42   1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:864)
10:46:42   1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:743)
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobStore.lambda$writeBlob$18(AzureBlobStore.java:322)
10:46:42   1> 	at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:69)
10:46:42   1> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
10:46:42   1> 	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:68)
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:321)
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:115)
10:46:42   1> 	... 8 more
10:46:42   1> "
10:46:42   1>         },
10:46:42   1>         "stack_trace" : "org.elasticsearch.repositories.RepositoryVerificationException: [repository] path [master_integration_tests] is not accessible on master node
10:46:42   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1172)
10:46:42   1> 	at org.elasticsearch.repositories.RepositoriesService$3.doRun(RepositoriesServ  1> ice.java:248)
10:46:42   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:706)
10:46:42   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
10:46:42   1> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
10:46:42   1> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
10:46:42   1> 	at java.base/java.lang.Thread.run(Thread.java:834)
10:46:42   1> Caused by: java.io.IOException: Can not write blob master.dat
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:117)
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlobAtomic(AzureBlobContainer.java:123)
10:46:42   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:1167)
10:46:42   1> 	... 6 more
10:46:42   1> Caused by: com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
10:46:42   1> 	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87)
10:46:42   1> 	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305)
10:46:42   1> 	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:196)
10:46:42   1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:1035)
10:46:42   1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:864)
10:46:42   1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:743)
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobStore.lambda$writeBlob$18(AzureBlobStore.java:322)
10:46:42   1> 	at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:69)
10:46:42   1> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
10:46:42   1> 	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:68)
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:321)
10:46:42   1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:115)
10:46:42   1> 	... 8 more
10:46:42   1> "
10:46:42   1>       },
10:46:42   1>       "status" : 500
10:46:42   1>     }
10:46:42   1>   }
10:46:42   1> }]
10:46:42   1> [2020-07-20T04:46:42,041][INFO ][o.e.r.a.RepositoryAzureClientYamlTestSuiteIT] [test] [yaml=repository_azure/20_repository/Register a repository with a non existing client] after test

```

**Comment by original-brownbear** [comment]
I think this is just the SAS tokens used by CI having expired. I opened an issue for infra to look into this.

**Comment by przemekwitek** [comment]
Another occurrence on `6.8`: https://gradle-enterprise.elastic.co/s/hbywknxdhjrfe

**Comment by original-brownbear** [comment]
I think for now all SAS token based test runs are broken. Test triage can ignore this issue for now until it's fixed I think, only infra can save us here.

**Comment by przemekwitek** [comment]
> Test triage can ignore this issue for now until it's fixed I think, only infra can save us here.

Thanks for checking, @original-brownbear !

**Comment by original-brownbear** [comment]
Infra fixed this now and I just got a clean build for this on master. This should return to green for the other branches on the next execution of their 3rd party tests as well => closing

**Comment by original-brownbear** [comment]
Infra fixed this now and I just got a clean build for this on master. This should return to green for the other branches on the next execution of their 3rd party tests as well => closing
