### ISSUE TITLE
GeoGridTilerTests.testGeoHashGridCircuitBreaker test failures on 7.9, 7.x and master during last few days

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#59853]
**Build scan**:

https://gradle-enterprise.elastic.co/s/exgal5veba75y

**Repro line**:
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:spatial:test' --tests "org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoGridTilerTests.testGeoHashGridCircuitBreaker" \
  -Dtests.seed=B2A327D756BB8DB \
  -Dtests.security.manager=true \
  -Dtests.locale=ca-ES \
  -Dtests.timezone=Europe/Monaco \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':x-pack:plugin:spatial:test' --tests "org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoGridTilerTests.testGeoHashGridCircuitBreaker" \
  -Dtests.seed=B2A327D756BB8DB \
  -Dtests.security.manager=true \
  -Dtests.locale=ca-ES \
  -Dtests.timezone=Europe/Monaco \
  -Druntime.java=8
```

**Reproduces locally?**:
No

**Applicable branches**:
`7.9`, `7.x`, `master`

**Failure history**:
4 failures:
https://gradle-enterprise.elastic.co/s/exgal5veba75y
https://gradle-enterprise.elastic.co/s/7tp4ufm4raoh6
https://gradle-enterprise.elastic.co/s/e4wgxvxqsvk3u
https://gradle-enterprise.elastic.co/s/ooaycjzm5oalu

**Failure excerpt**:

```
12:55:42 java.lang.OutOfMemoryError: Java heap space
12:55:42 Dumping heap to /dev/shm/elastic+elasticsearch+7.9+multijob+fast+part2/x-pack/plugin/spatial/build/heapdump/java_pid87501.hprof ...
12:55:42 Heap dump file created [52163801 bytes in 0.201 secs]
12:55:42 
12:55:42 
12:55:42 org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoGridTilerTests > testGeoHashGridCircuitBreaker FAILED
12:55:42     java.lang.OutOfMemoryError: Java heap space
12:55:42         at __randomizedtesting.SeedInfo.seed([B2A327D756BB8DB:492673E5DC68A259]:0)
12:55:42         at org.apache.lucene.util.ArrayUtil.growExact(ArrayUtil.java:323)
12:55:42         at org.elasticsearch.index.fielddata.SortingNumericDocValues.resize(SortingNumericDocValues.java:87)
12:55:42         at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoShapeCellValues.resizeCell(GeoShapeCellValues.java:47)
12:55:42         at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoHashGridTiler.setValuesByRasterization(GeoHashGridTiler.java:102)
12:55:42         at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoHashGridTiler.setValues(GeoHashGridTiler.java:39)
12:55:42         at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoGridTilerTests.testCircuitBreaker(GeoGridTilerTests.java:478)
12:55:42         at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoGridTilerTests.testGeoHashGridCircuitBreaker(GeoGridTilerTests.java:460)
12:55:44 REPRODUCE WITH: ./gradlew ':x-pack:plugin:spatial:test' --tests "org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoGridTilerTests.testGeoHashGridCircuitBreaker" -Dtests.seed=B2A327D756BB8DB -Dtests.security.manager=true -Dtests.locale=ca-ES -Dtests.timezone=Europe/Monaco -Druntime.java=8
12:55:44 
12:55:44 Suite: Test class org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoGridTilerTests
1
```

**Comment by talevy** [comment]
sorry. investigating this again! kind of surprised this is happening so frequently now
