### ISSUE TITLE
Test failure in IndexingIT::testIndexing

### ISSUE THREAD

**Issue by danhermann** [elastic/elasticsearch#59935]
**Build scan**: https://gradle-enterprise.elastic.co/s/4jme3x7byxxve

**Repro line**: `./gradlew ':qa:rolling-upgrade:v7.8.1#oldClusterTest' --tests "org.elasticsearch.upgrades.IndexingIT.testIndexing" -Dtests.seed=12DF798394B5D8E2 -Dtests.security.manager=true -Dtests.locale=ms-MY -Dtests.timezone=SystemV/MST7 -Druntime.java=8`

**Reproduces locally?**: No

**Applicable branches**: `7.9`

**Failure excerpt**:

```
org.elasticsearch.upgrades.IndexingIT > testIndexing FAILED |  -- | --
  | org.elasticsearch.client.WarningFailureException: method [PUT], host [http://[::1]:33059], URI [/test_index], status line [HTTP/1.1 200 OK] |  
  | Warnings: [index [test_index] matches multiple legacy templates [global, prevent-bwc-deprecation-template], composable templates will only match a single template] |  
  | {"acknowledged":true,"shards_acknowledged":true,"index":"test_index"} |  
  | at __randomizedtesting.SeedInfo.seed([12DF798394B5D8E2:F605368AB2C09B69]:0) |  
  | at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:298) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:272) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) |  
  | at org.elasticsearch.upgrades.IndexingIT.testIndexing(IndexingIT.java:99)
```

**Comment by dimitris-athanasiou** [comment]
Same failure in `7.x`. See https://gradle-enterprise.elastic.co/s/2dtnwgdhcgrw6

Should we backport the fix to `7.x` too?

**Comment by danhermann** [comment]
@dimitris-athanasiou, yes, I'll backport it to `7.x` momentarily.

**Comment by danhermann** [comment]
Backported in https://github.com/elastic/elasticsearch/pull/60482

**Comment by nik9000** [comment]
I'm seeing this [again](https://gradle-enterprise.elastic.co/s/a6kevvzmo6f5e/console-log/raw) in 7.x:
```

Suite: Test class org.elasticsearch.upgrades.IndexingIT
  1> [2020-08-04T14:45:23,120][INFO ][o.e.u.IndexingIT         ] [testIndexing] before test
  1> [2020-08-04T14:45:23,124][INFO ][o.e.u.IndexingIT         ] [testIndexing] initializing REST clients against [http://[::1]:42379, http://127.0.0.1:35663, http://[::1]:42865, http://127.0.0.1:36535, http://[::1]:34867, http://127.0.0.1:42215]
  2> अगस्त ०४, २०२० २:४५:२३ अपराह्न org.elasticsearch.client.RestClient logResponse
  2> WARNING: request [PUT http://127.0.0.1:42215/test_index] returned 1 warnings: [299 Elasticsearch-7.8.2-SNAPSHOT-fc175e9c459bec829e6b4627356259d60fe1e103 "index [test_index] matches multiple legacy templates [global, prevent-bwc-deprecation-template], composable templates will only match a single template"]
  1> [2020-08-04T14:45:23,417][INFO ][o.e.u.IndexingIT         ] [testIndexing] after test
  2> REPRODUCE WITH: ./gradlew ':qa:rolling-upgrade:v7.8.2#oldClusterTest' --tests "org.elasticsearch.upgrades.IndexingIT.testIndexing" -Dtests.seed=4BC66A97521B33D0 -Dtests.security.manager=true -Dtests.locale=hi-IN -Dtests.timezone=America/Grenada -Druntime.java=8
  2> org.elasticsearch.client.WarningFailureException: method [PUT], host [http://127.0.0.1:42215], URI [/test_index], status line [HTTP/1.1 200 OK]
    Warnings: [index [test_index] matches multiple legacy templates [global, prevent-bwc-deprecation-template], composable templates will only match a single template]
    {"acknowledged":true,"shards_acknowledged":true,"index":"test_index"}
        at __randomizedtesting.SeedInfo.seed([4BC66A97521B33D0:AF1C259E746E705B]:0)
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:298)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:272)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246)
        at org.elasticsearch.upgrades.IndexingIT.testIndexing(IndexingIT.java:100)
  1> [2020-08-04T14:45:23,479][INFO ][o.e.u.IndexingIT         ] [testAutoIdWithOpTypeCreate] before test
  1> [2020-08-04T14:45:23,590][INFO ][o.e.u.IndexingIT         ] [testAutoIdWithOpTypeCreate] after test
  2> NOTE: leaving temporary files on disk at: /dev/shm/elastic+elasticsearch+7.x+multijob+fast+bwc/qa/rolling-upgrade/build/testrun/v7.8.2#oldClusterTest/temp/org.elasticsearch.upgrades.IndexingIT_4BC66A97521B33D0-001
  2> NOTE: test params are: codec=Asserting(Lucene86): {}, docValues:{}, maxPointsInLeafNode=1416, maxMBSortInHeap=7.354752674619167, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=hi-IN, timezone=America/Grenada
  2> NOTE: Linux 4.15.0-1080-gcp amd64/Oracle Corporation 1.8.0_241 (64-bit)/cpus=32,threads=1,free=476963776,total=514850816
  2> NOTE: All tests run in this JVM: [XPackIT, UpgradeClusterClientYamlTestSuiteIT, RecoveryIT, MappingIT, JodaCompatibilityIT, IndexingIT]

```

**Comment by danhermann** [comment]
I missed a backport to 7.x that I've just now merged (https://github.com/elastic/elasticsearch/pull/60682) that should fix this.
