### ISSUE TITLE
AutoFollowIT.testAutoFollowParameterAreDelegated failure

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#59952]
**Build scan**:

https://gradle-enterprise.elastic.co/s/mupt6hgagq5zw

**Repro line**:

./gradlew ':x-pack:plugin:ccr:internalClusterTest' --tests "org.elasticsearch.xpack.ccr.AutoFollowIT.testAutoFollowParameterAreDelegated" \
  -Dtests.seed=B9F4B0CE61B09DE3 \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-JO \
  -Dtests.timezone=America/Dawson \
  -Druntime.java=11

**Reproduces locally?**:

No

**Applicable branches**:

master

**Failure history**:

occasional similar looking failures

**Failure excerpt**:

```
java.lang.AssertionError: 
Expected: <1L>
     but: was <0L>
	at __randomizedtesting.SeedInfo.seed([22FE3E639FD78A7:9DDD5B0F7B8AE948]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.ccr.AutoFollowIT.lambda$testAutoFollowSoftDeletesDisabled$12(AutoFollowIT.java:395)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:951)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:924)
	at org.elasticsearch.xpack.ccr.AutoFollowIT.testAutoFollowSoftDeletesDisabled(AutoFollowIT.java:393)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at 
```

This looks related to  #56891 and a timeout issue supposedly fixed by https://github.com/elastic/elasticsearch/pull/56910, maybe this needs another increase or another look.

**Comment by cbuescher** [comment]
And another one earlier today: https://gradle-enterprise.elastic.co/s/mupt6hgagq5zw
