### ISSUE TITLE
[CI] SLMSnapshotBlockingIntegTests.testSLMRetentionAfterRestore failure

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#59956]
**Build scan**:

https://gradle-enterprise.elastic.co/s/7qn5kbuvv52le

**Repro line**:

./gradlew ':x-pack:plugin:ilm:test' --tests "org.elasticsearch.xpack.slm.SLMSnapshotBlockingIntegTests.testSLMRetentionAfterRestore" \
  -Dtests.seed=FC982EB81E7E317B \
  -Dtests.security.manager=true \
  -Dtests.locale=es-AR \
  -Dtests.timezone=Asia/Taipei \
  -Druntime.java=11

**Reproduces locally?**:

No

**Applicable branches**:

master

**Failure excerpt**:

```
java.lang.AssertionError: 
Expected: an empty collection
     but: <[SnapshotInfo{snapshotId=snap-nrdpzrxorlsfo3lgnjowfg/lYLY8csgRbWBJ3P0BsShxQ, state=SUCCESS, reason='null', indices=[test], startTime=1595305966745, endTime=1595305967572, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[]}]>
	at __randomizedtesting.SeedInfo.seed([FC982EB81E7E317B:EDAE146EB0D0B1AB]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.slm.SLMSnapshotBlockingIntegTests.lambda$testSLMRetentionAfterRestore$11(SLMSnapshotBlockingIntegTests.java:427)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:897)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:870)
	at org.elasticsearch.xpack.slm.SLMSnapshotBlockingIntegTests.testSLMRetentionAfterRestore(SLMSnapshotBlockingIntegTests.java:423)
```

This is possible related to https://github.com/elastic/elasticsearch/issues/59140, but the method failing here is `testSLMRetentionAfterRestore` and the error looks a bit different. Opening as a separate issue, but feel free to close if the two are connected.

**Comment by original-brownbear** [comment]
This is not the same as #59140. This one looks like the result of a very slow CI run  (snapshot creation taking ~4s and deletion ~12s for trivial snapshots ... I'll fix this by increasing the test timeout that we hit here).
