### ISSUE TITLE
[CI] Failure in NetworkDisruptionIT.testJobRelocation 

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#60000]
**Build scan**:

https://gradle-enterprise.elastic.co/s/ldu5q6cjmrmn4

**Repro line**:

./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.NetworkDisruptionIT.testJobRelocation" \
  -Dtests.seed=A39CE63DA6870781 \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-IQ \
  -Dtests.timezone=Atlantic/Cape_Verde \
  -Druntime.java=11

**Reproduces locally?**:

No

**Failure excerpt**:

```
java.lang.AssertionError: failed to reach a stable cluster of [4] nodes. Tried via [node_t4]. last cluster state:
cluster uuid: VlGACP98Q46thuYCkMFFxg [committed: true]
version: 50
state uuid: dwDlKm0jRXimzIYgSB4S0A
from_diff: false
meta data version: 45
   coordination_metadata:
      term: 1
      last_committed_config: VotingConfiguration{YSZc8ao2Q-iLugkx5FHZ7Q,oQ4N3m77Rtq6C4B-vtXCbg,AG6GrlTpQ5-uLGMgpmxKCg}
      last_accepted_config: VotingConfiguration{YSZc8ao2Q-iLugkx5FHZ7Q,oQ4N3m77Rtq6C4B-vtXCbg,AG6GrlTpQ5-uLGMgpmxKCg}
      voting tombstones: []
   [.ml-anomalies-shared/BFyo0u1lS3eljqwVFVWPmg]: v[12], mv[1], sv[2], av[2]
      0: p_term [2], isa_ids [WrGV5W7aSYapLyKfVnSYHQ, 04-eqLwDTpet6LLczTCQQg]
   [.ml-notifications-000001/0y9fICxHT-yZ14__tRotqQ]: v[9], mv[1], sv[2], av[1]
      0: p_term [2], isa_ids [qRmilhScQ3KyOGLvvVStDA, MbfIpUpNSniOnHqx-AWX7Q]
   [.ml-state-000001/sDIdd0aHSLWCPyAZk1IIvQ]: v[10], mv[1], sv[2], av[1]
      0: p_term [1], isa_ids [WiMa0NPVThSmgkMyhT8WDg, hautRcG4RiK7J80MZ-OfJQ]
   [.ml-annotations-6/YChS2cdiQeW5kHvdTNQKZg]: v[9], mv[1], sv[2], av[2]
      0: p_term [1], isa_ids [TrpVnzsUTO-5svEkSMXT-g, Gq1HAJb_QMKGOg3ScNxbJA]
   [.ml-config/f3WRte2fSb6b5dE6s1zB0Q]: v[6], mv[1], sv[2], av[1]
      0: p_term [1], isa_ids [BTiavEIlSGigoRdFvHIK3g, lsmj4qCqSLqN-gyDiEJQYg]
metadata customs:
   index-graveyard: IndexGraveyard[[]]   ingest: org.elasticsearch.ingest.IngestMetadata@398db12a   persistent_tasks: {"last_allocation_id":2,"tasks":[{"id":"job-relocation-job","task":{"xpack/ml/job":{"params":{"job_id":"relocation-job","timeout":"1800000ms","job":{"job_id":"relocation-job","job_type":"anomaly_detector","job_version":"8.0.0","create_time":1595349606397,"analysis_config":{"bucket_span":"5m","detectors":[{"detector_description":"count","function":"count","detector_index":0}],"influencers":[]},"analysis_limits":{"model_memory_limit":"2mb","categorization_examples_limit":4},"data_description":{"time_field":"time","time_format":"epoch_ms"},"model_snapshot_retention_days":10,"daily_model_snapshot_retention_after_days":1,"results_index_name":"shared","allow_lazy_open":false}},"state":{"state":"opened","allocation_id":1}}},"allocation_id":2,"assignment":{"executor_node":null,"explanation":"awaiting reassignment after node loss"},"allocation_id_on_last_status_update":1}]}   index_lifecycle: {
  "policies" : {
    "ml-size-based-ilm-policy" : {
      "policy" : {
        "phases" : {
          "hot" : {
            "min_age" : "0ms",
            "actions" : {
              "rollover" : {
                "max_size" : "50gb"
              }
            }
          }
        }
      },
      "headers" : { },
      "version" : 1,
      "modified_date" : 1595349588886,
      "modified_date_string" : "2020-07-21T16:39:48.886Z"
    },
    "slm-history-ilm-policy" : {
      "policy" : {
        "phases" : {
          "hot" : {
            "min_age" : "0ms",
            "actions" : {
              "rollover" : {
                "max_size" : "50gb",
                "max_age" : "30d"
              }
            }
          },
          "delete" : {
            "min_age" : "90d",
            "actions" : {
              "delete" : {
                "delete_searchable_snapshot" : true
              }
            }
          }
        }
      },
      "headers" : { },
      "version" : 1,
      "modified_date" : 1595349587821,
      "modified_date_string" : "2020-07-21T16:39:47.821Z"
    }
  },
  "operation_mode" : "RUNNING"
}
```

**Comment by imotov** [comment]
Failed again on 7.x https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_RUNTIME_JAVA=zulu11,nodes=general-purpose/266/console

**Comment by cbuescher** [comment]
Another one on master today: https://gradle-enterprise.elastic.co/s/pehluzunpg6zi

**Comment by fcofdez** [comment]
Another instance on main https://gradle-enterprise.elastic.co/s/43svsjgqqwgaw/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.NetworkDisruptionIT/testJobRelocation?top-execution=1

**Comment by droberts195** [comment]
The latest failure is slightly different to before.  It's hung while cleaning up after the test and eventually hit the test time limit.  One stack trace from the thread dump at timeout is this:

```
"TEST-NetworkDisruptionIT.testJobRelocation-seed#[555ABD8A97241A7E]" ID=2294 WAITING on java.util.concurrent.CountDownLatch$Sync@7dfe8bab
	at java.base@18.0.2/jdk.internal.misc.Unsafe.park(Native Method)
	- waiting on java.util.concurrent.CountDownLatch$Sync@7dfe8bab
	at java.base@18.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	at java.base@18.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
	at java.base@18.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1047)
	at java.base@18.0.2/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
	at app//org.elasticsearch.transport.ClusterConnectionManager.internalClose(ClusterConnectionManager.java:334)
	at app//org.elasticsearch.transport.ClusterConnectionManager.close(ClusterConnectionManager.java:320)
	at app//org.elasticsearch.test.transport.StubbableConnectionManager.close(StubbableConnectionManager.java:115)
	at app//org.elasticsearch.core.IOUtils.close(IOUtils.java:71)
	at app//org.elasticsearch.core.IOUtils.close(IOUtils.java:87)
	at app//org.elasticsearch.core.IOUtils.close(IOUtils.java:63)
	at app//org.elasticsearch.transport.TransportService.doStop(TransportService.java:331)
	at app//org.elasticsearch.test.transport.MockTransportService.doStop(MockTransportService.java:682)
	at app//org.elasticsearch.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:63)
	- locked org.elasticsearch.common.component.Lifecycle@7eec2d04
	at app//org.elasticsearch.node.Node.stop(Node.java:1381)
	at app//org.elasticsearch.node.Node.close(Node.java:1400)
	- locked org.elasticsearch.common.component.Lifecycle@143a6041
	- locked org.elasticsearch.node.MockNode@4fdb715f
	at app//org.elasticsearch.test.InternalTestCluster$NodeAndClient.close(InternalTestCluster.java:1054)
	at app//org.elasticsearch.core.IOUtils.close(IOUtils.java:71)
	at app//org.elasticsearch.core.IOUtils.close(IOUtils.java:119)
	at app//org.elasticsearch.test.InternalTestCluster.close(InternalTestCluster.java:905)
	- locked org.elasticsearch.test.InternalTestCluster@62650eee
	at app//org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:579)
	at app//org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2235)
	at java.base@18.0.2/java.lang.invoke.DirectMethodHandle$Holder.invokeSpecial(DirectMethodHandle$Holder)
```

The log for the failing test is in https://gradle-enterprise.elastic.co/s/43svsjgqqwgaw/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.NetworkDisruptionIT/testJobRelocation/1/output

At a glance it looks like the post test cleanup is spinning because the cluster isn't well formed.

But the disruption was stopped during the test before the post test cleanup ran:

```
[2022-07-27T02:44:46,357][INFO ][o.e.t.d.NetworkDisruption] [testJobRelocation] stop disrupting (disruption scheme: network disconnects, disrupted links: two partitions (partition 1: [node_t2] and partition 2: [node_t4, node_t3, node_t1, node_t0]))
```

**Comment by droberts195** [comment]
Actually I notice that #88810 also occurred in the same test run as the most recent failure, and `BasicDistributedJobsIT.testMaxConcurrentJobAllocations` ran before `NetworkDisruptionIT.testJobRelocation`, so I wonder if there was any spillover from the failed test to subsequent tests.

Now #88810 is fixed let's see if this recurs.

**Comment by droberts195** [comment]
> Now https://github.com/elastic/elasticsearch/issues/88810 is fixed let's see if this recurs.

No more reports since last July - closing.
