### ISSUE TITLE
Bootstrap method initialization exception

### ISSUE THREAD

**Issue by dpadasala93** [elastic/elasticsearch#60174]
Hi Team,

Using java-high-level-rest client when we call getMapping for index or create index functions below errors get generated every time. almost for all the index related calls are generating this exception.

bootstrap method initialization exception
at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:194)
at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)
at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:259)
at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:249)
at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1883)
at org.elasticsearch.client.RestHighLevelClient.lambda$performRequestAndParseEntity$9(RestHighLevelClient.java:1564)
at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1628)
at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1596)
at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1563)
at org.elasticsearch.client.IndicesClient.getMapping(IndicesClient.java:282)

Caused by: java.lang.invoke.LambdaConversionException: Invalid receiver type interface org.apache.http.Header; not a subtype of implementation type interface org.apache.http.NameValuePair
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:254)
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:327)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:127)

I am using below environments

elasticsearch - 7.8.0.
openJDK - 11 and 14, JDK 1.8
elasticsearch-rest-high-level-client-7.8.0.jar and its dependencies included in pom.xml
Operation System : Tried both Windows 10 and Linux Mint.

**Comment by matriv** [comment]
Can you please include the code snippet that you use?

**Comment by dpadasala93** [comment]
RestClientBuilder builder = RestClient.builder(new HttpHost("localhost", 9200, "http"));
            builder.setRequestConfigCallback(requestConfigBuilder -> requestConfigBuilder.setConnectTimeout(60 * 1000).setSocketTimeout(60 * 1000)
                    .setConnectionRequestTimeout(60 * 1000));

            RestHighLevelClient client = new RestHighLevelClient(builder);

            String index = "events";

            GetIndexRequest getIndexRequest = new GetIndexRequest(index);

            if(!client.indices().exists(getIndexRequest, RequestOptions.DEFAULT))
            {
                CreateIndexRequest createIndexRequest = new CreateIndexRequest(index);

                createIndexRequest.alias(new Alias(index + "_write"));

                createIndexRequest.settings(Settings.builder().put("index.number_of_shards", 4)
                        .put( "index.number_of_replicas",0 ));

                CreateIndexResponse createIndexResponse = client.indices().create(createIndexRequest,RequestOptions.DEFAULT);

                System.out.println(createIndexResponse.index());
            }

**Comment by dpadasala93** [comment]
Now i have changed high level rest client version to 7.7.1 and it is working fine...

In 7.8.0 client, Below code snippet is creating issue which is not available in 7.7.1...

ClassName : RestHighLevelClient
MethodName : parseEntity
Line No : 1883

**HttpEntity entity = (HttpEntity)Optional.ofNullable(httpEntity.getContentEncoding()).map(NameValuePair::getValue).filter("gzip"::equalsIgnoreCase).map((gzipHeaderValue) -> {
                return new GzipDecompressingEntity(httpEntity);
            }).orElse(httpEntity);**

**Comment by swallez** [comment]
@dpadasala93 your issue seems very much like #61664. Can you check if there are several versions of `httpcore.jar` in your classpath?

If this is the case, you should either make sure there's only one version, or [shade the version used by the Elasticsearch client](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-low-usage-shading.html) to avoid conflicts between the two versions.

**Comment by swallez** [comment]
Closing, this is a classpath conflict in the application.
