### ISSUE TITLE
RegressionIT.testAliasFields is failing

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#60212]
**Build scan**:
https://gradle-enterprise.elastic.co/s/vjebbutdxi44g
**Repro line**:
```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testAliasFields" -Dtests.seed=4C8CA3AF936CD948 -Dtests.security.manager=true -Dtests.locale=ko-KR -Dtests.timezone=Australia/Broken_Hill -Druntime.java=11
```
**Reproduces locally?**:
Yes
**Applicable branches**:
main, 7.9, 7.x
**Failure excerpt**:
```
org.elasticsearch.xpack.ml.integration.RegressionIT > testAliasFields FAILED
    java.lang.AssertionError: 
    Expected: a numeric value within <10.0> of <468.0>
         but: <478.1716820377456> differed by <0.17168203774559743> more than delta <10.0>
        at __randomizedtesting.SeedInfo.seed([4C8CA3AF936CD948:7AF2C5FC13CBA4AE]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ml.integration.RegressionIT.testAliasFields(RegressionIT.java:553)
```

**Comment by dimitris-athanasiou** [comment]
Unfortunately the error margin I had originally used is not enough. I had run the test a bunch of times and looked at the max error I was getting. I doubled that and rounded it to 10. It seems we need to relax that further. I'll work on a PR to fix and unmute the tests.
