### ISSUE TITLE
[CI] Failure in ConcurrentSnapshotsIT.testMasterFailOverWithQueuedDeletes

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#60262]
This failed yesterday on `master` in https://gradle-enterprise.elastic.co/s/xzsmn2fpzfvfq/tests/:server:internalClusterTest/org.elasticsearch.snapshots.ConcurrentSnapshotsIT/testMasterFailOverWithQueuedDeletes#1

```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.ConcurrentSnapshotsIT.testMasterFailOverWithQueuedDeletes" -Dtests.seed=8A6CB23CE2AB701E -Dtests.security.manager=true -Dtests.locale=es-AR -Dtests.timezone=Africa/Maputo -Druntime.java=11
```

failed with

```
  2> REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.ConcurrentSnapshotsIT.testMasterFailOverWithQueuedDeletes" -Dtests.seed=8A6CB23CE2AB701E -Dtests.security.manager=true -Dtests.locale=es-AR -Dtests.timezone=Africa/Maputo -Druntime.java=11
  2> java.util.concurrent.ExecutionException: org.elasticsearch.transport.RemoteTransportException: [node_t2][127.0.0.1:35412][cluster:admin/snapshot/delete]
        at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:273)
        at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:260)
        at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:87)
        at org.elasticsearch.snapshots.ConcurrentSnapshotsIT.testMasterFailOverWithQueuedDeletes(ConcurrentSnapshotsIT.java:471)

        Caused by:
        org.elasticsearch.transport.RemoteTransportException: [node_t2][127.0.0.1:35412][cluster:admin/snapshot/delete]

            Caused by:
            org.elasticsearch.repositories.RepositoryException: [_all] Failed to update cluster state during repository operation
                at org.elasticsearch.snapshots.SnapshotsService.failAllListenersOnMasterFailOver(SnapshotsService.java:1645)
                at org.elasticsearch.snapshots.SnapshotsService$4.onFailure(SnapshotsService.java:982)
                at org.elasticsearch.cluster.ClusterStateTaskListener.onNoLongerMaster(ClusterStateTaskListener.java:37)
                at org.elasticsearch.cluster.service.MasterService$SafeClusterStateTaskListener.onNoLongerMaster(MasterService.java:519)
                at org.elasticsearch.cluster.service.MasterService$TaskInputs.lambda$onNoLongerMaster$0(MasterService.java:762)
                at java.util.ArrayList.forEach(ArrayList.java:1540)
                at org.elasticsearch.cluster.service.MasterService$TaskInputs.onNoLongerMaster(MasterService.java:762)
                at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:209)
                at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151)
                at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
                at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
                at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:647)
                at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
                at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at java.lang.Thread.run(Thread.java:834)

                Caused by:
                org.elasticsearch.cluster.NotMasterException: no longer master. source: [Run ready deletions]

    java.lang.IllegalStateException: Cannot cleanup [test-repo] - a snapshot is currently being deleted in [SnapshotDeletionsInProgress[[snapshot-two/Vxpgt46xTMy_3_nNvTN_jg, snapshot-three/4sKAbQTHSrmndqU9eWIZLQ, snapshot-one/A40QWDLnTcyKsVU1OD9jug]]]
        at org.elasticsearch.action.admin.cluster.repositories.cleanup.TransportCleanupRepositoryAction$2.execute(TransportCleanupRepositoryAction.java:183)
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47)
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:697)
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:319)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:214)
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:647)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
```

... looking into it. Reproduces locally at a rate of ~1/1000

**Comment by original-brownbear** [comment]
Tracked this down. It's the same issue that sprung up in a different context in https://github.com/elastic/elasticsearch/pull/60095 where a master node continues to do some work after finalizing a snapshot and resolving the respective listeners. I'll try to find a more general solution to this in tests.

**Comment by polyfractal** [comment]
In case it is helpful, looks like it just failed in 7.x: [Build Scan](https://gradle-enterprise.elastic.co/s/g2vjca46hzjl6) ([log](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+fast+part1/1147/consoleFull))
