### ISSUE TITLE
RestHighLevelClient re-connect on connection reset

### ISSUE THREAD

**Issue by raderio** [elastic/elasticsearch#60450]
I am using Spring + RestHighLevelClient to send data to Elasticsearch
```
restHighLevelClient.search(searchRequest, RequestOptions.DEFAULT)
```
But when the system has been idle for a while, the following exception is thrown
```
java.io.IOException: Connection reset by peer,
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:828) ~[elasticsearch-rest-client-7.6.2.jar!/:7.6.2],
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:248) ~[elasticsearch-rest-client-7.6.2.jar!/:7.6.2],
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235) ~[elasticsearch-rest-client-7.6.2.jar!/:7.6.2],
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1514) ~[elasticsearch-rest-high-level-client-7.6.2.jar!/:7.6.2],
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1484) ~[elasticsearch-rest-high-level-client-7.6.2.jar!/:7.6.2],
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1454) ~[elasticsearch-rest-high-level-client-7.6.2.jar!/:7.6.2],
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:970) ~[elasticsearch-rest-high-level-client-7.6.2.jar!/:7.6.2],
```
Please add possibility to specify to re-connect in case of reset.
For example this ca be added to RequestOptions.

**Comment by iadc2005** [comment]
Dear experts, we are also facing the same issue with the "connection reset by peer" issue and we were blocked for 4 weeks... has there any update on this issue? Thanks!

**Comment by sgnieto** [comment]
Same issue:

Caused by: com.confirma.listmanager.lists.index.IndexOperationException: test exist Index
	at com.confirma.listmanager.lists.index.IndexOperationManager.indexExists(IndexOperationManager.java:93)
	at com.confirma.listmanager.lists.index.ListIndexManager.indexExists(ListIndexManager.java:35)
	at com.confirma.listmanager.lists.jobs.ImportListJobsConfig.lambda$createPrepareIndexesStep$4(ImportListJobsConfig.java:742)
	... 45 common frames omitted
Caused by: java.io.IOException: Se ha forzado la interrupciÃ³n de una conexiÃ³n existente por el host remoto
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:828)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:248)

**Comment by gaurav-tanwar-gt** [comment]
Any update on this bug 
i am also facing the same "connection reset by peer"

**Comment by surabhi-zibo** [comment]
Any updates on this bug.
We are also facing the same issue.



> Pinging @elastic/es-core-features (:Core/Features/Java High Level REST Client)

**Comment by trungvo98** [comment]
I am also facing same issue when i index a document 
client.index(indexRequest, RequestOptions.DEFAULT)

**Comment by DaveCTurner** [comment]
I believe enabling TCP keepalives, and configuring them appropriately, is what's needed to fix this. See https://github.com/elastic/elasticsearch/issues/65213 for more details.
