### ISSUE TITLE
[CI] IndicesClientIT.testDataStreams failure

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#60461]
**Build scan**: https://gradle-enterprise.elastic.co/s/rtz2uf3u5fuwm

**Repro line**: ./gradlew ':client:rest-high-level:asyncIntegTestRunner' --tests "org.elasticsearch.client.IndicesClientIT.testDataStreams" -Dtests.seed=E89C70116AD44583 -Dtests.security.manager=true -Dtests.locale=ja-JP-u-ca-japanese-x-lvariant-JP -Dtests.timezone=Australia/LHI -Druntime.java=8

**Reproduces locally?**: No

**Applicable branches**: 7.9

**Failure history**: First time

**Failure excerpt**: 

```
org.elasticsearch.client.IndicesClientIT > testDataStreams FAILED
    java.lang.AssertionError: 
    Expected: not <0L>
         but: was <0L>
        at __randomizedtesting.SeedInfo.seed([E89C70116AD44583:AE38E9FD1394286D]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.client.IndicesClientIT.testDataStreams(IndicesClientIT.java:2084)
```

**Comment by martijnvg** [comment]
The test fails, because the total store size is expected to be not zero, but it is zero.
I think this can happen, because no shards of the backing index has been allocated,
which is possible, because we don't wait for shards to get allocated. Just some checks
that are based on things in the cluster state. I think we should wait for at least
on shard to get allocated of the backing index.

**Comment by nik9000** [comment]
@martijnvg this seems to have come [back](https://gradle-enterprise.elastic.co/s/vgdqjkvflmgeg/tests/:client:rest-high-level:integTest/org.elasticsearch.client.IndicesClientIT/testDataStreams#1). :zombie:?

**Comment by jaymode** [comment]
Happened again on a master intake build: https://gradle-enterprise.elastic.co/s/emezepdjekgwy/tests/:client:rest-high-level:asyncIntegTest/org.elasticsearch.client.IndicesClientIT/testDataStreams#1. I am muting the test.

**Comment by martijnvg** [comment]
I've opened #65879 that unmutes this test in master and removes the assertion that fails here. 
This assertion is flaky in CI (many reasons why disk size can be 0 bytes) and not needed to test HLRC integration (which is the purpose of this test). Just checking that a not null value is returned is sufficient and that is already done in this test.

**Comment by martijnvg** [comment]
Test hasn't failed after enabling this test on master. Also enabled this test in 7.x branch.

**Comment by DaveCTurner** [comment]
Looks like the same failure occurred in `master`, reopening this:

https://gradle-enterprise.elastic.co/s/w5vqxbordy566/console-log?task=:client:rest-high-level:asyncIntegTest

**Comment by jkakavas** [comment]
Same failure happened today in 7.x https://gradle-enterprise.elastic.co/s/3ly62xt63avf4
```
java.lang.AssertionError: 
Expected: not <0L>
     but: was <0L>
	at __randomizedtesting.SeedInfo.seed([EB401F52279437F7:ADE486BE5ED45A19]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.client.IndicesClientIT.testDataStreams(IndicesClientIT.java:2090)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$1
```

**Comment by albertzaharovits** [comment]
Another on 7.13 branch: https://gradle-enterprise.elastic.co/s/cyk6tiwssxpvu

Fails rarely though... (https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P28D&search.timeZoneId=Europe/Bucharest&tests.container=org.elasticsearch.client.IndicesClientIT&tests.sortField=FAILED&tests.test=testDataStreams&tests.unstableOnly=true not all failures in this have the same cause).
