### ISSUE TITLE
CI: VariableWidthHistogramAggregatorTests#testMultipleSegments

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#60673]
Error Message

java.lang.AssertionError: expected:<false> but was:<true>

Stacktrace

```
java.lang.AssertionError: expected:<false> but was:<true>
	at __randomizedtesting.SeedInfo.seed([7B50D97E959CDE64:C7276C27523B7221]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.elasticsearch.search.aggregations.bucket.histogram.VariableWidthHistogramAggregatorTests.lambda$testMultipleSegments$31(VariableWidthHistogramAggregatorTests.java:442)
	at org.elasticsearch.search.aggregations.bucket.histogram.VariableWidthHistogramAggregatorTests.executeTestCase(VariableWidthHistogramAggregatorTests.java:638)
	at org.elasticsearch.search.aggregations.bucket.histogram.VariableWidthHistogramAggregatorTests.testSearchAndReduceCase(VariableWidthHistogramAggregatorTests.java:576)
	at org.elasticsearch.search.aggregations.bucket.histogram.VariableWidthHistogramAggregatorTests.testMultipleSegments(VariableWidthHistogramAggregatorTests.java:429)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
```

**Comment by nik9000** [comment]
Link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_RUNTIME_JAVA=corretto8,nodes=general-purpose/140/

**Comment by nik9000** [comment]
I couldn't get this to reproduce, either with the reproduction line from the failing build's reproduce line or by running it locally a couple thousand times. I imagine #60683 has changed it. If this comes up again, I'll take another look. But for now I'll close.

**Comment by nik9000** [comment]
I'm able to reproduce this against a8a34ec40a66d6893be3407e489a2042e824c0ef with:
```
 ./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.histogram.VariableWidthHistogramAggregatorTests.testMultipleSegments" -Dtests.seed=84205C35358D3897 -Dtests.security.manager=true -Dtests.locale=ar-JO -Dtests.timezone=Canada/Newfoundland -Druntime.java=11
```

**Comment by nik9000** [comment]
This happens because we have a test that randomizes stuff pretty hard and it had some assumptions about the shape of the documents that turn out not to be true. Protip: the results are pretty wonky when you only allow a few pieces docs per shard and ask for very few clusters. This should only be a testing problem. Hopefully.

**Comment by hendrikmuhs** [comment]
@nik9000 This happened again in `7.9`: https://gradle-enterprise.elastic.co/s/3cd5fb2vt6gau

If I get it right, there is no `7.9` backport. Should this be backported?

**Comment by nik9000** [comment]
> If I get it right, there is no `7.9` backport. Should this be backported?

I thought that the 7.9 branch was "mostly dead" so we don't backport test fixes. Are we still running them consistently?
