### ISSUE TITLE
TransformContinuousIT#testContinousEvents can fail with assertion.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#60781]
**Build scan**: https://gradle-enterprise.elastic.co/s/rexmn4q3oxtry

**Repro line**:
```
./gradlew ':x-pack:plugin:transform:qa:single-node-tests:integTest' --tests "org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT.testContinousEvents" -Dtests.seed=729729FBA720DB7C -Dtests.security.manager=true -Dtests.locale=el -Dtests.timezone=MIT -Druntime.java=11
```

**Reproduces locally?**: no.

**Applicable branches**: failure observed on master.

**Failure history**: periodic failures, the earliest of which is from July 30th 2020. It seems to have started failing more frequently on August 5th.

**Failure excerpt**:
```
org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT > testContinousEvents FAILED
    java.lang.AssertionError: Error in test case [continuous-terms-pivot-test].If you want to mute the test, please mute [org.elasticsearch.xpack.transform.integration.continuous.TermsGroupByIT] only, but _not_ [org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT] as a whole.
        at __randomizedtesting.SeedInfo.seed([729729FBA720DB7C:49A158E02D4B592A]:0)
        at org.elasticsearch.xpack.transform.integration.continuous.TransformContinuousIT.testContinousEvents(TransformContinuousIT.java:258)

        Caused by:
        java.lang.AssertionError: Ingest run: 1 did not match max run: 0.0, iteration: 1
        Expected: <0.0>
             but: was <1.0>
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
            at org.junit.Assert.assertThat(Assert.java:956)
            at org.elasticsearch.xpack.transform.integration.continuous.TermsGroupByIT.testIteration(TermsGroupByIT.java:144)
            at 
```

**Comment by hendrikmuhs** [comment]
This test has been added in #60469. 

It's an integration test which covers a broad range of features in the stack, failures are expected (a lucene bug discovered by this test is in investigation). As long as the failure rate is low (as of writing 14 in the last 24 hours) I ask to not mute/silence it to discover hard to find bugs in the stack.

I looked at the logs of this and other failures, the problem seems to be:

```
[2020-08-05T17:16:18,242][ERROR][o.e.x.t.t.ClientTransformIndexer] [integTest-0] [continuous-terms-pivot-test] updating stats of transform failed.
java.lang.RuntimeException: Failed to persist transform statistics for transform [continuous-terms-pivot-test]
	at org.elasticsearch.xpack.transform.persistence.IndexBasedTransformConfigManager.lambda$putOrUpdateTransformStoredDoc$14(IndexBasedTransformConfigManager.java:527) [transform-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:71) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:50) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$1(NodeClient.java:91) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.tasks.TaskManager$1.onFailure(TaskManager.java:184) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:50) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.bulk.TransportSingleItemBulkWriteAction.lambda$wrapBulkResponse$0(TransportSingleItemBulkWriteAction.java:64) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]

...

Caused by: org.elasticsearch.index.engine.VersionConflictEngineException: [data_frame_transform_state_and_stats-continuous-terms-pivot-test]: version conflict, required seqNo [6], primary term [1]. current document has seqNo [11] and primary term [1]
	at org.elasticsearch.index.engine.InternalEngine.planIndexingAsPrimary(InternalEngine.java:1014) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.index.engine.InternalEngine.indexingStrategyForOperation(InternalEngine.java:977) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:866) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:815) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:787) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:752) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:279) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:168) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	... 10 more
[2020-08-05T17:16:18,250][DEBUG][o.e.x.t.t.TransformTask  ] [integTest-0] [continuous-terms-pivot-test] shutdown of transform requested

```

I need to find out where this conflict is coming from.

**Comment by DaveCTurner** [comment]
This is failing quite often; I discussed with Hendrik and we decided to mute it for now:

master: 2499d6b97b3e9cb52b0a526a82445f1a2e7c96ca
7.x: f24a3a4e814f0d57c54d61895bd434d3bf635aa7

**Comment by hendrikmuhs** [comment]
I suspect the root cause to be the same as in:

https://github.com/elastic/elasticsearch/issues/52035
https://github.com/elastic/elasticsearch/issues/51629
(and likely https://github.com/elastic/elasticsearch/issues/52931)

I think that the state is saved from 2 different threads, the indexer thread and the thread that runs the `_stop` action.

**Comment by DaveCTurner** [comment]
Having muted this test a different one in this suite now failed. I'm muting that one too:

master: f86d51d6ebef2716427e9e25ba1eeab420eb12e4
7.x: 05b2a2db8b170d882132793b60a5a4e898803cd6

**Comment by hendrikmuhs** [comment]
> Having muted this test a different one in this suite now failed. I'm muting that one too:

:+1: The logs indicate a problem in the infrastructure, so the problem applies to both. There are only 2 test cases, so you have muted all of them now.
