### ISSUE TITLE
SearchableSnapshotDirectoryTests#testNonCachedFilesAreExcludedFromRecoveryState fails

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#60813]
**Build scan**:

https://gradle-enterprise.elastic.co/s/rve5theumtlaw/console-log?task=:x-pack:plugin:searchable-snapshots:test

**Repro line**:

    
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.index.store.SearchableSnapshotDirectoryTests.testNonCachedFilesAreExcludedFromRecoveryState" -Dtests.seed=F1D689E910ABDDD7 -Dtests.security.manager=true -Dtests.locale=ar-SA -Dtests.timezone=Asia/Macau -Druntime.java=8
--
```

**Reproduces locally?**:

No, after many hundreds of retries.

**Applicable branches**:

Only seen on `7.x` so far.

**Failure history**:

Only once so far.

**Failure excerpt**:

```
org.elasticsearch.index.store.SearchableSnapshotDirectoryTests > testNonCachedFilesAreExcludedFromRecoveryState FAILED
    java.lang.AssertionError: 
    Expected: <DONE>
         but: was <FINALIZE>
        at __randomizedtesting.SeedInfo.seed([F1D689E910ABDDD7:9F0EA6FE12244832]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.index.store.SearchableSnapshotDirectoryTests.lambda$testNonCachedFilesAreExcludedFromRecoveryState$29(SearchableSnapshotDirectoryTests.java:829)
        at org.elasticsearch.index.store.SearchableSnapshotDirectoryTests.testDirectories(SearchableSnapshotDirectoryTests.java:622)
        at org.elasticsearch.index.store.SearchableSnapshotDirectoryTests.testNonCachedFilesAreExcludedFromRecoveryState(SearchableSnapshotDirectoryTests.java:826)

```

**Comment by droberts195** [comment]
Same error again in https://gradle-enterprise.elastic.co/s/afsizmamd3bhy
