### ISSUE TITLE
[CI] Node startup failed in :qa:mixed-cluster:v7.10.0#mixedClusterTest on Windows

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#60886]
**Build scan**:

https://gradle-enterprise.elastic.co/s/oh3dbgzcozqs6

**Repro line**:

```
./gradlew :qa:mixed-cluster:v7.10.0#mixedClusterTest
```

**Reproduces locally?**:

No

**Applicable branches**:

master

**Failure history**:

It's very hard to search for, as the build stats doc doesn't record the failed task in this case.  This search finds failures of Windows Gradle tasks that were not due to a test failure:

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-6M,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'build.job-name-extra:multijob-windows-compatibility*%20AND%20process.status:FAILURE%20AND%20test.errors:0%20AND%20test.failures:0'),sort:!(process.time-start,desc))

However, I couldn't see another that was like this one.

**Failure excerpt**:

```
=== Standard output of node `node{:qa:mixed-cluster:v7.10.0-1}` === |  

    ↓ errors and warnings from C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build\testclusters\v7.10.0-1\logs\es.stdout.log ↓ |  
 ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v7.10.0-1] uncaught exception in thread [main] |  
  org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Unable to access 'path.repo' (C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build\cluster\shared\repo\v7.10.0) |  
  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:174) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127) ~[elasticsearch-cli-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  Caused by: java.lang.IllegalStateException: Unable to access 'path.repo' (C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build\cluster\shared\repo\v7.10.0) |  
  	at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:70) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:313) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:252) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.bootstrap.Security.configure(Security.java:121) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:222) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	... 6 more |  
  Caused by: java.nio.file.NoSuchFileException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build\cluster\shared\repo\v7.10.0 |  
  	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?] |  
  	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:96) ~[?:?] |  
  	at sun.nio.fs.WindowsLinkSupport.getRealPath(WindowsLinkSupport.java:257) ~[?:?] |  
  	at sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:891) ~[?:?] |  
  	at sun.nio.fs.WindowsPath.toRealPath(WindowsPath.java:42) ~[?:?] |  
  	at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:385) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUtils.java:68) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:313) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:252) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.bootstrap.Security.configure(Security.java:121) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:222) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.10.0-SNAPSHOT.jar:7.10.0-SNAPSHOT] |  
  	... 6 more |  
   ↓ last 40 non error or warning messages from C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build\testclusters\v7.10.0-1\logs\es.stdout.log ↓ |  
 [2020-08-10T08:14:18.544732900Z] [BUILD] Copying additional config files from distro [C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build\testclusters\v7.10.0-1\distro\7.10.0-OSS\config\elasticsearch.yml, C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build\testclusters\v7.10.0-1\distro\7.10.0-OSS\config\jvm.options, C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build\testclusters\v7.10.0-1\distro\7.10.0-OSS\config\jvm.options.d, C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build\testclusters\v7.10.0-1\distro\7.10.0-OSS\config\log4j2.properties] |  
 [2020-08-10T08:14:18.548645100Z] [BUILD] Creating elasticsearch keystore with password set to [] |  
 [2020-08-10T08:14:19.917679Z] [BUILD] Starting Elasticsearch process |  
 [2020-08-10T08:14:27.848389100Z] [BUILD] Stopping node
```

However, if you download the server logs from https://storage.cloud.google.com/elasticsearch-ci-artifacts/jobs/elastic+elasticsearch+master+multijob-windows-compatibility/os=windows-2019/build/151.tar.bz2 and look across all of them:

```
bash-3.2$ find . -type f | xargs grep path.repo
./v7.10.0-2/config/elasticsearch.yml:path.repo: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build/cluster/shared/repo/v7.10.0
./v7.10.0-3/config/elasticsearch.yml:path.repo: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build/cluster/shared/repo/v7.10.0
./v7.10.0-1/config/elasticsearch.yml:path.repo: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build/cluster/shared/repo/v7.10.0
./v7.10.0-1/logs/es.stdout.log:org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Unable to access 'path.repo' (C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build\cluster\shared\repo\v7.10.0)
./v7.10.0-1/logs/es.stdout.log:Caused by: java.lang.IllegalStateException: Unable to access 'path.repo' (C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build\cluster\shared\repo\v7.10.0)
./v7.10.0-1/logs/v7.10.0.log:java.lang.IllegalStateException: Unable to access 'path.repo' (C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build\cluster\shared\repo\v7.10.0)
./v7.10.0-1/logs/v7.10.0.log:org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Unable to access 'path.repo' (C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build\cluster\shared\repo\v7.10.0)
./v7.10.0-1/logs/v7.10.0.log:Caused by: java.lang.IllegalStateException: Unable to access 'path.repo' (C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build\cluster\shared\repo\v7.10.0)
./v7.10.0-1/logs/v7.10.0_server.json:"stacktrace": ["java.lang.IllegalStateException: Unable to access 'path.repo' (C:\\Users\\jenkins\\workspace\\elastic+elasticsearch+master+multijob-windows-compatibility\\os\\windows-2019\\qa\\mixed-cluster\\build\\cluster\\shared\\repo\\v7.10.0)",
./v7.10.0-1/logs/v7.10.0_server.json:"stacktrace": ["org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Unable to access 'path.repo' (C:\\Users\\jenkins\\workspace\\elastic+elasticsearch+master+multijob-windows-compatibility\\os\\windows-2019\\qa\\mixed-cluster\\build\\cluster\\shared\\repo\\v7.10.0)",
./v7.10.0-1/logs/v7.10.0_server.json:"Caused by: java.lang.IllegalStateException: Unable to access 'path.repo' (C:\\Users\\jenkins\\workspace\\elastic+elasticsearch+master+multijob-windows-compatibility\\os\\windows-2019\\qa\\mixed-cluster\\build\\cluster\\shared\\repo\\v7.10.0)",
./v7.10.0-1/logs/es.stderr.log:java.lang.IllegalStateException: Unable to access 'path.repo' (C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build\cluster\shared\repo\v7.10.0)
./v7.10.0-0/config/elasticsearch.yml:path.repo: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2019\qa\mixed-cluster\build/cluster/shared/repo/v7.10.0
```

So `v7.10.0-0` happily loaded the file.  Only `v7.10.0-1` reported that it didn't exist.

An interesting bit of code is https://github.com/elastic/elasticsearch/blob/630a4a88b88eba676b7d8ecc63de5b528c2468f2/server/src/main/java/org/elasticsearch/bootstrap/Security.java#L380-L386

It shows that `Files.isDirectory(path)` returned `true` yet `path.toRealPath()` threw a `NoSuchFileException`.  This in turn suggests that there is loss of information in the way Java translates Windows errors to Java exceptions and the real problem was something to do with file locking or something like that.  Maybe concurrent access from `v7.10.0-0` and `v7.10.0-1` made one of them fail.

**Comment by valeriy42** [comment]
Also happened here https://gradle-enterprise.elastic.co/s/3ru6gbeyhnq6y on 7.x

**Comment by williamrandolph** [comment]
It looks like this still happens, though pretty rarely:
* 8 June: https://gradle-enterprise.elastic.co/s/5bohiftny4fus/console-log?task=:qa:mixed-cluster:v8.8.1%23mixedClusterTest
* 12 July: https://gradle-enterprise.elastic.co/s/335yewlq3qogy/console-log?task=:qa:mixed-cluster:v8.8.3%23mixedClusterTest

It's easier to search for non-verification task failures in Gradle Enterprise than it was in build-stats: https://gradle-enterprise.elastic.co/scans/failures?failures.failureMessage=*mixedCluster*&search.buildOutcome=failure&search.relativeStartTime=P90D&search.tags=WINDOWS%2CMAIN&search.timeZoneId=America/New_York

**Comment by thecoop** [comment]
This has not happened in months, so closing this - we can investigate when we have a recent example.
