### ISSUE TITLE
windows fails org.elasticsearch.packaging.test.ArchiveTests.test10Install

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#60923]
**Build scan**:
https://gradle-enterprise.elastic.co/s/tw66mp2r5nte2

**Repro line**:
none logged

**Reproduces locally?**:
don't have windows

**Applicable branches**:
7.x

**Failure history**:
Seems to have started August 10 around 3:30.

**Failure excerpt**:
```
12:19:59 Suite: Test class org.elasticsearch.packaging.test.ArchiveTests
12:19:59   1> [2020-08-10T16:19:58,037][INFO ][o.e.p.u.Shell            ] [SUITE-ArchiveTests-seed#[4E99502FF21E85A1]est_thread_info] Ran: [powershell.exe, -Command, which docker] exitCode = [1] stdout = [] stderr = [which : The term 'which' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
12:19:59   1> the spelling of the name, or if a path was included, verify that the path is correct and try again.
12:19:59   1> At line:1 char:1
12:19:59   1> + which docker
12:19:59   1> + ~~~~~
12:19:59   1>     + CategoryInfo          : ObjectNotFound: (which:String) [], CommandNotFoundException
12:19:59   1>     + FullyQualifiedErrorId : CommandNotFoundException]
12:19:59   1> [2020-08-10T16:19:58,050][WARN ][o.e.p.u.Shell            ] [SUITE-ArchiveTests-seed#[4E99502FF21E85A1]est_thread_info] Running command with env: {}
12:19:59   1> [2020-08-10T16:19:58,251][INFO ][o.e.p.u.Shell            ] [SUITE-ArchiveTests-seed#[4E99502FF21E85A1]est_thread_info] Ran: [powershell.exe, -Command, $Env:SYSTEM_JAVA_HOME] exitCode = [0] stdout = [C:\Users\jenkins\.java\openjdk11] stderr = []
12:19:59   1> [2020-08-10T16:19:58,691][INFO ][o.e.p.u.Shell            ] [SUITE-ArchiveTests-seed#[4E99502FF21E85A1]-workerest_thread_info] Ran: [powershell.exe, -Command, Get-WmiObject Win32_Process | Where-Object { $_.CommandLine -Match 'org.elasticsearch.bootstrap.Elasticsearch' } | ForEach-Object { $_.Terminate() }] exitCode = [0] stdout = [] stderr = []
12:19:59   1> [2020-08-10T16:19:58,717][INFO ][o.e.p.u.Archives         ] [TEST-ArchiveTests.test10Install-seed#[4E99502FF21E85A1]-workerest_thread_info] Installing file: C:\Users\jenkins\workspace\elastic+elasticsearch+pull-request+packaging-tests-windows-gcp-sample\PACKAGING_TASK\default-windows-archive-no-jdk\os\windows-2019\distribution\archives\no-jdk-windows-zip\build\distributions\elasticsearch-8.0.0-SNAPSHOT-no-jdk-windows-x86_64.zip
12:19:59   1> [2020-08-10T16:19:58,717][WARN ][o.e.p.u.Shell            ] [TEST-ArchiveTests.test10Install-seed#[4E99502FF21E85A1]-workerest_thread_info] Running command with env: {JAVA_HOME=C:\Users\jenkins\.java\openjdk11}
12:19:59   1> [2020-08-10T16:19:59,203][INFO ][o.e.p.u.Shell            ] [TEST-ArchiveTests.test10Install-seed#[4E99502FF21E85A1]-workerest_thread_info] Ran: [powershell.exe, -Command, Add-Type -AssemblyName 'System.IO.Compression.Filesystem'; [IO.Compression.ZipFile]::ExtractToDirectory('C:\Users\jenkins\workspace\elastic+elasticsearch+pull-request+packaging-tests-windows-gcp-sample\PACKAGING_TASK\default-windows-archive-no-jdk\os\windows-2019\distribution\archives\no-jdk-windows-zip\build\distributions\elasticsearch-8.0.0-SNAPSHOT-no-jdk-windows-x86_64.zip', 'C:\tmp')] exitCode = [1] stdout = [] stderr = [Exception calling "ExtractToDirectory" with "2" argument(s): "Could not find a part of the path 'C:\Users\jenkins\works
12:19:59   1> pace\elastic+elasticsearch+pull-request+packaging-tests-windows-gcp-sample\PACKAGING_TASK\default-windows-archive-no-jd
12:19:59   1> k\os\windows-2019\distribution\archives\no-jdk-windows-zip\build\distributions\elasticsearch-8.0.0-SNAPSHOT-no-jdk-wind
12:19:59   1> ows-x86_64.zip'."
12:19:59   1> At line:1 char:60
12:19:59   1> + ... ilesystem'; [IO.Compression.ZipFile]::ExtractToDirectory('C:\Users\je ...
12:19:59   1> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12:19:59   1>     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
12:19:59   1>     + FullyQualifiedErrorId : DirectoryNotFoundException]
12:19:59   2> org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [powershell.exe -Command Add-Type -AssemblyName 'System.IO.Compression.Filesystem'; [IO.Compression.ZipFile]::ExtractToDirectory('C:\Users\jenkins\workspace\elastic+elasticsearch+pull-request+packaging-tests-windows-gcp-sample\PACKAGING_TASK\default-windows-archive-no-jdk\os\windows-2019\distribution\archives\no-jdk-windows-zip\build\distributions\elasticsearch-8.0.0-SNAPSHOT-no-jdk-windows-x86_64.zip', 'C:\tmp')]
12:19:59        result: exitCode = [1] stdout = [] stderr = [Exception calling "ExtractToDirectory" with "2" argument(s): "Could not find a part of the path 'C:\Users\jenkins\works
12:19:59     pace\elastic+elasticsearch+pull-request+packaging-tests-windows-gcp-sample\PACKAGING_TASK\default-windows-archive-no-jd
12:19:59     k\os\windows-2019\distribution\archives\no-jdk-windows-zip\build\distributions\elasticsearch-8.0.0-SNAPSHOT-no-jdk-wind
12:19:59     ows-x86_64.zip'."
12:19:59     At line:1 char:60
12:19:59     + ... ilesystem'; [IO.Compression.ZipFile]::ExtractToDirectory('C:\Users\je ...
12:19:59     +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12:19:59         + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
12:19:59         + FullyQualifiedErrorId : DirectoryNotFoundException]
12:19:59         at __randomizedtesting.SeedInfo.seed([4E99502FF21E85A1:A2C35CD7AE8E3AFB]:0)
12:19:59         at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:158)
12:19:59         at org.elasticsearch.packaging.util.Shell.run(Shell.java:84)
12:19:59         at org.elasticsearch.packaging.util.Archives.installArchive(Archives.java:105)
12:19:59         at org.elasticsearch.packaging.util.Archives.installArchive(Archives.java:71)
12:19:59         at org.elasticsearch.packaging.test.ArchiveTests.test10Install(ArchiveTests.java:62)
```

**Comment by mark-vieira** [comment]
This is us exceeding the 260 character limit in file paths. Jenkins generates insane checkout locations for matrix jobs.

**Comment by mark-vieira** [comment]
I've configured the workspace base dir in the CI job to have a shorter name so these paths slip below the character limit now.
