### ISSUE TITLE
Reproducible Failure in org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests.testParentChild

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#60954]
```
./gradlew ':modules:parent-join:test' --tests "org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests.testParentChild" -Dtests.seed=2D773C1E12C3463D -Dtests.security.manager=true -Dtests.locale=es-BO -Dtests.timezone=Eire -Druntime.java=11
```

on `master` fails with:

```
org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests > testParentChild FAILED
    java.lang.AssertionError: Having 9 docs and aggregation results: {in_parent={"in_parent":{"value":5.0}}} expected:<8> but was:<9>
        at __randomizedtesting.SeedInfo.seed([2D773C1E12C3463D:34B65CEF542DE422]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests.lambda$testParentChild$1(ChildrenToParentAggregatorTests.java:122)
        at org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests.testCase(ChildrenToParentAggregatorTests.java:307)
        at org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests.testParentChild(ChildrenToParentAggregatorTests.java:115)
REPRODUCE WITH: ./gradlew ':modules:parent-join:test' --tests "org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests.testParentChild" -Dtests.seed=2D773C1E12C3463D -Dtests.security.manager=true -Dtests.locale=es-BO -Dtests.timezone=Eire -Druntime.java=11

Suite: Test class org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests
  1> [2020-08-11T10:50:39,091][INFO ][o.e.j.a.ChildrenToParentAggregatorTests] [testParentChild] before test
  1> [2020-08-11T10:50:40,086][INFO ][o.e.j.a.ChildrenToParentAggregatorTests] [testParentChild] after test
  2> REPRODUCE WITH: ./gradlew ':modules:parent-join:test' --tests "org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests.testParentChild" -Dtests.seed=2D773C1E12C3463D -Dtests.security.manager=true -Dtests.locale=es-BO -Dtests.timezone=Eire -Druntime.java=11
  2> java.lang.AssertionError: Having 9 docs and aggregation results: {in_parent={"in_parent":{"value":5.0}}} expected:<8> but was:<9>
        at __randomizedtesting.SeedInfo.seed([2D773C1E12C3463D:34B65CEF542DE422]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests.lambda$testParentChild$1(ChildrenToParentAggregatorTests.java:122)
        at org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests.testCase(ChildrenToParentAggregatorTests.java:307)
        at org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests.testParentChild(ChildrenToParentAggregatorTests.java:115)
  2> NOTE: leaving temporary files on disk at: /home/brownbear/src/elasticsearch/modules/parent-join/build/testrun/test/temp/org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests_2D773C1E12C3463D-001
  2> NOTE: test params are: codec=Asserting(Lucene86): {_id=PostingsFormat(name=Asserting), join_field=PostingsFormat(name=Asserting)}, docValues:{number=DocValuesFormat(name=Lucene80), join_field#parent_type=DocValuesFormat(name=Lucene80), subNumber=DocValuesFormat(name=Lucene80)}, maxPointsInLeafNode=1652, maxMBSortInHeap=7.56132819025695, sim=Asserting(RandomSimilarity(queryNorm=false): {join_field=IB LL-L2}), locale=es-BO, timezone=Eire
  2> NOTE: Linux 5.4.0-42-generic amd64/Oracle Corporation 11.0.2 (64-bit)/cpus=16,threads=1,free=430485288,total=536870912
  2> NOTE: All tests run in this JVM: [ChildrenToParentAggregatorTests]
```

for me locally on every run.

**Comment by nik9000** [comment]
I believe I fixed this with #60991.
