### ISSUE TITLE
Reproducible failure in ChildrenToParentAggregatorTests.testParentChildTerms

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#60980]
**Build scan**: https://gradle-enterprise.elastic.co/s/hrcgyap7ink5y/tests/:modules:parent-join:test/org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests/testParentChildTerms#1

**Repro line**: 
```
./gradlew ':modules:parent-join:test' --tests "org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests.testParentChildTerms" -Dtests.seed=5A1275B4C2BB46F7 -Dtests.security.manager=true -Dtests.locale=hr-HR -Dtests.timezone=America/Pangnirtung -Druntime.java=8
```

**Reproduces locally?**: Yes

**Applicable branches**: 7.x

**Failure excerpt**:

```
org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests > testParentChildTerms FAILED
    java.lang.AssertionError: expected:<5> but was:<40>
        at __randomizedtesting.SeedInfo.seed([5A1275B4C2BB46F7:6A8FFC1BFB980E92]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests.lambda$testParentChildTerms$5(ChildrenToParentAggregatorTests.java:188)
        at org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests.testCaseTerms(ChildrenToParentAggregatorTests.java:318)
        at org.elasticsearch.join.aggregations.ChildrenToParentAggregatorTests.testParentChildTerms(ChildrenToParentAggregatorTests.java:176)
```

**Comment by dnhatn** [comment]
Another instance: https://gradle-enterprise.elastic.co/s/bkjfalmxnsix2

**Comment by nik9000** [comment]
This bisects to #60683. So it'll be the test assuming that the result wasn't fully reduced. I'll dig.
