### ISSUE TITLE
CI: FIPS builds in 7.8 and 7.9 failing due to `Crypto provider not installed: BCFIPS`

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#60990]
**Build scan**:
There are plenty:
https://gradle-enterprise.elastic.co/s/cuatj7biqc5vi
https://gradle-enterprise.elastic.co/s/frm5jnlfve2s4
https://gradle-enterprise.elastic.co/s/h3wtibymoo5ik
https://gradle-enterprise.elastic.co/s/bmahzvuq2tt3i

**Repro line**:
Running any YAML test fails.

**Reproduces locally?**:
Yes

**Applicable branches**:
7.8 and 7.9

**Failure excerpt**:
```
23:20:28 > Task :rest-api-spec:yamlRestTestRunner FAILED
23:20:28 java.security.ProviderException: Crypto provider not installed: BCFIPS
23:20:28 	at sun.security.ssl.SunJSSE.<init>(SunJSSE.java:142)
23:20:28 	at sun.security.ssl.SunJSSE.<init>(SunJSSE.java:123)
23:20:28 	at com.sun.net.ssl.internal.ssl.Provider.<init>(Provider.java:51)
23:20:28 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
23:20:28 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
23:20:28 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
23:20:28 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
23:20:28 	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:224)
23:20:28 	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206)
23:20:28 	at java.security.AccessController.doPrivileged(Native Method)
```

**Comment by dnhatn** [comment]
@jakelandis is working on this.
