### ISSUE TITLE
[CI] FullClusterRestartIT.testCreateSystemIndexInOldVersion Failure

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#61111]
Console:
https://gradle-enterprise.elastic.co/s/en3x6ofkrd67k

Test Failure:
```
org.elasticsearch.upgrades.FullClusterRestartIT > testCreateSystemIndexInOldVersion FAILED
    org.elasticsearch.client.WarningFailureException: method [GET], host [http://[::1]:35477], URI [/.tasks], status line [HTTP/1.1 200 OK]
    Warnings: [[types removal] The parameter include_type_name should be explicitly specified in get indices requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', which means responses will omit the type name in mapping definitions.]
    {".tasks":{"aliases":{},"mappings":{"task":{"dynamic":"strict","_meta":{"version":2},"properties":{"completed":{"type":"boolean"},"error":{"type":"object","enabled":false},"response":{"type":"object","enabled":false},"task":{"properties":{"action":{"type":"keyword"},"cancellable":{"type":"boolean"},"description":{"type":"text"},"headers":{"type":"object","enabled":false},"id":{"type":"long"},"node":{"type":"keyword"},"parent_id":{"type":"keyword"},"running_time_in_nanos":{"type":"long"},"start_time_in_millis":{"type":"long"},"status":{"type":"object","enabled":false},"type":{"type":"keyword"}}}}}},"settings":{"index":{"number_of_shards":"1","auto_expand_replicas":"0-1","provided_name":".tasks","creation_date":"1597340969485","priority":"2147483647","number_of_replicas":"1","uuid":"PoDSIql_Qe-cZKc25-Uv1A","version":{"created":"6070299"}}}}}
        at __randomizedtesting.SeedInfo.seed([4FB66BD7A21D16AF:A2E0CA66AD9D734A]:0)
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:298)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:272)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246)
        at org.elasticsearch.upgrades.FullClusterRestartIT.lambda$testCreateSystemIndexInOldVersion$8(FullClusterRestartIT.java:1502)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:939)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:924)
        at org.elasticsearch.upgrades.FullClusterRestartIT.testCreateSystemIndexInOldVersion(FullClusterRestartIT.java:1497)
```

Reproduce:
```
./gradlew ':qa:full-cluster-restart:v6.7.2#oldClusterTest' --tests "org.elasticsearch.upgrades.FullClusterRestartIT.testCreateSystemIndexInOldVersion" -Dtests.seed=4FB66BD7A21D16AF -Dtests.security.manager=true -Dtests.locale=ar -Dtests.timezone=Australia/Lindeman -Druntime.java=8
```

**Comment by jdconrad** [comment]
More console links:
https://gradle-enterprise.elastic.co/s/ovegsadasho46
https://gradle-enterprise.elastic.co/s/sfv6ue7dhqh6o
https://gradle-enterprise.elastic.co/s/da6dtdna64z4m
https://gradle-enterprise.elastic.co/s/gc7q7l6byv7nc

**Comment by henningandersen** [comment]
Still fails, but only in 7.x:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'FullClusterRestartIT+AND+testCreateSystemIndexInOldVersion'),sort:!(time,desc))

Have opened #61131 that should fix this.

**Comment by gwbrown** [comment]
Thanks @henningandersen! I was intending to put up a fix this morning, but you beat me to it! This is the only cause of the failure of this test I could find when I was investigating yesterday, so I think we can close this issue now. I'll keep an eye out for any more failures here.
