### ISSUE TITLE
[CI] FIPS mode test failures

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#61137]
FIPS mode tests fails across master, 7.x and 7.9

**Build scan**: https://gradle-enterprise.elastic.co/s/oz3zflzy6rv7e

**Reproduces locally?**: Not attempted

**Applicable branches**: master, 7.x and 7.9

**Failure history**:

[Started failing August 11th](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(branch),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'java.security.NoSuchAlgorithmException+AND+matrix-java-periodic-fips'),sort:!(process.time-start,desc))), 8 times a day.

**Failure excerpt**:

```
java.lang.RuntimeException: java.security.NoSuchAlgorithmException: Service not registered with Provider BCFIPS: BCFIPS: SecureRandom.DEFAULT -> org.bouncycastle.jcajce.provider.random.DefSecureRandom
  attributes: {ImplementedIn=Software}

	at java.base/java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:294)
	at java.base/java.security.SecureRandom.<init>(SecureRandom.java:219)
	at java.base/java.io.File$TempDirectory.<clinit>(File.java:1934)
	at java.base/java.io.File.createTempFile(File.java:2094)
	at com.sun.jna.Native.extractFromResourcePath(Native.java:1124)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1009)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:340)
	at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:45)
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:110)
	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:86)
	at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:228)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:427)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:623)
Caused by: java.security.NoSuchAlgorithmException: Service not registered with Provider BCFIPS: BCFIPS: SecureRandom.DEFAULT -> org.bouncycastle.jcajce.provider.random.DefSecureRandom
  attributes: {ImplementedIn=Software}

	at java.base/java.security.Provider$Service.newInstance(Provider.java:1857)
	at java.base/java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:290)
	... 16 more
```

**Comment by jkakavas** [comment]
This is https://github.com/elastic/elasticsearch/issues/58644 again. It only fails in jdk14 but according to https://bugs.openjdk.java.net/browse/JDK-8248505 it should have been resolved in jdk14 b12 . Maybe we need to update the jdk14 installation we use in CI ? I can check this on Monday

**Comment by rjernst** [comment]
The fix is in https://github.com/elastic/elasticsearch/pull/61001, but I'm still working on the backport to 7.9/7.x for Jake.

**Comment by jkakavas** [comment]
I don't think this has to do with that issue @rjernst   The failure is quite unique and relevant to the jdk issue I pointed to above. This only fails in jdk14 and it does fail in master too (which has #61001)

**Comment by rjernst** [comment]
That may be, but the original linked CI failure here is in 7.9, where #61001 is not applied yet, so it does not have bcfips jars on the classpath.

**Comment by rjernst** [comment]
Here is the master failure:
https://gradle-enterprise.elastic.co/s/gjqctdmserjx4

Note that I am able to run one of those failed tests locally, in fips mode.

**Comment by jkakavas** [comment]
> Here is the master failure:
https://gradle-enterprise.elastic.co/s/gjqctdmserjx4

Yeap ,that's the jdk issue alright 

> Note that I am able to run one of those failed tests locally, in fips mode, and it passes.

Given that this has to do with specific jdk14 versions, can it be that you are on a different build on your laptop, than the one we currently use in CI ?

**Comment by rjernst** [comment]
This is my local version:

```
➜  java -version
java version "14" 2020-03-17
Java(TM) SE Runtime Environment (build 14+36-1461)
Java HotSpot(TM) 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)
```

I checked CI and it looks like we are running 14.0.2. I upgraded to that, but the test still passes locally.

**Comment by rjernst** [comment]
I'm specifically running `./gradlew :client:rest:test --tests=RestClientSingleHostIntegTests -Dtests.fips.enabled=true`, which was one of the failed tests in that master run.

**Comment by jkakavas** [comment]
Build says:
```
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 6.6
  OS Info               : Linux 4.18.0-193.14.2.el8_2.x86_64 (amd64)
  Runtime JDK Version   : 14 (OpenJDK)
  Runtime java.home     : /var/lib/jenkins/.java/openjdk14
  Gradle JDK Version    : 14 (OpenJDK)
  Gradle java.home      : /var/lib/jenkins/.java/openjdk-14.0.2-linux
  Random Testing Seed   : E3383059C5DC3339
  In FIPS 140 mode      : true
=======================================
```

and according to infra ` /var/lib/jenkins/.java/openjdk14` should point to `/var/lib/jenkins/.java/openjdk-14.0.2-linux`

So, [we are using](https://github.com/elastic/infra/blob/master/serverless/jvm-catalog-service/manifest.yml#L16) 14.0.2 build 12which is [downloaded from](https://github.com/elastic/infra/blob/master/serverless/jvm-catalog-service/manifest.yml#L647) [here](https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12/OpenJDK14U-jdk_x64_linux_hotspot_14.0.2_12.tar.gz) 

This build _should_ contain the fix and I have verified that the exception is not thrown locally. Not sure what causes the failure though in CI :bug: :shrug:

**Comment by jkakavas** [comment]
Actually in https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(branch,java.vm.version,java.runtime.version,build.branch),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'java.security.NoSuchAlgorithmException%20AND%20matrix-java-periodic-fips'),sort:!(process.time-start,desc)) , java runtime version is reported as 14.0.2+11-45 which is _before_ build 12 that has the fix we're looking for. I guess this is the reason, but we need to figure out why there is such a discrepancy between versions.

**Comment by mark-vieira** [comment]
Is it possible not _all_ images have the latest update?

**Comment by ywangd** [comment]
I wonder whether we could show detailed java version in the test preamble, e.g.:
```
Runtime JDK Version   : 14.0.2+11-45 (OpenJDK)
```
instead of just `14 (OpenJDK)`.

The build number is useful to us and I often struggle to find this info in the build log. There is often a line says something like 
> :extract-linux-x64-jdk-adoptopenjdk-14.0.1+7
> 
but I don't think this version is related to the actual JVM used for the testing. Sometimes the info is available as something like
> Linux 4.15.0-1080-gcp amd64/Azul Systems, Inc. 1.8.0_265 (64-bit)/cpus=32,threads=1,free=405172336,total=514850816
>
This is the right information but it does not seem to be always available. 
It would be great if this information is always available in one place.

**Comment by jkakavas** [comment]
We figured out that our JVM catalog 14.0.2 OpenJDK install is actually 14.0.2+11-45. AdoptOpenJDK is correctly 14.0.2+12. This explains the behavior too as the JDK bug was introduced in 14.0.2+10 and resolved in 14.0.2+12

Infra is looking into it and will get us the proper OpenJDK build
