### ISSUE TITLE
[CI] StatsAggregatorTests.testSummationAccuracy failure

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#61132]
**Build scan**:

https://gradle-enterprise.elastic.co/s/voerxtqazihqa

**Repro line**:

```
./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.metrics.StatsAggregatorTests.testSummationAccuracy"   -Dtests.seed=4772739B26F93342   -Dtests.security.manager=true   -Dtests.locale=ms-MY   -Dtests.timezone=Europe/Skopje   -Druntime.java=8
```

**Reproduces locally?**:
Yes, using above and in IntelliJ, using same seed.

**Applicable branches**:

**Failure history**:
It has failed once in master and once in 7.x in the [last couple of days](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'StatsAggregatorTests+AND+testSummationAccuracy'),sort:!(time,desc))).

**Failure excerpt**:

```
java.lang.AssertionError: expected:<0.9> but was:<0.8999999999999999>
        at __randomizedtesting.SeedInfo.seed([4772739B26F93342:1EBB81430D65ED31]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:553)
        at org.junit.Assert.assertEquals(Assert.java:683)
        at org.elasticsearch.search.aggregations.metrics.StatsAggregatorTests.lambda$verifySummationOfDoubles$6(StatsAggregatorTests.java:192)
        at org.elasticsearch.search.aggregations.metrics.StatsAggregatorTests.testCase(StatsAggregatorTests.java:438)
        at org.elasticsearch.search.aggregations.metrics.StatsAggregatorTests.verifySummationOfDoubles(StatsAggregatorTests.java:183)
        at org.elasticsearch.search.aggregations.metrics.StatsAggregatorTests.testSummationAccuracy(StatsAggregatorTests.java:143)
```

**Comment by nik9000** [comment]
I have a fix for this locally and I'll push tomorrow when I can be around after pushing.
