### ISSUE TITLE
A bug on old discovery mode

### ISSUE THREAD

**Issue by Charele** [elastic/elasticsearch#61177]
We know we can continue to use old discovery mode by setting:
discovery.type: legacy-zen

Bug I find a question on it,when you create a index(5 shards)
it throws the exception:

[2020-08-16T02:53:12,323][WARN ][o.e.i.IndexService       ] [es0] [a] failed to write dangling indices state for index [a/9mZKbl38Q0mA6IAu1vmE6A]
org.elasticsearch.gateway.WriteStateException: failed to write state to the first location tmp file C:\apps\es0\data\nodes\0\indices\9mZKbl38Q0mA6IAu1vmE6A\state-6.st.tmp
        at org.elasticsearch.gateway.MetadataStateFormat.writeStateToFirstLocation(MetadataStateFormat.java:127) ~[elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.gateway.MetadataStateFormat.write(MetadataStateFormat.java:243) ~[elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.gateway.MetadataStateFormat.writeAndCleanup(MetadataStateFormat.java:185) ~[elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.index.IndexService.writeDanglingIndicesInfo(IndexService.java:348) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.indices.IndicesService$6.doRun(IndicesService.java:1603) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:695) [elasticsearch-7.8.1.jar:7.8.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.8.1.jar:7.8.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.nio.file.FileAlreadyExistsException: C:\apps\es0\data\nodes\0\indices\9mZKbl38Q0mA6IAu1vmE6A\_state\state-6.st.tmp
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:87) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235) ~[?:?]
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478) ~[?:?]
        at java.nio.file.Files.newOutputStream(Files.java:224) ~[?:?]
        at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:410) ~[lucene-core-8.5.1.jar:8.5.1 edb9fc409398f2c3446883f9f80595c884d245d0 - ivera - 2020-04-08 08:55:42]
        at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:406) ~[lucene-core-8.5.1.jar:8.5.1 edb9fc409398f2c3446883f9f80595c884d245d0 - ivera - 2020-04-08 08:55:42]
        at org.apache.lucene.store.FSDirectory.createOutput(FSDirectory.java:254) ~[lucene-core-8.5.1.jar:8.5.1 edb9fc409398f2c3446883f9f80595c884d245d0 - ivera - 2020-04-08 08:55:42]
        at org.elasticsearch.gateway.MetadataStateFormat.writeStateToFirstLocation(MetadataStateFormat.java:107) ~[elasticsearch-7.8.1.jar:7.8.1]
        ... 9 more

The old discovery mode will add the "GatewayClusterApplier", it will write the index meta data,
but we know the "dangling process" will also write the index., 

So two threads handle same index meta data concurrently, the error happen...

Thread[elasticsearch[es0][DanglingIndices#updateTask][T#1],5,main]
Thread[elasticsearch[es0][clusterApplierService#updateTask][T#1],5,main]

I can resolve it by setting "gateway.write_dangling_indices_info: false",
I want to know do we have another better solution?(If I keep using old discovery mode)

**Comment by DaveCTurner** [comment]
> We know we can continue to use old discovery mode by setting:
> discovery.type: legacy-zen

No, this isn't expected to work. According to the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-settings.html#modules-discovery-settings) the only supported value for `discovery.type` is `"single-node"`. You are enabling a hidden mode intended for some internal tests that you can only discover by reading the depths of the source code, but which certainly isn't supported. A little knowledge is a dangerous thing.

I opened #61178 to prevent use of this deeply-hidden test mode outside of tests.

**Comment by DaveCTurner** [comment]
Closed by #61178.
