### ISSUE TITLE
[CI] Failure in CCSDuelIT.testFieldCollapsingOneClusterHasNoResults

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#61258]
**Build scan**:
https://gradle-enterprise.elastic.co/s/oict634dq5vga

**Repro line**:
./gradlew ':qa:multi-cluster-search:remote-cluster' --tests "org.elasticsearch.search.CCSDuelIT.testFieldCollapsingOneClusterHasNoResults" \
  -Dtests.seed=700B200D94EBA284 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-CU \
  -Dtests.timezone=Asia/Singapore \
  -Druntime.java=11

**Reproduces locally?**:
No

**Applicable branches**:
7.x

**Failure history**:
Couldn't find more recent failures

There seems to be a sporadic intialization assertion problem here:

**Failure excerpt**:
java.lang.AssertionError: expected:<1> but was:<2>
	at __randomizedtesting.SeedInfo.seed([700B200D94EBA284:2025134D3E63EADA]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.elasticsearch.search.CCSDuelIT.indexDocuments(CCSDuelIT.java:221)
	at org.elasticsearch.search.CCSDuelIT.lambda$init$0(CCSDuelIT.java:141)
	at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:187)
	at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:211)
	at org.elasticsearch.search.CCSDuelIT.init(CCSDuelIT.java:139)

**Comment by javanna** [comment]
This is indeed weird: we create an index with 1 shard (based on how I read the error), we index some documents into it, we then refresh it, and refresh returns successful : 2 which is not expected. I have no clue how this happened and weird that this tests failed only once in a very long time.
