### ISSUE TITLE
[CI] Failures in JdbcPreparedStatementIT.testConstantKeywordField

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#61256]
**Build scan**:

https://gradle-enterprise.elastic.co/s/hnwhcemwfw6d4

**Repro line**:

```
./gradlew ':x-pack:plugin:sql:qa:jdbc:multi-node:v7.10.0#bwcTest' --tests "org.elasticsearch.xpack.sql.qa.jdbc.multi_node.JdbcPreparedStatementIT.testConstantKeywordField" \
  -Dtests.seed=FAAE2116E1E1A3F2 \
  -Dtests.security.manager=true \
  -Dtests.locale=mt-MT \
  -Dtests.timezone=America/Anguilla \
  -Druntime.java=11 \
  -Dtests.fips.enabled=true
```

**Reproduces locally?**:
No

**Applicable branches**:
master

**Failure history**:
Five failures since Aug 17th so far, on master, 7.x and 7.9
First failure probably this one: https://gradle-enterprise.elastic.co/s/wnria74d4wdkc

**Failure excerpt**:

```
java.lang.AssertionError: expected:<1001> but was:<1003>
	at __randomizedtesting.SeedInfo.seed([FAAE2116E1E1A3F2:11DCA4D592802DBE]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.elasticsearch.xpack.sql.qa.jdbc.PreparedStatementTestCase.testConstantKeywordField(PreparedStatementTestCase.java:242)
```

**Comment by astefan** [comment]
Already fixed with https://github.com/elastic/elasticsearch/pull/61248.

**Comment by cbuescher** [comment]
Thanks, I'll close then and only reopen if I for some reason see this again today.
