### ISSUE TITLE
[CI] SslMultiPortTests testThatStandardTransportClientCanConnectToNoClientAuthProfile fails on 6.8

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#61262]
**Build scan**:
https://gradle-enterprise.elastic.co/s/sbaq67a7bqzlw
https://gradle-enterprise.elastic.co/s/sbaq67a7bqzlw/console-log?task=:x-pack:plugin:security:unitTest

**Repro line**:
./gradlew ':x-pack:plugin:security:unitTest' \
  -Dtests.seed=16301CD8007F75FC \
  -Dtests.class=org.elasticsearch.xpack.security.transport.ssl.SslMultiPortTests \
  -Dtests.method="testThatStandardTransportClientCanConnectToNoClientAuthProfile" \
  -Dtests.security.manager=true \
  -Dtests.locale=und \
  -Dtests.timezone=Asia/Irkutsk \
  -Dcompiler.java=12 \
  -Druntime.java=8

**Reproduces locally?**: No
 
**Applicable branches**: 6.8

**Failure history**:
Couldn't find recent similar looking failures

**Failure excerpt**:
```
1> javax.net.ssl.SSLException: SSLEngine closed already
  1> 	at io.netty.handler.ssl.SslHandler.wrap(...)(Unknown Source) ~[netty-handler-4.1.32.Final.jar:4.1.32.Final]
  1> [2020-08-18T11:50:55,758][WARN ][o.e.x.c.s.t.n.SecurityNetty4Transport] [node_s0] client did not trust this server's certificate, closing connection Netty4TcpChannel{localAddress=0.0.0.0/0.0.0.0:54387, remoteAddress=/127.0.0.1:54248}
  1> [2020-08-18T11:50:55,760][WARN ][o.e.x.c.s.t.n.SecurityNetty4Transport] [node_s0] client did not trust this server's certificate, closing connection Netty4TcpChannel{localAddress=0.0.0.0/0.0.0.0:54387, remoteAddress=/127.0.0.1:54248}
  1> [2020-08-18T11:50:55,759][WARN ][o.e.t.TcpTransport       ] [_client_] exception caught on transport layer [Netty4TcpChannel{localAddress=/127.0.0.1:54248, remoteAddress=localhost/127.0.0.1:54387}], closing connection
  1> io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
  1> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472) ~[netty-codec-4.1.32.Final.jar:4.1.32.Final]
  1>[...]
  1> Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
[...]
  1> Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  1> 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:450) ~[?:?]
[...]
  1> Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  1> 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141) ~[?:?]
[...]
```

**Comment by jkakavas** [comment]
I'm going to close this as a transient error since this hasn't happened before or since. If we get another occurrence, I'll reopend and investigate further
