### ISSUE TITLE
CI: docker failures in 7.x

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#61360]
The gcp docker build triggered a number of failures across different distros:

Debian: Unknown packaging type
```
java.lang.IllegalStateException: Unknown Elasticsearch packaging type.
	at __randomizedtesting.SeedInfo.seed([F2AA1E1586C0F84B:4D387A325DDDE154]:0)
	at org.elasticsearch.packaging.test.KeystoreManagementTests.verifyKeystorePermissions(KeystoreManagementTests.java:497)
	at org.elasticsearch.packaging.test.KeystoreManagementTests.test20CreateKeystoreManually(KeystoreManagementTests.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+packaging-tests-unix-gcp/os=debian-9-packaging/256/console
https://gradle-enterprise.elastic.co/s/m7qywza7g7epk

CentOS: no such file:
```
java.nio.file.NoSuchFileException: /usr/share/elasticsearch/config
	at __randomizedtesting.SeedInfo.seed([152C09C82FB6C832:3B982AA19DCE7463]:0)
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.nio.file.Files.walkFileTree(Files.java:2662)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.elasticsearch.packaging.util.FileUtils.copyDirectory(FileUtils.java:373)
	at org.elasticsearch.packaging.test.PackagingTestCase.withCustomConfig(PackagingTestCase.java:433)
	at org.elasticsearch.packaging.test.ConfigurationTests.test60HostnameSubstitution(ConfigurationTests.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

Log | https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+packaging-tests-unix-gcp/os=centos-7-packaging/256/console

Build Scans | https://gradle-enterprise.elastic.co/s/ecj2tdh4o4jlq

**Comment by costin** [comment]
Another one on debian:

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+packaging-tests-unix-gcp/os=debian-9-packaging/257/console
Build Scan: https://gradle-enterprise.elastic.co/s/j24m3c2swz4j4

**Comment by pugnascotia** [comment]
Huh. I thought I fixed that already. I'll take a look.

**Comment by pugnascotia** [comment]
Bah, I missed some cases. PR impending...

**Comment by pugnascotia** [comment]
This issue also affects `master` - I'll fix that too.
