### ISSUE TITLE
ActivateWatchTests suite failure

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#61538]
**Build scan**:
https://gradle-enterprise.elastic.co/s/7lsgegomrc5mq

**Repro line**:
```
./gradlew ':x-pack:plugin:watcher:unitTest' -Dtests.seed=C91C80295B431103 -Dtests.class=org.elasticsearch.xpack.watcher.transport.action.activate.ActivateWatchTests -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=Etc/UTC -Dcompiler.java=12 -Druntime.java=13
```

**Reproduces locally?**: No.

**Applicable branches**: 6.8

**Failure history**:
https://build-stats.elastic.co/goto/d9892f4ab3b204362b0c57d009a4504c

Twice in the past six months....

**Failure excerpt**:

```
  2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:watcher:unitTest' -Dtests.seed=C91C80295B431103 -Dtests.class=org.elasticsearch.xpack.watcher.transport.action.activate.ActivateWatchTests -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=Etc/UTC -Dcompiler.java=12 -Druntime.java=13
  2> NOTE: test params are: codec=Lucene70, sim=RandomSimilarity(queryNorm=false): {}, locale=lrc-IR, timezone=Etc/GMT-9
  2> NOTE: Linux 4.15.0-1080-gcp amd64/Oracle Corporation 15 (64-bit)/cpus=32,threads=1,free=462966680,total=536870912
  2> NOTE: All tests run in this JVM: [XContentSourceTests, DataAttachmentTests, TextTemplateTests, ActionErrorIntegrationTests, ActivateWatchTests]
ERROR   0.00s J10 | ActivateWatchTests (suite) <<< FAILURES!
   > Throwable #1: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=104, name=elasticsearch[node_s0][watcher][T#7], state=RUNNABLE, group=TGRP-ActivateWatchTests]
   > Caused by: java.lang.IllegalStateException: bulk process already closed
   > 	at __randomizedtesting.SeedInfo.seed([C91C80295B431103]:0)
   > 	at org.elasticsearch.action.bulk.BulkProcessor.ensureOpen(BulkProcessor.java:367)
   > 	at org.elasticsearch.action.bulk.BulkProcessor.internalAdd(BulkProcessor.java:372)
   > 	at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:357)
   > 	at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:353)
   > 	at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:346)
   > 	at org.elasticsearch.xpack.watcher.execution.TriggeredWatchStore.delete(TriggeredWatchStore.java:116)
   > 	at org.elasticsearch.xpack.watcher.execution.ExecutionService.execute(ExecutionService.java:337)
   > 	at org.elasticsearch.xpack.watcher.execution.ExecutionService.lambda$executeAsync$5(ExecutionService.java:416)
   > 	at org.elasticsearch.xpack.watcher.execution.ExecutionService$WatchExecutionTask.run(ExecutionService.java:617)
   > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681)
   > 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
   > 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
   > 	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by dimitris-athanasiou** [comment]
Closing in favour of #66495
