### ISSUE TITLE
[CI] DockerTests.test071BindMountCustomPathWithDifferentUID

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#61553]
**Build scan**:https://gradle-enterprise.elastic.co/s/zytljvsexacbm

**Repro line**: none logged 

**Reproduces locally?**: no idea

**Applicable branches**: 7.x, master

**Failure history**:
https://build-stats.elastic.co/goto/9305134dac50d3ef2708a0d2cf279f57

**Failure excerpt**:

```
:qa:os:destructiveDistroTest.default-docker_ubi FAILED

org.elasticsearch.packaging.test.DockerTests > test071BindMountCustomPathWithDifferentUID FAILED
    org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c docker run --rm --volume "/tmp/DockerTests13638892981020840716:/mount" alpine /bin/sh -c "cd /mount && rm -r esDataDir"]
       result: exitCode = [1] stdout = [] stderr = [rm: can't remove 'esDataDir/_state/pending_segments_e': No such file or directory]
        at __randomizedtesting.SeedInfo.seed([33BF03973DECA4FB:7EF34C50A75223C3]:0)
        at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:158)
        at org.elasticsearch.packaging.util.Shell.run(Shell.java:84)
        at org.elasticsearch.packaging.util.Docker.executePrivilegeEscalatedShellCmd(Docker.java:409)
        at org.elasticsearch.packaging.util.Docker.rmDirWithPrivilegeEscalation(Docker.java:451)
        at org.elasticsearch.packaging.test.DockerTests.lambda$test071BindMountCustomPathWithDifferentUID$1(DockerTests.java:217)
        at org.elasticsearch.packaging.util.Platforms.onLinux(Platforms.java:74)
        at org.elasticsearch.packaging.test.DockerTests.test071BindMountCustomPathWithDifferentUID(DockerTests.java:199)


Suite: Test class org.elasticsearch.packaging.test.DockerTests
  2> org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c docker run --rm --volume "/tmp/DockerTests13638892981020840716:/mount" alpine /bin/sh -c "cd /mount && rm -r esDataDir"]
       result: exitCode = [1] stdout = [] stderr = [rm: can't remove 'esDataDir/_state/pending_segments_e': No such file or directory]
        at __randomizedtesting.SeedInfo.seed([33BF03973DECA4FB:7EF34C50A75223C3]:0)
        at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:158)
        at org.elasticsearch.packaging.util.Shell.run(Shell.java:84)
        at org.elasticsearch.packaging.util.Docker.executePrivilegeEscalatedShellCmd(Docker.java:409)
        at org.elasticsearch.packaging.util.Docker.rmDirWithPrivilegeEscalation(Docker.java:451)
        at org.elasticsearch.packaging.test.DockerTests.lambda$test071BindMountCustomPathWithDifferentUID$1(DockerTests.java:217)
        at org.elasticsearch.packaging.util.Platforms.onLinux(Platforms.java:74)
        at org.elasticsearch.packaging.test.DockerTests.test071BindMountCustomPathWithDifferentUID(DockerTests.java:199)

Tests with failures:
 - org.elasticsearch.packaging.test.DockerTests.test071BindMountCustomPathWithDifferentUID
```

**Comment by rjernst** [comment]
@pugnascotia Could you please take a look?

**Comment by jkakavas** [comment]
Hi @pugnascotia , I'm reopening this as it failed today too : https://gradle-enterprise.elastic.co/s/3ljhjlk2ohxty

**Comment by pugnascotia** [comment]
That last failure was due to a timeout while pulling an image from Docker Hub. Unfortunate, but not the test's fault exactly.

**Comment by jkakavas** [comment]
Apologies, should have looked closer but it was tempting to blame you :)

**Comment by pugnascotia** [comment]
Understandable 😅
