### ISSUE TITLE
[CI] OOM in FIPS Build

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#61616]
**Build scan**: No build scan, only Jenkins 😿 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic-fips/ES_RUNTIME_JAVA=zulu8,nodes=general-purpose/185/console

**Applicable branches**: 7.x

**Failure excerpt**:
```
13:21:02 > Task :qa:repository-multi-version:v7.9.1#Step4NewClusterTest
13:21:02 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
13:21:03 java.lang.OutOfMemoryError: Java heap space
13:21:03 Dumping heap to java_pid2279.hprof ...
13:21:05 Heap dump file created [172357789 bytes in 1.960 secs]
13:21:09 
13:21:09 Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "pool-1-thread-1"
13:21:16 
13:21:16 Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
13:21:19 runbld>>> <<<<<<<<<<<< SCRIPT EXECUTION END <<<<<<<<<<<<
```

Unfortunately the GCS artifact seems to be corrupt, so I don't have much in the way of details.

There were some reproduction lines along the way:
```
./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.authz.WriteActionsTests.testBulk" -Dtests.seed=62FD7D15ED921BE8 -Dtests.security.manager=true -Dtests.locale=en-IN -Dtests.timezone=BET -Druntime.java=8 -Dtests.fips.enabled=true
```

and a lot of errors reported as
```
13:21:00   1> io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: No available authentication scheme
13:21:00   1> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471) ~[netty-codec-4.1.49.Final.jar:4.1.49.Final]
13:21:00   1> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.49.Final.jar:4.1.49.Final]
13:21:00   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
13:21:00   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
13:21:00   1> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
13:21:00   1> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
13:21:00   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
13:21:00   1> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
13:21:00   1> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
13:21:00   1> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
13:21:00   1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
13:21:00   1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
13:21:00   1> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
13:21:00   1> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
13:21:00   1> 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]
13:21:00   1> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]
13:21:00   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
13:21:00   1> Caused by: javax.net.ssl.SSLHandshakeException: No available authentication scheme 
```

**Comment by jkakavas** [comment]
I started looking at these yesterday and have been tracking this in https://github.com/elastic/elasticsearch/issues/61316 . I didn't notice the OOMs but the SSLHandshakeException: No available authentication scheme is what I focused on and this is reproducible locally with Azul zulu 8.

**Comment by jkakavas** [comment]
Closing this in favor of #61316
