### ISSUE TITLE
[CI] windows docs:integTest failures

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#61697]
**Build scan**:
https://gradle-enterprise.elastic.co/s/evy6ulghdf5bc
https://gradle-enterprise.elastic.co/s/ekuqxpei5tx2o
https://gradle-enterprise.elastic.co/s/w7tnvoyrcyufy

**Repro line**:
N/A

**Reproduces locally?**:
Did not try since it looks like it fails only on windows.

**Applicable branches**:
Master and 7x.

**Failure history**:
https://build-stats.elastic.co/goto/9e2b65ad1c23a124dd4b13577a6c8e67
Started failing August 28th and has failed around 26 times since (8 times per day). Seems likely to be related to #61692 and #60923 .

**Failure excerpt**:
Console log:
```
=== Standard error of node `node{:docs:integTest-0}` ===
last 40 non error or warning messages from C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2012-r2\docs\build\testclusters\integTest-0\logs\es.stderr.log ?
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:

...

Execution failed for task ':docs:integTest'.
> process was found dead while waiting for ports files, node{:docs:integTest-0}
```

The node log file in GCP showed following stderr:

```
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:
[0.002s][error][logging] Invalid decorator 'Usersjenkinsworkspaceelastic+elasticsearch+master+multijob-windows-compatibilityoswindows-2012-r2docsbuildtestclustersintegTest-0logsgc.log'.
error:
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=C:Usersjenkinsworkspaceelastic+elasticsearch+master+multijob-windows-compatibilityoswindows-2012-r2docsbuildtestclustersintegTest-0logsgc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
        at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:106)
        at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:71)
        at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:56)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:138)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:96)
```

The `:` in the `file` parameter is likely to confuse java unified logging, since it uses `:` to separate arguments.
```

**Comment by rjernst** [comment]
@breskeby It seems the log file path has all the backslashes removed. Can you take a look?

**Comment by breskeby** [comment]
fixed as part of https://github.com/elastic/elasticsearch/pull/61743
