### ISSUE TITLE
TasksIT.testGetValidTask failure in master

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#61849]
**Build scan**: 

https://gradle-enterprise.elastic.co/s/bzjjapdkctkes/console-log?task=:client:rest-high-level:asyncIntegTest

**Repro line**: 

./gradlew ':client:rest-high-level:asyncIntegTest' --tests "org.elasticsearch.client.TasksIT.testGetValidTask" -Dtests.seed=D53520E90F3EB1C1 -Dtests.security.manager=true -Dtests.locale=zh-Hant-HK -Dtests.timezone=Africa/Sao_Tome -Druntime.java=11

**Reproduces locally?**:

Not in 100 iterations

**Applicable branches**:

master

**Failure history**:

First time it has ever failed in this manner. 

**Failure excerpt**:
```
org.elasticsearch.client.TasksIT > testGetValidTask FAILED
    org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:44849], URI [/_tasks/hOux6zOfRqu8oKd_K6OuNg:56987], status line [HTTP/1.1 404 Not Found]
    {"error":{"root_cause":[{"type":"resource_not_found_exception","reason":"task [hOux6zOfRqu8oKd_K6OuNg:56987] isn't running and hasn't stored its results"}],"type":"resource_not_found_exception","reason":"task [hOux6zOfRqu8oKd_K6OuNg:56987] isn't running and hasn't stored its results"},"status":404}
        at __randomizedtesting.SeedInfo.seed([D53520E90F3EB1C1:D57D0F259C93120A]:0)
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:318)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:262)
        at org.elasticsearch.client.ESRestHighLevelClientTestCase.lambda$checkTaskCompletionStatus$2(ESRestHighLevelClientTestCase.java:346)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:911)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:896)
        at org.elasticsearch.client.TasksIT.testGetValidTask(TasksIT.java:124)
```

**Comment by tvernum** [comment]
Closing this issue since the HLRC is no longer supported/developed on `main`
