### ISSUE TITLE
OutlierDetectionWithMissingFieldsIT.testMissingFields failures

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#61853]
**Build scan**:

[7.10.0] https://gradle-enterprise.elastic.co/s/jxucdvlyzdura
[7.9.1] https://gradle-enterprise.elastic.co/s/7niyyhawaf5ei
https://gradle-enterprise.elastic.co/s/zw5qaa5rmupb6

**Repro line**:
```
gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTest' --tests "org.elasticsearch.xpack.ml.integration.OutlierDetectionWithMissingFieldsIT.testMissingFields" \
  -Dtests.seed=A7B04996B55C0D5F \
  -Dtests.security.manager=true \
  -Dtests.locale=ar \
  -Dtests.timezone=Etc/Zulu \
  -Druntime.java=11
```

**Reproduces locally?**:
No

**Applicable branches**:
master and 7.x

**Failure history**:
Started failing on September 1st: https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(branch,build-id,build_url,message),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testMissingFields),sort:!(time,desc))

**Failure excerpt**:
```
org.elasticsearch.xpack.ml.integration.OutlierDetectionWithMissingFieldsIT > testMissingFields FAILED
    java.lang.AssertionError: progress is complete: [{"phase":"reindexing","progress_percent":1}, {"phase":"loading_data","progress_percent":100}, {"phase":"computing_outliers","progress_percent":100}, {"phase":"writing_results","progress_percent":100}]
    Expected: is <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([A7B04996B55C0D5F:DD129717197A15E]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertProgressComplete(MlNativeDataFrameAnalyticsIntegTestCase.java:227)
        at org.elasticsearch.xpack.ml.integration.OutlierDetectionWithMissingFieldsIT.testMissingFields(OutlierDetectionWithMissingFieldsIT.java:111)
```

**Comment by dimitris-athanasiou** [comment]
The underlying problem for this failure is the same as https://github.com/elastic/elasticsearch/issues/61852. Closing in favor of that one.
