### ISSUE TITLE
AsyncSearchActionIT.testTermsAggregation failures in master 

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#61850]
**Build scan**:

**Repro line**:
```
./gradlew ':x-pack:plugin:async-search:internalClusterTest' --tests "org.elasticsearch.xpack.search.AsyncSearchActionIT.testTermsAggregation" \
  -Dtests.seed=DC511A34397367E2 \
  -Dtests.security.manager=true \
  -Dtests.locale=ja \
  -Dtests.timezone=America/Curacao \
  -Druntime.java=11
```
**Reproduces locally?**:
Yes, 4 times in 200 iterations

**Applicable branches**:
master

**Failure history**:
Once a day , since August 27th
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testTermsAggregation),sort:!(time,desc))
-->
**Failure excerpt**:
```
org.elasticsearch.xpack.search.AsyncSearchActionIT > testTermsAggregation FAILED
    java.lang.AssertionError: 
    Expected: <INTERNAL_SERVER_ERROR>
         but: was <NOT_FOUND>
        at __randomizedtesting.SeedInfo.seed([DC511A34397367E2:1332157DC294FFEA]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.search.AsyncSearchIntegTestCase$2.doNext(AsyncSearchIntegTestCase.java:280)
        at org.elasticsearch.xpack.search.AsyncSearchIntegTestCase$2.next(AsyncSearchIntegTestCase.java:256)
        at org.elasticsearch.xpack.search.AsyncSearchIntegTestCase$2.next(AsyncSearchIntegTestCase.java:243)
        at org.elasticsearch.xpack.search.AsyncSearchActionIT.testTermsAggregation(AsyncSearchActionIT.java:145)
```

**Comment by javanna** [comment]
looks very similar to #61790

**Comment by jimczi** [comment]
That's a duplicate that we'll solve in #61790,  hence closing
