### ISSUE TITLE
RunDataFrameAnalyticsIT failures

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#61852]
There are a few tests that fail: 

org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT testOutlierDetectionWithEnoughDocumentsToScroll
org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT testOutlierDetectionWithFewDocuments
org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT testOutlierDetectionWithMultipleSourceIndices
org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT testOutlierDetectionWithPreExistingDestIndex

with the same error. 

**Build scan**:
[7.10.0] https://gradle-enterprise.elastic.co/s/dp2u6q52kyxus
[7.9.1] https://gradle-enterprise.elastic.co/s/dlgajwjbzcmli
[7.10.0] https://gradle-enterprise.elastic.co/s/w57smywps3wlq
[7.9.1] https://gradle-enterprise.elastic.co/s/at3whtu5np6r6
https://gradle-enterprise.elastic.co/s/c5egkz647juis
 
and

[7.9.1] https://gradle-enterprise.elastic.co/s/jbaq7v3utks6q
[7.10.0] https://gradle-enterprise.elastic.co/s/bnbd27r4httos
[7.10.0] https://gradle-enterprise.elastic.co/s/si6k6omt5gjfe
[7.9.1] https://gradle-enterprise.elastic.co/s/blgn5kzzmp7pg

[7.10.0] https://gradle-enterprise.elastic.co/s/d5w6ctq3li7va
https://gradle-enterprise.elastic.co/s/3o4d53arbbfia

**Repro line**:

Example: 
```
REPRODUCE WITH: gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTest' --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testOutlierDetectionWithFewDocuments" \
  -Dtests.seed=E6859593F0B2A900 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-EC \
  -Dtests.timezone=Canada/Newfoundland \
  -Druntime.java=11
```

**Reproduces locally?**:
Didn't try ( windows)

**Applicable branches**:
master

**Failure history**:

FAiled twice today but hasnt been failing recently with this assertion error. 

**Failure excerpt**:

```

org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT > testOutlierDetectionWithFewDocuments FAILED
    java.lang.AssertionError: progress is complete: [{"phase":"reindexing","progress_percent":1}, {"phase":"loading_data","progress_percent":100}, {"phase":"computing_outliers","progress_percent":100}, {"phase":"writing_results","progress_percent":100}]
    Expected: is <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([E6859593F0B2A900:58D5761152F12CEA]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertProgressComplete(MlNativeDataFrameAnalyticsIntegTestCase.java:227)
        at org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testOutlierDetectionWithFewDocuments(RunDataFrameAnalyticsIT.java:143)
```

**Comment by dimitris-athanasiou** [comment]
I'm working on a fix for this. I should have a PR shortly.
