### ISSUE TITLE
Regression: NullPointerException when executing a percentile aggregation from a 7.8 Client to a 6.x Server

### ISSUE THREAD

**Issue by centic9** [elastic/elasticsearch#62199]
**Elasticsearch version** (`bin/elasticsearch --version`):
Server: Version: 6.8.9, Build: oss/tar/be2c7bf/2020-05-04T17:00:34.323820Z, JVM: 11.0.8 
Client: Version 7.8.1

**Plugins installed**: [default]

**JVM version** (`java -version`): 11.0.8

**OS version** (`uname -a` if on a Unix-like system): Linux

**Description of the problem including expected versus actual behavior**:

We are using the TransportClient 7.8.1 and Server is still at 6.8.9.

When running a percentile aggregation, we encounter a NullPointerException on the 7.8-Client-side during serialization of the query.

There were changes to percentile-aggregation in 7.8 via #51887.

It seems this missed handling of "null" value of PercentileConfig/PercentileMethod at https://github.com/elastic/elasticsearch/blob/v7.8.1/server/src/main/java/org/elasticsearch/search/aggregations/metrics/AbstractPercentilesAggregationBuilder.java#L167 

This was added/changed in 7.8, so it seems to be a regression in handling communication with older versions of Elasticsearch, any server-version below 7.8 seems to be affected.

Possible Workaround: Set the percentile configuration manually via

```
new ES7PercentilesAggregationBuilder(AggregationBuilders.percentiles(queryName).
				percentilesConfig(new PercentilesConfig.TDigest()));
```

Stacktrace:
```
java.lang.NullPointerException
	at org.elasticsearch.search.aggregations.metrics.AbstractPercentilesAggregationBuilder.innerWriteTo(AbstractPercentilesAggregationBuilder.java:167)
	at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doWriteTo(ValuesSourceAggregationBuilder.java:207)
	at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.writeTo(AbstractAggregationBuilder.java:69)
	at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:1091)
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.writeTo(AggregatorFactories.java:254)
	at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.writeTo(AbstractAggregationBuilder.java:67)
	at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:1091)
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.writeTo(AggregatorFactories.java:254)
	at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.writeTo(AbstractAggregationBuilder.java:67)
	at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:1091)
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.writeTo(AggregatorFactories.java:254)
	at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.writeTo(AbstractAggregationBuilder.java:67)
	at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:1091)
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.writeTo(AggregatorFactories.java:254)
	at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.writeTo(AbstractAggregationBuilder.java:67)
	at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:1091)
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.writeTo(AggregatorFactories.java:254)
	at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.writeTo(AbstractAggregationBuilder.java:67)
	at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:1091)
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.writeTo(AggregatorFactories.java:254)
	at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.writeTo(AbstractAggregationBuilder.java:67)
	at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:1091)
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.writeTo(AggregatorFactories.java:254)
	at org.elasticsearch.common.io.stream.StreamOutput.writeOptionalWriteable(StreamOutput.java:952)
	at org.elasticsearch.search.builder.SearchSourceBuilder.writeTo(SearchSourceBuilder.java:271)
	at org.elasticsearch.common.io.stream.StreamOutput.writeOptionalWriteable(StreamOutput.java:952)
	at org.elasticsearch.action.search.SearchRequest.writeTo(SearchRequest.java:236)
	at org.elasticsearch.transport.OutboundMessage.writeMessage(OutboundMessage.java:87)
	at org.elasticsearch.transport.OutboundMessage.serialize(OutboundMessage.java:64)
	at org.elasticsearch.transport.OutboundHandler$MessageSerializer.get(OutboundHandler.java:162)
	at org.elasticsearch.transport.OutboundHandler$MessageSerializer.get(OutboundHandler.java:148)
	at org.elasticsearch.transport.OutboundHandler$SendContext.get(OutboundHandler.java:195)
	at org.elasticsearch.transport.OutboundHandler.internalSend(OutboundHandler.java:129)
	at org.elasticsearch.transport.OutboundHandler.sendMessage(OutboundHandler.java:124)
	at org.elasticsearch.transport.OutboundHandler.sendRequest(OutboundHandler.java:88)
	at org.elasticsearch.transport.TcpTransport$NodeChannels.sendRequest(TcpTransport.java:262)
	at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:739)
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:653)
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:607)
	at org.elasticsearch.action.TransportActionNodeProxy.execute(TransportActionNodeProxy.java:48)
	at org.elasticsearch.client.transport.TransportProxyClient.lambda$execute$0(TransportProxyClient.java:57)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:253)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:57)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:396)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:399)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:70)
```

**Steps to reproduce**:

 1. Start Server 6.8.9
 2. Use binary Client 7.8.1 to execute a Percentile-Aggregation with default values
 3. execution of the query will cause a NullPointerException

**Provide logs (if relevant)**:

N/A

**Comment by polyfractal** [comment]
This slipped through the cracks, but could very well still be an issue.  Marking team-discuss so the team can take a look.

**Comment by nik9000** [comment]
We're sadly pretty swamped and given that this is deprecated I think we won't have time to fix this. I'd be happy to merge any fixes but I don't think any of us are going to work on it.
