### ISSUE TITLE
[CI] RunDataFrameAnalyticsIT fails with Failed to join results failing on 7.x and master

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#62202]
**Build scan**: https://gradle-enterprise.elastic.co/s/d6so7uwrnynhg

**Repro line**: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testOutlierDetectionWithFewDocuments" -Dtests.seed=FD8D6A22D4E1BB58 -Dtests.security.manager=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=es-HN -Dtests.timezone=Africa/Asmara -Druntime.java=8

**Reproduces locally?**: no

**Applicable branches**: 7.x, master

**Failure history**: [3/7days](
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:'%22Failed%20to%20join%20results:%20test_outlier_detection_with_pre_existing_dest_index%22'),sort:!(process.time-start,desc)))

**Failure excerpt**:

```
08:41:19 org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT > testOutlierDetectionWithPreExistingDestIndex FAILED
08:41:19     java.lang.AssertionError: 
08:41:19     Expected: is null
08:41:19          but: was "[test_outlier_detection_with_pre_existing_dest_index] Failed to join results: test_outlier_detection_with_pre_existing_dest_index experienced failure that cannot be automatically retried. See logs for bulk failures"
08:41:19         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
08:41:19         at org.junit.Assert.assertThat(Assert.java:956)
08:41:19         at org.junit.Assert.assertThat(Assert.java:923)
08:41:19         at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:209)
08:41:19         at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.lambda$waitUntilAnalyticsIsStopped$0(MlNativeDataFrameAnalyticsIntegTestCase.java:156)
08:41:19         at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:977)
08:41:19         at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.waitUntilAnalyticsIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:156)
08:41:19         at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.waitUntilAnalyticsIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:152)
08:41:19         at org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testOutlierDetectionWithPreExistingDestIndex(RunDataFrameAnalyticsIT.java:461)
08:41:19 
08:41:19     java.lang.RuntimeException: Had to resort to force-stopping jobs, something went wrong?
08:41:19         at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.stopAnalyticsAndForceStopOnError(MlNativeDataFrameAnalyticsIntegTestCase.java:113)
08:41:19         at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.cleanUpAnalytics(MlNativeDataFrameAnalyticsIntegTestCase.java:91)
08:41:19         at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.cleanUpResources(MlNativeDataFrameAnalyticsIntegTestCase.java:87)
08:41:19         at org.elasticsearch.xpack.ml.integration.MlNativeIntegTestCase.cleanUp(MlNativeIntegTestCase.java:158)
08:41:19         at org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.cleanup(RunDataFrameAnalyticsIT.java:62)
08:41:19 
08:41:19         Caused by:
08:41:19         ElasticsearchStatusException[cannot close data frame analytics [test_outlier_detection_with_pre_existing_dest_index] because it failed, use force stop instead]
08:41:19             at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.conflictStatusException(ExceptionsHelper.java:67)
08:41:19             at org.elasticsearch.xpack.ml.action.TransportStopDataFrameAnalyticsAction.normalStop(TransportStopDataFrameAnalyticsAction.java:173)
08:41:19             at org.elasticsearch.xpack.ml.action.TransportStopDataFrameAnalyticsAction.lambda$doExecute$0(TransportStopDataFrameAnalyticsAction.java:111)
08:41:19             at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
08:41:19             at org.elasticsearch.xpack.ml.action.TransportStopDataFrameAnalyticsAction.lambda$findIdsToStop$1(TransportStopDataFrameAnalyticsAction.java:127)
08:41:19             at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
08:41:19             at org.elasticsearch.xpack.ml.action.TransportStopDataFrameAnalyticsAction.lambda$findIdsToStop$2(TransportStopDataFrameAnalyticsAction.java:136)
08:41:19             at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
08:41:19             at org.elasticsearch.xpack.ml.dataframe.persistence.DataFrameAnalyticsConfigProvider.lambda$getMultiple$5(DataFrameAnalyticsConfigProvider.java:236)
08:41:19             at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
```

**Comment by dimitris-athanasiou** [comment]
A lot has changed in the code since this has been failed and we did not get any more failures like this reported. Closing this as we do not have much to investigate on at the moment.
