### ISSUE TITLE
[CI] BasicLicenseUpgradeIT.testOldAndMixedClusterHaveActiveBasic failure

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#62299]
**Build scan**: https://gradle-enterprise.elastic.co/s/5dz5qvaq35o6k

**Repro line**: 

```
./gradlew ':x-pack:qa:rolling-upgrade-basic:v7.10.0#oneThirdUpgradedTest' --tests "org.elasticsearch.upgrades.BasicLicenseUpgradeIT.testOldAndMixedClusterHaveActiveBasic" -Dtests.seed=8FC3C3A9376C6682 -Dtests.security.manager=true -Dtests.locale=en-ZA -Dtests.timezone=Asia/Baku -Druntime.java=11
```

**Reproduces locally?**: No

**Applicable branches**: master

**Failure excerpt**:

```
org.elasticsearch.upgrades.BasicLicenseUpgradeIT > testOldAndMixedClusterHaveActiveBasic FAILED
09:38:21     org.elasticsearch.client.ResponseException: method [DELETE], host [http://[::1]:34915], URI [_data_stream/*], status line [HTTP/1.1 500 Internal Server Error]
09:38:21     {"error":{"root_cause":[{"type":"e_o_f_exception","reason":null}],"type":"e_o_f_exception","reason":null},"status":500}
09:38:21         at __randomizedtesting.SeedInfo.seed([8FC3C3A9376C6682:AC126A67D16C4803]:0)
09:38:21         at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:318)
09:38:21         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
09:38:21         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:262)
09:38:21         at org.elasticsearch.test.rest.ESRestTestCase.wipeDataStreams(ESRestTestCase.java:666)
09:38:21         at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:556)
09:38:21         at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:314)
09:38:21         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:38:21         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:38:21         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:38:21         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
09:38:21         at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
09:38:21         at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
09:38:21         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
09:38:21         at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
09:38:21         at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
09:38:21         at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
09:38:21         at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
09:38:21         at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
09:38:21         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
09:38:21         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
09:38:21         at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
09:38:21         at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
09:38:21         at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)

```

**Comment by tvernum** [comment]
This seems to have been caused by https://github.com/elastic/elasticsearch/pull/62286 and is now resolved.
