### ISSUE TITLE
SQL: aliasing an aggregate function acting on a nonexistent field generates a StackOverflowError

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#62296]
Assuming a `test` index where the field `bla` doesn't exist. The following queries will generate a StackOverflowError:
- `SELECT MAX(bla) AS bla FROM test WHERE bla = 0`
- `SELECT COUNT(bla) AS bla FROM test WHERE bla = 0`
- `SELECT FIRST(bla) AS bla FROM test WHERE bla = 0`
- `SELECT LAST(bla) AS bla FROM test WHERE bla = 0`

It's likely other aggregate functions will have the same outcome.
Notes:
- the condition has to exist, but it doesn't seem to need to have a certain form (`WHERE bla IS NOT NULL`  reproduces the error as well). But it has to reference the `bla` field.
- the aggregate function has to be aliased as the same name as the field itself

**Comment by astefan** [comment]
```
╗  java.lang.StackOverflowError
╗       at org.elasticsearch.xpack.ql.tree.Node.lambda$transformDown$8(Node.java:178)
╗       at org.elasticsearch.xpack.ql.tree.Node.transformChildren(Node.java:210)
╗       at org.elasticsearch.xpack.ql.tree.Node.transformDown(Node.java:178)
╗       at org.elasticsearch.xpack.ql.tree.Node.lambda$transformDown$8(Node.java:178)
╗       at org.elasticsearch.xpack.ql.tree.Node.transformChildren(Node.java:210)
╗       at org.elasticsearch.xpack.ql.tree.Node.transformDown(Node.java:178)
╗       at org.elasticsearch.xpack.ql.tree.Node.lambda$transformDown$8(Node.java:178)
╗       at org.elasticsearch.xpack.ql.tree.Node.transformChildren(Node.java:210)
╗       at org.elasticsearch.xpack.ql.tree.Node.transformDown(Node.java:178)
╗       at org.elasticsearch.xpack.ql.tree.Node.lambda$transformDown$8(Node.java:178)
╗       at org.elasticsearch.xpack.ql.tree.Node.transformChildren(Node.java:210)
╗       at org.elasticsearch.xpack.ql.tree.Node.transformDown(Node.java:178)
╗       at org.elasticsearch.xpack.ql.tree.Node.lambda$transformDown$8(Node.java:178)
╗       at org.elasticsearch.xpack.ql.tree.Node.transformChildren(Node.java:210)
╗       at org.elasticsearch.xpack.ql.tree.Node.transformDown(Node.java:178)
╗       at org.elasticsearch.xpack.ql.tree.Node.lambda$transformDown$8(Node.java:178)
╗       at org.elasticsearch.xpack.ql.tree.Node.transformChildren(Node.java:210)
╗       at org.elasticsearch.xpack.ql.tree.Node.transformDown(Node.java:178)
╗       at org.elasticsearch.xpack.ql.tree.Node.lambda$transformDown$8(Node.java:178)
╗       at org.elasticsearch.xpack.ql.tree.Node.transformChildren(Node.java:210)
```

**Comment by astefan** [comment]
This happens also when the projection is not an aggregate function, ie the projection could be the result of a function: `SELECT CONCAT(bla, 'x') AS bla FROM test WHERE bla IS NOT NULL`.
