### ISSUE TITLE
[CI] CoordinatorTests.testLogsMessagesIfPublicationDelayed fails reproducibly

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#62383]
I had this failing on a PR and it reproduces on master for me:

https://gradle-enterprise.elastic.co/s/s33wgvgtlqvks

```
./gradlew ':server:test' --tests "org.elasticsearch.cluster.coordination.CoordinatorTests.testLogsMessagesIfPublicationDelayed" -Dtests.seed=BACFE347DDD2C688 -Dtests.security.manager=true -Dtests.locale=fr-CH -Dtests.timezone=Asia/Karachi -Druntime.java=11
```

Error:
```
java.lang.AssertionError: expected to see lag warning but did not
    Expected: <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([BACFE347DDD2C688:50A5B1B04E87756]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.elasticsearch.test.MockLogAppender$SeenEventExpectation.assertMatched(MockLogAppender.java:132)
        at org.elasticsearch.test.MockLogAppender.assertAllExpectationsMatched(MockLogAppender.java:66)
        at org.elasticsearch.cluster.coordination.CoordinatorTests.testLogsMessagesIfPublicationDelayed(CoordinatorTests.java:1513)
```

I saw this starting to fail on Aug 29th in CI failure mails now on 7.x and master, will probably push a commit to mute this test.

**Comment by cbuescher** [comment]
Muted this in 6a9f8908f04a2b5ff94766789e85cff55e1088d5 and 0ca9829867ca9577cbc2a12fe2b329efa4d8cb0f on master and 7.x
