### ISSUE TITLE
[CI] Recurring failure with ILMHistoryTests.testIlmHistoryIndexCanRollover

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#62409]
Could not reproduce this locally (with either OpenJDK or Oracle). But there is a relatively long standing history (since September 3rd) of these failures, so I'm opening an issue to capture them all: https://groups.google.com/a/elastic.co/g/build-elasticsearch/search?q=testIlmHistoryIndexCanRollover

Below is one failure captured from: https://groups.google.com/a/elastic.co/g/build-elasticsearch/c/jVSs4UZnDTI/m/eh0aqwU4BAAJ

```
22:25:12 REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:internalClusterTest' --tests "org.elasticsearch.xpack.ilm.ILMHistoryTests.testIlmHistoryIndexCanRollover" -Dtests.seed=1437E99FE304FB57 -Dtests.security.manager=true -Dtests.locale=mt -Dtests.timezone=SystemV/EST5 -Druntime.java=11
```

```
22:25:12 org.elasticsearch.xpack.ilm.ILMHistoryTests > testIlmHistoryIndexCanRollover FAILED
22:25:12     java.lang.AssertionError: Count is 6 hits but 9 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
22:25:12         at __randomizedtesting.SeedInfo.seed([1437E99FE304FB57:69A474D02C603615]:0)
22:25:12         at org.junit.Assert.fail(Assert.java:88)
22:25:12         at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertHitCount(ElasticsearchAssertions.java:270)
22:25:12         at org.elasticsearch.xpack.ilm.ILMHistoryTests.lambda$testIlmHistoryIndexCanRollover$1(ILMHistoryTests.java:97)
22:25:12         at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:923)
22:25:12         at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:896)
22:25:12         at org.elasticsearch.xpack.ilm.ILMHistoryTests.testIlmHistoryIndexCanRollover(ILMHistoryTests.java:94)
```

**Comment by probakowski** [comment]
This will hopefully be fixed by @original-brownbear's fix in #62353

**Comment by probakowski** [comment]
My bad, looks like this is different failure, I'll take a look

**Comment by original-brownbear** [comment]
@probakowski no this is exactly the spot I fixed. Looking at the line numbers in the failure it occurred in code without my fix.
-> This can be closed I think.
