### ISSUE TITLE
[CI] Failure in LogstashSystemIndexIT.testPipelineCRUD

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#62413]
Several reproducible failures on CI: https://groups.google.com/a/elastic.co/g/build-elasticsearch/search?q=testPipelineCRUD

Reproducible failure:
```
./gradlew ':x-pack:plugin:javaRestTest' --tests "org.elasticsearch.xpack.test.rest.LogstashSystemIndexIT.testPipelineCRUD" -Dtests.seed=E7A729884346CF82 -Dtests.security.manager=true -Dtests.locale=ar-JO -Dtests.timezone=America/Winnipeg -Druntime.java=11
```

Stacktrace:
```
11:32:27   2> java.lang.AssertionError: 
11:32:27     Expected: is "{}"
11:32:27          but: was "{\"test_pipeline\":{\"description\":\"test pipeline\",\"last_modified\":\"2020-03-09T15:42:30.229Z\",\"pipeline_metadata\":{\"version\":1,\"type\":\"logstash_pipeline\"},\"username\":\"john.doe\",\"pipeline\":\"\\\"input\\\": {},\\n \\\"filter\\\": {},\\n \\\"output\\\": {}\\n\",\"pipeline_settings\":{\"pipeline.batch.delay\":50,\"pipeline.batch.size\":125,\"pipeline.workers\":1,\"queue.checkpoint.writes\":1024,\"queue.max_bytes\":\"1gb\",\"queue.type\":\"memory\"}}}"
11:32:27         at __randomizedtesting.SeedInfo.seed([E7A729884346CF82:67B3BE1FAC2C7248]:0)
11:32:27         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
11:32:27         at org.junit.Assert.assertThat(Assert.java:956)
11:32:27         at org.junit.Assert.assertThat(Assert.java:923)
11:32:27         at org.elasticsearch.xpack.test.rest.LogstashSystemIndexIT.testPipelineCRUD(LogstashSystemIndexIT.java:85)
```

**Comment by cbuescher** [comment]
Another one today: https://gradle-enterprise.elastic.co/s/vf3m4tervizoc

**Comment by cbuescher** [comment]
Four more today, some on 7.x as well: https://gradle-enterprise.elastic.co/s/vmco3eehybmsq
I'm going to mute this one on master and 7.x

**Comment by cbuescher** [comment]
Muted in 64856987504e0f9322ecb35827680dd66cb7c57a and 6a016fb75597a9edacbf0027a633c82227b78b07

**Comment by williamrandolph** [comment]
Thanks for muting. I'll take a look.

**Comment by williamrandolph** [comment]
I merged what I hope is a fix, but if this comes up again I'm happy to keep working on it.
