### ISSUE TITLE
[CI] SmokeTestMonitoringWithSecurityIT.testHTTPExporterWithSSL failures on 7.9

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#62432]
**Build scan**:

https://gradle-enterprise.elastic.co/s/wqoychhjnlccs

**Repro line**:

./gradlew ':x-pack:qa:smoke-test-plugins-ssl:integTestRunner' --tests "org.elasticsearch.smoketest.SmokeTestMonitoringWithSecurityIT.testHTTPExporterWithSSL" \
  -Dtests.seed=E1133752B86D6B74 \
  -Dtests.security.manager=true \
  -Dtests.locale=sq-AL \
  -Dtests.timezone=America/Indianapolis \
  -Druntime.java=11 \
  -Dtests.fips.enabled=true

**Reproduces locally?**:

No

**Applicable branches**:

7.9

**Failure history**:

Saw one similar looking failure back on Sep. 10th

**Failure excerpt**:

```
java.lang.AssertionError: 
Expected: <true>
     but: was <false>
	at __randomizedtesting.SeedInfo.seed([E1133752B86D6B74:27821156061A06EF]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.smoketest.SmokeTestMonitoringWithSecurityIT.lambda$testHTTPExporterWithSSL$4(SmokeTestMonitoringWithSecurityIT.java:155)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:951)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:924)
	at org.elasticsearch.smoketest.SmokeTestMonitoringWithSecurityIT.testHTTPExporterWithSSL(SmokeTestMonitoringWithSecurityIT.java:153)
```

**Comment by jbaiera** [comment]
Closing this as it seems its a duplicate of #83130
