### ISSUE TITLE
[CI] DockerTests.test101AllFilesAreGroupZero failure on 7.x

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#62466]
Looks somewhat similar to https://github.com/elastic/elasticsearch/issues/54817 but might be a new issue since that one should be fixed

**Build scan**:

https://gradle-enterprise.elastic.co/s/37vs72sp7l5xi

**Repro line**:

---

**Reproduces locally?**:
no

**Applicable branches**:
7.x

**Failure excerpt**:
```
java.lang.RuntimeException: Command was not successful: [bash -c docker exec --user elasticsearch:root --tty 1ea428dd8ea98a7556768a1d6b880221d000c85ea31a0c9d41172cefbaf1b5b5 find . -not -gid 0]
   result: exitCode = [1] stdout = [find: './data/nodes/0/_state/_m.fdx': No such file or directory
./data/nodes/0/_state/_m.fdx] stderr = []
	at __randomizedtesting.SeedInfo.seed([82522C0BE4A6058F:103E3B6B6F630D8D]:0)
	at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:158)
	at org.elasticsearch.packaging.util.Shell.run(Shell.java:84)
	at org.elasticsearch.packaging.test.DockerTests.test101AllFilesAreGroupZero(DockerTests.java:531)
```

**Comment by pugnascotia** [comment]
I'll look into this.
