### ISSUE TITLE
[CI] ValueCountAggregatorTests.testSingleScriptNumber failure

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#62489]
**Build scan**:
https://gradle-enterprise.elastic.co/s/o3upu4ujz4z6g

**Repro line**:

./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.metrics.ValueCountAggregatorTests.testSingleScriptNumber" \
  -Dtests.seed=88D6605BE5528D4E \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-SD \
  -Dtests.timezone=America/Argentina/San_Juan \
  -Druntime.java=11

**Reproduces locally?**:
Yes

**Applicable branches**:
7.x

**Failure history**:

**Failure excerpt**:

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([88D6605BE5528D4E:AFD772B26EB53C0A]:0)
	at org.apache.lucene.search.AssertingScorer.score(AssertingScorer.java:100)
	at org.apache.lucene.search.AssertingScorable.score(AssertingScorable.java:36)
	at org.elasticsearch.script.AggregationScript.get_score(AggregationScript.java:127)
	at org.elasticsearch.script.MockScriptEngine$MockAggregationScript$1$1.execute(MockScriptEngine.java:609)
	at org.elasticsearch.search.aggregations.support.values.ScriptBytesValues.advanceExact(ScriptBytesValues.java:56)
	at org.elasticsearch.search.aggregations.metrics.ValueCountAggregator$3.collect(ValueCountAggregator.java:107)
	at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:107)
	at org.apache.lucene.search.AssertingLeafCollector.collect(AssertingLeafCollector.java:49)
	at org.apache.lucene.search.AssertingCollector$1.collect(AssertingCollector.java:53)
	at org.apache.lucene.search.AssertingLeafCollector.collect(AssertingLeafCollector.java:49)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:269)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:224)
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39)
	at org.apache.lucene.search.AssertingBulkScorer.score(AssertingBulkScorer.java:71)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:661)
	at org.apache.lucene.search.AssertingIndexSearcher.search(AssertingIndexSearcher.java:72)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:445)
	at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:467)
	at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:405)
	at org.elasticsearch.search.aggregations.AggregatorTestCase.testCase(AggregatorTestCase.java:524)
	at org.elasticsearch.search.aggregations.metrics.ValueCountAggregatorTests.testAggregation(ValueCountAggregatorTests.java:402)
	at org.elasticsearch.search.aggregations.metrics.ValueCountAggregatorTests.testSingleScriptNumber(ValueCountAggregatorTests.java:302)
```

**Comment by iverase** [comment]
Fixed in 265387f348297e9389d7bddc223c4314349ee2a4
