### ISSUE TITLE
AppendProcessorTests.testAppendingToListWithDuplicatesDisallowed can fail with assertion

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#62839]
**Build scan**: https://gradle-enterprise.elastic.co/s/dlgmkmibgzt2a

**Repro line**:

```
./gradlew ':modules:ingest-common:test' --tests "org.elasticsearch.ingest.common.AppendProcessorTests.testAppendingToListWithDuplicatesDisallowed" -Dtests.seed=7B44849061BF4D9F -Dtests.security.manager=true -Dtests.locale=th-TH -Dtests.timezone=America/Argentina/Cordoba -Druntime.java=11
```

**Reproduces locally?**: yes

**Applicable branches**: master

**Failure history**: failed twice recently, once on Sept 15th and once today.

**Failure excerpt**:
```
11:08:02   2> java.lang.AssertionError: 
11:08:02     Expected: iterable with items ["JZonyzmDZ", "qvEz", "TOGLQxvUng", "FOeEwuE", "XUafHwFLfr", "NvW", "Y", "rDU", "XsDDBt", "bzvqy", "Y", "wBMUs"] in any order
11:08:02          but: no item matches: "Y" in ["JZonyzmDZ", "qvEz", "TOGLQxvUng", "FOeEwuE", "XUafHwFLfr", "NvW", "Y", "XsDDBt", "bzvqy", "rDU", "wBMUs"]
11:08:02         at __randomizedtesting.SeedInfo.seed([7B44849061BF4D9F:699BB024BAB4EF35]:0)
11:08:02         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
11:08:02         at org.junit.Assert.assertThat(Assert.java:956)
11:08:02         at org.junit.Assert.assertThat(Assert.java:923)
11:08:02         at org.elasticsearch.ingest.common.AppendProcessorTests.testAppendingToListWithDuplicatesDisallowed(AppendProcessorTests.java:222)
```

**Comment by jtibshirani** [comment]
I pushed 755f9acc6e60f736603c077844792bb8873c467c to mute the test on master.
