### ISSUE TITLE
CI: GCSCleanupTests fail

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#63091]
**Build scan**:
https://gradle-enterprise.elastic.co/s/4z3szwzixwyyg/tests?toggled=WyI6eC1wYWNrOnNuYXBzaG90LXRvb2w6cWE6Z29vZ2xlLWNsb3VkLXN0b3JhZ2UtZ2NzdGhpcmRwYXJ0eXRlc3Qtb3JnLmVsYXN0aWNzZWFyY2guc25hcHNob3RzLWdjc2NsZWFudXB0ZXN0cyJd

**Repro line**:
```
  1> [2020-09-30T21:13:02,303][INFO ][o.e.s.GCSCleanupTests    ] [testCleanup] before test
  1> [2020-09-30T21:13:02,305][INFO ][o.e.s.GCSCleanupTests    ] [testCleanup] --> execute cleanup tool on empty repo, there is nothing to cleanup
  1> [2020-09-30T21:13:02,428][INFO ][o.e.s.GCSCleanupTests    ] [testCleanup] Cleanup command output:
  1> Obtaining latest index file generation and creation timestamp
  1> No index-N files found. Repository is empty or corrupted? Exiting

  1> [2020-09-30T21:13:02,438][DEPRECATION][o.e.d.c.m.MetadataCreateIndexService] [node_s_0] index [test-idx-1] matches multiple legacy templates [one_shard_index_template, random-soft-deletes-template], composable templates will only match a single template
  1> [2020-09-30T21:13:02,452][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s_0] [test-idx-1] creating index, cause [api], templates [random-soft-deletes-template, one_shard_index_template], shards [1]/[0]
  1> [2020-09-30T21:13:02,679][INFO ][o.e.c.r.a.AllocationService] [node_s_0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test-idx-1][0]]]).
  1> [2020-09-30T21:13:02,721][DEPRECATION][o.e.d.c.m.MetadataCreateIndexService] [node_s_0] index [test-idx-2] matches multiple legacy templates [one_shard_index_template, random-soft-deletes-template], composable templates will only match a single template
  1> [2020-09-30T21:13:02,727][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s_0] [test-idx-2] creating index, cause [api], templates [random-soft-deletes-template, one_shard_index_template], shards [1]/[0]
  1> [2020-09-30T21:13:02,775][INFO ][o.e.c.r.a.AllocationService] [node_s_0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test-idx-2][0]]]).
  1> [2020-09-30T21:13:02,794][DEPRECATION][o.e.d.c.m.MetadataCreateIndexService] [node_s_0] index [test-idx-3] matches multiple legacy templates [one_shard_index_template, random-soft-deletes-template], composable templates will only match a single template
  1> [2020-09-30T21:13:02,799][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s_0] [test-idx-3] creating index, cause [api], templates [random-soft-deletes-template, one_shard_index_template], shards [1]/[0]
  1> [2020-09-30T21:13:02,838][INFO ][o.e.c.r.a.AllocationService] [node_s_0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test-idx-3][0]]]).
  1> [2020-09-30T21:13:02,855][INFO ][o.e.s.GCSCleanupTests    ] [testCleanup] --> indexing some data
  1> [2020-09-30T21:13:02,926][INFO ][o.e.c.m.MetadataMappingService] [node_s_0] [test-idx-1/bvgqIszGSo-8ZvVA3VFJRg] create_mapping [doc]
  1> [2020-09-30T21:13:02,990][INFO ][o.e.c.m.MetadataMappingService] [node_s_0] [test-idx-2/nSr6fJXsQdawfpxJhhsI7Q] create_mapping [doc]
  1> [2020-09-30T21:13:03,028][INFO ][o.e.c.m.MetadataMappingService] [node_s_0] [test-idx-3/Ag8FcvBaQ8asivVDhBoePg] create_mapping [doc]
  1> [2020-09-30T21:13:03,717][INFO ][o.e.s.GCSCleanupTests    ] [testCleanup] Iteration number 1
  1> [2020-09-30T21:13:03,717][INFO ][o.e.s.GCSCleanupTests    ] [testCleanup] --> create first snapshot
  1> [2020-09-30T21:13:03,777][INFO ][o.e.s.SnapshotsService   ] [node_s_0] snapshot [test-repo:snap1/QwR-0bDVS-Kj10S_GDe2uA] started
  1> [2020-09-30T21:13:04,895][INFO ][o.e.s.SnapshotsService   ] [node_s_0] snapshot [test-repo:snap1/QwR-0bDVS-Kj10S_GDe2uA] completed with state [SUCCESS]
  1> [2020-09-30T21:13:04,949][INFO ][o.e.s.GCSCleanupTests    ] [testCleanup] --> execute cleanup tool, there is nothing to cleanup
  1> [2020-09-30T21:13:05,261][INFO ][o.e.s.GCSCleanupTests    ] [testCleanup] Cleanup command output:
  1> Obtaining latest index file generation and creation timestamp
  1> Latest index file generation is 0
  1> Latest index file creation timestamp is Wed Sep 30 21:13:04 AMT 2020
  1> Shifted by safety gap creation timestamp is Wed Sep 30 21:13:04 AMT 2020
  1> Reading latest index file
  1> Failed to read [incompatible-snapshots] blob
./gradlew ':x-pack:snapshot-tool:qa:google-cloud-storage:gcsThirdPartyTest' \
  --tests "org.elasticsearch.snapshots.GCSCleanupTests.testCleanup" \
  -Dtests.seed=EBDFEEEBDF79EE6A -Dtests.security.manager=false -Dtests.locale=es-DO -Dtests.timezone=Asia/Yerevan -Druntime.java=8	
```

**Reproduces locally?**:
I don't have the creds.

**Applicable branches**:

**Failure history**:
Looks to have started failing on 2020-9-24:
https://build-stats.elastic.co/goto/8c635f54f2b8231275d485652b34ba6c

**Failure excerpt**:
```
  1> [2020-09-30T21:13:05,262][INFO ][o.e.s.GCSCleanupTests    ] [testCleanup] after test
  1> [2020-09-30T21:13:05,264][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_s_0] [test-idx-3/Ag8FcvBaQ8asivVDhBoePg] deleting index
  1> [2020-09-30T21:13:05,265][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_s_0] [test-idx-2/nSr6fJXsQdawfpxJhhsI7Q] deleting index
  1> [2020-09-30T21:13:05,265][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_s_0] [test-idx-1/bvgqIszGSo-8ZvVA3VFJRg] deleting index
  2> REPRODUCE WITH: ./gradlew ':x-pack:snapshot-tool:qa:google-cloud-storage:gcsThirdPartyTest' --tests "org.elasticsearch.snapshots.GCSCleanupTests.testCleanup" -Dtests.seed=EBDFEEEBDF79EE6A -Dtests.security.manager=false -Dtests.locale=es-DO -Dtests.timezone=Asia/Yerevan -Druntime.java=8
  2> java.io.IOException: com.google.cloud.RetryHelper$RetryHelperException: com.google.cloud.storage.StorageException: 404 Not Found
    GET https://storage.googleapis.com/download/storage/v1/b/elasticsearch-ci-thirdparty/o/7.x%2Fincompatible-snapshots?alt=media
    No such object: elasticsearch-ci-thirdparty/7.x/incompatible-snapshots
        at __randomizedtesting.SeedInfo.seed([EBDFEEEBDF79EE6A:BBF5BD45A6D47EDF]:0)
        at com.google.cloud.storage.BlobReadChannel.read(BlobReadChannel.java:141)
        at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
        at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
        at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
        at java.io.InputStream.read(InputStream.java:101)
        at org.elasticsearch.core.internal.io.Streams.copy(Streams.java:57)
        at org.elasticsearch.core.internal.io.Streams.copy(Streams.java:91)
        at org.elasticsearch.snapshots.AbstractRepository.getIncompatibleSnapshots(AbstractRepository.java:91)
        at org.elasticsearch.snapshots.AbstractRepository.cleanup(AbstractRepository.java:173)
        at org.elasticsearch.snapshots.AbstractCleanupCommand.execute(AbstractCleanupCommand.java:48)
        at org.elasticsearch.snapshots.GCSCleanupTests.lambda$commandRunnable$0(GCSCleanupTests.java:101)

        Caused by:
        com.google.cloud.RetryHelper$RetryHelperException: com.google.cloud.storage.StorageException: 404 Not Found
        GET https://storage.googleapis.com/download/storage/v1/b/elasticsearch-ci-thirdparty/o/7.x%2Fincompatible-snapshots?alt=media
        No such object: elasticsearch-ci-thirdparty/7.x/incompatible-snapshots
            at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:54)
            at com.google.cloud.storage.BlobReadChannel.read(BlobReadChannel.java:123)
            ... 10 more

            Caused by:
            com.google.cloud.storage.StorageException: 404 Not Found
            GET https://storage.googleapis.com/download/storage/v1/b/elasticsearch-ci-thirdparty/o/7.x%2Fincompatible-snapshots?alt=media
            No such object: elasticsearch-ci-thirdparty/7.x/incompatible-snapshots
                at com.google.cloud.storage.StorageException.translate(StorageException.java:97)
                at com.google.cloud.storage.spi.v1.HttpStorageRpc.read(HttpStorageRpc.java:728)
                at com.google.cloud.storage.BlobReadChannel$1.call(BlobReadChannel.java:127)
                at com.google.cloud.storage.BlobReadChannel$1.call(BlobReadChannel.java:124)
                at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
                at com.google.cloud.RetryHelper.run(RetryHelper.java:76)
                at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
                ... 11 more

                Caused by:
                com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
                GET https://storage.googleapis.com/download/storage/v1/b/elasticsearch-ci-thirdparty/o/7.x%2Fincompatible-snapshots?alt=media
                No such object: elasticsearch-ci-thirdparty/7.x/incompatible-snapshots
                    at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:149)
                    at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:112)
                    at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:39)
                    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:443)
                    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1108)
                    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:541)
                    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:474)
                    at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeMedia(AbstractGoogleClientRequest.java:502)
                    at com.google.api.services.storage.Storage$Objects$Get.executeMedia(Storage.java:7029)
                    at com.google.cloud.storage.spi.v1.HttpStorageRpc.read(HttpStorageRpc.java:723)
                    ... 16 more
  1> [2020-09-30T21:13:05,834][INFO ][o.e.s.GCSCleanupTests    ] [testNegativeSafetyGap] before test
```

**Comment by original-brownbear** [comment]
I think I know where this is coming from, I'll fix it tomorrow.

**Comment by original-brownbear** [comment]
Closed via https://github.com/elastic/elasticsearch/pull/63168

**Comment by droberts195** [comment]
There was another failure today for 7.x that looks identical to the one in the issue description: https://gradle-enterprise.elastic.co/s/5klktiqomiobo

So the fix doesn't seem to have worked in every case.

**Comment by original-brownbear** [comment]
https://github.com/elastic/elasticsearch/pull/63243 should resolve this for good, sorry for the noise
