### ISSUE TITLE
[CI] ClassificationEvaluationWithSecurityIT testEvaluate_withSecurity failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#63118]
**Build scan**: https://gradle-enterprise.elastic.co/s/ysr3jinsb3yqo

**Repro line**: `gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.ClassificationEvaluationWithSecurityIT.testEvaluate_withSecurity" -Dtests.seed=37732706B5234FF -Dtests.security.manager=true -Dtests.locale=he -Dtests.timezone=Australia/Tasmania -Druntime.java=12`

**Reproduces locally?**: No

**Applicable branches**: 7.9

**Failure history**: https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.xpack.ml.integration.ClassificationEvaluationWithSecurityIT%22%20AND%20branch:7.9%20AND%20test:%22testEvaluate_withSecurity%22'),sort:!(time,desc))

Failed 8 times in the last 30 days.

**Failure excerpt**: 
```
org.elasticsearch.xpack.ml.integration.ClassificationEvaluationWithSecurityIT > testEvaluate_withSecurity FAILED
    org.elasticsearch.client.WarningFailureException: method [POST], host [http://[::1]:46039], URI [test_data/_doc], status line [HTTP/1.1 201 Created]
    Warnings: [[index.force_memory_term_dictionary] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version.]
    {"_index":"test_data","_type":"_doc","_id":"_pZd4nQBfojTIMNw5Zwo","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1}
        at __randomizedtesting.SeedInfo.seed([37732706B5234FF:3B51E2781CE84ACF]:0)
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:298)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:272)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246)
        at org.elasticsearch.xpack.ml.integration.ClassificationEvaluationWithSecurityIT.testEvaluate_withSecurity(ClassificationEvaluationWithSecurityIT.java:64)
```

A very similar failure here: https://github.com/elastic/elasticsearch/issues/61564

**Comment by dimitris-athanasiou** [comment]
This looks unrelated to the particular test. There is a number of tests failing probably because something caused trouble in the cluster.

**Comment by droberts195** [comment]
> A very similar failure here: #61564

It looks like the fix for #61564 also fixed this.
