### ISSUE TITLE
[CI] missing x-pack-ml/NOTICE.txt when building oss-linux-tar

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#63128]
**Build scan**: https://gradle-enterprise.elastic.co/s/3uv2bq5e2vjza

**Repro line**: N/A

**Reproduces locally?**: N/A

**Applicable branches**: master

**Failure history**: none

**Failure excerpt**:

```
:distribution:archives:oss-linux-tar:checkLicense
:distribution:archives:oss-linux-tar:checkMlCppNotice
java.nio.file.NoSuchFileException: /dev/shm/elastic+elasticsearch+master+multijob+fast+part1/distribution/archives/oss-linux-tar/build/tar-extracted/elasticsearch-8.0.0-SNAPSHOT/modules/x-pack-ml/NOTICE.txt
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2916)
	at java.base/java.nio.file.Files.readAllLines(Files.java:3396)
	at java.base/java.nio.file.Files.readAllLines(Files.java:3436)
	at org.elasticsearch.gradle.internal.InternalDistributionArchiveCheckPlugin$1.execute(InternalDistributionArchiveCheckPlugin.java:117)
	at org.elasticsearch.gradle.internal.InternalDistributionArchiveCheckPlugin$1.execute(InternalDistributionArchiveCheckPlugin.java:105)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:731)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:704)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.run(ExecuteActionsTaskExecuter.java:570)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:395)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:387)
```

Not sure exactly if this is a true failure or not, better to have a second pair of eyes looking at it, just in case.

**Comment by droberts195** [comment]
It's not surprising the ML notices don't exist when building OSS, because it's a commercial feature.  It may mean that the code that adds in the notices from the ML native components needs to be conditionally executed when building the default distribution/excluded when building OSS.
