### ISSUE TITLE
[CI] UpdateThreadPoolSettingsTests testFixedExecutorType failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#63131]
**Build scan**: https://gradle-enterprise.elastic.co/s/safmn5nukss7y

**Repro line**: `./gradlew ':server:test' --tests "org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests.testFixedExecutorType" -Dtests.seed=314CD7EE34B70039 -Dtests.security.manager=true -Dtests.locale=sq -Dtests.timezone=Australia/Sydney -Druntime.java=8`

**Reproduces locally?**: No

**Applicable branches**: 7.x

**Failure history**: [failed 5 times in the last 30 days. First failure on Sept 23rd.](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests%22%20AND%20test:%22testFixedExecutorType%22'),sort:!(time,desc)))

**Failure excerpt**:
```
org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests > testFixedExecutorType FAILED
    java.lang.IllegalArgumentException: Failed to parse value [15] for setting [thread_pool.system_write.size] must be <= 13
        at __randomizedtesting.SeedInfo.seed([314CD7EE34B70039:18FECDC3778D68C]:0)
        at org.elasticsearch.common.settings.Setting.parseInt(Setting.java:1260)
        at org.elasticsearch.common.settings.Setting.parseInt(Setting.java:1249)
        at org.elasticsearch.threadpool.FixedExecutorBuilder.lambda$new$1(FixedExecutorBuilder.java:117)
        at org.elasticsearch.common.settings.Setting.get(Setting.java:441)
        at org.elasticsearch.common.settings.Setting.get(Setting.java:435)
        at org.elasticsearch.threadpool.FixedExecutorBuilder.getSettings(FixedExecutorBuilder.java:131)
        at org.elasticsearch.threadpool.FixedExecutorBuilder.getSettings(FixedExecutorBuilder.java:38)
        at org.elasticsearch.threadpool.ThreadPool.<init>(ThreadPool.java:214)
        at org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests.testFixedExecutorType(UpdateThreadPoolSettingsTests.java:107)
```

**Comment by rjernst** [comment]
It looks like this started failing right after https://github.com/elastic/elasticsearch/pull/61655 was merged. @jaymode Can you take a look? My hunch is this randomly fails when the new SYSTEM_WRITE thread pool gets randomly selected in this test.

**Comment by cbuescher** [comment]
Another one today on 7.10: https://gradle-enterprise.elastic.co/s/xklyf67werd5c
