### ISSUE TITLE
TranslogTests.testFatalIOExceptionsWhileWritingConcurrently fails

### ISSUE THREAD

**Issue by tbrooks8** [elastic/elasticsearch#63299]
Stacktrace:

java.lang.AssertionError: expected:<98> but was:<99>
	at __randomizedtesting.SeedInfo.seed([6FCCE4EB877E5B57:3804632485A8F914]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.elasticsearch.index.translog.TranslogTests.testFatalIOExceptionsWhileWritingConcurrently(TranslogTests.java:2357)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

**Reproduces locally?**:

I am able to consistently reproduce when I run 1K times in Intellij.

**Applicable branches**:

Master

This is what is happening here:

In the past, the first thing we did was write the operation to a buffered output stream which may or may not involve flushing the file. There are no guarantees at this point. After that, we marked some metadata about the operation being added to the translog.

Now we add the operation to the buffer and increment metadata. After that, if the buffer is full, we flush. This is the first time we have the options for the mocked exceptions thrown in this test. Occasionally, the exception is thrown and our test infrastructure assumed this operation was not added successfully. However, it was and the metadata was incremented. So, the total operations are not what we expect.

**Comment by cbuescher** [comment]
Just fyi one today on 7.10: https://gradle-enterprise.elastic.co/s/n4fjwfehfndjm

**Comment by tbrooks8** [comment]
Thanks for reminding me. I will either fix or mute today.
