### ISSUE TITLE
[CI] DedicatedClusterSnapshotRestoreIT.testRestoreIndexWithShardsMissingInLocalGateway failure

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#63476]
**Build scan**:
https://gradle-enterprise.elastic.co/s/jeyrxd3tacn7c

**Repro line**:
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT.testRestoreIndexWithShardsMissingInLocalGateway" \
  -Dtests.seed=65E525FA968063DA \
  -Dtests.security.manager=true \
  -Dtests.locale=hr \
  -Dtests.timezone=Etc/GMT-2 \
  -Druntime.java=8

**Reproduces locally?**:
no

**Applicable branches**:
7.x

**Failure history**:
seen nothing recent

**Failure excerpt**:
java.lang.AssertionError: 
Expected: a value equal to or greater than <3>
     but: <2> was less than <3>
	at __randomizedtesting.SeedInfo.seed([65E525FA968063DA:92EF1F5C86019C56]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT.testRestoreIndexWithShardsMissingInLocalGateway(DedicatedClusterSnapshotRestoreIT.java:617)

**Comment by original-brownbear** [comment]
This is reproducible locally on 7.x ... looking into a fix
