### ISSUE TITLE
[CI] Failure in ConcurrentSnapshotsIT  testConcurrentSnapshotWorksWithOldVersionRepo

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#63672]
Both in 7.x and master there seems to be an NPE in:
```

java.lang.NullPointerException: null
  | at org.elasticsearch.snapshots.InFlightShardSnapshotStates.assertGenerationConsistency(InFlightShardSnapshotStates.java:107) ~[main/:?] |  
  | at org.elasticsearch.snapshots.InFlightShardSnapshotStates.addStateInformation(InFlightShardSnapshotStates.java:79) ~[main/:?] |  
  | at org.elasticsearch.snapshots.InFlightShardSnapshotStates.forRepo(InFlightShardSnapshotStates.java:68) ~[main/:?] |  
  | at org.elasticsearch.cluster.SnapshotsInProgress.assertConsistentEntries(SnapshotsInProgress.java:749) ~[main/:?] |  
  | at org.elasticsearch.cluster.SnapshotsInProgress.<init>(SnapshotsInProgress.java:763) ~[main/:?] |  
  | at org.elasticsearch.cluster.SnapshotsInProgress.of(SnapshotsInProgress.java:758) ~[main/:?] |  
  | at org.elasticsearch.snapshots.SnapshotsService$2.execute(SnapshotsService.java:434) ~[main/:?] |  
  | at org.elasticsearch.repositories.blobstore.BlobStoreRepository$1.execute(BlobStoreRepository.java:371) ~[main/:?] |  
  | at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) ~[main/:?] |  
  | at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:702) ~[main/:?] |  
  | at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:324) ~[main/:?] |  
  | at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:219) [main/:?] |  
  | at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73) [main/:?] |  
  | at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151) [main/:?] |  
  | at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [main/:?] |  
  | at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [main/:?] |  
  | at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) [main/:?] |  
  | at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [main/:?] |  
  | at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [main/:?] |  
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241] |  
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241] |  
  | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
```

Sample build scans:
* https://gradle-enterprise.elastic.co/s/g25empdhtuyzc/tests/:server:internalClusterTest/org.elasticsearch.snapshots.ConcurrentSnapshotsIT/testConcurrentSnapshotWorksWithOldVersionRepo#1
* https://gradle-enterprise.elastic.co/s/njjsq64oksovm/tests/:server:internalClusterTest/org.elasticsearch.snapshots.ConcurrentSnapshotsIT/testConcurrentSnapshotWorksWithOldVersionRepo#1
* https://gradle-enterprise.elastic.co/s/g25empdhtuyzc/tests/:server:internalClusterTest/org.elasticsearch.snapshots.ConcurrentSnapshotsIT/testConcurrentSnapshotWorksWithOldVersionRepo#1

History in the past 7 days: https://gradle-enterprise.elastic.co/scans/tests?list.size=50&list.sortColumn=startTime&list.sortOrder=desc&search.buildToolTypes=gradle&search.buildToolTypes=maven&search.relativeStartTime=P7D&search.timeZoneId=Europe/Bucharest&tests.container=org.elasticsearch.snapshots.ConcurrentSnapshotsIT&tests.sortField=FAILED&tests.test=testConcurrentSnapshotWorksWithOldVersionRepo&tests.unstableOnly=true

**Comment by tlrx** [comment]
Thanks @albertzaharovits but the failing assertion was fixed few hours ago by #63625 and #63642. I checked the commits in the build scans and they do not include the fix.
