### ISSUE TITLE
7.9.0: null_value set in legacy index template for type "ip" causes "java.lang.IllegalArgumentException: Mapper for [host_ip] conflicts with existing mapping"

### ISSUE THREAD

**Issue by jze1** [elastic/elasticsearch#63755]
**Elasticsearch version** (`bin/elasticsearch --version`): Version: 7.9.0, Build: default/rpm/a479a2a7fce0389512d6a9361301708b92dff667/2020-08-11T21:36:48.204330Z, JVM: 11.0.4

**Plugins installed**: []

**JVM version** (`java -version`): openjdk version "11.0.4" 2019-07-16 LTS
OpenJDK Runtime Environment Corretto-11.0.4.11.1 (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.4.11.1 (build 11.0.4+11-LTS, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): Linux 4.1.17-22.30.amzn1.x86_64 #1 SMP Fri Feb 5 23:44:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

I set legacy index template "ldb-dvm-environment" with mapping

         "host_ip":{
            "type":"ip",
            "doc_values":true,
            "null_value":"127.0.0.1"
         }

and when an index is created based on the template this appears in the elasticsearch log:

[ldb-dvm-system-2020.10.08] creating index, cause [auto(bulk api)], templates [ldb-dvm-environment], shards [1]/[0]
Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[ldb-dvm-system-2020.10.08][0]]]).
[ldb-dvm-system-2020.10.08/HndQQ8J9TrGfTNyy_USBNA] update_mapping [_doc]
[ldb-dvm-system-2020.10.08] [[ldb-dvm-system-2020.10.08/HndQQ8J9TrGfTNyy_USBNA]] failed to apply mappings
java.lang.IllegalArgumentException: Mapper for [host_ip] conflicts with existing mapping:
[mapper [host_ip] has different [null_value] values]
        at org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:308) ~[elasticsearch-7.9.0.jar:7.9.0]

Without null_value set in the template this does not happen.

"GET /_mapping" output shows the mapping set in the template in both cases (i.e.

        "host_ip" : {
          "type" : "ip",
          "null_value" : "127.0.0.1"
        },

resp.

        "host_ip" : {
          "type" : "ip"
        },.
)

**Steps to reproduce**:

Not sure what is relevant here but in my tests I did following:

on fresh ELK install

1.)
POST /_template/ldb-dvm-environment
{
   "index_patterns":[
      "ldb-dvm-*"
   ],
   "order":200,
   "settings":{
      "index.refresh_interval":"5s",
      "number_of_shards":1,
      "number_of_replicas":0
   },
   "aliases":{
      "ldb-dvm":{}
   },
   "mappings":{
      "_source":{
         "enabled":true
      },
      "dynamic_templates":[
         {
            "strings":{
               "match":"*",
               "match_mapping_type":"string",
               "mapping":{
                  "type":"text",
                  "fields":{
                     "raw":{
                        "type":"keyword",
                        "ignore_above":256
                     }
                  }
               }
            }
         }
      ],
      "properties":{
         "@timestamp":{
            "type":"date",
            "doc_values":true
         },
         "@version":{
            "type":"keyword"
         },
         "environment":{
            "type":"text",
            "fielddata":true
         },
         "application":{
            "type":"text",
            "fields":{
               "keyword":{
                  "type":"keyword",
                  "ignore_above":256
               }
            }
         },
         "host":{
            "type":"text",
            "fields":{
               "keyword":{
                  "type":"keyword",
                  "ignore_above":256
               }
            }
         },
         "host_ip":{
            "type":"ip",
            "doc_values":true,
            "null_value":"127.0.0.1"
         },
         "type":{
            "type":"text",
            "fields":{
               "keyword":{
                  "type":"keyword",
                  "ignore_above":256
               }
            }
         },
         "type_group":{
            "type":"text",
            "fields":{
               "keyword":{
                  "type":"keyword",
                  "ignore_above":256
               }
            }
         },
         "loglevel":{
            "type":"text",
            "fields":{
               "keyword":{
                  "type":"keyword",
                  "ignore_above":256
               }
            }
         },
         "logmessage":{
            "type":"text",
            "fields":{
               "keyword":{
                  "type":"keyword",
                  "ignore_above":256
               }
            }
         }
      }
   }
}

2.) then logged in the ELK host to create a log entry.

The mentioned error in elasticsearch log appeared.

3.) deleted the index template
4.) created the same legacy index template but without null_value for host_ip
5.) deleted the ldb-dvm-system-* index
6.) then logged in the ELK host

index created but no error in elasticsearch log appeared this time.

This is the elasticsearch output filter of logstash (if it is relevant):

  elasticsearch {
    id => 'out-env_index'
    hosts => [ "http://10.34.194.132:9200" ]
    index => '%{environment}-%{type_group}-%{+YYYY.MM.dd}'
    document_id => "%{[@metadata][document_id]}"
    manage_template => false
  }

I am a complete ELK newbie and the ELK seems to work for me, but this error spamming the log irritates me....

**Comment by romseygeek** [comment]
Hi @jze1, thanks for opening this issue.  Can you paste a complete stack trace of the error from your log?

**Comment by jze1** [comment]
[ldb-dvm-system-2020.10.23] [[ldb-dvm-system-2020.10.23/ozUusy2TTMW2IxZt6riM2Q]] failed to apply mappings
java.lang.IllegalArgumentException: Mapper for [host_ip] conflicts with existing mapping:
[mapper [host_ip] has different [null_value] values]
        at org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:308) ~[elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:50) ~[elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.index.mapper.ObjectMapper.doMerge(ObjectMapper.java:529) ~[elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.index.mapper.RootObjectMapper.doMerge(RootObjectMapper.java:296) ~[elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.index.mapper.ObjectMapper.merge(ObjectMapper.java:489) ~[elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.index.mapper.RootObjectMapper.merge(RootObjectMapper.java:291) ~[elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.index.mapper.Mapping.merge(Mapping.java:99) ~[elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.index.mapper.DocumentMapper.merge(DocumentMapper.java:320) ~[elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:480) ~[elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:427) ~[elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:377) ~[elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.index.mapper.MapperService.updateMapping(MapperService.java:233) [elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.index.IndexService.updateMapping(IndexService.java:631) [elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.updateIndices(IndicesClusterStateService.java:530) [elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:244) [elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$5(ClusterApplierService.java:522) [elasticsearch-7.9.0.jar:7.9.0]
        at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
        at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:519) [elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:490) [elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:437) [elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.access$100(ClusterApplierService.java:74) [elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:177) [elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:651) [elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.9.0.jar:7.9.0]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.9.0.jar:7.9.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by romseygeek** [comment]
Hi @jze1, apologies for talking so long to respond on this.  I can't actually recreate your problem at all on a fresh 7.9.0 install.  One thing I did notice is that the index pattern for your template is missing a trailing `*` so it's possible things aren't being correctly applied (or maybe a different template is being picked up?):

```
{
"index_patterns":[
"ldb-dvm-"          <---- should be ldb-dvm-*
],
```

**Comment by jze1** [comment]
Hello, @romseygeek, There is no other template with host_ip specified in my config. The ldb-dvm- without `*` must be some copy&pasta formatting error, I do have it in the template:

` "ldb-dvm-environment" : {
    "order" : 200,
    "index_patterns" : [
      "ldb-dvm-*"
    ],
    "settings" : {`

But you might be right about "maybe a different template is being picked up?". Will look into it more. Thanks.

**Comment by jze1** [comment]
Nope, I put it into all templates and it is more and more the same.

**Comment by javanna** [comment]
We were not able to reproduce this issue. Please add a comment if you can still recreate it with a recent version and we will reopen the issue.
