### ISSUE TITLE
[CI] ForecastIT.testOverflowToDisk

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#63793]
**Build scan**: https://gradle-enterprise.elastic.co/s/dakbqxzmvfxnm 

**Repro line**: 
```
/gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.ForecastIT.testOverflowToDisk" -Dtests.seed=E001230D5CCE4F9 -Dtests.security.manager=true -Dtests.locale=sr-CS -Dtests.timezone=Pacific/Easter -Druntime.java=8 -Dtests.fips.enabled=true
```
**Reproduces locally?**: No

**Applicable branches**: 7.9 onwards

**Failure history**:

**Failure excerpt**:
```
java.lang.AssertionError: 
Expected: one of {<finished>}
     but: was <scheduled>
	at __randomizedtesting.SeedInfo.seed([E001230D5CCE4F9:41D0AC6ABCB2ED49]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.ml.integration.MlNativeAutodetectIntegTestCase.lambda$waitForecastStatus$1(MlNativeAutodetectIntegTestCase.java:301)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:951)
	at org.elasticsearch.xpack.ml.integration.MlNativeAutodetectIntegTestCase.waitForecastStatus(MlNativeAutodetectIntegTestCase.java:298)
	at org.elasticsearch.xpack.ml.integration.MlNativeAutodetectIntegTestCase.waitForecastToFinish(MlNativeAutodetectIntegTestCase.java:292)
	at org.elasticsearch.xpack.ml.integration.ForecastIT.testOverflowToDisk(ForecastIT.java:244)
```

**Comment by ywangd** [comment]
Another one with 7.x: https://gradle-enterprise.elastic.co/s/gpojhbkhxysfs
Not reproducible locally.

The failures are [all from the fips jobs](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(build.job-name),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testOverflowToDisk),sort:!(process.time-start,desc))). Not sure if that means something or just coincidence.

**Comment by droberts195** [comment]
> The failures are [all from the fips jobs](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(build.job-name),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testOverflowToDisk),sort:!(process.time-start,desc))). Not sure if that means something or just coincidence.

I think it probably means that the test runs a bit slower in fips jobs than non-fips.  Looking at the relevant bit of the server side log for the first failure, the forecast took 32 seconds:

```
[2020-10-16T07:42:07,989][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [integTest-1] [forecast-it-test-overflow-to-disk] [autodetect/354739] [CForecastRunner.cc@124] Start forecasting from 2020-10-16T05:00:00+0000 to 2020-10-16T06:00:00+0000
[2020-10-16T07:42:39,587][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [integTest-1] [forecast-it-test-overflow-to-disk] [autodetect/354739] [CForecastRunner.cc@217] Finished forecasting, wrote 8000 records
```

But the test requires that it completes in 30 seconds: https://github.com/elastic/elasticsearch/blob/51d0bcacdf0c2daf47ae1f17574e1884304a8271/x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/MlNativeAutodetectIntegTestCase.java#L302

Similar story for the second failure: the forecast took 39 seconds:

```
[2020-10-30T03:43:21,440][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [javaRestTest-1] [forecast-it-test-overflow-to-disk] [autodetect/472440] [CForecastRunner.cc@124] Start forecasting from 2020-10-30T01:00:00+0000 to 2020-10-30T02:00:00+0000
[2020-10-30T03:43:54,764][DEBUG][o.e.c.c.PublicationTransportHandler] [javaRestTest-1] received diff cluster state version [4419] with uuid [f9iHqlSbSnqH4LC-hn1c3Q], diff size [423]
[2020-10-30T03:43:54,842][DEBUG][o.e.c.c.C.CoordinatorPublication] [javaRestTest-1] publication ended successfully: Publication{term=3, version=4419}
[2020-10-30T03:43:54,842][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [javaRestTest-1] Closing job [forecast-it-test-overflow-to-disk], because [close job (api)]
[2020-10-30T03:43:54,843][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [javaRestTest-1] [forecast-it-test-overflow-to-disk] [autodetect/472440] [CCmdSkeleton.cc@51] Handled 120000 records
[2020-10-30T03:43:54,877][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [javaRestTest-1] [forecast-it-test-overflow-to-disk] [autodetect/472440] [CAnomalyJob.cc@1560] Pruning all models
[2020-10-30T03:44:00,803][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [javaRestTest-1] [forecast-it-test-overflow-to-disk] [autodetect/472440] [CForecastRunner.cc@217] Finished forecasting, wrote 8000 records
```

I will bump the timeout to 60 seconds.

**Comment by javanna** [comment]
I just stumbled upon this same failure today: https://gradle-enterprise.elastic.co/s/ekxjxyoy7r4tc/console-log?task=:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest .

**Comment by droberts195** [comment]
> I just stumbled upon this same failure today

It's happening in the FIPS JVM, like in https://github.com/elastic/elasticsearch/issues/58806#issuecomment-762931901.

I will alter the test to wait _much_ longer for the forecast to complete in the FIPS JVM.
