### ISSUE TITLE
AggregationsTests.testFromXContentWithRandomFields reproducible failure

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#63925]
This test failed on a PR but it seems it has started today.

**Build scan**:

https://gradle-enterprise.elastic.co/s/drlszluma2dvc (different to the report failure)

**Repro line**:

```
./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.AggregationsTests.testFromXContentWithRandomFields" -Dtests.seed=413BAB3F569B03D6 -Dtests.security.manager=true -Dtests.locale=es-DO -Dtests.timezone=Asia/Kabul -Druntime.java=11
```

**Reproduces locally?**:

yes

**Applicable branches**:

Only tried in master

**Failure history**:

It seems this test start failing today

**Failure excerpt**:

```
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.AggregationsTests.testFromXContentWithRandomFields" -Dtests.seed=413BAB3F569B03D6 -Dtests.security.manager=true -Dtests.locale=es-DO -Dtests.timezone=Asia/Kabul -Druntime.java=11
  2> java.lang.IllegalStateException: aggregation was not reduced
        at __randomizedtesting.SeedInfo.seed([413BAB3F569B03D6:432E867E0D5C8B03]:0)
        at org.elasticsearch.search.aggregations.metrics.InternalScriptedMetric.aggregation(InternalScriptedMetric.java:91)
        at org.elasticsearch.search.aggregations.metrics.InternalScriptedMetric.doXContentBody(InternalScriptedMetric.java:151)
        at org.elasticsearch.search.aggregations.InternalAggregation.toXContent(InternalAggregation.java:299)
        at org.elasticsearch.search.aggregations.Aggregations.toXContentInternal(Aggregations.java:130)
        at org.elasticsearch.search.aggregations.bucket.InternalSingleBucketAggregation.doXContentBody(InternalSingleBucketAggregation.java:160)
        at org.elasticsearch.search.aggregations.InternalAggregation.toXContent(InternalAggregation.java:299)
        at org.elasticsearch.search.aggregations.Aggregations.toXContentInternal(Aggregations.java:130)
        at org.elasticsearch.search.aggregations.bucket.terms.InternalSignificantTerms$Bucket.toXContent(InternalSignificantTerms.java:157)
        at org.elasticsearch.search.aggregations.bucket.terms.InternalMappedSignificantTerms.doXContentBody(InternalMappedSignificantTerms.java:139)
        at org.elasticsearch.search.aggregations.InternalAggregation.toXContent(InternalAggregation.java:299)
        at org.elasticsearch.search.aggregations.Aggregations.toXContentInternal(Aggregations.java:130)

```

**Comment by DaveCTurner** [comment]
Also https://gradle-enterprise.elastic.co/s/drlszluma2dvc for a similar-looking failure (of a slightly different test) on master, which also reproduces for me.

`2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.AggregationsTests.testFromXContent" -Dtests.seed=40BB346BC1056C42 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:-UseSerialGC -XX:+UseG1GC" -Dtests.locale=lv-LV -Dtests.timezone=Europe/Moscow -Druntime.java=11`

**Comment by nik9000** [comment]
Sorry about this! I'm sure I must have broken this in #63821.

**Comment by nik9000** [comment]
I lucked into not hitting this error when I first wrote the new tests but the backport bumped into it!
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/10574/testReport/junit/org.elasticsearch.action.search/SearchResponseTests/testFromXContentWithFailures/
