### ISSUE TITLE
[CI] TasksIT testGetValidTask failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#64056]
**Build scan**: https://gradle-enterprise.elastic.co/s/m4ri3qe5dslwk

**Repro line**: `./gradlew ':client:rest-high-level:asyncIntegTestRunner' --tests "org.elasticsearch.client.TasksIT.testGetValidTask" -Dtests.seed=811D7AD2556E9BC7 -Dtests.security.manager=true -Dtests.locale=zh-CN -Dtests.timezone=Jamaica -Druntime.java=8` 

**Reproduces locally?**: No

**Applicable branches**: 7.9

**Failure history**: [it failed in the past but the errors were different then and maybe not all of them strictly related to this method](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.client.TasksIT%22%20AND%20test:%22testGetValidTask%22'),sort:!(time,desc)))

**Failure excerpt**:
```
org.elasticsearch.client.TasksIT > testGetValidTask FAILED
    org.elasticsearch.client.ResponseException: method [GET], host [http://127.0.0.1:42117], URI [/_tasks/B7ZED5VwT_i5O_wdl3eN9A:57079], status line [HTTP/1.1 404 Not Found]
    {"error":{"root_cause":[{"type":"resource_not_found_exception","reason":"task [B7ZED5VwT_i5O_wdl3eN9A:57079] isn't running and hasn't stored its results"}],"type":"resource_not_found_exception","reason":"task [B7ZED5VwT_i5O_wdl3eN9A:57079] isn't running and hasn't stored its results"},"status":404}
        at __randomizedtesting.SeedInfo.seed([811D7AD2556E9BC7:8155551EC6C3380C]:0)
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:302)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:272)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246)
        at org.elasticsearch.client.ReindexIT.lambda$checkCompletionStatus$0(ReindexIT.java:504)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:939)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:924)
        at org.elasticsearch.client.TasksIT.testGetValidTask(TasksIT.java:124)
```

**Comment by tlrx** [comment]
I opened #64724 that fixes the exact failure with `resource_not_found_exception`. In case this test fails again with a different failure please open a new issue.
