### ISSUE TITLE
SearchableSnapshotDirectoryTests testClearCache Failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#64136]
**Build scan**:
https://gradle-enterprise.elastic.co/s/g3apnwvkbbras
https://gradle-enterprise.elastic.co/s/oaodysf3koblg
https://gradle-enterprise.elastic.co/s/wa6guclg3dte4
https://gradle-enterprise.elastic.co/s/wuo3txzapb4oy

**Repro line**:
./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.index.store.SearchableSnapshotDirectoryTests.testClearCache" \
  -Dtests.seed=E63F8863CFDFE13C \
  -Dtests.security.manager=true \
  -Dtests.locale=sv-SE \
  -Dtests.timezone=Asia/Urumqi \
  -Druntime.java=8

**Reproduces locally?**:
No

**Applicable branches**:
master, 7.x

**Failure history**:
Multiple failures since 23/10/2020

**Failure excerpt**:
```
Expected: <0>	
     but: was <1>	
at __randomizedtesting.SeedInfo.seed([E63F8863CFDFE13C:28E0B2AF4D4CAE7C]:0)	
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)	
at org.junit.Assert.assertThat(Assert.java:956)	
at org.elasticsearch.index.store.SearchableSnapshotDirectoryTests.assertListOfFiles(SearchableSnapshotDirectoryTests.java:903)	
at org.elasticsearch.index.store.SearchableSnapshotDirectoryTests.testClearCache(SearchableSnapshotDirectoryTests.java:743)
```

**Comment by original-brownbear** [comment]
This was already fixed in https://github.com/elastic/elasticsearch/pull/64100 concurrently
