### ISSUE TITLE
SearchableSnapshotDirectoryTests cleanup failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#64141]
**Build scan**:
https://gradle-enterprise.elastic.co/s/wccywnq4vwa7i
https://gradle-enterprise.elastic.co/s/ape5azhubsr52
https://gradle-enterprise.elastic.co/s/6gi3bcwslc55a

**Repro line**:
./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.index.store.SearchableSnapshotDirectoryTests" \
  -Dtests.seed=85356C2FA0D407CA \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=UTC \
  -Druntime.java=11

**Reproduces locally?**:
No

**Applicable branches**:
master

**Failure history**:
The first instance I found occurred on 2020/10/23: https://gradle-enterprise.elastic.co/s/wccywnq4vwa7i and has failed a few times a day since then

**Failure excerpt**:
```
org.elasticsearch.index.store.SearchableSnapshotDirectoryTests > classMethod FAILED	
    java.lang.RuntimeException: file handle leaks: [FileChannel(/dev/shm/elastic+elasticsearch+master+matrix-java-periodic/ES_RUNTIME_JAVA/zulu11/nodes/general-purpose/x-pack/plugin/searchable-snapshots/build/testrun/test/temp/org.elasticsearch.index.store.SearchableSnapshotDirectoryTests_FB612E55208182B1-001/tempDir-006/o-O-R6uyRo61-coLL-lfIg), FileChannel(/dev/shm/elastic+elasticsearch+master+matrix-java-periodic/ES_RUNTIME_JAVA/zulu11/nodes/general-purpose/x-pack/plugin/searchable-snapshots/build/testrun/test/temp/org.elasticsearch.index.store.SearchableSnapshotDirectoryTests_FB612E55208182B1-001/tempDir-006/w_KdLYSbS8yoongvCVx9Eg)]	
        at __randomizedtesting.SeedInfo.seed([FB612E55208182B1]:0)	
        at org.apache.lucene.mockfile.LeakFS.onClose(LeakFS.java:63)	
        at org.apache.lucene.mockfile.FilterFileSystem.close(FilterFileSystem.java:77)	
        at org.apache.lucene.mockfile.FilterFileSystem.close(FilterFileSystem.java:78)	
        at org.apache.lucene.mockfile.FilterFileSystem.close(FilterFileSystem.java:78)	
        at org.apache.lucene.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:228)	
        at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)	
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)	
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)	
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)	
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)	
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)	
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)	
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)	
        at java.base/java.lang.Thread.run(Thread.java:834)	
        Caused by:	
        java.lang.Exception	
            at org.apache.lucene.mockfile.LeakFS.onOpen(LeakFS.java:46)	
            at org.apache.lucene.mockfile.HandleTrackingFS.callOpenHook(HandleTrackingFS.java:81)	
            at org.apache.lucene.mockfile.HandleTrackingFS.newFileChannel(HandleTrackingFS.java:197)	
            at org.apache.lucene.mockfile.HandleTrackingFS.newFileChannel(HandleTrackingFS.java:166)	
            at org.apache.lucene.mockfile.FilterFileSystemProvider.newFileChannel(FilterFileSystemProvider.java:202)	
            at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)	
            at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)	
            at org.elasticsearch.index.store.cache.CacheFile$FileChannelReference.<init>(CacheFile.java:87)	
            at org.elasticsearch.index.store.cache.CacheFile.acquire(CacheFile.java:144)	
            at org.elasticsearch.index.store.cache.CachedBlobContainerIndexInput$CacheFileReference.get(CachedBlobContainerIndexInput.java:791)	
            at org.elasticsearch.index.store.cache.CachedBlobContainerIndexInput.getCacheFileSafe(CachedBlobContainerIndexInput.java:139)	
            at org.elasticsearch.index.store.cache.CachedBlobContainerIndexInput.prefetchPart(CachedBlobContainerIndexInput.java:450)	
            at org.elasticsearch.index.store.SearchableSnapshotDirectory.lambda$prewarmCache$11(SearchableSnapshotDirectory.java:460)	
            at org.elasticsearch.action.ActionRunnable$1.doRun(ActionRunnable.java:45)	
            at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:733)	
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)	
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)	
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)	
            ... 1 more

```

**Comment by original-brownbear** [comment]
This specific failure is already fixed by https://github.com/elastic/elasticsearch/pull/64100 but I'll leave this one open since we have a very similar failure still that's fixed by the not yet merged https://github.com/elastic/elasticsearch/pull/64180
