### ISSUE TITLE
BulkProcessor threads in waiting state

### ISSUE THREAD

**Issue by maxio89** [elastic/elasticsearch#64161]
After upgrading to 7.9.x versions (including the latest one 9.7.3) we can see increasing number of threads in waiting state while adding items to BulkProcessor.
```
priority:5 - threadId:0x00007fe6ec0f1b70 - nativeId:0x154 - nativeId (decimal):340 - state:WAITING
stackTrace:
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00000007314aa6c0> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
at org.elasticsearch.action.bulk.BulkProcessor.internalAdd(BulkProcessor.java:379)
at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:361)
at org.elasticsearch.action.bulk.BulkProcessor.add(BulkProcessor.java:347)
```

Everything works fine in 7.7.1 version.

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
