### ISSUE TITLE
[CI] CcrRepositoryIT.testCcrRepositoryFetchesSnapshotShardSizeFromIndexShardStoreStats

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#64167]
**Build scan**:
[https://gradle-enterprise.elastic.co/s/ys4oqzz22q5j4](https://gradle-enterprise.elastic.co/s/ys4oqzz22q5j4)

**Repro line**:

> ./gradlew ':x-pack:plugin:ccr:internalClusterTest' --tests "org.elasticsearch.xpack.ccr.CcrRepositoryIT.testCcrRepositoryFetchesSnapshotShardSizeFromIndexShardStoreStats" -Dtests.seed=3E1F56A97DF16F81 -Dtests.security.manager=true -Dtests.locale=bg -Dtests.timezone=Etc/GMT-6 -Druntime.java=8

**Reproduces locally?**:
Haven't tried yet.

**Applicable branches**:
master and 7.x

**Failure history**:
[Failed 4 times last week](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'test:%22testCcrRepositoryFetchesSnapshotShardSizeFromIndexShardStoreStats%22'),sort:!(time,desc)))

**Failure excerpt**:
```
java.lang.AssertionError: 
Expected: <9533L>
     but: was null
	at __randomizedtesting.SeedInfo.seed([3E1F56A97DF16F81:3800E1220BE5AB1C]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.ccr.CcrRepositoryIT.lambda$testCcrRepositoryFetchesSnapshotShardSizeFromIndexShardStoreStats$9(CcrRepositoryIT.java:564)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:999)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:972)
	at org.elasticsearch.xpack.ccr.CcrRepositoryIT.testCcrRepositoryFetchesSnapshotShardSizeFromIndexShardStoreStats(CcrRepositoryIT.java:560)
```

**Comment by danhermann** [comment]
Looks like this is failing again here: https://gradle-enterprise.elastic.co/s/omebnvaesa5sm

**Comment by davidkyle** [comment]
Reopening this issue with a new failure: https://gradle-enterprise.elastic.co/s/kdj3bgnfwrceg/console-log?task=:x-pack:plugin:ccr:internalClusterTest


```
 java.lang.AssertionError: Snapshot shard size fetched for follower shard [2] does not match leader store size
Expected: <6693L>
     but: was <3536L>
	at __randomizedtesting.SeedInfo.seed([4E56F8C0D5CD4261:48494F4BA3D986FC]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.xpack.ccr.CcrRepositoryIT.testCcrRepositoryFetchesSnapshotShardSizeFromIndexShardStoreStats(CcrRepositoryIT.java:571)
```

Build stats shows that there has been a few failures recently: https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testCcrRepositoryFetchesSnapshotShardSizeFromIndexShardStoreStats),sort:!(time,desc))

**Comment by pugnascotia** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/avbzze6kcasbc/console-log?task=:x-pack:plugin:ccr:internalClusterTest

**Comment by gwbrown** [comment]
Another one: https://gradle-enterprise.elastic.co/s/ahg5ocrpsshrs.

Worth noting that the last couple weeks it appears there have only been failures on `master` and `7.10`.
