### ISSUE TITLE
Reproducible failure in RareTermsAggregatorTests

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#64356]
Found by CI on an unrelated pull request

**Build scan**:
https://gradle-enterprise.elastic.co/s/wj26schfjwofg/console-log?task=:server:test

**Repro line**:
```
./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.terms.RareTermsAggregatorTests.testNestedTerms" -Dtests.seed=EDABA787C024041A -Dtests.security.manager=true -Dtests.locale=id -Dtests.timezone=Europe/Zurich -Druntime.java=11
```

**Reproduces locally?**: Yes

**Applicable branches**: master

**Failure history**: 
Nothing found in gradle enterprise

**Failure excerpt**:
```
org.elasticsearch.search.aggregations.bucket.terms.RareTermsAggregatorTests > testNestedTerms FAILED |  
-- | --
  | java.lang.AssertionError: segment should have at least one document to replay, got 0 |  
  | at __randomizedtesting.SeedInfo.seed([EDABA787C024041A:37E876EF4248F7B6]:0) |  
  | at org.elasticsearch.search.aggregations.bucket.BestBucketsDeferringCollector.prepareSelectedBuckets(BestBucketsDeferringCollector.java:162) |  
  | at org.elasticsearch.search.aggregations.bucket.DeferableBucketAggregator.prepareSubAggs(DeferableBucketAggregator.java:96) |  
  | at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildSubAggsForBuckets(BucketsAggregator.java:189) |  
  | at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildSubAggsForAllBuckets(BucketsAggregator.java:255) |  
  | at org.elasticsearch.search.aggregations.bucket.terms.StringRareTermsAggregator.buildAggregations(StringRareTermsAggregator.java:171) |  
  | at org.elasticsearch.search.aggregations.Aggregator.buildTopLevel(Aggregator.java:154) |  
  | at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:430) |  
  | at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:367) |  
  | at org.elasticsearch.search.aggregations.bucket.terms.RareTermsAggregatorTests.executeTestCase(RareTermsAggregatorTests.java:581) |  
  | at org.elasticsearch.search.aggregations.bucket.terms.RareTermsAggregatorTests.testSearchCase(RareTermsAggregatorTests.java:552) |  
  | at org.elasticsearch.search.aggregations.bucket.terms.RareTermsAggregatorTests.testNestedTerms(RareTermsAggregatorTests.java:333)
```

**Comment by nik9000** [comment]
Sounds like something I caused. I'll have a look soon.

**Comment by nik9000** [comment]
I'm not sure I caused this, but I believe I've tracked it down. I'll make a PR.

**Comment by nik9000** [comment]
Oh yeah, I broke this yesterday. Explanation in PR.

**Comment by jtibshirani** [comment]
Another instance just popped up in CI: https://gradle-enterprise.elastic.co/s/dejnmsrxyylnq. Depending on how long the PR takes to review + merge, we could mute the test immediately ?

**Comment by nik9000** [comment]
> we could mute the test immediately ?

I'm working through checkstyle now. So I'll have it open pretty soon. I'm not sure how long to review. It isn't super big.

**Comment by nik9000** [comment]
Sorry for fixing this in master, closing the issue, and then not opening the backport over night.

**Comment by nik9000** [comment]
All backported.
