### ISSUE TITLE
RareTermsAggregatorTests.testEmbeddedMaxAgg failure

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#64383]
**Build scan**:
https://gradle-enterprise.elastic.co/s/bkg3w5d7oitbk/console-log?task=:server:test

**Repro line**:
./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.terms.RareTermsAggregatorTests.testEmbeddedMaxAgg" -Dtests.seed=5830685F688FB61B -Dtests.security.manager=true -Dtests.locale=en-AU -Dtests.timezone=Chile/EasterIsland -Druntime.java=11

**Reproduces locally?**: No

**Applicable branches**: Master

**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now%2Fd,mode:quick,to:now%2Fd))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:RareTermsAggregatorTests),sort:!(process.time-start,desc))

**Failure excerpt**:
```
org.elasticsearch.search.aggregations.bucket.terms.RareTermsAggregatorTests > testEmbeddedMaxAgg FAILED |  
-- | --
  | java.lang.AssertionError: segment should have at least one document to replay, got 0 |  
  | at __randomizedtesting.SeedInfo.seed([5830685F688FB61B:5AC68FE04B4FB032]:0) |  
  | at org.elasticsearch.search.aggregations.bucket.BestBucketsDeferringCollector.prepareSelectedBuckets(BestBucketsDeferringCollector.java:162) |  
  | at org.elasticsearch.search.aggregations.bucket.DeferableBucketAggregator.prepareSubAggs(DeferableBucketAggregator.java:96) |  
  | at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildSubAggsForBuckets(BucketsAggregator.java:189) |  
  | at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildSubAggsForAllBuckets(BucketsAggregator.java:255) |  
  | at org.elasticsearch.search.aggregations.bucket.terms.LongRareTermsAggregator.buildAggregations(LongRareTermsAggregator.java:165) |  
  | at org.elasticsearch.search.aggregations.Aggregator.buildTopLevel(Aggregator.java:154) |  
  | at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:430) |  
  | at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:367) |  
  | at org.elasticsearch.search.aggregations.bucket.terms.RareTermsAggregatorTests.executeTestCase(RareTermsAggregatorTests.java:581) |  
  | at org.elasticsearch.search.aggregations.bucket.terms.RareTermsAggregatorTests.testSearchCase(RareTermsAggregatorTests.java:552) |  
  | at org.elasticsearch.search.aggregations.bucket.terms.RareTermsAggregatorTests.testEmbeddedMaxAgg(RareTermsAggregatorTests.java:197)
```

**Comment by rjernst** [comment]
Already handled in https://github.com/elastic/elasticsearch/issues/64356

**Comment by ywangd** [comment]
Failure still happens on 7.x: https://gradle-enterprise.elastic.co/s/ywuksrllpmfie

I believe backports are needed for #64366. Re-openning this issue so it is tracked.
