### ISSUE TITLE
the field response in org.elasticsearch.client.ResponseException should implement Serializable

### ISSUE THREAD

**Issue by duguyin** [elastic/elasticsearch#64518]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.1.0

**Plugins installed**: []

**JVM version** (`java -version`):  1.8.0_171-b11

**OS version** (`uname -a` if on a Unix-like system):  ubuntu 18.04

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.  I use apache dubbo framework for invoke api which implemented by spring data elasticsearchRestTemplte;
 2.  when a exception was throwed,  the elastic exception can not be serialize; the reason for it is dubbo framework must transport a serializable class
 3.  

**Provide logs (if relevant)**:
Caused by: java.lang.RuntimeException: Serialized **class org.elasticsearch.client.Response must implement java.io.Serializable**
 Java field: private final org.elasticsearch.client.Response org.elasticsearch.client.ResponseException.response
 Java field: private java.util.List java.lang.Throwable.suppressedExceptions
 Java field: private java.lang.Throwable java.lang.Throwable.cause
	at com.alibaba.com.caucho.hessian.io.JavaSerializer$FieldSerializer.serialize(JavaSerializer.java:304) ~[dubbo-2.7.8.jar:2.7.8]
	at com.alibaba.com.caucho.hessian.io.JavaSerializer.writeInstance(JavaSerializer.java:284) ~[dubbo-2.7.8.jar:2.7.8]
	at com.alibaba.com.caucho.hessian.io.JavaSerializer.writeObject(JavaSerializer.java:251) ~[dubbo-2.7.8.jar:2.7.8]
	at com.alibaba.com.caucho.hessian.io.ThrowableSerializer.writeObject(ThrowableSerializer.java:68) ~[dubbo-2.7.8.jar:2.7.8]
	at com.alibaba.com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:412) ~[dubbo-2.7.8.jar:2.7.8]
	at com.alibaba.com.caucho.hessian.io.JavaSerializer$FieldSerializer.serialize(JavaSerializer.java:302) ~[dubbo-2.7.8.jar:2.7.8]
	... 34 common frames omitted

**Comment by imotov** [comment]
Elasticsearch is not using standard java serialization for several reasons and we don't have any plans to support it in the future. I would suggest to switch to using officially supported elasticsearch java client or open this issue with dubbo framework or spring data to switch to an alternative serialization method of elasticsearch classes.

**Comment by imotov** [comment]
Since there are no comments on this one, I am going to close it. @duguyin please feel free to reopen if I misunderstood your requests. If you have any other questions, please don't hesitate to use our [discussion forum](https://discuss.elastic.co/).
