### ISSUE TITLE
[CI] Failure in BwC Test org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.test {p0=mixed_cluster/20_date_range/Insert more docs to java index}

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#64577]
```
./gradlew ':qa:rolling-upgrade:v7.9.2#twoThirdsUpgradedTest' --tests "org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.test {p0=mixed_cluster/20_date_range/Insert more docs to java index}" -Dtests.seed=BDF3E85905AADFEC -Dtests.security.manager=true -Dtests.locale=hu-HU -Dtests.timezone=NZ-CHAT -Dtests.distribution=default -Druntime.java=8 -Dtests.rest.suite=mixed_cluster
```

failed in  https://gradle-enterprise.elastic.co/s/4rkksji6ukvck/console-log/raw due to

```
  2> REPRODUCE WITH: ./gradlew ':qa:rolling-upgrade:v7.9.2#twoThirdsUpgradedTest' --tests "org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.test {p0=mixed_cluster/20_date_range/Insert more docs to java index}" -Dtests.seed=BDF3E85905AADFEC -Dtests.security.manager=true -Dtests.locale=hu-HU -Dtests.timezone=NZ-CHAT -Dtests.distribution=default -Druntime.java=8 -Dtests.rest.suite=mixed_cluster
  2> org.elasticsearch.client.ResponseException: method [DELETE], host [http://127.0.0.1:38527], URI [_data_stream/*?expand_wildcards=all], status line [HTTP/1.1 400 Bad Request]
    {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [_data_stream/*] contains unrecognized parameter: [expand_wildcards]"}],"type":"illegal_argument_exception","reason":"request [_data_stream/*] contains unrecognized parameter: [expand_wildcards]"},"status":400}
        at __randomizedtesting.SeedInfo.seed([BDF3E85905AADFEC:35A7D783AB56B214]:0)
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:318)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:262)
        at org.elasticsearch.test.rest.ESRestTestCase.wipeDataStreams(ESRestTestCase.java:709)
        at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:585)
        at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:340)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.lang.Thread.run(Thread.java:748)
```

Does not reproduce locally but looks like the wipe cluster logic is not correctly handling BwC for wiping data streams with a 7.9 master in this test.

**Comment by csoulios** [comment]
Can this be related to the failures I am getting for PR #64594 against 7.x?

I am also receiving 

```
21:40:44 org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT > test {p0=mixed_cluster/10_basic/Verify custom cluster metadata still exists during upgrade} FAILED
21:40:44     org.elasticsearch.client.ResponseException: method [DELETE], host [http://127.0.0.1:45427], URI [_data_stream/*?expand_wildcards=all], status line [HTTP/1.1 400 Bad Request]
21:40:44     {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [_data_stream/*] contains unrecognized parameter: [expand_wildcards]"}],"type":"illegal_argument_exception","reason":"request [_data_stream/*] contains unrecognized parameter: [expand_wildcards]"},"status":400}
21:40:44         at __randomizedtesting.SeedInfo.seed([B14966AB2AE645E7:391D5971841A281F]:0)
21:40:44         at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:318)
21:40:44         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
21:40:44         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:262)
21:40:44         at org.elasticsearch.test.rest.ESRestTestCase.wipeDataStreams(ESRestTestCase.java:709)
21:40:44         at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:585)
21:40:44         at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:340)
21:40:44         at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
21:40:44         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:40:44         at java.lang.reflect.Method.invoke(Method.java:498)
21:40:44         at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
21:40:44         at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
21:40:44         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
21:40:44         at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
21:40:44         at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
21:40:44         at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
21:40:44         at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
21:40:44         at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
21:40:44         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
21:40:44         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
21:40:44         at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
21:40:44         at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
21:40:44         at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
21:40:44         at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
21:40:44         at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
21:40:44         at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
21:40:44         at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
21:40:44         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
21:40:44         at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
21:40:44         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
21:40:44         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
21:40:44         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
21:40:44         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
21:40:44         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
21:40:44         at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
21:40:44         at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
21:40:44         at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
21:40:44         at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
21:40:44         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
21:40:44         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
21:40:44         at java.lang.Thread.run(Thread.java:748)
21:40:44 REPRODUCE WITH: ./gradlew ':qa:rolling-upgrade:v7.9.4#twoThirdsUpgradedTest' --tests "org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.test {p0=mixed_cluster/10_basic/Verify custom cluster metadata still exists during upgrade}" -Dtests.seed=B14966AB2AE645E7 -Dtests.security.manager=true -Dtests.locale=tr-TR -Dtests.timezone=America/Argentina/Mendoza -Dtests.distribution=default -Druntime.java=8 -Dtests.rest.suite=mixed_cluster
21:40:44 
```





https://gradle-enterprise.elastic.co/s/sopko2m4u3bpg#tests

**Comment by imotov** [comment]
I did some additional digging and the very first time when it failed, it was in PR build for #63987. There are many tests that fail periodically with this error message. There were 140 failures in the last 3 days. I wonder if @probakowski could also take a look since it is affecting multiple seemingly unrelated tests that would be impractical to mute.

**Comment by probakowski** [comment]
Yep, it was me messing up the backport, I've created #64674 to fix it

**Comment by probakowski** [comment]
I'll close it now as #64674 is merged, please reopen if that pops up again
