### ISSUE TITLE
[CI] ArchiveTests - Fail to obtain node lock on Ubuntu 20 - test93ElasticsearchNodeCustomDataPathAndNotEsHomeWorkDir 

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#64683]
**Build scan**:
- *(Nov 3)* https://gradle-enterprise.elastic.co/s/ik6gx7vh6l3qs/tests/:qa:os:destructiveDistroTest.default-linux-archive/org.elasticsearch.packaging.test.ArchiveTests/test93ElasticsearchNodeCustomDataPathAndNotEsHomeWorkDir#1
- *(Nov 6)* https://gradle-enterprise.elastic.co/s/4l2oscn7jzku2/tests/:qa:os:destructiveDistroTest.default-linux-archive/org.elasticsearch.packaging.test.ArchiveTests/test93ElasticsearchNodeCustomDataPathAndNotEsHomeWorkDir#1

**Repro line**:
N/A (only fails on 1 O/S)

**Reproduces locally?**:
N/A (only fails on 1 O/S)

**Applicable branches**:
master ([all other branches seem OK](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(build.branch,process.status,sys.os,sys.os-version),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b646ed00-7efc-11e8-bf69-63c8ef516157,key:build.project,negate:!f,params:(query:elasticsearch,type:phrase),type:phrase,value:elasticsearch),query:(match:(build.project:(query:elasticsearch,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b646ed00-7efc-11e8-bf69-63c8ef516157,key:sys.os-version,negate:!f,params:(query:'20.04.1%20LTS',type:phrase),type:phrase,value:'20.04.1%20LTS'),query:(match:(sys.os-version:(query:'20.04.1%20LTS',type:phrase))))),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:%22packaging-tests-unix-gcp%22),sort:!(process.time-start,desc))))

**Failure history**:
- [Build Stats - Failures](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(sys.kernel-name,build.branch,build.build-scans,sys.os-version),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b646ed00-7efc-11e8-bf69-63c8ef516157,key:build.project,negate:!f,params:(query:elasticsearch,type:phrase),type:phrase,value:elasticsearch),query:(match:(build.project:(query:elasticsearch,type:phrase))))),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:%22test93ElasticsearchNodeCustomDataPathAndNotEsHomeWorkDir%22),sort:!(process.time-start,desc)))
- [Build Stats - All Jobs](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(process.status,sys.os,sys.os-version),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b646ed00-7efc-11e8-bf69-63c8ef516157,key:build.project,negate:!f,params:(query:elasticsearch,type:phrase),type:phrase,value:elasticsearch),query:(match:(build.project:(query:elasticsearch,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b646ed00-7efc-11e8-bf69-63c8ef516157,key:build.branch,negate:!f,params:(query:master,type:phrase),type:phrase,value:master),query:(match:(build.branch:(query:master,type:phrase))))),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:%22elastic%2Belasticsearch%2Bmaster%2Bmultijob%2Bpackaging-tests-unix%22),sort:!(process.time-start,desc)))

It looks to be failing on Ubuntu 20 and Fedora 32, but working elsewhere.
The Fedora 32 failures seem to be due to #64569, but I think the Ubuntu 20 issues is something different.
 
**Failure excerpt**:
```
org.elasticsearch.packaging.test.ArchiveTests > test93ElasticsearchNodeCustomDataPathAndNotEsHomeWorkDir FAILED	
    org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c echo y | /tmp/elasticsearch/bin/elasticsearch-node unsafe-bootstrap]	
       result: exitCode = [1] stdout = [------------------------------------------------------------------------	
	
        WARNING: Elasticsearch MUST be stopped before running this tool.] stderr = [Exception in thread "main" java.io.IOException: failed to obtain lock on /tmp	
    	at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:222)	
    	at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:192)	
    	at org.elasticsearch.cluster.coordination.ElasticsearchNodeCommand.processNodePaths(ElasticsearchNodeCommand.java:144)	
    	at org.elasticsearch.cluster.coordination.ElasticsearchNodeCommand.execute(ElasticsearchNodeCommand.java:168)	
    	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)	
    	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)	
    	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)	
    	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)	
    	at org.elasticsearch.cli.Command.main(Command.java:90)	
    	at org.elasticsearch.cluster.coordination.NodeToolCli.main(NodeToolCli.java:49)	
    Caused by: java.nio.file.AccessDeniedException: /tmp/node.lock	
    	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)	
    	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)	
    	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)	
    	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:181)	
    	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)	
    	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)	
    	at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:125)	
    	at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41)	
    	at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45)	
    	at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:215)	
    	... 9 more]	
        at __randomizedtesting.SeedInfo.seed([A07CFE26DB716C02:AE81F0553DD0A3D6]:0)	
        at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:158)	
        at org.elasticsearch.packaging.util.Shell.run(Shell.java:84)	
        at org.elasticsearch.packaging.test.ArchiveTests.test93ElasticsearchNodeCustomDataPathAndNotEsHomeWorkDir(ArchiveTests.java:395)	
```

**Comment by mark-vieira** [comment]
I'm not seeing a reoccurrence of this within the last month so I suspect it's resolved. We can reopen if it crops up again.
