### ISSUE TITLE
[CI] Failure in SharedClusterSnapshotRestoreIT. testSnapshotCanceledOnRemovedShard

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#64785]
**Build scan**: https://gradle-enterprise.elastic.co/s/pekmzo5khpp5u

**Repro line**: ```./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.testSnapshotCanceledOnRemovedShard" -Dtests.seed=349DB1893B939A53 -Dtests.security.manager=true -Dtests.locale=fr-CA -Dtests.timezone=Africa/Lome -Druntime.java=11```

**Reproduces locally?**: No

**Applicable branches**: master

**Failure history**: Failed 3 times in the past 2 months.

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testSnapshotCanceledOnRemovedShard),sort:!(process.time-start,desc))

**Failure excerpt**:

```
org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT > testSnapshotCanceledOnRemovedShard FAILED
    org.elasticsearch.snapshots.SnapshotMissingException: [test-repo:test-snap] is missing
        at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.loadSnapshotInfos(TransportGetSnapshotsAction.java:188)
        at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.lambda$getSingleRepoSnapshotInfo$3(TransportGetSnapshotsAction.java:144)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
        at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:112)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:176)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:106)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:98)
        at java.util.ArrayList.forEach(ArrayList.java:1540)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:98)
        at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:144)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:127)
        at org.elasticsearch.action.StepListener.innerOnResponse(StepListener.java:62)
        at org.elasticsearch.action.NotifyOnceListener.onResponse(NotifyOnceListener.java:40)
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.doGetRepositoryData(BlobStoreRepository.java:1368)
        at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:733)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)
```

**Comment by original-brownbear** [comment]
I believe this is likely fixed by https://github.com/elastic/elasticsearch/pull/64770 (a bug caused an exception on the CS thread which caused the cluster to get into a broken state). I'll leave this open to verify that connection though. On it

**Comment by original-brownbear** [comment]
I'm closing this for now as I'm 99% sure it's a result of #64770 after some digging.
