### ISSUE TITLE
I run elasticsearch-7.9.0 source code in IDEA occurs error '...x-pack-ml/platform/darwin-x86_64/controller.app/Contents/MacOS/controller": error=13, Permission denied'

### ISSUE THREAD

**Issue by meishaoyong** [elastic/elasticsearch#64903]
I try to configure 'elasticsearch.yml' file with xpack items below:
x-pack-analytics.enabled: false
x-pack-async.enabled: false
x-pack-async-search.enabled: false
x-pack-autoscaling.enabled: false
x-pack-ccr.enabled: false
x-pack-core.enabled: false
x-pack-data-streams.enabled: false
x-pack-deprecation.enabled: false
x-pack-enrich.enabled: false
x-pack-eql.enabled: false
x-pack-graph.enabled: false
x-pack-identity-provider.enabled: false
x-pack-ilm.enabled: false
x-pack-logstash.enabled: false
x-pack-ml.enabled: false
x-pack-monitoring.enabled: false
x-pack-ql.enabled: false
x-pack-rollup.enabled: false
x-pack-security.enabled: false
x-pack-sql.enabled: false
x-pack-stack.enabled: false
x-pack-voting-only-node.enabled: false
x-pack-watcher.enabled: false

there's also error : 

Caused by: java.io.IOException: Cannot run program "/Users/meishaoyong/workstation/elk/elasticsearch-7.9.0/modules/x-pack-ml/platform/darwin-x86_64/controller.app/Contents/MacOS/controller": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1128) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1071) ~[?:?]
	at org.elasticsearch.bootstrap.Spawner.spawnNativeController(Spawner.java:128) ~[classes/:?]
	at org.elasticsearch.bootstrap.Spawner.spawnNativeControllers(Spawner.java:88) ~[classes/:?]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:173) ~[classes/:?]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[classes/:?]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[classes/:?]
	... 6 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.ProcessImpl.forkAndExec(Native Method) ~[?:?]
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:340) ~[?:?]
	at java.lang.ProcessImpl.start(ProcessImpl.java:271) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1107) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1071) ~[?:?]
	at org.elasticsearch.bootstrap.Spawner.spawnNativeController(Spawner.java:128) ~[classes/:?]
	at org.elasticsearch.bootstrap.Spawner.spawnNativeControllers(Spawner.java:88) ~[classes/:?]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:173) ~[classes/:?]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[classes/:?]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[classes/:?]

i already try 'chown -R meishaoyong /Users/meishaoyong/workstation/elk/elasticsearch-7.9.0',  but it not work.

please help me, thanks~

**Comment by costin** [comment]
Please ask user questions on the [forums](https://discuss.elastic.co/), or consult the [documentation](https://www.elastic.co/guide/index.html).
We reserve GitHub issues for bug reports and feature requests only. The forums are the appropriate place to handle these questions.
