### ISSUE TITLE
[CI] destructiveDistroTest fails because it cannot remove the data directory 

### ISSUE THREAD

**Issue by valeriy42** [elastic/elasticsearch#65047]
**Build scan**: https://gradle-enterprise.elastic.co/s/tsgrirlij3i4s

**Repro line**: Run ` :qa:os:destructiveDistroTest.default-windows-archive-no-jdk`

**Reproduces locally?**: No

**Applicable branches**: `7.10`

**Failure excerpt**:
 ```
:qa:os:destructiveDistroTest.default-windows-archive-no-jdk FAILED

org.elasticsearch.packaging.test.ConfigurationTests > classMethod FAILED
    java.lang.RuntimeException: java.io.IOException: could not remove the following files (in the order of attempts):
       C:\tmp\elasticsearch\data\nodes\0\_state\_5.fdt: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\data\nodes\0\_state\_5.fdt
       C:\tmp\elasticsearch\data\nodes\0\_state: java.nio.file.DirectoryNotEmptyException: C:\tmp\elasticsearch\data\nodes\0\_state
       C:\tmp\elasticsearch\data\nodes\0: java.nio.file.DirectoryNotEmptyException: C:\tmp\elasticsearch\data\nodes\0
       C:\tmp\elasticsearch\data\nodes: java.nio.file.DirectoryNotEmptyException: C:\tmp\elasticsearch\data\nodes
       C:\tmp\elasticsearch\data: java.nio.file.DirectoryNotEmptyException: C:\tmp\elasticsearch\data
       C:\tmp\elasticsearch: java.nio.file.DirectoryNotEmptyException: C:\tmp\elasticsearch
        at __randomizedtesting.SeedInfo.seed([11DAF8CA3AA3DA29]:0)
        at org.elasticsearch.packaging.util.FileUtils.rm(FileUtils.java:91)
        at org.elasticsearch.packaging.util.Cleanup.lambda$cleanEverything$3(Cleanup.java:86)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.elasticsearch.packaging.util.Cleanup.cleanEverything(Cleanup.java:86)
        at org.elasticsearch.packaging.test.PackagingTestCase.cleanup(PackagingTestCase.java:234)
        at org.elasticsearch.packaging.test.PackagingTestCase.init(PackagingTestCase.java:147)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:878)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.io.IOException: could not remove the following files (in the order of attempts):
           C:\tmp\elasticsearch\data\nodes\0\_state\_5.fdt: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\data\nodes\0\_state\_5.fdt
           C:\tmp\elasticsearch\data\nodes\0\_state: java.nio.file.DirectoryNotEmptyException: C:\tmp\elasticsearch\data\nodes\0\_state
           C:\tmp\elasticsearch\data\nodes\0: java.nio.file.DirectoryNotEmptyException: C:\tmp\elasticsearch\data\nodes\0
           C:\tmp\elasticsearch\data\nodes: java.nio.file.DirectoryNotEmptyException: C:\tmp\elasticsearch\data\nodes
           C:\tmp\elasticsearch\data: java.nio.file.DirectoryNotEmptyException: C:\tmp\elasticsearch\data
           C:\tmp\elasticsearch: java.nio.file.DirectoryNotEmptyException: C:\tmp\elasticsearch
            at org.elasticsearch.core.internal.io.IOUtils.rm(IOUtils.java:212)
            at org.elasticsearch.packaging.util.FileUtils.rm(FileUtils.java:89)
            ... 15 more
```

**Comment by henningandersen** [comment]
This happened on my PR (#73435) build today for an unrelated change, see [build-scan](https://gradle-enterprise.elastic.co/s/mbeetozrqyjlq).

**Comment by mark-vieira** [comment]
This hasn't been observed in some time. Closing for now.
