### ISSUE TITLE
HistoryTemplateHttpMappingsTests#testHttpFields failure

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#65117]
**Build scan**:

[Last failure](https://gradle-enterprise.elastic.co/s/2jcvbp2gehjaw)
[Other failure](https://gradle-enterprise.elastic.co/s/zewljhi2l4nww)

**Repro line**:

```
./gradlew ':x-pack:plugin:watcher:internalClusterTest' --tests "org.elasticsearch.xpack.watcher.history.HistoryTemplateHttpMappingsTests.testHttpFields" \
  -Dtests.seed=7B65E35E8F2C5B8A \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-IQ \
  -Dtests.timezone=America/Fort_Wayne \
  -Druntime.java=11
```

**Reproduces locally?**:
Could not reproduce locally after 1,000 iterations.

**Applicable branches**:

master only

**Failure history**:

Could be related to https://github.com/elastic/elasticsearch/issues/64252

**Failure**:

```
java.lang.AssertionError: watch was triggered on [0] schedulers, expected [1]
Expected: a value equal to or greater than <1L>
     but: <0L> was less than <1L>
	at __randomizedtesting.SeedInfo.seed([E2D763563C560E94:3D3C8E6F2D1B6E6F]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase$TimeWarp.trigger(AbstractWatcherIntegrationTestCase.java:606)
	at org.elasticsearch.xpack.watcher.test.AbstractWatcherIntegrationTestCase$TimeWarp.trigger(AbstractWatcherIntegrationTestCase.java:591)
	at org.elasticsearch.xpack.watcher.history.HistoryTemplateHttpMappingsTests.testHttpFields(HistoryTemplateHttpMappingsTests.java:84)
```

**Comment by probakowski** [comment]
Should be fixed by #65186
