### ISSUE TITLE
Reproducible Failure in org.elasticsearch.search.aggregations.bucket.terms.StringRareTermsTests.testReduceRandom

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#65118]
Haven't seen this on CI yet but this reproduces 100% of the time for locally on master.

```
./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.terms.StringRareTermsTests.testReduceRandom" -Dtests.seed=7B822F4D26B620AD -Dtests.security.manager=true -Dtests.locale=lt -Dtests.timezone=MET -Druntime.java=15
```

fails via:

```
Suite: Test class org.elasticsearch.search.aggregations.bucket.terms.StringRareTermsTests
  1> [2020-11-17T09:27:20,643][INFO ][o.e.s.a.b.t.StringRareTermsTests] [testReduceRandom] before test
  1> [2020-11-17T09:27:20,736][INFO ][o.e.s.a.b.t.StringRareTermsTests] [testReduceRandom] after test
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.terms.StringRareTermsTests.testReduceRandom" -Dtests.seed=7B822F4D26B620AD -Dtests.security.manager=true -Dtests.locale=lt -Dtests.timezone=MET -Druntime.java=15
  2> java.lang.NullPointerException: Cannot read field "threshold" because "other" is null
        at __randomizedtesting.SeedInfo.seed([7B822F4D26B620AD:BBBF835C00EBB9FB]:0)
        at org.elasticsearch.common.util.SetBackedScalingCuckooFilter.merge(SetBackedScalingCuckooFilter.java:321)
        at org.elasticsearch.search.aggregations.bucket.terms.InternalMappedRareTerms.reduce(InternalMappedRareTerms.java:123)
        at org.elasticsearch.test.InternalAggregationTestCase.testReduceRandom(InternalAggregationTestCase.java:399)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
        at java.base/java.lang.Thread.run(Thread.java:832)
  2> NOTE: leaving temporary files on disk at: /home/brownbear/src/elasticsearch/server/build/testrun/test/temp/org.elasticsearch.search.aggregations.bucket.terms.StringRareTermsTests_7B822F4D26B620AD-002
  2> NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=1438, maxMBSortInHeap=5.731928455826495, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=lt, timezone=MET
  2> NOTE: Linux 5.4.0-54-generic amd64/AdoptOpenJDK 15.0.1 (64-bit)/cpus=16,threads=1,free=482448840,total=536870912
  2> NOTE: All tests run in this JVM: [StringRareTermsTests]

Tests with failures:
 - org.elasticsearch.search.aggregations.bucket.terms.StringRareTermsTests.testReduceRandom

```

**Comment by nik9000** [comment]
Thanks for the ping @original-brownbear !
