### ISSUE TITLE
Reproducible Failure in org.elasticsearch.search.aggregations.metrics.InternalTopHitsTests.testReduceRandom

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#65163]
This reproduces 100% of the time for me locally on current master:

```
Suite: Test class org.elasticsearch.search.aggregations.metrics.InternalTopHitsTests
  1> [2020-11-17T21:21:56,451][INFO ][o.e.s.a.m.InternalTopHitsTests] [testReduceRandom] before test
  1> [2020-11-17T21:21:56,586][INFO ][o.e.s.a.m.InternalTopHitsTests] [testReduceRandom] after test
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.metrics.InternalTopHitsTests.testReduceRandom" -Dtests.seed=3F5182C50EE4E338 -Dtests.security.manager=true -Dtests.locale=sk-SK -Dtests.timezone=Europe/Andorra -Druntime.java=15
  2> java.lang.AssertionError: Didn't match expected value:
                              hits: 
                                hits: 
                                     0: 
                                     _id: same [9]
                                  _score: same [0.99827045]
                                     1: 
                                     _id: same [10]
                                  _score: same [0.996799]
                                     2: 
                                     _id: same [0]
                                  _score: same [0.9966625]
                                     3: 
                                     _id: same [18]
                                  _score: same [0.99489796]
                                     4: 
                                     _id: same [11]
                                  _score: same [0.9931389]
                                     5: 
                                     _id: same [7]
                                  _score: same [0.99165297]
                                     6: 
                                     _id: same [3]
                                  _score: same [0.9915664]
                                     7: 
                                     _id: same [12]
                                  _score: same [0.9913156]
                                     8: 
                                     _id: same [0]
                                  _score: same [0.9905108]
                                     9: 
                                     _id: same [3]
                                  _score: same [0.9893769]
                                    10: 
                                     _id: same [1]
                                  _score: same [0.98848015]
                                    11: 
                                     _id: expected String [1] but was String [13]
                                  _score: expected Double [0.9830506] but was Double [0.98169035]
                           max_score: same [0.99827045]
                               total: 
                              relation: same [eq]
                                 value: same [24404932]
        at __randomizedtesting.SeedInfo.seed([3F5182C50EE4E338:FF6C2ED428B97A6E]:0)
        at org.elasticsearch.search.aggregations.metrics.InternalTopHitsTests.assertEqualsWithErrorMessageFromXContent(InternalTopHitsTests.java:298)
        at org.elasticsearch.search.aggregations.metrics.InternalTopHitsTests.assertReduced(InternalTopHitsTests.java:269)
        at org.elasticsearch.search.aggregations.metrics.InternalTopHitsTests.assertReduced(InternalTopHitsTests.java:67)
  2> NOTE: leaving temporary files on disk at: /home/brownbear/src/elasticsearch/server/build/testrun/test/temp/org.elasticsearch.search.aggregations.metrics.InternalTopHitsTests_3F5182C50EE4E338-002
  2> NOTE: test params are: codec=Lucene87, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=sk-SK, timezone=Europe/Andorra
  2> NOTE: Linux 5.4.0-54-generic amd64/AdoptOpenJDK 15.0.1 (64-bit)/cpus=16,threads=1,free=478926608,total=536870912
  2> NOTE: All tests run in this JVM: [InternalTopHitsTests]


```

**Comment by jtibshirani** [comment]
I muted the test:
* 8499e1d2dfeef71ac13b62dc5af803134d1e1dd9 (7.x)
* 848906d3b66520718d50341e9e65b1e7cd62ea0b (master)

**Comment by jtibshirani** [comment]
The case `InternalTopMetricsTests.testReduceRandom` can also consistently:

```
./gradlew ':x-pack:plugin:analytics:test' --tests "org.elasticsearch.xpack.analytics.topmetrics.InternalTopMetricsTests.testReduceRandom" -Dtests.seed=591D98BCABD883BC -Dtests.security.manager=true -Dtests.locale=bg-BG -Dtests.timezone=EET -Druntime.java=11 
```

The mute was quite broad, and covers all instances of `testReduceRandom` in aggregation tests. If it turns out it's not a widespread problem, I can adjust the mute to be more specific.

**Comment by nik9000** [comment]
I'll look at this tomorrow morning.

**Comment by nik9000** [comment]
Sorry this took so long! I've tracked down the issue to a test bug fix I did yesterday breaking other things. Yay. I've got to run a bunch of tests with `@Repeat(iterations=1000)` now.
