### ISSUE TITLE
TimeSeriesLifecycleActionsIT#testForceMergeActionWithCompressionCodec can fail with assertion error

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#65171]
**Build scan**: https://gradle-enterprise.elastic.co/s/5wksambdfququ

**Repro line**:
```
./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testForceMergeActionWithCompressionCodec" -Dtests.seed=769BF75C3D24820D -Dtests.security.manager=true -Dtests.locale=ar-JO -Dtests.timezone=America/Indiana/Marengo -Druntime.java=11
```

**Reproduces locally?**: no.

**Applicable branches**: master, 7.x

**Failure history**: seems to have started failing occasionally starting on November 3rd.

**Failure excerpt**:
```
org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT > testForceMergeActionWithCompressionCodec FAILED |  
-- | --
  | java.lang.AssertionError: |  
  | Expected: <1> |  
  | but: was <3> |  
  | at __randomizedtesting.SeedInfo.seed([769BF75C3D24820D:5F6B333BE1107442]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.junit.Assert.assertThat(Assert.java:923) |  
  | at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.lambda$forceMergeActionWithCodec$34(TimeSeriesLifecycleActionsIT.java:496) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:950) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:923) |  
  | at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.forceMergeActionWithCodec(TimeSeriesLifecycleActionsIT.java:493) |  
  | at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.testForceMergeActionWithCompressionCodec(TimeSeriesLifecycleActionsIT.java:507)
```

**Comment by jtibshirani** [comment]
I muted the test:
* 9bc17fa3d65d8690c81195d6c66d904669eb5ccd (7.x)
* caf9cd28804f0f44a01f6f0df6fa07018df3fb8e (master)
