### ISSUE TITLE
MlJobSnapshotUpgradeIT.testSnapshotUpgrader failure

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#65196]
**Build scan**:
https://gradle-enterprise.elastic.co/s/nscfpdycukcng
**Repro line**:

./gradlew ':x-pack:qa:rolling-upgrade:v7.6.1#oldClusterTest' --tests "org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.testSnapshotUpgrader" -Dtests.seed=641520299CC7DE26 -Dtests.security.manager=true -Dtests.locale=nn-NO -Dtests.timezone=Asia/Hebron -Dtests.distribution=default -Druntime.java=8 |  
 

**Reproduces locally?**:
yes
**Applicable branches**:
7.x
**Failure excerpt**:

org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT > testSnapshotUpgrader FAILED
    java.lang.AssertionError: 
    Expected: <7>
         but: was <6>
        at __randomizedtesting.SeedInfo.seed([641520299CC7DE26:783639469BB275A8]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.createJobAndSnapshots(MlJobSnapshotUpgradeIT.java:210)
        at org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.testSnapshotUpgrader(MlJobSnapshotUpgradeIT.java:98)

**Comment by benwtrent** [comment]
closed by https://github.com/elastic/elasticsearch/pull/65197
