### ISSUE TITLE
[CI] MlJobSnapshotUpgradeIT.testSnapshotUpgrader failure

### ISSUE THREAD

**Issue by csoulios** [elastic/elasticsearch#65198]
**Build scan**:
https://gradle-enterprise.elastic.co/s/rzjr3udmqcvhi
https://gradle-enterprise.elastic.co/s/eurjstylqxcow
https://gradle-enterprise.elastic.co/s/2kyfcpyv7pxms

**Repro line**:

```
./gradlew ':x-pack:qa:rolling-upgrade:v7.9.2#oldClusterTest' --tests "org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.testSnapshotUpgrader" -Dtests.seed=483DE8B22E516FA8 -Dtests.security.manager=true -Dtests.locale=ar -Dtests.timezone=America/Scoresbysund -Druntime.java=8
```

```
./gradlew ':x-pack:qa:rolling-upgrade:v7.4.1#oldClusterTest' --tests "org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.testSnapshotUpgrader" \
  -Dtests.seed=E785440A0FD7194E \
  -Dtests.security.manager=true \
  -Dtests.locale=ja \
  -Dtests.timezone=Europe/Malta \
  -Dtests.distribution=default \
  -Druntime.java=8
```
**Reproduces locally?**: **Yes**

**Applicable branches**: `7.x`

**Failure history**:

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-6M,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'test:%22testSnapshotUpgrader%22'),sort:!(time,desc))

**Failure excerpt**:

```
11:53:36 org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT > testSnapshotUpgrader FAILED
11:53:36     java.lang.AssertionError: 
11:53:36     Expected: <7>
11:53:36          but: was <6>
11:53:36         at __randomizedtesting.SeedInfo.seed([483DE8B22E516FA8:541EF1DD2924C426]:0)
11:53:36         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
11:53:36         at org.junit.Assert.assertThat(Assert.java:956)
11:53:36         at org.junit.Assert.assertThat(Assert.java:923)
11:53:36         at org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.createJobAndSnapshots(MlJobSnapshotUpgradeIT.java:210)
11:53:36         at org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.testSnapshotUpgrader(MlJobSnapshotUpgradeIT.java:98)
```

**Comment by csoulios** [comment]
Duplicate of #65196

**Comment by benwtrent** [comment]
closed by https://github.com/elastic/elasticsearch/pull/65197
