### ISSUE TITLE
The painless script goes wrong in Chinese

### ISSUE THREAD

**Issue by akamachi95** [elastic/elasticsearch#65268]
I just named a field in Chinese, And something goes wrong.
`if (ctx._source.品牌==“三菱”) {ctx._source.time='1';}else{ctx._source.time='0';}`
品牌 is Brand in Chinese，and the full trace is
```
ElasticsearchStatusException[Elasticsearch exception [type=script_exception, reason=compile error]]; nested: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=unexpected character [品].]]; nested: ElasticsearchException[Elasticsearch exception [type=lexer_no_viable_alt_exception, reason=null]];
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:187)
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1892)
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1869)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1626)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1583)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1553)
	at org.elasticsearch.client.RestHighLevelClient.updateByQuery(RestHighLevelClient.java:599)
	at com.functest.AddByData.addByDate(AddByData.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
	Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:9200], URI [/%E6%97%A5%E6%9C%AC%E4%BA%A4%E9%80%9Atoken/_update_by_query?slices=1&requests_per_second=-1&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&timeout=1m], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"script_exception","reason":"compile error","script_stack":["... tetime);\nif (ctx._source.品牌==\"三菱\") {ctx._source.ti ...","                             ^---- HERE"],"script":"String datetime = '1983-10-13T22:15:30Z';\nZonedDateTime zdt = ZonedDateTime.parse(datetime);\nif (ctx._source.品牌==\"三菱\") {ctx._source.time='1';}else{ctx._source.time='0';}","lang":"painless","position":{"offset":109,"start":84,"end":134}}],"type":"script_exception","reason":"compile error","script_stack":["... tetime);\nif (ctx._source.品牌==\"三菱\") {ctx._source.ti ...","                             ^---- HERE"],"script":"String datetime = '1983-10-13T22:15:30Z';\nZonedDateTime zdt = ZonedDateTime.parse(datetime);\nif (ctx._source.品牌==\"三菱\") {ctx._source.time='1';}else{ctx._source.time='0';}","lang":"painless","position":{"offset":109,"start":84,"end":134},"caused_by":{"type":"illegal_argument_exception","reason":"unexpected character [品].","caused_by":{"type":"lexer_no_viable_alt_exception","reason":null}}},"status":400}
		at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:302)
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:272)
		at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246)
		at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1613)
		... 30 more
Caused by: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=unexpected character [品].]]; nested: ElasticsearchException[Elasticsearch exception [type=lexer_no_viable_alt_exception, reason=null]];
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:496)
	at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:407)
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:437)
	at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:603)
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:179)
	... 33 more
Caused by: ElasticsearchException[Elasticsearch exception [type=lexer_no_viable_alt_exception, reason=null]]
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:496)
	at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:407)
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:437)
	... 37 more

```
But when I rename it to brand， it works....

**Comment by akamachi95** [comment]
Further more, this also happened to Japanese...

**Comment by romseygeek** [comment]
Hi @akamachi95, accessing fields using dot notation will only work if the field name can also be used as a painless identifier (see https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-identifiers.html).  In your case, you should be able to reference the field like this: `ctx._source.["品牌"]`
