### ISSUE TITLE
[CI] SegmentsStatsTests::testFileExtensionDescriptions failure

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#65267]
might be related to #62019

**Build scan**: https://gradle-enterprise.elastic.co/s/xmxbz7pi5vd3c

**Repro line**:
```
./gradlew ':server:test' --tests "org.elasticsearch.index.engine.SegmentsStatsTests.testFileExtensionDescriptions" -Dtests.seed=D61165645CCDFEC3 -Dtests.security.manager=true -Dtests.locale=es-NI -Dtests.timezone=Pacific/Tongatapu -Druntime.java=8
```

**Reproduces locally?**: yes

**Applicable branches**: 7.x, master

**Failure excerpt**:

```
12:08:06 org.elasticsearch.index.engine.SegmentsStatsTests > testFileExtensionDescriptions FAILED
12:08:06     java.lang.AssertionError
12:08:06         at __randomizedtesting.SeedInfo.seed([D61165645CCDFEC3:40B81B1D41AEE038]:0)
12:08:06         at org.junit.Assert.fail(Assert.java:86)
12:08:06         at org.junit.Assert.assertTrue(Assert.java:41)
12:08:06         at org.junit.Assert.assertTrue(Assert.java:52)
12:08:06         at org.elasticsearch.index.engine.SegmentsStatsTests.testFileExtensionDescriptions(SegmentsStatsTests.java:67)
12:08:06 REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.index.engine.SegmentsStatsTests.testFileExtensionDescriptions" -Dtests.seed=D61165645CCDFEC3 
```

**Comment by davidkyle** [comment]
Another https://gradle-enterprise.elastic.co/s/7vmpegykf2cfy

In fact it fails regularly, muting on master and 7.x

 https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:SegmentsStatsTests),sort:!(time,desc))
