### ISSUE TITLE
CI: centos-7 vagrant build failing due to cryptographic failure

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#65300]
Cause:

```
09:23:35 | Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
09:23:35 | 	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:121)
09:23:35 | 	... 98 more
09:23:35 | Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited
09:23:35 | 	at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:335)
09:23:35 | 	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:112)
09:23:35 | 	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:109)
09:23:35 | 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
09:23:35 | 	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:108)
09:23:35 | 	... 98 more
```

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-vagrant-matrix/OS=centos-7,nodes=metal/26/console
Build Scans: https://gradle-enterprise.elastic.co/s/ogiubfcoqmcim

To find the error one needs to scroll all the way to the bottom; the rest of the error messages are somewhat misleading - initially I thought it was a disk problem until bumping into the above.

**Comment by mark-vieira** [comment]
Vagrant jobs are gone.
