### ISSUE TITLE
JdbcCsvSpecIT#testCurrentDateFilter can fail with assertion error

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#65336]
**Build scan**: https://gradle-enterprise.elastic.co/s/4sbg4vwwi3wxc

**Repro line**:

```
./gradlew ':x-pack:plugin:sql:qa:server:security:without-ssl:integTest' --tests "org.elasticsearch.xpack.sql.qa.security.JdbcCsvSpecIT" -Dtests.method="test {date.testCurrentDateFilter}" -Dtests.seed=A44AF275CAF797A8 -Dtests.security.manager=true -Dtests.locale=ar-SA -Dtests.timezone=Egypt -Druntime.java=8
```

**Reproduces locally?**: yes

**Applicable branches**: 7.10, 7.x

**Failure history**: seems like it started failing earlier today. The first failure was at 12:05 UTC.

**Failure excerpt**:

```
 2> org.junit.ComparisonFailure: Different result for column [first_name], entry [9] expected:<B[ezalel]> but was:<B[ojan]>
        at __randomizedtesting.SeedInfo.seed([A44AF275CAF797A8:2C1ECDAF640BFA50]:0)
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.doAssertResultSetData(JdbcAssert.java:338)
        at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSetData(JdbcAssert.java:222)
        at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:105)
        at org.elasticsearch.xpack.sql.qa.jdbc.CsvSpecTestCase.assertResults(CsvSpecTestCase.java:55)
        at org.elasticsearch.xpack.sql.qa.jdbc.CsvSpecTestCase.executeAndAssert(CsvSpecTestCase.java:62)
        at org.elasticsearch.xpack.sql.qa.jdbc.CsvSpecTestCase.doTest(CsvSpecTestCase.java:48)
        at org.elasticsearch.xpack.sql.qa.jdbc.SpecBaseIntegrationTestCase.test(SpecBaseIntegrationTestCase.java:89)
```

**Comment by jtibshirani** [comment]
I'm not sure how to mute the test in a targeted way -- perhaps someone from @elastic/es-ql could take a look and mute if it's not immediately fixable?

**Comment by palesz** [comment]
I can take a look in about an hour or two.

**Comment by original-brownbear** [comment]
This also reproduces on master via:

```
./gradlew ':x-pack:plugin:sql:qa:server:security:with-ssl:integTest' --tests "org.elasticsearch.xpack.sql.qa.security.JdbcCsvSpecIT" -Dtests.seed=6EB27D271BC90F59 -Dtests.security.manager=true -Dtests.locale=ar-SD -Dtests.timezone=America/Merida -Druntime.java=11
```

**Comment by original-brownbear** [comment]
Muted in master, 7.x and 7.10 now

**Comment by hendrikmuhs** [comment]
Effects 6.8, too: https://gradle-enterprise.elastic.co/s/jrvugtavn6pka

**Comment by matriv** [comment]
@jtibshirani Just FYI, we have examples on how to mute SQL [csv](https://github.com/elastic/elasticsearch/blob/22065d97b52320be0be8f9ae2a1e7963595573b9/x-pack/plugin/sql/qa/src/main/resources/examples/example.csv-spec) and [sql](https://github.com/elastic/elasticsearch/blob/22065d97b52320be0be8f9ae2a1e7963595573b9/x-pack/plugin/sql/qa/src/main/resources/examples/example.sql-spec) tests.
