### ISSUE TITLE
Elasticsearch fails to start if a Watcher `default_account` has been set but the account no longer exists

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#65337]
**Elasticsearch version** (`bin/elasticsearch --version`): Observed on 7.10.0 and 7.6.2, bug is likely much older

**Plugins installed**: [xpack]

**JVM version** (`java -version`): built-in

**OS version** (`uname -a` if on a Unix-like system): MacOS, ECE

**Steps to reproduce**:

Using a single-node cluster:

 1. Start an Elasticsearch node.
 2. Configure an email account for Watcher using the Cluster Settings API:
```
PUT /_cluster/settings
{
    "persistent": {
        "xpack.notification.email": {
            "default_account": "example_acct",
            "account": {
                "example_acct": {
                    "profile": "standard",
                    "email_defaults.from": "example@example.com",
                    "smtp": {
                        "auth": false,
                        "host": "smtp.example.com",
                        "port": "25",
                        "user": "example@example.com"
                    }
                }
            }
        }
    }
}
```
 3. Remove the account settings, but not `default_account` using the Cluster Settings API:
```
PUT /_cluster/settings
{
    "persistent": {
        "xpack.notification.email": {
            "account": {
                "example_acct": {
                    "profile": null,
                    "email_defaults.from": null,
                    "smtp": {
                        "auth": null,
                        "host": null,
                        "port": null,
                        "user": null
                    }
                }
            }
        }
    }
}
```
 4. Attempt to restart the node.

Elasticsearch will continually fail to start with an error message like this:
```
[2020-11-20T19:02:27,406][WARN ][o.e.c.s.ClusterSettings  ] [Elastic-MBP-4.local] failed to apply settings
org.elasticsearch.common.settings.SettingsException: could not find default account [example_acct]
	at org.elasticsearch.xpack.watcher.notification.NotificationService.findDefaultAccountOrNull(NotificationService.java:160) ~[?:?]
	at org.elasticsearch.xpack.watcher.notification.NotificationService.buildAccounts(NotificationService.java:99) ~[?:?]
	at org.elasticsearch.xpack.watcher.notification.NotificationService.clusterSettingsConsumer(NotificationService.java:69) ~[?:?]
	at org.elasticsearch.common.settings.Setting$2.apply(Setting.java:710) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.common.settings.Setting$2.apply(Setting.java:682) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater.lambda$updater$0(AbstractScopedSettings.java:627) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:193) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:466) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:418) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:68) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:162) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.10.0.jar:7.10.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[2020-11-20T19:02:27,407][WARN ][o.e.c.s.ClusterApplierService] [Elastic-MBP-4.local] failed to apply updated cluster state in [0s]:
version [235], uuid [IO6KKltpRWuCoemCEjseLQ], source [Publication{term=195, version=235}]
org.elasticsearch.common.settings.SettingsException: could not find default account [example_acct]
	at org.elasticsearch.xpack.watcher.notification.NotificationService.findDefaultAccountOrNull(NotificationService.java:160) ~[?:?]
	at org.elasticsearch.xpack.watcher.notification.NotificationService.buildAccounts(NotificationService.java:99) ~[?:?]
	at org.elasticsearch.xpack.watcher.notification.NotificationService.clusterSettingsConsumer(NotificationService.java:69) ~[?:?]
	at org.elasticsearch.common.settings.Setting$2.apply(Setting.java:710) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.common.settings.Setting$2.apply(Setting.java:682) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater.lambda$updater$0(AbstractScopedSettings.java:627) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:193) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:466) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:418) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:68) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:162) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.10.0.jar:7.10.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Workaround**:

Adding an account of the same name and type to `elasticsearch.yml` will allow the node to start.

**Comment by dakrone** [comment]
For anyone stumbling upon this, it is possible to recover from this by using:

```
$ bin/elasticsearch-node remove-settings xpack.notification.email.default_account
```

While the ES node is down.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
