### ISSUE TITLE
Monitoring indices fails 

### ISSUE THREAD

**Issue by HaZet1968** [elastic/elasticsearch#65405]
**Elasticsearch version:** Version: 7.10.0, Build: default/deb/51e9d6f22758d0374a0f3f5c6e8f3a7997850f96/2020-11-09T21:30:33.964949Z, JVM: 15.0.1

**JVM version** : openjdk 11.0.9 2020-10-20

**OS version** (`uname -a` if on a Unix-like system): Linux esnode1-rza 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: Opening Kibana and try to view Management -> Stack Monitoring ->Indices fails and leads to a lot of entries in the elasticsearch logs since change from legacy monitoring to monitoring with metricbeat (7.9.1)

**Steps to reproduce**:

    Change elasticsearch monitoring to metricbeat
    In Kibana go to page Management -> Stack Monitoring ->Indices
    Wait...

After some time I get a lot of entries in the elasticsearch logs (on several nodes)

Expected behavior: Show an overview of the indices

**Provide logs (if relevant)**:

Output of one elasticsearch log:
2020-11-23T07:40:17,219][WARN ][o.e.t.InboundHandler ] [node-2-a] handling inbound transport message [InboundMessage{Header{3377158}{7.10.0}{33130325}{false}{false}{false}{false}{NO_ACTION_NAME_FOR_RESPONSES}}] took [7750ms] which is above the warn threshold of [5000ms]
[2020-11-23T07:41:49,122][INFO ][o.e.m.j.JvmGcMonitorService] [node-2-a] [gc][243275] overhead, spent [339ms] collecting in the last [1s]
[2020-11-23T07:41:55,957][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-2-a] uncaught exception in thread [elasticsearch[node-2-a][search][T#393]]
org.elasticsearch.tasks.TaskCancelledException: The parent task was cancelled, shouldn't start any child tasks
at org.elasticsearch.tasks.TaskManager$CancellableTaskHolder.registerChildNode(TaskManager.java:522) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.tasks.TaskManager.registerChildNode(TaskManager.java:213) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.support.TransportAction.registerChildNode(TransportAction.java:56) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:86) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:75) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:412) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:545) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.search.TransportMultiSearchAction.executeSearch(TransportMultiSearchAction.java:149) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.search.TransportMultiSearchAction$1.handleResponse(TransportMultiSearchAction.java:172) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.search.TransportMultiSearchAction$1.onFailure(TransportMultiSearchAction.java:157) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:98) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:50) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.ActionListener$5.onFailure(ActionListener.java:258) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.search.AbstractSearchAsyncAction.raisePhaseFailure(AbstractSearchAsyncAction.java:594) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:568) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.action.search.FetchSearchPhase$1.onFailure(FetchSearchPhase.java:100) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:737) ~[elasticsearch-7.10.0.jar:7.10.0]
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.10.0.jar:7.10.0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
last message repeated about 80-100 times...

**Any additional context:**
Sometimes the nodes get disconnected from cluster then. One time I had to do a full restart of the cluster.
Cluster has three nodes, 972 indices, 1944 Shards, 12 TB Data

**Comment by original-brownbear** [comment]
There is a legitimate bug here with us loosing a listener and hence probably leaking memory. I'll open a fix PR shortly.
