### ISSUE TITLE
[CI] SpatialClientYamlTestSuiteIT.test {yaml=/60_geo_line/Test geo_line aggregation on geo points} fails reproducibly

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#65418]
**Build scan**:

Happened on PR build, but reproduces on master: https://gradle-enterprise.elastic.co/s/pbfhdxzm3mzdo

**Repro line**:

./gradlew ':x-pack:plugin:spatial:yamlRestTest' --tests "org.elasticsearch.xpack.spatial.SpatialClientYamlTestSuiteIT.test {yaml=/60_geo_line/Test geo_line aggregation on geo points}" -Dtests.seed=BBE6AC6EDAC1677C -Dtests.security.manager=true -Dtests.locale=zh-Hans-CN -Dtests.timezone=Asia/Dushanbe -Druntime.java=11

**Reproduces locally?**:

Yes

**Applicable branches**:

master

**Failure history**:
No other failures seen so far

**Failure excerpt**:
```
[2020-11-24T17:55:30,915][INFO ][o.e.x.s.SpatialClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "error" : {
  1>         "root_cause" : [ ],
  1>         "type" : "search_phase_execution_exception",
  1>         "reason" : "",
  1>         "phase" : "fetch",
  1>         "grouped" : true,
  1>         "failed_shards" : [ ],
  1>         "caused_by" : {
  1>           "type" : "array_index_out_of_bounds_exception",
  1>           "reason" : "Index 0 out of bounds for length 0",
  1>           "stack_trace" : "java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
  1>    at org.elasticsearch.xpack.spatial.search.aggregations.MergedGeoLines.correctOrdering(MergedGeoLines.java:110)
  1>    at org.elasticsearch.xpack.spatial.search.aggregations.MergedGeoLines.heapifyUp(MergedGeoLines.java:143)
  1>    at org.elasticsearch.xpack.spatial.search.aggregations.MergedGeoLines.add(MergedGeoLines.java:103)
  1>    at org.elasticsearch.xpack.spatial.search.aggregations.MergedGeoLines.merge(MergedGeoLines.java:54)
  1>    at org.elasticsearch.xpack.spatial.search.aggregations.InternalGeoLine.reduce(InternalGeoLine.java:100)
  1>    at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:166)
  1>    at org.elasticsearch.search.aggregations.InternalAggregations.topLevelReduce(InternalAggregations.java:115)
  1>    at org.elasticsearch.action.search.SearchPhaseController.reduceAggs(SearchPhaseController.java:486)
  1>    at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:474)
  1>    at org.elasticsearch.action.search.QueryPhaseResultConsumer.reduce(QueryPhaseResultConsumer.java:141)
  1>    at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:109)
  1>    at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:95)
  1>    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  1>    at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)
  1>    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:733)
  1>    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  1>    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  1>    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  1>    at java.base/java.lang.Thread.run(Thread.java:834)
  1> "
  1>         },
  1>         "stack_trace" : "Failed to execute phase [fetch],
  1>    at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:593)
  1>    at org.elasticsearch.action.search.FetchSearchPhase$1.onFailure(FetchSearchPhase.java:100)
  1>    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
  1>    at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)
  1>    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:733)
  1>    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  1>    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  1>    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  1>    at java.base/java.lang.Thread.run(Thread.java:834)
  1> Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
  1>    at org.elasticsearch.xpack.spatial.search.aggregations.MergedGeoLines.correctOrdering(MergedGeoLines.java:110)
  1>    at org.elasticsearch.xpack.spatial.search.aggregations.MergedGeoLines.heapifyUp(MergedGeoLines.java:143)
  1>    at org.elasticsearch.xpack.spatial.search.aggregations.MergedGeoLines.add(MergedGeoLines.java:103)
  1>    at org.elasticsearch.xpack.spatial.search.aggregations.MergedGeoLines.merge(MergedGeoLines.java:54)
  1>    at org.elasticsearch.xpack.spatial.search.aggregations.InternalGeoLine.reduce(InternalGeoLine.java:100)
  1>    at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:166)
  1>    at org.elasticsearch.search.aggregations.InternalAggregations.topLevelReduce(InternalAggregations.java:115)
  1>    at org.elasticsearch.action.search.SearchPhaseController.reduceAggs(SearchPhaseController.java:486)
  1>    at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:474)
  1>    at org.elasticsearch.action.search.QueryPhaseResultConsumer.reduce(QueryPhaseResultConsumer.java:141)
  1>    at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:109)
  1>    at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:95)
  1>    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  1>    ... 6 more
  1> "
  1>       },
  1>       "status" : 500
  1>     }
  1>   }
  1> }]
```

**Comment by cbuescher** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/65473
