### ISSUE TITLE
Rollup cleanup leaves dangling task

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#65444]
The `RollupDateHistoUpgradeIT#testDateHistoIntervalUpgrade` test is not properly cleaning itself up, resulting in mixed-cluster tests failing across the suite since ESRestTestCase is unsuccessful at cleaning up.

**Build scan**:

https://gradle-enterprise.elastic.co/s/kbu2di3pqr2ok
'
**Repro line**:

```
./gradlew ':x-pack:qa:rolling-upgrade:v7.10.1#twoThirdsUpgradedTest' --tests "org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.test {p0=mixed_cluster/30_ml_jobs_crud/Test get old cluster job}" -Dtests.seed=1358107A42B0A7EE -Dtests.security.manager=true -Dtests.locale=en-GB -Dtests.timezone=America/Lima -Druntime.java=8 -Dtests.rest.suite=mixed_cluster
```

**Reproduces locally?**:

no

**Applicable branches**:

7.11

**Failure excerpt**:

```
{time_in_queue=576ms, time_in_queue_millis=576, source=update task state [rollup-id-test], executing=false, priority=NORMAL, insert_order=250}
	at __randomizedtesting.SeedInfo.seed([1358107A42B0A7EE:9B0C2FA0EC4CCA16]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.elasticsearch.test.rest.ESRestTestCase.lambda$waitForClusterStateUpdatesToFinish$12(ESRestTestCase.java:976)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1011)
	at org.elasticsearch.test.rest.ESRestTestCase.waitForClusterStateUpdatesToFinish(ESRestTestCase.java:967)
	at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:341)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.AssertionError: there are still running tasks:
{time_in_queue=4.3s, time_in_queue_millis=4373, source=update task state [rollup-id-test], executing=true, priority=NORMAL, insert_order=212}
{time_in_queue=3.3s, time_in_queue_millis=3390, source=update task state [rollup-id-test], executing=false, priority=NORMAL, insert_order=213}
{time_in_queue=2.3s, time_in_queue_millis=2352, source=update task state [rollup-id-test], executing=false, priority=NORMAL, insert_order=214}
{time_in_queue=376ms, time_in_queue_millis=376, source=update task state [rollup-id-test], executing=false, priority=NORMAL, insert_order=216}
{time_in_queue=1.3s, time_in_queue_millis=1373, source=update task state [rollup-id-test], executing=false, priority=NORMAL, insert_order=215}
		at org.junit.Assert.fail(Assert.java:88)
		at org.elasticsearch.test.rest.ESRestTestCase.lambda$waitForClusterStateUpdatesToFinish$12(ESRestTestCase.java:976)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:999)
		... 36 more
	Suppressed: java.lang.AssertionError: there are still running tasks:
```

**Failure history**:

**Comment by salvatore-campagna** [comment]
My understanding is that this issue is happening in a mixed cluster test involving both nodes with version 6.x and 7.x.
We are on version 8.x now and testing for BWC in mixed clusters with nodes running versions 7.x and 8.x.
I understand also that the cleanup job api was not available in version 6.x. If that is the case, probably the pending jobs are jobs that couldn't be cleaned up on a node running version 6.x.

Moreover, if we do not run mixed cluster tests against 6.x anymore, it means we can close this. Also considering that we don't see any recent failure.

**Comment by csoulios** [comment]
@salvatore-campagna +1 to closing this issue
