### ISSUE TITLE
[CI] LicenseHeadersPrecommitPluginFuncTest fail on windows

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#65456]
**Build scan**:
https://gradle-enterprise.elastic.co/s/tvrvtasuq6eaw/tests/:build-tools:integTest/org.elasticsearch.gradle.internal.precommit.LicenseHeadersPrecommitPluginFuncTest/detects%20invalid%20files%20with%20invalid%20license%20header?expanded-stacktrace=WyIwIl0

**Failure excerpt**:

```
java.lang.StringIndexOutOfBoundsException: begin -1, end 104, length 104
   at java.lang.String.checkBoundsBeginEnd(String.java:3756)
   at java.lang.String.substring(String.java:1902)
   at java.lang.String.substring(String.java:1875)
   at org.elasticsearch.gradle.internal.precommit.LicenseHeadersPrecommitPluginFuncTest.packageString(LicenseHeadersPrecommitPluginFuncTest.groovy:141)
```

**Comment by nik9000** [comment]
Looks like a `/` vs `\` in the path issue.
