### ISSUE TITLE
[CI] RecoveryIT test failing during 7.11 rolling upgrade tests

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#65465]
This test just started failing today. I'm seeing it primarily happen in PR builds so far.

**Build scan**:
https://gradle-enterprise.elastic.co/s/j7hi44os2jex4/tests/:qa:rolling-upgrade:v7.11.0%23oneThirdUpgradedTest/org.elasticsearch.upgrades.RecoveryIT/testRelocationWithConcurrentIndexing#1

**Repro line**:
`./gradlew ':qa:rolling-upgrade:v7.11.0#oneThirdUpgradedTest' --tests "org.elasticsearch.upgrades.RecoveryIT.testRelocationWithConcurrentIndexing" -Dtests.seed=418251B2617A62C9 -Dtests.security.manager=true -Dtests.locale=zh-Hans-CN -Dtests.timezone=Africa/Dar_es_Salaam -Dtests.distribution=default -Druntime.java=11`

**Reproduces locally?**:
This actually did reproduce locally for me, but with a slightly different error.
https://gradle-enterprise.elastic.co/s/yheut5dwzyx4y/tests/:qa:rolling-upgrade:v7.11.0%23oneThirdUpgradedTest/org.elasticsearch.upgrades.RecoveryIT/testRelocationWithConcurrentIndexing#1

**Applicable branches**:
`master`

**Failure history**:

https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.upgrades.RecoveryIT&tests.sortField=FAILED&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.upgrades.RecoveryIT > testAutoExpandIndicesDuringRollingUpgrade FAILED
    java.lang.AssertionError: expected:<0> but was:<1>
        at __randomizedtesting.SeedInfo.seed([418251B2617A62C9:563BAB18371D695C]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.elasticsearch.upgrades.RecoveryIT.testAutoExpandIndicesDuringRollingUpgrade(RecoveryIT.java:715)
REPRODUCE WITH: ./gradlew ':qa:rolling-upgrade:v7.11.0#oneThirdUpgradedTest' --tests "org.elasticsearch.upgrades.RecoveryIT.testAutoExpandIndicesDuringRollingUpgrade" -Dtests.seed=418251B2617A62C9 -Dtests.security.manager=true -Dtests.locale=zh-Hans-CN -Dtests.timezone=Africa/Dar_es_Salaam -Dtests.distribution=default -Druntime.java=11

org.elasticsearch.upgrades.RecoveryIT > testClosedIndexNoopRecovery FAILED
    java.lang.AssertionError: must find replica
        at __randomizedtesting.SeedInfo.seed([418251B2617A62C9:EDB04A36880F800D]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.elasticsearch.upgrades.RecoveryIT.assertNoopRecoveries(RecoveryIT.java:631)
        at org.elasticsearch.upgrades.RecoveryIT.testClosedIndexNoopRecovery(RecoveryIT.java:498)
REPRODUCE WITH: ./gradlew ':qa:rolling-upgrade:v7.11.0#oneThirdUpgradedTest' --tests "org.elasticsearch.upgrades.RecoveryIT.testClosedIndexNoopRecovery" -Dtests.seed=418251B2617A62C9 -Dtests.security.manager=true -Dtests.locale=zh-Hans-CN -Dtests.timezone=Africa/Dar_es_Salaam -Dtests.distribution=default -Druntime.java=11

org.elasticsearch.upgrades.RecoveryIT > testRecoveryWithConcurrentIndexing FAILED
    java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
        at __randomizedtesting.SeedInfo.seed([418251B2617A62C9:C1D395E1E3DEBC03]:0)
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:458)
        at org.elasticsearch.upgrades.RecoveryIT.testRecoveryWithConcurrentIndexing(RecoveryIT.java:162)
REPRODUCE WITH: ./gradlew ':qa:rolling-upgrade:v7.11.0#oneThirdUpgradedTest' --tests "org.elasticsearch.upgrades.RecoveryIT.testRecoveryWithConcurrentIndexing" -Dtests.seed=418251B2617A62C9 -Dtests.security.manager=true -Dtests.locale=zh-Hans-CN -Dtests.timezone=Africa/Dar_es_Salaam -Dtests.distribution=default -Druntime.java=11
```

**Comment by nik9000** [comment]
> This actually did reproduce locally for me, but with a slightly different error.
> https://gradle-enterprise.elastic.co/s/yheut5dwzyx4y/tests/:qa:rolling-upgrade:v7.11.0%23oneThirdUpgradedTest/org.elasticsearch.upgrades.RecoveryIT/testRelocationWithConcurrentIndexing#1

The reproduction lines for rolling upgrade tests are garbage. I think a more appropriate reproduction for this would be:
```
./gradlew ':qa:rolling-upgrade:v7.11.0#bwcTest' -Dtests.class="org.elasticsearch.upgrades.RecoveryIT" -Dtests.seed=418251B2617A62C9
```

I'll look more.

**Comment by mark-vieira** [comment]
:+1: we should revert to the "old" convention for bwc tests. I'll take a look at that.

**Comment by nik9000** [comment]
You can't really even output the test name - or the task name. It has to be `bwcTest` and it has to be just the class name. Without that you might not end up with the right state.

**Comment by mark-vieira** [comment]
You can do the task name, as the build will ensure the upstream dependencies run. It just won't do the later stages w/ shouldn't matter if we expect it to below up at this particular step. I'm, testing a local fix now.

The only scenario in which this won't work is if the BWC tests depend on some other tests also doing setup work in the upstream steps. There's no way to know and you can always remove the filter. Probably better to default to the optimal case for reproductions and make this scenario less annoying by default.

**Comment by nik9000** [comment]
> You can do the task name, as the build will ensure the upstream dependencies run.

I think I used to know that and then forgot. Thanks!

**Comment by nik9000** [comment]
This looks to be an problem forming the cluster. The console log has such wonders as:
```
» WARN ][o.e.t.InboundHandler     ] [v7.11.0-1] Failed to deserialize response from [127.0.0.1/127.0.0.1:33831]
»  org.elasticsearch.transport.TransportSerializationException: Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$6/[cluster:monitor/nodes/info[n]]:org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1@7b9b7121]
»  	at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:237) [elasticsearch-7.11.0-SNAPSHOT.jar:7.11.0-SNAPSHOT]
»  	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:133) [elasticsearch-7.11.0-SNAPSHOT.jar:7.11.0-SNAPSHOT]
»  	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:89) [elasticsearch-7.11.0-SNAPSHOT.jar:7.11.0-SNAPSHOT]
»  	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:700) [elasticsearch-7.11.0-SNAPSHOT.jar:7.11.0-SNAPSHOT]
»  	at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142) [elasticsearch-7.11.0-SNAPSHOT.jar:7.11.0-SNAPSHOT]
»  	at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117) [elasticsearch-7.11.0-SNAPSHOT.jar:7.11.0-SNAPSHOT]
»  	at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82) [elasticsearch-7.11.0-SNAPSHOT.jar:7.11.0-SNAPSHOT]
»  	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) [transport-netty4-client-7.11.0-SNAPSHOT.jar:7.11.0-SNAPSHOT]
»  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
»  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
»  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
»  	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271) [netty-handler-4.1.49.Final.jar:4.1.49.Final]
»  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
»  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
»  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
»  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
»  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
»  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
»  	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
»  	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
»  	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
»  	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
»  	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
»  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
»  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]
»  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]
»  	at java.lang.Thread.run(Thread.java:832) [?:?]
»  Caused by: java.lang.IllegalStateException: unexpected byte [0x0e]
»  	at org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:578) ~[elasticsearch-7.11.0-SNAPSHOT.jar:7.11.0-SNAPSHOT]
»  	at org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:568) ~[elasticsearch-7.11.0-SNAPSHOT.jar:7.11.0-SNAPSHOT]
»  	at org.elasticsearch.plugins.PluginInfo.<init>(PluginInfo.java:134) ~[elasticsearch-7.11.0-SNAPSHOT.jar:7.11.0-SNAPSHOT]
»  	at org.elasticsearch.common.io.stream.StreamInput.readCollection(StreamInput.java:1230) ~[elasticsearch-7.11.0-SNAPSHOT.jar:7.11.0-SNAPSHOT]
»  	at org.elasticsearch.common.io.stream.StreamInput.readList(StreamInput.java:1180) ~[elasticsearch-7.11.0-SNAPSHOT.jar:7.11.0-SNAPSHOT]
»  	at org.elasticsearch.action.admin.cluster.node.info.PluginsAndModules.<init>(PluginsAndModules.java:48) ~[elasticsearch-7.11.0-SNAPSHOT.jar:7.11.0-SNAPSHOT]
»  	at org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:1013) ~[elasticsearch-7.11.0-SNAPSHOT.jar:7.11.0-SNAPSHOT]
»  	at org.elasticsearch.action.admin.cluster.node.info.NodeInfo.<init>(NodeInfo.java:84) ~[elasticsearch-7.11.0-SNAPSHOT.jar:7.11.0-SNAPSHOT]
```

That hints to me that there was a wire incompatibility. I had a look around PluginInfo.java and found a7863808d9492b1ab129ba82b6861519f0be3941 which makes me think that we were building a snapshot that didn't have the commit that this was accounting for. Which explains why I can't reproduce it locally.
