### ISSUE TITLE
[CI] GeoLineAggregatorTests fails reproducibly

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#65470]
Looks like a new test.

**Build scan**:
https://gradle-enterprise.elastic.co/s/zgk3qlgvimij2/tests/:x-pack:plugin:spatial:test/org.elasticsearch.xpack.spatial.search.aggregations.GeoLineAggregatorTests/testMissingValues#1

**Repro line**:
`./gradlew ':x-pack:plugin:spatial:test' --tests "org.elasticsearch.xpack.spatial.search.aggregations.GeoLineAggregatorTests.testMissingValues" -Dtests.seed=2CE32AE9673FB527`

**Reproduces locally?**:
Yep, https://gradle-enterprise.elastic.co/s/c6rmpwnhsaj44

**Applicable branches**:
`master`, `7.x`

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.xpack.spatial.search.aggregations.GeoLineAggregatorTests&tests.sortField=FAILED&tests.test=testMissingValues&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.xpack.spatial.search.aggregations.GeoLineAggregatorTests > testMissingValues FAILED
    java.lang.ClassCastException: org.apache.lucene.index.ParallelCompositeReader cannot be cast to org.apache.lucene.index.DirectoryReader
        at __randomizedtesting.SeedInfo.seed([2CE32AE9673FB527:467E78AF43B581D6]:0)
        at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals$FieldData.globalOrdinalsValues(ValuesSource.java:218)
        at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals.globalMaxOrd(ValuesSource.java:191)
        at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.getMaxOrd(TermsAggregatorFactory.java:295)
        at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.access$000(TermsAggregatorFactory.java:52)
        at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory$1.build(TermsAggregatorFactory.java:97)
        at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.doCreateInternal(TermsAggregatorFactory.java:244)
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:48)
        at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:79)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.createAggregator(AggregatorTestCase.java:220)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:412)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:372)
        at org.elasticsearch.xpack.spatial.search.aggregations.GeoLineAggregatorTests.testCase(GeoLineAggregatorTests.java:221)
        at org.elasticsearch.xpack.spatial.search.aggregations.GeoLineAggregatorTests.testCase(GeoLineAggregatorTests.java:201)
        at org.elasticsearch.xpack.spatial.search.aggregations.GeoLineAggregatorTests.testMissingValues(GeoLineAggregatorTests.java:83)```

**Comment by mark-vieira** [comment]
@talevy looks you recently authored this test. Mind taking a look?

**Comment by talevy** [comment]
eek, yeah. thanks @mark-vieira. on it. second time this lucene issue got me. shame on me!

opened a PR for this
