### ISSUE TITLE
Forbid updating index.blocks.write to false for searchable snapshots index

### ISSUE THREAD

**Issue by gaobinlong** [elastic/elasticsearch#65566]
**Elasticsearch version**: master

**Plugins installed**: []

**JVM version (java -version)**: 14.0.1

**OS version (uname -a if on a Unix-like system)**: Mac OS 10.13.6

**Description of the problem including expected versus actual behavior**:

The setting  'index.blocks.write` of searchable snapshots index  defaults to `true`, but when we update it to `false`, and execute indexing API, then the es process crash.

Should we forbid updating index.blocks.write to false  for searchable snapshots index?

**Steps to reproduce**:
1. PUT test/_settings
```
"index.blocks.write": false
```
2. POST test/_doc

```
"a":1
```

**Provide logs (if relevant)**:

```
[2020-11-27T10:30:11,433][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node1] fatal error in thread [elasticsearch[node1][write][T#2]], exiting
java.lang.AssertionError: this should not be called
	at org.elasticsearch.index.engine.ReadOnlyEngine.index(ReadOnlyEngine.java:258) ~[classes/:?]
	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:865) ~[classes/:?]
	at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:837) ~[classes/:?]
	at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:802) ~[classes/:?]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:290) ~[classes/:?]
	at org.elasticsearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:179) ~[classes/:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:733) ~[classes/:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by DaveCTurner** [comment]
From the report this sounds like a bad blocker, but on closer inspection it doesn't affect production at all so I've removed the `blocker` label. The reported behaviour only happens if you have assertions enabled (i.e. you're running tests). In production we throw a `UnsupportedOperationException`, rejecting the indexing request but not failing the node:

https://github.com/elastic/elasticsearch/blob/68b546557544ff671ab0ed005318fc60fa3165bd/server/src/main/java/org/elasticsearch/index/engine/ReadOnlyEngine.java#L259-L263

We could certainly enhance the UX in this area. @gaobinlong would you be interested in opening a PR to address this?

**Comment by gaobinlong** [comment]
@DaveCTurner , thanks for your explanation, I'm glad to open a PR for this issue.
