### ISSUE TITLE
[CI] UncaughtExceptionError for AssertionError in IndexShard getTimestampMillisRange

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#65713]
**Build scan**:
* https://gradle-enterprise.elastic.co/s/lkbq4k3nc7kdm
* https://gradle-enterprise.elastic.co/s/oayikqrvplwkw
* https://gradle-enterprise.elastic.co/s/4kisrgnxsynno

**Repro line**:
> ./gradlew ':server:test' --tests "org.elasticsearch.indices.IndicesServiceTests.testDanglingIndicesWithAliasConflict" -Dtests.seed=499B2F4054F1673A -Dtests.security.manager=true -Dtests.locale=ja -Dtests.timezone=America/Nipigon -Druntime.java=11 -Dtests.fips.enabled=true

**Reproduces locally?**:
No

**Applicable branches**:
master

**Failure history**:
Two different test methods, `IndicesServiceTests  testDanglingIndicesWithAliasConflict` and `DataStreamIT 
 testCreatingDataStreamAndFirstBackingIndexExistsFails`, failed at the same underlying assertion in `IndexShard getTimestampMillisRange`. I was going to let them pass because they feel like tests were running slow. But then I noticed that the `getTimestampMillisRange` method was just added (within 24 hours?) and it failed at least 3 times. Not sure if there are more because it is a bit difficult to filter for it. The [AssertionError](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/shard/IndexShard.java#L1723) does not generate any paritcular error message. It would be helpful if it is something like:
`assert isReadAllowed() : "Read is not allowed for state: " + state.name();`.

**Failure excerpt**:
```
org.elasticsearch.indices.IndicesServiceTests > testDanglingIndicesWithAliasConflict FAILED
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=224, name=elasticsearch[node_s_0][generic][T#1], state=RUNNABLE, group=TGRP-IndicesServiceTests]
        at __randomizedtesting.SeedInfo.seed([499B2F4054F1673A:60A48E5604E3C74D]:0)

        Caused by:
        java.lang.AssertionError
            at __randomizedtesting.SeedInfo.seed([499B2F4054F1673A]:0)
            at org.elasticsearch.index.shard.IndexShard.getTimestampMillisRange(IndexShard.java:1723)
            at org.elasticsearch.index.shard.IndexShard.lambda$executeRecovery$19(IndexShard.java:2674)
            at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:128)
            at org.elasticsearch.index.shard.StoreRecovery.lambda$recoveryListener$5(StoreRecovery.java:332)
            at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:128)
            at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:351)
            at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:94)
            at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1936)
            at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73)
            at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:733)
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by DaveCTurner** [comment]
Oh dear, yes, I don't think this assertion is valid at all, the shard could also be in state `CLOSED` too.

I opened #65720 to fix this.
