### ISSUE TITLE
Regression: "java.lang.VerifyError: Bad type on operand stack" when using null-safe on a parameter

### ISSUE THREAD

**Issue by AndyHunt66** [elastic/elasticsearch#65728]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.0

**JVM version** (`java -version`): openjdk-11.0.2_linux-x64_bin

**OS version** (`uname -a` if on a Unix-like system): Linux ahunt11 5.4.0-54-generic #60~18.04.1-Ubuntu SMP Fri Nov 6 17:25:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
**Description**:
In a stored script, if you pass a parameter to a subroutine, and use the null-safe operator in that parameter, adding that script to a pipeline fails at compile time with `Bad type on operand stack`

**Steps to reproduce:**
```
POST _scripts/test-script
{
  "script":{
    "lang":"painless",
    "source":"""
     boolean istrue( String containerName){
         return true;
         }
         
      if(istrue(ctx.fieldname?.name )) {
        def bob = true;
      }
      """
  }
}
```

```
PUT _ingest/pipeline/my-pipeline-id
{
  "description": "test-pipeline",
  "processors": [
    {
      "script": {
        "id": "test-script",
        "tag": "test-script"
      }
    }
  ]
}
```

Expected behaviour : Pipeline is created
Observed behaviour:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "script_exception",
        "reason" : "compile error",
        "processor_type" : "script",
        "processor_tag" : "test-script",
        "script_stack" : [ ],
        "script" : "\n     boolean istrue( String containerName){\n         return true;\n         }\n         \n      \n      if(istrue(ctx.fieldname?.name )) {\n        def bob = true;\n      }\n      ",
        "lang" : "painless"
      }
    ],
    "type" : "script_exception",
    "reason" : "compile error",
    "processor_type" : "script",
    "processor_tag" : "test-script",
    "script_stack" : [ ],
    "script" : "\n     boolean istrue( String containerName){\n         return true;\n         }\n         \n      \n      if(istrue(ctx.fieldname?.name )) {\n        def bob = true;\n      }\n      ",
    "lang" : "painless",
    "caused_by" : {
      "type" : "verify_error",
      "reason" : "Bad type on operand stack\nException Details:\n  Location:\n    org/elasticsearch/painless/PainlessScript$Script.execute(Ljava/util/Map;)V @20: invokestatic\n  Reason:\n    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'java/lang/String'\n  Current Frame:\n    bci: @20\n    flags: { }\n    locals: { 'org/elasticsearch/painless/PainlessScript$Script', 'java/util/Map', integer }\n    stack: { 'java/lang/Object' }\n  Bytecode:\n    0000000: 1219 3d2b 1227 b900 2d02 0059 c600 08ba\n    0000010: 0038 0000 b800 3a99 0008 04b8 0040 4eb1\n    0000020: 0000 bf4e 2a2d 2db2 0042 b600 48b6 004c\n    0000030: bf4e 2a2d b800 52b6 004c bf4e 2a2d b800\n    0000040: 52b6 004c bf4e 2a2d b800 52b6 004c bf4e\n    0000050: 2a2d b800 52b6 004c bf4e 2a2d b800 52b6\n    0000060: 004c bf                                \n  Exception Handler Table:\n    bci [3, 32] => handler: 35\n    bci [3, 32] => handler: 49\n    bci [3, 32] => handler: 59\n    bci [3, 32] => handler: 69\n    bci [3, 32] => handler: 79\n    bci [3, 32] => handler: 89\n  Stackmap Table:\n    full_frame(@20,{Object[#2],Object[#41],Integer},{Object[#94]})\n    same_frame(@31)\n    full_frame(@32,{},{Object[#96]})\n    full_frame(@35,{Object[#2],Object[#41],Integer},{Object[#68]})\n    same_locals_1_stack_item_frame(@49,Object[#84])\n    same_locals_1_stack_item_frame(@59,Object[#86])\n    same_locals_1_stack_item_frame(@69,Object[#88])\n    same_locals_1_stack_item_frame(@79,Object[#90])\n    same_locals_1_stack_item_frame(@89,Object[#92])\n"
    }
  },
  "status" : 400
}
```

**Workaround:** 
Instead of using `?.` wrap the subroutine call in protective null checks:
```
     if ((ctx.fieldname != null) && (ctx.fieldname.name != null)  )
      {
        if(istrue(ctx.fieldname.name )) {
        def bob = true;
        }
      }
```

ES Log shows:
```
[2020-12-02T09:00:43,453][WARN ][o.e.i.IngestService      ] [ahunt11] failed to update ingest pipelines
org.elasticsearch.ElasticsearchParseException: Error updating pipeline with id [my-pipeline-id]
	at org.elasticsearch.ingest.IngestService.innerUpdatePipelines(IngestService.java:777) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.ingest.IngestService.applyClusterState(IngestService.java:710) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:510) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:501) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:471) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:418) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:68) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:162) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.10.0.jar:7.10.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.elasticsearch.script.ScriptException: compile error
	at org.elasticsearch.painless.PainlessScriptEngine.convertToScriptException(PainlessScriptEngine.java:506) ~[?:?]
	at org.elasticsearch.painless.PainlessScriptEngine.compile(PainlessScriptEngine.java:417) ~[?:?]
	at org.elasticsearch.painless.PainlessScriptEngine.compile(PainlessScriptEngine.java:145) ~[?:?]
	at org.elasticsearch.script.ScriptCache.lambda$compile$0(ScriptCache.java:110) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.common.cache.Cache.computeIfAbsent(Cache.java:433) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.script.ScriptCache.compile(ScriptCache.java:99) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.script.ScriptService.compile(ScriptService.java:384) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.ingest.common.ScriptProcessor$Factory.create(ScriptProcessor.java:138) ~[?:?]
	at org.elasticsearch.ingest.common.ScriptProcessor$Factory.create(ScriptProcessor.java:117) ~[?:?]
	at org.elasticsearch.ingest.ConfigurationUtils.readProcessor(ConfigurationUtils.java:430) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.ingest.ConfigurationUtils.readProcessor(ConfigurationUtils.java:399) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.ingest.ConfigurationUtils.readProcessorConfigs(ConfigurationUtils.java:337) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.ingest.Pipeline.create(Pipeline.java:74) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.ingest.IngestService.innerUpdatePipelines(IngestService.java:735) ~[elasticsearch-7.10.0.jar:7.10.0]
	... 13 more
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/elasticsearch/painless/PainlessScript$Script.execute(Ljava/util/Map;)V @20: invokestatic
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'java/lang/String'
  Current Frame:
    bci: @20
    flags: { }
    locals: { 'org/elasticsearch/painless/PainlessScript$Script', 'java/util/Map', integer }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: 1219 3d2b 1227 b900 2d02 0059 c600 08ba
    0000010: 0038 0000 b800 3a99 0008 04b8 0040 4eb1
    0000020: 0000 bf4e 2a2d 2db2 0042 b600 48b6 004c
    0000030: bf4e 2a2d b800 52b6 004c bf4e 2a2d b800
    0000040: 52b6 004c bf4e 2a2d b800 52b6 004c bf4e
    0000050: 2a2d b800 52b6 004c bf4e 2a2d b800 52b6
    0000060: 004c bf                                
  Exception Handler Table:
    bci [3, 32] => handler: 35
    bci [3, 32] => handler: 49
    bci [3, 32] => handler: 59
    bci [3, 32] => handler: 69
    bci [3, 32] => handler: 79
    bci [3, 32] => handler: 89
  Stackmap Table:
    full_frame(@20,{Object[#2],Object[#41],Integer},{Object[#94]})
    same_frame(@31)
    full_frame(@32,{},{Object[#96]})
    full_frame(@35,{Object[#2],Object[#41],Integer},{Object[#68]})
    same_locals_1_stack_item_frame(@49,Object[#84])
    same_locals_1_stack_item_frame(@59,Object[#86])
    same_locals_1_stack_item_frame(@69,Object[#88])
    same_locals_1_stack_item_frame(@79,Object[#90])
    same_locals_1_stack_item_frame(@89,Object[#92])

	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3062) ~[?:?]
	at java.lang.Class.getField0(Class.java:3247) ~[?:?]
	at java.lang.Class.getField(Class.java:1998) ~[?:?]
	at org.elasticsearch.painless.Compiler.compile(Compiler.java:235) ~[?:?]
	at org.elasticsearch.painless.PainlessScriptEngine$2.run(PainlessScriptEngine.java:412) ~[?:?]
	at org.elasticsearch.painless.PainlessScriptEngine$2.run(PainlessScriptEngine.java:408) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.elasticsearch.painless.PainlessScriptEngine.compile(PainlessScriptEngine.java:408) ~[?:?]
	at org.elasticsearch.painless.PainlessScriptEngine.compile(PainlessScriptEngine.java:145) ~[?:?]
	at org.elasticsearch.script.ScriptCache.lambda$compile$0(ScriptCache.java:110) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.common.cache.Cache.computeIfAbsent(Cache.java:433) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.script.ScriptCache.compile(ScriptCache.java:99) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.script.ScriptService.compile(ScriptService.java:384) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.ingest.common.ScriptProcessor$Factory.create(ScriptProcessor.java:138) ~[?:?]
	at org.elasticsearch.ingest.common.ScriptProcessor$Factory.create(ScriptProcessor.java:117) ~[?:?]
	at org.elasticsearch.ingest.ConfigurationUtils.readProcessor(ConfigurationUtils.java:430) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.ingest.ConfigurationUtils.readProcessor(ConfigurationUtils.java:399) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.ingest.ConfigurationUtils.readProcessorConfigs(ConfigurationUtils.java:337) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.ingest.Pipeline.create(Pipeline.java:74) ~[elasticsearch-7.10.0.jar:7.10.0]
	at org.elasticsearch.ingest.IngestService.innerUpdatePipelines(IngestService.java:735) ~[elasticsearch-7.10.0.jar:7.10.0]
	... 13 more
```
**Note:** This does not reproduce in 7.9.1

**Comment by stu-elastic** [comment]
Needs to verify this has been fixed by some recent SDHs, @jdconrad will update with details.

**Comment by rjernst** [comment]
This has been open for quite a while and we haven't seen any more reports of it. For now I'm going to close. We can re-open later if needed.
