### ISSUE TITLE
[CI] TranslogTests.testTotalTests yet another reproducible failure

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#65885]
**Repro line**:
```
./gradlew ':server:test' --tests "org.elasticsearch.index.translog.TranslogTests.testTotalTests" -Dtests.seed=982F99B53EB91EB8 -Dtests.security.manager=true -Dtests.locale=es-PE -Dtests.timezone=Asia/Singapore -Druntime.java=11
```
**Reproduces locally?**:
yes
**Applicable branches**:
master
**Failure excerpt**:
```
org.elasticsearch.index.translog.TranslogTests > testTotalTests FAILED
    java.lang.AssertionError: 
    Expected: <9223372036854775807L>
         but: was <0L>
        at __randomizedtesting.SeedInfo.seed([982F99B53EB91EB8:BE28292155CCC8E8]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.index.translog.TranslogTests.testTotalTests(TranslogTests.java:545)
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.index.translog.TranslogTests.testTotalTests" -Dtests.seed=982F99B53EB91EB8 -Dtests.security.manager=true -Dtests.locale=es-PE -Dtests.timezone=Asia/Singapore -Druntime.java=11

Suite: Test class org.elasticsearch.index.translog.TranslogTests
  1> [2020-12-04T22:10:02,391][INFO ][o.e.i.t.TranslogTests    ] [testTotalTests] before test
  1> [2020-12-04T22:10:02,675][INFO ][o.e.i.t.TranslogTests    ] [testTotalTests] after test
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.index.translog.TranslogTests.testTotalTests" -Dtests.seed=982F99B53EB91EB8 -Dtests.security.manager=true -Dtests.locale=es-PE -Dtests.timezone=Asia/Singapore -Druntime.java=11
  2> java.lang.AssertionError: 
    Expected: <9223372036854775807L>
         but: was <0L>
        at __randomizedtesting.SeedInfo.seed([982F99B53EB91EB8:BE28292155CCC8E8]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.index.translog.TranslogTests.testTotalTests(TranslogTests.java:545)
  2> NOTE: leaving temporary files on disk at: /home/hendrik/work/git-elastic/elasticsearch/server/build/testrun/test/temp/org.elasticsearch.index.translog.TranslogTests_982F99B53EB91EB8-003
  2> NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=335, maxMBSortInHeap=5.125415833398529, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=es-PE, timezone=Asia/Singapore
  2> NOTE: Linux 5.4.0-56-generic amd64/Oracle Corporation 11 (64-bit)/cpus=16,threads=1,free=462671928,total=536870912
  2> NOTE: All tests run in this JVM: [TranslogTests]

```

**Comment by dnhatn** [comment]
Did the test fail with the latest master? I think we fixed this failure in https://github.com/elastic/elasticsearch/pull/65632.
