### ISSUE TITLE
7.10 mixed cluster BWC tests are failing

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#65907]
The introduction of https://github.com/elastic/elasticsearch/pull/65490 (earlier today) causes bwc de-serialization when executed in a mixed cluster with 7.10.1-SNAPSHOT ( and any prior 7.x, I assume). BWC with 7.11.0 seems fine. 

Checkout 7.10 branch
`./gradlew ':qa:mixed-cluster:v6.8.14#mixedClusterTest' --info`
ignore the errors found in the output for the tests, and look at the server logs (i.e. `cat ./qa/mixed-cluster/build/testclusters/v6.8.14-1/logs/es.stdout.log` )

Note - the actual errors from the tests are misleading. The error manifests in different ways, but in general is the root cause of the errors are due to looking up node version information via node stats a failure of deserilization between 7.10 and 6.8.14. I have only included what i believe are the relevant error from the server, and intentionally left out the numerous misleading test failures stack traces.  

In a mixed cluster the 7.10.1-SNAPSHOT node errors (note the `v6.8.14-1` is the name of the node and initial version of the node. the mixed cluster tests upgrade the nodes in place and this message happens AFTER the node is upgraded to 7.10.1)

```
[2020-12-04T17:36:35,050][WARN ][o.e.t.InboundHandler     ] [v6.8.14-1] Failed to deserialize response from [127.0.0.1/127.0.0.1:36585]
org.elasticsearch.transport.TransportSerializationException: Failed to deserialize response from handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.transport.TransportService$6/[cluster:monitor/nodes/info[n]]:org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1@5a5466d2]
	at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:237) [elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:133) [elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:89) [elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:700) [elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142) [elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117) [elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82) [elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) [transport-netty4-client-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271) [netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.io.IOException: Invalid string; unexpected character: 243 hex: f3
	at org.elasticsearch.common.io.stream.StreamInput.throwOnBrokenChar(StreamInput.java:532) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.common.io.stream.StreamInput.readString(StreamInput.java:491) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.plugins.PluginInfo.<init>(PluginInfo.java:97) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.common.io.stream.StreamInput.readCollection(StreamInput.java:1220) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.common.io.stream.StreamInput.readList(StreamInput.java:1170) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.action.admin.cluster.node.info.PluginsAndModules.<init>(PluginsAndModules.java:48) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:1003) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.action.admin.cluster.node.info.NodeInfo.<init>(NodeInfo.java:84) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.action.admin.cluster.node.info.TransportNodesInfoAction.newNodeResponse(TransportNodesInfoAction.java:66) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.action.admin.cluster.node.info.TransportNodesInfoAction.newNodeResponse(TransportNodesInfoAction.java:38) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.read(TransportNodesAction.java:221) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.read(TransportNodesAction.java:218) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.transport.TransportService$6.read(TransportService.java:650) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.transport.TransportService$6.read(TransportService.java:630) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1162) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1149) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:234) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
	... 26 more
```

PluginInfo.java:97 is the following line:

```
   javaVersion = in.readString();
```

Nothing specifically changed here, however, I believe that this information can be sourced from the plugin descriptor. https://github.com/elastic/elasticsearch/pull/65490 introduces some changes to the plugin infrastructure so that is the leading theory to as the relevant change causing this issue. 

Once this issue is resolved we should also double check that serialization from 5.x is working properly as well no regressions with 7.11+

Also, chose not to revert the commit in 6.x to avoid complicating this issue since there is supporting code in both master and 7.11.

**Comment by pugnascotia** [comment]
I reverted serialising the `licensed` in `6.8` in e6276e8c28b, and removed the expectation that `6.8` would do this 7.x in 2ee4a550819, so we'll see if that fixes the issue.

**Comment by pugnascotia** [comment]
This test now passes in the `7.10` branch.

**Comment by pugnascotia** [comment]
I'm pretty sure I fixed this in the end.
