### ISSUE TITLE
"Setting upgrade_mode to enabled" yml test failing in 7.x and master

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#65947]
**Build scan**:

https://gradle-enterprise.elastic.co/s/7adiokzxinsqg

**Repro line**:

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:yamlRestTest' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=ml/set_upgrade_mode/Setting upgrade_mode to enabled}" \
  -Dtests.seed=DE059F860BFE3AA5 \
  -Dtests.security.manager=true \
  -Dtests.locale=et-EE \
  -Dtests.timezone=Asia/Jerusalem \
  -Druntime.java=8 \
  -Dtests.rest.blacklist=getting_started/10_monitor_cluster_health/*

REPRODUCE WITH: ./gradlew ':x-pack:plugin:yamlRestTest' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=ml/set_upgrade_mode/Setting upgrade_mode to enabled}" \
  -Dtests.seed=DE059F860BFE3AA5 \
  -Dtests.security.manager=true \
  -Dtests.locale=et-EE \
  -Dtests.timezone=Asia/Jerusalem \
  -Druntime.java=8 \
  -Dtests.rest.blacklist=getting_started/10_monitor_cluster_health/*
```

**Reproduces locally?**:

No

**Applicable branches**:

`7.x` `master`

**Failure history**:

Test failures that could be related to this problem started on Dec 4.

**Failure excerpt**:

Not very informative, need to look into server logs.

```
14:25:47 org.elasticsearch.xpack.test.rest.XPackRestIT > test {p0=ml/set_upgrade_mode/Setting upgrade_mode to enabled} FAILED
14:25:47     java.lang.RuntimeException: Had to resort to force-closing jobs, something went wrong?
14:25:47         at __randomizedtesting.SeedInfo.seed([DE059F860BFE3AA5:5651A05CA502575D]:0)
14:25:47         at org.elasticsearch.xpack.core.ml.integration.MlRestTestStateCleaner.deleteAllJobs(MlRestTestStateCleaner.java:86)
14:25:47         at org.elasticsearch.xpack.core.ml.integration.MlRestTestStateCleaner.clearMlMetadata(MlRestTestStateCleaner.java:31)
14:25:47         at org.elasticsearch.xpack.test.rest.AbstractXPackRestTest.clearMlState(AbstractXPackRestTest.java:226)
14:25:47         at org.elasticsearch.xpack.test.rest.AbstractXPackRestTest.cleanup(AbstractXPackRestTest.java:210)
14:25:47         at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
14:25:47         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:25:47         at java.lang.reflect.Method.invoke(Method.java:498)
14:25:47         at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
14:25:47         at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
14:25:47         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
14:25:47         at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
14:25:47         at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
14:25:47         at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
14:25:47         at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
14:25:47         at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
14:25:47         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
14:25:47         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
14:25:47         at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
14:25:47         at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
14:25:47         at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
14:25:47         at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
14:25:47         at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
14:25:47         at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
14:25:47         at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
14:25:47         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
14:25:47         at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
14:25:47         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
14:25:47         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
14:25:47         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
14:25:47         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
14:25:47         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
14:25:47         at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
14:25:47         at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
14:25:47         at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
14:25:47         at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
14:25:47         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
14:25:47         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
14:25:47         at java.lang.Thread.run(Thread.java:748)
14:25:47 
14:25:47         Caused by:
14:25:47         java.net.SocketTimeoutException: 60 000 milliseconds timeout on connection http-outgoing-1 [ACTIVE]
14:25:47             at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:864)
14:25:47             at org.elasticsearch.client.RestClient.performRequest(RestClient.java:283)
14:25:47             at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
14:25:47             at org.elasticsearch.xpack.core.ml.integration.MlRestTestStateCleaner.deleteAllJobs(MlRestTestStateCleaner.java:78)
14:25:47             ... 37 more
14:25:47 
14:25:47             Caused by:
14:25:47             java.net.SocketTimeoutException: 60 000 milliseconds timeout on connection http-outgoing-1 [ACTIVE]
14:25:47                 at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387)
14:25:47                 at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92)
14:25:47                 at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39)
14:25:47                 at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
14:25:47                 at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:261)
14:25:47                 at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:502)
14:25:47                 at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:211)
14:25:47                 at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
14:25:47                 at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
14:25:47                 at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
14:25:47                 ... 1 more

```

**Comment by benwtrent** [comment]
The earliest failures are indeed from back on dec 4th. Looking at the logs there is nothing interesting in the failures :/

The only difference is that the job seems to get re-assigned to a node and goes through the snapshot revert action path.
[yamlRestTest.log.zip](https://github.com/elastic/elasticsearch/files/5655260/yamlRestTest.log.zip)

Maybe related: https://github.com/elastic/elasticsearch/pull/65814

@dimitris-athanasiou could you look at the logs as well? This one is weird as nothing stands out to me

**Comment by przemekwitek** [comment]
> Looking at the logs there is nothing interesting in the failures :/

Yesterday I couldn't find anything interesting either. Possibly we are missing some logging.

**Comment by benwtrent** [comment]
what makes this even more strange, is that only this particular test is failing. 

There are other tests in the same file that enable and disable `upgrade_mode` that did not fail. All of them are VERY similar but only one of them failing is suspicious.

**Comment by benwtrent** [comment]
Looking over the test failure history, the test `"Setting upgrade mode to disabled from enabled":` had a similar amount of failures over the EXACT same time period. 

But, the failures ceased after December 7th.

Seeing if there is anything else that changed other than muting this other test. 

There may both may have failed due to the same factors, which ultimately resolved itself.

**Comment by jtibshirani** [comment]
We had a couple more failures pop up today:
* https://gradle-enterprise.elastic.co/s/tkcqo3sgagciu
* https://gradle-enterprise.elastic.co/s/52sss7voyxhj2

We could mute the test while it's being investigated?

**Comment by benwtrent** [comment]
Interesting logs from one of the recent failures:

```
[2021-02-16T22:18:48,060][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [yamlRestTest-0] Successfully set job state to [opened] for job [set-upgrade-mode-job]
[2021-02-16T22:18:48,184][INFO ][o.e.x.m.d.DatafeedJob    ] [yamlRestTest-0] [set-upgrade-mode-job] Datafeed started (from: 1970-01-01T00:00:00.000Z to: real-time) with frequency [600000ms]
[2021-02-16T22:18:48,186][INFO ][o.e.x.m.a.TransportSetUpgradeModeAction] [yamlRestTest-0] Starting to set [upgrade_mode] to [true] from [false]
[2021-02-16T22:18:48,186][TRACE][o.e.x.m.a.TransportSetUpgradeModeAction] [yamlRestTest-0] Executing cluster state update
[2021-02-16T22:18:48,226][TRACE][o.e.x.m.a.TransportSetUpgradeModeAction] [yamlRestTest-0] Cluster update response built: true
[2021-02-16T22:18:48,227][INFO ][o.e.x.m.a.TransportSetUpgradeModeAction] [yamlRestTest-0] Enabling upgrade mode, must isolate datafeeds
[2021-02-16T22:18:48,227][INFO ][o.e.x.m.a.TransportSetUpgradeModeAction] [yamlRestTest-0] Isolating datafeeds: [set-upgrade-mode-job-datafeed]
[2021-02-16T22:18:48,229][INFO ][o.e.x.m.a.TransportSetUpgradeModeAction] [yamlRestTest-0] Isolated the datafeeds
[2021-02-16T22:18:48,230][INFO ][o.e.x.m.a.TransportSetUpgradeModeAction] [yamlRestTest-0] Un-assigning persistent tasks : [ datafeed-set-upgrade-mode-job-datafeed, job-set-upgrade-mode-job ]
[2021-02-16T22:18:48,252][WARN ][o.e.x.m.MlAssignmentNotifier] [yamlRestTest-0] [set-upgrade-mode-job] No node found to start datafeed [set-upgrade-mode-job-datafeed]. Reasons [persistent task cannot be assigned while upgrade mode is enabled.]
[2021-02-16T22:18:48,260][INFO ][o.e.x.m.d.DatafeedManager] [yamlRestTest-0] [task has been removed, cancelling locally] attempt to stop datafeed [set-upgrade-mode-job-datafeed] [55]
[2021-02-16T22:18:48,261][INFO ][o.e.x.m.d.DatafeedManager] [yamlRestTest-0] [task has been removed, cancelling locally] attempt to stop datafeed [set-upgrade-mode-job-datafeed] for job [set-upgrade-mode-job]
[2021-02-16T22:18:48,261][INFO ][o.e.x.m.d.DatafeedManager] [yamlRestTest-0] [task has been removed, cancelling locally] try lock [0s] to stop datafeed [set-upgrade-mode-job-datafeed] for job [set-upgrade-mode-job]...
[2021-02-16T22:18:48,262][INFO ][o.e.x.m.d.DatafeedManager] [yamlRestTest-0] [task has been removed, cancelling locally] stopping datafeed [set-upgrade-mode-job-datafeed] for job [set-upgrade-mode-job], acquired [true]...
[2021-02-16T22:18:48,265][INFO ][o.e.x.m.d.DatafeedManager] [yamlRestTest-0] [task has been removed, cancelling locally] datafeed [set-upgrade-mode-job-datafeed] for job [set-upgrade-mode-job] has been stopped
[2021-02-16T22:18:48,287][INFO ][o.e.x.m.j.p.a.ProcessContext] [yamlRestTest-0] Killing job [set-upgrade-mode-job], because [task has been removed, cancelling locally]
[2021-02-16T22:18:48,290][INFO ][o.e.x.m.j.p.a.o.AutodetectResultProcessor] [yamlRestTest-0] [set-upgrade-mode-job] 0 buckets parsed from autodetect output
[2021-02-16T22:18:48,294][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [yamlRestTest-0] [controller/12786] [CDetachedProcessSpawner.cc@176] Child process with PID 60775 was terminated by signal 15
[2021-02-16T22:18:48,390][INFO ][o.e.x.m.a.TransportSetUpgradeModeAction] [yamlRestTest-0] Waited for tasks to be unassigned
[2021-02-16T22:18:48,390][INFO ][o.e.x.m.a.TransportSetUpgradeModeAction] [yamlRestTest-0] Completed upgrade mode request
[2021-02-16T22:18:48,413][INFO ][o.e.x.m.a.TransportSetUpgradeModeAction] [yamlRestTest-0] Starting to set [upgrade_mode] to [false] from [true]
[2021-02-16T22:18:48,414][TRACE][o.e.x.m.a.TransportSetUpgradeModeAction] [yamlRestTest-0] Executing cluster state update
[2021-02-16T22:18:48,435][TRACE][o.e.x.m.a.TransportSetUpgradeModeAction] [yamlRestTest-0] Cluster update response built: true
[2021-02-16T22:18:48,436][INFO ][o.e.x.m.a.TransportSetUpgradeModeAction] [yamlRestTest-0] Disabling upgrade mode, must wait for tasks to not have AWAITING_UPGRADE assignment
[2021-02-16T22:18:48,464][WARN ][o.e.x.m.MlAssignmentNotifier] [yamlRestTest-0] [set-upgrade-mode-job] No node found to start datafeed [set-upgrade-mode-job-datafeed]. Reasons [cannot start datafeed [set-upgrade-mode-job-datafeed], because the job's [set-upgrade-mode-job] state is stale]
[2021-02-16T22:18:48,467][INFO ][o.e.x.m.a.TransportSetUpgradeModeAction] [yamlRestTest-0] Done waiting for tasks to be out of AWAITING_UPGRADE
[2021-02-16T22:18:48,467][INFO ][o.e.x.m.a.TransportSetUpgradeModeAction] [yamlRestTest-0] Completed upgrade mode request
[2021-02-16T22:18:48,470][INFO ][o.e.x.m.j.t.OpenJobPersistentTasksExecutor] [yamlRestTest-0] [set-upgrade-mode-job] job has running datafeed task; reverting to current snapshot
[2021-02-16T22:18:48,474][INFO ][o.e.x.m.a.TransportRevertModelSnapshotAction] [yamlRestTest-0] Reverting to snapshot 'empty'
[2021-02-16T22:18:48,485][INFO ][o.e.x.m.a.TransportSetUpgradeModeAction] [yamlRestTest-0] Upgrade mode noop
[2021-02-16T22:18:48,533][INFO ][o.e.c.m.MetadataMappingService] [yamlRestTest-0] [.ml-anomalies-shared/NhfiATDWTqu0blrlGIN2cg] update_mapping [_doc]
[2021-02-16T22:18:48,614][INFO ][o.e.x.m.a.TransportRevertModelSnapshotAction] [yamlRestTest-0] [set-upgrade-mode-job] Removing intervening records after reverting model: deleting results after [1970-01-01T00:00:00.000+0000]
[2021-02-16T22:18:48,618][INFO ][o.e.x.m.a.TransportRevertModelSnapshotAction] [yamlRestTest-0] [set-upgrade-mode-job] Removing intervening annotations after reverting model: deleting annotations after [1970-01-01T00:00:00.000+0000]
[2021-02-16T22:18:48,620][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [yamlRestTest-0] Opening job [set-upgrade-mode-job]
[2021-02-16T22:18:48,624][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [yamlRestTest-0] [set-upgrade-mode-job] Loading model snapshot [N/A], job latest_record_timestamp [N/A]
[2021-02-16T22:18:49,157][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [yamlRestTest-0] [set-upgrade-mode-job] [autodetect/60996] [CResourceMonitor.cc@77] Setting model memory limit to 1024 MB
[2021-02-16T22:18:49,184][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [yamlRestTest-0] Successfully set job state to [opened] for job [set-upgrade-mode-job]
// See this 1 minute gap?!?!?!?!! Why?!!!!!!
[2021-02-16T22:19:48,783][INFO ][o.e.x.m.j.p.a.ProcessContext] [yamlRestTest-0] Killing job [set-upgrade-mode-job], because [task has been removed, cancelling locally]
[2021-02-16T22:19:48,793][WARN ][o.e.x.m.j.p.a.o.AutodetectResultProcessor] [yamlRestTest-0] [set-upgrade-mode-job] some results not processed due to the process being killed
[2021-02-16T22:19:48,806][INFO ][o.e.c.m.MetadataDeleteIndexService] [yamlRestTest-0] [.ml-annotations-6/BIeHpcjGTuqHS_hO2Q9lJg] deleting index
[2021-02-16T22:19:48,806][INFO ][o.e.c.m.MetadataDeleteIndexService] [yamlRestTest-0] [.ml-anomalies-shared/NhfiATDWTqu0blrlGIN2cg] deleting index
[2021-02-16T22:19:48,806][INFO ][o.e.c.m.MetadataDeleteIndexService] [yamlRestTest-0] [.ml-notifications-000001/1DPhVpMPSHuFIbvRMbeZRA] deleting index
[2021-02-16T22:19:48,806][INFO ][o.e.c.m.MetadataDeleteIndexService] [yamlRestTest-0] [.ml-state-000001/fizcsdUhRki4FKDM6HyPmQ] deleting index
[2021-02-16T22:19:48,806][INFO ][o.e.c.m.MetadataDeleteIndexService] [yamlRestTest-0] [airline-data/Jzd3VSyjTfGHkL6u2KsFHg] deleting index
[2021-02-16T22:19:48,807][INFO ][o.e.c.m.MetadataDeleteIndexService] [yamlRestTest-0] [.ml-config/ao-1X_eNSZOAVUw1vv5LOg] deleting index
[2021-02-16T22:19:48,822][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [yamlRestTest-0] [controller/12786] [CDetachedProcessSpawner.cc@176] Child process with PID 60996 was terminated by signal 15
```

After the test has effectively completed, there is a 1 minute pause in the logs between setting the job to opened and then it being killed.

Where that minute pause is occurring is the reason for the test failure. Finding exactly where that is will be difficult.

**Comment by benwtrent** [comment]
OK, digging a little further. 

This large pause in time 100% happens during `/_ml/anomaly_detectors/_all/_close` and periodically causes these tests to timeout. There may be some weird race condition for calling close on `_all` and a job still in the middle of opening.

**Comment by droberts195** [comment]
> and a job still in the middle of opening

This failure started occurring shortly after #65814 was merged (according to https://github.com/elastic/elasticsearch/issues/65947#issuecomment-740182623) so it is highly likely that something related to that change is the point where closing the opening job loses the request to close.

An _idea_ for what might be going wrong is as follows:

1. Test opens some jobs
2. Jobs get assigned and processes start
3. Test sets upgrade mode
4. Jobs get unassigned (still open) and processes are killed
5. Test unsets upgrade mode
6. Jobs get assigned again (still open)
7. Jobs revert to latest snapshot (new functionality added around the time the test started failing)
8. Test ends, cleanup kicks in closing `_all` jobs

If this theory is correct the place to look for a bug is in the area of what would happen if a job was asked to close while reverting a model snapshot as part of node assignment while already open.

_But note that this is only an educated guess - just a hint at where to start looking - it might be wrong._
