### ISSUE TITLE
[CI] [FIPS] Fails to setup default trustmanager (for reindex)

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#65995]
**Build scan**:
- `7.x` : https://gradle-enterprise.elastic.co/s/alv5khbzqka72/console-log?anchor=7004

**Failure excerpt**:
```
»    ↓ errors and warnings from /dev/shm/elastic+elasticsearch+7.x+matrix-java-periodic-fips/ES_RUNTIME_JAVA/corretto8/nodes/general-purpose/qa/full-cluster-restart/build/testclusters/v7.10.1-0/logs/es.stdout.log ↓	
» ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v7.10.1-0] uncaught exception in thread [main]	
»  org.elasticsearch.bootstrap.StartupException: org.elasticsearch.common.ssl.SslConfigException: failed to initialize a TrustManager for the system keystore	
»  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:174) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]	
...
»  Caused by: org.elasticsearch.common.ssl.SslConfigException: failed to initialize a TrustManager for the system keystore	
»  	at org.elasticsearch.common.ssl.DefaultJdkTrustConfig.createTrustManager(DefaultJdkTrustConfig.java:70) ~[?:?]	
»  	at org.elasticsearch.common.ssl.SslConfiguration.createSslContext(SslConfiguration.java:136) ~[?:?]	
»  	at org.elasticsearch.index.reindex.ReindexSslConfig.reload(ReindexSslConfig.java:145) ~[?:?]	
...
»  	at org.elasticsearch.node.Node.<init>(Node.java:557) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]	
...
»  Caused by: java.security.NoSuchAlgorithmException: PKIX TrustManagerFactory not available	
»  	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159) ~[?:?]	
»  	at javax.net.ssl.TrustManagerFactory.getInstance(TrustManagerFactory.java:163) ~[?:?]	
»  	at org.elasticsearch.common.ssl.KeyStoreUtil.createTrustManager(KeyStoreUtil.java:150) ~[?:?]	
»  	at org.elasticsearch.common.ssl.DefaultJdkTrustConfig.createTrustManager(DefaultJdkTrustConfig.java:68) ~[?:?]	
```

**Comment by tvernum** [comment]
It's been failing since [build 382](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic-fips/ES_RUNTIME_JAVA=corretto8,nodes=general-purpose/382) which corresponds with #65829 being merged, so I think we should start there.

**Comment by tvernum** [comment]
Also it looks like this is failing across everything except `Java8` in the JDK build matrix.
I haven't verified that they all have the same error message though.

**Comment by jkakavas** [comment]
> Caused by: java.security.NoSuchAlgorithmException: PKIX TrustManagerFactory not available

`PKIX` trust manager factory implementation should have been provided by BCJSSE so this points to `org.bouncycastle:bctls-fips:1.0.9` not being added to the classpath for certain plugins. This is why this doesn't fail for java8, which still uses SunJSSE. 

@breskeby can you shed some light here please ? We changed `pluginManager.withPlugin('java')` to `pluginManager.withPlugin('java-base')` so that it gets applied everywhere but it looks like this doesn't get applied everywhere. Any thoughts?

**Comment by martijnvg** [comment]
Another instance of this failure while executing `:qa:verify-version-constants:v7.10.1#integTest` task: https://gradle-enterprise.elastic.co/s/3fk4yalcusjyq

```
Caused by: java.security.NoSuchAlgorithmException: PKIX TrustManagerFactory not available |  
-- | --
  | »  	at sun.security.jca.GetInstance.getInstance(GetInstance.java:159) ~[?:?] |  
  | »  	at javax.net.ssl.TrustManagerFactory.getInstance(TrustManagerFactory.java:163) ~[?:?] |  
  | »  	at org.elasticsearch.common.ssl.KeyStoreUtil.createTrustManager(KeyStoreUtil.java:150) ~[?:?] |  
  | »  	at org.elasticsearch.common.ssl.DefaultJdkTrustConfig.createTrustManager(DefaultJdkTrustConfig.java:68) ~[?:?] |  
  | »  	at org.elasticsearch.common.ssl.SslConfiguration.createSslContext(SslConfiguration.java:136) ~[?:?] |  
  | »  	at org.elasticsearch.index.reindex.ReindexSslConfig.reload(ReindexSslConfig.java:145) ~[?:?] |  
  | »  	at org.elasticsearch.index.reindex.ReindexSslConfig.<init>(ReindexSslConfig.java:115) ~[?:?] |  
  | »  	at org.elasticsearch.index.reindex.ReindexPlugin.createComponents(ReindexPlugin.java:91) ~[?:?] |  
  | »  	at org.elasticsearch.node.Node.lambda$new$15(Node.java:553) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT] |  
  | »  	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?] |  
  | »  	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?] |  
  | »  	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] |  
  | »  	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?] |  
  | »  	at org.elasticsearch.node.Node.<init>(Node.java:557) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT] |  
  | »  	at org.elasticsearch.node.Node.<init>(Node.java:289) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.10.1-SNAPSHOT.jar:7.10.1-SNAPSHOT]
```

**Comment by jkakavas** [comment]
@breskeby , @mark-vieira any thoughst about https://github.com/elastic/elasticsearch/issues/65995#issuecomment-740394692 ?

**Comment by breskeby** [comment]
Please asssign this to me I'll have a look

**Comment by breskeby** [comment]
It seems a problem specific to corretto8. At least I can only reproduce the issue with that jdk

**Comment by breskeby** [comment]
I don't see any issue with the work done in #65829. Furthermore this seems only to fail on corretto 8. I'm not an expert in how this fips stuff needs to be setup. Is it possible we do not do something on java8 as other java 8 jdks do not require additional jars on the classpath?

**Comment by jkakavas** [comment]
The fips related setup we do is all in grips.gradle. can you further explain what you mean with 

> Is it possible we do not do something on java8 as other java 8 jdks do not require additional jars on the classpath

?

**Comment by jkakavas** [comment]
Zulu 8 broke fips CI a few weeks ago because they backported changes from jdk11 (earlier that adoptopenjdk did ) ,for instance. I suspect some jdk specific change triggers this. I'll assign it back to the security team and investigate further

**Comment by breskeby** [comment]
thank you. Yeah seems corretto 8 also backported plenty of changes from later jdks

**Comment by jkakavas** [comment]
This issue was specific to corretto 8 and FIPS which is not a combination we support and test for in CI any more, so I will close this as won't fix
