### ISSUE TITLE
elasticsearch-node does not load plugins roles

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#66000]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10, but applies to master as well

**Plugins installed**: [] transform (or another from plugin)

**OS version** (`uname -a` if on a Unix-like system): macos

**Description of the problem including expected versus actual behavior**:
when a node has a role from x-pack (like transform) elasticsearch-node tool will not be possible to run. This possibly is by design as per comment in 
`ElasticsearchNodeCommand:L75` 
```   
 // ... as command-line tools are not loading plugins,...
```

**Steps to reproduce**:
1. set a transform role in elasticsearch.yml
node.roles: [transform, master, remote_cluster_client, data, ml, data_content,data_warm, data_cold, ingest, data_hot]
2. run and stop ES

3. edit elasticsearch.yaml to remove `data_hot`
4. run `elasticsearch-node repurpose`

result:
```
bin/elasticsearch-node repurpose
------------------------------------------------------------------------

    WARNING: Elasticsearch MUST be stopped before running this tool.

Exception in thread "main" java.lang.IllegalArgumentException: unknown role [transform]
	at org.elasticsearch.cluster.node.DiscoveryNode.getRoleFromRoleName(DiscoveryNode.java:519)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.elasticsearch.common.settings.Setting.lambda$listSetting$44(Setting.java:1478)
	at org.elasticsearch.common.settings.Setting.get(Setting.java:441)
	at org.elasticsearch.common.settings.Setting.get(Setting.java:435)
	at org.elasticsearch.cluster.node.DiscoveryNode.getRolesFromSettings(DiscoveryNode.java:233)
	at org.elasticsearch.cluster.node.DiscoveryNode.isDataNode(DiscoveryNode.java:93)
	at org.elasticsearch.env.NodeRepurposeCommand.validateBeforeLock(NodeRepurposeCommand.java:68)
	at org.elasticsearch.cluster.coordination.ElasticsearchNodeCommand.execute(ElasticsearchNodeCommand.java:175)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.cluster.coordination.NodeToolCli.main(NodeToolCli.java:49)
```

**Comment by jasontedor** [comment]
Note that without some rework, loading plugins here would be risky. Plugins can execute arbitrary code when they're loaded. So we'd want the security manager in place before we could load plugins in command line tools. The command line tools don't have any infrastructure for that today. That is, addressing this issue is high-hanging fruit.
