### ISSUE TITLE
[CI] :x-pack:plugin:sql:qa:jdbc:security:with-ssl:v7.10.1#bwcTest (fips) failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#66095]
**Build scan**: https://gradle-enterprise.elastic.co/s/elzmdxfctoyi6
 (ES_RUNTIME_JAVA=zulu11,nodes=general-purpose)

**Repro line**: (no reproduce line)

**Reproduces locally?**: No

**Applicable branches**: master

**Failure history**:

* https://gradle-enterprise.elastic.co/s/3cmfp5x4tcmeg (ES_RUNTIME_JAVA=zulu11,nodes=general-purpose)
* https://gradle-enterprise.elastic.co/s/5vyjqckrl3v5g (ES_RUNTIME_JAVA=java11,nodes=general-purpose)
* https://gradle-enterprise.elastic.co/s/yrwejit7yf3h6 (ES_RUNTIME_JAVA=adoptopenjdk11,nodes=general-purpose)
* https://gradle-enterprise.elastic.co/s/gvpm7bmsp4kzk (ES_RUNTIME_JAVA=zulu8,nodes=general-purpose)

Seems to be fips related.

**Failure excerpt**:

QA module can't start node and build fails:

```
ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v7.10.1-bwcTest-0] uncaught exception in thread [main] |  
-- | --
  | »  org.elasticsearch.bootstrap.StartupException: org.elasticsearch.ElasticsearchSecurityException: failed to load SSL configuration [xpack.security.transport.ssl] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:174) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127) ~[elasticsearch-cli-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  Caused by: org.elasticsearch.ElasticsearchSecurityException: failed to load SSL configuration [xpack.security.transport.ssl] |  
  | »  	at org.elasticsearch.xpack.core.ssl.SSLService.lambda$loadSSLConfigurations$5(SSLService.java:533) ~[?:?] |  
  | »  	at java.util.HashMap.forEach(HashMap.java:1336) ~[?:?] |  
  | »  	at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.SSLService.loadSSLConfigurations(SSLService.java:529) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.SSLService.<init>(SSLService.java:140) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.XPackPlugin.createSSLService(XPackPlugin.java:413) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.XPackPlugin.createComponents(XPackPlugin.java:263) ~[?:?] |  
  | »  	at org.elasticsearch.node.Node.lambda$new$15(Node.java:542) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?] |  
  | »  	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?] |  
  | »  	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] |  
  | »  	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?] |  
  | »  	at org.elasticsearch.node.Node.<init>(Node.java:546) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.node.Node.<init>(Node.java:279) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:225) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:225) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:387) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	... 6 more |  
  | »  Caused by: org.elasticsearch.ElasticsearchException: failed to create trust manager |  
  | »  	at org.elasticsearch.xpack.core.ssl.TrustConfig$CombiningTrustConfig.createTrustManager(TrustConfig.java:171) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.SSLService.createSslContext(SSLService.java:442) ~[?:?] |  
  | »  	at java.util.HashMap.computeIfAbsent(HashMap.java:1133) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.SSLService.lambda$loadSSLConfigurations$5(SSLService.java:531) ~[?:?] |  
  | »  	at java.util.HashMap.forEach(HashMap.java:1336) ~[?:?] |  
  | »  	at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.SSLService.loadSSLConfigurations(SSLService.java:529) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.SSLService.<init>(SSLService.java:140) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.XPackPlugin.createSSLService(XPackPlugin.java:413) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.XPackPlugin.createComponents(XPackPlugin.java:263) ~[?:?] |  
  | »  	at org.elasticsearch.node.Node.lambda$new$15(Node.java:542) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?] |  
  | »  	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?] |  
  | »  	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] |  
  | »  	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?] |  
  | »  	at org.elasticsearch.node.Node.<init>(Node.java:546) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.node.Node.<init>(Node.java:279) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:225) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:225) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:387) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	... 6 more |  
  | »  Caused by: org.elasticsearch.ElasticsearchException: failed to initialize SSL TrustManager |  
  | »  	at org.elasticsearch.xpack.core.ssl.StoreKeyConfig.createTrustManager(StoreKeyConfig.java:103) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.TrustConfig$CombiningTrustConfig.lambda$createTrustManager$0(TrustConfig.java:168) ~[?:?] |  
  | »  	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?] |  
  | »  	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?] |  
  | »  	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.TrustConfig$CombiningTrustConfig.createTrustManager(TrustConfig.java:169) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.SSLService.createSslContext(SSLService.java:442) ~[?:?] |  
  | »  	at java.util.HashMap.computeIfAbsent(HashMap.java:1133) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.SSLService.lambda$loadSSLConfigurations$5(SSLService.java:531) ~[?:?] |  
  | »  	at java.util.HashMap.forEach(HashMap.java:1336) ~[?:?] |  
  | »  	at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.SSLService.loadSSLConfigurations(SSLService.java:529) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.SSLService.<init>(SSLService.java:140) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.XPackPlugin.createSSLService(XPackPlugin.java:413) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.XPackPlugin.createComponents(XPackPlugin.java:263) ~[?:?] |  
  | »  	at org.elasticsearch.node.Node.lambda$new$15(Node.java:542) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?] |  
  | »  	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?] |  
  | »  	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] |  
  | »  	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?] |  
  | »  	at org.elasticsearch.node.Node.<init>(Node.java:546) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.node.Node.<init>(Node.java:279) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:225) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:225) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:387) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	... 6 more |  
  | »  Caused by: java.io.IOException: Invalid keystore format |  
  | »  	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:667) ~[?:?] |  
  | »  	at sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222) ~[?:?] |  
  | »  	at java.security.KeyStore.load(KeyStore.java:1479) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.TrustConfig.getStore(TrustConfig.java:97) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.StoreKeyConfig.createTrustManager(StoreKeyConfig.java:94) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.TrustConfig$CombiningTrustConfig.lambda$createTrustManager$0(TrustConfig.java:168) ~[?:?] |  
  | »  	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?] |  
  | »  	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?] |  
  | »  	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.TrustConfig$CombiningTrustConfig.createTrustManager(TrustConfig.java:169) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.SSLService.createSslContext(SSLService.java:442) ~[?:?] |  
  | »  	at java.util.HashMap.computeIfAbsent(HashMap.java:1133) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.SSLService.lambda$loadSSLConfigurations$5(SSLService.java:531) ~[?:?] |  
  | »  	at java.util.HashMap.forEach(HashMap.java:1336) ~[?:?] |  
  | »  	at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.SSLService.loadSSLConfigurations(SSLService.java:529) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.ssl.SSLService.<init>(SSLService.java:140) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.XPackPlugin.createSSLService(XPackPlugin.java:413) ~[?:?] |  
  | »  	at org.elasticsearch.xpack.core.XPackPlugin.createComponents(XPackPlugin.java:263) ~[?:?] |  
  | »  	at org.elasticsearch.node.Node.lambda$new$15(Node.java:542) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?] |  
  | »  	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?] |  
  | »  	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?] |  
  | »  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] |  
  | »  	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?] |  
  | »  	at org.elasticsearch.node.Node.<init>(Node.java:546) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.node.Node.<init>(Node.java:279) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:225) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:225) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:387) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
```

**Comment by benwtrent** [comment]
Another FIPS failure: https://gradle-enterprise.elastic.co/s/3pwpovkmlqieg

Same keystore format failure.

**Comment by mark-vieira** [comment]
@jkakavas The FIPS builds are completely busted and have been for some time. Should we mute this, send the notifications elsewhere, etc? It's causing undue noise for test triage.

**Comment by jkakavas** [comment]
I am aware @mark-vieira but the triage and fix process we have right now for FIPS 140 related failures doesn't scale and I'm a bottleneck. We can reroute the notifications temporarily to a different address

**Comment by mark-vieira** [comment]
Indeed all FIPS stuff goes your direction so perhaps we should route the notifications so test triage isn't the main creator of these issues. Is there a mailing list I can send the FIPS build emails to? Or slack channel, someway that test triage isn't overwhelmed by the noise but these don't fall through the cracks?

**Comment by jkakavas** [comment]
> so perhaps we should route the notifications so test triage isn't the main creator of these issues. 

TBC ,the mid/long term goal should be that fips related failures/issues/fixes are handled in the same way as any other CI failure, we're just not there yet(again). It's a constant pain/effort, we were having mostly successful builds a few weeks/months back.

There is no list that we can use at the moment, can we create a new google group (build-failures-fips) where we can route these for now, until we are ready to merge them back to the build failures group ? I can make the request tomorrow morning and raise the relevant infra PR if you don't get to it by then.

**Comment by jkakavas** [comment]
This is rightly failing. What is concerning is that it just started failing recently. I started failing after https://github.com/elastic/elasticsearch/pull/65807 which made sure we apply the fips configuration to the correct plugins and it looks like until that time a lot of projects were not running with the fips configuration as the contents of fips.gradle were not applied. ( This also explains the fury of CI failures after December 8 )

I will mute this project as JDBC client only supports keystores and we can't use JKS/PKCS12 keystores in fips mode, but I'm curious about https://github.com/elastic/elasticsearch/pull/65807 @mark-vieira , @breskeby . Could you explain why `pluginManager.withPlugin('java')` was wrong and if `pluginManager.withPlugin('java-base') covers everything we care about ?

**Comment by mark-vieira** [comment]
> Could you explain why pluginManager.withPlugin('java') was wrong and if `pluginManager.withPlugin('java-base') covers everything we care about ?

Not all projects get `java` applied, specifically, the standalone test projects.

My intention is to ditch all that nonsense here soon. The matrix of different project plugins i starting to get out of hand.
