### ISSUE TITLE
[CI] java policy unavailable when staring 6.x node during bwc tests in fips mode

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#66102]
**Build scan**: https://gradle-enterprise.elastic.co/s/pdmimzsiolzoa

**Repro line**: (no reproduce line since tests have not run)

**Reproduces locally?**: no

**Applicable branches**:  7.x

**Failure history**:

* https://gradle-enterprise.elastic.co/s/ijuv5qzt7kiyi
* https://gradle-enterprise.elastic.co/s/dv642snk5vydg
* https://gradle-enterprise.elastic.co/s/qdf7mlk7pa5qq
* https://gradle-enterprise.elastic.co/s/gr5obmqgltioo
* https://gradle-enterprise.elastic.co/s/f6qgffrm7o3pu
* https://gradle-enterprise.elastic.co/s/hsrxrpn6iqahy
* https://gradle-enterprise.elastic.co/s/bsok5pxwmc2xm
* https://gradle-enterprise.elastic.co/s/vacwr3kydelx2
* https://gradle-enterprise.elastic.co/s/pphmpxnyzzl7w
* https://gradle-enterprise.elastic.co/s/j4ejqr3kfagak
* https://gradle-enterprise.elastic.co/s/5j5mqljpahugs

**Failure excerpt**:

```
errors and warnings from /dev/shm/elastic+elasticsearch+7.x+matrix-java-periodic-fips/ES_RUNTIME_JAVA/openjdk15/nodes/general-purpose/qa/full-cluster-restart/build/testclusters/v6.8.14-0/logs/es.stdout.log ↓ |  
-- | --
  | » WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [v6.8.14-0] uncaught exception in thread [main] |  
  | »  org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unable to parse policy file `file:/dev/shm/elastic+elasticsearch+7.x+matrix-java-periodic-fips/ES_RUNTIME_JAVA/openjdk15/nodes/general-purpose/qa/full-cluster-restart/build/testclusters/v6.8.14-0/distro/6.8.14-OSS/modules/transport-netty4/plugin-security.policy` |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  Caused by: java.lang.IllegalArgumentException: unable to parse policy file `file:/dev/shm/elastic+elasticsearch+7.x+matrix-java-periodic-fips/ES_RUNTIME_JAVA/openjdk15/nodes/general-purpose/qa/full-cluster-restart/build/testclusters/v6.8.14-0/distro/6.8.14-OSS/modules/transport-netty4/plugin-security.policy` |  
  | »  	at org.elasticsearch.bootstrap.Security.readPolicy(Security.java:246) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Security.getPluginPermissions(Security.java:186) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Security.configure(Security.java:123) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:207) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	... 6 more |  
  | »  Caused by: java.security.NoSuchAlgorithmException: JavaPolicy Policy not available |  
  | »  	at sun.security.jca.GetInstance.getInstance(GetInstance.java:198) ~[?:1.8.0_242] |  
  | »  	at java.security.Policy.getInstance(Policy.java:386) ~[?:1.8.0_242] |  
  | »  	at org.elasticsearch.bootstrap.Security.readPolicy(Security.java:238) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Security.getPluginPermissions(Security.java:186) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Security.configure(Security.java:123) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:207) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	... 6 more
```

Possible related to #56898

**Comment by benwtrent** [comment]
Just got a bunch more failures. All BWC from 6.x in with FIPS enabled. 

This occurred with all our runtimes that we test against.

Here is only one of the failures: https://gradle-enterprise.elastic.co/s/i4jeqhg76dbwk

```

↓ errors and warnings from /dev/shm/elastic+elasticsearch+7.x+matrix-java-periodic-fips/ES_RUNTIME_JAVA/corretto11/nodes/general-purpose/qa/rolling-upgrade/build/testclusters/v6.8.14-0/logs/es.stdout.log ↓ |  
-- | --
  | » WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [v6.8.14-0] uncaught exception in thread [main] |  
  | »  org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unable to parse policy file `file:/dev/shm/elastic+elasticsearch+7.x+matrix-java-periodic-fips/ES_RUNTIME_JAVA/corretto11/nodes/general-purpose/qa/rolling-upgrade/build/testclusters/v6.8.14-0/distro/6.8.14-OSS/modules/transport-netty4/plugin-security.policy` |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  Caused by: java.lang.IllegalArgumentException: unable to parse policy file `file:/dev/shm/elastic+elasticsearch+7.x+matrix-java-periodic-fips/ES_RUNTIME_JAVA/corretto11/nodes/general-purpose/qa/rolling-upgrade/build/testclusters/v6.8.14-0/distro/6.8.14-OSS/modules/transport-netty4/plugin-security.policy` |  
  | »  	at org.elasticsearch.bootstrap.Security.readPolicy(Security.java:246) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Security.getPluginPermissions(Security.java:186) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Security.configure(Security.java:123) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:207) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	... 6 more |  
  | »  Caused by: java.security.NoSuchAlgorithmException: JavaPolicy Policy not available |  
  | »  	at sun.security.jca.GetInstance.getInstance(GetInstance.java:198) ~[?:1.8.0_242] |  
  | »  	at java.security.Policy.getInstance(Policy.java:386) ~[?:1.8.0_242] |  
  | »  	at org.elasticsearch.bootstrap.Security.readPolicy(Security.java:238) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Security.getPluginPermissions(Security.java:186) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Security.configure(Security.java:123) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:207) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.14-SNAPSHOT.jar:6.8.14-SNAPSHOT] |  
  | »  	... 6 more


```

**Comment by jkakavas** [comment]
Closing this as BWC testing is disabled in FIPS mode. We still don't run BWC tests in FIPS mode but this is tracked in https://github.com/elastic/elasticsearch/issues/66772
