### ISSUE TITLE
MlJobSnapshotUpgradeIT fail after release of 7.10.1

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#66161]
**Build scan**: https://gradle-enterprise.elastic.co/s/xch5fx2z5pdgs

**Repro line**:

```
./gradlew ':x-pack:qa:rolling-upgrade:v6.8.9#upgradedClusterTest' \
  -Dtests.class="org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT" \
  -Dtests.method="testSnapshotUpgrader" \
  -Dtests.seed=E6803B0E7B86D7C2 \
  -Dtests.security.manager=true \
  -Dtests.bwc=true \
  -Dtests.locale=hr-HR \
  -Dtests.timezone=Pacific/Nauru \
  -Dtests.distribution=default \
  -Druntime.java=8
```

**Reproduces locally?**: yes

**Applicable branches**:

7.x

**Failure history**: 

https://gradle-enterprise.elastic.co/s/ldii6po4ooix2 / https://gradle-enterprise.elastic.co/s/epgtaodbgyhp4 and several more

**Failure excerpt**:

```
> Task :x-pack:qa:rolling-upgrade:v6.8.9#upgradedClusterTest


org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT > testSnapshotUpgrader FAILED
    java.lang.AssertionError: 
    Expected: <7.9.0>
         but: was <7.11.0>
        at __randomizedtesting.SeedInfo.seed([E6803B0E7B86D7C2:FAA322617CF37C4C]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.testSnapshotUpgrade(MlJobSnapshotUpgradeIT.java:140)
        at org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.testSnapshotUpgrader(MlJobSnapshotUpgradeIT.java:110)
REPRODUCE WITH: ./gradlew ':x-pack:qa:rolling-upgrade:v6.8.9#upgradedClusterTest' -Dtests.class="org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT" -Dtests.method="testSnapshotUpgrader" -Dtests.seed=E6803B0E7B86D7C2 -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=hr-HR -Dtests.timezone=Pacific/Nauru -Dtests.distribution=default -Druntime.java=8

Suite: Test class org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT
  1> [2020-12-11T00:00:22,709][INFO ][o.e.u.MlJobSnapshotUpgradeIT] [testSnapshotUpgrader] before test
  1> [2020-12-11T00:00:22,781][INFO ][o.e.u.MlJobSnapshotUpgradeIT] [testSnapshotUpgrader] initializing REST clients against [http://[::1]:40301, http://127.0.0.1:38287, http://[::1]:46773, http://127.0.0.1:35373, http://[::1]:37435, http://127.0.0.1:45817]
  1> [2020-12-11T00:00:25,634][INFO ][o.e.u.MlJobSnapshotUpgradeIT] [testSnapshotUpgrader] There are still tasks running after this test that might break subsequent tests [internal:index/shard/recovery/clean_files, internal:index/shard/recovery/start_recovery].
  1> [2020-12-11T00:00:25,672][INFO ][o.e.u.MlJobSnapshotUpgradeIT] [testSnapshotUpgrader] after test
  2> REPRODUCE WITH: ./gradlew ':x-pack:qa:rolling-upgrade:v6.8.9#upgradedClusterTest' -Dtests.class="org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT" -Dtests.method="testSnapshotUpgrader" -Dtests.seed=E6803B0E7B86D7C2 -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=hr-HR -Dtests.timezone=Pacific/Nauru -Dtests.distribution=default -Druntime.java=8
  2> java.lang.AssertionError: 
    Expected: <7.9.0>
         but: was <7.11.0>
        at __randomizedtesting.SeedInfo.seed([E6803B0E7B86D7C2:FAA322617CF37C4C]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.testSnapshotUpgrade(MlJobSnapshotUpgradeIT.java:140)
        at org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.testSnapshotUpgrader(MlJobSnapshotUpgradeIT.java:110)
  2> NOTE: leaving temporary files on disk at: /home/dl/source/elastic/elasticsearch-7.x/x-pack/qa/rolling-upgrade/build/testrun/v6.8.9#upgradedClusterTest/temp/org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT_E6803B0E7B86D7C2-001
  2> NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=321, maxMBSortInHeap=7.628230485710644, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=hr-HR, timezone=Pacific/Nauru
  2> NOTE: Linux 5.9.11-3-MANJARO amd64/AdoptOpenJDK 1.8.0_232 (64-bit)/cpus=32,threads=1,free=472785776,total=514850816
  2> NOTE: All tests run in this JVM: [IndexingIT, DataStreamsUpgradeIT, RollupDateHistoUpgradeIT, RollupIDUpgradeIT, TokenBackwardsCompatibilityIT, TransformSurvivesUpgradeIT, UpgradeClusterClientYamlTestSuiteIT, MlMappingsUpgradeIT, MlJobSnapshotUpgradeIT]

Tests with failures:
 - org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.testSnapshotUpgrader

1 test completed, 1 failed

```

**Comment by dliappis** [comment]
Muting in https://github.com/elastic/elasticsearch/pull/66164
