### ISSUE TITLE
[CI] CachedBlobContainerIndexInputTests.testRandomReads failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#66418]
Saw 4 failures in the past two days.

**Build scan**:
https://gradle-enterprise.elastic.co/s/2hkq7vdyvz3zy/tests/:x-pack:plugin:searchable-snapshots:test/org.elasticsearch.index.store.cache.CachedBlobContainerIndexInputTests/testRandomReads#1

**Repro line**:
`./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.index.store.cache.CachedBlobContainerIndexInputTests.testRandomReads" -Dtests.seed=65316F60EB4EFBC7 -Dtests.security.manager=true -Dtests.locale=ar-JO -Dtests.timezone=Etc/GMT-0 -Druntime.java=8`

**Reproduces locally?**:
Did not reproduce locally

**Applicable branches**:
master and 7.x

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.index.store.cache.CachedBlobContainerIndexInputTests&tests.disabledDistributions=WyJvdXRjb21lOnBhc3NlZCJd&tests.sortField=FAILED&tests.test=testRandomReads&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.index.store.cache.CachedBlobContainerIndexInputTests > testRandomReads FAILED
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=47, name=elasticsearch[testRandomReads][generic][T#1], state=RUNNABLE, group=TGRP-CachedBlobContainerIndexInputTests]
        at __randomizedtesting.SeedInfo.seed([65316F60EB4EFBC7:5033CD9301E25FED]:0)

        Caused by:
        java.lang.AssertionError: java.lang.IllegalArgumentException: Failed to find a Lucene index for cache file path [/dev/shm/elastic+elasticsearch+7.x+periodic/x-pack/plugin/searchable-snapshots/build/testrun/test/temp/org.elasticsearch.index.store.cache.CachedBlobContainerIndexInputTests_65316F60EB4EFBC7-001/tempDir-007/Jd_BIJGoTvmRmqAkG5fn5A]
            at __randomizedtesting.SeedInfo.seed([65316F60EB4EFBC7]:0)
            at org.elasticsearch.xpack.searchablesnapshots.cache.CacheService.synchronizeCache(CacheService.java:538)
            at org.elasticsearch.xpack.searchablesnapshots.cache.CacheService$CacheSynchronizationTask.runInternal(CacheService.java:575)
            at org.elasticsearch.common.util.concurrent.AbstractAsyncTask.run(AbstractAsyncTask.java:144)
            at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:748)

            Caused by:
            java.lang.IllegalArgumentException: Failed to find a Lucene index for cache file path [/dev/shm/elastic+elasticsearch+7.x+periodic/x-pack/plugin/searchable-snapshots/build/testrun/test/temp/org.elasticsearch.index.store.cache.CachedBlobContainerIndexInputTests_65316F60EB4EFBC7-001/tempDir-007/Jd_BIJGoTvmRmqAkG5fn5A]
                at org.elasticsearch.xpack.searchablesnapshots.cache.PersistentCache.lambda$getWriter$1(PersistentCache.java:127)
                at java.util.Optional.orElseThrow(Optional.java:290)
                at org.elasticsearch.xpack.searchablesnapshots.cache.PersistentCache.getWriter(PersistentCache.java:127)
                at org.elasticsearch.xpack.searchablesnapshots.cache.PersistentCache.addCacheFile(PersistentCache.java:133)
                at org.elasticsearch.xpack.searchablesnapshots.cache.CacheService.synchronizeCache(CacheService.java:533)
                ... 6 more
```

**Comment by tlrx** [comment]
Thanks @mark-vieira for opening this issue. I opened #66368 to fix this when I noticed it but I did not mention this test in the PR so there was no chance for you to find it, sorry.
