### ISSUE TITLE
clolud you help reindex problem in es6.5.4?

### ISSUE THREAD

**Issue by 15838028035** [elastic/elasticsearch#66574]
**Elasticsearch version** (`bin/elasticsearch --version`):  6.5.4

**Plugins installed**: []

**JVM version** (`java -version`):  jdk1.8

**OS version** (`uname -a` if on a Unix-like system): window10

java code :

@PostMapping("/reindexTest")
    @ResponseBody
    public void reindexTest()
    {
 		 Map<String, String> configs = esUtil.getConfig();
 		 
 	    RestHighLevelClient restHighLevelClient = ClientFactory.getRestHighLevelClient("192.168.120.112", 9200);
 	   String idx =  configs.get("index");
 	   
 	  ReindexRequest request = new ReindexRequest(); //创建ReindexRequest
 	  
 	 request.setRemoteInfo(
 		    new RemoteInfo(
 		        "http", "10.11.5.11", 9200, null,
// 		        new BytesArray(new MatchAllQueryBuilder().toString()),
 		        new BytesArray("{\"match_all\":{}}"),
 		        null, null, Collections.emptyMap(),
 		        new TimeValue(1000, TimeUnit.MILLISECONDS),
 		        new TimeValue(1000, TimeUnit.SECONDS)
 		    )
 		); //设置远程elastic集群o
 	 
 	request.setSourceIndices("test"); //添加要从源中复制的列表
 	request.setDestDocType("_doc");
 	request.setDestIndex("testaa");  //添加目标索引
 	
 	request.setSourceQuery(null);
 	
 	String aa = request.toString();
 	System.out.println("aa==================="+aa);
 	
 	restHighLevelClient.reindexAsync(request, RequestOptions.DEFAULT, new ActionListener<BulkByScrollResponse>() {
 	    @Override
 	    public void onResponse(BulkByScrollResponse bulkResponse) {
 	        //成功的时候执行
 	    	System.out.println("我执行成功了...");
 	    }
 	    @Override
 	    public void onFailure(Exception e) {
 	        //失败的时候执行
 	    	e.printStackTrace();
 	    }
 	}
 	); 
 	
    }

Exception:

aa===================reindex from [host=10.120.5.11port=9200 query={"match_all":{}}][test] to [testaa][_doc]
ElasticsearchStatusException[Elasticsearch exception [type=x_content_parse_exception, reason=[1:180] [reindex] failed to parse field [source]]]; nested: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=Unsupported fields in [remote]: [query]]];
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177)
	at org.elasticsearch.client.RestHighLevelClient$$Lambda$648.00000000185EAB00.apply(Unknown Source)
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1793)
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1769)
	at org.elasticsearch.client.RestHighLevelClient$1.onFailure(RestHighLevelClient.java:1744)
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:850)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:554)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:531)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:123)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:442)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:332)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:813)
	Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [http://192.168.120.128:9200], URI [/_reindex?scroll=5m&requests_per_second=-1&timeout=1m], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"x_content_parse_exception","reason":"[1:180] [reindex] failed to parse field [source]"}],"type":"x_content_parse_exception","reason":"[1:180] [reindex] failed to parse field [source]","caused_by":{"type":"illegal_argument_exception","reason":"Unsupported fields in [remote]: [query]"}},"status":400}
		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:546)
		... 16 more
Caused by: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=Unsupported fields in [remote]: [query]]]
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:509)
	at org.elasticsearch.ElasticsearchException.fromXContent(ElasticsearchException.java:420)
	at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:450)
	at org.elasticsearch.ElasticsearchException.failureFromXContent(ElasticsearchException.java:616)
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:169)
	... 22 more

what should i do ? cloud you help me ?

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
