### ISSUE TITLE
SimpleNetty4TransportTests.testTracerLog failures due to appending to non-started mock

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#66630]
**Build scan**: https://gradle-enterprise.elastic.co/s/txadsy2xjoac6

**Repro line**: `./gradlew ':modules:transport-netty4:test' --tests "org.elasticsearch.transport.netty4.SimpleNetty4TransportTests.testTracerLog" -Dtests.seed=6E8754C48D2EBD4F -Dtests.security.manager=true -Dtests.locale=es-ES -Dtests.timezone=Africa/Banjul -Druntime.java=8`

**Reproduces locally?**: No

**Applicable branches**: `7.x`, `7.10`

**Failure history**: [build stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(branch,message),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'test:testTracerLog'),sort:!(time,desc)))
This appears to have been failing a *lot* in late November, but has been quiet until Dec. 11. It's failed 3 times since then, once on `7.x` and twice on `7.10`.
**Failure excerpt**:
Failure stack trace:
```
java.lang.AssertionError: 	
Expected: an empty collection	
     but: <[Attempted to append to non-started appender mock]>	
	at __randomizedtesting.SeedInfo.seed([6E8754C48D2EBD4F:6D04A97A8C26139A]:0)	
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)	
	at org.junit.Assert.assertThat(Assert.java:956)	
	at org.junit.Assert.assertThat(Assert.java:923)	
	at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:572)	
	at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:393)	
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)	
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
	at java.lang.reflect.Method.invoke(Method.java:498)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)	
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)	
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)	
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)	
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)	
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)	
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)	
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)	
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)	
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)	
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)	
	at java.lang.Thread.run(Thread.java:748)
```

Possibly-relevant other logs:
```
[2020-12-18T08:10:08,859][TRACE][o.e.t.T.tracer           ] [TS_A] [4][internal:testError] received response from [{TS_B}{yENEiqPrQjqHBMqUZCw3zw}{SA6TJqj2RwKafLYWXp4kmg}{127.0.0.1}{127.0.0.1:11201}{dimr}]	
[2020-12-18T08:10:08,859][TRACE][o.e.t.T.tracer           ] [TS_B] [4][internal:testError] sent error response	
java.lang.RuntimeException: 	
	at org.elasticsearch.transport.AbstractSimpleTransportTestCase.lambda$testTracerLog$16(AbstractSimpleTransportTestCase.java:1031) ~[framework-7.10.2-SNAPSHOT.jar:7.10.2-SNAPSHOT]	
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:72) ~[elasticsearch-7.10.2-SNAPSHOT.jar:7.10.2-SNAPSHOT]	
	at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:207) ~[elasticsearch-7.10.2-SNAPSHOT.jar:7.10.2-SNAPSHOT]	
	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:107) ~[elasticsearch-7.10.2-SNAPSHOT.jar:7.10.2-SNAPSHOT]	
	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:89) ~[elasticsearch-7.10.2-SNAPSHOT.jar:7.10.2-SNAPSHOT]	
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:700) ~[elasticsearch-7.10.2-SNAPSHOT.jar:7.10.2-SNAPSHOT]	
	at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142) [elasticsearch-7.10.2-SNAPSHOT.jar:7.10.2-SNAPSHOT]	
	at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117) [elasticsearch-7.10.2-SNAPSHOT.jar:7.10.2-SNAPSHOT]	
	at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82) [elasticsearch-7.10.2-SNAPSHOT.jar:7.10.2-SNAPSHOT]	
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74) [main/:?]	
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271) [netty-handler-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) [netty-transport-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) [netty-transport-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]	
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]	
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]	
[2020-12-18T08:10:08,863][TRACE][o.e.t.T.tracer           ] [TS_B] [5][internal:testNotSeen] received request	
2020-12-18 08:10:08,866 elasticsearch[TS_B][transport_worker][T#9] ERROR Attempted to append to non-started appender mock	
[2020-12-18T08:10:08,864][TRACE][o.e.t.T.tracer           ] [TS_B] [5][internal:testNotSeen] sent response
```

**Comment by gwbrown** [comment]
Possibly related: https://github.com/elastic/elasticsearch/issues/41890

**Comment by DaveCTurner** [comment]
I tried to reproduce this for quite some time without success. The failure isn't very helpful unfortunately, so I opened #67117 because I think this will result in an earlier and more informative failure in future.

**Comment by DaveCTurner** [comment]
I tried to add more logging in #67117 and got a related-looking failure in`SimpleSecurityNioTransportTests`: https://gradle-enterprise.elastic.co/s/zkuyute2c4kvi/console-log?task=:x-pack:plugin:security:test but there's not a whole lot more info there. I will investigate further.

**Comment by DaveCTurner** [comment]
#67117 enhanced the logging on the wrong darn mock logger class 🤦 . Trying again with #67627.

**Comment by DaveCTurner** [comment]
Ok this does seem to be a genuine bug in how we're starting/stopping the mock appender, although I don't see an easy solution. This test reproduces the problem pretty quickly:

```
package org.elasticsearch.test;

import org.elasticsearch.common.logging.Loggers;
import org.elasticsearch.test.junit.annotations.TestLogging;

import java.util.concurrent.atomic.AtomicBoolean;

public class MockLogAppenderTest extends ESTestCase {

    @TestLogging(reason="testing logging", value="org.elasticsearch.test.MockLogAppenderTest:INFO")
    public void testAppenderStartAddRemoveStop() throws Exception {
        final AtomicBoolean keepGoing = new AtomicBoolean(true);
        final Thread logThread = new Thread(() -> {
            while (keepGoing.get()) {
                logger.info("message");
            }
        });
        logThread.start();

        for (int i = 0; i < 100; i++) {
            final MockLogAppender appender = new MockLogAppender();
            try {
                appender.start();
                Loggers.addAppender(logger, appender);
            } finally {
                Loggers.removeAppender(logger, appender);
                appender.stop();
            }
        }

        keepGoing.set(false);
        logThread.join();
    }
}
```

The stack trace:

```
WARNING: Uncaught exception in thread: Thread[Thread-5,5,TGRP-MockLogAppenderTest]
org.apache.logging.log4j.core.appender.AppenderLoggingException: Attempted to append to non-started appender mock
	at __randomizedtesting.SeedInfo.seed([2FBF10B5653E7F58]:0)
	at org.apache.logging.log4j.core.config.AppenderControl.handleError(AppenderControl.java:142)
	at org.apache.logging.log4j.core.config.AppenderControl.ensureAppenderStarted(AppenderControl.java:135)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:127)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:464)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:448)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:431)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
	at org.apache.logging.log4j.core.config.DefaultReliabilityStrategy.log(DefaultReliabilityStrategy.java:49)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2170)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2125)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2108)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2002)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1974)
	at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1311)
	at org.elasticsearch.test.MockLogAppenderTest.lambda$testAppenderStartAddRemoveStop$0(MockLogAppenderTest.java:34)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

We take hold of the appender in `callAppenders` but then there's nothing stopping it from being removed and stopped before we get all the way down to `ensureAppenderStarted`.

I'm relabelling this for the attention of the core/infra folks as it's not really anything to do with the transport. I guess it just happens that the transport tracer emits log messages at a high enough frequency to trigger this race.

**Comment by DaveCTurner** [comment]
> I'm relabelling this for the attention of the core/infra folks as it's not really anything to do with the transport.

I've changed my mind. This is a plain `ESTestCase` so there shouldn't really be any other transport activity at the point where we clean up the appender. Will wait for a failure with a stack trace before taking further action.

**Comment by DaveCTurner** [comment]
This test is now failing more consistently for a different reason, I opened https://github.com/elastic/elasticsearch/issues/67928.

**Comment by DaveCTurner** [comment]
#67928 has been resolved, but there have been no more failures of this test yet.
