### ISSUE TITLE
FullClusterRestartIT.testRecoveryWithTranslogRetentionDisabled failures on 7.x/7.11

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#66631]
**Build scan**: https://gradle-enterprise.elastic.co/s/n6qqxdb4oprma

**Repro line**: `./gradlew ':qa:full-cluster-restart:v6.1.1#oldClusterTest' -Dtests.class="org.elasticsearch.upgrades.FullClusterRestartIT" -Dtests.method="testRecoveryWithTranslogRetentionDisabled" -Dtests.seed=3EC8792B39068EF -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=pl-PL -Dtests.timezone=ACT -Dtests.distribution=default -Druntime.java=8`

**Reproduces locally?**: No

**Applicable branches**: `7.x`, `7.11` (this is a BWC test, only appears to fail against 6.0.X/6.1.X versions)

**Failure history**: [build stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(branch,message),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'test:testRecoveryWithTranslogRetentionDisabled'),sort:!(time,desc)))
Failures first started occurring Dec. 4. No recent code changes to this test on 7.x.
**Failure excerpt**:
```
org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:40281], URI [testrecoverywithtranslogretentiondisabled/_flush/synced], status line [HTTP/1.1 409 Conflict]	
{"_shards":{"total":2,"successful":0,"failed":2},"testrecoverywithtranslogretentiondisabled":{"total":2,"successful":0,"failed":2,"failures":[{"shard":0,"reason":"[6] ongoing operations on primary"}]}}	
	at __randomizedtesting.SeedInfo.seed([3EC8792B39068EF:7EFA2F66D2B63DE3]:0)	
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)	
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)	
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)	
	at org.elasticsearch.test.rest.ESRestTestCase.performSyncedFlush(ESRestTestCase.java:1493)	
	at org.elasticsearch.upgrades.FullClusterRestartIT.testRecoveryWithTranslogRetentionDisabled(FullClusterRestartIT.java:1454)	
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
	at java.lang.reflect.Method.invoke(Method.java:498)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)	
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)	
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)	
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)	
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)	
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)	
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)	
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)	
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)	
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)	
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)	
	at java.lang.Thread.run(Thread.java:748)
```

This test has been failing a decent amount, mute incoming.

**Comment by dnhatn** [comment]
Fixed in #66968
