### ISSUE TITLE
GetIndexResponseTests.testFromXContent fails reproducibly on 7.x

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#66653]
**Build scan**: https://gradle-enterprise.elastic.co/s/2cfsh7clo6ule

**Repro line**: `./gradlew ':client:rest-high-level:test' --tests "org.elasticsearch.client.indices.GetIndexResponseTests.testFromXContent" -Dtests.seed=4574146BD32F6171 -Dtests.security.manager=true -Dtests.locale=pt-PT -Dtests.timezone=Asia/Baghdad -Druntime.java=8`

**Reproduces locally?**: Yes

**Applicable branches**: Only failed on CI on `7.10`, reproduces on latest `7.x` at time of writing

**Failure history**: [build stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(branch,message),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.client.indices.GetIndexResponseTests%22'),sort:!(time,desc)))
Only failed once on CI on record, but reproduces locally.
**Failure excerpt**:
```
com.fasterxml.jackson.core.JsonParseException: Duplicate field 'pnI'	
 at [Source: (byte[])"�ebloWa�galiases�cpnI�mindex_routingfzEuVdLnsearch_routingfzEuVdL�cpnI�nsearch_routingeiwbRU�hyXANOIBK�ffilter�dterm�dyear���mindex_routingetQzxH��hmappings�gfield-0�hanalyzergenglisheindexhanalyzeddtypedtext��hsettings�eindex�pnumber_of_shardsa2rnumber_of_replicasa2��hdefaults�eindex�qflush_after_mergee512mbnfinal_pipelinee_nonewmax_inner_result_windowc100junassigned�inode_left�odelayed_timeoutb1m��omax_terms_counte65536vrouting_partition_sizea1xforce_memory_term_dictionaryefalsexmax_docval"[truncated 2245 bytes]; line: -1, column: 70]	
	at __randomizedtesting.SeedInfo.seed([4574146BD32F6171:641C21735A8881AB]:0)	
	at com.fasterxml.jackson.dataformat.cbor.CBORReadContext._checkDup(CBORReadContext.java:182)	
	at com.fasterxml.jackson.dataformat.cbor.CBORReadContext.setCurrentName(CBORReadContext.java:173)	
	at com.fasterxml.jackson.dataformat.cbor.CBORParser._decodeFieldName(CBORParser.java:2533)	
	at com.fasterxml.jackson.dataformat.cbor.CBORParser.nextToken(CBORParser.java:603)	
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:52)	
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMapEntries(AbstractXContentParser.java:329)	
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValueUnsafe(AbstractXContentParser.java:398)	
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMapEntries(AbstractXContentParser.java:327)	
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValueUnsafe(AbstractXContentParser.java:398)	
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMapEntries(AbstractXContentParser.java:327)	
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.readMapSafe(AbstractXContentParser.java:316)	
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.mapOrdered(AbstractXContentParser.java:271)	
	at org.elasticsearch.test.ESTestCase.shuffleXContent(ESTestCase.java:1236)	
	at org.elasticsearch.test.AbstractXContentTestCase.insertRandomFieldsAndShuffle(AbstractXContentTestCase.java:275)	
	at org.elasticsearch.test.AbstractXContentTestCase$XContentTester.test(AbstractXContentTestCase.java:133)	
	at org.elasticsearch.client.indices.GetIndexResponseTests.testFromXContent(GetIndexResponseTests.java:63)	
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
	at java.lang.reflect.Method.invoke(Method.java:498)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)	
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)	
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)	
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)	
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)	
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)	
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)	
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)	
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)	
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)	
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)	
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by martijnvg** [comment]
Should be fixed by #66934.
