### ISSUE TITLE
Tripped Assertion in ConcurrentSnapshotsIT.testMasterFailoverOnFinalizationLoop

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#66663]
This just happened on 7.x (first time ever, only once ever) but looks like something broken with a recent backport:

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.ConcurrentSnapshotsIT" -Dtests.seed=C783CB8D04758962 -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=Etc/UTC -Druntime.java=14 -Dtests.fips.enabled=true

org.elasticsearch.snapshots.ConcurrentSnapshotsIT > classMethod FAILED
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=223, name=elasticsearch[node_t2][clusterApplierService#updateTask][T#1], state=RUNNABLE, group=TGRP-ConcurrentSnapshotsIT]

        Caused by:
        java.lang.AssertionError: Illegal move from repository generation [0] to generation [-1]
            at __randomizedtesting.SeedInfo.seed([C783CB8D04758962]:0)
            at org.elasticsearch.repositories.blobstore.BlobStoreRepository.updateState(BlobStoreRepository.java:513)
            at org.elasticsearch.repositories.RepositoriesService.applyClusterState(RepositoriesService.java:309)
            at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:510)
            at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:500)
            at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:471)
            at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:418)
            at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:68)
            at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:162)
            at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:684)
            at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
            at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
            at java.base/java.lang.Thread.run(Thread.java:832)
```

Specific failure is:

```
REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.ConcurrentSnapshotsIT.testMasterFailoverOnFinalizationLoop" -Dtests.seed=C783CB8D04758962 -Dtests.security.manager=true -Dtests.locale=zh-CN -Dtests.timezone=America/Swift_Current -Druntime.java=14 -Dtests.fips.enabled=true
```

Will look into it after next week.

**Comment by original-brownbear** [comment]
Similar failure in a another related test org.elasticsearch.snapshots.ConcurrentSnapshotsIT/testQueuedSnapshotOperationsAndBrokenRepoOnMasterFailOverMultipleRepos

https://gradle-enterprise.elastic.co/s/bk5tsrvspstuy/tests/:server:internalClusterTest/org.elasticsearch.snapshots.ConcurrentSnapshotsIT/testQueuedSnapshotOperationsAndBrokenRepoOnMasterFailOverMultipleRepos
