### ISSUE TITLE
[ML] after upgrade to 7.11 BC1, real-time AD job state turns to "closed"

### ISSUE THREAD

**Issue by wwang500** [elastic/elasticsearch#66752]
**Steps to reproduce:**

0) On cloud production environment (EC_REGION=gcp-europe-west1),
1) Set up a 7.10.0 or 7.9.0 cluster with ml node enabled
2) create several real-time AD jobs. then leave them in opened and started state
3) upgrade to 7.11.0 BC1
4) after upgrade finished, check those jobs being created in step 2,

**Observations:**
Jobs are in **closed** and started state.

**Expected:**
Jobs should be still in **opened** and started state. 

Message from one job:
![image](https://user-images.githubusercontent.com/47184485/102905640-774c8a80-4441-11eb-83dd-032521b38b5d.png)

WARN exception in es.log:
```
[instance-0000000005] task job-airplane_1605130010_000_0 failed with an exception
org.elasticsearch.transport.RemoteTransportException: [instance-0000000000][172.17.0.19:19174][cluster:admin/xpack/ml/job/model_snapshots/revert]
Caused by: org.elasticsearch.ElasticsearchStatusException: Can only revert to a model snapshot when the job is closed.
	at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.conflictStatusException(ExceptionsHelper.java:67) ~[?:?]
	at org.elasticsearch.xpack.ml.action.TransportRevertModelSnapshotAction.lambda$masterOperation$1(TransportRevertModelSnapshotAction.java:100) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.11.0.jar:7.11.0]
	at org.elasticsearch.xpack.ml.job.persistence.JobConfigProvider$5.onResponse(JobConfigProvider.java:399) ~[?:?]

```

**Comment by dimitris-athanasiou** [comment]
Nice catch @wwang500 ! Indeed, if the master node has not been updated to `7.11` reverting to the current snapshot while the job is open will not be possible. I have raised a fix that protects against this. Note that in this scenario we will revert to the prior behaviour (the job will resume from where it had reached and the model will have a knowledge gap).
