### ISSUE TITLE
[CI] SequenceSpecTests fails with an initiation error

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#66778]
**Build scan**:

https://gradle-enterprise.elastic.co/s/ggdt2tk4f3buk

**Repro line**:

Not sure how to reproduce it

**Reproduces locally?**:

No

**Applicable branches**:

master / 7.x

**Failure history**:

https://build-stats.elastic.co/goto/8083f918cdd983b7d0558e4430441611

It started failing in December 

**Failure excerpt**:

```
 java.util.IllegalFormatArgumentIndexException: Illegal format argument index = 0
        at java.base/java.util.Formatter$FormatSpecifier.index(Formatter.java:2803)
        at java.base/java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2872)
        at java.base/java.util.Formatter.parse(Formatter.java:2729)
        at java.base/java.util.Formatter.format(Formatter.java:2671)
        at java.base/java.util.Formatter.format(Formatter.java:2625)
        at java.base/java.lang.String.format(String.java:3331)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.collectCandidatesForMethod(RandomizedRunner.java:1432)
```

**Comment by ywangd** [comment]
This failure always happens whenever OpenJDK 16 is used.

**Comment by matriv** [comment]
It can be reproduced with `/gradlew :x-pack:plugin:eql:test -Druntime.java=16`

**Comment by matriv** [comment]
`master` : a4199af58b8c5ab4757a45248672e0233978b208
`7.x` : a90e0ef62ca9bf38122f4624e4307396b42c0ed5
`7.11` : 8b35e58c8bc3bc814af7629af81f5a3c8831c44f
`7.10` : a2a389afdbce2cafcc22f87b20ae4f116a4bdfef

**Comment by astefan** [comment]
@matriv should this issue be closed since the PR for it has been merged?
