### ISSUE TITLE
Multiline JSON Log Messages Issue

### ISSUE THREAD

**Issue by Alsheh** [elastic/elasticsearch#66806]
The Elasticsearch JSON log format prints java exception traceback on multiple lines resulting in an event for each line when collected by Filebeat which makes it harder to read or reconstruct the original traceback in Kibana.

**Elasticsearch version**: `docker.elastic.co/elasticsearch/elasticsearch:7.9.1`
**Provide logs (if relevant)**:

```
{"type": "server", "timestamp": "2020-12-23T04:54:23,908Z", "level": "WARN", "component": "o.e.c.NodeConnectionsService", "cluster.name": "<cluster-name>", "node.name": "<node-01-name>", "message": "failed to connect to {<node-02-name>}{8gHXwvVeQHWjKwyV8DkuiQ}{zdVslxxLTb6OAqFjpoQG1Q}{<host-ip>}{<host-ip>:9300}{lr}{ml.machine_memory=33252220928, ml.max_open_jobs=20, xpack.installed=true, data=kibana, transform.node=false} (tried [1] times)", "cluster.uuid": "<cluster-uuid>", "node.id": "<node-id>" ,
"stacktrace": ["org.elasticsearch.transport.ConnectTransportException: [<node-02-name>][<host-ip>:9300] connect_exception",
"at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onFailure(TcpTransport.java:966) ~[elasticsearch-7.9.1.jar:7.9.1]",
"at org.elasticsearch.action.ActionListener.lambda$toBiConsumer$2(ActionListener.java:198) ~[elasticsearch-7.9.1.jar:7.9.1]",
"at org.elasticsearch.common.concurrent.CompletableContext.lambda$addListener$0(CompletableContext.java:42) ~[elasticsearch-core-7.9.1.jar:7.9.1]",
"at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]",
"at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]",
"at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]",
"at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152) ~[?:?]",
"at org.elasticsearch.common.concurrent.CompletableContext.completeExceptionally(CompletableContext.java:57) ~[elasticsearch-core-7.9.1.jar:7.9.1]",
"at org.elasticsearch.transport.netty4.Netty4TcpChannel.lambda$addListener$0(Netty4TcpChannel.java:68) ~[?:?]",
"at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[?:?]",
"at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570) ~[?:?]",
"at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549) ~[?:?]",
"at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[?:?]",
"at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[?:?]",
"at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) ~[?:?]",
"at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[?:?]",
"at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321) ~[?:?]",
"at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337) ~[?:?]",
"at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702) ~[?:?]",
"at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) ~[?:?]",
"at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) ~[?:?]",
"at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[?:?]",
"at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]",
"at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]",
"at java.lang.Thread.run(Thread.java:832) [?:?]",
"Caused by: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: <host-ip>/<host-ip>:9300",
"Caused by: java.net.NoRouteToHostException: No route to host",
"at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]",
"at sun.nio.ch.Net.pollConnectNow(Net.java:589) ~[?:?]",
"at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:839) ~[?:?]",
"at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[?:?]",
"at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[?:?]",
"... 7 more"] }
```

**Comment by pgomulka** [comment]
@Alsheh have you tried with filebeat's elasticsearch module? it should be able to parse ES logs out of the box (including multilined stactraces)

This behaviour will change in ES 8 and all JSON logs will be single lined

**Comment by Alsheh** [comment]
@pgomulka We use Docker containers for our Elasticsearch deployment and, currently, I don't see how I can tell the Ealsticsearch Filebeat module to look in a pre-defined logs path since usually the logs path contain the container ID and containers are ephemeral. Would it be possible to back port the update in ES 8 to ES 7?

**Comment by pgomulka** [comment]
I don't think this change will be backported to ES 7. This is a breaking change and will be introduced in the next major version.

ES filebeat module should be able to parse JSON logs emitted by docker containers into stdout

**Comment by Alsheh** [comment]
@pgomulka thanks for the update and happy new year! I'm going to look into how ES filebeat module can be configured with docker containers.
