### ISSUE TITLE
indices:data/read/search[phase/query/scroll

### ISSUE THREAD

**Issue by Ting-Z** [elastic/elasticsearch#66825]
version：elasticsearch-5.5.1 

```
[2020-12-27T16:12:51,064][DEBUG][o.e.a.s.TransportSearchScrollAction] [node-18] [1881582204] Failed to execute query phase
org.elasticsearch.transport.RemoteTransportException: [node-26][192.168.40.194:9300][indices:data/read/search[phase/query/scroll]]
Caused by: org.elasticsearch.search.SearchContextMissingException: No search context found for id [1881582204]
        at org.elasticsearch.search.SearchService.findContext(SearchService.java:443) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:314) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.action.search.SearchTransportService$8.messageReceived(SearchTransportService.java:350) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.action.search.SearchTransportService$8.messageReceived(SearchTransportService.java:347) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1544) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.5.1.jar:5.5.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[2020-12-27T16:12:51,064][DEBUG][o.e.a.s.TransportSearchScrollAction] [node-18-029005] [1687941879] Failed to execute query phase
org.elasticsearch.transport.RemoteTransportException: [node-30][192.168.40.205:9300][indices:data/read/search[phase/query/scroll]]
Caused by: org.elasticsearch.search.SearchContextMissingException: No search context found for id [1687941879]
        at org.elasticsearch.search.SearchService.findContext(SearchService.java:443) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:314) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.action.search.SearchTransportService$8.messageReceived(SearchTransportService.java:350) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.action.search.SearchTransportService$8.messageReceived(SearchTransportService.java:347) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1544) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-5.5.1.jar:5.5.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.5.1.jar:5.5.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by nik9000** [comment]
It looks like this is about Elasticsearch 5.5.1 which is a long time ago. Also, this is a DEBUG log. Also also, this happens when you try and do a scroll that has timed out. I believe similar things happen if you restart. Finally, this is kind of a question which sort of belongs on https://discuss.elastic.co/
