### ISSUE TITLE
ILM can get stuck in the hot phase during attempt-rollover step if rollover is removed from the policy

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#66838]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.1 on ESS

**Plugins installed**: n/a

**JVM version** (`java -version`):

```
        "vm_name" : "OpenJDK 64-Bit Server VM",
        "vm_version" : "15.0.1+9",
        "vm_vendor" : "AdoptOpenJDK"
```

**OS version** (`uname -a` if on a Unix-like system): CentOS Linux 8 (Core)

**Description of the problem including expected versus actual behavior**:

Removing the rollover action while an index is in the `check-rollover-ready` step will cause it to get stuck in the hot phase without error in ILM explain. This behavior may or may not be by design, or something ILM was not meant to do, so expected behavior could vary:

1. Allow the hot phase to complete to prevent further writes to the index and move to the next desired phase. Or,
2. Show an error in ILM explain to indicate there is a problem moving to the next step.

**Steps to reproduce**:

 1. Decrease the poll interval and up the logging.

    ```
    PUT /_cluster/settings
    {
      "persistent": {
        "indices.lifecycle.poll_interval": "1s",
        "logger.org.elasticsearch.xpack.ilm": "TRACE"
      }
    }
    ```

 1. Add an index template

    ```
    PUT /_template/devtest
    {
      "index_patterns": [
        "devtest-*"
      ],
      "settings": {
        "index": {
          "lifecycle": {
            "name": "devtest",
            "rollover_alias": "devtest"
          },
          "number_of_shards": "1",
          "number_of_replicas": "0"
        }
      }
    }
    ```

 1. Add policy version 1. Note the rollover action in the hot phase. 

    ```
    PUT /_ilm/policy/devtest
    {
      "policy": {
        "phases": {
          "hot": {
            "min_age": "0ms",
            "actions": {
              "rollover": {
                "max_size": "50mb",
                "max_age": "2m"
              }
            }
          },
          "delete": {
            "min_age": "2m",
            "actions": {
              "delete": {}
            }
          }
        }
      }
    }
    ```

1. Create the index

    ```
    PUT /devtest-000001
    {
      "aliases": {
        "devtest": {
          "is_write_index": true
        }
      }
    }
    ```

1. Let ILM perform an index rollover.

1. Create version 2 of the policy by removing the rollover action from the hot phase. The intention here is to let ILM perform index deletions per policy and prevent creation of a new index.

    ```
    PUT /_ilm/policy/devtest
    {
      "policy": {
        "phases": {
          "hot": {
            "min_age": "0ms",
            "actions": {}
          },
          "delete": {
            "min_age": "2m",
            "actions": {
              "delete": {}
            }
          }
        }
      }
    }
    ```

1. Wait a few minutes and observe the last index is stuck in the rollover action of the hot phase.

    ```
    GET /devtest/_ilm/explain
    {
      "indices" : {
        "devtest-000031" : {
          "index" : "devtest-000031",
          "managed" : true,
          "policy" : "devtest",
          "lifecycle_date_millis" : 1609189822495,
          "age" : "7.12m",
          "phase" : "hot",
          "phase_time_millis" : 1609189822954,
          "action" : "rollover",
          "action_time_millis" : 1609189825089,
          "step" : "check-rollover-ready",
          "step_time_millis" : 1609189825089,
          "phase_execution" : {
            "policy" : "devtest",
            "phase_definition" : {
              "min_age" : "0ms",
              "actions" : {
                "rollover" : {
                  "max_size" : "50mb",
                  "max_age" : "2m"
                }
              }
            },
            "version" : 3,
            "modified_date_in_millis" : 1609186540697
          }
        }
      }
    }
    ```

**Provide logs (if relevant)**:

```
[es/i-0/es.log] [2020-12-28T19:40:46.669Z][TRACE][org.elasticsearch.xpack.ilm.MoveToNextStepUpdateTask] [instance-0000000000] moving [devtest-000003] to next step ({"phase":"hot","action":"rollover","name":"attempt-rollover"})
[es/i-0/es.log] [2020-12-28T19:40:46.669Z][TRACE][org.elasticsearch.xpack.ilm.PolicyStepsRegistry] [instance-0000000000] parsed steps for policy [devtest] in phase [delete], definition: [{"policy":"devtest","phase_definition":{"min_age":"2m","actions":{"delete":{"delete_searchable_snapshot":true}}},"version":2,"modified_date_in_millis":1609184409141}], steps: [[{"phase":"delete","action":"delete","name":"wait-for-shard-history-leases"} => {"phase":"delete","action":"delete","name":"cleanup-snapshot"}, {"phase":"delete","action":"delete","name":"cleanup-snapshot"} => {"phase":"delete","action":"delete","name":"delete"}, {"phase":"delete","action":"delete","name":"delete"} => {"phase":"delete","action":"complete","name":"complete"}, {"phase":"delete","action":"complete","name":"complete"} => null]]
[es/i-0/es.log] [2020-12-28T19:40:46.674Z][ERROR][org.elasticsearch.cluster.service.MasterService] [instance-0000000000] exception thrown by listener notifying of failure from [ilm-move-to-step {policy [devtest], index [devtest-000003], currentStep [{"phase":"hot","action":"rollover","name":"check-rollover-ready"}], nextStep [{"phase":"hot","action":"rollover","name":"attempt-rollover"}]}]
org.elasticsearch.ElasticsearchException: policy [devtest] for index [devtest-000003] failed trying to move from step [{"phase":"hot","action":"rollover","name":"check-rollover-ready"}] to step [{"phase":"hot","action":"rollover","name":"attempt-rollover"}].
	at org.elasticsearch.xpack.ilm.MoveToNextStepUpdateTask.onFailure(MoveToNextStepUpdateTask.java:92) ~[?:?]
	at org.elasticsearch.cluster.service.MasterService$SafeClusterStateTaskListener.onFailure(MasterService.java:513) [elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.cluster.service.MasterService$TaskOutputs.notifyFailedTasks(MasterService.java:446) [elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:220) [elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73) [elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151) [elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) [elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.10.1.jar:7.10.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
	Suppressed: java.lang.IllegalArgumentException: step [{"phase":"hot","action":"rollover","name":"attempt-rollover"}] for index [devtest-000003] with policy [devtest] does not exist
		at org.elasticsearch.xpack.ilm.IndexLifecycleTransition.validateTransition(IndexLifecycleTransition.java:84) ~[?:?]
		at org.elasticsearch.xpack.ilm.IndexLifecycleTransition.moveClusterStateToStep(IndexLifecycleTransition.java:105) ~[?:?]
		at org.elasticsearch.xpack.ilm.MoveToNextStepUpdateTask.execute(MoveToNextStepUpdateTask.java:74) ~[?:?]
		at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) ~[elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:702) ~[elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:324) ~[elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:219) [elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73) [elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151) [elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) [elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.10.1.jar:7.10.1]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.IllegalArgumentException: step [{"phase":"hot","action":"rollover","name":"attempt-rollover"}] for index [devtest-000003] with policy [devtest] does not exist
	at org.elasticsearch.xpack.ilm.IndexLifecycleTransition.validateTransition(IndexLifecycleTransition.java:84) ~[?:?]
	at org.elasticsearch.xpack.ilm.IndexLifecycleTransition.moveClusterStateToStep(IndexLifecycleTransition.java:105) ~[?:?]
	at org.elasticsearch.xpack.ilm.MoveToNextStepUpdateTask.execute(MoveToNextStepUpdateTask.java:74) ~[?:?]
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) ~[elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:702) ~[elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:324) ~[elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:219) ~[elasticsearch-7.10.1.jar:7.10.1]
	... 10 more
```

### Use Case

The issue was discovered trying to use ILM to "dynamically" remove indices once they are no longer needed. The goal is to 1) stop creation of new indices; and 2) let ILM delete indices per the lifecycle policy.

**Comment by andreidan** [comment]
@inqueue thanks for this detailed report. I believe this is the intended behaviour (at least for now - we can try to detect this precise situation and not allow the update to the policy, but it'd be a solution that would only minimise the window of opportunity for this issue and would potentially cause frustration as the update policy call would be rejected as one managed index is currently executing an action that doesn't exist in the updated definition). 

Adding `team-discuss` to decide what the desire outcome is here (moving into the `ERROR` step is a good candidate).

With regards to the use case, does `stop creation of new indices` mean there are no more writes against the target alias? If that's the case would manually deleting the last index once no writes arrive anymore be an option? (ie. wait for `devtest-000003` to rollover so you have `devtest-000003` with data and it has to go through the rest of the lifecycle and be deleted automatically, and manually delete `devtest-000004`, which is empty, before it's rolled over)

Or is the use case about stopping rollovers, but new writes still arrive in the system and they should go in the last rolled index? If this is the case I believe removing `rollover` would expose the system to other issues (very large shards, out of disk errors, writes will fail due to the misconfiguration of the `is_write_index` for the alias after the "last" index is deleted etc) and instead tuning the rollover conditions might be needed in order to keep rollover (?)

**Comment by inqueue** [comment]
Thanks @andreidan. The use case is to "retire" the index series without expecting new writes. An error would be returned to the client if new write requests are received (like what happens when attempting to write to a read-only index. In this case, `devtest-000004` would never be created and any indices with data would age out via ILM.

**Comment by armelbd** [comment]
Here is a bit more context about why being able to "retire" an index in ILM would be something useful for what we are doing at Blizzard:

In our setup, we index a large variety of data (~1,400), each with their own mapping (strictly enforced). Since we updated to Elasticsearch 7, each data type has its own index (multiple types in same index is now depreciated).

We have an application that manage indices in our clusters, it's responsible for creating index when a new data type is registered in our system, it's also responsible for data retention policy (implemented using ILM). When there is an update to a data type, the resulting elastic mapping need to change, because we still receive data that use the two version for a short time we can't simply update the mapping of the existing index, so we create a new index with a new mapping. It's in this case that we would want to "retire" the old index.

The rational behind trying to remove the unused index is that we are constrain by the number of shards in our clusters. We are already hitting limit on number of shards per nodes, number of shards per search request etc.. so we don't want to have extra shards that are not necessary.

What we are doing by removing the "rollover" part of the ILM policy mostly works, but the remaining "orphan" index is not ideal, because that forces us to have a process that detect this case and remove it later, it would be great to have something that does this all at once and that we could trigger when we detect a version change.

**Comment by andreidan** [comment]
We discussed this today and we identified that ILM should actually honour the cached phase that still shows the rollover action (and attempt to execute the rollover action to its completion) and this is the direction we'd like to move this issue forward. This way, ILM's behaviour will be more deterministic even when the in-progress action is removed from the policy.

The cached phase is visible in the explain output and still shows `rollover`:
```
 "phase_execution" : {
        "policy" : "devtest",
        "phase_definition" : {
          "min_age" : "0ms",
          "actions" : {
            "rollover" : {
              "max_size" : "50mb",
              "max_age" : "2m"
            }
          }
        },
```
