### ISSUE TITLE
Eats some stack traces

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#6689]
I have a bug in my highlighter but I'm having trouble tracking it down because Elasticsearch is eating the stack trace from the root cause exception.  My logs:
```
Caused by: org.elasticsearch.search.fetch.FetchPhaseExecutionException: [simplewiki_content_1404072971][0]: query[filtered(+ConstantScore(_uid:page#425633) +(auxiliary_text:what auxiliary_text:love?))->cache(org.elasticsearch.index.search.nested.NonNestedDocsFilter@17097ef8)],from[0],size[10]: Fetch Failed [Failed to highlight field [auxiliary_text]]
        at org.elasticsearch.search.highlight.ExperimentalHighlighter.highlight(ExperimentalHighlighter.java:89)
        at org.elasticsearch.search.highlight.HighlightPhase.hitExecute(HighlightPhase.java:126)
        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:211)
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:340)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:751)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryFetchTransportHandler.messageReceived(SearchServiceTransportAction.java:740)
        at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.run(MessageChannelHandler.java:270)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

Why only print the name of the cause?  I'd much prefer the full, gory stack trace to show up in the logs.  It'd make it easier to reproduce the problem in a development environment.

I'm not sure where the comes from.  I certainly don't attempt to clear the stack trace any where.  The code that catches my exception and rethrows it to Elasticsearch is just:
```java
        } catch (Exception e) {
            throw new FetchPhaseExecutionException(context.context, "Failed to highlight field ["
                    + context.fieldName + "]", e);
        }
```
which seems pretty standard.

**Comment by clintongormley** [comment]
@nik9000 I think this has been resolved in recent versions, correct?
