### ISSUE TITLE
Timeout defined in the ReindexRequest is not reflecting. Client level timeout reflect always.

### ISSUE THREAD

**Issue by Ruchiragr** [elastic/elasticsearch#66913]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.6.2

**Plugins installed**: []

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**: I am trying to change the timeout on the fly for re-indexing in **RestHighLevelClient**. 

**Client Config**:
```
  elasticSearch:
    connectTimeout: 30000
    socketTimeout: 30000 
```
**High level rest client initialization**:

```
RestHighLevelClient client = new 
RestHighLevelClient(RestClient.builder(httpHost).setRequestConfigCallback(
    requestConfigBuilder -> requestConfigBuilder
        .setConnectTimeout(connectTimeout)
        .setSocketTimeout(socketTimeout));
```

**Re-indexing request**:
```
ReindexRequest request = new ReindexRequest();
request.setSourceIndices(indexName);
request.setDestIndex(destinationIndex);
request.setTimeout(new TimeValue(30000L));
```

In case of timeout exception, I am changing the timeout value in **ReindexRequest**, but updated timeout values not reflecting and original timeout set in the client still in the action.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Set 30000 milliseconds timeout to **RestHighLevelClient**. Set higher timeout value (40000 milliseconds) to **ReindexRequest**
 2. Run the re-indexing.
 3. Process will timeout after 30000 ms.

**Provide logs (if relevant)**:
java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-6 [ACTIVE]
at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
at com.dbs.digimarkets.migration.helpers.ElasticSearchMigrationHelper.doReIndexingBlotter(ElasticSearchMigrationHelper.java:181)
at com.dbs.digimarkets.migration.helpers.ElasticSearchMigrationHelper.doReIndexing(ElasticSearchMigrationHelper.java:146)
at com.dbs.digimarkets.migration.helpers.ElasticSearchMigrationHelper.doReIndexing(ElasticSearchMigrationHelper.java:153)
at com.dbs.digimarkets.migration.helpers.ElasticSearchMigrationHelper.doReIndexing(ElasticSearchMigrationHelper.java:153)
at com.dbs.digimarkets.migration.helpers.ElasticSearchMigrationHelper.doReIndexing(ElasticSearchMigrationHelper.java:153)
at com.dbs.digimarkets.migration.helpers.ElasticSearchMigrationHelper.doReIndexing(ElasticSearchMigrationHelper.java:153)
at com.dbs.digimarkets.migration.helpers.ElasticSearchMigrationHelper.doReIndexing(ElasticSearchMigrationHelper.java:153)
at com.dbs.digimarkets.migration.helpers.ElasticSearchMigrationHelper.doReIndexing(ElasticSearchMigrationHelper.java:153)
at com.dbs.digimarkets.migration.helpers.ElasticSearchMigrationHelper.migrate(ElasticSearchMigrationHelper.java:115)
at com.dbs.digimarkets.migration.MigrationManager.lambda$performMigrate$2(MigrationManager.java:44)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:502)
at com.dbs.digimarkets.migration.MigrationManager.performMigrate(MigrationManager.java:41)
at com.dbs.digimarkets.migration.MigrationManager.migrate(MigrationManager.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
at com.dbs.digimarkets.BlotterApplication.main(BlotterApplication.java:11)
Caused by: java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-6 [ACTIVE]
at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387)
at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92)
at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39)
at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:261)
at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:502)
at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:211)
at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by matriv** [comment]
@Ruchiragr In your example you set again 30000 to the ReindexRequest, guess it's a typo?
The version you are using is very old, could you try to check the behaviour with 7.10 or at least 6.8 which is still supported?

**Comment by Ruchiragr** [comment]
> @Ruchiragr In your example you set again 30000 to the ReindexRequest, guess it's a typo?
> The version you are using is very old, could you try to check the behaviour with 7.10 or at least 6.8 which is still supported?

@matriv Yes it is a typo. Corrected in the post. Let me try in the latest version too.
