### ISSUE TITLE
ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT testReloadSecureSettingsWithEmptyPassword fails with FIPS

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#66951]
**Build scan**:
https://gradle-enterprise.elastic.co/s/yzagtvaev7b36
**Repro line**:
```
./gradlew ':x-pack:qa:password-protected-keystore:integTest' --tests "org.elasticsearch.password_protected_keystore.ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT.testReloadSecureSettingsWithEmptyPassword" -Dtests.seed=2EEAA8E08B487969 -Dtests.security.manager=true -Dtests.locale=ga-IE -Dtests.timezone=MIT -Druntime.java=11 -Dtests.fips.enabled=true
```
**Reproduces locally?**:
Yes
**Applicable branches**:
master

**Failure excerpt**:
```
org.elasticsearch.password_protected_keystore.ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT > testReloadSecureSettingsWithEmptyPassword FAILED
    java.lang.AssertionError:
    Expected: ("Provided keystore password was incorrect" or "Keystore has been corrupted or tampered with")
         but: was "Error generating an encryption key from the provided password"
        at __randomizedtesting.SeedInfo.seed([2EEAA8E08B487969:60879A0A56ABEB4E]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.password_protected_keystore.ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT.testReloadSecureSettingsWithEmptyPassword(ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT.java:80
```

**Comment by jkakavas** [comment]
Duplicate of https://github.com/elastic/elasticsearch/issues/66880
