### ISSUE TITLE
SearchableSnapshotsIntegTests testCreateAndRestoreSearchableSnapshot failure

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#66958]
**Build scan**:
https://gradle-enterprise.elastic.co/s/zuplpddr4zy6k
**Repro line**:
```
gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testCreateAndRestoreSearchableSnapshot" -Dtests.seed=2CE33D36FC2EB66F -Dtests.security.manager=true -Dtests.locale=is -Dtests.timezone=America/Recife -Druntime.java=11
```
**Reproduces locally?**:
No, but this was a windows build and I don't run windows locally
**Applicable branches**:
master
**Failure excerpt**:
```

org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests > testCreateAndRestoreSearchableSnapshot FAILED |  
-- | --
  | com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=908, name=elasticsearch[node_s1][generic][T#2], state=RUNNABLE, group=TGRP-SearchableSnapshotsIntegTests] |  
  | at __randomizedtesting.SeedInfo.seed([2CE33D36FC2EB66F:A6804A4D6FB9E7DC]:0) |  
  |   |  
  | Caused by: |  
  | java.lang.AssertionError: shard eviction should be successful: [snapshotUUID=vHhGCWjPQtGXn6mwBTZOuw, snapshotIndexName=riiwtkwzmp, shardId=[riiwtkwzmp][2]] |  
  | at __randomizedtesting.SeedInfo.seed([2CE33D36FC2EB66F]:0) |  
  | at org.elasticsearch.xpack.searchablesnapshots.cache.CacheService.runIfShardMarkedAsEvictedInCache(CacheService.java:412) |  
  | at org.elasticsearch.xpack.searchablesnapshots.cache.CacheService$1.doRun(CacheService.java:351) |  
  | at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) |  
  | at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) |  
  | at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) |  
  | at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:680) |  
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) |  
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) |  
  | at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by javanna** [comment]
Another one: https://gradle-enterprise.elastic.co/s/giq2coadc6q2k

**Comment by tlrx** [comment]
The shard eviction mechanism has been improved in #67160 and the failing assertion removed in #67265, this should now be fixed so I'm closing this issue.
