### ISSUE TITLE
Many fips related: " Error generating an encryption key from the provided password	" failures

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#66953]
**Build scan**:
https://gradle-enterprise.elastic.co/s/pv6fvk3ax6i54
**Repro line**:
many different tests:

```
./gradlew ':distribution:tools:keystore-cli:test' --tests "org.elasticsearch.common.settings.UpgradeKeyStoreCommandTests.testKeystoreUpgrade" -Dtests.seed=27F0CA12B7EDBFC1 -Dtests.security.manager=true -Dtests.locale=ja-JP -Dtests.timezone=Europe/Vilnius -Druntime.java=14 -Dtests.fips.enabled=true
```

```
./gradlew ':distribution:tools:keystore-cli:test' --tests "org.elasticsearch.bootstrap.BootstrapTests.testLoadSecureSettings" -Dtests.seed=27F0CA12B7EDBFC1 -Dtests.security.manager=true -Dtests.locale=es-NI -Dtests.timezone=America/Antigua -Druntime.java=14 -Dtests.fips.enabled=true
```

```
./gradlew ':distribution:tools:keystore-cli:test' --tests "org.elasticsearch.common.settings.AddFileKeyStoreCommandTests.testAddToUnprotectedKeystore" -Dtests.seed=27F0CA12B7EDBFC1 -Dtests.security.manager=true -Dtests.locale=pt-BR -Dtests.timezone=America/Cordoba -Druntime.java=14 -Dtests.fips.enabled=true
```

and more

**Reproduces locally?**:
no
**Applicable branches**:
master

**Failure excerpt**:
All of the test failures have some form like this:

```
org.elasticsearch.common.settings.AddFileKeyStoreCommandTests > testAddToUnprotectedKeystore FAILED |  
-- | --
  | java.security.GeneralSecurityException: Error generating an encryption key from the provided password |  
  | at __randomizedtesting.SeedInfo.seed([27F0CA12B7EDBFC1:20A8D30787D6E56A]:0) |  
  | at org.elasticsearch.common.settings.KeyStoreWrapper.createCipher(KeyStoreWrapper.java:319) |  
  | at org.elasticsearch.common.settings.KeyStoreWrapper.encrypt(KeyStoreWrapper.java:401) |  
  | at org.elasticsearch.common.settings.KeyStoreWrapper.save(KeyStoreWrapper.java:510) |  
  | at org.elasticsearch.common.settings.KeyStoreCommandTestCase.createKeystore(KeyStoreCommandTestCase.java:82) |  
  | at org.elasticsearch.common.settings.AddFileKeyStoreCommandTests.testAddToUnprotectedKeystore(AddFileKeyStoreCommandTests.java:216) |  
  |   |  
  | Caused by: |  
  | org.bouncycastle.crypto.fips.FipsUnapprovedOperationError: password must be at least 112 bits |  
  | at org.bouncycastle.crypto.fips.FipsPBKD$Parameters.<init>(Unknown Source) |  
  | at org.bouncycastle.crypto.fips.FipsPBKD$Parameters.<init>(Unknown Source) |  
  | at org.bouncycastle.crypto.fips.FipsPBKD$ParametersBuilder.using(Unknown Source) |  
  | at org.bouncycastle.jcajce.provider.ProvPBEPBKDF2$BasePBKDF2.engineGenerateSecret(Unknown Source) |  
  | at java.base/javax.crypto.SecretKeyFactory.generateSecret(SecretKeyFactory.java:340) |  
  | at org.elasticsearch.common.settings.KeyStoreWrapper.createCipher(KeyStoreWrapper.java:315) |  
  | ... 4 more
```

NOTE: * org.bouncycastle.crypto.fips.FipsUnapprovedOperationError: password must be at least 112 bits*

Other issues: https://github.com/elastic/elasticsearch/issues/66880

https://github.com/elastic/elasticsearch/issues/66951

**Comment by jkakavas** [comment]
Thia is https://github.com/elastic/elasticsearch/issues/66845,  backport is pending for 7.x , 7.11, @ywangd will be looking at raising the backports tomorrow. Closing this and reopening 66845
