### ISSUE TITLE
ChangePolicyforIndexIT testChangePolicyForIndex test failure 

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#66960]
Expected `complete`, but was `allocate`

**Build scan**:
https://gradle-enterprise.elastic.co/s/zmpvqpicbtda4
**Repro line**:
```
./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.ChangePolicyforIndexIT.testChangePolicyForIndex" -Dtests.seed=EECC349DA8CBF60F -Dtests.security.manager=true -Dtests.locale=et -Dtests.timezone=Pacific/Majuro -Druntime.java=8
```

**Reproduces locally?**:
No, (but I don't have windows)
**Applicable branches**:
7.11
**Failure excerpt**:
```
org.elasticsearch.xpack.ilm.ChangePolicyforIndexIT > testChangePolicyForIndex FAILED |  
-- | --
  | org.junit.ComparisonFailure: expected:<[comple]te> but was:<[alloca]te> |  
  | at __randomizedtesting.SeedInfo.seed([EECC349DA8CBF60F:FDD60DC658E25FF]:0) |  
  | at org.junit.Assert.assertEquals(Assert.java:115) |  
  | at org.junit.Assert.assertEquals(Assert.java:144) |  
  | at org.elasticsearch.xpack.ilm.ChangePolicyforIndexIT.assertStep(ChangePolicyforIndexIT.java:132) |  
  | at org.elasticsearch.xpack.ilm.ChangePolicyforIndexIT.lambda$testChangePolicyForIndex$2(ChangePolicyforIndexIT.java:116) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1016) |  
  | at org.elasticsearch.xpack.ilm.ChangePolicyforIndexIT.testChangePolicyForIndex(ChangePolicyforIndexIT.java:116)
```

There were other test failures in the same build. Another was for a separate integration class (same suite) and failed similarly (allocated while expecting completed).
```
org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT > testAllocateOnlyAllocation FAILED |  
-- | --
  | java.lang.AssertionError: |  
  | Expected: <{"phase":"cold","action":"complete","name":"complete"}> |  
  | but: was <{"phase":"cold","action":"allocate","name":"check-allocation"}> |  
  | at __randomizedtesting.SeedInfo.seed([EECC349DA8CBF60F:A87251BFB4215803]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.junit.Assert.assertThat(Assert.java:923) |  
  | at org.elasticsearch.xpack.ilm.TimeSeriesLifecycleActionsIT.lambda$testAllocateOnlyAllocation$20(TimeSeriesLifecycleActionsIT.java:281) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1016) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:989)
```

**Comment by martijnvg** [comment]
This failure has returned on the 7.x branch: https://gradle-enterprise.elastic.co/s/hp7qkvwtbgc4g
(first failure since February 23)

With:

```
org.junit.ComparisonFailure: expected:<[warm]> but was:<[hot]> |  
-- | --
at __randomizedtesting.SeedInfo.seed([F3630ABC73D51F20:12725EFDBE90CCD0]:0) |  
-- | --
  |   | •••
  |   | at org.elasticsearch.xpack.ilm.ChangePolicyforIndexIT.assertStep(ChangePolicyforIndexIT.java:134) |  
  |   | at org.elasticsearch.xpack.ilm.ChangePolicyforIndexIT.lambda$testChangePolicyForIndex$2(ChangePolicyforIndexIT.java:119) |  
  |   | •••
  |   | at org.elasticsearch.xpack.ilm.ChangePolicyforIndexIT.testChangePolicyForIndex(ChangePolicyforIndexIT.java:119)
```
