### ISSUE TITLE
ProactiveStorageIT testScaleUp failure

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#66961]
**Build scan**:
https://gradle-enterprise.elastic.co/s/3ihlmaqmkfnl2
**Repro line**:
```
./gradlew ':x-pack:plugin:autoscaling:internalClusterTest' --tests "org.elasticsearch.xpack.autoscaling.storage.ProactiveStorageIT.testScaleUp" -Dtests.seed=4DA9CBCE483D3B7F -Dtests.security.manager=true -Dtests.locale=sq-AL -Dtests.timezone=America/Fort_Nelson -Druntime.java=8
```
**Reproduces locally?**:
no
**Applicable branches**:
7.11

**Failure excerpt**:
```
org.elasticsearch.xpack.autoscaling.storage.ProactiveStorageIT > testScaleUp FAILED |  
-- | --
  | java.lang.AssertionError: |  
  | Expected: a value equal to or greater than <33163L> |  
  | but: <21702L> was less than <33163L> |  
  | at __randomizedtesting.SeedInfo.seed([4DA9CBCE483D3B7F:6CF78D6C4413E5DE]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.junit.Assert.assertThat(Assert.java:923) |  
  | at org.elasticsearch.xpack.autoscaling.storage.ProactiveStorageIT.testScaleUp(ProactiveStorageIT.java:106)
```

Seems like simply a flakey test. Didn't reproduce locally though with the same seed.

**Comment by henningandersen** [comment]
Same as #66864
