### ISSUE TITLE
Hadoop Kerberos fixture failure with OpenJDK 16

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#66972]
**Build scan**: https://gradle-enterprise.elastic.co/s/6govaxtzeouze

**Repro line**:
There is no reproduction line, but I think it should be something like `./gradlew :x-pack:plugin:searchable-snapshots:qa:hdfs:secureHdfsFixture`.

**Reproduces locally?**:
Don't have JDK 16 locally yet. But above line works fine with 15.

**Applicable branches**:
master, 7.x

**Failure history**:

This failure is specific to OpenJDK 16 as shown by gradle enterprise [records](https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20*%0A%3E%20Failed%20to%20start%20secureHdfsFixture&search.relativeStartTime=P7D&search.timeZoneId=Australia/Melbourne).

**Failure excerpt**:
```
  [run]
    "/var/lib/jenkins/.java/openjdk16/bin/java" "$@" > run.log 2>&1 ; if [ $? != 0 ]; then touch run.failed; fi
secureHdfsFixture output:
-----------------------------------------
  failure marker exists: true
  pid file exists: false
  ports file exists: false

  [log]
    Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
    Exception in thread "main" java.lang.IllegalArgumentException: Can't get Kerberos realm
    	at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:65)
    	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:296)
    	at org.apache.hadoop.security.UserGroupInformation.setConfiguration(UserGroupInformation.java:342)
    	at hdfs.MiniHDFS.main(MiniHDFS.java:99)
    Caused by: java.lang.IllegalAccessException: class org.apache.hadoop.security.authentication.util.KerberosUtil cannot access class sun.security.krb5.Config (in module java.security.jgss) because module java.security.jgss does not export sun.security.krb5 to unnamed module @209c0b14
    	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:385)
    	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:687)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:559)
    	at org.apache.hadoop.security.authentication.util.KerberosUtil.getDefaultRealm(KerberosUtil.java:107)
    	at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:63)
    	... 3 more
```

**Comment by ywangd** [comment]
Another one with 7.x: https://gradle-enterprise.elastic.co/s/74bobxbd2tdnu
