### ISSUE TITLE
[CI] DocumentFieldTests.testToAndFromXContent fails reproducibly on master

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#67018]
**Build scan**:
https://gradle-enterprise.elastic.co/s/okfzo7ptu7dpu

**Repro line**:
```
./gradlew ':server:test' --tests "org.elasticsearch.index.get.DocumentFieldTests.testToAndFromXContent" -Dtests.seed=F175C551A1255CE3 -Dtests.security.manager=true -Dtests.locale=mk-MK -Dtests.timezone=Mexico/BajaNorte -Druntime.java=11
```

**Reproduces locally?**:
Yep!

**Applicable branches**:
Master

**Failure history**:
This was a local failure while working on different work

**Failure excerpt**:

```
org.elasticsearch.index.get.DocumentFieldTests > testToAndFromXContent FAILED
    java.lang.AssertionError: expected: org.elasticsearch.common.document.DocumentField<DocumentField{name='nTVya', values=[0.69425505, 0.79453, 0.9221062, 0.24998319, 0.9083719]}> but was: org.elasticsearch.common.document.DocumentField<DocumentField{name='nTVya', values=[0.69425505, 0.79453, 0.9221062, 0.24998319, 0.9083719]}>
        at __randomizedtesting.SeedInfo.seed([F175C551A1255CE3:DF5C6FDBC35A271F]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.elasticsearch.index.get.DocumentFieldTests.testToAndFromXContent(DocumentFieldTests.java:77)
```

**Comment by DaveCTurner** [comment]
Probably the same thing as https://github.com/elastic/elasticsearch/issues/67009
