### ISSUE TITLE
GetResultTests.testToAndFromXContentEmbedded failure

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#67064]
**Build scan**: N/A, local build. 

**Repro line**:
./gradlew ':server:test' --tests "org.elasticsearch.index.get.GetResultTests.testToAndFromXContentEmbedded" -Dtests.seed=E5FC519FC1275FEB -Dtests.security.manager=true -Dtests.locale=ar-AE -Dtests.timezone=Africa/Blantyre -Druntime.java=15

**Reproduces locally?**:
Yes

**Applicable branches**:
master

**Failure excerpt**:

<details><summary>Failure Details</summary>
<p>

```
Suite: Test class org.elasticsearch.index.get.GetResultTests
  1> [2021-01-06T03:49:14,797][INFO ][o.e.i.g.GetResultTests   ] [testToAndFromXContentEmbedded] before test
  1> [2021-01-06T03:49:15,006][INFO ][o.e.i.g.GetResultTests   ] [testToAndFromXContentEmbedded] after test
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.index.get.GetResultTests.testToAndFromXContentEmbedded" -Dtests.seed=E5FC519FC1275FEB -Dtests.security.manager=true -Dtests.locale=ar-AE -Dtests.timezone=Africa/Blantyre -Druntime.java=15
  2> java.lang.AssertionError: expected:<{
      "_index" : null,
      "_id" : null,
      "_seq_no" : 193165536962485811,
      "_primary_term" : 71,
      "_nested_path" : "Rmhd",
      "_routing" : "VYZsPS",
      "found" : true,
      "_source" : {
        "cDdkOed" : {
          "kIOmfBuye" : -4355782572476556875
        },
        "CHPTRkb" : 0.1974391328248285,
        "ngifuk" : "SIisj",
        "YjVWYCSNxE" : {
          "fErBpnn" : [
            {
              "pgdJSUie" : "KYm",
              "LAMHSFzle" : 0.5538381620236812
            },
            {
              "xJWtzXYOzq" : 2501515057617439655,
              "uILBlbRl" : "CYOBNHnQgQ",
              "kPYyInFAX" : 0.7238725410136407,
              "kegvNLXO" : -6906501997487968558,
              "QRRCPof" : 0.06681025923342088
            },
            {
              "EWvLpm" : "ZYBSyKZl",
              "VKbUdec" : 0.8878569548237388,
              "mkvlDUag" : 0.035264934026060124,
              "cysyqBfZvG" : "fCnF",
              "DWiIKgq" : "duJkfxQLUh"
            },
            {
              "XpiKBYLTYV" : 0.8365711755598817,
              "nEDSFe" : "NwGW",
              "gPlQFoaTqV" : 0.6106422641750852,
              "KApbrEZv" : -3187916961566692938,
              "YsLfTgF" : "HptyaRpTW"
            },
            {
              "EtCSBHjKHV" : 2032070882424922864,
              "XjtZKWu" : "aluUN",
              "cdsLri" : 646340918915008831,
              "xrYZLhjvg" : "qupmRsWQoA"
            }
          ]
        }
      },
      "fields" : {
        "dFszYoJZbp" : [
          "7qCb6oSJ8bGYgtic1pRLFNWN5Yu+8baHptebCvGpmaXzk5it6ZqjUee7rfKViLRdBMyJ3qfzg42AyZfun4nziLm17qK+8724hs+t7o2E7oSv7riW6KWnH+Woqe6ihe+MmOSFo3A="
        ],
        "jTooydPG" : [
          0.4488774315814221,
          0.23740623389882665,
          0.6111549990330503,
          0.6939449725143741,
          0.4813573856150549
        ],
        "POYUYSDipG" : [
          "lIT"
        ],
        "FQirH" : [
          {
            "pzrOO" : false,
            "xpySH" : "PrsvrkaFxc",
            "Nfuue" : -445787976
          }
        ],
        "ajOPP" : [
          {
            "PxdIx" : 515179785,
            "jYEEp" : "aAmcBIYApR",
            "BqGTY" : false
          },
          {
            "JRerP" : "xjecjpuTHz",
            "ONjWt" : 833395824,
            "tcZYJ" : false
          },
          {
            "Rfyki" : 886453855,
            "fcNqw" : false,
            "obrYj" : "FDxlDkRXFo"
          },
          {
            "fzSZH" : 1344392580,
            "vsHAr" : false,
            "NkxTf" : "FKZZYrNqIn"
          },
          {
            "dSMsD" : "zyTpYzfuqT",
            "wzqdI" : 1140600156,
            "CXNJw" : true
          }
        ]
      }
    }> but was:<{
      "_index" : null,
      "_id" : null,
      "_seq_no" : 193165536962485811,
      "_primary_term" : 71,
      "_routing" : "VYZsPS",
      "_nested_path" : "Rmhd",
      "found" : true,
      "_source" : {
        "cDdkOed" : {
          "kIOmfBuye" : -4355782572476556875
        },
        "CHPTRkb" : 0.1974391328248285,
        "ngifuk" : "SIisj",
        "YjVWYCSNxE" : {
          "fErBpnn" : [
            {
              "pgdJSUie" : "KYm",
              "LAMHSFzle" : 0.5538381620236812
            },
            {
              "xJWtzXYOzq" : 2501515057617439655,
              "uILBlbRl" : "CYOBNHnQgQ",
              "kPYyInFAX" : 0.7238725410136407,
              "kegvNLXO" : -6906501997487968558,
              "QRRCPof" : 0.06681025923342088
            },
            {
              "EWvLpm" : "ZYBSyKZl",
              "VKbUdec" : 0.8878569548237388,
              "mkvlDUag" : 0.035264934026060124,
              "cysyqBfZvG" : "fCnF",
              "DWiIKgq" : "duJkfxQLUh"
            },
            {
              "XpiKBYLTYV" : 0.8365711755598817,
              "nEDSFe" : "NwGW",
              "gPlQFoaTqV" : 0.6106422641750852,
              "KApbrEZv" : -3187916961566692938,
              "YsLfTgF" : "HptyaRpTW"
            },
            {
              "EtCSBHjKHV" : 2032070882424922864,
              "XjtZKWu" : "aluUN",
              "cdsLri" : 646340918915008831,
              "xrYZLhjvg" : "qupmRsWQoA"
            }
          ]
        }
      },
      "fields" : {
        "FQirH" : [
          {
            "pzrOO" : false,
            "xpySH" : "PrsvrkaFxc",
            "Nfuue" : -445787976
          }
        ],
        "dFszYoJZbp" : [
          "7qCb6oSJ8bGYgtic1pRLFNWN5Yu+8baHptebCvGpmaXzk5it6ZqjUee7rfKViLRdBMyJ3qfzg42AyZfun4nziLm17qK+8724hs+t7o2E7oSv7riW6KWnH+Woqe6ihe+MmOSFo3A="
        ],
        "jTooydPG" : [
          0.4488774315814221,
          0.23740623389882665,
          0.6111549990330503,
          0.6939449725143741,
          0.4813573856150549
        ],
        "POYUYSDipG" : [
          "lIT"
        ],
        "ajOPP" : [
          {
            "PxdIx" : 515179785,
            "jYEEp" : "aAmcBIYApR",
            "BqGTY" : false
          },
          {
            "JRerP" : "xjecjpuTHz",
            "ONjWt" : 833395824,
            "tcZYJ" : false
          },
          {
            "Rfyki" : 886453855,
            "fcNqw" : false,
            "obrYj" : "FDxlDkRXFo"
          },
          {
            "fzSZH" : 1344392580,
            "vsHAr" : false,
            "NkxTf" : "FKZZYrNqIn"
          },
          {
            "dSMsD" : "zyTpYzfuqT",
            "wzqdI" : 1140600156,
            "CXNJw" : true
          }
        ]
      }
    }>
        at __randomizedtesting.SeedInfo.seed([E5FC519FC1275FEB:B5959AD1926D8B93]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.elasticsearch.index.get.GetResultTests.testToAndFromXContentEmbedded(GetResultTests.java:120)
```
</p>
</details>

**Comment by DaveCTurner** [comment]
Hmm this looks very similar to https://github.com/elastic/elasticsearch/issues/67009 except that this one is still failing in `master` (as of 520c44706ec41328e99f6338b100e729c38f1a89). @pgomulka would you take a look at this one too?
