### ISSUE TITLE
[CI] ChainingInputStreamTests.testResetForDoubleMarkAnywhere fails

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#67086]
The test `ChainingInputStreamTests.testResetForDoubleMarkAnywhere` failed today on 7.x. It looks related to #66773.

**Build scan**:
https://gradle-enterprise.elastic.co/s/com46ut5ehh3m

**Repro line**:
```
./gradlew ':x-pack:plugin:repository-encrypted:test' --tests "org.elasticsearch.repositories.encrypted.ChainingInputStreamTests.testResetForDoubleMarkAnywhere" -Dtests.seed=4DFDD6C0D64E8F93 -Dtests.security.manager=true -Dtests.locale=en-IN -Dtests.timezone=America/Martinique
```

**Reproduces locally?**:
Yes

**Applicable branches**:
7.x and master

**Failure history**:
Failed once [today](https://build-stats.elastic.co/app/kibana#/doc/b646ed00-7efc-11e8-bf69-63c8ef516157/build-*/t?id=20210106105716-15DECE39&_g=())

**Failure excerpt**:

> org.elasticsearch.repositories.encrypted.ChainingInputStreamTests > testResetForDoubleMarkAnywhere FAILED
    org.mockito.exceptions.verification.TooManyActualInvocations: 
    inputStream.mark(24);
    Wanted 1 time:
    -> at org.elasticsearch.repositories.encrypted.ChainingInputStreamTests.testResetForDoubleMarkAnywhere(ChainingInputStreamTests.java:944)
    But was 2 times. Undesired invocation:
    -> at org.elasticsearch.repositories.encrypted.ChainingInputStream.mark(ChainingInputStream.java:336)
        at __randomizedtesting.SeedInfo.seed([4DFDD6C0D64E8F93:D154BBE6C69B1473]:0)
        at org.elasticsearch.repositories.encrypted.ChainingInputStreamTests.testResetForDoubleMarkAnywhere(ChainingInputStreamTests.java:944)

**Comment by tlrx** [comment]
Test is muted on master and 7.x.
