### ISSUE TITLE
[CI] DockerTests.test085EnvironmentVariablesAreRespectedUnderDockerExec fails with missing keystore file

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#67097]
This test `DockerTests.test085EnvironmentVariablesAreRespectedUnderDockerExec` fails everyday on master, 7.11, 7.10 or 7.x. Another issue #66656 is opened for this test but the error is different so I'm opening a new issue.

**Build scans**:
https://gradle-enterprise.elastic.co/s/jkuoddwnkjkzs
https://gradle-enterprise.elastic.co/s/pxr65mf6xmhqs
https://gradle-enterprise.elastic.co/s/gy5sbg4msiycw

**Applicable branches**:
master, 7.x, 7.11 and 7.10

**Failure history**:
Build history shows [many failures](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2020-11-07T13:31:46.218Z',mode:absolute,to:'2021-01-06T13:31:46.220Z'))&_a=(columns:!(branch,test),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'test:%22test085EnvironmentVariablesAreRespectedUnderDockerExec%22'),sort:!(time,desc))) over the last month.

**Failure excerpt**:
```
org.elasticsearch.packaging.test.DockerTests > test085EnvironmentVariablesAreRespectedUnderDockerExec FAILED
    java.lang.AssertionError: 
    Expected: a string containing "java.net.UnknownHostException: this.is.not.valid: Name or service not known"
         but: was "ERROR: Elasticsearch keystore file is missing [/usr/share/elasticsearch/config/elasticsearch.keystore]"
        at __randomizedtesting.SeedInfo.seed([23D04474A3D733E1:857F2D053C98986E]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.packaging.test.DockerTests.test085EnvironmentVariablesAreRespectedUnderDockerExec(DockerTests.java:486)
```

**Comment by tlrx** [comment]
I muted this test on master, 7.x, 7.11 and 7.10
