### ISSUE TITLE
[CI] RecoveryIT.testRecoveryWithConcurrentIndexing fails

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#67124]
**Build scan**:
https://gradle-enterprise.elastic.co/s/7boqrvei54mne
**Repro line**:
```
./gradlew ':qa:rolling-upgrade:v7.12.0#twoThirdsUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.RecoveryIT" -Dtests.method="testRecoveryWithConcurrentIndexing" -Dtests.seed=9539A846383D3E46 -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=sr-BA -Dtests.timezone=Africa/Maputo -Druntime.java=11
```
**Reproduces locally?**:
No
**Applicable branches**:
master
**Failure history**:

**Failure excerpt**:
```
[2021-01-06T21:35:34,643][INFO ][o.e.u.RecoveryIT         ] [testRecoveryWithConcurrentIndexing] before test
[2021-01-06T21:36:45,279][INFO ][o.e.u.RecoveryIT         ] [testRecoveryWithConcurrentIndexing] after test
REPRODUCE WITH: ./gradlew ':qa:rolling-upgrade:v7.12.0#twoThirdsUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.RecoveryIT" -Dtests.method="testRecoveryWithConcurrentIndexing" -Dtests.seed=9539A846383D3E46 -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=sr-BA -Dtests.timezone=Africa/Maputo -Druntime.java=11

java.lang.AssertionError: timed out waiting for green state for index [recovery_with_concurrent_indexing] cluster state [{ |  
...
```

This looks like a cluster got stuck on upgrade as the following tests also failed similarly:
```
testAutoExpandIndicesDuringRollingUpgrade
testUpdateDoc
testOperationBasedRecovery
IndexingIT
  testIndexing
  testAutoIdWithOpTypeCreate
```

**Comment by stu-elastic** [comment]
Console log: [7boqrvei54mne-console-log.txt.gz](https://github.com/elastic/elasticsearch/files/5778059/7boqrvei54mne-console-log.txt.gz)

**Comment by ywelsch** [comment]
```
»  java.lang.AssertionError: expected current mapping [{"task":{"dynamic":"strict","_meta":{"version":"7.12.0"},"properties":{"completed":{"type":"boolean"},"error":{"type":"object","enabled":false},"response":{"type":"object","enabled":false},"task":{"properties":{"action":{"type":"keyword"},"cancellable":{"type":"boolean"},"description":{"type":"text"},"headers":{"type":"object","enabled":false},"id":{"type":"long"},"node":{"type":"keyword"},"parent_task_id":{"type":"keyword"},"running_time_in_nanos":{"type":"long"},"start_time_in_millis":{"type":"long"},"status":{"type":"object","enabled":false},"type":{"type":"keyword"}}}}}}] for type [task] to be the same as new mapping [{"task":{"dynamic":"strict","_meta":{"version":"8.0.0"},"properties":{"completed":{"type":"boolean"},"error":{"type":"object","enabled":false},"response":{"type":"object","enabled":false},"task":{"properties":{"action":{"type":"keyword"},"cancellable":{"type":"boolean"},"description":{"type":"text"},"headers":{"type":"object","enabled":false},"id":{"type":"long"},"node":{"type":"keyword"},"parent_task_id":{"type":"keyword"},"running_time_in_nanos":{"type":"long"},"start_time_in_millis":{"type":"long"},"status":{"type":"object","enabled":false},"type":{"type":"keyword"}}}}}}]
»  	at org.elasticsearch.index.mapper.MapperService.assertMappingVersion(MapperService.java:310)
»  	at org.elasticsearch.index.mapper.MapperService.updateMapping(MapperService.java:222)
»  	at org.elasticsearch.index.IndexService.updateMapping(IndexService.java:667)
»  	at org.elasticsearch.indices.cluster.IndicesClusterStateService.updateIndices(IndicesClusterStateService.java:531)
»  	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:245)
»  	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:510)
»  	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:500)
»  	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:471)
»  	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:418)
»  	at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:68)
»  	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTas
```

It's same as https://github.com/elastic/elasticsearch/issues/67010

**Comment by stu-elastic** [comment]
Thanks @ywelsch, missed that one.
