### ISSUE TITLE
[CI][7.10] RateAggregatorTests.testKeywordSandwich ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by probakowski** [elastic/elasticsearch#67144]
**Build scan**:
https://gradle-enterprise.elastic.co/s/zk6g67adnacla
**Repro line**:
`./gradlew ':x-pack:plugin:analytics:test' --tests "org.elasticsearch.xpack.analytics.rate.RateAggregatorTests.testKeywordSandwich" -Dtests.seed=5595149044FEF48C -Dtests.security.manager=true -Dtests.locale=ru-RU -Dtests.timezone=America/Montreal -Druntime.java=8`
**Reproduces locally?**:
yes
**Applicable branches**:
7.10 only (works fine in 7.11, 7.x and master)
**Failure history**:
No other failures in last 28 days
**Failure excerpt**:
```
java.lang.ArrayIndexOutOfBoundsException: 1 
  | at __randomizedtesting.SeedInfo.seed([5595149044FEF48C:F587266809F38538]:0) |  
  | at org.elasticsearch.common.util.BigArrays$LongArrayWrapper.get(BigArrays.java:220) |  
  | at org.elasticsearch.common.util.MockBigArrays$LongArrayWrapper.get(MockBigArrays.java:420) |  
  | at org.elasticsearch.common.util.LongHash.get(LongHash.java:51) |  
  | at org.elasticsearch.search.aggregations.bucket.terms.LongKeyedBucketOrds$FromSingle.get(LongKeyedBucketOrds.java:143) |  
  | at org.elasticsearch.search.aggregations.bucket.histogram.DateHistogramAggregator.bucketSize(DateHistogramAggregator.java:194) |  
  | at org.elasticsearch.xpack.analytics.rate.RateAggregator.buildAggregation(RateAggregator.java:123) |  
  | at org.elasticsearch.search.aggregations.metrics.MetricsAggregator.buildAggregations(MetricsAggregator.java:51) |  
  | at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildSubAggsForBuckets(BucketsAggregator.java:192) |  
  | at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildSubAggsForAllBuckets(BucketsAggregator.java:255) |  
  | at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator.access$700(GlobalOrdinalsStringTermsAggregator.java:67) |  
  | at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator$StandardTermsResults.buildSubAggs(GlobalOrdinalsStringTermsAggregator.java:738) |  
  | at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator$StandardTermsResults.buildSubAggs(GlobalOrdinalsStringTermsAggregator.java:688) |  
  | at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator$ResultStrategy.buildAggregations(GlobalOrdinalsStringTermsAggregator.java:604) |  
  | at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator$ResultStrategy.access$200(GlobalOrdinalsStringTermsAggregator.java:553) |  
  | at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator.buildAggregations(GlobalOrdinalsStringTermsAggregator.java:197) |  
  | at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildSubAggsForBuckets(BucketsAggregator.java:192) |  
  | at org.elasticsearch.search.aggregations.bucket.BucketsAggregator.buildAggregationsForVariableBuckets(BucketsAggregator.java:349) |  
  | at org.elasticsearch.search.aggregations.bucket.histogram.DateHistogramAggregator.buildAggregations(DateHistogramAggregator.java:150) |  
  | at org.elasticsearch.search.aggregations.Aggregator.buildTopLevel(Aggregator.java:160) |  
  | at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:463) |  
  | at org.elasticsearch.search.aggregations.AggregatorTestCase.searchAndReduce(AggregatorTestCase.java:405) |  
  | at org.elasticsearch.search.aggregations.AggregatorTestCase.testCase(AggregatorTestCase.java:524) |  
  | at org.elasticsearch.xpack.analytics.rate.RateAggregatorTests.testKeywordSandwich(RateAggregatorTests.java:298)


```

**Comment by nik9000** [comment]
Hasn't failed since February 9th.
