### ISSUE TITLE
FrozenIndexIT.testRetryPointInTime

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#67307]
May be this is just one off failure, and should be ignored. Please feel free to close

**Build scan**:
https://gradle-enterprise.elastic.co/s/3tlvmqrujbggq

**Repro line**:
./gradlew ':x-pack:plugin:frozen-indices:internalClusterTest' --tests "org.elasticsearch.index.engine.FrozenIndexIT.testRetryPointInTime" -Dtests.seed=DCA39E4A873000C6 -Dtests.security.manager=true -Dtests.locale=ar-LB -Dtests.timezone=Europe/Skopje -Druntime.java=11	

**Reproduces locally?**:
no

**Applicable branches**:
was failed on PR for master branch

**Failure history**:

**Failure excerpt**:
```bash

java.lang.AssertionError: Unexpected ShardFailures: [shard [[UYO248ViTFGMo9H2xCimwQ][test][0]], reason [org.elasticsearch.transport.RemoteTransportException: [node_s0][127.0.0.1:34427][indices:data/read/search[phase/fetch/id]] |  
-- | --
  | Caused by: org.elasticsearch.search.SearchContextMissingException: No search context found for id [1] |  
  | at org.elasticsearch.search.SearchService.findReaderContext(SearchService.java:623) |  
  | at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:586) |  
  | at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$12(SearchTransportService.java:363) |  
  | at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:72) |  
  | at org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:805) |  
  | at org.elasticsearch.transport.TransportService$3.sendRequest(TransportService.java:125) |  
  | at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:749) |  
  | at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:663) |  
  | at org.elasticsearch.transport.TransportService.sendChildRequest(TransportService.java:714) |  
  | at org.elasticsearch.transport.TransportService.sendChildRequest(TransportService.java:706) |  
  | at org.elasticsearch.action.search.SearchTransportService.sendExecuteFetch(SearchTransportService.java:182) |  
  | at org.elasticsearch.action.search.SearchTransportService.sendExecuteFetch(SearchTransportService.java:172) |  
  | at org.elasticsearch.action.search.FetchSearchPhase.executeFetch(FetchSearchPhase.java:176) |  
  | at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:156) |  
  | at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:95) |  
  | at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) |  
  | at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) |  
  | at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:739) |  
  | at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) |  
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) |  
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) |  
  | at java.base/java.lang.Thread.run(Thread.java:834) |  
  | ], cause [org.elasticsearch.search.SearchContextMissingException: No search context found for id [1] |  
  | at org.elasticsearch.search.SearchService.findReaderContext(SearchService.java:623) |  
  | at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:586) |  
  | at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$12(SearchTransportService.java:363) |  
  | at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:72) |  
  | at org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:805) |  
  | at org.elasticsearch.transport.TransportService$3.sendRequest(TransportService.java:125) |  
  | at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:749) |  
  | at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:663) |  
  | at org.elasticsearch.transport.TransportService.sendChildRequest(TransportService.java:714) |  
  | at org.elasticsearch.transport.TransportService.sendChildRequest(TransportService.java:706) |  
  | at org.elasticsearch.action.search.SearchTransportService.sendExecuteFetch(SearchTransportService.java:182) |  
  | at org.elasticsearch.action.search.SearchTransportService.sendExecuteFetch(SearchTransportService.java:172) |  
  | at org.elasticsearch.action.search.FetchSearchPhase.executeFetch(FetchSearchPhase.java:176) |  
  | at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:156) |  
  | at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:95) |  
  | at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) |  
  | at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) |  
  | at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:739) |  
  | at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) |  
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) |  
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) |  
  | at java.base/java.lang.Thread.run(Thread.java:834) |  
  | ]] |  
  | Expected: <0> |  
  | but: was <1>


```

**Comment by dakrone** [comment]
This failed for me also: https://gradle-enterprise.elastic.co/s/ljoy7iwprjooq

**Comment by mayya-sharipova** [comment]
This failed for me today on 7.x branch PR: https://gradle-enterprise.elastic.co/s/j2g4xmlnrmfwm

**Comment by dnhatn** [comment]
I've muted this test. Sorry for the noise.
