### ISSUE TITLE
SSLDriverTests failures on Java 16

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#67324]
**Build scan**:

https://gradle-enterprise.elastic.co/s/nfsh3tlezlwba

**Repro line**:

```
./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.transport.nio.SSLDriverTests.testHandshakeFailureBecauseProtocolMismatch" -Dtests.seed=E6AA04E3D814FEAE -Dtests.security.manager=true -Dtests.locale=ca -Dtests.timezone=America/St_Barthelemy -Druntime.java=16
```

**Reproduces locally?**:

yes

**Applicable branches**:

I expect all branches running on Java 16

**Failure history**:

https://build-stats.elastic.co/goto/30a7ec831d753f0b753e6c60af3fa5ff

Started failing on January 8th

**Failure excerpt**:

```
   2> java.lang.AssertionError: Unexpected exception message: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
        at __randomizedtesting.SeedInfo.seed([E6AA04E3D814FEAE:7A3F56720CE43F06]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.elasticsearch.xpack.security.transport.nio.SSLDriverTests.testHandshakeFailureBecauseProtocolMismatch(SSLDriverTests.java:175)

```

**Comment by iverase** [comment]
I am muting the test for that JDK

**Comment by albertzaharovits** [comment]
The fix should be simple, working on it.
