### ISSUE TITLE
[CI] SimpleSecurityNetty4ServerTransportTests.testThreadContext

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#67427]
**Build scan**: https://gradle-enterprise.elastic.co/s/xxazk5c2csshk 

**Repro line**:
```
./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests.testThreadContext" -Dtests.seed=3DD775158F20CC58 -Dtests.security.manager=true -Dtests.locale=tr -Dtests.timezone=Etc/GMT-0 -Druntime.java=11
```
**Reproduces locally?**: No

**Applicable branches**: master

**Failure history**:

**Failure excerpt**:
```
java.lang.AssertionError: this header is only visible in the handler context expected null, but was:<booooom> 
at __randomizedtesting.SeedInfo.seed([3DD775158F20CC58:ABD4401512CF7604]:0) 
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotNull(Assert.java:755)
at org.junit.Assert.assertNull(Assert.java:737)
at org.elasticsearch.transport.AbstractSimpleTransportTestCase.testThreadContext(AbstractSimpleTransportTestCase.java:383)
```

**Comment by davidkyle** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/f4uk7a3i6r63g

**Comment by davidkyle** [comment]
Muted on master in #68643

I muted the test in the base class `AbstractSimpleTransportTestCase` so the muting actually affects several classes
