### ISSUE TITLE
[CI] [7.x] SSLDriverTests.testHandshakeFailureBecauseProtocolMismatch failures

### ISSUE THREAD

**Issue by csoulios** [elastic/elasticsearch#67511]
**Build scan**:
https://gradle-enterprise.elastic.co/s/oagxtkhqkf3jy
https://gradle-enterprise.elastic.co/s/7akgi2ktv5ot4

**Repro line**:
```
./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.transport.nio.SSLDriverTests.testHandshakeFailureBecauseProtocolMismatch" -Dtests.seed=E397264D250D880B -Dtests.security.manager=true -Dtests.locale=sr-CS -Dtests.timezone=America/St_Kitts -Druntime.java=8
```
**Reproduces locally?**: Yes

**Applicable branches**: 7.x

**Failure history**:
https://build-stats.elastic.co/goto/30a7ec831d753f0b753e6c60af3fa5ff

**Failure excerpt**:

```
org.elasticsearch.xpack.security.transport.nio.SSLDriverTests > testHandshakeFailureBecauseProtocolMismatch FAILED
    java.lang.AssertionError:
    Expected: is "The client supported protocol versions [TLSv1.1] are not accepted by server preferences [TLS12]"
         but: was "Client requested protocol TLSv1.1 not enabled or not supported"
        at __randomizedtesting.SeedInfo.seed([E397264D250D880B:7F0274DCF1FD49A3]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.security.transport.nio.SSLDriverTests.testHandshakeFailureBecauseProtocolMismatch(SSLDriverTests.java:189)
```

Failure relates to #67324

**Comment by jkakavas** [comment]
@albertzaharovits do you mind taking a look since this looks similar to #67324 ?

**Comment by albertzaharovits** [comment]
@jkakavas This is my bad.
In #67337 I've dropped the assert for the older TLS mismatch error message, which is still emitted on JDKs 1.8 that are still packaged by some linux distros.

**Comment by albertzaharovits** [comment]
Closed by https://github.com/elastic/elasticsearch/commit/08aab8bee22c240e598b5d37e9d9fe18b8f6e6b3

**Comment by hendrikmuhs** [comment]
Another failure which contains the fix but still fails. Can you check @albertzaharovits ?

https://gradle-enterprise.elastic.co/s/wlg73jwpaspd6

**Comment by jkakavas** [comment]
The reason is that `org.bouncycastle.tls.TlsFatalAlert: protocol_version(70)` is thrown only by BCJSSE which is used with JDK >=11 or with Azul Zulu 8. So when the above runs with JDK 8 ( adoptopenjdk, corretto, oracle ), the CI is using SunJSSE which throws 
```
anyOf(is("The client supported protocol versions [TLSv1.1] are not accepted by server preferences " +
                    "[TLS12]"), is("Client requested protocol TLSv1.1 not enabled or not supported"));
```

**Comment by albertzaharovits** [comment]
@jkakavas Thanks for the pointer. Is there a configuration for that? Can you help me figure out how did you figure it out?

**Comment by jkakavas** [comment]
> Is there a configuration for that?

Yes, see : 
https://github.com/elastic/elasticsearch/blob/7.x/gradle/fips.gradle#L17 and https://github.com/elastic/elasticsearch/pull/61857

We don't expose that back somehow, so there's no property like `BuildParams.runtimeJavaDetails` that can be used in the test. One could iterate the list of providers and their names to determine if SunJSSE or BCJSSE is used but I don't think it's worth it. I'd suggest we add the matcher for the BCJSEE error in the `anyOf`

> Can you help me figure out how did you figure it out?

Well, the " org.bouncycastle.tls.TlsFatalAlert: protocol_version(70) is thrown only by BCJSSE" comes from painful memories :) and that was actually the hint. `org.bouncycastle.tls.*` sounds like it comes from the JSSE (BCJSSE vs SunJSSE ) provider and not the crypto (BCFIPS) provider if you think about it. ( the `tls` part ) .

**Comment by albertzaharovits** [comment]
Aaarg, only in the 7.x branch, I could've peered into the master branch all day. Makes sense to sit in 7.x only, but I was fixated on master.
Thank you!

I'll use the anyOf trick.

**Comment by jkakavas** [comment]
> Aaarg, only in the 7.x branch

Yeap, its a Java 8 only thing. After Java 9, SunJSSE dropped support for FIPS 140-2 mode so we only use BCJSSE ;)

**Comment by albertzaharovits** [comment]
Closed by d74c2d7
