### ISSUE TITLE
[CI] TransportPutAutoscalingPolicyActionIT testUpdatePolicy failing reproducibly

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#67620]
This just started failing today.

**Build scan**:
https://gradle-enterprise.elastic.co/s/qbyrgkn5refj4/tests/:x-pack:plugin:autoscaling:internalClusterTest/org.elasticsearch.xpack.autoscaling.action.TransportPutAutoscalingPolicyActionIT/testUpdatePolicy#1

**Repro line**:
`REPRODUCE WITH: ./gradlew ':x-pack:plugin:autoscaling:internalClusterTest' --tests "org.elasticsearch.xpack.autoscaling.action.TransportPutAutoscalingPolicyActionIT.testUpdatePolicy" -Dtests.seed=5E99B04B51505E3B -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=America/Indiana/Tell_City -Druntime.java=11`

**Reproduces locally?**:
Yes.

**Applicable branches**:
`7.x` and `master`

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.xpack.autoscaling.action.TransportPutAutoscalingPolicyActionIT&tests.sortField=FAILED&tests.test=testUpdatePolicy&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.xpack.autoscaling.action.TransportPutAutoscalingPolicyActionIT > testUpdatePolicy FAILED
    java.lang.IllegalArgumentException: no default nor user configured deciders for policy [dBokRDFQ] with roles [[]]
        at __randomizedtesting.SeedInfo.seed([5E99B04B51505E3B:49A8F6ED79B12432]:0)
        at org.elasticsearch.xpack.autoscaling.capacity.AutoscalingCalculateCapacityService.validate(AutoscalingCalculateCapacityService.java:56)
        at org.elasticsearch.xpack.autoscaling.action.TransportPutAutoscalingPolicyAction.putAutoscalingPolicy(TransportPutAutoscalingPolicyAction.java:154)
        at org.elasticsearch.xpack.autoscaling.action.TransportPutAutoscalingPolicyAction$1.execute(TransportPutAutoscalingPolicyAction.java:106)
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:48)
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:686)
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:308)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:203)
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:140)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:139)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:177)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:669)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:241)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:204)
```

**Comment by mark-vieira** [comment]
Since this reproduces I've muted it on `master` and `7.x`.

**Comment by hendrikmuhs** [comment]
still fails for 7.11: https://gradle-enterprise.elastic.co/s/tecuxtmngfixw

will mute it, too

**Comment by henningandersen** [comment]
Muted this on 7.11 too.
