### ISSUE TITLE
[CI] SearchGroupsResolverInMemoryTests.testResolveWithDefaultUserAttribute fails

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#67638]
**Build scan**:
https://gradle-enterprise.elastic.co/s/ej2mf566bjwak
**Repro line**:
```
./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.authc.ldap.SearchGroupsResolverInMemoryTests.testResolveWithDefaultUserAttribute" -Dtests.seed=CF0DE4EC556A2B26 -Dtests.security.manager=true -Dtests.locale=mt -Dtests.timezone=Pacific/Bougainville -Druntime.java=8
```
**Reproduces locally?**:
no
**Applicable branches**:
7.10
**Failure history**:

**Failure excerpt**:
```
10:12:05   2> UncategorizedExecutionException[Failed execution]; nested: ExecutionException[LDAPException(resultCode=81 (server down), errorMessage='The connection to the directory server was closed while waiting for a response to an asynchronous request.', ldapSDKVersion=4.0.8, revision=28812)]; nested: LDAPException[The connection to the directory server was closed while waiting for a response to an asynchronous request.];
10:12:05         at __randomizedtesting.SeedInfo.seed([CF0DE4EC556A2B26:9786988522002C7B]:0)
10:12:05         at org.elasticsearch.common.util.concurrent.FutureUtils.rethrowExecutionException(FutureUtils.java:91)
10:12:05         at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:61)
10:12:05         at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:37)
10:12:05         at org.elasticsearch.xpack.security.authc.ldap.SearchGroupsResolverInMemoryTests.resolveGroups(SearchGroupsResolverInMemoryTests.java:163)
10:12:05         at org.elasticsearch.xpack.security.authc.ldap.SearchGroupsResolverInMemoryTests.testResolveWithDefaultUserAttribute(SearchGroupsResolverInMemoryTests.java:88)
10:12:05 
10:12:05         Caused by:
10:12:05         java.util.concurrent.ExecutionException: LDAPException(resultCode=81 (server down), errorMessage='The connection to the directory server was closed while waiting for a response to an asynchronous request.', ldapSDKVersion=4.0.8, revision=28812)
10:12:05             at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:273)
10:12:05             at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:260)
10:12:05             at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:87)
10:12:05             at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:56)
10:12:05             ... 3 more
10:12:05 
10:12:05             Caused by:
10:12:05             LDAPException(resultCode=81 (server down), errorMessage='The connection to the directory server was closed while waiting for a response to an asynchronous request.', ldapSDKVersion=4.0.8, revision=28812)
10:12:05                 at org.elasticsearch.xpack.security.authc.ldap.support.LdapUtils.toException(LdapUtils.java:407)
10:12:05                 at org.elasticsearch.xpack.security.authc.ldap.support.LdapUtils.access$200(LdapUtils.java:53)
10:12:05                 at org.elasticsearch.xpack.security.authc.ldap.support.LdapUtils$LdapSearchResultListener.searchResultReceived(LdapUtils.java:514)
10:12:05                 at com.unboundid.ldap.sdk.AsyncSearchHelper.responseReceived(AsyncSearchHelper.java:220)
10:12:05                 at com.unboundid.ldap.sdk.LDAPConnectionReader.closeInternal(LDAPConnectionReader.java:1023)
10:12:05                 at com.unboundid.ldap.sdk.LDAPConnectionReader.close(LDAPConnectionReader.java:969)
10:12:05                 at com.unboundid.ldap.sdk.LDAPConnectionInternals.close(LDAPConnectionInternals.java:655)
10:12:05                 at com.unboundid.ldap.sdk.LDAPConnection.setClosed(LDAPConnection.java:4635)
10:12:05                 at com.unboundid.ldap.sdk.LDAPConnectionReader.closeInternal(LDAPConnectionReader.java:1002)
10:12:05                 at com.unboundid.ldap.sdk.LDAPConnectionReader.run(LDAPConnectionReader.java:404)
```

might be relevant (root cause?):
```
10:12:03 Unable to receive command from client socket connection from /127.0.0.1:59240 to /127.0.0.1:59242. Discarding connection.
10:12:03 org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:59242'.
10:12:03 	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:94)
10:12:03 	at org.gradle.launcher.daemon.server.SynchronizedDispatchConnection.receive(SynchronizedDispatchConnection.java:70)
10:12:03 	at org.gradle.launcher.daemon.server.DefaultDaemonConnection$1.run(DefaultDaemonConnection.java:65)
10:12:03 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
10:12:03 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
10:12:03 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
10:12:03 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
10:12:03 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
10:12:03 	at java.base/java.lang.Thread.run(Thread.java:832)
10:12:03 Caused by: java.lang.IllegalArgumentException: Unexpected type tag 48 found.
10:12:03 	at org.gradle.internal.serialize.DefaultSerializerRegistry$TaggedTypeSerializer.read(DefaultSerializerRegistry.java:145)
10:12:03 	at org.gradle.internal.serialize.Serializers$StatefulSerializerAdapter$1.read(Serializers.java:36)
10:12:03 	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
10:12:03 	... 8 more
10:12:03 
```

**Comment by martijnvg** [comment]
Another instance of this failure: https://gradle-enterprise.elastic.co/s/yivm4jzsk6jym
This test failed 5 times in the last 90 days.

**Comment by slobodanadamovic** [comment]
This is the last failure I could find: https://gradle-enterprise.elastic.co/s/2au5advjmvfi4/tests/:x-pack:plugin:security:test/org.elasticsearch.xpack.security.authc.ldap.SearchGroupsResolverInMemoryTests/testResolveWithDefaultUserAttribute?top-execution=1

Looking at the history, this test only failed on **darwin** CI builds which [have been removed](https://github.com/elastic/elasticsearch/issues/58286#issuecomment-1115546995). Hence, I will close this issue.
