### ISSUE TITLE
Nested query returning 500 Internal Server Error due to IndexOutOfBoundsException

### ISSUE THREAD

**Issue by raoulvdberge** [elastic/elasticsearch#67692]
**Elasticsearch version**: 7.10.1

**Plugins installed**: None

**JVM version** (`java -version`):
``` 
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)
``` 

**OS version** (`uname -a` if on a Unix-like system):
```
Linux 048236da6b57 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
``` 
Using the `elasticsearch:7.10.1` docker image on WSL.

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

 1.
Create the `healthoffer_providers` index:

PUT /healthoffer_providers
```json
{
  "mappings": {
    "properties": {
      "healthoffers": {
        "type": "nested",
        "properties": {
          "addresses": {
            "type": "nested",
            "properties": {
              "municipality_description": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              }
            }
          },
          "name": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          }
        }
      },
      "provider_name": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      }
    }
  }
}
``` 

 2.
Insert a single entry:

PUT /healthoffer_providers/_doc/1
```json
{
    "provider_name": "MyFirstProvider",
    "healthoffers": [
        {
            "name": "Offer1",
            "addresses": [
                {
                    "municipality_description": "Hasselt"
                },
                {
                    "municipality_description": "Heusden-Zolder"
                }
            ]
        },
        {
            "name": "Offer2",
            "addresses": [
                {
                    "municipality_description": "Beveren"
                },
                {
                    "municipality_description": "Antwerpen"
                }
            ]
        },
        {
            "name": "Offer3",
            "addresses": [
                {
                    "municipality_description": "Puurs"
                },
                {
                    "municipality_description": "Brussel"
                }
            ]
        }
    ]
}
``` 

 3.
Look up the first healthoffer in the entry, and notice that it doesn't fail (works as expected).

GET /healthoffer_providers/_search
```json
{
    "query": {
        "nested": {
            "path": "healthoffers",
            "inner_hits": {},
            "query": {
                "bool": {
                    "must": [
                        {
                            "match": {
                                "healthoffers.name": "Offer1"
                            }
                        },
                        {
                            "nested": {
                                "path": "healthoffers.addresses",
                                "inner_hits": {},
                                "query": {
                                    "bool": {
                                        "must": [
                                            {
                                                "match": {
                                                    "healthoffers.addresses.municipality_description": "Hasselt"
                                                }
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    ]
                }
            }
        }
    }
}
``` 
Result (working):
```json
{
    "took": 6,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 1,
            "relation": "eq"
        },
        "max_score": 2.616888,
        "hits": [
            {
                "_index": "healthoffer_providers",
                "_type": "_doc",
                "_id": "1",
                "_score": 2.616888,
                "_source": {
                    "provider_name": "MyFirstProvider",
                    "healthoffers": [
                        {
                            "name": "Offer1",
                            "addresses": [
                                {
                                    "municipality_description": "Hasselt"
                                },
                                {
                                    "municipality_description": "Heusden-Zolder"
                                }
                            ]
                        },
                        {
                            "name": "Offer2",
                            "addresses": [
                                {
                                    "municipality_description": "Beveren"
                                },
                                {
                                    "municipality_description": "Antwerpen"
                                }
                            ]
                        },
                        {
                            "name": "Offer3",
                            "addresses": [
                                {
                                    "municipality_description": "Puurs"
                                },
                                {
                                    "municipality_description": "Brussel"
                                }
                            ]
                        }
                    ]
                },
                "inner_hits": {
                    "healthoffers": {
                        "hits": {
                            "total": {
                                "value": 1,
                                "relation": "eq"
                            },
                            "max_score": 2.616888,
                            "hits": [
                                {
                                    "_index": "healthoffer_providers",
                                    "_type": "_doc",
                                    "_id": "1",
                                    "_nested": {
                                        "field": "healthoffers",
                                        "offset": 0
                                    },
                                    "_score": 2.616888,
                                    "_source": {
                                        "addresses": [
                                            {
                                                "municipality_description": "Hasselt"
                                            },
                                            {
                                                "municipality_description": "Heusden-Zolder"
                                            }
                                        ],
                                        "name": "Offer1"
                                    },
                                    "inner_hits": {
                                        "healthoffers.addresses": {
                                            "hits": {
                                                "total": {
                                                    "value": 1,
                                                    "relation": "eq"
                                                },
                                                "max_score": 1.6360589,
                                                "hits": [
                                                    {
                                                        "_index": "healthoffer_providers",
                                                        "_type": "_doc",
                                                        "_id": "1",
                                                        "_nested": {
                                                            "field": "healthoffers",
                                                            "offset": 0,
                                                            "_nested": {
                                                                "field": "addresses",
                                                                "offset": 0
                                                            }
                                                        },
                                                        "_score": 1.6360589,
                                                        "_source": {
                                                            "municipality_description": "Hasselt"
                                                        }
                                                    }
                                                ]
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        ]
    }
}
```

4.
Look up the second or third healthoffer in the entry, and notice an exception.

GET /healthoffer_providers/_search
```json
{
    "query": {
        "nested": {
            "path": "healthoffers",
            "inner_hits": {},
            "query": {
                "bool": {
                    "must": [
                        {
                            "match": {
                                "healthoffers.name": "Offer2"
                            }
                        },
                        {
                            "nested": {
                                "path": "healthoffers.addresses",
                                "inner_hits": {},
                                "query": {
                                    "bool": {
                                        "must": [
                                            {
                                                "match": {
                                                    "healthoffers.addresses.municipality_description": "Beveren"
                                                }
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    ]
                }
            }
        }
    }
}
``` 
The error returned by Elasticsearch is the following:
```json
{
    "error": {
        "root_cause": [
            {
                "type": "index_out_of_bounds_exception",
                "reason": "Index: 1, Size: 1"
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "healthoffer_providers",
                "node": "UoUXiXZNT9Og9ZbTpPyRhA",
                "reason": {
                    "type": "index_out_of_bounds_exception",
                    "reason": "Index: 1, Size: 1"
                }
            }
        ],
        "caused_by": {
            "type": "index_out_of_bounds_exception",
            "reason": "Index: 1, Size: 1",
            "caused_by": {
                "type": "index_out_of_bounds_exception",
                "reason": "Index: 1, Size: 1"
            }
        }
    },
    "status": 500
}
```
I expected a result similar to step 3.

**Provide logs (if relevant)**:
After the failing result, this is logged to the console:
```
"Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 1",
"at java.util.Collections$SingletonList.get(Collections.java:4926) ~[?:?]",
"at org.elasticsearch.search.fetch.FetchPhase.prepareNestedHitContext(FetchPhase.java:448) ~[elasticsearch-7.10.1.jar:7.10.1]",
"at org.elasticsearch.search.fetch.FetchPhase.prepareHitContext(FetchPhase.java:292) ~[elasticsearch-7.10.1.jar:7.10.1]",
"at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:155) ~[elasticsearch-7.10.1.jar:7.10.1]",
"at org.elasticsearch.search.fetch.subphase.InnerHitsPhase.hitExecute(InnerHitsPhase.java:89) ~[elasticsearch-7.10.1.jar:7.10.1]",
"at org.elasticsearch.search.fetch.subphase.InnerHitsPhase.access$000(InnerHitsPhase.java:40) ~[elasticsearch-7.10.1.jar:7.10.1]",
"at org.elasticsearch.search.fetch.subphase.InnerHitsPhase$1.process(InnerHitsPhase.java:62) ~[elasticsearch-7.10.1.jar:7.10.1]",
"at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:164) ~[elasticsearch-7.10.1.jar:7.10.1]",
"at org.elasticsearch.search.fetch.subphase.InnerHitsPhase.hitExecute(InnerHitsPhase.java:89) ~[elasticsearch-7.10.1.jar:7.10.1]",
"at org.elasticsearch.search.fetch.subphase.InnerHitsPhase.access$000(InnerHitsPhase.java:40) ~[elasticsearch-7.10.1.jar:7.10.1]",
"at org.elasticsearch.search.fetch.subphase.InnerHitsPhase$1.process(InnerHitsPhase.java:62) ~[elasticsearch-7.10.1.jar:7.10.1]",
"at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:164) ~[elasticsearch-7.10.1.jar:7.10.1]",
"at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:462) ~[elasticsearch-7.10.1.jar:7.10.1]",
"at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:438) ~[elasticsearch-7.10.1.jar:7.10.1]",
"at org.elasticsearch.search.SearchService.access$500(SearchService.java:141) ~[elasticsearch-7.10.1.jar:7.10.1]",
"at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:401) ~[elasticsearch-7.10.1.jar:7.10.1]",
"at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:58) ~[elasticsearch-7.10.1.jar:7.10.1]",
"at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73) ~[elasticsearch-7.10.1.jar:7.10.1]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.10.1.jar:7.10.1]",
"... 6 more"] }
```

**Comment by raoulvdberge** [comment]
Thank you @jimczi, I can confirm `7.10.2` fixes the issue.
