### ISSUE TITLE
Possible Race Condition BlobStoreRepository (read, write delete) test

### ISSUE THREAD

**Issue by sachin-frayne** [elastic/elasticsearch#67704]
When using SMB as our backend snapshot storage and everything running on Windows we face the following error.

```
[2021-01-19T11:44:33,662][WARN ][o.e.r.RepositoriesService] [ELASTIC-03] [live_elastic_backup] failed to finish repository verification
org.elasticsearch.repositories.RepositoryVerificationException: [live_elastic_backup] cannot delete test data at
at org.elasticsearch.repositories.blobstore.BlobStoreRepository.endVerification(BlobStoreRepository.java:1287) ~[elasticsearch-7.10.1.jar:7.10.1]
at org.elasticsearch.repositories.RepositoriesService$3.lambda$doRun$1(RepositoriesService.java:274) [elasticsearch-7.10.1.jar:7.10.1]
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) [elasticsearch-7.10.1.jar:7.10.1]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.nio.file.DirectoryNotEmptyException: \\<SMB_SERVER>\Elastic_Backup\Live\tests-C9R0JHqiSKWI9Y9d-cWmKA
at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:271) ~[?:?]
at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105) ~[?:?]
at java.nio.file.Files.delete(Files.java:1146) ~[?:?]
at org.elasticsearch.common.blobstore.fs.FsBlobContainer$1.postVisitDirectory(FsBlobContainer.java:126) ~[elasticsearch-7.10.1.jar:7.10.1]
at org.elasticsearch.common.blobstore.fs.FsBlobContainer$1.postVisitDirectory(FsBlobContainer.java:122) ~[elasticsearch-7.10.1.jar:7.10.1]
at java.nio.file.Files.walkFileTree(Files.java:2822) ~[?:?]
at java.nio.file.Files.walkFileTree(Files.java:2876) ~[?:?]
at org.elasticsearch.common.blobstore.fs.FsBlobContainer.delete(FsBlobContainer.java:122) ~[elasticsearch-7.10.1.jar:7.10.1]
at org.elasticsearch.repositories.blobstore.BlobStoreRepository.endVerification(BlobStoreRepository.java:1285) ~[elasticsearch-7.10.1.jar:7.10.1]
... 5 more
```

We have looked at the permissions and cannot find anything significant, the user running Elasticsearch can create, read and delete folders as that user without a problem.

I have found the code that runs the delete and I am wondering if there is a possible race condition, if say for example I have a virus program running that reads all my created files or a scanning program that holds the file temporarily and stop the master node from being able to delete it instantly?

https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java#L1284-L1294

```
@Override
public void endVerification(String seed) {
    if (isReadOnly() == false) {
        try {
            final String testPrefix = testBlobPrefix(seed);
            blobStore().blobContainer(basePath().add(testPrefix)).delete();
        } catch (Exception exp) {
            throw new RepositoryVerificationException(metadata.name(), "cannot delete test data at " + basePath(), exp);
        }
    }
}
```

**Comment by DaveCTurner** [comment]
> I have found the code that runs the delete and I am wondering if there is a possible race condition, if say for example I have a virus program running that reads all my created files or a scanning program that holds the file temporarily and stop the master node from being able to delete it instantly?

It's not really a race condition, but yes you are expected to ensure that the repository is free from interference by things other than Elasticsearch. The data in the repository is (a) not executable and (b) mangled in a way that renders it opaque to this kind of scanning program. If a scan did manage to find a virus in a snapshot repository it would be a false positive; if it deleted or moved a file then that could easily destroy the whole repository. So don't do that.

That said we do permit multiple Elasticsearch clusters to point at the same repository at the same time, as long as all but one is in read-only mode, and in that case I think we do risk hitting this on a SMB mount.

**Comment by DaveCTurner** [comment]
> That said we do permit multiple Elasticsearch clusters to point at the same repository at the same time, as long as all but one is in read-only mode, and in that case I think we do risk hitting this on a SMB mount.

I stand corrected, we account for interference between Elasticsearch clusters, this problem only arises if you let other things fiddle with the repository contents too.

**Comment by sachin-frayne** [comment]
Thank you
