### ISSUE TITLE
[CI] FieldSortIT.testIssue8226

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#67714]
**Build scan**: https://gradle-enterprise.elastic.co/s/apmvcoxf6uh6o

**Repro line**: `./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.search.sort.FieldSortIT.testIssue8226" -Dtests.seed=59F785F1790E2D2 -Dtests.security.manager=true -Dtests.locale=sr-Latn-ME -Dtests.timezone=Europe/Sofia -Druntime.java=8`

**Reproduces locally?**: No 

**Applicable branches**: 7.11

**Failure history**: Only once: https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.sort.FieldSortIT&tests.test=testIssue8226

**Failure excerpt**:

```

java.lang.AssertionError: Unexpected ShardFailures: [shard [[GNMPQoGURUaVbWglns4Wqg][test_2][9]], reason [NoShardAvailableActionException[[node_s0][127.0.0.1:39635][indices:data/read/search[phase/query]]]], cause [[test_2/EIeaG8dNQHq493xOTWgW9Q][[test_2][9]] NoShardAvailableActionException[[node_s0][127.0.0.1:39635][indices:data/read/search[phase/query]]] |  
-- | --
  | at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:459) |  
  | at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:408) |  
  | at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$000(AbstractSearchAsyncAction.java:70) |  
  | at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:275) |  
  | at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73) |  
  | at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:59) |  
  | at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:415) |  
  | at org.elasticsearch.transport.TransportService$6.handleException(TransportService.java:754) |  
  | at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1299) |  
  | at org.elasticsearch.transport.InboundHandler.lambda$handleException$3(InboundHandler.java:277) |  
  | at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:224) |  
  | at org.elasticsearch.transport.InboundHandler.handleException(InboundHandler.java:275) |  
  | at org.elasticsearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:267) |  
  | at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:131) |  
  | at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:89) |  
  | at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:700) |  
  | at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142) |  
  | at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117) |  
  | at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82) |  
  | at org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:296) |  
  | at org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:228) |  
  | at org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:40) |  
  | at org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:139) |  
  | at org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:151) |  
  | at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:420) |  
  | at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:246) |  
  | at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:174) |  
  | at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:131) |  
  | at java.lang.Thread.run(Thread.java:748) |  
  | ]] |  
  | Expected: <0> |  
  | but: was <1>


at __randomizedtesting.SeedInfo.seed([59F785F1790E2D2:DE61AFA66AAA45BE]:0) |  
-- | --
  |   | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  |   | at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertNoFailures(ElasticsearchAssertions.java:307) |  
  |   | at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertSearchResponse(ElasticsearchAssertions.java:637) |  
  |   | at org.elasticsearch.search.sort.FieldSortIT.testIssue8226(FieldSortIT.java:139)
```

**Comment by mayya-sharipova** [comment]
We've decided that since this is just one failure and it looks to be a shard failure (NoShardAvailableActionException), we will monitor this issue, and if no more failures occur within the several weeks, we will close the issue

**Comment by mayya-sharipova** [comment]
I've checked failure history for the last 28 days, and we still have only this single failure.
So, we will consider this failure just one-off related to a shard failure, that's why I am closing this issue.
