### ISSUE TITLE
RollupIT#testPutStartAndGetRollupJob failure

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#67749]
**Build scan**:
https://gradle-enterprise.elastic.co/s/cbezj6gdp73wm
**Repro line**:
./gradlew ':client:rest-high-level:integTest' --tests "org.elasticsearch.client.RollupIT.testPutStartAndGetRollupJob" -Dtests.seed=1434E8CA3743FCB2 -Dtests.security.manager=true -Dtests.locale=hr-HR -Dtests.timezone=Europe/Vaduz -Druntime.java=8
**Reproduces locally?**:
No
**Applicable branches**:
7.11
**Failure history**:
No previous failure. 
**Failure excerpt**:
```
Suite: Test class org.elasticsearch.client.RollupIT
  1> [2021-01-20T05:21:58,112][INFO ][o.e.c.RollupIT           ] [testSearchWithType] before test
  1> [2021-01-20T05:21:58,112][INFO ][o.e.c.RollupIT           ] [testSearchWithType] initializing REST clients against [http://[::1]:33121, http://127.0.0.1:35097]
  1> [2021-01-20T05:21:58,459][INFO ][o.e.c.RollupIT           ] [testSearchWithType] after test
  1> [2021-01-20T05:21:58,478][INFO ][o.e.c.RollupIT           ] [testDeleteMissingRollupJob] before test
  1> [2021-01-20T05:21:58,809][INFO ][o.e.c.RollupIT           ] [testDeleteMissingRollupJob] after test
  1> [2021-01-20T05:21:58,838][INFO ][o.e.c.RollupIT           ] [testGetRollupCaps] before test
  1> [2021-01-20T05:21:59,459][INFO ][o.e.c.RollupIT           ] [testGetRollupCaps] after test
  1> [2021-01-20T05:21:59,479][INFO ][o.e.c.RollupIT           ] [testDeleteRollupJob] before test
  1> [2021-01-20T05:22:00,066][INFO ][o.e.c.RollupIT           ] [testDeleteRollupJob] after test
  1> [2021-01-20T05:22:00,096][INFO ][o.e.c.RollupIT           ] [testGetRollupIndexCaps] before test
  1> [2021-01-20T05:22:00,942][INFO ][o.e.c.RollupIT           ] [testGetRollupIndexCaps] after test
  1> [2021-01-20T05:22:00,973][INFO ][o.e.c.RollupIT           ] [testGetMissingRollupJob] before test
  1> [2021-01-20T05:22:01,388][INFO ][o.e.c.RollupIT           ] [testGetMissingRollupJob] after test
  1> [2021-01-20T05:22:01,438][INFO ][o.e.c.RollupIT           ] [testSearch] before test
  1> [2021-01-20T05:22:03,138][INFO ][o.e.c.RollupIT           ] [testSearch] after test
  1> [2021-01-20T05:22:03,161][INFO ][o.e.c.RollupIT           ] [testPutStartAndGetRollupJob] before test
  1> [2021-01-20T05:22:08,097][INFO ][o.e.c.RollupIT           ] [testPutStartAndGetRollupJob] after test
  2> REPRODUCE WITH: ./gradlew ':client:rest-high-level:integTest' --tests "org.elasticsearch.client.RollupIT.testPutStartAndGetRollupJob" -Dtests.seed=1434E8CA3743FCB2 -Dtests.security.manager=true -Dtests.locale=hr-HR -Dtests.timezone=Europe/Vaduz -Druntime.java=8
  2> java.lang.AssertionError: expected:<1> but was:<0>
        at __randomizedtesting.SeedInfo.seed([1434E8CA3743FCB2:DCCA39A73E9515CE]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.elasticsearch.client.RollupIT.testPutStartAndGetRollupJob(RollupIT.java:233)
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+7.11+multijob-unix-compatibility/os/centos-7&&immutable/client/rest-high-level/build/testrun/integTest/temp/org.elasticsearch.client.RollupIT_1434E8CA3743FCB2-001
  2> NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=1268, maxMBSortInHeap=6.142392772837063, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=hr-HR, timezone=Europe/Vaduz
  2> NOTE: Linux 3.10.0-1160.11.1.el7.x86_64 amd64/Oracle Corporation 1.8.0_271 (64-bit)/cpus=32,threads=1,free=453614776,total=512229376
  2> NOTE: All tests run in this JVM: [AnalyticsAggsIT, InferenceAggIT, AsyncSearchIT, BulkProcessorIT, BulkProcessorRetryIT, BulkRequestWithGlobalParametersIT, CCRIT, ClusterClientIT, CrudIT, AsyncSearchDocumentationIT, CCRDocumentationIT, ClusterClientDocumentationIT, CRUDDocumentationIT, EnrichDocumentationIT, GraphDocumentationIT, ILMDocumentationIT, IndicesClientDocumentationIT, IngestClientDocumentationIT, LicensingDocumentationIT, MigrationClientDocumentationIT, MigrationDocumentationIT, MiscellaneousDocumentationIT, RollupDocumentationIT, MlClientDocumentationIT, SearchDocumentationIT, SecurityDocumentationIT, SnapshotClientDocumentationIT, StoredScriptsDocumentationIT, TasksClientDocumentationIT, TransformDocumentationIT, WatcherDocumentationIT, EnrichIT, EqlIT, GraphIT, HighLevelRestClientCompressionIT, IndexLifecycleIT, IndicesClientIT, IngestClientIT, LicenseIT, MachineLearningGetResultsIT, MachineLearningIT, MigrationIT, PingAndInfoIT, RankEvalIT, ReindexIT, RollupIT]
```

I'm not muting this as it has only failed once. I think it will be more helpful to get some additional data if this is flaky. If I come across another failure today, I'm going to mute it

**Comment by tlrx** [comment]
This failed again in November (see #80496) and also in:
https://gradle-enterprise.elastic.co/s/6kmave7jxtdie
https://gradle-enterprise.elastic.co/s/q7odku5tfezuu

I'm going to mute.

**Comment by csoulios** [comment]
This test has been fixed by https://github.com/elastic/elasticsearch/pull/86992

Test was unumuted by PR https://github.com/elastic/elasticsearch/pull/89979
