### ISSUE TITLE
vagrant fedora 28 packaging tests fail 

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#67745]
Not entirely sure why these fail

**Build scan**:

https://gradle-enterprise.elastic.co/s/wreea6ek76une

**Repro line**:

**Reproduces locally?**:

**Applicable branches**:

**Failure history**:

**Failure excerpt**:

```
| Failed to execute org.gradle.cache.internal.AsyncCacheAccessDecoratedCache$2@36ea661f.
| org.gradle.api.UncheckedIOException: Could not add entry '/elasticsearch/buildSrc/build-bootstrap/classes/java' to cache outputFiles.bin (/elasticsearch/qa/os/fedora-28/build/gradle-cache/buildOutputCleanup/outputFiles.bin).
| 	at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.put(BTreePersistentIndexedCache.java:162)
| 	at org.gradle.cache.internal.DefaultMultiProcessSafePersistentIndexedCache$2.run(DefaultMultiProcessSafePersistentIndexedCache.java:74)
| 	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.doWriteAction(DefaultFileLockManager.java:215)
| 	at org.gradle.cache.internal.DefaultFileLockManager$DefaultFileLock.writeFile(DefaultFileLockManager.java:205)
| 	at org.gradle.cache.internal.DefaultCacheAccess$UnitOfWorkFileAccess.writeFile(DefaultCacheAccess.java:449)
| 	at org.gradle.cache.internal.DefaultMultiProcessSafePersistentIndexedCache.put(DefaultMultiProcessSafePersistentIndexedCache.java:71)
| 	at org.gradle.cache.internal.AsyncCacheAccessDecoratedCache$2.run(AsyncCacheAccessDecoratedCache.java:64)
| 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
| 	at org.gradle.cache.internal.CacheAccessWorker$2.run(CacheAccessWorker.java:185)
| 	at org.gradle.internal.Factories$1.create(Factories.java:26)
| 	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:220)
| 	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:201)
| 	at org.gradle.cache.internal.CacheAccessWorker.flushOperations(CacheAccessWorker.java:175)
| 	at org.gradle.cache.internal.CacheAccessWorker.run(CacheAccessWorker.java:145)
| 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
| 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
| 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
| 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
| 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
| 	at java.base/java.lang.Thread.run(Thread.java:832)
| Caused by: org.gradle.api.UncheckedIOException: java.io.IOException: No such file or directory
| 	at org.gradle.cache.internal.btree.FileBackedBlockStore.write(FileBackedBlockStore.java:140)
| 	at org.gradle.cache.internal.btree.CachingBlockStore.flush(CachingBlockStore.java:64)
| 	at org.gradle.cache.internal.btree.FreeListBlockStore.flush(FreeListBlockStore.java:103)
| 	at org.gradle.cache.internal.btree.StateCheckBlockStore.flush(StateCheckBlockStore.java:85)
| 	at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.put(BTreePersistentIndexedCache.java:160)
| 	... 19 more
| Caused by: java.io.IOException: No such file or directory
| 	at java.base/java.io.RandomAccessFile.setLength(Native Method)
| 	at org.gradle.cache.internal.btree.FileBackedBlockStore$BlockImpl.write(FileBackedBlockStore.java:227)
| 	at org.gradle.cache.internal.btree.FileBackedBlockStore.write(FileBackedBlockStore.java:136)
| 	... 23 more
```

**Comment by mark-vieira** [comment]
We don't test on this OS anymore.
