### ISSUE TITLE
CCSDuelIT#testScriptFields failure

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#67754]
**Build scan**:
https://gradle-enterprise.elastic.co/s/xeydly7v3laoc

**Repro line**:
```
./gradlew ':qa:multi-cluster-search:remote-cluster' --tests "org.elasticsearch.search.CCSDuelIT.testScriptFields" -Dtests.seed=7E283987EDC79033 -Dtests.security.manager=true -Dtests.locale=es-PE -Dtests.timezone=America/Edmonton -Druntime.java=11
```
**Reproduces locally?**:
No
**Applicable branches**:
7.x
**Failure history**:
No previous failures 

**Failure excerpt**:
```
rg.elasticsearch.search.CCSDuelIT > testScriptFields FAILED
    java.lang.AssertionError: expected:<5> but was:<6>
        at __randomizedtesting.SeedInfo.seed([7E283987EDC79033:BCF1FA44F2821168]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.elasticsearch.search.CCSDuelIT.indexDocuments(CCSDuelIT.java:221)
        at org.elasticsearch.search.CCSDuelIT.lambda$init$0(CCSDuelIT.java:141)
        at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:187)
        at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:211)
        at org.elasticsearch.search.CCSDuelIT.init(CCSDuelIT.java:139)
REPRODUCE WITH: ./gradlew ':qa:multi-cluster-search:remote-cluster' --tests "org.elasticsearch.search.CCSDuelIT.testScriptFields" -Dtests.seed=7E283987EDC79033 -Dtests.security.manager=true -Dtests.locale=es-PE -Dtests.timezone=America/Edmonton -Druntime.java=11
```

Not muting this since this is the first time it fails and it doesn't reproduce locally

**Comment by valeriy42** [comment]
This failure may be related https://gradle-enterprise.elastic.co/s/amcry4xsjn36m

**Comment by martijnvg** [comment]
A different `CSSDuelIT` test failure with the same failure: https://gradle-enterprise.elastic.co/s/2dw4sptlzdfoy/tests/:qa:multi-cluster-search:remote-cluster/org.elasticsearch.search.CCSDuelIT/testDocValueFields?expanded-stacktrace=WyIwIl0&top-execution=1

**Comment by benwtrent** [comment]
Another failure, same test: https://gradle-enterprise.elastic.co/s/xmnyusk6tfyk4

```
org.elasticsearch.search.CCSDuelIT > testScriptFields FAILED
    java.lang.AssertionError: expected:<1> but was:<2>
        at __randomizedtesting.SeedInfo.seed([2C01ECA7090CA835:EED82F641649296E]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.elasticsearch.search.CCSDuelIT.indexDocuments(CCSDuelIT.java:210)
        at org.elasticsearch.search.CCSDuelIT.lambda$init$0(CCSDuelIT.java:130)
        at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:187)
        at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:211)
        at org.elasticsearch.search.CCSDuelIT.init(CCSDuelIT.java:128)
```

```
./gradlew ':qa:multi-cluster-search:remote-cluster' --tests "org.elasticsearch.search.CCSDuelIT.testScriptFields" -Dtests.seed=2C01ECA7090CA835 -Dtests.locale=he -Dtests.timezone=Europe/Tallinn -Druntime.java=11 -Dtests.fips.enabled=true
```
