### ISSUE TITLE
SearchableSnapshotRecoveryStateIntegrationTests failure 

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#67795]
**Build scan**:
https://gradle-enterprise.elastic.co/s/s6dp3r56sx4we
**Repro line**:
```
./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotRecoveryStateIntegrationTests.testFilesStoredInThePersistentCacheAreMarkedAsReusedInRecoveryState" -Dtests.seed=1D3F11D71479ACFC -Dtests.security.manager=true -Dtests.locale=is -Dtests.timezone=Australia/Yancowinna -Druntime.java=8
```
**Reproduces locally?**:
yes
**Applicable branches**:
master, 7.x

**Failure excerpt**:
```
org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotRecoveryStateIntegrationTests > testFilesStoredInThePersistentCacheAreMarkedAsReusedInRecoveryState FAILED |  
  | java.lang.AssertionError: should only load repository data on master nodes |  
  | at __randomizedtesting.SeedInfo.seed([1D3F11D71479ACFC:EA0B6E2115E5490D]:0) |  
  | at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:1367) |  
  | at org.elasticsearch.action.support.PlainActionFuture.get(PlainActionFuture.java:32) |  
  | at org.elasticsearch.repositories.blobstore.ESBlobStoreRepositoryIntegTestCase.getRepositoryData(ESBlobStoreRepositoryIntegTestCase.java:77) |  
  | at org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotRecoveryStateIntegrationTests.testFilesStoredInThePersistentCacheAreMarkedAsReusedInRecoveryState(SearchableSnapshotRecoveryStateIntegrationTests.java:185) |  
```

Seems like it is caused by:
https://github.com/elastic/elasticsearch/pull/67780
 https://github.com/elastic/elasticsearch/commit/b467595564c49afa386539670657e41d7fe2961d

**Comment by DaveCTurner** [comment]
I reverted the offending commits from `master` (5e3ad9f20ab35b2318218f430aa67e9577ee25eb) and `7.x` (66b328a5f4b41315165f564db69d1de56c41129f) pending further investigation.

**Comment by DaveCTurner** [comment]
Closing this as the commits were reverted.
