### ISSUE TITLE
[CI] Failure in SearchableSnapshotActionIT.testSearchableSnapshotForceMergesIndexToOneSegment

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#67879]
This failed a couple of times last week:

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testSearchableSnapshotForceMergesIndexToOneSegment" -Dtests.seed=901F56500B783268 -Dtests.security.manager=true -Dtests.locale=ms -Dtests.timezone=America/Virgin -Druntime.java=8
```

fails as:

```
org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT > testSearchableSnapshotForceMergesIndexToOneSegment FAILED
    org.elasticsearch.client.ResponseException: method [DELETE], host [http://[::1]:45419], URI [/_snapshot/XssEL/2021.01.25-.ds-logs-jmrgikzmbx-2021.01.25-000001-policy-yaewi-0otapx4_rl-kwwusue3j8q], status line [HTTP/1.1 503 Service Unavailable]
    {"error":{"root_cause":[{"type":"concurrent_snapshot_execution_exception","reason":"[XssEL:2021.01.25-.ds-logs-jmrgikzmbx-2021.01.25-000001-policy-yaewi-0otapx4_rl-kwwusue3j8q/tQrS1-NdRoefIXTmt75QMA] cannot delete snapshot during a restore in progress in [RestoreInProgress[{TYgVzEj7TKi-wUKD9xMPYA}{XssEL:2021.01.25-.ds-logs-jmrgikzmbx-2021.01.25-000001-policy-yaewi-0otapx4_rl-kwwusue3j8q/tQrS1-NdRoefIXTmt75QMA}]]"}],"type":"concurrent_snapshot_execution_exception","reason":"[XssEL:2021.01.25-.ds-logs-jmrgikzmbx-2021.01.25-000001-policy-yaewi-0otapx4_rl-kwwusue3j8q/tQrS1-NdRoefIXTmt75QMA] cannot delete snapshot during a restore in progress in [RestoreInProgress[{TYgVzEj7TKi-wUKD9xMPYA}{XssEL:2021.01.25-.ds-logs-jmrgikzmbx-2021.01.25-000001-policy-yaewi-0otapx4_rl-kwwusue3j8q/tQrS1-NdRoefIXTmt75QMA}]]"},"status":503}
        at __randomizedtesting.SeedInfo.seed([901F56500B783268:3EC09A4B54875623]:0)
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:302)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:302)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:302)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:302)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:302)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:302)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:302)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
        at org.elasticsearch.test.rest.ESRestTestCase.wipeSnapshots(ESRestTestCase.java:757)
        at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:584)
        at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:344)
        at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.lang.Thread.run(Thread.java:748)
```

See https://gradle-enterprise.elastic.co/s/xqc5p6ffe7fby/console-log/raw

Does not reproduce locally.

**Comment by ywangd** [comment]
Another one, this time on master branch: https://gradle-enterprise.elastic.co/s/u3yalh3s4o6ro

Does not reproduce locally and the error message is the same `concurrent_snapshot_execution_exception`

**Comment by ywangd** [comment]
The same test failed a couple times again on master and 7.x. I muted it on [master](https://github.com/elastic/elasticsearch/commit/55ec78dcc3fb3b25f9e39cee6f8aa303ad70a26f) and [7.x](https://github.com/elastic/elasticsearch/commit/3046f58d16d3b1b7c65bf916c26997e1f4a881c7)

**Comment by original-brownbear** [comment]
Gotta reopen this: https://gradle-enterprise.elastic.co/s/2fqyvsi2g7hik 

@andreidan The problem here turns out to not be with the recovery just showing up for a short period of time, it seems we're staying stuck for some reason (maybe some bug in the restoring of data streams if I had to guess).
