### ISSUE TITLE
[CI] ExecutionVarsIntegrationTests fails

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#67908]
The test ExecutionVarsIntegrationTests fails on CI on `master` branch:
```
org.elasticsearch.xpack.watcher.test.integration.ExecutionVarsIntegrationTests > testVars FAILED
    java.lang.AssertionError: Count is 2 hits but 1 was expected.  Total shards: 1 Successful shards: 1 & 0 shard failures:
        at __randomizedtesting.SeedInfo.seed([285BF92CB6931E5:D6CEA7C8C6DCB5E6]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertHitCount(ElasticsearchAssertions.java:270)
        at org.elasticsearch.xpack.watcher.test.integration.ExecutionVarsIntegrationTests.testVars(ExecutionVarsIntegrationTests.java:140)
```

**Build scan**:
https://gradle-enterprise.elastic.co/s/2uy62shq5bjtg
https://gradle-enterprise.elastic.co/s/c7pigasrdhdcu
https://gradle-enterprise.elastic.co/s/onhmyy3saqzws
https://gradle-enterprise.elastic.co/s/fiefhluatakje

**Repro line**:
```
./gradlew ':x-pack:plugin:watcher:internalClusterTest' --tests "org.elasticsearch.xpack.watcher.test.integration.ExecutionVarsIntegrationTests.testVars" -Dtests.seed=285BF92CB6931E5 -Dtests.security.manager=true -Dtests.locale=es-EC -Dtests.timezone=Etc/GMT0 -Druntime.java=11
```

**Reproduces locally?**:
No

**Applicable branches**:
master

**Failure history**:
Failed 5 times in the last 30 days.

**Comment by tlrx** [comment]
I muted this test on master in 25c480c444d416beb192a109db4ec3945366c168
