### ISSUE TITLE
SimpleSecurityNetty4ServerTransportTests and SimpleSecurityNioTransportTests failing with Connection Reset (FIPS issue?)

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#67928]
**Build scan**: e.g. https://gradle-enterprise.elastic.co/s/aah6vyowgtfxy

**Repro line**:  `REPRODUCE WITH: ./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests.testProfilesIncludesDefault" -Dtests.seed=997AEA1D491B969A -Dtests.security.manager=true -Dtests.locale=ms-MY -Dtests.timezone=Asia/Rangoon -Druntime.java=8 -Dtests.fips.enabled=true`

**Reproduces locally?**: No.

**Applicable branches**: 7.x and 7.11

**Failure history**: A handful of failures over the last month but they started more consistently happening at around 2021-01-19: https://build-stats.elastic.co/goto/fd9a778a5a962bf60f9873d81d45bdf9

**Failure excerpt**:

E.g.

```
org.elasticsearch.xpack.security.transport.netty4.SimpleSecurityNetty4ServerTransportTests > testProfilesIncludesDefault FAILED
    ConnectTransportException[[TS_B][127.0.0.1:33402] general node connection failure]; nested: TransportException[handshake failed because connection reset];
        at __randomizedtesting.SeedInfo.seed([997AEA1D491B969A:E872FEBF0E27A3D0]:0)
        at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.lambda$onResponse$2(TcpTransport.java:968)
        at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:136)
        at org.elasticsearch.transport.TransportHandshaker$HandshakeResponseHandler.handleLocalException(TransportHandshaker.java:150)
        at org.elasticsearch.transport.TransportHandshaker.lambda$sendHandshake$0(TransportHandshaker.java:63)
        at org.elasticsearch.action.ActionListener.lambda$wrap$0(ActionListener.java:197)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:128)
        at org.elasticsearch.action.ActionListener.lambda$toBiConsumer$2(ActionListener.java:211)
        at org.elasticsearch.common.concurrent.CompletableContext.lambda$addListener$0(CompletableContext.java:39)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
        at org.elasticsearch.common.concurrent.CompletableContext.complete(CompletableContext.java:61)
        at org.elasticsearch.transport.netty4.Netty4TcpChannel.lambda$addListener$0(Netty4TcpChannel.java:61)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1158)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:760)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:736)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:607)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:105)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:171)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        TransportException[handshake failed because connection reset]
            at org.elasticsearch.transport.TransportHandshaker.lambda$sendHandshake$0(TransportHandshaker.java:63)
            ... 31 more
```

**Comment by jkakavas** [comment]
@DaveCTurner given your example build scan, this is part of https://github.com/elastic/elasticsearch/issues/61316 and only applicable to Azul Zulu 8. It became a problem with Gradle 6.8 [recently](https://github.com/elastic/elasticsearch/issues/61316#issuecomment-763392130) and It was resolved for 7.x 5 days ago and for 7.11 today.
