### ISSUE TITLE
HistoryTemplateHttpMappingsTests#testHttpFields failure

### ISSUE THREAD

**Issue by williamrandolph** [elastic/elasticsearch#68079]
#### Build Scan ####

* https://gradle-enterprise.elastic.co/s/hzbzg6od6w4v2
* https://gradle-enterprise.elastic.co/s/y4c5n5xdx6dig/

5 failures in the past 7 days.

#### Reproduction Line ####

```
./gradlew ':x-pack:plugin:watcher:internalClusterTest' \
  --tests "org.elasticsearch.xpack.watcher.history.HistoryTemplateHttpMappingsTests.testHttpFields" \
  -Dtests.seed=B3C10E2EDEA91CDC -Dtests.security.manager=true -Dtests.locale=ar-SA \
  -Dtests.timezone=Europe/Tallinn -Druntime.java=11 |  
```

#### Reproduces Locally? ####

I got a similar failure twice in 1,000 runs, so it's not a deterministic failure, but not vanishingly rare.

#### Failure Message ####

```
org.elasticsearch.xpack.watcher.history.HistoryTemplateHttpMappingsTests > testHttpFields FAILED
  java.lang.AssertionError:
  Expected: is <1L>
  but: was <2L>
  at __randomizedtesting.SeedInfo.seed([B3C10E2EDEA91CDC:6C2AE317CFE47C27]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.watcher.history.HistoryTemplateHttpMappingsTests.testHttpFields(HistoryTemplateHttpMappingsTests.java:107)
```

#### Applicable Branches ####

Just `master`, as far as I've seen.

#### Interesting bit from the stack trace ####

I found something curious in the [test logs](https://gradle-enterprise.elastic.co/s/hzbzg6od6w4v2/console-log/raw?task=:x-pack:plugin:watcher:internalClusterTest).

```
[2021-01-27T21:57:54,382][ERROR][o.e.t.h.MockWebServer    ] [[HTTP-Dispatcher]] failed to respond to request [GET /input/path]
java.lang.NullPointerException: null
 at org.elasticsearch.test.http.MockWebServer.lambda$start$1(MockWebServer.java:115) [x-pack-core-test-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77) [jdk.httpserver:?]
  at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82) [jdk.httpserver:?]
  at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80) [jdk.httpserver:?]
  at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692) [jdk.httpserver:?]
  at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77) [jdk.httpserver:?]
  at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664) [jdk.httpserver:?]
  at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159) [jdk.httpserver:?]
  at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:442) [jdk.httpserver:?]
  at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:408) [jdk.httpserver:?]
  at java.lang.Thread.run(Thread.java:834) [?:?]
[2021-01-27T21:57:54,394][ERROR][o.e.x.w.i.h.ExecutableHttpInput] [testHttpFields] failed to execute [http] input for watch [_id], reason [localhost:45995 failed to respond]
```

I've seen these two error logs in every failure I've spotted.

**Comment by burqen** [comment]
This test was fixed by @williamrandolph https://github.com/elastic/elasticsearch/pull/68021 but this issue was not closed. It was just now reassigned to `Team:Distributed`. The test has no failures in the last 7 days so I will close this issue.
