### ISSUE TITLE
 [CI] PermissionsIT.testCanManageIndexWithNoPermissions failure

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#68098]
**Build scan**:

https://gradle-enterprise.elastic.co/s/cdjjj6ewquzpa

**Repro line**:

```
./gradlew ':x-pack:plugin:ilm:qa:with-security:javaRestTest' --tests "org.elasticsearch.xpack.security.PermissionsIT.testCanManageIndexWithNoPermissions" \
  -Dtests.seed=F0371B631FABAFDB \
  -Dtests.security.manager=true \
  -Dtests.locale=nb-NO \
  -Dtests.timezone=NZ-CHAT \
  -Druntime.java=11
```

**Reproduces locally?**:

Not after several runs.

**Applicable branches**:

master

**Failure history**:

only seen this once

**Failure excerpt**:

```
java.lang.AssertionError: 
Expected: "ERROR"
     but: was "wait-for-shard-history-leases"
	at __randomizedtesting.SeedInfo.seed([F0371B631FABAFDB:7B16F368D93E02FF]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.security.PermissionsIT.lambda$testCanManageIndexWithNoPermissions$2(PermissionsIT.java:142)
```

**Comment by probakowski** [comment]
Another one https://gradle-enterprise.elastic.co/s/qcjvka3v74dy2

**Comment by andreidan** [comment]
This is a duplicate of https://github.com/elastic/elasticsearch/issues/69925 and has been fixed.
