### ISSUE TITLE
[CI] DocsClientYamlTestSuiteIT.test {yaml=reference/rest-api/usage/line_39} failure

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#68101]
**Build scan**:

https://gradle-enterprise.elastic.co/s/gkwrfu7vcedre

**Repro line**:

```
./gradlew ':docs:integTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/rest-api/usage/line_39}" \
  -Dtests.seed=F198448862F3D5DE \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=cs-CZ \
  -Dtests.timezone=America/Ensenada \
  -Druntime.java=11
```

**Reproduces locally?**:

Yes

**Applicable branches**:

master, 7.x, 7.11

**Failure history**:

Five failures in the last 12h

**Failure excerpt:**

```
java.lang.RuntimeException: Failure at [reference/rest-api/usage:16]: stashed value not found for key [body.watcher.execution.actions.logging.total]
	at __randomizedtesting.SeedInfo.seed([F198448862F3D5DE:79CC7B52CC0FB826]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:418)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:393)
```
```
[2021-01-28T00:15:13,093][INFO ][o.e.s.DocsClientYamlTestSuiteIT] [test] [yaml=reference/rest-api/usage/line_39] before test
[2021-01-28T00:15:13,263][INFO ][o.e.s.DocsClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  "stash" : {
    "body" : {
      "aggregate_metric" : {
        "available" : true,
        "enabled" : true
      },
      "analytics" : {
        "available" : true,
        "enabled" : true,
        "stats" : {
          "boxplot_usage" : 0,
          "cumulative_cardinality_usage" : 0,
          "string_stats_usage" : 2,
          "top_metrics_usage" : 0,
          "t_test_usage" : 1,
          "moving_percentiles_usage" : 0,
          "normalize_usage" : 0,
          "rate_usage" : 1
        }
      },
      "ccr" : {
        "available" : true,
        "enabled" : true,
        "follower_indices_count" : 0,
        "auto_follow_patterns_count" : 0
      },
      "data_streams" : {
        "available" : true,
        "enabled" : true,
        "data_streams" : 0,
        "indices_count" : 0
      },
      "data_tiers" : {
        "available" : true,
        "enabled" : true,
        "data_warm" : {
          "node_count" : 1,
          "index_count" : 0,
          "total_shard_count" : 0,
          "primary_shard_count" : 0,
          "doc_count" : 0,
          "total_size_bytes" : 0,
          "primary_size_bytes" : 0,
          "primary_shard_size_avg_bytes" : 0,
          "primary_shard_size_median_bytes" : 0,
          "primary_shard_size_mad_bytes" : 0
        },
        "data_cold" : {
          "node_count" : 1,
          "index_count" : 0,
          "total_shard_count" : 0,
          "primary_shard_count" : 0,
          "doc_count" : 0,
          "total_size_bytes" : 0,
          "primary_size_bytes" : 0,
          "primary_shard_size_avg_bytes" : 0,
          "primary_shard_size_median_bytes" : 0,
          "primary_shard_size_mad_bytes" : 0
        },
        "data_content" : {
          "node_count" : 1,
          "index_count" : 0,
          "total_shard_count" : 0,
          "primary_shard_count" : 0,
          "doc_count" : 0,
          "total_size_bytes" : 0,
          "primary_size_bytes" : 0,
          "primary_shard_size_avg_bytes" : 0,
          "primary_shard_size_median_bytes" : 0,
          "primary_shard_size_mad_bytes" : 0
        },
        "data_hot" : {
          "node_count" : 1,
          "index_count" : 0,
          "total_shard_count" : 0,
          "primary_shard_count" : 0,
          "doc_count" : 0,
          "total_size_bytes" : 0,
          "primary_size_bytes" : 0,
          "primary_shard_size_avg_bytes" : 0,
          "primary_shard_size_median_bytes" : 0,
          "primary_shard_size_mad_bytes" : 0
        }
      },
      "eql" : {
        "available" : true,
        "enabled" : true,
        "features" : {
          "joins" : {
            "join_queries_three" : 0,
            "join_queries_two" : 0,
            "join_until" : 0,
            "join_queries_five_or_more" : 0,
            "join_queries_four" : 0
          },
          "sequence" : 0,
          "keys" : {
            "join_keys_two" : 0,
            "join_keys_one" : 0,
            "join_keys_three" : 0,
            "join_keys_five_or_more" : 0,
            "join_keys_four" : 0
          },
          "join" : 0,
          "sequences" : {
            "sequence_queries_three" : 0,
            "sequence_queries_four" : 0,
            "sequence_queries_two" : 0,
            "sequence_until" : 0,
            "sequence_queries_five_or_more" : 0,
            "sequence_maxspan" : 0
          },
          "event" : 0,
          "pipes" : {
            "pipe_tail" : 0,
            "pipe_head" : 0
          }
        },
        "queries" : {
          "all" : {
            "total" : 0,
            "failed" : 0
          },
          "_all" : {
            "total" : 0,
            "failed" : 0
          }
        }
      },
      "frozen_indices" : {
        "available" : true,
        "enabled" : true,
        "indices_count" : 0
      },
      "graph" : {
        "available" : true,
        "enabled" : true
      },
      "ilm" : {
        "policy_count" : 7,
        "policy_stats" : [
          {
            "phases" : {
              "hot" : {
                "min_age" : 0,
                "actions" : [
                  "rollover"
                ]
              }
            },
            "indices_managed" : 0
          },
          {
            "phases" : {
              "delete" : {
                "min_age" : 604800000,
                "actions" : [
                  "delete"
                ]
              }
            },
            "indices_managed" : 0
          },
          {
            "phases" : {
              "hot" : {
                "min_age" : 0,
                "actions" : [
                  "rollover"
                ]
              }
            },
            "indices_managed" : 0
          },
          {
            "phases" : {
              "hot" : {
                "min_age" : 0,
                "actions" : [
                  "rollover"
                ]
              }
            },
            "indices_managed" : 0
          },
          {
            "phases" : {
              "hot" : {
                "min_age" : 0,
                "actions" : [
                  "rollover"
                ]
              }
            },
            "indices_managed" : 0
          },
          {
            "phases" : {
              "hot" : {
                "min_age" : 0,
                "actions" : [
                  "rollover"
                ]
              }
            },
            "indices_managed" : 0
          },
          {
            "phases" : {
              "hot" : {
                "min_age" : 0,
                "actions" : [
                  "rollover"
                ]
              },
              "delete" : {
                "min_age" : 7776000000,
                "actions" : [
                  "delete"
                ]
              }
            },
            "indices_managed" : 0
          }
        ]
      },
      "logstash" : {
        "available" : true,
        "enabled" : true
      },
      "ml" : {
        "available" : true,
        "enabled" : true,
        "jobs" : {
          "_all" : {
            "count" : 0,
            "detectors" : {
              "total" : 0.0,
              "min" : 0.0,
              "avg" : 0.0,
              "max" : 0.0
            },
            "created_by" : { },
            "model_size" : {
              "total" : 0.0,
              "min" : 0.0,
              "avg" : 0.0,
              "max" : 0.0
            },
            "forecasts" : {
              "total" : 0,
              "forecasted_jobs" : 0
            }
          }
        },
        "datafeeds" : {
          "_all" : {
            "count" : 0
          }
        },
        "data_frame_analytics_jobs" : {
          "_all" : {
            "count" : 0
          }
        },
        "inference" : {
          "ingest_processors" : {
            "_all" : {
              "num_docs_processed" : {
                "max" : 0,
                "sum" : 0,
                "min" : 0
              },
              "pipelines" : {
                "count" : 0
              },
              "num_failures" : {
                "max" : 0,
                "sum" : 0,
                "min" : 0
              },
              "time_ms" : {
                "max" : 0,
                "sum" : 0,
                "min" : 0
              }
            }
          },
          "trained_models" : {
            "_all" : {
              "count" : 0
            }
          }
        },
        "node_count" : 1
      },
      "monitoring" : {
        "available" : true,
        "enabled" : true,
        "collection_enabled" : false,
        "enabled_exporters" : {
          "local" : 1
        }
      },
      "rollup" : {
        "available" : true,
        "enabled" : true
      },
      "runtime_fields" : {
        "available" : true,
        "enabled" : true,
        "field_types" : [ ]
      },
      "searchable_snapshots" : {
        "available" : true,
        "enabled" : true,
        "indices_count" : 0
      },
      "security" : {
        "available" : true,
        "enabled" : false,
        "ssl" : {
          "http" : {
            "enabled" : false
          },
          "transport" : {
            "enabled" : false
          }
        }
      },
      "slm" : {
        "available" : true,
        "enabled" : true
      },
      "spatial" : {
        "available" : true,
        "enabled" : true
      },
      "sql" : {
        "available" : true,
        "enabled" : true,
        "features" : {
          "having" : 0,
          "subselect" : 0,
          "limit" : 0,
          "orderby" : 1,
          "where" : 0,
          "groupby" : 0,
          "join" : 0,
          "local" : 0,
          "command" : 0
        },
        "queries" : {
          "rest" : {
            "total" : 2,
            "paging" : 1,
            "failed" : 0
          },
          "cli" : {
            "total" : 0,
            "paging" : 0,
            "failed" : 0
          },
          "canvas" : {
            "total" : 0,
            "paging" : 0,
            "failed" : 0
          },
          "odbc" : {
            "total" : 0,
            "paging" : 0,
            "failed" : 0
          },
          "jdbc" : {
            "total" : 0,
            "paging" : 0,
            "failed" : 0
          },
          "odbc32" : {
            "total" : 0,
            "paging" : 0,
            "failed" : 0
          },
          "odbc64" : {
            "total" : 0,
            "paging" : 0,
            "failed" : 0
          },
          "_all" : {
            "total" : 2,
            "paging" : 1,
            "failed" : 0
          },
          "translate" : {
            "count" : 0
          }
        }
      },
      "transform" : {
        "available" : true,
        "enabled" : true
      },
      "vectors" : {
        "available" : true,
        "enabled" : true,
        "dense_vector_fields_count" : 0,
        "dense_vector_dims_avg_count" : 0
      },
      "voting_only" : {
        "available" : true,
        "enabled" : true
      },
      "watcher" : {
        "available" : true,
        "enabled" : true,
        "execution" : {
          "actions" : {
            "_all" : {
              "total" : 0,
              "total_time_in_ms" : 0
            }
          }
        },
        "watch" : {
          "input" : {
            "_all" : {
              "total" : 0,
              "active" : 0
            }
          },
          "trigger" : {
            "_all" : {
              "total" : 0,
              "active" : 0
            }
          }
        },
        "count" : {
          "total" : 0,
          "active" : 0
        }
      }
    }
  }
}]
[2021-01-28T00:15:13,314][INFO ][o.e.s.DocsClientYamlTestSuiteIT] [test] [yaml=reference/rest-api/usage/line_39] after test
```

**Comment by cbuescher** [comment]
I suspect this might have started somewhere with c91a808732c8de7c4aef2f972006974912e7544e, @lockewritesdocs could you take a look to narrow things down a bit more?

**Comment by cbuescher** [comment]
Tried muting this on master, 7.x and 7.11 by adding skips to the TESTRESPONSE check, see https://github.com/elastic/elasticsearch/commit/b85d52adbd3df383ee038bdc57bf2a126cd2c474

**Comment by lockewritesdocs** [comment]
From my testing, it seems that the `"logging"` action for the Watcher context is not being respected or validated in some way. If you look at the output that @cbuescher posted above (thanks Christoph!) there is no `"logging"` action for the Watcher context, even though it's explicitly included in the [`usage` API example](https://github.com/elastic/elasticsearch/blame/master/docs/reference/rest-api/usage.asciidoc#L71).

Looking at the second example from the [watcher condition context](https://www.elastic.co/guide/en/elasticsearch/painless/7.11/painless-watcher-condition-context.html), there's a specific logging action:

```
"logging" : {
          "text" : "At least one play has grossed over $50,000: {{ctx.payload.aggregations.theatres.buckets}}"
        }
```
When you run this action, the condition isn't met, which could be an issue for when the `usage` API checks on things:

```
"actions" : [
        {
          "id" : "my_log",
          "type" : "logging",
          "status" : "condition_failed",
          "condition" : {
            "type" : "script",
            "status" : "success",
            "met" : false
          },
          "reason" : "condition not met. skipping"
        }
      ]
```

The example after that one (the third on the page) has a similar issue with the `log_money_makers` action:

```
"actions" : {
      "log_money_makers" : {
        "condition": {
          "script" : "return ctx.payload.money_makers.size() > 0"
        },
```
This condition is also not met:
```
"actions" : [
        {
          "id" : "log_money_makers",
          "type" : "logging",
          "status" : "condition_failed",
          "condition" : {
            "type" : "script",
            "status" : "success",
            "met" : false
          },
          "reason" : "condition not met. skipping"
        },
```

This example is more interesting than the previous one, because it's included in [a single file](https://github.com/elastic/elasticsearch/blob/master/docs/painless/painless-contexts/painless-watcher-context-example.asciidoc), and then reused in both the Watcher condition and Watcher context pages via [an include statement](https://github.com/elastic/elasticsearch/blame/master/docs/painless/painless-contexts/painless-watcher-transform-context.asciidoc#L160) in both files.

I surmize that the `usage` API is hitting that example and throwing an error because the `log_money_makers` condition fails, but then it fails _again_ since that example is being called in two different files. I don't have a great way to test that scenario, but I bet it's not helping.

I think that there are two courses of action here, and look to @stu-elastic and @jdconrad  for guidance:

1. Augment the sample data so that the `"logging"` actions succeed as designed.
2. Remove the erroneous `"logging"` actions from the examples so that the `usage` API doesn't try to operate on them.

In either case, I think we should:

1. Not reuse the examples in both Watcher pages because it forces the build to run those examples twice.
2. Include a response for each of the examples to highlight the parts we want to illustrate to users. This effort is not trivial, because the examples are complex and generate a very long response.

**Comment by jdconrad** [comment]
@lockewritesdocs If we can guarantee the conditions we want to trigger, I like augmenting the sample data better. I do agree that having the examples twice doesn't make sense.

**Comment by stu-elastic** [comment]
Great analysis @lockewritesdocs.

I'm for 1, updating sample data and 1 with your suggestions.

I'll have to ponder suggestion 2.

**Comment by lockewritesdocs** [comment]
@jdconrad, if we're going to augment the sample data to achieve sales of `50000`, we would need to add a _lot_ of data. With the current data, I had to change the money value to `20` for this example to work. 

```
"logging" : {
            "logged_text" : "At least one play has grossed over $20: {0={doc_count=1, money={value=21.25}, key=Sunnyside Down}, 1={doc_count=1, money={value=17.5}, key=Test Run}}"
          }
```
We could change `50000` to `20` in the script. It's not as much of a real-world example, but would mean we wouldn't need to inject a lot more data. Alternatively, we could modify some ticket sales to have higher costs.

**Comment by jdconrad** [comment]
@lockewritesdocs I think it's okay to have it at 20 in the example. I think that even though it's a smaller than real-world value, our users will understand what we're trying to show.
