### ISSUE TITLE
NullPointerException when trying to restore sub-set of indices from a Snapshot containing a Data Stream

### ISSUE THREAD

**Issue by ChrisSamo632** [elastic/elasticsearch#68357]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.9.3

**Plugins installed**: [repository-s3, analysis-phonetic]

**JVM version** (`java -version`): (docker.elastic.co/elasticsearch/elasticsearch:7.9.3)
openjdk version "15" 2020-09-15
OpenJDK Runtime Environment (build 15+36-1562)
OpenJDK 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system): (docker.elastic.co/elasticsearch/elasticsearch:7.9.3)
Linux elasticsearch-0 4.19.128-flatcar #1 SMP Tue Jun 16 10:17:17 -00 2020 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Attempts to Restore a single index from a Snapshot (containing a Data Stream as well as normal indices) fail with a NullPointerException (stacktrace below); would expect the restore request to be successfully acknowledged and processed.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Create "basic" index containing a document
```
PUT my-index/_doc/1
{ "foo": "bar" }
```
 2. Create a Data Stream (with template and ILM) containing a document
```
PUT _ilm/policy/my-data-stream-ilm-policy
{
    "policy": {
        "phases": {
            "warm": {
                "min_age": "0ms",
                "actions": {
                    "shrink": {
                        "number_of_shards": 1
                    },
                    "forcemerge": {
                        "max_num_segments": 1
                    },
                    "set_priority": {
                        "priority": 50
                    },
                    "readonly": {}
                }
            },
            "hot": {
                "min_age": "0ms",
                "actions": {
                    "rollover": {
                        "max_age": "1d",
                        "max_docs": "10000000"
                    },
                    "set_priority": {
                        "priority": 100
                    }
                }
            },
            "delete": {
                "min_age": "20d",
                "actions": {
                    "wait_for_snapshot": {
                        "policy": "s3-hourly-snapshot"
                    },
                    "delete": {}
                }
            }
        }
    }
}

POST _index_template/my-data-stream
{
  "index_patterns": [
    "my-data-stream*"
  ],
  "data_stream": {},
  "template": {
    "settings": {
      "lifecycle.name": "my-data-stream-ilm-policy",
      "lifecycle.rollover_alias": "my-data-stream-write"
    }
  },
  "version": 1
}

PUT _data_stream/my-data-stream

POST my-data-stream/_doc
{  "bar": "baz" }
```
 3. Create SLM Repository and Policy including index and Data Stream
```
PUT _snapshot/s3_repository
{
  "type": "s3",
  "settings": {"bucket": "my-bucket", "base_path": "my-path", "server_side_encryption": true, "storage_class": "standard" }
}

PUT _slm/policy/s3-hourly-snapshot
{
   "schedule": "0 0 * * * ?",
   "name": "<snapshot-{now{yyyy.MM.dd-HH}}>",
   "repository": "s3_repository",
   "retention": { "expire_after": "10d"  },
   "config": { "indices": [ "my-index*", "my-data-stream" ] }
}
```
 4. Perform Snapshot
```
POST /_snapshot/s3_repository/my-snapshot
```
 5. Attempt Restore (once Snapshot completed and verified)
```
POST /_snapshot/s3_repository/my-snapshot/_restore
{ "indices": [ "my-index" ] }
```

**Provide logs (if relevant)**:

* Response from Restore request:
```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "null_pointer_exception",
        "reason" : null
      }
    ],
    "type" : "null_pointer_exception",
    "reason" : null
  },
  "status" : 500
}
```

* Stacktrace in Elasticsearch logs:
```
{"type": "server", "timestamp": "2021-02-02T11:21:16,550Z", "level": "WARN", "component": "r.suppressed", "cluster.name": "...-elasticsearch", "node.name": "elasticsearch-0.elasticsearch-hs.....svc.cluster.local", "message": "path: /_snapshot/s3_repository/snapshot-2021.02.02-11-.../_restore, params: {pretty=true, repository=s3_repository, snapshot=snapshot-2021.02.02-11-...}", "cluster.uuid": "...", "node.id": "..." , 
"stacktrace": ["java.lang.NullPointerException: null",
"at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]",
"at java.util.ImmutableCollections$ListN.<init>(ImmutableCollections.java:530) ~[?:?]",
"at java.util.List.of(List.java:1045) ~[?:?]",
"at java.util.ImmutableCollections.listCopy(ImmutableCollections.java:148) ~[?:?]",
"at java.util.List.copyOf(List.java:1066) ~[?:?]",
"at org.elasticsearch.common.collect.List.copyOf(List.java:79) ~[elasticsearch-core-7.9.3.jar:7.9.3]",
"at org.elasticsearch.cluster.metadata.IndexAbstraction$DataStream.<init>(IndexAbstraction.java:295) ~[elasticsearch-7.9.3.jar:7.9.3]",
"at org.elasticsearch.cluster.metadata.Metadata$Builder.buildIndicesLookup(Metadata.java:1495) ~[elasticsearch-7.9.3.jar:7.9.3]",
"at org.elasticsearch.cluster.metadata.Metadata$Builder.build(Metadata.java:1462) ~[elasticsearch-7.9.3.jar:7.9.3]",
"at org.elasticsearch.snapshots.RestoreService.lambda$restoreSnapshot$2(RestoreService.java:251) ~[elasticsearch-7.9.3.jar:7.9.3]",
"at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.9.3.jar:7.9.3]",
"at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:112) [elasticsearch-7.9.3.jar:7.9.3]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.9.3.jar:7.9.3]",
"at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:226) [elasticsearch-7.9.3.jar:7.9.3]",
"at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:106) [elasticsearch-7.9.3.jar:7.9.3]",
"at org.elasticsearch.common.util.concurrent.ListenableFuture.addListener(ListenableFuture.java:68) [elasticsearch-7.9.3.jar:7.9.3]",
"at org.elasticsearch.action.StepListener.whenComplete(StepListener.java:78) [elasticsearch-7.9.3.jar:7.9.3]",
"at org.elasticsearch.snapshots.RestoreService.restoreSnapshot(RestoreService.java:192) [elasticsearch-7.9.3.jar:7.9.3]",
"at org.elasticsearch.action.admin.cluster.snapshots.restore.TransportRestoreSnapshotAction.masterOperation(TransportRestoreSnapshotAction.java:80) [elasticsearch-7.9.3.jar:7.9.3]",
"at org.elasticsearch.action.admin.cluster.snapshots.restore.TransportRestoreSnapshotAction.masterOperation(TransportRestoreSnapshotAction.java:41) [elasticsearch-7.9.3.jar:7.9.3]",
"at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:99) [elasticsearch-7.9.3.jar:7.9.3]",
"at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$3(TransportMasterNodeAction.java:170) [elasticsearch-7.9.3.jar:7.9.3]",
"at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73) [elasticsearch-7.9.3.jar:7.9.3]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:737) [elasticsearch-7.9.3.jar:7.9.3]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.9.3.jar:7.9.3]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
"at java.lang.Thread.run(Thread.java:832) [?:?]"] }
```

**Comment by ChrisSamo632** [comment]
We realise Data Streams are handled differently in SLM/Snapshot/Restore compared to "normal" indices and there are different requirments/restrictions for their restoration into a running cluster (e.g. the Data Stream can't be restored if there's another Data Stream already present with the same name, etc.).

However, we'd expect to be able to exclude the Data Stream from our Snapshot and Restore just the "normal" indices without issue.

I'd guess this NPE is the result of the code not looking for Data Stream details when trying to gather information about the indices within the Snapshot (or something along those lines, from a very quick look at the stacktrace above).

The likely workaround (for us at least) will be to separate out Data Stream into their own SLM Policies, rather than keeping everything together in one as we have previously.

**Comment by original-brownbear** [comment]
This still reproduces on `master`, I'm on it for a fix.
