### ISSUE TITLE
elasticsearch-plugin hangs if prompt not answered y

### ISSUE THREAD

**Issue by thewunder** [elastic/elasticsearch#68419]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.2

**Plugins installed**: []

**JVM version** (`java -version`): openjdk 11.0.9.1 2020-11-04

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 20.04.1

**Description of the problem including expected versus actual behavior**:

When running elasticsearch-plugin install, if you answer N (or terminate the process in any way, Ctrl-C, etc..) instead of answering the Continue with installation? [y/N] prompt further attempts to install any other plugin will hang after download. The issue persists even after a reboot. This is making automation quite difficult.

If the prompt isn't answered it should prompt you again next time you run install.

**Steps to reproduce**:

```
$ sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install repository-s3
```

Answer N  (or Ctrl-C)at the Continue with installation? [y/N] prompt 

```
$ sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install repository-s3
```

And the process will hang it seems for about 15 minutes.

**Comment by DaveCTurner** [comment]
I couldn't reproduce this: for me, answering 'N' and hitting Ctrl-C both exit the installer as expected, and a subsequent attempt to install a plugin works just fine:

```
[ 13:41:53 ~/issues/68419/elasticsearch-7.10.2 ]
$ bin/elasticsearch-plugin install repository-s3
-> Installing repository-s3
-> Downloading repository-s3 from elastic
[=================================================] 100%
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission es.allow_insecure_settings read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]n
-> Failed installing repository-s3
-> Rolling back repository-s3
-> Rolled back repository-s3
ERROR: installation aborted by user
[ 13:42:10 ~/issues/68419/elasticsearch-7.10.2 ]
$ bin/elasticsearch-plugin install repository-s3
-> Installing repository-s3
-> Downloading repository-s3 from elastic
[=================================================] 100%
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission es.allow_insecure_settings read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]n
-> Failed installing repository-s3
-> Rolling back repository-s3
-> Rolled back repository-s3
ERROR: installation aborted by user
[ 13:42:41 ~/issues/68419/elasticsearch-7.10.2 ]
$ bin/elasticsearch-plugin install repository-s3
-> Installing repository-s3
-> Downloading repository-s3 from elastic
[=================================================] 100%
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission es.allow_insecure_settings read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]^C%
[ 13:42:55 ~/issues/68419/elasticsearch-7.10.2 ]
$ bin/elasticsearch-plugin install repository-s3
-> Installing repository-s3
-> Downloading repository-s3 from elastic
[=================================================] 100%
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission es.allow_insecure_settings read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]y
-> Installed repository-s3
[ 13:43:13 ~/issues/68419/elasticsearch-7.10.2 ]
$
```

What processes are running during the "hang"? Are they consuming a lot of CPU or are they idle? If they are Java processes, can you use `jstack` to extract a stack dump which would indicate what they're doing.

**Comment by DaveCTurner** [comment]
Having received no response to our followup questions, I am closing this.

**Comment by thewunder** [comment]
@DaveCTurner Sorry for the lack of response, no there is no cpu usage... completely idle

**Comment by nakulmanimala** [comment]
I am also facing the same. 

`root@xxxxxxxxxx:~# /usr/share/elasticsearch/bin/elasticsearch-plugin install repository-s3 -v
-> Installing repository-s3
Checking if url exists: https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-linux-x86_64-7.12.1.zip
-> Downloading repository-s3 from elastic
Retrieving zip from https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-7.12.1.zip
[=================================================] 100%   

`
waited for 15 minuets.

**Comment by mmenozzi** [comment]
Hi @DaveCTurner, I also have this issue on Ubuntu 20.04 installing the `analysis-phonetic` and `analysis-icu` plugin. This is a jstack dump of an hanged installation process for `analysis-phonetic`.

```
$ ps aux | grep java
root       89406  0.8  5.7 2124908 116768 pts/0  Sl+  08:33   0:06 /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Xms4m -Xmx64m -XX:+UseSerialGC -Des.path.home=/usr/share/elasticsearch -Des.path.conf=/etc/elasticsearch -Des.distribution.flavor=default -Des.distribution.type=deb -cp /usr/share/elasticsearch/lib/*:/usr/share/elasticsearch/lib/tools/plugin-cli/* org.elasticsearch.plugins.cli.PluginCli install analysis-phonetic -v

$ jstack 89406
2022-02-11 08:44:01
Full thread dump OpenJDK 64-Bit Server VM (17.0.1+12 mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x00007fe1d8001dc0, length=12, elements={
0x00007fe204024320, 0x00007fe20405dfd0, 0x00007fe20405f3e0, 0x00007fe2040659b0,
0x00007fe204066d30, 0x00007fe204068110, 0x00007fe204069a90, 0x00007fe20406af90,
0x00007fe20406c3d0, 0x00007fe2040a7de0, 0x00007fe2040ab550, 0x00007fe1d80013e0
}

"main" #1 prio=5 os_prio=0 cpu=2447.81ms elapsed=643.75s tid=0x00007fe204024320 nid=0x15d62 runnable  [0x00007fe20939b000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(java.base@17.0.1/Native Method)
	at java.io.FileInputStream.read(java.base@17.0.1/FileInputStream.java:276)
	at java.io.FilterInputStream.read(java.base@17.0.1/FilterInputStream.java:132)
	at sun.security.provider.NativePRNG$RandomIO.readFully(java.base@17.0.1/NativePRNG.java:425)
	at sun.security.provider.NativePRNG$RandomIO.implGenerateSeed(java.base@17.0.1/NativePRNG.java:442)
	- locked <0x00000000fdba8370> (a java.lang.Object)
	at sun.security.provider.NativePRNG.engineGenerateSeed(java.base@17.0.1/NativePRNG.java:227)
	at java.security.SecureRandom.generateSeed(java.base@17.0.1/SecureRandom.java:864)
	at org.bouncycastle.crypto.util.BasicEntropySourceProvider$1.getEntropy(Unknown Source)
	at org.bouncycastle.crypto.fips.ContinuousTestingEntropySource.getEntropy(Unknown Source)
	- locked <0x00000000fc875fd0> (a org.bouncycastle.crypto.fips.ContinuousTestingEntropySource)
	at org.bouncycastle.crypto.fips.HashSP800DRBG.getEntropy(Unknown Source)
	at org.bouncycastle.crypto.fips.HashSP800DRBG.init(Unknown Source)
	at org.bouncycastle.crypto.fips.HashSP800DRBG.<init>(Unknown Source)
	at org.bouncycastle.crypto.fips.FipsDRBG$HashDRBGProvider.get(Unknown Source)
	at org.bouncycastle.crypto.fips.DRBGPseudoRandom.lazyInitDRBG(Unknown Source)
	at org.bouncycastle.crypto.fips.DRBGPseudoRandom.generate(Unknown Source)
	- locked <0x00000000fc871680> (a org.bouncycastle.crypto.fips.DRBGPseudoRandom)
	at org.bouncycastle.crypto.fips.FipsSecureRandom$RandomSpi.engineNextBytes(Unknown Source)
	- locked <0x00000000fc871680> (a org.bouncycastle.crypto.fips.DRBGPseudoRandom)
	at java.security.SecureRandom.nextBytes(java.base@17.0.1/SecureRandom.java:761)
	- locked <0x00000000fc86eaa0> (a org.bouncycastle.crypto.fips.FipsSecureRandom)
	at java.math.BigInteger.randomBits(java.base@17.0.1/BigInteger.java:718)
	at java.math.BigInteger.<init>(java.base@17.0.1/BigInteger.java:691)
	at org.bouncycastle.util.BigIntegers.createRandomInRange(Unknown Source)
	at org.bouncycastle.math.internal.Primes.enhancedMRProbablePrimeTest(Unknown Source)
	at org.bouncycastle.crypto.asymmetric.KeyUtils.validatedModulus(Unknown Source)
	at org.bouncycastle.crypto.asymmetric.KeyUtils.validated(Unknown Source)
	at org.bouncycastle.crypto.asymmetric.AsymmetricRSAPublicKey.<init>(Unknown Source)
	at org.bouncycastle.jcajce.provider.ProvRSAPublicKey.<init>(Unknown Source)
	at org.bouncycastle.jcajce.provider.ProvRSA$RSAKeyFactory.engineGeneratePublic(Unknown Source)
	at java.security.KeyFactory.generatePublic(java.base@17.0.1/KeyFactory.java:345)
	at org.bouncycastle.openpgp.operator.jcajce.JcaPGPKeyConverter.implGeneratePublic(Unknown Source)
	at org.bouncycastle.openpgp.operator.jcajce.JcaPGPKeyConverter.getPublicKey(Unknown Source)
	at org.bouncycastle.openpgp.operator.jcajce.JcaPGPContentVerifierBuilderProvider$JcaPGPContentVerifierBuilder.build(Unknown Source)
	at org.bouncycastle.openpgp.PGPSignature.init(Unknown Source)
	at org.elasticsearch.plugins.cli.InstallPluginAction.verifySignature(InstallPluginAction.java:677)
	at org.elasticsearch.plugins.cli.InstallPluginAction.downloadAndValidate(InstallPluginAction.java:639)
	at org.elasticsearch.plugins.cli.InstallPluginAction.download(InstallPluginAction.java:318)
	at org.elasticsearch.plugins.cli.InstallPluginAction.execute(InstallPluginAction.java:242)
	at org.elasticsearch.plugins.cli.InstallPluginCommand.execute(InstallPluginCommand.java:88)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:95)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
	at org.elasticsearch.cli.Command.main(Command.java:77)
	at org.elasticsearch.plugins.cli.PluginCli.main(PluginCli.java:36)

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=1.24ms elapsed=643.74s tid=0x00007fe20405dfd0 nid=0x15d64 waiting on condition  [0x00007fe208733000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@17.0.1/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@17.0.1/Reference.java:253)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@17.0.1/Reference.java:215)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=3.99ms elapsed=643.74s tid=0x00007fe20405f3e0 nid=0x15d65 in Object.wait()  [0x00007fe208632000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.1/Native Method)
	- waiting on <0x00000000fd5bccc8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@17.0.1/ReferenceQueue.java:155)
	- locked <0x00000000fd5bccc8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@17.0.1/ReferenceQueue.java:176)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@17.0.1/Finalizer.java:172)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.38ms elapsed=643.73s tid=0x00007fe2040659b0 nid=0x15d66 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #5 daemon prio=9 os_prio=0 cpu=0.33ms elapsed=643.73s tid=0x00007fe204066d30 nid=0x15d67 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Monitor Deflation Thread" #6 daemon prio=9 os_prio=0 cpu=22.78ms elapsed=643.73s tid=0x00007fe204068110 nid=0x15d68 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #7 daemon prio=9 os_prio=0 cpu=2301.14ms elapsed=643.73s tid=0x00007fe204069a90 nid=0x15d69 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #8 daemon prio=9 os_prio=0 cpu=884.53ms elapsed=643.73s tid=0x00007fe20406af90 nid=0x15d6a waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #9 daemon prio=9 os_prio=0 cpu=0.06ms elapsed=643.73s tid=0x00007fe20406c3d0 nid=0x15d6b runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Notification Thread" #10 daemon prio=9 os_prio=0 cpu=0.07ms elapsed=643.70s tid=0x00007fe2040a7de0 nid=0x15d6c runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #11 daemon prio=8 os_prio=0 cpu=1.86ms elapsed=643.69s tid=0x00007fe2040ab550 nid=0x15d6e in Object.wait()  [0x00007fe1ec5f7000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.1/Native Method)
	- waiting on <0x00000000fd5bced8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@17.0.1/ReferenceQueue.java:155)
	- locked <0x00000000fd5bced8> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@17.0.1/CleanerImpl.java:140)
	at java.lang.Thread.run(java.base@17.0.1/Thread.java:833)
	at jdk.internal.misc.InnocuousThread.run(java.base@17.0.1/InnocuousThread.java:162)

"Attach Listener" #20 daemon prio=9 os_prio=0 cpu=0.27ms elapsed=0.10s tid=0x00007fe1d80013e0 nid=0x15f26 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM Thread" os_prio=0 cpu=190.12ms elapsed=643.74s tid=0x00007fe204059820 nid=0x15d63 runnable

"VM Periodic Task Thread" os_prio=0 cpu=695.10ms elapsed=643.69s tid=0x00007fe2040a9700 nid=0x15d6d waiting on condition

JNI global refs: 17, weak refs: 0
```

**Comment by mmenozzi** [comment]
I think that this is related: https://discuss.elastic.co/t/elasticsearch-plugin-install-plugin-hangs/277732

**Comment by DaveCTurner** [comment]
Thanks @mmenozzi, that's helpful indeed. The process is initialising its random-number generator and is waiting for the system to provide it with some entropy.

```
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(java.base@17.0.1/Native Method)
	at java.io.FileInputStream.read(java.base@17.0.1/FileInputStream.java:276)
	at java.io.FilterInputStream.read(java.base@17.0.1/FilterInputStream.java:132)
	at sun.security.provider.NativePRNG$RandomIO.readFully(java.base@17.0.1/NativePRNG.java:425)
	at sun.security.provider.NativePRNG$RandomIO.implGenerateSeed(java.base@17.0.1/NativePRNG.java:442)
	- locked <0x00000000fdba8370> (a java.lang.Object)
	at sun.security.provider.NativePRNG.engineGenerateSeed(java.base@17.0.1/NativePRNG.java:227)
```

I would expect that it reads from `/dev/urandom` which blocks less than `/dev/random` but doesn't guarantee never to block I believe. We'd need a heap dump to confirm which entropy source it's using. What is the uptime of this system? If it's just started up recently then it's more likely to need to wait for entropy.

In any case it's not stuck forever, this `read()` call will eventually return. There may be some OS parameters to adjust to make it return quicker, but that's outside of the scope of what we can help with.

**Comment by mmenozzi** [comment]
Hi @DaveCTurner yes the server started up recently:

```
$ uptime
 09:37:36 up 2 days,  1:07,  2 users,  load average: 0.00, 0.00, 0.00
```

Could you please give me instruction to create an heap dump? I'm not really skilled on Java...

**Comment by DaveCTurner** [comment]
`/usr/share/elasticsearch/jdk/bin/jmap -dump:gz=1,format=b,file=<FILE> <PID>` should capture a heap dump for you.

By "recent" I meant roughly "minutes" -- `up 2 days` should be more than enough time to build entropy.

Try also these commands:

- `dd if=/dev/urandom bs=1024 count=1 | base64`
- `dd if=/dev/random bs=1024 count=1 | base64`

Do they both complete quickly or do they hang too?

**Comment by mmenozzi** [comment]
Here's the [dump](https://github.com/elastic/elasticsearch/files/8047211/dump.gz) and the `dd` commands with their timing:

```
$ time dd if=/dev/urandom bs=1024 count=1 | base64
1+0 records in
1+0 records out
4DdfAIvUpGdLNS1ngy0EAuEYF2cqMM/vUfhjKmutzy5I/Mwy/YIVpHDFHDKM0hOoNGb8SbXugiBo
AJ066wjxkw/Qw7h/bzouzmFbFy/IUJKnpSrtG+cbr+YB4S5Z07N8C6Ox3FTHKKTEV61uPeu20XOO
1B/aGnRa1Lt8zc4+YCQXSYnLb0YjLfT0ZiEeEAlqiz1Y20mmO2ie4G0/ensGwiQCjKmTOulqL0M6
2p/60NAkFSMSm+MfSalltjbMDzLBrBpOUwJi9oLgn6sFhivaBrh9W90tofOyKnuG0Bj06aOeHEz5
6FZF5lW14wXIOS+1ufHBol0AzAOSdMYghVxOwth68nRqS1VSTi+zftBRt6k0AeqlApmYgBaAzeqq
onOIOJijA5rrrAOyX3CaurA6QZPokQLmIdibg3UoZDZgEKy9FDcop5IV7vTIf3ITnqZLDfhgiOzi
wrlFVnjH2Ldjnf1vtzP/w9+YFr6IaPRQwgc1px8G6A3WKZhyMasS00JkgEWbTAIM1syrPNCQwZLh
8EdbS+NHdc/iXAK3YW5ER9HtkRy54jdYgfwn5ELykms9UzCiTBR8WrZdaRnn5H/XNX8UyEoI2lXV
7I3uof0asTwnbCMIJDBcypA3gQ6brgx6gTn15wMCsW+TiyI7vW22TfJnClQCRqCpfe9Yn5jBUjVQ
1mVEszKfMIuI07FQEEJ9ayenCDWtgm6XIxuCsLpcBUVWCJ39gggJCv1XEVjqHiII5FtfHj/MQLxQ
c2SCBvnQvLi6+vH/1hRO+CyLAqPS50VV0/rJSeeUvAeFOAEJiQRk6XUsNRCeme8iSELKyyQzxnNC
9/t1bdX35Z+ArVkcg6w4ynVZwXGydPLxsY+/64bxTJEEyJEOpTCzk/9vQcLxg28dRI01SXWRTia8
26IKBm+MB9EKOaDYZsTXV19vf91glVZC+G2ourlF+Sthr1S2r+o26Hl6kuu+wMugiwD2QVhsLRyi
bq3G57KYYF/NvOhrUULWlLn6KC4AUVK0Cc43ZeHmpeKq0aCYBd1vjRtSCoyexHArWQ+b45DdX7HB
/AyaU/uV2h7tqqoxRdYFWbxUtb4SvylYiVCQYAcbjWrHoaJY2NtuISZ5bi/CeMTlSUN+4JJy5YEC
QUFQo6yZrT9Vfyz9ZtFyqwkOIJ2/JhDzBcmTKw0BHs/mJ+8kdlTFRoQEUUjTbfOyU4ZgLcmpWhqz
sn7+HVe8JKqbvq4wsq5UbeCxgNHxnOeG8Yn/OrKAAz5nZVlMNa9zG1uILLGBBbE3bPYRXhTvDAIe
qR6Gahj6AwKsNJ48oROyTshLpGAKd8cFYm/UDZd6ftCZyuQ0RjwvKh+SufGgAqGJb7gf6DVsDg==
1024 bytes (1.0 kB, 1.0 KiB) copied, 0.00120096 s, 853 kB/s

real	0m0.005s
user	0m0.002s
sys	0m0.002s

$ time dd if=/dev/urandom bs=1024 count=1 | base64
1+0 records in
1+0 records out
W60QGvyslNHs5LvuKddl09Mv1Aj+L0IZwfTvnH64DB2/SoP+g/Lts6j5UWh7f2eV8m5NGhccNl85
v+fhcK9UXgD24IZyrUX2uPCHcutuAabu8fwGYApctI1DDr1hlbNmG2D7bJCsZ7kt0lijt3aW9Ep5
FUEgaSdIZfI+rOyVgJgarTBiyOdOMUrwtH2hsJ8ZxUmWJe0l9yMOm/DqGpOtYSIeVi+bIAnMCJg8
JFvk2HC3rh2M3tJL9/Xu3Q1KhLOpy12ri3Dc6T5bQIP72uPmJlKZcDwdiTjtV610XUvUUfjH5y7G
4SIsHJtD7Qa5arXIeFe+PwmwGP00GfOdtXCPOncHezBDe4gzpDh5cleXmlmzRUvoaarSrDWNnD2p
9PH6/BEHWq4jflmq4h8E3oQZOK97hM55OJ4xlT5rQ44LiVOvevSdWt9RkiYdRw4U3zb4f7aaZ26y
uAfU+O5CFV9dBUNkCKScE8ngKdMd5UPzWNscaakhEXbOygtCxIyvJlp/c6fSl8i3ZW45kCqg0M20
/nmAj8rE3P+IrFF+YPwPxUvnj5gTv00MRxyVafQgfZ7rdqS85cDLky1CNR4dWEEC/Gn283HRFqak
7qNKnA74CgVyJi2TZW0DJv+KXsIbaycV9B4r/cWg8E39YMMzt32+9To878q1rpumBuLbSmABj/+Z
YTeikL37IwQirSgS+uF3Wn4bGVIRj3Lw67LaNQ+6pDWS6VQdhxlqaE/+TGJItccw4Fo0k6J7BXXo
4kV4/Ho8PlMCNeu388jq+nwu4DuBjcvay137waK40J7ThimzjCVH4QBxAIl8AB3CwfdbvJkebJtP
FqRt2+qY91J5yhVHfpihjiYO87bjsYH4UokShhmy1mbUVkSq99j+QymOFGi5BUCs6ni/E7BL7XjX
0ULq3wbXIRoxwQRSlbkPVgHGtXty0kj7bcsY5Ns6Yueuxgg70LOXVKcX3LvvPSLiwM39dik9orHE
/xWgA42q1eUPLRVTNi38CK2slVPc9j/E5821XbFa2qi9r309kLOa2qHjj88Ipw7Ck176msuIN59z
GFDHn0D9mmBEX2GgFgAnT8oAFOpc9u7OcWcVv0i8Ph1uCDazXx7+gVr7UWMZ6DFhyqjPj3yUx/5O
yIpuElwWfggQGyZ1AiLpuoNFMjBksaBVNNhrVuaGHQ6JigSSvpdpGk8JKT3iJv+tzx2v/EujLOZS
skmwWeXY+gMpVm6fmDIVvi/F5Tu+YrYRJcuCcQjI7qiIno9Cwe4AkuJDbyfi9BQC03HHaSvgRBaX
3b/vXsA/O2I/Fi+2KuGRlWtEEPOol5T0bQ9zf6D88ggocPFAPv/DPViUGqW4RSvxjrhIBfzxCQ==
1024 bytes (1.0 kB, 1.0 KiB) copied, 0.00125707 s, 815 kB/s

real	0m0.004s
user	0m0.001s
sys	0m0.002s
```

**Comment by mmenozzi** [comment]
> You ran the same `dd` command twice. Does `dd if=/dev/random bs=1024 count=1 | base64` return quickly?

Ah you're right sorry. I ran the `dd if=/dev/random bs=1024 count=1 | base64` just now and it hanged. Is still running while I'm writing this comment.

So I think that this is the issue.
