### ISSUE TITLE
Test failures around deprecating negative ByteSizeValue

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#68447]
7.x with 6.8.14 mixed cluster failes test when a timestamp is negative. This was deprecated and possibly 7.x tests do not assert about this
```
Values less than -1 bytes are deprecated and will not be supported in the next major version
```
most likely introduced by https://github.com/elastic/elasticsearch/pull/27702
Look out for these tests
```
rg.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT test {p0=mixed_cluster/10_basic/Get index works}
org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT test {p0=mixed_cluster/10_basic/Use the percolate query in mixed cluster}
org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT test {p0=mixed_cluster/10_basic/Verify custom cluster metadata still exists during upgrade}
org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT test {p0=mixed_cluster/10_basic/Verify nodes usage works}
org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT test {p0=mixed_cluster/10_basic/Verify that we can still find things with the template}
org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT test {p0=mixed_cluster/20_date_range/Insert more docs to java index}
org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT test {p0=mixed_cluster/20_date_range/Insert more docs to joda index}
```

**Build scan**:
https://gradle-enterprise.elastic.co/s/oulnm25d3t5wi/tests/failed
**Repro line**:
 ./gradlew ':qa:rolling-upgrade:v6.8.14#oneThirdUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=mixed_cluster/10_basic/Get index works}" -Dtests.seed=8B90F9C7DC1CE193 -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=ru -Dtests.timezone=Australia/Yancowinna -Druntime.java=8 -Dtests.rest.suite=mixed_cluster

**Reproduces locally?**:
not yet.. 

**Applicable branches**:
7.x

**Failure history**:

**Failure excerpt**:

**Comment by mark-vieira** [comment]
FYI, we're getting a lot of these failures and it's not practical to mute because it affects a wholes range of different BWC test suites.

**Comment by williamrandolph** [comment]
The logs for the 6.8 nodes in the upgrade tests have a lot of this going on:

```
» WARN ][o.e.m.o.OsProbe          ] [v6.8.14-0] exception retrieving total swap space size
»  java.lang.reflect.InvocationTargetException: null
»  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
»  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
»  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
»  	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
»  	at org.elasticsearch.monitor.os.OsProbe.getTotalSwapSpaceSize(OsProbe.java:145) [elasticsearch-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
»  	at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:647) [elasticsearch-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
»  	at org.elasticsearch.monitor.os.OsService.<init>(OsService.java:39) [elasticsearch-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
»  	at org.elasticsearch.monitor.MonitorService.<init>(MonitorService.java:33) [elasticsearch-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
»  	at org.elasticsearch.node.Node.<init>(Node.java:424) [elasticsearch-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
»  	at org.elasticsearch.node.Node.<init>(Node.java:279) [elasticsearch-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:217) [elasticsearch-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:217) [elasticsearch-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:397) [elasticsearch-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
»  	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75) [elasticsearch-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
»  	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116) [elasticsearch-cli-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
»  	at org.elasticsearch.cli.Command.main(Command.java:79) [elasticsearch-cli-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) [elasticsearch-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
»  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81) [elasticsearch-7.12.0-SNAPSHOT.jar:7.12.0-SNAPSHOT]
»  Caused by: java.lang.NullPointerException
»  	at jdk.internal.platform.cgroupv1.Metrics.getMemoryAndSwapLimit(Metrics.java:489) ~[?:?]
»  	at sun.management.OperatingSystemImpl.getTotalSwapSpaceSize(OperatingSystemImpl.java:55) ~[?:?]
»  	... 20 more
```

This is https://github.com/elastic/elasticsearch/issues/57312, which was fixed by https://github.com/elastic/elasticsearch/pull/57317. I'm backporting that fix, as well as the very similar https://github.com/elastic/elasticsearch/pull/56435, and hopefully that will take care of these failures.

**Comment by pgomulka** [comment]
looks like this has been fixed by the backport. Thank you @williamrandolph 
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'%22Values%20less%20than%20-1%20bytes%20are%20deprecated%22'),sort:!(process.time-start,desc))
