### ISSUE TITLE
[CI] LocalExporterResourceIntegTests failing on mac (darwin) agents

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#68608]
There are a couple of test cases in this suite that fairly regularly fail on our darwin builds.

**Build scan**:
https://gradle-enterprise.elastic.co/s/2mas55ozercbc/tests/:x-pack:plugin:monitoring:test/org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests/testCreateWhenResourcesNeedToBeAddedOrUpdated#1

**Repro line**:
`./gradlew ':x-pack:plugin:monitoring:test' --tests "org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests.testCreateWhenResourcesNeedToBeAddedOrUpdated" -Dtests.seed=1FEBD07E8BC5E4CD -Dtests.security.manager=true -Dtests.locale=ar-MA -Dtests.timezone=Arctic/Longyearbyen -Druntime.java=8`

**Reproduces locally?**:
Didn't reproduce for me on my macbook

**Applicable branches**:
`7.x`,`7.11` and `8.0`

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P28D&search.tags=not:nested&search.tags=mac&search.tags=ci&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests&tests.sortField=FAILED&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests > testCreateWhenResourcesNeedToBeAddedOrUpdated FAILED
    java.lang.AssertionError: 
    Expected: is <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([1FEBD07E8BC5E4CD:C7178A0E74CAA8E2]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests.lambda$createResources$1(LocalExporterResourceIntegTests.java:140)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1005)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:978)
        at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests.createResources(LocalExporterResourceIntegTests.java:140)
        at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests.createResources(LocalExporterResourceIntegTests.java:131)
        at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests.assertResourcesExist(LocalExporterResourceIntegTests.java:353)
        at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests.testCreateWhenResourcesNeedToBeAddedOrUpdated(LocalExporterResourceIntegTests.java:70)
```

**Comment by benwtrent** [comment]
Another failure:

https://gradle-enterprise.elastic.co/s/ul2vc3csgwb7w

Looking at test history, this test is definitely flaky, though ONLY for darwin :(

**Comment by BigPandaToo** [comment]
Another one: https://gradle-enterprise.elastic.co/s/l7hploizj6szk

**Comment by davidkyle** [comment]
Also fails on master: https://gradle-enterprise.elastic.co/s/qsj7ixfnpkhfi

**Comment by joegallo** [comment]
We don't run darmin/mac tests on CI anymore, so I'm closing this one.
