### ISSUE TITLE
[CI] SearchTemplateRequestTests testEqualsAndHashcode

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#68647]
**Build scan**:
https://gradle-enterprise.elastic.co/s/yyiuqbojjzygk

**Repro line**:
```
./gradlew ':modules:lang-mustache:test' --tests "org.elasticsearch.script.mustache.SearchTemplateRequestTests.testEqualsAndHashcode" \
  -Dtests.seed=14F709343A654A62 \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=Etc/GMT+10 \
  -Druntime.java=8
```

**Reproduces locally?**:
Yes

**Applicable branches**:
7.x

**Failure history**:
Rare

**Failure excerpt**:
```
java.lang.AssertionError: SearchTemplateRequest mutation should not be equal to original
Expected: not <org.elasticsearch.script.mustache.SearchTemplateRequest@136b4ddc>
     but: was <org.elasticsearch.script.mustache.SearchTemplateRequest@136b4ddc>
	at __randomizedtesting.SeedInfo.seed([14F709343A654A62:65F871F9F582034D]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.test.EqualsHashCodeTestUtils.checkEqualsAndHashCode(EqualsHashCodeTestUtils.java:71)
	at org.elasticsearch.test.AbstractWireTestCase.testEqualsAndHashcode(AbstractWireTestCase.java:49)
```

**Comment by jtibshirani** [comment]
This is the same issue as #43157 but we forgot to backport the fix to 7.x. I've backported it now and will close this out.
