### ISSUE TITLE
[CI] TokenAuthIntegTests testRefreshingMultipleTimesWithinWindowSucceeds 

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#68664]
**Build scan**:
https://gradle-enterprise.elastic.co/s/hemkzw2xylm2k

**Repro line**:
```
 ./gradlew ':x-pack:plugin:security:internalClusterTest' --tests "org.elasticsearch.xpack.security.authc.TokenAuthIntegTests.testRefreshingMultipleTimesWithinWindowSucceeds" \
  -Dtests.seed=CCB58946A74B520F \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=und \
  -Dtests.timezone=Atlantic/Faroe \
  -Druntime.java=8
```

**Reproduces locally?**:
lol

**Applicable branches**:
7.x

**Failure history**:
Very rare 

**Failure excerpt**:
```
java.util.ConcurrentModificationException
	at __randomizedtesting.SeedInfo.seed([CCB58946A74B520F:EDBBE984EA8ED27B]:0)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1390)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.LongPipeline.reduce(LongPipeline.java:439)
	at java.util.stream.LongPipeline.sum(LongPipeline.java:397)
	at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:526)
	at org.elasticsearch.xpack.security.authc.TokenAuthIntegTests.testRefreshingMultipleTimesWithinWindowSucceeds(TokenAuthIntegTests.java:626)
```

**Comment by martijnvg** [comment]
Another failure has occurred for this test: https://gradle-enterprise.elastic.co/s/kxaur4qmnhywo
This test fails rarely (3 times in the last 90 days): https://build-stats.elastic.co/goto/236c8dd3e222c098d7dbf71b5a50a258

**Comment by joegallo** [comment]
https://gradle-enterprise.elastic.co/s/n65lhlae7jafg

**Comment by benwtrent** [comment]
Here is yet another one: https://gradle-enterprise.elastic.co/s/r6tfdrenp6gik

```
org.elasticsearch.xpack.security.authc.TokenAuthIntegTests > testRefreshingMultipleTimesWithinWindowSucceeds FAILED
    java.util.ConcurrentModificationException
        at __randomizedtesting.SeedInfo.seed([B25B81D625B4A443:9355E11468712437]:0)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1390)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.LongPipeline.reduce(LongPipeline.java:461)
        at java.util.stream.LongPipeline.sum(LongPipeline.java:419)
        at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:593)
        at org.elasticsearch.xpack.security.authc.TokenAuthIntegTests.testRefreshingMultipleTimesWithinWindowSucceeds(TokenAuthIntegTests.java:626)
```

**Comment by benwtrent** [comment]
Failed again in the same day, going to mute in 7.x, 7.12, 7.13

https://gradle-enterprise.elastic.co/s/ehtgocyi5icdy
