### ISSUE TITLE
TokenBackwardsCompatibilityIT failures

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#68757]
TokenBackwardsCompatibilityIT » testGeneratingTokensInMixedCluster
TokenBackwardsCompatibilityIT » testRefreshingTokensInMixedCluster

**Build scan**: https://gradle-enterprise.elastic.co/s/7wjt3rnujlkae

**Applicable branches**: 7.x

**Failure history**:
Started once #68375 was backported to 7.x

**Failure excerpt**:

```

org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT > testGeneratingTokensInMixedCluster FAILED |  
-- | --
  | org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:38011], URI [/_security/oauth2/token], status line [HTTP/1.1 500 Internal Server Error] |  
  | {"error":{"root_cause":[{"type":"illegal_state_exception","reason":"Cannot update mappings in [.security-tokens-7]: system indices can only use mappings from their descriptors, but the mappings in the request did not match those in the descriptors(s)"}],"type":"illegal_state_exception","reason":"Cannot update mappings in [.security-tokens-7]: system indices can only use mappings from their descriptors, but the mappings in the request did not match those in the descriptors(s)"},"status":500} |  
  | at __randomizedtesting.SeedInfo.seed([4392CA99489E4B54:BCDB25AF041027C4]:0) |  
  | at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270) |  
  | at org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.createTokens(TokenBackwardsCompatibilityIT.java:397) |  
  | at org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.testGeneratingTokensInMixedCluster(TokenBackwardsCompatibilityIT.java:215) |  
  | REPRODUCE WITH: ./gradlew ':x-pack:qa:rolling-upgrade:v7.10.3#twoThirdsUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT" -Dtests.method="testGeneratingTokensInMixedCluster" -Dtests.seed=4392CA99489E4B54 -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=ja -Dtests.timezone=America/Creston -Druntime.java=8 |  
  |   |  
  | org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT > testRefreshingTokensInMixedCluster FAILED |  
  | org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:34445], URI [/_security/oauth2/token], status line [HTTP/1.1 500 Internal Server Error] |  
  | {"error":{"root_cause":[{"type":"illegal_state_exception","reason":"Cannot update mappings in [.security-tokens-7]: system indices can only use mappings from their descriptors, but the mappings in the request did not match those in the descriptors(s)"}],"type":"illegal_state_exception","reason":"Cannot update mappings in [.security-tokens-7]: system indices can only use mappings from their descriptors, but the mappings in the request did not match those in the descriptors(s)"},"status":500} |  
  | at __randomizedtesting.SeedInfo.seed([4392CA99489E4B54:A1F36B143CFB8E73]:0) |  
  | at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270) |  
  | at org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.refreshToken(TokenBackwardsCompatibilityIT.java:429) |  
  | at org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.testRefreshingTokensInMixedCluster(TokenBackwardsCompatibilityIT.java:246) |  
  | REPRODUCE WITH: ./gradlew ':x-pack:qa:rolling-upgrade:v7.10.3#twoThirdsUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT" -Dtests.method="testRefreshingTokensInMixedCluster" -Dtests.seed=4392CA99489E4B54 -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=ja -Dtests.timezone=America/Creston -Druntime.java=8

```

**Comment by ywangd** [comment]
I am closing this since #68760 should have fixed it. It didn't get auto-closed because it only works for PR on the master branch.
