### ISSUE TITLE
Can't initiate the cluster with an Active Directory auth method.

### ISSUE THREAD

**Issue by Jarzamendia** [elastic/elasticsearch#68877]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.11.0

**Plugins installed**: []

**OS version** (`uname -a` if on a Unix-like system): docker.elastic.co/elasticsearch/elasticsearch:7.11.0

**Description of the problem including expected versus actual behavior**:

The cluster won't initiate if an Active Directory authentication method is defined in configuration.

**Steps to reproduce**:

 1. Start a one node cluster with the Docker image.
 2. Use a Active Directory authentication method configuration.
 3. The cluster only start if we remove the Active Directory from elasticsearch.yml 

**Provide logs (if relevant)**:

[2021-02-11T00:29:39,714][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [elk-node-1] fatal error in thread [main], exiting
java.lang.NoClassDefFoundError: Could not initialize class com.unboundid.util.Debug
        at com.unboundid.ldap.sdk.LDAPConnectionOptions.getSystemProperty(LDAPConnectionOptions.java:2278) ~[?:?]
        at com.unboundid.ldap.sdk.LDAPConnectionOptions.<clinit>(LDAPConnectionOptions.java:213) ~[?:?]
        at org.elasticsearch.xpack.security.authc.ldap.support.SessionFactory.connectionOptions(SessionFactory.java:122) ~[?:?]
        at org.elasticsearch.xpack.security.authc.ldap.support.SessionFactory.serverSet(SessionFactory.java:203) ~[?:?]
        at org.elasticsearch.xpack.security.authc.ldap.support.SessionFactory.<init>(SessionFactory.java:81) ~[?:?]
        at org.elasticsearch.xpack.security.authc.ldap.PoolingSessionFactory.<init>(PoolingSessionFactory.java:62) ~[?:?]
        at org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactory.<init>(ActiveDirectorySessionFactory.java:68) ~[?:?]
        at org.elasticsearch.xpack.security.authc.ldap.LdapRealm.sessionFactory(LdapRealm.java:89) ~[?:?]
        at org.elasticsearch.xpack.security.authc.ldap.LdapRealm.<init>(LdapRealm.java:68) ~[?:?]
        at org.elasticsearch.xpack.security.authc.InternalRealms.lambda$getFactories$2(InternalRealms.java:113) ~[?:?]
        at org.elasticsearch.xpack.security.authc.Realms.initRealms(Realms.java:214) ~[?:?]
        at org.elasticsearch.xpack.security.authc.Realms.<init>(Realms.java:76) ~[?:?]
        at org.elasticsearch.xpack.security.Security.createComponents(Security.java:480) ~[?:?]
        at org.elasticsearch.xpack.security.Security.createComponents(Security.java:412) ~[?:?]
        at org.elasticsearch.node.Node.lambda$new$16(Node.java:560) ~[elasticsearch-7.11.0.jar:7.11.0]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at org.elasticsearch.node.Node.<init>(Node.java:564) ~[elasticsearch-7.11.0.jar:7.11.0]
        at org.elasticsearch.node.Node.<init>(Node.java:278) ~[elasticsearch-7.11.0.jar:7.11.0]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:216) ~[elasticsearch-7.11.0.jar:7.11.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:216) ~[elasticsearch-7.11.0.jar:7.11.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:387) ~[elasticsearch-7.11.0.jar:7.11.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.11.0.jar:7.11.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.11.0.jar:7.11.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75) ~[elasticsearch-7.11.0.jar:7.11.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116) ~[elasticsearch-cli-7.11.0.jar:7.11.0]
        at org.elasticsearch.cli.Command.main(Command.java:79) ~[elasticsearch-cli-7.11.0.jar:7.11.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.11.0.jar:7.11.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81) ~[elasticsearch-7.11.0.jar:7.11.0]
fatal error in thread [main], exiting
java.lang.NoClassDefFoundError: Could not initialize class com.unboundid.util.Debug
        at com.unboundid.ldap.sdk.LDAPConnectionOptions.getSystemProperty(LDAPConnectionOptions.java:2278)
        at com.unboundid.ldap.sdk.LDAPConnectionOptions.<clinit>(LDAPConnectionOptions.java:213)
        at org.elasticsearch.xpack.security.authc.ldap.support.SessionFactory.connectionOptions(SessionFactory.java:122)
        at org.elasticsearch.xpack.security.authc.ldap.support.SessionFactory.serverSet(SessionFactory.java:203)
        at org.elasticsearch.xpack.security.authc.ldap.support.SessionFactory.<init>(SessionFactory.java:81)
        at org.elasticsearch.xpack.security.authc.ldap.PoolingSessionFactory.<init>(PoolingSessionFactory.java:62)
        at org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactory.<init>(ActiveDirectorySessionFactory.java:68)
        at org.elasticsearch.xpack.security.authc.ldap.LdapRealm.sessionFactory(LdapRealm.java:89)
        at org.elasticsearch.xpack.security.authc.ldap.LdapRealm.<init>(LdapRealm.java:68)
        at org.elasticsearch.xpack.security.authc.InternalRealms.lambda$getFactories$2(InternalRealms.java:113)
        at org.elasticsearch.xpack.security.authc.Realms.initRealms(Realms.java:214)
        at org.elasticsearch.xpack.security.authc.Realms.<init>(Realms.java:76)
        at org.elasticsearch.xpack.security.Security.createComponents(Security.java:480)
        at org.elasticsearch.xpack.security.Security.createComponents(Security.java:412)
        at org.elasticsearch.node.Node.lambda$new$16(Node.java:560)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.elasticsearch.node.Node.<init>(Node.java:564)
        at org.elasticsearch.node.Node.<init>(Node.java:278)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:216)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:216)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:387)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
        at org.elasticsearch.cli.Command.main(Command.java:79)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81)

**Comment by dnhatn** [comment]
Fixed in https://github.com/elastic/elasticsearch/pull/68872.

**Comment by dnhatn** [comment]
@Jarzamendia Thank you for reporting this bug.
