### ISSUE TITLE
[CI] "mlt/20_docs/Basic mlt query with docs" failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#68908]
**Build scan**: https://gradle-enterprise.elastic.co/s/z33wzuxt5ggyc

**Repro line**: `gradlew ':qa:mixed-cluster:v7.11.1#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=mlt/20_docs/Basic mlt query with docs}" -Dtests.seed=D1DA4F611C9F9D83 -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=pl-PL -Dtests.timezone=PLT -Druntime.java=8`

**Reproduces locally?**: No

**Applicable branches**: 7.x

**Failure excerpt**:
```
1> [2021-02-11T18:47:06,250][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] [p0=mlt/20_docs/Basic mlt query with docs] before test
  2> lut 11, 2021 6:47:06 PM org.elasticsearch.client.RestClient logResponse
  2> WARNING: request [GET http://[::1]:36299/test_1/_search?rest_total_hits_as_int=true&error_trace=true] returned 1 warnings: [299 Elasticsearch-7.11.1-SNAPSHOT-ee0d2e22e6e5b61c9c0648ba6d013b2dbb916164 "[types removal] Types are deprecated in [more_like_this] queries. The type should no longer be specified in the [like] and [unlike] sections."]
  1> [2021-02-11T18:47:06,901][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "took" : 15,
  1>       "timed_out" : false,
  1>       "_shards" : {
  1>         "total" : 2,
  1>         "successful" : 2,
  1>         "skipped" : 0,
  1>         "failed" : 0
  1>       },
  1>       "hits" : {
  1>         "total" : 2,
  1>         "max_score" : 1.9616582,
  1>         "hits" : [
  1>           {
  1>             "_index" : "test_1",
  1>             "_type" : "_doc",
  1>             "_id" : "2",
  1>             "_score" : 1.9616582,
  1>             "_source" : {
  1>               "foo" : "baz"
  1>             }
  1>           },
  1>           {
  1>             "_index" : "test_1",
  1>             "_type" : "_doc",
  1>             "_id" : "3",
  1>             "_score" : 1.9616582,
  1>             "_source" : {
  1>               "foo" : "foo"
  1>             }
  1>           }
  1>         ]
  1>       }
  1>     }
  1>   }
  1> }]
  1> [2021-02-11T18:47:07,189][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] [p0=mlt/20_docs/Basic mlt query with docs] after test
  2> REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v7.11.1#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=mlt/20_docs/Basic mlt query with docs}" -Dtests.seed=D1DA4F611C9F9D83 -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=pl-PL -Dtests.timezone=PLT -Druntime.java=8
  2> java.lang.AssertionError: Failure at [mlt/20_docs:57]: hits.total didn't match expected value:
                        hits.total: expected Integer [3] but was Integer [2]
        at __randomizedtesting.SeedInfo.seed([D1DA4F611C9F9D83:598E70BBB263F07B]:0)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:450)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:427)
        at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.lang.AssertionError: hits.total didn't match expected value:
                            hits.total: expected Integer [3] but was Integer [2]
            at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:82)
            at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
            at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:443)
            ... 37 more
```

**Comment by dnhatn** [comment]
This test hasn't failed recently, and we no longer have the cluster logs to investigate.
