### ISSUE TITLE
MSI Installation is broken on Windows in 7.11.0

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#68914]
MSI installation with all defaults fails with the following error in the logs:

```
Service cannot be started. Elastic.ProcessHosts.Process.StartupException: Could not evaluate jvm.options file. result: Exception in thread "main" java.lang.IllegalArgumentException: Expected two arguments specifying path to ES_PATH_CONF and plugins directory, but was [C:\ProgramData\Elastic\Elasticsearch\config]
at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:72)

   at Elastic.ProcessHosts.Elasticsearch.Process.ElasticsearchProcess.CreateObservableProcessArguments(IEnumerable`1 args)
   at Elastic.ProcessHosts.Elasticsearch.Process.ElasticsearchProcess..ctor(IObservableProcess process, IConsoleOutHandler consoleOutHandler, IFileSystem fileSystem, ElasticsearchEnvironmentConfiguration env, JavaConfiguration java, IElasticsearchTool jvmOptionsParser, IElasticsearchTool javaVersionChecker, ManualResetEvent completedHandle, IEnumerable`1 args)
   at Elastic.ProcessHosts.Elasticsearch.Process.ElasticsearchProcess..ctor(ManualResetEvent completedHandle, IEnumerable`1 args)
   at Elastic.ProcessHost...
```
To reproduce, download MSI and click Next without changing any settings. I was able to reproduce on Windows 10. Was initially [reported by a user on our forum](https://discuss.elastic.co/t/7-11-expected-two-arguments-specifying-path-to-es-path-conf-and-plugins-directory/263986) on Windows 2016.

**Comment by plancked** [comment]
Same here. Windows 2019.

**Comment by ygel** [comment]
Thank you for reporting, we're investigating.
https://github.com/elastic/windows-installers/issues/401
https://github.com/elastic/windows-installers/issues/402

**Comment by JD-Media** [comment]
also having the same issue
Server 2016
Upgrading from 7.9.2 to 7.11.0
Error occurs when starting from windows services gui or running the exe directly

**Comment by pugnascotia** [comment]
Fixed in https://github.com/elastic/windows-installers/issues/402
