### ISSUE TITLE
Searchable snapshot support for http repos

### ISSUE THREAD

**Issue by graphaelli** [elastic/elasticsearch#68918]
Snapshots repositories of type `url` can be mounted but not actually used as searchable snapshots because of (per @DaveCTurner):

```
Caused by: java.lang.UnsupportedOperationException
        at org.elasticsearch.common.blobstore.url.URLBlobContainer.readBlob(URLBlobContainer.java:115) ~[?:?]
        at org.elasticsearch.common.blobstore.support.FilterBlobContainer.readBlob(FilterBlobContainer.java:50) ~[elasticsearch-7.11.0.jar:7.11.0]
        at org.elasticsearch.index.store.SearchableSnapshotDirectory$RateLimitingBlobContainer.readBlob(SearchableSnapshotDirectory.java:665) ~[?:?]
        at org.elasticsearch.index.store.cache.CachedBlobContainerIndexInput.openInputStreamFromBlobStore(CachedBlobContainerIndexInput.java:638) ~[?:?]
        at org.elasticsearch.index.store.cache.CachedBlobContainerIndexInput.writeCacheFile(CachedBlobContainerIndexInput.java:607) ~[?:?]
        at org.elasticsearch.index.store.cache.CacheFile$2.doRun(CacheFile.java:374) ~[?:?]
        ... 5 more
```

This is a request to implement support for this.  A note that this is currently unsupported is also in order.

**Comment by DaveCTurner** [comment]
Closed by #69521
