### ISSUE TITLE
Retrieving a field with null value triggers a NPE

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#68979]
Indexing the following document:
```
{
    "a": {"b": 0},
    "a.b": null
}
```
and retrieving it with:
```
{
    "fields": [
        {
            "field": "a.b"
        }
    ]
}
```
will fail due to:
```
Caused by: java.lang.NullPointerException
        at java.util.ArrayDeque.addLast(ArrayDeque.java:303) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at java.util.ArrayDeque.copyElements(ArrayDeque.java:329) ~[?:?]
        at java.util.ArrayDeque.addAll(ArrayDeque.java:324) ~[?:?]
        at org.elasticsearch.index.mapper.SourceValueFetcher.fetchValues(SourceValueFetcher.java:67) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.fetch.subphase.FieldFetcher.fetch(FieldFetcher.java:144) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.fetch.subphase.FetchFieldsPhase$1.process(FetchFieldsPhase.java:57) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:146) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:461) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:437) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:395) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        ... 6 more
```

(Simply stripping the `null`s [before enqueuing](https://github.com/elastic/elasticsearch/blob/947f1ebb3599bef96a285e3c871b365b823450fe/server/src/main/java/org/elasticsearch/index/mapper/SourceValueFetcher.java#L67) the values seems to fix it.)

**Comment by astefan** [comment]
CC @jtibshirani
