### ISSUE TITLE
`pre_tags` and `post_tags` params not validated for empty values

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#69009]
`pre_tags` and `post_tags` query parameters for highlighting are not validated of empty values.
As a result if a query sets them to an empty array we get an ArrayOutOfBoundsException:

```
{
  "query" : {
    "match" : {
      "field1" : "fox"}
    }, 
    "highlight" : {
      "type" : "plain",
      "fields" : {
        "field1" : {}
      },
      "pre_tags": ["<tag1>"],
      "post_tags" : []
    }
}
```

results in:

```
...
"caused_by" : {
           "type" : "array_index_out_of_bounds_exception",
           "reason" : "Index 0 out of bounds for length 0",
           "caused_by" : {
             "type" : "array_index_out_of_bounds_exception",
             "reason" : "Index 0 out of bounds for length 0",
             "stack_trace" : "java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
    at org.elasticsearch.search.fetch.subphase.highlight.PlainHighlighter.highlight(PlainHighlighter.java:79)
    at org.elasticsearch.search.fetch.subphase.highlight.HighlightPhase$1.process(HighlightPhase.java:64)
    at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:146)
    at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:461)
    at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:437)
    at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:395)
    at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47)
    at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservin gAbstractRunnable.doRun(ThreadContext.java:728)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    at java.base/java.lang.Thread.run(Thread.java:832)

...

**Comment by mfrandev** [comment]
Hi, I would like to work on this issue. Can someone please assign ?

**Comment by mayya-sharipova** [comment]
@mfrandev Thank you for your interest. We don't assign external contributors to the issues. We review a first PR submitted to address the issue. For this issue there was already a PR submitted, but let's see if they wanted to continue to refine it.
