### ISSUE TITLE
[CI] Build composeDown task fails with error while removing network

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#69045]
**Build scan**: https://gradle-enterprise.elastic.co/s/jp4kf47mfwagq

**Repro line**: `./gradlew :test:fixtures:s3-fixture:composeDown

**Reproduces locally?**: No

**Applicable branches**: `7.x`

**Failure history**:

**Failure excerpt**:

```
Caused by: java.lang.RuntimeException: Exit-code 1 when calling /usr/local/bin/docker-compose, stdout: N/A
13:39:27 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
13:39:27 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
13:39:27 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
13:39:27 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
13:39:27 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
13:39:27 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
13:39:27 	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
13:39:27 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
13:39:27 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
13:39:27 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
13:39:27 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
13:39:27 	at com.avast.gradle.dockercompose.ComposeExecutor.executeWithCustomOutput(ComposeExecutor.groovy:60)
13:39:27 	at com.avast.gradle.dockercompose.ComposeExecutor$executeWithCustomOutput$0.callCurrent(Unknown Source)
13:39:27 	at com.avast.gradle.dockercompose.ComposeExecutor.executeWithCustomOutputWithExitValue(ComposeExecutor.groovy:24)
13:39:27 	at com.avast.gradle.dockercompose.ComposeExecutor$executeWithCustomOutputWithExitValue.call(Unknown Source)
13:39:27 	at com.avast.gradle.dockercompose.tasks.ComposeDownForced.down(ComposeDownForced.groovy:57)
13:39:27 	at com.avast.gradle.dockercompose.tasks.ComposeDown.down(ComposeDown.groovy:16)
```

**Comment by mark-vieira** [comment]
I've seen this a few times now, here's the relevant error reported by `docker-compose`:

```
error while removing network: network 27412d02ee126b6aad7dececd269c164_s3-fixture__default id e9622139db28a8de4a642a0b9d1f5e6cf58b2a0348908da7eaf40eb9074fc717 has active endpoints
```

I'm not sure what kind of weird race condition there might be here, but given our workers are ephemeral, and we'll never restart a stopped fixture, I'm inclined to say we should "ignore" these somehow.

**Comment by jakelandis** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/pbm5nxee4chew

**Comment by benwtrent** [comment]
Here is another: https://gradle-enterprise.elastic.co/s/5phgivlk5z7mu

**Comment by ywangd** [comment]
Another one: https://gradle-enterprise.elastic.co/s/izlyxnzbt2csi/console-log#L20664

**Comment by mark-vieira** [comment]
We are refactoring the build to remove all usages of Docker compose. Closing this issue.
