### ISSUE TITLE
FsSnapshotRepoTestKitIT#testRepositoryAnalysis can fail with repository_verification_exception

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#69087]
**Build scan**: https://gradle-enterprise.elastic.co/s/7sc5twij3b5bc

**Repro line**:
```
./gradlew ':x-pack:plugin:snapshot-repo-test-kit:qa:rest:integTest' --tests "org.elasticsearch.repositories.blobstore.testkit.rest.FsSnapshotRepoTestKitIT.testRepositoryAnalysis" -Dtests.seed=9A24749B69423ACF -Dtests.security.manager=true -Dtests.locale=ca -Dtests.timezone=Etc/GMT-10 -Druntime.java=11
```

**Reproduces locally?**: no

**Applicable branches**: master, maybe 7.x

**Failure history**: the test was introduced recently in https://github.com/elastic/elasticsearch/pull/67247

**Failure excerpt**:
```
{"error":{"root_cause":[{"type":"repository_verification_exception","reason":"[repository] [GetRepositoryBlobChecksumRequest{retrieve [176717-217691] from [repository:temp-analysis-gmWa_cs7QsqcfbeTcNSV0Q/test-blob-6-riacINAwRK6-fjhy0-wb3w]}] (after write complete) failed on node [{integTest-0}{uflyZK1jTICL2L5Ki5ZpcA}{DWnV16kqRXCSJm3OfzQ2xg}{127.0.0.1}{127.0.0.1:43743}{cdfhilmrstw}{ml.machine_memory=101362774016, xpack.installed=true, transform.node=true, testattr=test, ml.max_open_jobs=20, ml.max_jvm_size=518979584}]: blob not found"}],"type":"repository_verification_exception","reason":"[repository] analysis failed, you may need to manually remove [temp-analysis-gmWa_cs7QsqcfbeTcNSV0Q]","caused_by":{"type":"repository_verification_exception","reason":"[repository] failure processing [blob analysis [repository:temp-analysis-gmWa_cs7QsqcfbeTcNSV0Q/test-blob-6-riacINAwRK6-fjhy0-wb3w, length=262144, seed=5958866466975255369, readEarly=false, writeAndOverwrite=true]]","caused_by":{"type":"repository_verification_exception","reason":"[repository] [GetRepositoryBlobChecksumRequest{retrieve [176717-217691] from [repository:temp-analysis-gmWa_cs7QsqcfbeTcNSV0Q/test-blob-6-riacINAwRK6-fjhy0-wb3w]}] (after write complete) failed on node [{integTest-0}{uflyZK1jTICL2L5Ki5ZpcA}{DWnV16kqRXCSJm3OfzQ2xg}{127.0.0.1}{127.0.0.1:43743}{cdfhilmrstw}{ml.machine_memory=101362774016, xpack.installed=true, transform.node=true, testattr=test, ml.max_open_jobs=20, ml.max_jvm_size=518979584}]: blob not found"}}},"status":500} |  
-- | --
  | at __randomizedtesting.SeedInfo.seed([9A24749B69423ACF:6319D5F5B7D90926]:0) |  
  | at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:330) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270) |  
  | at org.elasticsearch.repositories.blobstore.testkit.AbstractSnapshotRepoTestKitRestTestCase.testRepositoryAnalysis(AbstractSnapshotRepoTestKitRestTestCase.java:34) |  
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) |  
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

**Comment by jtibshirani** [comment]
I muted fairly aggressively, disabling `AbstractSnapshotRepoTestKitRestTestCase#testRepositoryAnalysis`:
* a7c5c2e0ea82d2b35960b5ce4763bdd76d486ff1 (master)
* 568906116ac1a76847cc7676235ab18a48f2c81b (7.x)

**Comment by DaveCTurner** [comment]
Thanks @jtibshirani, I've also seen one of the YAML REST tests failing similarly, however we need to understand why and I haven't been able to reproduce this locally (in thousands of test iterations) so I'd like to leave some of these failing tests running in CI with the additional logging introduced in #69098 for now.
