### ISSUE TITLE
Deadlock in get-snapshots API

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#69099]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.11.0

**Plugins installed**: Cloud

**JVM version** (`java -version`): Cloud

**OS version** (`uname -a` if on a Unix-like system): Cloud

**Description of the problem including expected versus actual behavior**:

A cluster was observed with all generic threads waiting here:

```
"elasticsearch[instance-0000000071][generic][T#1]" #33 daemon prio=5 os_prio=0 cpu=5894.11ms elapsed=559821.30s tid=0x00007f0af0746950 nid=0x1dc waiting on condition  [0x00007f0aef5f8000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@15.0.1/Native Method)
	- parking to wait for  <0x00000006d6607c20> (a org.elasticsearch.common.util.concurrent.BaseFuture$Sync)
	at java.util.concurrent.locks.LockSupport.park(java.base@15.0.1/LockSupport.java:211)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@15.0.1/AbstractQueuedSynchronizer.java:714)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@15.0.1/AbstractQueuedSynchronizer.java:1046)
	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:248)
	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:76)
	at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:45)
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:26)
	at org.elasticsearch.action.support.PlainActionFuture.get(PlainActionFuture.java:22)
	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:90)
	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:54)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:88)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$3(TransportMasterNodeAction.java:155)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$$Lambda$5714/0x0000000801b184c8.accept(Unknown Source)
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@15.0.1/ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@15.0.1/ThreadPoolExecutor.java:630)
	at java.lang.Thread.run(java.base@15.0.1/Thread.java:832)
```

These threads are all waiting to retrieve the repository data, which itself needs generic threads, but there are no more generic threads available.

**Steps to reproduce**:

I have not tried, but I guess that you could reproduce this by hitting the get-snapshots API hard enough, especially if there are lots of old snapshots in the repository so retrieving the `RepositoryData` happens every time and is slow enough.

I suspect this was introduced in https://github.com/elastic/elasticsearch/commit/1cde4a6364ce26ab38c99d2bc08aa4a1d4ce3be6, so might affect all 7.x.y for x ≥ 6, but apparently not 8.z.

**Comment by original-brownbear** [comment]
closed via #69101

**Comment by sagarrohankar-bsft** [comment]
We are facing the same issue, @original-brownbear may I know in which ES version the fix is available:

**Comment by original-brownbear** [comment]
@sagarrohankar-bsft see fixing PR https://github.com/elastic/elasticsearch/pull/69101 labels, it went into `7.11.2` and newer
