### ISSUE TITLE
RepositoryAnalysisSuccessIT#testRepositoryAnalysis can fail with IllegalArgumentException

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#69219]
**Build scan**: https://gradle-enterprise.elastic.co/s/76fmova7kmjo6

**Repro line**:
```
./gradlew ':x-pack:plugin:snapshot-repo-test-kit:internalClusterTest' --tests "org.elasticsearch.repositories.blobstore.testkit.RepositoryAnalysisSuccessIT.testRepositoryAnalysis" -Dtests.seed=51EC773179C2146D -Dtests.security.manager=true -Dtests.locale=ar-DZ -Dtests.timezone=Australia/South -Druntime.java=11
```

**Reproduces locally?**: yes

**Applicable branches**: master, maybe 7.x

**Failure history**:  the test was introduced recently in #67247

**Failure excerpt**:
```
org.elasticsearch.repositories.blobstore.testkit.RepositoryAnalysisSuccessIT > testRepositoryAnalysis FAILED
    java.lang.IllegalArgumentException: cannot satisfy max total bytes [1755B/1.7kb]: must write at least one byte per blob and at least one max-sized blob which is [1849B] in total
        at __randomizedtesting.SeedInfo.seed([51EC773179C2146D:A8D1D65FA7592784]:0)
        at org.elasticsearch.repositories.blobstore.testkit.RepositoryAnalyzeAction.getBlobSizes(RepositoryAnalyzeAction.java:208)
        at org.elasticsearch.repositories.blobstore.testkit.RepositoryAnalyzeAction$AsyncAction.run(RepositoryAnalyzeAction.java:450)
        at org.elasticsearch.repositories.blobstore.testkit.RepositoryAnalyzeAction$TransportAction.doExecute(RepositoryAnalyzeAction.java:136)
        at org.elasticsearch.repositories.blobstore.testkit.RepositoryAnalyzeAction$TransportAction.doExecute(RepositoryAnalyzeAction.java:91)
```

**Comment by jtibshirani** [comment]
I muted the test in master (7a0c379c90ea602d9c572dbac7e5d8628c0ee2e6) and 7.x (97389a50506497b426be6094f192da04e37c2c49).
