### ISSUE TITLE
SQL: fail to aggregate within aliased subquery

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#69263]
The following two queries work as expected:
* `SELECT * FROM (SELECT author FROM library GROUP BY author)` and 
* `SELECT * FROM (SELECT author FROM library) AS subquery`.

However, when aliasing the subquery with agg,
* `SELECT * FROM (SELECT author FROM library GROUP BY author) AS subquery`, 
 
the following exception triggers:

```
org.elasticsearch.xpack.sql.SqlIllegalArgumentException: Cannot find group [author]
	at org.elasticsearch.xpack.sql.util.Check.notNull(Check.java:37)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.fold(QueryFolder.java:604)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:414)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:226)
	at org.elasticsearch.xpack.ql.tree.Node.lambda$transformUp$11(Node.java:198)
	at org.elasticsearch.xpack.ql.tree.Node.transformUp(Node.java:192)
	at org.elasticsearch.xpack.ql.tree.Node.transformUp(Node.java:198)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:877)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:873)
	at org.elasticsearch.xpack.ql.rule.RuleExecutor$Transformation.<init>(RuleExecutor.java:83)
	at org.elasticsearch.xpack.ql.rule.RuleExecutor.executeWithInfo(RuleExecutor.java:159)
	at org.elasticsearch.xpack.ql.rule.RuleExecutor.execute(RuleExecutor.java:131)
	at org.elasticsearch.xpack.sql.planner.QueryFolder.fold(QueryFolder.java:112)
	at org.elasticsearch.xpack.sql.planner.Planner.foldPlan(Planner.java:39)
	at org.elasticsearch.xpack.sql.planner.Planner.plan(Planner.java:29)
	at org.elasticsearch.xpack.sql.session.SqlSession.lambda$physicalPlan$4(SqlSession.java:161)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:117)
	at org.elasticsearch.xpack.sql.session.SqlSession.lambda$optimizedPlan$3(SqlSession.java:157)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:117)
	at org.elasticsearch.xpack.sql.session.SqlSession.lambda$preAnalyze$2(SqlSession.java:145)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:117)
	at org.elasticsearch.xpack.ql.index.IndexResolver.lambda$resolveAsMergedMapping$4(IndexResolver.java:299)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:117)
	at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:100)
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:170)
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:164)
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$2(SecurityActionFilter.java:165)
	at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:167)
	at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.lambda$doExecute$0(TransportFieldCapabilitiesAction.java:78)
	at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:93)
	at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:87)
	at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:100)
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:170)
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:164)
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$2(SecurityActionFilter.java:165)
	at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:167)
	at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesIndexAction$AsyncShardsAction$1.handleResponse(TransportFieldCapabilitiesIndexAction.java:283)
	at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesIndexAction$AsyncShardsAction$1.handleResponse(TransportFieldCapabilitiesIndexAction.java:273)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1165)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1243)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1223)
	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:41)
	at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:32)
	at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:16)
	at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47)
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:728)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)


```

**Comment by matriv** [comment]
`master` : https://github.com/elastic/elasticsearch/commit/1a2a3df78bdb4551367fa229564d3a489f6a3946
`7.x` : https://github.com/elastic/elasticsearch/commit/3abfe79a4ee76bb7a05ae9c51fa3472f04479969
`7.13` : https://github.com/elastic/elasticsearch/commit/5e58bd2b18a185e90736a78645c8bce5f916330b
`7.12` : https://github.com/elastic/elasticsearch/commit/862f0387602b0f10978f49c1b88034c164f6ea86
