### ISSUE TITLE
[CI] AsyncSearchActionIT.testRemoveAsyncIndex failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#69313]
This has failed a few times in the past week.

**Build scan**:
https://gradle-enterprise.elastic.co/s/z5bgg7uul7rdg/tests/:x-pack:plugin:async-search:internalClusterTest/org.elasticsearch.xpack.search.AsyncSearchActionIT/testRemoveAsyncIndex#1

**Repro line**:
`./gradlew ':x-pack:plugin:async-search:internalClusterTest' --tests "org.elasticsearch.xpack.search.AsyncSearchActionIT.testRemoveAsyncIndex" -Dtests.seed=984425C72759CF1D -Dtests.security.manager=true -Dtests.locale=es-PE -Dtests.timezone=Asia/Saigon -Druntime.java=11`

**Reproduces locally?**:
nope

**Applicable branches**:
`master`

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.xpack.search.AsyncSearchActionIT&tests.disabledDistributions=WyJvdXRjb21lOnBhc3NlZCIsIm91dGNvbWU6c2tpcHBlZCJd&tests.sortField=FAILED&tests.test=testRemoveAsyncIndex&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.xpack.search.AsyncSearchActionIT > testRemoveAsyncIndex FAILED
    java.lang.AssertionError: 
    Expected: a value less than <1613776593241L>
         but: <1613776593765L> was greater than <1613776593241L>
        at __randomizedtesting.SeedInfo.seed([984425C72759CF1D:76158CAC50B6AE1D]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.search.AsyncSearchActionIT.testRemoveAsyncIndex(AsyncSearchActionIT.java:444)
```

**Comment by mark-vieira** [comment]
@jimczi Looks like you recently added the assertion the test is complaining about. Do you mind investigating?
