### ISSUE TITLE
Unassigned replica shards after node startup

### ISSUE THREAD

**Issue by binoyaf** [elastic/elasticsearch#6931]
I've had an issue during recovery of shards after node startup in a two node cluster. Both nodes are defined as master, data, and the cluster has 4 indexes with 1 shard and 1 replica each.

I get the issue with these steps-
1. Bring node-1 up (master)
2. Bring node-2 up. At this point, both primary and replicas are allocated.
3. Bring node-1 down. Node-2 gets elected as the master. The 4 replica shards (of each index) is now unassigned.
4. Bring node-1 up. At this point, a couple of the replica shards (randomly belonging to any of the 4 indexes) remain unassigned.

Both servers are running elasticsearch-1.0.0 embedded and use Oracle JRE 1.6.0_26. I have a custom analyzer plugin defined.

```
Node-2 JVM
RecoverySource.recover(StartRecoveryRequest)
- throws DelayRecoveryException("source node does not have the shard listed in its state as allocated on the node")

MessageChannelHandler
- transportChannel.sendResponse(e)
```
```
Node-1 JVM
In response to the sendResponse call on Node-VM,
- Message not fully read (response) for [23] handler future(org.elasticsearch.indices.recovery.RecoveryTarget$4@59df9cf4), error [true], resetting
and then from RecoveryTarget.doRecovery
- java.util.concurrent.ExecutionException: org.elasticsearch.transport.RemoteTransportException: Failed to deserialize exception response from stream
```
Now, without the analyzer plugin it works fine- even though the plugin itself did not throw any exceptions. The issue was because I had a custom classloader set in Settings on node initialization, but this was later overwritten to null by PluginService.updatedSettings during plugin initialization. I have changed the code in PluginService.updatedSettings to-
```
    public Settings updatedSettings() {
        ImmutableSettings.Builder builder = ImmutableSettings.settingsBuilder()
                .put(this.settings);
        for (Tuple<PluginInfo, Plugin> plugin : plugins) {
            builder.put(plugin.v2().additionalSettings().getAsMap());
        }
        return builder.build();
    }
```
This overloaded version does not set the classloader variable (assuming that plugin's don't need to set classloader on Settings).

All tests ran fine with the change. I couldn't find a similar fix in the latest version, do let me know if I should submit a pull request.

Exception trace for reference:
```
[2763cc060c8d75d85dbb357f5e220d8c] Message not fully read (response) for [80] handler future(org.elasticsearch.indices.recovery.RecoveryTarget$4@5445c50d), error [true], resetting
[2763cc060c8d75d85dbb357f5e220d8c] [data][0] failed to start shard

org.elasticsearch.indices.recovery.RecoveryFailedException: [data][0]: Recovery failed from [ca6450277735991d8085f84de36d6ecd][wfO9NNewTHuFdNRPhiE7og][MYHOST][inet[/10.225.115.166:9301]]{master=true} into [2763cc060c8d75d85dbb357f5e220d8c][agXTk8sKQKeMnHtspaWBNw][MYHOST][inet[/10.225.115.166:9300]]{master=true}
    at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:303)
    at org.elasticsearch.indices.recovery.RecoveryTarget.access$300(RecoveryTarget.java:65)
    at org.elasticsearch.indices.recovery.RecoveryTarget$2.run(RecoveryTarget.java:171)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
Caused by: org.elasticsearch.transport.TransportSerializationException: Failed to deserialize exception response from stream
    at org.elasticsearch.transport.netty.MessageChannelHandler.handlerResponseError(MessageChannelHandler.java:169)
    at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:123)
    at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
    at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
Caused by: java.io.InvalidClassException: failed to read class descriptor
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1566)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1495)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1731)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1328)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:350)
    at org.elasticsearch.transport.netty.MessageChannelHandler.handlerResponseError(MessageChannelHandler.java:167)
    ... 23 more
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.transport.RemoteTransportException
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1680)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1526)
    at org.elasticsearch.common.io.ThrowableObjectInputStream.loadClass(ThrowableObjectInputStream.java:93)
    at org.elasticsearch.common.io.ThrowableObjectInputStream.readClassDescriptor(ThrowableObjectInputStream.java:67)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1564)
    ... 28 more
[2763cc060c8d75d85dbb357f5e220d8c] [data][0] state: [RECOVERING]->[CLOSED], reason [recovery failure [RecoveryFailedException[[data][0]: Recovery failed from [ca6450277735991d8085f84de36d6ecd][wfO9NNewTHuFdNRPhiE7og][MYHOST][inet[/10.225.115.166:9301]]{master=true} into [2763cc060c8d75d85dbb357f5e220d8c][agXTk8sKQKeMnHtspaWBNw][MYHOST][inet[/10.225.115.166:9300]]{master=true}]; nested: RemoteTransportException[Failed to deserialize exception response from stream]; nested: TransportSerializationException[Failed to deserialize exception response from stream]; nested: InvalidClassException[failed to read class descriptor]; nested: ClassNotFoundException[org.elasticsearch.transport.RemoteTransportException]; ]]
```

**Comment by clintongormley** [comment]
We no longer use Java serialization for exceptions. Closing
