### ISSUE TITLE
RollupActionSingleNodeTests.testTemporaryIndexDeletedOnRollupFailure

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#69506]
**Build scan**:
https://gradle-enterprise.elastic.co/s/naqu7x7qvcw6q

**Repro line**:
> ./gradlew ':x-pack:plugin:rollup:test' --tests "org.elasticsearch.xpack.rollup.v2.RollupActionSingleNodeTests.testTemporaryIndexDeletedOnRollupFailure" -Dtests.seed=609D1DD31C78D15E -Dtests.security.manager=true -Dtests.locale=nn-NO -Dtests.timezone=Asia/Bahrain -Druntime.java=11

**Reproduces locally?**:
No

**Applicable branches**:
master

**Failure history**:
Only [once in past 30 days](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testTemporaryIndexDeletedOnRollupFailure),sort:!(process.time-start,desc))). So it could be transient. 

**Failure excerpt**:
```
java.lang.AssertionError: test leaves indices that were not deleted: jzklrm |  
-- | --
  | Expected: [] |  
  | but: was ["jzklrm"]
```

**Comment by benwtrent** [comment]
Happened again here: https://gradle-enterprise.elastic.co/s/tjlhzegcbs5um

```
java.lang.AssertionError: test leaves indices that were not deleted: ezolfv |  
-- | --
  | Expected: [] |  
  | but: was ["ezolfv"]
```

I bet there is some assert busy that needs to be added to the test as this is probably done asynchronously some where.

Did not reproduce locally.

**Comment by benwtrent** [comment]
This is a different test, but it is the same failure, most likely related:

reproduce:
```
./gradlew ':x-pack:plugin:rollup:test' --tests "org.elasticsearch.xpack.rollup.v2.RollupActionSingleNodeTests.testRollupShardIndexerCleansTempFiles" -Dtests.seed=DFDFD61694502742 -Dtests.security.manager=true -Dtests.locale=en-CA -Dtests.timezone=Brazil/DeNoronha -Druntime.java=11
```

https://gradle-enterprise.elastic.co/s/4x4gsnvprwl5m

```
org.elasticsearch.xpack.rollup.v2.RollupActionSingleNodeTests > testRollupShardIndexerCleansTempFiles FAILED |  
-- | --
  | java.lang.AssertionError: test leaves indices that were not deleted: obgtxw |  
  | Expected: [] |  
  | but: was ["obgtxw"] |  
  | at __randomizedtesting.SeedInfo.seed([DFDFD61694502742:7F5F5CD56BCD71A9]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.elasticsearch.test.ESSingleNodeTestCase.tearDown(ESSingleNodeTestCase.java:134) |  
  | at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) |  
  | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) |  
  | at java.base/java.lang.reflect.Method.invoke(Method.java:566) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49) |  
  | at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) |  
  | at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48) |  
  | at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) |  
  | at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902) |  
  | at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41) |  
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53) |  
  | at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) |  
  | at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) |  
  | at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831) |  
  | at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by DaveCTurner** [comment]
https://gradle-enterprise.elastic.co/s/ekmkp65j72hgs likewise

**Comment by DaveCTurner** [comment]
I muted `testRollupShardIndexerCleansTempFiles` in `master`, `7.x` and `7.12`.

**Comment by talevy** [comment]
hi all. thank you for the mute. sorry for the noise! I was out of office yesterday.

**Comment by talevy** [comment]
Closed because I unmuted tests to debug. also this test was removed. This issue is superseded by #70519.
