### ISSUE TITLE
[CI] Failure in WildcardFieldMapperTests#testSearchResultsVersusKeywordField

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#69600]
**Repro line**:
```
./gradlew ':x-pack:plugin:wildcard:test' --tests "org.elasticsearch.xpack.wildcard.mapper.WildcardFieldMapperTests.testSearchResultsVersusKeywordField" -Dtests.seed=DCE54AED6DA89445 -Dtests.security.manager=true -Dtests.locale=es-CO -Dtests.timezone=Asia/Harbin -Druntime.java=11
```

**Reproduces locally?**: Yes

**Applicable branches**: master, 7.x

**Failure excerpt**:
```
2> java.lang.AssertionError: keyword_field:/(a.*|doesnotexist)/
    DocValuesFieldExistsQuery [field=wildcard_field]
    Expected: <43L>
         but: was <98L>
        at __randomizedtesting.SeedInfo.seed([DCE54AED6DA89445:58D36CDE6F9B372]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.xpack.wildcard.mapper.WildcardFieldMapperTests.testSearchResultsVersusKeywordField(WildcardFieldMapperTests.java:352)
```

**Comment by markharwood** [comment]
I hit the bug behind this in this PR https://github.com/elastic/elasticsearch/pull/70452

That PR contains the fix - I just ran the repro line before and after to make sure. Will close this when the PR is merged

**Comment by markharwood** [comment]
Fixed in https://github.com/elastic/elasticsearch/commit/2f9c7318c288f4e24b391e28724b53073e63d284
