### ISSUE TITLE
DataStreamsUpgradeIT test failure due to day change (and other index name conflicts)

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#69689]
**Build scan**:

https://gradle-enterprise.elastic.co/s/t6szh3wjtaesi
https://gradle-enterprise.elastic.co/s/lq5qosiur4nc6
https://gradle-enterprise.elastic.co/s/gmrqcen5hlfnk
https://gradle-enterprise.elastic.co/s/qgsl232pkdcsq
https://gradle-enterprise.elastic.co/s/dnrdmjmictegk
https://gradle-enterprise.elastic.co/s/xlf5qc7f7qusw
https://gradle-enterprise.elastic.co/s/fd2dp6p2naycw

**Repro line**:
just one of the many
```
./gradlew ':x-pack:qa:rolling-upgrade:v7.9.2#oldClusterTest' -Dtests.class="org.elasticsearch.upgrades.DataStreamsUpgradeIT" -Dtests.method="testDataStreams" -Dtests.seed=7BC94CAD606533CD -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=es-ES -Dtests.timezone=Asia/Jayapura -Druntime.java=8
```
**Reproduces locally?**:
No
**Applicable branches**:
7.11 (maybe more)

**Failure excerpt**:

```
org.elasticsearch.upgrades.DataStreamsUpgradeIT > testDataStreams FAILED |  
-- | --
  | org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:40362], URI [/logs-foobar-2021.01.13/_rollover], status line [HTTP/1.1 500 Internal Server Error] |  
  | {"error":{"root_cause":[{"type":"illegal_state_exception","reason":"data stream [logs-foobar] could create backing indices that conflict with 1 existing index(s) or alias(s) including '.ds-logs-foobar-2021.01.13-000002'"}],"type":"illegal_state_exception","reason":"data stream [logs-foobar] could create backing indices that conflict with 1 existing index(s) or alias(s) including '.ds-logs-foobar-2021.01.13-000002'"},"status":500} |  
  | at __randomizedtesting.SeedInfo.seed([7BC94CAD606533CD:3D6DD54119255E23]:0) |  
  | at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270) |  
  | at org.elasticsearch.upgrades.DataStreamsUpgradeIT.testDataStreams(DataStreamsUpgradeIT.java:65)
```

Looking at the log timestamps, this test ran right at midnight. So, I am guessing since the indices are named by DAY, that is the source of the problem.

Since this is a rare occurrence, leaving unmuted. If the tests prove to fail during a time other than midnight, we should mute.

**Comment by benwtrent** [comment]
There were a flood of other failures but not due to a day change:

https://gradle-enterprise.elastic.co/s/gh6iexyulmkpu
https://gradle-enterprise.elastic.co/s/o7qds7o2hvof4
https://gradle-enterprise.elastic.co/s/ieoood46pclwm
https://gradle-enterprise.elastic.co/s/jz2v7gqxucbye

trace:
```

org.elasticsearch.upgrades.DataStreamsUpgradeIT > testDataStreams FAILED |  
-- | --
  | org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:38466], URI [/logs-foobar-2021.01.13/_rollover], status line [HTTP/1.1 500 Internal Server Error] |  
  | {"error":{"root_cause":[{"type":"illegal_state_exception","reason":"data stream [logs-foobar] could create backing indices that conflict with 1 existing index(s) or alias(s) including '.ds-logs-foobar-2021.01.13-000002'"}],"type":"illegal_state_exception","reason":"data stream [logs-foobar] could create backing indices that conflict with 1 existing index(s) or alias(s) including '.ds-logs-foobar-2021.01.13-000002'"},"status":500} |  
  | at __randomizedtesting.SeedInfo.seed([6DFB9EE6638AA5A2:2B5F070A1ACAC84C]:0) |  
  | at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270) |  
  | at org.elasticsearch.upgrades.DataStreamsUpgradeIT.testDataStreams(DataStreamsUpgradeIT.java:65)


```

**Comment by martijnvg** [comment]
I will mute this test in 7.x, 7.12 and 7.11 and work on a test fix.
