### ISSUE TITLE
RollupActionSingleNodeTests.testHistogramGrouping test failure

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#69733]
**Build scan**:
https://gradle-enterprise.elastic.co/s/m6ia7rfobjfea
**Repro line**:
```
./gradlew ':x-pack:plugin:rollup:test' --tests "org.elasticsearch.xpack.rollup.v2.RollupActionSingleNodeTests.testHistogramGrouping" -Dtests.seed=280F7E8889D1C61D -Dtests.security.manager=true -Dtests.locale=sk -Dtests.timezone=Pacific/Johnston -Druntime.java=8
```
**Reproduces locally?**:
no
**Applicable branches**:
7.12
**Failure history**:
first failure in the last 30 days
**Failure excerpt**:

```
org.elasticsearch.xpack.rollup.v2.RollupActionSingleNodeTests > testHistogramGrouping FAILED |  
-- | --
  | [.rolluptmp-gdskvg/JCBO72B1S_qHuVsYsH-ROg] IndexNotFoundException[no such index [.rolluptmp-gdskvg]] |  
  | at __randomizedtesting.SeedInfo.seed([280F7E8889D1C61D:514D2FB939734D0F]:0) |  
  | at org.elasticsearch.cluster.metadata.Metadata.getIndexSafe(Metadata.java:719) |  
  | at org.elasticsearch.cluster.metadata.MetadataDeleteIndexService.deleteIndices(MetadataDeleteIndexService.java:80) |  
  | at org.elasticsearch.cluster.metadata.MetadataDeleteIndexService$1.execute(MetadataDeleteIndexService.java:67) |  
  | at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:48) |  
  | at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:691) |  
  | at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:313) |  
  | at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:208) |  
  | at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:62) |  
  | at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:140) |  
  | at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:139) |  
  | at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:177) |  
  | at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673) |  
  | at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:241) |  
  | at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:204) |  
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) |  
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) |  
  | at java.lang.Thread.run(Thread.java:748)
```

Interestingly:

```
 1> [2021-03-01T07:18:45,233][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s_0] [.rolluptmp-gdskvg] creating index, cause [auto(bulk api)], templates [random-soft-deletes-template, one_shard_index_template], shards [1]/[0]
  1> [2021-03-01T07:18:45,303][INFO ][o.e.c.r.a.AllocationService] [node_s_0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[.rolluptmp-gdskvg][0]]]).
  1> [2021-03-01T07:18:45,388][INFO ][o.e.c.m.MetadataMappingService] [node_s_0] [.rolluptmp-gdskvg/JCBO72B1S_qHuVsYsH-ROg] create_mapping [_doc]
  1> [2021-03-01T07:18:45,538][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s_0] [.rolluptmp-ewbvrm] creating index, cause [api], templates [], shards [1]/[1]
  1> [2021-03-01T07:18:45,640][INFO ][o.e.x.r.v.RollupShardIndexer] [node_s_0] Successfully sent [349], indexed [349]
  1> [2021-03-01T07:18:45,671][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s_0] applying create index request using existing index [.rolluptmp-gdskvg] metadata
  1> [2021-03-01T07:18:45,671][DEPRECATION][o.e.d.c.m.MetadataCreateIndexService] [node_s_0] Creating indices with soft-deletes disabled is deprecated and will be removed in future Elasticsearch versions. Please do not specify value for setting [index.soft_deletes.enabled] of index [gdskvg].
  1> [2021-03-01T07:18:45,674][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s_0] [gdskvg] creating index, cause [clone_index], templates [], shards [1]/[1]
  1> [2021-03-01T07:18:45,745][INFO ][o.e.x.r.v.RollupShardIndexer] [node_s_0] Successfully sent [137], indexed [137]
  1> [2021-03-01T07:18:45,778][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s_0] applying create index request using existing index [.rolluptmp-ewbvrm] metadata
  1> [2021-03-01T07:18:45,781][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s_0] [ewbvrm] creating index, cause [clone_index], templates [], shards [1]/[1]
  1> [2021-03-01T07:18:45,822][INFO ][o.e.c.m.MetadataMappingService] [node_s_0] [gdskvg/bnWkAV53T2eRl7HfGNjlfw] create_mapping [_doc]
  1> [2021-03-01T07:18:45,855][INFO ][o.e.c.m.MetadataMappingService] [node_s_0] [ewbvrm/fZnuR_RmSN2Pj3tVaBiD-w] create_mapping [_doc]
  1> [2021-03-01T07:18:45,975][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_s_0] [.rolluptmp-ewbvrm/-LKTPjL7SBC2MsyLFJS_HA] deleting index
  1> [2021-03-01T07:18:46,006][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_s_0] [.rolluptmp-gdskvg/JCBO72B1S_qHuVsYsH-ROg] deleting index
  1> [2021-03-01T07:18:46,085][INFO ][o.e.x.r.v.RollupActionSingleNodeTests] [testHistogramGrouping] after test
```
The index is deleted and THEN deleted again in the after test clause??

**Comment by talevy** [comment]
Closing this issue in favor of #69799. All the RollupActionSingleNodeTests failures in recent weeks should be tracked there.
