### ISSUE TITLE
ARM64 support for 6.x

### ISSUE THREAD

**Issue by maschwenk** [elastic/elasticsearch#69767]
Are there plans to publish arm64 images for the 6.x series? Right now the only ones I see on DockerHub are for 7.x. I tried building my own and got 

```
docker run --rm -e "ES_JAVA_OPTS=-Xms128m -Xmx128m" -p 9200:9200 maschwenk/elasticsearch-6-8-m1-mac:latest         
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

When running on my M1 mac

**Comment by mark-vieira** [comment]
Thanks for reaching out. We have no current plans to support Elasticsearch on aarch64 for the 6.x series.

I tried running the x86 image via emulation on an M1 mac but it blows up starting ML. I tried `node.ml=false` but that didn't seem to help. @droberts195 I would have though just disabling ML would but sufficient to get things running via the x86 emulation.

```
[2021-03-04T01:08:04,756][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [unknown] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: org.elasticsearch.bootstrap.BootstrapException: java.io.IOException: Cannot run program "/usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller": error=0, Failed to exec spawn helper: pid: 130, exit value: 1
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.8.14.jar:6.8.14]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.8.14.jar:6.8.14]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.8.14.jar:6.8.14]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.8.14.jar:6.8.14]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.8.14.jar:6.8.14]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.8.14.jar:6.8.14]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.8.14.jar:6.8.14]
```
I am however able to run the `elasticsearch-oss` amd64 image.

**Comment by maschwenk** [comment]
@mark-vieira Running the oss image I get

`docker run --rm -it -e "ES_JAVA_OPTS=-Xms512m -Xmx512m" -p 9200:9200 docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.14`

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
OpenJDK 64-Bit Server VM warning: UseAVX=2 is not supported on this CPU, setting it to UseAVX=0
This command is not for general use and should only be run as the result of a call to
ProcessBuilder.start() or Runtime.exec() in a java application
[2021-03-04T01:40:34,740][WARN ][o.e.b.JNANatives         ] [unknown] unable to install syscall filter: 
java.lang.UnsupportedOperationException: seccomp unavailable: CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER are needed
        at org.elasticsearch.bootstrap.SystemCallFilter.linuxImpl(SystemCallFilter.java:342) ~[elasticsearch-6.8.14.jar:6.8.14]
        at org.elasticsearch.bootstrap.SystemCallFilter.init(SystemCallFilter.java:617) ~[elasticsearch-6.8.14.jar:6.8.14]
        at org.elasticsearch.bootstrap.JNANatives.tryInstallSystemCallFilter(JNANatives.java:260) [elasticsearch-6.8.14.jar:6.8.14]
        at org.elasticsearch.bootstrap.Natives.tryInstallSystemCallFilter(Natives.java:113) [elasticsearch-6.8.14.jar:6.8.14]
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:108) [elasticsearch-6.8.14.jar:6.8.14]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170) [elasticsearch-6.8.14.jar:6.8.14]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) [elasticsearch-6.8.14.jar:6.8.14]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-6.8.14.jar:6.8.14]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-6.8.14.jar:6.8.14]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.8.14.jar:6.8.14]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.8.14.jar:6.8.14]
        at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.8.14.jar:6.8.14]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) [elasticsearch-6.8.14.jar:6.8.14]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.8.14.jar:6.8.14]
[2021-03-04T01:40:36,050][INFO ][o.e.e.NodeEnvironment    ] [wmD0WRb] using [1] data paths, mounts [[/ (overlay)]], net usable_space [166.1gb], net total_space [195.8gb], types [overlay]
[2021-03-04T01:40:36,051][INFO ][o.e.e.NodeEnvironment    ] [wmD0WRb] heap size [512mb], compressed ordinary object pointers [true]
[2021-03-04T01:40:36,063][INFO ][o.e.n.Node               ] [wmD0WRb] node name derived from node ID [wmD0WRbtQua1HJ5aUkX0Ww]; set [node.name] to override
[2021-03-04T01:40:36,064][INFO ][o.e.n.Node               ] [wmD0WRb] version[6.8.14], pid[1], build[oss/docker/dab5822/2021-02-02T19:58:04.182039Z], OS[Linux/4.19.121-linuxkit/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/15.0.1/15.0.1+9]
[2021-03-04T01:40:36,064][INFO ][o.e.n.Node               ] [wmD0WRb] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch-2021683552785109788, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -XX:UseAVX=2, -Des.cgroups.hierarchy.override=/, -Xms512m, -Xmx512m, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=oss, -Des.distribution.type=docker]
[2021-03-04T01:40:39,420][INFO ][o.e.p.PluginsService     ] [wmD0WRb] loaded module [aggs-matrix-stats]
[2021-03-04T01:40:39,421][INFO ][o.e.p.PluginsService     ] [wmD0WRb] loaded module [analysis-common]
[2021-03-04T01:40:39,422][INFO ][o.e.p.PluginsService     ] [wmD0WRb] loaded module [ingest-common]
[2021-03-04T01:40:39,422][INFO ][o.e.p.PluginsService     ] [wmD0WRb] loaded module [ingest-geoip]
[2021-03-04T01:40:39,422][INFO ][o.e.p.PluginsService     ] [wmD0WRb] loaded module [ingest-user-agent]
[2021-03-04T01:40:39,422][INFO ][o.e.p.PluginsService     ] [wmD0WRb] loaded module [lang-expression]
[2021-03-04T01:40:39,423][INFO ][o.e.p.PluginsService     ] [wmD0WRb] loaded module [lang-mustache]
[2021-03-04T01:40:39,423][INFO ][o.e.p.PluginsService     ] [wmD0WRb] loaded module [lang-painless]
[2021-03-04T01:40:39,423][INFO ][o.e.p.PluginsService     ] [wmD0WRb] loaded module [mapper-extras]
[2021-03-04T01:40:39,423][INFO ][o.e.p.PluginsService     ] [wmD0WRb] loaded module [parent-join]
[2021-03-04T01:40:39,424][INFO ][o.e.p.PluginsService     ] [wmD0WRb] loaded module [percolator]
[2021-03-04T01:40:39,424][INFO ][o.e.p.PluginsService     ] [wmD0WRb] loaded module [rank-eval]
[2021-03-04T01:40:39,424][INFO ][o.e.p.PluginsService     ] [wmD0WRb] loaded module [reindex]
[2021-03-04T01:40:39,424][INFO ][o.e.p.PluginsService     ] [wmD0WRb] loaded module [repository-url]
[2021-03-04T01:40:39,425][INFO ][o.e.p.PluginsService     ] [wmD0WRb] loaded module [transport-netty4]
[2021-03-04T01:40:39,425][INFO ][o.e.p.PluginsService     ] [wmD0WRb] loaded module [tribe]
[2021-03-04T01:40:39,426][INFO ][o.e.p.PluginsService     ] [wmD0WRb] no plugins loaded
[2021-03-04T01:40:52,069][INFO ][o.e.d.DiscoveryModule    ] [wmD0WRb] using discovery type [zen] and host providers [settings]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000401ef65789, pid=1, tid=114
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (15.0.1+9) (build 15.0.1+9)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (15.0.1+9, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# J 3244 c1 java.lang.String.startsWith(Ljava/lang/String;)Z java.base@15.0.1 (7 bytes) @ 0x000000401ef65789 [0x000000401ef657a0+0xffffffffffffffe9]
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# logs/hs_err_pid1.log
Compiled method (c1)   23649 3244       2       java.lang.String::startsWith (7 bytes)
 total in heap  [0x000000401ef65610,0x000000401ef65928] = 792
 relocation     [0x000000401ef65768,0x000000401ef65798] = 48
 main code      [0x000000401ef657a0,0x000000401ef65880] = 224
 stub code      [0x000000401ef65880,0x000000401ef658c0] = 64
 metadata       [0x000000401ef658c0,0x000000401ef658c8] = 8
 scopes data    [0x000000401ef658c8,0x000000401ef658e0] = 24
 scopes pcs     [0x000000401ef658e0,0x000000401ef65920] = 64
 dependencies   [0x000000401ef65920,0x000000401ef65928] = 8
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
#
qemu: uncaught target signal 6 (Aborted) - core dumped
```

**Comment by mark-vieira** [comment]
Well... the QEMU emulation is frankly not ideal and there are no guarantees there. If you need to run ES 6.x on Apple silicon the best option is probably to use a proper aarch64 JDK and use the tarball distribution.

**Comment by zeljkokalezic** [comment]
For people that need to run ES 6.x images for various reasons these are working for me fine on my M1 MacBook (Docker for desktop 3.3.1, BigSur)

https://hub.docker.com/r/webhippie/elasticsearch/

**Comment by mark-vieira** [comment]
If that works well enough for you for testing/development I say go for it.
