### ISSUE TITLE
Timeouts in various YAML tests suggestive of slow regex matching of _cat API outputs

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#69778]
- https://gradle-enterprise.elastic.co/s/msf73k2qaprwy apparently took >30m (!) on `cat.nodes/10_basic/Test cat nodes output`, and the stack trace indicated it was busy deep in a Regex match at time of failure.

- https://gradle-enterprise.elastic.co/s/vkzbl5gtdiyze also took >30s on a similar test, and eventually the whole suite timed out

**Repro line**: `./gradlew ':qa:mixed-cluster:v7.11.2#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=cat.nodes/10_basic/Test cat nodes output}" -Dtests.seed=FE723402774A46F3 -Dtests.security.manager=true -Dtests.bwc=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=pt -Dtests.timezone=Pacific/Honolulu -Druntime.java=8` although this is not obviously relevant.

**Reproduces locally?**: Not like that, no.

**Applicable branches**: `master` and `7.x`

**Failure history**: A few times a day for at least the last week: https://build-stats.elastic.co/goto/f0e40be98917decf207fc23655bd65f0

A longer view indicates that this got a lot worse recently: https://build-stats.elastic.co/goto/ae9d41069a2ae3a731ec0c4407b3854f

<img width="1448" alt="image" src="https://user-images.githubusercontent.com/5058284/109634782-8cc8e980-7b41-11eb-8d56-b272596720da.png">

**Failure excerpt**:

```
  2> java.lang.Exception: Test abandoned because suite timeout was reached.
        at __randomizedtesting.SeedInfo.seed([388E0D08E2C4934E]:0)
```

The test thread was busy at time of failure here:

```
  2>   119) Thread[id=294, name=TEST-MixedClusterClientYamlTestSuiteIT.test-seed#[FE723402774A46F3], state=RUNNABLE, group=TGRP-MixedClusterClientYamlTestSuiteIT]
  2>         at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3811)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4808)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4195)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4196)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(P  2> attern.java:4196)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4196)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4196)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4195)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4196)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4196)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4195)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4196)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4195)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4293)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4196)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4196)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4195)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4293)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4196)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4195)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4293)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4196)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4195)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4195)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4293)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4196)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4196)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4196)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4196)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(  2> Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4196)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4799)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Ques.match(Pattern.java:4195)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.matchInit(Pattern.java:4815)
  2>         at java.util.regex.Pattern$Prolog.match(Pattern.java:4755)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4293)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3812)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$BranchConn.match(Pattern.java:4582)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$Branch.match(Pattern.java:4618)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4293)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$BranchConn.match(Pattern.java:4582)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$BranchConn.match(Pattern.java:4582)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3812)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Branch.match(Pattern.java:4618)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$Branch.match(Pattern.java:4616)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Branch.match(Pattern.java:4618)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4293)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$BranchConn.match(Pattern.java:4582)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$BranchConn.match(Pattern.java:4582)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3812)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Branch.match(Pattern.java:4618)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$Branch.match(Pattern.java:4616)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Branch.match(Pattern.java:4618)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4293)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$BranchConn.match(Pattern.java:4582)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$BranchConn.match(Pattern.java:4582)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3812)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Branch.match(Pattern.java:4618)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$Branch.match(Pattern.java:4616)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Branch.match(Pattern.java:4618)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4293)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$Branch.match(Pattern.java:4616)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4293)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4293)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4293)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4293)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4808)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3812)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4293)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4786)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3812)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4293)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.match(Pattern.java:4786)
  2>         at java.util.regex.Pattern$GroupTail.match(Pattern.java:4731)
  2>         at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3812)
  2>         at java.util.regex.Pattern$Curly.match0(Pattern.java:4286)
  2>         at java.util.regex.Pattern$Curly.match(Pattern.java:4248)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.matchInit(Pattern.java:4815)
  2>         at java.util.regex.Pattern$Prolog.match(Pattern.java:4755)
  2>         at java.util.regex.Pattern$GroupHead.match(Pattern.java:4672)
  2>         at java.util.regex.Pattern$Loop.matchInit(Pattern.java:4815)
  2>         at java.util.regex.Pattern$Prolog.match(Pattern.java:4755)
  2>         at java.util.regex.Pattern$Begin.match(Pattern.java:3539)
  2>         at java.util.regex.Matcher.search(Matcher.java:1248)
  2>         at java.util.regex.Matcher.find(Matcher.java:637)
  2>         at org.elasticsearch.test.hamcrest.RegexMatcher.matchesSafely(RegexMatcher.java:36)
  2>         at org.elasticsearch.test.hamcrest.RegexMatcher.matchesSafely(RegexMatcher.java:19)
  2>         at org.hamcrest.TypeSa  2> feMatcher.matches(TypeSafeMatcher.java:67)
  2>         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:10)
  2>         at org.junit.Assert.assertThat(Assert.java:956)
  2>         at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:57)
  2>         at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
  2>         at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:444)
  2>         at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:428)
  2>         at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
  2>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  2>         at java.lang.reflect.Method.invoke(Method.java:498)
  2>         at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  2>         at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  2>         at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  2>         at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  2>         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  2>         at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  2>         at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  2>         at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  2>         at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  2>         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  2>         at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  2>         at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  2>         at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  2>         at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  2>         at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  2>         at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  2>         at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  2>         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  2>         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  2>         at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  2>         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  2>         at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  2>         at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  2>         at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  2>         at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  2>         at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  2>         at java.lang.Thread.run(Thread.java:748)
```

**Comment by DaveCTurner** [comment]
Duplicates #69641
