### ISSUE TITLE
Various RollupActionSingleNodeTests failing with IndexNotFoundException

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#69799]
**Build scan**: 

- https://gradle-enterprise.elastic.co/s/ib5r6mw23rtcs
- https://gradle-enterprise.elastic.co/s/ezyp34u27mc36
- https://gradle-enterprise.elastic.co/s/s6zuen2tr2dva

**Repro line**: `./gradlew ':x-pack:plugin:rollup:test' --tests "org.elasticsearch.xpack.rollup.v2.RollupActionSingleNodeTests.testMaxMetric" -Dtests.seed=AF76AE54E383FA3F -Dtests.security.manager=true -Dtests.locale=nb -Dtests.timezone=Asia/Pontianak -Druntime.java=11`

**Reproduces locally?**: No

**Applicable branches**: `master`, `7.x` and `7.12`

**Failure history**:

https://build-stats.elastic.co/goto/de41e6b94aa2ae417cbe342ddc4d0741 indicates a few failures a day.

**Failure excerpt**:

```
  1> [2021-03-02T15:01:32,165][INFO ][o.e.x.r.v.RollupActionSingleNodeTests] [testAvgMetric] before test
  1> [2021-03-02T15:01:32,167][DEPRECATION][o.e.d.c.m.MetadataCreateIndexService] [node_s_0] index [jnmin] matches multiple legacy templates [one_shard_index_template, random-soft-deletes-template], composable templates will only match a single template
  1> [2021-03-02T15:01:32,173][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s_0] [jnmin] creating index, cause [api], templates [one_shard_index_template, random-soft-deletes-template], shards [1]/[0]
  1> [2021-03-02T15:01:32,232][DEPRECATION][o.e.d.c.m.MetadataCreateIndexService] [node_s_0] index [.rolluptmp-kglmlq] matches multiple legacy templates [one_shard_index_template, random-soft-deletes-template], composable templates will only match a single template
  1> [2021-03-02T15:01:32,233][DEPRECATION][o.e.d.c.m.MetadataCreateIndexService] [node_s_0] index name [.rolluptmp-kglmlq] starts with a dot '.', in the next major version, index names starting with a dot are reserved for hidden indices and system indices
  1> [2021-03-02T15:01:32,236][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s_0] [.rolluptmp-kglmlq] creating index, cause [auto(bulk api)], templates [one_shard_index_template, random-soft-deletes-template], shards [1]/[0]
  1> [2021-03-02T15:01:32,362][INFO ][o.e.c.r.a.AllocationService] [node_s_0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[.rolluptmp-kglmlq][0]]]).
  1> [2021-03-02T15:01:32,762][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s_0] [.rolluptmp-ecjbud] creating index, cause [api], templates [], shards [1]/[1]
  1> [2021-03-02T15:01:32,834][INFO ][o.e.c.m.MetadataMappingService] [node_s_0] [.rolluptmp-kglmlq/3YQHCIUPTW6YJhWTeug1Og] create_mapping [_doc]
  1> [2021-03-02T15:01:33,091][INFO ][o.e.x.r.v.RollupShardIndexer] [node_s_0] Successfully sent [262], indexed [262]
  1> [2021-03-02T15:01:33,149][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s_0] applying create index request using existing index [.rolluptmp-kglmlq] metadata
  1> [2021-03-02T15:01:33,153][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s_0] [kglmlq] creating index, cause [clone_index], templates [], shards [1]/[1]
  1> [2021-03-02T15:01:33,220][INFO ][o.e.x.r.v.RollupShardIndexer] [node_s_0] Successfully sent [10], indexed [10]
  1> [2021-03-02T15:01:33,328][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s_0] applying create index request using existing index [.rolluptmp-ecjbud] metadata
  1> [2021-03-02T15:01:33,330][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s_0] [ecjbud] creating index, cause [clone_index], templates [], shards [1]/[1]
  1> [2021-03-02T15:01:33,435][INFO ][o.e.c.m.MetadataMappingService] [node_s_0] [ecjbud/3VA-iINcTl6RCqNgz1jHxQ] create_mapping [_doc]
  1> [2021-03-02T15:01:33,509][INFO ][o.e.c.m.MetadataMappingService] [node_s_0] [kglmlq/g1PmmRXuQQ-6VUQ-duXhUA] create_mapping [_doc]
  1> [2021-03-02T15:01:33,633][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_s_0] [.rolluptmp-ecjbud/EbxCDhmdS-SltrHrWilOOQ] deleting index
  1> [2021-03-02T15:01:33,768][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_s_0] [.rolluptmp-kglmlq/3YQHCIUPTW6YJhWTeug1Og] deleting index
  1> [2021-03-02T15:01:33,780][INFO ][o.e.x.r.v.RollupActionSingleNodeTests] [testAvgMetric] after test
  2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:rollup:test' --tests "org.elasticsearch.xpack.rollup.v2.RollupActionSingleNodeTests.testAvgMetric" -Dtests.seed=5EC5B0A6CCAA9904 -Dtests.security.manager=true -Dtests.locale=is -Dtests.timezone=Africa/Lubumbashi -Druntime.java=8
  2> [.rolluptmp-kglmlq/3YQHCIUPTW6YJhWTeug1Og] IndexNotFoundException[no such index [.rolluptmp-kglmlq]]
        at __randomizedtesting.SeedInfo.seed([5EC5B0A6CCAA9904:73AACC3E1E9D7A9D]:0)
        at org.elasticsearch.cluster.metadata.Metadata.getIndexSafe(Metadata.java:719)
        at org.elasticsearch.cluster.metadata.MetadataDeleteIndexService.deleteIndices(MetadataDeleteIndexService.java:80)
        at org.elasticsearch.cluster.metadata.MetadataDeleteIndexService$1.execute(MetadataDeleteIndexService.java:67)
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:48)
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:691)
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:313)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:208)
        at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:62)
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:140)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:139)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:177)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:241)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:204)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by DaveCTurner** [comment]
Muted in `master`, `7.x` and `7.12`.

**Comment by talevy** [comment]
Unmuted in `master/8.0` for more debugging information. Difficult to reproduce and find out what is going on locally. #70519 unmuted. Will mute again if still causing issues and enough logging information was collected.
