### ISSUE TITLE
ArchiveTests#test51JavaHomeOverride fails because file is in use on Windows

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#69796]
**Build scan**: https://gradle-enterprise.elastic.co/s/6knl3oqwbjcqm

**Repro line**: None given, I tried `./gradlew :qa:os:destructiveDistroTest.default-windows-archive`

**Reproduces locally?**: No, but I'm not convinced it did anything useful since I have no `vagrant` and no Windows machine.

**Applicable branches**: Only seen on 7.12

**Failure history**: https://build-stats.elastic.co/goto/7d88f8933a0e9e836f0c750f79449e68 indicates no other (non-PR) failures for ages.

**Failure excerpt**:

```
org.elasticsearch.packaging.test.ArchiveTests > test51JavaHomeOverride FAILED
    java.lang.RuntimeException: Command was not successful: [powershell.exe -Command $processInfo = New-Object System.Diagnostics.ProcessStartInfo; $processInfo.FileName = 'C:\tmp\elasticsearch\bin\elasticsearch.bat'; $processInfo.Arguments = '-p C:\tmp\elasticsearch\elasticsearch.pid'; $processInfo.RedirectStandardOutput = $true; $processInfo.RedirectStandardError = $true; $processInfo.RedirectStandardInput = $true; $processInfo.Environment.Add('JAVA_HOME', 'C:\Users\jenkins\.java\java8'); $processInfo.UseShellExecute = $false; $process = New-Object System.Diagnostics.Process; $process.StartInfo = $processInfo; $outScript = { $EventArgs.Data | Out-File -Encoding UTF8 -Append 'C:\tmp\elasticsearch\logs\output.out' }; $errScript = { $EventArgs.Data | Out-File -Encoding UTF8 -Append 'C:\tmp\elasticsearch\logs\output.err' }; $stdOutEvent = Register-ObjectEvent -InputObject $process -Action $outScript -EventName 'OutputDataReceived'; $stdErrEvent = Register-ObjectEvent -InputObject $process -Action $errScript -EventName 'ErrorDataReceived'; $process.Start() | Out-Null; $process.BeginOutputReadLine(); $process.BeginErrorReadLine(); $process.StandardInput.WriteLine('null'); Wait-Process -Timeout 10 -Id $process.Id; $process.Id;]
       result: exitCode = [1] stdout = [4764] stderr = [Wait-Process : This command stopped operation because process "cmd (4764)" is not stopped in the specified time-out.
    At line:1 char:1103
    + ... t.WriteLine('null'); Wait-Process -Timeout 10 -Id $process.Id; $proce ...
    +                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : CloseError: (System.Diagnostics.Process (cmd):Process) [Wait-Process], TimeoutException
        + FullyQualifiedErrorId : ProcessNotTerminated,Microsoft.PowerShell.Commands.WaitProcessCommand]
        at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:147)
        at org.elasticsearch.packaging.util.Shell.run(Shell.java:73)
        at org.elasticsearch.packaging.util.Archives.runElasticsearchStartCommand(Archives.java:318)
        at org.elasticsearch.packaging.test.PackagingTestCase.runElasticsearchStartCommand(PackagingTestCase.java:293)
        at org.elasticsearch.packaging.test.PackagingTestCase.startElasticsearch(PackagingTestCase.java:352)
        at org.elasticsearch.packaging.test.ArchiveTests.test51JavaHomeOverride(ArchiveTests.java:170)

    java.lang.RuntimeException: java.nio.file.FileSystemException: C:\tmp\elasticsearch\logs\elasticsearch.log -> C:\tmp\elasticsearch\logs\ArchiveTests.test51JavaHomeOverride.elasticsearch.log: The process cannot access the file because it is being used by another process.
        at org.elasticsearch.packaging.util.FileUtils.mv(FileUtils.java:136)
        at org.elasticsearch.packaging.test.PackagingTestCase.teardown(PackagingTestCase.java:186)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.nio.file.FileSystemException: C:\tmp\elasticsearch\logs\elasticsearch.log -> C:\tmp\elasticsearch\logs\ArchiveTests.test51JavaHomeOverride.elasticsearch.log: The process cannot access the file because it is being used by another process.
            at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
            at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
            at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
            at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
            at java.nio.file.Files.move(Files.java:1395)
            at org.elasticsearch.packaging.util.FileUtils.mv(FileUtils.java:134)
            ... 12 more
```

**Comment by mark-vieira** [comment]
We've had no failures of this test in the past month so I'd say it's been sorted out.
