### ISSUE TITLE
ActiveDirectoryRealmTests#testUnauthenticatedLookupWithConnectionPool failed to find user

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#69804]
**Build scan**: https://gradle-enterprise.elastic.co/s/tw7kq5un6sjus

**Repro line**: `REPRODUCE WITH: ./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.authc.ldap.ActiveDirectoryRealmTests.testUnauthenticatedLookupWithConnectionPool" -Dtests.seed=C166C47928FCFF84 -Dtests.security.manager=true -Dtests.locale=hi -Dtests.timezone=America/Toronto -Druntime.java=8`

**Reproduces locally?**: No, not after a few iterations.

**Applicable branches**: Only seen in 7.x.

**Failure history**: The only such failure in [many months](https://build-stats.elastic.co/goto/ed23b3c04943e3ed75835953b555b720).

**Failure excerpt**:

```
Suite: Test class org.elasticsearch.xpack.security.authc.ldap.ActiveDirectoryRealmTests
  1> [2021-03-02T07:10:15,872][INFO ][o.e.x.s.a.l.ActiveDirectoryRealmTests] [testUnauthenticatedLookupWithConnectionPool] before test
  1> [2021-03-02T07:10:16,461][WARN ][o.e.x.s.a.s.DnRoleMapper ] [testUnauthenticatedLookupWithConnectionPool] Role mapping file [/private/var/lib/jenkins/workspace/elastic+elasticsearch+7.x+multijob-darwin-compatibility/x-pack/plugin/security/build/testrun/test/temp/org.elasticsearch.xpack.security.authc.ldap.ActiveDirectoryRealmTests_C166C47928FCFF84-001/tempDir-002/config/role_mapping.yml] for realm [testunauthenticatedlookupwithconnectionpool] does not exist. Role mapping will be skipped.
  1> [2021-03-02T07:10:21,681][INFO ][o.e.x.s.a.l.ActiveDirectoryRealmTests] [testUnauthenticatedLookupWithConnectionPool] after test
  2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.authc.ldap.ActiveDirectoryRealmTests.testUnauthenticatedLookupWithConnectionPool" -Dtests.seed=C166C47928FCFF84 -Dtests.security.manager=true -Dtests.locale=hi -Dtests.timezone=America/Toronto -Druntime.java=8
  2> java.lang.AssertionError: 
    Expected: not null
         but: was null
        at __randomizedtesting.SeedInfo.seed([C166C47928FCFF84:49682346750AAACF]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.security.authc.ldap.ActiveDirectoryRealmTests.doUnauthenticatedLookup(ActiveDirectoryRealmTests.java:330)
        at org.elasticsearch.xpack.security.authc.ldap.ActiveDirectoryRealmTests.testUnauthenticatedLookupWithConnectionPool(ActiveDirectoryRealmTests.java:299)
```

**Comment by slobodanadamovic** [comment]
I could not reproduce this one. It seems that it did not happen since it was reported. This might be because [darwin CI jobs have been removed](https://github.com/elastic/elasticsearch/issues/58286#issuecomment-1115546995) due to constant failures.
