### ISSUE TITLE
Watcher should retry a failed reload

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#69842]
If for some reason watcher fails to start after being paused due to an unrelated instance (such as the master node disappearing), and the reload of the Watch fails like in the stack trace below, Watcher enters a "started" state, but actually does nothing. 

The remediation is stopping and starting watcher, however this is not ideal since the alerting system is now effectively down.  Watcher should continue to retry starting if the reload fails. This change would likely be setting some type of error state on the watch status so that the normal cluster state even would continue to retry starting. 

This is quite similar to https://github.com/elastic/elasticsearch/issues/44981 , however in that case a stop/start does not fix the issue..but in this case it does. The fix here is likely applicable to both issues. 

```
Mar 1, 2021 @ 11:15:02.084[instance-0000000017] error reloading watcher
org.elasticsearch.ElasticsearchTimeoutException: java.util.concurrent.TimeoutException: Timeout waiting for task.
	at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:67) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:50) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:44) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.xpack.watcher.WatcherService.loadWatches(WatcherService.java:285) ~[x-pack-watcher-7.11.1.jar:7.11.1]
	at org.elasticsearch.xpack.watcher.WatcherService.reloadInner(WatcherService.java:235) ~[x-pack-watcher-7.11.1.jar:7.11.1]
	at org.elasticsearch.xpack.watcher.WatcherService.lambda$reload$1(WatcherService.java:198) [x-pack-watcher-7.11.1.jar:7.11.1]
	at org.elasticsearch.xpack.watcher.WatcherService$1.doRun(WatcherService.java:408) [x-pack-watcher-7.11.1.jar:7.11.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732) [elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.11.1.jar:7.11.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.util.concurrent.TimeoutException: Timeout waiting for task.
	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:232) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:54) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:65) ~[elasticsearch-7.11.1.jar:7.11.1]
	... 11 more

Mar 1, 2021 @ 11:15:01.750[instance-0000000006] error reloading watcher
org.elasticsearch.ElasticsearchTimeoutException: java.util.concurrent.TimeoutException: Timeout waiting for task.
	at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:67) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:50) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:44) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.xpack.watcher.WatcherService.loadWatches(WatcherService.java:285) ~[x-pack-watcher-7.11.1.jar:7.11.1]
	at org.elasticsearch.xpack.watcher.WatcherService.reloadInner(WatcherService.java:235) ~[x-pack-watcher-7.11.1.jar:7.11.1]
	at org.elasticsearch.xpack.watcher.WatcherService.lambda$reload$1(WatcherService.java:198) [x-pack-watcher-7.11.1.jar:7.11.1]
	at org.elasticsearch.xpack.watcher.WatcherService$1.doRun(WatcherService.java:408) [x-pack-watcher-7.11.1.jar:7.11.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732) [elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.11.1.jar:7.11.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.util.concurrent.TimeoutException: Timeout waiting for task.
	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:232) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:54) ~[elasticsearch-7.11.1.jar:7.11.1]
	at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:65) ~[elasticsearch-7.11.1.jar:7.11.1]
	... 11 more

Mar 1, 2021 @ 11:14:57.072[instance-0000000017] reloading watcher, reason [new local watcher shard allocation ids], cancelled [0] queued tasks
Mar 1, 2021 @ 11:14:56.749[instance-0000000006] reloading watcher, reason [new local watcher shard allocation ids], cancelled [0] queued tasks
Mar 1, 2021 @ 11:14:44.765[instance-0000000017] paused watch execution, reason [no master node], cancelled [43] queued tasks
Mar 1, 2021 @ 11:14:44.585[instance-0000000006] paused watch execution, reason [no master node], cancelled [5] queued tasks
```

**Comment by sakurai-youhei** [comment]
The description of PR #90421, that has fixed #44981 in v7.17.7 and v8.5.0, said:
> when the next cluster change event comes through it will attempt to start watcher again.

So, the retry is supposed to occur on those versions and above, but the watcher service may still be left STOPPED for a while like hours because [ClusterChangedEvent](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/cluster/ClusterChangedEvent.java) may not come in soon.
