### ISSUE TITLE
Windows failing to start ES during rolling upgrade tests

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#69988]
**Build scan**: https://gradle-enterprise.elastic.co/s/6zuy7d635uuiq

**Repro line**:None logged. This is what jenkins ran:
```
call ./gradlew.bat --parallel --scan --build-cache -Dorg.elasticsearch.build.cache.url=https://gradle-enterprise.elastic.co/cache/ -S --parallel --max-workers=2 -Dbwc.checkout.align=true  check 
```

**Reproduces locally?**: No windows.

**Applicable branches**: Hard to tell because build-stats can't really find these

**Failure history**:

**Failure excerpt**:
```
:x-pack:qa:password-protected-keystore:check
:x-pack:qa:reindex-tests-with-security:integTest
:x-pack:qa:reindex-tests-with-security:check
:x-pack:qa:rolling-upgrade:v7.13.0#oldClusterTest FAILED
Exec output and error:
| Output for cmd:Exception in thread "main" SettingsException[Failed to load settings from [elasticsearch.yml]]; nested: MarkedYAMLException[while scanning a double-quoted scalar
 in 'reader', line 9, column 14:
    path.repo: [ "C:\Users\jenkins\workspace\elas ... 
                 ^
expected escape sequence of 8 hexadecimal numbers, but found: sers\jen
 in 'reader', line 9, column 19:
    path.repo: [ "C:\Users\jenkins\workspace\elastic+e ... 
                      ^

 at [Source: (sun.nio.ch.ChannelInputStream); line: 9, column: 13]]; nested: ScannerException[while scanning a double-quoted scalar
 in 'reader', line 9, column 14:
    path.repo: [ "C:\Users\jenkins\workspace\elas ... 
                 ^
expected escape sequence of 8 hexadecimal numbers, but found: sers\jen
 in 'reader', line 9, column 19:
    path.repo: [ "C:\Users\jenkins\workspace\elastic+e ... 
                      ^
];
| 	at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1102)
| 	at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Settings.java:1075)
| 	at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:72)
| 	at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:89)
| 	at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:80)
| 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
| 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
| 	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:80)
| 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
| 	at org.elasticsearch.cli.Command.main(Command.java:79)
| 	at org.elasticsearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:32)
| Caused by: com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while scanning a double-quoted scalar
```

**Comment by nik9000** [comment]
https://gradle-enterprise.elastic.co/s/ofpggqb4pgz4c
