### ISSUE TITLE
Failed to find ML cpp notice

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#69993]
**Build scan**: https://gradle-enterprise.elastic.co/s/bddwgnmmn7c26

**Repro line**: Didn't log one but `./gradlew :distribution:archives:integ-test-zip:checkMlCppNotice` reproduces it.

**Reproduces locally?**: Yes

**Applicable branches**: Scan is in 7.11 but its hard to tell which branches have it because it doesn't seem to fail the build

**Failure history**: I don't think this actually fails the build.

**Failure excerpt**:
```
java.nio.file.NoSuchFileException: /dev/shm/elastic+elasticsearch+7.11+matrix-java-periodic/ES_RUNTIME_JAVA/adoptopenjdk8/nodes/general-purpose/distribution/archives/integ-test-zip/build/zip-extracted/elasticsearch-7.11.2-SNAPSHOT/modules/x-pack-ml/NOTICE.txt
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
```

**Comment by mark-vieira** [comment]
@breskeby I vaguely remember you mentioning this.

**Comment by jdconrad** [comment]
Here's another one (https://gradle-enterprise.elastic.co/s/efdjfs7akmzio/console-log?anchor=6488)

Note there's a diff build failure, but this did happen near the top of the console output.
