### ISSUE TITLE
1.3.0 ElasticsearchException: Failed to load logging configuration

### ISSUE THREAD

**Issue by brackxm** [elastic/elasticsearch#7002]
LogConfigurator.configure() now requires a config file, while previously it did not.

code to reproduce:
```
        final Node node = NodeBuilder.nodeBuilder()
                .local(true)
                .build();
        LogConfigurator.configure(node.settings());
```

exception:
```
Exception in thread "main" org.elasticsearch.ElasticsearchException: Failed to load logging configuration
	at org.elasticsearch.common.logging.log4j.LogConfigurator.resolveConfig(LogConfigurator.java:117)
	at org.elasticsearch.common.logging.log4j.LogConfigurator.configure(LogConfigurator.java:81)
```

**Comment by clintongormley** [comment]
Yes, this is true and will remain so.  Closing
