### ISSUE TITLE
SLM Retention can throw an exception while running retention when there are no snapshots to delete

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#70029]
**Elasticsearch version** (`bin/elasticsearch --version`): Observed on 7.11.0

**Plugins installed**: []

**JVM version** (`java -version`): built-in

**OS version** (`uname -a` if on a Unix-like system): docker

**Description of the problem including expected versus actual behavior**:

When SLM's retention comes across a repo with zero snapshots eligible for deletion, an exception is thrown due to trying to create a GroupedListsner with a group size of 0. This does not appear to happen in the "simple" case of kist setting up a policy with retention and waiting for a run with 0 snapshots to be deleted, but I can confirm this does happen in some circumstances.

Example exception (trimmed):
```
exception computing snapshots for repository my-repository
java.lang.IllegalArgumentException: groupSize must be greater than 0 but was 0
	at org.elasticsearch.action.support.GroupedActionListener.<init>(GroupedActionListener.java:40) ~[elasticsearch-7.11.0.jar:7.11.0]
	at org.elasticsearch.xpack.slm.SnapshotRetentionTask.deleteSnapshots(SnapshotRetentionTask.java:327) ~[x-pack-ilm-7.11.0.jar:7.11.0]
```

**I do not have a reliable reproduction case for this yet**

Another example case that can happen if there is an error while retrieving the snapshots in a repository:
```
unable to retrieve snapshots for repository [my-repository]
java.lang.IllegalArgumentException: groupSize must be greater than 0 but was 0
	at org.elasticsearch.action.support.GroupedActionListener.<init>(GroupedActionListener.java:40) ~[elasticsearch-7.11.0.jar:7.11.0]
	at org.elasticsearch.xpack.slm.SnapshotRetentionTask.deleteSnapshots(SnapshotRetentionTask.java:327) ~[?:?]
	at org.elasticsearch.xpack.slm.SnapshotRetentionTask.deleteSnapshots(SnapshotRetentionTask.java:319) ~[?:?]
	at org.elasticsearch.xpack.slm.SnapshotRetentionTask$1.onResponse(SnapshotRetentionTask.java:161) ~[?:?]
	at org.elasticsearch.xpack.slm.SnapshotRetentionTask$1.onResponse(SnapshotRetentionTask.java:143) ~[?:?]
	at org.elasticsearch.xpack.slm.SnapshotRetentionTask.lambda$getAllRetainableSnapshots$9(SnapshotRetentionTask.java:251) ~[?:?]
	at org.elasticsearch.xpack.slm.SnapshotRetentionTask.lambda$getAllRetainableSnapshots$12(SnapshotRetentionTask.java:270) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:117) [elasticsearch-7.11.0.jar:7.11.0]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32) [elasticsearch-7.11.0.jar:7.11.0]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:83) [elasticsearch-7.11.0.jar:7.11.0]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:77) [elasticsearch-7.11.0.jar:7.11.0]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32) [elasticsearch-7.11.0.jar:7.11.0]
	at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:143) [elasticsearch-7.11.0.jar:7.11.0]
	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:139) [elasticsearch-7.11.0.jar:7.11.0]
	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:54) [elasticsearch-7.11.0.jar:7.11.0]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:88) [elasticsearch-7.11.0.jar:7.11.0]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$3(TransportMasterNodeAction.java:155) [elasticsearch-7.11.0.jar:7.11.0]
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62) [elasticsearch-7.11.0.jar:7.11.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732) [elasticsearch-7.11.0.jar:7.11.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.11.0.jar:7.11.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]

```

**Comment by original-brownbear** [comment]
This is reproducible by having two repositories both running SLM policies and then just having one be empty or whatever so that no snapshots need to be deleted from it during a run. I'll deal with this, I accidentally broke this when I made SLM move to concurrent deletes.
