### ISSUE TITLE
Very long build configuration times when building BWC distributions

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#70043]
I noticed something very interesting today, it seems building BWC distributions can be _very_ slow when running something like `bwcTestSnapshots`. For example: https://gradle-enterprise.elastic.co/s/jgqlmj57k7s3e/timeline?task-path=buildBwcLinuxTar

8 minutes to build a distribution? That's odd, what's taking so long? Turns out, it's all [configuration time](https://gradle-enterprise.elastic.co/s/fhpzfrljafx7u/timeline). I've observed this locally as well, and in other BWC scenarios such as when doing `resolveAllDep`. My suspicion is the root cause here is some kind of lock contention within Gradle. Whether that's dependency or build script caches is unclear w/o doing thread dumps but I've seen issues where our `packer_cache.sh` script fails as well with errors waiting on locks.

This could be an issue in Gradle's optimistic locking. Daemons should be able to "request" these locks from eachother but it seems perhaps that's not working properly. Or it's locking at too granular a level and we're running into deadlocks. One workaround on our end would be to serialize these tasks w/ ordering rules. It's not ideal but it's better than having workers sitting around for 5 minutes or more doing nothing.

**Comment by mark-vieira** [comment]
@breskeby here's an interesting one. This is adding a substantial amount of time to our BWC jobs. Might be worth taking a look.

**Comment by mark-vieira** [comment]
Here's an example of where I believe this lock contention is causing packer cache failures.

```
> Task :distribution:bwc:staged:resolveAllBwcDependencies
 [7.12.0] 
 [7.12.0] FAILURE: Build failed with an exception.
 [7.12.0] 
 [7.12.0] * What went wrong:
 [7.12.0] A problem occurred configuring project ':plugins:discovery-ec2'.
 [7.12.0] > Timeout waiting to lock jars (/var/lib/jenkins/.gradle/caches/jars-8). It is currently in use by another Gradle instance.
 [7.12.0]   Owner PID: unknown
 [7.12.0]   Our PID: 87508
 [7.12.0]   Owner Operation: unknown
 [7.12.0]   Our operation: 
 [7.12.0]   Lock file: /var/lib/jenkins/.gradle/caches/jars-8/jars-8.lock
 [7.12.0] > description is a required setting for esplugin
 [7.12.0] 
 [7.12.0] * Try:
 [7.12.0] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
 [7.12.0] 
 [7.12.0] * Exception is:
 [7.12.0] org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':plugins:discovery-ec2'.
 [7.12.0] 	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:75)
 [7.12.0] 	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:68)
 [7.12.0] 	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$400(LifecycleProjectEvaluator.java:51)
 [7.12.0] 	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.lambda$run$0(LifecycleProjectEvaluator.java:102)
 [7.12.0] 	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.lambda$applyToMutableState$0(DefaultProjectStateRegistry.java:250)
 [7.12.0] 	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.lambda$withProjectLock$3(DefaultProjectStateRegistry.java:310)
 [7.12.0] 	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:213)
 [7.12.0] 	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withProjectLock(DefaultProjectStateRegistry.java:310)
 [7.12.0] 	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.fromMutableState(DefaultProjectStateRegistry.java:291)
 [7.12.0] 	at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.applyToMutableState(DefaultProjectStateRegistry.java:249)
 [7.12.0] 	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:91)
 [7.12.0] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
 [7.12.0] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
 [7.12.0] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
 [7.12.0] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
 [7.12.0] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
 [7.12.0] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
 [7.12.0] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
```

I'm wondering why the owner pid is showing "unknown" here. This implies that the inter-process communication that _should_ be used to ask other daemons to release this locks is not working.

**Comment by mark-vieira** [comment]
We're incredibly naive about parallelization here. We don't make any attempt to limit max-workers on these nested builds. I'm wondering if indeed just limiting parallelization is the smartest thing here so we don't have 4 Gradle builds all with 16 workers trying to cause the system to implode.
