### ISSUE TITLE
TransformConfigLinterTests.testGetWarnings_Pivot_WithScriptBasedRuntimeFields fails

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#70074]
**Build scan**: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/2334/testReport/junit/org.elasticsearch.xpack.transform.action/TransformConfigLinterTests/testGetWarnings_Pivot_WithScriptBasedRuntimeFields/

**Repro line**:
./gradlew ':x-pack:plugin:transform:test' --tests "org.elasticsearch.xpack.transform.action.TransformConfigLinterTests.testGetWarnings_Pivot_WithScriptBasedRuntimeFields" -Dtests.seed=8AE95425FC73191D -Dtests.security.manager=true -Dtests.locale=el -Dtests.timezone=SystemV/CST6CDT -Druntime.java=11

**Reproduces locally?**:
Yes

**Applicable branches**:
master and 7.x

**Failure excerpt**:
```
java.lang.AssertionError: 
Expected: is an empty collection
     but: <[could not find any optimizations for continuous execution, this transform might run slowly, please check your configuration.]>
	at __randomizedtesting.SeedInfo.seed([8AE95425FC73191D:4ADE3FCDA1B9C621]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.transform.action.TransformConfigLinterTests.testGetWarnings_Pivot_WithScriptBasedRuntimeFields(TransformConfigLinterTests.java:50)
```

**Comment by przemekwitek** [comment]
The fix is ready, I'll merge it ASAP
