### ISSUE TITLE
Unable to index into ilm history index during a rolling upgrade.

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#70086]
I noticed the following warning log during a rolling upgrade (from 7.0.1 to 7.13-snapshot):

```
[2021-03-08T09:57:36,107][ERROR][o.e.x.i.h.ILMHistoryStore] [v7.0.1-0] failed to index 3 items into ILM history index
»  java.lang.IllegalArgumentException: optype create not supported for indexing requests without explicit id until all nodes are on version 7.5.0 or higher
»  	at org.elasticsearch.action.index.IndexRequest.checkAutoIdWithOpTypeCreateSupportedByVersion(IndexRequest.java:696) ~[elasticsearch-7.13.0-SNAPSHOT.jar:7.13.0-SNAPSHOT]
»  	at org.elasticsearch.action.bulk.TransportBulkAction.doInternalExecute(TransportBulkAction.java:185) ~[elasticsearch-7.13.0-SNAPSHOT.jar:7.13.0-SNAPSHOT]
»  	at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:162) ~[elasticsearch-7.13.0-SNAPSHOT.jar:7.13.0-SNAPSHOT]
»  	at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:89) ~[elasticsearch-7.13.0-SNAPSHOT.jar:7.13.0-SNAPSHOT]
»  	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:173) ~[elasticsearch-7.13.0-SNAPSHOT.jar:7.13.0-SNAPSHOT]
»  	at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:42) ~[elasticsearch-7.13.0-SNAPSHOT.jar:7.13.0-SNAPSHOT]
»  	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:171) ~[elasticsearch-7.13.0-SNAPSHOT.jar:7.13.0-SNAPSHOT]
»  	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$3(SecurityActionFilter.java:160) ~[?:?]
»  	at org.elasticsearch.action.ActionListener$DelegatingFailureActionListener.onResponse(ActionListener.java:217) ~[elasticsearch-7.13.0-SNAPSHOT.jar:7.13.0-SNAPSHOT]
»  	at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:101) ~[elasticsearch-7.13.0-SNAPSHOT.jar:7.13.0-SNAPSHOT]
»  	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-7.13.0-SNAPSHOT.jar:7.13.0-SNAPSHOT]
»  	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:215) ~[elasticsearch-7.13.0-SNAPSHOT.jar:7.13.0-SNAPSHOT]
»  	at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:95) ~[elasticsearch-7.13.0-SNAPSHOT.jar:7.13.0-SNAPSHOT]
»  	at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:87) ~[elasticsearch-7.13.0-SNAPSHOT.jar:7.13.0-SNAPSHOT]
»  	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_281]
```

See: https://gradle-enterprise.elastic.co/s/ciwpar45g6ev6/console-log#L1247

It isn't super bad, but would be great if we not fail like this. Maybe index in a way that is compatible with nodes prior to 7.5.0 or postpone indexing until nodes having the ilm history shards have been upgraded?

**Comment by dakrone** [comment]
> Maybe index in a way that is compatible with nodes prior to 7.5.0 or postpone indexing until nodes having the ilm history shards have been upgraded?

We do have access to the `ClusterService`, I'm not sure if the node versions are in there, but we could inspect that and use a manually generate UUID for the id if there are <= 7.5.0 nodes in the cluster.

**Comment by martijnvg** [comment]
> We do have access to the ClusterService, I'm not sure if the node versions are in there, but we could inspect that and use a manually generate UUID for the id if there are <= 7.5.0 nodes in the cluster.

Yes, from `ClusterService#state()` method, we can fetch the cluster state and figure the node with the lowest version, so that sounds like a good idea.
