### ISSUE TITLE
[CI] ClientYamlTestSuiteIT.test {yaml=search/110_field_collapsing/field collapsing and inner_hits}

### ISSUE THREAD

**Issue by valeriy42** [elastic/elasticsearch#70091]
**Build scan**:
https://gradle-enterprise.elastic.co/s/sbju37ojrle3y

**Repro line**:

```
./gradlew ':rest-api-spec:yamlRestCompatTest' --tests "org.elasticsearch.test.rest.ClientYamlTestSuiteIT.test {yaml=search/110_field_collapsing/field collapsing and inner_hits}" -Dtests.seed=7A9553ECCD95068E -Dtests.security.manager=true -Dtests.locale=ar-MA -Dtests.timezone=Africa/Timbuktu -Druntime.java=11 -Dtests.rest.blacklist=bulk/11_basic_with_types/Array of objects,bulk/11_basic_with_types/Empty _id,bulk/11_basic_with_types/Empty _id with op_type create,bulk/11_basic_with_types/empty action,bulk/21_list_of_strings_with_types/List of strings,bulk/31_big_string_with_types/One big string,bulk/41_source_with_types/Source filtering,bulk/51_refresh_with_types/refresh=empty string immediately makes changes are visible in search,bulk/51_refresh_with_types/refresh=true immediately makes changes are visible in search,bulk/51_refresh_with_types/refresh=wait_for waits until changes are visible in search,bulk/70_mix_typeless_typeful/bulk without types on an index that has types,bulk/81_cas_with_types/Compare And Swap Sequence Numbers,cat.aliases/10_basic/Alias against closed index,cat.aliases/10_basic/Alias name,cat.aliases/10_basic/Alias sorting,cat.aliases/10_basic/Column headers,cat.aliases/10_basic/Complex alias,cat.aliases/10_basic/Empty cluster,cat.aliases/10_basic/Multiple alias names,cat.aliases/10_basic/Select columns,cat.aliases/10_basic/Simple alias,cat.aliases/40_hidden/Test cat aliases output with a hidden index with a hidden alias,cat.aliases/40_hidden/Test cat aliases output with a hidden index with a visible alias,cat.aliases/40_hidden/Test cat aliases output with a visible index with a hidden alias,cat.allocation/10_basic/All Nodes,cat.allocation/10_basic/Bytes,cat.allocation/10_basic/Column headers,cat.allocation/10_basic/Empty cluster,cat.allocation/10_basic/Node ID,cat.allocation/10_basic/One index,cat.allocation/10_basic/Select columns,cat.count/10_basic/Test cat count output,cat.fielddata/10_basic/Test cat fielddata output,cat.health/10_basic/Empty cluster,cat.health/10_basic/With ts parameter,cat.indices/10_basic/Test cat indices output,cat.indices/10_basic/Test cat indices output (no indices),cat.indices/10_basic/Test cat indices output for closed index,cat.indices/10_basic/Test cat indices sort,cat.indices/10_basic/Test cat indices using health status,cat.indices/10_basic/Test cat indices using wildcards,cat.indices/20_hidden/Test cat indices output for dot-hidden index and dot-prefixed pattern,cat.indices/20_hidden/Test cat indices output for hidden index,cat.indices/20_hidden/Test cat indices output with a hidden index with a hidden alias,cat.indices/20_hidden/Test cat indices output with a hidden index with a visible alias,cat.indices/20_hidden/Test cat indices output with a hidden index, dot-hidden alias and dot pattern,cat.nodeattrs/10_basic/Test cat nodes attrs output,cat.nodes/10_basic/Additional disk information,cat.nodes/10_basic/Test cat nodes output,cat.nodes/10_basic/Test cat nodes output with full_id set,cat.recovery/10_basic/Test cat recovery output,cat.recovery/10_basic/Test cat recovery output for closed index,cat.repositories/10_basic/Test cat repositories output,cat.repositories/10_basic/Test cat repositories sort,cat.segments/10_basic/Test cat segments output,cat.segments/10_basic/Test cat segments using wildcards,cat.shards/10_basic/Help,cat.shards/10_basic/Test cat shards output,cat.shards/10_basic/Test cat shards sort,cat.shards/10_basic/Test cat shards using wildcards,cat.snapshots/10_basic/Help,cat.snapshots/10_basic/Test cat snapshots output,cat.tasks/10_basic/Test cat tasks output,cat.tasks/10_basic/Test cat tasks output with X-Opaque-Id,cat.templates/10_basic/Column headers,cat.templates/10_basic/Filtered templates,cat.templates/10_basic/Mixture of legacy and composable templates,cat.templates/10_basic/Normal templates,cat.templates/10_basic/Select columns,cat.thread_pool/10_basic/Test cat thread_pool output,cluster.voting_config_exclusions/10_basic/Throw exception when adding voting config exclusion and specifying both node_ids and node_names,cluster.voting_config_exclusions/10_basic/Throw exception when adding voting config exclusion without specifying nodes,count/11_basic_with_types/count body without query element,count/11_basic_with_types/count with body,count/11_basic_with_types/count with empty body,create/11_with_id_with_types/Create with ID,create/36_external_version_with_types/External version,create/41_routing_with_types/Routing,create/61_refresh_with_types/Refresh,create/61_refresh_with_types/When refresh url parameter is an empty string that means "refresh immediately",create/61_refresh_with_types/refresh=wait_for waits until changes are visible in search,create/71_nested_with_types/Indexing a doc with No. nested objects less or equal to index.mapping.nested_objects.limit should succeed,create/71_nested_with_types/Indexing a doc with No. nested objects more than index.mapping.nested_objects.limit should fail,delete/11_shard_header/Delete check shard header,delete/13_basic_with_types/Basic,delete/14_shard_header_with_types/Delete check shard header,delete/15_result_with_types/Delete result field,delete/21_cas_with_types/Internal version,delete/27_external_version_with_types/External version,delete/28_external_gte_version_with_types/External GTE version,delete/31_routing_with_types/Routing,delete/51_refresh_with_types/Refresh,delete/51_refresh_with_types/When refresh url parameter is an empty string that means "refresh immediately",delete/51_refresh_with_types/refresh=wait_for waits until changes are visible in search,delete/61_missing_with_types/Missing document with catch,delete/61_missing_with_types/Missing document with ignore,delete/70_mix_typeless_typeful/DELETE with typeless API on an index that has types,exists/11_basic_with_types/Basic,exists/41_routing_with_types/Routing,exists/61_realtime_refresh_with_types/Realtime Refresh,exists/71_defaults_with_types/Client-side default type,explain/10_basic/Basic explain,explain/10_basic/Basic explain with alias,explain/11_basic_with_types/Basic explain,explain/11_basic_with_types/Basic explain with alias,explain/11_basic_with_types/Explain body without query element,explain/20_source_filtering/Source filtering,explain/21_source_filtering_with_types/Source filtering,explain/31_query_string_with_types/explain with query_string parameters,explain/40_mix_typeless_typeful/Explain with typeless API on an index that has types,field_caps/10_basic/Get date_nanos field caps,field_caps/30_filter/Field caps with index filter,get/100_mix_typeless_typeful/GET with typeless API on an index that has types,get/10_basic/Basic,get/11_basic_with_types/Basic,get/15_default_values/Default values,get/16_default_values_with_types/Default values,get/20_stored_fields/Stored fields,get/21_stored_fields_with_types/Stored fields,get/41_routing_with_types/Routing,get/50_with_headers/REST test with headers,get/51_with_headers_with_types/REST test with headers,get/61_realtime_refresh_with_types/Realtime Refresh,get/70_source_filtering/Source filtering,get/71_source_filtering_with_types/Source filtering,get/81_missing_with_types/Missing document with catch,get/81_missing_with_types/Missing document with ignore,get/91_versions_with_types/Versions,get_source/11_basic_with_types/Basic with types,get_source/16_default_values_with_types/Default values,get_source/41_routing_with_types/Routing,get_source/61_realtime_refresh_with_types/Realtime,get_source/71_source_filtering_with_types/Source filtering,get_source/81_missing_with_types/Missing document with catch,get_source/81_missing_with_types/Missing document with ignore,get_source/86_source_missing_with_types/Missing document source with catch,get_source/86_source_missing_with_types/Missing document source with ignore,index/10_with_id/Index with ID,index/11_with_id_with_types/Index with ID,index/13_result_with_types/Index result field,index/15_without_id/Index without ID,index/16_without_id_with_types/Index without ID,index/21_optype_with_types/Optype,index/37_external_version_with_types/External version,index/38_external_gte_version_with_types/External GTE version,index/41_routing_with_types/Routing,in
```

**Reproduces locally?**:

No

**Applicable branches**:

master

**Failure history**:

Seems to start failing today. I observed it failing on master and 3 times on PRs today. 
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.test.rest.ClientYamlTestSuiteIT&tests.sortField=FAILED&tests.test=test%20%7Byaml%3Dsearch/110_field_collapsing/field%20collapsing%20and%20inner_hits%7D&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.test.rest.ClientYamlTestSuiteIT > test {yaml=search/110_field_collapsing/field collapsing and inner_hits} FAILED
    java.lang.AssertionError: Failure at [search/110_field_collapsing:228]: field [hits.hits.0._type] is null
        at __randomizedtesting.SeedInfo.seed([7A9553ECCD95068E:F2C16C3663696B76]:0)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:451)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:428)
        at jdk.internal.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
        at java.base/java.lang.Thread.run(Thread.java:834)

        Caused by:
        java.lang.AssertionError: field [hits.hits.0._type] is null
            at org.junit.Assert.fail(Assert.java:88)
            at org.junit.Assert.assertTrue(Assert.java:41)
            at org.junit.Assert.assertNotNull(Assert.java:712)
            at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:68)
            at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
            at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:444)
            ... 37 more
```

```json
Stash dump on test failure [{
  "stash" : {
    "request_headers" : {
      "Accept" : "application/vnd.elasticsearch+json;compatible-with=7",
      "Content-Type" : "application/vnd.elasticsearch+json;compatible-with=7"
    },
    "body" : {
      "took" : 3,
      "timed_out" : false,
      "_shards" : {
        "total" : 1,
        "successful" : 1,
        "skipped" : 0,
        "failed" : 0
      },
      "hits" : {
        "total" : 6,
        "max_score" : null,
        "hits" : [
          {
            "_index" : "test",
            "_id" : "6",
            "_score" : null,
            "_source" : {
              "tag" : "B",
              "sort" : 36,
              "numeric_group" : 3
            },
            "fields" : {
              "numeric_group" : [
                3
              ]
            },
            "sort" : [
              36
            ],
            "inner_hits" : {
              "sub_hits" : {
                "hits" : {
                  "total" : 1,
                  "max_score" : null,
                  "hits" : [
                    {
                      "_index" : "test",
                      "_id" : "6",
                      "_score" : null,
                      "_source" : {
                        "tag" : "B",
                        "sort" : 36,
                        "numeric_group" : 3
                      },
                      "sort" : [
                        36
                      ]
                    }
                  ]
                }
              }
            }
          },
          {
            "_index" : "test",
            "_id" : "3",
            "_score" : null,
            "_source" : {
              "tag" : "A",
              "sort" : 24,
              "numeric_group" : 1
            },
            "fields" : {
              "numeric_group" : [
                1
              ]
            },
            "sort" : [
              24
            ],
            "inner_hits" : {
              "sub_hits" : {
                "hits" : {
                  "total" : 3,
                  "max_score" : null,
                  "hits" : [
                    {
                      "_index" : "test",
                      "_id" : "2",
                      "_score" : null,
                      "_source" : {
                        "tag" : "B",
                        "sort" : 6,
                        "numeric_group" : 1
                      },
                      "sort" : [
                        6
                      ]
                    },
                    {
                      "_index" : "test",
                      "_id" : "1",
                      "_score" : null,
                      "_source" : {
                        "tag" : "A",
                        "sort" : 10,
                        "numeric_group" : 1
                      },
                      "sort" : [
                        10
                      ]
                    }
                  ]
                }
              }
            }
          },
          {
            "_index" : "test",
            "_id" : "4",
            "_score" : null,
            "_source" : {
              "tag" : "B",
              "sort" : 10,
              "numeric_group" : 25
            },
            "fields" : {
              "numeric_group" : [
                25
              ]
            },
            "sort" : [
              10
            ],
            "inner_hits" : {
              "sub_hits" : {
                "hits" : {
                  "total" : 2,
                  "max_score" : null,
                  "hits" : [
                    {
                      "_index" : "test",
                      "_id" : "5",
                      "_score" : null,
                      "_source" : {
                        "tag" : "A",
                        "sort" : 5,
                        "numeric_group" : 25
                      },
                      "sort" : [
                        5
                      ]
                    },
                    {
                      "_index" : "test",
                      "_id" : "4",
                      "_score" : null,
                      "_source" : {
                        "tag" : "B",
                        "sort" : 10,
                        "numeric_group" : 25
                      },
                      "sort" : [
                        10
                      ]
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}]
```

**Comment by valeriy42** [comment]
Also here https://gradle-enterprise.elastic.co/s/6p6jlqwbanhiq

**Comment by pgomulka** [comment]
fixed https://github.com/elastic/elasticsearch/pull/70095
