### ISSUE TITLE
[CI] FsSearchableSnapshotsIT#testClearCache() test failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#70130]
**Build scan**:  https://gradle-enterprise.elastic.co/s/g4ie3qf5vxoua

**Repro line**: `./gradlew ':x-pack:plugin:searchable-snapshots:qa:rest:integTest' --tests "org.elasticsearch.xpack.searchablesnapshots.rest.FsSearchableSnapshotsIT.testClearCache" -Dtests.seed=18295046DB1AE2F4 -Dtests.security.manager=true -Dtests.locale=ar-AE -Dtests.timezone=Pacific/Apia -Druntime.java=11`

**Reproduces locally?**: No

**Applicable branches**: Master

**Failure history**: It looks like this test failed for the first time. 
No other failures of this test in the last 30 days: https://build-stats.elastic.co/goto/13418a2caf209e30fb7623aad30a8836

**Failure excerpt**:

```
java.lang.AssertionError: |  
-- | --
  | Expected: <64105L> |  
  | but: was <64164L>
at __randomizedtesting.SeedInfo.seed([18295046DB1AE2F4:D6F66A8A5989ADB4]:0) |  
-- | --
  |   | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  |   | at org.junit.Assert.assertThat(Assert.java:956) |  
  |   | at org.junit.Assert.assertThat(Assert.java:923) |  
  |   | at org.elasticsearch.xpack.searchablesnapshots.AbstractSearchableSnapshotsRestTestCase.lambda$testClearCache$18(AbstractSearchableSnapshotsRestTestCase.java:221) |  
  |   | at org.elasticsearch.xpack.searchablesnapshots.AbstractSearchableSnapshotsRestTestCase.runSearchableSnapshotsTest(AbstractSearchableSnapshotsRestTestCase.java:126) |  
  |   | at org.elasticsearch.xpack.searchablesnapshots.AbstractSearchableSnapshotsRestTestCase.runSearchableSnapshotsTest(AbstractSearchableSnapshotsRestTestCase.java:51) |  
  |   | at org.elasticsearch.xpack.searchablesnapshots.AbstractSearchableSnapshotsRestTestCase.testClearCache(AbstractSearchableSnapshotsRestTestCase.java:210)
```

**Comment by davidkyle** [comment]
`HdfsSearchableSnapshotsIT.testClearCache` is also failing with the same stack trace

https://gradle-enterprise.elastic.co/s/o26bbdjyka6ms

```
java.lang.AssertionError: 
Expected: <69283L>
     but: was <69877L>
	at __randomizedtesting.SeedInfo.seed([837D16E969149BA:C6E8EBA2140206FA]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.searchablesnapshots.AbstractSearchableSnapshotsRestTestCase.lambda$testClearCache$18(AbstractSearchableSnapshotsRestTestCase.java:221)
	at org.elasticsearch.xpack.searchablesnapshots.AbstractSearchableSnapshotsRestTestCase.runSearchableSnapshotsTest(AbstractSearchableSnapshotsRestTestCase.java:126)
	at org.elasticsearch.xpack.searchablesnapshots.AbstractSearchableSnapshotsRestTestCase.runSearchableSnapshotsTest(AbstractSearchableSnapshotsRestTestCase.java:51)
	at org.elasticsearch.xpack.searchablesnapshots.AbstractSearchableSnapshotsRestTestCase.testClearCache(AbstractSearchableSnapshotsRestTestCase.java:210)
```
