### ISSUE TITLE
docvalue_fetcher for range fields fails totally

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#70269]
**Elasticsearch version** (`bin/elasticsearch --version`): master, more?

**Steps to reproduce**:
```
curl -XDELETE -uelastic:password -HContent-Type:application/json localhost:9200/test
curl -XPUT -uelastic:password -HContent-Type:application/json localhost:9200/test -d'{
  "mappings": {
    "properties": {
      "r": {
        "type": "long_range"
      }
    }
  }
}'
curl -XPOST -uelastic:password -HContent-Type:application/json 'localhost:9200/test/_doc?pretty&refresh' -d'{
  "r": {
    "gt": 0,
    "lt": 100
  }
}'
curl -XPOST -uelastic:password -HContent-Type:application/json localhost:9200/test/_search?pretty -d'{
  "fields": [{"field": "r"}]
}'
# "fields" : {"r" : [{"lt" : 100, "gt" : 0}]}  Great! Backwards. Whatever.

curl -XPOST -uelastic:password -HContent-Type:application/json localhost:9200/test/_search?pretty -d'{
  "docvalue_fields": [{"field": "r"}]
}'

[2021-03-10T14:55:34,822][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [runTask-0] fatal error in thread [elasticsearch[runTask-0][search][T#7]], exiting
java.lang.AssertionError: null
        at org.apache.lucene.util.UnicodeUtil.UTF8toUTF16(UnicodeUtil.java:593) ~[lucene-core-8.8.0.jar:8.8.0 b10659f0fc18b58b90929cfdadde94544d202c4a - noble - 2021-01-25 19:07:45]
        at org.apache.lucene.util.BytesRef.utf8ToString(BytesRef.java:137) ~[lucene-core-8.8.0.jar:8.8.0 b10659f0fc18b58b90929cfdadde94544d202c4a - noble - 2021-01-25 19:07:45]
        at org.elasticsearch.search.DocValueFormat$1.format(DocValueFormat.java:106) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.DocValueFormat$1.format(DocValueFormat.java:83) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.index.fielddata.LeafFieldData$1.nextValue(LeafFieldData.java:50) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.index.mapper.DocValueFetcher.fetchValues(DocValueFetcher.java:48) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
```

Without assertions enabled ES won't crash but you'll get back some fun garbage.

**Comment by nik9000** [comment]
I wonder if I broke this when I moved doc values fetching onto the value fetcher infrastructure. Certainly we didn't have tests for this.

**Comment by nik9000** [comment]
Date ranges are also broken. They fail on:
```
Caused by: java.lang.UnsupportedOperationException
        at org.elasticsearch.search.DocValueFormat.format(DocValueFormat.java:62) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.index.fielddata.LeafFieldData$1.nextValue(LeafFieldData.java:50) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.index.mapper.DocValueFetcher.fetchValues(DocValueFetcher.java:48) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
```

**Comment by nik9000** [comment]
Duplicate of #53246.
