### ISSUE TITLE
[CI] TransformIndexerTests

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#70297]
**Build scan**: https://gradle-enterprise.elastic.co/s/sjxgxl4lrwvdw

**Repro line**: `./gradlew ':x-pack:plugin:transform:test' --tests "org.elasticsearch.xpack.transform.transforms.TransformIndexerTests.testPageSizeAdapt" -Dtests.seed=CC3798904518E8A0 -Dtests.security.manager=true -Dtests.locale=sr-Latn-ME -Dtests.timezone=Antarctica/Casey -Druntime.java=11`

**Reproduces locally?**: No

**Applicable branches**: 7.11

**Failure history**:  https://build-stats.elastic.co/goto/5224c4b05eb382217f00cb9244258ab0

**Failure excerpt**:

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([CC3798904518E8A0:844B3F16DD5F1A5F]:0)
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.elasticsearch.xpack.transform.transforms.TransformIndexerTests.testPageSizeAdapt(TransformIndexerTests.java:316)
```

**Comment by hendrikmuhs** [comment]
I suspect this is caused by #69551. The test should be relaxed: remove the surrounded `assert`.
