### ISSUE TITLE
[CI] SnapshotRepoTestKitClientYamlTestSuiteIT#'/10_analyze/Analysis with details' test failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#70303]
Different kind of failure than mentioned in #69060. This test only seems to fail on windows ci now.

**Build scan**: https://gradle-enterprise.elastic.co/s/gtntuyss7ikzc

**Repro line**: `gradlew ':x-pack:plugin:snapshot-repo-test-kit:qa:rest:integTest' --tests "org.elasticsearch.repositories.blobstore.testkit.rest.SnapshotRepoTestKitClientYamlTestSuiteIT.test {p0=/10_analyze/Analysis with details}" -Dtests.seed=72305616EAA9BC60 -Dtests.security.manager=true -Dtests.locale=de -Dtests.timezone=MIT -Druntime.java=11`

**Reproduces locally?**: No

**Applicable branches**: master, 7.12

**Failure history**: https://build-stats.elastic.co/goto/4f8e2c03dbd97495c9a0516c5c2a019d

**Failure excerpt**:

```
java.lang.AssertionError: Failure at [/10_analyze:107]: expected [2xx] status code but api [snapshot.repository_analyze] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"uncategorized_execution_exception","reason":"Failed execution","stack_trace":"org.elasticsearch.common.util.concurrent.UncategorizedExecutionException: Failed execution\r\n\tat 
--
```

Likely cause:

```
Caused by: java.util.concurrent.ExecutionException: java.nio.file.AccessDeniedException: C:\\Users\\jenkins\\workspace\\elastic+elasticsearch+master+multijob-windows-compatibility\\os\\windows-2016\\x-pack\\plugin\\snapshot-repo-test-kit\\qa\ |  
-- | --
  | est\\build\	estclusters\ |  
  | epo\	est_repo_loc\	emp-analysis-djO-NuFyTQ-v6KxUVYMKHQ\\pending-test-blob-3-vYASDcxYTD-EZr7VQow0SQ-jb2CxO1_Sf6kDEF_C4DFGg -> C:\\Users\\jenkins\\workspace\\elastic+elasticsearch+master+multijob-windows-compatibility\\os\\windows-2016\\x-pack\\plugin\\snapshot-repo-test-kit\\qa\ |  
  | est\\build\	estclusters\ |  
  | epo\	est_repo_loc\	emp-analysis-djO-NuFyTQ-v6KxUVYMKHQ\	est-blob-3-vYASDcxYTD-EZr7VQow0SQ |  
  | at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:262) |  
  | at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:235) |  
  | at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:54) |  
  | at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:65) |  
  | ... 44 more
```

**Comment by DaveCTurner** [comment]
The (unmangled) root cause is this an `AccessDeniedException` during a rename:

```
java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\x-pack\plugin\snapshot-repo-test-kit\qa\rest\build\testclusters\repo\test_repo_loc\temp-analysis-LAeXrU8DTdSYexwbJ5yJGw\pending-test-blob-0-i1tzoH1GS3azG-lPGbqDww-dNucr_aKR2CPd1Jp1QBNeA -> C:\
Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\x-pack\plugin\snapshot-repo-test-kit\qa\rest\build\testclusters\repo\test_repo_loc\temp-analysis-LAeXrU8DTdSYexwbJ5yJGw\test-blob-0-i1tzoH1GS3azG-lPGbqDww
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:309)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:288)
        at java.base/java.nio.file.Files.move(Files.java:1421)
        at org.elasticsearch.common.blobstore.fs.FsBlobContainer.moveBlobAtomic(FsBlobContainer.java:274)
        at org.elasticsearch.common.blobstore.fs.FsBlobContainer.writeBlobAtomic(FsBlobContainer.java:232)
        at org.elasticsearch.repositories.blobstore.testkit.BlobAnalyzeAction$BlobAnalysis.lambda$writeRandomBlob$5(BlobAnalyzeAction.java:324)
        at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:408)
        at org.elasticsearch.repositories.blobstore.testkit.BlobAnalyzeAction$BlobAnalysis.writeRandomBlob(BlobAnalyzeAction.java:305)
        at org.elasticsearch.repositories.blobstore.testkit.BlobAnalyzeAction$BlobAnalysis.lambda$run$3(BlobAnalyzeAction.java:284)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
        at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:101)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:165)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:95)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.addListener(ListenableFuture.java:57)
        at org.elasticsearch.common.util.concurrent.ListenableFuture.addListener(ListenableFuture.java:43)
        at org.elasticsearch.action.StepListener.addListener(StepListener.java:108)
        at org.elasticsearch.action.StepListener.whenComplete(StepListener.java:69)
        at org.elasticsearch.repositories.blobstore.testkit.BlobAnalyzeAction$BlobAnalysis.run(BlobAnalyzeAction.java:284)
        at org.elasticsearch.repositories.blobstore.testkit.BlobAnalyzeAction$TransportAction.doExecute(BlobAnalyzeAction.java:188)
        at org.elasticsearch.repositories.blobstore.testkit.BlobAnalyzeAction$TransportAction.doExecute(BlobAnalyzeAction.java:158)
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:77)
        at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:42)
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:75)
        at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.apply(SecurityActionFilter.java:122)
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:75)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:53)
        at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:53)
        at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:49)
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:232)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:295)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:61)
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:793)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:728)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

We rename the file shortly after creation, and I suspect it fails here because something outside Elasticsearch is also opening the file and holding it open while we try and rename it. I'll try and find someone to help investigate that possibility.

**Comment by DaveCTurner** [comment]
Ah.

```
        at org.elasticsearch.repositories.blobstore.testkit.BlobAnalyzeAction$BlobAnalysis.run(BlobAnalyzeAction.java:284)
```

We are overwriting this file, but reads happen concurrently with overwrites.

**Comment by nik9000** [comment]
[Here](https://gradle-enterprise.elastic.co/s/ptdu7tpg6jo5w) is a failure that is *probably* a duplicate.

**Comment by DaveCTurner** [comment]
Thanks Nik, yes that looks like more of the same. #70483 will fix this.
