### ISSUE TITLE
[CI] URLBlobContainerRetriesTests#testReadRangeBlobWithRetries() test failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#70310]
**Build scan**: https://gradle-enterprise.elastic.co/s/nydnir3ajjr5y
 
**Repro line**: `./gradlew ':modules:repository-url:test' --tests "org.elasticsearch.common.blobstore.url.URLBlobContainerRetriesTests.testReadRangeBlobWithRetries" -Dtests.seed=51C00D856CE5B95B -Dtests.security.manager=true -Dtests.locale=th -Dtests.timezone=America/Coral_Harbour -Druntime.java=8`

**Reproduces locally?**: Yes

**Applicable branches**: master, 7.x

**Failure history**: https://build-stats.elastic.co/goto/336577a2ea190cd0a40a88696ec86ff2
(at least once a day since 8th of March)

**Failure excerpt**:

```
org.elasticsearch.common.blobstore.url.URLBlobContainerRetriesTests > testReadRangeBlobWithRetries FAILED |  
-- | --
  | java.net.SocketTimeoutException: Read timed out |  
  | at __randomizedtesting.SeedInfo.seed([51C00D856CE5B95B:84BAE3D8E3575494]:0) |  
  | at java.net.SocketInputStream.socketRead0(Native Method) |  
  | at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) |  
  | at java.net.SocketInputStream.read(SocketInputStream.java:171) |  
  | at java.net.SocketInputStream.read(SocketInputStream.java:141) |  
  | at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) |  
  | at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) |  
  | at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:205) |  
  | at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176) |  
  | at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:198) |  
  | at org.apache.http.impl.io.ContentLengthInputStream.close(ContentLengthInputStream.java:101) |  
  | at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:142) |  
  | at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228) |  
  | at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172) |  
  | at java.io.FilterInputStream.close(FilterInputStream.java:181) |  
  | at org.elasticsearch.common.blobstore.url.http.HttpResponseInputStream.close(HttpResponseInputStream.java:34) |  
  | at org.elasticsearch.common.blobstore.url.http.RetryingHttpInputStream.close(RetryingHttpInputStream.java:129) |  
  | at org.elasticsearch.common.io.Streams$LimitedInputStream.close(Streams.java:353) |  
  | at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:74) |  
  | at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:116) |  
  | at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:87) |  
  | at org.elasticsearch.core.internal.io.Streams.copy(Streams.java:57) |  
  | at org.elasticsearch.core.internal.io.Streams.copy(Streams.java:80) |  
  | at org.elasticsearch.common.io.Streams.readFully(Streams.java:243) |  
  | at org.elasticsearch.repositories.blobstore.AbstractBlobContainerRetriesTestCase.testReadRangeBlobWithRetries(AbstractBlobContainerRetriesTestCase.java:201)
```

**Comment by davidkyle** [comment]
This test is failing in a number of interesting ways

https://gradle-enterprise.elastic.co/s/zqkttl24a3r2i
```
java.lang.IllegalArgumentException: end must be >= start and not Long.MAX_VALUE
	at __randomizedtesting.SeedInfo.seed([F649E4A33BB6B5B9:23330AFEB4045876]:0)
	at org.elasticsearch.common.blobstore.url.http.RetryingHttpInputStream.<init>(RetryingHttpInputStream.java:63)
	at org.elasticsearch.common.blobstore.url.http.HttpURLBlobContainer.readBlob(HttpURLBlobContainer.java:41)
	at org.elasticsearch.repositories.blobstore.AbstractBlobContainerRetriesTestCase.testReadRangeBlobWithRetries(AbstractBlobContainerRetriesTestCase.java:190)
```


https://gradle-enterprise.elastic.co/s/gds6tfvm6e5w4
```
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 248; received: 232)
	at __randomizedtesting.SeedInfo.seed([8AA4D16F125CFDC0:8891005B7FA8B56C]:0)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:198)
	at org.apache.http.impl.io.ContentLengthInputStream.close(ContentLengthInputStream.java:101)
	at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:142)
	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)
	at java.base/java.io.FilterInputStream.close(FilterInputStream.java:180)
	at org.elasticsearch.common.blobstore.url.http.HttpResponseInputStream.close(HttpResponseInputStream.java:34)
	at org.elasticsearch.common.blobstore.url.http.RetryingHttpInputStream.close(RetryingHttpInputStream.java:129)
	at org.elasticsearch.common.io.Streams$LimitedInputStream.close(Streams.java:353)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:74)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:116)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:87)
	at org.elasticsearch.core.internal.io.Streams.copy(Streams.java:54)
	at org.elasticsearch.core.internal.io.Streams.copy(Streams.java:77)
	at org.elasticsearch.common.io.Streams.readFully(Streams.java:243)
	at org.elasticsearch.repositories.blobstore.AbstractBlobContainerRetriesTestCase.testReadBlobWithRetries(AbstractBlobContainerRetriesTestCase.java:141)
```

**Comment by davidkyle** [comment]
Muted on master #70374 and 7.x #70377
