### ISSUE TITLE
Unknown codebases [codebase.jna]

### ISSUE THREAD

**Issue by jurajlutter** [elastic/elasticsearch#70342]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.11.2

**Plugins installed**: []

**JVM version** (`java -version`): openjdk version "11.0.10" 2021-01-19

**OS version** (`uname -a` if on a Unix-like system): FreeBSD 13.0-ALPHA3 amd64

**Description of the problem including expected versus actual behavior**:

While updating port of elasticsearch7 to 7.11.2, I am getting:
```
[2021-03-11T23:44:15,225][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [b13.owbuild.lan] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Unknown codebases [codebase.jna] in policy file [jar:file:/usr/local/lib/elasticsearch/lib/elasticsearch-7.11.2.jar!/org/elasticsearch/bootstrap/security.policy]
```

JNA is 5.7.0

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Startup elasticsearch

**Provide logs (if relevant)**:

```
Caused by: java.lang.IllegalArgumentException: Unknown codebases [codebase.jna] in policy file [jar:file:/usr/local/lib/elasticsearch/lib/elasticsearch-7.11.2.jar!/org/elasticsearch/bootstrap/security.policy]
Available codebases: [codebase.lucene-backward-codecs-8.7.0.jar, codebase.lucene-highlighter-8.7.0.jar, codebase.lucene-grouping, codebase.t-digest-3.2.jar, codebase.joda-time, codebase.lucene-core-8.7.0.jar, codebase.lucene-queryparser-8.7.0.jar, codebase.lucene-backward-codecs, codebase.lucene-spatial3d-8.7.0.jar, codebase.elasticsearch-geo, codebase.lucene-suggest-8.7.0.jar, codebase.elasticsearch-geo-7.11.2.jar, codebase.lucene-join-8.7.0.jar, codebase.java-version-checker-7.11.2.jar, codebase.lucene-highlighter, codebase.log4j-api-2.11.1.jar, codebase.elasticsearch-core-7.11.2.jar, codebase.lucene-memory, codebase.lucene-grouping-8.7.0.jar, codebase.jopt-simple, codebase.jts-core, codebase.elasticsearch-core, codebase.elasticsearch-launchers-7.11.2.jar, codebase.elasticsearch-x-content-7.11.2.jar, codebase.lucene-queries-8.7.0.jar, codebase.hppc, codebase.hppc-0.8.1.jar, codebase.elasticsearch-secure-sm-7.11.2.jar, codebase.spatial4j-0.7.jar, codebase.lucene-join, codebase.log4j-api, codebase.lucene-misc-8.7.0.jar, codebase.jackson-dataformat-cbor, codebase.HdrHistogram, codebase.spatial4j, codebase.java-version-checker, codebase.lucene-core, codebase.snakeyaml-1.26.jar, codebase.log4j-core-2.11.1.jar, codebase.elasticsearch, codebase.elasticsearch-cli-7.11.2.jar, codebase.lucene-analyzers-common-8.7.0.jar, codebase.elasticsearch-plugin-classloader-7.11.2.jar, codebase.snakeyaml, codebase.jackson-dataformat-yaml-2.10.4.jar, codebase.joda-time-2.10.4.jar, codebase.HdrHistogram-2.1.9.jar, codebase.t-digest, codebase.lucene-sandbox-8.7.0.jar, codebase.lucene-analyzers-common, codebase.jackson-dataformat-cbor-2.10.4.jar, codebase.elasticsearch-7.11.2.jar, codebase.lucene-spatial-extras, codebase.lucene-queryparser, codebase.jts-core-1.15.0.jar, codebase.jackson-core-2.10.4.jar, codebase.elasticsearch-x-content, codebase.elasticsearch-cli, codebase.jackson-dataformat-yaml, codebase.jna.jar, codebase.elasticsearch-secure-sm, codebase.lucene-memory-8.7.0.jar, codebase.jackson-core, codebase.log4j-core, codebase.lucene-queries, codebase.elasticsearch-launchers, codebase.lucene-sandbox, codebase.elasticsearch-plugin-classloader, codebase.lucene-suggest, codebase.jopt-simple-5.0.2.jar, codebase.jackson-dataformat-smile, codebase.lucene-misc, codebase.lucene-spatial3d, codebase.jackson-dataformat-smile-2.10.4.jar, codebase.lucene-spatial-extras-8.7.0.jar]
        at org.elasticsearch.bootstrap.PolicyUtil.readPolicy(PolicyUtil.java:261) ~[elasticsearch-7.11.2.jar:7.11.2]
        at org.elasticsearch.bootstrap.ESPolicy.<init>(ESPolicy.java:44) ~[elasticsearch-7.11.2.jar:7.11.2]
        at org.elasticsearch.bootstrap.Security.configure(Security.java:105) ~[elasticsearch-7.11.2.jar:7.11.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:211) ~[elasticsearch-7.11.2.jar:7.11.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:387) ~[elasticsearch-7.11.2.jar:7.11.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.11.2.jar:7.11.2]
        ... 6 more
```

**Comment by jurajlutter** [comment]
The problem has been found in `server/src/main/java/org/elasticsearch/bootstrap/PolicyUtil.java` at line 243:

```
String aliasProperty = "codebase." + name.replaceFirst("-\\d+\\.\\d+.*\\.jar", "");
```

This only works for versioned libraries. With `"(-\\d+\\.\\d+.*)?\\.jar"` it works for both versioned and unversioned .jar files.

**Comment by rjernst** [comment]
> OS version (uname -a if on a Unix-like system): FreeBSD 13.0-ALPHA3 amd64
> While updating port of elasticsearch7

It seems like you are trying to build an unofficial version of Elasticsearch on an unsupported platform. It looks like that build is missing pieces critical to its internal function. In particular, `jna` is a versioned lib included with Elasticsearch, yet your build seems to contain `jna.jar`, as indicated by `codebase.jna.jar` in the available codebases.

We expect all of our jar files to be versioned, so there is no reason to be lenient here. Doing so would require additional tests for a scenario that is not possible given our build requirements. Since this is not a problem with official builds, I hope you don't mind I close this issue.

**Comment by jurajlutter** [comment]
Just for completeness, I am not building any unofficial versions, just using the released ones. Anyway, thanks for explanation.

**Comment by rjernst** [comment]
@jurajlutter If there is a problem with an official release of Elasticsearch we are happy investigate. But we don't make any releases for FreeBSD, so this is in combination with your mention of updating a port, I thought you were building your own. Can you clarify if you are using a download from elastic.co?
