### ISSUE TITLE
[CI] TransformIndexerFailureHandlingTests.testPageSizeAdapt

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#70371]
**Build scan**:
https://gradle-enterprise.elastic.co/s/ekmjd2ixw7wis

**Repro line**:
```
./gradlew ':x-pack:plugin:transform:test' --tests "org.elasticsearch.xpack.transform.transforms.TransformIndexerFailureHandlingTests.testPageSizeAdapt" \
  -Dtests.seed=F700C62C08F961FE \
  -Dtests.security.manager=true \
  -Dtests.locale=en \
  -Dtests.timezone=Asia/Oral \
  -Druntime.java=11
```

**Reproduces locally?**:
No

**Applicable branches**:
8, 7.x

**Failure history**:
Regularly 

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(stacktrace,branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:TransformIndexerFailureHandlingTests),sort:!(time,desc))

**Failure excerpt**:
```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([F700C62C08F961FE:BF7C61AA90BE9301]:0)
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.elasticsearch.xpack.transform.transforms.TransformIndexerFailureHandlingTests.testPageSizeAdapt(TransformIndexerFailureHandlingTests.java:339)
```

**Comment by davidkyle** [comment]
Duplicate of #70297. Closing
