### ISSUE TITLE
[CI] FrozenIndexInputTests.testRandomReads failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#70482]
Failure: https://gradle-enterprise.elastic.co/s/miyqc2n7qypv2/tests/:x-pack:plugin:searchable-snapshots:test/org.elasticsearch.index.store.cache.FrozenIndexInputTests/testRandomReads

This test is failing when using ".cfs" files.

```
java.lang.AssertionError: org.elasticsearch.common.util.concurrent.UncategorizedExecutionException: Failed execution |  
-- | --
  | at __randomizedtesting.SeedInfo.seed([DD91E403E76CF8D0]:0) |  
  | at org.elasticsearch.common.lucene.store.ESIndexInputTestCase$1.onFailure(ESIndexInputTestCase.java:113) |  
  | at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:716) |  
  | at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:28) |  
  | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) |  
  | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) |  
  | at java.base/java.lang.Thread.run(Thread.java:834) |  
  | Caused by: org.elasticsearch.common.util.concurrent.UncategorizedExecutionException: Failed execution |  
  | at org.elasticsearch.common.util.concurrent.FutureUtils.rethrowExecutionException(FutureUtils.java:80) |  
  | at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:50) |  
  | at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:26) |  
  | at org.elasticsearch.common.lucene.store.ESIndexInputTestCase.randomReadAndSlice(ESIndexInputTestCase.java:167) |  
  | at org.elasticsearch.common.lucene.store.ESIndexInputTestCase.lambda$randomReadAndSlice$0(ESIndexInputTestCase.java:166) |  
  | at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:434) |  
  | at org.elasticsearch.common.lucene.store.ESIndexInputTestCase.randomReadAndSlice(ESIndexInputTestCase.java:166) |  
  | at org.elasticsearch.common.lucene.store.ESIndexInputTestCase.lambda$randomReadAndSlice$0(ESIndexInputTestCase.java:166) |  
  | at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:434) |  
  | at org.elasticsearch.common.lucene.store.ESIndexInputTestCase.randomReadAndSlice(ESIndexInputTestCase.java:166) |  
  | at org.elasticsearch.common.lucene.store.ESIndexInputTestCase.lambda$randomReadAndSlice$0(ESIndexInputTestCase.java:166) |  
  | at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:434) |  
  | at org.elasticsearch.common.lucene.store.ESIndexInputTestCase.randomReadAndSlice(ESIndexInputTestCase.java:166) |  
  | at org.elasticsearch.common.lucene.store.ESIndexInputTestCase$1.doRun(ESIndexInputTestCase.java:131) |  
  | at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:728) |  
  | at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) |  
  | ... 3 more |  
  | Caused by: java.util.concurrent.ExecutionException: java.io.IOException: failed to read data from cache |  
  | at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:262) |  
  | at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:249) |  
  | at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:76) |  
  | at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:45) |  
  | ... 17 more |  
  | Caused by: java.io.IOException: failed to read data from cache |  
  | at org.elasticsearch.index.store.cache.FrozenIndexInput.readDirectlyIfAlreadyClosed(FrozenIndexInput.java:470) |  
  | at org.elasticsearch.index.store.cache.FrozenIndexInput.doReadInternal(FrozenIndexInput.java:344) |  
  | at org.elasticsearch.index.store.BaseSearchableSnapshotIndexInput.readInternal(BaseSearchableSnapshotIndexInput.java:103) |  
  | at org.apache.lucene.store.BufferedIndexInput.refill(BufferedIndexInput.java:315) |  
  | at org.apache.lucene.store.BufferedIndexInput.readBytes(BufferedIndexInput.java:133) |  
  | at org.apache.lucene.store.BufferedIndexInput.readBytes(BufferedIndexInput.java:111) |  
  | at org.elasticsearch.common.lucene.store.ESIndexInputTestCase.randomReadAndSlice(ESIndexInputTestCase.java:68) |  
  | at org.elasticsearch.common.lucene.store.ESIndexInputTestCase.randomReadAndSlice(ESIndexInputTestCase.java:93) |  
  | at org.elasticsearch.common.lucene.store.ESIndexInputTestCase.lambda$randomReadAndSlice$0(ESIndexInputTestCase.java:166) |  
  | at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:434) |  
  | at org.elasticsearch.common.lucene.store.ESIndexInputTestCase.randomReadAndSlice(ESIndexInputTestCase.java:166) |  
  | ... 15 more |  
  | Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: invalid range [ByteRange [5865-6889], length=2592] |  
  | at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.getValue(BaseFuture.java:262) |  
  | at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:249) |  
  | at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:76) |  
  | at org.elasticsearch.index.store.cache.FrozenIndexInput.doReadInternal(FrozenIndexInput.java:182) |  
  | ... 24 more |  
  | Caused by: java.lang.IllegalArgumentException: invalid range [ByteRange [5865-6889], length=2592] |  
  | at org.elasticsearch.index.store.cache.SparseFileTracker.waitForRangeIfPending(SparseFileTracker.java:288) |  
  | at org.elasticsearch.xpack.searchablesnapshots.cache.FrozenCacheService$CacheFileRegion.readIfAvailableOrPending(FrozenCacheService.java:701) |  
  | at org.elasticsearch.xpack.searchablesnapshots.cache.FrozenCacheService$FrozenCacheFile.readIfAvailableOrPending(FrozenCacheService.java:831) |  
  | at org.elasticsearch.index.store.cache.FrozenIndexInput.doReadInternal(FrozenIndexInput.java:172) |  
  | ... 24 more
```

**Comment by original-brownbear** [comment]
@ywelsch looks like an instance of https://github.com/elastic/elasticsearch/pull/70408#discussion_r595414291 ?

**Comment by ywelsch** [comment]
> @ywelsch looks like an instance of #70408 (comment) ?

Correct. I'm not happy with just disabling the cfs logic everywhere in the tests. Ideally we can fix this by making `randomReadAndSlice` more aware of which regions it's actually allowed to access.

**Comment by original-brownbear** [comment]
> Ideally we can fix this by making randomReadAndSlice more aware of which regions it's actually allowed to access.

++ I'll look into that then I can remove the hack from my PR as well :)
