### ISSUE TITLE
Windows packaging plugin CLI test failure

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#70496]
**Build scan**: https://gradle-enterprise.elastic.co/s/aohhswsfxzera

**Repro line**: None logged

**Reproduces locally?**: No windows

**Applicable branches**: 7.x

**Failure history**:
[Gradle enterprise](https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/New_York&tests.container=org.elasticsearch.packaging.test.PluginCliTests&tests.disabledDistributions=WyJvdXRjb21lOmZsYWt5Iiwib3V0Y29tZTpwYXNzZWQiLCJvdXRjb21lOnNraXBwZWQiXQ&tests.sortField=FAILED&tests.test=test20SymlinkPluginsDir&tests.unstableOnly=true) says there are some non-windows failures 
[Build stats](https://build-stats.elastic.co/goto/853a11927364792f55ba10f354d8a2cc0) hasn't seen it this month either.

**Failure excerpt**:
Looks like we timed out while starting ES. Then lots of other exceptions happened because windows couldn't remove files. I think its safe to ignore those ones....
```
00:48:17     java.lang.RuntimeException: Command was not successful: [powershell.exe -Command $processInfo = New-Object System.Diagnostics.ProcessStartInfo; $processInfo.FileName = 'C:\tmp\elasticsearch\bin\elasticsearch.bat'; $processInfo.Arguments = '-p C:\tmp\elasticsearch\elasticsearch.pid'; $processInfo.RedirectStandardOutput = $true; $processInfo.RedirectStandardError = $true; $processInfo.RedirectStandardInput = $true; $processInfo.Environment.Add('ES_JAVA_HOME', 'C:\Users\jenkins\.java\java8'); $processInfo.UseShellExecute = $false; $process = New-Object System.Diagnostics.Process; $process.StartInfo = $processInfo; $outScript = { $EventArgs.Data | Out-File -Encoding UTF8 -Append 'C:\tmp\elasticsearch\logs\output.out' }; $errScript = { $EventArgs.Data | Out-File -Encoding UTF8 -Append 'C:\tmp\elasticsearch\logs\output.err' }; $stdOutEvent = Register-ObjectEvent -InputObject $process -Action $outScript -EventName 'OutputDataReceived'; $stdErrEvent = Register-ObjectEvent -InputObject $process -Action $errScript -EventName 'ErrorDataReceived'; $process.Start() | Out-Null; $process.BeginOutputReadLine(); $process.BeginErrorReadLine(); $process.StandardInput.WriteLine('null'); Wait-Process -Timeout 10 -Id $process.Id; $process.Id;]
00:48:17        result: exitCode = [1] stdout = [6032] stderr = [Wait-Process : This command stopped operation because process "cmd (6032)" is not stopped in the specified time-out.
00:48:17     At line:1 char:1106
00:48:17     + ... t.WriteLine('null'); Wait-Process -Timeout 10 -Id $process.Id; $proce ...
00:48:17     +                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
00:48:17         + CategoryInfo          : CloseError: (System.Diagnostics.Process (cmd):Process) [Wait-Process], TimeoutException
00:48:17         + FullyQualifiedErrorId : ProcessNotTerminated,Microsoft.PowerShell.Commands.WaitProcessCommand]
00:48:17         at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:147)
00:48:17         at org.elasticsearch.packaging.util.Shell.run(Shell.java:73)
00:48:17         at org.elasticsearch.packaging.util.Archives.runElasticsearchStartCommand(Archives.java:318)
00:48:17         at org.elasticsearch.packaging.test.PackagingTestCase.runElasticsearchStartCommand(PackagingTestCase.java:296)
00:48:17         at org.elasticsearch.packaging.test.PackagingTestCase.assertWhileRunning(PackagingTestCase.java:245)
00:48:17         at org.elasticsearch.packaging.test.PluginCliTests.lambda$test20SymlinkPluginsDir$2(PluginCliTests.java:71)
```

**Comment by mark-vieira** [comment]
Closing, as this is a super old test failure that's no longer happening.
