### ISSUE TITLE
yaml test suite times out in 6.8 mac frequently

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#70503]
**Build scan**:
https://gradle-enterprise.elastic.co/s/ait4ttorj4ypu

**Repro line**:
```
./gradlew ':distribution:archives:integ-test-zip:integTestRunner' 
```

**Reproduces locally?**: don't have a mac

**Applicable branches**: 6.8 - mac only

**Failure history**:
![image](https://user-images.githubusercontent.com/215970/111485818-55476900-870d-11eb-8857-d0d34f281a9e.png)

https://build-stats.elastic.co/goto/676c786f4f735b740b4a90dcfdb8a1e1

Happened a dozen times this year. But we typically only run the suite once a day. So proportionally that is quite high.

**Failure excerpt**:
```
21:58:01   1> [2021-03-17T09:57:41,685][INFO ][o.e.t.r.IntegTestZipClientYamlTestSuiteIT] [test] [p0=indices.stats/13_fields/Completion fields - star] after test
21:58:01   1> [2021-03-17T09:57:41,688][INFO ][o.e.t.r.IntegTestZipClientYamlTestSuiteIT] [test] [p0=search/160_exists_query/Test exists query on _type field] before test
21:58:01   1> [2021-03-17T09:57:48,529][WARN ][o.e.c.RestClient         ] [[I/O dispatcher 73]] request [PUT http://[::1]:62023/test?error_trace=true] returned 2 warnings: [299 Elasticsearch-6.8.15-SNAPSHOT-c9a8c60 "the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you must manage this on the create index request or with an index template"],[299 Elasticsearch-6.8.15-SNAPSHOT-c9a8c60 "[types removal] The parameter include_type_name should be explicitly specified in create index requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', and requests are expected to omit the type name in mapping definitions."]
21:58:01   2> Mar 17, 2021 9:57:48 AM com.carrotsearch.randomizedtesting.ThreadLeakControl$2 evaluate
21:58:01   2> WARNING: Suite execution timed out: org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT
21:58:01   2> ==== jstack at approximately timeout time ====
21:58:01   2> "I/O dispatcher 96" ID=124 RUNNABLE (in native code)
21:58:01   2> 	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
21:58:01   2> 	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
21:58:01   2> 	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
21:58:01   2> 	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
21:58:01   2> 	- locked sun.nio.ch.Util$3@66d7e4b7
```

**Comment by dnhatn** [comment]
Another instance: https://gradle-enterprise.elastic.co/s/kapurxzptmosc

**Comment by mark-vieira** [comment]
Darwin CI jobs have been removed.
