### ISSUE TITLE
[CI] GetTransformStatsActionResponseTests testSchema failing on Windows

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#70532]
The newly added schema valiation tests seem to fail on Windows. This is most likely a path encoding issue. `TransformConfigTests` fails with the same error.

**Build scan**:
https://gradle-enterprise.elastic.co/s/3gvkhwm3ovx3g/tests/:x-pack:plugin:core:test/org.elasticsearch.xpack.core.transform.action.schema.GetTransformStatsActionResponseTests/testSchema#1

**Repro line**:
`gradlew ':x-pack:plugin:core:test' --tests "org.elasticsearch.xpack.core.transform.action.schema.GetTransformStatsActionResponseTests.testSchema" -Dtests.seed=F25A50E4F92F16CE -Dtests.security.manager=true -Dtests.locale=zh-Hant-HK -Dtests.timezone=America/St_Vincent -Druntime.java=11`

**Reproduces locally?**:
Didn't try but I suspect it would on a Windows machine.

**Applicable branches**:
master

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.tags=windows&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.xpack.core.transform.action.schema.GetTransformStatsActionResponseTests&tests.sortField=FAILED&tests.test=testSchema&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.xpack.core.transform.action.schema.GetTransformStatsActionResponseTests > testSchema FAILED
    java.lang.RuntimeException: resource not found: \rest-api-spec\schema\transform.get_transform_stats.schema.json
        at __randomizedtesting.SeedInfo.seed([F25A50E4F92F16CE:81477AB15914E49D]:0)
        at org.elasticsearch.test.ESTestCase.getDataPath(ESTestCase.java:1036)
        at org.elasticsearch.test.AbstractSchemaValidationTestCase.testSchema(AbstractSchemaValidationTestCase.java:51)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
        at java.base/java.lang.Thread.run(Thread.java:834)

        Caused by:
        java.lang.NullPointerException
            at org.elasticsearch.test.ESTestCase.getDataPath(ESTestCase.java:1034)
            ... 38 more
```

**Comment by williamrandolph** [comment]
We're using a filesystem-specific concatenation method to construct a "resource path." This works on unix-like filesystems because of forward slashes, but breaks on windows. I've got a PR that might work.

**Comment by mark-vieira** [comment]
Thanks for the mute. I should have done so when I initially opened this issue given it fails 100% of the time on Windows. That's on me.
