### ISSUE TITLE
Elasticsearch fails to start with quota-aware-fs plugin configured on Windows with JDK 16

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#70583]
When bumping the bundled JDK to 16 I encountered this failing test: https://gradle-enterprise.elastic.co/s/gicuru3wr4nn4/tests/:qa:os:destructiveDistroTest.default-windows-archive/org.elasticsearch.packaging.test.QuotaAwareFsTests/test30ElasticsearchStartsWhenSystemPropertySet#1

The underlying error thrown by Elasticsearch on start is this:
```
[2021-03-18T11:50:07,992][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [MARK-PC] fatal error in thread [main], exiting
java.lang.ExceptionInInitializerError: null
        at sun.nio.ch.SelectorProviderImpl.openServerSocketChannel(SelectorProviderImpl.java:101) ~[?:?]
        at java.nio.channels.ServerSocketChannel.open(ServerSocketChannel.java:175) ~[?:?]
        at sun.nio.ch.PipeImpl.createListener(PipeImpl.java:220) ~[?:?]
        at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(PipeImpl.java:125) ~[?:?]
        at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:83) ~[?:?]
        at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:67) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:554) ~[?:?]
        at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:194) ~[?:?]
        at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:143) ~[?:?]
        at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:173) ~[?:?]
        at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:142) ~[?:?]
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:146) ~[?:?]
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:37) ~[?:?]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[?:?]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) ~[?:?]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47) ~[?:?]
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59) ~[?:?]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:86) ~[?:?]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:81) ~[?:?]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:68) ~[?:?]
        at org.elasticsearch.transport.SharedGroupFactory.getGenericGroup(SharedGroupFactory.java:78) ~[?:?]
        at org.elasticsearch.transport.SharedGroupFactory.getTransportGroup(SharedGroupFactory.java:59) ~[?:?]
        at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:115) ~[?:?]
        at org.elasticsearch.xpack.core.security.transport.netty4.SecurityNetty4Transport.doStart(SecurityNetty4Transport.java:85) ~[?:?]
        at org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4ServerTransport.doStart(SecurityNetty4ServerTransport.java:47) ~[?:?]
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.transport.TransportService.doStart(TransportService.java:220) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.node.Node.start(Node.java:821) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:306) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:389) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116) ~[elasticsearch-cli-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.cli.Command.main(Command.java:79) ~[elasticsearch-cli-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
Caused by: java.lang.IllegalArgumentException
        at java.net.UnixDomainSocketAddress.of(UnixDomainSocketAddress.java:167) ~[?:?]
        at java.net.UnixDomainSocketAddress.of(UnixDomainSocketAddress.java:145) ~[?:?]
        at sun.nio.ch.UnixDomainSockets.<clinit>(UnixDomainSockets.java:47) ~[?:?]
        ... 39 more
fatal error in thread [main], exiting
java.lang.ExceptionInInitializerError
        at java.base/sun.nio.ch.SelectorProviderImpl.openServerSocketChannel(SelectorProviderImpl.java:101)
        at java.base/java.nio.channels.ServerSocketChannel.open(ServerSocketChannel.java:175)
        at java.base/sun.nio.ch.PipeImpl.createListener(PipeImpl.java:220)
        at java.base/sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(PipeImpl.java:125)
        at java.base/sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:83)
        at java.base/sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:67)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
        at java.base/sun.nio.ch.PipeImpl.<init>(PipeImpl.java:194)
        at java.base/sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:143)
        at java.base/sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44)
        at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:173)
        at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:142)
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:146)
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:37)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:86)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:81)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:68)
        at org.elasticsearch.transport.SharedGroupFactory.getGenericGroup(SharedGroupFactory.java:78)
        at org.elasticsearch.transport.SharedGroupFactory.getTransportGroup(SharedGroupFactory.java:59)
        at org.elasticsearch.transport.netty4.Netty4Transport.doStart(Netty4Transport.java:115)
        at org.elasticsearch.xpack.core.security.transport.netty4.SecurityNetty4Transport.doStart(SecurityNetty4Transport.java:85)
        at org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4ServerTransport.doStart(SecurityNetty4ServerTransport.java:47)
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48)
        at org.elasticsearch.transport.TransportService.doStart(TransportService.java:220)
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48)
        at org.elasticsearch.node.Node.start(Node.java:821)
        at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:306)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:389)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
        at org.elasticsearch.cli.Command.main(Command.java:79)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81)
Caused by: java.lang.IllegalArgumentException
        at java.base/java.net.UnixDomainSocketAddress.of(UnixDomainSocketAddress.java:167)
        at java.base/java.net.UnixDomainSocketAddress.of(UnixDomainSocketAddress.java:145)
        at java.base/sun.nio.ch.UnixDomainSockets.<clinit>(UnixDomainSockets.java:47)
        ... 39 more
```

This is indeed an issue I was able to reproduce on Windows. Follow these steps:

1. Get on a Windows machine... sorry
2. Build Elasticsearch
    ```
    gradlew.bat localDistro
    ```
3. Install the quota-aware-fs plugin
    ```
    gradlew.bat :x-pack:quota-aware-fs:assemble
    cd build\distribution\local\elasticsearch-8.0.0-SNAPSHOT
    .\bin\elasticsearch-plugin.bat install file:///<path to plugin zip>
    ```
4. Create a quota.properties file
5. Configure the system property
    ```
    set ES_JAVA_OPTS=-Des.fs.quota.file=file:///C:/path/to/quota.properties
    ```
6. Start ES with Java 16
    ```
    set ES_JAVA_HOME=C:\path\to\jdk16
    .\bin\elasticsearch.bat
    ```

**Comment by rjernst** [comment]
I invested this last week and found a change inside JDK 16 that at least partially explains the failure, though not completely.

In JDK 16 a new internal class, UnixDomainSocketAddress (as seen in the stack trace above) was added. This file appears to only be used on Windows. There is a static empty path in `UnixDomainSockets` that is initialized (indirectly, when we start initializing netty). The static `of` method on `UnixDomainSocketAddress` has a hard check on the filesystem of the `Path` being used.

```
 if (fs != FileSystems.getDefault()) {
    throw new IllegalArgumentException();
}
``` 

That is, it checks that the file system of the path for the socket must be the same as the default filesystem. This at least explains where the `IllegalArgumentException` without a message comes from.

What I still do not understand is why this trips at all. The `quota-aware-fs` plugin overrides the default filesystem on startup, so `FileSystems.getDefault()` should always require the `QuotaAwareFileSystem`. Furthermore, the stack indicates we are calling the `of` [method](https://github.com/openjdk/jdk/blob/fdd3941121aad3975c7b448bb11e50f9943b7af7/src/java.base/share/classes/java/net/UnixDomainSocketAddress.java#L145) with this check through the other one which takes a `String` and calls `Path.of` inline, *which also uses the default filesystem`. So it seems impossible the FileSystem returned by `Path.of` could have a different `FileSystem` than the default.

Separately, I wonder if we should worry about this at all. I don't believe we ever intended to support `quota-aware-fs` outside of Cloud.

**Comment by mark-vieira** [comment]
Given this is blocking the upgrade of our bundled JDK we need to make a decision on this. Either a) we update the docs to say this plugin is not supported on Windows,  b) remove docs for this plugin altogether given it's meant only for cloud, or c) find a workaround.

**Comment by bytebilly** [comment]
I analyzed our telemetry data and it shows that 100% of deployments using the `quota-aware-fs` plugin are ESS clusters (so using Linux). Telemetry is not covering any possible case, but it confirms our assumption that this plugin is very related to ESS deployments only.

I suggest that we:
- update the documentation mentioning that this plugin cannot work on Windows
- bundle JDK16 as soon as possible
- mention this in the breaking change section

I'd like to double check if there is a technical solution for it, but it seems we don't have one at the moment, and this should not slow down the adoption of the new JDK.

**Comment by mark-vieira** [comment]
@rjernst is there a way to actually _fail_ if the plugin is installed on Windows?

**Comment by rjernst** [comment]
No, unfortunately we don't have any capability for that right now.

**Comment by mark-vieira** [comment]
Ok. @rjernst can someone from your team please take on the documentation updates @bytebilly has suggested? At which point I can follow up with the bundled JDK bump.

**Comment by bytebilly** [comment]
@mark-vieira could the bump happening in a patch release? I'm unsure, given implications on our support policy and the compatibility matrix.

**Comment by mark-vieira** [comment]
> @mark-vieira could the bump happening in a patch release? I'm unsure, given implications on our support policy and the compatibility matrix.

Yes, it's a non-breaking change. We regularly bump the bundled JDK in patch releases to ensure folks are always on the latest possible.

**Comment by bytebilly** [comment]
Can we already state that we support JDK16 for 7.12.x in the [Support Matrix](https://www.elastic.co/support/matrix#matrix_jvm)? This is not related to what is bundled, and we don't differentiate by patch releases there.

Since we don't have any code change, but just doc updates, I'd like to proceed with the matrix update as soon as possible.

**Comment by mark-vieira** [comment]
I've updated the docs to indicate this plugin is cloud-only. I'll follow up on the PR to bump the bundled JDK as well. Since we don't plan to "fix" this on Windows I suspect we can close this issue? The only other action item might be to open a bug report against the JDK if this is indeed an issue.

**Comment by bytebilly** [comment]
I discussed with @rjernst yesterday and we will not proceed with any bug report against the JDK for now.

The other action item here is to update the Support Matrix to include JDK 16 in the table, I'll start the process today.

**Comment by pugnascotia** [comment]
We removed this plugin in #76352.
