### ISSUE TITLE
Machine learning jobs failing to start due to CNamePipeFactory.cc failing to create named pipes with glibc 2.33

### ISSUE THREAD

**Issue by Aqualie** [elastic/elasticsearch#70613]
**Elasticsearch version**:  7.11.2

**JVM version** : java 15+36-1562

**OS version**: Linux 5.10.15-arch1-1 #1 SMP PREEMPT Wed, 10 Feb 2021 18:32:40 +0000 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: Attempting to start any machine learning job after upgrading nodes to 7.11.x fails due to provided error below. This is not a new install FYI was working fine prior to the upgrade.

**Steps to reproduce**:

1. Browse to Kibana console
2. Navigate to **Analytics** -> **Machine Learning**
3. Click into **Manage Jobs**
4. Select any job and attempt to start it while reviewing the Logs
5. Errors will be emitted on the designated node and the job will fail to start

**Provide logs (if relevant)**:
```
[2021-03-21T15:27:46,864][INFO ][o.e.x.m.j.t.OpenJobPersistentTasksExecutor] [] [linux_anomalous_user_name_ecs] job has running datafeed task; reverting to current snapshot
[2021-03-21T15:27:59,063][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [] Opening job [linux_anomalous_user_name_ecs]
[2021-03-21T15:27:59,567][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [] [linux_anomalous_user_name_ecs] Loading model snapshot [1613242348] with latest_record_timestamp [2021-02-13T18:41:27.000Z], job latest_record_timestamp [2021-02-13T18:41:27.000Z]
[2021-03-21T15:27:59,569][INFO ][o.e.x.m.j.p.a.NativeAutodetectProcessFactory] [] Restoring quantiles for job 'linux_anomalous_user_name_ecs'
[2021-03-21T15:27:59,668][ERROR][o.e.x.m.p.l.CppLogMessageHandler] [] [linux_anomalous_user_name_ecs] [autodetect/56037] [CNamedPipeFactory.cc@238] Unable to create named pipe /tmp/autodetect_linux_anomalous_user_name_ecs_input_55581: Permission denied
[2021-03-21T15:27:59,669][FATAL][o.e.x.m.p.l.CppLogMessageHandler] [] [linux_anomalous_user_name_ecs] [autodetect/56037] [Main.cc@166] Failed to initialise IO
[2021-03-21T15:28:09,791][ERROR][o.e.x.m.j.p.a.NativeAutodetectProcessFactory] [] Failed to connect to autodetect for job linux_anomalous_user_name_ecs
[2021-03-21T15:28:17,088][WARN ][o.e.p.AllocatedPersistentTask] [] task job-linux_anomalous_user_name_ecs failed with an exception
org.elasticsearch.ElasticsearchException: Unable to create named pipe /tmp/autodetect_linux_anomalous_user_name_ecs_input_55581: Permission denied
Failed to initialise IO

        at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.serverError(ExceptionsHelper.java:53) ~[?:?]
        at org.elasticsearch.xpack.ml.process.AbstractNativeProcess.close(AbstractNativeProcess.java:200) ~[?:?]
        at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:74) ~[elasticsearch-core-7.11.2.jar:7.11.2]
        at org.elasticsearch.xpack.ml.job.process.autodetect.NativeAutodetectProcessFactory.createAutodetectProcess(NativeAutodetectProcessFactory.java:103) ~[?:?]
        at org.elasticsearch.xpack.ml.job.process.autodetect.AutodetectProcessFactory.createAutodetectProcess(AutodetectProcessFactory.java:34) ~[?:?]
        at org.elasticsearch.xpack.ml.job.process.autodetect.AutodetectProcessManager.create(AutodetectProcessManager.java:629) ~[?:?]
        at org.elasticsearch.xpack.ml.job.process.autodetect.AutodetectProcessManager.createProcessAndSetRunning(AutodetectProcessManager.java:580) ~[?:?]
        at org.elasticsearch.xpack.ml.job.process.autodetect.AutodetectProcessManager.access$200(AutodetectProcessManager.java:101) ~[?:?]
        at org.elasticsearch.xpack.ml.job.process.autodetect.AutodetectProcessManager$3.doRun(AutodetectProcessManager.java:526) ~[?:?]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732) ~[elasticsearch-7.11.2.jar:7.11.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-7.11.2.jar:7.11.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]

```
 **ls -lhta / | grep tmp && mount | grep \/tmp && ls -lhta /opt | grep elastic && ps -ef | grep elasticsearch | grep -v grep                                  /opt/elasticsearch**
```
drwxrwxrwt  16 root root  320 Mar 21 17:47 tmp
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,nr_inodes=409600,inode64)
drwxr-xr-x 10 elasticsearch elasticsearch 4.0K Mar 21 13:08 elasticsearch
elastic+   55581       1 61 13:13 ?        02:52:47 /usr/lib/jvm/java-15-jdk/bin/java -Xshare:auto -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -XX:+ShowCodeDetailsInExceptionMessages -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.numDirectArenas=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.locale.providers=SPI,COMPAT -Xms6g -Xmx6g -XX:+UseG1GC -Djava.io.tmpdir=/tmp -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -XX:ErrorFile=logs/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m -XX:MaxDirectMemorySize=3221225472 -XX:G1HeapRegionSize=4m -XX:InitiatingHeapOccupancyPercent=30 -XX:G1ReservePercent=15 -Des.path.home=/opt/elasticsearch -Des.path.conf=/opt/elasticsearch/config -Des.distribution.flavor=default -Des.distribution.type=tar -Des.bundled_jdk=true -cp /opt/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -p /var/run/elasticsearch/elasticsearch.pid --quiet
elastic+   55745   55581  0 13:13 ?        00:00:00 /opt/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller
```
**sudo -u elasticsearch mkfifo /tmp/1 && ls -lhta /tmp/1 && sudo rm /tmp/1**                                                                                   
`prw-r--r-- 1 elasticsearch elasticsearch 0 Mar 21 18:00 /tmp/1`

 **sudo cat /usr/lib/systemd/system/elasticsearch.service**                                                                                                    
 ```
[Unit]
Description=Elasticsearch
Documentation=http://www.elastic.co
Wants=elasticsearch-keystore.service
Wants=network.target
After=elasticsearch-keystore.service
After=network.target

[Service]
RuntimeDirectory=elasticsearch
PrivateTmp=true
Environment=JAVA_HOME=/usr/lib/jvm/java-15-jdk
Environment=ES_PATH_CONF=/opt/elasticsearch/config
Environment=ES_TMPDIR=/tmp
Environment=PID_DIR=/var/run/elasticsearch

WorkingDirectory=/opt/elasticsearch


User=elasticsearch
Group=elasticsearch

ExecStart=/opt/elasticsearch/bin/elasticsearch -p /var/run/elasticsearch/elasticsearch.pid --quiet

StandardOutput=journal
StandardError=inherit

LimitNOFILE=65536
LimitNPROC=4096
LimitAS=infinity
LimitFSIZE=infinity
LimitMEMLOCK=infinity

Restart=on-failure
KillMode=process
SendSIGKILL=no
TimeoutStopSec=0
SuccessExitStatus=143

[Install]
WantedBy=multi-user.target
```

**Comment by droberts195** [comment]
This is a very strange failure.

We connect 5 named pipes for the `autodetect` process, starting with the one that carries the log messages.  Usually if there's a problem it happens on that first one (for logs).  In your case it's happening on the second one (used for input).  So that means that the logging named pipe was created, opened and connected without any problems.

> This is not a new install FYI was working fine prior to the upgrade

Which version did you upgrade _from_?

The most likely reason why this is happening is that a system call filter is blocking connection of the named pipes other than the logging one.  In 7.11 the system call filter (installed for security hardening) gets installed in between - see: https://github.com/elastic/ml-cpp/blob/c4f821e5f79a9a717edea485200c6651a1bbed94/bin/autodetect/Main.cc#L147-L168

So I suspect either you upgraded from a version before we introduced system call filtering _or_ you upgraded your OS at the same time you upgraded Elasticsearch.

Arch Linux is not an officially supported Linux distribution, so this isn't a bug as such, but it's a canary in the mine for when a supported Linux distribution creates named pipes using the syscall that's getting blocked for you, so we'll fix it in an upcoming patch if you can help us figure out which syscall it is.

Do you see any messages that look anything like `auid=4294967295 uid=1000 gid=1000 ses=4294967295 pid=8859 comm="autodetect" reason="seccomp" sig=0 syscall=4 compat=0 ip=0x7f8ebb41b205 code=0x50000` in your `dmesg` output, or in `/var/log/messages` or `/var/log/syslog` or wherever else audit messages might be going to?  (Obviously the exact numbers will vary.) If so, what is the syscall number, i.e. the number after `syscall=`, i.e. 4 in my example message. We need to know that number to fix this.

**Comment by Aqualie** [comment]
This was previously upgraded from 7.10.2 and yes this was a full upgraded including the OS to 7.11.0 then subsequently to 7.11.2 for testing. Examining both dmesg and journalctl when I enable the ML job I do not see any new audit events emitted when the error is being printed in the log. Does this require a specific audit rule to monitor for these kind of syscalls ?

**Comment by droberts195** [comment]
> this was a full upgraded including the OS to 7.11.0

So did the ML jobs break at this point, or only when you subsequently upgraded to 7.11.2?

And which OS version were you running before the OS upgrade?

> Does this require a specific audit rule to monitor for these kind of syscalls ?

Possibly.  One way to do it might be:

```
auditctl -a always,exit -S all -F ppid=1234
```

where `1234` is the PID of the `controller` process.  So start Elasticsearch, use `ps -ef` to find the PID of `controller`, then `auditctl -a always,exit -S all -F ppid=<controller_pid>` and `service auditd restart`.  Then try to open an ML job to generate the permission denied error, check the auditd output to see which syscall got denied, then remove the rule.

**Comment by Aqualie** [comment]
They broke after upgrading to 7.11.0, I attempted to upgrade to 7.11.2 to see if there would be any difference. The previous linux kernel is 6.9.13.arch1-1.

Linked is the information generated by audit for the controller process during the error: https://pastebin.com/raw/AnUWQEXj

**Comment by droberts195** [comment]
> Linked is the information generated by audit for the controller process during the error: https://pastebin.com/raw/AnUWQEXj

Thanks.  I am pretty sure the missing syscall that we need to allow is `mknodat`.  Tomorrow I will open a PR to add that.

**Comment by Aqualie** [comment]
Great thank you.
