### ISSUE TITLE
[CI] SearchableSnapshotsRelocationIntegTests.testRelocationWaitsForPreWarm fails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#70627]
**Build scan**:

This PR test run: https://gradle-enterprise.elastic.co/s/3amvbmcuylppi
But also earlier runs on CI, e.g. https://gradle-enterprise.elastic.co/s/l7ezvyjdj4u5s

**Repro line**:

./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsRelocationIntegTests.testRelocationWaitsForPreWarm" -Dtests.seed=BB10EA14543E1244 -Dtests.security.manager=true -Dtests.locale=fr-FR -Dtests.timezone=Europe/Oslo -Druntime.java=11

**Reproduces locally?**:

Yes

**Applicable branches**:

master, some earlier failures on 7.x

**Failure history**:

Found three failures in Dec. 2020

**Failure excerpt**:

```
 java.lang.AssertionError:
    Expected: an empty collection
         but: <[org.elasticsearch.indices.recovery.RecoveryState@9038606]>
        at __randomizedtesting.SeedInfo.seed([BB10EA14543E1244:C4CC9B2A028D3DAA]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsRelocationIntegTests.lambda$testRelocationWaitsForPreWarm$3(SearchableSnapshotsRelocationIntegTests.java:114)
```

**Comment by ywelsch** [comment]
This looks related to #70311
