### ISSUE TITLE
[CI] SqlSearchIT.testAllTypesWithRequestToOldNodes

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#70630]
Failed on my [PR](https://github.com/elastic/elasticsearch/pull/70625) [build](https://gradle-enterprise.elastic.co/s/s37uaz6kmdgcg) but also failed in master recently.

**Build scan**:

https://gradle-enterprise.elastic.co/s/hoqkn3lwgygi4 (master)

**Repro line**:

./gradlew ':x-pack:plugin:sql:qa:mixed-node:v7.13.0#mixedClusterTest' -Dtests.class="org.elasticsearch.xpack.sql.qa.mixed_node.SqlSearchIT" -Dtests.method="testAllTypesWithRequestToOldNodes" -Dtests.seed=3E20E2CF16857C7 -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=pt-PT -Dtests.timezone=America/Argentina/San_Luis -Druntime.java=11

**Reproduces locally?**:

Yes

**Applicable branches**:

master

**Failure history**:
Started failing [this morning](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:sqlsearchit),sort:!(time,desc)))

**Failure excerpt**:

```
org.elasticsearch.xpack.sql.qa.mixed_node.SqlSearchIT > testAllTypesWithRequestToOldNodes FAILED
    org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:36439], URI [_sql], status line [HTTP/1.1 400 Bad Request]
    {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: The [8.0.0] version of the [jdbc] client is not compatible with Elasticsearch version [7.13.0];"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: The [8.0.0] version of the [jdbc] client is not compatible with Elasticsearch version [7.13.0];"},"status":400}
        at __randomizedtesting.SeedInfo.seed([3E20E2CF16857C7:62A3743F85E3B504]:0)
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:330)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
        at org.elasticsearch.xpack.sql.qa.mixed_node.SqlSearchIT.runSql(SqlSearchIT.java:267)
        at org.elasticsearch.xpack.sql.qa.mixed_node.SqlSearchIT.lambda$assertAllTypesWithNodes$21(SqlSearchIT.java:254)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:946)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:931)
        at org.elasticsearch.xpack.sql.qa.mixed_node.SqlSearchIT.assertAllTypesWithNodes(SqlSearchIT.java:254)
        at org.elasticsearch.xpack.sql.qa.mixed_node.SqlSearchIT.testAllTypesWithRequestToOldNodes(SqlSearchIT.java:122)
```

**Comment by henningandersen** [comment]
Muted in 45878e78394157a9ed1850d9ba09e81f055e49e4 (master)

**Comment by cbuescher** [comment]
Also a problem for me on 7.x, trying to get a PR in there atm so I will cherry-pick the muting to 7.x as well.
