### ISSUE TITLE
QuotaAwareFileSystemProviderTests#testRepeatedUpdate test failure

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#70680]
**Build scan**:
https://gradle-enterprise.elastic.co/s/eobmousepg4ca
**Repro line**:
```
 ant test  -Dtestcase=QuotaAwareFileSystemProviderTests -Dtests.method=testRepeatedUpdate -Dtests.seed=7C315DE53A4CAA6D -Dtests.slow=true -Dtests.badapples=true -Dtests.locale=ar-TN -Dtests.timezone=Europe/Samara -Dtests.asserts=true -Dtests.file.encoding=UTF-8
```
what is this...a test for ANTS?
**Reproduces locally?**:
?
**Applicable branches**:
master
**Failure history**:
This is the first failure in the last 30 days.
**Failure excerpt**:
```
org.elasticsearch.fs.quotaaware.QuotaAwareFileSystemProviderTests > testRepeatedUpdate FAILED
    java.lang.IllegalStateException: Retry timed out after [2000]ms
        at __randomizedtesting.SeedInfo.seed([7C315DE53A4CAA6D:991E72CA298ED1A4]:0)
        at org.elasticsearch.fs.quotaaware.QuotaAwareFileSystemProviderTests.withRetry(QuotaAwareFileSystemProviderTests.java:362)
        at org.elasticsearch.fs.quotaaware.QuotaAwareFileSystemProviderTests.testRepeatedUpdate(QuotaAwareFileSystemProviderTests.java:99)

        Caused by:
        java.lang.AssertionError: The quota aware filesystem has failed
            at org.elasticsearch.fs.quotaaware.QuotaAwareFileSystemProvider.ensureHealth(QuotaAwareFileSystemProvider.java:359)
            at org.elasticsearch.fs.quotaaware.QuotaAwareFileSystemProvider.getTotal(QuotaAwareFileSystemProvider.java:351)
            at org.elasticsearch.fs.quotaaware.QuotaAwareFileSystemProviderTests.lambda$testRepeatedUpdate$2(QuotaAwareFileSystemProviderTests.java:100)
            at org.elasticsearch.fs.quotaaware.QuotaAwareFileSystemProviderTests.withRetry(QuotaAwareFileSystemProviderTests.java:355)
            ... 1 more

            Caused by:
            java.lang.NumberFormatException: null
                at java.base/java.lang.Long.parseLong(Long.java:655)
                at java.base/java.lang.Long.parseLong(Long.java:817)
                at org.elasticsearch.fs.quotaaware.QuotaAwareFileSystemProvider.refreshLimits(QuotaAwareFileSystemProvider.java:213)
                at org.elasticsearch.fs.quotaaware.QuotaAwareFileSystemProvider$RefreshLimitsTask.run(QuotaAwareFileSystemProvider.java:95)
                at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
                at java.base/java.util.TimerThread.run(Timer.java:506)
```

**Comment by rjernst** [comment]
This does not reproduce locally for me.

Note that the reproduce line includes ant because it is using a Lucene base test case directly. The correct reproduce line is:

```
./gradlew :x-pack:quota-aware-fs:test --tests QuotaAwareFileSystemProviderTests.testRepeatedUpdate -Dtests.seed=7C315DE53A4CAA6D
```

**Comment by mark-vieira** [comment]
This failed again with an identical error on `7.x` so it's probably not a fluke.

https://gradle-enterprise.elastic.co/s/dwr6efxvdcj3o/tests/:x-pack:quota-aware-fs:test/org.elasticsearch.fs.quotaaware.QuotaAwareFileSystemProviderTests/testRepeatedUpdate

I've muted this on `master` and `7.x` since it seems likely to happen again.

**Comment by mark-vieira** [comment]
Interestingly, here's a packaging test failure that I think is a result of the same root cause:

https://gradle-enterprise.elastic.co/s/vzb2nme5bs3em/tests/:qa:os:destructiveDistroTest.default-linux-archive/org.elasticsearch.packaging.test.QuotaAwareFsTests/test30ElasticsearchStartsWhenSystemPropertySet

**Comment by cbuescher** [comment]
Another one on master today: https://gradle-enterprise.elastic.co/s/35evv4r73mikk

**Comment by pugnascotia** [comment]
We removed this plugin in #76352.

**Comment by astefan** [comment]
One failure today, on 7.14 (which makes sense since the plugin was removed in 7.15). In the last 28 days, this test class had 3 failures in total.
Today's failure: https://gradle-enterprise.elastic.co/s/ovvtqljg2mml2

```
1> [2021-09-03T09:34:15,443][WARN ][o.e.p.u.Shell            ] [TEST-QuotaAwareFsTests.test30ElasticsearchStartsWhenSystemPropertySet-seed#[41E8A3A1AD93173C]-workerest_thread_info] Running command with env: {ES_JAVA_HOME=/var/lib/jenkins/.java/oracle-8u301-linux} |  
-- | --
  | 1> [2021-09-03T09:34:20,936][INFO ][o.e.p.u.Shell            ] [TEST-QuotaAwareFsTests.test30ElasticsearchStartsWhenSystemPropertySet-seed#[41E8A3A1AD93173C]-workerest_thread_info] Ran: [bash, -c, sudo -E -u elasticsearch "/tmp/elasticsearch/bin/elasticsearch-plugin" install --batch "file:///var/lib/jenkins/workspace/elastic+elasticsearch+7.14+multijob+packaging-tests-unix/os/oraclelinux-8-packaging/x-pack/quota-aware-fs/build/distributions/quota-aware-fs-7.14.2-SNAPSHOT.zip"] exitCode = [0] stdout = [-> Installing file:///var/lib/jenkins/workspace/elastic+elasticsearch+7.14+multijob+packaging-tests-unix/os/oraclelinux-8-packaging/x-pack/quota-aware-fs/build/distributions/quota-aware-fs-7.14.2-SNAPSHOT.zip |  
  | 1> -> Downloading file:///var/lib/jenkins/workspace/elastic elasticsearch 7.14 multijob packaging-tests-unix/os/oraclelinux-8-packaging/x-pack/quota-aware-fs/build/distributions/quota-aware-fs-7.14.2-SNAPSHOT.zip |  
  | 1> -> Installed quota-aware-fs |  
  | 1> -> Please restart Elasticsearch to activate any plugins installed] stderr = [Future versions of Elasticsearch will require Java 11; your Java version from [/var/lib/jenkins/.java/oracle-8u301-linux/jre] does not meet this requirement. Consider switching to a distribution of Elasticsearch with a bundled JDK. If you are already using a distribution with a bundled JDK, ensure the JAVA_HOME environment variable is not set. |  
  | 1> warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release] |  
  | 1> [2021-09-03T09:34:32,560][INFO ][o.e.p.u.Shell            ] [TEST-QuotaAwareFsTests.test30ElasticsearchStartsWhenSystemPropertySet-seed#[41E8A3A1AD93173C]-workerest_thread_info] Ran: [bash, -c, sudo -E -u  elasticsearch /tmp/elasticsearch/bin/elasticsearch -d -p /tmp/elasticsearch/elasticsearch.pid] exitCode = [0] stdout = [] stderr = [Future versions of Elasticsearch will require Java 11; your Java version from [/var/lib/jenkins/.java/oracle-8u301-linux/jre] does not meet this requirement. Consider switching to a distribution of Elasticsearch with a bundled JDK. If you are already using a distribution with a bundled JDK, ensure the JAVA_HOME environment variable is not set. |  
  | 1> warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release |  
  | 1> Future versions of Elasticsearch will require Java 11; your Java version from [/var/lib/jenkins/.java/oracle-8u301-linux/jre] does not meet this requirement. Consider switching to a distribution of Elasticsearch with a bundled JDK. If you are already using a distribution with a bundled JDK, ensure the JAVA_HOME environment variable is not set. |  
  | 1> warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release] |  
  | 1> [2021-09-03T09:34:45,416][INFO ][o.a.h.i.e.RetryExec      ] [TEST-QuotaAwareFsTests.test30ElasticsearchStartsWhenSystemPropertySet-seed#[41E8A3A1AD93173C]-workerest_thread_info] I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://localhost:9200: The target server failed to respond |  
  | 1> [2021-09-03T09:34:45,416][INFO ][o.a.h.i.e.RetryExec      ] [TEST-QuotaAwareFsTests.test30ElasticsearchStartsWhenSystemPropertySet-seed#[41E8A3A1AD93173C]-workerest_thread_info] Retrying request to {}->http://localhost:9200 |  
  | 1> [2
```

....

```
1> [2021-09-03T09:34:44,281][INFO ][o.e.x.s.s.SecurityStatusChangeListener] [elasticsearch-ci-immutable-oraclelinux-8-p-1630660772535017989] Active license is now [BASIC]; Security is disabled |  
-- | --
  | 1> [2021-09-03T09:34:44,281][WARN ][o.e.x.s.s.SecurityStatusChangeListener] [elasticsearch-ci-immutable-oraclelinux-8-p-1630660772535017989] Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.14/security-minimal-setup.html to enable security. |  
  | 1> [2021-09-03T09:34:45,061][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [elasticsearch-ci-immutable-oraclelinux-8-p-1630660772535017989] fatal error in thread [elasticsearch[elasticsearch-ci-immutable-oraclelinux-8-p-1630660772535017989][management][T#2]], exiting |  
  | 1> java.lang.AssertionError: The quota aware filesystem has failed |  
  | 1> 	at org.elasticsearch.fs.quotaaware.QuotaAwareFileSystemProvider.ensureHealth(QuotaAwareFileSystemProvider.java:359) ~[?:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.fs.quotaaware.QuotaAwareFileSystemProvider.getTotal(QuotaAwareFileSystemProvider.java:351) ~[?:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.fs.quotaaware.QuotaAwareFileStore.getTotalSpace(QuotaAwareFileStore.java:47) ~[?:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.env.ESFileStore.getTotalSpace(ESFileStore.java:91) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.monitor.fs.FsProbe.getTotal(FsProbe.java:148) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.monitor.fs.FsProbe.getFSInfo(FsProbe.java:139) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.monitor.fs.FsProbe.stats(FsProbe.java:48) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.monitor.fs.FsService$FsInfoCache.refresh(FsService.java:90) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.monitor.fs.FsService$FsInfoCache.refresh(FsService.java:76) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.common.util.SingleObjectCache.getOrRefresh(SingleObjectCache.java:43) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.monitor.fs.FsService.lambda$new$1(FsService.java:54) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.monitor.fs.FsService.stats(FsService.java:64) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.node.NodeService.stats(NodeService.java:113) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.action.admin.cluster.node.stats.TransportNodesStatsAction.nodeOperation(TransportNodesStatsAction.java:71) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.action.admin.cluster.node.stats.TransportNodesStatsAction.nodeOperation(TransportNodesStatsAction.java:64) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.action.admin.cluster.node.stats.TransportNodesStatsAction.nodeOperation(TransportNodesStatsAction.java:31) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:282) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:275) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:259) ~[?:?] |  
  | 1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:330) ~[?:?] |  
  | 1> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:61) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:912) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-7.14.2-SNAPSHOT.jar:7.14.2-SNAPSHOT] |  
  | 1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301] |  
  | 1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301] |  
  | 1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301] |  
  | 1> Caused by: java.lang.NumberFormatException: null |  
  | 1> 	at java.lang.Long.parseLong(Long.java:552) ~[?:1.8.0_301] |  
  | 1> 	at java.lang.Long.parseLong(Long.java:631) ~[?:1.8.0_301] |  
  | 1> 	at org.elasticsearch.fs.quotaaware.QuotaAwareFileSystemProvider.refreshLimits(QuotaAwareFileSystemProvider.java:213) ~[?:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.fs.quotaaware.QuotaAwareFileSystemProvider.access$100(QuotaAwareFileSystemProvider.java:86) ~[?:7.14.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.fs.quotaaware.QuotaAwareFileSystemProvider$RefreshLimitsTask.run(QuotaAwareFileSystemProvider.java:95) ~[?:7.14.2-SNAPSHOT] |  
  | 1> 	at java.util.TimerThread.mainLoop(Timer.java:555) ~[?:1.8.0_301] |  
  | 1> 	at java.util.TimerThread.run(Timer.java:505) ~[?:1.8.0_301]
```

**Comment by rjernst** [comment]
We don't have any plans to figure out the root cause of this test failure in 7.14, which will stop being built once 7.15 is released.
