### ISSUE TITLE
[CI] ClassificationIT and RegressionIT testStopAndRestart failing on Windows

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#70698]
This failed back to back on Windows.

**Build scan**:
https://gradle-enterprise.elastic.co/s/lkoaua3founn4/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.ClassificationIT/testStopAndRestart

**Reproduction line:**
`EPRODUCE WITH: gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testStopAndRestart" -Dtests.seed=C0225758D7D53E28 -Dtests.security.manager=true -Dtests.locale=et-EE -Dtests.timezone=US/Arizona -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.ClassificationIT&tests.test=testStopAndRestart

**Failure excerpt:**
```
  java.lang.AssertionError: Stats were: {"id":"classification_stop_and_restart","state":"started","progress":[{"phase":"reindexing","progress_percent":100},{"phase":"loading_data","progress_percent":100},{"phase":"feature_selection","progress_percent":0},{"phase":"coarse_parameter_search","progress_percent":0},{"phase":"fine_tuning_parameters","progress_percent":0},{"phase":"final_training","progress_percent":0},{"phase":"writing_results","progress_percent":0},{"phase":"inference","progress_percent":0}],"data_counts":{"training_docs_count":350,"test_docs_count":0,"skipped_docs_count":0},"memory_usage":{"timestamp":1616450803027,"peak_usage_bytes":28542,"status":"ok"},"node":{"id":"4ltUeffQSGGFxbYNiQprQw","name":"javaRestTest-2","ephemeral_id":"5knpfoKGTg2kwsU0EEL8aw","transport_address":"127.0.0.1:53204","attributes":{"testattr":"test","ml.machine_memory":"103077892096","ml.max_open_jobs":"20","xpack.installed":"true","ml.max_jvm_size":"518979584"}},"assignment_explanation":""}
  Expected: <stopped>
       but: was <started>

  at __randomizedtesting.SeedInfo.seed([C0225758D7D53E28:B76AD5A6C33F3888]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:224)
  at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.lambda$waitUntilAnalyticsIsStopped$0(MlNativeDataFrameAnalyticsIntegTestCase.java:160)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:958)
  at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.waitUntilAnalyticsIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:160)
  at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.waitUntilAnalyticsIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:156)
  at org.elasticsearch.xpack.ml.integration.ClassificationIT.testStopAndRestart(ClassificationIT.java:508)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by mark-vieira** [comment]
This continues to fail, should we mute? I'm not sure if we have a good pattern for conditionally muting something on a given platform.

**Comment by dimitris-athanasiou** [comment]
I will add some logging. Can we please hold off muting until we get some logging for the failures?

**Comment by mark-vieira** [comment]
Awesome, thanks for the fix. It's funny how many weird timing issues we catch on Windows because everything generally runs slower. I suppose that's a feature not a bug.

**Comment by dimitris-athanasiou** [comment]
Unfortunately we got another failure of this after using uniquely named pipes.

https://gradle-enterprise.elastic.co/s/eep2yodligwhg

I will further investigate.

**Comment by mark-vieira** [comment]
This is still pretty consistently failing on Windows on `master` as well so I've muted there with 38189bb9eac5d45756940156e51ff9f06a1717d5.

**Comment by dnhatn** [comment]
Another instance on 7.x and Windows: https://gradle-enterprise.elastic.co/s/ydvmuwliqbu72

**Comment by dimitris-athanasiou** [comment]
Thanks for the mutes @mark-vieira  and @dnhatn. This test has been a pain on Windows. Back into the drawing board.

**Comment by davidkyle** [comment]
@dimitris-athanasiou ClassificationIT failed again with your logging changes https://gradle-enterprise.elastic.co/s/7xuuvxnu3apbc

**Comment by davidkyle** [comment]
Another https://gradle-enterprise.elastic.co/s/hg7fs3ner63ae

**Comment by cbuescher** [comment]
Another one on master: https://gradle-enterprise.elastic.co/s/g3wok27dfhk2m

**Comment by cbuescher** [comment]
@dimitris-athanasiou can you advise if we should mute this again on master or if you are still looking for clues via logging?

**Comment by dimitris-athanasiou** [comment]
@cbuescher I have already pushed the mute.
