### ISSUE TITLE
[CI] FileTokensToolTests testCreateToken failing

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#70959]
**Build scan:**
https://gradle-enterprise.elastic.co/s/645u6o3akfxkq/tests/:x-pack:qa:security-tools-tests:test/org.elasticsearch.xpack.security.authc.service.FileTokensToolTests/testCreateToken

**Reproduction line:**
`./gradlew ':x-pack:qa:security-tools-tests:test' --tests "org.elasticsearch.xpack.security.authc.service.FileTokensToolTests.testCreateToken" -Dtests.seed=9F4671BB5652333E -Dtests.security.manager=true -Dtests.locale=it-CH -Dtests.timezone=Africa/Addis_Ababa -Druntime.java=16`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.security.authc.service.FileTokensToolTests&tests.test=testCreateToken

**Failure excerpt:**
```
joptsimple.UnrecognizedOptionException: O is not a recognized option

  at __randomizedtesting.SeedInfo.seed([9F4671BB5652333E:CBAC29DB5CBA1753]:0)
  at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
  at joptsimple.OptionParser.validateOptionCharacters(OptionParser.java:633)
  at joptsimple.OptionParser.handleShortOptionCluster(OptionParser.java:528)
  at joptsimple.OptionParser.handleShortOptionToken(OptionParser.java:523)
  at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:59)
  at joptsimple.OptionParser.parse(OptionParser.java:396)
  at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:101)
  at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:80)
  at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
  at org.elasticsearch.cli.CommandTestCase.execute(CommandTestCase.java:46)
  at org.elasticsearch.cli.CommandTestCase.execute(CommandTestCase.java:37)
  at org.elasticsearch.xpack.security.authc.service.FileTokensToolTests.testCreateToken(FileTokensToolTests.java:132)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:567)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:831)

```

**Comment by dimitris-athanasiou** [comment]
I see failures with this test too. Will mute asap.

**Comment by dimitris-athanasiou** [comment]
Note I can reproduce local failures with: ```./gradlew ':x-pack:qa:security-tools-tests:test' --tests "org.elasticsearch.xpack.security.authc.service.FileTokensToolTests.testCreateToken" -Dtests.seed=768FCA40A34AFAA1```

Offending option is different each time so I am not sure if the test might also pass with this seed but it failed when I run it few times locally.

**Comment by dimitris-athanasiou** [comment]
Test `FileTokensToolTests.testCreateTokenWithInvalidTokenName` may also fail with a similar error.

https://gradle-enterprise.elastic.co/s/uwwuhid5eyihi

I will mute this one too.
