### ISSUE TITLE
[CI] DatabaseRegistryTests testCheckDatabases failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#71006]
This has failed a number of times today and reproduces locally.

**Build scan**:
https://gradle-enterprise.elastic.co/s/vlat4vnmzmwra/tests/:modules:ingest-geoip:test/org.elasticsearch.ingest.geoip.DatabaseRegistryTests/testCheckDatabases#1

**Repro line**:
`./gradlew ':modules:ingest-geoip:test' --tests "org.elasticsearch.ingest.geoip.DatabaseRegistryTests.testCheckDatabases" -Dtests.seed=DC51F7818CF75EB6 -Dtests.security.manager=true -Dtests.locale=sv-SE -Dtests.timezone=Etc/GMT+9 -Druntime.java=11`

**Reproduces locally?**:
Yes.

**Applicable branches**:
master

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.ingest.geoip.DatabaseRegistryTests&tests.sortField=FAILED&tests.test=testCheckDatabases&tests.unstableOnly=true

**Failure excerpt**:
```
org.elasticsearch.ingest.geoip.DatabaseRegistryTests > testCheckDatabases FAILED
    java.lang.AssertionError: 
    Expected: not null
         but: was null
        at __randomizedtesting.SeedInfo.seed([DC51F7818CF75EB6:E0E5ECF359A7F3B6]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.ingest.geoip.DatabaseRegistryTests.testCheckDatabases(DatabaseRegistryTests.java:143)
```

**Comment by mark-vieira** [comment]
Since this reproduces I've muted in `master` with d407a9699ea6f2be3017f623477714b956ec8502.
