### ISSUE TITLE
[CI] VersionStringFieldMapperTests#testFetchMany failed

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#71053]
**Build scan**:

https://gradle-enterprise.elastic.co/s/7mri5usps5fui

**Repro line**:

./gradlew ':x-pack:plugin:mapper-version:test' --tests "org.elasticsearch.xpack.versionfield.VersionStringFieldMapperTests.testFetchMany" -Dtests.seed=257DB53B6581EE8F -Dtests.security.manager=true -Dtests.locale=es-PY -Dtests.timezone=Asia/Calcutta -Druntime.java=11

**Reproduces locally?**:

Yes 

**Applicable branches**:

master

**Failure history**:

This started failing on March 26. on 7.x, four failures to far so seems only to happen with certain random seeds.

**Failure excerpt**:

```
java.lang.AssertionError: fetching [90, 64alpha12.9.72, 31, 45.37, 31, 47.78]
    Expected: iterable with items ["31", "45.37", "47.78", "90", "64alpha12.9.72"] in any order
         but: not matched: "31"
        at __randomizedtesting.SeedInfo.seed([257DB53B6581EE8F:9EB254E5FE002DE7]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.index.mapper.MapperTestCase.lambda$assertFetch$19(MapperTestCase.java:577)
        at org.elasticsearch.index.mapper.MapperServiceTestCase.withLuceneIndex(MapperServiceTestCase.java:223)
        at org.elasticsearch.index.mapper.MapperTestCase.assertFetch(MapperTestCase.java:551)
        at org.elasticsearch.index.mapper.MapperTestCase.testFetchMany(MapperTestCase.java:496)
```

**Comment by cbuescher** [comment]
This is one of the new randomized tests, it apparently has issues handling duplicate values in the input field. I currently think its something in the test setup that needs to be avoided/altered.

**Comment by cbuescher** [comment]
Similar in spirit, the same in WildcardFieldMapperTests#testFetchMany: https://gradle-enterprise.elastic.co/s/lppeyz7eub4w4

Here we have the "T" value as a duplicate: 
```
java.lang.AssertionError: fetching [dGVXEBeSXFDfzAXeiGxwQjKgNhMATHMpgtKApUzZLUodnMpikXMtGJQmCbkwmrDrFiq, qzhbMdfSyxrTvQyjNQxkIZnXfgaOmZsIfWOBHzQJrxMcqlXzgWyUsqrSKBOfUhaY, mnUMxlvZR, T, TWONXEJQgwmJusugVBvxTQBKULJxjujIBVXnFzXFOo, fXXltGmebhJWxesR, T, fbGCuXnODwUIFkMJizeFkOHaeTQJsPkrbsCsKzBXdrrmrzZIJHniOnEIlvVaDpuAKZOzwYDwqmAkhmmBHUUQIWVa, rYAglzeUJXRBxK] 
```

**Comment by cbuescher** [comment]
I also muted this on 7.x where this test was still failing.
