### ISSUE TITLE
[CI] MachineLearningIT testGetTrainedModelsStats failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#71139]
This didn't reproduce locally for me, and it's the first instance but I noticed another similar looking failure in `XPackRestIT` `test {p0=ml/pipeline_inference/Test pipeline regression simple}`.

Here's the node log from the other failure indicating shard errors: https://gradle-enterprise.elastic.co/s/g67zgm2dkrkgw/console-log?task=:x-pack:plugin:yamlRestTest#L12890

This test is also failing due to backing shard failures. Related?

**Build scan:**
https://gradle-enterprise.elastic.co/s/3c4qg5eq3qvt4/tests/:client:rest-high-level:asyncIntegTest/org.elasticsearch.client.MachineLearningIT/testGetTrainedModelsStats

**Reproduction line:**
`./gradlew ':client:rest-high-level:asyncIntegTest' --tests "org.elasticsearch.client.MachineLearningIT.testGetTrainedModelsStats" -Dtests.seed=D1988407AAFC971E -Dtests.security.manager=true -Dtests.locale=mk -Dtests.timezone=Etc/GMT+8 -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.client.MachineLearningIT&tests.test=testGetTrainedModelsStats

**Failure excerpt:**
```
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=Partial shards failure]

  at __randomizedtesting.SeedInfo.seed([D1988407AAFC971E:C9EC9DBCBBF90267]:0)
  at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:176)
  at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1933)
  at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1910)
  at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1667)
  at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1639)
  at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1606)
  at org.elasticsearch.client.MachineLearningClient.deleteTrainedModel(MachineLearningClient.java:2528)
  at org.elasticsearch.client.MlTestStateCleaner.lambda$deleteAllTrainedModels$3(MlTestStateCleaner.java:98)
  at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
  at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
  at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
  at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
  at org.elasticsearch.client.MlTestStateCleaner.deleteAllTrainedModels(MlTestStateCleaner.java:96)
  at org.elasticsearch.client.MlTestStateCleaner.clearMlMetadata(MlTestStateCleaner.java:58)
  at org.elasticsearch.client.MachineLearningIT.cleanUp(MachineLearningIT.java:228)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by benwtrent** [comment]
I bet this is a new failure because we are now cleaning up trained models after REST tests, previously we weren't and that caused OTHER issues :/

It is probably getting a shard failure because the index was just recently created. 

Frustrating.

**Comment by mark-vieira** [comment]
Just got  another identical failure. Muted in `master` with af54635bb2032f2532d2992fc353f4c50841a7d9.

**Comment by mark-vieira** [comment]
This has failed numerous times on `7.x` as well so I muted there as well with b6fb847c3697b1f7ddb129a595544ae61445d56b until #71146 is merged and backported.

**Comment by benwtrent** [comment]
thanks @mark-vieira sorry for the noise.

**Comment by romseygeek** [comment]
This just failed again on master with the same error message:
https://gradle-enterprise.elastic.co/s/ntyuwasqkt26g/tests/:client:rest-high-level:integTest/org.elasticsearch.client.MachineLearningIT/testGetTrainedModelsStats

```
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=exception, reason=Searching for stats for models [lang_ident_model_1,a-get-trained-model-stats-2,a-get-trained-model-stats-1,a-get-trained-model-stats-0,a-get-trained-model-stats-4,a-get-trained-model-stats-3] failed]
...

Caused by: org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
```
