### ISSUE TITLE
[CI] GeoIpCliTests classMethod failing on Windows

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#71145]
Seems this is a newly added test. The `LuceneTestCase` cleanup code doesn't play well here on Windows.

**Build scan:**
https://gradle-enterprise.elastic.co/s/se7yv5fe6d4am/tests/:distribution:tools:geoip-cli:test/org.elasticsearch.geoip.GeoIpCliTests/classMethod

**Reproduction line:**
`./gradlew.bat :distribution:tools:geoip-cli:test --tests "org.elasticsearch.geoip.GeoIpCliTests"`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.geoip.GeoIpCliTests&tests.test=classMethod

**Failure excerpt:**
```
java.io.IOException: Could not remove the following files (in the order of attempts):
   C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_D0C1D7D454917487-001\tempDir-003: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_D0C1D7D454917487-001\tempDir-003
   C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_D0C1D7D454917487-001\tempDir-002: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_D0C1D7D454917487-001\tempDir-002
   C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_D0C1D7D454917487-001\tempDir-003\target: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_D0C1D7D454917487-001\tempDir-003\target
   C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_D0C1D7D454917487-001\tempDir-002\target: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_D0C1D7D454917487-001\tempDir-002\target
   C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_D0C1D7D454917487-001\tempDir-002\source: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_D0C1D7D454917487-001\tempDir-002\source
   C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_D0C1D7D454917487-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_D0C1D7D454917487-001

  at __randomizedtesting.SeedInfo.seed([D0C1D7D454917487]:0)
  at org.apache.lucene.util.IOUtils.rm(IOUtils.java:319)
  at org.apache.lucene.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:216)
  at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by mark-vieira** [comment]
@probakowski do you mind taking a look since you added this test today?

FYI, I've muted this on `master`, not sure if this test has been backported to other branches yet.

**Comment by probakowski** [comment]
Thanks @mark-vieira, I'll take a look

**Comment by mark-vieira** [comment]
Muted this in `7.x` as well.

**Comment by csoulios** [comment]
Seems that test is failing again in Windows enviroments

Build scan:
https://gradle-enterprise.elastic.co/s/l5rpw7wgyof3y/tests/:distribution:tools:geoip-cli:test/org.elasticsearch.geoip.GeoIpCliTests/classMethod

Reproduction line:
./gradlew.bat :distribution:tools:geoip-cli:test --tests "org.elasticsearch.geoip.GeoIpCliTests"

Applicable branches:
7.x (commit 6a96e9e04c975e0b293b6388c70cf70b7b1b39ed)

Reproduces locally?:
Didn't try

Failure history:
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.geoip.GeoIpCliTests&tests.test=classMethod


```
org.elasticsearch.geoip.GeoIpCliTests > classMethod FAILED
    java.io.IOException: Could not remove the following files (in the order of attempts):
       C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_707E1E6AD1D282EE-001\tempDir-002: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_707E1E6AD1D282EE-001\tempDir-002
       C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_707E1E6AD1D282EE-001\tempDir-001: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_707E1E6AD1D282EE-001\tempDir-001
       C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_707E1E6AD1D282EE-001\tempDir-004: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_707E1E6AD1D282EE-001\tempDir-004
       C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_707E1E6AD1D282EE-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_707E1E6AD1D282EE-001
        at __randomizedtesting.SeedInfo.seed([707E1E6AD1D282EE]:0)
        at org.apache.lucene.util.IOUtils.rm(IOUtils.java:319)
        at org.apache.lucene.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:216)
        at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.lang.Thread.run(Thread.java:748)


Suite: Test class org.elasticsearch.geoip.GeoIpCliTests
  2> java.io.IOException: Could not remove the following files (in the order of attempts):
       C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_707E1E6AD1D282EE-001\tempDir-002: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_707E1E6AD1D282EE-001\tempDir-002
       C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_707E1E6AD1D282EE-001\tempDir-001: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_707E1E6AD1D282EE-001\tempDir-001
       C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_707E1E6AD1D282EE-001\tempDir-004: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_707E1E6AD1D282EE-001\tempDir-004
       C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_707E1E6AD1D282EE-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\elastic+elasticsearch+7.x+multijob-windows-compatibility\os\windows-2012-r2\distribution\tools\geoip-cli\build\testrun\test\temp\org.elasticsearch.geoip.GeoIpCliTests_707E1E6AD1D282EE-001
        at __randomizedtesting.SeedInfo.seed([707E1E6AD1D282EE]:0)
        at org.apache.lucene.util.IOUtils.rm(IOUtils.java:319)
        at org.apache.lucene.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:216)
        at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by mark-vieira** [comment]
I've remuted this on `master` and `7.x`.
