### ISSUE TITLE
Docker image failed to run on read-only mode

### ISSUE THREAD

**Issue by brendansun93** [elastic/elasticsearch#71157]
**Elasticsearch version** (`bin/elasticsearch --version`):
7.9.3

**Plugins installed**: 
N/A

**JVM version** (`java -version`):
N/A

**OS version** (`uname -a` if on a Unix-like system):
18.04.1-Ubuntu SMP Sat Mar 20 14:37:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
I tried to run official docker image with read only flag, but it failed with exception. 
Here is the docker command: 
`
docker run -d --name elasticsearch --hostname elasticsearch --publish 9200:9200 \
  -e "discovery.type=single-node" \
  -e "xpack.security.enabled=false" \
  -e "ES_JAVA_OPTS=-Xms1g -Xmx1g" \
  -v esdata:/usr/share/elasticsearch/data \
  --tmpfs /usr/share/elasticsearch/data/nodes:rw \
  --tmpfs /usr/share/elasticsearch/logs:rw \
  --tmpfs /usr/share/elasticsearch/config:rw \
  -v tmp:/tmp:rw --tmpfs /run:rw --tmpfs /var/run:rw \
  --read-only --security-opt=no-new-privileges \
  docker.elastic.co/elasticsearch/elasticsearch:7.9.3
`
I got exception: 
`
Exception in thread "main" java.nio.file.NoSuchFileException: /usr/share/elasticsearch/config/jvm.options
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.readJvmOptionsFiles(JvmOptionsParser.java:168)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:124)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)
`
I have set `/usr/share/elasticsearch/config` to have read and write access, not sure why `jvm.options` is still missing. 

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

Please refer to description section as I mentioned steps there. 

**Provide logs (if relevant)**:
Error log please refer to description section.

**Comment by mark-vieira** [comment]
The issue here is that `--tmpfs` simply mounts that location in the container to an _empty_ in-memory volume. So you're effectively overwriting the `config` directory that in the image which contains the options file.

**Comment by brendansun93** [comment]
> The issue here is that `--tmpfs` simply mounts that location in the container to an _empty_ in-memory volume. So you're effectively overwriting the `config` directory that in the image which contains the options file.

Thanks for the reply, any idea what i need to do to fix it and still run it under read-only mode?

**Comment by brendansun93** [comment]
> The issue here is that `--tmpfs` simply mounts that location in the container to an _empty_ in-memory volume. So you're effectively overwriting the `config` directory that in the image which contains the options file.

If i remove `--tmpfs` on `config` folder, i got error on creating tmp file: 
`
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.nio.file.FileSystemException: /usr/share/elasticsearch/config/elasticsearch.keystore.tmp: Read-only file system
Likely root cause: java.nio.file.FileSystemException: /usr/share/elasticsearch/config/elasticsearch.keystore.tmp: Read-only file system
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:224)
        at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:410)
        at org.apache.lucene.store.FSDirectory$FSIndexOutput.<init>(FSDirectory.java:406)
        at org.apache.lucene.store.FSDirectory.createOutput(FSDirectory.java:254)
        at org.elasticsearch.common.settings.KeyStoreWrapper.save(KeyStoreWrapper.java:488)
        at org.elasticsearch.bootstrap.Bootstrap.loadSecureSettings(Bootstrap.java:259)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)

`

**Comment by brendansun93** [comment]
Above issue is fixed by changing the docker command to: 
`
docker run -i --name elasticsearch --hostname elasticsearch --publish 9200:9200 \
  -e "discovery.type=single-node" \
  -e "xpack.security.enabled=false" \
  -e "ES_JAVA_OPTS=-Xms1g -Xmx1g" \
  -v esdata:/usr/share/elasticsearch/data \
  -v logs:/usr/share/elasticsearch/logs \
  -v config:/usr/share/elasticsearch/config \
  -v tmp:/tmp:rw --tmpfs /run:rw --tmpfs /var/run:rw \
  -v nodes:/usr/share/elasticsearch/data/nodes \
  --read-only --security-opt=no-new-privileges \
  --network geotab_docker_bridge \
  docker.elastic.co/elasticsearch/elasticsearch:7.9.3
`


but i got a brand new issue: 
`
ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes/0];
Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes/0
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:388)
        at java.base/java.nio.file.Files.createDirectory(Files.java:694)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:801)
        at java.base/java.nio.file.Files.createDirectories(Files.java:787)
        at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:274)
        at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:211)
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:271)
        at org.elasticsearch.node.Node.<init>(Node.java:344)
        at org.elasticsearch.node.Node.<init>(Node.java:277)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
`

Please help..

**Comment by mark-vieira** [comment]
I would mount the `config` directory locally as you would the data`. Keep in mind though, when you do, it'll be missing loads of other stuff. I suggest grabbing the default `config` directory contents [from the tarball](https://www.elastic.co/downloads/past-releases/elasticsearch-7-9-3), put them in a location locally on the host, then bind mount that into the read-only container.

**Comment by david0** [comment]
I am able to avoid the `elasticsearch.keystore.tmp: Read-only file system` exception by just creating `elasticsearch.keystore` before.

Either you can run `/usr/share/elasticsearch/bin/elasticsearch-keystore create` when building a custom container or mount a previously created keystore.

**Comment by mark-vieira** [comment]
Keep in mind that [as per our documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_configuration_files_must_be_readable_by_the_elasticsearch_user) the entire `config` directory is expected to be writable. There are other files aside from the keystore that may need to be modified by Elasticsearch. Just pointing this out as you may continue to run into issues down the road even if you preemptively create a keystore.
