### ISSUE TITLE
[CI] CCSFieldCapabilitiesIT.testFailuresFromRemote

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#71349]
**Build scan**:

https://gradle-enterprise.elastic.co/s/mvr6xm42r4txw/tests/:server:internalClusterTest/org.elasticsearch.search.fieldcaps.CCSFieldCapabilitiesIT/testFailuresFromRemote#1

**Repro line**:

```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.search.fieldcaps.CCSFieldCapabilitiesIT.testFailuresFromRemote" -Dtests.seed=6B25B2499A82C5 -Dtests.security.manager=true -Dtests.locale=de-GR -Dtests.timezone=Asia/Ho_Chi_Minh -Druntime.java=8
```

**Reproduces locally?**: Yes

**Applicable branches**: master, 7.x

**Failure excerpt**:
```
java.lang.AssertionError: expected:<class java.lang.IllegalArgumentException> but was:<class org.elasticsearch.index.shard.IllegalIndexShardStateException>
        at __randomizedtesting.SeedInfo.seed([6B25B2499A82C5:627B2742E112BAF1]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.elasticsearch.search.fieldcaps.CCSFieldCapabilitiesIT.testFailuresFromRemote(CCSFieldCapabilitiesIT.java:75)
```

**Comment by mark-vieira** [comment]
I've muted this in `master` and `7.x`.
