### ISSUE TITLE
RestHighLevelClient terms query with enum not working

### ISSUE THREAD

**Issue by clempe** [elastic/elasticsearch#71388]
**Elasticsearch version** 7.9.3:

**Description of the problem including expected versus actual behavior**:
I updated the _elasticsearch-rest-high-level-client_ from 7.9.3 to 7.12.0 and got an error by creating a terms query with (a list of) _enums_. 

**Steps to reproduce**:
QueryBuilders.termsQuery("fieldName", MyEnum.A));
or
QueryBuilders.termsQuery("fieldName", List.of(MyEnum.A, MyEnum.B));

**Provide logs (if relevant)**:
IllegalArgumentException
can not write type  [class ...]

**Comment by cbuescher** [comment]
@clempe so I assume this this code worked in 7.9.3? Which version are you running / were you running on the server side?
Maybe you could also add the full stacktrace of the IllegalArgumentException here? 
I have a slight suspicion that maybe changes from https://github.com/elastic/elasticsearch/pull/67223 might cause this, we might have implicitely converted enums to their String representation before. This would mean you can work around this for now by doing the same on the client side (i.e. MyEnum.A.toString())

**Comment by clempe** [comment]
Yes, the code worked with 7.9.3.

Server Info:
```
 "version" : {
    "number" : "7.9.3",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "c4138e51121ef06a6404866cddc601906fe5c868",
    "build_date" : "2020-10-16T10:36:16.141335Z",
    "build_snapshot" : false,
    "lucene_version" : "8.6.2",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
```

TestCase tried with 7.12.0 - Both are working with 7.9.3
```
    public static enum MyEnum {
        A, B;
    }

    //This fails
    @Test
    public void termsQuery() {
        QueryBuilders.termsQuery("fieldName", MyEnum.A);
    }

    //This works
    @Test
    public void matchQuery() {
        QueryBuilders.matchQuery("fieldName", MyEnum.A);
    }
```
Stacktrace for temsQuery test:
```
java.lang.IllegalArgumentException: can not write type [class com.strabag.services.tas.ws.rs.provider.QueryTest$MyEnum]

	at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:845)
	at org.elasticsearch.common.io.stream.StreamOutput.lambda$static$12(StreamOutput.java:700)
	at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:843)
	at org.elasticsearch.index.query.TermsQueryBuilder$Values.serialize(TermsQueryBuilder.java:434)
	at org.elasticsearch.index.query.TermsQueryBuilder$BinaryValues.<init>(TermsQueryBuilder.java:493)
	at org.elasticsearch.index.query.TermsQueryBuilder$BinaryValues.<init>(TermsQueryBuilder.java:483)
	at org.elasticsearch.index.query.TermsQueryBuilder.<init>(TermsQueryBuilder.java:161)
	at org.elasticsearch.index.query.TermsQueryBuilder.<init>(TermsQueryBuilder.java:141)
	at org.elasticsearch.index.query.QueryBuilders.termsQuery(QueryBuilders.java:568)
	at com.strabag.services.tas.ws.rs.provider.QueryTest.termsQuery(QueryTest.java:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:184)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:180)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

```

**Comment by cbuescher** [comment]
I found why this was working in 7.9 but does create problems now when trying to create a TermsQueryBuilder in the client.
Before #67223 we used to store enums passed in via the `TermsQueryBuilder(String fieldName, Object... values)` constructor directly without altering, but when the client sends these queries to the server they are rendered as json (xContent) once, which rendes the enums "toString()" representation. With the change in #67223 we now already try to convert BinaryValues values to BytesRef using the BytesStreamOutput [here](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/query/TermsQueryBuilder.java#L431), which doesn't support Enum values (and never did). 
To me it sounds like the actual "bug" here is that for some reason creating TermsQueryBuilder with Enums worked on the client side before almost by accident, because rendering to json we used the enums string representation. I don't think we should fix this because using Enums here should not be supported and is not always sure to succeed (e.g. when the string representation differs from what is indexed in the underlying field). Instead, I'd suggest using the enums String representation when creating the query like suggested above ((i.e. MyEnum.A.toString()). 
I think we should also think about deprecating the public `TermsQueryBuilder(String fieldName, Object... values)` and maybe replace it by more specific versions for Object types that work, or alternatively at least specify which Object classes work in the javadoc. I'm going to open a separate issue for this an am going to close this since I think the behaviour is expected, the fact that it worked in previous versions were a sort of leniency bug in the API and there is a workaround (using the enums toString() instead). Please let me know if you disagree by reopening this issue.

**Comment by arosenheinrich** [comment]
Thanks for your explanation, I stumbled over the same problem with TermsQueryBuilder and enums, which is having quite an impact on our application. 
Deprecating the general constructor for TermsQueryBuilder or more specification would certainly help, but I am a bit concerned about the inconsistency between term or match and terms. For term or match queries it seems I can still use the enum, for terms I have to use enums toString() method. Whatever the solution will be (I would suggest to use enum.toString() everywhere like with terms now instead of just enum object) would certainly be a breaking change.
