### ISSUE TITLE
[CI] QueryRescorerIT.testScoring failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#71405]
Failure output: 

```
  2> REPRODUCE WITH: ./gradlew ':server:integTest' -Dtests.seed=C84ACE2FA7E8BAD9 -Dtests.class=org.elasticsearch.search.functionscore.QueryRescorerIT -Dtests.method="testScoring" -Dtests.security.manager=true -Dtests.locale=be-BY -Dtests.timezone=America/Inuvik -Dcompiler.java=11 -Druntime.java=8
FAILURE 2.09s J6  | QueryRescorerIT.testScoring <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Count is 3 but 4 was expected.  Total shards: 7 Successful shards: 7 & 0 shard failures:
   > 	at __randomizedtesting.SeedInfo.seed([C84ACE2FA7E8BAD9:EA68C910AD9CD888]:0)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertHitCount(ElasticsearchAssertions.java:252)
   > 	at org.elasticsearch.search.functionscore.QueryRescorerIT.testScoring(QueryRescorerIT.java:577)
   > 	at java.lang.Thread.run(Thread.java:748)
```

Branch: 7.x

Build scan: https://gradle-enterprise.elastic.co/s/yilook3amswnc/console-log?anchor=1404

**Comment by cbuescher** [comment]
The build scan suggests this failed on the 6.8 branch, not 7.x. I couldn't reproduce locally so far. Also this seems to be the only failure of this kind for a long time so far (latests failure of that test I could find was in 2019 for other reasons), so we should probably first observe if/how often this fails on other branches.
