### ISSUE TITLE
[CI] XPackRestIT test {p0=security\authz/14_cat_indices/Test explicit request while multiple opened/closed authorized indices} failing rest compatibility tests

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#71475]
Bunch of other related tests here failing. Primarily these are failing on Windows but I've seen similar failings in PR builds.

https://gradle-enterprise.elastic.co/s/7slud5rn5zoou/tests/:x-pack:plugin:yamlRestCompatTest/org.elasticsearch.xpack.test.rest.XPackRestIT/test%20%7Bp0=security%2Fauthz%2F14_cat_indices%2FTest%20empty%20request%20while%20no-authorized%20index%7D#1

**Build scan:**
https://gradle-enterprise.elastic.co/s/ofdr2oas5pi56/tests/:x-pack:plugin:yamlRestCompatTest/org.elasticsearch.xpack.test.rest.XPackRestIT/test%20%7Bp0=security%5Cauthz%2F14_cat_indices%2FTest%20explicit%20request%20while%20multiple%20opened%2Fclosed%20authorized%20indices%7D

**Reproduction line:**
`gradlew ':x-pack:plugin:yamlRestCompatTest' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=security\authz/14_cat_indices/Test explicit request while multiple opened/closed authorized indices}" -Dtests.seed=D1135D292DAA52AB -Dtests.security.manager=true -Dtests.locale=es-PR -Dtests.timezone=America/Argentina/Cordoba -Druntime.java=11 -Dtests.rest.blacklist=getting_started/10_monitor_cluster_health/*,getting_started/10_monitor_cluster_health/*,license/30_enterprise_license/Installing enterprise license,ml/data_frame_analytics_cat_apis/Test cat data frame analytics all jobs with header and column selection,ml/data_frame_analytics_cat_apis/Test cat data frame analytics all jobs with header,ml/data_frame_analytics_cat_apis/Test cat data frame analytics single job with header,ml/data_frame_analytics_cat_apis/Test cat data frame analytics single job,ml/datafeed_cat_apis/Test cat datafeeds,ml/datafeeds_crud/Test update datafeed to point to different job,ml/datafeeds_crud/Test update datafeed to point to job already attached to another datafeed,ml/datafeeds_crud/Test update datafeed to point to missing job,ml/job_cat_apis/Test cat anomaly detector jobs,ml/jobs_get_stats/Test get job stats after uploading data prompting the creation of some stats,ml/jobs_get_stats/Test get job stats for closed job,ml/jobs_get_stats/Test no exception on get job stats with missing index,ml/post_data/Test flush with skip_time,ml/post_data/Test POST data job api, flush, close and verify DataCounts doc,ml/set_upgrade_mode/Setting upgrade mode to disabled from enabled,ml/set_upgrade_mode/Setting upgrade_mode to enabled,ml/set_upgrade_mode/Test setting upgrade_mode to false when it is already false,ml/trained_model_cat_apis/Test cat trained models,privileges/11_builtin/Test get builtin privileges,roles/11_idx_arrays/Test put role api using as array of index names,roles/30_prohibited_role_query/Test use prohibited query inside role query,rollup/delete_job/Test basic delete_job,rollup/delete_job/Test delete job twice,rollup/delete_job/Test delete running job,rollup/get_jobs/Test basic get_jobs,rollup/put_job/Test basic put_job,rollup/put_job/Test put_job in non-rollup index,rollup/rollup_search/Obsolete BWC Timezone,rollup/rollup_search/Obsolete Timezone,rollup/start_job/Test start job twice,security/authz/14_cat_indices/Test empty request while no-authorized index,security/authz/14_cat_indices/Test empty request while single authorized index,security/authz/14_cat_indices/Test explicit request while multiple authorized indices,security/authz/14_cat_indices/Test explicit request while multiple opened/closed authorized indices,security/authz/14_cat_indices/Test wildcard request with multiple authorized indices,set_security_user/10_small_users_one_index/Test shared index separating user by using DLS,sql/sql/Clean cursor,sql/sql/Execute some SQL,sql/sql/Getting textual representation,sql/sql/Paging through results,sql/translate/Translate SQL,transform/transforms_cat_apis/Test cat transform stats hiding headers,transform/transforms_cat_apis/Test cat transform stats with column selection,transform/transforms_cat_apis/Test cat transform stats with continuous transform,vectors/10_dense_vector_basic/Cosine Similarity,vectors/10_dense_vector_basic/Deprecated function signature,vectors/10_dense_vector_basic/Dot Product,vectors/15_dense_vector_l1l2/L1 norm,vectors/15_dense_vector_l1l2/L2 norm,vectors/20_dense_vector_special_cases/Dense vectors should error with sparse vector functions,vectors/20_dense_vector_special_cases/Documents missing a vector field,vectors/20_dense_vector_special_cases/Functions with query vectors with dims different from docs vectors should error,vectors/20_dense_vector_special_cases/Indexing of Dense vectors should error when dims don't match defined in the mapping,vectors/20_dense_vector_special_cases/Vectors of mixed integers and floats,vectors/30_sparse_vector_basic/Cosine Similarity,vectors/30_sparse_vector_basic/Deprecated function signature,vectors/30_sparse_vector_basic/Dot Product,vectors/35_sparse_vector_l1l2/L1 norm,vectors/35_sparse_vector_l1l2/L2 norm,vectors/40_sparse_vector_special_cases/Dimensions can be sorted differently,vectors/40_sparse_vector_special_cases/Documents missing a vector field,vectors/40_sparse_vector_special_cases/Query vector has different dimensions from documents' vectors,vectors/40_sparse_vector_special_cases/Sparse vectors should error with dense vector functions,vectors/40_sparse_vector_special_cases/Vectors of different dimensions and data types,vectors/50_vector_stats/Usage stats on vector fields`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.test.rest.XPackRestIT&tests.test=test%20%7Bp0%3Dsecurity%5Cauthz/14_cat_indices/Test%20explicit%20request%20while%20multiple%20opened/closed%20authorized%20indices%7D

**Failure excerpt:**
```
java.lang.AssertionError: Failure at [security\authz/14_cat_indices:285]: field [$body] was expected to be of type String but is an instanceof [class java.util.ArrayList]
Expected: an instance of java.lang.String
     but: <[{i=this_index}, {i=index_to_monitor}, {i=this_index_is_closed}]> is a java.util.ArrayList

  at __randomizedtesting.SeedInfo.seed([D1135D292DAA52AB:594762F383563F53]:0)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:451)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:428)
  at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(null:-1)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

  Caused by: java.lang.AssertionError: field [$body] was expected to be of type String but is an instanceof [class java.util.ArrayList]
  Expected: an instance of java.lang.String
       but: <[{i=this_index}, {i=index_to_monitor}, {i=this_index_is_closed}]> is a java.util.ArrayList

    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
    at org.junit.Assert.assertThat(Assert.java:956)
    at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:52)
    at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:444)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:428)
    at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(null:-1)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
    at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
    at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
    at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
    at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
    at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
    at java.lang.Thread.run(Thread.java:834)

```

**Comment by mark-vieira** [comment]
Since this is an issue with the REST compatibility tests I'm tagging Core/Features here. It's likely we may just need to add these to the ignore list.

cc @jakelandis

**Comment by mark-vieira** [comment]
@jakelandis looks like this is still failing. Perhaps the weird escaping isn't being handled by the ignores correctly either?

**Comment by jakelandis** [comment]
I didn't merge the fix until earlier today, and the commit for the failure is a bit prior to the fix. Another [job](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/133/) is running now which should include the fix.

**Comment by mark-vieira** [comment]
Ah, sorry, I thought this got merged last week. Nvm.

**Comment by jakelandis** [comment]
Looks like the fix did not work :( ... re-opening
