### ISSUE TITLE
[CI] ChainingInputStreamTests testResetForDoubleMarkAnywhere failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#71510]
This indeed reproduces locally for me on all branches (not just 7.12) regardless of the FIPS flag so I suspect that's unrelated.

**Build scan:**
https://gradle-enterprise.elastic.co/s/wucgx7uqw55qe/tests/:x-pack:plugin:repository-encrypted:test/org.elasticsearch.repositories.encrypted.ChainingInputStreamTests/testResetForDoubleMarkAnywhere

**Reproduction line:**
`./gradlew ':x-pack:plugin:repository-encrypted:test' --tests "org.elasticsearch.repositories.encrypted.ChainingInputStreamTests.testResetForDoubleMarkAnywhere" -Dtests.seed=EE4F5B2128A3DCB7 -Dtests.security.manager=true -Dtests.locale=es-MX -Dtests.timezone=Africa/Algiers -Druntime.java=11 -Dtests.fips.enabled=true`

**Applicable branches:**
master, 7.x, 7.12

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.repositories.encrypted.ChainingInputStreamTests&tests.test=testResetForDoubleMarkAnywhere

**Failure excerpt:**
```
org.mockito.exceptions.verification.TooManyActualInvocations: 
inputStream.reset();
Wanted 1 time:
-> at org.elasticsearch.repositories.encrypted.ChainingInputStreamTests.testResetForDoubleMarkAnywhere(ChainingInputStreamTests.java:997)
But was 2 times. Undesired invocation:
-> at org.elasticsearch.repositories.encrypted.ChainingInputStream.reset(ChainingInputStream.java:387)

  at __randomizedtesting.SeedInfo.seed([EE4F5B2128A3DCB7:72E6360738764757]:0)
  at org.elasticsearch.repositories.encrypted.ChainingInputStreamTests.testResetForDoubleMarkAnywhere(ChainingInputStreamTests.java:997)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by original-brownbear** [comment]
This might explain https://github.com/elastic/elasticsearch/issues/71326 I'll take a look

**Comment by original-brownbear** [comment]
@albertzaharovits could you take a look here? I'm not quite able to work out what we're trying to test here. It seems ok to me that we see multiple resets on the same stream in this scenario since we're not moving the stream along between resets but I'd rather have you look at it and verify that I think :) thanks!

**Comment by albertzaharovits** [comment]
You are exactly right @original-brownbear. I've raised https://github.com/elastic/elasticsearch/pull/72595.

I think we need to find a clearer way to test the state machine for mark and reset on the encrypted stream, but for now the test is still useful.
