### ISSUE TITLE
NPE in DataTiersUsageTransportAction

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#71670]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.11.1 but still present in `master`

**Description of the problem including expected versus actual behavior**:

This code ...

https://github.com/elastic/elasticsearch/blob/a92a647b9f17d1bddf5c707490a19482c273eda3/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/DataTiersUsageTransportAction.java#L103-L111

... assumes that if any shards of an index are assigned to a `RoutingNode` then the node will have reported stats for this index. This isn't always true, because the assignment according to the cluster state might not match the assignment on the node at the time it computed its stats.

Relates #63031

**Provide logs (if relevant)**:

```
[WARN ][r.suppressed             ] [REDACTED] path: /_xpack/usage, params: {}
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "org.elasticsearch.indices.NodeIndicesStats.getShardStats(org.elasticsearch.index.Index)" is null
        at org.elasticsearch.xpack.core.DataTiersFeatureSet.lambda$calculateStats$7(DataTiersFeatureSet.java:120) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.elasticsearch.xpack.core.DataTiersFeatureSet.calculateStats(DataTiersFeatureSet.java:119) ~[?:?]
        at org.elasticsearch.xpack.core.DataTiersFeatureSet.lambda$usage$0(DataTiersFeatureSet.java:80) ~[?:?]
        at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178) ~[?:?]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1837) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at org.elasticsearch.xpack.core.DataTiersFeatureSet.lambda$usage$1(DataTiersFeatureSet.java:80) ~[?:?]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:117) [elasticsearch-7.11.1.jar:7.11.1]
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:83) [elasticsearch-7.11.1.jar:7.11.1]
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:77) [elasticsearch-7.11.1.jar:7.11.1]
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32) [elasticsearch-7.11.1.jar:7.11.1]
        at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47) [elasticsearch-7.11.1.jar:7.11.1]
        at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62) [elasticsearch-7.11.1.jar:7.11.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.11.1.jar:7.11.1]
        at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:213) [elasticsearch-7.11.1.jar:7.11.1]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.finishHim(TransportNodesAction.java:244) [elasticsearch-7.11.1.jar:7.11.1]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.onOperation(TransportNodesAction.java:229) [elasticsearch-7.11.1.jar:7.11.1]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.access$000(TransportNodesAction.java:166) [elasticsearch-7.11.1.jar:7.11.1]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:212) [elasticsearch-7.11.1.jar:7.11.1]
        at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1.handleResponse(TransportNodesAction.java:204) [elasticsearch-7.11.1.jar:7.11.1]
        at org.elasticsearch.transport.TransportService$6.handleResponse(TransportService.java:737) [elasticsearch-7.11.1.jar:7.11.1]
```

**Comment by danielmitterdorfer** [comment]
This has been addressed by https://github.com/elastic/elasticsearch/pull/75185. Nevertheless, the related issue https://github.com/elastic/elasticsearch/issues/87001 is still relevant.
