### ISSUE TITLE
[CI] JdbcPreparedStatementTests testSettingSqlDateValues failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#71704]
This failure looks to be specific with Java 16 and reproduced locally for me. Ran against Java 11 and 15 w/o failure.

**Build scan:**
https://gradle-enterprise.elastic.co/s/lafpotvh3stq6/tests/:x-pack:plugin:sql:jdbc:test/org.elasticsearch.xpack.sql.jdbc.JdbcPreparedStatementTests/testSettingSqlDateValues

**Reproduction line:**
`./gradlew ':x-pack:plugin:sql:jdbc:test' --tests "org.elasticsearch.xpack.sql.jdbc.JdbcPreparedStatementTests.testSettingSqlDateValues" -Dtests.seed=3A9DBCBB571CC4BB -Dtests.security.manager=true -Dtests.locale=id-ID -Dtests.timezone=America/Edmonton -Druntime.java=16`

**Applicable branches:**
master

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.sql.jdbc.JdbcPreparedStatementTests&tests.test=testSettingSqlDateValues

**Failure excerpt:**
```
java.lang.AssertionError: expected:<2099826214478867443> but was:<2099826214475267443>

  at __randomizedtesting.SeedInfo.seed([3A9DBCBB571CC4BB:CA6D94D4096061B5]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.failNotEquals(Assert.java:834)
  at org.junit.Assert.assertEquals(Assert.java:645)
  at org.junit.Assert.assertEquals(Assert.java:631)
  at org.elasticsearch.xpack.sql.jdbc.JdbcPreparedStatementTests.testSettingSqlDateValues(JdbcPreparedStatementTests.java:452)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:567)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:831)

```

**Comment by bpintea** [comment]
Seems to replicate with older JVM versions too when changing the timezone to the one in test (this varies between v15 and v16). The test seems to fail with time zones observing the European daylight saving and certain date values (tests uses `2099826214478867443L` -- `Sun Oct 27 02:27:47 CET 6654281`).

**Comment by craigtaverner** [comment]
JDK16 is no longer supported for Elasticsearch, so I tested on 17, 18, 19, 20 and 21.

* 17 - passed
* 18 - passed
* 19 - *FAILED* `expected:<2099826214478867443> but was:<2099826214475267443>`
* 20 - passed
* 21 - passed

Repeated tests yielded the same results. So clearly JDK19 fails this test reliably.

**Comment by craigtaverner** [comment]
The above tests were done on main (8.15), and earlier reports of the issue were on 7.x, so I've repeated the tests on 7.17 and included JDK22, since the Elastic support matrix indicates 7.17 is supported on JDK17, 18, 19, 20, 21 and 22.

| JDK Version | main(8.15)                 | 7.17                             |
| ------------ | -------------------- | ---------------------|
| 17                  | :white_check_mark: | :white_check_mark: | 
| 18                  | :white_check_mark: | :white_check_mark: | 
| 19                  | :x:                               | :white_check_mark: | 
| 20                  | :white_check_mark: | :white_check_mark: | 
| 21                  | :white_check_mark: | :white_check_mark: | 
| 22                  | :white_check_mark: | :white_check_mark: | 

JDK19 is not supported on 8.15. In fact, other than 7.17, it is only supported on 8.5, 8.6, 8.7 and 8.8. So this issue does not happen on any supported versions, and has not been reported in CI for a very long time (and the test is not muted). I recommend we close the issue.

**Comment by astefan** [comment]
+1
When these kind of failures happened in the past it was related to Locale changes from one JVM version to another. With jdbc (as a client) the JVM it is using can be different from the one of the server (where ES SQL "server" lives). So, if one JVM knows about one Locale/timezone but the other doesn't, this kind of issues are likely to pop up.
