### ISSUE TITLE
Unrecognized VM option 'UseConcMarkSweepGC' on Windows 10

### ISSUE THREAD

**Issue by mscherer82** [elastic/elasticsearch#71741]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.12.0

**JVM version** (`java -version`):
```
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
```

After installation I've started `elasticseach.exe` from comand line and got the following error:

```
Could not evaluate jvm.options file. result: Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:
error:
Unrecognized VM option 'UseConcMarkSweepGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
        at org.elasticsearch.tools.launchers.JvmOption.flagsFinal(JvmOption.java:119)
        at org.elasticsearch.tools.launchers.JvmOption.findFinalOptions(JvmOption.java:81)
        at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:38)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:135)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)
```

**Comment by dnhatn** [comment]
@mscherer82 Did you install Elasticsearch using an MSI installer or from a zip file?

**Comment by ebadyano** [comment]
No further feedback received. @mscherer82 if you have the requested information please add it in a comment and we will re-open this issue.
