### ISSUE TITLE
RESTART_ON_UPGRADE not working on RPM packages

### ISSUE THREAD

**Issue by sbruno** [elastic/elasticsearch#71784]
**Elasticsearch version**: `Version: 7.10.0, Build: default/rpm/51e9d6f22758d0374a0f3f5c6e8f3a7997850f96/2020-11-09T21:30:33.964949Z, JVM: 15.0.1`

**Plugins installed**: []

**JVM version**: `No java, using embedded jdk. /usr/share/elasticsearch/jdk/bin/java -version : openjdk version "15.0.1" 2020-10-20`

**OS version**: Centos 7 `Linux host3 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:

On a system with elasticsearch installed and running, having `RESTART_ON_UPGRADE` set to true in `/etc/sysconfig/elasticsearch`, after upgrading elasticsearch via `yum` service fails to be restarted.

Doing manual restart after yum command completes works.

**Steps to reproduce**:

```
rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

cat > /etc/yum.repos.d/elasticsearch.repo << EOF
[elasticsearch]
name=Elasticsearch repository for 7.x packages
baseurl=https://artifacts.elastic.co/packages/7.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=0
autorefresh=1
type=rpm-md
EOF

yum install -y --enablerepo=elasticsearch elasticsearch-7.10.0-1

systemctl daemon-reload
systemctl enable elasticsearch.service
systemctl start elasticsearch.service

sed -i 's/#RESTART_ON_UPGRADE=true/RESTART_ON_UPGRADE=true/' /etc/sysconfig/elasticsearch

yum install -y --enablerepo=elasticsearch elasticsearch-7.10.2-1

```
**Provide logs (if relevant)**:

```
[root@host3 bin]# yum install -y --enablerepo=elasticsearch elasticsearch-7.10.2-1
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.zero.com.ar
 * extras: mirrors.eze.sysarmy.com
 * updates: mirror1.cl.netactuate.com
Resolving Dependencies
--> Running transaction check
---> Package elasticsearch.x86_64 0:7.10.0-1 will be updated
---> Package elasticsearch.x86_64 0:7.10.2-1 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

========================================================================================================================
 Package                        Arch                    Version                    Repository                      Size
========================================================================================================================
Updating:
 elasticsearch                  x86_64                  7.10.2-1                   elasticsearch                  304 M

Transaction Summary
========================================================================================================================
Upgrade  1 Package

Total download size: 304 M
Downloading packages:
No Presto metadata available for elasticsearch
elasticsearch-7.10.2-x86_64.rpm                                                                  | 304 MB  00:00:44     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : elasticsearch-7.10.2-1.x86_64                                                                        1/2 
Restarting elasticsearch service...Job for elasticsearch.service failed because the control process exited with error code. See "systemctl status elasticsearch.service" and "journalctl -xe" for details.
 OK
  Cleanup    : elasticsearch-7.10.0-1.x86_64                                                                        2/2 
Created elasticsearch keystore in /etc/elasticsearch/elasticsearch.keystore
  Verifying  : elasticsearch-7.10.2-1.x86_64                                                                        1/2 
  Verifying  : elasticsearch-7.10.0-1.x86_64                                                                        2/2 

Updated:
  elasticsearch.x86_64 0:7.10.2-1                                                                                       

Complete!
```

```
[root@host3 bin]# journalctl -xe
Apr 16 21:30:00 host3 systemd[1]: Starting Elasticsearch...
-- Subject: Unit elasticsearch.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit elasticsearch.service has begun starting up.
Apr 16 21:30:02 host3 systemd-entrypoint[3614]: uncaught exception in thread [main]
Apr 16 21:30:02 host3 systemd-entrypoint[3614]: java.lang.IllegalStateException: jar hell!
Apr 16 21:30:02 host3 systemd-entrypoint[3614]: class: META-INF.versions.11.org.elasticsearch.core.internal.io.Streams
Apr 16 21:30:02 host3 systemd-entrypoint[3614]: jar1: /usr/share/elasticsearch/lib/elasticsearch-core-7.10.2.jar
Apr 16 21:30:02 host3 systemd-entrypoint[3614]: jar2: /usr/share/elasticsearch/lib/elasticsearch-core-7.10.0.jar
Apr 16 21:30:02 host3 systemd-entrypoint[3614]: at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:287)
Apr 16 21:30:02 host3 systemd-entrypoint[3614]: at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:195)
Apr 16 21:30:02 host3 systemd-entrypoint[3614]: at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:86)
Apr 16 21:30:02 host3 systemd-entrypoint[3614]: at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212)
Apr 16 21:30:02 host3 systemd-entrypoint[3614]: at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393)
Apr 16 21:30:02 host3 systemd-entrypoint[3614]: at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170
Apr 16 21:30:02 host3 systemd-entrypoint[3614]: at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:
Apr 16 21:30:02 host3 systemd-entrypoint[3614]: at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwar
Apr 16 21:30:02 host3 systemd-entrypoint[3614]: at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:1
Apr 16 21:30:02 host3 systemd-entrypoint[3614]: at org.elasticsearch.cli.Command.main(Command.java:90)
Apr 16 21:30:02 host3 systemd-entrypoint[3614]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126
Apr 16 21:30:02 host3 systemd-entrypoint[3614]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
Apr 16 21:30:02 host3 systemd-entrypoint[3614]: For complete error details, refer to the log at /var/log/elasticsearch/e
Apr 16 21:30:02 host3 systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Apr 16 21:30:02 host3 systemd[1]: Failed to start Elasticsearch.
-- Subject: Unit elasticsearch.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit elasticsearch.service has failed.
-- 
-- The result is failed.
Apr 16 21:30:02 host3 systemd[1]: Unit elasticsearch.service entered failed state.
Apr 16 21:30:02 host3 systemd[1]: elasticsearch.service failed.
Apr 16 21:30:02 host3 yum[3581]: Updated: elasticsearch-7.10.2-1.x86_64
```

**Comment by sbruno** [comment]
This is the same problem as reported in this old bug: https://github.com/elastic/elasticsearch/issues/23785
I'm adding the comment I posted there since I couldn't reopen it:

I tried to debug the problem so I created RPM packages where I added `find /usr/share/elasticsearch/lib`  commands in the `post`, `prerm` and `postrm` scripts

Turns out that `post` of the new package is executed before the old package is removed and actually `find` command shows that jar files for both packages exist at the same time. Sounds weird but that's what I see. And the service is restarted in the `post`.

In fact I then tried doing upgrades on other versions and got different errors, but all of them seem to be related with having both packages installed at the same time.
When upgrading form 7.11.0 to 7.12.0 I get:
```
2021-04-16T18:53:58,634][WARN ][stderr                   ] [host3] Exception in thread "main" java.lang.AssertionError: Lucene version mismatch this version of Elasticsearch requires lucene version [8.7.0]  but the current lucene version is [8.8.0]
[2021-04-16T18:53:58,636][WARN ][stderr                   ] [host3]     at org.elasticsearch.bootstrap.Bootstrap.checkLucene(Bootstrap.java:460)
[2021-04-16T18:53:58,636][WARN ][stderr                   ] [host3]     at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:380)
[2021-04-16T18:53:58,636][WARN ][stderr                   ] [host3]     at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
[2021-04-16T18:53:58,636][WARN ][stderr                   ] [host3]     at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
[2021-04-16T18:53:58,637][WARN ][stderr                   ] [host3]     at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
[2021-04-16T18:53:58,637][WARN ][stderr                   ] [host3]     at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
[2021-04-16T18:53:58,637][WARN ][stderr                   ] [host3]     at org.elasticsearch.cli.Command.main(Command.java:79)
[2021-04-16T18:53:58,637][WARN ][stderr                   ] [host3]     at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115)
[2021-04-16T18:53:58,637][WARN ][stderr                   ] [host3]     at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81)
```

On another upgrade combination I got:
```
Apr 16 16:31:50 host8 systemd-entrypoint[4179]: Exception in thread "main" java.lang.IllegalArgumentException: expected one argument specifying path to ES_PATH_CONF but was [/etc/elasticsearch, /usr/share/elasticsearch/plugins]
Apr 16 16:31:50 host8 systemd-entrypoint[4179]: 	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:82)
```

I tried moving the restart code from `post` to `posttrans`, which executes after the old package is removed, and it worked but I think that that way it is not possible to conditionally run it on upgrades but not in clean installations since `$1` will always be `0`. That is my understanding of it.

**Comment by mark-vieira** [comment]
Well my first thought here was "why aren't are upgrade tests catching this?". And then I realized they aren't running. I'm going to first get that sorted out so we can at least reproduce this easily.

**Comment by gitpel** [comment]
You should use *systemd override file*
https://www.elastic.co/guide/en/elasticsearch/reference/current/setting-system-settings.html#systemd

> *systemd units* need not obey files in /etc/default. Systemd is easily configurable, but requires that you know the syntax of systemd unit files.

create the file `/etc/systemd/system/elasticsearch.service.d/override.conf` with the content:
```
[Service]
Environment=RESTART_ON_UPGRADE=true
```

**Comment by mark-vieira** [comment]
I believe this might have been related to https://github.com/elastic/elasticsearch/pull/84224 as well. Our upgrade tests are now running so I presume this issue is fixed.
