### ISSUE TITLE
[CI] IndexShardTests testIndexCheckOnStartup failing

### ISSUE THREAD

**Issue by valeriy42** [elastic/elasticsearch#71827]
Failure message says "org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported ... : 256 (needs to be between 0 and 0)", so I guess maybe there is a problem with this test configuration.

**Build scan:**
https://gradle-enterprise.elastic.co/s/otcaa5pisr3fq/tests/:server:test/org.elasticsearch.index.shard.IndexShardTests/testIndexCheckOnStartup

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.index.shard.IndexShardTests.testIndexCheckOnStartup" -Dtests.seed=4EECBCE5A54FDD77 -Dtests.security.manager=true -Dtests.locale=es-CU -Dtests.timezone=Atlantic/Stanley -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.index.shard.IndexShardTests&tests.test=testIndexCheckOnStartup

**Failure excerpt:**
```
org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource MockIndexInputWrapper(MMapIndexInput(path="/private/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-darwin-compatibility/server/build/testrun/test/temp/org.elasticsearch.index.shard.IndexShardTests_4EECBCE5A54FDD77-001/tempDir-140/indices/_na_/0/index/_0.cfs") [slice=_0.kdd])): 256 (needs to be between 0 and 0)

  at __randomizedtesting.SeedInfo.seed([4EECBCE5A54FDD77:4F4A694CAFC91FAF]:0)
  at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:216)
  at org.apache.lucene.codecs.CodecUtil.checkHeader(CodecUtil.java:198)
  at org.apache.lucene.codecs.CodecUtil.checkIndexHeader(CodecUtil.java:255)
  at org.apache.lucene.codecs.lucene86.Lucene86PointsReader.<init>(Lucene86PointsReader.java:68)
  at org.apache.lucene.codecs.lucene86.Lucene86PointsFormat.fieldsReader(Lucene86PointsFormat.java:78)
  at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:136)
  at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:83)
  at org.apache.lucene.index.CheckIndex.checkIndex(CheckIndex.java:676)
  at org.apache.lucene.util.TestUtil.checkIndex(TestUtil.java:301)
  at org.apache.lucene.store.MockDirectoryWrapper.close(MockDirectoryWrapper.java:867)
  at org.apache.lucene.store.FilterDirectory.close(FilterDirectory.java:110)
  at org.elasticsearch.index.shard.IndexShardTests.testIndexCheckOnStartup(IndexShardTests.java:3100)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by andreidan** [comment]
Another instance https://gradle-enterprise.elastic.co/s/noleknwty4e4i
