### ISSUE TITLE
[CI] SysVInitTests test20Start failing

### ISSUE THREAD

**Issue by valeriy42** [elastic/elasticsearch#71848]
Failed 17 times since last Friday.

**Build scan:**
https://gradle-enterprise.elastic.co/s/sxwsyjm6ks7xi/tests/:qa:os:destructiveDistroTest.default-rpm/org.elasticsearch.packaging.test.SysVInitTests/test20Start

**Reproduction line:**
`null`

**Applicable branches:**
7.x

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.SysVInitTests&tests.test=test20Start

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: a string containing "\"count\" : 2"
     but: was "{
  "count" : 5,
  "_shards" : {
    "total" : 2,
    "successful" : 2,
    "skipped" : 0,
    "failed" : 0
  }
}
"

  at __randomizedtesting.SeedInfo.seed([A9FEC05361B78BF5:39DFFBD11FB3DD52]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
  at org.elasticsearch.packaging.util.ServerUtils.runElasticsearchTests(ServerUtils.java:236)
  at org.elasticsearch.packaging.test.SysVInitTests.test20Start(SysVInitTests.java:51)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by probakowski** [comment]
This is caused by enabling GeoIp downloader by default, I'll fix it
