### ISSUE TITLE
[CI] AllocationFilteringIntegTests testReplacesIncludeFilter failing

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#71910]
There seems to be an issue with initialising the searchable snapshots local cache on windows agents

```
java.io.UncheckedIOException: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\x-pack\plugin\searchable-snapshots\build\testrun\internalClusterTest\temp\org.elasticsearch.xpack.searchablesnapshots.allocation.AllocationFilteringIntegTests_601AC13B866DEDDF-001\tempDir-003\node_t1\indices\Rp2yWI6uTaO0QBg_AViMUg\2\snapshot_cache\AZ2Gu118RP6UWvbQaBiEPA\xEHsNSo-Q3-bN98vqFb4eA	
	at __randomizedtesting.SeedInfo.seed([601AC13B866DEDDF]:0)	
	at org.elasticsearch.common.util.concurrent.AbstractRefCounted.decRef(AbstractRefCounted.java:57)	
	at org.elasticsearch.xpack.searchablesnapshots.cache.common.CacheFile.decrementRefCount(CacheFile.java:247)	
	at org.elasticsearch.xpack.searchablesnapshots.cache.common.CacheFile.startEviction(CacheFile.java:275)	
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:74)	
	at org.elasticsearch.core.internal.io.IOUtils.closeWhileHandlingException(IOUtils.java:164)	
	at org.elasticsearch.xpack.searchablesnapshots.cache.full.CacheService.onCacheFileEviction(CacheService.java:485)	
	at org.elasticsearch.xpack.searchablesnapshots.cache.full.CacheService.lambda$new$1(CacheService.java:161)
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/ctfljqpopldba/tests/:x-pack:plugin:searchable-snapshots:internalClusterTest/org.elasticsearch.xpack.searchablesnapshots.allocation.AllocationFilteringIntegTests/testReplacesIncludeFilter

**Reproduction line:**
`gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.allocation.AllocationFilteringIntegTests.testReplacesIncludeFilter" -Dtests.seed=601AC13B866DEDDF -Dtests.security.manager=true -Dtests.locale=es-PY -Dtests.timezone=America/Detroit -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.searchablesnapshots.allocation.AllocationFilteringIntegTests&tests.test=testReplacesIncludeFilter

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=108, name=elasticsearch[node_t1][generic][T#1], state=RUNNABLE, group=TGRP-AllocationFilteringIntegTests]

  at __randomizedtesting.SeedInfo.seed([601AC13B866DEDDF:67B382AFD260FC5E]:0)

  Caused by: java.lang.AssertionError: java.io.UncheckedIOException: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\x-pack\plugin\searchable-snapshots\build\testrun\internalClusterTest\temp\org.elasticsearch.xpack.searchablesnapshots.allocation.AllocationFilteringIntegTests_601AC13B866DEDDF-001\tempDir-003\node_t1\indices\Rp2yWI6uTaO0QBg_AViMUg\2\snapshot_cache\AZ2Gu118RP6UWvbQaBiEPA\xEHsNSo-Q3-bN98vqFb4eA

    at __randomizedtesting.SeedInfo.seed([601AC13B866DEDDF]:0)
    at org.elasticsearch.common.util.concurrent.AbstractRefCounted.decRef(AbstractRefCounted.java:57)
    at org.elasticsearch.xpack.searchablesnapshots.cache.common.CacheFile.decrementRefCount(CacheFile.java:247)
    at org.elasticsearch.xpack.searchablesnapshots.cache.common.CacheFile.startEviction(CacheFile.java:275)
    at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:74)
    at org.elasticsearch.core.internal.io.IOUtils.closeWhileHandlingException(IOUtils.java:164)
    at org.elasticsearch.xpack.searchablesnapshots.cache.full.CacheService.onCacheFileEviction(CacheService.java:485)
    at org.elasticsearch.xpack.searchablesnapshots.cache.full.CacheService.lambda$new$1(CacheService.java:161)
    at org.elasticsearch.common.cache.Cache.delete(Cache.java:788)
    at org.elasticsearch.common.cache.Cache.lambda$new$6(Cache.java:488)
    at org.elasticsearch.common.cache.Cache$CacheSegment.remove(Cache.java:305)
    at org.elasticsearch.common.cache.Cache.invalidate(Cache.java:518)
    at org.elasticsearch.xpack.searchablesnapshots.cache.full.CacheService.processShardEviction(CacheService.java:409)
    at org.elasticsearch.xpack.searchablesnapshots.cache.full.CacheService$1.doRun(CacheService.java:345)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:669)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)

    Caused by: java.io.UncheckedIOException: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\x-pack\plugin\searchable-snapshots\build\testrun\internalClusterTest\temp\org.elasticsearch.xpack.searchablesnapshots.allocation.AllocationFilteringIntegTests_601AC13B866DEDDF-001\tempDir-003\node_t1\indices\Rp2yWI6uTaO0QBg_AViMUg\2\snapshot_cache\AZ2Gu118RP6UWvbQaBiEPA\xEHsNSo-Q3-bN98vqFb4eA

      at org.elasticsearch.xpack.searchablesnapshots.cache.common.CacheFile$1.closeInternal(CacheFile.java:71)
      at org.elasticsearch.common.util.concurrent.AbstractRefCounted.decRef(AbstractRefCounted.java:55)
      at org.elasticsearch.xpack.searchablesnapshots.cache.common.CacheFile.decrementRefCount(CacheFile.java:247)
      at org.elasticsearch.xpack.searchablesnapshots.cache.common.CacheFile.startEviction(CacheFile.java:275)
      at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:74)
      at org.elasticsearch.core.internal.io.IOUtils.closeWhileHandlingException(IOUtils.java:164)
      at org.elasticsearch.xpack.searchablesnapshots.cache.full.CacheService.onCacheFileEviction(CacheService.java:485)
      at org.elasticsearch.xpack.searchablesnapshots.cache.full.CacheService.lambda$new$1(CacheService.java:161)
      at org.elasticsearch.common.cache.Cache.delete(Cache.java:788)
      at org.elasticsearch.common.cache.Cache.lambda$new$6(Cache.java:488)
      at org.elasticsearch.common.cache.Cache$CacheSegment.remove(Cache.java:305)
      at org.elasticsearch.common.cache.Cache.invalidate(Cache.java:518)
      at org.elasticsearch.xpack.searchablesnapshots.cache.full.CacheService.processShardEviction(CacheService.java:409)
      at org.elasticsearch.xpack.searchablesnapshots.cache.full.CacheService$1.doRun(CacheService.java:345)
      at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
      at java.util.concurrent.FutureTask.run(FutureTask.java:264)
      at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:669)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
      at java.lang.Thread.run(Thread.java:834)

      Caused by: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\x-pack\plugin\searchable-snapshots\build\testrun\internalClusterTest\temp\org.elasticsearch.xpack.searchablesnapshots.allocation.AllocationFilteringIntegTests_601AC13B866DEDDF-001\tempDir-003\node_t1\indices\Rp2yWI6uTaO0QBg_AViMUg\2\snapshot_cache\AZ2Gu118RP6UWvbQaBiEPA\xEHsNSo-Q3-bN98vqFb4eA

        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:270)
        at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
        at org.apache.lucene.mockfile.FilterFileSystemProvider.deleteIfExists(FilterFileSystemProvider.java:238)
        at org.apache.lucene.mockfile.FilterFileSystemProvider.deleteIfExists(FilterFileSystemProvider.java:238)
        at org.apache.lucene.mockfile.FilterFileSystemProvider.deleteIfExists(FilterFileSystemProvider.java:238)
        at org.apache.lucene.mockfile.FilterFileSystemProvider.deleteIfExists(FilterFileSystemProvider.java:238)
        at java.nio.file.Files.deleteIfExists(Files.java:1180)
        at org.elasticsearch.xpack.searchablesnapshots.cache.common.CacheFile$1.closeInternal(CacheFile.java:69)
        at org.elasticsearch.common.util.concurrent.AbstractRefCounted.decRef(AbstractRefCounted.java:55)
        at org.elasticsearch.xpack.searchablesnapshots.cache.common.CacheFile.decrementRefCount(CacheFile.java:247)
        at org.elasticsearch.xpack.searchablesnapshots.cache.common.CacheFile.startEviction(CacheFile.java:275)
        at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:74)
        at org.elasticsearch.core.internal.io.IOUtils.closeWhileHandlingException(IOUtils.java:164)
        at org.elasticsearch.xpack.searchablesnapshots.cache.full.CacheService.onCacheFileEviction(CacheService.java:485)
        at org.elasticsearch.xpack.searchablesnapshots.cache.full.CacheService.lambda$new$1(CacheService.java:161)
        at org.elasticsearch.common.cache.Cache.delete(Cache.java:788)
        at org.elasticsearch.common.cache.Cache.lambda$new$6(Cache.java:488)
        at org.elasticsearch.common.cache.Cache$CacheSegment.remove(Cache.java:305)
        at org.elasticsearch.common.cache.Cache.invalidate(Cache.java:518)
        at org.elasticsearch.xpack.searchablesnapshots.cache.full.CacheService.processShardEviction(CacheService.java:409)
        at org.elasticsearch.xpack.searchablesnapshots.cache.full.CacheService$1.doRun(CacheService.java:345)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:669)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(Thread.java:834)

```

**Comment by mark-vieira** [comment]
This looks to be the same as https://github.com/elastic/elasticsearch/issues/71887. This should be sorted out now.
