### ISSUE TITLE
[CI] SearchableSnapshotIndexMetadataUpgraderTests.testUpgradeIndices

### ISSUE THREAD

**Issue by henningandersen** [elastic/elasticsearch#71973]
**Build scan**:
https://gradle-enterprise.elastic.co/s/hfll4qbiunmmy (7.x)
https://gradle-enterprise.elastic.co/s/7kqvtj64bdnew (master)
**Repro line**:

(from 7.x)
```
./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.xpack.searchablesnapshots.upgrade.SearchableSnapshotIndexMetadataUpgraderTests.testUpgradeIndices" -Dtests.seed=26B49F246A6B424 -Dtests.locale=sr-Latn -Dtests.timezone=Africa/Bissau -Druntime.java=8
```

**Reproduces locally?**:
yes

**Applicable branches**:
7.x, master

**Failure history**:
Only failed [twice so far](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testUpgradeIndices),sort:!(process.time-start,desc))) but was recently added.

**Failure excerpt**:

org.elasticsearch.xpack.searchablesnapshots.upgrade.SearchableSnapshotIndexMetadataUpgraderTests > testUpgradeIndices FAILED
    java.lang.AssertionError: 
    Expected: "frozen"
         but: was "normal"
        at __randomizedtesting.SeedInfo.seed([26B49F246A6B424:D64E14474C5532D1]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.searchablesnapshots.upgrade.SearchableSnapshotIndexMetadataUpgraderTests.lambda$testUpgradeIndices$0(SearchableSnapshotIndexMetadataUpgraderTests.java:70)
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
        at org.elasticsearch.xpack.searchablesnapshots.upgrade.SearchableSnapshotIndexMetadataUpgraderTests.testUpgradeIndices(SearchableSnapshotIndexMetadataUpgraderTests.java:58)

**Comment by henningandersen** [comment]
Muted in #71974
