### ISSUE TITLE
TestFeatureResetIT:testTransformFeatureReset fails due to index being recreated

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#72019]
**Build scan**:
https://gradle-enterprise.elastic.co/s/ogr7ullbtioag
**Repro line**:
```
./gradlew ':x-pack:plugin:transform:qa:multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.transform.integration.TestFeatureResetIT.testTransformFeatureReset" -Dtests.seed=EBF6A4F1FDBB418C -Dtests.locale=hi-IN -Dtests.timezone=America/Havana -Druntime.java=11
```
**Reproduces locally?**:
Not really
**Applicable branches**:
Master, 7.x

**Failure excerpt**:
org.elasticsearch.xpack.transform.integration.TestFeatureResetIT > testTransformFeatureReset FAILED
    java.lang.AssertionError: 
    Expected: is a map with size <0>
         but: map size was <1>
        at __randomizedtesting.SeedInfo.seed([EBF6A4F1FDBB418C:F6E3555DA4AAA438]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.transform.integration.TestFeatureResetIT.testTransformFeatureReset(TestFeatureResetIT.java:88)

From the cluster logs:

```
[2021-04-21T13:55:59,592][INFO ][o.e.c.m.MetadataDeleteIndexService] [javaRestTest-2] [.transform-notifications-000002/19JpP7suRVS3awoEAVO4xA] deleting index
[2021-04-21T13:55:59,592][INFO ][o.e.c.m.MetadataDeleteIndexService] [javaRestTest-2] [.transform-internal-007/tmX-n1HhSUCbsH7SDXH8Ig] deleting index
[2021-04-21T13:55:59,684][INFO ][o.e.c.m.MetadataCreateIndexService] [javaRestTest-2] [.transform-notifications-000002] creating index, cause [auto(bulk api)], templates [.transform-notifications-000002], shards [1]/[1]
```

Transform notifications index was recreated AFTER the feature reset was completed. Unsure if this is due to the test or something writing a notification while reset mode is active.

Digging

**Comment by benwtrent** [comment]
This has not failed in the same way since merging: https://github.com/elastic/elasticsearch/pull/72171

Closing issue
