### ISSUE TITLE
[CI] DateUtilsTests testTimezoneIds failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#72028]
This reproduced locally for me on Java 17.

**Build scan:**
https://gradle-enterprise.elastic.co/s/zcqrrhsg4t4me/tests/:server:test/org.elasticsearch.common.time.DateUtilsTests/testTimezoneIds

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.common.time.DateUtilsTests.testTimezoneIds" -Dtests.seed=3CBDAF986A64CE13 -Dtests.locale=ms -Dtests.timezone=Africa/Luanda -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.common.time.DateUtilsTests&tests.test=testTimezoneIds

**Failure excerpt:**
```
java.lang.AssertionError: Australia/Currie
Expected: <36000000>
     but: was <39600000>

  at __randomizedtesting.SeedInfo.seed([3CBDAF986A64CE13:E058F20227C88735]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.elasticsearch.common.time.DateUtilsTests.testTimezoneIds(DateUtilsTests.java:50)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:831)

```

**Comment by rjernst** [comment]
@pgomulka Can you take a look at this?

**Comment by pgomulka** [comment]
the jdk17 ships with latest tzdata2021a
The Australia/Currie is not mentioned in a changelist. But if you read the `NEWS` file in the timezone db itself it mentiones there are some changes
```
 Changes to past timestamps

    Correct many pre-1986 transitions, fixing entries originally
    derived from Shanks.  The fixes include:
      - Australia: several 1917 through 1971 transitions
      - Bahamas: several 1941 through 1945 transitions
      - Bermuda: several 1917 through 1956 transitions
      - Belize: several 1942 through 1968 transitions
      - Ghana: several 1915 through 1956 transitions
      - Israel and Palestine: several 1940 through 1985 transitions
      - Kenya and adjacent: several 1908 through 1960 transitions
      - Nigeria and adjacent: correcting LMT in Lagos, and several 1905
        through 1919 transitions
      - Seychelles: the introduction of standard time in 1907, not 1906
      - Vanuatu: DST in 1973-1974, and a corrected 1984 transition
    (Thanks to P Chan.)

    Because of the Australia change, Australia/Currie (King Island) is
    no longer needed, as it is identical to Australia/Hobart for all
    timestamps since 1970 and was therefore created by mistake.
    Australia/Currie has been moved to the 'backward' file and its
    corrected data moved to the 'backzone' file.

```

The tzdata2021a is available in 
```
16.0.1
11.0.11
8u291
7u301
```

https://www.oracle.com/java/technologies/tzdata-versions.html

latest 2.10-10 joda also has it, so joda update should fix.
I will create a PR.

Do we have jdk 16, 11, 8 and 7 also up to date? This might start failing on those JDKs once I update joda to latest

**Comment by mark-vieira** [comment]
> Do we have jdk 16, 11, 8 and 7 also up to date? 

They should be. I'm not sure for 11 and older but the initial GA release of 16 is still the only one that exists and is what we're using.

**Comment by pgomulka** [comment]
yesterday they released https://www.oracle.com/java/technologies/javase/16-0-1-relnotes.html  and it  also contains latest timezone dbs

**Comment by mark-vieira** [comment]
Yeah, I suspect that has not percolated through CI yet. Good catch.

**Comment by jtibshirani** [comment]
I muted this while we wait for it to be fixed.
* `master`: 541546a
* `7.x`: 693fe33
* `7.13`: 617bf69

**Comment by jbaiera** [comment]
There is now a failure on JDK 16 https://gradle-enterprise.elastic.co/s/qilw7noeoooxe/tests/:server:test/org.elasticsearch.common.time.DateUtilsTests/testTimezoneIds#1

**Comment by BigPandaToo** [comment]
Seeing it again:
https://gradle-enterprise.elastic.co/s/o7672p4lf3frq/console-log?task=:server:unitTest

**Comment by BigPandaToo** [comment]
In 6.8 and 7.12

**Comment by davidkyle** [comment]
The test has been muted on the 7.12 branch in 5fbfe9b

**Comment by mayya-sharipova** [comment]
Multiple failures on this test on 6.8 branch as well. I've muted this test on 6.8 in https://github.com/elastic/elasticsearch/commit/7d707f1ea2a1b5fc18933b157c56209124787235

**Comment by pgomulka** [comment]
reopening until 7.x and 6.8 branches are fine

**Comment by pgomulka** [comment]
the update was backported
