### ISSUE TITLE
[CI] KerberosAuthenticationIT testLoginByUsernamePassword failing

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#72120]
Looks JDK 17 related. Fails infrequently (2 failures out of 181 tests today). Tried to reproduce locally but couldn't get it to happen.

**Build scan:**
https://gradle-enterprise.elastic.co/s/cvahumzluevq2/tests/:x-pack:qa:kerberos-tests:integTest/org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT/testLoginByUsernamePassword

**Reproduction line:**
`./gradlew ':x-pack:qa:kerberos-tests:integTest' --tests "org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT.testLoginByUsernamePassword" -Dtests.seed=7D98DB14CF7C00EE -Dtests.locale=de-DE -Dtests.timezone=America/Toronto -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT&tests.test=testLoginByUsernamePassword

**Failure excerpt:**
```
java.lang.RuntimeException: javax.security.auth.login.LoginException: no supported default etypes for default_tkt_enctypes

  at __randomizedtesting.SeedInfo.seed([7D98DB14CF7C00EE:45B9D22D1EA00877]:0)
  at org.elasticsearch.xpack.security.authc.kerberos.SpnegoHttpClientConfigCallbackHandler.setupSpnegoAuthSchemeSupport(SpnegoHttpClientConfigCallbackHandler.java:142)
  at org.elasticsearch.xpack.security.authc.kerberos.SpnegoHttpClientConfigCallbackHandler.customizeHttpClient(SpnegoHttpClientConfigCallbackHandler.java:116)
  at org.elasticsearch.client.RestClientBuilder.createHttpClient(RestClientBuilder.java:291)
  at java.security.AccessController.doPrivileged(AccessController.java:312)
  at org.elasticsearch.client.RestClientBuilder.build(RestClientBuilder.java:266)
  at org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT.buildRestClientForKerberos(KerberosAuthenticationIT.java:191)
  at org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT.executeRequestAndVerifyResponse(KerberosAuthenticationIT.java:157)
  at org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT.testLoginByUsernamePassword(KerberosAuthenticationIT.java:108)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:831)

  Caused by: javax.security.auth.login.LoginException: no supported default etypes for default_tkt_enctypes

    at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:787)
    at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:597)
    at javax.security.auth.login.LoginContext.invoke(LoginContext.java:726)
    at javax.security.auth.login.LoginContext$4.run(LoginContext.java:665)
    at javax.security.auth.login.LoginContext$4.run(LoginContext.java:663)
    at java.security.AccessController.doPrivileged(AccessController.java:691)
    at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663)
    at javax.security.auth.login.LoginContext.login(LoginContext.java:574)
    at org.elasticsearch.xpack.security.authc.kerberos.SpnegoHttpClientConfigCallbackHandler.lambda$login$1(SpnegoHttpClientConfigCallbackHandler.java:169)
    at java.security.AccessController.doPrivileged(AccessController.java:554)
    at org.elasticsearch.xpack.security.authc.kerberos.SpnegoHttpClientConfigCallbackHandler.login(SpnegoHttpClientConfigCallbackHandler.java:156)
    at org.elasticsearch.xpack.security.authc.kerberos.SpnegoHttpClientConfigCallbackHandler.setupSpnegoAuthSchemeSupport(SpnegoHttpClientConfigCallbackHandler.java:127)
    at org.elasticsearch.xpack.security.authc.kerberos.SpnegoHttpClientConfigCallbackHandler.customizeHttpClient(SpnegoHttpClientConfigCallbackHandler.java:116)
    at org.elasticsearch.client.RestClientBuilder.createHttpClient(RestClientBuilder.java:291)
    at java.security.AccessController.doPrivileged(AccessController.java:312)
    at org.elasticsearch.client.RestClientBuilder.build(RestClientBuilder.java:266)
    at org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT.buildRestClientForKerberos(KerberosAuthenticationIT.java:191)
    at org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT.executeRequestAndVerifyResponse(KerberosAuthenticationIT.java:157)
    at org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT.testLoginByUsernamePassword(KerberosAuthenticationIT.java:108)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:568)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
    at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
    at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
    at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
    at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
    at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
    at java.lang.Thread.run(Thread.java:831)

    Caused by: sun.security.krb5.KrbException: no supported default etypes for default_tkt_enctypes

      at sun.security.krb5.Config.defaultEtype(Config.java:1014)
      at sun.security.krb5.internal.crypto.EType.getDefaults(EType.java:264)
      at sun.security.krb5.KrbAsReqBuilder.build(KrbAsReqBuilder.java:272)
      at sun.security.krb5.KrbAsReqBuilder.send(KrbAsReqBuilder.java:344)
      at sun.security.krb5.KrbAsReqBuilder.action(KrbAsReqBuilder.java:498)
      at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:749)
      at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:597)
      at javax.security.auth.login.LoginContext.invoke(LoginContext.java:726)
      at javax.security.auth.login.LoginContext$4.run(LoginContext.java:665)
      at javax.security.auth.login.LoginContext$4.run(LoginContext.java:663)
      at java.security.AccessController.doPrivileged(AccessController.java:691)
      at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663)
      at javax.security.auth.login.LoginContext.login(LoginContext.java:574)
      at org.elasticsearch.xpack.security.authc.kerberos.SpnegoHttpClientConfigCallbackHandler.lambda$login$1(SpnegoHttpClientConfigCallbackHandler.java:169)
      at java.security.AccessController.doPrivileged(AccessController.java:554)
      at org.elasticsearch.xpack.security.authc.kerberos.SpnegoHttpClientConfigCallbackHandler.login(SpnegoHttpClientConfigCallbackHandler.java:156)
      at org.elasticsearch.xpack.security.authc.kerberos.SpnegoHttpClientConfigCallbackHandler.setupSpnegoAuthSchemeSupport(SpnegoHttpClientConfigCallbackHandler.java:127)
      at org.elasticsearch.xpack.security.authc.kerberos.SpnegoHttpClientConfigCallbackHandler.customizeHttpClient(SpnegoHttpClientConfigCallbackHandler.java:116)
      at org.elasticsearch.client.RestClientBuilder.createHttpClient(RestClientBuilder.java:291)
      at java.security.AccessController.doPrivileged(AccessController.java:312)
      at org.elasticsearch.client.RestClientBuilder.build(RestClientBuilder.java:266)
      at org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT.buildRestClientForKerberos(KerberosAuthenticationIT.java:191)
      at org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT.executeRequestAndVerifyResponse(KerberosAuthenticationIT.java:157)
      at org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT.testLoginByUsernamePassword(KerberosAuthenticationIT.java:108)
      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
      at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:568)
      at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
      at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
      at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
      at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
      at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
      at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
      at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
      at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
      at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
      at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
      at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
      at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
      at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
      at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
      at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
      at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
      at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
      at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
      at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
      at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
      at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
      at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
      at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
      at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
      at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
      at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
      at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
      at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
      at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
      at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
      at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
      at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
      at java.lang.Thread.run(Thread.java:831)

```

**Comment by jbaiera** [comment]
Also seems to fail concurrently with the `testGetOauth2TokenInExchangeForKerberosTickets` and `testLoginByKeytab` tests as well

**Comment by davidkyle** [comment]
Another one https://gradle-enterprise.elastic.co/s/ixrbo343zx7km

**Comment by cbuescher** [comment]
Another one on master: https://gradle-enterprise.elastic.co/s/y5ld5n36pkgxg

**Comment by benwtrent** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/owxoenkuuv3uc

Java 17 doesn't like this test (or vice versa). But, with Java 17 locally, it does not repeatably fail...

```
./gradlew ':x-pack:qa:kerberos-tests:integTest' --tests "org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT.testGetOauth2TokenInExchangeForKerberosTickets" -Dtests.seed=932F61D7EA0BE5A -Dtests.locale=zh -Dtests.timezone=Africa/Niamey -Druntime.java=17 -Dtests.fips.enabled=true
```

**Comment by ywangd** [comment]
Another one, also JDK 17: https://gradle-enterprise.elastic.co/s/fvwa72nsgpaty

**Comment by cbuescher** [comment]
These from today look related as well, although its also two other tests in that suite failing:
```
org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT testGetOauth2TokenInExchangeForKerberosTickets
org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT testLoginByKeytab
org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT testLoginByUsernamePassword
```

https://gradle-enterprise.elastic.co/s/nkbph5n6sqfuu

**Comment by BigPandaToo** [comment]
One more today:
https://gradle-enterprise.elastic.co/s/4xyqudebfd5z4/console-log?task=:x-pack:qa:kerberos-tests:integTest

**Comment by matriv** [comment]
One more failure, opened and closed the issue, but you can find the relevant info here: #73453

**Comment by matriv** [comment]
and once more: https://gradle-enterprise.elastic.co/s/hhhdrlwmwg6yy

**Comment by williamrandolph** [comment]
It will probably not surprise you to learn out that this happened again today, and again with Java 17-ea: https://gradle-enterprise.elastic.co/s/l6o2pyyidbuqa

```
=======================================
  | Elasticsearch Build Hamster says Hello!
  | Gradle Version        : 7.0.2
  | OS Info               : Linux 3.10.0-1160.25.1.el7.x86_64 (amd64)
  | Runtime JDK Version   : 17-ea (Oracle)
  | Runtime java.home     : /var/lib/jenkins/.java/openjdk17
  | Gradle JDK Version    : 15.0.2 (Oracle)
  | Gradle java.home      : /var/lib/jenkins/.java/openjdk-15.0.2+7-linux
  | Random Testing Seed   : F901676C1A1D9357
  | In FIPS 140 mode      : true
  | =======================================
```

Since this is moderately noisy, I'm going to mute for `"17-ea".equals(System.getProperty("java.version"))` only.

**Comment by williamrandolph** [comment]
Mute commit: 6ca471beb6b596bde0a100aabc82d0cf914de847

Also, here's the list of failures: https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/New_York&tests.container=org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT&tests.sortField=FAILED&tests.test=testLoginByKeytab&tests.unstableOnly=true

It seems to show that this only happens on the master branch, for Java 17-ea, whether or not FIPS is enabled.

**Comment by tlrx** [comment]
Happened also on 7.x today, with 17-ea (https://gradle-enterprise.elastic.co/s/x3me6lelg4xck). I'll mute on 7.x too.

**Comment by dimitris-athanasiou** [comment]
Got new failures in `7.14`: https://gradle-enterprise.elastic.co/s/4vu52efvmsxyo. It seems when using java 17 as runtime we now use the normal candidate:

```
=======================================
   | Elasticsearch Build Hamster says Hello!
   | Gradle Version        : 7.1
   | OS Info               : Linux 4.15.0-1098-gcp (amd64)
   | Runtime JDK Version   : 17 (Oracle)
   | Runtime java.home     : /var/lib/jenkins/.java/openjdk17
   | Gradle JDK Version    : 16.0.2 (Oracle)
   | Gradle java.home      : /var/lib/jenkins/.java/openjdk-16.0.2+7-linux
   | Random Testing Seed   : 494CFD6F916E230A
   | In FIPS 140 mode      : false
=======================================
```

I will change the mute accordingly.

**Comment by tlrx** [comment]
@dimitris-athanasiou the test failed again today on 7.15 though it should be muted on that branch since #76229.

**Comment by dimitris-athanasiou** [comment]
The mute there is based on the java version being `17`:

```
assumeFalse("This test fails often on Java 17 early access. See: https://github.com/elastic/elasticsearch/issues/72120",
            "17".equals(System.getProperty("java.version")));
```

I assume that's not the case any more? CI was running on `openjdk17`, not sure if that results to a different java version than the `17` string.

**Comment by tlrx** [comment]
> JVM home [/var/lib/jenkins/.java/openjdk-17.0.1+12-linux], using bundled JDK [false]

I'll try to reproduce locally and see what string is returned.

**Comment by tlrx** [comment]
This test takes quite some effort from different people to just mute it correctly, that would be great if someone from  @elastic/es-security could work on the test to make it pass on JDK17 if possible or have a more reliable way to skip it on some JDK rather than having test triage developpers trying to sort this out every month or so.

**Comment by probakowski** [comment]
Another failure on 7.15 https://gradle-enterprise.elastic.co/s/q424mci2xwmci

**Comment by jkakavas** [comment]
AFAICT this was failing because we were using `des3-cbc-sha1-kd` for default enctypes and JDK17 disallows weak encryption types by default. This was fixed ( replaced default encytpe with `aes256-cts-hmac-sha1-96` ) in https://github.com/elastic/elasticsearch/pull/78703 but the tests were already muted when this was merged. https://github.com/elastic/elasticsearch/pull/78703 never made it back to 7.15 and this is why this still fails for 7.15

**Comment by jkakavas** [comment]
resolved by https://github.com/elastic/elasticsearch/pull/80537
