### ISSUE TITLE
NPE thrown from RerunTestResultProcessor

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#72169]
When looking for instances of the retries happening I found this: https://gradle-enterprise.elastic.co/s/umk7jt4e3vpka

```
Received a completed event for test with unknown id '926.29'. Registered test ids: '[]'
java.lang.IllegalArgumentException: Received a completed event for test with unknown id '926.29'. Registered test ids: '[]'
        at org.gradle.api.internal.tasks.testing.results.StateTrackingTestResultProcessor.completed(StateTrackingTestResultProcessor.java:79)
        at org.elasticsearch.gradle.internal.test.rerun.executer.RerunTestResultProcessor.completed(RerunTestResultProcessor.java:61)
        at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.completed(AttachParentTestResultProcessor.java:56)
        at jdk.internal.reflect.GeneratedMethodAccessor842.invoke(Unknown Source)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:30)
        at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
        at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
        at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
        at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:832)
Failed to notify test listener internal.
org.gradle.internal.event.ListenerNotificationException: Failed to notify test listener internal.
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:89)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:346)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:249)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:141)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy109.output(Unknown Source)
        at org.gradle.api.internal.tasks.testing.results.StateTrackingTestResultProcessor.output(StateTrackingTestResultProcessor.java:112)
        at org.elasticsearch.gradle.internal.test.rerun.executer.RerunTestResultProcessor.output(RerunTestResultProcessor.java:66)
        at org.gradle.api.internal.tasks.testing.results.AttachParentTestResultProcessor.output(AttachParentTestResultProcessor.java:48)
        at jdk.internal.reflect.GeneratedMethodAccessor852.invoke(Unknown Source)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:30)
        at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
        at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
        at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
        at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:832)
```

**Comment by mark-vieira** [comment]
Looks like there have been a few of these: https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20*%0A%3E%20Cannot%20read%20field%20%22test%22%20because%20the%20return%20value%20of%20%22java.util.Map.get(Object)%22%20is%20null&search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles

**Comment by breskeby** [comment]
I think what's happening here is that we receive events of tests that have been scheduled for execution in the first run that run on a different test jvm that hasn't crashed yet. The way to go here IMO would be to ignore those incoming events that do not have an active test event in the current rerun. I'll look into providing a Fix for that

**Comment by mark-vieira** [comment]
Looks like this is still happening: https://gradle-enterprise.elastic.co/s/tjqvyqlm33s7y

**Comment by ywangd** [comment]
Here is one from 7.x intake: https://gradle-enterprise.elastic.co/s/jhwkh6qcbvwb4

Error message is:
```
Execution failed for task ':x-pack:plugin:ccr:qa:multi-cluster:follow-cluster'. |  
-- | --
  | > Received a completed event for test with unknown id ':x-pack:plugin:ccr:qa:multi-cluster:follow-cluster'. Registered test ids: '[]'

```

**Comment by mark-vieira** [comment]
Closing this given we reverted this for now.
