### ISSUE TITLE
[CI] HotThreadsIT testHotThreadsDontFail failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#72376]
This just failed once on 7.13 and doesn't seem reproducable locally, still opening since it might be a rare occasion worth looking into.

**Build scan:**
https://gradle-enterprise.elastic.co/s/idmnonuqte7z4/tests/:server:internalClusterTest/org.elasticsearch.action.admin.HotThreadsIT/testHotThreadsDontFail

**Reproduction line:**
`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.action.admin.HotThreadsIT.testHotThreadsDontFail" -Dtests.seed=806766200ECB9FAE -Dtests.locale=sq-AL -Dtests.timezone=Etc/GMT-8 -Druntime.java=8`

**Applicable branches:**
7.13

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.action.admin.HotThreadsIT&tests.test=testHotThreadsDontFail

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: is <false>
     but: was <true>

  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.action.admin.HotThreadsIT.testHotThreadsDontFail(HotThreadsIT.java:120)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by cbuescher** [comment]
Maybe also interesting from the logs:

```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=4229, name=elasticsearch[node_s2][generic][T#5], state=RUNNABLE, group=TGRP-HotThreadsIT]
Caused by: java.lang.AssertionError: 
Expected: an empty collection
     but: <[FailedNodeException[Failed node [h0TqmrPdRSKn1JtyJlHAXg]]; nested: RemoteTransportException[[node_s2][127.0.0.1:45322][cluster:monitor/nodes/hot_threads[n]]]; nested: ElasticsearchException[failed to detect hot threads]; nested: IllegalArgumentException[duration cannot be negative, was given [-5160]];]>
	at __randomizedtesting.SeedInfo.seed([806766200ECB9FAE]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.action.admin.HotThreadsIT$1.onResponse(HotThreadsIT.java:81)
	at org.elasticsearch.action.admin.HotThreadsIT$1.onResponse(HotThreadsIT.java:74)
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:83)
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:77)
	at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:445)
	at org.elasticsearch.action.support.nodes.TransportNodesAction.newResponseAsync(TransportNodesAction.java:157)
	at org.elasticsearch.action.support.nodes.TransportNodesAction.newResponse(TransportNodesAction.java:133)
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.lambda$finishHim$0(TransportNodesAction.java:267)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rjernst** [comment]
We discussed this failure in the core/infra sync today. I did a brief investigation last week. The assertion that failed is a new one we added because of failures we had seen in 6.8 for this test.

Thankfully the assertion caught a failure case we were missing before (which results in later failures anyways), but unfortunately the exception is incomplete. In particular, the stack frames of the innermost exception are lost in transit, which would tell us what part of HotThreads is reading a negative value and passing that to TimeValue.

@gwbrown Suggested adding assertions before every TimeValue creation in HotThreads, so that when this fails again, we can get a direct culprit, without needing to fix the exception infrastructure (which is sad but that is a much more complex beast to fix).

**Comment by gwbrown** [comment]
Now that https://github.com/elastic/elasticsearch/pull/72837 has been merged, we should see `AssertionError`s start popping up when this test would have failed with the above exception. These assertion errors will come with a full stack trace and `ThreadInfo` printed as part of the error, although you may have to look in the node logs to find it.

**Comment by astefan** [comment]
Two failures today:
https://gradle-enterprise.elastic.co/s/usl6gqrwkyvqy
https://gradle-enterprise.elastic.co/s/n3y3mfrudrxa2

**Comment by rjernst** [comment]
I don't actually see the new assertions added by Gordon, but there is an interesting exception internal to the JDK:

```
1> [2021-05-14T07:20:57,358][WARN ][o.e.m.o.OsProbe          ] [testIgnoreIdleThreads] exception retrieving total swap space size |  
-- | --
  | 1> java.lang.reflect.InvocationTargetException: null |  
  | 1> 	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source) ~[?:?] |  
  | 1> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] |  
  | 1> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281] |  
  | 1> 	at org.elasticsearch.monitor.os.OsProbe.getTotalSwapSpaceSize(OsProbe.java:150) ~[main/:?] |  
  | 1> 	at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:701) ~[main/:?] |  
  | 1> 	at org.elasticsearch.monitor.os.OsService.<init>(OsService.java:39) ~[main/:?] |  
  | 1> 	at org.elasticsearch.monitor.MonitorService.<init>(MonitorService.java:33) ~[main/:?] |  
  | 1> 	at org.elasticsearch.node.Node.<init>(Node.java:423) ~[main/:?] |  
  | 1> 	at org.elasticsearch.node.MockNode.<init>(MockNode.java:88) ~[framework-7.12.2-SNAPSHOT.jar:?] |  
  | 1> 	at org.elasticsearch.node.MockNode.<init>(MockNode.java:78) ~[framework-7.12.2-SNAPSHOT.jar:?] |  
  | 1> 	at org.elasticsearch.test.InternalTestCluster.buildNode(InternalTestCluster.java:726) ~[framework-7.12.2-SNAPSHOT.jar:7.12.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.test.InternalTestCluster.reset(InternalTestCluster.java:1251) ~[framework-7.12.2-SNAPSHOT.jar:7.12.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.test.InternalTestCluster.beforeTest(InternalTestCluster.java:1154) ~[framework-7.12.2-SNAPSHOT.jar:7.12.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.test.ESIntegTestCase.lambda$beforeInternal$0(ESIntegTestCase.java:370) ~[framework-7.12.2-SNAPSHOT.jar:7.12.2-SNAPSHOT] |  
  | 1> 	at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:187) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:211) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at org.elasticsearch.test.ESIntegTestCase.beforeInternal(ESIntegTestCase.java:379) [framework-7.12.2-SNAPSHOT.jar:7.12.2-SNAPSHOT] |  
  | 1> 	at org.elasticsearch.test.ESIntegTestCase.setupTestCluster(ESIntegTestCase.java:2236) [framework-7.12.2-SNAPSHOT.jar:7.12.2-SNAPSHOT] |  
  | 1> 	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source) ~[?:?] |  
  | 1> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] |  
  | 1> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281] |  
  | 1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:972) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49) [lucene-test-framework-8.8.0.jar:8.8.0 b10659f0fc18b58b90929cfdadde94544d202c4a - noble - 2021-01-25 19:07:47] |  
  | 1> 	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) [lucene-test-framework-8.8.0.jar:8.8.0 b10659f0fc18b58b90929cfdadde94544d202c4a - noble - 2021-01-25 19:07:47] |  
  | 1> 	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48) [lucene-test-framework-8.8.0.jar:8.8.0 b10659f0fc18b58b90929cfdadde94544d202c4a - noble - 2021-01-25 19:07:47] |  
  | 1> 	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) [lucene-test-framework-8.8.0.jar:8.8.0 b10659f0fc18b58b90929cfdadde94544d202c4a - noble - 2021-01-25 19:07:47] |  
  | 1> 	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) [lucene-test-framework-8.8.0.jar:8.8.0 b10659f0fc18b58b90929cfdadde94544d202c4a - noble - 2021-01-25 19:07:47] |  
  | 1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) [lucene-test-framework-8.8.0.jar:8.8.0 b10659f0fc18b58b90929cfdadde94544d202c4a - noble - 2021-01-25 19:07:47] |  
  | 1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41) [lucene-test-framework-8.8.0.jar:8.8.0 b10659f0fc18b58b90929cfdadde94544d202c4a - noble - 2021-01-25 19:07:47] |  
  | 1> 	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53) [lucene-test-framework-8.8.0.jar:8.8.0 b10659f0fc18b58b90929cfdadde94544d202c4a - noble - 2021-01-25 19:07:47] |  
  | 1> 	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) [lucene-test-framework-8.8.0.jar:8.8.0 b10659f0fc18b58b90929cfdadde94544d202c4a - noble - 2021-01-25 19:07:47] |  
  | 1> 	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) [lucene-test-framework-8.8.0.jar:8.8.0 b10659f0fc18b58b90929cfdadde94544d202c4a - noble - 2021-01-25 19:07:47] |  
  | 1> 	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54) [lucene-test-framework-8.8.0.jar:8.8.0 b10659f0fc18b58b90929cfdadde94544d202c4a - noble - 2021-01-25 19:07:47] |  
  | 1> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368) [randomizedtesting-runner-2.7.1.jar:?] |  
  | 1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281] |  
  | 1> Caused by: java.lang.NullPointerException |  
  | 1> 	at jdk.internal.platform.cgroupv1.Metrics.getMemoryAndSwapLimit(Metrics.java:489) ~[?:?] |  
  | 1> 	at sun.management.OperatingSystemImpl.getTotalSwapSpaceSize(OperatingSystemImpl.java:55) ~[?:?] |  
  | 1> 	... 53 more
```

**Comment by rjernst** [comment]
I don't think the above is the same failure we've seen before. It looks like possibly https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8257746

**Comment by tlrx** [comment]
@rjernst In case this can be helpful, the exception you mentionned happened today in https://gradle-enterprise.elastic.co/s/c6bunui7pya6s on 6.8 with Oracle Java(TM) SE Runtime Environment 11.0.11+9-LTS-194:
```

> [2021-06-01T13:42:55,198][WARN ][o.e.m.o.OsProbe          ] [testIgnoreIdleThreads] exception retrieving free swap space size
  1> java.lang.reflect.InvocationTargetException: null
  1> 	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
  1> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
  1> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_291]
  1> 	at org.elasticsearch.monitor.os.OsProbe.getFreeSwapSpaceSize(OsProbe.java:135) ~[main/:?]
  1> 	at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:649) ~[main/:?]
  1> 	at org.elasticsearch.monitor.os.OsService.<init>(OsService.java:49) ~[main/:?]
  1> 	at org.elasticsearch.monitor.MonitorService.<init>(MonitorService.java:46) ~[main/:?]
  1> 	at org.elasticsearch.node.Node.<init>(Node.java:399) ~[main/:?]
  1> 	at org.elasticsearch.node.MockNode.<init>(MockNode.java:105) ~[framework-6.8.17-SNAPSHOT.jar:?]
  1> 	at org.elasticsearch.node.MockNode.<init>(MockNode.java:91) ~[framework-6.8.17-SNAPSHOT.jar:?]
  1> 	at org.elasticsearch.test.InternalTestCluster.buildNode(InternalTestCluster.java:669) ~[framework-6.8.17-SNAPSHOT.jar:6.8.17-SNAPSHOT]

...  

  1> Caused by: java.lang.NullPointerException
  1> 	at jdk.internal.platform.cgroupv1.Metrics.getMemoryAndSwapLimit(Metrics.java:492) ~[?:?]
  1> 	at sun.management.OperatingSystemImpl.getFreeSwapSpaceSize(OperatingSystemImpl.java:70) ~[?:?]
  1> 	... 53 more
```

Looking at the failures of `HotThreadsIT` in the last 60 days revealed 5 failures (branches 6.8, 7.12, 7.13) all with the same `NullPointerException`, always on `debian-8` and `Linux 3.16.0-11-amd64`.

JVM runtimes:
- Oracle OpenJDK Runtime Environment 15.0.2+7-27
- Oracle OpenJDK Runtime Environment 11.0.2+7
- Oracle Java(TM) SE Runtime Environment 11.0.11+9-LTS-194.

I'm linking the build scans just in case:
https://gradle-enterprise.elastic.co/s/idmnonuqte7z4
https://gradle-enterprise.elastic.co/s/n3y3mfrudrxa2
https://gradle-enterprise.elastic.co/s/usl6gqrwkyvqy
https://gradle-enterprise.elastic.co/s/p25eu7jouljts
https://gradle-enterprise.elastic.co/s/c6bunui7pya6s

**Comment by grcevski** [comment]
I looked this particular failure and I believe the error can happen in the event where a thread execution migrates a CPU while running the test. This would be a rare event on the platform where this test was run (CPU affinity is typically respected by the OS scheduler), however it's definitely something that would happen.

The IllegalArgumentException that's thrown comes from constructing a TimeValue with a duration less than -1, in this case -5160. The only place in `HotThreads.java` where we create a TimeValue object with a variable duration, is while constructing the output for CPU % per thread, i.e:

```
            sb.append(String.format(Locale.ROOT, "%n%4.1f%% (%s out of %s) %s usage by thread '%s'%n",
                percent, TimeValue.timeValueNanos(time), interval, type, threadName));
```

The `time` variable is calculated by taking a delta from the two CPU times, before and after the HotThreads sampling thread slept for 500ms. The way the JVM implements the API `ThreadMXBean.getThreadCpuTime` on Linux is by using `clock_gettime` with the `CLOCK_THREAD_CPUTIME_ID` parameter. This Linux API is implemented on x86-64 (or x86 in general) is via reading the internal CPU TSC registers. If a thread migrates a CPU during the 500ms sampler thread sleep, the calculated delta would be always bogus, and in case where most of the thread execution happened on the earlier CPU, the delta value calculated would be negative.

This issue with `clock_gettime` is documented here: https://linux.die.net/man/3/clock_gettime. Specifically the `NOTE for SMP systems` section.

The test failure because of this implementation limitation will be resolved when PR https://github.com/elastic/elasticsearch/pull/77392 is merged. It's not possible to calculate an accurate thread CPU time when a thread migrates a CPU, or in the event when a thread ID is reused on thread death (e.g. typical on Windows). Therefore, the PR mention above always caps the minimum delta to 0, effectively discarding the HotThreads result for this thread in the rare event of thread CPU migration or thread ID reuse.
