### ISSUE TITLE
[CI] KeyStoreWrapperTests fails on 6.8 with zulu8 and adoptopenjdk8

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#72387]
**Build scan**:
zulu8: https://gradle-enterprise.elastic.co/s/gbxomp66nkfgq
adoptopenjdk8:  https://gradle-enterprise.elastic.co/s/hixg5shxf5ehw

**Repro line**:

```
./gradlew ':server:unitTest' \
  -Dtests.seed=AD757CB6ECE0EEDF \
  -Dtests.class=org.elasticsearch.common.settings.KeyStoreWrapperTests \
  -Dtests.method="testBackcompatV2" \
  -Dtests.security.manager=true \
  -Dtests.locale=ru \
  -Dtests.timezone=Europe/Berlin \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

**Reproduces locally?**:

I tried running this test locally with AdoptOpenJDK 1.8.0_292 as "Runtime JDK Version" but could not reproduce.

**Applicable branches**:

6.8

**Failure history**:

Sudden increase starting on April 23rd, approx 

**Failure excerpt**:

```
java.security.KeyStoreException: Key protection  algorithm not found: java.security.NoSuchAlgorithmException: unrecognized algorithm name: PBEWithMD5AndDES
	at __randomizedtesting.SeedInfo.seed([BD1A136910B56F09:314EFEE1FED37C83]:0)
	at sun.security.pkcs12.PKCS12KeyStore.setKeyEntry(PKCS12KeyStore.java:694)
	at sun.security.pkcs12.PKCS12KeyStore.engineSetEntry(PKCS12KeyStore.java:1413)
	at java.security.KeyStore.setEntry(KeyStore.java:1557)
	at org.elasticsearch.common.settings.KeyStoreWrapperTests.testBackcompatV1(KeyStoreWrapperTests.java:322)
```

**Comment by jkakavas** [comment]
Closing this as a duplicate of https://github.com/elastic/elasticsearch/issues/72466
