### ISSUE TITLE
Tests failing due to very slow cluster state updates

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#72404]
**Build scan**:

https://gradle-enterprise.elastic.co/s/m2kldzfhmictm
https://gradle-enterprise.elastic.co/s/o4qzst6pglg36

**Repro line**: `REPRODUCE WITH: ./gradlew ':x-pack:plugin:snapshot-repo-test-kit:qa:azure:integTest' --tests "org.elasticsearch.repositories.blobstore.testkit.AzureSnapshotRepoTestKitIT.testRepositoryAnalysis" -Dtests.seed=C8C21C7C13ECEF87 -Dtests.locale=pt-BR -Dtests.timezone=Asia/Ho_Chi_Minh -Druntime.java=15`

**Reproduces locally?**: No

**Applicable branches**: 7.x, master

**Failure history**:

Not sure how best to characterise these failures, sorry.

**Failure excerpt**:

The two build scans above indicate failures due to processing cluster state updates very very slowly:

```
org.elasticsearch.client.ResponseException: method [PUT], host [http://127.0.0.1:44503], URI [_snapshot/repository?verify=true], status line [HTTP/1.1 503 Service Unavailable] |  
-- | --
  | {"error":{"root_cause":[{"type":"process_cluster_event_timeout_exception","reason":"failed to process cluster event (put_repository [repository]) within 30s"}],"type":"process_cluster_event_timeout_exception","reason":"failed to process cluster event (put_repository [repository]) within 30s"},"status":503} |  
  | at __randomizedtesting.SeedInfo.seed([C8C21C7C13ECEF87:31FFBD12CD77DC6E]:0) |  
  | at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
```

The slowness is not directly related to the test itself, instead we see that cluster state updates were taking 3+ seconds each even before the test started:

```
[2021-04-26T06:13:23,614][INFO ][o.e.n.Node               ] [integTest-0] started
[2021-04-26T06:13:23,756][INFO ][o.e.c.s.MasterService    ] [integTest-0] elected-as-master ([1] nodes joined)[{integTest-0}{cVjFb4J7QxCd567sAErqRQ}{LndVCvfnTaOZMeSZGmozzQ}{127.0.0.1}{127.0.0.1:37333}{cdfhilmrstw} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 1, version: 1, delta: master node
 changed {previous [], current [{integTest-0}{cVjFb4J7QxCd567sAErqRQ}{LndVCvfnTaOZMeSZGmozzQ}{127.0.0.1}{127.0.0.1:37333}{cdfhilmrstw}]}
[2021-04-26T06:13:23,810][INFO ][o.e.c.c.CoordinationState] [integTest-0] cluster UUID set to [uETKElK5Q8Od6WM8cKDEdg]
[2021-04-26T06:13:26,258][INFO ][o.e.c.s.ClusterApplierService] [integTest-0] master node changed {previous [], current [{integTest-0}{cVjFb4J7QxCd567sAErqRQ}{LndVCvfnTaOZMeSZGmozzQ}{127.0.0.1}{127.0.0.1:37333}{cdfhilmrstw}]}, term: 1, version: 1, reason: Publication{term=1, version=1}
[2021-04-26T06:13:27,905][INFO ][o.e.g.GatewayService     ] [integTest-0] recovered [0] indices into cluster_state
[2021-04-26T06:13:28,244][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding template [.ml-anomalies-] for index patterns [.ml-anomalies-*]
[2021-04-26T06:13:31,079][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding template [.ml-notifications-000001] for index patterns [.ml-notifications-000001]
[2021-04-26T06:13:34,819][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding template [.ml-state] for index patterns [.ml-state*]
[2021-04-26T06:13:38,311][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding template [.ml-stats] for index patterns [.ml-stats-*]
[2021-04-26T06:13:41,703][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding component template [logs-settings]
[2021-04-26T06:13:45,009][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding component template [synthetics-mappings]
[2021-04-26T06:13:48,208][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding component template [logs-mappings]
[2021-04-26T06:13:49,871][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding component template [metrics-mappings]
[2021-04-26T06:13:51,669][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding component template [metrics-settings]
[2021-04-26T06:13:55,051][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding component template [synthetics-settings]
[2021-04-26T06:13:57,883][ERROR][o.e.x.m.e.l.LocalExporter] [integTest-0] failed to set monitoring template [.monitoring-alerts-7]
org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (create-index-template [.monitoring-alerts-7], cause [api]) within 30s
        at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$0(MasterService.java:132) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
        at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$1(MasterService.java:131) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:669) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

We (the @elastic/es-distributed team) discussed this today and suspect we might just be overloading the CI worker. We're running tasks 8 wide in these builds, at least two of which are running full Elasticsearch nodes. Do we collect any telemetry to support/reject that idea? Is there anything we can do in the build to give these jobs more space to do their thing?

**Comment by mark-vieira** [comment]
> Is there anything we can do in the build to give these jobs more space to do their thing?

What do we mean by "space" here? These are ARM workers, but they are provisioned the same as x86 machines and parallelism tuned the same way.

**Comment by DaveCTurner** [comment]
I'm being deliberately vague here: the log messages tell us that things were running very slowly at this point in the build, causing the test failure, but don't give us much insight into why. For comparison, these are the kinds of timings we see in a healthy test run, typically 100ms or less per update:

```
 [2021-04-26T11:19:20,955][INFO ][o.e.g.GatewayService     ] [integTest-0] recovered [0] indices into cluster_state
[2021-04-26T11:19:21,126][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding template [.ml-stats] for index patterns [.ml-stats-*]
[2021-04-26T11:19:21,200][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding template [.ml-notifications-000001] for index patterns [.ml-notifications-000001]
[2021-04-26T11:19:21,328][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding template [.ml-state] for index patterns [.ml-state*]
[2021-04-26T11:19:21,416][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding template [.ml-anomalies-] for index patterns [.ml-anomalies-*]
[2021-04-26T11:19:21,473][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding component template [logs-mappings]
[2021-04-26T11:19:21,527][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding component template [metrics-settings]
[2021-04-26T11:19:21,576][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding component template [synthetics-settings]
[2021-04-26T11:19:21,634][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding component template [synthetics-mappings]
[2021-04-26T11:19:21,768][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding component template [logs-settings]
[2021-04-26T11:19:21,812][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding component template [metrics-mappings]
[2021-04-26T11:19:21,900][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding index template [.watch-history-13] for index patterns [.watcher-history-13*]
[2021-04-26T11:19:21,951][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding index template [.slm-history] for index patterns [.slm-history-5*]
[2021-04-26T11:19:21,998][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding component template [.deprecation-indexing-settings]
[2021-04-26T11:19:22,042][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding component template [.deprecation-indexing-mappings]
[2021-04-26T11:19:22,093][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding template [.monitoring-alerts-7] for index patterns [.monitoring-alerts-7]
[2021-04-26T11:19:22,156][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding template [.monitoring-es] for index patterns [.monitoring-es-7-*]
[2021-04-26T11:19:22,207][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding template [.monitoring-kibana] for index patterns [.monitoring-kibana-7-*]
[2021-04-26T11:19:22,262][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding template [.monitoring-logstash] for index patterns [.monitoring-logstash-7-*]
[2021-04-26T11:19:22,319][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding template [.monitoring-beats] for index patterns [.monitoring-beats-7-*]
[2021-04-26T11:19:22,369][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding index template [synthetics] for index patterns [synthetics-*-*]
[2021-04-26T11:19:22,418][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding index template [logs] for index patterns [logs-*-*]
[2021-04-26T11:19:22,467][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding index template [metrics] for index patterns [metrics-*-*]
[2021-04-26T11:19:22,521][INFO ][o.e.c.m.MetadataIndexTemplateService] [integTest-0] adding index template [.deprecation-indexing-template] for index patterns [.logs-deprecation.*]
```

**Comment by mark-vieira** [comment]
Right, I guess my question then becomes do we think we should reduce parallelism on these ARM builds? From my understanding, we should expect comparable performance on ARM. If we're running into issues in test execution should we be concerned or perhaps investigate further?

**Comment by mark-vieira** [comment]
> For comparison, these are the kinds of timings we see in a healthy test run, typically 100ms or less per update:

Also, what build exactly did you get these timings from? Not all builds are created equal. Our platform compatibility builds for example explicitly **do not** leverage a ramdisk for the build workspace so they'll be slower compared to other builds like our JDK matrix or intake/PR checks.

**Comment by mark-vieira** [comment]
Besides the obvious CPU architecture difference which I suspect _shouldn't_ be in play here. These Gravaton2 instances though are AWS, vs all the other stuff being GCP. Comparing storage isn't exactly apples to apples either. GCP we're using the pd-ssd storage class where as AWS (Arm) we are using gp3 (both 350GB disks). Perhaps @elastic/es-perf has some insight here form the testing they did on Arm?

**Comment by fcofdez** [comment]
I've observed similar performance characteristics in https://github.com/elastic/elasticsearch/issues/72235#issuecomment-831352397 where the cluster state takes quite a bit to be written to disk in the ARM workers. Maybe we're hitting some throttling on the EBS side?

**Comment by mark-vieira** [comment]
After cutting the number of workers in half still seeing failures relating to timeouts.

https://gradle-enterprise.elastic.co/s/yqgunepcgokxk

I doubt it's an issue with EBS at this point. It seems more likely something is up with the Ubuntu images since they seem _much_ more susceptible to this problem and suffer other timeout-related problems.

**Comment by mark-vieira** [comment]
Ok, now the last two CentOS jobs have failed with timeouts related to docker. Normally we don't use ramdisks for "platform" tests but I think in this case perhaps we should since what we're really testing is the system _architecture_ not anything file system related.

Any objections to running the Arm builds with an in-memory workspace?

**Comment by mark-vieira** [comment]
I've updated these jobs to run in a ramdisk. This seems to have sorted things out on the master builds so I've backported that change to 7.x and 7.13 as well.
