### ISSUE TITLE
[CI] RegressionIT testStopAndRestart failing

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#72463]
Started falling again today. There are a couple of clues in the node logs:
```
» [2021-04-29T07:55:10,039][WARN ][o.e.c.c.ClusterFormationFailureHelper] [javaRestTest-0] master not discovered or elected yet, an election requires at least 2 nodes with ids from [dspKaA99SGCsGD7FXLL8rQ, 6-67dwXAR0OyPN-Zfv55pA, 9ZHG0TH7R7mKhn99pWfmcQ], have discovered [{javaRestTest-0}{6-67dwXAR0OyPN-Zfv55pA}{0kJ_7EpoQk2d6yAHeBWFmQ}{127.0.0.1}{127.0.0.1:34271}{dim}, {javaRestTest-1}{9ZHG0TH7R7mKhn99pWfmcQ}{1wznyornT5GlXokfVC0qAQ}{127.0.0.1}{127.0.0.1:37337}{dilm}, {javaRestTest-2}{dspKaA99SGCsGD7FXLL8rQ}{3eYwNezSRAG1xfp6Sjk_bg}{127.0.0.1}{127.0.0.1:33681}{dilm}] which is a quorum; discovery will continue using [[::1]:42655, 127.0.0.1:37337, [::1]:42331, 127.0.0.1:33681] from hosts providers and [{javaRestTest-0}{6-67dwXAR0OyPN-Zfv55pA}{0kJ_7EpoQk2d6yAHeBWFmQ}{127.0.0.1}{127.0.0.1:34271}{dim}] from last-known cluster state; node term 0, last-accepted version 0 in term 0
» [2021-04-29T07:55:24,946][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [javaRestTest-0] uncaught exception in thread [elasticsearch[javaRestTest-0][generic][T#4]]
»  java.lang.IllegalArgumentException: Malformed [mappings] section for type [dynamic], should include an inner object describing the mapping
»  	at org.elasticsearch.action.admin.indices.template.put.PutIndexTemplateRequest.source(PutIndexTemplateRequest.java:331) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.action.admin.indices.template.put.PutIndexTemplateRequest.source(PutIndexTemplateRequest.java:370) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
»  	at org.elasticsearch.cluster.metadata.TemplateUpgradeService.upgradeTemplates(TemplateUpgradeService.java:136) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
```
and
```
» [2021-04-29T07:59:23,120][WARN ][o.e.x.m.d.DatafeedManager] [javaRestTest-2] [test-lookback-only-given-empty-index] Datafeed lookback retrieved no data
» [2021-04-29T07:59:35,732][WARN ][o.e.x.m.j.p.a.o.AutodetectResultProcessor] [javaRestTest-2] [job-realtime-2] some results not processed due to the process being killed
» [2021-04-29T07:59:56,749][ERROR][o.e.x.m.d.DatafeedJob    ] [javaRestTest-2] [permission-test-network-job] error while extracting data
»  org.elasticsearch.ElasticsearchSecurityException: action [indices:data/read/search] is unauthorized for user [ml_admin_plus_data] with roles [machine_learning_admin,test_data_access] on indices [network-data], this action is granted by the index privileges [read,all]
»  	at org.elasticsearch.xpack.core.security.support.Exceptions.authorizationError(Exceptions.java:35) ~[?:?]
»  	at org.elasticsearch.xpack.security.authz.AuthorizationService.denialException(AuthorizationService.java:659) ~[?:?]
»  	at org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.handleFailure(AuthorizationService.java:707) ~[?:?]
»  	at org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:692) ~[?:?]
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/cbqf4hqqqznua/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.RegressionIT/testStopAndRestart

**Reproduction line:**
`./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testStopAndRestart" -Dtests.seed=A2B59BBAB87B14CA -Dtests.locale=vi -Dtests.timezone=Australia/Queensland -Druntime.java=11 -Dtests.fips.enabled=true`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.RegressionIT&tests.test=testStopAndRestart

**Failure excerpt:**
```
java.lang.AssertionError: Stats were: {"id":"regression_stop_and_restart","state":"started","progress":[{"phase":"reindexing","progress_percent":100},{"phase":"loading_data","progress_percent":100},{"phase":"feature_selection","progress_percent":0},{"phase":"coarse_parameter_search","progress_percent":0},{"phase":"fine_tuning_parameters","progress_percent":0},{"phase":"final_training","progress_percent":0},{"phase":"writing_results","progress_percent":0},{"phase":"inference","progress_percent":0}],"data_counts":{"training_docs_count":350,"test_docs_count":0,"skipped_docs_count":0},"memory_usage":{"timestamp":1619676350640,"peak_usage_bytes":58214,"status":"ok"},"analysis_stats":{"regression_stats":{"timestamp":1619676350640,"iteration":7,"hyperparameters":{"alpha":60329.04936907058,"downsample_factor":0.9145559910759071,"eta":0.2790301501531671,"eta_growth_rate_per_tree":1.0828726825486736,"feature_bag_fraction":0.18750000000000006,"gamma":81820.99117237015,"lambda":15.824902969174392,"max_attempts_to_add_tree":3,"max_optimization_rounds_per_hyperparameter":2,"max_trees":75,"num_folds":5,"num_splits_per_feature":75,"soft_tree_depth_limit":10.228353513327463,"soft_tree_depth_tolerance":0.22500000000000003},"timing_stats":{"elapsed_time":84,"iteration_time":4},"validation_loss":{"loss_type":"mse"}}},"node":{"id":"pcbcKo7pRaCGc3eiZNiEYw","name":"javaRestTest-2","ephemeral_id":"07tWHh19S2KoSDVJyjplGQ","transport_address":"127.0.0.1:37503","attributes":{"testattr":"test","ml.machine_memory":"101375283200","ml.max_open_jobs":"20","xpack.installed":"true","ml.max_jvm_size":"518979584"}},"assignment_explanation":""}
Expected: <stopped>
     but: was <started>

  at __randomizedtesting.SeedInfo.seed([A2B59BBAB87B14CA:D5FD1944AC91126A]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:178)
  at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.lambda$waitUntilAnalyticsIsStopped$0(MlNativeDataFrameAnalyticsIntegTestCase.java:114)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:958)
  at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.waitUntilAnalyticsIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:114)
  at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.waitUntilAnalyticsIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:110)
  at org.elasticsearch.xpack.ml.integration.RegressionIT.testStopAndRestart(RegressionIT.java:331)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by dimitris-athanasiou** [comment]
This failed before I merged in 3da72d46f4dcaa3e25d23954f81985eec442b5d6 which should fix this problem. I'll close the issue and wait and see if it fails again.
