### ISSUE TITLE
[CI] ReloadAnalyzerTests testSynonymsInMultiplexerUpdateable failing

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#72635]
Reproduce with:
```
./gradlew ':x-pack:plugin:core:test' --tests "org.elasticsearch.xpack.core.action.ReloadAnalyzerTests.testSynonymsInMultiplexerUpdateable" -Dtests.seed=5483772DF71D429B -Dtests.locale=en-US -Dtests.timezone=America/Rankin_Inlet -Druntime.java=17
```

Trace:
```
org.elasticsearch.xpack.core.action.ReloadAnalyzerTests > testSynonymsInMultiplexerUpdateable FAILED
    [test/W1fqqDz3TXCZlE88MXlSbw] org.elasticsearch.ResourceAlreadyExistsException: index [test/W1fqqDz3TXCZlE88MXlSbw] already exists
        at __randomizedtesting.SeedInfo.seed([5483772DF71D429B:91955307A908C812]:0)
        at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validateIndexName(MetadataCreateIndexService.java:178)
        at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validate(MetadataCreateIndexService.java:1011)
        at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:325)
        at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:376)
        at org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:293)
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:48)
        at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:686)
        at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:308)
        at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:203)
        at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:140)
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:139)
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:177)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:669)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:241)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:204)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/n6vngnqhd6lzy/tests/:x-pack:plugin:core:test/org.elasticsearch.xpack.core.action.ReloadAnalyzerTests/testSynonymsInMultiplexerUpdateable

**Reproduction line:**
`./gradlew ':x-pack:plugin:core:test' --tests "org.elasticsearch.xpack.core.action.ReloadAnalyzerTests.testSynonymsInMultiplexerUpdateable" -Dtests.seed=5483772DF71D429B -Dtests.locale=en-US -Dtests.timezone=America/Rankin_Inlet -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.core.action.ReloadAnalyzerTests&tests.test=testSynonymsInMultiplexerUpdateable

**Failure excerpt:**
```
org.elasticsearch.ResourceAlreadyExistsException: index [test/W1fqqDz3TXCZlE88MXlSbw] already exists

  at __randomizedtesting.SeedInfo.seed([5483772DF71D429B:91955307A908C812]:0)
  at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validateIndexName(MetadataCreateIndexService.java:178)
  at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validate(MetadataCreateIndexService.java:1011)
  at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:325)
  at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:376)
  at org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:293)
  at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:48)
  at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:686)
  at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:308)
  at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:203)
  at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:140)
  at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:139)
  at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:177)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:669)
  at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:241)
  at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:204)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.lang.Thread.run(Thread.java:831)

```

**Comment by cbuescher** [comment]
The immediate reason for the failure here is not inherent in the test but because the "test" index cannot be created because it already exists. In theory all indices should be deleted during `tearDown()` in ESSingleNodeTestCase, which we also ack and assert in the method. It is unclear to me why this doesn't happen (or happens too late for the subsequent index creation to notice it). There are some master node change messages in the logs around the time of the failure but I don't see how they would explain the existence of the index. 

```
1> [2021-05-03T11:22:17,509][INFO ][o.e.x.c.a.ReloadAnalyzerTests] [testSynonymsInMultiplexerUpdateable] before test
  1> [2021-05-03T11:22:17,520][DEPRECATION][o.e.d.c.m.MetadataCreateIndexService] [node_s_0] data_stream.dataset="deprecation.elasticsearch" data_stream.namespace="default" data_stream.type="logs" ecs.version="1.7" elasticsearch.event.category="templates" event.code="index_template_multiple_match" message="index [test] matches multiple legacy templates [one_shard_index_template, random-soft-deletes-template], composable templates will only match a single template"
  1> [2021-05-03T11:22:17,547][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s_0] [test] creating index, cause [api], templates [one_shard_index_template, random-soft-deletes-template], shards [5]/[0]
  1> [2021-05-03T11:23:57,585][WARN ][o.e.t.ThreadPool         ] [node_s_0] timer thread slept for [5.4s/5496ms] on absolute clock which is above the warn threshold of [5000ms]
  1> [2021-05-03T11:23:57,590][WARN ][o.e.t.ThreadPool         ] [node_s_0] timer thread slept for [5.3s/5349953819ns] on relative clock which is above the warn threshold of [5000ms]
  1> [2021-05-03T11:23:57,646][INFO ][o.e.c.s.ClusterApplierService] [node_s_0] master node changed {previous [{node_s_0}{lw_JcgfjSkGqxToZE5dRTQ}{D7EzTZ3NSleBEJA2oDvZKA}{127.0.0.1}{127.0.0.1:34201}{cdfhilmrstw}], current []}, term: 1, version: 17, reason: becoming candidate: Publication.onCompletion(false)
  1> [2021-05-03T11:23:57,725][WARN ][o.e.c.s.MasterService    ] [node_s_0] failing [create-index [test], cause [api]]: failed to commit cluster state version [18]
  1> org.elasticsearch.cluster.coordination.FailedToCommitClusterStateException: publication failed
  1> 	at org.elasticsearch.cluster.coordination.Coordinator$CoordinatorPublication$4.onFailure(Coordinator.java:1421) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListenerDirectly(ListenableFuture.java:115) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.ListenableFuture.addListener(ListenableFuture.java:55) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.cluster.coordination.Coordinator$CoordinatorPublication.onCompletion(Coordinator.java:1344) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.cluster.coordination.Publication.onPossibleCompletion(Publication.java:114) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.cluster.coordination.Publication.cancel(Publication.java:78) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.cluster.coordination.Coordinator$CoordinatorPublication$2.run(Coordinator.java:1297) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:669) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
  1> 	at java.lang.Thread.run(Thread.java:831) [?:?]
  1> Caused by: org.elasticsearch.ElasticsearchException: publication cancelled before committing: timed out after 30s
  1> 	at org.elasticsearch.cluster.coordination.Publication.cancel(Publication.java:75) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
  1> 	... 5 more
  1> [2021-05-03T11:23:57,730][INFO ][o.e.c.s.MasterService    ] [node_s_0] elected-as-master ([1] nodes joined)[{node_s_0}{lw_JcgfjSkGqxToZE5dRTQ}{D7EzTZ3NSleBEJA2oDvZKA}{127.0.0.1}{127.0.0.1:34201}{cdfhilmrstw} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 2, version: 19, delta: master node changed {previous [], current [{node_s_0}{lw_JcgfjSkGqxToZE5dRTQ}{D7EzTZ3NSleBEJA2oDvZKA}{127.0.0.1}{127.0.0.1:34201}{cdfhilmrstw}]}
  1> [2021-05-03T11:23:57,792][WARN ][o.e.t.ThreadPool         ] [node_s_0] timer thread slept for [1.5m/90094ms] on absolute clock which is above the warn threshold of [5000ms]
  1> [2021-05-03T11:23:57,792][WARN ][o.e.t.ThreadPool         ] [node_s_0] timer thread slept for [1.5m/90405478517ns] on relative clock which is above the warn threshold of [5000ms]
  1> [2021-05-03T11:23:57,979][INFO ][o.e.c.s.ClusterApplierService] [node_s_0] master node changed {previous [], current [{node_s_0}{lw_JcgfjSkGqxToZE5dRTQ}{D7EzTZ3NSleBEJA2oDvZKA}{127.0.0.1}{127.0.0.1:34201}{cdfhilmrstw}]}, term: 2, version: 19, reason: Publication{term=2, version=19}
  1> [2021-05-03T11:23:58,009][INFO ][o.e.x.c.a.ReloadAnalyzerTests] [testSynonymsInMultiplexerUpdateable] after test
  1> [2021-05-03T11:23:58,625][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_s_0] [test/W1fqqDz3TXCZlE88MXlSbw] deleting index
```

Since this is a one-off failure so far I'll leave this open for a while for observation and to track if there is an increase of this kind of failure over time.

**Comment by cbuescher** [comment]
I could not find any other specific failure in `ReloadAnalyzerTests` in the last three weeks, I would like to close this as a one-off timing issue in the test infra. If this gets more frequent or happens again please reopen.
