### ISSUE TITLE
Support index sorting for unsigned_long/half_float/scaled_float

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#72741]
[Index sort](https://www.elastic.co/guide/en/elasticsearch/reference/master/index-modules-index-sorting.html#index-modules-index-sorting) claims to support numeric fields, however, when trying to apply index sort to `unsigned_long`, but also `half_` and `scaled_` `float`, the API returns an IAE.

Repro:
```
PUT index
{
  "settings": {
    "index": {
      "number_of_shards": 5,
      "sort.field": [
        "timestamp",
        "metric"
      ],
      "sort.order": [
        "desc",
        "desc"
      ],
      "sort.missing": [
        "_first",
        "_last"
      ]
    }
  },
  "mappings": {
    "properties": {
      "timestamp": {
        "type": "date"
      },
      "metric": {
        "type": "unsigned_long"
      }
    }
  }
}
```

returns

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "invalid index sort field:[metric]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "invalid index sort field:[metric]"
  },
  "status" : 400
}
```

Note: This might be by design, however
 - the returned error lacks a proper message
 - documentation should exclude the mentioned data types

It would be good to fix ^ as short term solution.

**Comment by martijnvg** [comment]
Note that this is still an issue for `half_float` and `scaled_float`. The problem was only fixed for `unsigned_long` by #75599.

Stacktrace:

```
[2024-06-21T11:36:44,223][INFO ][o.e.c.m.MetadataCreateIndexService] [runTask-0] failed on parsing mappings on index creation [index1] java.lang.IllegalArgumentException: invalid index sort field:[metric]
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.index.IndexSortConfig.validateIndexSortField(IndexSortConfig.java:282)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.index.IndexSortConfig.buildIndexSort(IndexSortConfig.java:274)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.index.IndexService.lambda$new$2(IndexService.java:235)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.updateIndexMappingsAndBuildSortOrder(MetadataCreateIndexService.java:1351)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.lambda$applyCreateIndexWithTemporaryService$2(MetadataCreateIndexService.java:473)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:718)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexWithTemporaryService(MetadataCreateIndexService.java:471)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequestWithV1Templates(MetadataCreateIndexService.java:594)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:421)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:300)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$UnbatchedExecutor.execute(MasterService.java:569)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:1070)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:1033)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService.executeAndPublishBatch(MasterService.java:233)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.lambda$run$2(MasterService.java:1686)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListener.run(ActionListener.java:444)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue$Processor.run(MasterService.java:1683)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$5.lambda$doRun$0(MasterService.java:1278)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.action.ActionListener.run(ActionListener.java:444)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.cluster.service.MasterService$5.doRun(MasterService.java:1257)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
        at org.elasticsearch.server@8.15.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by lkts** [comment]
Looking at the code, it seems like `half_float` should work.
