### ISSUE TITLE
Timeouts in cluster management requests 7.11.2

### ISSUE THREAD

**Issue by parapar** [elastic/elasticsearch#72853]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.11.2

**Plugins installed**: [repository-azure, custom search plugins]

**JVM version** (`java -version`): bundled openjdk15

**OS version** (`uname -a` if on a Unix-like system): Linux es-data1 5.4.0-1046-azure #48~18.04.1-Ubuntu SMP Tue Apr 13 19:41:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
We have 2 data nodes (Standard_L8s_v2) with a voting only node for breaking ties in master voting. We have a small number of indices and shards. The data nodes choose around 32GB of Heap out of 64GB system RAM. The JVM Heap pressure is low (~25%). Both nodes are in the same virtual network and region. The connection among them seems to be working ok. 

{
  "cluster_name" : "elastic7",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 3,
  "number_of_data_nodes" : 2,
  "active_primary_shards" : 36,
  "active_shards" : 72,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
 
But from time to time, we observe timeouts on cluster management requests, leading to situations where a node is removed from the cluster, or even a node seems to be a kind of freeze for search requests. Example os log entries: 

[2021-05-07T15:24:45,544][WARN ][o.e.t.InboundHandler     ] [es_data_1] handling inbound transport message [InboundMessage{Header{2659950}{7.11.2}{362663}{false}{false}{false}{false}{NO_ACTION_NAME_FOR_RESPONSES}}] took [36905ms] which is above the warn threshold of [5000ms]

We observe #65405 but this seems to be corrected on 7.11.2 and we even turned off Kibana and the symptoms persist. 

We even tried to increase the timeouts but still, we see entries like: 

[2021-05-07T15:24:28,988][WARN ][o.e.c.InternalClusterInfoService] [es_data_1] Failed to update node information for ClusterInfoUpdateJob within 15s timeout

We checked GC behaviour but the GC logs when this happens do not show any abnormal GC times. 

We enabled the slowlog for checking on queries around those moments. The queries are indeed recorded some of the times, but those queries are not "slow" at any other time. 

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Two data nodes and a voting only node with 7.11.2
 2. Shards around 25GB with 1 primary and 1 replica
 3. Run searchers and from time to time it happens 

**Provide logs (if relevant)**:

org.elasticsearch.ElasticsearchException: node [{es_data_1}{wmA9BeA8QJmJxucdEqtehw}{Tct4hctNQtirsv9FQaZ7jw}{***}{****:9300}{cdhilmrstw}{ml.machine_memory=67449720832, ml.max_open_jobs=20, xpack.installed=true, ml.max_jvm_size=33285996544, transform.node=true}] failed [10] consecutive checks	
at org.elasticsearch.cluster.coordination.LeaderChecker$CheckScheduler$1.handleException(LeaderChecker.java:275) ~[elasticsearch-7.11.2.jar:7.11.2]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1288) ~[elasticsearch-7.11.2.jar:7.11.2]
	at org.elasticsearch.transport.InboundHandler.lambda$handleException$3(InboundHandler.java:266) ~[elasticsearch-7.11.2.jar:7.11.2]
	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:213) ~[elasticsearch-7.11.2.jar:7.11.2]
	at org.elasticsearch.transport.InboundHandler.handleException(InboundHandler.java:264) ~[elasticsearch-7.11.2.jar:7.11.2]
	at org.elasticsearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:256) ~[elasticsearch-7.11.2.jar:7.11.2]
	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:120) ~[elasticsearch-7.11.2.jar:7.11.2]
	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:78) ~[elasticsearch-7.11.2.jar:7.11.2]
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:689) ~[elasticsearch-7.11.2.jar:7.11.2]
	at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:131) ~[elasticsearch-7.11.2.jar:7.11.2]
	at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:106) ~[elasticsearch-7.11.2.jar:7.11.2]
	at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:71) ~[elasticsearch-7.11.2.jar:7.11.2]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:63) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[?:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[2021-05-07T15:23:57,925][INFO ][o.e.c.s.ClusterApplierService] [es_data_0] master node changed {previous [{es_data_1}{wmA9BeA8QJmJxucdEqtehw}{Tct4hctNQtirsv9FQaZ7jw}{****}{****:9300}{cdhilmrstw}{ml.machine_memory=67449720832, ml.max_open_jobs=20, xpack.installed=true, ml.max_jvm_size=33285996544, transform.node=true}], current []}, term: 30, version: 5131, reason: becoming candidate: onLeaderFailure
[2021-05-07T15:23:57,983][INFO ][o.e.c.s.ClusterApplierService] [es_data_0] master node changed {previous [], current [{es_data_1}{wmA9BeA8QJmJxucdEqtehw}{Tct4hctNQtirsv9FQaZ7jw}{****}{****:9300}{cdhilmrstw}{ml.machine_memory=67449720832, ml.max_open_jobs=20, xpack.installed=true, ml.max_jvm_size=33285996544, transform.node=true}]}, term: 30, version: 5133, reason: ApplyCommitRequest{term=30, version=5133, sourceNode={es_data_1}{wmA9BeA8QJmJxucdEqtehw}{Tct4hctNQtirsv9FQaZ7jw}{****}{****:9300}{cdhilmrstw}{ml.machine_memory=67449720832, ml.max_open_jobs=20, xpack.installed=true, ml.max_jvm_size=33285996544, transform.node=true}}

**Comment by gwbrown** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
