### ISSUE TITLE
[CI] testThousandsAndPattern test fails on 7.x

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#72883]
**Build scan**:

https://gradle-enterprise.elastic.co/s/tlqehodl7gpgk

**Repro line**:

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.common.regex.RegexTests.testThousandsAndPattern" \
  -Dtests.seed=704ED4D78C990DFA \
  -Dtests.locale=ar-YE \
  -Dtests.timezone=Europe/Vienna \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.common.regex.RegexTests.testThousandsAndPattern" \
  -Dtests.seed=704ED4D78C990DFA \
  -Dtests.locale=ar-YE \
  -Dtests.timezone=Europe/Vienna \
  -Druntime.java=11
```

**Reproduces locally?**:

Yes:
```
org.elasticsearch.common.regex.RegexTests > testThousandsAndPattern FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([704ED4D78C990DFA:1C9B8B5E2D21CA03]:0)
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.fail(Assert.java:95)
        at org.elasticsearch.common.regex.RegexTests.testThousandsAndPattern(RegexTests.java:148)
```

**Applicable branches**:

`7.x`

**Failure history**:

This is the first failure I could find.

**Failure excerpt**:

```
14:12:27 org.elasticsearch.common.regex.RegexTests > testThousandsAndPattern FAILED
14:12:27     java.lang.AssertionError
14:12:27         at __randomizedtesting.SeedInfo.seed([704ED4D78C990DFA:1C9B8B5E2D21CA03]:0)
14:12:27         at org.junit.Assert.fail(Assert.java:86)
14:12:27         at org.junit.Assert.fail(Assert.java:95)
14:12:27         at org.elasticsearch.common.regex.RegexTests.testThousandsAndPattern(RegexTests.java:148)
```

**Comment by nik9000** [comment]
Looks like I made a silly mistake. Will see if I can fix it up.
