### ISSUE TITLE
[CI] CardinalityWithRequestBreakerIT testRequestBreaker failing

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#72923]
It reproduces if run with a few iterations

**Build scan:**
https://gradle-enterprise.elastic.co/s/obfrgujhsehd2/tests/:server:internalClusterTest/org.elasticsearch.search.aggregations.metrics.CardinalityWithRequestBreakerIT/testRequestBreaker

**Reproduction line:**
`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.search.aggregations.metrics.CardinalityWithRequestBreakerIT.testRequestBreaker" -Dtests.seed=D3BE36364C08A43A -Dtests.locale=mt-MT -Dtests.timezone=Asia/Baghdad -Druntime.java=16 -Dtests.fips.enabled=true`

**Applicable branches:**
master

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.aggregations.metrics.CardinalityWithRequestBreakerIT&tests.test=testRequestBreaker

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: an empty collection
     but: <[LEAK: resource was not cleaned up before it was garbage-collected.
Recent access records: 
#1:
	org.elasticsearch.common.bytes.ReleasableBytesReference.close(ReleasableBytesReference.java:90)
	org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:313)
	org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:217)
	org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:29)
	org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:128)
	org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:140)
	org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:409)
	org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:235)
	org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:163)
	org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:120)
	java.base/java.lang.Thread.run(Thread.java:831)
#2:
	org.elasticsearch.common.bytes.ReleasableBytesReference.close(ReleasableBytesReference.java:90)
	org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:108)
	org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:69)
	org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:311)
	org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:217)
	org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:29)
	org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:128)
	org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:140)
	org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:409)
	org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:235)
	org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:163)
	org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:120)
	java.base/java.lang.Thread.run(Thread.java:831)
#3:
	org.elasticsearch.common.bytes.ReleasableBytesReference.close(ReleasableBytesReference.java:90)
	org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:74)
	org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:116)
	org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:66)
	org.elasticsearch.transport.InboundMessage.close(InboundMessage.java:95)
	org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:130)
	org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:104)
	org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:69)
	org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:311)
	org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:217)
	org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:29)
	org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:128)
	org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:140)
	org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:409)
	org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:235)
	org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:163)
	org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:120)
	java.base/java.lang.Thread.run(Thread.java:831)
#4:
	org.elasticsearch.common.util.concurrent.AbstractRefCounted.incRef(AbstractRefCounted.java:28)
	org.elasticsearch.common.bytes.ReleasableBytesReference.retainedSlice(ReleasableBytesReference.java:84)
	org.elasticsearch.common.bytes.ReleasableBytesReference$1.readReleasableBytesReference(ReleasableBytesReference.java:135)
	org.elasticsearch.common.io.stream.FilterStreamInput.readReleasableBytesReference(FilterStreamInput.java:40)
	org.elasticsearch.common.io.stream.DelayableWriteable.delayed(DelayableWriteable.java:50)
	org.elasticsearch.search.query.QuerySearchResult.readFromWithId(QuerySearchResult.java:334)
	org.elasticsearch.search.query.QuerySearchResult.<init>(QuerySearchResult.java:75)
	org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:58)
	org.elasticsearch.action.ActionListenerResponseHandler.read(ActionListenerResponseHandler.java:25)
	org.elasticsearch.transport.TransportService$5.read(TransportService.java:634)
	org.elasticsearch.transport.TransportService$5.read(TransportService.java:614)
	org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1149)
	org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.read(TransportService.java:1136)
	org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:260)
	org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:126)
	org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:82)
	org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:678)
	org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:129)
	org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:104)
	org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:69)
	org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:311)
	org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:217)
	org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:29)
	org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:128)
	org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:140)
	org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:409)
	org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:235)
	org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:163)
	org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:120)
	java.base/java.lang.Thread.run(Thread.java:831)
#5:
	org.elasticsearch.common.util.concurrent.AbstractRefCounted.incRef(AbstractRefCounted.java:28)
	org.elasticsearch.common.bytes.ReleasableBytesReference.retain(ReleasableBytesReference.java:75)
	org.elasticsearch.transport.InboundAggregator.aggregate(InboundAggregator.java:71)
	org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:134)
	org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:104)
	org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:69)
	org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:311)
	org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:217)
	org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:29)
	org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:128)
	org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:140)
	org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:409)
	org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:235)
	org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:163)
	org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:120)
	java.base/java.lang.Thread.run(Thread.java:831)
#6:
	org.elasticsearch.common.bytes.ReleasableBytesReference.close(ReleasableBytesReference.java:90)
	org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:97)
	org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:69)
	org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:311)
	org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:217)
	org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:29)
	org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:128)
	org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:140)
	org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:409)
	org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:235)
	org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:163)
	org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:120)
	java.base/java.lang.Thread.run(Thread.java:831)
#7:
	org.elasticsearch.common.bytes.ReleasableBytesReference.close(ReleasableBytesReference.java:90)
	org.elasticsearch.transport.InboundPipeline.releasePendingBytes(InboundPipeline.java:169)
	org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:90)
	org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:69)
	org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:311)
	org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:217)
	org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:29)
	org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:128)
	org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:140)
	org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:409)
	org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:235)
	org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:163)
	org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:120)
	java.base/java.lang.Thread.run(Thread.java:831)
#8:
	org.elasticsearch.common.util.concurrent.AbstractRefCounted.incRef(AbstractRefCounted.java:28)
	org.elasticsearch.common.bytes.ReleasableBytesReference.retain(ReleasableBytesReference.java:75)
	org.elasticsearch.common.bytes.ReleasableBytesReference.retainedSlice(ReleasableBytesReference.java:81)
	org.elasticsearch.transport.InboundDecoder.internalDecode(InboundDecoder.java:86)
	org.elasticsearch.transport.InboundDecoder.decode(InboundDecoder.java:42)
	org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:88)
	org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:69)
	org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:311)
	org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:217)
	org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:29)
	org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:128)
	org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:140)
	org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:409)
	org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:235)
	org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:163)
	org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:120)
	java.base/java.lang.Thread.run(Thread.java:831)
#9:
	org.elasticsearch.common.util.concurrent.AbstractRefCounted.incRef(AbstractRefCounted.java:28)
	org.elasticsearch.common.bytes.ReleasableBytesReference.retain(ReleasableBytesReference.java:75)
	org.elasticsearch.transport.InboundPipeline.getPendingBytes(InboundPipeline.java:145)
	org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:87)
	org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:69)
	org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:311)
	org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:217)
	org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:29)
	org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:128)
	org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:140)
	org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:409)
	org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:235)
	org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:163)
	org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:120)
	java.base/java.lang.Thread.run(Thread.java:831)
#10:
	org.elasticsearch.common.util.concurrent.AbstractRefCounted.incRef(AbstractRefCounted.java:28)
	org.elasticsearch.common.bytes.ReleasableBytesReference.retainedSlice(ReleasableBytesReference.java:84)
	org.elasticsearch.transport.InboundPipeline.releasePendingBytes(InboundPipeline.java:164)
	org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:90)
	org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:69)
	org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:311)
	org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:217)
	org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:29)
	org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:128)
	org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:140)
	org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:409)
	org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:235)
	org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:163)
	org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:120)
	java.base/java.lang.Thread.run(Thread.java:831)
#11:
	org.elasticsearch.common.util.concurrent.AbstractRefCounted.incRef(AbstractRefCounted.java:28)
	org.elasticsearch.common.bytes.ReleasableBytesReference.retain(ReleasableBytesReference.java:75)
	org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:79)
	org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:69)
	org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:311)
	org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:217)
	org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:29)
	org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:128)
	org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:140)
	org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:409)
	org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:235)
	org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:163)
	org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:120)
	java.base/java.lang.Thread.run(Thread.java:831)
Created at:
	org.elasticsearch.transport.nio.MockNioTransport$MockTcpReadWriteHandler.consumeReads(MockNioTransport.java:310)
	org.elasticsearch.nio.SocketChannelContext.handleReadBytes(SocketChannelContext.java:217)
	org.elasticsearch.nio.BytesChannelContext.read(BytesChannelContext.java:29)
	org.elasticsearch.nio.EventHandler.handleRead(EventHandler.java:128)
	org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:140)
	org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:409)
	org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:235)
	org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:163)
	org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:120)
	java.base/java.lang.Thread.run(Thread.java:831)
: 3 leak records were discarded because they were duplicates]>

  at __randomizedtesting.SeedInfo.seed([D3BE36364C08A43A:6BEC0B76A3C87670]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:523)
  at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:373)
  at jdk.internal.reflect.GeneratedMethodAccessor27.invoke(null:-1)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:567)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:831)

```

**Comment by iverase** [comment]
related to https://github.com/elastic/elasticsearch/pull/67688
