### ISSUE TITLE
[CI] SimpleClusterStateIT has long GCs in 7.13 and below

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#73050]
**Build scan**: 
https://gradle-enterprise.elastic.co/s/npxmfxjlxapby/tests/failed

**Repro line**:
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.cluster.SimpleClusterStateIT.testLargeClusterStatePublishing" \
   -Dtests.seed=24365114AC556D09 -Dtests.security.manager=true -Dtests.locale=fr \
   -Dtests.timezone=America/Managua -Druntime.java=8 -Dtests.fips.enabled=true
```

**Reproduces locally?**: Yes

**Applicable branches**: 7.13 and below

**Failure history**:
First occurred January 3rd 2021, 03:02:56.
https://build-stats.elastic.co/goto/554daa67f31c18a514a0e61ce2ac2530
![image](https://user-images.githubusercontent.com/215970/118133653-13fecd00-b3cf-11eb-8f0e-f8b7ea895545.png)

**Failure excerpt**:
```
[2021-05-13T03:20:28,282][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s2] [baz] creating index, cause [auto(bulk api)], templates [random_index_template], shards [1]/[1]
[2021-05-13T03:20:28,470][INFO ][o.e.c.m.MetadataMappingService] [node_s2] [baz/54oXPOAFQwWf9Pa1pc8Mgw] create_mapping [baz]
[2021-05-13T03:20:28,557][INFO ][o.e.c.r.a.AllocationService] [node_s2] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[baz][0]]]).
[2021-05-13T03:20:33,199][INFO ][o.e.c.SimpleClusterStateIT] [testLargeClusterStatePublishing] number of fields [24603], estimated bytes [246027]
[2021-05-13T03:20:34,762][INFO ][o.e.m.j.JvmGcMonitorService] [node_s4] [gc][15] overhead, spent [270ms] collecting in the last [1s]
[2021-05-13T03:20:35,188][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s2] [test] creating index, cause [api], templates [random_index_template], shards [2]/[0]
[2021-05-13T03:20:36,408][WARN ][o.e.t.n.MockNioTransport ] [node_s0] Slow execution on network thread [643 milliseconds]
java.lang.RuntimeException: Slow exception on network thread
	at org.elasticsearch.transport.nio.MockNioTransport$TransportThreadWatchdog.maybeLogElapsedTime(MockNioTransport.java:396) ~[framework-7.12.2-SNAPSHOT.jar:7.12.2-SNAPSHOT]
	at org.elasticsearch.transport.nio.MockNioTransport$TransportThreadWatchdog.unregister(MockNioTransport.java:388) ~[framework-7.12.2-SNAPSHOT.jar:7.12.2-SNAPSHOT]
	at org.elasticsearch.transport.nio.TestEventHandler.acceptChannel(TestEventHandler.java:43) ~[framework-7.12.2-SNAPSHOT.jar:7.12.2-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:217) ~[elasticsearch-nio-7.12.2-SNAPSHOT.jar:7.12.2-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:163) ~[elasticsearch-nio-7.12.2-SNAPSHOT.jar:7.12.2-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:120) ~[elasticsearch-nio-7.12.2-SNAPSHOT.jar:7.12.2-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[2021-05-13T03:20:36,522][WARN ][o.e.m.j.JvmGcMonitorService] [node_s1] [gc][17] overhead, spent [750ms] collecting in the last [1s]
[2021-05-13T03:20:36,522][WARN ][o.e.m.j.JvmGcMonitorService] [node_s0] [gc][17] overhead, spent [750ms] collecting in the last [1s]
[2021-05-13T03:20:36,523][WARN ][o.e.m.j.JvmGcMonitorService] [node_s2] [gc][17] overhead, spent [750ms] collecting in the last [1s]
[2021-05-13T03:20:36,649][WARN ][o.e.m.j.JvmGcMonitorService] [node_s3] [gc][17] overhead, spent [802ms] collecting in the last [1s]
[2021-05-13T03:20:36,822][WARN ][o.e.m.j.JvmGcMonitorService] [node_s4] [gc][17] overhead, spent [840ms] collecting in the last [1s]
[2021-05-13T03:20:37,523][INFO ][o.e.m.j.JvmGcMonitorService] [node_s0] [gc][18] overhead, spent [256ms] collecting in the last [1s]
[2021-05-13T03:20:37,524][INFO ][o.e.m.j.JvmGcMonitorService] [node_s2] [gc][18] overhead, spent [256ms] collecting in the last [1s]
[2021-05-13T03:20:37,560][INFO ][o.e.m.j.JvmGcMonitorService] [node_s1] [gc][18] overhead, spent [291ms] collecting in the last [1s]
[2021-05-13T03:20:37,686][INFO ][o.e.m.j.JvmGcMonitorService] [node_s3] [gc][18] overhead, spent [274ms] collecting in the last [1s]
[2021-05-13T03:20:38,600][WARN ][o.e.m.j.JvmGcMonitorService] [node_s1] [gc][19] overhead, spent [925ms] collecting in the last [1s]
[2021-05-13T03:20:38,600][WARN ][o.e.m.j.JvmGcMonitorService] [node_s0] [gc][19] overhead, spent [960ms] collecting in the last [1s]
```

**Comment by iverase** [comment]
Another similar failure in https://gradle-enterprise.elastic.co/s/4ufkdqdrl2yxi/, in this case we get an OOM:

```
 Caused by:
        java.lang.OutOfMemoryError: GC overhead limit exceeded
            at __randomizedtesting.SeedInfo.seed([84C8CE67D06E251B]:0)
            at org.elasticsearch.index.mapper.TextFieldMapper$Builder.buildFieldType(TextFieldMapper.java:315)
            at org.elasticsearch.index.mapper.TextFieldMapper$Builder.build(TextFieldMapper.java:399)
            at org.elasticsearch.index.mapper.TextFieldMapper$Builder.build(TextFieldMapper.java:229)
            at org.elasticsearch.index.mapper.ObjectMapper$Builder.build(ObjectMapper.java:182)
            at org.elasticsearch.index.mapper.RootObjectMapper$Builder.build(RootObjectMapper.java:99)
            at org.elasticsearch.index.mapper.MappingParser.parse(MappingParser.java:110)
            at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:524)
            at org.elasticsearch.index.mapper.MapperService.assertSerialization(MapperService.java:490)
            at org.elasticsearch.index.mapper.MapperService$$Lambda$3226/1672721363.test(Unknown Source)
            at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
            at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
            at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
            at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
            at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
            at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
            at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
            at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
            at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
            at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
            at org.elasticsearch.index.mapper.MapperService.applyMappings(MapperService.java:381)
            at org.elasticsearch.index.mapper.MapperService.updateMapping(MapperService.java:232)
            at org.elasticsearch.index.IndexService.updateMapping(IndexService.java:655)
            at org.elasticsearch.indices.cluster.IndicesClusterStateService.createIndices(IndicesClusterStateService.java
```

It reproduces with:

```
/gradlew ':server:internalClusterTest' --tests "org.elasticsearch.cluster.SimpleClusterStateIT" -Dtests.seed=84C8CE67D06E251B -Dtests.locale=sr-Latn-BA -Dtests.timezone=Indian/Mahe -Druntime.java=8
```

One thing I notice is that changing the java version to 11, then it cannot be reproduce so my suspicion is that it might be a java bug?

**Comment by fcofdez** [comment]
It seems like in tests JVM GC is not configured, meaning that the default GC is used. In Java 8 the default GC is `-XX:+UseParallelGC` and that GC is not able to cope with the memory pressure that we're exercising in this test. With `ConcMarkSweepGC` and `G1GC` (the default since Java 9) the test works correctly. Can someone from @elastic/es-delivery take a look into this?

Additionally, in this test we're creating really large mappings that translate into large heap consumption in order to generate a relatively small ClusterState, maybe we could test the same behaviour storing just cluster metadata that doesn't get translated into more objects such as mappings?

**Comment by mark-vieira** [comment]
> It seems like in tests JVM GC is not configured, meaning that the default GC is used. In Java 8 the default GC is -XX:+UseParallelGC and that GC is not able to cope with the memory pressure that we're exercising in this test. With ConcMarkSweepGC and G1GC (the default since Java 9) the test works correctly. Can someone from @elastic/es-delivery take a look into this?

Indeed, good catch. I've opened https://github.com/elastic/elasticsearch/pull/73701 to address this bit.

> Additionally, in this test we're creating really large mappings that translate into large heap consumption in order to generate a relatively small ClusterState, maybe we could test the same behaviour storing just cluster metadata that doesn't get translated into more objects such as mappings?

Also keep in mind that our test JVMs are configured with pretty small heap sizes (512m) by default (since we run potentially a lot in parallel).

**Comment by fcofdez** [comment]
> Indeed, good catch. I've opened #73701 to address this bit.

Thanks for addressing it!

> Also keep in mind that our test JVMs are configured with pretty small heap sizes (512m) by default (since we run potentially a lot in parallel).

I'll keep an eye and see if this issue happens with the new GC settings.

**Comment by fcofdez** [comment]
This seems to be related to #73845

**Comment by valeriy42** [comment]
This failure is probably related https://gradle-enterprise.elastic.co/s/5mpvbmhmeqa3w

**Comment by mark-vieira** [comment]
> This failure is probably related https://gradle-enterprise.elastic.co/s/5mpvbmhmeqa3w

If it's a GC issue causing the slowdowns it's not because we aren't using the right settings. That bit has been fixed. Perhaps that test suite simply requires additional heap?
