### ISSUE TITLE
[CI] DockerTests test124CanRestartContainerWithStackLoggingConfig failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#73126]
**Build scan:**
https://gradle-enterprise.elastic.co/s/2h2t3ut35vnim/tests/:qa:os:destructiveDistroTest.default-docker_iron_bank/org.elasticsearch.packaging.test.DockerTests/test124CanRestartContainerWithStackLoggingConfig

**Reproduction line:**
`null`

**Applicable branches:**
7.x

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.DockerTests&tests.test=test124CanRestartContainerWithStackLoggingConfig

**Failure excerpt:**
```
java.lang.RuntimeException: Elasticsearch did not start

  at __randomizedtesting.SeedInfo.seed([800AEB3B0AD0B549:78A23A0C979C6893]:0)
  at org.elasticsearch.packaging.util.ServerUtils.waitForElasticsearch(ServerUtils.java:212)
  at org.elasticsearch.packaging.util.ServerUtils.waitForElasticsearch(ServerUtils.java:84)
  at org.elasticsearch.packaging.util.Docker.lambda$waitForElasticsearch$10(Docker.java:490)
  at org.elasticsearch.packaging.util.Docker.withLogging(Docker.java:505)
  at org.elasticsearch.packaging.util.Docker.waitForElasticsearch(Docker.java:490)
  at org.elasticsearch.packaging.test.DockerTests.test124CanRestartContainerWithStackLoggingConfig(DockerTests.java:698)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

  Caused by: java.net.SocketException: Connection reset

    at java.net.SocketInputStream.read(SocketInputStream.java:210)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
    at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
    at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
    at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
    at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
    at org.apache.http.client.fluent.Request.internalExecute(Request.java:173)
    at org.apache.http.client.fluent.Executor.execute(Executor.java:262)
    at org.elasticsearch.packaging.util.ServerUtils.execute(ServerUtils.java:132)
    at org.elasticsearch.packaging.util.ServerUtils.waitForElasticsearch(ServerUtils.java:176)
    at org.elasticsearch.packaging.util.ServerUtils.waitForElasticsearch(ServerUtils.java:84)
    at org.elasticsearch.packaging.util.Docker.lambda$waitForElasticsearch$10(Docker.java:490)
    at org.elasticsearch.packaging.util.Docker.withLogging(Docker.java:505)
    at org.elasticsearch.packaging.util.Docker.waitForElasticsearch(Docker.java:490)
    at org.elasticsearch.packaging.test.DockerTests.test124CanRestartContainerWithStackLoggingConfig(DockerTests.java:698)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
    at java.lang.Thread.run(Thread.java:748)

```

**Comment by mark-vieira** [comment]
I've muted this test on `7.x` for thow.

**Comment by pugnascotia** [comment]
Seems to be intermittent. I'll see what I can do to make it more robust.

**Comment by pugnascotia** [comment]
This test hasn't failed on `master` at all, so I've re-enabled the test on `7.x` in 9e32c036a2d and we'll see what happens.

**Comment by mark-vieira** [comment]
Looks it's failing but specifically on the ironbank image.

https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Los_Angeles&tests.container=org.elasticsearch.packaging.test.DockerTests&tests.sortField=FAILED&tests.test=test124CanRestartContainerWithStackLoggingConfig&tests.unstableOnly=true
