### ISSUE TITLE
StackOverflow Crash

### ISSUE THREAD

**Issue by vipwangtian** [elastic/elasticsearch#73133]
**Elasticsearch version** 7.10.1:

**Plugins installed**: []

**JVM version** :
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)

**OS version** :
Windows Server 2012 R2 Datacenter

**Description of the problem including expected versus actual behavior**:
The elasticsearch service crashed, the logs indicate stackoverflow

**Steps to reproduce**:

I 'm not sure, but I have already set **search.allow_expensive_queries** parameter to false, related on issues #37637 and #28344. I think nobody could use regexp query. After I set the parameter, it still occured 3 times, and this time, I set **index.max_regex_length** to 10, default 1000. I don't know whether it will work or not.

**Provide logs (if relevant)**:
```
[2021-05-17T09:15:55,263][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [SERVER2] fatal error in thread [Thread-103898], exiting
java.lang.StackOverflowError: null
	at org.apache.lucene.util.automaton.RegExp.next(RegExp.java:1119) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseCharExp(RegExp.java:1265) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseSimpleExp(RegExp.java:1260) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseCharClassExp(RegExp.java:1192) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseComplExp(RegExp.java:1180) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseRepeatExp(RegExp.java:1149) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1142) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
	at org.apache.lucene.util.automaton.RegExp.parseConcatExp(RegExp.java:1144) ~[lucene-core-8.7.0.jar:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
```

**Comment by dnhatn** [comment]
@vipwangtian Can you share the query?

**Comment by vipwangtian** [comment]
> @vipwangtian Can you share the query?

Thank you for your reply. But I can not provide the exact query which caused this, because it's our production envirament and there are many queries at that time, I don't know how to distinguish them.

**Comment by cbuescher** [comment]
@vipwangtian as you already probably guessed its likely a Regex query that is causing this, but without further information we cannot be sure. The stack trace is not sufficient to act on this issue, unfortunately.

> this time, I set index.max_regex_length to 10, default 1000. I don't know whether it will work or not.

Did the StackOverflowError after you changed that setting?

**Comment by vipwangtian** [comment]
> @vipwangtian as you already probably guessed its likely a Regex query that is causing this, but without further information we cannot be sure. The stack trace is not sufficient to act on this issue, unfortunately.
> 
> > this time, I set index.max_regex_length to 10, default 1000. I don't know whether it will work or not.
> 
> Did the StackOverflowError after you changed that setting?
didn't happen since I changed that, it seems to be usefull.

**Comment by cbuescher** [comment]
> didn't happen since I changed that, it seems to be usefull.

Thats great, unfortunately the earlier stack trace doesn't offer much for us for concrete investigations I'm closing this.
