### ISSUE TITLE
Elasticsearch not starting on RHEL7 java.lang.ClassNotFoundException: com.sun.jna.Native

### ISSUE THREAD

**Issue by truhlik** [elastic/elasticsearch#73197]
**Elasticsearch version**
```
# /usr/share/elasticsearch/bin/elasticsearch --version
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: UseAVX=2 is not supported on this CPU, setting it to UseAVX=1
Version: 6.8.11, Build: default/rpm/00bf386/2020-07-09T19:08:08.940669Z, JVM: 11.0.10
```

**Plugins installed**: []

**JVM version** (`java -version`):
```
$ java -version
openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9-LTS, mixed mode, sharing)
```

**OS version** (`uname -a` if on a Unix-like system):
```
# uname -a
Linux sgeczerczwebp10 3.10.0-1160.11.1.el7.x86_64 #1 SMP Mon Nov 30 13:05:31 EST 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:
ElasticSearch can't start. 

**Steps to reproduce**:
`service elasticsearch start`

```
# service elasticsearch status
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/etc/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2021-05-18 13:54:28 CEST; 1s ago
     Docs: http://www.elastic.co
  Process: 21748 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid --quiet (code=exited, status=1/FAILURE)
 Main PID: 21748 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/elasticsearch.service

May 18 13:54:24 sgeczerczwebp10 systemd[1]: Started Elasticsearch.
May 18 13:54:24 sgeczerczwebp10 elasticsearch[21748]: OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
May 18 13:54:24 sgeczerczwebp10 elasticsearch[21748]: OpenJDK 64-Bit Server VM warning: UseAVX=2 is not supported on this CPU, setting it to UseAVX=1
May 18 13:54:28 sgeczerczwebp10 systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
May 18 13:54:28 sgeczerczwebp10 systemd[1]: Unit elasticsearch.service entered failed state.
May 18 13:54:28 sgeczerczwebp10 systemd[1]: elasticsearch.service failed.
```

**Provide logs (if relevant)**:
```
# cat /var/log/elasticsearch/elasticsearch.log 
[2021-05-18T13:56:08,465][WARN ][o.e.b.Natives            ] [unknown] JNA not found. native methods will be disabled.
java.lang.ClassNotFoundException: com.sun.jna.Native
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:315) ~[?:?]
	at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:45) [elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:102) [elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170) [elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) [elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.8.11.jar:6.8.11]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) [elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.8.11.jar:6.8.11]
[2021-05-18T13:56:08,482][WARN ][o.e.b.Natives            ] [unknown] cannot check if running as root because JNA is not available
[2021-05-18T13:56:08,482][WARN ][o.e.b.Natives            ] [unknown] cannot install system call filter because JNA is not available
[2021-05-18T13:56:08,483][WARN ][o.e.b.Natives            ] [unknown] cannot mlockall because JNA is not available
[2021-05-18T13:56:08,483][WARN ][o.e.b.Natives            ] [unknown] cannot register console handler because JNA is not available
[2021-05-18T13:56:08,489][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [unknown] fatal error in thread [main], exiting
java.lang.NoClassDefFoundError: com/sun/jna/win32/StdCallLibrary$StdCallCallback
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:141) ~[elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170) ~[elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.8.11.jar:6.8.11]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.8.11.jar:6.8.11]
Caused by: java.lang.ClassNotFoundException: com.sun.jna.win32.StdCallLibrary$StdCallCallback
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 10 more
```

Trying to configure TMP for java
```
# cat /etc/sysconfig/elasticsearch | grep ES_
ES_TMPDIR=/var/lib/elasticsearch/tmp/
#ES_HOME=/usr/share/elasticsearch
ES_PATH_CONF=/etc/elasticsearch
ES_JAVA_OPTS="-Djna.tmpdir=/var/lib/elasticsearch/tmp/ -Djava.io.tmpdir=/var/lib/elasticsearch/tmp/"
ES_STARTUP_SLEEP_TIME=5
```
```
# cat /etc/elasticsearch/jvm.options | grep tmp
#-Djava.io.tmpdir=${ES_TMPDIR}
-Djava.io.tmpdir=/var/lib/elasticsearch/tmp
-Djna.tmpdir=/var/lib/elasticsearch/tmp
```
```
# ls -l /var/lib/elasticsearch/
celkem 0
drwxr-sr-x. 3 elasticsearch elasticsearch 14 11. kvě  2020 nodes
drwxrws---. 2 elasticsearch elasticsearch 29 18. kvě 13.56 tmp

```

**Comment by mark-vieira** [comment]
@rjernst any idea why we're seeing `win32` in the stacktrace here when loading on Linux?

**Comment by rjernst** [comment]
@truhlik Can you please provide the rest of the Elasticsearch log? It looks like you gave a snippet.

Have you modified anything in the Elasticsearch installation? Those classes should not be possible to be missing. The jna jar itself is always present in the distribution. The jna tmp dir is about extracting the platform specific bits and then being able to execute them (loading native libs), which is where the leniency comes into play. But the classes missing that log seem to indicate the jna jar is missing entirely from Elasticsearch's lib directory.

**Comment by truhlik** [comment]
This is complete log after rm elasticsearch.log and starting service (starting fails).
```
# cat elasticsearch.log 
[2021-06-03T21:21:51,988][WARN ][o.e.b.Natives            ] [unknown] JNA not found. native methods will be disabled.
java.lang.ClassNotFoundException: com.sun.jna.Native
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:315) ~[?:?]
	at org.elasticsearch.bootstrap.Natives.<clinit>(Natives.java:45) [elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:102) [elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170) [elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) [elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.8.11.jar:6.8.11]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) [elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.8.11.jar:6.8.11]
[2021-06-03T21:21:52,019][WARN ][o.e.b.Natives            ] [unknown] cannot check if running as root because JNA is not available
[2021-06-03T21:21:52,020][WARN ][o.e.b.Natives            ] [unknown] cannot install system call filter because JNA is not available
[2021-06-03T21:21:52,020][WARN ][o.e.b.Natives            ] [unknown] cannot mlockall because JNA is not available
[2021-06-03T21:21:52,020][WARN ][o.e.b.Natives            ] [unknown] cannot register console handler because JNA is not available
[2021-06-03T21:21:52,024][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [unknown] fatal error in thread [main], exiting
java.lang.NoClassDefFoundError: com/sun/jna/win32/StdCallLibrary$StdCallCallback
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:141) ~[elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170) ~[elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.8.11.jar:6.8.11]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.8.11.jar:6.8.11]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.8.11.jar:6.8.11]
Caused by: java.lang.ClassNotFoundException: com.sun.jna.win32.StdCallLibrary$StdCallCallback
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 10 more

```

I didn't modified anything about installation Elasticsearch. I did not have problem with the ES service until last week, when was made huge update of system packages. After upgrade ES stopped working.

```
# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)
```

**Comment by williamrandolph** [comment]
> I did not have problem with the ES service until last week, when was made huge update of system packages.

I was able to replicate your error by removing the JNA jar (`jna-5.5.0.jar` for Elasticsearch 6.8.12) from my installation's `lib` directory. I believe that your system package update probably removed or changed the JNA jar that Elasticsearch was relying on. As Ryan said, this jar file should always be present in an Elasticsearch installation. You may need to reinstall the jar, or reinstall Elasticsearch altogether.

Since this appears to be an issue with your system's configuration and not the original Elasticsearch installation, I'm going to close this issue. If a reinstallation seems to indicate a bug on our end, please feel free to comment here. Otherwise, you may be able to find help (and similar issues) at http://discuss.elastic.co.

**Comment by truhlik** [comment]
@williamrandolph thank you. You are right. The package was somehow corrupted (only 274B)

```
# ls -l /usr/share/elasticsearch/lib/
...
-rw-r--r--. 1 root root      274 20. dub 12.48 jna-5.5.0.jar
```

I downloaded package from https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.5.0/
and replace the original file. And elasticsearch is working correctly.
`-rw-r-----. 1 root            root         1506993 30. říj  2019 jna-5.5.0.jar`

Thank you, guys.

**Comment by mark-vieira** [comment]
FWIW, whatever caused that JAR to go missing could have caused other issues as well. I think it'd probably be worthwhile reinstalling the entire package rather than _patching_ the JNA jar back into the libs directory. You might hit other funny behavior down the road.
