### ISSUE TITLE
Reproducible Failure in CollapsingTopDocsCollectorSearchAfterTests.testCollapseDouble

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#73270]
Just ran into this locally on master and it reproduces 100% of the time:

```

> Task :server:test
OpenJDK 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release.

REPRODUCE WITH: ./gradlew ':server:test' --tests "org.apache.lucene.grouping.CollapsingTopDocsCollectorSearchAfterTests.testCollapseDouble" -Dtests.seed=57C720291214B3A3 -Dtests.locale=fr-LU -Dtests.timezone=America/Los_Angeles -Druntime.java=16

org.apache.lucene.grouping.CollapsingTopDocsCollectorSearchAfterTests > testCollapseDouble FAILED
    java.lang.AssertionError: expected:<1244> but was:<0>
        at __randomizedtesting.SeedInfo.seed([57C720291214B3A3:FFDF62F1CC5A52B3]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.apache.lucene.grouping.CollapsingTopDocsCollectorSearchAfterTests.assertSearchCollapse(CollapsingTopDocsCollectorSearchAfterTests.java:114)
        at org.apache.lucene.grouping.CollapsingTopDocsCollectorSearchAfterTests.assertSearchCollapse(CollapsingTopDocsCollectorSearchAfterTests.java:56)
        at org.apache.lucene.grouping.CollapsingTopDocsCollectorSearchAfterTests.testCollapseDouble(CollapsingTopDocsCollectorSearchAfterTests.java:230)

```

**Comment by original-brownbear** [comment]
Now it failed on CI as well https://gradle-enterprise.elastic.co/s/qqhsdfvlkavtc/tests/:server:test/org.apache.lucene.grouping.CollapsingTopDocsCollectorSearchAfterTests/testCollapseDouble?top-execution=1

**Comment by BigPandaToo** [comment]
Another failure in CI: https://gradle-enterprise.elastic.co/s/wjkkfm3dxbqrm
