### ISSUE TITLE
MatrixStats NPE when technically misused

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#73276]
**Elasticsearch version** (`bin/elasticsearch --version`):
All
**Steps to reproduce**:

 1. Two or more indices
 2. Try to execute matrix stats on two fields in the two indices (but the fields are EXCLUSIVELY in each index)
 3. Witness the NPE

**Provide logs (if relevant)**:

```
[2021-05-20T08:48:36,621][WARN ][r.suppressed             ] [runTask-0] path: /correlate_latency*/_search, params: {pretty=true, size=0, index=correlate_latency*}
org.elasticsearch.action.search.SearchPhaseExecutionException:
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:661) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.search.FetchSearchPhase$1.onFailure(FetchSearchPhase.java:89) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:28) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:728) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at org.elasticsearch.search.aggregations.matrix.stats.RunningStats.merge(RunningStats.java:235) ~[?:?]
        at org.elasticsearch.search.aggregations.matrix.stats.InternalMatrixStats.reduce(InternalMatrixStats.java:236) ~[?:?]
        at org.elasticsearch.search.aggregations.InternalAggregations.reduce(InternalAggregations.java:154) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.search.aggregations.InternalAggregations.topLevelReduce(InternalAggregations.java:103) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.search.SearchPhaseController.reduceAggs(SearchPhaseController.java:480) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:468) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.search.QueryPhaseResultConsumer.reduce(QueryPhaseResultConsumer.java:131) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:98) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:84) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
```

Reproduction Commands:
```
 PUT correlate_latency
 {
   "mappings": {
     "properties": {
       "latency": {
         "type": "double"
       }
     }
   }
 }

POST correlate_latency/_bulk?refresh=true
{"index":{}}
{"latency":"100"}
{"index":{}}
{"latency":"200"}

 PUT correlate_latency_2
 {
   "mappings": {
     "properties": {
       "latency_2": {
         "type": "double"
       }
     }
   }
 }
 
POST correlate_latency_2/_bulk?refresh=true
{"index":{}}
{"latency_2":"100"}
{"index":{}}
{"latency_2":"200"}

POST correlate_latency*/_search?size=0
{
  "aggs": {
    "stats": {
      "matrix_stats": {
        "fields": ["latency", "latency_2"]
      }
    }
  }
}
```

We should provide a better error when we attempt to merge stats that are otherwise not grouped.

**Comment by salvatore-campagna** [comment]
@benwtrent @nik9000 When saying we just need a better error message, do you mean returning something like this is acceptable?
```
{
  "error" : {
    "root_cause" : [ ],
    "type" : "search_phase_execution_exception",
    "reason" : "",
    "phase" : "fetch",
    "grouped" : true,
    "failed_shards" : [ ],
    "caused_by" : {
      "type" : "aggregation_execution_exception",
      "reason" : "Aggregation [stats] using missing fields [latency]"
    }
  },
  "status" : 500
}
```

**Comment by benwtrent** [comment]
@salvatore-campagna that error would be difficult. It would change based on which shards were hit first right? Since the fields are a disjoint set, the field would be on one shard, but not on another. 

So, we should indicate that all fields need to exist in all indices or something.

**Comment by iverase** [comment]
And not a 500 please

**Comment by benwtrent** [comment]
This is definitely a "bad request" as the documentation is clear that the fields must all co-exist in the same docs.

**Comment by salvatore-campagna** [comment]
Closing after merging https://github.com/elastic/elasticsearch/pull/86926
