### ISSUE TITLE
[CI] Failure in ILMDocumentationIT.testAddSnapshotLifecyclePolicy

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#73317]
**Build scan**:

https://gradle-enterprise.elastic.co/s/ggpfrso2pg44k

**Repro line**:

```
./gradlew ':client:rest-high-level:integTest' --tests "org.elasticsearch.client.documentation.ILMDocumentationIT.testAddSnapshotLifecyclePolicy" \
  -Dtests.seed=FEDE81D1218CD9F5 \
  -Dtests.locale=ms \
  -Dtests.timezone=Asia/Qostanay \
  -Druntime.java=8
```

**Reproduces locally?**:

No

**Applicable branches**:

master, 7.x, 7.13, 7.12

**Failure history**:

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'ILMDocumentationIT%20AND%20testAddSnapshotLifecyclePolicy'),sort:!(process.time-start,desc))

Sporadic over the last 30 days, so likely caused by a rare race condition.

**Failure excerpt**:

```
org.elasticsearch.client.documentation.ILMDocumentationIT > testAddSnapshotLifecyclePolicy FAILED
    java.lang.AssertionError: 
    Expected: <SUCCESS>
         but: was <IN_PROGRESS>
        at __randomizedtesting.SeedInfo.seed([FEDE81D1218CD9F5:97581F960F5FDB98]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.client.documentation.ILMDocumentationIT.lambda$assertSnapshotExists$5(ILMDocumentationIT.java:1050)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.elasticsearch.client.documentation.ILMDocumentationIT.lambda$assertSnapshotExists$6(ILMDocumentationIT.java:1048)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1026)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:999)
        at org.elasticsearch.client.documentation.ILMDocumentationIT.assertSnapshotExists(ILMDocumentationIT.java:1042)
        at org.elasticsearch.client.documentation.ILMDocumentationIT.testAddSnapshotLifecyclePolicy(ILMDocumentationIT.java:900)
```

**Comment by droberts195** [comment]
Two more failures of this test occurred in the last couple of hours.

First https://gradle-enterprise.elastic.co/s/v3gclubg4i4be, which is for master but with a different assertion failure to the original issue description:

```
    java.lang.AssertionError: Found in progress snapshots [{my_repository=[{metadata={policy=policy_id}, failures=[], include_global_state=true, end_time=1970-01-01T00:00:00.000Z, duration_in_millis=0, version_id=8000099, uuid=jr2UvXYvRLC3t8MCwlYQsQ, version=8.0.0, start_time=2021-05-24T10:39:07.541Z, shards={total=0, failed=0, successful=0}, indices=[.async-search, idx], feature_states=[{indices=[.async-search], feature_name=async_search}], start_time_in_millis=1621852747541, data_streams=[], state=IN_PROGRESS, snapshot=name-fcugq_frt26gumpvngg1bg, end_time_in_millis=0}]}].
    Expected: a map with size <0>
         but: map size was <1>
        at __randomizedtesting.SeedInfo.seed([AB1574811F8C5FE0:C293EAC6315F5D8D]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:710)
        at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:342)
        at jdk.internal.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

And then https://gradle-enterprise.elastic.co/s/demqjte33ngtk, a 7.12 failure but with the same error as the original issue description:

```
Expected: <SUCCESS>
	     but: was <IN_PROGRESS>
```

**Comment by droberts195** [comment]
Since this is failing more frequently now I have muted the test:

master: ffa38331c901d0eb61ab009db968237fdec7b33c
7.x: 4a938e1e1ff8c766c89afcb5d65375695468fa37
7.13: 47a548ef0bfab0de9956ba02f0541996571e8eaf

**Comment by masseyke** [comment]
I can't reproduce this, but did look at it a little bit and noticed what looks like a bug in the test -- the latch.await() call always times out (we're not asserting that it's true). It looks like the reason is that the call to client.snapshot().get(getSnapshotsRequest, RequestOptions.DEFAULT) always hangs forever inside the executeListener. I don't know why. So maybe sometimes the snapshot has actually not completed by the time we get past this latch.await(), and that causes problems.

**Comment by martijnvg** [comment]
Test has been removed as part of #81299
