### ISSUE TITLE
[CI] Several xcontent parsing failures on 6.8 branch

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#73362]
I see several xconten parsing errors of the following form on the 6.8 branch today. Here's just the first of them

**Build scan**:
https://gradle-enterprise.elastic.co/s/x6uxmdpe765ty

**Repro line**:

./gradlew ':x-pack:plugin:sql:qa:single-node:integTestRunner' \
  -Dtests.seed=A7E0BDE08B78BE99 \
  -Dtests.class=org.elasticsearch.xpack.sql.qa.single_node.JdbcResultSetIT \
  -Dtests.method="testGettingInvalidLong" \
  -Dtests.security.manager=true \
  -Dtests.locale=pt-BR \
  -Dtests.timezone=Zulu \
  -Dcompiler.java=11 \
  -Druntime.java=13

**Reproduces locally?**:

No

**Applicable branches**:

Only seeing this on 6.8 so far

**Failure history**:

Several days at least, looking for earlier failures now

**Failure excerpt**:

```
java.sql.SQLException: Server sent bad type [x_content_parse_exception]. Original type was [[1:57] [sql/query] failed to parse field [time_zone]]. [org.elasticsearch.common.xcontent.XContentParseException: [1:57] [sql/query] failed to parse field [time_zone]
	at org.elasticsearch.common.xcontent.ObjectParser.parseValue(ObjectParser.java:316)
	at org.elasticsearch.common.xcontent.ObjectParser.parseSub(ObjectParser.java:362)
	at org.elasticsearch.common.xcontent.ObjectParser.parse(ObjectParser.java:168)
	at org.elasticsearch.common.xcontent.ObjectParser.apply(ObjectParser.java:182)
	at org.elasticsearch.xpack.sql.action.SqlQueryRequest.fromXContent(SqlQueryRequest.java:135)
	at org.elasticsearch.xpack.sql.plugin.RestSqlQueryAction.prepareRequest(RestSqlQueryAction.java:46)
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:91)
	[...]
Caused by: java.time.zone.ZoneRulesException: Unknown time-zone ID: Asia/Qostanay
	at java.base/java.time.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:279)
	at java.base/java.time.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:234)
	at java.base/java.time.ZoneRegion.ofId(ZoneRegion.java:120)
	at java.base/java.time.ZoneId.of(ZoneId.java:408)
	at java.base/java.time.ZoneId.of(ZoneId.java:356)
	at org.elasticsearch.xpack.sql.action.AbstractSqlQueryRequest.lambda$objectParser$3(AbstractSqlQueryRequest.java:79)
```

**Comment by cbuescher** [comment]
I just found https://github.com/elastic/elasticsearch/issues/72963 which is where we apparently already track this. Closing here then.
