### ISSUE TITLE
[CI] FIPS140SecureSettingsBootstrapCheckTests testLegacySecureSettingsIsNotAllowed failing

### ISSUE THREAD

**Issue by matriv** [elastic/elasticsearch#73458]
**Build scan**:
https://gradle-enterprise.elastic.co/s/zcg2khu4w6mki

**Repro line**:
```
./gradlew ':x-pack:plugin:security:unitTest' -Dtests.seed=9EF260B10C78D505 -Dtests.class=org.elasticsearch.xpack.security.FIPS140SecureSettingsBootstrapCheckTests -Dtests.method="testLegacySecureSettingsIsNotAllowed" -Dtests.security.manager=true -Dtests.locale=no -Dtests.timezone=Europe/Budapest -Dcompiler.java=11 -Druntime.java=8
```

**Reproduces locally?**:
no

**Applicable branches**:
6.8

**Failure history**:
https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20*%0A%3E%20There%20were%20test%20failures:%20*%20suites,%20*%20tests,%20*%20ignored%20*%20assumptions)%20%5Bseed:%20*&search.relativeStartTime=P7D&search.timeZoneId=Europe/Athens

**Failure excerpt**:
```
ERROR   0.05s J13 \| FIPS140SecureSettingsBootstrapCheckTests.testLegacySecureSettingsIsNotAllowed &lt;&lt;&lt; FAILURES! | &nbsp;
-- | --
&nbsp; | &gt; Throwable #1: java.security.KeyStoreException: Key protection  algorithm not found: java.security.NoSuchAlgorithmException: unrecognized algorithm name: PBEWithMD5AndDES | &nbsp;
&nbsp; | &gt; 	at __randomizedtesting.SeedInfo.seed([9EF260B10C78D505:A11D063CC1DCE8A5]:0) | &nbsp;
&nbsp; | &gt; 	at sun.security.pkcs12.PKCS12KeyStore.setKeyEntry(PKCS12KeyStore.java:677) | &nbsp;
&nbsp; | &gt; 	at sun.security.pkcs12.PKCS12KeyStore.engineSetEntry(PKCS12KeyStore.java:1396) | &nbsp;
&nbsp; | &gt; 	at java.security.KeyStore.setEntry(KeyStore.java:1557) | &nbsp;
&nbsp; | &gt; 	at org.elasticsearch.xpack.security.FIPS140SecureSettingsBootstrapCheckTests.generateV2Keystore(FIPS140SecureSettingsBootstrapCheckTests.java:83) | &nbsp;
&nbsp; | &gt; 	at org.elasticsearch.xpack.security.FIPS140SecureSettingsBootstrapCheckTests.testLegacySecureSettingsIsNotAllowed(FIPS140SecureSettingsBootstrapCheckTests.java:35) | &nbsp;
&nbsp; | &gt; 	at java.lang.Thread.run(Thread.java:748) | &nbsp;
&nbsp; | &gt; Caused by: java.security.NoSuchAlgorithmException: unrecognized algorithm name: PBEWithMD5AndDES | &nbsp;
&nbsp; | &gt; 	at sun.security.x509.AlgorithmId.get(AlgorithmId.java:448) | &nbsp;
&nbsp; | &gt; 	at sun.security.pkcs12.PKCS12KeyStore.setKeyEntry(PKCS12KeyStore.java:645) | &nbsp;
&nbsp; | &gt; 	... 41 more
```

**Comment by matriv** [comment]
And one more failure: https://gradle-enterprise.elastic.co/s/hn6djtnbtbkfq
