### ISSUE TITLE
Indexing valid multipolygons with high resolution points can fail

### ISSUE THREAD

**Issue by GaelTadh** [elastic/elasticsearch#7372]
Multipolygons with high resolution points may fail due to a rounding error that incorrectly detects an overlap. These polygons render correctly on tools like geojsonlint.com but fail in elasticsearch with a 

```
MapperParsingException[failed to parse [geo_shape]]; nested: InvalidShapeException[Self-intersection at or near point
```

For a sample failing polygon see : 
https://gist.github.com/GaelTadh/f9ccae0c703451786da6

**Comment by bogensberger** [comment]
+1

**Comment by clintongormley** [comment]
@nknize one to think about for your work replacing jTS

**Comment by gmoskovicz** [comment]
Any news regarding this? It still seems to be an issue with JTS coming from the following code:

```
    protected JtsGeometry jtsGeometry(Geometry geom) {
        //dateline180Check is false because ElasticSearch does it's own dateline wrapping
        JtsGeometry jtsGeometry = new JtsGeometry(geom, SPATIAL_CONTEXT, false, MULTI_POLYGON_MAY_OVERLAP);
        if (AUTO_VALIDATE_JTS_GEOMETRY)
            jtsGeometry.validate();
        if (AUTO_INDEX_JTS_GEOMETRY)
            jtsGeometry.index();
        return jtsGeometry;
    }
```

The stack trace is very clear about it

```
[2017-12-14T09:44:41,687][DEBUG][o.e.a.b.TransportShardBulkAction] [bGXdNiM] [test][4] failed to execute bulk item (index) BulkShardRequest [[test][4]] containing [index {[test][incident][AWBU10K79QsC6f7f66N0], source[n/a, actual length: [1.3mb], max length: 2kb]}]
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [affected_area]
	at org.elasticsearch.index.mapper.GeoShapeFieldMapper.parse(GeoShapeFieldMapper.java:473) ~[elasticsearch-5.6.1.jar:5.6.1]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:468) ~[elasticsearch-5.6.1.jar:5.6.1]
...
...
...
Caused by: org.locationtech.spatial4j.exception.InvalidShapeException: Self-intersection at or near point (-89.76905934507116, 29.318118373985925, NaN)
	at org.locationtech.spatial4j.shape.jts.JtsGeometry.validate(JtsGeometry.java:127) ~[spatial4j-0.6.jar:?]
	at org.elasticsearch.common.geo.builders.ShapeBuilder.jtsGeometry(ShapeBuilder.java:94) ~[elasticsearch-5.6.1.jar:5.6.1]
	at org.elasticsearch.common.geo.builders.PolygonBuilder.build(PolygonBuilder.java:226) ~[elasticsearch-5.6.1.jar:5.6.1]
	at org.elasticsearch.common.geo.builders.GeometryCollectionBuilder.build(GeometryCollectionBuilder.java:148) ~[elasticsearch-5.6.1.jar:5.6.1]
	at org.elasticsearch.index.mapper.GeoShapeFieldMapper.parse(GeoShapeFieldMapper.java:455) ~[elasticsearch-5.6.1.jar:5.6.1]
	... 61 more
```

This is coming from the following validation: https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/operation/valid/IsValidOp.java#L296-L303 . 

To me it seems to be that the issue is clearly coming from `JTS` rather than Elasticsearch itself?

**Comment by DaveCTurner** [comment]
The [sample failing polygon](https://gist.github.com/GaelTadh/f9ccae0c703451786da6) genuinely does a self-intersection as reported:

```
              ...
              [
                -0.0688679,
                51.4773
              ],
              [
                -0.0688818,
                51.4773
              ],
              [
                -0.0688079,
                51.4773
              ],
              ...
```

There is no rounding error here, nor a problem with resolution: these three points all have equal latitude and the longitudes are not in order, so the polygon's boundary does intersect itself. It looks like this:

<img width="393" alt="screen shot 2017-12-14 at 14 31 35" src="https://user-images.githubusercontent.com/5058284/33997297-ced1afaa-e0db-11e7-8230-66700abea7c2.png">
