### ISSUE TITLE
RangeQueryBuilderTests. testToQuery Failure due to unknown timezone

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#73899]
**Build scan**:
https://gradle-enterprise.elastic.co/s/6jqxfpy5cjtqe
https://gradle-enterprise.elastic.co/s/zwjln6kii34n2
**Repro line**:
```
./gradlew ':server:unitTest' -Dtests.seed=9BAD455C70F83B8C -Dtests.class=org.elasticsearch.index.query.RangeQueryBuilderTests -Dtests.method="testToQuery" -Dtests.security.manager=true -Dtests.locale=pl -Dtests.timezone=Asia/Harbin -Dcompiler.java=11 -Druntime.java=12
```

```
./gradlew ':server:unitTest' -Dtests.seed=E5067C3545BCA7FB -Dtests.class=org.elasticsearch.index.query.RangeQueryBuilderTests -Dtests.method="testToQuery" -Dtests.security.manager=true -Dtests.locale=is -Dtests.timezone=Mexico/General -Dcompiler.java=11 -Druntime.java=8
```
**Reproduces locally?**:
No
**Applicable branches**:
6.8
**Failure history**:
Similar failures recorded here: https://github.com/elastic/elasticsearch/issues/72963
**Failure excerpt**:

```
Dtests.timezone=Asia/Harbin -Dcompiler.java=11 -Druntime.java=12
ERROR   0.06s J14 | RangeQueryBuilderTests.testToQuery <<< FAILURES!
   > Throwable #1: java.time.zone.ZoneRulesException: Unknown time-zone ID: America/Nuuk
   > 	at __randomizedtesting.SeedInfo.seed([9BAD455C70F83B8C:6C564762017BFE66]:0)
   > 	at java.base/java.time.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:279)
   > 	at java.base/java.time.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:234)
   > 	at java.base/java.time.ZoneRegion.ofId(ZoneRegion.java:120)
   > 	at java.base/java.time.ZoneId.of(ZoneId.java:408)
   > 	at java.base/java.time.ZoneId.of(ZoneId.java:356)
   > 	at org.elasticsearch.common.time.DateUtils.dateTimeZoneToZoneId(DateUtils.java:74)
   > 	at org.elasticsearch.index.mapper.DateFieldMapper$DateFieldType.parseToMilliseconds(DateFieldMapper.java:317)
   > 	at org.elasticsearch.index.mapper.DateFieldMapper$DateFieldType.rangeQuery(DateFieldMapper.java:283)
   > 	at org.elasticsearch.index.query.RangeQueryBuilder.doToQuery(RangeQueryBuilder.java:519)
   > 	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:106)
   > 	at org.elasticsearch.test.AbstractQueryTestCase.testToQuery(AbstractQueryTestCase.java:429)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   > 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
   > 	at java.base/java.lang.Thread.run(Thread.java:835)
```

Here is the runtime info for each linked buildscan (respectively)

```
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 5.4.1
  OS Info               : Linux 4.15.0-1098-gcp (amd64)
  Compiler JDK Version  : 11 (18.9 11.0.11 [Java HotSpot(TM) 64-Bit Server VM 11.0.11+9-LTS-194])
  Compiler java.home    : /var/lib/jenkins/.java/oracle-11.0.11-linux
  Runtime JDK Version   : 12 (Oracle Corporation 12.0.2 [OpenJDK 64-Bit Server VM 12.0.2+10])
  Runtime java.home     : /var/lib/jenkins/.java/openjdk12
  Gradle JDK Version    : 11 (18.9 11.0.11 [Java HotSpot(TM) 64-Bit Server VM 11.0.11+9-LTS-194])
  Gradle java.home      : /var/lib/jenkins/.java/oracle-11.0.11-linux
  Random Testing Seed   : 9BAD455C70F83B8C
=======================================
```

```
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 5.4.1
  OS Info               : Linux 5.3.18-24.64-default (amd64)
  Compiler JDK Version  : 11 (18.9 11.0.11 [Java HotSpot(TM) 64-Bit Server VM 11.0.11+9-LTS-194])
  Compiler java.home    : /var/lib/jenkins/.java/oracle-11.0.11-linux
  Runtime JDK Version   : 1.8 (Amazon.com Inc. 1.8.0_232 [OpenJDK 64-Bit Server VM 25.232-b09])
  Runtime java.home     : /var/lib/jenkins/.java/corretto8
  Gradle JDK Version    : 11 (18.9 11.0.11 [Java HotSpot(TM) 64-Bit Server VM 11.0.11+9-LTS-194])
  Gradle java.home      : /var/lib/jenkins/.java/oracle-11.0.11-linux
  Random Testing Seed   : E5067C3545BCA7FB
=======================================
```

**Comment by mark-vieira** [comment]
Is this still an issue? I haven't seen any failures. Did we mute this test in 6.8?

**Comment by breskeby** [comment]
Still failing occasionally: https://gradle-enterprise.elastic.co/s/g6twafzuquxoq/console-log?anchor=620

**Comment by breskeby** [comment]
Is it possible that hasn't been ported back to openjdk 12: https://bugs.openjdk.java.net/browse/JDK-8243541

**Comment by valeriy42** [comment]
Another failure here https://gradle-enterprise.elastic.co/s/3xl6d7zzxn6cm

**Comment by mark-vieira** [comment]
This looks to have been resolved.
