### ISSUE TITLE
[CI] SearchHitsTests testEqualsAndHashcode failing

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#73948]
**Build scan:**
https://gradle-enterprise.elastic.co/s/k3mbxqiha2fly/tests/:server:test/org.elasticsearch.search.SearchHitsTests/testEqualsAndHashcode

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.search.SearchHitsTests.testEqualsAndHashcode" -Dtests.seed=AECE544420BEE9E2 -Dtests.locale=sr-Latn-ME -Dtests.timezone=Europe/Riga -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.SearchHitsTests&tests.test=testEqualsAndHashcode

**Failure excerpt:**
```
java.lang.IllegalArgumentException: duplicate key: sAlzu

  at __randomizedtesting.SeedInfo.seed([AECE544420BEE9E2:DFC12C89EF59A0CD]:0)
  at java.util.ImmutableCollections$MapN.<init>(ImmutableCollections.java:800)
  at java.util.Map.of(Map.java:1349)
  at org.elasticsearch.index.get.DocumentFieldTests.lambda$randomDocumentField$5(DocumentFieldTests.java:127)
  at org.elasticsearch.test.ESTestCase.randomList(ESTestCase.java:826)
  at org.elasticsearch.index.get.DocumentFieldTests.randomDocumentField(DocumentFieldTests.java:126)
  at org.elasticsearch.index.get.GetResultTests.randomDocumentFields(GetResultTests.java:276)
  at org.elasticsearch.search.SearchHitTests.createTestItem(SearchHitTests.java:71)
  at org.elasticsearch.search.SearchHitsTests.createSearchHitArray(SearchHitsTests.java:43)
  at org.elasticsearch.search.SearchHitsTests.createTestItem(SearchHitsTests.java:60)
  at org.elasticsearch.search.SearchHitsTests.createTestItem(SearchHitsTests.java:54)
  at org.elasticsearch.search.SearchHitsTests.createTestInstance(SearchHitsTests.java:168)
  at org.elasticsearch.search.SearchHitsTests.createTestInstance(SearchHitsTests.java:33)
  at org.elasticsearch.test.AbstractWireTestCase.testEqualsAndHashcode(AbstractWireTestCase.java:50)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by pgomulka** [comment]
very unlucky failure :) 
```
 List<Object> objectValues = randomList(1, 5, () ->
                        Map.of(randomAlphaOfLength(5), randomInt(),
                            randomAlphaOfLength(5), randomBoolean(),
                            randomAlphaOfLength(5), randomAlphaOfLength(10)));
```
where two keys were the same
```
k1 = "sAlzu"
v1 = {Integer@3740} -278244604
k2 = "sAlzu"
v2 = {Boolean@3718} false
k3 = "cZtSV"
v3 = "XFQzodaLvm"
```
