### ISSUE TITLE
Reproducible Failure in org.elasticsearch.common.RoundingTests.testRandomTimeUnitRounding

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#73995]
On current master I'm running into this:

```
 ./gradlew ':server:test' --tests "org.elasticsearch.common.RoundingTests.testRandomTimeUnitRounding" -Dtests.seed=75EA10B45683EE61 -Dtests.locale=id -Dtests.timezone=PRT -Druntime.java=16
```

fails as:

```
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 7.0.2
  OS Info               : Linux 5.11.0-18-generic (amd64)
  JDK Version           : 16 (Oracle)
  JAVA_HOME             : /usr/lib/jvm/jdk-16
  Random Testing Seed   : 75EA10B45683EE61
  In FIPS 140 mode      : false
=======================================

> Task :server:test
OpenJDK 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release.

REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.common.RoundingTests.testRandomTimeUnitRounding" -Dtests.seed=75EA10B45683EE61 -Dtests.locale=id -Dtests.timezone=PRT -Druntime.java=16

org.elasticsearch.common.RoundingTests > testRandomTimeUnitRounding FAILED
    java.lang.AssertionError: Expected [Rounding[DAY_OF_MONTH in Canada/Newfoundland]] to round [1991-10-28T02:46:41.527Z] to [1991-10-27T02:30:00Z] but instead rounded to [1991-10-27T03:30:00Z]
        at __randomizedtesting.SeedInfo.seed([75EA10B45683EE61:697BF1694B23F476]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.elasticsearch.common.RoundingTests.assertUnitRoundingSameAsJavaUtilTimeImplementation(RoundingTests.java:269)
        at org.elasticsearch.common.RoundingTests.testRandomTimeUnitRounding(RoundingTests.java:231)


Suite: Test class org.elasticsearch.common.RoundingTests
  1> [2021-06-10T05:35:38,752][INFO ][o.e.c.RoundingTests      ] [testRandomTimeUnitRounding] before test
  1> [2021-06-10T05:35:39,263][INFO ][o.e.c.RoundingTests      ] [testRandomTimeUnitRounding] after test
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.common.RoundingTests.testRandomTimeUnitRounding" -Dtests.seed=75EA10B45683EE61 -Dtests.locale=id -Dtests.timezone=PRT -Druntime.java=16
  2> java.lang.AssertionError: Expected [Rounding[DAY_OF_MONTH in Canada/Newfoundland]] to round [1991-10-28T02:46:41.527Z] to [1991-10-27T02:30:00Z] but instead rounded to [1991-10-27T03:30:00Z]
        at __randomizedtesting.SeedInfo.seed([75EA10B45683EE61:697BF1694B23F476]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.elasticsearch.common.RoundingTests.assertUnitRoundingSameAsJavaUtilTimeImplementation(RoundingTests.java:269)
        at org.elasticsearch.common.RoundingTests.testRandomTimeUnitRounding(RoundingTests.java:231)
  2> NOTE: leaving temporary files on disk at: /home/brownbear/src/elasticsearch/server/build/testrun/test/temp/org.elasticsearch.common.RoundingTests_75EA10B45683EE61-004
  2> NOTE: test params are: codec=Lucene87, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=id, timezone=PRT
  2> NOTE: Linux 5.11.0-18-generic amd64/AdoptOpenJDK 16.0.1 (64-bit)/cpus=48,threads=1,free=523306880,total=536870912
  2> NOTE: All tests run in this JVM: [RoundingTests]

Tests with failures:
 - org.elasticsearch.common.RoundingTests.testRandomTimeUnitRounding

1 test completed, 1 failed

```

**Comment by DaveCTurner** [comment]
Likely related to https://github.com/elastic/elasticsearch/pull/27976: Newfoundland has two midnights sometimes, so rounding to midnight can be kinda complicated:

![](https://davecturner.github.io/assets/2019-04-timezone-rounding/09-clocks-go-back-duplicated-midnight.png)

**Comment by pgomulka** [comment]
I tried investigating this and it looks like the bounds where incorrectly limiting the transition to be looked up. 
<img width="1258" alt="Screenshot 2021-07-21 at 14 49 41" src="https://user-images.githubusercontent.com/11137008/126491578-bce049e2-c843-4671-b1bf-0afb263dfce8.png">
here we have a transition on 
```
Transition[Overlap at 1991-10-27T00:01-02:30 to -03:30]”
 epochSecond = 688530660
 transition = {LocalDateTime@5192} “1991-10-27T00:01"
 offsetBefore = {ZoneOffset@5188} “-02:30”
 offsetAfter = {ZoneOffset@5189} “-03:30"
```
our bound[0] aka `minUtcMillis` is within 1h from the transition
bounds[0] = 688617707942
bounds[0] = Monday, 28 October 1991 02:41:47.942
so in https://github.com/elastic/elasticsearch/blob/a92a647b9f17d1bddf5c707490a19482c273eda3/server/src/main/java/org/elasticsearch/common/LocalTimeOffset.java#L624 we would skip this, because aur bound is greater than the transition time.
We should include it though, because when rounding dates > `minUtcMillis`, that transition should be taken into account

Once we have this fixed, we also need to make sure that we use a `"new"` minutcMillis when trying to decide if offset is fixed. https://github.com/elastic/elasticsearch/blob/68817d7ca29c264b3ea3f766737d81e2ebb4028c/server/src/main/java/org/elasticsearch/common/Rounding.java#L536

I made an attempt here to fix this [super dirty draft](https://github.com/elastic/elasticsearch/pull/75584)
