### ISSUE TITLE
[CI] MlDistributedFailureIT testClusterWithTwoMlNodes_RunsDatafeed_GivenOriginalNodeGoesDown failing

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#74101]
**Build scan:**
https://gradle-enterprise.elastic.co/s/7eyxhvbgatq22/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT/testClusterWithTwoMlNodes_RunsDatafeed_GivenOriginalNodeGoesDown

**Reproduction line:**
`./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testClusterWithTwoMlNodes_RunsDatafeed_GivenOriginalNodeGoesDown" -Dtests.seed=968E3BF60DAACCF8 -Dtests.locale=ar-TN -Dtests.timezone=Etc/GMT+6 -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT&tests.test=testClusterWithTwoMlNodes_RunsDatafeed_GivenOriginalNodeGoesDown

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <80000L>
     but: was <76000L>

  at __randomizedtesting.SeedInfo.seed([968E3BF60DAACCF8:31C30FE4D40F7813]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.lambda$testClusterWithTwoMlNodes_RunsDatafeed_GivenOriginalNodeGoesDown$17(MlDistributedFailureIT.java:526)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:973)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:946)
  at org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testClusterWithTwoMlNodes_RunsDatafeed_GivenOriginalNodeGoesDown(MlDistributedFailureIT.java:524)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by nik9000** [comment]
Looks like this particular failure has happened [twice](https://build-stats.elastic.co/goto/717159aa19da9a2e0489a27031e3cd39). It's really just the last two items on this:
![image](https://user-images.githubusercontent.com/215970/121944319-8a6d5280-cd20-11eb-87c0-a62c93f5beab.png)


I tried running locally and it didn't fail for me but it looks timeouty so I didn't expect it to.

**Comment by droberts195** [comment]
@dimitris-athanasiou this is quite likely to be a side effect of #73908.  Now that we delete the old data counts if the job has no model snapshot when it switches nodes this could explain the data counts not being what was expected in this test.  However, it still seems a bit strange that the data counts don't increase back to match the number of documents.  It may be that the datafeed isn't restarting from the very first document after the reset.  Or it may just be that the reset takes so long that the timeout on the final `assertBusy` needs increasing to give time for both the reset and the analysis.  Please can you investigate these failures to make sure there isn't a bug here that will affect end users.

**Comment by not-napoleon** [comment]
This just failed again on 7.x.  https://gradle-enterprise.elastic.co/s/nssnrikqikci4/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT/testClusterWithTwoMlNodes_RunsDatafeed_GivenOriginalNodeGoesDown?top-execution=1

**Comment by dimitris-athanasiou** [comment]
```
[2021-06-18T14:58:31,009][INFO ][o.e.x.m.a.TransportResetJobAction] [node_t1] [test-node-goes-down-while-running-job] Resetting job
[2021-06-18T14:58:31,047][INFO ][o.e.x.m.j.p.JobDataDeleter] [node_t1] [test-node-goes-down-while-running-job] running delete by query on [.ml-anomalies-shared]
[2021-06-18T14:58:31,057][WARN ][o.e.c.r.a.AllocationService] [node_t1] [.ml-anomalies-shared][0] marking unavailable shards as stale: [FaBtYGABSJiDRhdvXD3yfA]
[2021-06-18T14:58:31,264][INFO ][o.e.x.m.a.TransportResetJobAction] [node_t1] [test-node-goes-down-while-running-job] Reset has successfully completed
[2021-06-18T14:58:31,264][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [node_t3] Opening job [test-node-goes-down-while-running-job]
[2021-06-18T14:58:31,296][INFO ][o.e.x.m.j.p.a.AutodetectProcessManager] [node_t3] [test-node-goes-down-while-running-job] Loading model snapshot [N/A], job latest_record_timestamp [2021-06-05T23:06:16.115Z]
[2021-06-18T14:58:31,296][WARN ][o.e.x.m.j.p.a.AutodetectProcessManager] [node_t3] [test-node-goes-down-while-running-job] No model snapshot could be found for a job with processed records
[2021-06-18T14:58:31,297][WARN ][o.e.x.m.j.p.a.AutodetectProcessManager] [node_t3] [test-node-goes-down-while-running-job] No quantiles could be found for a job with processed records
```

The above is from the log of a failed run I managed to reproduce. It indicates that we're trying to delete the job's data while a shard of the results index is not available. This is probably because the shard was on the node that went down. Not sure yet why that is as we are waiting for all active shards to be active before allocating a job task to a node. I'll keep digging.
