### ISSUE TITLE
[CI] Gradle connection failures during yaml testing

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#74251]
```
org.gradle.internal.remote.internal.ConnectException: Could not connect to server [19f44967-3a74-43ee-8d95-af2378d76353 port:34401, addresses:[/127.0.0.1]]. Tried addresses: [/127.0.0.1].	
	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:67)	
	at org.gradle.internal.remote.internal.hub.MessageHubBackedClient.getConnection(MessageHubBackedClient.java:36)	
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:123)	
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)	
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)	
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)	
Caused by: java.net.ConnectException: Connection refused	
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)	
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)	
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:111)	
	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.tryConnect(TcpOutgoingConnector.java:81)	
	at org.gradle.internal.remote.internal.inet.TcpOutgoingConnector.connect(TcpOutgoingConnector.java:54)	
	... 5 more
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/r7ju3vkcjz6lg/tests/:client:rest:test/org.elasticsearch.client.RestClientMultipleHostsIntegTests/testNodeSelector

**Reproduction line:**
`null`

**Applicable branches:**
7.13

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.client.RestClientMultipleHostsIntegTests&tests.test=testNodeSelector

**Failure excerpt:**
```
org.apache.http.ProtocolException: Not a valid protocol version: [0x1e][0x1f]Æ[0x21]org.gradle.api.internal.tasks.testing.worker.RemoteTestClassProcessor[0x67]Æ[0x69]org.gradle.api.internal.tasks.testing.worker.RemoteTestClassProcessorstartProcessing[0xbf][0xc0][0xc1][0xc2]Æ[0xc4]org.gradle.api.internal.tasks.testing.worker.RemoteTestClassProcessorprocessTestClass[0x11b]·org.gradle.api.internal.tasks.testing.TestClassRunInfo³org.elasticsearch.client.sniff.SnifferBuilderTests[0x186][0x187][0x188]Æ[0x18a]org.gradle.api.internal.tasks.testing.worker.RemoteTestClassProcessorstop[0x1d5][0x1d6]

  at __randomizedtesting.SeedInfo.seed([A963826D1DCD4C77:CD5BF7B2D690FF55]:0)
  at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:209)
  at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:245)
  at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
  at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
  at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
  at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
  at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
  at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
  at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
  at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
  at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
  at java.lang.Thread.run(Thread.java:748)

  Caused by: org.apache.http.ParseException: Not a valid protocol version: [U+0000]Æorg.gradle.api.internal.tasks.testing.worker.RemoteTestClassProcessor[U+0000]Æorg.gradle.api.internal.tasks.testing.worker.RemoteTestClassProcessorstartProcessing[U+0000][U+0000]Æorg.gradle.api.internal.tasks.testing.worker.RemoteTestClassProcessorprocessTestClass·org.gradle.api.internal.tasks.testing.TestClassRunInfo³org.elasticsearch.client.sniff.SnifferBuilderTests[U+0000]Æorg.gradle.api.internal.tasks.testing.worker.RemoteTestClassProcessorstop[U+0000]

    at org.apache.http.message.BasicLineParser.parseProtocolVersion(BasicLineParser.java:148)
    at org.apache.http.message.BasicLineParser.parseStatusLine(BasicLineParser.java:366)
    at org.apache.http.impl.nio.codecs.DefaultHttpResponseParser.createMessage(DefaultHttpResponseParser.java:112)
    at org.apache.http.impl.nio.codecs.DefaultHttpResponseParser.createMessage(DefaultHttpResponseParser.java:50)
    at org.apache.http.impl.nio.codecs.AbstractMessageParser.parseHeadLine(AbstractMessageParser.java:156)
    at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:207)
    at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:245)
    at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
    at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
    at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
    at java.lang.Thread.run(Thread.java:748)

```

**Comment by mark-vieira** [comment]
So this looks to be some kind of port collision between the test itself and Gradle test workers. The message above seems to indicate that the HTTP client attempted to make a request to a mock server, but instead it got a response from a test worker. I suspect this is just some weird fluke and in theory shouldn't happen since we are picking ephemeral ports here but there most likely still race conditions possible.

**Comment by mark-vieira** [comment]
I'm going to chaulk this up as a fluke unless it becomes prevalent again.
