### ISSUE TITLE
[CI] LocalExporterResourceIntegTests testRemoveWhenResourcesShouldBeRemoved failing

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#74250]
**Build scan:**
https://gradle-enterprise.elastic.co/s/ld2llxb66yeum/tests/:x-pack:plugin:monitoring:test/org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests/testRemoveWhenResourcesShouldBeRemoved

**Reproduction line:**
`./gradlew ':x-pack:plugin:monitoring:test' --tests "org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests.testRemoveWhenResourcesShouldBeRemoved" -Dtests.seed=927798F5A4519E97 -Dtests.locale=pl -Dtests.timezone=America/Atka -Druntime.java=8`

**Applicable branches:**
7.x

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests&tests.test=testRemoveWhenResourcesShouldBeRemoved

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: is <true>
     but: was <false>

  at __randomizedtesting.SeedInfo.seed([927798F5A4519E97:50EDE468121F6D6A]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests.lambda$createResources$1(LocalExporterResourceIntegTests.java:142)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1035)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1008)
  at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests.createResources(LocalExporterResourceIntegTests.java:142)
  at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests.createResources(LocalExporterResourceIntegTests.java:133)
  at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests.assertResourcesExist(LocalExporterResourceIntegTests.java:355)
  at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests.testRemoveWhenResourcesShouldBeRemoved(LocalExporterResourceIntegTests.java:88)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by romseygeek** [comment]
On Darwin again, possibly related to https://github.com/elastic/elasticsearch/issues/68608

**Comment by davidkyle** [comment]
This time the `testCreateWhenResourcesShouldNotBeReplaced` method failed but the error and stack trace are the same.

https://gradle-enterprise.elastic.co/s/xlmtomrtulcxa/tests/:x-pack:plugin:monitoring:test/org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests/testCreateWhenResourcesShouldNotBeReplaced

Also Darwin

**Comment by astefan** [comment]
Another one today: https://gradle-enterprise.elastic.co/s/5nhvxntslqdli
`gradlew ':x-pack:plugin:monitoring:test' --tests "org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests.testCreateWhenResourcesShouldNotBeReplaced" -Dtests.seed=3B08359F960300E2 -Dtests.locale=he -Dtests.timezone=America/St_Thomas -Druntime.java=8`

Doesn't repro locally.
```
org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests > testCreateWhenResourcesShouldNotBeReplaced FAILED
    java.lang.AssertionError: 
    Expected: is <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([3B08359F960300E2:FC0BFC6FD0909A7C]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests.lambda$createResources$1(LocalExporterResourceIntegTests.java:142)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1039)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1012)
        at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests.createResources(LocalExporterResourceIntegTests.java:142)
        at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests.createResources(LocalExporterResourceIntegTests.java:133)
        at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests.assertResourcesExist(LocalExporterResourceIntegTests.java:355)
        at org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests.testCreateWhenResourcesShouldNotBeReplaced(LocalExporterResourceIntegTests.java:78)
```

**Comment by ywangd** [comment]
Another one on darwin https://gradle-enterprise.elastic.co/s/w5zgrav3icrc2/tests/:x-pack:plugin:monitoring:test/org.elasticsearch.xpack.monitoring.exporter.local.LocalExporterResourceIntegTests/testCreateWhenResourcesShouldNotBeReplaced?top-execution=1

**Comment by joegallo** [comment]
All the test failures are for `MAC` (/ darwin) and we don't run those anymore, so I'm closing this.
