### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT test {p0=search/350_point_in_time/msearch} failing

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#74458]
This might be caused by a missing backport?

**Build scan:**
https://gradle-enterprise.elastic.co/s/enuvgm2h3pft2/tests/:qa:mixed-cluster:v7.14.0%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=search%2F350_point_in_time%2Fmsearch%7D

**Reproduction line:**
`./gradlew ':qa:mixed-cluster:v7.14.0#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search/350_point_in_time/msearch}" -Dtests.seed=6C8BF0A1AA8B630C -Dtests.bwc=true -Dtests.locale=en-CA -Dtests.timezone=America/Blanc-Sablon -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dsearch/350_point_in_time/msearch%7D

**Failure excerpt:**
```
java.lang.AssertionError: Failure at [search/350_point_in_time:195]: expected [400] status code but api [msearch] returned [200 OK] [{"took":3,"responses":[{"pit_id":"g-azAwIFdGVzdDIWVDI0TEJpeTFUTi1XakhzTjZUTDhKZwAWWkV0QmJhMEtTVjJpb3FGQ0tIUEJCZwAAAAAAAAAAxRZVeDlnWjRralRPT2s2al9sY3pHOVdBAAR0ZXN0Fkl0Q3lxTUttUk9hV0MtdkxqZVpjYVEAFk5iRnU5dzFnU2F1MHhLTzdSZC1nZGcAAAAAAAAAAuQWalg0VkhBeFRUcmFjd1pGTHdxTTYwZwACFlQyNExCaXkxVE4tV2pIc042VEw4SmcAABZJdEN5cU1LbVJPYVdDLXZMamVaY2FRAAA=","took":3,"timed_out":false,"_shards":{"total":2,"successful":2,"skipped":0,"failed":0},"hits":{"total":{"value":4,"relation":"eq"},"max_score":0.2876821,"hits":[{"_index":"test2","_type":"_doc","_id":"45","_score":0.2876821,"_source":{"foo":"bar","id":45,"age":19}},{"_index":"test","_type":"_doc","_id":"1","_score":0.13353139,"_source":{"foo":"bar","id":1,"age":18}},{"_index":"test","_type":"_doc","_id":"42","_score":0.13353139,"_source":{"foo":"bar","id":42,"age":18}},{"_index":"test","_type":"_doc","_id":"172","_score":0.13353139,"_source":{"foo":"bar","id":172,"age":24}}]},"status":200},{"pit_id":"g-azAwIFdGVzdDIWVDI0TEJpeTFUTi1XakhzTjZUTDhKZwAWWkV0QmJhMEtTVjJpb3FGQ0tIUEJCZwAAAAAAAAAAxRZVeDlnWjRralRPT2s2al9sY3pHOVdBAAR0ZXN0Fkl0Q3lxTUttUk9hV0MtdkxqZVpjYVEAFk5iRnU5dzFnU2F1MHhLTzdSZC1nZGcAAAAAAAAAAuQWalg0VkhBeFRUcmFjd1pGTHdxTTYwZwACFlQyNExCaXkxVE4tV2pIc042VEw4SmcAABZJdEN5cU1LbVJPYVdDLXZMamVaY2FRAAA=","took":2,"timed_out":false,"_shards":{"total":2,"successful":2,"skipped":0,"failed":0},"hits":{"total":{"value":4,"relation":"eq"},"max_score":1.0,"hits":[{"_index":"test","_type":"_doc","_id":"1","_score":1.0,"_source":{"foo":"bar","id":1,"age":18}},{"_index":"test","_type":"_doc","_id":"42","_score":1.0,"_source":{"foo":"bar","id":42,"age":18}},{"_index":"test","_type":"_doc","_id":"172","_score":1.0,"_source":{"foo":"bar","id":172,"age":24}},{"_index":"test2","_type":"_doc","_id":"45","_score":1.0,"_source":{"foo":"bar","id":45,"age":19}}]},"status":200}]}]

  at __randomizedtesting.SeedInfo.seed([6C8BF0A1AA8B630C:E4DFCF7B04770EF4]:0)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:451)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:428)
  at jdk.internal.reflect.GeneratedMethodAccessor19.invoke(null:-1)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

  Caused by: java.lang.AssertionError: expected [400] status code but api [msearch] returned [200 OK] [{"took":3,"responses":[{"pit_id":"g-azAwIFdGVzdDIWVDI0TEJpeTFUTi1XakhzTjZUTDhKZwAWWkV0QmJhMEtTVjJpb3FGQ0tIUEJCZwAAAAAAAAAAxRZVeDlnWjRralRPT2s2al9sY3pHOVdBAAR0ZXN0Fkl0Q3lxTUttUk9hV0MtdkxqZVpjYVEAFk5iRnU5dzFnU2F1MHhLTzdSZC1nZGcAAAAAAAAAAuQWalg0VkhBeFRUcmFjd1pGTHdxTTYwZwACFlQyNExCaXkxVE4tV2pIc042VEw4SmcAABZJdEN5cU1LbVJPYVdDLXZMamVaY2FRAAA=","took":3,"timed_out":false,"_shards":{"total":2,"successful":2,"skipped":0,"failed":0},"hits":{"total":{"value":4,"relation":"eq"},"max_score":0.2876821,"hits":[{"_index":"test2","_type":"_doc","_id":"45","_score":0.2876821,"_source":{"foo":"bar","id":45,"age":19}},{"_index":"test","_type":"_doc","_id":"1","_score":0.13353139,"_source":{"foo":"bar","id":1,"age":18}},{"_index":"test","_type":"_doc","_id":"42","_score":0.13353139,"_source":{"foo":"bar","id":42,"age":18}},{"_index":"test","_type":"_doc","_id":"172","_score":0.13353139,"_source":{"foo":"bar","id":172,"age":24}}]},"status":200},{"pit_id":"g-azAwIFdGVzdDIWVDI0TEJpeTFUTi1XakhzTjZUTDhKZwAWWkV0QmJhMEtTVjJpb3FGQ0tIUEJCZwAAAAAAAAAAxRZVeDlnWjRralRPT2s2al9sY3pHOVdBAAR0ZXN0Fkl0Q3lxTUttUk9hV0MtdkxqZVpjYVEAFk5iRnU5dzFnU2F1MHhLTzdSZC1nZGcAAAAAAAAAAuQWalg0VkhBeFRUcmFjd1pGTHdxTTYwZwACFlQyNExCaXkxVE4tV2pIc042VEw4SmcAABZJdEN5cU1LbVJPYVdDLXZMamVaY2FRAAA=","took":2,"timed_out":false,"_shards":{"total":2,"successful":2,"skipped":0,"failed":0},"hits":{"total":{"value":4,"relation":"eq"},"max_score":1.0,"hits":[{"_index":"test","_type":"_doc","_id":"1","_score":1.0,"_source":{"foo":"bar","id":1,"age":18}},{"_index":"test","_type":"_doc","_id":"42","_score":1.0,"_source":{"foo":"bar","id":42,"age":18}},{"_index":"test","_type":"_doc","_id":"172","_score":1.0,"_source":{"foo":"bar","id":172,"age":24}},{"_index":"test2","_type":"_doc","_id":"45","_score":1.0,"_source":{"foo":"bar","id":45,"age":19}}]},"status":200}]}]

    at org.junit.Assert.fail(Assert.java:88)
    at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:345)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:444)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:428)
    at jdk.internal.reflect.GeneratedMethodAccessor19.invoke(null:-1)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
    at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
    at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
    at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
    at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
    at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
    at java.lang.Thread.run(Thread.java:834)

```

**Comment by dnhatn** [comment]
Thanks @ywangd. It seems that https://github.com/elastic/elasticsearch/pull/63167 didn't make into 7.x.

**Comment by dnhatn** [comment]
Fixed in https://github.com/elastic/elasticsearch/pull/74459

**Comment by markharwood** [comment]
Failing in 7.13 https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.13+periodic+bwc/BWC_VERSION=7.11.2,nodes=general-purpose/143/

**Comment by mark-vieira** [comment]
Still failing on both 7.x and 7.13 branches.

**Comment by dnhatn** [comment]
I have adjusted the BWC versions on 7.x and 7.13.
