### ISSUE TITLE
Search Timeout does not take effect

### ISSUE THREAD

**Issue by boicehuang** [elastic/elasticsearch#74467]
Hi, I sent the following wildcard query to elasticsearch 7.10  
```
POST index1/_search 
{
	"size": 10,
	"timeout": "30000ms",
	"query": {
		"bool": {
			"filter": [{
				"range": {
					"__TIMESTAMP_US__": {
						"from": 1624204800000000,
						"to": 1624260673679000,
					}
				}
			}, {
				"query_string": {
					"query": "Message: *traitor*"
				}
			}]
		}
	}
}
```
The query execution took a long time, much more than the timeout. The result of the TASK API was shown below.
```
   "BUCZUVcHRka0r8RPuPiJDA:140498087" : {
      "node" : "BUCZUVcHRka0r8RPuPiJDA",
      "id" : 140498087,
      "type" : "transport",
      "action" : "indices:data/read/search[phase/query]",
      "description" : "shardId[[index1][11]]",
      "start_time" : "2021-06-23T08:04:07.778Z",
      "start_time_in_millis" : 1624435447778,
      "running_time" : "1.8m",
      "running_time_in_nanos" : 112809170447,
      "cancellable" : true,
      "parent_task_id" : "_o_CqFc0QoGCyUQE9i8_gw:33128316",
      "headers" : { }
    }
```
So I try to print the jstack of the node and got below. The search thread stuck on collecting term dictionary for a long time, even though I set a 30-second timeout.
```
"elasticsearch[1623812907002042532][search][T#49]" #258 daemon prio=5 os_prio=0 tid=0x00007ef780106800 nid=0x2668 runnable [0x00007ef51f4f2000]
   java.lang.Thread.State: RUNNABLE
        at java.nio.Bits.copyToArray(Unknown Source)
        at java.nio.DirectByteBuffer.get(Unknown Source)
        at org.apache.lucene.store.ByteBufferGuard.getBytes(ByteBufferGuard.java:93)
        at org.apache.lucene.store.ByteBufferIndexInput.readBytes(ByteBufferIndexInput.java:89)
        at org.apache.lucene.codecs.blocktree.IntersectTermsEnumFrame.load(IntersectTermsEnumFrame.java:183)
        at org.apache.lucene.codecs.blocktree.IntersectTermsEnum.pushFrame(IntersectTermsEnum.java:196)
        at org.apache.lucene.codecs.blocktree.IntersectTermsEnum._next(IntersectTermsEnum.java:510)
        at org.apache.lucene.codecs.blocktree.IntersectTermsEnum.next(IntersectTermsEnum.java:353)
        at org.apache.lucene.search.MultiTermQueryConstantScoreWrapper$1.collectTerms(MultiTermQueryConstantScoreWrapper.java:120)
        at org.apache.lucene.search.MultiTermQueryConstantScoreWrapper$1.rewrite(MultiTermQueryConstantScoreWrapper.java:147)
        at org.apache.lucene.search.MultiTermQueryConstantScoreWrapper$1.scorer(MultiTermQueryConstantScoreWrapper.java:219)
        at org.apache.lucene.search.Weight.scorerSupplier(Weight.java:147)
        at org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight.scorerSupplier(LRUQueryCache.java:787)
        at org.elasticsearch.indices.IndicesQueryCache$CachingWeightWrapper.scorerSupplier(IndicesQueryCache.java:164)
        at org.apache.lucene.search.BooleanWeight.scorerSupplier(BooleanWeight.java:379)
        at org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight.scorerSupplier(LRUQueryCache.java:787)
        at org.elasticsearch.indices.IndicesQueryCache$CachingWeightWrapper.scorerSupplier(IndicesQueryCache.java:164)
        at org.apache.lucene.search.BooleanWeight.scorerSupplier(BooleanWeight.java:379)
        at org.apache.lucene.search.BooleanWeight.scorer(BooleanWeight.java:344)
        at org.apache.lucene.search.Weight.bulkScorer(Weight.java:181)
        at org.apache.lucene.search.BooleanWeight.bulkScorer(BooleanWeight.java:338)
        at org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight.bulkScorer(LRUQueryCache.java:867)
        at org.elasticsearch.indices.IndicesQueryCache$CachingWeightWrapper.bulkScorer(IndicesQueryCache.java:170)
        at org.elasticsearch.search.internal.ContextIndexSearcher$1.bulkScorer(ContextIndexSearcher.java:162)
        at org.elasticsearch.search.internal.ContextIndexSearcher.searchInternal(ContextIndexSearcher.java:189)
        at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:173)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:442)
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:270)
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:113)

```

The query spends a lot of time loading the term dictionary,  which is executed before the iteration of docs.  But the query timeout depends on the iteration of docs as shown in [CancellableBulkScorer](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/internal/CancellableBulkScorer.java#L40)

So currently if the collecting term dictionary phase, or the fetch phase is very time-consuming, search timeout would not take effect. I wonder whether it is better to build a timeout mechanism to monitor the entire query and fetch process?

Any help will be appreciated.

**Comment by javanna** [comment]
hi @boicehuang thanks for opening this issue. This has come up already a few times, and even triggered some discussions on whether we should rename this parameter, because `timeout` is misleading (see #47716). It looks to me that what you are looking for is more of a client side timeout, as you don't want the query to last longer than 30 seconds, while the server side timeout that you use as part of the search request is more of a best effort and does not guarantee that the request will never last longer than the specified amount of time. The description of it in our [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html) does mention that it works at the shard level, perhaps we need to work on clarifying it further.
