### ISSUE TITLE
nonlocal binding

### ISSUE THREAD

**Issue by drewr** [elastic/elasticsearch#7447]
Currently when setting the transport host to an interface that doesn't yet exist (using Linux's `ip_nonlocal_bind`, eg), ES will start fine, but then complain often about not being able to make connections internally to itself:

```
2014-08-25 23:26:28.802763500 [2014-08-25 23:26:28,799][WARN ][cluster.service          ] [foo] failed to reconnect to node [foo][eEex7V1LRGOV6SNBw-UZmg][monitor][inet[/192.168.56.200:9300]]
2014-08-25 23:26:28.802764500 org.elasticsearch.transport.ConnectTransportException: [foo][inet[/192.168.56.200:9300]] connect_timeout[30s]
2014-08-25 23:26:28.802766500   at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:677)
2014-08-25 23:26:28.803108500   at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:611) 
```

Clearly, the transport not having a working interface that it _expects_ to be working is exceptional and should be reported as such.  I'm wondering how we can support when you don't expect it.  I thought about a `network.allow_nonlocal_bind` or somesuch flag.  Or maybe added syntax to the interface definition, like `~_eth0_`.  Thoughts?

**Comment by drewr** [comment]
The larger vision here is that ES wouldn't need to be restarted in an environment where local network interfaces are coming and going. This could happen, for example, with VPN where a virtual interface may not be created yet.

**Comment by clintongormley** [comment]
@drewr ok - I still don't understand, you're going to need to spell it out for me :)

What do you expect ES to do if the network interface isn't available?

**Comment by clintongormley** [comment]
Nothing further. Closing
