### ISSUE TITLE
[CI]  o.e.xpack.autoscaling.storage.ReactiveStorageDeciderServiceTests.testIsNotTierOnlyDecision Fails

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#74487]
New test added in https://github.com/elastic/elasticsearch/commit/8f2a327cdb242397ec0eb933a8d454e65565062d failing in 7.x 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+periodic+java-matrix/ES_RUNTIME_JAVA=adoptopenjdk8,nodes=general-purpose/96/

```
java.lang.AssertionError: 
Expected: is <false>
     but: was <true>
	at __randomizedtesting.SeedInfo.seed([A24D8BA70BCF81B9:509CE1329DCEC982]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.autoscaling.storage.ReactiveStorageDeciderServiceTests.testIsNotTierOnlyDecision(ReactiveStorageDeciderServiceTests.java:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)

```   
Reproduced for me 

    ./gradlew ':x-pack:plugin:autoscaling:test' --tests "org.elasticsearch.xpack.autoscaling.storage.ReactiveStorageDeciderServiceTests.testIsNotTierOnlyDecision" -Dtests.seed=A24D8BA70BCF81B9 -Dtests.locale=ar-AE -Dtests.timezone=Mexico/BajaNorte -Druntime.java=8

cc @DaveCTurner @henningandersen

**Comment by henningandersen** [comment]
Fixed in #74475
