### ISSUE TITLE
[CI] FiltersAggregatorTests.testMatchNoneTopLevel failing on master

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#74677]
This happend on a local run but seems reproducable on master

**Build scan**:

Edit: this is from a CI test failure on Sunday that looks similar
https://gradle-enterprise.elastic.co/s/wphgk3nxj73jg

**Repro line**:

```
./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.filter.FiltersAggregatorTests.testMatchNoneTopLevel" -Dtests.seed=D315C18B9D436BD4 -Dtests.locale=zh-TW -Dtests.timezone=Africa/Timbuktu -Druntime.java=16
```

**Reproduces locally?**:

yes

**Applicable branches**:

master

**Failure history**:

**Failure excerpt**:

```
org.elasticsearch.search.aggregations.bucket.filter.FiltersAggregatorTests > testMatchNoneTopLevel FAILED
    java.lang.AssertionError: Expected a map containing
                           test: a map containing
    segments_with_doc_count_field: <0>
       segments_with_deleted_docs: <0>
               segments_collected: <0>
                 segments_counted: expected <1> but was <2>
                          filters: a list containing
                                  0: a map containing
                                query: "MatchNoDocsQuery(\"User requested \"match_none\" query.\")"
                      specialized_for: "match_none"
        at __randomizedtesting.SeedInfo.seed([D315C18B9D436BD4:1A0FCEB66D3AF1FE]:0)
        at io.github.nik9000.mapmatcher.MapMatcher.assertMap(MapMatcher.java:78)
        at io.github.nik9000.mapmatcher.MapMatcher.assertMap(MapMatcher.java:61)
        at org.elasticsearch.search.aggregations.bucket.filter.FiltersAggregatorTests.lambda$testMatchNoneTopLevel$25(FiltersAggregatorTests.java:678)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.debugTestCase(AggregatorTestCase.java:634)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.lambda$debugTestCase$9(AggregatorTestCase.java:589)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.withIndex(AggregatorTestCase.java:553)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.debugTestCase(AggregatorTestCase.java:589)
        at org.elasticsearch.search.aggregations.bucket.filter.FiltersAggregatorTests.testMatchNoneTopLevel(FiltersAggregatorTests.java:669)
```

**Comment by tlrx** [comment]
A different test in the same test suite failed today with a similar error: https://gradle-enterprise.elastic.co/s/vypetlhquslnk

```

org.elasticsearch.search.aggregations.bucket.filter.FiltersAggregatorTests > testTermFilter FAILED
    java.lang.AssertionError: Expected a map containing
                           test: a map containing
    segments_with_doc_count_field: <0>
       segments_with_deleted_docs: <0>
               segments_collected: <0>
                 segments_counted: expected <1> but was <2>
                          filters: a list containing
                                  0: a map containing
                                query: "f:0"
                      specialized_for: "term"
                results_from_metadata: <2>
        at __randomizedtesting.SeedInfo.seed([4A87550F20633125:583542EB712611B0]:0)
        at io.github.nik9000.mapmatcher.MapMatcher.assertMap(MapMatcher.java:78)
        at io.github.nik9000.mapmatcher.MapMatcher.assertMap(MapMatcher.java:61)
        at org.elasticsearch.search.aggregations.bucket.filter.FiltersAggregatorTests.lambda$testTermFilter$27(FiltersAggregatorTests.java:717)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.debugTestCase(AggregatorTestCase.java:634)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.lambda$debugTestCase$9(AggregatorTestCase.java:589)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.withIndex(AggregatorTestCase.java:553)
        at org.elasticsearch.search.aggregations.AggregatorTestCase.debugTestCase(AggregatorTestCase.java:589)
        at org.elasticsearch.search.aggregations.bucket.filter.FiltersAggregatorTests.testTermFilter(FiltersAggregatorTests.java:708)
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.filter.FiltersAggregatorTests.testTermFilter" -Dtests.seed=4A87550F20633125 -Dtests.locale=uk -Dtests.timezone=Africa/Banjul -Druntime.java=11

```

**Comment by tlrx** [comment]
@nik9000 if you happen to look at this class, there are many CI failures for the following test in the past 7 days:
- testTermFilter
- testMatchNoneFilter
- testTermTopLevel
- testMatchAll
- testMatchNoneTopLevel

**Comment by nik9000** [comment]
Sorry I hadn't picked this up yesterday. I'd lost it in the shuffle between morning emails and starting work for real. I'll dig now. Sorry for the noise!

**Comment by nik9000** [comment]
Well that wasn't too bad! I was asserting that the indices I was testing with only had a single segment. By accident. Changed it to `>=1` and it passed when I ran it hundreds of times.

**Comment by tlrx** [comment]
Thanks Nik!
