### ISSUE TITLE
[CI] :client:sniffer:test and :client:transport:test failures in FIPS mode

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#74922]
**Build scan**:
https://gradle-enterprise.elastic.co/s/ci6nizixl4you (:client:sniffer:test) 
https://gradle-enterprise.elastic.co/s/2fiuydltov4gc (:client:transport:test)

**Repro line**:
`./gradlew :client:sniffer:test` I guess??

**Reproduces locally?**:
Haven't tried, 

**Applicable branches**:
7.x, master

**Failure history**:

**Failure excerpt**:
```
java.lang.SecurityException: SHA MessageDigest not available |  
-- | --
  | at java.base/java.io.ObjectStreamClass.computeDefaultSUID(ObjectStreamClass.java:1998) |  
  | at java.base/java.io.ObjectStreamClass$1.run(ObjectStreamClass.java:290) |  
  | at java.base/java.io.ObjectStreamClass$1.run(ObjectStreamClass.java:288) |  
  | at java.base/java.security.AccessController.doPrivileged(AccessController.java:312) |  
  | at java.base/java.io.ObjectStreamClass.getSerialVersionUID(ObjectStreamClass.java:287) |  
  | at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:717) |  
  | at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2022) |  
  | at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1872) |  
  | at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2179) |  
  | at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1689) |  
  | at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:495) |  
  | at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:453) |  
  | at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.deserializeWorker(SystemApplicationClassLoaderWorker.java:153) |  
  | at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:121) |  
  | at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71) |  
  | at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69) |  
  | at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)


```

**Comment by jkakavas** [comment]
This is an `MessageDigest md = MessageDigest.getInstance("SHA");` in `ObjectStreamClass.java`. 

*BUT* this is gradle internal code IIUC and we don't need to run Gradle JVM in FIPS mode so maybe we're too aggressive in our configuration somewhere?

**Comment by breskeby** [comment]
The gradle code you see is the one that runs the test executor, so I don't think we're too aggressive here as we definitely only configure the test jvm. maybe a class loader issue. I keep digging.
