### ISSUE TITLE
[CI] Sliced scroll YAML test failures

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#75226]
Both `Sliced scroll with doc values` and `Sliced scroll` tests failed.

**Build scan**: https://gradle-enterprise.elastic.co/s/vy73kgronu2fa

**Repro line**: ```./gradlew ':qa:mixed-cluster:v7.15.0#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=scroll/12_slices/Sliced scroll with doc values}" -Dtests.seed=532C57CEE2516DA6 -Dtests.bwc=true -Dtests.locale=zh-Hans-SG -Dtests.timezone=Antarctica/Syowa -Druntime.java=11``` 

```
./gradlew ':qa:mixed-cluster:v7.15.0#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=scroll/12_slices/Sliced scroll}" -Dtests.seed=532C57CEE2516DA6 -Dtests.bwc=true -Dtests.locale=zh-Hans-SG -Dtests.timezone=Antarctica/Syowa -Druntime.java=11
```

**Reproduces locally?**: No

**Applicable branches**: master

**Failure history**:  [history](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'Sliced%20scroll'),sort:!(process.time-start,desc)))

**Failure excerpt**:

For `Sliced scroll` test:

```
java.lang.AssertionError: Failure at [scroll/12_slices:54]: 	
Expected: <3>	
     but: was <1>	
at __randomizedtesting.SeedInfo.seed([532C57CEE2516DA6:DB7868144CAD005E]:0)	
at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:451)	
at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:428)	
at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)	
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
at java.lang.reflect.Method.invoke(Method.java:566)

...

[2021-07-12T13:11:16,952][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] Stash dump on test failure [{	
  "stash" : {	
    "scroll_id" : "FGluY2x1ZGVfY29udGV4dF91dWlkDnF1ZXJ5VGhlbkZldGNoAxZQWXM2cmRqalI1Q0NuRzZxTmtmRkJBAAAAAAAAAEYWUEhHSk9TaWNTQ2VLMkVKdFlEVElhQRYwajhBdWl5QlNSRzhEM1pzX2ZhOUNnAAAAAAAAAeMWeFRJZ0xURDRSNW13cGEzTEpfMWhjdxYwajhBdWl5QlNSRzhEM1pzX2ZhOUNnAAAAAAAAAeQWeFRJZ0xURDRSNW13cGEzTEpfMWhjdw==",	
    "body" : {	
      "_scroll_id" : "FGluY2x1ZGVfY29udGV4dF91dWlkDnF1ZXJ5VGhlbkZldGNoAxZQWXM2cmRqalI1Q0NuRzZxTmtmRkJBAAAAAAAAAEYWUEhHSk9TaWNTQ2VLMkVKdFlEVElhQRYwajhBdWl5QlNSRzhEM1pzX2ZhOUNnAAAAAAAAAeMWeFRJZ0xURDRSNW13cGEzTEpfMWhjdxYwajhBdWl5QlNSRzhEM1pzX2ZhOUNnAAAAAAAAAeQWeFRJZ0xURDRSNW13cGEzTEpfMWhjdw==",	
      "took" : 13,	
      "timed_out" : false,	
      "_shards" : {	
        "total" : 5,	
        "successful" : 3,	
        "skipped" : 0,	
        "failed" : 2,	
        "failures" : [	
          {	
            "shard" : 1,	
            "index" : "test_sliced_scroll",	
            "node" : "8kLbhqk6QBqfWeo_OXTSgA",	
            "reason" : {	
              "type" : "illegal_state_exception",	
              "reason" : "unexpected byte [0x03]"	
            }	
          }	
        ]	
      },	
      "hits" : {	
        "total" : 1,	
        "max_score" : null,	
        "hits" : [	
          {	
            "_index" : "test_sliced_scroll",	
            "_id" : "3",	
            "_score" : null,	
            "_source" : {	
              "foo" : 3	
            },	
            "sort" : [	
              3	
            ]	
          }	
        ]	
      }	
    }	
  }	
}]
```

For `Sliced scroll with doc values` test:

```
java.lang.AssertionError: Failure at [scroll/12_slices:163]: 	
Expected: <3>	
     but: was <1>	
at __randomizedtesting.SeedInfo.seed([532C57CEE2516DA6:DB7868144CAD005E]:0)	
at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:451)	
at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:428)	
at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)	
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
at java.lang.reflect.Method.invoke(Method.java:566)

...


[2021-07-12T13:08:04,177][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] Stash dump on test failure [{	
  "stash" : {	
    "scroll_id" : "FGluY2x1ZGVfY29udGV4dF91dWlkDnF1ZXJ5VGhlbkZldGNoAxYwajhBdWl5QlNSRzhEM1pzX2ZhOUNnAAAAAAAAAMAWeFRJZ0xURDRSNW13cGEzTEpfMWhjdxYwajhBdWl5QlNSRzhEM1pzX2ZhOUNnAAAAAAAAAL8WeFRJZ0xURDRSNW13cGEzTEpfMWhjdxZQWXM2cmRqalI1Q0NuRzZxTmtmRkJBAAAAAAAAABkWUEhHSk9TaWNTQ2VLMkVKdFlEVElhQQ==",	
    "body" : {	
      "_scroll_id" : "FGluY2x1ZGVfY29udGV4dF91dWlkDnF1ZXJ5VGhlbkZldGNoAxYwajhBdWl5QlNSRzhEM1pzX2ZhOUNnAAAAAAAAAMAWeFRJZ0xURDRSNW13cGEzTEpfMWhjdxYwajhBdWl5QlNSRzhEM1pzX2ZhOUNnAAAAAAAAAL8WeFRJZ0xURDRSNW13cGEzTEpfMWhjdxZQWXM2cmRqalI1Q0NuRzZxTmtmRkJBAAAAAAAAABkWUEhHSk9TaWNTQ2VLMkVKdFlEVElhQQ==",	
      "took" : 14,	
      "timed_out" : false,	
      "_shards" : {	
        "total" : 5,	
        "successful" : 3,	
        "skipped" : 0,	
        "failed" : 2,	
        "failures" : [	
          {	
            "shard" : 1,	
            "index" : "test_sliced_scroll",	
            "node" : "8kLbhqk6QBqfWeo_OXTSgA",	
            "reason" : {	
              "type" : "illegal_state_exception",	
              "reason" : "unexpected byte [0x03]"	
            }	
          }	
        ]	
      },	
      "hits" : {	
        "total" : {	
          "value" : 1,	
          "relation" : "eq"	
        },	
        "max_score" : null,	
        "hits" : [	
          {	
            "_index" : "test_sliced_scroll",	
            "_id" : "3",	
            "_score" : null,	
            "_source" : {	
              "foo" : 3	
            },	
            "sort" : [	
              3	
            ]	
          }	
        ]	
      }	
    }	
  }	
}]
```

```

**Comment by jtibshirani** [comment]
This doesn't reproduce now and hasn't failed since July 13th. I think it was caused by a temporary version-check mismatch during the backport. Please reopen the issue if the same failure pops up again.
