### ISSUE TITLE
[CI] SamlRealmTests.testCreateSigningCredentialFromKeyStoreFailureScenarios failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#75379]
**Build scan**: https://gradle-enterprise.elastic.co/s/oaqn5q3yqffto

**Repro line**:
```
gradlew ':x-pack:plugin:security:unitTest' -Dtests.seed=650E90755FF7B650 -Dtests.class=org.elasticsearch.xpack.security.authc.saml.SamlRealmTests -Dtests.method="testCreateSigningCredentialFromKeyStoreFailureScenarios" -Dtests.security.manager=true -Dtests.locale=ar-LY -Dtests.timezone=America/Atka -Dcompiler.java=11 -Druntime.java=8
```

**Reproduces locally?**: no

**Applicable branches**: 6.8

**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:'testCreateSigningCredentialFromKeyStoreFailureScenarios%20AND%20build.branch%20:%20%226.8%22'),sort:!(process.time-start,desc))

**Failure excerpt**:
```
ERROR   0.03s J9  | SamlRealmTests.testCreateSigningCredentialFromKeyStoreFailureScenarios <<< FAILURES!
   > Throwable #1: java.security.KeyStoreException: Key protection  algorithm not found: java.security.UnrecoverableKeyException: Encrypt Private Key failed: unrecognized algorithm name: PBEWithSHA1AndDESede
   > 	at __randomizedtesting.SeedInfo.seed([650E90755FF7B650:13239521B5747733]:0)
   > 	at sun.security.pkcs12.PKCS12KeyStore.setKeyEntry(PKCS12KeyStore.java:677)
   > 	at sun.security.pkcs12.PKCS12KeyStore.engineSetKeyEntry(PKCS12KeyStore.java:577)
   > 	at java.security.KeyStore.setKeyEntry(KeyStore.java:1140)
   > 	at org.elasticsearch.xpack.security.authc.saml.SamlRealmTests.testCreateSigningCredentialFromKeyStoreFailureScenarios(SamlRealmTests.java:508)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.security.UnrecoverableKeyException: Encrypt Private Key failed: unrecognized algorithm name: PBEWithSHA1AndDESede
   > 	at sun.security.pkcs12.PKCS12KeyStore.encryptPrivateKey(PKCS12KeyStore.java:921)
   > 	at sun.security.pkcs12.PKCS12KeyStore.setKeyEntry(PKCS12KeyStore.java:614)
   > 	... 40 more
   > Caused by: java.security.NoSuchAlgorithmException: unrecognized algorithm name: PBEWithSHA1AndDESede
   > 	at sun.security.x509.AlgorithmId.get(AlgorithmId.java:448)
   > 	at sun.security.pkcs12.PKCS12KeyStore.mapPBEAlgorithmToOID(PKCS12KeyStore.java:938)
   > 	at sun.security.pkcs12.PKCS12KeyStore.encryptPrivateKey(PKCS12KeyStore.java:895)
   > 	... 41 more
```

Similar/identic with https://github.com/elastic/elasticsearch/issues/72639.

**Comment by jkakavas** [comment]
This has been muted in #75770, closing this as won't fix since 6.8 is EOL
