### ISSUE TITLE
[CI] ClassCastException from SystemIndexManager.readMappingVersion(SystemIndexManager.java:272)

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#75375]
**Build scan**: https://gradle-enterprise.elastic.co/s/ipagefwpjmiru

**Repro line**: 
```
gradlew ':x-pack:qa:rolling-upgrade:v7.6.0#twoThirdsUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=mixed_cluster/90_ml_data_frame_analytics_crud/Get old classification job stats}" -Dtests.seed=221AEA7E8C89D798 -Dtests.bwc=true -Dtests.locale=fi -Dtests.timezone=Asia/Kuwait -Druntime.java=8
```

**Reproduces locally?**: No

**Applicable branches**: 7.x

**Failure excerpt**:

This was found in node 7.6.0-0 own logs:

```
[2021-07-14T22:12:33,492][INFO ][o.e.i.s.IndexShard       ] [v7.6.0-0] [test_operation_based_recovery][0] detected new primary with primary term [2], global checkpoint [176], max_seq_no [176]
[2021-07-14T22:12:33,492][INFO ][o.e.i.s.IndexShard       ] [v7.6.0-0] [turn_off_translog_retention][0] detected new primary with primary term [2], global checkpoint [200], max_seq_no [200]
[2021-07-14T22:12:33,496][INFO ][o.e.i.s.IndexShard       ] [v7.6.0-0] [empty_index][4] primary-replica resync completed with 0 operations
[2021-07-14T22:12:33,496][INFO ][o.e.i.s.IndexShard       ] [v7.6.0-0] [empty_index][3] primary-replica resync completed with 0 operations
[2021-07-14T22:12:33,501][INFO ][o.e.i.s.IndexShard       ] [v7.6.0-0] [closed_index_created_on_old][0] primary-replica resync completed with 0 operations
[2021-07-14T22:12:33,498][INFO ][o.e.i.s.IndexShard       ] [v7.6.0-0] [test_index_reindex][0] primary-replica resync completed with 0 operations
[2021-07-14T22:12:33,498][INFO ][o.e.i.s.IndexShard       ] [v7.6.0-0] [queries][0] primary-replica resync completed with 0 operations
[2021-07-14T22:12:33,502][INFO ][o.e.i.s.IndexShard       ] [v7.6.0-0] [recover_with_soft_deletes][0] primary-replica resync completed with 0 operations
[2021-07-14T22:12:33,503][INFO ][o.e.i.s.IndexShard       ] [v7.6.0-0] [index_with_replicas][4] primary-replica resync completed with 0 operations
[2021-07-14T22:12:33,505][INFO ][o.e.i.s.IndexShard       ] [v7.6.0-0] [test_date_nanos][0] primary-replica resync completed with 0 operations
[2021-07-14T22:12:33,507][INFO ][o.e.i.s.IndexShard       ] [v7.6.0-0] [index_history_uuid][0] primary-replica resync completed with 0 operations
[2021-07-14T22:12:33,508][WARN ][o.e.c.s.ClusterApplierService] [v7.6.0-0] failed to notify ClusterStateListener
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at org.elasticsearch.indices.SystemIndexManager.readMappingVersion(SystemIndexManager.java:272) ~[elasticsearch-7.15.0-SNAPSHOT.jar:7.15.0-SNAPSHOT]
	at org.elasticsearch.indices.SystemIndexManager.checkIndexMappingUpToDate(SystemIndexManager.java:256) ~[elasticsearch-7.15.0-SNAPSHOT.jar:7.15.0-SNAPSHOT]
	at org.elasticsearch.indices.SystemIndexManager.calculateIndexState(SystemIndexManager.java:225) ~[elasticsearch-7.15.0-SNAPSHOT.jar:7.15.0-SNAPSHOT]
	at org.elasticsearch.indices.SystemIndexManager.getUpgradeStatus(SystemIndexManager.java:139) ~[elasticsearch-7.15.0-SNAPSHOT.jar:7.15.0-SNAPSHOT]
	at org.elasticsearch.indices.SystemIndexManager.lambda$clusterChanged$0(SystemIndexManager.java:88) ~[elasticsearch-7.15.0-SNAPSHOT.jar:7.15.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_291]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_291]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_291]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_291]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_291]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_291]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_291]
	at org.elasticsearch.indices.SystemIndexManager.clusterChanged(SystemIndexManager.java:89) ~[elasticsearch-7.15.0-SNAPSHOT.jar:7.15.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListener(ClusterApplierService.java:516) [elasticsearch-7.15.0-SNAPSHOT.jar:7.15.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:506) [elasticsearch-7.15.0-SNAPSHOT.jar:7.15.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:474) [elasticsearch-7.15.0-SNAPSHOT.jar:7.15.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:408) [elasticsearch-7.15.0-SNAPSHOT.jar:7.15.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:57) [elasticsearch-7.15.0-SNAPSHOT.jar:7.15.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:152) [elasticsearch-7.15.0-SNAPSHOT.jar:7.15.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673) [elasticsearch-7.15.0-SNAPSHOT.jar:7.15.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:259) [elasticsearch-7.15.0-SNAPSHOT.jar:7.15.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:222) [elasticsearch-7.15.0-SNAPSHOT.jar:7.15.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_291]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
[2021-07-14T22:12:33,516][INFO ][o.e.c.r.DelayedAllocationService] [v7.6.0-0] scheduling reroute for delayed shards in [0s] (24 delayed shards)
[2021-07-14T22:12:33,548][INFO ][o.e.c.m.MetadataIndexTemplateService] [v7.6.0-0] adding index template [.ml-notifications-000002] for index patterns [.ml-notifications-000002]
```

**Comment by ywangd** [comment]
I took a closer look. The issue is genuine. `SystemIndexManager` [assumes](https://github.com/elastic/elasticsearch/blob/7.14/server/src/main/java/org/elasticsearch/indices/SystemIndexManager.java#L272) value of the `$versionMetaKey` field is always a `String`. But [mappings](https://github.com/elastic/elasticsearch/blob/c8783d38782a84d506570d765ec4d6dcd7ca892a/server/src/main/resources/org/elasticsearch/tasks/task-index-mapping.json#L3-L5) of the `.tasks` index on versions prior to 7.12.0 has the following `_meta` section:

```
    "_meta": {
      "version": 3
    },
```

Note that the above `version` field has an `Integer` value instead of `String`. This is what caused the `ClassCastException`. I think the fix could simply be replacing the casting with a `toString()` call. But since this is in the area of System Index, I'll unassign myself and let the true experts (@gwbrown @william0901 ) to speak for themselves 🙏

**Comment by gwbrown** [comment]
Thanks for your investigation @ywangd, it really sped up the process of implementing the fix! It wasn't *quite* as simple as a `toString()` call as the code expected an Elasticsearch version, but pretty close.
