### ISSUE TITLE
ILM's searchable_snapshot action can get "stuck" attempting to create a snapshot with a duplicate name, requiring the move-to-step API to unstick

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#75401]
I've observed this twice, though with limited capability to gather information, and I don't have steps to reproduce at this time (though I haven't tried very hard).

Observed on 7.13.2 only so far, but with a sample size of two that's not necessarily an indication it's the only impacted version.

The primary indicator that the index is "stuck" this way is an error message similar to:
```
invalid_snapshot_name_exception: [my-index-lt7xdseariqi0ld_6clspq] Invalid snapshot name [my-index-lt7xdseariqi0ld_6clspq], snapshot with the same name already exists
```

When this occurs, the index will be stuck in the `create-snapshot` step, repeatedly trying to create the snapshot, but failing because a `PARTIAL` snapshot already exists with that name. The ILM retry API leads to the same result. Deleting the snapshot causes the index to move on to the `mount-snapshot`, which then fails because the expected snapshot doesn't exist.

The only workaround that I've found so far is to use the move-to-step API to move the index back to the `generate-snapshot-name` step to force a new snapshot name to be generated, like so:
```
POST _ilm/move/restored-metricbeat-7.12.1-2021.05.10-000004
{
  "current_step": { 
    "phase": "cold",
    "action": "searchable_snapshot",
    "name": "ERROR"
  },
  "next_step": { 
    "phase": "cold",
    "action": "searchable_snapshot",
    "name": "generate-snapshot-name"
  }
}
```

It would be nice if ILM could detect when this happens and automatically generate a new snapshot name before retrying, rather than trying over and over with the same name, forcing manual intervention.

Stack trace for completeness, although I don't think this will be terribly useful:
```
InvalidSnapshotNameException[[my-index-lt7xdseariqi0ld_6clspq] Invalid snapshot name [my-index-lt7xdseariqi0ld_6clspq], snapshot with the same name already exists]
at org.elasticsearch.snapshots.SnapshotsService.ensureSnapshotNameAvailableInRepo(SnapshotsService.java:630)
at org.elasticsearch.snapshots.SnapshotsService.access$4700(SnapshotsService.java:119)
at org.elasticsearch.snapshots.SnapshotsService$2.execute(SnapshotsService.java:416)
at org.elasticsearch.repositories.blobstore.BlobStoreRepository$1.execute(BlobStoreRepository.java:393)
at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:48)
at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:691)
at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:313)
at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:208)
at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:62)
at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:140)
at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:139)
at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:177)
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673)
at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:241)
at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:204)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by andreidan** [comment]
Thanks for filing this @gwbrown 

I agree with the workaround in the description but a more straightforward way for this would be to delete the existing snapshot in the repository (assuming the managed index exists in a functional state). This way, ILM will retry the `create-snapshot` step, successfully create the snapshot, and carry on with the lifecycle.
