### ISSUE TITLE
[ML] testCloseUnassignedFailedJobAndStopUnassignedStoppingDatafeed test failing in 7.13

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#75447]
**Build scan**:

https://gradle-enterprise.elastic.co/s/ww33ngdwfhz4i

**Repro line**:

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testCloseUnassignedFailedJobAndStopUnassignedStoppingDatafeed" \
  -Dtests.seed=65508E0A48E168F5 \
  -Dtests.locale=en-CA \
  -Dtests.timezone=Africa/Asmera \
  -Druntime.java=16

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testCloseUnassignedFailedJobAndStopUnassignedStoppingDatafeed" \
  -Dtests.seed=65508E0A48E168F5 \
  -Dtests.locale=en-CA \
  -Dtests.timezone=Africa/Asmera \
  -Druntime.java=16

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.MlDistributedFailureIT.testCloseUnassignedFailedJobAndStopUnassignedStoppingDatafeed" \
  -Dtests.seed=65508E0A48E168F5 \
  -Dtests.locale=en-CA \
  -Dtests.timezone=Africa/Asmera \
  -Druntime.java=16
```

**Reproduces locally?**:
No

**Applicable branches**:
7.13

**Failure history**:
no recent failure history

**Failure excerpt**:

```
ElasticsearchStatusException[cannot close job datafeed [test-stop-unassigned-datafeed-for-failed-job-datafeed] hasn't been stopped]
	at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.conflictStatusException(ExceptionsHelper.java:73)
	at org.elasticsearch.xpack.ml.action.TransportCloseJobAction.lambda$checkDatafeedsHaveStopped$7(TransportCloseJobAction.java:243)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
	at org.elasticsearch.xpack.ml.datafeed.persistence.DatafeedConfigProvider.lambda$findDatafeedsForJobIds$1(DatafeedConfigProvider.java:210)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:31)
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:83)
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:77)
	at org.elasticsearch.action.ActionListener$RunAfterActionListener.onResponse(ActionListener.java:339)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:655)
	at org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:109)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:424)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:418)
	at org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:219)
	at org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$1(FetchSearchPhase.java:101)
	at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:107)
	at org.elasticsearch.action.search.FetchSearchPhase.access$000(FetchSearchPhase.java:36)
	at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:84)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.lang.Thread.run(Thread.java:831)
```

```
[2021-07-19T11:00:01,115][INFO ][o.e.x.m.d.DatafeedManager] [node_t4] [realtime_analysis_error] attempt to stop datafeed [test-stop-unassigned-datafeed-for-failed-job-datafeed] for job [test-stop-unassigned-datafeed-for-failed-job]
[2021-07-19T11:00:01,115][INFO ][o.e.x.m.d.DatafeedManager] [node_t4] [realtime_analysis_error] try lock [20s] to stop datafeed [test-stop-unassigned-datafeed-for-failed-job-datafeed] for job [test-stop-unassigned-datafeed-for-failed-job]...
[2021-07-19T11:00:01,115][INFO ][o.e.x.m.d.DatafeedManager] [node_t4] [realtime_analysis_error] stopping datafeed [test-stop-unassigned-datafeed-for-failed-job-datafeed] for job [test-stop-unassigned-datafeed-for-failed-job], acquired [true]...
[2021-07-19T11:00:01,116][WARN ][o.e.p.AllocatedPersistentTask] [node_t4] task datafeed-test-stop-unassigned-datafeed-for-failed-job-datafeed failed with an exception
org.elasticsearch.xpack.ml.datafeed.DatafeedJob$AnalysisProblemException: ElasticsearchStatusException[Cannot flush because job [test-stop-unassigned-datafeed-for-failed-job] does not have a corresponding autodetect process]
	at org.elasticsearch.xpack.ml.datafeed.DatafeedJob.flushJob(DatafeedJob.java:453) ~[main/:?]
	at org.elasticsearch.xpack.ml.datafeed.DatafeedJob.run(DatafeedJob.java:394) ~[main/:?]
	at org.elasticsearch.xpack.ml.datafeed.DatafeedJob.runRealtime(DatafeedJob.java:194) ~[main/:?]
	at org.elasticsearch.xpack.ml.datafeed.DatafeedManager$Holder.executeRealTime(DatafeedManager.java:434) [main/:?]
	at org.elasticsearch.xpack.ml.datafeed.DatafeedManager$Holder.access$600(DatafeedManager.java:317) [main/:?]
	at org.elasticsearch.xpack.ml.datafeed.DatafeedManager$3.doRun(DatafeedManager.java:241) [main/:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732) [elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: org.elasticsearch.ElasticsearchStatusException: Cannot flush because job [test-stop-unassigned-datafeed-for-failed-job] does not have a corresponding autodetect process
	at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.conflictStatusException(ExceptionsHelper.java:73) ~[x-pack-core-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.xpack.ml.job.process.autodetect.AutodetectProcessManager.flushJob(AutodetectProcessManager.java:283) ~[main/:?]
	at org.elasticsearch.xpack.ml.action.TransportFlushJobAction.taskOperation(TransportFlushJobAction.java:50) ~[main/:?]
	at org.elasticsearch.xpack.ml.action.TransportFlushJobAction.taskOperation(TransportFlushJobAction.java:21) ~[main/:?]
	at org.elasticsearch.action.support.tasks.TransportTasksAction.nodeOperation(TransportTasksAction.java:131) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.action.support.tasks.TransportTasksAction.access$800(TransportTasksAction.java:51) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(TransportTasksAction.java:307) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.action.support.tasks.TransportTasksAction$NodeTransportHandler.messageReceived(TransportTasksAction.java:303) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:61) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.transport.TransportService.sendLocalRequest(TransportService.java:901) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.transport.TransportService.access$100(TransportService.java:68) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.transport.TransportService$3.sendRequest(TransportService.java:140) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:845) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:759) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:685) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.action.support.tasks.TransportTasksAction$AsyncAction.start(TransportTasksAction.java:248) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.action.support.tasks.TransportTasksAction$AsyncAction.access$100(TransportTasksAction.java:202) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.action.support.tasks.TransportTasksAction.doExecute(TransportTasksAction.java:83) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.xpack.ml.action.TransportJobTaskAction.doExecute(TransportJobTaskAction.java:60) ~[main/:?]
	at org.elasticsearch.xpack.ml.action.TransportJobTaskAction.doExecute(TransportJobTaskAction.java:33) ~[main/:?]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:173) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:42) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:171) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:149) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:77) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:86) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:66) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:402) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:54) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.client.ParentTaskAssigningClient.doExecute(ParentTaskAssigningClient.java:52) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:402) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:390) ~[elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.xpack.ml.datafeed.DatafeedJob.flushJob(DatafeedJob.java:440) ~[main/:?]
	... 10 more
[2021-07-19T11:00:01,119][INFO ][o.e.x.m.d.DatafeedManager] [node_t4] [realtime_analysis_error] datafeed [test-stop-unassigned-datafeed-for-failed-job-datafeed] for job [test-stop-unassigned-datafeed-for-failed-job] has been stopped
[2021-07-19T11:00:01,134][WARN ][o.e.p.PersistentTasksClusterService] [node_t1] persistent task datafeed-test-stop-unassigned-datafeed-for-failed-job-datafeed failed
org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: analysis_problem_exception: ElasticsearchStatusException[Cannot flush because job [test-stop-unassigned-datafeed-for-failed-job] does not have a corresponding autodetect process]
	at org.elasticsearch.xpack.ml.datafeed.DatafeedJob.flushJob(DatafeedJob.java:453) ~[main/:?]
	at org.elasticsearch.xpack.ml.datafeed.DatafeedJob.run(DatafeedJob.java:394) ~[main/:?]
	at org.elasticsearch.xpack.ml.datafeed.DatafeedJob.runRealtime(DatafeedJob.java:194) ~[main/:?]
	at org.elasticsearch.xpack.ml.datafeed.DatafeedManager$Holder.executeRealTime(DatafeedManager.java:434) ~[main/:?]
	at org.elasticsearch.xpack.ml.datafeed.DatafeedManager$Holder.access$600(DatafeedManager.java:317) ~[main/:?]
	at org.elasticsearch.xpack.ml.datafeed.DatafeedManager$3.doRun(DatafeedManager.java:241) ~[main/:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732) [elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.13.4-SNAPSHOT.jar:7.13.4-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: org.elasticsearch.ElasticsearchStatusException: Cannot flush because job [test-stop-unassigned-datafeed-for-failed-job] does not have a corresponding autodetect process
```

**Comment by droberts195** [comment]
This test is unmuted and not failing in the more recent branches.  Since 7.13 is not going to be developed further I'll close this.
