### ISSUE TITLE
Unable to create index with _source disabled

### ISSUE THREAD

**Issue by jessebs** [elastic/elasticsearch#75650]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.13.2 & 7.13.4

**Plugins installed**: []

**JVM version** (`java -version`): openjdk version "16.0.1" 2021-04-20

**OS version** (`uname -a` if on a Unix-like system): MacOS 11.4

**Description of the problem including expected versus actual behavior**: I'm developing a plugin, the client passed to Plugin#createComponents is unable to be used to create an index with source disabled.

```
CreateIndexRequest createIndexRequest = new CreateIndexRequest("myIndex");
createIndexRequest.mapping("_source", Collections.singletonMap("enabled", false));
client.admin().indices().create(createIndexRequest).actionGet();
```

I also tried with a JSON string and XContentBuilder.  I tried settings createIndexRequest.source instead of mapping, and added mapping to the source, but it didn't change the behavior.

```
[2021-07-22T21:01:08,334][INFO ][o.e.c.m.MetadataCreateIndexService] [mymachine.local] failed on parsing mappings on index creation [myIndex]
org.elasticsearch.indices.InvalidTypeNameException: mapping type name [_source] can't start with '_' unless it is called [_doc]
	at org.elasticsearch.index.mapper.MapperService.validateTypeName(MapperService.java:509) ~[elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.index.mapper.MapperService.mergeMappings(MapperService.java:471) ~[elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.index.mapper.MapperService.mergeAndApplyMappings(MapperService.java:348) ~[elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:329) ~[elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.updateIndexMappingsAndBuildSortOrder(MetadataCreateIndexService.java:1046) ~[elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.lambda$applyCreateIndexWithTemporaryService$3(MetadataCreateIndexService.java:409) [elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:627) [elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexWithTemporaryService(MetadataCreateIndexService.java:407) [elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequestWithV1Templates(MetadataCreateIndexService.java:493) [elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:370) [elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:377) [elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:294) [elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:48) [elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:691) [elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:313) [elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:208) [elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:62) [elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:140) [elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:139) [elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:177) [elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673) [elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:241) [elasticsearch-7.13.4.jar:7.13.4]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:204) [elasticsearch-7.13.4.jar:7.13.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by jessebs** [comment]
Apparently a way around this is to use a PutMappingRequest after creating the index.  Is this the preferred way?

```
PutMappingRequest mappingRequest = new PutMappingRequest(indexName);
mappingRequest.type("_doc");
mappingRequest.source(Collections.singletonMap("_source", Collections.singletonMap("enabled", false)));
client.admin().indices().putMapping(mappingRequest).actionGet();
```

**Comment by jessebs** [comment]
Also, the first approach works if I change the mapping call to `createIndexRequest.mapping("_doc", Collections.singletonMap("_source", Collections.singletonMap("enabled", false)));`

I think this ends up being a documentation issue, not a code issue.
