### ISSUE TITLE
impossible to configure security with 0.0.0.0 config

### ISSUE THREAD

**Issue by f1-outsourcing** [elastic/elasticsearch#75663]
With this config 
network.host: 0.0.0.0

trying to run
/usr/share/elasticsearch/bin/elasticsearch-setup-passwords interactive

Getting:
Failed to establish SSL connection to elasticsearch at https://x.x.x.x:9200/_security/_authenticate?pretty.

Elasticsearch is connecting on a ip address???? Of course you will get ssl errors

PS. would also be good to have something like with curl --insecure so you can develop a container image, without the necessity to have to use development certificates.

PPS. how do you know even what ip to choose if I use multiple?

Is there some other way to configure security, without having to go through the web interface?

version: elasticsearch-7.13.4-1.x86_64

**Comment by georgebridgeman** [comment]
The docs for the `elasticsearch-setup-passwords` tool are [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-passwords.html). Try the `-u` parameter to tell the tool where to send the requests. AFAIK, all it does is automate a bunch of requests to the [security API](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api.html).

**Comment by f1-outsourcing** [comment]
Maybe this should be added to help output? 

```
@test2 elasticsearch]# /usr/share/elasticsearch/bin/elasticsearch-setup-passwords -h
Sets the passwords for reserved users

Commands
--------
auto - Uses randomly generated passwords
interactive - Uses passwords entered by a user

Non-option arguments:
command

Option             Description
------             -----------
-E <KeyValuePair>  Configure a setting
-h, --help         Show help
-s, --silent       Show minimal output
-v, --verbose      Show verbose output
```

**Comment by f1-outsourcing** [comment]
Why is the elasticsearch-setup-passwords with -u parameter even looking at my hostname config?

```

[@test2 elasticsearch]# /usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto -u 'http://localhost:9200'
Exception in thread "main" java.lang.IllegalArgumentException: Could not resolve placeholder 'ELASTIC_HN'
     at org.elasticsearch.common.settings.PropertyPlaceholder.parseStringValue(PropertyPlaceholder.java:105)
     at org.elasticsearch.common.settings.PropertyPlaceholder.replacePlaceholders(PropertyPlaceholder.java:58)
     at org.elasticsearch.common.settings.Settings$Builder.replacePropertyPlaceholders(Settings.java:1167)
     at org.elasticsearch.common.settings.Settings$Builder.replacePropertyPlaceholders(Settings.java:1123)
     at org.elasticsearch.node.InternalSettingsPreparer.initializeSettings(InternalSettingsPreparer.java:97)
     at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:79)
     at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:89)
     at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:80)
     at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
     at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
     at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:80)
     at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
     at org.elasticsearch.cli.Command.main(Command.java:79)
     at org.elasticsearch.xpack.security.authc.esnative.tool.SetupPasswordTool.main(SetupPasswordTool.java:117)
```

**Comment by tvernum** [comment]
Hi, thanks very much for your interest in Elasticsearch.

`elasticsearch-setup-passwords` is a multi-command which has implications for the way options work. You will get help on the `--url` option if you call `elasticsearch-setup-passwords interactive -h`.
It would indeed be preferable for that help to be provided when you pass `elasticsearch-setup-passwords -h`, but making those changes hasn't been a priority given it is covered by the online documentation.

Setup passwords always loads your elasticsearch configuration - it needs to in order to determine things such as SSL configurations and the bootstrap password. If your configuration cannot be loaded, then the tool will fail.

Ultimately, setup-passwords is a utility to assist with the first steps in setting up a cluster. The documentation covers how to use it, as well as other options for configuring the passwords in your cluster.

Though there are some possible improvements we could make here, I don't think there is a bug, per se.  
Perhaps we can move this discussion to the [Elasticsearch forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6), where we can provide better support.

**Comment by f1-outsourcing** [comment]
> `elasticsearch-setup-passwords` is a multi-command which has implications for the way options work. You will get help on the `--url` option if you call `elasticsearch-setup-passwords interactive -h`.
> It would indeed be preferable for that help to be provided when you pass `elasticsearch-setup-passwords -h`, but making those changes hasn't been a priority given it is covered by the online documentation.
> 
I would make it priority to put them here. After al this were people are getting there info first, not? Besides in the online docs that I was looking at it was not mentioned..

> Setup passwords always loads your elasticsearch configuration - it needs to in order to determine things such as SSL configurations and the bootstrap password. If your configuration cannot be loaded, then the tool will fail.
> 
So remove this from the code, this is not necessary when specifying a url.


> 
> Though there are some possible improvements we could make here, I don't think there is a bug, per se.
I would say if someone codes to use an ip address in a url and also codes validation on a certificate, classifies as bug don't you?
