### ISSUE TITLE
can not read from the default centos7 private path

### ISSUE THREAD

**Issue by f1-outsourcing** [elastic/elasticsearch#75664]
[2021-07-24T21:53:52,804][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [test2] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/pki/tls/private" "read")
      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.13.4.jar:7.13.4]
      at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.13.4.jar:7.13.4]
      at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75) ~[elasticsearch-7.13.4.jar:7.13.4]
      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116) ~[elasticsearch-cli-7.13.4.jar:7.13.4]
      at org.elasticsearch.cli.Command.main(Command.java:79) ~[elasticsearch-cli-7.13.4.jar:7.13.4]
      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.13.4.jar:7.13.4]
      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81) ~[elasticsearch-7.13.4.jar:7.13.4]
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/pki/tls/private" "read")
      at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:?]
      at java.security.AccessController.checkPermission(AccessController.java:1036) ~[?:?]
      at java.lang.SecurityManager.checkPermission(SecurityManager.java:408) ~[?:?]
      at java.lang.SecurityManager.checkRead(SecurityManager.java:747) ~[?:?]
      at sun.nio.fs.UnixPath.checkRead(UnixPath.java:810) ~[?:?]

If I check with the elasticsearch user, it is accessible.

[@/]# su elasticsearch
bash-4.2$ ls -l /etc/pki/tls/private/
total 4
-r--r----- 1 elasticsearch elasticsearch 1675 Jul 23  2020 xxxxx.key

elasticsearch-7.13.4-1.x86_64

**Comment by f1-outsourcing** [comment]
I guess this has to do with the jvm security as well, but if you release rpms you better take into account the default paths

**Comment by mark-vieira** [comment]
Can you provide the full stacktrace, there should be further causes down below.
