### ISSUE TITLE
syslog log4j2.properties not working

### ISSUE THREAD

**Issue by f1-outsourcing** [elastic/elasticsearch#75666]
log4j2.properties

```
appender.syslog.type = Syslog
appender.syslog.name = syslog
appender.syslog.host = xxxxxxx.local
appender.syslog.port = 514
appender.syslog.protocol = UDP
appender.syslog.facility = LOCAL0
appender.syslog.format = RFC5424
```

```
2021-07-25 11:29:53,411 main ERROR An exception occurred processing Appender syslog java.security.AccessControlException: access denied ("java.net.SocketPermission" "x.x.x.x:514" "connect,resolve")
      at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
      at java.base/java.security.AccessController.checkPermission(AccessController.java:1036)
      at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:408)
      at java.base/java.lang.SecurityManager.checkConnect(SecurityManager.java:910)
      at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:810)
      at java.base/sun.nio.ch.DatagramChannelImpl.blockingSend(DatagramChannelImpl.java:849)
      at java.base/sun.nio.ch.DatagramSocketAdaptor.send(DatagramSocketAdaptor.java:217)
      at java.base/java.net.DatagramSocket.send(DatagramSocket.java:531)
      at org.apache.logging.log4j.core.net.DatagramOutputStream.flush(DatagramOutputStream.java:103)
      at org.apache.logging.log4j.core.appender.OutputStreamManager.flushDestination(OutputStreamManager.java:275)
      at org.apache.logging.log4j.core.appender.OutputStreamManager.write(OutputStreamManager.java:233)
      at org.apache.logging.log4j.core.appender.OutputStreamManager.write(OutputStreamManager.java:201)
      at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.writeByteArrayToManager(AbstractOutputStreamAppender.java:186)
      at org.apache.logging.log4j.core.appender.SocketAppender.directEncodeEvent(SocketAppender.java:451)
      at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170)
      at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender
```

If I run under the elasticsearch user this command, the message is being received.

`logger -d -n aaaaaaaa.local -p 514 testtest-udp`

elasticsearch-7.13.4-1.x86_64

**Comment by f1-outsourcing** [comment]
pfff, fix:

https://github.com/elastic/elasticsearch/issues/28996

any one knows how to log to /dev/log?

**Comment by f1-outsourcing** [comment]
> 
> 
> Pinging @elastic/es-core-infra (Team:Core/Infra)

horning @elastic/es-core-infra  ;)

**Comment by gwbrown** [comment]
Thanks for your interest in Elasticsearch!

We discussed this today and our decision not to support this due to our need to keep the `connect` permission out of core stands.

You may be able to use Logstash with the [Syslog output plugin](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-syslog.html) to get your logs where you need them, or depending on your system, you may be able to accomplish this with the [File](https://www.elastic.co/guide/en/beats/filebeat/current/file-output.html) or [Console](https://www.elastic.co/guide/en/beats/filebeat/current/console-output.html) Filebeat outputs.

There's also an active community in the [forums](https://discuss.elastic.co/) that may be able to help you find a workaround.

However, given that we don't intend to implement this, I'm going to close this issue.
