### ISSUE TITLE
[CI] PyTorchModelIT testEvaluate failing on Aarch64 

### ISSUE THREAD

**Issue by valeriy42** [elastic/elasticsearch#75685]
**Build scan:**
https://gradle-enterprise.elastic.co/s/qcrlkzix3jwou/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.PyTorchModelIT/testEvaluate

**Reproduction line:**
`./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testEvaluate" -Dtests.seed=50F9E76C891B57C8 -Dtests.locale=es-HN -Dtests.timezone=America/Argentina/Salta -Druntime.java=16`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.PyTorchModelIT&tests.test=testEvaluate

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:34333], URI [/_ml/trained_models/simple_model_to_evaluate/deployment/_start?timeout=40s], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"exception","reason":"Deployment failed with reason: [simple_model_to_evaluate] loading the model failed with error [org.elasticsearch.ElasticsearchException: Failed to connect to pytorch process for job simple_model_to_evaluate]"}],"type":"exception","reason":"Deployment failed with reason: [simple_model_to_evaluate] loading the model failed with error [org.elasticsearch.ElasticsearchException: Failed to connect to pytorch process for job simple_model_to_evaluate]"},"status":500}

  at __randomizedtesting.SeedInfo.seed([50F9E76C891B57C8:7A54B8B055544793]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:330)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
  at org.elasticsearch.xpack.ml.integration.PyTorchModelIT.startDeployment(PyTorchModelIT.java:178)
  at org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testEvaluate(PyTorchModelIT.java:92)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:567)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:831)

```

**Comment by valeriy42** [comment]
Failure also occurred in https://gradle-enterprise.elastic.co/s/lhef3ru6uqvjk today.

May be related to #73769.

**Comment by benwtrent** [comment]
Node logs aren't much help :/
```
[2021-07-26T11:28:25,502][INFO ][o.e.c.s.ClusterApplierService] [javaRestTest-1] removed {{external_9}{c0havf__T_-4HuAiAAAAAA}{DR95_dX3ReuQyeGMr9Cc4Q}{127.0.0.1}{127.0.0.1:22101}}, term: 1, version: 1961, reason: ApplyCommitRequest{term=1, version=1961, sourceNode={javaRestTest-0}{TqDx6QI7Ti2jdiyHpb4uag}{dR14VKxSQNyKcSFbVc5j3Q}{127.0.0.1}{127.0.0.1:36591}{dim}{testattr=test, xpack.installed=true}}
[2021-07-26T11:28:36,083][ERROR][o.e.x.m.i.p.p.NativePyTorchProcessFactory] [javaRestTest-1] Failed to connect to pytorch process for job simple_model_to_evaluate
[2021-07-26T11:28:36,084][ERROR][o.e.x.m.i.d.DeploymentManager] [javaRestTest-1] [simple_model_to_evaluate] failed with reason [[simple_model_to_evaluate] loading the model failed with error [org.elasticsearch.ElasticsearchException: Failed to connect to pytorch process for job simple_model_to_evaluate]]
[2021-07-26T11:28:36,107][INFO ][o.e.x.m.i.d.DeploymentManager] [javaRestTest-1] [simple_model_to_evaluate] Stopping deployment
```

```
[2021-07-26T11:28:36,114][WARN ][r.suppressed             ] [javaRestTest-0] path: /_ml/trained_models/simple_model_to_evaluate/deployment/_start, params: {model_id=simple_model_to_evaluate, timeout=40s}
org.elasticsearch.ElasticsearchException: Deployment failed with reason: [simple_model_to_evaluate] loading the model failed with error [org.elasticsearch.ElasticsearchException: Failed to connect to pytorch process for job simple_model_to_evaluate]
	at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.serverError(ExceptionsHelper.java:61) ~[?:?]
	at org.elasticsearch.xpack.ml.action.TransportStartTrainedModelDeploymentAction$DeploymentStartedPredicate.test(TransportStartTrainedModelDeploymentAction.java:279) ~[?:?]
	at org.elasticsearch.xpack.ml.action.TransportStartTrainedModelDeploymentAction$DeploymentStartedPredicate.test(TransportStartTrainedModelDeploymentAction.java:240) ~[?:?]
	at org.elasticsearch.persistent.PersistentTasksService.lambda$waitForPersistentTaskCondition$1(PersistentTasksService.java:180) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.clusterChanged(ClusterStateObserver.java:180) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListener(ClusterApplierService.java:510) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:501) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:468) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:408) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:152) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:259) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:222) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by davidkyle** [comment]
Both failures are on Aarch64 so I expect that is the way to investigate.

**Comment by davidkyle** [comment]
I've muted the test for Aarch64 only in #75690

**Comment by davidkyle** [comment]
A failure on a FIPS JVM

https://gradle-enterprise.elastic.co/s/uvhmo7jwi5c3g

The error was a timeout in the inference call, the logs show the expected behaviour, possibly this was just a timeout but the model being tested is very small and the timeout period is 10s. 
```
[2021-07-27T07:04:05,337][INFO ][o.e.x.m.i.d.DeploymentManager] [javaRestTest-1] [simple_model_to_evaluate] trained model loaded
[2021-07-27T07:04:05,370][WARN ][o.e.x.m.i.p.p.PyTorchResultProcessor] [javaRestTest-1] [simple_model_to_evaluate] no pending result for [1]
[2021-07-27T07:04:15,423][INFO ][o.e.x.m.i.d.DeploymentManager] [javaRestTest-1] [simple_model_to_evaluate] Stopping deployment
[2021-07-27T07:04:15,466][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [javaRestTest-1] [controller/379067] [CDetachedProcessSpawner.cc@176] Child process with PID 418914 was terminated by signal 15
```

**Comment by benwtrent** [comment]
> no pending result for [1]

That happened before the 10 second timeout. I am wondering if my PR (https://github.com/elastic/elasticsearch/pull/75679) would address this as the pending result is created and stored before the listener attempts to wait on the latch.

**Comment by droberts195** [comment]
The only error message in the server-side log for the original failure (not the FIPS one) is:

```
[2021-07-26T11:28:05,625][WARN ][o.e.x.m.p.l.CppLogMessageHandler] [javaRestTest-1] [controller/575753] [CDetachedProcessSpawner.cc@192] Child process with PID 589373 has exited with exit code 127
```

This suggests the underlying reasons are completely different.

There are no messages from the `pytorch_inference` process itself, so it exited before it connected its log stream.

Exit code 127 usually means a file required to load a program was not found.  The problem may be that a file is missing from our distribution on linux-aarch64.

**Comment by droberts195** [comment]
Interestingly, even though this test failed on both distributions we test on on ARM, the exit code 127 was only seen on CentOS 8.  On the Ubuntu 18.04 ARM build the problem was just a timeout, like in the FIPS build.

This suggests that what is actually missing from CentOS 8 is an OS file that libtorch has linked to when we built it on CentOS 7.

**Comment by droberts195** [comment]
> Interestingly, even though this test failed on both distributions we test on on ARM, the exit code 127 was only seen on CentOS 8. On the Ubuntu 18.04 ARM build the problem was just a timeout, like in the FIPS build.

Hmm, not sure why it didn't give an exit code 127 on Ubuntu 18.04, as the problem is pretty fundamental:

```
[ec2-user@ip-172-30-2-201 bin]$ ./pytorch_inference --version
./pytorch_inference: error while loading shared libraries: libtorch_cpu.so: cannot open shared object file: No such file or directory
[ec2-user@ip-172-30-2-201 bin]$ ls -l ../lib
total 28116
-rw-r--r--. 1 ec2-user ec2-user    5920 Jul 27 09:02 libboost_atomic-gcc9-mt-a64-1_71.so.1.71.0
-rw-r--r--. 1 ec2-user ec2-user   47120 Jul 27 09:02 libboost_chrono-gcc9-mt-a64-1_71.so.1.71.0
-rw-r--r--. 1 ec2-user ec2-user   71696 Jul 27 09:02 libboost_date_time-gcc9-mt-a64-1_71.so.1.71.0
-rw-r--r--. 1 ec2-user ec2-user  108576 Jul 27 09:02 libboost_filesystem-gcc9-mt-a64-1_71.so.1.71.0
-rw-r--r--. 1 ec2-user ec2-user  100376 Jul 27 09:02 libboost_iostreams-gcc9-mt-a64-1_71.so.1.71.0
-rw-r--r--. 1 ec2-user ec2-user  829640 Jul 27 09:02 libboost_log-gcc9-mt-a64-1_71.so.1.71.0
-rw-r--r--. 1 ec2-user ec2-user  698408 Jul 27 09:02 libboost_log_setup-gcc9-mt-a64-1_71.so.1.71.0
-rw-r--r--. 1 ec2-user ec2-user  550952 Jul 27 09:02 libboost_program_options-gcc9-mt-a64-1_71.so.1.71.0
-rw-r--r--. 1 ec2-user ec2-user  810840 Jul 27 09:02 libboost_regex-gcc9-mt-a64-1_71.so.1.71.0
-rw-r--r--. 1 ec2-user ec2-user    5920 Jul 27 09:02 libboost_system-gcc9-mt-a64-1_71.so.1.71.0
-rw-r--r--. 1 ec2-user ec2-user  174120 Jul 27 09:02 libboost_thread-gcc9-mt-a64-1_71.so.1.71.0
-rw-r--r--. 1 ec2-user ec2-user  132952 Jul 27 09:02 libgcc_s.so.1
-rw-r--r--. 1 ec2-user ec2-user  413078 Jul 27 09:02 libgomp.a
-rw-r--r--. 1 ec2-user ec2-user     956 Jul 27 09:02 libgomp.la
-rw-r--r--. 1 ec2-user ec2-user  264784 Jul 27 09:02 libgomp.so
-rw-r--r--. 1 ec2-user ec2-user  264784 Jul 27 09:02 libgomp.so.1
-rw-r--r--. 1 ec2-user ec2-user  264792 Jul 27 09:02 libgomp.so.1.0.0
-rw-r--r--. 1 ec2-user ec2-user     169 Jul 27 09:02 libgomp.spec
-rw-r--r--. 1 ec2-user ec2-user 2279432 Jul 27 09:02 libMlApi.so
-rw-r--r--. 1 ec2-user ec2-user 2181280 Jul 27 09:02 libMlCore.so
-rw-r--r--. 1 ec2-user ec2-user 9427608 Jul 27 09:02 libMlMaths.so
-rw-r--r--. 1 ec2-user ec2-user 5801984 Jul 27 09:02 libMlModel.so
-rw-r--r--. 1 ec2-user ec2-user 2568496 Jul 27 09:02 libstdc++.so.6
-rw-r--r--. 1 ec2-user ec2-user 1737584 Jul 27 09:02 libxml2.so.2
```
