### ISSUE TITLE
[CI] TransformIT testStopWaitForCheckpoint failing

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#75846]
**Build scan:**
https://gradle-enterprise.elastic.co/s/q6kyadnnxpljg/tests/:x-pack:plugin:transform:qa:multi-node-tests:javaRestTest/org.elasticsearch.xpack.transform.integration.TransformIT/testStopWaitForCheckpoint

**Reproduction line:**
`./gradlew ':x-pack:plugin:transform:qa:multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.transform.integration.TransformIT.testStopWaitForCheckpoint" -Dtests.seed=545D076A9340F142 -Dtests.locale=id -Dtests.timezone=Australia/Victoria -Druntime.java=8`

**Applicable branches:**
7.13, 7.x

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.transform.integration.TransformIT&tests.test=testStopWaitForCheckpoint

**Failure excerpt:**
```
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=status_exception, reason=Failed to update transform task [transform-wait-for-checkpoint] state value should_stop_at_checkpoint from [true] to [true]]

  at __randomizedtesting.SeedInfo.seed([545D076A9340F142:29882B015FD41B74]:0)
  at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:176)
  at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1933)
  at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1910)
  at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1667)
  at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1639)
  at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1606)
  at org.elasticsearch.client.TransformClient.stopTransform(TransformClient.java:308)
  at org.elasticsearch.xpack.transform.integration.TransformIntegTestCase.stopTransform(TransformIntegTestCase.java:145)
  at org.elasticsearch.xpack.transform.integration.TransformIT.testStopWaitForCheckpoint(TransformIT.java:302)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by davidkyle** [comment]
Another failure on 7.x https://gradle-enterprise.elastic.co/s/uu22ctbeys7r6

**Comment by hendrikmuhs** [comment]
7.13: https://gradle-enterprise.elastic.co/s/llnuq6s3haxg2

**Comment by hendrikmuhs** [comment]
After analyzing the logs, it seems this is caused by quickly starting the transform after stopping it.

The transform is stopped, but the state hasn't been persisted yet:
```
[2021-08-02T05:07:00,272][DEBUG][o.e.x.c.i.AsyncTwoPhaseIndexer] [javaRestTest-2] Finished indexing for job [transform-wait-for-checkpoint], saving state and shutting down.
[2021-08-02T05:07:00,305][DEBUG][o.e.x.t.t.TransformIndexer] [javaRestTest-2] [transform-wait-for-checkpoint] finished indexing for transform checkpoint [4].
[2021-08-02T05:07:00,307][INFO ][o.e.x.t.t.TransformIndexer] [javaRestTest-2] [transform-wait-for-checkpoint] transform has stopped.
[2021-08-02T05:07:00,308][DEBUG][o.e.x.t.t.ClientTransformIndexer] [javaRestTest-2] [transform-wait-for-checkpoint] updating persistent state of transform to [{"task_state":"stopped","indexer_state":"stopped","checkpoint":4,"progress":{"docs_indexed":25,"docs_processed":25},"should_stop_at_checkpoint":false}].
```

Now the transform is started again, and it loads an old state document:

```
[2021-08-02T05:07:00,319][DEBUG][o.e.x.t.t.TransformPersistentTasksExecutor] [javaRestTest-2] [transform-wait-for-checkpoint] Loading existing state: [{"task_state":"stopped","indexer_state":"stopped","checkpoint":3,"should_stop_at_checkpoint":false}], position [null]
```

It loaded checkpoint 3, but it should be 4.

The indexer got initialized with _wrong_ state:
```
[2021-08-02T05:07:00,327][DEBUG][o.e.x.t.t.TransformTask  ] [javaRestTest-2] [transform-wait-for-checkpoint] start called with state [{"task_state":"stopped","indexer_state":"stopped","checkpoint":0,"should_stop_at_checkpoint":false}].
[2021-08-02T05:07:00,328][INFO ][o.e.x.t.t.TransformTask  ] [javaRestTest-2] [transform-wait-for-checkpoint] updating state for transform to [{"task_state":"started","indexer_state":"stopped","checkpoint":3,"should_stop_at_checkpoint":false}].
```

Now, finally the state with checkpoint 4 returned:

```
[2021-08-02T05:07:00,336][DEBUG][o.e.x.t.t.ClientTransformIndexer] [javaRestTest-2] [transform-wait-for-checkpoint] Updated state document from [{seqNo=10,primaryTerm=1,index=.transform-internal-007}] to [{seqNo=12,primaryTerm=1,index=.transform-internal-007}]
```

however, that's the old indexer, the new one has the old state and therefore stumbles upon saving:

```
[2021-08-02T05:07:00,443][ERROR][o.e.x.t.t.ClientTransformIndexer] [javaRestTest-2] [transform-wait-for-checkpoint] updating stats of transform failed.
java.lang.RuntimeException: Failed to persist transform statistics for transform [transform-wait-for-checkpoint]
	at org.elasticsearch.xpack.transform.persistence.IndexBasedTransformConfigManager.lambda$putOrUpdateTransformStoredDoc$14(IndexBasedTransformConfigManager.java:530) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:142) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:38) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:92) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:38) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.action.ActionListener$Delegating.onFailure(ActionListener.java:66) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.action.bulk.TransportSingleItemBulkWriteAction.lambda$wrapBulkResponse$0(TransportSingleItemBulkWriteAction.java:53) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:31) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$2(SecurityActionFilter.java:163) ~[?:?]
	at org.elasticsearch.action.ActionListener$DelegatingFailureActionListener.onResponse(ActionListener.java:217) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.action.ActionListener$RunBeforeActionListener.onResponse(ActionListener.java:387) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.action.bulk.TransportBulkAction$BulkOperation$1.finishHim(TransportBulkAction.java:538) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.action.bulk.TransportBulkAction$BulkOperation$1.onResponse(TransportBulkAction.java:519) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.action.bulk.TransportBulkAction$BulkOperation$1.onResponse(TransportBulkAction.java:508) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:83) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:77) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:31) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$2(SecurityActionFilter.java:163) ~[?:?]
	at org.elasticsearch.action.ActionListener$DelegatingFailureActionListener.onResponse(ActionListener.java:217) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.finishOnSuccess(TransportReplicationAction.java:877) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$1.handleResponse(TransportReplicationAction.java:796) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$1.handleResponse(TransportReplicationAction.java:787) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.transport.TransportService$5.handleResponse(TransportService.java:732) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1273) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.transport.InboundHandler.doHandleResponse(InboundHandler.java:291) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:275) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:128) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:84) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:693) ~[elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:129) [elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:104) [elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:69) [elasticsearch-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:63) [transport-netty4-client-7.13.5-SNAPSHOT.jar:7.13.5-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271) [netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1518) [netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1267) [netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1314) [netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_301]
Caused by: org.elasticsearch.index.engine.VersionConflictEngineException: [data_frame_transform_state_and_stats-transform-wait-for-checkpoint]: version conflict, required seqNo [10], primary term [1]. current document has seqNo [12] and primary term [1]
```

Summary: It is possible to start a transform, although the state hasn't been saved yet / the former `stop` hasn't been finished.

**Comment by hendrikmuhs** [comment]
Copied over from #76034:

The deadlock found:

| Thread 1 (transport of stop)                   | Thread 2 (task/scheduler)                        |
|------------------------------------------------|--------------------------------------------------|
| **(s)** task->stop_at_checkpoint               |                                                  |
|                                                | **(s)** task->triggered() (**lock A**)           |
| **(s)** indexer->save_state (**lock B**)       |                                                  |
|                                                | **(s)** indexer->triggered (**wait for lock B**) |
| **(s)** task->shutdown() (**wait for lock A**) |                                                  |
|                                                |                                                  |
| _timeout_ (**unlock B**)                       |                                                  |
|                                                | **(s)** indexer->triggered (**lock B**)          |


The problem are 2 locks of the task and the indexer that can lock one another. 

Interesting is the `task->stop_at_checkpoint` which is `synchronized` but as it moves the execution of
the thread:

```
        // move the call to the generic thread pool, so we do not block the network thread
        getThreadPool().executor(ThreadPool.Names.GENERIC)
            .execute(() -> { getIndexer().setStopAtCheckpoint(shouldStopAtCheckpoint, shouldStopAtCheckpointListener); });
```

it unlocks the _task_ (lock A) and therefore allows the trigger originating from the scheduler to acquire lock A.

**Summary**

The task and indexer have their own synchronization. These work independent and it is not necessary to introduce a global lock. However, if an operation requires to lock both, it is important to not mix the order. Most operations lock the task and the indexer, in this order. It is important not to introduce code that locks the indexer 1st and potentially the task later, e.g. on fail or shutdown.
