### ISSUE TITLE
[CI] InternalDistributionBwcSetupPluginFuncTest builds distribution from branches via archives assemble failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#75992]
This looks to be specific to ARM so I'm assuming something with our logic related to what versions exist with ARM capability. It's only failing on the 7.13 branch though which is going to be dropped in a couple day so it might not be worth even bothing to investigate.

**Build scan:**
https://gradle-enterprise.elastic.co/s/65566mdwsx626/tests/:build-tools:integTest/org.elasticsearch.gradle.internal.InternalDistributionBwcSetupPluginFuncTest/builds%20distribution%20from%20branches%20via%20archives%20assemble

**Reproduction line:**
`null`

**Applicable branches:**
7.13

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.gradle.internal.InternalDistributionBwcSetupPluginFuncTest&tests.test=builds%20distribution%20from%20branches%20via%20archives%20assemble

**Failure excerpt:**
```
org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in /tmp/junit4721040987505022776/cloned with arguments [:distribution:bwc:bugfix:buildBwcDarwinTar, :distribution:bwc:bugfix:buildBwcOssDarwinTar, -DtestRemoteRepo=/tmp/junit2176668399040020219/remote/.git, -Dbwc.remote=origin, -Dbwc.dist.version=7.10.1-SNAPSHOT]

Output:
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:processResources
> Task :buildSrc:classes
> Task :buildSrc:jar
> Task :buildSrc:assemble
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build

FAILURE: Build failed with an exception.

* What went wrong:
Task 'buildBwcDarwinTar' not found in project ':distribution:bwc:bugfix'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 773ms

  at org.gradle.testkit.runner.internal.DefaultGradleRunner.lambda$build$2(DefaultGradleRunner.java:264)
  at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:338)
  at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:262)
  at org.elasticsearch.gradle.internal.InternalDistributionBwcSetupPluginFuncTest.builds distribution from branches via archives #expectedAssembleTaskName(InternalDistributionBwcSetupPluginFuncTest.groovy:31)

```

**Comment by mark-vieira** [comment]
This is no longer failing on any active development branches so I'm closing.
