### ISSUE TITLE
[CI] DatafeedJobsIT testStopAndRestartCompositeDatafeed failing

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#76075]
The assertion is that the event counts for the scroll buckets and composite buckets are the same, but the more fundamental problem that the extra debug information shows up is that the _timestamp_ of the mismatched bucket is different - we're not comparing like with like for some reason.

**Build scan:**
https://gradle-enterprise.elastic.co/s/63sdskgd2dbki/tests/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/org.elasticsearch.xpack.ml.integration.DatafeedJobsIT/testStopAndRestartCompositeDatafeed

**Reproduction line:**
`./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.DatafeedJobsIT.testStopAndRestartCompositeDatafeed" -Dtests.seed=BCBE2D3EFDF6C14B -Dtests.locale=en-ZA -Dtests.timezone=Pacific/Samoa -Druntime.java=11 -Dtests.fips.enabled=true`

**Applicable branches:**
7.x, 7.15, master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.DatafeedJobsIT&tests.test=testStopAndRestartCompositeDatafeed

**Failure excerpt:**
```
java.lang.AssertionError: Hits: {
  "_index" : "stop-restart-data",
  "_type" : "type",
  "_id" : "BSwfDXsBsYrSD3fRB57C",
  "_score" : 1.0,
  "_source" : {
    "time" : 1626804286772,
    "@timestamp" : 1626804286772
  }
}
{
  "_index" : "stop-restart-data",
  "_type" : "type",
  "_id" : "XiwfDXsBsYrSD3fRB57C",
  "_score" : 1.0,
  "_source" : {
    "time" : 1626804000445,
    "@timestamp" : 1626804000445
  }
}
{
  "_index" : "stop-restart-data",
  "_type" : "type",
  "_id" : "5SwfDXsBsYrSD3fRB57C",
  "_score" : 1.0,
  "_source" : {
    "time" : 1626805874948,
    "@timestamp" : 1626805874948
  }
}
{
  "_index" : "stop-restart-data",
  "_type" : "type",
  "_id" : "VCwfDXsBsYrSD3fRB5_C",
  "_score" : 1.0,
  "_source" : {
    "time" : 1626806183402,
    "@timestamp" : 1626806183402
  }
}
{
  "_index" : "stop-restart-data",
  "_type" : "type",
  "_id" : "ViwfDXsBsYrSD3fRB5_C",
  "_score" : 1.0,
  "_source" : {
    "time" : 1626805948657,
    "@timestamp" : 1626805948657
  }
} 
 failure: composite bucket [Tue Jul 20 08:00:00 SST 2021] [2] does not equal scroll bucket [Tue Jul 20 07:00:00 SST 2021] [5]
Expected: <5L>
     but: was <2L>

  at __randomizedtesting.SeedInfo.seed([BCBE2D3EFDF6C14B:D200B6AEC903AC84]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.elasticsearch.xpack.ml.integration.DatafeedJobsIT.testStopAndRestartCompositeDatafeed(DatafeedJobsIT.java:470)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by dimitris-athanasiou** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/tydalvy6gvkx2

**Comment by benwtrent** [comment]
Digging into the logs:

```
[2021-09-07T10:47:27,247][INFO ][o.e.x.m.j.p.a.o.AutodetectResultProcessor] [javaRestTest-2] [stop-restart-composite] 334 buckets parsed from autodetect output
```
vs
```
[2021-09-07T10:47:23,777][INFO ][o.e.x.m.j.p.a.o.AutodetectResultProcessor] [javaRestTest-1] [stop-restart-scroll] 336 buckets parsed from autodetect output
```

Scroll has two more buckets than composite. Obviously, given the failure has the scroll bucket timestamp in the past, one of these "missing" buckets is at the start of the data. 

I am making a wild guess and thinking the other is at the end.

Still investigating.

**Comment by benwtrent** [comment]
Failed again recently: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+platform-support-unix/os=ubuntu-20.04&&immutable/287/consoleFull


Here are the logs
[testclusters.zip](https://github.com/elastic/elasticsearch/files/7236295/testclusters.zip)

This is frustrating, the failure indicates

```
Expected: <Mon Sep 13 04:00:00 CEST 2021>
          but: was <Mon Sep 13 05:00:00 CEST 2021>
```

So, the scroll had this bucket but the composite agg did not. 

But, looking at the logs:
```
[2021-09-27T01:44:10,172][TRACE][o.e.x.m.d.DatafeedJob    ] [javaRestTest-1] [stop-restart-composite] Processed another 1 records with latest timestamp [2021-09-13T02:43:59.100+0000]
```
The composite datafeed processed a record at that time stamp :(. 

Digging further.
