### ISSUE TITLE
[CI] SSLErrorMessageFileTests testMessageForPemKeyOutsideConfigDir failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#76166]
This is most likely a Windows related issue. It looks like the expected error message doesn't match what we get on a windows machine. Probably test checks need to be relaxed.

**Build scan:**
https://gradle-enterprise.elastic.co/s/5ijwj7srtbbzc/tests/:x-pack:plugin:security:test/org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests/testMessageForPemKeyOutsideConfigDir

**Reproduction line:**
`gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests.testMessageForPemKeyOutsideConfigDir" -Dtests.seed=EDB094E25CB6F885 -Dtests.locale=es-PA -Dtests.timezone=America/Resolute -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests&tests.test=testMessageForPemKeyOutsideConfigDir

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: a throwable with message of "cannot read configured PEM private key [\\this\\path\\is\\outside\\the\\config\\directory\\file.error] because access to read the file is blocked; SSL resources should be placed in the Elasticsearch config directory"
     but: was <org.elasticsearch.common.ssl.SslConfigException: cannot read configured PEM private key [C:\this\path\is\outside\the\config\directory\file.error] because access to read the file is blocked; SSL resources should be placed in the Elasticsearch config directory> at org.elasticsearch.common.ssl.SslFileUtil.accessControlFailure(SslFileUtil.java:96)

  at __randomizedtesting.SeedInfo.seed([EDB094E25CB6F885:9EB3967CD036087A]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests.checkBlockedResource(SSLErrorMessageFileTests.java:322)
  at org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests.checkBlockedKeyManagerResource(SSLErrorMessageFileTests.java:221)
  at org.elasticsearch.xpack.ssl.SSLErrorMessageFileTests.testMessageForPemKeyOutsideConfigDir(SSLErrorMessageFileTests.java:122)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by cbuescher** [comment]
Most likely related to b371463ac2b9709cd4c83e644db0665ba08ef25e

**Comment by dimitris-athanasiou** [comment]
Same failure here: https://gradle-enterprise.elastic.co/s/p2cjowaxbmdqu. I'll mute the test.
