### ISSUE TITLE
[CI] RetryableActionTests testRetryableActionTimeout failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#76165]
**Build scan:**
https://gradle-enterprise.elastic.co/s/bnq7vzq6jsmda/tests/:server:test/org.elasticsearch.action.support.RetryableActionTests/testRetryableActionTimeout

**Reproduction line:**
`gradlew ':server:test' --tests "org.elasticsearch.action.support.RetryableActionTests.testRetryableActionTimeout" -Dtests.seed=30262AAAB4F0DFBB -Dtests.locale=he-IL -Dtests.timezone=Etc/UCT -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.action.support.RetryableActionTests&tests.test=testRetryableActionTimeout

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: a value less than or equal to <3000L>
     but: <3761L> was greater than <3000L>

  at __randomizedtesting.SeedInfo.seed([30262AAAB4F0DFBB:6871BFE7697906F5]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.action.support.RetryableActionTests.testRetryableActionTimeout(RetryableActionTests.java:140)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by pugnascotia** [comment]
I've muted the test on `master`, `7.x` and `7.14`.

**Comment by stu-elastic** [comment]
Stepping through this, in [`RetryableActionTests.testRetryableActionTimeout`](https://github.com/elastic/elasticsearch/blob/master/server/src/test/java/org/elasticsearch/action/support/RetryableActionTests.java#L63), the random time is `1498`.

It is retried twice, on [`RetryableAction.onFailure`](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/action/support/RetryableAction.java#L148), the important values are:

```
final long nextDelayMillisBound = calculateDelayBound(delayMillisBound);                  // 1498
int range = Math.toIntExact((delayMillisBound + 1) / 2);                                  //  749
                                          // 121
final long delayMillis = Randomness.get().nextInt(range) + delayMillisBound - range + 1L; //  871


final long nextDelayMillisBound = calculateDelayBound(delayMillisBound);                  // 5992
int range = Math.toIntExact((delayMillisBound + 1) / 2);                                  // 1498
                                          // 1391
final long delayMillis = Randomness.get().nextInt(range) + delayMillisBound - range + 1L; // 2890
```

So the two delays calculated are: `2890` and `871` which adds up to the `3761` of the failure.
