### ISSUE TITLE
[CI] PersistentTasksClusterServiceTests testReassignOnlyOnce failing

### ISSUE THREAD

**Issue by pugnascotia** [elastic/elasticsearch#76337]
Test fails periodically - https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/London&tests.container=org.elasticsearch.persistent.PersistentTasksClusterServiceTests&tests.sortField=FAILED&tests.test=testReassignOnlyOnce&tests.unstableOnly=true

**Build scan:**
https://gradle-enterprise.elastic.co/s/oplmfm45lwzws/tests/:server:test/org.elasticsearch.persistent.PersistentTasksClusterServiceTests/testReassignOnlyOnce

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.persistent.PersistentTasksClusterServiceTests.testReassignOnlyOnce" -Dtests.seed=30AD981ED9A4583E -Dtests.locale=ar-QA -Dtests.timezone=Antarctica/Vostok -Druntime.java=16 -Dtests.fips.enabled=true`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.persistent.PersistentTasksClusterServiceTests&tests.test=testReassignOnlyOnce

**Failure excerpt:**
```
org.mockito.exceptions.verification.TooManyActualInvocations: 
clusterService.submitStateUpdateTask(
    "reassign persistent tasks",
    <any>
);
Wanted 2 times:
-> at org.elasticsearch.persistent.PersistentTasksClusterServiceTests.lambda$testReassignOnlyOnce$15(PersistentTasksClusterServiceTests.java:686)
But was 3 times. Undesired invocation:
-> at org.elasticsearch.persistent.PersistentTasksClusterService.reassignPersistentTasks(PersistentTasksClusterService.java:362)

  at __randomizedtesting.SeedInfo.seed([30AD981ED9A4583E:4297546793FE2066]:0)
  at org.elasticsearch.persistent.PersistentTasksClusterServiceTests.lambda$testReassignOnlyOnce$15(PersistentTasksClusterServiceTests.java:686)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:977)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:950)
  at org.elasticsearch.persistent.PersistentTasksClusterServiceTests.testReassignOnlyOnce(PersistentTasksClusterServiceTests.java:686)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:567)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:831)

```

**Comment by arteam** [comment]
@pugnascotia I think It should be fixed by https://github.com/elastic/elasticsearch/pull/76318, shall I merge it?
