### ISSUE TITLE
[Transform] Improve readability of error due to non-aggregatable field in group_by

### ISSUE THREAD

**Issue by sophiec20** [elastic/elasticsearch#76429]
**Elasticsearch version** (`bin/elasticsearch --version`):
Found in `"8.0.0-SNAPSHOT",
    "build_date" : "2021-08-06T14:32:37.737198474Z",`
Same behavior expected in 7.x

**Description of the problem including expected versus actual behavior**:

Created a continuous transform which grouped by `@timestamp` and `source.ip`.
This was targeted against a wide set of source indexes `logs-*,filebeat-*,packetbeat-*,auditbeat-*`.
One index contained an erroneous `source.ip` field which was mapped as text, rather than as ip.
The transform was successfully previewed, created and started, but failed soon after.
The stack trace was included in the failure reason and also as a job message.

**Workaround**
Find the index(es) where the field is not aggregatable.
`GET logs-*,filebeat-*,packetbeat-*,auditbeat-*/_field_caps?fields=source.ip`

Either delete the erroneous index (in this case, it wasn't needed), or add a runtime field to convert type to ip.

**Usability**
There was enough information in the stack trace to resolve the error, however there is room for improvement. 

The `Partial shards failure` was slightly misleading. Whilst technically correct, you had to read on to find that source.ip was not aggregatable. Can this error be made more human readable? for both failure reason and job message?

Could this have been picked up earlier during validation? 

**Error**
From `transform/_stats

```
      "id" : "my-transform",
      "state" : "failed",
      "reason" : """task encountered irrecoverable failure: Failed to execute phase [query], Partial shards failure; shardFailures {[R1Dz9wQNTje_UPfo018M3A][packetbeat-qa][0]: org.elasticsearch.transport.RemoteTransportException: [node1][127.0.0.1:9351][indices:data/read/search[phase/query]]
Caused by: java.lang.IllegalArgumentException: Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [source.ip] in order to load field data by uninverting the inverted index. Note that this can use significant memory.
	at org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType.fielddataBuilder(TextFieldMapper.java:809)
	at org.elasticsearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:109)
	at org.elasticsearch.index.query.SearchExecutionContext.getForField(SearchExecutionContext.java:275)
	at org.elasticsearch.search.aggregations.support.AggregationContext$ProductionAggregationContext.buildFieldData(AggregationContext.java:355)
	at org.elasticsearch.search.aggregations.support.AggregationContext.buildFieldContext(AggregationContext.java:95)
	at org.elasticsearch.search.aggregations.support.ValuesSourceConfig.internalResolve(ValuesSourceConfig.java:123)
	at org.elasticsearch.search.aggregations.support.ValuesSourceConfig.resolve(ValuesSourceConfig.java:55)
	at org.elasticsearch.search.aggregations.bucket.composite.CompositeValuesSourceBuilder.build(CompositeValuesSourceBuilder.java:266)
	at org.elasticsearch.search.aggregations.bucket.composite.CompositeAggregationBuilder.doBuild(CompositeAggregationBuilder.java:206)
	at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:128)
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:345)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:1009)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:770)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:448)
	at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$2(SearchService.java:424)
	at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47)
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:737)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.lang.Thread.run(Thread.java:831)
}; org.elasticsearch.ElasticsearchException$1: Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [source.ip] in order to load field data by uninverting the inverted index. Note that this can use significant memory.; java.lang.IllegalArgumentException: Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [source.ip] in order to load field data by uninverting the inverted index. Note that this can use significant memory.""",
```

**Comment by droberts195** [comment]
After #27906 it became "best practice" to disallow partial failures on searches.  This is where the outer "Partial shards failure" exception comes from.

I am thinking that for "unattended" transforms and datafeeds we should allow a certain level of partial failures, but record them somewhere.

We used to have our own code that looked for partial failures - it was what was deleted in #55537 to be replaced with simply `allow_partial_search_results=false`.  Historically our code for working through the partial failures in detail converted them all to fatal errors, so switching to `allow_partial_search_results=false` did simplify the code compared to what we had at the time.  It seems that in the future we might want to reinstate our own logic for handling partial failures, so that we can choose to soldier on in the case of some of them for unattended transforms/datafeeds, and just record them rather than stop.

**Comment by hendrikmuhs** [comment]
I think this is an enhancement, not a bug.

In transforms field caps are retrieved not only for validation but also for runtime to correctly map the result set from search to index requests. I suggest to spin off a sub-task to improve validation (check for _aggregatable_). Because source indexes can change, especially if wildcards are involved, we need to think about runtime in addition to creation. A new index that matches the pattern could be added later. Therefore it is not sufficient to only look at preview and/or creation.

I think checking field caps, resolving indexes and excluding indexes that are incompatible is a (IMO better) alternative to special handling of partial search results which is super tricky and fragile. We still don't want data loss due to temporary node failures. There is a thin line between error silencing and never stop running.

A field caps check together with an index resolver could create a message like:

```
Excluded [packetbeat-qa], field source.ip is incompatible to the given configuration. Please check....
```

Overall I see 2 scenarios:
 - the user wants to add that index and did not know about the incompatibility
 - the wildcard matches an index that it should not due to a name clash or a wildcard that is not specific enough

The 1st is better validation and 99% of the time something we can and should handle at preview/creation time.

The later covers runtime and is more likely to be seen for _unattended_ transforms.
