### ISSUE TITLE
[CI] RestSqlCancellationIT testRestCancellation failures

### ISSUE THREAD

**Issue by csoulios** [elastic/elasticsearch#76420]
Test `RestSqlCancellationIT.testRestCancellation()` fails in v7.14

**Build scan**: 
https://gradle-enterprise.elastic.co/s/ahl6g3rdeg2f2/
https://gradle-enterprise.elastic.co/s/lvdqaeku6vnum/

**Repro line**:

```
./gradlew ':x-pack:plugin:sql:internalClusterTest' --tests "org.elasticsearch.xpack.sql.action.RestSqlCancellationIT.testRestCancellation" -Dtests.seed=FDC09CD819083A93 -Dtests.locale=fr -Dtests.timezone=Asia/Qyzylorda -Druntime.java=16
```

```
 ./gradlew ':x-pack:plugin:eql:internalClusterTest' --tests "org.elasticsearch.xpack.eql.action.RestEqlCancellationIT.testRestCancellation" -Dtests.seed=8CC1172053171715 -Dtests.locale=vi-VN -Dtests.timezone=America/Regina -Druntime.java=8
```

**Reproduces locally?**: No

**Applicable branches**: 7.14

**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2021-01-31T22:00:00.000Z',mode:absolute,to:'2021-08-13T20:59:59.999Z'))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.xpack.sql.action.RestSqlCancellationIT%22'),sort:!(time,desc))

**Failure excerpt**:

```
:x-pack:plugin:eql:internalClusterTest FAILED
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF8


org.elasticsearch.xpack.eql.action.RestEqlCancellationIT > testRestCancellation FAILED
    java.lang.AssertionError: 
    Expected: null
         but: was <{
      "node" : "60Z7Y8sHQAqbzVhv1zZzaw",
      "id" : 111,
      "type" : "transport",
      "action" : "indices:data/read/eql",
      "start_time" : "2021-08-12T00:07:31.150Z",
      "start_time_in_millis" : 1628726851150,
      "running_time" : "20.8s",
      "running_time_in_nanos" : 20827834583,
      "cancellable" : true,
      "cancelled" : true,
      "headers" : {
        "X-Opaque-Id" : "GHkjDHRlOp"
      }
    }>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.eql.action.RestEqlCancellationIT.lambda$testRestCancellation$1(RestEqlCancellationIT.java:141)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1035)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1008)
        at org.elasticsearch.xpack.eql.action.RestEqlCancellationIT.testRestCancellation(RestEqlCancellationIT.java:140)

    java.lang.AssertionError: All incoming requests on node [node_s0] should have finished. Expected 0 but got 180; pending tasks [[{
      "node" : "node_s0",
      "id" : 116,
      "type" : "transport",
      "action" : "indices:data/read/search",
      "description" : "indices[test], types[], search_type[QUERY_THEN_FETCH], source[{\"size\":10,\"timeout\":\"30s\",\"query\":{\"bool\":{\"must\":[{\"term\":{\"event_type\":{\"value\":\"my_event\",\"boost\":1.0}}},{\"term\":{\"val\":{\"value\":1,\"boost\":1.0}}}],\"adjust_pure_negative\":true,\"boost\":1.0}},\"_source\":{\"includes\":[],\"excludes\":[]},\"sort\":[{\"@timestamp\":{\"order\":\"desc\",\"missing\":\"_last\",\"unmapped_type\":\"date\"}}],\"track_total_hits\":-1}]",
      "start_time" : "2021-08-12T00:07:41.801Z",
      "start_time_in_millis" : 1628726861801,
      "running_time" : "1.2m",
      "running_time_in_nanos" : 76127237007,
      "cancellable" : true,
      "cancelled" : true,
      "parent_task_id" : "60Z7Y8sHQAqbzVhv1zZzaw:111",
      "headers" : {
        "X-Opaque-Id" : "GHkjDHRlOp"
      }
    },{
      "node" : "node_s0",
      "id" : 117,
      "type" : "direct",
      "action" : "indices:data/read/search[phase/query]",
      "description" : "shardId[[test][0]]",
      "start_time" : "2021-08-12T00:07:41.839Z",
      "start_time_in_millis" : 1628726861839,
      "running_time" : "1.2m",
      "running_time_in_nanos" : 76088678626,
      "cancellable" : true,
      "cancelled" : true,
      "parent_task_id" : "60Z7Y8sHQAqbzVhv1zZzaw:116",
      "headers" : {
        "X-Opaque-Id" : "GHkjDHRlOp"
      }
    },{
      "node" : "node_s0",
      "id" : 111,
      "type" : "transport",
      "action" : "indices:data/read/eql",
      "description" : "indices[test], my_event where val==1",
      "start_time" : "2021-08-12T00:07:31.150Z",
      "start_time_in_millis" : 1628726851150,
      "running_time" : "1.4m",
      "running_time_in_nanos" : 86778701796,
      "cancellable" : true,
      "cancelled" : true,
      "headers" : {
        "X-Opaque-Id" : "GHkjDHRlOp"
      }
    }]]
        at org.elasticsearch.test.InternalTestCluster.lambda$assertRequestsFinished$43(InternalTestCluster.java:2613)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1035)
        at org.elasticsearch.test.InternalTestCluster.assertRequestsFinished(InternalTestCluster.java:2606)
        at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2581)
        at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:594)
        at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2263)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.lang.Thread.run(Thread.java:748)

    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=41, name=elasticsearch[node_s0][management][T#1], state=RUNNABLE, group=TGRP-RestEqlCancellationIT]

        Caused by:
        java.lang.AssertionError
            at __randomizedtesting.SeedInfo.seed([8CC1172053171715]:0)
            at org.junit.Assert.fail(Assert.java:86)
            at org.junit.Assert.assertTrue(Assert.java:41)
            at org.junit.Assert.assertFalse(Assert.java:64)
            at org.junit.Assert.assertFalse(Assert.java:74)
            at org.elasticsearch.xpack.eql.action.AbstractEqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$0(AbstractEqlBlockingIntegTestCase.java:203)
            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1035)
            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1008)
            at org.elasticsearch.xpack.eql.action.AbstractEqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$1(AbstractEqlBlockingIntegTestCase.java:203)
            at org.elasticsearch.xpack.eql.action.AbstractEqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$3(AbstractEqlBlockingIntegTestCase.java:220)
            at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
            at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47)
            at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
            at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:748)

    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=82, name=elasticsearch[node_s0][search][T#1], state=RUNNABLE, group=TGRP-RestEqlCancellationIT]

        Caused by:
        java.lang.AssertionError
            at __randomizedtesting.SeedInfo.seed([8CC1172053171715]:0)
            at org.junit.Assert.fail(Assert.java:86)
            at org.junit.Assert.assertTrue(Assert.java:41)
            at org.junit.Assert.assertFalse(Assert.java:64)
            at org.junit.Assert.assertFalse(Assert.java:74)
            at org.elasticsearch.xpack.eql.action.AbstractEqlBlockingIntegTestCase$SearchBlockPlugin$1.lambda$onNewReaderContext$0(AbstractEqlBlockingIntegTestCase.java:172)
            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1035)
            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1008)
            at org.elasticsearch.xpack.eql.action.AbstractEqlBlockingIntegTestCase$SearchBlockPlugin$1.onNewReaderContext(AbstractEqlBlockingIntegTestCase.java:172)
            at org.elasticsearch.index.shard.SearchOperationListener$CompositeListener.onNewReaderContext(SearchOperationListener.java:189)
            at org.elasticsearch.search.SearchService.createAndPutReaderContext(SearchService.java:713)
            at org.elasticsearch.search.SearchService.createOrGetReaderContext(SearchService.java:666)
            at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:439)
            at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$2(SearchService.java:416)
            at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47)
            at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
            at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
            at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732)
            at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:748)
```

**Comment by csoulios** [comment]
Issue looks like a duplicate of https://github.com/elastic/elasticsearch/issues/58270

**Comment by craigtaverner** [comment]
The two failures above (EQL and SQL rest cancellation) were reported on 7.14 using jdk16 and jdk8, which are no longer supported by CI. So I re-tested the latest 7.17 and main (8.15) for JDK17 through JDK22, and all tests pass. The test was never muted, and no-one has reported recent failures (no comments since this issue was created Aug 2021), so I'll close this issue.

| JDK Version | SQL, main(8.15)        | SQL, 7.17                    | EQL, main(8.15)       | EQL, 7.17                    |
| ------------ | -------------------- | ---------------------|-------------------- | ---------------------|
| 17                  | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | 
| 18                  | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | 
| 19                  | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | 
| 20                  | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | 
| 21                  | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | 
| 22                  | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
