### ISSUE TITLE
[CI] SqlCancellationIT testCancellation failures

### ISSUE THREAD

**Issue by csoulios** [elastic/elasticsearch#76428]
**Build scan**:
https://gradle-enterprise.elastic.co/s/hs66h63otoyem/

**Repro line**:

```
./gradlew ':x-pack:plugin:sql:internalClusterTest' --tests "org.elasticsearch.xpack.sql.action.SqlCancellationIT.testCancellation" -Dtests.seed=4009E77FD61A0E4 -Dtests.locale=zh-HK -Dtests.timezone=America/Regina -Druntime.java=8
```

**Reproduces locally?**: No

**Applicable branches**: 7.14

**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2021-01-31T22:00:00.000Z',mode:absolute,to:'2021-08-13T20:59:59.999Z'))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.xpack.sql.action.SqlCancellationIT%22'),sort:!(time,desc))

**Failure excerpt**:

```
[2021-08-11T18:10:00,481][INFO ][o.e.x.s.a.SqlCancellationIT] [testCancellation] Index [15] docs async: [true] bulk: [false]
8月 11, 2021 6:10:11 下午 com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
警告: Uncaught exception in thread: Thread[elasticsearch[node_s0][management][T#1],5,TGRP-SqlCancellationIT]
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([4009E77FD61A0E4]:0)
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at org.elasticsearch.xpack.sql.action.AbstractSqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$0(AbstractSqlBlockingIntegTestCase.java:221)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1035)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1008)
	at org.elasticsearch.xpack.sql.action.AbstractSqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$1(AbstractSqlBlockingIntegTestCase.java:221)
	at org.elasticsearch.xpack.sql.action.AbstractSqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$3(AbstractSqlBlockingIntegTestCase.java:238)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:134)
	at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47)
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:86)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertFalse(Assert.java:64)
		at org.junit.Assert.assertFalse(Assert.java:74)
		at org.elasticsearch.xpack.sql.action.AbstractSqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$0(AbstractSqlBlockingIntegTestCase.java:221)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1023)
		... 13 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:86)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertFalse(Assert.java:64)
		at org.junit.Assert.assertFalse(Assert.java:74)
		at org.elasticsearch.xpack.sql.action.AbstractSqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$0(AbstractSqlBlockingIntegTestCase.java:221)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1023)
		... 13 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:86)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertFalse(Assert.java:64)
		at org.junit.Assert.assertFalse(Assert.java:74)
		at org.elasticsearch.xpack.sql.action.AbstractSqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$0(AbstractSqlBlockingIntegTestCase.java:221)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1023)
		... 13 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:86)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertFalse(Assert.java:64)
		at org.junit.Assert.assertFalse(Assert.java:74)
		at org.elasticsearch.xpack.sql.action.AbstractSqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$0(AbstractSqlBlockingIntegTestCase.java:221)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1023)
		... 13 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:86)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertFalse(Assert.java:64)
		at org.junit.Assert.assertFalse(Assert.java:74)
		at org.elasticsearch.xpack.sql.action.AbstractSqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$0(AbstractSqlBlockingIntegTestCase.java:221)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1023)
		... 13 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:86)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertFalse(Assert.java:64)
		at org.junit.Assert.assertFalse(Assert.java:74)
		at org.elasticsearch.xpack.sql.action.AbstractSqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$0(AbstractSqlBlockingIntegTestCase.java:221)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1023)
		... 13 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:86)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertFalse(Assert.java:64)
		at org.junit.Assert.assertFalse(Assert.java:74)
		at org.elasticsearch.xpack.sql.action.AbstractSqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$0(AbstractSqlBlockingIntegTestCase.java:221)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1023)
		... 13 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:86)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertFalse(Assert.java:64)
		at org.junit.Assert.assertFalse(Assert.java:74)
		at org.elasticsearch.xpack.sql.action.AbstractSqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$0(AbstractSqlBlockingIntegTestCase.java:221)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1023)
		... 13 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:86)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertFalse(Assert.java:64)
		at org.junit.Assert.assertFalse(Assert.java:74)
		at org.elasticsearch.xpack.sql.action.AbstractSqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$0(AbstractSqlBlockingIntegTestCase.java:221)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1023)
		... 13 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:86)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertFalse(Assert.java:64)
		at org.junit.Assert.assertFalse(Assert.java:74)
		at org.elasticsearch.xpack.sql.action.AbstractSqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$0(AbstractSqlBlockingIntegTestCase.java:221)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1023)
		... 13 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:86)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertFalse(Assert.java:64)
		at org.junit.Assert.assertFalse(Assert.java:74)
		at org.elasticsearch.xpack.sql.action.AbstractSqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$0(AbstractSqlBlockingIntegTestCase.java:221)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1023)
		... 13 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:86)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertFalse(Assert.java:64)
		at org.junit.Assert.assertFalse(Assert.java:74)
		at org.elasticsearch.xpack.sql.action.AbstractSqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$0(AbstractSqlBlockingIntegTestCase.java:221)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1023)
		... 13 more
	Suppressed: java.lang.AssertionError
		at org.junit.Assert.fail(Assert.java:86)
		at org.junit.Assert.assertTrue(Assert.java:41)
		at org.junit.Assert.assertFalse(Assert.java:64)
		at org.junit.Assert.assertFalse(Assert.java:74)
		at org.elasticsearch.xpack.sql.action.AbstractSqlBlockingIntegTestCase$SearchBlockPlugin$2.lambda$apply$0(AbstractSqlBlockingIntegTestCase.java:221)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1023)
		... 13 more
```

**Comment by csoulios** [comment]
Looks like this issue is related to https://github.com/elastic/elasticsearch/issues/76420

**Comment by craigtaverner** [comment]
The failure above was reported on 7.14 using jdk8, which is no longer supported by CI. So I re-tested the latest 7.17 and main (8.15) for JDK17 through JDK22, and all tests pass. The test was never muted, and no-one has reported recent failures (no comments since this issue was created Aug 2021), so I'll close this issue.

| JDK Version | main(8.15)                 | 7.17                             |
| ------------ | -------------------- | ---------------------|
| 17                  | :white_check_mark: | :white_check_mark: |
| 18                  | :white_check_mark: | :white_check_mark: |
| 19                  | :white_check_mark: | :white_check_mark: |
| 20                  | :white_check_mark: | :white_check_mark: |
| 21                  | :white_check_mark: | :white_check_mark: |
| 22                  | :white_check_mark: | :white_check_mark: |
