### ISSUE TITLE
HighLevelClient 7.14.0+ Appears to Break Compatibility with Amazon Elasticsearch Service

### ISSUE THREAD

**Issue by sskrla** [elastic/elasticsearch#76479]
**Elasticsearch Server Version**: 7.10.2
**Elasticsearch Client Version**: HL 7.14.0-SNAPSHOT

**Description of the problem including expected versus actual behavior**:
#73910 introduces a number of compatibility checks, one of these is specifically for responses from 7.x servers to include a `build_flavor` of `default`. In the review [@dakrone called out that OSS should likely be supported](https://github.com/elastic/elasticsearch/pull/73910#pullrequestreview-686610618), but the comment appears to have been overlooked.

As a result, any one upgrading to this client version will have their clients exception during the first call of any kind against an OSS flavor of ElasticSearch.

**Steps to reproduce**:

Connect a HighLevelClient to a 7.x version of Amazon ElasticSearch Service and issue any request.

**Provide logs (if relevant)**:

```
WARN  c.t.s.ServiceApplication Unhandled exception, terminating application:
org.elasticsearch.ElasticsearchException: Invalid or missing build flavor [oss]
	at org.elasticsearch.client.RestHighLevelClient$4.onResponse(RestHighLevelClient.java:2056)
	at org.elasticsearch.client.RestHighLevelClient$4.onResponse(RestHighLevelClient.java:2043)
	at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListenerDirectly(ListenableFuture.java:113)
	at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:100)
	at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:133)
	at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:139)
	at org.elasticsearch.client.RestHighLevelClient$5.onSuccess(RestHighLevelClient.java:2129)
	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onSuccess(RestClient.java:636)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:376)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:370)
```

**Comment by swallez** [comment]
@sskrla This was not overlooked and was a deliberate decision.

The Elasticsearch clients go through rigorous testing and validation against the official Elasticsearch distribution coming from Elastic. Since the AWS Elasticsearch Service has incompatible APIs with Elasticsearch itself, either by missing APIs or has incompatible format, we do not support it. Please consider using [Elastic Cloud](https://cloud.elastic.co/) for an official and formally supported hosted Elasticsearch distribution.

Furthermore the [high level client compatibility guidelines](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/7.14/java-rest-high-compatibility.html) guarantee forward compatibility with later minor versions of the Elasticsearch server. In other words, we recommend to upgrade the server first, and then the clients (and your applications).
