### ISSUE TITLE
IndicesRequestCacheIT.testQueryRewriteMissingValues

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#76579]
**Build scan**:
https://gradle-enterprise.elastic.co/s/b7m2cyecfjyww/
**Repro line**:

```
./gradlew ':server:integTest' -Dtests.seed=6527442E36F4488C -Dtests.class=org.elasticsearch.indices.IndicesRequestCacheIT -Dtests.method="testQueryRewriteMissingValues" -Dtests.security.manager=true -Dtests.locale=ar-LB -Dtests.timezone=Europe/Vatican -Dcompiler.java=11 -Druntime.java=8
```
**Reproduces locally?**:
No
**Applicable branches**:
6.8

**Failure excerpt**:
```
> Throwable #1: java.lang.AssertionError: expected:<[1, 1]> but was:<[0, 2]> |  
-- | --
  | > 	at __randomizedtesting.SeedInfo.seed([6527442E36F4488C:5D26C7FC6E41536D]:0) |  
  | > 	at org.elasticsearch.indices.IndicesRequestCacheIT.assertCacheState(IndicesRequestCacheIT.java:415) |  
  | > 	at org.elasticsearch.indices.IndicesRequestCacheIT.testQueryRewriteMissingValues(IndicesRequestCacheIT.java:182) |  
  | > 	at java.lang.Thread.run(Thread.java:748)
```

This is probably related to: https://github.com/elastic/elasticsearch/issues/61565 but since it was a different method failing, decided to open a separate issue.

**Comment by ywelsch** [comment]
I think we should close this one as NOFIX. ES 6.8 will be EOL in a couple of weeks.
