### ISSUE TITLE
[CI] DockerTests test010Install failing

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#76722]
This seems to be related to #76696. As the requirement for `tar` was added there

**Build scan:**
https://gradle-enterprise.elastic.co/s/giiqd4bah4jgo/tests/:qa:os:destructiveDistroTest.default-dockerUbi/org.elasticsearch.packaging.test.DockerTests/test010Install

**Reproduction line:**
`null`

**Applicable branches:**
7.x

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.DockerTests&tests.test=test010Install

**Failure excerpt:**
```
java.lang.AssertionError: tar ought to be available.

  at __randomizedtesting.SeedInfo.seed([640DB32CF27634F2:405213BF90DB6BAA]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.elasticsearch.packaging.util.Docker.lambda$verifyContainerInstallation$7(Docker.java:473)
  at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
  at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
  at org.elasticsearch.packaging.util.Docker.verifyContainerInstallation(Docker.java:472)
  at org.elasticsearch.packaging.test.DockerTests.test010Install(DockerTests.java:110)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by pugnascotia** [comment]
Pushed fixes:

   * `7.x` -> 5eff49e0e90
   * `7.15` -> 1e55a62365f
