### ISSUE TITLE
[CI] SSLErrorMessageCertificateVerificationTests testDiagnosticTrustManagerForHostnameVerificationFailure failing

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#76767]
Three failures in within 15 minutes, I'm wondering if this is a setup issue for the windows boxes.  They all have this failure:
```
[2021-08-20T23:02:06,229][WARN ][o.e.c.s.DiagnosticTrustManager] [testDiagnosticTrustManagerForHostnameVerificationFailure] failed to establish trust with server at [127.0.0.1]; the server provided a certificate with subject name [CN=not-this-host], fingerprint [b46447f4e16b15a4770a8423884cb5afd31ad81f], no keyUsage and no extendedKeyUsage; the session uses cipher suite [TLS_AES_256_GCM_SHA384] and protocol [TLSv1.3]; the certificate has subject alternative names [DNS:not.this.host]; the certificate is issued by [CN=Certificate Authority 1,OU=ssl-error-message-test,DC=elastic,DC=co] but the server did not provide a copy of the issuing certificate in the certificate chain; the issuing certificate with fingerprint [2d5980e0c909cfc9ab4a77ad11e1f7b951ee7e13] is trusted in this ssl context ([xpack.http.ssl (with trust configuration: PEM-trust{C:\Users\jenkins\workspace\platform-support\217\x-pack\plugin\security\build\resources\test\org\elasticsearch\xpack\ssl\SSLErrorMessageTests\ca1.crt})])	

java.security.cert.CertificateException: No subject alternative names matching IP address 127.0.0.1 found	
```
https://gradle-enterprise.elastic.co/s/wianficjv2egu
https://gradle-enterprise.elastic.co/s/kq6yxbgxjtt6a
https://gradle-enterprise.elastic.co/s/zx33v2imcscp6

**Build scan:**
https://gradle-enterprise.elastic.co/s/zx33v2imcscp6/tests/:x-pack:plugin:security:test/org.elasticsearch.xpack.ssl.SSLErrorMessageCertificateVerificationTests/testDiagnosticTrustManagerForHostnameVerificationFailure

**Reproduction line:**
`gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.ssl.SSLErrorMessageCertificateVerificationTests.testDiagnosticTrustManagerForHostnameVerificationFailure" -Dtests.seed=D446C61A4236C5BB -Dtests.locale=en-GB -Dtests.timezone=SystemV/EST5EDT -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ssl.SSLErrorMessageCertificateVerificationTests&tests.test=testDiagnosticTrustManagerForHostnameVerificationFailure

**Failure excerpt:**
```
java.lang.AssertionError: ssl diagnostic
Expected: <true>
     but: was <false>

  at __randomizedtesting.SeedInfo.seed([D446C61A4236C5BB:E8146EBE1C4894E7]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.elasticsearch.test.MockLogAppender$PatternSeenEventExpectation.assertMatched(MockLogAppender.java:199)
  at org.elasticsearch.test.MockLogAppender.assertAllExpectationsMatched(MockLogAppender.java:55)
  at org.elasticsearch.xpack.ssl.SSLErrorMessageCertificateVerificationTests.testDiagnosticTrustManagerForHostnameVerificationFailure(SSLErrorMessageCertificateVerificationTests.java:149)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by jkakavas** [comment]
I think that this is due to the path pattern matching that Tim added to that test today 
https://github.com/elastic/elasticsearch/blob/76a684ad322ddb8da2f20862e8050aa4ad148a37/x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/ssl/SSLErrorMessageCertificateVerificationTests.java#L134-L135, the path probably needs to be matched differently on windows. I'll assign Tim, but I might get to it first today

**Comment by davidkyle** [comment]
Muted on the master branch for Windows in https://github.com/elastic/elasticsearch/commit/cf0d2b56aaa62bfd14aca55f40497cbdd72a2970
