### ISSUE TITLE
cgroups stats not available on Debian 11

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#76812]
**Build scan:**
https://gradle-enterprise.elastic.co/s/3hshdrpwm6ona/tests/:qa:os:destructiveDistroTest.default-docker/org.elasticsearch.packaging.test.DockerTests/test140CgroupOsStatsAreAvailable

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.DockerTests&tests.test=test140CgroupOsStatsAreAvailable

**Failure excerpt:**
```
java.lang.AssertionError: Couldn't find /nodes/{nodeId}/os/cgroup in API response

  at __randomizedtesting.SeedInfo.seed([64ACE3C2900202C5:3161EBF2641C65AB]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.junit.Assert.assertFalse(Assert.java:64)
  at org.elasticsearch.packaging.test.DockerTests.test140CgroupOsStatsAreAvailable(DockerTests.java:860)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by pugnascotia** [comment]
Well this is a surprising failure.

**Comment by davidkyle** [comment]
> Well this is a surprising failure.

A pleasant surprise?

**Comment by pugnascotia** [comment]
All the recent failures are on Debian 11 🤔

**Comment by pugnascotia** [comment]
I wonder if this is related to [this change](https://www.debian.org/releases/bullseye/amd64/release-notes/ch-whats-new.en.html#cgroupv2):

> In bullseye, systemd defaults to using control groups v2 (cgroupv2), which provides a unified resource-control hierarchy. Kernel commandline parameters are available to re-enable the legacy cgroups if necessary; see the notes for OpenStack in Section 5.1.9, “OpenStack and cgroups v1” section.

**Comment by pugnascotia** [comment]
I muted the test on `master` and `7.x`

I also spun up a `debian-11` instance on GCP and there's no `cgroups` information in the payload for `/_nodes/stats/os`.

**Comment by pugnascotia** [comment]
I tested the `7.14.0` and `8.0.0-alpha1` Docker images, BTW.

**Comment by pugnascotia** [comment]
Looks like all the cgroup info is under `/sys/fs/cgroup/` now.
