### ISSUE TITLE
[CI] Zen1IT testMixedClusterFormation failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#76847]
Likely relates the backport of #76771

**Build scan:**
https://gradle-enterprise.elastic.co/s/kw3zm7ec5erls/tests/:server:internalClusterTest/org.elasticsearch.cluster.coordination.Zen1IT/testMixedClusterFormation

**Reproduction line:**
`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.cluster.coordination.Zen1IT.testMixedClusterFormation" -Dtests.seed=59A2DAAB29E9A6F6 -Dtests.locale=uk-UA -Dtests.timezone=America/Monterrey -Druntime.java=8`

**Applicable branches:**
7.x

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.cluster.coordination.Zen1IT&tests.test=testMixedClusterFormation

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=3751, name=elasticsearch[node_t2][masterService#updateTask][T#1], state=RUNNABLE, group=TGRP-Zen1IT]


  Caused by: java.lang.AssertionError: (No message provided)

    at __randomizedtesting.SeedInfo.seed([59A2DAAB29E9A6F6]:0)
    at org.elasticsearch.cluster.ClusterStatePublicationEvent.getPublicationContextConstructionElapsedMillis(ClusterStatePublicationEvent.java:95)
    at org.elasticsearch.cluster.service.MasterService$ClusterStateUpdateStatsTracker.onPublicationSuccess(MasterService.java:953)
    at org.elasticsearch.cluster.service.MasterService.onPublicationSuccess(MasterService.java:316)
    at org.elasticsearch.cluster.service.MasterService.publish(MasterService.java:293)
    at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:267)
    at org.elasticsearch.cluster.service.MasterService.access$100(MasterService.java:63)
    at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:161)
    at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:139)
    at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:177)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:259)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:222)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

```

**Comment by DaveCTurner** [comment]
Closed by #76849
