### ISSUE TITLE
highlight_query return 500 error and array_index_out_of_bounds_exception

### ISSUE THREAD

**Issue by qsding** [elastic/elasticsearch#76860]
**Elasticsearch version** (`bin/elasticsearch --version`): 
Version: 7.11.1 & 6.3.2

**Plugins installed**:
 [ik-6.3.2,ik-7.11.1]

**JVM version** (`java -version`): 
1.8.0_211

**OS version** (`uname -a` if on a Unix-like system):
 Linux localhost 3.10.0-1160.25.1.el7.x86_64

**Description of the problem including expected versus actual behavior**:
A 500 is being returned with an array index out of bounds exception when running the query outlined below. (response and logs included)
if I remove the following from the query it will pass.
```
"highlight": {
    "type": "unified",
    "fields": {
      "_id": {}
    }
  }
```
**Steps to reproduce**:
```
PUT test

POST test/_doc/C86A73509CA91D71C447DCE426AAF703
{
  "doc":{
    "username": "zhangsan",
    "age": 12
  }
}

POST test/_doc/28350D8B6B9DCBC218881034DC93C0D8
{
  "doc":{
    "username": "lisi",
    "age": 56
  }
}

GET test/_search
{
  "query": {
    "terms": {
      "_id": [
        "C86A73509CA91D71C447DCE426AAF703",
        "28350D8B6B9DCBC218881034DC93C0D8"
      ]
    }
  },
  "highlight": {
    "type": "unified",
    "fields": {
      "_id": {}
    }
  }
}
```
returns the following

```
{
  "error": {
    "root_cause": [
      {
        "type": "array_index_out_of_bounds_exception",
        "reason": "Index 24 out of bounds for length 24"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "test",
        "node": "4zwL4ngxTB-AMgnyr_QVXA",
        "reason": {
          "type": "array_index_out_of_bounds_exception",
          "reason": "Index 24 out of bounds for length 24"
        }
      }
    ],
    "caused_by": {
      "type": "array_index_out_of_bounds_exception",
      "reason": "Index 24 out of bounds for length 24",
      "caused_by": {
        "type": "array_index_out_of_bounds_exception",
        "reason": "Index 24 out of bounds for length 24"
      }
    }
  },
  "status": 500
}
```

**Comment by cbuescher** [comment]
The problem here is that the "_id" field value is stored in an optimized way for numeric and base64 ids, which is denser than the usual encoding of regular text or keyword fields. Highlighters, and apparently the "unified" hightlighter in particular, doesn't seem to work well with that. When running this example in an integration test, I ran into assertion errors with this stack trace:
```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([6612612EB9FA19C2]:0)
	at org.apache.lucene.util.UnicodeUtil.UTF8toUTF16(UnicodeUtil.java:617)
	at org.apache.lucene.util.UnicodeUtil.UTF8toUTF16(UnicodeUtil.java:658)
	at org.apache.lucene.util.automaton.DaciukMihovAutomatonBuilder.build(DaciukMihovAutomatonBuilder.java:263)
	at org.apache.lucene.util.automaton.Automata.makeStringUnion(Automata.java:575)
	at org.apache.lucene.search.uhighlight.CharArrayMatcher.fromTerms(CharArrayMatcher.java:42)
	at org.apache.lucene.search.uhighlight.MemoryIndexOffsetStrategy.buildCombinedAutomaton(MemoryIndexOffsetStrategy.java:63)
	at org.apache.lucene.search.uhighlight.MemoryIndexOffsetStrategy.<init>(MemoryIndexOffsetStrategy.java:51)
	at org.apache.lucene.search.uhighlight.UnifiedHighlighter.getOffsetStrategy(UnifiedHighlighter.java:930)
	at org.elasticsearch.lucene.search.uhighlight.CustomUnifiedHighlighter.getFieldHighlighter(CustomUnifiedHighlighter.java:186)
	at org.elasticsearch.lucene.search.uhighlight.CustomUnifiedHighlighter.<init>(CustomUnifiedHighlighter.java:118)
	at org.elasticsearch.search.fetch.subphase.highlight.UnifiedHighlighter.buildHighlighter(UnifiedHighlighter.java:139)
	at org.elasticsearch.search.fetch.subphase.highlight.UnifiedHighlighter.highlight(UnifiedHighlighter.java:59)
	at org.elasticsearch.search.fetch.subphase.highlight.HighlightPhase$1.process(HighlightPhase.java:65)
```
Whithout assertions turned on like in the test the error happens a few lines later in the same method (note this is on 7.15, different line numberings here):
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 24 out of bounds for length 24
	at org.apache.lucene.util.UnicodeUtil.UTF8toUTF16(UnicodeUtil.java:602) ~[lucene-core-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:50:37]
	at org.apache.lucene.util.UnicodeUtil.UTF8toUTF16(UnicodeUtil.java:626) ~[lucene-core-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:50:37]
	at org.apache.lucene.util.automaton.DaciukMihovAutomatonBuilder.build(DaciukMihovAutomatonBuilder.java:303) ~[lucene-core-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:50:37]
	at org.apache.lucene.util.automaton.Automata.makeStringUnion(Automata.java:600) ~[lucene-core-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:50:37]
	at org.apache.lucene.search.uhighlight.CharArrayMatcher.fromTerms(CharArrayMatcher.java:47) ~[lucene-highlighter-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:51:16]
	at org.apache.lucene.search.uhighlight.MemoryIndexOffsetStrategy.buildCombinedAutomaton(MemoryIndexOffsetStrategy.java:65) ~[lucene-highlighter-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:51:16]
	at org.apache.lucene.search.uhighlight.MemoryIndexOffsetStrategy.<init>(MemoryIndexOffsetStrategy.java:51) ~[lucene-highlighter-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:51:16]
	at org.apache.lucene.search.uhighlight.UnifiedHighlighter.getOffsetStrategy(UnifiedHighlighter.java:899) ~[lucene-highlighter-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:51:16]
	at org.apache.lucene.search.uhighlight.CustomUnifiedHighlighter.getFieldHighlighter(CustomUnifiedHighlighter.java:159) ~[elasticsearch-7.15.1.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:51:16]
	at org.apache.lucene.search.uhighlight.CustomUnifiedHighlighter.<init>(CustomUnifiedHighlighter.java:105) ~[elasticsearch-7.15.1.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:51:16]
```

I'm not sure the use case of highlighting the "_id" field is something that we would actively want to support though. What's the motivation behind trying to do this? Since "_id" is a metadata field that doesn't even appear under "_source" I'm not sure how highlighting should work even without this problem.

**Comment by cbuescher** [comment]
Closing this issue since we don't see failing highlighting on the "_id" metadata field as something that should be supported. If this is really something you need please open this as a new feature request with an explanation why highlighting this particular fields is important for your use case and you cannot use a copy of the "_id" metadata field that is part of the document itself.
