### ISSUE TITLE
[CI] Reproducible Failure in InternalAutoDateHistogramTests.testReduceRandom

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#77056]
**Build scan**:
https://gradle-enterprise.elastic.co/s/m66nyj7irozk6

**Repro line**:
 ./gradlew ':server:unitTest' \
  -Dtests.seed=9C7AEC6AB4869C93 \
  -Dtests.class=org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests \
  -Dtests.method="testReduceRandom" \
  -Dtests.security.manager=true \
  -Dtests.locale=de-AT \
  -Dtests.timezone=Zulu \
  -Dcompiler.java=11 \
  -Druntime.java=13

**Reproduces locally?**:
Yes

**Applicable branches**:
Failed on 6.8

**Failure history**:
Saw some similar looking failures back on January, seems to be a specific seed only. Also all on 6.8 as far as I can see.

**Failure excerpt**:
```
java.lang.AssertionError: expected:<{1627776000000=1309, 1630368000000=71}> but was:<{1627776000000=1309, 1630454400000=71}>
	at __randomizedtesting.SeedInfo.seed([9C7AEC6AB4869C93:5C47407B92DB05C5]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.assertReduced(InternalAutoDateHistogramTests.java:200)
	at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.assertReduced(InternalAutoDateHistogramTests.java:50)
```

**Comment by not-napoleon** [comment]
Just based on the error message, this looks like it could be a date formatting issue.  I've fixed a bunch of bugs around date formats in aggs during the 7.x lifetime.  My inclination is to say that if this is only failing on 6.8, we should just ignore it.  That version is almost end of life, and I don't think tracking this down is worth the effort.
