### ISSUE TITLE
SQL: "Unexpected end of ZLIB input stream" when reading the rolled over audit file

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#77114]
**Build scan**: https://gradle-enterprise.elastic.co/s/ensysdvzylal6
https://gradle-enterprise.elastic.co/s/knviewjp4hvus

**Repro line**: `gradlew ':x-pack:plugin:sql:qa:server:security:without-ssl:integTest' --tests "org.elasticsearch.xpack.sql.qa.security.RestSqlSecurityIT.testDescribeSingleFieldGranted" -Dtests.seed=D3D8A09C04D6FEF8 -Dtests.locale=en-AU -Dtests.timezone=Etc/GMT-14 -Druntime.java=11`

**Reproduces locally?**: no

**Applicable branches**: master

**Failure excerpt**:
```
<html>
<body>
<!--StartFragment-->

java.io.EOFException: Unexpected end of ZLIB input stream |  
-- | --
  | at __randomizedtesting.SeedInfo.seed([D3D8A09C04D6FEF8:7F32AEF790CC3BD7]:0) |  
  | at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245) |  
  | at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159) |  
  | at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:118) |  
  | at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) |  
  | at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) |  
  | at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) |  
  | at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181) |  
  | at java.base/java.io.BufferedReader.fill(BufferedReader.java:161) |  
  | at java.base/java.io.BufferedReader.skip(BufferedReader.java:414) |  
  | at org.elasticsearch.xpack.sql.qa.security.SqlSecurityTestCase$AuditLogAsserter.lambda$assertLogs$3(SqlSecurityTestCase.java:612) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:965) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:950) |  
  | at org.elasticsearch.xpack.sql.qa.security.SqlSecurityTestCase$AuditLogAsserter.assertLogs(SqlSecurityTestCase.java:580) |  
  | at org.elasticsearch.xpack.sql.qa.security.SqlSecurityTestCase.testDescribeSingleFieldGranted(SqlSecurityTestCase.java:452) |  
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) |  
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) |  
  | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) |  
  | at java.base/java.lang.reflect.Method.invoke(Method.java:566) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49) |  
  | at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) |  
  | at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48) |  
  | at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) |  
  | at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891) |  
  | at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902) |  
  | at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41) |  
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53) |  
  | at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) |  
  | at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) |  
  | at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54) |  
  | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375) |  
  | at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831) |  
  | at java.base/java.lang.Thread.run(Thread.java:834)

<!--EndFragment-->
</body>
</html>
```

**Comment by ywangd** [comment]
Another one: https://gradle-enterprise.elastic.co/s/vr26r5lvh3npy
Does not reproduce locally
