### ISSUE TITLE
[CI] Failure in FrozenSearchableSnapshotsIntegTests.testCreateAndRestorePartialSearchableSnapshot

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#77178]
**Build scan**:

https://gradle-enterprise.elastic.co/s/aa7pdmv5abrtc/console-log/raw

**Repro line**:

```
./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.FrozenSearchableSnapshotsIntegTests.testCreateAndRestorePartialSearchableSnapshot" -Dtests.seed=56B5E0A9C949E1D2 -Dtests.locale=zh-Hans-SG -Dtests.timezone=Africa/Tunis -Druntime.java=11
```

**Reproduces locally?**:

haven't tried yet

**Applicable branches**:

```
master
```

**Failure excerpt**:

```
  2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.FrozenSearchableSnapshotsIntegTests.testCreateAndRestorePartialSearchableSnapshot" -Dtests.seed=56B5E0A9C949E1D2 -Dtests.locale=zh-Hans-SG -Dtests.timezone=Africa/Tunis -Druntime.java=11
  2> org.elasticsearch.ElasticsearchException: java.io.IOException: access denied: /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob+platform-support-unix/os/centos-7&&immutable/x-pack/plugin/searchable-snapshots/build/testrun/internalClusterTest/temp/org.elasticsearch.xpack.searchablesnapshots.FrozenSearchableSnapshotsIntegTests_56B5E0A9C949E1D2-001/tempDir-002/node_s2/indices/jvnmfpSxTDG5sGhI07FVcg/4/snapshot_cache/-XXiEyMOQrCuPfojK-0R0Q/eOf3tXJeShS38UStFPglOA
        at __randomizedtesting.SeedInfo.seed([56B5E0A9C949E1D2:22322178F42ECF30]:0)
        at app//org.elasticsearch.ExceptionsHelper.convertToRuntime(ExceptionsHelper.java:48)
        at app//org.elasticsearch.xpack.searchablesnapshots.cache.full.PersistentCache$1.visitFile(PersistentCache.java:250)
        at app//org.elasticsearch.xpack.searchablesnapshots.cache.full.PersistentCache$1.visitFile(PersistentCache.java:229)
        at java.base@11.0.12/java.nio.file.Files.walkFileTree(Files.java:2725)
        at java.base@11.0.12/java.nio.file.Files.walkFileTree(Files.java:2797)
        at app//org.elasticsearch.xpack.searchablesnapshots.cache.full.PersistentCache.repopulateCache(PersistentCache.java:229)
        at app//org.elasticsearch.xpack.searchablesnapshots.cache.full.CacheService.doStart(CacheService.java:190)
        at app//org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:48)
        at java.base@11.0.12/java.util.ArrayList.forEach(ArrayList.java:1541)
        at java.base@11.0.12/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
        at app//org.elasticsearch.node.Node.start(Node.java:817)
        at app//org.elasticsearch.test.InternalTestCluster$NodeAndClient.startNode(InternalTestCluster.java:901)
        at java.base@11.0.12/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base@11.0.12/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at app//org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678)
        at java.base@11.0.12/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base@11.0.12/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base@11.0.12/java.lang.Thread.run(Thread.java:834)

        Caused by:
        java.io.IOException: access denied: /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob+platform-support-unix/os/centos-7&&immutable/x-pack/plugin/searchable-snapshots/build/testrun/internalClusterTest/temp/org.elasticsearch.xpack.searchablesnapshots.FrozenSearchableSnapshotsIntegTests_56B5E0A9C949E1D2-001/tempDir-002/node_s2/indices/jvnmfpSxTDG5sGhI07FVcg/4/snapshot_cache/-XXiEyMOQrCuPfojK-0R0Q/eOf3tXJeShS38UStFPglOA
            at org.apache.lucene.mockfile.WindowsFS.checkDeleteAccess(WindowsFS.java:114)
            at org.apache.lucene.mockfile.WindowsFS.delete(WindowsFS.java:123)
            at java.base/java.nio.file.Files.delete(Files.java:1142)
            at org.elasticsearch.xpack.searchablesnapshots.cache.full.PersistentCache$1.visitFile(PersistentCache.java:247)
            ... 16 more
```

**Comment by tlrx** [comment]
See https://github.com/elastic/elasticsearch/issues/77017#issuecomment-1020022300
