### ISSUE TITLE
[CI] LegacyGeoShapeIT testBulk failing

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#77174]
**Build scan:**
https://gradle-enterprise.elastic.co/s/6ld2i2ojixqfy/tests/:server:internalClusterTest/org.elasticsearch.search.geo.LegacyGeoShapeIT/testBulk

**Reproduction line:**
`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.search.geo.LegacyGeoShapeIT.testBulk" -Dtests.seed=AE5B9DCA21C1837A -Dtests.locale=hu -Dtests.timezone=NET -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.geo.LegacyGeoShapeIT&tests.test=testBulk

**Failure excerpt:**
```
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping: using deprecated parameters [strategy] in mapper [location] of type [geo_shape] is no longer allowed

  at __randomizedtesting.SeedInfo.seed([AE5B9DCA21C1837A:F7EFCB215FA875D3]:0)
  at org.elasticsearch.index.mapper.MapperService.parseMapping(MapperService.java:297)
  at org.elasticsearch.index.mapper.MapperService.mergeAndApplyMappings(MapperService.java:275)
  at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:259)
  at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.updateIndexMappingsAndBuildSortOrder(MetadataCreateIndexService.java:1006)
  at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.lambda$applyCreateIndexWithTemporaryService$2(MetadataCreateIndexService.java:413)
  at org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:636)
  at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexWithTemporaryService(MetadataCreateIndexService.java:411)
  at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequestWithV1Templates(MetadataCreateIndexService.java:488)
  at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:374)
  at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:381)
  at org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:298)
  at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:48)
  at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:745)
  at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:361)
  at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:224)
  at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:161)
  at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:139)
  at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:177)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678)
  at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:259)
  at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:222)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.lang.Thread.run(Thread.java:834)

  Caused by: java.lang.IllegalArgumentException: using deprecated parameters [strategy] in mapper [location] of type [geo_shape] is no longer allowed

    at org.elasticsearch.index.mapper.GeoShapeFieldMapper.lambda$static$0(GeoShapeFieldMapper.java:157)
    at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:203)
    at org.elasticsearch.index.mapper.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:153)
    at org.elasticsearch.index.mapper.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:149)
    at org.elasticsearch.index.mapper.MappingParser.parse(MappingParser.java:98)
    at org.elasticsearch.index.mapper.MappingParser.parse(MappingParser.java:92)
    at org.elasticsearch.index.mapper.MapperService.parseMapping(MapperService.java:295)
    at org.elasticsearch.index.mapper.MapperService.mergeAndApplyMappings(MapperService.java:275)
    at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:259)
    at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.updateIndexMappingsAndBuildSortOrder(MetadataCreateIndexService.java:1006)
    at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.lambda$applyCreateIndexWithTemporaryService$2(MetadataCreateIndexService.java:413)
    at org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:636)
    at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexWithTemporaryService(MetadataCreateIndexService.java:411)
    at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequestWithV1Templates(MetadataCreateIndexService.java:488)
    at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:374)
    at org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:381)
    at org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:298)
    at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:48)
    at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:745)
    at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:361)
    at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:224)
    at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:161)
    at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:139)
    at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:177)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:259)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:222)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)

```

**Comment by iverase** [comment]
I am muting this test for now.
