### ISSUE TITLE
[CI] TestFeatureLicenseTrackingIT testFeatureTrackingInferenceModelPipeline failing

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#77182]
**Build scan:**
https://gradle-enterprise.elastic.co/s/jzuycanbghb4c/tests/:x-pack:plugin:ml:internalClusterTest/org.elasticsearch.xpack.ml.integration.TestFeatureLicenseTrackingIT/testFeatureTrackingInferenceModelPipeline

**Reproduction line:**
`./gradlew ':x-pack:plugin:ml:internalClusterTest' --tests "org.elasticsearch.xpack.ml.integration.TestFeatureLicenseTrackingIT.testFeatureTrackingInferenceModelPipeline" -Dtests.seed=97E92D7B6941E903 -Dtests.locale=fr-CH -Dtests.timezone=Africa/Douala -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ml.integration.TestFeatureLicenseTrackingIT&tests.test=testFeatureTrackingInferenceModelPipeline

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=74, name=elasticsearch[node_s_0][ml_utility][T#2], state=RUNNABLE, group=TGRP-TestFeatureLicenseTrackingIT]

  at __randomizedtesting.SeedInfo.seed([97E92D7B6941E903:9F9EA15B692AEE67]:0)

  Caused by: org.elasticsearch.common.util.CancellableThreads$ExecutionCancelledException: Reset mode has been enabled

    at __randomizedtesting.SeedInfo.seed([97E92D7B6941E903]:0)
    at org.elasticsearch.xpack.ml.utils.persistence.ResultsPersisterService.lambda$new$0(ResultsPersisterService.java:117)
    at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListener(ClusterApplierService.java:531)
    at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:521)
    at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:489)
    at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:421)
    at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:151)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:259)
    at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:222)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)

```

**Comment by benwtrent** [comment]
I am not 100% sure how this exception was thrown from within the cluster state applier callback thread. 

It may be that `PlainActionFuture` simply throws from within any thread that from which the `onFailure` is called. This would be problematic. It is also weird that we don't have a full stack trace indicating the thread that originally called for the retry-able action to run.

Investigating further to see why we threw here...
