### ISSUE TITLE
[CI] ReleaseNotesIndexGeneratorTest generateFile_rendersCorrectMarkup failing

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#77190]
**Build scan:**
https://gradle-enterprise.elastic.co/s/s6xqghj265kyu/tests/:test/org.elasticsearch.gradle.internal.release.ReleaseNotesIndexGeneratorTest/generateFile_rendersCorrectMarkup

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.gradle.internal.release.ReleaseNotesIndexGeneratorTest&tests.test=generateFile_rendersCorrectMarkup

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: "[[es-release-notes]]\r\n= Release notes\r\n\r\n[partintro]\r\n--\r\n\r\nThis section summarizes the changes in each release.\r\n\r\n* <<release-notes-8.2.0>>\r\n* <<release-notes-8.1.1>>\r\n* <<release-notes-8.1.0>>\r\n* <<release-notes-8.0.2>>\r\n* <<release-notes-8.0.1>>\r\n* <<release-notes-8.0.0>>\r\n* <<release-notes-8.0.0-rc3>>\r\n* <<release-notes-8.0.0-beta2>>\r\n* <<release-notes-8.0.0-alpha1>>\r\n\r\n--\r\n\r\ninclude::release-notes/8.2.asciidoc[]\r\ninclude::release-notes/8.1.asciidoc[]\r\ninclude::release-notes/8.0.asciidoc[]\r\ninclude::release-notes/8.0.0-rc3.asciidoc[]\r\ninclude::release-notes/8.0.0-beta2.asciidoc[]\r\ninclude::release-notes/8.0.0-alpha1.asciidoc[]\r\n\r\n"
     but: was "[[es-release-notes]]\n= Release notes\n\n[partintro]\n--\n\nThis section summarizes the changes in each release.\n\n* <<release-notes-8.2.0>>\n* <<release-notes-8.1.1>>\n* <<release-notes-8.1.0>>\n* <<release-notes-8.0.2>>\n* <<release-notes-8.0.1>>\n* <<release-notes-8.0.0>>\n* <<release-notes-8.0.0-rc3>>\n* <<release-notes-8.0.0-beta2>>\n* <<release-notes-8.0.0-alpha1>>\n\n--\n\ninclude::release-notes/8.2.asciidoc[]\ninclude::release-notes/8.1.asciidoc[]\ninclude::release-notes/8.0.asciidoc[]\ninclude::release-notes/8.0.0-rc3.asciidoc[]\ninclude::release-notes/8.0.0-beta2.asciidoc[]\ninclude::release-notes/8.0.0-alpha1.asciidoc[]\n\n"

  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
  at org.junit.Assert.assertThat(Assert.java:964)
  at org.junit.Assert.assertThat(Assert.java:930)
  at org.elasticsearch.gradle.internal.release.ReleaseNotesIndexGeneratorTest.generateFile_rendersCorrectMarkup(ReleaseNotesIndexGeneratorTest.java:53)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:567)
  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
  at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
  at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
  at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
  at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
  at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
  at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
  at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
  at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
  at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
  at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
  at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:567)
  at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
  at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
  at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
  at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
  at jdk.proxy1.$Proxy2.processTestClass(null:-1)
  at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
  at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
  at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
  at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
  at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
  at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
  at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
  at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
  at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

```

**Comment by pugnascotia** [comment]
Should finally be fixed by #77238.
