### ISSUE TITLE
[CI] DataStreamIT testCreatingDataStreamAndFirstBackingIndexExistsFails failing

### ISSUE THREAD

**Issue by valeriy42** [elastic/elasticsearch#77307]
I've seen two failures in the past 3 days. Only on `oraclelinux`.

**Build scan:**
https://gradle-enterprise.elastic.co/s/biabjnsiw6j2s/tests/:x-pack:plugin:data-streams:internalClusterTest/org.elasticsearch.datastreams.DataStreamIT/testCreatingDataStreamAndFirstBackingIndexExistsFails

**Reproduction line:**
`./gradlew ':x-pack:plugin:data-streams:internalClusterTest' --tests "org.elasticsearch.datastreams.DataStreamIT.testCreatingDataStreamAndFirstBackingIndexExistsFails" -Dtests.seed=2F26E895DD7EBA43 -Dtests.locale=et -Dtests.timezone=Asia/Famagusta -Druntime.java=8`

**Applicable branches:**
7.14

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.datastreams.DataStreamIT&tests.test=testCreatingDataStreamAndFirstBackingIndexExistsFails

**Failure excerpt:**
```
junit.framework.AssertionFailedError: Expected exception ElasticsearchStatusException but no exception was thrown

  at __randomizedtesting.SeedInfo.seed([2F26E895DD7EBA43:1208B5880CA9E3E2]:0)
  at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2744)
  at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2734)
  at org.elasticsearch.datastreams.DataStreamIT.testCreatingDataStreamAndFirstBackingIndexExistsFails(DataStreamIT.java:1243)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by martijnvg** [comment]
The index created that should conflict with the backing index of the data stream has a different name.

Index creation:

```
[2021-09-06T02:59:59,962][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s0] [.ds-logs-foobar-2021.09.05-000001] creating index, cause [api], templates [random_index_template], shards [4]/[1]	
```

Data stream creation:

```
[2021-09-06T03:00:00,293][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s0] [.ds-logs-foobar-2021.09.06-000001] creating index, cause [initialize_data_stream], templates [id], shards [1]/[1]	
	[2021-09-06T03:00:00,297][INFO ][o.e.c.m.MetadataCreateDataStreamService] [node_s0] adding data stream [logs-foobar] with write index [.ds-logs-foobar-2021.09.06-000001] and backing indices []
```

It has a different name because the regular index is created before local midnight and the data stream after. This is a classic data/time related test bug.

**Comment by martijnvg** [comment]
@danhermann What do you think about adding a startTime field to `CreateDataStreamAction.Request` class? The `MetadataCreateDataStreamService#createDataStream(...)` will use that for the name of the backing index instead of using `System.currentTimeMillis()` (via `DataStream#getDefaultBackingIndexName()`). Then in tests like this one we set this field, so that we can ensure the same backing index is created as expected. Which means that in test we can consistently expect a failure.

This setter/constructor to be added to `CreateDataStreamAction.Request`, will not be used in the create data stream rest action, which means it is only accessible from tests / internal code.

**Comment by danhermann** [comment]
> @danhermann What do you think about adding a startTime field to `CreateDataStreamAction.Request` class? The `MetadataCreateDataStreamService#createDataStream(...)` will use that for the name of the backing index instead of using `System.currentTimeMillis()` (via `DataStream#getDefaultBackingIndexName()`). Then in tests like this one we set this field, so that we can ensure the same backing index is created as expected. Which means that in test we can consistently expect a failure.
> 
> This setter/constructor to be added to `CreateDataStreamAction.Request`, will not be used in the create data stream rest action, which means it is only accessible from tests / internal code.

That sounds good to me, especially since we've had this issue for lots of data stream tests.
