### ISSUE TITLE
:example-plugins:rest-handler:javaRestTest fails with "seccomp unavailable" on certain builds

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#77333]
I've seen this on the following build today: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+platform-support-unix/os=centos-6&&immutable/

**Build scan**:

https://gradle-enterprise.elastic.co/s/2vrlt7eth7oso

**Repro line**:

No repro line

**Reproduces locally?**:

No

**Applicable branches**:

7.x, seems to be this particular build

**Failure history**:

I encountered a similar looking one at https://gradle-enterprise.elastic.co/s/gelxmydenjaz4, although that one failed in :example-plugins:custom-settings:yamlRestTest

Console output: 
```
03:13:36 > Task :example-plugins:rest-handler:javaRestTest FAILED
03:13:36 
03:13:36 === Log output of node `node{:example-plugins:rest-handler:javaRestTest-0}` ===
03:13:36 
03:13:36 »    ↓ errors and warnings from /var/lib/jenkins/workspace/elastic+elasticsearch+7.x+multijob+platform-support-unix/os/centos-6&&immutable/plugins/examples/rest-handler/build/testclusters/javaRestTest-0/logs/javaRestTest.log ↓
03:13:36 » [2021-09-07T01:12:43,456][WARN ][o.e.b.JNANatives         ] [javaRestTest-0] unable to install syscall filter: 
03:13:36 »  java.lang.UnsupportedOperationException: seccomp unavailable: CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER are needed
03:13:36 »  	at org.elasticsearch.bootstrap.SystemCallFilter.linuxImpl(SystemCallFilter.java:331) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.bootstrap.SystemCallFilter.init(SystemCallFilter.java:606) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.bootstrap.JNANatives.tryInstallSystemCallFilter(JNANatives.java:248) [elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.bootstrap.Natives.tryInstallSystemCallFilter(Natives.java:102) [elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:108) [elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170) [elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:399) [elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:167) [elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:158) [elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75) [elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:114) [elasticsearch-cli-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.cli.Command.main(Command.java:79) [elasticsearch-cli-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:123) [elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81) [elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 » [2021-09-07T01:12:45,920][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [javaRestTest-0] fatal error in thread [main], exiting
03:13:36 »  java.lang.AssertionError: null
03:13:36 »  	at org.elasticsearch.monitor.os.OsProbe.readProcSelfCgroup(OsProbe.java:298) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.monitor.os.OsProbe.areCgroupStatsAvailable(OsProbe.java:579) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:637) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:857) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:864) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.monitor.os.OsService.<init>(OsService.java:39) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.monitor.MonitorService.<init>(MonitorService.java:33) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.node.Node.<init>(Node.java:509) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.node.Node.<init>(Node.java:288) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:219) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:219) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:399) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:167) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:158) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:114) ~[elasticsearch-cli-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.cli.Command.main(Command.java:79) ~[elasticsearch-cli-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:123) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
03:13:36 »  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
```

**Comment by pugnascotia** [comment]
It looks like ES also had a problem reading `/proc/self/cgroup` which is really peculiar. I wonder if the machine was just...busted?

**Comment by dimitris-athanasiou** [comment]
A number of tests failed similarly in https://gradle-enterprise.elastic.co/s/pg7mm5k2i4nz6

**Comment by mark-vieira** [comment]
This looks to be specific to CentOS 6 and Oracle Linux 6. Those CI jobs have been consistently failing with this error. Somewhere along the line we broke compatibility with those OSes or something has changed in our CI images.

**Comment by mark-vieira** [comment]
Looks like this started earlier this month: https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20*%0A%3E%20process%20was%20found%20dead%20while%20waiting%20for%20ports%20files,%20*&search.relativeStartTime=P28D&search.tags=os%3Doraclelinux-6%26%26immutable&search.tags=7.x&search.tags=not:nested&search.timeZoneId=America/Los_Angeles
