### ISSUE TITLE
[CI] UpgradeClusterClientYamlTestSuiteIT test {p0=mixed_cluster/50_token_auth/Get the indexed token and use if to authenticate} failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#77350]
**Build scan:**
https://gradle-enterprise.elastic.co/s/4vky7vfzdsoca/tests/:x-pack:qa:rolling-upgrade:v6.8.19%23twoThirdsUpgradedTest/org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT/test%20%7Bp0=mixed_cluster%2F50_token_auth%2FGet%20the%20indexed%20token%20and%20use%20if%20to%20authenticate%7D

**Reproduction line:**
`./gradlew ':x-pack:qa:rolling-upgrade:v6.8.19#twoThirdsUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=mixed_cluster/50_token_auth/Get the indexed token and use if to authenticate}" -Dtests.seed=900DED1F8A9F603F -Dtests.bwc=true -Dtests.locale=el -Dtests.timezone=Cuba -Druntime.java=8`

**Applicable branches:**
7.15

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dmixed_cluster/50_token_auth/Get%20the%20indexed%20token%20and%20use%20if%20to%20authenticate%7D

**Failure excerpt:**
```
java.lang.AssertionError: Failure at [mixed_cluster/50_token_auth:21]: expected [2xx] status code but api [security.authenticate] returned [401 Unauthorized] [{"error":{"root_cause":[{"type":"security_exception","reason":"token expired","header":{"WWW-Authenticate":"Bearer realm=\"security\", error=\"invalid_token\", error_description=\"The access token expired\""}}],"type":"security_exception","reason":"token expired","header":{"WWW-Authenticate":"Bearer realm=\"security\", error=\"invalid_token\", error_description=\"The access token expired\""}},"status":401}]

  at __randomizedtesting.SeedInfo.seed([900DED1F8A9F603F:1859D2C524630DC7]:0)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:462)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:439)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

  Caused by: java.lang.AssertionError: expected [2xx] status code but api [security.authenticate] returned [401 Unauthorized] [{"error":{"root_cause":[{"type":"security_exception","reason":"token expired","header":{"WWW-Authenticate":"Bearer realm=\"security\", error=\"invalid_token\", error_description=\"The access token expired\""}}],"type":"security_exception","reason":"token expired","header":{"WWW-Authenticate":"Bearer realm=\"security\", error=\"invalid_token\", error_description=\"The access token expired\""}},"status":401}]

    at org.junit.Assert.fail(Assert.java:88)
    at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:354)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:455)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:439)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
    at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
    at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
    at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
    at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
    at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
    at java.lang.Thread.run(Thread.java:748)

```

**Comment by cbuescher** [comment]
When I tried local reproduction with the reported repro line I didn't get the same failure as in the CI run but this:

```
org.elasticsearch.client.ResponseException: method [GET], host [http://127.0.0.1:52837], URI [token_backwards_compatibility_it/_doc/old_cluster_token1], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"token_backwards_compatibility_it","index_uuid":"_na_","index":"token_backwards_compatibility_it"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"token_backwards_compatibility_it","index_uuid":"_na_","index":"token_backwards_compatibility_it"},"status":404}
	at __randomizedtesting.SeedInfo.seed([900DED1F8A9F603F:7260E4D4E66430E4]:0)
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
	at org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.retrieveStoredTokens(TokenBackwardsCompatibilityIT.java:429)
	at org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.testAccessTokensWorkInMixedCluster(TokenBackwardsCompatibilityIT.java:200)
```
This might be due to the rolling upgrade test procedure which I'm not totally familiar with. I don't know how good the reproduction line is supposed to work here, adding it just in case.

**Comment by tvernum** [comment]
@ywangd will look

**Comment by valeriy42** [comment]
It also happened here https://gradle-enterprise.elastic.co/s/u7kvqotax4an4

**Comment by tlrx** [comment]
Occured again today: https://gradle-enterprise.elastic.co/s/ze4jfz3smozjk

**Comment by martijnvg** [comment]
This failed again today: https://gradle-enterprise.elastic.co/s/vnrpri3dk6vzy

Test that failed because of expired token: 
* UpgradeClusterClientYamlTestSuiteIT » test {p0=upgraded_cluster/50_token_auth/Get the indexed token and use if to authenticate}
* TokenBackwardsCompatibilityIT » testAccessTokensWorkInUpgradedCluster

When trying to reproduce the `testAccessTokensWorkInUpgradedCluster` failure I ran into the same issue that @cbuescher mentioned. The test failed, but not because expired token but because of `index_not_found_exception`. See: https://gradle-enterprise.elastic.co/s/ieeibaketyhbq

**Comment by csoulios** [comment]
Failed again today: https://gradle-enterprise.elastic.co/s/5c5ntednor7tq

**Comment by n1v0lg** [comment]
Hmm it looks like the reason it doesn't reproduce locally and fails with an index_not_found instead, is that the test relies on other tests to create tokens. `storeTokens` is what creates the relevant index and populates it with tokens, and that method is not called on setup or in the specific failing test (`testAccessTokensWorkInUpgradedCluster` in my case).

**Comment by ywangd** [comment]
It seems concerning that these tests took so long to run. The entire suite finishes/fails around 4 hours. The gap between running oldClusterTest and upgradedClusterTest is more than 1 hour. I noticed they are all of job `elastic+elasticsearch+main+multijob+platform-support-unix` for different OSes. Is this normal? @mark-vieira

**Comment by n1v0lg** [comment]
Based [on gradle performance stats](https://gradle-enterprise.elastic.co/scans/performance?performance.metric=buildTime&performance.offset=4973&performance.pageSize=172&search.buildOutcome=success&search.relativeStartTime=P28D&search.rootProjectNames=elasticsearch&search.tags=elastic%2Belasticsearch%2Bmain%2Bmultijob%2Bplatform-support-unix&search.tasks=check&search.timeZoneId=Europe/Berlin#performance.focusedBuild=hguh5mpeprzzo) for the `check` task and label `elastic+elasticsearch+main+multijob+platform-support-unix`, the overall build time does not appear to have changed over the past 28 days. The average is 4 hr 15 min for successful builds.

It is a little suspect that there would be such a long time between `oldClusterTest` and `upgradedClusterTest`, though that also seems consistent with the past since the same issue--at least so far as I can tell--was occurring already back in Sept '21. 

My guess for why there is such a big gap is that we first run multiple test suites with `oldClusterTest` in a batch, then mixed, then upgraded. However, that's mere surmise on my part. Will wait for Mark to confirm or deny!

**Comment by mark-vieira** [comment]
> My guess for why there is such a big gap is that we first run multiple test suites with oldClusterTest in a batch, then mixed, then upgraded. However, that's mere surmise on my part. Will wait for Mark to confirm or deny!

This is accurate. Our mixed cluster tests are by far the slowest running tests in the suite. I've raised several issues about this in the past. The general finding is that mixed clusters, especially with older 6.x nodes, perform _much_ worse. I can't speculate as to why that is but that's the story being told by our test suites. Really mixed clusters are a temporary situation, so I think from a performance standpoint, this isn't a real priority, as it's a transient situation. Of course for our test suites it's a different story.

So yes, they are incredibly slow, and yes, we are aware, and no, there's not a whole lot we can do about it other than potentially split up the test suites or run more in parallel but their are complex obstacles to doing so.
