### ISSUE TITLE
[CI] CustomLoggingConfigIT testSuccessfulStartupWithCustomConfig failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#77430]
Looks like it gets _some_ relevant log lines but it's missing the one about state recovery. The log lines it does capture will be emitted after state recovery so I think it's not just that the 10s wait is too short.

**Build scan:**
https://gradle-enterprise.elastic.co/s/xflawzovvzi36/tests/:qa:logging-config:integTest/org.elasticsearch.qa.custom_logging.CustomLoggingConfigIT/testSuccessfulStartupWithCustomConfig

**Reproduction line:**
`./gradlew ':qa:logging-config:integTest' --tests "org.elasticsearch.qa.custom_logging.CustomLoggingConfigIT.testSuccessfulStartupWithCustomConfig" -Dtests.seed=1DF5C65D581FFA4C -Dtests.locale=sv -Dtests.timezone=America/North_Dakota/Beulah -Druntime.java=8`

**Applicable branches:**
7.14, master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.qa.custom_logging.CustomLoggingConfigIT&tests.test=testSuccessfulStartupWithCustomConfig

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: a collection containing .*integTest-0.*cluster.uuid.*node.id.*recovered.*cluster_state.*
     but: mismatches were: [was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding index template [.watch-history-13] for index patterns [.watcher-history-13*]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding index template [ilm-history] for index patterns [ilm-history-5*]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding index template [.slm-history] for index patterns [.slm-history-5*]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding component template [.deprecation-indexing-mappings]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding component template [.deprecation-indexing-settings]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding template [.monitoring-alerts-7] for index patterns [.monitoring-alerts-7]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding template [.monitoring-es] for index patterns [.monitoring-es-7-*]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding template [.monitoring-kibana] for index patterns [.monitoring-kibana-7-*]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding template [.monitoring-logstash] for index patterns [.monitoring-logstash-7-*]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding template [.monitoring-beats] for index patterns [.monitoring-beats-7-*]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding index template [metrics] for index patterns [metrics-*-*]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding index template [logs] for index patterns [logs-*-*]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding index template [synthetics] for index patterns [synthetics-*-*]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding index template [.deprecation-indexing-template] for index patterns [.logs-deprecation.*]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding index lifecycle policy [ml-size-based-ilm-policy]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding index lifecycle policy [synthetics]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding index lifecycle policy [logs]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding index lifecycle policy [metrics]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding index lifecycle policy [watch-history-ilm-policy]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding index lifecycle policy [ilm-history-ilm-policy]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding index lifecycle policy [slm-history-ilm-policy]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding index lifecycle policy [.deprecation-indexing-ilm-policy]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  adding index lifecycle policy [.fleet-actions-results-ilm-policy]", was "integTest-0 \"cluster.uuid\": \"jyYtHikyROyUCvx6hh4P_g\", \"node.id\": \"DKXsozUgT1e99KNLzN1vFQ\"  license [19e77cfe-0a46-4626-bbb4-3b17b843727d] mode [basic] - valid"]

  at __randomizedtesting.SeedInfo.seed([1DF5C65D581FFA4C:827E1328EE574FE8]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.qa.custom_logging.CustomLoggingConfigIT.lambda$testSuccessfulStartupWithCustomConfig$0(CustomLoggingConfigIT.java:37)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1035)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1008)
  at org.elasticsearch.qa.custom_logging.CustomLoggingConfigIT.testSuccessfulStartupWithCustomConfig(CustomLoggingConfigIT.java:35)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by pgomulka** [comment]
looks like the test run around midnight and the logs rolled over. The log line that it wanted to assert was already in a zipped file. (gradle -> summary -> gcp upload contains the package with logs).
I think this is not a rare scenario - we discussed this with @astefan when he observed this problem for JDBC logs https://github.com/elastic/elasticsearch/issues/73657

I will try to fix this with just a hack to read the archived file as well. 
Similar approach was used here for packaging archive test https://github.com/elastic/elasticsearch/issues/41436

**Comment by pgomulka** [comment]
actually we discussed this and concluded that the test itself serves no purpose. There is no point testing custom (or old - previous version) logging configs. 
We should expect ES user when upgrading he will update the config to latest version.
I will remove that test from master and 7.x
