### ISSUE TITLE
[CI] JdbcShowTablesIT.testShowTablesWithManyIndices failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#77492]
**Build scan**: https://gradle-enterprise.elastic.co/s/4agbjy4xtkv3c

**Repro line**: `./gradlew ':x-pack:plugin:sql:qa:server:security:with-ssl:integTest' --tests "org.elasticsearch.xpack.sql.qa.security.JdbcShowTablesIT.testShowTablesWithManyIndices" -Dtests.seed=A61A29C541868346 -Dtests.locale=it-CH -Dtests.timezone=Brazil/West -Druntime.java=11`

**Reproduces locally?**: No

**Applicable branches**: master

**Failure history**:

**Failure excerpt**:

```
org.junit.ComparisonFailure: Different result for column [name], entry [1] expected:<[test00]> but was:<[.security]>


at __randomizedtesting.SeedInfo.seed([A61A29C541868346:59054DA9B50F79C2]:0) |  
-- | --
  |   | at org.junit.Assert.assertEquals(Assert.java:115) |  
  |   | at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.doAssertResultSetData(JdbcAssert.java:337) |  
  |   | at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSetData(JdbcAssert.java:221) |  
  |   | at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:104) |  
  |   | at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:83) |  
  |   | at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:72) |  
  |   | at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:68) |  
  |   | at org.elasticsearch.xpack.sql.qa.jdbc.ShowTablesTestCase.testShowTablesWithManyIndices(ShowTablesTestCase.java:36) |  
  |   | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) |  
  |   | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) |  
  |   | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) |  
  |   | at java.lang.reflect.Method.invoke(Method.java:566) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49) |  
  |   | at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) |  
  |   | at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48) |  
  |   | at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) |  
  |   | at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375) |  
  |   | at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824) |  
  |   | at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902) |  
  |   | at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41) |  
  |   | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  |   | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53) |  
  |   | at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) |  
  |   | at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) |  
  |   | at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375) |  
  |   | at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831) |  
  |   | at java.lang.Thread.run(Thread.java:834)

```

**Comment by astefan** [comment]
Thank you for the report. Reproduces for me. It seems that `.security` indices are listed as well, something that the tests didn't account for since they were created some years ago. Likely, the `.security` indices cannot be deleted anymore judging by the test logs:

```
  1> [2021-09-09T07:33:22,792][INFO ][o.e.x.s.q.s.JdbcShowTablesIT] [testShowTablesWithManyIndices] before test
  1> [2021-09-09T07:33:23,010][INFO ][o.e.x.s.q.s.JdbcShowTablesIT] [testShowTablesWithManyIndices] initializing REST clients against [https://[::1]:33621, https://127.0.0.1:41127]
  1> [2021-09-09T07:33:27,203][WARN ][o.e.c.RestClient         ] [testShowTablesWithManyIndices] request [DELETE https://127.0.0.1:41127/*,-.ds-ilm-history-*?expand_wildcards=open%2Cclosed%2Chidden] returned 1 warnings: [299 Elasticsearch-8.0.0-SNAPSHOT-7042e4441a8c5c039632476f1f4e2ee8cce5cf94 "this request accesses system indices: [.security-7], but in a future major version, direct access to system indices will be prevented by default"]
  1> [2021-09-09T07:33:27,592][INFO ][o.e.x.s.q.s.JdbcShowTablesIT] [testShowTablesWithManyIndices] after test
  2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:sql:qa:server:security:with-ssl:integTest' --tests "org.elasticsearch.xpack.sql.qa.security.JdbcShowTablesIT.testShowTablesWithManyIndices" -Dtests.seed=A61A29C541868346 -Dtests.locale=it-CH -Dtests.timezone=Brazil/West -Druntime.java=11
  2> org.junit.ComparisonFailure: Different result for column [name], entry [1] expected:<[test00]> but was:<[.security]>
        at __randomizedtesting.SeedInfo.seed([A61A29C541868346:59054DA9B50F79C2]:0)
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.doAssertResultSetData(JdbcAssert.java:337)
        at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSetData(JdbcAssert.java:221)
        at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:104)
        at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:83)
        at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:72)
        at org.elasticsearch.xpack.sql.qa.jdbc.JdbcAssert.assertResultSets(JdbcAssert.java:68)
        at org.elasticsearch.xpack.sql.qa.jdbc.ShowTablesTestCase.testShowTablesWithManyIndices(ShowTablesTestCase.java:36)
```
