### ISSUE TITLE
[CI] SSLReloadDuringStartupIntegTests.testReloadDuringStartup failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#77490]
**Build scan**: https://gradle-enterprise.elastic.co/s/clwjh3wwihleq

**Repro line**: `./gradlew ':x-pack:plugin:security:internalClusterTest' --tests "org.elasticsearch.xpack.ssl.SSLReloadDuringStartupIntegTests.testReloadDuringStartup" -Dtests.seed=BA2B1D7CDA4F078A -Dtests.locale=en-IN -Dtests.timezone=Europe/Chisinau -Druntime.java=11`

**Reproduces locally?**: no

**Applicable branches**: master

**Failure history**: failed two times today

**Failure excerpt**:

```
java.lang.AssertionError: Shard [.security-7][0] is still locked after 5 sec waiting
at __randomizedtesting.SeedInfo.seed([BA2B1D7CDA4F078A:61F923312DF8000E]:0) |  
-- | --
  |   | at org.junit.Assert.fail(Assert.java:88) |  
  |   | at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2331) |  
  |   | at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:553) |  
  |   | at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2079) |  
  |   | at jdk.internal.reflect.GeneratedMethodAccessor18.invoke(Unknown Source) |  
  |   | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) |  
  |   | at java.lang.reflect.Method.invoke(Method.java:566) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004) |  
  |   | at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49) |  
  |   | at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) |  
  |   | at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48) |  
  |   | at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) |  
  |   | at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375) |  
  |   | at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824) |  
  |   | at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902) |  
  |   | at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) |  
  |   | at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41) |  
  |   | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  |   | at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53) |  
  |   | at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47) |  
  |   | at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64) |  
  |   | at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375) |  
  |   | at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831) |  
  |   | at java.lang.Thread.run(Thread.java:834)
```

Logs show

```
[2021-09-09T14:15:57,651][WARN ][o.e.t.TcpTransport       ] [node_s3] exception caught on transport layer [TcpNioSocketChannel{localAddress=null, remoteAddress=null, profile=default}], closing connection
javax.net.ssl.SSLException: Closed engine without completely sending the close alert message.
	at org.elasticsearch.xpack.security.transport.nio.SSLDriver.close(SSLDriver.java:161) ~[main/:?]
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:74) ~[elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:116) ~[elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:66) ~[elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.security.transport.nio.SSLChannelContext.closeFromSelector(SSLChannelContext.java:207) ~[main/:?]
	at org.elasticsearch.nio.EventHandler.handleClose(EventHandler.java:229) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.closeChannel(NioSelector.java:469) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.queueChannelClose(NioSelector.java:300) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.security.transport.nio.SSLChannelContext.closeChannel(SSLChannelContext.java:190) [main/:?]
	at org.elasticsearch.transport.nio.NioTcpChannel.close(NioTcpChannel.java:61) [transport-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:74) [elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:116) [elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:99) [elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.common.network.CloseableChannel.closeChannels(CloseableChannel.java:78) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.closeAndFail(TcpTransport.java:987) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onFailure(TcpTransport.java:975) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.action.ActionListener.lambda$toBiConsumer$0(ActionListener.java:277) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.core.CompletableContext.lambda$addListener$0(CompletableContext.java:31) [elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) [?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) [?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) [?:?]
	at org.elasticsearch.core.CompletableContext.completeExceptionally(CompletableContext.java:46) [elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.SocketChannelContext.connect(SocketChannelContext.java:131) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.EventHandler.handleConnect(EventHandler.java:106) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.attemptConnect(NioSelector.java:417) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.registerChannel(NioSelector.java:440) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.setUpNewChannels(NioSelector.java:429) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.preSelect(NioSelector.java:250) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:144) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:120) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:834) [?:?]
	Suppressed: javax.net.ssl.SSLException: Closed engine without receiving the close alert message.
		at org.elasticsearch.xpack.security.transport.nio.SSLDriver.close(SSLDriver.java:166) ~[main/:?]
		at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:74) ~[elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:116) ~[elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:66) ~[elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.xpack.security.transport.nio.SSLChannelContext.closeFromSelector(SSLChannelContext.java:207) ~[main/:?]
		at org.elasticsearch.nio.EventHandler.handleClose(EventHandler.java:229) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.nio.NioSelector.closeChannel(NioSelector.java:469) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.nio.NioSelector.queueChannelClose(NioSelector.java:300) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.xpack.security.transport.nio.SSLChannelContext.closeChannel(SSLChannelContext.java:190) [main/:?]
		at org.elasticsearch.transport.nio.NioTcpChannel.close(NioTcpChannel.java:61) [transport-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:74) [elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:116) [elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:99) [elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.common.network.CloseableChannel.closeChannels(CloseableChannel.java:78) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.closeAndFail(TcpTransport.java:987) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onFailure(TcpTransport.java:975) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.action.ActionListener.lambda$toBiConsumer$0(ActionListener.java:277) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.core.CompletableContext.lambda$addListener$0(CompletableContext.java:31) [elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) [?:?]
		at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) [?:?]
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
		at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) [?:?]
		at org.elasticsearch.core.CompletableContext.completeExceptionally(CompletableContext.java:46) [elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.nio.SocketChannelContext.connect(SocketChannelContext.java:131) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.nio.EventHandler.handleConnect(EventHandler.java:106) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.nio.NioSelector.attemptConnect(NioSelector.java:417) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.nio.NioSelector.registerChannel(NioSelector.java:440) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.nio.NioSelector.setUpNewChannels(NioSelector.java:429) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.nio.NioSelector.preSelect(NioSelector.java:250) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:144) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:120) [elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
		at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by jrodewig** [comment]
Had another instance of this failure: https://gradle-enterprise.elastic.co/s/w6qy6wijryvqs

Muted the test with https://github.com/elastic/elasticsearch/pull/77518

**Comment by DaveCTurner** [comment]
I encountered a failure of this test on 7.15 too, albeit with different symptoms: https://gradle-enterprise.elastic.co/s/zrooj4ggt6bza

```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=3210, name=Thread-33, state=RUNNABLE, group=TGRP-SSLReloadDuringStartupIntegTests]
Caused by: java.io.UncheckedIOException: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\platform-support\56\x-pack\plugin\security\build\testrun\internalClusterTest\temp\org.elasticsearch.xpack.ssl.SSLReloadDuringStartupIntegTests_DDBA3F0E8B6C43A4-001\tempFile-004.tmp -> C:\Users\jenkins\workspace\platform-support\56\x-pack\plugin\security\build\testrun\internalClusterTest\temp\org.elasticsearch.xpack.ssl.SSLReloadDuringStartupIntegTests_DDBA3F0E8B6C43A4-001\tempDir-003\SUITE-1\config\testnode.jks
	at __randomizedtesting.SeedInfo.seed([DDBA3F0E8B6C43A4]:0)
	at org.elasticsearch.xpack.ssl.SSLReloadDuringStartupIntegTests$1.lambda$onNodeStopped$0(SSLReloadDuringStartupIntegTests.java:101)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\platform-support\56\x-pack\plugin\security\build\testrun\internalClusterTest\temp\org.elasticsearch.xpack.ssl.SSLReloadDuringStartupIntegTests_DDBA3F0E8B6C43A4-001\tempFile-004.tmp -> C:\Users\jenkins\workspace\platform-support\56\x-pack\plugin\security\build\testrun\internalClusterTest\temp\org.elasticsearch.xpack.ssl.SSLReloadDuringStartupIntegTests_DDBA3F0E8B6C43A4-001\tempDir-003\SUITE-1\config\testnode.jks
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at org.apache.lucene.mockfile.FilterFileSystemProvider.move(FilterFileSystemProvider.java:147)
	at org.apache.lucene.mockfile.FilterFileSystemProvider.move(FilterFileSystemProvider.java:147)
	at org.apache.lucene.mockfile.FilterFileSystemProvider.move(FilterFileSystemProvider.java:147)
	at org.apache.lucene.mockfile.FilterFileSystemProvider.move(FilterFileSystemProvider.java:147)
	at java.nio.file.Files.move(Files.java:1395)
	at org.elasticsearch.xpack.ssl.SSLReloadDuringStartupIntegTests.copyAndAtomicMoveIfPossible(SSLReloadDuringStartupIntegTests.java:123)
	at org.elasticsearch.xpack.ssl.SSLReloadDuringStartupIntegTests.access$000(SSLReloadDuringStartupIntegTests.java:31)
	at org.elasticsearch.xpack.ssl.SSLReloadDuringStartupIntegTests$1.lambda$onNodeStopped$0(SSLReloadDuringStartupIntegTests.java:98)
	... 1 more
```

and

```
	at org.elasticsearch.test.InternalTestCluster.validateClusterFormed(InternalTestCluster.java:1320)
	at org.elasticsearch.test.InternalTestCluster.restartNode(InternalTestCluster.java:1950)
	at org.elasticsearch.test.InternalTestCluster.restartNode(InternalTestCluster.java:1905)
	at org.elasticsearch.xpack.ssl.SSLReloadDuringStartupIntegTests.testReloadDuringStartup(SSLReloadDuringStartupIntegTests.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: Missing master, expected nodes: [{node_s0}{AzdMRfl7TFGZqeM3gx99rA}{CFhOIFAqQpGL5ncrceEcrQ}{127.0.0.1}{127.0.0.1:55179}{cdfhimrsw}{xpack.installed=true}, {node_s2}{F1ZTMsaSTb2Jba5T0vg8wQ}{Cf2fB8h_T2OufWPerGcKYw}{127.0.0.1}{127.0.0.1:55180}{xpack.installed=true}, {node_s1}{dSz6u7lgQk-oNhjDhra0rg}{Y51gOXx1R-qiLXkFLFR61g}{127.0.0.1}{127.0.0.1:55285}{cdfhimrsw}{xpack.installed=true}] and actual cluster states [cluster uuid: 0Iv-_FldTrG7YYsGm_tdnQ [committed: true]
...
```

I backported the mute to 7.x and 7.15.

**Comment by justincr-elastic** [comment]
I suspect this is a race condition. There is ~1.5 seconds between starting and finishing the initial Transport SSL reload. During that time, Transport is trying to send and receive messages. SecurityServerTransportInterceptor is trying and failing to use the incomplete initialized SSL contexts (server & client), which fails for different reasons depending how far along it is in initialization.
