### ISSUE TITLE
[CI] ArchiveGenerateInitialPasswordTests test50VerifyAutogeneratedCredentials failing

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#77621]
**Build scan:**
https://gradle-enterprise.elastic.co/s/2jrqszvkajhiw/tests/:qa:os:destructiveDistroTest.default-linux-archive/org.elasticsearch.packaging.test.ArchiveGenerateInitialPasswordTests/test50VerifyAutogeneratedCredentials

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.ArchiveGenerateInitialPasswordTests&tests.test=test50VerifyAutogeneratedCredentials

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <2>
     but: was <0>

  at __randomizedtesting.SeedInfo.seed([38D37D63EC2D9FF5:200079D521ABAA55]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.packaging.test.ArchiveGenerateInitialPasswordTests.test50VerifyAutogeneratedCredentials(ArchiveGenerateInitialPasswordTests.java:89)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by stu-elastic** [comment]
Looks like we're still having issues with this test: https://gradle-enterprise.elastic.co/s/cf4eggz4upmkc

**Comment by jkakavas** [comment]
Yes, the 10sec delay I aded in #77605 doesn't seem to be enough in all cases. I'll work on a more foolproof fix

**Comment by DaveCTurner** [comment]
I saw a bunch more failures of this test so I muted it in 170e4a9a1882c07ed008e2b288f1a2585ed2b299.

**Comment by jkakavas** [comment]
Closing this in favor of https://github.com/elastic/elasticsearch/issues/84407
