### ISSUE TITLE
[CI] ArchiveGenerateInitialPasswordTests test60PasswordAutogenerationOnlyOnce failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#77796]
**Build scan:**
https://gradle-enterprise.elastic.co/s/2zuqi3d4tqg2g/tests/:qa:os:destructiveDistroTest.default-linux-archive/org.elasticsearch.packaging.test.ArchiveGenerateInitialPasswordTests/test60PasswordAutogenerationOnlyOnce

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try. A few of us saw the same failure on PR builds and concluded it probably wasn't us, although strangely it only seems to have affected PR builds.

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.ArchiveGenerateInitialPasswordTests&tests.test=test60PasswordAutogenerationOnlyOnce

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: is <true>
     but: was <false>

  at __randomizedtesting.SeedInfo.seed([21C45DF24A8CA65A:B01E8ADE62032FC4]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.packaging.test.ArchiveGenerateInitialPasswordTests.test60PasswordAutogenerationOnlyOnce(ArchiveGenerateInitialPasswordTests.java:105)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by jkakavas** [comment]
Closing this as a duplicate of https://github.com/elastic/elasticsearch/issues/77621. Working on a solution for the whole class
