### ISSUE TITLE
[CI] WatcherUtilsTests testSerializeSearchRequest failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#78035]
Didn't reproduce but this has failed 12 times in the past week so I think there's definitely something up. Looks to be specific to `master`

**Build scan:**
https://gradle-enterprise.elastic.co/s/5xlsqazi26hns/tests/:x-pack:plugin:watcher:test/org.elasticsearch.xpack.watcher.support.WatcherUtilsTests/testSerializeSearchRequest

**Reproduction line:**
`./gradlew ':x-pack:plugin:watcher:test' --tests "org.elasticsearch.xpack.watcher.support.WatcherUtilsTests.testSerializeSearchRequest" -Dtests.seed=77B8557950BD0018 -Dtests.locale=ar-SA -Dtests.timezone=Antarctica/McMurdo -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.watcher.support.WatcherUtilsTests&tests.test=testSerializeSearchRequest

**Failure excerpt:**
```
java.lang.AssertionError: unexpected warning headers
Expected: an empty collection
     but: <[299 Elasticsearch-8.0.0-SNAPSHOT-63521b4cc2e643cb868e448148d763029aa6d44d "Deprecated field [ignore_throttled] used, this field is unused and will be removed entirely"]>

  at __randomizedtesting.SeedInfo.seed([77B8557950BD0018:30EFF250F63EBF5B]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.elasticsearch.test.ESTestCase.ensureNoWarnings(ESTestCase.java:414)
  at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:385)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by tvernum** [comment]
This reproduces locally for me:
```
./gradlew ':x-pack:plugin:watcher:test' \
  --tests "org.elasticsearch.xpack.watcher.support.WatcherUtilsTests.testSerializeSearchRequest" \
  -Dtests.seed=404523440417732B -Dtests.locale=zh-Hans-SG \
  -Dtests.timezone=America/Paramaribo -Druntime.java=11
```
running against 8d3f78126c7e8e9194c1879720fd3368fb5ab03a

-  uname: `Darwin tv-e-co.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64`
- Java16: `AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)`
- Java11: `AdoptOpenJDK (build 11.0.6+10)`

**Comment by tvernum** [comment]
The deserialize test is also failing (`testDeserializeSearchRequest`)
```
./gradlew ':x-pack:plugin:watcher:test' --tests "org.elasticsearch.xpack.watcher.support.WatcherUtilsTests.testDeserializeSearchRequest" -Dtests.seed=2FF83109E55E0EC5 -Dtests.locale=pt-BR -Dtests.timezone=Australia/North -Druntime.java=11
```

I'm going to mute both tests methods on master.

**Comment by martijnvg** [comment]
This my fault and related to #77479. Unfortunately local and pr ci test runs didn't catch this...
