### ISSUE TITLE
Test framework unit test failures on 6.8 when run on Java 17

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#78279]
We have a couple of unit tests in our test framework project failing on Java 17 due to access violations: https://gradle-enterprise.elastic.co/s/cq25zgsh6kyzq/console-log?task=:test:framework:unitTest

```
   > Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2a48d10f
   > 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
   > 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
   > 	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
   > 	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
   > 	at org.mockito.cglib.core.ReflectUtils$2.run(ReflectUtils.java:69)
   > 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
   > 	at org.mockito.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:59)
   > 	... 56 more
```

cc @rjernst looks like we might need to tweak default jvm args here?

**Comment by rjernst** [comment]
@mark-vieira I can look into it, but is this really Java 17? The repro line says 13?

```
./gradlew ':test:framework:unitTest' -Dtests.seed=8C95F0E86525B415 -Dtests.class=org.elasticsearch.test.rest.yaml.section.TransformAndSetSectionTests -Dtests.method="testTransformation" -Dtests.security.manager=true -Dtests.locale=en-VI -Dtests.timezone=America/Port-au-Prince -Dcompiler.java=11 -Druntime.java=13
```

**Comment by mark-vieira** [comment]
Ug, yes, this continues to come up. 6.8 is a super old version of Gradle that way predates Java 17 so it incorrectly reports as the latest version it knew of at the time... 13 :facepalm:

**Comment by rjernst** [comment]
We added appropriate opens a couple months ago in 7.x/master, but didn't do it for 6.8, see #72588. I've opened https://github.com/elastic/elasticsearch/pull/78283 to backport it there now.

**Comment by mark-vieira** [comment]
Thanks, Ryan!

**Comment by rjernst** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/78283
