### ISSUE TITLE
[CI] LongScriptFieldTypeTests testNow failing

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#78315]
**Build scan:**
https://gradle-enterprise.elastic.co/s/gm3mgt56cw26e/tests/:server:test/org.elasticsearch.index.mapper.LongScriptFieldTypeTests/testNow

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.index.mapper.LongScriptFieldTypeTests.testNow" -Dtests.seed=E319CC5B4F2EADC5 -Dtests.locale=th -Dtests.timezone=Greenwich -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.index.mapper.LongScriptFieldTypeTests&tests.test=testNow

**Failure excerpt:**
```
java.lang.NullPointerException: (No message provided)

  at __randomizedtesting.SeedInfo.seed([E319CC5B4F2EADC5:7E10B7AAC59030A9]:0)
  at java.util.TreeMap.getEntry(TreeMap.java:345)
  at java.util.TreeMap.get(TreeMap.java:277)
  at org.apache.lucene.index.ParallelLeafReader.getPointValues(ParallelLeafReader.java:384)
  at org.apache.lucene.search.comparators.NumericComparator$NumericLeafComparator.<init>(NumericComparator.java:92)
  at org.apache.lucene.search.comparators.LongComparator$LongLeafComparator.<init>(LongComparator.java:65)
  at org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource$1$1.<init>(LongValuesComparatorSource.java:96)
  at org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource$1.getLeafComparator(LongValuesComparatorSource.java:96)
  at org.apache.lucene.search.FieldValueHitQueue.getComparators(FieldValueHitQueue.java:176)
  at org.apache.lucene.search.TopFieldCollector$TopFieldLeafCollector.<init>(TopFieldCollector.java:64)
  at org.apache.lucene.search.TopFieldCollector$SimpleFieldCollector$1.<init>(TopFieldCollector.java:196)
  at org.apache.lucene.search.TopFieldCollector$SimpleFieldCollector.getLeafCollector(TopFieldCollector.java:196)
  at org.apache.lucene.search.FilterCollector.getLeafCollector(FilterCollector.java:38)
  at org.apache.lucene.search.AssertingCollector.getLeafCollector(AssertingCollector.java:45)
  at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:745)
  at org.apache.lucene.search.AssertingIndexSearcher.search(AssertingIndexSearcher.java:73)
  at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:679)
  at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:673)
  at org.apache.lucene.search.IndexSearcher.searchAfter(IndexSearcher.java:653)
  at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:570)
  at org.elasticsearch.index.mapper.LongScriptFieldTypeTests.testNow(LongScriptFieldTypeTests.java:137)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by ywangd** [comment]
Another one failed on my PR and reproducible: https://gradle-enterprise.elastic.co/s/352yyhir3v2ko/tests/:server:test/org.elasticsearch.index.mapper.LongScriptFieldTypeTests/testNow?top-execution=1

**Comment by astefan** [comment]
Another fresh failure today: https://gradle-enterprise.elastic.co/s/eakcv4h7kffua
