### ISSUE TITLE
[CI] PruneChangelogsTaskTests findAndDeleteFiles_withFilesToDeleteButDeleteFails_throwsException failing

### ISSUE THREAD

**Issue by hendrikmuhs** [elastic/elasticsearch#78318]
**Build scan:**
https://gradle-enterprise.elastic.co/s/luvjtmfzabv2q/tests/:test/org.elasticsearch.gradle.internal.release.PruneChangelogsTaskTests/findAndDeleteFiles_withFilesToDeleteButDeleteFails_throwsException

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.gradle.internal.release.PruneChangelogsTaskTests&tests.test=findAndDeleteFiles_withFilesToDeleteButDeleteFails_throwsException

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: "Failed to delete some files:\n\n\tdocs/changelog/1234.yml\n"
     but: was "Failed to delete some files:\n\n\tdocs\\changelog\\1234.yml\n"

  at __randomizedtesting.SeedInfo.seed([758ABC1E6031364A:86FEF6E946D7F36F]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
  at org.junit.Assert.assertThat(Assert.java:964)
  at org.junit.Assert.assertThat(Assert.java:930)
  at org.elasticsearch.gradle.internal.release.PruneChangelogsTaskTests.findAndDeleteFiles_withFilesToDeleteButDeleteFails_throwsException(PruneChangelogsTaskTests.java:201)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:567)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$2.evaluate(ThreadLeakControl.java:411)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSuite(RandomizedRunner.java:716)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.access$200(RandomizedRunner.java:138)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:637)

```

**Comment by hendrikmuhs** [comment]
fails on several windows CI's:

https://gradle-enterprise.elastic.co/s/sbchjk7skdgvg
https://gradle-enterprise.elastic.co/s/wkfnrc3wuzxtu

**Comment by mark-vieira** [comment]
This certainly looks like line ending normalization issues parsing output from `git` on Windows. For now I've muted this test on `master` and `7.x` when running on Windows.

**Comment by pugnascotia** [comment]
Bah, how have I only just noticed this? I'll prep a fix.
