### ISSUE TITLE
[CI] Backwards compatibility tests in x-pack:qa:mixed-tier-cluster failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#78360]
In the past 12 hours there have been a large number of build failures as the older nodes in `x-pack:qa:mixed-tier-cluster` do not seem to be correctly set up.

Perhaps relates to #78312

Build scan: https://gradle-enterprise.elastic.co/s/j4bckkcqk3jvc

```
[2021-09-28T06:12:43,636][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v7.9.1-1] uncaught exception in thread [main] |  
-- | --
  | »  org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown role [data_content] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:174) ~[elasticsearch-7.9.1.jar:7.9.1] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161) ~[elasticsearch-7.9.1.jar:7.9.1] |  
  | »  	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.9.1.jar:7.9.1] |  
  | »  	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127) ~[elasticsearch-cli-7.9.1.jar:7.9.1] |  
  | »  	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.9.1.jar:7.9.1] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126) ~[elasticsearch-7.9.1.jar:7.9.1] |  
  | »  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.9.1.jar:7.9.1]
```

**Comment by breskeby** [comment]
@ywelsch that is likely related. working on a fix

**Comment by breskeby** [comment]
PR raised at https://github.com/elastic/elasticsearch/pull/78365 auto-merged when passing CI jobs

**Comment by mark-vieira** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/78365
