### ISSUE TITLE
[CI] ArchiveGenerateInitialCredentialsTests test40VerifyAutogeneratedCredentials failing

### ISSUE THREAD

**Issue by masseyke** [elastic/elasticsearch#78557]
Fails with:
{noformat}
    Expected: not null
         but: was null
        at __randomizedtesting.SeedInfo.seed([A2D202C51290C728:6C77C4AA99A2F0AB]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.packaging.test.ArchiveGenerateInitialCredentialsTests.test40VerifyAutogeneratedCredentials(ArchiveGenerateInitialCredentialsTests.java:87)
{noformat}

**Build scan:**
https://gradle-enterprise.elastic.co/s/i22zdhl7jp3mc/tests/:qa:os:destructiveDistroTest.default-linux-archive/org.elasticsearch.packaging.test.ArchiveGenerateInitialCredentialsTests/test40VerifyAutogeneratedCredentials

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.ArchiveGenerateInitialCredentialsTests&tests.test=test40VerifyAutogeneratedCredentials

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: not null
     but: was null

  at __randomizedtesting.SeedInfo.seed([5BAE149FFD932B1C:950BD2F076A11C9F]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.packaging.test.ArchiveGenerateInitialCredentialsTests.test40VerifyAutogeneratedCredentials(ArchiveGenerateInitialCredentialsTests.java:87)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by grcevski** [comment]
I can see this particular test was added just recently here: https://github.com/elastic/elasticsearch/pull/78293. Any ideas @jkakavas? Thanks!

**Comment by jkakavas** [comment]
Yes, I un-muted this erroneously in that PR. The problem is tracked in https://github.com/elastic/elasticsearch/issues/77621 and it's because we need to check the output of running elasticsearch but sometimes we check too early and elasticsearch hasn't printed the lines yet. I'll mute again and work on a fix

**Comment by jkakavas** [comment]
Closing this in favor of https://github.com/elastic/elasticsearch/issues/77621 so that we can keep track of the test issues with this class in one place. I'm working on a fix for all the tests in this class
