### ISSUE TITLE
[CI] RecoveryStatusTests testRenameTempFiles failing

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#78698]
All tests seem to have failed due to a NPE at ESSingleNodeTestCase.java:255 (NODE==null?).

**Build scan:**
https://gradle-enterprise.elastic.co/s/izgbs6mtssewo/tests/:server:test/org.elasticsearch.indices.recovery.RecoveryStatusTests/testRenameTempFiles

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.indices.recovery.RecoveryStatusTests.testRenameTempFiles" -Dtests.seed=B9687578CE124CA1 -Dtests.locale=sr-CS -Dtests.timezone=Europe/Madrid -Druntime.java=8`

**Applicable branches:**
7.x

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.indices.recovery.RecoveryStatusTests&tests.test=testRenameTempFiles

**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at org.elasticsearch.monitor.os.OsProbe.readProcSelfCgroup(OsProbe.java:298)
  at org.elasticsearch.monitor.os.OsProbe.areCgroupStatsAvailable(OsProbe.java:579)
  at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:637)
  at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:857)
  at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:864)
  at org.elasticsearch.monitor.os.OsService.<init>(OsService.java:39)
  at org.elasticsearch.monitor.MonitorService.<init>(MonitorService.java:33)
  at org.elasticsearch.node.Node.<init>(Node.java:509)
  at org.elasticsearch.node.MockNode.<init>(MockNode.java:89)
  at org.elasticsearch.node.MockNode.<init>(MockNode.java:79)
  at org.elasticsearch.node.MockNode.<init>(MockNode.java:71)
  at org.elasticsearch.test.ESSingleNodeTestCase.newNode(ESSingleNodeTestCase.java:242)
  at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:187)
  at com.carrotsearch.randomizedtesting.RandomizedContext.runWithPrivateRandomness(RandomizedContext.java:211)
  at org.elasticsearch.test.ESSingleNodeTestCase.startNode(ESSingleNodeTestCase.java:79)
  at org.elasticsearch.test.ESSingleNodeTestCase.setUp(ESSingleNodeTestCase.java:118)
  at sun.reflect.GeneratedMethodAccessor4.invoke(null:-1)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:972)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by fcofdez** [comment]
I think this is unrelated to this test and it's an environmental problem (in the linked build there are ~400 test failures), the problem seems to be that `/proc/self/cgroup` is empty, maybe cgroups is not enabled in oracle linux?
