### ISSUE TITLE
XPackRestIT.test {p0=data_stream/150_tsdb/created the data stream} failure

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#78726]
**Build scan**:
https://gradle-enterprise.elastic.co/s/x3cpwn62cohwo/console-log?task=:x-pack:plugin:yamlRestTest

**Repro line**:
```./gradlew ':x-pack:plugin:yamlRestTest' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=data_stream/150_tsdb/created the data stream}" -Dtests.seed=6DECEBDBBE6C1E1E -Dtests.locale=ar-EG -Dtests.timezone=Australia/LHI -Druntime.java=11```

**Reproduces locally?**:
Yes

**Applicable branches**:
master

**Failure history**:
None that I could find

**Failure excerpt**:
```
        Caused by:
        java.lang.AssertionError: got unexpected warning header [
                299 Elasticsearch-8.0.0-SNAPSHOT-e5af31678f40e85434d7ecd6c411e28942221360 "index template [my-template1] has index patterns [k8s*] matching patterns from existing older templates [global] with patterns (global => [*]); this template [my-template1] will take precedence during new index creation"
        ]
            at org.junit.Assert.fail(Assert.java:88)
            at org.elasticsearch.test.rest.yaml.section.DoSection.checkWarningHeaders(DoSection.java:461)
            at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:349)
            at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:444)
```

**Comment by astefan** [comment]
Another failure today: https://gradle-enterprise.elastic.co/s/dhbvi2ny5rtjw

**Comment by mayya-sharipova** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/2uuobcqggsxk4

**Comment by nik9000** [comment]
Copy and paste error on the name of the template and terrible luck it not failing during the PR. Sorry for the noise friends!
