### ISSUE TITLE
[CI] HttpExporterResourceTests.testTemplateCheckBlocksAfterSuccessfulVersion failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#78736]
**Build scan**: https://gradle-enterprise.elastic.co/s/7646snlf6bvis

**Repro line**: `./gradlew ':x-pack:plugin:monitoring:test' --tests "org.elasticsearch.xpack.monitoring.exporter.http.HttpExporterResourceTests.testTemplateCheckBlocksAfterSuccessfulVersion" -Dtests.seed=11AFA8263009B917 -Dtests.locale=es-HN -Dtests.timezone=Europe/Vatican -Druntime.java=11 -Dtests.fips.enabled=true`

**Reproduces locally?**:

**Applicable branches**: master

**Failure history**: seems to have started yesterday:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:testTemplateCheckBlocksAfterSuccessfulVersion),sort:!(process.time-start,desc))

**Failure excerpt**:

```
org.elasticsearch.xpack.monitoring.exporter.http.HttpExporterResourceTests > testTemplateCheckBlocksAfterSuccessfulVersion FAILED
    org.mockito.exceptions.verification.NeverWantedButInvoked: 
    actionListener.onResponse(<any>);
    Never wanted here:
    -> at org.elasticsearch.xpack.monitoring.exporter.http.AbstractPublishableHttpResourceTestCase.verifyPublishListener(AbstractPublishableHttpResourceTestCase.java:454)
    But invoked here:
    -> at org.elasticsearch.xpack.monitoring.exporter.http.VersionHttpResource.doCheckAndPublish(VersionHttpResource.java:62)
        at __randomizedtesting.SeedInfo.seed([11AFA8263009B917:DA8932FB706B7A11]:0)
        at app//org.elasticsearch.xpack.monitoring.exporter.http.AbstractPublishableHttpResourceTestCase.verifyPublishListener(AbstractPublishableHttpResourceTestCase.java:454)
        at app//org.elasticsearch.xpack.monitoring.exporter.http.HttpExporterResourceTests.awaitCheckAndPublish(HttpExporterResourceTests.java:103)
        at app//org.elasticsearch.xpack.monitoring.exporter.http.HttpExporterResourceTests.testTemplateCheckBlocksAfterSuccessfulVersion(HttpExporterResourceTests.java:175)
```

**Comment by astefan** [comment]
Failed multiple times today. Muted with https://github.com/elastic/elasticsearch/pull/78749.
