### ISSUE TITLE
LocalIndicesCleanerTests. testDeleteIndices failures in CI

### ISSUE THREAD

**Issue by gwbrown** [elastic/elasticsearch#78862]
**Build scan**: [scan](https://gradle-enterprise.elastic.co/s/352shig3xez3w/tests/:x-pack:plugin:monitoring:test/org.elasticsearch.xpack.monitoring.cleaner.local.LocalIndicesCleanerTests/testDeleteIndices?top-execution=1)

**Repro line**: `./gradlew ':x-pack:plugin:monitoring:test' --tests "org.elasticsearch.xpack.monitoring.cleaner.local.LocalIndicesCleanerTests.testDeleteIndices" -Dtests.seed=9B896DFE5953A195 -Dtests.locale=el-CY -Dtests.timezone=Asia/Kuching -Druntime.java=11`

**Reproduces locally?**: No

**Applicable branches**: `master`

**Failure history**: [20 failures in Gradle Enterprise](https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=America/Denver&tests.container=org.elasticsearch.xpack.monitoring.cleaner.local.LocalIndicesCleanerTests&tests.sortField=FAILED&tests.test=testDeleteIndices&tests.unstableOnly=true)

**Failure excerpt**:
```
java.lang.AssertionError: 	
	Expected: is <true>	
	     but: was <false>	

		at __randomizedtesting.SeedInfo.seed([9B896DFE5953A195:4730C978834C3934]:0)	
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)	
		at org.junit.Assert.assertThat(Assert.java:956)	
		at org.junit.Assert.assertThat(Assert.java:923)	
		at org.elasticsearch.xpack.monitoring.cleaner.AbstractIndicesCleanerTestCase.lambda$getListener$0(AbstractIndicesCleanerTestCase.java:170)	
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:985)	
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:958)	
		at org.elasticsearch.xpack.monitoring.cleaner.AbstractIndicesCleanerTestCase.getListener(AbstractIndicesCleanerTestCase.java:170)	
		at org.elasticsearch.xpack.monitoring.cleaner.AbstractIndicesCleanerTestCase.testDeleteIndices(AbstractIndicesCleanerTestCase.java:111)	
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
		at java.lang.reflect.Method.invoke(Method.java:566)	
		at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)	
		at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)	
		at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)	
		at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)	
		at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
		at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)	
		at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)	
		at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)	
		at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)	
		at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)	
		at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
		at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)	
		at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)	
		at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)	
		at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)	
		at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)	
		at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)	
		at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)	
		at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)	
		at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
		at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)	
		at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)	
		at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)	
		at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
		at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
		at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)	
		at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)	
		at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)	
		at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)	
		at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)	
		at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
		at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)	
		at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)	
		at java.lang.Thread.run(Thread.java:834)
```

**Comment by hendrikmuhs** [comment]
create a mute PR: https://github.com/elastic/elasticsearch/pull/78973

(seems to only fail for master)
