### ISSUE TITLE
[CI] GeoIpDownloaderIT testStartWithNoDatabases failing

### ISSUE THREAD

**Issue by jrodewig** [elastic/elasticsearch#79074]
**Build scan:**
https://gradle-enterprise.elastic.co/s/uhhnoantetlfq/tests/:modules:ingest-geoip:internalClusterTest/org.elasticsearch.ingest.geoip.GeoIpDownloaderIT/testStartWithNoDatabases

**Reproduction line:**
`./gradlew ':modules:ingest-geoip:internalClusterTest' --tests "org.elasticsearch.ingest.geoip.GeoIpDownloaderIT.testStartWithNoDatabases" -Dtests.seed=976EEDC6532D0E7E -Dtests.locale=es-HN -Dtests.timezone=America/Thunder_Bay -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.ingest.geoip.GeoIpDownloaderIT&tests.test=testStartWithNoDatabases

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: map containing ["tags"-><[_geoip_database_unavailable_GeoLite2-City.mmdb, _geoip_database_unavailable_GeoLite2-Country.mmdb, _geoip_database_unavailable_GeoLite2-ASN.mmdb]>]
     but: map was [<_id=_id>, <ip-asn={ip=89.160.20.128, organization_name=Bredband2 AB, asn=29518, network=89.160.0.0/17}>, <_index=my-index>, <ip-city={continent_name=Europe, region_iso_code=SE-AB, city_name=Tumba, country_iso_code=SE, country_name=Sweden, region_name=Stockholm, location={lon=17.8167, lat=59.2}}>, <ip-country={continent_name=Europe, country_iso_code=SE, country_name=Sweden}>, <ip=89.160.20.128>]

  at __randomizedtesting.SeedInfo.seed([976EEDC6532D0E7E:5AD1C00E49EC69D]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.ingest.geoip.GeoIpDownloaderIT.testStartWithNoDatabases(GeoIpDownloaderIT.java:324)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by martijnvg** [comment]
Sorry about the noise. I recently added this test in a change that went only in master. I will fix this.

**Comment by danhermann** [comment]
> @danhermann I think so. Can you mute this test?

Yes, muting in https://github.com/elastic/elasticsearch/pull/79089

**Comment by DaveCTurner** [comment]
I had a failure of `GeoIpDownloaderCliIT#testStartWithNoDatabases` in https://gradle-enterprise.elastic.co/s/6ln3sxuv2ohhm, I'm assuming it's related to this rather than a separate thing so just linking it here.

**Comment by DaveCTurner** [comment]
Failed for me on a PR build here: https://gradle-enterprise.elastic.co/s/miosturet4dp4

**Comment by martijnvg** [comment]
I looked into this failure and this instance the simulate pipeline api was repeatedly executed on a coordinating only node. The databases are only loaded on nodes with ingest role, this causes the geoip lookup never to happen. The simulate pipeline api always executes on the first node it hits, I think we should change that (redirect to a node with ingest role instead, or wait until we drop the ingest role...). For now, I will adjust the test to not hit a coordinating only node.

Note that this isn't an issue for bulk/index api (if an ingest pipeline is used the these APIs always redirect to a node with an ingest role).

**Comment by martijnvg** [comment]
Muting this test now. My latest tweak to the test, apparently made things worse.

**Comment by martijnvg** [comment]
The test hasn't failed, since 4db5fc5296631839be07da1879e66a8b9f4074cc has been pushed. Closing it for now, if this test fails again then this issue can re-opened or a new issue can be opened.
