### ISSUE TITLE
[CI] BitArrayTests testVeryLarge failing

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#79567]
Started failing since yesterday on 7.x branch with OutOfMemoryError.

Are there perhaps build-related changes that could explain this?

**Build scan:**
https://gradle-enterprise.elastic.co/s/ahgtxf7bdya7m/tests/:server:test/org.elasticsearch.common.util.BitArrayTests/testVeryLarge

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.common.util.BitArrayTests.testVeryLarge" -Dtests.seed=417736DD4B53ADE5 -Dtests.locale=zh-HK -Dtests.timezone=Pacific/Guadalcanal -Druntime.java=11`

**Applicable branches:**
7.x

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.common.util.BitArrayTests&tests.test=testVeryLarge

**Failure excerpt:**
```
java.lang.OutOfMemoryError: Java heap space

  at __randomizedtesting.SeedInfo.seed([417736DD4B53ADE5:481BCFFA18A0C7B0]:0)
  at org.elasticsearch.common.util.AbstractBigArray.newLongPage(AbstractBigArray.java:127)
  at org.elasticsearch.common.util.BigLongArray.<init>(BigLongArray.java:34)
  at org.elasticsearch.common.util.BigArrays.newLongArray(BigArrays.java:606)
  at org.elasticsearch.common.util.BigArrays.resize(BigArrays.java:629)
  at org.elasticsearch.common.util.BigArrays.grow(BigArrays.java:645)
  at org.elasticsearch.common.util.BitArray.set(BitArray.java:38)
  at org.elasticsearch.common.util.BitArrayTests.testVeryLarge(BitArrayTests.java:55)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)

```

**Comment by mark-vieira** [comment]
While trying to find out where Mockito is coming from to begin with I discovered https://github.com/elastic/securemock, which I was never aware even existed, and it seems we bundle the ancient version of Mockito in that library, which also hasn't been touched in 6 years.

@rjernst Any intention of using testing libraries released _after_ our kids were born in the immediate future? I can't believe this stuff even _works_ on Java 17.
