### ISSUE TITLE
[CI] FeatureMigrationIT testMigrateInternalManagedSystemIndex failing

### ISSUE THREAD

**Issue by fcofdez** [elastic/elasticsearch#79620]
**Build scan:**
https://gradle-enterprise.elastic.co/s/ehqtual4h3pr4/tests/:modules:reindex:internalClusterTest/org.elasticsearch.migration.FeatureMigrationIT/testMigrateInternalManagedSystemIndex

**Reproduction line:**
`./gradlew ':modules:reindex:internalClusterTest' --tests "org.elasticsearch.migration.FeatureMigrationIT.testMigrateInternalManagedSystemIndex" -Dtests.seed=D307C9C39AD2B347 -Dtests.locale=ar-DZ -Dtests.timezone=Africa/Dakar -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.migration.FeatureMigrationIT&tests.test=testMigrateInternalManagedSystemIndex

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <NO_MIGRATION_NEEDED>
     but: was <IN_PROGRESS>

  at __randomizedtesting.SeedInfo.seed([D307C9C39AD2B347:8CA5A65ADC26C455]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.migration.FeatureMigrationIT.lambda$testMigrateInternalManagedSystemIndex$2(FeatureMigrationIT.java:149)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:993)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:966)
  at org.elasticsearch.migration.FeatureMigrationIT.testMigrateInternalManagedSystemIndex(FeatureMigrationIT.java:145)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by williamrandolph** [comment]
These are some fairly new system index tests. It looks like we have some race conditions. We fixed one known race condition (https://github.com/elastic/elasticsearch/pull/80049) today, so there's a chance we caught this failure... but if this fails again, I will be happy to mute.

**Comment by droberts195** [comment]
This test failed again today in https://gradle-enterprise.elastic.co/s/yhh5s2f2w753e/tests/:modules:reindex:internalClusterTest/org.elasticsearch.migration.MultiFeatureMigrationIT/testMigrateInternalManagedSystemIndex?top-execution=1

But the failure was an NPE in the test code:

```
java.lang.NullPointerException: (No message provided)
		at __randomizedtesting.SeedInfo.seed([B5E72155117BF2FF:EA454ECC578F85ED]:0)
		at org.elasticsearch.migration.FeatureMigrationIT.assertIndexHasCorrectProperties(FeatureMigrationIT.java:292)	
		at org.elasticsearch.migration.FeatureMigrationIT.testMigrateInternalManagedSystemIndex(FeatureMigrationIT.java:236)
```

Even if it's hard to fix the race conditions it's probably worth making the test code more robust so that it gives clear error messages instead of NPEs.

**Comment by pugnascotia** [comment]
Another NPE in https://gradle-enterprise.elastic.co/s/n7pfqmblv5lra

**Comment by gwbrown** [comment]
It was not immediately obvious what was causing the NPE as nothing in that chain of calls should be null, per my understanding. I've opened https://github.com/elastic/elasticsearch/pull/82497 to check if each part is null individually, which should hopefully help track this down.

**Comment by williamrandolph** [comment]
Looks like we had this failure again last week: https://gradle-enterprise.elastic.co/s/3xvjmnz7rkg34/tests/:modules:reindex:internalClusterTest/org.elasticsearch.migration.FeatureMigrationIT/testMigrateInternalManagedSystemIndex

**Comment by williamrandolph** [comment]
It looks like the test failed because the migration took about twenty-five seconds. The `assertBusy` loop needs the operation to finish within ten seconds.

```
[2022-03-04T18:04:26,861][INFO ][o.e.u.SystemIndexMigrator] [node_s2] preparing to migrate old index [.ext-man-old] from feature [A-test-feature] to new index [.ext-man-old-reindexed-for-8]	
[2022-03-04T18:04:26,869][INFO ][o.e.m.FeatureMigrationIT ] [testMigrateInternalManagedSystemIndex] {"features":[{"feature_name":"A-test-feature","minimum_index_version":"7.0.0","migration_status":"MIGRATION_NEEDED","indices":[{"index":".ext-man-old","version":"7.0.0"},{"index":".ext-unman-old","version":"7.0.0"},{"index":".int-man-old","version":"7.0.0"},{"index":".int-unman-old","version":"7.0.0"}]},

[...]

[2022-03-04T18:04:49,318][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_s2] [.int-unman-old/W7PiJ_rEQZWvPjo7d52ezg] deleting index	
[2022-03-04T18:04:50,013][INFO ][o.e.u.SystemIndexMigrator] [node_s2] finished migrating old index [.int-unman-old] from feature [A-test-feature] to new index [.int-unman-old-reindexed-for-8]	
[2022-03-04T18:04:50,467][INFO ][o.e.u.SystemIndexMigrator] [node_s2] finished migrating feature indices
```

Normal execution should happen much more quickly. My system can run the whole test in under eight seconds, and in particular gets through that block of code in about one second.

We could try to mitigate this by boosting the timeout, though that is usually just a way to delay having to deal with a problem. There's evidence of a slowdown just earlier in the logs:

```
[2022-03-04T18:04:09,833][WARN ][o.e.t.n.MockNioTransport ] [node_s2] Slow execution on network thread [331 milliseconds]	
java.lang.RuntimeException: Slow execution on network thread	
	at org.elasticsearch.transport.nio.MockNioTransport$TransportThreadWatchdog.maybeLogElapsedTime(MockNioTransport.java:459) [framework-8.0.2-SNAPSHOT.jar:8.0.2-SNAPSHOT]	
	at org.elasticsearch.transport.nio.MockNioTransport$TransportThreadWatchdog.unregister(MockNioTransport.java:450) [framework-8.0.2-SNAPSHOT.jar:8.0.2-SNAPSHOT]	
	at org.elasticsearch.transport.nio.TestEventHandler.handleRead(TestEventHandler.java:146) [framework-8.0.2-SNAPSHOT.jar:8.0.2-SNAPSHOT]	
	at org.elasticsearch.nio.NioSelector.handleRead(NioSelector.java:415) [elasticsearch-nio-8.0.2-SNAPSHOT.jar:8.0.2-SNAPSHOT]	
	at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:241) [elasticsearch-nio-8.0.2-SNAPSHOT.jar:8.0.2-SNAPSHOT]	
	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:168) [elasticsearch-nio-8.0.2-SNAPSHOT.jar:8.0.2-SNAPSHOT]	
	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:125) [elasticsearch-nio-8.0.2-SNAPSHOT.jar:8.0.2-SNAPSHOT]	
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by droberts195** [comment]
@williamrandolph check out the performance tab in the Gradle scan.  CI runs 16 test suites in parallel, and if several heavyweight tests end up running at the same time things can really thrash and grind to a halt.  So it really could just be a case of needing to up the timeout.  There's an example of this in https://github.com/elastic/elasticsearch/issues/84290#issuecomment-1059016371.
