### ISSUE TITLE
ES Index Out of Bounds Exception when Querying

### ISSUE THREAD

**Issue by marcreichman** [elastic/elasticsearch#79658]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.9.2, 7.15.1

**Plugins installed**: None

**JVM version** (`java -version`): Built-in with RPM (for both versions)

**OS version** (`uname -a` if on a Unix-like system): CentOS 7, `Linux localhost 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Description**:

# ES Index Out of Bounds Exception when Querying

We have a system that involves heavily nested data that includes possible (partially) repeated items on lower levels.  We have a 
query that counts (or sums) specific fields for the nested lower level data and compares the resulting value to a threshold to determine whether the document itself matches.  This query sometimes returns incorrect results or even blows up with an exception. We believe this to be a bug within Elasticsearch or Lucene.  

A simplified version of the query is illustrated below.  We use a match phrase query to choose the specific fields and use a constant score query with a value of 1 (for the counting case) for a score, and use a scoring mode of `sum` in the nested query to find the number of matches.  We then use a script with a `min_score` equal to threshold results so we only find counts exceeding the threshold.

This query usually works fine, but when the match phrase query is long we either:

1. Get an exception from ES with the message:
```
ElasticsearchException[Elasticsearch exception [type=index_out_of_bounds_exception, reason=index_out_of_bounds_exception: null]]
com.pfi.trex.enterprisemanager.search.es.control.ESSearchException: Search Failure  (0) ElasticsearchException[Elasticsearch exception [type=index_out_of_bounds_exception, reason=index_out_of_bounds_exception: null]]
```

2. Get inconsistent results where the results are either not found or only partial results are returned.

If we use a lower level query different from a match phrase query (e.g. a `match` query, or a `wildcard` query or a `fuzzy` match), then results are returned as expected.  Also (oddly) if we run the match phrase query with `profiling` set to `true`, it does return the expected results.

We have found this on a `7.9.2` version of Elasticsearch but have reproduced it on a system using `7.15.1` as well. We have seen this on a number of systems of various sizes. Nodes all run on Linux, typically CentOS 7 with the RPM distribution from Elastic.

In the following, we give (1) the stack trace that results from the index out of bounds exception, and then (2) provide a simplified example that shows the inconsistent results.

We only see the stack trace on a larger system with many items, but the simpified case at least shows that the query is not functioning properly.  The simplified query that we give below gives the same stack trace when run against a fully populated system.  The `size` or the `from` and `size` fields sometimes need adjustment in order to trigger the stack trace, depending upon the system.  Using a `size` of `0` also triggers the stack trace on the populated systems.

----------------------------------------------------------------

The Stack Trace (from a development system with log level debug):

```
[2021-10-14T13:15:24,068][INFO ][o.e.m.j.JvmGcMonitorService] [martyes] [gc][1892293] overhead, spent [261ms] collecting in the last [1s]
[2021-10-14T15:42:19,895][WARN ][r.suppressed             ] [martyes] path: /transitextmeta/_search, params: {typed_keys=true, max_concurrent_shard_requests=36, ignore_unavailable=false, expand_wildcards=open, allow_no_indices=true, ignore_throttled=true, index=transitextmeta, search_type=query_then_fetch, batched_reduce_size=512, ccs_minimize_roundtrips=true}
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:551) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:309) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:582) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:393) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$100(AbstractSearchAsyncAction.java:68) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:245) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:59) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:403) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.transport.TransportService$6.handleException(TransportService.java:638) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1172) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.transport.InboundHandler.lambda$handleException$2(InboundHandler.java:235) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:226) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.transport.InboundHandler.handleException(InboundHandler.java:233) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:225) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:115) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:78) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:692) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82) [elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:76) [transport-netty4-client-7.9.2.jar:7.9.2]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271) [netty-handler-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: index_out_of_bounds_exception: null
	at java.nio.Buffer.checkIndex(Buffer.java:744) ~[?:?]
	at java.nio.DirectByteBuffer.getLong(DirectByteBuffer.java:920) ~[?:?]
	at org.apache.lucene.store.ByteBufferGuard.getLong(ByteBufferGuard.java:134) ~[lucene-core-8.6.2.jar:8.6.2 016993b65e393b58246d54e8ddda9f56a453eb0e - ivera - 2020-08-26 10:53:36]
	at org.apache.lucene.store.ByteBufferIndexInput$SingleBufferImpl.readLong(ByteBufferIndexInput.java:479) ~[lucene-core-8.6.2.jar:8.6.2 016993b65e393b58246d54e8ddda9f56a453eb0e - ivera - 2020-08-26 10:53:36]
	at org.apache.lucene.util.packed.DirectReader$DirectPackedReader64.get(DirectReader.java:343) ~[lucene-core-8.6.2.jar:8.6.2 016993b65e393b58246d54e8ddda9f56a453eb0e - ivera - 2020-08-26 10:53:36]
	at org.apache.lucene.codecs.lucene80.Lucene80DocValuesProducer$8.longValue(Lucene80DocValuesProducer.java:545) ~[lucene-core-8.6.2.jar:8.6.2 016993b65e393b58246d54e8ddda9f56a453eb0e - ivera - 2020-08-26 10:53:36]
	at org.apache.lucene.document.SortedNumericDocValuesRangeQuery$1$1.matches(SortedNumericDocValuesRangeQuery.java:124) ~[lucene-core-8.6.2.jar:8.6.2 016993b65e393b58246d54e8ddda9f56a453eb0e - ivera - 2020-08-26 10:53:36]
	at org.apache.lucene.search.ConjunctionDISI$ConjunctionTwoPhaseIterator.matches(ConjunctionDISI.java:345) ~[lucene-core-8.6.2.jar:8.6.2 016993b65e393b58246d54e8ddda9f56a453eb0e - ivera - 2020-08-26 10:53:36]
	at org.apache.lucene.search.join.ToParentBlockJoinQuery$ParentTwoPhase.matches(ToParentBlockJoinQuery.java:262) ~[lucene-join-8.6.2.jar:8.6.2 016993b65e393b58246d54e8ddda9f56a453eb0e - ivera - 2020-08-26 10:54:38]
	at org.apache.lucene.search.ConjunctionDISI$ConjunctionTwoPhaseIterator.matches(ConjunctionDISI.java:345) ~[lucene-core-8.6.2.jar:8.6.2 016993b65e393b58246d54e8ddda9f56a453eb0e - ivera - 2020-08-26 10:53:36]
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:250) ~[lucene-core-8.6.2.jar:8.6.2 016993b65e393b58246d54e8ddda9f56a453eb0e - ivera - 2020-08-26 10:53:36]
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:229) ~[lucene-core-8.6.2.jar:8.6.2 016993b65e393b58246d54e8ddda9f56a453eb0e - ivera - 2020-08-26 10:53:36]
	at org.elasticsearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:56) ~[elasticsearch-7.9.2.jar:7.9.2]
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39) ~[lucene-core-8.6.2.jar:8.6.2 016993b65e393b58246d54e8ddda9f56a453eb0e - ivera - 2020-08-26 10:53:36]
	at org.elasticsearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:226) ~[elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:199) ~[elasticsearch-7.9.2.jar:7.9.2]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:445) ~[lucene-core-8.6.2.jar:8.6.2 016993b65e393b58246d54e8ddda9f56a453eb0e - ivera - 2020-08-26 10:53:36]
	at org.elasticsearch.search.query.QueryPhase.searchWithCollector(QueryPhase.java:343) ~[elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.search.query.QueryPhase.executeInternal(QueryPhase.java:298) ~[elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:150) ~[elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:362) ~[elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:435) ~[elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.search.SearchService.access$200(SearchService.java:136) ~[elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:396) ~[elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:412) ~[elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) ~[elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:737) ~[elasticsearch-7.9.2.jar:7.9.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.9.2.jar:7.9.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:832) ~[?:?]
```

Example error return when running the sample query against a fully populated system:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4565  100   932  100  3633    242    945  0:00:03  0:00:03 --:--:--  1187{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_out_of_bounds_exception",
        "reason" : "index_out_of_bounds_exception: null"
      },
      {
        "type" : "index_out_of_bounds_exception",
        "reason" : null
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "[redacted]",
        "node" : "VeddA7VTTz-oqvvyVECOsQ",
        "reason" : {
          "type" : "index_out_of_bounds_exception",
          "reason" : "index_out_of_bounds_exception: null"
        }
      },
      {
        "shard" : 1,
        "index" : "[redacted]",
        "node" : "dYjvEQmLSi6CeL4VVElGKw",
        "reason" : {
          "type" : "index_out_of_bounds_exception",
          "reason" : null
        }
      }
    ]
  },
  "status" : 500
}
```

----------------------------------------------------------------

To Reproduce the Inconsistent Behavior:

This illustrates that the normal `match_phrase` query fails for this simple case, but that with profiling enabled, or with a different low level query, it succeeds.  Both the index and queries have been greatly simplified compared to what is run on the deployed systems.  In the following, please substitute your ES node IP address for what is used in the following.  This was run against a dev system with more than one node, so there were two shards created, the primary and a replica.

1. Create an index with the following mapping:

```
$ curl -X PUT "localhost:9200/outofboundsv1?pretty" -H 'Content-Type: application/json' -d'
{
  "aliases": {
    "outofbounds": {}
  },
  "mappings": {
    "dynamic": "strict",
    "properties": {
      "toolTracks": {
        "type": "nested",
        "properties": {
          "idToken": {
            "type": "text"
          },
          "data": {
            "type": "text"
          },
          "start" : {
            "type" : "long"
          },
          "confidence": {
            "type": "double"
          }
        }
      },
      "md5": {
        "type": "keyword"
      },
      "durationMSecs": {
        "type": "long"
      },
      "calculatedDurationMSecs": {
        "type": "long"
      }
    }
  },
  "settings": {
    "index": {
      "requests.cache.enable": true,
      "max_result_window": 1000000,
      "max_inner_result_window": 1000000,
      "refresh_interval": "30s"
    }
  }
}
'
```
Results:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   916  100    89  100   827     43    408  0:00:02  0:00:02 --:--:--   452{
  "acknowledged" : true,
  "shards_acknowledged" : true,
  "index" : "outofboundsv1"
}
```

2. Populate it with a single document with several records of a nested type:

```
$ curl -X POST "localhost:9200/outofboundsv1/_doc/00001?pretty" -H 'Content-Type: application/json' -d'
{
  "md5" : "00001",
  "durationMSecs" : "2000",
  "toolTracks": [{
	"idToken" : "videoLabelsTemporalID",
         "start" : 10,
         "data" : "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM",
         "confidence" : 0.3
  },
  {
	"idToken" : "videoLabelsTemporalID",
         "start" : 100,
         "data" : "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM",
         "confidence" : 0.92
  },
  {
	"idToken" : "videoLabelsTemporalID",
         "start" : 200,
         "data" : "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM",
         "confidence" : 0.7
  },
  {
	"idToken" : "videoLabelsTemporalID",
         "start" : 300,
         "data" : "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM",
         "confidence" : 0.85
  },
  {
	"idToken" : "videoLabelsTemporalID",
         "start" : 400,
         "data" : "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM",
         "confidence" : 0.2
  },
  {
	"idToken" : "videoLabelsTemporalID",
         "start" : 500,
         "data" : "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM",
         "confidence" : 0.3
  },
  {
	"idToken" : "videoLabelsTemporalID",
         "start" : 600,
         "data" : "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM",
         "confidence" : 0.75
  },
  {
	"idToken" : "videoLabelsTemporalID",
         "start" : 700,
         "data" : "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM",
         "confidence" : 0.82
  },
  {
	"idToken" : "videoLabelsTemporalID",
         "start" : 800,
         "data" : "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM",
         "confidence" : 0.1
  },
  {
	"idToken" : "videoLabelsTemporalID",
         "start" : 900,
         "data" : "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM",
         "confidence" : 0.6
  },
  {
	"idToken" : "videoLabelsTemporalID",
         "start" : 1000,
         "data" : "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM",
         "confidence" : 0.3
  },
  {
	"idToken" : "videoLabelsTemporalID",
         "start" : 1100,
         "data" : "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM",
         "confidence" : 0.7
  }
 ]
}
'
```

Results:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3041  100   231  100  2810   1358  16529 --:--:-- --:--:-- --:--:-- 17888{
  "_index" : "outofboundsv1",
  "_type" : "_doc",
  "_id" : "00001",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 2,
    "successful" : 2,
    "failed" : 0
  },
  "_seq_no" : 0,
  "_primary_term" : 1
}
```

3. To validate the query, use a `match_phrase` Query with profiling ENABLED.  This returns the valid result; it does find the document.  Aside from profiling, this query is identical to the failing version.

```
$ curl -X POST "localhost:9200/outofboundsv1/_search/?pretty" -H 'Content-Type: application/json' -d'
{
  "from": 0,
  "size": 200,
  "timeout": "600000ms",
  "profile" : true,
  "query": {
    "bool": {
      "filter": [
                    {
                      "script_score": {
                        "query": {
                          "nested": {
                            "query": {
                              "constant_score": {
                                "filter": {
                                  "bool": {
                                    "filter": [
                                      {
                                        "match_phrase": {
                                          "toolTracks.data": {
                                            "query": "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, atm",
                                            "slop": 0,
                                            "zero_terms_query": "NONE",
                                            "boost": 1.0
                                          }
                                        }
                                      },
                                      {
                                        "match": {
                                          "toolTracks.idToken": {
                                            "query": "videoLabelsTemporalID",
                                            "operator": "OR",
                                            "prefix_length": 0,
                                            "max_expansions": 50,
                                            "fuzzy_transpositions": true,
                                            "lenient": false,
                                            "zero_terms_query": "NONE",
                                            "auto_generate_synonyms_phrase_query": true,
                                            "boost": 1.0
                                          }
                                        }
                                      },
                                      {
                                        "range": {
                                           "toolTracks.confidence": {
                                            "from": 0.8,
                                            "to": null,
                                            "include_lower": true,
                                            "include_upper": true,
                                            "boost": 1.0
                                          }
                                        }
                                      }
                                    ],
                                    "adjust_pure_negative": true,
                                    "boost": 1.0
                                  }
                                },
                                "boost": 1.0
                              }
                            },
                            "path": "toolTracks",
                            "ignore_unmapped": false,
                            "score_mode": "sum",
                            "boost": 1.0
                          }
                        },
                        "script": {
                          "source": "_score",
                          "lang": "painless"
                        },
                        "min_score": 2.0,
                        "boost": 1.0
                      }
                    }
                  ],
      "adjust_pure_negative": true,
      "boost": 1.0
    }
  },
  "_source": false,
  "track_total_hits": 2147483647
}'
```

Results (hits.total.value = 1):

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 0.0,
    "hits" : [
      {
        "_index" : "outofboundsv1",
        "_type" : "_doc",
        "_id" : "00001",
        "_score" : 0.0
      }
    ]
  },
  "profile" : { ... } //suppressing display of profile

```

4. The failing case: use a `match_phrase` Query but for normal use with profiling DISABLED.  This finds no hits as shown below.

```
$ curl -X POST "localhost:9200/outofboundsv1/_search/?pretty" -H 'Content-Type: application/json' -d'
{
  "from": 0,
  "size": 200,
  "timeout": "600000ms",
  "profile" : false,
  "query": {
    "bool": {
      "filter": [
                    {
                      "script_score": {
                        "query": {
                          "nested": {
                            "query": {
                              "constant_score": {
                                "filter": {
                                  "bool": {
                                    "filter": [
                                      {
                                        "match_phrase": {
                                          "toolTracks.data": {
                                            "query": "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, atm",
                                            "slop": 0,
                                            "zero_terms_query": "NONE",
                                            "boost": 1.0
                                          }
                                        }
                                      },
                                      {
                                        "match": {
                                          "toolTracks.idToken": {
                                            "query": "videoLabelsTemporalID",
                                            "operator": "OR",
                                            "prefix_length": 0,
                                            "max_expansions": 50,
                                            "fuzzy_transpositions": true,
                                            "lenient": false,
                                            "zero_terms_query": "NONE",
                                            "auto_generate_synonyms_phrase_query": true,
                                            "boost": 1.0
                                          }
                                        }
                                      },
                                      {
                                        "range": {
                                           "toolTracks.confidence": {
                                            "from": 0.8,
                                            "to": null,
                                            "include_lower": true,
                                            "include_upper": true,
                                            "boost": 1.0
                                          }
                                        }
                                      }
                                    ],
                                    "adjust_pure_negative": true,
                                    "boost": 1.0
                                  }
                                },
                                "boost": 1.0
                              }
                            },
                            "path": "toolTracks",
                            "ignore_unmapped": false,
                            "score_mode": "sum",
                            "boost": 1.0
                          }
                        },
                        "script": {
                          "source": "_score",
                          "lang": "painless"
                        },
                        "min_score": 2.0,
                        "boost": 1.0
                      }
                    }
                  ],
      "adjust_pure_negative": true,
      "boost": 1.0
    }
  },
  "_source": false,
  "track_total_hits": 2147483647
}'
```

Results (hits.total.value == 0)

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3881  100   261  100  3620  43500   589k --:--:-- --:--:-- --:--:--  758k{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
```

5. Change the `match_phrase` query to a `match` query and see that it works:

```
$ curl -X POST "localhost:9200/outofboundsv1/_search/?pretty" -H 'Content-Type: application/json' -d'
{
  "from": 0,
  "size": 200,
  "timeout": "600000ms",
  "profile" : false,
  "query": {
    "bool": {
      "filter": [
                    {
                      "script_score": {
                        "query": {
                          "nested": {
                            "query": {
                              "constant_score": {
                                "filter": {
                                  "bool": {
                                    "filter": [
                                      {
                                        "match": {
                                          "toolTracks.data": {
                                            "query": "cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, atm",
                                            "zero_terms_query": "NONE",
                                            "boost": 1.0
                                          }
                                        }
                                      },
                                      {
                                        "match": {
                                          "toolTracks.idToken": {
                                            "query": "videoLabelsTemporalID",
                                            "operator": "OR",
                                            "prefix_length": 0,
                                            "max_expansions": 50,
                                            "fuzzy_transpositions": true,
                                            "lenient": false,
                                            "zero_terms_query": "NONE",
                                            "auto_generate_synonyms_phrase_query": true,
                                            "boost": 1.0
                                          }
                                        }
                                      },
                                      {
                                        "range": {
                                           "toolTracks.confidence": {
                                            "from": 0.8,
                                            "to": null,
                                            "include_lower": true,
                                            "include_upper": true,
                                            "boost": 1.0
                                          }
                                        }
                                      }
                                    ],
                                    "adjust_pure_negative": true,
                                    "boost": 1.0
                                  }
                                },
                                "boost": 1.0
                              }
                            },
                            "path": "toolTracks",
                            "ignore_unmapped": false,
                            "score_mode": "sum",
                            "boost": 1.0
                          }
                        },
                        "script": {
                          "source": "_score",
                          "lang": "painless"
                        },
                        "min_score": 2.0,
                        "boost": 1.0
                      }
                    }
                  ],
      "adjust_pure_negative": true,
      "boost": 1.0
    }
  },
  "_source": false,
  "track_total_hits": 2147483647
}'
```
Results:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3948  100   390  100  3558  65000   579k --:--:-- --:--:-- --:--:--  642k{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 0.0,
    "hits" : [
      {
        "_index" : "outofboundsv1",
        "_type" : "_doc",
        "_id" : "00001",
        "_score" : 0.0
      }
    ]
  }
}
```

-------------------------------------------------------------
Other comments:
1. The mapping and query above are greatly simplified from the production version, but show the same behavior
2. If the `toolTracks.data` query text is shortened significantly in the match phrase above we do get hits.  But for other examples we haven't found a fixed size cutoff.  Also, in most cases with shorter query texts, the query works fine.
2. In some versions of our production queries, we use an inner hit stategy to return the lower level results.  So we would rather not completely restructure the query.  (This is not used for the version that gives the index out of bounds exception)
3. We could potentially work around the problem by using a `match` query instead of the `match_phrase` query, but that is obviously not as precise.

**Comment by dnhatn** [comment]
@marcreichman I can reproduce the issue with these steps. Thank you so much for the detailed report. I will open the fix soon.

**Comment by dnhatn** [comment]
I've open a fix in https://github.com/elastic/elasticsearch/pull/80116.

**Comment by marcreichman** [comment]
@dnhatn Thank you so much for the quick eyes and turnaround on this! Is there any chance it could make it into 7.15.2 if merged?

**Comment by dnhatn** [comment]
@marcreichman Yes, we will try to get it in 7.15.2 if possible. I've updated the fix versions of the PR.
