### ISSUE TITLE
[CI] RestGetSnapshotsIT testSortAndPaginateWithInProgress failing

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#79779]
This has been particularly flaky over the last 4 days, https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Athens&tests.container=org.elasticsearch.http.snapshots.RestGetSnapshotsIT&tests.sortField=FAILED&tests.test=testSortAndPaginateWithInProgress&tests.unstableOnly=true

**Build scan:**
https://gradle-enterprise.elastic.co/s/j6rh73in4gaqi/tests/:qa:smoke-test-http:integTest/org.elasticsearch.http.snapshots.RestGetSnapshotsIT/testSortAndPaginateWithInProgress

**Reproduction line:**
`./gradlew ':qa:smoke-test-http:integTest' --tests "org.elasticsearch.http.snapshots.RestGetSnapshotsIT.testSortAndPaginateWithInProgress" -Dtests.seed=7213D5EE803D5CAB -Dtests.locale=es-GT -Dtests.timezone=Africa/Accra -Druntime.java=11`

**Applicable branches:**
master, 7.16

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.http.snapshots.RestGetSnapshotsIT&tests.test=testSortAndPaginateWithInProgress

**Failure excerpt:**
```
java.lang.AssertionError: expected:<[SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-0/sDjyOJX2T6iU413ObgP0vQ, state=SUCCESS, reason='null', indices=[], startTime=1635229854789, endTime=1635229854798, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-1/-V1xYn8BSo2wfPpb0NMJHg, state=SUCCESS, reason='null', indices=[], startTime=1635229854799, endTime=1635229854977, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-2/ZN4gRmQ_RYGD_bncyxtt0g, state=SUCCESS, reason='null', indices=[], startTime=1635229854807, endTime=1635229855058, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-3/1V7dbEZTRViX6Xm6gpFPpw, state=SUCCESS, reason='null', indices=[], startTime=1635229854815, endTime=1635229855195, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-4/lTg7HDpoQu6Mjj5oezP-5A, state=SUCCESS, reason='null', indices=[], startTime=1635229854825, endTime=1635229855266, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-5/h6NqkmHdSeyh39M5RDnDAg, state=SUCCESS, reason='null', indices=[], startTime=1635229854834, endTime=1635229855336, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-6/ujKA23-5RlKYnsuR4voX-g, state=SUCCESS, reason='null', indices=[], startTime=1635229854844, endTime=1635229855406, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-7/RHoKZTc7RFqAWjPtVd7wuw, state=SUCCESS, reason='null', indices=[], startTime=1635229854853, endTime=1635229855475, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-8/c92IKJWrTTKErIjYIdpYDA, state=SUCCESS, reason='null', indices=[], startTime=1635229854862, endTime=1635229855554, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-9/_YPz1Pb4R2GFA3MAfmPlOA, state=SUCCESS, reason='null', indices=[], startTime=1635229854869, endTime=1635229855625, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-10/ci7dlrL4QhSRts6C9T0W-A, state=SUCCESS, reason='null', indices=[], startTime=1635229854877, endTime=1635229855698, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-11/T8FYr2TuQOua6LA8ixbs1A, state=SUCCESS, reason='null', indices=[], startTime=1635229854886, endTime=1635229855774, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-0/IN6wQLGIRhy1zYwuu-yQAQ, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856046, endTime=1635229856184, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-1/uax8pIsKQPy8faEh70tJCQ, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856073, endTime=1635229856275, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-2/nk49YuzDQtGzoGnK4J9DAg, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856084, endTime=1635229856370, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-3/-001QUBSQqiaOSG-OgsrAA, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856096, endTime=1635229856464, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-4/AGpAmNKsShqJjmHuQ5ejsA, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856106, endTime=1635229856548, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-5/WP1Lxs8eRsiFk0RNcr0imA, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856118, endTime=1635229856635, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-6/j3IqqtHkTmmX6g2hJDDhxg, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856127, endTime=1635229856706, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-7/Nxjbp5-VQCemmpCrUbAI4Q, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856137, endTime=1635229856787, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-8/iI6h0Db3TwSKxzj9Q9QdFw, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856145, endTime=1635229856868, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-9/4TJbSrfTTy-sKoE5dEyJig, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856156, endTime=1635229856960, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-10/KFTwDVyYRFCx3urqyGd79Q, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856166, endTime=1635229857023, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-0/J_xiB2MJSzasDHffrckpHw, state=IN_PROGRESS, reason='null', indices=[test-index-1, test-index-2], startTime=1635229857294, endTime=0, totalShards=2, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}]> but was:<[SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-0/sDjyOJX2T6iU413ObgP0vQ, state=SUCCESS, reason='null', indices=[], startTime=1635229854789, endTime=1635229854798, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-1/-V1xYn8BSo2wfPpb0NMJHg, state=SUCCESS, reason='null', indices=[], startTime=1635229854799, endTime=1635229854977, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-2/ZN4gRmQ_RYGD_bncyxtt0g, state=SUCCESS, reason='null', indices=[], startTime=1635229854807, endTime=1635229855058, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-3/1V7dbEZTRViX6Xm6gpFPpw, state=SUCCESS, reason='null', indices=[], startTime=1635229854815, endTime=1635229855195, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-4/lTg7HDpoQu6Mjj5oezP-5A, state=SUCCESS, reason='null', indices=[], startTime=1635229854825, endTime=1635229855266, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-5/h6NqkmHdSeyh39M5RDnDAg, state=SUCCESS, reason='null', indices=[], startTime=1635229854834, endTime=1635229855336, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-6/ujKA23-5RlKYnsuR4voX-g, state=SUCCESS, reason='null', indices=[], startTime=1635229854844, endTime=1635229855406, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-7/RHoKZTc7RFqAWjPtVd7wuw, state=SUCCESS, reason='null', indices=[], startTime=1635229854853, endTime=1635229855475, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-8/c92IKJWrTTKErIjYIdpYDA, state=SUCCESS, reason='null', indices=[], startTime=1635229854862, endTime=1635229855554, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-9/_YPz1Pb4R2GFA3MAfmPlOA, state=SUCCESS, reason='null', indices=[], startTime=1635229854869, endTime=1635229855625, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-10/ci7dlrL4QhSRts6C9T0W-A, state=SUCCESS, reason='null', indices=[], startTime=1635229854877, endTime=1635229855698, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-11/T8FYr2TuQOua6LA8ixbs1A, state=SUCCESS, reason='null', indices=[], startTime=1635229854886, endTime=1635229855774, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-0/IN6wQLGIRhy1zYwuu-yQAQ, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856046, endTime=1635229856184, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-1/uax8pIsKQPy8faEh70tJCQ, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856073, endTime=1635229856275, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-2/nk49YuzDQtGzoGnK4J9DAg, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856084, endTime=1635229856370, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-3/-001QUBSQqiaOSG-OgsrAA, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856096, endTime=1635229856464, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-4/AGpAmNKsShqJjmHuQ5ejsA, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856106, endTime=1635229856548, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-5/WP1Lxs8eRsiFk0RNcr0imA, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856118, endTime=1635229856635, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-6/j3IqqtHkTmmX6g2hJDDhxg, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856127, endTime=1635229856706, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-7/Nxjbp5-VQCemmpCrUbAI4Q, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856137, endTime=1635229856787, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-8/iI6h0Db3TwSKxzj9Q9QdFw, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856145, endTime=1635229856868, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-9/4TJbSrfTTy-sKoE5dEyJig, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856156, endTime=1635229856960, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-10/KFTwDVyYRFCx3urqyGd79Q, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856166, endTime=1635229857023, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-0/J_xiB2MJSzasDHffrckpHw, state=IN_PROGRESS, reason='null', indices=[test-index-1, test-index-2], startTime=1635229857294, endTime=0, totalShards=2, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}]>

  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.failNotEquals(Assert.java:834)
  at org.junit.Assert.assertEquals(Assert.java:118)
  at org.junit.Assert.assertEquals(Assert.java:144)
  at org.elasticsearch.http.snapshots.RestGetSnapshotsIT.assertStablePagination(RestGetSnapshotsIT.java:340)
  at org.elasticsearch.http.snapshots.RestGetSnapshotsIT.testSortAndPaginateWithInProgress(RestGetSnapshotsIT.java:179)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by davidkyle** [comment]
A failure on 7.16 and now muted on 7.16

https://gradle-enterprise.elastic.co/s/xzgprxf33u6h4/tests/:qa:smoke-test-http:integTest/org.elasticsearch.http.snapshots.RestGetSnapshotsIT/testSortAndPaginateWithInProgress
