### ISSUE TITLE
[CI] DockerTests test310IronBankImageHasNoAdditionalLabels failing

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#79781]
**Build scan:**
https://gradle-enterprise.elastic.co/s/znkrwcj2h53wc/tests/:qa:os:destructiveDistroTest.default-docker/org.elasticsearch.packaging.test.DockerTests/test310IronBankImageHasNoAdditionalLabels

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.DockerTests&tests.test=test310IronBankImageHasNoAdditionalLabels

**Failure excerpt:**
```
java.lang.AssertionError: Elasticsearch container did not start successfully.

ps output:
PID   USER     TIME  COMMAND
    1 elastics  0:00 /bin/tini -- /usr/local/bin/docker-entrypoint.sh eswrapper
    7 elastics  0:00 {elasticsearch} /bin/bash /usr/share/elasticsearch/bin/elasticsearch
  524 elastics  0:22 /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Xms4m -Xmx64m -XX:+UseSerialGC -Des.cgroups.hierarchy.override=/ -Des.cgroups.hierarchy.override=/ -Des.path.home=/usr/share/elasticsearch -Des.path.conf=/usr/share/elasticsearch/config -Des.distribution.flavor=default -Des.distribution.type=docker -cp /usr/share/elasticsearch/lib/*:/usr/share/elasticsearch/modules/x-pack-core/*:/usr/share/elasticsearch/modules/x-pack-security/*:/usr/share/elasticsearch/lib/tools/security-cli/* org.elasticsearch.xpack.security.cli.ConfigInitialNode -Eingest.geoip.downloader.enabled=false -Ediscovery.type=single-node
  714 elastics  0:00 ps ax

Stdout:
Created elasticsearch keystore in /usr/share/elasticsearch/config/elasticsearch.keystore

Stderr:

  at __randomizedtesting.SeedInfo.seed([589B4D994D3273F9:F4094DEAC9AE5E3F]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.elasticsearch.packaging.util.docker.Docker.waitForElasticsearchToStart(Docker.java:177)
  at org.elasticsearch.packaging.util.docker.Docker.runContainer(Docker.java:118)
  at org.elasticsearch.packaging.test.DockerTests.setupTest(DockerTests.java:105)
  at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(null:-1)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:980)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by pugnascotia** [comment]
I think is probably fixed by #80376.
