### ISSUE TITLE
[CI] DockerYmlTestSuiteIT test {p0=/11_nodes/Test cat nodes output with full_id set} (and 1 more) failing

### ISSUE THREAD

**Issue by Luegg** [elastic/elasticsearch#79803]
Similar failure mode seems to happen for `test {p0=/11_nodes/Test cat nodes output with full_id set}` as well.

**Build scan:**
https://gradle-enterprise.elastic.co/s/jqiynex57roww/tests/:distribution:docker:integTest/org.elasticsearch.docker.test.DockerYmlTestSuiteIT/test%20%7Bp0=%2F11_nodes%2FTest%20cat%20nodes%20output%20with%20full_id%20set%7D
and
https://gradle-enterprise.elastic.co/s/jqiynex57roww/tests/:distribution:docker:integTest/org.elasticsearch.docker.test.DockerYmlTestSuiteIT/test%20%7Bp0=%2F11_nodes%2FTest%20cat%20nodes%20output%20with%20full_id%20set%7D?top-execution=1

**Reproduction line:**
`./gradlew ':distribution:docker:integTest' --tests "org.elasticsearch.docker.test.DockerYmlTestSuiteIT.test {p0=/11_nodes/Test cat nodes output with full_id set}" -Dtests.seed=F21346016F4B686B -Dtests.locale=bg -Dtests.timezone=America/Asuncion -Druntime.java=16`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.docker.test.DockerYmlTestSuiteIT&tests.test=test%20%7Bp0%3D/11_nodes/Test%20cat%20nodes%20output%20with%20full_id%20set%7D
and
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Zurich&tests.container=org.elasticsearch.docker.test.DockerYmlTestSuiteIT&tests.sortField=FAILED&tests.test=test%20%7Bp0%3D/11_nodes/Test%20cat%20nodes%20output%20with%20full_id%20set%7D&tests.unstableOnly=true

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [DELETE], host [https://localhost:49156], URI [*,-.ds-ilm-history-*?expand_wildcards=open%2Cclosed%2Chidden], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"index [.ds-.logs-deprecation.elasticsearch-default-2021.10.26-000001] is the write index for data stream [.logs-deprecation.elasticsearch-default] and cannot be deleted"}],"type":"illegal_argument_exception","reason":"index [.ds-.logs-deprecation.elasticsearch-default-2021.10.26-000001] is the write index for data stream [.logs-deprecation.elasticsearch-default] and cannot be deleted"},"status":400}

  at __randomizedtesting.SeedInfo.seed([F21346016F4B686B:7A4779DBC1B70593]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:329)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:295)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:269)
  at org.elasticsearch.test.rest.ESRestTestCase.wipeAllIndices(ESRestTestCase.java:801)
  at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:636)
  at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:371)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:567)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:831)

```

**Comment by pugnascotia** [comment]
Another failure: https://gradle-enterprise.elastic.co/s/3jqk2kdhl7soq

**Comment by gwbrown** [comment]
Hit what I'm pretty sure is also this failure, although the test in question is [](https://gradle-enterprise.elastic.co/s/heop4nfpufrh4/tests/:distribution:docker:integTest/org.elasticsearch.docker.test.DockerYmlTestSuiteIT/test%20%7Bp0=%2F10_info%2FInfo%7D?top-execution=1)

The stack trace is quite similar: 
```
org.elasticsearch.client.ResponseException: method [DELETE], host [https://localhost:49156], URI [*,-.ds-ilm-history-*?expand_wildcards=open%2Cclosed%2Chidden], status line [HTTP/1.1 400 Bad Request]	
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"index [.ds-.logs-deprecation.elasticsearch-default-2021.11.29-000001] is the write index for data stream [.logs-deprecation.elasticsearch-default] and cannot be deleted"}],"type":"illegal_argument_exception","reason":"index [.ds-.logs-deprecation.elasticsearch-default-2021.11.29-000001] is the write index for data stream [.logs-deprecation.elasticsearch-default] and cannot be deleted"},"status":400}	
	at __randomizedtesting.SeedInfo.seed([CF2CBEA07435DF4B:4778817ADAC9B2B3]:0)	
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:335)	
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:301)	
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:276)	
	at org.elasticsearch.test.rest.ESRestTestCase.wipeAllIndices(ESRestTestCase.java:931)	
	at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:668)	
	at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:383)	
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)	
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
	at java.lang.reflect.Method.invoke(Method.java:568)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)	
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)	
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)	
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)	
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)	
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)	
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)	
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)	
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)	
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)	
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)	
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)	
	at java.lang.Thread.run(Thread.java:833)
```

**Comment by jdconrad** [comment]
I think I have another one that's possibly related:

https://gradle-enterprise.elastic.co/s/6fzaazxdu6ydw

**Comment by grcevski** [comment]
I took a look at this test failure and it seems like the wipeDataStreams call didn't properly remove all data streams, or that wipeAllIndices caused a deprecation warning that reactivated the deprecation logs data stream. 

Perhaps a solution to this problem is to disable the deprecation logger in the ESRestTestcase teardown code or there might be a better solution here.

**Comment by pgomulka** [comment]
I support the idea of disabling this for docker test. Looks like it does not use a org.elasticsearch.gradle.testclusters.ElasticsearchCluster where I disabled this setting (for testing only)

The problem comes down to hidden data stream being not deleted (fine), but indices are being attempted to be deleted (even though they are hidden)
https://github.com/elastic/elasticsearch/pull/78911/files#diff-0e8d8cbefbf91b6141ecfe2e904cfbef291161f3c36f31696e220ecb64c6d4bdR5

Cleanup of hidden data stream is tricky. I intentionally disabled this for all tests (ElasticsearchCluster default) and only enabled for those who assert about the content of the deprecation data stream.
The cleanup in those test is manual https://github.com/elastic/elasticsearch/blob/170812143df9b59a880c7e0f9e64ed476db4b47c/x-pack/plugin/deprecation/qa/rest/src/javaRestTest/java/org/elasticsearch/xpack/deprecation/DeprecationHttpIT.java#L106

I wonder if we could get some eyes from @elastic/es-data-management on this? I did a similar problem to index_templates in the past. It was discussed on 6th Oct 2020 - search `Should index templates for hidden data streams be excluded from `DELETE /_index_template/*` requests?` in es data managment agenda.

**Comment by pgomulka** [comment]
another one 
https://gradle-enterprise.elastic.co/s/b35jx6r77qpwe/tests/:distribution:docker:integTest/org.elasticsearch.docker.test.DockerYmlTestSuiteIT/test%20%7Bp0=%2F11_nodes%2FTest%20cat%20nodes%20output%7D?top-execution=1

**Comment by pgomulka** [comment]
@mark-vieira do you think this failure is because this test is INTEG_TEST whereas javaRestTests are DEFAULT?
I only disable `cluster.deprecation_indexing.enabled` setting for DEFAULT
https://github.com/elastic/elasticsearch/blob/cb40354d87181bb4da6a1b6b71876f035d0b4db7/build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchCluster.java#L322

**Comment by mark-vieira** [comment]
I'm frankly not familiar enough with the behavior of that setting to say, but yes, if we are only setting it for default distributions and that impacts these tests that would explain it. We can either a) configure the test cluster for those test to set that setting, b) use the default distribution for those tests or c) otherwise adapt the tests to account for this.

I'd prefer we **not** go with (b) as using the integ-test distribution is lighter weight and results in better test avoidance.

**Comment by romseygeek** [comment]
Another failure here: https://gradle-enterprise.elastic.co/s/gtw3rbsrxjcja/tests/:distribution:docker:integTest/org.elasticsearch.docker.test.DockerYmlTestSuiteIT/test%20%7Bp0=%2F11_nodes%2FAdditional%20disk%20information%7D?top-execution=1

**Comment by valeriy42** [comment]
Another related failure of `DockerYmlTestSuiteIT » test {p0=/10_info/Info` here https://gradle-enterprise.elastic.co/s/nqo2emkkw3any

**Comment by pgomulka** [comment]
another one https://gradle-enterprise.elastic.co/s/eigkjlzojiar4

**Comment by pgomulka** [comment]
The main problem is that this test is using deprecation xpack module which I did not expect. In fact it loads all modules (60+). I need to disable deprecation indexing for this.

The test is failing because there must be some kind of race condition that creates a data stream in between `ESRestTestCase#wipeDataStream` and `ESRestTestCase#wipeAllIndices`
We do create deprecations immedialy when the test starts in `ESClientYamlSuiteTestCase`
```
WARNING: request [PUT https://localhost:49174/_template/global] returned 2 warnings: [299 Elasticsearch-7.17.1-SNAPSHOT-da5fda06224fae085bfa366bb2c8fd7ceaeb4fa9 "legacy template [global] has index patterns [*] matching patterns from existing composable templates [.deprecation-indexing-template,.ml-anomalies-,.ml-notifications-000002,.ml-state,.ml-stats,.slm-history,.watch-history-13,ilm-history,logs,metrics,synthetics] with patterns (.deprecation-indexing-template => [.logs-deprecation.*],.ml-anomalies- => [.ml-anomalies-*],.ml-notifications-000002 => [.ml-notifications-000002],.ml-state => [.ml-state*],.ml-stats => [.ml-stats-*],.slm-history => [.slm-history-5*],.watch-history-13 => [.watcher-history-13*],ilm-history => [ilm-history-5*],logs => [logs-*-*],metrics => [metrics-*-*],synthetics => [synthetics-*-*]); this template [global] may be ignored in favor of a composable template at index creation time"],[299 Elasticsearch-7.17.1-SNAPSHOT-da5fda06224fae085bfa366bb2c8fd7ceaeb4fa9 "Legacy index templates are deprecated in favor of composable templates."]
```

I need to figure out a way to disable indexing for INTEG_TEST when deprecation module is used (not sure it is safe to assume it is always used). For this test I could see that it was used from the call here https://github.com/elastic/elasticsearch/blob/273eeddc14601988ad0a70f0b199d163c6e09f1d/test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java#L227

Place to disable indexing: https://github.com/elastic/elasticsearch/blob/64929dc5df696e64ae48432651eed043194c630e/build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchCluster.java#L334

**Comment by mark-vieira** [comment]
The docker tests aren't using tests clusters or the integ_test distribution, they are testing against the Docker container. If changes to settings for the cluster need to be made here it has to be done in the d[ocker-compose file](https://github.com/elastic/elasticsearch/blob/master/distribution/docker/docker-compose.yml).
