### ISSUE TITLE
[CI] EnrollmentProcessTests test10AutoFormCluster failing

### ISSUE THREAD

**Issue by Luegg** [elastic/elasticsearch#79810]
Test seems to fail somewhat frequently

**Build scan:**
https://gradle-enterprise.elastic.co/s/lbprapwe6bi56/tests/:qa:os:destructiveDistroTest.default-linux-archive/org.elasticsearch.packaging.test.EnrollmentProcessTests/test10AutoFormCluster

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.EnrollmentProcessTests&tests.test=test10AutoFormCluster

**Failure excerpt:**
```
org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c sudo -E -u elasticsearch "/tmp/elasticsearch-node2/bin/elasticsearch-enroll-node" --enrollment-token eyJ2ZXIiOiI4LjAuMCIsImFkciI6WyIxNzIuMTcuMC4xOjkyMDAiLCIxMC4yMjQuMy40Njo5MjAwIl0sImZnciI6IjcxZmEyNDhkZDIwZjJjZTI5YWYyYjA2YzMzZmUwMGIxMzQ3ZmM5YzI2M2YzNmIzMTEyMDk1YTk2YTdmY2JlODAiLCJrZXkiOiJEaDVOdkh3QkZfRFZsNDZkc2Q5QjpXRjFJaWJjdFNxcVpIckZ3aVlzMFNnIn0=]
   result: exitCode = [1] stdout = [] stderr = [Exception in thread "main" javax.net.ssl.SSLHandshakeException: No subject alternative names matching IP address 172.17.0.1 found
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
	at org.elasticsearch.xpack.core.common.socket.SocketAccess.lambda$doPrivileged$0(SocketAccess.java:43)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.elasticsearch.xpack.core.common.socket.SocketAccess.doPrivileged(SocketAccess.java:42)
	at org.elasticsearch.xpack.core.security.CommandLineHttpClient.execute(CommandLineHttpClient.java:164)
	at org.elasticsearch.xpack.core.security.CommandLineHttpClient.execute(CommandLineHttpClient.java:125)
	at org.elasticsearch.xpack.security.cli.EnrollNodeToCluster.execute(EnrollNodeToCluster.java:202)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:114)
	at org.elasticsearch.cli.Command.main(Command.java:79)
	at org.elasticsearch.xpack.security.cli.EnrollNodeToCluster.main(EnrollNodeToCluster.java:108)
Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address 172.17.0.1 found
	at java.base/sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:165)
	at java.base/sun.security.util.HostnameChecker.match(HostnameChecker.java:101)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:452)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:426)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:1475)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1442)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
	... 24 more]

  at __randomizedtesting.SeedInfo.seed([4154C633C8488898:2C736EC85B2BC262]:0)
  at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:152)
  at org.elasticsearch.packaging.util.Shell.run(Shell.java:73)
  at org.elasticsearch.packaging.util.Installation$Executable.run(Installation.java:187)
  at org.elasticsearch.packaging.util.Installation$Executable.run(Installation.java:170)
  at org.elasticsearch.packaging.test.EnrollmentProcessTests.test10AutoFormCluster(EnrollmentProcessTests.java:51)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

**Comment by ywangd** [comment]
Failed again https://gradle-enterprise.elastic.co/s/qgr46cln7dotg/tests/:qa:os:destructiveDistroTest.default-linux-archive/org.elasticsearch.packaging.test.EnrollmentProcessTests/test10AutoFormCluster?top-execution=1

**Comment by mark-vieira** [comment]
Yeah, this is continuing to fail 2-4 times a day. Should we consider muting for now?

**Comment by jkakavas** [comment]
Yes we should @mark-vieira , it’d be awesome if you can push a mute. It’s still on my radar but I’ve been out for a few days

**Comment by mark-vieira** [comment]
I've muted this in `master` and `8.0` branches.
