### ISSUE TITLE
[CI] PackageUpgradeTests test20InstallUpgradedVersion failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#79950]
Seems our package upgrade tests are failing when upgrading from 8.0.0 to 8.1.0 when verifying that we don't run security auto configuration again. It's possible this might be an actual issue.

**Build scan:**
https://gradle-enterprise.elastic.co/s/krjoyc56huo76/tests/:qa:os:destructiveDistroUpgradeTest.v8.0.0.default-deb/org.elasticsearch.packaging.test.PackageUpgradeTests/test20InstallUpgradedVersion

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.PackageUpgradeTests&tests.test=test20InstallUpgradedVersion

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: is <false>
     but: was <true>

  at __randomizedtesting.SeedInfo.seed([1A9709608842AF00:4608857FB4D610FB]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.packaging.test.PackagingTestCase.verifySecurityNotAutoConfigured(PackagingTestCase.java:724)
  at org.elasticsearch.packaging.test.PackageUpgradeTests.test20InstallUpgradedVersion(PackageUpgradeTests.java:84)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

**Comment by davidkyle** [comment]
Muted while @jkakavas works through his short list 

#80128

**Comment by mark-vieira** [comment]
@jkakavas what's the latest on this? I'm looking to augment our package upgrade tests to validate other work. As it is, we effectively are not testing package upgrades at all with these tests muted. I'd _really_ like to get some resolution here soon so we have better confidence for 8.0.

**Comment by jkakavas** [comment]
I'm looking at this today, will open a PR
