### ISSUE TITLE
[CI] MultiVersionRepositoryAccessIT failures 

### ISSUE THREAD

**Issue by csoulios** [elastic/elasticsearch#80088]
Execution failed for task `:qa:repository-multi-version:v7.11.2#Step1OldClusterTest`.

The following tests fail for `org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT`:

- `testReadOnlyRepo`
- `testUpgradeMovesRepoToNewMetaVersion`
- `testCreateAndRestoreSnapshot`

**Build scan**:

https://gradle-enterprise.elastic.co/s/wqdizvweltvmi
https://gradle-enterprise.elastic.co/s/k4jys7bayx6cs

**Repro line**:

```
REPRODUCE WITH: ./gradlew ':qa:repository-multi-version:v7.7.0#Step1OldClusterTest' \
  -Dtests.class="org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT" \
  -Dtests.method="testReadOnlyRepo" \
  -Dtests.seed=4F0038EE588A6063 \
  -Dtests.bwc=true \
  -Dtests.locale=sl \
  -Dtests.timezone=Etc/UCT \
  -Druntime.java=17

REPRODUCE WITH: ./gradlew ':qa:repository-multi-version:v7.7.0#Step1OldClusterTest' \
  -Dtests.class="org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT" \
  -Dtests.method="testUpgradeMovesRepoToNewMetaVersion" \
  -Dtests.seed=4F0038EE588A6063 \
  -Dtests.bwc=true \
  -Dtests.locale=sl \
  -Dtests.timezone=Etc/UCT \
  -Druntime.java=17

REPRODUCE WITH: ./gradlew ':qa:repository-multi-version:v7.7.0#Step1OldClusterTest' \
  -Dtests.class="org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT" \
  -Dtests.method="testCreateAndRestoreSnapshot" \
  -Dtests.seed=4F0038EE588A6063 \
  -Dtests.bwc=true \
  -Dtests.locale=sl \
  -Dtests.timezone=Etc/UCT \
  -Druntime.java=17
```

**Reproduces locally?**: No

**Applicable branches**: master

**Failure history**:

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2021-08-31T21:00:00.000Z',mode:absolute,to:'2021-10-29T13:46:50.119Z'))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT%22'),sort:!(time,desc))

https://gradle-enterprise.elastic.co/scans/tests?search.startTimeMax=1635515071899&search.startTimeMin=1634850000000&search.timeZoneId=Europe/Athens&tests.container=org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT&tests.sortField=FAILED&tests.unstableOnly=true

**Failure excerpt**:

```
org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT > testReadOnlyRepo FAILED
    org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:41741], URI [_index_template], status line [HTTP/1.1 400 Bad Request]
    {"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [_index_template], must not start with '_'.","index_uuid":"_na_","index":"_index_template"}],"type":"invalid_index_name_exception","reason":"Invalid index name [_index_template], must not start with '_'.","index_uuid":"_na_","index":"_index_template"},"status":400}
        at __randomizedtesting.SeedInfo.seed([4F0038EE588A6063:D0C4727D8CF71D9]:0)
        at app//org.elasticsearch.client.RestClient.convertResponse(RestClient.java:335)
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:301)
        at app//org.elasticsearch.client.RestClient.performRequest(RestClient.java:276)
        at app//org.elasticsearch.test.rest.ESRestTestCase.getAllUnexpectedTemplates(ESRestTestCase.java:855)
        at app//org.elasticsearch.test.rest.ESRestTestCase.checkForUnexpectedlyRecreatedObjects(ESRestTestCase.java:817)
        at app//org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:385)
        at java.base@17.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@17.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base@17.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@17.0.1/java.lang.reflect.Method.invoke(Method.java:568)
        at app//com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at app//com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
        at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app//org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
        at app//org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at app//org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at app//org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at app//org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app//com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
        at app//com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
        at app//com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
        at app//com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at app//com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at app//com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at app//com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at app//org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app//org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at app//com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at app//com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app//org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at app//org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at app//org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at app//org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at app//org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at app//com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at app//com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
        at app//com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
        at java.base@17.0.1/java.lang.Thread.run(Thread.java:833)

```

Also, some tests failed with the following error:

```

org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT > testCreateAndRestoreSnapshot FAILED
    java.lang.AssertionError: Expected no templates after deletions, but found .logstash-management
        at __randomizedtesting.SeedInfo.seed([8C28F35E378D8CA1:A90D100AA8CED1C]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.elasticsearch.test.rest.ESRestTestCase.checkForUnexpectedlyRecreatedObjects(ESRestTestCase.java:818)
        at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:385)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by davidkyle** [comment]
These tests are now muted on master #80119 and 8.0 #80120
