### ISSUE TITLE
xcontent excludes filter badcase

### ISSUE THREAD

**Issue by weizijun** [elastic/elasticsearch#80142]
**Elasticsearch version** (`bin/elasticsearch --version`): master

**Plugins installed**: [] no

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. add a test in `AbstractXContentFilteringTestCase`
```
    public void testExcludesFailed() throws IOException {
        final Builder sample = builder -> builder.startObject().field("bar", "test").field("bbb", "bbb").endObject();
        Builder expected = builder -> builder.startObject().field("bar", "test").field("bbb", "bbb").endObject();
        testFilter(expected, sample, emptySet(), singleton("bar.xxx"));
    }
```
 2. throw the exception:
```
com.fasterxml.jackson.core.JsonGenerationException: Can not write a field name, expecting a value

	at __randomizedtesting.SeedInfo.seed([D5C7EEE02AA53137:388E1895E77A618D]:0)
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:2080)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeFieldName(UTF8JsonGenerator.java:220)
	at com.fasterxml.jackson.core.JsonGenerator._copyCurrentContents(JsonGenerator.java:1938)
	at com.fasterxml.jackson.core.JsonGenerator.copyCurrentStructure(JsonGenerator.java:1914)
	at org.elasticsearch.xcontent.json.JsonXContentGenerator.copyCurrentStructure(JsonXContentGenerator.java:396)
	at org.elasticsearch.xcontent.XContentBuilder.copyCurrentStructure(XContentBuilder.java:1161)
	at org.elasticsearch.xcontent.support.filtering.AbstractXContentFilteringTestCase.filterOnParser(AbstractXContentFilteringTestCase.java:87)
	at org.elasticsearch.xcontent.support.filtering.AbstractXContentFilteringTestCase.testExcludesFailed(AbstractXContentFilteringTestCase.java:94)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
```
I think the right action is passed the test.

**Comment by nik9000** [comment]
Oh yeah, that's fixed in modern jackson. Let's see about updating!

**Comment by weizijun** [comment]
in the new jackson version, filterOnBuilder is ok, but filterOnParser is also bad

**Comment by nik9000** [comment]
> in the new jackson version, filterOnBuilder is ok, but filterOnParser is also bad

The upgrade to jackson in #80160 did seem to fix it for me. That's just stuck....

**Comment by weizijun** [comment]
> > in the new jackson version, filterOnBuilder is ok, but filterOnParser is also bad
> 
> The upgrade to jackson in #80160 did seem to fix it for me. That's just stuck....

yeah, It really fixed. Sorry, I misled you. I test the branch of #80160, it really work!

**Comment by nik9000** [comment]
> yeah, It really fixed. Sorry, I misled you. I test the branch of #80160, it really work!

It happens to me a lot too. I'm glad it's fixed though.
