### ISSUE TITLE
Percentiles Aggregation causes `illegal_state_exception` potentially due to overflow.

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elasticsearch#80153]
**Elasticsearch version** : Experienced on 7.14.2 and 7.15.0
**Plugins installed**: N/A
**JVM version**: Bundled version
**OS version**: Windows

**Description of the problem including expected versus actual behavior**:
When running a search with a `percentiles` aggregation against a histogram field with a large count in one of the buckets, an unexpected server-side `illegal_state_exception` occurs causing a 500 response. After an initial discussion with @not-napoleon we suspect a potential overflow is occurring.

**Steps to reproduce**:
```
PUT test-index
{
    "mappings": {
        "properties": {
            "my_histogram": {
                "type": "histogram"
            }
        }
    }
}

PUT test-index/_doc/1
{
    "my_histogram": {
        "counts": [
            2100000000,
            300000000
        ],
        "values": [
            1,
            2
        ]
    }
}

GET test-index/_search
{
    "aggs": {
        "my_aggregation": {
            "percentiles": {
                "field": "my_histogram",
                "percents": [
                    "95.0"
                ]
            }
        }
    }
}
```

The error occurs after execution of the last search query:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_state_exception",
        "reason" : "Negative longs unsupported, use writeLong or writeZLong for negative numbers [-1894967296]"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "test-index",
        "node" : "t0_xEcuVQhOFiBA8ak-B1w",
        "reason" : {
          "type" : "illegal_state_exception",
          "reason" : "Negative longs unsupported, use writeLong or writeZLong for negative numbers [-1894967296]"
        }
      }
    ],
    "caused_by" : {
      "type" : "illegal_state_exception",
      "reason" : "Negative longs unsupported, use writeLong or writeZLong for negative numbers [-1894967296]",
      "caused_by" : {
        "type" : "illegal_state_exception",
        "reason" : "Negative longs unsupported, use writeLong or writeZLong for negative numbers [-1894967296]"
      }
    }
  },
  "status" : 500
}
```

Stack trace from my reproduction of the issue:

```
elasticsearch01 | "stacktrace": ["org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed",
elasticsearch01 | "at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:661) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:384) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:693) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:467) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$000(AbstractSearchAsyncAction.java:62) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.innerOnResponse(AbstractSearchAsyncAction.java:307) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:34) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:18) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.search.SearchExecutionStatsCollector.onResponse(SearchExecutionStatsCollector.java:63) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.search.SearchExecutionStatsCollector.onResponse(SearchExecutionStatsCollector.java:25) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:43) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleResponse(SearchTransportService.java:400) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.transport.TransportService$5.handleResponse(TransportService.java:737) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1279) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1357) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1337) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:41) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:32) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:16) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:737) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]",
elasticsearch01 | "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
elasticsearch01 | "at java.lang.Thread.run(Thread.java:831) [?:?]",
elasticsearch01 | "Caused by: org.elasticsearch.ElasticsearchException$1: Negative longs unsupported, use writeLong or writeZLong for negative numbers [-1894967296]",
elasticsearch01 | "at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:633) ~[elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:382) [elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "... 26 more",
elasticsearch01 | "Caused by: java.lang.IllegalStateException: Negative longs unsupported, use writeLong or writeZLong for negative numbers [-1894967296]",
elasticsearch01 | "at org.elasticsearch.common.io.stream.StreamOutput.writeVLong(StreamOutput.java:288) ~[elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.search.aggregations.metrics.TDigestState.write(TDigestState.java:40) ~[elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.search.aggregations.metrics.AbstractInternalTDigestPercentiles.doWriteTo(AbstractInternalTDigestPercentiles.java:54) ~[elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.search.aggregations.InternalAggregation.writeTo(InternalAggregation.java:191) ~[elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:1112) ~[elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteableList(StreamOutput.java:1237) ~[elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.search.aggregations.InternalAggregations.writeTo(InternalAggregations.java:117) ~[elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.common.io.stream.DelayableWriteable.getSerializedSize(DelayableWriteable.java:210) ~[elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.common.io.stream.DelayableWriteable$Referencing.getSerializedSize(DelayableWriteable.java:113) ~[elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.search.QueryPhaseResultConsumer$PendingMerges.ramBytesUsedQueryResult(QueryPhaseResultConsumer.java:283) ~[elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.search.QueryPhaseResultConsumer$PendingMerges.consume(QueryPhaseResultConsumer.java:309) ~[elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.search.QueryPhaseResultConsumer.consumeResult(QueryPhaseResultConsumer.java:110) ~[elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardResult(AbstractSearchAsyncAction.java:551) ~[elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction.onShardResult(SearchQueryThenFetchAsyncAction.java:99) ~[elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.innerOnResponse(AbstractSearchAsyncAction.java:305) ~[elasticsearch-7.15.0.jar:7.15.0]",
elasticsearch01 | "... 22 more"] }
```

**Comment by imotov** [comment]
It is indeed an overflow during centroid calculation, when we calculate count for the centroid we get overflow and negative count. I think the cleanest way to solve this would be to add a check on ingest and not allow histograms where sum of counts exceeds Integer.MAX_VALUE from being ingested. I don't think we can support it otherwise without a significant modification of t-digest library that we use there.

**Comment by not-napoleon** [comment]
Looks like merging digest (a different algorithm for tdigest) might solve this problem.  I've been meaning to convert us over to that for a while anyway.  I'll look into it and see if that fixes this.  

for reference: https://github.com/tdunning/t-digest/issues/81#event-1049957668

**Comment by salvatore-campagna** [comment]
I have done some investigation about this and I have found the following:
* the overflow happens while counting the number of centroids. It is `centroid.count()` in `TdigestState::write` method that is returning a negative number;
* when writing the count to `out` I see we use `out.writeVLong` while the `centroid.count()` method returns an int. Now I can imagine it might be ok to write an int as. long...anyway it is not clear to me why we are doing that? Shouldn't we use `out.writeVInt(centroid.count()`?
* I see in `StreamOutput` that `writeVLong` does a check on the argument being `< 0` and throwing (it throws with the actual error we see in the bug report). I see also that `writeVInt` is not doing the same check. Is there a reason  why the check is there when writing longs and not when writing ints.
* Of course using `out.writeVInt(centroid.count()` instead of `out.writeVLong(centroid.count())` would **fix** the issue since it has no check on the value being negative. ANyway, it looks like to me that this centroid count is not used...is it an issue if we let the negative (incorrect) value **slip through**? According to some tests I have done this value is not exposed to the user...so maybe we don't care if it is correct or not?

**Comment by not-napoleon** [comment]
So, really, this problem is happening when we ingest the histogram.  We just don't see it until we try to serialize it.  Centroid counts should not be negative, that just doesn't make sense in the t-digest algorithm.  Fixing it at write time will only allow us to serialize an already invalid state.

Merging digest half-solves this problem, in that it stores the counts internally as `double`s.  But it still casts them to `int`s when returning the list of centroids, which means we'll be losing data in serialization.  Compounded by the fact that we can't switch to merging digest right now due to an unrelated bug.  T-digest 3.3 doesn't seem to fix this issue either.

In the short term, I think our best fix is to check these values at ingest time and throw then if we detect an overflow.  We shouldn't be letting bad data into the index to begin with.  Probably this should happen in t-digest, so it might be good to submit a PR there and then put in a stop gap fix on our side.  

I'm not sure what a good long term fix to actually support large counts would be.  Let's figure out if that's a real requirement, and depending on how badly we need it we can discuss some options.

> In the read method we actually read an int and not a long state.add(in.readDouble(), in.readVInt());.

That seems weird to me too.  Possibly a bug, definitely worth fixing.  I don't think it solves this issue though, for the reasons listed above.

> Anyway, it looks like to me that this centroid count is not used (excluding the read method)...is it an issue if we let the negative (incorrect) value slip through?

I believe the centroid count is a critical bit of internal state on the t-digest data structure.  It represents the mass of values at that centroid and is used internally for weighting between centroids.  It's true we don't expose this to the user, but only because t-digest itself is an implementation detail we want to hide (mostly).  I am not comfortable saying we can just allow this to be wrong.

**Comment by salvatore-campagna** [comment]
I had another loo at this before starting to work on histograms for downsampling. The overflow issue is not actually happening because of a single histogram value (2100000000) but it is rather the result of internal computations leading to a large value in the number of centroids (in my understanding just the sum of the values in the counts array). As a result, validation on the input is pretty much useless. To be more precise, validation of the input already happens in the `HistogramFieldMapper.java` when doing:

```
counts.add(subParser.intValue());
```

The line above throws if the value does not fit an integer. Both values used in the example triggering the issue are parsed correctly.

I replaced the AVL implementation with a `MergingTDigest` available already in the same library and the issue does not reproduce anymore (after the change). A PR will follow.

**Comment by salvatore-campagna** [comment]
At the end I think the issue here is that internally counts are kept using doubles while `count` (in `centroid.count()`) returns an integer and if the value is too large it just does not fit. I also think that this issue doe not really affect the internal working of tDigest because internally there is no overflow.
