### ISSUE TITLE
[CI] ArchiveTests test32SpecialCharactersInJdkPath failing

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#80183]
This test failed on windows today.

**Build scan:**
https://gradle-enterprise.elastic.co/s/b4b3qcqdg4xzo/tests/:qa:os:destructiveDistroTest.default-windows-archive/org.elasticsearch.packaging.test.ArchiveTests/test32SpecialCharactersInJdkPath

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.ArchiveTests&tests.test=test32SpecialCharactersInJdkPath

**Failure excerpt:**
```
java.lang.RuntimeException: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\a (special) path -> C:\tmp\elasticsearch\jdk

  at __randomizedtesting.SeedInfo.seed([6697705A889E9A84:129460B6892CF05F]:0)
  at org.elasticsearch.packaging.util.FileUtils.mv(FileUtils.java:136)
  at org.elasticsearch.packaging.test.ArchiveTests.test32SpecialCharactersInJdkPath(ArchiveTests.java:128)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.nio.file.AccessDeniedException: C:\tmp\elasticsearch\a (special) path -> C:\tmp\elasticsearch\jdk

    at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
    at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
    at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:403)
    at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293)
    at java.nio.file.Files.move(Files.java:1432)
    at org.elasticsearch.packaging.util.FileUtils.mv(FileUtils.java:134)
    at org.elasticsearch.packaging.test.ArchiveTests.test32SpecialCharactersInJdkPath(ArchiveTests.java:128)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:568)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by mark-vieira** [comment]
Haven't seen another failure since this one so I'm closing for now. We can reopen if we encounter this again.
