### ISSUE TITLE
[CI] DocsClientYamlTestSuiteIT test {yaml=reference/text-structure/apis/find-structure/line_250} failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#80438]
Didn't reproduce for me but this has failed three times today with the same error.

**Build scan:**
https://gradle-enterprise.elastic.co/s/qm2in5o67wmkk/tests/:docs:integTest/org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT/test%20%7Byaml=reference%2Ftext-structure%2Fapis%2Ffind-structure%2Fline_250%7D

**Reproduction line:**
`./gradlew ':docs:integTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/text-structure/apis/find-structure/line_250}" -Dtests.seed=ADF5CCA552FF2C7D -Dtests.locale=en -Dtests.timezone=Asia/Muscat -Druntime.java=17`

**Applicable branches:**
master, 8.0

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT&tests.test=test%20%7Byaml%3Dreference/text-structure/apis/find-structure/line_250%7D

**Failure excerpt:**
```
java.lang.AssertionError: Failure at [reference/text-structure/apis/find-structure:285]: Expected a map containing
          acknowledged: expected <true> but was <missing>
    num_lines_analyzed: <unexpected> but was <24>
 num_messages_analyzed: <unexpected> but was <24>
          sample_start: <unexpected> but was "{\"release_date\":\"2011-06-02\",\"author\":\"James S.A. Corey\",\"name\":\"Leviathan Wakes\",\"page_count\":561}\n{\"release_date\":\"1989-05-26\",\"author\":\"Dan Simmons\",\"name\":\"Hyperion\",\"page_count\":482}\n"
               charset: <unexpected> but was "UTF-8"
 has_byte_order_marker: <unexpected> but was <false>
                format: <unexpected> but was "ndjson"
       timestamp_field: <unexpected> but was "release_date"
joda_timestamp_formats: <unexpected> but was <[ISO8601]>
java_timestamp_formats: <unexpected> but was <[ISO8601]>
  need_client_timezone: <unexpected> but was <true>
              mappings: <unexpected> but was <{properties={@timestamp={type=date}, author={type=keyword}, name={type=keyword}, page_count={type=long}, release_date={type=date, format=iso8601}}}>
       ingest_pipeline: <unexpected> but was <{description=Ingest pipeline created by text structure finder, processors=[{date={field=release_date, timezone={{ event.timezone }}, formats=[ISO8601]}}]}>
           field_stats: <unexpected> but was <{author={count=24, cardinality=20, top_hits=[{value=Frank Herbert, count=4}, {value=Robert A. Heinlein, count=2}, {value=Alastair Reynolds, count=1}, {value=Aldous Huxley, count=1}, {value=Dan Simmons, count=1}, {value=Douglas Adams, count=1}, {value=George Orwell, count=1}, {value=Iain M. Banks, count=1}, {value=Isaac Asimov, count=1}, {value=James S.A. Corey, count=1}]}, name={count=24, cardinality=24, top_hits=[{value=1984, count=1}, {value=A Fire Upon the Deep, count=1}, {value=Brave New World, count=1}, {value=Children of Dune, count=1}, {value=Consider Phlebas, count=1}, {value=Dune, count=1}, {value=Dune Messiah, count=1}, {value=Ender's Game, count=1}, {value=Fahrenheit 451, count=1}, {value=Foundation, count=1}]}, page_count={count=24, cardinality=24, min_value=180, max_value=768, mean_value=387.0833333333333, median_value=329.5, top_hits=[{value=180, count=1}, {value=208, count=1}, {value=224, count=1}, {value=227, count=1}, {value=268, count=1}, {value=271, count=1}, {value=275, count=1}, {value=288, count=1}, {value=304, count=1}, {value=311, count=1}]}, release_date={count=24, cardinality=20, earliest=1932-06-01, latest=2011-06-02, top_hits=[{value=1985-06-01, count=3}, {value=1969-06-01, count=2}, {value=1992-06-01, count=2}, {value=1932-06-01, count=1}, {value=1951-06-01, count=1}, {value=1953-10-15, count=1}, {value=1959-12-01, count=1}, {value=1965-06-01, count=1}, {value=1966-04-01, count=1}, {value=1969-10-15, count=1}]}}>

  at __randomizedtesting.SeedInfo.seed([ADF5CCA552FF2C7D:25A1F37FFC034185]:0)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:489)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:462)
  at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(null:-1)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.lang.AssertionError: Expected a map containing
            acknowledged: expected <true> but was <missing>
      num_lines_analyzed: <unexpected> but was <24>
   num_messages_analyzed: <unexpected> but was <24>
            sample_start: <unexpected> but was "{\"release_date\":\"2011-06-02\",\"author\":\"James S.A. Corey\",\"name\":\"Leviathan Wakes\",\"page_count\":561}\n{\"release_date\":\"1989-05-26\",\"author\":\"Dan Simmons\",\"name\":\"Hyperion\",\"page_count\":482}\n"
                 charset: <unexpected> but was "UTF-8"
   has_byte_order_marker: <unexpected> but was <false>
                  format: <unexpected> but was "ndjson"
         timestamp_field: <unexpected> but was "release_date"
  joda_timestamp_formats: <unexpected> but was <[ISO8601]>
  java_timestamp_formats: <unexpected> but was <[ISO8601]>
    need_client_timezone: <unexpected> but was <true>
                mappings: <unexpected> but was <{properties={@timestamp={type=date}, author={type=keyword}, name={type=keyword}, page_count={type=long}, release_date={type=date, format=iso8601}}}>
         ingest_pipeline: <unexpected> but was <{description=Ingest pipeline created by text structure finder, processors=[{date={field=release_date, timezone={{ event.timezone }}, formats=[ISO8601]}}]}>
             field_stats: <unexpected> but was <{author={count=24, cardinality=20, top_hits=[{value=Frank Herbert, count=4}, {value=Robert A. Heinlein, count=2}, {value=Alastair Reynolds, count=1}, {value=Aldous Huxley, count=1}, {value=Dan Simmons, count=1}, {value=Douglas Adams, count=1}, {value=George Orwell, count=1}, {value=Iain M. Banks, count=1}, {value=Isaac Asimov, count=1}, {value=James S.A. Corey, count=1}]}, name={count=24, cardinality=24, top_hits=[{value=1984, count=1}, {value=A Fire Upon the Deep, count=1}, {value=Brave New World, count=1}, {value=Children of Dune, count=1}, {value=Consider Phlebas, count=1}, {value=Dune, count=1}, {value=Dune Messiah, count=1}, {value=Ender's Game, count=1}, {value=Fahrenheit 451, count=1}, {value=Foundation, count=1}]}, page_count={count=24, cardinality=24, min_value=180, max_value=768, mean_value=387.0833333333333, median_value=329.5, top_hits=[{value=180, count=1}, {value=208, count=1}, {value=224, count=1}, {value=227, count=1}, {value=268, count=1}, {value=271, count=1}, {value=275, count=1}, {value=288, count=1}, {value=304, count=1}, {value=311, count=1}]}, release_date={count=24, cardinality=20, earliest=1932-06-01, latest=2011-06-02, top_hits=[{value=1985-06-01, count=3}, {value=1969-06-01, count=2}, {value=1992-06-01, count=2}, {value=1932-06-01, count=1}, {value=1951-06-01, count=1}, {value=1953-10-15, count=1}, {value=1959-12-01, count=1}, {value=1965-06-01, count=1}, {value=1966-04-01, count=1}, {value=1969-10-15, count=1}]}}>

    at io.github.nik9000.mapmatcher.MapMatcher.assertMap(MapMatcher.java:79)
    at io.github.nik9000.mapmatcher.MapMatcher.assertMap(MapMatcher.java:62)
    at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:94)
    at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:478)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:462)
    at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(null:-1)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:568)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by lcawl** [comment]
Seems same as https://github.com/elastic/elasticsearch/issues/80409

**Comment by mark-vieira** [comment]
Thanks Lisa, I'll close this one in favor of the existing one.
