### ISSUE TITLE
[CI] DocsClientYamlTestSuiteIT test {yaml=reference/ml/anomaly-detection/ml-configuring-aggregations/line_159} failing

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#80622]
**Build scan:**
https://gradle-enterprise.elastic.co/s/mjohvjdhbvmw6/tests/:docs:integTest/org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT/test%20%7Byaml=reference%2Fml%2Fanomaly-detection%2Fml-configuring-aggregations%2Fline_159%7D

**Reproduction line:**
`./gradlew ':docs:integTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/ml/anomaly-detection/ml-configuring-aggregations/line_159}" -Dtests.seed=282ED9D85BC4C7C7 -Dtests.locale=cs-CZ -Dtests.timezone=Pacific/Funafuti -Druntime.java=17`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT&tests.test=test%20%7Byaml%3Dreference/ml/anomaly-detection/ml-configuring-aggregations/line_159%7D

**Failure excerpt:**
```
java.lang.AssertionError: Failure at [reference/ml/anomaly-detection/ml-configuring-aggregations:131]: Expected a map containing
                             acknowledged: expected <true> but was <missing>
                                   job_id: <unexpected> but was "farequote-composite"
                                 job_type: <unexpected> but was "anomaly_detector"
                              job_version: <unexpected> but was "8.1.0"
                              create_time: <unexpected> but was <1636538928192L>
                          datafeed_config: <unexpected> but was <{datafeed_id=farequote-composite, job_id=farequote-composite, query_delay=104306ms, chunking_config={mode=off}, indices_options={expand_wildcards=[open], ignore_unavailable=false, allow_no_indices=true, ignore_throttled=true}, query={match_all={}}, indices=[farequote], aggregations={buckets={composite={size=1000, sources=[{time_bucket={date_histogram={fixed_interval=360s, field=time, time_zone=UTC}}}, {airline={terms={field=airline}}}]}, aggregations={responsetime={avg={field=responsetime}}, time={max={field=time}}}}}, scroll_size=1000, delayed_data_check_config={enabled=true}}>
                          analysis_config: <unexpected> but was <{bucket_span=60m, summary_count_field_name=doc_count, detectors=[{detector_description=mean(responsetime) by airline, function=mean, field_name=responsetime, by_field_name=airline, detector_index=0}], influencers=[]}>
                          analysis_limits: <unexpected> but was <{model_memory_limit=1024mb, categorization_examples_limit=4}>
                         data_description: <unexpected> but was <{time_field=time, time_format=epoch_ms}>
            model_snapshot_retention_days: <unexpected> but was <10>
daily_model_snapshot_retention_after_days: <unexpected> but was <1>
                       results_index_name: <unexpected> but was "shared"
                          allow_lazy_open: <unexpected> but was <false>

  at __randomizedtesting.SeedInfo.seed([282ED9D85BC4C7C7:A07AE602F538AA3F]:0)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:489)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:462)
  at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(null:-1)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.lang.AssertionError: Expected a map containing
                               acknowledged: expected <true> but was <missing>
                                     job_id: <unexpected> but was "farequote-composite"
                                   job_type: <unexpected> but was "anomaly_detector"
                                job_version: <unexpected> but was "8.1.0"
                                create_time: <unexpected> but was <1636538928192L>
                            datafeed_config: <unexpected> but was <{datafeed_id=farequote-composite, job_id=farequote-composite, query_delay=104306ms, chunking_config={mode=off}, indices_options={expand_wildcards=[open], ignore_unavailable=false, allow_no_indices=true, ignore_throttled=true}, query={match_all={}}, indices=[farequote], aggregations={buckets={composite={size=1000, sources=[{time_bucket={date_histogram={fixed_interval=360s, field=time, time_zone=UTC}}}, {airline={terms={field=airline}}}]}, aggregations={responsetime={avg={field=responsetime}}, time={max={field=time}}}}}, scroll_size=1000, delayed_data_check_config={enabled=true}}>
                            analysis_config: <unexpected> but was <{bucket_span=60m, summary_count_field_name=doc_count, detectors=[{detector_description=mean(responsetime) by airline, function=mean, field_name=responsetime, by_field_name=airline, detector_index=0}], influencers=[]}>
                            analysis_limits: <unexpected> but was <{model_memory_limit=1024mb, categorization_examples_limit=4}>
                           data_description: <unexpected> but was <{time_field=time, time_format=epoch_ms}>
              model_snapshot_retention_days: <unexpected> but was <10>
  daily_model_snapshot_retention_after_days: <unexpected> but was <1>
                         results_index_name: <unexpected> but was "shared"
                            allow_lazy_open: <unexpected> but was <false>

    at io.github.nik9000.mapmatcher.MapMatcher.assertMap(MapMatcher.java:79)
    at io.github.nik9000.mapmatcher.MapMatcher.assertMap(MapMatcher.java:62)
    at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:94)
    at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:478)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:462)
    at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(null:-1)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:568)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
    at java.lang.Thread.run(Thread.java:833)

```

**Comment by droberts195** [comment]
This is exactly the same problem as https://github.com/elastic/elasticsearch/issues/80409#issuecomment-961885589, but on a different test: the test thinks it's expecting an `AcknowledgedResponse` when actually it's expecting a complex response _and gets it_.

So it seems to be a framework problem rather than something about this particular test.

**Comment by benwtrent** [comment]
Doesn't seem to have failed in the same way for some time. Closing
