### ISSUE TITLE
The doc should be discarded before writing to lucene if the length of keyword field is bigger than 32766.

### ISSUE THREAD

**Issue by kkewwei** [elastic/elasticsearch#80865]
It’s known that if the length of keyword field is bigger than 32766, Lucene will throw the exception:
```
java.lang.IllegalArgumentException: Document contains at least one immense term in field="keyword1" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[-26, -97, -81, -26, -97, -81, -26, -97, -81, -26, -97, -81, -26, -97, -81, -26, -97, -81, -26, -97, -81, -26, -97, -81, -26, -97, -81, -26, -97, -81]...', original message: bytes can be at most 32766 in length; got 98301
```
After throwing the exception, Lucene will mark it to be deleted, and delete it in the process of merge. 

We know that the types of compressingStoredFields include the following:
1.MergeStrategy.DOC
2.MergeStrategy.BULK
3.MergeStrategy.VISITOR
see: https://github.com/apache/lucene/blob/ad911df2605591a63ca58d237182f84aa8384325/lucene/core/src/java/org/apache/lucene/codecs/lucene90/compressing/Lucene90CompressingStoredFieldsWriter.java#L686

As long as the current `chunk` contains one deleted doc, the merge type of the chunk will change from `bulk` to `doc`, which becomes very inefficient. After our test, we find that the `doc` merge type efficiency will be reduced by 25%+ .

If we should discard the doc in ES engine, rather than  Lucene engine.

**Comment by kkewwei** [comment]
@jtibshirani can you please comfirm it? It indeed can speed up merge when the length of keyword field is bigger than 32766.

**Comment by jtibshirani** [comment]
> After throwing the exception, Lucene will mark it to be deleted, and delete it in the process of merge.

This is not my understanding of what happens. If that exception is encountered during indexing, then Lucene will refuse to index the document. So the Elasticsearch index request should just fail. There shouldn't be deleted documents left around because of this failure.

Are you observing some surprising behavior, where you unexpectedly see deleted documents? It'd be helpful to describe your set-up the behavior you're observing (best case with a simple reproduction). I might be missing some important detail.

**Comment by kkewwei** [comment]
We can see that it is indeed that lucene will throw the exception:
```
[2022-01-20T15:58:33,185][DEBUG][o.e.a.b.TransportShardBulkAction] [node-1] [test3][0] failed to execute bulk item (index) index {[test3][_doc][XLp-dn4B_5pZwVi2kH-g], source[n/a, actual length: [96kb], max length: 2kb]}
java.lang.IllegalArgumentException: Document contains at least one immense term in field="field2" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[-26, -97, -81, -26, -97, -81, -26, -97, -81, -26, -97, -81, -26, -97, -81, -26, -97, -81, -26, -97, -81, -26, -97, -81, -26, -97, -81, -26, -97, -81]...', original message: bytes can be at most 32766 in length; got 98301
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:948) ~[lucene-core-8.6.2.jar:8.6.2 3ba7dea7ab12f29da634f4a638a6541838174327 - kkewwei - 2022-01-20 15:33:28]
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:501) ~[lucene-core-8.6.2.jar:8.6.2 3ba7dea7ab12f29da634f4a638a6541838174327 - kkewwei - 2022-01-20 15:33:28]
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:465) ~[lucene-core-8.6.2.jar:8.6.2 3ba7dea7ab12f29da634f4a638a6541838174327 - kkewwei - 2022-01-20 15:33:28]
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocuments(DocumentsWriterPerThread.java:237) ~[lucene-core-8.6.2.jar:8.6.2 3ba7dea7ab12f29da634f4a638a6541838174327 - kkewwei - 2022-01-20 15:33:28]
	at org.apache.lucene.index.DocumentsWriter.updateDocuments(DocumentsWriter.java:419) ~[lucene-core-8.6.2.jar:8.6.2 3ba7dea7ab12f29da634f4a638a6541838174327 - kkewwei - 2022-01-20 15:33:28]
	at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1335) ~[lucene-core-8.6.2.jar:8.6.2 3ba7dea7ab12f29da634f4a638a6541838174327 - kkewwei - 2022-01-20 15:33:28]
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1621) ~[lucene-core-8.6.2.jar:8.6.2 3ba7dea7ab12f29da634f4a638a6541838174327 - kkewwei - 2022-01-20 15:33:28]
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1264) ~[lucene-core-8.6.2.jar:8.6.2 3ba7dea7ab12f29da634f4a638a6541838174327 - kkewwei - 2022-01-20 15:33:28]
	at org.elasticsearch.index.engine.InternalEngine.addDocs(InternalEngine.java:1158) ~[classes/:?]
	at org.elasticsearch.index.engine.InternalEngine.indexIntoLucene(InternalEngine.java:1095) ~[classes/:?]
	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:935) ~[classes/:?]
	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:819) ~[classes/:?]
	at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:791) ~[classes/:?]
	at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:748) ~[classes/:?]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:275) [classes/:?]
	at org.elasticsearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:165) [classes/:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [classes/:?]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:210) [classes/:?]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:116) [classes/:?]
	at org.elasticsearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:82) [classes/:?]
	at org.elasticsearch.action.support.replication.TransportWriteAction$1.doRun(TransportWriteAction.java:161) [classes/:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:710) [classes/:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException: bytes can be at most 32766 in length; got 98301
	at org.apache.lucene.util.BytesRefHash.add(BytesRefHash.java:270) ~[lucene-core-8.6.2.jar:8.6.2 3ba7dea7ab12f29da634f4a638a6541838174327 - kkewwei - 2022-01-20 15:33:28]
	at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:177) ~[lucene-core-8.6.2.jar:8.6.2 3ba7dea7ab12f29da634f4a638a6541838174327 - kkewwei - 2022-01-20 15:33:28]
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:938) ~[lucene-core-8.6.2.jar:8.6.2 3ba7dea7ab12f29da634f4a638a6541838174327 - kkewwei - 2022-01-20 15:33:28]
	... 25 more
```

> After throwing the exception Lucene will mark it to be deleted. 
for example, the deleted document is as follow:
```
{
    "field1":"word",
    "field2":"word1 word1 word1 ......"      //  whose UTF8 encoding is longer than the max length 32766
}
```
the order of fields writing is: field1->field2. First, lucene processes `field1`, write it into memory index buffer, these operations are not rollbackable, because the data struct has changed, second lucene processes `field2`, find it bigger than 32766, lucene fails to write, and throw the exception, as writing `field1`is irreversible, lucene can't ignore it, so lucene marks it to be deleted.

**Comment by ywelsch** [comment]
@kkewwei Thanks for explaining how we arrive at the deleted docs. I think what you're suggesting makes sense to explore. Would you be interested in working on a PR?

Note that a good workaround for your current indexing pipeline would be to set `ignore_above` appropriately.

**Comment by kkewwei** [comment]
It's my pleasure to do it, thank you for the your idea.

**Comment by kkewwei** [comment]
I plan to set default value of `ignore_above` to be 32766(current default value is Integer.MAX_VALUE), and check the utf8 length of value here:
https://github.com/elastic/elasticsearch/blob/0a93df1e736461397a8c89801130e118e041399f/server/src/main/java/org/elasticsearch/index/mapper/KeywordFieldMapper.java#L913

@ywelsch, I have a little doubt about using ignore_above here, If user doesn't set `ignore_above`, and the field is discarded because of the case, ES doesn't throw exception, in that way, it seems not very user-friendly to swallow the user's data without the user's perception.

If we just check the utf8 length of value here, and  don't use  ignore_above. It seems be better. https://github.com/elastic/elasticsearch/blob/0a93df1e736461397a8c89801130e118e041399f/server/src/main/java/org/elasticsearch/index/mapper/KeywordFieldMapper.java#L913

**Comment by ywelsch** [comment]
> If we just check the utf8 length of value here

Adding this check looks reasonable to me.
