### ISSUE TITLE
Elasticsearch fails to generate kibana enrollment token on startup

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#80922]
This has been reported a couple of times already but I have been unable to figure out why it happens or reproduce it. The manifestation is that elasticsearch fails to generate and output a kibana enrollment token on startup and the following is logged:

```

[2021-11-19T13:14:07,824][ERROR][o.e.x.s.e.InternalEnrollmentTokenGenerator] [xxxxxxx] Failed to create enrollment when extracting HTTPS bound addresses
java.lang.NullPointerException: Cannot invoke "org.elasticsearch.http.HttpInfo.getAddress()" because "httpInfo" is null
	at org.elasticsearch.xpack.security.enrollment.InternalEnrollmentTokenGenerator.getAllHttpAddresses(InternalEnrollmentTokenGenerator.java:188) ~[x-pack-security-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.xpack.security.enrollment.InternalEnrollmentTokenGenerator.assembleToken(InternalEnrollmentTokenGenerator.java:160) [x-pack-security-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.xpack.security.enrollment.InternalEnrollmentTokenGenerator.lambda$createKibanaEnrollmentToken$3(InternalEnrollmentTokenGenerator.java:127) [x-pack-security-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:136) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:31) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:107) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:176) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:170) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:31) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$2(SecurityActionFilter.java:171) [x-pack-security-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.action.ActionListener$DelegatingFailureActionListener.onResponse(ActionListener.java:219) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:447) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.action.support.nodes.TransportNodesAction.newResponseAsync(TransportNodesAction.java:181) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.action.support.nodes.TransportNodesAction.newResponse(TransportNodesAction.java:156) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.lambda$finishHim$0(TransportNodesAction.java:291) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:712) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

The relevant code is 

```java 
final NodesInfoRequest nodesInfoRequest = new NodesInfoRequest().nodesIds("_local")
            .addMetric(NodesInfoRequest.Metric.HTTP.metricName());
client.execute(NodesInfoAction.INSTANCE, nodesInfoRequest, ActionListener.wrap(response -> {
            assert response.getNodes().size() == 1;
            NodeInfo nodeInfo = response.getNodes().get(0);
            assembleToken(EnrollmentTokenType.KIBANA, nodeInfo.getInfo(HttpInfo.class), consumer);
}, e -> {
            LOGGER.error("Failed to create kibana enrollment token when retrieving local nodes HTTP info", e);
            consumer.accept(null);
}));
```

- we know it is a single node cluster and we ask the `_local` node. 
- we pass the HTTP metric in the request

For httpInfo to be null ( https://github.com/elastic/elasticsearch/blob/12ad399c488f0cc60e19b5e1b29c6d569cb4351a/server/src/main/java/org/elasticsearch/node/NodeService.java#L119) either HttpServerTransport is null and I can't see how this could be the case with default settings or (and most likely) this is a race and https://github.com/elastic/elasticsearch/blob/5e98ea427bc8bbc0120b099e501f425f1880a7b7/server/src/main/java/org/elasticsearch/http/AbstractHttpServerTransport.java#L155 hasn't finished yet so boundAddress is still `null`

Getting the full logs from a node where that happens will be helpful

**Comment by jkakavas** [comment]
Got hold of additional logs from a manifestation of the bug which seems to indicate this is actually a race condition: 

```
[2021-11-19T13:14:07,783][INFO ][o.e.g.GatewayService     ] [macbook-pro-aris.home] recovered [0] indices into cluster_state
[2021-11-19T13:14:07,824][ERROR][o.e.x.s.e.InternalEnrollmentTokenGenerator] [xxxxx] Failed to create enrollment when extracting HTTPS bound addresses
<stacktrace removed> 
[2021-11-19T13:14:07,925][INFO ][o.e.c.m.MetadataIndexTemplateService] [xxxxx] adding template [.monitoring-kibana] for index patterns [.monitoring-kibana-7-*]
[2021-11-19T13:14:08,033][INFO ][o.e.c.m.MetadataIndexTemplateService] [xxxxx] adding template [.monitoring-logstash] for index patterns [.monitoring-logstash-7-*]
[2021-11-19T13:14:08,174][INFO ][o.e.c.m.MetadataIndexTemplateService] [xxxxx] adding template [.monitoring-alerts-7] for index patterns [.monitoring-alerts-7]
[2021-11-19T13:14:08,257][INFO ][o.e.h.AbstractHttpServerTransport] [xxxxx] publish_address {192.168.1.9:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}, {192.168.1.9:9200}
[2021-11-19T13:14:08,258][INFO ][o.e.n.Node               ] [xxxxx] started
```

https://github.com/elastic/elasticsearch/blob/5e98ea427bc8bbc0120b099e501f425f1880a7b7/server/src/main/java/org/elasticsearch/http/AbstractHttpServerTransport.java#L179 is 

```
[2021-11-19T13:14:08,257][INFO ][o.e.h.AbstractHttpServerTransport] [xxxxx] publish_address {192.168.1.9:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}, {192.168.1.9:9200}
```

It looks like triggering the token generation on recovering the cluster state is not a sufficient guard, we need to reconsider
