### ISSUE TITLE
java.nio.file.NoSuchFileException: ... /.attach_pid 

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#80943]
**Build scan**:

https://gradle-enterprise.elastic.co/s/fuew44mslhbog
https://gradle-enterprise.elastic.co/s/qk7jlgthv3g7a
https://gradle-enterprise.elastic.co/s/htw42u5uxpl7e
https://gradle-enterprise.elastic.co/s/kqpkhzgtqbdkg
https://gradle-enterprise.elastic.co/s/pybf7lmdvlxqs

**Repro line**:

Not avaliable

**Reproduces locally?**:

No

**Applicable branches**:

master

**Failure history**:

I am not sure how to find stats for this. Found above 5 build failures just by scrolling #es-test-triage so I assume this is happening at least couple of times per week.

UPD: https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20%27:x-pack:plugin:async-search:qa:rest:yamlRestTest%27.%0A%3E%20java.nio.file.NoSuchFileException:%20/var/lib/jenkins/workspace/elastic%2Belasticsearch%2Bmaster%2Bmultijob%2Bplatform-support-unix/os/*/distribution/archives/linux-tar/build/install/elasticsearch-8.1.0-SNAPSHOT/*&search.relativeStartTime=P28D&search.timeZoneId=Europe/Berlin

**Failure excerpt**:

<details>
  <summary>Failure stack trace</summary>
  
  ```
Caused by: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /var/lib/jenkins/workspace/elastic+elasticsearch+7.16+multijob+platform-support-unix/os/ubuntu-16.04&&immutable/distribution/archives/linux-tar/build/install/elasticsearch-7.16.0-SNAPSHOT/.attach_pid322537	
at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:87)	
at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:103)	
at java.util.Iterator.forEachRemaining(Iterator.java:132)	
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)	
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)	
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)	
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)	
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)	
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)	
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)	
at org.elasticsearch.gradle.testclusters.ElasticsearchNode.sync(ElasticsearchNode.java:1194)	
at org.elasticsearch.gradle.testclusters.ElasticsearchNode.syncWithLinks(ElasticsearchNode.java:1171)	
at org.elasticsearch.gradle.testclusters.ElasticsearchNode.setupNodeDistribution(ElasticsearchNode.java:1150)	
at org.elasticsearch.gradle.testclusters.ElasticsearchNode.start(ElasticsearchNode.java:510)
  ```
  
</details>

**Comment by idegtiarenko** [comment]
I suspect this could happen if the directory or one of the files from

https://github.com/elastic/elasticsearch/blob/62d2df4f6a6399ea964afe436c627f902ea808d6/build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java#L1155-L1156

is concurrently removed

**Comment by markharwood** [comment]
Looks like another case today https://gradle-enterprise.elastic.co/s/5th7cmf7s3gxe
