### ISSUE TITLE
ElasticsearchException.toXContent incorrectly serializes cause and supressed stack traces

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#80983]
When serializing `ElasticsearchException` using `REST_EXCEPTION_SKIP_STACK_TRACE=false` then cause and each suppressed stack trace is written in resulted json twice.

Suppressed stack traces are written in `suppressed` array as well as appended to `stacktrace`. Same is true for the cause stack trace.

This might result in huge json when exception has multiple causes.

**Steps to reproduce**:

```
ToXContent.Params params = new ToXContent.MapParams(
    Map.of(ElasticsearchException.REST_EXCEPTION_SKIP_STACK_TRACE, "false")
);

var cause = new RuntimeException("cause");
var suppressed1 = new RuntimeException("suppressed1");
var suppressed2 = new RuntimeException("suppressed2");

var exception = new ElasticsearchException("exception", cause);
exception.addSuppressed(suppressed1);
exception.addSuppressed(suppressed2);

XContentBuilder builder = XContentFactory.jsonBuilder();
builder.startObject();
exception.toXContent(builder, params);
builder.endObject();
```

<details>
  <summary>Sample output</summary>
  
  ```
{
  "type": "exception",
  "reason": "exception",
  "caused_by": {
    "type": "runtime_exception",
    "reason": "cause",
    "stack_trace": "java.lang.RuntimeException: cause
  at org.elasticsearch.ElasticsearchExceptionTests.testToXContentWithCauseAndSuppressed(ElasticsearchExceptionTests.java:964)
...
  at java.base/java.lang.Thread.run(Thread.java:833)
"
  },
  "stack_trace": "org.elasticsearch.ElasticsearchException: exception
  at org.elasticsearch.ElasticsearchExceptionTests.testToXContentWithCauseAndSuppressed(ElasticsearchExceptionTests.java:968)
...
  at java.base/java.lang.Thread.run(Thread.java:833)
  Suppressed: java.lang.RuntimeException: suppressed1 <--------------------
    at org.elasticsearch.ElasticsearchExceptionTests.testToXContentWithCauseAndSuppressed(ElasticsearchExceptionTests.java:965)
    ... 38 more
  Suppressed: java.lang.RuntimeException: suppressed2 <--------------------
    at org.elasticsearch.ElasticsearchExceptionTests.testToXContentWithCauseAndSuppressed(ElasticsearchExceptionTests.java:966)
    ... 38 more
Caused by: java.lang.RuntimeException: cause <--------------------
  at org.elasticsearch.ElasticsearchExceptionTests.testToXContentWithCauseAndSuppressed(ElasticsearchExceptionTests.java:964)
  ... 38 more
",
  "suppressed": [
    {
      "type": "runtime_exception",
      "reason": "suppressed1",
      "stack_trace": "java.lang.RuntimeException: suppressed1
  at org.elasticsearch.ElasticsearchExceptionTests.testToXContentWithCauseAndSuppressed(ElasticsearchExceptionTests.java:965)
...
  at java.base/java.lang.Thread.run(Thread.java:833)
"
    },
    {
      "type": "runtime_exception",
      "reason": "suppressed2",
      "stack_trace": "java.lang.RuntimeException: suppressed2
  at org.elasticsearch.ElasticsearchExceptionTests.testToXContentWithCauseAndSuppressed(ElasticsearchExceptionTests.java:966)
...
  at java.base/java.lang.Thread.run(Thread.java:833)
"
    }
  ]
}
  ```
  
</details>

**Comment by idegtiarenko** [comment]
Following classes declare: `REST_EXCEPTION_SKIP_STACK_TRACE = "false"`, and would have stack traces duplicated:
* org.elasticsearch.xpack.ilm.history.ILMHistoryItem
* org.elasticsearch.xpack.ilm.IndexLifecycleTransition
* org.elasticsearch.xpack.core.watcher.history.WatchRecord.ExceptionWatchRecord
