### ISSUE TITLE
[CI] CertGenCliTests test40RunWithCert failure

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#81035]
**Build scan**: https://gradle-enterprise.elastic.co/s/4jr4pm6rjlav6

**Repro line**:

**Reproduces locally?**: 

**Applicable branches**: 7.16

**Failure excerpt**:

```
Tests with failures:
 - org.elasticsearch.packaging.test.CertGenCliTests.test40RunWithCert

171 tests completed, 1 failed, 166 skipped
:qa:os:destructiveDistroTest.default-rpm-aarch64#deps
:qa:os:destructiveDistroTest.default-rpm-aarch64 SKIPPED
:qa:os:destructiveDistroTest.default-rpm-no-jdk#deps
:qa:os:destructiveDistroTest.default-rpm-no-jdk FAILED

org.elasticsearch.packaging.test.CertGenCliTests > test40RunWithCert FAILED
    org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c systemctl enable elasticsearch.service]
       result: exitCode = [1] stdout = [] stderr = [Synchronizing state of elasticsearch.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
    Executing: /usr/lib/systemd/systemd-sysv-install enable elasticsearch
    /sbin/insserv: No such file or directory]
        at __randomizedtesting.SeedInfo.seed([59FBD2A988A82E2C:C194DFEB90E917D8]:0)
        at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:147)
        at org.elasticsearch.packaging.util.Shell.run(Shell.java:73)
        at org.elasticsearch.packaging.util.Packages.runElasticsearchStartCommand(Packages.java:259)
        at org.elasticsearch.packaging.test.PackagingTestCase.runElasticsearchStartCommand(PackagingTestCase.java:309)
        at org.elasticsearch.packaging.test.PackagingTestCase.assertWhileRunning(PackagingTestCase.java:254)
        at org.elasticsearch.packaging.test.CertGenCliTests.test40RunWithCert(CertGenCliTests.java:109)
```

**Comment by astefan** [comment]
Another one: https://gradle-enterprise.elastic.co/s/nvivzu6pmswg4/
Same OS - SLES-15 - different branch - 7.15.

**Comment by mark-vieira** [comment]
I don't think this is relevant anymore. I've not seen any failures on the 7.17 branch in the last month.
